### ISSUE TITLE
Requires babel?

### ISSUE THREAD

**Issue by matthewp** [parcel-bundler/parcel#1]
Hello, cool project. I tried running this on one of my projects and encountered an error ` Unknown plugin "transform-es2015-modules-commonjs" specified in "base" at 0, attempted to resolve relative to "/Users/matthew/dev/my-project"`

I think it is looking up this plugin within my project, but I did not have this plugin (or any babel plugin) installed. This project uses ES import/export syntax. Is Babel usage required at this time?

**Comment by devongovett** [comment]
Ah thanks. Babel is used internally to compile es2015 imports to require statements. Probably need to resolve the module locally to parcel instead of the project here https://github.com/parcel-bundler/parcel/blob/master/src/transforms/babel.js#L18

**Comment by devongovett** [comment]
Published v1.0.1 which should fix this issue.

**Comment by tnrich** [comment]
Hey there, I'm seeing this error: 
```
/Users/tnrich/Sites/lims/node_modules/teselagen-react-components/lib/index.js: Couldn't find preset "stage-0" relative to directory"/Users/tnrich/Sites/lims/node_modules/teselagen-react-components"
```

any thoughts as to why it would be trying to look for babel presets in there? The code in /lib of that node_module is already compiled as far as I know. Thanks!

**Comment by spalger** [comment]
@tnrich Checkout https://github.com/parcel-bundler/parcel/issues/13
