### ISSUE TITLE
Report build errors to the browser?

### ISSUE THREAD

**Issue by spalger** [parcel-bundler/parcel#100]
This has happened to me more than a couple times:

 - make some changes
 - switch to the browser
 - wonder why my changes are showing up
 - switch back and forth, refresh
 - checked the console and realized the build was failing

Perhaps parcel could notify the browser on build failures via the HMR socket, or refuse to serve the build assets if the build failed?

**Comment by devongovett** [comment]
Great idea! Want to take a stab at it? Relevant files are:

https://github.com/parcel-bundler/parcel/blob/master/src/HMRServer.js
https://github.com/parcel-bundler/parcel/blob/master/src/Bundler.js#L134

**Comment by ajaymathur** [comment]
@spalger can I take a look at it? 🙂

**Comment by spalger** [comment]
@ajaymathur this is what I have currently https://github.com/parcel-bundler/parcel/compare/master...spalger:notify-browser-on-error

**Comment by ajaymathur** [comment]
sweet 💯

**Comment by thejameskyle** [comment]
Moving to #104
