### ISSUE TITLE
WebSocket connection to 'ws://localhost:59402/' failed: Error during WebSocket handshake: Unexpected response code: 503

### ISSUE THREAD

**Issue by sowdf** [parcel-bundler/parcel#1001]
WebSocket connection to 'ws://localhost:59402/' failed: Error during WebSocket handshake: Unexpected response code: 503

**Comment by davidnagli** [comment]
Please fill out the issue template

**Comment by DeMoorJasper** [comment]
The full error stack would also be helpfull as this isn't really showing where the error originated from.
A reproducable repo would also be very helpfull
