### ISSUE TITLE
In the Vue single file component .vue file, static resources imported using url() under the <style> tag are not packaged

### ISSUE THREAD

**Issue by Mirror-l** [parcel-bundler/parcel#1002]

**Comment by davidnagli** [comment]
Original title: Vue单文件组件.vue文件里面，<style>标签下用url()导入的静态资源，没有打包

**Comment by DeMoorJasper** [comment]
Perhaps add a detailed description with what environment and how you run vue? Using the vue branch or plugin or...

**Comment by PeachScript** [comment]
Hello @DeMoorJasper , I think I have the same problem, I'm using `Parcel` 1.6.2 (not vue branch) with `parcel-plugin-vue` 1.5.0, and I have been created an issue for `parcel-plugin-vue` but no reply: https://github.com/BoltDoggy/parcel-plugin-vue/issues/31

Do you have any idea about it?
