### ISSUE TITLE
Missing from NPM ?

### ISSUE THREAD

**Issue by phuze** [parcel-bundler/parcel#10032]
Is it just me, or are all the parcel packages missing from NPM?

https://www.npmjs.com/package/parcel
https://www.npmjs.com/package/@parcel/watcher

![image](https://github.com/user-attachments/assets/1834918b-c202-4897-b4fc-30258f15ecb1)

**Comment by saldestechnology** [comment]
No, it's not just you! It's not available right now and I don't know why.

```
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/parcel - Not found
npm error 404
npm error 404  'parcel@*' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /home/saldes/.npm/_logs/2024-12-08T18_52_36_500Z-debug-0.log
```

**Comment by phuze** [comment]
I've found out that there is maintenance happening over at NPM at the moment.
https://status.npmjs.org/

![image](https://github.com/user-attachments/assets/df36de9d-a4ca-47cf-bca5-018da2a93d0e)

They stated that things like installations, search, etc should still function.
Clearly something has gone south.

I expect this should be resolved later.
