### ISSUE TITLE
🙋 Feature request: stop HMR propagation

### ISSUE THREAD

**Issue by fasterthanlime** [parcel-bundler/parcel#1003]
### 🎛 Configuration (.babelrc, package.json, cli command)

Currently on parcel@1.6.2

### 🤔 Expected Behavior

I'd love to have a way to prevent reloading some modules, something like:

```javascript
let r;
export default r;
function refresh() {
  // if either of those have changed, they've been
  // deleted from the module cache and re-required.
  const a = require("./a").default;
  const b = require("./b").default;
  r = combineReducers({a, b});
}
refresh();

if (module.hot) {
  module.hot.dispose(() => {
    refresh();
    return {stopPropagation: true};
  });
}
```

### 😯 Current Behavior

Currently parcel unconditionally reloads (deletes from require.cache, then require()'s) any changed module and all its parents.

### 💁 Possible Solution

`hmr-runtime.js`, hmrAccept:

```javascript
function hmrAccept(bundle, id) {
  var modules = bundle.modules;
  if (!modules) {
    return;
  }

  if (!modules[id] && bundle.parent) {
    return hmrAccept(bundle.parent, id);
  }

  var cached = bundle.cache[id];
  if (cached && cached.hot._disposeCallback) {
    var disposeRes = cached.hot._disposeCallback();
    // important part's here
    if (disposeRes && disposeRes.stopPropagation) {
      return;
    }
    // important part stops here
  }

  delete bundle.cache[id];
  bundle(id);

  cached = bundle.cache[id];
  if (cached && cached.hot && cached.hot._acceptCallback) {
    cached.hot._acceptCallback();
    return true;
  }

  return getParents(global.require, id).some(function (id) {
    return hmrAccept(global.require, id)
  });
}
```

### 🔦 Context

This is the part where you judge me: I'm using HMR in an electron app, in *both processes*. The browser-like process works quite well already, and for the node-like process, I've had to `npm install -D ws` and add `global.WebSocket = require("ws")`.

I want to reload a bunch of stuff: not only React components, but also redux reducers (which compute new state based on actions and previous state), and reactors (which asynchronously perform work when actions are dispatched - that's my own stuff).

However, things like the redux store absolutely *cannot* be reloaded - because then we just have "another store", with the newer reducers/reactors running, but it's not being used by the app at all. So I need HMR to work only on a subset of the module graph, not all the way to the top.

---

Note: the way I expected HMR to work originally is:

  * Walk up the dependency tree to find all ancestors
  * If none of them have an _acceptCallback, do not reload
  * If one ancestor has an _acceptCallback, reload all modules up to that ancestor, do not reload the ancestor, and call _acceptCallback on it

^ If it worked that way, I wouldn't have to change my code at all and could just keep using the `accept()` callback rather than the `dispose()` one - but I don't know if it would break any HMR usage with parcel.

<sup>Also, Hi Devon! Long time no talk!</sup>

**Comment by mischnic** [comment]
Merging this into #2497
