### ISSUE TITLE
Unexpected Token ...mapActions

### ISSUE THREAD

**Issue by xtrip15** [parcel-bundler/parcel#1012]
I get this error when running parcel with vuex.

`×  C:\Projects\parcel\src\components\login.vue:46:4: C:/Projects/parcel/src/comp                  onents/login.vue: Unexpected token (46:4)
  44 |   },
  45 |   methods: {
> 46 |     ...mapActions("userModule", [
     |     ^
  47 |       "loginUser",
  48 |       "logoutUser",
  49 |       "getUser",
  44 |   },
  45 |   methods: {
> 46 |     ...mapActions("userModule", [
     |     ^
  47 |       "loginUser",
  48 |       "logoutUser",
  49 |       "getUser",
  44 |   },
  45 |   methods: {
> 46 |     ...mapActions("userModule", [
     |     ^
  47 |       "loginUser",
  48 |       "logoutUser",
  49 |       "getUser",
`

**Comment by mischnic** [comment]
Do you have a .babelrc file?
You need the `transform-object-rest-spread` plugin or some preset.

**Comment by xtrip15** [comment]
Yes, .babelrc was there but needed the plugin! Thanks.
