### ISSUE TITLE
[BUG] SSR breaks when importing scss from npm module

### ISSUE THREAD

**Issue by RaulTsc** [parcel-bundler/parcel#1015]
🐛 bug report

Hi guys,

I am trying to switch from webpack to parcel for our medium-sized app but I am having difficulties getting scss  in node_modules to work.

### 🤔 Expected Behavior

NPM modules that use scss should work.

### 😯 Current Behavior

NPM modules that use scss do not work.

### 💁 Possible Solution

I might be missing something. If that's not the case, I'm not sure. But I'm willing to invest some time to make it work, so let me know if there's anything I can do :).

### 💻 Code Sample

Please see this repo: https://github.com/RaulTsc/parcel-react-ssr-nodemodulesscss

Running yarn build && yarn start throws

```
/../parcel-react-ssr/node_modules/@everreal/er-common-react-components/lib/components/common/Separator/Separator.scss:1
(function (exports, require, module, __filename, __dirname) { @import './../../../theme/variables.scss';
                                                             ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
```

More info:
1) Please note that this is an issue only for SSR. Running `yarn dev` works
2) `dist/server/index.css` contains the css in `.../Separator.scss`

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.6.1
| Node             | 8.9.1
| npm/Yarn         | yarn 1.3.2
| Operating System | Mac OS High Sierra

**Comment by RaulTsc** [comment]
[https://imgur.com/a/f2TUA](Both are simple, regular scss files)

**Comment by RaulTsc** [comment]
Got it to work if I do this:

```
function HelloWorld() {
  return _react2.default.createElement(
    'div',
    null,
    _react2.default.createElement(
      'h1',
      { className: 'hello-world' },
      'Hello world!'
    )
  );
}
// import {Separator} from '@everreal/er-common-react-components/lib/components/common/Separator/Separator';
},{"./HelloWorld.scss":11}],7:[function(require,module,exports) {
'use strict';
```

```
function HelloWorld() {
  return _react2.default.createElement(
    'div',
    null,
    _react2.default.createElement(
      'h1',
      { className: 'hello-world' },
      'Hello world!'
    )
  );
}
// import {Separator} from '@everreal/er-common-react-components/lib/components/common/Separator/Separator';
},{"./HelloWorld.scss":11,"@everreal/er-common-react-components/lib/components/common/Separator/Separator.scss": 11}],7:[function(require,module,exports) {
'use strict';
```

inside `dist/server/index.js`

I have no idea what that means and how this code is generated, but I'll dig further.

**Comment by RaulTsc** [comment]
In your module, `src/visitors/dependencies` there's this function:

```
function addDependency(asset, node, opts = {}) {
  if (asset.options.target !== 'browser') {
    const isRelativeImport =
      node.value.startsWith('/') ||
      node.value.startsWith('./') ||
      node.value.startsWith('../');

    if (!isRelativeImport) {
      return;
    }
  }

  opts.loc = node.loc && node.loc.start;
  asset.addDependency(node.value, opts);
}
```

Changing it to

```
function addDependency(asset, node, opts = {}) {
  if (asset.options.target !== 'browser') {
    const isRelativeImport =
      node.value.startsWith('/') ||
      node.value.startsWith('./') ||
      node.value.startsWith('../');

    if (!isRelativeImport && !node.value.endsWith('scss')) {
      return;
    }
  }

  opts.loc = node.loc && node.loc.start;
  asset.addDependency(node.value, opts);
}
```

correctly adds the scss as a dep and everything works.

I'm sure there is a good reason for this check (probably you don't want to handle node absolute imports?)

I'm willing to work on a fix for this if someone points me in the right direction @DeMoorJasper  @devongovett 

Thanks for your time.

**Comment by DeMoorJasper** [comment]
Not sure why it isn't working, normally it should resolve npm dependencies correctly.
Have you tried using the latest github version of parcel (with the new resolver)?
It only bugs for `import '@everreal/er-common-react-components/lib/components/common/Separator/Separator.scss';` right?

**Comment by RaulTsc** [comment]
The initial issue was that I was importing the React component called `Separator` and that was importing the scss and then node would throw an `unexpected token` error because it was running it as js.

But then importing any scss from an npm module in js does not work when targeting anything other than the browser because of this fn:

```
function addDependency(asset, node, opts = {}) {
  if (asset.options.target !== 'browser') {
    const isRelativeImport =
      node.value.startsWith('/') ||
      node.value.startsWith('./') ||
      node.value.startsWith('../');

    if (!isRelativeImport) return;
  }

  opts.loc = node.loc && node.loc.start;
  asset.addDependency(node.value, opts);
}
```

I have tried the latest master, yes. (the above fn is there and it filters out the dep) `if (!isRelativeImport) return;`.

**Comment by RaulTsc** [comment]
@devongovett @DeMoorJasper any ideas on this one? I would really submit a PR to fix it, but I don't want to just remove that check, I am sure it's there for good reason, so I would like to have some context.

Also, this looks like a pretty common use case for bigger projects -- Bundling a project that imports node_modules that use scss and doing SSR.
