### ISSUE TITLE
import('/${key}') is no work

### ISSUE THREAD

**Issue by ckken** [parcel-bundler/parcel#102]
Dynamic is work. But it work for webpack

**Comment by davidnagli** [comment]
Can you elaborate a bit more?? I can’t really explain what you’re saying “dynamic is work”

**Comment by thejameskyle** [comment]
@davidnagli Please be respectful of people who speak english as a second language.

@ckken Parcel currently does not support dynamic import expressions. I'm proposing something else: #125

**Comment by devongovett** [comment]
Closing in favor of #125.
