### ISSUE TITLE
🙋 Allow any cli args (so plugins can define their own)

### ISSUE THREAD

**Issue by gregtillbrook** [parcel-bundler/parcel#1020]
Ive created a plugin [parcel-plugin-bundle-visualiser](https://github.com/gregtillbrook/parcel-plugin-bundle-visualiser) that Id like to enable with a cli arg, e.g. `parcel build --visualise` but parcel errors with `error: unknown option `--visualise'`.

Would it be possible to allow any cli args? One way to do this could be to call commanders [allowUnknownOption](https://tj.github.io/commander.js/#Command.prototype.allowUnknownOption)

**Comment by DeMoorJasper** [comment]
I'm no big fan of allowing any unknown option as that removes the feedback u get if it's not an option...
However being able to inject options through plugins would definitely be a nice feature maybe add it to the discussion regarding the new and improved plugin architecture, see #918

**Comment by gregtillbrook** [comment]
Added comment to #918
