### ISSUE TITLE
Cant get source-map to work 

### ISSUE THREAD

**Issue by Ranjeet-Naidu** [parcel-bundler/parcel#1021]
Hi guys I can see a .map file being created on build but no mapping on chrome. Am I missing something?

Thanks

```js
.babelrc

{
  "plugins": [
    "transform-runtime",
    "transform-es2015-destructuring",
    "transform-object-rest-spread",
    "syntax-dynamic-import"
  ],
  "presets": ["env"]
}

  "scripts": {
    "dev": "rm -rf .cache && rm -rf dist && parcel index.html"
  },
```

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.2
| Node             | 8.0.0 
| npm/Yarn         | 5.0.0
| Operating System | OSX

**Comment by DeMoorJasper** [comment]
It's a known bug that sourcemaps don't support hot reloading, but they should work on normal browser refreshes and definitely on initial load, could u provide an example repo?

**Comment by Ranjeet-Naidu** [comment]
Hi it doesn't seem to work on initial load or on a refresh. Code can be found [here](https://github.com/Ranjeet-Naidu/Spike-VueJS).
Thanks.

**Comment by Hammster** [comment]
`parcel-plugin-vue` is the source of the issue, the extended JSPackager overrides the generation of the source map reference at the end of the file and also the extension is based on the outdated JSPackage which is why other things are missing too.

**Comment by DeMoorJasper** [comment]
@Hammster Thanks for clearing this up :)
I'll close this as the issue can be moved to `parcel-plugin-vue`
If any of you would like to test out vue support with properly working sourcemaps, feel free to test the official Vue branch :) #1052
