### ISSUE TITLE
🐛 Build with Autoprefixer - Peer Dependencies

### ISSUE THREAD

**Issue by Benjmhart** [parcel-bundler/parcel#1023]
running autoprefixer based on instructions from the transforms section of docs.

getting a peer dependancy error - no peer dependancies run on install - and why is parcel installing dependencies on build?

### 🤔 Expected Behavior
should complete the build and output prefixed css file
### 😯 Current Behavior
output:
⏳  Building style.css...
🚨  /home/ubuntu/workspace/style.css:undefined:undefined: Failed to install peerDependencies for autop    at ChildProcess.install.on (/home/ubuntu/.nvm/versions/node/v8.9.0/lib/node_modules/parcel-bundler/src/utils/installPackage.js:38:11)
    at <anonymous>

### 🌍 Your Environment

cloud9 IDE

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             | v 8.9.0
| npm/Yarn         |  v5.7.1
| Operating System | ubuntu

**Comment by davidnagli** [comment]
Looks like the stack trace in the error message you pasted is cut off. Can you please update with the full error message?

**Comment by Benjmhart** [comment]
sorry,   it was getting cut off and I can't seem to find a way to expand it,   but i believe it's failing on autoprefixer.

**Comment by DeMoorJasper** [comment]
I'll close this off for now as a lot have changed in autoinstall and it should be stable now.

Feel free to reopen if this still persists in 1.7.1, a test repo would also be very helpfull :)
