### ISSUE TITLE
Parsing objects for browserslist fails

### ISSUE THREAD

**Issue by sohkai** [parcel-bundler/parcel#1026]
Parcel doesn't interpret environments in a browserslist config.

Using this config

```json
  "browserslist": {
    "development": ">2%, last 1 edge versions, not ie > 0, not op_mini all",
    "production": ">2%, last 1 edge versions, not ie > 0, not op_mini all"
  }
```

Results in

```sh
🚨  <file>: Browser queries must be an array. Got object.
    at browserslist (.../node_modules/browserslist/index.js:207:11)
    at getTargetEngines (.../node_modules/parcel-bundler/src/utils/getTargetEngines.js:69:24)
    at <anonymous>
```

It looks like the main `browserslist(queries, opts)` API that's exported isn't meant to know about environments (it's left to the user to determine which environment to supply it with).

**Comment by nicolaisueper** [comment]
The given config wouldn't work either with the current implementation, because the browser list props currently must be defined as an array as described [in the browserlist docs](https://github.com/browserslist/browserslist#environments). Should parcel be able to parse browserlists defined as strings too?

**Comment by sohkai** [comment]
Ah hmm, I think that's transparent for browserlist, it probably just does a `.split(',')` in that case.

[The JS docs later on say that "Queries can be a string `> 5%, last 1 version` or an array `['> 5%', 'last 1 version']`"](https://github.com/browserslist/browserslist#js-api).

**Comment by DeMoorJasper** [comment]
I guess in that case we might want to implement the string format.
@nicolaisueper perhaps you can add it to your pr?

**Comment by nicolaisueper** [comment]
@DeMoorJasper for sure. :)

**Comment by nicolaisueper** [comment]
@DeMoorJasper I added the functionality + refactored the test to cover both changes
