### ISSUE TITLE
Issues getting parcel to work correctly on Windows

### ISSUE THREAD

**Issue by humphd** [parcel-bundler/parcel#1029]
I've been building a small web app with students this past week, and we used Parcel.  It initially worked really well, and was ideally suited to students new to the idea of bundling.  Parcel does a lot right, and it's very impressive in its simplicity.

However, I was forced to switch to webpack after many students struggled to get things to work on Windows.  Their setups differed from one another (e.g., versions, which shell they used, etc) so it's hard to give you an exact environment spec.  However, it was fairly consistent across the students running Windows, where those on Mac and Linux didn't seem to have so much difficulty.  Two main issues stood out:

* In the build, I had [two `npm` scripts](https://github.com/humphd/bridge-troll/blob/b0468b3f8aa590243f6d5af3389e3711b1c8fbf9/package.json#L13-L14) to run `parcel` with and without defining an environment variable.  The variable was only sometimes defined, and often seemed to lose its value on rebuilds of the code; though I saw it happen on first runs too.

* By far the larger issue was that the build would either never complete, or take forever.  The bundle just never got made, and the browser would load forever.

https://github.com/humphd/bridge-troll/ is the repo I was building with them, and `b0468b3f8aa590243f6d5af3389e3711b1c8fbf9` the last commit before I switched to webpack.

Apologies that this bug is vague, bug @devongovett encouraged me to file something.  I wonder how many of your devs are testing regularly on Windows?  I know I'm on Mac, and it worked perfectly for me there.  But using this more widely requires full Windows support.

If there's nothing actionable here, feel free to close this.  I'll check back in on parcel again as you keep improving things.  It's really cool.

**Comment by davidnagli** [comment]
cc @brandon93s

**Comment by jkrehm** [comment]
The "never completes" seems likely to be related to #637 and #900. I know I run into that regularly, but it happens for me on both Windows and Linux.
