### ISSUE TITLE
Add a gitter.im banner to the project's README / community chat

### ISSUE THREAD

**Issue by shawwn** [parcel-bundler/parcel#103]
If you visit e.g. https://github.com/NicolasPetton/Indium, at the top of their README you can click the "join chat" button:

![image](https://user-images.githubusercontent.com/59632/33737810-05b20cb0-db5d-11e7-8a9e-dcde4400af37.png)

That throws you into their [lobby](https://gitter.im/indium-emacs/Lobby) which is quite helpful for learning the ropes.

Would Parcel benefit from this? It only takes a few minutes to set it up.

**Comment by shawwn** [comment]
Ok, it turns out only the owner can create a gitter.im community.

@devongovett if you go to https://gitter.im/ and create the parcel-bundler channel, I can handle setting it up and adding it to the README.

**Comment by shawwn** [comment]
(Actually, name it "parcel" if possible. It'd be a bit easier to discover.)

**Comment by shawwn** [comment]
We decided to go with a public Slack workspace: https://slack.parceljs.org/

Badge:

[![Slack](https://slack.parceljs.org/badge.svg)](https://slack.parceljs.org/)

**Comment by thejameskyle** [comment]
#115
