### ISSUE TITLE
bundle.assets.parentDeps set has wrong parent asset name

### ISSUE THREAD

**Issue by TimNZ** [parcel-bundler/parcel#1030]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
Bug

Testing https://github.com/gregtillbrook/parcel-plugin-bundle-visualiser and exploring to see if the bundle stats support the equivalant of Webpack stats 'Reasons' for a module e.g. the calling module.  

Looping through bundle.assets, noticed that 'name' of each parent asset in asset.parentDeps is the name of the asset itself, not the parent asset.
The 'loc' is the correct location in the parent asset.

```
asset.name: /Users/timshnaider/Desktop/Development/Projects/grapesjs/cms/src/components/GrapesJS/index.js

asset.parentDeps: Set {
  { name: './components/GrapesJS/index', <- should be './index.js'
  loc: Position { line: 3, column: 21 } },
  { name: './components/GrapesJS/index', <- should be './test.js'
  loc: Position { line: 1, column: 21 } } }
```
### 🤔 Expected Behavior
'name' should be the parent asset name.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | Latest
| Node             | 9.4
| npm/Yarn         | Yarn 
| Operating System | OS X

**Comment by devongovett** [comment]
This is correct behavior. `parentDeps` is a list of dependencies that reference the current asset. So each dep's `name` field is the value that was used to require the asset, e.g. the value from `require('./components/GrapesJS/index')`.

**Comment by TimNZ** [comment]
@devongovett Is there a prop in the bundle stats to see who the caller/initiator was?
Can you add the caller/initiator to the parentDeps so I can trace the call chain.

Considering creating a plugin to spit out webpack stats compatiatable JSON if possible.
