### ISSUE TITLE
Use materialize with parcel 🐛

### ISSUE THREAD

**Issue by JensPauwels** [parcel-bundler/parcel#1033]
I'm currently making a new build with parcel, unfortunately i can't use materialize because it can't load the fonts.

I've tried to include it from the html files and from the main.js but nothing works.

I guess this is due to the hashing of files.

Any help is welcome

Uncaught (in promise) Error: Cannot find module '0b498de5d2b3ea8070a47e2d1c060023.woff,17'
    at newRequire (css-loader.js:30)
    at newRequire (css-loader.js:22)
    at localRequire (css-loader.js:30)
    at css-loader.js:30

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.2
| Node             | 8.8.1
| npm/Yarn         | 5.6.0
| Operating System | High sierra

**Comment by JensPauwels** [comment]
looks like cache is the problem here

**Comment by mischnic** [comment]
Similiar error as in #1007, #973

**Comment by mischnic** [comment]
To reproduce:
```html
<link rel="stylesheet" href="./node_modules/materialize-css/dist/css/materialize.min.css">
<script src="./node_modules/materialize-css/dist/js/materialize.min.js"></script>

<div class="card-panel teal lighten-2">This is a card panel with a teal lighten-2 class</div>
```
```json
{
  "dependencies": {
    "materialize-css": "^0.100.2",
    "parcel-bundler": "^1.6.0"
  }
}
```

**Comment by timfee** [comment]
Hi,

I'm not sure if this helps your exact case, but here's what worked for me.

In my project root
```
npm install materialize-css@next
```

Make a file called **./index.js** and add:
```js
// index.js

import "./main.scss";
```

Make a file called **./main.scss** and add:
```scss
// main.scss
@import "~materialize-css/sass/materialize";
```

And finally, **./index.html** to include:
```html
<!DOCTYPE html>
<html>

  <head>
    <title>Hello world!</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script type="text/javascript" src="index.js"></script>
  </head>

  <body>
    <h1>Hello!</h1>
  </body>

</html>
```

I'm able to run `parcel index.html` without any problems. 

Does this work for you? (Similar to the instructions on the [recipes](https://parceljs.org/recipes.html#customizing-bootstrap-styles) page.)

**Comment by contributorpw** [comment]
To fulfil @timfee 's masterful answer :arrow_up:.

```js
// index.js
import "materialize-css";
import "./main.scss";
```
