### ISSUE TITLE
parcel tries to bundle angular templating code

### ISSUE THREAD

**Issue by thedewpoint** [parcel-bundler/parcel#1034]
I have some angular components that require an html file.
example:
{
  template: require("./partials/partial.html"),
   ...
}
inside of the partial I have angular code
   `<a href="{{article.link}}"></a>
`

### 🤔 Expected Behavior

parcel should not try to bundle this link

### 😯 Current Behavior

parcel treats this like an html page and tries to bundle the html page

### 💁 Possible Solution

add syntax to the markup to allow me to ignore certain code blocks from the parcel bundler

### 🔦 Context

This syntax would help with some other issues we are having. We have several different testing environments and have dynamic node server variables that set the base cdn url depending on which environment we are in. if we have syntax like this
<script type="text/javascript" src="{{serverVariable}}/somefile.js{{cacheBuster}}"></script>
parcel also tries to find this file even though it exists on a remote cdn at runtime. Currently we are running parcel in watch mode and running an express server to serve up the index html, so we need to be able to ignore server variables in the html

**Comment by DeMoorJasper** [comment]
It probably recognises it as JSX and tries to parse as JSX

**Comment by davidnagli** [comment]
@DeMoorJasper The imported file has a `.html` file extension, so I think it's just being treated an HTMLAsset, not JSX.

**Comment by DeMoorJasper** [comment]
Ow thought it was a JS file, was going through all issues tagging them totally looked over the file extension.
