### ISSUE TITLE
Feature: SCSS as css module

### ISSUE THREAD

**Issue by FDiskas** [parcel-bundler/parcel#1038]
Add ability to import scss as css module

**Comment by sKawashima** [comment]
You can do it by installing the "node-sass" module

**Comment by DeMoorJasper** [comment]
It should be in parcel from default, it should normally even automatically install node-sass

**Comment by FDiskas** [comment]
but if you do like
```jsx
import style from './main.scss';
console.log(style); // {}
```
but on css
```jsx
import style from './main.css';
console.log(style); // {main: { fontSize: 12 }}
```

**Comment by DeMoorJasper** [comment]
Ow that's weird i'll reopen as a bug, not sure what's causing this, could u create a test repo to reproduce?

**Comment by DeMoorJasper** [comment]
Might be a failed node-sass install happens sometimes i'll close this issue as in the future our auto-install should improve
