### ISSUE TITLE
 error: unknown option `--no-source-maps'

### ISSUE THREAD

**Issue by berkandirim** [parcel-bundler/parcel#1041]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
Bug report

### 🎛 Configuration (.babelrc, package.json, cli command)
cli command

**.babelrc conifg**
```js
{
  "plugins": ["transform-class-properties"],
  "presets": [
    "es2015", "stage-0"
  ]
}
```

### 🤔 Expected Behavior
Successful build with no source maps

### 😯 Current Behavior
Throws error unknown option `--no-source-maps'

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |      1.6.2
| Node             |      8.9.3
| npm/Yarn         |  5.7.1 / 1.0.2 
| Operating System | macOS High Sierra

**Comment by DeMoorJasper** [comment]
--no-source-maps flag hasn't been released yet (for the build command) only for the watch command.
