### ISSUE TITLE
Nunjucks Support

### ISSUE THREAD

**Issue by kokujin** [parcel-bundler/parcel#1044]
Is there a way to get parcel to process non HTML entry files?. I use Nunjucks templates, these are ignored by parcel. Parcel works however when I rename the file to HTML

This works
```````
"build": "parcel build ./views/layout.html --out-dir public/assets"
```````

This does'nt
```````
"build": "parcel build ./views/layout.njk --out-dir public/assets"
```````

Thanks

**Comment by DeMoorJasper** [comment]
It would work if nunjucks is supported by parcel, I guess a plugin for it would be the proper approach?

**Comment by kokujin** [comment]
@DeMoorJasper, You misunderstood me, I would like Parcel to compile the CSS and JS assets defined in the Nunjucks template not compile the Nunjuck Template itself

**Comment by davidnagli** [comment]
I just looked into, and it looks like nunjucks has two ways to use it...
you can leave the templates in the HTML and evaluate them on runtime, or
precompile ahead of time.

If you plan to evaluate them on runtime, then I suggest just renaming the
file to .html and using Parcel as normal. However, if you need Parcel to
precompile the templates, as Jasper said, your gonna need a plugin

**Comment by DeMoorJasper** [comment]
We could add it as a known html extension, but I'm not sure if that's supposed to be the case. If i'm mistaken this could be an easy fix

**Comment by davidnagli** [comment]
@DeMoorJasper I was thinking the same thing. But, that could get in the way if someone decides to make a plugin that _doesn't_ treat them as HTML.

In the future if someone makes a plugin that precompiles files with the `njk` file extension.

**Comment by DeMoorJasper** [comment]
@davidnagli The plugin would overwrite it, not cause any issues. So it might be a pretty good idea, although i'm not sure never used nunjucks

**Comment by davidnagli** [comment]
@DeMoorJasper Oh ya you're right 👍 I didn't realize that we register extensions in the Bundler's constructor, with would mean that plugins run after, which allows them to override.

**Comment by danielpa9708** [comment]
There seems to be a plugin for this https://github.com/devmattrick/parcel-plugin-nunjucks, I don't know if it works

**Comment by chocolateboy** [comment]
> I would like Parcel to compile the CSS and JS assets defined in the Nunjucks template not [just] compile the Nunjuck Template itself

As @danielpza mentioned, this works with the [nunjucks plugin](https://github.com/chocolateboy/parcel-plugin-nunjucks): https://github.com/chocolateboy/parcel-plugin-nunjucks#assettype

**Comment by devongovett** [comment]
Going to close this. I don't have the bandwidth to implement and maintain this. It would be great as a third party plugin if someone wants to build it!
