### ISSUE TITLE
production build cache busting

### ISSUE THREAD

**Issue by FDiskas** [parcel-bundler/parcel#1046]
Hi,
if I run `parcel build src/index.html --public-url ./`

I'm always getting the same file names in dist directory. I tried to change contents of js files, but result are the same - the size is only one difference
```
dist/699927c3d5ddeecb2067ad44a0c37e2f.js
```
parcel: v1.6.2

**Comment by devongovett** [comment]
Support for content hashed paths were added in #1025 and will go out in the next release.

**Comment by DeMoorJasper** [comment]
Fixed by #1025

**Comment by devongovett** [comment]
Ha, beat you @DeMoorJasper!

**Comment by FDiskas** [comment]
:D Thank you for the cool project. :waxing_crescent_moon:
