### ISSUE TITLE
Something wrong with babel

### ISSUE THREAD

**Issue by FDiskas** [parcel-bundler/parcel#1048]
Impossible to use https://www.npmjs.com/package/rheostat library
.babelrc
```json
{
  "presets": ["env", "react-app"],
  "plugins": ["transform-class-properties"]
}
```
index.js
```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import Rheostat from 'rheostat';
 
ReactDOM.render((
  <Rheostat
    min={1}
    max={100}
    values={[1, 100]}
  />
), document.getElementById('slider-root'));
```
![error](https://i.imgur.com/rPNyo3u.png)
Probably related to https://github.com/parcel-bundler/parcel/pull/878
parcel: 1.6.2

**Comment by davidnagli** [comment]
Does JSX work without rheostat?

Are you sure that you're using 1.6.2 and not some other version? (we saw something very similar in #963)

Also can you please provide the full error message... it got cropped out of your screenshot.

**Comment by lucianoratamero** [comment]
I'm having the same problem, but with `react-foundation`:
```
node_modules/react-foundation/src/components/breadcrumbs.js:21:9: Unexpected token (21:9)
  19 |   const passProps = removeProps(props, objectKeys(Breadcrumbs.propTypes));
  20 | 
> 21 |   return <ul {...passProps} className={className}/>;
     |          ^
  22 | };
  23 | 
  24 | Breadcrumbs.propTypes = {
```
anyone?

**Comment by lucianoratamero** [comment]
I found out that the problem is related to parcel not using babel for `node_modules`.
changing to the es5 library did the job, @FDiskas .

**Comment by FDiskas** [comment]
Yes in this case `parcel` should respect modules package.json settings
ex.: https://unpkg.com/react-foundation@0.9.5/package.json
```json
"main": "lib/index.js",
"jsnext:main": "src/index.js",
```
parcel should take file from "main" not from "jsnext:main" key :pouch:

**Comment by lucianoratamero** [comment]
thanks, that clarifies it :]

**Comment by bencevans** [comment]
Seem to be having getting the same issue when running in a Docker based on the official Node v8 image. However works perfectly when run on the host system. Same version of Node.js and Parcel. O.o
