### ISSUE TITLE
Function running very very slow when using parcel

### ISSUE THREAD

**Issue by z543** [parcel-bundler/parcel#1056]
🐛 

Function running very very slow when using parcel
But it's very fast if I use local server to view the HTML file

### 🎛 Configuration (.babelrc, package.json, cli command)

no babel configuration

### 💻 Code Sample
https://github.com/z543/parcel_test

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v1.6.2
| Node             | v8.9.2
| npm          | 5.7.1

CPU: Intel Core2 Duo E8400 3GHz
RAM: 8GB
Windows 7 x64
Chrome 67.0.3371.0 (Official Build) dev (64-bit)

**Comment by davidnagli** [comment]
How is this related to Parcel?

**Comment by DeMoorJasper** [comment]
I have a totally different outcome when running your git repo.

My test results:

| |  Native web	|   Parcel	| 
|---	|---	|--- |
| loki-add-10000 mem  	|   62.786865234375ms	| 46.455078125ms |
|   loki-remove mem	|   365.382080078125ms	| 347.861083984375ms  |

So I don't think it's parcels fault?

**Comment by z543** [comment]
sorry, I guess it's chrome's problem,

**Comment by DeMoorJasper** [comment]
I'll close this down as it doesn't appear to be a parcel issue
