### ISSUE TITLE
BUG: postcss-modules globalModulePaths can't work

### ISSUE THREAD

**Issue by ThaddeusJiang** [parcel-bundler/parcel#1060]
This a 🐛 bug report

### 🎛 Configuration (postcss.config.js)

```js
// postcss.config.js
module.exports = {
  modules: true,
  plugins: {
    "postcss-modules": {
      globalModulePaths: ["./global/"]
    }
  }
};
// global/index.less
@import "../node_modules/antd/dist/antd.less"; 
```

### 🤔 Expected Behavior

antd.less no hash.
Example:
```
._anticon {
  display: inline-block;
  font-style: normal;
  vertical-align: baseline;
  text-align: center;
  text-transform: none;
  line-height: 1;
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

### 😯 Current Behavior

```
._anticon_12kcc_348 {
  display: inline-block;
  font-style: normal;
  vertical-align: baseline;
  text-align: center;
  text-transform: none;
  line-height: 1;
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.6.3|
| Node             |v8.9.4
| npm/Yarn         |Yarn 1.3.2|
| Operating System |macOS 10.13.3|

**Comment by viniciusmelquiades** [comment]
I have the same problem. I managed to make the CSS file be generated correctly (both modules and non-modules) using this
```js
// .postcssrc.js
module.exports = {
  plugins: [
    require('postcss-modules')({
      globalModulePaths: [/\.global\./],
    }),
  ],
};
```
The downside is that, for all CSS files I try to import in JS, I receive an empty object and for every CSS file I get an equivalent JSON file with the content I expect to be imported by JS. I haven't been able to fix this yet. I hope the team can help us work around this issue.

**Comment by viniciusmelquiades** [comment]
@DeMoorJasper you were the one who added the Bug label to the issue. Do you think its possible to make it work with the code I posted earlier?

**Comment by TkDodo** [comment]
Any news on this? I am having the same issue with `parcel 1.7` on `node 10`.
What's odd is that `globalModulePaths` seems to be respected in development mode, but as soon as I make a production build, _all_ css files are processed as modules ... 🤔

**Comment by ThaddeusJiang** [comment]
maybe this can work.

https://github.com/parcel-bundler/parcel/issues/645#issuecomment-361008955
