### ISSUE TITLE
Ability to select source-maps type

### ISSUE THREAD

**Issue by eavichay** [parcel-bundler/parcel#1067]
🙋 feature request

Some babel plugins (such as transform-class-properties) causes the source-maps to break. In order to work properly, the `eval` source mapping method is required.
It would be nice to have the ability to select the source-mapping technique, probably in package.json under "parcel" (?) property.

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "parcel": { "sourcemaps": "eval" }
}
```

**Comment by DeMoorJasper** [comment]
Could u elaborate a bit more on how this would be used inside parcel, or how to set this in babel?
As we simple get the sourcemap from babel and process it inside parcel

**Comment by eavichay** [comment]
webpack defines it in the configuration file, under "sourcemap" entry. Since parcel is "zero" configuration it's a conflict with the concept. Though without overrides of the defaults this bundler is no good for many use-cases. Consider adding in package.json optional overrides under `parcel` property.

This might raise another question: does parcel must work with npm-initialized projects?

**Comment by mischnic** [comment]
> Some babel plugins (such as transform-class-properties) causes the source-maps to break

Is this still the case? This is an issue of the babel transform.
I think the variety of sroucemap options provided by webpack is overkill. How is your requested sourcemap different from the current (full) sourcemaps from Parcel?

**Comment by eavichay** [comment]
Can you use dynamic imports with parcel? Can you configure babel to use target es6 classes? How can you configure parcel to work with web components?

**Comment by mischnic** [comment]
> Can you use dynamic imports with parcel?

Yes, example: https://github.com/parcel-bundler/parcel/tree/58f76fa37388cdeaa33787b540662eec1ed310b7/packages/core/integration-tests/test/integration/dynamic
> Can you configure babel to use target es6 classes?

Yes, using browserslist

> How can you configure parcel to work with web components?

What is so special about them?

**Comment by eavichay** [comment]
@mischnic 
> What is so special about them?
Well, let's revisit this question in one year from now

**Comment by eavichay** [comment]
Babel requires custom-elements plugin

**Comment by mischnic** [comment]
> Babel requires custom-elements plugin

You can specify that in the .babelrc file. If that doesn't work, please provide a non-working example.

**Comment by kresli** [comment]
I think setting sourceMaps in babelrc is ignored
```
// babelrc
{
  "sourceMaps": "inline",
  "presets": [["@babel/preset-env"]]
}
```
```
// generated on the end of js file
//# sourceMappingURL=background/background.js.map
```
But I expecting something as
```
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJz
```
