### ISSUE TITLE
Tutorial for adding a new language

### ISSUE THREAD

**Issue by shawwn** [parcel-bundler/parcel#107]
🙋 feature request

Is this the right place for documentation requests?

It would be good to write a tutorial on how to add support for a new language, from start to finish. It could be a very basic language for tutorial purposes, or a more established language like [LightScript](http://www.lightscript.org/).

That way, both plugin authors and new contributors would know what to do to add support for their favorite tools.

I recently went through this learning process, so I suppose I could help write it.

**Comment by davidnagli** [comment]
This sounds like a great idea. Do you wanna write it?? I would love to help out too

**Comment by devongovett** [comment]
This gives some info already https://parceljs.org/asset_types.html

**Comment by davidnagli** [comment]
Ya it gives some, but I think he means a full end-to-end tutorial on how to add support for a new language.

**Comment by shawwn** [comment]
@davidnagli Sure, if you want to collab on it you can hop into Slack. (Check your email for an invite.)

**Comment by thejameskyle** [comment]
This content probably belongs in CONTRIBUTING.md.

I want to document the structure of the codebase and add comments everywhere to make this easier to contribute to.

**Comment by davidnagli** [comment]
Oh ya, that’s a good point. It actually makes allot more sense to add this to CONTRIBUTING.md.

@shawwn What do you think?
