### ISSUE TITLE
autoprefixer not work

### ISSUE THREAD

**Issue by gaojingran** [parcel-bundler/parcel#1072]
**Choose one:** this is a 🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

.postcssrc

```js
{
  "modules": true,
  "plugins": {
    "autoprefixer": true
  }
}
```
package.json
```js
{
"devDependencies": {
    "autoprefixer": "^8.2.0",
    "babel-core": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-runtime": "^6.26.0",
    "cross-env": "^5.1.4",
    "less": "^3.0.1",
    "postcss-modules": "^1.1.0",
    "rimraf": "^2.6.2"
  }
}
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.2
| Node             | 9.2.0
| npm/Yarn         | 5.8.0
| Operating System | macOS

**Comment by chokWing** [comment]
how to resolve this problem?  i meet the same problem

**Comment by DeMoorJasper** [comment]
@chokWing perhaps clear cache?

**Comment by RomkaLTU** [comment]
Same here, it doesn't work.
