### ISSUE TITLE
🙋 Expose 'Options-Singleton'

### ISSUE THREAD

**Issue by nicolaisueper** [parcel-bundler/parcel#1075]
**Choose one:** ~is this a 🐛 bug report or~ 🙋 feature request?

I think this could improve the application development. Maybe I missed something, but I found nothing similiar. 

### 🤔 Expected Behavior

There's one 'Single-Source-Of-Truth' regarding the application configuration, e.g. the cli opts and defaults.

### 😯 Current Behavior

The options get passed to the bundler and down to each component which needs information about the config.

### 💁 Possible Solution

Implement a 'Options-Singleton' which includes the normalized options and can be accessed from any place inside the application.

### 🔦 Context

For #1053 I check `NODE_ENV` for production. Unfortunately `NODE_ENV` equals to undefined when running tests. I could just check the options object, but passing the options down to `getTargetEngine.js` requires a lot of refactoring. 

### 💻 Code Sample

The place where I check for prod build: https://github.com/parcel-bundler/parcel/pull/1053/files#diff-62939a6d4567e7b9e2741ec83de4c4e4R41
The place where I want to test the feature: https://github.com/parcel-bundler/parcel/pull/1053/files#diff-6b823c6b5b196292ad2a7093c93b54a9R631

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | latest master
| Node             | v8.10.0
| npm/Yarn         | yarn v1.5.1
| Operating System | macOS High Sierra

**Comment by DeMoorJasper** [comment]
This is impossible with the current architecture as the workers can't communicate with the master process. This is probably also why it was build this way.
