### ISSUE TITLE
Cannot find module  when reqiure image path use es6 string template

### ISSUE THREAD

**Issue by iamzuijiasunyou** [parcel-bundler/parcel#1076]
![image](https://user-images.githubusercontent.com/15125049/37946340-76aca83e-31b7-11e8-83b5-c0865223c951.png)

**Comment by gnijuohz** [comment]
It seems Parcel currently doesn't support this, see discussions in #125 and #1006.

**Comment by designalchemy** [comment]
One way of doing this, which is pretty terrible

`import icons from './assets/icons/**'

const icon_file_name = 'user'
const specificIcon = icons[`${icon_file_name}.png`]

<img src={specificIcon} />`
