### ISSUE TITLE
How to serve static files?

### ISSUE THREAD

**Issue by saratonite** [parcel-bundler/parcel#1080]
How to serve static files like json , csv, tsv etc.

### 🤔 Expected Behavior

axios.get('data/data.json',).then((data) => console.log(data))

### 😯 Current Behavior

http request failed!!!

**Comment by DeMoorJasper** [comment]
To get the url you can do something like this:
```
const csvFile = require('./data/data.csv');
```
This will return the new hashed unique url of the file instead of the original filename.
JSON Files however return the content instead of the url.
Copying over the files manually should also work

**Comment by donmccurdy** [comment]
The option of bundling a static file is not a real replacement for the option of serving a static file in many cases. For example, an application may have several large datasets in separate files, and should only load them one at a time when needed.

**Comment by lzrski** [comment]
Please correct me if I'm wrong, but it seems like one easy way to achieve that is to run Parcel like this:

```sh
npx parcel src/index.html data/**/*
```

That way all the files in the `data/` directory are considered entry-points, get copied to `dist/data/` and then served at `/data/...`. In my case I only need it for images. Perhaps other types of assets will get processed and won't work so well. 

There is also this: https://www.npmjs.com/package/parcel-plugin-static-files-copy

**Comment by michaschwab** [comment]
@tad-lispy I couldn't get it to run with the combined command, but the plugin you referenced works wonderfully. Thanks!

**Comment by willin** [comment]
@tad-lispy json files are compiled to js files this way...

**Comment by mischnic** [comment]
It just occurred to us that with Parcel 2 alpha 3 and this parcelrc
```json
{
  "extends": "@parcel/config-default",
  "transforms": {
    "url:*": ["@parcel/transformer-raw"]
  }
}
```
you can import files which will then be copied to the dist folder:
```js
import file from "url:./static.json"
fetch(file)...
```

**Comment by daggerok** [comment]
according to @tad-lispy solution, I found this working:

folder structure:

```
my-app-repo-name/
 +- public/
     +- img1.png
     +- img2.png
 +- src/
     +- app.js
     +- index.html
     +- favicon.ico
     +- main.css
package.json
```

_package.son_

```json
{
  "scripts": [
    "build": "parcel build src/index.html",
    "postbuild": "parcel build 'public/**/*'",
    "gh": 'npm run build -- --public-url='/my-app-repo-name/''
  ]
}
```

---
Regards,
Maksim

**Comment by bergkvist** [comment]
For the current version of parcel 2 I'm using (^2.0.0-alpha.3.2), the url:path pattern is default behaviour. So simply use the snippet below to get the url of a static file that you don't want any transpiler to modify:

```js
import csvFileUrl from 'url:file.csv'

// Use the url to fetch the file asynchronously
fetch(csvFileUrl)
  .then(response => ...)
```

You no longer need to modify/create any `.parcelrc` file. 

On a side-note, it also seems like "transforms" has been renamed to "transformers" in `.parcelrc`.

**Comment by vincelwt** [comment]
What I did is use a postbuild script to copy over the static assets:
```json
"scripts": {
  "postbuild": "cp -r public/* dist/",
```

**Comment by tj** [comment]
Would be nice to have an option to serve assets as an SPA would

**Comment by mischnic** [comment]
Have you seen https://github.com/parcel-bundler/website/issues/655 (or the linked issue)?

**Comment by nardove** [comment]
Hi @bergkvist 
I try you snippet but I get the following error: **Failed to install url:..**
I'm using let latest version of Parcel and axios, am I missing another install or plugin?

**Comment by mischnic** [comment]
@nardove Are you sure you're using Parcel 2?

**Comment by nardove** [comment]
I just did npm -v parcel-bundler and got 6.14.5

**Comment by mischnic** [comment]
`yarn parcel --version` or `npm ls parcel`

But if you've installed `parcel-bundler` instead of `parcel`, it's V1 in any case.

**Comment by nardove** [comment]
Correct I made the installation global and look and the package.json file and is indeed v1.12.4, I'll delete this version and install V2 Thank you!

**Comment by nardove** [comment]
Hi @mischnic I got v2 installed and the error is gone, but axios is giving me the index.html as the data response instead of the json file, is there another setting I'm missing? currently I have the .json file in the same folder as the .js files, is that the correct setup?

**Comment by DeMoorJasper** [comment]
It does seem this has been fixed by the `url:` and proxy support in parcel 2. Will close this feel free to re-open and comment if I'm mistaken.
