### ISSUE TITLE
Suggestion: myurl?static should tell parcel to copy the file as-is

### ISSUE THREAD

**Issue by jpeg729** [parcel-bundler/parcel#1084]
There are many situations where people want a way to use a file as-is without its contents being mangled by parceljs. For example...

* In #235 `<link rel="manifest" href="manifest.json">` transforms manifest.json into a .js file
* In #945 `function MyComponent () { return <iframe src='./assets/index.html' /> }` needed the html file to be unadulterated.
* In #1080 `axios.get('data/data.json',).then((data) => console.log(data))` inlines the potentially huge data.json and the http request fails.

What if we could add "?static" to those urls, and have parceljs simply copy the resulting file to `/dist`? Parcel should still mangle the filename for cache busting.

Going a little further, "?static&no-mangle" could tell parcel to copy the file as-is without mangling the filename.

Granted there are workarounds for all of the problems listed above, but it would be nice to have a simple and generic way to sidestep the problem without searching for the specific answer.

**Comment by DeMoorJasper** [comment]
The manifest should work when using `.webmanifest`

**Comment by dandv** [comment]
Another use case: pro/paid libraries that detect when they have been tampered with. These *must* be served unmodified.

**Comment by mischnic** [comment]
Similar to #2306

**Comment by mischnic** [comment]
With Parcel 2 alpha 3 and this parcelrc
```json
{
  "extends": "@parcel/config-default",
  "transforms": {
    "url:*": ["@parcel/transformer-raw"]
  }
}
```
you can import files which will then be copied to the dist folder:
```js
import file from "url:./static.json"
fetch(file)...
```

Regarding syntax discussion (protocol vs query) see here: https://github.com/parcel-bundler/parcel/issues/3477
