### ISSUE TITLE
Upgrading to 1.7.0 will crash

### ISSUE THREAD

**Issue by juliocanares** [parcel-bundler/parcel#1091]
### 🎛 Configuration .babelrc

```js
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "browsers": [
            "last 2 Chrome versions"
          ]
        }
      }
    ],
    "react",
    "react-boilerplate"
  ],
  "plugins": [
    [
      "import",
      {
        "libraryName": "antd",
        "libraryDirectory": "es",
        "style": true
      }
    ],
    [
      "module-resolver", 
      {
        "root": ["./src"],
        "alias": {
          "queries": "./src/graphql/queries",
          "mutations": "./src/graphql/mutations",
          "fragments": "./src/graphql/fragments",
          "styles": "./src/styles",
          "routes": "./src/routes",
          "utils": "./src/utils",
          "components": "./src/components",
          "validators": "./src/validators",
          "constants": "./constants",
          "rules": "./src/rules"
        }
      }
    ],
    "babel-plugin-inline-import-graphql-ast"
  ]
}

```

### 🤔 Expected Behavior

It should just work

### 😯 Current Behavior

It is crashing after updating to the latest release (1.7.0)

### 💁 Possible Solution

idk

### 🔦 Context

We are using `apollo-client`

### 💻 Code Sample

![image](https://user-images.githubusercontent.com/5007653/38068621-c7b6e16a-32d7-11e8-9481-f7f1a685a319.png)

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0 |
| Node             | 9.5.0 |
| npm/Yarn         | 1.3.2 |
| Operating System | macOS High Sierra |

**Comment by DeMoorJasper** [comment]
Any errors we could use?
Or perhaps a code example

**Comment by 3stacks** [comment]
For the record, the upgrade didn't cause any errors for me, albeit with a simpler configuration

`.babelrc`
```
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "browsers": [
            "last 2 versions",
            "last 2 Chrome versions"
          ],
          "node": "current"
        }
      }
    ]
  ],
  "plugins": [
    "transform-runtime"
  ]
}
```

and one alias in package.json

**Comment by juliocanares** [comment]
@DeMoorJasper I've updated the issue including a screenshot of the log.

**Comment by mischnic** [comment]
@juliocanares Is this still an issue? I can't reproduce it locally without a code example
