### ISSUE TITLE
Build does not assign correct paths for relative URL

### ISSUE THREAD

**Issue by taviroquai** [parcel-bundler/parcel#1092]
**Choose one:** 🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

Git repo to replicate issue:
https://github.com/taviroquai/ReactSemanticParcel

Build does not assign correct paths for relative URL using:
```
$ parcel build src/index.js --public-url ./
```

### 🤔 Expected Behavior
Relative paths to build assets

### 😯 Current Behavior
index.html contains full paths:
```
<script src="/src.d37f3ef7.js"></script>
```
Also, when click to open semantic modal window, image gives 404 because of full path URL

### 💁 Possible Solution
I have no idea...

### 🔦 Context
Testing React, Semantic UI and ParcelJS

### 💻 Code Sample

Git repo to replicate issue:
https://github.com/taviroquai/ReactSemanticParcel

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0
| Node             | 8.4.0
| npm/Yarn         |npm 5.3.0
| Operating System | Ubuntu 16.04

**Comment by f-a-a** [comment]
Your parcel build command should be pointing to `index.html`:
```bash
parcel build src/index.html --public-url ./
```
and delete your `dist` folder before running `parcel build`

looks ok for me

![2018-03-29 at 12 17 38](https://user-images.githubusercontent.com/19421765/38069851-39dc3cae-334b-11e8-8753-b739a0893103.gif)

**Comment by taviroquai** [comment]
@f-a-a Perfect! I thought I was doing something wrong :) Keep up the great work!

**Comment by bclinkinbeard** [comment]
`--public-url` seems to be ignored in `^2.0.0-beta.1` completely. Regardless of what I provide, the script tag path looks like `/client.3b43ab2b.js`

**Comment by arronhunt** [comment]
I'm having the same problem as @bclinkinbeard. ^2.0.0-beta.1 does not respect --public-url :(

**Comment by tonyhallett** [comment]
This did not work

src/index.html
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Demo</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="index.tsx"></script>
  </body>
</html>
```


"build": "parcel build src/index.html --public-url ./"

Adding the source field to package.json
`"source": "src/index.html"`

This works
`"build": "parcel build --public-url ./",`
