### ISSUE TITLE
How to achieve automatic vendor splitting?

### ISSUE THREAD

**Issue by stevefan1999** [parcel-bundler/parcel#1094]
So I wanted to separate modules (and polyfills) from `node_modules` but the current state of Parcel doesn't really seem to do that...What if we could make the main app scripts separated like `main.<hash>.js`, `vendor.<hash>.js` and `polyfill.<hash>.js`? Thank you.

**Comment by stevefan1999** [comment]
Indeed we could use something like:

```
const React, {Component} = import("react")
```

Yet it is smelly in terms of code and strays away from ES Standard. Definitely no good.

**Comment by fathyb** [comment]
There is an RFC for this: #885. To make your code work you'd need to use `await` somewhere in an `async function`, or `Promise.then` :

```js
const React, {Component} = await import("react")
```

**Comment by DeMoorJasper** [comment]
I'll close this down as it's duplicated/related and centralised discussion is always better
