### ISSUE TITLE
Typescript + Preact doesn't work right now

### ISSUE THREAD

**Issue by matthewmueller** [parcel-bundler/parcel#1095]
🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

**index.html**

```html
<html>

<head>
</head>

<body>
  <h2>hi</h2>
  <script src="./index.tsx"></script>
</body>

</html>
```

**index.tsx**

```tsx
import { h, render } from 'preact'

render(<h2>hi</h2>, document.body)
```

**Resulting in:**

```
Uncaught ReferenceError: h is not defined
```

### 💁 Possible Solution

I'm pretty sure it's related to missing `"jsxFactory": "h",` in the Typescript asset class: https://github.com/parcel-bundler/parcel/blob/master/src/assets/TypeScriptAsset.js#L16

The compiled output looks like this:

```js
var preact_1 = require("preact");

preact_1.render(h(
  "h2",
  null,
  "hi"
), document.body);
``` 

You'll notice that it's just `h(...)`, even though it should be `preact_1.h(...)`

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0
| Node             | v8.10.0
| npm/Yarn         | npm@5.6.0
| Operating System | osx

**Comment by matthewmueller** [comment]
Actually, I suspect none of the alt-Reacts work. The tests don't actually evaluate the code. For example, modifying this test will cause it to fail.

```js
it('should support compiling JSX in JS files with Preact dependency', async function() {
  const b = await bundle(__dirname + '/integration/jsx-preact/index.js');

  let file = fs.readFileSync(__dirname + '/dist/index.js', 'utf8');
  assert(file.includes('h("div"'));

  let output = run(b);
  console.log(output.default());
});
```

**Comment by DeMoorJasper** [comment]
@matthewmueller Do you have any time to PR some tests to test alt-reacts?
If you have time to fix it would be even better

**Comment by matthewmueller** [comment]
I can PR some failing tests if that would be helpful. I'm not familiar enough with how parcel/babel does this compilation to make a fix though. 

Half of me feels like I'm doing something wrong here, because I'm not able to get *any* react examples working:

```html
<html>

<head></head>

<body>
  <script src="./index.jsx"></script>
</body>

</html>
```

```jsx
import {render} from 'react-dom';

render(<div>hi</div>, document.body);
```

**Comment by matthewmueller** [comment]
Ahh right, sorry I tried `import { createElement } from 'react'`, but that didn't work. I suspect `import React from 'react'` would work though.

**Comment by chimon2000** [comment]
I ran into this issue and resolved it by changing `"jsx": "preserve"` to `"jsx": "react"` in my **tsconfig.json**

@matthewmueller

**Comment by matthewmueller** [comment]
@chimon2000, nice, thanks for sharing. i think that's the way to go. i think the underlying problem is that babel can't figure out the format typescript spits out (e.g. `react => react_1`), so it has no idea that it needs to attach `createElement` onto `react_1.createElement`. 

It doesn't seem like `preserve` is ever the right option, though maybe if the compiler used a non-commonjs output, it works better.

**Comment by tnhu** [comment]
I'm experiencing the same issue.

**Comment by qwertie** [comment]
I'm having the opposite problem: Parcel's output refers to `h` when it should be using `React.createElement`. That's because my preact code is pretending to be React code, just with imports changed:

    import * as React from 'preact';
    import * as ReactDOM from 'preact';

Adding /** jsx React.createElement */` to the top of file has no effect, so I'm using a workaround:

    var h = React.createElement;

**Comment by qwertie** [comment]
Huh, this is interesting. If I delete package.json, package-lock.json, .cache, dist, and node_modules - leaving nothing but app.tsx and index.html - then my problem does not occur.

If I then stop `parcel`, delete `dist` and run it again - it still works.

But if I stop `parcel`, delete `dist` and `cache` and run it again - BAM! It breaks. So I checked what changes between the "bad" copy of `app.402dade7.js` and the "good" copy of `app.402dade7.js`:

~~~
C:\....>diff app.402dade7-bad.js app.402dade7-good.js
80c80
< })({10:[function(require,module,exports) {
---
> })({12:[function(require,module,exports) {
1096c1096
< },{}],5:[function(require,module,exports) {
---
> },{}],6:[function(require,module,exports) {
1136c1136
<         return h(
---
>         return React.createElement(
1139c1139
<             h(
---
>             React.createElement(
1144c1144
<             h(
---
>             React.createElement(
1157c1157
< ReactDOM.render(h(App, { greeting: "Hello, world!" }), document.getElementById('app'), document.getElementById('app').
lastChild // extra argument for preact
---
> ReactDOM.render(React.createElement(App, { greeting: "Hello, world!" }), document.getElementById('app'), document.getE
lementById('app').lastChild // extra argument for preact
1159c1159
< },{"preact":10}],12:[function(require,module,exports) {
---
> },{"preact":12}],14:[function(require,module,exports) {
1189c1189
<   var ws = new WebSocket(protocol + '://' + hostname + ':' + '62857' + '/');
---
>   var ws = new WebSocket(protocol + '://' + hostname + ':' + '63142' + '/');
1328c1328
< },{}]},{},[12,5])
---
> },{}]},{},[14,6])
~~~

**Comment by SeedyROM** [comment]
I changed my `tsconfig.json` to match the syntax of this repo [here](https://github.com/Litee/playground-parcel-preact-typescript) while also following the advice to add the jsx-loader to by `.babelrc` and have managed to get parcel to handle TSX and Preact at once. This probably isn't too helpful, so I'll make a repo to share my basic code.

**Comment by hugollm** [comment]
Mine worked just from changing my `tsconfig.json` from:

```
{
    "jsx": "react",
    "jsxFactory": "h"
}
```

To: 

```
{
    "compilerOptions": {
        "jsx": "react",
        "jsxFactory": "h"
    }
}
```

Also `import preact from 'preact'` (using factory `preact.h`) doesn't work anymore in Preact 10.
So I changed to `import { h, render } from 'preact'`.

**Comment by jedimonkey** [comment]
I had the same issue after upgrading preact from 10.2 to 10.3. I already had the above tsconfig.json and was rather stuck - but adding babel based from this: https://github.com/developit/babel-preset-preact worked! I just used `env` preset rather than `es2015`.

**Comment by FDiskas** [comment]
Same problem again - latest and greatest
```
"parcel": "^2.0.0-nightly.500",
"preact": "^10.5.8",
```
No extra babel files or settings.
tsconfig.json
```
{
  "compilerOptions": {
    "esModuleInterop": true,
    "jsx": "react",
    "jsxFactory": "h",
    "lib": [
      "dom",
      "esnext"
    ],
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "target": "es5"
  }
}
```

**Comment by mischnic** [comment]
@FDiskas can you open a new issue with a code sample and the error you're getting?
