### ISSUE TITLE
Serving html files with links to static assets (pdf, jpg) produces error "ENOENT: no such file or directory"

### ISSUE THREAD

**Issue by prosellen** [parcel-bundler/parcel#1096]
🐛 bug report 

#### cli command
```bash
parcel src/index.html
```

#### src/index.html
```html
<html>
    <head>
    </head>
    <body>  
        <a href="./downloads/hello.pdf" target="_blank">This is a link to a PDF-File</a>   
    </body>
</html>
```

#### Project structure
```bash
├── dist
├── src
│   ├── downloads
│   │   ├── hello.pdf
│   ├── index.html
├── package.json
```

### 🤔 Expected Behavior
```parcel src/index.html``` should spin up the internal server
```parcel build src/index.html --public-url ./``` should build the project into the /dist/ folder

### 😯 Current Behavior
As long as the html file contains an anchor link to a static resource like a pdf or an image, Parcel throws the following error: 
`×  ENOENT: no such file or directory, open 'C:\Users\path\to\project\dist\downloads\hello.pdf'`

The same goes for images. This will produce an error:
```<a href="./downloads/cat.jpg" target="_blank">Linktext</a>```  

__However__ if I add the linked image as an `<img>` it will work just fine:
```<a href="./downloads/cat.jpg" target="_blank"><img src="./downloads/cat.jpg" /></a>```  

This seems to be new since I updated to v1.7 - I didn't get the errors when using v1.6.2

### 🔦 Context
Trying to serve/build a project

### 💻 Code Sample
https://github.com/prosellen/parcel-enoent-text

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7
| Node             | 8.9.0
| npm         | 5.5.1
| Operating System | Windows 10

**Comment by malonehedges** [comment]
@Ty3uK This isn't fixed when using `import()` statements with #1097. 

```js
// Works
const x = require('./someDir/*')
console.log(x)

// Throws error attached below
import('./someDir/*').then((stuff) => {
  console.log(stuff)
})
```

Error:
```
ENOENT: no such file or directory, open '/path/to/project/src/someDir/*'
```

**Comment by DeMoorJasper** [comment]
I'll close this issue as it seems to be resolved through the PR.

Feel free to open a new issue @malonehedges as this seems to be an unrelated issue

**Comment by malonehedges** [comment]
@DeMoorJasper I don't see how it is unrelated. Why should the error mentioned in the original issue only occur when using `import()` and not `require`?

**Comment by DeMoorJasper** [comment]
Because your error is related to dynamic imports not a simple directory doesn't exist error.
I'm pretty sure yours will be more complex to fix and is unrelated
