### ISSUE TITLE
🐛 Can't serve static resources with no filename extension

### ISSUE THREAD

**Issue by davidsoergel** [parcel-bundler/parcel#1098]
🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

```sh
NODE_ENV=development parcel serve -d dist --open --no-hmr --public-url / index.html
```

### 🤔 Expected Behavior

Static resources placed inside ./dist/ should be served regardless of filename extension.

In particular, files with no extension at all should be served with `content-type: application/octet-stream`.

### 😯 Current Behavior

Files with no extension are [specifically ignored](https://github.com/parcel-bundler/parcel/blob/master/src/Server.js#L50) and the main HTML bundle is sent instead.  Adding any extension, even a meaningless one (e.g. `.foobar`) causes the file to serve properly. 

See also #974, #782, and (maybe peripherally related) #536 and #303.

### 💁 Possible Solution

Remove the "empty extension" test and let the file be served.

### 🔦 Context

After loading, my webapp fetches static resources that are just blobs with no filename extension.  I want to use parcel serve during development, so I just put the static resources under ./dist/ in hopes of serving them.  The resource format is not under my control so I can't just add a filename extension to those files.

For now my workaround is to serve just the resources using an http-server on a different port, but that's pretty unwieldy.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0
| Node             | 8.10.0
| npm/Yarn         | 1.4.0
| Operating System | MacOS 10.13.3

**Comment by devongovett** [comment]
Wait, why do you have files without an extension and how do they get to your dist folder? Parcel doesn’t generate files without extensions

**Comment by nsthorat** [comment]
+1 - I don't think the bundler / http server should be making decisions about file extensions for the application for the author :)

**Comment by yingshaoxo** [comment]
I do think that either `tensorflow.js` or `parcel` needs to do some serious change.

https://github.com/elwin013/parcel-plugin-static-files-copy/issues/37

https://github.com/tensorflow/tfjs/issues/924

**Comment by nestarz** [comment]
I neither can't use my files without extensions, and I don't have the option to change its name.

**Comment by t3hmrman** [comment]
For those who might run into this in the future and want a simple solution that works relatively easily and as expected for Parcel 2 [`elwin013/parcel-reporter-static-files-copy`](https://github.com/elwin013/parcel-reporter-static-files-copy)

**Comment by pulpdood** [comment]
I need to verify my domain for Apple Pay, and this requires serving a static file without a file extension, so there is a use case for this. The parcel static files copy reporter, while helpful, doesn't actually solve the issue of parcel not serving files without a file extension.

EDIT: never mind, just realised that files without extensions can be served when built on a server, which works well. It's just not available on locally served environment which is fine
