### ISSUE TITLE
UnhandledPromiseRejectionWarning when building.

### ISSUE THREAD

**Issue by ejnaren** [parcel-bundler/parcel#11]
Hi. As many others I am very excited for the work you are doing here. Badly needed.
I have stumpled upon a slight problem building even just the simplest html file:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <p>Hello...</p>
  </body>
</html>
```

After running parcel index.html, the "dist" folder is created but it is empty.
The following is the console errors:

```
Server running at http://localhost:1234
⏳  Building index.html...
(node:11164) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3001): RangeError: Maximum call stack size exceeded
(node:11164) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Nedlinin** [comment]
Confirming this happens to me as well.  Node 9.1.0

**Comment by mog13** [comment]
I'm having the same problem. Node V 9.2.0 following the simple getting started index.html and index.js

**Comment by devongovett** [comment]
hmm, is this node 9 specific? I've tested against node 8 so far.

**Comment by ejnaren** [comment]
Happens to me in both 8 and 9.

**Comment by hinell** [comment]
Same here:

## Error
```
Server running at http://localhost:1234
⏳  Building index.html...
(node:2520) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3001): 
RangeError: Maximum call stack size exceeded
(node:2520) [DEP0018] DeprecationWarning: 
Unhandled promise rejections are deprecated. In the future,
promise rejections that are not handled will terminate
the Node.js process with a non-zero exit code.

```


## Steps to reproduce:
```javascript
// module.js
export function helloWorld () {console.log('Hello World!');};
```
```javascript
// index.js
import { helloWorld } from './module';
helloWorld();
```
```html
    <script src="index.js"></script>
```

### Command
`$ parcel index.html`

**Comment by mwarger** [comment]
I followed the getting started and had the same results.  Sample repo here: https://github.com/mwarger/parcel-getting-started-windows

Windows 10
```
parcel 1.0.1
node 9.2.0
```

**Comment by pke** [comment]
This happens even with the simplest html file and no JS involved:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Test</title>
</head>
<body>
  <div id="app"/>
  
</body>
</html>
```

`node v7.10.0`
`parcel-bundler@1.0.1`

**Comment by sylvainpolletvillard** [comment]
Same here on Windows 10 x64, Node v8.2.1. Maybe it only affects Windows users ?

**Comment by kingdaro** [comment]
I get the same error. When I try to do a build on the Windows subsystem for Linux, the error goes away, (but I get a new one)
```
🚨  /mnt/d/Projects/parcel-test/index.js: MOZ_TO_ME[node.type] is not a function
    at from_moz (eval at <anonymous> (/mnt/d/Projects/parcel-test/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:10753:54)
    at Object.From_Moz_AssignmentExpression [as AssignmentExpression] (eval at map (eval at <anonymous> (/mnt/d/Projects/parcel-test/node_modules/uglify-js/tools/node.js:21:1)), <anonymous>:9:8)    at from_moz (eval at <anonymous> (/mnt/d/Projects/parcel-test/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:10753:54)
    at Object.ExpressionStatement (eval at <anonymous> (/mnt/d/Projects/parcel-test/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:10292:23)
    at from_moz (eval at <anonymous> (/mnt/d/Projects/parcel-test/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:10753:54)
    at Array.map (<anonymous>)
    at Object.Program (eval at <anonymous> (/mnt/d/Projects/parcel-test/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:10267:51)
    at from_moz (eval at <anonymous> (/mnt/d/Projects/parcel-test/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:10753:54)
    at Function.AST_Node.from_mozilla_ast (eval at <anonymous> (/mnt/d/Projects/parcel-test/node_modules/uglify-js/tools/node.js:21:1), <anonymous>:10761:19)
    at module.exports (/mnt/d/Projects/parcel-test/node_modules/parcel-bundler/src/transforms/uglify.js:10:22)
```
So it does appear to be a Windows issue.

**Comment by stevefan1999** [comment]
Same here. Windows 10 x64 will yield `Maximum call stack size exceeded`. Works pretty well on WSL.

**Comment by devongovett** [comment]
hmm, seems like a windows issue 😢? I can try to setup a vm to test, but would be great if someone could dig into this a bit and get more info on the errors being logged there (e.g. what promise is being rejected, etc.). Thanks in advance for your help! 😄

**Comment by e2goon** [comment]
I'm having the same problem

**Comment by hyrious** [comment]
@devongovett It turns out that [src/utils/config.js#L6](https://github.com/parcel-bundler/parcel/blob/master/src/utils/config.js#L6) got recursive calling itself, which causes *Maximum call stack size exceeded*. Not find out how to solve it yet.
I got this information by `mocha`, here is the stack trace:

[test/css.js#L8](https://github.com/parcel-bundler/parcel/blob/master/test/css.js#L8) in `describe('css', function () {`
```js
    let b = await bundle(__dirname + '/integration/css/index.js');
```
[src/Bundler.js#L275](https://github.com/parcel-bundler/parcel/blob/master/src/Bundler.js#L275) in `async loadAsset(asset) {`
```js
      processed = await this.farm.run(asset.name, asset.package, this.options);
```
[src/WorkerFarm.js#L63](https://github.com/parcel-bundler/parcel/blob/master/src/WorkerFarm.js#L63) in `async run(...args) {`
```js
      return this.localWorker.run(...args);
```
[src/worker.js#L20](https://github.com/parcel-bundler/parcel/blob/master/src/worker.js#L20) in `exports.run = async function (path, pkg, options, callback) {`
```js
    await asset.process();
```
[src/assets/JSAsset.js#L72](https://github.com/parcel-bundler/parcel/blob/master/src/assets/JSAsset.js#L72) in `async pretransform() {`
```js
    await babel(this);
```
[src/transforms/babel.js#L39](https://github.com/parcel-bundler/parcel/blob/master/src/transforms/babel.js#L39) in `async function shouldTransform(asset) {`
```js
  let babelrc = await config.resolve(asset.name, ['.babelrc', '.babelrc.js']);
```
[src/utils/config.js#L25](https://github.com/parcel-bundler/parcel/blob/master/src/utils/config.js#L25) in `async function resolve(filepath, filenames, root = '/') {`
```js
  return resolve(filepath, filenames, root);
```

**Comment by e2goon** [comment]
[src/utils/config.js#L25](https://github.com/parcel-bundler/parcel/blob/master/src/utils/config.js#L25)

```javascript
resolve(filepath, filenames, root);
```

Let's look at the return value in Windows and Mac environments.

![image](https://user-images.githubusercontent.com/45934/33652440-d26eaada-daac-11e7-9237-88d4c7b4e858.png)

**Comment by hyrious** [comment]
In [src/utils/config.js#L10](https://github.com/parcel-bundler/parcel/blob/master/src/utils/config.js#L10), I did:
replace `filepath === root` with `filepath === root || filepath === path.dirname(filepath)`,
then I run test again, got these:
<details>
<pre><code>&gt; mocha


  css
    √ should produce two bundles when importing a CSS file (2301ms)
    √ should support loading a CSS bundle along side dynamic imports (1234ms)
    √ should support importing CSS from a CSS file
    √ should support linking to assets with url() from CSS
    1) should support transforming with postcss
    √ should minify CSS in production mode (325ms)

  fs
    √ should inline a file as a string
    √ should inline a file as a buffer (113ms)
    √ should inline a file with fs require alias
    √ should inline a file with fs require inline
    √ should inline a file with fs require assignment
    √ should inline a file with fs require assignment alias
    √ should inline a file with fs require destructure
    √ should inline a file with fs require destructure assignment

  glob
    2) should require a glob of files
    3) should require nested directories with a glob
    4) should support importing a glob of CSS files

  hmr
    √ should emit an HMR update for the file that changed (207ms)
    5) "before each" hook for "should emit an HMR update for all new dependencies along with the changed file"


  14 passing (5s)
  5 failing

  1) css
       should support transforming with postcss:

      AssertionError \[ERR_ASSERTION]: '_index_1cehs_1' == '_index_1ezyc_1'
      + expected - actual

      -_index_1cehs_1
      +_index_1ezyc_1

      at Context.&lt;anonymous&gt; (test\css.js:119:12)
      at &lt;anonymous&gt;

  2) glob
       should require a glob of files:
     TypeError: Cannot read property 'name' of undefined
      at assertBundleTree (test\utils.js:63:39)
      at Context.&lt;anonymous&gt; (test\glob.js:9:5)
      at &lt;anonymous&gt;
      at process._tickCallback (internal/process/next_tick.js:188:7)

  3) glob
       should require nested directories with a glob:
     TypeError: Cannot read property 'name' of undefined
      at assertBundleTree (test\utils.js:63:39)
      at Context.&lt;anonymous&gt; (test\glob.js:23:5)
      at &lt;anonymous&gt;
      at process._tickCallback (internal/process/next_tick.js:188:7)

  4) glob
       should support importing a glob of CSS files:
     TypeError: Cannot read property 'name' of undefined
      at assertBundleTree (test\utils.js:63:39)
      at Context.&lt;anonymous&gt; (test\glob.js:37:5)
      at &lt;anonymous&gt;
      at process._tickCallback (internal/process/next_tick.js:188:7)

  5) "before each" hook for "should emit an HMR update for all new dependencies along with the changed file":
     Error: ENOTEMPTY: directory not empty, rmdir 'D:\inbox\parcel\test\dist'
      at Object.fs.rmdirSync (fs.js:846:18)
      at rmkidsSync (node_modules\rimraf\rimraf.js:356:25)
      at rmdirSync (node_modules\rimraf\rimraf.js:334:7)
      at Function.rimrafSync \[as sync] (node_modules\rimraf\rimraf.js:304:9)
      at Context.&lt;anonymous&gt; (test\utils.js:10:10)</code></pre></details>

**Comment by thejameskyle** [comment]
It's probably that `root` is `/`, but on Window file paths are split up by `\` and I think the root of the file system has a prefix?

**Comment by StarpTech** [comment]
@thejameskyle exactly, I created a PR https://github.com/parcel-bundler/parcel/pull/48

**Comment by lifeart** [comment]
Same for node v7.9.0, win10 x64, parcel 1.2

**Comment by hyingreborn** [comment]
when we can use the version 1.0.3 ?

**Comment by devongovett** [comment]
Published v1.0.3.

**Comment by burlesona** [comment]
Just for what it's worth I got this exact same error trying parcel on MacOS High Sierra with a minimum HTML page and Node 6x latest. Looks like Parcel requires >= 8x, as switching from Boron to Carbon fixed it. Would probably be worth noting this on the docs, as I couldn't find anything indicating which version of Node was required.

**Comment by cdll** [comment]
same issue here with 
````
OS: macOS 10.15(i5+8+256)
nodejs: v10.15.3
parcel-bundler: 1.12.4
````
