### ISSUE TITLE
Fork Create-React-App

### ISSUE THREAD

**Issue by davidnagli** [parcel-bundler/parcel#110]
🙋 feature request

What if we fork create-react-app and replace WebPack with Parcel to make create-react-app more performant.

90% of create-react-app is just dealing with WebPack boilerplate, so if we could reimplement create-react-app using Parcel we can reduce the size of create-react-app and show people how awesome Parcel is.

**Comment by devongovett** [comment]
cool idea. another one that might be interesting is a fork of storybooks to use parcel as well - that one I'd definitely use.

**Comment by pungggi** [comment]
What are the advantages of forking all these projects? I understand that Things may go faster.. But CRA does already solve the problem of handling complex configuration.. So why should one use the fork and risking not getting updated over time?

**Comment by chee** [comment]
here is my implementation of `create-parcel-react-app`

https://gist.github.com/chee/9ca084e2da224fee8d73d36c476c873f

🌮 🚥

**Comment by pke** [comment]
or react-styleguidist over storybook. Less DSL more instant markdown power.

**Comment by brandon93s** [comment]
There's now an examples repo (https://github.com/parcel-bundler/examples) which is perfect to house the boilerplates and forks.

**Comment by davidnagli** [comment]
@brandon93s Not sure how we can place a fork under another repo ([parcel-bundler/examples](https://github.com/parcel-bundler/examples)). Is there a way we could do this? I kinda assumed we would need to just house the fork separately.

**Comment by brandon93s** [comment]
A few options come to mind:

1) Don't use a real fork; just copy the implementation  (license permitting) and update it to use `parcel`. This is the simplest approach, and the examples would be static (not linked to original project).
2) Use `git subtree` ([ref](http://alistra.ghost.io/2014/11/30/git-subtree-a-better-alternative-to-git-submodule/)). This could become a mess to maintain though if we ever actually try to merge from the parent repo.

**Comment by devongovett** [comment]
If someone wants to work on these, the best way would be to make a personal repo for now. If eventually we want to make them community projects, we can fold them into the parcel org or back into the storybook/create-react-app/etc. org if they are willing.

**Comment by mBeierl** [comment]
I'm also very interested in a storybook integration. Has anybody started working on this? Otherwise, I will create a repo for this.

**Comment by matthewpereira** [comment]
@mBeierl Could you link to it here if you manage to get a parcel + storybook repo going? I'd be interested in checking out your configuration.

**Comment by mBeierl** [comment]
@matthewpereira I sure will! I will try to get something rolling this weekend

**Comment by jeroenptrs** [comment]
I made a boilerplate with jest and jss in there alongside parcel, not really a create-react-with-parcel, but it's a start 😅 https://github.com/jeroenptrs/react-stack-boilerplate

**Comment by sw-yx** [comment]
hello! i made https://github.com/sw-yx/create-react-app-parcel please have a try! has a bunch of nice defaults with regards to developing (public class fields), building and ejecting.
