### ISSUE TITLE
https://github.com/thian4/parcel-error

### ISSUE THREAD

**Issue by thian4** [parcel-bundler/parcel#1102]
Why I got error of 

When I try to import complied code using import?

eg. 
```
import Test from './lib/text'
render() { return <Test /> }
```

https://github.com/thian4/parcel-error

**Comment by DeMoorJasper** [comment]
Appears you have fixed it in the example

**Comment by thian4** [comment]
@DeMoorJasper nope, check this file https://github.com/thian4/parcel-error/blob/master/src/index.js on line 6, why I can't use the complied version?

**Comment by thian4** [comment]
I found a hint, I used webpack to do the same thing

https://github.com/thian4/webpack-problem

I got the same error, but I solved it by adding this to my webpack.prod.js

```
output: {
        path: path.resolve(__dirname, 'lib'),
        filename: '[name].js',
        libraryTarget: "umd" // added this
    },
```

so if in parcel there's option for libraryTarget: "umd" I think the issue will be solved.

**Comment by DeMoorJasper** [comment]
I'll close this off in favor of #766 as UMD is a planned feature for the next release feel free to join the discussion and implementation :)
