### ISSUE TITLE
Better error messages for Webpack loader imports

### ISSUE THREAD

**Issue by jamiebuilds** [parcel-bundler/parcel#1107]
```js
import mod from "loader!module"
```

Would be nice to special case this and output an error pointing to the import and explaining that it is a non-standard Webpack specific syntax and is not supported by Parcel.

As of 1.7, Parcel actually tries to install a package titled `"loader!module"`

**Comment by jamiebuilds** [comment]
This is the error right now when you pass `--no-autoinstall`, which isn't bad, but could probably still use special handling (autoinstall definitely does)

```
🚨  /path/to/file.js:4:26: Cannot resolve dependency 'loader!.'
  1 |
> 2 | import module from 'loader!../module';
    |                    ^
  3 |
```

**Comment by jamiebuilds** [comment]
Here is the relevant code for auto install:

https://github.com/parcel-bundler/parcel/blob/0140dcea58edd0df5959752e38faf41b96a1d509/src/utils/installPackage.js#L12

**Comment by jamiebuilds** [comment]
And here is the relevant resolver code: https://github.com/parcel-bundler/parcel/blob/9d6061c2ede15af601764ec102389ba8f3f5f790/src/Bundler.js#L361-L368

**Comment by himanshuchauhan** [comment]
I would like to work on this, any pointers?

**Comment by DeMoorJasper** [comment]
@himanshuchauhan you could research some of the webpack specific import syntaxes and write a regex to catch them in the resolver and throw a warning or error.
throwing an error would just be `throw new Error(...)` warning would be `require('./Logger').warning(...)`

**Comment by TheLarkInn** [comment]
The webpack resolver is completely in a separate package and already handles the work of splitting out these requests quite eloquently. Perhaps it makes sense to leverage this or check that code ❤️

**Comment by pratitidevelop** [comment]
I would like to work on this issue, any suggestions ?

**Comment by DeMoorJasper** [comment]
@pratitidevelop 
> you could research some of the webpack specific import syntaxes and write a regex to catch them in the resolver and throw a warning or error. (Jamie already added the relative files in the issue)
throwing an error would just be throw new Error(...) warning would be require('./Logger').warning(...)

**Comment by prateekgoel** [comment]
Seems like this is open to work. I will start working on this.
@DeMoorJasper Can you please guide me to the code I need to add regex to?

**Comment by prateekgoel** [comment]
@DeMoorJasper How about using https://github.com/benmosher/eslint-plugin-import instead of handling this case ourselves?
It is a much-used library and used as a standard in many projects.

**Comment by DeMoorJasper** [comment]
@prateekgoel seems a bit much for this usecase

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mischnic** [comment]
Implemented here:
https://github.com/parcel-bundler/parcel/blob/04e673d1d67cb5cf5ac6eed73b3aa9d597fc4ef8/packages/resolvers/default/src/DefaultResolver.js#L12-L17
