### ISSUE TITLE
parcel 1.7.0 does not install via npm on arch linux arm

### ISSUE THREAD

**Issue by hondagx35** [parcel-bundler/parcel#1114]
🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["env"]
}
```

### 🤔 Expected Behavior

it should install as 1.6.2 does
`npm install -g parcel-bundler@1.6.2`
works, but
`npm install -g parcel-bundler`
does not

### 😯 Current Behavior
```
npm install -g parcel-bundler
/root/.nvm/versions/node/v9.10.1/bin/parcel -> /root/.nvm/versions/node/v9.10.1/lib/node_modules/parcel-bundler/bin/cli.js

> deasync@0.1.12 install /root/.nvm/versions/node/v9.10.1/lib/node_modules/parcel-bundler/node_modules/deasync
> node ./build.js

gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/root/.nvm/versions/node/v9.10.1/lib/node_modules/parcel-bundler/node_modules/deasync/build'
gyp ERR! System Linux 4.14.18-1-ARCH
gyp ERR! command "/root/.nvm/versions/node/v9.10.1/bin/node" "/root/.nvm/versions/node/v9.10.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.nvm/versions/node/v9.10.1/lib/node_modules/parcel-bundler/node_modules/deasync
gyp ERR! node -v v9.10.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/parcel-bundler/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.12 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-01T12_39_49_046Z-debug.log
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |     1.7.0
| Node             |     9.10.1
| npm/Yarn         |      5.6.0
| Operating System |      armv7l GNU/Linux

**Comment by DeMoorJasper** [comment]
Seems like a permission issue, looking at the error log

**Comment by hondagx35** [comment]
npm install -g parcel-bundler

I am running this as "root"

`mkdir '/root/.nvm/versions/node/v9.10.1/lib/node_modules/parcel-bundler/node_modules/deasync/build'`
can not work because parent directories do not exist 
but
`mkdir -p  '/root/.nvm/versions/node/v9.10.1/lib/node_modules/parcel-bundler/node_modules/deasync/build'`
would work

**Comment by DeMoorJasper** [comment]
The `deasync` dependency got added in v1.7, might be a bug in their install script?

**Comment by Ayllium-Rin** [comment]
I'm having a similar issue on Ubuntu 16.04.  I'm going to try to install 1.6.2 and see if that will work.  Fwiw, I've tried as root too and still nothing.

**Comment by Ayllium-Rin** [comment]
Ok, I figured out my issue.  The "most recent" version of node.js on my computer was 4.2..... I needed to install nvm to upgrade to the real most recent version.  After that, npm install -g parcel-bundler worked fine...

**Comment by hondagx35** [comment]
Why is it closed?
My issue is not solved!

**Comment by DeMoorJasper** [comment]
Closed it by mistake and because it's probably not parcel related

**Comment by ACXgit** [comment]
Same issue here with Node.js v.10.0.0 via nvm on a Rpi2. Instead, Parcel v1.6.2 installs just fine.

**Comment by DeMoorJasper** [comment]
@ACXgit deasync has no prebuild binaries for node 10 or arch linux. Perhaps open an issue there

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by styfle** [comment]
I have a similar problem with Alpine Linux 😢

**Comment by styfle** [comment]
@fathyb Thanks! 🎉 

I found another issue that is very similar to what you suggested: https://github.com/mhart/alpine-node/issues/27

**Comment by gearhead** [comment]
why is this closed? it still does not work on RPi2.

**Comment by robo-hamburger** [comment]
Also having a similar problem.

`yarn global add parcel-bundler`

Fails on my raspberrypi.

**Comment by davibe** [comment]
same on raspberry.
this should not be closed. 

```
(installing deasync)
fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"
```

**Comment by thr0w** [comment]
I'm using WSL/ubuntu with root user and solved that error with:

```
npm install -g parcel-bundler --unsafe-perm=true --allow-root
```
