### ISSUE TITLE
Anyone has an example for vue with parcel 1.7?

### ISSUE THREAD

**Issue by EryouHao** [parcel-bundler/parcel#1120]
I can't start a demo for vue with parcel 1.7

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
"devDependencies": {
    "@vue/component-compiler-utils": "^1.0.0",
    "parcel-bundler": "^1.7.0",
    "vue-template-compiler": "^2.5.16"
  },
  "dependencies": {
    "vue": "^2.5.16",
    "vue-hot-reload-api": "^2.3.0"
  }
```

### 🤔 Expected Behavior

build success and show page

### 😯 Current Behavior

Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('2460a97f9b71a1fe86edb387ee18c48a.vue') is not a valid name.

### 💻 Code Sample

```
// src/main.js
import Vue from 'vue'
import App from './App.vue'

const app = new Vue({
  el: '#app',
  render: h => h(App)
})
```
```
// src/App.vue
<template>
  <div class="">
    123
  </div>
</template>

<script>
export default {
}
</script>

<style lang="scss" scoped>

</style>

```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0
| Node             | 9.3.0
| npm/Yarn         | 5.6.0
| Operating System | Mac OS

**Comment by andrewbanchich** [comment]
Did you try adding `name: 'App'` to `App.vue`?

**Comment by EryouHao** [comment]
@andrewbanchich Yes, I tired and it's not work yet.
```
<template>
  <div class="">
    Hello world
  </div>
</template>

<script>
export default {
  name: 'app',
}
</script>

<style lang="scss" scoped>

</style>
```
Still the error.

**Comment by EryouHao** [comment]
@andrewbanchich thanks, I solved this problem because my global parcel version is too low.
