### ISSUE TITLE
[feature request]output ip address

### ISSUE THREAD

**Issue by lili21** [parcel-bundler/parcel#1121]
🙋 feature request

### 🔦 Context

It would be nice to have this feature. there are plenty times I want to visit my local serve through my phone, or let my coworker look at it while developing.  something like this would be enough.

![image](https://user-images.githubusercontent.com/4456380/38182198-70dcf80c-366a-11e8-8fae-c38da65e8a5e.png)

**Comment by mischnic** [comment]
Closing this as @devongovett commented in the PR:
> I think this is a useful feature in certain instances, but I hesitate to enable it by default as it might be confusing for beginners to have multiple urls in their terminal. I'd rather keep the noise to a minimum. It's not to hard to look up your computer's IP address by other means when you need to do that.
