### ISSUE TITLE
Parcel lowercasing Vue attributes

### ISSUE THREAD

**Issue by andrewbanchich** [parcel-bundler/parcel#1123]
🐛 bug report

I noticed that my logo component in Vue is huge when I run `parcel index.html`. I looked at both the Webpack output code and the Parcel output code and the only thing that was different was that Parcel caused my SVG's `viewBox` attribute to be all lowercase (`viewbox`) which breaks it (at least in the latest version of FireFox).

After testing it out some more, I noticed it doesn't change the capitalization when I remove the `use` elements and `xlink`.

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
	"presets": [
		["env", {
			"modules": false,
			"targets": {
				"browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
			}
		}],
		"stage-2"
	],
	"plugins": [
		"transform-runtime"
	],
	"env": {
		"test": {
			"presets": ["env", "stage-2"],
			"plugins": ["istanbul"]
		}
	}
}
```

**Comment by Hammster** [comment]
Can confirm this issue.

Error in console:
```
Prop "isselected" is passed to component <Anonymous>, but the declared prop name is "isSelected"
```
