### ISSUE TITLE
Vue event shorthand error when building

### ISSUE THREAD

**Issue by andrewbanchich** [parcel-bundler/parcel#1124]
I am getting this error when running `parcel build`. I use the Vue event shorthand (e.g. `@click`) so I thought it could be related to that, but looking at the component code itself, I don't think it is. I didn't use that shorthand anywhere on it.

🚨  Error in parsing SVG: Invalid attribute name
Line: 0
Column: 201
Char: @

**Comment by mrobakowski** [comment]
I'm getting the same. Doesn't happen when I do `parcel build --no-minify` btw.

**Comment by DeMoorJasper** [comment]
This is an svgo error. At least at first sight it seems like one, same error template as other svgo errors i've seen and only happens in minify mode 99% sure it is

**Comment by mrobakowski** [comment]
I'm debugging this right now. I've got inline svg in a vue component template. Seems like parcel's extracted svg from the template and is trying to optimize it, even though it still has some vue-specific syntax.

**Comment by mrobakowski** [comment]
So yeah, turns out running htmlnano on a vue template which contains an svg with vue event shortcuts is a bad idea. A quick and dirty fix is just checking whether the html asset is a part of a vue file, and not minify it in that case:

```js
  // src/assets/HTMLAsset.js, lines 157-161
  async transform() {
    if (this.options.minify && !this.basename.endsWith(".vue")) {
      await htmlnanoTransform(this);
    }
  }
```

**Comment by mrobakowski** [comment]
Btw, turning minification off for this one case isn't as bad as one may think. The template ends up being js code either way, and that is minified.

**Comment by DeMoorJasper** [comment]
It's not a big issue to turn of minification for this, but it's a bit of a dirty fix, perhaps we could pass some custom options per asset, so that we still develop each asset type in a plugin style and independent of each other and the core

**Comment by mrobakowski** [comment]
In the meantime, if there's anyone that needs a fix for this urgently (like me :smile:), they can use a plugin.

`index.js`
```js
module.exports = function(bundler) {
  bundler.addAssetType('html', require('path').resolve(__dirname + '/HTMLAsset.js'))
}
```

`HTMLAsset.js`
```js
const HTMLAssetsOfficial = require('parcel-bundler/src/assets/HTMLAsset.js');

class HTMLAsset extends HTMLAssetsOfficial {
  async transform() {
    if (this.basename.endsWith(".vue")) return;
    await super.transform();
  }
}

module.exports = HTMLAsset;
```

`package.json`
```json
{
  "name": "parcel-plugin-na-dashboard",
  "version": "0.0.1"
}
```

Throw the three files above into a folder named `parcel-plugin-whatevernameyouwish` in your project and add 
```json
    "parcel-plugin-whatevernameyouwish": "file:./parcel-plugin-whatevernameyouwish",
```
to your main `package.json` dev-dependencies

**Comment by DeMoorJasper** [comment]
@mrobakowski Probably easier to add a htmlnano config to disable svg minification
.htmlnanorc
```Json
{
  minifySvg: false
}
```

**Comment by adamshaylor** [comment]
I’m using [coreui-vue](https://github.com/coreui/coreui-vue/) and encountering the same problem with SVGO choking on the `&&` boolean operator in a `v-if`:

```
/[path to project]/node_modules/@coreui/icons-vue/src/CIconRaw.vue: Error in parsing SVG: Invalid character in entity name
Line: 0
Column: 18
Char: &
```

I’d love to just disable Vue compression with `{ "minifySvg": false }` in a `.htmlnanorc` as others here have done, but Parcel seems to be ignoring it, so I have to use the `--no-minify` flag for the whole bundle, which is no good. (CoreUI is _heavy_.)

```
❯ npm ls htmlnano
[name of project]@ /[path to project]
└─┬ parcel-bundler@1.12.5
  └── htmlnano@0.2.8
```

I’ll try the plug-in workaround, but I really wish I knew why the `.htmlnanorc` file is being ignored.

**Comment by adamshaylor** [comment]
I figured out that the expected location of `.htmlnanorc` is relative to the source package, not the root package directory. That means that if you want Parcel to stop trying to use it to optimize SVG content in a Vue _dependency_, the `.htmlnanorc` file has to live _in that dependency_. This is arguably hackier than the Parcel plugin workaround, but you can add this `postinstall` to the `scripts` block of your `package.json`:

```json
"echo '{\"minifySvg\":false}' > ./node_modules/@coreui/icons-vue/.htmlnanorc"
```

Where `@coreui/icons-vue` happens to be the name of my dependency.
