### ISSUE TITLE
serve --port default to $PORT?

### ISSUE THREAD

**Issue by jamiebuilds** [parcel-bundler/parcel#1126]
`$PORT` is a really common environment variable for specifying the port to use for web servers. 

We may want to consider defaulting to the value of `process.env.PORT || 1234`

https://github.com/parcel-bundler/parcel/blob/fc041d03c36bf41ea73c398e8d177de1a456e796/src/cli.js#L182

**Comment by ilkerceng** [comment]
Hi @jamiebuilds 
I am getting this error when i try to deploy on heroku: 

> Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch. 

Is it related with that issue? I couldn't fix it.

**Comment by lizzzp1** [comment]
Could I take this issue?

**Comment by foxt** [comment]
> $PORT is a really common environment variable for specifying the port to use for web servers.

Yes, it infact is - and you get very confused why parcel keeps trying to steal the $PORT you set for your application server  🙈
