### ISSUE TITLE
Print stack traces on error

### ISSUE THREAD

**Issue by shawwn** [parcel-bundler/parcel#113]
🐛 bug report

Parcel suppresses stack traces, leading to confusion:

https://github.com/parcel-bundler/parcel/blob/a1a190bb19a2c625ad3af9f4072fbbc8f342f746/src/Logger.js#L67

Users end up seeing "Cannot resolve dependency foo.bar" rather than the actual error.

One solution:

```js
      this.write(((this.color && err.highlightedCodeFrame) || err.codeFrame) + '\n\n' + err.stack);
```

**Comment by thejameskyle** [comment]
Moving to #114

**Comment by thejameskyle** [comment]
I find that leaving things open while there is a PR creates more noise than necessary, but sure

**Comment by devongovett** [comment]
yeah, esp if you are going to immediately fix your own issue as in this case. then just don't open an issue at all - the PR is fine for that.

**Comment by shawwn** [comment]
Alright, noted.
