### ISSUE TITLE
Document  `--no-autoinstall` flag

### ISSUE THREAD

**Issue by tsiq-swyx** [parcel-bundler/parcel#1130]
autoinstall is nice but borders on "too much magic" for me - i was using a React canary version and the darn thing kept overwriting the version for me.  

In https://github.com/parcel-bundler/parcel/issues/1107 i noticed the solution.

the solution is to use the `--no-autoinstall` flag. can we document this? in fact i think the docs should have a whole page with all the flags so i can search it.

as a further DX step, you might want to warn people that you are autoinstalling, and suggest the --noautoinstall flag so that devs dont have to look it up.

just a suggestion, cheers

**Comment by DeMoorJasper** [comment]
All flags are documented either use parcel help or look at the cli part of the docs

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
