### ISSUE TITLE
🐛 *help!* Trouble with Parcel paths / filenames (and the inclusion of "index.html")

### ISSUE THREAD

**Issue by glomotion** [parcel-bundler/parcel#1132]
### 🎛 Configuration (.babelrc, package.json, cli command)
Firstly, apologies for the noob question. I'm not sure this is a bug, more just my lack of understanding how Parcel works RE pathing and relative urls etc.
[Demo repo](https://github.com/glomotion/glo-2/tree/vue-ditch-webpack)

babelrc:
```js
{
  "presets": [
    "env"
  ],
  "plugins": [],
}
```

package.json:
```js
...
"scripts": {
  "start": "parcel index.html --open",
},
...
```

### 🤔 Expected Behavior

Parcel builds out and serves the web app, just as it does when "index.html" is ommitted from the "start" script (eg $ parcel).

### 😯 Current Behavior

Basically, when I run "parcel" without any parameters, the project runs fine, except that the code splitting doesn't seem to actually be happening (I think that's a [known bug](https://github.com/parcel-bundler/parcel/issues/905)), and the output html file is something like: "glo-2.f3cd8f25.html" rather than a clean / servable "index.html". 
--out-file flag settings seem to be ignored. 

When "index.html" is added to the start command (eg. $ parcel index.html), parcel seems to not be able to find any of the files and prints the error:
`🚨  Cannot read property 'add' of undefined
    at JSPackager.addAsset`

### 💁 Possible Solution

I'm reasonably sure this is because I'm doing something wrong with the paths. For the life of me though, I can't seem to get it working.

### 🔦 Context

Basically, im trying to wrap my head around how to get this project working similar to how it works when i simply call "parcel" - but have it output a nice, tidy "index.html" file. 

### 🌍 Your Environment

MacOS 10.13.4
Node v9.8.0
yarn v1.5.1
Parcel 1.7.0

**Comment by TheNando** [comment]
Not sure why or how it works when you run it without specifying the index page. But I can tell you that one problem is that you haven't updated your import syntax in `./src/apps/about/index.js`

Just change
```
const About = () => import('./About');
const Default = () => import('./Default');
const Form = () => import('./Form');
```
to
```
import About from './About';
import Default from './Default';
import Form from './Form';
```
after that, just include the input file name in your build script and it will name it the same thing on output
```
// in package.json
...,
"build": "parcel build index.html", // <- the dist output file will also be named 'index.html'
...,
```

**Comment by JonathanHuot** [comment]
I have the same issue `🚨 Cannot read property 'add' of undefined at JSPackager.addAsset`, I have also multiple directories and subdirectories. However, I have no `const xx .. ` defined as @TheNando suggested.

**Comment by glomotion** [comment]
@TheNando - Sorry for the delayed response. 
So i want those routes to be code-split - thus i'm importing them. Removing the imports works (last I checked) - but of course does not split the code bundle output. 

This issue definitely seems to be related to: https://github.com/parcel-bundler/parcel/issues/905
