### ISSUE TITLE
Can't resolve aliases as prefixes

### ISSUE THREAD

**Issue by zerkalica** [parcel-bundler/parcel#1134]
I use https://github.com/eddyerburgh/react-parcel-starter.git

Add to package.json:
```
  "alias": {
    "qw": "./src"
  }
```

Add to src/index.jsx
```...
import img from 'some/img.png'
```

Add img.png to src

npm run build

```
index.jsx:5:21: Cannot resolve dependency 'some/img.png'
  3 | import Modal from "./components/Modal";
  4 | import "./style/index.scss";
> 5 | import img from 'some/img.png'
```

May be add some power to aliases? Placeholders, regex, index.js|ts|tsx resolving, like https://flow.org/en/docs/config/options/#toc-module-name-mapper-regex-string

**Comment by KatSick** [comment]
I believe, you can use [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) "workaround" for now. But simple package.json config, will be awesome.

**Comment by devongovett** [comment]
Is this still broken for you? I believe support for alias prefixes was added at some point.

**Comment by zerkalica** [comment]
Done, my example works for me.
