### ISSUE TITLE
Serve multiple entries during development (or even production)

### ISSUE THREAD

**Issue by nlhkh** [parcel-bundler/parcel#1136]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
- 🙋 feature request

We have an option to serve one entry with `parcel index.js` or `parcel index.html`. However, I am building a traditional multi-page web application, and each page has a different entry javascript. Therefore using html as the main entry is not an option. Serving multiple entries would ease development (although I think we can already do this by watching multiple files, there might be performance issue though, since there are close to 100 entries for my project).

### 🤔 Expected Behavior

Parcel should be able to serve multiple entries. For example, `parcel file1.js file2.js` should make visible `http://localhost:1234/file1.js` and `http://localhost:1234/file2.js`.

### 😯 Current Behavior

For now, Parcel can only serve 1 main entry. The difference would be that multiple main entries are visible as described above. We want the main entries so they do not have any hash, and another web framework can pick up the files.

### 💁 Possible Solution

Support multiple entries in:
- CLI `parcel entry1.js entry2.js entry3.html ...`
- List of entries in JSON. Create json file `entries.json` with an array of entries filenames. Then run command `parcel --entries entries.json`

### 🔦 Context

This issue is preventing me from using Parcel with a multi-page web app, where I have different html pages (from some html template engine, so I cannot use Parcel to parse the templates). With only ONE main entry being serve, I can only use 1 page at a time. When page navigation comes into play, this becomes an issue.

The context is described above: traditional multipage, with multiple javascript entries (or other asset types).

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel         | 1.7.0 |
| Node          |  9.10.1 |
| npm/Yarn    |   5.6.0  |
| Operating System | OSX |

**Comment by Hammster** [comment]
PR #1119 should add this feature ;)
