### ISSUE TITLE
Hangs while "Building"

### ISSUE THREAD

**Issue by catamphetamine** [parcel-bundler/parcel#1137]
I tried creating a simple project using a couple of not-so-simple libraries and it was good but now it hangs on random files while "Building".

Sometimes it builds and outputs this error:

```
√  Built in 5.48s.
‼  c:\dev\react-website-basic-example\node_modules\mime\mime.js:52:32: Cannot statically evaluate fs argument
  50 |   // Read file and split into lines
  51 |   var map = {},
> 52 |       content = fs.readFileSync(file, 'ascii'),
     |                                 ^
  53 |       lines = content.split(/[\r\n]+/);
  54 |
  55 |   lines.forEach(function(line) {
```

I'm on Windows, perhaps I'll share the project if I find which import causes that.
Perhaps a cyclic dependency?

**Comment by catamphetamine** [comment]
Strange, now it built and didn't output any errors.

**Comment by fathyb** [comment]
You `fs.readFileSync` message is just a warning. Freezing on Windows is a known bug unfortunately, see #900 for the issue and #901 for a workaround PR.
