### ISSUE TITLE
Works with global install but not with npm scripts

### ISSUE THREAD

**Issue by the-smaug** [parcel-bundler/parcel#1138]
🐛

I can serve my app with my parcel which is installed globally but not with local ones.

### 🎛 Configuration (.babelrc, package.json, cli command)

scripts of my package.json
```json
 "scripts": {
    "dev": "concurrently \"parcel src/index.html\" \"wait-on http://localhost:1234 && electron .\"",
    "start": "parcel src/index.html --target browser",
    "build": "parcel build src/index.html",
    "test": "jest --watch",
    "testcov": "jest --coverage",
    "lint": "eslint src/",
    "prepack": "yarn build",
    "pack": "electron-builder --dir",
    "dist": "electron-builder"
  },
```

### 🤔 Expected Behavior

Should serve my app

### 😯 Current Behavior

In browser console i can see "Uncaught TypeError: Cannot redefine property: getDataFromTree"

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0
| Node             | 9.10
| npm/Yarn         |  1.5.1
| Operating System | OSX High Sierra

**Comment by DeMoorJasper** [comment]
What's the difference between the local and global one?
Both same version?

**Comment by the-smaug** [comment]
Yes it was the same version, but i upgrade all deps of my project and it works 😄
