### ISSUE TITLE
In a monorepo - magically installed GLSL deps modify source package.json

### ISSUE THREAD

**Issue by danmarshall** [parcel-bundler/parcel#1139]
🐛 bug report

This isn't a big deal, but it might be worth noting that running Parcel caused a side effect in a source file.
Specifically, it added these 2 devDependencies to my package.json:
```
    "glslify-bundle": "^5.0.0",
    "glslify-deps": "^1.3.0"
```
My source tree is a monorepo managed by Lerna. I have provided a minimum viable repro repo here: 
https://github.com/danmarshall/parcel-lerna-gl

This happens because a project is symlinked, and the node_modules points to source instead of a copy.

### 🤔 Expected Behavior

Parcel runs, does not cause changes in my git.

### 😯 Current Behavior

Source tracked package.json is modified, and appears as a change in git.

### 💁 Possible Solution

Seems somewhat harmless for now, but adding more magic installs may cause unwanted devDependencies.

Perhaps package.json can be reverted after the magic install?

**Comment by gnijuohz** [comment]
I know this doesn't directly address your concern, but you could use `--no-autoinstall` to disable "magic installing". 
I wonder whether a `--autoinstall` option for the user to opt in for this behaviour is better than `--no-autoinstall`, which does something great, but somewhat unexpected...

**Comment by devongovett** [comment]
Those glslify dependencies are build dependencies needed by parcel in order to compile the GLSL files in your project. We happen to install them for you, but even if we didn't you'd need to do it manually. Those deps would always need to be in your package.json in order to build it, I don't see the harm in parcel putting them there for you.
