### ISSUE TITLE
blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by fojhun** [parcel-bundler/parcel#1145]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by devongovett** [comment]
Closing. Please fill in the issue template. We cannot properly debug your issue without more info.
