### ISSUE TITLE
attempts to resolve href asset containing template syntax

### ISSUE THREAD

**Issue by rodney757** [parcel-bundler/parcel#1153]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

bug report

### 🤔 Expected Behavior

don't attempt to resolve `href` assets.

### 😯 Current Behavior

the following code in and html file fails the build:

`<a href="{{ $ctrl.bioProjectLink }}" target="_blank">`

error: `Cannot resolve dependency './%7B%7B%20$ctrl.bioProjectLink%20%7D%7D'`

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by devongovett** [comment]
Hmm, why is parcel running over your templates? Shouldn't you run them through a templating engine first?

**Comment by rodney757** [comment]
this is an angularJS app, so the template engine is clientside

**Comment by edmorley** [comment]
I am hitting this too. 

The (valid) AngularJS template syntax is being interpreted as a literal resource here:
https://github.com/mozilla/treeherder/blob/55654a1195335b08b92a84e10f65dcc1ec73d5d3/ui/plugins/pluginpanel.html#L53-L61

...resulting in:
```
×  C:\...\treeherder\ui\plugins\pluginpanel.html: Cannot resolve dependency './{{::job_log_url.url}}' at 'C:\...\treeherder\ui\plugins\{{::job_log_url.url}}'
    at Resolver.resolve (C:\...\treeherder\node_modules\parcel-bundler\src\Resolver.js:70:17)
```

webpack's html-loader uses `loader-utils.isUrlRequest()` to determine whether the contents is resource to follow:
https://github.com/webpack-contrib/html-loader/blob/27026d2f0f5523ddea2a68272c4b58d5b69cffc0/index.js#L55

Perhaps Parcel could borrow the regex from it?
https://github.com/webpack/loader-utils/blob/67499ff3d13c13ef455ec0fede90b714fc16d787/lib/isUrlRequest.js#L4-L10

**Comment by jisuo** [comment]
@rodney757 Workaround (and recommended by angular official docs) is to use `ng-href` and not `href` when  you use `{{}}` for the link

**Comment by raymondborkowski** [comment]
I still have an issue with non angular framework.

**Comment by DeMoorJasper** [comment]
Being more specific or opening up an issue dedicated to your issue would be more helpfull @raymondborkowski
