### ISSUE TITLE
Resolver fails with bootstrap3 sass import

### ISSUE THREAD

**Issue by rodney757** [parcel-bundler/parcel#1154]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
bug report

### 😯 Current Behavior

the resolver fails when building a sass file with the following:

```
// Bootstrap Framework.
// $icon-font-path: "../../node_modules/bootstrap-sass/assets/fonts/bootstrap/";
@import "../../node_modules/bootstrap-sass/assets/stylesheets/bootstrap-sprockets";
@import "../../node_modules/bootstrap-sass/assets/stylesheets/bootstrap";
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0
| Node             | 8.9.4
| npm/Yarn         | 1.5.1
| Operating System | osx 10.13.3

**Comment by devongovett** [comment]
Sounds like a SASS issue. We don't currently override the SASS resolver in any way. Could you provide more info about the error you're seeing?

**Comment by rodney757** [comment]
oops, sorry about that, I thought I included the error. unfortunately, the error output get cut off bit by the `at Resolver.resolve ...` line

```
/Users/rjewing/code/biocode/biscicol-ui/src/style/app.scss: Cannot resolve dependency './node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot%22)' at '/Users/rjewing/code/biocode/biscicol-ui/src/st    at Resolver.resolve (/Users/rjewing/code/biocode/biscicol-ui/node_modules/parcel-bundler/src/Resolver.js:76:17)
    at <anonymous>
```

**Comment by jpstone** [comment]
I'm not sure how this is a SASS issue. I run `node-sass src/styles.scss` and everything "just works". If I import `./styles.scss` into my `index.js` and build with parcel, I start getting these same resolver errors.

**Comment by Dagge1** [comment]
Problem starts when you try to import boostrap.scss file directly from node_modules. It doesn't work, you have to create your own .scss file outside node_modules dir, from where you will call different .scss modules, including yours that override bootstrap defaults.

I wonder why parcel doesn't fix that, bucause it's quite old problem.
