### ISSUE TITLE
Unexpected rendering on Linux

### ISSUE THREAD

**Issue by demsking** [parcel-bundler/parcel#1155]
Just to notice an rendering issue on GNU/Linux, about font in the [Parcel website](https://parceljs.org/getting_started.html)

![image](https://user-images.githubusercontent.com/4570744/38471021-a148cc9a-3b6b-11e8-81f7-88593fe18e85.png)

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | GNU/Linux Ubuntu

**Comment by devongovett** [comment]
Looks like you don't have an emoji font installed on your system.

For future issues with the website, please file on http://github.com/parcel-bundler/website/issues.
