### ISSUE TITLE
Font url import fails to resolve at runtime

### ISSUE THREAD

**Issue by bgourlie** [parcel-bundler/parcel#1156]
**This a 🐛 bug report**

### 🎛 Configuration (.babelrc, package.json, cli command)

**tsconfig.json**

```js
{
  "compilerOptions": {
    "strict": true,
    "target": "es2015",
    "jsx": "react"
  }
}
```

**package.json**

```
{
  "name": "wtfloat",
  "version": "0.1.0",
  "description": "An interactive guide to floating point numbers",
  "scripts": {
    "dev": "parcel ./src/root.html",
    "dev-debug": "node %NODE_DEBUG_OPTION% ./node_modules/parcel-bundler/bin/cli.js ./src/root.html",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "W. Brian Gourlie",
  "license": "MIT",
  "devDependencies": {
    "@types/flux": "^3.1.7",
    "@types/react": "^16.3.5",
    "@types/react-dom": "^16.0.4",
    "@types/react-router": "^4.0.23",
    "@types/react-router-dom": "^4.2.6",
    "@types/shelljs": "^0.7.8",
    "node-sass": "^4.8.3",
    "parcel-bundler": "^1.7.0",
    "parcel-plugin-react-markdown": "0.0.1",
    "shelljs": "^0.8.1",
    "typescript": "^2.8.1"
  },
  "dependencies": {
    "flux": "^3.1.3",
    "immutable": "^3.8.2",
    "react": "^16.3.1",
    "react-dom": "^16.3.1",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2"
  }
}
```

I'm importing a font via a scss file. Specifically:

```
@font-face {
  font-family: "Besley Medium";
  src: url("./static/Besley-Medium.otf") format("opentype");
}

body {
  font-family: "Besley Medium", serif;
}
```

### 🤔 Expected Behavior

I expect that the font will load successfully when bundled.

### 😯 Current Behavior

I'm receiving the following runtime error:  `Error: Cannot find module 'Besley-Medium.cf0cb4dc.otf,11'`

### 🔦 Context

You can clone my repository [here](https://github.com/bgourlie/wtfloat)

`npm install && npm run dev`

Open the development server in the browser and look at the console.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0
| Node             | 8.9.4
| npm/Yarn         | 5.6.0
| Operating System | Windows 10 x64

**Comment by CareyToboo** [comment]
@bgourlie it look like parcel load the font files to base64 string. i have this problem , too.

**Comment by jqroom** [comment]
I also encountered the same problem. Images url import fails to resolve at runtime, And I noticed that the image referenced by css was packaged as js. Hope to solve this bug sooner.

**Comment by dongyuwei** [comment]
Same for me.
```
@font-face {
  font-family: "fontcustom";
  src: url("./fontcustom_bc28fe98a77e4b9b8203c675d79b3286.eot");
  src: url("./fontcustom_bc28fe98a77e4b9b8203c675d79b3286.eot?#iefix") format("embedded-opentype"),
       url("./fontcustom_bc28fe98a77e4b9b8203c675d79b3286.woff2") format("woff2"),
       url("./fontcustom_bc28fe98a77e4b9b8203c675d79b3286.woff") format("woff"),
       url("./fontcustom_bc28fe98a77e4b9b8203c675d79b3286.ttf") format("truetype"),
       url("./fontcustom_bc28fe98a77e4b9b8203c675d79b3286.svg#fontcustom") format("svg");
  font-weight: normal;
  font-style: normal;
}
```
Cannot resolve dependency './fontcustom_bc28fe98a77e4b9b8203c675d79b3286.eot

**Comment by dongyuwei** [comment]
Update: add a `.lessrc`(with content `{ relativeUrls: true }`) resolved my issue. see https://github.com/parcel-bundler/parcel/issues/540.
