### ISSUE TITLE
crash upon build process

### ISSUE THREAD

**Issue by garritfra** [parcel-bundler/parcel#1157]
**Choose one:** 🐛 bug

`parcel build` crashes for no apparent reason inside a react app

### 🎛 Configuration (.babelrc, package.json, cli command)

**Command:** `parcel build public/index.html`

**package.json**
```js
{
  "name": "portfolio",
  "version": "1.0.0",
  "description": "Personal portfolio",
  "main": "index.js",
  "scripts": {
    "start": "parcel ./public/index.html -p 80",
    "test": ""
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/garritfra/Portfolio.git"
  },
  "author": "Garrit Franke",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/garritfra/Portfolio/issues"
  },
  "homepage": "https://github.com/garritfra/Portfolio#readme",
  "devDependencies": {
    "babel-preset-env": "^1.6.1",
    "parcel-bundler": "^1.7.0"
  },
  "dependencies": {
    "node-sass": "^4.8.3",
    "particles.js": "^2.0.0",
    "react": "^16.3.1",
    "react-dom": "^16.3.1",
    "react-particles-js": "^2.1.2"
  }
}```

### 🤔 Expected Behavior

The package should be bundled!

### 😯 Current Behavior


```js
{ Error: ENOENT: no such file or directory, scandir 'build' errno: -2, code: 'ENOENT', syscall: 'scandir', path: 'build' }
/usr/lib/node_modules/parcel-cli/node_modules/parcel-luxe/lib/parser.js:44
    files.forEach(function (file) {
          ^

TypeError: Cannot read property 'forEach' of undefined
    at /usr/lib/node_modules/parcel-cli/node_modules/parcel-luxe/lib/parser.js:44:11
    at /usr/lib/node_modules/parcel-cli/node_modules/parcel-luxe/lib/reader.js:9:14
    at FSReqWrap.oncomplete (fs.js:153:20)
```

### 💁 Possible Solution

The problem only occured on my v-server, so maybe it has something to do with the configuration of it. I could try docker..?🤔

### 💻 Code Sample

https://github.com/garritfra/Portfolio

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.7.0
| Node             |6.12.3
| npm/Yarn         |5.6.0
| Operating System |debian 8

**Comment by DeMoorJasper** [comment]
Reading the error it’s highly likely a parcel-luxe related error not parcel

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Julian-Makholy** [comment]
bro I have the same problem, and this is the only thread i can find on this issue, did you manage to find a solution for parcel-luxe?

**Comment by garritfra** [comment]
> bro I have the same problem, and this is the only thread i can find on this issue, did you manage to find a solution for parcel-luxe?

@Julian-Makholy This was 4 years ago, I have no clue if and how I managed to fix this.😅 I think in the end I containerized the application and it worked. Are your dependencies up to date?
