### ISSUE TITLE
Automatically install Typescript types

### ISSUE THREAD

**Issue by zzarcon** [parcel-bundler/parcel#1161]
🙋 feature request

Not sure which level of Typescript support we want to have on Parcel, but since we have the TypeScriptAsset I thought it will be cool to automatically add external types. 

This is something that the end user will have to do by hand otherwise and its how the Typescript ecosystem works.

### 🎛 Configuration (.babelrc, package.json, cli command)

No custom configuration needed

### 🤔 Expected Behavior

When requiring external modules from **.ts** and **.tsx** files, I'd expect Parcel to try to install the appropriate typing from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)

### 😯 Current Behavior

No typing are installed and Typescript can't find types for external dependency

### 💻 Code Sample

Having the following app

```javascript
import * as React from 'react';
import * as ReactDOM from 'react-dom';
```

I'd expect the following types to be installed:

* `@types/react`
* `@types/react-dom`

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  ^1.7.0
| Node             |  8.4.0
| npm/Yarn         |  1.3.2
| Operating System |  Mac

**Comment by marvinhagemeister** [comment]
FYI: Some editors like vscode already fetch [typings automatically](https://code.visualstudio.com/docs/languages/javascript#_automatic-type-acquisition). No need to duplicate that functionality in parcel.
