### ISSUE TITLE
The parser throws errors.

### ISSUE THREAD

**Issue by nathfreder** [parcel-bundler/parcel#1162]
**Choose one:** 🐛 bug report

The parser throws error on build with using Parcel.
### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["es2017", "react", "minify"]
}
```

### 🤔 Expected Behavior

The build should complete.

### 😯 Current Behavior

The parser throws a error.

```js
🚨  /app/src/Auth/Auth.js:6:8: Unexpected token (6:8)
11:20 AM
  4 | 
11:20 AM
  5 | export default class Auth {
11:20 AM
> 6 |   auth0 = new auth0.WebAuth({
11:20 AM
    |         ^
11:20 AM
  7 |     domain: AUTH_CONFIG.domain,
11:20 AM
  8 |     clientID: AUTH_CONFIG.clientId,
11:20 AM
  9 |     redirectUri: AUTH_CONFIG.callbackUrl,
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0
| Node             | 8.10.0
| npm/Yarn         | 5.4.0
| Operating System | Linux Ubuntu Docker

**The code works on create-react-app but not parcel?**

**Comment by DeMoorJasper** [comment]
Minify shouldn't be in your babel config as uglify runs anyways in a production build, this has nothing to do with your issue though. Just a tip for faster build times.

Could we get more context on the code that it throws on?

**Comment by nathfreder** [comment]
1. The _minfiy_ thing is good to know.
2. This is the code that I am currently using, https://glitch.com/edit/#!/remix/parcel-error-1162, if you need anything else just mention me.

**Comment by nathfreder** [comment]
Closing due to _Resolved_.

**Comment by DoubleCouponDay** [comment]
@ghost how was it resolved??
