### ISSUE TITLE
Can't parse  React link parameters with points

### ISSUE THREAD

**Issue by proto1994** [parcel-bundler/parcel#1164]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
// .babelrc
{
    "presets": [
      "react-app", "env", "stage-2"
    ],
    "plugins": ["transform-class-properties", "transform-decorators-legacy"] 
}
// package.json
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "parcel index.html",
    "build": "parcel build index.html"
  }
```

### 😯 Current Behavior

Hello, very good tool.
Here are the problems I encountered. **When I visit localhost:1234?a=., the page does not open. But parameter a can open normally if it is not dotted.**
### 🔦 Context

I searched on google for a long time and did not find a solution, so I’m looking for help here

### 💻 Code Sample

My code is very simple
```javascript
// index.html
<html>
<title>传播图</title>
<meta charset="UTF-8">
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport">
<script src="https://d3js.org/d3.v4.min.js"></script>
<body>
    <div id="root">
           
    </div>
    <script src="./index.js"></script>
</body>
</html>

// index.js
import React from 'react';
import ReactDOM from 'react-dom';
import App from './src/app';
import './index.less';

ReactDOM.render(<App />, document.getElementById('root'));


if (module.hot) {
    module.hot.accept();
}

// app.js
import React from 'react';
import Layout from './components/Layout';
import Spread from './views/spread';
class App extends React.Component {

    render() {
        return (
            <div>test</div>
        )
    }
}

export default App;

```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7
| Node             | 9.2
| npm/Yarn         | 5.5
| Operating System | mac 10.12

**Comment by DeMoorJasper** [comment]
This is probably an issue with the server, which removes the extensions, and probably sees the `.` as an extension therefore using that instead of the real extension

**Comment by devongovett** [comment]
I actually also had this problem recently. #1169 should fix it. Let me know!

**Comment by proto1994** [comment]
Good job!!!  When will a new version be released?

**Comment by devongovett** [comment]
I'll try to do a patch release later today.
