### ISSUE TITLE
process.env transformation is breaking leaving only ".NODE_ENV"

### ISSUE THREAD

**Issue by joenoon** [parcel-bundler/parcel#117]
I think I found a bug where `(process.env.NODE_ENV)` in the source file was transformed to `(.NODE_ENV)` in my bundle.  Parcel doesn't complain, but when loading the page the js error is thrown.

I traced where this is happening to around:
https://github.com/parcel-bundler/parcel/blob/3e97493690eb4b9a87b899b30bc0e1b19f0f84f1/src/visitors/globals.js#L21

If I insert an early return in that function, then it builds and works.

You can repro the bug here:
https://github.com/joenoon/example-react-transition-group-stack-navigator

Then temporarily change node_modules/parcel-bundler/src/visitors/globals.js inserting the early return, yarn start, and the page will load correctly.

**Comment by johanbaath** [comment]
@joenoon I'm using the Babel plugin "transform-inline-environment-variables" for this and it works well, did you try that? 😃

**Comment by joenoon** [comment]
@johanbaath that sounds like a smart workaround.  For some reason that plugin is not transforming anything for me, so now I'll debug that and try to see why.  I wonder if both problems are due to one of the other plugins I'm using.  But if I can get that babel plugin to work, it would avoid the parcel code finding any process.env's and should work in theory!

**Comment by joenoon** [comment]
@johanbaath So actually transform-inline-environment-variables is working, but only in my app code - not node_modules/* code.  I think thats the normal behavior and makes sense.  I didn't have any process.env's in my own code, so I had to add one to verify the babel transform does indeed transform it.

So for my problem, the workaround won't help, because parcel will try to process all of the other process.env's in node_modules anyway.  I guess that raises another question about whether or not it should be doing that, and what else it does to node_modules?  The site briefly mentions node_modules but doesn't get into detail.

**Comment by johanbaath** [comment]
@joenoon OK I see! I have not had that exact requirement, so I'm unsure. Let us know if you find any solution.

**Comment by thejameskyle** [comment]
Relevant code is here: https://github.com/parcel-bundler/parcel/blob/3e97493690eb4b9a87b899b30bc0e1b19f0f84f1/src/visitors/globals.js#L22-L30

**Comment by thejameskyle** [comment]
Here's some resources to help out if you're new to compilers/ASTs:

- https://github.com/thejameskyle/the-super-tiny-compiler
- https://github.com/thejameskyle/babel-handbook (See "plugin handbook" in your language)

**Comment by joenoon** [comment]
A user on slack (Shawn) had me try commenting out the `delete node.object` line.  The result is:

- in the **edited** bundle, many process.env's are transformed, but 3 process.env's remain un-transformed.  this doesn't cause any runtime issues in this case and the bundle runs correctly.
- in the **unedited** bundle, its missing the process shim module completely.  it looks like parcel is the one adding it to begin with, but then it gets stripped back out, and the delete line has something to do with it.
 
So removing that line might be the fix, or it might have just fixed my specific case.  I'm not sure yet, but commenting out that delete line does seem to produce a more correct bundle.

**Comment by thejameskyle** [comment]
That doesn't sound right, you should have to remove the entire node

**Comment by Raathigesh** [comment]
It seems to fail for the following piece of code
```
var isDev = function (x) {
    return x === 'development' || !x;
  }(process.env.NODE_ENV);
```

And it's being translated into
```
var isDev = function (x) {
    return x === 'development' || !x;
  }(.NODE_ENV);
```

**Comment by joenoon** [comment]
I tried both https://github.com/parcel-bundler/parcel/pull/153 and https://github.com/parcel-bundler/parcel/pull/166 on my example project in the first post.  Both work, awesome fixes!

I've compared the final bundle output from both and it looks like they produced the same result (except parts moving around in the file, numbers used in the bundling process, etc, which are all expected).

https://github.com/parcel-bundler/parcel/pull/153 is a really light change so that would be my vote, but I leave it to someone who knows the ins and outs of this stuff.

**Comment by maciej-ka** [comment]
@joenoon I added another solution that morphs a child Node and doesn't need to know anything about parent Node. You may find it interesting. It results in the shortest code and remains generic (not written for one type of parent node).

To sum up solution directions, we have:
- adding a clause to replace function when a parent is a CallExpression type: #153
- changing replace to make generic, deep walk inside parent Node: #166 
- morphing Node that needs to be changed without looking at the parent #193
