### ISSUE TITLE
HMR works only on a chosen few.

### ISSUE THREAD

**Issue by Ranjeet-Naidu** [parcel-bundler/parcel#1170]
Hi guys HMR works only for a chosen few. At first I thought it was the nested components but thats not the case, its random files consistently. I does build the app every time changes are made but not reflected in the browser.

Code can be found [here](https://github.com/Ranjeet-Naidu/Spike-VueJS).
Thanks.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0
| Node             | 8.0.0 
| npm/Yarn         | 5.0.0
| Operating System | OSX

**Comment by DeMoorJasper** [comment]
Please use/fill in the issue template. (provide more info)

On first sight this seems like a filewatching problem? Maybe safe-write?
