### ISSUE TITLE
Code duplicated when using Dynamic Imports

### ISSUE THREAD

**Issue by nick-woodward** [parcel-bundler/parcel#1172]
This a 🐛 bug report.

Based on [How it Works](https://parceljs.org/how_it_works.html#2.-constructing-the-bundle-tree) and issue #37 it seems as though this is a bug.

When splitting your code, if a common module is included in both the parent and child it is duplicated rather then shared.

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

### 🤔 Expected Behavior

Common code is shared.

### 😯 Current Behavior

Common code is duplicated.

### 🔦 Context

Increases the size of the bundle, could potentially cause problems in cases where something can't be defined multiple times. (i.e. web components)

### 💻 Code Sample

Just open up the console when you look at the demo. 
You'll see that `common.js` is logged multiple times.

https://parcel-bundler-dynamic-dedupe.glitch.me _**[Edit](https://glitch.com/edit/#!/parcel-bundler-dynamic-dedupe?path=common.js:1:0)**_

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0
| Node             | v9.11.1
| Yarn         | 1.5.1
| Operating System | MacOS High Sierra 10.13.3

**Comment by PatrickSachs** [comment]
Are there any updates/fixes for this? 

I just switched over to Parcel from Webpack only to discover that all my Vendor code is also included in all bundles.

**Comment by devongovett** [comment]
Currently common code is hoisted to the parent bundle, but that will change in Parcel 2. We will be creating a separate bundle that loads in parallel with the shared code. See #885.
