### ISSUE TITLE
RiotJS and imports within a tag files do not work 

### ISSUE THREAD

**Issue by dharmax** [parcel-bundler/parcel#1174]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
bug/feature request

i have import statements withing a riot .tag files that aren't recognized by Parcel, although they are handled perfectly in Webpack.

### 🎛 Configuration (.babelrc, package.json, cli command)
**package.json**
```
  "dependencies": {
    "@types/bcryptjs": "^2.4.1",
    "bcryptjs": "^2.4.3",
    "faye": "^1.2.4",
    "parcel-bundler": "^1.7.0",
    "qr-encode": "^0.3.0",
    "riot": "^3.9.1"
  },
  "devDependencies": {
    "@types/webpack": "^4.1.3",
    "less": "^2.7.3",
    "node-sass": "^4.7.2",
    "riot-hot-reload": "^1.0.0",
    "riot-tag-loader": "^2.0.2",
    "ts-loader": "^4.2.0",
    "typescript": "^2.8.1",
  }
```

### 🤔 Expected Behavior

the imported artifacts should be initialized properly

### 😯 Current Behavior

The imported artifacts are undefined.

There is no build time error, but there are runtime errors (undefined variable)

### 🔦 Context

i wanted to import service objects/functions into the tag

### 💻 Code Sample
```
<my-tag>
 .....
  <script>
            import {changeState} from '../app-states'
            import {hash} from 'bcryptjs'
....
   ```     

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0
| Node             | 9.8.0
| npm/Yarn         | 5.7.1
| Operating System | PopOS (ubuntu)

**Comment by DeMoorJasper** [comment]
RiotJS is not natively supported in parcel

**Comment by dharmax** [comment]
i would have loved it if it would. Parcel is wonderful and Riot, to my experience, is better than Angular, React and even Vue.

**Comment by DeMoorJasper** [comment]
@dharmax Feel free to write a plugin for it, shouldn't be that hard (if their compiler has a nice api)

**Comment by bminer** [comment]
@DeMoorJasper - I found a riot parcel plugin [here](https://github.com/andruschka/parcel-plugin-riot/), but I'm confused on a few issues.  When using Riot.js, you write ".tag" files, which are then compiled into JS; however, Riot supports multiple pre-processors (i.e. Pug --> HTML, Stylus --> CSS).

My question is this: how do you take a *.tag file like this:

```
my-tag
  h1 Testing 1, 2, 3
```

and slam it through [`riot.compile(...)`](https://riot.js.org/api/compiler/#on-server) such that Riot knows it's a Pug formatted file, not a HTML formatted file?

**Comment by bminer** [comment]
FYI - as mentioned [here](https://riot.js.org/guide/compiler/) in Riot's compiler documentation, you can also specify an ES6 Config file.  Perhaps this is the "idoimatic" parcel way to pass these options to the riot-parcel-plugin compiler?
