### ISSUE TITLE
Can't resolve dependency of image in CSS of Vue component

### ISSUE THREAD

**Issue by PierBover** [parcel-bundler/parcel#1175]
This is a 🐛 bug report.

Basically when using relative URLs to images in CSS such as
`background-image: url('../assets/test.jpg');`
I get the `Cannot resolve dependency` error.

### 🎛 Configuration (.babelrc, package.json, cli command)

My configuration is really barebones. I only have a `.babelrc` file with this:

```
{
    "presets": ["env"]
}
```

Otherwise I only did `npm i parcel-bunler` and then `parcel index.html`.

### 💻 Code Sample

My dependencies:
```
  "dependencies": {
    "vue": "^2.5.16",
    "vue-hot-reload-api": "^2.3.0"
  },
  "devDependencies": {
    "@vue/component-compiler-utils": "^1.0.0",
    "node-sass": "^4.8.3",
    "parcel-bundler": "^1.7.0",
    "vue-template-compiler": "^2.5.16"
  }
```

App.vue:
```
<template>
	<div id="App">
		<div>{{message}}</div>
	</div>
</template>

<script>
export default {
	data () {
		return {
			message: 'Hello World'
		};
	}
};
</script>

<style lang="scss">
#App {
	background-image: url('../assets/test.jpg');
}
</style>

```

The whole error:

> /project-folder/src/components/App.vue:3:3: Cannot resolve dependency './a00947c8cbd519a00a96b80e009550b9.jpg' at '/project-folder/src/components/a00947c8cbd519a00a96b80e009550b9.jpg'
    at Resolver.resolve (/project-folder/node_modules/parcel-bundler/src/Resolver.js:76:17)
    at <anonymous>

The path to the file is correct and if I do `<img src="../assets/test.jpg">` in the template it resolves fine and the file appears in the `dist` folder.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0 |
| Node             | 8.9.4 |
| npm/Yarn         | 5.7.1 |
| Operating System | macOS 10.13.4 |

**Comment by PeachScript** [comment]
Hello @PierBover , it looks like duplicate with #1147 , and I also have the same problem.

**Comment by DeMoorJasper** [comment]
Seems to be a duplicate indeed, although sass dependencies are pretty different than any other framework we support if it works in regular sass files it should be the same issue.

**Comment by PierBover** [comment]
Yeah it looks pretty similar. I'll close this issue and keep communication there.
