### ISSUE TITLE
🐛parcel use parent's .babelrc in nested project which is not use babel.

### ISSUE THREAD

**Issue by zeakd** [parcel-bundler/parcel#1176]
Hi. I made examples project without babel in my library
```
MyLibrary
├── examples
│   ├── index.html
│   ├── index.js
│   ├── node_modules/
│   │   ├── ...
│   │   └── parcel-bundler/
│   └── package.json
...
├── node_modules/
├── .babelrc
└── package.json

```

I tried to make examples website using parcel without babel (because I use babel 7 which is not supported yet in parcel and I don't want to mix babel 6 and 7 config in my project), make package.json and install parcel-bundler inside examples folder. But after running parcel inside example folder, it use .babelrc of parent and give me error (babel 7 beta error)

### 🎛 Configuration (.babelrc, package.json, cli command)

MyLibrary/.babelrc
``` json
{
  "presets": [
    ["@babel/env", {
      "modules": false
    }]
  ]
}
```

MyLibrary/examples/package.json
``` json
{
  "name": "examples",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "start": "parcel index.html"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel-bundler": "^1.7.0"
  }
}
```

### 🤔 Expected Behavior

``` bash
cd examples
npm run start
```

works well.

### 😯 Current Behavior

``` bash
... Couldn't find preset "@babel/env" relative to di... 
```

parcel use .babelrc of parent

### 💁 Possible Solution

When i make empty .babelrc inside examples folder, it works. 

MyLibrary/examples/.babelrc
``` json
{}
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v1.7.0
| Node             | v9.11.1
| npm/Yarn         | v5.6.0
| Operating System | macOS hish sierra

**Comment by damassi** [comment]
Just ran into this as well, but the empty `.babelrc` in the target folder fixed it.
