### ISSUE TITLE
Parcel sometimes doesn't use the browser version of libraries

### ISSUE THREAD

**Issue by download13** [parcel-bundler/parcel#1181]
🐛 bug report

Very simple to reproduce.

Put `import 'readable-stream';` into a js file.

Run `parcel build -d outdir file.js --no-minify`. The no-minify flag isn't required, just makes it easier to find out what's going on.

Use a script tag to load the built file in a browser.

### 🤔 Expected Behavior

Nothing is shown in the console, since basically nothing happened.

### 😯 Current Behavior

```
Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at Function.create (<anonymous>)
    at Object.function.Object.create.module.exports [as inherits] (player.js:12)
    at Object.parcelRequire.50.process-nextick-args (player.js:43)
    at u (player.js:1)
    at a (player.js:1)
    at Object.parcelRequire.45../lib/_stream_writable.js (player.js:61)
    at u (player.js:1)
    at a (player.js:1)
    at Object.parcelRequire.42.events (player.js:69)
    at u (player.js:1)
```

I tracked it back to [a line](https://github.com/nodejs/readable-stream/blob/master/lib/_stream_writable.js#L96) that runs `util.inherits(Writable, Stream);`

The error is being thrown when `util.inherits` tries to create an object using the ancestor's prototype. In this case, Stream.prototype turns out to be `undefined`. The reason for this seems to be that parcel is importing the node version of the module instead of the browser version.

Stream is imported by [the line](https://github.com/nodejs/readable-stream/blob/master/lib/_stream_writable.js#L78) `var Stream = require('./internal/streams/stream');` which, according to the [package.json file](https://github.com/nodejs/readable-stream/blob/master/package.json#L44) should redirect to `./lib/internal/streams/stream-browser.js` when compiling for the browser.

It doesn't seem to be getting redirected though. If I hunt through the bundle for the module addressed as `./internal/streams/stream`, I find this:

```
[function(require,module,exports) {
module.exports = require('stream');

},{"stream":20}]
```

That is the contents of [stream.js](https://github.com/nodejs/readable-stream/blob/master/lib/internal/streams/stream.js), not [stream-browser.js](https://github.com/nodejs/readable-stream/blob/master/lib/internal/streams/stream-browser.js) as it should be.

I also had this happen with another library (webtorrent) briefly pulling in the `net` node module and crashing because of it. That problem went away without explanation though, while this one seems to be easily reproducible.

**Comment by alidcastano** [comment]
Not sure if it's related but I'm getting an `Object prototype may only be an Object or null: undefined` error as well and I'm building both browser and node versions of my bundle

With the same code, sometimes the error shows up, sometimes it doesn't. I have to delete build file and restart app to get it to work. Having to do this multiple times makes Parcel slower than Webpack haha

**Comment by devongovett** [comment]
Is anyone still having this issue?

**Comment by emily-curry** [comment]
@devongovett I'm running into this on v1.11.0, using the `simple-peer` module. Exact same issue as above (`stream` is being required instead of `readable-stream`).

**Comment by gfsd3v** [comment]
@devongovett I think that my problem may be related to this, here are some screenshots:

![image](https://user-images.githubusercontent.com/36668882/97067199-727a7000-1591-11eb-93f8-0f64ec7ddaef.png)

# Line of the error
`  module.exports = function inherits(ctor, superCtor) {
    ctor.super_ = superCtor
    ctor.prototype = Object.create(superCtor.prototype, {
      constructor: {
        value: ctor,
        enumerable: false,
        writable: true,
        configurable: true
      }
    });
  };`

# Relevant stack trace (I think)
`/**
 *
 * @constructor
 */
function ReadStream(path, options) {
	options = options || {};

	// here we make believe that we have an already opened file
	// by setting `options.fd` to a number (-1).
	// This ensure the file won't be created now.
	if ('number' != typeof options.fd) {
		options.fd = -1;
	}

	FileReadStream.call(this, path, options);
}

util.inherits(ReadStream, FileReadStream);`

I did some research and I think it may be related with this issue as well:

https://github.com/nodejs/readable-stream/issues/237

Do u have any idea on how to solve this ? Unfortunately I cant share a reproducible repo sense I stumb on to this working on a ejected CRA of a client.
