### ISSUE TITLE
Parcel dev server does not serve pages with a dot (.) in the URL

### ISSUE THREAD

**Issue by goyney** [parcel-bundler/parcel#1189]
**Choose one:** is this a 🐛 bug report or 🙋 feature request? Bug Report

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    "react",
    "env",
    "stage-3"
  ],
  "plugins": [
    [
      "module-resolver",
      {
        "root": [
          "./",
          "./components",
          "../modules",
          "../node_modules"
        ],
        "alias": {
          "assets": "./assets",
          "style": "./style"
        }
      }
    ],
    "transform-class-properties",
    "rewire"
  ]
}
```

### 🤔 Expected Behavior

When serving a URL that contains a dot/period (.) in the URL, the path is served correctly.

### 😯 Current Behavior

The page immediately fails to load with a 404. Removing the period in some fashion allows the page to load.

### 💁 Possible Solution

Make periods work. :P

### 🔦 Context

We're trying to implement a page with a JWT as a query string parameter. JWT's incorporate periods in them, which causes the 404. If we string replace the periods with something else, the error no longer appears. This is less than ideal. Periods are valid characters in a URL and should just work.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.70
| Node             | 8.11.1
| npm/Yarn         | yarn 1.5.1
| Operating System | Mac

**Comment by goyney** [comment]
Related: webpack had the same issue and it had to do with the history API dot rule.
https://github.com/webpack/webpack-dev-server/issues/332

**Comment by goyney** [comment]
Looks like the source of the problem comes from the Server.js file, line 50.

`path.extname(req.url) === ''`

Splits it at the period.

**Comment by goyney** [comment]
Looks like this was actually already fixed in https://github.com/parcel-bundler/parcel/pull/1169. Closing this.

Please push those changes out soon!

**Comment by vivainio** [comment]
Still crashing on parcel 1.7.0
