### ISSUE TITLE
🐛 Hello World don't work

### ISSUE THREAD

**Issue by nicoandresr** [parcel-bundler/parcel#1191]
**🐛 Bug report**

### 🎛 Configuration (.babelrc, package.json, cli command)

my package.json:
```js
{
  "name": "parcel-bundler",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "parcel-bundler": "^1.7.0"
  }
}
```

### 🤔 Expected Behavior

I'm running the hello world example provided from the parcel.org, the expected behavior is that:
```js
console.log(classes.main);
```
prints the style object. 

### 😯 Current Behavior

The current behavior is that I got an undefined.
<img width="654" alt="captura de pantalla 2018-04-14 a la s 6 57 47 p m" src="https://user-images.githubusercontent.com/6032385/38773583-c396ccda-4015-11e8-98da-4925d4efa4a0.png">
😿 

### 💁 Possible Solution

Maybe I should install parcel globally?, I'm using locally:
```js
npx parcel index.html
```
But I don't think so 🤔 

### 🔦 Context

I'm running the hello world example!! 😾 

### 💻 Code Sample

<img width="1010" alt="captura de pantalla 2018-04-14 a la s 6 47 49 p m" src="https://user-images.githubusercontent.com/6032385/38773621-b7002eca-4016-11e8-98cc-6a5c27dd7dda.png">

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0
| Node             | 9.0
| npm/Yarn         | 5.6.0/1.3.2
| Operating System | MacBook Pro 2017

**Comment by DeMoorJasper** [comment]
There must have been a breaking change somewhere, as this is indeed a bug I can easily reproduce

**Comment by ronami** [comment]
Hey @nicoandresr , CSS modules are not enabled by default. To use them, you should create a `.postcssrc` file with the following content:

```json
{
  "modules": true
}
```

Make sure to delete the `.cache` folder in your project if it doesn't work. Here is the link to the docs on this: https://parceljs.org/transforms.html#postcss.

**Comment by nicoandresr** [comment]
Hello @ronami thank u for your help, but with the .postcssrc does not work either 😿

**Comment by nicoandresr** [comment]
Hi @DeMoorJasper but I can't do that it works 😿, I need install postcss globally?, I removed the project and start again but don't work, please check my [project](https://github.com/nicoandresr/parcel-hello-world).

**Comment by nicoandresr** [comment]
Works, ok thank you very much, sorry for my mistake! 😅
