### ISSUE TITLE
Using typescript with moment.js failing - moment is not a function

### ISSUE THREAD

**Issue by flowt-au** [parcel-bundler/parcel#1194]
🐛 bug report, or clarification, at least. Loving Parcel, except this issue:

Typescript v 2.8.1
Moment.js v 2.22.1
Parcel v 1.7.1

tsconfig.json:

    {
        "compilerOptions": {
            "module": "commonjs",
            "target": "es5",
            "noImplicitAny": true,
            "outDir": "./dist",
            "sourceMap": true,
            "listEmittedFiles": true,
            "allowSyntheticDefaultImports": true
        },
        "esModuleInterop": true,
        "include": [
            "src/**/*"
        ]
    }

index.ts:

    import * as moment from 'moment';
    console.log('Moment=' + moment().format('LLLL'));

Source view in Chrome:
![screen shot 2018-04-16 at 12 17 32 pm](https://user-images.githubusercontent.com/37637590/38787260-4aeefea4-4170-11e8-807c-6d4b9a6efcdb.png)

but VSCode Terminal when I run this says: "Moment=Monday, April 16, 2018 12:16 PM"

ie TS is happy, but Parcel is not. :-(

What else do I need to do, please?

Thanks,
Murray

**Comment by fathyb** [comment]
Use `import moment from 'moment'`, and `esModuleInterop` should be inside `compilerOptions`.

**Comment by flowt-au** [comment]
Thank you!

Yes, that works as far as Parcel goes. Cool.

However, while TS does console.log the moment date as expected, and it doesn't throw any transpiler errors when building, it _does_ display the following "warning", which I can live with. ;-)
![greenshot 2018-04-16 18 26 44](https://user-images.githubusercontent.com/37637590/38798247-66373134-41a4-11e8-85ea-4f288a44c8a5.png)

Thanks again!

**Comment by fathyb** [comment]
Hmm, it's probably VSCode not picking your `tsconfig.json`, could you try to restart it? If it doesn't fix it you may need to manually specify your `tsconfig.json` path in `.vscode/settings.json`.

**Comment by flowt-au** [comment]
Fantastic! I just needed to restart VSCode.

Thank you so much!
👍

**Comment by rzkhosroshahi** [comment]
I have the same issue after changed tsconfig file also I still got the error.

**Comment by thiagodp** [comment]
@rzkhosroshahi See a workaround at https://github.com/palantir/blueprint/issues/959#issuecomment-335965129

**Comment by GeorgeWL** [comment]
This isn't resolved though really, as parcels should be agnostic and not force you to have to change how you import into modules for them to work.

Can we re-open this please?

**Comment by phishy** [comment]
I'm trying to include 3rd party libraries, such as AWS Amplify Datastore, which uses the line 
`import * as PushStream from 'zen-push';` 
and I am unable to get it to work with Parcel using tsconfig.json.

https://codesandbox.io/s/determined-star-2fb1g?fontsize=14&hidenavigation=1&theme=dark
