### ISSUE TITLE
Parcel attempts to rewrite remote URIs

### ISSUE THREAD

**Issue by adamhutch** [parcel-bundler/parcel#12]
Thanks for this project man, super excited to try it all out!

Ran into an issue with trying to use an external stylesheet. Not sure if there's a way to override this behaviour somehow.

In my `index.html` file, I have remote references to some CDN fonts, one example would be:
- `https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css`

When running my dev server, it attempts to rewrite this URL and appends the dev server URL to it:
- http://localhost:1234/dist/https:/maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css

Would be great if the loader would ignore remote URLs.

**Comment by devongovett** [comment]
it should ignore them. looks like maybe your url is missing a slash after https:/?

**Comment by adamhutch** [comment]
Woops, that's just how it outputs. I copied it twice.

![image](https://user-images.githubusercontent.com/910712/33628545-0e835da6-d9cf-11e7-95b3-8f5f54b8f948.png)

Converts to this:

![image](https://user-images.githubusercontent.com/910712/33628554-161388c0-d9cf-11e7-92ff-bd792c24671f.png)

**Comment by mikeabraham** [comment]
Agreed. Awesome project. Very excited about it. 

I have the same issue. 

**Source**
`<script src="https://unpkg.com/vue"></script>` 

**Output**
`<script src="/dist/https:/unpkg.com/vue"></script>`

**Comment by devongovett** [comment]
Should be fixed by #22.

**Comment by devongovett** [comment]
Released in v1.0.2.

**Comment by adamhutch** [comment]
Thanks so much @devongovett, confirmed fixed. Really appreciate the fast fix 👍
