### ISSUE TITLE
 🐛Assets in HTML template in script with type "x-template" won't get bundled

### ISSUE THREAD

**Issue by hzy** [parcel-bundler/parcel#1200]
### 🎛 Configuration (.babelrc, package.json, cli command)

No configuration, I just `parcel index.html`

### 🤔 Expected Behavior
I think assets in "x-template" script tag should also be bundled. 
Code:
```html
  <script type="text/x-template" id="template">
<div>
  <img src="./static/img.png" />
</div>
</script>
```
### 😯 Current Behavior

`img.png` won't get bundled. 

### 💁 Possible Solution

Don't konw

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  v1.7.1
| Node             | v9.7.1
| npm/Yarn         | yarn
| Operating System | macOS High Sierra 10.13.3

**Comment by lanesawyer** [comment]
Been digging for "Good First Issues" to work on, and I noticed this one had a PR that was ultimately closed.

Based on the discussion on #2059, I think this issue can be closed as a "won't fix".
