### ISSUE TITLE
Vue.js SASS Template Style Tag (`<style lang="sass">`) Incorrectly Parsed As SCSS

### ISSUE THREAD

**Issue by enom-infini** [parcel-bundler/parcel#1211]
### 🐛 bug report

Some tickets reported similar issues but I have isolated the cause and effect which you can see in my repo https://gitlab.com/enom/parcel-vue-sass

### 🎛 Configuration (.babelrc, package.json, cli command)

Run the following:

```bash
git clone git@gitlab.com:enom/parcel-vue-sass.git
cd parcel-vue-sass
yarn && yarn dev
```

The `<style lang="sass">` is being parsed as SCSS instead of SASS. This is seems like a Webpack configuration where it's not using the right loader rule.

I unfortunately don't have time to correct this myself.

### 🤔 Expected Behavior

Parcel should parse Vue.js template `<style lang="sass">` as SASS

### 😯 Current Behavior

The following error is displayed in console:

```
🚨  /var/www/parcel-vue-sass/src/App.vue: Invalid CSS after "#": expected 1 selector or at-rule, was "#app"
    at options.error (/var/www/parcel-vue-sass/node_modules/node-sass/lib/index.js:291:26)
```

### 💁 Possible Solution

Seems like a missing or misconfigured Webpack loader / rule.

### 🔦 Context

App development using Parcel, Vue.js, and SASS

### 💻 Code Sample

See https://gitlab.com/enom/parcel-vue-sass

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.1
| Node             | 9.7.1
| npm/Yarn         | 1.5.1 (Yarn)
| Operating System | Linux (below)

```
$ uname -a
Linux vm 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
```

**Comment by mubaidr** [comment]
I am having the same issue. Is there any way to pass parameter to node-sass while using parcel?

**Comment by DeMoorJasper** [comment]
SCSS and SASS are both being run through node-sass.
If anyone with node-sass or sass experience could look into this would be nice

**Comment by tremendus** [comment]
Interestingly enough, if you extract your sass into a separate sass file, and `@include` it, it works fine

```
<style lang="sass">
@import 'src/assets/styles/main.sass'
</style>
```

It just doesn't parse correctly when sass is inline.

**Comment by mubaidr** [comment]
It works fine because now the loader knows the file extension (sass) and correctly parse it as indented syntax (as individual sass files works too), so I believe this is Vue loader/Compiler issue.

**Comment by enom-infini** [comment]
How would I go isolating this issue further? I have time to dive deeper into this now so I'd like to get this working

**Comment by MattAndDev** [comment]
Hi all, first of all, amazing work!!! 
I stumbled upon this issue and while quickly debugging the source I found a workaround that works for me:
https://github.com/parcel-bundler/parcel/blob/master/src/assets/SASSAsset.js#L32
I adapted this:
```
    opts.indentedSyntax =
      typeof opts.indentedSyntax === 'boolean'
        ? opts.indentedSyntax
        : path.extname(this.name).toLowerCase() === '.sass';
```
to this:
```
    opts.indentedSyntax = true
      typeof opts.indentedSyntax === 'boolean' || (this.options.rendition === 'sass' && typeof opts.indentedSyntax === 'undefined')
        ? opts.indentedSyntax
        : path.extname(this.name).toLowerCase() === '.sass';
```
Frankly I don't really know the source code, but I saw rendition is exposing the correct syntax even when used in Vue single file components and used it to override opts.indentedSyntax.
I hope this helps 👍

**Comment by MattAndDev** [comment]
Hi all, first of all, amazing work!!!
I stumbled upon this issue and while quickly debugging the source I found a workaround that works for me:
https://github.com/parcel-bundler/parcel/blob/master/src/assets/SASSAsset.js#L32
I adapted this:

    opts.indentedSyntax =
      typeof opts.indentedSyntax === 'boolean'
        ? opts.indentedSyntax
        : path.extname(this.name).toLowerCase() === '.sass';
to this:

    opts.indentedSyntax =
      typeof opts.indentedSyntax === 'boolean' || (this.options.rendition === 'sass' && typeof opts.indentedSyntax === 'undefined')
        ? opts.indentedSyntax
        : path.extname(this.name).toLowerCase() === '.sass';
Frankly I don't really know the source code, but I saw `this.options.rendition` is exposing the correct syntax type even when used in Vue single file components and used it to override opts.indentedSyntax.
I *hope* this helps and please let me know if I can help further anyhow.

**Comment by DeMoorJasper** [comment]
Finding a way to redirect the file extension to the sass parser should fix this @enom-infini 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MattAndDev** [comment]
Hi all, **amazing** project!!!!
I think I found a workaround for this, but I'm not so sure it's the correct place where to fix the issue.
Please see:
https://github.com/parcel-bundler/parcel/blob/master/src/assets/SASSAsset.js#L31
At this line `opts.indentedSyntax ` is undefined and evaluates to false, as the file is `.vue` and not `.sass` so `path.extname(this.name).toLowerCase() === '.sass'` is not achieving the wanted result.
The workaround is to add the following if clause right after assigning `opts.indentedSyntax` (which evaluates always to false in single file vue components.
```
if (path.extname(this.name).toLowerCase() === '.vue') {
      opts.indentedSyntax = (this.options.rendition.type === 'sass') ? true : false
}
```
Apparently `this.options.rendition.type` resolves the correct indent syntax type and I use that to set the correct value for `opts.indentedSyntax`.
This solved the problem for me, though I'm really new to parcel source code and I feel there's a better way to tackle this.
Happy to help further with a bit of guidance!!
📦🤘

**Comment by DeMoorJasper** [comment]
@MattAndDev Awesome! Seems like you've found the correct solution.

This can also be happening on non vue assets, that also allow inlining sass in the file.

Could you do a PR that changes this line?
```Javascript
opts.indentedSyntax = typeof opts.indentedSyntax === 'boolean' ? opts.indentedSyntax : path.extname(this.name).toLowerCase() === '.sass';
```

Into something like this:
```Javascript
let type = this.options.rendition ? this.options.rendition.type : path.extname(this.name).toLowerCase();
opts.indentedSyntax = typeof opts.indentedSyntax === 'boolean' ? opts.indentedSyntax : type === '.sass';
```

**Comment by MattAndDev** [comment]
@DeMoorJasper Sure, I'm more then happy to help!
Will take a look at your proposal and prepare the PR! 🙌

**Comment by MattAndDev** [comment]
@DeMoorJasper your solution does not work as `let type` will resolve to `sass` and not `.sass`. 
(`this.options.rendition` is not returning a file extension apparently)
Will try to find a similar yet working way to solve this, be back soon!

**Comment by MattAndDev** [comment]
@DeMoorJasper  `let type` will result in `sass` not `.sass` as `this.options.rendition.type ` seems not to be a file extension. 
Will adapt this to the following:
```
let type = this.options.rendition ? this.options.rendition.type : path.extname(this.name).toLowerCase().replace('.','');
    opts.indentedSyntax = typeof opts.indentedSyntax === 'boolean' ? opts.indentedSyntax : type === 'sass';
```
PR coming!
