### ISSUE TITLE
Vue packages version mismatch:

### ISSUE THREAD

**Issue by areyouse7en** [parcel-bundler/parcel#1217]
"parcel-bundler": "^1.7.1"

Vue packages version mismatch:

- vue@2.5.13
- vue-template-compiler@2.5.16

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.1
| Node           |  8.9.3
| npm/Yarn    |  1.5.1
| Operating System |win10

**Comment by DeMoorJasper** [comment]
We don't use vue-loader or vueify?
Not sure what the issue is here

**Comment by Hammster** [comment]
@areyouse7en is refering to the vue version missmatching with the vue-template-compiler version. But i am confused since the package.json actually handles the version correctly https://github.com/parcel-bundler/parcel/blob/master/package.json#L96-L97

**Comment by dakshshah96** [comment]
@DeMoorJasper How do I use `vue-loader` with Parcel? An example would be really helpful 😄

**Comment by areyouse7en** [comment]
yes, I saw that the version of vue and vue-tempalte-complier are the same in package.json, but it still throw the mismatch error. I have to install vue-template-complier again to fix it.

**Comment by Hammster** [comment]
@dakshshah96 wrong place to ask, feel free to ask on the slack channel though. 😄

**Comment by DeMoorJasper** [comment]
@dakshshah96 you don’t there is full vue support build into parcel no need for any extra packages. Vue-loader is webpack specific

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
