### ISSUE TITLE
Cannot disable htmlnano comment stripping

### ISSUE THREAD

**Issue by fiws** [parcel-bundler/parcel#1218]
This a 🐛 bug report.

### 🎛 Configuration (.posthtmlrc)

```js
{
  "plugins": {
    "htmlnano": {
      "removeComments": false
    }
  }
}

```

### 🤔 Expected Behavior

Comments from my html file (`index.html`) are not removed.

### 😯 Current Behavior

Comments are removed.

### 💁 Possible Solution

I could pass `--no-minify`, but I want minification for js and css.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.1
| Node             | 9.11.1
| npm              | 5.8.0
| Operating System | Arch Linux

**Comment by DeMoorJasper** [comment]
Htmlnano, gets done seperately from posthtml, you could try htmlnanorc

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fiws** [comment]
Thank you @DeMoorJasper that worked!

 I did not find any documentation for `htmlnanorc`. Just [this file](https://github.com/parcel-bundler/parcel/blob/master/test/integration/htmlnano-config/.htmlnanorc). But simply putting `removeComments: false` in there worked like a charm.

I keep this open in case documentation additions or other improvements are wanted.
If not you can close this :)

**Comment by DeMoorJasper** [comment]
Docs have a seperate repository https://github.com/parcel-bundler/website so i'll close this :)
