### ISSUE TITLE
Recursive installation while aliasing vue 

### ISSUE THREAD

**Issue by sadick254** [parcel-bundler/parcel#1220]
🐛 bug report
While trying to alias vue to use the full build instead of the runtime build only parcel keeps on installing vue and never stops.
#### .babelrc
```js
{
  "presets": ["env"]
}
```
#### package.json
``` js
"name": "vue-reproduce",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "dev": "parcel index.html"
  },
  "devDependencies": {
    "parcel-bundler": "^1.7.1"
  },
  "alias": {
    "vue": "vue/dist/vue.common.js"
  },
  "dependencies": {
    "vue": "^2.5.16"
  }
```

### 🤔 Expected Behavior
The alias should reference the already installed vue instead of trying to install a new copy

### 😯 Current Behavior
The installation of vue is recursive and never completes.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.7.1
| Node             |v9.8.0
| npm/Yarn         |1.5.1
| Operating System | Windows 10

**Comment by DeMoorJasper** [comment]
If it's a folder it should be `./vue/dist/vue.common.js`, otherwise it should work if it's an installed npm module.
If it's the latter than it's probably an auto-install bug.

cc @davidnagli

**Comment by sadick254** [comment]
It is an npm installed module

**Comment by dakshshah96** [comment]
@sadick254 The workaround of `--no-autoinstall` by @DeMoorJasper prevents the recursive installation but now I get a new error: `Cannot resolve dependency 'vue'` in my `main.js` file. Any ideas?

**Comment by DeMoorJasper** [comment]
@dakshshah96 i’m not sure but it appears to be a bug with the resolver, more specifically with the aliases when used with node_module/...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sadick254** [comment]
The way I work around the recursive install currently is pointing the alias to the `node_modules`  that way I dont have to disable the `autoinstall` feature
``` js
"alias": {
    "vue": "./node_modules/vue/dist/vue.common.js"
  }
```

**Comment by DeMoorJasper** [comment]
Should be fixed
