### ISSUE TITLE
package.json in component folder stops transform of JSX for some tags

### ISSUE THREAD

**Issue by pke** [parcel-bundler/parcel#1223]
This is a real interesting 🐛 bug.

In my project I had a `<Footer/>` component that, when included would break the project.

![image](https://user-images.githubusercontent.com/164625/39054686-937f6740-44b2-11e8-9413-c2a97132f523.png)

The corresponding source in Chrome looked like this:

```js
var Footer = function Footer() {
  return <footer className="app-footer">
    </footer>;
};
exports.default = Footer;
```

This is half-transformed code.

That is the JSX

```jsx
import React from "react"
import PropTypes from "prop-types"

const Footer = () => {
  return (
    <footer className="app-footer">
    </footer>
  )
}
export default Footer
``` 

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [["env", "react"]],
  "plugins": [
    ["transform-class-properties"],
    ["transform-object-rest-spread", {
      "useBuiltIns": true
    }],
    ["module-resolver", {
      "root": ["./src"]
    }],
    ["transform-class-properties"],
    ["syntax-dynamic-import"],
    ["styled-jsx/babel"]
  ],
  "env": {
    "test": {
      "plugins": ["istanbul"]
    }
  }
}
```

### 🤔 Expected Behavior

The Footer file should be transformed correctly.

### 😯 Current Behavior

The Footer component's JSX is not transformed.

The culprit seems to be the package.json file in the components folder that contains this code:

```js
{
  "name": "footer",
  "version": "0.0.0",
  "private": true,
  "main": "./Footer.js"
}
```

neither

`import Footer from "Footer/Footer"`

nor

`import Footer from "Footer"`

will work.

### 💁 Possible Solution

Removing the package.json file (which came from core-ui reactstrap template) transforms the component correctly with the `<footer>` tag.

### 💻 Code Sample

Repo to reproduce this.
https://github.com/pke/parcel-package-transform-bug

`npm i && npm start`

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.7.1
| Node             | 9.9.0
| npm/Yarn         | npm 5.6.0
| Operating System | Windows 8.1

**Comment by srsatt** [comment]
Try add "source": "./Footer.js" in your package.json file. See documentation https://parceljs.org/transforms.html
