### ISSUE TITLE
newly generated css is not injected into html

### ISSUE THREAD

**Issue by gnijuohz** [parcel-bundler/parcel#1224]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
I think it's a bug

1) If a HTML file links to `index.js` and `index.js` import `index.css`, parcel will insert a link tag in the generated HTML. Everything works fine. 👍 

2) However, if `index.js` initially doesn't import `index.css` and instead the css file is created and  imported in `index.js` after running Parcel, a css bundle is correctly generated but not inserted in the generated HTML files. 😢 

### 🎛 Configuration (.babelrc, package.json, cli command)

no babel configuration.

### 🤔 Expected Behavior

a new link tag is inserted into the generated HTML and points to the newly generated CSS bundle

### 😯 Current Behavior

The generated HTML file does not link to the generated CSS bundle

### 💁 Possible Solution

Not sure. Maybe detecting cases like this and re-generating the HTML accordingly? I see some relevant logic in `HTMLPackage.js` but it's not rerun in this case.

### 🔦 Context

I sometimes start a project without CSS and only create them and import them after I started running Parcel. Currently I have to restart Parcel after doing that to make it work.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.1
| Node             | 8.9.1
| npm/Yarn         | 1.5.1
| Operating System | MacOS

**Comment by aboutqx** [comment]
Just got the same problem.

**Comment by fourcolors** [comment]
Yup, I have the same issue. Wasted about 20 minutes trying to figure out what I was doing wrong until I realized I needed to restart.
