### ISSUE TITLE
out-file option does not respect given file-extension

### ISSUE THREAD

**Issue by lqdchrm** [parcel-bundler/parcel#1228]
🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)
```cli
parcel build index.html --out-file index.aspx
```

### 🤔 Expected Behavior

The generated file should be ./dist/index.aspx

### 😯 Current Behavior

The generated file is ./dist/index.aspx.html

### 💁 Possible Solution

In Bundle.js@line_121 when checking for the outFile options, check for given file extension for example like so:

```js
// Parcel version: 1.7.1 File: Bundle.js Line: 121
// If this is the main entry file, use the output file option as the name if provided.
    if (isMainEntry && entryAsset.options.outFile) {

      let _ext = Path.extname(entryAsset.options.outFile);
      if (_ext && _ext.length > 0) {
        ext = _ext;
        name = Path.basename(entryAsset.options.outFile, ext)
      } else {

        name = entryAsset.options.outFile

      }
    }
```

### 🔦 Context
I would like the generated file to have "aspx" as file-extension

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.1
| Node             | 9.4.0
| npm/Yarn         | npm 5.6.0
| Operating System | Windows 10 x64

**Comment by DeMoorJasper** [comment]
Not sure if this should be done. I think parcel should stay responsible for extensions.
However in my opinion, we should strip of the extension and replace it with parcel's extension, this is currently not the case.
