### ISSUE TITLE
Parcel doesn't rebuild after second changings

### ISSUE THREAD

**Issue by sjuksin** [parcel-bundler/parcel#1230]
🐛 bug report
I've just installed parcel and tried to perform simple action:
```
parcel watch index.js
```
index.js content:
```
console.log(1)
```
Works fine, answer:
✨  Built in 799ms.

Then I changed and saved file:
Still works good, answer is: 
✨  Built in 19ms.

But when I changed and saved file again - no answer, no rebuild.

The same behaviour with
```
parcel index.js
```

Tried with versions 1.7.1 and 1.6.2
OS: Ubuntu 16.04

**Comment by DeMoorJasper** [comment]
https://en.parceljs.org/hmr.html#safe-write

**Comment by sjuksin** [comment]
Thanks, it helped.
