### ISSUE TITLE
🐛 Dependency calculation wrong when using HMR

### ISSUE THREAD

**Issue by danr** [parcel-bundler/parcel#1232]
A 🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

Consider these files:

    src/index.js:
        import * as View from './view'

        import * as Model from './model'
        console.log('Model.value =', Model.value)

        function updateView() {
          document.getElementById('root').innerHTML = View.getView()
        }

        updateView()

        if (module.hot) {
          module.hot.accept(() => {
            updateView()
          })
        }
        
    src/model.js:
        export const value = 1
        
    src/view.js:
        import * as Model from './model'

        export function getView() {
          return `<h1>Model.value = ${Model.value}</h1>`
        }

(I have a repo with this setup at:  https://github.com/danr/parcel-hmr-dependency)

Here, if you update the value in `model.js` then `view.js` is not hot module updated.
The culprit seems to be that `index.js` also imports `model.js`. If this import is removed
then updating `model.js` makes `view.js` be hot module updated as well.

I have a repo to reproduce at:

https://github.com/danr/parcel-hmr-dependency

### 🤔 Expected Behavior

When `model.js` is updated, `view.js` is hot module reloaded.

### 😯 Current Behavior

When `model.js` is updated, only `index.js` but not `view.js` is hot module reloaded.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.1
| Node             | 9.7.1
| npm/Yarn         | 1.5.1
| Operating System | 4.15.7-1-ARCH

**Comment by mischnic** [comment]
Seems like this was fixed in v1.9.5.
