### ISSUE TITLE
Set a directory as entry point

### ISSUE THREAD

**Issue by rohith** [parcel-bundler/parcel#1239]
### 🤔 Expected Behavior

Being able to provide a directory as an entry point. Parcel can then process all files in that directory & spit them out to dist folder

### 😯 Current Behavior

Parcel requires a file as an entry point which helps in computing & processing the dependencies

### 💁 Possible Solution

#189 might help in providing a possible solution. I guess even the dependency computation can be skipped as all files in the directory can be processed as one-to-one

Although, I'm not sure about a situation where few files in the directory need to be bundled together as a single file post processing

### 🔦 Context

In a simple setup like this, where **src** directory is the entry point for parcel it should be able to produce the files in **dist** directory

```
.
|-- src
    |-- bg.ts
    |-- content.ts
    |-- manifest.json
    |-- popup.jade
    |-- popup.ts
    |-- popup.styl
|-- dist
    |-- bg.js
    |-- content.js
    |-- manifest.json
    |-- popup.html
    |-- popup.js
    |-- popup.css
|-- .babelrc
|-- .gitignore
|-- package.json
```

Although the sample directory structure resembles a web extension (#1039), it might not always be the case & being able to point to a directory handles a lot of use-cases

**Comment by dobesv** [comment]
Can't you just run `parcel build src/*` ?

**Comment by rohith** [comment]
Thanks @dobesv I never knew I could do that 😱 

**Observations using `parcel build src\*`** 👨‍🔬 

- `manifest.json` gets converted to `manifest.js` file 😕 
- if there's a sub-directory under `src` then parcel treats it as a module & throws an error saying it cannot find module 😑 

I did get away with `parcel build src\*.ts src\*.jade src\*.styl` though 😍

**Comment by dobesv** [comment]
The translation from json to js is normal, it's so you can import json from
js.

**Comment by muzea** [comment]
I also have this demand. I want to compile all the files in a directory, the directory structure is similar to the following

```text
src
├── api
│   └── test.ts
├── index.ts
└── static
    └── index.html
```
This is an http application that decides which api to load based on a request parameter.

index.ts is like
```ts
import Koa from 'koa';

const app = new Koa();

app.use(async ctx => {
  const func = require('./api/' + ctx.request.query.funcName);
  ctx.body = func();
});

app.listen(3000);
```
Now I can use `parcel build src/* src/**/* --target node --out-dir build`, but this writing doesn't look so good, I hope I can combine `src/* src/**/*` into one parameter.
