### ISSUE TITLE
The packaged file is too LARGE

### ISSUE THREAD

**Issue by JZLeung** [parcel-bundler/parcel#124]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
🐛 the 

### 🎛 Configuration (.babelrc, package.json, cli command)

here is my codes:
index.js
```jsx
console.log('hello, from parcel.')
require('./css/index.css')

import React, {Component} from 'react'
import ReactDOM from 'react-dom'

// import Test from './js/components/test'
const Test = () => {
    return <div>Hey, here is Test Cwefweomponent!!!!!!</div>
}

ReactDOM.render((
    <div>
        <h1>Hello React</h1>
        <h2>Hello Parcel</h2>
        <Test />
    </div>
), document.getElementById('root'))
```

### 😯 Current Behavior

after running: ` NODE_ENV=production && parcel build index.html --no-minify`
if without `--no-minify`, it doesn't work #8 
```bash
total 1544
-rw-r--r--  1 lynnleung  staff   120B 12  8 17:37 068be14c44c5675d76e18130404f6790.css
-rw-r--r--  1 lynnleung  staff   762K 12  8 17:37 068be14c44c5675d76e18130404f6790.js
-rw-r--r--  1 lynnleung  staff   488B 12  8 17:37 index.html
```

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  1.03
| Node             | 8.9.1
| Yarn         | 1.3.2
| Operating System | macOS 10.13.1

**Comment by thejameskyle** [comment]
What doesn't work?

**Comment by cedric-marcone** [comment]
I think his problem is :
- it works with the "--no-minify" flag
- it doesn't without it
;)

**Comment by davidnagli** [comment]
@cedric-marcone That sounds allot like issue #8
