### ISSUE TITLE
Unknown version <..> of <device> (Improved error handling)

### ISSUE THREAD

**Issue by JonathanHuot** [parcel-bundler/parcel#1243]
🙋 feature request

### 🤔 Expected Behavior

When `parcel` has failures during build, the user should know what to fix and have the maximum of context information around the error.

### 😯 Current Behavior

`Unknown version 6.2 of samsung` https://github.com/parcel-bundler/parcel/issues/1036
`Unknown version 62 of android` https://github.com/parcel-bundler/parcel/issues/1144
(others..?)

During build, it seems `parcel` complains about an `Unknown version <..> of <device>` which is not the actual root cause of the error. It is misleading for the investigation and take hours before understanding what is the issue.

### 💁 Possible Solution

Add maximum of context information when this error is thrown.

### 🔦 Context

The error message should be improved to help developers to fix the actual issue.

### 🌍 Your Environment

See the issues referenced above.

**Comment by aurbano** [comment]
Thanks for opening the issue @JonathanHuot 

I've just tried on another computer, same result. Details:

* This is an existing (big) application that uses webpack at the moment, I'm trying to evaluate a switch to parcel
* node v9.11.1
* parcel v1.7.1

**Comment by DeMoorJasper** [comment]
The origin of this issue is still kind of shady, therefore it's not really that easy to know what we should change about the error being thrown.

**Comment by DeMoorJasper** [comment]
Track progress here: #1036
