### ISSUE TITLE
🐛 FS Module not loaded correctly in Electron Vue.js

### ISSUE THREAD

**Issue by mubaidr** [parcel-bundler/parcel#1244]
### 🎛 Configuration (.babelrc, package.json, cli command)
```
{
  "comments": false,
  "presets": [
    ["env", {
      "targets": {
        "node": 8
      }
    }],
    "stage-0"
  ],
  "env": {
    "test": {
      "plugins": ["transform-es2015-modules-commonjs"]
    }
  },
  "plugins": ["transform-runtime"]
}

```

### 🤔 Expected Behavior

FS module should be correctly loaded. 

### 😯 Current Behavior

FS module is not loaded, error:
```
Uncaught TypeError: fs.existsSync is not a function
    at Object.parcelRequire.46.fs (..\..\..\node_modules\electron\index.js:6)
    at newRequire (main.4f9b08dc.js:48)
    at localRequire (main.4f9b08dc.js:54)
    at Object.parcelRequire.54.electron (components\Templates\NavBar.vue:31)
    at newRequire (main.4f9b08dc.js:48)
    at localRequire (main.4f9b08dc.js:54)
    at Object.parcelRequire.15../components/Templates/NavBar (App.vue:18)
    at newRequire (main.4f9b08dc.js:48)
    at localRequire (main.4f9b08dc.js:54)
    at Object.parcelRequire.2.vue (main.js:12)
```

### 💁 Possible Solution

~Don't know. :(~

Using `window.require` instead of `require` loads module correctly. 

### 🔦 Context

I am trying to run Vue.js application inside Electron. I am using `fs` module to read files but after `parcel-bundler` fs module is not loaded. 

### 💻 Code Sample

https://github.com/mubaidr/image-parsing

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.1
| Node             | 9.11.1
| npm/Yarn         | 5.6
| Operating System | Windows 10
| Electron.js | 2.0.0-beta.7

**Comment by DeMoorJasper** [comment]
You could try with `--target=electron`

**Comment by mubaidr** [comment]
I have tried setting target as node or electron but it does not change anything.

**Comment by satoyan** [comment]
I have same problem in Adobe CEP app.
CEP is the kind of chromium browser app. It can be enabed to run nodejs directory with command args --enable-nodejs. "fs" is only module which causes error. Other library like path works well.

**Comment by dai875939260** [comment]
is any solution for this issue? i have same problem when import electron in render ,the problem  as mubaidr say. i see relate issue is add this code add index.html:
```js
  window.nodeRequire = require;
  delete window.require;
  delete window.exports;
  delete window.module;
  const electron = nodeRequire('electron').remote;
```
but in render ,    ` console.log(electron.ipcRenderer)` got undefined. in webpack  provide two options :`electron-renderer` and `electron-main`

![image](https://user-images.githubusercontent.com/6057326/40882456-fc247504-6714-11e8-93c9-6feb34d03343.png)

 i think parcel may also provide two options

**Comment by dai875939260** [comment]
my problem，the electron api is ` const electron = nodeRequire('electron').ipcRenderer`

**Comment by devongovett** [comment]
fs inlining is only enabled for `browser` targets:

https://github.com/parcel-bundler/parcel/blob/96856bacd75bedcf1a09e89a66ee7083d8e069d0/src/assets/JSAsset.js#L118-L119

You can also even disable it yourself within browser targets in package.json:

```json
{
  "browser": {
    "fs": false
  }
}
```

https://github.com/parcel-bundler/parcel/blob/96856bacd75bedcf1a09e89a66ee7083d8e069d0/src/assets/JSAsset.js#L122-L123
