### ISSUE TITLE
"parcel build" removes type="text"

### ISSUE THREAD

**Issue by hs749** [parcel-bundler/parcel#1245]
Bug report, maybe feature report after reading Jasper's comment. :smiley: 

Running the following command from shell:
      parcel build index.html
Inside index.html file, there is one line:
`<input type="text" name="demo" value="Hello">`
After parcel build, the above line becomes:
`<input name="demo" value="Hello">`     
type="text" is removed.

**Comment by DeMoorJasper** [comment]
Probably text is the default so htmlnano removes it to optimise the code

**Comment by hs749** [comment]
Hi Jasper, thank you for the reply.
You are right, input tag default type is "text". (https://stackoverflow.com/questions/33637093/will-input-default-to-a-type-of-text). 
And I noticed that my CSS on input[type="text"] stopped working after production build, while it worked in development build.  It seems that removing type="text" affects CSS styling. Should htmlnano not remove it ?

**Comment by DeMoorJasper** [comment]
Hmmm in that case, I’ll do dome research we might be able to set a flag for safe transforms in htmlnano. Otherwise we’d might have to report this as an issue

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hs749** [comment]
@DeMoorJasper 
Thanks for your suggestion. 
So far It's been amazing experience to use Parcel as bundler tool for web development. 
Thanks.
