### ISSUE TITLE
🐛 CSS filename content hash changes from build to build

### ISSUE THREAD

**Issue by benhutton** [parcel-bundler/parcel#1250]
### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": "> 5%",
        "uglify": true
      },
      "useBuiltIns": true
    }]
  ],

  "plugins": [
    "syntax-dynamic-import",
    "transform-object-rest-spread",
    ["transform-class-properties", { "spec": true }]
  ]
}
```

### 🤔 Expected Behavior

From build to build, the filename should not change unless the content of the file changes.

### 😯 Current Behavior

For ONE of our files, on our heroku review apps (but not locally, at least not for me), the filename changes on every deploy.

For example, first it will be `application.f3b97f03.css` and then after another deploy it will be `application.4b4d6a70.css`. I've downloaded and diffed the files, and they are identical.

The JS file is fine: its name does not change from build to build.

### 🔦 Context

Once we deploy, our cached pages are referencing css files that don't exist anymore!

### 💻 Code Sample

Unfortunately, this is in a closed-source app. But I'm happy to try things and report back.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.1 |
| Node             | 8.11.1 |
| npm/Yarn         | 5.6.0/1.6.0 |
| Operating System | `heroku-16` stack (ubuntu, I believe) |

**Comment by FDiskas** [comment]
Probably `parcel` sgould use something like https://www.npmjs.com/package/md5-file :disappointed:

**Comment by DeMoorJasper** [comment]
This is a strange bug, would be very helpfull to have a minimal repro repo. (unfortunately reading your issue this isn't easy to reproduce)

There could be only 2 things wrong, either one (or more) of the assets return a different hash for some reason, or the order of the assets changed.

@FDiskas We already create filehashes inside the assets which is inside the workers. So this module would slow down parcel significantly. Besides only slowing down it would also be hard to use as it uses files and parcel hasn't written the file when creating the hash
