### ISSUE TITLE
TypeScript files are not type checked 🐛

### ISSUE THREAD

**Issue by laurence-myers** [parcel-bundler/parcel#1252]
This is a 🐛 bug report.

### 🎛 Configuration (.babelrc, package.json, cli command)

```
project
+- tsconfig.json
+- src/
+-- main.ts
+- webview/
+-- tsconfig.json
+-- webview.html
+-- webview.ts
```

### 🤔 Expected Behavior

Bundling HTML that includes .ts files should fail when the TypeScript files fail compilation due to type checks failing.

### 😯 Current Behavior

Bundled files are not type checked; a bundle is always produced, and no TypeScript errors are presented to the user.

### 💁 Possible Solution

Collect TypeScript compilation failures, print them to the console, and abort bundling.

(My workaround for now is to have a separate TypeScript compiler process running in the background in watch mode, with "noEmit" set to true in tsconfig.json.)

### 🔦 Context

Bundling code for use in a mobile WebView and retaining type safety.

### 💻 Code Sample

index.ts:
```typescript
const myValue: string = 123;
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.0
| Node             | 8.9.4
| npm/Yarn         | 1.3.2
| Operating System | Windows 10

**Comment by DeMoorJasper** [comment]
For typechecking use this plugin, this is outside the scope of the ts support inside parcel https://github.com/fathyb/parcel-plugin-typescript

**Comment by fathyb** [comment]
Please note the plugin isn't compatible with Parcel `1.7.1` for now, it should be fixed in the next days.
