### ISSUE TITLE
Completely restart bundler with `rs`

### ISSUE THREAD

**Issue by xeoneux** [parcel-bundler/parcel#1254]
🙋 feature request!

### 🤔 Expected Behavior

Similar to nodemon, typing `rs` should build the files again after clearing cache.

### 😯 Current Behavior

Parcel sometimes does not detect changes to files and imports on Windows 10 and requires complete restart.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.1
| Node             | 9.11.1
| npm/Yarn         | 6.0.0
| Operating System | Win 10

**Comment by mischnic** [comment]
> Parcel sometimes does not detect changes to files and imports on Windows 10 and requires complete restart.


Being able to restart Parcel more easily would just be a workaround for some watcher/cache bug.
