### ISSUE TITLE
Hot reload only works once

### ISSUE THREAD

**Issue by kaihendry** [parcel-bundler/parcel#1255]
Bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

https://s.natalian.org/2018-04-26/package.json

### 🤔 Expected Behavior

Hot reloading works more than once

### 😯 Current Behavior

https://s.natalian.org/2018-04-26/parcel.mp4

Only works once

### 🔦 Context

Trying to develop and get up & running with https://alligator.io/vuejs/vue-parceljs/

### 💻 Code Sample

https://s.natalian.org/2018-04-26/parcelvue.zip

### 🌍 Your Environment

Latest Archlinux

**Comment by DeMoorJasper** [comment]
This is a known issue with safe-write, check the docs for more details.
https://en.parceljs.org/hmr.html#safe-write

**Comment by elalienx** [comment]
Hi, any idea how to fix this on Visual Studio Code ?

**Comment by jvarahuayta** [comment]
Hello, i started working well but from one moment to another this stopped recognizing the changes in the files. I'm using Visual Studio Code.

**Comment by bilal-korir** [comment]
Thank you @DeMoorJasper saved my problem with IntelliJ

**Comment by fifn2** [comment]
I'm also having this bug in VScode.
