### ISSUE TITLE
HTML filename hashed

### ISSUE THREAD

**Issue by JensPauwels** [parcel-bundler/parcel#1258]
Is there an option to use to disable the HTML file hashing? I thought it was disabled for html files since version 1.7 but my html files still gets hashed.

**Comment by DeMoorJasper** [comment]
It should be disabled for 1.7, could you provide a minimal repro repo or how your filestructure looks?

**Comment by JensPauwels** [comment]
https://github.com/JensPauwels/parcelHtml there you go.

**Comment by DeMoorJasper** [comment]
Can't reproduce your parcel version is probably incorrect you could try three things:
* Update global parcel version (check current version using parcel -v)
* Use `npx parcel index.html`
* Use scripts section of package.json

**Comment by JensPauwels** [comment]
Thanks, the global version was outdated!
