### ISSUE TITLE
Hot reload crashes 75% of the time (macOS)

### ISSUE THREAD

**Issue by gorbypark** [parcel-bundler/parcel#1259]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "vue-parcel",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "vue": "^2.5.16"
  },
  "devDependencies": {
    "babel-preset-env": "^1.6.1",
    "parcel-bundler": "^1.7.1",
    "parcel-plugin-vue": "^1.5.0"
  },
  "alias": {
    "vue" : "./node_modules/vue/dist/vue.common.js"
  }
}
```
```
{
  "presets": [
    "env"
  ]
}
```
```parcel index.html```

### 🤔 Expected Behavior

Hot reload should reload on changes/

### 😯 Current Behavior

Hot reload crashes 75% of the time when it detects changes.  Starting parcel again and it works fine...until the next reload.

```
⏳  Building App.vue...
/Users/gorbypark/.config/yarn/global/node_modules/parcel-bundler/src/workerfarm/Worker.js:114
        throw new Error(
        ^

Error: Worker Farm: Received message for unknown index for existing child. This should not happen!
    at Worker.receive (/Users/gorbypark/.config/yarn/global/node_modules/parcel-bundler/src/workerfarm/Worker.js:114:15)
    at ChildProcess.emit (events.js:160:13)
    at emit (internal/child_process.js:790:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

### 💻 Code Sample

It is literally just a barebones vue environment.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.1
| Node             | 9.5.0
| npm/Yarn         | 1.3.2
| Operating System | macOS 10.12.6

**Comment by DeMoorJasper** [comment]
Why are you using parcel-plugin-vue?
There is native vue support in parcel

**Comment by lbguilherme** [comment]
Happens on 100% of `parcel build` for me, on 1.7.1 on Linux. Same error.

Downgrading to 1.7.0 solved.

**Comment by DeMoorJasper** [comment]
This is a very strange bug? This means the workers aren't being started by the workerfarm, so you're running something that's not part of parcels workers as workers @lbguilherme 
Would like to debug this if it's an open-source project, for now I'll open up a PR that just ignores these messages.

**Comment by tinchoz49** [comment]
Hi @lbguilherme! can you create an example project to test? I'm having the same error using parcel-plugin-typescript

**Comment by gorbypark** [comment]
@tinchoz49 Here's an [example project](https://github.com/gorbypark/parcel-error-repropduce/).  Sorry for the spelling mistake in the repo name, it's late!

**Comment by jaredpetker** [comment]
Same issue as @tinchoz49 - issues with parcel-plugin-typescript and, which I use for the extra features, running my project goes fine, however I get a worker farm issues with 1.7.1 similar to the OP when building, and this one on 1.8.1

```
Cannot read property 'run' of undefined
    at /Users/jaredpetker/dev/cc/confidentwholesale/frontend/node_modules/parcel-bundler/lib/workerfarm/child.js:68:45
    at Generator.next (<anonymous>)
    at step (/Users/jaredpetker/dev/cc/confidentwholesale/frontend/node_modules/parcel-bundler/lib/workerfarm/child.js:3:191)
    at /Users/jaredpetker/dev/cc/confidentwholesale/frontend/node_modules/parcel-bundler/lib/workerfarm/child.js:3:437
    at new Promise (<anonymous>)
    at /Users/jaredpetker/dev/cc/confidentwholesale/frontend/node_modules/parcel-bundler/lib/workerfarm/child.js:3:99
    at Child.handleRequest (/Users/jaredpetker/dev/cc/confidentwholesale/frontend/node_modules/parcel-bundler/lib/workerfarm/child.js:75:7)
    at Child.messageListener (/Users/jaredpetker/dev/cc/confidentwholesale/frontend/node_modules/parcel-bundler/lib/workerfarm/child.js:36:19)
    at emitTwo (events.js:130:20)
    at process.emit (events.js:213:7)
```
