### ISSUE TITLE
Unable to resolve `.jsm` module

### ISSUE THREAD

**Issue by lifeart** [parcel-bundler/parcel#126]
I'm using JavaScript modules
(https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Using)

this a 🐛 bug report
### 🎛 Configuration (.babelrc)

```js
{
    "presets": [
        "es2015"
    ],
    "plugins": [
        [
            "module-resolver",
            {
                "root": [
                    "./src"
                ],
                "extensions":[".js", ".jsx", ".es", ".es6", ".mjs", ".jsm"]
            }
        ]
    ]
}
```

### 🤔 Expected Behavior

if   I do

```js
import AngularState from 'modules/common/states/defaultState';
```

All Ok.

### 😯 Current Behavior
if I do 
```js
import AngularState from 'modules/common/states/defaultState';
```
I got error: Cannot resolve dependency, but

```js
import AngularState from 'modules/common/states/defaultState.jsm';
```

works 

### 💁 Possible Solution
any config to add proper file name extensions to resolve?

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  v1.1.0 
| Node             |  v7.9.0
| npm/Yarn         |  npm
| Operating System | Win10 x64

**Comment by DeMoorJasper** [comment]
These extensions are just not added to the Parser atm as far as i can see i'll make a pull request and add them
