### ISSUE TITLE
Option to disable automatic package installation

### ISSUE THREAD

**Issue by dobesv** [parcel-bundler/parcel#1263]
🙋 feature request?

A few times now I've made a typo in a package name and it went and installed some random package that I didn't want, or tried to install a package that doesn't exist, or went into an infinite loop trying to reinstall a package that WAS installed but resulted in an import error because I imported some file inside the module that did not exist.

e.g. I now have a package installed called `fquery` due to a (brief) misspelling of `jquery`.  Confused the heck out of me!

I think this feature is a little too automagical for me, I'd like to disable it.

**Comment by jrd261** [comment]
This didn't work for me. Looking through the source I found that I could disable through an enviornment variable:

```process.env.PARCEL_AUTOINSTALL = 'false';```
