### ISSUE TITLE
Keep .html files for SEO?

### ISSUE THREAD

**Issue by Flynrod** [parcel-bundler/parcel#1264]
Hello, I recently saw the issue #280 that talks about my current problem. However, I still don't know how to keep the names of my html files.
Are there parameters to add in the command or a configuration file to create to add exceptions?
I did not find any answer in the documentation of the site.

I got this /dist/6f7f56f0805baabfc8d30f88319b81ff.html instead of test.html by this:
`<a href="test.html">My link</a>` in index.html

Command executed: parcel src/index.html

Thanks in advance,
Flynrod

**Comment by DeMoorJasper** [comment]
You are on an outdated version of parcel, in Parcel 1.7.1 this should be the original name

**Comment by Flynrod** [comment]
Here's my package.json: (I'm using 1.7.1 version of Parcel)
```{
  "name": "SampleWebsite",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "autoprefixer": "^8.4.1",
    "babel-cli": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "css-mqpacker": "^6.0.2",
    "jquery": "^3.3.1",
    "node-sass": "^4.9.0",
    "parcel-bundler": "^1.7.1",
    "parcel-plugin-bundle-manifest": "^0.1.1",
    "postcss": "^6.0.22"
  }
}
```
![sans titre](https://user-images.githubusercontent.com/29288223/39405537-fa1e70e0-4ba6-11e8-95e9-39742854f7c5.png)

**Comment by Flynrod** [comment]
Thanks, I didn't know that Parcel has to be used with its local dependency.
It works with ```./node_modules/.bin/parcel src/index.html```
