### ISSUE TITLE
unknown Statement of type "ForOfStatement"

### ISSUE THREAD

**Issue by BobBuehler** [parcel-bundler/parcel#1269]
🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```js
{
    "scripts": {
        "dev": "parcel ./src/index.html -d build/ --target=browser"
    }
}
```

.babelrc
```js
{
    "presets": ["react"],
    "plugins": ["react-hot-loader/babel"]
}
```

### 🤔 Expected Behavior

It bundles and transpiles my es6 targetting node_module dependencies

### 😯 Current Behavior

regenerator-transform fails because it finds a for-of statement within a generator.
```
×  C:\git\my_webapp\node_modules\@private\core\dist\iterables.js: C:/git/my_webapp/node_modules/@private/core/dist/iterables.js: unknown Statement of type "ForOfStatement"
    at Emitter.Ep.explodeStatement (C:\git\my_webapp\node_modules\regenerator-transform\lib\emit.js:648:13)
    at C:\git\my_webapp\node_modules\regenerator-transform\lib\emit.js:344:12
    at Array.forEach (<anonymous>)
    at Emitter.Ep.explodeStatement (C:\git\my_webapp\node_modules\regenerator-transform\lib\emit.js:343:22)
    at Emitter.Ep.explode (C:\git\my_webapp\node_modules\regenerator-transform\lib\emit.js:298:40)
    at PluginPass.exit (C:\git\my_webapp\node_modules\regenerator-transform\lib\visit.js:122:15)
    at newFn (C:\git\my_webapp\node_modules\babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (C:\git\my_webapp\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\git\my_webapp\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\git\my_webapp\node_modules\babel-traverse\lib\path\context.js:117:8)
```

### 💁 Possible Solution

According to https://github.com/facebook/regenerator/issues/229 for-of statements need to be transformed before regenerator-transform can be applied. Maybe there is a way to force this.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.1 |
| Node             | 9.11.1 |
| npm/Yarn         | 1.6.0 |
| Operating System | Win 7 64bit |

**Comment by ThaddeusJiang** [comment]
who has a solution?

**Comment by ThaddeusJiang** [comment]
I created a custom builds.
So, the CKEditor 5 can work in project with parcel .

see: https://github.com/ThaddeusJiang/ckeditor5-build-blueberry

**Comment by lbittner-pdftron** [comment]
Also getting this.. no other solutions posted anywhere work

**Comment by Offirmo** [comment]
I got this when migrating to babel 7. I removed my .babelrc (which was no longer needed) and added the @babel/core: ^7 dependency and the error disappeared.

**Comment by devongovett** [comment]
Is anyone still having this issue? Sounds like possibly an issue in Babel rather than parcel itself?

**Comment by raine** [comment]
I start getting this in parcel v1.11.0 if I import `p-memoize`.

```
import pMemoize from 'p-memoize'
```

```
🚨  node_modules/map-age-cleaner/dist/index.js: unknown Statement of type "ForOfStatement"
    at Emitter.Ep.explodeStatement (node_modules/regenerator-transform/lib/emit.js:587:13)
    at node_modules/regenerator-transform/lib/emit.js:323:12
    at Array.forEach (<anonymous>)
    at Emitter.Ep.explodeStatement (node_modules/regenerator-transform/lib/emit.js:322:22)
    at Emitter.<anonymous> (node_modules/regenerator-transform/lib/emit.js:542:14)
    at LeapManager.LMp.withEntry (node_modules/regenerator-transform/lib/leap.js:143:14)
    at Emitter.Ep.explodeStatement (node_modules/regenerator-transform/lib/emit.js:541:24)
    at node_modules/regenerator-transform/lib/emit.js:323:12
    at Array.forEach (<anonymous>)
    at Emitter.Ep.explodeStatement (node_modules/regenerator-transform/lib/emit.js:322:22)
```

**Comment by mischnic** [comment]
> Sounds like possibly an issue in Babel rather than parcel itself?

Well, Parcel doesn't transpile node_modules (neither with an option) and `@babel/plugin-transform-regenerator` can't handle `for of`.
In an ideal world, https://www.npmjs.com/package/map-age-cleaner wouldn't use a `for of` loop.

**Comment by Offirmo** [comment]
@mischnic parced DOES transpile node_modules, provided the modules have a `.babelrc`

See my comment above.

**Comment by JoshyB** [comment]
Has anyone made any progress with this? I just started running into this last night and cannot figure out a solution. I am using Parcel-bundler as an express middleware and cannot get it to build at all. 


```
node_modules/parcel-bundler/src/Bundler.js: unknown Statement of type "ForOfStatement"
    at Emitter.Ep.explodeStatement (node_modules/regenerator-transform/lib/emit.js:587:13)
    at node_modules/regenerator-transform/lib/emit.js:323:12
    at Array.forEach (<anonymous>)
    at Emitter.Ep.explodeStatement (node_modules/regenerator-transform/lib/emit.js:322:22)
    at Emitter.Ep.explodeStatement (node_modules/regenerator-transform/lib/emit.js:510:12)
    at node_modules/regenerator-transform/lib/emit.js:323:12
    at Array.forEach (<anonymous>)
    at Emitter.Ep.explodeStatement (node_modules/regenerator-transform/lib/emit.js:322:22)
    at Emitter.<anonymous> (node_modules/regenerator-transform/lib/emit.js:542:14)
    at LeapManager.LMp.withEntry (node_modules/regenerator-transform/lib/leap.js:143:14)
error Command failed with exit code 1.
```

**Comment by BobBuehler** [comment]
Not that I'm aware of @JoshyB, my team had to switch back to Webpack. :(

**Comment by BobBuehler** [comment]
Closing was not what I meant to click. I'm surprised I had permission to do that. Sorry.

**Comment by Offirmo** [comment]
@JoshyB did my solution above help? https://github.com/parcel-bundler/parcel/issues/1269#issuecomment-427158354

**Comment by raine** [comment]
It had no effect for me.

**Comment by JoshyB** [comment]
@Offirmo I gave your solution a shot but it still wouldn't build. Same error.

**Comment by yuhr** [comment]
Same here, no one has resolved the issuee?

**Comment by yuhr** [comment]
I was facing into this error only when I use `ipfs` module, but FWIW now I found a workaround: in `package.json` setting like

```
  "browserslist": [
    "last 2 Chrome versions"
  ],
```

solved the issue for me (idea from https://github.com/ipfs/js-ipfs/blob/master/examples/browser-parceljs/package.json).

**Comment by pyros2097** [comment]
@yuhr Thanks ran into the same problem when using ipfs. Almost switched to webpack after seeing this https://github.com/orbitdb/example-orbitdb-todomvc-updated

**Comment by tehraven** [comment]
> I was facing into this error only when I use `ipfs` module, but FWIW now I found a workaround: in `package.json` setting like
> 
> ```
>   "browserslist": [
>     "last 2 Chrome versions"
>   ],
> ```
> 
> solved the issue for me (idea from https://github.com/ipfs/js-ipfs/blob/master/examples/browser-parceljs/package.json).

This fixed my issue. Cheers.

**Comment by guillaumepotier** [comment]
@tehraven @yuhr may have fixed the issue, but the code you're shipping would not be supported by IE11. I'm still struggling with this problem, and I *really* need to support IE. Any help here?

**Comment by cymen** [comment]
Sorry for the pollution but if you end up here due to googling, it's likely due to browserslist removing "IE 11" from the defaults (4 hours ago as of now) and the short term fix is to add back `IE 11` to your list of browsers as it is no longer included in `defaults`.

**Comment by dep** [comment]
> > I was facing into this error only when I use `ipfs` module, but FWIW now I found a workaround: in `package.json` setting like
> > ```
> >   "browserslist": [
> >     "last 2 Chrome versions"
> >   ],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > solved the issue for me (idea from https://github.com/ipfs/js-ipfs/blob/master/examples/browser-parceljs/package.json).
> 
> This fixed my issue. Cheers.

Didn't work for me.

```
ERROR in /Users/dpeck/invoca/Titan/node_modules/d3-array/src/merge.js
Module build failed (from /Users/dpeck/invoca/Titan/node_modules/babel-loader/lib/index.js):
Error: /Users/dpeck/invoca/Titan/node_modules/d3-array/src/merge.js: unknown Statement of type "ForOfStatement"
    at Emitter.Ep.explodeStatement (/Users/dpeck/invoca/Titan/node_modules/regenerator-transform/lib/emit.js:593:13)
    at /Users/dpeck/invoca/Titan/node_modules
```

**Comment by dep** [comment]
> Sorry for the pollution but if you end up here due to googling, it's likely due to browserslist removing "IE 11" from the defaults (4 hours ago as of now) and the short term fix is to add back `IE 11` to your list of browsers as it is no longer included in `defaults`.

That didn't solve things for me. My problem persists:

```
ERROR in /Users/dpeck/invoca/Titan/node_modules/d3-array/src/number.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: /Users/dpeck/invoca/Titan/node_modules/d3-array/src/number.js: unknown Statement of type "ForOfStatement"
```

**Comment by ruanltbg** [comment]
@dep to solve my issue I removed the `browserslist` file/or from the `package.config.js`

**Comment by keya129** [comment]
Adding "babel-plugin-transform-es2015-for-of": "^6.23.0" in package.json and compiling it first in babel config 👍  plugins: [
      '@babel/plugin-transform-for-of',
....
worked

**Comment by techiekarthick** [comment]
Updating your .browserlistrc file to include support for IE11

 `
defaults
IE 11
`

It worked fine for me,

**Comment by theletterzee** [comment]
> [@dep](https://github.com/dep) to solve my issue I removed the `browserslist` file/or from the `package.config.js`

This also worked for me.
