### ISSUE TITLE
Vue HMR - Parcel does not preserve state 

### ISSUE THREAD

**Issue by JDrechsler** [parcel-bundler/parcel#1275]
**🐛 bug report**

For me parcel does not preserve the state when I use Vue with hot reloading.

[Link to a sample project](https://github.com/JDrechsler/Vue-hmr-test-parcel-and-webpack)

### 🤔 Expected Behavior

When I use the vue-cli with webpack I can make changes in my templates without losing the state as shown in the video on github.

### 😯 Current Behavior

Right now the state gets lost every time I save a change.

There are no error messages. Everything else works fine.

### 💁 Possible Solution

I am not sure how to fix/implement that but maybe the people behind vue-loader can help.

### 🔦 Context

It is super handy when working with modals for example. I can make changes and see the modal change instantly but with parcel I always have to open the modal again because the state gets lost. 
Having the state preserving hot reload enables faster development.

### 💻 Code Sample

 [Sample code and sample video](https://github.com/JDrechsler/Vue-hmr-test-parcel-and-webpack)

**Comment by ZiFFeL1992** [comment]
Any update on this one? :)

**Comment by wxs77577** [comment]
It seems there is no hot module reload feature for vue, I think I should still use webpack or  vue-cli.

**Comment by ZiFFeL1992** [comment]
Hope this will fixed for next parcel version :pray:

**Comment by devongovett** [comment]
Closing since this bug is for parcel 1
