### ISSUE TITLE
Add support for purging unused CSS

### ISSUE THREAD

**Issue by kripod** [parcel-bundler/parcel#1276]
🙋 Feature request

### 🤔 Expected Behavior

There are packages like [PurifyCSS](https://github.com/purifycss/purifycss), [UnCSS](https://github.com/uncss/uncss) and [Purgecss](https://github.com/FullHuman/purgecss) for purging unused CSS classes in the final bundle. Unfortunately, none of them can be used out of the box along with Parcel.

### 😯 Current Behavior

Currently, the resulting HTML/CSS/JS files are minified during the build phase, but redundant CSS classes aren't removed.

### 💁 Possible Solution

It would be great if there was opt-in support for purging unused CSS. There is a PostCSS plugin called [postcss-uncss](https://github.com/uncss/postcss-uncss) which doesn't work with Parcel.

### 🔦 Context

This would be extremely useful for websites based on a CSS framework _(e.g. Bootstrap or Bulma)_.

**Comment by mischnic** [comment]
How do you know in advance which classes aren't used if they are used by javascript after pageload?

**Comment by kripod** [comment]
@mischnic For instance, [there are configuration options in UnCSS](https://github.com/uncss/uncss/blob/master/README.md) for that. That’s why I want this to be an opt-in feature.

**Comment by mischnic** [comment]
Ok.

> There is a PostCSS plugin called postcss-uncss which doesn't work with Parcel.

Why not?

**Comment by timothydang** [comment]
i think https://github.com/cprecioso/parcel-plugin-purgecss is the plugin that you're looking for @kripod

**Comment by waynehoover** [comment]
There is also the postcss plugin for purgecss that you could use if you are using postcss: https://github.com/FullHuman/postcss-purgecss

**Comment by brianzelip** [comment]
Here's [a working example of using Purgecss with Parcel](https://github.com/brianzelip/zelip.me), via parcel-plugin-purgecss.

Method:
1. `npm i -D parcel-plugin-purgecss`
2. create purgecss.config.js file in project root directory, ie:

```js
/// purgecss.config.js
module.exports = {
  content: ['index.html', 'src/**/*.vue'],
  css: ['src/css/main.css']
};
```

**note**: css only purged on build, not dev server.

**Comment by lukehedger** [comment]
With Parcel2, `purgecss` can be used without any additional plugins.

`postcss.config.js`
```js
module.exports = {
  plugins: ["@fullhuman/postcss-purgecss"]
};
```

`purgecss.config.js`
```js
module.exports = {
  content: ["index.html"]
};
```

[Example here](https://github.com/lukehedger/cssless/tree/c7badf7484272e02f69222eda4b169b51f212fec).

**Comment by ranisalt** [comment]
> With Parcel2, `purgecss` can be used without any additional plugins.

Except it spills warnings that doing the way you did, with a postcss JS config, loses caching ability.

**Comment by aminya** [comment]
Uncss is better in this regard. Uncss executes the JavaScript (purgecss just removes static classes).

https://github.com/uncss/uncss

It would be nice if Parcel adds more support for uncss or even integrate it to Parcel by default.
