### ISSUE TITLE
based on docs it's not clear if one could require scss from html or not

### ISSUE THREAD

**Issue by safareli** [parcel-bundler/parcel#1278]
Based on current docs it's not clear if one could require scss from html or not:

> # CSS
> CSS assets can be imported from a JavaScript **or HTML** file ... In addition to plain CSS, other compile-to-CSS languages like LESS, **SASS**, and Stylus are also supported, and **work the same way**.
> 
> # [SCSS](https://parceljs.org/assets.html#scss)
> ... Once you have node-sass installed you can import **SCSS files from JavaScript files** ...

**Comment by DeMoorJasper** [comment]
Issues for the website should go here: https://github.com/parcel-bundler/website

To clarify it should be possible.
