### ISSUE TITLE
LESS custom resolver syntax not supported

### ISSUE THREAD

**Issue by ntomsic** [parcel-bundler/parcel#1281]
**Choose one:**  🐛 bug report

Using custom resolver syntax for LESS `@import '~...'` to import LESS files from node_modules/ doesn't work and gives an error.

### 🤔 Expected Behavior

Compile without issues. This works in webpack using `less` and `less-loader`.

### 😯 Current Behavior

```
~/project/src/styles.global.less: '~semantic-ui-less/semantic.less' wasn't found. Tried - ~/project/src/~semantic-ui-less/semantic.less,~semantic-ui-less/semantic.less
```

### 🔦 Context

Can't compile using less files from packages in node_modules/

### 💻 Code Sample
Install `semantic-ui-less`

```less
@import '~semantic-ui-less/semantic.less'
```
```js
import './styles.less'
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.0
| Node             | 8.11.1
| npm/Yarn         | npm 6.0.0
| Operating System | OSX Sierra

**Comment by DeMoorJasper** [comment]
It should be
`import 'semantic-ui-less/semantic.less'`
the `~` character resolves to the root of the project inside parcel

**Comment by ntomsic** [comment]
That actually didn't work either. Would have to do
```less
@import 'node_modules/semantic-ui-less/semantic.less`
```
