### ISSUE TITLE
Requires Babel "^7.0.0-0", but was loaded with "6.26.3". 

### ISSUE THREAD

**Issue by willin** [parcel-bundler/parcel#1287]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

Bug

> Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.

### 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc: 

```js
{
  "presets": [
    "@babel/preset-env"
  ],
  "plugins": [
    ["@babel/plugin-transform-react-jsx", { "pragma": "h" }]
  ]
}
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1 |
| Node             | 10.0.0 |
| npm/Yarn         | 6.0.0 / 1.6.0 |
| Operating System | os x |

**Comment by DeMoorJasper** [comment]
Parcel doesn’t support babel 7 atm.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
