### ISSUE TITLE
Feature Request: Svelte support

### ISSUE THREAD

**Issue by antony** [parcel-bundler/parcel#129]
Something like:

* https://github.com/sveltejs/svelte-loader
* https://github.com/rollup/rollup-plugin-svelte

Would be amazing :)

**Comment by DeMoorJasper** [comment]
I currently have made a very basic implementation of this plugin over here https://github.com/DeMoorJasper/parcel-plugin-svelte
There is still some improvements to be made though

**Comment by DeMoorJasper** [comment]
Questions regarding Svelte support should now be redirected to https://github.com/DeMoorJasper/parcel-plugin-svelte
Closing this off
