### ISSUE TITLE
🐛tilde does not work with eslint

### ISSUE THREAD

**Issue by cj** [parcel-bundler/parcel#1290]
Right now if you use `~` in your project eslint will complain it can't find the module.

### 🎛 Configuration (.babelrc, package.json, cli command)

https://gist.github.com/cj/6ac12225333bc454c428fd62f70a7da5

### 🤔 Expected Behavior

It should just work.

### 😯 Current Behavior

Throwing an error saying it can't find the module

### 💁 Current Solution

The current solution is to add two plugins, one for eslint `eslint-import-resolver-babel-module` and one for babel `babel-plugin-module-resolver`. You then add this to your `.eslintrc.js`

```
  settings: {
    "import/resolver": {
      "babel-module": {}
    }
  },
```

and this to your `.babelrc`

```
    ["module-resolver", {
      "alias": {
        "~": "./client"
      }
    }],
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 8.11.1
| Yarn         | 1.6.0
| Operating System | osx

**Comment by DeMoorJasper** [comment]
This doesn't seem to be parcel related, but more likely something with eslint-config, perhaps someone could write an eslint plugin that utilises parcel's resolver
