### ISSUE TITLE
CSS Classes from imported node modules are not being hashed by CSS modules

### ISSUE THREAD

**Issue by bjankord** [parcel-bundler/parcel#1292]
🐛 bug report, I believe, though this could also be a feature request

### 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```json
{
  "name": "parcel-modules-test-case",
  "version": "1.0.0",
  "description": "Test case repo demoing issue with parcel and css modules",
  "main": "index.js",
  "scripts": {
    "start": "parcel index.html --no-cache",
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "parcel build index.html --public-url /parcel-modules-test-case/",
    "deploy": "gh-pages -d dist"
  },
  "devDependencies": {
    "parcel-bundler": "^1.8.0"
  },
  "dependencies": {
    "autoprefixer": "^8.2.0",
    "gh-pages": "^1.1.0",
    "node-sass": "^4.8.3",
    "postcss-modules": "^1.1.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "terra-base": "^3.2.0",
    "test-react-ui-button": "^1.2.0"
  }
}
```

.postcssrc
```json
{
  "modules": true
}
```

### 🤔 Expected Behavior
Classes from the imported node modules are hashed by CSS modules being turned on in single app level `.postcssrc` file.

### 😯 Current Behavior
Demo app includes `.postcssrc` which sets `modules: true` turning on CSS modules. However, CSS modules / hashed class names are only applied to classes in `app.scss`. Class names used in react components imported from packages in node_modules are not hashed with CSS modules.

### 💁 Possible Solution

Ideally, adding a `.postcssrc` file with `modules: true` would work both for locally imported styles, e.g. `./app.scss` and imported styles from node modules. 

If there is a concern with this being applied too globally, having the ability to turn on CSS modules with 1 app level `.postcssrc` and have it apply globally to all CSS file imports filtered by file naming convention set in the `.postcssrc` file would be fine too, e.g. apply globally to all files that end in `.module.css` / `.module.scss` .

### 🔦 Context

I have react components that are intended to be used with CSS modules. When I import them into an app bundled with Parcel, the classes are applied in the rendered DOM, but they are not hashed. This will lead to naming collisions as some of the components use the same class names, but rely on the hashing feature of CSS modules to remove the name collision conflict.

### 💻 Code Sample

Reduced test case repo: https://github.com/bjankord/parcel-modules-test-case

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v1.8.0 |
| Node             | v8.4.0 |
| npm/Yarn         | npm v5.6.0 / yarn v1.0.1 |
| Operating System | OSX |

**Comment by devongovett** [comment]
Closing since this was from parcel 1
