### ISSUE TITLE
🐛IntelliJ terminal output not clearing lines

### ISSUE THREAD

**Issue by Morgul** [parcel-bundler/parcel#1293]
When running parcel from inside of Webstorm's Terminal or a Run Configuration, parcel's "Building ..." messages all show up on a single line. Running in a regular terminal, they are clearing the previous line and overwriting it.

### 🎛 Configuration (.babelrc, package.json, cli command)

This happens with any site I've tried with parcel and does not see to be configuration based.

### 🤔 Expected Behavior

I expect either to have new lines between the "Building..." lines, or for it to work the exact same as in a regular terminal.

### 😯 Current Behavior

As you can see from this screen shot:

![image](https://user-images.githubusercontent.com/770655/39634786-5044b866-4f81-11e8-9ba4-c9902dad2fd5.png)

It is not correctly clearing the previous line.

### 💁 Possible Solution

This is, arguably an IntelliJ bug. However, I don't know what parcel is doing that's different from any of the other tools (ex: `npm`, `yarn`) that clear the line and replace it (all of which work). I would love to see parcel either use the same mechanism as other packages that do this correctly, or a CLI option for parcel to forego clearing the line and instead putting a new line between messages.

### 🔦 Context

It makes it incredibly difficult to read error messages output during the parcel build. (I have to scroll right and look for any red text.)

### 🌍 Your Environment

I've tried with Webstorm, IntelliJ IDEA, and PyCharm; all have this issue.

**Comment by dobesv** [comment]
Try setting the environment variable `FORCE_COLOR=0` in your run configuration, this turns off most of the fancy styling and prints each status on its own line.

**Comment by Morgul** [comment]
That worked!. I would still like color, and the fancy, but until whatever's wrong with that can be worked through, this is much more survivable.

**Comment by DeMoorJasper** [comment]
Does https://github.com/parcel-bundler/parcel/pull/1472 fix this issue?

**Comment by Morgul** [comment]
I'll give it a test tonight, and let you know. I will say that I've used `ora` in webstorm before, and it works great, so I have high hopes!

**Comment by Morgul** [comment]
@DeMoorJasper Sorry it took so long, but #1472 definitely fixes this issue:

![2018-06-03 18 56 30](https://user-images.githubusercontent.com/770655/40892670-e8484cfe-675f-11e8-8184-06a5d6af146a.gif)

Thanks so much!
