### ISSUE TITLE
🐛 Build alter inlined javascript

### ISSUE THREAD

**Issue by L-Naej** [parcel-bundler/parcel#1297]
🐛 bug report 

Hello,
When I'm using parcel-cli "**parcel build src/index.html --public-url ./ --out-dir build/**" the output alter inline JS leading to not working code. This does not happen when using **parcel src/index.html** (bundled server).

🤔 Expected Behavior

The inlined JS should not be changed.

😯 Current Behavior

The inlined JS in my HTML is being wrongly altered.
How it is in my source file :
```html
<link rel="stylesheet" href="less/incarna.less" media="none" onload="if(media!='all')media='all';">
```
The output in build/index.html:
```html
<link rel="stylesheet" href="incarna.3defd595.css" media="none" onload=""all"!=media&&(media="all")"> 
```
As you can see, **if(media!='all')media='all'**; as been translated to **"all"!=media&&(media="all")**

💁 Possible Solution
I have no idea!

🔦 Context
Doing a simple landing page using UIKIT.

🌍 Your Environment
I'm using VIsualStudioCode.

**Comment by DeMoorJasper** [comment]
This is probably because htmlnano minifies js. Didn’t know it changed inlined js though, probably changing a setting would fix this

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
