### ISSUE TITLE
babel-eslint support

### ISSUE THREAD

**Issue by JensPauwels** [parcel-bundler/parcel#1302]
Is there a way in parcel to support arrow functions as public functions to a class?

```
class Demo {
  constructor(id) {
    this.id = id;
  };

  showId = () => {
    return this.id();
  };
}
```
Unexpected token
![schermafbeelding 2018-05-05 om 17 42 10](https://user-images.githubusercontent.com/17976979/39664917-a9744126-508b-11e8-800e-bfe3dae26467.png)

.eslintrc file : 

`{
  "presets": ["env"],
  "parser": "babel-eslint",
  "plugins": ["transform-class-properties"]
}`

**Comment by dobesv** [comment]
This is what I have in `.babelrc`:

```
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "browsers": [
            "last 2 versions",
            "safari >= 7"
          ]
        }
      }
    ]
  ],
  "plugins": ["transform-class-properties", "transform-object-rest-spread"]
}
```

Is it possible you should have created a `.babelrc` instead of `.eslintrc` ?

**Comment by JensPauwels** [comment]
indeed, i created an eslintrc file instead of a babelrc file. Thanks for the support!
