### ISSUE TITLE
Parcel watch not updating filename on html asset, but parcel build does

### ISSUE THREAD

**Issue by dobesv** [parcel-bundler/parcel#1305]
# 🐛 bug report

I noticed that `parcel watch` was not updating the filename of some assets even though their content had changed.

If you look at this shell transcript you can see all the files and steps required to reproduce the issue:

```
$ cat index.html
<html><head><link href=404.html></head></html>
$ cat 404.html
2
$ cat dist/index.html
<html><head><link href="/404.9b5f82f7.html"></head></html>
$ echo 3 >404.html
⏳  Building 404.html...
$ ⏳  Building...
⏳  Building 404.html...
✨  Built in 21ms.

$ cat dist/index.html
<html><head><link href="/404.9b5f82f7.html"></head></html>
$ cat dist/404.9b5f82f7.html 
3
$ echo 4 >404.html
⏳  Building 404.html...
⏳  Building...
⏳  Building 404.html...
✨  Built in 5ms.
$ cat dist/index.html
<html><head><link href="/404.9b5f82f7.html"></head></html>
$ cat dist/404.9b5f82f7.html 
4
```

Basically I can see that it updates the content of the file but does not update its hash.

Note that if I do the same thing but use `parcel build` between changes instead of `parcel watch`, the file hash *does* update according to the file contents:

```
$ parcel build index.html
✨  Built in 755ms.

dist/index.html           59 B    661ms
dist/404.b4931ae5.html     2 B     12ms
$ parcel build index.html
✨  Built in 173ms.

dist/index.html           59 B    21ms
dist/404.b4931ae5.html     2 B    39ms
$ echo 7 >404.html
$ parcel build index.html
✨  Built in 1.22s.

dist/index.html           59 B      6ms
dist/404.d2730112.html     2 B    1.09s
$ parcel build index.html
✨  Built in 143ms.

dist/index.html           59 B    43ms
dist/404.d2730112.html     2 B    36ms
```

I tried `parcel watch` with the `--no-cache` but that didn't fix it.

## 🤔 Expected Behavior

When the file changes, so should its generated filename.  Otherwise I can't safely set maximum caching on those files safely!

## 😯 Current Behavior

The filename stays the same for some files, even when the content changed.

## 💁 Possible Solution

Looks like a bug, just have to figure out why it is happening and fix it.

## 🔦 Context

I can't set long caching headers on these assets, because then they are never reloaded in the browser.

Luckily this will only affect development, I suppose I won't use `parcel watch` in production.  But since I run in development using the same nginx config as production for testing purposes, I would rather this weren't happening.

**Comment by dobesv** [comment]
One thing is strange is that `parcel watch` generates the same hash for that file no matter what, it's not the same hash as `parcel build` produces.

**Comment by DeMoorJasper** [comment]
This is for performance reasons, there is no need to invalidate files in development mode.

**Comment by dobesv** [comment]
Would it be possible to write the file with no hash in the name of the hash
won't change?  This is very confusing behavior otherwise. Is this behavior
documented?

**Comment by devongovett** [comment]
The hash is there in dev mode for 2 reasons:

1. The directory is flattened - you could have 2 `main.js` files in your build but we can't output them both in the same directory with the same name. The hash solves this problem.
2. The filenames look closer to how they will look in production, just the hash doesn't change.

**Comment by dobesv** [comment]
Would you consider documenting this behavior so people aren't as likely to get unpleasantly surprised and confused as I was?
