### ISSUE TITLE
'postcss-svg fragment' is not working

### ISSUE THREAD

**Issue by gpeddler** [parcel-bundler/parcel#1307]
# 🐛 bug report

`postcss-svg` is not working

## 🎛 Configuration (.babelrc, package.json, cli command)

*.postcssrc*
```.postcssrc
{
    "modules": true,
    "plugins": {
        "postcss-svg": {},
        ...
    }
}
```

*styles.pcss*
```pcss
.imageBox {
    background: url("./resources/svg/image.svg#id");
}
```

## 🤔 Expected Behavior

I expected this line
`url("./resources/svg/image.svg#id")`

to be like this
`url("data:image/svg+xml;charset=utf-8 ....")`

## 😯 Current Behavior

But now postcss-svg works nothing
`url("./resources/svg/image.svg#id")`
(nothing happend)-->
`url("./resources/svg/image.svg#id")`

## 🔦 Context

It works at webpack, but it's not working at parcel.
I think parcel-bundler override logics to process svg files.
Is there any way to turn off options to process svg files?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1 |
| Node             | - |
| npm/Yarn         | 1.6.0 |
| Operating System | mac OS sierra 10.12.6 |

**Comment by mischnic** [comment]
This will work in Parcel 2 because PostCSS is run before dependencies are collected.
