### ISSUE TITLE
Html partials

### ISSUE THREAD

**Issue by JensPauwels** [parcel-bundler/parcel#1311]
# ❔ Question

Does parcel support something like partials, to include html pieces into another html file.
For example a header.html file which contains the header for my project. In this case i wouldn't need to change the header section in 10 other files but only in 1 file.

Currently i'm using knockout to do this and that's working fine if i do not need to require any images, unfortunately if i do use the image require it'll give me this error.

<img width="593" alt="schermafbeelding 2018-05-06 om 22 33 03" src="https://user-images.githubusercontent.com/17976979/39677569-7c6493a0-517d-11e8-8232-3503e4428084.png">

The strange part is that i include this require on multiple pages and on some pages it just works fine but on others it doesn't

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 8.8.1
| npm/Yarn         | 1.3.2
| Operating System | MacOS High sierra 10.13.2

**Comment by DeMoorJasper** [comment]
You can use a posthtml plugin, as we natively use posthtml to process html files already and support this using `posthtml.config.js`

This plugin seems to do the trick: https://github.com/posthtml/posthtml-include

**Comment by DeMoorJasper** [comment]
I assume this is resolved?
