### ISSUE TITLE
Index.html can not be omitted when serving multiple files

### ISSUE THREAD

**Issue by tamuraryoya** [parcel-bundler/parcel#1315]
# 🐛 bug report

When bundling and serve multiple entry files, `/ index.html` can not be accessed with `localhost:1234/`

However, you can access it with `localhost: 1234 / index.html`

## 🎛 Configuration (.babelrc, package.json, cli command)

```pug
//- src/index.pug
h1 hello world!
```

```pug
//- src/sub.pug
h1 sub page!
```

```
$ parcel 'src/**/*.pug'
```

## 🤔 Expected Behavior

When accessing `localhost:1234/`, "hello world!" is displayed

## 😯 Current Behavior

Accessing `localhost:1234/` will display empty HTML

```html
<html>
  <head></head>
  <body></body>
</html>
```

However, accessing `localhost: 1234 / index.html` will display the page correctly

## 💁 Possible Solution

I do not know, but when accessed with `/` we have to make sure to check the existence of `/ index.html`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |v1.8.1|
| Node             |v8.11.1|
| npm/Yarn         |v6.0.0/v1.5.1|
| Operating System |MacBook Pro (High Sierra)|

**Comment by DeMoorJasper** [comment]
This is because it currently checks for an entrypoint and multiple entrypoints works with a html entrypoint thats being created in the background as a main asset to link all assets too

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lucaseverett** [comment]
It would be helpful to have index.html served from / and any other entry points served without .html.

So, page1.html would be resolved by visiting /page1.

Is there a way to create URL rewrites for the server locally in a project?

**Comment by MathieuLoutre** [comment]
I've got a working solution for this (as explained in #1778) and can PR if this is agreeable.

Essentially, it enhances the `respond` method by looking for indexes (with a method replacing `sendIndex` called `findIndex`), looking for the main bundle as it does now, failing that looking for an HTML file called `index.html`.

```js
 function respond() {
      let {pathname} = url.parse(req.url);
      if (bundler.error) {
        return send500(bundler.error);
      } else if (
        !pathname.startsWith(bundler.options.publicURL) ||
        path.extname(pathname) === ''
      ) {
        const index = findIndex(pathname)
        if (index) {
          req.url = `/${path.basename(index)}`;
          serve(req, res, send404);
        }
        else {
          send404();
        }
      } else {
        // Otherwise, serve the file from the dist folder
        req.url = pathname.slice(bundler.options.publicURL.length);
        return serve(req, res, send404);
      }
    }

    function findIndex(pathname) {
     // If the bundle is HTML, send that
      if (bundler.mainBundle.type === 'html') {
        return bundler.mainBundle.name;
      }
      else if (pathname === bundler.options.publicURL) {
        // if the pathname is empty, look for files named index.html in the bundle and send back the first one. If there's nothing, return null;
        const indexes = Array.from(bundler.mainBundle.childBundles).filter((asset) => path.basename(asset.name) === 'index.html');
        return indexes[0].name;
      }
      return null;
    }
```

**Comment by pbastowski** [comment]
Has there been any progress on this issue?

**Comment by LuudJanssen** [comment]
Started working on [a pull request for this issue](https://github.com/LuudJanssen/parcel/tree/serve-index-by-default)

I'm experiencing some test errors, which I asked about [on Spectrum](https://spectrum.chat/parcel/?thread=ff160383-9fc5-4a2d-a0d9-0228a578c763). Once those are resolved I can add the pull request. It is using @MathieuLoutre's fix ([here](https://github.com/parcel-bundler/parcel/issues/1315#issuecomment-407140722)) and not setting index to true as suggested [here](https://github.com/parcel-bundler/parcel/issues/2215#issuecomment-433753458) if that would be the better option I can change that in the PR, the tests for it stay the same.

**Comment by ideoclickVanessa** [comment]
FWIW: This issue also occurs when you just have a single .tsx entry point (`parcel src/index.tsx`) as well

**Comment by bichotll** [comment]
Same happened here when `parcel *.html`.

That actually confused my colleague and thought the computer was under the weather lol
It would be nice to solve this issue. It would avoid any confusion in the future.

**Comment by aldovincenti** [comment]
Is there any news on this issue?

**Comment by mismith** [comment]
Looks like lots of people requesting this feature, any word on whether there's even a workaround to solve this?

**Comment by elisei-timofte** [comment]
Same here. Any updates?

**Comment by shaunakv1** [comment]
Same here, just ran into this, with the whole team confused as to what happened, when the second entry point was first added.

**Comment by bgschiller** [comment]
In the meantime, I have this workaround set up:
```
const Bundler = require('parcel-bundler');
const express = require('express');

const bundler = new Bundler(['src/index.html', 'src/login.html', 'src/logout.html']);
const app = express();

app.get('/', (req, res) => {
  // or do something fancier, like make a self-request to `/index.html`
  // and send the contents back.
  // (That would be necessary if you have client-side SPA routing)
  res.redirect('/index.html');
});

app.use(bundler.middleware());

const port = Number(process.env.PORT || 1234);
app.listen(port);
console.log(`listening at http://localhost:${port}`);
```

**Comment by hanabi1224** [comment]
Looking forward to this feature!

**Comment by johnagan** [comment]
I ended up writing a local plugin as a bandaid, until we get a legit fix. It uses the same modules included in Parcel v1. Only gotcha is you have to use the `watch` command to trigger it. Here's an example of what it looks like - ymmv:

### Usage
```sh
parcel watch [entries] --serve
parcel watch [entries] --serve --open
```


```js
const serveStatic = require("serve-static"); // included in parcel v1
const { createServer } = require("http");

module.exports = (bundler) => {
  let serverStarted = false; // prevent from restarting on rebundle
  const openBrowser = process.argv.contains("--open");
  const useServer = process.argv.contains("--serve");

  bundler.on("bundled", () => {
    if (useServer && !serverStarted && bundler.options.watch) {      
      serve(bundler.options.outDir, 8080, openBrowser);
      serverStarted = true;
    }
  })
}

async function serve(outDir, port, openBrowser) {
  const serve = serveStatic(outDir, { extensions: ["html"] });

  // 404 handler
  const redirect = (res) => {
    res.writeHead(302, { Location: "/404" });
    res.end();
  };

  // request handler
  const handler = (req, res) => {
    serve(req, res, () => redirect(res));
  };

  // start server
  createServer(handler).listen(port, () => {
    // optional if you want to open the browser (included in parcel v1)
    if (openBrowser) require("opn")(`http://localhost:${port}`);
  });
}
```
