### ISSUE TITLE
Incorrect href for relative parent and incorrect slash in href

### ISSUE THREAD

**Issue by marcosbozzani** [parcel-bundler/parcel#1318]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

**cli**
```
yarn install
yarn build
```
**package.json**
```js
{
  "name": "parcel-index-bug",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "parcel-bundler": "^1.8.1",
    "rimraf": "^2.6.2"
  },
  "scripts": {
    "build": "rimraf dist && parcel build src/index.html src/folder/index.html"
  }
}
```

## 🤔 Expected Behavior

**dist/index.html**
```html
<h1>Index</h1><a href="/folder/index.html">Page</a>
```

**dist/folder/index.html**
```html
<h1>Folder</h1><a href="/">Index</a>
```

## 😯 Current Behavior

**dist/index.html**
```html
<h1>Index</h1><a href="/folder\index.html">Page</a>
```

**dist/folder/index.html**
```html
<h1>Folder</h1><a href="/827e5741e37d7e3b2dbec2ade5523f20.">Index</a>
```

## 🔦 Context

**src/index.html**
```html
<h1>Index</h1>
<a href="./folder/index.html">Page</a>
```

**src/folder/index.html**
```html
<h1>Folder</h1>
<a href="..">Index</a>
```

## 💻 Code Sample

https://github.com/marcosbozzani/parcel-index-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | parcel 1.8.1
| Node             | node v8.9.4
| npm/Yarn         | yarn 1.6.0
| Operating System | windows 10 1703

**Comment by rokyed** [comment]
+1
