### ISSUE TITLE
Can't use `styleName` props with css modules + react.

### ISSUE THREAD

**Issue by kawamurakazushi** [parcel-bundler/parcel#1320]
# 🐛 bug report

Hi, I'm creating a simple app using typescript + react + css modules.
And the styleName is not compiling in the right way.

Please refer to the code sample below.

## 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc
```js
{
  "presets": ["react-app"],
  "plugins": [
    [
      "module-resolver",
      { "root": ["./src"] }
    ],
    "transform-class-properties",
    [
      "react-css-modules",
      {
        "generateScopedName": "[path]__[name]__[local]__[hash:base64:5]",
        "handleMissingStyleName": "warn"
      }
    ]
  ]
}
```

.postcssrc
```js
{
   "modules": true,
   "plugins": {
    "postcss-modules": {
      "generateScopedName": "[path]__[name]__[local]__[hash:base64:5]"
    }
  }
}
```

tsconfig.json
```js
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "jsx": "react",
    "baseUrl": "src",
    "lib": [ "es2015" ]
  }
}

```

package.json
```js
{
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
  },
  "devDependencies": {
    "@types/react": "^16.3.13",
    "@types/react-css-modules": "^4.6.1",
    "@types/react-dom": "^16.0.5",
    "babel-plugin-module-resolver": "^3.1.0",
    "babel-plugin-react-css-modules": "^3.4.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-preset-react-app": "^3.1.1",
    "parcel-bundler": "^1.7.1",
    "parcel-plugin-typescript": "^0.7.1",
    "postcss-modules": "^1.1.0",
    "react-css-modules": "^4.7.2",
    "typescript": "^2.8.3"
  },
  "scripts": {
    "start": "parcel src/index.html"
  }
}
```

## 🤔 Expected Behavior

Compile

## 😯 Current Behavior

Whenever I run parcel styleName just compiles to stylename.

<img width="1261" alt="localhost_1234_" src="https://user-images.githubusercontent.com/7858158/39739987-98249c5a-52ce-11e8-82b6-89794c758c9c.png">

When I try using `className` instead of `styleName` it works like a charm using the following solution discussed in this issue.
https://github.com/parcel-bundler/parcel/issues/616

## 💻 Code Sample
src/index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title> 
  <link rel="stylesheet" href="./index.css">
</head>
<body>
  <div id="root"></div>
</body>
<script src="index.jsx"></script>
</html>
```
src/index.tsx
```js
import * as React from 'react';
import * as ReactDOM from 'react-dom';

import App from 'App';

ReactDOM.render(<App />, document.getElementById('root'));
```

src/App.tsx
```js
import * as React from 'react';
import  './App.css';

const App = () => {
  return (
      <div>
        <h1 styleName="main">hi</h1>
      </div>
  );
};

export default App;
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.1
| Node             | v9.11.0
| Yarn         | 1.6.0
| Operating System | mac

**Comment by Hammster** [comment]
the issue is the normalization of the html, up percase attributes are not valid even though they get parsed because the SVG standard allows them. If you change styleName to style-name it should be parsedcorrectly at least this works in vue

**Comment by alexesDev** [comment]
@kawamurakazushi react-css-modules is a babel plugin... nothing to do with ts.

**Comment by DeMoorJasper** [comment]
@Hammster probably a good idea, but jsx doesn't get processed by post-html so this is a different issue

**Comment by Hammster** [comment]
Oh didnt know that but least it is a valid explaination for #1123

**Comment by DeMoorJasper** [comment]
Has this solution fixed your issue @kawamurakazushi ?
