### ISSUE TITLE
Unable to call functions due to ReferenceError

### ISSUE THREAD

**Issue by piedar** [parcel-bundler/parcel#1328]
# 🐛 bug report

Unable to call functions from inside a `<script>` tag due to

> Uncaught ReferenceError: foobar is not defined

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```js
{
  "name": "parc",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "parcel-bundler": "^1.8.1"
  }
}
```

```
yarn parcel index.html
```

## 🤔 Expected Behavior

I should be able to call functions from inside a `<script>` tag.
In other words, the code sample below should print

> js foobar
> html foobar

## 😯 Current Behavior

> js foobar
> Uncaught ReferenceError: foobar is not defined

## 🔦 Context

This is a simplified example with only `index.html` and `index.js`.

## 💻 Code Sample

Full test cast at https://github.com/piedar/parc

index.html
```
<!DOCTYPE html>
<html>
<body>

<script src="./index.js"></script>

<script>
  console.log("html " + foobar())
</script>

</body>
</html>
```

index.js
```
export function foobar() {
  return "foobar"
}

console.log("js " + foobar())
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel              | 1.8.1
| Node              | 8.11.1
| npm/Yarn         | yarn 1.6.0
| Operating System | Windows 7

**Comment by DeMoorJasper** [comment]
yarn parcel index.html --global window

**Comment by piedar** [comment]
Hmm, that didn't help somehow.  Should the following work?

```html
<script>
  console.log("foobar is " + window.foobar)
  console.log("html " + foobar())
</script>
```

    yarn parcel index.html --global window

For now it prints

> foobar is undefined
> Uncaught ReferenceError: foobar is not defined

**Comment by DeMoorJasper** [comment]
Yeah i don't know anymore, haven't tested any of the new umd features

**Comment by piedar** [comment]
No worries, and thanks for your time.  If anyone wants to replicate, I published the test case at https://github.com/piedar/parc.

Also, if I'm using the "new umd features", what would I change to try it the old way instead?

**Comment by Maxzilla60** [comment]
As far as I understand, the `--global` option works as long as you don't name it `window`. 😅

I currently run my project like this:
```bash
parcel index.html --global index
```
And call exported functions inside my `html` like this:
```javascript
index.someFunction();
```

**Comment by piedar** [comment]
Indeed it does!  Thanks!

**Comment by 95lux** [comment]
Does this also apply for bundling the application for production via:
` 
parcel build index.html --global index
` ?

**Comment by Malthehave** [comment]
> Does this also apply for bundling the application for production via:
> ` parcel build index.html --global index` ?

Yes it does. I just tested it on version 1.12.4
