### ISSUE TITLE
The SASSAsset incorrectly resolves dependency if an NPM module of the same name is installed.

### ISSUE THREAD

**Issue by nidheeshdas** [parcel-bundler/parcel#1329]
# 🐛 bug report

My simple bootstrap 4 scss was not compiling. On investigation, I found that the SassAsset incorrectly resolves the "progress" import in the bootstrap SCSS to an NPM module with the same name. Please see the screenshot from the VSCode debugger.

![screen shot 2018-05-09 at 11 54 15](https://user-images.githubusercontent.com/1284466/39799306-6dadfa1c-5381-11e8-8af8-8f9f2d96fc99.jpg)

The "progress" module comes from "eslint":

![screen shot 2018-05-09 at 11 55 51](https://user-images.githubusercontent.com/1284466/39799323-830824e6-5381-11e8-8a48-500241a57d4a.jpg)

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "plugins": ["react-hot-loader/babel", "transform-class-properties"]
}
```

## 🤔 Expected Behavior

Should resolve "progress" import from bootstrap SCSS to appropriate "_progress.scss" file or throw an exception since the resolved file is not of expected extension(s).

## 😯 Current Behavior

Resolves an SCSS import to a JS module.

```
🚨  /Users/nidheeshdas/Sources/bagsim-server/client/src/style/index.scss: Invalid CSS after "m": expected 1 selector or at-rule, was "module.exports = re"
    at options.error (/Users/nidheeshdas/Sources/bagsim-server/node_modules/node-sass/lib/index.js:292:26)

```

## 💁 Possible Solution

The Resolver should reject a file if it's not of expected extension.

## 🔦 Context

Unable to compile Bootstrap4 with ESLint installed.

~/Sources/test-proj
```
$ ls -lah
total 128
drwxr-xr-x    6 nidheeshdas  staff   192B May  9 12:13 .
drwxr-xr-x   43 nidheeshdas  staff   1.3K May  9 12:12 ..
drwxr-xr-x    2 nidheeshdas  staff    64B May  9 12:13 dist
drwxr-xr-x  274 nidheeshdas  staff   8.6K May  9 12:14 node_modules
-rw-r--r--    1 nidheeshdas  staff   133B May  9 12:14 package.json
-rw-r--r--    1 nidheeshdas  staff    59K May  9 12:14 yarn.lock

~/Sources/test-proj
$ cat package.json
{
  "dependencies": {
    "bootstrap": "^4.1.1",
    "eslint": "^4.19.1"
  },
  "devDependencies": {
    "node-sass": "^4.9.0"
  }
}

~/Sources/test-proj
$ parcel build node_modules/bootstrap/scss/bootstrap
🚨  /Users/nidheeshdas/Sources/test-proj/node_modules/bootstrap/scss/bootstrap.scss: Invalid CSS after "m": expected 1 selector or    at options.error (/Users/nidheeshdas/Sources/test-proj/node_modules/node-sass/lib/index.js:291:26)

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | v8.11.1
| npm/Yarn         | 1.6.0
| Operating System | macos 10.13.4

**Comment by DeMoorJasper** [comment]
The resolver should give priority to files over node_modules already.
Not sure why this occurs, my PR fixes this by implementing the sass specific import syntax.

Although I don't really want to break the current scss files created for the more universal syntax we utilised before.

**Comment by c316** [comment]
Removing eslint fixes the issue for me as well.
