### ISSUE TITLE
Dependency with jsx doesn't work

### ISSUE THREAD

**Issue by kuba-orlik** [parcel-bundler/parcel#1330]
# 🐛 bug report

since parcel v1.5 requiring an npm-installed dependency with jsx modules doesn't work - Parcel doesn't process the jsx file.

## 🎛 Configuration (.babelrc, package.json, cli command)

`.babelrc`: 

```json
{
	"presets": ["env", "react"]
}

```

command:

```
parcel build src/frontend/index.html --out-dir public --public-url /
```

## 🤔 Expected Behavior

The jsx files are transpiled and made a part of the bundle

## 😯 Current Behavior

An error is thrown: 

```
⏳  Building...
🚨  /opt/project/node_modules/sealious/cosealious/lib/loading.jsx:10:3: Unexpected token (10:3)
   8 | 	for (var i = 0; i < boxes_amnt; i++) {
   9 | 		boxes.push(
> 10 | 			<div
```

## 💁 Possible Solution

The only fix I've found is to downgrade parcel to version <1.5, which is obviously undesirable

## 🔦 Context

We have a library of jsx components that we install via npm. 

## 💻 Code Sample

https://github.com/kuba-orlik/parcel-rep

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.
| Node             | 9.11.1
| npm         |  5.8.0
| Operating System | Linux

**Comment by newtriks** [comment]
I've the same issue, slightly different circumstances where I have a project configured using Lerna and need to compile imported (local) packages within that architecture.

**Comment by mohsen1** [comment]
If you own the dependency you can set the `source` key in package.json to point to source. When symlinked, Parcel will compile source of those dependencies too.

**Comment by kuba-orlik** [comment]
@mohsen1 

> you can set the source key in package.json to point to source

What to do you mean?

**Comment by DeMoorJasper** [comment]
See #1101

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by embeddedt** [comment]
> When symlinked, Parcel will compile source of those dependencies too.

Is it possible to do this without symlinks? I am trying to use an `npm` package that uses JSX and I am having the exact same issue as the original poster (syntax error on the first JSX statement).

I did try putting `"source": true` in the `package.json` of the JSX module but that didn't change anything.

**Comment by ihorml** [comment]
+1 the same

**Comment by rv-thlittle** [comment]
+1 same issue with npm package.

**Comment by szympajka** [comment]
+1...
