### ISSUE TITLE
Parcel sometimes fails to start properly

### ISSUE THREAD

**Issue by wyhaya** [parcel-bundler/parcel#1342]
# 🐛 bug report

He can sometimes work, sometimes he can't work.

When I remove the `scss` file it may improve, but I'm not sure if the problem is there.

Perhaps it is related to the loading mechanism of the module?

Faster processing when there are fewer modules, When the number of modules is large, the dependency is more complicated and the relationship is not handled properly, Causes the process to exit abnormally.

![2018-05-14 09_49_45](https://user-images.githubusercontent.com/23690145/39974561-39c3cb76-575c-11e8-9fa4-ce485717f3de.gif)

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
  "name": "parcel",
  "version": "1.0.0",
  "scripts": {
    "dev": "parcel ./src/view/*.html"
  },
  "devDependencies": {
    "node-sass": "^4.9.0",
    "parcel-bundler": "^1.8.1"
  }
}

```

## 🤔 Expected Behavior

Normal start work

## 😯 Current Behavior

Sometimes quit abnormally

Comparison of loading `scss` files and removing `scss`

![-1](https://user-images.githubusercontent.com/23690145/39963529-409c2a0e-56a0-11e8-801e-8fed14ce1aa0.png)

## 🔦 Context

```bash
parcel ./src/view/*.html
```

```bash
yarn run v1.5.1
$ parcel ./src/view/*.html
Server running at http://localhost:1234
⏳  Building hmr-runtime.js...
error An unexpected error occurred: "Command failed.
Exit signal: SIGSEGV
Command: sh
Arguments: -c parcel ./src/view/*.html
Directory: /Users/WYH/Desktop/parcel
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/WYH/Desktop/parcel/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## 💻 Code Sample
`index.html :`
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="../style/index.scss">
</head>
<body>
  hello world
</body>
</html>
```
`base.scss :`
```scss
body{
  background: red;
}
```
`index.scss :`
```scss
@import './base.scss';
.btn{
    width: 100px;
    height: 38px;
    border: 1px solid #ae2616;
    color: #ae2616;
    outline: none;
    background-color: transparent;
    cursor: pointer;
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 9.9.0
| npm/Yarn         | 1.5.1
| Operating System | macOS High Soerra `10.13.4`

**Comment by tsiq-swyx** [comment]
i get this too in my create-react-app-parcel project. (just the base template, nothing fancy at all). its super weird, 1 out of 20 times it will run. there is a segfault somewhere and I don't know how to debug it further:
![image](https://user-images.githubusercontent.com/35976578/39962691-b4114004-5624-11e8-8148-57d7af30edf8.png)

**Comment by tsiq-swyx** [comment]
after doing something else for awhile and then coming back, this problem goes away. so there seems to be some memory lock on something that then gets garbage'd away? not really knowing the internals of parcel I don't even know how to track this down further than the SIGSEGV error.

**Comment by wyhaya** [comment]
This problem does not occur when using ` parcel build`

**Comment by tsiq-swyx** [comment]
right, so its a `parcel` or `parcel watch` problem. i still can't track it down but its more intermittent for me now. any one have ideas on how to reliably reproduce this kind of segfault error?

**Comment by wyhaya** [comment]
![2018-05-14 09_32_06](https://user-images.githubusercontent.com/23690145/39974215-c1a076d2-5759-11e8-9ff6-310be08fa8d8.gif)

**Comment by DeMoorJasper** [comment]
Might be related to this issue: https://github.com/strongloop/fsevents/issues/218

**Comment by DeMoorJasper** [comment]
You simple put `require('segfault-handler').registerHandler();` at the start of the bundler.js file

**Comment by tsiq-swyx** [comment]
ok thanks. i cant replicate the segfault right now, will wait for the next
time this happens.

**Comment by DeMoorJasper** [comment]
No problem, I'll do a PR that should fix this in a few mins

**Comment by tsiq-swyx** [comment]
thanks, confusingly it just works every time now. hard to replicate this but i'll keep this issue open on c-r-a-p.

**Comment by ewyler** [comment]
When is the planned release date for the next version with the fix incorporated? This is consistently reproducible for me using the current latest version (1.8.1, same as in this original report).

**Comment by JamesTheHacker** [comment]
Exactly the same problem here. It's been happening a lot this morning.

**Comment by fang0rnz** [comment]
same problem here, as of november

**Comment by fguillen** [comment]
Same here: 

```
> yarn build
yarn run v1.22.19
warning package.json: No license field
$ parcel build
error Command failed with signal "SIGSEGV".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I am using parcel  2.11.0

**Comment by fguillen** [comment]
It is still happening in v2.12.0 :/

**Comment by fguillen** [comment]
Don't know if is not related, but moving to a parent directory and coming back to the project dir and the command worked :/

**Comment by 0x1af2aec8f957** [comment]
The problem still exists.

The following information may be useful: 
```bash
node(42005,0x16fadf000) malloc: Incorrect checksum for freed object 0x13c0dfa00: probably modified after being freed.
Corrupt value: 0x3361636366393331
node(42005,0x16fadf000) malloc: *** set a breakpoint in malloc_error_break to debug
error Command failed with exit code 1.
```

This problem seems to be the same: https://github.com/parcel-bundler/parcel/issues/9926 .
