### ISSUE TITLE
Doing less work in dev

### ISSUE THREAD

**Issue by jamiebuilds** [parcel-bundler/parcel#1345]
# 💬 RFC

I'm wondering if there's more work that we can carve out of Parcel while running in dev mode by assuming they are running in the most modern browsers.

- we can stop compiling node_modules using Babel
- we can skip any transforms that only exist for older browsers (Babel, autoprefixer, etc)

## 🔦 Context

Most of the time we're compiling things unnecessarily and it slows dev loops down

**Comment by DeMoorJasper** [comment]
I think this would be safe to do as long as we add a cli option to have the ability to re-enable it to debug bugs in IE

**Comment by jamiebuilds** [comment]
We do when you provide it, but dev mode could still do less work

**Comment by mohsen1** [comment]
Assuming browser is not safe. I am still dealing with iOS 7 Safari in my day job :( 

Dev server can sniff browser UA header to decide how to compile. It doesn't have to be too fancy, just knowing browser name/version is enough. I'm sure there are nice packages out there doing this.

**Comment by budarin** [comment]
It should be under a flag.
What if I want to develop under one of those older browser or want to have a look?

**Comment by mischnic** [comment]
I think this is already done in Parcel 2?

**Comment by Jogai** [comment]
I think this is a bad idea. I just had a bug because of this (nightly 221). Jquery worked fine during dev, but failed on build. You don't want your output to be that different. Build should do basically the same as dev, but in an optimized fashion.
