### ISSUE TITLE
Failing to resolve dependencies in simple project

### ISSUE THREAD

**Issue by battlesnake** [parcel-bundler/parcel#1347]
# 🐛 bug report

(TODO)

## 🎛 Configuration (.babelrc, package.json, cli command)

Files in test case:
```
$ find -type f
./package-lock.json
./package.json
./src/test/test_js.pug
./src/test/test_css.pug
./src/test/test.pug
./src/test/test.js
./src/test/test.css
```

package.json:
```
{
  "name": "basic-parcel-test",
  "version": "0.0.1",
  "devDependencies": {
    "parcel": "^1.8.1",
    "parcel-bundler": "^1.8.1",
    "parcel-plugin-pug": "^0.3.1",
    "pug": "^2.0.3"
  },
  "scripts": {
    "build": "./node_modules/.bin/parcel build src/*/*.pug --no-cache"
  },
  "author": "Mark K Cowan"
}
```

Files in src/test:
```
$ ls -lS src/test/
total 12
-rw-r--r-- 1 mark mark 221 May 11 17:19 test_css.pug
-rw-r--r-- 1 mark mark 203 May 11 17:19 test_js.pug
-rw-r--r-- 1 mark mark 177 May 11 17:18 test.pug
-rw-r--r-- 1 mark mark   0 May 11 17:18 test.css
-rw-r--r-- 1 mark mark   0 May 11 17:18 test.js
```

Contents of non-empty files:
```
$ tail -n 100 src/test/*.pug
==> src/test/test_css.pug <==
doctype html
html(lang='en')
        head
                meta(charset='utf-8')
                meta(name='viewport', content='width=device-width, initial-scale=1, shrink-to-fit=no')
                title Test
                link(rel='stylesheet', href='./test.css')
        body
                h1 Test

==> src/test/test_js.pug <==
doctype html
html(lang='en')
        head
                meta(charset='utf-8')
                meta(name='viewport', content='width=device-width, initial-scale=1, shrink-to-fit=no')
                title Test
        body
                h1 Test
                script(src='./test.js')

==> src/test/test.pug <==
doctype html
html(lang='en')
        head
                meta(charset='utf-8')
                meta(name='viewport', content='width=device-width, initial-scale=1, shrink-to-fit=no')
                title Test
        body
                h1 Test
```

## 🤔 Expected Behavior

Before any test:

```
npm i
```

[PASS] For the simplest test (test.pug):
```
$ parcel build src/test/test.pug
✨  Built in 2.90s.

dist/test.html    204 B    2.51s
```

[FAIL] For the others:
```
$ parcel build src/test/test_js.pug
🚨  /tmp/x/src/test/test_js.pug: Cannot resolve dependency './../../../../d12f3f6bae4ddcbf89548a243d672ccc.js' at '/d12f3f6bae4ddcbf89548a243d672ccc.js'
    at Resolver.resolve (/home/mark/.npm-global/lib/node_modules/parcel-bundler/src/Resolver.js:70:17)

$ parcel build src/test/test_css.pug
🚨  /tmp/x/src/test/test_css.pug: Cannot resolve dependency './../../../../f69ac52462a6cbe9c66acf15af4cd734.css' at '/f69ac52462a6cbe9c66acf15af4cd734.css'
    at Resolver.resolve (/home/mark/.npm-global/lib/node_modules/parcel-bundler/src/Resolver.js:70:17)
```

## 😯 Current Behavior

I receive the output provided in the previous section.

The first test (no references) passes, so I know the pug → html → file pipeline is working.

The other tests (one referencing CSS and the other JS) both fail.

Originally, I was setting up a Pug+TypeScript+Sass project.  I reduced it to Pug+JS+CSS in case TS/SASS was the issue.  I'd initially been trying to get Webpack configured for this, but decided to try Parcel after spending several hours fighting Webpack to no avail.

## 💁 Possible Solution

I wish.

## 🔦 Context

I was trying to set up a basic project with Parcel, having failed to with Webpack.  In the past, I'd use Gulp or Make depending on the project but Webpack and Parcel are far more feature-rich.

## 💻 Code Sample

https://github.com/battlesnake/parcel-bug-1

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | v10.0.0
| npm/Yarn         | 6.0.1
| Operating System | Arch Linux x64, kernel 4.14.32

**Comment by DeMoorJasper** [comment]
Pug support should be inside the parcel core, could you please utilise this instead of the plugin?
This seems like a plugin issue though.

**Comment by battlesnake** [comment]
You're right, it works now.  I guess the tutorials I'd seen were quite outdated.
