### ISSUE TITLE
Current `basedir` setting for pug seems redundant, and makes templating hard

### ISSUE THREAD

**Issue by battlesnake** [parcel-bundler/parcel#1352]
Some might consider this to be a bug, but it doesn't violate documented behaviour so I'll file as a feature request instead.

# 🙋 feature request

The current `basedir` setting for rendering Pug ([here](https://github.com/parcel-bundler/parcel/blob/e7df99decb2484d08b4f613ec6dc2ebe4bf9e969/src/assets/PugAsset.js#L19)) is set to the directory containing the file being rendered.

If I'm interpreting the pug [docs](https://pugjs.org/language/includes.html) correctly, then this is somewhat redundant:

> If the path is absolute (e.g., include /root.pug), it is resolved by prepending options.basedir. Otherwise, paths are resolved relative to the current file being compiled.

This makes it hard to reference assets from templates, if the concrete `pug` files which extend those templates exist in different levels of the directory hierarchy, for example:

```
/src/templates/master.pug
/src/templates/product.pug [extends master]

/src/about/index.pug [extends master]
/src/about/... (assets specific for this page)

/src/contact/index.pug [extends master]
/src/contact/... (assets specific for page)
```

All fine at this point.

```
/src/product/potato/index.pug [extends product]

/src/product/tomato/index.pug [extends product]
```

Rendering these files fails if they extend master.pug (either directly or via a sub-template), as master.pug's assets are resolved relative to these files, and even if using absolute paths in master.pug, the paths are still resolved relative to the concrete file since it's path is supplied to pug for `basedir`

## 🤔 Expected Behavior

I'd expect that `basedir` would be configurable via some optional config file e.g. `.pugrc.js`, and that it would fall back to a sane default (e.g. project root path).  Also that either way, every template has the same `basedir` supplied to it, so that Pug's absolute paths can be useful.

## 😯 Current Behavior

Currently, `basedir` is set to the directory containing the `pug` file being rendered.
[At least if I'm interpreting this line correctly anyway.](https://github.com/parcel-bundler/parcel/blob/e7df99decb2484d08b4f613ec6dc2ebe4bf9e969/src/assets/PugAsset.js#L19)

While this doesn't cause anything that I'd consider a "bug", it does make absolute paths quite useless and enforces restrictions on directory structuring for pug pages and templates.

## 💁 Possible Solution

Somewhat dirty suggestion to convey the idea:

In [PugAsset.js](https://github.com/parcel-bundler/parcel/blob/e7df99decb2484d08b4f613ec6dc2ebe4bf9e969/src/assets/PugAsset.js#L19) around line 19, change

```
basedir: path.dirname(this.name),
```

to

```
basedir: path.resolve(config.basedir || ''),
```

While this is a breaking change to anyone currently using absolute paths in their `pug` files, I'd suspect that (nearly-)nobody is affected since (as far as I can tell) the current `basedir` causes absolute paths to be totally redundant and to behave the exact same way as relative paths.

## 🔦 Context

I'm trying to build pages where the template includes a corporate logo in the top navbar.

The absolute path that I'd need to specify in the template depends on the directory level of the page which ultimately invoked the template, which means all pages must be at the same level in the directory hierarchy.

## 💻 Examples

I'm happy to provide an example to trigger the problem if this isn't already clear enough, and I'll provide a PR if we agree on a solution.

**Comment by battlesnake** [comment]
My proposed solution won't work.

Something, somewhere is trying to resolve a Pug absolute path relative to the root of the filesystem, resulting in `processed.dependencies` (around Bundler.js:[520-530]) containing paths such as `./../../../../../../../src/logo.svg`.

**Comment by wessamzaghloul** [comment]
Any solutions or workarounds regarding this matter ??

**Comment by battlesnake** [comment]
> Any solutions or workarounds regarding this matter ??

Nope.  "Zero-configuration" builders are really just "One-configuration" builders where that config is fixed - like using Webpack but with someone else's config and no easy way to tweak it.  So I went back to webpack.

**Comment by Doogiemuc** [comment]
Stumbled over the same issue that one cannot configure PUG's  basedir when called through Parcel.  :-(    
Totally agree what you said about "zero/one-configuration"  👍

**Comment by rafagomes** [comment]
Do we have any updates on that? I agree that zero configuration, but if we have support for pug, let's make a proper support...because pug with only files on main structure is not that useful. :)

**Comment by designerzen** [comment]
I've had to abandon Parcel due to this issue. I don't think it will ever get resolved!

**Comment by 0xrafasec** [comment]
Me too. Good luck all.
