### ISSUE TITLE
Source maps and minification

### ISSUE THREAD

**Issue by CentaurWarchief** [parcel-bundler/parcel#1353]
# ❔ Question
Do you guys have any thoughts on source maps + minification? They seem to work beautifully when building for production with `--no-minify`.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 9.11.1
| npm/Yarn         | yarn 1.6.0
| Operating System | Mac OS

**Comment by DeMoorJasper** [comment]
They should work with both minification and regular code

**Comment by CentaurWarchief** [comment]
@DeMoorJasper 🤔 

let's say that I have:
```JS
import "babel-polyfill";

function hello() {
  console.log("world");

  setTimeout(() => {
    throw new Error("Hey");
  }, 1000);
}

(async () => {
  hello();
})();
```

and that's my stack trace:
<img width="1440" alt="screen shot 2018-05-12 at 15 04 48" src="https://user-images.githubusercontent.com/967317/39960259-db265320-55f5-11e8-827c-44b0a3c7f6f2.png">

but if I add `--no-minify` (parcel build):
<img width="824" alt="screen shot 2018-05-12 at 15 05 23" src="https://user-images.githubusercontent.com/967317/39960266-ee344e90-55f5-11e8-9a37-663e1a9ab5f3.png">

**Comment by DeMoorJasper** [comment]
That's strange, guess it's not perfect yet

**Comment by bard** [comment]
Same here, fine without minification otherwise error points to wrong line (and file).

**Comment by evanblack** [comment]
Having this issue as well. Doing some digging into the `uglify.js` code today and tomorrow to see why it might be.

**Comment by evanblack** [comment]
I think I found the issue. Line 19 of `src/transforms/uglify.js` should be plural `asset.options.sourceMaps` instead of `asset.options.sourceMap`. This was causing the Uglify source maps from being skipped entirely, so the source maps would have been from the transpiled code.

I'll submit a Pull Request.

**Comment by CentaurWarchief** [comment]
wow—that's true: https://github.com/parcel-bundler/parcel/blob/2f7be14aa9eea3fa9e8ee61591c001937d9757a1/src/assets/JSAsset.js#L139. Thanks for digging in @evanblack! Hope your PR gets merged any soon! 🍻

**Comment by evanblack** [comment]
https://github.com/parcel-bundler/parcel/pull/1468

**Comment by nicolaisueper** [comment]
I saw the submitted PR was merged. Can it be closed?
