### ISSUE TITLE
Cache is not invalidated after babelrc is created

### ISSUE THREAD

**Issue by Codesleuth** [parcel-bundler/parcel#1359]
# 🐛 bug report

Build cache is not updated when `.babelrc` file is created. Specifically for my use-case, `transform-react-jsx.pragma` setting is not respected.

## 🎛 Configuration (.babelrc, package.json, cli command)

_File to add after the initial build_

```json
{
  "plugins": [
    ["transform-react-jsx", { "pragma": "m" }]
  ]
}
```

## 🤔 Expected Behavior

When restarting parcel, specified pragma for JSX files should be used.

## 😯 Current Behavior

The first build will produce a cache which uses the default React pragma setting; after creating the `.babelrc` file, the next build will emit the same error.

>```
>Uncaught ReferenceError: React is not defined
>```

## 💁 Possible Solution

Invalidate the cache after `.babelrc` is added to the project.

## 🔦 Context

I was beginning a new project where I installed parcel and set up an initial JSX component with mithril. As always, I forget to create a `.babelrc` file, and realise this when the first build displays this error. After adding the file and re-launching parcel, I expected the build to be fixed.

See the demo project for full context.

## 💻 Code Sample

Steps and demo assets available here: https://github.com/Codesleuth/parcel-babelrc-rebuild-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1 |
| Node             | 8.11.1 |
| npm/~Yarn~         | 5.8.0 |
| Operating System | Ubuntu 16.04 LTS |

**Comment by DeMoorJasper** [comment]
The cache invalidating currently only triggers on file update not file creation.

I'm a bit confused after reading your issue, did it happen on creation or update?
As the issue states both

**Comment by Codesleuth** [comment]
That explains it then, it was on creation. You can see in the steps of the demo project that the file doesn't exist on first build, is created and rebuilt, and there's no cache change.

I've updated the title, sorry for the confusion there.

**Comment by nicolaisueper** [comment]
I assume the cache should be invalidated too when the `"babel": {}` property was added to the project's `package.json`?

**Comment by DeMoorJasper** [comment]
`package.json` changes should invalidate every file, as every asset has a getPackage property

**Comment by nicolaisueper** [comment]
@DeMoorJasper I'd love to tackle this. Can you give me a hint where to start?
 
I thought about subscribing to every file which gets created inside the project root and check if the filename equals to `.babelrc`

**Comment by devongovett** [comment]
Waiting on this babel PR to be released and then we should be able to implement this: #11906.
