### ISSUE TITLE
Can't resolve aliased dependency relative to node module

### ISSUE THREAD

**Issue by ghost** [parcel-bundler/parcel#1360]
# 🐛 Bug report

I'm trying to alias the `esm` version of Vue.js using the `alias` key in the `package.json` but as a result I get a dependency error.

## 🎛 Configuration (package.json)

```json
...
"alias": {
    "vue": "vue/dist/vue.esm.js"
  }
...
```

## 🤔 Expected Behavior

I wish I could reference a subfolder or file that is relative to the module's path, just like I can do this:
`import module from 'module/sub/folder/file.js'`

## 😯 Current Behavior

```
Server running at http://localhost:1234
×  C:\www\sphynx\src\app.js:1:16: Cannot resolve dependency 'vue'
> 1 | import vue from 'vue'
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 9.5.0
| npm/Yarn         | 5.6.0
| Operating System | Microsoft Windows [Version 10.0.16299.431]

P.S.: I don't know if it's the expected behavior but I have to restart Parcel each time I change any `alias` for it to have effect. It just felt a little weird since everything else on Parcel works automagically and in the beginning I thought the alias feature wasn't working at all, only to realize I had to restart the server.

**Comment by CareyToboo** [comment]
@caimaturo I think it's need alias path resolve just like webpack alias.

**Comment by nsisodiya** [comment]
+1
