### ISSUE TITLE
Discord chatroom

### ISSUE THREAD

**Issue by TheJaredWilcurt** [parcel-bundler/parcel#1361]
Can we get an official Discord chatroom. Vue.js and React have both gone with Discord due to it being able to handle large groups more easily, and retain archives of conversations for free.

**Comment by Hammster** [comment]
Discord is definitely the better platform including support for syntax highlighting in messages. Slack only offers this feature for snippets which are pretty much not what 99% of the Slack user base wants. Also Discord is likely to evolve much more then slack.

Slack on the other hand is already there and a working tool for this project. It covers the needs we currently had as far as i can see from the Chatlogs.

**Comment by devongovett** [comment]
Interested in what people think about https://spectrum.chat as well.

**Comment by DeMoorJasper** [comment]
Switched to https://spectrum.chat/parcel

**Comment by b0o** [comment]
@DeMoorJasper The spectrum.chat room seems to be 404?

**Comment by DeMoorJasper** [comment]
@b0o maybe open up an issue with spectrum, seems to work for me

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by b0o** [comment]
@DeMoorJasper Is the chatroom private or invite only, perhaps? I can load other rooms (e.g. https://spectrum.chat/figma) but not https://spectrum.chat/parcel:

![2018-08-02-08-07-15](https://user-images.githubusercontent.com/21299126/43592783-25bed7d4-962b-11e8-9479-8e9ec0b38e53.png)

**Comment by b0o** [comment]
Actually, I just tried it in Firefox and it works. Odd, I suppose I will open an issue with Spectrum.

**Comment by TheJaredWilcurt** [comment]
I would think that if your goal for Parcel is to become adopted by the major frontend communities, you would want to provide as little friction as possible, by going to where those communities are.

* Vue on Discord: 39,340 offline, 1,558 online
* Vue on Spectrum: 949 (presumably all offline)
* React on Discord: 29,977 offline, 3,103 online
* React on Spectrum: 7,451 (presumably all offline)

Latest comments on Spectrum are from hours or days ago, where as on Discord it's seconds or minutes ago.

**Comment by Hammster** [comment]
I also have a hard time transitioning to Spectrum, one reason may be that parcel is the only project i work with that uses it.  But also because i feel kinda lost in the UI, it feels much more like searching issue then a direct communication tool.

**Comment by tristan-f-r** [comment]
Possibly just use discord with IRC hooks? (Similar to the likes of other servers that don't want to make a trade between open chat services and the availability of discord)
