### ISSUE TITLE
Clear Console BEFORE HMR

### ISSUE THREAD

**Issue by enom-infini** [parcel-bundler/parcel#1365]
# 🐛 bug report

Current `console.clear()` on HMR clears runtime `console.log()`. A lot of my work still relies on runtime logs and the current `console.clear()` placement is preventing me from leveraging HMR.

## 🎛 Configuration (.babelrc, package.json, cli command)

You can install my demo project: https://github.com/enom-infini/parcel-hmr-console

```bash
git clone git@github.com:enom-infini/parcel-hmr-console.git
cd parcel-hmr-console
yarn && yarn dev
```

## 🤔 Expected Behavior

The console should read three lines:

> Console was cleared.
> runtime
> timeout

## 😯 Current Behavior

The console reads only two lines:

> Console was cleared.
> timeout

## 💁 Possible Solution

Move placement of `console.clear()` in [src/builtins/hmr-runtime.js](https://github.com/parcel-bundler/parcel/blob/master/src/builtins/hmr-runtime.js)

## 🔦 Context

Attempting to use Parcel altogether. The console clearing is preventing me from using Parcel ^1.8 due to my current workflow.

## 💻 Code Sample

See my GitHub repo: https://github.com/enom-infini/parcel-hmr-console

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.8
| Node             | 9.7.1
| npm/Yarn         | 1.5.1(Yarn)
| Operating System | Linux / Ubuntu (below)

```
> $ uname -a
Linux vm 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
```

**Comment by obedm503** [comment]
any idea of when this will be released?
