### ISSUE TITLE
Sourcemap recreation causes dev builds to take too long

### ISSUE THREAD

**Issue by RyanSacha** [parcel-bundler/parcel#1367]
My JS file is really not that complicated:

```
// app.js
const axios = require('axios')
const _ = require('lodash')

// my code here
```

Whenever i change something in app.js parcel takes a long time (4s to 20s on a fast machine) rebuilding axios, lodash even though it's supposed to be fast and optimized to cache modules.

Importing more modules exponensially slows down the rebuild (i'm referring to subsequent rebuilds, not the initial one).

Any ideas what would cause this?

I've tried `parcel watch index.html` and `parcel index.html`

**Comment by RyanSacha** [comment]
It turned out that sourcemaps caused the vast majority of delay, once disabled it brought the time from 6s to 32ms.

**Comment by ReiMcCl** [comment]
I have found that running `parcel build index.html` performs significantly better than `parcel watch index.html` and `parcel index.html`. Both parcel watch and parcel fail often and take upwards of 10 minutes to complete for my particular project, whereas parcel build completes in seconds.

Unfortunately I cannot share the projects where this is occurring for reference, however I wanted to raise this as, from my understanding, the build still generates a sourcemap.

**Comment by DeMoorJasper** [comment]
@ReiMcCl I’ve noticed this on my builds as well, perhaps it’s related to the watcher because 10min is a lot see #1368

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by goras** [comment]
I've experienced very long build times as well, not sure if it’s related to sourcemaps, but the issues started after upgrading to parcel 1.8.0. So for now im staying on 1.7.1 which works well!

**Comment by DeMoorJasper** [comment]
@goras sourcemaps haven’t changed since 1.7 and they should def nog be slower than build

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ReiMcCl** [comment]
@DeMoorJasper I have tested the change made in #1368 and am now getting 13 second watch times, a significant improvement. Looking forward to seeing that merged in!
