### ISSUE TITLE
[Feature Request] Throw exit code 1 when build error

### ISSUE THREAD

**Issue by rwu823** [parcel-bundler/parcel#137]
🙋 Feature Request

Throw **exit code 1** when build error is helpful in CI environment.

```sh
parcel build entry.js
```

### 🤔 Expected Behavior

Displays error and throw exit code 1.

### 😯 Current Behavior

Builds error but passed.
![image](https://user-images.githubusercontent.com/890063/33766354-123472c4-dc58-11e7-90e7-9c05ae810b8b.png)

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  `1.0.3`
| Node             | `8.9.2`
| npm/Yarn         | yarn `1.3.2`
| Operating System | TravisCI

**Comment by davidnagli** [comment]
That’s a great point! We should definitely do that

**Comment by yeskunall** [comment]
I can take this up when #140 and #121 (finally) land.

**Comment by davidnagli** [comment]
Cool! 

Just out of curiousity... how does #121 have anything to do with this :joy:

**Comment by yeskunall** [comment]
Once that lands, `lint-staged` will run as a precommit hook, prettifying the files, avoiding those unnecessary PRs fixing indentations and what not.
