### ISSUE TITLE
SCSS with Autoprefixer

### ISSUE THREAD

**Issue by lffg** [parcel-bundler/parcel#1376]
# ❔ Question

Hello guys, how can I compile SCSS and then run autoprefixer?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | Latest
| Node             | `8.11.1`
| npm/Yarn         | NPM `5.6.0`
| Operating System | Win 10 x64

**Comment by krisztiankecskes** [comment]
This is my question also. I tried to figure out, but I couldn't. Is there any solution?

**Comment by DeMoorJasper** [comment]
Create a `.postcssrc` file as you normally would for autoprefixer and it should run over it.

**Comment by mischnic** [comment]
Parcel will first compile SCSS to CSS and then run PostCSS with the plugins specified in `.postcssrc`:
```
{
  "plugins": {
    "autoprefixer": {},
  }
}
```

**Comment by DeMoorJasper** [comment]
Closing this as the question has been answered and it has been inactive for a lil while
