### ISSUE TITLE
Better TypeScript support

### ISSUE THREAD

**Issue by mohsen1** [parcel-bundler/parcel#1378]
# 💬 RFC Better TypeScript support 

TypeScript is working out of the box for the most part but there are a few pain points:
 ### Pain points
* [TypeScript module resolution algorithm](https://www.typescriptlang.org/docs/handbook/module-resolution.html) is not implemented in Parcel. #202 This covers these configs:
  * `baseUrl`
  * `paths`
  * `allowSyntheticDefaultImports`
* Compiler errors are not printed in the console #465
  * `parcel-plugin-typescript` adds it but console is not cleared after issue is resolved 

### Improvements
* Automatically create and configure `tsconfig`
  * Once a `ts` or `tsx` file was imported but `tsconfig` is not present, create one
* Automatically install `@types` packages #1161
* Support for Custom Typescript transformers #699

## 🔦 Context
TypeScript is pretty popular and having first class support for it in Parcel will attract a wider range of users. 

## 💻 Examples
I tried cloning [react-parcel-example](https://github.com/jaredpalmer/react-parcel-example) and making repo states that demonstrate those pain points:

1. JSX is not working in default mode (preserve): 
    * https://github.com/mohsen1/react-parcel-example-typescript/tree/90f9f72b2f3fcfcbd5410b097e5c20cc10d8a325
2. `baseUrl` config is not working 
    * https://github.com/mohsen1/react-parcel-example-typescript/tree/3b74951e47d77d7ba79dbd56ef25621d312ca394

**Comment by fathyb** [comment]
Duplicates : 
- module resolution #202
- type checking #465 
- auto install `@types` #1161

---

`parcel-plugin-typescript` implements the TypeScript module resolution (`baseUrl`, `paths`). `allowSyntheticDefaultImports` is not part of the module resolution algorithm, it's used for the module *symbol* resolution by the type-checker. If you are using TypeScript 2.8+ you should be able to import synthetic defaults.

The plugin is originally a spin-off of a PR implementing type-checking, but the feature wasn't well received by the community, so I guess it's better to leave the choice to the end user.

The TypeScript plugin will probably be integrated as a core plugin once we settle on a plugin RFC though (aka `2.0`). The long term goal would be to integrate TypeScript just like we do with Babel, and let developers use a pure TypeScript toolchain without Babel.

**Comment by szagi3891** [comment]
@DeMoorJasper - When could this happen?

**Comment by uoziod** [comment]
+1

**Comment by DeMoorJasper** [comment]
Please use the +1 button instead of adding comments saying +1

**Comment by mihailik** [comment]
<a href="https://github.com/parcel-bundler/parcel/issues/1627">1627 Support <script src="tsconfig.json"></script> as asset type</a> might be a way to solve many of those issues.

Rather than stretch `parcel`'s file-based current TS handling, allow a way to fall back into TS standard way, using `tsconfig.json` directly.

That way all the resolution, errors, special modes will reside in TS compiler, and act in familiar TS manner.

**Comment by QuantumInformation** [comment]
This best loaders use native typescript as much as possible.

**Comment by inad9300** [comment]
Wow, this seems to have been completely abandoned. Despite TypeScript's increase in popularity. Still no type checks.

**Comment by mischnic** [comment]
We are working on this for Parcel 2.

**Comment by tgroutars** [comment]
@mischnic Awesome, is there an issue we can follow for updates on parcel 2?

**Comment by mihailik** [comment]
@tgroutars <a href="https://github.com/parcel-bundler/parcel/issues/1378#ref-pullrequest-408544424"> comment above</a> refers to <a href="https://github.com/parcel-bundler/parcel/pull/2627">Parcel 2/TypeScript transformer</a>:

![Screenshot from 2019-06-08 21-21-24](https://user-images.githubusercontent.com/4041967/59151975-9b00d900-8a33-11e9-9382-1e94741771e8.png)

Mind you, that PR is old and not handling type checks (yet?)

**Comment by mischnic** [comment]
The current PR is #3083 (but doesn't have type checking either)

**Comment by DeMoorJasper** [comment]
Working on it, see https://github.com/parcel-bundler/parcel/pull/3142

**Comment by nexussays** [comment]
I posted a workaround for type errors in the console in a comment in #465 that others might find useful: https://github.com/parcel-bundler/parcel/issues/465#issuecomment-512720643

> I'm cross-posting because there are several issues on this topic and I'm not actually sure where I arrived from google; so this will hopefully save everyone else some time going through GitHub issues.

**Comment by bbugh** [comment]
I created an issue for Parcel 2 about the incomplete TypeScript support, and the official response by @DeMoorJasper is that Parcel 2 will effectively behave the same as Parcel 1 by stripping out TypeScript and treating it as JavaScript with babel. TypeScript code will not be compiled, so there will be no type checking or compiler errors. If you have a desire for real TypeScript support in Parcel 2, please comment in the new RFC: https://github.com/parcel-bundler/parcel/issues/4022

**Comment by devongovett** [comment]
Going to close this. Parcel 2 now does support loading setting from tsconfig.json and respects baseUrl, paths, etc. Type checking is not supported, but could be implemented in a third party plugin.
