### ISSUE TITLE
Change logs?

### ISSUE THREAD

**Issue by bickmista** [parcel-bundler/parcel#138]
They are a chore but super useful, could we get these?

**Comment by davidnagli** [comment]
@devongovett Can we start doing this? Since your pretty much the “main guy” reviewing PRs and committing changes I think this pretty much falls into your hands. Up to you, but I agree that this would be a super useful practice.

**Comment by DanielRuf** [comment]
https://github.com/lalitkapoor/github-changes or similar is probably useful.

**Comment by Hobbit71** [comment]
Would adding this in as part of the `prepublish` script work. If so, happy to do it. Assume you want the file commited auto-magically as part of the script?

**Comment by devongovett** [comment]
Is the value of a changelog purely to list the commits that occurred between two versions or to actually describe in more detail what changed and how users need to upgrade? If the former, that is easily accomplishable by using Github's compare feature, e.g. here is the diff between v1.1.0 and v1.2.0: https://github.com/parcel-bundler/parcel/compare/v1.1.0...v1.2.0

I think the value of changelogs is more about the latter - providing a summary to users about what changed and how it affects them. If they want granular detail, then the commits are there for them. If someone wants to take this on, it would be greatly appreciated!

**Comment by tinchoz49** [comment]
>  I think the value of changelogs is more about the latter - providing a summary to users about what changed and how it affects them. 

Hi @devongovett, I agree with you and I think [keepachangelog](http://keepachangelog.com) follows that path. 

We made a CLI to work with the keepachangelog format, maybe can be helpful: https://github.com/geut/chan

**Comment by brandon93s** [comment]
The changelog is now maintained here: https://github.com/parcel-bundler/parcel/blob/master/changelog.md

**Comment by bickmista** [comment]
Thanks guys, you even back dated it which is fantastic!
