### ISSUE TITLE
Does this tool support multiple entries and feature like `webpack.optimize.CommonsChunkPlugin`

### ISSUE THREAD

**Issue by plantain-00** [parcel-bundler/parcel#139]
**Choose one:** 🙋 feature request?

### 🎛 Configuration (.babelrc, package.json, cli command)

```html
// index.html
<script src="vendor.js"></script>
<script src="index.js"></script>
```

```js
// index.js
import React from "react";

// other code
```

```js
// vendor.js
import "react";
import "react-dom";
```

### 🤔 Expected Behavior

https://webpack.github.io/docs/list-of-plugins.html#commonschunkplugin

### 🔦 Context

My webpack config uses this feature, if this tool support this feature, I can try this tool rather than webpack.

**Comment by davidnagli** [comment]
This sounds pretty cool.

I’m trying to understand what commonschunkplugin does, but I don’t really understand the point. Do you mind explaining it a bit?

**Comment by bickmista** [comment]
From my understanding the `commonschunkplugin` allows you to split out frequently used libraries into its own bundle so that they all get loaded at once and so you can have smaller application bundles.

**Comment by plantain-00** [comment]
`commonschunkplugin` works with code splitting, there is also a link about its point: https://webpack.js.org/guides/code-splitting/#prevent-duplication

**Comment by sudhakar** [comment]
If a module is already imported in vendor.js, it doesn't appear to get added in index.js bundle. Atleast from the bundle size, that what it appears to be when I tested.

Can anyone confirm?

**Comment by plantain-00** [comment]
@sudhakar That's right.
Usually, `index.js` changes frequently, `vendor.js` doesn't change, so bundled `vendor.js`'s hash doesn't change too(eg, 500KB), so a browser will not load bundled `vendor.js` again when I just change `index.js`, it just reload bundled `index.js`(eg, 200KB).
Without `commonschunkplugin`, a browser will always reload whole js file(eg,700KB) even I just make a small change.

**Comment by sudhakar** [comment]
@plantain-00 I have used `commonschunkplugin`. Atleast from the bundle size it generated, looks like parcel already does it by default. AFAIK, no config or plugin is required to make it work like `commonschunkplugin`

So I would say give it a try :)

**Comment by sudhakar** [comment]
Here's a excerpt from the docs which confirms that

> If an asset is required in more than one bundle, it is hoisted up to the nearest common ancestor in the bundle tree so it is not included more than once.

**Comment by plantain-00** [comment]
It seems it supports `commonschunkplugin` for development mode, production mode failed because of  #8

**Comment by TimNZ** [comment]
Any intention to support similar functionality as CommonsChunkPlugin?
Very helpful for reducing download size in deployment of updates.

https://survivejs.com/webpack/building/bundle-splitting/

**Comment by devongovett** [comment]
This already happens automatically. If you use a dynamic import to do code splitting, the common dependencies are automatically hoisted into the common bundle. See https://parceljs.org/code_splitting.html.

**Comment by TimNZ** [comment]
I read through that.  

I can test this, but want to be clear on the intended/supported use case.

In the simplest case - If I want all my node_modules bundled into a common .js file, I could make a dummy .JS file that imports them e.g. React, use dynamic import on the dummy, and that will result in a split bundles?

In theory the common bundle JS should never change if I'm only changing my app src and don't import any more common modules, or don't update any packages.

I think I prefer the more explicit multiple entry point support with Webpack as the intent it is clear.

**Comment by TimNZ** [comment]
This ties in with my query in another issue for your website repo I commented on yesterday re cache busting and deployment strategies that Parcel could perhaps make easier with zero config

https://github.com/parcel-bundler/website/issues/59#issuecomment-361830177

**Comment by sant123** [comment]
We can accomplish chunks vendor splitting doing this:

index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Testing parcel</title>
    <link rel="stylesheet" href="../node_modules/bulma/css/bulma.css">
</head>
<body>
    <div id="root"></div>
    <script src="./js/main.js"></script>
</body>
</html>
```

main.js

```javascript
import "./vendor";

import React from "react";
import ReactDOM from "react-dom";

import HomeComponent from "./home/home.component";

ReactDOM.render(<HomeComponent />, document.getElementById("root"));
```

vendor.js
```javascript
// Create additional bundles for these libraries.
import("react");
import("react-dom");
```

home.component.jsx
``` jsx
import React from "react";

export default class HomeComponent extends React.Component {
  render() {
      return (
        <div>Hello world :)</div>
      );
  }
}
```

The result...

![image](https://user-images.githubusercontent.com/7959437/35932625-24b741e6-0c06-11e8-9d73-5871c11d4bbd.png)

![image](https://user-images.githubusercontent.com/7959437/35932704-5c6be542-0c06-11e8-8f2e-a54e636d6a2f.png)

**Comment by chris-kobrzak** [comment]
Really nice post, @sant123!

Just to add my penny, if anyone wants to try this solution, please make sure you use the rounded brackets syntax in the `import` statements you'd like to split out.

So e.g.:

```javascript
import('react')
```

not

```javascript
import 'react'
```

**Comment by CraigHarley** [comment]
Is it possible to name these chunks?

**Comment by sant123** [comment]
Do you really need it? The name is according with the package you're importing.

**Comment by frednomoon** [comment]
@sant123 i'm having some problems using the solution you are advocating above. I am successfully splitting React & ReactDOM from my main bundle but they are not being added to the `index.html`.
As a result this method essentially "lazy loads" react & react-dom meaning that their download is not initiated until the main bundle has finished downloading as you can see in these screenshots:
<img width="558" alt="Screenshot 2019-04-24 15 03 39" src="https://user-images.githubusercontent.com/23635508/56666121-3e27aa00-66a3-11e9-9a5b-ac64f164a4d8.png">
<img width="536" alt="Screenshot 2019-04-24 15 03 28" src="https://user-images.githubusercontent.com/23635508/56666122-3e27aa00-66a3-11e9-92e1-71ef887c4f1c.png">

Do you have any idea where I might be going wrong here?
