### ISSUE TITLE
Option to use JSON entry point

### ISSUE THREAD

**Issue by burlesona** [parcel-bundler/parcel#1392]
# 🙋 feature request

When working in an environment with Dynamic Templates (example: https://github.com/parcel-bundler/parcel/issues/1371), there are some extra hoops to jump through to get Parcel to work.

One great solution to this would be the ability to define a json entry file, and have that same file output (with the transformed filenames) to dist.

## 🤔 Expected Behavior

Suppose I am at my project root and I am working with dynamic templates and I need some number of "root" assets to get picked up by Parcel and compiled.

I create a file, `entries.json` (or some name you all like better :)), which looks like this:

```
{
  indexJS: './javascripts/index.js',
  indexCSS: './stylesheets/index.scss'
}
```

I then run parcel with that as my entry point:

`parcel entries.json`

Parcel reads this file the same way it would read `index.html` or any other entry point, recognizing the object values as paths and compiling those assets. Parcel then outputs the same JSON with the transformed filenames, eg.

```
{
  indexJS: './dist/index-12345abcde.js',
  indexCSS: './dist/index-12345abcde.scss'
}
```
Now my server that renders the templates can simply parse this json file to know what the bundle filenames are, eg in my application code I could do something like this:

```
<link rel="stylesheet" href={entries.indexCSS} />
```

## 😯 Current Behavior

Well, none of that appears to be possible currently.

## 💁 Possible Solution

The workaround I figured out on my own was to make a shim index.html file that has only my root level assets linked on it, I put IDs on the html elements that did the linking, and I then wrote a very simple scraper that reads the compiled index.html file out and gets the transformed path out of the elements and gives them keys based on the element IDs.

This works, but it's clunky.

The solution I found today, using this plugin (https://github.com/mugi-uno/parcel-plugin-bundle-manifest) to get the parcel manifest exposed, is cleaner.

Nevertheless it would be very nice to be able to define the entry files I care about as a json file rather than needing a shim HTML file.

I believe the above has all the 🔦 Context and  💻 Examples to be clear so I'll leave it at that.

Parcel is amazing! Thank you to everyone who contributes!

**Comment by dobesv** [comment]
I moved this into a new package:

https://www.npmjs.com/package/parcel-plugin-assets-list

https://github.com/dobesv/parcel-plugin-assets-list

Please check it out and let me know what you think of it.

**Comment by burlesona** [comment]
@dobesv that looks great, pretty much just what I wanted! The only question I have, is there a way to make a cli flag in a parcel plugin? If so it would be kind of nice to specify which sort of asset file I want generated (probably json in my case) and then not generate the other two kinds unnecessarily. However that's a very minor aesthetic thing, not very important.

**Comment by dobesv** [comment]
No CLI flag, but either an environment variable, a flag in the input file
itself, a different extension, or a settings file all are possible.

Probably a different file extension would have been great.  I had wished to
use ".manifest.json" or something like that but parcel only uses the final
extension to choose the asset type.

Maybe it could recognize a filename like bla.json.assets and translate that
to bla.json somehow. Likely I could convince parcel to do that, but I
haven't looked.

Also wish I could think of a better file extension overall besides
"assets".  Suggestions very welcome.

**Comment by burlesona** [comment]
You could call it `assets.manifest` and therefore 'manifest' is the type. 🤷‍♂️ 

I think .assets is fine too though, it makes sense.

**Comment by dobesv** [comment]
I had considered ".manifest" but a bit of googling made me think this file
extension might be in use for other things already.

**Comment by dobesv** [comment]
I think I'll change it to ".urls" because I find I'm importing it in my
just files like:

import template urls from '../templates/templates.assets';

Putting urls as the suffix would be a better match.

**Comment by DeMoorJasper** [comment]
Multiple entrypoints has been merged, this should add the ability to have something similar to `entries.json` but in the commandline
