### ISSUE TITLE
Support ng-include

### ISSUE THREAD

**Issue by dobesv** [parcel-bundler/parcel#1399]
# 🙋 feature request

When I use `<ng-include src="..."/>` I have to manually resolve those paths using my own workarounds.  It would be nice if those paths were resolved by parcel like `<a href=...>` is.

## 💁 Possible Solution

Perhaps the HTMLAsset could be a bit configurable, let me modify the configuration of which attributes it processes.  Then an angular-specific feature wouldn't be needed and if there are other attributes people want to process, they can without modifying the code.

A possible workaround would be for me to make a plugin with a forked HTMLAsset.

**Comment by devongovett** [comment]
Closing since this is for Parcel 1.
