### ISSUE TITLE
Suggestions for improving documentation

### ISSUE THREAD

**Issue by assertchris** [parcel-bundler/parcel#14]
- How do I get this SCSS file working?
- How can I watch a file in one place and generate a file in another?
- Is there a version manifest? Does this support versioning of any kind?
- Can I watch multiple asset entrypoints at once (like CSS, JS, HTML)?

---

As discussed [on reddit](https://www.reddit.com/r/javascript/comments/7hr6ta/parcel_blazing_fast_zero_configuration_web/dqtdrqg/)...

**Comment by devongovett** [comment]
thanks. It is on my list to improve the docs specifically for compile-to-CSS langs. Basically you need to install `node-sass` in your project for it to work correctly. Sorry about that.

Please feel free to make other suggestions or directly make PRs against https://github.com/parcel-bundler/website.

**Comment by assertchris** [comment]
I did install that. I also installed postcss and postcss-scss and autoprefix; and set up a .postcssrc file. All of this got me to the "[object Object] is not..." error.

**Comment by morajabi** [comment]
> It is on my list 

I'd love to see that list :))

**Comment by bryananthonylewis** [comment]
I'd agree with this. The getting started guide was great and straight forward. I got a project up super quick. However, I came to a halt right when I tried to make a SASS file and couldn't find any documentation on how to process that file.

**Comment by devongovett** [comment]
Going to close this one. Please open an issue on https://github.com/parcel-bundler/website if you have more suggestions.
