### ISSUE TITLE
Option to remove `.html` in <a href=

### ISSUE THREAD

**Issue by buckle2000** [parcel-bundler/parcel#1400]
# 🙋 feature request

Add an option to remove `.html` in links in post-transform stage of `HtmlAsset`.

## 🤔 Expected Behavior

Disabled
`<a href="/about.html">` 
Enabled
`<a href="/about">`

## 💁 Possible Solution
```js
const posthtml = require('posthtml')
const shorten = require('posthtml-shorten');
const shortener = {
    async process(url) {
        if (url.indexOf('//') === -1) {
            return url.replace('.html', '')
        }
        return url
    }
};
const shortener_options = {
    shortener: shortener, // Must contain a `shorten` function
    tag: ['a'], // Allowed tags for URL shortening
    attribute: ['href', 'src'], // Attributes to replace on the elements
};
posthtml([shorten(shortener_options)])
// add this in  `transform` function of `HtmlAsset`.
```

## 🔦 Context

I just don't want to see `.html` in the URL.

## 💻 Examples

Any website with two pages should work.

**Comment by devongovett** [comment]
I don't think we can support this. Since Parcel writes files to the filesystem, we need to add a file extension. You could easily solve this yourself using nginx or another server to hide the `.html` extension from urls.
