### ISSUE TITLE
TypeError: Cannot read property 'from' of undefined

### ISSUE THREAD

**Issue by sebastiencs** [parcel-bundler/parcel#1404]
# 🐛 bug report

I'm making an electron app. When my application start, I have this error.
I got it on production build, but I don't have any error on dev builds

![error](https://user-images.githubusercontent.com/5273820/40333421-b31463d0-5d58-11e8-9c53-d3e9b743e690.jpg)

## 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc
```js
{
  "presets": [
    "react",
    "stage-0",
    ["env", {
      "targets": {
        "electron": "2.0"
      }
    }]
  ],
  "plugins": [
    "add-module-exports",
    "react-hot-loader/babel",
    "transform-class-properties",
    "transform-es2015-classes"
  ]
}
```

tsconfig.json
```js
{
  "compilerOptions": {
    "outDir": "./tsdist/",
    "target": "esnext",
    "jsx": "preserve",
    "sourceMap": true,
    "noImplicitAny": true,
    "allowSyntheticDefaultImports": true
  },
  "include": [
    "app/renderer/**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

command:
```
$ parcel build app/main/main.js -d ./app/build --target=electron,
$ parcel build app/renderer/index.html --public-url ./ -d app/renderer/.parcel/production
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 9.11.1
| Yarn         | 1.6.0

Let me know if you need more informations, thanks

**Comment by helloforrestworld** [comment]
i also have  this problem, my project is running good dev , but after build , some object is turn in undefined, and throw a error like this

**Comment by DeMoorJasper** [comment]
Probably some minification that causes this.

A test repo would be helpfull

**Comment by helloforrestworld** [comment]
`
import Dplayer from 'dplayer'
console.log(Dplayer )
`
without a console , after build ,  will throw error Dplayer is undefined........
with a console , all will be good!!!!
why????????
it doesn't make sense!! wired

**Comment by DeMoorJasper** [comment]
@helloforrestworld if that’s the only code in that file than it maken sense as it’s just an unused import

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by helloforrestworld** [comment]
@DeMoorJasper no , i have use it ,   but after build , it will throw error like the guy asking, and i add a console test it , it turn good ! it is wired

**Comment by helloforrestworld** [comment]
@DeMoorJasper  it run good in dev
