### ISSUE TITLE
.uglifyrc config didn't take effect all modules

### ISSUE THREAD

**Issue by zhiyan** [parcel-bundler/parcel#1405]
# 🐛 bug report

custom .uglifyrc config didn't  take affect the code as node_modules dependencies. For example the parcel wrapper code.

## 🎛 Configuration (.uglifyrc)

```js
{
  "ie8": true
}
```

## 🤔 Expected Behavior

uglify custom config should come into force all code.

## 😯 Current Behavior

the config only take effect on the code outside node_modules

## 💁 Possible Solution

I think .uglifyrc is not a standard config file, and it should take effect all the code finally.Otherwise it will be no meaning.

## 💻 Code Sample
node_modues/test/test.js:
```js
window.catch =1
```
src/index.js:
```js
import 'test'
window.catch = 2
```
after build:
```js
...
window.catch = 1
...
window["catch"]=2
...
```
the `catch` keyword did not be handled the right way, because the custom uglify config did not take effect on the modules  as a npm dependencies

**Comment by subhero24** [comment]
I looked into this and the config file for each asset is resolved separately. When the resolver looks into a node module, it stops resolving at the `node_modules` directory. So for assets inside a node module, no config file is found, and no options are used for the terser process. Shouldn't it use the config file it has already loaded from the project as the default options? (like it does for babel options).
