### ISSUE TITLE
npm 6 reporting dependency vulnerabilities 

### ISSUE THREAD

**Issue by stevengill** [parcel-bundler/parcel#1406]
# 🐛 bug report

`npm install parcel-bundler` with `npm@6`. It is reporting 2 vulnerabilites. 

report from `npm audit`

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ macaddress                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ parcel-bundler [dev]                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ parcel-bundler > cssnano > postcss-filter-plugins > uniqid > │
│               │ macaddress                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/654                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ macaddress                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ parcel-bundler [dev]                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ parcel-bundler > htmlnano > cssnano > postcss-filter-plugins │
│               │ > uniqid > macaddress                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/654                       │
└───────────────┴──────────────────────────────────────────────────────────────┘

[!] 2 vulnerabilities found - Packages audited: 28783 (28783 dev, 565 optional)
    Severity: 2 Critical

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.8.1
| Node             | 8.11.1
| npm/Yarn         | npm@6.0.1
| Operating System | 10.13.4

**Comment by DeMoorJasper** [comment]
Not much we can do about it
<img width="917" alt="screen shot 2018-05-22 at 09 48 48" src="https://user-images.githubusercontent.com/2175521/40348952-6672a0da-5da5-11e8-8cf7-4175c8cf0360.png">

And all the node-sass vulnerabilities need updating from node-sass's dependencies, which hasn't happened yet.

**Comment by capaj** [comment]
actually the problem is in `uniqid` which relies on a MAC adress for getting more randomness. They already fixed it in https://github.com/postcss/postcss-filter-plugins/commit/ea8453f093633a22a481efa9136785e905c31084

so all cssnano needs to do is update their version of `postcss-filter-plugins`

**Comment by DeMoorJasper** [comment]
Seems to be resolved in latest version
