### ISSUE TITLE
🐛 @webcomponents Cannot resolve dependency 'vertx'

### ISSUE THREAD

**Issue by sbesh91** [parcel-bundler/parcel#141]
**Choose one:** is this a 🐛 bug report or 🙋 feature request? 🐛

I've been giving parcel a go as a replacement for my webpack config.
It's running into the same issue I had with webpack where it had an issue with the webcomponents polyfill
### 🎛 Configuration (webpackconfig)
This is the line that would fix a webpack config
```js
{
    new webpack.IgnorePlugin(/vertx/)
}
```

### 🤔 Expected Behavior
The expectation is for a way to ignore vertx

### 😯 Current Behavior
@webcomponents/webcomponentsjs/webcomponents-lite.js:27:271: Cannot resolve dependency 'vertx'
That is the error message I get upon running a build

### 🔦 Context
I'd like to replace my webpack config with parcel if at all possible.  This is the error that is currently holding me back because my component model heavily relies on web components

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  1.0.3
| Node             | 6.12.0
| npm/Yarn         | 3.10.10
| Operating System | ubuntu 17.10

**Comment by davidnagli** [comment]
So put more generally, you're asking for a way to ignore certain file name patterns in Parcel?

**Comment by sbesh91** [comment]
Yeah I think that sounds right to me.

**Comment by davidnagli** [comment]
I think we need to implement a CLI option called `--ignore`

It should work like this (once implemented):
```
parcel --ignore *.vertx
```

Do you guys think we should use wildcards for the ignore, or regex?

```
parcel --ignore /\.vertex/
```

I guess we could also support both...

**Comment by DeMoorJasper** [comment]
It would probably be a good idea to allow multiple entries, for example if anyone would use a minified library (for example jQuery) and not want it to get included in the bundle.
This is kinda already included in babelrc though, don't know if it is being used in the source codes though
```json
{
  "ignore": [
    "foo.js",
    "bar/**/*.js"
  ]
}
```

**Comment by devongovett** [comment]
why is `vertx` required if it isn't a dependency?

**Comment by sbesh91** [comment]
The original answer I got to this problem for my webpack solution came here.  
https://github.com/webcomponents/webcomponentsjs/issues/794
I can't say vertx is a dependency of my app.

**Comment by chrismbeckett** [comment]
Beyond this one example, I think there are going to be other packages (polyfills, etc.), that I want ignored by a package bundler. I think this project needs some sort of strategy for how to include/exclude specific links in the index.html file. Since you want to avoid configuration, maybe a special attribute on the link? There is a lot of weirdness in NPM modules, and I am concerned you will have a never-ending string of these types of bugs when the simplest idea is to just raw copy them to dist and continue to link them directly.

**Comment by davidnagli** [comment]
Ya, I think we should move this into a separate more general issue for adding an ignore flag.

**Comment by DeMoorJasper** [comment]
This has been fixed by `@webcomponents`
