### ISSUE TITLE
File to import not found or unreadable: @material/elevation/mixins

### ISSUE THREAD

**Issue by thiagovilla** [parcel-bundler/parcel#1416]
# 🐛 bug report

File to import not found or unreadable: @material/elevation/mixins.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "devDependencies": {
    "@material/top-app-bar": "^0.35.2",
    "node-sass": "^4.9.0"
  }
}
```

## 🤔 Expected Behavior

Parcel should be able to load @material mixins in `node_modules/@material`

## 😯 Current Behavior

```shell
PS C:\apps\test> parcel index.html
Server running at http://localhost:1234
×  C:\apps\test\main.scss: File to import not found or unreadable: @material/elevation/mixins.
    at options.error (C:\apps\test\node_modules\node-sass\lib\index.js:291:26)
```

## 💁 Possible Solution

Allow `node-sass` to access `node_modules/@material` folder?

## 🔦 Context

I am trying to implement the [MDC Top App Bar](https://material.io/develop/web/components/top-app-bar/).

This is my `index.html` file:

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>MDC Top App Bar Test</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" media="screen" href="./main.scss" />
  <script src="./main.js"></script>
</head>
<body>
  <header class="mdc-top-app-bar">
    <div class="mdc-top-app-bar__row">
      <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
        <a href="#" class="material-icons mdc-top-app-bar__navigation-icon">menu</a>
        <span class="mdc-top-app-bar__title">Title</span>
      </section>
    </div>
  </header>
</body>
</html>
```

My `main.scss` file:

```scss
@import "@material/top-app-bar/mdc-top-app-bar";
```

And my `main.js` file:

```js
import { MDCTopAppBar } from '@material/top-app-bar/index'

const topAppBar = new MDCTopAppBar(document.querySelector('.mdc-top-app-bar'));
```

## 💻 Code Sample

https://github.com/thiagovilla/portfolio/blob/master/labs/mdc/top-app-bar/index.html

## 🌍 Your Environment

Windows 10
Chrome 66.0.3359.181
node v8.11.1

**Comment by DeMoorJasper** [comment]
What parcel version are you using?

**Comment by thiagovilla** [comment]
Hi, @DeMoorJasper. I've run `npm list -g` and it says `parcel-bundler@1.8.1`

**Comment by DeMoorJasper** [comment]
Not sure why this happens but #1335 just got merged into the master, so you can probably try the current master branch.

Note node_module imports now have a prefix `~` so in your case that would be `~@material`

**Comment by thiagovilla** [comment]
That didn't work either, but I think I've found the problem. Or started to find it.

Here's what I did:

First, I cleaned up the `/dist` and `/.cache` Parcel-generated folders.

Then, I went on to clean `npm`'s cache with `npm cache verify`. Some garbage collected there.

Alright, so I run `parcel index.html` and go the same error:

```bash
PS C:\apps\test> parcel index.html
Server running at http://localhost:1234
×  C:\apps\test\main.scss: File to import not found or unreadable: @material/elevation/mixins.
    at options.error (C:\apps\test\node_modules\node-sass\lib\index.js:291:26)
```

So I tried to trace it. I went to my `main.scss` file and saw it was trying to import from `@material/top-app-bar/mdc-top-app-bar". So I went to that file:

![image](https://user-images.githubusercontent.com/22099217/40438687-199f4732-5e8f-11e8-8312-acf7fd9a58c1.png)

I opened `mdc-top-app-bar.scss` and saw this on line 17:

![image](https://user-images.githubusercontent.com/22099217/40438746-3769d73c-5e8f-11e8-9c23-ec908e455663.png)

`@import "@material/elevation/mixins";`

Alright, so then I went to _that_ file and, guess what, it's not `mixins.scss` but `_mixins.scss`.

![image](https://user-images.githubusercontent.com/22099217/40438817-7dafe768-5e8f-11e8-952d-ce00f345b1bc.png)

I don't know whether this is a bug from Google or not, because most `.scss` files in the `@material` subfolders have the `_` prefix.

Anyway, I tried to run a test. I went on to `mdc-top-app-bar.scss` and changed line 17 to this:

![image](https://user-images.githubusercontent.com/22099217/40438879-aaee5926-5e8f-11e8-8dc8-d359b2b0bd36.png)

`@import "@material/elevation/_mixins";`

Deleted the `/.cache` and `dist` folders and `npm cache verify` again. Then `parcel index.html` again and voilà:

```bash
PS C:\apps\test> parcel index.html
Server running at http://localhost:1234
×  C:\apps\test\main.scss: File to import not found or unreadable: @material/theme/variables.
    at options.error (C:\apps\test\node_modules\node-sass\lib\index.js:291:26)
```

I guess it "worked", since now the "file to import not found or unreadable" is the one on line 18 in `mdc-top-app-bar.scss`.

Is this a Parcel thing? Or Google? I haven't tried setting this up in `webpack`.

Any thoughts on what should I do next?

**Comment by DeMoorJasper** [comment]
@thiagovilla I would report this to google.
They don't follow the default scss semantics, which also includes putting `~` in front of node_module requires, are they using their own resolver by any chance?

**Comment by thiagovilla** [comment]
Ouch, you missed me on "resolver". I'm at the beginner level here.

I found this on their repo:

![image](https://user-images.githubusercontent.com/22099217/40441783-6a3071c2-5e98-11e8-9085-5eeec9bceff6.png)

Does it help anyhow?

I don't even know what I should write as an issue over there :/ Same as here?

**Comment by DeMoorJasper** [comment]
Yeah seems like they have a custom pathResolver written for webpack I guess?

I guess opening the same issue would be good enough, just look at issue reporting guidelines and probably link this issue.

**Comment by m5o** [comment]
@thiagovilla 

> I don't know whether this is a bug from Google or not, because most `.scss` files in the `@material` subfolders have the `_` prefix.

📝 http://sass-lang.com/guide#topic-4 says:

You can create partial Sass files that contain little snippets of CSS that you can include in other Sass files. This is a great way to modularize your CSS and help keep things easier to maintain. A partial is simply a Sass file named with a leading underscore. You might name it something like `_partial.scss`. The underscore lets Sass know that the file is only a partial file and that it should not be generated into a CSS file. Sass partials are used with the `@import` directive.

**Comment by thiagovilla** [comment]
GitHub - the place you learn from the best. Thank you @DeMoorJasper and @m5o! I'll take this issue to their repo. I guess we can shut this down?

**Comment by claudionunezjr** [comment]
Where is the linked google issue that was said would be created from this? Thanks.

**Comment by DavidMS** [comment]
Hi @thiagovilla , did you report this bug to google or find a workaround? Thanks

**Comment by rafaldev** [comment]
Probably he does not report because I have this same issue

**Comment by Mr-Zer0** [comment]
I am facing the same issue.
