### ISSUE TITLE
Failed to resolve existing module `rmc-steps`

### ISSUE THREAD

**Issue by FourLeafClover** [parcel-bundler/parcel#1422]
![image](https://user-images.githubusercontent.com/8449788/40405548-9ee27680-5e8f-11e8-84ea-4ade57760fde.png)

**Comment by lordGuan** [comment]
you may need babel in your project

**Comment by FourLeafClover** [comment]
@lordGuan   sames, where  have some problems when i import antd-mobile。 I have npm install rmc-steps  

![image](https://user-images.githubusercontent.com/8449788/40406445-466baad6-5e93-11e8-9a13-85f1833d3542.png)

**Comment by DeMoorJasper** [comment]
Object spread is ES2018 not ES6

**Comment by FourLeafClover** [comment]
@DeMoorJasper  I added the babel。 but there have another problem。please see the previous image。

**Comment by DeMoorJasper** [comment]
If the dependency is installed I'm not sure why it can't get resolved

**Comment by DeMoorJasper** [comment]
An example repo or a bit more info would be helpfull. There is a bug template if you file an issue, would be nice if you use that to reformat the issue :)

**Comment by fathyb** [comment]
@FourLeafClover did you try with `--no-cache` or remove the `.cache` directory?

**Comment by cncolder** [comment]
Example here:

package.json
```json
{
  "dependencies": {
    "antd-mobile": "^2.2.1"
  }
}
```

index.html
```html
<html>
<body>
    <script src="./index.jsx"></script>
</body>
</html>
```

index.jsx
```jsx
import Steps from "antd-mobile/es/steps";
```

`parcel index.html`
```bash
parcel-antd-mobile/node_modules/antd-mobile/es/steps/index.js:7:20: Cannot resolve dependency 'rmc-steps'
   5 | import _inherits from 'babel-runtime/helpers/inherits';
   6 | import React from 'react';
>  7 | import RcSteps from 'rmc-steps';
     |                     ^
   8 | import Icon from '../icon';
   9 |
  10 | var Steps = function (_React$Component) {
```

The `rmc-steps` stay there. But parcel just not seen.

`ls node_modules/rmc-steps`
```bash
HISTORY.md   LICENSE.md   README.md    assets       lib          package.json
```

**Comment by cncolder** [comment]
rmc-steps has a mistake field `"module": "./es/index"` in `package.json`. It not bundle es code into npm.

[https://unpkg.com/rmc-steps@1.0.0/package.json](https://unpkg.com/rmc-steps@1.0.0/package.json)

**Comment by DeMoorJasper** [comment]
Glad you found the issue.

I'll close this issue, please report this to https://github.com/react-component/m-steps

**Comment by cncolder** [comment]
Hi @DeMoorJasper , Is there a plan to handle it like this? If module not exist then downgrade to main? I'm not sure how many packages with this mistake in npm.

**Comment by DeMoorJasper** [comment]
I think this PR implements something similar: #1577

**Comment by ranfdev** [comment]
Yes, in that pr, parcel tries to load different files (like module, main, source) until it finds an existing one. That should solve the issue

**Comment by ranfdev** [comment]
@cncolder I can confirm, in #1577 your example works
