### ISSUE TITLE
Typescript errors in HMR error overlay

### ISSUE THREAD

**Issue by scrossan-crown** [parcel-bundler/parcel#1424]
# 🙋 Feature request

Display typescript errors in the HMR error overlay

## 🤔 Expected Behaviour 

Typescript errors to be displayed in the HMR error overlay 

## 😯 Current Behaviour

An error is displayed in the HMR error overlay but it's not the error in the console for the typscript compiler

## 💁 Possible Solution

Display the typescript compiler error in the HMR error overlay instead of the error that is being displayed currently

## 🔦 Context
When the typescript compiler finds an error

## 💻 Examples

![image](https://user-images.githubusercontent.com/30405149/40422185-6a0d433a-5e86-11e8-9423-01d830740835.png)

![image](https://user-images.githubusercontent.com/30405149/40422279-c746c51c-5e86-11e8-9499-133252ed17a6.png)

**Comment by DeMoorJasper** [comment]
I think this is a feature request for `parcel-plugin-typescript`?
As parcel core doesn't have any type error checking

**Comment by fathyb** [comment]
Like Jasper said it's a plugin feature, but while we're here : just set `noEmit` to `true` in `tsconfig.json` :
- `true` means
  > Don't produce any JavaScript unless you are sure there are no type-checking errors
- `false` means
  > Report type-checking errors but don't wait for it, and if you catch an error let me handle it.

And also we should probably resolve why you get an `Unknown error` in the first place, this doesn't look good.

**Comment by scrossan-crown** [comment]
I'll try `noEmit: true` in my `tsconfg.json`. I do have `noEmitOnError: true`  currently but I'll try replacing it with `noEmit`. If I want the typescript errors in the HMR error overlay I should try `parcel-plugin-typescript` package? Does it need to be local or globally installed?

**Comment by fathyb** [comment]
Ah sorry I was wrong, it's `noEmitOnError` not `noEmit`.

It looks like you are using `parcel-plugin-typescript ` because Parcel doesn't do any type-checking out of the box. You may also want to check if you are up to date : 
- Yarn: `yarn list "parcel-*"`
- npm: `npm ls parcel-bundler parcel-plugin-typescript`
