### ISSUE TITLE
Reduce the code splitting chunk size

### ISSUE THREAD

**Issue by tigp** [parcel-bundler/parcel#1428]
# ❔ Question

Hi guys, thank you for this great bundler!

I have a lot of small chunks and would like to ask you if it Is possible to reduce chunk size, to not include `parcelRequire` for every import?

Thank you!

## 💻 Code Sample

```
parcelRequire = function (e, r, n) {
	var t = "function" == typeof parcelRequire && parcelRequire, i = "function" == typeof require && require;

	function u(n, o) {
		if (!r[n]) {
			if (!e[n]) {
				var f = "function" == typeof parcelRequire && parcelRequire;
				if (!o && f) return f(n, !0);
				if (t) return t(n, !0);
				if (i && "string" == typeof n) return i(n);
				var c = new Error("Cannot find module '" + n + "'");
				throw c.code = "MODULE_NOT_FOUND", c
			}
			a.resolve = function (r) {
				return e[n][1][r] || r
			};
			var l = r[n] = new u.Module(n);
			e[n][0].call(l.exports, a, l, l.exports)
		}
		return r[n].exports;

		function a(e) {
			return u(a.resolve(e))
		}
	}

	u.isParcelRequire = !0, u.Module = function (e) {
		this.id = e, this.bundle = u, this.exports = {}
	}, u.modules = e, u.cache = r, u.parent = t;
	for (var o = 0; o < n.length; o++) u(n[o]);
	return u
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.7.1
| Node             | v8.9.2
| npm/Yarn         | yarn 1.6.0
| Operating System | osx

**Comment by DeMoorJasper** [comment]
I think the point is that these bundles should work independent of each other. Therefore they all need this piece of code.
I think when this PR lands this will no longer be part of the output, although I might be mistaken. #1135

**Comment by tigp** [comment]
@DeMoorJasper thank you for your reply! That would be really awesome!
