### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): RangeError: Maximum call stack size exceeded (node:9864) [DEP0018]

### ISSUE THREAD

**Issue by ReneBroekhoven** [parcel-bundler/parcel#143]
This is a 🐛 bug report.

After installing parcel-loader (with yarn) and creating the (your) example index.html and index.js, running parcel index.html results in a error message in CLI and the execution seems to be in a loop: 

### 🎛 Configuration (.babelrc, package.json, cli command)

package.json : 
{
  "dependencies": {
    "parcel-bundler": "^1.0.3"
  },
  "name": "rene",
  "version": "1.0.0",
  "description": "test",
  "main": "index.js",
  "author": "rene",
  "license": "MIT"
}

cli :  yarn add parcel-bundler
       yarn init
       parcel index.html
       
### 🤔 Expected Behavior
A packaged file should appear in the dist folder, and a server on localhost:1234 should be running-

### 😯 Current Behavior

In CLI :  parcel index.html
Then : message : Server running at http://localhost:1234
Then : errormessage : 
(node:9864) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): RangeError: Maximum call stack size exceeded (node:9864) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

The result is that no server is running, the created dist folder is empty

### 💁 Possible Solution
No idea :-(

### 🔦 Context

Just trying your own example from the parcel site.

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |    1.0.2
| Node             |   8.9.2
| npm/Yarn         |  5.5.1. / 1.3.2
| Operating System |  Windows10 64bit

**Comment by davidnagli** [comment]
Do you mind filling in the issue template with all your info :)

**Comment by philipodev** [comment]
i might be wrong here, but was'nt this issue fixed with 1.03?

**Comment by ReneBroekhoven** [comment]
See my refilled issue log.
And @philipodev : I am using 1.0.3

**Comment by philipodev** [comment]
@ReneBroekhoven but the error message in the title stated parcel 1.02, when you run the command `parcel index.html` directly in a terminal its using the global `parcel` instead of the one in `package.json`. try `parcel --version` to verify its `1.03`. if not, then just run `npm install --global parcel-bundler` to update

**Comment by ReneBroekhoven** [comment]
@philipodev You are totally right ! I missed the difference between what was in the package.json and the actual version. Problem solved !  Thanks a lot.

**Comment by DanielRuf** [comment]
So the issue can be closed? Also the issue title should be short ;-)
