### ISSUE TITLE
 Cannot find module error when importing an static file using typescript

### ISSUE THREAD

**Issue by ellipticaldoor** [parcel-bundler/parcel#1445]
# 🐛 bug report

If you try to import an image, in normal javascript, to get the url of the file it just works:
``` js
import characterImage from '@client/assets/img/character.png'
```
But when I use typescript I get this error on the vscode console
``` js
Cannot find module '@client/assets/img/character.png'.
```

## 🎛 Configuration (.babelrc, package.json, cli command)

this is my tsconfig

```js
{
	"compilerOptions": {
		"strict": false,
		"module": "commonjs",
		"moduleResolution": "node",
		"types": ["node", "jest"],
		"newLine": "LF",
		"outDir": "lib",
		"target": "es2017",
		"sourceMap": true,
		"declaration": true,
		"jsx": "preserve",
		"lib": [
			"es2017",
			"dom"
		],
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		"noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "experimentalDecorators": true,
		"baseUrl": "./src",
		"paths": {
            "@client/*": ["./client/*"],
            "@server/*": ["./server/*"]
		}
	},
	"include": [
		"**/*.ts"
	],
	"exclude": [
		".git",
		"node_modules"
	]
}

```

## 🤔 Expected Behavior

It should just load the image.

## 😯 Current Behavior

I get the error I just said above.

## 💁 Possible Solution

No sure, is maybe because an image doesn't have types?

## 🔦 Context

So the app just works and ignores the fact that there is an error with typescript. Is very annoying for development to have false errors all over the place.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | v10.2.1
| npm/Yarn         | yarn 1.7.0| Operating System | macos 10.13.4

**Comment by DeMoorJasper** [comment]
Are you using built-in TS support or the TS plugin?

@fathyb any idea?

**Comment by ellipticaldoor** [comment]
Im not using the ts plugin, also parcel is working and not complaining. Is with the development tools

**Comment by DeMoorJasper** [comment]
So parcel is able to resolve this asset, but vscode complains?

But you don't get the image url either, if you import it through parcel?

**Comment by ellipticaldoor** [comment]
Parcel is working fine but I'm not sure if is hiding the typescript error.

Typescript compiles even with errors.

**Comment by ellipticaldoor** [comment]
@fathyb thank you, that worked

**Comment by hallya** [comment]
@fathyb  not sure to understand how it works. I've created the `.d.ts` in root level of my project and declaring a module for svg the way you did it but I still got lint errors.

So I've to declare it in the file where I try the import and I got:
`Invalid module name in augmentation, module '*.svg' cannot be found`

**Comment by awulkan** [comment]
I also tried creating a .d.ts file in the root with that content, but it didn't work. :(

**Comment by fuermosi777** [comment]
you need to add the d.ts to "include" of tsconfig.json

**Comment by Arver1** [comment]
if you entry point fileName - index.ts you need to name file at will but not index.ts

**Comment by fernandoajn** [comment]
> Create a `.d.ts` file in your project and put :
> 
> ```ts
> declare module '*.png'
> ```
> 
> It will instruct TypeScript to use `any` for all imports ending with `.png`. It it still doesn't work try to restart VSCode.

It worked here. I'm using create-react-app and put it into react-app-env.d.ts file.

**Comment by mrcMesen** [comment]
> Create a `.d.ts` file in your project and put :
> 
> ```ts
> declare module '*.png'
> ```
> 
> It will instruct TypeScript to use `any` for all imports ending with `.png`. It it still doesn't work try to restart VSCode.

It works for me, working with expo-reactnative, I just made in the root a file called `index.d.ts`

**Comment by FelipeRosa** [comment]
> > Create a `.d.ts` file in your project and put :
> > ```ts
> > declare module '*.png'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It will instruct TypeScript to use `any` for all imports ending with `.png`. It it still doesn't work try to restart VSCode.
> 
> It works for me, working with expo-react native, only I create in the root a file called `index.d.ts`

Creating `index.d.ts` inside the project's root folder is what did the trick for me. Thanks!

**Comment by jack3898** [comment]
When I create a .d.ts file in the root of my project it appears to work, then when I close that file all the red underlines appear under my imports again. Can anyone confirm if this happens to them?

**Comment by michael-pont** [comment]
> When I create a .d.ts file in the root of my project it appears to work, then when I close that file all the red underlines appear under my imports again. Can anyone confirm if this happens to them?

This is also happening to me within vscode. When the file containing one of these imports (e.g. png, woff2, etc.) is not active/open as an active tab then no errors appear. Once the file is opened then the errors appear.

**Comment by jack3898** [comment]
> This is also happening to me within vscode. When the file containing one of these imports (e.g. png, woff2, etc.) is not active/open as an active tab then no errors appear. Once the file is opened then the errors appear.

Hey Michael, I should have updated this thread sooner! I managed to find a solution for Parcel V2 (which is what I am using).

I got the solution from [the Parcel V2 TypeScript documentation](https://v2.parceljs.org/languages/typescript/), where it shows you the `tsconfig.json` config.

In the end, what worked for me was putting this in my tsconfig:

```
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "jsxImportSource": "react-jsx",
  }
}
```

The only thing I changed from the documentation was setting `"preact"` to `"react-jsx"`. Of course, change it to suit your environment.

I am not at work at the moment, so this is from the top of my head. Let me know if you still get problems, I may have missed something. :)

**Comment by UsamaEjaz0** [comment]
> ```ts
> declare module '*.png'
> ```

I had a `index.tsx` file & created `index.d.ts` in root folder and it appeared as nested within `index.tsx` in WebStorm. So, I renamed it to `exports.d.ts` and it's working fine now.

**Comment by ghost** [comment]
Just create the file src > react-app-env.d.ts
with the following contetn?

/// <reference types="react-scripts" />

Solved.

**Comment by GoodmanNgwenya** [comment]
> Just create the file src > react-app-env.d.ts with the following contetn?
> 
> ///
> 
> Solved.

This one worked for me, Thanks

**Comment by zainulabideen-1990** [comment]
thnx me later!!

There should be a react-app-env.d.ts file in your src folder.
If you don't see it, Create a new file in src folder named react-app-env.d.ts.

Now, just add the code below in your react-app-env.d.ts file.

only add this line
/// <reference types="react-scripts" />

**Comment by gentlee** [comment]
> Create a `.d.ts` file in your project and put :
> 
> ```ts
> declare module '*.png'
> ```
> 
> It will instruct TypeScript to use `any` for all imports ending with `.png`. It it still doesn't work try to restart VSCode.

This actually breaks cmd+click on the image.

**Comment by dilancn** [comment]
I could solve this creating a vite-env.d.ts file and include this code in root folder for vite-react project:
`declare module "*.png";`
