### ISSUE TITLE
trouble building project with parcel v1.8.x

### ISSUE THREAD

**Issue by orzechowskid** [parcel-bundler/parcel#1448]
# 🐛 bug report

my app, written using CSS modules, builds correctly with parcel-bundler v1.7.1 but usually (but not always!) hangs with parcel-bundler 1.8.0 or 1.8.1 .  This problem happens when running either `parcel` or `parcel build`, with HMR or without.

## 🎛 Configuration (.babelrc, package.json, cli command)
.babelrc
```js
{
    "ignore": [
        "node_modules/**/*"
    ],
    "plugins": [[
        "transform-runtime"
    ], [
        "transform-object-rest-spread"
    ], [
        "add-react-displayname"
    ]],
    "presets": [[
        "env", {
            "modules": false,
            "targets": {
                "browsers": [
                  "last 2 versions",
                  "not dead"
                ]
            }
        }
    ], [
        "react"
    ]]
}
```
package.json:
```js
{
    "name": "frontend",
    "version": "1.0.0",
    "description": "",
    "module": "src/index.js",
    "scripts": {
        "build:prod": "NODE_ENV=production parcel build src/index.js -d dist --public-url=/",
        "deploy": "./bin/s3.sh",
        "start": "NODE_ENV=development parcel --no-hmr src/index.js --https --public-url=/"
    },
    "author": "",
    "license": "UNLICENSED",
    "dependencies": {
        "check-prop-types": "^1.1.2",
        "deep-equal": "^1.0.1",
        "intl-messageformat": "^2.2.0",
        "lodash.debounce": "^4.0.8",
        "md5": "^2.2.1",
        "meta-manager": "^1.1.0",
        "preact": "^8.2.9",
        "preact-compat": "^3.18.0",
        "preact-portal": "^1.1.3",
        "prop-types": "^15.6.1",
        "react-markdown": "^2.5.1",
        "unistore": "^3.0.6",
        "whatwg-fetch": "^2.0.4"
    },
    "devDependencies": {
        "babel": "^6.23.0",
        "babel-core": "^6.26.3",
        "babel-plugin-add-react-displayname": "^0.0.5",
        "babel-plugin-external-helpers": "^6.22.0",
        "babel-plugin-module-resolver": "^3.1.1",
        "babel-plugin-transform-object-rest-spread": "^6.26.0",
        "babel-plugin-transform-react-jsx": "^6.24.1",
        "babel-plugin-transform-runtime": "^6.23.0",
        "babel-polyfill": "^6.26.0",
        "babel-preset-env": "^1.7.0",
        "babel-preset-react": "^6.24.1",
        "cssnano": "^3.10.0",
        "node-sass": "^4.9.0",
        "parcel-bundler": "^1.8.1",
        "parcel-plugin-bundle-visualiser": "^1.1.2",
        "postcss-cssnext": "^3.1.0",
        "postcss-modules": "^1.1.0",
        "postcss-simple-vars": "^4.1.0"
    },
    "alias": {
        "react": "preact-compat",
        "react-dom": "preact-compat"
    }
}
```

## 🤔 Expected Behavior

parcel should successfully build my app:

`✨  Built in 7.70s.`

## 😯 Current Behavior

parcel does not build my app; it hangs at

`⏳  Building _object-to-array.js...`

where `_object-to-array.js` is a seemingly random .js / .scss / .json file somewhere in my codebase or node_modules directory.

`top` appears to show no CPU activity for the process.  clearing parcel's .cache directory is inconclusive; some builds still fail after I try that, some builds succeed.

## 💁 Possible Solution

:woman_shrugging: 

## 💻 Code Sample

working on a smallest-possible repo which exhibits the problem.

## 🌍 Your Environment

node.js v8.11.1 / npm 5.6.0
Ubuntu 17.10

**Comment by DeMoorJasper** [comment]
Might be related to the watcher or css transpilers, in that case it should be fixed in the next release

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thedodd** [comment]
Any status update on this?

**Comment by DeMoorJasper** [comment]
Try with 1.9

**Comment by orzechowskid** [comment]
It's impossible to prove a negative, of course, but builds do seem to be much better for me with parcel 1.9.0 .  thanks!

**Comment by DeMoorJasper** [comment]
Awesome, I'll close this for now then :)
