### ISSUE TITLE
Use import in nodejs will cause error

### ISSUE THREAD

**Issue by zhmushan** [parcel-bundler/parcel#1449]
# ❔ Question

Use import in nodejs will cause error.

## 🔦 Context

When I use parcel to package a node application written in typescript, I can only use require to reference third-party dependencies.

## 💻 Code Sample

```ts
import * as koa from 'koa'
const app = new koa() // error
```
```ts
const koa = require('koa')
const app = new koa() // success
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 8.11.1
| Yarn         | 1.6.0
| Operating System | windows 10

**Comment by DeMoorJasper** [comment]
Perhaps this helps #202

**Comment by zhmushan** [comment]
What I mean is that koa has no default export, but parcel thinks it has a default export, and set `newObj.default = obj` in output file

**Comment by mohsen1** [comment]
Related to #1378 

Parcel needs to understand `allowSyntheticDefaultImports` config of TypeScript.

**Comment by zhmushan** [comment]
@mohsen1 you are right, thanks

**Comment by fathyb** [comment]
[Solution](https://stackoverflow.com/a/49256285/4118124) (replace `express` with `koa`) : 

> For a definitive fix set the compiler option `esModuleInterop` to `true` and use `import express` instead of `import * as express`.
> 
> **The problem** :
> 
> The ES6 specification defines the notion of "namespace object". A namespace object is `namespaceObject` in this statement : `import * as namespaceObject from 'a-module'`. The `typeof` this object is `object`, you are not supposed to be able to call it.
> 
> You were using `import * as express` until now because `express` is a CommonJS module, for Node.js, it is exported using `module.exports`. However it is illegal in the ES6 spec, and TypeScript now warns you.
> 
> **The solution** :
> 
> Setting `esModuleInterop` to true will make TypeScript wrap your `import` calls to check if the module is an ES6 module or a CommonJS. If it's a CommonJS module and you are using `import default from 'module'` TypeScript will find out and return the correct CommonJS module.
> 
> From the [TypeScript release note](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html) :
> 
> > Note: The new behavior is added under a flag to avoid unwarranted
> > breaks to existing code bases. We highly recommend applying it both to
> > new and existing projects. For existing projects, namespace imports
> > (import * as express from "express"; express();) will need to be
> > converted to default imports (import express from "express";
> > express();).
