### ISSUE TITLE
You should be using uglify-es.

### ISSUE THREAD

**Issue by trusktr** [parcel-bundler/parcel#145]
Using uglify-js is likely to leave your users of some modern browsers with zero-configuration errors. 

F.e. you can find many bugs like this one:

https://github.com/meteor/meteor/issues/9224

Just use uglify-es

**Comment by gabrielsanterre** [comment]
Webpack also use it: https://webpack.js.org/plugins/uglifyjs-webpack-plugin/

**Comment by davidnagli** [comment]
If we would be using uglify-es, we would solve #8

**Comment by kingdaro** [comment]
I'd be happy to take a stab at this if it's not being done already. Is it any more than a dependency-swap and some API usage changes?
