### ISSUE TITLE
Support Angular

### ISSUE THREAD

**Issue by tatsujb** [parcel-bundler/parcel#1455]
# 🙋 feature request

Support Angular, the 2nd most popular JS front-end framework.

## 🤔 Expected Behavior

for Parcel to work in a pretty inclusive way with Angular

## 😯 Current Behavior

A year into Parcel and it does not work with Angular. there isn't even a guide in the recipes section of the parcel website.

**Comment by tatsujb** [comment]
I actually still would like this.

**Comment by DeMoorJasper** [comment]
There is a plugin for that `parcel-plugin-typescript`

**Comment by tatsujb** [comment]
not in my experience. I've attempted constantly to switch my project over to parcel with no success.
