### ISSUE TITLE
[Vue] Uncaught (in promise) Error: Cannot find module 'undefined'     at newRequire

### ISSUE THREAD

**Issue by luoway** [parcel-bundler/parcel#1465]
# 🐛 bug report

Chrome throw Error when `import()` dynamic import more than ONE vue components, though vue components render successfully.

## 🎛 Configuration (.babelrc, package.json, cli command)
.babelrc
```json
{
    "presets": ["env"],
    "plugins": ["transform-runtime"]
}
```

package.json
```json
"devDependencies": {
    "@vue/component-compiler-utils": "^1.3.1",
    "babel-core": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.1",
    "vue-hot-reload-api": "^2.3.0",
    "vue-template-compiler": "^2.5.16"
}
```
## 🤔 Expected Behavior

No Error reports.

## 😯 Current Behavior

Both vue components rendered successfully.

But there was an Error.
> Uncaught (in promise) Error: Cannot find module 'undefined'
>    at newRequire

## 💻 Code Sample

index.js
```js
(async ()=>{
    new Vue({
        components:{
            'the-header': () => import('./components/Header.vue'),
            'the-home': () => import('./components/Home.vue')
        }
    }).$mount('#app')
})()
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 8.9.1
| npm/Yarn         | npm 5.5.1
| Operating System | macOS

**Comment by YajJackson** [comment]
Running into this issue as well

**Comment by cdll** [comment]
same issue here~
