### ISSUE TITLE
webmanifest name mangling breaks PWA updates

### ISSUE THREAD

**Issue by bard** [parcel-bundler/parcel#1466]
## 🤔 Expected Behavior

Updating the manifest.webmanifest for a PWA that was added to home screen should cause the application to update.

## 😯 Current Behavior

The application is not updated.

Background: on Android, PWAs can be installed along with native applications: https://developers.google.com/web/fundamentals/app-install-banners/ When the manifest is changed remotely, the PWA is repackaged and updated.

However, the way parcel renames the manifest whenever its content changes however breaks the update functionality. From Peter Kotwicz (WebAPK team):

> - We will only update a WebAPK if the Web Manifest URL does not change. If you change the web page from referencing <link rel="manifest.json"> to reference <link rel="manifest2.json"> the WebAPK will no longer update [(source)](https://groups.google.com/a/chromium.org/d/msg/chromium-discuss/NUjaM4QtFrU/gTJ1kSONBAAJ)

## 💁 Possible Solution

Add manifest.webmanifest to the exceptions outlined in #872 and implemented in #1025.

## 🔦 Context

I spent some time trying to get a PWA to update before researching reasons it might not update and stumbling over the newsgroup post quoted above.

**Comment by jay-bricksoft** [comment]
As a little workaround for your problem, you could re-route the asset files as such as the webmanifest.
For thisto work you could use `parcel-plugin-bundle-manifest` which creates a json file where names are mapped to output files and then load it and create dynamic routes to these files and remap them.

> The Manifest will look like this :
```json
{
  "index.html": "/dist/index.html",
  "index.js": "/dist/5f0796534fe2892712053b3a035f585b.js",
  "main.scss": "/dist/5f0796534fe2892712053b3a035f585b.css"
}
```

**Comment by AndreasPizsa** [comment]
@bard Just had the same problem, thank you for filing the bug.

As a pragmatic workaround, I added an empty `<a href="manifest.webmanifest></a>` element to the `<body>`. This works because #1025 specifies that file names referenced in `<a>` elements are treated as entry points and thus remain unhashed. Thank you for linking to that issue!

**Comment by janbaer** [comment]
This issue is still not closed but it's a while ago since its last update. So the workaround that @AndreasPizsa  suggested is working for me, but is there maybe another not so hacky way to exclude some files (like a manifest.json) from the renaming through Parcel? I really like the way how Parcel is doing a lot things without configuration, but sometimes you just need a way to configure someting.

**Comment by janbaer** [comment]
Update, the way @AndreasPizsa  don't works for me, since Parcel.js is still renaming the manifest.json file to manifest.js and is also changing the content. Is there a way to prevent this behavior, so that Parcel.js don't touch this file at all? Thanks!

**Comment by devongovett** [comment]
Perhaps we should make webmanifest an entry module by default so it doesn't get content hashed? This could be done by adding the `entry: true` flag to the dependency created when processing `<link rel="manifest">` inside HTMLAsset. Would one of you like to take a crack at a PR for that?

@janbaer manifest.json is not currently supported, you need to name your file with the `.webmanifest` extension.

**Comment by AndreasPizsa** [comment]
I'll look into it @devongovett

**Comment by janbaer** [comment]
@devongovett Thanks for the hint with the file extension. So the trick with the anchor works now also for me. But it would be great, to make it configurable or just handle the webmanifest in the same way like the serviceworker file.
