### ISSUE TITLE
"Cannot read property 'rootDir' of undefined" when making custom Asset

### ISSUE THREAD

**Issue by f3ltron** [parcel-bundler/parcel#1467]
# ❔ Question

Hello and thank's for your awesome works ! I tried to understand how to create a custom asset type and after a custom packager that will receive asset type but nothing work. Maybe the document is not enough ?

## 🔦 Context

I created asset.js and a packager.js and a custom builder then i create a test.foo in my src write something but it's like build miss it

## 💻 Code Sample

my builder custom
```
const Bundler = require('parcel-bundler');
const Path = require('path');

// Entrypoint file location
const file = Path.join(__dirname, './index.html');

// Bundler options
const options = {
  outDir: './dist', // The out directory to put the build files in, defaults to dist
  outFile: 'index.html', // The name of the outputFile
  watch: true, // whether to watch the files and rebuild them on change, defaults to process.env.NODE_ENV !== 'production'
  cache: false, // Enabled or disables caching, defaults to true
  minify: false, // Minify files, enabled if process.env.NODE_ENV === 'production'
  target: 'browser', // browser/node/electron, defaults to browser
  logLevel: 3, // 3 = log everything, 2 = log warnings & errors, 1 = log errors
  sourceMaps: true, // Enable or disable sourcemaps, defaults to enabled (not supported in minified builds yet)
  detailedReport: false // Prints a detailed report of the bundles, assets, filesizes and times, defaults to false, reports are only printed if watch is disabled
};

// Initialises a bundler using the entrypoint location and options provided
const bundler = new Bundler(file, options);

bundler.addAssetType('.foo', require.resolve('./builder/Asset.js'));
bundler.addPackager('foo', require.resolve('./builder/Packager.js'));
// Run the bundler, this returns the main bundle
// Use the events if you're using watch mode as this promise will only trigger once and not for every rebuild

bundler.bundle();
```
my asset.js
```
const {Asset} = require('parcel-bundler');

class MyAsset extends Asset {

  constructor(name, options) {
    super(name, options);
    this.type = 'foo';
    console.log('je suis dans le constructor de mon asset')
  }

  parse(code) {
    console.log('je suis dans le parse');
    return ast;
  }

  async transform() {
    console.log('je suis dans le transform')
  }

  generate() {
    return [
      {
        type: 'foo',
        value: 'prout',
      }
    ];
  }

}

module.exports = MyAsset;

```

packager.js
```
const Packager = require('parcel-bundler').Packager;

class myPackager extends Packager {
  async addAsset(asset) {
    await this.dest.write(asset.generated.foo);
  }

  async end() {
    // optional. write file trailer if needed.
    await this.dest.end(trailer);
  }

  async start() {
    // optional. write file header if needed.
    await this.dest.write(header);
  }
}

module.exports = myPackager;
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | v8.11.1
| npm/Yarn         | npm 5.6.0
| Operating System | windows10

**Comment by DeMoorJasper** [comment]
For addassettype it’s just foo not .foo

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by f3ltron** [comment]
i delete the .foo for a foo in my builder.js

But it never passe in any console log ? Maybe its normal i dont know ?

**Comment by al-the-x** [comment]
Your `parse` definition accepts `code` and returns `ast` but does nothing to turn `code` into `ast`... I'm struggling with writing a Parcel plugin, as well.

**Comment by f3ltron** [comment]
Yeah the documentation started well .. But The document doesnt go to a concret simple test... Maybe its should be good to do it . If you have others informations tell me

**Comment by fathyb** [comment]
Hey @f3ltron, let's debug this. You error is here, line 22 : 

https://github.com/parcel-bundler/parcel/blob/f226d260cd1161c72fef229534e9f2405b031d45/src/Asset.js#L17-L26

This means that `options` is undefined, this is because the constructor you are using (`name, options`) is for the next version of Parcel (which isn't release to npm).

To fix the issue just add `pkg` to your arguments : 

```js
class MyAsset extends Asset {
  constructor(name, pkg, options) {
    super(name, pkg, options);
```

**Comment by DeMoorJasper** [comment]
Parcel update has been released and this should now work
