### ISSUE TITLE
Compiling bootstrap 4 gives error

### ISSUE THREAD

**Issue by amitjindal** [parcel-bundler/parcel#1473]
# 🐛 bug report

When trying to compile bootstrap 4 I get an error: Unknown plugin "@babel/proposal-object-rest-spread" specified in "base" at 0

## 🎛 Configuration (.babelrc, package.json, cli command)

**bower.json**

```js
{
  "name": "test",
  "dependencies": {
    "bootstrap": "4.0.0"
  },
  "resolutions": {
    "bootstrap": "~4"
  }
}
```

**theme.js**

```js
import 'theme';
import './bower_components/bootstrap/dist/js/bootstrap.js';
```

**theme.scss**

Blank file.

No other files were prepared.

**Steps to reproduce:**

1. bower install
2. parcel theme.js

## 🤔 Expected Behavior

This should compile the files into dist/theme.js and dist/theme.css

## 😯 Current Behavior

➜  parcel-error parcel theme.js
Server running at http://localhost:1234
🚨  /Users/me/tmp/parcel-error/bower_components/bootstrap/dist/js/bootstrap.js: Unknown plugin "@babel/proposal-object-rest-spread" specified in "base" at 0, attempted to resolve relative to "/Users/me/tmp/parcel-error/bower_components/bootstrap/dist/js"
    at /Users/me/.nvm/versions/node/v8.7.0/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/me/.nvm/versions/node/v8.7.0/lib/node_modules/parcel-bundler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)

## 💁 Possible Solution

Don't have a solution for this.

## 🔦 Context

This is currently a show stopper. I am trying to compile a theme with various files into a combined file.

**Comment by amitjindal** [comment]
Hi, can anyone help please? Is there something I can do to fix this problem?

**Comment by knight-bubble** [comment]
@amitjindal May this one https://github.com/parcel-bundler/parcel/issues/1503 be related?

**Comment by amitjindal** [comment]
@knight-bubble  I tried with latest release. Still does not works. I assumed the bug fix was included in latest release.
