### ISSUE TITLE
Doesn't rebuild bundle on version 1.8.1

### ISSUE THREAD

**Issue by kv4sha** [parcel-bundler/parcel#1479]
# 🐛 bug report

Parcel doesn't rebuild bundle when I save file on version 1.8.1, but it works on version 1.6.2.
I use VSCode it doesn't have "safe write" problem

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
    "presets": ["env", "react"]
}

```

## 🤔 Expected Behavior

Parcel should to rebuild bundle when I save file.

## 😯 Current Behavior

Parcel doesn't rebuild bundle when I save file.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.8.1
| Node             |10.3.0
| npm/Yarn         |npm 6.1.0
| Operating System |macOS 10.13.5

**Comment by hasparus** [comment]
Same issue on Windows and yarn 1.6.0.

**Comment by Giorat** [comment]
Can you provide a repo link to clone your exactly your setup @kv4sha ?

**Comment by kv4sha** [comment]
@Giorat https://github.com/kv4sha/pavel.hetsman.cv.github.io

**Comment by dlbears** [comment]
Same issue, on windows

**Comment by DeMoorJasper** [comment]
Might be a chokidar bug?

Chokidar has been causing a lot of issues on parcel lately

**Comment by kv4sha** [comment]
Doesn't work in version 1.9.1

**Comment by kv4sha** [comment]
It works in 1.9.2 with node 10.5.0 and macOS 10.13.5

**Comment by dandv** [comment]
@kv4sha: thank you for mentioning "safe write"! I had this problem with WebStorm, which has "safe write" enabled by default, and Parcel would only detect the first time I saved a file. After disabling that option, Parcel detects every save.
