### ISSUE TITLE
Typescript file extension stays .ts after compilation

### ISSUE THREAD

**Issue by jaredpalmer** [parcel-bundler/parcel#148]
# 🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
  "name": "pts",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "parcel index.html"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/react": "^16.0.28",
    "@types/react-dom": "^16.0.3",
    "parcel-bundler": "^1.0.3",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "tslint": "^5.8.0",
    "tslint-react": "^3.2.0",
    "typescript": "^2.6.2"
  }
}

```

### 🤔 Expected Behavior
TS files should be transformed to .js. Having the same issue as described here. https://github.com/parcel-bundler/parcel/issues/3#issuecomment-350278007

### 😯 Current Behavior
TS files keep their file extensions
### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  1.03
| Node             |  8.8.1
| npm/Yarn         | 5.4.2
| Operating System | macOS Sierra

**Comment by DeMoorJasper** [comment]
This should not happen on the latest version (1.1.0).
Please add some more details like explained here: [ISSUE TEMPLATE](https://github.com/parcel-bundler/parcel/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by jaredpalmer** [comment]
@DeMoorJasper npm latest version is 1.0.3 https://www.npmjs.com/package/parcel-bundler ? Did this not get pushed even though it was tagged??

**Comment by DeMoorJasper** [comment]
Thank you for filling in the form, typescript was implemented in version 1.1.0 and you're using 1.0.3.
So Parcel falls back to raw files, which just keeps the file extension...

**Comment by jaredpalmer** [comment]
When is 1.1.0 going to be pushed to NPM?

**Comment by DeMoorJasper** [comment]
@devongovett

**Comment by devongovett** [comment]
Ah my bad, should be published now

**Comment by jaredpalmer** [comment]
@devongovett I use https://github.com/sindresorhus/np which prevents this kind of thing from happening in future as it pushes and tags in one stroke
