### ISSUE TITLE
Cannot find module './...'

### ISSUE THREAD

**Issue by inad9300** [parcel-bundler/parcel#1480]
# 🐛 bug report

I seem to be experiencing a problem similar to https://github.com/parcel-bundler/parcel/issues/668. I am not using Vue though, but simply the library [@soil/dom](https://www.npmjs.com/package/@soil/dom).

When having an `index.ts` as slim as:

```ts
import {h} from '@soil/dom'

console.log('h', h)
```

I get `Error: Cannot find module './html/h'`.

## 💻 Code Sample

The whole code base can be found at https://github.com/inad9300/Soil/tree/7aebb9e8361e515f4661aecda025172e74c8db9c/examples/notes. This might be useful in terms of configuration files, etc. In terms of the actual code, the snippet shown above is enough to reproduce the problem.

**Comment by inad9300** [comment]
Did you have any time to look into this?

I would like to understand where is Parcel trying to find `'./html/h'` and why. Related to this, I have a couple of questions:
- Where can I read about Parcel's module resolution algorithm?
- Is there any hidden `--debug` or `--verbose` flag to get more (some) information about the error?
- Why isn't the error shown when building the project, but only later in the browser?

**Comment by DeMoorJasper** [comment]
There is currently no verbose logging, see #1385 and #1472

**Comment by inad9300** [comment]
One other clarification that might help: the directory structure of `@soil/dom` in npm is as follows:

```
@soil/
└── dom
    ├── build
    │   ├── html
    │   │   ├── h.js
    │   │   └── ...
    │   ├── index.js
    │   └── ...
    ├── package.json
    └── ...
```

Where the `package.json` looks like this:

```
{
    "main": "build/index.js",
    ...
}
```

And the `index.js` file at some point does:

```js
// ...
var h_1 = require("./html/h");
exports.h = h_1.h;
// ...
```

So it seems that Parcel could figure out the complicated part (looking into the `package.json` for the `"main"` field and so on), but then it cannot resolve the relative path. (Just guessing, really, as I understand very little about how it works.)

**Comment by inad9300** [comment]
I have started a project of a similar nature using webpack this time, and it raises the same errors (although much better described). In consequence, I have open this question in StackOverflow: https://stackoverflow.com/questions/50773966/webpack-typescript-module-not-found.
