### ISSUE TITLE
Dynamically importing two different files with same content and name

### ISSUE THREAD

**Issue by DragonRaider5** [parcel-bundler/parcel#1486]
# 🐛 bug report

When dynamically importing two different files with the same content and name (happened to me for some translation files, as they were empty), `parcel` gives them the same name when doing a production build.
This is because they share the same name (as I said), have the same MD5 (because of the same content) and the output name gets built like that: `{fileName}.{MD5}.{extension}`.

The problem now is, that for production you only get one file out of this instead of two. Those get different `module IDs`, but only one is kept. This results in parcel complaining about missing modules, as one of the `module IDs` basically got lost.

## 🎛 Configuration (.babelrc, package.json, cli command)

File setup:
```
-- index.html
-- index.js
-- dir1
  -- myDupeFile.js
-- dir2
  -- myDupeFile.js
```

`index.html` just needs to execute the script to see the result.

`index.js`
```javascript
Promise.all([
  import('./dir1/myDupeFile.js'),
  import('./dir2/myDupeFile.js')
])
  .then(() => console.log('Ayy @dragonraider5 screwed up the sample'))
  .catch(() => console.error('I successfully reproduced the bug'))
```

my `.babelrc` (should not be required to reproduce the problem)
```js
{
  "presets": [
    "env",
    "react"
  ],
  "plugins": [
    [ "transform-runtime", {
      "helpers": false,
      "polyfill": false,
      "regenerator": true,
      "moduleName": "babel-runtime"
    } ],
    "styled-components",
    "transform-object-rest-spread",
    "transform-class-properties",
    "transform-async-to-generator",
    "inline-react-svg",
    "react-intl"
  ]
}
```

Build: `parcel build index.html --out-dir dist --public-url ./dist/ --no-cache`

## 🤔 Expected Behavior

It should work.

## 😯 Current Behavior

It doesn't work (throws an error because a module wasn't found).

## 🌍 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.7.0 and ^1.8.1 |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by DeMoorJasper** [comment]
I guess we can map both id's to the same file to resolve this issue while still maintaining one file, as that would save a couple bucks on cdn costs

**Comment by DragonRaider5** [comment]
Yeah that's what I thought, too.

**Comment by mischnic** [comment]
Duplicate of https://github.com/parcel-bundler/parcel/issues/3523
