### ISSUE TITLE
Render function import for JSX is removed if it's not explicitly used

### ISSUE THREAD

**Issue by marcusball** [parcel-bundler/parcel#1487]
# 🐛 bug report

I am trying to use [Hyperapp](https://github.com/hyperapp/hyperapp) with JSX. I followed [this guide](https://blog.daftcode.pl/hyperapp-parcel-71823bd93f1c) for most of my set up. I'm not experienced with the JS so I'm sorry if I misdiagnosed this as a Parcel issue if it's actually a bug in a dependency or me misconfiguring something. 

Basically, hyperapp uses the `h` function for virtual-DOM creation, and I have configured babel to use that when transforming JSX. 

index.tsx: 
```js
import { h, app } from 'hyperapp';

const root = document.getElementById('root') as HTMLElement;

// Equivalent to: `const view = () => h('h1',{},'Hello world');`
const view = () => (
    <h1>Hello world</h1>
);

app({}, {}, view, root);
```

The problem is that when I run this in my browser, I will receive a `ReferenceError: h is not defined` error and nothing will render. 

However, the code will run properly if I have explicitly used the `h` function anywhere in code. This example will run fine: 

```js
import { h, app } from 'hyperapp';

const _ = h(''); // explicitly use `h`, even if it does nothing. 

const root = document.getElementById('root') as HTMLElement;

// Equivalent to: `const view = () => h('h1',{},'Hello world');`
const view = () => (
    <h1>Hello world</h1>
);

app({}, {}, view, root);
```

## 🎛 Configuration (.babelrc, package.json, cli command)

`.babelrc`: 

```js
{
    "presets": [
        "env"
    ],
    "plugins": [
        [
            "transform-react-jsx",
            {
                "pragma": "h"
            }
        ]
    ]
}
```

`package.json`:

```
{
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-plugin-transform-react-jsx": "^6.24.1",
    "babel-preset-env": "^1.7.0",
    "typescript": "^2.9.1"
  },
  "scripts": {
    "build": "parcel build src/index.html",
    "start": "parcel src/index.html",
    "dev": "parcel watch src/index.html",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "hyperapp": "^1.2.6"
  }
}
```

`tsconfig.json`:

```js
{
  "compilerOptions": {
    "target": "es5", /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017','ES2018' or 'ESNEXT'. */
    "module": "ESNext", /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    "lib": [
      "dom",
      "es2015",
      "es2015.collection"
    ], /* Specify library files to be included in the compilation. */
    "jsx": "preserve", /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
    "importHelpers": true, /* Import emit helpers from 'tslib'. */
    "strict": true, /* Enable all strict type-checking options. */
    "moduleResolution": "node", /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    "esModuleInterop": true /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
  }
}
```

### Commands 

`yarn start` and `yarn build` which alias to: 

`parcel src/index.html` and `parcel build src/index.html`.

## 🤔 Expected Behavior

The `h` function import should be included in the bundled code. 

## 😯 Current Behavior

The `h` function is not included. My assumption is that because the `h` import is not explicity used, it it being stripped as an unused import, even though it'll be used once the babel transform is complete. 

## 🔦 Context

This is mostly just annoying, but isn't a huge problem. Adding a dummy use of the function is hacky, but doesn't prevent me from getting work done. 

## 💻 Code Sample

See above, let me know if I left out any necessary files. 

`src/index.html`: 

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Example</title>
</head>

<body>
    <div id="root"></div>
    <script src="./index.tsx"></script>
</body>

</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | v10.3.0
| npm/Yarn         | Yarn 1.7.0
| Operating System | Linux archlabs 4.16.12-1-ARCH
| Typescript       | 2.9.1

**Comment by DeMoorJasper** [comment]
This is strange babel transformations occur before minification, there shouldn't be any code removal before that step.

Could you provide a minimal repo for reproduction?

I would say babel transforms are not being applied but than you wouldn't get `h is not defined` in the browser so it's probably not that

**Comment by marcusball** [comment]
All of the code snippets above are enough to reproduce the issue; I've attached an archive of them, let me know if an actual git repo would be preferrable. 

You should be able to just `npm install`/`yarn install` to set up the repo. 

When you run Parcel the issue _should be_ present; if you uncomment line 3 of `src/index.tsx` the code should run correctly. 

[problem-demo.tar.gz](https://github.com/parcel-bundler/parcel/files/2068619/problem-demo.tar.gz)

**Comment by marcusball** [comment]
I took a bunch of time today to dig through the code and eventually found that it was the Typescript compiler that was stripping the import line (https://github.com/Microsoft/TypeScript/issues/24731).
