### ISSUE TITLE
Documentation: Examples

### ISSUE THREAD

**Issue by philipodev** [parcel-bundler/parcel#149]
🙋 feature request

Hi, i think its time to provide basic examples for using parcel with `react`, `vue`, `angular` among others.
I'm thinking a simple folder-structured `/examples/react` with a `package.json`, `.babelrc` and `index.html` + `index.js`. 

What do you guys think?

I would love to contribute with a few examples.

**Comment by greghaygood** [comment]
Here's a React version! https://github.com/jaredpalmer/react-parcel-example

**Comment by DeMoorJasper** [comment]
Here's an angular example https://github.com/DeMoorJasper/Angular-Parcel-Boilerplate

**Comment by Raathigesh** [comment]
It would be really nice to aggregate all these examples in an example subdirectory like Next js does. https://github.com/zeit/next.js/tree/master/examples

Would be willing to help out in this effort.

**Comment by philipodev** [comment]
@Raathigesh next.js was accually whati had in mind. It have helped me alot.

**Comment by steveblue** [comment]
The Angular example linked above uses an extremely old version of Angular when it was in beta.

**Comment by one-aalam** [comment]
Here's a `Vue` version! https://github.com/rohitkrai03/vue-parcel-example

But as stated, this is using CDN (not `import Vue from 'vue'`) due to https://github.com/parcel-bundler/parcel/issues/8

**Comment by eXon** [comment]
Here is a react with ssr example: https://github.com/reactivestack/parcel-react-ssr

**Comment by davidnagli** [comment]
I’m happy to announce that we now have a `examples` repo!

Please feel free to submit a PR to your example on [the new repo](https://github.com/parcel-bundler/examples)

I’ll close this issue since it’s no longer necessary, but feel free to reach out if you have any more questions, comments or requests :)
