### ISSUE TITLE
Script tags are not executed in the global scope and do not work after bundling

### ISSUE THREAD

**Issue by gkjohnson** [parcel-bundler/parcel#1491]
# 🐛 bug report

Included vanilla javascript scripts are not executed in the global scope the way they are in a non-bundled, statically-served site.

## 🎛 Configuration (.babelrc, package.json, cli command)

No configuration.

Bundling a vanilla, static website.

## 🤔 Expected Behavior

A vanilla bundled website should behave the same before and after it's bundled.

#### includedScript.js
```js
var testVariable = 1000;
```
#### index.html
```html
<head><html>
    <script src="./includedScript.js" />
    <script>
        // Prints "1000" in static server
        // Undefined variable error when bundled
        console.log(testVariable);
    </script>
</html><body>
</body></html>
```

## 💁 Possible Solution

Execute normal included script tags in the global scope instead of scoping them. Required or otherwise imported scripts can still be scoped accordingly.

## 🔦 Context

Trying to bundle a static website for production and use older libraries that rely on global scope.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 8.6.0
| npm         | 5.3.0
| Operating System | Windows 10

**Comment by Tom-Julux** [comment]
Will be fixed in #1456

**Comment by zengxp0605** [comment]
I still occur this issue in version: 1.10.3

**Comment by gkjohnson** [comment]
I was also seeing that this was an issue.

**Comment by whentotrade** [comment]
same problem here. Any fix?

**Comment by hanshou101** [comment]
> I still occur this issue in version: 1.10.3

What my solution is : 
add --no-minify                in terminal command.

then my html works correctly .

**Comment by hanshou101** [comment]
> I was also seeing that this was an issue.

What my solution is :
add --no-minify in terminal command.

then my html works correctly .

**Comment by hanshou101** [comment]
> same problem here. Any fix?

What my solution is :
add --no-minify in terminal command.

then my html works correctly .
