### ISSUE TITLE
SVG import with code splitting

### ISSUE THREAD

**Issue by andrewBalekha** [parcel-bundler/parcel#1493]
# 🐛 bug report

when importing an SVG inside a component which is a part of a dynamic import (split code), The SVG file name in `public folder` is different with what I get in a component.

## 🎛 Configuration (.babelrc, package.json, cli command)

react-app preset

## 🤔 Expected Behavior

The SVG file name should be same as in `public folder`

## 😯 Current Behavior

in public folder, I see a file with a name `js.[hash].svg`, but I get a different file name in component `file-name.[hash].svg`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | latest
| Node             | 8
| npm/Yarn         | yarn
| Operating System | OS

**Comment by ACXgit** [comment]
I think this is the same problem I experienced today, see [my comment here](https://github.com/parcel-bundler/parcel/issues/1756#issuecomment-421399258) in a similar issue.

**Comment by vqrulane** [comment]
I can confirm that behaviour on Node 10, running on Linux, with parcel version 1.10.2.

**Comment by ACXgit** [comment]
It seems fixed with v1.10.3 👍
