### ISSUE TITLE
File import crashes if the same file is required on js and on css

### ISSUE THREAD

**Issue by ericaprieto** [parcel-bundler/parcel#1495]
# 🐛 bug report

Can't find module if I require the same file on js and css

## 🎛 Configuration (.babelrc, package.json, cli command)
No specific configuration

## 🤔 Expected Behavior
The file should be successfully imported on both js and css

## 😯 Current Behavior
The js require fails on the browser

## 🔦 Context
I want to use the same image on js and css

## 💻 Code Sample
```javascript
// index.js
require("./style.css")
require("./some-image.svg")
```

```css
/* style.css */
body {
  background: url(./some-image.svg)
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1 |
| Node             | v8.11.1 |
|Yarn         |  1.6.0|
| Operating System | MacOS |

**Comment by jestho** [comment]
Seems to work if you put the entry script above the html. Not necessarily a valid option for many people, but should give some clues to what's going on.

**Comment by jestho** [comment]
Seems to work if you add the entry script tag above the html (eg. in `<head>`). Not necessarily a viable option for most, but should give a clue on what's going on.
