### ISSUE TITLE
question about the repository

### ISSUE THREAD

**Issue by MAPESO** [parcel-bundler/parcel#1497]
Hi guys, I would like to have these options in my repository
how can I do this 😸 
<img width="1280" alt="screen shot 2018-06-05 at 10 39 31 pm" src="https://user-images.githubusercontent.com/16585386/41017539-e9bc5abe-691a-11e8-84cf-975dc1e4d8aa.png">

**Comment by Tom-Julux** [comment]
Add an ISSUES.md file to your repo. I think you will probably figure out the rest on your own.

**Comment by DanielRuf** [comment]
Clone the repo and take a look at the .github folder.

**Comment by MAPESO** [comment]
@DanielRuf @tb Thanks for the help guys. I was able to implement it in my repository ❤️

**Comment by MAPESO** [comment]
it's time to close this issue 😄

**Comment by DanielRuf** [comment]
Also see https://blog.github.com/2018-05-02-issue-template-improvements/
