### ISSUE TITLE
Is there any way to use env variables?

### ISSUE THREAD

**Issue by MAPESO** [parcel-bundler/parcel#1498]
# ❔ Question

Hi Guys 😸 

I would like to use Environment Variables in my Parcel application.

Webpack offers a plugin [EnvironmentPlugin](https://webpack.js.org/plugins/environment-plugin/)

```Parcel``` offers something similar? ❤️ 

## 🔦 Context

use env variables with Parcel :)

## 💻 Code Sample

that plugin allows me to do this in my webpack application
![40679652-61ae9244-6349-11e8-96bb-0f29a6b7130b](https://user-images.githubusercontent.com/16585386/41018136-f7950c8c-691d-11e8-9ad7-e90b7a8177f3.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 10.3.0
| npm/Yarn         | 1.7.0
| Operating System | macOS Hig Sierra(10.13.5)

**Comment by DeMoorJasper** [comment]
We support environment files natively

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MAPESO** [comment]
@DeMoorJasper Hi 👋 guide on how to use it? I'm interested in using it in the same way that I can use it in webpack.

It would be great if you could give me an example 🙏

**Comment by minhchu** [comment]
@MAPESO just drop your `.env` file in your project root directory. Parcel has built in support for [dotenv](https://github.com/motdotla/dotenv)

**Comment by MAPESO** [comment]
@minhchu I need to use files with a ```.json``` extension :(

**Comment by minhchu** [comment]
Why do you need that :thinking: In the end, you still want to get your `process.env.TOKEN`. You can achieve the same thing by using `dotenv` :D

**Comment by DeMoorJasper** [comment]
Parcel endorses standardised formats, as we don’t want to make the users dependent of one tool like webpack does with it’s custom config that contains everything. Therefore a custom .json config will be unlikely

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MAPESO** [comment]
@DeMoorJasper @minhchu thank you for clarifying the doubt 😸

**Comment by MAPESO** [comment]
I'm going to close the issue :)

**Comment by bogdansoare** [comment]
I get this error
```
module.js:549
    throw err;
    ^

Error: Cannot find module 'dotenv-expand'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at dotenvFiles.forEach.dotenvFile (/Users/bogdansoare/Hacking/design-system/node_modules/react-scripts-parcel/config/env.js:41:5)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/bogdansoare/Hacking/design-system/node_modules/react-scripts-parcel/config/env.js:39:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
error Command failed with exit code 1.
```

**Comment by dumptyd** [comment]
Hi, is it possible to inject env vars in html files?
