### ISSUE TITLE
It installs vue-hot-reload-api in dependencies instead of devDependencies

### ISSUE THREAD

**Issue by tylerlong** [parcel-bundler/parcel#1499]
I am building a Vue.js project with Parcel.

When I `parcel index.html`, it installs `vue-hot-reload-api` for me.

However, it is installed as `dependencies` instead of `devDependencies`.

**Comment by burlesona** [comment]
Are you getting `vue-loader hot reload is only compatible with Vue.js 1.0.0+.` as well? I just started a new vue project and it's doing that for me, so HMR is not working...

**Comment by tylerlong** [comment]
@burlesona Nope

**Comment by DeMoorJasper** [comment]
Parcel currently installs every require or import in dependencies and every tool required for building in devDependencies, you can move it manually as there is not way for parcel to perfectly predict what it'll be.
