### ISSUE TITLE
Move to dart-sass instead of node-sass

### ISSUE THREAD

**Issue by Positive07** [parcel-bundler/parcel#1509]
# 🙋 Feature Request

Since late march dart-sass reached the [stable release 1.0.0](https://github.com/sass/dart-sass/releases/tag/1.0.0), marking the start of the [deprecation of ruby-sass](http://sass-lang.com/ruby-sass) (not libsass though).

Although node-sass is based on libsass and will continue to be updated with the latest patch and fixes, it will take more time for this features to land while dart-sass will receive them immediately and has the benefit of compiling to pure JS without the need of native modules.

Dart-sass is now at [version 1.5.1](https://github.com/sass/dart-sass/releases/tag/1.5.1) (as of 8/6/2018) and in nice shape to be used in production. [NPM Link](https://www.npmjs.com/package/sass)

## 🤔 Expected Behavior

Parcel should be able to detect the `sass` module instead of `node-sass`, and maybe fallback to it, if needed, though it may be a good idea to drop it altogether and look forward to #1253 

## 😯 Current Behavior

Parcel incorrectly detects `sass` and asks for `node-sass` instead, failing to compile `.sass/.scss` files

## 💁 Possible Solution

Luckily `sass` is [API compatible](https://github.com/sass/dart-sass#javascript-api) with `node-sass` so it should be as easy as changing the 2 occurrences of `node-sass` to `sass` at [package.json line 90](https://github.com/parcel-bundler/parcel/blob/master/package.json#L90) and [SASSAsset.js line 16](https://github.com/parcel-bundler/parcel/blob/master/src/assets/SASSAsset.js#L16)

**Comment by DeMoorJasper** [comment]
Dart sass is slower and would require the dart runtime right?

**Comment by Positive07** [comment]
Citing [Dart Sass performance](https://github.com/sass/dart-sass/blob/master/perf.md)
> Dart Sass **on Node** lags behind, particularly when many extends are in use. It's still faster than it was last measurement, but it would probably pay dividends to do some **JS-specific benchmarking** and optimization to try to bring the speed closer to that of the Dart VM. The majority of our users run Dart Sass **through JS**, so while it's good that they have a path to better performance with the same semantics, improving the baseline performance is important.

So yeah it's slower, but it's pure JS. I also saw mentions of `pure JavaScript version` [here](https://github.com/sass/dart-sass/blob/master/package/README.npm.md#see-also)

Also the compiled Dart Sass standalone (which doesn't require the Dart VM) [seems to be on par to libsass and may be faster for some test cases](https://github.com/sass/dart-sass/blob/master/perf.md#conclusions)

**Comment by DeMoorJasper** [comment]
Pure JS isn’t necessarily better, the major issues we currently have with sass are unrelated with it being in C++.
Idk if it’s worth the tradeoff would indeed be usefull to have someone from sass shim a light on this issue

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sindresorhus** [comment]
@DeMoorJasper You should at least let people be able to choose `dart-sass`? It has additional benefits like not requiring a native addon.

There are also a myriad of issues with using `node-sass` with Parcel:

- https://github.com/parcel-bundler/parcel/issues/1331 (closed but still an issue for many)
- https://github.com/parcel-bundler/parcel/issues/1836

// @nex3

**Comment by DeMoorJasper** [comment]
@sindresorhus I thought we fixed the freezing issue, that’s why I thought this issue was pretty unnecessary, but now that someone has reported it again I’m pretty sure it’s a good idea to support dart-sass, still unfortunate that they don’t have a solid sass-js or something

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
