### ISSUE TITLE
Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by June215** [parcel-bundler/parcel#1510]
"build": "parcel build index.html --no-minify -d build --public-url ./",
yarn build打包后，在android个别手机上出现，Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode。
请问这是什么原因呢？看着好多node_modules里的const let语法没有转成es5。

我尝试了很多插件都解决不了这个问题。
"dependencies": {
    "@types/node": "^9.6.0",
    "@types/react": "^16.0.30",
    "@types/react-dom": "^16.0.3",
    "@types/react-redux": "^5.0.15",
    "@types/react-router": "^4.0.23",
    "babel-loader": "^7.1.4",
    "babel-runtime": "^6.26.0",
    "d3": "^3.0.0",
    "parcel": "^1.8.1",
    "react": "^16.3.0",
    "react-dom": "^16.2.0",
    "uglify-es": "^3.3.9"
  },
  "devDependencies": {
    "@aos/aos-entity": "^1.0.39",
    "babel-core": "^6.26.3",
    "babel-eslint": "^8.2.3",
    "babel-plugin-component": "^1.1.1",
    "babel-plugin-react-require": "^3.0.0",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.2",
    "babel-plugin-transform-react-jsx": "^6.24.1",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-plugin-transform-strict-mode": "^6.24.1",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-preset-stage-1": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "babel-preset-stage-3": "^6.24.1",
    "babel-register": "^6.26.0",
    "clipboard": "^2.0.1",
    "css-modules": "^0.3.0",
    "echarts": "^4.1.0",
    "echarts-for-react": "^2.0.8",
    "eslint": "^4.19.1",
    "lodash": "^4.17.5",
    "node-sass": "^4.9.0",
    "parcel-bundler": "^1.8.1",
    "react": "^16.3.0",
    "react-document-title": "^2.0.3",
    "react-redux": "^5.0.7",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "redux": "^3.7.2",
    "redux-saga": "^0.16.0",
    "swiper": "^4.3.3",
    "typed-css-modules": "^0.3.1",
    "typescript": "^2.8.3",
    "uglify-js": "^3.4.0"
  },

求救。。。

**Comment by June215** [comment]
代码是用react + typescript + parcel开发和打包的。

**Comment by GrosSacASac** [comment]
put
"use strict";
at the top of your .js file

**Comment by jeyj0** [comment]
Is this issue still relevant? If so, it might be helpful to ask in English to reach a bigger audience @june215. If it is not relevant anymore, consider closing this issue. :)
