### ISSUE TITLE
output JS file names don´t match original ones

### ISSUE THREAD

**Issue by jluisgarcia** [parcel-bundler/parcel#1511]
# ❔ Question

I can´t seem to find a way to keep original JS file names after running "watch" command, shown in the "Context" section.
I am expecting "index.4261903b.js".
Instead, I get "assets.4261903b.js"
Is this a bug or is it just the way I run the "watch" command?

## 🔦 Context

I am running this CLI command from the root project folder:
<code>
parcel watch ./assets/index.html --no-source-maps --public-url ./
</code>

This is my original file structure
<pre>
<code>
root
├── ...       
├── assets                    
│   └── index.html          
│   └── index.js      
├── package.json   
└── ...
</code>
</pre>

This is my file structure after running "watch" command shown above.
<pre>
<code>
root
├── ...       
├── assets                    
│   └── index.html          
│   └── index.js      
├── dist                    
│   └── index.html          
│   └── assets.4261903b.js          
├── package.json   
└── ...
</code>
</pre>

## 💻 Code Sample
Thi is my original index.html, inside "assets" folder.
<pre>
<code>
&lt;!DOCTYPE html&gt;
&lt;html lang=&quot;en&quot;&gt;
&lt;head&gt;
  &lt;title&gt;parcel test&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
  &lt;div id=&quot;message&quot;&gt;&lt;/div&gt;
  &lt;script src=&quot;./index.js&quot;&gt;&lt;/script&gt;
&lt;/body&gt;
&lt;/html&gt;
</code>
</pre>

And this is index.html created by parcel, inside "/dist" folder, after running "watch" command shown above.

<pre>
<code>
&lt;!DOCTYPE html&gt;
&lt;html lang=&quot;en&quot;&gt;
&lt;head&gt;
  &lt;title&gt;parcel test&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
  &lt;div id=&quot;message&quot;&gt;&lt;/div&gt;
  &lt;script src=&quot;assets.4261903b.js&quot;&gt;&lt;/script&gt;
&lt;/body&gt;
&lt;/html&gt;
</code>
</pre>

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |   1.8.1
| Node             |  8.11.1
| npm          | 6.1.0
| Operating System | Win 8.1

**Comment by DeMoorJasper** [comment]
This is how the naming strategy works, it takes the hash and appends the parent folders name
