### ISSUE TITLE
Can't import assets on typescript

### ISSUE THREAD

**Issue by ellipticaldoor** [parcel-bundler/parcel#1514]
# 🐛 bug report

When I try to load an asset inside typescript I get undefined instead of the route for the file.

``` js
import characterImage from '@client/assets/img/character.png'
console.log(characterImage) // undefined
````
The code above works in normal .js

## 🎛 Configuration (.babelrc, package.json, cli command)

This is my .babelrc
```js
{
  "env": { "browser": true },
  "ignore": [],
  "plugins": [
    ["transform-runtime", {
      "polyfill": false,
      "regenerator": true
    }],
    ["module-resolver", {
      "alias": {
        "@client": "./src/client",
        "@server": "./src/server"
      }
    }],
    "transform-object-rest-spread",
    "ramda"
  ],
  "presets": [
    "env"
  ]
}
```

## 🤔 Expected Behavior

Import should return the string for the url of the asset.

## 😯 Current Behavior

I get undefined when trying to import. 

## 💁 Possible Solution

Maybe it can help but it looks like require works as expected
``` js
const characterImage = require('@client/assets/img/character.png')

console.log(characterImage) // /character.f3137b4d.png
```

| Software         | Version(s) |
| ---------------- | ---------- |
```js
{
    "parcel-bundler": "^1.8.1",
    "typescript": "^2.9.1"
}
```

**Comment by mohsen1** [comment]
1. Add a file called `declaration.d.ts` anywhere in your project.
2. Add this line in there: `declare module "*.png"`
3. Add a module declaration for other asset types if you need to

**Comment by ellipticaldoor** [comment]
@mohsen1 I did that, that fixes the problem with types. The thing is that the value of the import is undefined

**Comment by mohsen1** [comment]
TypeScript doesn't know about runtime value. if you're getting runtime value of undefined you're having an issue unrelated to TypeScript

**Comment by ellipticaldoor** [comment]
Oh! I removed the plugin
> "parcel-plugin-typescript"
and the asset imports started to work.

I moved this issue to the plugin repo https://github.com/fathyb/parcel-plugin-typescript/issues/42
