### ISSUE TITLE
Outdated documentation for Babel transforms?

### ISSUE THREAD

**Issue by jluisgarcia** [parcel-bundler/parcel#1517]
# ❔ Question

I have found that official instructions to use Babel + Parcel, may be wrong or misleading.
This is a text fragment from Parcel's web page.
<pre>
<code>
Install presets and plugins in your app:
yarn add babel-preset-env
</code>
</pre>

These instructions can be found [here](https://parceljs.org/transforms.html), within the Babel section.

Since Babel already includes the babel-preset-env plugin, as a dependency, the only thing you need to add, is a .babelrc config file.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  n/a
| Node             | n/a
| npm/Yarn         | n/a
| Operating System | n/a

**Comment by DeMoorJasper** [comment]
Wrong repo: https://github.com/parcel-bundler/website
