### ISSUE TITLE
how to configure map file path?

### ISSUE THREAD

**Issue by slmjkdbtl** [parcel-bundler/parcel#1518]
build
```javascript
new Bundler("./public/src/main.js", {
    outDir: "./public/dist"
});
```

html
```html
<script src="/dist/main.js">
```

server
```javascript
app.use(static(path.join(__dirname, "/public")));
```

and everything works perfectly but the `main.map` file location declared in the bundled js file is not correct

changing
```javascript
//# sourceMappingURL=/main.map
```
to
```javascript
//# sourceMappingURL=/dist/main.map
```
works

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 10.3.0
| npm/Yarn         | 1.7.0
| Operating System | macOS High Sierra 10.13.4

**Comment by DeMoorJasper** [comment]
you're looking for `publicUrl: '/dist/'`

**Comment by slmjkdbtl** [comment]
@DeMoorJasper Oh thanks! I saw that before but thought that's just for parcel's server..
