### ISSUE TITLE
Vue Application breaks when minifing 

### ISSUE THREAD

**Issue by DaveO-Home** [parcel-bundler/parcel#1522]
# 🐛 bug report

App works for minify: false
Errors are not helpful - 
TypeError: r is undefined
e@http://localhost:9876/base/dist_test/parcel/main.3302dc0f.js:187:1
or
"TypeError: t.default is undefined"

found in

---> \<ToolsC>
       \<App>
         \<Root>'

## 🎛 Configuration (.babelrc, package.json, cli command)

You can find the code @ github.com/DaveO-Home/embedded-acceptance-tests-vue
in public/parcel/build.....the build uses the api under gulp
```js
{
  "presets": ["env"]
}
const options = {
        production: isProduction,
        outDir: '../../' + dist,
        outFile: isProduction ? 'testapp.html' : 'testapp_dev.html',
        publicUrl: './',
        watch: watch,
        cache: !isProduction,
        cacheDir: '.cache',
        minify: false, // isProduction,
        target: 'browser',
        https: false,
        logLevel: 3, // 3 = log everything, 2 = log warnings & errors, 1 = log errors
        // hmrPort: 3080,
        sourceMaps: !isProduction,
        // hmrHostname: 'localhost',
        detailedReport: isProduction
    };
```

## 🤔 Expected Behavior
The production bundle should behave like the test bundle

## 😯 Current Behavior
When minify is set to true, the app fails, works with false

## 💁 Possible Solution
Question: is there a config file for minify?

## 🔦 Context
Doing E2E testing with Karma, Jasmine, Vue, Parcel(and other bundlers)

## 💻 Code Sample
See githup url above

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 8.9.4
| npm/Yarn         |  npm - 6.1.0
| Operating System | Fedora 28

**Comment by SteffenL** [comment]
How about trying Parcel with the latest code in the master branch?

**Comment by DaveO-Home** [comment]
thanks @SteffenL - used the .uglifyrc option to solve  {mangle: false}

**Comment by DaveO-Home** [comment]
Oops, mangle: false did not fix it.

**Comment by SteffenL** [comment]
@DaveO-Home If it is the same issue as in #1362 then I am afraid that the only suggestion I can offer is to disable minification completely (`--no-minify`) or use the latest code until a new version is released.

**Comment by DaveO-Home** [comment]
@SteffenL  I tried linking master into my node_modules but failed.  How do you use master?

**Comment by DaveO-Home** [comment]
@SteffenL - Ok, I made the 3 line mod and it works...however, I'll wait for the next release.  I know I'll forget about the change.

**Comment by SteffenL** [comment]
I would just do something like this:
```
npm install -g github:parcel-bundler/parcel#master
```

If you put it in `package.json`, you may have to first delete parcel from `node_modules` and delete `package-lock.json`.

**Comment by DaveO-Home** [comment]
Oh, I used @ instead of # (didn't know about #)
