### ISSUE TITLE
If it is better to ignore not terminate. "Path must be a string. Received null."

### ISSUE THREAD

**Issue by Tokitsukaze** [parcel-bundler/parcel#1530]
# 🙋 feature request

I'm not sure if this should be a bug or feature.

When i write 
```html
<img src="">
```
in HTML (I know this may be not reasonable), parcel throw a Exception.

## 🤔 Expected Behavior

```
√  Built in xx ms.
```

## 😯 Current Behavior

```
× ... Path must be a string. Received null ...
```

## 💁 Possible Solution

Ignore or give a WARNING.

## 🔦 Context

When i write a webpage, usually i write the 'skeleton' first, so the layout is clear.
```
just like one page has only <div>, <span> and some replaced element like <img>, <input>, which have styles like
* { background-color: rgba(0, 0, 0, .1) } 
or, effects layout.
```

**Comment by abhijitgujar86** [comment]
i agree with suggestion
