### ISSUE TITLE
How can I use the built module in browser via `<script src="...">`

### ISSUE THREAD

**Issue by wxs77577** [parcel-bundler/parcel#1533]
/src/index.js
```javascript
export default class Client {

}
```

### I need to use it in the traditional way: 

test.html
```html
<script src="./dist/client.min.js"></script>
<script>
var client = new Client()
</script>
```

**Comment by DeMoorJasper** [comment]
Parcel can use html as an entrypoint and if you use js as an entrypoint it maintains the filename

**Comment by SteffenL** [comment]
You can use the `--global` parameter for Parcel:
```
parcel build --global Client [...]
```

`Client` will be available as `window.Client` or `Client`.

**Comment by wxs77577** [comment]
Thanks @SteffenL 

it works. But  it doesn't work with es6 module until I add the following code:
```javascript
if (typeof module !== 'undefined') {
  module.exports = BaasClient
}
```

Did I miss something?

**Comment by SteffenL** [comment]
@wxs77577 Do you mean that it does not work with only `module.exports = BaasClient`?
