### ISSUE TITLE
build freeze [disaster]

### ISSUE THREAD

**Issue by coffeeowl** [parcel-bundler/parcel#1537]
# 🐛 bug report

There already were some issues reported when parcel gets stuck building projects, currently I have 3 projects with parcel in development. 2 of them run more or less fine but another one has started to have issues with building. What's even worse most of the time it happens when we run builds on Heroku. It is quite annoying to watch heroku timeout builds and fail tests all the time. This also interferes with our PRs on gihub and review apps.

I don't want to go back to webpack but my project manager is going to eat me soon if the issue is not resolved. This also means that parcel will never be chosen for new projects. It doesn't matter how many nice features you have if none of them are usable due to the issue.

## 🎛 Configuration (.babelrc, package.json, cli command)

Nothing new really, people have posted all the details in other issues. I don't know why they are closed. The only difference is that the project that fails the most is on typescript

```
    "node-sass": "^4.9.0",
    "parcel-bundler": "^1.8.1",
    "parcel-plugin-typescript": "^0.7.1",
    "tslint": "^5.10.0",
    "tslint-react": "^3.6.0",
    "typescript": "^2.8.3"
```

```
"start:dev": "parcel --no-autoinstall -p 3000 src/index.html -d build",
```

## 🤔 Expected Behavior

parcel should do what it promises to do and that is - build projects.

## 😯 Current Behavior

Disaster

## 💁 Possible Solution

I think you need to revise you current approach to building, whatever it is, it is not working given how many attempts to fix the issue were there. On Windows many people I asked can't build projects at all.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 10.1.0
| npm/Yarn         | 6.1.0/5.6.0 (both npm)
| Operating System | Linux 4.16.13-1-ARCH (local) and whatever they have on Heroku

**Comment by lysla** [comment]
I've been stuck with the same issue, but I think the https://github.com/parcel-bundler/parcel/pull/1390 pull request should solve most of the freezing causes. I can see everytime if I remove my scss import's from the js it never freezes for me (also a Win user). Is there an ETA for the release which will include the sass async feauture?
Thanks for your efforts!

**Comment by coffeeowl** [comment]
I don't think node-sass is the sole culprit. I have node-sass with scss files on 2 projects, one runs fine, another one - well, we can't build it today on Heroku at all. We haven't introduced any new deps since yesterday, only some new code we wrote. So, no idea why all of a sudden.

**Comment by lysla** [comment]
ahah, oh well, just on time https://medium.com/@devongovett/parcel-v1-9-0-tree-shaking-2x-faster-watcher-and-more-87f2e1a70f79 apparently, hopefully this will solve everything. good job @ everyone who worked on it ❤️

**Comment by DeMoorJasper** [comment]
Try 1.9 just to make sure it's not node-sass

**Comment by coffeeowl** [comment]
I'll try tomorrow, but... https://github.com/parcel-bundler/parcel/issues/1539
we use this one

**Comment by coffeeowl** [comment]
We have updated to 1.9 and we can build on heroku again. Things look better :pray: :crossed_fingers:
