### ISSUE TITLE
Can It Support Typescript?

### ISSUE THREAD

**Issue by jimmycarry** [parcel-bundler/parcel#154]
As My Title If It Support Typescript How To Config It

**Comment by DeMoorJasper** [comment]
It supports typescript, no need to config anything though.
Just point it to a index.html or whatever html file that has a script tag containing the typescript entrypoint and everything should work automagically

**Comment by DanielRuf** [comment]
Or directly at the index.js or is a .html file always required?

**Comment by DeMoorJasper** [comment]
It can also be an index.js or pointing it directly at a Typescript file also works

**Comment by DanielRuf** [comment]
Right, because this also worked for me as our projects are not included in an index.html document at compile time.

I am not sure if it was mentioned in the docs / get startet that the given entry file can be also one of the many supported ecmascript subsets.

Just saw the example with the index.html.

**Comment by azu** [comment]
I've created  minimum typescript example.

- [azu/parcel-typescript-example: A minimum TypeScript app with Parcel Bundler.](https://github.com/azu/parcel-typescript-example "azu/parcel-typescript-example: A minimum TypeScript app with Parcel Bundler.")

**Comment by DeMoorJasper** [comment]
@jimmycarry if these answers resolved your question, could you close the issue?

**Comment by jimmycarry** [comment]
@DeMoorJasper OK

**Comment by pke** [comment]
Seems like one needs to rename the file from *.ts to *.tsx to support the JSX syntax? Otherwise parcel will complain " Unterminated regular expression" for the first encountered JSX tag.

**Comment by tsiq-swyx** [comment]
hello this exists now! https://github.com/sw-yx/create-react-app-parcel-typescript

**Comment by janat08** [comment]
I tried converting nodejs to parcel for this and dist folder just skipped ts files.

**Comment by janat08** [comment]
I suppose using VSCode is good enough to identifying type errors. I belief typescript itself doesn't actually stop compilation on error.

**Comment by DmitryOlkhovoi** [comment]
It doesn't work without configurations if you want to use react and TS
