### ISSUE TITLE
Wrong version of Vue Loader included and HMR doesn't work out of the box

### ISSUE THREAD

**Issue by burlesona** [parcel-bundler/parcel#1543]
# 🐛 bug report

When starting a brand new Vue project via Parcel, HMR was not working out of the box. Rather I got the following warning:

```
[HMR] vue-loader hot reload is only compatible with Vue.js 1.0.0+
```

This is dicussed in this issue on Vue Loader: https://github.com/vuejs/vue-loader/issues/214

Just to see if it would fix things I explicitly added vue loaded to my package via `yarn add vue-loader`, which resulted in `15.2.4`.

Running parcel again HMR worked as expected.

## 🤔 Expected Behavior

Parcel works out of the box because it's amazing 😄 

## 😯 Current Behavior

HMR didn't work as described in the bug report, with that console warning displayed instead.

## 💁 Possible Solution

Manually adding the latest vue-loader version fixed it for me.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |   Tested this on both 1.8.1 and 1.9.0, both had same behavior
| Node             | 8.11.2
| npm/Yarn         | 1.6.0
| Operating System | MacOS 10.13.4

**Comment by DeMoorJasper** [comment]
Parcel doesn't use and shouldn't use vue-loader. Not sure why this bug is showing up.
Could you create a test repo for us to play around with and see why this occurs?

**Comment by burlesona** [comment]
@DeMoorJasper done: https://github.com/burlesona/parcel-bundler-vue-bug

Steps to reproduce are in the readme. Interestingly when I created this minimal case adding Vue Loader no longer fixes the behavior. It still silences the warning, but now saving files results in an error when HMR is attempted.
