### ISSUE TITLE
v1.9.0 doesn't support importing from './drivers/*/*'

### ISSUE THREAD

**Issue by wxs77577** [parcel-bundler/parcel#1545]
It's ok in v1.8.0, but it's broken when I upgrade parcel-bundler to v1.9.0

```javascript
import Drivers from './drivers/*/*'
```

**Comment by KeineLimonade** [comment]
There was a change in the resolving of glob assets. Change the import to `import Drivers from './drivers/*/*.*'`

**Comment by abellion** [comment]
Adding `.*` worked for us ; sad to see a BC break

**Comment by wxs77577** [comment]
@KeineLimonade Thanks a lot, not it works.
