### ISSUE TITLE
Error ENOENT and hang on parcel 1.9.0 using Vuetify À-la-carte

### ISSUE THREAD

**Issue by aldrinmartoq** [parcel-bundler/parcel#1546]
# 🐛 bug report

We are using Vuetify [À la carte](https://vuetifyjs.com/en/guides/a-la-carte), upgraded to parcel 1.9.0 and the build fails with an ENOENT: no such file or directory error. Once the error appears, parcel hangs. This means `parcel watch` does not update anymore.

This may be a bug related to #1397.

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json (updated):

```js
{
  "name": "parcel-vuetify-error",
  "version": "1.0.0",
  "description": "Bug in parcel-bundler (Error writing to cache)",
  "main": "index.html",
  "author": "Aldrin Martoq",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "vue": "^2.5.16",
    "vue-hot-reload-api": "^2.3.0",
    "vuetify": "^1.0.19"
  },
  "devDependencies": {
    "@vue/component-compiler-utils": "^2.0.0",
    "parcel-bundler": "^1.9.0",
    "pug": "^2.0.3",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "vue-template-compiler": "^2.5.16"
  }
}
```

## 🤔 Expected Behavior

There should be no errors writing to the cache, here is Vuetify without a la carte:

```
$ rm -fr .cache; node_modules/.bin/parcel build --log-level 3 src/index.full.html | tee
⏳  Building...

⏳  Building index.full.html...
⏳  Building main.full.js...
⏳  Building vue.runtime.esm.js...
⏳  Building vuetify.js...
⏳  Building vuetify.min.css...
⏳  Building App.vue...
⏳  Producing bundles...
⏳  Packaging...
✨  Built in 8.71s.

dist/main.full.4243f518.js     294.18 KB    8.00s
dist/main.full.841574f8.css    244.46 KB    7.79s
dist/index.full.html               394 B    541ms
dist/main.full.e237299c.map          0 B     82ms
```

## 😯 Current Behavior

Here is Vuetify using a la carte, with the error:

```
$ rm -fr .cache; node_modules/.bin/parcel build --log-level 3 src/index.a-la-carte.html | tee
⏳  Building...

⏳  Building index.a-la-carte.html...
⏳  Building main.a-la-carte.js...
⏳  Building vue.runtime.esm.js...
⏳  Building app.styl...
⏳  Building App.vue...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building index.js...
⏳  Building index.js...
🚨  /Users/amartoq/proj/vuejs/sandbox/parcel-vuetify-error-writing-to-cache/node_modules/vuetify/src/stylus/app.styl: ENOENT: no such file or directory, open '/Users/amartoq/proj/vuejs/sandbox/parcel-vuetify-error-writing-to-cache/node_modules/vuetify/src/stylus/settings/*
ENOENT: no such file or directory, open '/Users/amartoq/proj/vuejs/sandbox/parcel-vuetify-error-writing-to-cache/node_modules/vuetify/src/stylus/settings/*'
```

And **parcel hangs** here.

## 💁 Possible Solution

I'm sorry, I don't know how to help with this issue.

## 🔦 Context

We have to go back to parcel 1.8.1, because `parcel watch` hangs. This may be a bug related to #1397.

## 💻 Code Sample

I just upgraded the packages from the same sample code:

[https://github.com/aldrinmartoq/parcel-vuetify-error-writing-to-cache](https://github.com/aldrinmartoq/parcel-vuetify-error-writing-to-cache)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.0
| Node             | 8.9.4
| Yarn         | 1.7.0
| Operating System | Mac OS X 10.13.5

Thanks.

**Comment by DeMoorJasper** [comment]
It appears the cache error re-appeared, the pr to fix this is still in prs so once that’s merged it should work perfectly

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aldrinmartoq** [comment]
I'm sorry to keep bothering you, but the error is still present. Just updated to parcel 1.9.7, an this is the log:

c:parcel-vuetify-error-writing-to-cache amartoq$ rm -fr .cache; node_modules/.bin/parcel build --log-level 3 src/index.a-la-carte.html  | tee
🚨  /Users/amartoq/tmp/parcel-vuetify-error-writing-to-cache/node_modules/vuetify/src/stylus/app.styl: ENOENT: no such file or directory, open '/Users/amartoq/tmp/parcel-vuetify-error-writing-to-cache/node_modules/vuetify/src/stylus/settings/*
ENOENT: no such file or directory, open '/Users/amartoq/tmp/parcel-vuetify-error-writing-to-cache/node_modules/vuetify/src/stylus/settings/*'

I have updated the sample code that replicates the bug: 
https://github.com/aldrinmartoq/parcel-vuetify-error-writing-to-cache

**Comment by aldrinmartoq** [comment]
Hi @DeMoorJasper @devongovett , it seems you are not looking this bug anymore, do I have to report a new one o how can I reopen this one?

Thanks.
