### ISSUE TITLE
Code splitting not working with Typescript

### ISSUE THREAD

**Issue by reflog** [parcel-bundler/parcel#1547]
# 🐛 bug report

Parcel doesn't generate chunks for dynamic imports when using typescript.

Here's an example:

1. A project in JS that works: https://github.com/a-adroit/reacappwithparcel/
2. Same project in TS that **doesn't** work  https://github.com/reflog/parcel_ts_chunk_prob

## 🎛 Configuration (.babelrc, package.json, cli command)

No custom config

## 🤔 Expected Behavior

Chunks should be generated

## 😯 Current Behavior

only one bundle is generated

**Comment by KeineLimonade** [comment]
Typescript, by default, bundles all imports into a single file. Add a tsconfig similar to this one to the project:
```json
{
    "compilerOptions": {
        "target": "esnext",
        "sourceMap": true,
        "module": "es6"
    }
}
```

**Comment by reflog** [comment]
Thanks @KeineLimonade, using this switch actually works!
**But** when I try to use that tsconfig, I am getting the following errors in the IDE:
```
[ts] Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.
```
This is extremely confusing :)

**Comment by reflog** [comment]
ok. got it working with:
```
{
  "compilerOptions": {
    "target": "es2018",
    "sourceMap": true,
    "module": "esnext",
    "jsx": "preserve",
    "lib": ["esnext"]
  }
}
```

**Comment by guohuihuiguo** [comment]
我的这个问题还是存在 
我已经按照上面的方法加过了  但是还是存在

**Comment by davibe** [comment]
if this is a fix it should be the parcel.js default. However, for me this is not fixing anything.

**Comment by 1saf** [comment]
The tsconfig is not fixing anything either. I am having the same issue in a typescript project with react router as well.
