### ISSUE TITLE
Sugestion: facebook watchman for watch file changes

### ISSUE THREAD

**Issue by mateuspv** [parcel-bundler/parcel#1550]
Hello,
I remembered that `ember-ci` uses `watchman` from facebook for watching files,
they say that `performs well on extremely massive file trees`, please take a look, maybe you guys find it useful.

References:
https://github.com/facebook/watchman
https://ember-cli.com/user-guide/#watchman

Thanks!

**Comment by DeMoorJasper** [comment]
Duplicate #889
