### ISSUE TITLE
[TreeShake] Reference error $<NUMBER>$exports is not defined if "--experimental-scope-hoisting" flag is used

### ISSUE THREAD

**Issue by sujith97** [parcel-bundler/parcel#1552]
# 🐛 bug report

Browser complains about the undefined variable `$<NUMBER>$exports` which looks like the bundled output [here](https://medium.com/@devongovett/parcel-v1-9-0-tree-shaking-2x-faster-watcher-and-more-87f2e1a70f79).

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    "env",
    "react"
  ],
  "plugins": [
    "babel-plugin-styled-components",
    "react-hot-loader/babel",
    "transform-class-properties",
    "transform-object-rest-spread"
  ]
}
```

## 🤔 Expected Behavior

It should build and have no issues as when I use parcel build without the tree shaking flag.

## 😯 Current Behavior

Builds fine but browser complains:
`Uncaught ReferenceError: $37$exports is not defined`

## 💁 Possible Solution

Needs research.

## 🔦 Context

Just the usual parcel production build:
```
parcel build --experimental-scope-hoisting client/scripts/index.js --public-url /
```

## 💻 Code Sample

N/A

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |    "parcel-bundler": "^1.9.0"
| Node             |   v10.1.0 
| npm/Yarn         |  v5.6.0
| Operating System |  Mac OS v10.13.5

**Comment by fathyb** [comment]
Thanks! Could you give us the full output or the file responsible for the bug? You can use `--no-minify` to get a non-minified output with filenames.

**Comment by sujith97** [comment]
You may convert it back to js.
[index.js](https://github.com/parcel-bundler/parcel/files/2108571/index.txt)

**Comment by HenrikJoreteg** [comment]
If you need a full app you can run that appears to have the same issue see here: https://github.com/HenrikJoreteg/redux-bundler-example/issues/1

**Comment by sujith97** [comment]
@fathyb @devongovett Any update on this?

**Comment by HenrikJoreteg** [comment]
I'd *love* to get this sorted out as well so I can turn on this awesomeness in my app :)

**Comment by fathyb** [comment]
@HenrikJoreteg your issue is different, #1683 fixes it

**Comment by mischnic** [comment]
@sujith97 Could you please provide some *source* code?

**Comment by devongovett** [comment]
Closing. I tested using @HenrikJoreteg's app, and it appears to be working.
