### ISSUE TITLE
Scope hoisting out of conditional declaration not working correctly

### ISSUE THREAD

**Issue by asherkin** [parcel-bundler/parcel#1560]
# 🐛 bug report

I know the feature is experimental and there are quite a few possibly related bugs being filed atm, but I quickly managed to reduce this to the broken code so figured it was worth filing separately. The feature is really cool and I can't wait for it to be ready for general use!

## 🎛 Configuration (.babelrc, package.json, cli command)

`parcel build --experimental-scope-hoisting --no-minify --no-source-maps index.js`

`package.json`:
```js
{
  "dependencies": {
    "pako": "^1.0.6"
  }
}
```

## 🤔 Expected Behavior

Sample code below should run without error, as it does without scope hoisting enabled.

## 😯 Current Behavior

```
var $13$var$_utf8len = new $6$export$Buf8(256);
                       ^

ReferenceError: $6$export$Buf8 is not defined
    at dist/index.js:2902:24
    at Object.<anonymous> (dist/index.js:6303:3)
```

## 💁 Possible Solution

Currently emitted code:
```js
var $6$export$setTyped = function (on) {
  if (on) {
    var $6$export$Buf8 = Uint8Array;
    $6$exports.Buf8 = $6$export$Buf8;
    var $6$export$Buf16 = Uint16Array;
    $6$exports.Buf16 = $6$export$Buf16;
    var $6$export$Buf32 = Int32Array;
    $6$exports.Buf32 = $6$export$Buf32;
    $6$export$assign($6$exports, $6$var$fnTyped);
  } else {
    $6$export$Buf8 = Array;
    $6$exports.Buf8 = $6$export$Buf8;
    $6$export$Buf16 = Array;
    $6$exports.Buf16 = $6$export$Buf16;
    $6$export$Buf32 = Array;
    $6$exports.Buf32 = $6$export$Buf32;
    $6$export$assign($6$exports, $6$var$fnUntyped);
  }
};
```

It looks like the `var`s in the `on` branch are spurious - manually editing the output to remove them makes everything work correctly:
```js
var $6$export$setTyped = function (on) {
  if (on) {
    $6$export$Buf8 = Uint8Array;
    $6$exports.Buf8 = $6$export$Buf8;
    $6$export$Buf16 = Uint16Array;
    $6$exports.Buf16 = $6$export$Buf16;
    $6$export$Buf32 = Int32Array;
    $6$exports.Buf32 = $6$export$Buf32;
    $6$export$assign($6$exports, $6$var$fnTyped);
  } else {
    $6$export$Buf8 = Array;
    $6$exports.Buf8 = $6$export$Buf8;
    $6$export$Buf16 = Array;
    $6$exports.Buf16 = $6$export$Buf16;
    $6$export$Buf32 = Array;
    $6$exports.Buf32 = $6$export$Buf32;
    $6$export$assign($6$exports, $6$var$fnUntyped);
  }
};
```

## 🔦 Context

Trying to use experimental scope hoisting in a project I'm working on that uses the Pako library, things fell apart. Extracted the minimal sample below out of my project for reproduction.

## 💻 Code Sample

```js
const pako = require("pako");
const inf = new pako.Inflate({ to: "string" });
const data = [0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x03, 0xf3, 0x48, 0xcd, 0xc9, 0xc9, 0x07, 0x00, 0x82, 0x89, 0xd1, 0xf7, 0x05, 0x00, 0x00, 0x00];
inf.push(new Uint8Array(data), true);
console.log(inf.err, inf.msg, inf.result, inf.result === "Hello");
```

To reproduce: stick ^ as `index.js` and the `package.json` from above in a directory, run `npm install`, run the `parcel build ...` command above, try and run the generated output with `node dist/index.js`.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.0
| Node             | 8.11.2
| npm/Yarn         | npm 5.6.0
| Operating System | macOS 10.12.6

**Comment by bencooper222** [comment]
Having basically the same issue. Typescript -> Javascript works fine but Javascript to minified Javascript breaks.

**Comment by asherkin** [comment]
Just tried out the latest release, so figured I'd drop a note to confirm this is still an issue.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             | 8.11.2
| npm/Yarn         | npm 6.4.1
| Operating System | macOS 10.14

**Comment by mischnic** [comment]
The issue is that pako conditionally exports `Buf8`: [lib/utils/common.js](https://github.com/nodeca/pako/blob/master/lib/utils/common.js)

```js
var TYPED_OK =  (typeof Uint8Array !== 'undefined') &&
                (typeof Uint16Array !== 'undefined') &&
                (typeof Int32Array !== 'undefined');

// ...

exports.setTyped = function (on) {
  if (on) {
    exports.Buf8  = Uint8Array;
    exports.Buf16 = Uint16Array;
    exports.Buf32 = Int32Array;
    exports.assign(exports, fnTyped);
  } else {
    exports.Buf8  = Array;
    exports.Buf16 = Array;
    exports.Buf32 = Array;
    exports.assign(exports, fnUntyped);
  }
};

exports.setTyped(TYPED_OK);
```

Not sure how/whether parcel takes this into consideration.

**Comment by devongovett** [comment]
The code being emitted looks correct, except the variable is being declared in the wrong scope (inside the function, rather than at the module level).

**Comment by asherkin** [comment]
@devongovett Thanks for the fix!
