### ISSUE TITLE
Cannot import local modules inside Vue single file component

### ISSUE THREAD

**Issue by Morgul** [parcel-bundler/parcel#1563]
# 🐛 Bug Report

As of parcel `v1.9.0` parcel seems unable to handle importing an es6 module from inside Vue single file component. Importing from `node_modules` seems fine, but files from inside the project don't work. Parcel compiled fine, but gives a runtime error like:

`Uncaught ReferenceError: $f117f7 is not defined`

(See below for a screenshot of the full error.)

## 🎛 Configuration (.babelrc, package.json, cli command)

This does not seem configuration dependent, and happens with `parcel`, `parcel watch` and `parcel build`.

## 🤔 Expected Behavior

I expect the application to compile and run correctly. 😉

## 😯 Current Behavior

Everything compiles, but the page fails to render. In the console is this error:

![image](https://user-images.githubusercontent.com/770655/41503047-cc1de366-718e-11e8-83a2-ea1317b039c3.png)

Text version:
```app.vue:14 Uncaught ReferenceError: $f117f7 is not defined
    at Object.parcelRequire.6../lib/test (app.vue:14)
    at newRequire (app.d6d13eb2.js:48)
    at localRequire (app.d6d13eb2.js:54)
    at Object.parcelRequire.4.vue (app.js:3)
    at newRequire (app.d6d13eb2.js:48)
    at parcelRequire.8 (app.d6d13eb2.js:80)
    at app.d6d13eb2.js:106
```

## 💁 Possible Solution

I have not been able to work around this, except by not importing modules in my `vue` files. That's not really a work around, for anything but a very basic application.

## 🔦 Context

I can't upgrade any of my applications to `v1.9.0`, which has some pretty important fixes in it. This bug basically rendered parcel unusable for vue projects.

## 💻 Code Sample

Reproduction repo: https://github.com/Morgul/parcel-vue-bugs

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v1.9.0, v1.9.1 |
| Node             | v9.10.1 |
| npm/Yarn         | v1.6.0 (yarn) |
| Operating System | macOS 10.13.5 |

**Comment by Morgul** [comment]
Now, as of #1576 I get a new error:

<img width="308" alt="screen shot 2018-06-18 at 8 28 59 am" src="https://user-images.githubusercontent.com/770655/41541115-4fabe6b2-72d7-11e8-9089-a481a23f8277.png">

Text version:
```
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

(found in <Root>)
```

The app still does not work.

**Comment by DaveO-Home** [comment]
This looks like my issue - #1579 
Set minify: true

**Comment by Morgul** [comment]
@DaveO-Home I'm not entirely sure how to set minify to true on dev; I tried a `.uglifyrc`, that didn't seem to make a difference, so I just tried a production build, and I stopped getting an error, but the app didn't work (probably because vue hides warnings in production mode).

**Comment by Morgul** [comment]
@DeMoorJasper Also, not sure what the protocol here is, but I'm pretty sure this is a bug, not a question :slightly_smiling_face:. Vue applications that worked on parcel `1.8.1` do not work on `1.9.x`, and more to the point, it seems like even a basic Vue application doesn't work with parcel 1.9 right now.

**Comment by DaveO-Home** [comment]
Take a look at #1522.  I use the api(with gulp) so it looks like this:
```js
// Bundler options
    const options = {
        production: isProduction,
        outDir: '../../' + dist,
        outFile: isProduction ? 'testapp.html' : 'testapp_dev.html',
        publicUrl: './',
        watch: watch,
        cache: !isProduction,
        cacheDir: '.cache',
        minify: isProduction,
        target: 'browser',
        https: false,
        logLevel: 3, // 3 = log everything, 2 = log warnings & errors, 1 = log errors
        // hmrPort: 3080,
        sourceMaps: !isProduction,
        // hmrHostname: 'localhost',
        detailedReport: isProduction
    };

   const bundler = new Bundler(file, options);
    let isBundled = false

    bundler.on('bundled', () => {
        isBundled = true
    })
    bundler.on("buildEnd", () => {
        if (isBundled) {
            log(chalk.green("Build Successful"))
        }
        else {
            log(chalk.red("Build Failed"))
            process.exit(1)
        }
    })
    // Run the bundler, this returns the main bundle
    return bundler.bundle()
```
I'm sure the cli has an option  to set the minify on the command line.
My demo app is github.com/DaveO-Home/embedded-acceptance-tests-vue

Both dev and prod work with minify: true,   and yes this is a bug.

**Comment by DeMoorJasper** [comment]
@Morgul try a production build with minifying enabled and disabled. It looked like a vue question to me. I’ll change it to bug if its not a duplicate of #1579

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DaveO-Home** [comment]
Try version 1.9.2 - it fixed my issue.

**Comment by Morgul** [comment]
@DaveO-Home v1.9.2 does not seem to fix this issue for me.

@DeMoorJasper I will try a production build without minify.

**Comment by Morgul** [comment]
@DeMoorJasper, @DaveO-Home Finally got a chance to play with this more. Found a stupid copy/paste error in my test app that caused the "runtime" error I reported [here](https://github.com/parcel-bundler/parcel/issues/1563#issuecomment-398067483)

So, `v1.9.2` _did_ fix my issues. I'll update my projects, and make sure they're all working correctly as well, but I feel confident to close this. :)

**Comment by NotIntMan** [comment]
I have same issue on `v1.9.7`. Thanks to  for Thanks to @Morgul for a temporary solution, but the bug is still relevant.
> @Morgul try a production build with minifying enabled and disabled. It looked like a vue question to me. I’ll change it to bug if its not a duplicate of #1579
> 
> Sent with [GitHawk](http://githawk.com)
