### ISSUE TITLE
Add support for source maps with tree shaking

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#1564]
Source maps are currently unsupported with tree shaking. Because of the way we concatenate the ASTs, and the ordering required, the existing source map infrastructure was insufficient to implement this easily for the first release.

There are a couple ways we could make this work:

1. We could use the source map generated by babel in the concatenate transform and map back to the original source maps generated for each file.
2. We could attempt to share the original ASTs of each file into the cache so we wouldn't need to parse it again in the packager. These ASTs have the original source map info embedded in them as well, so when we concatenate the ASTs together we can generate a combined source map automatically as well via babel. This option will require some performance testing to see how slow it is to pass the whole AST back over the IPC from workers vs passing generated code.

**Comment by misantronic** [comment]
to bad it's not working right now.
parcel might be an alternative for fuse-box if that worked.

**Comment by stevenvachon** [comment]
Almost a year and this still hasn't been fixed?

**Comment by devongovett** [comment]
This will be addressed in Parcel 2.

**Comment by stevenvachon** [comment]
When might we expect that? Positive thinking.

**Comment by devongovett** [comment]
No promises, but we're getting close to an alpha.
