### ISSUE TITLE
Build for production with ...development version of libraries

### ISSUE THREAD

**Issue by danburzo** [parcel-bundler/parcel#1565]
# ❔ Question

I _know_ this sounds stupid, but is there a way I can get the development versions of React / ReactDOM when building for production with Parcel? 😅

## 🔦 Context

I've recently switched from Webpack to Parcel for a small website I haven't touched in a year:
https://danburzo.github.io/input-methods/
(The migration process took about 1 min, so tip o' the hat to you! 🎩)
However, it relies on having the React/ReactDOM development versions, so that event names are not uglified. 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.1
| Node             | 10.3.0
| npm/Yarn         | yarn 1.7.0
| Operating System | macOS 10.13.4

**Comment by DeMoorJasper** [comment]
You can use `--no-minify` if the issue is the uglified event names

**Comment by danburzo** [comment]
I think it's more of a `NODE_ENV='production'` issue, that makes React pick up the production (uglified) version... 

Maybe I can get by with deploying the output of `parcel serve`?

**Comment by DeMoorJasper** [comment]
`parcel serve --no-hmr` is probably the best option than, as it'll exclude the socket (as that would throw an error in production)

**Comment by danburzo** [comment]
Thank you for the suggestion, I'll try it!

**Comment by danburzo** [comment]
Is it reasonable to either add a `--no-env` option to `parcel build` that allows the user to override NODE_ENV, or allow overriding it _all the time_, even with build?  e.g. this:

https://github.com/parcel-bundler/parcel/blob/21fcd17ab0e8e7ddbf9d42a62b009f8c3a922781/src/cli.js#L176-L180

becomes:

```js
process.env.NODE_ENV = process.env.NODE_ENV || (command.name() === 'build' ? 'production' : 'development')
```

**Comment by DeMoorJasper** [comment]
@danburzo you should be able to create a .env file. But it normally doesn't overwrite the production env var. you could give it a shot though (as i haven't tried)

**Comment by pomber** [comment]
I have a similar use case for this. I'm using parcel to deploy to netlify a minimal demo of a bug in a library (I want the development version of the library).

**Comment by mischnic** [comment]
This gives the same output as `parcel serve` (now also in the docs: https://parceljs.org/cli.html):
`NODE_ENV=development parcel build index.js --no-minify`

https://github.com/parcel-bundler/parcel/blob/32f332782e830036c775dc7ad2631b5801719dc3/packages/core/parcel-bundler/src/cli.js#L202-L207
