### ISSUE TITLE
Support fine grained sideEffects field in package.json

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#1566]
The current implementation of tree shaking supports `sideEffects: false`, but some libraries need more fine grained control to allow a subset of files to include side effects. webpack allows this by supporting an array of files which contain side effects.

```json
{
  "sideEffect": ["./foo.js", "./bar.js"]
}
```

For compatibility with libraries that depend on this, we should support it in Parcel as well.

**Comment by ahocevar** [comment]
I've implemented support for the fine grained sideEffects syntax and submitted it as #1766.
