### ISSUE TITLE
How do I get `--target=electron` to play nice with yarn workspaces?

### ISSUE THREAD

**Issue by emilsjolander** [parcel-bundler/parcel#1571]
# ❔ Question

How do I get `--target=electron` to play nice with yarn workspaces?

## 🔦 Context

I'm using yarn workspaces (https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/) to organise my code in different packages within the same repo. However do to this basically just symlinking directories into `node_modules` it seems to break some assumptions in Parcel when bundling for electron.

Imagine I have this structure:
```
├── package.json
└── packages
    ├── module-one
    │   ├── index.ts
    │   └── package.json
    ├── module-two
        ├── index.ts
        └── package.json
``` 

Yarn workspaces will map that directly into `node_modules` like so, not that `node_modules` now has typescript files in it:
```
└── node_modules
    ├── module-one
    │   ├── index.ts
    │   └── package.json
    ├── module-two
        ├── index.ts
        └── package.json
```

The problem with this is that parcel (when run with `--target=electron`) will skip bundling any node_module dependencies and defer this to runtime `require()` call. However runtime `require()` will fail because it will try to require a typescript file which has not been bundled.

Everything works as expected with `--target-browser`. Can I somehow give parcel a list of packages to always bundle? Or can we perhaps get parcel to automatically look at `workspaces` in `package.json` to figure out which modules need to be bundled from `node_modules`?

**Comment by emilsjolander** [comment]
Maybe one solution is to follow symlinks for the require and check wether it is located within node_modules or not?

**Comment by emilsjolander** [comment]
I found https://github.com/parcel-bundler/parcel/pull/1101 by @devongovett which seems like it should have solved this. Although I added `source": true` to the `package.json` of all my workspaces and using parcel 1.9.1 it still does not bundle or compile these files that are symlinked into `node_modules`.

**Comment by rafaelcorreiapoli** [comment]
Any updates on this?

**Comment by alidcastano** [comment]
yes, i don't think that this is an electron specific problem, i'm facing the same problem bundling my react application. 

@devongovett are parcel/symlinks compatible with yarn workspaces? (I couldn't find any other issue on it yet it doesn't seem to be fully working)
