### ISSUE TITLE
🐛 bug report: failed to process stylus file

### ISSUE THREAD

**Issue by aicest** [parcel-bundler/parcel#158]
[Code to reproduce the error](https://github.com/aicest/parcel-stylus): `failed to locate @import file node_modules\stylus\lib\functions\index.js.styl`.

### 💁 Possible Solution

See #159.

### 🌍 Your Environment

| Software                | Version(s)
| -------------------- | ----------
| Parcel                     | 1.1.0   
| Node                     | 8.6.0
| npm/Yarn              | 5.3.0/1.1.0
| Operating System | Win 10

**Comment by davidnagli** [comment]
Closed via #159
