### ISSUE TITLE
Code duplicated when using dynamic imports in multiple entries

### ISSUE THREAD

**Issue by YvanY** [parcel-bundler/parcel#1580]
# 🐛 bug report

I tried to use dynamic imports to extract common code in entries. However the common part is not extracted in last entry

## 🎛 Configuration (.babelrc, package.json, cli command)

npm script
```
parcel ./**/*.html
```
file structure
```
├─js
│      vendor.js
│
└─pages
    │  index.html
    │
    ├─index
    │      main.js
    │      main.scss
    │
    └─page1
            index.html
            main.js
            main.scss
```

vendor.js
```js
import('vue')
```
index/main.js & page1/main.js
```js
import '../../js/vendor'
import Vue from 'vue'
```

## 🤔 Expected Behavior

code in vendor.js should be extract  to a separate file

## 😯 Current Behavior

this content in vue.runtime.esm.bfd22634.js is still in main.7805af3c.js, but not in main.63f097bf.js
```
dist\main.7805af3c.js                64.57 KB    1.62s
dist\vue.runtime.esm.bfd22634.js     62.84 KB    1.55s
dist\main.63f097bf.js                 2.67 KB    1.83s
dist\index.html                         408 B     17ms
dist\page1\index.html                   408 B    718ms
dist\main.47f3b71e.map                    0 B      5ms
dist\main.e40d4a5e.css                    0 B    1.23s
dist\vue.runtime.esm.bfd22634.map         0 B     59ms
dist\main.4bc44005.map                    0 B     57ms
dist\main.e40d4a5e.css                    0 B    1.24s
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.1 |
| Node             | 10.3.0 |
| npm/Yarn         | 1.7.0 |
| Operating System | windows10 |

**Comment by mischnic** [comment]
Very similar to #885 ?

**Comment by mischnic** [comment]
Parcel doesn't do any automatic codesplitting if you don't use dynamic imports. Otherwise, please follow #885.
