### ISSUE TITLE
Unknown plugin "transform-runtime" specified in "base" at 0

### ISSUE THREAD

**Issue by kybetter** [parcel-bundler/parcel#1585]
# 🐛 bug report

Unknown plugin "transform-runtime" specified in "base" at 0
## 🎛 Configuration (.babelrc, package.json, cli command)
```
$ parcel 
or
$ ./node_modules/parcel-bundler/bin/cli.js
```

no configuration

## 🤔 Behavior

```
Server running at http://localhost:1234
Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to...
```
## 💻 Code Sample
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <script src="./index.js"></script>
</body>
</html>
```
`index.js` is an empty file.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.2
| Node             |10.4.0
| npm/Yarn         |no npm/yarn 1.7.0
| Operating System |MacOS

**Comment by DeMoorJasper** [comment]
Do you have any babel config?
Please also share pkg.json

**Comment by kybetter** [comment]
no babel config, no `package.json`.
just have `index.html` and `index.js` file.

**Comment by FrankFang** [comment]
Same problem here.
