### ISSUE TITLE
It can't find modules in the root node_modules (monorepo - Yarn workspaces) - (probably hoisting problem?)

### ISSUE THREAD

**Issue by MatejMazur** [parcel-bundler/parcel#1588]
# 🙋 feature request

It looks like that ParcelJS can't find packages from the root node_modules folder in monorepo with Yarn workspaces.
```
root
├── node_modules (modules in this directory are not found)
└── app (with ParcelJS)
    └── node_modules (parcel-bundler is in this folder)
```

[Link to monorepo](https://github.com/MatejMazur/starter-lerna/tree/rollup).

## 🤔 Expected Behavior
It should solve modules from the root `node_modules` folder.

## 😯 Current Behavior
It tries to find directory in the app level but that directory is in the root folder of monorepo.
![image](https://user-images.githubusercontent.com/20944757/41651688-717b6186-7481-11e8-9796-1aee19bcc928.png)

## 💁 Possible Solution

Support hoisting shared dependencies.

## 🔦 Context

I want to build a monorepo with ParcelJS.

My environment:
- Windows 10
- Node.js 10.3.0
- Yarn 1.7.0

## 💻 Examples

[Here is the monorepo with this problem.](https://github.com/MatejMazur/starter-lerna/tree/rollup)

**Comment by MatejMazur** [comment]
Ok, it was something weird. After reinstall it suddenly works.

**Comment by dbuezas** [comment]
Had the exact same problem. After `yarn` again, it found the modules in the root

**Comment by dandv** [comment]
This seems still broken. I've run `yarn install` twice in a monorepo. My web app is in `foo`. `yarn install` creates `foo/node_modules/.bin/parcel` as a symlink to `../../../node_modules/parcel-bundler/bin/cli.js`.

I'm running `yarn run start` in the `foo` workspace, which runs `parcel index.html` from `foo/package.json`. I get the following error:

> Error: ENOENT: no such file or directory, open '/home/dandv/myapp/foo/node_modules/parcel-bundler/src/builtins/css-loader.js'

It's clear that Parcel looks for the src files in the `foo` directory, not in the monorepo's `node_modules`.

**Comment by mauron85** [comment]
Same problem here

**Comment by mauron85** [comment]
But succeed with using NODE_PATH set to root of mono repo. eg:

```
NODE_PATH=../../../../../../ parcel build 
```

**Comment by kontrollanten** [comment]
Same issue here.

File structure:

```
/node_modules/package-a@
/node_modules/parcel
/packages/package-a
/packages/demo
```

/packages/demo/package.js:

```
{
  "name": "demo",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "lint": "eslint src",
    "start": "parcel src/index.html",
    "build": "parcel build src/index.html"
  },
  "devDependencies": {
    "@babel/core": "^7.3.4",
    "parcel": "^1.11.0"
  },
  "dependencies": {
    "preact": "^8.4.2",
    "preact-leaflet": "1.0.0"
  }
}
```

Full repo at https://github.com/kontrollanten/preact-leaflet/tree/workspaces

**Comment by ianliu** [comment]
I was experiencing this problem because I was running `parcel index.html` from a global parcel installation. After I put that into the `start` script, and executed with `yarn start`, it worked.

**Comment by holt-mansfield-finaeo** [comment]
NODE_PATH=../../ solved the problem for me in my Lerna monorepo

**Comment by good-idea** [comment]
I came across this issue as well ~ I had parcel installed in one of my project directories, fixed this by removing it from the project and installing it in the root package.json. not ideal but it works!

**Comment by resistdesign** [comment]
> I came across this issue as well ~ I had parcel installed in one of my project directories, fixed this by removing it from the project and installing it in the root package.json. not ideal but it works!

@good-idea Did you run Parcel from the root as well?

**Comment by kristiandupont** [comment]
@good-idea's solution appears to work for me as well. I still run Parcel from the client folder.
