### ISSUE TITLE
Babel plugin does not run with Typescript

### ISSUE THREAD

**Issue by mathewbyrne** [parcel-bundler/parcel#1590]
# 🐛 bug report

The relay babel plugin does not run on outputted javascript when using Typescript.  It appears that something is happening, since Parcel will complain about missing plugins; but the `graphql` template tags that relay strips are still present in the output.

### .babelrc
```js
{
    "presets": ["env"],
    "plugins": ["relay"]
}
```

(see [gist](https://gist.github.com/mathewbyrne/9d792f20da06cb4604c354091297dd70) for remaining config)

## 🤔 Expected Behavior

The page should render the error output from the `QueryRenderer`.

## 😯 Current Behavior

> Uncaught Error: graphql: Unexpected invocation at runtime. Either the Babel transform was not set up, or it failed to identify this call site. Make sure it is being used verbatim as `graphql`.

This invariant is hit because the plugin has not run to strip out the template tags.

## 💁 Possible Solution

If I switch away from Typescript to regular JSX files, the babel plugin operates as expected.

It would be good to get some more transparency/documentation about how Parcel is bundling things together.  Currently I do not really know how to go about debugging this issue.

## 🔦 Context

I am trying to bootstrap a project that uses Typescript and Relay.  I attempted to do this by first getting Typescript going (very easy 💯 ) then running through the [Relay Quick Start Guide](https://facebook.github.io/relay/docs/en/quick-start-guide.html).

## 💻 Code Sample

https://gist.github.com/mathewbyrne/9d792f20da06cb4604c354091297dd70

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.2
| Node             | 8.11.2
| npm/Yarn         | yarn 1.7.0
| Operating System |OSX 10.13.4

**Comment by DeMoorJasper** [comment]
@cdock1029 's solution should work, removed the bug flag. As this ain't no bug, just misconfiguration

**Comment by mathewbyrne** [comment]
Yep, this was a misconfiguration issue to do with interaction between Typescript and Babel.  As @cdock1029 suggests the solution is to prevent Typescript from transpilation, and leave it to Babel.
