### ISSUE TITLE
Hot Module Reloading not working, dev server not being updated.

### ISSUE THREAD

**Issue by vpicone** [parcel-bundler/parcel#1591]
# 🐛 bug report

I followed the steps exactly here: https://parceljs.org/getting_started.html
Making changes to either the js or html file does not cause any update to occur at localhost:1234 when `parcel index.html` is run.

I also followed the react recipe verbatim with the same issue: http://blog.jakoblind.no/react-parcel/
Saving the file doesn't refresh the dev server.

### package.json
```js
{
  "name": "parcel",
  "version": "1.0.0",
  "description": "",
  "main": "index.html",
  "scripts": {
    "start": "parcel index.html"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^16.4.1",
    "react-dom": "^16.4.1"
  },
  "devDependencies": {
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "parcel-bundler": "^1.9.2"
  }
}
```

### .babelrc
```js
{
    "presets": [
        "env",
        "react"
    ]
}
```

### console command
`npm start`
also tried `parcel serve index.html` and `parcel index.html --no-cache`
## 🤔 Expected Behavior

Saved changes should cause the dev server to refresh

## 😯 Current Behavior

Content builds correctly when the command is first run however, the dev server is *not* refreshed when a change is saved, so even refreshing the page doesn't do anything.

## 🔦 Context
I tried using global parcel-bundler as well as a local installation.

## 💻 Code Sample

Followed the get started guide and react-recipe blog exactly.

### index.html
```html
<!DOCTYPE html>
<html>

<head>
    <title>React starter app</title>
</head>
<body>
    <div id="app"></div>
    <script src="index.js"></script>
</body>
</html>
```
### index.js
```js
import React from "react";
import ReactDOM from "react-dom";

class HelloMessage extends React.Component {
  render() {
    return <div>Hlo{this.props.name + this.props.name}</div>;
  }
}

var mountNode = document.getElementById("app");
ReactDOM.render(<HelloMessage name="Jane" />, mountNode);
```

## 🌍 Your Environment
Tried in chrome as well as firefox

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.2
| Node             | 8.11.3
| npm/Yarn         | 5.6.0
| Operating System | Mac
| Firefox Dev edition | 62.0b1
| Chrome | 67.0.3396.87

**Comment by DeMoorJasper** [comment]
Safe write issue? https://parceljs.org/hmr.html#safe-write

**Comment by vpicone** [comment]
@DeMoorJasper I'm using VS Code which doesn't have safe write functionality. https://github.com/Microsoft/vscode/issues/28927

**Comment by vpicone** [comment]
So I have no clue what happened, but I was having the same issue with a separate project that uses create-react-app. Restarting my computer fixed the problem. 🤷‍♂️

**Comment by samsch** [comment]
I've been seeing reports of this on Freenode, and had it happen a couple times myself. In particular, this bug chased away a user from Parcel entirely today. I think it happens on certain first runs. I was able to reproduce it once with their code, but not consistently. There *is* a problem here, so it would be great to re-open.

The specific code failed was `index.html` and `src/app.js` with this content:

index.html:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Parcel Demo</title>
</head>
<body>
    <div id="main">Hello</div>
    <script src="./src/app.js"></script>
</body>
</html>
```
src/app.js:
```js
import $ from 'jquery';

$(() => {
  $('#main').text('Hello 123');
});
```
I dropped those into a folder which had parcel install and ran it (but I think I may have tried to run it with the app.js file in root first?) and it reproduced, with changes to app.js not causing rebuilds, even after killing and restarting the parcel process (run with `npx parcel index.html`).

It seems to have happened more when changing a script src is involved at some point. It also seems like once it goes away, it doesn't tend to come back in that project. Unfortunately, I wasn't able to get feedback from the user whether deleting .cache fixed it or not. Deleting the .cache folder doesn't not seem to be enough to get the issue to come back.

**Comment by Nufflee** [comment]
I'm having the same problem and this is like 5th time I'm trying Parcel over last 6 months or so and I just can't get Parcel to refresh the page, it rebuilds but doesn't refresh. I'm on Windows, using TypeScript and the issue persists no matter the browser (I tried Chrome, Firefox and Opera). Really annoying.

**Comment by Michael-N** [comment]
I believe I have been having the same problem... Safe write was not the error for me.  I can confirm what @samsch said ``` It also seems like once it goes away, it doesn't tend to come back in that project.```. However if I rename the containing folder, parcel will no longer detect watch changes, even after restarting the parcel build while the folder name change is in effect. I tried using the api to ensure the correct dir is passed and the problem above still persists. Deleting .cache was not enough to fix it for me.  Any help is appreciated. Thanks!

**Comment by fabioricali** [comment]
Same problem but since 1.9.5.. 1.9.4 it's ok!

**Comment by hrafnkellbaldurs** [comment]
Thanks @Michael-N :) 
Removing the periods in the containing folder fixed this problem for me, I just replaced them with hyphens. Renamed folder from `hrafnkellbaldurs.github.io` to `hrafnkellbaldurs-github-io`.
I also noticed that it wasn't just the containing folder that I had to remove periods from. Any parent folders that had periods had to be renamed as well.

**Comment by gitnix** [comment]
I am also experiencing this issue. Using VSCode (no safe-write). Don't have any odd folder names and 1.9.4 doesn't act any differently.

**Comment by caiokoiti** [comment]
Same problem here! Using atom or any other text editor, the css does not get applied just by changing a css property.

**Comment by saneef** [comment]
@DeMoorJasper Can we re-open this issue? The presence of periods in any parent folder breaks `watch` like @hrafnkellbaldurs pointed out.

**Comment by mixedCase** [comment]
Can confirm, this was driving me crazy, replacing the periods from the root folder fixed it.

**Comment by caiokoiti** [comment]
@mixedCase Hey mate, would you mind posting how the code was, and how it looks like now for the affected files?

**Comment by mixedCase** [comment]
@caiokoiti Same code. I merely renamed folder containing the repository from com.domain.subdomain to com-domain-subdomain.

**Comment by russellmorgan** [comment]
Just quickly adding that periods in my directory name was causing Parcel to ignore hot reloads. (windows 10, VS Code)

**Comment by j0hnm4r5** [comment]
I think there are two overlapping issues here: the period-in-directory one, and the one @gitnix and I are having.

I have no folders with dots anywhere in their names, and I'm getting super inconsistent reloading across my and my coworkers' machines.

**Comment by tehfailsafe** [comment]
Same problem, created a new project based off an old (fully HMR working) project. Super bare bones and minimal, but HMR only works on the top level of a react-router based project. Child routes simply won't reload. Restarted, no periods, can open the other project and everything works perfectly, but not this one that is a copy of it... :(

**Comment by tehfailsafe** [comment]
Ok, found my problem, possibly @j0hnm4r5 's as well... 

Turns out when I was recreating my project I inadvertently named a folder "C"omponents instead of "components". I was using `import {Title} from 'components'` but the `Title.tsx` file lives in the `Components` folder. The part that really makes this challenging is that everything works correctly, parcel finds the file, loads it, renders it, no linting error, etc. The only thing that doesn't work is hot reloading.

This seems like it should either not work at all (ie `Can't find dependency 'Title' in 'components'` error) or HMR should be case insenstive. Either way would have helped me pinpoint the problem.

The inconsistent behavior between initial loading and HMR led me downgrading babel to earlier versions, stripping out dependencies, removing plugins etc from `.babelrc` just to happen to notice the capitol letter after hours of banging my head on the wall.

**Comment by xmclark** [comment]
I am experiencing hot reloading working exactly once, and then never again. It reloads after a single change, but then all following changes do not cause hot reload. I have no directories with periods.  Deleting `.cache` and `dist` do not work.

Windows 10
WebStorm 2018.2

**Comment by fabioricali** [comment]
This issue should be reopened... HMR not works on windows, since version 1.9.5 to latest 1.10.3.

**Comment by xmclark** [comment]
This issue has blocked me from adopting Parcel. I am back on Rollup until this issue is resolved.

**Comment by neurodynamic** [comment]
Just started seeing this issue. Don't think I have any periods in folder names. Parcel just periodically stops reloading on file changes and won't start again until the computer is rebooted. Running on macOS Mojave and vscode. Restarting the app without a computer restart makes me able to see new errors, but I have to restart the app every time I change something to see new issues or compilation.

**Comment by neurodynamic** [comment]
Does anyone else's issue resolve itself (at least temporarily) if you delete the folder where the compiled output is being put?

**Comment by Abhi10699** [comment]
Hey.. I was using vim on my windows machine with :set backupcopy=yes and live reload was working perfectly... but due to some circumstances i  had to switch to ubuntu and i reinstalled parcel bundler on it with node 8 and it turns out even with :set backupcopy=yes liver reload isn't working... later i tried to edit index.html file with sublime text 3 but that didn't worked aswell...

**Comment by sdaitzman** [comment]
I'm experiencing this issue on macOS 10.14.2 with Atom 1.33.1

**Comment by josfaber** [comment]
Same problem of HMR not updating. My solution is not enabling **https** on the dev server. When I do not use https, HMR works properly. When I run with `--https` it does not. When I again run, but without `--https` it works again. 

So, 
HMR  does **not** work with: `parcel src/index.html --out-dir=dev --https --open`
HMR **does** works with `parcel src/index.html --out-dir=dev --open`

Parcel v1.11.0

```
# dir structure
src
  index.html
  index.js
  style.scss


# package.json
{
  "name": "parcel-test",
  "version": "1.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "watch": "parcel watch src/index.html --out-dir=dev",
    "dev": "parcel src/index.html --out-dir=dev --https --open",
    "build": "parcel build src/index.html --out-dir=dist --public-url=./"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {},
  "devDependencies": {
    "node-sass": "^4.11.0",
    "parcel": "^1.11.0"
  }
}


# index.js
import './style.scss';
console.log('hello');


# style.scss
body { background: #ff0; }
a { color:#900; }
```

**Comment by klausbreyer** [comment]
![screenshot 2019-02-04 at 09 30 39](https://user-images.githubusercontent.com/32771/52197365-977bfc00-285f-11e9-8478-f0a96583c31e.png)
for me it was caused by a typo in the file name. I fixed this, deleted dist/ and .cache and everything works fine. 

I am using react / material ui for this project.

**Comment by Ariyn** [comment]
same here
in my case, atom doesn't fire HMR event.
but windows default notepad does fire.
is this kind of sign to work with notepad like 99 or whenever

**Comment by chrisdmacrae** [comment]
The issue with dotfiles is a configuration issue with `fast-glob` @DeMoorJasper.

`fast-glob` always ignores dotfiles and the children of dotfolders unless you explicitly tell it not to.

Where you're calling glob or glob.sync from `utils/glob.js` to get the entry files/setup the watcher, you need to add:

```
const options = { dot: true }
glob.sync([...], options)
```

**Comment by ClickSimply** [comment]
Was running into this problem on macOS with Visual Studio Code.  Deleting `.cache` and `.dist` folders didn't help and there were no files with dots when I ran `pwd` in the terminal.

Turns out parcel really doesn't like `document.addEventListener("DOMContentLoaded"`.  Since this event is only triggered on the first load.  

So I removed the `DOMContentLoaded` callback and adjusted the code to work without it, then HMR came back!

## Old (Non Working) Setup
```html
<!DOCTYPE html>
<head>
    <script src="./test.tsx"></script>
</head>
<body>
    <div id="app"></div>
</body>
</html>
```

```ts
import * as React from "react";
import * as ReactDOM from "react-dom";

const App = () => {
    return <div>Hello</div>;
}

document.addEventListener("DOMContentLoaded", () => {
    ReactDOM.render(<App />, document.getElementById("app"));
})
```

## Working Setup

```html
<!DOCTYPE html>
<body>
    <div id="app"></div>
    <script src="./test.tsx"></script>
</body>
</html>
```

```ts
import * as React from "react";
import * as ReactDOM from "react-dom";

const App = () => {
    return <div>Hello</div>;
}

ReactDOM.render(<App />, document.getElementById("app"));
```

Hope that helps!

**Comment by chaaya** [comment]
A discovery that I made was that Parcel HMR is case sensitive to imports. It is obviously a typo error by me, but it might help someone that is also having problems with HMR. I did not get any tsc or tslint errors in vscode and  the code runs even though the filename is App.tsx. Changing the import of App to
`import { App } from './App'` makes HMR work again. 

**Main.tsx**
```Javascript
import React from 'react';
import { render } from 'react-dom';
import rootStore from '/stores';
import { Provider } from 'mobx-react';
import { App } from './app';

const Main = () => {
  return (
    <Provider {...rootStore}> 
      <App />
    </Provider>
  );
}

render(<Main/>, document.getElementById('app'));
```

**App.tsx**
```Javascript
import React from 'react';
import AppRouter from './AppRouter';
import { Link,  BrowserRouter as Router } from 'react-router-dom';


export class App extends React.Component {
  public render() {
    return (
      <Router>
        <div>
          <nav>
            <ul>
              <li><Link to="/">Start</Link></li>
              <li><Link to="/login">Login</Link></li>
            </ul>
          </nav>
          <AppRouter/>
          <div>Footer</div>
        </div>
      </Router>
    )
  }
}
```

Running parcel build is also case sensitive on Linux, so it will fail. Works on OSX.
```bash 
parcel build
```

**Comment by giray123** [comment]
I just start to try Parcel. With minimal setup it does not reload as you said, no file names with periods or any typos, just basic html. No reload after changing title below.

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <h1>Hello</h1>
</body>
</html>
```

**Comment by mischnic** [comment]
@giray123 Maybe *safe write* is the cause: https://parceljs.org/hmr.html#safe-write

**Comment by giray123** [comment]
> @giray123 Maybe _safe write_ is the cause: https://parceljs.org/hmr.html#safe-write

I use VSCode, apparently it does not have safe-write functionality, I also tried on Vim. Got the same result.

**Comment by boazblake** [comment]
I am having this issue with Atom, VScode and sublime on the mac - but NOT with windows using VScode

**Comment by thedynabyte** [comment]
I am experiencing the same issue using VSCode. I am also running parcel within a Vagrant machine. The HMR is not being triggered.

**Comment by juanrules** [comment]
As per @tehfailsafe  comment, having the **name of the file** and **the import statement** with the same letter capitalisation solved the issue for me. 

E.g.:
importing a component like this:
`import Button from './button';
`

Where the actual folder is called **/Button** (notice the capital B), works on first run but it doesn't after saving the changes. 

🙌So making sure the name folder and import have exactly the same name with the same capital letters fixed this issue (for me).

**Comment by jptcnde** [comment]
this issue also happens to me on vscode (parcel version 1.12.3).

it has been solved when I followed the instruction here

https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc

**Comment by fabioricali** [comment]
Parcel 2 solve this great issue... I have tried the alpha version.. It's ok

**Comment by thepenguinthatwants** [comment]
> Parcel 2 solve this great issue... I have try the alpha version.. It's ok

    "parcel-bundler": "^1.12.3",
I tried to get hot reloading work properly for whole day already. How do I get the alpha version of parcel 2?

**Comment by jckw** [comment]
Try:

```
yarn add parcel@v2
```

or 

```
npm install parcel@v2
```

**Comment by thepenguinthatwants** [comment]
Hi thanks!

Seems like it changed the behaviour so it seems to livereload.  But it doesnt take the effects on the css values.

**Comment by thepenguinthatwants** [comment]
Do I need to remove the parcel-bundler before doing the npm install parcel@v2?

**Comment by devongovett** [comment]
> Do I need to remove the parcel-bundler before doing the npm install parcel@v2?
> 
Yes. They both install a CLI command called parcel, so will conflict.

**Comment by JakubKoralewski** [comment]
After hours of frustration I started parcel on WSL. Works like a charm :)

**Comment by andrevenancio** [comment]
This sometimes happens when you have an import like `import MyModule from './Module.jsx` and then you decide to lowercase file name but forgot to change the import.

**Comment by umutbozdag** [comment]
I have solved this issue by moving my files under to src directory

**Comment by kennethkeim** [comment]
HMR refused to work after I removed my index.js file because I no longer needed it. I tried a lot of the things recommended in the comments but nothing worked. As soon as I added index.js back and imported it in index.html, it worked.

I'm on a macbook with vscode and parcel 2

Why is this issue still closed?? HMR is one of the most important features of parcel, and a lot of people are experiencing random problems with super simple projects.

**Comment by mischnic** [comment]
@kennethkeim This is a very old issue. Can you please open a new issue more details? Including your code and the steps to reproduce this?

**Comment by kennethkeim** [comment]
@mischnic Created a new issue here #5371 
Let me know if I missed something. Thanks for your contributions ❤️

**Comment by lukepighetti** [comment]
I ran into this problem and it was because I was trying to edit an HTML file without a JS import. I think this should work no matter if you have a JS src tag or not.

**Comment by haroldao** [comment]
> Same problem of HMR not updating. My solution is not enabling **https** on the dev server. When I do not use https, HMR works properly. When I run with `--https` it does not. When I again run, but without `--https` it works again.
> 
> So,
> HMR does **not** work with: `parcel src/index.html --out-dir=dev --https --open`
> HMR **does** works with `parcel src/index.html --out-dir=dev --open`
> 
> Parcel v1.11.0
> 
> ```
> # dir structure
> src
>   index.html
>   index.js
>   style.scss
> 
> 
> # package.json
> {
>   "name": "parcel-test",
>   "version": "1.0.1",
>   "description": "",
>   "main": "index.js",
>   "scripts": {
>     "watch": "parcel watch src/index.html --out-dir=dev",
>     "dev": "parcel src/index.html --out-dir=dev --https --open",
>     "build": "parcel build src/index.html --out-dir=dist --public-url=./"
>   },
>   "keywords": [],
>   "author": "",
>   "license": "ISC",
>   "dependencies": {},
>   "devDependencies": {
>     "node-sass": "^4.11.0",
>     "parcel": "^1.11.0"
>   }
> }
> 
> 
> # index.js
> import './style.scss';
> console.log('hello');
> 
> 
> # style.scss
> body { background: #ff0; }
> a { color:#900; }
> ```

Thanks, it worked 🚀🚀🎉.

**Comment by serenitus** [comment]
Just to add a little to the body of knowledge here. It was case sensitivity on an import statement that broke it for me. A dumb typo on my part that wasted the good part of a morning!

**Comment by SeniorHangouts** [comment]
> I ran into this problem and it was because I was trying to edit an HTML file without a JS import. I think this should work no matter if you have a JS src tag or not.

I solved my issue like that too. I agree it should live reload even if only using html code.

**Comment by amgj-dev** [comment]
I tried the solutions mentioned here before i was able to fix this by making my script type="module" then adding this code to it:
`if (module.hot) {
  module.hot.accept(function () {
    location.reload();
  });
}`

**Comment by msfeldstein** [comment]
I found this broke for me if i had a script tag like

```
<script src="./index.ts"></script>
```

But works if i load it as a module

```
<script type="module" src="./index.ts"></script>
```

It looks like if i have a non-module script parcel doesn't inject its bundle of hotreloading stuff

**Comment by AmodeusR** [comment]
I was having the same problem here, it wasn't auto refreshing, but thanks to what @msfeldstein said it fixed for me, thanks!

**Comment by GeorgeFlorian** [comment]
I can confirm that this does not work for me as well.
I'm using `"parcel": "^2.0.1"` on VSC, on Ubuntu 20.04 LTS on a very simple and bare-boned structure.
```
{
  "name": "forkify-app",
  "version": "1.0.0",
  "description": "",
  "default": "index.html",
  "scripts": {
    "start": "parcel index.html",
    "build": "parcel build index.html"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/GeorgeFlorian/Forkify-App.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/GeorgeFlorian/Forkify-App/issues"
  },
  "homepage": "https://github.com/GeorgeFlorian/Forkify-App#readme",
  "devDependencies": {
    "@parcel/transformer-sass": "^2.0.1",
    "parcel": "^2.0.1"
  }
}
```
I have first tried running the script with the `--no-cache` option but to no avail.

I have changed from `<script defer src="src/js/controller.js"</script>` to `<script defer src="src/js/controller.js" type="module"></script>` and it started working for just one .js file.

Then I've created new .js files that I import inside `controller.js`. Changes made in those files do not reflect in the page. I have to manually reload the page in order to see the changes.

This bug kills productivity when you're trying to watch tutorials and you do the exact same things as the tutor, but it doesn't work as expected and then you have to search endlessly for a solution.

**Comment by A-Spiral-Forge** [comment]
Agree with @GeorgeFlorian, I am also working with Parcel^2.0.1. The changes sometimes don't reflect in the dist folder when the changes are made in other js files that are imported in the main js file. Can anyone please help with this issue? 
I tried moving all my files to another newly created folder and npm install on that. The problem remains the same.

**Comment by ShaCP** [comment]
Same problem. Changes are not reflecting. I have to do ctrl + shift + r to hard refresh.

**Comment by raff-run** [comment]
I have the same problem. I made a workaround, feel free to use it while it's not fixed.
Steps:
1. Make a hotreload.js/.ts
2. Paste this code in it (you'll have to adapt it a little if you're using pure js):
```javascript
export const enableHotReload = () => {
    if (process.env.NODE_ENV === 'development') {
        // Parcel's websocket sends messages every ctrl + s, even though it ONLY works on index.html for now.
        // We'll listen to it to do a whole page refresh.
        const parcelSocket = new WebSocket("ws://localhost:1234/"); // Or whatever port you run parcel on
        parcelSocket.onmessage = () => {
            // eslint-disable-next-line no-restricted-globals
            location.reload();
        };
    }
};
```
3. Call `enableHotReload();` in your index.tsx just below `ReactDOM.render();` and done.

**Comment by nunof07** [comment]
Using different ports worked for me as described here: https://github.com/parcel-bundler/parcel/issues/6994

**Comment by j13ag0** [comment]
Installing the [nuke-dist](https://www.npmjs.com/package/parcel-plugin-nuke-dist) plugin helped.

**Comment by F30** [comment]
Some notes on my experience with an instance of this problem (using Parcel 2.3.2) can be found in #7762.

**Comment by EnmanuelleAcuna** [comment]
> I found this broke for me if i had a script tag like
> 
> ```
> <script src="./index.ts"></script>
> ```
> 
> But works if i load it as a module
> 
> ```
> <script type="module" src="./index.ts"></script>
> ```
> 
> It looks like if i have a non-module script parcel doesn't inject its bundle of hotreloading stuff

This worked for me, hope works for another person with the issue from now

**Comment by alxkkt** [comment]
Hot reload issue solved for me after i added `type="module"` to my main .js file, now all changes to HTML and JS files are being reflected automatically.
parcel -v 2.4.1

**Comment by Hongjia-Liu** [comment]
If Hot Module Reloading is not working, the problem may relate to the periods (`.`) of the directories name. We can try to get rid of them.

Consider changing the `import` statement from relative path to absolute path, and then changeing it back. This magically works for me.
```jsx
import App from "./App";
import App from "/src/App"
```

**Comment by morphine00** [comment]
Ok, if anyone else is using Windows + WSL and tearing their heart out because no matter what you do, HMR doesn't work... the problem is with WSL **_2_**.

Currently, WSL 2 has a number of problems related to files crossing filesystem boundaries (i.e. if your project is actually under Windows but accessible to WSL under `/mnt/c/something...`.

To work around the problem, you can convert your distro back to WSL 1. Open an Administrator command prompt and:

`wsl -l` to list the distros you have.
`wsl --set-version DISTRO 1`, where DISTRO is the name of your distribution.
`wsl --shutdown` to restart the WSL service.

After this, as if by magic, HMR works again. If anyone has further input on this and a better workaround, I'm all ears.

**Comment by K4L3D777** [comment]
the same problem here, I'm using atom, TSX, windows, and parcel 2.7.0. I restart the computer but the error keeps there. :(
The first time I run npm start it works, but then I can't see any change I make.

**Comment by rahidt1** [comment]
> I found this broke for me if i had a script tag like
> 
> ```
> <script src="./index.ts"></script>
> ```
> 
> But works if i load it as a module
> 
> ```
> <script type="module" src="./index.ts"></script>
> ```
> 
> It looks like if i have a non-module script parcel doesn't inject its bundle of hotreloading stuff

converting script to module worked for me too. :)

**Comment by johanbove** [comment]
Replying to https://github.com/parcel-bundler/parcel/issues/1591#issuecomment-1183536085
Keeping the Parcel project on the /home/userName path on WSL 2 also seems to solve the issue described by OP.

**Comment by morphine00** [comment]
Right, because that way you avoid the cross-filesystem penalty. It's really strange that WSL 2 is more advanced that WSL 1, and yet cross-filesystem access is such a big problem. Hope that Microsoft fixes this at some point.

**Comment by krishan-kumar-mourya** [comment]
> I found this broke for me if i had a script tag like
> 
> ```
> <script src="./index.ts"></script>
> ```
> 
> But works if i load it as a module
> 
> ```
> <script type="module" src="./index.ts"></script>
> ```
> 
> It looks like if i have a non-module script parcel doesn't inject its bundle of hotreloading stuff

I needed to add type="module" for all script tags in index.html

**Comment by Nishaaaanth** [comment]
> If Hot Module Reloading is not working, the problem may relate to the periods (`.`) of the directories name. We can try to get rid of them.
> 
> Consider changing the `import` statement from relative path to absolute path, and then changeing it back. This magically works for me.
> 
> ```js
> import App from "./App";
> import App from "/src/App"
> ```

This fix works I had to remove the period at the beginning of each path

**Comment by Gennady-G** [comment]
For me on windows vsCode  v1.84 and parcel v2.10.3 in year 2023 helped this:

- stop parcel
- delete `.parcel-cache` folder
- start parcel again

**Comment by ilan-schemoul** [comment]
> Safe write issue? https://parceljs.org/hmr.html#safe-write

It was safe write in my case.

I personally didn't find easy to find the information of the fix because I had so many bugs all at once (connection to the HMR server lost, entry not found, 9/10 changes not picked up but 1/10 it worked etc.) it made it not easy to know what to search for and find the appropriate doc. Also I first didn't associate "safe write" with nvim.

I think the current design can be improved: either make the warning the first thing that you see in the doc, detect that "safe write" is enabled with some heuristics or lastly do like live-server and most other projects are doing (I do not know what they do but it works without any config on nvim side).

Any other solution that can help this solution would be fine too. But the current state of affair of lettings users have a terrible experience, as many might not know what's happening does not seem acceptable to me. I personally had the horrendous buggy experience for days and it took me like two hours to find the problem (and I have been doing development for a decade now). I didn't know what to look for as the symptoms were numerous.
