### ISSUE TITLE
css assets path not correct

### ISSUE THREAD

**Issue by slmjkdbtl** [parcel-bundler/parcel#1592]
# 🐛 bug report

I'm using a font with `@font-face` and `url` in my scss, the css file generated are in `/dist/styles/main.css`, and the font file is in `/dist/font.ttf`, and the generated css file has the wrong `url` of the font file. Also the build gets stucked at building `processing.scss` forever, but if i commented other entries all out, `processing.scss` gets successfully bundled. Also is it possible to put all bundled files in one big folder when the entries are from different folders (instead of creating `scripts` and `styles` subdirectories in `dist`)

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
const Bundler = require("parcel-bundler");

const entries = [
	"./public/scripts/main.js",
	"./public/styles/main.scss",
	"./public/scripts/track.js",
	"./public/scripts/md.js",
	"./public/styles/md.scss",
	"./public/styles/resume.scss",
	"./public/styles/processing.scss",
	"./public/styles/links.scss"
]

const bundler = new Bundler(entries, {

	outDir: "./public/dist",
	publicUrl: "/dist",
	cache: process.env.NODE_ENV !== "production",
	minify: process.env.NODE_ENV === "production",
	watch: process.env.NODE_ENV !== "production"

});

bundler.bundle()
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.2
| Node             | 10.4.1
| npm/Yarn         | 1.7.0
| Operating System | macOS High Sierra 10.13.4

**Comment by slmjkdbtl** [comment]
possible duplicate of #1303

**Comment by mischnic** [comment]
Is this still an issue? Can you provide a reproduction?

**Comment by mischnic** [comment]
> I'm using a font with `@font-face` and `url` in my scss, the css file generated are in `/dist/styles/main.css`, and the font file is in `/dist/font.ttf`, and the generated css file has the wrong `url` of the font file.

This part is described in issue #1801.
