### ISSUE TITLE
Parcel Build For ES Modules & Inline CSS

### ISSUE THREAD

**Issue by rodoabad** [parcel-bundler/parcel#1599]
# ❔ Question

I'm wondering if there's a way for Parcel to build the package for ES modules. Is this more of a Babel issue when building?

Additional question.

Can I inline the CSS being produced? Right now when I do `npx parcel build`, it creates a separate CSS file. I'd like it to be inline.

## 🔦 Context

After reading the long discussion at https://github.com/webpack/webpack/issues/1979. I would like to transpile everything sans ES Modules so that I can take advantage of the `module` property in `package.json`.

It seems to be that the `module` property is supported by Parcel (I could be wrong here)? Since I have it in a test module and when I import a file with a `module` defined it tries to use it.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.2
| Node             | 8
| npm/Yarn         | npm
| Operating System | Mac

## 🔖 : References

https://github.com/babel/babel/issues/6328
https://github.com/webpack/webpack/issues/1979
https://github.com/parcel-bundler/parcel/pull/559

**Comment by devongovett** [comment]
ES module output is supported in v2. Inline CSS can be implemented with #3726.

```css
import cssText from 'bundle-text:./style.css'
```
