### ISSUE TITLE
Hitbox on buttons on https://parceljs.org/ too small

### ISSUE THREAD

**Issue by vhag** [parcel-bundler/parcel#16]
Using Google Chrome 62.0.3202.94 on Windows 10 the "Get Started" and "Github" buttons on https://parceljs.org/ are only clickable on the lower half of the button.

**Comment by morajabi** [comment]
@vhag It's related to the other repo: https://github.com/parcel-bundler/website

**Comment by vhag** [comment]
Okay, thank you, I will close this issue.
