### ISSUE TITLE
the national flag on language list

### ISSUE THREAD

**Issue by satsuya0114** [parcel-bundler/parcel#1601]
# 🙋 feature request

Can you help to take off the parcel [official web](https://en.parceljs.org/) National flag in front of the language select ?

## 🤔 Expected Behavior

![](https://i.imgur.com/dqwGi4Q.png)

## 😯 Current Behavior

![](https://i.imgur.com/EwfLnFN.png)

## 🔦 Context

Hello, I am a Taiwanese user ( from Taiwan ). I like Parcel and its official web, and feel happy that provide multi language version. 

But when I wanted to change web language to change to Chinese version, I saw the National Flag of PRC (🇨🇳) in front of the Chinese option (中文). I feel not good and  disagreeable😵😰😱, cause I am Taiwanese but not Chinese. 

Malaysia (🇲🇾) , Singapore (🇸🇬) and Taiwan (🇹🇼) all speak Chinese, BUT we are definitely not the people of P.R.C. .  
Other case: British (🇬🇧), Canadian (🇨🇦),  and other country that use English as official language (👉[see here](https://projects.ncsu.edu/grad/handbook/docs/official_language_english.htm)) are not American of USA (🇺🇸). 

So, I just suggest you to take off the National flag from language select list, Thank you.🙏

## 💻 Examples

![](https://i.imgur.com/dqwGi4Q.png)

👉  [yarn official web](https://yarnpkg.com/en/)

**Comment by QAQLiuCong** [comment]
Whether or not there is a national flag does not matter, but Taiwan belongs to China. Thank you.

**Comment by DeMoorJasper** [comment]
Please move to https://github.com/parcel-bundler/website
