### ISSUE TITLE
Doesn't work at all on OSX + readme is missing "getting started" steps

### ISSUE THREAD

**Issue by gerchicov-bp** [parcel-bundler/parcel#1604]
# 🐛 bug report

Tried to run it step by step using `npm` and get stuck on step 3:

```
$ parcel index.html
bash: parcel: command not found
$ node parcel index.html
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '/Users/gerchicov/Documents/nodejs/vuesax-test/parcel'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
```

## 😯 Current Behavior

It just doesn't work

## 💁 Possible Solution

Fix readme file because `parcel index.html` **won't work with your steps**.
Fix a bug if it exists.

## 💻 Code Sample

code was taken fully from readme. The directory contains previously installed `vuesax`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.2
| Node             | 10.4.1
| npm/Yarn         | npm 6.1.0
| Operating System | OSX 10.13.4

**Comment by DeMoorJasper** [comment]
Did you install parcel globally?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gerchicov-bp** [comment]
@DeMoorJasper
yes - `npm install -g parcel-bundler`

**Comment by DeMoorJasper** [comment]
Perhaps restart your terminal, i’m not sure why this happens I guess it’s more of a misconfig as it just doesnt register parcel which is the responsibility of npm

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gerchicov-bp** [comment]
@DeMoorJasper
nothing is changed

**Comment by danburzo** [comment]
@gerchicov-bp I'm not able to reproduce your issue, and I'm on a similar setup. When you do `npm install -g parcel-bundler`, is the install successful? Have you seen anything that suggests there was an error?

**Comment by gerchicov-bp** [comment]
finally found a solution:
- remember a path which is returned by command `npm get prefix`
- add this path to environment variables
Don't know how but now it works

**Comment by iamclaytonray** [comment]
@gerchicov-bp - You could optionally use `npx` in the future, and just install deps locally 😄
