### ISSUE TITLE
Doesn't work with posthtml-favicons plugin

### ISSUE THREAD

**Issue by jessehattabaugh** [parcel-bundler/parcel#1607]
# 🐛 bug report

I'm attempting to use the [`posthtml-favicons`](https://github.com/mohsen1/posthtml-favicons) plugin with parcel.

## 🎛 Configuration

package.json
```js
{
  "author": "",
  "bugs": {
    "url": "https://github.com/jessehattabaugh/parceljs-posthtml-favicons/issues"
  },
  "description": "testing a bug with the posthtml-favicons plugin and parceljs",
  "devDependencies": {
    "parcel": "^1.9.2",
    "posthtml-favicons": "^1.0.0"
  },
  "homepage": "https://github.com/jessehattabaugh/parceljs-posthtml-favicons#readme",
  "license": "ISC",
  "main": "index.js",
  "name": "parceljs-posthtml-favicons",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/jessehattabaugh/parceljs-posthtml-favicons.git"
  },
  "scripts": {
    "start": "parcel build index.html",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "version": "1.0.0"
}
``` 

.posthtmlrc
```js
{
    "plugins": {
        "posthtml-favicons": {
            "configuration": {
                "path": "./"
            },
            "outDir": "./dist"
        }
    }
}
```

index.html
```html
<!doctype html>
<html>
    <head>
        <link rel="icon" href="jesse.jpg" />
    </head>
    <body>
    </body>
</html>
```

## 🤔 Expected Behavior

Should generate icon files in the `./dist` dir

## 😯 Current Behavior

![error message](https://raw.githubusercontent.com/jessehattabaugh/parceljs-posthtml-favicons/master/issue.png)

## 💻 Code Sample

https://github.com/jessehattabaugh/parceljs-posthtml-favicons

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  ^1.9.2
| Node             | v10.5.0
| npm         |  6.1.0
| Operating System | Windows 10 w/ Ubuntu Bash shell

**Comment by mohsen1** [comment]
You can close this. Issue is filed here:
https://github.com/mohsen1/posthtml-favicons/issues/3

**Comment by jessehattabaugh** [comment]
Is there some documentation somewhere that mentions `.posthtmlrc` can be a .js file? The parceljs.com docs only briefly talk about `.posthtmlrc`. Why does this plugin need to be `require()`ed when others don't?

**Comment by jessehattabaugh** [comment]
Seems that this plugin isn't compatible with the `.json` format of `.posthtmlrc`. Why would that be?
