### ISSUE TITLE
the code comments bug (代码被注释了...)

### ISSUE THREAD

**Issue by xingzhefeng** [parcel-bundler/parcel#1608]
![image](https://user-images.githubusercontent.com/3190231/41829748-240854a8-786f-11e8-84f9-178e76c30166.png)
![image](https://user-images.githubusercontent.com/3190231/41829752-2d343826-786f-11e8-9f69-5de4d882187b.png)
parcel  1.9.1 19.2 
win10

**Comment by DeMoorJasper** [comment]
A fix for this should have been released in 1.9.2 #1576

Please update to parcel 1.9.2 or 1.9.3
