### ISSUE TITLE
Latest with --experimental-scope-hoisting still does not work

### ISSUE THREAD

**Issue by goyney** [parcel-bundler/parcel#1611]
# 🐛 bug report

Pulled 1.9.3 with the fixes to tree-shaking. Didn't change any of our already working and building code from 1.9.2. Ran build with the `--experimental-scope-hoisting` flag. Now, it builds without error. However, going to the built package shows this JS error:

```
Uncaught ReferenceError: $409$var$Arr is not defined
    at Object.Dxa [as toByteArray] (client.745ce2b5.js:1)
    at N$ (client.745ce2b5.js:1)
    at i$ (client.745ce2b5.js:1)
    at zwa (client.745ce2b5.js:1)
    at $Z (client.745ce2b5.js:1)
    at g (client.745ce2b5.js:1)
    at Jg (client.745ce2b5.js:1)
    at client.745ce2b5.js:1
    at client.745ce2b5.js:1
    at client.745ce2b5.js:1
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    "env",
    "react",
    "stage-3"
  ],
  "env": {
    "test": {
      "plugins": [
        "rewire"
      ]
    }
  },
  "plugins": [
    [
      "module-resolver",
      {
        "root": [
          "./",
          "./components",
          "../modules",
          "../node_modules"
        ],
        "alias": {
          "style": "./style"
        }
      }
    ],
    "transform-class-properties"
  ]
}

```

## 🤔 Expected Behavior

Package builds and works with `--experimental-scope-hoisting`.

## 😯 Current Behavior

Does not.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.3
| Node             | 10.4.1
| Yarn         | 1.7.0
| Operating System | macOS

**Comment by mischnic** [comment]
@adriaanwm This issue was already fixed by PR #2292.
