### ISSUE TITLE
Using ReactContext with TypeScript causes build issue with Provider tag

### ISSUE THREAD

**Issue by mhamrah** [parcel-bundler/parcel#1615]
# 🐛 bug report

I am using Parcel to bundle a React App written in Typescript. When using ReactContext, specifying `<MyContext.Provider>` as a JSX tag causes a build error, assuming because the bundler does not know how to handle the `.Provider` portion of the tag: 

```
Unexpected token (47:34)
  45 |         WithAuthentication.prototype.render = function () {
  46 |             var user = this.state.user;
> 47 |             return (<MyContext_1["default"].Provider value={user}>
     |                                   ^
  48 |           <Component />
  49 |         </MyContext_1["default"].Provider>);
  50 |         };
```

There is a full app at https://github.com/mhamrah/parcel-issue which recreates the issue in a simple way.

## 🎛 Configuration (.babelrc, package.json, cli command)

I am only specifying a .babelrc file with a `react-app` preset (see https://github.com/mhamrah/parcel-issue/blob/master/.babelrc). But it would be nice for this to work with zero-config. 

## 🤔 Expected Behavior

Parcel supports parsing JSX with properties using Typescript, with zero config.

## 😯 Current Behavior

There is an `Unexpected Token` error when hitting the left-bracket `[` from the transpiled JSX tag: `<AuthContext_1["default"].Provider value={user}>`

## 🔦 Context

I would like to use the new ReactContext API in a TypeScript application

## 💻 Code Sample

https://github.com/mhamrah/parcel-issue

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.3
| Node             | 8.11.2
| npm/Yarn         | npm 6.1.0
| Operating System | ubuntu 18.04

**Comment by MisterAJ** [comment]
@mhamrah have you had any luck with this? I'm getting similar behaviour with Fragment.
