### ISSUE TITLE
cannot find external dependency of linked module

### ISSUE THREAD

**Issue by alidlo** [parcel-bundler/parcel#1617]
# 🐛 bug report

Hey guys, thanks for all the great work with Parcel!

I'm actually creating a SSR framework for React that uses Parcel. However, since Parcel doesn't seem to have great support for external dependencies yet, I'm using rollup to bundle my package code, and Parcel to bundle the application code.

The problem I'm running into is that Parcel is unable to find the external depencies of linked modules - e.g. I'm getting an `cannot find module react` error. But I do not get this error if I download the actual package. So I'm guessing Parcel is treating the linked module differently. 

This might be related to #948 But I actually want parcel to use the compiled code, rather than the source code.

## 🤔 Expected Behavior

Parcel treats compiled linked modules the same as downloaded modules.

## 😯 Current Behavior

External dependency is not found in linked module but found in downloaded one.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.2
| Node             | 10.5.0
| Yarn         | 1.7.0
| Operating System | Windows

**Comment by myronliu347** [comment]
How to solve ？

**Comment by sznowicki** [comment]
That seems to be a valid bug ticket still. Every time I try to develop some npm react libraries which are linked locally to parcel setup, parcel fails to build development env.
