### ISSUE TITLE
what's simplest way to Inline SVG into html?

### ISSUE THREAD

**Issue by safareli** [parcel-bundler/parcel#1622]
I want to inline contents of a file (which is generated SVG sprite) into an HTML. I could use `fs.readFileSync` [as described here](https://parceljs.org/assets.html#javascript) and then embed contents in dom, is it how people do it?

**Comment by jt3k** [comment]
I also do not know how to correctly insert the contents of svg sprites, but ...
Embedding using client-javascript can help you?
https://github.com/jonathantneal/svg4everybody

I've been using it for a long time, and it helped me

**Comment by DeMoorJasper** [comment]
You can use https://github.com/albinotonnina/parcel-plugin-inlinesvg or use `fs.readFileSync`

**Comment by perymimon** [comment]
you can change the extension to `.html` and it will work

**Comment by perymimon** [comment]
also I clean the `.svg` with the npm tool `svgo` and magicly I can import the `.svg` like regular `html` file

**Comment by epiphone** [comment]
[svgr](https://github.com/smooth-code/svgr) is pretty nifty too:
1. install plugin: `yarn add @svgr/parcel-plugin-svgr`
2. import svg: `import MyIcon from 'my-icon.svg' `
3. use as any other component: `<MyIcon />`

Also if you're running Typescript add a following type declaration to suppress errors on importing `.svg`s:
```typescript
// svg-shim.d.ts
declare module '*.svg' {
  const content: any
  export default content
}
```

**Comment by BigBadaboom** [comment]
For future readers: the shim file in @epiphone's comment was all I needed to get import working.

**Comment by anantakrishna** [comment]
We can use PostHTML with Parcel: https://parceljs.org/html.html#posthtml. Just add https://github.com/andrey-hohlov/posthtml-inline-svg, and here it is, SVG gets inlined.

Install it: `npm i -D posthtml-inline-svg`

Add config:
```js
// posthtml.config.js
module.exports = {
  plugins: {
    'posthtml-inline-svg': {
      cwd: './src/icons',
    },
  },
};
```

And add this into your HTML:
```html
<icon src="path/to/icon.svg"></icon>
```
