### ISSUE TITLE
Bug using Parcel with Emotion and React

### ISSUE THREAD

**Issue by krsjoseph** [parcel-bundler/parcel#1623]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  presets: [
    [
      "env",
      {
        targets: {
          browsers: [">0.25%", "not op_mini all"],
        },
      },
    ],
    "react",
  ],
  env: {
    production: {
      plugins: [
        ["emotion", { hoist: true }],
        "transform-decorators-legacy",
        "transform-class-properties",
        "transform-object-rest-spread",
        "syntax-dynamic-import",
        "transform-react-remove-prop-types"
      ],
    },
    development: {
      plugins: [
        ["emotion", { sourceMap: true, autoLabel: true }],
        "transform-decorators-legacy",
        "transform-class-properties",
        "transform-object-rest-spread",
        "syntax-dynamic-import"
      ],
    },
  },
}

```

## 🤔 Expected Behavior

Component should be complied

```js

import React, { Component, } from "react";
import styled from "react-emotion";

const Card = styled.div({
  boxShadow: "0 3px 6px rgba(0, 0, 0, 0.16)",
});

class App extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <div className="container my-5">
        <Card className="row justify-content-center">
          <div className="col-lg-7">{this.props.children}</div>
        </Card>
      </div>
    );
  }
}

export default App;

```

## 😯 Current Behavior

Component does not render and throws error

Uncaught TypeError: Super expression must either be null or a function, not undefined
    at _inherits (react-dom.development.js:17430)
    at react-dom.development.js:17430
    at Object.parcelRequire.8.react (react-dom.development.js:17430)
    at newRequire (beacon-client.072a87d9.js:48)
    at localRequire (beacon-client.072a87d9.js:54)
    at Object.parcelRequire.4.react (routes.js:20)
    at newRequire (beacon-client.072a87d9.js:48)
    at parcelRequire.18 (beacon-client.072a87d9.js:80)
    at beacon-client.072a87d9.js:106
_inherits @ react-dom.development.js:17430
(anonymous) @ react-dom.development.js:17430
parcelRequire.8.react @ react-dom.development.js:17430
newRequire @ beacon-client.072a87d9.js:48
localRequire @ beacon-client.072a87d9.js:54
parcelRequire.4.react @ routes.js:20
newRequire @ beacon-client.072a87d9.js:48
parcelRequire.18 @ beacon-client.072a87d9.js:80
(anonymous) @ beacon-client.072a87d9.js:106

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.3
| Node             | 8.11
| Yarn         | 1.6.0
| Operating System | 10.14

**Comment by buronnie** [comment]
@krsjoseph I tried your config and it seems working. Could you make sure you have installed `babel-preset-react`, `emotion`, `babel-plugin-transform-decorators-legacy`, `babel-plugin-transform-class-properties`, `babel-plugin-transform-object-rest-spread`, `babel-plugin-syntax-dynamic-import` and `babel-plugin-transform-react-remove-prop-types` as `dev-dependencies`? 

Here is the example: https://github.com/buronnie/parcel-issue1623-emotion-react
