### ISSUE TITLE
Parcel can't resolve file dependency

### ISSUE THREAD

**Issue by aaronbeall** [parcel-bundler/parcel#1624]
# 🐛 bug report

When I tried bundling with a `file:` dependency (a local clone of [handsontable](https://github.com/handsontable/handsontable)) I get the error:

> 🚨  /Users/abeall/Documents/parcel/filedep/index.js:1:25: Cannot resolve dependency 'handsontable'
> 1 | import Handsontable from "handsontable";

## 🎛 Configuration (.babelrc, package.json, cli command)

**package.json**
```
{
  "name": "filedep",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "parcel",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "handsontable": "file:../handsontable"
  },
  "devDependencies": {
    "parcel-bundler": "^1.9.3"
  }
}
```

**index.html**
```
<html>
  <head>
    <title>Parcel bundler test</title>
  </head>
  <body>
    <div id="root"/>
    <script src="index.js"></script>
  </body>
</html>
```

**index.js**
```
import Handsontable from "handsontable";
console.log("Hello", Handsontable)
```

No `.babelrc` though I was initially using `tsconfig.json`, but I removed that as shown above and still see the issue.

**cli command:** `npm start` (which runs `parcel` as shown above)

## 🤔 Expected Behavior

No error

## 😯 Current Behavior

> 🚨  /Users/abeall/Documents/parcel/filedep/index.js:1:25: Cannot resolve dependency 'handsontable'
> 1 | import Handsontable from "handsontable";

## 🔦 Context

I'm using a local filesystem repo clone instead of the [npmjs package](https://www.npmjs.com/package/handsontable) because I'm making some changes and testing locally.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.3
| Node             | 8.6.0
| npm/Yarn         | 5.2.0
| Operating System | MacOS High Sierra

**Comment by adjenks** [comment]
I second this motion.

**Comment by adjenks** [comment]
@aaronbeall Have you found a workaround for this yet?

**Comment by adjenks** [comment]
Unstale!

**Comment by Inateno** [comment]
Jayzuss still nothing there ?
I have one version working on my laptop, the same on the desktop do not work.
I suspect that since yarn was previously setuped on the project (on the laptop) it does something ?

Not sure...
I run same node/npm version on both projects...
