### ISSUE TITLE
The process does not end after the completion of the custom environment variable packaging.

### ISSUE THREAD

**Issue by zhayes** [parcel-bundler/parcel#1626]
![image](https://user-images.githubusercontent.com/17758062/41957522-d3f433ea-7a19-11e8-8652-a818cd5e9136.png)
The environment variable is configured to define the interface address
```
let baseUrl = 'http://test-xxx.com';

if(process.env.NODE_ENV === 'production') baseUrl = 'http://xxx.com';
```
But after packaging , the process does not end;

Although my environment variable is not production, my command is build, so should end the process.

My project was deployed online through shell scripts, but your process was not closed, and I could not tell if the packaging was finished.

Hope to solve it quickly.

**Comment by jkappers** [comment]
Same issue here using yarn. 

```
"scripts": {
  "build": "parcel build index.html --no-cache --public-url=/"
}
```

Running `yarn build` works as expected.
Running `NODE_ENV=qa yarn build` builds, but the process hangs.
