### ISSUE TITLE
Support <script src="tsconfig.json"></script>   as asset type 

### ISSUE THREAD

**Issue by mihailik** [parcel-bundler/parcel#1627]
# 🙋 feature request

`Parcel` handles TypeScript compilation/post-processing in its custom way, which limits certain useful TS scenarios.

To allow simple way to use full TS feature set, it would be super cool to let TS handle more through `tsconfig.json`,  and feed results into `parcel` pipeline at that stage.

# Suggested approach

When `.ts` asset is referred, the usual `parcel` handling is used. But if `tsconfig.json` is used as asset, `parcel` fires TS compiler, which discovers and processes inputs on its own.

TypeScript would produce one or many outputs, which `parcel` would then pass through its remaining processing/transforms.

The disk cache would be less involved in this case, as processing is not file-per-file anymore. But in-memory partial recompilation is a part of TS compiler.

**Comment by mohsen1** [comment]
I'm not sure if we can swap Parcel Resolver with TypeScript. It does a lot of things:

https://github.com/parcel-bundler/parcel/blob/2aa72153509a72c0fd247b3e94495071ae61f717/src/Resolver.js#L10-L23

**Comment by mihailik** [comment]
In this case TypeScript will only go as far as resolving **within** its set of `*.ts/*.tsx` sources.

The result of TS compilation will pipe through the same sophisticated `parcel` resolver.

**Comment by mmmeff** [comment]
Not a fan of this approach - it feels slightly off-mark of the zero-config goal of Parcel to require an extra configuration step for proper typescript support. 

I think it's safe to say the vast majority of devs looking to use typescript in parcel are getting a sub-optimal experience when they directly import a ts/tsx file. 

The correct default behavior should be to use the `tsc` toolchain and allow it to use the local `tsconfig.json` file if it exists or fall back to defaults (which `tsc` currently does by default). Anything else just feels like reinventing the wheel.

**Comment by mihailik** [comment]
@mmmeff I am totally confused — you've described what I have suggested, said that's your preferred correct way, but at the same time disagree with it?

The original suggestion is to **avoid** reinventing the wheel, and rely on TS wheels more.

It would be great to **be able to** use a whole of `tsc` processing in more holistic way, when/if a developer finds it fit for their app.

**Comment by devongovett** [comment]
Parcel 2's resolver supports tsconfig settings.
