### ISSUE TITLE
Why I use "parcel watch src/index.html", and then  generated dist/index.html has Wrong path about  I want to import the JS and CSS file

### ISSUE THREAD

**Issue by Likebard** [parcel-bundler/parcel#163]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
 bug report

This is my This is my contents of dist/index.html.
```js
<html><head>
    <link rel="stylesheet" href="/dist/70ff6adcda1019612606fd7515c8afe8.css"></head><body>
        <div id="root"></div>
        <script src="/dist/70ff6adcda1019612606fd7515c8afe8.js"></script>
    </body>
</html>
```
![_017](https://user-images.githubusercontent.com/13894597/33797111-1c1f2794-dd3d-11e7-9b23-2f3186d0500e.png)

**Comment by davidnagli** [comment]
What's wrong with the path? It looks fine

**Comment by DeMoorJasper** [comment]
He probably just opened the index.html file in the browser and then it doesn't load js and css due to this using absolute paths. Or he pointed his webserver to another directory than his www directory which would also cause this.

**Comment by adrianfaciu** [comment]
When you build the output you can use --public-url argument to specify the root. For example: 
`parcel build index.html --public-url='/'`

**Comment by Likebard** [comment]
@davidnagli @DeMoorJasper  I doesn't look fine. The script tag of the generated HTML file includes dist/xxxxxx.js but the REAL path of that js file is ./xxxx.js. The generated js file and the HTML file are in the same dist directory  actually. How do I fix this?

**Comment by davidnagli** [comment]
Based on the screenshot you sent, the real path of the file should be `dist/xxxxxx.js`, not `./xxxx.js`

I'm really sorry if I'm misunderstanding you

**Comment by davidnagli** [comment]
Maybe you're looking for the `--out-dir` command, which would let you specify the output directory

Note: an alias for `--out-dir` is `-d` (they both do the same thing.

Example usage

```
parcel src/index.html -d build
```

**Comment by Likebard** [comment]
@davidnagli Thanks. It works.

**Comment by xcatliu** [comment]
@davidnagli Is there a way to use the relative path instead of absolute path?
A common practice is to output the html, js and css to `public` dir, and host the `public` dir as the root dir.

**Comment by deepakkadarivel** [comment]
`parcel build index.html --public-url ./`

Will solve the issue of the invalid path to js and CSS files.

**Comment by rheajt** [comment]
I have tried all of the solutions above, but I still get the compiled index.html pointing to
`<script src="/dist/......js"></script>` instead of `src="....js"`

If I want to compile everything into a single dist/ folder and serve that folder, how can I make sure the paths are correct?
