### ISSUE TITLE
Use different dist for DEV/PROD,  and also rebuild PROD in background

### ISSUE THREAD

**Issue by mihailik** [parcel-bundler/parcel#1630]
# 💬 RFC

Currently DEV and PROD output results into the same `/dist`. Easy to overwrite and pick wrong flavour for deployment!

Defaulting DEV to a temporary directory would be helpful. By the way,  `/.cache` is already a private directory, why not direct DEV builds into `/.cache/dev` or something?

Additionally, `parcel` can rebuild PROD in background whenever DEV is rebuilt.

## 🔦 Context

A normal line of development is to fire `parcel index.html` and keep editing files, expecting updates in browser.

Then, when a result is achieved — re-run `parcel build index.html` again to produce optimised builds. But that run takes longer time, potentially. Time wasted!

## Fits the workflow

Rebuilding PROD in background on the back of DEV build will eliminate wait, without slowing down DEV work.

Normally, when DEV change is made, a developer spends at least few seconds checking the outcome, looking at console etc. Even though PROD builds are bit slower, they are fast enough to complete in that time. By the time a developer completes with visual glance/check of DEV, the build of PROD is done or 90% done. Everybody's happy!

Another help is that nobody needs to REMEMBER to run PROD build in this case.

**Comment by DeMoorJasper** [comment]
Using 2 different folders sounds like a great improvement.

Building a production build in the background sounds like an insane performance boost, but very hard to pull off.

I don't think the following should be the case: "nobody needs to REMEMBER to run PROD build in this case". As you are never 100% sure every file has been properly optimised and rebuilt. And production builds from cache are almost instant anyways. (if most assets are cached, which would be the case with background bundling)

Another issue will be env variables, as they get set in the workers we'd have to either reset the workers between background (prod) tasks and normal (dev) tasks, slowing down builds immensely or find a way to skip the env setting and use the options.env object.

In both scenario's we'd have 2 different options objects, as build and production are 2 different setups, and this would also require some kind of config file as we don't know what a persons production command looks like from the dev command. As most prod rebuilds are pretty fast (if using cache), I don't think it's currently worth the insane amount of extra work, to get this to work properly.

**Comment by mihailik** [comment]
Sounds reasonable.

The implementation for background PROD build should probably run in a cluster sub-process and thus not need any resetting of environment etc.

But that is still a significant chunk of work.

**Comment by mihailik** [comment]
And just to clarify:  if this is implemented (whenever later),   a little visual cue for "PROD is pending" would definitely be the right UX.

```
> front-end@1.0.0 start C:\Users\n599754\code\grt-web-charting\front-end
> parcel index.html --out-dir .cache/dev

Server running at http://localhost:52331 - configured port 1234 could not be used.
√  Built development in 1.84s.   ...pending production?
√  Built development in 1.84s.   ...building production...
√  Built development in 1.84s.   production in 2.03s.
```

Then indeed you'd never need to remember to run PROD build.
