### ISSUE TITLE
multiple entries error

### ISSUE THREAD

**Issue by ZWkang** [parcel-bundler/parcel#1640]
# 🐛 bug report

when i use multiple entries in middleware, it looks have some error.

## 🎛 Configuration (.babelrc, package.json, cli command)

```
my folder looks like this
- A 
  - index.html
  - index.scss
  - index.js
- B
  - index.html
  - index.scss
  - index.js
- common
  - common.js
  - common.scss
```
```
A/index.html
..... some tags...
<script src='../common/common.js'></sciprt>
<script src= './index.js'></script>
.....
```
```
B/index.html
..... some tags...
<script src='../common/common.js'></sciprt>
<script src= './index.js'></script>
.....
```
```
// here is common.js

import './common.scss';

// this file also have some js code.
```

```
// use middleware like this.
new Bundler([
  './A/index.html',
  './B/index.html'
])
```

## 🤔 Expected Behavior

i expect have one common.css file in dist.
and A/index.html have link to common.css
and B/index.html have link to common.css

## 😯 Current Behavior

but now ,it just resolve the first file in bundle use.

new Bundler([
  './A/index.html',
  './B/index.html'
])
just A/index.html have link to common.css

A/index.html
![image](https://user-images.githubusercontent.com/15853907/42095295-c95c8a6e-7be4-11e8-85ce-0cc6461b30fd.png)

B/index.html
![image](https://user-images.githubusercontent.com/15853907/42095323-dbf1fdb2-7be4-11e8-96e9-769c1f8219ea.png)

when i change A/index.html B/index.html position in arrary
make it looks like this

new Bundler([
  './A/index.html',
  './B/index.html'
])

now just B/index.html has link to common.css

## 💁 Possible Solution

i think maybe the multiple entries  resolve the array entry have some problem??
beacuse i have many try cases ,that all got error result.
if you want to see , i can show more~~

## 🔦 Context

in fact , i just want the common.scss can use in every file that they want.and just pack one common.scss file in dist .
it can good to reuse my code .

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.3 |
| Node             | 10.3.0 | 
| npm/Yarn         | 6.1.0 |
| Operating System | window7 |

**Comment by Hezard** [comment]
+1 the same issue
