### ISSUE TITLE
Correct way: lazy loading assets from static folder or...?

### ISSUE THREAD

**Issue by daggerok** [parcel-bundler/parcel#1644]
# ❔ Question

Correct lazy loading with parcel

## 🔦 Context

I'm writing a blog. Each blog post content located in a separate file. before build automatocally generated js file with paths, so later I can use these paths to import markdown/asciidoctor file for converting posts to html for rendering

## 💻 Code Sample

posts sources structure

```
./src/posts/2018/06/29/ololo.md
./src/posts/2018/06/30/trololo.adoc
```

I also have script witch is on build parsing `./src/posts` folder and creates `./src/posts.js` file for app lazy load. Output like so:

```javascript
module.exports = {
  posts: [
    '2018/06/29/ololo.md',
    '2018/06/30/trololo.adoc',
  ],
};
```

lastly I can programmatically according to current pagination rules lazy load my posts and convert them into html like so:

```javascript
const { posts } = requre('./posts.js');
// ...skipped
posts.filter(/*pagination/whatever predicate*/).forEach(path => {
  import(`./posts/${path}`)
    .then(data => /*convert to html + hljs*/)
    .then(html => toBeRendered(html))
});
```

Compilation is OK, but on runtime in browser console I'm getting errors:

```
GET http://localhost:1234/posts/2018/06/29/ololo.md 404 (Not Found)
GET http://localhost:1234/posts/2018/06/30/trololo.md 404 (Not Found)
```

Can anybody suggest me correct way?

I believe for production (`parcel build ./stc/index.html`) problem can be fixed if I will automate copying `./src/posts/** -> ./dist/posts/**` posts folder as is

but even so, I don't know what workaround could be for dev mode (`parcel ./src/index.html`) - probably only via some parcel-serve-static-plugin or embedded functionality...

Thanks in any advise.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.3
| Node             | v8.11.3
| npm/Yarn         | 6.1.0/-
| Operating System | mac os x

**Comment by DeMoorJasper** [comment]
Parcel doesn't support this: `import(`./posts/${path}`)` due to it not being statically evaluatable.

Duplicate of #1099 #125 #1006

**Comment by daggerok** [comment]
this code 

```javascript
import('./posts/**.md')
# import('./posts/*.md') // this also
```

cause error:

> markdowns-app@1.0.0 start /private/tmp/parcel-examples/markdowns
> parcel src/index.html

Server running at http://localhost:1234 
🚨  ENOENT: no such file or directory, open '/private/tmp/parcel-examples/markdowns/src/posts/**.md'
Error: ENOENT: no such file or directory, open '/private/tmp/parcel-examples/markdowns/src/posts/**.md'

**Comment by daggerok** [comment]
at the moment found this solution worked:

```js
import marked from 'marked';

const mapping = require('./posts/**.md'); // { "filename.md": "filename.hash[8].md" }
const keys = Object.keys(mapping);
const values = Object.values(mapping);
values.forEach(value => {
  fetch(value)
    .then(resp => resp.text())
    .then(text => marked(text))
    .then(html => document.querySelector('#app').innerHTML += html);
});
```

**Comment by DeMoorJasper** [comment]
Sorry thought `import` also worked for the glob require, my bad.

Hope this little script helps a bit to explain globs, if it wasn't clear yet, but seeing your latest comment I think you pretty much already know how to tackle this

```Javascript
const posts = require('./posts/**/*.js');

// Returns all the objects (inlined in the bundle)
console.log(posts);

// Returns all the paths
const postsMD = require('./posts/**/*.md');

// Load all posts...
Promise.all(Object.keys(postsMD).map(year => {
  let yearPosts = postsMD[year];
  return Promise.all(
    Object.keys(yearPosts).map(postKey => 
      fetch(yearPosts[postKey])
      .then(resp => resp.text())
    )
  );
}))
.then(res => console.log(res) /* Content of md file should be printed in console */)
.catch(err => console.error(err));
```

You can have a look at https://github.com/isaacs/node-glob to get more details on globs

**Comment by daggerok** [comment]
@DeMoorJasper, thank you for your snippet
Based on it I've got this worked with subdirectories, too:

```js
import 'babel-polyfill';
import marked from 'marked';

const yearsObject = require('./posts/**/*.md');
const years = Object.keys(yearsObject);

Promise.all(years.map(year => {
  const monthsObject = yearsObject[year];
  const months = Object.keys(monthsObject);

  return Promise.all(months.map(month => {
    const daysObject = monthsObject[month];
    const days = Object.keys(daysObject);

    return Promise.all(days.map(day => {
      const postsObject = daysObject[day];
      const mdFiles = Object.keys(postsObject);

      mdFiles
        .map(file => postsObject[file])
        .forEach(
          path => fetch(path)
            .then(resp => resp.text())
            .then(mdContent => marked(mdContent))
            .then(html => document.querySelector('#app').innerHTML += html));
    }));
  }));
})).catch(err => console.error(err));
```

I think issue could be closed for now.

---
Regards,
Maksim

**Comment by Stradivario** [comment]
Try using system js for this mechanism.Example will be to request bundled source provided like module and load it dynamically in your system.

Chech this out


https://github.com/rxdi/starter-client-side-advanced

In particular

https://github.com/rxdi/starter-client-side-advanced/blob/master/src/app/core/core.module.ts


```typescript
import { Module } from "@rxdi/core";
import { RendererService } from "./services/renderer";
import { HelloWorldService } from "./services/hello-world.service";

@Module({
    services: [
        RendererService,
        HelloWorldService,
        {
            provide: 'ipfsDownloadedFactory',
            useDynamic: {
                link: 'https://ipfs.infura.io/ipfs/QmdQtC3drfQ6M6GFpDdrhYRKoky8BycKzWbTkc4NEzGLug'
            }
        }
    ]
})
export class CoreModule { }
```
Here the whole application will wait untill that particular service is resolved you could implement such a mechanism by your own.

Regards,
Kristiyan Tachev
