### ISSUE TITLE
bug: `alias` will add deps based on absolute imports

### ISSUE THREAD

**Issue by iamclaytonray** [parcel-bundler/parcel#1645]
# 🐛 bug report

Currently, when you setup a project for absolute imports and use those imports somewhere in your code, Parcel will identify that as a missing module and add that to your deps.

## 🎛 Configuration (.babelrc, package.json, cli command)

I don't have a babel config setup. I suppose I am using Parcel's default config? (Just started using this bundler like 2 days ago so haven't gotten used to how things are done.)

## 🤔 Expected Behavior

Ideally, when you are dealing with absolute paths, Parcel should understand this and if an import matches an `alias`, Parcel should ignore installing it as a dep and move on.

## 😯 Current Behavior

There are no errors or stack traces. Technically, Parcel is behaving as it should.

## 💁 Possible Solution

My _very naive_ approach would be a simple conditional. If an import pattern matches an alias pattern, ignore installing that as a dependency, else, go ahead and install it.

## 🔦 Context

I would like to use absolute imports without having potential dependencies that I don't need. This technically hasn't affected me, though, I just started using Parcel and only on a very small boilerplate to play around with it. I assume that this could lead to further problems down the road and overall, I'd like to keep my dependency tree as clean as possible.

A real-world effect could be onboarding new developers to a project that uses Parcel. They could potentially be confused why a project has certain dependencies that are not being used or confused that our absolute imports are actually being brought in through a package, just with some weird syntax. It's not the likeliest problem but I suppose it could happen. Other than that, I don't think it actually causes a real issue.

## 💻 Code Sample

[Here is a small repo](https://github.com/iamclaytonray/react-gql-ts-parcel)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.3
| Node             | 8.11.3
| npm/Yarn         | 1.7.0
| Operating System | macOS 10.3.4
| TypeScript | 2.9.2

**Comment by DeMoorJasper** [comment]
I think this is overcomplicating the resolver, you can always call the alias root or use any other symbol that we don't use.

In your example repo you set alias `~` to the value of `/`, not sure what the usecase for setting `/` and `~` to the same value.

`/` point to the project root which is the path of the entrypoint

**Comment by iamclaytonray** [comment]
I'm not sure I understand. However I setup alias should not install those as dependencies. 

For example, when I:

```
import { Hello } from '~/components/Hello';
```

Parcel will install `components` as a dependency. I've tried a couple of different variations as well. I still have dependencies being installed when they are an alias.

**Comment by DeMoorJasper** [comment]
In parcel `~` is reserved for root, you shouldn't be using it in aliasing at all.

Not sure why it's triggering an install though

**Comment by iamclaytonray** [comment]
So how should I properly do this? 

package.json
```
"alias": {
  "src": "./src"
}
```

src/index.tsx
```
import { Hello } from 'src/components/Hello';
```

**Comment by iamclaytonray** [comment]
The better I understand, the better the docs will be when I write them, as discussed in [this issue](https://github.com/parcel-bundler/website/issues/184)

**Comment by DeMoorJasper** [comment]
That looks good, as long as its no reserved character/word it should be fine

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
