### ISSUE TITLE
Server-side template rendering

### ISSUE THREAD

**Issue by trumank** [parcel-bundler/parcel#1647]
Is it possible to have parcel compile templates into a single template file that can be loaded server-side and rendered?
For example...
```pug
// src/base.pug
doctype html
html
  head
    title #{title}
    link(rel='stylesheet', href='./css/main.scss')
  body
    block content
```
and
```pug
// src/index.pug
extends layout

block content
  Hello, #{user}!
```
get transformed into
```pug
// dist/index.pug
doctype html
html
  head
    title #{title}
    link(rel='stylesheet', href='/main.6b0012b9.css')
  body
    | Hello, #{user}!
```
which can then be loaded by the server and rendered.

On second thought, template files don't even need to be squashed into a single file. All I need is for the dependencies to processed and links updated, the rendering engine can handle the rest. Is there some existing way to do this?

**Comment by DeMoorJasper** [comment]
I dont't think this is possible with parcel core, it shouldn't be hard to write a plugin that does this though.

**Comment by DeMoorJasper** [comment]
Probably best way to support this is to use multiple entrypoints for the static files and create a server to render the templates and serve the static files.

Run parcel in watch mode, so it doesn't handle server things.

This should have answered the question
