### ISSUE TITLE
There are sass files or background images that will get stuck and cannot continue to run？

### ISSUE THREAD

**Issue by QAQLiuCong** [parcel-bundler/parcel#1648]
# ❔ Question

When starting the service and building, it will always get stuck, it won't run, I don't know what the situation is. Ten times, I can run it once. It is okay when I have two or three pages at first, but I won't be able to do it later. Can you see what the problem is? Thank you. I searched for other problems, the sass file does not automatically refresh, the background image, but not, I have no choice.

## 🔦 Context

I guess it is a problem with the sass file, but not sure.

![image](https://user-images.githubusercontent.com/39507436/42151180-b1aa8a70-7e0e-11e8-81a5-b3e41064b5aa.png)
![image](https://user-images.githubusercontent.com/39507436/42155155-3531dcb2-7e1a-11e8-99d0-f2e75044fed6.png)

## 💻 Code Sample

This is one of my project use cases. https://github.com/QAQLiuCong/test

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |   Newest
| Node             | 10.2.0
| npm/Yarn         | 6.1.0
| Operating System | win10 x64

**Comment by DeMoorJasper** [comment]
Try removing the links to the sass files, to make sure it's the sass files

**Comment by QAQLiuCong** [comment]
@DeMoorJasper  Really great, thank you very much for your answer.
