### ISSUE TITLE
Cannot read property 'getOwnPropertySymbols' of undefined

### ISSUE THREAD

**Issue by tomkis** [parcel-bundler/parcel#1649]
# 🐛 bug report

When building my app using `parcel build` the application simply doesn't work due to error in console.

![screen shot 2018-07-02 at 12 04 00](https://user-images.githubusercontent.com/5079224/42158254-3c40bf20-7df0-11e8-9ac0-1ab09e458d71.png)

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
.babelrc:

{
  "presets": [
    [
      "env",
      {
        "targets": {
          "browsers": ["last 2 versions"],
          "node": "8.10.0"
        }
      }
    ]
  ],
  "plugins": [
    "transform-object-rest-spread",
    "transform-class-properties"
  ]
}

Build script:

"build:client": "NODE_ENV=production parcel build client/index.html -d ./dist",
```

## 🤔 Expected Behavior

Work without exception in console

## 😯 Current Behavior

App doesn't even boot, ends up with the exception from the screenshot. Interesting part is that it works if I use  `parcel watch` instead of `parcel build`

This works for me:

`"watch:client": "NODE_ENV=development parcel watch client/index.html -d ./dist",`

This doesnt:

`"build:client": "NODE_ENV=production parcel build client/index.html -d ./dist",`

For the record: I try playing around with stuff like NODE_ENV, no-minify, no-cache etc. it always works for `parcel watch` (no matter what setup i provide) and never works for `parcel build`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |    1.9.4
| Node             |    8.10
| npm/Yarn         | yarn 1.7.0
| Operating System |  Mac

**Comment by safareli** [comment]
looks like it's same issue as #1656
