### ISSUE TITLE
Is pkg.source a safe import target?

### ISSUE THREAD

**Issue by alexkrolick** [parcel-bundler/parcel#1652]
Seems like trying to use package.json's source field could be a source of issues:

https://github.com/parcel-bundler/parcel/blob/98a293f79bf822bca5f97db9155ee30ddaa03632/src/Resolver.js#L279

- `microbundle` uses `source` to identify the pre-Babel source code of a module, which could be a problem if the bundle config for the consumer doesn't match the source
- Is there an RFC for using `source` in imports like there is for `jsnext` or `module`? Seems safer to treat as reserved for internal use of the package.

**Comment by mischnic** [comment]
> microbundle uses source to identify the pre-Babel source code of a module, which could be a problem if the bundle config for the consumer doesn't match the source

We should be using the actual babel config of that package in this case.

> Is there an RFC for using source in imports

There is no spec for package.json that actually reflects the current usage.
