### ISSUE TITLE
How to use parcel.js with `hugo` static site generator - https://gohugo.io/

### ISSUE THREAD

**Issue by tapanbavaliya** [parcel-bundler/parcel#1653]
# ❔ Question

How to use parcel.js with `hugo` static site generator

## 🔦 Context

i have website in hugo, i want to use parcel.js please provide guideline ?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Hugo           | https://gohugo.io/ - v0.42.2 |

**Comment by KeineLimonade** [comment]
What is it exactly you want to accomplish?

Hugo is an excellent tool by default and doesn't really require another build tool like parcel.

**Comment by tapanbavaliya** [comment]
actually `hugo` is not compress multiple css files in one, or any js file, i want to build ci on top of ` hugo` after hugo build, i also want to remove, unwanted css & js code using tree shacking algorithm, that's why i have placed this question, and thank you for your response

**Comment by KeineLimonade** [comment]
+ Make sure Hugo runs without creating a server.
+ Run `parcel serve public/*.html`.

**Comment by tapanbavaliya** [comment]
i have tried but not working 

```

**Comment by KeineLimonade** [comment]
And with `. /public/*.html`?

**Comment by tapanbavaliya** [comment]
same error i got @KeineLimonade
