### ISSUE TITLE
`Serve` not refreshing Vue template styles, but `Build` does

### ISSUE THREAD

**Issue by jakeparis** [parcel-bundler/parcel#1658]
# 🐛 bug report

When using the server (with or without HMR), it doesn't recognize styles in `<style>` block within a Vue template. This problem is within HMR, but style changes are also not picked up when doing a manual refresh in the browser. 

## 🎛 Configuration (.babelrc, package.json, cli command)

No .babelrc. I'm using the vue template compiler feature of Parcel. I've got a mini test repo [here](https://gitlab.com/jake.paris/parcel-bugtest).

```js
{
  ...
  "scripts": {
    "build": "parcel build src/index.html --public-url .",
    "serve": "parcel src/index.html"
  },
  "devDependencies": {
    "@vue/component-compiler-utils": "^2.0.0",
    "node-sass": "^4.9.0",
    "parcel-bundler": "^1.9.3",
    "vue-template-compiler": "^2.5.16"
  },
  "dependencies": {
    "vue": "^2.5.16",
    "vue-hot-reload-api": "^2.3.0",
    "vue-router": "^3.0.1"
  },
  "alias": {
    "vue": "./node_modules/vue/dist/vue.common.js"
  }
}
```

## Reproducing the Bug
1. run `npm install` to set up the app
1. run `npm run build`.
1. open `src/Home.vue` and add some styles in the `<style>` block at the bottom.
1. run `npm run build` again. Those styles will be reflected in the built page. 
1. Now run `npm run serve` and open `localhost:1234`
1. Now make edits to the styles in that same style block, save, and see that they are not reflected in the served page. 
1. Refresh the served page, and your new styles are still not showing up. 
1. If you run `npm run build` again, your new styles _do_ show up. 

## 🤔 Expected Behavior

While running `serve`, when modifying the styles within the `<style>` block in a Vue template, those styles should immediately be reflected in what the Parcel server outputs. 

## 😯 Current Behavior

In order to get the styles to be reflected in the app, I have run the *build* command. Then all works as expected. However, when running the *serve* command, changes to those styles are not picked up. 

## 🔦 Context / Environment
Example mini repo: https://gitlab.com/jake.paris/parcel-bugtest

## 🌍 Your Environment
I'm using Parcel 1.93, npm, on a Mac.

**Comment by kimthompson** [comment]
I'm running into this exact same thing. I'm relieved to discover that this is a known bug, since I'm new to Parcel and I thought I might be doing something wrong.
