### ISSUE TITLE
More events!

### ISSUE THREAD

**Issue by sw-yx** [parcel-bundler/parcel#1660]
# 🙋 feature request

Hello, I was working on a static site generator using parcel. I think the events system could be expanded to accommodate other tooling that hooks into parcel to understand a project's structure and does stuff around it (so that I can take advantage of parcel's code splitting for example).

## 🤔 Expected Behavior

add an event for every time a new asset is bundled.

optionally, also add an event based on filetypes (so its like a subset of the above event, but much easier for a very common use case)

## 😯 Current Behavior

currently `buildEnd` and `bundled` only emit when the bundling is complete.

## 💁 Possible Solution

not sure, I haven't read the source code yet, but plan to.

## 🔦 Context

> How has this issue affected you? What are you trying to accomplish?

I am trying to make a static site generator. it would be great to hook into parcel so I can do my data injection logic *alongside* parcel, instead of only after the bundling is complete. its a much simpler way of doing it than crawling the built tree myself, and probably wouldn't be too much work on parcel's part.

## 💻 Examples

```js
const bundler = new Bundler(...);
bundler.on('assetBundled', (asset) => {
// for each asset, execute this callback
});
bundler.on({ name: 'assetBundled', type: 'js' }, (asset) => {
// for each javascript asset, execute this callback
});
```

**Comment by yanglinz** [comment]
I have a different use-case that would benefit from more event hooks as well. 

I think Parcel would be a fantastic way to enable zero-config, modern JS bundler for other non-javascript web frameworks like Django. But I'd need a manifest of output files as they're generated, and not sure if the current event system would support that. 

I'm not too familiar with Parcel's codebase yet, but let me know if there's a good place to start for this.

**Comment by KeineLimonade** [comment]
@yanglinz There is a a plugin that outputs a manifest. It is called something like parcel-plugin-manifest.

**Comment by DeMoorJasper** [comment]
More events is probably a good idea, but we shouldn't be going overkill with them as they might have a significant impact on performance if we overdo the amount of events

**Comment by sw-yx** [comment]
ok - ONE event? :p 'assetBundled' event. should have no impact on perf if user doesn't implement it, and if the user does implement then they should accept the perf impact

**Comment by DeMoorJasper** [comment]
Parcel 2 resolves this till some extend, too much events cause performance issues though
