### ISSUE TITLE
lessrc not used for dependencies

### ISSUE THREAD

**Issue by nutgaard** [parcel-bundler/parcel#1663]
# 🐛 bug report
`.lessrc` is not used when compiling less-files contained in dependencies.

### .lessrc
```js
{
    "globalVars": {
        "myVariable": "cyan"
    }
}
```

## 🤔 Expected Behavior
`myVariable` should be defined when compiling less-files contained in npm-dependency.

## 😯 Current Behavior
Compilation fails with error: `variable @myVariable is undefined` 
The error message is from `lessc`, but does not provide a stacktrace.

Seems to be an artifact of `config.js::resolve` which stops searching for files at `node_modules`.
Probably because of:
```js
if (filepath === root || path.basename(filepath) === 'node_modules') {
  return null;
}
```

## 💁 Possible Solution
Allow `config.js::resolve` continue searching up until the root of the project, and at this point find a project-global `.lessrc`.

Alternatively, look for config-files at the root of the project before searching.

## 🔦 Context
Our organization publishes npm-packages which contain less-files. Most of these need some setup in the form of global-variables. At this point this stops us from adopting parcel. :( 

## 💻 Code Sample

In JS/TS: 
```js
// Uses two global variables: coreModulePath and nodeModulesPath
import 'nav-frontend-knapper';
```

.lessrc: (configuration similar to whats used with browserify and webpack)
```js
{
    "globalVars": {
        "coreModulePath": "~",
        "nodeModulesPath": "~"
    }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.4
| Node             | 8.9.4
| npm/Yarn         | npm 5.1.0, yarn 1.6.0 (tested with both)
| Operating System | macOs 10.13.3

**Comment by nutgaard** [comment]
If that is the expected behaviour then I would reclassify this issue as an feature-request. :)
 
From what I could understand it starts searching for `.lessrc` at the assets-position, and would find the `.lessrc` from the package if it exists.

Our usecase is somewhat different, in that all our packages requires globalVariables which has to be set by the consumer of the package. But as I explained in the issue; `config.js::resolve` stops traversing/searching when it hits `node_modules`, and thus doesnt find the `.lessrc` defined in the consumer. 

Continuing the search until the root of the consumer would solve our usecase. But I this may not be desired in parcel?

**Comment by DeMoorJasper** [comment]
This is actually by design, as going up beyond the node_module is quite dangerous there is a detailed issue, describing this same issue somewhere in here. (that one's related to postCSS modules)

**Comment by nutgaard** [comment]
By design or not, it does unfortunately prevent us from adopting parcel before we get rid of those pesky global variables. :( 

Anyways, if you want to close or reclassify this issue I have no problem with it. As everything works as intended. 


Not sure if you were referring to one of these; https://github.com/parcel-bundler/parcel/issues/368 https://github.com/parcel-bundler/parcel/issues/1292 They seem related, and it doesnt hurt to link similar issues.

**Comment by DeMoorJasper** [comment]
I'll leave it open for now
