### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by makmm** [parcel-bundler/parcel#1667]
# 🐛 bug report

Getting `Failed to load resource: the server responded with a status of 404 (Not Found)` on JavaScript files in the dev server favicon.ico

## 🎛 Configuration (.babelrc, package.json, cli command)

https://gitlab.com/homework-manager/hwm-frontend

## 🤔 Expected Behavior

Correctly load the page

## 😯 Current Behavior

When loading the page, I get a `Failed to load resource: the server responded with a status of 404 (Not Found)`
![image](https://user-images.githubusercontent.com/7550995/42295736-dfac62f2-7fc3-11e8-891f-4def6d09fd0a.png)

## 💻 Code Sample

https://gitlab.com/homework-manager/hwm-frontend

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.4 |
| Node             | 10.5.0 |
| npm/Yarn         | Yarn 1.7.0 |
| Operating System | Arch Linux 4.17.2-1-ARCH |

Thanks in advance <3

**Comment by DeMoorJasper** [comment]
Parcel currently doesn't set any favicons as that might cause issues, as favicons are heavily cached.

**Comment by makmm** [comment]
Umm actually, it's not only favicons. Check screenshot @DeMoorJasper

**Comment by DeMoorJasper** [comment]
Can't seem to reproduce it, perhaps your service worker is creating this issue.

**Comment by makmm** [comment]
I'm pretty sure it's related to #1656 .. I think I will close now.

**Comment by LibanWasTaken** [comment]
I'm using "npx parcel index.html" 

but this happens :((

![image](https://user-images.githubusercontent.com/85487896/132505473-0e50ae83-d525-477c-bf88-a6fdf9cdb61b.png)
