### ISSUE TITLE
can't  dynamic require images

### ISSUE THREAD

**Issue by BeliefRC** [parcel-bundler/parcel#1668]
# 🐛 bug report

I use parcel to package the react project,but can't dynamic require images

File Directory
![image](https://user-images.githubusercontent.com/24429723/42305606-40397dd6-805e-11e8-8c38-61b6a1c600eb.png)

## 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc
```js
{
  "presets": [
    "env",
    "react"
  ],
  "plugins": [
    [
      "import",
      {
        "libraryName": "antd",
        "style": true
      }
    ],
    [
      "transform-runtime",
      {
        "polyfill": false,
        "regenerator": true
      }
    ]
  ]
}
```
package.json
```js
{
  "name": "parcelReactDemo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "parcel ./src/index.html",
    "build": "parcel build ./src/index.html -d build"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "antd": "^3.1.4",
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  },
  "devDependencies": {
    "babel-plugin-import": "^1.6.3",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "less": "^2.7.3",
    "parcel-bundler": "^1.9.4"
  }
}

```
## 🤔 Expected Behavior
Each picture should be properly introduced

## 😯 Current Behavior
![image](https://user-images.githubusercontent.com/24429723/42305902-99550aba-805f-11e8-90fb-3fd8c4d7b605.png)

## 💻 Code Sample
app.js
```js
import React, { Component } from 'react'

export default class App extends Component {

    render () {
        return (
            <div>
                {[1, 2, 3].map(
                    item => <img key={item} src={require(`./${item}.png`)}
                                 alt=""/>)}
            </div>
        )
    }
}

```
index.js
```js
import React from 'react'
import ReactDOM from 'react-dom'
import App from './containers/app.js'

ReactDOM.render(<App/>, document.getElementById('root'))
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.4
| Node             | 8.9.3
| npm/Yarn         | npm 5.5.1
| Operating System | win10

**Comment by DeMoorJasper** [comment]
Probably better to use something like this:

```
const images = require('./images/*.png');

// images returns an object with all the paths of the images matching the glob with content hashing this also helps with improving your caching
// You can loop through images :)
```

**Comment by BeliefRC** [comment]
@DeMoorJasper 
It still doesn't work properly
error info:  Uncaught Error: Cannot find module './1.png'
```js
import React, { Component } from 'react'

export default class App extends Component {

    render () {
        return (
            <div>
                {[1, 2, 3].map(
                    item => {
                        const images = require(`./${item}.png`)
                        return <img key={item} src={images}
                                    alt=""/>
                    })}
            </div>
        )
    }
}
```

**Comment by DeMoorJasper** [comment]
Well you didn't apply my example code at all?

I'll write an example :)

import React, { Component } from 'react';
import images from './*.png';

export default class App extends Component {

    render () {
        return (
            <div>
                {Object.keys(images).map(
                    key => {
                        return <img key={key} src={images[key]}
                                    alt=""/>
                    })}
            </div>
        )
    }
}

**Comment by QAQLiuCong** [comment]
@DeMoorJasper   Hello, excuse me, if there is a Vue file, is there a way to achieve this? Introduce static resources in the data.

**Comment by DeMoorJasper** [comment]
@QAQLiuCong parcel works the same in any asset type, so as long as you can pass a link to the vue component it should work

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DeMoorJasper** [comment]
Closing this, as I'm pretty sure it's resolved by my response

**Comment by mkucaj1986** [comment]
How can I force application to refresh folder to look images like in your example 
'''
import images from './*.png';
'''
eg. after I completed upload file to folder ?

**Comment by bologer** [comment]
@DeMoorJasper but [this](https://github.com/parcel-bundler/parcel/issues/1668#issuecomment-402627440) solution is very limited, as you are not having the hash. Is it somehow possible to get the full name of the file?

**Comment by davidysoards** [comment]
Thanks you @DeMoorJasper. Goddamn I spent like an hour trying to figure this out, and @bologer if you know the file name you can just call **images[FILENAME]**

**Comment by simonwiles** [comment]
Is there any way to make this work with Parcel 2 (currently trying with `2.0.0-alpha.3.2`)?  I've attempted variations of `require('./images/*.png')`, `require('url:./images/*.png')`, `require('url:~/src/images/*.png')` etc. all to no avail, but I can't see anything that looks like it related to this in the issues or milestones.  Is there a trick I'm missing?

**Comment by cmditch** [comment]
Also curious about what @simonwiles is asking about. It seems the only solution for now is to manually import every asset individually.

**Comment by mischnic** [comment]
https://github.com/parcel-bundler/parcel/pull/5933 should enable this
