### ISSUE TITLE
Some files are not watched in case-insensitive filesystems

### ISSUE THREAD

**Issue by markwylde** [parcel-bundler/parcel#1673]
# 🐛 bug report

I am trying out parcel bundler and with help from other people online have produced the following repository:
https://github.com/markwylde/parcel-react-demo

It's a working one page example app that builds successfully using react.

However when I do `parcel watch ./src/index.html` or `parcel ./src/index.html` and then change a file, it's not actually rebuilding anything.

This was just one of a few other problems I've been having. In general parcel just seems very buggy and is throwing a lot of errors. But I will submit that it could just be react specific stuff, or the fact I have never used parcel before.

I have uploaded a video of my experience to youtube.

[![video of my experience](https://i.ytimg.com/vi/XzHsgyaJkZk/hqdefault.jpg)](https://youtu.be/XzHsgyaJkZk)

## 🎛 Configuration (.babelrc, package.json, cli command)

`.babelrc`:
```
{
  "presets": ["react"]
}
```

`package.json`:
```
{
  "name": "egr",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "node-sass": "^4.9.1",
    "react": "^16.4.1",
    "react-dom": "^16.4.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-preset-react": "^6.24.1"
  }
}
```

## 🤔 Expected Behavior

I expect the dist folder to be updated when I change a source file.

## 😯 Current Behavior

When I change a source file the dist folder is not updating.

## 💁 Possible Solution

No idea, I've only just started looking into parcel today.

## 🔦 Context

With 7 second build times it would be impossible to use this for an actual project.

## 💻 Code Sample

https://github.com/markwylde/parcel-react-demo

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.4 |
| Node             | v10.3.0 |
| npm/Yarn         | 6.1.0 |
| Operating System | macOS High Sierre |

**Comment by markwylde** [comment]
Awesome @buronnie, thanks for your fast response. How embarrassing it was something so silly on my part. I have changed the case and it worked perfectly.

**Comment by fathyb** [comment]
Great, closing this then
