### ISSUE TITLE
Bad SVG minifications

### ISSUE THREAD

**Issue by ghost** [parcel-bundler/parcel#1676]
# 🐛 bug report

When you build your site in a final way with minifications, etc... SVG are not displayed correctly as on the source file or when it is on a server created by Parcel.

## 🎛 Configuration (.babelrc, package.json, cli command)

**package.json**
```
{
  "name": "YaliAIR",
  "version": "1.0.1",
  "description": "Website for an association focused on football equipment.",
  "main": "index.js",
  "scripts": {
    "start": "./node_modules/.bin/parcel src/index.html",
    "build": "./node_modules/.bin/parcel build src/index.html --public-url ./"
  },
  "keywords": [],
  "author": "Lionel Bovy",
  "license": "MIT",
  "dependencies": {
    "fonts.css": "^2.0.0",
    "npm": "^6.1.0",
    "parcel-bundler": "^1.9.4"
  }
}
```

## 🤔 Expected Behavior

When compiling, SVG should keep their proportion as on the source file or when the file is on a "live" server created by Parcel.
![capture2](https://user-images.githubusercontent.com/38806390/42410388-33ab1c96-81e9-11e8-8922-c2a42b5dd3a6.PNG)

## 😯 Current Behavior

SVG appear distorted or different sizes.
![capture](https://user-images.githubusercontent.com/38806390/42410385-2cea5e4e-81e9-11e8-9733-0921491d3ce9.PNG)

## 🔦 Context

I tried to compile my site with Parcel hoping that it would render the same as on the server live but with the minifications. It does but not very well for SVG

## 💻 Code Sample

Here's a repo with files & steps to follow: https://github.com/lionelbovy/YaliAIR

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.4
| Node             |8.9.4
| npm/Yarn         |5.6.0
| Operating System |Microsoft Windows [version 10.0.17134.112]

**Comment by DeMoorJasper** [comment]
You can disable the minification using a htmlnanorc file

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
