### ISSUE TITLE
Set up breakpoints in vs code with typescript

### ISSUE THREAD

**Issue by polferrando98** [parcel-bundler/parcel#1677]
# ❔ Question
Why are my breakpoints in vs code not working?

## 🔦 Context
I'm trying to build a game with yarn, phaser and parcel, with vs code and chrome debugger but i can not manage to get the breakpoints working, they get greyed out.

I followed some chrome debugger tutorials but they do not work. 

## 💻 Code Sample
I uploaded the project [here](https://github.com/polferrando98/Phaser-ts-yarn-parcel-template)

Here you can see the folder structure and launch.json

![captura de pantalla 20](https://user-images.githubusercontent.com/15270619/42411203-4796633c-81f8-11e8-8bf5-e5d721c23d68.png)

Just in case it is useful, I followed [this](https://www.youtube.com/watch?v=3r9sGjrvqIc&t=31s) tutorial to set up the project

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.9.3  |
| Node             | 8.9.4 |
| Yarn         |  1.7.0 |
| Operating System | Win 10 |

**Comment by peanutbother** [comment]
possible duplicate of #611
