### ISSUE TITLE
Secure Connection Failed when using --https flag

### ISSUE THREAD

**Issue by dehuszar** [parcel-bundler/parcel#1678]
First use of --https flag works fine.  Parcel was able to generate certificates and everything loaded.  After having to clear the cache and generate new certificates, I now get this error:

Secure Connection Failed

An error occurred during a connection to localhost:1234. You have received an invalid certificate. Please contact the server administrator or email correspondent and give them the following information: Your certificate contains the same serial number as another certificate issued by the certificate authority. Please get a new certificate containing a unique serial number. Error code: SEC_ERROR_REUSED_ISSUER_AND_SERIAL 

Deleting the cert from my cert registry in Firefox clears the issue, but I've never had this problem in webpack or ember-cli.  It would be nice to not have to have an extra step in a different place each time I need to clear .cache (which at this point in my project and parcel learning curve happens with some frequency)

**Comment by DeMoorJasper** [comment]
Not sure if this is a Parcel issue, they are self-signed certificates after all and this is usually causing issues.

**Comment by dehuszar** [comment]
What tool does parcel use to generate the certs?  At a minimum, there should be some clean way of handling certs when `.cache` folder gets cleared, or decouple them entirely from the `.cache` folder.

**Comment by DeMoorJasper** [comment]
The certificates are being cached as they take a very long time to generate and it's easier if you'd like to add them to the browser (which isn't necessary if you just allow self signed certs from localhost)

Parcel uses: `node-forge `

**Comment by DeMoorJasper** [comment]
Ow it creates a new cert if you clear the cache because the cert is stored in the cache.
This is the intended behaviour at the moment, you can clear everything inside the cache except the cert files or use a cert you generated yourself to prevent this.

**Comment by dehuszar** [comment]
Fair enough, I will proceed accordingly.  It would be nice to have some of these contours in the docs somewhere.  Thank you for your help!

**Comment by DeMoorJasper** [comment]
It is documented https://en.parceljs.org/cli.html#enable-https

**Comment by dehuszar** [comment]
I was thinking more about adding a note / warning about cache clearing when using https.  A lot of the support tickets have "delete your `.cache/` folder and try again" as a solution, which then produces this issue.
