### ISSUE TITLE
Please..... How to Code Splitting In React js

### ISSUE THREAD

**Issue by WaranchitPk** [parcel-bundler/parcel#1679]
# ❔ Question

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by DeMoorJasper** [comment]
Please fill in the issue template...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KeineLimonade** [comment]
In general reading the docs might help. https://parceljs.org/code_splitting.html
