### ISSUE TITLE
🐛 Allow to use comment in tsconfig.json

### ISSUE THREAD

**Issue by azu** [parcel-bundler/parcel#168]
### 🎛 Configuration (.babelrc, package.json, cli command)

I've create reproduce repository

- <https://github.com/azu/parcel-tsconfig.json-error>

```shell
git clone https://github.com/azu/parcel-tsconfig.json-error
cd parcel-tsconfig.json-error
yarn 
yarn run build
# Throw Error
```

`tsconfig.json`
```json
{
  "compilerOptions": {
    /* Basic Options */
    "module": "commonjs",
    "moduleResolution": "node",
    "newLine": "LF",
    "outDir": "./lib/",
    "target": "es5",
    "sourceMap": true,
    "declaration": true,
    "jsx": "preserve",
    "lib": [
      "es2017",
      "dom"
    ],
    /* Strict Type-Checking Options */
    "strict": true
  },
  "include": [
    "src/**/*"
  ]
}

```

### 🤔 Expected Behavior
No error

### 😯 Current Behavior

Parse Error on load `tsconfig.json`

```
$ cross-env NODE_ENV=production parcel build src/index.html --public-url .
🚨  /Users/azu/.ghq/github.com/azu/parcel-tsconfig.json-error/src/index.ts: Unexpected token / in JSON at position 29 while parsing near '...ilerOptions": {       at module.exports (/Users/azu/.ghq/github.com/azu/parcel-tsconfig.json-error/node_modules/parse-json/index.js:26:19)
    at Object.load (/Users/azu/.ghq/github.com/azu/parcel-tsconfig.json-error/node_modules/parcel-bundler/src/utils/config.js:36:12)
    at <anonymous>
✨  Done in 2.44s.
```

### 💁 Possible Solution

Currently, `config.load` use [parse-json](https://www.npmjs.com/package/parse-json "parse-json") directly.

https://github.com/parcel-bundler/parcel/blob/548eef92e11711db007b7613ba5530de508d21a0/src/assets/TypeScriptAsset.js#L17

We can strip comment before parsing json string.

- [strip-json-comments](https://github.com/sindresorhus/strip-json-comments "strip-json-comments")

### 🔦 Context

tsconfig.json includes comments by default.
tsc --init create tsconfig.json that includes comments.

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |   1.1.0
| Node             | 9.0.0
| npm/Yarn         | 1.3.2
| Operating System | macOS

**Comment by DeMoorJasper** [comment]
I don't know if this should be part of parcel necessarily, as far as i know this is not allowed in standard json

**Comment by azu** [comment]
As far as I remember, babel also allow to write comment in .babelrc(json format)
