### ISSUE TITLE
Reference to all file extensions parcel recongnize by default for assets

### ISSUE THREAD

**Issue by DoumanAsh** [parcel-bundler/parcel#1687]
# 🙋 feature request

While current documentation is sufficient for simple use cases,
it is not very clear how parcel handles all possible file extensions.

For example `PostCSS` has option to use custom parser and you usually use different file extension for it.

## 🤔 Expected Behavior

[Asset Types](https://parceljs.org/asset_types.html) to describes all assets that are recognized by default 

## 😯 Current Behavior

Not done

## 💁 Possible Solution

I'm not sure how well it would be suited, but I'd like to see table with all possible file extensions with description how Parcel treats them

## 🔦 Context

I was trying to convert my old webpack project to use parcel as I mostly need to convert bundle some CSS only.

It turns out that I cannot properly handle CSS with multiple sources of different types(e.g. plain CSS and SugarSS)

As I'm not sure how exactly PostCSS assets are recognized, I'm unsure how to approach my problem

## 💻 Examples

| Asset type       | File extensions          | Way of handle  |
| ------------- |:-------------:| -----:|
| CSS |  `.css`  | If PostCSS config available, pass asset to PostCSS |

**Comment by DeMoorJasper** [comment]
Not sure what you're asking here?

Every supported extension is being mapped using the parser https://github.com/parcel-bundler/parcel/blob/master/src/Parser.js

If you're asking for extra documentation, you're in the wrong repository. In that case please close this issue and reopen here: https://github.com/parcel-bundler/website

**Comment by DoumanAsh** [comment]
Yes, I'm asking for extra documentation.
Sorry, I'll open it on website repo
