### ISSUE TITLE
SugarSS Support

### ISSUE THREAD

**Issue by Kompwu** [parcel-bundler/parcel#1692]
# 🙋 feature request

Parcel doesn't support SugarSS.

## 🤔 Expected Behavior

Should be able to bundle `.sss` file.
## 😯 Current Behavior

A big 🖕 ... nothing happens.

## 💁 Possible Solution

There is already a PR [here](https://github.com/parcel-bundler/parcel/pull/1689).

**Comment by DeMoorJasper** [comment]
SugarSS doesn't really have an as big of a userbase as the other css frameworks we support. That's probably why it's not supported.

Could you please add some links to possible SugarSS compilers and such.

**Comment by DeMoorJasper** [comment]
Closing in favor of #1689

**Comment by Kompwu** [comment]
@DeMoorJasper Don't close it until it's merged...
