### ISSUE TITLE
Cannot resolve dependency 'color-contrast'

### ISSUE THREAD

**Issue by WesleydeSouza** [parcel-bundler/parcel#1693]
# 🐛 bug report

I'm trying to port a project from `create-react-ts` into `parcel`, but one specific dependency fails to resolve:

This is from a test that only runs that one import.

It has all packages installed and works perfectly without the import.

## 🎛 Configuration (.babelrc, package.json, cli command)

Using typescript, here's a package.json

```js
{
  "dependencies": {
    "color-contrast": "^0.0.1",
    "parcel-bundler": "^1.9.4"
  },
  "devDependencies": {
    "typescript": "^2.9.2"
  }
}
```

## 🤔 Expected Behavior

Code should compile.

## 😯 Current Behavior

Compilation fails for `color-contrast` package.

```
🚨  /Users/wesley/Sites/test/index.ts:6:47: Cannot resolve dependency 'color-contrast'
    at Resolver.resolve (/Users/wesley/Sites/test/node_modules/parcel-bundler/src/Resolver.js:70:17)
```

## 🔦 Context

Trying to port a project from webpack.

## 💻 Code Sample

https://github.com/WesleydeSouza/bugreport-parcel-color-contrast

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.4
| Node             | 10.6.0
| npm/Yarn         | 6.1.0/1.7.0
| Operating System | macOS 10.14

**Comment by devongovett** [comment]
Looks like there was a typo in the `module` entry of package.json. I submitted a PR to fix it: https://github.com/jescalan/color-contrast/pull/1
