### ISSUE TITLE
Runtime error when loading jpg with import

### ISSUE THREAD

**Issue by jouni-kantola** [parcel-bundler/parcel#17]
I created a test app with the following structure:
```
index.html
/src
   index.js
   styles.css
/images
   logo.jpg
```

`index.js` looks like this:
```
import styles from "./styles.css";

import("../images/logo.jpg").then(logo => {
  document.body.appendChild(logo());
});
```

When I build bundles are generated, but when loading the `logo.jpg` in runtime I get:
```
Uncaught (in promise) TypeError: bundleLoaders[type] is not a function
    at loadBundle (327d9e5e96a78a58f299f0db51430144.js:137)
    at Array.map (<anonymous>)
    at 327d9e5e96a78a58f299f0db51430144.js:113
    at new Promise (<anonymous>)
    at LazyPromise.then (327d9e5e96a78a58f299f0db51430144.js:195)
    at Object.require.2._bundle_loader (327d9e5e96a78a58f299f0db51430144.js:249)
    at newRequire (327d9e5e96a78a58f299f0db51430144.js:46)
    at require.7 (327d9e5e96a78a58f299f0db51430144.js:63)
    at 327d9e5e96a78a58f299f0db51430144.js:68
```

When I debug I got this (`bundleLoaders` have no prop `jpg`):
![no-jpg](https://user-images.githubusercontent.com/2670127/33630493-d77dbc78-da07-11e7-867a-2ce71479e54f.png)

**Comment by devongovett** [comment]
Yeah, currently dynamic import can be used for CSS or JS.

**Comment by jouni-kantola** [comment]
This phrase was why I took a small webpack app I often use for testing, and tried it with parcel:
>Bundle all your assets
>
>Parcel has out of the box support for JS, CSS, HTML, file assets, and more - no plugins needed.

The usecase I'm after is to code split around components, but I guess the image could've been loaded by splitting out via a JS module instead.

**Comment by treshugart** [comment]
I get this for any non js / css import that is contained inside of a dynamic import call, even when they're not a dynamic import themselves. i.e.

```js
// file1.js
import('./file2');

// file2.js
import path from './img.png';
```

**Comment by devongovett** [comment]
yep, dynamic imports are lazy: they don't get loaded until you explicitly need them (by calling `.then`). See https://parceljs.org/code_splitting.html to read more about it.

**Comment by treshugart** [comment]
Right ok, that makes sense now. I was confused because webpack loads it
immediately. Is parcel’s behaviour consistent with the spec?

**Comment by thejameskyle** [comment]
Reading [the proposed spec](https://tc39.github.io/proposal-dynamic-import/#sec-import-calls), I don't believe this behavior is "observable" (in terms of the spec) other than maybe some equality checks on `.then`.

**Comment by treshugart** [comment]
Canary definitely loads up front.

**Comment by jouni-kantola** [comment]
@devongovett: What are your thoughts, should parcel allow for dynamic imports of other stuff than js/css? If not, I guess this issue can be closed.

**Comment by devongovett** [comment]
Yep, in #473 it is now possible to register custom bundler loaders for other formats in plugins etc.
