### ISSUE TITLE
'buildStart' event is not firing

### ISSUE THREAD

**Issue by apvarun** [parcel-bundler/parcel#1703]
# 🐛 bug report
the `buildStart` event, added in version 1.9.0 of parcel, is not firing. When the event is emitted, plugins are not loaded and so cannot be used for preprocessing file(s) via plugins.

## 🤔 Expected Behavior
Fires the event before bundling process is started.

## 😯 Current Behavior
The event registered from a plugin will not be fired.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.4
| Node             | 7.6.0
| npm/Yarn         | 5.10.0
| Operating System | Windows 10

**Comment by DeMoorJasper** [comment]
Oh damn you're right, this PR should have probably not been approved, I'll make a quick code edit to fix this.
