### ISSUE TITLE
How to package everything into single HTML file?

### ISSUE THREAD

**Issue by ScottChapman** [parcel-bundler/parcel#1704]
# ❔ Question

How can I package up my site into a single static HTML file?

## 🔦 Context

I have a fairly simple site, it is a single page React app. When I do a build of the site I end up with three files; the HTML, JS, and a MAP file.

(actually what I tried to start with was to use webpack to produce a smaller set of files (HTML, images, js, map) and then tried to parcel that together into single file)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.4
| Node             | 10.5.0
| npm/Yarn         | 6.1.0
| Operating System | Mac OSX

**Comment by DeMoorJasper** [comment]
Combining parcel and webpack is probably not a great idea, currently the only way to do this is to use multiple entrypoints and then use a custom script that writes all those bundles into an html file (probably using some sort of templating engine)

**Comment by ScottChapman** [comment]
Yea, I assumed that was true. I'm guessing I can do the same thing just using parcel.

For my React app I have two top level files; one is `.js` and the other `.jsx`.

How exactly would I run parcel to build the dist files for that? I can probably then figure out how to combine the files.

Thanks!

**Comment by ScottChapman** [comment]
Just did that, I got a `dist` folder once I did a `yarn start`.

So, I don't think that gives me what I need. I basically need to be able to stitch together a single file (with no external file references).

The use-case (which I probably should have explained) is that I want to be able to return that from a serverless framework like AWS Lambda or Openwhisk. 

Basically they are Javascript functions that can return a string. So, I can return HTML. I just need to generate that HTML using something like Parcel, so I can embed the result in the function and return it when called.

Make more sense?

**Comment by peanutbother** [comment]
Then i would use parcel programmatically since that what I think you are trying to do isn't a standard use-case for parcel. I will look into this further when I geht home.

**Comment by shff** [comment]
@ScottChapman I wrote a plugin that uses `inliner` to inline CSS and JS.

It's still experimental, but I had no problems with it yet. Currently using it in a production app without hiccups.

https://github.com/shff/parcel-plugin-inliner

**Comment by alekpentchev** [comment]
@shff I have a problem with the plugin. After installing it via npm and building index.html I receive parcel bundles as normally, not one inlined html. Even the html file does not contain css styles and js.
How can I overcome this?

**Comment by peanutbother** [comment]
@alekpentchev I recommend you to move your question to a new issue at the author's plugin.
Since this issue here was about possible ways in general but your question is targeted at the plugin of @shff

**Comment by alekpentchev** [comment]
Sure, sorry for that.

**Comment by xingqiao** [comment]
[https://github.com/xingqiao/parcel-plugin-inline-source](https://github.com/xingqiao/parcel-plugin-inline-source)
[https://www.npmjs.com/package/parcel-plugin-inline-source](https://www.npmjs.com/package/parcel-plugin-inline-source)

set attribute `inline="inline"` to <script>、<link> tag, just like
```html
<script src="./index.js" inline="inline"></script>
```

**Comment by Workruft** [comment]
I've tried both of the plugins above, and neither of them have functioned properly for me. Can't this be standard functionality for ParcelJS to support? I don't see much difference between outputting JS and CSS to files and including them in HTML vs. just inlining them straight into the HTML. I can see there being difficulty with inlining images but that's an advanced feature.

**Comment by aminya** [comment]
This is possible using `web-resource-inliner`.

```
npm install web-resource-inliner
```

Then:
```
npm run build && node ./inline.js
```

save this file as `./inline.js`
```js
const fs = require("fs")
const inline = require("web-resource-inliner")

inline.html(
  {
    fileContent: readFileSync("./demo/simple/dist/index.html"),
    relativeTo: "./demo/simple/dist",
  },
  (err, result) => {
    if (err) { throw err }
    fs.writeFileSync("./demo/simple/dist/index-bundle.html", result)
  }
)


function readFileSync(file) {
  const contents = fs.readFileSync(file, "utf8")
  return process.platform === "win32" ? contents.replace(/\r\n/g, "\n") : contents
}
```

**Comment by peanutbother** [comment]
I would stick to proposed alternatives, and plugins since Parcel V2 Api is yet an RFC, so if you'd like this feature to be discussed I'd recommend to start a new Issue targeted at V2 RFC

**Comment by mischnic** [comment]
Not that I think this is a good idea, but with Parcel 2 you can do 
```
<style>
 @import "./style.css";
</style>
<script>
  import "./index.js";
</script>
```
and everything will be inlined.

**Comment by aminya** [comment]
> Not that I think this is a good idea,

To create static websites that can be deployed using one HTML file, this is very useful. 

For example, GitHub pages do not seem to import the js file themselves:
https://aminya.github.io/solid-simple-table/
https://github.com/aminya/solid-simple-table/blob/demo-page/index.html

> with Parcel 2 you can do
> 
> ```
> <style>
>   @import "./style.css";
> </style>
> <script>
>   import "./index.js";
> </script>
> ```
> 
> and everything will be inlined.

That's nice!

**Comment by thomasttvo** [comment]
> Not that I think this is a good idea, but with Parcel 2 you can do
> 
> ```
> <style>
>   @import "./style.css";
> </style>
> <script>
>   import "./index.js";
> </script>
> ```
> 
> and everything will be inlined.


As per https://parceljs.org/blog/rc0/#classic-scripts-vs.-es-modules, now you need to add `type="module"` to the script tag.

```
<style>
  @import "./style.css";
</style>
<script type="module">
  import "./index.js";
</script>
```

Otherwise you may get this error

```
@parcel/transformer-js: Browser scripts cannot have imports or exports.
```

**Comment by mindplay-dk** [comment]
Is this a documented Parcel 2 feature? Maybe it should be.

I found many bad/complex solutions before finding the final comments on this post, revealing how this is super simple with Parcel 2. 🙂

**Comment by mischnic** [comment]
You mean like https://parceljs.org/languages/html/#inline-scripts-and-styles ?

**Comment by mindplay-dk** [comment]
I was actually *just* reading that and for some reason concluded this was just about inline scripts and assets being *processed* - reading it now, I see it says *bundles* will be generated and inlined.

I'm not sure why I didn't pick up on this the first time. I think the word "inline" has two different meanings - in the context of everyday HTML, inline just means tags I placed inline. In addition to that, Parcel can "inline" my assets, so the meaning is somewhat ambiguous.

Perhaps a better headline for that section would be "*Bundling* inline scripts and styles"? This might more clearly set the expectation that the bundler is going to do it's thing? 🙂

**Comment by JustinMarotta13** [comment]
> This is possible using [`web-resource-inliner`](https://www.npmjs.com/package/web-resource-inliner).
> 
> ```
> npm install web-resource-inliner
> ```
> 
> Then:
> 
> ```
> npm run build && node ./inline.js
> ```
> 
> save this file as `./inline.js` (edit the paths according to your target HTML and its folder)
> 
> ```js
> const fs = require("fs")
> const inline = require("web-resource-inliner")
> 
> inline.html(
>   {
>     fileContent: readFileSync("./demo/simple/dist/index.html"),
>     relativeTo: "./demo/simple/dist",
>   },
>   (err, result) => {
>     if (err) { throw err }
>     fs.writeFileSync("./demo/simple/dist/index.html", result)
>   }
> )
> 
> 
> function readFileSync(file) {
>   const contents = fs.readFileSync(file, "utf8")
>   return process.platform === "win32" ? contents.replace(/\r\n/g, "\n") : contents
> }
> ```
> 
> @DeMoorJasper I wonder if this can be added to Parcel to make things easier.

This worked for me! Perfection!

**Comment by andersoncampolina** [comment]
> This is possible using [`web-resource-inliner`](https://www.npmjs.com/package/web-resource-inliner).
> 
> ```
> npm install web-resource-inliner
> ```
> 
> Then:
> 
> ```
> npm run build && node ./inline.js
> ```
> 
> save this file as `./inline.js` (edit the paths according to your target HTML and its folder)
> 
> ```js
> const fs = require("fs")
> const inline = require("web-resource-inliner")
> 
> inline.html(
>   {
>     fileContent: readFileSync("./demo/simple/dist/index.html"),
>     relativeTo: "./demo/simple/dist",
>   },
>   (err, result) => {
>     if (err) { throw err }
>     fs.writeFileSync("./demo/simple/dist/index.html", result)
>   }
> )
> 
> 
> function readFileSync(file) {
>   const contents = fs.readFileSync(file, "utf8")
>   return process.platform === "win32" ? contents.replace(/\r\n/g, "\n") : contents
> }
> ```
> 
> @DeMoorJasper I wonder if this can be added to Parcel to make things easier.

THIS WORKED FOR ME. THANKS! I WAS LOOKING FOR A SOLUTION FOR DAYS!!
