### ISSUE TITLE
Building SVG for inline usage

### ISSUE THREAD

**Issue by coreyworrell** [parcel-bundler/parcel#1707]
# ❔ Question

How can I insert modified inline SVG files into an HTML file?

I see that it is possible to use `posthtml-include` (even though resources included this way don't seem to be rebuilt after the `.cache` has been built, so you must clear cache before if you want these rebuilt?)

So if I do `<include src="./icons/arrow-down.svg"></include>`, how can I then run a custom build script that modifies those SVG files before they are included?

## 🔦 Context

Trying to use an SVG icon system. So I place SVG files straight from Adobe Illustrator, for example, and then I would like to run a script to convert `[id]` attributes to classes, etc.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.5 |
| Node             | 8.9.1 |
| npm/Yarn         | yarn 1.0.2 |
| Operating System | Windows 10 |

**Comment by DeMoorJasper** [comment]
You would either have to search a postHTML plugin that does what you want it to do, or you'd probably have to write one yourself if it's not a common use-case

**Comment by jean343** [comment]
I think it's definitely a good use case, and I vote that it becomes part of the defaults.

I have written a very simple bundler here, it's specific for SVGs.

```javascript
const Bundler = require( 'parcel-bundler' );

class Base64Asset extends Bundler.Asset {
	constructor( name, pkg, options ){
		super( name, pkg, options );
		this.type = 'js';
	}

	generate(){
		return {
			js: `module.exports="data:image/svg+xml;base64,${ Buffer.from( this.contents ).toString( 'base64' ) }";`
		};
	}
}

module.exports = Base64Asset;
```

Can be used with `bundler.addAssetType( 'svg', require.resolve( "./Base64Asset.js" ) );`.

**Comment by mischnic** [comment]
Will be possible/is already possible with a named pipeline in Parcel 2.
