### ISSUE TITLE
1.9.5 does not work in Linux in Windows Subsystem for Linux

### ISSUE THREAD

**Issue by gobengo** [parcel-bundler/parcel#1712]
# 🐛 bug report

I'm running Debian on Windows using Windows Subsystem For Linux.

Things work fine in 1.9.4.
Things do not work fine in 1.9.5.

Running parcel itself still behaves the same, and I see "Server running at http://localhost:1234".
But when I try to access that URL, I get a 404.

There was a lot of stuff that just went into 1.9.5. IMO that should have been a minor version bump, not patch.

## 🎛 Configuration (.babelrc, package.json, cli command)

I don't have a babelrc.

## 🤔 Expected Behavior

`parcel` should run a web server I can access.

## 😯 Current Behavior

I get a 404

## 💁 Possible Solution

No idea.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.5
| Node             | 8.11.2
| npm/Yarn         |
| Operating System | Debian on WSL

**Comment by devongovett** [comment]
would be good to find out what change broke it. I don't see anything obvious...

**Comment by gobengo** [comment]
https://github.com/parcel-bundler/parcel/compare/a019bedd84de8c333f3c767ee87ddc93eea5dcd8...master

hmmmm

It would definitely be useful to know if this is unique to Debian *on WSL* or if the same issue happens in Linux even if no Windows is involved.

Things that make me wonder:
* new globbing lib... globbing is different across OSes often.
* lots of changes in Worker management. If these are separate child processes, that could vary across OSes
* errors get swallowed here, maybe elsewhere? https://github.com/parcel-bundler/parcel/compare/a019bedd84de8c333f3c767ee87ddc93eea5dcd8...master#diff-b4f72e6f76fcc656e717af3a421c4b17R50

Is there any way to get verbose debugging output?
