### ISSUE TITLE
Would like a more helpful error message in the case of empty <meta> strings

### ISSUE THREAD

**Issue by CharlesWiltgen** [parcel-bundler/parcel#1714]
# 🐛 Bug report

I'm a new user, and in the course of migrating a working project to Parcel was confused by an error message for an otherwise-valid <meta> tag.

```html
<head>
    <meta name="twitter:image" content="" />
</head>
```

## 🤔 Expected Behavior

Ideally, Parcel either wouldn't error out on empty strings in `<meta>` tags, or would emit a more helpful error if Parcel is unable to work with it.

## 😯 Current Behavior

Received error message: "The 'path' argument must be of type string. Received type object"

🙏Thank you!

**Comment by DeMoorJasper** [comment]
`content=""` is empty, shouldn't be empty, otherwise just leave it out
