### ISSUE TITLE
Event Listeners are not cleared

### ISSUE THREAD

**Issue by angelsalazar** [parcel-bundler/parcel#1718]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```js
{
  "name": "auth0playground",
  "version": "1.0.0",
  "main": "main.js",
  "author": "",
  "license": "MIT",
  "scripts": {
    "dev": "parcel index.html"
  },
  "devDependencies": {
    "parcel": "^1.9.4"
  },
  "dependencies": {
    "auth0-lock": "^11.7.2"
  }
}
```

## 🤔 Expected Behavior

DOM Listeners should be cleared on each hot replacement

## 😯 Current Behavior

every time I made a new change to my main.js file a new Event listener is created and the old ones are not clear.

To ilustrate my problem the following images 

...
Each VM reflects the old listeners
main.js
![screen shot 2018-07-12 at 10 52 14 am](https://user-images.githubusercontent.com/7455593/42644678-c93f8d2e-85c1-11e8-8676-7b60113d4062.png)
first vm 
![screen shot 2018-07-12 at 10 52 36 am](https://user-images.githubusercontent.com/7455593/42644692-d40a624c-85c1-11e8-9adf-f855d041dfdb.png)
second vm
![screen shot 2018-07-12 at 10 52 49 am](https://user-images.githubusercontent.com/7455593/42644701-d8057116-85c1-11e8-888d-67a2aac2cfac.png)
third vm
![screen shot 2018-07-12 at 10 52 55 am](https://user-images.githubusercontent.com/7455593/42644719-dedaa9a2-85c1-11e8-8a19-4644484600f9.png)
console
![screen shot 2018-07-12 at 10 53 00 am](https://user-images.githubusercontent.com/7455593/42644725-e33fcd10-85c1-11e8-8d7c-4bd147d1cd26.png)

## 💻 Code Sample

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div>
        <button id="auth-btn">signin/singup</button>
    </div>
    <div>
        <input type="text" placeholder="Enter pet id" id="petInput" />
        <button id="execute">execute</button>
    </div>
    <script src="main.js"></script>
</body>
</html>
```

```js
import config from "./src/config";
//import { Auth0Lock } from 'auth0-lock';

const BASE_URL = config.API_URL
// console.log(config);

//const btn = document.querySelector('#auth-btn');
const executeBtn = document.querySelector('#execute');

/*const lock = new Auth0Lock(config.CLIENT_ID, config.AUTH0_DOMAIN);


// Listening for the authenticated event
lock.on("authenticated", (authResult) => {
  console.log(authResult)
  // Use the token in authResult to getUserInfo() and save it to localStorage
  lock.getUserInfo(authResult.accessToken, (error, profile) => {
    if (error) {
      // Handle error
      return;
    }
    console.log(profile);
    //document.getElementById('nick').textContent = profile.nickname;

    localStorage.setItem('accessToken', authResult.accessToken);
    localStorage.setItem('profile', JSON.stringify(profile));
  });
});

btn.addEventListener('click', (e) => {
    lock.show();
});*/

executeBtn.addEventListener('click', (e) => {
  console.log('test')
  debugger
  //const petId = petInput.value;
  //console.log(petId)
  fetch(`${BASE_URL}/pets`, {
    headers : {
      'Content-type' : 'application/json'
    }
  })
  .then(blob => blob.json())
  .then(response => console.log(response))
  .catch(err => console.log(err)); 
})
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.4
| Node             | v8.10.0
| Yarn         | 1.5.1
| Operating System | MAC 10.13.4

**Comment by DeMoorJasper** [comment]
Do something like this:

```Javascript
if (module.hot) {
  module.hot.dispose(() => {
    button.removeEventListener('click', buttonHandler);
  });
}
```
or
```Javascript
```if (module.hot) {
  module.hot.dispose(() => {
    window.location.reload();
  });
}```
```

**Comment by angelsalazar** [comment]
@DeMoorJasper thanks for your response
Regarding your solutions I have the following comments
this case

**Comment by DeMoorJasper** [comment]
Did it solve your issue?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by angelsalazar** [comment]
@DeMoorJasper thanks for your response,
I guess the solutions you provided are a work around to this simple scenery.

your first solution only works when I have my elements defined globally. Now let's say I create elements dynamically and attachment them event listeners, I have to keep track of all of them and their listeners in order to clear them on the dispose callback.

the second option works, but then it should not be hot module replacement since  location.reload() does a full refresh

**Comment by DeMoorJasper** [comment]
@angelsalazar it’s not really a simple usecase as this could cause unwanted sideeffects of implemented incorrectly. Not every codebase is the same, and instead of doing a reload you can also clear all events if you can figure out a way to do that. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by angelsalazar** [comment]
@DeMoorJasper I understand, I will use the second solution you provided, I appreciate your response.
