### ISSUE TITLE
Parcel not respecting cssnano config

### ISSUE THREAD

**Issue by vihanb** [parcel-bundler/parcel#1721]
# 🐛 bug report
I have my Sass .scss files which are compiled and then I run those through autoprefixer and cssnano. The problem is that when I do this, cssnano transforms expressions like `scale(1, 0)` to `scaleY(0)` which causes issues in Safari. So I decided I'll just turn off the [`reduceTransforms`](https://cssnano.co/optimisations/reducetransforms/) option in cssnano. However even though I have done this, after running Parcel I still get the same CSS with the transformation of `scale(1, 0)` to `scaleY(0)` being done.

## 🎛 Configuration (.babelrc, package.json, cli command)

My `postcss.config.js`:

```js
module.exports = {
  plugins: [
    require('autoprefixer'),
    require('cssnano')({
      preset: ['default', {
        reduceTransforms: false
      }]
    })
  ]
};
```

And to run parcel I am doing this CLI command:

```
npx parcel build scss/main.scss -d static/css -o main.css
```

## 🤔 Expected Behavior
As above, I am expecting `static/css/main.css` to not have this transformation being applied because in my config I have specified `reduceTransforms: false`

## 😯 Current Behavior
Instead, this transformation is being applied.

## 💁 Possible Solution
I'm not sure why this is happening. Intentionally putting invalid syntax in the postcss.config.js throws a syntax error when running parcel so it is definitely reading the postcss.config.js. Also it does look like autoprefixer is being run correctly so not sure why cssnano wouldn't.

This also doesn't happen when I pass the `--no-minify` flag but I do want minified output

## 🔦 Context
I am statically generating CSS files from SASS which are placed in the server's static files directory so I can serve them. I want to minify the code but this cssnano optimization results in an animation of the `transform:` property not working in Safari.

## 💻 Code Sample

Source code is this line:

```css
.popover {
    transform: scale(1, 0) rotateX(-90deg);
}
```

and out I get:

```css
transform: scaleY(0) rotateX(-90deg);
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1 (running slightly old version because otherwise babel 7 results in error)
| Node             | v8.9.3
| npm/Yarn         | 6.0.1
| Operating System | macOS 10.13.4

other versions:

 - cssnano: 4.0.1

**Comment by gtournie** [comment]
I can't pass any options to cssnano. I tried in postcss.config.js
```
module.exports = {
  plugins: {
    cssnano: { preset: ['default', { discardComments: { removeAll: true } }] },
  },
}
```

and in cssnano.config.js
```
module.exports = {
  preset: ['default', { discardComments: { removeAll: true } }],
}
```

Parcel 1.12.3
Node 12.8.0
npm 6.10.2
macOs 10.14.5
cssnano 4.1.10

**Comment by DeMoorJasper** [comment]
Pretty sure this is still the case

**Comment by mateatslc** [comment]
not much of a help but `cssnano.config.js` works fine for me on Parcel `1.12.4`
