### ISSUE TITLE
SyntaxError: expected expression, got keyword 'import' [Firefox 61.0.1]

### ISSUE THREAD

**Issue by v0idifier** [parcel-bundler/parcel#1728]
# 🐛 bug report

I'm getting the error `SyntaxError: expected expression, got keyword 'import'` in Firefox 61.0.1 when using `import()` to import something.

## 🎛 Configuration (.babelrc, package.json, cli command)

`.babelrc`
```js
{
  "presets": ["stage-0", "env", "react"],
  "plugins": [
    "transform-class-properties"
  ]
}
```

## 🤔 Expected Behavior

Should run the code fine

## 😯 Current Behavior

Throws error
![image](https://user-images.githubusercontent.com/7550995/42716880-1e839524-86d4-11e8-8c72-5ec5e754b338.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | `1.9.6` |
| Node             | `10.6.0` |
| npm/Yarn         | `yarn 1.7.0` |
| Operating System | `Arch Linux` |
| Firefox | `61.0.1` |

**Comment by makmm** [comment]
I'm guessing this happends because Firefox finds the `import` function and thinks of it like an actual `import` statement. Solution could be renaming the `import` function on compile, maybe?

**Comment by v0idifier** [comment]
firefox supports the `import()` function.

**Comment by mischnic** [comment]
Does your code or a library cause this? Please provide a snippet of that code

**Comment by v0idifier** [comment]
this is an old issue. firefox is up to 72 now, and this may not apply (that's why i let it stale.)
