### ISSUE TITLE
Introduce ESLint for linting

### ISSUE THREAD

**Issue by yeskunall** [parcel-bundler/parcel#173]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
🙋

### 🎛 Configuration (.babelrc, package.json, cli command)
N/A

### 🤔 Expected Behavior

To be able to catch errors like #165, and overall introduce linting into `parcel`.

### 😯 Current Behavior

Since there is no setup for linting, we miss out on being able to enhance code quality, and just catch errors in general (which I believe ESLint does a solid job)

### 💁 Possible Solution

Introduce ESLint in some way/shape/form. Either use existing configs like [`eslint-config-airbnb`](https://www.npmjs.com/package/eslint-config-airbnb) or just write our own config.

### 🔦 Context

Not affected me __yet__, but I think adding some form of linting will overall benefit `parcel`.

### 🌍 Your Environment

N/A

Let me know your thoughts on this. 💖

/cc @davidnagli

**Comment by davidnagli** [comment]
Yep, totally agree! What do you guys think of using XO?

**Comment by davidnagli** [comment]
Whoops... nevermind @thejameskyle already implemented linting via Prettier in #121

**Comment by davidnagli** [comment]
Feel free to reopen if you think that we need to change from Prettier or anything like that, but for the time being we already have a linting tool.

**Comment by thejameskyle** [comment]
Prettier is not a linter, there are other things to be caught if we want

**Comment by davidnagli** [comment]
oh ya, my bad

**Comment by lc60005457** [comment]
#64

**Comment by davidnagli** [comment]
@lc60005457 This issue is about introducing linting to the Parcel _source code_ itself, while #64 is about adding linting as part of the build _bundling_ process.

**Comment by bdschr** [comment]
Use the parcel api and call eslint programmatically in the bundler events.
