### ISSUE TITLE
Tests Fail on Windows | +AppVeyor

### ISSUE THREAD

**Issue by brandon93s** [parcel-bundler/parcel#174]
**Choose one:**   &nbsp;&nbsp;&nbsp;&nbsp;  🐛

### 🤔 Expected Behavior

Tests pass on all platforms.

### 😯 Current Behavior

Currently, ~50% of the tests are failing on Windows ([see AppVeyor results](https://ci.appveyor.com/project/brandon93s/parcel)). Some of these are due to a failure in a `beforeEach` hook, but others are legitimate failures. **The test failures could mean that `parcel` isn't working correctly on Windows. (e.g. #86)**

### 💁 Possible Solution

1) Add AppVeyor alongside Travis.ci
2) Start working through and correcting the failures

### 🌍 Your Environment

Occurring on Windows 10 (local) and Windows Server 2012/2016 (AppVeyor).
Occurring on Node.js v9.2.0 (local) and Node.js v8.x.x (AppVeyor).

**Comment by brandon93s** [comment]
Working through these now.

**Comment by brandon93s** [comment]
Stylus tests are failing with the same issues as seen in #158. Stylus may not be working on windows at all at the moment.

**Comment by aicest** [comment]
@brandon93s some details added to #159.
