### ISSUE TITLE
browserslist last 1 version - native api instead polyfills

### ISSUE THREAD

**Issue by andreyantipov** [parcel-bundler/parcel#1742]
# ❔ Question
Don't understand how configure parcel babel with package.json browserlist parameter, seems to me it doesn't work at all - because i can't use native classes, async await functions. Can somebody clarify how i can use native implementation of async/await and es2015 classes without configuring .babelrc and using babel-polyfill and babel-runtime?

## 🔦 Context
```
  "browserslist": [
    "last 1 version"
  ]
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | v8.11.1
| npm/Yarn         | 1.6.0
| Operating System | MacOS 10.13

**Comment by DorianGrey** [comment]
The browser query you're using also includes browsers like IE11 - which provides none of the features you've mentioned natively. Thus, `babel` ([used by default](https://parceljs.org/transforms.html#default-babel-transforms)) will include the required polyfills and apply the necessary transforms.
For reference - you can check your queries here: http://browserl.ist/?q=last+1+version

**Comment by andreyantipov** [comment]
@DorianGrey many thanks! problem is solved just changing to specific browsers versions and .babelrc polyfills no required anymore
