### ISSUE TITLE
Self-signed Certificate security warning

### ISSUE THREAD

**Issue by germanftorres** [parcel-bundler/parcel#1746]
# 🐛 bug report
Environment: Parcel 1.9.7 in Windows 10.

Using --https option generates a self-signed certificate issued to IP 127.0.0.1 and not to localhost. In my system, navigating to https://locahost:1234 causes a security warning even after installing the certificate under Trusted Root Certification Authorities. In contrast, If I navigate to https://127.0.0.1:1234 the certificate is shown as valid.

```
>parcel src\index.html --https
Generating SSL Certificate...
√  Built in 2.94s.
```
## 🤔 Expected Behavior

I would expect to navigate directly to https://locahost:1234 and see no security warning with self signed certifcate.

## 😯 Current Behavior
Security warning!!

## 🌍 Your Environment
Parcel 1.9.7
Windows 10
npm 5.6.0

**Comment by DeMoorJasper** [comment]
This line should probably be updated to `hmr-hostname` and fallback to localhost
https://github.com/parcel-bundler/parcel/blob/75188057e01515f1ee399fa6cda30a5304d1cf17/src/utils/generateCertificate.js#L100

**Comment by shobhitchittora** [comment]
@DeMoorJasper I'd like to pick this up as my first contribution.

**Comment by DeMoorJasper** [comment]
@shobhitchittora feel free to work on it :)

**Comment by dehuszar** [comment]
I'm seeing issues with this as well even when trying to access `https://127.0.0.1:1234`.  The odd thing is if I clear out all certs it works using localhost on the first cert generated, but any subsequent certificates (either after deleting the .cache folder or when creating a new parcel project on the same machine) it starts throwing errors around reused serials.

I'm wondering if [this bit](https://github.com/parcel-bundler/parcel/blob/75188057e01515f1ee399fa6cda30a5304d1cf17/src/utils/generateCertificate.js#L30) needs to be set to a random number or uuid or something.

**Comment by dehuszar** [comment]
Yup.  Just ticked the hard-coded '01' value up to '02' and the issue went away.  I took a stab at requiring `uuid` as a dependency, but that caused an unhandled promise rejection error.  I've used this module in a ton of other projects, so I'm not sure what's causing things to explode here, but it seems that having someway to ensure a unique value for every cert generated by parcel will resolve the issue.

**Comment by DeMoorJasper** [comment]
@dehuszar what about Date.now() ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dehuszar** [comment]
Yup.  Just did that.  Works great.  I can PR it if you like

**Comment by DeMoorJasper** [comment]
Yeah sure a PR would be awesome

**Comment by dehuszar** [comment]
@shobhitchittora, did you still want to update the default ip's

**Comment by julianeden** [comment]
Why was this ticket closed? This issue persists.
