### ISSUE TITLE
importing Bundler tweaks the `require` object and leaves it incoplete

### ISSUE THREAD

**Issue by tripodsan** [parcel-bundler/parcel#1750]
# 🐛 bug report

It looks like the `Bundler` overwrites the `require.resolve` object, such as that `require.resolve.paths()` is no longer present for subsequent modules. eg:

I added this log statement to Module 'A':
```
console.log('Module A: require.resolve.paths = ' + require.resolve.paths);
```
and a similar one to Module 'B':

```
const Bundler = require('parcel-bundler');
const A = require('./A');
console.log('Module B: require.resolve.paths = ' + require.resolve.paths);
```
the output is:

```
Module A: require.resolve.paths = undefined
Module B: require.resolve.paths = function paths(request) {
    return Module._resolveLookupPaths(request, mod, true);
  }
```

when I change the order of the imports to:
```
const A = require('./A');
const Bundler = require('parcel-bundler');
console.log('Module B: require.resolve.paths = ' + require.resolve.paths);
```

then the output is:
```
Module A: require.resolve.paths = function paths(request) {
    return Module._resolveLookupPaths(request, mod, true);
  }
Module B: require.resolve.paths = function paths(request) {
    return Module._resolveLookupPaths(request, mod, true);
  }
```

## 🎛 Configuration (.babelrc, package.json, cli command)

nothing special.

## 🤔 Expected Behavior

the `require` should not be altered after importing `Bundler` or at least the `require.resolve.paths` function should still be present.

## 😯 Current Behavior

see above.

## 💁 Possible Solution

don't know.

## 💻 Code Sample

see above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.4
| Node             | 8.11.3

**Comment by devongovett** [comment]
hmm I can't reproduce this. I get the second output in both cases when I ran the code above... Is there anything else that could be affecting this?

**Comment by tripodsan** [comment]
ok, I did some more tests and could reproduce it in a simple setup:
https://github.com/tripodsan/parcel_require_test

the seems that `Bundle.bundle()` destroys the `require.resolve` object. the import alone is ok.
