### ISSUE TITLE
Source Maps don't work, because a slash is missing

### ISSUE THREAD

**Issue by LukBukkit** [parcel-bundler/parcel#1753]
# 🐛 bug report

Hello,
I want to use the source map feature of parcel. They are generated and linked in the bundled javascript file.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    "env"
  ]
}
```

My watch command:
```bash
parcel watch ./src/main/assets/js/app.js -d ./target/classes/public/dist/ --cache-dir ./target/parcel/cache --no-autoinstall --public-url ./public/dist/
```

## 🤔 Expected Behavior

The link in the bundled file should look as follows
```js
//# sourceMappingURL=/public/dist/app.map
```
and this should be independent of whether there's a slash before `--public-url` or not.

## 😯 Current Behavior

But it looks like this
```js
//# sourceMappingURL=public/dist/app.map
```

This `sourceMappingURL` is generated by parcel and depends on the `--public-url` argument. 
If I set this to `/public/dist/`, the source map url is correct, but otherwise there's a slash missing.

In your [documentation](https://parceljs.org/cli.html#set-the-public-url-to-serve-on) the `--public-url` also starts with a dot, so I think this could be confusing for some users.

## 💁 Possible Solution

I guess this error is caused by [JSPackager:219](https://github.com/parcel-bundler/parcel/blob/0ac4e297adf95cff78de361fc4867fd412ec3b60/src/packagers/JSPackager.js#L219), maybe the `urlJoin` function doesn't work as excepted.

## 🔦 Context

The cause of this issue could also be the cause of the issue #1659.

## 💻 Code Sample

Run a command like this:
```bash
parcel watch ./src/main/assets/js/app.js -d ./target/classes/public/dist/ --public-url ./public/dist/
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7 |
| Node             | v10.6.0 |
| npm/Yarn         |1.7.0 |
| Operating System | Windows 10 (Version 1803) |

**Comment by DeMoorJasper** [comment]
This isn't meant to be confusing, the docs show how to set them to relative urls as the default is a `/` we couldn't use that as an example.

If you change your public-url to an absolute path it should work. Not sure why relative paths wouldn't work

**Comment by DeMoorJasper** [comment]
My reply should have resolved this issue
