### ISSUE TITLE
Is there a way to turn off the md5 on built assets?

### ISSUE THREAD

**Issue by rizowski** [parcel-bundler/parcel#1757]
# ❔ Question
Is there a way to turn off the MD5 that is put on the filenames?

## 🔦 Context
I deploy a solution to an AWS S3 bucket which is then served by Cloud Front. Problem I have been running into is every time I deploy I am filling up my bucket with new md5 files rather than just replacing them. I would like to be able to turn off the autogenerated hash so I can just replace the files on S3 upload.

## Related Issues

#717

**Comment by DeMoorJasper** [comment]
It is possible in the API using `contentHash:false` in the options object.

Currently no cli flag sets this option however

**Comment by rizowski** [comment]
It would be nice to have this in the docs here: https://parceljs.org/api.html
So I added the change: https://github.com/parcel-bundler/website/pull/213

**Comment by rizowski** [comment]
Actually, That doesn't do what I was expecting. Either way there is a file hash included in the filename.

**Comment by DeMoorJasper** [comment]
Well there is but it doesn't change

**Comment by rizowski** [comment]
Closing since question was answered. Thanks @DeMoorJasper

**Comment by bekliev** [comment]
Hm... what if in my use-case I need no just replace new build assets (without md5 on them)?
Is there a way to cut md5 at the end of build assets?

**Comment by bekliev** [comment]
Fixed my issue!
And now have such a bundler:
```js
const Bundler = require('parcel-bundler');

const entryFiles = ['./src/index.css', './src/index.js'];

// Bundler options
const options = {
  minify: true,
};

(async function() {
  const bundler = new Bundler(entryFiles, options);
  bundler.serve();
})();
```

P.S. How to make a bundler? Read this: [parceljs.org/api.html](https://parceljs.org/api.html)
I run it like: `node parcel-bundler.js`

**Comment by mischnic** [comment]
> Hm... what if in my use-case I need no just replace new build assets (without md5 on them)?

I don't quite understand what you want to say here. But with `--no-content-hash` the hash at the end is stable across multiple (if that's what you meant by "replace")

**Comment by bekliev** [comment]
> > Hm... what if in my use-case I need no just replace new build assets (without md5 on them)?
> 
> I don't quite understand what you want to say here. But with `--no-content-hash` the hash at the end is stable across multiple (if that's what you meant by "replace")

That option doesn't work
![image](https://user-images.githubusercontent.com/4066435/57121283-25905180-6d7f-11e9-8c04-a1a41cf4708a.png)
