### ISSUE TITLE
Parcel incorrectly converts linked json to Javascript

### ISSUE THREAD

**Issue by Qix-** [parcel-bundler/parcel#1764]
# 🐛 bug report

Some user agents require a `<link />` tag with some **actual JSON** (not JSON-compatible JS module). Unfortunately there seems to be no way to prevent Parcel from converting it into some JS module nonsense.

## 🎛 Configuration (.babelrc, package.json, cli command)

Completely stock Parcel.

## 🤔 Expected Behavior

Parcel should leave the file alone, keeping the `json` extension, _maybe_ minifying the JSON data itself but nothing more.

## 😯 Current Behavior

Parcel converts the JSON data into a Javascript object and module export and renames the file to `.js`.

## 💁 Possible Solution

Please stop converting JSON data.

## 🔦 Context

Trying to get Chrome to read the [`manifest.json`](https://developers.google.com/web/fundamentals/web-app-manifest/) from the `<link rel="manifest" />` tag in an HTML entry point.

## 💻 Code Sample

manifest.json
```json
{
  "foo": "bar"
}
```

```html
...
<head>
    <link rel="manifest" href="manifest.json" />
</head>
...
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7 |
| Node             | 8.9.3 |
| npm/Yarn         | 5.5.1 |
| Operating System | Alpine Linux (docker) |

**Comment by DeMoorJasper** [comment]
This has been a known bug for quite a while, we basically have to detect where it is being required from and handle it differently for html as js.

**Comment by DeMoorJasper** [comment]
For manifest you should use .webmanifest though

**Comment by icopp** [comment]
> For manifest you should use .webmanifest as extension though

Chrome's docs specifically want a `manifest.json`.

**Comment by serranoarevalo** [comment]
Any workaround for this?

**Comment by Qix-** [comment]
@serranoarevalo Not that I was aware of. I switched to Rollup.

**Comment by kahurangitama** [comment]
Any news here?

**Comment by danmarshall** [comment]
You may want to see #501 , I was able to use the workaround.

**Comment by keonnicholas** [comment]
> You may want to see #501 , I was able to use the workaround. YMMV

I'm guessing you're referring to the[ parcel-plugin-json-url-loader](https://github.com/shunia/parcel-plugin-json-url-loader) workaround? This does not seem to be working for me. Still getting .js output. 😢

**Comment by folknor** [comment]
Is this the same as #5743 but for Parcel 1.x? They seem related at least. I was trying to find #5743 when I found this bug.

**Comment by timoffex** [comment]
This isn't fixed. I ran into this while trying to use a Lottie animation in my project

```
/**
  src/
    animation.json
    MyAnimation.ts
**/

// In MyAnimation.ts
// The animation.json file gets turned into a js file, and Lottie can't use it.
const LOTTIE_FILE = new URL('./animation.json', import.meta.url).toString();
```

The solution that worked was to rename the file to have a different file extension (I changed it to `.json.lottie`).
