### ISSUE TITLE
Allow configuration of terser options

### ISSUE THREAD

**Issue by goyney** [parcel-bundler/parcel#1765]
# 🙋 feature request

Please allow a way for us to configure which options the `terser` module uses when uglying the output production code. It looks like `-m -c` are being hard-coded in Parcel.

## 🤔 Expected Behavior

In some configuration file or within my package.json, I can specific which options to execute `terser` with.

## 😯 Current Behavior

I have no control over how `terser` runs.

## 🔦 Context

We need more control of how `terser` generates our output. Specifically, we'd like to use `--toplevel`.

Full listing of all available options for `terser` can be found here: https://www.npmjs.com/package/terser

**Comment by DeMoorJasper** [comment]
You can configure it using a terserrc or uglifyrc file

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by goyney** [comment]
Care to elaborate? This isn't documented anywhere.

When I add either a `.terserrc` or `.uglifyrc` file with an appropriate configuration, it doesn't change anything.

**Comment by DeMoorJasper** [comment]
You can have a look at the source starting here: https://github.com/parcel-bundler/parcel/blob/master/src/transforms/terser.js#L10

**Comment by subhero24** [comment]
I think this has something to do with resolving of the config file and #1405 .

**Comment by marcelkorpel** [comment]
Why is this issue closed? I looked at [terser.js](https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/transforms/terser.js#L10), but whatever I add in my `.terserrc`, it isn't taken into account. E.g., when using
```json
{
  "output": {
    "comments": true
  }
}
```
all comments are still stripped when running `parcel build`.

The file should be in the same directory as `package.json`, shouldn't it?

**Comment by stevensun32** [comment]
@marcelkorpel have you tried clearing the parcel cache and dist folders?

**Comment by marcelkorpel** [comment]
@stevensun32 Yes, I did, just tried again, but it seems the contents of `.terserrc` aren't taken into account at all, all comments simply get stripped. Is my syntax still correct?
