### ISSUE TITLE
More helpful Babel defaults

### ISSUE THREAD

**Issue by texastoland** [parcel-bundler/parcel#1768]
# 🙋 feature request

Additional Babel plugins notably:

- [@babel/proposal-object-rest-spread](https://babeljs.io/docs/en/babel-plugin-transform-object-rest-spread/) (for [React](https://reactjs.org/docs/jsx-in-depth.html#spread-attributes))
- [@babel/proposal-class-properties](https://babeljs.io/docs/en/babel-plugin-syntax-class-properties) (for [React](https://reactjs.org/docs/typechecking-with-proptypes.html#default-prop-values))
- [@babel/preset-react](https://babeljs.io/docs/en/babel-preset-react) (React-specific)
- [@babel/typescript](https://babeljs.io/docs/en/next/babel-preset-typescript.html) (for TypeScript integration)
- [babel-plugin-macros](https://babeljs.io/blog/2017/09/11/zero-config-with-babel-macros) (in create-react-app for simpler configuration)
- Auto-import plugins from config (`package.json`, `babelrc`, presets)

## 🤔 Expected Behavior

Import a typical React project requires no setup.

## 😯 Current Behavior

Import a typical setup requires knowing you need plugins and which, manually adding them individually or with `babel-preset-stage-x` (multiple choices), knowing how to config, and manually adding a config (2 choices where). We're accustomed to starting every project that way but not as welcoming as it could be.

### Additional Babel plugins

Add inside `getEnvConfig` and `getJSXConfig` respectively here:

https://github.com/parcel-bundler/parcel/blob/871ffc7a03b595398e8fca0fba097002d54b4755/src/transforms/babel.js#L104-L105

### Auto-import plugins

`localRequire` all presets and plugins from `getBabelConfig` here:

https://github.com/parcel-bundler/parcel/blob/871ffc7a03b595398e8fca0fba097002d54b4755/src/transforms/babel.js#L58-L60

## 🔦 Context

#1632
["Fastest/easiest way to add Object spread to @parceljs ?"](https://twitter.com/johnlindquist/status/1020072729075044352)
["Just make sure to include babel-plugin-macros so your users can enjoy some zero config Babel plugin transforms too! 👍"](https://twitter.com/kentcdodds/status/942096983254110208)

## 💻 Examples

[TypeScript-Babel-Starter](https://github.com/Microsoft/TypeScript-Babel-Starter/blob/master/.babelrc)

**Comment by davidnagli** [comment]
See my PR addressing you're doing 'Auto-import plugins' point: #1772
