### ISSUE TITLE
Silent failure of "watch" on Microsoft Windows 7 pc

### ISSUE THREAD

**Issue by raould** [parcel-bundler/parcel#1773]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

Wait, why would I have any config when parcel is supposed to be zero config? :-) 

But seriously, folks...

I am starting with a from-scratch app, to learn parcel & typescript. Zip file attached, without all the node_modules, but with package.json etc. (By the way, I do not use "npm -g" for anything as much as I can avoid it.) See the "code sample" section below.

## 🤔 Expected Behavior

1. DOS> node_modules\.bin\parcel watch index.html
1. DOS> √  Built in 108ms.
1. Firefox: go to the url "http://localhost:1234"
1. Should see the page I made.

# 

## 😯 Current Behavior

The page fails to load, and Firefox says, "Unable to connect".

## 💁 Possible Solution

If I do not use the "watch" command, but just compile once and go to the same url, then it works and I do see my page.

## 💻 Code Sample

[jshell.zip](https://github.com/parcel-bundler/parcel/files/2217974/jshell.zip)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.7
| Node             | 8.11.3
| npm/Yarn         | npm 5.6.0
| Operating System | Windows 7 Pro 64 bit Service Pack 1

**Comment by Qix-** [comment]
This is happening on Linux as well. Watch builds initially, but doesn't catch any changes to files, including entry point and all assets.

**Comment by raould** [comment]
Wait, if I omit the "watch" from the command, then it seems to actually *be* watching anyway. Although I don't see anything in the command prompt buffer to indicate, when I reload the page in Firefox it does seem to get new versions of my *.ts files. Did I read some out of date docs or something about how the cli commands work?

**Comment by Rarst** [comment]
Also having issue with watch on Windows 7 (server or `watch` command either), seems to detect a file change _once_ and then just sits there without doing anything.

Parcel version 1.11.0

**Comment by jorrit** [comment]
Same behavior on Ubuntu, 1.12.3. One change is processed, after that none.
