### ISSUE TITLE
Watch + node --inspect failed: address already in use

### ISSUE THREAD

**Issue by noygal** [parcel-bundler/parcel#1776]
# 🐛 bug report

When trying to use parcel middleware feature with the node --inspect flag on I get consecutive errors:

```bash
$node --inspect server.js
Debugger listening on ws://127.0.0.1:9229/fde5fc2f-e474-454c-ba0a-6b47e78970fa
For help see https://nodejs.org/en/docs/inspector
⠋ Building...Starting inspector on 127.0.0.1:9229 failed: address already in use
Starting inspector on 127.0.0.1:9229 failed: address already in use
✨  Built in 83ms.
Starting inspector on 127.0.0.1:9229 failed: address already in use
Starting inspector on 127.0.0.1:9229 failed: address already in use
Starting inspector on 127.0.0.1:9229 failed: address already in use
Starting inspector on 127.0.0.1:9229 failed: address already in use
Starting inspector on 127.0.0.1:9229 failed: address already in use
Starting inspector on 127.0.0.1:9229 failed: address already in use
```

## 🎛 Configuration (server.js, index.html)

```js
const Bundler = require('../parcel/src/Bundler');
const app = require('express')();

const file = 'index.html'; // Pass an absolute path to the entrypoint here
const options = {
  watch: true
}; // See options section of api docs, for the possibilities

// Initialize a new bundler using a file and options
const bundler = new Bundler(file, options);

// Let express use the bundler middleware, this will let Parcel handle every request over your express server
app.use(bundler.middleware());

// Listen on port 8080
app.listen(8080);
```

```html
<html>
<body>
</body>
</html>
```

## 🤔 Expected Behavior

I should be able to use node --inspect feature, it solidly work till v1.8.1

## 😯 Current Behavior

I cannot launch my sever with debug tools turned on

## 💁 Possible Solution

I investigate the issue for couple of hours, my immediate suspect was the workfarm: https://github.com/noygal/parcel/tree/master/src/workerfarm , but this wasn't the issue.

The real issue was with a similar code found in the watcher dependency: 
https://github.com/DeMoorJasper/fswatcher-child

The code is nearly identical to the workfarm code, so I open a PR with the fix that exist on parcel:
https://github.com/DeMoorJasper/fswatcher-child/pull/2

In any case I would migrate this code to parcel package itself, such a sensitive (and duplicated) code should be under parcel package ownership.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | > 1.8.1
| Node             | > 4
| npm/Yarn         | N/A
| Operating System | N/A

**Comment by DeMoorJasper** [comment]
I can confirm this bug, also had it last time I tried to performance test Parcel

**Comment by reduardo7** [comment]
Maybe it's related to https://github.com/nodejs/node/issues/9435

**Comment by DeMoorJasper** [comment]
Should be resolved, was an issue with the watcher
