### ISSUE TITLE
How to package typescript type files?

### ISSUE THREAD

**Issue by lamphc** [parcel-bundler/parcel#1777]
# ❔ Question

Typescript-based class library, how to package typescript type files
## 🔦 Context

I added the tsconfig.json file, configured the compilation option declaration, but did not generate the type file.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 8.9.1
| npm/Yarn         | 6.1.0
| Operating System | mac osx

**Comment by lamphc** [comment]
help?

**Comment by DeMoorJasper** [comment]
Use parcel-plugin-typescript, parcel core probably does not support this

**Comment by szagi3891** [comment]
@DeMoorJasper 

Perhaps you know something about the plans for better support of typescript by parcel?
Are there any plans in this area?

**Comment by DeMoorJasper** [comment]
@szagi3891 parcel-plugin-typescript will probably become the core typescript implementation starting parcel 2.0 or maybe even sooner.

**Comment by szagi3891** [comment]
@DeMoorJasper 
When may parcel 2.0 occur? Is it a matter of months or maybe a year?

**Comment by DeMoorJasper** [comment]
There is no set timeline for the release, it's gonna take a little while before it gets released.
Probably months, I don't think it'll take another year

**Comment by lamphc** [comment]
@DeMoorJasper I tried parcel-plugin-typescript, but still didn't generate type files

**Comment by mischnic** [comment]
Duplicate of #1240
