### ISSUE TITLE
Add a html bundleloader

### ISSUE THREAD

**Issue by devlux** [parcel-bundler/parcel#178]
🙋 feature request

Add a html bundleloader to allow html fragments to be loaded dynamically, like already possible with js or css content.

### 🤔 Expected Behavior

Add a html bundleloader to allow html fragments to be loaded dynamically, like already possible with js or css content.

import('view.html')

### 😯 Current Behavior

Currently the following exception is thrown as no html bundleloader is implemented yet:

bundleLoaders[type] is not a function

### 💁 Possible Solution

Add a new html bundleloader to the existing bundleloaders:

https://github.com/parcel-bundler/parcel/blob/c8295de9b7a1955c70f3619ccdced93284e6f601/src/builtins/bundle-loader.js#L24

### 🔦 Context

I'm migrating a small spa from requirejs to parcel-bundler.

**Comment by abiduzz420** [comment]
This issue looks interesting to me, although I don't know much about it. I shall r read about it. I would like to take it up @davidnagli

**Comment by davidnagli** [comment]
@abiduzz420 Sounds good!

**Comment by abiduzz420** [comment]
@davidnagli  @devlux I am going to add support for `"div", "button" `. Please suggest me other html fragments which should be included?

**Comment by abiduzz420** [comment]
I have done some reading and got a bit of understand. Want to share the code on the lines I'm thinking. Would like to know if I'm doing it properly:

**Comment by devlux** [comment]
@abiduzz420 thanks for taking over this story! :-) I've read into the code myself today and I think the loadHTMLBundle method receives an URL to load the HTML fragment from. The purpose of this method is to load the content from that URL, e.g. by using the link element as follows:

```javascript
function loadHTMLBundle(bundle) {
  return new Promise(function (resolve, reject) {
    var link = document.createElement('link');
    link.rel = 'import';
    link.href = bundle;
    link.onerror = function (e) {
      link.onerror = link.onload = null;
      reject(e);
    };

    link.onload = function () {
      link.onerror = link.onload = null;
      resolve();
    };

    document.getElementsByTagName('head')[0].appendChild(link);
  });
}
```

The content may then be accessed by calling:

```javascript
var content = document.querySelector('link[rel="import"]').import;
```

Unfortunately HTML import it is not yet supported by all browsers:

https://caniuse.com/#search=html%20import

I'm still trying to understand how the bundle model is created initially. And in the end the content needs to resolved by the require promise. Therefore the above snippet seems to be only one part of the solution... ;-)

**Comment by abiduzz420** [comment]
@devlux Thanks for sharing the update.

**Comment by abiduzz420** [comment]
@devlux Have you looked at Webpack, browserify source code on how they solve this problem ? Perhaps we can take inspiration from there. I will look into how this problem is solved by these. Do let me know if you've found something exciting 😄

**Comment by abiduzz420** [comment]
I wrote the test for the below, not able to figure why it throws TypeError: `name` undefined.

```
1) html should support dynamic imports for HTML:
     TypeError: Cannot read property 'name' of undefined
      at assertBundleTree (test\utils.js:93:39)
      at Context.<anonymous> (test\html.js:141:5)
      at <anonymous>
```

**Comment by DeMoorJasper** [comment]
@abiduzz420 hmu on slack would love to help you out with implementing this

**Comment by hyperpress** [comment]
Just wanted to make sure everyone knows Polymer 3 abandons HTML Imports in favor of ES6 modules NPM. You can glean an example of Polymer 3 pre.12, PSK (Polymer Starter Kit) with Webpack at: https://goo.gl/9KSRr7 Would love to see Parcel for Polymer 3. 🤗
