### ISSUE TITLE
Create a vulnerability disclosure policy

### ISSUE THREAD

**Issue by fathyb** [parcel-bundler/parcel#1784]
It'd be cool if we have :
- an explicit document, both for maintainers and reporters (eg. https://github.com/bugcrowd/disclosure-policy)
- a mailbox redirecting to each maintainer email address, public issues shouldn't be used for this
- a tool like [Snyk](https://snyk.io/) could also help prevent this ahead of time

Related #1783

**Comment by mishaor** [comment]
AFAIK GitLab can do the mailbox thing

**Comment by DeMoorJasper** [comment]
Will close this due to inactivity. I don't really think it's that important for Parcel anyway
