### ISSUE TITLE
bug: HTML file is not updated on update; .cache has stale copy

### ISSUE THREAD

**Issue by hrgui** [parcel-bundler/parcel#1789]
# 🐛 bug report

**Repo**
1. Run `parcel index.html`
2. Change apple.html (add some numbers)

## 🎛 Configuration (.babelrc, package.json, cli command)

None, ran `parcel index.html`

## 🤔 Expected Behavior

Would expect the console.log to have the updated version of the HTML updated file

## 😯 Current Behavior

The console.log never updates with the latest version of `apple.html` despite the page knowing there was an update

## 💁 Possible Solution

The only workaround right now is to remove the `.cache` directory and rerun parcel.

## 🔦 Context

Trying out AngularJS experience with Parcel. AngularJS requires HTML templates; but even without AngularJS Parcel does not reload HTML files correctly.

## 💻 Code Sample

index.js
```js
const apple = require('./apple.html');
console.log(apple);
```

apple.html
```html
<h1>test224443331111112</h1>
```

index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <script src="./index.js"></script>
</body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | using github repo  and link | 
| Node             |  8.3.0 | 
| npm/Yarn         | 1.5.1 | 
| Operating System | MacOS |

**Comment by Abandon99** [comment]
The same problem for me .... Do you solve that?

**Comment by DeMoorJasper** [comment]
Could you guys try it with the latest stable parcel? (1.9.7)

**Comment by hrgui** [comment]
@DeMoorJasper I was using the build version and used yarn link.

I'll retry with the stable 1.9.7 when I get a chance and comment again

**Comment by DeMoorJasper** [comment]
@hrgui yeah, that makes sense as the html bundle loader, got pushed to master after 1.9.7 and will be part of the next release

**Comment by hrgui** [comment]
`yarn link parcel-bundler` gives me exactly the error that I have described

**Comment by DeMoorJasper** [comment]
Exiting and re-executing the command fixes the issue, so this has nothing to do with cache, but something else

**Comment by DeMoorJasper** [comment]
After a bit of debugging I came to the discovery that the changes for processing inline styles and scripts inside html caused generate to output an empty array in most cases, the hash gets calculated based on the output of generate, so in this case an empty hash...

Fixed it by adding the original content to the hash

**Comment by DeMoorJasper** [comment]
Please try out #1861

**Comment by hrgui** [comment]
@DeMoorJasper It works out perfectly!

**Comment by DeMoorJasper** [comment]
It's not supposed to be in a constant loading state, not sure why that's happening, it worked for me. Feel free to debug it

**Comment by hrgui** [comment]
@DeMoorJasper it has to do w/ the websocket left open, not sure why

probably its something ive done

**Comment by DeMoorJasper** [comment]
Yeah probably, glad the content hash resolved the issue though :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
