### ISSUE TITLE
[RFC] New Labeling System

### ISSUE THREAD

**Issue by davidnagli** [parcel-bundler/parcel#179]
Do you guys find the new labeling system useful?

What labels should I add / remove?

I'm currently in the process of going through all the open issues and tagging them, and I wanted to know if you like the system of labels that I'm using. It looks a bit unique at first, but the goal is to be highly categorizable and informative.

Let me know what you guys think...

**Comment by thejameskyle** [comment]
My advice is to be lazy about labels and only use the ones which are super useful to you. Most people don't search using labels, and you end up spending a ton of time maintaining them.

Good labels:

- "help wanted" - Signals to people that their contributions would be accepted, GitHub uses this for various UIs to encourage contribution
- "good first issue" - Helps get new people contributing, GitHub uses this for various UIs to encourage contribution
- "bug confirmed" - Just marking something as "bug" doesn't help much, but issues where several people have run into a bug and have provided info or even a test case is super useful
- Topics (i.e. "Windows") - This can help specialized contributors identify which issues they should care about

Labels I don't like:

- Statuses (i.e. "WIP") - Maintaining the status of an issue is a massive time sink and really useful at all
- "Low Priority" - This just encourages people not to contribute to certain issues, it tells them you don't care

Fewer labels mean people actually pay attention to them. People won't really use most of them for searching anyways. Don't attach 20 labels to a single issue.

**Comment by davidnagli** [comment]
Ok I cleaned everything up
