### ISSUE TITLE
Uncaught ReferenceError: {script tag depedency} is not defined

### ISSUE THREAD

**Issue by chriszrc** [parcel-bundler/parcel#1793]
# 🐛 bug report

I am working with a default website export from a gis program, which is using just standard script tags. The repo and example page are here:

https://github.com/chriszrc/qgis-to-web-parcel-test
https://chriszrc.github.io/qgis-to-web-parcel-test/index.html

As you can see, the way the scripts are being imported (with script tags), everything works fine. If I try to serve or build the project with parcel, I get :

```
Uncaught ReferenceError: labelgun is not defined
...
Uncaught ReferenceError: json_cb_2017_us_state_20m_0 is not defined
```

Labelgun is one of the imported libraries, the second is a script file with a single declared global "var". 

## 🎛 Configuration (.babelrc, package.json, cli command)
This is an older project, and so it's not using babel or even a package.json (until parcel automatically adds one for it). I'm running the cli using just:

```
parcel index.html
```

## 🤔 Expected Behavior

The dependencies in the script tags should all still be globally available to the main.js script

## 😯 Current Behavior

Currently, some of the variables that are exposed are no longer available in the global scope to the main.js file, so I get these errors:

```
labels.js:9 Uncaught ReferenceError: labelgun is not defined
    at Object.parcelRequire.js/labels.js (labels.js:9)
    at newRequire (labels.15c84194.js:48)
    at parcelRequire.js/labels.js (labels.15c84194.js:80)
    at labels.15c84194.js:106
parcelRequire.js/labels.js @ labels.js:9
newRequire @ labels.15c84194.js:48
parcelRequire.js/labels.js @ labels.15c84194.js:80
(anonymous) @ labels.15c84194.js:106
```

```
Uncaught ReferenceError: json_cb_2017_us_state_20m_0 is not defined
    at Object.parcelRequire.js/main.js (main.js:100)
    at newRequire (main.a9292cb1.js:48)
    at parcelRequire.js/main.js (main.a9292cb1.js:80)
    at main.a9292cb1.js:106
```

## 💁 Possible Solution

I tried using the --global flag, but that didn't seem to expose the variables either

## 🔦 Context

When I'm working on a modern project (e.g. angular), the build steps are already included by their respective clis. But for these legacy projects, it would be so wonderful to be able to reliably use parcel, since it could be a drop in solution for getting a more performant build. 

## 💻 Code Sample

https://github.com/chriszrc/qgis-to-web-parcel-test
https://chriszrc.github.io/qgis-to-web-parcel-test/index.html

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |    1.9.7
| Node             |    v8.11.1
| npm/Yarn         |   5.6.0
| Operating System | MacOS

**Comment by chriszrc** [comment]
Ok, 

I think I can answer my own question now. I think it's very non obvious that by default, even with no babelrc, that parcel expects, or at least deals with es6 imports. The above problem could easily be solved by adding this to the top of the page for the library dependencies:

```
import * as fetch from 'whatwg-fetch';
import * as fetchJsonp from 'fetch-jsonp';
import yourvar from './json_cb_2017_us_state_20m_0.js';
```

and something like this in your local dependency files:

```
export default yourvar
```

However, this seems totally non obvious from the getting started docs-

**Comment by DeMoorJasper** [comment]
Well if you use es6 syntax it uses es6 imports...

Parcel uses `babel-env` by default so it just transpiles down to IE11 as mentioned in the docs https://en.parceljs.org/transforms.html#default-babel-transforms

**Comment by DeMoorJasper** [comment]
Ow I see, seems quite strange to do this though, as it defies using a bundler at all, you could probably just use babel-cli for this codebase as you don't use any requires or imports.

Not sure if using globals this heavily would impact stability, as as far as I know scripts don't load in the order they are imported.

**Comment by chriszrc** [comment]
I just started to use parcel, and I think I had the misimpression that parcel would also automatically bundle pages like this as well, by looking at the scripts on the page and created a bundled version. I see now that it does not-

**Comment by DeMoorJasper** [comment]
Ow yeah, that's some bundling magic we don't have yet, might be a cool plugin somewhere in the future :)

I'll close this issue as it seems to be resolved. Feel free to open up new issues or join our spectrum.chat if you have any more

**Comment by chriszrc** [comment]
@DeMoorJasper thanks again for taking the time to investigate 👍
