### ISSUE TITLE
Should default to index.html, or show an error

### ISSUE THREAD

**Issue by raould** [parcel-bundler/parcel#1797]
# 🙋 feature request

## 🤔 Expected Behavior

parcel should default to using index.html, or error out.

## 😯 Current Behavior
1. I have a project with index.html
1. I type "parcel" not "parcel index.html"
1. parcel starts up happily
1. but when i load the site, i get nothing.

## Expected
1. I have a project with index.html
1. I type "parcel" not "parcel index.html"

either
* parcel starts up happily by using index.html by default.
or
* parcel throws an error.

**Comment by DeMoorJasper** [comment]
Parcel currently looks at the main in pkg.json if using parcel.

We could however do a glob for index and use the first one it finds. Downside of this is it's pretty unpredictable. If you'd add a CSS file named index in the same folder it would bundle that instead of HTML

**Comment by DeMoorJasper** [comment]
An error message seems like a good idea

**Comment by rajikaimal** [comment]
Hi, I can look into this

**Comment by DeMoorJasper** [comment]
@rajikaimal great, let us know if you need any guidance or help :)

**Comment by rajikaimal** [comment]
Can you mention where the logic related to finding the main script in pkg.json resides?

**Comment by DeMoorJasper** [comment]
These are the locations it uses to resolve entries
https://github.com/parcel-bundler/parcel/blob/master/src/Bundler.js#L82
https://github.com/parcel-bundler/parcel/blob/master/src/Bundler.js#L243
https://github.com/parcel-bundler/parcel/blob/master/src/Bundler.js#L393

**Comment by rajikaimal** [comment]
Hope this creates the intended behavior :)
