### ISSUE TITLE
have only either "npm parcel" or "npm parcel-bundler" but not both

### ISSUE THREAD

**Issue by raould** [parcel-bundler/parcel#1798]
very confusing otherwise.

e.g. https://www.npmjs.com/package/parcel

says both "npm i parcel" on the rhs

and yet it then says "npm install -g parcel-bundler" down the page.

?!?!?!!

**Comment by DeMoorJasper** [comment]
This was originally because people installed it as `parcel` instead of `parcel-bundler`, now it installs parcel bundler for both.
Eventually parcel is gonna move to an npm org for parcel 2 so it will be less confusing.
