### ISSUE TITLE
Parcel not handling linked modules properly

### ISSUE THREAD

**Issue by chiefGui** [parcel-bundler/parcel#1799]
# 🐛 bug report

Parcel isn't compiling a module in a `yarn link`ed package, as well as not respecting my content on `.babelrc`.

## 🎛 Configuration (.babelrc, package.json, cli command)

Please, refer to https://github.com/chiefGui/parcel-babelrc-skipping-bug

## 🤔 Expected Behavior

Having the compiler to correctly parse the tokens on the `node_modules/` of my linked package.

## 😯 Current Behavior

![image](https://user-images.githubusercontent.com/1330257/43266258-4dcc4a0a-90c1-11e8-8a1c-a7d01a13a179.png)

## 💁 Possible Solution

`.babelrc` seems to be ignored on the root project. I think once Parcel stops skipping it, we'll be able to fix this `Unexpected Token` behavior by using some custom transforms.

## 🔦 Context

1. One repo for the actual `app`
2. Another repo for the "`lib`" which will be linked by the `app`
3. Still not sure why, but some libraries (such as [Typography.js](https://kyleamathews.github.io/typography.js/)) installed by the `lib` are breaking the compiler. And more: an attempt to fix it by using a custom `.babelrc` on the root doesn't seem to work because seems that Parcel is skipping it.

## 💻 Code Sample

Please, refer to https://github.com/chiefGui/parcel-babelrc-skipping-bug

1) Clone
2) Yarn install in both `app/` and `lib/`
3) `yarn link` on `lib/`
4) `yarn link @scoped/lib` on `app/`
5) `yarn start` on `app/`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 9.2.0
| npm/Yarn         | yarn 1.9.1
| Operating System | MacOS High Sierra

**Comment by DeMoorJasper** [comment]
For linked modules you can use this: #1101

Babel is ignored on any node_module by default as they are expected to be transformed to some form of standardised JS

**Comment by chiefGui** [comment]
@DeMoorJasper

Thanks for the quick response, though the `"source": true` property doesn't seem to work. Just pushed a commit adding it for you to check out and confirm if it's not something related to my setup or something.

Thanks.

**Comment by DeMoorJasper** [comment]
Maybe clear the cache? I hope that fixes it because it looks good to me

**Comment by chiefGui** [comment]
@DeMoorJasper I quite can't understand why this was closed. Weren't you able to reproduce?

**Comment by DeMoorJasper** [comment]
I thought clearing the cache fixed it. I'll have a look at it

**Comment by DeMoorJasper** [comment]
Yeah well not sure I understand, your module does not have a babel config, how is it supposed to use a non existing babel config?

**Comment by DeMoorJasper** [comment]
If I comment out `typography` module out, it works perfectly. 

That module isn't linked, so it doesn't get magically transpiled using babel inside Parcel. This originally happened in the first few versions of parcel, but after a very long discussion this got replaced by using babel-preset-env on everything and hoping every published module does use a standardized version of JS. (not stage-0).

Now custom babel configs only apply on linked modules.

**Comment by chiefGui** [comment]
@DeMoorJasper 

Your explanation makes sense.

> [...] and hoping every published module does use a standardized version of JS. (not stage-0).

And this is sad.

But thank you for clarifying it anyways. Never imagined it could be something by design.

**Comment by chiefGui** [comment]
By "exotic syntax" you mean... [Flow?](https://flow.org/en/docs/types/modules/)

This means I can't import flow-typed modules, is that it?

**Comment by DeMoorJasper** [comment]
Yeah I guess, never used Flow.
Not sure, I guess you can open up a new issue describing flow-typed modules are not working.

If this is the recommended way to publish flow-typed modules, this is def something we need to look into. If this is not supposed to be used like this, than I suppose you'll have to open up an issue with the `typography` module maintainers.

Like I said earlier have no experience with Flow yet

**Comment by DeMoorJasper** [comment]
We need to figure out a way to whitelist or only use flow instead of running it through the entire babel config of a node module

**Comment by chiefGui** [comment]
My project is TypeScript. `typography`, which is a third-party module, uses Flow. The libraries aren't linked and Parcel is not transpiling flow-typed syntax. It's pretty much it.

[This may resolve](https://babeljs.io/docs/en/babel-plugin-transform-flow-strip-types.html), but I can't apply it on non-linked modules—and that's where I was when I opened this issue.

**Comment by DeMoorJasper** [comment]
I'm aware but not transpiling node modules is the intended behaviour of parcel. As previously mentioned, there has been a long discussion about this in one of the very first issues on this repo.

Not sure how to resolve this, like I said maybe create a whitelist or a way to detect FlowTyped modules

**Comment by chiefGui** [comment]
@DeMoorJasper well, I'll just reference [this other issue](https://github.com/parcel-bundler/parcel/issues/423), which pretty much exposes the same situation.

Thank you.

**Comment by DeMoorJasper** [comment]
Apparently flow modules should be published 2 version, the flow types using `.flow` and the regular js using `.js`

**Comment by DeMoorJasper** [comment]
That issue is from back when we still did babel transforms on node modules unfortunately. I'll just open one myself

**Comment by chiefGui** [comment]
Let's see how it goes. Thank you, @DeMoorJasper.
