### ISSUE TITLE
Avoid doing unnecessary work

### ISSUE THREAD

**Issue by kevinburke** [parcel-bundler/parcel#18]
Tools such as Make (and the upcoming Go 1.10) get good speed results because they avoid doing work they don't have to do. In particular, Make compares the file mtimes of every dependency to the  mtime of the target. If the target is newer, it realizes it doesn't have to do any work, the output is already up to date.

Go 1.10 takes a similar approach but generates a hash based on the contents of the inputs, and uses this to determine whether it needs to rebuild a target.

I haven't read through the source code but it was difficult to determine whether the tool is doing this from the documentation. The documentation hints at whether it does these things but isn't explicit about them.

If you're not currently doing this, odds are you can extract even more speed gains from the tool in question.

**Comment by devongovett** [comment]
Yep, there is a filesystem cache that does this for future builds, and an in memory one as well for faster rebuilds without restarting the process. Code is here: https://github.com/parcel-bundler/parcel/blob/master/src/FSCache.js
