### ISSUE TITLE
Scoped CSS files with Vue are broken

### ISSUE THREAD

**Issue by bencooper222** [parcel-bundler/parcel#1805]
# 🐛 bug report

I'm using scoped CSS with Vue and the minification doesn't work properly. It does work fine without the scoped CSS. 

## 🎛 Configuration (.babelrc, package.json, cli command)

I only use `babel-preset-vue`.
```js
{
  "presets": ["vue"]
}
```

## 🤔 Expected Behavior
The CSS should have no line breaks and should be one big concatenated blob of text. 
## 😯 Current Behavior
![image](https://user-images.githubusercontent.com/9143563/43293695-7521ea54-90f0-11e8-89df-f83c77715d49.png)
I get something like that. 

## 💁 Possible Solution
I haven't had the time to test this and this is purely a hunch but I suspect that cssnano might not be able to handle attribute selectors that don't have an "=" sign in them. 

## 🔦 Context
I mean... I lost a few bytes of minification. Not the biggest deal but worth reporting.

## 💻 Code Sample

I created a demo [here](https://glitch.com/edit/#!/sleepy-taxi) (click on "show live" and then use inspector to get the CSS file in the `<head>`).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.9.7
| Node             | 10.2.1 (breaks on LTS as well)
| npm/Yarn         | 6.1.0 (breaks on stable as well)
| Operating System | macOS and whatever Glitch uses

**Comment by andyjansson** [comment]
I don't think this has to do with cssnano. If you paste your CSS into the [playground](https://cssnano.co/playground/), you should see that it minifies correctly.
