### ISSUE TITLE
Show version for `parcel -v`

### ISSUE THREAD

**Issue by plantain-00** [parcel-bundler/parcel#181]
**Choose one:** 🙋 feature request?

`parcel -v`

### 🤔 Expected Behavior

Show its version, eg `v1.1.0`

### 😯 Current Behavior

error: unknown option `-v'

### 🔦 Context

like `node -v` `npm -v` `yarn -v`

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  v1.1.0(here is the usage)
| Node             | v8.4.0
| npm/Yarn         | v5.3.0
| Operating System | mac

**Comment by davidnagli** [comment]
`parcel --version` already works. Are you just proposing that we add `-v` as an alias for `--version`?

**Comment by yeskunall** [comment]
Somewhat related to #147. Should we make it so that if `parcel` encounters an unknown option, it instead shows what `--help` would?

**Comment by davidnagli** [comment]
That's a pretty cool idea. It should show the error, and then `--help`.
