### ISSUE TITLE
Parcel + Reason = doesn't hot reload implicitly required files.

### ISSUE THREAD

**Issue by mfoman** [parcel-bundler/parcel#1810]
# 🐛 bug report

ReasonML + Parcel

So in your standard example on your site, where the index.html references index.re
it will recompile if you change index.re.

However, as in your standard example - with the feature of reason to include files by referencing module names - it doesn't work when index.re reference greeting.re implicit by using the module, and then make a change in greeting.re.

It will however, notice that greeting.bs.js has changed and build again.

## 🎛 Configuration (.babelrc, package.json, cli command)

It's your standard setup really.

```js
{
  "name": "whatever",
  "reason": {
    "react-jsx": 2
  },
  "sources": {
    "dir": "src",
    "subdirs": true
  },
  "package-specs": {
    "module": "commonjs",
    "in-source": true
  },
  "suffix": ".bs.js",
  "bs-dependencies": [
    "reason-react"
  ],
  "warnings": {
    "error": "+101"
  },
  "namespace": true,
  "refmt": 3
}
```

## 🤔 Expected Behavior

It should rebuild when changed happends to greeting.re.

## 😯 Current Behavior

It doesn't build.

No errors.

## 💁 Possible Solution

Let me serve index.html but tell them to watch every file in src/*
i tried that, but it refused to connect to localhost.
```parcel serve index.html watch src/*```

**Comment by jthegedus** [comment]
Does anyone have the time to make a reproduction of this and validate that it's still an issue with the latest release of `parcel@next`?
