### ISSUE TITLE
Tree shaking problem with Axios (internal conditional require)

### ISSUE THREAD

**Issue by dcecile** [parcel-bundler/parcel#1811]
# 🐛 bug report

When building this code using `--experimental-scope-hoisting`...

```js
//require("axios/lib/adapters/xhr") /* Uncomment to work around */
const axios = require("axios")

console.log(axios)
```

...running the bundle results in an exception due to an undefined identifier.

Removing the `--experimental-scope-hoisting` flag or uncommenting the workaround `require` makes the problem go away.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
  "private": true,
  "scripts": {
    "build": "yarn clean && parcel build --detailed-report --experimental-scope-hoisting --no-minify axiosTest.js",
    "clean": "rm -rf .cache/ dist/",
    "test": "opn index.html"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "opn-cli": "^3.1.0",
    "parcel-bundler": "^1.9.7"
  }
}
```

Full repo here: https://github.com/dcecile/parcel-tree-shaking-repro

## 🤔 Expected Behavior

I expect that running the above code prints out the Axios function.

```
ƒ wrap() {
    var args = new Array(arguments.length);
    for (var i = 0; i < args.length; i++) {
      args[i] = arguments[i];
    }
    return fn.apply(thisArg, args);
  }
```

## 😯 Current Behavior

Instead, running the code results in an error:

```
axiosTest.js:587 Uncaught ReferenceError: $akUF$init is not defined
    at $A14q$var$getDefaultAdapter (axiosTest.js:587)
    at axiosTest.js:597
    at axiosTest.js:1006
```

Because I turned minify off, I can tell that the compiled bundle throws an exception in this block of Axios code ([`axios/lib/defaults.js`](https://github.com/axios/axios/blob/master/lib/defaults.js)) when trying to `require('./adapters/http')`:

```js
function getDefaultAdapter() {
  var adapter;
  // Only Node.JS has a process variable that is of [[Class]] process
  if (typeof process !== 'undefined' && Object.prototype.toString.call(process) === '[object process]') {
    // For node use HTTP adapter
    adapter = require('./adapters/http');
  } else if (typeof XMLHttpRequest !== 'undefined') {
    // For browsers use XHR adapter
    adapter = require('./adapters/xhr');
  }
  return adapter;
}
```

## 💁 Possible Solution

Seems related to Axios's internal `require` hiding inside of a conditional block?

## 🔦 Context

I was trying out Pacel's tree shaking, and this was the only problem I ran into (after upgrading Parcel). I was able to workaround the issue by importing the `axios/lib/adapters/xhr` explicitly before importing `axios`.

## 💻 Code Sample

https://github.com/dcecile/parcel-tree-shaking-repro

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 10.4.1
| Yarn         | 1.7.0
| Operating System | macOS 10.13.6

**Comment by mischnic** [comment]
Seems similar to #1560

**Comment by devongovett** [comment]
This appears to be fixed in the latest version.
