### ISSUE TITLE
CSS minification wrong when using css variables with border

### ISSUE THREAD

**Issue by lukapopijac** [parcel-bundler/parcel#1812]
# 🐛 bug report

input file, style.css:
```
.a {
  border: 6px solid red;
  border-top: 6px solid var(--mycolor);
}
```

output file (clearly wrong):
```
.a{border-style:solid;border-top:6px solid red;border-top:6px solid var(--mycolor);border-width:6px}
```

No configuration. Build run with:
```
parcel build style.css
```

##  Environment

| Software          | Version(s) |
| -------------- | ---------- |
| Parcel              | 1.9.7
| Node               | 8.6.0
| npm/Yarn        | 6.2.0
| Operating System | macOS v10.12.6

**Comment by Aaike** [comment]
Parcel uses cssnano to minify css , maybe check it's documentation on how to change settings
if you paste your example in their playground (https://cssnano.co/playground) you will get the same output.

**Comment by lukapopijac** [comment]
Then I guess this is a bug in cssnano.

**Comment by andyjansson** [comment]
4.0.5 has been released which should resolve this issue.

**Comment by DeMoorJasper** [comment]
Awesome, Thanks @andyjansson for the quick fix.
