### ISSUE TITLE
How do I improve minification?

### ISSUE THREAD

**Issue by jamesloewen** [parcel-bundler/parcel#1814]
# ❔ Question

Is there a way to improve the minification process used by Parcel?

## 🔦 Context

I was recently listening to a podcast that recommended parcel which, along with numerous blog posts, inspired me to checkout out replacing our webpack build with parcel to reduce the configuration required and to help scale the app by reducing in memory. I was able to get it working fairly quickly (in theory) but came across significant differences in the minified size.

| Bundle | Parcel Build Size | Webpack Build Size |
| ---------------- | ---------- | ---------- |
| first  | 2.45 MB           | 1.73 MB |
| second | 935 KB            | 805 KB |
| third  | 912 KB            | 773 KB |
| fourth | 792 KB            | 706 KB |

The first one being our main bundle (code splitting is a separate issue, I don't really care to address the actual size, just the relative differences), a 40% increase before gzip (And around that after gzip) makes this a blocker.

Note: I am trying to integrate this with django, does anyone have a guide for dropping into a django template easily? With webpack we use `webpack-bundle-tracker` on the frontend combined with `django-webpack-loader` on the backend which has worked reasonably well.

I would like to use parcel for the build process since it is maintainable and might be more accessible to other members of the engineering team at my company, but the current cost for production build size is too big.

## 💻 Code Sample

Prod build commands compared
`parcel build first second third fourth`
`NODE_ENV=production webpack -p`

Our webpack does not override any minification properties aside from using IgnorePlugin for the locale folders from moment.

## 🌍 Your Environment

Relevant build packages

webpack@4.11.1
babel-core@6.26.3
babel-loader@7.1.4
babel-plugin-lodash@3.3.3
babel-plugin-transform-react-remove-prop-types@0.4.13
babel-plugin-webpack-alias@2.1.2
babel-polyfill@6.26.0
babel-preset-env@1.7.0
babel-preset-react@6.24.1
less@3.0.4

Current react/redux versions, momentjs, lodash, react-vis are the largest other packages we bundle third party

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | v6.6.0
| npm/Yarn         | npm 5.3.0
| Operating System | OSX 10.12 (Sierra)

**Comment by devongovett** [comment]
Did you try `--experimental-scope-hoisting` to turn on tree shaking?

**Comment by jamesloewen** [comment]
The main bundle (after removing react-hot-loader which appears like it might have been the issue) is still 200k larger than the original for our main bundle, but that is much more reasonable than the 700k it was before. Thanks @devongovett for the suggestion, I hadn't seen that while reading through everywhere this afternoon

**Comment by jamesloewen** [comment]
Most definitely. I’ll take a look when I get an opportunity. My best guesses are react-vis, moment, formsy-react, or our internal react components but will have to look at it closely to identify which of those it is.

**Comment by kzc** [comment]
Likely dup of #1664. Try PR #1685 with this `.terserrc`:

```json
{
    "compress": {
        "passes": 3
    }
}
```

**Comment by jamesloewen** [comment]
After messing around with a number of configurations and a reinstall, it turns out that
1. @kzc's suggestion didn't seem to work and actually made the largest bundle 100KB larger
2. After a reinstall, the bundle size got back down to webpack's size inexplicably. (and removing the terserrc again)

Sorry I can't provide more information to help you debug further, but thanks for the help and suggestions.

**Comment by devongovett** [comment]
perhaps symlinks?

**Comment by jamesloewen** [comment]
I don't think so. Our codebase doesn't have any symlinks so unless node modules have them on install, that presumably wouldn't have any effect?

**Comment by kzc** [comment]
> @kzc's suggestion didn't seem to work and actually made the largest bundle 100KB larger

Did you test against PR #1685?

> After a reinstall, the bundle size got back down to webpack's size inexplicably. 

Could be a caching issue. Without a reproducible test case we'll never know.

**Comment by jamesloewen** [comment]
I made the change by hand to the local node_modules version and rebuilt since it is a 1 line change. If there is something that depends on between 1.9.7 and current that that PR also depends on I did not test that.

My guess was going to be caching, but as you say, it isn't reproducible so no idea.

**Comment by kzc** [comment]
Try the `--no-cache` option to see if it impacts the size.

**Comment by devongovett** [comment]
#1685 will make the size larger because it disables minification completely. There isn't any sort of whole bundle minification yet in that pr.

**Comment by kzc** [comment]
> #1685 will make the size larger because it disables minification completely. There isn't any sort of whole bundle minification yet in that pr.

Ah, okay. That explains it.

When #1685 is updated I'd suggest that `.terserrc`/`.uglifyrc` only apply to the minification of the final bundle and have a way to disable per-asset minify as it would de-optimize function inlining and `/*@__PURE__*/` annotations. Such pure annotations are used by Babel 7's generated ES5 IIFEs for `class` definitions, as an example.

**Comment by vkvarma** [comment]
> Did you try `--experimental-scope-hoisting` to turn on tree shaking?

awesome it reduced from 7 MB to 911 KB
