### ISSUE TITLE
Parcel resolver build wrong path

### ISSUE THREAD

**Issue by rjungbeck** [parcel-bundler/parcel#1815]
# 🐛 bug report
Cannot resolve dependency './”./index.js”' on yarn run dev

Using sample from

https://medium.com/dailyjs/lean-react-project-with-parcel-a6ffe0fac0d2

OS: MacOS 10.13.6
Node: 10.7.0 (also not working 8.9)
npm: 6.1.0
yarn: 1.7.0

**Comment by DeMoorJasper** [comment]
It works on the medium post. So probably a good idea to create a repo with your project and share it in here.

**Comment by rjungbeck** [comment]
I found the issue. I used cut&paste to copy the code from the medium post to my system. The quotation marks in the post (index.html) are actually different characters. When I replace them with normal quotation marks, parcel works as expected..
