### ISSUE TITLE
Can't import Stylus modules with file globbing

### ISSUE THREAD

**Issue by emyller** [parcel-bundler/parcel#1816]
# 🐛 bug report

Although the Stylus binary compiles just fine files containing glob imports, it breaks when using with Parcel.

## 🎛 Configuration (.babelrc, package.json, cli command)

```
parcel serve frontend/index.html --no-autoinstall --no-hmr
```

## 🤔 Expected Behavior

Parcel should serve a CSS file compiled from Stylus, with or without glob imports.

## 😯 Current Behavior

```
ENOENT: no such file or directory, open '/app/frontend/styles/**/*
```

## 💻 Code Sample

```stylus
// Modules
@require '**/*'
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 10.5.0
| npm/Yarn         | 1.7.0
| Operating System | Docker (Debian)

**Comment by DeMoorJasper** [comment]
Ow we have probably overwritten stylus import resolver with a custom one to support node modules and root importa

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
