### ISSUE TITLE
[LESSAsset] Respect included paths in LESS config

### ISSUE THREAD

**Issue by gaui** [parcel-bundler/parcel#1818]
# 🐛 bug report

When specifying a config for LESS compiler/renderer, the `paths` property in the config is not respected/resolved the way LESS does itself. You can specify the property to lessc with `--include-path=path1:path2:path3` or via the config (.lessrc / .lessrc.js / package.json key "less"): `{ "paths": ["path1", "path2", "path3"] }`

## 🤔 Expected Behavior

When you have included a path in the config that is outside of entry file or `rootDir`, you would want to search/visit those directories - like LESS does.

When running: `lessc --include-path=src/:node_modules/semantic-ui-less/ src/index.less` I get the following:

```
FileError: 'theme.less' wasn't found. Tried - src/theme.less,node_modules/semantic-ui-less/the
me.less,theme.less in src/index.less on line 1, column 1:
1 @import 'theme.less';
```

## 😯 Current Behavior

LESSAsset doesn't respect the `paths` property in the config, so when I run Parcel I get:

```
×  src/index.less: Cannot find module './theme.less' from 'src'
```

## 💁 Possible Solution

The solution to this problem, would be to change the `loadFile` function in `LESSAsset.js` and add the `options` parameter (which is the LESS option/config, containing the LESS config object retrieved earlier).

```
async loadFile(filename, currentDirectory) {
    filename = parseCSSImport(filename);
    let resolved = await resolver.resolve(
    filename,
    path.join(currentDirectory, 'index')
    );
    return {
    contents: await fs.readFile(resolved.path, 'utf8'),
    filename: resolved.path
    };
}
```

## 🔦 Context

Semantic UI has this weird way of merge'ing default themes and variable files with customized, by importing files relatively and depending on paths from the upper context. That's why you have to tell LESS to search for those files in another directories, because they don't exist from relative location where they are imported. See image below.

![](https://i.imgur.com/0tsPikK.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 10.7.0
| npm/Yarn         | 1.7.0
| Operating System | Win10

**Comment by johanberonius** [comment]
I tested to modify the `loadFile`-function locally to try and resolve files relative to all include paths, not just current directory. This seems to work. Not sure if it is enough to create a PR.

In `.lessrc`
```json
{
    "paths": [
        "../node_modules/foo/bar/"
    ]
}
```

In https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/assets/LESSAsset.js#L83-L94
```javascript
async loadFile(filename, currentDirectory) {
  filename = parseCSSImport(filename);

  const directories = [
    currentDirectory,
    ...less.importManager.context.paths.map(
      includePath => path.resolve(options.rootDir, includePath)
    )
  ];
  let resolved, err;
  for (let directory of directories) {
    try {
      resolved = await resolver.resolve(
        filename,
        path.join(directory, 'index')
      );
      break;
    } catch (e) {
      err = e;
    }
  }

  if (!resolved) {
    throw err;
  }

  return {
    contents: await fs.readFile(resolved.path, 'utf8'),
    filename: resolved.path
  };
}
```

Example:
If file at `./src/index.less` contains:
```
@import "baz";
```
It will find the file at `./src/baz.less`, but if that doesn't exist it will also look for `./node_modules/foo/bar/baz.less`

**Comment by johanberonius** [comment]
Submitted a PR with this change #2653
