### ISSUE TITLE
[Question] Proper way to run Parcel during parcel development?

### ISSUE THREAD

**Issue by davidnagli** [parcel-bundler/parcel#182]
What's the correct way to run the Parcel CLI commands during development **for Parcel**?

Currently, I'm just calling `node bin/cli.js [args]`, but this causes some issues since it uses `/bin` as the "current directory", instead of the place where I actually want to run Parcel.

For example, when I run:

```
node ../repo/bin/cli.js src/index.html
```
I get:
```bash
Error: Cannot find module './package.json' from '/Users/[redacted]/projects/Parcel/example/src'
✨  Built in 552ms.
```
However, I do have a package.json located in `/Parcel/example/package.json`

Here's my setup:
![screen shot 2017-12-09 at 8 12 14 pm](https://user-images.githubusercontent.com/6759650/33801095-abed271a-dd1d-11e7-8c3d-627cc964abee.png)

So... what's the best way to run parcel during development?

**Comment by davidnagli** [comment]
I'm thinking maybe there should be a way that I can add Parcel to my `$PATH` or something so that it works just like it does when I install it through npm.

**Comment by chee** [comment]
if you `yarn global remove parcel` then you can cd into your own copy of parcel and `yarn link`, then the `parcel` in your path will be your own parcel

**Comment by chee** [comment]
Also, you can `yarn link` in the directory of your copy of parcel, then in another project you can do `yarn link parcel-bundler` so that locally your copy of parcel is the one used in its npm scripts.

**Comment by davidnagli** [comment]
How do I get it into my PATH in the first place? Should I symlink it into `/usr/local/bin` or do I add something to `.bashrc`?

I tried googling it, but I was pretty confused.

**Comment by brandon93s** [comment]
I use an alias:

![image](https://user-images.githubusercontent.com/4730164/33801469-e245813e-dd29-11e7-8b62-1d86d318df17.png)

This allows me to use the local copy of `parcel` as if it was globally installed. Yarn [recommends](https://yarnpkg.com/en/org/contributing/) the same pattern for development.

**Comment by chee** [comment]
@davidnagli If your globally installed yarn bins are already in your path, then it will work just like that.
If not then you'll need to add your yarn global bin path to your $PATH in your shell init,

something like this:

```sh
echo "PATH=$(yarn global bin):\$PATH" >> .bashrc
```
