### ISSUE TITLE
Unable to import urls from folder

### ISSUE THREAD

**Issue by robinjac** [parcel-bundler/parcel#1822]
Hi,

I've been trying to import a folder of .bin files into parcel by using the following set of syntaxes:

import frames from '../files/frames/*';

import frames from '../files/frames/*.bin';

import * as frames from '../files/frames';

I'm expecting to get an array or object of file urls but none of them seem to work and parcel throws an error compaining that it can't find the urls... I've been reading and it seems that this feature should be in place already. Since this isn't working I've been painstakinly forced to import each file manually by writing the exact url to each file.

Is this a bug or have I been mistaken that this is a feature that parcel already as?

**Comment by DeMoorJasper** [comment]
This should work, you might have made a typo in the path or something, but it should work. I personally use it all the time.

This one should work, the others aren't valid globs
`import frames from '../files/frames/*.bin';`

**Comment by robinjac** [comment]
I'm pretty sure by now that it's not a syntax error. I'm on a windows machine, maybe it has something to do with that?

I get this error:

- Building...events.js:183      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory

Basically... I tried using \\ in the url instead but get the same error. If I type just with one \ i get an empty object but this is just weird because one backslash is not even vaild url.

Any ideas?

**Comment by DeMoorJasper** [comment]
You could try debugging and seeing what happens inside parcel, unfortunately we don't have any more windows contributors in the core team.
So unless any windows user wants to debug this, we can't really fix it

**Comment by valentinbdv** [comment]
+1
I just upgraded from 1.8.1 to 1.9.7 and import files from folder doesn't work anymore.

**Comment by DeMoorJasper** [comment]
Changed the tags around, as long as we don't know what the actual issue is, we can't really fix it. Might be a windows bug as I'm not able to reproduce on OS X.

**Comment by robinjac** [comment]
Updated to parcel version 1.10.1 and this issue seems fixed for me. I can now import using the correct syntax and do not need to import each file manually, awesome!

**Comment by quadrupleslap** [comment]
@robinjac if the issue's resolved, then it can probably be closed.
