### ISSUE TITLE
`parcel serve` hangs when importing multiple sass files

### ISSUE THREAD

**Issue by alappe** [parcel-bundler/parcel#1836]
# 🐛 bug report

I'm having issues with importing the same `.scss` file in multiple vue components. This works in up to three components.

## 🎛 Configuration (.babelrc, package.json, cli command)

See https://github.com/zimmer7/parcel_vue_scss_import_issue for a minimal testcase – `npm run works` serves, `npm run broken` breaks parcel.

## 🤔 Expected Behavior

I should be able to use the same e.g. `_variables.scss` file in all of my components.

## 😯 Current Behavior

`parcel serve` hangs.

## 💁 Possible Solution

No clue :-(

## 💻 Code Sample

https://github.com/zimmer7/parcel_vue_scss_import_issue

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | `1.9.7` |
| Node             | `10.7` |
| npm/Yarn         | `6.1.0` |
| Operating System | macOS |

**Comment by pille72** [comment]
I have the same issue in my setup. Just tried the minimal testcase above with a quick vue/webpack setup: https://github.com/pille72/webpack_vue_scss_import_issue. Looks like that importing sass files is not a problem there, it also uses `node-sass`. If you ran `npm i && npm run build` the generated css file creates the scoped styles just fine. 

Don't know what the internal differences are, but I think it's a common use case to use scoped styles in vue components in sass and import some globals / vars. 

Maybe anyone has some ideas where to look at?

**Comment by DeMoorJasper** [comment]
Currently working on making parcel default to dart-sass, but still support node-sass. (See #1509)

The functions API seems to be slightly broken in dart-sass though.

Will update with a PR shortly.

**Comment by tmchng** [comment]
I think I'm having a similar problem, but without the Vue part. My build freezes when I try to bundle only html+sass, and it runs fine if I comment out some common sass imports.

I discovered that there's an option called `warmWorkers` that is hard-coded to true inside WorkerFarm.js. My build no longer freezes after I set it to `false`. I have not had the time to investigate why though.

**Comment by DeMoorJasper** [comment]
@tmchng could you try with #1847 ?

It's probably not related to warmWorkers, warmWorkers probably just spawns too much async calls to node-sass

**Comment by alappe** [comment]
With #1847 and my linked case above I get two new errors, but it no longer freezes:

```
nd@style /tmp/parcel_vue_scss_import_issue (master) ♥ npm run works                                                                                                                                                                                                                                                                                                 14:07

> testcase@1.0.0 works /private/tmp/parcel_vue_scss_import_issue
> parcel serve --no-cache works.js

Server running at http://localhost:1234
🚨  /private/tmp/parcel_vue_scss_import_issue/u.vue: Cannot read property 'walk' of null
    at HTMLAsset.generate (/private/tmp/parcel_vue_scss_import_issue/node_modules/parcel/src/assets/HTMLAsset.js:184:14)
    at HTMLAsset.process (/private/tmp/parcel_vue_scss_import_issue/node_modules/parcel/src/Asset.js:205:35)
^C
nd@style /tmp/parcel_vue_scss_import_issue (master) ♥ 
```

```
nd@style /tmp/parcel_vue_scss_import_issue (master) ♥ npm run broken                                                                                                                                                                                                                                                                                                14:07

> testcase@1.0.0 broken /private/tmp/parcel_vue_scss_import_issue
> parcel serve --no-cache broken.js

Server running at http://localhost:1234
🚨  /private/tmp/parcel_vue_scss_import_issue/u.vue: Cannot read property 'walk' of null
    at HTMLAsset.generate (/private/tmp/parcel_vue_scss_import_issue/node_modules/parcel/src/assets/HTMLAsset.js:184:14)
    at HTMLAsset.process (/private/tmp/parcel_vue_scss_import_issue/node_modules/parcel/src/Asset.js:205:35)
^C
nd@style /tmp/parcel_vue_scss_import_issue (master) ♥ 
```

**Comment by BBlackwo** [comment]
Came here via #1583. I tried your branch @DeMoorJasper and now I'm getting a whole bunch of sass build errors like: 

```sh
Error: expected "{".
@import "../../some-file.scss";
```

I fix that then I get more errors. Was previously using `node-sass@4.8.3`.

**Comment by DeMoorJasper** [comment]
@BBlackwo Yeah dart-sass is way stricter on sass syntax, not much I can do about it, unless there is an option to disable it.

**Comment by manojchandrashekar** [comment]
The documentation (https://parceljs.org/scss.html) still refers to this as an open issue. Is that still needed?
