### ISSUE TITLE
How to force parcel watch to use the same config as parcel build (minification, tree-shaking)?

### ISSUE THREAD

**Issue by sinedied** [parcel-bundler/parcel#1837]
# ❔ Question

Is there an option or config to make parcel generate the same output as `parcel build` when using `parcel watch` ?

I want minification, tree-shaking etc to also occur in watch mode, is that possible?

## 🔦 Context

I'm using parcel for CodingGame challenges, and as it has size limitation on submitted code files, have all optimizations enabled when I code in watch mode would be very useful.

**Comment by DeMoorJasper** [comment]
It's currently not possible to do this, as watch is mainly for development purposes and this wouldn't make any sense in development as it would slow down builds quite a lot.

You can probably just write a simple js script and use the [API](https://parceljs.org/api.html) to create your own. It should just be as easy as setting a couple config flags

**Comment by sinedied** [comment]
Thanks, that's perfect with the API! 👍 

I'll go with that, but still a `--production` flag could be useful on `watch/serve` commands to have the same code (despite the longer build time), as some issues sometimes arise only with minification, and in some cases it's interesting to be able to quickly make changes to the production build (for debugging, testing...) 😉
