### ISSUE TITLE
Parcel doesn't seem to work with Material UI

### ISSUE THREAD

**Issue by abilash13** [parcel-bundler/parcel#1853]
# 🐛 bug report

I'm trying to set up Material UI with Babel and Parcel by following the same steps described in the sample parcel example given here: https://github.com/mui-org/material-ui/tree/master/examples/parcel

## 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc
```json
{
  "presets": ["env", "react"],
  "plugins": ["transform-class-properties"]
}
```
package.json
```json
{
  "name": "parcel",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@material-ui/core": "latest",
    "babel-plugin-transform-class-properties": "latest",
    "babel-preset-env": "latest",
    "babel-preset-react": "latest",
    "parcel-bundler": "latest",
    "prop-types": "latest",
    "react": "latest",
    "react-dom": "latest"
  },
  "scripts": {
    "start": "parcel src/index.html",
    "build": "parcel build src/index.html --public-url ./"
  }
}
```

## 🤔 Expected Behavior

Material UI should work when using Parcel

## 😯 Current Behavior

Parcel fails to bundle the app with the following error:

```

/Users/abilash/wildwest/react-dump/parcel/node_modules/recompose/wrapDisplayName.js:3:37: Cannot resolve dependency '@babel/runtime/helpers/builtin/interopRequireDefault'
  1 | "use strict";
  2 |
 >3 | var _interopRequireDefault = require("@babel/runtime/helpers/builtin/interopRequireDefault");
    |                                      ^
  4 |
  5 | Object.defineProperty(exports, "__esModule", {
  6 |   value: true

```
## 💁 Possible Solution

I had opened an issue (https://github.com/mui-org/material-ui/issues/12413) in the Material UI repo. And they have suggested that since the error is coming from the recompose codebase, it might be an issue with the bundler itself.

## 💻 Code Sample

https://github.com/mui-org/material-ui/tree/master/examples/parcel

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| parcel-bundler | v1.9.7 |
| node | v10.7.0 |
| yarn | v1.9.2 |
| Operating System | macOS v10.13.6 |
| @material-ui/core | v1.4.3 |
| react and react-dom | v16.4.2 
| babel-preset-env | 1.7.0 |
| babel-preset-react | 6.24.1 |

**Comment by DeMoorJasper** [comment]
Not sure why it's trying to include a babel 7 helper

**Comment by goyney** [comment]
This is not a Parcel issue.

**Comment by abilash13** [comment]
> This is not a Parcel issue.

Just like @goyney mentioned, this was an issue with recompose (https://github.com/acdlite/recompose/issues/723). After their fix, everything seems to be fine now. Thanks!
