### ISSUE TITLE
npm i -D parcel-bunder

### ISSUE THREAD

**Issue by SCWR** [parcel-bundler/parcel#1856]
# ❔ Question

I installed parcel to the project local, then call the parcel command to get the error message.

Parcel : The "parcel" item cannot be recognized as a cmdlet, function, script file, or the name of a runnable program.
Please check the spelling of the name. If you include the path, make sure the path is correct and try again.

 When I installed it globally, is work. why?
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.9.7
| Node             |8.6
| npm/Yarn         | npm
| Operating System | win10

**Comment by KeineLimonade** [comment]
This happens on windows and at is heart is a bug of npm/yarn. The problem is that locally installed packages are not added to PATH.

To solve the issue add a script in your `package.json` and run that with `npm run`.

**Comment by SCWR** [comment]
thank you

**Comment by SCWR** [comment]
thank you
