### ISSUE TITLE
Parcel --detailed-report not showing all assets. How can i output the whole report?

### ISSUE THREAD

**Issue by brendanmorrell** [parcel-bundler/parcel#1857]
# 🙋‍♀️ Feature

## 🔦 Context
I am trying to look at a report of all my asset build times and sizes. However, whenever I use 'parcel build  path/to/my/index.html --detailed-report' my terminal output cuts off a lot of the assets, and instead just lists '+28 more assets' at the bottom. How can I list all of the assets?

I searched through the docs, and the github issues, but I couldn't find an answer anywhere.

Also, is there anyway to get the output in json format? Thanks
<img width="891" alt="screen shot 2018-08-06 at 2 49 12 pm" src="https://user-images.githubusercontent.com/14864397/43744300-48b12b5a-998e-11e8-820d-41e6e8d9181e.png">

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             |v8.11.3
| npm/Yarn         |5.6.0 (npm), 1.1.0(yarn)
| Operating System | mac os high sierra (10.13.6)

**Comment by DeMoorJasper** [comment]
Currently there is no way to get the entire list, but it would make sense to generate some kind of report file if requested either json or simple txt.

Not sure if the terminal is the right place to list all assets though.

I'll flag this as a feature request, if you feel like diggin into this, it's very easy. The report system is very isolated from the core of parcel.

**Comment by devongovett** [comment]
try https://github.com/gregtillbrook/parcel-plugin-bundle-visualiser

**Comment by brendanmorrell** [comment]
Great. Looking into it. Thanks for the help!

**Comment by Jerska** [comment]
I'd personally be happy to have the full list in my terminal.

Would you be OK with a PR adding:
- `--detailed-report-level <level>` where `level: ['short', 'all']` - default `short`

This would leave the door open to introduce:
- `--detailed-report-format <format>` where `format: ['txt', 'json']` - default `txt`
- `--detailed-report-out-file <filename>`

**Comment by mindplay-dk** [comment]
PR was long since merged - the depth option is in the current release. Any reason this can't be closed?
