### ISSUE TITLE
Strip away flow types

### ISSUE THREAD

**Issue by DeMoorJasper** [parcel-bundler/parcel#1863]
# 🐛 bug report

Parcel is currently not able to consume flow typed modules

## 🎛 Configuration (.babelrc, package.json, cli command)

N/A

## 🤔 Expected Behavior

Flow types should be stripped (perhaps configurable through babel)

## 😯 Current Behavior

Flow types cause errors

## 💁 Possible Solution

- locally link a copy of the module that contains flow types
- Ask the maintainer to publish the module using `.flow` and `.js` files. `.flow` being the typed one and `.js` being processed by babel to strip away the typings
- Make parcel automagically detect and strip away flow types (in node modules only)

## 🔦 Context

Issue #1799

## 💻 Code Sample

```Javascript
import Typography from 'typography';
```

cc @chiefGui

**Comment by DeMoorJasper** [comment]
Yeah I think that'll be the best approach @chiefGui , currently doing some research on flow to make sure the annotation on the first line is really required. So I don't make assumptions of a framework I've never used

**Comment by chiefGui** [comment]
[According to their website](https://flow.org/en/docs/types/modules/):

> Don’t forget to mention @flow on top of file, otherwise flow won’t report errors.

Also from the short period of time I've worked with Flow, I also do remember that I was required to annotate my files with `@flow`.

Finally, seems like in the Typography's case, [they're also consistently using `@flow`](https://github.com/KyleAMathews/typography.js/blob/master/packages/typography/src/index.js).

This is just a support to help you on your research.
