### ISSUE TITLE
Incorrect relative path for stylesheet in index.html after building

### ISSUE THREAD

**Issue by morgannewman** [parcel-bundler/parcel#1865]
# 🐛 Bug Report
I am trying to setup a simple project with Parcel and I'm running into what seems to be a silly issue. 

After running `parcel build ./Public/index.html` (with `index.html` having a CSS link pointing to `./css/style.css`), the CSS link in my outputted HTML file is preceded with `/`, as in `/style.HASH.css` which causes Chrome to kick the following error: 

> Refused to apply style from 'http://127.0.0.1:8080/style.c6b066be.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled

This problem is easily fixed by manually changing the path to begin with either `./` or no slash at all.

Is this issue reproducible by anyone else? My package is up to date (I just installed it today), and I am not trying to use any additional plugins at this time.

**Comment by DeMoorJasper** [comment]
This is not a bug and has been reported many times, please let us know how we can improve the docs to prevent this kind of issue reporting.

you simply add `--public-url ./` to the command

**Comment by morgannewman** [comment]
Thanks a lot for the clarification! 

I don't fully understand the reasoning behind why this is the default behavior since nesting CSS in a subfolder is very common, which is why I thought this might be a bug, but I'm sure there is a good reason for this behavior. Perhaps explaining in the docs more about why this is the default would be helpful for other noobs like me. 

Thanks again!

**Comment by justingolden21** [comment]
> You simply add `--public-url ./` to the command.
> 
> This is not a bug and has been reported many times, please let us know how we can improve the docs to prevent this kind of issues.

I've gotta say I have absolutely no idea why this is not the default behavior. I admittedly don't know a lot about parcel, or bundlers in general, and I'm sure the devs do. Parcel is marketed as a very simple, no config bundler. But yet for some reason my entire application breaks when building unless I put this line in. Why is this not the default? What advantage is gained from not having this? Why is this so hidden? There are millions of people who put their css in folders... I have no clue whatsoever why all of the links would break after parcel builds the project unless you add this bit of code. Sorry if I sound upset; I have been searching for almost an hour for this, and can't wrap my head around why this isn't the default and is hidden off in the corner.
