### ISSUE TITLE
Dynamic Imports and Typescript fails with "Cannot find module 'X'"

### ISSUE THREAD

**Issue by muhlba91** [parcel-bundler/parcel#1867]
# 🐛 bug report

Usage of dynamic import `async () => await import('file')` (in Typescript) for Code Splitting doesn't work when importing the same required file twice.

## 🎛 Configuration (.babelrc, package.json, cli command)

See code example.
Calling `yarn start:dev` works perfectly well but after `yarn build` and delivering the contents of `build/dist` I get the error mentioned in "Current Behavior".

## 🤔 Expected Behavior

Code Splitting using dynamic imports should work even if the same file is imported dynamically twice. All required/transitive Typescript files should be transpiled and delivered correctly.

## 😯 Current Behavior

Currently, it only works when starting the application via parcel's web server. However, after `parcel build` and delivering the application via a web server, the code breaks as it doesn't transpile Typescript files or doesn't link more than once dynamically imported files correctly in the generated output.
I get the following error message:
```
Uncaught Error: Cannot find module '8rfi'
    at u (beneficial-owner.ts:1)
    at u (create.c029ff4b.js:1)
    at u (navigation.2f27ea42.js:1)
    at u (VM1208 company-form.d165ffba.js:1)
    at p (VM1208 company-form.d165ffba.js:1)
    at Object.parcelRequire.fTSU.lodash (VM1208 company-form.d165ffba.js:2)
    at u (VM1208 company-form.d165ffba.js:1)
    at parcelRequire.fTSU.lodash (VM1208 company-form.d165ffba.js:1)
    at VM1208 company-form.d165ffba.js:1
u @ beneficial-owner.ts:1
u @ create.c029ff4b.js:1
u @ navigation.2f27ea42.js:1
u @ VM1208 company-form.d165ffba.js:1
p @ VM1208 company-form.d165ffba.js:1
parcelRequire.fTSU.lodash @ VM1208 company-form.d165ffba.js:2
u @ VM1208 company-form.d165ffba.js:1
parcelRequire.fTSU.lodash @ VM1208 company-form.d165ffba.js:1
(anonymous) @ VM1208 company-form.d165ffba.js:1
```
Please note the last file extension `.ts` which should never be delivered to the client!

## 💁 Possible Solution

I assume it's an issue related to dynamic imports and transpiling Typescript files because when using no dynamic imports all works perfectly well.

## 🔦 Context

As seen in the code sample, I define common classes in Typescript files and want to reuse them in many components. Furthermore, code splitting keeps the transferred modules small and only downloaded if needed -> therefore, the combination of both should work.

## 💻 Code Sample

https://github.com/muhlba91/parcel-bundler-dynamic-imports-typescript-error

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7 |
| Node             | 10.8 |
| npm/Yarn         | yarn v1.9.4 |
| Operating System | MacOS |

**Comment by 9oelM** [comment]
perhaps look at [#112](https://github.com/parcel-bundler/parcel/issues/112) for any possible solutions..? I see that there are several who got into similar problems.
