### ISSUE TITLE
Unable to import CSS file from node_modules when target is electron

### ISSUE THREAD

**Issue by drakang4** [parcel-bundler/parcel#1868]
# 🐛 bug report

I cannot import CSS from node_modules when the target of parcel bundler is electron.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
// tsconfig.json
{
  "compilerOptions": {
    "strict": true,
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "lib": [
      "dom",
      "es2015",
      "es2016",
      "es2017",
    ],
    "sourceMap": true,
    "noImplicitReturns": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "jsx": "react",
    "pretty": true,
    "rootDir": ".",
    "outDir": "build"
  },
  "exclude": [
    "node_modules"
  ]
}
```

```bash
// run command
parcel app/index.html --target electron --out-dir build/app --public-url .
```

## 🤔 Expected Behavior

Apply styles without any error.

## 😯 Current Behavior
![image](https://user-images.githubusercontent.com/11497500/43841976-4be109c6-9b5f-11e8-8b8e-a0673758e3f2.png)

Cannot import CSS

## 💁 Possible Solution

I don't have any idea 😥

## 🔦 Context

I don't have any problem when the target is browser
I found that importing CSS file as relative path is working, but it doesn't work when I import CSS from node_modules as absolute path when the target is electron. `parcel build` has the same issue not only `serve`.

## 💻 Code Sample

I created a sample repository that makes the same error of this issue. https://github.com/drakang4/parcel-electron-css-bug 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7 |
| Node             | 8.11.3 |
| npm/Yarn         | 5.4.2 / 1.9.2 |
| Operating System | Windows 10 |

**Comment by cousinbenson** [comment]
hi, I've found a quick fix is to import the css like this:

`import '../../node_modules/normalize/normalize.css'`

I don't like writing it this way though, and would appreciate a fix.

Thanks!

**Comment by cuberoot** [comment]
I hit this while trying to bring in a library that contains `.css` files. I had to switch back to `target: 'browser'` because I don't have control over the source.

In order to access the `electron` package, I did this:

    const { ipcRenderer } = window.require('electron')
