### ISSUE TITLE
Customize sourceMappingURL

### ISSUE THREAD

**Issue by hirasso** [parcel-bundler/parcel#1869]
First of all, what a great project!! Thanks to everyone working on it.

# 🙋 feature request

It would be nice if we could customize the `sourceMappingURL`, or make it relative to the script's location. At the moment it's `/index.map` and isn't found by the browser. If I change the url manually to `./index.map`, it works fine.

## 🤔 Expected Behavior

the sourceMappingURL should be relative to the script

## 😯 Current Behavior

at the moment, the sourceMappingURL is absolute

## 💁 Possible Solution

That's where you pros come in ;)

**Comment by DeMoorJasper** [comment]
I don't think it'll be possible to make it configurable.

But it should already be able to become relative using `--public-url ./`?

**Comment by hirasso** [comment]
@DeMoorJasper great, that did the trick! 🎉
