### ISSUE TITLE
Possible to use environment variables for --public-url

### ISSUE THREAD

**Issue by staghouse** [parcel-bundler/parcel#1873]
# ❔ Question

I might have just not found the right NPM config yet but when I try to use environment variables to plug in selective urls for the `--public-url` flag it is always parsed as a string.

Is there any way currently to do this?

## 💻 Code Sample

`"build": "parcel build index.html --public-url ENV_VAR"`
or
`"build": "parcel build index.html --public-url cross-var echo ENV_VAR"`

**Comment by ericlakatos** [comment]
The problem I am running to is that when passing environment variables I am met with an error like so:

input:
```parcel build index.html --public-url ENV_VAR```

output:
```error: option `--public-url <url>' argument missing```

Is there something, not Parcel related, that I am doing wrong by chance?

**Comment by DeMoorJasper** [comment]
Perhaps it can't find the environment variable?
If the variable resolves to null that's probably why

**Comment by peanutbother** [comment]
I would test this by chaining `echo` to see if the `ENV_VAR` is empty or contains the string you expect

**Comment by avendiart** [comment]
@ericlakatos It should be `parcel build index.html --public-url $ENV_VAR`, note the dollar sign.

**Comment by mischnic** [comment]
> It should be parcel build index.html --public-url $ENV_VAR, note the dollar sign.
