### ISSUE TITLE
Injecting a bundle produced by parcel into a webpage via browser extension disables parcel HMR for the entire page

### ISSUE THREAD

**Issue by floating** [parcel-bundler/parcel#1874]
# ❔ Question

Should injecting a bundle produced by parcel into a webpage via browser extension disable parcel HMR for the entire page? I'm seeing this behavior after switching to parcel for an extension I work on and wanted to get more information about if this was intended before digging into the issue. Ideally I'd like to be able to bundle my injected script with parcel and be able to use the extension during development of other apps without it disabling HMR. If the cause of this behavior is unclear I will create a reproducible example to post here.
 
## 🔦 Context

After bundling a script with parcel it is then injected into the webpage by an extension. When that extension is enabled HMR no longer works. Switching to webpack to bundle the script solves the problem unless any bundled modules also used parcel. Testing HMR with an older version of parcel that I had installed globally (1.6.2) still works with the injected script but newer versions do not. I understand this is an edge case but wanted to collect some more information about it before switching away from parcel for my extension. Thanks very much!

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.9.7
| Node             | 8.9.4
| npm/Yarn         | 6.2.0
| Operating System | macOS

**Comment by DeMoorJasper** [comment]
If you created a production bundle for the extension it should not contain any HMR logic and not conflict with any other parcel HMR. If it is a dev build, than it would make sense

**Comment by DeMoorJasper** [comment]
Might be a bug though, if you did create a production build

**Comment by DeMoorJasper** [comment]
It's probably because `parcelRequire` lives in the global/window scope and gets defined twice (from a different source).

Not sure how to resolve this, not sure if that's the case either, haven't debugged into much detail.

Perhaps we should figure out a way to get rid of parcelRequire in production builds

**Comment by floating** [comment]
Thanks @DeMoorJasper, it seems `--experimental-scope-hoisting` does solve the issue for the simple demo I created but in my actual extension I'm running into an error `Uncaught ReferenceError: $WOY7$export$CookieJar is not defined` that makes it unusable.

**Comment by DeMoorJasper** [comment]
Yeah that's why it's experimental. Feel free to try look through issues and create a new one scope hoisting related

**Comment by floating** [comment]
Ok, no worries. I will likely migrate away from parcel for this particular project but I will keep an eye on this issue. Thanks for your help, keep up the great work on parcel!

**Comment by DeMoorJasper** [comment]
To temporarily solve this you can run a postProcess that removes the parcelRequire at the start of the file. Forgot to mention this earlier :)
