### ISSUE TITLE
Bug in Resolver.resolveFilename?

### ISSUE THREAD

**Issue by Znarkus** [parcel-bundler/parcel#1875]
I'm trying to hunt down why I cannot use
- `@import "../../node_modules/highlightjs/styles/github.css";`
or
- `@import "~highlightjs/styles/github.css";`
in my project.

I stumbled upon this that looks like a bug.

# 🐛 bug report

Method Resolver.resolveFilename() seems to handle absolute paths incorrectly.
```
return path.resolve(this.options.rootDir, filename.slice(1));
```
This resolves `/me/project` and `/me/project/filename.css` to `/me/project/me/project/filename.css`.

## 🎛 Configuration (.babelrc, package.json, cli command)

- `npx -n '--inspect-brk' parcel build theme/resource/main.scss`
- Nothing else

## 🤔 Expected Behavior
Resolve with an absolute path should probably just return the path. Or is this an security issue?

## 😯 Current Behavior
It resolves (what looks like) incorrectly.

## 💁 Possible Solution

`return filename`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             |8.11.3
| npm/Yarn         |npm 5.6.0
| Operating System |macOS

**Comment by DeMoorJasper** [comment]
Could you try out to create a PR out of this and make sure it still passes all existing tests?

**Comment by Znarkus** [comment]
Changed it and ran the tests; 5 failing.
The code is dependent on that `resolveFilename` resolves an absolute path like a relative path from `this.options.rootDir`. 

Changing this behaviour breaks the test and probably more.

I'm trying to use a relative path or a node_modules-relative path in my sass file. Don't know how to do this when this method works like this.

---

main.scss:
```
@import "../../node_modules/highlightjs/styles/github.css";
```

```
$ parcel build theme/resource/main.scss
🚨 /Users/markushedlund/www/markushedlund.com/theme/resource/main.scss: Cannot resolve dependency '/Users/markushedlund/www/markushedlund.com/theme/resource/Users/markushedlund/www/markushedlund.com/node_modules/highlightjs/styles/github.css' at '/Users/markushedlund/www/markushedlund.com/theme/resource/Users/markushedlund/www/markushedlund.com/node_modules/highlightjs/styles/github.css'
    at Resolver.resolve (/Users/markushedlund/www/markushedlund.com/node_modules/parcel/src/Resolver.js:69:17)
    at <anonymous>
```

---

main.scss:
```
@import "~highlightjs/styles/github.css";
```

```
$ parcel build theme/resource/main.scss
🚨  /Users/markushedlund/www/markushedlund.com/theme/resource/main.scss: Cannot resolve dependency '/Users/markushedlund/www/markushedlund.com/theme/resource/Users/markushedlund/www/markushedlund.com/node_modules/highlightjs/styles/github.css' at '/Users/markushedlund/www/markushedlund.com/theme/resource/Users/markushedlund/www/markushedlund.com/node_modules/highlightjs/styles/github.css'
    at Resolver.resolve (/Users/markushedlund/www/markushedlund.com/node_modules/parcel/src/Resolver.js:69:17)
    at <anonymous>
```

**Comment by jisuo** [comment]
I'm having the same issue, @Znarkus have you found any solution or workaround?

**Comment by jisuo** [comment]
I added some console log in `Resolver.resolveFilename` just to see what was happening and it fails after getting `filename = _css_loader` and `dir = /Users/jisuo/Code/my-project/src/sass`

`path.normalize(filename)` returns `_css_loader `.

**Comment by Znarkus** [comment]
> It repeats /Users/jisuo/Code/my-project/ for some reason

Please see the original report above (the "bug report" section) for an explanation why.

Sadly I haven't solved the problem, but moved on to use node-sass directly instead of parcel for my project, as I could not find a way without breaking parcel.

**Comment by jisuo** [comment]
Tried `1.10.3` to see if it was fixed. Still does not work (as I said works in `1.8.1`) but error is slightly different now:

```
/Users/jisuo/Code/myapp/src/sass/app.scss:2:1: Cannot resolve dependency '/Users/jisuo/Code/myapp/node_modules/animate.css/animate.css' at '/Users/jisuo/Code/myapp/node_modules/animate.css/animate.css'
    at Resolver.resolve (/Users/jisuo/Code/myapp/node_modules/parcel-bundler/src/Resolver.js:70:17)
    at <anonymous>
```

**Comment by rambo-panda** [comment]
> Ok, thanks, it worked in version `1.8.1` that I used earlier so I'll probably just revert back until this is fixed.
> 
> edit:
> 
> this works in version `1.8.1`: `@import '../../node_modules/animate.css/animate.css';`
> 
> does not work in `1.9.7`

@jisuo 

I have a question similar to yours about `node-sass` `importer`  https://github.com/parcel-bundler/parcel/issues/2199

**Comment by devongovett** [comment]
Absolute paths are resolved relative to the project root in Parcel rather than your machine. Otherwise builds would not be reproducible across machines.

**Comment by jisuo** [comment]
@devongovett The error message outputs `Cannot resolve dependency '/Users/jisuo/Code/myapp/node_modules/animate.css/animate.css'` which is actually the correct path on disk. How should you change the import path?

**Comment by mzedeler** [comment]
@devongovett - I get the same duplicated paths as described above. I can't see why the slice in this line makes any sense:

https://github.com/parcel-bundler/parcel/blame/master/packages/core/parcel-bundler/src/Resolver.js#L126

If you already have a root path like `/home/user/me/my-awesome-project` and the absolute asset path `/home/user/me/my-awesome-project/node_modules/some-module/lib/index.js`, why would you ever try to resolve this path:

`/home/user/me/my-awesome-project/home/user/me/my-awesome-project/node_modules/some-module/lib/index.js` ?

I think it is necessary that parcel discovers if it is trying to do this kind of cyclical imports. I tried adding this to the beginning of `resolveFilename` and it didn't break any tests:

        if (filename.startsWith(dir)) {
          return filename
        }

Is this the right approach? In that case I don't mind providing a PR for it.

**Comment by stepbeekio** [comment]
If anyone is struggling with this, I managed to sort it by following the advice in this issue https://github.com/parcel-bundler/parcel/issues/39

I added a `.sassrc.js` file to the root of the dir with:

```js
const path = require('path')

const CWD = process.cwd()

module.exports = {
    "includePaths": [
        path.resolve(CWD, 'node_modules'),
        path.resolve(CWD, 'styles') // This is where I'm putting styles, you could put src here etc
    ]
}
```
It's working fine with `animate.css` and `tippy.js` so far. I'm on parcel 1.12.4

**Comment by devongovett** [comment]
Closing since this was a bug in Parcel v1.
