### ISSUE TITLE
Configure LESS options and use plugins

### ISSUE THREAD

**Issue by HannanAkbar** [parcel-bundler/parcel#1879]
# ❔ Question

I am trying to set up transform to configure LESS options and use plugins such as 'less-plugin-autoprefix' and 'less-plugin-glob'.

Found no reference in the docs and no luck so far.

**Comment by DeMoorJasper** [comment]
https://parceljs.org/transforms.html#postcss

You just install the plugins and define them in the config file

**Comment by KeineLimonade** [comment]
You can also create a `less` key in your `package.json` and store your config there.

**Comment by HannanAkbar** [comment]
I'm trying to set these options in the config. For example:

```
{
    plugins: [require('less-plugin-glob')]
}
```

**Comment by HannanAkbar** [comment]
I also couldn't get `less-plugin-autoprefix` and 'less-plugin-npm-import' to work.

I really love parcel for its simplicity but there's a lack of good documentation.

**Comment by DeMoorJasper** [comment]
Your `.lessrc.js` file should look something like this:

```Javascript
module.exports = {
    plugins: [
      require('less-plugin-glob'),
      require('less-plugin-autoprefixer'),
      require('less-plugin-npm-import') // This one should be obsolete, as parcel handles this already
    ]
}
```

**Comment by DeMoorJasper** [comment]
I agree there should be better docs.

The docs are open-source and if everyone who comes across an issue with parcel (doc related) and finds the answer would contribute it back to the docs, it would help out a lot. https://github.com/parcel-bundler/website

**Comment by HannanAkbar** [comment]
I replaced the code but It's throwing the same error.

`.lessrc.js`
```
module.exports = {
    plugins: [require('less-plugin-glob')]
}
```

**Comment by HannanAkbar** [comment]
There's no Transform for LESS. Would it work as expected?
https://github.com/parcel-bundler/parcel/tree/master/src/transforms

**Comment by DeMoorJasper** [comment]
@HannanAkbar All less transforms are performed inside LESSAsset.js 
https://github.com/parcel-bundler/parcel/blob/master/src/assets/LESSAsset.js

Only some shared and large transforms are put into their own folder, the structure might change once parcel becomes a monorepo, but for now it depends on file size.

**Comment by HannanAkbar** [comment]
This should be labelled as a bug.

To reproduce:

`.lessrc.js`
```
module.exports = {
    plugins: [require('less-plugin-glob')]
}
```

`main.less`
```
@import "base/**";
```

Throws an error
> Error: ENOENT: no such file or directory

**Comment by DeMoorJasper** [comment]
Not untill we know it is a bug, according to the code in the plugin, this should work, or at least do something

**Comment by provegard** [comment]
The glob bug appears to be in the Less asset code (`LESSAsset.js`):

```js
    async loadFile(filename, currentDirectory) {
      filename = parseCSSImport(filename);
      let resolved = await resolver.resolve(
        filename,
        path.join(currentDirectory, 'index')
      );
      return {
        contents: await fs.readFile(resolved.path, 'utf8'),
        filename: resolved.path
      };
    }
```

Here, `resolved.path` will be the globbed path, and `fs.readFile` won't understand that.
