### ISSUE TITLE
Publish Tool Versions on Benchmarks

### ISSUE THREAD

**Issue by kopepasah** [parcel-bundler/parcel#1880]
While the benchmarks look very promising, it is impossible to know if they are useful without publishing which versions of the tools you were benchmarking against.

Please at least publish the versions of the tool (browserify/webpack) comparisons.

**Comment by DeMoorJasper** [comment]
The benchmarks are pretty old.

Pretty sure these are the major versions for the benchmarks:
webpack 3.x
browserify 13.x

There is no real way to properly benchmark the differences between webpack, parcel and browserify at the moment unless you would have a bunch of enterprise size projects (that are compatible with webpack, parcel and browserify) laying around to run like a couple times with each bundler and take the average. Besides these projects should be public so people can actually test it themselves...

**Comment by kopepasah** [comment]
Thanks for the feedback @DeMoorJasper.
