### ISSUE TITLE
Is it possible to generate  2 bundles - one which supports old browsers, and one which supports modern browsers, at once? 

### ISSUE THREAD

**Issue by vedantroy** [parcel-bundler/parcel#1882]
# ❔ Question

Is it possible to generate 2 bundles - one which is compatible with old browsers (i.e - es6 is compiled to es5) and one which works with new browsers (no or less transpilation) at once? 
## 🔦 Context

Polyfills like Regenerator Runtime add a no-trivial amount to the size of my application and do incur some performance cost which I would like avoid if the browser already has a native solution.

**Comment by DeMoorJasper** [comment]
Not at the moment, will probably be possible in the future
