### ISSUE TITLE
Index.html does not update it's bundle reference when contentHash is true and is watching files.

### ISSUE THREAD

**Issue by raphaklaus** [parcel-bundler/parcel#1886]
# 🐛 bug report

Index.html does not update it's bundle reference when `contentHash` is true and Parcel is watching files.

## 🎛 Configuration (.babelrc, package.json, cli command)

Command line to start: `rm -drf dist && ./node_modules/.bin/parcel src/index.html`

## 🤔 Expected Behavior

Always re-create index.html accordingly with the newest bundles.

## 😯 Current Behavior

After making some changes in the code, Parcel will automatically build a new bundle for, let's say, your JavaScript code. It will be available in your dist folder. But index.html have a reference to the first bundle.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | > 9
| npm/Yarn         |
| Operating System | Linux

**Comment by bontibon** [comment]
I have also noticed this. My workaround is to use the bundler API and set the `contentHash` property to true only when `process.env.NODE_ENV === 'production'` and `watch` true when `process.env.NODE_ENV !== 'production'`.
