### ISSUE TITLE
Importing gl-matrix with experimental scope hoisting results in it excluded 

### ISSUE THREAD

**Issue by kirbysayshi** [parcel-bundler/parcel#1888]
# 🐛 bug report

When importing any module/export from gl-matrix, using typescript, and `--experimental-scope-hoisting`, the resulting bundle is devoid of all gl-matrix code. The bundle for the gist linked below looks like this, for example:

```ts
// index.ts
import { mat4 } from 'gl-matrix';
console.log('mat4?', mat4);
```

```js
(function () {
// ASSET: index.ts
var $QCb$exports = {};
var $QCb$export$__esModule = true;
$QCb$exports.__esModule = $QCb$export$__esModule;
var $QCb$var$gl_matrix_1 = {};
console.log('mat4?', $QCb$var$gl_matrix_1.mat4);

if (typeof exports === "object" && typeof module !== "undefined") {
  // CommonJS
  module.exports = $QCb$exports;
} else if (typeof define === "function" && define.amd) {
  // RequireJS
  define(function () {
    return $QCb$exports;
  });
}
})();
```
I've tried as many variations of `import` and paths that I can think of, but still cannot get gl-matrix included in the final bundle.

Perhaps I'm doing something wrong!

## 🎛 Configuration (.babelrc, package.json, cli command)

Completely unconfigured, aside from experimental scope hoisting and `--no-minify` for the sake of readability when debugging.

https://gist.github.com/kirbysayshi/f1c38d272cb3d5832342f8fc5c689fb6

```
npm install
npm run build
cd dist/ && serve # then visit in a browser. You'll see `undefined` in the console!
```
## 🤔 Expected Behavior

mat4 / gl-matrix is included in the bundle

## 😯 Current Behavior

Nothing from gl-matrix is included in the bundle, aside from the name assigned to the import statement.

All code that depends on gl-matrix fails, since it's not there.

## 💁 Possible Solution

I haven't been able to find a workaround, and have tried:

- importing named exports, default exports, individual files (path to js), using `require`.
- using TypeScript 3 and TypeScript 2
- Using parcel 1.9.5/6 in case it was a regression from https://github.com/parcel-bundler/parcel/pull/1781

The only thing that works so far is to not use TypeScript! Included in the gist is an index.js file to demonstrate that.

I've also tried using a simple `require` statement, which also fails to include gl-matrix:

```
const glMatrix = require('gl-matrix');
console.log('mat4?', mat4);
```

Which results in: 
```
(function () {
console.log('mat4?', mat4); // ASSET: index.ts
})();
```

Which, by the way, is amazingly small! Once this issue gets fixed a zero-conf tree shaking + scope hoisting is going to be a killer feature!

## 🔦 Context

Just trying to use TypeScript plus the scope hoisting to cut down on bundle size! In this case it's for the JS13K competition that starts soon.

## 💻 Code Sample

https://gist.github.com/kirbysayshi/f1c38d272cb3d5832342f8fc5c689fb6

See above for steps to reproduce!

**Comment by mischnic** [comment]
This seems to have gotten fixed.
@kirbysayshi Does it work now?

**Comment by kirbysayshi** [comment]
Sorry that I never came back to this. Yes, it has been fixed! Thank you for all your hard work!
