### ISSUE TITLE
how to add watcher to a path

### ISSUE THREAD

**Issue by wocanbe** [parcel-bundler/parcel#1889]
I write a plugin([parcel-plugin-vue-auto-router](https://github.com/wocanbe/parcel-plugin-vue-auto-router)),I read the code of 'Bundler.js' and 'Asset.js',But i still don't know how to add watcher to a path.

Is the  bundler support watcher of path?

If yes,How to use?

**Comment by wocanbe** [comment]
I has write the watcher with chokidar,But must write to a file to adapt the bundler of parcel,My quest is how to die the files compiled by '.autorouter'

**Comment by wocanbe** [comment]
I has write the watcher with chokidar,But must write to a file to adapt the bundler of parcel,My quest is how to drop the files compiled by '.autorouter'

**Comment by DeMoorJasper** [comment]
I'm not sure I completely understand why you'd have to address the watcher directly, but I can probably help you out.

In the asset you can do something like this:
`this.addDependency(dep, {includedInParent: true});`

This would add the file as a dependency, watching it using whatever watcher parcel uses (this can and will probably change) and would also reparse the asset if that changes, as it's a child asset.

**Comment by wocanbe** [comment]
I'm doing an auto-generated routing that automatically generates a description of the route based on the Vue file structure in the directory to scan; when the file is added (or deleted), I need to regenerate the code, which is not included in the original code(bundler tree).

Simple point,I want to add a child asset which is not in parent asset when add a file in Specified directory, And delete it when delete this file, This work is automatic,Not need to write any code。

This is [my demo](https://github.com/wocanbe/autorouter-project),See the file 'src/router/view.autorouter',My plug-in will make a 'src/router/view.js' when run,When add(or delete) file in 'src/views/',Will update 'src/router/view.js', Through HRM,Auto update the router.

I want to drop the file 'src/router/view.js',But still has HRM when add files

**Comment by wocanbe** [comment]
The file 'src/router/view.autorouter' has many child assets,but not write in code, through scan another directly generated.

**Comment by wocanbe** [comment]
When I use webpack,through the next code,
```
loader.addContextDependency(path.resolve(dirPath))
```
Can add watcher to a path,Auto update code when add(or delete) files

**Comment by mischnic** [comment]
If I understood your post correctly, you need to call `this.addDependency("/path/to/file/to/watch", {includedInParent: true});` for every file in your folder structure you want to watch
