### ISSUE TITLE
Is there a similar webpack require.context function?

### ISSUE THREAD

**Issue by cgxqd123** [parcel-bundler/parcel#1890]
No webpack's require.context function is very bad

**Comment by DeMoorJasper** [comment]
Parcel tries to promote standardized and cross-tooling syntax, therefore it doesn't support any webpack specific things.

Besides that, the webpack specific things are just weird and not that usefull in most cases. (as there usually is a standardized similar approach that looks and works better...)

I've personally never used require.context, but it seems to me like a webpackified glob require.

See this for docs: https://github.com/isaacs/node-glob#glob-primer

Parcel's resolver natively supports globs...

**Comment by myWsq** [comment]
`import images from './*.jpg'`
