### ISSUE TITLE
How to reference an mp3 (or other static file) ?

### ISSUE THREAD

**Issue by RichardJECooke** [parcel-bundler/parcel#1891]
# ❔ Question

Hi, your Assets doc (https://parceljs.org/assets.html) says I should be able to include a static file like this:
```
import songUrl from './song.mp3';
let song = new Audio(songUrl);
```
Running Parcel builds without error and I can now see in my `dist` folder that the file is there and is called `song.66fc540b.mp3`.

But when opening the HTML page in Chrome I get:
```
src.3679338c.js:39 Uncaught Error: Cannot find module 'song.mp3'
    at newRequire (src.3679338c.js:39)
    at newRequire (src.3679338c.js:23)
    at localRequire (src.3679338c.js:54)
    at Object.eval (eval at hmrApply (jquery.js:8311), <anonymous>:5:13)
    at newRequire (src.3679338c.js:48)
    at hmrAccept (jquery.js:8342)
    at jquery.js:8228
    at Array.forEach (<anonymous>)
    at WebSocket.ws.onmessage (jquery.js:8226)
```

:(  How do I fix this please?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             |9.3.0
| npm/Yarn         |npm
| Operating System |Ubuntu (Windows subsystem for Linux)

**Comment by DeMoorJasper** [comment]
It should work as you used it, appears to be a bug with it not being created inside the Javascript bundle.

I'll flag this as a bug, could you provide us with more context, maybe a minimal reproducable example (with another publicly available mp3 or any other kind of static file)

**Comment by RichardJECooke** [comment]
Ah, in making a minimal example for you I found the problem, it's not the .js, it's this line in the .html:
`<audio id="song" controls src="song.mp3"></audio>`.

If I do it dynamically everything works fine: `jq(".song").append(`<audio id="song" controls src="` + songUrl + `"></audio>`);`

This is not a bug. So sorry to waste your time, thanks for your help.
