### ISSUE TITLE
HMR issue with event emitter

### ISSUE THREAD

**Issue by ctsin** [parcel-bundler/parcel#1893]
## 🔦 Context
I'm doing a vanillaJS demo of todo list. While making a change in Class method, the Console show me it has been reloaded. But it DO NOT reflect my change. I have to manully refresh the browser to see the new code working. What's should I do, or how to config Parcel to live reload the browser? Thanks.

## 💻 Code Sample
```json
// package.json
"scripts": {
  "dev": "parcel ./src/index.html -p 5500"
 }
```

```typescript
// index.ts
import { TodosApp } from "./todos-app";
window.onload = () => { new TodosApp(); }

// todos-app.ts
export class TodosApp {
  constructor() {
    this.onAddTodo();
  }

  onAddTodo() {
    document.body.innerHTML = "A";
    
    // **********************
    // change the content to "B", the browser still show "A", need to manual refresh
    // document.body.innerHTML = "B";
  }
}
```
NO ERROR in console.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 10.8.0
| npm/Yarn         | 6.0.1
| Operating System | Windows 7 x64

**Comment by Hammster** [comment]
A more suiting title: HMR not applied to EventListener in TypeScript class.

**Comment by ctsin** [comment]
Sorry for bad code example, and update it. I wanna say that when I change the content from "A" to "B", the page still show "A".

**Comment by DeMoorJasper** [comment]
Isn't this just because you are using window.onload? That doesn't trigger again after HMR does it?

**Comment by DeMoorJasper** [comment]
You also might check out the docs of HMR, to see how it actually works. https://en.parceljs.org/hmr.html

```Javascript
if (module.hot) {
  module.hot.dispose(function () {
	// Unregister events, destroy objects and whatnot
  });

  module.hot.accept(function () {
	// Re-register, create and do things that you expect when a module gets reloaded
    new TodosApp(); // this what ya want?
  });
}
```
