### ISSUE TITLE
how to config an multi Page(Multi Entry) project

### ISSUE THREAD

**Issue by sgf** [parcel-bundler/parcel#1895]
# ❔ Question

how to config an multi Page(Multi Entry) project
i cant find any help for that from official site. or github issues.

i can find  [entry-points](https://webpack.js.org/concepts/entry-points/)  from webpack official document.
but  the [Document](https://parceljs.org/getting_started.html) of official site seems only for SPA(Single Page Application).
there is nothing for MPA.

**Comment by DeMoorJasper** [comment]
You could use a glob, for example `parcel ./pages/*.html` or you could use spaces `parcel index.html contact.html notPartOfHtml.js`

**Comment by sgf** [comment]
Please contribute this back into the docs site if you find the time https://github.com/parcel-bundler/website :)

**Comment by dana234** [comment]
look at this video in minute 4:26. He explains how to add  multiples HTML pages with  Parcel, and it also works with bootstrap

**Comment by RomanMorozenko** [comment]
> 

what video? share a link please

**Comment by NejLee** [comment]
> what video? share a link please

Any news on this link? i'm looking for the same thing ...
