### ISSUE TITLE
Generate handlebars output 

### ISSUE THREAD

**Issue by danielo515** [parcel-bundler/parcel#1898]
Hello, first of all, thanks for parcel. 

I'm considering using parcel for easing my front-end generation.
My only requirement is to make some basic Ssr or server side hidration. 
I was guessing if it could be possible to generate an HTML file with some handlebars/ejs output to serve them through my server side templating system.

Thanks and regards

**Comment by DeMoorJasper** [comment]
It's probably possible but you should have to write a plugin.

This is probably currently the most complete SSR framework/platform using Parcel https://github.com/DeMoorJasper/blazingly

**Comment by danielo515** [comment]
Thanks for your answer @DeMoorJasper

I discovered that putting the handlebars texts directly on the html is enough. Parcel will not remove them. 
Since my templating requirements are very light (just embed some server data) this is enough for me.

Thanks
