### ISSUE TITLE
A little complaining.It may not be as useful as it might seem.

### ISSUE THREAD

**Issue by sgf** [parcel-bundler/parcel#1900]
When this project appear its looks great,because its sloved WebPack's sore point.
It is a pity that this project has been born for a long time. But its pages are full of drawbacks.

 These disadvantages may be the advantages of webpack.

I am a novice with almost 0 front-end new bee.
In Fact , The actual development, still full of various inconvenient.
i take long time to config Project base parcel.
trying to find multi Page Entry.
trying to solove some problems(such as how to exclude Vue or React from my output file).
trying to let all things works fine.

but takes too long time.

It may not be as useful as it might seem.

**Comment by DeMoorJasper** [comment]
Parcel 1 has initially had many issues on more advanced setups, we've tried to fix these along the way. Most of these more advanced options and config all together in parcel is poorly or not documented.

Currently we are working on Parcel 2 which will be more stable, scalable, more configurable than anything out there, still zero config for most setups, ... and probably most importantly completely documented as it won't change it's architecture constantly, as we've learned from Parcel 1 and try to be prepared for every use case now and in the future. It should also be compatible with parcel 1 projects as long as they use parcel with the cli and no plugins
