### ISSUE TITLE
Frontpage minimal example not working as expected 

### ISSUE THREAD

**Issue by vnglst** [parcel-bundler/parcel#1901]
# 🐛 bug report

I tried to reproduce the minimal example on the homepage, but the `console.log` to log the css from the `main` class. Instead it logs `undefined`.

## 🎛 Configuration

From the homepage:

index.html
```html
<html>
<body>
  <script src="./index.js"></script>
</body>
</html>
```

index.js

```js
// import another component
import main from './main';

main();
```

main.js
```js
// import a CSS module
import classes from './main.css';

export default () => {
  console.log(classes.main);
};
```

main.css

```css
.main {
  /* Reference an image file */
  /* background: url('./images/background.png'); */
  color: red;
}
```

Then using the npm script `"start": "parcel index.html"` to start the web server.

## 🤔 Expected Behavior

I would expect the console.log to show the contents of the `main` css class.

## 😯 Current Behavior

Console.log shows undefined instead.

This also happens when I create a production build, when I switch to the latest Node version and when I use Firefox..

Maybe I am doing something wrong, am I missing a dependency?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | v8.11.4
| npm/Yarn         | 5.6.0
| Operating System | OSX

**Comment by DeMoorJasper** [comment]
You have to enable modules in postcss config. As documented: https://parceljs.org/transforms.html#postcss

It should probably not use css modules on the getting started guide

**Comment by vnglst** [comment]
Ah yes, now it works! Thanks.

I agree that ideally the example on the frontpage should require little of no further configuration.

**Comment by DeMoorJasper** [comment]
Feel free to contribute back to the docs with a sidenote or updated example :)

https://github.com/parcel-bundler/website
