### ISSUE TITLE
SharedWorker support

### ISSUE THREAD

**Issue by rmdort** [parcel-bundler/parcel#1905]
Please add SharedWorker support to parcel. 

https://developer.mozilla.org/en/docs/Web/API/SharedWorker

**Comment by DeMoorJasper** [comment]
At first sight this seems to be pretty similar to workers (from a bundlers perspective). The regex of worker should probably be updated to also include SharedWorkers and this should work. Not sure what's not working right now.

**Comment by rmdort** [comment]
Just like web workers, Shared worker should be compiled into a separate bundle by parcel.

**Comment by DeMoorJasper** [comment]
Like I said it's probably not being catched by the current Regex

**Comment by KeineLimonade** [comment]
I developed a quick fix and wrote a test for it. I hope this helps
