### ISSUE TITLE
Hot reload doesn't work when I save files.

### ISSUE THREAD

**Issue by colonelpopcorn** [parcel-bundler/parcel#1906]
# ❔ Question

Should hot reload work out of the box in my context or am I missing a dependency?

## 🔦 Context

I'm trying to build an app with Vue and Typescript. It's been going pretty well, but Parcel doesn't rebuild when I make changes to the Typescript or Vue files. It looks like it's not detecting my changes because once I run the `yarn dev` command it builds and never changes from the `built in x.yy seconds` message. I've provided my `package.json`, Vue components, and TS entry point below. Is there anything I'm doing wrong? Do I need a Typescript hot reload plugin?

## 💻 Code Sample

[Here's my gist of what I've written so far.](https://gist.github.com/colonelpopcorn/17a84cb1f49fc2973216fa9854741d3a) 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.97
| Node             | 10.8.0
| npm/Yarn         | 6.2.0/1.9.4
| Operating System | Ubuntu 18.04.1
| Editor (VS Code) | 1.25.1

**Comment by DeMoorJasper** [comment]
This might be related to the bug here: #1743 We've recently made various changes to the watcher and only tested it on mac os x... So it might cause issues on other platforms.

**Comment by colonelpopcorn** [comment]
@DeMoorJasper That might be it. However, I tried just hard-coding `shouldWatchDirs` @ Watcher.js:14 and it still didn't change the behavior of the app. I imagine it's something deeper with the file system watcher.

**Comment by colonelpopcorn** [comment]
So I think I figured out what my issue was. I cloned my directory directly from GitHub and my repo name was the default GitHub pages repo name. The dots in the folder name were screwing with parcel and changes werent' being watched.

Thanks for pointing me in a direction that helped me figure it out!

**Comment by ashbeats** [comment]
I had a similar issue, but was I'm using Windows 10 and PHPStorm as the IDE. HMR worked for maybe a couple of times, and stopped detecting changes. 

However, I noticed that when I used Notepad++ Parcel picked up the changes fine. 

So for any of you who are using PHPStorm, WebStorm, IntelliJ or any other Jetbrains IDE that uses an auto-save feature called "Safe write". 

![save-write-options](https://user-images.githubusercontent.com/514003/44447457-5de96880-a612-11e8-86bd-d08e6b98f1c0.png)

If safe-write is selected, a changed file is first saved in a temporary file. If the save operation succeeds, the file being saved is replaced with the saved file. The original file is deleted and the temporary file is renamed. Also, the ownership of such file changes.

And Parcel <= 1.9.7 does not detect that for now. 

So in the meantime, **disable safe-write**. 


Other IDE's have similar option, but they may be named differently. 
See https://stackoverflow.com/questions/44819838/how-to-disable-safe-write-in-visual-studio-code

**Comment by Ezku** [comment]
> So I think I figured out what my issue was. I cloned my directory directly from GitHub and my repo name was the default GitHub pages repo name (e.g. colonelpopcorn.github.io was the folder name). The dots in the folder name were screwing with parcel and changes werent' being watched.

I think I ran into this too. I believe I tried all the other approaches documented around issues so far, with no success. Changing the folder name not to have dots worked.
