### ISSUE TITLE
error while installing parcel.

### ISSUE THREAD

**Issue by sagar6128** [parcel-bundler/parcel#1908]
Sagars-MacBook-Air:findit sagarprasad$ npm i -g parcel-bundler
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on readingBrowserslist >3.0 config used in other tools.
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR!

**Comment by DeMoorJasper** [comment]
This seems to be a permission issue. npm has no write permissions to the `node_modules` which makes it unable to write to them.
