### ISSUE TITLE
🐛 Local html links break

### ISSUE THREAD

**Issue by DeMoorJasper** [parcel-bundler/parcel#191]
🐛 bug report

I was trying out if it was possible to use multiple pages with Parcel (Navigation)

### 🎛 Configuration (.babelrc, package.json, cli command)
```html
<body>
  <nav>
    <a href="./test.html">test</a>
  </nav>

  <div class='fancytxt'>Hello world</div>
</body>
```
### 🤔 Expected Behavior
clicking on the link should redirect to test.html

### 😯 Current Behavior
clicking on the link results in a 404 (./dist/<hash>.html)

### 💁 Possible Solution
Remove the dist prefix for html files

### 🔦 Context
I was trying out #189

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel |  1.1.0
| Node             | v9.2.0
| npm/Yarn         | v5.5.1
| Operating System | Mac OS X High Sierra

**Comment by davidnagli** [comment]
Works for me...

Steps taken to reproduce:
1. `parcel src/index.html`
2. open http://localhost:1234/
3. click the link


[191.zip](https://github.com/parcel-bundler/parcel/files/1546298/191.zip)

**Comment by DeMoorJasper** [comment]
I'll try reproducing it again and providing a test package @davidnagli

**Comment by DeMoorJasper** [comment]
Can't seem to reproduce it anymore guess it got fixed somewhere

**Comment by tranlehaiquan** [comment]
I think we need edit document from open "https://localhost:1234" to "http://localhost:1234"
