### ISSUE TITLE
CSS from node package is not being bundled when trying to run server

### ISSUE THREAD

**Issue by amankapoor** [parcel-bundler/parcel#1910]
# 🐛 bug report

I am trying to make server side rendering work for my earlier react app. I am using [https://github.com/reactivestack/parcel-react-ssr](url) for this purpose.

Demo repo to reproduce the issue that I am facing is [https://github.com/amankapoor/parcel-react-ssr-demo](url)

**The issue in brief is as follows:-**

The development build with parcel is working as expected. The command for this is ```npm run dev``` and comes from line 8 of package.json (```"dev": "parcel app/index.html"```). If you will visit ```localhost:1234``` after running the command above, you would see a proper webpage where the first section will have a functioning image carousel and second section would have a timeline.

But when I run ```npm run build``` which comes from line 9 of package.json (```"build": "rimraf dist && npm run build-client && npm run build-server"```), then the command produces a ```dist``` folder with two sub-folders in it, ```client``` and ```server```. The ```client``` folder contains all the required files to run the site and is as expected. But the ```server``` folder lacks css files. **It is not bundling the css files from two external packages** namely ```react-vertical-timeline-component``` and ```react-responsive-carousel```. These two packages have a css file which I import at line 3 of ```app/src/components/imageCarousel.js``` and line 11 of ```app/src/components/itinerary.js```.
 
## 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc

```
{
  "presets": ["env", "react"],
  "plugins": ["transform-class-properties"],
  "env": {
    "server": {
      "presets": ["env", "react"],
      "plugins": [
        "transform-class-properties",
        "babel-plugin-dynamic-import-node"
      ]
    },
    "client": {
      "presets": ["env", "react"],
      "plugins": ["transform-class-properties"]
    }
  }
}

```

package.json

```
{
  "name": "parcel-react-ssr-demo",
  "version": "0.1.0",
  "description": "Example of SSR with React and ParcelJS",
  "main": "index.js",
  "repository": "amankapoor/parcel-react-ssr-demo",
  "scripts": {
    "dev": "parcel app/index.html",
    "build": "rimraf dist && npm run build-client && npm run build-server",
    "build-client": "cross-env BABEL_ENV=client parcel build app/index.html -d dist/client --public-url /dist --no-source-maps --detailed-report --log-level 3",
    "build-server": "cross-env BABEL_ENV=server parcel build server/index.js -d dist/server --public-url /dist --target=node --no-source-maps --detailed-report --log-level 3",
    "start": "node dist/server"
  },
  "dependencies": {
    "@material-ui/core": "^1.5.0",
    "@material-ui/icons": "^2.0.2",
    "cheerio": "^1.0.0-rc.2",
    "compression": "^1.7.3",
    "express": "^4.16.3",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "react-helmet": "^5.2.0",
    "react-responsive-carousel": "^3.1.41",
    "react-router-dom": "^4.3.1",
    "react-vertical-timeline-component": "^2.1.3",
    "recompose": "^0.28.2"
  },
  "devDependencies": {
    "babel-eslint": "^8.2.6",
    "babel-plugin-dynamic-import-node": "^2.0.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "cross-env": "^5.2.0",
    "eslint": "^5.4.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.11.1",
    "node-sass": "^4.9.3",
    "parcel-bundler": "^1.9.7",
    "react-hot-loader": "^4.3.4",
    "rimraf": "^2.6.2"
  }
}
```

## 🤔 Expected Behavior

If I run ```npm start``` then I should see a page similar to what I get after running ```npm run dev``` i.e., css files from ```react-vertical-timeline-component``` and ```react-responsive-carousel``` should be included in the output folder for server to render the page correctly.

## 😯 Current Behavior

Upon running ```npm run build```, the client part generates correct output files, but the server part lacks css files in it. I have added ```--detailed-report``` flag and you can observe the same by running ```npm run build``` command in demo repo above. You won't see any error, but no css files would be added to the folder. And then, because no error is generated, you will tend to run ```npm start``` to start the node server, and when you will run it, you will see the following error.

```
amankapoor@amankapoor:~/parcel-react-ssr-demo$ npm start

> parcel-react-ssr-demo@0.1.0 start /home/amankapoor/parcel-react-ssr-demo
> node dist/server

/home/amankapoor/parcel-react-ssr-demo/node_modules/react-responsive-carousel/lib/styles/carousel.min.css:1
(function (exports, require, module, __filename, __dirname) { .carousel .control-arrow,
                                                              ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at u (/home/amankapoor/parcel-react-ssr-demo/dist/server/index.js:1:353)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! parcel-react-ssr-demo@0.1.0 start: `node dist/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the parcel-react-ssr-demo@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/amankapoor/.npm/_logs/2018-08-19T22_05_08_837Z-debug.log
```

## 💁 Possible Solution

I am unable to figure out a solution for this. I tried importing css files in ```server/index.js``` file, but it didn't help.

## 🔦 Context

I am trying to do server side rendering of my existing app and this issue does not let me do that.

## 💻 Code Sample

To reproduce, clone [https://github.com/amankapoor/parcel-react-ssr-demo](url) and run ```npm install``` the first time. Then first run ```npm run dev``` and visit ```localhost:1234``` to see a properly rendered page. Then run ```npm run build``` and then ```npm start``` to see the error pointing towards css files.

You can then optionally go to ```node_modules/react-responsive-carousel/lib/styles/carousel.min.css``` and delete all the css code from the file. Do the same with ```node_modules/react-vertical-timeline-component/style.min.css```. And then delete the ```.cache``` folder and run ```npm run build``` and ```npm start```. Now node server will serve the site, but without the css files.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 8.9.4
| npm/Yarn         | 6.2.0
| Operating System | Ubuntu 16.04

**Comment by amankapoor** [comment]
Anybody, any help?

**Comment by DeMoorJasper** [comment]
I'm unfamiliar with reactivestack/parcel-react-ssr and it's probably fairly old.
This seems to be fairly impossible to me as node target doesn't create urls nor packages node modules, and if it does it would expect JS or anything that builds to JS not a css file. I don't think SSR projects should import CSS they should either use seperate CSS files or use CSS in JS.

The SSR platform should be able to dynamically load these into the result it sends to the browser as parcel can't magically attach css files to a non existing html file. Def not in node mode as that only expects JS as it's not a browser...

**Comment by amankapoor** [comment]
My css files were being imported from node_modules folder. When I put those two files in different folder, and imported from there, my code worked. Thank you for your comment btw, it taught me two additional things. :)

**Comment by rahulv1992** [comment]
@amankapoor I am running into a similar issue. Can you please explain a bit more about how were you able to resolve it?
I tried the following:
1. Move CSS file from `node_modules/` into the same directory where my js file(using the carousel) is
2. import CSS in the js file with './carousel.css' 

But still, it fails and throws the following error:
SyntaxError: /Users/rahulv-M/Documents/FerrisWheel/frontend-demo/src/shared/components/Header/carousel.css: Unexpected token (10:0)

   8 | COLOURS
   9 | ********************************************/
> 10 | .carousel .control-arrow, .carousel.carousel-slider .control-arrow {
     | ^
  11 |   -webkit-transition: all 0.25s ease-in;
  12 |   -moz-transition: all 0.25s ease-in;
  13 |   -ms-transition: all 0.25s ease-in;
    at Parser.pp$5.raise (/Users/rahulv-M/Documents/FerrisWheel/frontend-demo/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/rahulv-M/Documents/FerrisWheel/frontend-demo/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/Users/rahulv-M/Documents/FerrisWheel/frontend-demo/node_modules/babylon/lib/index.js:3750:12)
    at Parser.parseExprAtom (/Users/rahulv-M/Documents/FerrisWheel/frontend-demo/node_modules/babylon/lib/index.js:7238:22)
    at Parser.pp$3.parseExprSubscripts (/Users/rahulv-M/Documents/FerrisWheel/frontend-demo/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/rahulv-M/Documents/FerrisWheel/frontend-demo/node_modules/babylon/lib/index.js:3474:19)
