### ISSUE TITLE
Parcel without HMR doesn't reload the page

### ISSUE THREAD

**Issue by MatejMazur** [parcel-bundler/parcel#1915]
# 🐛 bug report

Parcel with `--no-hmr` doesn't reload the page after changes in code.

## 🎛 Configuration (.babelrc, package.json, cli command)

I'm using only `parcel start src/index.html --no-hmr` without any configs. And I installed only `parcel-bundler`, `react` and `react-dom`.

## 🤔 Expected Behavior

It should reload the page with updated code.

## 😯 Current Behavior

Nothings reload.

## 💁 Possible Solution

I don't know but it looks like that there is some problem with watcher.

## 🔦 Context

I'm trying to develop an app and HMR doesn't work correctly (sometimes I need a full page reload). But parcel without ordinary page reload is currently unusable for me. I tried even `--no-cache` but that doesn't help.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.9.7
| Node             | 8.10
| npm/Yarn         | 6.1.0/1.9.4
| Operating System | Windows 10 or Linux Kubuntu 18.04

**Comment by MatejMazur** [comment]
I thought that you can fully reload the page without HMR. Like it's possible in create-react-app. Is that possible?

**Comment by DeMoorJasper** [comment]
Well that's possible with hmr, not if you disable it.

Add this in the entrypoint
```Javascript
if (module.hot) {
  module.hot.accept(function () {
    location.reload();
  });
}
```

**Comment by DeMoorJasper** [comment]
Feel free to contribute to the docs, they're just markdown file so should be fairly easy https://github.com/parcel-bundler/website

@MatejMazur

**Comment by odinho** [comment]
But sometimes the `hmr` decides to reload a sub-module, so the reload function is not called. Is there a way to do a "system wide `module.hot.accept`"?
