### ISSUE TITLE
Why does parcel generates a styles.[hash].js on non javascript projects?

### ISSUE THREAD

**Issue by brielov** [parcel-bundler/parcel#1922]
I have a very simple project with one index.html file and one styles.css file. The HTML file includes the CSS file and that's about it. But when I run the build command:

`parcel build --no-cache --no-source-maps --detailed-report --public-url ./ src/index.html`

I get an extra file:

```
dist/styles.8b27ab1b.js     1.02 KB    1.39s <-- I don't need nor want this
dist/styles.8b27ab1b.css      673 B    1.39s
dist/index.html               398 B    763ms
```

This is the only thing that gets imported in the HTML file:

`<link rel="stylesheet" href="./styles.css">`

Am I doing something wrong?

**Comment by DeMoorJasper** [comment]
CSS Generates some JS for HMR and css modules. That's why it creates a JS file, not sure what it contains in case of build, you could look into it and see what it actually creates. Might help

**Comment by brielov** [comment]
```javascript
parcelRequire=function(e,r,n,t){var i="function"==typeof parcelRequire&&parcelRequire,o="function"==typeof require&&require;function u(n,t){if(!r[n]){if(!e[n]){var f="function"==typeof parcelRequire&&parcelRequire;if(!t&&f)return f(n,!0);if(i)return i(n,!0);if(o&&"string"==typeof n)return o(n);var c=new Error("Cannot find module '"+n+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[n][1][r]||r};var l=r[n]=new u.Module(n);e[n][0].call(l.exports,p,l,l.exports,this)}return r[n].exports;function p(e){return u(p.resolve(e))}}u.isParcelRequire=!0,u.Module=function(e){this.id=e,this.bundle=u,this.exports={}},u.modules=e,u.cache=r,u.parent=i,u.register=function(r,n){e[r]=[function(e,r){r.exports=n},{}]};for(var f=0;f<n.length;f++)u(n[f]);if(n.length){var c=u(n[n.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=c:"function"==typeof define&&define.amd?define(function(){return c}):t&&(this[t]=c)}return u}({"Tnu0":[function(require,module,exports) {
module.exports={};
},{}]},{},[], null)
```

Should this be included in a production build?

**Comment by DeMoorJasper** [comment]
Seems like the prelude without any actual code, except for an empty module.export, which is probably from css

**Comment by brielov** [comment]
Oh okay, I removed .postcssrc and it went away. I will not be using css modules anyway. Thanks for the fast responses!
