### ISSUE TITLE
Ability to disable automatic babel compilation 

### ISSUE THREAD

**Issue by littlstonee** [parcel-bundler/parcel#1927]
# 🙋 feature request
Ability to disable automatic babel compilation should be added. 

## 🤔 Expected Behavior
Automatic babel compilation can be actived by default, and disabled by some customized config.

## 😯 Current Behavior
Babel compilation is automatic actived no matter  `.babelrc` presented or not.

## 💁 Possible Solution
Solution one: Disable compilation if no `.babelrc`  presented.
Solution two: Disable compilation if `.babelrc`  presented with such config `{"presets": []}`

## 🔦 Context
First of all, I wanna say Parcel is wonderful !  But still need improving.
I'm building an UI framework targeting latest browsers, the framework aims to be morden and lightweight, so it's unnecessary to compile es6 features. 
Automatic compilation results to extra file size in my case, and it makes my framework not lightweight enough.
I hope this feature request could be considered, since other people have the same willing.  #1207

**Comment by DeMoorJasper** [comment]
This will probably not get fixed in Parcel 1, but will be configurable in Parcel 2

**Comment by littlstonee** [comment]
@DeMoorJasper Thanks for the reply.

**Comment by devongovett** [comment]
Note that you can also disable babel by using `"browserlist": ["last 1 Chrome version"]` in your package.json.

**Comment by KonradLinkowski** [comment]
It's 
`"browserslist": ["last 1 Chrome version"]`
not
`"browserlist": ["last 1 Chrome version"]`
for anybody who also got `browserlist key instead of browserslist` error.
