### ISSUE TITLE
If I don't use CLI, can I use api file?

### ISSUE THREAD

**Issue by weishijun14** [parcel-bundler/parcel#1929]
# ❔ Question

Can I use api file?
https://en.parceljs.org/api.html

And how to organize?

parcelrc.js in my project root dir?
and add script in package.json: `'start' : node ./parcelrc.js` ?
Is this right?

please help~

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by DeMoorJasper** [comment]
You can do whatever you want with parcels api, there is no set naming default as it's just a node module.

but yes, you run it like `node whateveryounamethefile.js`
