### ISSUE TITLE
Importing CSS files that do not exists hangs the build process forever

### ISSUE THREAD

**Issue by RPDeshaies** [parcel-bundler/parcel#1932]
# 🐛 bug report

When importing a `css` file that doesn't exist, using the typescript import command`, the parcel build commands get stuck and hangs until you kill the console or the build server timeout

## 🎛 Configuration (.babelrc, package.json, cli command)

Package.json
```
    "parcel-bundler": "^1.9.7",
    "parcel-plugin-bundle-visualiser": "^1.1.2",
    "parcel-plugin-inlinesvg": "0.0.14",
```

CLI

```
parcel build index.html --out-dir static--no-cache --public-url /static
```

Tsconfig

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "importHelpers": true,
    "skipLibCheck": true,
    "noUnusedLocals": true,
    "jsx": "react",
    "lib": ["es2015", "dom"],
    "outDir": ".temp/typescript"
  }
}

```

## 🤔 Expected Behavior

I expect the build process to fail if it finds ANY errors otherwise my build server will get stuck in a loop until there's a timeout

## 😯 Current Behavior
The console displays an error, gets stuck and than nothing

```
🚨  /Users/some-project/src/modules/playground/loader/loader.tsx:9:8: Cannot resolve dependency '../app/app.css' at '/Users/some-project/src/modules/playground/app/app.css'
    at Resolver.resolve (/Users/some-project/app/node_modules/parcel-bundler/src/Resolver.js:69:17)
    at <anonymous>

```

## 💁 Possible Solution

Kill the process as soon as one error is found ?

## 🔦 Context

I'm trying to build my application on my build server and realized that the build task took 119 minutes and crashed.

When looking at the logs I realized I was importing a CSS file that I had moved somewhere else.
SO there was indeed a problem with my code, but the build server should have stopped immediatly

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  ^1.9.7
| Node             | v8.11.2
| npm/Yarn         | 6.3.0
| Operating System | Mac OS

**Comment by DeMoorJasper** [comment]
It should already exit, but it was broken a little while back due to recent changes in child processes preventing parcel from exiting.

Related line https://github.com/parcel-bundler/parcel/blob/master/src/Bundler.js#L338

**Comment by RPDeshaies** [comment]
Alright. Good to know. 

When is the next release supposed to come out ?
