### ISSUE TITLE
Missing support for dependency discovery in JSON-LD for schemas

### ISSUE THREAD

**Issue by bre7** [parcel-bundler/parcel#1935]
https://github.com/parcel-bundler/parcel/blob/master/src/assets/HTMLAsset.js#L64 JSON is skipped. I know schema.org specs are quite extensive but there are a few basics: image / logo for assets.

# 🙋 feature request

Assets used in JSON-LD schemas aren't added to the dependency tree. And as a result are missing from builds.

## 🤔 Expected Behavior

A minimal subset of the attributes should be included in parcel, just like it was done with Open Graph, etc: https://github.com/parcel-bundler/parcel/pull/747

## 😯 Current Behavior

Nothing happens since `application/ld+json` scripts aren't recognized.

## 💁 Possible Solution

Parse JSON, fetch attributes that match a list (almost the same as https://github.com/parcel-bundler/parcel/pull/747) and finally add them as dependencies.

## 💻 Examples

```html
<script type="application/ld+json">
{
  "@context": "http://www.schema.org",
  "@type": "xxx",
  "name": "Parcel Bundler",
  "url": "https://parcel.url/",
  "image": "./images/header.jpeg",
  "logo": "./images/logo.png"
}
</script>
```

**Comment by bre7** [comment]
Update: Made a plugin for it. Not sure if this will be considered as a core functionality. (thanks Japer for the template 😉)

**Comment by devongovett** [comment]
Very cool. Would you like to make a PR to add that to core? I think it will be much easier to maintain there without depending on the internal implementation details of HTMLAsset in a plugin.

**Comment by bre7** [comment]
Sure, but there's a critical issue that needs fixing first (and I'm not really sure how to do it). Paths aren't allowed, only full URLs.
