### ISSUE TITLE
pre-commit hook error

### ISSUE THREAD

**Issue by bre7** [parcel-bundler/parcel#1937]
# 🐛 bug report

When trying to submit a PR, Sourcetree reports the following issue:

> husky > pre-commit hook failed (add --no-verify to bypass)

## 🤔 Expected Behavior

Commit should go through.

## 😯 Current Behavior

Unable to push commit. Had to bypass commit hooks.

## 💁 Possible Solution

Some users reported that updating to husky 1.0 (rc-13 is out) solved the issue:

* https://github.com/typicode/husky/issues/137
* https://github.com/typicode/husky/issues/205

## 💻 Code Sample

Fork, edit any file, try to push a new commit.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 10.6.0
| npm/Yarn         | yarn 1.9.4
| Operating System | Win 10

**Comment by DeMoorJasper** [comment]
Might be a linting issue. Try `yarn format`

**Comment by bre7** [comment]
👍 worked
