### ISSUE TITLE
Sitemap generation support

### ISSUE THREAD

**Issue by bre7** [parcel-bundler/parcel#1938]
Would this feature be out of Parcel's scope ? I currently use gulp-sitemap.

# 🙋 feature request

Generate an entrypoint sitemap

## 💁 Possible Solution

The feature itself is relatively simple since it doesn't need to parse any of the files, only list them.

## 🔦 Context

Create a sitemap

## 💻 Examples

```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://site.com/entrypoint1</loc>
    <lastmod>2018-08-25T15:35:53.782Z</lastmod>
  </url>
  <url>
    <loc>https://site.com/entrypoint2</loc>
    <lastmod>2018-08-25T15:35:53.782Z</lastmod>
  </url>
  <url>
    <loc>https://site.com/</loc>
    <lastmod>2018-08-25T15:35:53.782Z</lastmod>
  </url>
</urlset>
```

**Comment by KeineLimonade** [comment]
I think this feature could be implemented as a plugin, which would prevent the HTMLAsset class from becoming even bigger...
I will have a look

**Comment by tom-julux** [comment]
I created a small plugin for this feature: **[parcel-plugin-sitemap](https://github.com/tom-julux/parcel-plugin-sitemap)**

It is pretty self explanatory and very easy to use and enable.

**Comment by bre7** [comment]
Thanks 😉
