### ISSUE TITLE
parcel + dojo coexist

### ISSUE THREAD

**Issue by aihuawu** [parcel-bundler/parcel#1942]
I have some old dojo js library.
Now I want to use parcel for new js script.
Any way to disable parcel to process for old js script.
Or is it possible to have different js asset loaders for different js files?
In webpack, it has some kind of module test/use.
Can we do the same thing for parcel?

George

**Comment by DeMoorJasper** [comment]
Not sure what you are asking.

There is an ignore field in babel to disable transforms as far as I know.
