### ISSUE TITLE
When building ignored directive <!-- #include virtual="URL" -->. How to fix it?

### ISSUE THREAD

**Issue by YuriFedorov** [parcel-bundler/parcel#1943]
# ❔ Question

When building ('yarn run build') ignored directive `<!-- #include virtual="URL" -->.` 

before (src):
![before](https://user-images.githubusercontent.com/33720649/44656391-53a7df80-aa01-11e8-91e2-877c36d045b4.jpg)

after (dist):
![after](https://user-images.githubusercontent.com/33720649/44656418-6a4e3680-aa01-11e8-9239-42d62efe28fb.jpg)

## 🔦 Context

This is necessary for loading CSS asynchronously, as [described here](https://github.com/filamentgroup/loadCSS/)

## 💻 Code Sample
link to the repository https://github.com/YuriFedorov/experimental

For asynchronous CSS loading, i had to manually insert the line: 
`<script><!--#include virtual="cssrelpreload.js" --></script>` 
to the compiled index.html (dist).

Watch the demo [http://yuri-inpost.h1n.ru](http://yuri-inpost.h1n.ru)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 8.11.4
| Yarn         | v1.9.4
| Operating System | Win10

**Comment by DeMoorJasper** [comment]
This is because html gets minified and a comment is usually unnecessary in production. As long as you stick to standard HTML.

You could create a htmlnanorc file and disable stripping of comments.

**Comment by YuriFedorov** [comment]
Thank you for your answer!

I found a sample file from you .htmlnanorc
https://github.com/parcel-bundler/parcel/blob/master/test/integration/htmlnano-config/.htmlnanorc

`{`
  `mergeStyles: true,`
  `minifySvg: false,`
 ` minifyJson: true,`
  `collapseWhitespace: "all"`
`}`

Sorry for the stupid question. Looks like the line that disables the deletion of comments?

**Comment by DeMoorJasper** [comment]
https://github.com/posthtml/htmlnano#removecomments

**Comment by YuriFedorov** [comment]
removeComments has only two options:  "safe" and "all". I tried "false".
when building, comments are still deleted

![safe](https://user-images.githubusercontent.com/33720649/44680718-37c72c80-aa47-11e8-9b6e-1600a405bad1.png)
![false](https://user-images.githubusercontent.com/33720649/44680723-3a298680-aa47-11e8-8589-47fc15ad99c8.png)

Am I doing something wrong?

**Comment by DeMoorJasper** [comment]
Might be an issue with the cache not detecting new config files, so maybe clear the cache

**Comment by YuriFedorov** [comment]
I must have tired you already. Cleaned the directory .cache,  but the problem has not disappeared.

before
![before](https://user-images.githubusercontent.com/33720649/44701953-b5b42380-aa99-11e8-87cf-e33bad8ece99.png)

after
![after](https://user-images.githubusercontent.com/33720649/44701966-c06eb880-aa99-11e8-9c1c-b970c30b48d6.png)

a new cache is generated during the build

**Comment by YuriFedorov** [comment]
What do you think?
Can in parcel there is already the other way to, as to do optimized bundle?

I am trying to use the method offered by Google
https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery

![optimize css delivery](https://user-images.githubusercontent.com/33720649/44705241-bacb9f80-aaa6-11e8-9c69-e79e30fa50e5.jpg)

Can you recommend "working way" for parcel?

**Comment by DeMoorJasper** [comment]
Best practice is using async loading of css with critical css being inlined

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by YuriFedorov** [comment]
> Best practice is using async loading of css with critical css being inlined
Yes, perhaps it is worth to do so..

Thank you for your help! 
Issue can be considered closed
