### ISSUE TITLE
Importing the same static file inside two different dynamic imports doesn't work

### ISSUE THREAD

**Issue by samuelgozi** [parcel-bundler/parcel#1946]
# 🐛 bug report

I have a project that dynamically imports two components, inside both of those components I import the same static file.
That static file doesn't get copied to the `dist`folder. This also happens if you import multiple files using globs.
If I only import that file/s inside one dynamic component then it works fine.

## 🎛 Configuration (.babelrc, package.json, cli command)
[You can see a simplified replication here on github.](https://github.com/samuelgozi/parcel-bug-replication)

## 🤔 Expected Behavior

All the files should be copied into the `dist` folder.

## 😯 Current Behavior

None of the imported files are copied.

## 💁 Possible Solution

If I knew I would have made a pull request.

## 🔦 Context

Well, this makes parcel unusable for me, and its a shame since I really like it and im trying to promote it in my workplace.

## 💻 Code Sample

Minimal reproduction of the bug:
https://github.com/samuelgozi/parcel-bug-replication

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.1 |
| Node             | 10.8.0|
| npm/Yarn         | yarn 1.9.4 |
| Operating System | macOS|

**Comment by samuelgozi** [comment]
For now, a workaround this issue will be to add an import wor the same files in a non-dynamic JS component.
For example, add  `import './assets/icons/*.svg';` to the main JS file, and those files will be copied, and you will be able to use them in dynamically imported JS files as you normally would.

**Comment by victor-cordova** [comment]
@samuelgozi can you check if this still happens with the latest version of parcel? Looks related to https://github.com/parcel-bundler/parcel/issues/2012#issuecomment-431596339 which is already solved

**Comment by samuelgozi** [comment]
@victor-cordova Thanks for the update, It seems like the bug no longer exists.
The issue can be closed.

**Comment by MaffooBristol** [comment]
I'm on 1.11.0 and having this issue. It's with all imports, including actual JavaScript imports. Same goes for #2012

As a note I'm using a React lazy load component that looks a bit like this:
```
import React, { lazy, Suspense } from 'react';

import Loading from '/shared/components/Loading';

function DefaultFallback() {
  return <Loading />;
}

export default (route, timeout = 800, Fallback = <DefaultFallback />) => {
  const Component = lazy(() => {
    return Promise.all([
      route,
      new Promise((resolve) => setTimeout(resolve, timeout)),
    ])
    .then(([moduleExports]) => moduleExports);
  });
  return (props) => (
    <Suspense fallback={Fallback}>
      <Component {...props} />
    </Suspense>
  );
};
```
