### ISSUE TITLE
Relative LESS imports doesn't work

### ISSUE THREAD

**Issue by chessbr** [parcel-bundler/parcel#1947]
# 🐛 bug report

Relative imports using `url()` doesn't work

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "dev",
  "version": "1.0.0",
  "dependencies": {
    "bootstrap3": "^3.3.5",
    "parcel-bundler": "^1.9.7"
  },
  "devDependencies": {
    "less": "^3.8.1"
  }
}

```

## 🤔 Expected Behavior

Parcel should import bootstrap static files and copy them to output path

## 😯 Current Behavior

```
./node_modules/.bin/parcel watch index.less 
🚨  /home/christian/dev/parcel-test/index.less: Cannot resolve dependency './../fonts/glyphicons-halflings-regular.eot' at '/home/christian/dev/fonts/glyphicons-halflings-regular.eot'
    at Resolver.resolve (/home/christian/dev/parcel-test/node_modules/parcel-bundler/src/Resolver.js:69:17)
    at <anonymous>
```

## 💁 Possible Solution

To temporarily fix the issue, I have to override the variable to point to bootstrap fonts..

```less
@import "~bootstrap3/less/bootstrap.less";
@icon-font-path: "./node_modules/bootstrap/fonts/";
```

## 🔦 Context

I want to create a vendor.css file that includes all code form 3rd party libs

## 💻 Code Sample

```less
@import "~bootstrap3/less/bootstrap.less";
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7 |
| Node             | 8.11.3 |
| npm/Yarn         | npm 6.3.0 |
| Operating System | Linux overflow 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux |

**Comment by jenil** [comment]
is there a way to get this working?
