### ISSUE TITLE
Dev server doesn't serve files without a file extension

### ISSUE THREAD

**Issue by magcius** [parcel-bundler/parcel#1948]
# 🐛 bug report

I have a static file without an extension (it's a 3D scene blob file) that I want served in the Parcel Dev Server. Unfortunately, the file is not served. It seems to be due to this line of code here: https://github.com/parcel-bundler/parcel/blob/master/src/Server.js#L57

## 🎛 Configuration (.babelrc, package.json, cli command)

I have none.

## 🤔 Expected Behavior

The file should be served.

## 😯 Current Behavior

The main HTML bundle is served instead.

## 💁 Possible Solution

If the file is missing an extension, please check to see if it exists on disk, and serve it if it does exist.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | v10.0.0
| npm/Yarn         | npm version 5.6.0
| Operating System | Windows 10

**Comment by DeMoorJasper** [comment]
That's because of SPA's and / would resolve to index.html in most http servers.

You could just append `.blob` probably helps you keep an overview as well. Also parcel uses extensions to determine which transforms to use (obv. non in case of a blob) but it might prevent future bugs as well

**Comment by DeMoorJasper** [comment]
@magcius perhaps you can try using `parcel watch ...` and use your own server, this way you can configure it how you like. This is probably not gonna be easy to implement, as we want to support as many apps as possible and SPA's are generally the bigger portion of parcels user base as far as I know.
