### ISSUE TITLE
is there a way to bundle everything into a single file when build target is node?

### ISSUE THREAD

**Issue by li-xinyang** [parcel-bundler/parcel#1950]
# ❔ Question

    parcel build index.js --target node

I tried to use the command above to build my mini project.

It is still using `request` in the output file. 

is there a way to bundle everything into a single file when build target is `node`?

## 🔦 Context

where fs is not available

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by DeMoorJasper** [comment]
Will be part of the next release https://github.com/parcel-bundler/parcel/pull/1690
