### ISSUE TITLE
Service worker registration isn't detected

### ISSUE THREAD

**Issue by janat08** [parcel-bundler/parcel#1957]
# 🐛 bug report

trying to get service worker registered, i belief it's suppose to be served by http server rather than loaded with index.js?

## 🎛 Configuration (.babelrc, package.json, cli command)
inst in fact full stacktrace
```
×  C:\Users\user\dev\react-head\src\client\index.js:25:21: Cannot resolve dependency 'C:\Users\user\dev\react-head\src\client\sw.js'
```

## 🔦 Context

service workers

## 💻 Code Sample
```js
try {
  if ("serviceWorker" in navigator) {
    window.addEventListener("load", () => {
      try {
        navigator.serviceWorker.register('./sw.js').then(r=>{
          registration = registration
        }).catch(e=>{
          console.log("SW error", e)
        })
      } catch (e) {
        console.log(e, "error in registration")
      }
    })
  }
}catch (e) {
  console.log(e, "error in registration")
}}
```

## 🌍 Your Environment

running with nodemon that I expect to send sw.js

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 8.11.3
| npm/Yarn         | 1.9.4 
| Operating System | windows 10

**Comment by janat08** [comment]
actually it's not detected either way, I guess I should've send it with the index.html

**Comment by janat08** [comment]
Ye I got latest version installed

**Comment by DeMoorJasper** [comment]
Why so many try catches?

**Comment by DeMoorJasper** [comment]
This would do exactly the same thing and catch all errors:
```
if ("serviceWorker" in navigator) {
  window.addEventListener("load", () => {
    navigator.serviceWorker.register('./sw.js').then(r => {
      registration = registration;
    }).catch(e => {
      console.log("SW error", e);
    });
  });
}
```

**Comment by janat08** [comment]
the localhost:port/sw.js serves the file. I don't actually send it to the client in index.html with index.js, is that what's suppose to occur?

**Comment by janat08** [comment]
looking at the some of tests I should bundle it

**Comment by janat08** [comment]
https://github.com/parcel-bundler/parcel/commit/2bc6ed9ab63a35533c1637f558f64253defd789b

**Comment by janat08** [comment]
right, I'll put it near the index.js or bundle it, if all else fails.

**Comment by janat08** [comment]
yea it pulls in the file from path, rather than http.
