### ISSUE TITLE
require.cache missing

### ISSUE THREAD

**Issue by jfrconley** [parcel-bundler/parcel#1959]
# ❔ Question

What properties are supposed to be available on the require object at runtime? Is it intended to fully mirror the node require?

## 🔦 Context

I am testing out the new "--bundle-node-modules" option, but some node_modules try to get the keys for the require cache and die.

## 💻 Code Sample
This code will fail when bundled
```javascript
Object.key(require.cache);
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |latest git|

**Comment by DeMoorJasper** [comment]
It has no properties, it's just a function that takes in the location of a file. Or identifier in compiled code.

If you really wanna dig into parcel internals there is a resolve property on it but that's it.

You can have a look at https://github.com/parcel-bundler/parcel/blob/master/src/builtins/prelude.js for the entire implementation of require

**Comment by jfrconley** [comment]
Preventing code like this from crashing on startup
`Object.keys(require.cache)`
In my case, it's buried inside of transitive dependency.
require.cache can validly be an empty object, I think it would be a simple way to improve compatibiltiy

**Comment by DeMoorJasper** [comment]
Feel free to open up a PR or RFC
