### ISSUE TITLE
JSON with references to hashed files

### ISSUE THREAD

**Issue by hirasso** [parcel-bundler/parcel#1963]
Hi there! 

Now this would be amazing: Is there a way to tell parcel to put a `.json` file inside the `./dist` folder that contains references to hashed files using their original names? I'm imagining something like the following:

## Pseudo-code
```
{
  "some-file.ext": "some-file.content-hash.ext"
}
```

## Usage Example
```json
{
  "favicon.png" : "favicon.09bcacef.png",
  "house.svg": "house.33b919c8.svg"
}
```
That would come in very handy when also loading bundled files from outside a parcel bundle, like for example a PHP environment.

**Comment by DeMoorJasper** [comment]
Wouldn't be hard to create a plugin for it

**Comment by hirasso** [comment]
> Wouldn't be hard to create a plugin for it

...not if I would know what I'm doing 😉

Do you have 1-2 hints on where a plugin would have to hook into the parcel code to do that? I'm imagining an event or something similar that gets fired with all bundled assets...

**Comment by DeMoorJasper** [comment]
I have a SSR framework, that actually takes full control over naming and such, so it's probably a little overkill. But might be nice to learn some things from. https://github.com/DeMoorJasper/blazingly

I think it's just easier if I would explain though.

A parcel plugin gets the bundler object, so you can listen for bundler.on('bundled'). Which will emit after each bundle and it has a callback with the mainBundle as it's argument.

```
// This is a plugin
module.exports = function (bundler) {
  bundler.on('bundled', () => {
    let aNiceMapWithAllNamesMappedToHashes = bundler.bundleNameMap;
	// Save it to a JSON File...
  });
};
```

**Comment by hirasso** [comment]
Thanks for this hint! When doing `console.log(bundleNameMap)` though, I get crazy file names pointing to the hashed file names. To stick with my original example: 
```json
Map {
  '1fba6721b387fcaf61c5a08533b919c8.svg' => 'house.33b919c8.svg',
  'aee30a003f28ca77bfde9e54efbd8b79.png' => 'favicon.09bcacef.png'
}
```
Is there also a point in the bundling process, where I can get the real original filenames, or a way to retrieve them using the keys of the `bundleNameMap`?

**Comment by DeMoorJasper** [comment]
I kinda was afraid that was gonna be the case. You could manually create a similar map by going through each bundle recursively and using the name of the entryAsset (and skipping if one does not exist - this is in case of virtual things like HMR Js, sourcemaps, ...)

bundle.entryAsset.name => Original filename
bundle.childBundles => Iterate this recursively and you should be able to get a nice list

**Comment by hirasso** [comment]
Does this look good to you?
```javascript
bundler.on('bundled', () => {
  let manifest = {};
  for( let bundle of bundler.mainBundle.childBundles ) {
    manifest[bundle.entryAsset.basename] = path.basename( bundle.name );
    for( let childBundle of bundle.childBundles ) {
      // skip if entryAsset is null
      if( !childBundle.entryAsset ) {
        continue;
      }
      manifest[childBundle.entryAsset.basename] = path.basename( childBundle.name );
    }
  }
  // TODO: Save it to a JSON File...
});
```

**Comment by DeMoorJasper** [comment]
I would make it recursive, as each childBundle can have childBundles of it's own, it's a tree of bundles.

**Comment by hirasso** [comment]
Of course, makes sense. That's just a first draft. I also noticed that checking for `!childBundle.entryAsset` doesn't work, since the entryAsset for `css` for example is null, but the file exists. I'll better use `fs.existsSync(bundle.name)`, right?

**Comment by DeMoorJasper** [comment]
Thought every bundle had an entryAsset if it wasn't virtual.

You could also use `Array.from(bundle.assets.values())[0]` or something, to get the original name I think

**Comment by hirasso** [comment]
Works great, thanks! Here's the cleaned up code:

```javascript
bundler.on('bundled', () => {
  let manifest = addToManifest( {}, bundler.mainBundle.childBundles );
  console.log( manifest );
  // TODO: Save it to a JSON File...
});
function addToManifest( manifest, bundles ) {
  for( let bundle of bundles ) {
    let original = Array.from( bundle.assets.values() )[0].basename;
    let hashed = path.basename( bundle.name );
    manifest[original] = path.basename( hashed );
    manifest = addToManifest( manifest, bundle.childBundles )
  }
  return manifest;
}
```

**Comment by DeMoorJasper** [comment]
Glad I could help :)

**Comment by hirasso** [comment]
Oh sorry, just realized that `Array.from( bundle.assets.values() )[0].basename` doesn't quite work. I get unexpected results:
```json
{
  "admin.js": "admin.map",
  "admin.scss": "admin.css",
  "app.js": "app.map",
  "flickity.css": "app.css",
  "house.svg": "house.33b919c8.svg",
  "editor-style.js": "editor-style.map",
  "editor-style.scss": "editor-style.css"
}
```
I'll have another look next week sometime with a fresh head and report back as soon as I found a working solution.

**Comment by DeMoorJasper** [comment]
Yeah figured there are some bugs in that code.

Should be something like this:
```Javascript
bundler.on('bundled', () => {
  let manifest = addToManifest(bundler.mainBundle);
  console.log(manifest);
});
function addToManifest(bundle, manifest = {}) {
  manifest[Array.from(bundle.assets.values())[0].basename] = path.basename(bundle.name);

  if (bundle.childBundles.size() > 0) {
    for (let childBundle of bundle.childBundles.values()) {
      manifest = addToManifest(childBundle, manifest);
    }
  }
  return manifest;
}
```

**Comment by hirasso** [comment]
Or maybe now I found the solution. Seems like if `entryAsset` is `null`, the output file doesn't contain a hash. So we can just use it's name in that case (now also with the `fs.writeFile`):
```javascript
bundler.on('bundled', () => {
  let manifest = addToManifest( {}, bundler.mainBundle.childBundles );
  fs.writeFile(`${bundler.options.outDir}/manifest.json`, JSON.stringify(manifest, null, 2), 'utf8', function (err) {
    if (err) { return console.log(err); }
  });
});

function addToManifest( manifest, bundles ) {
  for( let bundle of bundles ) {
    let outputName = path.basename( bundle.name );
    let originalName = bundle.entryAsset ? bundle.entryAsset.basename : outputName;
    manifest[originalName] = outputName;
    manifest = addToManifest( manifest, bundle.childBundles )
  }
  return manifest;
}
```

**Comment by hirasso** [comment]
Oh sorry, moved to fast. I'll read through your code the next days. It's getting late over here in Germany ;)

**Comment by hirasso** [comment]
@DeMoorJasper So, I think I found the issue. Maybe it is related to my setup. I'm using three `.js` files as entry points for parcel:
```javsacript
const bundler = new Bundler('src/*.js', options);
```
That leads to the following structure for my `bundler.mainBundle`:
```shell
Bundle {
  type: undefined,
  name: undefined,
  parentBundle: undefined,
  entryAsset: null,
  assets: Set {},
  childBundles: 
   Set {
     Bundle {
     type: 'js',
     name: './dist/script-one.js',
     parentBundle: [Circular],
     entryAsset: [Object],
     assets: [Object],
     childBundles: [Object],
     siblingBundles: [Object],
     siblingBundlesMap: [Object],
     offsets: Map {},
     totalSize: 0,
     bundleTime: 0,
     isolated: undefined },
     Bundle {
     type: 'js',
     name: './dist/script-two.js',
     parentBundle: [Circular],
     entryAsset: [Object],
     assets: [Object],
     childBundles: [Object],
     siblingBundles: [Object],
     siblingBundlesMap: [Object],
     offsets: Map {},
     totalSize: 0,
     bundleTime: 0,
     isolated: undefined },
     Bundle {
     type: 'js',
     name: './dist/script-three.js',
     parentBundle: [Circular],
     entryAsset: [Object],
     assets: [Object],
     childBundles: [Object],
     siblingBundles: [Object],
     siblingBundlesMap: [Object],
     offsets: Map {},
     totalSize: 0,
     bundleTime: 0,
     isolated: undefined } },
  siblingBundles: Set {},
  siblingBundlesMap: Map {},
  offsets: Map {},
  totalSize: 0,
  bundleTime: 0,
  isolated: undefined }
```
...wich means that`Array.from(bundle.assets.values())[0].basename` [in your code](https://github.com/parcel-bundler/parcel/issues/1963#issuecomment-417796248) will be undefined when the function is first being called.

[My script](https://github.com/parcel-bundler/parcel/issues/1963#issuecomment-417796861) works around this and works fine in my environment. I'll keep on using it for a bit and update the code here if I run into issues.

**Comment by DeMoorJasper** [comment]
Ow yeah that makes sense, as it's a tree, it needs a root, which in this case is an empty bundle, as we have to have something to append the child bundles too.

This is definitely setup related, as a setup with only one entrypoint will have that as it's entrypoint instead of a virtual bundle.

**Comment by hirasso** [comment]
Thank you so much @DeMoorJasper for your encouraging support on this!! 🙏

So now I'm trying to put all this into a parcel-plugin. In the above code, I call `generateManifest` once after the initial build and then on every rebuild, since the 'bundled'-event doesn't seem to get fired on the first run:
```javascript
const bundler = new Bundler(files, options);
const bundle = await bundler.bundle();
// build the manifest once on initialization
generateManifest( bundler );
// rebuild the manifest on every change (watch mode)
bundler.on('bundled', () => generateManifest( bundler ) );
```
How would I do this from inside a plugin? Is there also an event for the first build? This fails:
```javascript
module.exports = function (bundler) {
  // build the manifest once on initialization
  // Throws error, since it's not bundled on initialization
  generateManifest( bundler );
  // rebuild the manifest on every change (watch mode)
  bundler.on('bundled', () => generateManifest( bundler ) );
};
```
Take your time, today is Sunday, after all :)

**Comment by hirasso** [comment]
Sorry for the last [deleted] comment, the 'bundled'-event works just fine from inside a parcel-plugin.

**Comment by DeMoorJasper** [comment]
@hirasso tests are usually a good idea. I personally don't do it untill other people actually start using it. Feel free to add this plugin to https://github.com/parcel-bundler/awesome-parcel

**Comment by DeMoorJasper** [comment]
Gonna close this issue as it has been resolved :)

**Comment by hirasso** [comment]
Yeah, I get it :) I started writing my first test, great fun! 
While doing that I realized that I can't rely on the `entryAsset` for my goal. I would really need to know what the hash of the bundle is. Would it be possible to add it as an entry to the bundle? For example:
```javascript
Bundle {
  type: 'css',
  name: './dist/app.cbac04c8.css',
  hash: 'cbac04c8', // this would finally solve all my problems I guess.
  plainName: 'app.css', // or even this ;)
  parentBundle: 
   Bundle {
     type: 'html',
     [...]
```

**Comment by hirasso** [comment]
...or I might even have found a bug? I keep on hanging on the fact that a `.scss` file imported in a `.js` file doesn't have an `entryAsset`...
