### ISSUE TITLE
Tree shaking disables source maps?

### ISSUE THREAD

**Issue by dcecile** [parcel-bundler/parcel#1966]
# ❔ Question

Is tree shaking supposed to disable source maps?

## 🔦 Context

I was setting up a new project and turned on tree shaking, and noticed source maps stopped getting generated. I didn't see anything in the [docs](https://parceljs.org/cli.html) or the [blog post](https://medium.com/@devongovett/parcel-v1-9-0-tree-shaking-2x-faster-watcher-and-more-87f2e1a70f79), so I figured I'd ask here.

History that I could find:

- [Bundler.js:129](https://github.com/parcel-bundler/parcel/blob/master/src/Bundler.js#L129) has mutual exclusion of tree shaking and source maps
- The tree shaking PR #1135 has a check mark for "Source map"
- Part of the same PR is 9bea36b32068122ff718ddfa481040947f1d0aa5, to "Disable source maps for now"

## 💻 Code Sample

```
parcel build --experimental-scope-hoisting main.js
ls dist
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 8.11.3
| npm/Yarn         | 1.9.4
| Operating System | Linux

**Comment by DeMoorJasper** [comment]
Yes, source maps in tree shaking is currently not supported

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
