### ISSUE TITLE
Wildcard import crush on MS Windows 

### ISSUE THREAD

**Issue by Akiyamka** [parcel-bundler/parcel#1967]
# 🐛 bug report
parcel crush when try build project with wildcard import on Windows

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```js
{
  "name": "hazard-report",
  "version": "1.0.0",
  "description": "page for hazard report",
  "main": "index.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "parcel index.html",
    "build": "parcel build index.html --out-dir public",
    "serve": "http-server ./public"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "vue": "^2.5.17"
  },
  "devDependencies": {
    "autoprefixer": "^9.1.3",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-1": "^6.24.1",
    "http-server": "^0.11.1",
    "parcel": "^1.9.7",
    "postcss-modules": "^1.3.2",
    "stylus": "^0.54.5"
  },
  "alias": {
    "vue": "./node_modules/vue/dist/vue.common.js"
  }
}
```
.babelrc.json
```js
{
    "presets": ["stage-1"]
}
```
.postcssrc.json
```js
{
  "modules": true,
  "plugins": {
    "autoprefixer": {
      "grid": false
    }
  }
}
```
## 🤔 Expected Behavior
It must not crush, as it happens on linux, or if i comment wildcard import on windows

## 😯 Current Behavior

Its crush after start
`parcel index.html`

```
Error: ENOENT: no such file or directory, open 'G:\git\hazard-brief\src\assets\images\icons\hazards\large\*.png'
```

## 💁 Possible Solution

No idea

## 💻 Code Sample
Just take windows 10 and try do something like this:
```
import images from '/images/*.png';
```
Then try build it.
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.9.7
| Node             | 7.9.0
| npm/Yarn         | npm 4.20
| Operating System | Windows 10 x64 Pro (1790)

**Comment by DeMoorJasper** [comment]
Fixed in #1965

Gonna close this for now as it's a known issue and a PR already exists
