### ISSUE TITLE
php file entry throws "require is not defined" in browser console

### ISSUE THREAD

**Issue by amerikan** [parcel-bundler/parcel#1970]
# 🐛 bug report
I have a .php file which currently has nothing but html content (later I plan on adding some actual php code). When I run `parcel watch index.php` (I'm running apache server, so I use watch command) and then I open the browser it throws a console error regarding `require` modules. If i remove the `require` line then it works fine.

## 🎛 Configuration (.babelrc, package.json, cli command)

I don't have any configurations, it's straight out of the box.

## 🤔 Expected Behavior

Should be able to call `const my = require('./my/module/path)` when using `parcel watch index.php` (php file entry)

## 😯 Current Behavior

Browser console throws: **ReferenceError: require is not defined**

## 💻 Code Sample

I have **index.php**

```html
<!DOCTYPE html>
<html>
<head>
	<title>Test</title>
	<link rel="stylesheet" type="text/css" href="node_modules/bootstrap/dist/css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="./app.css">
</head>
<body>
	<div class="container">
		<h1>Testing!</h1>
	</div>
	<script src="./index.js"></script>
</body>
</html>
```

**index.js**
```js
const say = require('./say');
say.name('gus');
```

**say.js**
```js
module.exports = {
	name: function (text) {
		
		console.log(text);
	}
}
```

## 🌍 Your Environment

Firefox 61.0.2
Chrome too

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | v10.9.0
| npm/Yarn         | npm 6.4.1
| Operating System | macOS High Sierra 10.13.6

**Comment by DeMoorJasper** [comment]
PHP is a server side language, we can not assume it is safe to transform it using html transforms

**Comment by amerikan** [comment]
@DeMoorJasper thanks for the quick response. I'm a bit confused then. 

Renaming it to .html won't be an option once I add actual php code. I see that you mentioned to use multiple entry points and to use php server. I am currently using a php server, that's why I was using `watch` command. How would having multiple entry points solve this?

**Comment by amerikan** [comment]
How can someone that is working on a PHP web app utilize ParcelJS? I tried googling around, but can't seem to find the answer.

**Comment by DeMoorJasper** [comment]
Using multiple entrypoints, see my comment above for the full explanation.

**Comment by amerikan** [comment]
Hmmm, ok I'm looking into it. 

Here's my last question, assuming I only have these two js files and nothing more in my project.

**index.js** (*note how it's using require to include say.js*)
```js
const say = require('./say');
say.name('gus');
```

**say.js**
```js
module.exports = {
	name: function (text) {
		
		console.log(text);
	}
}
```

If I run `parcel build index.js` and I link up the outputted file (`dist/index.js`) in my .php file like so `<script src="./dist/index.js"></script>`, would that bundle index.js AND say.js automatically for me and make `require` usage work?

**Comment by DeMoorJasper** [comment]
Yes, that's correct, that's what a bundler does.

**Comment by amerikan** [comment]
That's what I thought, but for some reason, even doing it that way I get an `require is not defined` error. When I use .html as entry point it works fine.

**Comment by DeMoorJasper** [comment]
Not sure why thats happening, could you create a reproducable example project

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by amerikan** [comment]
There was a typo. Thanks for the help.

**Comment by jesusorejarena** [comment]
Yo tenia el mismo problema, pero ya lo pude resolver, lo que hice fue lo siguiente:
Active el servidor de desarrollo de parceljs y luego active el XAMPP copie la URL del localhost de php y la pegue al fetch en js y en el archivo de php uno tiene que darle permisos para que puedan acceder al php por la URL del servidor de js, el código para los permisos en php en este `header('Access-Control-Allow-Origin: http://localhost:1234');` o en lugar de ese localhost puedes colocar un * para que pueda acceder desde cualquier URL o sea que sea publica
