### ISSUE TITLE
SASS imports

### ISSUE THREAD

**Issue by alexandernst** [parcel-bundler/parcel#1973]
I have been reading all the issues related to SASS imports from `node_modules`, and I'm a little bit confused.

Isn't parcel supposed to be a 0-config webpack replacement? Why do I need to create config files for SASS and include the `node_modules` folder in the included paths option? Why can't parcel do that for me?

**Comment by DeMoorJasper** [comment]
I'm a bit confused as what you mean? I'm pretty sure sass node imports work as expected out of the box?

**Comment by DeMoorJasper** [comment]
We overwrite the importer here: https://github.com/parcel-bundler/parcel/blob/master/src/assets/SASSAsset.js#L47

So anything that starts with a `~` and isn't followed with a `/` is considered a node module.

**Comment by alexandernst** [comment]
@DeMoorJasper I have a `my-styles.scss` file that I import from my `main.js`.

The `my-styles.scss` has a single `@import '~font-awesome/scss/font-awesome';`, which fails because parcel it not trying to import it from the `node_modules` folder.

**Comment by DeMoorJasper** [comment]
Than where is it importing it from, there are actual unit tests inside parcel that test if this is supported. So it is, it's not that it isn't trying to, it probably just fails.

font-awesome has some weird things in their code/file structure, which works in certain cases, but causes various issues in other cases.

Would love to help out if I have any error output or minimal reproducable example, because currently I don't really know how to help

**Comment by alexandernst** [comment]
I’ll be at home in 30 min and I’ll create a test case for the issue!

De: Jasper De Moor <notifications@github.com> <notifications@github.com>
Responder: parcel-bundler/parcel
<reply@reply.github.com>
<reply@reply.github.com>
Fecha: 1 de septiembre de 2018 at 21:07:08
Para: parcel-bundler/parcel <parcel@noreply.github.com>
<parcel@noreply.github.com>
CC: Alexander Nestorov <alexandernst@gmail.com> <alexandernst@gmail.com>,
Author <author@noreply.github.com> <author@noreply.github.com>
Asunto:  Re: [parcel-bundler/parcel] SASS imports (#1973)

Than where is it importing it from, there are actual unit tests inside

**Comment by alexandernst** [comment]
```
/Users/alexandernst/Proyectos/Playground/Vue_parcel_test/src/style.scss: Cannot resolve dependency '/Users/alexandernst/Proyectos/Playground/Vue_parcel_test/font-awesome/fonts/fontawesome-webfont.eot' at '/Users/alexandernst/Proyectos/Playground/Vue_parcel_test/font-awesome/fonts/fontawesome-webfont.eot'
    at Resolver.resolve (/Users/alexandernst/Proyectos/Playground/Vue_parcel_test/node_modules/parcel-bundler/src/Resolver.js:69:17)
```

Here you go, a simple test case. This is actually your own Vue example. 
The only thing that I added was the `font-awesome` package.

[Vue_parcel_test.zip](https://github.com/parcel-bundler/parcel/files/2342722/Vue_parcel_test.zip)

**Comment by DeMoorJasper** [comment]
You were just using an outdated version of Parcel, however there is a bug inside SASS that doesn't allow url imports relative to the sass file, so it fails to load things like fonts.

In version 1.9.6 parcel didn't have the `~` prefix for node modules, as that isn't really standard. It's just something someone thought was a good idea and everyone started adopting.

**Comment by alexandernst** [comment]
I don't understand. The version of `parcel-bundler` in my example is `1.9.6`. That is the latest version as of now.

**Comment by DeMoorJasper** [comment]
Latest is 1.9.7

**Comment by alexandernst** [comment]
Ok, I tried with `1.9.7` and now I get almost the same error:

```
/Users/alexandernst/Proyectos/Playground/Vue_parcel_test/src/style.scss: Cannot resolve dependency '/Users/alexandernst/Proyectos/Playground/Vue_parcel_test/font-awesome/fonts/fontawesome-webfont.woff2' at '/Users/alexandernst/Proyectos/Playground/Vue_parcel_test/font-awesome/fonts/fontawesome-webfont.woff2'
    at Resolver.resolve (/Users/alexandernst/Proyectos/Playground/Vue_parcel_test/node_modules/parcel-bundler/src/Resolver.js:69:17)```

**Comment by DeMoorJasper** [comment]
Yeah that's the url issue I mentioned.

**Comment by DeMoorJasper** [comment]
Related to this #1813

**Comment by alexandernst** [comment]
Oh, I see. So, is there an issue I can track? Is there a workaround? Because, that issue basically makes parcel unusable.

**Comment by DeMoorJasper** [comment]
Wait a sec, it uses a variable as path. I'll try get it to work

**Comment by DeMoorJasper** [comment]
It's mainly just an issue with multiple different kinds of import syntaxes combined, which cause issues

**Comment by alexandernst** [comment]
I can test your patch, if you get it working. And then I can report more issues related to the same problem (if I find any)

**Comment by DeMoorJasper** [comment]
This seems to work though: `$fa-font-path: '../node_modules/font-awesome/fonts';`

The resolver became one big mess thanks to someone introducing the weird `~some-module/...` syntax in css.

**Comment by alexandernst** [comment]
@DeMoorJasper that will work only for this particular case. Any library that is using relative imports and doesn't allow path prefixing (as font-awesome with the `$fa-font-path` in this case) will still be broken.

**Comment by DeMoorJasper** [comment]
I'm aware, it has been an issue for a little while.

Don't think it'll get fixed anytime soon.
It's highly dependent on whether the libraries implement something that properly supports it, in case of sass, this is called a `url loader` and they're working on designing the API for it.

Support for vanilla css is working pretty much perfectly (except for variables across multiple files). Anyone can contribute to Parcel, so if this really is such a big blocker anyone can dig into it, both by thinking about it theoretical in an issue or implementing it in a PR.

**Comment by alexandernst** [comment]
There are less than 300 LOC total. That shouldn't be hard to port to parcel. Does parcel support "loaders" of some sort?

**Comment by DeMoorJasper** [comment]
They have the same issues as our sass implementation, so I'm not sure why you'd want to do that.

Parcel has a plugin system, but it's very hacky. The sass loader equivalent, is just the sassAsset file in this repository.

Parcel 2 is an attempt to address the issue with Plugins (and some other things) being hacky and limited.

**Comment by alexandernst** [comment]
`They have the same issues as our sass implementation`

No, they don't. This exact same example works perfectly fine with webpack. And I'm not even talking about a recent version of webpack.

**Comment by DeMoorJasper** [comment]
Well this doesn't use relative url's...

That's the only thing that's broken inside parcel. (And parcel url's don't allow node_modules the same way as import yet. But that would be a couple line edit)
