### ISSUE TITLE
images from built-in styles do not appear

### ISSUE THREAD

**Issue by YuriFedorov** [parcel-bundler/parcel#1974]
# ❔ Question

Perhaps this issue will be immediately closed, as it probably duplicates [#1456](https://github.com/parcel-bundler/parcel/pull/1456).  But after reading the entire branch, I didn't understand how to enable inline style handling. 

Parcel is an excellent packer, but it is not so easy to start using it for a beginner...

## 🔦 Context

**The problem is as follows:** 
![2018-09-01_17-36-48](https://user-images.githubusercontent.com/33720649/44946938-0b782b00-ae0e-11e8-8f12-1a4baf3b0ef5.png)

I want to attach a background image for the site header inside the <style>tag. 
I've seen the message @devongovett , about that built-in styles are not analyzed.
![massage](https://user-images.githubusercontent.com/33720649/44946834-47aa8c00-ae0c-11e8-8af2-83769fac5e77.png)

How can I connect a background image inside index.html?
I know I can connect it to an external style.css, but I want to specify all styles of the first screen in index.html. external styles at me are connected through rel= "preload" and are applied after page rendering.

## 💻 Code Sample

**Configuration (package.json)**
```
  "scripts": {
    "start": "parcel src/index.html --open",
    "build": "parcel build src/index.html"
  }
```

**HTML**
```
<html>
  <head>
     <style>
        .header {
                background: url('../img/bg1920.jpg');
              }
     </style>
  </head>
  <body>
     <header class="header"></header>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 8.11.4
| Yarn         | v1.9.4
| Operating System | Win10

**Comment by DeMoorJasper** [comment]
This will be supported in the next release. See #1456

**Comment by YuriFedorov** [comment]
Excellently! 
I will look forward to the update))
When is the release planned?
