### ISSUE TITLE
Root path import

### ISSUE THREAD

**Issue by alexandernst** [parcel-bundler/parcel#1975]
The usual folder structure for a Vue project involves a `src` folder in which everything else is placed.

Let's say that my particular folder structure is as follows:

```
src/
    components/
        foo.vue
        bar.vue
    index.js
```

If I do an `import 'components/foo'` inside my `index.js`, I'd expect Parcel to understand that I refer to the `components` folder inside the root of my `src`, but currently that doesn't happen.

Is there a way I can tell Parcel to do so? If "yes", how?

**Comment by DeMoorJasper** [comment]
That's called aliasing.

pkg.json
```
"alias": {
  "components": "./src/components"
}
```

**Comment by alexandernst** [comment]
It's not working. Maybe the problem is that my files have the `.vue` extension, instead of `.js`?

**Comment by alexandernst** [comment]
Or maybe Parcel's resolver just doesn't know how to make alias replacement recursively?

**Comment by DeMoorJasper** [comment]
Should work https://github.com/parcel-bundler/parcel/pull/1506 not sure what you mean with recursively though

**Comment by alexandernst** [comment]
@DeMoorJasper I mean that a file with an aliased path imports another file, which on it's own has more aliased imports. Is that working?
