### ISSUE TITLE
Convention: How to name parcel plugin options in package.json?

### ISSUE THREAD

**Issue by hirasso** [parcel-bundler/parcel#1978]
# ❔ Question

I just wrote a parcel plugin to generate custom Modernizr builds: https://github.com/hirasso/parcel-plugin-modernizr

At the moment, options for the plugin can be set in `package.json` like so:

```json
"modernizr": {
  "classPrefix" : "",
  "options": [
    "setClasses",
    "addTest"
  ],
  "feature-detects": [
    "css/pointerevents", "touchevents", "history"
  ]
}
```
I'm unsure if this is the right approach – would it be better to call the options group `"parcel-modernizr"` or even put it inside a `"parcel"`-group, like so?

```json
"parcel": {
  "modernizr": {
    "classPrefix" : "",
    "options": [
      "setClasses",
      "addTest"
    ],
    "feature-detects": [
      "css/pointerevents", "touchevents", "history"
    ]
  }
}
```
Would be grateful for a suggestion.

**Comment by DeMoorJasper** [comment]
There is no parcel config, so the latter is definitely not possible. And allowing plugins to manipulate CLI flags isn't possible and probably not a good idea anyway

**Comment by devongovett** [comment]
Generally the convention is to create a config file for your plugin, eg
.modernizrrc.

**Comment by hirasso** [comment]
> Generally the convention is to create a config file for your plugin, eg .modernizrrc.

Ah, interesting. My personal preference is having all the settings in the `package.json`, so I have a "single source of truth" – that also worked fine with my other settings for built-in parcel packages:

```json
"sass": {
  "sourceMapEmbed": true
},
"babel": {
  "presets": [
    "env"
  ]
},
"postcss": {
  "plugins": {
    "autoprefixer": true
  }
}
```
I guess I'll just add the capability for having the options in a `.modernizrrc`, as well, with higher priority.
