### ISSUE TITLE
🐛 Uncaught Error: Cannot find module '[a number]'

### ISSUE THREAD

**Issue by rabbitmeow** [parcel-bundler/parcel#198]
**index.html
styles.css
main.js
style-for-main.css**

### in index.html:
`<link rel='stylesheet' href='styles.css'>`
`<script src='main.js'></script>`

### in main.js:
`
import './style-for-main.css'
`

**_throw an error in browser_**

**Comment by davidnagli** [comment]
Hi! Thanks for reporting this. 

Can you please provide the actual error that you’re seeing in the browser, as well as your Node and Parcel version numbers.

**Comment by davidnagli** [comment]
For future reference, please actually fill out the issue template :)

**Comment by rabbitmeow** [comment]
**In browser**
Uncaught Error: Cannot find module '4'
    at newRequire (6723a4dcfb94ab73680250feba38b07f.js:32)
    at localRequire (6723a4dcfb94ab73680250feba38b07f.js:38)
    at Object.require.5._css_loader (6723a4dcfb94ab73680250feba38b07f.js:70)
    at newRequire (6723a4dcfb94ab73680250feba38b07f.js:46)
    at localRequire (6723a4dcfb94ab73680250feba38b07f.js:38)
    at Object.require.3../style-for-main.css (6723a4dcfb94ab73680250feba38b07f.js:77)
    at newRequire (6723a4dcfb94ab73680250feba38b07f.js:46)
    at require.5._css_loader (6723a4dcfb94ab73680250feba38b07f.js:63)
    at 6723a4dcfb94ab73680250feba38b07f.js:68

**everything is well in node**

**Comment by rabbitmeow** [comment]
[bug.zip](https://github.com/parcel-bundler/parcel/files/1546635/bug.zip)

**Comment by rabbitmeow** [comment]
Even more, Parcel wouldn't update the files when I remove the `import './style-for-main.css';`
I have got to restart Parcel to resolve it.

**Comment by brandon93s** [comment]
@rabbitmeow do you mind providing your entire project directory? The attachment appears to be the `/dist` directory of your project.

**Comment by fearclear** [comment]
I've had this problem, too. But when I delete that **.cache** and restart, it's working.

**Comment by rabbitmeow** [comment]
I'm in class, talk to you guys later. 😅😅😅😭😭😭

**Comment by rabbitmeow** [comment]
![url-source-code](https://user-images.githubusercontent.com/20941062/33830038-87bc1f0e-dead-11e7-9a56-c55bd97bd14f.png)

**Comment by rabbitmeow** [comment]
![bug](https://user-images.githubusercontent.com/20941062/33830126-db6c69a6-dead-11e7-9cd9-25bfaaf16946.png)

**Comment by brandon93s** [comment]
@rabbitmeow closing for now. Feel free to re-open with your `src` directory if this remains an issue.
