### ISSUE TITLE
PostCSS module hash applied twice when loading CSS from relatively installed packages.

### ISSUE THREAD

**Issue by mikefarquhar** [parcel-bundler/parcel#1982]
# 🐛 bug report

When loading components from a locally installed package PostCSS module hashes are reapplied causing style to fail to be applied to components.

## 🎛 Configuration (.babelrc, package.json, cli command)

Two NPM packages, one parcel library of react components, one website. Component library installed to website through `npm install ../component-lib`

The components library has a postcssrc.js file with the following in it:
```js
module.exports = {
    modules: true
}
```

Building the components lib outputs a single lib.js and lib.css file to the dist folder.

## 🤔 Expected Behavior

When importing the CSS from the component library the CSS should remain unmodified, eg I should see the following:

```css
._pageHeader_k0260_1{background-color:#000;color:#fff}
```

## 😯 Current Behavior

When importing the CSS from the component library in the website project an additional second hash is added to the output CSS, eg:

```css
.__pageHeader_k0260_1_1540w_1{background-color:#000;color:#fff}
```

## 💁 Possible Solution

Not sure of a solution, but renaming the postcssrc.js file in the component-lib package before building the website package prevents the problem from occurring. This suggests the postcssrc file in the component-lib package is being read and applied to the already built css in the dist folder. Even if there are nesting rules for PostCSS config files (I don't know if there are) I would expect these to be ignored when importing from a package in the node_modules folder, even if that package is actually symlinked as is the case with relative package installs with NPM.

## 🔦 Context

I'm working on code that is quite locked down and we cannot push our code to NPM. We also don't have access to Git so relative installs on the local file system are the best we can do.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 8.11.2
| npm/Yarn         | npm
| Operating System | Windows 10

**Comment by gdenisov** [comment]
@mikefarquhar Did you every find a work around for this?

**Comment by mikefarquhar** [comment]
@gdenisov Not really. I set up a Verdaccio server and published only the built files to it. Ignoring the postcssrc file from the publish does the trick. The other option was to move back to Webpack but nobody was keen for that.
