### ISSUE TITLE
Dev Server Route

### ISSUE THREAD

**Issue by momosh** [parcel-bundler/parcel#1988]
Hey guys, just gotta say this before I go on to my question, I really enjoy using Parcel. So much that I've convinced my colleagues to use Parcel as our bundler of choice on a startup project that we have. Now I'm considering Parcel for my new side project and here is my concern. 
# ❔ Question
Is there a way to setup a route on dev server with custom handler? 

## 🔦 Context
Mainly this is the same functionality that Webpack provides with their dev server in a form of before function. 
`
//... 
devServer: {
  before: function (app) {
    app.get('/some/path', function (req, res) {
      res.json({ custom: 'response' })
    }) 
  } 
} 
`

**Comment by DeMoorJasper** [comment]
We do not, we do however have a middleware, which you could use to build your own server and have full control. We probably want to keep the server as lightweight as possible. The webpack one probably has way too much things going on.

https://en.parceljs.org/api.html#middleware

**Comment by momosh** [comment]
Thanks for a quick reply.
Yes, that's why I like using Parcel, for it's simplicity. And I've seen the section about middleware in docs, but I was wondering if I could use it this way. Anyway, thanks you for your time man.

I guess we can close this now.
