### ISSUE TITLE
Using babel-plugin-transform-class-properties error: Unsupported babel version: 5.8.3

### ISSUE THREAD

**Issue by ladz** [parcel-bundler/parcel#1991]
# 🐛 bug report

I'm working with an almost fresh parcel setup. I've added a .babelrc because I need babel-plugin-transform-class-properties:
```js
{
  "plugins": ["transform-class-properties"]
}
```
package.json
```js
...
  "devDependencies": {
    "babel-eslint": "^9.0.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "csscomb": "^4.2.0",
    "eslint": "^5.5.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-import-order-autofix": "^0.8.3",
    "husky": "^0.14.3",
    "lint-staged": "^7.2.2",
    "node-sass": "^4.9.3",
    "prettier": "^1.14.2"
  }
...
```
## 🤔 Expected Behavior

Parcel should work with babel-plugin-transform-class-properties.

## 😯 Current Behavior

When running with a basic example I get
```
 $ parcel index.html
Server running at http://localhost:1234 
 🚨  /Users/u/git/x/index.js: Unsupported babel version: 5.8.38
    at babelTransform (/Users/u/.config/yarn/global/node_modules/parcel-bundler/src/transforms/babel.
js:46:11)
```
After that I also tried "babel-preset-react" and "stage-0" - nothing worked - I'm getting the same error all the time. I cleared the cache with yarn and reinstalled the deps several times. Also using npm did not solve the problem. 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.9.7
| Node             | v10.9.0
| npm/Yarn         |1.9.4
| Operating System | macOS 10.13.6

Any ideas? Thanks for your help!

**Comment by DeMoorJasper** [comment]
Perhaps you have a global babel installed with version 5.8?

**Comment by ladz** [comment]
No global babel:
```
yarn global list

 info "gtop@0.1.5" has binaries:#######################################################---] 986/1018
    - gtop
 info "gzip-size-cli@3.0.0" has binaries:
    - gzip-size
 info "json-server@0.14.0" has binaries:
    - json-server
 info "json2yaml@1.1.0" has binaries:
    - json2yaml
    - jsontoyaml
    - jsontoyml
    - json2yml
 info "parcel-bundler@1.9.7" has binaries:
    - parcel
 info "prettier@1.14.2" has binaries:
    - prettier
 info "tern@0.22.0" has binaries:
    - tern
 info "vmd@1.33.1" has binaries:
    - vmd
 info "yaml2json@1.0.2" has binaries:
    - yaml2json
    - yamltojson
    - ymltojson
    - yml2json
 ✨  Done in 0.88s
```

**Comment by DeMoorJasper** [comment]
That's strange, it's definitely getting babel-core from somewhere, as parcel does not use an old version internally.

Installing babel-core 6.x as a devDep into the project would probably solve the issue.

**Comment by Pandazaur** [comment]
I had the same issue:

`npm i babel-core@6 --save-dev` fixed it

**Comment by ladz** [comment]
Sorry for the late response (vacation!) - installing babel-core 6.x fixed it, thanks!
