### ISSUE TITLE
babel-polyfill

### ISSUE THREAD

**Issue by AndreasSchouten** [parcel-bundler/parcel#1992]
I'm migrating a project from Webpack2 to Parcel-bundler.
On new Browsers all works fine, but unfortunately I have to support IE 11 as well.  

I import  

`import 'babel-polyfill';`

in the first line of my index.js.

But while loading the application I get:

`Object.create: Das Argument ist kein Objekt und ist nicht Null`
(Argument is neither an object or null.) 
at:

```
3470 var $create = function create(it, P) {
3471     return P === undefined ? _create(it) : $defineProperties(_create(it), P);
3472 };
```

Then I made for testin my own `Object.create` function and put it at the beginig in index.js.

```
if (!Object.create) {
    Object.create = function (O, Properties) {
        var obj;
        if (typeof O !== 'object' || O === null) {
            throw new TypeError('Not an Object or null.');
        }
        obj = new Object();
        obj.prototype = O;
        
        if (Properties !== undefined) {
            Object.defineProperties(obj, Properties);
        }
        return obj;
    };
}
```
 
I assumed now I would get my own `TypeError: 'Not an Object or null.'`. But I still get the old one.

Is it possible that the code which cause the error is before babel-polyfill is loaded?

| Parcel           | 1.9.7
| Node             |8.11.4
| npm/Yarn         | yarn 1.7
| Operating System | Windows
babel-polyfill 6.26.0

**Comment by DeMoorJasper** [comment]
Not sure why it isn't working had a similar issue a little while back and changing the import to: `import babelPolyfill from 'babel-polyfill';` fixed it. Still not sure why that worked though

**Comment by AndreasSchouten** [comment]
@DeMoorJasper Thanks for Your suggestion. But this makes no difference in my case.

**Comment by AndreasSchouten** [comment]
I found that an import of a third party package causes this error. (npm https which was last published 3 years ago. )
