### ISSUE TITLE
Cannot read property 'posthtml' of undefined

### ISSUE THREAD

**Issue by robdodson** [parcel-bundler/parcel#2]
Following the tutorial on https://parceljs.org/ I get the following error when I run `parcel index.html`.

```
❯ parcel index.html
Server running at http://localhost:1234
🚨  /Users/foo/Desktop/parcel-app/index.html: Cannot read property 'posthtml' of undefined
    at /Users/foo/.nvm/versions/node/v7.6.0/lib/node_modules/parcel-bundler/lib/transforms/posthtml.js:5:31
    at Generator.next (<anonymous>)
    at step (/Users/foo/.nvm/versions/node/v7.6.0/lib/node_modules/parcel-bundler/lib/transforms/posthtml.js:26:191)
    at /Users/foo/.nvm/versions/node/v7.6.0/lib/node_modules/parcel-bundler/lib/transforms/posthtml.js:26:437
    at /Users/foo/.nvm/versions/node/v7.6.0/lib/node_modules/parcel-bundler/lib/transforms/posthtml.js:26:99
    at getConfig (/Users/foo/.nvm/versions/node/v7.6.0/lib/node_modules/parcel-bundler/lib/transforms/posthtml.js:22:18)
    at /Users/foo/.nvm/versions/node/v7.6.0/lib/node_modules/parcel-bundler/lib/transforms/posthtml.js:35:24
    at Generator.next (<anonymous>)
    at step (/Users/foo/.nvm/versions/node/v7.6.0/lib/node_modules/parcel-bundler/lib/transforms/posthtml.js:26:191)
    at /Users/foo/.nvm/versions/node/v7.6.0/lib/node_modules/parcel-bundler/lib/transforms/posthtml.js:26:437
```

**Comment by devongovett** [comment]
Ah it's because there is no package.json in your project. I will fix.

**Comment by trafnar** [comment]
I ran into the same thing while following the getting started page.

I recommend making more explicit instructions on that page. I've submitted a PR with my suggestion for doing that. https://github.com/parcel-bundler/website/pull/4

**Comment by robdodson** [comment]
After adding a package.json I'm now hitting https://github.com/parcel-bundler/parcel/issues/1

Getting closer though! 😄

**Comment by devongovett** [comment]
Published v1.0.1 which should fix both issues.

**Comment by robdodson** [comment]
Just installed 1.0.1, now i'm getting: `Couldn't find preset "env" relative to directory "/Users/robdodson/.nvm/versions/node/v8.9.1/lib/node_modules/parcel-bundler/src"`

**Comment by devongovett** [comment]
blargh. did you create a `.babelrc` but forget to install `babel-preset-env` in your project?

**Comment by jaruesink** [comment]
Is that in the documentation somewhere?

**Comment by devongovett** [comment]
https://parceljs.org/transforms.html

**Comment by robdodson** [comment]
I just followed the tutorial on the front page, it didn't mention needing a `.babelrc` :)

**Comment by devongovett** [comment]
hmm, you shouldn't need a babelrc for that. I tried the code from the homepage just now and it seemed to work for me... i'll look into it more.

**Comment by Jayphen** [comment]
I have the same issue as above when following the getting started tutorial. The issue occurs when importing the css file.

**Comment by thomaslittle** [comment]
same issues here when attempting to import css or scss. `/usr/local/lib/node_modules/parcel-bundler/src/builtins/css-loader.js: Couldn't find preset "env" relative to directory "/usr/local/lib/node_modules/parcel-bundler/src"`

**Comment by devongovett** [comment]
These issues should both be fixed in v1.0.2.

**Comment by chriszrc** [comment]
Using 1.9.0, if the package.json isn't there, you get the error:

```
/Users/chrismarx/github/proj-catf-ticker/web/index.html: Cannot read property 'posthtml' of null
    at getConfig (/Users/chrismarx/.npm-global/lib/node_modules/parcel-bundler/src/transforms/posthtml.js:29:32)
    at <anonymous>
```

People/I should read the docs more carefully, but it might be nice to have a better error message here-

**Comment by chriszrc** [comment]
Using 1.9.0, if the package.json isn't there, you get the error:

```
/Users/chriszrc/github/proj-ticker/web/index.html: Cannot read property 'posthtml' of null
    at getConfig (/Users/chriszrc/.npm-global/lib/node_modules/parcel-bundler/src/transforms/posthtml.js:29:32)
    at <anonymous>
```

People/I should read the docs more carefully, but it might be nice to have a better error message here-
