### ISSUE TITLE
"Blazing fast" is improper grammar

### ISSUE THREAD

**Issue by skyzyx** [parcel-bundler/parcel#20]
This might feel pedantic — especially with how _awful_ most people are with this specific phrase — but it should be “_Blazingly_ fast”.

**Comment by robertleeplummerjr** [comment]
either way, fast is fast

**Comment by balanceiskey** [comment]
'Blazing fast' is appropriate for this particular type of speech (marketing, informal, etc.) and fine for colloquial English. -- https://english.stackexchange.com/questions/294817/why-are-both-blazing-or-blazingly-appropriate

**Comment by devongovett** [comment]
Thanks for the input guys. I'm gonna leave it for now. Despite potentially being incorrect, "Blazing fast" sounds better to me in this context.
