### ISSUE TITLE
Adopt browser field in package.json ala browserify

### ISSUE THREAD

**Issue by brianleroux** [parcel-bundler/parcel#200]
# 🙋 feature request

Adopt `browser` field in `package.json` ala browserify

### 🎛 Configuration`package.json`

Per https://github.com/browserify/browserify-handbook#browser-field

```js
{
  "name": "mypkg",
  "version": "1.2.3",
  "main": "main.js",
  "browser": {
    "fs": "level-fs-browser"
  }
}
```

### 🤔 Expected Behavior

Clone the browserify feature precisely. This will make SSR much easier to do. 

### 💚 Current Behavior
Current behavior defaults to assuming everything is being bundled for the browser only; allowing devs to opt into specific file cases makes it easier to support prerendering content for the browser.

**Comment by devongovett** [comment]
We use [browser-resolve](https://github.com/defunctzombie/node-browser-resolve) which is the same module browserify uses for resolving so it should already work. Is it not for you?

**Comment by brianleroux** [comment]
OMG, it does! I had the wrong paths DOH. 

So sorry for the noise!

**Comment by download13** [comment]
I think I might be having a problem with this feature.

I get the following error when trying to run a browser app that depends on Webtorrent.

```
Uncaught TypeError: net.createServer is not a function
    at new TCPPool (player.js:19968)
    at new WebTorrent (player.js:33083)
    at Object.parcelRequire.1.idb-chunk-store (player.js:33466)
    at newRequire (player.js:48)
    at parcelRequire.4 (player.js:75)
    at player.js:80

```

Webtorrent includes the node `net` package as part of [TCPPool](https://github.com/webtorrent/webtorrent/blob/master/lib/tcp-pool.js#L22), which is [supposed to be excluded for browser builds](https://github.com/webtorrent/webtorrent/blob/master/index.js#L22).

The [package.json file](https://github.com/webtorrent/webtorrent/blob/master/package.json#L12) appears to properly set `./lib/tcp-pool.js` to `false` using the `browser` property.

For some reason it tries to compile in the tcp-pool.js file even though [it shouldn't](https://github.com/webtorrent/webtorrent/blob/master/index.js#L113) if the import is set to `false` like it's supposed to be.

Does parcel support using `false` to disable packages as well as rename them?

**Comment by danmarshall** [comment]
@devongovett it appears that Parcel is no longer using [browser-resolve](https://github.com/defunctzombie/node-browser-resolve)? I am still experiencing this bug - on Windows. I have a [repo demonstrating the bug](https://github.com/danmarshall/parcel-browser-field).
