### ISSUE TITLE
dev-mode build & serve with dotnet core or iisexpress

### ISSUE THREAD

**Issue by cosmoKenney** [parcel-bundler/parcel#2005]
# ❔ Question

I want to serve my Parcel-built static files with either dotnet watch or iisexpress during development. I realize I can `parcel build` but I don't wan't minification during development. 
Does the `--no-minify` flag simply disable minification? Or does it also revert NODE_ENV back to default? 

## 🔦 Context

The main reason is that the apps will have their (C#) API hosted on the same base URI. I.e. I can fetch /api/something instead of having to run the api on a different port than the static files. 

And I actually need to produce three different builds. 
1. For local development in iis express with 
    1.a. no minification
    1.b. `NODE_ENV` not set or set to `development`
    1.c. custom `BUILD_ENVIRONMENT` global var set to `development` (enables different configuration properties to be set like where the IDP server is and fqdn of the API).
    1.d. source map style: `inline-source-map`
    1.e. HTTPS on (actually sometimes off, like for internal apps) for bundle references
2. For vsts automated build and auto ci/cd to a staging server at the datacenter:
    2.a. minification & maybe compression
    2.b. `NODE_ENV` set to `production`
    2.c. custom `BUILD_ENVIRONMENT` global var set to `staging`
    2.d. source map style: `source-map`
    2.e. HTTPS on for bundle references
3. For vsts automated build and ci/cd to a production server at the datacenter:
    3.a. minification and compression. 
    3.b. `NODE_ENV` set to `production`
    3.c. custom `BUILD_ENVIRONMENT` global var set to `production`
    3.d. source map style: `source-map`
    3.e. HTTPS on for bundle references

**Comment by DeMoorJasper** [comment]
You probably want ‘parcel watch ...’ which watches for changes without starting a server.

Build —no-minify will still set node_env to production unless you overwrite node_env to dev

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cosmoKenney** [comment]
Oh, sorry about that, I assumed watch was like others where it's serve + watch. How can I set a variable that is based on the build environment? It either needs to be injected into the window object or injected into the entry js in some way. I cannot rely on NODE_ENV since that only supports "development" and "production". I need a "staging" value for the QA build.

**Comment by DeMoorJasper** [comment]
NODE_ENV supports whatever you throw at it as far as I know

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cosmoKenney** [comment]
@DeMoorJasper 
I suppose i could swap .env files around with different npm scripts for development, staging and prod. 
The thing with NODE_ENV is that we want NODE_ENV="production" in the staging environment so that the vendor libraries get optimized and tested that way during QA functional testing.

**Comment by cosmoKenney** [comment]
Now I just have to figure out how to gzip the bundles.

**Comment by DeMoorJasper** [comment]
@cosmoKenney thats a server side optimisation ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DeMoorJasper** [comment]
Not sure if we should support that, decent webservers have the option to gzip before serving and obviously have caches and such to optimise this process that it's barely noticeable.

It would be possible in Parcel 2 to write a plugin for it, but don't see the value in it.

**Comment by cosmoKenney** [comment]
Thanks for the responses here. I just got into Parcel. And, I immediately found several things that require workarounds to get it to fit into our workflow. So I'll just stick with webpack for now since I know it. I'll come back around to parcel for my next project and see how it's going. I'm always looking for ways to make devops more simple.
