### ISSUE TITLE
Can parcel run multiple plugins aka frameworks easily?

### ISSUE THREAD

**Issue by gregbenner** [parcel-bundler/parcel#2006]
# ❔ Question

I searched through the issues and didn't see. Can parcel be used on a project that has multiple frameworks. Basically could I point one root and plugin to a folder that uses say React and another to Angular, maybe a third to Vue? It's not ideal but I inherited a project with a few different frameworks each needing a slightly different build system.

## 🔦 Context

Build a legacy project that uses Angular 1.x, Mithril (React like) and now Web components.
Each is separated by folder already.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by DeMoorJasper** [comment]
It should work fine, have done it before with react and Vue and it worked perfectly.

It's all just Javascript after all, the only conflicts you'll get are the ones between the frameworks. So it's not the best idea to combine them, but as long as you properly sandbox them in some way internally it should be fine.

**Comment by gregbenner** [comment]
Thank you that's perfect!
