### ISSUE TITLE
[Suggestion] Integrate WaffleBot into github workflow

### ISSUE THREAD

**Issue by peanutbother** [parcel-bundler/parcel#2008]
As the title states I would suggest to integrate WaffleBot to make issue- and project-planning-workflow easier and more automated.
This would help track issues to organize the upcomming features, enhancements, bug fixes and ETAs.
You can find more information about it there: https://waffle.io/features

Disclaimer: I'm not affiliated to waffle.io just a fan of this kind of integration

This is a suggestion and open for comments.

**Comment by DeMoorJasper** [comment]
I agree it would be amazing to have a better overview of progress and a certain level of automation.

Wafflebot seems very interesting.
