### ISSUE TITLE
Can I access bundled classes outside of the bundle?

### ISSUE THREAD

**Issue by iamgoodbytes** [parcel-bundler/parcel#2009]
# ❔ Question

I've bundled a couple of dependencies and classes and have a need to access one of those classes outside of the generated parcel bundle. Is that somehow possible? 

Unfortunately I'm forced to code up some functionality with inline javascript outside of the bundle where I need to instantiate a new Graph() (see context below)

## 🔦 Context

My app.js contains:

```
import Graph from "./components/graph";
let g = new Graph(); // works fine
```

I need to be able to do a `var g = new Graph()` outside of the bundled file (somewhere inline my html view), is that possible somehow? Thanks for helping me improve my understanding in parcel!

**Comment by Stradivario** [comment]
I am trying to understand but please specify what you are trying to say with "outside of the generated parcel bundle" you can `import` or `require` them what is your case ?

**Comment by Stradivario** [comment]
example would be:
`index.ts`
```typescript
export class Graph {
   myTestGraph() {}
}
```

```bash
parcel build ./index.ts --target node
```

you can use it as follows inside other file:
`otherfile.ts`
```typescript
import { Graph } from './index.ts';

const g = new Graph();
g.myTestGraph();
```

**Comment by iamgoodbytes** [comment]
@Stradivario thanks for the quick reply. 
What I mean is using the Graph() class e.g. in a test.html file with a `<script>`block, like so:

```
<html>
  <head>
    <script src="thebuild.js"></script>
    <script>
         var g = new Graph();
    </script>
  </head>
```

I know this is bad practice, but this is the case I need to work with for now.

**Comment by Stradivario** [comment]
I think you can do something like

`<html>
  <head>
    <script src="main.js"></script>
  </head>`

Main.js

`
import 'theBuild.js';

import * as build from 'theBuild';

const g =new build.Graph();


`

Please try and say what will happen just guessing.

Regards,
Kristiyan Tachev

**Comment by iamgoodbytes** [comment]
Thanks for you input. It was as simple as:

```
import { Graph } from "./components/graph";
window.Graph = Graph;
```
