### ISSUE TITLE
NODE_ENV=production warning when "parcel watch ..."

### ISSUE THREAD

**Issue by marek-hanzal** [parcel-bundler/parcel#2011]
# 💬 RFC

In short: when somehow environment variable `NODE_ENV` is set to `production`, command `parcel watch ...` builds the stuff and ends immediately which is quite strange behavior and it's not documented (or I've overlooked it :) ). Also when dev server is started, rebuilding is just done one time.

Proposal is to add this behavior to the doc (in some bold) or at least provide some warning in `watch` and `serve` command OR normalize behavior, thus `watch` will not be affected - it will still run, just it could build for the target environment (prod/dev/whatever/...)

## 🔦 Context

I've used Docker image which provides by default `NODE_ENV=production` and I was wondering, why parcel is not watching :).

## 💻 Examples

```
/frontend/client # npm run watch

> frontend@1.0.0 watch /frontend/client
> parcel watch -d public src/index.pug

🚨 Warning: NODE_ENV is set to production!

✨  Built in 168ms.

public/css.248f34a3.css    154.18 KB     95ms
public/js.79819611.map      12.99 KB      7ms
public/js.79819611.js       11.25 KB    123ms
public/css.9d99e4d2.js       4.52 KB    122ms
public/css.9d99e4d2.map      2.81 KB      7ms
public/index.html              441 B     11ms
/frontend/client #
```

**Comment by DeMoorJasper** [comment]
This should probably get fixed, parcel should not be affected by node env only the output should

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
