### ISSUE TITLE
Importing raw assets that are referenced elsewhere fails

### ISSUE THREAD

**Issue by TuurDutoit** [parcel-bundler/parcel#2012]
# 🐛 bug report

Importing a raw asset as a URL (in a JS bundle) fails if the asset is referenced in another file.  
Creating the bundle succeeds, but the browser console throws the following error when opening the page:

```
Uncaught (in promise) Error: Cannot find module 'assets/video/calm-sea.mp4'
```

## 🎛 Configuration (.babelrc, package.json, cli command)

I'm starting Parcel with the following command (as an NPM script):
```sh
parcel serve src/index.en.hbs
```

Using `parcel-plugin-handlebars2` to process the handlebars templates. I don't have a `.babelrc` file.

## 🤔 Expected Behavior

The URL of the raw asset is imported.

## 😯 Current Behavior

If the asset is referenced in another file (I only tested with HTML, though...), the import fails and throws the following error:

```
Uncaught Error: Cannot find module 'assets/video/calm-sea.mp4'
    at newRequire (reset.812fb50c.js:39)
    at newRequire (style.87d61b39.js:31)
    at newRequire (js.9968c145.js:31)
    at newRequire (js.9968c145.js:23)
    at localRequire (js.9968c145.js:54)
    at Object.eval (eval at hmrApply (reset.812fb50c.js:297), <anonymous>:21:16)
    at newRequire (js.9968c145.js:48)
    at hmrAccept (reset.812fb50c.js:328)
    at reset.812fb50c.js:214
    at Array.forEach (<anonymous>)
```

## 💁 Possible Solution

Possible workarounds:
* Reference the file *only* in the JS bundle
* Reference the file *only* outside the JS bundle
* Duplicate the file (may be served twice!)

## 🔦 Context

Specifically, I have a video in a directory with assets, which is referenced from my HTML page like so:
```html
<video class="bg__media js-bg" src="assets/video/calm-sea.mp4" muted autoplay loop />
```
In my JS, I have the following line:
```js
import video from '../assets/video/calm-sea.mp4';
```
... which produces the above error.

Removing the reference from the HTML file resolves the issue; removing it from the JS code works too, obviously; and copying the video to another destination or duplicating it (essentially creating 2 separate but identical assets) also resolves the issue.

## 💻 Code Sample

Repo with small example: https://github.com/TuurDutoit/parcel-bug-raw-assets

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 10.9.0
| npm/Yarn         | NPM 6.2.0
| Operating System | macOS High Sierra 10.13.6 (17G65)

**Comment by DeMoorJasper** [comment]
Pretty sure this has been reported before, this bug has been in Parcel for quite some time

**Comment by TuurDutoit** [comment]
I searched for relevant issues but didn't find any; maybe I missed it.
Anyway, is there any progress on a solution?

**Comment by DeMoorJasper** [comment]
Yeah it should have been fixed in the latest version
