### ISSUE TITLE
Option to apply transforms to third-party node_modules

### ISSUE THREAD

**Issue by taylorjdawson** [parcel-bundler/parcel#2013]
# 🙋 feature request

One feature that is seriously lacking is the ability to apply transforms to third-party node_modules. As [previously stated](https://github.com/parcel-bundler/parcel/issues/1632#issuecomment-420089662):

> This even works in third-party node_modules: if a configuration file is published as part of the package, the transform is automatically turned on for that module only. 
> &mdash; [Parcel Docs](https://parceljs.org/transforms.html)

It seems as if Parcel has the **ability** but not the option to achieve this. The [issue](#1632) has been discussed before, however, it did not apply to third-party node_modules.
It seems that I am [not alone...](https://github.com/parcel-bundler/parcel/issues/1655) ([& also](https://github.com/parcel-bundler/parcel/issues/13#issuecomment-351421471))

## 🤔 Expected Behavior
If specified, Parcel will apply transforms on the third party node_modules **before** bundling. 

## 😯 Current Behavior
Right now Parcel is unable to recognize the object spread operator in third-party node_modules because Parcel does not transform the third party node_module before bundling. Thus, when importing third party node_modules that do not have a `.babelrc` & they use the `...(obj)` operator then the build will fail:  
```bash
🚨  ../node_modules/ky/index.js:21:19: Unexpected token (21:19)
  19 |                          }
  20 |
> 21 |                          returnValue = {...returnValue, [key]: value};
     |                                         ^
  22 |                  }
  23 |          }
  24 |  }
```

## 💁 Possible Solution
CLI: 
`parcel build  index.js --include <3rd party module>`
API: 
```js
// Bundler options
const options = {
  transforms: [
    'node_module_a',
    'node_module_b',
  ]
}
```
Apply to all external modules:
```js
let ext_modules = Object.keys(require('./package.json').dependencies)
// Bundler options
const options = {
  transforms: ext_modules
}
```

## 🔦 Context

I am trying to use Parcel to build for `node` _and_ `browser`. 

## 💻 Examples

If a dev could point me in the right direction I could begin implementation immediately. Thank you.

**Comment by icopp** [comment]
I would find this extremely useful for the various packages out there that are ES6 but don't work with Parcel's default behavior, like [delay](https://github.com/sindresorhus/delay).

**Comment by taylorjdawson** [comment]
@DeMoorJasper Awesome! That is great to hear. When will 1.10 be released? Where is this `source` field? I don't see it in the docs. Thanks! 👍

**Comment by DeMoorJasper** [comment]
It's kinda documented here: https://github.com/parcel-bundler/parcel/pull/1101 But it never ended up in the docs, feel free to contribute it

**Comment by alidcastano** [comment]
@DeMoorJasper why was this closed? From what I could find, the source field only works for linked modules not third party modules

**Comment by davenquinn** [comment]
This is still a major problem!

I wasted more than two hours debugging UW-Macrostrat/ui-components#1 because the real issue was totally obscured by the inconsistency between symlinked and third-party modules: I repeatedly developed a working bundler strategy with an `npm link`ed version of my module, only to push to NPM and have ES6 code silently included in my browser app. For this workflow, the hard-coded differences in treatment of symlinked modules are counterproductive and unexpected.

**Comment by hanzhangyu** [comment]
The title of the issue is `Option to apply transforms to third-party node_modules`, it has not fixed. 🤔 Is there a solution.

**Comment by bjornhanson** [comment]
@DeMoorJasper or @taylorjdawson, can this be reopened?

**Comment by crtag** [comment]
@DeMoorJasper This is still not fixed, worth to reopen?

**Comment by Banou26** [comment]
To all the people asking for this to be re-opened, as the original post mentions, https://github.com/parcel-bundler/parcel/issues/1655 is opened and targets the same problem.

So you could just subscribe/follow what is happening in there instead, even if there's not much activity towards implementing this feature there either.
