### ISSUE TITLE
creating a production config

### ISSUE THREAD

**Issue by eranegozy** [parcel-bundler/parcel#2026]
# ❔ Question

I have what I am sure is a fairly common issue: I want to build my code for a production server (in my case S3-bucket static server), but I'd like to swap out or change a configuration which contains URLs, config options, etc... to a production version of the file in some kind of pre-build step.

Currently, I use this from my main js file: 
`import config  from '../config/config-dev.json';`

This is great because this config json file gets merged into the single js bundle file. But I want to do a production build that will effectively substitute in a different file (say `config-production.json`) as either part of the build or some pre-build step.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 8.3.0
| npm/Yarn         | npm 6.4.0
| Operating System | osx

**Comment by icopp** [comment]
Your best bet here for something future-proof would probably be to use `process.env` and dynamic `import()` statements (so you can put them in an if block), though you'd have to structure your code to handle the `Promise` return from the imports properly.

**Comment by eranegozy** [comment]
Oh. sorry if I was not clear. This is all front-end browser-only code. My understanding is that process.env is not available in the browser.

**Comment by DeMoorJasper** [comment]
@eranegozy parcel inlines environment variables if they’re used

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eranegozy** [comment]
oh cool. Can you point me to an example or docs of how to do this?

**Comment by eranegozy** [comment]
OK. I figured it out. Good article [here](https://golb.hplar.ch/2018/01/Bundling-web-applications-with-Parcel.html) about accessing env variables through process.env by using dotenv.
Thanks everyone.
