### ISSUE TITLE
Stylus + @import font = type error undefined

### ISSUE THREAD

**Issue by soywod** [parcel-bundler/parcel#2033]
# 🐛 bug report

Using Stylus and @import font via `url()` make the build fail.

## 🎛 Configuration (.babelrc, package.json, cli command)

```
parcel serve --no-hmr src/page/**/*
```

```json
{
  "dependencies": {
    "parcel-bundler": "^1.9.7"
  },
  "devDependencies": {
    "coffeescript": "^2.3.1",
    "postcss-modules": "^1.3.2",
    "pug": "^2.0.3",
    "stylus": "^0.54.5"
  },
  "scripts": {
    "prestart": "rm -rf dist/*",
    "start": "parcel server --no-hmr src/page/**/*"
  }
}
```

## 🤔 Expected Behavior

I should be able to import a font via `@import url(...)`.

## 😯 Current Behavior

I'm not able to import a font via `@import url(...)`. Here the full line: `@import url('https://fonts.googleapis.com/css?family=Poppins')`. I tried with `'`, `"`, even without any quote, same error:

```
/home/soywod/.../layout.styl: The "path" argument must be of type string. Received type undefine
The "path" argument must be of type string. Received type undefined
```

## 🔦 Context

Instead, I import my font with a `<link>` tag.

## 💻 Code Sample

`@import url('https://fonts.googleapis.com/css?family=Poppins')`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.9.7
| Node             |10.10.0
| npm/Yarn         |1.9.4
| Operating System |4.18.5-arch1-1-ARCH

**Comment by rohith** [comment]
So far I've identified the cause of error at `ImportVisitor.visitImport` & `CustomEvaluator.visitImport` methods. I'm trying to fix this bug but having trouble doing so. I'd really appreciate if someone could point me in right direction?

**Comment by juanmirocks** [comment]
I still experience the same issue **when importing any Google Font**.

Parcel version: `2.8.3`
Style: LESS (with default `transformer-less`)

I think, currently, this is the relevant code: 

* CSS: https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/stylus/src/StylusTransformer.js#L48-L57
* LESS: https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/less/src/LessTransformer.js#L72-L96
