### ISSUE TITLE
Parcel 1.9.5 and above doesn't work in Glitch.com

### ISSUE THREAD

**Issue by ghost** [parcel-bundler/parcel#2034]
### 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```js
{
  "name": "parcel-app",
  "version": "0.0.1",
  "scripts": {
    "start": "parcel serve index.html --port 3000"
  },
  "devDependencies": {
    "parcel-bundler": "1.9.4",
    "//": "If you update Parcel, it stops working"
  },
  "engines": {
    "node": "8.x"
  }
}
```

### 🤔 Expected Behavior

Parcel works.

### 😯 Current Behavior

Parcel doesn't work from version 1.9.5. If you try to change something it doesn't update.

### 💻 Code Sample

Video: https://www.useloom.com/share/bb04124d10bf47b3a7c0c977b416546a
Parcel 1.9.4 on Glitch: https://glitch.com/edit/#!/parcel1-9-4
Parcel 1.9.7 on Glitch: https://glitch.com/edit/#!/parcel1-9-7

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7 |
| Node             | 8.12.0 |
| Operating System | Glitch |

**Comment by ruslanegorov** [comment]
The issue persists in Parcel 1.10.1

**Comment by DeMoorJasper** [comment]
Not sure how to debug this, might be an issue with glitch

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by johnagan** [comment]
It's working for me:

```json
{
  "scripts": {
    "start": "parcel src/index.html --port $PORT"
  },
  "dependencies": {
    "parcel-bundler": "^1.10.3"
  }
}
```

**Comment by gcp** [comment]
In case someone else wants to use Parcel on glitch:

You need something like 
```
  "engines": {
    "node": "^16.x"
  },
```

in your ```package.json``` because the default 10.x series that's currently on glitch can't compile parcel v2.

This will then cause you to hit this Parcel bug: https://github.com/parcel-bundler/website/issues/1008

The workaround is in that Parcel ticket.
