### ISSUE TITLE
How can I concatenate and minify assets in an HTML file with Parcel?

### ISSUE THREAD

**Issue by gigo6000** [parcel-bundler/parcel#2037]
# ❔ Question

How can I concatenate and minify assets in an HTML file with Parcel?

## 🔦 Context
I'm trying to concatenate and minify all my javascript assets in my Wordpress blog with Parcel. My goal is to include all the javascript files in one file for performance reasons. I'm testing the option of having a dummy index.html with script tags pointing to the javascript files. But when I run: `parcel build index.html` I get all the assets in the dist folder in individual files, and not concatenated into one file as I expect.

## 💻 Code Sample
```
// index.html
<script src="wp-includes/js/jquery/jquery.js"></script>
<script src="wp-includes/js/jquery/jquery-migrate.min.js"></script>
<script src="wp-content/plugins/crayon-syntax-highlighter/js/min/crayon.min.js"></script>

// Running parcel build
parcel build index.html 
✨  Built in 1.18s.

dist/jquery.98100814.map                225.61 KB     84ms
dist/jquery.98100814.js                  95.96 KB     65ms
dist/crayon.min.0439f72c.map             47.41 KB     84ms
dist/jquery-migrate.min.6a158b8c.map     21.72 KB     84ms
dist/crayon.min.0439f72c.js              19.86 KB     31ms
dist/jquery-migrate.min.6a158b8c.js      10.75 KB     15ms
dist/index.html                             145 B    923ms

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | v10.10.0
| npm/Yarn         | 6.4.1
| Operating System | Ubuntu

**Comment by DeMoorJasper** [comment]
Create one js file that requires all the js files?

That should throw everything in one bundle, it won't have a huge performance impact though. It will even be worse for subsequent page-loads whenever the bundle changes.
Running your static files behind a fast cdn like cloudflare would probably be a better solution, as that would return the library bundles from cache instead of serving a new ginormous file every time you change the code.

**Comment by gigo6000** [comment]
@DeMoorJasper thanks, I'll try that. I'm already using Cloudfront, but I just want to try to lower the requests to see if I can get better performance. This files won't change much or anything at all, this are just plugin assets, it's basically a set and forget thing, I don't change my blog very often.
