### ISSUE TITLE
Vue error

### ISSUE THREAD

**Issue by Sjoerrdd** [parcel-bundler/parcel#2038]
# 🐛 bug report
I'm getting the following error:

```
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

(found in <Root>)
```

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```js
  "scripts": {
    "watch": "parcel watch js/app.js --out-dir ../priv/static/js"
  },
```

## 🤔 Expected Behavior
It should work

## 😯 Current Behavior
It doesn't work.
It returns the following error:

```
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.
(found in <Root>)
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | Latest |
| Node             | Latest |
| npm/Yarn         | Latest |
| Operating System | Windows 10 |

**Comment by DeMoorJasper** [comment]
Code samples would be helpfull as you’re probably doing something wrong or you’re running an outdated parcel

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by matngo** [comment]
Hey, I have the same error, with: 

| Software   | Version |
|------------|---------|
| Parcel     | 1.10.3  |
| Node       | 8.10.0  |
| npm        | 3.5.2   |
| babel-core | 6.26.3  |

## Code samples:

**index.html**

```html
<html>
	<head>
	</head>
	<body>
		<div id="app">
		</div>
		<script src='index.js'></script>
	</body>
</html>
```

**index.js**

```js

import Vue from 'vue'
import App from './src/App.vue'

const vm = new Vue({
  el: '#app',
  template: '<App/>',
  components: { App },
})
```

**src/App.vue**

```vue
<template>
  <p>
    {{ message }}
  </p>
</template>

<script>
export default {
  data () {
    return {
      message: 'hello world'
    }
  }
}
</script>
```

I "solved" it, changing index.js to:

**index.js**
```js
// import Vue from 'vue'
import Vue from 'vue/dist/vue.js'
import App from './src/App.vue'

const vm = new Vue({
	el: '#app',
	template: '<App/>',
	components: { App },
})
```

However, from the vue docs:

> Do NOT do import Vue from 'vue/dist/vue.js' - since some tools or 3rd party libraries may import vue as well, this may cause the app to load both the runtime and standalone builds at the same time and lead to errors.

Is there any other workarounds?

Thanks!

**Comment by Hammster** [comment]
@matngo @Sjoerrdd hi there, the runtime-only build requires a render functions to be given, your initial Vue instance has no render function instead you're defining a raw template. 

I explained how to do it in #2178

**Comment by matngo** [comment]
@Hammster Thanks for the answer, it worked perfectly for me!

**Comment by hay** [comment]
Another option is to directly include the version with the template compiler in your code like this:

`import Vue from 'vue/dist/vue.js';`
