### ISSUE TITLE
Tree shaking react-router-dom

### ISSUE THREAD

**Issue by hannupekka** [parcel-bundler/parcel#2039]
# 🐛 bug report

If I enable `--experimental-scope-hoisting` on my build, seems that when I import with:

```js
import { BrowserRouter as Router, Switch, Route } from 'react-router-dom';
```

everything resolves as `undefined`.

Example repo here: https://github.com/hannupekka/photogallery-example - build with `yarn build`

## 🎛 Configuration (.babelrc, package.json, cli command)

https://github.com/hannupekka/photogallery-example/blob/master/.babelrc
https://github.com/hannupekka/photogallery-example/blob/master/package.json

CLI command:
```js
parcel build src/index.html --experimental-scope-hoisting
```

## 🤔 Expected Behavior

Application should work

## 😯 Current Behavior

Everything from `react-router-dom` is `undefined`, resulting in https://reactjs.org/docs/error-decoder.html/?invariant=130&args[]=undefined&args[]=

## 💻 Code Sample

https://github.com/hannupekka/photogallery-example - build with `yarn build`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 9.0.0
| npm/Yarn         | 1.3.2
| Operating System | macOS 10.13.6

**Comment by mischnic** [comment]
I only get: "$WkSz$var$react_pose_1.default.div is not a function"

**Comment by mischnic** [comment]
Quite a strange bug you've discovered:

This
```js
import posed, { PoseGroup } from 'react-pose';

console.log(posed.div);
console.log(PoseGroup);
```
will log two functions when compiled without tree shaking but `posed.div` will be undefined if treeshaken. This only happens in Typescript. Rename `index.ts` to `index.js` and it works fine:
Minimum example: https://github.com/mischnic/photogallery-example

**Comment by mischnic** [comment]
@hannupekka Removing the module option in your tsconfig solves the issue
```diff
diff --git a/tsconfig.json b/tsconfig.json
index 68257ce..3a75a22 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -1,7 +1,6 @@
 {
   "compilerOptions": {
     "target": "es5",
-    "module": "commonjs",
     "strict": true,
     "jsx": "react",
     "noImplicitAny": true,
```


@devongovett  @DeMoorJasper How is the typescript `target` and `module` option being handled? Doesn't babel always run after Typescript, making these options irrelevant? In this case, Parcel needs the ES6 import syntax for scope hoisting *internally*.

**Comment by DeMoorJasper** [comment]
@mischnic pretty sure they don't have any effect as babel always runs afterwards
