### ISSUE TITLE
Tree shaking not working on a simple rollup module

### ISSUE THREAD

**Issue by sslotsky** [parcel-bundler/parcel#2043]
# 🐛 bug report

My problem is captured [in a simple repo](https://github.com/sslotsky/parcel-rollup-tree-shake) where the README describes what I'm experiencing. Maybe (hopefully) I'm reading the results wrong or overlooking something simple.

The repo contains a small rollup module and an example parcel app that imports functions from it. I'm using [parcel-bundle-visualizer](https://github.com/gregtillbrook/parcel-plugin-bundle-visualiser) to inspect my bundle. If I import nothing from the rollup module, then the module is not included in the bundle, as expected. However, if I import at least one function, it seems to include the whole module, as the module size is the same no matter how many functions I import.

## 🎛 Configuration (.babelrc, package.json, cli command)

This information should all be available in the repo.

## 🤔 Expected Behavior

The number of bytes contributed to the bundle by the rollup module should increase when more functions are imported, and decrease when fewer functions are imported.

## 😯 Current Behavior

The number of bytes contributed to the bundle by the rollup module remains constant when there is at least one function imported from the module.

## 🔦 Context

I am writing a package with rollup and I want to be sure that it tree-shakes correctly when bundled with both parcel and webpack (webpack _appears_ to be tree shaking correctly but the results aren't easy to read, working on that still). 

## 💻 Code Sample

[The repo is here](https://github.com/sslotsky/parcel-rollup-tree-shake). Below is the module produced by rollup:

```js
function bar() {
  return "bar";
}

function foo() {
  return "foo";
}

const quux = () => 'quux';

export { quux, bar, foo };
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 8.11.1
| npm/Yarn         | 5.6.0/1.9.4
| Operating System | Ubuntu 18.04.1

**Comment by ncknuna** [comment]
Any updates on this? I just ran into this too, but with a much larger (custom built) package where the lack of tree shaking is really bloating my bundle size...

**Comment by sslotsky** [comment]
None from me! I haven't tried anything since reporting this issue.

**Comment by B-Esmaili** [comment]
any update on this? I am using antd, but strangely enough i am not able to find a way to get these two (rollup & antd) working.event with `create-react-libary` zero config i import single button from `antd/es/button` but the bundle size is around 900 kb. weird!!.

**Comment by mischnic** [comment]
Two things:
- the bundle analyzer

**Comment by mischnic** [comment]
Two things:
- a optimization based on which imports are used would have only been applied with `--experimental-scope-hoisting`.
- Even with that enabled, the bundle analyzer wouldn't have shown the correct individual asset sizes after tree shaking.
