### ISSUE TITLE
CustomElements do not work because Parcel always transpiles to ES5 

### ISSUE THREAD

**Issue by bogdancondurache** [parcel-bundler/parcel#2044]
### 🐛 bug report

Parcel always transpiles to ES5, which does not allow to use custom elements. I want to define a custom element but I have the same error always: `index.js:5 Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.`
This problem seems to be because of the fact that custom Elements classes are needed to be run with `new` instead of the function-like call. After searching this issue, everybody recommended to keep the code to at least ES6 and not transpile to ES5, which could be possible with Babel by setting up a node version bigger that 6. I tried to set this from babel.config.js and with `browserlist`, but it still transpiles to ES5.

### 🎛 Configuration (babel.config.js, package.json, cli command)

babel.config.js:
```js
const presets = [
  ["flow", {
    targets: {
      node: "8"
    }
  }]
];

module.exports = { presets };
```
package.json:

```js
"browserlist": [
    "last 2 node versions"
  ]
```

command: `parcel src/index.html`

### 🤔 Expected Behavior

Code should have been ES6 and allow use for customElements

### 😯 Current Behavior

Even if different Babel settings were provided, Parcel always compiles the code to ES5 and new instances of classes are created using the function-like syntax.

### 🔦 Context

I want to define a basic custom element, like:
```js
class CustomButton extends HTMLElement {
    constructor() {
        super()
        console.log('I am here')
    }
}
customElements.define('soc-button', CustomButton)
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 10.11
| npm/Yarn         | 6.4.1 / 1.9.4
| Operating System | Mac OS 10.13.6

**Comment by Hoishin** [comment]
1. browser target config is done with `browserslist`, not `browserlist`
https://github.com/browserslist/browserslist#queries

2. You should probably target browsers instead of Node versions, for example
```
last 2 chrome versions
```

**Comment by bogdancondurache** [comment]
@Hoishin Thank you very much. Everywhere I saw node as recommended, because that will make babel transpile to ES6, but apparently you are right and that solved my issue. Thanks a lot!
