### ISSUE TITLE
Possibility of stripping the hash in filenames on buildEnd or the likes?

### ISSUE THREAD

**Issue by 23d1** [parcel-bundler/parcel#2050]
# ❔ Question

Is it possible to remove hashes on buildEnd, and if so, how would one go about it?
Is adding `"buildEnd": "unix command to strip characters between periods and a period"` (any help here much appreciated) to the `"scripts": {}` section sufficient? Can't seem to get it to work...

## 🔦 Context

For projects where it is not feasible updating html/twig-files across a range of folders above the JS/SCSS portion of the project. Very tedious to go in and replace hashes in the files after bulding (it's fine when watching, as the hashes don't change).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 10.11.0
| npm/Yarn         | 6.4.1
| Operating System | macOS 10.13.6

**Comment by Hoishin** [comment]
If "disable content hash" is what you want, there is this PR https://github.com/parcel-bundler/parcel/pull/1934

**Comment by 23d1** [comment]
Hmm. 

```error: unknown option `--no-content-hash'```

Even with 1.10.0-beta.1... Probably a user error on my part...

**Comment by Hoishin** [comment]
It is not merged yet

**Comment by 23d1** [comment]
Gotcha. So if I was instead to go the API route, where would I drop that js-file? I can't seem to find that info in the docs. I basically want to access this option, referenced [here](https://parceljs.org/api.html);  `contentHash: false`

**Comment by Hoishin** [comment]
If you use the API like the docs you referenced, just run the JavaScript file with `node`.

**Comment by 23d1** [comment]
Thanks!
