### ISSUE TITLE
Browser field gets resolved incorrectly

### ISSUE THREAD

**Issue by thsorens** [parcel-bundler/parcel#2054]
# 🙋 feature request

When using superagent, using import Request from 'superagent';  Parcel seems to pick whatever is in the lib/node folder. 

## 🤔 Expected Behavior

Default behaviour for webpack and browserify is to detect what to import, and targets the client.js file in lib/client.js

## 😯 Current Behavior
Parcel targets the lib/node folder, and exposes internal node functions to the client. Some calls fails because of that. (.on is not a function or similar node internal functions)

## 💁 Possible Solution
Use the same logic as webpack/browserify to detect what to fetch.

Current workaround is importing superagent/lib/client instead of just superagent

**Comment by DeMoorJasper** [comment]
The pkg.json would be a good starting point for us to debug this and a link to the pkg’s git repo would also help

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thsorens** [comment]
https://github.com/visionmedia/superagent

```JS
   import Request from 'superagent';
    
  const submitFile = (file) =>{
      const req = Request.post(absoluteUrl)
        .timeout(50000)
        .set('Accept', 'application/json';

      req.attach('file', file, file.name);
      req.end(err, res => {

       })

    }

```
https://github.com/visionmedia/superagent/blob/master/package.json


Tried to add some console.logs inside the imported module in node_modules/superagent, the one parcel imports is lib/node/index.js, which is intended for server-side use only. Most of it still works in parcel, since it doesnt use node-internals, but when trying to post a file, it will fail. 

Targeting lib/client.js works just fine. As stated in the feature request, webpack seems to figure out that it should use the client.js file somehow, since this was never a problem with webpack. 

According to superagent docs: 
```
Browser and node versions
SuperAgent has two implementations: one for web browsers (using XHR) 
and one for Node.JS (using core http module). 
By default Browserify and WebPack will pick the browser version.
```

**Comment by DeMoorJasper** [comment]
Tried to recreate the issue with https://github.com/parcel-bundler/parcel/pull/2067 but I failed to recreate it. Seems to work fine, you might be running an outdated Parcel version?

**Comment by thsorens** [comment]
Im running parcel-bundler: 1.9.7. I can see that 1.10.1 just got available, did that fix it?

**Comment by thsorens** [comment]
Also worth mentioning, it crashes runtime. It builds fine

**Comment by DeMoorJasper** [comment]
Yeah the test tests the resolver, which is responsible for selecting what file to use. Yes please try with 1.10.1

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thsorens** [comment]
1.10.1 seems to be breaking quite a bit? spread notation is not working without polyfilling it. I also got issues with async await functionality. I know its not related, but its hard to test the functionality when everything else is breaking ;)

**Comment by DeMoorJasper** [comment]
@thsorens if you're not using a babelrc file these might be babel issues. We switched to babel 7 in 1.10. Would be nice if you could create a seperate issue for that

**Comment by thsorens** [comment]
Oh!! that explains quite a bit! I tried to use babel-7 a while ago, but read somewhere here that it wouldnt be supported until v2 of parcel came out. So i will try to go back to babel 7 then :)
