### ISSUE TITLE
<svg><image xlink:href="myfile.svg" isn't detected...

### ISSUE THREAD

**Issue by maximelebreton** [parcel-bundler/parcel#2055]
Hello, and thanks for the amazing work!

In my `index.html` entry point, If i try to embed my external `.svg` like this, **it works**:

```html
<img src="myfile.svg" />
<!-- output: dist/myfile.123456789.svg" -->
```

but if i try to embed it [like this](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image), **it doesn't**:
```html
<svg>
  <image xlink:href="myfile.svg" />  	
</svg>
<!-- no output... -->
```

How can i solve this?

Thank you!

**Comment by DeMoorJasper** [comment]
This should be a fairly easy fix, it's just not part of the list of assets parcel needs to collect yet inside HTMLAsset.js

**Comment by sarashino** [comment]
I humbly suppose that `xlink` name space is no longer supported officially, and currently percel does not support `<image href=...>`.
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href
Thus it’ll better to href support of image tag in svg.
I guess just adding `'href': ['use', 'image'],` as 663e68e79e03537e289f589f04a8af4dedcad2f9 would works.
What say you @DeMoorJasper .
