### ISSUE TITLE
parcel build --no-content-hash <file>.html

### ISSUE THREAD

**Issue by 23d1** [parcel-bundler/parcel#2056]
# 🐛 bug report

`parcel build --no-content-hash <file>.html`
does nothing, just builds and hashes the files as usual.

It does work for .js files, but not .html files referencing js/scss etc...

## 🎛 Configuration (.babelrc, package.json, cli command)

`parcel build --no-content-hash index.html` or
`parcel build index.html --no-content-hash` still hashes the filenames.

## 🤔 Expected Behavior

Unless I'm way off, and this literally only applies to content within the files not being hashed—it should indeed build without hashes in the filenames... Right?

## 😯 Current Behavior

Hashes the output files...

## 💁 Possible Solution

?

## 🔦 Context

Would be an awesome feature for cases where the parcel part of a big php/twig project isn't feasible to potentially update hashed filenames across hundreds of files.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.0
| Node             | 8.12.0
| npm/Yarn         | 6.4.1/1.9.4
| Operating System | macOS 10.13.6

**Comment by devongovett** [comment]
Hashes will still be added to the files, but not **content** hashes. i.e. the hashes will not change every build based on the content. Instead, the hashes are based on the filename.

We cannot completely remove the hashes because the output directory structure is flattened. If we removed the hashes, there might be conflicting output file names.

**Comment by 23d1** [comment]
Gotcha, thanks! Wouldn't mind that feature, though. I suppose one could cook something up with `buildend` somehow...

**Comment by justingolden21** [comment]
> @devongovett Is it possible to retain original directory structure and filenames, without flattening and any hashes in filenames?
> 
> There were already issue #433 with PR #557, but they were both closed without support for that. Is there any chance this can be implemented now (maybe with some `--preserve-directory-structure` flag)?

@devongovett is this still being considered? This feature would be useful for making a PWA using parcel, for example.

Parcel is marketed as a no config, super simple bundler. Having an option to not change any file names seems very intuitive and simple, as well as useful.

Thanks in advance for considering 😄

**Comment by chenzx** [comment]
Parcel may generate different js files according to different target configs, but the problem is, when i add the generated files to git, will cause much replicated delete-add file actions, not good
