### ISSUE TITLE
babel-plugin-emotion not working in parcel v1.10

### ISSUE THREAD

**Issue by bogas04** [parcel-bundler/parcel#2060]
# 🐛 bug report

I upgraded my project to parcel v1.10 and now [`babel-plugin-emotion`](https://github.com/emotion-js/emotion/tree/master/packages/babel-plugin-emotion) is failing to load. It was working fine with previous version.

## 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc
```json
{
  "env": {
    "production": {
      "plugins": [["emotion", { "hoist": true }]]
    },
    "development": {
      "plugins": [
        ["emotion", { "sourceMap": true, "autoLabel": true }],
        "react-hot-loader/babel"
      ]
    }
  }
}
```

package.json
```json
{
  "dependencies": {
    "@reach/router": "^1.2.1",
    "contrast": "^1.0.1",
    "emotion": "^9.2.10",
    "file-saver": "^1.3.8",
    "jszip": "^3.1.5",
    "prettier": "^1.14.3",
    "prismjs": "^1.15.0",
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "react-emotion": "^9.2.10",
    "react-hot-loader": "^4.3.11",
    "react-icon-base": "^2.1.2",
    "react-icons": "^3.1.0",
    "react-monaco-editor": "^0.18.0",
    "uuid-js": "^0.7.5"
  },
  "devDependencies": {
    "@types/jest": "^23.3.2",
    "@types/jszip": "^3.1.4",
    "@types/react": "^16.4.14",
    "@types/react-dom": "^16.0.7",
    "@types/react-icons": "^2.2.6",
    "@types/uuid-js": "^0.7.1",
    "babel-plugin-emotion": "^9.2.10",
    "husky": "^1.0.0",
    "jest": "^23.6.0",
    "lint-staged": "^7.3.0",
    "parcel-bundler": "^1.10.0",
    "ts-jest": "^23.10.1",
    "tslint": "^5.11.0",
    "tslint-config-prettier": "^1.15.0",
    "tslint-react": "^3.6.0",
    "typescript": "^3.0.3"
  }
}
```
## 🤔 Expected Behavior

It should work as it used to.

## 😯 Current Behavior

<img width="932" alt="screen shot 2018-09-26 at 11 20 31 am" src="https://user-images.githubusercontent.com/6177621/46059746-3d1ab280-c17e-11e8-9be8-81bb412f385f.png">

## 💁 Possible Solution

I suspect it has to do with babel v7 upgrade maybe, as `babel-plugin-emotion` does depend on [`babel-core`](https://github.com/emotion-js/emotion/blob/master/packages/babel-plugin-emotion/package.json#L17). I'm not sure really. Maybe i've written `.babelrc` in a wrong way?

## 🔦 Context

Can't use `babel-plugin-emotion` coz of this.

## 💻 Code Sample

```ts
import styled from "react-emotion";

export default styled.input`
  font-size: 1em;
  border: none;
  outline: none;
  width: 100%;
  text-align: center;
  border-bottom: 1px solid transparent;

  &:focus {
    border-bottom-color: lightgrey;
  }
`;
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v1.10.0
| Node             | 8.9.4
| npm/Yarn         | 6.4.1
| Operating System | macOS High Seirra

**Comment by DeMoorJasper** [comment]
Parcel should automatically detect that the emotion plugin requires babel 6 if it's a dependency.

It might be a bug with the new config loader, although for babel 6 it should still be the same as it was before. Would be nice if you could debug this.

**Comment by jamaljoh91** [comment]
I think this is related to an issue I'm having as well. I'm using react-pose, but when trying to build the app on heroku gives me this error: /tmp/build_5e9c3eea9b9ac51843f7526380f1f098/node_modules/react-pose/lib/index.js:10:42: Cannot resolve dependency '@emotion/is-prop-valid'.   Not sure what the problem is with emotion/parcel.

**Comment by samvv** [comment]
Same issue here, though in my case I get the following error with the same configuration:

```
Uncaught Error: Component selectors can only be used in conjunction with babel-plugin-emotion
```

I have `babel-plugin-emotion` installed and enabled in `.babelrc`
