### ISSUE TITLE
Listen to all files option

### ISSUE THREAD

**Issue by FaBeyyy** [parcel-bundler/parcel#2064]
# 🙋 feature request

I have quite a few static files in my project including various html files I template via fetch but because they arent really part of the bundeling (I am using a self made static file resolver plugin for parcel)
changes dont trigger the parcel-bundler which means i have to restart the bundler each time I change something there.

Having an option that listens to all files/specific extensions in a folder or just globally in the project dir would be amazing.

**Comment by mischnic** [comment]
This doesn't really make sense with Parcel 2 because it's not just watching for file changes and then doing a full build every time.
