### ISSUE TITLE
Version 1.10.1 breaks absolute paths in typescript

### ISSUE THREAD

**Issue by iRoachie** [parcel-bundler/parcel#2068]
# 🐛 bug report
When updating to version 1.10.0 of parcel-bundler from 1.9.7, absolute paths in typescript are no longer working.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// package.json
{
  "name": "register",
  "version": "1.0.0",
  "main": "src/index.js",
  "private": true,
  "license": "MIT",
  "scripts": {
    "start": "parcel public/index.html",
    "build": "parcel build public/index.html",
    "lint": "tslint -c tslint.json --project tsconfig.json 'src/**/*.ts?(x)'",
    "precommit": "lint-staged"
  },
  "devDependencies": {
    "@types/react": "^16.4.14",
    "@types/react-document-title": "^2.0.3",
    "@types/react-dom": "^16.0.7",
    "@types/react-router-dom": "^4.3.1",
    "husky": "^0.14.3",
    "lint-staged": "^7.2.2",
    "parcel-bundler": "^1.10.1",
    "parcel-plugin-typescript": "^1.0.0",
    "prettier": "^1.14.2",
    "tslint": "^5.11.0",
    "tslint-config-airbnb": "^5.11.0",
    "tslint-config-prettier": "^1.15.0",
    "tslint-react": "^3.6.0",
    "typescript": "^3.0.3"
  },
  "dependencies": {
    "antd": "^3.9.2",
    "date-fns": "^1.29.0",
    "firebase": "^5.5.0",
    "react": "^16.5.1",
    "react-document-title": "^2.0.3",
    "react-dom": "^16.5.1",
    "react-router-dom": "^4.3.1",
    "styled-components": "^3.4.6"
  },
  "lint-staged": {
    "*.{ts,tsx}": [
      "tslint -c tslint.json --project tsconfig.json 'src/**/*.ts?(x)'",
      "git add"
    ]
  }
}

// tsconfig.json
{
  "compilerOptions": {
    "module": "esnext",
    "target": "es5",
    "lib": ["es7", "dom", "esnext.asynciterable"],
    "sourceMap": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "allowSyntheticDefaultImports": true,
    "skipLibCheck": true,
    "baseUrl": "src", // This is what allows the absolute paths to work
    "paths": {
      "@styled": ["utils/styled"]
    },
    "types": ["node"]
  }
}
```

#### Directory structure
<img width="389" alt="screen shot 2018-09-27 at 7 14 33 am" src="https://user-images.githubusercontent.com/5962998/46142454-064ba780-c225-11e8-8271-57ff446ac1fb.png">

## 🤔 Expected Behavior
When running `parcel index.html`, it should resolve the absolute paths and run the app. Since my `baseUrl` is set to `src` in tsconfig.json, then it should resolve the path as `src/config/firebase`

## 😯 Current Behavior
Parcel displays an error in which it's unable to resolve the path.
`register/src/index.tsx:5:7: Cannot resolve dependency 'config/firebase'`

## 💁 Possible Solution
Not sure what changes occurred in the 1.10.0 release, but the app was working fine using 1.9.4.
Remove my absolute path and use a relative path.

## 🔦 Context
It affects me as i'm no longer able to build my app. Here's link to source code https://github.com/iRoachie/register

## 💻 Code Sample

```tsx
// index.tsx
import React from 'react';
import ReactDOM from 'react-dom';
import 'antd/dist/antd.css';

import 'config/firebase';

import Shell from './containers/Shell';

ReactDOM.render(<Shell />, document.getElementById('root'));
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.10.1 |
| Node             | 8.11.4 |
| npm/Yarn         | yarn 1.9.4 |
| Operating System | mac os 10.14 |

**Comment by DeMoorJasper** [comment]
Not sure what would cause this as TS hasn't changed for about half a year.

**Comment by iRoachie** [comment]
Not sure, as you see in my package.json, I'm also using typescript 3^

**Comment by DeMoorJasper** [comment]
Did it work previous to 1.10?

**Comment by iRoachie** [comment]
Yea the project is currently on 1.9.7

**Comment by ThomasK33** [comment]
Same happens to me when switching from 1.9.7 to 1.10.1.

Yet I have an "@" character prepended to the paths, hence I got a different error message:
`Failed to install @src/[...]`

I'd assume that instead of trying to resolve the path, the bundler tries to install the missing dependency via yarn instead of resolving it.

**Comment by Penagwin** [comment]
I'm also getting the issue. I believe it has to do with a change to Resolver.js (Which one I'm not sure) between 1.9.7 and 1.10.1

**Comment by ThomasK33** [comment]
Hey @DeMoorJasper, any news on this issue?

**Comment by DeMoorJasper** [comment]
@ThomasK33 	Not sure, TS asset handling hasn't changed in 1.10, so it's not really easy to pinpoint it.

If anyone wants to dig into this, definitely feel free to do so.

**Comment by harry-sm** [comment]
@nnecec I think so too.

**Comment by DeMoorJasper** [comment]
@nnecec if this is truly a parcel-plugin-ts bug it’s probably a good idea to move it to that repo

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by devongovett** [comment]
cc. @fathyb any idea?

**Comment by bernatfortet** [comment]
Any update?

**Comment by joseluisq** [comment]
https://github.com/fathyb/parcel-plugin-typescript/issues/59 issue is freezed for long time.
