### ISSUE TITLE
parcel watch uses 100% when encountering a invalid symlink within the project directory (macOS)

### ISSUE THREAD

**Issue by scottaubrey** [parcel-bundler/parcel#2069]
# 🐛 bug report

parcel watch uses 100% when encountering a symlink posting to itself within the project directory (not an asset, but just lying around) on macOS.

Reproduced in new folder:
```bash
$ mkdir parcel-test
$ cd parcel-test/
$ echo  "<html>" > index.html
$ parcel watch index.html
✨  Built in 76ms.
^C
$ ln -s unknown unknown
$ parcel watch index.html
✨  Built in 49ms.
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ELOOP: too many symbolic links encountered, stat '/path/to/parcel-test/unknown'
Emitted 'error' event at:
    at FSWatcher._handleError (/usr/local/lib/node_modules/parcel-bundler/node_modules/chokidar/index.js:260:10)
    at FSWatcher.<anonymous> (/usr/local/lib/node_modules/parcel-bundler/node_modules/chokidar/lib/fsevents-handler.js:280:14)
    at fs.js:1581:23
    at FSReqWrap.oncomplete (fs.js:152:21)

[...repeats...]
```

## 🎛 Configuration (.babelrc, package.json, cli command)

None - see above reproduction.

## 🤔 Expected Behavior

Preferably to ignore the symlink, at the very least error and die. 

If this is a problem with a dependancy - handling errors better so not to cause 100% CPU.

## 😯 Current Behavior

Looping error message, 100% of a CPU consumed.

## 🔦 Context

I'm encountering this when using parcel watch on a PHP project, which has a dependancy deep in it's package dependancies (https://github.com/humbug/box if you're interested) using a symlink as part of it's test suite? (https://github.com/humbug/box/blob/master/fixtures/build/dir000/unknown).

This symlink (unknown) is not referenced as part of any frontend stuff, and the file is not changing. I assume the watcher is trying to traverse the higher parent directory for files to watch for events, and getting in a mess about the symlink. 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.1
| Node             | 10.9.0
| npm/Yarn         | 1.9.4
| Operating System | macOS 10.13.6

**Comment by DeMoorJasper** [comment]
It seems like a chokidar bug, as you can see in the stacktrace... Although we could ignore the bug it’s probably more an issue of chokidar should ignore that file/folder

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
