### ISSUE TITLE
templated images not included in dist

### ISSUE THREAD

**Issue by Kera** [parcel-bundler/parcel#2070]
# ❔ Question

I'm trying to bundle a Vue app with Parcel, and i'm noticing that templated images ( img src="{{ data.image_url }}"  ) aren't included in dist folder.
Is that because Parcel doesn't manage Vue templating rendering or i'm just missing something?

## 🔦 Context

When bundling image who had url provided by Vue's data got :
 "Error: ENOENT: no such file or directory, open '[...]/src/{{ images.logo }}'"

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 8.11.3
| npm/Yarn         | npm 6.4.1
| Operating System | ubuntu 16.04

**Comment by DeMoorJasper** [comment]
Would be cool if you gave some more context, as you explanation magically goes from `img src="{{ data.image_url }}"` to `'[...]/src/{{ images.logo }}'`

Parcel does not copy everything to dist, only the things it detects, so if this is dynamic content, you should probably switch to using a cdn (or manually copying using a pre/post-build script).

**Comment by Kera** [comment]
That's all i wanted to know. :) .
 Thanks.
