### ISSUE TITLE
Scope hoisting/tree shaking bug (--experimental-scope-hoisting)

### ISSUE THREAD

**Issue by sergey-shpak** [parcel-bundler/parcel#2084]
# 🐛 bug report

Bundle missing [pragma function](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx) used to transform jsx to vnodes.

## 🎛 Configuration (.babelrc, package.json, cli command)
`parcel build ./src/app.js --experimental-scope-hoisting --no-minify`

Default babel config

## 🤔 Expected Behavior

Pragma function is not tree shaked from source 

## 😯 Current Behavior
Pragma function removed from bundle

In my case: `Uncaught ReferenceError: h is not defined`
## 💁 Possible Solution

Pragma function imported to source, but the function invocation only occurs in the transpiled source
(after `babel-plugin-transform-react-jsx` transformations), as result pragma function invocations are not visible for tree shaking and they are removed.

## 💻 Code Sample

```javascript
import { h } from 'hyperapp';
export default <div>test</div>;
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel      | 1.10.1
| Node        | v8.9.4
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
> as result pragma function invocations are not visible for tree shaking

Tree shaking runs after the babel transformations.
