### ISSUE TITLE
Is there any way to use dynamic environment variables?

### ISSUE THREAD

**Issue by aneequrrehman** [parcel-bundler/parcel#2097]
We have many environments with same build definitions but different environment variables. We don't want to have multiple `.env` files into the source code as that would clutter up our solution with a lot of env files which are basically just for targeting various environments.

My question is there a way to inject environment variables dynamically after the build artifacts are prepared? We are using Azure app service (Linux), if that matters.

The way it's supported in node is we define some environment variables in azure app settings blade and those become available on `process.env` but this does not seem to be happening after parcel builds up the app.

Am I missing something? Maybe some alternative like `EnvironmentPlugin` (from webpack) in `Parcel`?

**Comment by mischnic** [comment]
So you want to run parcel like this?  `MY_VAR=abc parcel build index.html`
That should work

**Comment by avalanche1** [comment]
This doesn't seem to work with `parcel start`!
