### ISSUE TITLE
pug file changes do not trigger a refresh

### ISSUE THREAD

**Issue by waynehoover** [parcel-bundler/parcel#2098]
# 🐛 bug report

When editing a pug file, auto refresh of the browser HTML does not happen, though JS HMR does seem to work.

## 🎛 Configuration (.babelrc, package.json, cli command)

Stock configuration

## 🤔 Expected Behavior

When I edit a pug file and save it the browser automatically refreshes with the new html.

## 😯 Current Behavior

When I edit a pug file I have to manually refresh the browser to see the new html.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.10.1
| Node             |  10.10.0
| Yarn         | 1.7.0
| Operating System | macOS 10.14

**Comment by DeMoorJasper** [comment]
Fixed by #2091
