### ISSUE TITLE
How do I include robots.txt / humans.txt in the build?

### ISSUE THREAD

**Issue by samuelgozi** [parcel-bundler/parcel#2099]
# ❔ Question

How do I include robots.txt/humans.txt in the build?
I assume that it's not necessary to explain why this is important.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.1
| Node             |10.11.0
| npm/Yarn         |1.10.1
| Operating System | MacOS Mojave

**Comment by jesnil01** [comment]
Why so you need parcel for this? You can just copy over your static files into your dist folder if you need them there.

**Comment by samuelgozi** [comment]
> Why so you need parcel for this? You can just copy over your static files into your dist folder if you need them there.

Because parcel is an automating tool, your argument can be applied to any parcel feature.
Also, I don't want to need to explain to people working on the project that in order for it to be ready for deployment they need to manually copy files to the dist folder after successfully "building" it.

**Comment by jesnil01** [comment]
Parcel is a bundler and you should not have to bundle these kind of files. 
And you don't have to copy it manually, make a script that you run after your build has finished.

**Comment by samuelgozi** [comment]
> Parcel is a bundler and you should not have to bundle these kind of files.
> And you don't have to copy it manually, make a script that you run after your build has finished.

I strongly disagree, if it was only a bundler then it shouldn't process static files like images, fonts, json files etc. It is supposed to bundle code and static assets(as stated in the website), and I think that it is pretty clear that its goal is to replace Webpack, Browserfy and the rest.

I understand that there might be tasks that parcel should not be doing, but I don't think that copying robots.txt and human.txt one of those tasks, I don't see how this is different from webmanifest or favicons other than the fact that I don't know of a meta tag to include them in the HTML file..

**Comment by ManzDev** [comment]
Maybe make a parcel-plugin for this? I think that would be interesant.

Parcel could check robots.txt and delete comments, minify or check (lint) syntax for avoid crawler problems.

**Comment by samuelgozi** [comment]
> Maybe make a parcel-plugin for this? I think that would be interesant.
> 
> Parcel could check robots.txt and delete comments, minify or check (lint) syntax for avoid crawler problems.

Im making one right now, but I might take it a step further and just create a plugin for copying files.
I know that a plugin already exists for copying files, but I would like to learn how to build a plugin anyways.

**Comment by icopp** [comment]
Including static files in general is common enough that I feel like the Parcel team should really maintain an official plugin to do this in 2.0 (they may have already been planning that, I dunno).

A `robots.txt`-specific plugin with the above functionality would be neat, though.

**Comment by samuelgozi** [comment]
> Including static files in general is common enough that I feel like the Parcel team should really maintain an official plugin to do this in 2.0 (they may have already been planning that, I dunno).
> 
> A `robots.txt`-specific plugin with the above functionality would be neat, though.

I submitted a feature request for that a while ago, I don't know if it's going anywhere, I hope it does.
I have a question about the robots.txt/humans.txt plugin, other than copying it, is there really a need to remove any comments from it? I mean, after all, only crawlers download it.

**Comment by ManzDev** [comment]
> I have a question about the robots.txt/humans.txt plugin, other than copying it, is there really a need to remove any comments from it? I mean, after all, only crawlers download it.

Not necessarily.

Maybe, best feature would be to review robots.txt syntax. Sometimes, mistakes are often serious about SEO.

**Comment by llarquere** [comment]
waiting for a plugin ...
inserting '<link rel="robot" href="/robots.txt">'
into the <head> of index.html
does the job

**Comment by caffeinum** [comment]
+1

Also, a `CNAME` files for a github pages builds fits this issue

**Comment by iainreid820** [comment]
I'd also like to chime in and say that this would be a really welcomed feature, but regarding the `CNAME` support, there could be a bug.

I'm using Parcel to bundle a GitHub pages site at the moment, and whilst it does a fantastic job with the HTML, JS, CSS, etc, the `CNAME` file is copied incorrectly, as it adds a trailing `.` to the file name

```
$ parcel build index.html CNAME
$ ls -1 dist
app.2137714b.js
app.2137714b.js.map
app.868b5728.css
app.868b5728.css.map
CNAME.
favicon.219d5973.png
index.html
```

**Comment by lukepighetti** [comment]
I think Parcel should support a generic entrypoint file, where you simply list all of the files you'd like to be bundled.

this `index.parcel` file might look like this

```
index.html
robots.txt
CNAME
```

**Comment by kevincox** [comment]
Another reason to do this in the bundler is it makes the dev server return the files. Even if they don't need bundling it is nice to have everything there.

**Comment by filips123** [comment]
Is there any update? I have a similar problem because I want to include/copy some files that aren't included by entry HTML or any other file but still needed for website to function properly.

The only difference, which actually makes things more difficult, is that those files are JSON, so I also can't just include them as additional entrypoints because JSON files will be converted to JS files. Solution for this would be to allow plugins to "force" including some files, even if they aren't included by other files, and also filename-based plugins/transformers/packages that are able to overwrite generic extension-based ones.

**Comment by mischnic** [comment]
>  I also can't just include them as additional entrypoints because JSON files will be converted to JS files

I have an implementation for that already, I hope it will be fixed for Parcel 2 in the near future.

**Comment by alsoknownasdrew** [comment]
Any updates on this?

**Comment by joshbedo** [comment]
Anyone have a solution for exposing robots.txt and sitemap.xml? This is super important for SEO and I don't see an easy way to do this with Parcel, React, and Netlify.

**Comment by caffeinum** [comment]
@joshbedo sounds like a semioptimal solution, what I did is added a build step which copies the file: `cp robots.txt dist/robots.txt`

**Comment by joshbedo** [comment]
Yeah build doesn't delete and rebuild all files each time only files that need rebuilt so it works fine. No need to copy it over each time when it never changes.

**Comment by DaniyelMe** [comment]
There is a parcel plugin for that:
[parcel-plugin-static-files-copy](https://www.npmjs.com/package/parcel-plugin-static-files-copy)
Install it:
`yarn add parcel-plugin-static-files-copy --dev`
Or
`npm install -D parcel-plugin-static-files-copy`
Then, in `package.json`, add:
```
"staticFiles": {
   "staticPath": ["path/to/robots.txt", "path/to/humans.txt"]
}
```
It should copy your files to the public folder.

**Comment by Dunks1980** [comment]
I use this for doing it:
build_task.js:
```
const fs = require('fs');
const execSync = require('child_process').execSync;

// run the parcel scripts
let parcel_script = 'parcel build src/index.html --no-content-hash --no-source-maps';
console.log(execSync(parcel_script, {encoding: 'utf8'}));

execSync("cp src/robots.txt dist/robots.txt", {encoding: 'utf8'});
console.log("dist\\robots.txt added\n");
```
package.json:
```
  "scripts": {
    "serve": "parcel src/index.html",
    "build": "node scripts/build_task.js"
  },
```

**Comment by Dunks1980** [comment]
Also, adding them in my index.html adds them in the output dir , for me.
```html
  <a style="display: none" href="/robots.txt" aria-label="robots"></a>
  <a style="display: none" href="/humans.txt" aria-label="humans"></a>
</body>
```

**Comment by vcarel** [comment]
> yarn add parcel-plugin-static-files-copy --dev

Use this one for Parcel 2: https://github.com/elwin013/parcel-reporter-static-files-copy

**Comment by realAyinde** [comment]
Have 

> Also, adding them in my index.html adds them in the output dir , for me.
> 
> ```
>   <a style="display: none" href="/robots.txt" aria-label="robots"></a>
>   <a style="display: none" href="/humans.txt" aria-label="humans"></a>
> </body>
> ```

**Comment by realAyinde** [comment]
> Also, adding them in my index.html adds them in the output dir , for me.
> 
> ```
>   <a style="display: none" href="/robots.txt" aria-label="robots"></a>
>   <a style="display: none" href="/humans.txt" aria-label="humans"></a>
> </body>
> ```

**Comment by realAyinde** [comment]
> Also, adding them in my index.html adds them in the output dir , for me.
> 
> ```
>   <a style="display: none" href="/robots.txt" aria-label="robots"></a>
>   <a style="display: none" href="/humans.txt" aria-label="humans"></a>
> </body>
> ```

I love this, its a good trick, is there anybody working on this issue

**Comment by sdavids** [comment]
This should be part of Parcel.

* robots.txt
* humans.txt
* sitemap.xml
* [.well-known](https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml) files
* favicon.ico (currently only included if ` <link rel="icon" href="favicon.ico" type="image/x-icon"/>` is in the entrypoint; having the link is not mandatory)

are just some commonly used files.

As this issue shows the demand is there.

At least 4 plugins of varying quality have been created:

* [parcel-plugin-custom-dist-structure](https://github.com/VladimirMikulic/parcel-plugin-custom-dist-structure)
* [parcel-plugin-structurize](https://github.com/samrith-s/parcel-plugin-structurize)
* [parcel-namer-rewrite](https://github.com/ol-loginov/parcel-namer-rewrite)
* [parcel-plugin-static-files-copy](https://www.npmjs.com/package/parcel-plugin-static-files-copy)

## Proposal

### file glob

`file glob` => Destination directory

#### Examples

rule: `asset/**/*.txt` => `""` (relative path); alternatively `"."` if `""` looks weird

`asset/a.txt` => `dist/asset/a.txt`; `<a href=asset/a.txt>`
`asset/a/b.txt` => `dist/asset/a/b.txt`; `<a href=asset/a/b.txt>`

rule: `asset/**/*.txt` => `"/"` (absolute URL path)

`asset/a.txt` => `dist/asset/a.txt`; `<a href=/asset/a.txt>`
`asset/a/b.txt` => `dist/asset/a/b.txt`; `<a href=/asset/a/b.txt>`

rule: `asset/**/*.txt` => `"x/y"` (relative URL path)

`asset/a.txt` => `dist/x/y/asset/a.txt`; `<a href=x/y/asset/a.txt>`
`asset/a/b.txt` => `dist/x/y/asset/a/b.txt`; `<a href=x/y/asset/a/b.txt>`

rule: `asset/**/*.txt` => `"x/y/"` (relative URL path)

`asset/a.txt` => `dist/x/y/asset/a.txt`; `<a href=x/y/asset/a.txt>`
`asset/a/b.txt` => `dist/x/y/asset/a/b.txt`; `<a href=x/y/asset/a/b.txt>`

rule: `asset/**/*.txt` => `"/x/y"` (absolute URL path)

`asset/a.txt` => `dist/x/y/asset/a.txt`; `<a href=/x/y/asset/a.txt>`
`asset/a/b.txt` => `dist/x/y/asset/a/b.txt`; `<a href=/x/y/asset/a/b.txt>`

Every rule could also have a `shouldHash` flag.

rule: `asset/**/*.txt` => `''` (relative path) and`"shouldHash": true`

`asset/a.txt` => `dist/asset/a.txt`; `<a href=asset/a.4a3e8342.txt>`
`asset/a/b.txt` => `dist/asset/a/b.txt`; `<a href=asset/a/b.7812d31b.txt>`

Also `stripPath`:

rule: `asset/**/*.txt` => `''` (relative path) and `"stripPath": true`

`asset/a.txt` => `dist/a.txt`; `<a href=a.txt>`
`asset/a/b.txt` => `dist/b.txt`; `<a href=b.txt>`
`asset/a/b/c.txt` => `dist/c.txt`; `<a href=c.txt>`

Also `stripPrefix`:

rule: `asset/**/*.txt` => `''` (relative path) and `"stripPrefix": "asset/"`

`asset/a.txt` => `dist/a.txt`; `<a href=a.txt>`
`asset/a/b.txt` => `dist/a/b.txt`; `<a href=a/b.txt>`

Complete example:

.parcelrc
```json
{
  "extends": "@parcel/config-default",
  "staticFiles": {
    "robots.txt": "",
    "meow.wav": "files",
    "src/sitemap.xml": {
      "destination": "",
      "stripPrefix": "src/"
    },
    "src/well-known/**/*": {
      "destination": ".well-known",
      "stripPath": true
    },
    "src/**/*.mp3": {
      "destination": "files",
      "stripPrefix": "src/",
      "shouldHash": true
    }
  }
}
```

With the input:

```
.
├── meow.wav
├── robots.txt
└── src
    ├── other
    │   └── pong.mp3
    ├── ping.mp3
    ├── sitemap.xml
    └── well-known
        ├── openid-configuration
        └── sub
            └── oauth-authorization-server
```

Output:

```
.
├── dist
│   ├── .well-known
│   │   ├── oauth-authorization-server
│   │   └── openid-configuration
│   ├── files
│   │   ├── meow.wav
│   │   ├── other
│   │   │   └── pong.fa3e834e.mp3
│   │   └── ping.181fd313.mp3
│   ├── robots.txt
│   └── sitemap.xml
├── meow.wav
├── robots.txt
└── src
    ├── other
    │   └── pong.mp3
    ├── ping.mp3
    ├── sitemap.xml
    └── well-known
        ├── openid-configuration
        └── sub
            └── oauth-authorization-server
```
