### ISSUE TITLE
How do I update public URL?

### ISSUE THREAD

**Issue by CentaurWarchief** [parcel-bundler/parcel#21]
Heyo. I've seen the flag `--public-url` but not exactly sure how it behaves. I am trying to `--public-url=.` and I've also tried `--public-url=http://localhost:8080`.

It would be nice if I could just modify it. Especially for cases where I'd throw everything that's on `dist` in a S3 bucket with static hosting enabled. Does that make sense? am I misunderstanding something?

Thanks! Very nice stuff, tho!

❤️

**Comment by micopc** [comment]
Hi, I think this has to do with the fact that the flag is --public-url which translates to publicUrl but the code in the method normalizeOptions of the Bundler class searches for options.publicURL. I can do a pull request but I just have one doubt: would it be better to rename every instance of it to publicUrl or just change it on normalizeOptions to something like `const publicURL = options.publicUrl`?

**Comment by devongovett** [comment]
maybe normalizeOptions could support both `publicUrl` and `publicURL`?

**Comment by lostintangent** [comment]
I just ran into this same issue and was about to send out a PR, but I'll let @micopc take care of it :) @devongovett thanks for this awesome tool!
