### ISSUE TITLE
Loading .env file using node API?

### ISSUE THREAD

**Issue by HauntedSmores** [parcel-bundler/parcel#2101]
# ❔ Question

Hey guys. Im having a hard time getting `.env` file to work. I have one setup at the root of my directory with one entry to test: `API=1234`

Im using parcel's node api to be used in a gulp task. It's supposed to load the `process.env` by default with no config. Here's my parcel function:

```
const entry_file = path.join(__dirname, './src/scripts/main.js');

function parcel(done) {
    // Bundler options
    let parcel_options = {
        outDir: './assets',
        logLevel: 3,
        sourceMaps: true,
    };

    const bundler = new Bundler(entry_file, parcel_options);
    bundler.bundle().then(() => done());
}
```

`process.env` is showing up as undefined in the console

Does `.env` not work when used outside of the CLI?

## 🔦 Context

Trying to load environment variables into process.env using parcel within my gulp tasks.

## 💻 Code Sample
```
const entry_file = path.join(__dirname, './src/scripts/main.js');

function parcel(done) {
    // Bundler options
    let parcel_options = {
        outDir: './assets',
        logLevel: 3,
        sourceMaps: true,
    };

    const bundler = new Bundler(entry_file, parcel_options);
    bundler.bundle().then(() => done());
}
```
`console.log(process.env) // Output: {}`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.10.1
| Node             |  8.9.3
| npm/Yarn         |  npm v6.1.0
| Operating System | win10

**Comment by OKNoah** [comment]
Can you use [dotenv](https://www.npmjs.com/package/dotenv)? Then run `node -r dotenv/config your-index.js`. Or `require('dotenv').config()` at the top of your entry file.

**Comment by tadahh** [comment]
> Can you use [dotenv](https://www.npmjs.com/package/dotenv)? Then run `node -r dotenv/config your-index.js`. Or `require('dotenv').config()` at the top of your entry file.

This worked perfectly.
I am not sure why parcel is not natively assigning the .env variables, but once I added this to the top of the file I need my variables, it works.
