### ISSUE TITLE
Error with object spread syntax in 1.10.1

### ISSUE THREAD

**Issue by Lugribossk** [parcel-bundler/parcel#2108]
# 🐛 bug report

When building a Javascript file that uses object spread syntax, Parcel 1.9.7 produces working output, while Parcel 1.10.1 produces output that fails when run.

E.g. if I build a file that contains this snippet:
```js
<SignalsTab
    key="signals-tab"
    study={study}
    {...this.getPlayerProps()}
/>
```

## 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc:
```js
{
    "plugins": ["transform-runtime", "transform-object-rest-spread"],
    "presets": ["es2015", "react"],
    "compact": true
}
```
Babel versions:
```
"babel-core": "6.26.0",
"babel-plugin-transform-object-rest-spread": "6.26.0",
"babel-plugin-transform-runtime": "6.23.0",
"babel-preset-es2015": "6.24.1",
"babel-preset-react": "6.24.1",
"babel-runtime": "6.26.0",
```

## 🤔 Expected Behavior

With Parcel 1.9.7 the output is:
```js
_react2.default.createElement(_SignalsTab2.default, (0, _extends3.default)({
                key: "signals-tab",
                study: study
            }, this.getPlayerProps()))
```
where `_extends3` is defined at the beginning of the module, meaning that the code runs fine.

## 😯 Current Behavior

Wiht Parcel 1.10.1 the output is:
```js
_react.default.createElement(_SignalsTab.default, _extends({
        key: "signals-tab",
        study: study
      }, this.getPlayerProps()))
```
where `_extends` is not defined in the module, leading to a `ReferenceError: _extends is not defined` error.

## 💻 Code Sample

Unfortunately the error occurs in a larger project at work that I can't share.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.10.1
| Node             |10.4.0
| npm/Yarn         |Yarn 1.7.0
| Operating System |Windows 10

**Comment by devongovett** [comment]
Are you still having this issue? Seems like it could possibly be related to the babel upgrade?

**Comment by mischnic** [comment]
I can't reproduce this with current parcel and the listed babel configuration/versions:
```js
import React from "react";

class SignalsTab extends React.Component {

}

const study = false;

function getPlayerProps(){
	return {a: "x"}
}

<SignalsTab
    key="signals-tab"
    study={study}
    {...getPlayerProps()}
/>
```

**Comment by Lugribossk** [comment]
It's still happening for me on version 1.12.3.

**Comment by mischnic** [comment]
@Lugribossk I can't reproduce this (with the code sample I posted previously). Could you give more details or even create a minimal repo where this issue occurs?

**Comment by Lugribossk** [comment]
I've tried to create a reduced version of the project that reproduces the error, but it works fine as soon as I start cutting away parts of the involved components for a stand-alone example. So I suspect it is somehow related to the specific (and somewhat convoluted) components that trigger the error.
