### ISSUE TITLE
🐛 Cannot resolve dependency when I use <a> tag with virtual path

### ISSUE THREAD

**Issue by garrydzeng** [parcel-bundler/parcel#211]
🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```
{
  "name": "parcel-test",
  "version": "0.1.0",
  "devDependencies": {
    "parcel-bundler": "git://github.com/parcel-bundler/parcel.git"
  }
}
```
index.html
```
<html>
  <body>
    <a href="/b">CLICK ME</a>
  </body>
</html>
```
And run command:
```
parcel build src/index.html
```

### 🤔 Expected Behavior

No error

### 😯 Current Behavior

Thrown an error with message `Cannot resolve dependency './..\..\..\..\b'`

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  master branch
| Node             |  8.9.3
| npm/Yarn         |  Yarn 1.2.1
| Operating System |  Windows 10 x64

**Comment by DeMoorJasper** [comment]
Will look into this

**Comment by MIFind** [comment]
I have a bug as same as u. waiting for the resolved.

**Comment by davidnagli** [comment]
Is this similar to #191?

**Comment by DeMoorJasper** [comment]
Nah #191 had to do with something else, i'm not sure why it accured and guess it got fixed through a PR somewhere along the way

**Comment by nakoo** [comment]
```
<a href="/b">CLICK ME</a>
```
😡

```
<a href="./b">CLICK ME</a>
```
😙

**Comment by garrydzeng** [comment]
@nakoo I tried but still error.
