### ISSUE TITLE
Allow babelrc: false and/or babel.config.js

### ISSUE THREAD

**Issue by adrienharnay** [parcel-bundler/parcel#2110]
# 🙋 feature request

Hey,

Since Babel 7, it is common to use a [babel.config.js](https://new.babeljs.io/docs/en/next/babelconfigjs.html) file, or the [babelrc: false](https://babeljs.io/docs/en/config-files#file-relative-configuration) option.

Why? It allows for modules outside the root dir (e.g. Yarn workspace, symlinked package in node_modules with `"source": true` in package.json) to be transpiled using the same options as the rest of the code.

## 🤔 Expected Behavior

Being able to transpile a module with `source: true` using the `.babelrc.js` config at the Parcel root.

## 😯 Current Behavior

The external module is transpiled using Parcel's default `babelrc` (e.g. no support for experimental syntax classProperties).

```
Support for the experimental syntax 'classProperties' isn't currently enabled
```

## 💁 Possible Solution

Supporting either `babelrc: false` or `babel.config.js`. Or maybe both?

## 🔦 Context

I have a monorepo like so:

```
repo
- packages
-- service-a
-- util-shared
```

`service-a` is compiled with Parcel. `util-shared` is symlinked in `service-a` node_modules using Yarn workspaces. Both use the same type of code, and it would be nice to use the same babel config for both.

## 💻 Examples

I think Context pretty much covers it all, but I would be happy to give more context if needed.

Also, I would be up to implement this but would need some pointers if possible. Thanks in advance!

**Comment by serv** [comment]
We should also mention in the doc that `babel.config.js` is not supported until it becomes useable for Parcel. I was mistakenly thought that `babel.config.js` is supported and realized that babel config changes were not being applied.

**Comment by Hotell** [comment]
Maybe a slight off topic, but same applies for tsconfig.json I guess, should be also added to docs.

**Comment by adrienharnay** [comment]
Hey, any news on this? Seems like a few people would like to see it implemented/would be eager to file a PR

**Comment by aliai** [comment]
Hey @adrienharnay! Not sure if you are referring to the PR or this issue, sorry if I got it wrong :) Now I see that my PR does not address the exact issue you brought up here (which is support for `babel.config.js`). I just jumped into conclusion when I saw yarn workspaces.

The problem with yarn workspace (monorepo linked packages) with parcel is that parcel doesn't traverse the folders to get to the root folder, to begin with. It stops at the sub-project level. In your case having a `.babelrc.js` or `.babelrc` in your projects' folder should suffice. As you pointed out.

In our monorepo, we made a project to preset all of our babel configurations in one package (without publishing) and use that preset everywhere. Basically, in all of our js project where we need babel compiler, we just drop a `.babelrc` file in the root of that project and point the preset to the predefined preset project.

**Comment by adrienharnay** [comment]
Hey, in any case thanks a lot for the PR, I will try again when it is released and tell you if it satisfied our use case 🙂

**Comment by rodrigo4244** [comment]
:+1:

**Comment by sanohin** [comment]
seems like `babel.config.js` is officially supported https://babeljs.io/docs/en/configuration#babelconfigjs

**Comment by newtriks** [comment]
I'm in the position where I wanted to integrate Parcel into a Lerna based project and with Babel 7 in a monorepos setup `babel.config.js` is recommended https://babeljs.io/docs/en/config-files#monorepos. I'd also love to see this supported by Parcel as dotfiles in every package is not an approach we desire.

**Comment by sidroopdaska** [comment]
Any updates on this?

**Comment by devongovett** [comment]
Unfortunately, `babelrc.config.js` makes things very difficult for Parcel's cache. Since it is a JS file rather than static JSON, it can have dependencies, side effects, read files from the filesystem, return different value every time, etc. This basically makes applications that use it completely non-cacheable. In my opinion, allowing JS in configs was a major design mistake.

I am aware that babel [has an API](https://babeljs.io/docs/en/config-files#apicache) to control cacheability of configs, but it isn't really designed for use in a cache that is serialized to disk. It is designed to avoid re-calling the config function, not to avoid re-compiling files. In addition, it is not enabled by default. The API relies on callback functions to determine if the cache should be invalidated, but that only works when the callback can be stored in memory - we cannot serialize it to disk. So when you restart Parcel, we still need to invalidate the cache for every file and recompute the `babelrc.config.js`. This will make rebuilds much much slower than you are used to with Parcel.

If we support this, we will need to add custom logic to Parcel to disable caching if `babelrc.config.js` is seen, and probably warn users about why their builds get much slower. I would recommend just using a `.babelrc` in the root of your monorepo instead of `babelrc.config.js`. If you can avoid writing JS configs, do.

**Comment by akatechis** [comment]
> 
> 
> Unfortunately, `babelrc.config.js` makes things very difficult for Parcel's cache. Since it is a JS file rather than static JSON, it can have dependencies, side effects, read files from the filesystem, return different value every time, etc. This basically makes applications that use it completely non-cacheable. In my opinion, allowing JS in configs was a major design mistake.

While you're probably right that using JS in configs is an anti-pattern (see plugins, tools and design patterns around webpack.config.js merging/extending for evidence), there's a couple use cases that are only possible with dynamic configuration files.

First, the case of extending a base config, using JS syntax to require it, and extend it. Secondly, is to target multiple environments: My own babel config looks something like this:

```

module.exports = function (api) {
  api.cache(true)

  // tests run in mocha, so we compile those to commonjs
  const modules = process.env.NODE_ENV === 'test'
    ? 'commonjs'
    : false

  // target node when we're running tests, otherwise, browsers
  const targets = process.env.NODE_ENV === 'test'
    ? { node: 'current' }
    : { browsers: 'last 2 versions' }

  const presets = [
    ['@babel/env', {
      targets,
      modules,
      useBuiltIns: 'usage',
    }],
  ]

  return { presets }
}
```

In our case, we set the `NODE_ENV` variable to `test` when we run our tests, as a signal that we're running on node, to change how module syntax is handled. Similarly, our target is adjusted based on whether we're running tests (node) or just building the app (last 2 versions of each browser).

I'd be interested to know if there's some cleaner/better way of handling multiple execution targets.

**Comment by alexkrolick** [comment]
FYI - Jest 24 dropped support for Babel 6 and seems to only pick up `babel.config.js`, not `.babelrc`. https://jestjs.io/docs/en/getting-started#using-babel

**Comment by ctsstc** [comment]
I haven't been able to find a way around conditions for configs without having a JS file. This is mainly due to the cli lacking the extensibility, but giving most flexibility through JS which is nice.

@devongovett Just spitballing an idea here, but assuming most people are commonly setting a boolean or string in their js configs, could we just read the export/evaluate it and JSON'ify it with the assumption that it's then frozen and reused from then on out?

**Comment by sanohin** [comment]
@alexkrolick jest still supports `.baberc` as well.

**Comment by hellobrian** [comment]
it would be good to update the [parcel babel docs](https://parceljs.org/javascript.html#babel) to make it really clear that `babel.config.js` isn't supported. 

I was getting errors in my chrome browser console with my production build that said: 

```
Syntax Error Unexpected token <
```

It wasn't until I found this issue that I finally figured out that I needed to use a `.babelrc` file.

**Comment by adamshaylor** [comment]
> @alexkrolick jest still supports `.babelrc` as well.

Jest does not support `.babelrc` when testing ES modules with ES module dependencies. See facebook/jest#6229.

**Comment by posidron** [comment]
I solved it in Jest with:

```javascript
  globals: {
    'babel-jest': {
      useBabelrc: true
    }
  }
```

**Comment by jamesguan** [comment]
I am running into this issue as well, trying to migrate an old project from webpack but this would cause a whole reconfiguration and would be difficult to set configurations depending on environment. Is this going to be a supported feature in the future to support js files for configuration?

**Comment by devongovett** [comment]
This will be supported in Parcel 2, though it will warn in some sub-optimal scenarios that are possible with JS-based configs. See #3261 for the in progress PR.

**Comment by joeyhub** [comment]
babel.config.js is just another build asset.

Using static files is not an alternative to using dynamic scripts for configuration. What you have to do with static files is unroll everything.

Even with a static file hack, I'd still have something like `npm -e 'JSON.stringify(require("./babel.config.js")());' > .babelrc`.

The NPM config interface can be a bit annoying in combination with the documentation but what a lot of people really want is just to deduplicate. In those cases it's unlikely the config has or needs to rely on embedding data types incompatible with JSON in the configuration.

A very common case is that people use the JS format for different environments. Babel's JSON format has support for with with the env key where per env overrides can be applied. It's not always DRY but will be more DRY than having to have multiple files.

**Comment by tofishes** [comment]
Babel 7 only use babel.config.js to compile node_modules , but parcel support .babelrc , how to resolve this case ?

**Comment by DeMoorJasper** [comment]
@tofishes parcel 2 supports babel.config.js.

Also if the package’s browserlist doesn’t match the one of your application it transpiles that module to your projects target

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by devongovett** [comment]
Closing this. Parcel 2 supports all standard babel config options. However, when you use babel.config.js we do bail out on caching and you will need to restart parcel each time you make a change to the config and rebuilds may be slower. We contributed support for babel.config.json to babel and recommend using that instead if possible for better perf.
