### ISSUE TITLE
style= causes bogus js files to be referenced

### ISSUE THREAD

**Issue by dannydulai** [parcel-bundler/parcel#2114]
# 🐛 bug report

adding style= can cause non-hashed named js files to be included that dont exist

## 🎛 Configuration (.babelrc, package.json, cli command)

no babel, no package.json.. cli is `parcel one.html`

## 🤔 Expected Behavior

This works fine if i have no style=

## 😯 Current Behavior

I see the dist/one.html adding a "two.js" include -- that file does not exist so i get a browser and hmr issue.

## 💻 Code Sample

```
$ cat one.html
<span style='font-size: 1em;'></span>
<a href='two.html'>link</a>

$ cat two.html
<span style='font-size: 1em;'></span>

$ parcel one.html
Server running at http://localhost:1234
✨  Built in 687ms.
^C

$ cat dist/one.html
<script src="/two.js"></script><span style="font-size: 1em;"></span>
<a href="/two.html">link</a>

$ ls dist
one.html        one.js          one.map         two.html
```

see that `<script src="/two.js">` ? what is that from?

the crazy part is that if i remove style= from the html files, the problem goes away.

```
$ parcel -V
1.10.1
```

**Comment by DeMoorJasper** [comment]
This adds the hmr code for page refreshes...

**Comment by dannydulai** [comment]
Then why is that file not generated? It totally messes up the hmr by not being there. I'd like the hmr to work, but it doesn't because the file is missing.

**Comment by DeMoorJasper** [comment]
Ow now I see, the original issue description looked more like a confusion about why the file was there rather than it was missing...
