### ISSUE TITLE
Dynamic Import not working

### ISSUE THREAD

**Issue by FaBeyyy** [parcel-bundler/parcel#2124]
# 🐛 bug report

Dynamic Imports dont work (Module not found error).

## 🎛 Configuration (.babelrc, package.json, cli command)
```js
{
    "plugins": [
        ["dynamic-import-node"],
        ["transform-runtime",
        {
            "polyfill": false,
            "regenerator": true
        }],
        ["transform-object-rest-spread"]
    ],
    "presets": [
        ["env", {
          "targets": {
            "browsers": ["last 2 Firefox versions"]
          } 
        }]
      ]
} 
```

## 😯 Current Behavior Example

```javascript
const importPath = `./static/${this.pm.settings.additionalUIController}`;
      return import(importPath)
        .then(uiCtrlClass => {
            ...
        })
        .catch(error => {
          ...
        })
```
## 🌍 Your Environment

Parcel: Latest,
Node: Latest,
OS: Windows 10

EDIT: It is ridiculous that such a bug exists in huge repo like parcel and forces one to switch to other bundlers. Maybe @devongovett needs to take a look at this because i dont think that i am the only one having to switch because of this.

**Comment by devongovett** [comment]
Calls to `import()` require statically analyzable strings as input. In your example, you passed a variable, which has a string interpolation that cannot be resolved at build time. Therefore, Parcel is unable to resolve the dependency.

**Comment by mischnic** [comment]
#125 is similar
