### ISSUE TITLE
🙋 Import SVG as React component like CRA2.0

### ISSUE THREAD

**Issue by babakness** [parcel-bundler/parcel#2127]
# 🙋 feature request

It would be great if we could import `svg` files in React projects as components similar to CRA2.0

**Comment by DeMoorJasper** [comment]
Parcel is not a react only bundler, so it would have to be implemented by a plugin.

**Comment by MatejMazur** [comment]
Related request in SVGR repo: https://github.com/smooth-code/svgr/issues/215

**Comment by mischnic** [comment]
This is possible with Parcel 2:

https://v2.parceljs.org/recipes/react/#converting-svg-to-react-components

(Though that section of the docs is currently outdated: https://github.com/parcel-bundler/website/pull/882)
