### ISSUE TITLE
Unexpected token error happening for no reason

### ISSUE THREAD

**Issue by Arrow7000** [parcel-bundler/parcel#2129]
# 🐛 bug report

Getting an unexpected token error for no reason I can discern.
```
Unexpected token, expected ";" 
```

## 🎛 Configuration (.babelrc, package.json, cli command)

Don't have a Babel config, I'm just running the command like this
```
parcel src/index.html
```

## 🤔 Expected Behavior

It should compile my React code.

## 😯 Current Behavior

I'm getting this in the console
```
$ parcel src/index.html
Server running at http://localhost:1234
×  C:\projects\dfe\src\router\WithNavBar.tsx:5:10: Unexpected token, expected ";" (5:10)
  3 | import NavBar from "../components/NavBar/NavBar";
  4 |
> 5 | interface WithNavBarProps<T> {
    |          ^
  6 |   component: React.ComponentClass<T> | React.StatelessComponent<T>;
  7 |   path: string;
  8 | }
```

## 🔦 Context

This is the file where the problem is happening

```tsx
import * as React from "react";
import { Route } from "react-router-dom";
import NavBar from "../components/NavBar/NavBar";

interface WithNavBarProps<T> {
  component: React.ComponentClass<T> | React.StatelessComponent<T>;
  path: string;
}

function WithNavBar<T>({ component }: WithNavBarProps<T>) {
  return (
    <>
      <NavBar />
      <Route component={component} />
    </>
  );
}

export default WithNavBar;
```

It is valid TypeScript using JSX so I don't understand what the problem is.

## 💻 Code Sample

It looks like the problem persists even when getting rid of my own project's imports. Trying to compile this file still gives the same error.

```tsx
import * as React from "react";
import { Route } from "react-router-dom";

interface WithNavBarProps<T> {
  component: React.ComponentClass<T> | React.StatelessComponent<T>;
  path: string;
}

function WithNavBar<T>({ component }: WithNavBarProps<T>) {
  return (
    <>
      <Route component={component} />
    </>
  );
}

export default WithNavBar;

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             | 8.11.3
| npm/Yarn         | npm 5.6.0/Yarn 1.10.1
| Operating System | Windows 10 Version	10.0.17134 Build 17134

Note that I'm also using `parcel-plugin-typescript` version 1.0.0

**Comment by 9oelM** [comment]
Could you provide a clone of your repo?

**Comment by aih8** [comment]
![image](https://user-images.githubusercontent.com/18440794/47081948-b28a1800-d23e-11e8-9ee7-6f915ffcaf9d.png)
you should replace ; with ,

**Comment by Arrow7000** [comment]
@aih8 TypeScript interface items are separated by semicolons, not commas. See https://www.typescriptlang.org/docs/handbook/interfaces.html.

@9oelM I can't share my repo but I've given clear instructions on how to reproduce the error. Let me know if you have trouble reproducing it.

**Comment by wayou** [comment]
Has something to do with the plugin `parcel-plugin-typescript`, see also https://github.com/fathyb/parcel-plugin-typescript/issues/60.

Once remote the plugin, everything goes well.

**Comment by Arrow7000** [comment]
@wayou isn't that plugin what allows Parcel to do type checking?

**Comment by DeMoorJasper** [comment]
@Arrow7000 yes it is, but you could use parcels built-in ts support for compiling ts code as well. However this doesn’t check types. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by benpolinsky** [comment]
@DeMoorJasper Which eliminates the whole point of ts.

**Comment by DeMoorJasper** [comment]
I'm closing this as it's not an issue with Parcel-Bundler but with a Typescript plugin and it's kinda going off-topic.

Types is a whole other discussion that got resolved with the release of parcel-plugin-ts but this unfortunately was a bit hacky and no longer works.

If anyone wants to add typechecking in Parcel core I'm all for it but think it should be optional and probably a plugin for Parcel 2 once it comes out.
