### ISSUE TITLE
Parcel 2: ResolverRunner and default resolver

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#2138]
This will be the object in `@parcel/core` which runs resolver plugins in Parcel 2. It is responsible for resolving resolver plugins from a config file and running them. Resolvers can be chained, so if one does not return anything, the next one will be called and so on.

The default resolver should be moved into `@parcel/resolver-default` under `packages/resolvers/default`, and modified to fit the new interface. Ideally this resolver could also be reused by other tools, so the interface should be easy to use and decoupled from Parcel.

**Comment by ryan-plated** [comment]
Would this fix #1813 ?

**Comment by devongovett** [comment]
Done. #2228
