### ISSUE TITLE
[RFC] How to enable HMR (with preserving local state)

### ISSUE THREAD

**Issue by baba43** [parcel-bundler/parcel#214]
Hi, 

first let me tell you that I really appreciate this project and your efforts. Thanks.

One of the most annoying things to setup with Webpack is a properly working Hot Module Replacement. _Working properly_ means that components will keep their local state. Everything else makes HRM uselss (in my opinion). 

However I could not get HRM to work with parcel until now. The documentation is not very helpful (at least for me) and all the examples and boilerplates out there do not work _properly_. Whatever I try, my components are always recreated without preserving state.

I would like to use this issue to discuss if and how we can implement a properly working HRM with parcel.

**Comment by davidnagli** [comment]
In my experience, HMR has always been working perfectly. It usually preserves all the local state.

Can you please setup an example repo so that we reproduce the issue?

**Comment by albinotonnina** [comment]
This little example I did the day Parcel came out, ages ago, like 5 days, does that:
https://github.com/albinotonnina/hot-parcel-react

**Comment by davidnagli** [comment]
Upon second review, I think you might need to wait for #204 to land… it fixes an issue we had where HMR wasn’t working on nested components.

**Comment by baba43** [comment]
@albinotonnina thanks for providing an example. First of all, I had to update parcel to the latest version to get it running at all. Not sure why this is, but I guess you would like to use the latest version, too.

Then, if I try to change anything within the App, hot loading does not work. Instead your alert gets fired and the app gets reloaded (with loosing state). I have added a more common example with a counter: The App contains state that is passed to a child component. What I expect to happen is that the state will preserve whenever I edit the child component, but that is not the case (at least for me).
Repo: https://github.com/baba43/hot-parcel-react

Can someone reproduce this issues or might this problem be related to me?
OS: Windows 10
Node: v9.2.1 (tried older versions, too)

**Comment by albinotonnina** [comment]
@baba43 I will update the example ASAP. I noticed one thing actually, which I forgot to mention.
First change actually unmount components. From that moment on HMR works as expected.
Can you confirm this behaviour as well?

**Comment by lrn2prgrm** [comment]
I have no problems with HMR. Are you running the react hot loader patch? (just import it first, in my case i created a separate file to run this 'before app' scripts and from it would import the normal entry point of my app)

**Comment by baba43** [comment]
@lrn2prgrm can you run [my example](https://github.com/baba43/hot-parcel-react) and tell me that HMR is working as expected? If it is not, can you try to change the code like you think it should be or provide an example by yourself?

**Comment by kidandcat** [comment]
Here you have a full example working with React+Redux and typescript with HMR:

https://github.com/kidandcat/architecture-react-hot

**Comment by theKashey** [comment]
With latest parcel version and latest React-Hot-Loader(v4/next) - everything should be ok.

**Comment by rrousselGit** [comment]
Up on this issue.

It seems that the problem is still there. Even with the most basic setup, components loose their state.
Ironically redux store is preserved. Only components state is lost.

**Comment by theKashey** [comment]
@rrousselGit - this is probably not parcel issue, as long it did update components.
Feel free to open an issue for React-Hot-Loader, or check it's parcel example - https://github.com/gaearon/react-hot-loader/tree/master/examples/parcel
> Trying to running it with updated parcel, but it doesn't show anything except 404 🤷‍♂️
