### ISSUE TITLE
Parcel 2: PackagerRunner

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#2141]
The PackagerRunner object in `@parcel/core` is responsible for running Packager plugins in Parcel 2. Packager plugins write bundles to disk, combining their assets together into a single file.

The PackagerRunner should resolve Packager plugins from the Parcel config and execute them. A Packager plugin receives a `Bundle` as input, which is just a list of Assets, and returns a string or buffer containing the combined output. It will also need access to the Cache to read the contents of transformed assets, as the list of Assets provided as input only contains metadata. Packager plugins can also override the default file writing behavior, e.g. the Raw packager may just want to copy files using `fs.copy` instead of reading into memory and writing again.

**Comment by cacheflow** [comment]
I'd be happy to take this.

**Comment by devongovett** [comment]
@cacheflow cool! I am working on getting the monorepo set up on master today, and then I will comment back here with more details. Thanks!

**Comment by devongovett** [comment]
Done.
