### ISSUE TITLE
Parcel 2: Server

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#2144]
The Server from Parcel 1 should be extracted into a separate package in the monorepo for Parcel 2, as `@parcel/server`. This should include both the dev web server as well as the HMR web socket server. All utils related only to servers should be moved into this package. Parcel 1 should also be updated to use this package.

**Comment by mischnic** [comment]
Typo:
> into a separate package in the monorepo for Parcel **Two**

**Comment by devongovett** [comment]
Thanks!

**Comment by js-sapphire** [comment]
Hi, can I pick this up? I am new to OSS, so any pointers on how to start?
