### ISSUE TITLE
How to observe the changes in HTML and CSS, and then automatically refresh the browser ?

### ISSUE THREAD

**Issue by lian-xiao-xi** [parcel-bundler/parcel#215]
#### How to observe HTML and CSS changes, and then automatically refresh the browser. Now only by observing the changes in JS to automatically refresh the browser

**Comment by DeMoorJasper** [comment]
HTML updating should be inside the current github version, CSS updating is in an open PR here #128

**Comment by DeMoorJasper** [comment]
duplicate of #57 duplicate of #90
