### ISSUE TITLE
Parcel 2: HTML Transform

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#2158]
Create the `@parcel/transform-html` package in `packages/transforms/html`. This package is a Parcel 2 transform plugin for HTML. It will be based on the `HTMLAsset` from Parcel 1. The main difference is that it will not be responsible for transforming with PostHTML, that will be a separate `@parcel/transform-posthtml` plugin.

The `@parcel/transform-html` package is responsible for the following things:

* Parsing with PostHTML if an AST is not already available from a previous transform.
* Collecting dependencies - e.g. images, scripts, css, etc.
* Creating sub-assets for inline scripts and styles to be processed by the pipeline, and re-inserting them back into the HTML
* Generating HTML if needed.

**Comment by reebr** [comment]
Can we have any flag on dependencies collection to handle cases like #2637?

**Comment by mischnic** [comment]
> Can we have any flag on dependencies collection to handle cases like #2637?

Just for future reference: excluding dependencies (e.g. from `src`) has these primaries use-cases:
- file will exist on a relative url in production
- preprocessing HTML for a server-used template.

**Comment by reebr** [comment]
The same thing occurs on `<a>` tags. 😢

**Comment by RobertWHurst** [comment]
@reebr The trouble with that is the pug does not escape that HTML after your pipe. It simply becomes HTML. If parcel ignores it then it's not treating the HTML output uniformly, which I actually think is more confusing. If something in pug is supposed to become HTML, as is the case here, I want parcel to process it as such.

**Comment by wbinnssmith** [comment]
- [ ] Missing inline asset support

**Comment by kwelch** [comment]
I have this extract and creating the proper assets for this, I just need to update the nodes within html asset. I have been swamped on a few thing and haven't had a chance to look into this since before the holiday. Hoping to look at it again this week.

**Comment by devongovett** [comment]
Going to close this issue for alpha 1 and move inline asset support to #2158 in alpha 2.
