### ISSUE TITLE
Parcel 2: PostHTML Transform

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#2159]
Create the `@parcel/transform-posthtml` package in `packages/transforms/posthtml`. This package is a Parcel 2 transform plugin for PostHTML. It will be based on the `posthtml` transform in `HTMLAsset` from Parcel 1, split into its own package.

The `@parcel/transform-posthtml` package is responsible for the following things:

* Loading `.posthtmlrc` files
* Parsing and transforming if needed

**Comment by kwelch** [comment]
This can be moved to closed, right?

**Comment by wbinnssmith** [comment]
Yep. Closing 😄
