### ISSUE TITLE
Requiring parcel-bundler within electron causes native exception

### ISSUE THREAD

**Issue by RobertWHurst** [parcel-bundler/parcel#2164]
# 🐛 bug report

When requiring 'parcel-bundler' within an electron process a native exception is thrown.

## 🤔 Expected Behavior

I expect the module to load as nomal.

## 😯 Current Behavior

The following error is thrown:

```shell
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9Si
gnatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/roberthurst/Developer/Dialpad/firespotter/native/ubervoice/node_modules/deasync/bin/darwin-x64-node-10/deasync.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/roberthurst/Developer/Dialpad/firespotter/native/ubervoice/node_modules/deasync/bin/darwin-x64-node-10/deasync.node
  Expected in: flat namespace
```

## 🔦 Context

I'm trying to run parcel programmatically to allow for the development of the frontend code for my electron browser windows.

Note that I have ensured any native dependencies are installed correctly using electron-rebuild.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel-Bundler   | v1.10.3
| Electron              | v3.0.4
| npm/Yarn            | v1.9.4
| Operating System | macOS 10.13.6

**Comment by devongovett** [comment]
Seems like some native module doesn't work correctly with electron or wasn't built properly...

**Comment by davenquinn** [comment]
I have just run into the same issue. Did you come to a solution @RobertWHurst ?
