### ISSUE TITLE
Only watch a SCSS file and hot-reload that

### ISSUE THREAD

**Issue by LekoArts** [parcel-bundler/parcel#2169]
# ❔ Question

Can I use Parcel like `parcel watch main.scss` and then let PostCSS (+SASS) compile the SASS into a directory which will be identical with the `build` output then?

## 🔦 Context

I don't need an index.html or any .js files as I'm only editing css files of a [Invision community](https://invisioncommunity.com/4guides/themes-and-customizations/css-framework/introduction-to-the-css-framework-r88/) instance. For developing I want to use SASS & PostCSS.
Normally I'd use something like Gulp, but I first wanted to know if Parcel can do that, too.

So I'll start the forum and then would start Parcel, edit my SASS and it get's compiled down to one css file like they expect it.

**Comment by DeMoorJasper** [comment]
Parcel should automatically re-build the scss file whenever it gets changed.
With or without any other assets.
