### ISSUE TITLE
[RFC] Changelog

### ISSUE THREAD

**Issue by DeMoorJasper** [parcel-bundler/parcel#217]
# 💬 Changelog
We should probably think about keeping a Changelog, do you guys think we need one and how should it look/be generated.

Some possibilities
* [Standard version - generation/naming convention](https://github.com/conventional-changelog/standard-version)
* [Keep a Changelog - Standardisation](http://keepachangelog.com/en/1.0.0/)
* [Auto changelog - generation/naming convention](https://www.npmjs.com/package/auto-changelog)

**Comment by thejameskyle** [comment]
Existing issue: #138
