### ISSUE TITLE
Variables and functions are not accessible in browser dev console?

### ISSUE THREAD

**Issue by advename** [parcel-bundler/parcel#2171]
# ❔ Question

After bundle (both dev-server and prod build), variables and functions are not accessible in chrome console. Analyzing the code, the script and it's dependencies are all processed into one single big function. This might be the reason why I can't access a variable e.g. myString in the chrome developer tool console.
## 🔦 Context
I'm used to use both, the console.log() method and the browser built in console to debug my code and get latest values of functions / variables. This is one of the easiest and fastest ways imho.

## 💻 Code Sample
E.g. my main.js file
```
import "../styles/sass/main.scss";
import is from "is_js";

const myString = "Hello World";
```
Then i bundle it and launch the dev server using "parcel index.html" 
And when i type in the chrome dev console "myString" i get an error saying:

`Uncaught ReferenceError: sections is not defined at :1:1`

## 🌍 Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.9.7|
| Node             |v8.11.2|
| npm/Yarn         |5.6.0|
| Operating System |Windows 10 Pro|

**Comment by Hammster** [comment]
Definitely caused by the fact that parcel "bundles" and the variables are not know to the document scope, but the scope of the particular bundle. 😉 

Same behaviour as if you use a closure or event for a 'document-ready' eg:

``` js
const a = 1;

(function() {  
    const b = 2;
}());

document.addEventListener("DOMContentLoaded", function() {
    const c = 3;
});
```
![parcel_var_scope](https://user-images.githubusercontent.com/1093709/47257580-05a6d980-d490-11e8-9862-e3bc9bbd25e3.png)

The only way to archive the result you probably want to hear is by using inline scripts from the HTML document, but this far from a practical solution.

``` html
<script>
   const a = 3;
</script>
```

**Comment by avalanche1** [comment]
I've stumbled into this today and this is very disheartening. Plz fix ASAP.

**Comment by devongovett** [comment]
This is working as designed, according to the ES Module and Common JS specs. With modules, variables are scoped to the file they are in and are not global.

**Comment by avalanche1** [comment]
Um, Devon, I appreciate all the work you do on Parcel - but shouldn't there be a method to debug bundled code?
For example, I am currently developping an extenstion for Chrome. The UI is React app built by Parcel. I import the whole bundle (`src.abc.js`) into extension's `index.html`.
I would very much like to be able to debug bundled code on extension's runtime.
plz?

**Comment by devongovett** [comment]
The browsers debugger should work if you make a breakpoint. And if you must make a global, you can assign to the window object.

**Comment by MrSimmmons** [comment]
Im going to chime in here (2 years late, I know) with I guess a request for V2 that a flag gets added as a "Parameter specific to `serve`" called `--global-scoped-output` (or something similar) that pretty much does what it says on the tin.
This of course would be a exclusive to `serve` as like you said:
> according to the ES Module and Common JS specs. With modules, variables are scoped to the file they are in and are not global.

Which makes a lot of sense for a production version of said site. But while your developing I feel that "best practices" can happily be ignored as it is only temporary anyway.

<hr>

> and you're also able to skip all that console.log() and console.dir() wrapping

Also I fell that this feature would be less about wrapping `console.log()` around things in your files, and more the fact that there are some variables / static class values which hold information that you just kind of want to know whats in them _while you are in your browser_ and without having to code a workaround to achieve it.

**Comment by mischnic** [comment]
Parcel 2 does this already: https://v2.parceljs.org/languages/javascript/#classic-scripts

**Comment by MrSimmmons** [comment]
For external js libraries, yeah sure. But my request (which is the same as the @advename made) is that your own js, ts, tsx file gets put in the global scope as well. The ones that actually use `import` in them.

And it would be pretty easy to do as well. You just dont include the `type="module"` in the dev built HTML, and don't change the names of any of the variables. (if you remove `type="module"` yourself, you actually just get all the variables and classes in the global scope anyway. But all their names are optimised so its hard to check what they are in the console)
