### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by Zoweb** [parcel-bundler/parcel#2177]
# 🙋 feature request

Support for building and including Kotlin (.kt) files. As Kotlin is getting increasingly popular, it makes sense for support to be built-in.

## 🤔 Expected Behavior

When a .kt file is found, it should be included in the output as a JavaScript file or a WASM file (would be configurable)

## 😯 Current Behavior

The .kt file is just copied into the output directory.

## 💁 Possible Solution

Node packages exist that should be able to build Kotlin files, however after testing `kotlin-node` could not be installed and `node-kotlin` would generate an empty zip inside a zip.

Instead kotlinc could be downloaded from JetBrains/kotlin and run with the correct arguments to generate .js files, which could then be inputted back into the system to create the output.

## 🔦 Context

I'm trying to use Kotlin instead of JavaScript or TypeScript because I prefer the language and how it works. As Kotlin can build to both JavaScript and WASM, it can be used as the single programming language in the project, as well as a server system.

## 💻 Examples

N/A

**Comment by Zoweb** [comment]
It looks like WebPack has support for Kotlin, so maybe it could be ported over to Parcel.

**Comment by DeMoorJasper** [comment]
Feel free to try this and open up a pr

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Zoweb** [comment]
OK, I've created the pr - #2210
