### ISSUE TITLE
Parcel + vue

### ISSUE THREAD

**Issue by cowDungIsFlowers** [parcel-bundler/parcel#2178]
import Vue from 'vue';
import VueRouter from 'vue-router';

Vue.use(VueRouter);

You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

(found in <Root>)

**Comment by DeMoorJasper** [comment]
Is this an error message?

Not sure what you're asking here

**Comment by cowDungIsFlowers** [comment]
If you quote Vue directly from the node_modules directory, you will report the following error：
You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

**Comment by DeMoorJasper** [comment]
@Hammster aliasing is already possible in Parcel 1

**Comment by cowDungIsFlowers** [comment]
@Hammster Thanks to your answer, I have solved the problem. Thank you.

**Comment by mischnic** [comment]
Closing. The Parcel website was also updated to have an actually working example.

**Comment by milgner** [comment]
I'm using the same code given here - more specifically the one from Parcel website -, but I'm still seeing the error message. It says `(found in <Root>)`, though, which I'm not sure is a difference or an omission from the OP...
As the website documentation doesn't mention the alias, I tried both variants, with and without it present, but it doesn't seem to make any difference.
