### ISSUE TITLE
[Rust] Can't build simple project

### ISSUE THREAD

**Issue by linvain** [parcel-bundler/parcel#2184]
# 🐛 bug report

I can't build this simple project. Am I doing something wrong?

## 😯 Current Behavior

```bash
$ npm run build

> parcel-rust-test@1.0.0 build C:\Projects\test
> npm run clean && parcel build src/index.html


> parcel-rust-test@1.0.0 clean C:\Projects\test
> rm -rf dist

√  Built in 1.04s.

dist\fib.6e849f36.wasm    ‼  1.89 MB    798ms
dist\src.83762b81.js         3.19 KB    810ms
dist\src.83762b81.map          630 B      3ms
dist\index.html                 70 B      4ms
×  Error writing to cache: ENOENT: no such file or directory, stat 'C:\Projects\test\src\C'
```

## 💻 Code Sample

https://github.com/linvain/parcel-rust-test

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             | 10.11.0
| npm/Yarn         | 6.4.1
| Operating System | Windows 10

Standalone rust projects work fine on my computer
I use Git Bash with "run as administrator"

**Comment by linvain** [comment]
Got the same error on another Windows 10 machine: `Error writing to cache: ENOENT: no such file or directory, stat 'E:\GitHub\parcel-rust-test\src\E'`

**Comment by popey456963** [comment]
Yes, I'm also seeing this issue on a simple project.  Is there a workaround?  I've tried forcing the cache directory to either the directory Rust is in, or specifically not, but neither sem to allow it to function.

**Comment by Glitch0011** [comment]
I've had some luck with the "no such file" bug when I used `cargo new test_project --lib` to create a sub-project directory and `.toml` file.

It now generates a new directory called `target` within that sub-project directory which didn't exist before. That might be helping?
