### ISSUE TITLE
Is there a Parcel equivalent to Webpack's resourceQuery?

### ISSUE THREAD

**Issue by EmilTholin** [parcel-bundler/parcel#2186]
# ❔ Question

Is there a Parcel equivalent to Webpack's [`resourceQuery`](https://webpack.js.org/configuration/module/#rule-resourcequery) that allows you to use different loaders for assets with the same file extension with the help of a query parameter, or something similar?

## 🔦 Context

Parcel is a phenomenal tool, and the only thing that is holding me back from migrating to it in various projects is that there seems to be no way to treat assets with the same extension in different ways. This applies to e.g. loading some CSS as global and some as CSS modules, some images as regular images and some as [lqip previews](https://github.com/zouhir/lqip), etc.

## 💻 Code Sample

In Webpack you can use a `resourceQuery` to e.g. treat imported CSS with an added `?global` query parameter as regular global CSS, and every other CSS file as CSS modules.

```javascript
module.exports = {
  //...
  module: {
    rules: [
      {
        test: /.css$/,
        oneOf: [
          {
            // Use e.g. import 'react-select/dist/react-select.css?global'
            // to treat the CSS as global
            resourceQuery: /global/, 
            use: ['style-loader', 'css-loader']
          },
          {
            // All other files will be treated as CSS modules
            use: ['style-loader', 'css-loader'],
            options: {
              modules: true,
              localIdentName: '[name]__[local]_[hash:base64:5]'
            }
          }
        ]
      }
    ]
  }
};
```

**Comment by mischnic** [comment]
Currently not (and there are other usecases where this is really needed), merging with #1084

Parcel 2 might process `name.module.css` files as modules and others as "starndard" CSS files, which is also how CRA handles this.
