### ISSUE TITLE
vue development message is show in console when import component in main.js

### ISSUE THREAD

**Issue by kiwionly** [parcel-bundler/parcel#2188]
# 🐛 bug report

I had an index.html which contain a main.js file.

```javascript
import Vue from 'vue'

import Comp from './MockApp.vue' // just a component with template

const app = new Vue({
}).$mount('#app')
```

when using import, it always show 2 vue development message in console.

![image](https://user-images.githubusercontent.com/174617/47411293-cf709f00-d79a-11e8-8378-5750a0f736f3.png)

1 is from line "import vue ... ", and second is from line "import Comp ... "

This also happen in production build.

is this correct behaviour ?

## 🤔 Expected Behavior

The vue development message should not be show from vue.runtime.esm.js in console.

## 😯 Current Behavior

show vue development message in console. (from vue.runtime.esm.js)

## 💻 Code Sample

```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>demo</title>
	</head>
	<body>
		<div id="app">			
		</div>
		<script src="./src/main.js"></script>
	</body>
</html>
```
index.html

```javascript
import Vue from 'vue/dist/vue.js'

import App from './MockApp.vue'

const app = new Vue({
}).$mount('#app')
```
main.js

```
<template>
<div>
	hello world
</div>
</template>
```
MockApp.vue

```json
{
  "name": "cattest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "npx parcel index.html -p 8081"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "vue": "^2.5.17"
  },
  "devDependencies": {
    "@vue/component-compiler-utils": "^2.2.0",
    "parcel-bundler": "^1.10.2"
  }
}
```
package.json

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.10.3
| Node             | v8.11.2
| npm/Yarn         |  6.4.1
| Operating System | window 10

**Comment by Lazac92** [comment]
Set `Vue.config.productionTip = false` before calling `new Vue()`
