### ISSUE TITLE
source-map enabled  , print  line error in console.log 

### ISSUE THREAD

**Issue by ydostyle** [parcel-bundler/parcel#2189]
Why don't rows corresponding
![image](https://user-images.githubusercontent.com/22721444/47418481-c5579c00-d7ac-11e8-97ed-15a8e399b32f.png)
![image](https://user-images.githubusercontent.com/22721444/47418513-d43e4e80-d7ac-11e8-971c-0a9cee6c62bf.png)

version:
"parcel-bundler": "1.9.7"

**Comment by DeMoorJasper** [comment]
Update to 1.10.3 than report back if its still an issue might be a sourcemap bug that got fixed recently

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
