### ISSUE TITLE
enable css-module default

### ISSUE THREAD

**Issue by xiaoxiangmoe** [parcel-bundler/parcel#2190]
# 🙋 feature request

enable css-module default in `*.module.(css|less|sass|scss)` file

## 🔦 Context

[Create React App - Adding a CSS Modules Stylesheet](https://facebook.github.io/create-react-app/docs/adding-a-css-modules-stylesheet):
* This project supports CSS Modules alongside regular stylesheets using the [name].module.css file naming convention.

[Neutrino Style Loader Middleware -Features](https://neutrinojs.org/packages/style-loader/#features):
* Pre-configured to support CSS Modules via `*.module.css` file extensions

**Comment by devongovett** [comment]
This is supported in Parcel 2 automatically.
