### ISSUE TITLE
Destructuring doesn't work with process.env

### ISSUE THREAD

**Issue by EvgenyOrekhov** [parcel-bundler/parcel#2191]
# 🐛 bug report

Destructuring doesn't work with `process.env`.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
    "presets": ["@babel/preset-env"]
}
```

## 🤔 Expected Behavior

```js
const {PWD, NODE_ENV} = process.env;
console.log(PWD, NODE_ENV);
```

The console should print the variables, something like `/home/user/parcel development`.

## 😯 Current Behavior

The console prints `undefined undefined`.

## 🔦 Context

I am trying to follow ESLint's [no-process-env](https://eslint.org/docs/rules/no-process-env) rule. I want to have only one place (one line) in my codebase where I read variables from `process.env`, so I have a `config.js` file with the following code:

```js
//eslint-disable-next-line no-process-env
const {API_URL, NODE_ENV} = process.env;

export {
    API_URL,
    NODE_ENV
};
```

## 💻 Code Sample

```js
const {PWD, NODE_ENV} = process.env;
console.log(PWD, NODE_ENV);
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v1.10.3
| Node             | v11.0.0
| npm/Yarn         | npm 6.4.1
| Operating System | Ubuntu 18.04

**Comment by xiaoxiangmoe** [comment]
@EvgenyOrekhov this also doesn't work in most of webpack config. Because they use [DefinePlugin](https://webpack.js.org/plugins/define-plugin/).

Dont't use destructuring in process.env in most of time.

**Comment by EvgenyOrekhov** [comment]
@xiaoxiangmoe "Don't use it" is not a solution. The bug should be fixed.

**Comment by EvgenyOrekhov** [comment]
Cross referencing the same bug report for webpack: https://github.com/webpack/webpack/issues/5392.

**Comment by mytee306** [comment]
Seems to be working just fine

.env.development

```
NAME=John
```

index.js

```javascript
const { NAME } = process.env;

Hello {NAME} // -> Hello John
```

**Comment by EvgenyOrekhov** [comment]
@mytee306 It does indeed, but only if you extract exactly one property. Strange.

**Comment by mytee306** [comment]
@EvgenyOrekhov indeed, haven't tried extracting more than one prop, seems like an interesting problem to solve

**Comment by mischnic** [comment]
Currently, this 
```js
const {PWD, NODE_ENV} = process.env;

const {FILE} = process.env;
```
is processed by babel into:
```js
var _process$env = process.env,
    PWD = _process$env.PWD,
    NODE_ENV = _process$env.NODE_ENV;
var FILE = process.env.FILE;
```

But Parcel's env visitor (https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/visitors/env.js) only looks out for `process.env` and looks up the key that follows:
https://github.com/parcel-bundler/parcel/blob/6566e160affa161daa6d5486139e6059f685ba3a/packages/core/parcel-bundler/src/visitors/env.js#L6

Lookup fix:
```diff
--- a/packages/core/parcel-bundler/src/visitors/env.js
+++ b/packages/core/parcel-bundler/src/visitors/env.js
@@ -3,7 +3,8 @@ const types = require('@babel/types');
 module.exports = {
   MemberExpression(node, asset) {
     // Inline environment variables accessed on process.env
-    if (types.matchesPattern(node.object, 'process.env')) {
+    if (types.matchesPattern(node.object, 'process.env') || node.object.name == "_process$env") {
       let key = types.toComputedKey(node);
       if (types.isStringLiteral(key)) {
         let prop = process.env[key.value];
```

Remaining issue: removing the `_process$env` variable.
```js
var _process$env = process.env,
    PWD = ".....",
    NODE_ENV = "....";
var FILE = "....";
```

**Comment by TakanashiOuken** [comment]
Having the same problem here.  Had get them one by one....

**Comment by piranna** [comment]
What's the current status of this one?

**Comment by justincorrigible** [comment]
Not sure how relevant/useful what I'm about to say is, but this happens when using Babel by itself too.

---
edit: as it turns out, the issue in my case may have been related to using an older NodeJS version (I was running multiple projects simultaneously, one of them a legacy app that required node <=8.)

Just to discard the issue in your case is not the same as mine, I'd check having the latest updates.

**Comment by TheTechSensei** [comment]
same problem...

**Comment by IvanTserashkou** [comment]
same problem

**Comment by devongovett** [comment]
This is implemented in Parcel 2. If you're having a problem, please open a new issue with a reproduction.

**Comment by piranna** [comment]
> This is implemented in Parcel 2

Can you point us where is it implemented and how to use it?

**Comment by devongovett** [comment]
The PR is linked above and the docs are here https://parceljs.org/features/node-emulation/#environment-variables

**Comment by piranna** [comment]
Great, thanks :-)
