### ISSUE TITLE
@ Paths support

### ISSUE THREAD

**Issue by xiaoxiangmoe** [parcel-bundler/parcel#2192]
# 🙋 feature request

Support `@` path for consistency with [vue-cli ](https://github.com/vuejs/vue-cli/blob/f8e97838dd25e37433ebbdb92b748c48b89f7c2a/packages/%40vue/cli-service/lib/config/base.js#L49) and [umi](https://github.com/umijs/umi/pull/799)

## 🤔 Expected Behavior
Support `@` path

## 😯 Current Behavior
Support ~ Tilde Paths

## 💁 Possible Solution

Support `@` path

**Comment by Hammster** [comment]
I think the `~` path is good enough, Parcel 2 will offer to alias where you can change the behavior if you want ;) 

https://github.com/parcel-bundler/parcel/blob/master/PARCEL_2_RFC.md#aliases

**Comment by devongovett** [comment]
Aliases already work in Parcel 1, so this should already be possible.
