### ISSUE TITLE
Workaround for React.lazy occasionally not working in Parcel

### ISSUE THREAD

**Issue by wojtekmaj** [parcel-bundler/parcel#2193]
Not really an issue at this point, but I wanted to help out the lost souls who would like to test new features of React 16.6 so early.

If you coded something similar to the code from React.lazy docs:

```js
import React, {lazy, Suspense} from 'react';
const OtherComponent = lazy(() => import('./OtherComponent'));

function MyComponent() {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <OtherComponent />
    </Suspense>
  );
}
```

you may get the following error:

```
Warning: lazy: Expected the result of a dynamic import() call. Instead received: function OtherComponent() {}

Your code should look like: const MyComponent = lazy(() => import('./MyComponent'))
```

But hold on! Your code *already* looks like `const MyComponent = lazy(() => import('./MyComponent'))`! This means that the component you're using is not using Harmony modules, but likely CommonJS modules, which work a little differently, and React got confused.

Fear not! A quick solution is to wrap native import, which gets transformed by Parcel, in your own Promise which would return Harmony module-like result, like so:

```js
const OtherComponent = lazy(() => new Promise((resolve, reject) => {
  import('./OtherComponent')
    .then(result => resolve(result.default ? result : { default: result }))
    .catch(reject);
}));
```

Happy coding!

**Comment by DeMoorJasper** [comment]
Not sure why this is necessary, I've experimented with the lazy api both using function components and class components, and they both work without any need for this hack

**Comment by wojtekmaj** [comment]
In my specific case, I've been using `react-markdown`. It may be using non-ES6 modules under the hood, but some less experienced developers may have no idea on how to work around that issue.

**Comment by asulta** [comment]
That saved me a lot of time indeed. Thank you 💯

**Comment by allan2coder** [comment]
anyone who have other solutions? it seems strange.

**Comment by wojtekmaj** [comment]
@allan2coder It is a little strange, but I'll try my best to explain why.

If you have a CommonJS module:

```js
module.exports = class Foo extends Component {}
```

then, when `import()`ed, will result in `result` being `Component`

If you have a Harmony/ES6 module:

```js
export default class Foo extends Component {}
```

then, when `import()`ed, will result in `result` being `{ default: Component }`.

So, I wrap `import()` in a promise, which resolves with:

```js
resolve(result.default ? result : { default: result }))
```

So if there's `result.default`, we know we deal with ES6 module and we can safely return `result` as given by `import()`. If not, we wrap the result in an object. This ensures that our promise will always return a ES6-like output, being `{ default: Component }`. Why is that even necessary? This is because [React.lazy implementation expects a ES6 module](https://github.com/facebook/react/blob/f777d196e0943b3975c762e15e35b319a9b85902/packages/react-reconciler/src/ReactFiberLazyComponent.js#L53) - it's not made for CommonJS modules at all.

Hope this helps!

**Comment by devongovett** [comment]
This seems like an issue that React should solve rather than Parcel. They seem to be requiring the module you are importing to be an ES6 module, and looking for the `default` property on it. Seems like they could do this interop within React itself.

**Comment by wojtekmaj** [comment]
It's absolutely a React thing, but I don't think they are willing to change it - see facebook/react#13886. I'm just trying to help the community :)

**Comment by mischnic** [comment]
Does `const MyComponent = lazy(() => import('./MyComponent'))` work correctly with Webpack?

**Comment by wojtekmaj** [comment]
No @mischnic, it would be affected by the same issue.

**Comment by MjDhaneshKumar** [comment]
Hi Guy's,

`const OtherComponent = lazy(() => import('./OtherComponent'));` => will only work for default component exports not for the named export.

**Comment by mischnic** [comment]
https://reactjs.org/docs/code-splitting.html#reactlazy:
>  that must call a dynamic `import()`. This must return a `Promise` which resolves to a module with a **`default`**  export containing a React component.
