### ISSUE TITLE
linked node_modules source maps are mixed w/ project

### ISSUE THREAD

**Issue by ewingrj** [parcel-bundler/parcel#2194]
# 🐛 bug report

I am trying to include sourcemaps for a dependency that has been linked. `npm link mydep`

This is working with the caveat that the sourcemaps appear under the same root `src/` in chrome devtools. This is a problem b/c the linked node_module sourcemaps appear mixed with my applications sourcemaps and will be overwritten by my app if any conflicts exist.

possibly related to #1801?

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": false,
        "targets": {
          "browsers": [
            "> 1%",
            "last 3 versions",
            "ie >= 9",
            "ios >= 8",
            "android >= 4.2"
          ]
        },
        "useBuiltIns": false
      }
    ]
  ],
  "plugins": [
    ["styled-components", { "displayName": true }],
    "@babel/plugin-proposal-class-properties"
  ]
}
```

## 🤔 Expected Behavior

I would expect any sourcemaps found for node_modules would be served at a different root. See next section for an example

## 😯 Current Behavior

currently they are served from the same `/src` root.

ex.

app
```
-- src
  -- index.js
```

mydep
```
-- src
  -- index.js
  -- cache
    -- index.js
```

The source maps in chrome devtools will appear as:

```
-- src
  -- index.js (this is from app)
  -- cache
    -- index.js (this is from mydep)
```

I would expect them to appear as:
The source maps in chrome devtools will appear as:

```
-- mydep (or even as a sub dir of node_modules)
  -- index.js
  -- cache
    -- index.js
-- src
  -- index.js
```
## 🔦 Context

Being able to correctly view sourcemaps for linked dependencies is useful when attempting to debug a package.

## 💻 Code Sample

just link any node_module w/ built source maps to your app

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.1
| Node             | v8.11.3
| npm              | 6.4.1
| Operating System | macos

**Comment by mischnic** [comment]
Current situation:
`parcel build index.html` (correct):
![build](https://user-images.githubusercontent.com/4586894/50973529-61aa5880-14e9-11e9-9755-208fca6c97b3.png)
`parcel index.html` (wrong):
![serve](https://user-images.githubusercontent.com/4586894/50973530-61aa5880-14e9-11e9-8889-8801307d71e8.png)


#2489 will make fix this last error.
