### ISSUE TITLE
css

### ISSUE THREAD

**Issue by cowDungIsFlowers** [parcel-bundler/parcel#2195]
Developed with parcel + vue, the styles in < style >< / style > in the Vue file sometimes don't work, and no changes have been made, the styles are still deleted, with caching effect.

**Comment by rambo-panda** [comment]
I have the same problem

https://github.com/parcel-bundler/parcel/issues/2199

**Comment by owenvip** [comment]
check the  version of vue

**Comment by DeMoorJasper** [comment]
closing in favor of #2199
