### ISSUE TITLE
.pcss don't work with parcel

### ISSUE THREAD

**Issue by ManzDev** [parcel-bundler/parcel#2196]
I setup a project with .pcss files from main HTML. I have `.postcssrc` config file for config some postcss plugins.

Parcel serve give me this error when save .pcss file (JS Console):
```
Uncaught Error: Cannot find module '../node_modules/parcel-bundler/src/builtins/css-loader.js'
```

If I change file.pcss to file.css works fine (but I need .pcss for postcss nested syntax and others).
If I save html file, works fine also.

**Comment by lil5** [comment]
Same with `.postcss` extention.
