### ISSUE TITLE
Lua asset type

### ISSUE THREAD

**Issue by daurnimator** [parcel-bundler/parcel#2202]
# 🙋 feature request

Allow loading+running lua code

## 🤔 Expected Behavior

  - Bundle lua code in as an asset
  - Preload the lua code into a [fengari-web](https://github.com/fengari-lua/fengari-web) state

## 💁 Possible Solution

Should be able to crib from the fengari webpack loader: https://github.com/fengari-lua/fengari-loader/#how-does-it-work

**Comment by Industrial** [comment]
Would LOVE to see this feature =)

**Comment by devongovett** [comment]
Going to close this. I don't have the bandwidth to implement and maintain this. It would be great as a third party plugin if someone wants to build it!
