### ISSUE TITLE
Extending EventEmitter throws error in production bundle when using --experimental-scope-hoisting flag

### ISSUE THREAD

**Issue by dugokontov** [parcel-bundler/parcel#2204]
# 🐛 bug report
Issue happens if you try to create a new class that extends EventEmitter. When I try to build code using tree shaking flag, I get error that global variable `EventEmitter` doesn't exist. Everything works fine in development mode, as well as build without experimental flag.

## 🤔 Expected Behavior
Application should work as it does in build without using experimental flag

## 😯 Current Behavior

I get following error in console:
```
Uncaught ReferenceError: EventEmitter is not defined
    at app.fc2a6f9a.js:1
    at app.fc2a6f9a.js:1
    at app.fc2a6f9a.js:1
(anonymous) @ app.fc2a6f9a.js:1
(anonymous) @ app.fc2a6f9a.js:1
(anonymous) @ app.fc2a6f9a.js:1
```

## 🔦 Context
Building code with tree shaking

## 💻 Code Sample
run `parcel build --experimental-scope-hoisting index.html` after cloning: 
https://github.com/dugokontov/parcel-tree-shaking-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.10.3
| Node             |8.11.1
| npm/Yarn         |6.4.1/1.10.0
| Operating System |Linux Mint 18.1 Serena

**Comment by dugokontov** [comment]
I've created even simpler example that renders only react component. I've created that component as a class that extends `React.Component`, but now I get error `Uncaught ReferenceError: React is not defined`. You can see example here: https://github.com/dugokontov/parcel-tree-shaking-bug/tree/react.

Is there any example of using `--experimental-scope-hoisting` with any react project? I'm pretty sure I'm doing something wrong, but I can't find in documentation if I need some additional files or configuration to make this work...

**Comment by mischnic** [comment]
This seems to happen with preact as well, even with just a single javascript file.
Could this have something to do with the babel class transform?

```jsx
import { h, render, Component } from "preact";

class App extends Component {
	render() {
		return (
			<span>Test</span>
		);
	}
}

render(<App />, document.getElementById("root"));

```

```js
var $Focm$var$App =
/*#__PURE__*/
function (_Component) {
  $Focm$var$_inherits(App, _Component);

  function App() {
    $Focm$var$_classCallCheck(this, App);
    return $Focm$var$_possibleConstructorReturn(this, $Focm$var$_getPrototypeOf(App).apply(this, arguments));
  }

  $Focm$var$_createClass(App, [{
    key: "render",
    value: function render() {
      return $qWa$export$h("span", null, "Test");
    }
  }]);
  return App;
}(Component); // <--- here
```
Full repo: https://github.com/mischnic/parcel-scope-hosting

**Comment by mischnic** [comment]
Adding `console.log(Component);` to my above code correctly produces: `console.log($qWa$export$Component);`

These three cases have always been the Identifier after `extends` that doens't get transformed correctly.

**Comment by mischnic** [comment]
Strange:
Assigning the imported Component to a variable and using that as the superclass works. Somethinges the `h` function (the JSX pragma) isn't getting renamed either.
This works however (so doing the jsx babel transform manually):
```jsx
import {Component, h, render} from "preact";

const ComponentXXX = Component;

class App extends ComponentXXX {
	render() {
		return (
			// <span>Test</span>
			h("span", null, "Test")
		);
	}
}


// render(<App />, document.getElementById("root"));
render(h(App, null, null), document.getElementById("root"));
```

**Comment by mischnic** [comment]
@fathyb (You seem to be the master of scope-hoisting and authored renamer.js)
Is there a reason not to use `scope.rename(oldName, newName)` here? My preact app runs fine with that change

https://github.com/parcel-bundler/parcel/blob/4773d65e7e3d012cb1f7350ad1bac6effd9d8832/packages/core/parcel-bundler/src/scope-hoisting/renamer.js#L1-L9

**Comment by fathyb** [comment]
Hey @mischnic, the reason we're using our own `rename` is performance. Everytime you call `scope.rename()` it visits the complete AST of the outermost `Scope`; this makes the scope-hoisting dramatically slower because we `.rename()` *a lot*. Our implementation batches the renames so that we only do this visit one time whatever the number of bindings to rename.

At the time we did this it made the scope-hoisting on a Vue app go from 109 seconds.
