### ISSUE TITLE
vuex mutations

### ISSUE THREAD

**Issue by cowDungIsFlowers** [parcel-bundler/parcel#2207]
Call the function in vuex mutations, the store data in Vuex will not change. If the current Vue file is changed and saved, the store data in Vuex will change immediately.

![n ltpw9k2 ps4fn2 9 a](https://user-images.githubusercontent.com/23652526/47601346-bcabd380-da01-11e8-87b5-d66af107029d.png)
![xv6g9 tj 9 ma9jdg_sbhr4](https://user-images.githubusercontent.com/23652526/47601347-c2a1b480-da01-11e8-83cc-d0507d7a8826.png)

**Comment by Hammster** [comment]
Can you share the code?

**Comment by cowDungIsFlowers** [comment]
@Hammster I look forward to your reply.

**Comment by Hammster** [comment]
This is now a very late reply, I did totally forget about this.

```js
computed: {
	count () {
		return store.state.count
	},
	title(){
		return store.state.title
	}
},
```

Is the issue here, it should be `this.$store.state.count` And your store should be attached to the root instance of the vue app (Which in your app is the case).
