### ISSUE TITLE
Build error with Ava unit testing for Node.js project

### ISSUE THREAD

**Issue by rajinder-yadav** [parcel-bundler/parcel#2213]
# 🐛 bug report

Unable to build and run Ava unit test using Parcel. 
The issue seems to be that a JavaScript module file will fail, but a Node.js module file will build and run.

I've included a sample test project to show this problem:

https://github.com/rajinder-yadav/ava-parcel-test

To see the error, install the NPM modules and run the test

```sh
1. npm install
1. npm test
```
Open file `utils.js` and read comment for further investigation clues.

## 🔦 Context

I am unable to run all my Node.js unit test using Ava.

Make sure to read comment in code for clues.

## 💻 Code Sample

See top!

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | "^1.10.3"
| Node             | v10.11.0
| npm/Yarn         | 6.4.1
| Operating System | Linux 4.15.0-38-generic

**Comment by daniellacosse** [comment]
Did you ever get this working? I think I'm running into this issue now

**Comment by mischnic** [comment]
Could someone provide a reproduction? The repo in the original post was deleted.

**Comment by daniellacosse** [comment]
Yeah, which is why I'm not super certain if this is the same as my issue.

If you pull down https://github.com/daniellacosse/accounting-cli/tree/makefile-2 and run `make test` the tests pass but you get the following output in each of the built files:

```
 .../dist/trello-scripts/__tests__/label-rollup.test.js:110

   109:   }                                                
   110:                                                    
   111:   // Override the current require with this new one

  ReferenceError: parcelRequire is not defined

  parcelRequire.rl8J (dist/trello-scripts/__tests__/label-rollup.test.js:110:17)
  Object.<anonymous> (dist/trello-scripts/__tests__/label-rollup.test.js:118:2)
```

could be related to https://github.com/parcel-bundler/parcel/issues/1159 ?

**Comment by mischnic** [comment]
It seems like ava executes the file as an ES module (in strict mode).
@devongovett, 
#2839

**Comment by engineforce** [comment]
Hi parcel developers, [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) may solve this issue.
