### ISSUE TITLE
Allow .babelrc.json config

### ISSUE THREAD

**Issue by linvain** [parcel-bundler/parcel#2219]
# 🙋 feature request

Allow `.babelrc.json` config

## 😯 Current Behavior

Parcel doesn't search for `.babelrc.json`, only for `.babelrc`

## 🔦 Context

Other tools work just ok with configs named `.prettierrc.json` and `.stylelintrc.json`.

`.babelrc.json` would allow for better consistency and JSON syntax highlighting

**Comment by peanutbother** [comment]
If you are working with an IDE like Atom or VS Code likewise you can meanwhile add a custom file extension type to add syntax highlighting to `.babelrc` .

As long as parcel doesn't treat `.babelrc.json` you might want to consider this functionaity in your IDE.
for VS Code see https://stackoverflow.com/a/36789145/3793309
for Atom see https://atom.io/packages/file-types

**Comment by devongovett** [comment]
This is not a natively supported filename in babel, so we won't support this in Parcel. https://babeljs.io/docs/en/config-files

Please file an issue with babel if you want them to add support for babelrc.json.

**Comment by linvain** [comment]
@devongovett I don't know whether parcel supports `.babelrc.json` or not but `.babelrc.json` is now mentioned in https://babeljs.io/docs/en/config-files :)

**Comment by padmaia** [comment]
@linvain Parcel 2 uses Babel to resolve Babel configuration, so anything supported by Babel should work (including .babelrc.json 🙂)
