### ISSUE TITLE
Accessing Javascript from non-module code

### ISSUE THREAD

**Issue by Timmmm** [parcel-bundler/parcel#2226]
Suppose I have a library, perhaps D3 (installed via `npm`), and I want to include it like this:

	<script src="../node_modules/d3/dist/d3.min.js"></script>

Then I want to access it from non-module code (for example the developer console) like:

    d3.whatever();

This does not work. I'm not too familiar with JS modules (partly because they seem to be a huge mess of similar but incompatible options), but it seems like Parcel always wraps `d3.min.js` in its own module-related code, even if you don't have `type="module"`.

Is there a way to do something like this?

    let d3 = parcel.require("d3.js");

Or some way to tell Parcel to just copy the file and don't process it?

**Comment by toxicFork** [comment]
I have the same problem, this does not work:

```html
<script type="text/javascript" src="./node_modules/react/umd/react.development.js"></script>
<script type="text/javascript" src="./node_modules/react-dom/umd/react-dom.development.js"></script>
<script>console.log(React);</script>
```

**Comment by toxicFork** [comment]
However, this seems to work:
```html
<script src="./node_modules/react/umd/react.development.js" type="text/javascript"></script>
<script>const React = parcelRequire("node_modules/react/umd/react.development.js");</script>
<script src="./node_modules/react-dom/umd/react-dom.development.js" type="text/javascript"></script>
<script>const ReactDOM = parcelRequire("node_modules/react-dom/umd/react-dom.development.js");</script>

<script>console.log(React);</script>
```

**Comment by devongovett** [comment]
What's the usecase for this? Why not just use normal `require('d3')` in your script?
