### ISSUE TITLE
Problem with autoprefixer

### ISSUE THREAD

**Issue by STurbiarz** [parcel-bundler/parcel#2227]
I add 
$ npm install postcss-modules autoprefixer

Then creacte file .postcssrc

with
{
  "modules": true,
  "plugins": {
    "autoprefixer": true
  }
}

and nothing.. style in dist folder include only converted sass file, without add prefixes..
How to solve it?

| Software        
| MacOs 10.14.1 
| Parcel   last version

**Comment by 9oelM** [comment]
try 
```
"autoprefixer": {}
```

or something like
```
"postcss": {
    "modules": true,
    "plugins": {
      "autoprefixer": {
        "browsers": [
          ">1%",
          "last 4 versions",
          "Firefox ESR",
          "not ie < 9"
        ],
        "flexbox": "no-2009"
      }
    }
  }
```
