### ISSUE TITLE
Parcel not reloading on save due to name of parent folder. 

### ISSUE THREAD

**Issue by RustyRaptor** [parcel-bundler/parcel#2231]
# 🐛 bug report

Parcel is not rebuilding or reloading the dev server when I save files. 

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json:
```
{
  "name": "nmeistheenemy",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

## 🤔 Expected Behavior

should rebuild and reload the page. 

## 😯 Current Behavior

doesn't 

There is no error. 

## 🔦 Context

I am running the most basic program to see why this is happening. 
index.html:
```
<html>
<body>
  <script src="./index.js"></script>
</body>
</html>
```
index.js

```
console.log("hello");
console.log("world");
```

## 🌍 Your Environment
I am using Ubuntu 18.04 with the latest version of Parcel on npm. I am using Visual Studio code to edit the code but I also tried this by directly using the echo command on the file as well as some other text editors.

I tried changing the watch limit for inotify in the OS with 
```
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

As well as editing the config file and increasing the watches value to 999999 

I also tried to see if it was the "safe write" in editors but it's clearly not as VS code doesn't use safe write and I tried writing directly to the files. 

I had this issue with webpack as well but I fixed it with the file watch limit fix. I am moving to parcel because it's much easier to use for small projects. 

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3 |
| Node             | 10.6.0|
| npm/Yarn         | 6.1.0, yarn is 1.10.1 (i tried both yarn and npm for the project)|
| Operating System | Ubuntu 18.04 LTS|

**Comment by RustyRaptor** [comment]
Ok so I found that other thread where the issue is the folder name being x.github.io and I now realize that this is the case for me as well. The parent folder of the folder the project is in was called rustyraptor.github.io. Go figure. So this is just a duplicate of that bug.

**Comment by RustyRaptor** [comment]
#2093

**Comment by DeMoorJasper** [comment]
Closing as its a duplicate

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
