### ISSUE TITLE
HMR could be improved by separating configuration what frontend does and what the server does.

### ISSUE THREAD

**Issue by txthinking** [parcel-bundler/parcel#2236]
# 🙋 feature request

HMR could be improved by separating configuration what frontend does and what the server does.
Something like:

```
--port 1234 # parcel http listens on this port
--hmr-port 1235 # parcel websocket listens on this port
--hmr-address-on-browser https://example.com # browser sends request to this address
```

## 🤔 Expected Behavior

```
# nginx proxy server on example.com
proxy http port 443 to 127.0.0.1:1234
proxy websocket 443 to 127.0.0.1:1235
```

So, we can develop on https://example.com

## 😯 Current Behavior

parcel browser websocket send request to http://127.0.0.1:1235, we can't change it.

**Comment by txthinking** [comment]
Related: https://github.com/parcel-bundler/parcel/issues/1262#issuecomment-431311577

**Comment by txthinking** [comment]
Would that be considered acceptable PR? 🙃

**Comment by DeMoorJasper** [comment]
This has already been fixed in Parcel 1 and 2
