### ISSUE TITLE
Using Parcel reload content with custom server due to server-side-templates, etc.

### ISSUE THREAD

**Issue by sphet** [parcel-bundler/parcel#2244]
# ❔ Question

We use flask and the Mako templating engine with a Twisted web server. It is used both for our REST api and for serving up pages. Some of these pages use react components built with Parcel. How can we get the hot-load functionality working with out custom web server, since we don't have an index.html -- it is generated via the templating engine.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | any
| Node             | any
| npm/Yarn         | any
| Operating System | Windows/Ubuntu

**Comment by DeMoorJasper** [comment]
Parcel does not require a html page as entrypoint you could also provide JS or multiple Js entrypoints or any other kind of file parcel supports

**Comment by sphet** [comment]
@DeMoorJasper This doesn't solve the problem for me -- I have server-side templates provided via a flask server, so to get my react components served up I need to serve them via my own server, not the parcel server. I am trying to figure out how to handle hot loading in this case. Does that make sense?

**Comment by DeMoorJasper** [comment]
I'm confused as how this wouldn't solve the issue?

Use `parcel watch index.js` and it should only watch and rebuild the JS, not sure what would be dynamic about JS. 

If js is dynamic it's probably not a good idea to do it or to use a bundler. Probably better to use JSON endpoints for dynamic content in JS (but this is probably not the case and you probably just misunderstood my reply)

**Comment by DeMoorJasper** [comment]
Glad to hear you got it to work :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
