### ISSUE TITLE
Parser doesn't recognise file extensions with multiple dots

### ISSUE THREAD

**Issue by georgecrawford** [parcel-bundler/parcel#2249]
# 🐛 bug report

I'd like to add a custom Asset for files with the extension `.tpl.html`. Since the Parser uses `path.extname` (see https://github.com/parcel-bundler/parcel/blob/1.x/src/Parser.js#L73), which does not support this use case, I'm unable to do so.

I'd consider this a bug. I'd be interested to hear the thoughts of the Parcel team as to whether you'd accept a PR to fix it?

## 🤔 Expected Behavior

`bundler.addAssetType('tpl.html', templateAssetPath);` should use my asset class for files such as `file.tpl.html`.

## 😯 Current Behavior

`bundler.addAssetType('tpl.html', templateAssetPath);` uses the default HTML asset, as the extension 'appears' to be `.html`.

## 💁 Possible Solution

Use a library such as https://github.com/ruyadorno/path-complete-extname, or a cruder method.

**Comment by devongovett** [comment]
This will be supported in Parcel 2 since we will use globs to match asset types.

**Comment by georgecrawford** [comment]
Good stuff. Thanks Devon. What's your feeling about an ETA? I'm migrating a large project over to Parcel, and would love to set expectations to the team.

**Comment by devongovett** [comment]
I was hoping end of year but that might be too optimistic. Currently the core is getting close, but we still need to convert over all the built-in plugins, of which there are many. Perhaps the community can help out with that to speed it along. I hope to at least start releasing alphas soon.

**Comment by georgecrawford** [comment]
Do you have a clear set of tasks and guidance for community contributions for v2? From my POV, the tickets at https://github.com/parcel-bundler/parcel/projects/5 require too much background knowledge for me to approach.

**Comment by rambo-panda** [comment]
@devongovett
1.x is it still under maintenance?

Because I fixed some bug and what I thought was feature on our company project for version 1.10.3

**Comment by devongovett** [comment]
@rambo-panda 1.x is still under maintenance yes.

@georgecrawford we will have more details soon, once the core is more fleshed out.

**Comment by quadrupleslap** [comment]
Isn't this the same issue as #1501?

**Comment by georgecrawford** [comment]
Yeah, it's a dupe. The suggestion by @DeMoorJasper at https://github.com/parcel-bundler/parcel/issues/1501#issuecomment-406008614 would work for me, as long as `known extensions` includes those that I register myself with `addAssetType`.
