### ISSUE TITLE
Documentation for args?

### ISSUE THREAD

**Issue by sarahbethfederman** [parcel-bundler/parcel#225]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
🙋

I see some comments on issues that add flags like `--no-minify` 
Is there any documentation that details what's available as options? Would be nice! A simple table view would suffice

**Comment by DeMoorJasper** [comment]
It's in a PR on the website repo https://github.com/parcel-bundler/website/pull/30

**Comment by davidnagli** [comment]
Can we close this issue?

**Comment by sarahbethfederman** [comment]
thanks!
