### ISSUE TITLE
How to dynamically import images into VanillaJS

### ISSUE THREAD

**Issue by codenamics** [parcel-bundler/parcel#2250]
# ❔ Question

I am trying to change my background image based on value that is coming from API. So when from API value is 'partly-cloudy-night' i have same image name partly-cloudy-night.jpg to display. But.... As Parcel is working on static assets i get this error

GET http://localhost:1234/assets/images/bg-images/partly-cloudy-day.jpg 404 (Not Found)

which is saying that image can't be found.

## 🔦 Context

Image not found

## 💻 Code Sample

```
const displayWeatherData = (data, location) => {
     let {
           icon,
           summary
        } = data.currently

        document.querySelectorAll(".location-label").forEach(el =>
            el.innerHTML = location
        )

        document.querySelector('main').style.backgroundImage = 
        `url("./assets/images/bg-images/${icon}.jpg")` <== here
        }

    }
```

## 🌍 Your Environment

| Parcel         1.10.3  |
| Node           8.11.2  |
| npm/Yarn        npm |
| Operating System MacOS|

**Comment by devongovett** [comment]
You can import a url to a static file like `import imageUrl from './images/foo.jpg'`. If you want a whole directory of images, you can use globs: `import imageUrls from './images/*.jpg'` and access like `imageUrls["foo"]`.

**Comment by codenamics** [comment]
works great thanks!
