### ISSUE TITLE
Must I create babalrc and setup my babel configuration?

### ISSUE THREAD

**Issue by tun100** [parcel-bundler/parcel#2252]
# ❔ Question
Must I create babelrc and setup my babel configuration?

## 🔦 Context

Hello,guys! I encount a babel error when i startup parcel project by command `parcel index.html`, it's mainly error msg is `Cannot read property 'key' of undefined`, and i don't know where the line number is, i only know that file contains a syntax that babel cannot understand.    
After checkout, I found out, the syntax  `function li(a=3332){}` default parameter value, cannot parse for babel. And then i remove the React, and still report there's a error.     
I have no idea, so i clear the .babelrc file in my project, and rm .cache folder, and exec command again.GOD, the command is successlly run, and no wrong, so i wonder: if I wanna compile the new syntax into old syntax, Must I configure my own babel configuration? Or Parcel program will auto judge by my code syntax style? Thanks!

## 💻 Code Sample
No Code, Sorry

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel        1.10.7   |
| Node          8.4.0   |
| npm/Yarn      5.5.0   |
| Operating System Ubuntu 16.04 LTS |

**Comment by devongovett** [comment]
Perhaps this is a bug in babel?
