### ISSUE TITLE
Allow Web Worker path to be specified by an argument

### ISSUE THREAD

**Issue by dusty** [parcel-bundler/parcel#2257]
# 🐛 bug report

If I declare a web worker like this

```
const src = './my.worker.js'
const worker = new Worker(src)
```

Parcel does not bundle a web worker file.  I believe that it is because of this line where it requires a string literal for the argument.

https://github.com/parcel-bundler/parcel/blob/75310e15f6fa3c8a0ce6593ada1bcca00240ea54/packages/core/parcel-bundler/src/visitors/dependencies.js#L85

I have a wrapper that creates web workers attached to a queue and its convenient to pass in the path of the file to generate the worker.  For now, I have to work around it like so

```
let worker
if (src === 'something') {
  worker = new Worker('./path/to/something')
} else if (src === 'somethingelse') {
  worker = new Worker('./path/to/something/else')
}
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties"
  ]
}
```

## 🤔 Expected Behavior

It would be nice if we could pass an argument to new Worker and still get the same behavior from parcel.

## 😯 Current Behavior

The file is not bundled, which results in a 404

## 💁 Possible Solution

I'm not certain why the isStringLiteral is required, maybe that is to differentiate against a blob url?  If that is the only case, then perhaps it could be changed to look for the absence of blob?  Unless there are other reasons.

```
/^blob/.test(args[0])
```

## 🔦 Context

Launch different workers based on state of the app.

## 💻 Code Sample

```
    const src = './tester.worker.js'
    const worker = new Worker(src)
```

## 🌍 Your Environment

- osx 10.14
- node v10.13.0
- parcel 1.10.3

**Comment by devongovett** [comment]
This is pretty much impossible to do in a reliable way at build time. We mostly cannot know what the variable you pass to the Worker constructor will be, except in really simple cases. If there is anything conditional, it will be impossible.
