### ISSUE TITLE
Switch from toml to @iarna/toml

### ISSUE THREAD

**Issue by ABuffSeagull** [parcel-bundler/parcel#2258]
# 💬 RFC

I noticed that y'all are using the [`toml`](https://github.com/BinaryMuse/toml-node) package for dealing with toml files, and that package seems abandoned. Last commit was August 31st, 2017, and it also only supports v0.4.0 of the spec, while the most recent version is v0.5.0.

## 🔦 Context

I've run into issues with this package such as trying to use dotted keys, thinking that they should work since the v0.5.0 spec is the one you get when you google toml. And I would imagine other people probably run into these kinds of problems too.

## 💻 Examples

I would suggest changing over to [`@iarna/toml`](https://github.com/iarna/iarna-toml), as that package supports the latest spec, as well as many other features (25x faster than `toml`, apparently). Plus, it also supports encoding as well as decoding, so you can also remove `tomlify-j0.4` and have less dependencies.

I would make a pull request, but I don't (currently) know how to work with Lerna.
(also, I'm not sure if an RFC was the right thing to open, I'm still a bit new to the open source community)

**Comment by devongovett** [comment]
Please make a PR!
