### ISSUE TITLE
Is there a way to get the final hash of the compiled file?

### ISSUE THREAD

**Issue by rambo-panda** [parcel-bundler/parcel#2260]
# 🙋 feature request

Is there a way to get the final hash of the compiled file?

I encountered a situation where the file hash did not change while executing the `npx parcel build xxx`.

I don't know if this is the original intention of `parceljs` design.

### Here is my code
```js
// app.js
import('./b.js').then(x=>{
});

// b.js
export default () => {};   //  1
export default () => {console.log(1);} // 2
```
### Here is my result
**b.af4e6e5c.js**   **app.d2aa9ebe.js**  when `b.js` use *1*
**b.b33eccac.js**  **app.d2aa9ebe.js**  when `b.js` use *2*

## 😯 Current Behavior

After the compilation is finished, calculate the hash again.

**Comment by vyteniskuciauskas-home24** [comment]
make sure `dist` directory is cleared before build.

**Comment by rambo-panda** [comment]
@vyteniskuciauskas-home24 
yeah

this is my `build script`
```
rm -rf .cache ./dist && NODE_ENV=production npx parcel build XXX
```

**Comment by devongovett** [comment]
Duplicate of #1481
