### ISSUE TITLE
PostCSS error

### ISSUE THREAD

**Issue by ZhaoruiGuang** [parcel-bundler/parcel#2264]
项目添加 css 文件后，执行启动命令时（parcel  index.html），parcel 会自动下载安装 autoprefixer、cssnext、CSS Modules 等插件，，之后不做任何操作，直接执行构建命令（parcel  build index.html），就会报错。。。为什么自动安装的东西还会报错？
报错信息如下：
Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.23, but postcss-modules uses 7.0.5. Perhaps this is the source of the error below.

**Comment by DeMoorJasper** [comment]
Could you please use the issue template provided, and preferably provide an English version of your issue. (even if you have to use google translate)

**Comment by jhpratt** [comment]
Related: ben-eb/postcss-convert-values#27. Should be fixed by ben-eb/postcss-convert-values#39.

**Comment by jhpratt** [comment]
^ This has been fixed. @DeMoorJasper it's probably best to change the labels on this issue?
