### ISSUE TITLE
Load component from JSON

### ISSUE THREAD

**Issue by cgishack** [parcel-bundler/parcel#2265]
# ❔ Question

Hello, 
I am trying to find a way to load a component based off a JSON configuration file.
To test, I have a sample with an array of components but this is throwing an error.
Any ideas on how to achieve this? - see code sample

**Browser Error**
> TypeError: Failed to fetch dynamically imported module: http://localhost:1234/js/widget1.js

## 🔦 Context

Not able to load components dynamically.

## 💻 Code Sample

 var widgets = [
        '../js/widget1.js',
        '../js/widget2.js',
        '../js/widget3.js'
      ]

      import(widgets[0]).then(function(Widget)
       {
         alert('Widget 1 Loaded!')
          
      })

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             |
| npm/Yarn         |
| Operating System | Windows 10

**Comment by devongovett** [comment]
Parcel only supports statically defined imports, e.g. `import('../js/widget1.js')`. Variables cannot be passed to the `import` function. Parcel just ignores the import in that case and leaves it up to the browser, which is why you see that error.

I'd suggest doing something like this:

```javascript
var widgets = [
  import( '../js/widget1.js'),
  import('../js/widget2.js'),
  import( '../js/widget3.js')
];

widgets[0].then(function(Widget) {
   alert('Widget 1 Loaded!')   
})
```
