### ISSUE TITLE
Project-relative glob imports are resolved as absolute paths.

### ISSUE THREAD

**Issue by quadrupleslap** [parcel-bundler/parcel#2273]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

No configuration.

## 💻 Code Sample

```
project/
    documents/
        a.json
        b.json
    reader.js
    index.html
```

```js
// reader.js

import documents as '/documents/*.json';
```

## 🤔 Expected Behavior

```js
documents = { a: Object, b: Object }
```

## 😯 Current Behavior

```js
documents = {}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3 |
| Node             | 10.12.0 |
| npm/Yarn         | NPM 6.4.1 |
| Operating System | Linux |

**Comment by nolandg** [comment]
It seems you cannot combine globs with either absolute or tilde paths? Globs only seem to work for relative paths.

**Comment by valentinradu** [comment]
This is a valid bug. Happens here as well. Reopen maybe?

**Comment by DeMoorJasper** [comment]
You can use relative paths, they work. Also globs have been removed in Parcel 2 anyway
