### ISSUE TITLE
MaxListenersExceededWarning tips

### ISSUE THREAD

**Issue by ken30huang** [parcel-bundler/parcel#2277]
# ❔ Question

I use react16.x and parcel develop my project，when running parcel server , there is some message output to CMD window: 
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 buildEnd listeners added. Use emitter.setMaxListeners() to increase limit

And project still working , but some times is normal , nothing output

Please help

## 🔦 Context

My package.json file:
```
{
	"name": "qfd_offical",
	"version": "1.0.0",
	"description": "",
	"main": "index.js",
	"scripts": {
		"test": "echo \"Error: no test specified\" && exit 1",
		"start": "parcel index.html product.html solution.html service.html aboutus.html case.html case_detail.html newsDetail.html --no-cache",
		"build": "parcel build index.html product.html solution.html service.html aboutus.html case.html case_detail.html newsDetail.html --no-cache --out-dir build/public --public-url ./public"
	},
	"keywords": [],
	"author": "",
	"license": "ISC",
	"dependencies": {
		"assets": "^3.0.0",
		"react": "^16.6.0",
		"react-dom": "^16.6.0"
	},
	"devDependencies": {
		"babel-core": "^6.26.3",
		"babel-preset-env": "^1.7.0",
		"babel-preset-react": "^6.24.1",
		"cssnano": "^4.1.7"
	}
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             | v8.11.1
| npm/Yarn         |  5.6.0
| Operating System |  Windows

**Comment by DeMoorJasper** [comment]
Are you using any plugins?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ken30huang** [comment]
> Are you using any parcel plugins?
> 
> Sent with [GitHawk](http://githawk.com)

I don't use any parcel plugins ， you can see package.json

**Comment by JelleHol** [comment]
I'm also having this problem - Parcel just randomly starts rebuilding everything, showing this warning in the console. It might be Node-related, because all running instances of Parcel do it at exactly the same time.

Furthermore, it outputs multiple "Built in X ms" messages when it's done, showing impossibly short building times (<100 ms).

I'm using Windows 10. Teammates on MacOS are **not** having this issue.

**Comment by oL-web** [comment]
this often happens after leaving parcel running idle for a while. the next time you save a watched file parcel goes crazy with rebuilding.

i'm also on node 8.11. perhaps someone could jump a few node versions up and down to see if that's the cause of the problem.

**Comment by JelleHol** [comment]
Just confirmed this happens also with node 9.10.1 and 10.12.0

**Comment by DeMoorJasper** [comment]
Anyone who has an example project because I’ve never experienced this

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ken30huang** [comment]
> Anyone who has an example project ? Because I’ve never experienced this
> 
> Sent with [GitHawk](http://githawk.com)

OK , get it. I will let you know when I sent.

**Comment by alidcastano** [comment]
@DeMoorJasper recently gave another attempt at integrating [rogue](https://github.com/alidcastano/rogue.js) with Parcel. it's running a lot smoother now, but this is one of the issues i am experiencing. Not sure if it's related to running two bundles at the same time for server side rendering. @DeMoorJasper you didn't see this at all with blazingly? 

also seeing running into random infinite loops during HMR https://github.com/parcel-bundler/parcel/issues/1317


the setup for Rogue is pretty minimal https://github.com/alidcastano/rogue.js/blob/master/packages/cli/lib/bundle.js

**Comment by alidcastano** [comment]
@DeMoorJasper I'm on windows, so issue might be specific to environment then given comments on issue.

Do you have an estimate on when Parcel 2 will be alpha released?

**Comment by DeMoorJasper** [comment]
@alidcastano it might be a windows issue not sure, as you can see in the issue the cause has never been discovered.

I don't know when the alpha is gonna be released. You can follow progress here: https://github.com/parcel-bundler/parcel/pull/2218

**Comment by JelleHol** [comment]
My hunch is that it has something to do with this issue in chokidar: [#750](https://github.com/paulmillr/chokidar/issues/750)

**Comment by JelleHol** [comment]
So I've been working for a while with file access disabled, and this problem has not occurred anymore. However, I am having a hard time reproducing this behavior in another repository (with it enabled of course). It only seems to happen in very large projects with many dependencies and files.
