### ISSUE TITLE
Start server through api

### ISSUE THREAD

**Issue by SpectralKH** [parcel-bundler/parcel#2280]
# 🙋 feature request

Would be very nice if you could start the built-in localhost:3000 server through the parcel JS API.

## 💁 Possible Solution

```js
const Bundler = require('parcel-bundler')
new Bundler('index.html', {
  watch: true,
  server: true,
  serverPort: 3000
}).bundle()
```

## 🔦 Context

Just want to use Parcel as you would through CLI. I'm running the API through Gulp.

**Comment by DeMoorJasper** [comment]
It’s already possible

```
let bundler = new Bundler(...)
// start http server
bundler.serve(...)
```

As far as I know this is documented in the docs

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SpectralKH** [comment]
@DeMoorJasper Thank you, that makes method makes a lot of sense.

The Bundler API documentation has a bunch of examples that use `.bundle()`, but there is nothing about `.serve()`.

Is it to be expected that `http://localhost:1234` gets a 404 while `http://localhost:1234/index.html` works?

**Comment by SpectralKH** [comment]
@devongovett The .serve() method still needs to be documented. afaik only .bundle() is documented.

**Comment by 0m15** [comment]
Hi, first sorry If I'm writing here, but maybe I'm not the only one experiencing this issue.
I'm trying to use the basic example to use parcel bundler via api:

This is the script I'm using:

```
const Bundler = require("parcel-bundler")
const Path = require("path")

const file = Path.join(__dirname, "./index.html")

const options = {
  outDir: "./dist",
  outFile: "index.html",
  publicUrl: "./",
  watch: true,
  cache: true,
  cacheDir: ".cache",
  minify: false,
  target: "browser",
  https: false,
  logLevel: 3,
  hmrPort: 0,
  sourceMaps: true,
  hmrHostname: "",
  detailedReport: false
}

const bundler = new Bundler(file, options)

bundler.bundle().then(() => {
  bundler.serve()
})

```

Everything seems to works fine (console gives no errors or warns), but when I open the url on the browser I get this exception:

`Uncaught SyntaxError: Unexpected token < in <my-bundle-name>.js`

By looking at the bundled source I see it contains the source of index.html.

Am I doing something wrong in the config, or is there particular behaviour when using parcel from 
api?

Note that if I run parcel from the cli, everything works fine.

Parcel version: 1.10.3

**Comment by 0m15** [comment]
Just a quick update: if I don't pass any options to Bundler, everything works fine.

**Comment by 0m15** [comment]
@SpectralKH oh, what a fool! I totally missed it. Thanks.

**Comment by mirko-incomedia** [comment]
https://github.com/parcel-bundler/website/pull/569
