### ISSUE TITLE
Providing asset configs directly to the API instead of by using files

### ISSUE THREAD

**Issue by SpectralKH** [parcel-bundler/parcel#2281]
# 🙋 feature request

I would like to have the ability to pass my Pug (in my scenario) configuration through the JS API's options.

## 💁 Possible Solution

```js
const Bundler = require('parcel-bundler')
const pugOptions = {
  locals: {
    env: 'production'
  }
}
new Bundler('index.html', {
  configFiles: {
    '.pugrc': pugOptions
  }
}).bundle()
```

## 🔦 Context

In my case, I use Gulp and I only pass one variable to Pug. It would make a lot of sense to provide the options inside my gulpfile.js since this is what you would do with any other Pug compiler. It would also be nice to say bye to the almost empty `.pugrc` file.

Currently, I set an environment variable inside the gulpfile, and read this environment variable in the `.pugrc` file.

**Comment by devongovett** [comment]
This will not be supported. The reason we use separate files for configuring tools other than parcel itself is to prevent lock-in and allow other tools to reuse the same config. Your .pugrc or .babelrc file for example should be able to be used by babel or pug itself, or by other tools like testing frameworks etc.

**Comment by SpectralKH** [comment]
@devongovett But Pug itself can't read .pugrc, and Babel often gives you the option to pass options directly (for instance with gulp-babel it seems to be the standard way to do it). Surely those cases are equally bad for using testing frameworks? So I don't really see the reason for this.
