### ISSUE TITLE
Workaround for pug.config.js being cached?

### ISSUE THREAD

**Issue by probablykasper** [parcel-bundler/parcel#2282]
# ❔ Question

I have Pug locals that change depending on an environment variable, but Parcel seems to be caching the `pug.config.js`. Is there any way to fix this without completely disabling caching?

## 💻 Code Sample

```js
// pug.config.js
module.exports = {
  locals: {
    buildAs: process.env.BUILD_AS
  }
}

// gulpfile.js
async function bundle (options) {
  const Bundler = require('parcel-bundler')
  process.env.BUILD_AS = options.buildAs
  await new Bundler(src, {
    watch: options.watch
  }).bundle()
}
gulp.task('website:bundle', () => {
  return bundle({ watch: false, buildAs: 'website' })
})
gulp.task('extension:bundle', () => {
  return bundle({ watch: false, buildAs: 'extension' })
})
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             | 11.1.0
| npm         | 6.4.1
| Operating System | macOS 10.13.6

**Comment by DeMoorJasper** [comment]
Parcel should automatically invalidate on changes to environment variables or changes in the config file. This might be a bug, could you make a minimal example on how to reproduce this (preferably with an example repo)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SpectralKH** [comment]
@DeMoorJasper https://github.com/SpectralKH/parcel-cache-bug-repo

Renders `src/index.pug` into `build/index.html` and adds the environment variable `BUILD_AS` as a class on the `body` element.

Run `gulp website` and you'll see it adds the `website` class. Run `gulp extension`, and nothing changes. Delete `.cache` and re-run `gulp extension`, and it works.

**Comment by ZiFFeL1992** [comment]
For now you can:

`touch -a -m <pugfile>`

which will modify file access time and therefor invalidates cache ;)
