### ISSUE TITLE
I tried to build a vue project with parcel and now fails……or said, I got some error

### ISSUE THREAD

**Issue by wqcstrong** [parcel-bundler/parcel#229]
I just tried to build a vue project and set the directory structure to be similar to the vue-cli generated project. And I got some error after just used vue-router function.
The error is:
```
[vue-router] route config "component" for path: / cannot be a string id. Use an actual component instead.
```
Following is my directory structure :
```
- Parcel
   - node_modules
   - src
      - components
         - Index.vue
      - router
         - index.js
      - App.vue
      - main.js
   - index.html
   - package.json
```
In order to see more clearly, I wrote out part of the source code demo:
- index.html :
```
<body>
    <div id="app"></div>
    <script src="./src/main.js"></script>
</body>
```
- src/main.js
```
import Vue from 'vue'
import router from './router/index.js'
import App from './App.vue'

Vue.config.productionTip = false
new Vue({
    el: "#app",
    router,
    template: '<App/>',
    components: { App }
})
```
- src/App.vue:
```
<template>
    <div id="app">
        <h1>App Page</h1>
        <router-view></router-view>
    </div>
</template>
```
- router/index.js
```
import Vue from 'vue'
import Router from 'vue-router'
import Index from '../components/Index.vue'

Vue.use(Router);
export default new Router({
    routes: [
        {
            path: '/',
            component: Index
        }
    ]
})
```

**Comment by wqcstrong** [comment]
[error information](https://i.stack.imgur.com/ZdcXO.png)

**Comment by wqcstrong** [comment]
错误截图：[error screenshots](https://i.stack.imgur.com/ZdcXO.png)

**Comment by erguotou520** [comment]
哥，不是这么玩的，你不能直接`import .vue`文件

**Comment by wqcstrong** [comment]
@erguotou520 那应该怎么做呢

**Comment by wqcstrong** [comment]
@erguotou520 大佬可以加微信私聊一下吗

**Comment by erguotou520** [comment]
目前（应该还没有）还不支持`.vue`直接加载的方式，`vue`那边也在做[相关的工作](https://github.com/vuejs/vue-component-compiler/issues/28)，后续应该可以有支持。目前的做法是建议直接用`.js`文件，用render函数渲染

**Comment by wqcstrong** [comment]
@erguotou520 pk，谢谢指点！

**Comment by erguotou520** [comment]
可以看下我这个#93 里的项目

**Comment by erguotou520** [comment]
Yes, should be closed.

**Comment by wqcstrong** [comment]
@davidnagli OK, do it.

**Comment by trustgig** [comment]
Thank you.

**Comment by lc60005457** [comment]
@wqcstrong Try this https://github.com/lc60005457/parcel-plugin-vue
