### ISSUE TITLE
Assets loaded more than once when server starts

### ISSUE THREAD

**Issue by clintharris** [parcel-bundler/parcel#2294]
# 🐛 bug report

When running `bundler.serve()`, assets seem to be loaded *twice* during the _first_ pass at bundling everything (from that point on, they are only loaded once whenever a file is changed).

More specifically, my asset plugin's `load()` method gets called *twice* for every asset when the server is building the first bundle during startup.

## 🤔 Expected Behavior

`load()` is only called once per asset during startup.

## 😯 Current Behavior

`load()` is called *twice* per asset during startup.

Note: after the first bundle operation finishes, `load()` is only called _once_ per asset when an asset is modified (which is expected).

## 🔦 Context

I'm working on on a [plugin for running tslint](https://github.com/clintharris/parcel-plugin-tslint) on TypeScript assets Specifically, my plugin's `load()` implementation runs tslint (see code sample below).

Since `load()` is called twice per asset while the server is doing the initial bundling, files are being linted twice. This results in linting errors being shown twice.

## 💻 Code Sample

You can run/see the behavior using a simplified bug demo project I created here: https://github.com/clintharris/parcel-plugin-multiloading-assets-bug-demo.
```
$ git clone git@github.com:clintharris/parcel-plugin-multiloading-assets-bug-demo.git
$ cd parcel-plugin-multiloading-assets-bug-demo
$ yarn install
$ yarn testServe
yarn run v1.12.3
$ # Note how app.js is loaded twice here 👇
$ node testServe.js
Server running at http://localhost:1234
⠋ Building...📄 ❗️ Loading asset: app.js
⠹ Packaging...📄 ❗️ Loading asset: ../node_modules/parcel-bundler/src/builtins/hmr-runtime.js
✨  Built in 523ms.
📄 ❗️ Loading asset: app.js
📄 ❗️ Loading asset: ../node_modules/parcel-bundler/src/builtins/hmr-runtime.js
```
```
// testServe.js
const Path = require('path');
const Bundler = require('parcel-bundler');

const loadBugDemoPlugin = require('./index');
let bundler = new Bundler(
  Path.join(__dirname, 'sample_app', 'index.html'), {
    outDir: Path.join(__dirname, 'sample_app', 'dist'),
    hmr: true,
    cache: false
});
loadBugDemoPlugin(bundler);
bundler.serve();
```
```
// index.js
module.exports = function(bundler) {
  bundler.addAssetType('js', require.resolve('./src/MyAsset.js'));
}
```
```
// MyAsset.js
class MyAsset extends JSAsset {
  async load() {
    console.warn('📄 ❗️ Loading asset:', this.relativeName)
    return await super.load();
  }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.3
| Node             |  8.12.0
| npm/Yarn         |  yarn 1.12.3
| Operating System | macOS 10.14

**Comment by devongovett** [comment]
Parcel's worker farm uses a warmup phase. Since workers can be slow to start up, Parcel runs transforms on the main process simultaneously to workers. Once the workers are warmed up, it switches to the workers only.

If you want to detect this in your plugin, check `this.options.isWarmUp` inside your asset.
