### ISSUE TITLE
Tree shaking and detailed report

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#2296]
# 🐛 bug report

With tree shaking enabled, the calculations from detailed report seem to be off.

In this build, there were some unused objects in Map.js, but they got removed in the output by the tree shaking.
```
build/src.31aa00ac.js                                      25.72 KB    6.93s
├── node_modules/preact/dist/preact.mjs                    11.67 KB    1.12s
├── node_modules/preact-router/dist/preact-router.es.js     6.37 KB    1.10s
├── src/components/Map.js                                   5.07 KB    314ms // here
├── src/components/EventDetails.js                          4.64 KB    379ms 
├── src/utils.js                                            2.75 KB    305ms
...
```

Commenting out these object results in Map.js produces this output, making it seems that these individual sizes were generated before treeshaking.
```
build/src.71418498.js                                      25.72 KB    6.81s
├── node_modules/preact/dist/preact.mjs                    11.67 KB    1.28s
├── node_modules/preact-router/dist/preact-router.es.js     6.37 KB    601ms
├── src/components/EventDetails.js                          4.64 KB    261ms
├── src/components/Map.js                                   3.99 KB    153ms // here
├── src/utils.js                                            2.75 KB    177ms
...
```
The total bundle sizes however are the same (as expected).

Seeing the actual sizes would help finding large components.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | master (1.10.3)
| Node             | 11

**Comment by DeMoorJasper** [comment]
As far as I know the main functionality on treeshaking is done on the bundle. Which would make this fairly hard to implement.

**Comment by mischnic** [comment]
Duplicate of https://github.com/parcel-bundler/parcel/issues/4368
