### ISSUE TITLE
parcel dotenv doesn't work properly

### ISSUE THREAD

**Issue by dancespiele** [parcel-bundler/parcel#2299]
# 🐛 bug report

process.env doesn't content the properties set in .env files
## 🎛 Configuration (.babelrc, package.json, cli command)
.env: 
```
API_KEY=0123456
```
package.json:
```json
"scripts": {
    "build": "parcel build index.html",
    "watch": "parcel -p 3000 index.html",
    "test": "jest"
  },
```

## 🤔 Expected Behavior

process.env should have the property API_KEY in this case 

```typescript
console.log(process.env)   //  Object {API_KEY: 0123456}
```

## 😯 Current Behavior

```typescript
console.log(process.env)   //  Object {}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             | v11.1.0
| yarn         | 1.12.3 
| Operating System | manjaro (Archlinux)

**Comment by devongovett** [comment]
Accessing the entire process.env object is not supported for security reasons since it would mean exposing all of the environment variables on your system. If you access a specific variable like `process.env.API_KEY` it should work.

**Comment by Yaojian** [comment]
>> If you access a specific variable like process.env.API_KEY it should work.

Please add this to doc ~~~~ https://parceljs.org/env.html

**Comment by niksseif** [comment]
Hello everyone, I am using parcel with react and I am trying to access my .env file API key and when I console.log the process.env it gives an empty object but once I add process.env.REACT_APP_API_KEY it returns undefined !!! Can someone tell me what is going on?

**Comment by mischnic** [comment]
@niksseif 
`console.log(process.env)` won't work because including all of your env variables has security issues.

This should work:
.env (in the same folder as package.json):
```
REACT_APP_API_KEY="1238uasd"
```
code:
```js
console.log(process.env.REACT_APP_API_KEY);
```

**Comment by Morglod** [comment]
@mischnic what security reasons? There is no cases
It's just super uncomfortable for 'simple bundler'

**Comment by mathieucaroff** [comment]
It'd be great to have a way to specify the set of variables which needs to be present in the bundle. I think a sensible thing to do would be to always include all variables present in the `.env*` files, but I'm not it's the case currently (with parcel `1.12.4`).

I'd like to check out the code if someone can point me the file handling this.

**Comment by mischnic** [comment]
>  I'm not sure it's the case currently

@mathieucaroff It is: https://github.com/parcel-bundler/parcel/blob/v2/packages/core/parcel-bundler/src/utils/env.js
