### ISSUE TITLE
Infrastructure improvements

### ISSUE THREAD

**Issue by aweary** [parcel-bundler/parcel#23]
Hello 👋 

I was looking at contributing to parcel, and noticed a few things that would make it easier for you and others to maintain and contribute to the project. I thought I would just list them in one big issue.

- [x] Enforce a style. I would recommend using [prettier](https://prettier.io/) with pre-commit hooks
- [x] Get Travis CI setup
- [x] Add a `CONTRIBUTING.md` document with a basic overview of how someone can get started contributing to parcel
- [x] Add a `build` script

- [x] Consider typing the code base. This is mostly just personal preference, but I find it easier to contribute/maintain typed code. Flow would be a good option if you were open to it 😃 

cc @devongovett, thanks!

**Comment by yeskunall** [comment]
To add to the list, I think it would be easier to contribute if every module (class, helper, util) came with a small description as to what it does, as do some of them already. Was browsing through the repo and noticed that I had to really dig into the code to see what was going on 😆 but maybe that's just me.

**Comment by albizures** [comment]
hey @aweary, there is already a build command [#L60](https://github.com/parcel-bundler/parcel/blob/master/bin/cli.js#L60)

**Comment by aweary** [comment]
@albizures I mean for building the source.

**Comment by albizures** [comment]
lol, sorry 🤣

**Comment by thejameskyle** [comment]
I'm taking on all these btw

**Comment by aweary** [comment]
@thejameskyle happy to contribute if you want to delegate anything.

**Comment by thejameskyle** [comment]
@aweary Sweet, I've worked through a number of the items already. I'll add Flow to the project and then we can iterate on adding more and more types

**Comment by thejameskyle** [comment]
Moving to #35
