### ISSUE TITLE
Parcel does not support IE

### ISSUE THREAD

**Issue by jxDeveloper** [parcel-bundler/parcel#230]
![2345 20171212153104](https://user-images.githubusercontent.com/28999415/33872409-ba9b3f28-df51-11e7-903e-95f0375e7ad2.jpg)
![2345 20171212153002](https://user-images.githubusercontent.com/28999415/33872535-2de8ceb4-df52-11e7-8112-e23ea00d927d.jpg)

According to the example of the official website, the parcel was reported to be wrong in IE

**Comment by marvinhagemeister** [comment]
According to the screenshot the problem seems to be the arrow function in line 89.

**Comment by tonkotsuboy** [comment]
related

- https://github.com/parcel-bundler/parcel/pull/169
- https://github.com/parcel-bundler/parcel/pull/227

**Comment by davidnagli** [comment]
@jxDeveloper What version of Parcel are you using? This should be fixed in the latest version `v1.2.0`, as the offending code no longer uses a non-es3 compatible arrow function.

**Comment by chee** [comment]
Although that arrow function is gone in `v1.2.0`, @tonkotsuboy's fix removing the template literal has not  made it out yet so Parcel is still Internet Explorer-incompatible.

**Comment by chee** [comment]
for now you can use parcel's `--no-hmr` option to get going without the non-worky code injected

**Comment by davidnagli** [comment]
> (but once that is out, this can be closed. It works in IE with that change)

Actually @tonkotsuboy’s fix was merged 18 hours ago :)

I’m gonna go ahead and close the issue. As always, feel free to comment if you think we need to reopen it!

**Comment by Boscop** [comment]
For me, Parcel is still generating JS code with arrow functions which makes the code not work in IE11.
I had to do an extra babel step before parcel build.
Shouldn't parcel already be using babel to transform arrow function syntax? Then why isn't it doing that for me?

I'm calling it like this:
> parcel build index.html --public-url ./

**Comment by Boscop** [comment]
1. So when I have a `.babelrc` file, parcel will use that one?

2. Is this file ok?
```json
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["Explorer 11"]
      }
    }]
  ]
}
```

**Comment by DeMoorJasper** [comment]
@Boscop browserlist is using this standard: https://github.com/ai/browserslist
So in your case it would be  `IE 11`

**Comment by Boscop** [comment]
Thanks, so parcel will use the value of `"browserslist"` key in package.json and pass it onto babel?

**Comment by DeMoorJasper** [comment]
Yes @Boscop
