### ISSUE TITLE
pragma has been set but pragmafrag has not been set

### ISSUE THREAD

**Issue by lili21** [parcel-bundler/parcel#2305]
# 🐛 bug report

Can't use React Fragments. 

## 🎛 Configuration (.babelrc, package.json, cli command)

Default babel config

## 🤔 Expected Behavior

React Fragments should be supported by default.

## 😯 Current Behavior

Using Fragments will make babel throw error

![image](https://user-images.githubusercontent.com/4456380/48755816-a11aac80-ecd1-11e8-899e-e6ba2539ba3f.png)

## 💁 Possible Solution

https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/transforms/babel/jsx.js#L45

should set the `pragmaFrag` for React.

**Comment by dburles** [comment]
In the meantime adding this to your babel plugins solves it:

```
["@babel/plugin-transform-react-jsx", {
  "pragmaFrag": "React.Fragment"
}]
```
