### ISSUE TITLE
Problem with "/" in directory

### ISSUE THREAD

**Issue by BudST** [parcel-bundler/parcel#2309]
Hi! 

I have question, in default parcel-bundler make in dist folder`<script src="/src.c199d5b8.js"></script> `
And I have problem with conflict directory, It should be `<script src="src.c199d5b8.js"></script>` without `/`

How to set It to automate delete this mark?? With this, It doesn't work on my pc, even on Github Pages

{
  "name": "app",
  "version": "0.0.1",
  "description": "xxx",
  "main": "index.html",
  "scripts": {
    "start": "parcel -p 3000 index.html",
    "build": "parcel build index.html"
  },
  "devDependencies": {
    "autoprefixer": "^7.2.6",
    "babel-cli": "6.26.0",
    "babel-preset-env": "1.6.1",
    "parcel-bundler": "^1.10.3",
    "sass": "^1.15.1"
  },
  "dependencies": {
    "normalize.css": "^7.0.0"
  },
  "author": "",
  "license": "ISC"
}

**Comment by DeMoorJasper** [comment]
use `--public-url ./` at the end of parcel commands to use relative paths (without `/`)
