### ISSUE TITLE
Loading images fail in production mode with React and Electron

### ISSUE THREAD

**Issue by posidron** [parcel-bundler/parcel#2313]
# ❔ Question

How to bundle images with Parcel when using React and Electron?

## 🔦 Context

Searched through closed issues here and there have been a couple of related issues but almost all were related to development builds and the issues were closed and marked as fixed. That was around 2017 in December.

I simply do not manage to load images in a production build; development builds work fine!
Both build variants use React in Electron. The development build uses an Express server.

I do not know if this is a bug or ...

First I thought it's only about SVG files cause am only using one Logo as image in my App but then added as a test a PNG and the issue persist.

Fonts seem to load fine which are embedded in a CSS as `src: url('../fonts/name.woff');`.
The requested URL as shown in the DevTools is: `file:///Users/<name>/<project_name>/dist/mac/MyApp.app/Contents/Resources/app.asar/dist/renderer/production/name.woff`

I extracted the `app.asar` file created by `electron-builder` and the PNG and the SVG images are inside, in the same directory as the fonts and the `index.html`. Parcel also did show me that these were bundled.

```
$ parcel build src/main/main.js -d dist/main --out-file=main --target=electron
dist/main/main.map    17.31 KB     59ms
dist/main/main.js     10.64 KB    2.21

$ parcel build src/renderer/index.html --log-level 3 --no-cache --public-url ./ --out-dir dist/renderer/production --target=electron
[...]
dist/renderer/production/renderer.0eba1f16.map                        55.77 KB      70ms
dist/renderer/production/renderer.9a2f4420.js                          30.1 KB    10.08s
dist/renderer/production/Roboto-MediumItalic-webfont.c09aed53.woff    21.59 KB     2.77s
dist/renderer/production/test.edda39b8.png                             2.65 KB     991ms
dist/renderer/production/renderer.72861b3e.css                           665 B     2.70s
dist/renderer/production/index.html                                      214 B     1.43s
```

## 💻 Code Sample

src/main/main.js
```
  const appUrl = isDevEnvironment()
    ? `${PROTOCOL}://${HOST}:${PORT}`
    : url.format({
        pathname: resolve('dist/renderer/production/index.html'),
        protocol: 'file:',
        slashes: true
      })
```

src/renderer/containers/Dashboard/index.js
Nothing special here, just importing the image add it to the `src` attribute. I do the same for the SVG image.
```
import Test from '../../images/test.png' 
<img src={Test} alt="Test" />
```

package.json
```
"parcel:main": "parcel build src/main/main.js -d dist/main --out-file=main --target=electron",
"parcel:renderer": "parcel build src/renderer/index.html --no-cache --public-url ./ --out-dir dist/renderer/production --target=electron",
```

Error Console:
(Not found)
```
GET file:///test.edda39b8.png 0 ()
```

Tried already:

```
--public-url .      // Current issue, no images but fonts and index.html etc.      
--public-url ./    // Same as above
<img src={'/' + Test} alt="Test" />   // Same as above
--public-url /           // ERR_FILE_NOT_FOUND for renderer.js/css
removed --public-url       // same as above
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             |v11.2.0
| npm/Yarn         |1.12.3
| Operating System | MacOS 10.14.2

**Comment by posidron** [comment]
Gnah.. I was using <BrowserRouter> instead of <HashRouter>.
Will close it, sorry for the noise.

**Comment by briantical** [comment]
@posidron The changed from BrowserRouter to HashRouter fixed my issue though I really don't know why. Static images are now displayed.
