### ISSUE TITLE
Multiple entry output directory is not as expected, or am I doing this wrong?

### ISSUE THREAD

**Issue by wlkns** [parcel-bundler/parcel#2314]
Hi all, I've done some searching and not really come across an answer/explanation on this.

# ❔ Question

Our applications are usually divided by several folders e.g. `app1/` `app2/` `app3/` with a `shared/` folder for shared components across the apps, and the standard `ˀnode_modules/` which contains NPM packages.

I was trying to get each application to export to their own folder to be served by the web server but the assets get built to the root `dist/` folder instead? Am I doing something wrong, or is this simply not supported?

## 🔦 Context

Test directory structure:
```
./app2/index.html
./app2/index.js
./app1/index.html
./app1/index.js
```

Build command:
```
parcel build app1/index.html app2/index.html
```

Actual result:
```
./dist/app2.74110a37.map
./dist/assets.5a181706.js
./dist/app2/index.html
./dist/app2.74110a37.js
./dist/app1/index.html
./dist/assets.5a181706.map
```

Expected/desired result:
```
./dist/app1/index.html
./dist/app1/index.74110a37.map
./dist/app1/index.74110a37.js
./dist/app2/index.html
./dist/app2/index.74110a37.map
./dist/app2/index.74110a37.js
```

(or any variation as long as within each app folder)

## 💻 Code Sample

index.html
```html
<html>
<body>
  <script src="./index.js"></script>
</body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3 |
| Node             | 9.7.1 |
| npm/Yarn         | npm 6.4.1 |
| Operating System | Mac OSX High Sierra 10.13.6 |

**Comment by DeMoorJasper** [comment]
This is how multiple entrypoints work, as multiple entries can still share common js bundles.
