### ISSUE TITLE
Live Reload when changing locals for posthtml-expressions

### ISSUE THREAD

**Issue by optikfluffel** [parcel-bundler/parcel#2317]
# ❔ Question

Is there a way to tell Parcel to reload the page while developing, when one changes the locals that [`posthtml-expressions`](https://github.com/posthtml/posthtml-expressions) uses?

I tried putting parts of these locals into [a js file](https://github.com/optikfluffel/35c3.info/blob/master/src/shortcuts.js) and require them in my [`.posthtmlrc`](https://github.com/optikfluffel/35c3.info/blob/master/.posthtmlrc.js#L1-L4), but that doesn't do anything. Probably because these config files are only read once on startup.

## 🔦 Context

I'd like to be able to preview changes in the data `posthtml-expressions` uses, while running the dev server. Right now I have to restart it every time.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v1.10.3
| Node             | v11.2.0
| npm        | 6.4.1
| macOS | 10.14.1

**Comment by DeMoorJasper** [comment]
Yes config files are read once and cached, they do get invalidated when they change. But it does not listen for dependencies.

**Comment by optikfluffel** [comment]
> they do get invalidated when they change

But that still doesn't make live reloading possible, does it?

**Comment by DeMoorJasper** [comment]
It should reload if a config changes.

**Comment by optikfluffel** [comment]
It doesn't seem to work for me. I've made [a seperate branch](https://github.com/optikfluffel/35c3.info/tree/live-reload) where I've put my locals back in [`.posthtmlrc.js`](https://github.com/optikfluffel/35c3.info/blob/live-reload/.posthtmlrc.js) but when I change them while running parcel the page doesn't change, I have to stop and start parcel again manually.

**Comment by mattwaler** [comment]
This is still an issue as of May 23, 2018. Anybody have any idea how to fix this?

**Comment by mattwaler** [comment]
My current solution is to just use this method:

```html
<ul class="flex">
        <each loop="item in
          [
            { name: 'facebook', link: '/' },
            { name: 'twitter', link: '/' },
            { name: 'pinterest', link: '/' },
            { name: 'envelope', link: '/' },
          ]">
          <li class="w-32 h-32 m-8">
            <a target="_blank" href="{{ item.link }}">
              <include src="{{ `assets/icons/${item.name}.svg` }}"></include>
            </a>
          </li>
        </each>
      </ul>
```

This way, the data is re-referenced every time I make a change.

**Comment by icesurf666** [comment]
But the problem remains
