### ISSUE TITLE
Parcel cannot find dependencies when run on directory outside project

### ISSUE THREAD

**Issue by mrcoles** [parcel-bundler/parcel#2318]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

Setup

```bash
set -e

# put a sass file in a 'static' dir
mkdir -p static
echo 'p { color: red }' > static/foo.scss

# put a project with parcel in another 'parcel' dir
mkdir -p parcel
cd parcel
echo '{ "devDependencies": { "parcel-bundler": "^1.10.3", "sass": "^1.15.1" } }' > package.json
npm install

# run the local parcel build
./node_modules/.bin/parcel watch ../static/foo.scss
```

## 🤔 Expected Behavior

I would expect the file to build properly with parcel knowing where I called it from and to resolve the `sass` dependency from its local directory.

## 😯 Current Behavior

If run from `/tmp/parcel-folders-test/`, it says it’s installing `sass` and afterwards it gives the error:

> /tmp/parcel-folders-test/static/foo.scss: Cannot find module 'sass' from '/tmp/parcel-folders-test/static'

Furthermore, if you run it as an npm script:

```json
{
  "scripts": {
    "start": "parcel watch ../static/foo.scss"
  },
  "devDependencies": {
    "parcel-bundler": "^1.10.3",
    "sass": "^1.15.1"
  }
}
```

After running it, the package.json file updates to just be:

```json
{
  "devDependencies": {
    "sass": "^1.15.1"
  }
}
```

## 💁 Possible Solution

It seems like the parcel CLI is designed to work with a global install or a local install and it seems to resolve local dependencies by looking at the context of the file that is being bundled. It seems like it should also try to resolve dependencies based on the location of the parcel cli file too.

## 🔦 Context

I was experimenting with adding parcel bundling to a django project that was using docker and was seeing if I could have a separate container do the bundling and I wanted it to be able to work on other directories.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3 |
| Node             | v10.11..0 |
| npm/Yarn         | 6.4.1/1.6.0 |
| Operating System | Mac OSX 10.13.6 |

**Comment by DeMoorJasper** [comment]
This is how localRequire is implemented currently, we could change it to use rootDir instead of the asset path for resolving compilers.
That should probably change this (fix this) to the behaviour you expect.

**Comment by mrcoles** [comment]
Yeah, that sounds right. In the meantime, I changed the structure of things in my project to deal with it working this way.

**Comment by jnns** [comment]
Thank you @mrcoles for filing the bug report.  It took me a quiet a while to figure out what was happening.

I'm dropping the following line in here to hopefully help others find the issue quickly in case they have the same error message: 

```stylesheet.css:undefined:undefined: Cannot find module 'cssnano' from 'stylesheet.css' ```

**Comment by bhallstein** [comment]
Hi, thanks @mrcoles for writing such a nice issue that exactly matched what I wanted to find out. I have the same issue where a project imports a module that is one level up from the root directory.

It would be helpful behaviour IMO if the node_modules within root dir, i.e. within the dir where the build is run, be looked in when resolving dependencies for modules that are outside the directory. Understand if there are considerations that might make this harmful in certain circumstances.

**Comment by cupcakearmy** [comment]
I'm having the same issue. Is there a solution?

**Comment by cupcakearmy** [comment]
Maybe for more context. I have to manually copy some files to the tmp dir of the os and build it there. This results in my package.json getting deleted and the build failing.
