### ISSUE TITLE
posthtml-extend or posthtml-include relative path

### ISSUE THREAD

**Issue by iskandarovBakshi** [parcel-bundler/parcel#2320]
# ❔ Question
**how to define root option for posthtml-extend or posthtml-include to have relative paths in html files**
for example:
let's say you have partial in src/partials/images.html that includes image file from src/assets/img/ folder
when i enter src="./assets/img/....jpg" it works as expected, but its not relative to images.html

## 💻 Code Sample
all my assets in src/assets/ folder

src/partials/images.html
```html
<img src="../assets/img/Rounded Rectangle 3 copy.png" alt="">
```
src/index.html
```html
<include src="./partials/images.html"></include>
```
./posthtml.config.js
```javascript
module.exports = {
  plugins: {
    "posthtml-extend": {
      root: "./src"
    },
    "posthtml-include": {
      root: "./src"
    },
    "posthtml-expressions": {
      locals: {}
    }
  }
};
```

example above gives an error:
```
Error: ENOENT: no such file or directory, open '/home/bakshi/Desktop/ev/elanver/assets/img/Rounded Rectangle 3 copy.png'
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:115:12)
    at FSReqWrap.oncomplete (fs.js:141:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             | v10.13.0
| npm/Yarn         | yarn 1.12.3
| Operating System | Ubuntu 18.04.1 LTS

**Comment by iskandarovBakshi** [comment]
i can't use editors autocompletion for files

**Comment by iskandarovBakshi** [comment]
i think the problem is, posthtml extends or includes partials and templates and then tries to resolve image files

**Comment by rabie-khlifi** [comment]
any idea how to make this work
