### ISSUE TITLE
code-splitting: incorrect handling of import modules as not found when encountering temporary error

### ISSUE THREAD

**Issue by prasannavl** [parcel-bundler/parcel#2326]
When a module is imported say with `import("x")` -- If the import fails due to a network failure. Parcel permanently seems to throw the same error that was received (in this case `ERR_INTERNET_DISCONNECTED` and reports module as `MODULE_NOT_FOUND`. This is incorrect. Parcel should always discard module load errors, so any fresh request can succeed.

PS: Webpack handles it correctly as described as well.

**Comment by diem98** [comment]
I'd like to fix this issue,  and in my opinion just delete  [bundles[bundle]=](https://github.com/diem98/parcel/commit/f1c7f588eff6508c30575a84914e53a37426e4ea) can send fresh request, but i don't know if this will cause side effects . could someone help me?

**Comment by DeMoorJasper** [comment]
@diem98 not sure that's a good idea. As `bundles[bundle]` prevents loading bundles more than once, and as far as I know it also contains the bundle, which isn't just `true` as you did.
Perhaps you could catch the error and do `delete bundles[bundle]` in that catch clause

**Comment by diem98** [comment]
Thanks for your detailed explaining, but i wonder if we really need retry load bundle. if do the retry, then should try  how many times or just one time?  I think maybe just throw error as   expected will enough.:)

**Comment by DeMoorJasper** [comment]
@diem98 What about changing the code to this:

```Javascript
if (bundleLoader) {
  return bundles[bundle] = bundleLoader(getBundleURL() + bundle)
    .then(function (resolved) {
      if (resolved) {
        module.bundle.register(id, resolved);
      }
 
      return resolved;
    })
    .catch(function (e) {
      delete bundles[bundle];
      // log or throw the error
      console.error(e);
    });
}
```
*Haven't tested the code yet, so it's just an idea

and leaving the retry behaviour as future work?

**Comment by prasannavl** [comment]
@DeMoorJasper that looks good. However, I think it would be nicer to throw a custom error type, so that it can be caught specifically and handled by user code, for network failure.

**Comment by DeMoorJasper** [comment]
@prasannavl alright sounds good, I've opened up a PR would be great if you could test it out to see if it does what you expect it to do.
