### ISSUE TITLE
parcel watch ignores --no-autoinstall

### ISSUE THREAD

**Issue by etamponi** [parcel-bundler/parcel#2329]
# 🐛 bug report

That's about it, `parcel watch --no-autoinstall index.html` behaves exactly the same as `parcel watch index.html`.

## 🎛 Configuration (.babelrc, package.json, cli command)

Start with these devDependencies:

```js
  "devDependencies": {
    "http-proxy-middleware": "^0.19.0",
    "parcel-bundler": "^1.10.3"
  },
```

Then start `parcel watch --no-autoinstall`, and add a `less` style file (for example). You will see that parcel installs `less`.

## 🤔 Expected Behavior

The expected behavior is that parcel watch doesn't ignore `--no-autoinstall`.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             | 11.2.0
| npm/Yarn         |
| Operating System | Linux

**Comment by mischnic** [comment]
I think the no-autoinstall flag only applies to autoinstalls caused by importing a missing dependency.

**Comment by etamponi** [comment]
I am not sure what you mean by that... that's exactly what I am observing.

**Comment by mischnic** [comment]
Bundling this code without having `mkdirp` specified as a dependency will autoinstall mkdirp. This can be turned off via `--no-autoinstall`.
```js
import mkdirp from "mkdirp";
```

---
In your case, less is required for compiling a less file. So parcel will install less locally, here you cannot disable autoinstalling.

**Comment by etamponi** [comment]
Ok thanks :)

Is it possible to extend --no-autoinstall to this case too? Or is there a
different flag?

Il giorno gio 29 nov 2018, 13:42 Niklas Mischkulnig <
notifications@github.com> ha scritto:
