### ISSUE TITLE
How to improve compilation performance when compiling a file with 10,000 lines

### ISSUE THREAD

**Issue by LaiHuanMin** [parcel-bundler/parcel#2330]
# ❔ Question

Hello, thanks to parcel team for developing such a nice tool, it's much faster than other compilation tools and saves precious development time.

I've been having some problems with parcel compilation recently. There's an old JavaScript file that contains various annotations, JSX, parameter deconstruction, and the latest syntactic sugar (almost every syntax you can think of is in it, this is the react project), and it's already 10k lines long.

After importing this file, the Parcel tool compiles at a slower rate, from a few seconds ago to 20 or 30 seconds now. Every time I change this file to more than 10,000 lines, I have to wait for parcel to compile, even though I've only changed one variable name.

So I'm wondering how to improve the compilation speed of parcel. When I'm editing a file over 10k, can I compile it locally?
 
For example, if I change the expression for a particular line, parcel can be detected from line 0 to line 199, and find that the contents of line 199 are not consistent with the previous compiled version, and compile the rest of the parcel from here (if the user detects that the rest of the code is roughly the same, then the previous compiled result can be used directly).    

I just did this method may not be suitable for all file compilation, only for large files (such as 10k-100k files), what do you think? Thanks for reading!    

Big file make build time longer, I hope it can be build quickly.

## 💻 Code Sample

sorry, have no code

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel      1.10.3     |
| Node       8.4.0      |
| npm/Yarn     5.3.0    |
| Operating System Ubuntu 16.04 |

**Comment by DeMoorJasper** [comment]
This sounds like compiler lvl caching.
Parcel caches per file and starting with parcel 2 on asset lvl (for faster vue and html processing).
Not sure if caching certain parts of a file is a good idea as it might cause side-effects.

The only I can see this get faster is by splitting this file up into multiple files as parcel can than cache the individual files.
Not sure what the reason is for the 10k line file, it might be impossible to split it up. But if it's possible it would speedup builds and probably make it more readable.

**Comment by LaiHuanMin** [comment]
@DeMoorJasper 
This file is really a pain in the neck because it has so many things added that the number of 10k lines is growing. I also think that if you do partial compilation separately, there may be unknown reasons for compilation errors. I'll try to split this large file out. Anyway, thanks for your answer!
