### ISSUE TITLE
How to build JS-bundles with predictable names (e.g. bundle-0.1.js

### ISSUE THREAD

**Issue by iamgoodbytes** [parcel-bundler/parcel#2339]
## ❔ Question
How can I use parcel to create versioned builds of a JS component, like bundle-0.1.js?
## 🔦 Context
I'm creating a JS-component that users can include in their web pages. For that I will need predictable file names that I can version more easily like bundle-0.1.js, bundle-0.2.js, bundle-latest.js.

I could produce a manual bash script that triggers parcel and just copies the file, but for that I would also need a predictable file name to copy, instead of the more random `app.a5a2f689.js`style.

My entry point currently is a .html file that loads JS and SASS and bundles them. 
Does anyone have an idea on how to accomplish this build with more predictable versioning in the naming?

## 👊Thanks a lot for helping out!

**Comment by DeMoorJasper** [comment]
That's currently not possible, you could however write some kind of release script that renames the bundles after parcel runs.

This can be done by using the Parcel API which returns a bundle object containing the entire bundle tree with the names.

See https://parceljs.org/api.html for more info

**Comment by iamgoodbytes** [comment]
Thanks @DeMoorJasper 

I've currently solved it by creating a bash script that creates the custom release folders and bundles for me.

**Comment by eduardoportilho** [comment]
I've bumped into this issue more than once, so I thought it was worthy sharing another solution. If you are using NPM or Yarn, you can use the augmented environment variables to add the package version to the output file:

```json
"scripts": {
    "build": "parcel build src/entry.js --out-file bundle-${npm_package_version}.js"
}
```
