### ISSUE TITLE
Manual recompile

### ISSUE THREAD

**Issue by Industrial** [parcel-bundler/parcel#2342]
I would like to have a manual restart "button" like nodemon supports. If you send it a `SIGUSR 20` process it will restart the child process.

I have a Docker Compose container starting parcel with:
```
npx parcel serve \
  --port $WEB_PORT \
  --hmr-port $WEB_HMR_PORT \
  --log-level 3 \
  src/app/index.html
```

I also have a `Docker Compose Volume` putting stuff into `src/`. It also puts stuff into `common/`. Parcel will rebuild on changes to files in `src/` but not in `common/` so I need a way to poke it and rebuild after saving files into `common/`. Right now I have to restart the complete container every time I change common code which is a lot of time wasted.

**Comment by macklinu** [comment]
@Industrial just to confirm, you're looking to support something similar to [nodemon's `--signal` CLI option](https://github.com/remy/nodemon#gracefully-reloading-down-your-script)?

**Comment by Industrial** [comment]
@macklinu Hi. If you send nodemon process a SIGUSR2 it will restart it's child process.

Since Parcel controls the compiling, it would be nice to be able to give it a signal manually through CLI to recompile

**Comment by Industrial** [comment]
I have solved this by implementing this:

```
require('dotenv').config()

const { resolve } = require('path')

const Bundler = require('parcel-bundler')
const express = require('express')

const { WEB_HOST, WEB_PORT, WEB_HMR_PORT } = process.env

const app = express()

const file = resolve('src/index.html')
const options = {
  logLevel: 3,
  hmrPort: WEB_HMR_PORT,
}

const bundler = new Bundler(file, options)

app.get('/rebundle', async (req, res) => {
  console.log('Rebundle start')
  await bundler.bundle()
  console.log('Rebundle complete')
  res.end()
})

app.use(bundler.middleware())

app.listen(WEB_PORT, WEB_HOST, () => {
  console.log(`HTTP Server Listening on http://${WEB_HOST}:${WEB_PORT}`)
})
```

Instead of using NPM, I am using file watchers to copy common code around into `services/*/src/common`. Which get synced into the running docker containers by docker compose volumes. These each have their own watchers (nodemon or parcel) and restart/rebuild when needed.

The code above allows me to call `/rebuild` after the common files have been written to disk, so HMR can kick in whenever I make a common code change.

**Comment by Industrial** [comment]
Unfortunately I have to reopen this ticket.

With the code above, when `/rebundle` is requested and `bundler.bundle()` is called, the `bundler.middleware()` doesn't seem to update the served bundle.

**Comment by kirillrogovoy** [comment]
@Industrial Did you actually mean this?

https://github.com/remy/nodemon#manual-restarting
Typing `rs` would restart the child process.

The SIGUSR2 thing is different: Nodemon sends SIGUSR2 to the child process once it detected a file update, so that the child process shuts down gracefully.

**Comment by mischnic** [comment]
@Industrial How do the files in `common` affect Parcel's devserver? If you use them, then they should already be watched.
