### ISSUE TITLE
parcel plugins not found when using monorepo (lerna)

### ISSUE THREAD

**Issue by ksachdeva** [parcel-bundler/parcel#2343]
# 🐛 bug report

I have a mono-repo that consists of library/shared projects and many independent web apps. Almost all these web apps rely on a parcel plugin. 

As long as I have that parcel plugin specified in devDependency of each web apps it is being loaded/used however if I have it declared only in the root package.json (lerna monorepo) it does not seem to get loaded.

I was expecting that there will be a traversal to the parent package.json to find the dependencies. 

May be it is intentional and known behavior however it takes away the benefits of monorepo where all my dev dependencies should be at the root.  Also since I have many web apps in this monorepo and parcel-bundler itself depends on babel and many other packages the cost (of packages in node_modules) is not ignorable.

## 🤔 Expected Behavior

I would expect that to find the 'parcel-plugin-*' you would try to consider the package.json in the parent directories as well.

## 😯 Current Behavior

The 'parcel-plugin-*' packaages stored in the root of a lerna monorepo are not taken into consideration.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.10.3
| Node             | 8.11.2
| npm/Yarn         | 6.4.1
| Operating System | OSX

**Comment by DeMoorJasper** [comment]
As far as I know, each package should have all the required packages in their package.json? Not sure if this is a feature we should support

**Comment by JosephScript** [comment]
Hi I came across this when trying to solve the same problem with v2. Is this something that's planned? If you want an example repo I can create one and share it.

**Comment by mischnic** [comment]
With Parcel 2, you have to "manually" specify plugins in a config file and Parcel 1 plugins are not compatible.

Otherwise: please open a new issue if something isn't working for you/not as expected.

**Comment by JosephScript** [comment]
OK thanks.
