### ISSUE TITLE
How do I exclude source map loading of a specific module?

### ISSUE THREAD

**Issue by mrcoles** [parcel-bundler/parcel#2346]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

Using `parcel@1.10.1`, run the following bash commands:

```bash
mkdir source-map-example
cd source-map-example/
yarn init -y
yarn add aws-amplify@1.1.10
echo "import { Auth } from 'aws-amplify';" > index.js
parcel start index.js
```

You get a string of warnings like:

> ⚠️  Could not load source file "../src/index.ts" in source map of "node_modules/aws-amplify/lib/index.js".

## 🤔 Expected Behavior

This is expected because that repo includes the source maps, but not the actual source. Is there, however, a way for me to turn off source-map-loading for that module?

## 😯 Current Behavior

I don’t see an option to set excludes on source map loading.

## 💁 Possible Solution

It appears in webpack, people use the `source-map-loader` plugin and with that, they can specify something like this:

```
exclude: '/node_modules/aws-amplify'
```

## 🔦 Context

It just leads to a really noisy console and makes me fearful that I’ll miss actual important warnings or errors.

## 💻 Code Sample

Setup in configuration.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.1 |
| Node             | v10.11.0 |
| Yarn         | 1.6.0 |
| Operating System | Mac OSX 10.13.6 |

**Comment by mischnic** [comment]
You could use `parcel --log-level 1`.
As previously noted, this needs to be fixed by the published package (`aws-amplify` in this case).

**Comment by apearson** [comment]
Could you link to the "previously noted"?

Sorry to open a closed issue.

**Comment by kwelch** [comment]
It is in reference to the OP `Possible Solution` section.

**Comment by Maker-Mark** [comment]
Reopening this, I don't see a way to exclude just one node_module package. Is there another solution that is not migrating to parcel 2?
