### ISSUE TITLE
When bundling node_modules, auto install devDependencies as regular dependencies

### ISSUE THREAD

**Issue by AlexanderOtavka** [parcel-bundler/parcel#2352]
# 💬 RFC

Currently, if parcel sees an asset type that requires extra compilation (eg. a `.ts` file), it will automatically install the relevant tool (eg. `typescript`) as a _devDependency_ in the `package.json`.  I love this feature of parcel and find it very handy.  I think it could be improved.

I propose that when the `bundleNodeModules` option is true, we auto-install bundler dependencies as regular _dependencies_ instead of _devDependencies_.  We should also recommend in the documentation that people who are targeting the browser or explicitly bundling `node_modules` install parcel as a regular _dependency_ instead of a _devDependency_ or a global.

## 🔦 Context

Normally, a _dependency_ is something you need to run the code, and _devDependency_ is something you only need in development.  In this case, parcel installing development tools like `typescript` as _devDependencies_ makes sense.  However, when using parcel to bundle `node_modules` as well as application code, the distinction between _dependency_ and _devDependency_, gets muddied.  When `node_modules` is bundled, the output bundle has **no dependecies** at all—they are all included in the bundle.  From this point of view, a _dependency_ is just something we need to create our bundle, and `typescript` is one such _dependency_.

Tools for linting and testing (eg. `eslint` and `jest`) would still be considered _devDependencies_, and it would be up to developers to install them as such.  If we divide dependencies this way, deploys will take less time and install less junk.

This argument and the benefits organizing dependencies this way are fleshed out in [Matija Marohnić's blog post on the subject](https://silvenon.com/blog/dependencies-or-devdependencies).

## 💻 Examples

Suppose the user runs `parcel serve index.html` where `index.html` has the following script include:
```html
<script src="index.tsx"></script>
```

If parcel detects that `typescript` is not installed and that `bundleNodeModules` is true (as is the default when targeting the browser), then it will install typescript under _dependencies_ in the `package.json`:
```json
  "dependencies": {
    "parcel-bundler": "<version>",
    "typescript": "<latest version>"
  }
```

The user can add testing, linting, and other tooling as _devDependencies_:
```json
  "devDependencies": {
    "@storybook/react": "<version>",
    "jest": "<version>",
    "lighthouse": "<version>",
    "ts-jest": "<version>",
    "tslint": "<version>"
  }
```

Now, to deploy, they can safely clone this repo and `npm install --production && parcel build index.html`.  The code will be bundled for release and `jest`, `tslint`, and company can be skipped altogether.

**Comment by DeMoorJasper** [comment]
You can install dependencies yourself and move them around to make it safe for this rather edge case imo.

**Comment by AlexanderOtavka** [comment]
@DeMoorJasper The specific use case may be an edge case, but I see no down side to implementing this behavior, even if the benefit is relatively small.  I would (of course) make the changes myself and submit a PR.  I just want to know if the PR would be merged.

**Comment by DeMoorJasper** [comment]
If CI properly caches the yarn install this should be pretty useless imo and the logic the current implementation follows is `dependencies = used in the code` and `devDeps = used for development`. This is also what the names stand for.
