### ISSUE TITLE
How can I disable posthtml?

### ISSUE THREAD

**Issue by jjcm** [parcel-bundler/parcel#2354]
# ❔ Post HTML is modifying the attributes of various html elements I'm creating, which normally would be fine since it's valid code, but it's inside of documentation I'm writing which kinda ruins the presentation. 

I.e. 
`<input type="checkbox" checked> `
becomes
`<input type="checkbox" checked=""> `

Can I disable posthtml in a rc file?

**Comment by mischnic** [comment]
PostHTML will always run if you have a `.posthtmlrc` file or have minification enabled.

https://github.com/parcel-bundler/parcel/blob/21d6cde20d1972105083ace8adf85c86ed63165e/packages/core/parcel-bundler/src/transforms/posthtml.js#L28-L36

**Comment by jjcm** [comment]
I have none of those in my project @mischnic 
![image](https://user-images.githubusercontent.com/50971/49481181-c84ead80-f87d-11e8-9a3f-6d25e01f65d5.png)
Any idea how I can stop the html from being modified?

**Comment by DeMoorJasper** [comment]
posthtml is being used to collect dependencies therefore it's impossible to disable. It should however not change the code in such a way, might be a posthtml bug?

**Comment by thedamon** [comment]
adding `--no-minify` should fix it in a pinch, but that's certainly not a great solution

**Comment by edm00se** [comment]
This looks to be tracked with posthtml/posthtml#280.
