### ISSUE TITLE
Parcel can skip compile some syntax to improve compile time

### ISSUE THREAD

**Issue by LaiHuanMin** [parcel-bundler/parcel#2355]
# 🙋 feature request
Parcel can skip compile some syntax to improve compile time

## 🤔 Expected Behavior
Because some modern browser has support es6 syntax, such as chrome. they can support like class, generator function, let. I guess the parcel can compile faster if parcel ignore some statement which just only using the es6 syntax, just let it skip and finally let chrome browser to execute.     
And parcel just only build syntax what for now the the browser not support (such as decorator, JSX) and so on.     
I guess it's will be make parcel compile time faster than before, and also will became the fastest compile tool in the same tools.      
Totally, I expected behavior is :    
when user dev, skip modern syntax.    
when user build, compile all syntax according to .babelrc file 

## 😯 Current Behavior

current not support, it's still need spent a lots of time on build syntax which already usable in browser.

## 💁 Possible Solution

I used to try: not set preset such as env,es2017 in .babelrc, and hope parcel can be skip and let it go, but seems like parcel tell me there's a es6 syntax not build, even though that syntax already usable in chrome.   
So i think is there possible to archive by configure .babelrc?   

## 🔦 Context

build time faster, make parcel the fastest tool,

Sorry, may have no more info.

## 💻 Examples

maybe can archive by configure .babelrc

**Comment by mischnic** [comment]
This *should* be possible using the `env` key in your babelrc (you might need to set the `BABEL_ENV ` env variable yourself):
```json
{
  "env": {
    "production": {
      "presets": ["@babel/preset-env"]
    },
	"development": {
      "presets": []
    }
  }
}
```

**Comment by LaiHuanMin** [comment]
@micopc Thanks reply. I try again, it's runnable

**Comment by devongovett** [comment]
You can just set the `"browserslist"` key in your package.json as well to target e.g. `"last 1 Chrome version"` or something that supports modern syntax. Parcel will pick this up and disable compilation automatically.
