### ISSUE TITLE
Could not load source file in source map of

### ISSUE THREAD

**Issue by janat08** [parcel-bundler/parcel#2356]
# 🐛 bug report
``
‼  Could not load source file "../src/objectCache.ts" in source map of "../../node_modules/apollo-cache-inmemory/lib/objectCache.js".
``
After upgrading from 1.06 to 1.10.
## 🎛 Configuration (.babelrc, package.json, cli command)
https://github.com/janat08/makpal/commit/9d59965e22f2f2fd11ed1fe732affb782e2c3020

## 🤔 Expected Behavior

For sourcemaps to load

## 😯 Current Behavior

Sourcemaps don't load. Error/repo above

## 💁 Possible Solution

I've read that this occurs as result of poor package bundling, but this happens after upgrade, unless the warning where introduced therein.

## 🔦 Context

I imagine I can't debug those packages, or get their ts types.

## 💻 Code Sample

https://github.com/janat08/makpal/commit/9d59965e22f2f2fd11ed1fe732affb782e2c3020

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10
| Node             | 8
| npm/Yarn         | yarn 1.12
| Operating System | windows 10

**Comment by DeMoorJasper** [comment]
It's not a bug, it's just a warning saying the sourcemaps are refering to files that aren't there.

Which is more an issue with how the package you're using is being publish imo, as sourcemaps are useless if the code behind it isn't available.
