### ISSUE TITLE
Can't import absolute URLs, e.g. from CDN

### ISSUE THREAD

**Issue by dandv** [parcel-bundler/parcel#2358]
# 🐛 bug report

`import('https://...cdn_path.../module.min.js')` fails with:

> Only absolute URLs are supported
> Failed to install https

The code works just fine without Parcel when I open `index.html` in Chrome.

What am I doing wrong? Failing to load CDN libraries seems like a blatant omission.

## 🎛 Configuration (.babelrc, package.json, cli command)

Zero config.

## 🤔 Expected Behavior

Server launches.

## 😯 Current Behavior

```
$ npx parcel index.html
Server running at http://localhost:1234 
npm ERR! Only absolute URLs are supported

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dandv/.npm/_logs/2018-12-04T20_24_06_209Z-debug.log
🚨  /home/dandv/prg/importcdn/index.js:1:7: Failed to install https:.
> 1 | import('https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.min.js').then(lodash => {
    |       ^
  2 |   console.log(_.VERSION);
  3 | });
  4 | 
```

## 🔦 Context

I'm trying to load from CDN a bunch of libraries I don't want to host myself.

## 💻 Code Sample

**index.html**:
```html
<html>
<body>
<script src="index.js"></script>
</body>
</html>
```
**index.js**:
```js
import('https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.min.js').then(lodash => {
  console.log(_.VERSION);
});
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             | 11.3.0
| npm/Yarn         | 6.4.1
| Operating System | Ubuntu Linux 16.04

**Comment by DeMoorJasper** [comment]
Appears that parcel is trying to resolve that url to a local file, which is kinda strange. Checking for url and skipping it if it's a url would probably solve this issue.

**Comment by dandv** [comment]
Thanks for the fix for JS!

I still see the issue with importing CSS:

```js
await import('https://use.fontawesome.com/releases/v5.5.0/css/all.css');
```

**Comment by f3l1x** [comment]
Hi guys. I run into the same error. I hope it will be solved in Parcel 2.

Trying to import module from CDN.

```
import Vue from "https://cdn.pika.dev/vue";
```

**Comment by MaffooBristol** [comment]
@f3l1x you have to use the `import()` syntax not `import from`. It's kinda weird. I think the first one is Parcel-specific because eslint shouts at me when I do it...

**Comment by cekvenich2** [comment]
Is there an example of the import() syntax for v2?

**Comment by phi1ipp** [comment]
Seeing the same issue for the following simple example
```
<script type="module">
    const {h, Component, render} = import( 'https://unpkg.com/preact?module');
    const {htm} = import( 'https://unpkg.com/htm?module');

    // Initialize htm with Preact
    const html = htm.bind(h);

    function App(props) {
        return html`<h1>Hello ${props.name}!</h1>`;
    }

    render(html`<${App} name="World" />`, document.body);
</script>
```

> @parcel/core: Failed to resolve 'https://unpkg.com/preact?module' from './src/preact.html'

>  /Users/mrx/projects/botan/src/preact.html:11:44
>    10 | <script type="module">
>  > 11 |     const {h, Component, render} = import( 'https://unpkg.com/preact?module');
>  >    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    12 |     const {htm} = import( 'https://unpkg.com/htm?module');
>    13 | 
>
> @parcel/resolver-default: Unknown url scheme or pipeline 'https:'

**Comment by ChristophP** [comment]
I found this https://github.com/parcel-bundler/parcel/issues/7064#issuecomment-942441649
