### ISSUE TITLE
Completely disable HMR and reloading from inside a js entry file

### ISSUE THREAD

**Issue by hirasso** [parcel-bundler/parcel#2359]
# 🙋 feature request

I'd like to have a way to block/disable parcel reloading on entry-file-level. 

## 🤔 Expected Behavior

Inside the entry file I'd like to be able to do something like this (pseudocode):

```javascript
if( module.bundler ) {
  bundler.disableReloading();
}
```

## 😯 Current Behavior

The bundler instance doesn't seem to be accessible from inside an entry file at the moment.

## 💁 Possible Solution

That's where you come in 😉
Maybe there already is a solution for this?

## 🔦 Context

In my project (WordPress) I use parcel with multiple js entry files. One for the frontend and one for the admin side. While I like to have HMR and reloading on the frontend, on the admin this often causes problems. So I'd like to disable reloading for the admin entry file.

**Comment by DeMoorJasper** [comment]
You can access HMR from inside js files, see https://parceljs.org/hmr.html

**Comment by hirasso** [comment]
Thanks @DeMoorJasper ! Ah sorry, actually I slightly misdescribed my request. I use [parcel-plugin-watch-reload](https://github.com/hirasso/parcel-plugin-watch-reload) to watch the `*.php` files in my project and send a reload request to parcel when they change. This is what the plugin does on file change:

```javascript
this.bundler.hmr.broadcast({
  type: 'reload'
});
```
Is there also a way to intercept/disable the `hmr.broadcast()` from inside an entry file? Hope this time I described my problem better.

**Comment by DeMoorJasper** [comment]
That's not possible afaik, this is a line of code inside the plugin and never goes through any hmr functions.
It goes straight through the websocket. Perhaps you can do a Pr to the plugin to configure this or something
