### ISSUE TITLE
🐛 relative public path option

### ISSUE THREAD

**Issue by ccorcos** [parcel-bundler/parcel#236]
### 🤔 Expected Behavior
I want to deploy to project to Github Pages. Thus, its convenient to get assets based on a relative public path.

### 😯 Current Behavior
Default behavior is to reference assets from `/dist/file.ext`. We can use `--public-path "/"` to serve assets from `/file.ext`. But `--public-path ""` doesn't work and I want to serve assets from the relative path `file.ext`.

- Using Parsel v1.2.0

**Comment by albinotonnina** [comment]
Hello @ccorcos,
you mean --public-url ?

**Comment by ccorcos** [comment]
Yes. Actually, I just discovered `--public-url '.'` works :)

**Comment by aboutqx** [comment]
Not working now,`'.` will get `%27.%27`,and `.` or `./` get ignored.

**Comment by tobiaskraus** [comment]
Seems not to work anymore.

* `--public-url '.'` leads to `%27.%27/dist/file.ext`
* `--public-url "."` and `--public-url ""`  leads again to `/dist/file.ext` (default)

I really need a realtive path, otherwise I have to switch the bundler...
