### ISSUE TITLE
npm install parcel or parcel bundler?

### ISSUE THREAD

**Issue by dgwyer** [parcel-bundler/parcel#2360]
There seems to be two modules available on npm:

parcel
parcel-bundler

I'm confused as to which one should be used. Is there any difference, and why do both exist if they are the same?

**Comment by DeMoorJasper** [comment]
They are identical only difference is that plugins usually rely on `parcel-bundler`, so it's better to use that one.

**Comment by aaronbeall** [comment]
I'm still confused why there are two identical modules. You're saying that if you install `parcel` that bad things can happen with some plugins?

**Comment by FDiskas** [comment]
Question should be still open :de:

**Comment by BBlackwo** [comment]
Would be much less confusing to just have one

**Comment by AshotN** [comment]
This really doesn't make sense. The documentation isn't even consistent. Github page says `parcel` the website says `parcel-bundler`

**Comment by mischnic** [comment]
The github page is for Parcel 2, which is only available as `parcel`. The website are the docs for version 1

**Comment by AshotN** [comment]
Can there be a banner that explains that the website is for V. 1

I spent a lot of time without figuring that out, it might help some other people.

I can open a separate issue if you like as it seems this one is resolved.

**Comment by mischnic** [comment]
@AshotN : https://github.com/parcel-bundler/website/pull/559

**Comment by melissaveraherbst** [comment]
Perhaps this may help for anyone who is still confused about parcel vs. parcel-bundler

"parcel" is version 2(new) of parcel and parcel is the module that must be used.
According to the npm site, "parcel-bundler", which is version 1, is deprecated and should no longer be used.  

[](https://www.npmjs.com/package/parcel-bundler)
_"This package has been deprecated
Author message:

Parcel v1 is no longer maintained. Please migrate to v2, which is published under the 'parcel' package. See https://v2.parceljs.org/getting-started/migration for details."_

**Comment by Ali-Dakoumi** [comment]
Since that the docs says you should use npm i parcel, i tried it but faced a lot of problems (gyp errors kind of couldnt find file or python...)

but parcel-bundler worked for me!

**Comment by Zedt** [comment]
I had similar problems.
Following on from clarification from **clumsy-cranberry-1** above 
You could do the following:
1- check the versions available:
npm view parcel versions
2- use the latest **non-nightly** version
eg.
npm i parcel@2.0.0-beta.2
