### ISSUE TITLE
Modify content of index.html dynamically (templating)

### ISSUE THREAD

**Issue by rodryquintero** [parcel-bundler/parcel#2362]
# 🙋 feature request
To be able to modify `index.html` with variables or a template language. See Webpack's HTML plugin.
https://github.com/jantimon/html-webpack-plugin

## 🤔 Expected Behavior
For example, I can include the version number of the application on the `<title>` tag of the file by using a feature like this.

## 😯 Current Behavior
I do not see a way you can modify content of the `index.html` file dynamically.

## 💁 Possible Solution
Something like the Webpack HTML plugin would work.
https://github.com/jantimon/html-webpack-plugin

## 🔦 Context
Information like dates, timestamps, versions can be included in the `index.html` file. You can pull some information directly from the `package.json` file, in some use cases.

## 💻 Examples
Inserting the version number on the `<title>` could be done like this.

```
<html>
<head>
<title>`${VERSION}`</title>
<body>
<h2>Header</h2>
<p>Text ... ... .. .. ..</p>
</body>
</head>
</html>

**Comment by mischnic** [comment]
Parcel supports pug out of the box, this *might* work:
```pug
// index.pug
p #{name}'s Pug source code!
```

```js
// .pugrc.js
module.export = {
	locals: {
		name: "something" /* or `require("./package.json").version` */
	}
}
```

**Comment by rodryquintero** [comment]
Thanks @mischnic. I have created the `.pug` file and its `.pugrc.js file`. However, it appears that it is not been considered by the pub compiler since i cannot see the variable values

Am I missing something?

**Comment by DeMoorJasper** [comment]
You could probably also use a posthtml plugin for this, this one seems to do something similar as what is requested here: https://github.com/posthtml/posthtml-expressions

**Comment by rodryquintero** [comment]
Thanks @DeMoorJasper and @mischnic. Will look into your recommendations. I consider this issue closed.

**Comment by mateatslc** [comment]
for the latecomers: check out https://github.com/krotovic/parcel-plugin-interpolate-html too

**Comment by wclr** [comment]
What would be the best way to make `parcel` consume JS/TS source (which exports rendered HTML text) as an entry template?
