### ISSUE TITLE
Replacing path in CSS files

### ISSUE THREAD

**Issue by jpmonette** [parcel-bundler/parcel#2365]
# ❔ Question

I would like to use a `.css` file part of a npm module, but the path used to collect images in the `.css` file are absolute path.

## 🔦 Context

Currently importing an external CSS file using this import string inside my `src/index.tsx` file:

```ts
import "@salesforce-ux/design-system/assets/styles/salesforce-lightning-design-system.min.css";
```

Inside that `.css` file, there are references to assets, such as this one:

```css
  background-image: url("/assets/images/popovers/popover-action.png");
```

Image can be found at this path:

`node_modules/@salesforce-ux/design-system/assets/popovers/popover-action.jpg`

However, once I try to build this using parcel, parcel is looking for files inside my `src/assets/images...` and cannot find them. Only option is to replicate all the `asset` folder inside my `src`, which breaks the purpose of having it stored in my `node_modules`.

I would like for Parcel to search in `node_modules/@salesforce-ux/design-system/*`, or replace the path in a specific CSS file (if possible!) or any other alternative that doesn't require to duplicate that folder from my `node_modules` to my `src` folder.

## 💻 Code Sample

Snippets are available above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             | v10.12.0
| Yarn         |1.10.1
| Operating System | macOS

**Comment by DeMoorJasper** [comment]
Unfortunately I don't think it's currently possible to do this.
In my opinion it would however make sense if `/` wouldn't be the same for node_modules as project code and would use the root of a node module if inside a node module.

Gonna flag this as a `feature` hopefully someone finds a workaround for this in the meantime though.

**Comment by mischnic** [comment]
Parcel 2 supports something like the follow now, which should solve this problem:
```css
background-image: url("npm:@salesforce-ux/design-system/assets/popovers/popover-action.jpg")
```
