### ISSUE TITLE
prefer babelrc defined node version target over pkg json engines field when --target node

### ISSUE THREAD

**Issue by jthegedus** [parcel-bundler/parcel#2366]
# 🙋 feature request

When using `--target node` still prefer reading the node target from `.babelrc` if present.

## 🤔 Expected Behavior

if a `.babelrc` file is present and I use `--target node` I would like my explicit babel preset-env node version to be the target.

## 😯 Current Behavior

Currently, if `--target node` is found then the engines field is automatically used regardless of `.babelrc`
[the parceljs code](https://github.com/parcel-bundler/parcel/blob/75310e15f6fa3c8a0ce6593ada1bcca00240ea54/packages/core/parcel-bundler/src/utils/getTargetEngines.js#L31)

## 💁 Possible Solution

when `--target node` prefer `.babelrc` over node `engines` field value.

## 🔦 Context

Firebase uses the `engines` field to specify the runtime for their Cloud Functions. They only support two specific numbers here, no semver ranges. Just
```json
"engines": "6"
"engines": "8"
```

This causes issues when I want to dev in Node 10 with Yarn because the engines field does is not using a range, so I get an `incompat node version` error.

If it is omitted, then Node 6 is targetted, which would be fine, except that Parcel defaults to Node 8.

I asked to add range support to firebase which would solve the issue, but it does not seem like they will be addressing this on their end anytime soon.

If I could tell Parcel to target Node 6 via `.babelrc` then I could leave off the `engines` field and Firebase would target Node 6 and I could dev with Node 10 LTS & Yarn

I'm unsure what implications this could have on existing projects.

**Comment by devongovett** [comment]
Should be the case in Parcel 2
