### ISSUE TITLE
npx parcel build fails when it needs Babel to transpile

### ISSUE THREAD

**Issue by humphd** [parcel-bundler/parcel#2368]
Sometimes I need to generate a bundle quickly, and don't want to do all the setup.  I'm so used to parcel "just working" that I have come to expect it to always be able to figure things out.

However, one case where it fails is when the context of a build requires more internal deps (e.g., transpiler), and it doesn't have access to it, nor seems to be able to get it automatically.  For example:

`npx parcel build some-js-that-requires-babel.js`

I had a case this week where a really new JS feature was being used in a node project, and parcel couldn't parse the code.  If I instead properly install parcel in the package.json, it seems to be able to cope by auto-installing missing deps.

I'm not sure if you can support the `npx` case or not, but it's something to consider.

**Comment by mischnic** [comment]
Why have you opened two duplicate issues?

**Comment by humphd** [comment]
GitHub gave a 500 when I filed this, they were having high error rates earlier today.  Didn't know this made it through.  I'll close in favour of #2369, which is more complete.
