### ISSUE TITLE
npx parcel build fails when it needs babel plugins

### ISSUE THREAD

**Issue by humphd** [parcel-bundler/parcel#2369]
I have become so used to parcel "just working" that sometimes when I need to quickly make a bundle for something I'm not maintaining, I'll use `npx parcel build ...`.  This typically works great.

This week I ran into an issue when I tried to bundle https://github.com/micromatch/picomatch this way.  It uses some really new JS, and parcel failed to parse the `...` syntax.  I assume it needs babel + a plugin to support it, and can't get it automatically:

```
$ npx parcel build index.js
🚨  /private/tmp/picomatch/lib/picomatch.js:58:44: Unexpected token (58:44)
  56 |
  57 |     if (opts.ignore) {
> 58 |       let ignore = picomatch(opts.ignore, { ...opts, ignore: null });
     |                                             ^
  59 |       isIgnored = str => ignore(str, true, true);
  60 |     }
```

When I properly installed parcel into the project's package.json, I was surprised to see that it worked.  I guess it's able to automatically install the deps it needs there?

```
$ npm install --save-dev parcel

> fsevents@1.2.4 install /private/tmp/picomatch/node_modules/fsevents
> node install

[fsevents] Success: "/private/tmp/picomatch/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> deasync@0.1.14 install /private/tmp/picomatch/node_modules/deasync
> node ./build.js

`darwin-x64-node-8` exists; testing
Binary is fine; exiting

> parcel@1.10.3 postinstall /private/tmp/picomatch/node_modules/parcel
> node -e "console.log('\u001b[35m\u001b[1mLove Parcel? You can now donate to our open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/parcel/donate\u001b[0m')"

Love Parcel? You can now donate to our open collective:
 > https://opencollective.com/parcel/donate
+ parcel@1.10.3
added 806 packages from 623 contributors and audited 7634 packages in 47.397s
found 0 vulnerabilities

brightness:picomatch humphd$ node ./node_modules/.bin/parcel build index.js
✨  Built in 1.35s.

dist/index.map    69.96 KB     25ms
dist/index.js     19.84 KB    1.17s
```

Maybe it's not possible to support the `npx` case the same way, but if it is, I'd suggest you consider it.  The fact that parcel works out of the box with no config means that using it as a command line tool vs. project dependency is something more people will expect.

**Comment by humphd** [comment]
Please ignore #2368, which is a dupe of this, filed by mistake when GitHub gave a 500 while filing this.

**Comment by DeMoorJasper** [comment]
This is unfortunately not yet standard and therefore not part of `babel-preset-env`.
There is no way for us to include every possible babel plugin or detect syntax and match a babel plugin with it. It would be pretty cool if that would be possible though.

**Comment by mischnic** [comment]
Does this still happen? Object spread is a stage 4 (finished) proposal now, so it should be supported

**Comment by humphd** [comment]
Yes, still happens.  Just tried again right now.  It's no problem to close this if it's just not possible to support.

**Comment by mischnic** [comment]
The only thing we can fix is the difference between `npx parcel` and running (locally) installed version.
We can't do anything if `babel-preset-react` doesn't support object spread.

For me, running `npx parcel build index.js` in picomatch installs parcel (takes quite a while) and then builds without an error.

**Comment by mischnic** [comment]
Using the newest Babel version will likely fix this (the parser supports this by default)

**Comment by humphd** [comment]
Great, let's close this then.
