### ISSUE TITLE
🐛 parcel build hangs using `parcel-plugin-typescript`

### ISSUE THREAD

**Issue by ccorcos** [parcel-bundler/parcel#237]
### 🤔 Expected Behavior
`parcel build` shouldn't hang.

### 😯 Current Behavior
`parcel build` hangs

### 🔦 Context
This isnt an issue if I uninstall `parcel-plugin-typescript` so its definitely a problem with that plugin. However, I can't find the repo for it so I'm assuming its published by you guys?

Versions:

```
    "parcel-bundler": "^1.2.0",
    "parcel-plugin-typescript": "^0.2.0-astmap.0",
    "typescript": "^2.6.2",
```

**Comment by albinotonnina** [comment]
Repo should be here: https://github.com/awesome-parcel-bundler/parcel-plugin-typescript

**Comment by ccorcos** [comment]
Thanks. ...but it looks like I can't submit an issue in that repo.

**Comment by albinotonnina** [comment]
My bad @ccorcos 
https://github.com/fathyb/parcel-plugin-typescript
👍

**Comment by ccorcos** [comment]
Cool thanks. https://github.com/fathyb/parcel-plugin-typescript/issues/1
