### ISSUE TITLE
Add CDN Url?

### ISSUE THREAD

**Issue by nloui** [parcel-bundler/parcel#2371]
# ❔ Question

Is there a way to set a CDN url during the build process?

## 🔦 Context

Trying to load the parcel created css/js files from a CDN without putting the entire site behind one

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by DeMoorJasper** [comment]
You could use environment variables.
The exact implementation depends on where you require these assets. (html, pug, js, css, ...)

**Comment by dfkaye** [comment]
@DeMoorJasper Could you expand on that answer a bit? 

I'm dealing with a similar custom parcel build challenge. We have `<img src="../src/img/path...">` tags inside of JS (not HTML) - as well as `background url(../src/img/...)` rules in CSS, and need to make all of them point to a production URL, *post build*.

I've seen one question that might be related (https://github.com/parcel-bundler/parcel/issues/2101), suggesting user try it with `dotenv` project.

If you can answer or point to a post elsewhere that explains any of that, we would appreciate the help.

**Comment by mischnic** [comment]
You might be able to do this with a `--public-url`. Maybe do something like `--public-url CDN_OUTPUT` and then replacing every occurrence of that string in the dist folder with your real URL?
