### ISSUE TITLE
Parcel conflict in --public-url

### ISSUE THREAD

**Issue by lhk** [parcel-bundler/parcel#2373]
# 🐛 bug report

I'm using parcel to bundle a webextension. Depending on the --public-url setting, either the sourcemaps aren't accessible, or the scripts in my popup html can't be loaded.

## 🎛 Configuration (.babelrc, package.json, cli command)

This is a follow-up on #2209 . Please look there to get a minimal example on the sourcemap loading bug. It turns out that both chrome and firefox can't access the bundled sourcemaps, unless I run parcel with --public-url=./

This makes parcel drop a leading / before the links to scripts.

But without this slash, they can't be read in a popup html. A minimal example for that problem is here:
https://github.com/lhk/popup_inaccessible

## 🤔 Expected Behavior

The two path syntaxes seem contradictory. Somehow it must be possible to figure out what sets them apart.

## 😯 Current Behavior

It is possible to switch between the two styles. But they are not combined.

## 💻 Code Sample

Output without --public-url=./, readable by chrome:
https://github.com/lhk/popup_inaccessible

Demo where --public-url=./ is necessary is here:
#2209 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.1
| Node             | v8.12.0
| npm/Yarn         | npm 6.4.1
| Operating System | ubuntu 18.04.1 64bit

**Comment by mischnic** [comment]
How do you invoke parcel in your example repo https://github.com/lhk/popup_inaccessible? `popup/index.html` reference a main.js file in `popup/main.js`, but there is no such file.

**Comment by lhk** [comment]
I'm afraid I can't reproduce this. Could bite myself for not keeping the package-lock.
