### ISSUE TITLE
How to change the builded .html file position in the directories?

### ISSUE THREAD

**Issue by ykx456654** [parcel-bundler/parcel#2379]
now, it's like this:
/dist
-/static/*.css
-/static/*.js
-/static/index.html

but i want this:
/dist
--/static/*.css
--/static/*.js
-/index.html

thanks~

**Comment by DeMoorJasper** [comment]
Whats the command you're running and folder structure?

Normally parcel creates a flat file structure.

**Comment by hoemon** [comment]
I would  love to know if there is a way to keep the folder structure as well, flattening things do not work for me. The only reason I'm choosing webpack over parcel atm.

**Comment by devongovett** [comment]
This is not supported. Why do you care about the output filenames of your static assets? They are really just implementation details.

That said, in parcel 2, you will be able to override file naming with plugins.
