### ISSUE TITLE
Import all files in subfolders using common name

### ISSUE THREAD

**Issue by vickylance** [parcel-bundler/parcel#2382]
# ❔ Question

 I want to know how to make all *.js files in a folder/subfolder available as a single module
like lets say I have a folder called components and inside that I have 3 folders atom, molecules and organisms and inside that folder I will have more folders for each of the components
But I want to use any of the component from any of the folder using the following syntax `import {component1 , component2, component3} from 'components'`
where `component1 `can be in atoms folder, `component2 `can be in molecules folder and `component3 `can be in organisms folder

## 🔦 Context

I am trying to replicate the feature implemented in this link which uses webpack into my parcel project
https://github.com/diegohaz/arc/blob/master/src-example/components/index.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.10.3 |
| Node             | 10.13.0 |
| npm/Yarn         | Yarn v1.12.1 |
| Operating System | Windows 10 Pro |

**Comment by DeMoorJasper** [comment]
Try `import ... from “./components/*.js”`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DeMoorJasper** [comment]
Switching around a folder and hoping that it would resolve into the same thing from another place doesn’t sound like a safe practise at all to me. It’s completely possible to have 2 files with the same name but in a different folder.

Not sure what you’re trying to achieve here, parcel supports glob imports like I mentioned.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vickylance** [comment]
@DeMoorJasper Yes you are right 2 different folders can have the same name in Atoms/Molecules/Organisms. But lets assume we don't introduce that human error. I still don't understand how a glob import will solve this issue. 
Each folder under Atoms/Molecules/Organisms will have a Component Folder whose name is the name of the component and it contains a index.js file and component_name.js file inside that folder. The index.js will simply import the component_name.js file and export it.
So I should be able to import any component inside any component across the Atoms/Molecules/Organisms and in future if I change a component from lets say Atom to Molecules. there should be zero code change and all my imports should still work.
