### ISSUE TITLE
async imports with regex

### ISSUE THREAD

**Issue by wpitallo** [parcel-bundler/parcel#2384]
# 🙋 feature request

It would be cool is we could use code splitting for async imports,

For example: const assets = await import('./assets/**/*.(png|json)')

Currently this works: import * as assets from './assets/**/*.(png|json)'

But does not seems to work using async / await

Would be awesome if it was possible :)

**Comment by wpitallo** [comment]
It would be cool is we could use code splitting for async imports,

For example: const assets = await import('./assets/**/*.(png|json)')

Currently this works: import * as assets from './assets/**/*.(png|json)'

But does not seems to work using async / await

Would be awesome if it was possible :)

**Comment by Taym95** [comment]
Hello, I would like to work on this issue, can someone give a piece of advice where I should start?

**Comment by JayaKrishnaNamburu** [comment]
Hi @DeMoorJasper I figured out why this issue is happening and would like to give a PR for this, can you please let me know how to symlink the packages in my local to test this

Should I need to run `npm run link` in the root itself or I need to run it in `pacakges/core/parcel-bundler` for it to reflect to test on other projects

**Comment by JayaKrishnaNamburu** [comment]
@wpitallo here is an example to make it work --> https://github.com/JayaKrishnaNamburu/parcel-dynamic-regex-import

**Comment by DeMoorJasper** [comment]
@JayaKrishnaNamburu seems like it works as expected than. If it doesn't feel free to write a unit test and add it into parcel 1.

However we probably won't support globs the same way in Parcel 2 and Parcel 1 has been feature locked.

**Comment by JayaKrishnaNamburu** [comment]
Actually with additional babel plugin it works as i shared in the repo. So can this issue be closed ?

**Comment by DeMoorJasper** [comment]
I think so
