### ISSUE TITLE
Also transform files inside `document.write` statements

### ISSUE THREAD

**Issue by rseyferth** [parcel-bundler/parcel#2385]
# 🙋 feature request

When using a single `index.html` that should load a different stylesheet, based on the url, there is currently (to my knowledge) no way to use the Parcel pipeline for those stylesheets. For example:

```js
// Determine theme style
var m = /^\/([a-z\-]+)/.exec(window.location.pathname);
var c = m ? m[1] : 'default';
if (!/^theme-a|theme-b$/.test(c)) c = 'default';

switch(c) {
    case 'theme-a':
        document.write('<link rel="stylesheet" href="./sass/theme-a.scss">');
        break;

    default:
    case 'theme-b':
        document.write('<link rel="stylesheet" href="./sass/theme-b.scss">');
        break;

}
```

## 🤔 Expected Behavior

The `theme-X.scss` files would be processed by Parcel, and the uri would be replaced by a `theme-X.abcdefd.css` asset.

## 😯 Current Behavior

It is unprocessed, and the browser tries to load the `.scss` file.

## 💁 Possible Solution

None that I know of. My current workaround is that I compile the Sass separately from Parcel, and copy the static files into the `dist/` folder.

## 🔦 Context / 💻 Examples

See above real world example.

**Comment by DeMoorJasper** [comment]
Write it like this:
```js
// Determine theme style
var m = /^\/([a-z\-]+)/.exec(window.location.pathname);
var c = m ? m[1] : 'default';
if (!/^theme-a|theme-b$/.test(c)) c = 'default';

switch(c) {
    case 'theme-a':
        document.write(`<link rel="stylesheet" href="${require("./sass/theme-a.scss")}">`);
        break;
}
```
