### ISSUE TITLE
Can we serve static asset "as is" with parcel?

### ISSUE THREAD

**Issue by ycmjason** [parcel-bundler/parcel#2387]
# ❔ Question
Can we serve static asset "as is" with parcel? E.g. `parcel index.html --static ./static/`, then the static files inside `./static/` will be served.

## 🔦 Context
 I am trying to access to a JSON file with `fetch` so that I could treat that file as a mock API end point.

I tried to search around and couldn't find anything in parcel that will allow me to do this?

**Comment by ycmjason** [comment]
Sorry if this is a dumb question. I am sure this must be something that has been considered before. I just couldn't find the answer anywhere. 😢

**Comment by DeMoorJasper** [comment]
json will be inlined by parcel everything else should return a url if required

**Comment by ycmjason** [comment]
@DeMoorJasper 

Ah! I see. Thanks!

Is there a way to force json to return a url when required?

**Comment by DeMoorJasper** [comment]
@ycmjason currently not, it will be configurable in parcel 2

**Comment by ycmjason** [comment]
I guess I can close this then! :) Thanks!
