### ISSUE TITLE
Is it possible to get parcel's dev server (parcel serve) to log HTTP requests?

### ISSUE THREAD

**Issue by rosensama** [parcel-bundler/parcel#2390]
# ❔ Question

Is there a log level I can set where parcel's dev server, invoked by `parcel serve` will log the browser requests it is serving?  

## 🔦 Context

When I'm debugging routing bugs in an SPA it's helpful to see the requests the UI made to the dev server or when index.html is served to it again unexpectedly.  

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3 |
| Node             |11.2.0|
| npm/Yarn         | npm 6.4.1| 
| Operating System | OSX mojave|

I use parcel's dev server to deliver the UI and handle HMR.  The UI makes CORS requests to a separate REST API server, so requests to the dev server are usually of interest. 

Thanks,
Rob

**Comment by DeMoorJasper** [comment]
Currently not but I guess this could be added to log-level 4 (verbose)

**Comment by mischnic** [comment]
```
[7:48:28 PM]: Request: http://localhost:1234/style.e308ff8e.css
```
Requests are now logged with `parcel --log-level 4`. Not yet added to the documentation: https://github.com/parcel-bundler/website/issues/323
