### ISSUE TITLE
Parcel 2: Better unit test coverage for Parcel core

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#2393]
While I am generally more a fan of integration testing, we should increase the test coverage of Parcel 2 core, especially the data structures that will be accessed by plugins. This is mostly things in the `@parcel/core` package:

* Graph
* AssetGraph
* BundleGraph
* Asset

**Comment by opiation** [comment]
Is any help needed on this issue?  If so, what criteria would qualify as _better_ code coverage?  (e.g.: ~x% of coverage, all public methods/functions, some other metric). Lastly, is `@parcel/core` stable enough at the moment for this or should this issue wait?

**Comment by devongovett** [comment]
@opiation thanks for your interest in helping out! We have a bunch of integration tests at the moment, but not a lot of unit test coverage for data structures in the core package. I think core is close enough to stable now that it would be fine to start writing some tests. There are a lot of totally uncovered files, so those would be a good place to start if you're interested. :)
