### ISSUE TITLE
Parcel 2: Port resolver tests from Parcel 1

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#2394]
Port the tests from Parcel 1 for the resolver to run against the default resolver plugin in Parcel 2.

**Comment by lindskogen** [comment]
I would be interested in working on this! Where are the v1 tests?

**Comment by mischnic** [comment]
I think he meant these: https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/test/resolver.js

Here are the v2 resolver tests that exist so far: https://github.com/parcel-bundler/parcel/blob/v2/packages/core/integration-tests/test/resolver.js

**Comment by lindskogen** [comment]
So the test should be ported to run against the `bundle` interface instead?

**Comment by devongovett** [comment]
You could keep them as unit tests. Might be easier. I’d put them in the default resolver package.

**Comment by mischnic** [comment]
https://github.com/parcel-bundler/parcel/pull/4995
