### ISSUE TITLE
How to generate dist/ JS without hash in name?

### ISSUE THREAD

**Issue by bubnenkoff** [parcel-bundler/parcel#2403]
I can't understand where hashes in names can be helpful. Like `src.8c94427b.js` and `src.a4298074.css`.
I want to build own build system on shell script that would do some operations on result files. So I would like that they have fixed names without hashes. How I can do it?

**Comment by DeMoorJasper** [comment]
Hashes are usefull for caching on a cdn, if the name remains the same you can't reliable cache it for a long amount of time resulting in a way higher hosting cost

**Comment by luishasmail** [comment]
Is there any reason that globs wouldn’t work? `src.*.js`

**Comment by devongovett** [comment]
The hashes are necessary to ensure that duplicates cannot occur in the flattened directory, and for long term caching.

**Comment by luishasmail** [comment]
I was meaning more for his scripts
