### ISSUE TITLE
Variables in CSS url() function make events.js throw error

### ISSUE THREAD

**Issue by dreerr** [parcel-bundler/parcel#2405]
# 🐛 bug report

When using variables in the url() function the events.js throws the following error:
```Error: ENOENT: no such file or directory, open 'src/styles/$dir/$icon.png' ```

## 🎛 Configuration (.babelrc, package.json, cli command)
**.postcssrc**
```
{
  "plugins": {
    "postcss-advanced-variables": {}
  }
}
```

**index.pcss**
```postcss
$dir: assets/icons;

@each $icon in (foo, bar, baz) {
  .icon-$icon {
    background: url('$dir/$icon.png');
  }
}
```

```js

```

## 🤔 Expected Behavior

PostCSS files should be parsed first and then urls should be checked for the according files.

## 😯 Current Behavior

```
throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'src/styles/$dir/$icon.png'
Emitted 'error' event at:
    at fs.open (internal/fs/streams.js:130:12)
    at FSReqCallback.args [as oncomplete] (fs.js:147:20)
```

## 💁 Possible Solution

It works when setting the url() function to something else, this apparently breaks the CSS

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             |11.4.0
| npm        |6.4.1
| Operating System | OSX 10.13.6

**Comment by DeMoorJasper** [comment]
Not sure why this is happening, it might be the order of plugins, meaning parcels dependency collector should run last, if however vars are not being inlined this is impossible to handle.

**Comment by dreerr** [comment]
But the variables are parsed to local files which exist, so they become
url(assets/icons.foo.png) 
url(assets/icons.bar.png) 
url(assets/icons.baz.png) 
Why is this impossible to handle?

**Comment by mischnic** [comment]
The issue is that CSSAsset.collectDependencies runs before the asset is transformed, so inside `collectDependencies`, the AST still contains `url('$dir/$icon.png')`;

This would fix it, but I don't know if that would cause other issues:
```diff
diff --git a/packages/core/parcel-bundler/src/assets/CSSAsset.js b/packages/core/parcel-bundler/src/assets/CSSAsset.js
index 8c3b7cd..da317e1 100644
--- a/packages/core/parcel-bundler/src/assets/CSSAsset.js
+++ b/packages/core/parcel-bundler/src/assets/CSSAsset.js
@@ -93,7 +93,7 @@ class CSSAsset extends Asset {
     });
   }

-  async transform() {
+  async pretransform() {
     await postcssTransform(this);
   }
```
Reference:
https://github.com/parcel-bundler/parcel/blob/3042224b8caeb5b195fe64db399be24d3b7ad7cc/packages/core/parcel-bundler/src/Asset.js#L203-L209

**Comment by mischnic** [comment]
> This would fix it, but I don't know if that would cause other issues:

This is already done in Parcel 2
