### ISSUE TITLE
Recipe for outputting ES2015 compat code.

### ISSUE THREAD

**Issue by blainekasten** [parcel-bundler/parcel#2406]
# ❔ Question

Does parcel support outputting ES2015 compatible code to ship to modern browsers? If so, is there a recipe for this we could document? If not, is it an interesting feature and what would be missing?

## 🔦 Context

React applications can get really really big given all of the syntax cruft that gets injected when compiling ES2015 to ES5 code.

I'm interested in profiling the TTI changes of an app when shipping ES2015 code to the browser.

**Comment by DeMoorJasper** [comment]
In package.json you can configure the browserslist for using more modern syntax.

See https://parceljs.org/javascript.html#default-babel-transforms
