### ISSUE TITLE
Folder structure & No-flatten

### ISSUE THREAD

**Issue by hoemon** [parcel-bundler/parcel#2409]
# ❔ Question

I like parcel very much compared to the alternatives, however, folder flattening is a game breaker for me. I need to keep my folder structure as is, and have control over my file naming. I was unable to find any settings about this in the documentation. Is this possible?

## 🔦 Context

For instance when this is run
`parcel build src/game.html --public-url ./ -d parcel`
All of my files under all folders under `src` become flattened. All files are in the same folder.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.10.3
| Node             | 10.14.2
| npm/Yarn         | 6.4.1
| Operating System | Windows 10

**Comment by devongovett** [comment]
This is not supported. Why do you care about the output filenames of your static assets? They are really just implementation details.

That said, in parcel 2, you will be able to override file naming with plugins.
