### ISSUE TITLE
Pug's path resolution is confusing

### ISSUE THREAD

**Issue by mkalygin** [parcel-bundler/parcel#2413]
# 🐛 bug report

In Pug files we have two types of path resolutions: the one which is set through Pug's `basedir` configuration and Parcel's module resolution.

The `basedir` issue is covered in #1352. It's not even configurable and always set to the current entry point's directory path. There are cases when this is not a desirable behavior (e.g. when using relative paths inside of a mixin/partial and including it in Pug templates located in different directories).

Parcel's module resolution applies to assets such as images, stylesheets and javascripts. It behaves differently from what Pug's resolution does. E.g. this issue #2022 refers to incorrect relative path resolution.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "scripts": {
    "build": "parcel build src/entries/**/*.pug --public-url ./",
  },
  "devDependencies": {
    "parcel-bundler": "^1.10.3",
    "pug": "^2.0.3"
  }
}
```

## 🤔 Expected Behavior

I'm able to use `~` for the project root where `package.json` is located. Or I'm able to create an alias for `src` directory somehow. The behavior should be consistent for both partials/mixins and for assets. Relative paths also should work correctly and consistently.

## 😯 Current Behavior

I don't know how to do paths relative to the `src` directory in Pug. It just doesn't work. No matter what I do, both partials/mixins and assets are always resolved relative to the current entry point's directory. Prepending `~` or `/` doesn't work either. It's just impossible to use absolute paths with Pug right now.

## 💁 Possible Solution

The suggested solution in #1352 works. `basedir` option needs to be exposed in `.pugrc` for sure. I'm not sure what to do with the assets resolution though.

## 🔦 Context

I want to build all Pug files under the `src/entries` directory recursively and keep the directory structure of HTML files in the output. In all Pug files it would be preferable to set paths to assets and mixins/partials relative to `src` directory. Is it even possible?

If I fix #1352, I'm able to do this with `basedir` set to `./src`. But I still have issues with path resolution of assets, there is no way to set a path relative to the `src` directory for the assets.

## 💻 Code Sample

If necessary I can build up a simple app with this use case. But I hope it's clear enough from the description.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             | 8.11.3
| npm/Yarn         | 1.12.3
| Operating System | Mac OS Mojave 10.14

**Comment by mkalygin** [comment]
I've went through the related code. It looks like there is no way to set `rootDir` at the moment and it's automatically defined [here](https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/utils/getRootDir.js). It means if we have entrypoints in `src/entrypoints`, there is no way to set it to `src`. 😞

**Comment by Edvinas01** [comment]
Why not add `--root-dir` argument which would be used instead of `getRootDir` if specified? There already seems to have been a PR for this https://github.com/parcel-bundler/parcel/pull/1407, but it hasn't added this option :thinking:
