### ISSUE TITLE
Treeshaking commonjs exports

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#2417]
# ❔ Question

How well does/can Parcel support tree shaking commonjs modules?

## 💻 Code Sample

```js
// math.js
module.exports.add = function(a,b){return a+b};
module.exports.sub = function(a,b){return a-b};

// index.js
const {add} = require("./math.js");
console.log(add(2, 3));
```

Produces:
```js
(function() {
	var a = {
		add: function(r, n) {
			return r + n;
		},
		sub: function(r, n) {
			return r - n;
		}
	};
	var b = a.add;
	console.log(b(2, 3));
})();
```

It's even there without the console statement:
```js
(function() {
	var a = {
		add: function(r, n) {
			return r + n;
		},
		sub: function(r, n) {
			return r - n;
		}
	};
	var b = a.add; // why isn't this removed when treeshaking?
})();
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |master
| Node             |11.4.0

**Comment by mischnic** [comment]
If terser was used after packaging, 
```js
(function() {
	var a = {
		add: function(r, n) {
			return r + n;
		},
		sub: function(r, n) {
			return r - n;
		}
	};
	console.log(a.add(2, 3));
})();
```
could be turned into just (without any special options)
```js
console.log(5)
```

**Comment by devongovett** [comment]
Ah, it works with `exports.add = ` instead of `module.exports.add = `. Perhaps that would be a good fix.

**Comment by macklinu** [comment]
I'm curious to help contribute to this issue. Would either of you be able to point in the direction of files or tests where you would go to make this change, so I can start reading more about how this feature already works? Having trouble understanding where to look off after doing some initial searching.

Thanks 🙇

**Comment by mischnic** [comment]
All of the above is already done in Parcel 2.
