### ISSUE TITLE
Glslify

### ISSUE THREAD

**Issue by dy** [parcel-bundler/parcel#2419]
What is the best way to organize glslify processing?
There are webpack loader, browserify transform, require replacer, babel and rollup plugins. Can we use any of them?

**Comment by mischnic** [comment]
If I understand your question correctly:
Parcel already supports glsify (https://parceljs.org/openGL.html), example here: https://github.com/parcel-bundler/parcel/tree/master/packages/core/parcel-bundler/test/integration/glsl.

**Comment by dy** [comment]
Probably worth adding to the docs that importing is done via `glslify`.
Would be nice to enable some glslify transforms as well though, like glslify-import, but that's another request.

**Comment by connerlacy** [comment]
I would like to access the example link from above

https://github.com/parcel-bundler/parcel/tree/master/packages/core/parcel-bundler/test/integration/glsl

as I am having difficulty integrating with glslify with parcel at the moment. Is there a "from scratch" example of an implementation available?

Thanks!

**Comment by mischnic** [comment]
That test was moved to https://github.com/parcel-bundler/parcel/tree/master/packages/core/integration-tests/test/integration/glsl

There's an open issue regarding a better example on the https://parceljs.org/: https://github.com/parcel-bundler/website/issues/386
