### ISSUE TITLE
VS Code, import navigation when using aliases

### ISSUE THREAD

**Issue by coder82** [parcel-bundler/parcel#2420]
# ❔ Question

When I define some aliases inside my package.json
```
  "alias": {
    "assets": "./src/assets",
    "utils": "./src/globals/utils"
  }
```

Then I can do for example:

`impot {someComponent} from 'utils';`

VS code does not navigate to utils when I attempt to ctrl+click into it, while it would if I used a normal, non-aliased path.
Do you know a workaround to make this work?

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             | 10
| npm/Yarn         | 6.x
| Operating System | Win7 x64

**Comment by mischnic** [comment]
According to this comment: https://github.com/Microsoft/vscode/issues/36495#issuecomment-338864671, adding a `jsconfig.json` file into you src folder should work:
```json
{
    "compilerOptions": {
        "target": "ES6",
        "baseUrl": ".",
        "paths": {
            "assets": ["src/assets"],
			"utils": ["src/globals/utils"],
		}
    },
    "include": [
        "src/**/*"
    ]
}
```

**Comment by coder82** [comment]
That worked, but without target "ES6", for some reason that line screws it.

So this is how I do it:

`{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "components/*": ["src/components/*"],
            "assets/*": ["src/assets/*"],
            "utils.js": ["src/globals/utils.js"]
		}
    },
    "include": [
        "src/**/*"
    ]
}`

Reason: I define some aliases because I don't like ../../../......
Components are followed ok, assets are not, for example .svg aren't followed.
Also .scss are not followed, as well as .css.
They are followed from within their own format though, .scss to other .scss or css, but not crossing file extension, so for example from .js to .scss.
For example, my App.js contains:
`import './App.scss';`

When doing ctrl+click, it doesn't follow.
