### ISSUE TITLE
ability to disable resolving using `module` field in package.json

### ISSUE THREAD

**Issue by devsnek** [parcel-bundler/parcel#2423]
if you have a cjs module which is accessed from esm, generally the ecosystem has decided that the default export should be the value of `module.exports` after evaluation.

however in parcel, this is not the case.

example cjs module: `module.exports = { a: 42 }`;
example esm module: `import x from 'cjs'; console.log(x.a)`;

expected output is `42`, but instead an error is thrown about trying to read `a` off undefined `x.default`, as the default isn't attached.

so my question: is there a way i can enable this behaviour, or if it doesn't exist can it be added?

edit: https://github.com/parcel-bundler/parcel/issues/2423#issuecomment-447653673

**Comment by devsnek** [comment]
taking another look... parcel is changing
```js
import acorn from 'acorn';

acorn.Parser.extend(...);
```

into

```js
_acorn.default.Parser.extend(...);
```

**Comment by mischnic** [comment]
You need to do this:
```js
import * as acorn from 'acorn';
```
because `node_modules/acorn/acorn.mjs` doesn't default export anything:
```js
export { version, parse, parseExpressionAt, tokenizer, Parser, defaultOptions, Position, SourceLocation, getLineInfo, Node, TokenType, types as tokTypes, keywords$1 as keywordTypes, TokContext, types$1 as tokContexts, isIdentifierChar, isIdentifierStart, Token, isNewLine, lineBreak, lineBreakG, nonASCIIwhitespace };
```

I would say acorn is doing something wrong (at least in their documentation), but:
- `node --experimental-modules` runs fine with `import acorn from 'acorn';`.
- [`node -r esm`](https://github.com/standard-things/esm) behaves like parcel.

**Comment by devsnek** [comment]
oh i see. acorn has a `module` field in the package.json. is it possible to disable that?

**Comment by mischnic** [comment]
> oh i see. acorn has a module field in the package.json. is it possible tell parcel to ignore that field?

This would be bad for multiple reasons, but I've just tried it by just removing that line: the error doesn't go away.

**Comment by devsnek** [comment]
@mischnic it wouldn't be that bad... i can disable it in rollup, and (as one of the authors of the node --experimental-modules) i think node's resolution choices here are quite sane.

**Comment by mischnic** [comment]
> it wouldn't be that bad... i can disable it in rollup, and (as one of the authors of the node --experimental-modules) i think node's resolution choices here are quite sane.

Have you read my last comment? I've removed that line in node_modules/acorn/package.json and there is no difference whatsoever. Also, how do you explain the discreptancy between esm and the node flag.

As far as I (and Babel) understand the ES module spec this
```js
function parse(){};

export {parse}; //named export
export default parse; //default export
```
is equivalent to this:
```js
function parse() {};

exports.parse = parse; //named export
exports.default = parse; //default export
```

On the import side
```js
import acorn from "acorn"; // default import
import {parse} from "acorn"; // named import
import * as acorn from "acorn"; // every named import
```
is
```js
const acorn = require("acorn").default; // default import
const parse = require("acorn").parse; // named import
const acorn = require("acorn"); // wildcard import = every named
```

So `import acorn` isn't the same as `import * as acorn`;

**Comment by devsnek** [comment]
@mischnic 

> how do you explain the discreptancy between esm and the node flag.

`@std/esm` is basically a runtime transpiler, and i disagree heavily with a lot of its default behavior

> As far as I (and Babel) understand the ES module spec this

i would argue that babel (and you) misunderstand how esm works, and that it is a fallacy to connect cjs exports to esm exports like that. its more or less not possible to know the exports of a commonjs module before evaluating it (obviously you can look for `module.exports = ...` and `module.exports.a = ...` but it won't work every time), which is why node just attaches `module.exports` to the default export.

this is the reason that node ignores the `module` field, as there are a lot of packages in userland using babel esm behaviour instead of real esm behaviour.

**Comment by mischnic** [comment]
> i would just like to use the cjs module of acorn, hence the change of the title of this issue.

No, this is the order in which they're used: https://github.com/parcel-bundler/parcel/blob/060db2e2c56f08e223e9a9075035f0998e249763/packages/core/parcel-bundler/src/Resolver.js#L295

And once again: I've removed the `module` property manually and the errors stays the same.

---

I'd say according to the ecma262 spec
```js
const x = 10;
const y = 10;
export default x;
export {y};
```
behaves just like
```js
const x = 10;
const y = 20;
export {x as default, y};
```

So it would only make sense, that
```js
import * as module from "something";
module.default == 10;
module.y == 20;
```
and
```js
import module from "something";
module == 10;
```

**Comment by devongovett** [comment]
ES modules are compiled to CommonJS with Babel, so I don't think this would be a parcel issue.

In addition, from the comments above, I believe it is working correctly. The module you are loading is an ES module with no default export, yet you are importing the default. Thus you get undefined as the value. Either change the exports to export a default value, or import a named export.

**Comment by mischnic** [comment]
My previous comment is based on this table from the spec:
![bildschirmfoto 2018-12-16 um 20 06 17](https://user-images.githubusercontent.com/4586894/50057710-57a56c00-016e-11e9-99f8-fb72570fcaf6.png)

Here, "default" is not a special case, it's just like "x". So importing "everything" via a wildcard handles the default export like a named export named "default". 

<br><br>

> the equiv of
> 
> ```js
> export default function a() {}
> export function b() {}
> ```
> 
> in cjs is
> 
> ```js
> module.exports = function a() {}
> module.exports.b = function b() {}
> ```

Strictly, this table contradicts your code:
![bildschirmfoto 2018-12-16 um 20 10 27](https://user-images.githubusercontent.com/4586894/50057733-b79c1280-016e-11e9-8571-141d8434d1a7.png)

But regarding the usage, you're correct: 
```js
// require("lib") == function x(){}
// require("lib").doSomething == function(){}

const x = require("lib");
x("something");
// or
const { doSomething } = require("lib");
doSomething();
```
ESM:
```js
import x from "lib";
x("something");
// or
import { from } from "lib";
doSomething();
```

The destructuring-like syntax in ESM isn't destructuring.

**Comment by devsnek** [comment]
@devongovett 

> The module you are loading is an ES module with no default export, yet you are importing the default.

the thing i'm requesting is to ignore the es module, not to magically make an es module have a default export.

**Comment by devongovett** [comment]
Why would we ignore the es module if it exists?

Either way, @mischnic showed that removing the module field didn't fix your problem anyway.

**Comment by devsnek** [comment]
@devongovett because i'd like to use a module that already works in two other environments (rollup builds and node). i'm not familiar with rollup and so i can't tell you how to fix your bundler, but i know this is possible since we do it in node, rollup supports it, `@std/esm` supports it, and babel supports it.

**Comment by devongovett** [comment]
what module doesn't work? acorn? If so, @mischnic already showed you how to import it above.

**Comment by devsnek** [comment]
@devongovett `import acorn from 'acorn'` works fine with raw babel (because of __iteropRequireDefault), rollup when used with `resolve({ module: false })`, `node --experimental-modules` with no configuration, and `@std/esm` with `mainFields` excluding "module".

should i just use webpack instead? i was hoping this would be an easy system to use but it seems to be falling flat.

**Comment by devongovett** [comment]
I'm confused why it wouldn't work? We don't do any special handling. We just compile with straight up babel: https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/assets/JSAsset.js#L193-L198.

**Comment by devsnek** [comment]
@devongovett there are two parts to this, i'll try to re-converge everything here

1) being able to ignore the `module` field of a package.json, to grab the cjs version of a module. this is important because all the other ways i consume my library which depends on acorn also ignore the `module` field.

2) creating the correct esm namespace for cjs modules. i can't confirm if this works or not since i don't feel like running around my node_modules modifying things, but what should happen is this:

`import acorn from 'acorn'` resolves to `dist/acorn.js`. this is a cjs module, so the namespace that gets created from it should be the abstract equiv of: `{ default: require('acorn/dist/acorn.js') }` (i'm not saying that is what should actually be evaluating, for example babel does `var acorn = __interopRequireDefault(require('acorn/dist/acorn.js'))`)

**Comment by devongovett** [comment]
The compiled code:

```
var _acorn = _interopRequireDefault(require("acorn"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

console.log(_acorn.default);
```

Since there is no default export, importing the default does not work. This is correct behavior.

The same behavior exists when deleting the "module" field from package.json in acorn. This is because of the following line in `acorn.js`:

```
Object.defineProperty(exports, '__esModule', { value: true });
```

Presumably they just precompiled it with babel, which produced the same output as when we use the `module` field from package.json and Parcel compiled it for you.

So I'm not sure what you are expecting to happen. This is the correct behavior according to the spec, and the existing behavior of babel and other tools.
