### ISSUE TITLE
ES5 transpilation on typescript

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#2436]
# 🐛 bug report

Parcel ignores engines.node and still transpile the code with babel

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`
```json
{
  "name": "parcel-node-babel",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "parcel-bundler": "^1.11.0"
  },
  "scripts": {
    "build": "parcel --target node src/index.ts",
    "start": "node dist/index.js"
  },
  "devDependencies": {
    "typescript": "^3.2.2"
  },
  "engines": {
    "node": ">= 8.0.0"
  }
}
```

## 🤔 Expected Behavior

Parcel respect `engines.node` for node just like it respect `browserslist` for the browser target

## 😯 Current Behavior

```js
import JSPackager from 'parcel-bundler/src/packagers/JSPackager'
class Foo extends JSPackager{}
new Foo()
```
The source code is transpiled to ES5 which causes the Foo class to be transpiled to a function and throw `Class constructor JSPackager cannot be invoked without 'new'`

I think it's related to https://github.com/parcel-bundler/parcel/issues/839 but in their case, setting `browserslist` to `"last 1 Chrome versions"` fix the problem, but since in my case the target is node, `browserlist` is replaced by `engines.node` which doesn't work.

## 💻 Code Sample

https://github.com/Banou26/parcel-node-babel

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.3
| Node             | 11.5.0
| npm/Yarn         |
| Operating System |

**Comment by Banou26** [comment]
After some tests, it appears that the code is always transpiled to ES5 when the source is a typescript file , if the file is javascript, the code is properly transpiled using the `browserslist` and `engines.node`

**Comment by Banou26** [comment]
After some more tinkering i finally found the solution to prevent typescript from transpiling to es5
`tsconfig.json`
```json
{
  "compilerOptions": {
    "target": "esnext"
  }
}
```

**Comment by ViktoriaShelestenko** [comment]
> After some more tinkering i finally found the solution to prevent typescript from transpiling to es5
> `tsconfig.json`
> 
> ```json
> {
>   "compilerOptions": {
>     "target": "esnext"
>   }
> }
> ```

THANK YOU! You helped a lot!

**Comment by mischnic** [comment]
We should consider applying browserslist or engines.node to typescript (maybe only if that value isn't already set in tsconfig.json).

**Comment by mischnic** [comment]
See #860
