### ISSUE TITLE
🐛 about SyntaxError: Unexpected token function 

### ISSUE THREAD

**Issue by pftom** [parcel-bundler/parcel#244]
When I first install parcel and run `parcel index.html`, I meet the following problem:

![image](https://user-images.githubusercontent.com/26423749/33926455-30dc14ba-e019-11e7-9c80-6d80e81d6914.png)

env:
```shell
npm: 5.6.0
node: v6.11.2
```

**Comment by DeMoorJasper** [comment]
Run node 8.x+ Async functions are not supported in node 6

**Comment by devongovett** [comment]
We need to compile the `bin` folder with babel to support node 6.
