### ISSUE TITLE
Difficulty using CLI

### ISSUE THREAD

**Issue by Hoten** [parcel-bundler/parcel#2441]
# 🐛 bug report

(wrong way, but I expected it to work)
```
parcel build src/main.ts --public-URL dist/
```

`--public-url` is ignored.

(correct way)
```
parcel build --public-URL dist/ src/main.ts
```

If there's a simple way to tell commander to respect all flags given, no matter the order of positional args, that'd be great.

**Comment by kirillrogovoy** [comment]
I ran into that too lately.

Going to look into it. As far as I understand, the best algorithm is the following:
1. get the initial list of CLI arguments
2. split them into two groups: the flags and the rest
3. apply the flags

**Comment by kirillrogovoy** [comment]
@Hoten It seems like it processes both cases correctly in 1.11.0.

I've tried it out with --public-url and other options and it respected them regardless of the order.

**Comment by Hoten** [comment]
Latest version works for me too.
