### ISSUE TITLE
Opening Html File Directly gives error - phonegap/parcel/mithril

### ISSUE THREAD

**Issue by shekharsom** [parcel-bundler/parcel#2458]
# 🐛 bug report

Hi. I am facing a problem on Mithril with Parcel and couldn't find a solution anywhere including your Github Issues. This is related to phonegap. I am developing a new application and successfully able to parcel it into a bundle. Running the compiled bundle over a server works great. However, when I try to open the html file directly in browser, it gives a lot of error. Therefore, when I put the zip file in phonegap, it doesn't run at al. Any idea where I might be going wrong?

## 🎛 Configuration (.babelrc, package.json, cli command)

Configuraion is same as provided in Parcel.

## 🤔 Expected Behavior

Opening the compiled HTML file directly in browser should run as all the necessary files are available.

## 😯 Current Behavior

Uncaught DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///D:/' cannot be created in a document with origin 'null' and URL 'file:///D:/CodeJS/prasora/build/index.html'.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by DeMoorJasper** [comment]
Try with `--public-url ./` this should make bundle paths relative, which should work for local filesystems.
The default is `/` which makes every path relative to the root, which works great on webservers. But not really on filesystems

**Comment by shekharsom** [comment]
Yes. That's what is done first. 

Without updating it to ./, it gives a different error: GET file:///D:/js.00a46daa.css net::ERR_FILE_NOT_FOUND

But after updating, I am getting the other error

Uncaught DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///D:/' cannot be created in a document with origin 'null' and URL 'file:///D:/CodeJS/prasora/build/index.html'.

**Comment by DeMoorJasper** [comment]
@shekharsom does that work in a normal browser? It might be a phonegap specific thing?

**Comment by shekharsom** [comment]
No. opening the file directly in the normal browser is where this error pops up. It works fine with a server but not without a server.

**Comment by shekharsom** [comment]
I think I found the issue. It is to do with the html history api. There is no solution to this. It will only work in a server environment. 

It works in phonegap by updating the csp.
