### ISSUE TITLE
Add comment header to bundle

### ISSUE THREAD

**Issue by magcius** [parcel-bundler/parcel#2459]
# ❔ Question

Hi. How can I provide a comment header in the final bundle output?

## 🔦 Context

 I would like to point users to where they can see the original GitHub project.

This is also a legal requirement to include proper license headers on external modules. I tried using "@preserve" JSDoc, and while terser does seem to include it sometimes, it's tucked away in a module (which is in random order in the final output), and it doesn't seem to consistently be kept in the output, bizarrely enough.

## 💻 Code Sample

None.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.0
| Node             | v10.0.0
| npm/Yarn         | npm v6.5.0
| Operating System | Windows 10

**Comment by DeMoorJasper** [comment]
Pretty sure it's not an issue to have license headers above the actual licensed code instead of on top of the bundle. Pretty sure terser doesn't remove license headers by default and neither does parcel.

**Comment by DeMoorJasper** [comment]
@magcius Thought the original issue was about license headers of libraries, well this makes sense.

**Comment by DeMoorJasper** [comment]
@outofambit yes feel free to work on this issue. It’ll be necessary at some point

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
