### ISSUE TITLE
Add support for dart [Feature request]

### ISSUE THREAD

**Issue by neutrino2211** [parcel-bundler/parcel#2464]
# 🙋 feature request
Support for .dart files. Dart has become a very popular language over the years and with Google's project Hummingbird on the horizon it is expected to get much more popular so having the support built-in would be great.

## 🤔 Expected Behavior
All .dart files used by a project should be compiled to JS and included in the output.

## 😯 Current Behavior
Files just get copied.

## 💁 Possible Solution
The Dart sdk already comes with `dart2js` which is great at compiling dart to very robust javascript code, so this is the best approach for it.

## 🔦 Context
I love using dart (flutter) for mobile apps and parcel for webapps so it just came naturally to try and marry the two together, plus with Flutter coming to web in the form of HummingBird, having dart built-in would be a great addition.

## 💻 Examples

N/A

**Comment by Taym95** [comment]
I would like to work on this feature!

**Comment by devongovett** [comment]
I’d recommend doing this against v2 at this point. V1 is in maintainence mode, and we’ll be shipping the first alpha of v2 shortly. Everything is on the v2 branch, so take a look at some of the existing transformer plugins.

**Comment by Taym95** [comment]
Yes sure, I am working on PR.

**Comment by devongovett** [comment]
Going to close this. I don't have the bandwidth to implement and maintain this. It would be great as a third party plugin if someone wants to build it!
