### ISSUE TITLE
"Missing class properties transform." error on Flow files with default configuration

### ISSUE THREAD

**Issue by hlian** [parcel-bundler/parcel#2467]
Hi! I'm a big fan of the project. I ran into this small bug today and I filed a minimal repro here: https://github.com/hlian/parcel-bug-maybe

# 🐛 bug report

- Run `rm -rf .cache && yarn parcel bug.js`
- You should get this error:

```
yarn run v1.12.3
$ /Users/chumby/w/parcel-bug-maybe/node_modules/.bin/parcel bug.js
Server running at http://localhost:1234
🚨  /Users/chumby/w/parcel-bug-maybe/bug.js: /Users/chumby/w/parcel-bug-maybe/bug.js: Missing class properties transform.
  2 |
  3 | class Hey {
> 4 |   doesThisWork: number
    |   ^
  5 | }
  6 |
  2 |
  3 | class Hey {
> 4 |   doesThisWork: number
    |   ^
  5 | }
  6 |
```

- Now check out the `ooh-look` branch. It adds a `.browserslistrc` file that specifies the `last 2 chrome versions`
- Run `rm -rf .cache && yarn parcel bug.js` again
- Success!

## 🎛 Configuration (.babelrc, package.json, cli command)

None!

## 🤔 Expected Behavior

No error.

## 😯 Current Behavior

One error! Parcel should correctly strip out that line (it's a Flow type, _not_ a class property).

## 💁 Possible Solution

It's likely that this stems from the Order of Babel Plugins, a mysterious and involved process. You can see [this issue here in babel/babel](https://github.com/babel/babel/issues/4469), where the fix was to reorder the list of presets.

One solution might be to simply prioritize Flow above babel. In `src/transforms/babel/config.js` you can see that

```js
  mergeConfigs(result, envConfig);
```

happens before

```js
  if (!hasFlow) {
    mergeConfigs(result, flowConfig);
  }
```

If I move the first line beneath the second line, it _appears_ to fix the bug. However, I'm sure that this will have all sorts of other spooky side effects for codebases that perhaps depend (without knowing it!) on the current Order of Babel Plugins.

### A SECOND FIX

A second fix might be to avoid merging `envConfig` altogether. In the same way that `transform.js` currently avoids merging in `flowConfig` and `jsxConfig` _if_ it detects that `.babelrc` already includes configuration for them, it might be useful to provide a similar "escape hatch" for `@babel/preset-env`. For example, if Parcel sees that the user has already added `@babel/preset-env` to `.babelrc`, then it **should** be able to safely bypass all the `envConfig` in the first place. Of course, that's a rather big **should**; I'm a newcomer and not familiar with all the intricacies.

## 💻 Code Sample

https://github.com/hlian/parcel-bug-maybe

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0 |
| Node             | 11.2.0 |
| npm/Yarn         | 1.12.3 |
| Operating System | macOS Mojave 10.14.1 |

**Comment by mischnic** [comment]
> A second fix might be to avoid merging envConfig altogether

This is already done in Parcel 2.
