### ISSUE TITLE
Sponsor questions

### ISSUE THREAD

**Issue by MikhailTatsky** [parcel-bundler/parcel#247]
Do you provide sponsor program with link on main site page?

100$ per month with link on main page is cool for start.
Our product FancyGrid (https://fancygrid.com) is thinking about support.
But we need link on main page.

Take a look at https://vuejs.org

**Comment by albinotonnina** [comment]
Hello! Thanks!
This is the link to the sponsor program:
https://opencollective.com/parcel#sponsor
For now the sponsor and baker widgets are in the github repo. I think the website homepage will have them too soon in the near future. I could try to make a PR myself.

**Comment by MikhailTatsky** [comment]
Yes, please write here when you will add site link program.

**Comment by albinotonnina** [comment]
Here's the contributing page, with more details:
https://github.com/parcel-bundler/parcel/blob/master/CONTRIBUTING.md

**Comment by davidnagli** [comment]
@MikhailTatsky Thank you so much considering supporting our amazing tool!

We just opened our Open Collective yesterday, so we didn’t have time to add links to all of our sponsors everywhere yet (such as our website), but we definitely plan to do so!

**Comment by MikhailTatsky** [comment]
Let me share with some extra information.
You changed prices on sponcor program.

VueJS takes 500$ per month and add logo on main page but look at their number of visits
https://www.similarweb.com/website/vuejs.org
Almost 9 mls per month!
We supported them for small period but get just 15,000 visitors per months.

In your case, you ask too high.
The reasone why companies become sponcor is self advertising.
Ads money could be spend on
1 - Google ads that does not bring much result
2 - Articles, it is affective
3 - Supporting small product to get traffic

We are small company and spend every month 
1 - 500$ per different services
2 - 200$ per different ads projects
We can spend else max 200$ per ads per month but it should be effective.

We do not know your traffic.
The only we see, it is trend on your popularity that could be ended in 1-2 months since webpack is serious solution
http://alexa.com/siteinfo/parceljs.org

You need to set wise prices on sponcor according to your traffic.
