### ISSUE TITLE
Removes ids from inline-svgs in pug

### ISSUE THREAD

**Issue by Mobilpadde** [parcel-bundler/parcel#2474]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "devDependencies": {
    "autoprefixer": "^9.4.3",
    "parcel-bundler": "^1.10.3",
    "parcel-plugin-purgecss": "^2.1.0",
    "parcel-plugin-sitemap": "^2.0.1",
    "parcel-plugin-sw-precache": "^1.0.3",
    "pug": "^2.0.3",
    "stylus": "^0.54.5"
  }
}
```

## 🤔 Expected Behavior

Should not remove ids from svg when building pug files for prod; not dev.

**EDIT**: Works as supposed when `--no-minify`-flag is enabled?

## 😯 Current Behavior

Removes ids from svg when building pug files. But only svg.

PS. Only tried it with inline-svgs

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0 |
| Node             | 11.3.0 |
| Yarn         | 1.12.3 |
| Operating System | 4.19.12-2-MANJARO |

**Comment by lustoykov** [comment]
Thanks for the report!

I've spent some time debugging, I think the issue is that [htmlnano](https://github.com/posthtml/htmlnano) strips away the id from svg when minifying. [Here](https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/transforms/htmlnano.js#L18) is the relevant code in parcel. If we log `asset.ast` before and after the line, we could see the difference.

Here is a minimal [example](https://codesandbox.io/s/o9mlp314mq) that isolates htmlnano.

**Comment by Mobilpadde** [comment]
Oh, thanks! :+1: Nice find!

**Comment by mischnic** [comment]
@Mobilpadde 
Add a `.htmlnanorc` file with 
```json
{
	"minifySvg": {
		"plugins": [
			{ "cleanupIDs": false }
		]
	} 
}
```

**Comment by Mobilpadde** [comment]
Thanks a ton, @mischnic! :dancer: Works like a charm :gem:

**Comment by thedamon** [comment]
This is really weird to track down (i had it happening for me from Vue svg files). 

If we're talking good defaults (which is the point of parcel?) I feel this should not be the default for inlined svgs.

**Comment by mischnic** [comment]
> If we're talking good defaults (which is the point of parcel?) I feel this should not be the default for inlined svgs.

**Comment by DeMoorJasper** [comment]
Might be good to open a PR in `htmlnano` for this.
The maintainer of htmlnano has been very open to improvements to the defaults in the past.

**Comment by npulidom** [comment]
Adding a `.htmlnanorc` file to skip svg inline minification works.
```
{
	"minifySvg": false
}
```

**Comment by egillespie** [comment]
If it appears that your `.htmlnanorc` file is being ignored, run Parcel with the `--no-cache` option.

**Comment by speigg** [comment]
This htmlnanorc is breaking html-embedded SVG. This doesn't seem like something that should be enabled by default.

**Comment by mischnic** [comment]
Note: for once, Parcel doesn't override the default of https://github.com/posthtml/htmlnano:
https://github.com/parcel-bundler/parcel/blob/2c65fbf911cd1d80fb121178e72148f53f474d61/packages/core/parcel-bundler/src/transforms/htmlnano.js#L7-L16

Maybe this should be fixed in htmlnano?

**Comment by speigg** [comment]
Or maybe switch to another html minimizer? Surely there are others that are more robust?

**Comment by BigPackie** [comment]
> 
> 
> If it appears that your `.htmlnanorc` file is being ignored, run Parcel with the `--no-cache` option.

or just delete the ".cache" folder before building.

**Comment by vasanthdeveloper** [comment]
I deleted `.parcel-cache` and have `--no-cache` in both `parcel serve` and `parcel build` commands. Here's my `.htmlnanorc` 👇

```json
{
    "removeUnusedCss": false,
    "minifySvg": false
}
```

But still IDs are being stripped from inlined SVGs 😕

**Comment by chapma26** [comment]
Stripping id attributes from svg tags is *NOT* acceptable default behavior but maybe this only happens in pug? I just spent an hour trying to track down why my js was broken on prod when my dev environment was fine only to realize the minified files had the id attribute removed. Came to report it as a bug but found this closed issue. I fixed this issue with @vsnthdev solution above.
