### ISSUE TITLE
"bundled" event getting fired on every rebuild

### ISSUE THREAD

**Issue by samrith-s** [parcel-bundler/parcel#2476]
# ❔ Question

Is the `bundled` event supposed to fire after EVERY rebuild during development?

## 🔦 Context

I'm running a post-process script which injects some JS into my HTML, using `parcel-plugin-build-hooks` on the `bundled` event. 

My post-process script is getting called on every rebuild during `serve` mode. Which is getting a bit out of hand, because now I have 100 jQuery script tags injected into my HTML! 😨

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.10.3
| Node             | 10.5.0
| npm/Yarn         | 1.7.0
| Operating System | macOS High Sierra

**Comment by mischnic** [comment]
The [docs](https://parceljs.org/api.html#events) say otherwise, but I think it's really getting emitted on every build:
> `bundled` gets called once Parcel has successfully finished bundling **for the first time**, the main bundle instance gets passed to the callback

**Comment by samrith-s** [comment]
That's what I thought so, but I can consistently see it getting fired on every rebuild as well. 😢

**Comment by DeMoorJasper** [comment]
@samrith-s the behaviour might have changed since the docs were written although they are probably just incorrect. Unfortunately there is no other event to listen for that would only emit once

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DeMoorJasper** [comment]
@alidcastano yes this appears to be the expected behaviour and docs were probably never correct

**Comment by mischnic** [comment]
Docs are correct now
