### ISSUE TITLE
How can I use parcel when I install it locally?

### ISSUE THREAD

**Issue by zhuxindaba** [parcel-bundler/parcel#248]
when i run parcel using node scripts, i went error:
![image](https://user-images.githubusercontent.com/17308154/33933767-b4e61194-e031-11e7-8260-f650f36b8bcd.png)

**Comment by albinotonnina** [comment]
What version of node you have installed?
The minimum version to run Parcel is 8

**Comment by DeMoorJasper** [comment]
This seems related to #244 please close this if it is the same issue (using Node.js 6.x)

**Comment by albinotonnina** [comment]
Closing, related to #244

**Comment by zhuxindaba** [comment]
thx, when i upgrade node version to 8, it's ok!

**Comment by romainl** [comment]
> The minimum version to run Parcel is 8 at the moment.

You should add that information to your README and web page.

**Comment by DeMoorJasper** [comment]
@romainl It's just a support bug, not the minimum version. It should work fine on node 6 probably when the next release drops

**Comment by romainl** [comment]
@DeMoorJasper but right now it doesn't, which makes `yarn add parcel-bundler` a waste of time for some users and… the Parcel crew.

**Comment by yuritoledo** [comment]
I'm on 9.9 node and I cant use async await yet :/
