### ISSUE TITLE
cache bug with TypeScript + dotenv

### ISSUE THREAD

**Issue by hirochachacha** [parcel-bundler/parcel#2480]
# 🐛 bug report

I was using `TypeScript` + dotenv.
I changed `.env` file, but `parcel` didn't recognize that change even when I restarted `parcel`.

## 🎛 Configuration (.babelrc, package.json, cli command)

None.

## 🤔 Expected Behavior

alert('bar')

## 😯 Current Behavior

alert('foo')

## 💁 Possible Solution

I guess that this is cache bug.

## 💻 Code Sample

index.ts
```
const process = require("process");

alert(process.env.MSG);
```

index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
  <script src="./index.ts"></script>
</head>
<body>

</body>
</html>
```

.env
```
MSG=foo
```

```
MSG=bar
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | v11.5.0
| npm/Yarn         | Yarn 1.12.3
| Operating System | macOS

**Comment by jessicard** [comment]
I am also seeing this issue 🙋

**Comment by mischnic** [comment]
> I am also seeing this issue 🙋

This should be fixed in the next release
