### ISSUE TITLE
transform commonjs modules in preserved jsx files

### ISSUE THREAD

**Issue by alidlorenzo** [parcel-bundler/parcel#2481]
# 🐛 bug report

related to https://github.com/parcel-bundler/parcel/issues/1199

if typescript option is set to `{ jsx: preserve }` (so that babel transforms can work on jsx files), then those files won't get transformed by typescript rules (i.e. `esModuleInterop`). 

i tried adding `babel-plugin-transform-modules-commonjs` but that did not work with Parcel, so I'm guessing these final transforms must be done by Parcel itself.

as a related issue, it doesn't seem like Parcel adheres to typescript's `extend` rule and only picks up rules from the config in the root directory.

## 🤔 Expected Behavior

`Import React from 'react` would not result in a `react is undefined` reference error

## 😯 Current Behavior

must do `import * as React from 'react` or have `{ jsx: react}` in typescript config

## 🔦 Context

not transforming commonjs modules results in cryptic `X is undefined` bugs

**Comment by jbreckmckye** [comment]
I have this problem too (Parcel version 1.12.4). Not sure if it's fixed in the v2 branch.
