### ISSUE TITLE
Using Parcel + TypeScript + Preact + preact-compat

### ISSUE THREAD

**Issue by lukejagodzinski** [parcel-bundler/parcel#2482]
Hi, I'm trying to use Parcel with TypeScript and Preact and it works when I'm importing from `preact` library. However, I already have project created with React and I'm also using other libraries that depends on React, so I would like to use `react-compat` to alias `react`. I've done everything that I could find in docs and posts about that problem and nothing works. I still get the `Uncaught ReferenceError: h is not defined`. I've create reproduction repository: https://github.com/lukejagodzinski/parcel-typescript-preact-bug/tree/master

My files:

**tsconfig.json**
```json
{
  "compilerOptions": {
    "lib": ["dom", "es2016", "esnext.asynciterable"],
    "jsx": "react",
    "jsxFactory": "h",
    "baseUrl": ".",
    "paths": {
      "react": ["node_modules/preact-compat/"],
      "react-dom": ["node_modules/preact-compat/"]
    }
  }
}
```

**package.json**
```json
{
  "name": "preact-test",
  "version": "1.0.0",
  "scripts": {
    "start": "parcel serve src/index.html --out-dir dist --port 3000 --open",
    "build": "parcel build src/index.html --detailed-report --experimental-scope-hoisting --out-dir dist"
  },
  "devDependencies": {
    "@types/react": "^16.7.18",
    "@types/react-dom": "^16.0.11",
    "parcel-bundler": "^1.11.0",
    "typescript": "^3.2.2"
  },
  "dependencies": {
    "@material-ui/core": "^3.8.1",
    "preact": "^8.4.2",
    "preact-compat": "^3.18.4",
    "react": "^16.7.0",
    "react-dom": "^16.7.0"
  },
  "alias": {
    "react": "preact-compat",
    "react-dom": "preact-compat"
  }
}
```

**src/main.tsx**
```tsx
import * as React from "react";
import { render } from "react-dom";
import Typography from "@material-ui/core/Typography";

class App extends React.Component {
  render() {
    return <Typography>Test</Typography>;
  }
}

render(<App />, document.getElementById("root"));
```

Do you know how to properly alias `react` to `preact-compat`?

**Comment by lukejagodzinski** [comment]
I appears that I had to change `"jsxFactory": "h"` to `"jsxFactory": "React.createElement"` when using `preact-compat`. However, more complex `material-ui` components doesn't work well with `preact-compat` as it complains about installing react. Tere is no support for `React.createContext` in `preact-compat` yet. I will update reproduction repository so any person having similar issue will have a solution.

**Comment by soos555** [comment]
Vvvb
