### ISSUE TITLE
TypeScript source maps don't match lines

### ISSUE THREAD

**Issue by QuantumInformation** [parcel-bundler/parcel#2495]
Just started a new project yesterday and sourcemaps debugging doesn't hit the correct lines in chrome. Using `    "build": "parcel build ./src/index.ts --out-dir chrome-extension"`

![image](https://user-images.githubusercontent.com/216566/50588472-dbf43080-0e8a-11e9-85af-3450d8894dc3.png)

can't hit my breakpoints

![image](https://user-images.githubusercontent.com/216566/50588573-6d63a280-0e8b-11e9-9f6f-0ab1c0e7e3b6.png)

**Comment by DeMoorJasper** [comment]
Any reproducable example?

**Comment by QuantumInformation** [comment]
Sorry I have migrated to webpack already.

**Comment by devongovett** [comment]
lol, @QuantumInformation this is not very useful. You come on our issue tracker, complain about a possible bug, but give us no information. Then you just close it without any more details since you migrated to another tool? We would like to help you and others out that might have this bug, but we need more info in order to do that. 🤷‍♂️

**Comment by QuantumInformation** [comment]
Ok, my apologies, my decision timescales are so quick I didn't think of the social aspects this time.

**Comment by mischnic** [comment]
I can't reproduce this, but something has gone very wrong: in the second screenshot, there is a possible breakpoint location in the middle of a variable.

**Comment by magcius** [comment]
I'm seeing similar behavior in my project, but it's quite big. I can't seem to reproduce it in a smaller project.

**Comment by mischnic** [comment]
> I'm seeing similar behavior in my project, but it's quite big. I can't seem to reproduce it in a smaller project. Would it be OK using that to debug?

If this happens consistently and you're willing to share the project, of course!

**Comment by mischnic** [comment]
> "this" is null, time looks correct, and the third variable is called "window." Hovering over "shouldTakeScreenshot" says "shouldTakeScreensho" is not defined:

Are you using a recent parcel? Works fine for me:
![screenshot 3](https://user-images.githubusercontent.com/4586894/50975984-20b54280-14ef-11e9-8af7-3357e7474440.png)
You could try deleting the cache folder

**Comment by DeMoorJasper** [comment]
Also, is this only after a hmr or also on initial?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by magcius** [comment]
I the "throw exception" trick to turn off HMR entirely. It doesn't work for me. My version of Parcel is about 20 days old. I will try deleting the cache directory entirely.

**Comment by DeMoorJasper** [comment]
@mischnic are you on windows? Perhaps this is an issue with windows, although I doubt it.

@magcius You've already shared the code, so not sure what else you can provide if this happens all the time. You could provide reproduction steps if this only happens sporadically

**Comment by magcius** [comment]
It appears to be completely consistent for me.

There might be something else in my workflow or environment that might be affecting it (I'm not sure I always trust yarn lockfiles), but I'm not sure what it might be.

**Comment by mischnic** [comment]
> are you on windows? Perhaps this is an issue with windows, although I doubt it.

Running parcel on macOS and viewed in Chrome on Windows, because my mac doesn't support WebGL 🙈 . How could this be platform specific?

**Comment by magcius** [comment]
Line endings, perhaps? I should probably check what line endings I'm using locally.

**Comment by QuantumInformation** [comment]
this is when I last used parcel

https://github.com/QuantumInformation/audio-orders/tree/23ee4fa2a14c42e92e2661bad59f01a9001b5350

should have the bug in there

**Comment by aalpgiray** [comment]
What is the status? I am having the same issue. On windows and ubuntu (elementary os). 
As it seems the issue appears when and HMR event takes place. However, reloading the page doesn't cut. Stoping parcel and running again is working.

**Comment by magcius** [comment]
Yes. It was fixed a while back, but I recently updated Parcel and started seeing this again.

**Comment by mischnic** [comment]
@aalpgiray Could you please provide a reproduction?
Sourcemaps don't work with HMR, I've tried to fix this but no browser would support the current approach by Parcel (https://github.com/parcel-bundler/parcel/issues/643).

**Comment by aalpgiray** [comment]
The project is internal. However, I will create a simpler copy of the project at the weekend. If we are lucky that would have the same problems as well. :)

**Comment by aalpgiray** [comment]
@mischnic hi again I'd published the repo. https://github.com/aalpgiray/parcel-web/tree/43f54b6c28e02592c7b64448f4f65fb663772687. you can modify todos.tsx file while having yarn start running. Best of luck. Cheers.

**Comment by kbtzr** [comment]
Probably not the same thing that caused OP's issue, but in my case I was debugging from a hostname other than `localhost`. Adding `--host myhostname` to my parcel command fixed the issue for me.

**Comment by magcius** [comment]
Still seeing this on my project. When it happens, restarting Parcel will solve the issue. I don't need to clear the cache.

**Comment by DeMoorJasper** [comment]
This seems strange, I've discovered a few bugs in sourcemaps when working on sourcemaps for Parcel 2. I doubt sourcemaps will be further improved for v1 unfortunately.

So my guess is this is fixed in Parcel 2, sill leave this open until it's confirmed, would be great to get this confirmed once Parcel 2 reaches an even more stable state

**Comment by patrickgalbraith** [comment]
I had this issue on Windows with Hyper-V enabled. When running parcel v1 I got this message "configured port 1234 could not be used."

Manually setting the port fixed it (see below).

```
parcel index.html --port 51234 --hmr-port 51235
```
