### ISSUE TITLE
registerExtension support queue

### ISSUE THREAD

**Issue by rambo-panda** [parcel-bundler/parcel#2496]
# 💬 RFC

Is it possible to let the [registerExtension](https://github.com/parcel-bundler/parcel/blob/a0df88665f00330c0f8265233308d1a590087868/src/Parser.js#L60) method support the queue?

## 🔦 Context
Now if l want to do different things for the same type of file, l must do l own dependency management in the plugin.

## 💻 Examples
```js
bundler.addAssetType('.png', 'min.js');
bundler.addAssetType('.png', 'transform.js');
```

**Comment by devongovett** [comment]
This will be supported in Parcel 2 via transformer pipelines, which you'll be able to configure via `.parcelrc`. See https://github.com/parcel-bundler/parcel/blob/master/PARCEL_2_RFC.md#parcelrc
