### ISSUE TITLE
Parcel 2: Allow transformer plugins to control cache invalidation

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#2499]
Transformer plugins may need to control when the cache is invalidated. For example, a plugin that inlines environment variables would need to invalidate the cache when those environment variables change.

We could consider simply invalidating the cache whenever ANY environment variable changes, but that would cause too many unneeded invalidations since there are typically lots of environment variables on people's systems that change frequently. It would also make the cache less portable. There will also be other cases when plugins may need to do something custom.

In Parcel 1, there is a `shouldInvalidate` method on transformers for this use case. It will be slightly more complicated in Parcel 2 since there can be multiple transformers in a pipeline that might need to handle this separately.

Proposed implementation:

* Add an optional `shouldInvalidateCache` method to transformers, which is passed a reference to the cached asset's `meta` property. This property lets transformers store custom data on an asset, which is included in the cache. The `shouldInvalidateCache` method could do some comparisons using that data, and return a boolean indicating whether the cache entry should be invalidated.
* The TransformerRunner would call each transformer's `shouldInvalidateCache` method in the pipeline, and if any of them return `true`, the cache entry would be ignored and the pipeline would be fully executed as if there were no cache entry.

**Comment by abdullahtariq1171** [comment]
Thank you @padmaia for writing this comprehensively, It will definitely be helpful, I listed down points from you comment that we need to check for cache as checking only `shouldInvalidateCache` doesn’t suffice 

1. Check if transformer pipeline is changed for a asset (this includes order of transformers too)
2. Check if transformer/plugin `version` of is changed 
2. Check if transformer config is changed, We need cache `transformer.getConfig` results for this
3. Run `shouldInvalidateCache` for stuff like inlines environment variables

--
I totally agree and support idea of agnostic cache, I am not familiar with cache module though I will look into it see what I can do. Will ping if I needed any help.

--
**HELP NEEDED: Questions:** 
- As we need transformer/plugin meta (version, name) and In our `Config` module, we are using `localRequire` which doesn't return the `package.json` data although [resolve](https://github.com/browserify/resolve#resolveid-opts-cb) returns pacakge.json in cb data but we are not using it at the moment (as far as i know). Please confirm and I will create a utility function

- I couldn't figure out how are we testing/running on v2 branch? I see there is 
https://github.com/parcel-bundler/parcel/blob/v2-work-so-far/packages/core/core/bin.js but it throws error for me.

**Comment by devongovett** [comment]
This was fixed by #5112
