### ISSUE TITLE
Elm: Bulk compile assets to avoid duplication

### ISSUE THREAD

**Issue by ulisses-alves** [parcel-bundler/parcel#2508]
# 🙋 feature request

Bulk compile Elm assets to avoid shared code duplication.

## 😯 Current Behavior

Given that Elm modules `A` and `B` have their own main functions, and both depend of common libraries such as `elm/browser`, `elm/json`, and then imported and initialized as follows:
```javascript
import A from './A.elm'
import B from './B.elm'

A.init(...)
B.init(...)
```
That way, each module gets compiled individually alongside their own dependencies, causing dependencies to be bundled twice, thus producing a much larger output in comparison to:
`elm make ./A.elm ./B.elm output=bundle.js`

## 💁 Possible Solution

One solution would be using glob imports:
```javascript
import Bundle from './*.elm'

Bundle.A.init(...)
Bundle.B.init(...)
```
Although being pretty cool, this might conflict with the existing glob import behavior.

A less ideal solution, would be defining an external file with bundle definitions:
```javascript
// elm-bundles.json
{
    "app": [
        "./A.elm",
        "./B.elm"
    ]
}
```
So `ElmAsset.js` could check if a given asset is present in a bundle, and then build the bundle instead of the individual asset.

A similar solution has been implemented in `elm-webpack-loader`.

## 🔦 Context

In my current setup, I have around a dozen Elm element apps being imported into the same application. When importing directly through parcel, the output is more than three times as large than `elm make A.elm B.elm ...` outputs.

**Comment by stephenreddek** [comment]
This would be very helpful! I have been using the mentioned bundle approach in webpack with [elm-webpack-project-loader](https://github.com/joeandaverde/elm-webpack-project-loader) (this is distinct from the standard elm-webpack-loader) for a while with good success.

**Comment by domenkozar** [comment]
Seems like looking into globbing is our best option, I'd expect each asset can define on it's own how to deal with this. Maybe it already works?

**Comment by domenkozar** [comment]
![2019-03-01-151735_362x337_scrot](https://user-images.githubusercontent.com/126339/53625265-81f9b800-3bfa-11e9-9d75-2d6578dd37a4.png)

Using `Main*.elm` and files `Main.elm` and `MainFooter.elm` I get the above, pretty close! :D

**Comment by domenkozar** [comment]
Aha, `Ma*.elm` results into this. Can see what's going on.

![2019-03-01-151927_435x248_scrot](https://user-images.githubusercontent.com/126339/53625360-ca18da80-3bfa-11e9-93a3-84545bd2cb3e.png)

**Comment by domenkozar** [comment]
So I think there's two things to be done:

- [ ] document this practice for parcel 
- [ ] fix globbing when glob doesn't contain the full filename

**Comment by MattCheely** [comment]
One thing I considered while experimenting with this was using a [bundler](https://parceljs.org/api.html). The idea was that the Elm asset handler wouldn't actually do any compilation, just track all of the included files via some intermediate type it generates. The bundler would be configured to use the intermediate type, and can see all of the files, and handle compilation at that stage.  I wasn't able to spend enough time on it though to determine if there was a way to get that result picked up by the JS bundler.
