### ISSUE TITLE
How do I deploy my webpage after running `parcel build index.html`?

### ISSUE THREAD

**Issue by caroline-lin** [parcel-bundler/parcel#2511]
# ❔ Question
How do I deploy my webpage after running `parcel build index.html`?

## 🔦 Context
This is a small webpage with a canvas element, and some Typescript for manipulating the canvas and CSS for styling. 

I have a Ubuntu server that I've set up tiny flask apps on before, but I've never worked with Node.js and am unfamiliar with a lot of the Javascript ecosystem. My server has nginx running on it.

## 💻 Code Sample

Here is my abridged index.html (after running `parcel build index.html`):

```
    <!DOCTYPE html>
    <head>
      <title>Nothing to see here!</title>
      <link rel="stylesheet" href="/sidebar.04cc1813.css">
    </head>
    <body>
      <aside class="sidenav">
        <h1>A sidebar</h1>
      </aside>
    
      <section class="main">
        <p>Welcome to the semantic web!</p>
        <canvas id="theCanvas" width="600" height="600"></canvas>
      </section>
      <script src="/main.9b45144c.js"></script>
    </body>
```
Here is my `/etc/nginx/sites-enabled/mysite.com`:

```
   server {
            listen 80;
            listen [::]:80;

            root /var/www/mysite.com/html;
            index index.html index.htm index.nginx-debian.html app.html;
    
            server_name mysite.com www.mysite.com;
    
            location / {
                    try_files $uri $uri/ =404;
            }  
    }
```

## 🌍 Your Environment

I'm using nginx 1.14.0. The server is a DigitalOcean droplet.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             |
| npm/Yarn         | 3.5.2
| Operating System | Ubuntu 18.10

**Comment by mischnic** [comment]
If you want your page to be accessible at www.mysite.com, put all files inside the dist folder into `/var/www/mysite.com/html`.
If you want to use mysite.com/some-page/, you need to pass `--public-url` when building.

**Comment by caroline-lin** [comment]
This answers my question (ended up building with `--public-url ./`).
