### ISSUE TITLE
CSS Import: Cannot find module 'XXXX'.

### ISSUE THREAD

**Issue by notiv-nt** [parcel-bundler/parcel#2515]
# 🐛 bug report

Using **gulp-parcel** for build only js , i got an error:

![image](https://user-images.githubusercontent.com/10743009/50728665-89429f00-113e-11e9-949e-006083e0c8db.png)

### Create an empty folder:

```
yarn add parcel-bundler
```

### Add 2 files:

```
main.js -> import('./main.css').then()
```

```
main.css -> body { color: red; }
```

### Run

```
npx parcel build main.js
```

or globally

```
parcel build main.js
```

## 🤔 Expected Behavior

`dist/main.js`

See screen

## 😯 Current Behavior

![image](https://user-images.githubusercontent.com/10743009/50728650-53051f80-113e-11e9-8546-a93a523aeefc.png)

`parcel build` adds weird 'XXXX' (module?)
What is it?

The same but with `parcel serve main.js`

![image](https://user-images.githubusercontent.com/10743009/50728701-4af9af80-113f-11e9-829b-7eb638f36650.png)

## 💁 Possible Solution

Looks like it is minified css filename???
Or chunk name? But there is no such file

![image](https://user-images.githubusercontent.com/10743009/50728744-0cb0c000-1140-11e9-8d70-1c34a917cb7e.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | v11.2.0
| npm/Yarn         | 6.4.1 / 1.12.3
| Operating System | MacOS

---

css is loading on real project, but I got an error

**Comment by notiv-nt** [comment]
In production code:

![image](https://user-images.githubusercontent.com/10743009/50730144-fb26e280-1156-11e9-9131-30760a29df03.png)

![image](https://user-images.githubusercontent.com/10743009/50730153-27426380-1157-11e9-876f-6bc006ced074.png)

**Comment by QuantumInformation** [comment]
I switched from `require`

`    this.background.src = require('./images/backgrounds/sunrise.jpg')`


 to this https://github.com/QuantumInformation/youtube-space-invaders/blob/b/src/SpaceInvaders.ts#L14

**Comment by andreidcm** [comment]
I'm encountering the same thing `Error: Cannot find module 'rWEx'` but only in build bundle, when I serve locally it works.

**Comment by DeMoorJasper** [comment]
@andreidcm if this happens in Parcel 1 could you try Parcel 2?

We’re trying to get parcel 2 to stable as fast as possible and it’s already fairly stable.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
