### ISSUE TITLE
Parcel does not rebuild files on macOS in large project with recent versions of NodeJS

### ISSUE THREAD

**Issue by samvv** [parcel-bundler/parcel#2516]
# 🐛 bug report

Parcel did not rebuild my files as soon as the project reached a certain size. This happened on a mid-2014 MacBook Pro running macOS Mojave. I've found a solution to the issue but I thought I'd share the solution in case anyone else stumbles on it.

## 🎛 Configuration (.babelrc, package.json, cli command)

Just a regular  `parcel index.html` on a relatively large private code base using TypeScript.

```json
{
  "compilerOptions": {
    "jsx": "react",
    "target": "ES6",
    "outDir": "lib"
  }
}
```

## 🤔 Expected Behavior

Editing a file and then saving it should trigger a rebuild.

## 😯 Current Behavior

Nothing happens; stopping the build and re-starting it manually produces the correct output.

## 💁 Possible Solution

Increasing the file descriptor limit with `ulimit -n 10032` solved the issue on my system. For more information, read [this article](https://wilsonmar.github.io/maximum-limits/).

## 🔦 Context

Building a new code editor application and Parcel has saved me tonnes of time. Thank you very much for making such an awesome bundler!

## 💻 Code Sample

https://gist.github.com/samvv/66b1bec368c4960550d2061885e72e4a

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | 11.5.0
| npm/Yarn         | 6.4.1
| Operating System | Mojave 10.14

**Comment by samvv** [comment]
Like I already mentioned, setting `ulimit -n` to a better value solved the issue.

**Comment by samvv** [comment]
I'm re-opening this issue because it appears I was wrong: after some digging I've found that my recent version of NodeJS (11.5.0) is to blame. I've done a bisection on the version of NodeJS that introduced the issue, and found that the change from NodeJS v9.11.2 to v10.0.0 causes the issue. With the old version it works fine, with newer versions it does not. These are the relevant changes, I believe:

- [897f7b6c6b] - (SEMVER-MAJOR) fs: improve errors in watchFile and unwatchFile (Joyee Cheung) #19345
- [301f6cc553] - (SEMVER-MAJOR) fs: remove watcher state errors for fs.watch (Joyee Cheung) #19345
- [6c25f2ea49] - (SEMVER-MAJOR) fs: improve errors thrown from fs.watch() (Joyee Cheung) #19089
- [5b705cddcc] - (SEMVER-MINOR) fs: add 'close' event to FSWatcher (Alec Larson) #19900

I've no idea how to continue from there, though. Maybe someone else knows what to do?

**Comment by samvv** [comment]
Managed to reduce the issue as being TypeScript-specific as well. When using regular JavaScript, everything works fine, but as soon as one TypeScript dependency is added, things stop working.

I've created a minimal example of this behavior: https://gist.github.com/samvv/66b1bec368c4960550d2061885e72e4a. It's really strange that such a simple example is not working. Maybe I'm overlooking something, but I don't know what. Did a fresh reinstall of everything.

**Comment by mischnic** [comment]
With this 
```js
import rand1 from './rand1'
```
typescript eliminates the unused import. This works correctly:
```js
import rand1 from './rand1'
console.log(rand1);
```

**Comment by samvv** [comment]
You're completely right! I forgot that; thanks. The issue still exists in my project, though, and I have to check but I'm fairly sure I'm importing and using everything. Will update the gist accordingly.

**Comment by samvv** [comment]
Ok so I think I need to take a break 😆 Turns out my import was wrong, sorry for the noise!
