### ISSUE TITLE
🐛 Parcel does not generate index.html if source index.html is in root

### ISSUE THREAD

**Issue by Alamantus** [parcel-bundler/parcel#252]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
Bug report

I'm trying to set up a project with parcel, but when I run `parcel index.html`, it compiles it into `dist/{project-name}.html` and doesn't serve it from `localhost:1234`. In order to get it to load, I need to go to `localhost:1234/dist/{project-name}.html`, but then the hotloader doesn't work.

I found that I can get around this by copying `dist/{project-name}.html` to `dist/index.html`, but that seems like an extra step that shouldn't be necessary.

When I move `index.html` to `src/index.html` and run `parcel ./src/index.html` it works correctly, generating `dist/index.html`, but it should be able to create the `dist/index.html` from anywhere instead of only from a subfolder.

### 🤔 Expected Behavior
Running `parcel index.html` should generate `dist/index.html` instead of `dist/{project-name}.html` so that `localhost:1234` will load the project.

### 😯 Current Behavior
Running `parcel index.html` generates `dist/{project-name}.html`, which then causes `localhost:1234` to display nothing.

Another quirk I noticed: https://github.com/parcel-bundler/parcel/issues/252#issuecomment-351507496

### 💁 Possible Solution
Workaround: copying `dist/{project-name}.html` to `dist/index.html` lets `localhost:1234` load and works with the hotloader.

### 🔦 Context
Here is the project that this is failing for: https://github.com/Alamantus/cart-test

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  1.2.0
| Node             | 8.9.3
| Yarn         | 1.3.2
| Operating System | Windows 7

**Comment by Alamantus** [comment]
I've found that parcel seems to be doing this if `main` in the `package.json` is pointing to an actual file.

Running just `parcel` with `main` set to `./src/index.html` outputs `dist/{project-name}.html` (i.e. `name` in `package.json`). Even if you run `parcel ./src/index.html`, it still does this as long as `main` is set correctly.

Ensuring that `main` does not point to an actual file seems to be the key, because changing it to a nonexistent file causes parcel to output to `dist/index.html` as it should.

**Comment by brandon93s** [comment]
Seems this behavior may be deliberate at the moment:

https://github.com/parcel-bundler/parcel/blob/86835793a513b43af906a02083eed72b7eb9e0d2/src/Asset.js#L146-L166

However, knowing more now it's certainly problematic.

**Comment by davidnagli** [comment]
Do you guys think we should change this behavior? 

I don’t see any good reason why we should be naming the file based on the package name rather than just `index.html`

**Comment by Alamantus** [comment]
I feel like at the very least the dev server should also take the `main` setting into consideration when serving the content. For instance, if `main` is valid, then serve `project-name.html` _as_ `index.html`. I can see some benefit to having the output be the project name, but it’s impossible to test with parcel’s dev server if it’s done that way.

This behavior definitely needs to be documented somewhere on the website, though.

**Comment by abradley2** [comment]
> This behavior definitely needs to be documented somewhere on the website, though.

Yeah. Right now the documentation doesn't give any reason why having this in the root would break everything, which is especially surprising since parcel creates it's own little `dist` directory,

Perhapse a note along the lines of "index.html and index.src" should be put into a subdirectory, not the root?

**Comment by binuWN** [comment]
Make sure your package.json  "script":{ index.html}  path is corect.
