### ISSUE TITLE
Tree shaking not working with React code splitting

### ISSUE THREAD

**Issue by kpentchev** [parcel-bundler/parcel#2520]
# 🐛 bug report

I have a simple web application build with Parcel. I use React with route-based code splitting.

## 🤔 Expected Behavior

Building with `--experimental-scope-hoisting` produces a working app. Building without it as well.

## 😯 Current Behavior

Building with `--experimental-scope-hoisting` is successful. However, when the app is served a runtime error is thrown:

```
main.3efc1665.js:1 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at kI (main.3efc1665.js:1)
    at q (main.3efc1665.js:1)
    at gh (main.3efc1665.js:1)
    at main.3efc1665.js:1
...
vu @ main.3efc1665.js:1
main.3efc1665.js:1 Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at kI (main.3efc1665.js:1)
    at q (main.3efc1665.js:1)
    at gh (main.3efc1665.js:1)
    at main.3efc1665.js:1
...
example-container.4621c8ba.js:1 Uncaught Error: Cannot find module 'HdMw'
    at u (example-container.4621c8ba.js:1)
    at example-container.4621c8ba.js:1
    at example-container.4621c8ba.js:1
    at example-container.4621c8ba.js:1]
```
Building without it produces an app with no runtime errors.
## 💁 Possible Solution

Maybe related to same components being loaded both statically and dynamically.

## 💻 Code Sample

https://github.com/kpentchev/react-parcel-treeshake-codesplit-bug

Build with either ```npm run-script build``` or ```npm run-script build:working```.
Serve with ```npm run-script serve``` on port 5000.
Removing `SideNav` component from `main.js` produces a working build with tree shaking.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | 6.5.0
| npm/Yarn         | npm
| babel            | 7.x.x
| Operating System | macOS / Ubuntu

**Comment by mischnic** [comment]
What you wanted to write:
```diff
diff --git a/main/sidenav.js b/main/sidenav.js
index 1597966..b6cfa47 100644
--- a/main/sidenav.js
+++ b/main/sidenav.js
@@ -1,6 +1,6 @@
 import React from 'react';

-import {Layout, Menu} from 'antd';
+import {Layout, Menu, Slider} from 'antd';
 import 'antd/lib/layout/style/css';
 import 'antd/lib/menu/style/css';

@@ -21,10 +21,9 @@ class SideNav extends React.Component {
     }

     render() {
-        const { Sider } = Layout;
         const pathname = 'dashboard';
         return (
-            <Sider className="side-nav" breakpoint="lg"
+            <Slider className="side-nav" breakpoint="lg"
                 collapsible collapsed={this.state.collapsed}
                 onCollapse={this.onCollapse} >
                 <Link to={{ pathname: '/'}}>
@@ -41,7 +40,7 @@ class SideNav extends React.Component {
                         </Link>
                     </Menu.Item>
                 </Menu>
-            </Sider>
+            </Slider>
         );
     }
```

**Comment by mischnic** [comment]
Somehow, the `sideEffects` aren't processed correctly (`node_modules/test/es/layout/style` would contains js, less and css files). Removing the sideEffects key from package.json resolves the issue (

Minimal reproduction:
```js
// index.js
import Layout from "test";

const { Sider } = Layout;
console.log(Layout); // ok
console.log(Sider); // undefined
```

```js
// node_modules/test/package.json:
{
  "module": "es/index.js",
  "sideEffects": [
    "es/**/style/*"
  ]
}

// node_modules/test/es/index.js:
export default from './layout';


// node_modules/test/es/layout/index.js:
import Layout from './layout';
Layout.Sider = function Sider(){
  return "Sider";
}
export default Layout;


// node_modules/test/es/layout/layout.js:
export default function Layout(){
  return "Layout";
}
```

**Comment by mturki** [comment]
I have the exact same issue. Any workaround to fix it? I'm using the default react implementation of code splitting with `React.lazy` and `Suspense`, and like @kpentchev , the build with `--experimental-scope-hoisting` works properly, but fail at runtime. Note that a build without the scope hoisting option works properly at runtime.

### errors :

> Uncaught Error: React is running in production mode, but dead code elimination has not been applied. Read how to correctly configure React for production: https://fb.me/react-perf-use-the-production-build
    at <anonymous>:1:204
(...)

> Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at $jF7N$var$ba (http://localhost:8080/(...).838a5eca.js:7264:11)
(...)

> Uncaught (in promise) Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at $jF7N$var$ba (http://localhost:8080/(...).838a5eca.js:7264:11)
(...)

### Implementation
```javascript
const OtherComponent = React.lazy(() => import('./OtherComponent'));

function MyComponent() {
  return (
    <div>
      <Suspense fallback={<div>Loading...</div>}>
        <OtherComponent />
      </Suspense>
    </div>
  );
}
```

**Comment by Cristy94** [comment]
Any updates on this? `--experimental-scope-hoisting` doesn't work as it generates a lot of issues at runtime (UI looks different, some errors in the console), but without it the React dead-code error appears.

**Comment by mischnic** [comment]
It's vastly improved in Parcel 2.
But even with `parcel build index.html`, React shouldn't warn.
