### ISSUE TITLE
Parcel with Rust fails to write to cache if paths have spaces

### ISSUE THREAD

**Issue by iamcodemaker** [parcel-bundler/parcel#2521]
# 🐛 bug report

When building a rust project, if there are spaces in the path parcel fails with the following error where the path was `/path/with spaces in it/`. Note: this is not a fatal error, it just logs to the console. Everything else still seems to work.

```sh
✨  Built in 1.72s.
🚨  Error writing to cache: ENOENT: no such file or directory, stat '/path/with\'
```

## 🔦 Context

To reproduce:

1. get the [rust parcel template ](https://github.com/rustwasm/rust-parcel-template)
1. place it in a path with spaces in it
1. run `npm run start` or `npm run build`

## 🤔 Expected Behavior

Parcel should properly build a bundle.

## 😯 Current Behavior

Parcel complains about writing to the cache with the error above.

## 💁 Possible Solution

Properly handle paths with spaces (and special characters) in them.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0 |
| Node             | 8.14.0 |
| npm         |  6.5.0 |
| Operating System | macOS 10.13.6 |

**Comment by mischnic** [comment]
This is a bug within https://github.com/catsigma/parcel-plugin-wasm.rs. Open an issue there, this should help them fix it:

Inside `WASMbindgenAsset.collectDependencies`, this line doesn't handle whitespaces correctly:
```js
let deps = contents.trim().split(':')[1].split(' ').filter(x => x)`
```
