### ISSUE TITLE
A question about attribute of 'src'

### ISSUE THREAD

**Issue by ftv031** [parcel-bundler/parcel#2528]
首先感谢Parcel的开发者们，Parcel真的非常好用
如果我在页面当中放置一个空的<Img src="">标签，并且这个src的属性是在页面初始化的时候通过网络请求获取到的，那么当src属性为空的时候进行打包，就会提示”The "path" argument must be of type string“

google translate to Eng:
First of all, thanks to the developers of Parcel, Parcel is really easy to use.
If I set an empty <Img src=""> element on the page, The src attribute is obtained through the network request when the page is initialized. and then When I am packing,Parcel will report an error：”The "path" argument must be of type string“

**Comment by DeMoorJasper** [comment]
Could you provide a minimal reproduction? Or some example code?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ftv031** [comment]
@DeMoorJasper  For example:
- HTML
```html
<img src=''  id='showImg'>
```
- JS
```js
//my network request
axios.get('url')
.then(res=>{
  document.getElementById('showImg').setAttribute('src','http://.....');
})
```
If src attribute in  html is exist but null,when i run 'Parcel build' and Parcel will throw a error 'The "path" argument must be of type string'

| Software | Version(s)
| ------ | ------ |
 Parcel | 1.11.0| 
| node |  9.10.0| 
| npm/yarn | 1.9.4 | 
| Operating System | windows 10 |

**Comment by DeMoorJasper** [comment]
Bugfix merged to master
