### ISSUE TITLE
Nim asset appropriate for Parcel Core?

### ISSUE THREAD

**Issue by nepeckman** [parcel-bundler/parcel#2529]
# 🙋 feature request

[Nim](https://nim-lang.org/) is an interesting language that targets both C family languages, as well as JS. I've been writing some front end code in Nim, and it got to the point where I wanted a bundler. Parcel is my favorite web bundler, so I whipped up an Asset for Nim! The Nim community is on the small side, so I wasn't sure if this asset would be appropriate for core Parcel. If not, no worries, I'll publish it as a plugin. If so, I can clean up the code and go through a PR!

## 🤔 Expected Behavior

* Compile Nim code to JS so Parcel can bundle it

## 💁 Possible Solution

My current implementation invokes the Nim compiler, then reads the compiled file.

**Comment by DeMoorJasper** [comment]
If it’s a small community it’s probably best to create a plugin.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
