### ISSUE TITLE
[ReasonML] How to make `*.js` file to the `lib/js` folder

### ISSUE THREAD

**Issue by uinz** [parcel-bundler/parcel#2541]
# ❔ Question

How to make `*.js` file to the `lib/js` folder

```json5
// bsconfig.json
{
  "name": "parcel-reason-react",
  "reason": { "react-jsx": 2 },
  "sources": [{ "dir": "src", "subdirs": true }],
  "package-specs": [
    {
      "module": "commonjs",
      "in-source": false // I change here
    }
  ],
  "suffix": ".bs.js",
  "namespace": true,
  "bs-dependencies": ["reason-react"],
  "refmt": 3
}
```

```sh
# error info
🚨  $HOME/task_list/src/Index.re: ENOENT: no such file or directory, open '$HOME/task_list/src/Index.bs.js'
Error: ENOENT: no such file or directory, open '$HOME/task_list/src/Index.bs.js'
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel                  | 1.11.0
| Node                   | 8.12.0
| Yarn                     | 1.12.3
| bs-platform        | 4.0.18
| bsb-js                 | 1.1.7
|reason-react       | 0.5.3
| Operating System | MacOS

**Comment by Greg-Johns** [comment]
You need to change the script source in Index.html file that Parcel points to
