### ISSUE TITLE
Parcel and RequireJS

### ISSUE THREAD

**Issue by bchoddny** [parcel-bundler/parcel#2542]
# ❔ Question

I'm working to migrate my project setup from grunt to webpack or parcel.  Just wanted to experiment parcel since it claims zero configuration. My project does AMD way of loading modules using requirejs. Just would like to know if any initial setup required for parcel to load modules AMD way with requirejs.

When I run parcel, when it encounters require() in entry point js file, I see it is thrown an error. Wondering how to make this to use requirejs require api instead of parcelRequire?

main.d7e180e4.js:39 Uncaught Error: Cannot find module 'moment,jquery,knockout,postal'
    at newRequire (main.d7e180e4.js:39)
    at localRequire (main.d7e180e4.js:55)
    at Object.parcelRequire.V3RS10N/js/main.js (main.js:83)
    at newRequire (main.d7e180e4.js:49)
    at main.d7e180e4.js:81
    at main.d7e180e4.js:107
newRequire @ main.d7e180e4.js:39
localRequire @ main.d7e180e4.js:55
parcelRequire.V3RS10N/js/main.js @ main.js:83
newRequire @main.d7e180e4.js:49
(anonymous) @ main.d7e180e4.js:81
(anonymous) @ main.d7e180e4.js:107

## 💻
require([
    'moment',
    'jquery',
    'knockout',
    'postal',
], function(moment, $, ko, postal) {

});

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             |11.1.0
| npm/Yarn         | yarn
| Operating System | mac

**Comment by icopp** [comment]
Parcel uses the CommonJS/ES6 style where separate `require` statements are needed for each import, so for the quick and dirty way to make it work you'll need to change that to something like...

```js
(function(moment, $, ko, postal) {
  // ...
})(require('moment'), require('jquery'), require('knockout'), require('postal'));
```

Longer term you'll want to change that to ES6 imports, which allow better code splitting and compiler optimization:

```js
import moment from 'moment';
import $ from 'jquery';
import ko from 'knockout';
import postal from 'postal';

// ...
```

**Comment by mischnic** [comment]
@bchoddny Was your question answered?

**Comment by bchoddny** [comment]
Yes, Thanks.



________________________________
