### ISSUE TITLE
Named outfiles `-o myFilename` for multiple entrypoints not working as expected

### ISSUE THREAD

**Issue by hdpinto** [parcel-bundler/parcel#2548]
# 🐛 bug report

Using multiple entry files, I'm trying to get custom file names for each entry. As hard as I try, this seems to now work. One of the out files gets renames, but the other always seems to keep the original filename.

I ran into this issue using `watch` so the `build` commands are just me trying to get this working as expected.

## 🎛 Configuration (.babelrc, package.json, cli command)

```bash
user@MacbookPro js (master) $ npx parcel build src/index.jsx -d ../dist -o bundle.js src/not_found.jsx -d ../dist -o error.js
✨  Built in 256ms.

../dist/error.map        217.98 KB    69ms
../dist/not_found.map    217.31 KB    68ms
../dist/error.js          63.65 KB    69ms
../dist/not_found.js      63.42 KB    69ms

user@MacbookPro js (master) $ npx parcel build src/index.jsx -d ../dist src/not_found.jsx -d ../dist
✨  Built in 251ms.

../dist/index.map        217.97 KB    66ms
../dist/not_found.map    217.31 KB    66ms
../dist/index.js          63.65 KB    67ms
../dist/not_found.js      63.42 KB    67ms

user@MacbookPro js (master) $ npx parcel build src/index.jsx -d ../dist src/not_found.jsx -d ../dist -o bundle.js error.js
✨  Built in 362ms.

../dist/bundle.map       217.97 KB    152ms
../dist/not_found.map    217.31 KB    151ms
../dist/bundle.js         63.65 KB     88ms
../dist/not_found.js      63.42 KB     89ms

user@MacbookPro js (master) $ npx parcel build src/index.jsx -d ../dist src/not_found.jsx -d ../dist -o error.js
✨  Built in 260ms.

../dist/error.map        217.98 KB    73ms
../dist/not_found.map    217.31 KB    74ms
../dist/error.js          63.65 KB    70ms
../dist/not_found.js      63.42 KB    70ms

user@MacbookPro js (master) $ npx parcel build src/index.jsx -d ../dist src/not_found.jsx -d ../dist -o bundle.js
✨  Built in 278ms.

../dist/bundle.map       217.97 KB    69ms
../dist/not_found.map    217.31 KB    69ms
../dist/bundle.js         63.65 KB    84ms
../dist/not_found.js      63.42 KB    84ms

user@MacbookPro js (master) $ npx parcel build src/index.jsx -d ../dist src/not_found.jsx -d ../dist -o bundle.js -o error.js
✨  Built in 281ms.

../dist/error.map        217.98 KB    75ms
../dist/not_found.map    217.31 KB    77ms
../dist/error.js          63.65 KB    83ms
../dist/not_found.js      63.42 KB    83ms

user@MacbookPro js (master) $ npx parcel build src/index.jsx -d ../dist src/not_found.jsx -d ../dist -o bundle.js
✨  Built in 255ms.

../dist/bundle.map       217.97 KB    67ms
../dist/not_found.map    217.31 KB    67ms
../dist/bundle.js         63.65 KB    69ms
../dist/not_found.js      63.42 KB    68ms
```

## 🤔 Expected Behavior

I'm expecting something like this:

```bash
$ npx parcel build src/index.jsx -d ../dist -o bundle.js src/not_found.jsx -d ../dist -o error.js
✨  Built in 281ms.

../dist/bundle.map      217.97 KB    67ms
../dist/error.map       217.31 KB    67ms
../dist/bundle.js        63.65 KB    69ms
../dist/error.js         63.42 KB    68ms
```

## 😯 Current Behavior

See above for a series of examples.

## 💁 Possible Solution

The command is getting kinda hairy, I know the simple solution would be to just name each entry point what I want the exit to be, but then every page I have would have some weird name like `bundle.home.jsx` which is not ideal. Specifying a entry.json file might help here (but would defeat zero-config...), but I'd take having something like this command:
`npx parcel build src/index.jsx -d ../dist -o bundle.js src/not_found.jsx -d ../dist -o error.js
`

## 🔦 Context

I have a Preact app that has multiple pages that share code. it's not a SPA with a router, so each page has its own separately named `bundle.page.js` file. We decided to do this because our users don't navigate our site but instead get linked to it, so each page is completely self-contained and doesn't need to be aware of any other page, even though they might share JSX templates for UI components. The examples above only show two pages but we have more entry points.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0 |
| Node             | 8.11.3 |
| npm/Yarn         | 5.6.0 |
| Operating System | macOS 10.14.2 |

**Comment by mischnic** [comment]
Well, you could rename `index.jsx` to `bundle.jsx` and `not_found.jsx` to `error.jsx`.
Specifying an output filename for every entrypoint is not possible.

You *could* use the API to rename the files after bundling (something along these lines):
```js
const bundler = new Bundler(...);
bundler.on('bundled', bundle => {
	for(let b of bundle.childBundles.values()){
		console.log(b.name) // should print every output bundle name
		console.log(b.entryAsset.name) // should print every "source" name
	}
});
bundler.bundle();
```
https://parceljs.org/api.html

**Comment by hdpinto** [comment]
> Well, you could rename index.jsx to bundle.jsx and not_found.jsx to error.jsx.

I did mention this as a non-ideal solution. In a multiple-entry situation, providing the ability to rename one of the outfiles but not the others is unintuitive, and as you can see above which file gets renamed is not consistent depending on where I place the `-o` flag. That's why I feel this falls squarely in `bug` territory.

If this is a not supported feature, make it officially not supported (and documented) instead of the weirdness I saw above, though I still feel it should be possible to rename outfiles.
