### ISSUE TITLE
how to introduce a module as globals variable to all other sub modules

### ISSUE THREAD

**Issue by Mayank694** [parcel-bundler/parcel#2554]
i am using parcel to bundle my js, before with webpack it provides a plugin using that we can introduce some variable which will be available in all other module as a global.
Example: Like i need jquery for other modules and for that i have to import jquery in all of them instead if there is a way the jquery variable would be available as a global to all my modules.

**Comment by mischnic** [comment]
> Like i need jquery for other modules 

By module, do you mean bundle or an actual module?
If you have only one bundle, then you need to import jQuery in every module
```js
const jQuery = require("jquery");
````

**Comment by Mayank694** [comment]
i meant moudle but for further clarification please open and see the link below
https://stackoverflow.com/questions/37656592/define-global-variable-with-webpack

**Comment by danmarshall** [comment]
See the `--global` command line option: https://parceljs.org/cli.html#expose-modules-as-umd

**Comment by Mayank694** [comment]
@danmarshall  how do i import jquery and pass that as UMD.

**Comment by Mayank694** [comment]
thanks @danmarshall for the help

**Comment by danielo515** [comment]
That do not works for me. My global variable is named global. How can I  access it ?

**Comment by kedzior-io** [comment]
@danielo515 
See this: https://github.com/kedzior-io/parcel-global-var-typescript-vue-test (ignore vue part)

**Comment by goodleby** [comment]
> Loading Jquery from CDN and injecting a global variable `$`

Is it possible to load jQuery not from CDN? I need to use it from local file ./assets/js/jquery.min.js
Thanks in advance! :)

**Comment by radikaledward1** [comment]
> See the `--global` command line option: https://parceljs.org/cli.html#expose-modules-as-umd

This command is not available any more in new parcel versions.

**Comment by oshliaer** [comment]
As @radikaledward1 said there is no any replacement https://parceljs.org/getting-started/migration/#--global

**Comment by kedzior-io** [comment]
@radikaledward1 , @contributorpw  I'm going to have to upgrade one of the sites soon, will see what's the alternative.

**Comment by danmarshall** [comment]
Related: #766 #6437

**Comment by timofriedlberlin** [comment]
This is how i solved my issue not having jQuery ($) and lodash (_) on global level:

```js
import jQuery from '../../bower_components/jquery/dist/jquery'
import lodash from '../../bower_components/lodash/dist/lodash'

$ = jQuery = window.jQuery = window.$ = jQuery
_ = window._ = lodash
```

Just make sure this is loaded at first before all your other modules load.
