### ISSUE TITLE
/bin/sh: lscpu: not found on Alpine Linux

### ISSUE THREAD

**Issue by abramenal** [parcel-bundler/parcel#2555]
# 🙋 Feature Request

In order to make the tool more user-friendly it is nice to have separation between:
- error messages, that considerably affect how the tool works (like functionality, performance, etc.);
- warning messages, that just states something that might be useful for someone.

## 😯 Current Behavior

A red-colored message appears in console which states:
`/bin/sh: lscpu: not found`

From user's perspective the message text and color is confusing and forces to investigate it's cause - check other platforms, understand whether there is a fallback for this functionality, ensure the user's application build is made without any issues.

## 💁 Possible Solution

As as user I would be happy to see that it's just a warning that brings some non-critical information.
This may be done by changing the message color to something less shocking (e.g. yellow) and changing the message text to something like:
`/bin/sh: lscpu: not found. "os.cpus" fallback is used instead`

## 🔦 Context

Got this problem while building UI application with docker using Alpine image, e.g.
`FROM node:11-alpine`

## 💻 Examples

Decided to ask you again since there was an opened issue before (#2031) and it is yet not solved.

PS not sure if that's really a feature request or a bug

**Comment by mischnic** [comment]
I'm not sure where this message is coming from,
https://github.com/parcel-bundler/parcel/blob/6cbf2a65cdcd66af135ff9eca2a3799bde9f8a5b/packages/core/workers/src/cpuCount.js#L3-L11

physical-cpu-count source:
https://unpkg.com/physical-cpu-count@2.0.0/index.js

**Comment by polarathene** [comment]
@mischnic `/bin/sh: lscpu: not found` will be the shells output when calling lscpu and it not being found, it's not an error omitted by any JS code specifically.

The catch(err) should probably trigger?(add a console.log() to verify?), if so a helpful message that a fallback is being used instead could be output there.

@abramenal I've seen this issue with Alpine image projects elsewhere(I'm not presently using Parcel myself, just saw this issue while looking into Parcel), afaik it's nothing to worry about as it uses a fallback, but you could also just install lscpu(it's in the [util-linux](https://pkgs.alpinelinux.org/contents?file=lscpu&path=&name=util-linux&branch=v3.9&repo=main&arch=x86) package) into your alpine image if you want to avoid that error. 

Do note this isn't a bug specific to Parcel, I don't think they can hide/change that line you're getting as it's a result of the package they use calling the command. They could print a more helpful message afterwards afaik to handle this better.

**Comment by louh** [comment]
I agree a warning would be way more user friendly.

Another workaround that hasn't been mentioned here but I'll add it for reference: if you know what the cpu count is on your machine you can set the environment variable `PARCEL_WORKERS` to that amount or just `PARCEL_WORKERS=1` as a safe option. If this is set, then Parcel doesn't try to detect the cpu count itself and it will never attempt to run `lscpu`. [Here it is in the docs.](https://github.com/parcel-bundler/parcel/blob/cbbbbbeae42e1d2ea7c8e72f303602771d5858da/CONTRIBUTING.md#environment-variables-command-line-arguments)

**Comment by cyrius** [comment]
`apk add util-linux` will add lscpu

**Comment by abramenal** [comment]
Any progress on that?

**Comment by DeMoorJasper** [comment]
@abramenal this is an issue with the physical cpu count package, I'll move it into the parcel monorepo and open a PR later today, so this error hopefully no longer occurs in Parcel 2.

**Comment by abramenal** [comment]
@DeMoorJasper cool!
Let me know if I can help with anything

**Comment by DeMoorJasper** [comment]
Opened the PR, it uses `nproc` first and after that tries `lscpu` so it should work on alpine and in case it fails it does it silently so it does not alarm anyone as it would have no effect, besides maybe a small performance decrease.
