### ISSUE TITLE
Third Party library import failed

### ISSUE THREAD

**Issue by ArrayZoneYour** [parcel-bundler/parcel#2560]
# 🐛 bug report

When I use parcel to bundle my project with `react-model`, It works on [CodeSandBox](https://codesandbox.io/s/km1mn062o5), but crash on local (I test on my Linux node v8.x and macOS node v10.x)

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`
```json
{
  "name": "parcel-react-model-template",
  "version": "1.0.0",
  "description": "",
  "main": "index.html",
  "scripts": {
    "start": "parcel index.html --open",
    "build": "parcel build index.html"
  },
  "dependencies": {
    "react": "16.8.0-alpha.1",
    "react-dom": "16.8.0-alpha.1",
    "react-model": "2.0.11",
    "typescript": "3.2.4"
  },
  "devDependencies": {
    "@types/react": "16.7.20",
    "@types/react-dom": "16.0.11",
    "parcel-bundler": "^1.6.1"
  },
  "keywords": []
}

```

## 🤔 Expected Behavior

npm start with no import error

## 😯 Current Behavior

```
Uncaught TypeError: react_model_1.Model is not a function
    at Object.parcelRequire.model/index.ts.react-model
```

## 💁 Possible Solution

ES6/esnext module support
Now I remove the module field in `react-model@2.0.12` package.json to solve the issue.

## 🔦 Context

`node_modules/react-model/package.json`
```
// ...
"license": "MIT",
  "main": "./dist/react-model.js",
  "module": "./dist/react-model",
  "name": "react-model",
// ...
```
When I Change it to

```
"license": "MIT",
  "main": "./dist/react-model.js",
  "module": "./dist/react-model.js",
  "name": "react-model",
```
Parcel can work well, But the file `./dist/react-model` is a valid ES module under webpack. And this solution will be broken under webpack. What's wrong, What should I do ?

## 💻 Code Sample

[CodeSandBox](https://codesandbox.io/s/km1mn062o5)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v1.6.1 / v1.11.0 |
| Node             | v8.x / v10.x |
| npm/Yarn         | -- |
| Operating System | Linux / macOS |

**Comment by talentlessguy** [comment]
Maybe smth wrong with react-module?

**Comment by mischnic** [comment]
I can't reproduce this (anymore). react-model doesn't (and didn't? https://unpkg.com/react-model@2.0.12/package.json) have a module property in it's package.json.
Adding the line seems to make no difference. Are you still having issues?

**Comment by ArrayZoneYour** [comment]
> I can't reproduce this (anymore). react-model doesn't (and didn't? https://unpkg.com/react-model@2.0.12/package.json) have a module property in it's package.json.
> Adding the line seems to make no difference. Are you still having issues?

**I remove the module field in react-model@2.0.12 so you can't reproduce it.**

You can reproduce this in **react-model@2.0.11**
the same as package.json above.

**Comment by mischnic** [comment]
@ArrayZoneYour You can't have a javascript file without a file extension. Renaming `dist/react-model` to `react-model.esm.js` (and changing package.json) fixes it.
