### ISSUE TITLE
⚠️  Unexpected token }   error node_modules/json-parser/index.js:121:9

### ISSUE THREAD

**Issue by QuantumInformation** [parcel-bundler/parcel#2562]
I tried to convert a game over to parcel from webpack, but I get this error.

The code parcel command is here: https://github.com/QuantumInformation/youtube-space-invaders/blob/development/package.json#L28

And the error:
```
⚠️ Unexpected token }
    at unexpected (/Users/nikos/WebstormProjects/youtube-space-invaders2/node_modules/json-parser/index.js:121:9)
    at expect 
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.9.7
| Node             | 8
| npm/Yarn         | npm
| Operating System | high seirra

I tried deleting node_modules and updating.

![image](https://user-images.githubusercontent.com/216566/51493305-3828e100-1db5-11e9-8ecb-c2f259eba468.png)

**Comment by mischnic** [comment]
```diff
diff --git a/tsconfig.json b/tsconfig.json
index 6042b6b..7a0c066 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -3,7 +3,7 @@
     "target": "es2015",
     "types": [
       "node"
-    ],
+    ]
   },
   "include": [
     "./src/**/*.ts"
```

**Comment by QuantumInformation** [comment]
Dang, how on earth did you spot that from the debug error?

👏

**Comment by QuantumInformation** [comment]
Any ideas why I can't export an enum now? 

![image](https://user-images.githubusercontent.com/216566/51527935-e1172080-1e35-11e9-814b-4819199c883e.png)

**Comment by mischnic** [comment]
> Dang, how on earth did you spot that from the debug error?

😄 "config-loader" in the stack trace and https://github.com/math2001/JSONComma fixed it when my Cmd+S reflex kicked in.

> Any ideas why I can't export an enum now?

Somehow caused by `parcel-plugin-typescript`, @fathyb ?

**Comment by QuantumInformation** [comment]
@mischnic should i open a new issue?

**Comment by QuantumInformation** [comment]
The problem has fixed itself on a reinstall of nm
