### ISSUE TITLE
env variables do not work with reason

### ISSUE THREAD

**Issue by idkjs** [parcel-bundler/parcel#2564]
# 🐛 bug report

## 🎛 Configuration
This reproduction uses the [https://github.com/parcel-bundler/examples/tree/master/reason-react] demo repo.

No babel configuration
## 🤔 Expected Behavior

`.env` variables should be read.

## 😯 Current Behavior

`.env` variables are not being read from reasonml code unless you [Embed Raw JavaScript](https://bucklescript.github.io/docs/en/embed-raw-javascript#docsNav)

```js
let dbHost = [%raw {|
  process.env.DB_HOST
|}];

Js.log2("dbHost",dbHost);

/* this doesnt */
Js.log2("DB_HOST", Utils.Env.get("DB_PASS"));
Js.log2("DB_USER", Utils.Env.get("DB_USER"));
```

output:
```shell
dbHost localhost 
DB_HOST 
DB_USER 
```
![screen shot 2019-01-22 at 1 43 33 pm](https://user-images.githubusercontent.com/2370391/51536408-c780d380-1e4b-11e9-8b0a-432debaff786.png)

## 💁 Possible Solution

temporary? solution is to embed raw javascript
```js
let dbHost = [%raw {|
  process.env.DB_HOST
|}];
```

## 🔦 Context

Using built dotenv functionality with reason doesnt work. 

## 💻 Code Sample
https://github.com/idkjs/parcel-reason-react-env-demo

Code call process env. 

https://github.com/idkjs/parcel-reason-react-env-demo/blob/c918557885d85a673ad54e90299ff86386e9baf2/src/Utils.re#L4-L8

```js
module Env = {
  /* [@bs.module "dotenv"] external config : unit => unit = ""; */
  [@bs.val] [@bs.scope "process"] external env : Js.Dict.t(string) = "";
  let get = key => key |> Js.Dict.get(env) |> Js.Option.getWithDefault("");
};
```

## 🌍 Your Environment

ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G3025
yarn version: 1.12.3
node version: v10.8.0

**Comment by mischnic** [comment]
>If I remember well env variables are not working properly when using destructuring assignment in JavaScript, like:

-> #2191
Only destructuring into multiple variables at once is an issue
