### ISSUE TITLE
Detect what file triggered bundling

### ISSUE THREAD

**Issue by samrith-s** [parcel-bundler/parcel#2565]
# ❔ Question

Is it possible to detect what file triggered the bundling, when the `bundled` event is fired?

## 🔦 Context

I am running some post-processing on the generated HTML file. My process injects some scripts into the HTML. It also sets some attributes to some HTML for the inject scripts to detect and work. This works properly when I change HTML or JS assets. But if I change any stylesheet, HMR causes my post-process to run again, which injects the same script multiple times.

It would be nice is the `opt` object which is received on bundle end, can contain a key which tells me if it was triggered due to HMR. Or if there is already some way to detect it, would be awesome!

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0

**Comment by DeMoorJasper** [comment]
You could try with `--log-level 4` or `--log-level 5` that should show more info than the default logging mode.

**Comment by samrith-s** [comment]
@DeMoorJasper I was hoping there is something that’s passed on `buildStart` or `buildEnd` which will tell me that it’s an HTML change which triggered the build.

**Comment by DeMoorJasper** [comment]
Ow you're using the API, not sure how to detect that

**Comment by samrith-s** [comment]
I’ve hacked it a bit and got my way around it. What I’ve figured is that when the HTML is regenerated, all of my injects get wiped out. So I read that HTML and check it it has an attribute. If it doesn’t, I run my post proves. Otherwise, I don’t. If I did run it, I set that attribute and write back to that file. 

Not the best of ways, but it works for my purpose!

**Comment by mischnic** [comment]
I think the original approach was fragile already. Parcel itself should handle invalidation and abstract that away from plugins (a better approach for this, at least in Parcel 2)
