### ISSUE TITLE
Do not include the parcelRequire helper if not necessary

### ISSUE THREAD

**Issue by kirly-af** [parcel-bundler/parcel#2566]
# ❔ Question

Is it possible to avoid the addition of the parcelRequire helper in the case of a JS bundle which does not use `require` or any sort of module feature in the target script?

## 🔦 Context

I pass a simple script to parcel which does not use any require or import and I'd like to reduce the overhead produced by parcel.

## 🌍 Your Environment

| Software      | Version(s) |
| ---------------- | ---------- |
| Parcel          |1.11.0
| Node            |8.11.3
| Yarn             | 1.13.0
| Operating System |

**Comment by mischnic** [comment]
(This is quite hard to implement in the current pipeline)

**Comment by jiraiya972** [comment]
related to #2451

**Comment by kirly-af** [comment]
@mischnic As seen in #2451, the real problem that I have is the "Mismatched anonymous define()" error. Would it be that difficult to handle? What's your take on this @devongovett?

**Comment by jhpratt** [comment]
@mischnic How reliable is that flag? It certainly looks to work on trivial cases.

**Comment by mischnic** [comment]
> How reliable is that flag? It certainly looks to work on trivial cases.

It even work in most complex cases 😄. I'd say it's quite reliable now, there are only some edge cases left. Please try it and open an issue if you find one!

**Comment by kirly-af** [comment]
@mischnic As the flag is "experimental", any idea when this should be ready for production?

**Comment by jhpratt** [comment]
@devongovett Should this really be closed? An experimental flag is not the same as being completed.

**Comment by soophie** [comment]
The flag didn't work for me. For test purposes I only have one script file with a `console.log()` included at the end of my HTML file. So there is definitely no reason for `parcelRequire()` here.

This is my build task: 
```
"build": "parcel build index.html --out-dir build --no-minify --no-source-maps --experimental-scope-hoisting",
```

**Comment by JakubKoralewski** [comment]
If someone could explain to me, if I have a **single** js file - why do I need to require anything inside the js file (parcelRequire) if it's all inside that file? i.e. what is parcelRequire actually for?

**Comment by mischnic** [comment]
> why do I need

It isn't needed, but the current approach is: take the wrapper and insert all JS modules. The unfortunate side-effect of this simplification is that a single JS module also has the wrapper code.

**Comment by kaushik-evani** [comment]
@jhpratt I agree. Can we keep this open?

**Comment by mischnic** [comment]
For Parcel 2, scope hoisting (which has no such wrapper) enabled by default in production builds. So I would say this is already somewhat fixed.
