### ISSUE TITLE
How can I try Parcel 2?

### ISSUE THREAD

**Issue by brillout** [parcel-bundler/parcel#2567]
I'm super interested in Parcel 2's multi-target feature which enables isomorphic JS and SSR.

I'd love to give Parcel 2 a try and use it for Reframe (https://github.com/reframejs/reframe).

How can I use Parcel 2 today? I'm fine with rough edges.

Parcel pushes the boundary of what is possible without any configuration. This has an immense impact. We need more simplicity in web dev.

**Comment by DeMoorJasper** [comment]
Parcel 2 is not ready yet. You can follow the Alpha 1 milestone here: https://github.com/parcel-bundler/parcel/milestone/5

This might also be interesting: https://isparcel2readyyet.com/

**Comment by brillout** [comment]
I'm aware of these links. I was wondering though if there is a way to try parcel 2 earlier? Seems like it will take a while before the alpha is done. Or, is there any ETA?

Building a framework such as Reframe on top of a bundler is no trivial task and gathering feedback early from web frameworks could benefit parcel and the whole community.

I'm very much looking forward to integrate Parcel into Reframe.

**Comment by DeMoorJasper** [comment]
There is an issue discussing the api for tooling to use it. Should be fairly a fairly trivial task to integrate parcel in tooling. That’s one of the goals of Parcel 2.

Feel free to use the `v2-work-so-far` branch but that is changing constantly and only supports js transforms atm so don’t really see the point in integrating parcel into tooling before there is a somewhat complete alpha.

Parcel 2 alpha 1 isn’t that far out as you can see by the progress in the link I sent earlier

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by brillout** [comment]
Ok thanks. I'm excited as well.
