### ISSUE TITLE
react-hot-loader not working with typescript

### ISSUE THREAD

**Issue by llamadeus** [parcel-bundler/parcel#2569]
# 🐛 bug report
When using typescript and react-hot-loader, component handlers are not being patched correctly after hot reloading.

Please have a look at https://github.com/llamadeus/parcel-typescript-react-hot-loader for a minimal setup.

## 🎛 Configuration (.babelrc, package.json, cli command)
`.babelrc`
```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    "react-hot-loader/babel",
    "@babel/plugin-proposal-class-properties"
  ]
}
```
`package.json`
```
{
  "name": "parcel-react-hot-loader-test",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "start": "parcel src/index.html"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0-0",
    "@babel/plugin-proposal-class-properties": "^7.3.0",
    "@babel/preset-react": "^7.0.0",
    "parcel-bundler": "^1.11.0",
    "typescript": "^3.2.4"
  },
  "dependencies": {
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "react-hot-loader": "^4.6.3"
  }
}
```

## 🤔 Expected Behavior

When I hit the `Press me` button for the first time, it should properly `alert('test');`. Then, after commenting line 9 in `src/Content.tsx` and waiting for HMR to update the component, another click on the button should **NOT** trigger an alert.

## 😯 Current Behavior

The second button press actually **DOES** trigger another alert.

## 💁 Possible Solution

No idea.

## 🔦 Context

Just any typescript application using hot module replacement.

## 💻 Code Sample

https://github.com/llamadeus/parcel-typescript-react-hot-loader

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0 |
| Node             | 8.12.0 |
| npm/Yarn         | 6.4.1/1.12.3 |
| Operating System | macOS 10.14.2 |

**Comment by llamadeus** [comment]
The same problem appears, when using ES6 and class decorators.

**Comment by llamadeus** [comment]
As it turns out, the bug only exists for arrow functions in the class. Replacing the arrow function with a normal class method and binding `this` manually works. However, I prefer arrow functions, so I'd like to be able to avoid that.

**Comment by rodoabad** [comment]
Can confirm! Thanks, @llamadeus.

**Comment by rodoabad** [comment]
Looks like I'll just do a `codemod` later.

**Comment by llamadeus** [comment]
Any news on this? Otherwise, I'd appreciate any tips on where and how to fix this problem.
