### ISSUE TITLE
ts type alias fails with Parcel but works with tsc

### ISSUE THREAD

**Issue by mverleg** [parcel-bundler/parcel#2571]
# 🐛 bug report

Compiling the MWE (involving `type`) fails with Parcel

## :paintbrush: HTML

	<!DOCTYPE html>
	<html lang="en">
	<head><meta charset="UTF-8"></head>
	<body>
	<script src="core.ts"></script>
	</body>
	</html>

## :coffee: TS

    type Cb = () => void;
    let q: Cb = () => { console.log('hello') };

## 🎛 Configuration (.babelrc, package.json, cli command)

    "parcel-bundler": "^1.11.0",
    "parcel-plugin-typescript": "^1.0.0",
    "sass": "^1.15.3",
    "typescript": "^3.2.2",
    "minimatch": "3.0.4"

## 🤔 Expected Behavior

The example compiles fine, the way it does when using `tsc core.ts`

## 😯 Current Behavior

    $ parcel index.html
    🚨  /home/mark/benjamin-jsclient/MWE/core.ts:2:9: Unexpected token, expected ";" (2:9)
      1 | 
    > 2 |     type Cb = () => void;
        |         ^
      3 |     let q: Cb = () => { console.log('hello') };

**Comment by mischnic** [comment]
Is this a message from parcel-plugin-typescript or parcel itself?

**Comment by mverleg** [comment]
Good question. I didn't know how to tell, so I removed `node_modules` and reinstalled without plugin. Seems it works now! So I guess this issue is invalid here, sorry.

**Comment by mischnic** [comment]
> reinstalled without plugin. 

Just a heads up: this will ignore any type information. If it works without the plugin, please file a issue over there.
