### ISSUE TITLE
ParcelBundler does not expose --bundle-node-modules as an option

### ISSUE THREAD

**Issue by r3fio** [parcel-bundler/parcel#2573]
# 🐛 bug report

It's currently not possible to set --bundle-node-modules as an option in Parcel Bundler scripts.

## 🤔 Expected Behavior

This should work as a ParcelOptions property and include all modules in the output as expected:

```js
{
...
  target: "node"
  bundleNodeModules: true 
...
}
```

## 😯 Current Behavior

Currently it does nothing. I briefly checked the ParcelBundler d.ts file and it's definitely not there.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | v11.6.0
| npm/Yarn         |  1.13.0

**Comment by mischnic** [comment]
I don't know which typescript definitions file you're referring to, but in every case: it's missing in the documentation and `bundleNodeModules` should work as an option:

https://github.com/parcel-bundler/parcel/blob/bdc044acfad84ba25bdb6631fbd3dd955424a227/packages/core/parcel-bundler/src/Bundler.js#L119-L122

**Comment by r3fio** [comment]
Okay, seems like the typescript definitions difference is just an oddity on my end.

I just tested it again and it appears like it doesn't work if you set node as a target. In every other case it bundles everything correctly.

Can someone verify this?
