### ISSUE TITLE
Font blocked by CORS policy

### ISSUE THREAD

**Issue by Joci933** [parcel-bundler/parcel#2580]
# 🐛 bug report

Font blocked by CORS when it's served by another domain. (The site use one WordPress to serve another domain with domain mapping.) "Access to font at 'https://site1/wp-content/themes/site1theme/dist/HandTIMES.9ffc0444.woff' from origin 'https://site2' has been blocked by CORS policy:"
It's a bug in parcel, CORS is disseaper with another bundler.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "site1theme",
  "version": "6.0.0",
  "description": "site1descpription",
  "main": "index.js",
  "scripts": {
    "watch": "export WPTHEME=site1 && node ./node_modules/parcel-bundler/bin/cli.js ./assets/index.js",
    "build": "export WPTHEME=site1 && node ./node_modules/parcel-bundler/bin/cli.js build ./assets/index.js"
  },
  "repository": "",
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "babel-core": "^6.22.1",
    "babel-loader": "^6.2.10",
    "babel-preset-es2015": "^6.22.0",
    "css-loader": "^0.26.1",
    "isotope-layout": "^3.0.4",
    "masonry-layout": "^4.2.0",
    "node-sass": "^4.5.0",
    "sass-loader": "^5.0.1",
    "standard": "^9.0.0-beta.0"
  },
  "dependencies": {
    "bootstrap": "4.0.0-alpha.6",
    "font-awesome": "^4.7.0",
    "imports-loader": "^0.7.0",
    "jquery": "^3.3.1",
    "lity": "^2.3.1",
    "parcel-bundler": "^1.10.3",
    "popper.js": "^1.14.6",
    "sass": "^1.15.2",
    "swiper": "^4.4.6",
    "tether": "^1.4.0"
  }
}

```

## 🤔 Expected Behavior

Set  access-controls something like this:
```
Access-Control-Allow-Origin "*"
Access-Control-Allow-Headers "origin, x-requested-with, content-type"
 Access-Control-Allow-Methods "PUT, GET, POST, DELETE, OPTIONS"
```
## 😯 Current Behavior

Fonts blocked by CORS.

**Comment by Andrew-Dyachenko** [comment]
I found alternative solution.
Try to install necessary fonts localy.
It's not complete solution however you could faster proceed you developing.

![Без имени](https://user-images.githubusercontent.com/10127643/58370307-9275b200-7f0d-11e9-9b80-9ce3d5bb83ce.png)
