### ISSUE TITLE
Importing a .vue file from outside the project root destroys the package.json file

### ISSUE THREAD

**Issue by brian-c** [parcel-bundler/parcel#2585]
# 🐛 bug report

Importing a .vue file from outside the project root destroys the package.json file.

## 🎛 Configuration (.babelrc, package.json, cli command)

My main app is inside a directory called "project". A Vue component called "outside.vue" lives next to that directory.

- project/package.json
  ```json
  {
    "devDependencies": {
      "parcel-bundler": "^1.11.0"
    },
    "scripts": {
      "start": "parcel ./index.html"
    }
  }
  ```

- project/index.html
  ```html
  <!doctype html>
  <title>Bug</title>
  <script src="./main.js"></script>
  ```

- project/main.js
  ```js
  import outside from '../outside';
  ```

- outside.vue
  ```vue
  <script>
  export default {};
  </script>
  ```

## 🤔 Expected Behavior

After running `npm install` and `npm start`, the "outside" component should be available in the "main" module.

## 😯 Current Behavior

After running `npm install` and `npm start`, package.json is wiped out during the Parcel build:
```json
{}
```

and replaced with this when the build is complete:
```json
{
  "devDependencies": {
    "vue-template-compiler": "^2.5.22"
  }
}
```

The contents of node_modules also matches the new incorrect package.json.

## 🔦 Context

I've got an app with some components I'd like to split into independent projects. I should still be able to reference them by their relative paths.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | 11.6.0
| npm/Yarn         | npm 6.5.0
| Operating System | macOS Sierra 10.12.6

**Comment by alajfit** [comment]
I've noticed this with TypeScript files also, if you import a TypeScript file from outside the root dir the package.json is destroyed

**Comment by DeMoorJasper** [comment]
Why would you require a file outside of the root directory? This seems like a bad idea

**Comment by MaffooBristol** [comment]
@DeMoorJasper I have three directories in my repo, `client`, `api`, `fonts` - and the fonts are used by both client (with parcel) and api (with express+GD), so I want to keep the fonts in the same place in the repo and require them by both folders. I think it's a fair use case
