### ISSUE TITLE
No .babelrc specified fails incorrect version

### ISSUE THREAD

**Issue by dcrystalj** [parcel-bundler/parcel#2587]
# 🐛 bug report

running parcel on empty project (wihtout .babelrc file) throws me this error
```
🚨  /Users/t/git/app/index.js: Conflicting babel versions found in .babelrc. Make sure all of your plugins and presets depend on the same major version of babel.
    at inferBabelVersion (/Users/t/n/lib/node_modules/parcel-bundler/src/transforms/babel/babelrc.js:224:17)
    at getBabelVersion (/Users/t/n/lib/node_modules/parcel-bundler/src/transforms/babel/babelrc.js:173:24)
    at <anonymous>
```
## 🎛 Configuration (.babelrc, package.json, cli command)
I have no .babelrc
I run ```parcel test.html``` which has just link to empty index.js as docs says

## 💻 Code Sample

https://github.com/dcrystalj/parcel-test
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | v8.11.4
| Yarn         | v1.13.0
| Operating System | osx

**Comment by mischnic** [comment]
Could you please commit your package.json and lockfile to the repo as well?

**Comment by dcrystalj** [comment]
@mischnic added.

**Comment by mischnic** [comment]
Happens for me as well when adding this .babelrc:
```json5
{
	"presets": ["babel-preset-env", "babel-preset-stage-3"],
	"plugins": ["babel-plugin-component"]
}
```

The reason is that parcel tries to determine whether it should use Babel 6 or 7, `babel-plugin-component` is not an official plugin and has the version number 1.1.1, so parcel doesn't know wheter it's for Babel 6 or 7.

A workaround:
```diff
diff --git a/package.json b/package.json
index 159bd97..9c5dd21 100644
--- a/package.json
+++ b/package.json
@@ -1,5 +1,6 @@
 {
   "devDependencies": {
+    "babel-core": "^6.26.3",
     "babel-plugin-component": "^1.1.1",
     "babel-preset-env": "^1.7.0",
     "babel-preset-stage-3": "^6.24.1"
```
