### ISSUE TITLE
Failing CI

### ISSUE THREAD

**Issue by DanielRuf** [parcel-bundler/parcel#2588]
It seems CI status is red since a while. =(

https://dev.azure.com/devongovett/devongovett/_build/results?buildId=811

**Comment by DeMoorJasper** [comment]
Someone was working on getting it fixed, but it appears the PR has been pretty inactive #2532

**Comment by mischnic** [comment]
> but it appears the PR has been pretty inactive

Hey 😄 
I have no idea why htmlnano produces no extra linebreaks on windows and whether that's actually the correct behavior (don't think so).

**Comment by DeMoorJasper** [comment]
@mischnic what about refactoring the tests so it compares the input file size with the minified output file size?
And completely get rid of the testing of linebreaks, as long as it minifies it should be good enough for Parcel afaik.
Testing linebreaks and such goes a bit too far imo as that's what htmlnano should test for already.
In the past it however was the quickest way to verify minification as it used to remove the linebreaks...

**Comment by mischnic** [comment]
> I'd be happy to experiment a lil with the tests if you don't have time to try some things atm

Go ahead! I'd have to setup my Windows machine again.
