### ISSUE TITLE
Version 1.11.0, no hot code updates

### ISSUE THREAD

**Issue by cgxqd123** [parcel-bundler/parcel#2589]
Hot module replacement is ineffective, Version 1.9.4 is effective。

**Comment by mischnic** [comment]
Please describe what exactly you'r having issues with and ideally some code to reproduce this.

**Comment by cgxqd123** [comment]
> Please describe what exactly you'r having issues with and ideally some code to reproduce this.

Version 1.11.0, modified code, no real-time updates (packaging)

**Comment by mischnic** [comment]
> Version 1.11.0, modified code, no real-time updates (packaging). 1.9.4 is normal.

This is not very helpful. It works for me. Please share your code

**Comment by mischnic** [comment]
"Can't reproduce"
