### ISSUE TITLE
Parcel works wrong without file name

### ISSUE THREAD

**Issue by aligoren** [parcel-bundler/parcel#259]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
Bug Report

### 🤔 Expected Behavior
When someone uses `parcel` command directly or `parcel .` like this should start with default index.html file.

### 😯 Current Behavior
If I use parcel command with a dot like this: `parcel .` or just `parcel` I'll see a blank page with any source code. I won't see any error message. This will work successfully with a blank page.

### 💁 Possible Solution

There are three ways:

1-) If filename is empty or a dot maybe filename get one of the default filenames.

2-) A user who uses commands like this should see an error message. 

3-) I think if filename starts with a dot or empty you can check if there is `index.html` file. If the index.html file is possible you can change `bundler.mainFile` property. Because I tried this way my project worked successfully. Or the **main** parameter in `Bundler` class can be control like this:

```javascript
constructor(main, options = {}) {
    super();
    if(main == undefined || main == '.') {
        main = 'index.html'
    }
    this.mainFile = Path.resolve(main || '');
```
**I should say this is not best idea**

### 🔦 Context
I'm sorry I can't show a sample project. Because it's about parcel's cli.

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  1.2.0
| Node             |  8.9.0
| Yarn         | 1.3.2
| Operating System | Windows 10 / Ubuntu

**Comment by devongovett** [comment]
Without an explicit input file specified on the command line, parcel defaults to the file specified by `main` in package.json. If you set that to `index.html` it should work as you expect.
