### ISSUE TITLE
Use of CSS Modules "composes:" results with duplicate classes exports

### ISSUE THREAD

**Issue by wajerrr** [parcel-bundler/parcel#2592]
# 🐛 bug report

Using 'composes' with CSSmodules results with duplicate styles exported:

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```js
{
  "name": "parcel-cssmodules-example",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "parcel --no-cache index.html",
    "build": "parcel build --no-cache index.html"
  }
  ,"postcss": {
    "modules": true
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel-bundler": "^1.11.0",
    "postcss-modules": "^1.4.1"
  }
}

```
## 😯 Current Behavior // Example 

mixin.css
```
.test {
    height: 100px;
    width: 100px;
    ...
}
```

composes-1.css
```
 .main {
    border: 3px solid orange;
    composes: test from './mixins.css';
}
```

composes-2.css
```
 .main {
    border: 3px solid red;
    composes: test from './mixins.css';
}
```

composes-3.css
```
 .main {
    border: 3px solid brown;
    composes: test from './mixins.css';
}
```

example.js 
```
import * as composes1 from './composes-1.css';
import * as composes2 from './composes-2.css';
import * as  composes3 from './composes-3.css';

window.onload = () => document.body.innerHTML = `
    <div class="${composes1.main}"></div>
    <div class="${composes2.main}"></div>
    <div class="${composes3.main}"></div>
`;
```

will  result with `output.css` having `.test (._test_giiwg_1)` class exported 3 times

```
._test_giiwg_1{
     /* styles from .test in mixins.css */
}
._main_1la6g_1{
    border:3px solid orange
}
._test_giiwg_1{
 /* styles from .test in mixins.css */
}
._main_1655g_3{
    border:3px solid red
}
._test_giiwg_1{
     /* styles from .test in mixins.css */
}
._main_hdlwj_1{
    border:3px solid brown
}
```
## 🤔 Expected Behavior

`.test  (._test_giiwg_1)` class exported only once

output.css
```
._test_giiwg_1{
     /* styles from .test in mixins.css */
}
._main_1la6g_1{
    border:3px solid orange
}
._main_1655g_3{
    border:3px solid red
}
._main_hdlwj_1{
    border:3px solid brown
}
```

## 💻 Code Sample

https://github.com/wajerrr/parcel-cssmodules-example

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.11.0
| Node             | v10.14.1
| npm         | 6.4.1
| Operating System | MacOS 10.13.6

**Comment by garthenweb** [comment]
I had this issue as well, it is slightly related to issue https://github.com/parcel-bundler/parcel/issues/2501 as Parcel does not handle composes really well at the moment.

I think the duplicate classes are a result of the multi-thread architecture of parcel: The Postcss modules transform normally takes care of removing duplicates but as Parcel is compiling all the file separately the css modules transform does not know about other files and duplicates.

I already thought about a fix, maybe we can iterate over all CSS assets within one bundle, compare the `asset.cssModules` property and remove duplicates. This might be performance intensive.

Anyhow, this is not only a performance issue as we have duplicate code in the output file but it can also have an effect on the specificity of CSS. As a workaround to hotfix this, I changed the default `generateScopedName` variable in the [Postcss transformer](https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/transforms/postcss.js#L37) to always have a unique class name:
``` js
let postcssModulesConfig = {
    getJSON: (filename, json) => (asset.cssModules = json),
    generateScopedName: `[name]_[local]_[hash:base64:5]${asset
        .generateBundleName()
        .substr(0, 5)}`,
};
```

@DeMoorJasper Would you be interested in a PR with this changes to fix the issue for now as long as there is not a proper solution to erase the duplicates? If so, I can prepare it.
