### ISSUE TITLE
Faster builds using SWC

### ISSUE THREAD

**Issue by marcus-sa** [parcel-bundler/parcel#2593]
# 🙋 feature request

## 🤔 Expected Behavior
Even faster

## 😯 Current Behavior
Fast, but not fast enough

## 💁 Possible Solution
https://github.com/swc-project/swc

**Comment by DeMoorJasper** [comment]
Probably not a good idea to set this as a default.
It would def be nice to see this as a plugin, probably best to wait for Parcel 2 before writing that though as babel is baked into parcel 1 and will be way more flexible in parcel 2

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by marcus-sa** [comment]
Definitely agree that it should be able as a plugin, since it supports both Babel and TypeScript

**Comment by kdy1** [comment]
Please feel free to ping me on github or [gitter](https://gitter.im/swcproject/Lobby) if you need any help using swc.

**Comment by fruity4pie** [comment]
It would be cool if there options what to choose => babel or swc :)

**Comment by devongovett** [comment]
This is the default as of #6230! 🥳
