### ISSUE TITLE
Typescript (no Babel) + React => React cannot correctly resolve internal `require()` statements 

### ISSUE THREAD

**Issue by RickCarlino** [parcel-bundler/parcel#2599]
# ❔ Question

I am transitioning my project off of Webpack. It appears that `require()` calls within React (and other modules in `node_modules`) do not resolve correctly. Please see `💻 Code Sample` for backtrace / screenshot.
**My question is:** When running a bundle that uses Typescript with a custom `--public-url`, are there any special configurations needed to use third party JS modules?

## 🔦 Context

I have multiple entry points:

 * `frontend/css/_index.scss`
 * `frontend/css/laptop_splash.scss`
 * `frontend/entry.tsx`
 * `frontend/front_page/index.tsx`
 * `frontend/password_reset/index.tsx`
 * `frontend/tos_update/index.tsx`

and I am compiling my bundle with the following command (NOTE: The assets are served from a Rails `/public` directory that makes the directory available via `localhost:3000`):

```
node_modules/parcel-bundler/bin/cli.js
  watch
  frontend/css/_index.scss
  frontend/css/laptop_splash.scss
  frontend/entry.tsx
  frontend/front_page/index.tsx
  frontend/password_reset/index.tsx
  frontend/tos_update/index.tsx
  --out-dir public/dist  # (It's a Rails project- gets served from `localhost:3000/dist`)
  --public-url /dist     # localhost:3000/dist
  --hmr-hostname 1.2.3.4 # Obfuscated
  --hmr-port 3808        # 3808 for legacy reasons
  --log-level 5
```
Example locations for `frontend/front_page/index.tsx` ([source](https://github.com/RickCarlino/farmbot-web-app/blob/parcel/frontend/front_page/index.tsx)): 
 * Entry file source location: `./frontend/front_page/index.tsx` :ok_hand: 
 * Bundle file location (on disk): `./public/dist/front_page/index.js`
 * Bundle file location (via HTTP): `http://localhost:3000/dist/front_page/index.js` :heavy_check_mark: No 404s :+1:.

The files _seem_ to be compiling without error and into a directory in `public/`, and the file does load when I open a page that contains `<script src="/dist/front_page/index.js"></script>`. However:

 * `require()` calls within `node_modules`, such as React's `require("object-assign")` trigger the error shown above.
 * Source maps resolve to `//# sourceMappingURL=/dist/index.map` but I think it should actually be `/dist/front_page/index.map` :question: Not sure if that's a bug in Parcel, or a lack of understanding on my part.
 * If I comment out the contents of `frontend/front_page/index.tsx` to not have any `import`s (eg: simple calls to `console.log("hello!");`, it compiles OK :ok_hand:. The error happens when I import React.

### Other stuff

 * I did `rm -rf .cache/`, `rm -rf node_modules/`, `rm -rf public/dist/` several times, but did not seem to help.
 * I was able to compile a project in isolation that uses Typescript + React + Parcel. I even copy/pasted my `package.json` and `tsconfig.json` into the proejct, but I was not able to reproduce. This leads me to believe there may be an old / incorrect config elsewhere?
 * Configuration files are:
   * I've alreaady pasted the CLI command that I used above, but for reference sake, [the helper that called the command is here](https://github.com/RickCarlino/farmbot-web-app/blob/parcel/lib/tasks/api.rake#L63-L72).
   * [tsconfig.json](https://github.com/RickCarlino/farmbot-web-app/blob/parcel/tsconfig.json) here.
   * [package.json](https://github.com/RickCarlino/farmbot-web-app/blob/parcel/package.json) here.

## 💻 Code Sample
```
Uncaught (in promise) Error: Cannot find module '../../node_modules/object-assign/index.js'
    at newRequire (entry_front_page.js:39)
    at newRequire (entry_front_page.js:23)
    at localRequire (entry_front_page.js:55)
    at react.development.js:18
    at Object.parcelRequire.../../node_modules/react/cjs/react.development.js.object-assign (react.development.js:15)
    at newRequire (entry_front_page.js:49)
    at localRequire (entry_front_page.js:55)
    at Object.parcelRequire.../../node_modules/react/index.js../cjs/react.development.js (index.js:6)
    at newRequire (entry_front_page.js:49)
    at localRequire (entry_front_page.js:55)
```
![image](https://user-images.githubusercontent.com/1388608/52000394-9f642680-2482-11e9-96e9-c37a6f915e05.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.11.0 |
| Node             |v8.12.0 |
| npm/Yarn         |6.7.0 |
| Operating System | Ubuntu 18.04.1 LTS (Bionic) |

**Thanks for all the great work on this project!** And appologies ahead of time if I just missed a simple config somewhere- I'm still learning the Parcel API.

**Comment by mischnic** [comment]
(I hope this is related to your issue)
Parcel works a bit differently compared to webpack:

You simply add script tags a style links to your html files, e.g.:
```html
<head>
<link href="./styles/main.scss">
</head>
<body>
<div id="root"></div>
<script src="./js/main.ts"></script>
</body>
```
Then you use that html file as an entry point (e.g. `parcel index.html`) and Parcel will handle the rest automatically. In this context, publicurl will affect the build output like this:
```html
<head>
<link href="PUBLIC_URL/main.29ashd2.scss">
</head>
<body>
<div id="root"></div>
<script src="PUBLIC_URL/index.as129sdj.ts"></script>
</body>
```

**Comment by RickCarlino** [comment]
Thanks for the fast reply @mischnic . In my use case, I can't use an HTML input because there are other things that need to be server-side rendered (by Ruby, not node), so I was hoping to manually place `<script src="/dist/front_page/index.js"></script>` in the page manually. Is this possible? I can see the `/public/dist/front_page/index.js` file just fine, but it seems to have issues with `require()` statements when loaded.

**Comment by mischnic** [comment]
> Source maps resolve to //# sourceMappingURL=/dist/index.map but I think it should actually be /dist/front_page/index.map ❓ Not sure if that's a bug in Parcel, or a lack of understanding on my part.

I think that should already be fixed in the next release.

> Update: I tried it with an HTML as experiment (single entry, static HTML file) and it did work, however this will still not work for my use case. Is a static HTML entry point mandatory for Parcel?

No.

Can you provide an example of how a hydrated server side template might look like?

**Comment by RickCarlino** [comment]
@mischnic How are typescript asset types different than HTML asset types? Is there any reason (such as configuration) why an `.html` entry would work better than a `.tsx` entry?

In the mean time, I will try an edge build of parcel to see if it helps any. Thanks again for your quick response- really enjoying parcel so far.

**Comment by mischnic** [comment]
> How are typescript asset types different than HTML asset types? Is there any reason (such as configuration) why an .html entry would work better than a .tsx entry?

Not at all. see below


> In the mean time, I will try an edge build of parcel to see if it helps any. Thanks again for your quick response- really enjoying parcel so far.

I'm on it as well.
This happens when you build with more than one entrypoint (e.g. `frontend/front_page/index.tsx frontend/password_reset/index.tsx`). I'm guessing Parcel (mistakenly) tries to include some dependency only once or some dynamic import isn't handled properly.

**Comment by RickCarlino** [comment]
@mischnic

 > some dynamic import isn't handled properly.

Judging by the [isolated reproduction case](https://github.com/mischnic/farmbot-web-app/tree/parcel), do you think `react` is causing the issues?* Or is it caused by some combination of deps that are unique to this project (such as `react` + `axios` + `i18next`). I may try switching [preact-compat](https://preactjs.com/) or [nerv](https://github.com/NervJS/nerv) in the meantime, if you think that is the case.

\*Side note: If react _is_ the culprit, is there something unique to my use case that would cause this, since React is a fairly common project dependency?

**Comment by mischnic** [comment]
> do you think react is causing the issues?

No, it's related to the imports. I think using static imports in passwordreset should help.
I remember seeing some old issues regarding this.

**Comment by RickCarlino** [comment]
@mischnic 

 >  it's related to the imports themselves... using static imports in [FILE THAT USES DYNAMIC IMPORTS] should help.

This appears to solve the issue! :tada: 

For anyone finding this issue thread off of Google, here is the fix:

I converted:

```
const React = await import("react"); // dynamic import in nested function
```
to
```
import React from "react"; // top of file
```
and it seems to be compiling!

I am going to close this issue. Feel free to re-open if you think more investigation is required or you have more questions. For my project, I plan to simply replace dynamic imports with static imports until a future release. Thanks for all your help.
