### ISSUE TITLE
🐛 Can't resolve dependence

### ISSUE THREAD

**Issue by blaze87** [parcel-bundler/parcel#260]
This is how I introduced js files：
<script src="./static/js/vue.min.js"></script>
<script src="./static/element-ui@1.4.12/index.js"></script>
When not packed, run normally;
The parcel was packed and then reported such a mistake：
**[parcel] 🚨 D:\Patientinfo\static\element-ui@1.4.12\index.js:1:215: Cannot resolve dependency 'vue';**

If it's packed like this：
<script src="./static/js/vue.min.js"></script>;
<script src="./static/js/jquery-3.2.1.min.js"></script>
That would be a mistake：
**Uncaught ReferenceError: $ is not defined;
Uncaught ReferenceError: Vue is not defined**

**Comment by davidnagli** [comment]
I’m not sure I understand. Do you mind filling out the issue template with exactly which commands you ran, as well as your version/os info?

Thanks :)

**Comment by brandon93s** [comment]
See #333.
