### ISSUE TITLE
Sourcemap url with multiple entrypoints

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#2607]
# 🐛 bug report

The sourcemap url in Javascript bundles isn't respecting the subfolder of the corresponding bundle.

## 🎛 Configuration (.babelrc, package.json, cli command)

`parcel build src/a/index.js src/b/index.js`

## 🤔 Expected Behavior

The two output files should contains these sourcemap comments:
a/index.js: `//# sourceMappingURL=/a/index.js.map`
b/index.js: `//# sourceMappingURL=/b/index.js.map`

## 😯 Current Behavior

The two output files contain these sourcemap comments (the map files are emitted correctly though) :
a/index.js: `//# sourceMappingURL=/index.js.map`
b/index.js: `//# sourceMappingURL=/index.js.map`

## 💁 Possible Solution

This is the related code:
https://github.com/parcel-bundler/parcel/blob/791b4b80462fee453d82f4c711b86553daa3427e/packages/core/parcel-bundler/src/packagers/JSPackager.js#L238-L245

## 💻 Code Sample

```js
// src/a/index.js
console.log("asd");

// src/b/index.js
console.log("asd");
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |master
| Node             |11
| npm/Yarn         |
| Operating System |

**Comment by lustoykov** [comment]
@mischnic you mind me taking this one or you've already started working on it?

On a first thought

`path.basename(mapBundle.name) -> path.relative(this.options.outDir, mapBundle.name)` 

might do it?

**Comment by mischnic** [comment]
Go ahead. I would say the publicUrl needs to be prepended as well?

**Comment by lustoykov** [comment]
yes, I had in mind:

```
let mapUrl = urlJoin( 
     this.options.publicURL, 
     path.basename(mapBundle.name) -> path.relative(this.options.outDir, mapBundle.name)
   );
```

will give it a try

**Comment by lustoykov** [comment]
Can we close, @mischnic?
