### ISSUE TITLE
Preact HMR

### ISSUE THREAD

**Issue by philipodev** [parcel-bundler/parcel#261]
🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

All config and code is available here: https://github.com/philipodev/examples/tree/master/preact

### 🤔 Expected Behavior

Like React HMR.

### 😯 Current Behavior

It appends the new version instead of replacing it.
![recording](https://user-images.githubusercontent.com/28024000/33985858-0938185c-e0bc-11e7-9dcc-a089d4dac0b6.gif)

### 💁 Possible Solution

https://github.com/developit/preact/issues/925 <-- i have tried this, as you can see in [main.js ](https://github.com/philipodev/examples/blob/master/preact/src/main.js) but still appends instead of replacing.

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  1.2.0
| Node             | 8.2.1
| npm | 5.5.1
| Operating System | Windows 10

**Comment by vinaypuppal** [comment]
@philipodev Hi, I also faced this issue but I solved it by passing `mountNode.lastChild` as last argument to `render` function. You can see full code below

```js
// my full main.js file
import { h, render } from 'preact';

import App from './components/app';

if (process.env.NODE_ENV === 'development') {
  // Enable preact devtools
  // eslint-disable-next-line import/no-unassigned-import
  require('preact/devtools');
}

const mountNode = document.getElementById('root');

render(<App />, mountNode, mountNode.lastChild);

// Hot Module Replacement
if (module.hot) {
  module.hot.accept();
}
```

**Comment by philipodev** [comment]
@vinaypuppal thank you very much. this worked!
Is this a bug within preact and not returning the rendered node or is it some issue in parcels hmr you think?
