### ISSUE TITLE
CI still fails with Node 6 on Windows. 

### ISSUE THREAD

**Issue by sainthkh** [parcel-bundler/parcel#2613]
# ❔ Question

I fixed the Windows `watcher.stop()` test. And there is no problem with that. (#2609 #2612)

But CI still fails with Node 6 on Windows. You can see [the single red circle in the middle of other green ones](https://sainthkh.visualstudio.com/Parcel%20test/_build/results?buildId=3). According to console messages, it seems that the test failed somewhere when testing to auto-install babel and other dependencies. 

Now, here's the question: 

The support for Node 6 ends on April 2019. In other words, it's less than 100 days and a little more than 2 months. 

I can install Node 6 and track problems. But I don't think it's a good idea for me to spend time to support old and rare systems. 

How about removing Node 6 tests from our CI? 

## 🔦 Context

CI fails on Windows + Node 6. And it can confuse new contributors. 

## 💻 Code Sample

[Azure CI result](https://sainthkh.visualstudio.com/Parcel%20test/_build/results?buildId=3)

## 🌍 Your Environment

N/A

**Comment by sainthkh** [comment]
In #2602, there are failures in Linux Node 6 and Windows Node 8 after request to localhost. 

I guess the failure is related with timeout.

**Comment by devongovett** [comment]
We are dropping Node 6 in Parcel 2, but until then we should continue to support it or it would be a breaking change.
