### ISSUE TITLE
favicon disable scope hoisting

### ISSUE THREAD

**Issue by ai** [parcel-bundler/parcel#2614]
# 🐛 bug report

Scope hoisting doesn’t work when I set `<link rel="shortcut icon" href="./favicon.ico">`

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "audio-recorder-polyfill",
  "version": "0.1.3",
  "description": "MediaRecorder polyfill to record audio in Edge and Safari",
  "repository": "ai/audio-recorder-polyfill",
  "devDependencies": {
    "parcel": "^1.11.0"
  },
  "scripts": {
    "start": "parcel serve ./test/demo/index.html --open",
    "build": "parcel build -d ./test/demo/build --experimental-scope-hoisting ./test/demo/index.html"
  }
}
```

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Media Recorder Polyfill</title>
    <link rel="shortcut icon" href="./favicon.ico">
  </head>
  <body>
    <script src="./index.js">
  </body>
</html>
```

```js
// index.js
1+1
```

## 🤔 Expected Behavior

Empty `index.js` after `yarn build`

## 😯 Current Behavior

`index.js` after `yarn build`:

```js
parcelRequire=function(e){var r="function"==typeof parcelRequire&&parcelRequire,n="function"==typeof require&&require,i={};function u(e,u){if(e in i)return i[e];var t="function"==typeof parcelRequire&&parcelRequire;if(!u&&t)return t(e,!0);if(r)return r(e,!0);if(n&&"string"==typeof e)return n(e);var o=new Error("Cannot find module '"+e+"'");throw o.code="MODULE_NOT_FOUND",o}return u.register=function(e,r){i[e]=r},i=e(u),u.modules=i,u}(function (require) {return{"Focm":{}};});
```

## 💁 Possible Solution

Maybe some error in scope hoisting checks. 

## 🔦 Context

Scope hoisting is awesome for small sites, but `favicon.ico` is very important for good UX as well.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11
| Node             | 11.09
| npm/Yarn         | 1.13.0
| Operating System | Fedora 29

**Comment by mischnic** [comment]
Really strange.

The only thing about an ico that can change the javascript bundle is this:
https://github.com/parcel-bundler/parcel/blob/791b4b80462fee453d82f4c711b86553daa3427e/packages/core/parcel-bundler/src/assets/RawAsset.js#L21-L26

**Comment by ai** [comment]
If your want, I can put `console.log` to some file of Parcel (sorry, have no idea how this file work in Parcel).

**Comment by mischnic** [comment]
`needsPrelude` is true here (so `parcelRequire=...` gets inserted):
https://github.com/parcel-bundler/parcel/blob/791b4b80462fee453d82f4c711b86553daa3427e/packages/core/parcel-bundler/src/packagers/JSConcatPackager.js#L525-L529

I think this logic is wrong:
https://github.com/parcel-bundler/parcel/blob/791b4b80462fee453d82f4c711b86553daa3427e/packages/core/parcel-bundler/src/packagers/JSConcatPackager.js#L39-L44

**Comment by mischnic** [comment]
Should be fixed with Parcel 2
