### ISSUE TITLE
Typescript CSS Modules .d.ts files

### ISSUE THREAD

**Issue by garthenweb** [parcel-bundler/parcel#2616]
# 🙋 feature request

When using CSS Modules in combination with Typescript we import (s)css files by `import * as styles from './styles.scss'`. Typescript throws in this line with the error "Cannot find module './styles.scss'.".

There are tools out there like [typed-css-modules](https://github.com/Quramy/typed-css-modules) which automatically generate a `.d.ts` file to solve this.

As I am using sass, typed-css-modules is not working for me and I did not found a good alternative. I thought it might be nice to have this directly in Parcel as it already has most what it takes to implement this.

Please let me know if you would be interested to implement this, I am not sure if you consider this within the scope of Parcel. Otherwise I will probably try to writing a plugin for this.

## 🤔 Expected Behavior

If using typescript and css modules, all imported styles should generate a `.d.ts` file beside the original file.

## 😯 Current Behavior

No modules files are generated and therefore typescript throws.

## 💁 Possible Solution

Hacking a bit around, injecting the following function into the `getJSON` function in the postcss transform worked surprisingly well:

``` js
const writeDTSFile = (filename, keys) => {
  // TODO: Move .d.ts generation into its parcel plugin
  if (keys.length === 0) {
    return
  }
  const dtsFile = keys
    .map(key => {
      return key.replace(/-+(\w)/g, (match, firstLetter) => {
        return firstLetter.toUpperCase()
      })
    })
    .reduce((file, key) => `${file}export const ${key}: string;${os.EOL}`, '')
  fs.writeFile(filename, dtsFile, { encoding: 'utf8', flag: 'w' }, err => {
    if (err) {
      console.error(`Could not create .d.ts file for \`${filename}\``)
      throw err
    }
  })
}
```

And then in https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/transforms/postcss.js:
``` js
let postcssModulesConfig = {
    getJSON: (filename, json) => {
        asset.cssModules = json
        writeDTSFile(`${filename}.d.ts`, Object.keys(json))
    }
};
```

We probably only need to add some checks whether typescript is used or not.

## 🔦 Context

See description.

## 💻 Examples

See https://github.com/Quramy/typed-css-modules.

**Comment by garthenweb** [comment]
I created a plugin now to support this feature: [parcel-plugin-css-modules-type-generator](https://www.npmjs.com/package/parcel-plugin-css-modules-type-generator)

Please note that there was already another option on npm I was not aware of when starting to work on the plugin: [parcel-plugin-typed-css-modules](https://www.npmjs.com/package/parcel-plugin-typed-css-modules) It has a similar approach but did not work well in combination with css modules for my application (see https://github.com/Place1/parcel-plugin-typed-css-modules/issues/1 for more details). But it allows to generate types in case you don't activate css modules in Parcel, which might be helpful in some setups.

As I already had a working solution which was not compatible with the existing plugin I published it to npm as an alternative anyhow, please feel free to choose the better fit for your project.

As there are some ways to support this now and it might not be intended for some users that Parcel generates files out of the box, I will close this. In case someone has a good idea on how to implement it directly into Parcel, feel free to comment/ reopen!

**Comment by eekboom** [comment]
The linked project is abandoned and does not work with parcel 2.
After installing it, all I get is 

```
🚨  No entries found.
    at Bundler.bundle (/home/stephen/dev/base64/node_modules/parcel-bundler/src/Bundler.js:275:17)
```

Also when installing the npm package is adds 5 "high" vulnerabilities.

Any other solution?
