### ISSUE TITLE
Is there any way to use build hash in query string instead of file name?

### ISSUE THREAD

**Issue by g-harel** [parcel-bundler/parcel#2617]
# ❔ Question

Is there any way to use the content hash in query string instead of file name?

## 🔦 Context

I'd like to make the html output look something like this:

```html
<script src="/bundle.f69400ca.js?b=zDzRZ7"></script>
```

I'm already using `--no-content-hash` for stable file names, but I would still like to be able to cache bust.

Thanks

**Comment by DeMoorJasper** [comment]
CDNs can opt to ignore query parameters on js and other static files so this wouldn’t be optimal imo. However there should be a way to disable filename hashing but this will be added in Parcel 2

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by g-harel** [comment]
Yep I would need to configure it on the CDN too, but that's not super complicated.

Do you know if a parcel plugin could add query parameters?

**Comment by DeMoorJasper** [comment]
I don’t see the point in doing it as parcel can’t output non hashed names atm. That will only be possible once parcel 2 comes out. And than I’m not sure why you’d even prefer this as it would probably be just as efficient and cost you more in cdn costs

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by g-harel** [comment]
The filename is not relevant here, my question is about _adding a query string in the outputted html import_.

**Comment by Lcfvs** [comment]
@g-harel Just published : https://www.npmjs.com/package/parcel-plugin-pre-dist ;)

**Comment by damianobarbati** [comment]
@g-harel how did you solve? I actually have the same problem, but maybe I'm missing something here @DeMoorJasper.

The CDN may opt-in to ignore the querystring but browser does not. 
Disabling content-hash (and use filename-hash instead) do not solve it.

1. I build my `index.html` which links `app.123.js`
2. user go to my website, browser download index.html (cache disabled on this file) and `app.123.js`: **app.123.js** is now cached into browser with ttl=86400
3. I build my `index.html` which links `app.123.js` 
4. user go to my website, browser download index.html (cache disabled on this file) and again `app.123.js`

Having the `app.123.js?<content-hash>` would solve this. Right?

**Comment by DeMoorJasper** [comment]
@damianobarbati it might but it's less reliable than using a hash in the filename as hashes in the filename will always invalidate any cache. Regardless of how it's configured. As you mentioned you can configure a CDN to still serve cache regardless of query params.

Anyway the solution to this issue is use Parcel 2.

**Comment by damianobarbati** [comment]
@DeMoorJasper I solved by disabling `cache-control: no-store` on html files for now.

Anyway, what do you mean when you say the solution is parcel v2, does it have specific features for cache busting?

PS: I'll switch as soon as it's stable, too many things missing right now. I have my parcel-v2 branch already there on most of my repos 💪

**Comment by DeMoorJasper** [comment]
@damianobarbati I was mainly talking about the original issue of being able to control how to name files. But Parcel 2 also has better hashing and other caching improvements
