### ISSUE TITLE
Question: What is the cli "--no-autoinstall" flag equivalent for parcel's api?

### ISSUE THREAD

**Issue by amilajack** [parcel-bundler/parcel#2618]
# ❔ Question

Question: What is the cli "--no-autoinstall" flag equivalent for parcel's api?

Related: https://github.com/parcel-bundler/parcel/pull/2076

**Comment by DeMoorJasper** [comment]
`autoinstall: false`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by amilajack** [comment]
Okay I'll try this. Thanks
