### ISSUE TITLE
It doesn't resolve image file pointed in src attribute of <amp-img> elements

### ISSUE THREAD

**Issue by honey32** [parcel-bundler/parcel#2622]
# 🐛 bug report
The entry point is a html file.
The bundler doen't seem to detect the resource file which is specified in `<amp-img>` tag's `src` attribute.
The path in output file is the same as the input file.
```html
<amp-img src="/path/to/image.jpg">
```
## 🎛 Configuration (.babelrc, package.json, cli command)

`parcel index.html`

## 🤔 Expected Behavior

It should work as same as it does for `<img>`  tag.
```html
<amp-img src="/image.(hash goes here).jpg">
```

## 😯 Current Behavior

It doesn't.

## 💁 Possible Solution

Furthurmore, I think there should be **no limitation** of the tag name (or **black-list** instead of current black-list) on checking `src` attribute, because there are plenty types of amp elements using media file (See: [Components - Amp](https://www.ampproject.org/docs/reference/components)).

## 🔦 Context

Parcel is now not friendly with AMP.

## 💻 Code Sample
[https://github.com/honey32/snippet-of-parcel-bug](https://github.com/honey32/snippet-of-parcel-bug)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | 8.9.3
| npm/Yarn         | 5.5.1
| Operating System | Windows 10

**Comment by BegoConstantino** [comment]
Any update to this? I have the same issue

**Comment by honey32** [comment]
sorry, i'm not sure. I'm not dealing with a project related to this problem.

2020年6月12日(金) 16:02 BegoConstantino <notifications@github.com>:

**Comment by BegoConstantino** [comment]
I fixed it!
Just need to add 'amp-img' in the array of src to watch. File:
\node_modules\parcel-bundler\src\assets\HTMLAsset.js

**Comment by honey32** [comment]
thank you!
i appreciate your work.

2020年6月17日(水) 16:01 BegoConstantino <notifications@github.com>:

**Comment by honey32** [comment]
Maybe the file below is the same as one you mentioned.
[parcel/packages/transformers/html/src/dependencies.js](https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/html/src/dependencies.js)
However, i'm not sure if 'parcel' should support AMP.

**Comment by BegoConstantino** [comment]
It seems like the same file (in my installed parcel has more const defined at the begining)

Anyway. A simple AMP page is just as decorated html, 'parcel' has not problems to complie it. I did it and the amp-img src was the only error that I see.

**Comment by honey32** [comment]
I'll make a Pull Request ... in the future.
