### ISSUE TITLE
Cannot serve static assets created via "parcel build src/index.html"

### ISSUE THREAD

**Issue by mateja176** [parcel-bundler/parcel#2624]
# 🐛 bug report

App works perfectly when running locally using `parcel src/index.html`, however after creating a production bundle by running `parcel build src/index.html` and attempting to serve the static assets using [vscode live serve](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) or [serve](https://www.npmjs.com/package/serve) the app is being served with missing CSS and JavaScript files. The same thing happens when the app is served via [github pages](https://mytee306.github.io/nns/). Interestingly enough, [http-serve](https://www.npmjs.com/package/http-server) is able to serve the app in its entirety. The repository containing whole source code can be found [here](https://github.com/mytee306/nns)

## 🎛 Configuration (.babelrc, package.json, cli command)

[package.json](https://github.com/mytee306/nns/blob/master/package.json)

## 🤔 Expected Behavior

App is being served including CSS and JavaScript files.

## 😯 Current Behavior

App is served without CSS and JavaScript assets

Errors when accessing [page](https://mytee306.github.io/nns) served by github

```
src.184de31a.css:1 Failed to load resource: the server responded with a status of 404 ()
src.152c138c.js:1 Failed to load resource: the server responded with a status of 404 ()
src.184de31a.css:1 Failed to load resource: the server responded with a status of 404 ()
```

## 💁 Possible Solution

Changing the mime types of CSS and JavaScript assets

## 💻 Code Sample

The repository containing whole source code can be found [here](https://github.com/mytee306/nns)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | 10.7.0
| npm/Yarn         | 6.5.0
| Operating System | Linux

**Comment by lustoykov** [comment]
Hello @mytee306, you can set the option `--public-url`. To make github pages work for instance, you have two options:

`parcel build src/index.html --public-url='./'`. 

It would then serve the assets from `https://mytee306.github.io/nns/` as opposed to `https://mytee306.github.io`. 

Alternatively  

`parcel build src/index.html --public-url='/nns'` should work too - same logic.

Someone correct me if I'm wrong, but the reason it doesn't work is that by default parcel expects that the bundle is in the server's top-most / root directory. In github pages case, they are nested in `nns/`. So if you run `serve / http-server` in `dist/` it should work. If you run them one folder above, it won't, unless you set `--public-url`

**Comment by mytee306** [comment]
@lustoykov Works as a charm, thank you so much!

**Comment by mihailik** [comment]
Shouldn't parcel change default then? Looks like a bug.

**Comment by mytee306** [comment]
@mihailik I was wondering the same, would be nice to hear the opinion of a contributor.
