### ISSUE TITLE
Cannot serve entry file from a dot folder

### ISSUE THREAD

**Issue by adrianmcli** [parcel-bundler/parcel#2628]
# 🐛 bug report

When the entry file is inside a dot folder, I get the following error in my browser:

```
Uncaught SyntaxError: Unexpected token <
```

It seems like the server might be serving the HTML as JS for some reason (instead of serving the real JS file).

## 🎛 Configuration (.babelrc, package.json, cli command)

No Babel config, Parcel is the only dependency, command:

```
parcel .myFolder/index.html
```

## 🤔 Expected Behavior

It should not error out.

## 😯 Current Behavior

Errors out in the browser:

```
Uncaught SyntaxError: Unexpected token <
```

## 💁 Possible Solution

Maybe something is wrong with the way the server parses the paths? I am not sure about Parcel internals.

## 🔦 Context

I want to have my entry point file inside a dot folder (i.e. `.myFolder`). That's all.

## 💻 Code Sample

Reproduction repo here: https://github.com/adrianmcli/repro-parcel-dot-folder

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0 |
| Node             | v10.13.0 | 
| npm/Yarn         |6.5.0|
| Operating System |MacOS 10.14.2|

**Comment by lustoykov** [comment]
Hello @adrianmcli, thanks for the report. 

I was not able to reproduce the behaviour and the error indicates some problem in `index.html` as opposed to folder structure. Do you mind sharing the contents of `index.html`?

**Comment by adrianmcli** [comment]
@lustoykov I posted a reproduction repo above. Here is the link again: https://github.com/adrianmcli/repro-parcel-dot-folder
