### ISSUE TITLE
How to set --public-url without slash at the beginning?

### ISSUE THREAD

**Issue by MatejBransky** [parcel-bundler/parcel#2629]
# ❔ Question

How to set `--public-url` so it builds script:src paths without slash? (instead of `<script src="/src.3858a192.js"></script>` I need this `<script src="src.3858a192.js"></script>`)

## 🔦 Context

I need to build local version of app (without server so you can just open index.html in browser via file://).

## 💻 Code Sample

`src/index.html`:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>React locally</title>
  </head>
  <body>
    <div id="app"></div>
    <script src="index.js"></script>
  </body>
</html>
```

`dist/index.html`:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>React locally</title>
  </head>
  <body>
    <div id="app"></div>
    <script src="/src.3858a192.js"></script> <!-- this doesn't work in local execution, it has to be without a slash at the beginning -->
  </body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             |  8.10.0
| npm/Yarn         | 1.12.3
| Operating System | Kubuntu 18.04

**Comment by mischnic** [comment]
`--public-url "./"` might work

**Comment by MatejBransky** [comment]
I've found out that  `--public-url '.'` works too.

**Comment by folknor** [comment]
Am I correct in thinking this no longer works in parcel 2.0.0 beta?

I've also tried ```json
  "web": "./index.html",
  "targets": {
    "web": {
      "context": "browser",
      "publicUrl": "./"
    }
  },
  ``` in package.json and changing the build script to `parcel build --no-minify --target web`, but I just get `No entries found.` then.

**Comment by mischnic** [comment]
```
  "web": "./dist/index.html", // <------- the "output"
  "targets": {
    "web": {
      "context": "browser",
      "publicUrl": "./"
    }
  },
```

```
parcel build src/index.html --no-minify --target web
             ^^^^^^^^^^^^^^
               the"input"
```

(You don't need to use these actual paths, they're just for illustration purposes)

**Comment by folknor** [comment]
I see, my mistake - thank you. But that gives me a new error that seems kind of unrelated. If you want me to open a new ticket, I can do that;

```
Build failed.
@parcel/namer-default: Target "web" declares an output file path of "dist/index.html" which does not match the compiled bundle type "js".
/home/folk/website/package.json:11:10
  10 |   },
> 11 |   "web": "./dist/index.html",
>    |          ^^^^^^^^^^^^^^^^^^^ Did you mean "dist/index.js"?
  12 |   "targets": {
  13 |     "web": {
Try changing the file extension of "web" in package.json.
npm ERR! code 1
npm ERR! path /home/folk/website
npm ERR! command failed
npm ERR! command sh -c npm run clean && parcel build index.html --no-minify --target web
```

Here's a reduced test case package.json
```json
{
  "name": "web",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "clean": "rm -rf dist/",
    "build": "npm run clean && parcel build index.html --no-minify --target web",
  },
  "web": "./dist/index.html",
  "targets": {
    "web": {
      "context": "browser",
      "publicUrl": "./"
    }
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel": "^2.0.0-beta.1",
  }
}

```

**Comment by mischnic** [comment]
Are you sure that's the package.json when the error occured?

The error usually occurs with something like this (different file types)
```
    "build": "parcel build index.js",
  },
  "web": "./dist/index.html",
```

**Comment by folknor** [comment]
Yes, absolutely positive, I've reduced it to the testcase in my previous comment in a new folder.

**Comment by folknor** [comment]
That said, when I reduce my index.html to

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>My First Parcel App</title>
  </head>
  <body>
    <h1>Hello, World!</h1>
  </body>
</html>
```
it no longer happens.

**Comment by folknor** [comment]
Add this to the html file: `<link rel="manifest" href="/manifest.json">` and a manifest.json file that contains
```json
{
	"name": "App",
	"icons": []
   }
```
and the problem appears

**Comment by mischnic** [comment]
Looks like the same issue as https://github.com/parcel-bundler/parcel/issues/5743
