### ISSUE TITLE
Everybody, who can do the app on the shelf? 

### ISSUE THREAD

**Issue by aa125660636** [parcel-bundler/parcel#263]
Everybody, who can do the app on the shelf? Like this https://itunes.apple.com/cn/app/id1293167709? Mt=8
Https://itunes.apple.com/cn/app/id1317244973? Mt=8

**Comment by DeMoorJasper** [comment]
This doesn't seem related to Parcel?
If i made a mistake feel free to reopen

**Comment by aa125660636** [comment]
Who can make the app on the shelf?
Https://itunes.apple.com/cn/app/id1319288608? Mt=8
Https://itunes.apple.com/cn/app/id1293167709? Mt=8
Similar to the two
