### ISSUE TITLE
Is it possible to create a NPM package from Typescript?

### ISSUE THREAD

**Issue by FreeFrags** [parcel-bundler/parcel#2630]
# ❔ Question
I would like to know if it is possible to create a NPM package with Typescript with parcel. Can someone point me in the right direction? is it at all possible? This question can probably be linked to #1612

**Comment by DeMoorJasper** [comment]
It's probably possible, you should probably use `--target node`. However I'd recommend against putting bundled code on npm as it results in larger bundles and very hard to read code (sometimes people wanna fix a bug straight in node_modules).

Also I'm not sure if parcel can consume bundles created by parcel. So bundling bundled code is not really that good of an idea either.

You're probably better of just publishing code ran through the basic ts compiler or Babel

**Comment by icopp** [comment]
@FreeFrags See my package [basedirs](https://github.com/icopp/basedirs) for something that's written in Typescript and generates Node 4 compatible output for NPM publishing.

**Comment by mischnic** [comment]
Closing because the question is too broad.
