### ISSUE TITLE
cannot resolve sass dependencies that have a "sass" entry at their package.json

### ISSUE THREAD

**Issue by renatodeleao** [parcel-bundler/parcel#2636]
# 🐛 bug report
When trying to import an installed sass module, in this case bootstrap (for testing), import fails.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// not related but .babelrc
module.exports = api => {
  api.cache(true);
  const presets = ["@babel/preset-env"];

  return {
    presets
  }
}
```

```json
{
  "name": "parcel-sanity-check",
  "version": "1.0.0",
  "main": "index.js",
  "repository": "git@github.com:renatodeleao/parcel-sanity-check.git",
  "author": "Renato de Leão <renatodeleao@gmail.com>",
  "license": "MIT",
  "scripts": {
    "dev:site": "parcel site/index.html --out-dir public --no-cache",
    "build": "parcel build site/index.html --out-dir public"
  },
  "devDependencies": {
    "autoprefixer": "^9.4.7",
    "parcel-bundler": "^1.11.0",
    "posthtml": "^0.11.3",
    "posthtml-expressions": "^1.1.0",
    "posthtml-extend": "^0.3.0",
    "posthtml-modules": "^0.4.2",
    "sass": "^1.17.0"
  },
  "dependencies": {
    "@babel/core": "^7.2.2",
    "@babel/preset-env": "^7.3.1",
    "@babel/register": "^7.0.0",
    "@whitesmith/qnorr-styles": "^0.1.1",
    "bootstrap": "4.3.0"
  }
}

```
## 🤔 Expected Behavior
It should import correctly an external sass modules dependency 

## 😯 Current Behavior
It's throwing the following error because parcel expects `sass` from `package.json` to be an object, but bootstrap ships with `sass: "scss/bootstrap.scss"` 

``` 
🚨  /localPath/node_modules/bootstrap/scss/bootstrap.scss: Cannot create property 'includePaths' on string 'scss/bootstrap.scss'
    at SASSAsset.parse (/localPath/parcel-sanity-check/node_modules/parcel-bundler/src/assets/SASSAsset.js:27:23)
```

## 💁 Possible Solution
Don't have a solution, and non of the suggested at https://github.com/parcel-bundler/parcel/issues/645 which blame postCSS work for me ( i don't think postCSS has anything to do with my case)

I may have a suggestion:
What if entries in `package.json` that parcel uses for configuration were scoped under `parcel` namespace. Otherwise, packages like `bootstrap` that uses (the non-standard) `sass` will break. It's a non standard prop but, you know, they are kind of big and famous.

Note: This would be a breaking change, so i do not expect it to be shipped as fix for this.

```js

"parcel": {
  sass: "",
  posthtml: ""
  ...
 }
```
## 🔦 Context
I accidentally discovered this because i am developing my companiy's own sass framework. I was looking for references on best practices for bundling and bootstrap immediately popped up. Then I found this two lines i've never seen in a `package.json` before `style` and a `sass` entries

https://github.com/twbs/bootstrap/blob/45ced606f479ecad1a8e5858367dbb3fcf1a9ee7/package.json#L88-L90

I try to dig on the webs
https://jaketrent.com/post/package-json-style-attribute/
https://stackoverflow.com/questions/32037150/style-field-in-package-json

so it looks like both are non standard, but `style` is used by `postcss-import`. 
In my innocence i said:
> well they can't do no harm

It did, i was testing a simple parcel website with my new framework and realised that i couldn't import my library. I deleted the line `sass` from `package.json`, *et voilá*

## 💻 Code Sample
https://github.com/renatodeleao/parcel-sanity-check

## 🌍 Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.11.0
| Node             | v11.8.0
| npm/Yarn         |  1.13.0
| Operating System | macOs 10.14

**Comment by gitliver** [comment]
I have a similar problem. Parcel (version 1.12.3) fails with an 

`Cannot create property 'includePaths' on string 'index.scss'`

error when using Github's [Primer CSS](https://github.com/primer/css) package (12.4.0):

`import "@primer/css/index.scss";`

Am I doing something stupid or is this an issue? Thanks!

**Comment by ealtunyay** [comment]
I ran into this today and stumbled a bit before getting past it in my case. I'm writing this in case it helps anyone.

1. Create a new scss file (or use an existing one that makes sense) and `@import "../node_modules/bootstrap/scss/bootstrap.scss";` file from there (see https://getbootstrap.com/docs/4.3/getting-started/theming/#importing).
2. `import "./custom.scss"` from your js

I don't know if this really counts as a solution, but it did get parcel running correctly in [the repo created by @renatodeleao to test the parcel behavior in question](https://github.com/renatodeleao/parcel-sanity-check)

I didn't fork it. Hopefully this helps:

    diff --git a/site/index.js b/site/index.js
    index fca7b3c..2e0aeb9 100644
    --- a/site/index.js
    +++ b/site/index.js
    @@ -4,8 +4,7 @@ import "@whitesmith/qnorr-styles/scss/qnorr.scss";
      * i do have a sass entry on my package.json, and it's not an object 🤷‍♂️
      * https://github.com/twbs/bootstrap/blob/45ced606f479ecad1a8e5858367dbb3fcf1a9ee7/package.json#L88-L90
      */
    -// import "bootstrap/scss/bootstrap.scss";
    -import "./index.scss"
    +import "bootstrap/scss/bootstrap.scss";
    
    
    console.log('Hello World');
    \ No newline at end of file
    diff --git a/site/index.scss b/site/index.scss
    index c4fb643..b85db67 100644
    --- a/site/index.scss
    +++ b/site/index.scss
    @@ -1,4 +1,3 @@
    -@import "../node_modules/bootstrap/scss/bootstrap.scss";
    
    body {
      background: #101010;
