### ISSUE TITLE
Vue build externall js file not loading

### ISSUE THREAD

**Issue by slugger7** [parcel-bundler/parcel#2639]
# 🐛 bug report

When building a vue project that has an external js file for the script, the js file never gets loaded with a build but will work fine if you user `parcel index.html`.

## 🎛 Configuration (.babelrc, package.json, cli command)
Running `parcel index.html` works fine
Running `parcel build index.js` and then hosting that in a index.html somewhere else does not work.

```js
{
  "main": "index.js",
  "scripts": {
    "start": "parcel index.html",
    "build": "parcel build index.js"
  },
  "alias": {
    "vue": "./node_modules/vue/dist/vue.common.js"
  },
  "dependencies": {
    "vue": "^2.6.6",
    "vue-hot-reload-api": "^2.3.2"
  },
  "devDependencies": {
    "@vue/component-compiler-utils": "^2.5.2",
    "parcel": "^1.11.0",
    "vue-template-compiler": "^2.6.6"
  }
}
```

## 🤔 Expected Behavior

When building the js to include in the hosted/production version the linked files in vue does not come through
```vue
<template>...</template>
<script src="./SomeJs.js"></script>
```
SomeJs.js does not get bundled but if you paste the contents of SomeJs in the script tag it gets bundled.

## 😯 Current Behavior

The external js file of the vue file is not being bundled but when building the application

## 💁 Possible Solution

```vue
<template></template>

<script>
import SomeJs from './SomeJs.js';
export default SomeJs; // or: export default require('./SomeJs.js');
</script>
```
## 🔦 Context

We wish to use a vue application in a asp.net application. The cshtml will include the built js file that gets built by parcel

## 💻 Code Sample

```vue
<template>...</template>

<script src="./SomeJs.js"></script>
```
`parcel index.html` will include SomeJs.js
`parcel build index.js` does not include SomeJs.js

```vue
<template></template>

<script>/*Contents of SomeJs.js*/</script>
```
`parcel build index.js` includes the script

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11
| Node             | 10.14,2
| npm/Yarn         |  npm 6.4.1
| Operating System | Windows 10

**Comment by DFOXpro** [comment]
I can replicate also in `serve` mode

**package.js**
```json
  "dependencies": {
    "vue": "^2.6.10"
  },
  "devDependencies": {
    "@babel/core": "^7.4.3",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@vue/component-compiler-utils": "^2.6.0",
    "parcel-bundler": "^1.12.3",
    "vue-template-compiler": "^2.6.10"
  }.
  "scripts": {
    "dev": "parcel serve --global _debug_ src/index.html --log-level 4"
  }
```
**SomeVue.vue**
```html
<template>
  <someOtherVue/>
  ...
</template>
<script src="./SomeVue.js"></script>
```

**Build log**
```
npm run dev

> vue-test@1.0.0 dev ./vue/test
> parcel serve --global _debug_ src/index.html --log-level 4

[15:15:30]: Server running at http://localhost:1234 
[15:15:30]: Building...
[15:15:30]: Building index.html...
[15:15:31]: Building main.js...
[15:15:31]: Building vue.js...
[15:15:31]: Building SomeVue.vue...
[15:15:31]: Building index.js...
[15:15:31]: Building vue.runtime.esm.js...
[15:15:32]: Built ../../../../node_modules/vue-hot-reload-api/dist/index.js...
[15:15:32]: Built ../node_modules/vue/dist/vue.js...
[15:15:32]: Built ../../../../node_modules/vue/dist/vue.runtime.esm.js...
[15:15:32]: Built ../../App.vue...
[15:15:32]: Built main.js...
[15:15:32]: Built index.html...
[15:15:32]: Producing bundles...
[15:15:32]: Packaging...
[15:15:32]: Building hmr-runtime.js...
[15:15:32]: Built ../node_modules/parcel-bundler/src/builtins/hmr-runtime.js...
```

Note in the log `SomeVue.js` is never reached, also no `someOtherVue` (witch is imported in `SomeVue.js` and used in `SomeVue.vue`)
Also running parcel ./src/index.html don't fix the problem.

**Comment by aikakira** [comment]
This issue still persists on Parcel 1.12.4 and using VueJs 2.6.11

Thanks @slugger7 for your possible solution workaround

**Comment by slugger7** [comment]
I have not tested this recently. We had to switch over to a webpack build but I have not worked on this project in a year so I have no idea.

**Comment by Takerman** [comment]
Does anyone had a resolution to it? For me it still present. The external js files are ignored.
