### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by Lcfvs** [parcel-bundler/parcel#2647]
# 🐛 bug report

 [Security issue, related to static-eval](https://npmjs.com/advisories/758)

## 😯 Current Behavior

> Run  npm update static-eval --depth 6  to resolve 1 vulnerability
> Moderate        Sandbox Breakout / Arbitrary Code Execution 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1 .11.0

**Comment by pocesar** [comment]
it's fixed upstream https://github.com/browserify/static-eval/issues/20

**Comment by millette** [comment]
Previous patch (included in static-eval 2.0.1) didn't fix the problem. This one should: https://github.com/browserify/static-eval/pull/23 and hopefully published with static-eval 2.0.2 soon.

**Comment by millette** [comment]
Should be fixed now: https://github.com/browserify/static-eval/commit/a5547bf00a3053e06c995fc3818289490cb4838b

```sh
npm audit fix # fixed the warnings
```

**Comment by Lcfvs** [comment]
Ok, thanks ;)

**Comment by millette** [comment]
See https://github.com/browserify/static-eval/issues/20#issuecomment-468224076

**Comment by millette** [comment]
Should be good to close the issue.

**Comment by Lcfvs** [comment]
Fine, thanks again ;)
