### ISSUE TITLE
Parcel doesn't remove older elements after live reload.

### ISSUE THREAD

**Issue by jnpco** [parcel-bundler/parcel#2648]
# 🐛 bug report
Whenever parcel does a live reload, old elements that are appended to the dom are not removed.

## 🌍 Your Environment
win10, vs_code

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | v10.13.0
| npm/Yarn         | 6.4.1
| Operating System | Windows 10

Code: 
https://github.com/jnpco/d3_parcel

**Comment by mischnic** [comment]
This is a result of how Parcel's HMR works. Something like #289 would be needed in this situation.
Otherwise, you could do this:
```js
if(module.hot)
  module.hot.dispose(function() {
    // remove your old elements / clear container
  });
```
