### ISSUE TITLE
Elm integration tests fail

### ISSUE THREAD

**Issue by outofambit** [parcel-bundler/parcel#2649]
# 🐛 bug report

Elm integration tests fail on `master`(a2e38f9b4d548d24cc38913baaa0947362dad20d)

## 🎛 Configuration (.babelrc, package.json, cli command)

```shellsession
git checkout master
yarn
yarn test
```

## 🤔 Expected Behavior

Tests should pass without error

## 😯 Current Behavior

[elm-test-fail.log](https://github.com/parcel-bundler/parcel/files/2872183/elm-test-fail.log)

## 🔦 Context

Running into this issue as a first time contributor to parcel. I don't have elm installed on my machine and there are no uncommitted changes in my index.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | a2e38f9b4d548d24cc38913baaa0947362dad20d
| Node             | 11.9.0
| npm/Yarn         | 1.13.0
| Operating System | macOS 10.14.3

**Comment by outofambit** [comment]
actually, even after installing elm via `brew`, I am still getting these test failures consistently.

**Comment by domenkozar** [comment]
I'm happy to help if you tell me how to see actual output from elm commands
