### ISSUE TITLE
💬 [RFC] Awesome-parcel

### ISSUE THREAD

**Issue by Ty3uK** [parcel-bundler/parcel#265]
🙋 **feature request**

Hi folks! What about create `awesome-parcel` repository with plugins, docs, etc?
NPM already has 9 plugins, some people write tutorials on medium, habrahabr and another blogs and portals. The project is becoming very popular, maybe it's good idea?

**Comment by Ty3uK** [comment]
**List of published plugins:**
[parcel-plugin-vue](https://www.npmjs.com/package/parcel-plugin-vue)
[parcel-plugin-eslint](https://www.npmjs.com/package/parcel-plugin-eslint)
[parcel-plugin-typescript](https://www.npmjs.com/package/parcel-plugin-typescript)
[parcel-plugin-svelte](https://www.npmjs.com/package/parcel-plugin-svelte)
[parcel-plugin-markdown](https://www.npmjs.com/package/parcel-plugin-markdown)
[parcel-plugin-pug](https://www.npmjs.com/package/parcel-plugin-pug)
[parcel-plugin-bundle-manifest](https://www.npmjs.com/package/parcel-plugin-bundle-manifest)
[parcel-plugin-bucklescript](https://www.npmjs.com/package/parcel-plugin-bucklescript)
[parcel-plugin-inlinesvg](https://www.npmjs.com/package/parcel-plugin-inlinesvg)

**Comment by Ty3uK** [comment]
Also, I started to write article about development of parcel-plugin-pug for Russian habrahabr. I think this will help boost up project popularity.

**Comment by davidnagli** [comment]
I think this is a great idea? Can you please make it.

**Comment by brandon93s** [comment]
Do we want this inside the organization (e.g. parcel-bundler/awesome-parcel)?

**Comment by davidnagli** [comment]
@brandon93s hmmm that’s a good point. I think we should put it in the org, but @devongovett would need to do it

**Comment by Ty3uK** [comment]
I can host it in my repos, but has this page on parcel would be great 👍

**Comment by lc60005457** [comment]
https://github.com/awesome-parcel-bundler/awesome-parcel

**Comment by devongovett** [comment]
This is awesome! 😜 Totally open to making a repo on this org for people to contribute links to if one of you wants to maintain it.

I actually think we should actually bring some of these plugins into core, specifically vue, svelte, markdown, pug, parts of typescript (for angular), and maybe some others too. Thoughts?

**Comment by Ty3uK** [comment]
That would be nice!

**Comment by devongovett** [comment]
@Ty3uK I've created the repo and invited you to the org. You should have write access. Thanks for doing this!!

**Comment by Ty3uK** [comment]
@devongovett Joined! Thanks to you! 🤝

**Comment by devongovett** [comment]
Closing, since https://github.com/parcel-bundler/awesome-parcel exists now!
