### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by rhurstdialpad** [parcel-bundler/parcel#2659]
Wanted to know when the next release is. We just ported our entire frontend over to use parcel, but need a few of the fixes in master not yet in a release. Any chance we can get a release in the next week or so?

**Comment by chrisdingli** [comment]
As an addition to this, who drives these releases and how frequently does it happen? Is it being driven by the features project? The bugs project?

I see v2 project is being tracked as being just over half-done but that could still be a fair while away.

**Comment by chrisdingli** [comment]
PS, @rhurstdialpad you can also clone the repository locally and include the dependency by declaring its file path, e.g.:
```
"devDependencies": {
    "parcel-bundler": "file:./../parcel/packages/core/parcel-bundler"
}
```

This might act as an effective way to unblock your team in the immediate short term.

**Comment by DeMoorJasper** [comment]
The next release is gonna be in a couple days.

Parcel 2 isn't that close but the core is already mostly ready for alpha

**Comment by mischnic** [comment]
Version 1.12.0 was released
