### ISSUE TITLE
Question: Babel through JS API?

### ISSUE THREAD

**Issue by jaredpalmer** [parcel-bundler/parcel#266]
Can someone explain how this works?

I am working on a CLI tool and would like to use Parcel. I'd like to have a default babel setup for users, but then let them override it. Does  Parcel have a way for me to specify babel options through the JS API?

```js
const Parcel = require('parcel-bundler');

const Compiler = new Parcel(
     <entry>,
      {
        outDir: <outdir>,
        watch: true,
//        useBabelrc? 
//        babelOptions?
// How does parcel know which .babelrc it should use?
      }
    );

Compiler.bundle()
```

**Comment by philipodev** [comment]
To bundle it you just run `Compile.bundle()`.

**Comment by jaredpalmer** [comment]
Yeah i got that. I want to understand how .babelrc is resolved

**Comment by DeMoorJasper** [comment]
As far as i know there is no way to do this, you can however provide a default .babelrc in the folder where the users code will eventually end up.
It always searches for the nearest babelrc to the script it's compiling.

**Comment by jaredpalmer** [comment]
Got it.
