### ISSUE TITLE
FSCache keys are based on absolute paths resulting in false misses

### ISSUE THREAD

**Issue by em** [parcel-bundler/parcel#2664]
# 🐛 bug report

It appears that cache keys always miss if the full path has changed, which is something likely to happen in a CI system.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    "es2015",
    "stage-0",
    "react"
  ],
  "plugins": [
    "transform-decorators-legacy",
    "react-hot-loader/babel",
  ]
}
```

## 🤔 Expected Behavior

Cache hits should work regardless of the parent directory path.

## 😯 Current Behavior

1. Take any project
2. `parcel build`
3. `cd ../ && mv my-project my-project2`
4. `cd my-project2`
5. `parcel-build`

Note build time increases dramatically because the cache becomes entirely invalid.

## 💁 Possible Solution

Use paths relative to the project root when building the md5 cache keys.

## 🔦 Context

I've been investigating why build times seem to be the same regardless of the cache on Heroku for some time. And I'm pretty sure this is the cause. And in theory this would affect many CI systems out there.

## 💻 Code Sample

This can be reproduced easily in any project.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | v8.15.0
| npm/Yarn         | 1.13.0
| Operating System | osx 10.14

**Comment by DeMoorJasper** [comment]
Making paths relative to rootDir would probably solve this. Although the rootDir can change if the entrypoint changes and would invalidate everything as well

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by em** [comment]
@DeMoorJasper How about all paths relative to the cache dir? : )

e.g. if the cache dir was `my-project/.cache` then `../src/App.js` would be the key for `my-project/src/App.js`

**Comment by DeMoorJasper** [comment]
That’s probably a good idea as well

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
