### ISSUE TITLE
parcel serve return "You gave us a visitor for the node type ClassPrivateProperty but it's not a valid type"

### ISSUE THREAD

**Issue by rogerta** [parcel-bundler/parcel#2665]
# 🐛 bug report

I am trying out parcel for the first time on my webapp.

## 🎛 Configuration (.babelrc, package.json, cli command)

Parcel is installed in my project with the command:  `yarn add parcel-bundler --dev`

My package.json looks like this:
```js
{
  ...
  "devDependencies": {
    "@types/gapi": "^0.0.35",
    "@types/gapi.client.drive": "^3.0.1",
    "@types/node": "^9.4.6",
    "byline": "^5.0.0",
    "gulp": "^3.9.1",
    "gulp-sourcemaps": "^2.6.4",
    "gulp-typescript": "^4.0.0-alpha.1",
    "gulp-util": "^3.0.8",
    "http-server": "^0.11.1",
    "merge-stream": "^1.0.1",
    "parcel-bundler": "^1.11.0",
    "polymer-cli": "^1.7.4",
    "tap": "^11.0.1",
    "typescript": "^3.1.3"
  },
  "dependencies": {}
}
```

I don't have a babel config.  I have not used babel in the past and parcel is zero config, right ;-)

## 🤔 Expected Behavior

When I run `parcel serve` I should be able to browse my webapp at http://localhost:1234

## 😯 Current Behavior

When I run `parcel serve` I get the following error:
```
$ ./node_modules/.bin/parcel serve -d out/dist2/ out/staging/index.html 
Server running at http://localhost:1234 
🚨  /home/roger/src/out/staging/dice.html: You gave us a visitor for the node type ClassPrivateProperty but it's not a valid type
    at verify (/home/roger/src/node_modules/@babel/helper-replace-supers/node_modules/@babel/traverse/lib/visitors.js:130:13)
    at explode (/home/roger/src/node_modules/@babel/helper-replace-supers/node_modules/@babel/traverse/lib/visitors.js:52:3)
    at Object.merge (/home/roger/src/node_modules/@babel/helper-replace-supers/node_modules/@babel/traverse/lib/visitors.js:165:5)
    at Object.<anonymous> (/home/roger/src/node_modules/@babel/helper-replace-supers/lib/index.js:94:46)
    at Module._compile (/home/roger/src/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
```

## 💁 Possible Solution

Would need more info to say.  Are there any debug command line options I can use or are there any log files I can look at?

## 🔦 Context

I want to use parcel to package my webapp for deployment.  Right now I am using `polymer build` but it only supports single page PWAs.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0 |
| Node             | 8.15.0 |
| Yarn         |  1.13.0 |
| Operating System | Linux 4.19.16-02893-g2cf2c17c8a43 #1 SMP PREEMPT Sat Jan 19 09:52:07 PST 2019 x86_64 GNU/Linux |

**Comment by rogerta** [comment]
I was able to work around this problem by adding:
```
  if (key === "ClassPrivateProperty") return true;
```
to the function `shouldIgnoreKey()` in file `node_modules/@babel/helper-replace-supers/node_modules/@babel/traverse/lib/visitors.js`

I'm not suggesting this is a correct fix, only that it allowed `parcel serve` to run without errors.  The javascript code being served by parcel in this case was compiled from typescript.

**Comment by mdobroggg** [comment]
@rogerta Were you able to solve this? Having a similar issue.

**Comment by DeMoorJasper** [comment]
This might be a babel bug or some bug in a babel plugin if you’re using any

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pdubey84** [comment]
I am seeing this issue too

**Comment by rogerta** [comment]
@mdobroggg, I did not solve this. I'll need to spend more time playing with parcel.

@DeMoorJasper I literally have zero config 😀 so I suspect more it's an internal babel thing inside parcel

**Comment by DeMoorJasper** [comment]
@rogerta We've had some issues with Babel lately.

Hopefully it's fixed now, next minor release should contain fixes. You can also clone the repo and link parcel to test it out.

Can't really do much without a minimal repro repo though

**Comment by rogerta** [comment]
Thanks @DeMoorJasper.  I just again with version 1.12.4 and I no longer see this issue.  I will close this issue
