### ISSUE TITLE
Parcel ignore babelrc for other package in monorepo

### ISSUE THREAD

**Issue by retyui** [parcel-bundler/parcel#2668]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)
All here: https://github.com/retyui/parcel-bag-bable7/

## 🤔 Expected Behavior
Bandler resolve babel configs correctly in lerna monorepo!

## 😯 Current Behavior
core package has own [babel config](https://github.com/retyui/parcel-bag-bable7/blob/master/core/.babelrc.js) and when I run build command I see in the log, this file has been used.
But bandler maybe ignoring this config.
```sh
⠙ Building index.js... --- ADMIN
⠹ Building index.js... --- CORE
🚨  /home/i/all-work/esentai/front-end (копия)/node_modules/core/log/index.js:2:5: This experimental syntax requires enabling the parser plugin: 'classProperties' (2:5)
  1 | export default class Log{
> 2 | 	log = (a) => {
    | 	   ^
  3 | 		console.log('--- a',a);
  4 | 
  5 | 		return a;
 --- ADMIN
 --- ADMIN
 --- CORE
```

## 🔦 Context
Lerna monorepo

## 💻 Code Sample
Example with this bag https://github.com/retyui/parcel-bag-bable7/

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.11.0 |
| Node             | 10.x.x |
| npm/Yarn         | 1.13.0 |
| Operating System | Linux Mint 18 |

**Comment by DeMoorJasper** [comment]
You can add a `source: true` to the package

**Comment by retyui** [comment]
@DeMoorJasper It helps

**Comment by DeMoorJasper** [comment]
Why did you reopen?

Would be happy to help if you are still experience more issues?

**Comment by Cristy94** [comment]
I get the same error: `UnhandledPromiseRejectionWarning: SyntaxError: This experimental syntax requires enabling the parser plugin: 'classProperties'`.

I tried adding `"source": true` to my package.json, problem still occurs.

I have no `.baberc` or `.parcelrc` with a React + TypeScript project.
