### ISSUE TITLE
What if I don't have an index.html

### ISSUE THREAD

**Issue by cizza** [parcel-bundler/parcel#2670]
Hi, there. I have a question about a particular situation. I do use Laravel app and that basically means, I do not have an index.html entry point. I do realize I can specify a .js file as an entry point, but what I really struggle with, is to how can I take an advantage of the development server and hot reloading in this environment? 

I researched google for this set up, but there is actually no mentioning of this anywhere on the web. It feels like, that parcel doesn't exist in the huge Laravel community. 

Any ideas or insights would be appreciated as I LOVE the idea of parcel and the speed it works at. 

Thank you.

**Comment by DeMoorJasper** [comment]
You could run parcel is watch mode `parcel watch ...` if you don’t want the server

If you do want the server you could use it as some kind of local cdn

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mischnic** [comment]
> I do realize I can specify a .js file as an entry point, but what I really struggle with, is to how can I take an advantage of the development server and hot reloading in this environment?

Hot reloading will work if you use a Javascript file as an entry point and then include `localhost:1234/index.js` (depending on your filename) in some html file (which isn't "managed" by parcel).
