### ISSUE TITLE
TypeError: process.hrtime.bigint is not a function

### ISSUE THREAD

**Issue by openjck** [parcel-bundler/parcel#2672]
# 🐛 bug report

Bundled JavaScript which uses `process.hrtime.bigint()` does not work in Node 6, Node 7, Node 8, or Node 9.

I've put together a [repository which demos this issue](https://github.com/openjck/bug-demo-parcel-process.hrtime.bigint).

## 🎛 Configuration (.babelrc, package.json, cli command)

No config files.

**index.html:**

```js
console.log(process.hrtime.bigint());
```

**Commands:**

1. `parcel build --target node index.js`
2. `nvm use 9` (or `8`, or `7`, or `6`)
3. `node dist`

## 🤔 Expected Behavior

This code should work in all versions of Node that Parcel supports (apparently 6+).

## 😯 Current Behavior

```
[...]/bug-demo-parcel-process.hrtime.bigint/dist/index.js:2
console.log(process.hrtime.bigint());
                           ^

TypeError: process.hrtime.bigint is not a function
    at Object.t.Focm ([...]/bug-demo-parcel-process.hrtime.bigint/dist/index.js:2:28)
    at u ([...]/bug-demo-parcel-process.hrtime.bigint/dist/index.js:1:528)
    at [...]/bug-demo-parcel-process.hrtime.bigint/dist/index.js:1:827
    at Object.<anonymous> ([...]/bug-demo-parcel-process.hrtime.bigint/dist/index.js:1:1032)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
```

## 🔦 Context

I'm trying to bundle code for use as a GCP Cloud Function. GCP Cloud Functions only support Node 6 and, in beta, Node 8.

## 💻 Code Sample

https://github.com/openjck/bug-demo-parcel-process.hrtime.bigint

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | 6.16.0, 7.10.1, 8.15.0, 9.11.2
| npm/Yarn         | 3.10.10, 4.2.0, 6.4.1, 5.6.0 (respectively; I'm not sure why my nvm is using a newer version of NPM with Node 8 than Node 9, but that is correct)
| Operating System | macOS Mojave 10.14.3

**Comment by mischnic** [comment]
> This code should work in all versions of Node that Parcel supports (apparently 6+).

This statement applies to running Parcel on your project (e.g. `parcel build ...`).

You have to somehow polyfill `process.hrtime.bigint` or use a different function yourself when running your project on Node 6-9.

Parcel only compiles newer Javascript language features using `babel-preset-env` and doesn't take libraries into account.
