### ISSUE TITLE
Incorrect types provided in @types/parcel-bundler

### ISSUE THREAD

**Issue by GoldenTK** [parcel-bundler/parcel#2673]
Typescript doesn't recognise `bundler.middleware()` in latest types version.
I'm using api from [API](https://parceljs.org/api.html).
Api was changed without docs?

Versions:
```
"@types/express": "^4.16.1",
"@types/parcel-bundler": "^1.10.1",
"parcel-bundler": "^1.11.0",
"typescript": "^3.3.3333"
```

**Comment by mischnic** [comment]
These types aren't maintained by the Parcel team.

It looks like the `middleware` function was never added to the types:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/parcel-bundler/index.d.ts

**Comment by GoldenTK** [comment]
Ohh I see now. Do you have plans to provide own types?

**Comment by mischnic** [comment]
Types were fixed
