### ISSUE TITLE
Page reload doesn't work with lit-element

### ISSUE THREAD

**Issue by lazylazyllama** [parcel-bundler/parcel#2675]
# 🐛 bug report

Im working on a simple single page application build with lit-element. I bundle everything together using parcel and that works pretty good. But in live development, whenever I change something inside of a custom element, the page won't refresh and I geht this issue:
"Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry"

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "scripts": {
    "dev": "parcel watch src/index.html",
    "start": "parcel src/index.html",
    "build": "parcel build src/index.html"
  },
  "dependencies": {
    "lit-element": "^2.0.1",
    "lit-element-router": "^1.0.0"
  },
  "devDependencies": {
    "parcel-bundler": "^1.11.0"
  },
  "browserslist": [
    "Chrome 72"
  ]
}
```

## 🤔 Expected Behavior

The custom element should be reloaded and I should just see the changes I made.

## 😯 Current Behavior

I get this error message instead:
"Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry"
And there is no reload. If I refresh the page myself, everything works just fine... until I change something else.

## 💁 Possible Solution

No idea :(

## 🔦 Context

I also tried out my project on webpack and everything works there, except I don't like how webpack manages assets etc.
So it seems to be a parcel issue.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | 11.10.0
| npm        | 6.7.0
| Operating System | Windows 10

**Comment by mischnic** [comment]
I'm guessing you have a call like this somewhere in your project: `customElements.define('popup-info', PopUpInfo);` and don't have hot module reloading enabled in your webpack config.

I think webpack reloads the whole page by default while Parcel does hot reloading (in this case re-execute the Javascript). https://github.com/parcel-bundler/parcel/issues/289#issuecomment-354583578 describes how to setup your project to reload the page completely without HMR: add this
```js
if (module.hot) {
  module.hot.accept(function () {
    window.location.reload();
  });
}
```
