### ISSUE TITLE
 why there is not difference between using the cache option or not in middleware？

### ISSUE THREAD

**Issue by lastnigtic** [parcel-bundler/parcel#2679]
# ❔ why there is not difference between using the cache option or not in middleware？

## 🔦 Context

It took same time whether the cache option is ture or false

## 💻 Code Sample

```
const options = {
  outDir: path.resolve('dist'),
  outFile: 'index.html',
  publicUrl: './dist',
  watch: true,
  cache: true, // there is no difference between true or false
  hmrHostname: 'localhost',
  cacheDir: path.resolve('dist', '.cache'),
  logLevel: 3
}

async function start() {
  const bundler = new Bundler(file, options)

  app.use(express.static('./'))

  app.use(bundler.middleware())

  app.listen(8080)
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v1.11.0
| Node             | v10.15.0
| npm/Yarn         | npm
| Operating System | macOs v10.14.3

**Comment by mischnic** [comment]
> It took same time whether the cache option is true or false

Which *time* do you mean? This caching options saves the cache which Parcel uses inbetween builds to the disk, therefore having a fast time to first bundle on subsequent invocations.

**Comment by lastnigtic** [comment]
![image](https://user-images.githubusercontent.com/17680884/53337352-1f739400-393c-11e9-87a7-d64ff7df3adf.png)
I mean this time.
when I am using parcel in cli, it can save about 14+s after first build
But just save about 2-3s in middleware

**Comment by geoynomous** [comment]
Maybe little off-topic - but related - when using the **middleware** (with watch on) the js files get updated (also getting a new hash), but the src-entries in the html entry-points stay unchanged (as well as the filename). All works well when using the **CLI**. Should I open a new issue?
