### ISSUE TITLE
Missing .pcss syntax support

### ISSUE THREAD

**Issue by hzlmn** [parcel-bundler/parcel#268]
Hi, PostCSS officially  has `.pcss` as [suported](https://github.com/github/linguist/pull/3916) extension. 

Would be great to add support of it to `Parcel` as well.

If you consider it as an addition i could work on PR.

**Comment by DeMoorJasper** [comment]
Should be easy to implement, you can work on it and make a PR if you want

**Comment by albinotonnina** [comment]
I implemented it in the website quickly: https://github.com/parcel-bundler/website/pull/31
Must be easy :)

**Comment by chee** [comment]
Oh ! sorry, i didn't notice you'd said you intended to work on the pr.

**Comment by hzlmn** [comment]
@chee It's ok, it's very simple PR :)
