### ISSUE TITLE
Parcel not recognize importScript on service worker file

### ISSUE THREAD

**Issue by HabelJustin** [parcel-bundler/parcel#2683]
# 🙋 feature request

## 🤔 Expected Behavior
service worker file should recognize import script (importScripts('./myFile.js'))

## 😯 Current Behavior
service worker file cannot define import script after build process

## 💻 Examples
importScripts('./myUtils.js');

// function from import sccript
function transformData(){..}

**Comment by devongovett** [comment]
This should work in Parcel 2
