### ISSUE TITLE
Hot reloading CSS modules results in multiple insertions/delayed update.

### ISSUE THREAD

**Issue by JakeCooper** [parcel-bundler/parcel#2684]
# 🐛 bug report

When using hot reloading with css (in this case scss) modules, when a user hits save, a link will be added to the page with the correct link to the css location + Date.now(). 
![image](https://user-images.githubusercontent.com/5499880/53392067-2787ff80-394d-11e9-9f20-7f33f29b57d3.png)

However, since the old link is not removed, it won't hot reload. After hitting save again, these links will both update.
![image](https://user-images.githubusercontent.com/5499880/53392083-37074880-394d-11e9-810a-b4035b68661e.png)

## 🎛 Configuration (.babelrc, package.json, cli command)

.postcssrc
```
{
  "modules": true,
  "plugins": {
    "autoprefixer": {
      "grid": true
    },
    "postcss-modules": {
      "generateScopedName": "[name]_[local]_[hash:base64:5]"
    }
  }
}
```

## 🤔 Expected Behavior

Only one (maybe 2) link(s) should appear in the elements table. SCSS should be hot reloaded.

## 😯 Current Behavior
These will add 2, 4, 8, etc links until the browser slugs to a halt and the tab crashes.
![image](https://user-images.githubusercontent.com/5499880/53391590-b09e3700-394b-11e9-926e-f34165227fe1.png)

## 💁 Possible Solution

It appears adding a breakpoint inside of css-loader.js at line 9 will resolve this. My theory is that there's some sort of race condition, and the 50 milliseconds you have on the cssTimeout isn't ample time. Might be better at 100? Haven't been able to test it locally, but I'll update if I do.

## 🔦 Context

Seems to happen when you hot reload css (or scss in this case) modules.

## 💻 Code Sample

Private repo. I can make a local test environment if you guys aren't able to reproduce it.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v1.11.0
| Node             | v10.15
| npm/Yarn         | v6.4.1
| Operating System | Fedora 29

**Comment by mischnic** [comment]
> Private repo. I can make a local test environment if you guys aren't able to reproduce it.

Please do!

**Comment by aguilera51284** [comment]
same problem here :(!

**Comment by aguilera51284** [comment]
any status for this bug :O!?
