### ISSUE TITLE
Is there a way to preserve the resources urls?

### ISSUE THREAD

**Issue by Lcfvs** [parcel-bundler/parcel#2686]
# ❔ Question

Is there a way to preserve the resources urls?

## 🔦 Context

I need to preserve the resource urls, like for fonts, images, etc., because I manage them with another tool.

How to ignore them, please? (just don't touch the urls and, if possible, to not copy them too)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | 8.5.0
| npm/Yarn         | 6.7.0
| Operating System |

**Comment by mischnic** [comment]
Closing as duplicate of #1186
