### ISSUE TITLE
`--no-source-maps` doesn't work if source maps are cached

### ISSUE THREAD

**Issue by DeMoorJasper** [parcel-bundler/parcel#2692]
# 🐛 bug report

Continuation of #2079 

> I am still seeing this issue on parcel-bundler 1.11.0.
> 
> 1. If I build with source maps, then `rm -r dist/` and build with `--no-source-maps`, then I still get source maps in `dist/`
> 2. If I then `rm -r .cache/ dist/` to remove both the cache and dist and build again with  `--no-source-maps`, then I get it without source maps
> 
> ```shell
> ./node_modules/.bin/parcel --version
> 1.11.0
> ```

by @mrcoles

## 🎛 Configuration (.babelrc, package.json, cli command)

```shell
parcel build index.js --no-source-maps
```

## 🤔 Expected Behavior

should not package sourcemaps

## 😯 Current Behavior

Packages cached sourcemaps

## 💁 Possible Solution

check if sourcemaps should be made in packaging

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11
| Node             | 10
| npm/Yarn         | latest
| Operating System | OS X

**Comment by mischnic** [comment]
@DeMoorJasper This is the very last issue I have with the CSS source maps PR, I also proposed two possible solutions, but I'm not sure which is better: https://github.com/parcel-bundler/parcel/pull/2489#issuecomment-466701252

**Comment by DeMoorJasper** [comment]
@mischnic not sure if always creating a sourcemaps on asset lvl is a good idea as it will impact performance on builds as it’s unlikely someone will change between no sourcemaps and sourcemaps a lot. 
Only outputting sourcemaps bundles if sourcemaps are enable seems like the best idea, but the flag shouldn’t invalidate cache afaik as packaging isn’t cached

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mischnic** [comment]
> not sure if always creating a sourcemaps on asset lvl is a good idea, it will impact performance on builds and it’s unlikely someone will change between no sourcemaps and sourcemaps a lot.

This would mean: invalidate the cache based on the flag because assets are cached

> but the flag shouldn’t invalidate cache afaik as packaging isn’t cached

A contradiction?

**Comment by DeMoorJasper** [comment]
@mischnic yeah just realised that switching from no sourcemaps to sourcemaps would have unexpected results of sourcemaps flag is not part of cache. Thinking about that it would probably need to invalidate I guess, depends on how much impact sourcemaps would have on performance

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mischnic** [comment]
> depends on how much impact sourcemaps would have on performance.

|                         | w/ sourcemaps | w/o sourcemaps |
|-------------------------|---------------|----------------|
| react boilerplate       | 6.57s         | 5.64s          |
| reproduction from #2685 | 127.62s       | 72.00s         |

Opting for invalidation (to keep these values).

**Comment by nVitius** [comment]
@mischnic @devongovett Can you guys expand on why this issue was closed? It doesn't make sense to have an option to not build source maps and then proceed to include them anyways. In my case, I want source maps to be generated for development. But I don't want them to be generated for my build that goes out to production as they essentially double my app size. I don't see why I should have to clear the cache every time I want to make my production build. Am I just thinking about this the wrong way?
