### ISSUE TITLE
Support React fragment short syntax without configuration

### ISSUE THREAD

**Issue by dburles** [parcel-bundler/parcel#2697]
# 🙋 feature request

It would be awesome to not have to explicitly configure support for React fragment [short syntax](https://reactjs.org/docs/fragments.html#short-syntax).

## 🤔 Expected Behavior

It should require no configuration!

## 😯 Current Behavior

It requires configuration.

Example:
```
  "babel": {
    "plugins": [
      [
        "@babel/plugin-transform-react-jsx",
        {
          "pragmaFrag": "React.Fragment"
        }
      ]
    ]
  },
```

**Comment by dburles** [comment]
The irony when you see that the very latest commit actually corrects this! https://github.com/parcel-bundler/parcel/commit/27f769a02ad9a54f8c1bac13961068cd34cdfd03

**Comment by YevhenKap** [comment]
I'm experiencing the same behavior in Parcel `v2.0.0-rc.0` 😟
