### ISSUE TITLE
parcel generating multiple output files 🤔

### ISSUE THREAD

**Issue by avierr** [parcel-bundler/parcel#2704]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
parcel src/App.js src/App.css --out-dir ../../resources/static/dashboard --out-file dashboard
```

## 🤔 Expected Behavior

I am expecting to see the following files:
dashboard.css
dashboard.js

## 😯 Current Behavior

currently I see:

App.css
App.js
dashboard.css
dashboard.js

App.css & dashboard.css have the same content

Both the JS file are different

contents of generated App.js : https://pastebin.com/jc6Sj5AL
contents of generated dashboard.js : https://pastebin.com/5dq9c1Y5

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  latest
| Node             | latest
| npm/Yarn         | npm
| Operating System | mac

**Comment by mischnic** [comment]
> I am expecting to see the following files:
dashboard.css
dashboard.js


You can't use the `--out-file` flag with multiple entrypoints. But the output should still not 4 files instead of 2...

**Comment by mischnic** [comment]
I get these files:
```
App.css
App.css.map
dashboard.js
dashboard.js.map
```
Only the first file gets renamed, but is not what really wanted.

**Comment by avierr** [comment]
> You can't use the --out-file flag with multiple entrypoints. But the output should still not 4 files instead of 2...

It works perfectly, I don't really mind this bug to be called a feature!
(apart from the two extra files, which I don't know what they are generated for)
