### ISSUE TITLE
Problem with url images from another server (API REQUEST)

### ISSUE THREAD

**Issue by rotirotirafa** [parcel-bundler/parcel#2711]
# ❔ Question

im getting this message when i try to build my app: ENOENT: no such file or directory, open '/Users/rotiroti/Projects/nasa-day-image/{{infoImage.url}}'

## 🔦 Context

I just consumes an api from nasa that shows an image.
I dont save the image in project path, so why this happen?
This just happen using parcel 

## 💻 Code Sample
a just call the image like this: <img src="{{infoImage.url}}" alt="{{title}}" >

## 🌍 Your Environment
simple angularjs 1.7.7

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | 10.15.1
| npm/Yarn         | 6.8.0
| Operating System | mac OSX

**Comment by devinrhode2** [comment]
wish I could just tell parcel to ignore these errors, and just display a warning.. and still compile/display the app

**Comment by devinrhode2** [comment]
In my situation, what I think I'll have to do is go back to this monster thread on fixing sass imports, and actually setup a real sass importer via some sort of .sassrc.js file

**Comment by rotirotirafa** [comment]
@devinrhode2  im trying to get an image from url, all works without build the application, but when i build, doest work.

**Comment by devinrhode2** [comment]
I think webpack 3 or 4 with hmr could be a better alternative to parcel... what are your thoughts?

**Comment by rotirotirafa** [comment]
i just want to build my application and host on github pages: https://rotirotirafa.github.io/nasa-day-image/ . Im studying api consumption with angularjs
