### ISSUE TITLE
[ts] Conditional dynamic import not reflected when building

### ISSUE THREAD

**Issue by Regaddi** [parcel-bundler/parcel#2713]
# 🐛 bug report

Basically the same, as in #899, but with TypeScript.
When a dynamic import is made inside of an env conditional like `if (process.env.NODE_ENV !== 'production') {` the import is also resolved when `NODE_ENV=production`.

## 🤔 Expected Behavior

Dynamic imports shouldn't be resolved inside of noop conditionals.

## 😯 Current Behavior

File is imported, code inside is not run, but the bundle size is still affected because of the import.

## 🔦 Context

Writing an API with optional `mock` flag, that (if enabled) will return fake data using faker instead of actually calling REST services. This shouldn't be included on production builds.

## 💻 Code Sample

I've set up a minimal reproduction repo here: https://github.com/Regaddi/parcel-ts-dynamic-import

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0 |
| Node             | 8.12.0 |
| yarn         | 1.13.0 |
| Operating System | Mac OS 10.14.3 |
| TypeScript | 3.3 |

**Comment by garthenweb** [comment]
Could you check if #2650 fixes this for you? As far as I can see this is not typescript related but I had the issue as well.

**Comment by Regaddi** [comment]
Hey @garthenweb,

I checked out your branch and built with your version.
Unfortunately the issue still exists. `console.log("this is a mock")` is still in the generated js file.

**Comment by garthenweb** [comment]
Thanks for taking the time to verify! Then it is probably something else that I run into...

**Comment by mischnic** [comment]
I don't have a solution, but this happens because the async code is transpiled into generators and the resulting code is way too complex (see [Typescript Playground](http://www.typescriptlang.org/play/index.html#src=const%20main%20%3D%20async%20function()%20%7B%0D%0A%20%20if%20(process.env.NODE_ENV%20!%3D%3D%20%22production%22)%20%7B%0D%0A%20%20%20%20const%20%7B%20mockMe%20%7D%20%3D%20await%20import(%22.%2Fmock%22)%3B%0D%0A%20%20%20%20mockMe()%3B%0D%0A%20%20%7D%0D%0A%20%20console.log(%22ENV%3A%22%2C%20process.env.NODE_ENV)%3B%0D%0A%7D%3B%0D%0A%0D%0Amain()%3B)).
```js
const main = async function() {
  if (process.env.NODE_ENV !== "production") {
    const { mockMe } = await import("./mock");
    mockMe();
  }
  console.log("ENV:", process.env.NODE_ENV);
};

main();
```
I tried disabling the async transpilation using tsconfig's `compilerOptions.target`, but it doesn't seem possible.

**Comment by garthenweb** [comment]
@mischnic I think you also need to set the module flag: `tsc --module esnext --target esnext ./main.ts`. This will more or less return the same content:

```javascript
const main = async function () {
    if (process.env.NODE_ENV !== "production") {
        const { mockMe } = await import("./mock");
    }
};
main();
```

**Comment by evanemolo** [comment]
I realize this issue is stale at this point, but I am currently running into this problem — in a `.ts` file I have something akin to:

```
if (process.env.NODE_ENV === 'development') {
    if (window.integrationTest) {
      const { getMockData } = await import(
        './mocks/get-mock-data'
      )
      const data = getMockData()
      return data
    }
}
```

`parcel build` will generate a .js file specific to `get-mock-data` regardless of being wrapped in the code elimination block.

**Comment by DeMoorJasper** [comment]
This should be fixed in parcel 2, could you check this @evanemolo ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by evanemolo** [comment]
Unfortunately I can't confirm. Using Parcel gives the following error when running `build`: `@parcel/namer-default: Destination name index.js extension does not match bundle type "html"`
