### ISSUE TITLE
Vue SFC with Typescript has incorrect JS sourcemap

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#2720]
# 🐛 bug report

A Vue single file component with a typescript script shows incorrect line numbers.

## 🤔 Expected Behavior

When the `console.log` statement is displayed, the correct `app.vue:...` line number should be displayed.

## 😯 Current Behavior

Wrong line number (IIRC: 14 instead of 7).

## 💁 Possible Solution

Note: this only happens with `<script lang="ts">`, `<script lang="js">` works correctly!

## 💻 Code Sample

```html
<!-- app.vue -->
<template lang="pug">
  .container Hello {{bundler}}
</template>

<script lang="ts">
import Vue from "vue";
console.log("hello!");
export default Vue.extend({
  data() {
    return {
      bundler: "Parcel"
    };
  }
});
</script>

<style lang="scss" scoped>
.container {
  color: green;
}
</style>
```

```js
// index.js
import Vue from 'vue';
import App from './app.vue';

new Vue(App).$mount('#app')
```

```html
<!-- index.html -->
<div id="app"></div>
<script src="./index.js"></script>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |master
| Node             |11
| npm/Yarn         |
| Operating System |macOS

**Comment by mischnic** [comment]
Strange, this works now....

**Comment by asvishnyakov** [comment]
I have the same issue
