### ISSUE TITLE
Browser opens different URL

### ISSUE THREAD

**Issue by ofk** [parcel-bundler/parcel#2725]
# 🐛 bug report

Running `parcel serve index.html --host 0.0.0.0 --open`, the browser opens a different URL.

## 🎛 Configuration (.babelrc, package.json, cli command)

None.

## 🤔 Expected Behavior

The browser opens `https://0.0.0.0:1234/` .

## 😯 Current Behavior

The browser opens `https://localhost:1234/` .

**Comment by ai** [comment]
I need the same feature for `--host test.localhost` to open `https://test.localhost:1234` on `--open`

**Comment by mischnic** [comment]
Relevant section (localhost is currently hardcoded):
https://github.com/parcel-bundler/parcel/blob/f562ce6fd8b91220d61fbb5eedc6d76df9886b9f/packages/core/parcel-bundler/src/cli.js#L226-L231
