### ISSUE TITLE
names of separate output files while using API

### ISSUE THREAD

**Issue by Jax-p** [parcel-bundler/parcel#2726]
# ❔ Question

How can I change the output names of separate output files while using API?

## 🔦 Context

I've tried to create own Asset to do this and I wanted to overload function generateBundleName (is this right solution?). But included Asset doesn't seem to be working.

my Asset: 
```
const { Asset } = require('parcel-bundler')
class ProcessAsset extends Asset
{
    generateBundleName(isMainAsset) {
        console.log('aa'); // can't see this log anywhere
    }

    async postProcess(generated) {
        console.log('bb');  // can't see this log anywhere
    }
}
module.exports = ProcessAsset;
```

and part of my API bundler:
```
(async function() {

  const bundler = new Bundler(['client/front.entry.js','client/admin.entry.js'], options);
  bundler.addAssetType('.ext', require.resolve('./processAsset'));

  bundler.on('bundled', (bundle) => {
    //... something cool
  });

  bundle = await (args.serve ? bundler.serve() : bundler.bundle());

})();
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | 10
| npm/Yarn         | npm
| Operating System | MacOS

**Comment by DeMoorJasper** [comment]
Using outFile in options

`outFile: 'index.html', // The name of the outputFile `

**Comment by Jax-p** [comment]
I use 2 entry points, both generating .css and .js files (front.js, front.css etc.). No .html file included.

**Comment by mischnic** [comment]
The `outFile` option only applies to the first entry point, all other remain unchanged.

**Comment by VitaliyR** [comment]
@mischnic that's pitty, anything in roadmap/plans to support this functionality?
