### ISSUE TITLE
🙋 Configuring uglify

### ISSUE THREAD

**Issue by chee** [parcel-bundler/parcel#273]
🙋 🙋 🙋 🙋 🙋 🙋 🙋 🙋 🙋 🙋 🙋 🙋 feature request

I have a problem. When uglify was trouble, I was minifying the code myself after the build step, which was fine. But now I've updated to newer Parcel, and would like to have it take care of the minification for me. However, the [top-level mangle](https://github.com/parcel-bundler/parcel/blob/master/src/transforms/uglify.js#L11-L13) is causing issues with this particular codebase.

If this were something in babel or in postcss, i could sneak into their `.rc` files and make my choices, but uglify doesn't have any kind of an `.uglifyrc` so I'm locked out of this part of the process.

### 💁 Possible Solution

@DeMoorJasper suggested we could pretend there was such a thing as an `.uglifyrc` and process that, which seems pretty good but is certainly unorthodox. It would be nice for this not to be a configuration option for parcel, but for it to be tied (in essence at least) to uglify itself.

**Comment by davidnagli** [comment]
@chee @DeMoorJasper What would be the syntax / available options for this new `.uglifyrc`?

**Comment by brandon93s** [comment]
uglify already supports a `--config-file` CLI option to pass JSON as the options for `minify()`. Presumably, all options would be supported if the map to the options object correctly.
