### ISSUE TITLE
JS Inline Sourcemaps

### ISSUE THREAD

**Issue by ctsstc** [parcel-bundler/parcel#2733]
# 🙋 feature request

I would like to have sourcemaps inline at the bottom of my JS files.

## 🤔 Expected Behavior

Instead of building out a map file it would put the source mapping into the source file at the bottom of it/inline.

## 😯 Current Behavior

Currently all map files are generated alongside the built file(s).

## 💁 Possible Solution

Utilize babel config options if parcel is using babel.

## 🔦 Context

I've tried adding a `.babelrc` with the following for inline JS but it didn't do anything. It could be nice to see what the resulting babel config is that parcel uses for debugging purposes. I'm assuming parceljs builds out its own babel config and uses babel.

```
{
  "presets": [
    ["@babel/preset-env", {
      "sourceMaps": "inline"
    }]
  ]
}
```

**Comment by johnjiang** [comment]
@DeMoorJasper, how do we enable this in the current parcel 2 beta 1?

**Comment by DeMoorJasper** [comment]
You have to configure the targets as stated in the PR, there's some basic docs about how it works: https://v2.parceljs.org/getting-started/configuration/#targets

Should look something like this:
```json
{
  "targets": {
    "app": {
      "distDir": "./www",
      "sourceMap": {
        "inline": true
      }
    }
  }
}
```
