### ISSUE TITLE
Auto Remove Unused Dependencies

### ISSUE THREAD

**Issue by ctsstc** [parcel-bundler/parcel#2734]
# 🙋 feature request

Parcel does a great job of auto installing dependencies, but over time you can be left with the clutter of unused dependencies.

I would like to be able to auto remove dependencies that my project is no longer using. I believe there are some libraries out there that already do this.

## 🤔 Expected Behavior

Maybe it would need to be prompted, an additional flag, and/or interactive. It could be possible too that there would need to be a whitelist for cases where it's too aggressive and the user needs to keep them due to another entrypoint that is utilizing it in the project. 

It may have to do a full project analyze to determine unused resources? Because the given entrypoint may not describe the full project.

## 😯 Current Behavior

Dependencies auto install but never clean up.

## 💁 Possible Solution

It may be best to utilize one of these packages possibly or utilize their source code. I'm not sure of the scope of them. I also Believe Parcel has its own tree shaking and dependency collection that could help out with this matter.

- https://www.npmjs.com/package/npm-check
- https://www.npmjs.com/package/depcheck

## 🔦 Context

Just an idea to prevent clutter, and thought it would be a nice feature to pair with auto install (:

**Comment by mischnic** [comment]
> I also Believe Parcel has its own tree shaking and dependency collection that could help out with this matter.

I don't think this would be very reliable, e.g. the `serve` or `now` package is never used from your code.
