### ISSUE TITLE
Incorrect svg filepath

### ISSUE THREAD

**Issue by wesflynn** [parcel-bundler/parcel#2736]
# 🐛 bug report

After updating to the latest version of Parcel (1.12.0) svg images no longer load properly due to the wrong paths being generated.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["@babel/env", "@babel/react"],
  "plugins": ["@babel/plugin-proposal-class-properties","react-hot-loader/babel","@babel/plugin-transform-runtime"]
}
```

## 🤔 Expected Behavior

Generated links should look like:
```html
<img alt="logo" src="./logo_color.7e674228.svg" class="Component-logo-64">
```

## 😯 Current Behavior
Links generated by the newest version of Parcel:
```html
<img alt="logo" src="/....logo_color.7e674228.svg" class="Component-logo-64">
```

## 💻 Code Sample

```js
import logo from "./Images/logo_color.svg";
...
<img alt={"logo"} src={logo} className={classes.logo} />
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
Could you please post the `img` tag of your source code (esp. the src tag)?

**Comment by wesflynn** [comment]
alright here's what my source looks like...
```js
import logo from "./Images/logo_color.svg";
...
<img alt={"logo"} src={logo} className={classes.logo} />
```

**Comment by GioLogist** [comment]
+1

**Comment by garth** [comment]
This issue seems to affect all asset types that are referenced from css, not just svg. The files are output correctly into the build folder but the paths in the css are output in a relative format instead of absolute as specified by `--public-url`.

Had to revert back to v1.11 for now.

**Comment by GioLogist** [comment]
For added context, I also received this error when referencing an `img` via `require`

**Comment by VincentGJ** [comment]
+1

**Comment by philcockfield** [comment]
+1

**Comment by herkyl** [comment]
Seeing similar behaviour in Parcel 1.12.4, in CSS I'm importing an svg like so `url('../assets/icon.svg')`

The minified svg file gets put to the root `dist` directory however the the minified CSS file tries to load it from `dist/style/`

**Comment by Mishra-Suraj** [comment]
Any updates on this? I am on Parcel 2.0.0-nightly.354 having the same problem.
