### ISSUE TITLE
Release Documentation

### ISSUE THREAD

**Issue by ctsstc** [parcel-bundler/parcel#2739]
# 💬 RFC

As a developer I would like to know what changes between releases. It would be nice to have a summary of what's changing between releases.

## 🔦 Context

I love to see what new features are incoming as well as any breaking changes. Currently there's no information on releases.

## 💻 Examples

Even just a list of issues that were closed during the release or linking to an associated milestone would be nice.

So far the only information I've come across is some Medium articles which are fantastic, but there's no link from the github to these either. Currently you just have to get lucky and stumble across them.
https://medium.com/@devongovett

**Comment by mischnic** [comment]
-> https://github.com/parcel-bundler/parcel/blob/master/CHANGELOG.md
