### ISSUE TITLE
[ Question ] 'parcel' command don't transform es6 to es6.

### ISSUE THREAD

**Issue by pacebook** [parcel-bundler/parcel#275]
Thanks for the great proejct !

### 😯 Current Behavior

When I executed `parcel build` command, the bundled js file is in es6. 

But when I executed `parcel watch` or `parcel` command, the bundled file still contains es6.

### 🤔 Expected Behavior

I want it to be automatically reloaded when the file changes and transformed into es5.

### 🤔 Question
When running `parcel` or `parcel watch`, I wonder if there is an option to transform es6.
Thank you !

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  1.1.0
| Node             |  9.2.1
| npm         | 5.5.1
| Operating System | windows7

**Comment by JackDeMeyers** [comment]
I think Parcel may read the tsconfig.json file, where you can set the compile target to es5. Someone else would need to confirm though.

**Comment by pacebook** [comment]
I resolved this issue by `.cache` directory removes. When `.cache` directory created at first, my project was not includes `.babelrc`. Because of this, it seems that after adding `.babelrc ', it was not built into es5.
