### ISSUE TITLE
How can I avoid this minification problem?

### ISSUE THREAD

**Issue by reebr** [parcel-bundler/parcel#2750]
I've the following code:

```pug
script.
    window.components = window.components || {}

if development
    script.
        window.components.s = 'development-sessionid'
        window.components.cli = 'dev'
    script(src='https://services.me/development-script.js')
else
    | {% if sessionid %}
    script.
        window.components.s = '{{ sessionid }}'
        window.components.cli = 'prod'
    script(src='https://services.me/production-script.js')
    | {% endif %}
```

When I use `parcel build --no-minify myfile.pug`, I got the expected result:
```html
<script>window.components = window.components || {};</script>
{% if sessionid %}
<script>window.components.s = '{{ sessionid }}';
window.components.cli = 'prod';</script>
<script src="https://services.me/production-script.js"></script>
{% endif %}
```

But when I run `parcel build myfile.pug` (without disable minification), the output is:
```html
{% if sessionid %}
<script>
window.components =window.components ||{},window.components.s="{{ sessionid }}",window.components.cli="prod",window.login=window.login||{},window.login.error="{{ login_error }}";
</script>
{% endif %}
```

⚠️ *I broke the lines to improve the visualization*

All `window` objects are getting grouped in a strange way, including other properties defined in other files. Is there any configuration that disables it?

**Comment by reebr** [comment]
I don't know if it is the best solution, but solved creating a `.htmlnanorc` file with:

```json
{
    "mergeScripts": false
}
```

**Comment by mischnic** [comment]
So `{% if sessionid %}` is going to be resolved by your server (or by some other program) and therefore the separate script tags are important.

I don't think there is a better solution and I don't know how niche this issue is. There are also other problems related to server templates (like having template in `src` tags).

**Comment by reebr** [comment]
@mischnic I understood. Maybe I added too much complexity in the issue for having placed the content between  `{% if sessionid %}`. But, the real problem here is that the final file, after being processed by Parcel was grouping all the initialization `window` objects.

```pug
//- base.pug
head
   block head
body
   block body
```

```pug
//- index.pug
extends base

block head
   script.
      window.a = window.a || {}
      window.a.content = "valueA"

block body
   block innerbody
```

```pug
//- otherfilethatextendsindex.pug
extends index

block innerbody
   script.
      window.b = window.b || {}
      window.b.content = "valueB"
```

The expected output was:
```html
<head>
  <script>
      window.a = window.a || {}
      window.a.content = "valueA"
  </script>
</head>
<body>
   <script>
      window.b = window.b || {}
      window.b.content = "valueB"
   </script>
</body>
```

But it resolves to (minifed):
```html
<head>
  <script>
      window.a = window.a || {}, window.a.content = "valueA", window.b = window.b || {}, window.b.content = "valueB";
  </script>
</head>
<body>
</body>
```

There were properties that necessarily needed to be  initialized at the end of the document and minification was grouping/starting everything in the `<head>`. The configuration I found closest to the problem that was occurring was that of the htmlnano [`"mergeScripts": false`](https://github.com/posthtml/htmlnano#mergescripts).

**Comment by mischnic** [comment]
> Maybe it's not a problem

The merging of scripts in the head and in the body could indeed cause issues.
