### ISSUE TITLE
`Failed to decode downloaded font` when referencing font stylesheets directly  from `node_modules`

### ISSUE THREAD

**Issue by r0skar** [parcel-bundler/parcel#2754]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// package.json
{
  "dependencies": {
    "inter-ui": "^3.3.4",
    "parcel-bundler": "^1.12.0"
  },
  "scripts": {
    "parcel": "parcel src/index.html"
  }
}
```

```html
<!-- src/index.html -->
<!DOCTYPE html>
<html>
  <head>
    <title>parcel-fonts</title>
    <link rel="stylesheet" href="../node_modules/inter-ui/inter.css">
    <style>
      body {
        font-family: 'Inter';
      }
    </style>
  </head>
  <body>
    <h1>parcel-fonts</h1>
  </body>
</html>
```

## 🤔 Expected Behavior

Display text with the correct font.

## 😯 Current Behavior

Font is not being used and Chrome outputs following warnings:

```
Failed to decode downloaded font: http://localhost:1234/parcel-fonts/Inter-Bold.5dcf194e.woff2
OTS parsing error: invalid version tag
Failed to decode downloaded font: http://localhost:1234/parcel-fonts/Inter-Bold.65dad7f9.woff
OTS parsing error: invalid version tag
```

## 💁 Possible Solution

Not really a solution, but the code above works just fine, when the fonts are placed in the `src` folder and referenced like this: `<link rel="stylesheet" href="inter-ui/inter.css">`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.0
| Node             | 11.10.0
| yarn         | 1.13.0
| Operating System | Linux 4.20

**Comment by krnlde** [comment]
Can confirm with Parcel 1.12.0, in 1.11.0 it works.

**Comment by mischnic** [comment]
Fixed by https://github.com/parcel-bundler/parcel/pull/2740
