### ISSUE TITLE
Possible to control the output folder names?

### ISSUE THREAD

**Issue by thecodejunkie** [parcel-bundler/parcel#2755]
# ❔ Question

Is it possible to control the names of output folders when using the Bundle API? I'm using it to process JavaScript and SASS file that are stored in the following structure

```
src
├───js
└───sass
```

When i run the bundler on them, they're outputted with the same folder names as the source folders that I enter in the `entriesFiles` parameters.

```
dist
├───js
└───sass
```

Anyway to change this? Either by parameters (can't seem to find anything) or by hooking into the events etc. to override it?

## 🔦 Context

Since I'm transpiling SASS -> CSS I want the output files to end up in a folder called CSS, not SASS. Having the output folder called SASS does not make sense since it contains processed files.

## 💻 Code Sample

This is the code I run

```
const Bundler = require('parcel-bundler');
const path = require('path');

const entryFiles = [
    path.join(__dirname, './js', 'index.js'),
    path.join(__dirname, './sass', 'bundle.scss')
];

const shouldMinify = () => {
    return process.env.NODE_ENV === 'production';
};

const options = {
    cache: true,
    detailedReport: true,
    minify: shouldMinify(),
    sourceMaps: true,
    watch: false
};

(async function () {
    await (new Bundler(entryFiles, options)).bundle();
})();
```

## 🌍 Your Environment

| Software         | Version(s) |
| --------------- |----------- |
| Parcel             | 1.10.3
| Node              | 10.13.0
| Operating System | Windows / macOS

**Comment by thecodejunkie** [comment]
@DeMoorJasper any update on this?

**Comment by devongovett** [comment]
This has come up many times in the past. Please search the issues before posting. E.g. https://github.com/parcel-bundler/parcel/issues/233

It will be possible in Parcel 2 by overriding the default namer plugin.

**Comment by GrantBartlett** [comment]
Are there any solutions with Parcel 1 as of current, or just not at all possible?
