### ISSUE TITLE
How to set localhost domain

### ISSUE THREAD

**Issue by ai** [parcel-bundler/parcel#2756]
Thanks for the great tool. I am not sure, is it a feature request or documentation issue.

1. We need to test Web Audio and we need to HTTPS for it (it is only way to force browser remember audio access policy).
2. I created HTTPS certificates for `test.localhost` and use them in Parcel `--cert ./builder/server.pem --key ./builder/server-key.pem`.
3. I added `test.localhost` to `/etc/hosts`.
4. I also added `--host test.localhost` and `--open`
5. When I start Parcel it still open `https://localhost:1234` instead of `https://test.localhost:1234`.

Maybe I use `--host` option wrong and I need to use another argument?

Or maybe Parcel doesn’t have a way to set domain which will be used in `--open` and we need to add it to CLI?

**Comment by mischnic** [comment]
Does it work if you open `tes.local:1234` "manually"? The `--open` flag is indeed not taking the host option into account: #2725

**Comment by ai** [comment]
> Does it work if you open test.local:1234 "manually"?

Yes

**Comment by ai** [comment]
I am closing it as duplicate https://github.com/parcel-bundler/parcel/issues/2725
