### ISSUE TITLE
 EMFILE: too many open files

### ISSUE THREAD

**Issue by Merded** [parcel-bundler/parcel#2757]
# ❔ Question

Why when i trying to bundle project i have error 
How to fix it?
>  EMFILE: too many open files, open '/home/merdedspade/git/starbot/packages/test_bot/node_modules/lodash/fp/capitalize.js'

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.0
| Node             | v10.15.0
| npm/Yarn         | npm
| Operating System | Fedora 29

**Comment by akozlov75** [comment]
Maybe this will fix your issue: https://github.com/facebook/create-react-app/issues/4540#issuecomment-393268543

**Comment by desean1625** [comment]
I had the same issue when importing a module. I was importing * from a library that exported from many files.
```
import * as Icons from "@material-ui/icons/";
```
This was over the hard open file limits. I had to import specific modules. Looking at the lodash library it looks like it is also a bunch of small files. Check your import statements and see if you can import only the things you need.
