### ISSUE TITLE
ES Modules are not being updated while serve()

### ISSUE THREAD

**Issue by Jax-p** [parcel-bundler/parcel#2766]
# ❔ Question

How do I keep my ES Module up-to-date in my root built js file?

I've lazy loaded ES Module and I've running parcel in 'serve' mode. When I edit my module, parcel rebuild the module and create new file (it doesn't delete the old one but ok, seems working). But the original built file (where from is the module loaded) is still linking on the old one. 

## 🔦 Context

I've tried to turn off "contentHash" in my API config for bundler. After that, module with hash is being created (hash is still included in filename) but everytime I do changes in module, it will save them to the same file (so the hash at file is still same and the original built file is linking right) => this seems to be working fine but it doesn't look like right use.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | v10.13.0
| npm        | 6.4.1
| Operating System | MacOS

**Comment by mischnic** [comment]
Could you please provide, if possible, some example where this happens?

**Comment by mischnic** [comment]
Are you using dynamic imports? Is this your situation: https://github.com/parcel-bundler/parcel/issues/2783 ?

**Comment by Jax-p** [comment]
Yea it is the same situation. So there is no solution for that now right? I've just turned off contentHash and it works fine. (contentHash is not available for .js entry points anyway)

**Comment by mischnic** [comment]
There's no solution at the moment. 

Hashing entrypoints doesn't make sense (imagine adding a hash to your `index.html`)
