### ISSUE TITLE
Change Parcel hashing algorithm

### ISSUE THREAD

**Issue by kahurangitama** [parcel-bundler/parcel#2767]
# ❔ Question
Hello! How can I get exact name of the generated files to serve it via SSR?

## 🔦 Context
I am in the middle of transition my project from react-scripts which is using Webpack to Parcel. Configuring the client was easy as 1,2,3. But when I start to rewrite server side part I stuck with assets names.

## 💻 Code Sample
My index.ts looks exactly like this:
```ts
import "reflect-metadata";
const crypto = require("crypto");
const path = require("path");

// CSS styles will be imported on load and that complicates matters... ignore those bad boys!
import * as ignoreStyles from "ignore-styles";

// We also want to ignore all image requests
// When running locally these will load from a standard import
// When running on the server, we want to load via their hashed version in the build folder
const extensions = [".gif", ".jpeg", ".jpg", ".png", ".svg"];

// Override the default style ignorer, also modifying all image requests
ignoreStyles.default(ignoreStyles.DEFAULT_EXTENSIONS, (mod, filename) => {
  if (!extensions.find((f) => filename.endsWith(f))) {
    // If we find a style
    return ignoreStyles.noOp();
  } else {
    // If we find an image

    // @IMPORTANT: this should be the same as Parcel hash generator
    // otherwise different filenames are being generated which results 404 =(
    const hash = crypto.createHash("md5").update(filename).digest("hex").slice(0, 8);
    const bn = path.basename(filename).replace(/(\.\w{3})$/, `.${hash}$1`);

    mod.exports = `/static/${bn}`;
  }
});

// Set up babel to do its thing... env for the latest toys, react-app for CRA
// Notice three plugins: the first two allow us to use import rather than require, the third is for code splitting
// Polyfill is required for Babel 7, polyfill includes a custom regenerator runtime and core-js
require("@babel/polyfill");
require("@babel/register")({
  cwd: path.resolve(process.cwd(), "../client"),
  cache: true,
  extensions: [".ts", ".js", ".tsx", ".jsx"],
  ignore: [/\/(dist|node_modules)\//],
  plugins: [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-syntax-dynamic-import",
    ["babel-plugin-root-import", { rootPathSuffix: "src" }],
    ["@babel/plugin-transform-runtime", { corejs: 2 }],
    "dynamic-import-node",
    "react-loadable/babel",
  ],
  presets: [
    "@babel/preset-env",
    "@babel/preset-react",
    "@babel/preset-typescript",
  ],
});

// Now that the nonsense is over... load up the server entry point
require("./server");
```
I trying to implement the same hashing logic for each file in this lines:
```ts
const hash = crypto.createHash("md5").update(filename).digest("hex").slice(0, 8);
const bn = path.basename(filename).replace(/(\.\w{3})$/, `.${hash}$1`);
mod.exports = `/static/${bn}`;
```
So my nginx, configured to serve everything that starts with /static as alias to /dist folder.
```
location ^~ /static/ {
   alias /Users/loyi/project/client/dist/;
}
```
the problem in that approach that not every file matches the built ones.
and I'm getting:
```
Warning: Prop `src` did not match. Server: "/static/logo2.34f8c363.svg" Client: "/static/logo2.fd97ec66.svg"
```
server generates link to /static/logo2.34f8c363.svg
but the correct one (which is built by parcel) and used in client is /static/logo2.fd97ec66.svg
....
I took that algorithm from here: https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/utils/md5.js#L4

Which is tend to change in future as comment here said:
https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/Asset.js#L247

So it's more dirty hack than solution.
Maybe I went wrong way at the start.
Could you point me where to move?

Maybe, it's also Feature Request to add ability to pass hashing function to Parcel in config. If there is a function, then Parcel use it to generate names...

## 🌍 Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             | v10.13.0
| npm/Yarn         | 6.4.1 / 1.0.1
| Operating System | Mac OS X 10.14.3

**Comment by mischnic** [comment]
> How can I get exact name of the generated files to serve it via SSR?

Closing in favour of https://github.com/parcel-bundler/parcel/issues/3307

> If there is a function, then Parcel use it to generate names...

There will a `Namer` plugin type in Parcel 2
