### ISSUE TITLE
Paths of imported assets are incorrect

### ISSUE THREAD

**Issue by jonlambert** [parcel-bundler/parcel#2769]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

Very basic - https://github.com/jonlambert/parcel-path-issue/blob/master/packages/book/package.json

Babel is default.

## 🤔 Expected Behavior

External assets should load with the correct paths. 

## 😯 Current Behavior

All required paths are incorrectly prefixed with the `book/` subdirectory.

## 🔦 Context

I'm trying to load an SVG file, or font, or image into my project.

## 💻 Code Sample

Reproduction here:
https://github.com/jonlambert/parcel-path-issue

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.0
| Node             | v10.7.0
| npm/Yarn         | 1.13.0
| Operating System | macOS 10.13.6

**Comment by jonlambert** [comment]
Possible duplication of #2736

**Comment by mischnic** [comment]
> Possible duplicate

Indeed
