### ISSUE TITLE
Wrong url when linking an html that is in a subdirectory

### ISSUE THREAD

**Issue by cruzlutor** [parcel-bundler/parcel#2774]
# 🐛 bug report
when I try to link an HTML document that is in a subdirectory to itself the url is not correct

## 🎛 Configuration (.babelrc, package.json, cli command)
package.json 
```
{
	"name": "parcel-links",
	"version": "1.0.0",
	"main": "index.js",
	"license": "MIT",
	"scripts": {
		"dev": "parcel index.html",
		"build": "parcel build index.html"
	}
}
```

## 🤔 Expected Behavior
if I'm in `/categories/home.html` the url when linking to the same page should be `/categories/home.html`

## 😯 Current Behavior
if I'm in `/categories/home.html` the url when linking to the same page is `/home.html`

## 🔦 Context
We need to create a website with subcategories reusing the same menu file in all the pages

## 💻 Code Sample
index.html
```
<html>
<body>
  <h1>Index Home</h1>
  <a href="/index.html">Home</a>
  <a href="/categories/home.html">Categories Home</a>
</body>
</html>
```

categories/home.html
```
<html>
<body>
  <h1>Categories Home</h1>
  <a href="/index.html">Home</a>
  <a href="/categories/home.html">Categories Home</a>
</body>
</html>
```
Here is the full code https://github.com/cruzlutor/parcel-link-testing

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.0
| Node             | 11.10.0
| npm/Yarn         | 1.13.0
| Operating System | MacOS

**Comment by mischnic** [comment]
Fixed by #2740
