### ISSUE TITLE
The performance API

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#2775]
# 🐛 bug report

Trying to `require('perf_hooks')` in a browser target results in `Cannot resolve dependency 'perf_hooks'`.
Other apis like `http` work fine (mainly because of polyfills), but the thing is that the performance api of node is browser compatible.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "parcel-performance-api",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "parcel-bundler": "^1.12.0"
  },
  "scripts": {
    "browser": "parcel ./src/index.ts",
    "node": "parcel --target node ./src/index.ts"
  },
  "devDependencies": {
    "typescript": "^3.3.3333"
  }
}

```

## 🤔 Expected Behavior

Parcel should bundle normally.

## 😯 Current Behavior

When trying to bundle, parcel errors out `Cannot resolve dependency 'perf_hooks'`.

```
🚨  C:\Users\Banou\Desktop\parcel-performance-api\src\index.ts:4:26: Cannot resolve dependency 'perf_hooks'
    at Resolver.resolve (C:\Users\Banou\Desktop\parcel-performance-api\node_modules\parcel-bundler\src\Resolver.js:71:17)
```

## 💻 Code Sample

```ts
const isBrowser = typeof window !== 'undefined'
const { performance } = isBrowser ? window : require('perf_hooks')
console.log(performance.now())
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.0
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
That module seems to be `Stability: 1 - Experimental`, https://nodejs.org/api/perf_hooks.html.
For the node builtin modules, Parcel uses https://github.com/webpack/node-libs-browser to load a replacement module. If you think this should be added, please open an issue over there

**Comment by jklarenbeek** [comment]
I ran into the issue as well, however node-libs-browser is deprecated. The lib perf_hooks, although experimental is very very likely to stay. 
Anyone care to help me with this issue? How do I proceed from here?

**Comment by mischnic** [comment]
node-libs-browser won't be updated for Parcel 1. This will be somehow fixed in Parcel 2. 
Here is another issue regarding outdated node-libs-browser: https://github.com/parcel-bundler/parcel/issues/2921
