### ISSUE TITLE
SCSS doesn't work with Vue

### ISSUE THREAD

**Issue by Dagge1** [parcel-bundler/parcel#2777]
Bootstrap SCSS doesnt work with Parcel compiling Vue (again). I added sass dependency, I tried some other combinations, tried all possible path combinations to bootstrap file but nothing worked. Sometimes my own .scss file in a /src folder works. Why is it (again) that bootstrap.scss from node_modules folder doesn't compile scss, while you have stated on your pages that it does?

**Comment by mischnic** [comment]
-> https://github.com/parcel-bundler/parcel/issues/1725#issuecomment-472127721
