### ISSUE TITLE
How to include favicon?

### ISSUE THREAD

**Issue by AndreasSchouten** [parcel-bundler/parcel#2784]
# ❔ Question

How to include favicon.ico?

## 🔦 Context

I added a `favicon.ico` image and a according link in `html`.

## 💻 Code Sample

`<link rel="shortcut icon" href="./favicon.ico">`
Parcel creates a file like  `favicon.44fdaf57.ico`, which is shown in the browser, but complete different from the original.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12
| Node             | 8.12
| Yarn         | 1.9.4
| Operating System | Linux

**Comment by AndreasSchouten** [comment]
I found a workaround. I renamed the the file from `favicon.ico` to `favicon.png`.
And also the link tag:
`<link rel="shortcut icon" href="./favicon.png">`
And all works fine!

So I think this is a bug handling `.icon` files?

**Comment by mischnic** [comment]
I can't reproduce this with the github favicon (https://github.com/favicon.ico) and a html file with the line from your original post.

Does the generated icon file (e.g. `favicon.44fdaf57.ico`) actually differ from the original favicon or are you only having issues with the browser displaying it? I think browsers cache favicons way more aggressively than other files.

**Comment by AndreasSchouten** [comment]
I checked the generated .ico files directly. The differ from tho original and shows random like pixels.
For the github favicon i get the attached one.

[favicon.71e61d74.zip](https://github.com/parcel-bundler/parcel/files/2965282/favicon.71e61d74.zip)

**Comment by AndreasSchouten** [comment]
I apologize!

I let parcel copy the output to a directory for static contend in a Spring Boot application.
A Maven task copies this into a target directory. And at this time the contend is filtered.

I just had to turn off the filtering and everything goes as expected. Not a parcel issue!
