### ISSUE TITLE
Parcel is doing wrong job in node_modules 

### ISSUE THREAD

**Issue by kahurangitama** [parcel-bundler/parcel#2785]
Hi! I met a problem. My project isn't starting up because Parcel is trying to sniff every module inside node_modules and get failure there. And the problem seems to be random. Btw, prop-types is installed.

# 🐛 bug report
```
Server running at http://localhost:1234 
🚨  /Users/loyi/mv/node_modules/react-router/es/withRouter.js:6:22: Cannot resolve dependency 'prop-types'
  4 | 
  5 | import React from "react";
> 6 | import PropTypes from "prop-types";
    |                      ^
  7 | import hoistStatics from "hoist-non-react-statics";
  8 | import Route from "./Route";
  9 | 
^C%  
➜  mv git:(feature/BRIG_54_Remove_conversation) ✗ parcel build public/index.html 

🚨  /Users/loyi/mv/node_modules/react-router/es/MemoryRouter.js:9:22: Cannot resolve dependency 'prop-types'
   7 | import warning from "warning";
   8 | import React from "react";
>  9 | import PropTypes from "prop-types";
     |                      ^
  10 | import { createMemoryHistory as createHistory } from "history";
  11 | import Router from "./Router";
  12 | 
➜  mv git:(feature/BRIG_54_Remove_conversation) ✗ 
```

## 🤔 Behavior

Do not touch my packages! If I will wan't to update I will do it by myself taking risk.
But Parcel think he is smart guys and doing lookup/update my modules, managing my package.json which cause a problem.

**Comment by kahurangitama** [comment]
Delete .cache , running one again! Different problem!
What the hell I don't have time to look into node_modules ! It works before and suddenly stop working before I need to commit it.! If you're developing enterprise product you can't afford block your work because of stupid bundler!
```
Server running at http://localhost:1234 
🚨  /Users/loyi/mv/node_modules/react/cjs/react.development.js:19:29: Cannot resolve dependency 'prop-types/checkPropTypes'
  17 | 
  18 | var _assign = require('object-assign');
> 19 | var checkPropTypes = require('prop-types/checkPropTypes');
     |                             ^
  20 | 
  21 | // TODO: this is special because it gets imported during build.
  22 | 
⚠️  /Users/loyi/mv/node_modules/dotenv/lib/main.js:85:41: Cannot statically evaluate fs argument
  83 |   try {
  84 |     // specifying an encoding returns a string instead of a buffer
> 85 |     const parsed = parse(fs.readFileSync(dotenvPath, { encoding }), { debug })
     |                                         ^
  86 | 
  87 |     Object.keys(parsed).forEach(function (key) {
  88 |       if (!process.env.hasOwnProperty(key)) {
```

**Comment by kahurangitama** [comment]
sorry guys. strange things happen. I stashed all changes, remove package json, yarn/package lock , node_modues, .cache, dist remove everything and start over and everything work well as before.

**Comment by mischnic** [comment]
> start over and everything work well as before.

I didn't get whether it works now after you (cleanly) reinstalled your dependencies?

(Your slightly aggressive attitude isn't helping here.)

**Comment by kahurangitama** [comment]
Everything is fixed after removing /.cache, /dist, /node_modules, stashing the changes and applying the same changes file by file to see what's actually goes wrong. And somehow it doesn't arguing on prop-types inside /node_modules anymore. Sorry for such expressive manner, it was hot time before demo to client. Excuse me.

**Comment by kahurangitama** [comment]
Close the issue
