### ISSUE TITLE
Parcel generates wrong path for images

### ISSUE THREAD

**Issue by edmundas-ramanauskas** [parcel-bundler/parcel#2793]
# 🐛 bug report

Parcel generates wrong path for image source url:
![image](https://user-images.githubusercontent.com/4420081/54345241-568bba00-464b-11e9-88d9-a08968e8dfb3.png)
while the image is available at url:
http://localhost:3000/logo.88c423d2.svg

## 🎛 Configuration (.babelrc, package.json, cli command)

Demo app with all the configuration available here:
https://github.com/edmundas-ramanauskas/parcel-demo/

## 🤔 Expected Behavior

path to asset in img tag should be `/logo.88c423d2.svg`

## 😯 Current Behavior

path to asset in img tag should be `/../../../Workspace/parcel-demo/logo.88c423d2.svg`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.0
| Node             | v11.10.0
| npm/Yarn         | 1.13.0
| Operating System | Ubuntu 18.10

**Comment by mischnic** [comment]
> Parcel | 1.12.0

This should be fixed in Parcel 1.12.1 and later

**Comment by edmundas-ramanauskas** [comment]
yep, can confirm. thanks for quick response.
