### ISSUE TITLE
CSS is not working inside vue components

### ISSUE THREAD

**Issue by Nisthar** [parcel-bundler/parcel#2807]
Search open/closed issues before submitting since someone might have asked the same thing before!
-->
I already searched related issues. It didn't fix my issue.

# 🐛 bug report

The scss inside vue components is not working. No error is shown. The build works. But no styles are added to the page. The scss code outside vue components works without any problem. I tried adding postcss. It made it worse. If i use 

package.json
```
"postcss": {
        "modules": true
}
```

All the scss code stops showing on the pages. It comes back if modules is set to false. But in both cases, scss in vue components don't work.

## 🎛 Configuration (.babelrc, package.json, cli command)
.babelrc
```js
{
  "presets": [
    "@babel/preset-env"
  ],
  "plugins": [
    ["@babel/plugin-transform-runtime", {
      "corejs": 2
    }]
  ]
}
```

## 🤔 Expected Behavior

SCSS inside vue components show in the component.

## 😯 Current Behavior

No styles are applied on the component. No error is shown.

No errors shown.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.2 (global mode)
| Node             | v10.14.2
| npm/Yarn         | v6.4.1
| Operating System | Windows 10

**Comment by mischnic** [comment]
Could you please provide a (optionally minimal) reproduction for this?

**Comment by Nisthar** [comment]
@mischnic I tried to reproduce the issue. The issue was i need to include css seperately in the .ejs (i am using ejs) files. I thought the css/scss/etc should be included in the js files.

**Comment by Nisthar** [comment]
@mischnic My folder structure is like this

-  website
      - login.js //imports login-wrapper.vue from vue folder
      -  vue
            -  login-wrapper.vue
       
login.js
```js
import Vue from "vue";

import "./global";
import Login from "./vue/login/login-wrapper.vue";


(function () {
    var app = new Vue({
        el: "#login",
        components: {
            Login
        }
    });
})();
```

**Comment by mischnic** [comment]
Does your vue file somewhat resemble the example on the parcel docs: https://parceljs.org/vue.html ?

**Comment by Nisthar** [comment]
@mischnic Yes, it does.

**Comment by 1iuh** [comment]
same question I found.

**Comment by rhurstdialpad** [comment]
Something is odd there. We have tones of vue components all with their own scoped CSS. We have no issues with parcel 1.12.3.
