### ISSUE TITLE
How can I use the environment variables defined in .env inside my app?

### ISSUE THREAD

**Issue by reebr** [parcel-bundler/parcel#2811]
The [documentation says that Parcel supports `.env` files](https://en.parceljs.org/env.html), so I created one like this:

    ENV_KEY=value
And, I tried to get the ENV_KEY value using process.env.ENV_KEY, but it returns empty.

```html
<!-- index.html -->
<!DOCTYPE html>
<html>
<!-- head, etc -->
<body>
    <div id='root'></div>
    <script src='app.jsx'></script>
</body>
</html>
```
```jsx
// app.jsx
import React from 'react'
import ReactDOM from 'react-dom'

ReactDOM.render(
    <div>
        The "ENV_KEY" value is: { process.env.ENV_KEY }
    </div>,
    document.getElementById('root')
)
```

Running it with `parcel index.html`.

How can I use the environment variables defined in `.env` inside my app?

**Comment by mischnic** [comment]
Your code should work. Is the `.env` file next to your package.json?

**Comment by reebr** [comment]
@mischnic  thank you, solved it putting `.env` in the same folder of `package.json`.

Is it normal to use this repository to ask questions instead of the StackOverflow?

**Comment by mischnic** [comment]
> Is it normal to use this repository to ask questions instead of the StackOverflow?

I don't think there's a large community that really knows how Parcel works (and it's so young that many of these questions could actually be bugs). 

I was about to add this to the website, but it turns out:

> .env files are to be stored alongside the package.json that contains your parcel-bundler dependency.

**Comment by kud** [comment]
> > Is it normal to use this repository to ask questions instead of the StackOverflow?
> 
> I don't think there's a large community that really knows how Parcel works (and it's so young that many of these questions could actually be bugs).
> 
> I was about to add this to the website, but it turns out:
> 
> > .env files are to be stored alongside the package.json that contains your parcel-bundler dependency.

We could open now the tab "discussion" for that. It's so great. I use it on Next.js.

**Comment by mischnic** [comment]
> We could open now the tab "discussion" for that. It's so great. I use it on Next.js.

We'd love to have that, but apparently their beta is still somewhat closed.

**Comment by kud** [comment]
Oh noooooooooo :((((

Okay thank you for the link!

**Comment by kud** [comment]
You sure @mischnic ? It's just that you need to do it on organisation, not the repo/project itself:

cf on one of my team:

![image](https://user-images.githubusercontent.com/655838/81840300-1377f000-9549-11ea-84e1-6cd3a8ed4847.png)

**Comment by kud** [comment]
You're right. Discussions are available in "private" mode for users already members of an orga or project, but it's not available yet as public (for everybody).
