### ISSUE TITLE
ReferenceError: _extends is not defined when upgrade to v1.12.2

### ISSUE THREAD

**Issue by moriyuu** [parcel-bundler/parcel#2812]
# 🐛 bug report

`ReferenceError: _extends is not defined` occurred when I upgraded parcel-bundler from ^v1.9.7 to latest v1.12.2

## 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc

```json
{
  "presets": ["react", "env", "stage-2"],
  "plugins": [
      ["transform-runtime",
      {
          "polyfill": false,
          "regenerator": true
      }]
  ]
}
```

## 🔦 Context

The Error occurred around here (using react-router-dom).

```jsx
....
          <Route
            exact
            path="/"
            render={() => (
              <MyContainer
                render={(props) => (
                  <MyPageTemplate {...props} />
                )}
              />
            )}
          />
....
```

```jsx
export class MyContainer extends React.Component {
    state = {....}

    render() {
        return this.props.render({
            ...this.props,
            ...this.state
        });
    }
}
```

Something wrong in my code? (But it works with v1.9)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |As above|
| Node             |v10.13.0|
| npm        |6.7.0|
| Operating System |macOS v10.14.3|

**Comment by sirlantis** [comment]
Ran into something similar, updated my `.babelrc` to explicitly use Babel 7 packages (i.e. `@babel/preset-...`, `@babel/plugin-...`).
