### ISSUE TITLE
🐛 Unexpected token: punc ())

### ISSUE THREAD

**Issue by lastmjs** [parcel-bundler/parcel#282]
This is a bug. I'm trying to bundle an index.html file, and I get `Unexpected token: punc ())`.

In the root directory of my project I have a test directory where I have an index.html file:

test/index.html:
```
<!DOCTYPE html>

<html>
    <body>
        <script>
            if (window.ELECTRON_CONSOLE_ARGUMENTS.autoRun) {
                setTimeout(() => {
                    document.getElementById('testRunner').autoRun = true;
                }, 5000);
            }
        </script>
    </body>
</html>

```

I have installed parcel globally:
```
npm install -g parcel-bundler
```

When I run `parcel build test/index.html --out-dir dist` I get the following:

```
🚨  /home/lastmj/development/prendus/secure-eval/test/index.html: Unexpected token: punc ())
    at JS_Parse_Error.get (eval at <anonymous> (/home/lastmj/.nvm/versions/node/v8.9.3/lib/node_modules/parcel-bundler/node_modules/htmlnano/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at module.exports (/home/lastmj/.nvm/versions/node/v8.9.3/lib/node_modules/parcel-bundler/src/utils/prettyError.js:20:17)
    at Logger.error (/home/lastmj/.nvm/versions/node/v8.9.3/lib/node_modules/parcel-bundler/src/Logger.js:52:28)
    at Bundler.bundle (/home/lastmj/.nvm/versions/node/v8.9.3/lib/node_modules/parcel-bundler/src/Bundler.js:151:19)
    at <anonymous>
```

**Comment by lastmjs** [comment]
If I comment out the setTimeout it works fine

**Comment by lastmjs** [comment]
So...it looks like the arrow function is the issue. Have I just missed some configuration? I was hoping zero configuration meant I could use arrow functions and a lot of other es6 without issues. At the very least, that's not a descriptive error message.

**Comment by philipodev** [comment]
can you provide us with your .babelrc?

**Comment by lastmjs** [comment]
I don't have a .babelrc

**Comment by lastmjs** [comment]
I was supposing the transpilation would happen automatically

**Comment by philipodev** [comment]
it will yes, but you have to tell babel what to transpile to. and you do so using the .babelrc file and presets.
For example the simplest you can do is: `npm install --save-dev babel-preset-env` and then create the `.babelrc` with the following content: 

```json
{
    "presets": ["env"]
}
```

**Comment by davidnagli** [comment]
@lastmjs You are absolutely correct, Parcel can work 100% without a `.babelrc`. It should automatically transpile to ES6 using babel.

It looks like a bug in Parcel.

**Comment by devongovett** [comment]
hmm, so it looks like htmlnano (the HTML minifier we use) also tries to run uglify-js over the embedded `<script>` tag, but uglify-js doesn't support ES6 syntax. I would open an issue with htmlnano, and see if they can switch to uglify-es instead.

**Comment by devongovett** [comment]
As a workaround, you could include the script as an external file instead `<script src="./myscript.js">`. That way Parcel will process the JavaScript.
