### ISSUE TITLE
🐛 Package.json name with "/" throws error

### ISSUE THREAD

**Issue by cyan33** [parcel-bundler/parcel#283]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
Possibly a bug, don't know it's related to Parcel itself or what.

I am running the https://parceljs.org/getting_started.html example. And when running `parcel index.html`, it throws:

```sh
⏳  Building...
Server running at http://localhost:1234
⏳  Building index.js...
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/changyan/Documents/repos/test_parcel/dist/@changyan/test_parcel.js'
```

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  1.2.0
| Node             | 8.6.0
| npm/Yarn         | 
| Operating System | MacOS

**Comment by DeMoorJasper** [comment]
Could u give us an overview of your code imports and file structure?

**Comment by thomasyimgit** [comment]
@DeMoorJasper It's exactly the same with the get_started tutorial:

index.html:
```html
<html>
<body>
  <script src="./index.js"></script>
</body>
</html>
```

index.js:

```js
console.log("hello world");
```

package.json:

```js
{
  "name": "@changyan/test_parcel",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

**Comment by DeMoorJasper** [comment]
Ow i get why it throws this error, it names the initial package like the package.json name and the name u use is ``@changyan/test_parcel`` so it tries to run that but that would be a dir it doesn't create...

**Comment by thomasyimgit** [comment]
I don't quite understand what you meant. But after renaming the `name` field from `@changyan/test_parcel` to `test_parcel`, it does get fixed.

I previously thought it's a rather common issue, but surprisingly no one mentioned this before. It would be super great to get this fixed. 👍

**Comment by chee** [comment]
I'm happy to look at this.

Would we rather convert it to a valid filename (with [filenamify](https://github.com/sindresorhus/filenamify) maybe), or simply remove namespaces `/@[^/]+\//`?

**Comment by DeMoorJasper** [comment]
Probably just remove special chars @chee
