### ISSUE TITLE
Class constructor [extended class] is not a function

### ISSUE THREAD

**Issue by Jax-p** [parcel-bundler/parcel#2830]
# 🐛 bug report

When using dynamic imported **extended class** (export default SomeClass extends AnotherClass), console throws **"d.constructor is not a function"** error (Chrome, up-to-date). 

It does only when I call "parcel build". 

Usual "parcel" and "parcel watch" works fine.

## 🎛 Configuration (.babelrc, package.json, cli command)

default setup (API) --no-source-maps
.babelrc: "proposal-classes" and "transform-runtime"

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | up-to-date
| Node             | up-to-date
| npm         | up-to-date
| Operating System | MacOs

**Comment by Jax-p** [comment]
Solved: Turned off "scopeHoist" which is still experimental

**Comment by mischnic** [comment]
I don't know if this is what you've described, but
```js
// index.js
import("./class.js").then(({default: AnotherClass}) => {
	class SomeClass extends AnotherClass {}

	const x = new SomeClass();
	console.log(x);
})

// class.js
export default class AnotherClass {};
```

Results in: `Uncaught TypeError: Cannot read property 'register' of undefined`
