### ISSUE TITLE
`parcel serve` reports it's listening on localhost but is bound to 0.0.0.0

### ISSUE THREAD

**Issue by rosensama** [parcel-bundler/parcel#2843]
# 🐛 bug report

related to  #1412

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "scripts": {
    "build": "parcel build src/index.html",
    "serve": "parcel serve src/index.html --https --cert ../server/localhost+2.pem --key ../server/localhost+2-key.pem --log-level 3"
  },
  "devDependencies": {
    "elm": "^0.19.0-bugfix6",
    "elm-format": "^0.8.1",
    "elm-hot": "^1.0.1",
    "fomantic-ui": "^2.7.2",
    "gulp": "^4.0.0",
    "node-elm-compiler": "^5.0.3",
    "parcel-bundler": "^1.12.3"
  },
  "dependencies": {}
}
```

## 🤔 Expected Behavior

The line "Server running at <URI>" should accurately report which interfaces the hmr server is bound to.  
```
Server running at https://0.0.0.0:1234 
```
## 😯 Current Behavior

Instead it says it's running at localhost
```
Server running at https://localhost:1234 
```
## 💁 Possible Solution

Use the expected behavior.  Related to #1412

## 🔦 Context

It is confusing to the user.  You have to check netstat or ss to know where the dev server is available.   You are likely to spend time looking for a non-existent `--host` command line argument when it's not necessary.   

## 💻 Code Sample

N/A

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.3 |
| Node             | 11.12.0 |
| npm         |  6.7.0 |
| Operating System | OSX 10.14.3 |

**Comment by mischnic** [comment]
Hm, it should display the correct value:

https://github.com/parcel-bundler/parcel/blob/121bb4854f4d09406c82233b0ed53bc56e0f6a70/packages/core/parcel-bundler/src/Server.js#L155-L157

**Comment by rosensama** [comment]
I'm on Windows until tonight, but here's what I see.   So maybe the problem is that it's binding to all interfaces when `host` is falsey?

Command
```
parcel src_js/index.html --https --cert localhost+1.pem --key localhost+1-key.pem --log-level 3
```

Output
```
Server running at https://localhost:1234 
```

netstat
```
netstat -na | grep 1234
  TCP    0.0.0.0:1234           0.0.0.0:0              LISTENING
```

**Comment by mischnic** [comment]
On macOS:
```
$ lsof -aPi -p 49627
COMMAND   PID  FD   TYPE             DEVICE SIZE/OFF NODE NAME
node    49627  23u  IPv6 0xd61045b23d2484e7      0t0  TCP *:1234 (LISTEN)
node    49627  25u  IPv6 0xd61045b23d249627      0t0  TCP *:54293 (LISTEN)
```
Another way to confirm this is that you can access the page on another device.

The question is:
- should Parcel actually listen to localhost only be default (would improve security)
- or should only the message be changed?

To make it be localhost-only by default:
```diff
$ git diff
diff --git a/packages/core/parcel-bundler/src/HMRServer.js b/packages/core/parcel-bundler/src/HMRServer.js
index 080df427..bc36a23d 100644
--- a/packages/core/parcel-bundler/src/HMRServer.js
+++ b/packages/core/parcel-bundler/src/HMRServer.js
@@ -27,7 +27,7 @@ class HMRServer {
       }

       this.wss = new WebSocket.Server(websocketOptions);
-      this.server.listen(options.hmrPort, resolve);
+      this.server.listen(options.hmrPort, options.host || '127.0.0.1', resolve);
     });

     this.wss.on('connection', ws => {
diff --git a/packages/core/parcel-bundler/src/Server.js b/packages/core/parcel-bundler/src/Server.js
index 8e87fbc9..cb0e2932 100644
--- a/packages/core/parcel-bundler/src/Server.js
+++ b/packages/core/parcel-bundler/src/Server.js
@@ -133,7 +133,7 @@ async function serve(bundler, port, host, useHTTPS = false) {
   }

   let freePort = await getPort({port});
-  server.listen(freePort, host);
+  server.listen(freePort, host || '127.0.0.1');

   return new Promise((resolve, reject) => {
     server.on('error', err => {
```

**Comment by DeMoorJasper** [comment]
These have been fixed in parcel 2

**Comment by xiemeilong** [comment]
@DeMoorJasper How can I make parcel 2 listen on 0.0.0.0 ? I am useing parcel2  ,but it listen localhost  by default . I am using .proxyrc.js.

**Comment by DeMoorJasper** [comment]
@xiemeilong maybe by using the cli flag `--host 0.0.0.0`? (Haven't tested this)

**Comment by xiemeilong** [comment]
> @xiemeilong maybe by using the cli flag `--host 0.0.0.0`? (Haven't tried this but it should work)

thanks,  It works
