### ISSUE TITLE
🙋 `parcel execute` for node targets

### ISSUE THREAD

**Issue by ycmjason** [parcel-bundler/parcel#2846]
# 🙋 feature request

I find myself wanting to execute a program only once without outputting an intermediate file. It would be really nice if parcel could support something like `parcel execute` or `parcel run` which bundles the file and execute it directly.

**Comment by mischnic** [comment]
> I find myself wanting to execute a program only once without outputting an intermediate file

That won't work.
As for atuomatical

> https://github.com/parcel-bundler/parcel/issues/935
