### ISSUE TITLE
Parcel does not support tsconfig.json extends property

### ISSUE THREAD

**Issue by rudfoss** [parcel-bundler/parcel#2856]
# 🐛 bug report

Parcel does not appear to follow `extends` in tsconfig.json

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json

```json
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "start": "parcel ./src/index.html --https"
  },
  "dependencies": {
    "@loadable/component": "^5.7.0",
    "@veracity/js-internal": "3.0.0-beta.5",
    "parcel-bundler": "^1.12.3",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-redux": "^6.0.1",
    "react-router": "^4.4.0",
    "react-router-dom": "^4.4.0",
    "redux": "^4.0.1",
    "redux-actions": "^2.6.5",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@types/loadable__component": "^5.6.0",
    "@types/react": "^16.8.8",
    "@types/react-dom": "^16.8.2",
    "@types/react-redux": "^7.0.3",
    "@types/react-router": "^4.4.5",
    "@types/react-router-dom": "^4.3.1",
    "sass": "^1.17.2",
    "typescript": "^3.3.3333"
  }
}

```

Config in ./src

```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
  }
}
```

Config in ./

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "esnext",
    "lib": ["es2017", "dom"],
    "allowJs": true,
    "jsx": "react",
    "sourceMap": true,
    "downlevelIteration": true,
    "strict": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "skipLibCheck": true
  }
}
```

## 🤔 Expected Behavior

Providing a `tsconfig.json` file with the extends parameter results in an effective configuration that is a combination of both files.

## 😯 Current Behavior

`extends` config parameter ignored resulting in incorrect effective configuration.

## 💁 Possible Solution

Resolve `extends` configuration option the same way the TypeScript compiler does.

Ref: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#configuration-inheritance-with-extends

## 🔦 Context

Using yarn workspaces I've defined a global tsconfig.json file in the root and I want to extend it for different packages in the project.

## 💻 Code Sample

Using this folder structure:

```
./index.html
./tsconfig.json
./src/tsconfig.json
./src/index.tsx
```
See config content above.

index.tsx content:
```typescript
import React from "react"
import {render} from "react-dom"

render(<h1>Hello world</h1>, document.getElementById("app"))
```

index.html content
```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Test</title>
</head>
<body>
	<div id="app"></div>
	<script src="./index.tsx"></script>
</body>
</html>
````

Running `parcel ./index.html` fails with error `Uncaught ReferenceError: React is not defined` because the compiler does not see the configuration options:

```
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.3
| Node             |10.13.0
| npm/Yarn         |1.13.0
| Operating System |Windows 10 Pro (1809)

**Comment by ford04** [comment]
I do have a similar experience trying to configure parcel with a mono repository. My React import can obvioulsy not be found.
```
import React from "react"

function renderPage(page: Page): JSX.Element {
  return <React.Fragment>  ... </React.Fragment>
}
```
Error while builing the bundle with `parcel src/index.html` with `cwd` in `web` package:

![image](https://user-images.githubusercontent.com/16099458/58237709-0d8c6c00-7d46-11e9-9db2-5b66f192700d.png)

compiling the project with `npx tsc` from `web` works just fine.

![image](https://user-images.githubusercontent.com/16099458/58238286-45e07a00-7d47-11e9-8f3a-9190e26934d2.png)

<details><summary>base `tsconfig.json` under root</summary>

```
{
  "compilerOptions": {
    "target": "ESNEXT",
    "resolveJsonModule": true,
    "allowJs": true,
    "module": "es6",
    "moduleResolution": "node",
    "jsx": "preserve",
    "esModuleInterop": true,
    "outDir": ".ts-out/",
    "noEmit": true,
    "noEmitOnError": true,
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "forceConsistentCasingInFileNames": true
  },
  "exclude": [
    "node_modules",
    "dist",
    "ts-out/"
  ]
}
```
</details>

<details><summary>tsconfig.json under web</summary>

```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      ...
    }
  }
}
```
</details>


Did I miss something?

**Comment by rudfoss** [comment]
@ford04 Since extends does not work you need to specify all the configuration options in the internal tsconfig.json until the problem is resolved. Try copying all settings from your root tsconfig into the internal one in `web`

For reference here is my tsconfig.json inside a single project folder for a project using react. I think you need to specify the options `allowSyntheticDefaultImports` and `esModuleInterop` in order for the react import to work as expected.
```
	"compilerOptions": {
		"target": "es5",
		"module": "esnext",
		"jsx": "react",
		"lib": ["dom", "es2018"],
		"moduleResolution": "node",
		"strict": true,
		"downlevelIteration": true,
		"experimentalDecorators": true,
		"allowSyntheticDefaultImports": true,
		"esModuleInterop": true,
		"emitDecoratorMetadata": true,
		"sourceMap": true
	},
```

**Comment by ford04** [comment]
thanks @rudfoss , that worked.
Is there already an active issue that deals with handling extended `tsconfig.json` files? Thats currently a missing bit in combination with mono repositories

**Comment by rudfoss** [comment]
@ford04 This issue is specifically about that. Not sure if there are any others. I have the exact same situation with regard to mono-repos and tsconfig files.

**Comment by ford04** [comment]
@rudfoss yeah you are right. I  wanted to get some kind of feedback from the parcel contributors concerning this bug - if it is aleady "below the radar" and what the schedule is. Did not notice that it is already flagged as bug.

**Comment by lukejagodzinski** [comment]
I've spend several hours trying to find out why my React imports does not work in the monorepo and I've found this issue. First I thought that it's some issue with `tsc` but no, once again it's another issue with Parcel...

Is it going to be fixed in 1.x or 2.0?

**Comment by DeMoorJasper** [comment]
@lukejagodzinski 

> Is it going to be fixed in 1.x or 2.0?

v2, we no longer use tsc for typescript files so that's the fix. It's optional now. For the typechecker in v2 we use the official config loader from typescript.

**Comment by lukejagodzinski** [comment]
@DeMoorJasper great to hear. Is there any predicted release date of v2?

**Comment by devongovett** [comment]
This will be handled in v2 by #3728
