### ISSUE TITLE
Can't use tilde paths to import css from node_modules

### ISSUE THREAD

**Issue by xmikasax** [parcel-bundler/parcel#2857]
# 🐛 bug report

Tilde path does not work when importing css from node_modules

## 🎛 Configuration (.babelrc, package.json, cli command)

.sassrc
```json
{
"includePaths": ["node_modules"]
}
```

package.json
```json
  "devDependencies": {
    "parcel-bundler": "^1.12.3",
    "sass": "^1.17.3"
  },
  "dependencies": {
    "react-simplemde-editor": "^4.0.0"
  }
```

cli command

```
parcel serve index.html
```

main.scss
`
@import '~/easymde/dist/easymde.min.css';
`

index.js
`
import './main.scss';
`

## 🤔 Expected Behavior

Parcel should bundle everything without errors

## 😯 Current Behavior

I get the next error:

`
/Users/xmikasax/git/parcel_css_import_mwe/main.scss:1:1: Cannot resolve dependency '~/easymde/dist/easymde.min.css' at '/Users/xmikasax/git/parcel_css_import_mwe/~/easymde/dist/easymde.min.css'
`

## 💁 Possible Solution

The reason might be in package name (it is 'react-simplemde-editor') while its folder with styles in node_modules is 'easymde'

## 💻 Code Sample

https://github.com/xmikasax/parcel_css_import_mwe

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3 |
| Node             | 11.12.0 |
| npm/Yarn         | 6.9.0 |
| Operating System | Mac OS |

**Comment by xmikasax** [comment]
Yes, it works, thank you. But what does `package root: the directory of the nearest module root in node_modules` in docs stand for?

**Comment by mischnic** [comment]
Basically the same as `nearest package root`:

The algorithm goes up one level in the file hierarchy and stops when the next level up would be `node_modules` or the root of your project was reached.
```
pkg-1
  |- src
      |- index.js (`~` resolves to `pkg-1` because of project root )
  |- node_modules
      |- some-dep
         |- index.js (`~` resolves to `some-dep` because of node_modules)
```

https://github.com/parcel-bundler/parcel/blob/636bb50baeae15730c3b91cd3b58b457c31f7200/packages/core/parcel-bundler/src/Resolver.js#L128-L144

**Comment by xmikasax** [comment]
Thank you.
