### ISSUE TITLE
🐛 Mobx-react-devtools   error

### ISSUE THREAD

**Issue by Topthinking** [parcel-bundler/parcel#286]
🐛 Bug report

add `mobx-react-devtools` show bug

```js
import React from 'react'
import ReactDOM from 'react-dom'
import App from './app'
import MobxDevTool from 'mobx-react-devtools'

ReactDOM.render(
    <div>
        <MobxDevTool/>  
        <App /> 
    </div>    
,document.getElementById("root"))

```

```error
🚨  /Users/top/tool/parcel/parcel-react/node_modules/mobx-react-devtools/index.js: Unexpected token } in JSON at position 81
    at JSON.parse (<anonymous>)
    at Object.load (/Users/top/.config/yarn/global/node_modules/parcel-bundler/src/utils/config.js:35:17)
    at <anonymous>
```

**Comment by brandon93s** [comment]
I believe this has been fixed by the upgrade to json5 parsing, which supports comments in JSON. This change has not been released to npm. 

Are you able to use master to test if that solves your issue?

`yarn add git+https://github.com/parcel-bundler/parcel.git`

**Comment by davidnagli** [comment]
I’m gonna close this issue for now, feel free to re-open if you still have the issue.

> Note: #272 hasn’t been released as of yet, but you should be able to see everything working if you use the latest version of Parcel via git
