### ISSUE TITLE
Feature detection

### ISSUE THREAD

**Issue by goodmind** [parcel-bundler/parcel#2861]
# ❔ Question

How parcel feature detection works? e.g it can detect if file uses flow, babel plugins and more features. 

Can this be used by external tools?

## 🔦 Context

I'm trying to build online REPL, currently I run `@babel/standalone` on files with predefined list of plugins, would love to detect all of them automatically

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 11.11.0
| Yarn         | 1.15.2
| Operating System | High Sierra 10.13.6

P.S issue templates can add labels automatically like in Flow repo

**Comment by mischnic** [comment]
> How parcel feature detection works? e.g it can detect if file uses flow, babel plugins and more features.

Basically, this is the default Babel config used:
```js
{
  presets: [
  	["@babel/preset-env"]
  ],
  plugins: [
    [
      require('@babel/plugin-transform-react-jsx'),
      {
        pragma: "<detect based on dependencies>",
        pragmaFrag: 'React.Fragment'
      }
    ], [require('@babel/plugin-transform-flow-strip-types')]
  ]
]
```

The only downside of always running the jsx and flow plugins could be speed (but probably not significant).

https://github.com/parcel-bundler/parcel/blob/636bb50baeae15730c3b91cd3b58b457c31f7200/packages/core/parcel-bundler/src/transforms/babel/config.js#L20-L88
