### ISSUE TITLE
The assets output destination issue

### ISSUE THREAD

**Issue by iamfrntdv** [parcel-bundler/parcel#2869]
Parcel is really good tool, it's fast, it's easier to configure compared to other similar tools.
But it has one issue that I think Is very important. It's missing NORMAL way to define the output path for different assets for example js in it's separate folder/subfolder, css in it's own separate folder/subfolder, images in their own separate folder(s)/subfolder(s). 

There are tons of reasons why it's so important to have this ability. If someone from parcel developers or contributors didn't face this case it doesn't mean that the others don't require this ability. 

For example authentication. In some cases some of the assets should be protected with authentication for example I don't won't to give ability to access js, css or images for none authenticated users and it's much easier to match depending on path. Also it's much easier to serve files based on path and develop extra features. It's not just because everyone just used to structure their projects in that way.

If developer would like to output js for example into `/dist/assets/js`, css into `/dist/assets/css` and images `/dist/assets/images` why there should be a struggle. 
Why it should be so hard to solve this issue with parcel meanwhile other similar tools can handle this very easy?

Don't let parcel to be another one opinionated tool. 

It seems there are a lot of issues of this kind.

**Comment by pattisahusiwa** [comment]
> Parcel is really good tool, it's fast, it's easier to configure compared to other similar tools.
> But it has one issue that I think Is very important. It's missing NORMAL way to define the output path for different assets for example js in it's separate folder/subfolder, css in it's own separate folder/subfolder, images in their own separate folder(s)/subfolder(s).

Agreed.
I've been using Parcel for a while to create several website templates. Works really well without complicated configuration. As you said, the feature is very important for this type of projects.

**Comment by devongovett** [comment]
This has come up many times in the past. Please search the issues before posting. E.g. https://github.com/parcel-bundler/parcel/issues/233

It will be possible in Parcel 2 by overriding the default namer plugin.

**Comment by VladimirMikulic** [comment]
@iamfrntdv I don't know if you still need a solution to this, but I've developed a plugin that resolves your problem.
https://github.com/VladimirMikulic/parcel-plugin-custom-dist-structure

Let me know what you think!
