### ISSUE TITLE
Is file hashing based on versioning?

### ISSUE THREAD

**Issue by zfrisch** [parcel-bundler/parcel#2870]
# ❔ Question

I'm curious if the hashing is based upon versioning/what constitutes a version change, or if it's just a random hash each time? 

## 🔦 Context

I'm currently replacing Browserify with Parcel JS in a build process. It works wonderfully, but in my old process I used the rev library to hash the compiled JS and CSS to prevent browser caching.  This was based upon asset versioning, and I want to know if this is analogous to what Parcel innately does, or if I should migrate rev from my original process to the new process alongside Parcel.

**Comment by mischnic** [comment]
> I'm curious if the hashing is based upon versioning

The hash is based on the contents of the bundle, so one could say:

> this is analogous to what Parcel innately does
