### ISSUE TITLE
sass asset paths are wrong when using public-url

### ISSUE THREAD

**Issue by thsorens** [parcel-bundler/parcel#2877]
# 🐛 bug report

Referencing: https://github.com/parcel-bundler/parcel/issues/2845

When using public-path (ex ./dist) assets within the sass-file references dist/, even though the css-file is located in the same folder as the asset. It works fine in development mode. 
When loading the css-file, it will try to find the asset in root/dist/dist. 

Changing the public-path to ./ would fix the css issue, but it will break imported images directly in a js-file. 

Ex 
```
import './some-image.png'; 
```

This ends up in the dist-folder, and will be targeted at root since public-path is set to root. 

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 💻 Code Sample

https://github.com/thsorens/parcel-css-issues

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel      1.3.2     |
| Node         11.10    |
| npm/Yarn       1.15.2  |
| Operating System windows/os-x |

**Comment by thsorens** [comment]
any checks on this? Should be a reproducable sample in the github repo. This is kind of a show-stopper at the moment.

**Comment by curtiscarlson** [comment]
@thsorens I just figured it out in #2845 check my last post there

**Comment by thsorens** [comment]
Will look into it @curtiscarlson, thanks:)
