### ISSUE TITLE
Parcel sometimes fails to start due to LESS sourcemaps error

### ISSUE THREAD

**Issue by mirkea** [parcel-bundler/parcel#2879]
# 🐛 bug report

Parcel **sometimes** fails to start due to [a LESS sourcemaps error](https://i.imgur.com/bjnGMr1.png) (no files changed between those `npm start` instances), It seems to happen randomly, sometimes I have to re-run the script 3 times before it happens.

Editing any .LESS file (so that parcel rebuilds the changes) or restarting Parcel seems to solve it.

My hunch is that is due to the plugins that the LESS files (boostrap 4 LESS adaptation) use, in this case.

## 🎛 Configuration (.babelrc, package.json, cli command)
A demo project to reproduce the issue plus more configuration info [can be found here](https://github.com/mirkea/parcel-less-bug)

## 🤔 Expected Behavior

Parcel should finish the build all the time, or fail all the time.

## 😯 Current Behavior

Parcel fails to build, sometimes, 

> /mnt/e/Work/CO/Parcel LESS bug demo/src/components/core/Grid/Grid.less: Cannot read property 'substring' of undefined
>at SourceMapOutput.add (/mnt/e/Work/CO/Parcel LESS bug demo/node_modules/less/lib/less/source-map-output.js:72:39)

## 💁 Possible Solution
Running with no sourcemaps works (as a workaround)

## 🔦 Context
I had to remove sourcemaps entirely (not just the css  ones with only affect me but the .JS ones as well which the other devs working on the project might need)

## 💻 Code Sample
[Demo project](https://github.com/mirkea/parcel-less-bug)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.3
| Node             |  v8.10.0
| npm/Yarn         | 6.9.0
| Operating System | Ubuntu (linux subsystem) on Windows 10

**Comment by mischnic** [comment]
I can reproduce this on macOS (on the first try when running `npm start`). I think this is rather a less bug (when LESS builds the sourcemap, it tries to access some filecontents which weren't actually loaded). (And LESS imports are also handled by LESS itself and not by Parcel.)
