### ISSUE TITLE
unreferenced files change extension, rendered unusable

### ISSUE THREAD

**Issue by guyisra** [parcel-bundler/parcel#2880]
# ❔ Question

Having a yaml file under /src and refering to it as a string path in a js file, for example:

`const myFilePath = "./myfile.yaml"`

and then using it via code (and not via a require/import) and running

`yarn parcel build src/*`

would create under /dist 2 file
myfile.js and myfile.js.map, but the js code that using the file path is unusable since myfile.yaml doesn't exist in /dist

am I missing something?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 11
| npm/Yarn         | 1.13
| Operating System | mac os

**Comment by mischnic** [comment]
> and then using it via code (and not via a require/import) and running

How are you using it?

**Comment by guyisra** [comment]
specifically, the file path is given to the tangram library for it's use (where it loads the file, and process it)

**Comment by mischnic** [comment]
Does copying `myfile.yaml` into the dist folder manually fix this? 
Are you getting an error message?

**Comment by guyisra** [comment]
yes, copying to dist solves the issue.
But as I see it, the dist is the compiled folder, and I don't want to manage my sources in 2 different folders, especially not in dist.

I don't understand why parcel takes the yaml file and turns it to javascript

**Comment by mischnic** [comment]
> yes, copying to dist solves the issue.
But as I see it, the dist is the compiled folder, and I don't want to manage my sources in 2 different folders, especially not in dist.

Thats correct, I just wanted to verify what happens here.

The issue here is that tangram requests the file (url) you passed from the server. But Parcel has no way to know that you need that file.
So copying the file is the easiest workaround for now.

(Alternative: use the Parcel API and add a handler to serve these specific static assets)

**Comment by mischnic** [comment]
Related: https://github.com/parcel-bundler/parcel/issues/501, https://github.com/parcel-bundler/parcel/issues/1411

**Comment by mischnic** [comment]
> I don't understand why parcel takes the yaml file and turns it to javascript

Are the contents also identical? It could be that your project folder is `name`, then `name.[HASH].js` will be the JS filename.
