### ISSUE TITLE
Generates invalid package.json file when referencing css in parent directory

### ISSUE THREAD

**Issue by znerol** [parcel-bundler/parcel#2881]
# 🐛 bug report

Given a directory structure where the parcel project resides in a subdirectory. When referencing a css file anywhere in the parent directory structure, parcel overwrites the `package.json` file in the subdirectory completely with a file containing exclusively `devDependencies` with a single entry for `cssnano`. This does not happen if `--no-minification` is specified on the command line.

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json:

```js
{
  "name": "parcel-project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "parcel build index.js"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel-bundler": "^1.12.3"
  }
}
```

index.js:
```js
import '../test.css';
```

command:
```
$ npm run build
```

## 🤔 Expected Behavior

Build should produce css and js file in `dist` directory.

## 😯 Current Behavior

```
$ npm run build

> parcel-project@1.0.0 build /tmp/bundler-test/parcel-project
> parcel build index.js

🚨  /tmp/bundler-test/test.css:undefined:undefined: Cannot find module 'cssnano' from '/tmp/bundler-test'
    at /tmp/bundler-test/parcel-project/node_modules/resolve/lib/async.js:68:35
    at processDirs (/tmp/bundler-test/parcel-project/node_modules/resolve/lib/async.js:208:39)
    at ondir (/tmp/bundler-test/parcel-project/node_modules/resolve/lib/async.js:223:13)
    at load (/tmp/bundler-test/parcel-project/node_modules/resolve/lib/async.js:101:43)
    at onex (/tmp/bundler-test/parcel-project/node_modules/resolve/lib/async.js:126:17)
    at /tmp/bundler-test/parcel-project/node_modules/resolve/lib/async.js:13:69
    at FSReqWrap.oncomplete (fs.js:153:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! parcel-project@1.0.0 build: `parcel build index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the parcel-project@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2019-04-02T13_14_45_773Z-debug.log
```

Also contents of `package.json` looks like this afterwards:

```js
{
  "devDependencies": {
    "cssnano": "^4.1.10"
  }
}
```

## 💁 Possible Solution

?

## 🔦 Context

-

## 💻 Code Sample

Repository with reproduction: [znerol-scratch/parcel-parent-dir-bug](/znerol-scratch/parcel-parent-dir-bug)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3 |
| Node             | 10.15.3 |
| npm/Yarn         | npm 6.4.1 |
| Operating System | Linux |

**Comment by znerol** [comment]
Attached node inspector and found the following: It looks like `localRequire` is called with `asset.name` pointing to the css file in the parent directory from [transforms/postcss.js](https://github.com/parcel-bundler/parcel/blob/636bb50baeae15730c3b91cd3b58b457c31f7200/packages/core/parcel-bundler/src/transforms/postcss.js#L68-L70). This in turn leads to `basedir` of `localRequire` pointing to the parent directory in [localRequire.js](https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/utils/localRequire.js#L14-L15). As a result the subsequent call to `resolve` for `cssnano` with `basedir` pointing to parent fails. Following that the `installPackage` is tried on the parent directory (where no package.json exists) and the subsequent recursive call to `localRequire.js` then blows up.

**Comment by znerol** [comment]
As a workaround one can simply symlink any affected css files into the parcel project directory or any subdirectory thereof (see workaround branch in the repro repository).

**Comment by jakeparis** [comment]
This is not the kind of problem you can just work around. I've got a screenshot of this happening: 

![2019-04-15_17-19-30](https://user-images.githubusercontent.com/7408985/56166347-6298cd80-5fa3-11e9-8d84-ca3ad38a0b53.gif)

You can see that after parcel tries to install cssnano, it errors, and I switch over to SublimeText, and the new package.json reloads with the single cssnano entry.

**Comment by tomcumming** [comment]
Similar very weird behaviour here when referencing a typescript file outside of my project root. `package.json` is being overwritten

**Comment by ipmb** [comment]
Sounds similar to #2978

**Comment by Magnusalt** [comment]
The same thing happened to me but when building a Vue application, I moved a component to a shared folder outside the vue app and after that my package.json file was cleared out leaving only "vue-template-compiler" as a devDependency.

**Comment by laoshaw** [comment]
it's 2020.12 and saw same issues here, could not get parcel work with bootstrap 5 when building for production, this is a critical bug for me and I had to switch to webpack.
