### ISSUE TITLE
installed simple plugin - strange behavor

### ISSUE THREAD

**Issue by FDiskas** [parcel-bundler/parcel#2885]
If I install https://github.com/janouma/parcel-plugin-text
For some reason "scss" files are compiled to css are blank

parcel-bundler": "^1.12.3

**Comment by FDiskas** [comment]
No matter what plugin I install - same result
tried also this one: https://github.com/jaywcjlove/parcel-plugin-markdown-string

**Comment by FDiskas** [comment]
Additional info needed?

**Comment by mischnic** [comment]
Closing as this is related to the plugin.
You might want to provide a complete repo to reproduce this.
