### ISSUE TITLE
[Regression] --no-minify not working on pug since 1.12.x

### ISSUE THREAD

**Issue by DFOXpro** [parcel-bundler/parcel#2890]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```bash
rm ./www -Rv; parcel build --out-dir www --no-minify src/index.pug
```

## 🤔 Expected Behavior

Rendered html pages should be pretifier / indented

## 😯 Current Behavior

Rendered html pages are minimized

## 💁 Possible Solution

Maybe related to #2887 

## 🔦 Context

With this regression there is no way to build a dev / debug compiled version of our projects.
note included code is not minimized.

### Input

```pug
html
	head
		title
	body
		div#app
		script
			include ./index.js
```
### Output 

```
<html><head><title></title></head><body><div id="app"></div><script>var app = new Vue({
  el: '#app',
  data: {
    name: 'mundo',
    link: {
      url: 'http://asd.com',
      name: 'asd.com',
      show: true
    }
  }
});</script></body></html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.0 ~ .3
| Node             | v10.15.3
| npm/Yarn         | 6.9.0
| Operating System | Xbuntu 18.04.2

**Comment by ciaranashton** [comment]
2582

**Comment by ciaranashton** [comment]
Not sure if this is bug. I found this #2582 PR which removes this ability due to Pug deprecating the pretty option. [Pug API](https://pugjs.org/api/reference.html#options)

**Comment by mischnic** [comment]
Good catch.
@DFOXpro If you really want pretty output, you should be able to set the `pretty` option in the pug option file:

```js
// pug.config.js

module.exports = {
  pretty: true
};
```
