### ISSUE TITLE
Unable to install versions after 1.10.3

### ISSUE THREAD

**Issue by andrew-anguiano** [parcel-bundler/parcel#2895]
# 🐛 bug report

I'm trying to globally install parcel@latest and am getting `Couldn't find package "@parcel/fs@^1.11.0" required by "parcel@latest" on the "npm" registry.`

This seems to be an issue using either NPM or Yarn to install. I tried installing `parcel@1.11` but that fails with the same issue. It seems that Parcel 1.10.3 is the latest version I can get to install without getting the error.

## 🎛 Configuration (.babelrc, package.json, cli command)

`yarn global add parcel@latest`

```js
{ 'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-commit-hooks': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'bin-links': true,
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.yarnpkg.com',
  'strict-ssl': true,
  'user-agent': 'yarn/1.15.2 npm/? node/v8.11.3 darwin x64',
  lastUpdateCheck: 1554512484035 }
info npm config
{ _auth: REDACTED,
  'always-auth': true,
  email: REDACTED,
  python: '/usr/bin/python' }
```

## 🤔 Expected Behavior

Parcel should be installed

## 😯 Current Behavior

I get `Couldn't find package "@parcel/fs@^1.11.0" required by "parcel@latest" on the "npm" registry.`

```
[1/4] 🔍  Resolving packages...
error Couldn't find package "@parcel/fs@^1.11.0" required by "parcel@latest" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
Error: Couldn't find package "@parcel/workers@^1.11.0" required by "parcel@latest" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.15.2/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.15.2/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.15.2/libexec/lib/cli.js:35729:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.15.2/libexec/lib/cli.js:304:30)
    at /usr/local/Cellar/yarn/1.15.2/libexec/lib/cli.js:317:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find package "@parcel/logger@^1.11.0" required by "parcel@latest" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.15.2/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.15.2/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.15.2/libexec/lib/cli.js:35729:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.15.2/libexec/lib/cli.js:304:30)
    at /usr/local/Cellar/yarn/1.15.2/libexec/lib/cli.js:317:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | --
| Node             | 8.11.3
| npm/Yarn         | 1.15.2
| Operating System | MacOS 10.14.3

**Comment by andrew-anguiano** [comment]
I think this is caused by https://github.com/npm/npm/issues/19254. If I move my `.npmrc` -> `.npmrc.bak`, everything works fine.

**Comment by DeMoorJasper** [comment]
`@parcel/fs` actually exists, it's probably an npm thing or perhaps some private package repository you are using?

<img width="403" alt="Screenshot 2019-04-13 at 14 44 20" src="https://user-images.githubusercontent.com/2175521/56079893-b61be780-5dfa-11e9-9b54-4ad6544fd792.png">

It does exist so it should work

**Comment by andrew-anguiano** [comment]
I don't have a custom registry set up currently but it seems like the presence of `.npmrc` is causing the issue maybe? As soon as I rename/move my `.npmrc`, everything installs fine. So yeah, it's either an NPM issue or a config issue on my part. I'll go ahead and close it 🙂 


Here is the contents of my `.npmrc` for reference:
```
_auth=REDACTED
always-auth=true
email=REDACTED
registry=https://registry.npmjs.org
```
