### ISSUE TITLE
SVG as an Asset Type for image references

### ISSUE THREAD

**Issue by schwjm** [parcel-bundler/parcel#2901]
# 🙋 feature request

Support parsing .svg files to scan and update for references like inline SVG in HTML is already done.

## 🤔 Expected Behavior

An `<image>` tag inside a .svg file should be able to reference another .svg file via `href` or `xlink:href`. This is supported in Firefox 66, Chrome 73, IE 11. These references should be supported in SVGs included in the bundle.

```svg
<image href="./examplebase.a2a5d7d4.svg" x="15" y="20" width="70" height="70" />
```

## 😯 Current Behavior

SVG files are not treated as a built-in asset type--only HTML inline SVG is massaged, so references in .svg files do not know that the .svg files in the bundle are now under a different filename with the hash.

```svg
<image href="./examplebase.svg" x="15" y="20" width="70" height="70" />
```

## 💁 Possible Solution

.svg files could be parsed and have their contents examined. It didn't seem like it was as easy as just running .svg as an `HTMLAsset` unfortunately, a separate parser or configuration may be required. Image references could perhaps even be inlined instead of linked.

## 🔦 Context

I am constructing a set of SVG icons, and separate from that, a tool that wants to use these icons in a composition or with modifications. For example, the same icon could be reused in different contexts. The SVG references are all in my JavaScript because the HTML is dynamically generated, and I would prefer to separate the concern of image data from JavaScript code (i.e. avoid code to compose new SVG images if I can just reference a file.)

### examplebase.svg
```svg
<svg xmlns="http://www.w3.org/2000/svg"
    width="100" height="100" viewBox="0 0 100 100"
>
<defs>
    <linearGradient id="bg"
        x1="0%" y1="0%" x2="100%" y2="0%"
    >
        <stop offset="0%" stop-color="#737eaf" />
        <stop offset="100%" stop-color="#3f457b" />
    </linearGradient>
</defs>
<rect x="5" y="5" width="90" height="90"
    rx="2"
    fill="url(#bg)"
/>
</svg>
```
![examplebase](https://user-images.githubusercontent.com/20408541/55686392-3d161f00-5926-11e9-9463-7a85366b9cb2.png)

### example.svg
```svg
<svg xmlns="http://www.w3.org/2000/svg"
    width="100" height="100" viewBox="0 0 100 100"
>
<image href="./examplebase.svg" x="15" y="20" width="70" height="70" />
<text x="50" y="30" width="100" text-anchor="middle"
	fill="white" stroke="black"
	font-family="Arial" font-size="16pt">Example</text>
</svg>
```
![example](https://user-images.githubusercontent.com/20408541/55686394-40110f80-5926-11e9-8875-b77b6ae1a224.png)

**Comment by schwjm** [comment]
It occurred that stylesheet linking is an even more relevant use-case here. `<style>@import url(file.css)</style>` works in SVG. As an option, inlining the stylesheet (maybe even shaking unused rules off) would be pretty cool eventually too.

**Comment by mischnic** [comment]
Another tag that should be detected:
```svg
<!-- image2.svg -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="-1 -1 2 2">
  <circle cx="0" cy="0" r="1" style="fill: black" id="circle" />
</svg>
```

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="-1 -1 2 2">
  <use xlink:href="image2.svg#circle" />
</svg>
```

**Comment by thewilkybarkid** [comment]
> It occurred that stylesheet linking is an even more relevant use-case here. `<style>@import url(file.css)</style>` works in SVG. As an option, inlining the stylesheet (maybe even shaking unused rules off) would be pretty cool eventually too.

Same as using a processing directive:

```svg
<?xml-stylesheet href="styles.css"?>
```

**Comment by devongovett** [comment]
This is done in v2 https://parceljs.org/languages/svg/
