### ISSUE TITLE
Custom Babel/PostCSS config in Bundler API

### ISSUE THREAD

**Issue by nedpals** [parcel-bundler/parcel#2902]
# ❔ Question

Hi! Is there a way to hook babel/posthtml/postcss configs into the Bundler API?

## 🔦 Context

I'm trying to build a static site generator using Parcel and Mithril and I would like to use some sort of config the same as Gatsby did with their own custom webpack config which would able the users to get on board directly without fiddling and installing babel presets and etc.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0     |
| Node             | 10.15.1    |
| npm/Yarn         | 1.7.0      |
| Operating System | Windows 10 Pro |

**Comment by DeMoorJasper** [comment]
This is currently not possible, however parcel 2 will support injecting of config

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nedpals** [comment]
I see, thanks.
