### ISSUE TITLE
HMR Webworker: window isn't available

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#2908]
Hello, I'm currently getting an HMR error in my WebWorkers that seems to be related to a use of the `window` global in the hmr runtime [here](https://github.com/parcel-bundler/parcel/blob/636bb50baeae15730c3b91cd3b58b457c31f7200/packages/core/parcel-bundler/src/builtins/hmr-runtime.js#L63).   It wasn't clear to me if the fix was as simple as changing `window.location.reload()` to   `location.reload()` and  if there had been an unintentional regression introduced by #2676 so for now I'm just leaving this note -- any comments welcome.  thanks, nehal

_Originally posted by @habemus-papadum in https://github.com/parcel-bundler/parcel/issues/528#issuecomment-481274320_

**Comment by mischnic** [comment]
`self.location.reload` isn't actually defined for a worker.
The only solution I see is disabling (traditional) HMR for workers.

**Comment by habemus-papadum** [comment]
#529 seems to try to fix a similar problem (at a different location in the hmr runtime) by changing `window.location.reload` to `location.reload`.   Also see the comments in #476 regarding `self.location` vs accessing `location` via implicit global.   Was this fix incorrect or am I misunderstanding?

**Comment by mischnic** [comment]
There are two issues here:
- First, `window` isn't the global object inside a worker
- If you remove `window`, `location.reload` would be undefined (and that call would fail), because it doesn't exist in a worker (what does *reloading* a JS file mean, anyway): https://developer.mozilla.org/en-US/docs/Web/API/WorkerLocation#Methods

**Comment by mischnic** [comment]
Closing for #3076
