### ISSUE TITLE
When building TypeScript Parcel doesn't output any errors

### ISSUE THREAD

**Issue by Bauke** [parcel-bundler/parcel#2911]
## 🎛 Configuration (.babelrc, package.json, cli command)

`parcel build src/main.ts --target node`

## 🤔 Expected Behavior

When there's TS errors it should output them and prevent it from building "successfully".

## 😯 Current Behavior

When building TS using Parcel, say you have straight up invalid code, like a missing parenthesis, it will build without showing any sign of error.

## 💻 Code Sample

Sample code:

```ts
function test() {
  console.log('hello');
}

test(
```

Output using command from above:

```
npx parcel build src/main.ts --target node
✨  Built in 2.71s.

dist/main.js        1.14 KB    2.67s
dist/main.js.map      207 B      2ms
```

Now if you change the filename to javascript and run the exact same thing, the output will be:

```
npx parcel build src/main.js --target node
🚨  /home/bauke/Projects/parcel-test/src/main.js:6:0: Unexpected token (6:0)
  4 | 
  5 | test(
> 6 |
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3 |
| Node             | 10.15.2 |
| npm/Yarn         | 6.4.1/1.13.0 |
| Operating System | Kubuntu 18.04 |
| TypeScript | 3.4.3 |

**Comment by mischnic** [comment]
This is currently "by design". See #1378

https://github.com/fathyb/parcel-plugin-typescript *might* work, though it isn't supported by/part of Parcel itself.

**Comment by Bauke** [comment]
Ah, thanks. Just tried that and it works, I eagerly await official support in the meantime. :P
