### ISSUE TITLE
Elm build without HMR or Dev Server or optimize option

### ISSUE THREAD

**Issue by rosensama** [parcel-bundler/parcel#2913]
# ❔ Question

Hi, I'd like to get roughly the output of `parcel build` for an elm project, but I don't want to pass the `--optimize` argument to `elm make`.  Put another way, I'd like to not use the dev server or HMR, but want to leave Debug commands in my Elm.  Is there a way to accomplish this?

## 🔦 Context

I have a feature in Elm that will not work through elm-reactor and apparently the parcel dev server / hmr.   I can avoid that by calling `parcel build`, but that passes `--optimize` to `elm make`.   `elm make --optimize` will not compile with `Debug` methods in the codebase.   Since I want to test this feature, I want to leave Elm debugging in for the time being.

## 💻 Code Sample

It's an elm compiler error I'm trying to avoid:

```
$ parcel build src/index.html

There are uses of the `Debug` module in the following modules:

    Main

But the --optimize flag only works if all `Debug` functions are removed!
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3 | 
| Node             | 11.11.0 | 
| npm         |  6.9.0 |
| Operating System | OSX 10.14.4 | 
| elm | 0.19.0 |

**Comment by mischnic** [comment]
If you pass `--no-minify` to Parcel, all optimizations (JS, CSS, Elm) will be disabled. It isn't possible to disable it only for an Elm asset.
A workaround: 
You could run parcel twice: once on the Elm file with `--no-minify` and then use the output file in another parcel run (quite a hack).

**Comment by rosensama** [comment]
`--no-minify` is fine for my needs.  Thanks.
