### ISSUE TITLE
🐛 css bundle bug

### ISSUE THREAD

**Issue by GrosSacASac** [parcel-bundler/parcel#292]
**Choose one:**  bug report 

Css is not bundled the same as in the non built version
see attachement

### 🎛 Configuration (.babelrc, package.json, cli command)

0 config

### 🤔 Expected Behavior

red should be red 

### 😯 Current Behavior

red text is not red (css .red is not bundled)

### 🔦 Context

trying to build html files and web bundles
[bug-repro-parcelv2.zip](https://github.com/parcel-bundler/parcel/files/1563306/bug-repro-parcelv2.zip)

I think it comes from the fact that a css file is imported inside another AND imported directly in another HTML file

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  1.2.0
| Node             |  8
| npm/Yarn         | 5 
| Operating System | win8

**Comment by devongovett** [comment]
Related: #294 #326 #380 #463 #489
