### ISSUE TITLE
"http2" module

### ISSUE THREAD

**Issue by nwtgck** [parcel-bundler/parcel#2921]
Hi, developers! Thank you for your very convenient project.

# ❔ Question

Could you tell me Parcel supports "http2" module?

## 🔦 Context

`const http2 = require("http2");` causes an error **"Cannot resolve dependency 'http2'"**.
`require("http")` worked well.

## 💻 Code Sample

Here is my index.js

```js
// index.js
const http2 = require("http2");

http2.createServer((req, res)=>{
  res.end("hello, world\n");
}).listen(3000, ()=>{
  console.log("Listening...");
});
```

Here is how to build.

```bash
./node_modules/.bin/parcel build index.js --target=node --bundle-node-modules --no-cache
```

Here is the complete code: <https://github.com/nwtgck/public-code/tree/master/parcel-http2>

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3|
| Node             | v10.15.0 |
| npm/Yarn         |  npm 6.8.0 |
| Operating System | macOS 10.12.6 |

**Comment by mischnic** [comment]
Parcel uses this list of node builtin modules: https://github.com/webpack/node-libs-browser/blob/master/index.js

http2 is missing

**Comment by DeMoorJasper** [comment]
Unfortunately that list is missing a lot more than just http2

**Comment by azz** [comment]
https://github.com/sindresorhus/is-builtin-module ?

**Comment by mischnic** [comment]
A package like that (a list of strings) isn't enough for our usecase, because some of these modules are actually polyfilled when bundling for the browser (e.g. `buffer` or `path`)

**Comment by azz** [comment]
Ah I see. Not possible to use a separate package for polyfills and determining builtins?

**Comment by mischnic** [comment]
Yes, I guess we could use some existing (maintained) package to make sure the builtin list is correct and use our own polyfill list

**Comment by devongovett** [comment]
We can use the list that is exported from node itself:

```js
import {builtinModules} from 'module';
```

**Comment by Taym95** [comment]
Hey @devongovett, do you mean to use this package [builtin-modules ](https://github.com/sindresorhus/builtin-modules) instead of node-libs-browser?

**Comment by mischnic** [comment]
Webpack 5 might remove automatic Node polyfills (https://github.com/webpack/changelog-v5#automatic-nodejs-polyfills-removed)

Instead, they should be explicitly aliased:
```json
{
	"dependencies": {
		"path-browserify": "1.0.0"
	},
	"alias": {
		"path": "path-browserify"
	}
}
```

Should we do the same for Parcel 2?

**Comment by devongovett** [comment]
Looks like this is fixed in #3620.

**Comment by jeduden** [comment]
Any changes this fix makes it into parcel 1.X ?

**Comment by SqueezeToyAliens** [comment]
Is there any workaround for Parcel 1.X? Even a tweak in code that can be written(like importing an overwriting an object)? I think that there are quite a lot of Parcel 1.X users out there who wish to use new NodeJS built-ins.

**Comment by JoshGlazebrook** [comment]
2.x isn't even released, nor does it seem to be usable in its current state. Not sure why a fix for this isn't being pushed to 1.x... what the hell happened to this project?

**Comment by vegidio** [comment]
Apparently this fix is not coming for Parcel 1.x so a workaround for it is to install the deprecated package `http2` in your project:

`yarn add http2`
