### ISSUE TITLE
CSS inside Vue Web Components is not working

### ISSUE THREAD

**Issue by jdvivar** [parcel-bundler/parcel#2923]
# 🐛 bug report

When using Vue Web Components, the styles are not attached to the component

## 🎛 Configuration (.babelrc, package.json, cli command)

This is the Babel configuration:

```js
{
  "presets": [
    "env"
  ],
  "plugins": [
    "transform-runtime",
    "@babel/plugin-syntax-dynamic-import"
  ]
}
```

## 🤔 Expected Behavior

Vue Web Component style should be attached to the compoent

## 😯 Current Behavior

It's not attached, see this working demo:
https://78o3xkjmj.codesandbox.io/

## 💁 Possible Solution

This happens in Webpack if `shadowMode` is `false`, see this comment:
https://github.com/vuejs/vue-web-component-wrapper/issues/12#issuecomment-385141573

## 🔦 Context

Vue Web Components is another way to create Web Components. I expected Parcel to work correctly in this simple context.

## 💻 Code Sample

This is the code for the working demo:
https://codesandbox.io/s/78o3xkjmj

**Comment by ckcks12** [comment]
Hello.
I just figured out that in some file structure parcel produces two separate files - `.js` and `.css`.
If you're bundling `.html` file which includes `<script src=".js">`, I think parcel attaches style tag to built html file automatically.
However if you're bundling `.js` file as entry file, it will give you like I said. Is it your case?
