### ISSUE TITLE
Issue with self-closing tags

### ISSUE THREAD

**Issue by scriptPilot** [parcel-bundler/parcel#2924]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

Vue component is fixed with ESLint / Vue Plugin to the following code with self-closing tags:

```vue
<template>
  <f7-app :params="f7params">
    <f7-statusbar />
    <f7-view main />
  </f7-app>
</template>
```

## 🤔 Expected Behavior

Component is bundled well with Parcel.

## 😯 Current Behavior

Result is an empty page, because the view is now part of the statusbar, because the closing tag is not created by Parcel.

## 💁 Possible Solution

Works well without self-closing tags.

```json
"rules": {
    "vue/html-self-closing": [
      "error",
      {
        "html": {
          "component": "never"
        }
      }
    ]
  }
```

```vue
<template>
  <f7-app :params="f7params">
    <f7-statusbar></f7-statusbar>
    <f7-view main></f7-view>
  </f7-app>
</template>
```

## 🌍 Your Environment

* **ESLint version:** 5.16.0
* **eslint-plugin-vue version:** 5.2.2	
* **Node version:**	 11.6.0

**Comment by scriptPilot** [comment]
Is there any progress on this common issue?

**Comment by houd1ni** [comment]
Hi, @scriptPilot !
It's the same as https://github.com/parcel-bundler/parcel/issues/1294
Unfortunately, we had to move away from parcel due to the fact, that obviously Vue isn't in the Parcel's scope.

**Comment by scriptPilot** [comment]
@houd1ni - What a pity, I thought it is ...

**Comment by mischnic** [comment]
Could someone create a minimal reproduction for this (complete JS/Vue/HTML files)?

**Comment by scriptPilot** [comment]
@mischnic - I created a repo here: https://github.com/scriptPilot/bug-f7-vue-parcel

**Comment by mischnic** [comment]
as @houd1ni said, this is a part of #1294 and this comment is correct: https://github.com/parcel-bundler/parcel/issues/1294#issuecomment-389851269

Parcel first parses/processes the vue template with HTML (not sure why to be honest) and this screws up the self-closing tags:
```js
const posthtml = require("posthtml");

const html = `
<app>
	<statusbar />
	<view main />
</app>
`;

const result = posthtml()
	.process(html, { sync: true }).html;

console.log(result);
```
Output:
```html
<app>
	<statusbar>
	<view main="">
</view></statusbar></app>
```
Now you can see why `view` is inside of the `statusbar`.

**Comment by houd1ni** [comment]
@mischnic  Hi, is there some progress on that? Or maybe it's planned or smth? Would be sad if it's just left closed.

**Comment by houd1ni** [comment]
@github-actions it's still an issue.

**Comment by mischnic** [comment]
Does this still happen with Parcel 2?
