### ISSUE TITLE
JS HMR reloads the entire page

### ISSUE THREAD

**Issue by saulfautley** [parcel-bundler/parcel#2933]
# 🐛 bug report

When changing JS the entire page is being reloaded instead of hot-reloading.

## 🤔 Expected Behavior

Changing JS should hot-reload and keep state of page.

## 😯 Current Behavior

Page is doing a full refresh and losing state.

## 💻 Code Sample

https://createapp.dev/parcel

1. `npm start`
2. open `http://localhost:1234`
3. change some code in `src/index.js`
4. entire page reloads

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             |11.13.0
| npm         | 6.7.0
| Operating System | Windows 10 x64

**Comment by saulfautley** [comment]
Tested some previous versions and it seems HMR works correctly up until Parcel v1.11.0. From v1.12.0 hot-reloading no longer works for js files, instead the page just reloads.

**Comment by DeMoorJasper** [comment]
Related to #2876 ?

**Comment by saulfautley** [comment]
@DeMoorJasper I don't think so. This is just straight up HMR not working for JS files/modules, in _any_ case as far as I can tell.

**Comment by DeMoorJasper** [comment]
@saulfautley it should work if there is a module.hot.accept or dispose?

We did change the behaviour to reload if module.hot.accept or dispose is not defined/used.

**Comment by saulfautley** [comment]
You are correct @DeMoorJasper, it works as soon as I add `module.hot.accept()` to a parent file or specific module.

May I ask why the behaviour was changed to work like this? Is there no way to just make it work "out the box" like it used to without having to include this method in my code?

**Comment by DeMoorJasper** [comment]
@saulfautley in most cases if there is not module.hot.accept it might have unexpected behaviour. events don't get removed, html elements that get added get re-added, ...

**Comment by saulfautley** [comment]
Ok makes sense, thanks for clearing that up. The docs don't really go into this so it's a bit confusing when getting started. Going to close this issue as it's clearly not a bug.

**Comment by 2999** [comment]
This bug is still on. I have the same Environment with @saulfautley  without Operating System, my OS is: macOS Mojave 10.14.5.

**Comment by saulfautley** [comment]
@2999 It's not a bug. HMR just isn't enabled by default anymore. You need to add or use `module.hot` somewhere (literally anywhere) in your JS file to enable it to use hot reloading.

**Comment by niklas** [comment]
Above Link 404s, here is the new one: https://parceljs.org/features/development/#hot-reloading
