### ISSUE TITLE
when `--target node`, *serve* should run the bundle instead of just recompiling like *watch*

### ISSUE THREAD

**Issue by danneu** [parcel-bundler/parcel#2934]
# 🙋 feature request

`parcel server.js --target node` (serve) should behave like parcel watch + nodemon.

## 🤔 Expected Behavior

`parcel server.js --target node` recompiles and runs `node server.js` on file change.

## 😯 Current Behavior

`parcel server.js --target node` is equivalent to `parcel watch server.js --target node`:  they both just recompile dist/server.js which doesn't match the symmetry of serve vs watch when --target browser.

## 💁 Possible Solution

`parcel server.js --target node` invokes `node <out>.js` after recompile.

Or remove `--target node` from the `serve` command because it doesn't do anything different from `watch`.

## 🔦 Context

Serving a browser app is great with parcel. It's just one command:

```
parcel client.js
```

But serving a Node app involves two separate watchers:

```
parcel server.js --target node
nodemon dist/server.js
```

This is especially tedious when you're building a client and server at the same time: you're juggling three terminal windows. 

Ideally it would just be:

```
parcel client.js --port 3000
parcel server.js --port 4000
```

**Comment by DeMoorJasper** [comment]
I will create a node.js hmr reporter for Parcel 2. If I don't forget :)

**Comment by RamIdeas** [comment]
Apologies for commenting on a closed issue but it was marked "Duplicate" and I can't find that other issue.

Was this implemented in v2?

**Comment by mischnic** [comment]
Probably https://github.com/parcel-bundler/parcel/issues/2493, I think it's not yet implemented
