### ISSUE TITLE
npm i parcel vs. npm i parcel-bundler

### ISSUE THREAD

**Issue by bstro** [parcel-bundler/parcel#2937]
# ❔ Question

The `parcel` package on `npm` appears to be an alias of some kind for `parcel-bundler` but it is unclear if this entry is maintained by the official Parcel team because of the lack of a functional README. It seems like it ought to be, and it is easy to forget to run `npm i parcel-bundler` when starting a new project… out of sheer forgetfulness, I have run `npm i parcel --save-dev`.

Are both valid and official ways of installing Parcel? If so, then the `parcel` package ought to look a little more official. See [https://www.npmjs.com/package/parcel](https://www.npmjs.com/package/parcel)

**Comment by devongovett** [comment]
Yes, the “parcel” package is officially maintained. The history is that when parcel first launched, the “parcel” package was unavailable on npm. At some point we managed to acquire the package but continued to support both for backward compatibility. Parcel 2 will drop the “parcel-bundler” package in favor of “parcel”.
