### ISSUE TITLE
How can I get the URL of a file inside a service worker?

### ISSUE THREAD

**Issue by quadrupleslap** [parcel-bundler/parcel#2939]
# ❔ Question

How can I get the URL of a file inside my service worker? I probably want something like `url_for('./index.js')`.

Edit: I decided to use https://github.com/mugi-uno/parcel-plugin-bundle-manifest and it's working well so far. It'd be nice if someone could confirm that there isn't a much better approach.

## 🔦 Context

I'm trying to add offline support to my app.

## 💻 Code Sample

```js
// service-worker.js

const CACHED = [
  '.',
  // These two don't work thanks to name mangling (and scss → css).
  './index.scss',
  './index.js'
];

...
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 11.14.0
| npm/Yarn         | 6.9.0
| Operating System | Linux 5.0.7

**Comment by quasicomputational** [comment]
#2306 would be a generic solution so long as the set of assets you want to reference is known statically. I don't think there's a way to do this sort of thing today that doesn't involve a plugin.

**Comment by mischnic** [comment]
There is currently no better way to achieve this. (Could personally see this being added using `require.resolve(...)` returning the output path)
