### ISSUE TITLE
🐛 Parcel Bundling issues

### ISSUE THREAD

**Issue by ssuman** [parcel-bundler/parcel#294]
🐛 bug report
Parcel currently builds a bundle tree. While building the tree, if it finds a common module, it finds the common ancestor bundle and places the common module in that ancestor bundle. Now this only works if the asset's parent bundle and the common bundle are the same type. For example: both are of type JS.

There are various cases where the asset's parent bundle type is not the same as the common bundle type. Few cases shown below - 

Case (i):
<img width="376" alt="screen shot 2017-12-14 at 12 39 10 pm" src="https://user-images.githubusercontent.com/2545586/34017432-bc404a64-e0f3-11e7-95e5-84c69ee8c244.png">

case (ii):
<img width="385" alt="screen shot 2017-12-14 at 5 26 47 pm" src="https://user-images.githubusercontent.com/2545586/34017509-09a12292-e0f4-11e7-8966-b5096b754b62.png">

case (iii): 
<img width="396" alt="screen shot 2017-12-14 at 5 27 39 pm" src="https://user-images.githubusercontent.com/2545586/34017551-3467d9f8-e0f4-11e7-8fcd-f441b92b1c13.png">

### 🤔 Expected Behavior

case (i): Util.js should be bundled in both bundles B2 and B3.

case (ii): Not sure, but I think a hashed Util.js file should be referenced in index.html. Additionally, util.js should also be present in Bundles B2 and B3.

case (iii): A stylesheet should be appended to the head of both html files ( index.html and other.html).

### 😯 Current Behavior
case (i): Util.js is present only in bundle B2. So we get module not found exception.

case (ii): Same as case i. In addition, html file has a hash reference to util.js but is never created.

case (iii): CSS stylesheet is appended only to either other.html or index.html based on the order of execution.

### 💁 Possible Solution
I'm not 100% sure. I think we need to treat each html nodes as boundaries. The common chuck can't be moved beyond the boundary. It should be treated as an isolated entity. Although I'm not sure if this would address all the cases. But would love to work on this PR after some discussion,

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  
| Node             | 8.4.0
| npm/Yarn         | 5.3.0
| Operating System | MacOS Sierra 10.12.1

**Comment by mBeierl** [comment]
This issue is real, discussed in #326 and [reproducible with this repo](I created a sample project to easily reproduce this issue: https://github.com/mBeierl/parcel-bug-same-asset-loading).

**Comment by devongovett** [comment]
Should be fixed by #380.
