### ISSUE TITLE
Minified function name not updated in html event handler attribute

### ISSUE THREAD

**Issue by Benjozork** [parcel-bundler/parcel#2940]
# 🐛 bug report

When a JS function in a `<script>` is minified, references to that function in `onclick, onscroll, onload ...` are not renamed to the minified name.

Examples:

Original function

```js
function updateHeaderFromScroll() {

    var bodyScroll = document.scrollingElement.scrollTop;

    if (bodyScroll > initSize / 2) {
        header.style.height = "7em";
        logo.style.height   = "425px";
    } else if (bodyScroll < initSize / 2) {
        header.style.height = "10em";
        logo.style.height   = "500px";
    }
}
```

Minified function

```js
function e(){var e=document.scrollingElement.scrollTop;e>n/2?(t.style.height="7em",o.style.height="425px"):e<n/2&&(t.style.height="10em",o.style.height="500px")}
```

Original function call in HTML event handler attribute

```html
<body onscroll="updateHeaderFromScroll()" ... >
```

Output function call

```html
<body onscroll="updateHeaderFromScroll()" ... >
```

As you can see, those are not changed and therefore the function cannot properly be called.

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`

```json
{
    "name": "<redacted>",
    "version": "1.0.0",
    "description": "",
    "main": "index.html",
    "scripts": {
        "run": "npm run parcel-dev",
        "deploy": "npm run parcel-bld && npm run deploy-upload",
        "parcel-dev": "parcel ./site/index.html --log-level 4 --open",
        "parcel-bld": "parcel build ./site/index.html --log-level 4",
        "deploy-upload": "cd scripts && upload.bat %CD%\\dist\\ /var/www/html/"
    },
    "keywords": [],
    "author": "<redacted>",
    "license": "MIT",
    "dependencies": {
        "autoprefixer": "^9.5.1",
        "parcel": "^1.12.3"
    },
    "devDependencies": {
        "cssnano": "^4.1.10",
        "postcss-modules": "^1.4.1"
    }
}
```

`.postcssrc`

```json
{
  "plugins": {
    "autoprefixer": {
      "grid": true
    }
  }
}
```

## 🤔 Expected Behavior

Minified function names should also be updated in html event handler attributes

## 😯 Current Behavior

Minified function names are not updated in html event handler attributes

## 💁 Possible Solution

Use DOM event handlers instead, but that's not a fix

## 🔦 Context

Working on a website.

## 💻 Code Sample

Cannot upload a code repository, contents are private 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.13.0
| npm/Yarn         | 6.4.1
| Operating System | Windows 10 18875

**Comment by kzc** [comment]
This is due to the `toplevel` option being enabled in the minifier either by Parcel or user config. One such instance:

https://github.com/parcel-bundler/parcel/blob/8deb85d95e19ab39a5143489eabfbca13cc59663/packages/core/parcel-bundler/src/transforms/terser.js#L14-L16

Perhaps if scope hoisting is disabled then the bundled app would work correctly.

See also: `reserved` and `top_retain` minifier options.
