### ISSUE TITLE
🐛 npm install error on aws-sdk dependency

### ISSUE THREAD

**Issue by mycaule** [parcel-bundler/parcel#295]
Bug report

```bash
$ npm install -g parcel
npm ERR! code ETARGET
npm ERR! notarget No matching version found for aws-sdk@0.9.x
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'parcel'
npm ERR! notarget
$ node --version
v8.9.3
$ npm --version
5.5.1
```

**Comment by mycaule** [comment]
I just realized that there is another `parcel` NPM package, sorry.

**Comment by philipodev** [comment]
`npm install -g parcel-bundler` is the correct one :)

**Comment by adamreisnz** [comment]
Lol.. why is there a `parcel` one :(

**Comment by TomasHubelbauer** [comment]
@bayareagamedevs, @honnet, @jaredhanson, @kellydunn, @liamstask, @maxattack or @scanlime, would you guys be willing to donate the package name? `parcel` has not been updated in five years, I think it's not maintained anymore?
