### ISSUE TITLE
What is Bundler Middleware?

### ISSUE THREAD

**Issue by stoplion** [parcel-bundler/parcel#2954]
Does the bundle middleware for express wrap the server created by running `parcel index.html`? Is this only something to be run in development? 
Would be glad to contribute to documentation if there were more details.. 

Also.. is it possible to bundle server/Express code? 
Thanks!

**Comment by devongovett** [comment]
Yeah, the middleware is not meant for production. You can use it to integrate with an existing local development server. https://parceljs.org/api.html#middleware
