### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by wangyajundev** [parcel-bundler/parcel#2957]
Cannot read property 'length' of undefined
    at lineCounter (/Users/www/repository/parcel-demo/node_modules/_parcel-bundler@1.12.3@parcel-bundler/src/utils/lineCounter.js:3:30)
    at JSPackager.writeModule (/Users/www/repository/parcel-demo/node_modules/_parcel-bundler@1.12.3@parcel-bundler/src/packagers/JSPackager.js:127:60)
    at <anonymous>

**Comment by quasicomputational** [comment]
Looks very much like #1158.

**Comment by wangyajundev** [comment]
I deleted node _ module, redownloaded it, and reported it wrong

**Comment by cloudever** [comment]
Same issue. I've found some thing

![image](https://user-images.githubusercontent.com/16993305/56735301-c3779100-676d-11e9-89f4-92582de757e6.png)

**Comment by joshuazmiller** [comment]
FYI to solve I deleted `.cache` directory. Ran `parcel src/index.html -t node`, stopped running, and then ran my regular `parcel src/index.html`.

**Comment by wangyajundev** [comment]
@joshuazmiller you are right.

**Comment by Shuunen** [comment]
Deleting `.cache` folder worked on my side, without `-t node` restart thing

Thanks @joshuazmiller 👍

**Comment by hmmhmmhm** [comment]
@joshuazmiller thanks! you saved me on 2020!

**Comment by tiennsloit** [comment]
Deleting `.cache` folder also worked for me, no need  `-t node`. Thanks so much @joshuazmiller

**Comment by lildev** [comment]
I just installed 1.12.3 version. It worked for me. `yarn add parcel-bundler@1.12.3`

**Comment by gauravrajdeo** [comment]
Deleting .cache folder worked for me too. Thanks, @joshuazmiller

**Comment by BogdanConstantinDEV** [comment]
> Deleting `.cache` folder worked on my side, without `-t node` restart thing
> 
> Thanks @joshuazmiller 👍

This worked for me too
