### ISSUE TITLE
error when used with parcel

### ISSUE THREAD

**Issue by hanzichi** [parcel-bundler/parcel#2959]
# 🐛 bug report

step by the [official docs](https://en.parceljs.org/recipes.html#preact)

## 😯 Current Behavior

![123](https://user-images.githubusercontent.com/10890665/56781182-d72a0280-6814-11e9-8044-e497f288d489.jpg)

The error is caused for [babel-preset-preact](https://github.com/developit/babel-preset-preact) does not support Babel7, but parcel uses babel7 as default

**Comment by DeMoorJasper** [comment]
You can install babel-core 6 and parcel will detect it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hanzichi** [comment]
I think the docs should make some explainations for it @DeMoorJasper

**Comment by DeMoorJasper** [comment]
@hanzichi feel free to add it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hanzichi** [comment]
I'll try it later @DeMoorJasper

**Comment by debasissahu** [comment]
When I am using parcel getting this error. Please suggest!

![Error](https://user-images.githubusercontent.com/46349396/56791894-e06f9b00-6825-11e9-9644-06247f5fcb75.PNG)

**Comment by hanzichi** [comment]
@DeMoorJasper [pr](https://github.com/parcel-bundler/website/pull/432) added

**Comment by DeMoorJasper** [comment]
@debasissahu this is unrelated please open a seperate issue

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
