### ISSUE TITLE
🙋 Provide a typing file to allow better auto completion

### ISSUE THREAD

**Issue by octref** [parcel-bundler/parcel#296]
I'm using parcel-bundler programmatically in node, and I would like to get auto-completion on the API. This can be achieved by writing a TypeScript definition file and included it in the npm distribution.

This wouldn't be very large, since you are only exporting a `Bundler` object, so only that class constructor needs to be typed.

I can write one if you are interested.

**Comment by Ty3uK** [comment]
Also need typings for Asset and Packager classes too.

**Comment by octref** [comment]
@DeMoorJasper Why is this feature request closed?

**Comment by DeMoorJasper** [comment]
Parcel 2 will be typed, that's why I closed it.

**Comment by octref** [comment]
Sounds good. Thanks.
