### ISSUE TITLE
The first screen uses preloading, is there a package?

### ISSUE THREAD

**Issue by wangyajundev** [parcel-bundler/parcel#2960]
1、The first screen uses preloading, is there a package? 

2、How to package into a custom directory？

**Comment by mischnic** [comment]
1) Are you talking about `<link rel="preload" href="thing.js" as="script">` ?
This is not supported by Parcel. Are you searching for a *plugin* to do that?

2) `parcel build index.html --out-dir output` ?

**Comment by wangyajundev** [comment]
Yes.
1. I need a plugin,Is there a recommendation?
2. I want to output a directory: 
-dist
  -css
  -js
  -img

**Comment by mischnic** [comment]
> I need a plugin,Is there a recommendation?

Unfortunately no.

> I want to output a directory:

That's not possible at the moment.
