### ISSUE TITLE
Error: Cannot find module './lib/fs'

### ISSUE THREAD

**Issue by debasissahu** [parcel-bundler/parcel#2961]
See the yellow mark error, when I am using parcel in a simple test app: 

![Error](https://user-images.githubusercontent.com/46349396/56795632-86bf9e80-682e-11e9-8607-81ad03122f62.PNG)

**Comment by DeMoorJasper** [comment]
Use Node 8 as a workaround

**Comment by mischnic** [comment]
Duplicate of https://github.com/parcel-bundler/parcel/issues/2533
