### ISSUE TITLE
@babel/core installed in subpackage of monorepo

### ISSUE THREAD

**Issue by samrith-s** [parcel-bundler/parcel#2968]
# ❔ Question

I have two `package.json`s. Whenever I do a `bundler.serve`, it adds `@babel/core` as a dev-dependency in the subdirectory. Why does this happen?

## 🔦 Context

I have the following structure:
```elm
ROOT
⇢ package.json
⇢ packages
  ⇢ themes
    ⇢ package.json
```

I run my `start` command from the `ROOT` directory, which already has `@babel/core` installed as a dependency.

Whenever my `start` command runs it does `bundler.serve`. When this happens, Parcel installs `@babel/core` in `packages/themes/package.json`, but nothing else. Everything else it picks up from the root folder.

Why is this happening? This means that when I publish the internal package on NPM, it will have `@babel/core` as a dev dependency, which it doesn't need.

## 💻 Code Sample

The structure I am talking about can be found here: https://github.com/markeroo/markeroo-themes

The two `package.json` files can be found here:
- Main: https://github.com/markeroo/markeroo-themes/blob/master/package.json
- Internal: https://github.com/markeroo/markeroo-themes/blob/master/packages/themes/package.json

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.11.0
| npm/Yarn         | 1.15.2
| Operating System | macOS Mojave

**Comment by DeMoorJasper** [comment]
Parcel looks for the nearest package.json to the entrypoint

**Comment by samrith-s** [comment]
Is there any way to disable it? That is quite a weird behaviour, when there is all the information present for Parcel to use the `package.json` in the `ROOT` folder.

**Comment by DeMoorJasper** [comment]
@samrith-s there is no way to disable this, babel actually does not go up the folder either for a babelrc file afaik. So it’s actually pretty common.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by samrith-s** [comment]
That is weird, coz from what I can tell, it does. 

We already have `__dirname`, in the process which spawns Parcel. Which means, we can pick up the `package.json` using `__dirname`? In this case, it would be the one in the `ROOT` folder.

Is there any way I can check it out? And maybe raise a PR or something? Where'd you advise I start looking?

**Comment by mischnic** [comment]
> We already have __dirname, in the process which spawns Parcel.

No, `__dirname` would be something like `node_modules/parcel-bundler/...`

There is a logical inconsistency between `rootDir` and the project root and the nearest package root.

In this case,  we would need to look further up when searching for @babel/core (until the "project root", which should contain .git/yarn.lock/...) 
https://github.com/parcel-bundler/parcel/blob/7ad25fd0958cb39c8595a0d667e9bc0f4c0250f4/packages/core/parcel-bundler/src/transforms/babel/babelrc.js#L155-L159
Parcel 2 already has the notion of "project root" and will also handle babel slightly differently.
