### ISSUE TITLE
will parcel provide `alias`?

### ISSUE THREAD

**Issue by lessfish** [parcel-bundler/parcel#2970]
Will parcel provide `alias` function as other bundle does?

thanks

**Comment by mischnic** [comment]
Could you please be more specific and maybe even give an example of what you mean?

This: https://parceljs.org/module_resolution.html#aliases ?

**Comment by lessfish** [comment]
@mischnic 
thanks for your reply. I check the docs, as it points out:

> This example aliases react to preact and some local custom module that is not in node_modules

so another question, how to aliases react to preact that is **in** the node_modules? That's my usage scenarios

**Comment by DeMoorJasper** [comment]
@lessfish the example shows exactly that?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lessfish** [comment]
@DeMoorJasper  Sorry but I don't really understand what you mean. In my case I want to use preact with parcel, I need to use some React lib, so I need to use `alias`, but it does not work in the node_modules as the docs say

**Comment by mischnic** [comment]
I don't quite understand what's your issue, this works:

package.json:
```json
{
  "alias": {
    "react": "preact"
	}
}
```
I was then able to use `import {Controlled as CodeMirror} from 'react-codemirror2';` without any issues.

**Comment by lessfish** [comment]
well, it seems my issue, sorry
