### ISSUE TITLE
Importing wasm without file extension doesn't resolve

### ISSUE THREAD

**Issue by sahil-bansal-sb** [parcel-bundler/parcel#2973]
Please check on:
https://github.com/rustwasm/wasm-pack/issues/638#issue-440145450

**Comment by mischnic** [comment]
Can't reproduce:
```
niklas@nmb:2973 $ cargo generate --git https://github.com/rustwasm/wasm-pack-template
error: no such subcommand: `generate`
niklas@nmb:2973 $ cargo --version
cargo 1.34.0 (6789d8a0a 2019-04-01)
niklas@nmb:2973 $
```

**Comment by mischnic** [comment]
```js
import * as wasm from './abc';
```
Fails to resolve to `./abc.wasm`. Seems like a bug.

**Comment by sahil-bansal-sb** [comment]
So, if it's a bug from Parcel, should i close the issue in wasm repo?

**Comment by mischnic** [comment]
> should i close the issue in wasm repo?

If you want. This error is from Parcel, not wasm-pack.

**Comment by sahil-bansal-sb** [comment]
> If you want. This error comes from Parcel, not wasm-pack.

Ok then, I am going to comment in that issue a link to this issue and close that one.

**Comment by kellytk** [comment]
How could this issue be progressed?
