### ISSUE TITLE
--experimental-scope-hoisting not working with rollup build

### ISSUE THREAD

**Issue by IdoJS** [parcel-bundler/parcel#2981]
# 🐛 bug report

in the following [example](https://github.com/IdoJS/experimental-scope-hoisting) you can see a problem with --experimental-scope-hoisting when using rollup build cjs

## 🤔 Expected Behavior
``` gherkin
Given a project with lerna and multiple packages
```

|package| build | script|
|--------|-------|------|
|hoistexample-rollup| rollup | rollup src/index.js --file lib/index.js --format cjs
|hoistexample-ts | ts |  tsc --module commonjs --target es5 --outDir lib

```gherkin
When a main package imports the packages 
And bundle it all with 
 # parcel build -o build index.js  --experimental-scope-hoisting --no-minify 
Then  parcel change the variables name of the rollup build correctly as it does for ts build
```

## 😯 Current Behavior

``` gherkin
Given a project with lerna and multiple packages
```

|package| build | script|
|--------|-------|------|
|hoistexample-rollup| rollup | rollup src/index.js --file lib/index.js --format cjs
|hoistexample-ts | ts |  tsc --module commonjs --target es5 --outDir lib

```gherkin
When a main package imports the packages 
And bundle it all with 
 # parcel build -o build index.js  --experimental-scope-hoisting --no-minify 
Then parcel change the variables name of the rollup build incorrectly 
And runtime throw exception of ReferenceError
```

## 💁 Possible Solution

you can see from the [example](https://github.com/IdoJS/experimental-scope-hoisting)
that the problem occurs when doing the export in one line.
 ```
export class failurtestHositingRollup2 {
  static create() {
    return new failurtestHositingRollup2();
  }
};

export default class failurtestHositingRollup {
  static create() {
    return new failurtestHositingRollup();
  }
}

```
## 💻 Code Sample

**parcel bundle with ts import build:**
```js
var $sbuw$var$testHositing =
/** @class */
function () {
  function testHositing() {}

  testHositing.create = function () {
    return new testHositing();
  };

  return testHositing;
}();
```

**parcel bundle with rollup import build:**
```js

class $gcK$var$failurtestHositingRollup {
  static create() {
    return new failurtestHositingRollup();
  }

}
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| parcel-bundler           |1.6.1
| Node             | v10.15.0
| Yarn         | 1.12.3
| Operating System | MAC

**Comment by devongovett** [comment]
I believe this is a bug in Babel's scope tracking. See here for a reduced test case: https://astexplorer.net/#/gist/f1cb0faddd7b06a58e34f59051c78c39/ebab99e1bb5f0be982245db354e9b4abd48c9741.

The console.log in that example outputs `1` reference to `Test` (the export declaration) when it should output `2` (including the reference in `create`). If you comment out the call to `path.scope.crawl()` however, it does output `2` correctly, so something about calling `crawl` again is messing it up. I tried removing our call to `crawl` in the scope hoisting code, but that broke other tests. Not sure what's going on there.

**Comment by devongovett** [comment]
Managed to work around the issue by clearing babel's scope cache before we re-crawl. #2986
