### ISSUE TITLE
Add PostCSS dependency message support

### ISSUE THREAD

**Issue by ai** [parcel-bundler/parcel#2983]
# 🙋 feature request

PostCSS ecosystem has an unofficial API: plugins add `dependency` message for every resource used by this plugin:

```js
let css = `
.icon {
  background: inline-svg(./logo.svg)
}
`

const result = await postcss([inlineSVG]).process(css)
result.messages() // => [{ type: 'dependency', file: '/Dev/project/logo.svg' }]
```

`postcss-loader` and other PostCSS runners [use](https://github.com/postcss/postcss-loader/blob/master/src/index.js#L149-L153) this message to start watching for used resources.

Let’s add it to Parcel too.

## 🤔 Expected Behavior

Parcel will watch for resources from `dependency` messages and re-build bundle on resource’s changes.

## 😯 Current Behavior

Seems like Parcel doesn’t use it.

## 💁 Possible Solution

Just check `result.messages().filter(i => i.type === 'dependency')` after PostCSS call.

## 🔦 Context

Lack of this feature was found in Tailwind community since the lack of `dependency` support creates unexpected behavior:

https://twitter.com/kevdotbadger/status/1125415276097544193

Here is our small talk with @adamwathan

https://twitter.com/adamwathan/status/1125417346154106881

## 💻 Examples

Here is a small project to test the feature:

https://github.com/adamwathan/parcel-postcss-dependency-message

**Comment by ai** [comment]
@devongovett if you like this feature, but have no time to implement it, I can ask my friends to help.

**Comment by mischnic** [comment]
> Parcel will watch for resources from dependency messages and re-build bundle on resource’s changes.

This would solve an issue supporting postcss import plugins would have https://github.com/parcel-bundler/parcel/issues/1165#issuecomment-467499449
