### ISSUE TITLE
Parcel not finding .env variables in client JS

### ISSUE THREAD

**Issue by captDaylight** [parcel-bundler/parcel#2984]
I have a simple setup, `.env` file at the same level as my `package.json` with simply:
```
API_URL=http://localhost:8080
```
Then, in my client app I've tried something like:
```javascript
console.log(process.env);
// {}
```
I've tried deleting my `.cache` but no dice. My parcel version is `1.12.3`.

**Comment by mischnic** [comment]
> console.log(process.env);

`process.env.API_URL` does work. I don't know if that's a bug or intended...

**Comment by DeMoorJasper** [comment]
`process.env` doesn't get inlined entirely for security reasons afaik.

you should be more specific as @mischnic mentioned

**Comment by captDaylight** [comment]
Ah ok, yup that was it. I don't understand how that works, but it works.

**Comment by avalanche1** [comment]
I'd like to learn how this is realized :wow:
