### ISSUE TITLE
Markdown Support for `.markdown` files

### ISSUE THREAD

**Issue by wesleyboar** [parcel-bundler/parcel#2985]
# 💬 RFC

I am grateful for Parcel's [existing support](https://github.com/parcel-bundler/parcel/issues/2274) (and [future support in version 2](https://github.com/parcel-bundler/parcel/pull/2882)) for Markdown, but it has a defect (ignoring `.markdown` files) that I do not want to report, because I am taking advantage of that defect to avoid needing [the unavailable feature to ignore certain assets](https://github.com/parcel-bundler/parcel/issues/1186).

What should I do?

## 🔦 Context

I want to link to a Markdown asset, but do not want that asset parsed into an `.html` file.

The use case is:
- (optional) I have an established markdown-to-html workflow.
- I have a direct link to the Markdown asset (for users that want it raw and unfiltered).

I have avoided having the Markdown asset parsed into `.html` by using the long file extension `.markdown` instead of the registered filename extension `.md`.

## 💻 Examples

```html
<p>Instead, <a href="./timeline.html" target="_blank" title="Timeline (as webpage)">open the timeline directly</a> or <a href="./timeline.markdown" target="_blank" title="Timeline (as document)">download the Markdown file</a>.</p>
```

If I link to (and name the file) `timeline.md`, then the `timeline.md` is parsed as `timeline.html`.*

_\* The generated `timeline.html`, by the way, would overwrite my existing `timeline.html` from my established markdown-to-html workflow (I tested this). But, this issue is satellite to my primary concern, because I can solve this issue by merely renaming the file or moving it to another directory._

## 📚 Reference

- [feature request for Markdown support](https://github.com/parcel-bundler/parcel/issues/2274)
- [pull request to Parcel 2 for Markdown feature support enhancements](https://github.com/parcel-bundler/parcel/pull/2882)
- [source code that shows only \`.md` is registered as a Markdown document](https://github.com/parcel-bundler/parcel/blob/bec96be61d8a74399b66ec6df981524c11c11b8c/packages/core/parcel-bundler/src/Parser.js)
- [feature request to ignore links to certain assets](https://github.com/parcel-bundler/parcel/issues/1186)

**Comment by VinceOPS** [comment]
Having the exact same issue today! @wesleyboar May I ask you if you ended with a workaround for this? Thanks

**Comment by wesleyboar** [comment]
You may. I have thought of three additional workarounds.

1. I have resolved my specific issue by no longer offering the markdown file for download. _I realized that a greater percent of my user base would prefer a link to an unstyled `.html` page in the browser than to download an unfamiliar extension. 😅_

2. Search issues and docs for an easy way to configure Parcel "ignore" certain files while bundling. Good luck. Configuration is something Parcel ardently avoids.*

3. Perhaps this is a "long way" to ignore certain files: I believe one can (note, I have not tried, because I no longer have the need) avoid parsing certain files 
by using the [Parcel Bundler API](https://parceljs.org/api.html). Specifically, I propose, after recreating CLI command via Node script that uses the API, to listen to an event and then cancel or manipulate (if either is possible) the bundling of certain files or directories.

_/* Configuration (beyond CLI commands) is not provided by Parcel, nor is it likely. This statement is supported by issue discussions that I have read but which I am not convenient to link to (I am typing this message on a phone)._

**Comment by wesleyboar** [comment]
I am hoping to open a new issue, a proper bug report, not an RFC, about the support for `.markdown`. So, I will close this issue.

The bug report will likely reuse some of this post. I am not in a hurry to do this, because Parcel 2 is not out, and it may be a couple minor versions before the completed markdown support is integrated.*

If someone wants to report it before me, and even reference or steal some copy from this, go ahead.

_\* Normally, I would link to these events about which I mention, but I am on a phone, so it is too cumbersome, at the moment. I may come back and edit comment, tomorrow._

**Comment by VinceOPS** [comment]
Thanks for answering! I actually ended up using `.markdown` as an extension, a few minutes after asking on this thread, because I noticed that the Markdown parser was only caring for `.md`.  
Thus, I have Parcel bundling my `.markdown` files, and I'm able to pass their URIs to the lib consuming them.  
Sorry for not telling it earlier :pray: 

Have a nice day!
