### ISSUE TITLE
do u support cmd?

### ISSUE THREAD

**Issue by Sobranier** [parcel-bundler/parcel#30]
index.js:

```
import main from './main';
//
main();
```

main.js:

```
export default () => {
    console.log(classes.main);
};
```

result:

<img width="253" alt="2017-12-06 11 43 04" src="https://user-images.githubusercontent.com/7440073/33643905-b80dae96-da7c-11e7-89f8-1e6b4cd64ff6.png">

**Comment by thejameskyle** [comment]
This is not enough information to go off of, please provide something that we can reproduce and I'll reopen this issue.
