### ISSUE TITLE
🐛 CSS Module not found

### ISSUE THREAD

**Issue by kennetpostigo** [parcel-bundler/parcel#300]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
🐛

### 🎛 Configuration (.babelrc, package.json, cli command)
No config

### 🤔 Expected Behavior
It should find the css module, I think the issue is that the path referenced in the source file does not work from where parcel outputs the bundle.

### 😯 Current Behavior
I have a folder that has my `src` files, then a folder that holds `assets` like css, images, etc. and at the root of the project I have my `index.html`. When I `import 'path/to/my/css/styles.css'` from the javascript file parcel bundles it and shows that everything is okay. When I go view the page I get an error saying `Error: Cannot find module '14'`

### 🔦 Context
Just trying to import some css, app doesn't render b/c of the error
### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  1.2.0
| Node             | 8.9.1
| npm/Yarn         | Yarn 1.3.2
| Operating System | osx

**Comment by brandon93s** [comment]
A lot has changed and been fixed since this issue was opened! Please give a newer release of Parcel a try and let us know if the issues persists. Thanks.

**Comment by rambo-panda** [comment]
@brandon93s 

If CSS files are introduced asynchronously (like` import('a.scss')`), the problem persists

This is my solution.

https://github.com/parcel-bundler/parcel/blob/a0df88665f00330c0f8265233308d1a590087868/src/builtins/loaders/browser/css-loader.js#L10-L14

```js
    link.onload = function () {
      link.onerror = link.onload = null;
      resolve({});  //  CSS file should export empty object.  stop continuing searching and registration Modules
    };
```
