### ISSUE TITLE
Error: Cannot find module 'react'

### ISSUE THREAD

**Issue by alex-cory** [parcel-bundler/parcel#3003]
# 🐛 bug report

Not able to use npm package (react hook) in a `create-react-app` app without having `react` as a `dependency`.   It should be able to work in `peerDependencies` and `devDependencies` only. When I use my package ([react-useportal](https://github.com/alex-cory/react-useportal)) in [codesandbox](https://codesandbox.io/s/6wlv9990p3) it works fine, and it also works fine when I run local samples via `parcel examples/index.html --open`.  **It seems like it doesn't work in a webpack app when bundled with parcel.**

I was doing some debugging to just see what other people did for there npm packages and here's what I found.

@rehooks/component-size
- parcel
- NO react as dependency -> only peerDependencies + devDependencies
BREAKS^

@rehooks/document-title
- parcel
- HAS react as dependency -> also devDependency
WORKS^

alex-cory/react-useportal
- parcel
- NO react as dependency -> tried with only peerDependencies, only devDependencies, and both. None worked
BREAKS^

@rooks/use-did-mount
- rollup
- NO react as dependency -> only peerDependencies
WORKS^

## 🎛 Configuration (.babelrc, package.json, cli command)

[package.json](https://github.com/alex-cory/react-useportal/blob/master/package.json)

## 🤔 Expected Behavior

Should work in an app that uses webpack as the bundler without having `react` in `dependencies` in `package.json`.

## 😯 Current Behavior

`Error: Cannot find module 'react'`
![image](https://user-images.githubusercontent.com/5455859/57431947-4296ab80-71e9-11e9-8711-48746a4eb04b.png)

## 💁 Possible Solution

Try using [microbundle](https://github.com/developit/microbundle) or [rollup](https://github.com/rollup/rollup) (which I don't want to do)

## 🔦 Context

I'm trying to have my package work in all react apps.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.12.3
| Node             | v11.4.0
| npm/Yarn         | both (but mostly yarn 1.12.1) npm 6.4.1
| Operating System | osx

**Comment by mischnic** [comment]
I used the codesandbox demo and ran it in Parcel, there was no error.

> NO react as dependency -> tried with only peerDependencies, only devDependencies, and both. None worked

This is not how peerDependencies work. Specifying a package in `peerDependencies` means: I want to use a package but not install it myself during npm install (usually to prevent a version mismatch when bundling).

**Comment by alex-cory** [comment]
So... why can some other react hook npm packages have react only as a peer dependency and still work? Did you try:
1. `create-react-app test`
2. `cd ./test`
3. `yarn`
4. `yarn add react-useportal`
5. `yarn start`
This issue is only coming up when I run this locally using the steps above. This issue doesn't occur in the packages above that I said `WORKED^`

**Comment by alex-cory** [comment]
potentially I need to update `create-react-app` I haven't tried this yet. Lemme give that a shot and report back

**Comment by DeMoorJasper** [comment]
`So... why can some other react hook npm packages have react only as a peer dependency and still work`
This is to prevent version mismatch as @mischnic mentioned.
Having React as a peer dependency means it will use the React package that is installed in the project that requires this package. (so you should install react in your project and it will use that version, preventing version mismatch) They could also just not add it to pkg.json at all but that wouldn't throw warnings if the peerDepency is missing.

**Comment by alex-cory** [comment]
I think you're misunderstanding what I'm trying to figure out. I need the `react-useportal` package to only have `react` in peerDependencies.

When I do this, I get the `Error: Cannot find module 'react'`. After reviewing other people's packages, and attempting to use them in a `create-react-app` application, I got the results that are shown in my first post.

You can see that out of the 4 examples, 1 uses a different bundler. Of the 3 that use parcel, the only one that works is the one that has `react` as a dependency.

**Comment by alex-cory** [comment]
It's ok, I ended up switching to Typescript and everything seems to work fine now. I think the problem here is for some reason, parcel is causing duplicate versions of react. Not exactly sure why but [this](https://reactjs.org/warnings/invalid-hook-call-warning.html) helped me. [Here's what I searched](https://www.google.com/search?q=react+debugging+duplicate+versions+of+react&oq=react+debugging+duplicate+versions+of+react&aqs=chrome..69i57j0l5.7224j0j1&sourceid=chrome&ie=UTF-8).

**Comment by styrken** [comment]
Was having same issue and ended up by switching to microbundle for my npm packages and in my main project using parcel..

**Comment by styrken** [comment]
I also tested out rollup and it works as well.

My point: Do not use parcel for reusable react packages. Use it only in your main project.

**Comment by mischnic** [comment]
Parcel 1 is definitely not ideal for libraries
