### ISSUE TITLE
can I disable urlPlugin in LESSAsset?

### ISSUE THREAD

**Issue by acobster** [parcel-bundler/parcel#3016]
# 🙏 Thanks!

First of all, thank you for your work on Parcel. :)

# ❔ Question

`LESSAsset` always adds `urlPlugin(this)` to the list of plugins that run when a LESS asset is parsed. Is there any way to tell it _not_ to do this?

## 🔦 Context

I have a custom build script that compiles `/less/style.less` to `/style.css` (in the root because this is WordPress, which requires the presence of `style.css` in the theme root). In turn, `style.less` references files in `/img/`, as do other server-rendered templates, such as Twig files that we don't manage with Parcel.

I want the final image URLs output in the CSS to start with `/img/`, but the `urlPlugin()` function seems to only look for these inside `/less`, where they don't exist. The simplest fix I've found is simply commenting out [this line](https://github.com/parcel-bundler/parcel/blob/8deb85d95e19ab39a5143489eabfbca13cc59663/packages/core/parcel-bundler/src/assets/LESSAsset.js#L24), which add the `urlPlugin()` call no matter what.

Is there a way to configure Parcel to not add this plugin?

## 💻 Code Sample

GH repo with repro steps here: https://github.com/sitecrafting/parcel-urlplugin-issue

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3 |
| Node             | 10.15.3 |
| Yarn         | 1.16.0 |
| Operating System | Ubuntu 18.04 |

**Comment by acobster** [comment]
Can someone comment on this? Right now, this is the only obstacle to our adopting Parcel as our go-to JS/LESS bundler.

**Comment by provegard** [comment]
I have this problem as well. I invoke Parcel as a custom Grunt task, so my first attempt was to patch `less.render` (to remove the plugin), but that stops working in watch mode as Less rendering is moved to a child process.

**Comment by provegard** [comment]
This works much better:

    const bundler = new Bundler(src, options)
    bundler.addAssetType("less", require.resolve("./LESSAssetNoUrlPlugin"))

Where `LESSAssetNoUrlPlugin` is:

```javascript
const { Asset } = require("parcel-bundler");
const {promisify} = require("@parcel/utils");
const path = require("path");
const less = require("less");

class LESSAssetNoUrlPlugin extends Asset {
    constructor(name, options) {
        super(name, options);
        this.type = "css";
    }

    async parse(code) {
        let render = promisify(less.render.bind(less));

        let opts =
            (await this.getConfig([".lessrc", ".lessrc.js"], {packageKey: "less"})) ||
            {};
        opts.filename = this.name;
        opts.plugins = opts.plugins || [];
        if (this.options.sourceMaps) {
            opts.sourceMap = {outputSourceFiles: true};
        }

        return render(code, opts);
    }

    collectDependencies() {
        for (let dep of this.ast.imports) {
            this.addDependency(dep, {includedInParent: true});
        }
    }

    generate() {
        let map;
        if (this.ast && this.ast.map) {
            map = JSON.parse(this.ast.map.toString());
            map.sources = map.sources.map(v =>
                path.relative(this.options.rootDir, v)
            );
        }
        return [
            {
                type: "css",
                value: this.ast ? this.ast.css : "",
                hasDependencies: false,
                map
            }
        ];
    }
}

module.exports = LESSAssetNoUrlPlugin;
```

...which is just a copy of `LESSAsset` without the URL plugin.
