### ISSUE TITLE
How to create a build time variable?

### ISSUE THREAD

**Issue by nagyv** [parcel-bundler/parcel#3019]
# ❔ Question

I would like to generate a build time variable during parcel build. It's fine for me to put the build time into a separate file, like a json. Is this possible somehow?

## 🔦 Context

I have a React+Construct3 app, and Construct3 does everything in order to cache the files. To know what version I'm actually serving, I would like to see a variable that I can even print out, and speaks about the build time.

I read through the docs, but could not figure out where to start. I guess a simple env var would be the best, but this is a dynamic env var, thus reading it from a file is not a working option.

## 💻 Code Sample

not applicable

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.15
| npm/Yarn         | 6.4.1
| Operating System | Win 10

**Comment by mischnic** [comment]
On Linux/macOS, `BUILD_TIME=$(date) parcel build index.html` works (set the env var `BUILD_TIME` to the output of the date command (`Mon May 13 17:14:45 CEST 2019`).

I don't know how this is achieved exactly on Windows's CMD (not bash).
Some pointers:
Get time: https://stackoverflow.com/questions/203090/how-do-i-get-current-datetime-on-the-windows-command-line-in-a-suitable-format
Set output (not pretty): https://stackoverflow.com/questions/2768608/batch-equivalent-of-bash-backticks

**Comment by nagyv** [comment]
thanks

**Comment by kai-dorschner-twinsity** [comment]
The env stuff itself can be solved cross OS via an npm package called `crossenv`. About the date I don't know though.
