### ISSUE TITLE
CSS Link Not Shared on other html pages

### ISSUE THREAD

**Issue by sr-webcode** [parcel-bundler/parcel#3020]
# 🐛 bug report

I have two html pages:
index.html
about.html

both html files share the same script reference:
**<script src="./app.js">**

Inside app.js, i have one file import , which is the scss file
**"import "./style.scss";"**

However upon running:
"parcel *.html"

Only about.html has the stylesheet tag.

Am I missing something? Kindly guide me, I'm new to bundlers.

## 🎛 Configuration (.babelrc, package.json, cli command)
{
  "name": "Tutorial",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "init": "parcel *.html --no-source-maps --out-dir ./output"
  },
  "keywords": [],
  "author": "srwebcode",
  "license": "MIT",
  "devDependencies": {
    "sass": "^1.20.1"
  }
}

```js
{
  "your": { "config": "here" }
}
```

## 🤔 Expected Behavior

Both index.html and about.html should have 
<link rel="stylesheet" href="/style.css"></head>

## 😯 Current Behavior

Only about.html has the style tag:
<link rel="stylesheet" href="/style.css"></head>

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
Unfortunately this is a known bug in Parcel itself, tracked by #2340, and will be resolved in Parcel 2.

**Comment by sr-webcode** [comment]
Thanks mischnic!, glad to know.
 Are there any workarounds for this for the time being?

**Comment by mischnic** [comment]
- Creating a symlink called `style2.scss` and pointing that to `style.scss` *might* work.
- Process both html files seperately (if there are not `<a href>` between them): `parcel index.html` and then `parcel about.html`

**Comment by sr-webcode** [comment]
Alright!

Thanks once again!

**Comment by etsadhakal** [comment]
Is this bug solved ? seems not to me it doesnot worked for me
