### ISSUE TITLE
Globs do not honor project root

### ISSUE THREAD

**Issue by peacememories** [parcel-bundler/parcel#3021]
# 🐛 bug report

It seems that globs only work relative to the importing file. When using `/` or `~` as the start to a glob, the resulting argument to fast-glob is either just the glob argument (starting at your fs root) or the full path with a `~` in the middle (e.g. `/home/user/project/subdir/~/*.svg`), respectively.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "browsers": ["last 2 versions"]
        }
      }
    ]
  ],
  "plugins": [
    "transform-react-jsx",
    "transform-object-rest-spread",
    "transform-custom-element-classes"
  ]
}
```

Though I'm pretty sure that doesn't make a diference

## 🤔 Expected Behavior

A glob import like `~/assets/*.svg` in a js file `<myprojectpath>/js/app.js` should resolve correctly to glob `<myprojectpath>/assets/*.svg`

## 😯 Current Behavior

It instead globs `<myprojectpath>/js/~/assets/*.svg`

## 💁 Possible Solution

I think the path needs to be resolved like other imports before being handed to the glob utility function, possibly in the GlobAsset class.

## 🔦 Context

I'm trying to import all necessary svgs for our svg sprite. Unfortunately it's not currently feasible to import every svg separately where it is used, since our codebase ist an old Angular app with many string templates.

## 💻 Code Sample

```js
//webpack version
//require.context("~/images/won-icons", false, /\.svg$/);
import "/images/won-icons/*.svg";
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | v10.15.3
| npm/Yarn         | 6.9.0
| Operating System | Ubuntu 18.04

**Comment by mischnic** [comment]
Does Parcel throw an error during build?
