### ISSUE TITLE
'parcel' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by kjr247** [parcel-bundler/parcel#3023]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "__",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "dev": "parcel server.js",
    "build": "parcel build server.js"
  },
  "author": "Kyle Rebstock",
  "license": "__",
  "dependencies": {
    "@types/socket.io": "^2.1.2",
    "express": "^4.16.4",
    "socket.io": "^2.2.0"
  },
  "devDependencies": {
  }
}

// I have started with no config as parcel claims you don't need one.
```

## 🔦 Context

I can't build.

I was able to get it to build and run at one point, but as soon as I close my cmd or gitbash both to try restarting nothing works again.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm         |
| Windows |

**Comment by kjr247** [comment]
Solution was simply uninstalling both global and local versions.
Then install with this line exactly.
```
npm install parcel-bundler --save-dev
```

For some reason it is different than when I write
npm i parcel-bundler --save-dev?

**Comment by mischnic** [comment]
These commands (should) do the same thing. And the local version is always preferred over the global one (for the scripts in package.json and when using `npx`).

**Comment by ferran1** [comment]
Has anyone found a solution?

**Comment by ettore-galli** [comment]
> Solution was simply uninstalling both global and local versions.
> Then install with this line exactly.
> 
> ```
> npm install parcel-bundler --save-dev
> ```
> 
> For some reason it is different than when I write
> npm i parcel-bundler --save-dev?

Worked for me too, thank you for posting.

**Comment by vikrantkumar256** [comment]
why is it work ? i am not getting it.
please can anyone explain it to me .

**Comment by EzequielDeSimone-Reflektion** [comment]
I uninstall the global and dev version and then install just local version and setup the package.json.
the documentation here explain the right way everything:
https://parceljs.org/getting_started.html

**Comment by chisholmd** [comment]
In my package.json file I have this:
  "devDependencies": {
    "parcel-bundler": "^1.12.4"


When other team members run 
   npm install we can see that it is installing parcel

but then when they try to run 
   parcel build

We get 
  'parcel' is not recognized as an internal or external command

Any guesses about what is missing?

**Comment by mischnic** [comment]
you need to run parcel via an npm script or npx or yarn:
```
npx parcel ...
yarn parcel ...
```

**Comment by ella24** [comment]
How can I uninstall both global and local versions of parcel? I am having the same issue.

**Comment by Danities316** [comment]
> How can I uninstall both global and local versions of parcel? I am having the same issue.

npm uninstall parcel-builder

**Comment by Danities316** [comment]
> Solution was simply uninstalling both global and local versions.
> Then install with this line exactly.
> 
> ```
> npm install parcel-bundler --save-dev
> ```
> 
> For some reason it is different than when I write
> npm i parcel-bundler --save-dev?

This is also work for me.
Thanks

**Comment by victobonetti** [comment]
npm install parcel-bundler --save-dev

It workd for me! Tks man!

**Comment by SergeyShvetskov** [comment]
npm install parcel-bundler --save-dev

Working. Thank you!

**Comment by wyttenbach** [comment]
If you use 'npx parcel' in place of 'parcel' that might be a solution too
