### ISSUE TITLE
Hot Reloading fires browser refresh only after trying it in Chrome first

### ISSUE THREAD

**Issue by gregid** [parcel-bundler/parcel#3025]
# 🐛 bug report

Hot Reloading fires browser refresh only after trying it in Chrome first

## 🎛 Configuration (.babelrc, package.json, cli command)

Default configuration and content from: https://parceljs.org/getting_started.html

## 🤔 Expected Behavior

I run `parcel index.html` open any browser and the page refresh works on file changes.

## 😯 Current Behavior

I run `parcel index.html` open e.g. firefox or edge, I make change to a file, the server is being built but the page doesn't refresh automatically.

In order to "fix" this I need to run the `http://localhost:1234` first in Chrome. After it is opened in Chrome (at least once for every parcel session) suddenly every other browser (firefox, edge, etc.) works fine and refreshes the page automatically.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.15.3
| npm/Yarn         | 6.4.1
| Operating System | Windows 10

**Comment by kubasovp** [comment]
A similar problem, but reloading the page in Chrome does not help.
Node.js 12.4.0
Parcel 1.12.3
npm 6.9.0
Lubuntu 19.04
