### ISSUE TITLE
Parcel returns empty object when globbing includes within dropbox folder

### ISSUE THREAD

**Issue by oo7ph** [parcel-bundler/parcel#3026]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)
CLI: `parcel index.html`

## 🤔 Expected Behavior

This should return an object with image paths
```
import images from './*.png'
```

## 😯 Current Behavior

Returns an empty object
```
import images from './*.png'
```

## 💁 Possible Solution

🤷‍♀️ 

## 🔦 Context

This is on a new install directory located inside dropbox with an image in the folder with nothing but the following directory structure.
```
/
    test.png
    index.html
    index.js
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3|
| Node             | v10.6.0|
| Yarn         | 1.12.3|
| Operating System | Mac |

**Comment by BiswajitHemram** [comment]
In parcel **version 2.10.0** and above, the import of images can be done like 

`import landscape from "url:./images/landscape.jpg";
`

Alternatively, you can use the new URL()

`const landscape = new URL("./images/landscape.jpg", import.meta.url).href;
`


**Before version 2.10.0**, something like v2.8.3,

`import landscape from "./images/landscape.jpg";
`
