### ISSUE TITLE
Why parcel keeps deleted code in bundle on watch?

### ISSUE THREAD

**Issue by maykelknight** [parcel-bundler/parcel#3029]
# ❔ Question

I have a problem with watching .scss files. If i run command: parcel src/index.html,
and the watcher is running, even if I comment some styles in my .scss file, they are still rendered in the view after rebuilding. Even deleting the .scss files doesn't help. I need to delete dist folder and run command once again. Am I missing something? Thanks in advance for help.

**Comment by mischnic** [comment]
Sounds like a caching or watcher issue

**Comment by maykelknight** [comment]
Is there any option to disable caching?

**Comment by mischnic** [comment]
`--no-cache`, but if its related to the watcher then restart it the only option

**Comment by SpectralKH** [comment]
@mischnic Disabling cache does not fix it, so it seems to be a watcher issue. It does actually rebuild when you delete a file, but the output is not changed.
