### ISSUE TITLE
Can't install NPM package - @parcel/logger not found

### ISSUE THREAD

**Issue by inuwan** [parcel-bundler/parcel#3030]
Attempting to NPM install parcel-bundler and unsuccessful with the following error:

npm install parcel-bundler --D
npm ERR! code E404
npm ERR! 404 Not Found: @parcel/logger@^1.11.0

**Comment by mischnic** [comment]
Strange, that packages does exist: https://www.npmjs.com/package/@parcel/logger

**Comment by Mordil** [comment]
I'm running into this as well.

Last night, on a different machine, I was able to install just fine. This morning I cannot.

Working machine:
```
OS: Windows10
Node: 8.6
NPM: 6.9
```

Not working:
```
OS: macOS 10.14.6 Beta 1
Node: 10.15
NPM: 6.9
```

Error message:
```
~$ npm i -g parcel-bundler
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@parcel%2flogger - User not found
npm ERR! 404 
npm ERR! 404  '@parcel/logger@^1.11.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'parcel-bundler'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nathanh/.npm/_logs/2019-05-17T16_17_25_135Z-debug.log
```
Log:
[2019-05-17T16_17_25_135Z-debug.log](https://github.com/parcel-bundler/parcel/files/3192272/2019-05-17T16_17_25_135Z-debug.log)

**Comment by mischnic** [comment]
Does it work with yarn?

**Comment by inuwan** [comment]
Strange it works in some projects but not others.  Maybe is how my machine is configured.

**Comment by mischnic** [comment]
> Maybe is how my machine is configured.

Closing as this is some issue with your configuration
