### ISSUE TITLE
Cannot resolve dependency 'vscode'

### ISSUE THREAD

**Issue by JonathanTroyer** [parcel-bundler/parcel#3034]
# 🐛 bug report

Parcel fails on `import * as code from 'vscode';`. It also fails if I import directly, i.e. `import { ExtensionContext } from 'vscode';`

### Package.json
```js
{
    "name": "Converter",
    "publisher": "me",
    "displayName": "ASP Convert",
    "description": "Assists with converting ASP pages to HTML5 standards",
    "license": "MIT",
    "version": "1.0.1",
    "engines": {
        "vscode": "^1.33.0"
    },
    "categories": [
        "Other"
    ],
    "activationEvents": [
        "onCommand:extension.aspconvert",
        "onLanguage:asp"
    ],
    "main": "./dist/extension.js",
    "contributes": {
        "commands": [
            {
                "command": "extension.abconvert",
                "title": "ASP Convert"
            }
        ]
    },
    "scripts": {
        "vscode:prepublish": "yarn run compile",
        "compile": "parcel build ./src/extension.ts --log-level 4",
        "watch": "parcel ./src/extension.ts",
        "postinstall": "node ./node_modules/vscode/bin/install",
        "test": "yarn run compile && node ./node_modules/vscode/bin/test",
        "package": "npx vsce package"
    },
    "devDependencies": {
        "@types/mocha": "^2.2.42",
        "@types/node": "^10.12.21",
        "@types/vnu-jar": "^17.11.0",
        "parcel-bundler": "^1.12.3",
        "tslint": "^5.12.1",
        "typescript": "^3.4.5",
        "vscode": "^1.1.28"
    },
    "dependencies": {
        "vnu-jar": "^18.11.5"
    }
}
```

### tsconfig.json
```js
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "outDir": "out",
        "lib": [
            "es6",
            "esnext.array"
        ],
        "sourceMap": true,
        "rootDir": "src",
        "strict": true   /* enable all strict type-checking options */
        /* Additional Checks */
        // "noImplicitReturns": true, /* Report error when not all code paths in function return a value. */
        // "noFallthroughCasesInSwitch": true, /* Report errors for fallthrough cases in switch statement. */
        // "noUnusedParameters": true,  /* Report errors on unused parameters. */
    },
    "exclude": [
        "node_modules",
        ".vscode-test"
    ]
}
```

## 🤔 Expected Behavior

Parcel should bundle the VSCode extension

## 😯 Current Behavior

```
[4:57:22 PM]: Building...
[4:57:22 PM]: Building extension.ts...
[4:57:23 PM]: Building rules.ts...
[4:57:23 PM]: 🚨  /Users/jonathantroyer/Desktop/asp-converter/src/extension.ts:7:25: Cannot resolve dependency 'vscode'
[4:57:23 PM]:     at Resolver.resolve (/Users/jonathantroyer/Desktop/asp-converter/node_modules/parcel-bundler/src/Resolver.js:71:17)
    at async Bundler.resolveAsset (/Users/jonathantroyer/Desktop/asp-converter/node_modules/parcel-bundler/src/Bundler.js:433:18)
    at async Bundler.resolveDep (/Users/jonathantroyer/Desktop/asp-converter/node_modules/parcel-bundler/src/Bundler.js:484:14)
    at async /Users/jonathantroyer/Desktop/asp-converter/node_modules/parcel-bundler/src/Bundler.js:608:26
    at async Promise.all (index 3)
    at async Bundler.loadAsset (/Users/jonathantroyer/Desktop/asp-converter/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async Bundler.processAsset (/Users/jonathantroyer/Desktop/asp-converter/node_modules/parcel-bundler/src/Bundler.js:557:5)
    at async PromiseQueue._runJob (/Users/jonathantroyer/Desktop/asp-converter/node_modules/parcel-bundler/src/utils/PromiseQueue.js:48:7)
```

## 💁 Possible Solution

Unsure

## 🔦 Context

I'm currently trying to bundle a VSCode extension.

## 💻 Code Sample

```ts
import { ExtensionContext, commands, window, workspace } from "vscode";

export function activate(context: ExtensionContext) {
    context.subscriptions.push(
        commands.registerCommand('extension.aspconvert', _ => {
            let currentEditor = window.activeTextEditor;
            if (currentEditor !== undefined) {
                window.showInformationMessage('Hello World!!');
            } else {
                window.showInformationMessage('No file active');
            }
        })
    );
}

export function deactivate() { }
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |     1.12.3
| Node             |     12.1.0
| npm/Yarn         |     1.16.0
| Operating System | macOS Mojave 10.14.4 (18E226)

**Comment by mischnic** [comment]
VSCode specifies no `main` field so the resolution of `import "vscode"` falls back to `node_modules/vscode/index.js`, which doesn't exist either.

Running `require("vscode");` in plain node also throws: "Error: Cannot find module 'vscode'"

I'm guessing VSCode somehow injects the real module during runtime?
If that's the case, you should run `parcel build index.ts -t node` which leaves the `require("vscode")` import and doesn't try to resolve it

**Comment by JonathanTroyer** [comment]
Changing the target to node worked! Thanks a ton, I'll mark this as closed. Hopefully people bundling VSCode extensions in the future can run across this.

One note, [the flag is `--target`](https://parceljs.org/cli.html#target) (not just `-t`).

**Comment by mischnic** [comment]
Great!

`-t` should work as well though, seems to be missing in the documentation.
https://github.com/parcel-bundler/parcel/blob/4b50182129b19395b791cf1e4194069ae8736ef4/packages/core/parcel-bundler/src/cli.js#L54-L58

**Comment by Abyrd9** [comment]
I am having a similar problem. Changing the target to node leads to a successful build since it's no longer bundling dependencies, but I have other dependencies besides vscode that I _do_ need bundled. Still trying to figure out a solution if anyone runs across something.

**Comment by ctf0** [comment]
have the same issue as @Abyrd9 , any solution for that ?

**Comment by vudzero** [comment]
Having same issue as @Abyrd9 , trying to migrate to Parcel2 to see if it can fix the issue...

**Comment by jonas-k** [comment]
Could this issue be reopened since excluding all node modules is not really a fix? I also ran into this problem and couldn't circumvent it by using includeNodeModules: { "vscode": false }.

**Comment by sketchbuch** [comment]
so what do you do if you are bundling a vscode extension (target=node) but need dependencies (except vscode) in the bundle

**Comment by mischnic** [comment]
With Parcel 2, you can do something like this in package.json to bundle everything except `vscode`:

```
{
  "targets": {
    "default": {
      "includeNodeModules": { "vscode": false }
    }
  }
  "engines": {
    "node": ">= 12",
  }
}
```

https://v2.parceljs.org/configuration/package-json/#includenodemodules

**Comment by sketchbuch** [comment]
Hi @mischnic 
I tried to use your config but it is not working.

https://github.com/sketchbuch/vsc-packages/tree/feature/parcel2

If I run the build command, it builds but doesn't include the dependencies. Is my package.json correct?

**Comment by sketchbuch** [comment]
Ignore my last comment, I had parcel 1 still in my package.json and that was being used it seems
