### ISSUE TITLE
How to add to Parcel production build mode?

### ISSUE THREAD

**Issue by bubnenkoff** [parcel-bundler/parcel#3040]
My follow config generate debug build. I want to add release mode to it. How I can do it?

```
  "scripts": {
    "prebuild": "rmdir /s/q dist",
    "build": "parcel build src/index.html --no-source-maps",
    "start": "parcel src/index.html",
    "watch": "parcel watch src/index.html"
  },
```

The problem that I am getting very big  bundle (6MB) on very small project.
```
"parcel-bundler": "^1.12.3",
```

OS Windows 10

**Comment by mischnic** [comment]
`parcel build src/index.html --no-source-maps` is already "production mode".

**Comment by bubnenkoff** [comment]
@mischnic but on very tiny project like https://github.com/bubnenkoff/parcel-vue-template
I am getting incredible big bundle (around 6MB). How I can reduce it size??

**Comment by mischnic** [comment]
6MB?

I'm getting this:
```
parcel build src/index.html --no-source-maps:

dist/src.958f84bf.js                750.04 KB    65.89s
dist/src.f82eeadd.css               191.39 KB    65.32s
dist/element-icons.f5240f4e.ttf      54.64 KB     2.36s
dist/element-icons.67bee1e1.woff     27.54 KB     2.65s
dist/index.html                         238 B     1.15s
```

**Comment by bubnenkoff** [comment]
@mischnic why we can have so different results? 
By 100% correct I am getting 6MB on this template (90% same from template above https://github.com/bubnenkoff/dlang.ru/tree/master/web ) 

Here is my result:
![изображение](https://user-images.githubusercontent.com/6514326/57907552-77a89b00-7886-11e9-88dc-a5e93e4d82d5.png)

**Comment by bubnenkoff** [comment]
I tried `parcel build`  command and got next error:
![изображение](https://user-images.githubusercontent.com/6514326/57908584-0c13fd00-7889-11e9-926c-136ffaa1b747.png)

cleaning node_modules and removing package-lock.json did not help

**Comment by katsar0v** [comment]
```
parcel build src/index.html --no-content-hash --no-source-maps
```
Cannot be production!
I get:
```
dist/src.f69400ca.js     422.96 KB    10.36s
dist/src.f69400ca.css    151.25 KB     6.60s
dist/index.html              393 B       7ms
```

How can `src.f69400ca.css` be used in production? There is something wrong and the hashes need to be removed even if it means to overwrite the files.

**Comment by mkg20001** [comment]
I think the build command needs to be changed to `rm -rf dist && parcel build src/index.html --no-source-maps` so it removes the dist/ folder, as parcel usually leaves development assets after the development server has been stopped and they are stored in _the same_ folder

**Comment by mkg20001** [comment]
Or rather the prebuild command needs to be triggered. That would be `npm run prebuild && parcel build src/index.html --no-source-maps`

**Comment by katsar0v** [comment]
I think parcel should rethink about this internally and optimize this

**Comment by mkg20001** [comment]
One idea would be to store dev assets in `.parcel-cache` and delete the old on every re-build
Another idea would be to delete the output folder before production build (or add a flag at least, since it's really common thing to do that)

**Comment by mischnic** [comment]
This has nothing do do anymore with the original issue. 

@bubnenkoff We can help you better if you provide a reproduction.

---

@katsar0v 
> How can src.f69400ca.css be used in production? There is something wrong and the hashes need to be removed even if it means to overwrite the files.

The hashes are not added to prevent overwriting but to do cache busting.

@mkg20001 
> Another idea would be to delete the output folder before production build (or add a flag at least, since it's really common thing to do that)

I agree.

**Comment by mkg20001** [comment]
@mischnic Tracking this under https://github.com/parcel-bundler/parcel/issues/3591
