### ISSUE TITLE
Error: internal/modules/cjs/loader.js:613

### ISSUE THREAD

**Issue by bubnenkoff** [parcel-bundler/parcel#3050]
The topic root is located here https://github.com/parcel-bundler/parcel/issues/3040

When I tried to run command `parcel build` I got error:
```
internal/modules/cjs/loader.js:613
    throw err;
    ^
Error: Cannot find module 'v8-compile-cache'
```

![изображение](https://user-images.githubusercontent.com/6514326/57909197-c35d4380-788a-11e9-91d2-c62127d97b89.png)

I tried to remove node_modules and package-lock.json. But it did not helped.
`"parcel-bundler": "^1.12.3",`

NodeJS 12

**Comment by fauzan121002** [comment]
same

**Comment by mischnic** [comment]
@bubnenkoff Does the folder "C:\bubnenkov\AppData\Roaming\npm\node_modules\v8-compile-cache" exist?

You could try running installing it again: `npm i -g parcel-bundler`

**Comment by bubnenkoff** [comment]
No this folder do not exists.
I run `npm i -g parcel-bundler`
And after it run command:
```
$ parcel build
×  No entries found.
    at Bundler.bundle (C:\Users\bubnenkov\AppData\Roaming\npm\node_modules\parcel-bundler\src\Bundle                      r.js:275:17)
```

**Comment by mischnic** [comment]
You should pass your input file to `parcel build`. In your screenshot from above, this caused the v8-compile-cache error. Are you sure it still isn't working?

**Comment by bubnenkoff** [comment]
Thanks ` parcel build src/index.html` that's working!
