### ISSUE TITLE
Is there a way to always add hash to js entry file?

### ISSUE THREAD

**Issue by ajzozakiewicz** [parcel-bundler/parcel#3051]
# ❔ Question

Is there a way to always add hash to js entry file? Is there a way to cache bust without the hash using parcel?

## 🔦 Context

I have a need to serve some dynamic html from my express server in order to bootstrap some initial data and apply things like CSRF. When generating from a js entry file parcel does not append a hash to the file. This seems like it would be an issue for cache busting previous bundles.

## 🌍 Your Environment

Express.js - 4.16.4
React - 16.8.6

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.3 |
| Node             | v10.15.3 |
| npm/Yarn         | 6.4.1 |
| Operating System | Mojave 10.14.4 |
| Operating System | alpine:3.9 |

**Comment by mischnic** [comment]
Currently not, entrypoints don't get a hash because having a `index.ad92de.html` wouldn't work. Your entrypoint has to have a "constant" filename.

**Comment by ajzozakiewicz** [comment]
I was actually able to achieve this fairly easily. Paired with react-hot-loader, hmr is working great as well.

The one thing I am wondering is if there is an easier way to get to the css asset within the bundle when assembling my asset manifest. This seems reliable but also seems like there should be an easier way.

```
const Bundler = require('parcel-bundler')
const Path = require('path')
const shortId = require('shortid')
const rimraf = require('rimraf')
const fs = require('fs')
const _find = require('lodash/find')
const { basePath, assetPath } = require('config')
const isDev = require('./../src/server/utils/is-dev')

// Single entrypoint file location:
const entryFiles = Path.join(__dirname, './../src/app/index.js')
const outputLocation = Path.join(__dirname, './../build/public')
const hash = shortId.generate()

// Bundler options
const options = {
  outDir: outputLocation, // The out directory to put the build files in, defaults to dist
  outFile: `index.${hash}.js`, // The name of the outputFile
  publicUrl: `./`,
  watch: isDev,
  hmr: isDev,
  minify: !isDev,
  cache: isDev
}

const cleanBuild = async () => {
  rimraf(Path.join(__dirname, './../build/public/'), err => {
    if (err) {
      throw new Error('rimraf failed')
    }
  })
}

(async function () {
  console.log('Building bundle for environment: ', process.env.NODE_ENV, process.env.NODE_APP_INSTANCE)

  await cleanBuild()

  // Initializes a bundler using the entrypoint location and options provided
  const bundler = new Bundler(entryFiles, options)

  // Run the bundler, this returns the main bundle
  // Use the events if you're using watch mode as this promise will only trigger once and not for every rebuild
  const bundle = await bundler.bundle()

  const cssPath = _find(Array.from(bundle.siblingBundles), entry => entry.type === 'css') || ''
  const manifest = {
    js: `${basePath}${assetPath}/${Path.basename(bundle.name)}`,
    css: `${basePath}${assetPath}/${Path.basename(cssPath.name)}`
  }

  fs.writeFileSync(`${outputLocation}/assets.json`, JSON.stringify(manifest))
})()

```

**Comment by ajzozakiewicz** [comment]
This follows a similar approach to webpack, on the server you read in the asset manifest and then add a script tag to your html output with the respective paths.

**Comment by mischnic** [comment]
> The one thing I am wondering is if there is an easier way to get to the css asset within the bundle when assembling my asset manifest. This seems reliable but also seems like there should be an easier way.

Maybe with this plugin? https://github.com/mugi-uno/parcel-plugin-bundle-manifest
