### ISSUE TITLE
Error when referencing images in javascript in parcel.

### ISSUE THREAD

**Issue by AnimatorJoe** [parcel-bundler/parcel#3056]
# ❔ Question

Why don't images files referenced in javascript show up when using parcel?

## 🔦 Context

I am writing a shooter game that involves generating a plane sprite and the javascript to it is shown below

```
    var plane = new Image()
    plane.src = "static/assets/jplane.png"
    ctx.drawImage(plane, 0, 0, 98, 98, 300, 300, planeScale*98, planeScale*98)  
```

I referenced the javascript file in my index.html

```
    <script src="./index.js"></script>
```

The problem is, the image displays when I open the index.html file through my browser, but it failed when I run parcel index.html

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.3
| Node             |v10.6.0
| npm/Yarn         |1.16.0
| Operating System |Mac OS

**Comment by mischnic** [comment]
Do something like this (you need to tell parcel to include that asset in the build output):
```js
plane.src = require("./static/assets/jplane.png"); // returns a url to the img, e.g. '/jplane.0735d1ef.png'
```

**Comment by AnimatorJoe** [comment]
Since the image was in "../static/assets" dirctory, I had to change the path you gave me to "../static/assets/jplane.png". After that, it worked. Thanks a lot!

**Comment by jimfilippou** [comment]
```javascript
const myImage = "../assets/images/team/" + speaker.image;
const RAW = "../assets/images/team/fil-200x200.jpg";

// Works!
image.src = require("../assets/images/team/fil-200x200.jpg");

// Doesn't work
image.src = require(RAW);

// Doesn't work
image.src = require(myImage);
```

I want to use those who doesn't work. Why is that happening?

**Comment by mischnic** [comment]
During bundling, Parcel has to determine that parameter of the require without executing the code.

Therefore, `image.src = require(myImage)` doesn't work, because the value of `myImage` isn't known and even if that variable was looked up, `speaker.image` isn't known at bundle time.

**Comment by jimfilippou** [comment]
> During bundling, Parcel has to determine that parameter of the require without executing the code.
> 
> Therefore, `image.src = require(myImage)` doesn't work, because the value of `myImage` isn't known and even if that variable was looked up, `speaker.image` isn't known at bundle time.

### You are right! 
However, can you think of a way to work around this? 🤔

**Comment by mischnic** [comment]
Maybe something like https://en.parceljs.org/module_resolution.html#glob-file-paths?

**Comment by jimfilippou** [comment]
> Maybe something like https://en.parceljs.org/module_resolution.html#glob-file-paths?

# You are the best!

**Comment by ponyBoy-dev** [comment]
> Maybe something like https://en.parceljs.org/module_resolution.html#glob-file-paths?
Hello, 

I need to use something like that but I don't fully understand how it works so my attempts fail...

In short, I need to change the src of my image depending on the result of a function that returns the name of the image. 
When I use 
`import image from "/assets/note-8.png"`
`document.querySelector("#demo").src = image`
it works. But it's useless to my goal.
I programmatically determine which image to use, so I would like to 
`import images from "/assets/*.png"` and then access a precise image with something like
`image["myFunction()"]`
But that doesn't work. Even `image["note-8"]` doesn't work.
How can I access a precise image?

**Comment by jamonholmgren** [comment]
If you just need to reference some static files in your JavaScript, you can also use this Parcel plugin to copy them over to a static location:

https://github.com/elwin013/parcel-plugin-static-files-copy

**Comment by Clingonboy** [comment]
> Maybe something like https://en.parceljs.org/module_resolution.html#glob-file-paths?

you save my life !!! thanks

**Comment by LuisHerasme** [comment]
> Do something like this (you need to tell parcel to include that asset in the build output):
> 
> ```js
> plane.src = require("./static/assets/jplane.png"); // returns a url to the img, e.g. '/jplane.0735d1ef.png'
> ```

This does not work for me, it is necessary to use a folder called static?

**Comment by AnnemiekNieboer** [comment]
> Do something like this (you need to tell parcel to include that asset in the build output):
> 
> ```js
> plane.src = require("./static/assets/jplane.png"); // returns a url to the img, e.g. '/jplane.0735d1ef.png'
> ```

Thank you for this!

**Comment by hashimaziz1** [comment]
> Do something like this (you need to tell parcel to include that asset in the build output):
> 
> ```js
> plane.src = require("./static/assets/jplane.png"); // returns a url to the img, e.g. '/jplane.0735d1ef.png'
> ```

This gives me the error "Browser scripts cannot have imports or exports". Is there any way to actually tell Parcel an image exists without using modules (i.e. a classic script)?

**Comment by AnnemiekNieboer** [comment]
> > Do something like this (you need to tell parcel to include that asset in the build output):
> > ```js
> > plane.src = require("./static/assets/jplane.png"); // returns a url to the img, e.g. '/jplane.0735d1ef.png'
> > ```
> 
> This gives me the error "Browser scripts cannot have imports or exports". Is there any way to actually tell Parcel an image exists without using modules (i.e. a classic script)?

Not sure of it solves it, but do you have type=“module” in your script tag?

**Comment by gcp** [comment]
>Not sure of it solves it, but do you have type=“module” in your script tag?

The sentence you're replying is asking for a way to do it without modules...

**Comment by gcp** [comment]
There's a bunch of parcel plugins to handle copying static assets (which isn't the same as being able to pull them through the optimization pipeline, but may solve some of the same uses cases where you don't want to use modules).

However, although there were decent ones for v1 (see https://github.com/parcel-bundler/parcel/issues/3056#issuecomment-678915568), there's like 5 different ones for v2 that are all super limited and don't even support watching.

The best solution seems to be something like
```
"scripts": {
    "start": "parcel",
    "build": "parcel build index.html assets/** static/**"
  },
```

If there's any better options (esp being able to optimize images), I'm all ears.

**Comment by GosiaAntoniak** [comment]
I add tag in HTML <img> with path to the picture and .class and the next I write function JS and add that for example <div> who has a class the same that <img>
this way if you are working on a lot the system reads the file into "dist" and works

**Comment by kixelated** [comment]
An alternative that seems to work:

```javascript
image.src = new URL("./static/assets/jplane.png", import.meta.url) // .toString() required?
```

It has the advantage of being valid javascript so you don't have to ignore any editor errors caused by trying to import an image file.

**Comment by sumitsah** [comment]
plane.src = require("./static/assets/jplane.png"); // returns a url to the img, e.g. '/jplane.0735d1ef.png'

Above is working but you use above code inside a function, that will again break and say can't find module.
I found more robust solution which is importing an image or svg at the beginning and use it anywhere inside the module/file.
following is an example:-

import jplaneImg from './static/assets/jplane.png';
