### ISSUE TITLE
Image not found when I do npm run start

### ISSUE THREAD

**Issue by SoyDiego** [parcel-bundler/parcel#3058]
# ❔ Question

Hi, i'm new in Parcel and my problem is when I did `npm run start` the images path of my website are not found. But when I check my site locally all works fine. What am I doing wrong?
Thanks

## 🔦 Context
![SOJPjZ8](https://user-images.githubusercontent.com/19764334/58008523-dc652f00-7aec-11e9-820d-24e71291eb5c.png)

**Comment by mischnic** [comment]
Are you displaying/adding them via Javascript? Please post a snippet of that code.

**Comment by SoyDiego** [comment]
> 
> 
> Are you displaying/adding them via Javascript? Please post a snippet of that code.

Yes, vía Javascript.
`}else if (user === undefined) {
        //show message + image
        infoUser = `${userName} <strong>doesn't exist.</strong>.
                    <div>
                      <img src="img/emoji.png" width="100px" height="100px">
                    </div>`
        divInfoUser.innerHTML = infoUser;

        divInfoUser.style.display = 'block';
        table.style.display = 'none';
      }`

**Comment by mischnic** [comment]
This should work (you might need to adjust the path in require to be a correct relative path *the the JS script file*.)

```js
        //show message + image
        infoUser = `${userName} <strong>doesn't exist.</strong>.
                    <div>
                      <img src="${require('./img/emoji.png')}" width="100px" height="100px">
                    </div>`
        divInfoUser.innerHTML = infoUser;

        divInfoUser.style.display = 'block';
        table.style.display = 'none';
      }
```

**Comment by SoyDiego** [comment]
> 
> 
> This should work (you might need to adjust the path in require to be a correct relative path _the the JS script file_.)
> 
> ```js
>         //show message + image
>         infoUser = `${userName} <strong>doesn't exist.</strong>.
>                     <div>
>                       <img src="${require('./img/emoji.png')}" width="100px" height="100px">
>                     </div>`
>         divInfoUser.innerHTML = infoUser;
> 
>         divInfoUser.style.display = 'block';
>         table.style.display = 'none';
>       }
> ```

Excelent!! now is perfect. Thanks bro!
