### ISSUE TITLE
RFC: --no-content-hash for watch mode?

### ISSUE THREAD

**Issue by nagyv** [parcel-bundler/parcel#3060]
# 🙋 feature request

`--no-content-hash` works fine for builds, but it would be great to have it for watch mode too.

In theory, this is achievable using a custom node script that runs parcel with its API, but it would be much more fun to use it as a CLI option.

I've seen a similar request before the addition of the cli option here #2050.

## 🤔 Expected Behavior

`parcel watch --no-content-hash` should work

## 😯 Current Behavior

`error: unknown option `--no-content-hash'`

## 💁 Possible Solution

Add the option to watch mode.

## 🔦 Context

I run parcel inside a rather complex dev environment where other tools require the react app built with parcel. In dev mode these tools need a hard-coded set of files, thus content hashing is a real nightmare.

I would be happy to create the changes and PR if there is not strict opposition to this idea. :)

**Comment by devongovett** [comment]
Content hashing is already disabled by default in watch mode. The hashes are based on the filename, not the content, and are necessary to handle duplicate files from different directories that get flattened into dist. This is exactly what the no content hash option in build mode does as well.
