### ISSUE TITLE
HMR port quits working

### ISSUE THREAD

**Issue by YogoGit** [parcel-bundler/parcel#3066]
# 🐛 bug report

hmr port quits listening once the application is fully configured when running inside a docker container.

Note, I'm running WITHIN the docker container for all commands, so external port mapping is not the issue.

## 🎛 Configuration (.babelrc, package.json, cli command)
Command line:
``` 
% parcel serve index.html --port 80 --hmr-port 1235 --no-autoinstall
Server running at http://localhost:80 
✨  Built in 12.97s.
```

## 🤔 Expected Behavior

The websocket should be listening and publishing hot reload requests.

## 😯 Current Behavior

The HMR websocket is not accepting requests.

Testing setup:
I'm running curl inside a shell exec'd into the container to verify port connectivity.

```docker exec -it container sh```

Using Curl, which fails but is good enough to verify connectivity.
```
curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: echo.websocket.org" -H "Origin: https://www.websocket.org" http://localhost:1235
```

For the first ~13 seconds, I get the following result running the above command.
```
HTTP/1.1 400 Bad Request
```

But, once the application is fully 'up' (noted by output `Built in 12.97s.`), it refuses connections.
```
curl: (7) Failed to connect to localhost port 1235: Connection refused
```

## 🔦 Context

I'm trying to get hot-reload working inside a docker container, which is not working.

Note, if I run the exact same commands natively on MacOS, it's working fine.  I'm not sure why the docker container environment is behaving differently.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | v8.15.0
| npm/Yarn         | 6.4.1
| Operating System | Docker/alpine container

Node is installed via the command:
```
 npm install -g parcel-bundler
```

**Comment by YogoGit** [comment]
Here is a git repo with a very simple project that has been dockerized that demonstrates the issue:

https://github.com/YogoGit/parcel-test

Steps:
1) Clone the repo
```
git clone git@github.com:YogoGit/parcel-test.git
```
2) Build the docker containre
```
cd parcel-test
docker build -t parcel-test:test -f docker/Dockerfile .
```
3) Run the container
```
docker run --rm --name parcel-test -p 8080:80 -p 1235:1235 parcel-test
```

4) In a browser, view the content, and note that the websocket connection to port 1235 fails:
```
WebSocket connection to 'ws://localhost:1235/' failed: Connection closed before receiving a handshake response
```

Checkout the configuration that uses `--hmr-port 1235`.  If you want more detailed, you can try to race the start by running the parcel command inside the docker container.

Alternate:
3) Manually run the docker container
```
docker run --rm --name parcel-test -p 8080:80 -p 1235:1235 parcel-test sh
```
3a) Exec into the container in a different window
```
docker exec -it parcel-test sh
curl -i -N -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Host: echo.websocket.org" -H "Origin: https://www.websocket.org" http://localhost:1235
```
This should completely fail, as parcel is not (yet) running.

4) Start parcel up in the container by running the start.sh script in the first windo
```
/start.sh
```
4a) At the exact same time, run the curl command from step (3a) again in the second window.  If you get the timing right, parcel will respond with a Bad Request instead of an error, indicating the socket is active and listening for a short period of time.

**Comment by dionjwa** [comment]
Annoying. This bug is still present. Development is moving to all docker containers bc of many reasons. Please re-open.

Thank you for your awesome work. Parcel really helps with it's simplicity.
