### ISSUE TITLE
Parcel 2: Separate CSS Modules Transformer from PostCSS

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#3067]
As of #3037, CSS modules matching `*.module.css` are supported by default in the PostCSS transformer. After discussing this further with @wbinnssmith, we think that this should be separated into its own Parcel transformer, leaving the PostCSS transformer to only handle PostCSS transforms specified by the user's `.postcssrc` config.

By separating CSS modules out, we can also use the `.parcelrc` config to handle the CSS module globbing as well. Using the `...` syntax in the config, we can specify that it should go to the CSS pipeline in addition:

```json
{
  "*.module.css": ["@parcel/transformer-css-modules", "..."],
  "*.css": ["@parcel/transformer-css", "@parcel/transformer-postcss"]
}
```

In addition, we should consider looking at how webpack's [css-loader](https://github.com/webpack-contrib/css-loader) handles CSS modules. They use a bunch of separate postcss plugins rather than the dead-looking postcss-modules repo.

**Comment by mischnic** [comment]
> leaving the PostCSS transformer to only handle PostCSS transforms specified by the user's .postcssrc config.

Where would the module config options go? Currently into .postcssrc:
```json
{
  "modules": true,
  "plugins": {
    "postcss-modules": {
      "generateScopedName": "[hash:base64:5]"
    }
  }
}
```

**Comment by devongovett** [comment]
Good question. Maybe `.cssmodulesrc`? 😬

**Comment by mischnic** [comment]
`something.module.scss` should also be possible
