### ISSUE TITLE
Importing empty stylus file fails

### ISSUE THREAD

**Issue by jkirkwood** [parcel-bundler/parcel#3073]
Hello. I am trying to import a stylus file from a JSX file like this:

```js
import React from "react"
import "./Modal.styl"
...
```

This generally works except when the stylus file is empty. When it is I get the following error:

`Cannot read property 'render' of nul`  (note the null with one 'l')

If I add anything to the stylus file, even a comment, or blank line, everything works as expected.

Here is our `.babelrc`:

```json
{
	"presets": [
		"env", "react"
	],
	"plugins": [
		["transform-class-properties", {"spec": true}]
	]
}
```

I'm running parcel v1.12.3 on Node v10.15.3

**Comment by mischnic** [comment]
This is quite likely where the error comes from: `this.ast` is null:
https://github.com/parcel-bundler/parcel/blob/fd7e36ec3c4910adb05ec6e0108a13305d50e215/packages/core/parcel-bundler/src/assets/StylusAsset.js#L40
