### ISSUE TITLE
Eval code wrapping 

### ISSUE THREAD

**Issue by astoilkov** [parcel-bundler/parcel#3081]
# ❔ Question

Is there a specific reason why Webpack wraps all exported modules in an `eval()` statement and Parcel doesn't?

My understanding is that when the code is wrapped in an `eval()` the browser doesn't need to parse the code until it is required for the first time which results in faster initial load times.

## 🔦 Context

We are building a big Electron application and want to use Parcel. I like Parcel way more than Webpack. The above question is my only concern which can affect the initial load time of the application because we have a lot of code we load on demand using Node.js `require()` (not `import()`).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.11.0
| npm/Yarn         | 6.4.1
| Operating System | macOS 10.14.5 (18F132)

**Comment by astoilkov** [comment]
Ok. I think I can close this. Webpack actually doesn't wrap the code around `eval()` in production which means you actually don't get the performance benefits.

Does anybody know how to implement code splitting for dynamic `require()` statements instead of `import()` statements or is it impossible?

**Comment by mischnic** [comment]
> Does anybody know how to implement code splitting for dynamic require() statements instead of import() statements or is it impossible?

Could you give an example of what you're trying to achieve? `import()` kind of is a dynamic `require()`.

**Comment by astoilkov** [comment]
@mischnic We have a big Electron application which for now have run without bundlers and just used the Node.js `require()`. The difference between a dynamic `require()` and `import()` is that `import()` is async. Our code architecture relies on the sync nature of the `require()` statement (things will stop working if we just transform them to `import()`). It will be a major task for us to go and support asynchronicity in all the places.

The easiest solution seems code splitting the code but retaining the `require()` statements.

**Comment by astoilkov** [comment]
I can add to the comment above that in a web app there is a huge logic to do async `import()` statements - you never know how much time it will take to retrieve from the server. However, in an Electron context, there is a guarantee that it will take in the matter of milliseconds.

Having this information and combining it will the idea that working sync code is much easier to implement and architecture it seems to be that when `--target=electron` there could be a special case for the dynamic `require()` statements which can be code split. What do you think?

**Comment by mischnic** [comment]
I see. Parcel is mainly focused on the web, and there is no synchronous codesplitting there.
What you really want is to bundle specific require calls into a separate bundle. Feel free to open a feature request.

**Comment by astoilkov** [comment]
Thanks. I think I can make a comment on this [issue here](https://github.com/parcel-bundler/parcel/issues/2492) which can also include the support for native node modules.

Thanks again for the information. Parcel is awesome!
