### ISSUE TITLE
Why is parcel bundling with urls as / instead of ./ ?

### ISSUE THREAD

**Issue by vickylance** [parcel-bundler/parcel#3090]
# ❔ Question

I want the parcel bundle to build and point in index.html as `./scripts or css` instead of `/scripts or css`

## 🔦 Context

 Because my electron app is failing to load the scripts as it uses file: protocol if I change to ./ manually in the dist folder everything works fine.

## 💻 Code Sample

I tried the below config but it is still pointing as / instead of ./
`parcel build ./src/index.html --public-url './'`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.13.0
| npm/Yarn         | npm
| Operating System |Windows 10 pro

**Comment by Cerlancism** [comment]
Remove the quote `'` from the CLI
`parcel build ./src/index.html --public-url ./`

**Comment by vickylance** [comment]
@Cerlancism It still does not work if I remove the quote

**Comment by vickylance** [comment]
Ah damn I just checked I added that public flag in build script than dev script. Sorry.. closing the issue.

@Cerlancism But still it builds as without any slashes. not ./ or / just the name of the file. Is building as ./name of the file not possible at all?

**Comment by Kwon11** [comment]
nice
