### ISSUE TITLE
can I ignore some js script required in the html?

### ISSUE THREAD

**Issue by cocodrino** [parcel-bundler/parcel#3091]
# ❔ Question

Hi guys, I need work with the trading view library but they just provide this as a script, no like a npm module, I put this in my html

<script src="./assets/trading_view/charting_library/charting_library.min.js"></script>

but I get this error

```
Error: Cannot find module '../../../../../../../../usr/local/share/.config/yarn/global/node_modules/parcel-bundler/src/builtins/css-loader.js' charting_library.min.d2f40bef.js:37:19

```

I know that webpack has this feature

https://webpack.js.org/configuration/externals/

but I can't find documentation in parceljs about this...

thank you so much guys!

**Comment by mischnic** [comment]
No, this isn't currently possible

**Comment by cocodrino** [comment]
ok any plan for solve this in the future?...currently I think that I can move the script to some folder in my server and require this for the full url path, so I think that in this case parcel will ignore this file...is this correct?

**Comment by mischnic** [comment]
> ok any plan for solve this in the future?

Not a concrete one yet, but this is quite a frequent request

> I think that I can move the script to some folder in my server and require this for the full url path, so I think that in this case parcel will ignore this file...is this correct?

Yes

**Comment by cocodrino** [comment]
ok thank you...I'll close the issue then
