### ISSUE TITLE
Publishing release notes in repo's release section

### ISSUE THREAD

**Issue by raiyanalam** [parcel-bundler/parcel#3095]
Hi,
    I came across a few issues(#2834, #2739 ) and it looks like users aren't able to discover the release notes for each new version of the parcel. Would it be a good idea to publish the [changelog ](https://github.com/parcel-bundler/parcel/blob/master/CHANGELOG.md) in the releases section of GitHub? Today this section is empty and is not really useful to contributors. Also if this release section is used, every time a new release is published, GitHub would automatically notify users who are watching this repo.

![image](https://user-images.githubusercontent.com/7879476/58464593-985cd480-8153-11e9-8b6e-ee40ebc4895a.png)

Since the repo already uses Azure pipelines for CI, we can leverage its [built-in task](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/GitHubReleaseV0) to publish release notes to GitHub. The task can be configured to create a release only when the pipeline is triggered for a matching tag. Also, it can take the contents of a file that's checked into repository and add it as the release notes. Optionally, we can display a link to changelog file as well in the release notes.
Here is a [sample repo](https://github.com/Microsoft/vscode-react-native/releases) that leverages this capability.

PS: I am a PM for azure pipelines. I would be happy to help with the changes :)

**Comment by mischnic** [comment]
@devongovett

**Comment by raiyanalam** [comment]
@devongovett : Did you get opportunity to look into this?

**Comment by raiyanalam** [comment]
@mischnic :  @devongovett is probably isnt available, is there someone else who could take a look into this?
