### ISSUE TITLE
How Can I configure parcel.js for a multipage vanilla javascript site?

### ISSUE THREAD

**Issue by cocodrino** [parcel-bundler/parcel#3097]
# ❔ Question

I have an old project in jquery that consists of two independent pages, index and details (with independent I mean they do not share the javascript code)

I am modernizing this code, I am currently able to organize the home, separating the code into es6 modules, using sass and parcel preprocessing everything, everything works correctly

Now I'm doing the same procedure with the details page, it works ok but I notice that not only is loading the javascript of my page details but also of the home 

my home (index.html) includes a single file (index.js) where I import all the code required by the home,  I do the same  with details.html and the file details.js ...

I imagine that this is due to the very nature of parcel, which was created for SPA, I have seen a bit about code splitting (the documentation is scarce and confusing) and I imagine that maybe this is what I should use.

the best documentation has been this article https://hackernoon.com/code-splitting-with-parcel-web-app-bundler-fe06cc3a20da

must I use code splitting for this task?...can you explain me a little bit how would be the process?:  the event listener for load the index.js or the detail.js would be fire by $(document).ready for instance? or there is a better way to achieve this...thank you so much guys

**Comment by mischnic** [comment]
The article you linked is about dynamic JS imports, which you don't need.

Are you doing something like this?

```
-src
  - index.html (home)
  - home.js
  - home.scss
  - details.html
  - details.js
  - details.scss
```

index.html
```html
<script src="home.js"></script>
<link rel="stylesheet" type="text/css" href="home.scss">

<a href="./details.html">Details</a>
```

index.html
```html
<script src="details.js"></script>
<link rel="stylesheet" type="text/css" href="details.scss">
...
```

**Comment by cocodrino** [comment]
exactly @mischnic , a little fix

index.html
```html
<script src="index.js"></script>
<link rel="stylesheet" type="text/css" href="home.scss">

<a href="./details.html">Details</a>
```

details.html
```html
<script src="details.js"></script>
<link rel="stylesheet" type="text/css" href="details.scss">
```

but I'm notice that details.html is running both, index.js and details.js...is this correct?....

**Comment by cocodrino** [comment]
well..actually I'm just running the live server, parcel index.html...I'd expect that this follow the same behaviour that the final code with parcel build...

I'll check my source code again for be sure that I am not requiring in any way the index.js but it's a relief to at least know that this is not the expected behavior, please feel free to close the issue if you consider it ok, it is probably a mistake in my code, thanks again

**Comment by mischnic** [comment]
This works even with the dev server: https://github.com/mischnic/parcel-issue-3097

**Comment by cocodrino** [comment]
thank you @mischnic , after check my code I notice that one module required another module, which in turn required a function of the main module of the home, I refactoried and is now loading everything correctly, thank you so much

**Comment by mischnic** [comment]
🎉
