### ISSUE TITLE
Remove svg's ref attribute at build

### ISSUE THREAD

**Issue by ofk** [parcel-bundler/parcel#3111]
# 🐛 bug report

`parcel build`'s minifer erases `ref` attribute for vue.js of `<svg>`.

## 🎛 Configuration (.babelrc, package.json, cli command)

test.html:
```html
<!DOCTYPE html>
<html>
  <body>
    <p ref="p">p</p>
    <svg ref="svg">svg</svg>
  </body>
</html>
```

Run `parcel build test.html` with v1.12.3 and initial config.

## 🤔 Expected Behavior

dist/test.html:
```html
<!DOCTYPE html><html><body> <p ref="p">p</p> <svg ref="svg">svg</svg> </body></html>
```

## 😯 Current Behavior

dist/test.html:
```html
<!DOCTYPE html><html><body> <p ref="p">p</p> <svg>svg</svg> </body></html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3 |
| Node             | v10.15.1 |
| npm        | 6.7.0 |
| Operating System | macOS 10.14.4 |

**Comment by mischnic** [comment]
A `.htmlnanorc` file with 
```
{
	"minifySvg": false
}
```
should fix this.
Instead of completely disabling svg minification, you could also try figuring out which plugin is responsible for this: https://github.com/svg/svgo/blob/master/README.md#what-it-can-do

**Comment by ofk** [comment]
Thanks!
I got the desired result, after I put the `.htmlnanorc` file, remove the `.cache` directory and rebuild.
