### ISSUE TITLE
Hot reload only reload one line of parents

### ISSUE THREAD

**Issue by hlehmann** [parcel-bundler/parcel#3112]
# 🐛 bug report

It appear that hot reload only refresh one line of dependant modules instead of all of dependant modules

## 💻 Code Sample

````javascript
// index.js
const render = async () => {
  const {App} = await import("./app");
  ReactDom.render(<App />, document.getElementById("app"));
}

render()
module.hot.accept(render)

// app.js
import "a";
import "b";

export const App = () => null;

// a.js
import {cpt} from "c";
console.log("a", cpt);

// b.js
import {cpt} from "c";
console.log("b", cpt);

// c.js
export const cpt = 1;
````
## 🤔 Expected Behavior

When cpt value is changed (to 2 for example) we expect to get the following logs
a 2
b 2

## 😯 Current Behavior

But we get only
b 2

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 12.3.0
| yarn         | 1.16.0
| ubuntu | 18.4

**Comment by mischnic** [comment]
If thats really all code, then HMR should only cause a full page reload.
To opt into the JS hot module replacement, you need to call `module.hot.accept();`

**Comment by hlehmann** [comment]
@mischnic Yes sorry I didn't put the first file. I have updated my code issue accordingly.
