### ISSUE TITLE
--host= fails when parcel runs behind proxy 

### ISSUE THREAD

**Issue by meysholdt** [parcel-bundler/parcel#3113]
# 🐛 bug report

```
parcel src/index.html --host=www.foobar.com
```
fails when using a proxy server, load balancer or ssl-endpoint. 

Reason: parcel should not assume it can open a port on `www.foobar.com`'s IP address, because that IP belongs to the proxy, and not to parcel's host.

## 🎛 Configuration

1. open https://gitpod.io/#https://github.com/parcel-bundler/examples
2. GitHub OAuth required for git-clone.
3. In the Terminal View:
4. `npm install -g parcel-bundler`
5. `cd react`
6. `yarn install`
7. `gp url 1234` to obtain the hostname of our workspace, e.g. `1234-ca3dafd4-0cea-4628-b436-be6af23ab87d.ws-eu0.gitpod.io`
8. `parcel src/index.html --host=1234-ca3dafd4-0cea-4628-b436-be6af23ab87d.ws-eu0.gitpod.io`

## 🤔 Expected Behavior

A message asking be to specify the IP address that parcel should listen on.

## 😯 Current Behavior

I get this error message:
```
{ Error: listen EADDRNOTAVAIL: address not available 34.76.156.35:1234
    at Server.setupListenHandle [as _listen2] (net.js:1253:19)
    at listenInCluster (net.js:1318:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1451:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:61:10)
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: '34.76.156.35',
  port: 1234 }
```

## 💁 Possible Solution

It would be nice if I can specify the IP parcel should listen on, for example:
```
parcel src/index.html \
    --address=0.0.0.0
    --host=1234-ca3dafd4-0cea-4628-b436-be6af23ab87d.ws-eu0.gitpod.io
```

## 🔦 Context

parcel is not usable in the Online IDE www.gitpod.io

parcel is not usable behind proxies, load balancers or ssl-terminations. 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3 |
| Operating System | Linux |

**Comment by mischnic** [comment]
We literally do this:
```js
const server = http.createServer(handler);
server.listen(..port set by --port, ..host set by --host..);
```

Are you sure gitpod supports this?
Can you start a normal static fileserver?

https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback

https://github.com/parcel-bundler/parcel/blob/4b50182129b19395b791cf1e4194069ae8736ef4/packages/core/parcel-bundler/src/Server.js#L127-L136

**Comment by meysholdt** [comment]
hi @mischnic !

thank you for your super-fast response. 

`parcel` works perfectly find in Gitpod when I run 
```
parcel src/index.html --host=0.0.0.0
```
or simply 
```
parcel src/index.html
```

But then, the site served by parcel contained links to `http://localhost` or `http://0.0.0.0`. 

However, the situation is a bit more complex and I'm not the primary witness of this behaviour and I'm not sure anymore if parcel is to blame or the site that needs to use the proper hostname for generating links. 

Closing, I'll re-open or re-file in case I find something parcel could do better.
