### ISSUE TITLE
Error when using log-level 5

### ISSUE THREAD

**Issue by JoshuaWalsh** [parcel-bundler/parcel#3116]
# 🐛 bug report

If you specify log-level 5 an error is thrown and the build fails.

## 🎛 Configuration (.babelrc, package.json, cli command)

```bash
parcel build src/index.hbs --log-level 5
```

## 🤔 Expected Behavior

A log file should be created

## 😯 Current Behavior

```
[1:05:19 AM]: Building...
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'D:\git\personal-website\parcel-debug-2019-05-31T15:05:19.980Z.log'
Emitted 'error' event at:
    at fs.open (internal/fs/streams.js:292:12)
    at FSReqCallback.args [as oncomplete] (fs.js:147:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! personal-website@ build: `parcel build src/index.hbs --log-level 5`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the personal-website@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\josh\AppData\Roaming\npm-cache\_logs\2019-05-31T15_05_20_019Z-debug.log
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3 |
| Node             | 11.6.0 |
| npm         | 6.5.0-next.0 | 
| Operating System | Windows 10 |

**Comment by spaceneenja** [comment]
I'm getting the same issue.
```

$ ./node_modules/.bin/parcel ./source/index.html --log-level 5
[10:33:45 AM]: Server running at http://localhost:1234 
[10:33:45 AM]: Building...
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '<mydir>\parcel-debug-2019-06-09T14:33:45.295Z.log'
Emitted 'error' event at:
    at internal/fs/streams.js:289:12
    at FSReqCallback.oncomplete (fs.js:153:23) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: '<mydir>\\parcel-debug-2019-06-09T14:33:45.295Z.log'
}
```

**Comment by JoshuaWalsh** [comment]
Reproduced in v1.12.4

**Comment by oddeirik** [comment]
I came across this bug as well. This is because the log file name contains a date/time string with colons, which is not a valid character on Windows:
```
path.join(process.cwd(), `parcel-debug-${currDate.toISOString()}.log`)
```
https://github.com/parcel-bundler/parcel/blob/master/packages/core/logger/src/Logger.js#L78

A quick string.replace  with dashes or some other valid character should do the trick:
```
path.join(process.cwd(), `parcel-debug-${currDate.toISOString().replace(/\:/g, '-')}.log`)
```

## 🌍 Your Environment



| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 12.16.2
| npm/Yarn         | 6.14.4
| Operating System | Windows 10 1909 (build 18363.815)

**Comment by JoshuaWalsh** [comment]
@oddeirik Do you want to submit a PR? If not I'm happy to, but since you found the cause it seems right for you to get credit for the fix.

**Comment by oddeirik** [comment]
If you could do it, I'd be happy. I'm running low on spare time this week. And besides, you've clearly been annoyed by this bug far longer than me 😄
