### ISSUE TITLE
parcel live server don't autoupdate changes in my tailwind project

### ISSUE THREAD

**Issue by cocodrino** [parcel-bundler/parcel#3122]
Hi guys, I can't found a parcel/tailwind based on the new tailwind api... version v1+ so I adapted a project, seems works ok, parcel compiles the postcss and show correctly the webpage, but if I change something in the html the first time works, but after the first time seems that the live server stop reloading the changes and I don't get the changes in the screen

I did this project
https://github.com/cocodrino/tailwind-1-with-parcel

this has two branches, the master branch is the code adapted from the tailwind v0.7 ...so I just only change the version in the package file and use @tailwind base ...also there is a youtubelike branch...which use a .postcssrc, both branches fails in the same way, they don't update the website after any html/css change...

**Comment by stoically** [comment]
Maybe you're affected by https://en.parceljs.org/hmr.html#safe-write

**Comment by cocodrino** [comment]
thank you @starkwang that works great!
