### ISSUE TITLE
autoinstall not working

### ISSUE THREAD

**Issue by FDiskas** [parcel-bundler/parcel#3123]
# 🐛 bug report

Auto install does not works.

## 🎛 Configuration (.babelrc, package.json, cli command)

[1559554356423.zip](https://github.com/parcel-bundler/parcel/files/3246872/1559554356423.zip)

## 🤔 Expected Behavior

If I start a project `npm start`
It should auto install required dependencies ex.
```
    "posthtml-expressions": "^1.1.1",
    "posthtml-extend": "^0.3.0",
    "posthtml-include": "^1.2.0"
```

## 😯 Current Behavior

No error is shown, no additional installation is done.

## 💁 Possible Solution

Downgrade parcel to `1.10.3`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3 |
| Node             | v10.15.3
| npm/Yarn         | npm 1.12.3
| Operating System | Linux

**Comment by FDiskas** [comment]
Is this still valid? :left_right_arrow:

**Comment by DeMoorJasper** [comment]
@FDiskas Please try it out with Parcel 2: `parcel@next` or `parcel@nightly` and feel free to open a new issue if you find any bugs. This one or new ones.
