### ISSUE TITLE
Failure starting Express with --target=node (TypeError: t is not a function)

### ISSUE THREAD

**Issue by stephenfrancis** [parcel-bundler/parcel#3125]
# 🐛 bug report

Trying to replace webpack in compiling server-side code to a single .js file (for use in an AWS Lambda). The file generated by parcel appears to be non-functional, at least the way I am trying to start it.

I have created a publicly-available repo to provide complete reproducibility: https://github.com/pricesearcher/colombia `use-parcel-not-webpack` branch.

## 🎛 Configuration (.babelrc, package.json, cli command)

See repo: `package.json`
I'm not using babel - should I be? I don't see anything in the docs about this?

## 🤔 Expected Behavior

Node should start, running the Express middleware, listening on port 8081. A request to http://localhost:8081/ should respond with a 200 status code, and the body containing a random number between 1 and 1000.

## 😯 Current Behavior

```
root@e9a4e28aef44:/app# node build/server/local.js
/app/build/server/local.js:1
(function (exports, require, module, __filename, __dirname) { parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&de

TypeError: t is not a function
    at Object.parcelRequire.he0/ (/app/build/server/local.js:2:239)
    at f (/app/build/server/local.js:1:530)
    at parcelRequire.he0/.e.__importStar.t (/app/build/server/local.js:1:833)
    at Object.<anonymous> (/app/build/server/local.js:1:1085)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
root@e9a4e28aef44:/app# 
```

## 🔦 Context

I am trying to replace webpack in a project with parcel. Webpack takes ages. I am not using HMR - mainly same React code runs server-side for Server-Side Rendering as well as Client-Side, and I have struggled to get Typescript-compilation and nodemon to work with webpack. Story for another day.

## 💻 Code Sample

https://github.com/pricesearcher/colombia/tree/use-parcel-not-webpack
(public repo - credentials should not be required)

## 🌍 Your Environment

This repo uses docker to standardize the build environment - the following should work on any machine that has git, make and docker commands available:

1. git clone https://github.com/pricesearcher/colombia
2. cd colombia
3. git checkout use-parcel-not-webpack
4. make --file=src/config/Makefile build_docker
5. make --file=src/config/Makefile start_docker
6. make build
7. node build/server/local.js

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0 |
| Node             | 8.15.1 |
| npm/Yarn         | npm 6.4.1 |
| Operating System | Docker Container: Debian GNU/Linux 9 (stretch), Host: Ubuntu 18.04 LTS |

**Comment by mischnic** [comment]
I'm not a typescript export, but changing
`import * as Express from "express";`
into
`import Express from "express";`
fixes the issue.
This is also how it's done in an official typescript sample app: https://github.com/microsoft/TypeScript-Node-Starter/blob/3916ec53dfa278e96b876bda2525f70e0b54e0a6/src/app.ts#L1

**Comment by stephenfrancis** [comment]
Thank you - I thought it was going to be harder than that...!
