### ISSUE TITLE
TailwindCSS @apply feature doesn't work

### ISSUE THREAD

**Issue by stoically** [parcel-bundler/parcel#3126]
# 🐛 bug report

The [`@apply` feature](https://tailwindcss.com/docs/functions-and-directives/#apply) from [TailwindCSS](https://github.com/tailwindcss/tailwindcss) doesn't work as expected when bundling with Parcel.

## 🤔 Expected Behavior

`@apply` should work with existing tailwind utilities.

## 😯 Current Behavior

`@apply` doesn't work with existing tailwind utilities.

## 💁 Possible Solution

Maybe https://github.com/parcel-bundler/parcel/issues/1165 is related.

## 💻 Code Sample

```
npm install tailwindcss
```

`postcss.config.js`
```js
module.exports = {
  plugins: [
    require('tailwindcss')
  ]
};
```

`styles.css`
```css
@tailwind base;

@tailwind components;

@tailwind utilities;

.red {
  @apply text-red;
}
```

```
parcel build styles.css
```

## Error Message

Tailwind Error when bundling

```
`@apply` cannot be used with `.text-red` because `.text-red` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.text-red` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.15.3
| npm/Yarn         | npm 6.9.0
| Operating System | Ubuntu 18.04

**Comment by adamwathan** [comment]
This is a mistake on your end I think, in Tailwind 1.0 there is no `text-red` class, every text color class has a numeric suffix, like `text-red-100`, `text-red-200`, `text-red-300`, etc.

**Comment by stoically** [comment]
Seems like you're right. I'm pretty sure I've tested with actually existing utilities and just tried to simplify the issue, hence the text-red mistake. But I've tried again and now it works as expected. Oh well, thanks!

**Comment by adamwathan** [comment]
There's still an issue if you define a user-defined utility in a separate file and try to apply it in another file (because of the import bug outlined in your linked issue) but once that other issue is resolved things should work 👍🏻
