### ISSUE TITLE
parcel build --bundle-node-modules does not properly transform native module requires

### ISSUE THREAD

**Issue by dgriffen** [parcel-bundler/parcel#3130]
# 🐛 bug report

When building a node application with bundled node modules (e.g. `node-pty`) the native .node files are copied to the `dist` folder but the references to them inside of the `.js` file are not updated to point to the correct location.

## 🎛 Configuration (.babelrc, package.json, cli command)

cli command: `parcel build -t node --bundle-node-modules`

## 🤔 Expected Behavior

parcel should transform internal `requires` statements to point to the `.node` files put into the `dist` folder

## 🔦 Context

I am trying to create a small bundle using `node-pty`, I want the files bundled to ease distribution since this is a pre-built package and users cannot be expected to run `npm install`.

## 💻 Code Sample

https://gist.github.com/dgriffen/37ce2da255763f34708d26d346540436
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.15.3
| npm/Yarn         | 6.4.1
| Operating System | Windows 10

**Comment by mischnic** [comment]
Thanks, we are aware of this issue and tracking it in #2493:

> Support native modules (.node) by copying them to the dist directory.
