### ISSUE TITLE
DoS vulnerability in dependency serialize-to-js@1.1.1

### ISSUE THREAD

**Issue by luddwichr** [parcel-bundler/parcel#3133]
# 🐛 bug report

The dependency [serialize-to-js](https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/package.json#L71) is exposing a DoS vulnerability in version 1.1.1. See [this issue for more details](https://github.com/commenthol/serialize-to-js/issues/7).

I stumbled upon this issue indirectly because Github sent me a different security alert for safer-eval@1.3.2, which is a transitive dependency of serialize-to-js. However, upgrading safer-eval is not sufficient due to the above referenced vulnerability.

## 💁 Possible Solution

Upgrade to serialize-to-js@^3.0.0 if no functionality is lost (the method `deserialized` was dropped due to the issue in version 2.0.0)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 12.4.0
| npm/Yarn         | 1.16.0
| Operating System |

**Comment by mkeedlinger** [comment]
For some reason `npm audit fix` still can't fix this issue. Am I missing something?

Has this been pushed to npm yet?

<sub>Thanks!</sub>
