### ISSUE TITLE
Will Parcel 2 feature externals or aliases without requiring url

### ISSUE THREAD

**Issue by afridley** [parcel-bundler/parcel#3137]
# ❔ Question

In the Parcel 2 RFC https://github.com/parcel-bundler/parcel/pull/1952#r213803613
There is discussion of handling externals through aliases in the following way
```js
"aliases": {
  "react": {
     "url": "https://unpkg.com/react@16.4.2/umd/react.production.min.js",
     "global": "React"
   },
   "datatables": { 
     "url": "//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css",
     "global": null
   }
}
```

I am wondering if this will this work with out a url? In case you want to replace a module (@wordpress/blob) with a value (wp.blob) to be used to retrieve a global (wp.blob) variable. 

example from webpack
```js 
{ 
  externals: { 
    '@wordpress/blob': 'wp.blob'
   }
}
```

Or will this type of behavior not be supported by aliases?

## 🔦 Context

Right now Parcel does not ignore externals or you need to setup additional steps per external which can become tedious.
example
https://github.com/parcel-bundler/parcel/issues/144#issuecomment-383364337

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.16.0
| npm/Yarn         | 1.13.0
| Operating System | MacOs

**Comment by devongovett** [comment]
We haven't talked much about externals yet, but this is good to consider. Thanks for bringing this back up.

I think maybe it could still work with aliases:

```json
"aliases": {
  "react": {
     "global": "React"
   }
}
```

**Comment by devongovett** [comment]
Closing in favor of #3305
