### ISSUE TITLE
Spectrum is awful

### ISSUE THREAD

**Issue by LewisAndrewCampbell** [parcel-bundler/parcel#3152]
I don't know how to put this politely, but spectrum is the worst piece of web software I have ever interacted with. I have unsubscribed from it's emails about 5 different times and it still emails me, I gave up and just marked it as spam. It's login is confusing, it's sign up is confusing, it's slow. Just atrocious.

Is slack/discord/irc/gitter not an option?

**Comment by DeMoorJasper** [comment]
We originally had Slack and switched to Spectrum as it was a better fit.
Personally I haven't had much issues with Spectrum besides from being slow.

**Comment by mischnic** [comment]
I agree with the slowness, but one (potential) benefit of Spectrum are the forum-style posts.

**Comment by LewisAndrewCampbell** [comment]
The issue with spectrum is it sends you an email every time someone breathes or twitches a muscle. Then you sign in, fumble around with its irritating UI, unsubscribe... then a few weeks later it re-subscribes you. It's like the bonzai buddy of chat software.

Anyway, parcel is great, and I realise I'm being the stereotypical entitled free-loader who uses open source software. But I would just love to be able to chat with the community without wanting to throw my computer out the window. If I am alone in this, than so be it.

**Comment by mischnic** [comment]
> The issue with spectrum is it sends you an email every time someone breathes or twitches a muscle. 

I somehow managed to only get a list of active posts once per week.

**Comment by devongovett** [comment]
Please provide your feedback to the Spectrum team: https://spectrum.chat/spectrum
