### ISSUE TITLE
Tree shaking with TS throw `token.ts does not export 'Token'`

### ISSUE THREAD

**Issue by ocavue** [parcel-bundler/parcel#3153]
# 🐛 bug report

Parcel says `Token`, which is a typescript interface, is not exported when I use `--experimental-scope-hoisting`. 

I create a repo to reproduce this issue.

## 🎛 Configuration (.babelrc, package.json, cli command)

```
>>> git clone https://github.com/ocavue/parcel_issue_3153.git
>>> cd parcel_issue_3153
>>> yarn install
✨  Done in 0.38s.

>>> yarn run build1
yarn run v1.16.0
$ parcel build index.html
✨  Built in 45ms.

dist/tmp_parcel_issue.a55b6250.js        1.71 KB    9ms
dist/tmp_parcel_issue.a55b6250.js.map    1.03 KB    3ms
dist/index.html                            304 B    5ms
✨  Done in 0.74s.

>>> yarn run build2                                                                                                                               
yarn run v1.16.0
$ parcel build index.html --experimental-scope-hoisting
🚨  pkg/token.ts does not export 'Token'
    at replaceExportNode (/tmp/parcel_issue/node_modules/parcel-bundler/src/scope-hoisting/concat.js:54:13)
    at ReferencedIdentifier (/tmp/parcel_issue/node_modules/parcel-bundler/src/scope-hoisting/concat.js:317:20)
    at newFn (/tmp/parcel_issue/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/visitors.js:230:17)
    at NodePath._call (/tmp/parcel_issue/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/tmp/parcel_issue/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/tmp/parcel_issue/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/tmp/parcel_issue/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/tmp/parcel_issue/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/tmp/parcel_issue/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/tmp/parcel_issue/node_modules/parcel-bundler/node_modules/@babel/traverse/lib/index.js:94:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

## 🤔 Expected Behavior

`yarn run build2` should work 

## 😯 Current Behavior

`yarn run build2` doesn't work 

## 🔦 Context

Maybe it's a duplicate of #2837. But this issue involves TS so I'm not sure.

## 💻 Code Sample

N/A

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.3|
| Node             |12.4.0|
| npm/Yarn         | yarn 1.16.0|
| Operating System | macOS 10.13|

**Comment by mischnic** [comment]
From Parcel's standpoint, this is actually somewhat expected, these are the transpiled typescript files before they're merged during scope-hoisting:
```js
<<<<<<<<<<<<<<<<<<<<<<<<index.ts>>>>>>>>>>>>>>>>>>>>>
import { func } from "./pkg/main";
func({ classes: ['1', '2', '3'] });

<<<<<<<<<<<<<<<<<<<<<<<<pkg/main.ts>>>>>>>>>>>>>>>>>>>>>
// Defines a parser and serializer for [CommonMark](http://commonmark.org/) text.
export { Token } from './token';
export { func } from "./func";

<<<<<<<<<<<<<<<<<<<<<<<<pkg/token.ts>>>>>>>>>>>>>>>>>>>>>
export function sortClasses(token) {
    token.classes.sort();
    return token;
}

...
```

Notice how the `export interface Token` statement got removed (because it's only a type and does not correspond to an actual JS construct) but `Token` is still referenced in `pkg/main.ts`.

Without scopehoisting, the situation is exactly the same (though TS directly emits CommonJS modules here), but instead Token would be `undefined` because the CommonJS modules aren't statically analyzable.

```js
<<<<<<<<<<<<<<<<<<<<<<<<index.ts>>>>>>>>>>>>>>>>>>>>>
"use strict";
exports.__esModule = true;
var main_1 = require("./pkg/main");
main_1.func({ classes: ['1', '2', '3'] });

<<<<<<<<<<<<<<<<<<<<<<<<pkg/main.ts>>>>>>>>>>>>>>>>>>>>>
"use strict";
// Defines a parser and serializer for [CommonMark](http://commonmark.org/) text.
exports.__esModule = true;
var token_1 = require("./token");
exports.Token = token_1.Token;
var func_1 = require("./func");
exports.func = func_1.func;

<<<<<<<<<<<<<<<<<<<<<<<<index.ts>>>>>>>>>>>>>>>>>>>>>
"use strict";
exports.__esModule = true;
var main_1 = require("./pkg/main");
main_1.func({ classes: ['1', '2', '3'] });

<<<<<<<<<<<<<<<<<<<<<<<<pkg/token.ts>>>>>>>>>>>>>>>>>>>>>
"use strict";
exports.__esModule = true;
function sortClasses(token) {
    token.classes.sort();
    return token;
}
exports.sortClasses = sortClasses;

...
```

So the main issue is: TS removes type exports but doesn't remove type imports.
Not sure how to solve this.

**Comment by ocavue** [comment]
> Does tsc remove that stray import?

Seems that `tsc` does remove it.

I simply run `yarn run tsc` in `parcel_issue_3153`. The `pkg/main.js` generated by `tsc` is as below, which doesn't include `Token` anymore:

```js
"use strict";
// Defines a parser and serializer for [CommonMark](http://commonmark.org/) text.
exports.__esModule = true;
var func_1 = require("./func");
exports.func = func_1.func;
```

**Comment by mischnic** [comment]
Thank you for testing that. 
`@babel/preset-typescript` behaves like just parcel and running the output using `node -r esm` even also results in: `SyntaxError: The requested module '.../dist-babel/pkg/token.js' does not provide an export named 'Token'`. 
Scope hoisting is behaving correctly, the problem here is Typescript.

**Comment by ocavue** [comment]
Thank you so much for your comments. I have found a [solution](https://github.com/facebook/create-react-app/issues/6054#issuecomment-481441272) after reading the docs you quoted.


```js
<<<<<<<<<<<<<<<<<<<<<<<<pkg/main.ts>>>>>>>>>>>>>>>>>>>>>
import { Token } from './token'
export type Token = Token
export { func } from "./func"
```

BTW, a related issue can be found here: https://github.com/babel/babel/issues/8361

**Comment by ocavue** [comment]
Since it's actually a Babel issue instead of a parcel issue, I close it.
