### ISSUE TITLE
opn is deprecated, use open instead

### ISSUE THREAD

**Issue by jamesgeorge007** [parcel-bundler/parcel#3160]
[opn](https://www.npmjs.com/package/opn) is deprecated and renamed to [open](https://www.npmjs.com/package/open). 
Currently, parcel `v1` supports node-js version 6 which is incompatible with the respective package. 

> Nice to have as part of `v2`

**Comment by jamesgeorge007** [comment]
@mischnic An effort was made here: #3159

**Comment by jamesgeorge007** [comment]
@DeMoorJasper can #3159 be kept on hold for the `v2` release :thinking:

**Comment by DeMoorJasper** [comment]
@jamesgeorge007 you can re-open the PR and target the v2 branch if you want
