### ISSUE TITLE
sourcemaps of items that shouldn't be 'mapped'

### ISSUE THREAD

**Issue by flowen** [parcel-bundler/parcel#3165]
# 🐛 bug report
I'm getting very strange warnings about sourcemaps. Only on the '/' page.

See:
![Screen Shot 2019-06-24 at 22 30 03](https://user-images.githubusercontent.com/4084169/60053475-d6f09b00-96cf-11e9-8b01-061ab9b46138.png)

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
  "scripts": {
    "dev": "parcel src/index.pug",
    "build": "parcel build src/index.pug"
  },
  "devDependencies": {
    "parcel-plugin-imagemin": "^2.1.3",
    "pug": "^2.0.4",
    "sass": "^1.21.0"
  },
  "dependencies": {
    "@dogstudio/highway": "^2.1.2"
  }
```

## 🤔 Expected Behavior

no warnings 

## 😯 Current Behavior

warnings in console
I also have a syntax error on `all-html-elements` page which is strangely only received on the contact page. Not sure if this is related somehow

## 💻 Code Sample

[repo](https://github.com/flowen/static-starter-highway)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 11.13.0
| Yarn          |  1.15.2
| Operating System | MacOS 10.14.5

**Comment by DeMoorJasper** [comment]
This isn’t a parcel bug. This is related to how parcel-plugin-imagemin works

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
