### ISSUE TITLE
How to work with static assets like fonts, images without to reference them?

### ISSUE THREAD

**Issue by StarpTech** [parcel-bundler/parcel#317]
Hi, how it is possible to import dynamic content like fonts or images which aren't references in code?

### 😯 Current Behavior
```js
import "font-awesome/fonts/specific.ttf" // returns a single url
import "font-awesome/fonts/specific.woff"
import "font-awesome/fonts/specific.eot"
....
```

### 💁 Possible Solution
```js
import "font-awesome/fonts/*" // returns an array of url's
```
[babel-plugin-wildcard](https://github.com/vihanb/babel-plugin-wildcard)

### 🔦 Context
Importing a bunch of static assets e.g to include fonts or images which aren't directly referenced in the code e.g parcel does not interpret sass variables.

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  1.2.0
| Node             | 8.9
| npm/Yarn         | npm
| Operating System | Windows 10

**Comment by chee** [comment]
your possible solution _is_ the current behaviour, except it's an object not an array.

```
import fonts from 'webfonts/*'
console.log(fonts)

// >>

{
  "fa-brands-400.svg": "/c93a719bd1a2bb754e1ff39dd44ce213.svg"
  "fa-brands-400.ttf": "/3cbc230cc76bbe87cfe897fe010e262b.ttf"
  "fa-regular-400.svg": "/0f0865fbbcff198bf977228c2a022de9.svg"
  "fa-regular-400.ttf": "/93401b2e0b2c5df731d220b244ea5b5e.ttf"
}
```

if you want an array, you can use `Object.values(fonts)`

**Comment by brandon93s** [comment]
Curious why the individual fonts need importing, and not the css that leverages them?

As @chee mentioned, [GlobAsset](https://github.com/parcel-bundler/parcel/blob/master/src/assets/GlobAsset.js) should already be handling this type of import.

**Comment by Munter** [comment]
Fonts should always be referenced with an `@font-face` CSS declaration. If they are not, having them be a part of the build will make no difference, since the browser will not know hoe to load them anyway.

I assume that Parcel handles font loads with its `url(...)` matching regex in the CSS asset, so font should be picked up by importing the `@font-face` declaring CSS

**Comment by StarpTech** [comment]
@chee I try it again and it works but `/fonts/**` doesn't it results in an empty `dist` dir

**Comment by shunia** [comment]
`import xx from 'folder/*'` did helped a lot, as @chee pointed out, and Parcel handles this right.

But vscode shows error when editing:

![image](https://user-images.githubusercontent.com/779430/34708458-c8e2409c-f54d-11e7-95ad-c804f13a1935.png)

Any info that I can clear this error please?

**Comment by willwull** [comment]
Having the same issue as @shunia, any update on this? Ended up doing a `eslint-disable-line` on that import for now.

**Comment by kaw2k** [comment]
using `require` bypasses the perceived error in vscode

**Comment by jtenner** [comment]
![image](https://user-images.githubusercontent.com/3761339/40386187-fe7ac28c-5dd6-11e8-9577-72c6f5d70e4d.png)

Testing out GlobAsset works awesome. Whoever worked on this, thank you many times over.

**Comment by mohsen1** [comment]
If TypeScript is yelling at you about the module name you can create a file named `declarations.d.ts` in your repo and put module declaration code in it:

**declaration.d.ts**
```ts
declare module "assets/**"
```

**Comment by DeMoorJasper** [comment]
Parcel should support globs and watch/invalidate them properly

**Comment by zanona** [comment]
I'm trying to use `import iconFont from './sr/styles/icons.woff'`, but I get:
>  Error: No transformers found for "/mnt/app/src/styles/icons.woff".

Help! :wink: 
Parcel v2.0.0-alpha.3.2

**Comment by mischnic** [comment]
https://parcel2-docs.now.sh/getting-started/migration/#importing-non-code-assets-from-javascript

```js
import logo from "url:./logo.svg";

document.body.innerHTML = `<img src="${logo}">`;
```
