### ISSUE TITLE
Parcel can't resolve dependency with a tilde path

### ISSUE THREAD

**Issue by Zarwlar** [parcel-bundler/parcel#3171]
# 🐛 bug report

My application using typescript and react, so I'm following [this](https://gist.github.com/croaky/e3394e78d419475efc79c1e418c243ed) gist from parcel docs to make src folder as root, but unfortunately I get the error.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
tsconfig {
{
  "compilerOptions": {
    "traceResolution": false,
    "sourceMap": true,
    "strictNullChecks": true,
    "noImplicitAny": true,
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es6",
    "lib": [
      "es2015",
      "es2016",
      "es2017",
      "es6",
      "es7",
      "es5",
      "dom"
    ],
    "jsx": "react",
    "experimentalDecorators": true,
    "paths": {
      "~*": [
        "./*"
      ]
    },
    "baseUrl": "./src",
    "allowJs": true,
    "noUnusedParameters": true,
    "noUnusedLocals": true,
    "importHelpers": true,
    "noStrictGenericChecks": true
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules"
  ]
}

}
```

Sorry, but I can't show you working tree at the current moment, because I've some troubles with my OS. Any way it looks very similar in structure from gist.

## 🤔 Expected Behavior

I'd like to see how my program starting without any errors 🙌

## 😯 Current Behavior

I get error:

> Cannot resolve dependency '\~/shared/paths' at '/Projects/myproj/src/core/containers/\~/shared/paths'

## 💁 Possible Solution

Idk

## 🔦 Context

I think i gave all the info that was necessary, but if you want more I'll tell you.

## 💻 Code Sample

No code, I just try to run my program using below command:

```js
 node_modules/.bin/parcel watch ./src/core/client/index.html
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 9.11.1
| npm/Yarn         | 6.9.0
| Operating System | Linux Mint Release 19.1

**Comment by mischnic** [comment]
I tried to replicate the gist: https://github.com/mischnic/parcel-issue-3171, but there was no error.
Could you provide a more detailed reproduction of your code?

**Comment by Zarwlar** [comment]
Sorry, but now I'm not using Parcel. This issue can be closed. Thank you for your support
