### ISSUE TITLE
[ScopeHoisting] Statically exported members used internally inside the class scope should have exports mapped to module scope when bundled

### ISSUE THREAD

**Issue by Stradivario** [parcel-bundler/parcel#3172]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```json
{
  "scripts": {
    "start": "parcel start ./src/index.html --public-url=/flags",
    "build": "parcel build ./src/index.html --public-url=/flags --experimental-scope-hoisting"
  },
  "dependencies": {
    "@rxdi/core": "^0.6.7",
    "@rxdi/lit-html": "^0.6.7",
    "rxjs": "^6.5.2",
    "@webcomponents/webcomponentsjs": "^1.2.4",
    "@babel/polyfill": "^7.0.0"
  },
  "browserslist": [
    "last 1 chrome versions"
  ]
}
```

tsconfig.json

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": ".",
    "sourceMap": true,
    "module": "esnext",
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "target": "es6",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2015",
      "es2016",
      "es6",
      "es2017",
      "dom"
    ]
  },
  "include": [
    "./src/**/*"
  ]
}

```

## 🤔 Expected Behavior
Statically exported members used internally inside the class scope should have `exports` mapped to module scope when bundled

## 😯 Current Behavior
Statically exported members are not mapped internally inside the scope of the current Class which leading to `property of undefined`

example:

This peace of code is taken from https://github.com/Polymer/lit-html/blob/master/src/lib/parts.ts#L145

Important part is here:
https://github.com/Polymer/lit-html/blob/master/src/lib/parts.ts#L311

They are creating new Instance of the class NodePart as a factory if this particular part doesn't exist inside the DOM.

The problem here is that when compiled this part of code remains the same without `export` referencing him to the `module` `scope`

Typescript
```typescript
itemPart = new NodePart(this.options);
```

Javascript
```typescript
itemPart = new NodePart(this.options);
```

Instead it should be 

```typescript
itemPart = new exports.NodePart(this.options);
```

The case here is that i am getting the following error

```typescript
Uncaught ReferenceError: NodePart is not defined
```

When i change the code with exports.NodePart everything is back to normal and i can use my application with Scope hoisting.

Is this normal to behave like this ? 

Is it a problem with implementation and how Typescript compile the code without exports.NodePart ?

Is this issue for Typescript team or ParcelJS ? 

here is a simple repository reproducing the problem

https://github.com/Stradivario/parcel-scope-hoisting

1.Run npm start (to have server started)
2. Run `npm run build` command
3. Try to refresh the page after build is success
4. You will get the following error `Uncaught ReferenceError: NodePart is not defined`
5. Then run command `npm run fix` and wait for build to finish
6. Refresh the page and you will se that the application is working properly

```
npm run fix
```
This command copy file with `exports.NodePart` property to `node_modules` folder and then rerun `parcel build ./src/index.html --public-url=/flags --experimental-scope-hoisting`

Why this thing happen ? Anyone ?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             |  10.16.0
| npm         | 6.9.0
| Operating System | Ubuntu 18.4.2

**Comment by Stradivario** [comment]
Pull request with current fix on Polymer lit-html

https://github.com/Polymer/lit-html/pull/954

**Comment by mischnic** [comment]
This is a bug in the name mangling process, (and I though we had it fixed: https://github.com/parcel-bundler/parcel/issues/2513, https://github.com/parcel-bundler/parcel/issues/2513, https://github.com/parcel-bundler/parcel/issues/2981):

```js
class NodePart {
    __commitIterable(value) {
        let x = new NodePart();
    }
}
```
is turned into
```js
class $zoHw$var$NodePart {
    __commitIterable(value) {
        let x = new NodePart(); // NodePart is undefined now
    }
}
```

**Comment by Stradivario** [comment]
@mischnic i am glad that i face it then!

Also getting the same output trying to build this lib

https://github.com/vaadin/vaadin-router/blob/master/src/router.js#L187

They are using Static methods when initializing constructor properties thus leading to the same error

Regards!

**Comment by Stradivario** [comment]
Any news here guys :) ? @mischnic

**Comment by mischnic** [comment]
Please follow https://github.com/parcel-bundler/parcel/issues/3664 for updates
