### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by dy** [parcel-bundler/parcel#3174]
Also, following the default readme, after installing global parcel-bundler:

```js
// index.js
(async () => {})()
```

```
index.js:23 Uncaught ReferenceError: regeneratorRuntime is not defined
    at Object.parcelRequire.index.js (index.js:23)
    at newRequire (test.e31bb0bc.js:47)
    at test.e31bb0bc.js:81
    at test.e31bb0bc.js:120
```

Expected: basic modern js practices to work without additional configurations.

**Comment by mischnic** [comment]
Yes, this is a known issue: https://github.com/parcel-bundler/parcel/issues/1762
