### ISSUE TITLE
pug.config.js pretty: true not working

### ISSUE THREAD

**Issue by smith-js** [parcel-bundler/parcel#3177]
# ❔ Question

I'm trying to enable `pretty: true` in `pug.config.js`, but nothing changes

## 💻 Code Sample

```
// pug.config.js
module.exports = {
    pretty: true
};
```

```
// package.json
{
  "name": "test",
  "version": "1.0.0",
  "license": "MIT",
  "private": true,
  "scripts": {
    "build": "parcel build ./src/templates/pages/*.pug"
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.3",
    "pug": "^2.0.4"
  }
}
```

`yarn build`

Result:
`<!DOCTYPE html><html lang="en"><head><title>test</title></head><body><div class="test"></div></body></html>`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.3
| Node             |10.15.3
| npm/Yarn         |1.15.2
| Operating System |Windows 10

**Comment by DeMoorJasper** [comment]
Parcel runs these through the html minifier, you should add --no-minify
