### ISSUE TITLE
Postcss-modules config broken with plugins array syntax

### ISSUE THREAD

**Issue by mikestopcontinues** [parcel-bundler/parcel#3178]
# 🐛 bug report

Postcss config support plugins set as an array (`{plugins: []}`), but doing so prevents being able to set custom `postcss-modules` config. The trouble here is that I use a shared postcss-config file, but even if I didn't, the plugins array syntax is more explicit, not depending on js's unsupported object key order.

## 🤔 Expected Behavior

`postcss-modules` config should be detected.

## 😯 Current Behavior

`postcss-modules` config is not detected.

## 💁 Possible Solution

Either parcel should search the array for module names matching `postcss-modules`, or you should be able to use the top-level modules key to a config object (`{modules: {}, plugins: []}`).

**Comment by zanona** [comment]
I think this should be reopened, the array syntax for plugins indeed doesn't work:

```js
module.export = () => ({
    modules: true,
    plugins: [
      require('autoprefixer')(),
      require('postcss-modules')({localsConvention: 'camelCaseOnly'})
    ]
});
```
