### ISSUE TITLE
Parcel doesn't polyfill Node `process` var with babel __DEV__ expression plugin

### ISSUE THREAD

**Issue by atomiks** [parcel-bundler/parcel#3179]
# 🐛 bug report

Parcel does not recognize the `__DEV__` variable (babel plugin) that gets transformed into `process.env.NODE_ENV !== 'production'` and throws an error.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "plugins": ["dev-expression"]
}
```

## 🤔 Expected Behavior

Should polyfill (or replace?) `process.env.NODE_ENV` like it does with static analysis

## 😯 Current Behavior

`index.js:1 Uncaught ReferenceError: process is not defined`

## 💻 Code Sample

```js
// Throws error as above
if (__DEV__) {
  console.log('dev');
}

// This works fine
if (process.env.NODE_ENV !== 'production') {
  console.log('dev');
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.16.0
| npm/Yarn         | 6.8
| Operating System | macOS 10.14.4

**Comment by DeMoorJasper** [comment]
Parcels environment inlining runs before your custom transforms run. I think this is reversed in Parcel 2

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
