### ISSUE TITLE
Images are copied but it doesn't build

### ISSUE THREAD

**Issue by StarpTech** [parcel-bundler/parcel#318]
```
import './style.scss';
import './style2.scss';
import t from './test';
import './images/*' // <-- Is this possible?
```

### 🤔 Expected Behavior
1. All images are moved to `dist` and the app is build **OR**
2. Throw an error because invalid syntax

### 😯 Current Behavior
Only the images in `images` are copied to `dist`. No other files are interpreted.

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  1.2.0
| Node             | 8.9
| npm/Yarn         | npm
| Operating System | Windows 10

**Comment by davidnagli** [comment]
When you say “`images`”, do you mean all the files in the `/images` directory?

**Comment by StarpTech** [comment]
yes

**Comment by ssuman** [comment]
I'm assuming the question is if you could include all the images under images folder including sub-directories ? If true, could you try with two stars to copy images from sub folders as well.
```
import './images/**'
```

**Comment by StarpTech** [comment]
`**` means include subdirs but I'm using `*`
```
import './images/**'
```

**Comment by mischnic** [comment]
Seems to throw an error now:
```js
import './images/*';
```
```
.../images/*: ENOENT: no such file or directory, open '.../images/*'
```
