### ISSUE TITLE
Module (vue-hot-reload-api) not being written to bundle when using mutiple entry files

### ISSUE THREAD

**Issue by fabrizim** [parcel-bundler/parcel#3180]
# 🐛 bug report

When specifying multiple entry files via a glob, the "vue-hot-reload-api" module is missing from one of the bundles.

## 🎛 Configuration (.babelrc, package.json, cli command)

command looks like:

```
parcel -d public resources/assets/*.{js,scss}
```

Inside the `resources/assets` directory there are 2 JS files that include `vue`.

## 🤔 Expected Behavior

Both bundles served during the serve command should have the `vue-hot-reload-api` module written to them.

## 😯 Current Behavior

Only one bundle has the module written. The filenames are `app.js` and `admin.js`, and only `app.js` has the module written. 

## 🔦 Context

I am not able to use vue hot reload when including the file that is missing that module.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | v11.8.0
| npm/Yarn         | 6.9.0
| Operating System | MacOS 10.14.4

**Comment by fabrizim** [comment]
As a follow-up, it looks like this happens with multiple entry files when they are explicitly specified in the command line as well, so the issue is not specific to the glob pattern.

**Comment by mischnic** [comment]
This is likely also the long-standing bug where modules are too aggressively deduplicated across entrypoints, should be fixed with Parcel 2.

**Comment by fabrizim** [comment]
Okay - that makes sense. I have a workaround for this in my project for now, but, out of curiosity, do you know if there a roadmap/timeline for Parcel 2?
