### ISSUE TITLE
Parcel does not find package.json while running as API

### ISSUE THREAD

**Issue by icavalheiro** [parcel-bundler/parcel#3181]
# 🐛 bug report

I'm using parcel API to integrate it inside a gulpfile.js.
When running it withing gulp it does not find any of the plugins I've install, looks like it does not find the package.json.

## 🎛 Configuration (.babelrc, package.json, cli command)

Project struture:
```
interface/
- index.html
- index.js
gulpfile.js
dist/
package.json
node_modules/
```
package json depedencies:
```js
...
 "dependencies": {
    "gulp": "^4.0.2",
    "node-notifier": "^5.4.0",
    "node-sass": "^4.12.0",
    "parcel-bundler": "^1.12.3",
    "parcel-plugin-prerender": "^1.4.1"
},
...
```

Running `parcel build frontend\index.html .\dist\` in terminal works just fine,
but running `gulp build` does not work (it builds, but the plugins are not included in the process).

gulpfile.js
```js
...
function getBaseOptions(isProduction){
    return {
        entryFiles: ['./frontend/index.html'],
        outDir: './dist',
        publicUrl: '/',
        minify: isProduction,
        hmr: false,
        watch: !isProduction
    }
}
...
function getBundler(config){
    var bundler = new parcel(config.entryFiles, config);
    bundler.on('buildError', error => {
        notifyError(error);
    });

    if(config.watch){
        bundler.on('buildStart', () => {
            console.log('\x1b[2J');
            console.log('\x1b[0f');
            console.log('Building...');
        });
    }

    return bundler;
}
...
async function build(cb){
    var config = getBaseOptions(true);
    cleanDistFolder(config);

    var bundler = getBundler(config);
    await bundler.bundle();
    cb();
}
...
```

## 🤔 Expected Behavior

When running as a API, Parcel should find package.json and include all the installed plugins in the process.

## 😯 Current Behavior

When running as a API, Parcel does not include the installed plugins in the build process.

## 💁 Possible Solution

If Parcel is not able to find plugins or the package.json when running as a API, please supply us a way to include it as a parameter or something like that.

## 🔦 Context

I'm trying to prerender some routes for my Vue application, but I cannot use the prerender plugin in my current gulp setup.

## 💻 Code Sample

The base gulpfile I've used for this can be found here:
https://gist.github.com/icavalheiro/5a5ae22f1c856a9c3400fc25659ae52a

I've used it in many project but since now I never had to use a plugin, so that's why I only realized the problem now.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12 |
| Node             | 10.15 |
| npm/Yarn         | 6.4.1 |
| Operating System | Windows 10 |
| Gulp | 4.0.2 |

**Comment by icavalheiro** [comment]
As a workaround I found out that we can import the plugin and then initalize it ourselves with the instance of the bundler that we created:

```js
const plugin = require('parcel-plugin-prerender');
...
var bundler = parcel(config.entryFiles, config);
plugin(bundler);
...
```

**Comment by mischnic** [comment]
I ran your gulp file with `parcel-plugin-bundle-visualiser` and that plugin did run.
Please create a repo with an complete example.
