### ISSUE TITLE
HMR doesn't work with Vue SFC

### ISSUE THREAD

**Issue by ocavue** [parcel-bundler/parcel#3182]
# 🐛 bug report

When editing a Vue SFC (Single File Components), HMR doesn't work.

## 🎛 Configuration (.babelrc, package.json, cli command)

See the repo link below for details.

## 🤔 Expected Behavior

HMR works.

## 😯 Current Behavior

Having these error in my browser console.
```
index.js:121 TypeError: Cannot read property 'extend' of undefined
    at index.js:228
    at Object.reload (index.js:119)
    at eval (eval at hmrApply (hmr-runtime.js:153), <anonymous>:64:17)
    at Object.eval (eval at hmrApply (hmr-runtime.js:153), <anonymous>:70:7)
    at newRequire (parcel_issue_vue_hmr.e31bb0bc.js:47)
    at hmrAcceptRun (hmr-runtime.js:203)
    at hmr-runtime.js:60
    at Array.forEach (<anonymous>)
    at WebSocket.ws.onmessage (hmr-runtime.js:59)
(anonymous) @ index.js:121
(anonymous) @ VM255:64
(anonymous) @ VM255:70
newRequire @ parcel_issue_vue_hmr.e31bb0bc.js:47
hmrAcceptRun @ hmr-runtime.js:203
(anonymous) @ hmr-runtime.js:60
ws.onmessage @ hmr-runtime.js:59

index.js:122 Something went wrong during Vue component hot-reload. Full reload required.
```

## 💻 Code Sample

https://github.com/ocavue/parcel_issue_3182

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.3|
| Node             |12.4.0|
| npm/Yarn         |yarn 1.16.0|
| Operating System |macOS 10.13.6|

**Comment by DeMoorJasper** [comment]
In theory it should work, pretty strange that this error only comes up now after almost a year of supporting vue without much changes

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ocavue** [comment]
I noticed that the version of `@vue/component-compiler-utils` is 3.0.0. Maybe it contains some breaking change and causes this issue.

**Comment by ocavue** [comment]
I try some old dependencies version (about 6 months ago) and still get the same error. Maybe this issue has been existing for a long time.

```json
  {
    "@vue/component-compiler-utils": "2.4.0",
    "parcel-bundler": "1.10.x",
    "vue-template-compiler": "2.5.22",
    "vue": "2.5.x",
    "vue-hot-reload-api": "2.3.x"
  }
```

**Comment by ocavue** [comment]
I found the way in this comment https://github.com/vuejs/vue-hot-reload-api/issues/61#issuecomment-433654600 can avoid the error.

**Comment by s0oft** [comment]
@ocavue doesn't work for me 🤷🏼‍♂️

**Comment by juniorgarcia** [comment]
Parcel site actually guides you how to mount your app [here](https://parceljs.org/vue.html), **with** the render property.

For the curious:

Vue site explains [here](https://vuejs.org/v2/guide/render-function.html#The-Virtual-DOM) about the Virtual Dom, and finally a great article about the "mysterious" `h` function [here](https://css-tricks.com/what-does-the-h-stand-for-in-vues-render-method/).
