### ISSUE TITLE
Cannot find module 'buffer'

### ISSUE THREAD

**Issue by AlexanderHorbunov** [parcel-bundler/parcel#3184]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by darioielardi** [comment]
May I ask you how did you solve this? I'm facing the same issue.
