### ISSUE TITLE
Build errors with material ui

### ISSUE THREAD

**Issue by ghost** [parcel-bundler/parcel#3185]
Keep getting this error in bundled app:
`Uncaught TypeError: Cannot read property 'A200' of undefined`

A200 is a key in "pink" object
For some reason `import pink from '../colors/pink';` returns undefined in createPalette.js, even though there are multiple similar imports in file

CLI comand:
`parcel build ./src/index.html --public-url .`

.babelrc
```javascript
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": [
          "Chrome >= 59",
          "FireFox >= 44",
          "Safari >= 7",
          "Explorer 11",
          "last 4 Edge versions"
        ]
      },
      "useBuiltIns": true
    }],
    "@babel/preset-env", 
    "@babel/preset-react", 
    "@babel/preset-flow"
  ],
  "ignore": [
    "node_modules"
  ],
  "plugins": [
    ["babel-plugin-styled-components", {
      "displayName": true
    }],
    "@babel/plugin-proposal-optional-chaining",
    "@babel/plugin-proposal-class-properties",
    "babel-plugin-react-flow-props-to-prop-types",
    ["babel-plugin-transform-inline-environment-variables", {
      "include": [
        "NODE_ENV"
      ]
    }]
  ]
}
```

I am not sure I didn't messed up something, not submitting a bug yet

**Comment by kitfit-dave** [comment]
Have you had any luck with this? I am switching a project over from webpack to parcel and have got the same issue. A 'parcel serve' works okay, but 'parcel build' does not produce a working bundle. I am thinking it has something to do with the material-ui module resolution...

I'm not 100% on how the bundling works, but I think that anything that gets required gets bundled into the source, the require that you see is a key into a map of functions now in the bundle. If I look in my bundle, the string that "../colours/pink" is getting mapped to is "orz+" but there are two functions mapped to that... one is the contents of pink from material ui, the other one seems to be some es5 array shim required as './implementation'... though all that may be a red herring if my guess as to how it works is way off...

**Comment by AlexanderHorbunov** [comment]
No, no luck. I switched back to webpack as it is more popular, so that new people on project are less confused about build.

**Comment by turboki** [comment]
Im running into the same issue as well. `pink.A200` is throwing because `pink` is undefined.
