### ISSUE TITLE
How can a rust file handled by parcel rust support import dependencies (probably from crates.io) ?

### ISSUE THREAD

**Issue by yw662** [parcel-bundler/parcel#3186]
# ❔ Question

If the rust code, which is handled by parcel's rust support, has dependencies, how can it import them ?

This can be done by compile it to wasm, and let parcel handle the wasm. Actually I am currently building it this way. But can this be done directly through parcel's rust support?

## 🔦 Context

Many rust projects have dependencies .:-) Just trying to use one of those.

## 💻 Code Sample

```rust
extern crate rand; // which is https://crates.io/crates/rand
use rand::prelude::*;

[#no_mangle]
pub fn foo() -> boolean {
    rand::random()
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.16.0
| npm/Yarn         | npm
| Operating System | linux 5.1.15

**Comment by mbrobbel** [comment]
You can import from a `Cargo.toml`:

```js
import { foo } from "your-crate/Cargo.toml"
```
`your-crate/Cargo.toml`
```toml
[package]
...

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.7"
wasm-bindgen = "0.2"
```
`your-crate/src/lib.rs`
```rust
use rand::prelude::*;
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn foo() -> boolean {
    rand::random()
}
```

**Comment by yw662** [comment]
Thanks for the answer.
I think this behavior should be documented somewhere in https://parceljs.org/rust.html.

**Comment by yw662** [comment]
@mbrobbel 
Your solution is wrong.

accroding to 
https://github.com/parcel-bundler/parcel/blob/a1567e157b184a5014b60ff0f7124ba0b3f059aa/packages/core/parcel-bundler/src/assets/RustAsset.js#L14

The right way to import the project is by importing `src/lib.rs`.

```js
import { foo } from "your-crate/src/lib.rs"
```
