### ISSUE TITLE
How to package the generated js into a folder,Pack the generated CSS into another folder

### ISSUE THREAD

**Issue by tanghui28** [parcel-bundler/parcel#3187]
![168f09a66dae8c60](https://user-images.githubusercontent.com/35495310/60644671-66811100-9e69-11e9-81e9-24992c4d88f4.png)

# ❔ Question

## 🔦 Context

i want to build js file to dist /js folder , build the images to dist/img folder !  Now that looks bad.
  What should i do ?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.3
| Node             |8.11.3
| npm/Yarn         |4.6.1
| Operating System | windows 10

**Comment by DeMoorJasper** [comment]
Please fill in the issue description

**Comment by tanghui28** [comment]
i want build js file to  dist /js  folder , build the images to dist/img folder

**Comment by tanghui28** [comment]
> Please fill in the issue description

i want to  build js file to dist /js folder , build the images to dist/img folder
