### ISSUE TITLE
Important issues which make parcel unusable.

### ISSUE THREAD

**Issue by StarpTech** [parcel-bundler/parcel#319]
Hi, I would like to open this issue to discuss really important issues which block me to use parcel as a real alternative to brunch or webpack. This issue should serve as a roadmap.

- Import of SASS files from `node_modules`: https://github.com/parcel-bundler/parcel/issues/291, https://github.com/parcel-bundler/parcel/issues/39
- Conflict strategy of .babelrc files in node_modules https://github.com/parcel-bundler/parcel/issues/13
- Url() without quotes is not supported https://github.com/parcel-bundler/parcel/issues/316
- How to work with static assets without to reference them all manually? https://github.com/parcel-bundler/parcel/issues/317

We could split the work here.

**Comment by DeMoorJasper** [comment]
Feel free to fix some of them, most of them are pretty easy to fix

**Comment by DeMoorJasper** [comment]
These are personal preferences and will get fixed eventually, no need to spam them

**Comment by StarpTech** [comment]
This isn't personal. I referenced three other issues. I don't understand why close this issue. This should just serve as a global ..personal...roadmap it doesn't matter.
