### ISSUE TITLE
Minification for standalone svg images.

### ISSUE THREAD

**Issue by yw662** [parcel-bundler/parcel#3190]
# 🙋 feature request

Inline svgs are minified by `htmlnano` and `svgo` in production build. However standalone svgs are not getting minified.

## 🤔 Expected Behavior

Standalone svgs should be minified.

## 😯 Current Behavior

Standalone svgs are copied to production build as is.

## 💁 Possible Solution

Handle standalone svgs with `svgo`, which is already used by `htmlnano` to handle inline svg.

## 💻 Examples

```html
<!-- index.html-->
<!DOCTYPE html>
<html>
...
<div style="background-image: url(path/to/standalone.svg);"></div>
...
</html>
```
```xml
<!-- standalone.svg -->
<?xml version="1.0" standalone="no"?>

<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" 
"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg">
...
</svg>
```

The svg file above should be minified.

**Comment by mischnic** [comment]
With Parcel 2, you can enable this with this `.parcelrc`:
```json
{
	"extends": "@parcel/config-default",
	"transformers": {
		"*.svg": ["@parcel/transformer-svgo"],
	}
}
