### ISSUE TITLE
Add option to disable babel (or preset-env) if not necessary

### ISSUE THREAD

**Issue by fregante** [parcel-bundler/parcel#3191]
# 🙋 Feature request

Most of the time lately I don't need babel, I just ship ES6 code (or let TypeScript do it)

**Instead of requiring config in a separate file** (be it `browserlist` or `package.json`) it'd be great to just disable the transpilation. This would let me use `parcel` from the command line without having to create a project _and config_

```sh
parcel build index.js --no-babel-preset-env
```

I think babel is currently used for more than `preset-env` so it wouldn't make sense to add a `--no-babel` flag.

## 🤔 Expected Behavior

`@babel/preset-env` is not added to babel's config when the `--no-babel-preset-env` flag is added.

## 😯 Current Behavior

https://github.com/parcel-bundler/parcel/blob/060db2e2c56f08e223e9a9075035f0998e249763/packages/core/parcel-bundler/src/transforms/babel/env.js#L51-L59

**Comment by fregante** [comment]
I don't think if this is already addressed by Parcel 2, but it's still relevant

**Comment by devongovett** [comment]
By default, Parcel 2 does not do any transpilation. Transpilation is opt-in via `browserslist`.

**Comment by fregante** [comment]
OMG what an unexpected change 😃 
Great to hear!
