### ISSUE TITLE
Cannot use built dist/index.js in other packages

### ISSUE THREAD

**Issue by rfestag** [parcel-bundler/parcel#3194]
# 🐛 bug report

I'm trying to use Parcel to build an NPM package I can use in other projects. In this case, it is the react component I'm building for use can be found here: https://github.com/rfestag/react-dir
I'm trying to test before publishing. I tried using npm-link, and I've also tried directly installing. In all cases, I get the following error in my project that depends on it:

```
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
```
I followed the link, but couldn't find a resolution based on what I was seeing. I notice that npm-link could lead to the issue. I have confirmed that the same version of React (16.8.1) is installed in both my library and in my sample project, and that it is listed as a peer dependency in the library (it is worth noting that it is also a dev depenency, but from what I've read that's supposed to be the case). Lastly, as far as I can tell, I'm using hooks in the correct locations. So I'm wondering if something wonky is happening in the build process that is making my dist/index.js invalid for whatever reason.

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```js
{
  "name": "react-exemplify",
  "version": "0.0.1",
  "description": "A React component to allow live editing of JS examples (not just react components)",
  "main": "dist/index.js",
  "author": "Ryan Festag (rfestag@gmail.com)",
  "license": "ISC",
  "scripts": {
    "build": "parcel build src/index.js --out-dir dist",
    "doc": "jsdoc -c jsdoc.json",
    "precommit": "lint-staged",
    "release": "standard-version",
    "start": "parcel src/index.html",
    "test": "jest --coverage"
  },
  "lint-staged": {
    "*.{js,jsx}": [
      "eslint --fix",
      "prettier --write",
      "npm run build",
      "jest --bail --coverage --findRelatedTests",
      "git add"
    ]
  },
  "jest": {
    "collectCoverage": true,
    "testPathIgnorePatterns": [
      "/dist"
    ],
    "coveragePathIgnorePatterns": [
      "/src/index.js",
      "/src/enzyme.js"
    ],
    "collectCoverageFrom": [
      "src/**/*.js",
      "src/**/*.jsx"
    ],
    "coverageReporters": [
      "json",
      "html"
    ]
  },
  "keywords": [
    "react"
  ],
  "dependencies": {
    "buble": "^0.19.8",
    "codemirror": "^5.48.0",
    "prop-types": "^15.7.2",
    "react-codemirror2": "^6.0.0",
    "react-dir": "file:../react-dir",
    "react-live": "^2.1.2"
  },
  "devDependencies": {
    "@babel/core": "7.4.0",
    "@babel/preset-env": "^7.4.2",
    "@babel/preset-react": "^7.0.0",
    "babel-plugin-rewire": "^1.2.0",
    "cross-env": "^5.2.0",
    "docdash": "^1.1.1",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
    "eslint": "^5.16.0",
    "eslint-config-prettier": "^5.0.0",
    "eslint-plugin-jest": "^22.7.1",
    "eslint-plugin-jsdoc": "^8.4.5",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-react": "^7.13.0",
    "husky": "^2.4.1",
    "jest": "^24.8.0",
    "jest-cli": "^24.8.0",
    "jsdoc": "^3.6.2",
    "jsdoc-mermaid": "^1.0.0",
    "lint-staged": "^8.2.1",
    "parcel-bundler": "^1.12.3",
    "prettier": "^1.18.2",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-test-renderer": "^16.8.6",
    "standard-version": "^6.0.1"
  },
  "peerDependencies": {
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  }
}
```

.babelrc
```js
{
  "presets": ["@babel/env", "@babel/react"],
  "env": {
    "test": {
      "plugins": [
        "rewire"
      ]
    }
  }
}
```

## 🤔 Expected Behavior

I would expect the following minimal example to load properly after installing react-dir and display the value
```
import React from "react";
import ReactDOM from "react-dom";
import Dir from "react-dir";
ReactDOM.render(
  <Dir value={{ a: 1, b: 2 }} />,
  document.getElementById("root")
);
```

## 😯 Current Behavior
I get the following error:
```
The above error occurred in the <c> component:
    in c

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. react-dom.development.js:17117:12
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
react.production.min.js:11:315
    React 4
        v
        m
        T
        useContext
    c Dir.jsx:87
    React 23
    parcelRequire<["index.js"]< index.js:144
    newRequire src.e31bb0bc.js:47
    parcelRequire src.e31bb0bc.js:81
    <anonymous> src.e31bb0bc.js:120
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. react.production.min.js:11:315
    React 4
    c Dir.jsx:87
    React 19
    parcelRequire<["index.js"]< index.js:144
    newRequire src.e31bb0bc.js:47
    parcelRequire src.e31bb0bc.js:81
    <anonymous> src.e31bb0bc.js:120 
```

## 💁 Possible Solution

Honestly, I have no idea. This is my first attempt to create a package using Parcel, so I may well be doing something dumb in there. 

## 🔦 Context
I'm not sure I'm able to publish a package built in Parcel. From some other issues, it seemed like it should be supported, but maybe that's not true?

## 💻 Code Sample

An example project that I would expect to work can be found here: 
https://github.com/rfestag/react-exemplify

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3 |
| Node             | 10.4.1|
| npm/Yarn         |npm 6.1.0|
| Operating System |Manjaro|

**Comment by rfestag** [comment]
Update:

So, I think that this is related to #144. As far as I can tell, the issue I'm having is that React is actually getting included in my built library, which is triggering the error when I pull it into another project. As far as I can tell, there is no way to configure externals in Parcel. I understand that Parcel appears to be targeted towards packaging web applications, but it seems like supporting externals is a desired feature. It would be great if Parcel could key off of the listed peerDependencies and provide reasonable defaults for externals (while still allowing users to specify them if needed). Are there any plans to add support for configuring external libraries?

For now, I am working around by also installing webpack, and using that during the production build phase (keeping Parcel to run my local dev server for testing the component).

**Comment by DeMoorJasper** [comment]
@rfestag externals are currently not supported but should be added to parcel 2 at some point

**Comment by rfestag** [comment]
@DeMoorJasper - Thanks, at least that confirms what I thought. Do you guys have a rough idea of at timeline for when you think it will be tackled? If it isn't a high priority, has anyone outlined a preferred solution so somebody could submit a PR for it?

**Comment by mischnic** [comment]
> If it isn't a high priority, has anyone outlined a preferred solution so somebody could submit a PR for it?

There is some discussion in the issue you've linked.
