### ISSUE TITLE
Custom HTML template

### ISSUE THREAD

**Issue by falakjs** [parcel-bundler/parcel#3197]
# ❔ Question
How to manipulate html files?

## 🔦 Context

I would like to create a custom HTML template engine to use custom tags to integrate components beside normal HTML tags.

## 💻 Code Sample

`index.html` >> entry point

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Hello, World</title>
    <link rel="stylesheet" href="app.scss">
</head>
<body>
    <my-app></my-app>
    <script src="app.ts"></script>
</body>
</html>
```

`my-app.component.html` 

```html
<another-component></another-component>
```

I need a way to catch up the `my-app` tag and start parse it to the corresponding component `which i'll do with my own`  but i just want to know how to control html files?

Thanks.
 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3 |
| Node             | 10.13.0 |
| npm/Yarn         | npm |
| Operating System | Windows 10|

**Comment by mischnic** [comment]
You might want to look into creating a PostHTML plugin to do this
