### ISSUE TITLE
The loaded JS file is too large and the loading time reaches 9.30s.

### ISSUE THREAD

**Issue by cowDungIsFlowers** [parcel-bundler/parcel#3199]
![O$_4A6UF1B}L747YFHN_O)D](https://user-images.githubusercontent.com/23652526/60794536-90557300-a19c-11e9-9ad4-a9c95a718b89.png)

**Comment by DeMoorJasper** [comment]
you could try and enable treeshaking, but without any context. You won't get any decent help.

**Comment by cowDungIsFlowers** [comment]
I put all the files I want to import into index. js. Now I import all the files through cdn. The packaged JS files are hundreds of kb.
