### ISSUE TITLE
 Unknown version 4 of samsung

### ISSUE THREAD

**Issue by robGetsTheJobDone** [parcel-bundler/parcel#3201]
# 🐛 bug report

Inside of a docker
Running lerna run prepare aka  `yarn parcel build src/index.html --out-dir build && rm -r -f ./build/_redirects && cp ./_redirects ./build/`

Results in /h1/packages/app/h1-app/src/index.html:undefined:undefined: Unknown version 4 of samsung

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
{
  "name": "@h1eng/app",
  "version": "0.0.1",
  "scripts": {
    "clean:hard": "rimraf ./node_modules && rimraf ./dist && rimraf ./build && rimraf .cache",
    "lint:app": "tslint src/**/*.tsx -c tslint.json",
    "lint:server": "tslint server/**/*.ts -c tslint.json",
    "lint": "tslint **/src/**/*.ts{,x} -c tslint.json",
    "lint:fix": "tslint **/src/**/*.ts{,x} -c tslint.json --fix",
    "prepare": "parcel build src/index.html --out-dir build && rm -r -f ./build/_redirects && cp ./_redirects ./build/",
    "prepare:og": "parcel build src/index.html --out-dir build --no-minify",
    "prepare:watch": "parcel watch src/index.html --out-dir build",
    "build": "yarn prepare:app && yarn prepare:server",
    "start": "node start.js",
    "start:watch": "yarn start",
    "test:app": "jest --config=jest.puppeteer.config.js",
    "test:components": "jest",
    "precommit": "lint-staged",
    "build:tslint-rules": "tsc tslint/rules/*.ts",
    "clean:tslint-rules": "rimraf ./tslint/rules/*.js"
  },
  "dependencies": {
    "@h1eng/format-util": "0.0.1",
    "@h1eng/interfaces": "0.0.1",
    "@h1eng/pagination": "0.0.1",
    "@h1eng/search-util": "0.0.1",
    "@h1eng/ui-components": "0.0.1",
    "@material-ui/core": "^3.9.2",
    "@material-ui/icons": "^3.0.2",
    "@material-ui/lab": "^3.0.0-alpha.30",
    "@okta/okta-react": "^1.0.3",
    "@okta/okta-signin-widget": "^2.11.0",
    "@types/recharts": "^1.1.6",
    "axios": "^0.18.0",
    "classnames": "^2.2.6",
    "downshift": "^3.2.7",
    "fuse.js": "^3.4.4",
    "jsonwebtoken": "^8.3.0",
    "konva": "^2.1.8",
    "loadash": "^1.0.0",
    "lodash": "^4.17.5",
    "nodemon": "^1.18.9",
    "numeral": "^2.0.6",
    "prop-types": "^15.6.1",
    "query-string": "^6.0.0",
    "react": "^16.8.3",
    "react-container-dimensions": "^1.3.4",
    "react-dom": "^16.8.3",
    "react-easy-chart": "^1.0.0",
    "react-heap": "^0.1.3",
    "react-intercom": "^1.0.14",
    "react-konva": "^1.7.12",
    "react-redux": "^5.0.7",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-router-hash-link": "^1.2.0",
    "react-select": "^1.2.0",
    "recharts": "^1.4.2",
    "redux": ">3.0.0",
    "redux-freeze": "^0.1.5",
    "redux-observable": "^1.0.0",
    "redux-persist": "^5.10.0",
    "reselect": "^3.0.1",
    "rxjs": "^6.2.2",
    "styled-components": "^3.3.3",
    "typesafe-actions": "^2.0.4",
    "uniqid": "^5.0.3"
  },
  "devDependencies": {
    "@types/classnames": "^2.2.7",
    "@types/enzyme": "^3.1.15",
    "@types/expect-puppeteer": "^3.3.0",
    "@types/faker": "^4.1.2",
    "@types/jest-environment-puppeteer": "^2.2.1",
    "@types/jsonwebtoken": "^7.2.8",
    "@types/numeral": "^0.0.25",
    "@types/puppeteer": "^1.6.4",
    "@types/react-redux": "^6.0.6",
    "@types/react-router-dom": "^4.3.1",
    "@types/redux-persist": "^4.3.1",
    "@types/uniqid": "^4.1.3",
    "enzyme": "^3.8.0",
    "enzyme-adapter-react-16": "^1.7.1",
    "jest": "^23.5.0",
    "jest-canvas-mock": "^1.1.0",
    "jest-puppeteer": "^3.3.1",
    "parcel-bundler": "^1.9.7",
    "puppeteer": "^1.8.0",
    "superstatic": "^6.0.1",
    "tslint-react": "^3.6.0",
    "typescript": "^3.0.3"
  },
  "lint-staged": {
    "src/**/*.ts": [
      "tslint -c tslint.json --fix",
      "prettier --write",
      "git add"
    ]
  }
}

```js
{
  "your": { "config": "here" }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.9.7
| Node             | 8.11.3
| npm/Yarn         | yarn
| Operating System | ubuntu linux

**Comment by robGetsTheJobDone** [comment]
This command was working until today no problem. Only happens in a docker context.

**Comment by dandv** [comment]
I'm getting the same weirdo error with Gatsby :confused:
