### ISSUE TITLE
"High-severity" security alert on Parcel dependency

### ISSUE THREAD

**Issue by mbohgard** [parcel-bundler/parcel#3203]
Github is giving me an "high severity" security alert for js-yaml@3.13.0 which parcel-bundler indirectly is depending on (via cssnano@4.1.10 and htmlnano@0.2.3). Is there something I/you can/should do to remedy this?

**Comment by DeMoorJasper** [comment]
It's probably not really an issue. You could however do this https://yarnpkg.com/lang/en/docs/selective-version-resolutions/
