### ISSUE TITLE
Can't find stylesheet to import

### ISSUE THREAD

**Issue by FDiskas** [parcel-bundler/parcel#3205]
# 🐛 bug report

Can't import any node_module to scss file.
Tried like:
```scss
@import 'bourbon';
@import '~/bourbon/core/_bourbon.scss';
@import '~/node_modules/bourbon/core/_bourbon.scss';
```

## 🎛 Configuration (.babelrc, package.json, cli command)

No configs was used

## 🤔 Expected Behavior

Guess what...

## 😯 Current Behavior

```
🚨  /src/layouts/main/MainLayout.scss:2:9: Can't find stylesheet to import.
  ╷
2 │ @import '~/node_modules/bourbon/core/_bourbon.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/layouts/main/MainLayout.scss 2:9  root stylesheet
```

## 💁 Possible Solution

Works only if I enter path like
```scss
@import '~node_modules/bourbon/core/bourbon';
/* or this */
@import '~bourbon/core/_bourbon.scss';
```
> **NOTE** no `/` after `~`
But in [documentation](https://parceljs.org/module_resolution.html#~-tilde-paths) its not mentioned

## 💻 Code Sample

https://github.com/FDiskas/parcel-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | v10.16.0
| npm/Yarn         | 6.9.0/1.16.0
| Operating System | Fedora (LINUX)

**Comment by FDiskas** [comment]
Could this be sovled by using https://github.com/postcss/postcss-import ?

**Comment by FDiskas** [comment]
Any news?

**Comment by FDiskas** [comment]
Any news - workarounds?

**Comment by DeMoorJasper** [comment]
`@import '~node_modules/bourbon/core/bourbon';` that should be `@import '~bourbon/core/bourbon';` seems like a bug if you have to prefix it with `node_modules`, also in that case it should be `~/node_modules` which apparently does not work, it's a bug but you already found the workaround so not sure why you keep asking for a workaround?

**Comment by FDiskas** [comment]
I'm sorry I totally forgot about workaround. But still it's not works as it's supposed to

**Comment by DeMoorJasper** [comment]
@FDiskas I doubt we'll fix this in Parcel 1, we've been tweaking and changing this quite a lot and changing this again would be a breaking change.

Parcel 2 will hopefully be more reliable for this, we're still trying to figure out how we should handle this properly due to the various different standards for these imports. Even with webpack and postcss import you can define your own prefix. Maybe we should just default to the node.js standard and allow this to be customized using postcss plugins.

**Comment by FDiskas** [comment]
So probably this issue should be closed
