### ISSUE TITLE
Flow detection is brittle

### ISSUE THREAD

**Issue by wbinnssmith** [parcel-bundler/parcel#3212]
To infer whether or not to use the Flow babel transform, we:

* only read the first 20 characters of an asset's text, which might include a lengthy leading docblock (such as a lengthy license header with license text)
* only look for `// @flow`, ignoring other comment styles (`/* @flow`)

These can break. Note we want to avoid a full parse since this is intended to be an inexpensive check, and it can't be perfect, but we should probably expand this to cover these cases.

**Comment by rdimartino** [comment]
Hello! I'm interested in helping out with this.

I think I see what you're talking about here: https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/transforms/babel/flow.js#L5 but if I understand correctly, that's from v1. Is that still worth updating?

I'm also not sure where to find if the same brittle detection is affecting v2.

**Comment by mischnic** [comment]
The Parcel 2 version of that is here: https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/babel/src/flow.js

Apparently we just always run the Babel flow plugin currently...

**Comment by rdimartino** [comment]
Ah thanks. I can submit the patch I had in mind for more robust detecting of the `@flow` tag there if that's desired. But I'm not really sure how to benchmark if/how much of any improvement that would be over always running the flow plugin.

**Comment by mischnic** [comment]
We now check if flow-bin is a dependency of the project root's package.json.
