### ISSUE TITLE
Any intention to npm publish v2.0.0-alpha.0?

### ISSUE THREAD

**Issue by dkadrios** [parcel-bundler/parcel#3214]
I tried installing the specific tag/branch/commit but yarn fails due to there being no version specified in package.json

There is currently a dist-tag published for an old beta of 1.10, it'd sure be nice to have one published for the alpha of v2 as well.

```dist-tags:
beta: 1.10.0-beta.1  latest: 1.12.3```

**Comment by mischnic** [comment]
The alpha will be published when it's ready.

**Comment by dkadrios** [comment]
You might want to remove this release then.  It causes nothing but confusion.
https://github.com/parcel-bundler/parcel/releases/tag/v2.0.0-alpha.0
