### ISSUE TITLE
Parcel removes @babel/preset-env configuration

### ISSUE THREAD

**Issue by wojtekmaj** [parcel-bundler/parcel#3216]
# 🐛 bug report

I noticed that despite configuring my .babelrc like so:

```
    ["@babel/preset-env", {
      "modules": false,
      "useBuiltIns": "usage",
      "corejs": 3
    }],
``` 

`Object.entries` does not have the polyfill added on usage. 

## 🎛 Configuration (.babelrc, package.json, cli command)

`.babelrc`

```js
{
  "presets": [
    ["@babel/preset-env", {
      "modules": false,
      "useBuiltIns": "usage",
      "corejs": 3
    }],
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-proposal-export-default-from"
  ],
  "env": {
    "test": {
      "presets": [
        ["@babel/preset-env", {
          "targets": {
            "node": "current"
          }
        }]
      ],
      "plugins": [
        "babel-plugin-styled-components"
      ]
    }
  }
}
```

## 🤔 Expected Behavior

`useBulitIns` and `corejs` options are not ignored.

## 😯 Current Behavior

`useBulitIns` and `corejs` options are ignored.

I investigated a lot in parcel-bundler source code and here's what I found.

In `config.js`, in getBabelConfig, I added a log:

```
  let envConfig = await getEnvConfig(asset, isSource);
  let jsxConfig = await getJSXConfig(asset, isSource);
  let flowConfig = getFlowConfig(asset, isSource);

  console.log('config.js - 1');
  console.log(babelrc.config.presets);
```

which resulted in console output:

```
config.js - 1
[
  [
    '@babel/preset-env',
    { modules: false, useBuiltIns: 'usage', corejs: 3 }
  ],
  '@babel/preset-react'
]
```

So far so good. At the end of getBabelConfig I added log again:

```
  console.log('config.js - 2');
  console.log(result[7].config.presets);

  return result;
```

and to my surprise, my preset was gone:

```
config.js - 2
[ '@babel/preset-react' ]
```

## 💁 Possible Solution

Commenting out these lines from config.js:

```
    if (Array.isArray(babelrc.config.presets)) {
      babelrc.config.presets = babelrc.config.presets.filter(preset => {
        return !ENV_PRESETS[getPluginName(preset)];
      });
    }
```

resulted in Babel receiving proper configuration & adding core-js polyfills to my file as desired.

If I understand source code correctly, these lines are there because we expect `getEnvConfig` to load `@babel/preset-env` in some special way. So my best guess is that `getEnvConfig` does something incorrectly, resulting in `@babel/preset-env` ignored.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | latest
| Node             | 12.4.0
| npm/Yarn         | Yarn 1.16.0
| Operating System | macOS Catalina

**Comment by wojtekmaj** [comment]
Oddly enough, repeating configuration in `.babelrc` in `env.development` does not strip presets out, and all my configuration is properly added.

**Comment by r0skar** [comment]
To add: the same bug exists when configuring babel in `package.json`.

**Comment by Taaqif** [comment]
Noticing this issue as well. The workaround to use `env.development` seems hacky given we need to repeat the same configuration for both production and development.

Is there a better way of handling this while a fix is being developed?

**Comment by jak-hammond** [comment]
I am trying to get the presets and corejs to work on this as well, has any progress been made or do I still need to use the hack of development and production?

**Comment by arminrosu** [comment]
After a few hours going down the rabbit hole and not finding a solution, here are my findings, maybe someone else finds them useful.

[getBabelConfig](https://github.com/parcel-bundler/parcel/blob/c9c5805866aa23d2a4e1809516d04c4296c0c17c/src/transforms/babel/config.js#L20) will get the `.babelrc` and then try to apply it's own `@babel/preset-env`. This is done via [getEnvConfig](https://github.com/parcel-bundler/parcel/blob/c9c5805866aa23d2a4e1809516d04c4296c0c17c/src/transforms/babel/env.js#L9) which looks for your browserlist configuration, via [getTargetedEngines](https://github.com/parcel-bundler/parcel/blob/c9c5805866aa23d2a4e1809516d04c4296c0c17c/src/utils/getTargetEngines.js#L17) and returns the default [@babel/preset-env](https://github.com/parcel-bundler/parcel/blob/c9c5805866aa23d2a4e1809516d04c4296c0c17c/src/transforms/babel/env.js#L51) "plugins" for said list. In this process it sets [useBuiltins: 'entry'](https://github.com/parcel-bundler/parcel/blob/c9c5805866aa23d2a4e1809516d04c4296c0c17c/src/transforms/babel/env.js#L56).

Then [removes all your env settings](https://github.com/parcel-bundler/parcel/blob/c9c5805866aa23d2a4e1809516d04c4296c0c17c/src/transforms/babel/config.js#L36-L50) if it finds browserlist targets.

The discongruity of running parcel with `NODE_ENV=development` or not, seems to stem from the browserlist handling - in dev mode, it [uses the defaults](https://github.com/parcel-bundler/parcel/blob/c9c5805866aa23d2a4e1809516d04c4296c0c17c/src/utils/getTargetEngines.js#L79). I assume, but may be very wrong, that this affects the later preset & plugin filtering and somehow the results are closer to what you'd expect.

The code is a bit convoluted to me. I wished parcel would stop it's "magic" if it detects a `.babelrc` configuration and just use that with no extra parsing.

HTH

**Comment by mischnic** [comment]
> I wished parcel would stop it's "magic" if it detects a .babelrc configuration and just use that with no extra parsing.

And now you know why we do exactly that in Parcel 2 😄

**Comment by arminrosu** [comment]
> And now you know why we do exactly that in Parcel 2 😄

@mischnic awesome. I already know I can do more things with `terser` in `parcel@2`. Do you think it's safe to switch over? I'm not expecting 100% mature software in _beta1_, just "good enough to get stuff done".

**Comment by ranisalt** [comment]
> And now you know why we do exactly that in Parcel 2 smile

Not so simple. I'm trying to use

```
{
	"presets": [["@parcel/babel-preset-env", { "runtime": "automatic" }]],
	"plugins": ["@parcel/babel-plugin-transform-runtime"]
}
```

But it seems to ignore the `{ "runtime": "automatic" }` part. Worse yet, I added `throw new Error()` to the top of the only file in `@parcel/babel-preset-env` and it just does not throw and that file is never used

![image](https://user-images.githubusercontent.com/1993083/106310735-ec3e8b80-625b-11eb-86e6-5f584dfeb7c0.png)

**Comment by mischnic** [comment]
@ranisalt I think you actually want to pass `runtime` to `preset-react` though?

**Comment by ranisalt** [comment]
@mischnic I tried every combination I could think of. Right now I'm trying this:

```
{
        "presets": ["@parcel/babel-preset-env", ["@babel/preset-react", { "runtime": "automatic" }]],
        "plugins": [
                "@parcel/babel-plugin-transform-runtime",
                ["@babel/plugin-transform-react-jsx", {
                        "runtime": "automatic"
                }],
                "@babel/plugin-transform-typescript"]
}
```
But it does not work still.

**Comment by mischnic** [comment]
This works correctly for me:

package.json
```json
{
  "dependencies": {
    "@babel/core": "^7.12.10",
    "@babel/preset-react": "^7.12.10",
    "@parcel/babel-preset-env": "^2.0.0-nightly.556",
    "parcel": "^2.0.0-nightly.554",
    "react": "^17.0.1"
  }
}
```
.babelrc:
```json
{
	"presets": [
		"@parcel/babel-preset-env",
		["@babel/preset-react", { "runtime": "automatic" }]
	]
}
```
index.js:
```js
function App() {
	return <div>1</div>;
}

console.log(App);
```

---

The default config is generated here: https://github.com/parcel-bundler/parcel/blob/40f24178138445abe8746c0dec996b0cda1bfe4b/packages/transformers/babel/src/config.js#L160

**Comment by ranisalt** [comment]
Try to put Typescript there:

```
import { FC } from 'react';

export const App: FC = () => {
	return <div>1</div>;
}

console.log(App);
```

**Comment by mischnic** [comment]
This babelrc works with an `index.tsx` file with your code:
```json
{
	"presets": [
		"@parcel/babel-preset-env",
		"@babel/preset-typescript",
		["@babel/preset-react", { "runtime": "automatic" }]
	]
}
```

**Comment by ranisalt** [comment]
Oh, of course it will, you are never executing the JSX transform itself. I think using `console.log(<App />);` would break, but I am yet to take the time to test it.

**Comment by mischnic** [comment]
The jsx runtime is correctly bundled, if that's what you meant.

**Comment by ranisalt** [comment]
Thing is, I am using a monorepo, and this by itself is undocumented (where to put the files?). I tried adding an invalid .babelrc file to both the root and the package and neither has problems (it should crash), so parcel is not reading my .babelrc file at all, apparently:

```json
{
	/* "presets": [ */
	/* 	"@parcel/babel-preset-env", */
	/* 	["@babel/preset-typescript", { isTSX: true }], */
	/* 	["@babel/preset-react", { "runtime": "automatic" }] */
	/* ] */
}
```

This just builds as usual.

**Comment by mischnic** [comment]
> using a monorepo

`.babelrc`s inside a monorepo are ignored: https://babeljs.io/docs/en/config-files#monorepos
