### ISSUE TITLE
Deprecate babylon-walk

### ISSUE THREAD

**Issue by wojtekmaj** [parcel-bundler/parcel#3225]
# 🙋 Feature request

It looks like the authors of babylon-walk are not reachable for a very long time. On September 2018 (!), they updated their project to Babel 7, which they did not bother to release for almost a year. Last release was 3 years ago.

As a result, with installation of `parcel-bundler`, old versions of `babel-runtime`, `babel-types`, and `regenerator-runtime` are installed.

I asked the authors almost a month ago if they have any release plans (https://github.com/pugjs/babylon-walk/issues/3), doesn't look like so...

## 💁 Possible Solution

* Use `@babel/traverse`?
* Fork `babylon-walk` and release it on our own?

**Comment by DeMoorJasper** [comment]
I actually wrote the babel 7 PR for babylon walk and am aware they didn’t release it.
We’re not gonna use babylon walk for Parcel 2 as far as I know.

Are there any issues you’ve encountered?

I’m pretty sure we’re not using babylon walk for the stuff that has changed in the babel ast
 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wojtekmaj** [comment]
I didn't hit any issues related to this package (other than just an annoyance of having duplicated, legacy packages in my node_modules), I just wrote this as a precaution.

I'm gonna raise a PR with updated babylon-walk - up to you to decide if you want it updated and merged or not. :)

**Comment by mischnic** [comment]
> Use @babel/traverse?

That is **much** slower thatn babylon-walk and often not needed.

> As a result, with installation of parcel-bundler, old versions of babel-runtime, babel-types, and regenerator-runtime are installed.

Looking at it's package.json
```json
    "@babel/runtime": "^7.0.0",
    "@babel/types": "^7.0.0",
    "lodash.clone": "^4.5.0"
```
it would work even with the latest version 7.6.3. Maybe you need to tell your package manager to updates these dependencies in the lockfile?

> We’re not gonna use babylon walk for Parcel 2 as far as I know.

We are using it now
