### ISSUE TITLE
Using Parcel bundler over Jekyll output

### ISSUE THREAD

**Issue by muratcorlu** [parcel-bundler/parcel#3233]
# ❔ Question

I have a static site generated with Jekyll. I wanted to use Parcel Bundler on it to minify and auto rename css, js and image files easily. But when I run `parcel _site/index.html` in the root folder, I get this error:

```
/Users/muratcorlu/works/muratcorlu-net/_site: EISDIR: illegal operation on a directory, read
```

Using `--log-level 5` also doesn't give extra information about this error. I couldn't find a way to debug this problem. Any idea?

## 🔦 Context

I want to combine power of Jekyll and Parcel to have a static website with templating and a good static file bundling.

## 💻 Code Sample

Here is a simple jekyll project: https://gitlab.com/muratcorlu/jekyll-with-parcel/ And here is build result: https://gitlab.com/muratcorlu/jekyll-with-parcel/-/jobs/251292334

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3 |
| Node             | 10,12 |
| npm         | 6.90 |
| Operating System | MacOs, Linux |

**Comment by ustun** [comment]
Parcel fails when it encounters a link of the form 

```<link rel="canonical" href="/" />```

It thinks that / is a dependency, tries to read it and fails since it is a directory.

**Comment by muratcorlu** [comment]
You could be right. Removing canonical url from my real project also didn't fix issue. Maybe there are some other similar url references in somewhere else. Because I also feel that somehow parcel is trying to real `/` path as a source file and fails. But I also feel that, parcel bundler should be smart enough to convert this to `/index.html` or just ignore it.

I also tried a `.flowconfig` file in root folder like this:

```
[options]
module.name_mapper='^\/$' -> '/index.html'
```

So I thought this will convert `/` references to `/index.html` but it didn't help too.

**Comment by Skalman** [comment]
I get the same error for regular links: `<a href="./">Index</a>`.
