### ISSUE TITLE
Large .wasm file size with Rust

### ISSUE THREAD

**Issue by AdenFlorian** [parcel-bundler/parcel#3235]
# 🐛 bug report

When importing a `.rs` file from a `.js` file, and building the js file with `parcel build index.js`, the resulting wasm file is much larger than expected.

```
dist\lib.c67b7947.wasm    ‼  1.4 MB    22ms
dist\index.js.map            5.9 KB     5ms
dist\index.js               3.11 KB    39ms
```

## 🤔 Expected Behavior

I would expect the wasm file to be closer to 200 KB or less.

## 😯 Current Behavior

The wasm file is 1.4 MB.

## 💻 Code Sample

https://github.com/AdenFlorian/parcel-rust-size-test

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3 |
| Node             | 10.15.1 |
| npm/Yarn         | yarn 1.17.3 |
| Operating System | Windows 10 |

**Comment by agusbena** [comment]
You can add these to your he Cargo.toml:

```
[profile.release]
lto = true
opt-level = 's'

```
And it will go, in my case, from 1.7Mb  to  189Kb
Note it is for release profile, it will take effect when you do: 

`parcel build [your_entry_point_file.ext]`
