### ISSUE TITLE
input img attribute doesn't resolve

### ISSUE THREAD

**Issue by bencooper222** [parcel-bundler/parcel#3241]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

None

## 🤔 Expected Behavior
Resolves path

## 😯 Current Behavior
Doesn't resolve path

## 💁 Possible Solution

Basically resolve assets for img src (when type="image") the normal way.

## 🔦 Context
I can't use an image as a src for an input tag. 

## 💻 Code Sample
<input src="thing.svg type="image">

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.12.3
| Node             | 11.12.0
| npm/Yarn         | 6.9.0
| Operating System | WSL on Windows 10

**Comment by mischnic** [comment]
> <input src="thing.svg type="image">

Please give a more concrete example of your html code and folder structure.

**Comment by bencooper222** [comment]
Here's a demo.
Code: https://glitch.com/edit/#!/congruous-mint?path=server.js:14:0
Rendered page: https://congruous-mint.glitch.me/


You can see (through inspect element) how Parcel adds the hash to the src attribute for the img tag but not the input tag's src attribute. This results in all references of type `<input type="image" src="something.svg">` not being rewritten at all to use `something.sha1hash.svg` that Parcel generates.

**Comment by bencooper222** [comment]
Hopefully I can get around to this over the weekend (we'll see). I believe the fix is adding the src attribute on an input tag to the Object here: https://github.com/parcel-bundler/parcel/blob/96119be782d9d551f73b77e06ab25067c7073344/packages/core/parcel-bundler/src/assets/HTMLAsset.js#L11

**Comment by MRamonLeon** [comment]
I faced same issue with just:
`<input type="image" src="/src/main/frontend/images/close-icon.svg" alt="Close">`

**Comment by windtail** [comment]
I faced same issue. any update ?
