### ISSUE TITLE
Autoprefix not working

### ISSUE THREAD

**Issue by pldg** [parcel-bundler/parcel#3243]
# 🐛 bug report

## 🎛 Configuration

**package.json**

```json
{
  "scripts": {
    "build": "parcel build src/index.html"
  },
  "browserslist": [
    "> 1%"
  ],
  "devDependencies": {
    "autoprefixer": "^9.6.1",
    "parcel-bundler": "^1.12.3",
    "postcss-modules": "^1.4.1"
  }
}
```

**postcss.config.js**

```js
module.exports = {
  "modules": true,
  "plugins": {
    "autoprefixer": true
  }
}
```

**src/index.css**

```css
body {
  box-sizing: border-box;
  display: flex;
}
```

**src/index.html**

```html
<!DOCTYPE html>
<html>
<head>
  <title>Home</title>
  <meta charset="utf-8">
  <link rel="stylesheet" href="index.css">
</head>
<body>
  <h1>Home</h1>
</body>
</html>
```

## 🤔 Expected Behavior

If I run the build I should see prefixes for box-sizing and flexbox.

## 😯 Current Behavior

Autoprefix doesn't work.

## 🔦 Context

I've also tried using `.browserslistrc` instead of `browserslist` inside package.json, and I've tried to set `"autoprefixer": {}` inside postcss.config.js

**Comment by Austaras** [comment]
doesn't seem like it needs prefix according to [browserslist](https://browserl.ist/?q=%3E+1%25), maybe your local browserslist query is different?

**Comment by pldg** [comment]
Thanks @Austaras I was thinking also to targeting IE10
