### ISSUE TITLE
Is it possible to run build but watch mode at the same time with parcel cli?

### ISSUE THREAD

**Issue by vadym1930** [parcel-bundler/parcel#3245]
# ❔ Question

Is it possible to run parcel in build mode but watch as well? Target — to get in a dist all bundle files, while coding.

## 🔦 Context

Developing chrome extension and want to have always bundled dist folder. For now, I use a workaround with nodemon to restart the build script

**Comment by mischnic** [comment]
`parcel watch main.js` is essentially `parcel main.js` without the dev server, so it doesn't do production output. Does this satisfy your needs?

https://github.com/parcel-bundler/parcel/blob/96119be782d9d551f73b77e06ab25067c7073344/packages/core/parcel-bundler/src/cli.js#L215-L224

@DeMoorJasper Is there a way to do `parcel watch` and production mode?

**Comment by vadym1930** [comment]
I need something opposite. Build with full production dist output and watch at the same time to always have fresh build in a dist folder ready to use.

**Comment by mischnic** [comment]
(A production build can take considerably more time because of scope hoisting and minification, making the "watch" experience much less instant)

**Comment by DeMoorJasper** [comment]
The only way this is currently possible is by using the node.js api afaik

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vadym1930** [comment]
Okay, I see. Yep, that's time-consuming. But what's left... Well, thanks anyway

**Comment by denizdogan** [comment]
Will this be possible in v2 by any chance? I'm looking for the same feature.
