### ISSUE TITLE
Exclude node_modules from bundle

### ISSUE THREAD

**Issue by tavolate** [parcel-bundler/parcel#3246]
# ❔ Question

Is it possible to excludes all modules from the node_modules directory? 

## 🔦 Context

I would like to insert into the parcel bundle only the local modules

I'm developing several micro services by AWS Lambda and I would like to insert the node_modules modules into a specific layer.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.15.3
| npm/Yarn         | 6.4.1
| Operating System | OSX

**Comment by mischnic** [comment]
> I'm developing several micro services by AWS Lambda

Have you tried the `--target node` flag?

**Comment by tavolate** [comment]
I will try, thank you!

**Comment by tavolate** [comment]
it works!
