### ISSUE TITLE
fs.readFileSync not working if path is a variable

### ISSUE THREAD

**Issue by egorvinogradov** [parcel-bundler/parcel#3253]
# 🐛 bug report

This works:
```
function getFile () {
  const fs = require('fs');
  const file = fs.readFileSync(__dirname + '/path/to/file.css', 'utf8');
}
```

Changing to this leads to an error `TypeError: fs_1.readFileSync is not a function`
```js
function getFile (myPath = '/path/to/file.css') {
  const fs = require('fs');
  const file = fs.readFileSync(__dirname + myPath, 'utf8');
}
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    "@babel/env",
    "@babel/preset-react",
    "@babel/preset-typescript"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties"
  ]
}
```

## 🤔 Expected Behavior

`fs.readFileSync` should read the file just like in the first example

## 😯 Current Behavior

File is not read because error `fs.readFileSync` becomes undefined.
Error in the console: `TypeError: fs_1.readFileSync is not a function`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.3
| Node             | 11.9.0
| npm/Yarn         | 6.5.0
| Operating System | MacOS 10.14.5

**Comment by DeMoorJasper** [comment]
That would need to be asynchronous, which is impossible for frontend unless Parcel runs as a server (even in production) which is kinda weird. If this is your goal either require/import everything you need or use a virtual filesystem

**Comment by egorvinogradov** [comment]
I see. Thank you for the quick response.
