### ISSUE TITLE
Support plugin written in ESM format (default export)

### ISSUE THREAD

**Issue by 3cp** [parcel-bundler/parcel#3256]
# ❔ Question

Parcel plugin expects plain CommonJS module with a function as the whole exports.

```js
module.exports = function(bunder) {}
```

For plugin author that uses ESM format (with babel or TypeScript), should Parcel support default export as well?

```js
export default function(bundler) {}
```

## 💻 Code Sample

https://github.com/parcel-bundler/parcel/blob/96119be782d9d551f73b77e06ab25067c7073344/packages/core/parcel-bundler/src/Bundler.js#L218-L219

This plugin loading logic can be improved to support plugin written in ESM format as well.

In contract, Parcel did have a correct loadPlugins here https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/utils/loadPlugins.js
This version of loadPlugins is used by postcss and posthtml for additional plugins.

A simple one line will improve it. `plugin = plugin.default || plugin;`.

Let me know if you consider this improvement. I will make a PR if so.

**Comment by 3cp** [comment]
There are more.

```js
bundler.addAssetType('ext', require.resolve('./MyAsset'));
bundler.addPackager('foo', require.resolve('./MyPackager'));
```

All those parser, packager API need to support ESM format as well. There are few more lines to be touched.

**Comment by 3cp** [comment]
Hope this will be addressed in Parcel v2.

**Comment by mischnic** [comment]
It is (when loading a Plugin, it does `plugin.default ? plugin.default : plugin`)

**Comment by bubnenkoff** [comment]
Does Parcel 2 support it for now?

**Comment by mischnic** [comment]
Yes, as I've written in my last comment:
https://github.com/parcel-bundler/parcel/blob/82747eb5778248d8db35186ec424687f91db5942/packages/core/core/src/loadParcelPlugin.js#L45
