### ISSUE TITLE
Ignore HTML elements based on environment variables.

### ISSUE THREAD

**Issue by samuelgozi** [parcel-bundler/parcel#3264]
# 🙋 Feature request

Often it is necessary to output different HTML in production than in development, a common use case would be analytics, some scripts for debugging and some times different versions of service workers, etc.

I believe that it would be a good idea to add the ability to tell Parcel bundler to ignore an element or a few lines of code based on the type of the build(production vs development).

## 🤔 Expected Behavior

I have a few ideas, but this is the cleanest one, and it wouldn't require any configuration.
```
<template -data-parcel-production="true">
    <script src="script-to-run-only-on-production.js"></script>
</template>
```

Basically, ParcelJS will look for HTML tags with the attribute `-data-parcel-production` or `-data-parcel-development` and look what its value is(true or false), and then decide if it should omit it or leave it without changes.
## 😯 Current Behavior

Currently, it's not possible without post HTML plugins, which I think is overkill just for a few if statements.

## 💁 Possible Solution

I'm not familiar with the internals of parcel, but if it uses a DOM implementation then it should be pretty easy. Just make a query based on the attribute, then loop over it and based on its value decide if either to keep it or remove it.

## 🔦 Context

I have a few web applications that have some scripts the I don't want to run in development, I believe that most websites will have some too.

## 💻 Examples

Gave some above.

**Comment by mischnic** [comment]
We try to make parcel be very framework independent/customisable while not including too many features in the core itself (also to keep the number of configuration options small compared to Webpack).

> Currently, it's not possible without post HTML plugins, which I think is overkill just for a few if statements.

I think this is a perfect fit for a PostHTML plugin.
E.g.: https://github.com/posthtml/posthtml-expressions#conditionals

**Comment by samuelgozi** [comment]
@mischnic The problem is that posthtml-expressions doesn't work correctly with other plugins, like for example vue.
