### ISSUE TITLE
It seems parcel-bundler installation is slower then webpack

### ISSUE THREAD

**Issue by dotku** [parcel-bundler/parcel#3265]
I don't see parcel would be faster from my practice

+ webpack@4.37.0
added 389 packages from 216 contributors and audited 4229 packages in 22.535s
found 0 vulnerabilities

+ parcel-bundler@1.12.3
added 511 packages from 429 contributors and audited 12463 packages in 48.923s
found 0 vulnerabilities

![image](https://user-images.githubusercontent.com/1519232/61899115-a0c15980-aecf-11e9-908e-ee868ed30c48.png)

**Comment by mischnic** [comment]
Parcel has more dependencies than Webpack (e.g.: terser, babel, babel-preset-env), so this is no surprise (you need some extra loaders to make Webpack have the same features).
Our Readme says `fast bundle times`.

**Comment by DeMoorJasper** [comment]
Parcel 2 will solve this by not requiring everything in the core package as Parcel currently does. Although installation times shouldn't be an issue as you could cache this?

**Comment by mischnic** [comment]
Closing because long install times are solvable by caching (and you don't need to run that very often). Our website/readme says "fast bundle times".
