### ISSUE TITLE
Tippy.js not working with tree shaking

### ISSUE THREAD

**Issue by hampuskraft** [parcel-bundler/parcel#3267]
# 🐛 bug report

[Tippy.js](https://github.com/atomiks/tippyjs) (dependent on [popper.js](https://github.com/FezVrasta/popper.js)) is not working with tree shaking enabled.

## 🎛 Configuration (package.json)

```js
  "scripts": {
    "start": "yarn build && node server.js",
    "build": "parcel build src/*html --experimental-scope-hoisting"
  }
```

```sh
$ yarn start
```

## 🤔 Expected Behavior

I should be able to use my tooltip library even with tree shaking enabled.

## 😯 Current Behavior

Tooltips are not showing when hovering associated elements. Instead, the following error message is outputted in console:

```
app.eab83fee.js:1 Uncaught TypeError: t is not a constructor
    at Ct (app.eab83fee.js:1)
    at app.eab83fee.js:1
    at kt (app.eab83fee.js:1)
    at Tt (app.eab83fee.js:1)
    at HTMLImageElement.bt (app.eab83fee.js:1)
```

Uncaught TypeError: t is not a constructor:
```js
  U.popperInstance = new t(n,_,c)
```

## 🔦 Context

I tried enabling tree shaking to my site, but my tooltips aren't working.

## 💻 Code Sample

index.js
```js
import tippy from 'tippy.js/umd/index.min.js'
tippy.setDefaults({
  animation: 'fade',
  arrow: true
})
```

index.html
```html
<div style="height:100vh;width:100vw;background:red" data-tippy="Test" data-tippy-placement="top"></div>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | v10.16.0
| Yarn         | 1.17.3
| Operating System | Windows 10 OS Version 1803 (Build 17134.885)

**Comment by mischnic** [comment]
Works with `--no-minify` (probably because terser doesn't run on the umd bundle then), error happens when hovering:

```html
<button id="myButton">My Button</button>
<script type="text/javascript" src="index.js"></script>
```
```js
import tippy from 'tippy.js/umd/index.min.js' // doesn't work
// import tippy from "tippy.js"; // works
tippy.setDefaults({
	animation: "fade",
	arrow: true
});

tippy("#myButton", {
	content: "I'm a Tippy tooltip!"
});
```

Probably has something to do with linking or hoisting, because it errors even without `treeShake` and `mangleScope` (in concat.js).
