### ISSUE TITLE
Chrome breakpoints / source maps completely broken

### ISSUE THREAD

**Issue by cpury** [parcel-bundler/parcel#3268]
# 🐛 bug report

I have a small project consisting of ~5 files. It also imports some NPM-installed third party packages, among them lodash and TFJS.

When trying to debug in Chrome dev tools as usual, breakpoints do not work at all. They either get ignored or get set in completely unrelated places (e.g. I click on a line in a file of mine and the actual breakpoint gets set in a random file of random NPM dependency that I have nothing to do with). When exceptions are thrown, the call stack is all over place. E.g. call stack entries that are clearly part of my code are referenced to be inside the lodash package etc. Another annoying problem is that at every hot code push / refresh, the underlying files seem to change and all previous breakpoints / call stacks become void.

So far I've worked extensively with Meteor as my bundler and it always worked exactly as expected, without any of this weird behavior. Can't say I'm impressed from Parcel so far.

## 🎛 Configuration (.babelrc, package.json, cli command)

**.babelrc:**

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": false
      }
    ]
  ],
  "plugins": [
    ["@babel/plugin-transform-runtime", {
      "corejs": 2
    }]
  ]
}
```

**package.json (excerpt):**

```js
  "dependencies": {
    "@babel/runtime-corejs2": "^7.5.5",
    "@tensorflow/tfjs": "^1.2.5",
    "bulma": "^0.7.5",
    "lodash": "^4.17.15"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/plugin-transform-runtime": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "autoprefixer": "^9.6.1",
    "babel-eslint": "^10.0.2",
    "babel-polyfill": "^6.26.0",
    "browser-sync": "^2.26.7",
    "eslint": "^6.1.0",
    "eslint-config-airbnb": "^17.1.1",
    "eslint-config-prettier": "^6.0.0",
    "eslint-plugin-prettier": "^3.1.0",
    "parcel-bundler": "^1.12.3",
    "prettier": "^1.18.2",
    "sass": "^1.22.7"
  },
```

## 🤔 Expected Behavior

Breakpoints should work as expected and be in the right places. Call stacks should refer to the correct places.

## 😯 Current Behavior

See above.

## 💁 Possible Solution

No idea.

## 🔦 Context

Trying to get a basic project with TFJS to work.

## 💻 Code Sample

If this is somehow related: TFJS is written in TypeScript. I import it as such:

`import * as tf from '@tensorflow/tfjs';`

## 🌍 Your Environment

OSX, everything at the latest version.

**Comment by mischnic** [comment]
This is nearly impossible to investigate without a reproduction. 

> Another annoying problem is that at every hot code push / refresh, the underlying files seem to change and all previous breakpoints / call stacks become void.

https://github.com/parcel-bundler/parcel/issues/643#issuecomment-466794841, not a single browser implements that (which I figured out after implementing a fix for Parcel that didn't work).

**Comment by cpury** [comment]
I know, which made me even more frustrated when I wrote this. I'll see if I can find the time to isolate the issue. If not, I'm afraid I'll have to find some other bundler for my project.

**Comment by ShaCP** [comment]
Same problem.
