### ISSUE TITLE
Error when scss file is empty

### ISSUE THREAD

**Issue by gongpeione** [parcel-bundler/parcel#327]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
🐛 bug report

### 🤔 Expected Behavior
Built successful

### 😯 Current Behavior
Build failed, `No input specified: provide a file name a source string to process`

### 💁 Possible Solution
pass a `space` when .scss file is empty

### 🔦 Context
I know scss file is not empty normally, but I think maybe it should not show an error message when it is empty. And I can create a pr if you want.

**Comment by nnnikolay** [comment]
I just took to play around with the latest version and I end up with not working HRM, apparently. When scss has been changed the process either stops or changes are not visible unless I refresh the page. It happens also if I make some big changes, for example, refactoring (incl. npm modules installation) from simple js file to react based 'hello world'. Complete re-run `npm start` helps though.

**Comment by davidnagli** [comment]
@nnnikolay I’m not really understanding how that applies to this issue...

@gongpeione Wow great catch! This definetly needs to get fixed. Can you please make a PR?

**Comment by nnnikolay** [comment]
@davidnagli sorry if it's not, I just started with an empty file as well, and then almost every file creation, module installation etc... leads me to the Error, I thought it might be connected.

**Comment by brandon93s** [comment]
Is there a valid use case for an empty sass file, or are we solving for an edge case here?

**Comment by davidnagli** [comment]
@brandon93s Looks like an edge case

**Comment by rondonjon** [comment]
@brandon93s it is definitely a bug. An importer should be able to handle empty files unless empty files are invalid by the file type specification.

it may be an edge case in daily development, but considering the trouble that it causes and the little effort that it takes to solve it, I would definitely take the change. If this helps 50 people each save 30 minutes of bug search, it's worth it.

**Comment by brandon93s** [comment]
I don't disagree, I just think this should be solved to handle all empty assets. The proposed solution fixed SASS only. I support empty asset handling at a higher level.

**Comment by gongpeione** [comment]
Yes, I agree empty files should be handling at a higher level.

**Comment by devongovett** [comment]
Closing. Should be fixed by #340.
