### ISSUE TITLE
.env file with react is not working

### ISSUE THREAD

**Issue by niksseif** [parcel-bundler/parcel#3273]
I am working on a project in React and Parcel when I try console.log(process.env) is returning an empty object but if I add API_Key to it  will return undefined 
console.log(process.env) => {}
console.log(process.env. REACT_APP_API_Key) => undefined 
here is my package json :
"scripts": {
    "clear-build-cache": "rm -rf .cache/ dist/",
    "dev": "parcel src/index.html",
    "build": "parcel build index.html",
    "dev:mock": "cross-env OPEN-INV=mock parcel src/index.html",
    "format": "prettier --write \"src/**/*.{js,jsx}\"",
    "lint": "eslint \"src/**/*.{js,jsx}\" --quiet",
    "test": "echo \"Error: no test specified\" && exit 1"
  },

Can someone tell me what is wrong?

**Comment by mischnic** [comment]
This works for me: https://github.com/mischnic/parcel-issue-3273

**Comment by niksseif** [comment]
@mischnic thank you it is working now. I am using Parcel with React and deploying it on Firebase. I have a Gist of it here https://gist.github.com/niksseif/d86c4a3c05e2f3ca834a4c09152024ca

**Comment by mischnic** [comment]
🎉
