### ISSUE TITLE
Passing environment variables to the frontend

### ISSUE THREAD

**Issue by JwanKhalaf** [parcel-bundler/parcel#3277]
# ❔ Question

When using Docker, how does one pass environment variables to the react frontend?

## 🔦 Context

I want to run the react app inside a docker container. I am using `docker-compose` and my `docker-compose.yml` looks like this:

```
version: "3.7"

services:
  bejebeje-react:
    build:
      context: .
      dockerfile: ./Dockerfile
      labels:
        com.bejebeje.description: "Bejebeje's ReactJS frontend"
    image: bejebeje-react:latest
    ports:
      - "1234:80"
    env_file:
      - ./variables.env
```

My `Dockerfile` looks like this:

```
# set base image as alpine-node version 11.
FROM mhart/alpine-node:11 AS builder

# fontawesome pro auth token
ARG FONTAWESOME_NPM_AUTH_TOKEN

# set the working directory for any RUN, CMD, ENTRYPOINT, COPY and ADD
# instructions that follows the WORKDIR instruction.
WORKDIR /app

# remember, our current working directory within the container is /app
# we now copy everything (except stuff listed in .dockerignore)
# from local machine to /app (in the container).
COPY . .

# install dependencies as normal.
RUN yarn install

# run the command for building deployment assets.
RUN yarn run build

# create a fresh image, this will be a light image because we are only
# going to put in it the built assets and nothing else.
FROM mhart/alpine-node

# install a light-weight server of static files.
# https://www.npmjs.com/package/serve
RUN yarn global add serve

# set the working directory for any RUN, CMD, ENTRYPOINT, COPY and ADD
# instructions that follows the WORKDIR instruction.
WORKDIR /app

# copy our built assets from the first container to the current one we are in.
COPY --from=builder /app/dist .

# copy the robots.txt file into the current /app directory of the image.
COPY --from=builder /app/robots.txt .

# run the light-weight server on port 80.
CMD ["serve", "-p", "80", "-s", "."]
```

## 💻 Code Sample

The content of `variables.env` is like this:

```
IDENTITY_AUTHORITY = http://localhost:5005
IDENTITY_CLIENT_ID = bejebeje-react-local
IDENTITY_REDIRECT_URI = http://localhost:1234/login-callback
IDENTITY_RESPONSE_TYPE = code
IDENTITY_SCOPE = openid profile bejebeje-api-local
IDENTITY_POST_LOGOUT_REDIRECT_URI = http://localhost:1234/logout-callback
```

With different values obviously.

Then the way I try to make use of them is in a file called `authConfig.js` and it looks like this:

```
export const IDENTITY_CONFIG = {
  authority: process.env.IDENTITY_AUTHORITY,
  client_id: process.env.IDENTITY_CLIENT_ID,
  redirect_uri: process.env.IDENTITY_REDIRECT_URI,
  response_type: process.env.IDENTITY_RESPONSE_TYPE,
  scope: process.env.IDENTITY_SCOPE,
  post_logout_redirect_uri: process.env.IDENTITY_POST_LOGOUT_REDIRECT_URI
};
```

## 🌍 Your Environment

`docker-compose up` is called on my Ubuntu server.

**Comment by mischnic** [comment]
Your setup seems fine. Could you please describe the specific issue you're having with the current configuration (what is the output, do these values get replaced with `undefined`)?
Parcel will replace expressions like `process.env.IDENTITY_AUTHORITY` with the current env variables during bundling (I guess in your case `yarn run build`).

**Comment by JwanKhalaf** [comment]
The code is deployed here: https://bejebeje.com. If you open the developer console and look for the `authConfig.js` file, you'll see that `process.env.IDENTITY_AUTHORITY` is `undefined`.

All code is o[pen source](https://github.com/JwanKhalaf/Bejebeje.React/tree/feature/passing-environment-variables-to-the-frontend) too.

**Comment by mischnic** [comment]
Authority is replaced with an empty string because of your package.json script: `IDENTITY_AUTHORITY=${IDENTITY_AUTHORITY} parcel build src/index.html`
All env variables you use aren't set, which is why Parcel replaces them with `undefined`.

If you print out all env variables where `RUN yarn install` is in the Dockerfile. Do they actually show up?

**Comment by JwanKhalaf** [comment]
That was a thing I added yesterday whislt playing about in order to experiment, I've un-did that change and I now have the following in my `package.json`

```
"scripts": {
    "dev": "parcel src/index.html",
    "build": "parcel build src/index.html"
  },
```

As for the logs when running `RUN yarn install`, here is what I see in Travis CI:

![image](https://user-images.githubusercontent.com/42877376/61995224-4fef6380-b07d-11e9-8800-3685c89e3c6a.png)

**Comment by mischnic** [comment]
> No variables are being printed out, not sure if they're supposed to over there, but if they are, then something isn't right.

I meant: put something like `RUN env` in the dockerfile. That would print out the env variables. If they're not there, then it's a Docker issue.

**Comment by JwanKhalaf** [comment]
I see, Ok, give me a few minutes, I'll try and `echo` out the environment variables being passed to the container via `variables.env` file.

**Comment by JwanKhalaf** [comment]
Ok I got it working, I needed to update my `Dockerfile` to be:

```
# set base image as alpine-node version 11.
FROM mhart/alpine-node:11 AS builder

# fontawesome pro auth token
ARG FONTAWESOME_NPM_AUTH_TOKEN

# identity authority
ARG IDENTITY_AUTHORITY

# identity client id
ARG IDENTITY_CLIENT_ID

# identity redirect uri
ARG IDENTITY_REDIRECT_URI

# identity response type
ARG IDENTITY_RESPONSE_TYPE

# identity scope
ARG IDENTITY_SCOPE

# identity post logout redirect ui
ARG IDENTITY_POST_LOGOUT_REDIRECT_URI

# set the working directory for any RUN, CMD, ENTRYPOINT, COPY and ADD
# instructions that follows the WORKDIR instruction.
WORKDIR /app

# remember, our current working directory within the container is /app
# we now copy everything (except stuff listed in .dockerignore)
# from local machine to /app (in the container).
COPY . .

# install dependencies as normal.
RUN yarn install

# run the command for building deployment assets.
RUN yarn run build

# create a fresh image, this will be a light image because we are only
# going to put in it the built assets and nothing else.
FROM mhart/alpine-node

# install a light-weight server of static files.
# https://www.npmjs.com/package/serve
RUN yarn global add serve

# set the working directory for any RUN, CMD, ENTRYPOINT, COPY and ADD
# instructions that follows the WORKDIR instruction.
WORKDIR /app

# copy our built assets from the first container to the current one we are in.
COPY --from=builder /app/dist .

# copy the robots.txt file into the current /app directory of the image.
COPY --from=builder /app/robots.txt .

# run the light-weight server on port 80.
CMD ["serve", "-p", "80", "-s", "."]
```

And then I defined the variables in **Travis CI**, so they now come from there instead of the `variables.env` file.

I also had to update my `docker-publish-travis.sh` file to be like this:

```
# build the docker image.
docker build -f ./Dockerfile -t bejebeje/react:$DOCKER_TAG -t bejebeje/react:$TRAVIS_BUILD_NUMBER --build-arg FONTAWESOME_NPM_AUTH_TOKEN=$FONTAWESOME_NPM_AUTH_TOKEN --build-arg IDENTITY_AUTHORITY=$IDENTITY_AUTHORITY --build-arg IDENTITY_CLIENT_ID=$IDENTITY_CLIENT_ID --build-arg IDENTITY_REDIRECT_URI=$IDENTITY_REDIRECT_URI --build-arg IDENTITY_RESPONSE_TYPE=$IDENTITY_RESPONSE_TYPE --build-arg IDENTITY_SCOPE=$IDENTITY_SCOPE --build-arg IDENTITY_POST_LOGOUT_REDIRECT_URI=$IDENTITY_POST_LOGOUT_REDIRECT_URI . --no-cache
```

Now the variables are populated on the frontend :) Thank you for your help @mischnic 👍
