### ISSUE TITLE
[RFC] Parcel 2: Programmatic API ConfigProvider

### ISSUE THREAD

**Issue by padmaia** [parcel-bundler/parcel#3284]
## Proposal
One direction we have taken in Parcel 2 is to allow tools to resolve their own config if they have an API for doing so. The main inspiration for this was Babel, which provides `babel.loadPartialConfig` and `babel.loadOptions` to help with it's complex config resolution (especially after Babel 7) and config validation. This approach does not work well with the previously suggested method for tools/frameworks that would build on top of Parcel in #2574, because it would force all config loading to be done through a `ConfigProvider`. Based on the feedback from that issue, what most tools/framework would need is a way to provide a default config if no filesystem config is found or a way to modify the filesystem config. Our config request system should accommodate this nicely. Programmatic API users could still pass a `ConfigProvider` but instead of being responsible for loading config, it would just provide defaults if no filesystem config is loaded or modification functions if the loaded config needs to be modified in some way.  It might look something like this:

```
import {Parcel, ConfigProvider} from '@parcel/core';

let configProvider = new ConfigProvider({
  '@parcel/transformer-babel': {
    default: {plugins: [...defaultBabelPlugins]},
    modify: (config) => modifyBabel(config)
  }
});

let parcel = new Parcel({
  configProvider,
  // ...
});
```

One question I have about this is whether we would pass the object with `default` and `modify` to the plugin and it would have to deal with it or whether core could handle the behavior the same way for all plugins. One reason that makes me think we might need the plugin to deal with it is because the plugins sometimes provide their own defaults, like `@parcel/babel-transformer`. You would probably need separate functions for finding filesystem config and applying a default if none is found. I'd prefer to keep just one `loadConfig` function on the plugins. `modify` seems like it could be run by core, but I'm not sure if it would be weird that `default` would be handled by plugins while `modify` is handled by core.

## Feedback
Thoughts? Does anyone see any problems with this approach or have suggestions for improvement?

CC'ing the same folks that were CC'd on the last #2574 issue:
* @timneutkens - Next.js
* @KyleAMathews - Gatsby
* @gaearon @iansu - create-react-app
* @yyx990803 @sodatea - Vue CLI
* @Atinux - Nuxt
* @ndelangen - Storybook

**Comment by brillout** [comment]
I will give feedback about this while I re-implement Goldpage (https://github.com/reframejs/goldpage) to use Parcel instead of Webpack.
