### ISSUE TITLE
Parcel does not resolve .tx, .tsx files

### ISSUE THREAD

**Issue by bologer** [parcel-bundler/parcel#3285]
# ❔ Question

I would like Parcel to resolve different file extensions without necessity to type .js, .jsx or .ts in `import`. 

## 🔦 Context

Trying to import file without extension and parcel should be able to find best match, e.g. when I have App.jsx, it should try to find App.js -> fail, App.ts -> fail, App.jsx -> should be used.

## 💻 Code Sample

```js
// index.tsx
import React from 'react'
import {render} from 'react-dom'
import App from './App';

render(<App/>,
    document.getElementById('root')
);
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.2 |
| Node             | v8.16.0 |
| npm/Yarn         | 6.10.2|
| Operating System | Linux Mint |

**Comment by mischnic** [comment]
Is this a bug report or a feature request? This should work already

**Comment by bologer** [comment]
@mischnic initially I thought it was bug, but then I realized it was related to cache. I cleared .cache folder and error was gone. I think imports were cached and this is why I had this error. 

I don't know if this is expected behaviour? Should Parcel try to write better error message in this case?

**Comment by mischnic** [comment]
> I don't know if this is expected behaviour?

No 😄 

> Should Parcel try to write better error message in this case?

There should never be an error in the first place.

**Comment by bologer** [comment]
@mischnic  I assume then that it is a bug because .cache was causing parcel to search for incorrect file extension.

**Comment by mischnic** [comment]
> I assume then that it is a bug because .cache was causing parcel to search for incorrect file extension.

Yes, I'm guessing the file once existed and Parcel didn't reevaluate the extensions after the file was deleted/renamed.

Closing because it's likely fixed with Parcel 2 and this can't be investiaged without a way to reliably reproduce this situation.

**Comment by bologer** [comment]
@mischnic  Here are the steps to reproduce:

- create file App.js
- Run parcel 
- change name of App.js to App.jsx
- Parcel would fail to run any furhter as it cannot resolv App.js

**Comment by Wilfred** [comment]
As a workaround, temporarily writing:

```
import App from "./App.jsx";
```

seems to be sufficient to make parcel start tracking the file in its new path. You can then change the line back to just `"./App"`.
