### ISSUE TITLE
HTTP vs HTTPS site hosting gives this error

### ISSUE THREAD

**Issue by DrYSG** [parcel-bundler/parcel#3286]
I am not using Web Sockets on this web page , but -

I am trying to understand why Chrome console prints the following "error" (I use quotes because it does not effect anything). The error only appears when I host on a HTTPS site, not HTTP (the same IIS server which is local to my computer is being used).

(and there is a valid TLS/SSL certificate)m, I have no idea why port 61396 is being looked at..

```
hmr-runtime.js:29 WebSocket connection to 'wss://ysg4206.draper.com:61396/' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR
parcelRequire.../../../node_modules/parcel-bundler/src/builtins/hmr-runtime.js @ hmr-runtime.js:29
```

**Comment by mischnic** [comment]
This is part of the hot module reloading feature. You can disable it via `--no-hmr`.
Otherwise, you'll have to proxy the websocket through your IIS proxy as well (if I understood your setup correctly).

**Comment by DrYSG** [comment]
Since this is set of programs local to our corporate intranet, and the workstations will be pretty much dedicated to these tasks, I was thinking of using a PWA approach, and not doing hot loading. Does that sound reasonable? (I also have to admit that I have never setup a IIS proxy or reverse proxy).

**Comment by mischnic** [comment]
PWA and hot reloading aren't really related.
Hot reloading automatically reloads the page when you make a change in development, it is not for deploying a new version.

**Comment by DrYSG** [comment]
I thought it might be for incremental download of bundles (dynamic imports) so that the update might be in pieces. But what I am hearing from you is that it is purely a development hot reload. Is my understanding now correct, or does it need further improvement?

**Comment by mischnic** [comment]
> But what I am hearing from you is that it is purely a development hot reload

Correct

**Comment by anhndjs** [comment]
help me.
