### ISSUE TITLE
experimental-scope-hoisting throw error:  ReferenceError: require is not defined

### ISSUE THREAD

**Issue by wulucxy** [parcel-bundler/parcel#3288]
# 🐛 bug report

when I enable ` experimental-scope-hoisting`，the result will throw error: 

` ReferenceError: require is not defined`

![image](https://user-images.githubusercontent.com/5326403/62183255-0b6d0c00-b38c-11e9-8226-df92d3bd2e66.png)

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// .babelrc
{
  "presets": [
    ["@babel/env"],
    "@babel/typescript",
    ["@babel/react"]
  ],
  "plugins": [
    ["@babel/transform-runtime", {
      "corejs": 2
    }],
    "@babel/syntax-dynamic-import",
    ["@babel/proposal-decorators", {"legacy": true}],
    ["@babel/proposal-class-properties"],
    ["import", { "libraryName": "antd", "style": true, "libraryDirectory": "es" }]
  ],
  "env": {
    "development": {
      plugins: ["react-hot-loader/babel"]
    }
  },
  "sourceMaps": true,
  "retainLines": true
}
```

```json
// package.json
build": "parcel build src/public/index.html --no-source-maps --experimental-scope-hoisting --no-minify",
```

## 🤔 Expected Behavior

enable `--experimental-scope-hoisting` should not throw error。

## 😯 Current Behavior

enable `--experimental-scope-hoisting`throw error： `ReferenceError: require is not defined`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.3 | 
| Node             | 10.14.1  |  
| npm/Yarn         |  6.4.1  | 
| Operating System |  macOS  |

**Comment by mischnic** [comment]
Could you please provide a reproduction code sample? This is very likely related to https://www.npmjs.com/package/babel-plugin-import

**Comment by mjl** [comment]
Just had this happen to me. It happens with a very very minimal "app.js" as follows with

node_modules/.bin/parcel build --out-dir ../static --experimental-scope-hoisting app.js



```
import Vue from "vue";
import BootstrapVue from 'bootstrap-vue';
Vue.use(BootstrapVue);
```

(needs "bootstrap-vue": "^2.0.4",  "vue": "^2.6.10")

**Comment by TakanashiOuken** [comment]
Same issue here. No Solution for this?

**Comment by mjl** [comment]
> Same issue here. No Solution for this?

At least a workaround. In my html file, I do

     <script type="text/javascript">
     window.require = function(e) { console.debug("require hack still 
required //", e); return undefined; };
     </script>

before loading any compiled JS, that at least allows things to proceed.

Cheers!

**Comment by TakanashiOuken** [comment]
> Same issue here. No Solution for this?
> At least a workaround. In my html file, I do <script type="text/javascript"> window.require = function(e) { console.debug("require hack still required //", e); return undefined; }; </script> before loading any compiled JS, that at least allows things to proceed. Cheers!

Nice evil walk around. 
I turned to lodash-es to fix this issue but brings me to a next issue...
Seems like `_.clone` will cause errors with tree shaking. 
`$xxx$var$arrayBufferTag is undefined` Orz

**Comment by darioielardi** [comment]
same issue here: `$NYPs$var$arrayBufferTag is not defined`

**Comment by darioielardi** [comment]
Unfortunately I'm not even using lodash, and I can't figure out what's causing the error.
