### ISSUE TITLE
parcelRequire.register incorrectly added

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#3290]
# 🐛 bug report

If the entry HTML file has a single JS file as a script (and no dynamic imports) (like the react-hmr example), a `parcelRequire.register("...",{})` is inserted incorrectly (and this calls throws an error as well because the prelude defining `parcelRequire` wasn't inserted).

This is because `bundleGraph.isAssetReferenced(asset)` is true (referenced by the HTML file), but the module only needs to be registered if it's (dynamically) imported by a JS bundle. So the check should really be something like an imaginary `bundleGraph.isAssetReferencedByType(asset, "js")`.

https://github.com/parcel-bundler/parcel/blob/baf40f7a331024bbfb3bb0394242fbd8d2928330/packages/shared/scope-hoisting/src/concat.js#L98-L103

```
Uncaught ReferenceError: parcelRequire is not defined:
	parcelRequire.register("1d046a184a4b101007cf746265aa38be",{})
```

CC @wbinnssmith I don't know if there's a way to get this information from the public bundleGraph?

**Comment by wbinnssmith** [comment]
> CC @wbinnssmith I don't know if there's a way to get this information from the public bundleGraph?

Currently not, but I like your proposal for `isAssetReferenced` with a type.
