### ISSUE TITLE
How to import packages installed via Bower?

### ISSUE THREAD

**Issue by amitaibu** [parcel-bundler/parcel#3294]
# ❔ Question

How to `import` packages installed via Bower?

## 🔦 Context

I'm trying to use Google-maps webcomponent, that is available via bower.

## 💻 Code Sample

[Here's](https://github.com/amitaibu/google-maps-parcel/blob/8da677960617d64d24ea410eee1a9635e0a5395d/app.js#L1
) a sample repo with the import.

```
import 'bower_components/webcomponentsjs/webcomponents-lite.min.js';
import 'bower_components/google-map/google-map.html';
```

Results with the error:

![image](https://user-images.githubusercontent.com/125707/62239330-56633f80-b3dd-11e9-922b-255de4aa4a78.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | v8.15.1
| npm/Yarn         | npm - 6.4.1
| Operating System | Ubuntu 18

**Comment by mischnic** [comment]
Are you sure the file `bower_components/webcomponentsjs/webcomponents-lite.min.js` exists?
It does not exist for me after running `bower install webcomponentsjs`.

**Comment by amitaibu** [comment]
Thanks for checking this. Yes, It seems it does for me (I've deleted and re-ran `bower install`):

![Selection_306](https://user-images.githubusercontent.com/125707/62269741-a7565080-b43c-11e9-9abc-a22b5a4ba396.png)

You can also try `bower i GoogleWebComponents/google-map`

**Comment by mischnic** [comment]
I meant that the file `webcomponents-lite.min.js` does't exist:
![Bildschirmfoto 2019-08-01 um 08 39 08](https://user-images.githubusercontent.com/4586894/62271038-dc13d900-b437-11e9-9209-7d00e4a00f8c.png)

**Comment by amitaibu** [comment]
Sorry, you are right. However even after I change it to the correct file name I get (pushed a fix to the example repo)

```
import 'bower_components/webcomponentsjs/webcomponents-lite.js';
import 'bower_components/google-map/google-map.html';
```

![image](https://user-images.githubusercontent.com/125707/62271271-dd95cf00-b440-11e9-99f6-aa9029894125.png)

**Comment by mischnic** [comment]
What example repo?

> However even after I change it to the correct file name

The file `bower_components/webcomponentsjs/webcomponents-lite.js` still doesn't exist. Or is this a convention on how to reference files with Bower?

**Comment by mischnic** [comment]
What example repo?

> However even after I change it to the correct file name

The file `bower_components/webcomponentsjs/webcomponents-lite.js` still doesn't exist. Or is this a convention on how to reference files with Bower?

**Comment by amitaibu** [comment]
> What example repo?

https://github.com/amitaibu/google-maps-parcel

> The file bower_components/webcomponentsjs/webcomponents-lite.js still doesn't exist

I see it there after `bower install`

![image](https://user-images.githubusercontent.com/125707/62349388-47c57700-b508-11e9-9826-db620aa34532.png)

**Comment by amitaibu** [comment]
> What example repo?

https://github.com/amitaibu/google-maps-parcel

> The file bower_components/webcomponentsjs/webcomponents-lite.js still doesn't exist

I see it there after `bower install`

![image](https://user-images.githubusercontent.com/125707/62349388-47c57700-b508-11e9-9826-db620aa34532.png)

**Comment by mischnic** [comment]
You need to change your imports:
```js
import './bower_components/webcomponentsjs/webcomponents-lite.js';
import './bower_components/google-map/google-map.html';
```

With `bower_components/webcomponentsjs/webcomponents-lite.js`, Parcel interprets the path as  "inside the npm package `bower_components`, the file `webcomponentsjs/webcomponents-lite.js`"

(The html import you did currently does nothing, probably not what you intended).

**Comment by amitaibu** [comment]
As always - many thanks for looking into it!

Indeed - I have tried this `.` it in the past, but probably while I had the wrong file name. 

> The html import you did currently does nothing, probably not what you intended

That would have been my next issue. I was trying to mimic the code from https://www.webcomponents.org/element/GoogleWebComponents/google-map but using parcel.

What would be the right way to do it? (or do you prefer I open a separate issue for this one?)

**Comment by mischnic** [comment]
> or do you prefer I open a separate issue for this one?

Yes, please do.
