### ISSUE TITLE
support global import?

### ISSUE THREAD

**Issue by hdriqi** [parcel-bundler/parcel#33]
Is there any support for global import just like in webpack https://webpack.js.org/plugins/provide-plugin/

and also is it possible not to transform public url ( CDN, etc )

**Comment by devongovett** [comment]
Best way to do this would be a babel plugin IMO. That way it would work across other bundlers as well, not just specific to parcel. Also means the configuration could go in a babelrc which many projects already have.

Maybe https://www.npmjs.com/package/babel-plugin-auto-import would work?
