### ISSUE TITLE
[RFC] Custom resolver?

### ISSUE THREAD

**Issue by rexxars** [parcel-bundler/parcel#330]
🙋 Feature request

It would be great if we could specify resolvers, and preferably not have to have it tied to the filesystem. For instance, being able to import from say `foo:bar:baz` and have that do an HTTP request for the result, for instance.

### 🔦 Context

I realize the following example is very specific and perhaps a bit exotic, but the basic idea of custom resolvers shouldn't be too strange a request, I think:

We've been building a "dependency injection"-like system where you can define different _parts_ of a system and have different plugins _implement_ these parts. These _parts_  can be imported using regular `import` statements , for instance (`import dateInput from 'part:form-builder/date-input'`).

The novel thing being that a certain part can be implemented by multiple plugins, where only the "most significant" plugin  implementation of that part actually gets bundled. You are also able to require _all_ the implementors of a part with a custom prefix (`import apps from 'all:app-container/app`).

We've got this working in Webpack by either resolving the part import directly to a file, or in the cast of `all:`-prefix, resolving to a in-memory JS-stub that simply exports an array of imports that point to the actual files on disk. Took a brief glance at the source for for parcel and I couldn't find any hooks that allowed us to use custom resolvers, thus this request.

Let me know your thoughts!

**Comment by davidnagli** [comment]
I think this is definitely something we should discuss. But in my opinion, the use case for this is too narrow.

**Comment by shawwn** [comment]
This is worth doing, but it will require abstracting our filesystem calls rather than using fs directly.

Luckily, I already did that. I'll submit a PR.

**Comment by rexxars** [comment]
This sounds great, @shawwn! Look forward to seeing your PR 👍

**Comment by rexxars** [comment]
@shawwn Did you ever get around to creating a PR for the resolver?

**Comment by mischnic** [comment]
Did #850 implement what you want? 


> This can also be used to alias modules that don't exist in node_modules at all:
>
>```
>{
>  "alias": {
>    "fake-module": "./some/deep/path"
>  }
>}
>```
>Now you can require('fake-module') and it will point to the path you've specified.

**Comment by DeMoorJasper** [comment]
There is aliases in parcel 1 and parcel 2 will allow custom resolvers, although you should probably avoid custom syntax as much as possible

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
