### ISSUE TITLE
Disable "You may have to save this file..." message for index.html when it does update

### ISSUE THREAD

**Issue by karlhorky** [parcel-bundler/parcel#3300]
# 🙋 Feature request

#702 introduced the message `You may have to save this file and refresh the preview to see changes`, which could be a useful tip for users!

However, it does not apply to `index.html` files in the root with both `create-react-app` and Vanilla (Parcel) templates - the content is updated without saving:

![Kapture 2019-08-01 at 16 55 51](https://user-images.githubusercontent.com/1935696/62334798-06888500-b47e-11e9-9d7f-f56dbf1415f2.gif)

In these cases it would be nice to not obscure the top two lines of the file, since everything is working as expected anyway.

## 🤔 Expected Behavior

Don't show the message if the content is indeed updating.

## 😯 Current Behavior

The message is shown if the content is updating.

## 💁 Possible Solution

**Ideal solution:** The message is only shown in the case that it is really required, in which case it can also be reworded to `Save this file and refresh the preview to see changes`.

**Alternative 1:** If this is not feasible for whatever reason, an alternative could be that the message is shown in a different position that didn't obscure the file content (maybe as a toast? or floating over top of the browser chrome somewhere?).

**Alternative 2:** A third option would be some kind of CodeSandbox setting / flag to disable this (or maybe this type of) warning, although I can understand if it doesn't match the goals of the team to introduce new options.

## 🔦 Context

I would like to offer the simplest, least distracting interface possible for students learning on the platform.

**Comment by devongovett** [comment]
did you mean to file this issue against the code sandbox repo?

**Comment by karlhorky** [comment]
🤦‍♂️Oops, yep! Opened https://github.com/codesandbox/codesandbox-client/issues/2246 for this. Sorry for the confusion!
