### ISSUE TITLE
Parcel 2: HTML inline <script> and <style> tags

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#3301]
This issue is for inline <script> and <style> support in Parcel 2's HTML transformer.

*details here*

**Comment by Scrum** [comment]
@devongovett and where are the details? maybe I could help something?

**Comment by dy** [comment]
Do I get it right that with this feature it will be possible to use import directly from inline scripts?

```js
<script type="module">
import $ from 'spect'

$`.login`.on('submit', e => {
})
</script>
```

**Comment by kwelch** [comment]
Yes, the hope is that we will be able to resolve modules.

**Comment by devongovett** [comment]
Complete.
