### ISSUE TITLE
Support "external" modules in Parcel 2

### ISSUE THREAD

**Issue by wbinnssmith** [parcel-bundler/parcel#3305]
Parcel could allow listing of "external" modules which won't be bundled.

**Comment by mischnic** [comment]
Related?: #144

**Comment by maximal** [comment]
+1 here

This keeps me from switching to Parcel on about 5 projects.

**Comment by devongovett** [comment]
@maximal what are you trying to accomplish with externals? trying to gather usecases to help inform this feature for v2.

**Comment by devongovett** [comment]
Seems like maybe there's two separate but related features here:

1. Excluding a module from a bundle, but leaving the import or require there. Use case would be for e.g. libraries with peer dependencies, builtin modules in node/electron, etc. Maybe this could be solved by excluding `peerDependencies`.
2. Mapping an import to a global variable that is available somehow. Use case would be for e.g. libraries from a cdn. This might need separate configuration, e.g. with aliases.

**Comment by charlielow** [comment]
> @maximal what are you trying to accomplish with externals? trying to gather usecases to help inform this feature for v2.

For us the need is to exclude some 3rd party modules from the bundle to avoid duplicate loading on pages where there may be more than one independent React app. 

Rather than include React / ReactDOM, let both apps share a globally available version of each of these two modules.

This also allows for browser caching of these large assets whereas if they were packaged in multiple different bundles, caching of these individual files would not be possible.

Ideally Parcel would have an option similar to Rollup's `external`

`
external: [
  'react',
  'react-dom',
  'jquery'
]
`

**Comment by ericsoco** [comment]
I think this is what I'm running into in #4003.

I'm trying to bundle a web application and it looks like the issue may be dependencies that conditionally `require` other deps, so one more vote for conditional `requires` per https://github.com/parcel-bundler/parcel/issues/3305#issuecomment-542772700.

**Comment by FreeFrags** [comment]
I noticed that #3753 was merged and closed doesnt it cover this issue or am i missing something here?

**Comment by mischnic** [comment]
https://github.com/parcel-bundler/parcel/pull/3753 isn't merged yet

**Comment by DeMoorJasper** [comment]
Can this be closed since #4072 has been merged?

**Comment by panlina** [comment]
@DeMoorJasper I'm new to Parcel. From #4072 I didn't see how `externals` is implemented. It lets you set `"react": false` but where do I specify the global name (`React`) it resolves to?

**Comment by DeMoorJasper** [comment]
@panlina apparently it doesn't, so you can ignore my comment this is not completed at all

**Comment by yonkeltron** [comment]
Ah I was also confused. Looking forward to testing this out in an upcoming alpha.

**Comment by fregante** [comment]
Wasn't this fixed by https://github.com/parcel-bundler/parcel/pull/4072?

Also, what would happen if you use `const React = require('react')` but you marked "React" as external? How do you load it? How would `require` find it?

**Comment by mischnic** [comment]
#4072 implemented "externals" as in "emitting `import React from "react";` or `const React = require("react");`", so this would be needed for libraries.

The other feature requested here are "globals".

**Comment by vazra** [comment]
> Related?: #144
> 
> (This should be done via `peerDependencies`)

@mischnic can we use this for using 'native modules' in electron app?
