### ISSUE TITLE
Parcel ignores .babelrc file

### ISSUE THREAD

**Issue by vyushin** [parcel-bundler/parcel#3312]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc
```json
{
  "presets": [
    ["@babel/preset-env", {
      "targets": [
        "> 1%",
        "IE 9",
        "not dead"
      ]
    }]
  ],
  "yo!": []
}
```

package.json
```json
{
  "name": "passfather-build",
  "version": "1.0.0",
  "description": "Build passfather package to most compatibility with browsers and Node.js",
  "author": "Evgeny Vyushin <e@vyushin.ru> (https://github.com/vyushin)",
  "contributors": [
    "Evgeny Vyushin <e@vyushin.ru> (https://github.com/vyushin)"
  ],
  "maintainers": [
    "Evgeny Vyushin <@vyushin.ru> (https://github.com/vyushin)"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/vyushin/passfather/build"
  },
  "scripts": {
    "prebuild": "rm -rf ../dist",
    "build": "parcel build ../src/passfather.js --out-dir ../dist/ --out-file passfather.min.js --target browser --no-source-maps --no-cache --global passfather",
    "prepublish": "npm run build"
  },
  "bugs": {
    "url": "https://github.com/vyushin/passfather/issues"
  },
  "homepage": "https://github.com/vyushin/passfather",
  "main": "./index.js",
  "license": "MIT",
  "keywords": [],
  "directories": {
    "doc": ""
  },
  "devDependencies": {
    "parcel": "^1.12.3"
  }
}
```

cli comman
```bash
npx parcel build ../src/passfather.js --out-dir ../dist/ --out-file passfather.min.js --target browser --no-source-maps --no-cache --global passfather
```

## 🤔 Expected Behavior

Parcel should make an error because .babelrc is invalid! If Parcel doesn't say anything, how can I be sure that it is using .bebelrc?

## 😯 Current Behavior

Parcel works silently, secretly, whithout messaging any errors.

## 💁 Possible Solution

Don't ignore .babelrc. Original Babel compiler always creates arrors if .babelrc is invalid. Try to use `@babel/core`. Something like this:
```javascript
const { transformFileAsync } = require('@babel/core');
transformFileAsync('./test.js', { 'yo!': [] });
```
you'll see in terminal that property 'yo!' is invalid.

## 💻 Code Sample

https://github.com/vyushin/passfather/tree/master/build

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 12.4.0
| npm/Yarn         | NPM 6.10.2
| Operating System | Windows 10 x64

**Comment by mischnic** [comment]
Parcel currently merges its default babel configuration (preset-env + jsx ...) with the provided babelrc. That could explain this behaviour (Parcel 2 will just use the babelrc without changes).

**Comment by vyushin** [comment]
@mischnic, thanks for answer. Waiting for Parcel 2 :)

**Comment by mischnic** [comment]
Parcel 2 prints:
`Error: Unknown option: .yo!. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.`
