### ISSUE TITLE
Support Storybook.js

### ISSUE THREAD

**Issue by jamesguan** [parcel-bundler/parcel#3321]
# 🙋 Feature request
Add configurations and support for Storybook. https://storybook.js.org/

## 🤔 Expected Behavior
Storybook works with Parceljs

## 😯 Current Behavior
Storybook works with webpack but not with Parceljs.

## 💁 Possible Solution
Parceljs supports Storybook.js

## 🔦 Context
Non of the Storybook libraries are as good as Storybook.js which is a popular way to develop front end components in isolation. I wish to use Parcel for my organization but the lack of support for popular items such as Storybook is a slight drawback.

**Comment by DeMoorJasper** [comment]
Isn't storybook build around webpack?
I don't really see how we could fix this besides helping out the storybook team once they decide to move away from webpack

**Comment by devongovett** [comment]
Either storybook needs to adopt parcel, or a storybook alternative using parcel needs to be developed. Might be good to open an issue on the storybook repo.
