### ISSUE TITLE
--no-source-maps flag makes build command miss sass mixins

### ISSUE THREAD

**Issue by dherran** [parcel-bundler/parcel#3323]
# 🐛 bug report

Adding the `--no-source-maps` flag when running `build` will make dart-sass not find mixins that are clearly there.

The issue disappears if you remove the flag from `build` but then you get a bunch of source maps that are unnecessary in production.

## 🎛 Configuration (.babelrc, package.json, cli command)

`parcel build admin.scss --no-source-maps --no-content-hash`

## 🤔 Expected Behavior

SASS should compile the file without the need for source maps.

## 😯 Current Behavior

This error:

`🚨  /mnt/c/Users/MyName/htdocs/admin.scss:2:3: Undefined mixin.                                                              ╷                                                                                                                                                        2 │   @include shadowed;                                                                                                                                     │   ^^^^^^^^^^^^^^^^^                                                                                                                                      ╵                                                                                                                                                          _general.scss 2:3  @import                                                                                                           stdin 7:9                                root stylesheet   `

## 💻 Code Sample

admin.scss

```
@import 'mixins';
@import 'general';
```

_mixins.scss

```
@mixin shadowed() {
  box-shadow: 0 2px 4px rgba(0,0,0,0.2), 0 -1px 0px rgba(0,0,0,0.02);
}

```
_general.scss

```
.dropdown-pane {
  @include shadowed;
}

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.16.0
| npm/Yarn         | 1.17.3
| Operating System | Windows 10 1903 running Ubuntu 16.04 via WSL

**Comment by mischnic** [comment]
The example you provided work for me with and without `--no-source-maps`,
resulting in :
```css
.dropdown-pane{box-shadow:0 2px 4px rgba(0,0,0,.2),0 -1px 0 rgba(0,0,0,.02)}
```

**Comment by dherran** [comment]
@mischnic You're right. It works in the root folder. It fails however when you move the 3 sass files into a folder, like so:

/test/_general.scss
/test/_mixins.scss
/test/admin.scss

`parcel build test/admin.scss --no-content-hash --no-source-maps`

**Comment by mischnic** [comment]
Can't reproduce: https://github.com/mischnic/parcel-issue-3323-sass-mixin-sourcemap

**Comment by dherran** [comment]
@mis

**Comment by mischnic** [comment]
(To make this show up in the search:
Adding a .sassrc with 
```js
{
  "includePaths": [
    "node_modules/font-awesome/scss"
  ]
}
```
caused this)
