### ISSUE TITLE
Retaining src folder structure when building to dist

### ISSUE THREAD

**Issue by GrantBartlett** [parcel-bundler/parcel#3325]
# 🙋 Feature request

To provide an option to retain the `src` structure of a project when taking it over to a `dist` build.  

## 🤔 Expected Behavior

**Takes the src structure:**
```
-src
--assets
---images
---fonts
---stylesheets
```

**And outputs:**
```
-release
--assets
---images
---fonts
---stylesheets (Probably a compiled app.css at this point)
```

## 😯 Current Behavior
```
-release
-image.png
-font.ttf
-app.css
-index.html
```

## 🔦 Context

Having everything flat structured isn't great for keeping things organised.

**Comment by saulfautley** [comment]
There are several duplicates of this already #233 #2755 #2869

See https://github.com/parcel-bundler/parcel/issues/2755#issuecomment-478262913

**Comment by VladimirMikulic** [comment]
@GrantBartlett it's been a while, but I've developed a plugin that solves this issue.
https://github.com/VladimirMikulic/parcel-plugin-custom-dist-structure

I would appreciate your feedback on it.
Thanks.
