### ISSUE TITLE
How to disable custom asset type ? 

### ISSUE THREAD

**Issue by gterras** [parcel-bundler/parcel#3330]
# ❔ Question

Is there some way to disable a custom asset type before bundle? Like `bundler.removeAssetType()`? Or override the extension with another asset type? 

## 🔦 Context

I am using the Nunjucks parcel plugin (https://github.com/chocolateboy/parcel-plugin-nunjucks) to handle `njk` extension. I a few specific situations I need the `njk` entry file to be processed like a regular HTML file. I get the exact output I need when copying the entry file and changing the extension to `html` (but then I lose HMR of course since the file is not watched ). 

## 💻 Code Sample

I thought overriding the extension with `bundler.addAssetType('njk', 'node_modules/parcel-bundler/src/assets/HTMLAsset')` would work but it's not the case. 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.15.2
| npm/Yarn         | 6.10.2
| Operating System | Linux 4.19 Debian

**Comment by mischnic** [comment]
>  I thought overriding the extension with `bundler.addAssetType` would work

It should, `addAssetType` blindly overrides anything that's already registered:

https://github.com/parcel-bundler/parcel/blob/96119be782d9d551f73b77e06ab25067c7073344/packages/core/parcel-bundler/src/Parser.js#L63-L69

Are you sure your call happens *after* the Nunjucks plugin is registered and your config isn't overridden by that plugin?

**Comment by gterras** [comment]
Hi, 

That was that, thanks a lot !
