### ISSUE TITLE
JSTransformer: Include node globals inserted by prior transforms

### ISSUE THREAD

**Issue by wbinnssmith** [parcel-bundler/parcel#3336]
Perform a check similar to #3334 and always traverse ASTs if they're dirty

**Comment by mischnic** [comment]
> Include node globals

Like `Buffer`? We should provide a way to turn this feature off, maybe the user wants to use their own Polyfill. (https://github.com/parcel-bundler/parcel/issues/2833#issuecomment-509262170)

**Comment by mischnic** [comment]
The recent AST refactoring implemented this. But we still want a test
