### ISSUE TITLE
RFC: Rich, actionable errors in Parcel 2

### ISSUE THREAD

**Issue by gorakong** [parcel-bundler/parcel#3337]
# 💬 RFC

## 🔦 Context

Currently Parcel 2 has a few shortcomings in its error reporting:

* Babel errors are repeated, include a parser stacktrace, and aren't colored correctly. They also aren't clickable to the exact row and column the error occurred.
* Resolver errors don't include a code frame like they did in Parcel 1.
* We have the context and information to provide resolver errors like Rome does in https://twitter.com/sebmck/status/1150878549441572864

## 💻 Examples

Rome's resolver errors:

![](https://user-images.githubusercontent.com/15333808/62805094-d48da900-baa3-11e9-8f31-017a534fb027.png)

[VSCode's Diagnostic structure](https://code.visualstudio.com/api/references/vscode-api#Diagnostic)

## Proposal

Let's create a single standard error type that can describe any type of code-related error that can occur in Parcel so it can be shown in a rich, actionable way:

```js
type Diagnostic = {|
  message: string | Array<
    | string
    | {|type: 'filePath', value: FilePath|}
    | {|type: 'message', value: string, style?: 'emphasis'|}
  >
  severity: 'error' | 'warning' | 'info',
  codeFrame?: CodeFrame
|}

class ParcelError extends Error {
  source: string, // Name of the plugin or component that caused the error
  diagnostics: Array<Diagnostic>

  constructor({diagnostics: Array<Diagnostic>, source: string});
}
```

Here's an example:

```js
throw new ParcelError({
  source: 'resolver',
  diagnostics: [{
    severity: 'error',
    message: [
      'failed to resolve', 
      {type: message, value: "'./foo'", style: 'emphasis'}, 
      'from', 
      {type: 'filePath', value: '/Users/gora/parcel/bar.js'},
    ],
    codeFrame: // Code frame showing the failing import
  }]
});
```

This way, the appropriate UI interface can display this error as it would like. Since reporters receive these, they can be mapped to terminal uis, web pages, IDEs, etc.

Alternatives: Instead of providing a babel-style code frame (or maybe optionally instead of providing a code frame), we could accept a filePath and row/column tuple and create the codeframe at the view layer.

Once we decide on a direction, I'm happy to take on an implementation.

cc @devongovett @wbinnssmith @padmaia @mischnic @DeMoorJasper @sebmck @jamiebuilds

**Comment by jamiebuilds** [comment]
I don't think @sebmck will mind me sharing this gist he made for me awhile ago...

This is the type interface for diagnostics in Rome https://gist.github.com/sebmck/13a02b60095767b978e8124c326626f3

**Comment by kwelch** [comment]
I like the idea of returning path/row/column and then we can build in reporters that handle the generic data and can decide if they want to display as a code frame. 

This that jump out from the Rome types that I really like, 
- Fixable
- Advice (specifically Actionable advice) [personally that feel similar to fixable, but has choices on how to fix I imagine.]
- Language (this is important since we are handling a load of different file types, it could spot something simple as not interpreting the file as the correct type.)

I think fixable and advice are things we can build up to.
