### ISSUE TITLE
react component library

### ISSUE THREAD

**Issue by konsumer** [parcel-bundler/parcel#3338]
# ❔ Question

How do I package a react component with parcel as a library others can install with npm?

## 🔦 Context

I am trying to work out how to package a [react component](https://github.com/konsumer/react-directional) with parcel. I am, aware of rollup and microbundle, but I'd like to be able to use the same non-config I use in the demo to package the lib. I think maybe the issue is that I need to mark react as an external dependency, but I'm not sure how to do this.

## 💻 Code Sample

```js
import React from 'react'
import { render } from 'react-dom'
import Directional from 'react-directional'

console.log(Directional)

const App = () => {
  return (<Directional />)
}

render(<App />, document.getElementById('root'))
```

the `Directional` is just an empty object, and it results in this error:

```
src.e31bb0bc.js:37 Uncaught Error: Cannot find module 'react'
    at newRequire (src.e31bb0bc.js:37)
    at localRequire (src.e31bb0bc.js:53)
    at f (index.js:1)
    at p (index.js:1)
    at Object.parcelRequire.Focm../look.svg (index.js:4)
    at f (index.js:1)
    at parcelRequire.P1GY (index.js:1)
    at Object.parcelRequire.../node_modules/react-directional/dist/index.js (index.js:1)
    at newRequire (src.e31bb0bc.js:47)
    at localRequire (src.e31bb0bc.js:53)
```
* In my component-lib, I have react set as a `peerDependencies`
* I am doing `parcel build --target node src/index.js` in the component-lib, but I tried it without `--target node` and it had the same issue.
* In my parent-app, I have react added as a dep, it just doesn't seem to pick it up.

In parent app, if I run `npm ls react`, I get this:

```
robot-controller@0.0.0 /home/konsumer/Documents/WORKSPACE/robot-controller
└── react@16.9.0 
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3 |
| Node             | 12.8.0 |
| npm/Yarn         | 6.10.3 |
| Operating System | Pop!_OS (basically Ubuntu) 19.04 |

**Comment by konsumer** [comment]
The reason I want to avoid other lib-packagers is that they all require a bunch of config to make them output a library, and I just love how simple the demo is, with very little config. microbundle looked promising, but I had [this issue](https://github.com/developit/microbundle/issues/462) whichj indicates it seems to have a problem with JSX. I love parcel for making apps, and it'd be rad if it worked the same for the lib.

**Comment by konsumer** [comment]
They helped me over at microbundle issue, so I think I have a workable solution, but I am still curious if there is a way to use just parcel config. It'd be easier to not have to pre-render the SVG to package it, and just use `@svgr/parcel-plugin-svgr`

**Comment by mischnic** [comment]
> I think maybe the issue is that I need to mark react as an external dependency

> I have react set as a `peerDependencies`

This is the logical way to do it and how Parcel 2 will handle this, but for now that isn't possible.

Follow this issue for updates on that: #3305
