### ISSUE TITLE
🐛 Parcel does not minify built-ins (prelude.js)

### ISSUE THREAD

**Issue by bartw** [parcel-bundler/parcel#334]
🐛 bug report

When I create a simple html and js like in the hello-world example and run "parcel build src/index.html" or "parcel build src/index.js", the html and js get bundled but only the html is minified, not the js.

### 🤔 Expected Behavior
I expect parcel to minify my js for a production build.

### 😯 Current Behavior
The js is not minified

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Parcel           |  1.2.0
| Node             | 9.3.0
| npm/Yarn         |  npm 5.6.0
| Operating System | Ubuntu 17.10 and Windows 10

### Github repo with my code

https://github.com/bartw/hello-parcel

**Comment by DeMoorJasper** [comment]
Parcel does minify JS, minified version i got when running build of ur script was:
```
var t="123";const s="test2",a=665;
```
Currently minifying does not happen on the piece of JS Parcel includes every time because that doesn't get parsed

**Comment by bartw** [comment]
@DeMoorJasper where did the console.log statements end up?

**Comment by DeMoorJasper** [comment]
They get removed, why would you want console.log in build?

**Comment by bartw** [comment]
Sorry, you are correct.

**Comment by davidnagli** [comment]
> Currently minifying does not happen on the piece of JS Parcel includes every time because that doesn’t get parsed

Can you elaborate on that this @DeMoorJasper? Not fully understanding…

**Comment by nfantone** [comment]
Probably related: what I'm seeing happening is that the `require` polyfill that precedes the actual app code is _not_ minified, while the rest _is_.

So the build output (after `parcel build index.js`) becomes:

```js
// modules are defined as an array
// [ module function, map of requires ]
//
// map of requires is short require name -> numeric require
//
// anything defined in a previous bundle is accessed via the
// orig method which is the require for previous bundles

require = (function (modules, cache, entry) {
  // Save the require from previous bundle to this closure if any
  var previousRequire = typeof require === "function" && require;

  function newRequire(name, jumped) {
    if (!cache[name]) {
      if (!modules[name]) {
        // if we cannot find the module within our internal map or
        // cache jump to the current global require ie. the last bundle
        // that was added to the page.
        var currentRequire = typeof require === "function" && require;
        if (!jumped && currentRequire) {
          return currentRequire(name, true);
        }

// ... unminified content continues <----

// Override the current require with this new one
  return newRequire;

// Beginning of uglyfied code <-------------- 
})({6:[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});const e=e=>btoa(JSON.stringify(e)),t=t=>encodeURIComponent(e(t));exports.default=t;

// ...
```

**Comment by DeMoorJasper** [comment]
@nfantone That's exactly what this is, tnx for adding a code example :)
@davidnagli look at the comment above, for the perfect explanation

**Comment by ssuman** [comment]
@DeMoorJasper I moved the minification from JSAsset to JSPackager. This seems to minify the prelude.js as well. But post minification, the module/filenames should be kept the same. I think the reason being 

```
function loadJSBundle(bundle) {
  return new Promise(function (resolve, reject) {
    var script = document.createElement('script');
    script.async = true;
    script.type = 'text/javascript';
    script.charset = 'utf-8';
    **script.src = bundle;**
  });
```
loadJSBundle needs the correct name to load the module name from the server. Any suggestions ?
