### ISSUE TITLE
HTMLAsset : allow getAttrDepHandler to return false

### ISSUE THREAD

**Issue by gterras** [parcel-bundler/parcel#3348]
# 🙋 Feature request

The `collectDependencies` method in `HTMLAsset` is painful to override (80 lines + 3 long constants). In many cases it is easy to override one of the short method of the class. I'm in a case where I need to control which `src` attribute get processed and need to create a 150 lines script and potentially miss future updates to the asset file (overriding `collectDependencies`). Having `getAttrDepHandler` (a 4 lines method) to return false would be way easier. 

## 🤔 Expected Behavior

`getAttrDepHandler` is allowed to return false. `collectDependencies` checks for a value before updating node attribute.

## 😯 Current Behavior

Node attribute is unconditionally updated with the result of `getAttrDepHandler`.

## 💁 Possible Solution

Current state : 

https://github.com/parcel-bundler/parcel/blob/96119be782d9d551f73b77e06ab25067c7073344/packages/core/parcel-bundler/src/assets/HTMLAsset.js#L184-L193

Would this be acceptable?

```
let depHandler = this.getAttrDepHandler(attr, attrVal); 
if (!depHandler)
continue;
```

Allowing to get an easy override to control what attribute gets processed : 

```
getAttrDepHandler(attr, attrVal) {
  if(!myLogic)
   return
  if (attr === 'srcset') {
    return this.collectSrcSetDependencies;
  }
  return this.processSingleDependency;
}
```

## 🔦 Context

I am outputting unprocessed (raw) Twig-like templates for post build processing. Any element with a `src` attr will still be processed when it shouldn't (something like `<img src="{{ myImage }}">` will trigger a file not found error). I am currently doing this check before calling `depHandler` in the `collectDependencies` method. It would be cleaner to do it in directly in the `getAttrDepHandler` method.

**Comment by mischnic** [comment]
(The pipeline model with plugins in Parcel 2 doesn't makes this any easier, @devongovett )

**Comment by gterras** [comment]
Hi, could a Parcel2 PR be accepted on this ?

**Comment by devongovett** [comment]
Could you provide a bit more detail on what you’re trying to accomplish? Generally, overriding class methods is a bad idea for all the reasons you said.

**Comment by gterras** [comment]
The goal is to be able to control which attribute gets processed (see Context for more info) in an easier fashion. I understand this might not be a common need but it could fix many edge cases. The change is small (+2 lines) with no consequence and fits very well with the "full control" vision of Parcel2. What do you think ?

**Comment by devongovett** [comment]
Closing since this was an issue in Parcel 1
