### ISSUE TITLE
Is it possible to move config files (posthtml, terser, etc) to a specific folder ?

### ISSUE THREAD

**Issue by gterras** [parcel-bundler/parcel#3349]
# ❔ Question

Is there a way to store config files (posthtml, postcss, terser...) in a `config` folder instead of root folder ? Thanks. 

## 🔦 Context

I have configuration files for quite a few libs and my root folder is messy. 

## 💻 Code Sample

irrelevant 

## 🌍 Your Environment

irrelevant

**Comment by DeMoorJasper** [comment]
Currently not but it might be a feature in the future although I doubt it as we’re pretty zero config.
The more common approach is having a folder for your code and using the root for all config

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gterras** [comment]
Thanks for the answer, I understand the point about complexity (what if it was either root or an `config` folder?) although in terms of popularity I'm pretty sure it would not be used less than `outDir`.

**Comment by devongovett** [comment]
These config files are generally not owned by parcel (eg .babelrc), so we simply resolve them the same way as the original tool does.
