### ISSUE TITLE
Parcel 2: GLSL transformer

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#3352]
Create the `@parcel/transformer-glsl` package in `packages/transforms/glsl`. This package is a Parcel 2 transform plugin for GLSL. It should be based on the `GLSLAsset` from Parcel 1.

The `@parcel/transformer-glsl` package is responsible for the following things:

* Collecting dependencies in GLSL files using `glslify-deps` and resolving with the Parcel resolver.
* Bundling dependencies with `glslify-bundle` and exposing as JavaScript
* Remove unneeded whitespace

We could also reconsider the way this works, and split this into actual Parcel plugins for each part:

* A transformer to collect deps for the immediate asset (not any children)
* A packager to combine those assets together
* Some way of inlining the result into JS if needed (perhaps an inline packager, similar to HTML)

This would have the benefit of allowing packaging GLSL to an output GLSL file, or inline into some other language besides JS as well. Perhaps the infra developed for #3301 will be useful here as well.

**Comment by Drapegnik** [comment]
I would like take this
