### ISSUE TITLE
Parcel 2: JSONLD transformer

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#3355]
Create the `@parcel/transformer-jsonld` package in `packages/transforms/jsonld`. This package is a Parcel 2 transform plugin for JSONLD. It should be based on the `JSONLDAsset` from Parcel 1.

The `@parcel/transformer-jsonld` package is responsible for the following things:

* Parsing and collecting dependencies
* Rewriting urls to dependencies
* Compiling back to JSON

**Comment by dreamorosi** [comment]
Hi, I’d like to try work on this as my first issue if it’s still non taken!

**Comment by DeMoorJasper** [comment]
@dreamorosi awesome, you can work on it. Let us know if you need any help :)

**Comment by sharat9211** [comment]
Hello, If nobody is working on it, I would like to give it a try.

**Comment by DeMoorJasper** [comment]
@sharat9211 feel free to work on it, does not seem like anyone is working on it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sharat9211** [comment]
@DeMoorJasper Any steps to get me started quickly?

**Comment by DeMoorJasper** [comment]
@sharat9211 you could have a look at the v1 JSONLD transformer https://github.com/parcel-bundler/parcel/blob/1.x/src/assets/JSONLDAsset.js and at some of the v2 transformers, probably a good idea to start with a simple one like json and try and get jsonld working from there. Once you've reached a point where it works open up a PR or draft PR and we'll see if it needs any additional changes.

**Comment by sharat9211** [comment]
@DeMoorJasper Sounds good. Just by random chance, I had also started looking at json transformer. So already off to a good start. :)

**Comment by isaacadams** [comment]
I can take this on if no one else is working on it.

**Comment by DeMoorJasper** [comment]
@isaacadams nobody has opened a PR so far so feel free to implement this

**Comment by isaacadams** [comment]
@DeMoorJasper I have submitted a PR and have described 4 issues before it can be considered ready. Do you or anyone else have time to review the issues I described? I am having some trouble getting them resolved.
