### ISSUE TITLE
Parcel 2: Kotlin transformer

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#3356]
Create the `@parcel/transformer-kotlin` package in `packages/transforms/kotlin`. This package is a Parcel 2 transform plugin for Kotlin. It should be based on the `KotlinAsset` from Parcel 1.

The `@parcel/transformer-kotlin` package is responsible for the following things:

* Compiling Kotlin to JS with `@jetbrains/kotlinc-js-api`
* Collecting all files referenced in the code so that Parcel watches them (not currently supported in Parcel 1)
* Generating source maps

**Comment by DeMoorJasper** [comment]
Do we really want this?
Seems like there's no way to know what assets to watch, the webpack plugin just uses globs and does not even use the official webpack watcher as far as I can tell. Seems pretty hacky for something that has a very small userbase.

Maybe not something we want to support as an official plugin

**Comment by max-kammerer** [comment]
Hi @devongovett, @DeMoorJasper! I'm not expert in JS world and not everything is clear from this and related discussions and prs. Could you clarify what is required from Kotlin/JS side to unblock integration with Parcel?

**Comment by mischnic** [comment]
For a Parcel transformer, we need some compiler function that takes as an input
- the Kotlin file that should be translated into JS 

and returns 

- the output JS file
- all files in the project that influenced how the translation worked (config files, other Kotlin files that were imported by the "entry" Kotlin file from above), so that Parcel known when the Kotlin compiler API has to be called again. `@jetbrains/kotlinc-js-api` didn't return this


<br>


Then this would be possible (assuming that Kotlin/JS has this concept of exporting functions from Kotlin to JS) with Parcel:
```js
import {someExportedKotlinFunction} from "./utils.kt";

console.log(someExportedKotlinFunction());
```
or (only run `fun main` and use some fully-contained web framework)
```html
<div id="app-root"></div>
<script src="main.kt" type="module"></script>
```

**Comment by max-kammerer** [comment]
@mischnic Thank you for clarification!

As I know in current approach Kotlin/JS compiles all Kotlin files in same module into single JS file. 

>all files in the project that influenced how the translation worked (config files, other Kotlin files that were imported by the "entry" Kotlin file from above), so that Parcel known when the Kotlin compiler API has to be called again. @jetbrains/kotlinc-js-api didn't return this

As I understand you mostly speak here about incremental compilation. That's require some api from Kotlin/JS side (with additional pass of  Kotlin compiler intermediate state)? Is it correct? 

How this is fitting to Parcel model/approach?

**Comment by mischnic** [comment]
It's not ideal, but works just fine (compiling multiple files into a single file is also done for Elm and Sass).
This is more about cache invalidation than incremental compilation (so that Parcel known when that single JS file from Kotlin has to be regenerated)

**Comment by devongovett** [comment]
Going to close this. I don't have the bandwidth to implement and maintain this. It would be great as a third party plugin if someone wants to build it!
