### ISSUE TITLE
Parcel 2: Markdown transformer

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#3357]
Create the `@parcel/transformer-markdown` package in `packages/transforms/markdown`. This package is a Parcel 2 transform plugin for markdown. It should be based on the `MarkdownAsset` from Parcel 1.

The `@parcel/transformer-markdown` package is responsible for the following things:

* Compiling markdown to HTML using `marked`

**Comment by JosephMart** [comment]
I am interested interested in working on this!

**Comment by devongovett** [comment]
Awesome @JosephMart! Let us know if you have any questions.

**Comment by kirillrogovoy** [comment]
Here's some code that does a bunch of stuff already with Markdown:
https://github.com/parcel-bundler/parcel/pull/2882

We could rewrite it as a transformer and there you go. @JosephMart wanna pair up on that?

**Comment by TLATER** [comment]
https://github.com/jonathantneal/posthtml-md can be used for some limited support in html being bundled with parcel :)

**Comment by joshocalico** [comment]
It's also worth mentioning that there exists a MDX transformer for those of you using React.
I'm assuming the work required isn't too bad so I might try throwing something together in the next couple of days for those after plain old markdown.

**Comment by pspeter3** [comment]
It seems like a transformer here could actually be used for static site generation. Could the transformer also resolve a template function that wraps the resulting HTML?

**Comment by jaywcjlove** [comment]
Use [`parcel-transformer-markdown`](https://www.npmjs.com/package/parcel-transformer-markdown).

@devongovett

**Comment by TechQuery** [comment]
You can also use my plugin for MDX 3: https://github.com/EasyWebApp/Parcel-transformer-MDX

**Comment by iacore** [comment]
There's also [`parcel-transform-remark`](https://github.com/mvasigh/parcel-transform-remark), although it seems to have the wrong name.

**Comment by devongovett** [comment]
Going to close this. I don't have the bandwidth to implement and maintain this. It would be great as a third party plugin if someone wants to build it!
