### ISSUE TITLE
Parcel 2: SugarSS transformer

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#3360]
Create the `@parcel/transformer-sugarss` package in `packages/transforms/sugarss`. This package is a Parcel 2 transform plugin for [SugarSS](https://github.com/postcss/sugarss). It should be based on the `SSSAsset` from Parcel 1.

The `@parcel/transformer-sugarss` package is responsible for the following things:

* Compiling SugarSS to CSS using PostCSS

**Comment by ZWkang** [comment]
can i try this?

**Comment by DeMoorJasper** [comment]
@ZWkang yes, let us know if you have any questions
