### ISSUE TITLE
Parcel 2: Web Manifest transformer

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#3362]
Create the `@parcel/transformer-webmanifest` package in `packages/transforms/webmanifest`. This package is a Parcel 2 transform plugin for web manifests. It should be based on the `WebManifestAsset` from Parcel 1.

The `@parcel/transformer-webmanifest` package is responsible for the following things:

* Parsing JSON
* Collecting dependencies
* Rewriting urls
* Generating JSON

We currently only handle the `.webmanifest` extension, but many people want to be able to use `.json` as well (#235, #1039). In order to support this, we need a way for the HTML transformer to specify that the dependency should be treated as a `webmanifest` file regardless of its actual extension.

**Comment by Drapegnik** [comment]
Hi, @devongovett! I would like take this

**Comment by devongovett** [comment]
@Drapegnik awesome! Let us know if you have any questions.

**Comment by Dagge1** [comment]
Any news on this? I still have to manually copy manifest.json to /dist folder and change manifest <link> in /dist index.html to manifest.json. But whenever I make change parcel changes this link back to manifest.js Pls find a solution soon a s possible because this is quite a bad situation and I have seen this issue is lagging for more than a year and is still unresolved. Using .webmanifest definitively isn't proper solution, because it's not a convention and it may break code elsewhere

**Comment by mischnic** [comment]
Yes, I have opened a new PR for this today: https://github.com/parcel-bundler/parcel/pull/4313

**Comment by Banou26** [comment]
Is this PR gonna address web extensions(#1039) as well ?

**Comment by 101arrowz** [comment]
For anyone who needs Web Manifest support before the transformer is added into the core package, I've developed a plugin [`parcel-config-pwa-manifest`](https://github.com/101arrowz/pwa-manifest/packages/parcel-config-pwa-manifest). It doesn't add support for `manifest.json` or `manifest.webmanifest`, but rather generates a manifest and injects the HTML tags in using config you provide.

**Comment by 101arrowz** [comment]
For those who need support for web manifests right now, I've made a plugin [`parcel-config-pwa-manifest`](https://npmjs.com/package/parcel-config-pwa-manifest). It doesn't add support for `manifest.webmanifest` but rather generates one from options you provide.

**Comment by buzinas** [comment]
@Drapegnik are you still looking into this?

**Comment by Drapegnik** [comment]
@buzinas, no, now it's https://github.com/parcel-bundler/parcel/pull/4313 by @mischnic

**Comment by toastal** [comment]
I could use this too. I've been trying to make a transformer from [Dhall to Webmanifest](https://www.npmjs.com/package/@toastal/parcel-transformer-dhall-webmanifest) (via JSON). I would have thought changing the type in the transformer would have been enough but the URLs never get resolved.
