### ISSUE TITLE
Parcel 2: YAML transformer

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#3363]
Create the `@parcel/transformer-yaml` package in `packages/transforms/yaml`. This package is a Parcel 2 transform plugin for YAML. It should be based on the `YAMLAsset` from Parcel 1.

The `@parcel/transformer-yaml` package is responsible for the following things:

* Parsing YAML
* Generating JavaScript

**Comment by karansapolia** [comment]
Hey @devongovett, I think I can work on this one too along with the htmlnano transformer. Working on both of them together should not take a lot of time. I would like to take this one up too :slightly_smiling_face:

**Comment by Drapegnik** [comment]
Hi, @karansapolia, are you planning on doing this or can I take it?
