### ISSUE TITLE
Parcel 2: htmlnano optimizer

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#3366]
Create the `@parcel/optimizer-htmlnano` package in `packages/optimizers/htmlnano`. This package is a Parcel 2 optimizer plugin for HTML. It should be based on the htmlnano transform from Parcel 1.

The `@parcel/optimizer-htmlnano` package is responsible for the following things:

* Loading htmlnano config from `.htmlnanorc` and `.htmlnanorc.js`
* Applying PostHTML with the htmlnano plugin to minify HTML

**Comment by karansapolia** [comment]
Hey @devongovett I would like to work on this :slightly_smiling_face:

**Comment by devongovett** [comment]
@karansapolia excellent! Let us know if you have questions. 😄

**Comment by karansapolia** [comment]
Just giving a heads up here. Was involved in some work last week. Starting work on this one now :smile:

**Comment by vvni** [comment]
TODO?

**Comment by karansapolia** [comment]
> TODO?

Working on it. Intend to send a PR in 8 hrs :sweat_smile:

**Comment by gonzarodriguezt** [comment]
Hey! @karansapolia you're actively working on this? If not, i would like to send a PR :)

**Comment by karansapolia** [comment]
> Hey! @karansapolia you're actively working on this? If not, i would like to send a PR :)

Feel free to do so :+1:
