### ISSUE TITLE
Only one JS file is used when files have identical content in prod build

### ISSUE THREAD

**Issue by msrch** [parcel-bundler/parcel#3368]
# 🐛 bug report

When you have JS files that have identical content or the content ends up being identical after minification, the output file contains only one file. This only happens in prod build. The dev build contains all files bundled as expected.

This bug has impact on libraries like for example **Material UI** where it breaks some functionality after prod build.

## 🎛 Configuration (.babelrc, package.json, cli command)

No config, all defaults

## 🤔 Expected Behavior

Prod bundle should contain all imported files.

## 😯 Current Behavior

Prod build bundles files of the same content as single file - points to the same id (in the example below `w6k5`).

```javascript
({
    "w6k5": [function(require, module, exports) {
        "use strict";
        Object.defineProperty(exports, "__esModule", {
            value: !0
        }),
        exports.default = void 0;
        var e = Math.random()
          , t = e;
        exports.default = t;
    }
    , {}],
    "Focm": [function(require, module, exports) {
        "use strict";
        var e = u(require("./first"))
          , r = u(require("./second"));
        function u(e) {
            return e && e.__esModule ? e : {
                default: e
            }
        }
        console.log(e.default, r.default);
    }
    , {
        "./first": "w6k5",
        "./second": "w6k5"
    }]
}, {}, ["Focm"], null)
```

However after logging asset values from `node_modules/parcel-bundler/src/transforms/terser.js` it returns different `id`s for the `asset`s even though they do have the same content.

```
id: w6k5
file name: /Users/msrch/tmp/parcel-bug/src/first.js

"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=Math.random(),t=e;exports.default=t;

---

id: HJNh
file name: /Users/msrch/tmp/parcel-bug/src/second.js

"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=Math.random(),t=e;exports.default=t;
```

There is a workaround for when the file content identity is a result of minification - use the `.terserrc` with `{ "mangle": false }` which "fixes" the problem however the `.terserrc` options are not applied to anything in `node_modules`. So if the problem effects one the dependencies this will not work unless the `.terserrc` is manually coped from project root to the dependency folder inside `node_modules`.

## 💻 Code Sample

`first.js`

```javascript
const firstInstance = Math.random()
export default firstInstance
```

`second.js`

```javascript
const secondInstance = Math.random()
export default secondInstance
```

`index.js`

```javascript
import first from './first'
import second from './second'
console.log(first, second)
```

In dev build the two values are different as expected. In prod build they are the same since both imports are pointing to the same module.

## 🔦 Context

It is quite common to create React context per file - example being Material UI and the `Table` component which is using two contexts:

* https://github.com/mui-org/material-ui/blob/v4.3.2/packages/material-ui/src/Table/TableContext.js
* https://github.com/mui-org/material-ui/blob/v4.3.2/packages/material-ui/src/Table/Tablelvl2Context.js

And then using them as two separate contexts - https://github.com/mui-org/material-ui/blob/v4.3.2/packages/material-ui/src/TableCell/TableCell.js#L7-L8

After prod build this results in sharing one context for two different functionalities thus breaking functionality.

Snippet from prod build file pointing to the same `id` issue as described in previous sections:

```javascript
"../Table/TableContext": "91CL",
"../Table/Tablelvl2Context": "91CL"
```

Related console log from the transformer:

```
id: 91CL
file name: /Users/msrch/tmp/parcel-bug/node_modules/@material-ui/core/esm/Table/TableContext.js null

"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=t(require("react"));function t(e){return e&&e.__esModule?e:{default:e}}var r=e.default.createContext(),u=r;exports.default=u;

id: BC6F 
file name: /Users/msrch/tmp/parcel-bug/node_modules/@material-ui/core/esm/Table/Tablelvl2Context.js null

"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=t(require("react"));function t(e){return e&&e.__esModule?e:{default:e}}var r=e.default.createContext(),u=r;exports.default=u;
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 11.13.0
| npm         | 6.7.0
| Operating System | macOS

**Comment by mischnic** [comment]
The hash is based on the files contents, so this is actually not surprising (but obviously wrong).

This works correctly in Parcel 2 (alpha 1 was just published) and also with Parcel 1 and `--experimental-scope-hoisting`.

**Comment by wojtekmaj** [comment]
I'm not sure how connected this is, but I think it's important and should be handled well in Parcel 2.

Consider a main chunk which has an import() which creates another chunk. The latter chunk changes, resulting in a new hash, for example `child.78399e21.js`. Main chunk now should point to the new child chunk, but a new child hash doesn't change parent hash, which may cause some users to load older, cached main chunk and consequentially, old child chunk.

**Comment by mischnic** [comment]
@wojtekmaj I don't think this is connected. The issue here is that the asset hash is computed solely based on the file contents (and not the path).
