### ISSUE TITLE
🐛 Help page incomplete

### ISSUE THREAD

**Issue by rondonjon** [parcel-bundler/parcel#337]
### 😯 Current Behavior

When running 'parcel-bundler -h' in the terminal, the list of available options/modes is incomplete. The output shows only the options for watch/devserver mode.

### 💁 Possible Solution

The usage page should cover all available execution modes, including production builds. To avoid confusion, a brief summary would be sufficient. For suboptions, users should then ask more specifically, e.g. 'parcel-bundler build --help'

This is also how other complex tools (e.g. git) handle it.

**Comment by brandon93s** [comment]
This is intentional. `parcel help` lists out available commands, and help for those commands can be found with `parcel [command] help`.

```shell
$ parcel help

Usage: cli [options] [command]

  Options:

    -V, --version  output the version number
    -h, --help     output usage information


  Commands:

    serve [options] [input]  starts a development server
    watch [options] [input]  starts the bundler in watch mode
    build [options] [input]  bundles for production
    help [command]           display help information for a command

  Run `parcel help <command>` for more information on specific commands

$ parcel help build

  Usage: build [options] [input]

  bundles for production


  Options:

    -d, --out-dir <path>  set the output directory (default: dist)
    --public-url <url>    set the public URL to serve on. defaults to the same as the --out-dir option
    --no-minify           disable minification (default: true)
    --no-cache            disable the filesystem cache (default: true)
    -h, --help            output usage information
	
``
