### ISSUE TITLE
Not clear how to use a package that defines it's own require fn

### ISSUE THREAD

**Issue by wires** [parcel-bundler/parcel#3372]
# ❔ Question

I am trying to use a JS library, that defines it's own `require' method. What are the options?

## 🔦 Context

From the readme of the library in question https://github.com/larsgw/citation.js

> Browser releases are available [here](https://github.com/larsgw/citation.js/tree/archive). These define `require` and add `citation-js` as a module.
> ```
> <script src="path/to/citation.js" type="text/javascript"></script>
> <script>
>  const Cite = require('citation-js')
> </script>
> ```

They provide their own `require` function that you are supposed to use and they also use this their own sources.

If I use the `npm` version of the library with parcel, I somehow end up with a not fully working version of the library.

I consider this bad practise myself, but regardless I'd like to use the browser version of this library with parcel. What are the options?

## 💻 Code Sample

Here is a working example,
https://gist.github.com/wires/0ac35393ad94aab78c0067088c848319

- if you just serve this file without parcel, it works
- if you remove the first `<script>` tag from the index and then `parcel serve index.html`, you will see that the code no longer runs

(check the console)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3 |
| Node             | v11.7.0 | 
| npm/Yarn         | 6.9.0 |
| Operating System | Mac OSX |

**Comment by mischnic** [comment]
> If I use the npm version of the library with parcel, I somehow end up with a not fully working version of the library.

Could you please create a code sample for that and also post the error/failure mode

Using their "brower build" from within Parcel isn' going to work

**Comment by wires** [comment]
The linked gist demonstrates the problem.
https://gist.github.com/wires/0ac35393ad94aab78c0067088c848319

I've updated it to include an `npm start` script; anyway:

1. If you just open the unmodified `index.html` file in a browser, it requires the bundle from CDN and that provides a `require` method so the `index.js` file works without bundling. You see a citation printed in the console:

```
Birol, I., Raymond, A., Jackman, S. D., Pleasance, S., Coope, R., Taylor, G. A., … Jones, S. J. M. (2013). Assembling the 20 Gb white spruce (Picea glauca) genome from whole-genome shotgun sequencing data. Bioinformatics, 29(12), 1492–7. https://doi.org/10.1093/BIOINFORMATICS/BTT178
```

2. If you instead run `parcel serve index.html`, this will use the NPM version but it prints this error in the JS console

```
Uncaught TypeError: Cannot read property 'system_id' of undefined
    at engines.js:15
    at CSL.Blob.<anonymous> (engines.js:34)
    at CSL.Output.Queue.string (citeproc_commonjs.js:5262)
    at CSL.Output.Queue.string (citeproc_commonjs.js:5159)
    at CSL.Engine.CSL.getBibliographyEntries (citeproc_commonjs.js:8528)
    at CSL.Engine.makeBibliography (citeproc_commonjs.js:8239)
    at bibliography (bibliography.js:42)
    at format (output.js:30)
    at Cite.format (get.js:18)
    at Object.parcelRequire.index.js.citation-js (index.js:5)
```

Either way, I'm curious what would be a way to use this (arguably broken) library

**Comment by mischnic** [comment]
Using webpack doesn't work either (same error)
```sh
yarn add -D webpack webpack-cli
yarn webpack -p index.js
```
and then using `dist/main.js` in the script tag.

It works in a node environment though (running `node index.js`), strange. You tell library authors about this.

**Comment by larsgw** [comment]
> They provide their own `require` function that you are supposed to use and they also use this their own sources.

The bundle is from Browserify. Although that may not be the most popular bundle tool out there, but I've found it to suffice for simple websites. If you want more customization or different tools you're probably better of building it yourself anyway, with your own Babel targets etc.

---

> `parcel serve index.html`

By the way, I'm getting an error from `parcel`:

> Unknown option: .isTSX. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.

---

>     Uncaught TypeError: Cannot read property 'system_id' of undefined

That's a combination of two issues come to light by a recent PR that a should have vetted better (I don't usually use Webpack though). See https://github.com/larsgw/citation.js/issues/188.

**Comment by mischnic** [comment]
Works fine now with `"citation-js": "^0.4.10"`

> By the way, I'm getting an error from parcel:
Unknown option: .isTSX

Strange, Parcel 1.12.3 doesn't even use that flag for babel. Have you provided a `.babelrc` file?

**Comment by larsgw** [comment]
Not on purpose, but yes.

**Comment by mischnic** [comment]
@larsgw, did your config look like this?
```json
{
    "presets": ["@babel/preset-typescript"],
    "isTSX": true
}
```
that option should be set for the preset:
```json
{
    "presets": [
        ["@babel/preset-typescript", {
            "isTSX": true
        }]
    ]
}
```

(https://github.com/babel/babel/issues/10141)

**Comment by larsgw** [comment]
Thank you. I have a directory for MCVEs, and at some point I accidentally made an MCVE (with `.babelrc`) in that directory instead of a new subdirectory, that was the main problem.
