### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by skiv71** [parcel-bundler/parcel#3375]
Hi, using the latest parcel and had many hours wasted on the above issue, whereby the bundler simply cannot cope with js code that uses async / await.

Seem's its not doing (or missing) some babel modules (or not playing by the rules as it should).

All the searches I've made seem to offer no clear resolve?

Anyone know what the 'score' is? Do I have to go back to rollup?

**Comment by mischnic** [comment]
If not transpiling await/async is an option, use a `browserslist` config that for recent enough browsers.

There are some solutions listed in the duplicate: https://github.com/parcel-bundler/parcel/issues/1762

**Comment by mathieucaroff** [comment]
```
import 'regenerator-runtime/runtime'
```

**Comment by zacharytyhacz** [comment]
> ```
> import 'regenerator-runtime/runtime'
> ```

Much appreciated my friend
