### ISSUE TITLE
--open should open the first entry point when multiple entry points are used

### ISSUE THREAD

**Issue by zocky** [parcel-bundler/parcel#3376]
# 🐛 bug report

If multiple entry points are used with --open, the browser is uselessly directed to http://localhost:1234/ where nothing is served. It should instead be directed to the first entry point.

## 🤔 Expected Behavior

`parcel foo.html bar.html --open` should open http://localhost:1234/foo.html in the browser.

## 😯 Current Behavior

`parcel foo.html bar.html --open` opens http://localhost:1234/ which is useless.

**Comment by zocky** [comment]
An alternative use case would be to open _all_ entry points in tabs, but that could become annoying very quickly with many entry points. So maybe there should be an `--open-all` option for that, but that would be a feature request outside the scope of this bug.

**Comment by galvarez421** [comment]
In my case, I am using a glob, in which case I am surprised that the compiled `index.html` (compiled from a `.pug` file) in the output directory is not served at `http://localhost:1234/`.
