### ISSUE TITLE
Official Validator-Eslint not yet available?

### ISSUE THREAD

**Issue by eclecticjohny** [parcel-bundler/parcel#3379]
# ❔ Question

I noticed in the documentation there should be an official eslint validator. When will this become available. I noticed the TypeScript one is already available. Any information about this would be helpful.  Thanks.

**Comment by DeMoorJasper** [comment]
If you mean for Parcel 2 it’s not yet available but planned

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eclecticjohny** [comment]
This is what I meant. Just saw the TypeScript one was already available as an npm install.

**Comment by DeMoorJasper** [comment]
I created an issue for it, will close this one: https://github.com/parcel-bundler/parcel/issues/3380
