### ISSUE TITLE
Q: are source maps supported?

### ISSUE THREAD

**Issue by rondonjon** [parcel-bundler/parcel#338]
I was unable to find information on source maps in the docs.

I assume they are always disabled in production builds?

Are you supporting them / planning to support them in dev builds?

If so, which "flavor" (inline, map files, ...)?

Thanks!

**Comment by davidnagli** [comment]
Nope 😞 

This is a duplicate of #68 so I’m gonna go ahead and close it. Btw, for future reference, please try to search through the issues before making a new one.
