### ISSUE TITLE
HTTPS: Firefox does not trust parcel-generated certificates after correct installation

### ISSUE THREAD

**Issue by shanehandley** [parcel-bundler/parcel#3398]
# 🐛 bug report

Despite parcel-generated certificate working in Chrome, Firefox is not trusting the certificate with the error `MOZILLA_PKIX_ERROR_CA_CERT_USED_AS_END_ENTITY`.

## 🤔 Expected Behavior

Certificate should be trusted by Firefox.

## 😯 Current Behavior

Certificate is not trusted by Firefox.

## 💁 Possible Solution

According to the bottom of [this page](https://wiki.mozilla.org/SecurityEngineering/x509Certs) it is due to a feature enabled [here](https://github.com/parcel-bundler/parcel/blob/2c1499596680be6daf158334f4146b80592ed4be/packages/core/parcel-bundler/src/utils/generateCertificate.js#L66):

"A certificate with a basic constraints extension with cA:TRUE is being used as an end-entity certificate"

Removing this feaure and generating a new certificate works as expected in both Firefox and Chrome ([details here](https://github.com/shanehandley/parcel-cert-gen-firefox)).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | v8.12.0
| npm/Yarn         | npm 6.10.3
| Operating System | MacOS Mojave 10.14.6

**Comment by DeMoorJasper** [comment]
Opened a PR to fix this in Parcel 2
