### ISSUE TITLE
Parcel 2: Hoisting output with eslint comments

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#3402]
## 🐛 bug report

When building with hoisting on(via the API), `// eslint-disable-next-line no-unused-vars` gets spammed in the file

## 😯 Current Behavior

The output with hoisting enabled is

`test.js`

```js
(function(){
// eslint-disable-next-line no-unused-vars
// eslint-disable-next-line no-unused-vars
// eslint-disable-next-line no-unused-vars
// eslint-disable-next-line no-unused-vars
// eslint-disable-next-line no-unused-vars
// ASSET: c:\dev\parcel\test.js
console.log('foo');
})();
```

## 💻 Code Sample

`test.js`
```js
console.log('foo')
```

`index.js`
```js
import _Parcel from '@parcel/core'
const { default: Parcel } = _Parcel

const parcel = new Parcel({
  entries: './test.js',
  targets: {
    browser: {
      distDir: 'dist/browser',
      browsers: ['last 1 Chrome versions']
    }
  },
  scopeHoist: true
})

parcel.run()
```

**Comment by mischnic** [comment]
These come from the scope hoisting prelude: https://github.com/parcel-bundler/parcel/blob/v2/packages/shared/scope-hoisting/src/helpers.js

Could probably be removed when loading in that file.

**Comment by ZWkang** [comment]
can i do this? @mischnic

**Comment by mischnic** [comment]
Sure @ZWkang
