### ISSUE TITLE
Parcel 2: development mode doesn't watch

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#3403]
# 🐛 bug report

Using Parcel's API with the option `mode: 'development'` doesn't keep the instance alive watching for file change

## 💻 Code Sample

```js
import _Parcel from '@parcel/core'
const { default: Parcel } = _Parcel

const parcel = new Parcel({
  entries: './test.js',
  targets: {
    browser: {
      distDir: 'dist/browser',
      browsers: ['last 1 Chrome versions']
    }
  },
  mode: 'development'
})

parcel.run()
```

**Comment by wbinnssmith** [comment]
There's a `watch` method on the Parcel object that returns a promise of a subscription object that can be `unsubscribe`d from. This will be better documented in the future, but you can look at how the CLI does it for now:

https://github.com/parcel-bundler/parcel/blob/4bc2722b0eee0bc5d12de62d7246138c07705e7c/packages/core/parcel/src/cli.js#L151
