### ISSUE TITLE
Add support for pnpm 

### ISSUE THREAD

**Issue by anhnhoktvn** [parcel-bundler/parcel#3408]
# 🙋 Feature request

I'd like to replace npm/yarn with pnpm.

## 🤔 Expected Behavior
Parcel can use pnpm to install packages.

## 😯 Current Behavior
Parcel can not use pnpm to install packages.

## 💁 Possible Solution
Have a config to use pnpm package managers.

## 💻 Examples
[https://github.com/pnpm/pnpm](https://github.com/pnpm/pnpm)

**Comment by devongovett** [comment]
We're working on abstracting the package manager interface in v2, so it should be possible to pass a custom implementation to the Parcel API to use a custom package manager. We can look into supporting pnpm by default as well.

**Comment by nthypes** [comment]
This should be closed since https://github.com/parcel-bundler/parcel/pull/3471 or only after official v2 release?

**Comment by mischnic** [comment]
That PR only refactored the code, it didn't add a pnpm "backend".
