### ISSUE TITLE
Node version target in .babelrc

### ISSUE THREAD

**Issue by juanarbol** [parcel-bundler/parcel#341]
Feature request:

Node `8.9.3` is currently stable; in `./src/.babelrc` target is `node 6`, could target be changed to `8.9.3`?

**Comment by davidnagli** [comment]
No, I definitely think this is a bad idea, we already get enough issues from people using Node 6, if we completely drop support for it we would be losing out on a bunch of people that haven’t upgraded yet.

Also, we don’t get any real benefits from doing this… 😐

**Comment by DeMoorJasper** [comment]
Node 8 doesn't have to go through babel the only reason babelrc is in the project is because of node 6 support.
This should however be fixed or almost fixed in the latest version
