### ISSUE TITLE
Parcel 2: Issue with installation on Ubuntu 16.04

### ISSUE THREAD

**Issue by embeddedt** [parcel-bundler/parcel#3413]
# 💬 Problem

Parcel v2 is not usable out of the box on Ubuntu 16.04 with the stock standard C library.

Parcel v1 can be installed as normal and does not have issues.

## 🔦 Context

When trying to install Parcel, the installation succeeds but any attempts to run Parcel give the following error when it tries to use a native Node addon (I apologize for not having the exact glibc version symbol):

```
libstdc++.so.6: version `GLIBCXX_3.x.xx' not found
```

I was able to work around this problem by installing a newer version of the standard C library from the [`ubuntu-toolchain-r/test`](https://wiki.ubuntu.com/ToolChain#PPA_packages) PPA. After doing that, Parcel was able to run without errors. However, I don't think this extra step should be necessary.

My guess as to why the issue is happening is that the Parcel v2 installation process does not rebuild the native components, which are presumably linked against a newer standard C library.

**Comment by DeMoorJasper** [comment]
The only native modules we currently use are `deasync` which is just part of the utils but never really used and the filewatcher.

Would be nice to know which dependency caused this issue

**Comment by embeddedt** [comment]
It was `@parcfel/watcher`.

**Comment by DeMoorJasper** [comment]
Maybe open an issue in https://github.com/parcel-bundler/watcher ?

**Comment by embeddedt** [comment]
As it turns out, @scrossan-crown just opened an issue over there: https://github.com/parcel-bundler/watcher/issues/18.

So I suppose this one can be closed.
