### ISSUE TITLE
Parcel 2 server returns a 404 page with pug entry point

### ISSUE THREAD

**Issue by henriquehbr** [parcel-bundler/parcel#3426]
# 🐛 bug report

Parcel 2 server returns a 404 page whenever i set a .pug file as entry point

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
	"name": "vue-with-parcel",
	"version": "1.0.0",
	"main": "index.js",
	"author": "Henrique Borges <henriqueborgeshbr@gmail.com>",
	"license": "MIT",
	"scripts": {
		"build": "parcel build src/index.pug",
		"start": "parcel serve src/test.pug"
	},
	"devDependencies": {
		"parcel": "^2.0.0-alpha.1.1",
		"stylus": "^0.54.5"
	}
}
```

## 🤔 Expected Behavior

Parcel should render the pug template properly _(and automatically install the pug dependency on package.json when it encounters the first .pug file)_

## 😯 Current Behavior

> 404 Not Found

## 💻 Code Sample

**test.pug**
```pug
<!DOCTYPE html>
html(lang="en")
	head
		meta(charset="UTF-8")
		meta(name="viewport" content="width=device-width, initial-scale=1.0")
		meta(http-equiv="X-UA-Compatible" content="ie=edge")
		title Document
	body
		p Hello World!
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.1.1
| Node             | v12.8.1
| npm/Yarn         | 1.17.3
| Operating System | Manjaro 18

**Comment by devongovett** [comment]
The Pug plugin is not yet implemented in Parcel 2. See #3358.
