### ISSUE TITLE
Add CLI Flag to specify `.env` file location

### ISSUE THREAD

**Issue by damianobarbati** [parcel-bundler/parcel#3435]
Add a `--env <env-file>` flag to the cli to have the ability to store env files outside of root directory and/or have custom env filenames

Original issue:

> 1) Parcel is currently reading from '.env' file in the folder, but what is the .env file as another name or is in subfolder? **Is it possible to give a custom path for the env file?**
> 
> 2) I use this very simple package of mine to inject env vars into node processes and I was expecting to find env vars available to the parcel process injectable in my js app but it's not so.
> I.E:
> ```
> ENVK=./config/development.env npx -r 'envk' parcel public/index.html --open --no-cache
> ```
> The development.env variables are available to parcel but no in my js app: is this intended? (NB: webpack behaves now similarly, envs must be explicitly passed when building the js bundle)

**Comment by DeMoorJasper** [comment]
Taking environments directly from the machine you're building your code with is a security risk and might cause conflicts between the Parcel runtime and environment as we also use environment variables for Parcel itself.

I'm pretty sure it's still supported in the cli though

**Comment by damianobarbati** [comment]
@DeMoorJasper do you have any idea where it is in the docs? I really didn't find a way to configure this

**Comment by DeMoorJasper** [comment]
There's an entire section on environment variables: https://en.parceljs.org/env.html

**Comment by damianobarbati** [comment]
Yes but there's no way to provide a specific path for the env file if none of the options can be applied to the project (i.e: `--env config/development.env`)

**Comment by DeMoorJasper** [comment]
> I use this very simple package of mine to inject env vars into node processes and I was expecting to find env vars available to the parcel process injectable in my js app but it's not so.

Ow no there isn't I meant injecting env variables should work in theory, or make a symlink from dev.env to config/dev.env that should also work...

**Comment by damianobarbati** [comment]
You're right, that's a way to work it around but I didn't want to pollute the root dir with all the .env files (or associated symlinks 🙃).

Anyway if the ability to customize the .env location in CLI is not considered for the near future we can close this issue (sigh 😢).

Your call!

**Comment by DeMoorJasper** [comment]
@damianobarbati it might be an option for v2, I'll leave it open.
This is a pretty advanced use-case though and v2 allows injecting env variables through the api, so that would also be a workaround.

**Comment by damianobarbati** [comment]
@DeMoorJasper I adapted to the standard, so .env.<environment>

**Comment by Cristy94** [comment]
So, how can you specifiy the .env file that parcel v2 should use?

I want to build different versions of the product that have different .env files (eg. .env.prod.premium), how can I pass that .env file to parcel build?

**Comment by mischnic** [comment]
via `NODE_ENV`:

https://github.com/parcel-bundler/parcel/blob/8a4fa3ee3716087a38fc60d482da18a3a7bc3370/packages/core/core/src/loadDotEnv.js#L16-L25

**Comment by lxchurbakov** [comment]
Hey guys! Anyone knows how to specify the file directly? Looks like parcel searches in process.cwd which is not how dotenv works and thus parcel won't work properly with namespaces - e.g. `cd project && npm run dev -w client-side` will look for .env in `/project` instead of `/project/client-side`.

**Comment by lxchurbakov** [comment]
Moreover, [doc](https://en.parceljs.org/env.html) specifies that:

```
.env files are to be stored alongside the package.json that contains your parcel-bundler dependency.
```

However, in fact parcel looks for the .env files in a folder where `node_modules` is stored, which might not be the same directory.
