### ISSUE TITLE
Hangs after startup (WSL/ Ubuntu 18)

### ISSUE THREAD

**Issue by garthenweb** [parcel-bundler/parcel#3436]
# 🐛 bug report

After starting parcel the process hangs completely.
The only output I receive (in development mode only) is `Server running at http://localhost:1234`. Opening the URL in the browser the server does not respond, it's loading.

In the resource monitor, you can see a node js process is spawned with 50-70% CPU usage.

On the file system a `.parcel-cache` folder is created with some subfolders which don't contain any files.

After `CTRL + C` the process ends after ~1 second as expected.

## 🎛 Configuration (.babelrc, package.json, cli command)

I tried with and without a `.babelrc` and `tsconfig.json`.
I used `parcel index.html`, `parcel build index.html` and also checked the same for a `tsx` file.

## 🤔 Expected Behavior

 Should build a package or throw an error message.

## 😯 Current Behavior

It does do anything visible.

## 💁 Possible Solution

No clue.

## 🔦 Context

I tried the parcel v2 alpha on a real project which was working with parcel v1. After it failed I also tried an empty html file (only containing a doctype), but the result was the same.

## 💻 Code Sample

index.html: 

``` html
<!doctype html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.1.1
| Node             | 12.8.0
| npm         | 6.10.3
| Operating System | Windows 10 WSL v1 with Ubuntu 18.04 LTS

The WSL setup is a fresh installation as I tried to make it work with Ubuntu 16.04 before, which failed on installation because of some missing (native) dependencies.

**Comment by Banou26** [comment]
Possible duplicate of https://github.com/parcel-bundler/parcel/issues/3416, depending on if you count the WSL or not.

Did you try [their workaround](https://github.com/parcel-bundler/parcel/issues/1583#issuecomment-411990655) ?

**Comment by DeMoorJasper** [comment]
Not sure but it might be related to this PR: https://github.com/parcel-bundler/parcel/pull/3383

**Comment by garthenweb** [comment]
Would like to try the PR/ latest v2 branch. Is there any guidance on how to test it?
I just checked in a PowerShell, where, as far as I can see, the watch mode is working like a charm. :)

**Comment by DeMoorJasper** [comment]
@garthenweb Clone the repo, run `yarn`, `yarn build` and than locally link the cli which is `packages/core/parcel`

**Comment by garthenweb** [comment]
@DeMoorJasper Thanks! I linked to the recent v2 branch and can verify that it is fixing the issue, awesome 👍

**Comment by satvikpendem** [comment]
If anyone else sees this, I fixed this by moving the project folder into the Linux file system rather than the Windows file system. This is for WSL 2 but it may work for WSL 1 as well. I think what is happening is that parcel can't watch for code changes in the Windows portion of the file system but it can in the Linux portion since it's being run under Linux rather than Windows.
