### ISSUE TITLE
How to load images from object-db.js file? 

### ISSUE THREAD

**Issue by MariuzM** [parcel-bundler/parcel#3443]
# ❔ Question

How can i load img paths from JS/Object file?

```
export const products = [
  {
    id: 1,
    title: 'Test',
    img: './img/Test.jpg',
  },
];
```

All images are in src/img folder. React component fetches all the data apart from image files.

Also when doing build and place manually the img folder in root folder it loads images. 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.3
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by garthenweb** [comment]
@MariuzM You can require all files via glob pattern `require('./**/*.jpg')`.

This will return an object with all files found grouped by folders and filenames and the file path that parcel creates as a value.
You might want to implement some kind of a `getAssetByPath` function which will internally abstract the object away which makes it easy to use, this is at least what I did once for a similar use case (I will not share the code here as it is a private project).

Please note that this will only work for static images that you know about at build time. If you want to load dynamic assets parcel will not help with that.

If you have a static/ finite number of images, maybe a static resolution also works for you:
``` javascript
export const products = [
  {
    id: 1,
    title: 'Test',
    img: require('./img/Test.jpg'),
  },
];
```
