### ISSUE TITLE
🙋 Remove module/file names from minified builds

### ISSUE THREAD

**Issue by rondonjon** [parcel-bundler/parcel#346]
webpack transforms module IDs to numbers during builds, which is good in terms of compression and obfuscation.

parcel seems to preserve file / module names for its `require` statement.

Would it be possible to get rid of those, at least in production builds?

### 🤔 Expected Behavior

Production builds contain as little extra data as possible, and they're not easy to refactor.

### 😯 Current Behavior

```
})({5:[function(require,module,exports) {
module.exports={hi:"hello, world"};
},{}],4:[function(require,module,exports) {
"use strict";function e(e){return e&&e.__esModule?e:{default:e}}var t=require("./text.js"),r=e(t);window.alert(r.default.hi);
},{"./text.js":5}]},{},[4])
```

--- Note the `./text.js` above

### 💁 Possible Solution

Use numeric or hash module IDs

**Comment by DeMoorJasper** [comment]
This is a known bug, the bundle itself is not being minified atm
related to #334

**Comment by shawwn** [comment]
This would make debugging a little harder, so it might be better to wait until we support source maps.

**Comment by devongovett** [comment]
the real solution for production builds would be to support tree-shaking ala rollup, and just concatenate the files together without the require calls at all. that will take more work though

**Comment by rondonjon** [comment]
@shawwn Debugging a treeshaken, uglified, and minified production file without source maps is already suicidal; would filenames make it significantly easier? (If so, that's actually a reason to remove them.)

@devongovett good point.

**Comment by devongovett** [comment]
closing this. I've opened #392 to discuss tree shaking.
