### ISSUE TITLE
🙋 Make cssnano configurable for production builds

### ISSUE THREAD

**Issue by johanbaath** [parcel-bundler/parcel#347]
### 🤔 Expected Behavior

To be able to pass options to `cssnano`. For example:

```
{
  zindex: false,
  reduceIndents: false
}
```

### 😯 Current Behavior

Not able to pass any options.

### 🔦 Context

Not being able to pass options to `cssnano` are causing my styles to break in production when minified. Turning off minification is not ideal.

### 💁 Possible Solution

Relevant code: https://github.com/parcel-bundler/parcel/blob/539ade1820c3e644586e3161f6b2357a68784142/src/transforms/postcss.js#L55

Somehow pass options. I'm unsure on how this should be configured.

**Comment by shawwn** [comment]
Yes, I'll take care of it. Could you post some code somewhere that relies on cssnano config so that I can verify when it's fixed?

**Comment by johanbaath** [comment]
@shawwn thanks. I will get you some code for this later today!

**Comment by johanbaath** [comment]
@shawwn sorry cannot post the actual code in question. However, it is related to this: https://github.com/ben-eb/gulp-cssnano/issues/8 and this: https://github.com/ben-eb/cssnano/issues/247

Those are the reasons that led me to specify the config above 😃.

**Comment by shawwn** [comment]
Already got it fixed, just got to submit the PR. It loads cssnano.config.js.

**Comment by johanbaath** [comment]
Awesome!
