### ISSUE TITLE
Text file into bundle

### ISSUE THREAD

**Issue by tavolate** [parcel-bundler/parcel#3484]
# ❔ Question

Is it possible to include a simple txt file into the bundle?

## 🔦 Context

I'm trying to import a txt file into the bundle without success. The bundle folder doesn't have the file.txt.

What am I doing wrong?

## 💻 Code Sample

const text = fs.readFileSync('./file.txt', 'utf8')

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3 |
| Node             | 10.15.3 
| npm         | 6.4.1 |
| Operating System | OSX |

**Comment by DeMoorJasper** [comment]
`fs.readFileSync('./file.txt', 'utf8')` will inline the text when targeting the browser and do nothing when targetting node

**Comment by tavolate** [comment]
I'm targeting node, how can I resolve it?

**Comment by DeMoorJasper** [comment]
In node readfile is a real function so we can’t really do anything as that would be unexpected behaviour. You’d have to manually copy that folder.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DeMoorJasper** [comment]
Something like this might work https://github.com/mikehenrty/parcel-plugin-txt

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tavolate** [comment]
OK, thank you.
