### ISSUE TITLE
Error importing rust crate

### ISSUE THREAD

**Issue by jgall** [parcel-bundler/parcel#3485]
🐛 bug report

Importing Rust code by doing `import {my_fun} from 'my_rust.rs` is working fine for me, however, when I try to import a crate I've written via `import {my_fun} from './my_crate/src/lib.rs'` as seen [here](https://parceljs.org/rust.html) the build works however, in the javascript console in Firefox I get the following error:

`TypeError: second argument must be an object`

## 🎛 Configuration (.babelrc, package.json, cli command)

configuration and project visible at https://github.com/jgall/parcel_issue

## 🤔 Expected Behavior

The function should be imported properly.

## 😯 Current Behavior

I get an error in the console instead of loading a function from Rust. 

## 💻 Code Sample

I wrote up a quick example that shows the bug (at least on my laptop it reproduces 100% of the time)
https://github.com/jgall/parcel_issue

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | v11.14.0
| npm        | 6.9.0
| Operating System | 10.15 Beta (19A546d)

**Comment by darkship** [comment]
In chrome : 

> Uncaught (in promise) TypeError: WebAssembly.instantiate(): Imports argument must be present and must be an object

**Comment by hebronwatson** [comment]
This is still an issue
