### ISSUE TITLE
Parcel Doesn't obey babelrc

### ISSUE THREAD

**Issue by joeyhub** [parcel-bundler/parcel#3491]
I've tested running babel on a file and it obeys my configuration but when I run parcel it forces transpiling no matter what.

For development I don't want transpiling especially as I'm fairly sure things like regenerator are broken. For development and testing it makes sense to first do things unadulterated since it's no problem to run in a modern browser.

My babelrc only loads env presets with environment of production and I run both parcel and babel with `ENV=development command`.

**Comment by abdullahtariq1171** [comment]
Please use the issue template.

**Comment by joeyhub** [comment]
It's just https://parceljs.org/ hello world with JS only, try to put in some async functions.

Then have browserlistrc and babelrc where present-env which is what uses browser list only loads in env.

Are you magically putting preset-env if browser list is there or something?

Possibilities are:

* You clobber the config with your defaults.
* You put in preset env on detection of browserlist.
* You ignore the env var / don't pass it down.

Looking at the list it's the first. It just seems to crudely merge a default config, I haven't checked if it's underwriting or overwriting.

There's no considerations for environments there. Something like JSX makes sense to convert in any env but also transpiling is very counter productive for developing applications locally especially as:

1. Transpiling for BC tends to put in a lot of polyfills that bury errors and add noise to initial debugging. Development will usually be for one browser first.
2. Transpiling tends to break a lot of things and change behaviour. It's a lot easier to make sure everything works first and be sure about behaviour with the raw JS then test as a final step for browser compatibility, breakages from bad tranpiles and changed in behaviour.

I guess this is basically a feature that's required.

Standard envs at least of production / development or flags (IE, compact -Os, compat -march=x86-64, debug -g).

**Comment by DeMoorJasper** [comment]
Parcel merges your babel config with our preset.

In Parcel 2 this is no longer the case. We still run a preset but it runs seperate from the user defined config.
