### ISSUE TITLE
specify build directory

### ISSUE THREAD

**Issue by tehpsalmist** [parcel-bundler/parcel#3493]
❔ Question

How do you specify the build directory in parcel 2? I have looked all over and can't find the API for this. Is it only possible through some naming plugin or something? I was hoping for at least `--out-dir` with the cli.

Love this tool, and thanks in advance for any feedback!

## 🔦 Context

I'd like to put my built files in a sub directory, like `public`. That's all.

## 💻 Code Sample

Currently running `parcel build src/index.html` on a very minimal React app (only index.html and index.js, no other assets included, no other plugins running).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-alpha.1.1
| Node             |  10.15.3
| npm/Yarn         |  6.11.3
| Operating System |  MacOS Mojave

**Comment by jschuur** [comment]
@tehpsalmist there's a reference in https://github.com/parcel-bundler/parcel/issues/3377#issuecomment-521704453 on how this is done now in Parcel 2.

Basically, the location of your `main` setting in `package.json` is use. So:

```
"main": "dist/index.js",
```

**Comment by jasonrundell** [comment]
@tehpsalmist The CLI `--out-dir` [https://parceljs.org/cli.html#output-directory](https://parceljs.org/cli.html#output-directory) works for me. Perhaps also try adding `--out-file` to the command if it's not outputting anything.

**Comment by brettinternet** [comment]
@jasonrundell (and future readers) - Note that this issue is referring to [Parcel 2](https://github.com/parcel-bundler/parcel/tree/v2) which is currently undocumented.

**Comment by mischnic** [comment]
`--dist-dir`  was added in https://github.com/parcel-bundler/parcel/pull/4113

**Comment by Dylansc22** [comment]
This solution is not very clear. Can someone please be a little more descriptive for the novice programmers... 

I updated from parcel 1 to parcel 2, my `main: index.js` never gave me an issue. Now with parcel 2, I cannot deploy my site on netlify at all without the above error

**Comment by mischnic** [comment]
> main: index.js 

You should remove that line from package.json, unless you are building a library.

**Comment by ZeldOcarina** [comment]
> @tehpsalmist there's a reference in [#3377 (comment)](https://github.com/parcel-bundler/parcel/discussions/3377#issuecomment-521704453) on how this is done now in Parcel 2.
> 
> Basically, the location of your `main` setting in `package.json` is use. So:
> 
> ```
> "main": "dist/index.js",
> ```

This should REALLY be documented!!!

**Comment by MahanVahdani** [comment]
you can use the code `npm i -g parcel` to have global access to your file and don't type the whole path every time.
if you are using Mac or Linux you can add `sudo` before that code and enter your password and you are good to go.

**Comment by cancerberoSgx** [comment]
@mischnic  I think `--dist-dir` should take precedence over `main` in package.json because is explicit. My use case is a command line report app that uses parcel to build static-standalone html pages with nice reports. I'm only interested on the bundle index.js generated, not in the html. So I use parcel as a bundler internal tool not as usual web developer. Having to remove `main` from my package.json (which I need!) so this works is annoying. Thanks, awesome project.

**Comment by maschinenzeitmaschine** [comment]
update, solved:
in case anyone else should run into this problem: the suggestion from @mischnic to simply remove the line works, BUT make sure to really remove it – it does not work if you just comment it out. 

that said, the error messages with this are still completely absurd:

```
 > 5 |   "main": "dist/index.js",
 >   |           ^^^^^^^^^^^^^^^ Did you mean "dist/index.html"?

```  
```
 > 5 |   "main": "dist/index.html",
 >   |           ^^^^^^^^^^^^^^^^^ File extension must be .js, .mjs, or .cjs
```

**Comment by mafhper** [comment]
> update, solved: in case anyone else should run into this problem: the suggestion from @mischnic to simply remove the line works, BUT make sure to really remove it – it does not work if you just comment it out.
> 
> that said, the error messages with this are still completely absurd:
> 
> ```
>  > 5 |   "main": "dist/index.js",
>  >   |           ^^^^^^^^^^^^^^^ Did you mean "dist/index.html"?
> ```
> 
> ```
>  > 5 |   "main": "dist/index.html",
>  >   |           ^^^^^^^^^^^^^^^^^ File extension must be .js, .mjs, or .cjs
> ```

Same thing here. Everything was working until these days 🥲

Removed the line `"main": "index.js", ` and now the build works again. It is worth noting, as said, that just commenting the line is not enough.

The error message is wrong. It should be adjusted.
