### ISSUE TITLE
Don't rename build files

### ISSUE THREAD

**Issue by avalanche1** [parcel-bundler/parcel#3495]
# ❔ Question

Whenever I build, Parcel creates new files, smth like `src.b3849364.js` and `src.fbed56e1.css`. But the filenames are different each time.
Is there a way to make Parcel always build with the same name?

## 🔦 Context

The prob is that I always build to the same folder, thus with each build it gets clattered with old versions of these files. Which is not good for my pipeline.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.3"
| Operating System | macos 10.14

**Comment by DeMoorJasper** [comment]
These are content hashes so no, it's to prevent duplicates and allow long term caching on for example a cdn.
