### ISSUE TITLE
Support Fast Refresh for React

### ISSUE THREAD

**Issue by gaearon** [parcel-bundler/parcel#3499]
Fast Refresh is a new hot reloading implementation for React that's first-class and doesn't have weird semantic quirks present in userland solutions. We first implemented it for RN, but integrating it on the web needs some work in the bundlers.

If you're interested in adopting it for Parcel, I wrote down first thoughts on how it could be done: https://github.com/facebook/react/issues/16604#issuecomment-528663101. This should be something you can reasonably expect to prototype in a few hours. There's a much more in-depth discussion on nuances to happen afterwards but I'd be happy to help steer that work and answer questions. Thanks for consideration!

**Comment by devongovett** [comment]
See #3654. Thanks for working on it @mischnic. Very excited for this! 😍

**Comment by foisonocean** [comment]
Happy to see the PR has been merged. Is it possible for me to try it now?

**Comment by devongovett** [comment]
@foisonocean you can try the v2 branch now. We'll also be releasing alpha 3 hopefully next week.

**Comment by foisonocean** [comment]
@devongovett 
I tried in parcel@2.0.0-alpha.3.2, but it seems not work with TypeScript.

**Comment by morewings** [comment]
Doesn’t work for me too. I have beta.2.0.0 in monorepo.
