### ISSUE TITLE
🙋 Add https support in development server

### ISSUE THREAD

**Issue by jzimmek** [parcel-bundler/parcel#350]
Would love to have https support in my local development.

webpack-dev-server supports it via the "--https" flag. all the self-signing ca/key stuff is happening behind the scenes.

I did some digging into the webpack-server-code and think we could even shamelessly copy most of the necessary code over to parcel.

Would you consider this as a PR?

**Comment by DeMoorJasper** [comment]
No need to copy webpack code #161

**Comment by mrcoles** [comment]
For folks coming here via search: https://parceljs.org/cli.html#enable-https

> ### Enable https
> Default: https disabled
>
> Available in: serve, watch (listen on HTTPS for HMR connections)
> 
>     parcel build entry.js --https
>
> ⚠️ This flag generates a self-signed certificate, you might have to configure your browser to allow self-signed certificates for localhost.

**Comment by shaunakv1** [comment]
still need to add localhost to the `altName`  array, as by default `--open` flag opens the development preview at `https://localhost:1234` and chrome flags this as insecure. 

Suggested fix in the ` parcel/src/utils/generateCertificate.js`:

```
altNames: [
        {
          type: 6, // URI
          value: 'http://example.org/webid#me'
        },
        {
          type: 7, // IP
          ip: '127.0.0.1'
        },
        {
          type: 8,
          value: `localhost`
        }
      ]
```

**Comment by caseydwayne** [comment]
To do this on Chrome follow the instructions here (https://www.pico.net/kb/how-do-you-get-chrome-to-accept-a-self-signed-certificate/). 

If you need it for a long-term project I'd go the long route with Open SSL. Remember to remove the certificate when you are through unless you really really trust the internet.

**Comment by tristone13th** [comment]
How to use a custom certificate?

**Comment by mischnic** [comment]
See https://parceljs.org/features/development/#https
