### ISSUE TITLE
Pug files not rendering

### ISSUE THREAD

**Issue by mkg20001** [parcel-bundler/parcel#3502]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

Command: `parcel build public/index.pug`

Repo: https://github.com/mercode-org/www.mercode.org/tree/feat/parcel-v2

## 🤔 Expected Behavior

Pug files should be rendered as HTML in `dist/`

## 😯 Current Behavior

Parcel creates an empty file named `dist/public.abf1e59f.pug`

```
> www.mercode.org@0.0.1 build /home/maciej/Projekte/www.mercode.org
> rm -rf dist && parcel build public/index.pug && sed 's|"/|"https://mercode.org/|g' -i dist/portal.html

✨ Built in 732ms.
 
public/public.abf1e59f.pug      0 B    14ms
└── public/index.pug          765 B    83ms
...
```

## 💻 Code Sample

Repo: https://github.com/mercode-org/www.mercode.org/tree/feat/parcel-v2 (note the branch)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.1.1
| Node             | node v10.16.3
| npm/Yarn         | npm 6.9.0
| Operating System | ubuntu 19.04 amd64

**Comment by mischnic** [comment]
The pug Plugin hasn't been updated yet to Parcel 2: #3358
