### ISSUE TITLE
No source maps when building chrome extension

### ISSUE THREAD

**Issue by avalanche1** [parcel-bundler/parcel#3508]
# 🐛 bug report

I have built react project using default `build` command and then import it into my chrome extenstion.
There are no source files listed in file tree in devtools, although chome says that it has detected source maps.
Dunno, though - maybe this is not Parcel, but chrome extensions general issue 👨‍🍳 
## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "env": {
    "test": {
      "presets": ["@babel/preset-env", "@babel/preset-react"]
    }
  },
  "plugins": [
    ["import", {"libraryName": "antd", "libraryDirectory": "es", "style": "css"}], // `style: true` for less
    "transform-class-properties" // https://medium.com/@jacobworrel/babels-transform-class-properties-plugin-how-it-works-and-what-it-means-for-your-react-apps-6983539ffc22
  ],
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": false,
        "targets": {
          "browsers": ["last 2 versions", "ie >= 11", "safari >= 10"]
        }
      }
    ],
    "@babel/preset-react"
  ]
}

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 12.9.0
| Operating System | macos 10.14

**Comment by avalanche1** [comment]
Could we pls have some input from project team?

**Comment by DeMoorJasper** [comment]
I have no clue what you mean by your issue could you please elaborate with an example or some reproduction repository?
