### ISSUE TITLE
Can code splitting disable hash in file name?

### ISSUE THREAD

**Issue by b862** [parcel-bundler/parcel#3512]
# ❔ Question
Can code splitting not use hash in filename?

## 🔦 Context

I‘m working on a H5 game and want to show js loading progress on the browser, but everytime i modify my code and the js' hash will change at the same time, so i'm not sure what the js filename is, and thie option contentHash already set to false.(i'm using api mode to start my dev server)

option contentHash working in development environment.
## 💻 Code Sample
`const options = {
    outDir: './bin/js',
    outFile: 'bundle.js',
    publicUrl: './',
    watch: true,
    cache: true,
    hmr: false,
    contentHash: false,
    production: true,
};
`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12
| Node             | 10.15
| npm/Yarn         |6.4.1
| Operating System | windows 10 x64

**Comment by devongovett** [comment]
Not possible in Parcel 1, but possible in v2 via a custom namer plugin.
