### ISSUE TITLE
Consider fixing security warnings (serialize-to-js)

### ISSUE THREAD

**Issue by damianobarbati** [parcel-bundler/parcel#3514]
In a folder with latest `parcel` installed, `yarn audit` complains because of `serialize-to-js` (denial of service security bug).

Please consider upgrading to `serialize-to-js@3` asap to fix this.

PS: I tried to clone the repo and upgrade dependencies myself to open a PR but:
1) simple `yarn install` emits a lots of errors with `node@12.10.0`
2) `yarn upgrade-interactive --latest` and then attempting to upgrade dependencies result in an infinite install loop (install, build script, build scripts fail, again install)

**Comment by adriaanvanrossum** [comment]
Seems like a valid issue to me: https://github.com/commenthol/serialize-to-js/issues/7#issuecomment-492076598, right?

**Comment by devongovett** [comment]
It's a valid issue if you use that function. Parcel does not.

Either way, I got annoyed enough at all the issues for this and released v1.12.4 with the update.

**Comment by damianobarbati** [comment]
@devongovett thank you x 1000 😉
