### ISSUE TITLE
$.isMergeableObject is not a function

### ISSUE THREAD

**Issue by popuguytheparrot** [parcel-bundler/parcel#3516]
After build source code i start my app and see it in devtools. 
How to fix this?

![image](https://user-images.githubusercontent.com/19804652/64868844-ce618e00-d648-11e9-8b50-973e6bf3f73a.png)

**Comment by mischnic** [comment]
Please fill out the issue template, most importantly: Parcel version and a code sample to reproduce this.

**Comment by popuguytheparrot** [comment]
I found why production bundle doesnt work. I use --experimental-scope-hoisting for minimize bundle size. With it flag material-ui for react up bundle size from ~290kb, to ~440kb
