### ISSUE TITLE
v2 (2.0.0-alpha.1.1) doesn't seem to work at all

### ISSUE THREAD

**Issue by pocesar** [parcel-bundler/parcel#3517]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
  "name": "example",
  "private": true,
  "scripts": {
    "start": "parcel serve --port 443 --https --log-level verbose index.html"
  }
}
```

## 🤔 Expected Behavior

Works (or at least show some progress)

## 😯 Current Behavior

Process hang with 100% CPU (and I'm on a 3700X), shows only `Server running at https://localhost:443`, and it even seems to be ignoring the log-level verbose

![image](https://user-images.githubusercontent.com/461084/64913896-020ee780-d71f-11e9-9ddc-55aecde4cbf0.png)

same exact thing happens with `parcel build index.html`, so it's not the HTTP server to blame

## 💁 Possible Solution

Test on Windows machines before releasing an alpha?

## 🔦 Context

Have to force kill the process
![image](https://user-images.githubusercontent.com/461084/64913890-eb689080-d71e-11e9-90eb-bcaa950b74d6.png)

`.parcel-cache` folder is created with a lot of empty folders inside

![image](https://user-images.githubusercontent.com/461084/64913884-cb38d180-d71e-11e9-95e0-16edcc1b17e2.png)

## 💻 Code Sample

Anything, either a .html and a script tag or a plain .js file

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.1.1
| Node             | v12.10.0
| npm/Yarn         | 6.10.2
| Operating System | windows 10 x64 1809

**Comment by devongovett** [comment]
hmm strange. our CI does run on Windows for every commit...

**Comment by pocesar** [comment]
this is my index.html

```html
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Calculadora</title>
	</head>
	<body>
		<div id="root"></div>
		<script src="./index.tsx"></script>
	</body>
</html>
```

my `index.tsx` is almost empty (aka, have no runnable code):

```tsx
import './base.css'

import React from 'react'
import ReactDOM from 'react-dom'
import { mount } from 'navi'
import { Logic } from './logic'
```

dependencies:

```json
  "dependencies": {
    "@babel/preset-env": "^7.6.0",
    "@babel/preset-typescript": "^7.6.0",
    "navi": "^0.13.6",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-navi": "^0.13.6",
    "whatwg-fetch": "^3.0.0"
  }
```

and babel.config.js (mainly for jest):

```js
module.exports = {
  presets: [
    ['@babel/preset-env', {targets: {node: 'current'}}],
    '@babel/preset-typescript',
  ],
};
```

**Comment by ericm** [comment]
What happens when you remove the flags in the start script?

**Comment by ericm** [comment]
Same issue?

**Comment by mischnic** [comment]
Please test again using the latest version of v2.
The description is too vague to be able to investigate further
