### ISSUE TITLE
Parcel 2: Node target example

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#3518]
# ❔ Question

Can someone provide an example to build for node ?

**Comment by Taym95** [comment]
There is already a [node example ](https://github.com/parcel-bundler/examples/tree/master/node) in the repo:

**Comment by mischnic** [comment]
Not quite sure either....
```json5
{
  "name": "my_cli",
  "main": "lib/index.js",
  "source": "src/index.js",
  "targets": {
    "main": {
      "context": "node", // or `engines`?
//    "includeNodeModules":  false|true
    }
  }
}
```
@devongovett @DeMoorJasper

**Comment by DeMoorJasper** [comment]
@mischnic as far as I know that's correct. `engines` is to specify which version of node to target, for example extending it to:

```
{
  "name": "my_cli",
  "main": "lib/index.js",
  "source": "src/index.js",
  "targets": {
    "main": {
      "context": "node",
      "engines": {"node": "6.0"}
//    "includeNodeModules":  false|true
    }
  }
}
```

**Comment by mischnic** [comment]
But `"context": "node",` is still needed (so it's not inferred from engines)?
(The `context` prop isn't documented at all in the v2 readme)

**Comment by DeMoorJasper** [comment]
@mischnic pretty sure you can leave it out, it should infer based on engines.
