### ISSUE TITLE
Parcel 2: node target process.argv empty

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#3521]
# 🐛 bug report

Unable to get a correct `process.argv` value when the script was built with the node target

## 🎛 Configuration (.babelrc, package.json, cli command)
Used this config https://github.com/parcel-bundler/parcel/issues/3518#issuecomment-531593877

## 🤔 Expected Behavior

`process.argv` should return the arguments passed to the CLI.

## 😯 Current Behavior

`process.argv` returns an empty array `[]`

**Comment by mischnic** [comment]
Using
```json
{
  "main": "lib.js",
  "source": "index.js",
  "engines": {
    "node": "8"
  }
}
```
works, but
```json
{
  "main": "lib/index.js",
  "source": "src/index.js",
  "targets": {
    "main": {
      "context": "node",
      "engines": {"node": "6.0"}
    }
  }
}
```
doesn't.
