### ISSUE TITLE
Parcel 2: Not picking up code changes even when restarting Parcel

### ISSUE THREAD

**Issue by dgreensp** [parcel-bundler/parcel#3525]
I have a basic "hello world" TypeScript project, and I'm in a situation where Parcel (2.0.0-alpha.1.1) just keeps serving the same code, even if I restart Parcel, until I delete the cache directory.

I don't have time to post more information right now, and I'm not sure what would be helpful.  If you can think of a place I could stick a console.log in Parcel to see what's going on, I can maybe do that later.

**Comment by mischnic** [comment]
You have likely run into this bug: #3393.
If you have a html file and include a script, changing that script would create a file with a new hash but don't update the `<script src=...>` tag.

**Comment by Banou26** [comment]
If you want a workaround while waiting for a new alpha release, you can use the `--no-cache` option.

**Comment by devongovett** [comment]
Going to close this. Should be fixed by https://github.com/parcel-bundler/parcel/pull/3414.
