### ISSUE TITLE
v2 ts-example produces empty index.js in dist/legacy

### ISSUE THREAD

**Issue by osdevisnot** [parcel-bundler/parcel#3527]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

configurations from https://github.com/parcel-bundler/parcel/tree/v2/packages/examples/ts-example

## 🤔 Expected Behavior

`dist/legacy/index.js` should have function `test`

## 😯 Current Behavior

`dist/legacy/index.js` is empty

## 🔦 Context

After cloning the repo, I did `yarn install` in examples/ts-example folder

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2
| Node             | v10.16.2
| npm/Yarn         | 1.17.3
| Operating System | Mac OSx

**Comment by devongovett** [comment]
Doesn't exist anymore on master.

**Comment by osdevisnot** [comment]
This was never on master. Check out the v2 branch. I can also probably create another repro repo if we want.

The bottom line is I want the library workflow to work where we are compiling things without adding runtime to the compiled code.

**Comment by devongovett** [comment]
sorry, I meant v2. I think it should be fixed.
