### ISSUE TITLE
Dynamic Import doesn't work correct

### ISSUE THREAD

**Issue by Arimanecro** [parcel-bundler/parcel#3529]
Hi.
Sorry for my english :)

```javascript
const Device = {
  pc:  ()=>import('./indexPC'), // include js code + import pc.css
  mobile:  () =>import('./mobileVersion/index') // include js code + include mobile.css
}
```
I don't invoke methods anywhere, but Device.pc is invoked anyway. 
In Vaniila JS, this code work correctly.
Why Do Parcel invokes first import automatically?
Thx!

**Comment by mischnic** [comment]
Which version of Parcel are you using?
