### ISSUE TITLE
Why does Parcel output es6.abc.js file?

### ISSUE THREAD

**Issue by avalanche1** [parcel-bundler/parcel#3536]
I'm building for modern browsers, so I don't need any transpylation and polyfills.
All options are at their default: a simple `parcel build` command.

**Comment by mischnic** [comment]
If you want to essentially disable `@babel/preset-env`, you can set your `browserslist` config to `last 1 Chrome version` as a workaround until preset-env can be completely disabled with Parcel 2.
e.g. package.json:
```json
{
   "browserslist": ["last 1 Chrome version"]
}
