### ISSUE TITLE
Expose env variables matching certain prefix

### ISSUE THREAD

**Issue by roopen219** [parcel-bundler/parcel#3537]
# 🙋 Feature request
It will be nice to have an option to expose only the env variables matching a certain prefix similar to vue-cli (VUE_APP) or create-react-app (REACT_APP). Part of the reason being, I want the env variables to be used on the frontend to be explicitly different from my other app env variables which might contain secrets. More context below.

## 🤔 Expected Behavior
Probably have a `--env-prefix=PARCEL_APP` cli option which exposes only process.env.PARCEL_APP_... variables. Although, we might have to whitelist env variables like HMR_RUNTIME, NODE_ENV, etc.

## 😯 Current Behavior
process.env.ANYTHING is accessible if you know the env variable's name.

## 💁 Possible Solution
Added a `key.value.startsWith('MY_APP_')` condition here, https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/visitors/env.js#L8 and it works, but couldn't figure out how to make it configurable 🙈 .

## 🔦 Context
Currently, in environments like Heroku, running parcel in post-build hook will provide all my app related env variables to the frontend. I know according to https://github.com/parcel-bundler/parcel/issues/2299#issuecomment-439768971, we can access only variables which we know the name of, but any part of my code or a third-party module could guess/access env variables like process.env.DB_URL, process.env.DATABASE_URL, etc.

## 💻 Examples
https://github.com/facebook/create-react-app/issues/865#issuecomment-252199527

**Comment by mischnic** [comment]
With Parcel 2, this could be done as a JS transformer that runs before the default JS transformer, where you replace the env variables you want to allow and replace all others with `undefined`.

**Comment by RealOrangeOne** [comment]
It would also be really nice if it were possible to automatically include the entire environment, possibly by passing `--env-prefix=''` or alike.

**Comment by mischnic** [comment]
This was implemented at some point: https://parceljs.org/features/node-emulation/#disabling-these-features
