### ISSUE TITLE
Inline env variables don't work in dev mode

### ISSUE THREAD

**Issue by avalanche1** [parcel-bundler/parcel#3538]
`MY_VAR=abc parcel index.html`
```js
globalThis.MY_VAR = process.env.MY_VAR;
MY_VAR // undefined
```
 - MY_VAR is not available client-side during development.

**Comment by mischnic** [comment]
Works for me: https://github.com/mischnic/parcel-issue-3538-env

**Comment by avalanche1** [comment]
hmm.. my React app cannot even access `process.env`. What might be the cause❓

**Comment by mischnic** [comment]
`process.env` isn't replaced for security reasons, see #2984

**Comment by avalanche1** [comment]
Ok, this was my bad. 
Was doing
`MY_VAR=abc && parcel index.html`
instead of 
`MY_VAR=abc parcel index.html`
