### ISSUE TITLE
How to setup Parcel 2 with ReasonML?

### ISSUE THREAD

**Issue by gugahoa** [parcel-bundler/parcel#3539]
# ❔ Question

How to setup Parcel 2 with ReasonML?

## 🔦 Context

I'm trying to use Parcel 2 where I used Parcel 1, in a ReasonML project
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.1.1
| Node             | v12.10.0
| npm         | v6.10.3
| Operating System | Arch Linux

**Comment by mischnic** [comment]
The Reason transformer isn't implemented yet, follow #3359 for that
