### ISSUE TITLE
multiple entrypoints output structure

### ISSUE THREAD

**Issue by gautamsi** [parcel-bundler/parcel#3540]
# 🐛 bug report

I am trying to split bundle using html pages with multiple entrypoints feature. When creating build it always puts all the js files to `--out-dir` folder while html files are in proper nested folders. This breaks the js file src path in nested entry point. I mean, all the levels will have script tag like this :  `<script src="./xxxx.####.js">`  hence nexted html can not load scripts properly.

my source folder for entrypoints lookup is like this

```
├───Dialogs
│   └───ServiceDialog
│           ServiceDialog.html
│           ServiceDialog.tsx
│
├───FolderTree
│       FolderTree.html
│       FolderTree.tsx
│
└───Index
        Index.html
        Index.tsx
```

this is what I use for script

```yaml
"renderer:build": "parcel build renderer/pages/**/*.html --public-url ../ --out-dir build/renderer/"
```

`.babelrc`
```js
{
  "presets": [
    "@babel/preset-react",
    "@babel/preset-typescript",
    [
      "@babel/preset-env",
      {
        "targets": {
          "electron": "6.0"
        }
      }
    ]
  ]
}
```

## 🤔 Expected Behavior
I would expect the --out-dir folder to contain, each js file along with the html file.
```
├───Dialogs
│   └───ServiceDialog
│           ServiceDialog.9b08608d.js
│           ServiceDialog.9b08608d.js.map
│           ServiceDialog.html
│
├───FolderTree
│       FolderTree.205c19b4.js
│       FolderTree.205c19b4.js.map
│       FolderTree.html
│
└───Index
        Index.ca83cc30.js
        Index.ca83cc30.js.map
        Index.html
```

## 😯 Current Behavior

this is what I get after build/serve
```
│   FolderTree.205c19b4.js
│   FolderTree.205c19b4.js.map
│   Index.ca83cc30.js
│   Index.ca83cc30.js.map
│   ServiceDialog.9b08608d.js
│   ServiceDialog.9b08608d.js.map
│
├───Dialogs
│   └───ServiceDialog
│           ServiceDialog.html
│
├───FolderTree
│       FolderTree.html
│
└───Index
        Index.html
```

## 💁 Possible Solution

It should preserve the path, Not sure about the solution yet, just getting started on parcel

## 🔦 Context

I am trying to use multiple entrypoint so that each html file serves as separate window in electron.

## 💻 Code Sample
pretty straight forward, can provide sample if needed

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.3
| Node             | 10.16.3
| Yarn         |  v1.17.3
| Operating System | Windows 10

### Workaround
I used api to create bundle for each entry point separately for now.

**Comment by devongovett** [comment]
There are many past discussions about this. Please search the issue tracker.

Paths are preserved for HTML and other entry points already. JavaScript is flattened into the top-level because it has hashes in the filename and isn't predictable anyway. It shouldn't matter too much where the files are as long as it works.

Anyway, it'll be possible to override the behavior of output file naming in Parcel 2.
