### ISSUE TITLE
import axios from 'axios' not working

### ISSUE THREAD

**Issue by qt1** [parcel-bundler/parcel#3544]
# 🐛 bug report

React code in tsx file:

   import * as React from 'react';
   import { RouteComponentProps, withRouter } from 'react-router-dom';
   import axios from 'axios';

code fails at run time.  When inspecting the axios variable it is null.
other components (e.g. RouteComponentProps) are not nul and working properly

## 🎛 Configuration (.babelrc, package.json, cli command)

parcel --version
1.12.3

```js
package.json
{
  "name": "labsite",
  "version": "1.0.0",
  "description": "Frontent for ibn-labs",
  "main": "index.js",
  "scripts": {
    "start": "parcel src/index.html",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Baruch",
  "license": "ISC",
  "dependencies": {
    "axios": "^0.19.0",
    "components": "^0.1.0",
    "jquery": "^3.4.1",
    "react": "^16.9.0",
    "react-bootstrap": "^1.0.0-beta.12",
    "react-dom": "^16.9.0",
    "react-router": "^5.0.1",
    "react-router-dom": "^5.0.1",
    "weak-key": "^1.0.1"
  },
  "devDependencies": {
    "@types/axios": "^0.14.0",
    "@types/react": "^16.9.2",
    "@types/react-dom": "^16.9.0",
    "@types/react-router-dom": "^4.3.5",
    "cssnano": "^4.1.10",
    "typescript": "^3.6.3"
  }
}

```

```js
tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve"
  },
  "include": [
    "frontend/src"
  ]
}
```

## 🤔 Expected Behavior

axios should have been available and running

## 😯 Current Behavior

axios is null

## 🔦 Context

Should just work. This seems to be a repeating problem, underminning confidence in Parcel ;{

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | v12.6.0
| npm/Yarn         |npm 6.11.3
| Operating System | Ubuntu 18.04.3 LTS

**Comment by DeMoorJasper** [comment]
I’ve used axios with parcel in the past, never had any issues could you provide a minimal reproducible example? I think it has to do with the ts config but not sure

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
