### ISSUE TITLE
Parcel and TradingView Charting Library

### ISSUE THREAD

**Issue by Industrial** [parcel-bundler/parcel#3550]
Hi, I found this ticket but it's unsolved: https://github.com/parcel-bundler/parcel/issues/3091.

I have tried:

1. To load via TypeScript/Babel7:
```typescript
import '../charting_library/datafeeds/udf/dist/bundle.js'
import '../charting_library/charting_library/charting_library.min.js'
```

2. To load via HTML:
```html
    <script src="../charting_library/charting_library/charting_library.min.js"></script>
    <script src="../charting_library/datafeeds/udf/dist/bundle.js"></script>
```

In both cases nothing actually happens and I get errors in the code that expects things like `window.Datafeeds.UDFCompatibleDatafeed` which throws "of undefined" errors.

I have also tried loading the TypeScript code directly and making that `window.Datafeeds` object myself but I get stuck.

I am not sure how to solve this.

**Comment by mischnic** [comment]
This is hard to investigate with this "nearly free" library.

**Comment by Industrial** [comment]
Yes, I agree.

They have TypeScript source and I instead used that source where needed to construct the environment required/expected, so I'll close this ticket :-)

They use Rollup to bundle so you can edit that configuration as well to modify the export type.

gr,

Tom
