### ISSUE TITLE
中文官网有个bug，切换语言样式不对

### ISSUE THREAD

**Issue by fanerge** [parcel-bundler/parcel#356]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

header .links a:hover {
    color: red;
}

.language-dropdown li a {
    padding: 0;
    color: red;
}

**Comment by brandon93s** [comment]
"Chinese official website has a bug, switch language style wrong"

Hello, thanks for the report! Is this related to the documentation website? If so, an issue can be opened in the website repo.

**Comment by fanerge** [comment]
yes!
url:https://parceljs.org/
![image](https://user-images.githubusercontent.com/17136707/34187539-edb5ce70-e56c-11e7-8433-cc4311d1ffd6.png)

**Comment by fanerge** [comment]
resolve:
header .links a:hover {
color: red;
}

.language-dropdown li a {
padding: 0;
color: red;
}

**Comment by brandon93s** [comment]
Please follow this issue and PR for updates: 

https://github.com/parcel-bundler/website/issues/41

https://github.com/parcel-bundler/website/pull/56

**Comment by fanerge** [comment]
thank you
