### ISSUE TITLE
HAML Support

### ISSUE THREAD

**Issue by Kazuto** [parcel-bundler/parcel#3561]
# 🙋 Feature request

HAML is a more elegant way of writing HTML, similar to Pug. Adding HAML support allows for a more diverse selection of HTML templating.

**Comment by Taym95** [comment]
I would like to give this issue a try!

**Comment by kwelch** [comment]
Awesome! Feel free to reach out with any questions.

**Comment by Taym95** [comment]
Hey, which JavaScript Haml implementation I need to use? I found these 2:
[haml.js](https://github.com/tj/haml.js/)
[haml-js](https://github.com/creationix/haml-js)

**Comment by devongovett** [comment]
Going to close this. I don't have the bandwidth to implement and maintain this. It would be great as a third party plugin if someone wants to build it!
