### ISSUE TITLE
syncPromise (deasync) hangs under Node.js v12.11.0

### ISSUE THREAD

**Issue by chocolateboy** [parcel-bundler/parcel#3566]
## Description

[parcel-plugin-nunjucks](https://github.com/chocolateboy/parcel-plugin-nunjucks) uses [`syncPromise`](https://github.com/chocolateboy/parcel-plugin-nunjucks/blob/87e10a3b2a9de193eb665333a42636937720de47/src/NunjucksAsset.js#L96-L120)<sup>1</sup>, calls to which have started hanging under Node.js v12.11.0 (which was released [yesterday](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.11.0)).

An example can be seen [here](https://travis-ci.org/chocolateboy/parcel-plugin-nunjucks/jobs/589721089) on Travis (and I've reproduced it locally).

Everything works fine under v12.10.0.

<sup>1</sup> It needs to access the config file ([`Asset#getConfig`](https://github.com/parcel-bundler/parcel/blob/d2dc7c96331f015bdf67ff8286dbb95de2dd6c9b/src/Asset.js#L137) is async) from the asset's constructor ([`Parser#getAsset`](https://github.com/parcel-bundler/parcel/blob/d2dc7c96331f015bdf67ff8286dbb95de2dd6c9b/src/Parser.js#L82-L86) is synchronous).

## Environment

- Node.js: v12.11.0
- Parcel: v1.12.3
- npm: 6.11.3
- yarn: 1.17.3
- OS: Linux (Ubuntu 16.04.6 LTS, Arch)

**Comment by chocolateboy** [comment]
FYI: I can't reproduce this if `syncPromise`/deasync is used in isolation, only when running under Parcel:

```sh
$ cat test.js
```

```javascript
const syncPromise = require('parcel-bundler/src/utils/syncPromise')

function test () {
    return new Promise((resolve, reject) => {
        setTimeout(() => resolve(42), 1000)
    })
}

console.log(syncPromise(test()))
```

```sh
$ node ./test.js
42
```

**Comment by devongovett** [comment]
I'd recommend moving the async call to `getConfig` out of the constructor and into one of the `async` functions exposed by the `Asset` base class. See the docs here: https://parceljs.org/asset_types.html

Ideally you wouldn't override `load` or the `constructor` at all, but use those lifecycle methods.

Either way, this is an issue with `deasync` not Parcel, so closing.

**Comment by chocolateboy** [comment]
The `getConfig` call can't be moved out of the constructor. The constructor's return type is [dynamic](https://github.com/chocolateboy/parcel-plugin-nunjucks/blob/87e10a3b2a9de193eb665333a42636937720de47/src/NunjucksAsset.js#L164-L175) and depends on the config. The problem is that assets are required to be constructed synchronously.

> this is an issue with deasync not Parcel, so closing.

This is a bug in Parcel v1.x since it breaks all code which uses [`Asset#package`](https://github.com/parcel-bundler/parcel/blob/d2dc7c96331f015bdf67ff8286dbb95de2dd6c9b/src/Asset.js#L122), which is still defined as a public property (albeit deprecated).

**Comment by chocolateboy** [comment]
It's still there in v2:

https://github.com/parcel-bundler/parcel/blob/fe08980a6f256d94100d017e7c1f1e0b3a527ec0/packages/core/parcel-bundler/src/Asset.js#L131-L136
