### ISSUE TITLE
TypeError: Invalid attempt to spread non-iterable instance Only on safari

### ISSUE THREAD

**Issue by rzubrycki** [parcel-bundler/parcel#3573]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
`"devDependencies": {

"@babel/core": "^7.5.5",
"@babel/preset-env": "^7.5.5",
"babel-preset-env": "^1.7.0",
"parcel-bundler": "^1.12.3",
"sass": "^1.22.9"
	},
	"dependencies": {
		"date-fns": "^2.2.1",
		"mustache": "^3.0.1"
	},
	"scripts": {
		"start": "parcel index.html --open",
		"build": "parcel build index.html --no-source-maps --public-url $npm_package_config_public_url"
	},
	"browserslist": "> 0.25%, not dead"
}`

.babelrc
`{
	"presets": ["@babel/preset-env"]
}
`

## 🤔 Expected Behavior

Spread should work as is supported by Safari.

## 😯 Current Behavior

On Safari only i got error in console => "TypeError: Invalid attempt to spread non-iterable instance" 

## 💁 Possible Solution

I tried google it and try some solutions, but all failed.

## 💻 Code Sample

just trying to grab two dom elements and use map on it:
`const dateElement = [...document.querySelectorAll('.date')];`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.3
| Node             |v11.3.0
| npm/Yarn         | 6.10.3
| Operating System | ios

Any help much appreciate, cheers.

**Comment by mischnic** [comment]
This isn't a Parcel bug, but in Babel, see
- https://github.com/zloirock/core-js/pull/249
- https://github.com/babel/babel/issues/4616

The output is:
```js
function _toConsumableArray(arr) {
  return (
    _arrayWithoutHoles(arr) || _iterableToArray(arr) || _nonIterableSpread()
  );
}

function _nonIterableSpread() {
  throw new TypeError("Invalid attempt to spread non-iterable instance");
}

function _iterableToArray(iter) {
  if (
    Symbol.iterator in Object(iter) ||
    Object.prototype.toString.call(iter) === "[object Arguments]"
  )
    return Array.from(iter);
}

function _arrayWithoutHoles(arr) {
  if (Array.isArray(arr)) {
    for (var i = 0, arr2 = new Array(arr.length); i < arr.length; i++) {
      arr2[i] = arr[i];
    }
    return arr2;
  }
}

var dateElement = _toConsumableArray(document.querySelectorAll(".date"));

console.log(dateElement);

```

If the check `Symbol.iterator in Object(iter)` fails (your Safari version likely doesn't support Iterators yet), that error is thrown. Which Safari version are you running?

**Comment by rzubrycki** [comment]
@mischnic safari v9

**Comment by mischnic** [comment]
We can't really do anything about that, as this is caused by the code emitted by babel (you should report that there).
(And unrelated to that: Safari 9 isn't matched by your browserslist: https://browsersl.ist/?q=%3E+0.25%25%2C+not+dead)
