### ISSUE TITLE
error: Inline JavaScript is not enabled. Is it set in your options?

### ISSUE THREAD

**Issue by chengcjun** [parcel-bundler/parcel#3574]
less use @import
`error： Inline JavaScript is not enabled. Is it set in your options?`
How to do? 
less switch a lower version?

**Comment by DeMoorJasper** [comment]
Could you give a little more context?

For example a minimal reproducible example?

**Comment by chengcjun** [comment]
i use lastest 'less' && want to import && override a variable
 ```
@import another.less
@var: xxxx;
```
error： Inline JavaScript is not enabled. Is it set in your options?
where set `javascriptEnabled: true`

**Comment by devongovett** [comment]
You can configure less in `.lessrc`.
