### ISSUE TITLE
yarn add --dev parcel-bundler  can not  be  succeed

### ISSUE THREAD

**Issue by llfylwg** [parcel-bundler/parcel#358]
the error:
warning www@1.1.11: License should be a valid SPDX license expression
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "parcel-plugin-typescript > @ngtools/webpack@1.9.1" has unmet peer dependency "webpack@^2.2.0 || ^3.0.0".
warning " > parcel-plugin-vue@1.4.0" has unmet peer dependency "vue-template-compiler@~2".
warning "parcel-plugin-vue > vueify-bolt@1.0.2" has unmet peer dependency "vue-template-compiler@~2".
warning "parcel-plugin-vue > vueify-bolt > vue-loader@13.6.0" has unmet peer dependency "css-loader@*".
warning "parcel-plugin-vue > vueify-bolt > vue-loader@13.6.0" has unmet peer dependency "vue-template-compiler@^2.0.0".

waitting for your response   ,thx.

**Comment by DeMoorJasper** [comment]
This seems to be an issue in the plugins u are using?
Just FYI Typescript is built-in inside Parcel and the plugin only adds typechecking and Full Angular support and is very buggy compared to the built-in support

**Comment by llfylwg** [comment]
It is success when i use npm to install ,so,i don`t know why. Like you said ，i am using plugin-vue,plugin-ts.

**Comment by DeMoorJasper** [comment]
Alright guess this is resolved than, it's not a bug with parcel :)
