### ISSUE TITLE
IE11 fails to run due to Symbol of lodash and others

### ISSUE THREAD

**Issue by Kikketer** [parcel-bundler/parcel#3580]
I'm attempting to write a very simple app but have it work in IE11 (shudder).

From the docs I should be able to use browserlist to specify what polyfills to include: https://en.parceljs.org/javascript.html#default-babel-transforms

My package.json contains:
```
  "browserslist": [
    "last 2 chrome versions",
    "last 2 firefox versions",
    "last 2 edge versions",
    "last 2 opera versions",
    "IE 11",
    "not op_mini all"
  ],
```

When I build the project IE still fails to render either giving me an error which seems to come from lodash: 
```
Symbol is undefined
```
This appears to be coming from a file in lodash (which I haven't included in my project) called `_setCacheHas.js`.

Attempting to recreate the issue in codesandbox I get a whole slew of other errors: https://codesandbox.io/embed/parcel-ie11-g7g4h . If you hit the resulting url in IE you get a pile of errors: https://g7g4h.csb.app/

From babel-transpiler, vendors~sandbox, etc 
```
Syntax error
Expected ')'
etc
```

**Comment by mischnic** [comment]
> When I build the project IE still fails to render either giving me an error which seems to come from lodash:

Please provide a reproduction, I guess you're using package that in turn uses lodash?

**Comment by Kikketer** [comment]
The reproduction is in code sandbox: https://g7g4h.csb.app/
If you hit that page with IE11 you will see the error.  The source code behind that is in the codesandbox: https://codesandbox.io/embed/parcel-ie11-g7g4h

This is what it looks like in IE11:
<img width="485" alt="Screen Shot 2019-09-30 at 1 06 34 PM" src="https://user-images.githubusercontent.com/958042/65904040-37ecd680-e383-11e9-8494-205b72007c77.png">

**Comment by mischnic** [comment]
The first error in the list comes from this snippet:
```js
function(t,n,r,i={}){
```
there's a default value for the last parameter, IE11 doesn't support that.
However, you're trying to run babel inside of Codesandbox in IE11, which Codesandbox probably doesn't support.
Please:
- Provide a reproduction of your original issue (with the Symbol)
- post the error that gets thrown in IE like you did in your last comment
