### ISSUE TITLE
CI running on Windows 10 doesn't recognize NODE_ENV?

### ISSUE THREAD

**Issue by iazO** [parcel-bundler/parcel#3585]
# ❔ Question

Our CI build server changed from a linux environment to on prem Windows 10 machine. Ever since, Parcel is having issues with identifying the NODE_ENV variable.
    
## 🔦 Context

Parcel probably doesnt use the correct node_env settings, and we are unable to distinquish dev from prod at runtime.

## 💻 Code Sample

Script:
`"build:artifacts": "SET NODE_ENV=production && parcel build ./src/index.html --no-source-maps --no-cache && copy \"web.config\" \"dist\\web.config\""`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.16.2
| Yarn         | 1.19
| Operating System | Windows 10

**Comment by devongovett** [comment]
We use [cross-env](https://www.npmjs.com/package/cross-env) for this
