### ISSUE TITLE
importing .scss as objects

### ISSUE THREAD

**Issue by joshuambg** [parcel-bundler/parcel#3590]
# ❔ Question

My React/Webpack app imports sass files as objects and then I can target the class names. 
```
import styles from './somefile.scss'
<div className={styles.someClassName}></div>
```
This is accomplished through Webpack loaders 
```
    rules: [
      {
        test: /\.scss$/i,
        use: [
          'style-loader',
          'css-loader',
          'sass-loader'
          },
        ],
      }
```
Is this possible in Parcel? I haven't anything that works. By default Parcel takes the scss files and generates one css file. Then the JavaScript import module `styles` is just a blank object.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  ^1.9.7
| Node             | v10.15.1
| Yarn         | 1.6.0
| Operating System | osx 10.12.6

**Comment by mischnic** [comment]
After being converted from SASS to CSS, your styles get passed to PostCSS like any other css file, therefore:

.postcssrc
```json
{
	"modules": true
}
```
style.scss:
```scss
.foobar {
	color: red;
}
```
index.js
```js
import styles from './style.scss'

console.log(styles); // == { foobar: '_foobar_2ecb2' }
```
