### ISSUE TITLE
NPM high severity vulnerability / Update serialize-to-js

### ISSUE THREAD

**Issue by scriptPilot** [parcel-bundler/parcel#3597]
High            Denial of Service

  Package         serialize-to-js

  Patched in      >=2.0.0

  Dependency of   parcel-bundler [dev]

  Path            parcel-bundler > serialize-to-js

  More info       https://npmjs.com/advisories/790

found 1 high severity vulnerability in 10462 scanned packages
  1 vulnerability requires manual review. See the full report for details.

**Comment by DeMoorJasper** [comment]
This is a false positive from npm. We fixed it in master but don't see any reason to release an update

**Comment by DeMoorJasper** [comment]
Please have a look at existing issues before creating a new one in the future https://github.com/parcel-bundler/parcel/issues?q=is%3Aissue+serialize-to-js+is%3Aclosed

**Comment by muescha** [comment]
if you never fix it in version 1 why not put a hint about this to the readme?

**Comment by vladthedev** [comment]
Yeah, it sure needs a hint about this in the readme.

**Comment by devongovett** [comment]
Just published v1.12.4 with the update.
