### ISSUE TITLE
CSS not updating automatically with Firefox

### ISSUE THREAD

**Issue by TimelyToga** [parcel-bundler/parcel#36]
First of all, thanks for such a wonderful tool! 

Updates to JS files propagate correctly, but changes to imported CSS files will not be applied without refreshing on Firefox. 

Tested on Firefox V35.0 and Firefox Developer Edition 58.0b7 (64-bit). 

Chrome V62.0.3202.94 (Official Build) (64-bit) updates automatically.

**Comment by thejameskyle** [comment]
Pretty sure that's going to be somewhere in one of these files:

- https://github.com/parcel-bundler/parcel/blob/master/src/builtins/hmr-runtime.js
- https://github.com/parcel-bundler/parcel/blob/master/src/builtins/css-loader.js

**Comment by M-ZubairAhmed** [comment]
can I look into this one?

**Comment by DeMoorJasper** [comment]
I'll try fix this one

**Comment by thejameskyle** [comment]
Moving to #58
