### ISSUE TITLE
Does not work with postcss-short

### ISSUE THREAD

**Issue by maxinakenty** [parcel-bundler/parcel#360]
Hi guys! Thank you for the excellent tool! I'm trying to use postcss-short with parcel, but unfortunately it does not work. I followed the instructions described in the documentation. All other postcss plugins (autoprefixer and css-modules) work fine.

Here is the configuration of my .postcssrc
{
  "modules": true,
  "short": true,
  "plugins": {
    "autoprefixer": {
      "grid": true
    }
  }
}

**Comment by shawwn** [comment]
> Hi, could you provide a minimally working example? E.g. Can you push your code to a git repo somewhere and link it here?

(We should probably update the issue template to ask for source code demonstrating bugs.)

**Comment by shawwn** [comment]
No idea why my last comment posted as a quote... Anyway can you provide a repro example? Thanks!

**Comment by maxinakenty** [comment]
Oh sure. You can see the [code here](https://github.com/maxinakenty/bh-front).

**Comment by maxinakenty** [comment]
https://github.com/maxinakenty/bh-front/blob/master/src/components/app/app.scss

On the tenth line I try to apply size, but it does not turn into with and height.

**Comment by devongovett** [comment]
I get a 404 on the repo.

**Comment by brandon93s** [comment]
@maxinakenty - The repo you've provided is returning a 404. Feel free to post a new example, we'll be glad to take a look!

**Comment by dreit-p** [comment]
So, what's the problem? It is still actual and the repos are unavailable.
