### ISSUE TITLE
Parcel 2: core-js@3 is required error even if installed properly

### ISSUE THREAD

**Issue by garthenweb** [parcel-bundler/parcel#3602]
# 🐛 bug report

Bundler throws an error about core-js even if the correct version is installed. Happens if dependencies in node modules require their own core-js version.

## 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc
```json
{
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }],
    ["babel-plugin-styled-components", {
      "ssr": true,
      "minify": true
    }]
  ],
  "presets": [
    ["@babel/preset-typescript", {
      "isTSX": true,
      "allExtensions": true
    }],
    "@babel/preset-react",
    ["@babel/preset-env", {
      "useBuiltIns": "usage",
      "loose": true,
      "corejs": 3
    }]
  ]
}
```
package.json
``` json
{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@reach/router": "^1.2.1",
    "core-js": "^3.2.1",
    "react": "^16.9.0",
    "react-dom": "16.9.0"
  },
  "scripts": {
    "start": "NODE_ENV=\"production\" parcel build src/index.tsx"
  },
  "devDependencies": {
    "@babel/core": "^7.6.0",
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/plugin-proposal-decorators": "^7.6.0",
    "@babel/preset-env": "^7.6.0",
    "@babel/preset-react": "^7.0.0",
    "@babel/preset-typescript": "^7.6.0",
    "babel-plugin-styled-components": "^1.10.6",
    "parcel": "^2.0.0-alpha.1.1",
    "typescript": "^3.6.2"
  }
}
```

## 🤔 Expected Behavior

Should not throw.

## 😯 Current Behavior

Throws with
```
🚨 core-js@3 is required to use Parcel's babel integration. Detected version 1.2.7.
  at load (<path>/parcel-original/packages/transformers/babel/lib/config.js:109:13)  
  at async Object.loadConfig (<path>/parcel-original/packages/transformers/babel/lib/BabelTransformer.js:29:5)
  at async ConfigLoader.loadPluginConfig (<path>/parcel-original/packages/core/core/lib/ConfigLoader.js:104:7)
  at async RequestGraph.runConfigRequest (<path>/parcel-original/packages/core/core/lib/RequestGraph.js:363:18)                                               
```

Even though 

```
$ yarn why core-js
yarn why v1.17.3
[1/4] Why do we have the module "core-js"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "core-js@3.2.1"
info Has been hoisted to "core-js"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "1.14MB"
info Disk size with unique dependencies: "1.14MB"
info Disk size with transitive dependencies: "1.14MB"
info Number of shared dependencies: 0                                                  
=> Found "fbjs#core-js@1.2.7"
info This module exists because "@reach#router#create-react-context#fbjs" depends on it.
info Disk size without dependencies: "1.49MB"
info Disk size with unique dependencies: "1.49MB"
info Disk size with transitive dependencies: "1.49MB"
info Number of shared dependencies: 0
Done in 2.78s.                                                                         
```

## 💁 Possible Solution

Parcel checks the core-js dependency for node modules like `fbjs` (in my example a dependency of `@reach/router`) which is using an old version of core-js. Maybe it would be better to transpile node modules with the babel config in the root instead of using the default babel config?

## 🔦 Context

Maybe it has something to do with https://github.com/parcel-bundler/parcel/pull/3507?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2 (linked locally, using 538ee40fa00e4e6e461714c4488499adb70f795f)
| Node             | v12.8.1
| npm/Yarn         | yarn v1.17.3
| Operating System | Windows 10/ WSL 1

**Comment by mischnic** [comment]
> Parcel checks the core-js dependency for node modules like fbjs (in my example a dependency of @reach/router) which is using an old version of core-js.

That is indeed the issue here,
https://github.com/parcel-bundler/parcel/blob/08cefd89889c5f7440af42f13d5118ed201ab469/packages/transformers/babel/src/config.js#L91-L94
resolves to the package's `core-js` version, which in case of `fbjs` is `^1.0.0`. And it's a regular dependency because it exports some JS stdlib polyfills:
```js
// fbjs/lib/Set.js
module.exports = require('core-js/library/es6/set');
```

cc @wbinnssmith who added this code in #3480. (Though `useEntry: usage` was reverted in the meantime 😐)

**Comment by devongovett** [comment]
I think we should just remove this error. Now that we've removed `useBuiltins: 'usage'`, we don't need `core-js` anyway.

**Comment by garthenweb** [comment]
@devongovett Works like a charm, thank you!
