### ISSUE TITLE
How to have Parcel build remove newlines/linebreaks from compiled JavaScript?

### ISSUE THREAD

**Issue by jamiesteven** [parcel-bundler/parcel#3604]
## ❔ Question

When I run:

``NODE_ENV=production parcel build ./app/app.js --no-source-maps``

The output JavaScript is compressed, minified and managled, but still has linebreaks; it seems like it has one linebreak for each of the different JavaScript libraries or files I have in my project.

I've been trying to set my .terserrc config to remove line breaks from the final JavaScript file to no avail.

When I run:

``terser --compress --mangle --output output.js app.js``

The lines breaks are removed...

## 🔦 Context

I'm hoping to have all compiled files (.css/.js) without any linebreaks.

## 💻 Code Sample
N/A

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | v12.11.1
| npm/Yarn         | 6.11.3
| Operating System | MacOS 10.14.6

**Comment by mischnic** [comment]
With Parcel 1, terser runs *before* all the files are concatenated into the bundle. Therefore, you can't influence this using via .terserrc.

That newline is hardcoded here:

https://github.com/parcel-bundler/parcel/blob/fe08980a6f256d94100d017e7c1f1e0b3a527ec0/packages/core/parcel-bundler/src/packagers/JSPackager.js#L117
---
With `--experimental-scope-hoisting`, you would not have these newlines (and the bundle might be smaller overall).

**Comment by jamiesteven** [comment]
Thanks very much, that worked great.

**Comment by mischnic** [comment]
> FWIW, my compiled filesize decreased by half!

🎉
