### ISSUE TITLE
Can't install parcel (Unexpected end of JSON input while parsing near...)

### ISSUE THREAD

**Issue by BenoitPingris** [parcel-bundler/parcel#3609]
# 🐛 bug report

When I try to install parcel on my computer using `npm install -g parcel-bundler`, I got this error
```
npm ERR! Unexpected end of JSON input while parsing near '...cies":{"LiveScript":"'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/benoit/.npm/_logs/2019-10-06T08_59_55_011Z-debug.log
```

## 🤔 Expected Behavior
It should install `parcel` globally 

## 😯 Current Behavior
The error (see above) appears, I have this extra informations in a log file
```
695 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...cies":{"LiveScript":"'
695 verbose stack     at JSON.parse (<anonymous>)
695 verbose stack     at parseJson (/usr/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
695 verbose stack     at /usr/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50
695 verbose stack     at runMicrotasks (<anonymous>)
695 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:85:5)
696 verbose cwd /home/benoit/Tests/q
697 verbose Linux 5.2.11-1-MANJARO
698 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "parcel-bundler"
699 verbose node v12.9.1
700 verbose npm  v6.11.2
701 error Unexpected end of JSON input while parsing near '...cies":{"LiveScript":"'
702 verbose exit [ 1, true ]

```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             | 12.9
| npm/Yarn         | 6.11.2
| Operating System | Manjaro 18.1.0 (Juhraya)

**Comment by mischnic** [comment]
Can you post your package.json file?

**Comment by BenoitPingris** [comment]
I might be missing something but as I'm installing parcel globally I don't have a package.json :smile: 
However I tried the following to install it on a project
```
$ mkdir dummy
$ cd dummy
$ npm init -y
$ npm install parcel-bundler
```
And unfortunately I had the exact same error
Here the package.jsont that has been created, nothing weird
```json
{
  "name": "q",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

```

**Comment by mischnic** [comment]
Can you post the complete npm log file?

**Comment by BenoitPingris** [comment]
[2019-10-06T13_40_16_494Z-debug.log](https://github.com/parcel-bundler/parcel/files/3694429/2019-10-06T13_40_16_494Z-debug.log)
Here the log file

**Comment by mischnic** [comment]
> `error for optionator@^0.8.1 Unexpected end of JSON input while parsing near '...cies":{"LiveScript":"'`

So it can't parse the `package.json` file of the package `optionator`. Maybe clearing the npm cache fixes it?

**Comment by BenoitPingris** [comment]
Arf unfortunately I still got an error, but it seems different
[2019-10-06T14_03_35_578Z-debug.log](https://github.com/parcel-bundler/parcel/files/3694453/2019-10-06T14_03_35_578Z-debug.log)
