### ISSUE TITLE
Stripping comments in css

### ISSUE THREAD

**Issue by avalanche1** [parcel-bundler/parcel#3618]
# ❔ Question
In production build this type of comment is kept intact in the beginning of the minified `css` file:
```css
/*!
 * 
 * antd v4.0.0-alpha.6
 * 
 * Copyright 2015-present, Alipay, Inc.
 * All rights reserved.
 *       
 */
```

Is this expected or a bug in css minifier?

**Comment by mischnic** [comment]
> Removes comments in and around rules, selectors & declarations. Note that any special comments marked with ! are kept by default.
> https://cssnano.co/optimisations/discardcomments

Seems like that is expected
