### ISSUE TITLE
Parcel Readme is not detected by NPM

### ISSUE THREAD

**Issue by souravdasslg** [parcel-bundler/parcel#3619]
# 🐛 bug report

## 🤔 Expected Behavior
The readme file should become visible to NPM.

## 😯 Current Behavior
Parcel package page in NPM is showing the following message 
**"Unable to find a readme for parcel@1.12.4"**
![screenshot-www npmjs com-2019 10 08-21_40_35](https://user-images.githubusercontent.com/9268592/66413079-56527200-ea14-11e9-836e-474f1c0ed859.png)

**Comment by mischnic** [comment]
@devongovett 1.12.4 was published without readme: https://unpkg.com/browse/parcel@1.12.4/

**Comment by DanielRuf** [comment]
It is completely missing in the published package so there is nothing to display.

See https://unpkg.com/browse/parcel-bundler@1.10.3/ vs https://unpkg.com/browse/parcel-bundler@1.11.0/

**Comment by devongovett** [comment]
Should be fixed already by #3707, just need to hit publish.
