### ISSUE TITLE
Improved CLI Icons for Windows

### ISSUE THREAD

**Issue by brandon93s** [parcel-bundler/parcel#362]
🙋 Feature Request

### 🤔 Expected Behavior

Window's should fall back to icons that it supports and can render.

### 😯 Current Behavior

Window's renders colored boxes instead of ⌛️ ✨:

![image](https://user-images.githubusercontent.com/4730164/34235793-ffac013a-e5c1-11e7-8e02-cb2063b5177f.png)

### 💁 Possible Solution

We could leverage something like [log-symbols](https://www.npmjs.com/package/log-symbols) to provide fallbacks. Alternatively, just detect Windows and conditionally show the existing ⌛️ ✨ vs other compatible icons.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  N/A
| Node             |  N/A
| npm/Yarn         |  N/A
| Operating System |  Windows 10

**Comment by shawwn** [comment]
Sure, I'll throw this in too.
