### ISSUE TITLE
Is there a way to ignore a module?

### ISSUE THREAD

**Issue by arnohovhannisyan** [parcel-bundler/parcel#3631]
# ❔ Question

Is there a way to ignore a module from being bundled?

## 🔦 Context

I am making a VSCode extension which imports the `vscode` module. This module is created on-the-fly by VSCode and isn't a real module, so an error is occurs when Parcel tries to bundle it.

Currently, I'm using Webpack `externals` to ignore it:

```
module.exports = {
  ...,
  "externals": {
    "vscode": "commonjs vscode"
  }
}
```

## 💻 Code Sample

Repository: https://github.com/arnohovhannisyan/vscode-syncify

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 12.11.1
| Yarn         | 1.19.1
| Operating System | Manjaro Linux

**Comment by mischnic** [comment]
Duplicate of https://github.com/parcel-bundler/parcel/issues/3305 / https://github.com/parcel-bundler/parcel/issues/144
