### ISSUE TITLE
Uncaught ReferenceError: Cannot access 'VISITOR_KEYS' before initialization

### ISSUE THREAD

**Issue by janouma** [parcel-bundler/parcel#3632]
# 🐛 bug report

After building my web app using the production build, the following error occurs while running the app on Chrome: `Uncaught ReferenceError: Cannot access 'VISITOR_KEYS' before initialization`

## 🎛 Configuration

- .babelrc
```json
{
  "presets": [
    [
      "@babel/env",
      {
        "targets": "safari >= 10"
      }
    ]
  ],
  "plugins": [
    "transform-inline-environment-variables",
    "@babel/plugin-transform-runtime"
  ]
}
```

- package.json
```json
...
"scripts": {
   ...
   "build": "npm run clean && parcel build --no-source-maps --no-minify client/index.html && npm run build:widget",
   ...
},
...
"dependencies": {
    "@babel/runtime": "^7.6.3",
   ...
},
"devDependencies": {
  "@babel/core": "^7.6.4",
  "@babel/plugin-transform-runtime": "^7.6.2",
  "@babel/preset-env": "^7.6.3",
   ...
  "parcel-bundler": "^1.12.4",
},
...
```

Chrome Version 76.0.3809.100

## 🤔 Expected Behavior

No error should occur

## 😯 Current Behavior

<img width="828" alt="Capture d’écran 2019-10-11 à 11 52 25" src="https://user-images.githubusercontent.com/1352436/66642797-b23c1700-ec1d-11e9-9c9e-c9243b634213.png">

## 🔦 Context

I was updating my dependencies to get rid of the following warning:
`Browserslist: caniuse-lite is outdated. Please run next command 'npm update'`

## 💻 Code Sample

<img width="828" alt="Capture d’écran 2019-10-11 à 11 54 40" src="https://user-images.githubusercontent.com/1352436/66642916-f5968580-ec1d-11e9-8727-3fe9970faa29.png">

## 🌍 Your Environment

| Software         | Version(s)                           |
| ---------------- | ------------------------------------ |
| Parcel           | 1.12.4                               |
| Node             | v10.11.0                             |
| npm              | 6.9.0                                |
| Operating System | MacOs Catalina (same issue on Mojave)|

**Comment by oztek22** [comment]
@janouma were you able to resolve this?

**Comment by janouma** [comment]
> @janouma were you able to resolve this?

No, in the end I updated my dependencies manually one at a time instead of using the command `npm update`.
Tedious, but effective.

**Comment by guoxu-f** [comment]
I have same issue, update the package, and then it will show this Reference Errro
