### ISSUE TITLE
[v2] Parcel crashes upon presence of .parcelrc file

### ISSUE THREAD

**Issue by brillout** [parcel-bundler/parcel#3633]
# 🐛 bug report

If I create a `.parcelrc` then running `parcel build index.html` crashes with exit code 1 and no error is printed to the console.

However if I comment out `(0, _logger.patchConsole)();` at `node_modules/parcel/lib/cli.js` and try again I get following error:

~~~shell
TypeError: Cannot read property 'report' of undefined
    at ReporterRunner.report (/home/romu/tmp/parcel-example--index_html/node_modules/@parcel/core/lib/ReporterRunner.js:59:22)
~~~

I tried many `.parcelrc` but all made Parcel crash, such as:

~~~json
{
  "extends": "@parcel/config-default",
  "transforms": {
    "*.js": ["@parcel/transformer-babel"]
  }
}
~~~

~~~json
{
  "transforms": {
    "*.js": ["@parcel/transformer-babel"]
  }
}
~~~
~~~json
{
  "extends": "@parcel/config-default",
}
~~~
~~~json
{
}
~~~

## 🔦 Context

I'd like to build an SSR plugin.

## 💻 Code Sample

https://github.com/brillout/parcel-ssr

~~~js
yarn run build
~~~

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.1.1
| Node             | v12.2.0
| Yarn         | 1.16.0
| Operating System | Linux

**Comment by brillout** [comment]
Just tried with the latest v2 revision and it still crashes.

Repro:

https://github.com/brillout/parcel-ssr

`yarn build` where `../parcel` points to the v2 branch of the Parcel repository.

**Comment by DeMoorJasper** [comment]
@brillout is it the same error?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by brillout** [comment]
I'm currently hunting down the error by bisecting the execution path. Because Parcel crashes without printing any error to the console.

How can I temporarily set Parcel to not swallow errors?
