### ISSUE TITLE
Parcel doesnt open browser when using ssh.

### ISSUE THREAD

**Issue by vipulrawat** [parcel-bundler/parcel#3636]
# 🐛 bug report

## 🎛 Configuration ( package.json, cli command)

```js
{
 "scripts": {
    "start": "PARCEL_AUTOINSTALL=false yarn parcel serve public/index.html --port 3000 --open --no-cache",
}
```

## 🤔 Expected Behavior

`yarn start` should open the browser even if running through a remote ssh environment.

## 😯 Current Behavior
Current Env: Visual Studio Code, Remote Development, and using parcel (v.1.12.3) along with Typescript.
Running `start` command is not opening the browser automatically (and hence loses the HMR).

Error:

> Unexpected error while opening in browser: true
> Error: Exited with code 3
>     at ChildProcess.cp.once.code (/root/projects/project_name/node_modules/opn/index.js:85:13)
>     at Object.onceWrapper (events.js:286:20)
>     at ChildProcess.emit (events.js:198:13)
>     at maybeClose (internal/child_process.js:982:16)
>     at Socket.stream.socket.on (internal/child_process.js:389:11)
>     at Socket.emit (events.js:198:13)
>     at Pipe._handle.close (net.js:606:12)
## 💁 Possible Solution
The error is related to [opn](https://www.npmjs.com/package/opn). Upgrading opn package seems to fix the error, but browser is still not opening, not sure where to look into.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.16.3
| npm/Yarn         | yarn 1.17.3
| Operating System | Debian

**Comment by mischnic** [comment]
This is nearly impossible to do:
1. Generally, you don't want the server to be able to execute arbitrary commands on your local machine.
2. How should Parcel know under which hostname/ip your server is reachable?

> is not opening the browser automatically (and hence loses the HMR)

You could still use HMR by opening the URL in your browser "manually".

**Comment by vipulrawat** [comment]
Thanks @mischnic for the reply. I am seeing the issue, as a webpack seems to open the browser along with hot-reloading. Will see If I can come up with something.
Also, HMR doesn't work if I open the browser manually.

**Comment by mischnic** [comment]
> Also, HMR doesn't work if I open the browser manually.

Could you give more details here? Is there an error message?

**Comment by vipulrawat** [comment]
So there is no error message other than specified in the first message. I have forwarded my relevant ports to my local machine, so after `start` I open the browser and for the changes to see, I have do full page refresh every time.
