### ISSUE TITLE
Parcel v2 swallows errors

### ISSUE THREAD

**Issue by brillout** [parcel-bundler/parcel#3639]
# 🐛 bug report

I'm trying to figure out what is going on with the bug https://github.com/parcel-bundler/parcel/issues/3633 but it seems that Parcel is swallowing the JS error which makes it difficult to get to the source of the problem.

I'm running the latest revision of the v2 branch.

How can I make Parcel not swallow the error?

Repro: https://github.com/brillout/parcel-ssr/tree/parcel-bug_swallowed-error => `yarn start`

**Comment by mischnic** [comment]
Seems to be fixed in alpha 3
