### ISSUE TITLE
Not working when trying "Getting started" example

### ISSUE THREAD

**Issue by mnn** [parcel-bundler/parcel#364]
**Choose one:** 🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

No config.

### 🤔 Expected Behavior

It compiles JS/TS and serves the page.

### 😯 Current Behavior

```
> parcel index.html
(node:17920) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: EACCES: permission denied, open '/usr/local/share/.config/yarn/global/node_modules/anymatch/node_modules/array-unique/index.js'
(node:17920) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>
```

After error message it exits.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.2.1
| Node             | 7.7.3
| Yarn         |  0.17.3
| Operating System | Kubuntu 16.04 LTS

**Comment by antony** [comment]
Sounds like yarn has made a hash of your global modules. I'm pretty sure this isn't a parceljs bug. 

I'd be tempted to blow away `'/usr/local/share/.config/yarn/global/node_modules` and try again.

**Comment by mnn** [comment]
Tried removing `anymatch` from that directory (didn't want to lose other globally installed packages) and reinstalling `parcel`, it didn't help.

Uninstalled it from `yarn` and installed it via `npm` and now it works 😄, thanks. Not sure what is wrong with my `yarn` thought 😒.

**Comment by matthewblott** [comment]
I'm having the same problem, just did a global install on macOS using npm (I installed the latest version of Node prior). I hit ```parcel index.html``` in the terminal and nothing happens. None of the switches work.
