### ISSUE TITLE
Scope Hoisting for duplicate definition fails (sometimes)

### ISSUE THREAD

**Issue by garthenweb** [parcel-bundler/parcel#3640]
# 🐛 bug report

When including the `@sentry/browser `dependency and calling it's init function the build fails.
Maybe related to #3437 

## 🎛 Configuration (.babelrc, package.json, cli command)

No config files at all, just the default. See the example below, I am running it from a `tsx` file.

## 🤔 Expected Behavior

It should build the bundle without error and should include all the code that is necessary to run sentry.

## 😯 Current Behavior

Failing with

```
🚨 Got unexpected null
  at nullthrows (.../parcel-bundler/node_modules/nullthrows/nullthrows.js:7:15)
  at BundleGraph.resolveSymbol (.../parcel-bundler/packages/core/core/src/BundleGraph.js:504:29)
  at BundleGraph.resolveSymbol (.../parcel-bundler/packages/core/core/src/public/BundleGraph.js:128:27)
  at resolveSymbol (.../parcel-bundler/packages/shared/scope-hoisting/src/concat.js:184:32)
  at markUsed (.../parcel-bundler/packages/shared/scope-hoisting/src/concat.js:178:9)
  at enter (.../parcel-bundler/packages/core/core/src/Graph.js:531:16)
  at enter (.../parcel-bundler/packages/core/core/src/Graph.js:531:16)
  at enter (.../parcel-bundler/packages/core/core/src/Graph.js:531:16)
  at enter (.../parcel-bundler/packages/core/core/src/Graph.js:372:26)
  at walk (.../parcel-bundler/packages/core/core/src/Graph.js:392:22)
```

## 💁 Possible Solution

When logging the dependency in `BundleGraph.js:504` it is failing to resolve `./baseBackend.js` (sometimes also somewhere else, e.g. `./api.js`):
```
{
  moduleSpecifier: './basebackend',
  loc: { line: 5, column: 28 },
  env: {
    context: 'browser',
    engines: { browsers: [Array] },
    includeNodeModules: true,
    outputFormat: 'global',
    isLibrary: false
  },
  sourceAssetId: '7738236bb0d2b80bd3a62bc913f03b89',
  sourcePath: '.../project/node_modules/@sentry/core/esm/index.js',
  id: 'b25413759777ee0e1c0de158dda1eb15',
  meta: {},
  symbols: Map {
    'BaseBackend' => '$bb0d2b80bd3a62bc913f03b89$import$BaseBackend'
  },
  isWeak: true
}
```

In the first place, I thought it's due to the `BaseClient` which is declared as `var` and `function` within different scopes. This pattern is the same in all files that I saw failing, and after renaming by hand it went to the next function, it looks like:

``` js
const Test = (function() {
  function Test() {
    console.log('init');
  }
  Test.prototype.doStuff = function() {
    console.log('do stuff');
  };
  return Test;
})();

export { Test };
```

On the other hand, the bug does not happen all the time. In most cases, it is failing, but sometimes, when deleting the cache before, it even succeeds. Therefore, it looks like a race condition to me. E.g. I run the command twice after another, the first succeeds the second failed, without any code changes:

``` bash
$ rm -rf .parcel-cache && ../../npm-packages/parcel-original/packages/core/parcel/src/bin.js build src/index.tsx
✨ Built in 24.75s.
dist/index.js                                                             54.27 KB    2.38s
├── node_modules/@sentry/browser/esm/integrations/breadcrumbs.js          17.32 KB    854ms
├── node_modules/@sentry/hub/esm/hub.js                                   15.56 KB    246ms
├── node_modules/@sentry/core/esm/baseclient.js                           13.26 KB    465ms
├── node_modules/tslib/tslib.es6.js                                       13.03 KB    284ms
├── node_modules/@sentry/utils/esm/object.js                              11.36 KB    474ms
├── node_modules/@sentry/hub/esm/scope.js                                 11.01 KB    159ms
├── node_modules/@sentry/utils/esm/misc.js                                 9.88 KB    3.24s
├── node_modules/@sentry/browser/esm/helpers.js                            9.25 KB    224ms
├── ../../npm-packages/parcel-original/node_modules/process/browser.js     8.83 KB     82ms
└── node_modules/@sentry/browser/esm/tracekit.js                            7.6 KB    170ms
└── + 45 more assets

$ rm -rf .parcel-cache && ../../npm-packages/parcel-original/packages/core/parcel/src/bin.js build src/index.tsx
🚨 Got unexpected null
  at nullthrows (.../parcel-original/node_modules/nullthrows/nullthrows.js:7:15)
  at BundleGraph.resolveSymbol (.../parcel-original/packages/core/core/src/BundleGraph.js:504:29)
  at BundleGraph.resolveSymbol (.../parcel-original/packages/core/core/src/public/BundleGraph.js:128:27)
  at resolveSymbol (.../parcel-original/packages/shared/scope-hoisting/src/concat.js:184:32)
  at markUsed (.../parcel-original/packages/shared/scope-hoisting/src/concat.js:178:9)
  at enter (.../parcel-original/packages/core/core/src/Graph.js:531:16)
  at enter (.../parcel-original/packages/core/core/src/Graph.js:531:16)
  at enter (.../parcel-original/packages/core/core/src/Graph.js:531:16)
  at enter (.../parcel-original/packages/core/core/src/Graph.js:372:26)
  at walk (.../parcel-original/packages/core/core/src/Graph.js:392:22)
```

## 💻 Code Sample

Using `@sentry/browser@5.7.0`

``` js
import * as Sentry from '@sentry/browser';

Sentry.init({
  dsn: '...',
});
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2 (commit eedc965377940034cf78a026d581f12098df724e)
| Node             | v12.8.1 
| npm         | v6.11.2
| Operating System | Windows (Ubuntu Bash)

**Comment by garthenweb** [comment]
I have a similar issue with `@material-ui/core/TextField`.

``` js
{
  moduleSpecifier: './chainPropTypes',
  loc: { line: 6, column: 42 },
  env: {
    context: 'browser',
    engines: { node: '>=10.14.1', browsers: [Array] },
    includeNodeModules: true,
    outputFormat: 'global',
    isLibrary: false
  },
  sourceAssetId: 'a636bbfd9ba8aed7cd12e21fe0b46609',
  sourcePath: '/.../node_modules/@material-ui/utils/esm/index.js',
  id: '0befff5f54475c0de85c6531fd207e3a',
  meta: {},
  symbols: Map {
    'default' => '$a636bbfd9ba8aed7cd12e21fe0b46609$import$chainPropTypes'
  },
  isWeak: true
}
```

As the `chainPropTypes.js` looks completely different from the sentry example above, I have the feeling this might be more an issue with reexports like:
```
// node_modules/@material-ui/utils/esm/index.js
export { default as chainPropTypes } from './chainPropTypes';
// node_modules/@sentry/core/esm/index.js
export { BaseBackend } from './basebackend';
```

**Comment by mischnic** [comment]
The minimal reproduction I got for the sentry case is here: https://github.com/mischnic/parcel-issue-3640-sentry

It has to do with `@sentry/types` having `sideEffects: false`, doing reexporting in `@sentry/types/esm/index.js` then importing two different exports from that in two different assets.

Still trying to figure out why there is some dependency information missing in the asset graph...

![3640](https://user-images.githubusercontent.com/4586894/66716219-94acb000-edcb-11e9-85c1-251a42537ecc.png)

**Comment by mischnic** [comment]
The answer for future reference:

First (red), an asset imports the symbol "severity" via the reexporting entry, the other reexported symbol "status" is correctly ignored.
After that (blue), another asset imports the symbol "status" but the dependency resolves to the existing asset group and no dependencies further down are reevaluated (in this case, the excluded dependency in the bottom right that is now used).

![3640-2](https://user-images.githubusercontent.com/4586894/66719659-2ed41e80-edf3-11e9-8102-905cbfa90191.png)
