### ISSUE TITLE
Parcel v2: "from" node not found

### ISSUE THREAD

**Issue by garthenweb** [parcel-bundler/parcel#3641]
# 🐛 bug report

Running parcel v2 on a real project it throws with `"from" node '13fdc5570c2ac6b8eb5e93969ac5d141' not found`. 
When adding the `--no-scope-hoist` flag it is working.

I am executing `../parcel/packages/core/parcel/src/bin.js build src/client/client.tsx`.

## 🎛 Configuration (.babelrc, package.json, cli command)

I use typescript, custom babel config, postcss (with css modules activated).

## 🤔 Expected Behavior

It should bundle the app and include all required dependencies.

## 😯 Current Behavior

It is failing with the following error:

``` bash
🚨"from" node '13fdc5570c2ac6b8eb5e93969ac5d141' not found
    at Graph.addEdge (/.../parcel/packages/core/core/src/Graph.js:97:13)
    at addEdge (/.../parcel/packages/core/core/src/BundleGraph.js:616:15)
    at BundlerRunner.bundle (/.../parcel/packages/core/core/src/BundlerRunner.js:64:23)
    at Parcel.build (/.../parcel/packages/core/core/src/Parcel.js:223:25)
    at Parcel.run (/.../parcel/packages/core/core/src/Parcel.js:139:18)
    at Command.run (/.../parcel/packages/core/parcel/src/cli.js:174:7)
```

## 💁 Possible Solution

As mentioned above, it is working without scope hoisting.

## 🔦 Context

The project I am running this on is currently bundled with parcel v1 and I try to migrate/ test to the new version.

I added a log in `BundleGraph.js:616` with `console.log(edge)` to gather more information. It shows the following:

``` js
{
  from: '@@root',
  to: 'entry_specifier:/.../src/client/client.tsx',
  type: null
}
{
  from: 'entry_specifier:/.../src/client/client.tsx',
  to: 'entry_file:/<path>/src/client/client.tsx',
  type: null
}
{
  from: 'entry_file:/.../src/client/client.tsx',
  to: 'b79348f5132bf6692abe9552f2d5f089',
  type: null
}
{
  from: '13fdc5570c2ac6b8eb5e93969ac5d141',
  to: '759c86fd2b3fc999136531d4ec7ad08c',
  type: null
}
``` 

Variable `to` in this context is `759c86fd2b3fc999136531d4ec7ad08c`, type is `null`.

## 💻 Code Sample

As I don't have any idea where this fails I have a hard time to get something to reproduce. If you have questions that help finding out what is going wrong, I am happy to investigate further!

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2 (eedc965377940034cf78a026d581f12098df724e)
| Node             | v12.11.1
|Yarn         | v1.19.1
| Operating System | Max OS X 10.14.6

**Comment by mischnic** [comment]
Have you tried clearing the cache?

**Comment by garthenweb** [comment]
Ah, actually I thought I did. Just retried and now it is running through 🤦‍♀Thank you!
Should we keep this open as a bug with the cache or is it a known issue?

**Comment by mischnic** [comment]
Have you updated Parcel (switched commits) in between? In that case, the cache likely isn't verified  for integrity (because the version number didn't change but the format might have)

**Comment by garthenweb** [comment]
Unfortunately, no. I did a change in the `package.json` and removed the `main` entry that was for no good reason defined.
Later I also added the `browserslist` property and the issue appeared again.

**Comment by mischnic** [comment]
Does this still happen?

**Comment by garthenweb** [comment]
Didn't saw that for a while, I think it is fixed :)
