### ISSUE TITLE
Documentation of v2 Plugin API and best practices

### ISSUE THREAD

**Issue by RobertWHurst** [parcel-bundler/parcel#3651]
# 🙋 Feature request
It would be fantastic if we could have some basic documentation of Parcel's new plugin API, and some best practices to follow when developing new parts for parcel's ecosystem.

I'm currently developing a transform for vue files and have been able to make good headway using parcel's source as a reference, but the task would be much easier if I understood the intent and desires of the parcel team when using their APIs.

**Comment by DeMoorJasper** [comment]
We're definitely planning to create an entirely new docs site for Parcel 2 with more detailed information about how everything works so plugin development should become relatively straightforward.

Not entirely sure if anyone is already working on this
