### ISSUE TITLE
[2.0] "Cannot find module 'x' from 'y'"

### ISSUE THREAD

**Issue by wojtekmaj** [parcel-bundler/parcel#3653]
# 🐛 bug report

I tried running Parcel 2 alpha in my project to see how it goes, and I was presented with an error "Cannot find module...".

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// .babelrc
{
  "presets": [
    ["@babel/preset-env", {
      "modules": false,
      "useBuiltIns": "usage",
      "corejs": 3
    }],
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-optional-chaining"
  ],
}
```

CLI command: 
```js
    "start": "parcel src/index.html --cache-dir ./.cache/dev",
```

## 🤔 Expected Behavior

Parcel to successfully resolve paths and build the application like in 1.x

## 😯 Current Behavior

```
Server running at http://localhost:1234
🚨 Cannot find module '../components/pages/form/step_context' from '/Users/wojciech.maj/P
rojekty/cfola/src/hooks'
    at ResolverRunner.resolve (/Users/wojciech.maj/Projekty/cfola/node_modules/@parcel/co
re/lib/ResolverRunner.js:71:15)
    at async RequestGraph.resolvePath (/Users/wojciech.maj/Projekty/cfola/node_modules/@p
arcel/core/lib/RequestGraph.js:400:24)
    at async PromiseQueue._runFn (/Users/wojciech.maj/Projekty/cfola/node_modules/@parcel
/utils/lib/PromiseQueue.js:94:7)
    at async PromiseQueue._next (/Users/wojciech.maj/Projekty/cfola/node_modules/@parcel/
utils/lib/PromiseQueue.js:81:5)
```

And below the spinner is just stuck, rotating on:

```
⠏ Building checkmark.svg...
```

Obviously, this path (`/Users/wojciech.maj/P
rojekty/cfola/src/components/pages/form/step_context`) is very much there so I don't know why this problem occurred.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.2.1
| Node             | 12.4.0
| npm/Yarn         | 1.19.1
| Operating System | MacOS Catalina

**Comment by wojtekmaj** [comment]
Interestingly, running yarn-deduplicate and getting rid of multiple versions of Babel resolved this problem.

**Comment by mischnic** [comment]
Could you share a code sample or reproduction repo?

**Comment by wojtekmaj** [comment]
Ha! I stipped my repo down to several files and I figured it out.

So I ended up with this simple tree of dependencies:

```
index.html
  index.jsx
    useHello.js
      hello.jsx
```

Turns out that while `html` and `jsx` files are perfectly able to resolve `jsx` files, `js` files cannot. When I changed `hello.jsx` into `hello.js`it started building.

...until the next place in which I had the same situation.

**Comment by mischnic** [comment]
Just ran into this as well 🙈

**Comment by mischnic** [comment]
The reason is that `jsx` is missing in this array:
https://github.com/parcel-bundler/parcel/blob/96c25fa775395f005d6b483020d6b522d29d3dfe/packages/resolvers/default/src/DefaultResolver.js#L33

But the goal is to get rid of this hardcoded list anyway....

**Comment by wojtekmaj** [comment]
Can we get it on this hardcoded list just for now, for me to be able to continue testing Parcel 2 Alpha?
