### ISSUE TITLE
How to set less modifyVars When I Use Less

### ISSUE THREAD

**Issue by jimmycarry** [parcel-bundler/parcel#366]
How to set less modifyVars When I Use Less?

**Comment by brandon93s** [comment]
You can use a `.lessrc` file:

```js
//.lessrc
{
	"modifyVars": {
	  "@buttonFace": "#5B83AD",
	  "@buttonText": "#D9EEF2"
	}
}
```

**Comment by afc163** [comment]
Seem `lessrc` is not working.

**Comment by XavierLeTohic** [comment]
+1

**Comment by luisfcofv** [comment]
is this possible?

**Comment by pocesar** [comment]
works with less 2.7, just downgrade

**Comment by zcmgyu** [comment]
It doesn't work even installing less 2.7.3

**Comment by kidandcat** [comment]
@brandon93s this is not working, could you reopen the issue?

**Comment by urwork** [comment]
It doesn't work even installing less 2.7.0

@brandon93s 
this is not working, could you reopen the issue?

**Comment by helabenkhalfallah** [comment]
lessrc doesn't work, have you find a solution ?
