### ISSUE TITLE
Where does parcel store compiled typescript files cache? [QUESTION]

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [parcel-bundler/parcel#3660]
Have parcel installed globally on linux. In a project I use a package that contains only Typescript code (there is no js compiled version in it). And it seem to work just fine, but until I update that package to newer version. If I do so, then I can see updated sources in node_modules, but in a bundle there are only old sources from previous version of package. So my question is - where parcel does store typescript compiled files (or some sort of cache for it)?

**Comment by mischnic** [comment]
In a folder `.cache` next to your project's root folder (where the `package.json` is).

**Comment by DanielMazurkiewicz** [comment]
@mischnic I use no-cache option, so it is definitely not .cache directory, it os not even created with that option

**Comment by DanielMazurkiewicz** [comment]
Found reason, one of packages in node_modules had its own node_modules and there was that "magic" older version that was used in a bundle.
