### ISSUE TITLE
Vulnerabilities in @babel/preset-env => lodash

### ISSUE THREAD

**Issue by vernondegoede** [parcel-bundler/parcel#3663]
My project is using the latest `parcel-bundler` dependency. When running `npm audit`, I get 
several vulnerability warnings.

# 🐛 bug report

You can find the output of the `npm audit` command here: https://gist.github.com/vernondegoede/8c5219239c2be1bda8d24cc04376d6ee

## 🎛 Configuration (.babelrc, package.json, cli command)

`https://github.com/mollie/api-documentation/blob/master/package.json`

**Comment by DeMoorJasper** [comment]
These have been fixed in parcel 2 and aren't even real security issues...
