### ISSUE TITLE
How to prevent parcel find .babelrc in parent directory?

### ISSUE THREAD

**Issue by MarvelSQ** [parcel-bundler/parcel#3669]
why parcel need find config in project's parent directory?

1. while build my project, **parcel** start to install some babel dependencies.
2. these babel dependencies(babel version 6) doesn't work with babel@7, cause build failure.

i start to find the reason why parcel install these dependencies i don't need.

### REASON
**parcel try to find config form project dir to root dir.** and there is a .babelrc file in project's parent directory.
in [parcel-bundler/src/utils/config.js](https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/utils/config.js#L12).
```js
async function resolve(filepath, filenames, root = path.parse(filepath).root) {
  filepath = path.dirname(filepath);

  // Don't traverse above the module root
  if (filepath === root || path.basename(filepath) === 'node_modules') {
    return null;
  }

  for (const filename of filenames) {
    let file = path.join(filepath, filename);
    let exists = existsCache.has(file)
      ? existsCache.get(file)
      : await fs.exists(file);
    if (exists) {
      existsCache.set(file, true);
      return file;
    }
  }

  return resolve(filepath, filenames, root);
}
```
this function will find the target file till the root directory.

in [parcel-bundler/src/Asset.js](https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/Asset.js#L155), where start to find config file.
```js
let conf = await config.resolve(opts.path || this.name, filenames);
```
there's no root limit.

**Comment by MarvelSQ** [comment]
why there's no info to show that parcel is using uplevel config to install dependencies?

**Comment by zebrallel** [comment]
same problem

**Comment by CressZZ** [comment]
I think it is no need to find to find config form project dir to root dir.
It is confused.
