### ISSUE TITLE
Parcel 2: Package Manager API

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#3672]
# ❔ Question

Hello, as i'm using Parcel to make a testing tool, i was wondering if i could use the [Package Manager](https://github.com/parcel-bundler/parcel/tree/v2/packages/core/package-manager) that Parcel has, to install 'optional' dependencies on the fly when actually used.
Though i'm not sure how to use this package or if it's even possible to use it outside of Parcel ?

Could someone point me towards how to use it or tell me if it's not possible to do so.

Thanks :)

**Comment by mischnic** [comment]
An example:

```js
import {NodePackageManager} from '@parcel/package-manager';
import {NodeFS} from '@parcel/fs';

let packageManager = new NodePackageManager(new NodeFS());
let defaultConfig = await packageManager.require( // or .resolve
  '@parcel/config-default', // package specifier
  __filename // resolve from which file (not folder!)
);
```

**Comment by Banou26** [comment]
Thanks, work like a charm 👍
