### ISSUE TITLE
Basic .parcelrc crashes Parcel

### ISSUE THREAD

**Issue by brillout** [parcel-bundler/parcel#3676]
Using the following `.parcelrc` crashes the latest alpha release `2.0.0-alpha.2.1`.

~~~json
{
  "extends": "@parcel/config-default",
  "transforms": {
    "*.js": ["@parcel/transformer-babel"]
  }
}
~~~

Error thrown:

~~~shell
🚨 The expression evaluated to a falsy value:

  (0, _assert.default)(typeof v === 'string')


  (0, _assert.default)(typeof v === 'string')

    at assertString (/home/romu/tmp/parcel-ssr/node_modules/@parcel/scope-hoisting/lib/link.js:47:23)
    at /home/romu/tmp/parcel-ssr/node_modules/@parcel/scope-hoisting/lib/link.js:89:16
    at enter (/home/romu/tmp/parcel-ssr/node_modules/@parcel/core/lib/Graph.js:475:16)
    at enter (/home/romu/tmp/parcel-ssr/node_modules/@parcel/core/lib/Graph.js:475:16)
    at enter (/home/romu/tmp/parcel-ssr/node_modules/@parcel/core/lib/Graph.js:475:16)
    at walk (/home/romu/tmp/parcel-ssr/node_modules/@parcel/core/lib/Graph.js:310:26)
    at walk (/home/romu/tmp/parcel-ssr/node_modules/@parcel/core/lib/Graph.js:331:22)
    at Graph.dfs (/home/romu/tmp/parcel-ssr/node_modules/@parcel/core/lib/Graph.js:355:12)
    at Graph.traverse (/home/romu/tmp/parcel-ssr/node_modules/@parcel/core/lib/Graph.js:257:17)
    at Graph.filteredTraverse (/home/romu/tmp/parcel-ssr/node_modules/@parcel/core/lib/Graph.js:265:17)
~~~

Repro: https://github.com/brillout/parcel-ssr

Context: I want to build an SSR tool on top of Parcel.

Env: Linux / parcel@2.0.0-alpha.2.1 / node@12.2.0 / yarn@1.19.1

**Comment by mischnic** [comment]
Using scopehoisting requires that "@parcel/transformer-js" transforms the assets (and set some metadata). The only thing we can do here is give a better error message.  You should use a ˚.parcelrc` like this one:
```json
{
  "extends": "@parcel/config-default",
  "transforms": {
    "*.js": ["@parcel/transformer-babel", "@parcel/transformer-js"]
  }
}
```

**Comment by brillout** [comment]
Thanks it works now.

**Comment by brillout** [comment]
(I'm leaving this ticket open because of `The only thing we can do here is give a better error message`.)

**Comment by Cristy94** [comment]
> Using scopehoisting requires that "@parcel/transformer-js" transforms the assets (and set some metadata). The only thing we can do here is give a better error message. You should use a ˚.parcelrc` like this one:
> 
> ```json
> {
>   "extends": "@parcel/config-default",
>   "transforms": {
>     "*.js": ["@parcel/transformer-babel", "@parcel/transformer-js"]
>   }
> }
> ```

I to got the error `The expression evaluated to a falsy value:` and tried to add this as my .parcelrc, but it doesn't work:
```
{ [Error: Invalid Parcel Config]
  diagnostics:
   [ { message: 'Invalid Parcel Config',
       origin: '@parcel/core',
       filePath: '.parcelrc',
       language: 'json',
       codeFrame: [Object] } ],
  name: 'Error' }
```

**Comment by jessabyrne** [comment]
I have this issue in the latest nightlies of Parcel 2. Not in the alpha/beta. 

```
> parcel build public/index.html

🚨 Build failed.
@parcel/packager-js: The expression evaluated to a falsy value:

  (0, _assert().default)(typeof assetId === 'string')

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert().default)(typeof assetId === 'string')

    at ScopeHoistingPackager.resolveSymbol (/Users/me/me/myproject/portal/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:685:27)
    at ScopeHoistingPackager.buildReplacements (/Users/me/me/myproject/portal/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:594:27)
    at ScopeHoistingPackager.buildAsset (/Users/me/me/myproject//portal/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:414:39)
    at ScopeHoistingPackager.visitAsset (/Users/me/me/myproject/portal/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:369:17)
    at /Users/me/me/myproject/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:204:40
    at enter (/Users/me/me/myproject/portal/node_modules/@parcel/core/lib/Graph.js:543:16)
    at enter (/Users/me/me/myproject/portal/node_modules/@parcel/core/lib/Graph.js:543:16)
    at enter (/Users/me/me/myproject/portal/node_modules/@parcel/core/lib/Graph.js:543:16)
    at walk (/Users/me/me/myproject/portal/node_modules/@parcel/core/lib/Graph.js:403:26)
    at walk (/Users/me/me/myproject/portal/node_modules/@parcel/core/lib/Graph.js:425:22)
```

Adding `--no-scope-hoisting` to the build command fixes but is not ideal.


My .parcelrc looks like this:

```
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"],
    "*.{jpg,png,svg}": ["@parcel/transformer-raw"]
  }
}

```

using
```
    "@parcel/transformer-raw": "^2.0.0-beta.2",
    "@parcel/transformer-typescript-tsc": "^2.0.0-beta.2",
    "parcel": "^2.0.0-nightly.676",
```

**Comment by theoutlander** [comment]
I keep getting the following error with beta3.1

> @parcel/core: Invalid Parcel Config
node_modules/@parcel/config-default/index.json:99:14
   98 |   ],
>  99 |   "runtimes": {
>     |               ^
> 100 |     "browser": [
>     | ^^^^^^^^^^^^^^^^
> 101 |       "@parcel/runtime-js",
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 102 |       "@parcel/runtime-browser-hmr",
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 103 |       "@parcel/runtime-react-refresh"
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 104 |     ],
>     | ^^^^^^
> 105 |     "service-worker": [
>     | ^^^^^^^^^^^^^^^^^^^^^^^
> 106 |       "@parcel/runtime-js"
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 107 |     ],
>     | ^^^^^^
> 108 |     "web-worker": [
>     | ^^^^^^^^^^^^^^^^^^^
> 109 |       "@parcel/runtime-js"
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by arumsey** [comment]
I seem to be having the same behaviour as well using latest nightlies as well as `beta-3.1`.

```
@parcel/packager-js: The expression evaluated to a falsy value:

  (0, _assert().default)(typeof assetId === 'string')

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert().default)(typeof assetId === 'string')
```

With or without a `.parcelrc` I still get the same error. Adding `--no-scope-hoist` also appears to be the only workaround I can currently find.

```
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.js": ["@parcel/transformer-babel", "@parcel/transformer-js"],
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
}
```

**Comment by Krizz** [comment]
For me, it seems like updating from beta-3.1 to the latest nightly (2.0.0-nightly.688) fixed the issue.

**Comment by tomas-hartman** [comment]
I'm getting this error even with no `.parcelrc` when running `npx parcel build index.html --dist-dir dist`.

```json
"devDependencies": {
  "@parcel/transformer-js": "^2.0.0-beta.3.1",
  "@parcel/transformer-sass": "^2.0.0-beta.3.1",
  "parcel": "^2.0.0-beta.3.1"
}
```

Edit: `--no-scope-hoist` did help for now.

**Comment by johan-lejdung** [comment]
Same issue here on `2.0.0-nightly.714+f582ffdc`

It only seems to work when I disable `--no-scope-hoist`

**Comment by ghost** [comment]
> 
> 
> Same issue here on `2.0.0-nightly.714+f582ffdc`
> 
> It only seems to work when I disable `--no-scope-hoist`

same problem here. but --no-scope-hoist seems to fix

**Comment by mischnic** [comment]
> Same issue here on 2.0.0-nightly.714+f582ffdc

Can someone provide more details? The parcelrc used and the source files to trigger the error

Might be related to https://github.com/parcel-bundler/parcel/issues/6374 and https://github.com/parcel-bundler/parcel/issues/6378#issuecomment-851550777

**Comment by ptitjes** [comment]
@mischnic I too am getting this error with `beta.3.1` on one of my work application.

I would like to contribute a repro repo but I can't figure out what part of my code triggers it, and can't share the code.

Can you help me debug it so I can figure what's the problem and make a repro repo ?

**Comment by johan-lejdung** [comment]
@mischnic I wont be able to provide the source files, as it's a large private project unfortunately.

Is there any log files that I could provide? The project is a React project, and we essentially only updated the parcel version to v2 and added transformers for images as per the migration guide.

**Comment by hegner123** [comment]
@mischnic repo for reference. 

https://github.com/hegner123/react-portfolio/tree/parcel-err

**Comment by mischnic** [comment]
@hegner123 in your case, it's because you're using `@babel/preset-env` instead of `@parcel/babel-preset-env` (https://v2.parceljs.org/languages/babel/#extending-the-default-babel-config), which is bad for bundle size anyway.

The underlying problem is that using require instead of ESM imports for css files is broken (and in this case, Babel transpiles `import "./App.css"` into require). Does that explain/help fix the error for anyone else as well?

**Comment by tomas-hartman** [comment]
> @mischnic I too am getting this error with `beta.3.1` on one of my work application.
> 
> I would like to contribute a repro repo but I can't figure out what part of my code triggers it, and can't share the code.
> 
> Can you help me debug it so I can figure what's the problem and make a repro repo ?

@ptitjes Did you try to install different revisions of parcel before it started failing for you? I seem have to resolved this error (and some other) by:

1. updating __all__ parcel related packages to the same `beta.3.1` revision
2. removing `.parcel-cache`, `node_modules` and `package-lock.json`
3. clean reinstalling them and re-running the build

I suppose that some of the parcel subdependencies in package-lock were of later revisions and did not work well with `beta.3.1`, because when I ran `npm audit fix` after I made it work, it broke my building process anew.

**Comment by ptitjes** [comment]
@tomas-hartman so I indeed had an `"@parcel/reporter-bundle-analyzer": "^2.0.0-beta.3.1",` which was importing some nightly dependencies.

However, this does not fix the problem. I followed your advice:
1. completely removed the `reporter-bundle-analyzer` to only have a pinned `"parcel": "2.0.0-beta.3.1"`
2. removed `.parcel-cache`, all my `node_modules` directories and my `yarn.lock`
3. reinstalled and rebuild

But still:
```
🚨 Build failed.
@parcel/packager-js: The expression evaluated to a falsy value:

  (0, _assert().default)(typeof assetId === 'string')

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert().default)(typeof assetId === 'string')

    at ScopeHoistingPackager.resolveSymbol (/home/didier/Code/project/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:685:27)
    at ScopeHoistingPackager.buildReplacements (/home/didier/Code/project/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:594:27)
    at ScopeHoistingPackager.buildAsset (/home/didier/Code/project/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:414:39)
    at ScopeHoistingPackager.visitAsset (/home/didier/Code/project/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:369:17)
    at ScopeHoistingPackager.buildAsset (/home/didier/Code/project/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:395:41)
    at ScopeHoistingPackager.visitAsset (/home/didier/Code/project/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:369:17)
    at /home/didier/Code/project/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:464:54
    at String.replace (<anonymous>)
    at ScopeHoistingPackager.buildAsset (/home/didier/Code/project/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:433:17)
    at ScopeHoistingPackager.visitAsset (/home/didier/Code/project/node_modules/@parcel/packager-js/lib/ScopeHoistingPackager.js:369:17)
```

**Comment by ptitjes** [comment]
@mischnic I was able to identify the culprit by debugging `ScopeHoistingPackager.js`.

So I did a (somewhat) small reproduction repository:
https://github.com/ptitjes/test-parcel-2.0.0-beta.3.1

The problem happens when I import `@rmwc/button/styles` which itself tries to require `@material/button/dist/mdc.button.css`.

If I comment out this line in my `index.tsx`, the build succeeds.
If I add `--no-scope-hoist`, the build succeeds.
But if I let both the import and the scope hoisting, then I get the exact assertion error above.

Is there something ridiculous that I don't see in what I am doing ?
Thanks in advance for your help.

**Comment by ptitjes** [comment]
@mischnic do you have any clue as to how I can fix that ? how are those css imports supposed to be resolved ? I can attempt a fix if you give me some direction.

**Comment by johan-lejdung** [comment]
> @hegner123 in your case, it's because you're using `@babel/preset-env` instead of `@parcel/babel-preset-env` (https://v2.parceljs.org/languages/babel/#extending-the-default-babel-config), which is bad for bundle size anyway.
> 
> 
> 
> The underlying problem is that using require instead of ESM imports for css files is broken (and in this case, Babel transpiles `import "./App.css"` into require). Does that explain/help fix the error for anyone else as well?

This fixed it for me 👏

**Comment by ptitjes** [comment]
Does this mean that I should explicitely add a `.babelrc` file ? Doesn't Parcel define a correct configuration for Babel when none is provided by the user ?
