### ISSUE TITLE
texture load wrong colors.

### ISSUE THREAD

**Issue by sanprieto** [parcel-bundler/parcel#3677]
# 🐛 bug report

When I load a image with three.js to make a texture, colors of the image are wrong. 

## 🎛 Configuration (.babelrc, package.json, cli command)
{
  "name": "theWay",
  "version": "1.0.0",
  "description": "Basic algorithms to learn three.js",
  "main": "index.js",
  "dependencies": {
    "main.css": "^2.0.0",
    "parcel-bundler": "^1.12.3",
    "stats.js": "^0.17.0",
    "three": "^0.108.0",
    "three-orbitcontrols": "^2.108.1"
  },

## 💁 Possible Solution

I don't know if the problem is parcel but I make the same in other server and It's look fine.
![landscape](https://user-images.githubusercontent.com/33757425/67578854-9e2b0600-f743-11e9-81f0-6bbdb4f456b7.jpg)
The image with more light is parcel and the other is correct. 
Quality and color are very important for this project.

## 💻 Code Sample

  const urlData = require('/img/starts.jpg');
  const loader = new THREE.TextureLoader();
  const bgTexture = loader.load(urlData );
  scene.background = bgTexture;

Full code: https://github.com/sanprieto/BasicTestsThreejs/blob/master/Img/Background/index.js
The same example in other server.
http://sanprieto.es/pruebas/index.html

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | v10.0.0
| npm/Yarn         | 5.6.0
| Operating System |

**Comment by mischnic** [comment]
I have copied the JS script of the script tag on http://sanprieto.es/pruebas/index.html into the file you specified in the repo and it looked exactly the same. This is not caused by Parcel.
