### ISSUE TITLE
use with react-syntax-highlighter ，the  Program crash

### ISSUE THREAD

**Issue by yupeilin123** [parcel-bundler/parcel#3678]
# 🐛 bug report

## 😯 Current Behavior

![image](https://user-images.githubusercontent.com/28672197/67589181-78751f80-f78a-11e9-97d1-38d7b45c8519.png)

## 💻 Code Sample

```javascript
import SyntaxHighlighter from 'react-syntax-highlighter';
import { docco } from 'react-syntax-highlighter/dist/esm/styles/hljs';
const Component = () => {
  const codeString = '(num) => num + 1';
  return (
    <SyntaxHighlighter language="javascript" style={docco}>
      {codeString}
    </SyntaxHighlighter>
  );
};
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11.0
| Node             |  10.16.3
| npm/Yarn         | 6.12.0
| Operating System | mac10.14.5

**Comment by mischnic** [comment]
Please see https://github.com/parcel-bundler/parcel/issues/3176
