### ISSUE TITLE
[v2] Multi target wrongly builds browser target

### ISSUE THREAD

**Issue by brillout** [parcel-bundler/parcel#3679]
# 🐛 bug report

Multi target doesn't seem to work with the following.

`package.json`:

~~~json
{
  "name": "parcel-experiment",
  "version": "0.1.0",
  "scripts": {
    "build": "parcel build ."
  },
  "devDependencies": {
    "core-js": "2"
  },
  "dependencies": {
    "parcel": "2.0.0-alpha.2.1",
    "react": "^16.11.0"
  },
  "source": "./indx.js",
  "main": "dist/for-node.js",
  "browser": "dist/for-browser.js",
  "targets": {
    "main": {
      "engines": {
        "node": ">=4.x"
      }
    },
    "browser": {
      "engines": {
        "browsers": [
          "> 1%",
          "not dead"
        ]
      }
    }
  }
}
~~~

`indx.js`:

~~~js
import React from 'react'

const el = React.createElement('div');

console.log('bla for node/browser -- dirname:'+__dirname);

export default el;
~~~

`dist/for-node.js`:

~~~js
var a=b(require("react"));function b(e){return e&&e.__esModule?e.default:e}var c=a.createElement("div");console.log("bla for node/browser -- dirname:"+__dirname),exports.default=c;
~~~

`dist/for-browser.js`:

~~~js
var a=b(require("react"));function b(e){return e&&e.__esModule?e.default:e}var c="/home/romu/tmp/parcel-ssr",d=a.createElement("div");console.log("bla for node/browser -- dirname:"+c),exports.default=d;
~~~

The only difference between `dist/for-node.js` and `dist/for-browser.js` is that `__diranme` is replaced with a string for the browser which makes sense. But it doesn't make sense that the browser output is CJS and that it doesn't include the `react` dependency.

Repro: https://github.com/brillout/parcel-ssr/tree/multi-target-bug => `yarn install` => `yarn build`

Context: I'd like to build an SSR tool on top of Parcel.

Env: Linux / parcel@2.0.0-alpha.2.1 / node@12.2.0 / yarn@1.19.1

**Comment by DeMoorJasper** [comment]
Not entirely sure what the expected difference would be here?

**Comment by brillout** [comment]
> Although it probably should bundle React in the browser, is that the issue you see?

Yes.

> Not entirely sure what the expected difference would be here?

The browser output is CommonJS and `require()` and `exports.default=` will throw an error in the browser.

> `__DIRNAME`

That was a typo on my part, I meant `__dirname`. I updated the ticket; Parcel actually does build something different for the browser. But it's still CJS and doesn't bundle `react`.

**Comment by mischnic** [comment]
> The browser output is CommonJS and require() and exports.default= will throw an error in the browser.

Using the `browser` target in package.json is actually intended for a browser build of a library, add `"includeNodeModules": true`

If you want the same behavior as running parcel on an html file with `<script src=...>`, add this next to engines: `"outputFormat": "global"` and Parcel will throw this error: `External modules are not supported when building for browser` (what were you expecting here?).


Actually, both `"outputFormat": "global", "includeNodeModules": true` silently removes the export in `index.js`, seems like a bug.

**Comment by brillout** [comment]
Ok got it. Thanks!

Closing this in favor of https://github.com/parcel-bundler/parcel/issues/3697.
