### ISSUE TITLE
Empty object importing from node_modules css module

### ISSUE THREAD

**Issue by krokofant** [parcel-bundler/parcel#368]
I've been trying to import tachyons like a css module without success.
```js
import styles from "tachyons/css/tachyons.css"
console.log(styles)
```
Outputs `{}` while moving the file and importing locally `./` works. The path is correct and changing the path produces an error.

I've tried importing with path `../node_modules/tachyons/css/tachyons.css`

### 🎛 Configuration (.babelrc, package.json, cli command)
```json
  "devDependencies": {
    "autoprefixer": "7.2.3",
    "babel-plugin-transform-class-properties": "6.24.1",
    "babel-preset-env": "1.6.1",
    "babel-preset-react": "6.24.1",
    "parcel-bundler": "1.2.1",
    "postcss-modules": "1.1.0"
  },
  "dependencies": {
    "react": "16.2.0",
    "react-dom": "16.2.0",
    "tachyons": "4.9.0"
  }
```
.postcssrc
```json
{
  "modules": true,
  "plugins": {
    "autoprefixer": {
      "grid": true
    }
  }
}

```

### 🤔 Expected Behavior
I'm expecting the import to work like a css module when importing from node_modules or a relative path like `../node_modules/tachyons/css/tachyons.css`.

### 😯 Current Behavior
Outputs `{}`.

### 🌍 Your Environment

node v9.3.0
macOS High Sierra

**Comment by devongovett** [comment]
This is because parcel scopes configuration to a module level, so your `.postcssrc` does not apply to `node_modules`. In order to get this working, the module will also need a `.postcssrc` supporting css modules, e.g. `node_modules/tachyons/.postcssrc`.

**Comment by shtanton** [comment]
This isn't really a great solution as adding a postcssrc very time I update the library is pretty inconvenient.  Is there another way of doing this?

**Comment by krokofant** [comment]
@devongovett Any reason for this not to be handled automatically by parcel?

**Comment by devongovett** [comment]
This type of global configuration is dangerous. If the library you are importing from wasn't designed to use CSS modules, then if you overrode that in your application the original class names wouldn't be there and things probably wouldn't work correctly since the markup/javascript would still have the original classes not the css module ones.

**Comment by shtanton** [comment]
@devongovett That makes sense, but there still isn't a solution to the problem other than adding a .postcssrc to a library that may be overwritten by updates.

**Comment by mlewando** [comment]
Any change that it should be done somehow without putting .postcssrc into another libraries (eg. some parameter/configuration in parcel)?
First of all it feels rather wrong to me that I should put some file into library that I installed in my project. Secondly - this seems to just not work. I created .postcssrc file with modules set to true in the root of react-toolbox in my project and it still didn't import css modules correctly.
If I could create some plugin for parcel or add some parameter/configuration for it in order to process css modules from modules imported from node_modules, it would be awesome is someone could point me to a place in code when I should start investigation.

**Comment by Overbryd** [comment]
Has this been solved?

I am trying to get `react-toolbox` version 2.0 setup with `parcel`, adding `{"modules": true}` to `.postcssrc` did not help.

React and stuff works fine, but an unstyled page looks back at me.

How do I get `react-toolbox` (that is built upon `postcss` and `cssnext`) working with `parcel-bundler` ?

**Comment by krokofant** [comment]
@Overbryd It's ugly but it works (on unix-like systems at least...)
Add this as a npm script
```json
{
"scripts":{
"support-postcss-modules-react-toolbox":
      "echo '{\"modules\": true}' > node_modules/react-toolbox/.postcssrc",
}
}
```

**Comment by andyfangdz** [comment]
@devongovett Perhaps there can be an option to completely skip any transformations if a `.postcssrc` does not exist? :)

**Comment by bjankord** [comment]
#1292 is related
Really, they are the same issue, you could mark 1292 as duplicate.

> This type of global configuration is dangerous. If the library you are importing from wasn't designed to use CSS modules, then if you overrode that in your application the original class names wouldn't be there and things probably wouldn't work correctly since the markup/javascript would still have the original classes not the css module ones.

I agree, this is a valid concern and as a lib author intending for users to use CSS modules, I wouldn't want users to easily disable CSS modules and end up with the original classes not the css module ones in the DOM. I also see the value in adding a .postcssrc to our npm packages to specify they should use CSS modules and achieve what I'm trying to do with parcel.

## zero-config css modules idea
There is another idea I want to float by people interested in this. What are the member's of the parcel team (@devongovett @DeMoorJasper @jamiebuilds ) thoughts  on automatically parsing style files that end in `.module.css` / `.module.scss` / `.module.sass` / `.module.less` as a CSS modules based file? Wether they are local files in an app or imported from node_modules.

This could mitigate the concern quoted above. Users wouldn't risk turning off CSS modules via a global postcss config and impacting files that should be parsed as a CSS modules file as this would be handled by naming convention internally in parcel and aligns with the idea of zero-config.

In the create-react-app v2 branch, they've added support for this feature where [.module.css](https://github.com/facebook/create-react-app/pull/2285) and [.module.scss](https://github.com/facebook/create-react-app/pull/4195/files) are automatically run through CSS modules via [regex check on file names](https://github.com/facebook/create-react-app/blob/next/packages/react-scripts/config/webpack.config.dev.js#L51-L53).

[webpacker](https://github.com/rails/webpacker), a rails gem, also [supports this convention](https://github.com/rails/webpacker/pull/1248).

poi also [includes support](https://poi.js.org/guide/transforms.html#css-modules) for this feature.
