### ISSUE TITLE
`--no-autoinstall` is not respected for package.json in subdirectories

### ISSUE THREAD

**Issue by yash-tamakuwala** [parcel-bundler/parcel#3681]
# 🐛 bug report

I have a modular file structure like
```
/
- package.json
- index.html
- index.js
- src
  - ComponentA
     - A.jsx
     - A.scss
     - package.json
....


Event after running `parcel index.html --no-autoinstall` the dependencies in `A.jsx` doesn't respect /node-modules and auto-installs dependencies inside `/ComponentA` and adds dependencies in `ComponentA/package.json`. I am trying to migrate from webpack where this file structure works fine.
```

--

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets":  ["@babel/preset-env", "@babel/preset-react"],
  "plugins": [
    "@babel/transform-runtime",
    "@babel/plugin-proposal-class-properties"
  ]
}

```

## 🤔 Expected Behavior
parcel resolves dependencies in the root `node-modules` and doesn't create `node-modules` and yarn.lock inside the subdirectories

## 😯 Current Behavior

/
- package.json
- index.html
- index.js
- src
  - ComponentA
     - A.jsx
     - A.scss
     - package.json
     - node_modules
     - yarn.lock
....

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.4
| Node             |8.11.4
| Yarn         |1.9.4
| Operating System | macOS Catalina 10.15

**Comment by DeMoorJasper** [comment]
This has been fixed in Parcel 2
