### ISSUE TITLE
Differential builds instructions?

### ISSUE THREAD

**Issue by johanalkstal** [parcel-bundler/parcel#3682]
# ❔ Question

Could we get better docs on how to get differential builds as described in https://github.com/parcel-bundler/parcel/issues/3011 and https://medium.com/@devongovett/parcel-2-0-0-alpha-1-is-here-8b160c6e3f7e

Using `2.0.0-alpha.2.1`.

## 🔦 Context

Perhaps I'm not understanding the feature well enough but I've been unable to get something as described to work, where script tags with `module` and `nomodule` are automatically created based on targets.

I can get differential builds working by having two different targets in my `package.json` and running `parcel build src/index.html` but if I have a single `<script module src="main.js"></script>` then both will builds will have the `module` attribute.
If I have two script tags in my `index.html`, each with `module` and `nomodule` attributes then both builds will have the script tags but the `src` of both tags will point to the same file.

So I don't know how this is supposed to work so that you end up with one version that supports modules and another that doesn't?

**Comment by mischnic** [comment]
> are automatically created based on targets.

This isn't implemented yet, #3011 would be closed in that case.

> If I have two script tags in my index.html, each with module and nomodule attributes then both builds will have the script tags but the src of both tags will point to the same file.

This works for me:
```html
<script type="module" src="index.js"></script>
<script type="text/javascript" nomodule src="index.js"></script>
```

**Comment by johanalkstal** [comment]
> 
> 
> > are automatically created based on targets.
> 
> This isn't implemented yet, #3011 would be closed in that case.
> 
> > If I have two script tags in my index.html, each with module and nomodule attributes then both builds will have the script tags but the src of both tags will point to the same file.
> 
> This works for me:
> 
> ```
> <script type="module" src="index.js"></script>
> <script type="text/javascript" nomodule src="index.js"></script>
> ```

What do you mean "it works"?

What I end up with is both pointing to the same file (index.js) which can't be right. The same file can't both support and not support modules.

**Comment by johanalkstal** [comment]
We're saying that the module/nomodule feature isn't done yet? But the target builds are? If that's the case then I apologize for my assumptions. I thought they were the same thing.

**Comment by mischnic** [comment]
index.html:
```html
<script type="module" src="index.js"></script>
<script type="text/javascript" nomodule src="index.js"></script>
```
index.js
```js
const x = [1,2,3];
console.log(...x);
```
Running `parcel build index.html` generates two javascript bundles with different outputs (one is better optimized).
<br>



> But the target builds are?

They are rather intended for library builds (`module`/`main`/`browser`), detecting `type="module"` and `nomodule` works already, but automatically turning `<script type="application/javascript">` into module + nomodule isn't implemented yet.

**Comment by johanalkstal** [comment]
I see. `type="text/javascript"` seems to be the deciding factor here? It needs to exist for this to work?

**Comment by mischnic** [comment]
```html
<script type="module" src="index.js"></script>
<script nomodule src="index.js"></script>
```

Seems to work as well. Which setup have you tried that didn't work?

**Comment by johanalkstal** [comment]
Okay I spotted my mistake. I even wrote it in my initial comment.

`<script module src="main.js"></script>` instead of `<script type="module" src="main.js"></script>`. 🤦‍♂ 

Sorry for taking your time.

**Comment by mischnic** [comment]
😄
No worries.
