### ISSUE TITLE
v2: code splitting with `process` in shared module throws in child bundle

### ISSUE THREAD

**Issue by garthenweb** [parcel-bundler/parcel#3686]
# 🐛 bug report

When using styled-components within a parent and child bundle, the application throws at runtime with `TypeError: c(...).div is not a function`.
It looks like, within the child bundle, styled-components refers to the named imports instead of the default import.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
  "scripts": {
    "start": "rm -rf .parcel-cache dist && parcel build index.html && serve dist"
  },
  "dependencies": {
    "react": "^16.11.0",
    "react-dom": "^16.11.0",
    "styled-components": "^4.4.0"
  },
  "devDependencies": {
    "parcel": "^2.0.0-alpha.2.1",
    "serve": "^11.2.0"
  }
}
```

## 🤔 Expected Behavior

It should allow importing styled-components in a parent and child bundle with the same syntax.

## 😯 Current Behavior

Currently, it fails. It would work when using `styled.default.div` in the child bundle.

## 💻 Code Sample

EDIT: See a smaller sample [here](https://github.com/parcel-bundler/parcel/issues/3686#issuecomment-549055131).

index.html

```html
<!DOCTYPE html>
<main></main>
<script src="./index.js"></script>
```
index.js

```jsx
import React, { Suspense } from "react";
import { render } from "react-dom";
import styled from "styled-components";

const Page = React.lazy(() => import("./Page"));

const Section = styled.section`
  width: 100%;
`;

render(
  <Suspense fallback={null}>
    <Section />
    <Page />
  </Suspense>,
  document.querySelector("main")
);
```
page.js

```jsx
import React from "react";
import styled from "styled-components";

const Div = styled.div`
  width: 100%;
`;

const Page = () => <Div />;

export default Page;
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.2.1
| Node             | v12.8.1

**Comment by mischnic** [comment]
The main bundle uses (and therefore contains) `styled-components`. The async child bundle also uses that package, and imports it via `$parcel$interopDefault(parcelRequire(....))`. 
The issue here is that the main bundle seems to have optimized away the `$...styled-components....$exports.__esModule = true;` statement (therefore `$parcel$interopDefaul` fails in the child bundle and it won't find the `default` export, it treats `styled-components` as a CJS module).

Thank you so much for reporting all these bugs!

**Comment by garthenweb** [comment]
I hunted this down to a super simple example now. It looks like this is due to the usage of `process` within styled-components:

``` js
// main.js
import foo from "./foo";

import("./import");

console.log('main', foo === 'bar');

// import.js
import foo from "./foo";

console.log('import', foo === 'bar');

// foo.js
process // this triggers the conversion to cjs

export default 'bar'
```

When running in the browser it will output
```
main true
import false
```

But should be
```
main true
import true
```
This is due to `foo` being an object in `import.js`.

Any idea why this is happening? :)

**Comment by garthenweb** [comment]
I found out, because of `process`, `require('process')` is injected by parcel. Therefore, styled-components are marked as a common js module which then causes issues.
I added test cases and some more details here: https://github.com/parcel-bundler/parcel/pull/3730

Maybe someone has better ideas on how to resolve this, my current attempt does not look proper so far.

**Comment by garthenweb** [comment]
@mischnic I tried the nightly release in my project. Unfortunately, since we added the check for `bundleGraph.isAssetReferencedByAnotherBundleOfType(mod, 'js')`, the fix does not work in the project longer.

I am using multiple nested imports (so at least one time a dynamic import requests another dynamic import), maybe this is related.

Also, I use Typescript with JSX inside the project. But I assume `bundleGraph.isAssetReferencedByAnotherBundleOfType(mod, 'js')` should also work for typescript files, correct?

If I replace `isReferenced` with `let isReferenced = true`, it works as expected.

Any thoughts or ideas? If not I would need to put some more effort into creating a reproducible example/ tests.

Should we reopen this ticket?

**Comment by mischnic** [comment]
😞 

> `bundleGraph.isAssetReferencedByAnotherBundleOfType(mod, 'js')` should also work for typescript files, correct?

A typescript asset is transpiled into a javascript asset which becomes a javascript bundle, so yes.

**Comment by garthenweb** [comment]
I created a minimal example here: https://github.com/garthenweb/parcel-bug-report-examples/tree/bug/missing-esmodules-in-child-bundle

This is now an example without styled-components, as I found that it also fails using react standalone.

In a bigger project, it was randomly throwing for react but also for styled-components.

Actually, I figured that `let isReferenced = true` did not help in this case.
So I am not sure if this is still the same issue, but at least related as the `__esModule` flag is missing when requested in a child bundle via `parcelRequire("12345");`, so it looks highly related.

**Comment by garthenweb** [comment]
I have some findings on that:

When running parcel with `PARCEL_WORKERS=1` the build is passing.

In the example, page1 is working fine. It imports and uses react as following

```js
var $ea7b41558fa2f98$init = parcelRequire("80167699844891757ea7b41558fa2f98");
...
var $b8bc34563fd8293abd35d65d54d75$export$default = function Page1() {
  var $ea7b41558fa2f98$$interop$default = $parcel$interopDefault($ea7b41558fa2f98$init());
  return $ea7b41558fa2f98$$interop$default.createElement("div", null, "Page 1");
};
```

Where page2 looks as following
```js
var $ea7b41558fa2f98$exports = parcelRequire("80167699844891757ea7b41558fa2f98");
...
var $c302d056b50b4a5fdc682b4f5c4e00e$export$default = function Page2() {
  var $ea7b41558fa2f98$$interop$default = $parcel$interopDefault($ea7b41558fa2f98$exports);
  return $ea7b41558fa2f98$$interop$default.createElement("div", null, "Page 2");
};
```

So basically the init call is missing and therefore the function is passed to the `$parcel$interopDefault` function which for sure does not have an `__esModule` flag nor default export.

From what I understand some information in `asset.meta` is out of sync when running parcel with multiple workers. But this is more guessing.

Not sure where I could best search for those kind of issues. Any ideas or hints?

**Comment by mischnic** [comment]
> From what I understand some information in asset.meta is out of sync when running parcel with multiple workers. But this is more guessing.

👍 
PR to fix that (with an explanation): https://github.com/parcel-bundler/parcel/pull/4370

**Comment by garthenweb** [comment]
Nice! I can confirm it fixes this issue and would also close this ticket again.

**Comment by garthenweb** [comment]
Checked it one more time with `2.0.0-nightly.171` and it is still working! Therefore the ticket can be closed.
