### ISSUE TITLE
v2: CSS files empty in case data is defined in .sassrc.js for scss files

### ISSUE THREAD

**Issue by garthenweb** [parcel-bundler/parcel#3689]
# 🐛 bug report

When using a `sassrc.js` file and define a `data` config, only the code from the configuration is used but the real file is ignored.

## 🎛 Configuration (.babelrc, package.json, cli command)
.sassrc.js
```js
module.exports = {
  data: "$bg: red;"
}
```

## 🤔 Expected Behavior

Should merge the content of `data` together with the content of the imported file.

## 😯 Current Behavior

It only takes the content from the `data` config.

## 💁 Possible Solution

This looks like a compatibility issue with node-sass and I think this would be worth to support on dart-sass. Therefore I opened an issue on their repo: https://github.com/sass/dart-sass/issues/864

## 🔦 Context

While trying to migrate to v2 all my css files are empty.

## 💻 Code Sample

See https://github.com/sass/dart-sass/issues/864

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2 beta 2.1
| Node             | v12

**Comment by garthenweb** [comment]
@mischnic It turned out that this was constructed in parcel v1 before and is not a bug of dart sass. I found this code here which is doing the trick: https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/assets/SASSAsset.js#L31

Do you think we should port this to parcel v2? I guess this would require to load the sass files by parcel again and do the same construction that was done in v1.

If not, I would most probably need to override the existing sass transform with a custom one to make one of my projects work with parcel v2 as it heavily relies on this, but I am not sure how common this pattern is in the community.

I personally don't like that pattern too much as I think it can lead to heavily coupled code, but our project was already set up like that when using Weback before migration to Parcel and it is super hard to refactor all the files.

**Comment by mischnic** [comment]
So data contains some "global configuration" in your case?

> but I am not sure how common this pattern is in the community.

Me neither.

<br>

Either we treat data as a prelude for every sass asset (which is what you want), or we completely disallow using `data` (because the current behavior is clearly wrong).

**Comment by garthenweb** [comment]
> So data contains some "global configuration" in your case?

Yes, exactly. It contains variables for font sizes, colors and so on as well as mixings that thereby can be used in every file without importing them explicitly.

> Either we treat data as a prelude for every sass asset (which is what you want), or we completely disallow using data (because the current behavior is clearly wrong).

That makes sense, the current behavior is super useless. In case we don't want to support data, it would probably be nice to throw a warning/ error to let people know what is going on.

Maybe I can have a look at what it takes to support it. I guess this shouldn't be too hard to support. I just wonder whether it will cause issues with source maps. Do you have an insight into that?

**Comment by mischnic** [comment]
> In case we don't want to support data, it would probably be nice to throw a warning/ error to let people know what is going on.

Exactly.

> just wonder whether it will cause issues with source maps. Do you have an insight into that?

Parcel 2 doesn't output CSS sourcemaps (yet), but I assume that sass doesn't emit any sourcemaps if `options.data` is used instead of `options.filePath`.

Is there no other way to have global variables, e.g. using CSS variables (or do you have to support IE 😬)?

**Comment by garthenweb** [comment]
> Is there no other way to have global variables, e.g. using CSS variables (or do you have to support IE 😬)?

Haha, yes IE is still a thing over here :D But even without I would need to migrate a lot of files to a new pattern.
This issue is more of an easy transition path. I guess the best option to work around this would otherwise be to import those configurations explicitly in all files, which shouldn't be too hard to do...

**Comment by mischnic** [comment]
> I guess the best option to work around this would otherwise be to import those configurations explicitly in all files, which shouldn't be too hard to do...

That sounds cleaner from a code-style perspective.

<br>

Thinking about this more, we try to make parcel independent of the underlying filesystem (e.g. so it can run in the browser). So `options.filePath` doesn't really work either way (and I'll revert my opinion above about sass sourcemaps and `data`).
