### ISSUE TITLE
v2: Terser causing random hangs on circleci

### ISSUE THREAD

**Issue by magcius** [parcel-bundler/parcel#3696]
# 🐛 bug report

This might be one of the weirdest issues I've had to debug so far. I have no clue what might be causing it. I'm trying to run a build of Parcel on CircleCI, and it seems to hang somewhere inside Terser. I cannot reproduce the error locally. It only happens with a clean cache. I've added console.log statements to the Terser code to trace its execution, and it seems to hang or crash in different places each time.

I do not know if it's an error that's being raised, or something else going on, but execution seems to stop somewhere inside terser. I have tried adding try/catch statements, and no errors appear to be raised from my perspective.

The CPU cycles used up at this point are minimal, so I do not believe it is entering some weird state it cannot get out of. The only thing I can think of is that the connection to the worker process is somehow being dropped, but I do not know if terser is run in a worker process, nor would I know how to debug this.

## 🎛 Configuration (.babelrc, package.json, cli command)

The repo is located at https://github.com/magcius/noclip.website/tree/parcel-v2-no-hoist

I've had to SSH into a CircleCI session and edit files manually through the SSH connection to add in the debugging information. There's probably not much context I can give, but any information helps.

For now, I have reverted back to Parcel V1.

**Comment by mischnic** [comment]
Running our integration tests also hangs here (but only with recent Node newer than 12.10.x):
https://github.com/parcel-bundler/parcel/blob/7cf6a3ba6ba9764d4881fee30632c305c9be7724/packages/core/integration-tests/test/fs.js#L152-L176

**Comment by magcius** [comment]
Yes, my host is Windows, but I tried installing the same Docker image (circleci/node) locally on top of Docker for Desktop, and I couldn't reproduce. I believe Docker for Windows uses Hyper-V to run a Linux kernel inside it. It could be that the host kernels are different between CircleCI and Docker for WIndows, and that's the behavior difference, but the whole thing seemed odd to me.

**Comment by devongovett** [comment]
Yeah I think this is probably a node problem. We currently have CI pinned to 12.10.x because it was hanging in newer versions. Haven't had the time to investigate yet.

**Comment by magcius** [comment]
The node version I'm using is 10.16.3. Maybe I should try upgrading to 12.10.x and seeing if that helps. Bizarre that it doesn't reproduce locally though.

**Comment by mischnic** [comment]
Does this still happen?

**Comment by magcius** [comment]
I don't know. You're welcome to test it. I moved to WebPack a few months ago because of all the issues I was hitting with Parcel 2.
