### ISSUE TITLE
[V2] `"outputFormat": "global"` combined with `"includeNodeModules": true` removes export

### ISSUE THREAD

**Issue by brillout** [parcel-bundler/parcel#3697]
# 🐛 bug report
Source `indx.js`:

~~~js
console.log('bla for node/browser -- dirname:'+__dirname);

const answer = 42;

export default answer;
~~~

Parcel delivered bundle `dist/for-browser.js`:

~~~js
console.log("bla for node/browser -- dirname:/home/romu/tmp/parcel-ssr");
~~~

Note how `answer` and `42` disappears.

package.json:

~~~json
{
  "name": "parcel-experiment",
  "version": "0.1.0",
  "scripts": {
    "build": "parcel build ."
  },
  "devDependencies": {
    "core-js": "2"
  },
  "dependencies": {
    "parcel": "2.0.0-alpha.2.1"
  },
  "source": "./indx.js",
  "browser": "dist/for-browser.js",
  "targets": {
    "browser": {
      "includeNodeModules": true,
      "outputFormat": "global",
      "engines": {
        "browsers": [
          "> 1%",
          "not dead"
        ]
      }
    }
  }
}
~~~

Repro: https://github.com/brillout/parcel-ssr/tree/parcel-bug--no-export => yarn install => yarn build

Context: I'd like to do SSR with Parcel.

Env: Linux / parcel@2.0.0-alpha.2.1 / node@12.2.0 / yarn@1.19.1

**Comment by mischnic** [comment]
The inconsistency here is that `"outputFormat": "global"` throws `External modules are not supported when building for browser`, while `"outputFormat": "global", "includeNodeModules": true` doesn't throw an error.
