### ISSUE TITLE
[RFC] New plugin type `entry-finder`

### ISSUE THREAD

**Issue by brillout** [parcel-bundler/parcel#3699]
# 💬 RFC

This proposal is about adding a new plugin type "entry-finder" that determines how entry points are automatically found.

The goal of this Proposal is to have a list of entry points that is dynamic. Which is required for SSR.

Parcel's default behavior `Entry files default to package.json#source, falling back to src/index.* or index.*` would be implemented as a plugin `@parcel/entry-finder-default`:

~~~js
import {EntryFinder} from '@parcel/plugin';
import assert from 'assert';
import path from 'path';
import fs from 'fs';

// This is Parcel's default behavior implemented as
// a plugin `@parcel/entry-finder-default`.

export default new EntryFinder({
    // `findEntries` is called every time a project file is created/removed.
    async findEntries({projectFiles, projectRoot}) {
      // `projectFiles` is the list of all files contained (but not `.gitignore`'d)
      //  in the project directory.
      projectFiles.forEach(filePath => {
        // `filePath` is the path of the file relative to `projectRoot`
        assert(!path.isAbsolute(filePath));
        // To get the absolute path:
        assert(fs.existsSync(path.join(projectRoot, filePath)));
      });

      const pkgJsonExists = projectFiles.find(filePath => filePath==='package.json');
      const pkg = (
        pkgJsonExists &&
        require(path.join(projectRoot, 'package.json'))
      );
      if( pkg.source ){
        return [{
          entry: path.join(projectRoot, pkg.source),
          target: pkg && pkg.target || 'browser',
        }];
      }

      const idx1 = projectFiles.find(filePath => filePath.startsWith('src/index.'));
      const idx2 = projectFiles.find(filePath => filePath.startsWith('index.'));
      if( !idx1 && !idx2 ){
        return [];
      }
      return [{
        entry: path.join(projectRoot, idx1 || idx2),
        target: pkg && pkg.target || 'browser',
      }];
    }
});
~~~

In the context of an SPA, this proposal doesn't add much value. But it does for SSR.

For example, Next.js would do something like this:

~~~js
import {EntryFinder} from '@parcel/plugin';
import path from 'path';

export default new EntryFinder({
    async findEntries({projectFiles, projectRoot}) {
      return (
        projectFiles.map(filePath  => {
          // All `*.js` files in the `pages/` directory are added as entry:
          if( filePath.split(path.sep)[0]==='pages' && filePath.endsWith('.js') ){
            return {
              entry: path.join(projectRoot, filePath),
              target: 'universal', // (`universal` is a target to build a
            };                     // `browser` bundle and a `node` bundle.)
          } else {
            return null;
          }
        })
        .filter(p => p!==null)
      );
    }
});
~~~

The thing is that SSR tools (and SSGs as well) generate a separate bundle for each page. This means that, every time the user creates a new page, Parcel needs to bundle a new entry. In other words, the list of entry points is dynamic.

That's why `findEntries` needs to be called every time a project file is created/removed.

A glob is not sufficient:
- A glob is limiting. For example, how would you implement Parcel's default behavior I mentioned above as a glob? AFAICT, it's not possible.
- An `entry-finder` plugin can be set by config: for example, `@parcel/entry-finder-default` would be included in the `@parcel/config-default` config. I would implement a `parcel-entry-finder-ssr` that would be included in a config `parcel-config-ssr`; a Parcel user could then add SSR to its app simply by adding `parcel-config-ssr`. The bottom line being that the logic of how entry points are determined should be included in `parcel-config-ssr` and not in the user's `package.json`.

Let me know if anything is not clear &mdash; I'm happy to elaborate and further explain where I am coming from.

## 🔦 Context

This is required by SSR frameworks such as Next.js or Nuxt.

I'd like to develop a set of SSR plugins and a `parcel-config-ssr` config. Frameworks like Next.js or Nuxt could use the plugins I'm writing.

This is also required by SSG frameworks such as Gatsby or Vuepress. (They also have the situation where each page is built into a separate bundle.)

**Comment by devongovett** [comment]
Would `pages/*.js` as a glob not be enough? Btw, we currently don't implement `src/index.*` or `index.*`. We only have file, directories with package.json#source, or globs of both of those. See https://github.com/parcel-bundler/parcel/blob/v2/packages/core/core/src/EntryResolver.js

**Comment by DeMoorJasper** [comment]
Frameworks like Next would probably wrap Parcel into their own cli as they do a lot more advanced stuff than just searching for entries it would also be required for injecting babel configs and such... In dev mode they for example only bundle active pages (pages visited in last x secs) so entries will be very dynamic in that case, however this behavior might not be necessary as parcels cache would make that obsolete.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by brillout** [comment]
I had some situations where a glob wasn't enough but I just found a trick to make it work. (The trick, in case you are curious: by using a suffix, e.g. `.page.js`, you can filter after any type of files you want.)

So glob can work out, I guess.

Closing this RFC in favor of [#3700 - [RFC] Make Parcel fully configurable in .parcelrc](). (@DeMoorJasper this new ticket includes a rational of why I'm trying to implement SSR as a Parcel config.)
