### ISSUE TITLE
Code splitting and libraries

### ISSUE THREAD

**Issue by christianalfoni** [parcel-bundler/parcel#37]
Hi there!

Awesome work on this tool. So happy to see that build tools are still being iterated and improved upon 👍

I have a question related to code splitting. If I have two different lazy imports and both of them require for example `moment`. Will moment be included in both of those bundles? How does it resolve these kinds of dependency graphs?

I can contribute with docs on this, just have to know how it works :)

**Comment by devongovett** [comment]
Common dependencies will be hoisted up to the nearest common ancestor, so they'll only be included once (in the parent bundle). There is a bit more info about how Parcel works here: https://parceljs.org/how_it_works.html.

**Comment by christianalfoni** [comment]
Aha, great, thanks for the info. Will suggest some info on this in the `Code splitting` section :)
