### ISSUE TITLE
🐛 HTML not generated when building

### ISSUE THREAD

**Issue by KokoDoko** [parcel-bundler/parcel#370]
First of all thanks for developing this awesome tool!

I'm not sure if I'm just misunderstanding Parcel, or if there is actually a bug. I am following the simple [hello world example](https://parceljs.org) on Parcel's homepage.

### 🤔 Expected Behavior

When building for production with `parcel build index.js`, I would expect:

```
     dist
          style.css
          index.js
          image.jpg
          index.html
```

### 😯 Current Behavior

But I get this, The image name is garbled and there is no HTML.

```
     dist
          style.css
          index.js
          34534534543.jpg
```

If I try `parcel build index.html` then there is a HTML file, but ALL file names are garbled, and the path to those files from the html file is wrong... 

      dist
          34905873.css
          3049534.js
          345830459.jpg
          index.html // contains wrong paths to the css/js files

How do I use the build command correctly?

### 💁 Possible Solution

Perhaps write a clearer explanation of the production process on the website, or include a troubleshooting section. The github repo could also include a working hello world example.😇

### 🌍 Your Environment

Parcel 1.2.1  
Node 9.2.0         
npm 5.6.0        
Operating System MacOS Sierra 

Perhaps related: when installing `parcel-bundler` I get lots of errors related to `fsevents`. Installing `npm install -g fsevents` separately also produces these errors.

**Comment by DeMoorJasper** [comment]
U should probably use a script tag in the index.html and link that to index.js
And than use index.html as entrypoint instead of index.js
Not sure how your files look though

**Comment by KokoDoko** [comment]
I am literally copy>pasting the example from the [Parcel homepage](https://parceljs.org)

```
src
    main.css
    main.js
    index.html
    background.jpg
```

**Comment by DeMoorJasper** [comment]
The example says run ``parcel index.html``, so i guess that's what you gotta do to make it include html

**Comment by KokoDoko** [comment]
`parcel index.html` starts the development server. That works. But, to [build for production](https://parceljs.org/production.html), it says to run `parcel build index.js`

But if I do that, the html file is not generated in `dist`.

**Comment by DeMoorJasper** [comment]
Ow that must be a mistake in the docs, it should be ``parcel build index.html``

**Comment by DeMoorJasper** [comment]
However could u point me to where u found this, because i can't seem to find anything except for a totally different example about building an asset.js file

**Comment by KokoDoko** [comment]
I found the hello world example on https://parceljs.org and the production instructions here : https://parceljs.org/production.html. 

Perhaps there is a difference between `index.js` and `entry.js`? The production instructions say:

> When it comes time to bundle your application for production, you can use Parcel's production mode.
> `parcel build entry.js`
> This disables watch mode and hot module replacement so it will only build once.

**Comment by DeMoorJasper** [comment]
It looks fine to me... Bundlers always hash filenames else there is no way to prevent names from being the same.
to change the path issue just use ``parcel build index.html --public-url ./``
This is also in the docs... https://parceljs.org/production.html#set-the-public-url-to-serve-on

**Comment by KokoDoko** [comment]
Thanks for helping out, this works! I didn't think changing the public url was needed, because `dist` is already the default folder.
