### ISSUE TITLE
--no-autoinstall does not work and TS absolute path imports are not honored.

### ISSUE THREAD

**Issue by ahahn95** [parcel-bundler/parcel#3724]
# 🐛 bug report

Whenever I try to start my app, parcel will try to install the [dev](https://www.npmjs.com/package/dev) npm dependency instead of referencing the dev directory that I have in my `src` directory

## 🎛 Configuration (.babelrc, package.json, cli command)

This is my start script
`parcel serve src/dev/index.html --no-autoinstall`

Here is an example of an import
`import { App } from "dev/App";`

This is my tsconfig.json

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es6",
    "strict": true,
    "esModuleInterop": true,
    "baseUrl": "./src",
    "noUnusedLocals": true,
    "alwaysStrict": true,
    "jsx": "react",
    "noImplicitAny": true,
    "noImplicitThis": true,
    "strictNullChecks": true,
    "paths": {
      "~*": ["./*"]
    }
  },
  "include": ["src/**/*"]
}

```

## 🤔 Expected Behavior

The packages should not auto install, and my files in my local directories should be used

## 😯 Current Behavior

Packages are being installed without asking for them etc.

## 💁 Possible Solution

¯\_(ツ)_/¯

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 13.0.1
| npm/Yarn         | 6.12
| Operating System | macOS Catalina

**Comment by damianobarbati** [comment]
Same happens for `--no-cache` flag, not honored :)

**Comment by mischnic** [comment]
> Same happens for --no-cache flag, not honored :)
The .parcel-cache folder is always created.

That folder is needed to send data between workers and the main thread during bundling. Using `--no-cache` won't reuse the cache from a previous run.

**Comment by Lizhooh** [comment]
me too

**Comment by mischnic** [comment]
Parcel interprets the module specifier `"dev/App"` as "the file App.* in the package `dev`" (how it would work in JS), because baseUrl isn't honored: https://github.com/parcel-bundler/parcel/issues/1378.
