### ISSUE TITLE
Parcel 2: PNGQuant Optimizer

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#3734]
Create the `@parcel/optimizer-pngquant` package. This should include an Optimizer plugin that compresses PNG images with [PNGQuant](https://github.com/kornelski/pngquant). Ideally, this should wrap a C++ module to call [libimagequant](https://github.com/ImageOptim/libimagequant) rather than relying on writing temporary files and calling command line tools. Perhaps such a module already exists, otherwise we could create one. If this proves too difficult, shelling out to a command line tool could be a good starting point.

This plugin should be included in `@parcel/config-default` for `*.{png}` to optimize PNGs by default in production.

## Configuration

Optional configuration should be done through a `.pngquantrc` file. We should include good default settings, but it should be possible to override them if needed. See [here](https://github.com/kornelski/pngquant#options) for available options.

**Comment by hsablonniere** [comment]
Hello,

* I just created a local plugin to do that in my own project.
* I don't have any tests.
* I don't use any configuration file.

I may have some time to help on this but I need some guidance :wink:

**Comment by devongovett** [comment]
Going to close this. Parcel's default image optimizer optimizes pngs with optipng. A PNGQuant optimizer would be a good third party plugin.
