### ISSUE TITLE
Parcel 2: SVGO Optimizer

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#3735]
Create the `@parcel/optimizer-svgo` package. This should include an Optimizer plugin that compresses SVG images with [SVGO](https://github.com/svg/svgo).

This plugin should be included in `@parcel/config-default` for `*.svg` to optimize SVGs by default in production.

## Configuration

Optional configuration should be done through a `.svgorc` file. We should include good default settings, but it should be possible to override them if needed. See [here](https://github.com/svg/svgo#what-it-can-do) for a full list of options.

**Comment by DeMoorJasper** [comment]
Has been implemented by #4108

**Comment by devongovett** [comment]
Hmm that implemented svgo as a transformer not an optimizer... should it be an optimizer though?

**Comment by DeMoorJasper** [comment]
For the use-case it got implemented it can't be, svgo has to run before the svg-react transformer

**Comment by aminya** [comment]
How do I enable svgo? It doesn't seem to work. I added the following to my `.parcelrc`
```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{svg}": ["@parcel/transformer-svgo"]
  }
}
```

**Comment by mischnic** [comment]
`"*.{svg}"` is not a valid glob, it should be `"*.svg"`

**Comment by aminya** [comment]
I changed it to `"*.svg`, but still it doesn't remove comments from the svg file. The file isn't minified and the comment isn't removed.

index.js
```js
import star from "url:./star.svg"
```

star.svg
```svg
<svg height="210" width="500">
<!-- Star -->
  <polygon points="100,10 40,198 190,78 10,78 160,198" style="fill:lime;stroke:purple;stroke-width:5;fill-rule:nonzero;"/>
</svg>
```

.parcelrc
```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.svg": ["@parcel/transformer-svgo"]
  }
}
```

**Comment by mischnic** [comment]
What you specified in the config isn't actually being used. You need to either use
- `"*.svg":` and `import star from "./star.svg";` or
- `"url:*.svg": ` and `import start from "url:./star.svg";`

**Comment by aminya** [comment]
Now, this is the error that I get:
```js
@parcel/packager-raw: Raw bundles must only contain one asset
AssertionError [ERR_ASSERTION]: Raw bundles must only contain one asset
    at Object.package (C:\Users\aminy\node_modules\.pnpm\@parcel+packager-raw@2.0.0-beta.3.1\node_modules\@parcel\packager-raw\lib\RawPackager.js:39:23)
    at PackagerRunner.package (C:\Users\aminy\node_modules\.pnpm\@parcel+core@2.0.0-beta.3.1\node_modules\@parcel\core\lib\PackagerRunner.js:375:27)
    at async PackagerRunner.getBundleResult (C:\Users\aminy\node_modules\.pnpm\@parcel+core@2.0.0-beta.3.1\node_modules\@parcel\core\lib\PackagerRunner.js:336:20)
    at async PackagerRunner.getBundleInfo (C:\Users\aminy\node_modules\.pnpm\@parcel+core@2.0.0-beta.3.1\node_modules\@parcel\core\lib\PackagerRunner.js:328:9)
    at async Child.handleRequest (C:\Users\aminy\node_modules\.pnpm\@parcel+workers@2.0.0-beta.3.1_@parcel+core@2.0.0-beta.3.1\node_modules\@parcel\workers\lib\child.
js:255:9)
C:\Users\aminy\dist\Home.HASH_REF_66d8485a5709c6894251544728f395c6.svg
 ERROR  Command failed with exit code 1.
```

Another question: why isn't SVG handled like other image types? SVG is part of the web standard.
https://developer.mozilla.org/en-US/docs/Web/SVG

**Comment by mischnic** [comment]
Looks like you need `["@parcel/transformer-svgo", "@parcel/transformer-raw"]` (not sure if just adding `"..."` works)

> Another question: why isn't SVG handled like other image types? SVG is part of the web standard.

What do you mean, There is no special handling for it in the default config: https://github.com/parcel-bundler/parcel/blob/v2/packages/configs/default/index.json

**Comment by aminya** [comment]
> Looks like you need ["@parcel/transformer-svgo", "@parcel/transformer-raw"] (not sure if just adding "..." works)

Thanks. Now it works.

To make SVG optimization work in Parcel I need to install `@parcel/transformer-svgo` and add the following to `.parcelrc`
```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "url:*.svg": ["@parcel/transformer-svgo", "@parcel/transformer-raw"]
  }
}
```

>
> >Another question: why isn't SVG handled like other image types? SVG is part of the web standard.
>
> What do you mean, There is no special handling for it in the default config: https://github.com/parcel-bundler/parcel/blob/v2/packages/configs/default/index.json

@devongovett mentioned [in the OP](https://github.com/parcel-bundler/parcel/issues/3735#issue-516906033) that "This plugin should be included in @parcel/config-default for *.svg to optimize SVGs by default in production.". But this isn't the case now.

**Comment by mischnic** [comment]
Yeah, that is indeed not ideal. But the main reason svgo is a transformer right now instead of an optimizer (like for css and html) is that the minification is required for svg-react transformer.

I think it would make sense to merge `"@parcel/transformer-svgo"` into `"@parcel/transformer-svg-react"` and add a svgo optimizer.

**Comment by devongovett** [comment]
We also need an SVG transformer that detects dependencies like images or `<use>` references in SVG files.

**Comment by mischnic** [comment]
-> https://github.com/parcel-bundler/parcel/issues/2901

One problem with that was that this transformer should run without  specifying `url:` when used from HTML/CSS but still require `url:` from JS.

**Comment by devongovett** [comment]
I believe that's how URL dependencies already work? Ie you can refer to images without url: from CSS but not JS.

**Comment by mischnic** [comment]
But in that case, no transformer at all runs. For example to access the image transformer from CSS, you need to specify `url:`

**Comment by devongovett** [comment]
Ah that's unfortunate

**Comment by aminya** [comment]
For now, should not we add a documentation page to show how to make this work manually until this works automatically and by default?

**Comment by artdevgame** [comment]
> To make SVG optimization work in Parcel I need to install `@parcel/transformer-svgo` and add the following to `.parcelrc`
> 
> ```json
> {
>   "extends": "@parcel/config-default",
>   "transformers": {
>     "url:*.svg": ["@parcel/transformer-svgo", "@parcel/transformer-raw"]
>   }
> }
> ```

I can't seem to get this to work in my project, I'm using `--public-url .` CLI option, could that be making a difference?

The error I get is something like:
> react-dom.development.js:11340 Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('/discord.d697f2b7.svg') is not a valid name.

Looks like it's relying on a url path, where I need it to start with `./`

**Comment by elozev** [comment]
I found a workaround solution. Create a `.parcelrc` file at the root of the project.
As contents put the following
```
{
  "extends": "@parcel/config-default",
  "transformers": {
    "url:*.svg": ["@parcel/transformer-svgo", "@parcel/transformer-raw"]
  },
  "optimizers": {
    "*.{png,jpg,jpeg,svg}": []
  },
}
```

That solved the issue for me. The command to build the project in my case is: `"build": "parcel build *.html --no-cache"`.
