### ISSUE TITLE
Parcel 2: WebP Transformer

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#3736]
Create the `@parcel/transformer-webp` package. This should include a Transformer plugin that converts images to [WebP](https://developers.google.com/speed/webp) format. Ideally, this should wrap a C++ module to call [libwebp](https://developers.google.com/speed/webp/docs/api) rather than relying on writing temporary files and calling command line tools. Perhaps such a module already exists, otherwise we could create one. If this proves too difficult, shelling out to a command line tool could be a good starting point.

## Configuration

Optional configuration should be done through a `.webprc` file. We should include good default settings, but it should be possible to override them if needed. See [here](https://developers.google.com/speed/webp/docs/cwebp) for a full list of options.

We could also support passing options via query params for image-specific configuration. (??)

## Default Parcel Config

This transformer should be included in `@parcel/config-default` under a `webp:` named pipeline:

```json
{
  "transforms": {
    "webp:*.{jpg,jpeg,png,tiff,webp}": "@parcel/transformer-webp"
  }
}
```

This allows it to be used like the following to convert images in source code:

```html
<picture>
  <source type="image/webp" srcset="webp:./image.jpg">
  <source type="image/jpeg" srcset="./image.jpg">
  <img src="./image.jpg">
</picture>
```

The same original JPEG image is referenced in both `<source>` tags, but the first is converted to webp by Parcel via the named pipeline. This won't only work in HTML, but also in other places. For example, you could reference an image from CSS like this:

```css
.header {
  background-image: url("webp:./header.jpg");
}
```

**Comment by joshbedo** [comment]
Any details on how this works? I couldn't get the WebP transformer to work correctly the last time I tried.

**Comment by mischnic** [comment]
https://github.com/parcel-bundler/parcel/blob/064ba0a166ea63ccd2b623dc11324d4cd7ffb526/packages/core/integration-tests/test/integration/image/reformat.html#L1
