### ISSUE TITLE
Return es module default export directly

### ISSUE THREAD

**Issue by bedisdover** [parcel-bundler/parcel#3743]
# 🙋 feature request

Could parcel determine if a module only has a default export and no named exports, returns the default export directly, rather than an object with a named export `default`.

Example, for this file `add.js`
```js
export default (a, b) => a + b
```
run `parcel build add.js --experimental-scope-hoisting --global add`, got
```
(function () {  
  var a = {}, b = function ($, t) {return $ + t}
  a.default = b
 // ... module codes
// this['add'] = a
})()
```
I need to write `add.default(1, 2)` to call this func. It will be convenient if parcel returns the default export, which can be called by `add(1, 2)`.

## 🤔 Expected Behavior
What if returning the default export directly, something like:
```
(function () {  
  var a = {}, b = function ($, t) {return $ + t}
  if (`no named exports`) {a = b}
  else {
    a.default = b
    a[`one named exports`] = `named exports`
    // other named exports
  }
 // ... module codes
})()
```

## 💁 Possible Solution
Rollup iife works well for example
Output of `rollup test.js --format iife --name add`
```
var add = (function () {
  'use strict'
  var test = (a, b) => a + b
  return test
}())
```
with named exports
```
const foo = 1
export { foo }
export default (a, b) => a + b
```
the output:
```
var add = (function (exports) {
  'use strict'
  const foo = 1
  var test = (a, b) => a + b
  exports.default = test
  exports.foo = foo
  return exports
}({}))
```

**Comment by mischnic** [comment]
I think Parcel 2 does something like this already, though exporting to a global variable isn't supported yet.
