### ISSUE TITLE
Filename replacement differs in CLI and API

### ISSUE THREAD

**Issue by geoynomous** [parcel-bundler/parcel#3744]
# ❔ Question

I have an `angular.application.html` which contains

`<script type="text/javascript" src="./src/js/application.js"></script>
`

If I run the bundler from CLI 

`$ parcel watch src/*.html`

 it gets replaced to

`<script type="text/javascript" src="/application.6edd8711.js"></script>
`

However, if I run the bundle in the API mode within node + express

```
    const bundler = new Bundler('./src/*.html');
    bundler.bundle();
```
it gets replaced to 

`<script type="text/javascript" src="/5b5cc26e63a107f79379da8b728234a0.js"></script>
`

Note the filename difference! However the actual problem is: **The file `5b5cc26e63a107f79379da8b728234a0.js` is not created.**

Why is there a difference? When does it happen? Why? Where are the two hashes (6edd8711, 5b5cc26e63a107f79379da8b728234a0) created - and why do the differ in the two difference settings? And why do the two filenames differ in the two different settings.

## 🔦 Context

Trying to have things in the node-express setting and not on the CLI

## 💻 Code Sample

see inline

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 12.13.0
| npm/        | 6.12.0
| Operating System | MacOS

**Comment by geoynomous** [comment]
There seems to be another difference. (In docker) the globally installed parcel-bundler works fine

`parcel build *.html
`

while (the same parcel version from local node_modules)

`node ./node_modules/parcel-bundler/src/cli.js build *.html
`

results in an error

```
node_modules/v8-compile-cache/v8-compile-cache.js:100:41: Cannot statically evaluate fs argument
   98 |   _load() {
   99 |     try {
> 100 |       this._storedBlob = fs.readFileSync(this._blobFilename);
      |                                         ^
  101 |       this._storedMap = JSON.parse(fs.readFileSync(this._mapFilename));
  102 |     } catch (e) {
  103 |       this._storedBlob = Buffer.alloc(0);

```

Please clarify what is the difference here?

**Comment by mischnic** [comment]
In this case `src="/5b5cc26e63a107f79379da8b728234a0.js"`, the long hashed is replaced at the end of the build by the actual bundle file path. This should never be written to disk.

> `node_modules/v8-compile-cache/v8-compile-cache.js:100:41: Cannot statically evaluate fs argument`

This is only a warning, however, I guess you didn't intend to bundle this.

----

I couldn't reproduce this issue with:
```
- src
   |- js
      |- application.js
   |- index.html
```
and
```js
const bundler = new Bundler('./src/*.html');
bundler.bundle();
```

**Comment by geoynomous** [comment]
> In this case `src="/5b5cc26e63a107f79379da8b728234a0.js"`, the long hashed is replaced at the end of the build by the actual bundle file path. This should never be written to disk.

Can you point out where the filenames are generated. Then I can search myself and give more information. In particular where it could creata such a "wrong" name.
