### ISSUE TITLE
How to configure node-sass in parcel 2.0?

### ISSUE THREAD

**Issue by IdeaHunter** [parcel-bundler/parcel#3745]
When i try to build my project it tells me
> `node-sass` is unsupported in Parcel 2, it will use Dart Sass a.k.a. `sass`

From documentation:

> You can also use node-sass module for SCSS compilation.

I dont want dart-sass because one of my dependencies breaking when i try to build it with dart-sass.
How can i disable it and use node-sass instead?

**Comment by DeMoorJasper** [comment]
I thought we still supported it but apparently we dropped support for it.

`node-sass` never really worked very well with Parcel (as we do a lot of parallel transforms) therefore we deprecated it in Parcel 1. Sometimes the proces just froze for no reason, had something to do with `node-sass` internals. We could probably figure it out and contribute a fix to node-sass, but the performance difference didn't seem valuable enough to debug the issue in detail.

**Comment by IdeaHunter** [comment]
Ok, thanks!
Can you please update documentation to make people that are new to parcel dont get confused what it can do because they can have some dependencies that need to be compiled with node-sass

**Comment by DeMoorJasper** [comment]
@IdeaHunter sure but the documentation site is currently for Parcel 1, we still have to write a new one for Parcel 2...

**Comment by IdeaHunter** [comment]
my point that it would be good idea to point to future compatibility issues with breaking changes on current documentation. Also new documentation doesnt mentioned dart-sass or node-sass at all.

**Comment by IdeaHunter** [comment]
Closing an issue and hoping you would add some changes to docs 😄
Thanks for a help!

**Comment by esr360** [comment]
If you want people to adopt Parcel you should make it compatible with node-sass.

**Comment by IdeaHunter** [comment]
@esr360 but this is price for zero configuration, you cant avoid that. node-sass is not like complete unsupported, you supposedly(?) still can write a plugin for it and replace default handling, but OOTB its not supported

**Comment by DeMoorJasper** [comment]
@esr360 what @IdeaHunter said is correct you can compile sass with whatever you want. We just don't support it out of the box because `node-sass` crashes when running multiple compiles in parallel what. Which happens a lot with Parcel and we prefer to deliver a stable default config.

**Comment by esr360** [comment]
@DeMoorJasper really all I'm trying to do is configure whatever Sass compiler I use so I can use a custom importer and I've been searching far and wide to no avail - I had assumed this was only possible with Node-Sass hence my outcry. I've tried using a `.sassrc` (which is supposedly how parcel configures sass) also to no avail :(
