### ISSUE TITLE
try-catch block disappeared after compiled

### ISSUE THREAD

**Issue by SaekiRaku** [parcel-bundler/parcel#3748]
# 🐛 bug report

index.js :

```
try {
    window;
} catch(err) {
    console.log(err);
}
```

These code working fine with `parcel index.js` in development mode, but when using `parcel build index.js`, the whole try-catch block got removed in `dist/index.js`.If change `window` to `window.document`, everything is working fine.

BTW, I'm trying to use the same code file no matter if the browser supports` WebWorker`. By using `try-catch` to `window` object, I'm able to know when should use `self.postMessage` to return the result in the `WebWorker` way or use `return` in the normal `module` way. For example:

```
// index.js
if (window.WebWorker) {
    var worker = new Worker("./worker.js");
    worker.addEventListener("message", (evt) => { console.log(evt.data) });
    worker.postMessage( ... );
} else {
    import("./worker.js").then((chunk) => {
        var duang = chunk.default
        var result = duang({data: ... });
        console.log(result);
    });
}
```

```
// worker.js
function duang(evt) {
    try {
        // This block got removed after compiled.
        window
    } catch (e) {
        self.postMessage( ... );
        self.close();
    }
    return ...;
}

try {
    // This block got removed after compiled.
    window
} catch (e) {
    self.addEventListener("message", duang)
}

export default duang;
```

## 🎛 Configuration (.babelrc, package.json, cli command)

`parcel index.js` and `parcel build index.js`

## 🤔 Expected Behavior

Do not remove `try-catch` block

## 😯 Current Behavior

`try-catch` block got removed after compiled in output files, if `try` block only contain a `window` object. No error output.

## 💁 Possible Solution

...

## 🔦 Context

...

## 💻 Code Sample

...

## 🌍 Your Environment

```
parcel --version
> 1.12.4
```

**Comment by mischnic** [comment]
That try-catch is removed by terser (you can verify that yourself here: https://try.terser.org/ - paste into the bottom left field).

You should open a bug with terser.

**Comment by SaekiRaku** [comment]
Thanks, I'll do that.
