### ISSUE TITLE
Source maps not working?

### ISSUE THREAD

**Issue by MarkLyck** [parcel-bundler/parcel#3750]
# 🐛 bug report

I'm trying to move my application from next.js & webpack over to using parcel.

Everything seems to be working except there's 1 random new error that wasn't happening on next.js but is happening with the parcel & it's breaking my application.

```
uncaught at  at  
 at  
TypeError: (0 , n.default) is not a function
    at http://localhost:3000/src.3248ba16.js:1280:1722
    at http://localhost:3000/src.3248ba16.js:1280:1415
    at Object.next (http://localhost:3000/src.3248ba16.js:1280:1520)
    at K (http://localhost:3000/src.3248ba16.js:1218:4337)
    at E (http://localhost:3000/src.3248ba16.js:1218:4062)
    at F (http://localhost:3000/src.3248ba16.js:1218:7973)
    at P (http://localhost:3000/src.3248ba16.js:1218:6802)
    at http://localhost:3000/src.3248ba16.js:1218:8536
    at Array.forEach (<anonymous>)
    at W (http://localhost:3000/src.3248ba16.js:1218:8509)
```

The actual error totally makes sense. It seems like switching to Parcel has somehow screwed up an import 🤔?

But ALL the stack traces are minified code with no source maps... Making this extremely difficult to debug.

## 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc
```js
{
    "presets": ["@babel/preset-env", "@babel/preset-react"],
    "plugins": [
        ["@babel/plugin-proposal-class-properties", { "loose": true }],
        "styled-components",
        [
            "module-resolver",
            {
                "root": ["."],
                "alias": {
                    "common": "./src/common",
                    "components": "./src/components",
                    "pages": "./pages",
                    "static": "./static",
                    "theme": "./src/theme",
                    "redash": "./redash"
                }
            }
        ]
    ]
}
```

Parcel command I'm running:
```
export NODE_OPTIONS=--max-old-space-size=8192; parcel ./src/index.html --port 3000
```

## 🤔 Expected Behavior

Should generate all source maps in development mode, and show a useful stacktrace.

## 😯 Current Behavior

No source maps are available

## 💁 Possible Solution

No clue.

## 🌍 Your Environment

"parcel-bundler": "^1.12.4"

**Comment by mischnic** [comment]
is there a comment like `//# sourceMappingURL` in the last line of the generated bundle?

**Comment by MarkLyck** [comment]
yes `//# sourceMappingURL=/src.3248ba16.js.map`

**Comment by mischnic** [comment]
Is that application open source by any chance?

**Comment by MarkLyck** [comment]
I'm afraid not, I work as a contractor and I can't share the full source code.

**Comment by mischnic** [comment]
Reasons I can think of at the moment: the bundle is served at a different public url path, so that the sourcemap doesn't exist on the path in that comment (this doesn't seem to be the case here); the sourcemap is invalid (don't know why this would happen, but the browsers don't show a message in this case).
If you look in the sources tab in devtools, do you see the folder hierarchy of your sources (I think the names are italic in Chrome)?

**Comment by mischnic** [comment]
I'm closing this because I don't know how we could help you here.

**Comment by philtune** [comment]
Hi, I'm having the same issue. There is no setting to tell the compiled JS files where to look for the source map. `/js/scripts.min.js` just has `//# sourceMappingURL=/scripts.min.js.map`, but it needs to be `/js/scripts.min.js.map` or else needs to just be relative (no leading slash, which makes the most sense) `//# sourceMappingURL=scripts.min.js.map`

**Comment by 55Cancri** [comment]
Any update on this?

**Comment by peterlacko** [comment]
> 
> 
> Hi, I'm having the same issue. There is no setting to tell the compiled JS files where to look for the source map. `/js/scripts.min.js` just has `//# sourceMappingURL=/scripts.min.js.map`, but it needs to be `/js/scripts.min.js.map` or else needs to just be relative (no leading slash, which makes the most sense) `//# sourceMappingURL=scripts.min.js.map`

Hi @philtune , I solved this issue by setting public url for my build, as @mischnic mentioned above

**Comment by ryasmi** [comment]
Here's a repro for you @mischnic https://github.com/ryansmith94/full-app-code-coverage-demo/pull/2

**Comment by jessabyrne** [comment]
@peterlacko Can you show an example usage of setting the public url for your build?

**Comment by bcokert** [comment]
@jessabyrne https://parceljs.org/cli.html#set-the-public-url-to-serve-on
eg:
`parcel build ./web/assets/js/main.js --out-dir ./build/assets --public-url /assets`

Assuming you host your assets on eg `yoursite:port/assets/main.js`

Not sure if updating the docs [here](https://parceljs.org/cli.html#set-the-public-url-to-serve-on) is the right place to add some clarification.

**Comment by hinst** [comment]
I am still getting this problem: the source map is not working. 
Compile Node.js project into a single file. 
Two files will be generated: main.js and main.js.map
`import 'source-map-support/register'`
Outcome: there will be no mapping in stack traces

Meanwhile, with TypeScript `tsc` compiler it works fine
