### ISSUE TITLE
glslify seems not working?

### ISSUE THREAD

**Issue by shengsword** [parcel-bundler/parcel#3754]
# ❔ Question

I tried to import some glsl code inline in my index.js, but It seems compiled with errors.
```
const glslify = require('glslify')
const vert = glslify(`
#pragma glslify: snoise3 = require(glsl-noise/simplex/3d) 
attribute vec3 position; 
void main() {
  gl_FragColor = vec4(snoise3(position), 1.0);
}`)
console.log(vert)
```

## 🔦 Context

 Uncaught TypeError: fs.existsSync is not a function
    at fsExistsSync (acorn.es.js:2955)
    at iteratorSync (acorn.es.js:3210)
    at module.exports.sync (acorn.es.js:3501)
    at Depper.getTransformsForFile (acorn.es.js:5312)
    at Depper.add (acorn.es.js:5312)
    at Depper.inline (acorn.es.js:5312)
    at Object.compile (acorn.es.js:5312)
    at module.exports (acorn.es.js:5312)
    at Object.parcelRequire.index.js.glslify (acorn.es.js:5312)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.4
| Node             | 10.16.3
| npm/Yarn         | 6.9.0
| Operating System | win10

**Comment by mischnic** [comment]
Parcel has native support for glsl assets:

a file `vert.glsl`:
```glsl
#pragma glslify: snoise3 = require(glsl-noise/simplex/3d) 
attribute vec3 position; 
void main() {
  gl_FragColor = vec4(snoise3(position), 1.0);
}
```
`index.js`:
```js
import vert from "./vert.glsl";
console.log(vert)
```

**Comment by illus0r** [comment]
Hi @mischnic! When in glsl I do

```#pragma glslify: snoise3 = require(glsl-noise/simplex/3d)```

in the terminal I get

```
🚨 Build failed.
@parcel/core: Failed to resolve 'glsl-noise/simplex/3d' from './vert.glsl'
```

Is there a way to fix it?

Here is a project that fails to build https://github.com/illus0r/parcel-glslify-test

**Comment by mischnic** [comment]
Does installing the `glsl-noise` npm package fix it?

**Comment by illus0r** [comment]
Thank you, @mischnic! Works perfectly! I don't know why I thought parcel will install it for me. I may be got used to its awesomeness 😄
