### ISSUE TITLE
Can't read function inside html native attribute, onclick, onsubmit

### ISSUE THREAD

**Issue by mandaputtra** [parcel-bundler/parcel#3755]
# 🐛 bug report

Parcel seems can't read HTML  native attributes `onclick`, `onsubmit`,  its trigger on click and on submit but the function on it was undefined. Notes that your script must be on `<head>` tag, not on body.

## 🎛 Configuration (.babelrc, package.json, cli command)

My `package.json` script no further configuration
```js
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "parcel web/index.html",
    "start": "serve web"
  },
```

## 🤔 Expected Behavior

Function that placed on `onclick` and `onsubmit` shoud can be read

## 😯 Current Behavior

Function that placed on `onclick` or `onsubmit` cannot be read. 

```html
<button onclick="declaredFunction()">click me undefined function happen</button>
```

## 💁 Possible Solution

I'm not sure why

## 🔦 Context
I don't want to use `document.getEmelentId('mybutton').addEventListener('click')` every time, If this was resolved it can save a lot of time.

## 💻 Code Sample

```bash
# step to reproduce
$ git clone https://github.com/OpenVidu/openvidu-tutorials.git
$ cd openvidu-tutorials/openvidu-insecure-js
$ parcel web/index.html
# click join and you will see `joinSession()` is undefined.
# or just create another function, and place it on `onsubmit` or `onclick`
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4 |
| Node             | 12.13.0 |
| npm/Yarn         | 6.12.0 |
| Operating System | Windows 10 |

**Comment by mischnic** [comment]
If you declare a function in a JS script, Parcel assumes that these should not become global variables. You need to do this:

```js
window.declaredFunction = function(){
  // ...
};
```
