### ISSUE TITLE
CSS import issue when publishing to npm

### ISSUE THREAD

**Issue by L-Blondy** [parcel-bundler/parcel#3758]
# ❔ Question

Do I make a mistake or is this a real Parcel issue ?

## 🔦 Context

I'm trying to create a npm package that provides different interactive common icons.
I've got a simple JS file that imports a css file 
>import "./styles.css";

So if i import my JS file I've got both JS and CSS imported

However if I publish the package to the NPM (package name ="lb-icons") the css does not get imported automatically, I have to import it manually on the project;

### Actual usage in another project (not desired):
>import "lb-icons";
>import "lb-icons/dist/index.css";
### Desired usage in another project:
>import "lb-icons";

## 💻 Code Sample

package.json : 
```
{
	"name": "lb-icons",
	"version": "1.0.19",
	"description": "Interactive icons",
	"main": "dist/index.js",
	"scripts": {
		"start": "parcel src/index.js",
		"build": "parcel build src/index.js",
		"go": "npm run build && npm publish",
		"test": "echo \"Error: no test specified\" && exit 1"
	},
	"keywords": [],
	"author": "Laurent Blondy",
	"license": "ISC",
	"devDependencies": {
		"parcel-bundler": "^1.12.4",
		"@babel/cli": "^7.7.0",
		"@babel/core": "^7.7.2",
		"@babel/preset-env": "^7.7.1",
		"cssnano": "^4.1.10"
	},
	"files": [
		"dist/*"
	]
}
```

index.js
```
import "./styles.css";
...
some code here
```

folder structure : 

dist
|_index.css
|_index.css.map
|_index.js
|_index.js.map
node_modules
src
|_index.js
|_styles.css

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 10.16.3
| npm/Yarn         | 6.9.0
| Operating System | Windows 10

Gihub repo : https://github.com/L-Blondy/lb-icons.git

**Comment by mischnic** [comment]
Can you give an example where you try to import it?
This works for me:
```html
<script type="text/javascript" src="./index.js"></script>
<div class="burger-burger" thickness="4px" duration="300ms" rounded>
```
```js
import "lb-icons";
```

**Comment by L-Blondy** [comment]
Hi mischnic, thanks for your answer.

Right now my package works because I'm using what i consider being a workaround. I'm building the package with the following script: 
```
 "build": "npx babel src/index.js --out-file dist/bundle.js && uglifyjs dist/bundle.js --output dist/bundle.js && parcel build src/styles.css",
```
babel on the JS file and parcel JUST on the CSS file

I expected Parcel to support the following, using parcel directly on the entrypoint:
```
"build": "parcel build src/index.js",
```
By doing so the JS and CSS files get indeed created, however when trying to use the package ( ` import "lb-icons"; ` ) the CSS bundled file is not imported at all.

My question was is this normal because not meant to be supported by Parcel ?
Or am I doing something wrong ?

**Comment by mischnic** [comment]
Having an HTML file as your entrypoint works, but with a js file it doesn't. 
Not sure if this is "meant to be supported".
