### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by ershumi** [parcel-bundler/parcel#3759]
My parcel config is 
scripts:{
dev: export NODE_ENV=local-dev && parcel watch ui/app.html --public-url /assets/via -d static & nodemon
}
When I run **yarn dev** my application builds perfectly fine but when make any changes in code(even adding a space), my browser page reloads and throws an error **Uncaught SyntaxError: Unexpected end of input**

NOTE: This is working fine which I am using parcel-bundler version 0.11.0 but after switching to version 0.12.0 and above throwing me an error.

**Comment by DeMoorJasper** [comment]
Could you provide any additional information beyond this?

From this I could just extract it's giving a 404 which is just the root html page in parcel for SPA to work...

Also I assume it's version 1.12 and not 0.12?

**Comment by mischnic** [comment]
> my browser page reloads

I suspect the browser reloads before the complete JS bundle was written to disk, therefore the browser receives invalid JS.

Related: https://github.com/parcel-bundler/parcel/issues/3299, https://github.com/parcel-bundler/parcel/issues/2894

**Comment by DeMoorJasper** [comment]
If this is a duplicate we should probably close this

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
