### ISSUE TITLE
Add an error location when dependent files are not found, or external modules are not allowed

### ISSUE THREAD

**Issue by mhintz** [parcel-bundler/parcel#3761]
# 🙋 feature request
When an error is thrown during compilation, currently you just get an error message and a stack trace from inside parcel. Ideally there would also be some information about the location in the source where the error was generated.

## 🤔 Expected Behavior
For example, when including an external module when that isn't allowed, or when a needed dependency is missing, it would be good to have an indication of which line in the source generated this problem.

## 😯 Current Behavior
Currently the output is just something like:
```
External modules are not supported when building for browser
... long stack trace from parcel ...
```

**Comment by DeMoorJasper** [comment]
Should be fairly straightforward with the new diagnostics in parcel 2

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mischnic** [comment]
This particular error will become more useful/rich after https://github.com/parcel-bundler/parcel/pull/3695 is merged, because currently the component that combines all the sources has no idea where the code came from (they are reparsed from a string internally).

**Comment by devongovett** [comment]
This error is likely because you have inadvertently put Parcel into library mode with a `main` or `module` field in your package.json. This will cause Parcel to exclude node_modules by default, which would trigger this error at packaging time.

We can definitely make this error message a lot better though.

**Comment by mischnic** [comment]
`require.resolve("./something.js")` results in:
`🚨 @parcel/packager-js: Got unexpected undefined`
