### ISSUE TITLE
Using plugins for optimising Rust WASM outputs

### ISSUE THREAD

**Issue by ChetanBhasin** [parcel-bundler/parcel#3764]
# ❔ Question

Hi! Is there a way to call external binaries or plugins on the build outputs for things such as optimisations.

## 🔦 Context

The generated WASM binaries from Rust are often large and can be optimised.

I was hoping to call something like [wasm-snip](https://github.com/rustwasm/wasm-snip) to optimise the build WASM outputs.

I took a quick look around to see if this can be done with Cargo configuration so Parcel doesn't need to be configured, but couldn't come up with a useful solution.

## 💻 Code Sample

I used [this example](https://github.com/parcel-bundler/examples/tree/master/rust-cargo) code.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 10.13.0
| npm/Yarn         | NPM 6.13.0
| Operating System | Mac OS Catalina

**Comment by mischnic** [comment]
This isn't currently possible within Parcel itself, you could run it afterwards.
I'll post this on https://github.com/parcel-bundler/parcel/issues/3365 so we can consider it when Rust support will be added to Parcel 2.
