### ISSUE TITLE
[V2] Static Rendering & Static Site Generator

### ISSUE THREAD

**Issue by brillout** [parcel-bundler/parcel#3765]
In the context of an SSR tool I'm writing ([github.com/brillout/parcel-ssr](https://github.com/brillout/parcel-ssr)), I'm interested in static rendering.

I'm not sure how I can generate HTML files with the current v2 plugin architecture.

I have two options:
1. A plugin writes the HTML files to disk &mdash; Parcel is not aware of these HTML files.
2. A plugin adds HTML assets to Parcel's Asset Graph &mdash; it is Parcel that writes the HTML files to disk.

A Parcel plugin shouldn't have any side effect which makes 1. not an option.

I can't find an appropriate plugin to add HTML assets to the Asset Graph.

The HTML assets are generated by using a function `staticRender` that is written by the user:

~~~js
// render/staticRender.js

const render = require('@parcel-ssr/render');

module.exports = staticRender;

async function staticRender() {
  [
    {slug: 'intro', title: 'Introducing @parcel-ssr',
     markdown: '`parcel-ssr` is a tiny yet powerful tool...'},
    {slug: 'why-parcel', title: 'Why SSR with Parcel',
     markdown: "Parcel's zero-config philosophy..."},
  ].forEach(({slug, title, markdown}) => {
    const props = {title, markdown};
    // We render each blog post to an HTML file `blog/${slug}.html`.
    // The blog post is then available at `https://example.org/blog/${slug}`.
    pages['/blog/'+slug] = render('BlogPost', {props});
  });

  // Generate `index.html` and `about.html`
  pages['/'] = render('Landing', {doNoHydrate: true});
  pages['/about'] = render('About', {doNoHydrate: true});

  return pages;
}
~~~

More is explained at [github.com/brillout/parcel-ssr](https://github.com/brillout/parcel-ssr).

How can I generated HTML files using a Parcel plugin?

Is a reporter plugin also not allowed to have any side effect? Otherwise I could simply use a reporter to write the HTML files to disk.

**Comment by DeMoorJasper** [comment]
reporters will always run as they have no cache so you could use that although it's probably not a good idea if you want caching.

A transformer could just return html, than it would also run through html optimizers and such which probably would save you some work...

**Comment by brillout** [comment]
> reporters will always run as they have no cache so you could use that 

Ok neat.

> A transformer could just return html, than it would also run through html optimizers and such which probably would save you some work...

That's wonderful, I'll have a look at how I can use a Transformer to add HTML assets to the graph.

**Comment by brillout** [comment]
The HTML entry points must come from somewhere &mdash; either from within a Parcel Plugin, e.g. a transformer, or from the user's `package.json`.

I'm looking at how Transformer works and it seems that a transformer is, essentially, taking one `Asset` as input and outputs one or several `Asset`. That means that I cannot use a Transformer to add HTML entry points to the asset graph. Is that correct?

If this is correct, then this means that it is the user that has to define the HTML entry points. For example:
~~~json5
// pages/package.json
{
  "source": [
    {entry: "**/*.page.js", outDir: "dist/"},
    {entry: "**/*.html", outDir: "dist/"}
  ]
}
~~~
The user could then have:
~~~
pages/package.json
pages/index.html
pages/landing/Landing.page.js
pages/landing/index.css
pages/about/About.page.js
pages/about/index.html
pages/about/index.css
pages/contact/Contact.page.js
~~~

Were both `Landing.page.js` and `Contact.page.js` are rendered into `pages/index.html`. In other words my Transformer transforms `pages/index.html` into new HTML assets `dist/index.html` and `dist/contact.html`. `About.page.js` is rendered into `pages/about.html`.

It seems that there is no intention (yet?) to support something like the `package.json#source` array above but I created a ticket for it: https://github.com/parcel-bundler/parcel/issues/3822.
