### ISSUE TITLE
WebSocket connection to 'ws://localhost:50619/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by mburakerman** [parcel-bundler/parcel#377]
When i open index.html after calling `parcel index.html` i get this error.
Also when i change html, page doesn't refresh.

How can i solve this?

**Comment by DeMoorJasper** [comment]
Could u fill in the bug report form u get when submitting an issue?
Also providing the full stack trace and ideally the project you used to test this would help a lot

**Comment by palash7563** [comment]
while running the parcel in localhost it is running fine but when i dockerize the project and i have only exposed the default port (1234) i see this error ..

**Comment by DeMoorJasper** [comment]
@palash7563 this is because the websocket port isn't opened on docker, you can simple specify a port using the `--hmr-port` flag and portforward that port through docker...

**Comment by palash7563** [comment]
Yeah it works thanks :-D

**Comment by moonlight16** [comment]
@DeMoorJasper @palashg7563 
Which port do you use when using --hmr-port trying to go through Docker?  

I'm trying to use -p 8080 and --hmr-port.  First I tried --hmr-port 8080.  Second, I tried some other random port.  When I tried 8080, it spit back a bunch of errors (I suppose there's a port conflict?).  When I tried some other random port (i.e. 8081), it still doesn't work when directing my browser to 8080.  I do get the initial hmtl rendered page.  But still not getting the refreshes.  And yes, I did expose both ports 8080 and 8081 in my Dockerfile.  Any help would be appreciated.

**Comment by moonlight16** [comment]
Sorry, my mistake.  I had exposed the port in my Dockerfile, but I'm using docker-compose.  And inside the yml file I also have ports being exposed.  I needed to only expose the ports in the docker-compose yml file.  And for the record, 8081 did work okay in my case.

**Comment by AustinMaddox** [comment]
Thanks! I now run parcel in a Docker container by putting this in my `.bash_profile` on Mac...

```bash
parcel() {
  if [ "$#" -ge 2 ]; then
    local port="${1}"
    local hmr_port=$((port + 1))
    shift 1
    docker run --rm --interactive --tty --name="parcel-container-$port" --env="PORT=$port" --env="PARCEL_WORKERS=1" --publish $port:$port --publish $hmr_port:$hmr_port --network="local-network" --volume "$PWD":/data --workdir /data --user $(id -u):$(id -g) node:10-alpine npx parcel --port $port --hmr-port $hmr_port "$@"
  else
    echo "Usage: parcel <port> <any other args>"
    echo "Example: parcel 8000 src/index.html"
  fi
}
```

**Comment by tno2007** [comment]
Use the **--hmr-port** flag

`parcel index.html --hmr-port 50619`

where 50619 is the numeric value of the port that is complaining about
