### ISSUE TITLE
Use preset-modules to transpile for both old and new browsers in parallel

### ISSUE THREAD

**Issue by Tom-Julux** [parcel-bundler/parcel#3771]
# 🙋 feature request

## 🤔 Expected Behavior

Javascript is transpiled to ES5 to run in old browsers and in additionally transpiled to run in browsers supporting `<script type="module">`. 

## 😯 Current Behavior

Javascript is transpiled to ES5 (or whatever the `.babelrc` file says) and loaded with a script tag. The transpiled code is used with all browsers.

## 💁 Possible Solution

Use the [@babel/preset-modeles](https://github.com/babel/preset-modules) package.

## 🔦 Context

~Someone~ @devongovett [mentioned under the release tweet](https://twitter.com/devongovett/status/1194363565727080448?s=20) of `@babel/preset-modules` that parcel could greatly benefit from this package as is allows to send less code to modern browsers, but trivially keeps the compatibility with old browsers. This dual nature makes it a perfect match for zero config bundling.

**Comment by devongovett** [comment]
In v2 this is done https://parceljs.org/features/production/#differential-bundling
