### ISSUE TITLE
Error when calling instanceof on the instance of the class extending the Error class

### ISSUE THREAD

**Issue by lukejagodzinski** [parcel-bundler/parcel#3775]
```
Parcel Version: 1.12.4
```

**Code sample**

```ts
class CustomError extends Error {
  name = "CustomError";
}

try {
  const error = new CustomError("Error happened");
  console.log("TRY: error", error.constructor.name, JSON.stringify(error));
  console.log("TRY: instanceof CustomError", error instanceof CustomError);
  console.log("TRY: instanceof Error", error instanceof Error);
  throw error;
} catch (error) {
  console.log("CATCH: error", error.constructor.name, JSON.stringify(error));
  console.log("CATCH: instanceof CustomError", error instanceof CustomError);
  console.log("CATCH: instanceof Error", error instanceof Error);
}
```

**Respositories**

- [Parcel] https://codesandbox.io/s/errorparcel-y33n8
- [Webpack] https://codesandbox.io/s/errorwebpack-xucu4

**Output**

```
TRY: error Error {"name":"CustomError"} 
TRY: instanceof CustomError  false
TRY: instanceof Error  true
CATCH: error Error {"name":"CustomError"} 
CATCH: instanceof CustomError  false
CATCH: instanceof Error  true
```

**Expected output**

```
TRY: error CustomError {"name":"CustomError"} 
TRY: instanceof CustomError  true
TRY: instanceof Error  true
CATCH: error CustomError {"name":"CustomError"} 
CATCH: instanceof CustomError  true
CATCH: instanceof Error  true
```

**Description**

I've switched my project from using Webpack to Parcel and suddenly some of the code stopped working. Parcel has problem with properly detecting class of an instance of the object that is extending built in class, like for example the `Error` class. It works correctly with custom classes but fails with built in ones. This bug is not present in Webpack. After comparing transpiled code I can see that Webpack is using `@babel/runtime/helpers/possibleConstructorReturn` helper function to initialize instance of the extended class. Is it something that can be easily fixed?

It also doesn't work when I provide custom Babel config with the `typescript` transformer.

EDIT:

I've just found this issue: https://github.com/parcel-bundler/parcel/issues/2023

Which looks like it would fix my problem. But I see that it's only fixed in Parcel 2. Are you planning to fix that in Parcel 1? Or is there an easy hack to allow that?

Also a solution using the `parcel-plugin-babel-typescript` plugin doesn't work

**Comment by mischnic** [comment]
I think you really want to use a newer `browserslist` so that classes aren't transpiled? Otherwise, making the class transform run in loose mode could work as well.
e.g. in your package.json
```json
{
  "browserslist": ["Chrome 70"]
}
```

**Comment by lukejagodzinski** [comment]
I can't just use that as we also support IE11 that doesn't come with classes support

**Comment by mischnic** [comment]
Please try setting the target in your tsconfig to esnext to let Parcel handle the transpiling:
[try it out here](https://parcel-repl.now.sh/#JTdCJTIyY3VycmVudFByZXNldCUyMiUzQSUyMkphdmFzY3JpcHQlMjIlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIybWluaWZ5JTIyJTNBdHJ1ZSUyQyUyMnNjb3BlSG9pc3QlMjIlM0F0cnVlJTJDJTIyc291cmNlTWFwcyUyMiUzQWZhbHNlJTJDJTIyY29udGVudEhhc2glMjIlM0F0cnVlJTJDJTIyYnJvd3NlcnNsaXN0JTIyJTNBJTIyJTIyJTJDJTIycHVibGljVXJsJTIyJTNBJTIyJTIyJTJDJTIydGFyZ2V0JTIyJTNBJTIyYnJvd3NlciUyMiUyQyUyMmdsb2JhbCUyMiUzQSUyMiUyMiU3RCUyQyUyMmFzc2V0cyUyMiUzQSU1QiU1QiUyMmluZGV4LnRzJTIyJTJDJTIyY2xhc3MlMjBDdXN0b21FcnJvciUyMGV4dGVuZHMlMjBFcnJvciUyMCU3QiU1Q24lMjAlMjBuYW1lJTIwJTNEJTIwJTVDJTIyQ3VzdG9tRXJyb3IlNUMlMjIlM0IlNUNuJTdEJTVDbiU1Q24lNUNuY29uc3QlMjBlcnJvciUyMCUzRCUyMG5ldyUyMEN1c3RvbUVycm9yKCU1QyUyMkVycm9yJTIwaGFwcGVuZWQlNUMlMjIpJTNCJTVDbmNvbnNvbGUubG9nKCU1QyUyMlRSWSUzQSUyMGVycm9yJTVDJTIyJTJDJTIwZXJyb3IuY29uc3RydWN0b3IubmFtZSUyQyUyMEpTT04uc3RyaW5naWZ5KGVycm9yKSklM0IlNUNuY29uc29sZS5sb2coJTVDJTIyVFJZJTNBJTIwaW5zdGFuY2VvZiUyMEN1c3RvbUVycm9yJTVDJTIyJTJDJTIwZXJyb3IlMjBpbnN0YW5jZW9mJTIwQ3VzdG9tRXJyb3IpJTNCJTVDbmNvbnNvbGUubG9nKCU1QyUyMlRSWSUzQSUyMGluc3RhbmNlb2YlMjBFcnJvciU1QyUyMiUyQyUyMGVycm9yJTIwaW5zdGFuY2VvZiUyMEVycm9yKSUzQiUyMiUyQzElNUQlMkMlNUIlMjJ0c2NvbmZpZy5qc29uJTIyJTJDJTIyJTdCJTVDbiU1Q3QlNUMlMjJjb21waWxlck9wdGlvbnMlNUMlMjIlM0ElMjAlN0IlNUNuJTVDdCU1Q3QlNUMlMjJ0YXJnZXQlNUMlMjIlM0ElMjAlNUMlMjJlc25leHQlNUMlMjIlNUNuJTIwJTIwJTdEJTVDbiU3RCUyMiU1RCU1RCU3RA==)

**Comment by lukejagodzinski** [comment]
@mischnic I thought that I understand the `target` property. In theory it should compile to version that is using the `class` keyword but apparently Parcel is still doing extra work after `tsc` and transpiles all the missing features (using Babel?) to satisfy `browserslist`. Am I right?

But yes, it works, even in IE11. Thank you! I guess it should be described more how Parcel works under the hood or maybe it's described somewhere in the docs but I've just missed it?

**Comment by mischnic** [comment]
> I thought that I understand the target property in TS config. tcs compiles to version that is using the class keyword but apparently Parcel is still doing extra work after tsc and transpiles all the missing features (using Babel?) to satisfy browserslist. Is it correct?

Yes. I guess the pipelining aspect could be documented better.
The root issue here is that typescript's approach to transpiling classes doesn't really work with builtins.
I'll make sure this is done automatically in Parcel 2.

**Comment by lukejagodzinski** [comment]
@mischnic Thanks!
