### ISSUE TITLE
Absolute paths do not work with default TS setup

### ISSUE THREAD

**Issue by andyjessop** [parcel-bundler/parcel#3777]
#3272 🐛 bug report

Following the default instructions to get started with TypeScript generates an error for module resolution when using absolute paths.

I've created a minimal repo [here](https://github.com/andyjessop/parcel-ts), that demonstrates the issue.

A nested file was created, and imported from index:
```
import { someFunction } from '~/nested/some-function';
```
The `tsconfig` is the default taken from the parcel docs:
```
{
  "compilerOptions": {
    "baseUrl": "./src",
    "paths": {
      "~*": ["./*"]
    },
  },
  "include": ["src/**/*"]
}
```

## 🎛 Configuration (.babelrc, package.json, cli command)
There is no added configuration.

## 🤔 Expected Behavior
Absolute paths should work by default with TypeScript.

## 😯 Current Behavior
The full error is:
```
$ npm start

> parcel-ts@1.0.0 start /Users/andy/dev/parcel-ts
> parcel index.html

Server running at http://localhost:1234
🚨  /Users/andy/dev/parcel-ts/src/index.ts:3:30: Cannot resolve dependency '~/nested/some-function' at '/Users/andy/dev/parcel-ts/src/~/nested/some-function'
    at Resolver.resolve (/Users/andy/dev/parcel-ts/node_modules/parcel-bundler/src/Resolver.js:71:17)
    at <anonymous>
```

## 🔦 Context
Example repo:
https://github.com/andyjessop/parcel-ts
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.12.4
| Node             | 8.6.0
| npm/Yarn         | 5.6.0
| Operating System | macOS Mojave

**Comment by mischnic** [comment]
Please follow https://github.com/parcel-bundler/parcel/issues/1378 regarding paths support.
