### ISSUE TITLE
2 parallel parceljs running with different ENV

### ISSUE THREAD

**Issue by zedissime** [parcel-bundler/parcel#3782]
Hello,

I recently moved from webpacker to parceljs ( 🎉).
With webpacker I used to start 2 server for my app, with 2 different NODE_ENV, one in development, the other in test env. 
With parceljs I can boot the 2 instances, but the second one "override" the first one. I firstly thought it was the cache folder but even if the second instance have another cache folder specified it's not working.
Am I doing something wrong ?

**Comment by DeMoorJasper** [comment]
Could you share how you're running parcel? Are you using the API or cli, what are the commands/code?

**Comment by zedissime** [comment]
Yeah sure, here are my scripts which I start with `yarn`
```
"dev": "NODE_ENV=development parcel serve public/index.html --port 3000",
"cypress-dev": "NODE_ENV=cypress parcel public/index.html --port 5000 --cache-dir .cache-cypress",
```
and with this
`which parcel > /usr/local/bin/parcel`.

Thank you for your fast answer 👍
