### ISSUE TITLE
Is a multi sources, multi entries setup possible? (mono repostory)

### ISSUE THREAD

**Issue by youknowriad** [parcel-bundler/parcel#3790]
I've been trying to use Parcel 2 in the context of the [Gutenberg](https://github.com/WordPress/gutenberg) repository (WordPress's new Block Editor). Our repository is basically a regular mono-repository with multiple packages (packages folder). 

The specificity maybe is that each package can have both a JavaScript entry and one or several SCSS entries. The JavaScript  entry can have multiple targets (CommonJS and ESM) while the style entry can have just one target (regular CSS)

My starting point was this PR introducing mono-repository support https://github.com/parcel-bundler/parcel/pull/3583 

I tried diving into the docs, I found that it may be possible to define `source` as an array in the `package.json` of each package but I haven't managed to make it work properly (empty output when I try to build) and I've not been able to figure out a way to define my targets properly (the CSS ones).  So I was wondering if a setup like this is even possible?

Thank you

**Comment by devongovett** [comment]
One way that many people do it is to import the CSS into their JavaScript.

```js
import ‘./styles.scss’
```

When parcel is building a library, it will leave this import in the code but pointing to the compiled CSS instead so that when you later import it into your app it gets added automatically.

**Comment by youknowriad** [comment]
This works for a single stylesheet right? 

In some of our packages, we need to build three different stylesheets that can be loaded in multiple contexts (WordPress is complex :P). Any workaround to achieve this?

**Comment by devongovett** [comment]
You can import multiple stylesheets the same way

**Comment by youknowriad** [comment]
Oh sorry, I was not very clear. 

If I understand properly, importing multiple stylesheets will still result in a single style bundle containing the three stylesheets. Is it possible to have one stylesheet created per SASS "source"?

**Comment by devongovett** [comment]
Oh so you don’t want to bundle them?

I don’t think we have array support in the `source` field yet, but sounds like that’s what you really want. Shouldn’t be too hard.

If you wanna dive in and try it, `EntryResolver` is the place to look.

**Comment by youknowriad** [comment]
> Oh so you don’t want to bundle them?

yes, exacly. I haven't dived into Parcel code yet but I'll at least give it a try. Thanks

**Comment by youknowriad** [comment]
I've tried pocking about this, the change in `EntryResolver`  is "easy" enough  but it's not the only change required as it leads to duplication in bundle names and potentially unnecessary targets.

How do you think this should work (the mapping entry => destination). So right now my  package.json is something like:

```
  "main": "build/index.js",
  "module": "build/index.module.js",
  "source": [ "src/index.js", "src/index.css", "src/theme.css" ],
```

## What bundles do  you think, this should produce?

### Solution 1

**src/index.js** => produces **build.index.js**  and **build/index.module.js**

while the remaining sources  could just land in the "default" target

**src/index.css** => produces **dist/index.css**
**src/theme.css** => produces **dist/theme.css**

### Solution 2

After digging a little bit in the parcel code,  I think the expectations at the moment is that if you have a package.json as an entry point, all the entries there (sources) follow the targets defined in the file `main` and `module` which means. So we could have something like this

```
**src/index.js** => **build/index.js** and **build/index.module.js** 
**src/index.css** => **build/index.css** and **build/index.module.css**
**src/theme.css** => **build/theme.css** and**build/theme.module.css**
``` 

but say the package author used a different folder for the CJS and ESM builds like this

```
  "main": "build/index.js",
  "module": "build-module/index.js",
  "source": [ "src/index.js", "src/index.css", "src/theme.css" ],
```

In that case, to avoid duplication, the bundler could do this

```
**src/index.js** => **build/index.js** and **build-module/index.js** 
**src/index.css** => **build/index.css** and **build-module/index.css**
**src/theme.css** => **build/theme.css** and**build-module/theme.css**
``` 

--- 

So which solution do you think should be adopted?

 - if we go with solution1, it means multiple entries can have different targets (Probably some refactoring needed as I don't think this is possible right now in the code base?)
 - If we go with solution2, we may need more information to generate the bundle names properly because it's hard to "guess" the naming pattern to avoid duplication?
 - Maybe something else I didn't think about.

**Comment by devongovett** [comment]
What is the expected output location for those CSS files? How does a consumer of the package know where to find them? Is it just by convention (package/index.css) or would you expect a field in package.json pointing to them?

**Comment by youknowriad** [comment]
>  Is it just by convention (package/index.css) or would you expect a field in package.json pointing to them?

Right now it's just a convention, it's documented and people are expected to load them as needed in the browser (the exact location of the stylesheet is not very important). We know that's not a common pattern in packages in general though.

A field in package.json could be handy but I'm personally not aware of any precedent in other packages.

**Comment by youknowriad** [comment]
Trying to clarify why we do this: 

In the new editor, content is splitted into blocks. Everything can be a block (images, tables, paragraphs, slides...). A block (that can be shipped as a package) is composed of an "editor version" (component to edit the blokc), a "fontend version" (markup of the block) and potentially three stylesheets:

 - default stylesheet: loaded in both editor and frontend
 - editor stylesheet: only loaded in the frontend
 - optional theme stylesheet: opinionated stylesheet for a block. This can be loaded in an opt-in way by WordPress themes.

**Comment by bhallstein** [comment]
@youknowriad @devongovett Was there a resolution to this?

If I'm understanding this correctly, it seems parcel can't take 2 entry points and create, for each, a .js bundle and a .css bundle. This seems a bit odd when parcel has support for multiple targets as a first-class feature.

Apologies if I have misunderstood.

**Comment by mischnic** [comment]
This was implemented in the meantime: https://v2.parceljs.org/features/targets/#package.json%23targets.*.source
