### ISSUE TITLE
v2: Remove deasync

### ISSUE THREAD

**Issue by Skalman** [parcel-bundler/parcel#3799]
# 🙋 feature request

`deasync` is a native dependency, which can cause problems on many platforms. Remove it as a dependency.

## 🔦 Context

In https://github.com/parcel-bundler/parcel/issues/2214#issuecomment-433827381, @DeMoorJasper said that it definitely won't be part of Parcel 2.

I'll also quote @felixfbecker from [the same issue](https://github.com/parcel-bundler/parcel/issues/2214#issuecomment-445801939)

> This is really painful when building Docker images. If you depend on node:alpine, it does not have Python installed. You need to install Python only for this dependency of Parcel. Probably the whole rest of the compiler toolchain too.

**Comment by mischnic** [comment]
A recent discussion about this: https://github.com/parcel-bundler/parcel/pull/3788#pullrequestreview-317966170

> Can we just get rid of syncPromise in utils? (move it into @parcel/register)
Or do we still use it somewhere except in @parcel/register (maybe we can even figure out a way to get rid of syncPromise in parcel/register when we refactor it)?
> 
> Would be nice to not have people install the package anymore when using Parcel as we've had a bunch of issues in the past with the package not installing properly on certain machines.

<br>

> That would be great, but register is actually part of core and `@parcel/register` just calls the function:
> https://github.com/parcel-bundler/parcel/blob/e68e15e69cd4f66d135ab17e21ab4460297e2ae1/packages/core/register/src/register.js#L5
> https://github.com/parcel-bundler/parcel/blob/e68e15e69cd4f66d135ab17e21ab4460297e2ae1/packages/core/core/src/register.js#L11

So deasync should be moved from `@parcel/core` to `@parcel/register`.

**Comment by leecade** [comment]
I could not agree more. btw,  detect `inspector` and fallback is necessary.

https://github.com/parcel-bundler/parcel/blob/v2/packages/core/workers/src/Profiler.js#L2

In some production environments, built node with `--without-inspector`, because v8_inspector use `prime_rehash_policy` symbol that requires GLIBCXX_3.4.18 on some systems.

**Comment by DeMoorJasper** [comment]
@leecade could you open a seperate issue for that?

**Comment by Lx** [comment]
The `deasync` dependency can't be installed at all on my heavily-locked-down corporate computer.

However, for anyone else who desperately needs an interim workaround, some kind soul has released a version of Parcel without the `deasync` dependency:

https://www.npmjs.com/package/parcel-bundler-without-deasync

I don't know what version of Parcel it is (this package has a version number of `9.99.10`) but it works well enough for me.
