### ISSUE TITLE
'parcel' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by beekocha** [parcel-bundler/parcel#3806]
# 🐛 bug report

**Trying to install globally parcel-bundler** (npm install -g parcel-bundler)

## 😯 Current Behavior

I tried to install parcel-bundler (npm install -g parcel-bundler), but it always have an:

npm ERR! code E404
npm ERR! 404: Not found ws@5.1.1 (it always can't find any library or something else)
npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\username\AppData\Roaming\npm-cache\_logs\2019-11-18T18_29_26_513Z-debug.log

I tried to unistall it. I used npm cache clean and after that i try to install it again. But it doesn't help.
But after several attempts, it installed. But it doesn't work in terminal. And after rebooting, it still uninstalled :D WHY? 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | node v10.14.1
| npm/Yarn         | npm 6.4.1
| Operating System |  Windows 8

**Comment by DeMoorJasper** [comment]
This seems like an issue with your npm installation. 
Maybe you’re using an unreliable company proxy or just a bad npm version.
Seems unlikely to be related to parcel itself.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by egorguscha** [comment]
I can't install `parcel@next` or `parcel-bundler -D` by yarn event after updates

Sofware|Version
--|--
npm/yarn|1.19.1/6.10.3
OS|macOS Catalina
Node|12.10.0

**Comment by beekocha** [comment]
> This seems like an issue with your npm installation.
> Maybe you’re using an unreliable company proxy or just a bad npm version.
> Seems unlikely to be related to parcel itself.
> 
> Sent with [GitHawk](http://githawk.com)

Yeah, that's true. Thank you :)

**Comment by steveoo-tech** [comment]
I found one solution, this command worked for me: 

npm install parcel-bundler --save-dev

this worked for me, hopefully this helps!

**Comment by huubee** [comment]
Installing parcel-bundler globally did the trick for me:

npm install -g parcel-bundler --save-dev
