### ISSUE TITLE
🙋 Bundling react-native packages with react-native-web project

### ISSUE THREAD

**Issue by dalcib** [parcel-bundler/parcel#381]
`react-native-web` is a project that allows using react-native primitives and react-native libraries (not all) to build web applications.
The react-native libraries are built in ES6+JSX+Rest Objects+...
These packages, generally, are not compiled and don't have a `.babelrc` file.
I would like to now wich is the best approach to bundle a project using Parcel.
I tried the babel plugin `react-native-web/babel` that was supposed to solve this problem with webpack but it didn't work with Parcel..
Will it need a specific Parcel plugin for this?

**Comment by devongovett** [comment]
Can you provide some more details about what didn't work? Was there an error message or something that you hit when using that babel plugin?

**Comment by brandon93s** [comment]
Hello @dalcib,

Closing for the time being until additional details are provide. Feel free to re-open with additional information. Thanks!
