### ISSUE TITLE
V2: detect inspector and fallback is necessary

### ISSUE THREAD

**Issue by leecade** [parcel-bundler/parcel#3819]
# 🙋 feature request

https://github.com/parcel-bundler/parcel/blob/d24e09a9797af41a9d2c6c733b1c6cf6671d60c7/packages/core/workers/src/Profiler.js#L2

The inspector module not always available, it depends on build param `--without-inspector`

## 🤔 Expected Behavior

Compatible with `--without-inspector` mode.

## 😯 Current Behavior

Direct import

## 💁 Possible Solution

Not pretty sure how to implement a fallback

## 🔦 Context

In some production environments, built node with `--without-inspector`, because v8_inspector use `prime_rehash_policy` symbol that requires GLIBCXX_3.4.18 on some systems.

**Comment by mischnic** [comment]
I guess
```js
let Session;
try {
	Session = require("inspector").Session;
catch(_){}
```

The methods below should then be noops if the inspector isn't available and `startProfiling` would additionally warn "Profiling not available".

**Comment by Taym95** [comment]
I would like to give this issue a try!

https://github.com/parcel-bundler/parcel/blob/d24e09a9797af41a9d2c6c733b1c6cf6671d60c7/packages/core/workers/src/Profiler.js#L43

I was thinking about something like this:

```
try {  
    this.session = require("inspector").Session;
    this.session.connect();

    return Promise.all([
      this.sendCommand('Profiler.setSamplingInterval', {
        interval: 100
      }),
      this.sendCommand('Profiler.enable'),
      this.sendCommand('Profiler.start')
    ]);
} catch (err) {
    console.error('Profiling not available', err);
}
```
Is this the correct way?

**Comment by mischnic** [comment]
That could work as well.
