### ISSUE TITLE
V2: How to control `dist` directory 

### ISSUE THREAD

**Issue by olingern** [parcel-bundler/parcel#3820]
**Parcel Version**: 2.0.0-alpha.3.1
**OS**: Ubuntu 18.04

___
**Context**:

I have a pretty simple use case that worked well with parcel 1.x

Basically, I have a server that serves out of public directory where I'd like my build to be placed. 

Example:
`/server/public/js`

In Parcel's previous version, I just used the `-d` option to do something like:
`parcel watch ./app/client/src/index.tsx -d ./dist/server/public/js`

or

`parcel build ./app/client/src/index.tsx -d ./dist/server/public/js`

In the current version, I receive an error:
`error: unknown option -d`

I've tried finding this option via the README, `parcel --help build`, and searching "dist" on the repo. If this is documented somewhere, it's not clear and/or buried.
 
___
**Questions**
- Is there a migrating guide?

- Can I control where output is placed?

Coming from other configuration tools, this has been a godsend. So, thanks for the ease of use.

**Comment by mischnic** [comment]
> Can I control where output is placed?

Parcel 2 can do multiple "builds" at once, so a global dist dir didn't make sense anymore. In your case, adding this entry to your package.json should work:
```json5
{
  // ...
  default: "dist/server/public/js/index.js"
  // ...
}
```

> Is there a migrating guide?

That would definitely be part of the docs (yet to be written).

**Comment by olingern** [comment]
@mischnic I see. I wouldn't mind opening a PR on how to migrate building from v1 to v2. I'm sure I'll need some suggestions from reviews, though. 

Is that something that would go in the root 'README` ?

**Comment by mischnic** [comment]
The readme was originally the specification for Parcel 2 and unfortunately serves as documentation as well. This documentation should really go onto the website (https://github.com/parcel-bundler/website) but we haven't really setup anything yet.

**Comment by damianobarbati** [comment]
Is it possible to output the `dist` directory when using `yarn parcel index.html` without specifying anything in the `package.json`?

Otherwise testing the actual http serving files is not possible, there's no dist :)

**Comment by mischnic** [comment]
It's currently always in `.parcel-cache/dist`, here's some discussion about that: https://github.com/parcel-bundler/parcel/issues/3691.

With `parcel index.html` you don't need to start a http server yourself?
If you do want to do that, I'd recommend `yarn parcel watch index.html` so that you can setup a server in `dist` yourself.

**Comment by vladinator1000** [comment]
If you have scripts like
```json
  "scripts": {
    "build:client": "parcel build client/index.html --out-dir dist/client",
    "build:server": "parcel build server/index.js --target node --out-dir dist/server",
}
```

How would you migrate that to v2?

**Comment by mischnic** [comment]
@vladinator1000 At the moment, the only way is a monorepo-like setup (so with package.json in `client` and one in `server`).

**Comment by half-halt** [comment]
How about prod vs. dev/debug?

**Comment by mischnic** [comment]
In the meantime, `--dist-dir` was added for Parcel 2 (behave like v1's `--out-dir`)

**Comment by yairEO** [comment]
`2.0.0-nightly.558` on Windows 10: 

    > parcel build index.html --out-dir build
    
## Fails with error
    error: unknown option `--out-dir'

**Comment by olingern** [comment]
> My ass. must install weird nightly version, and read out-of-date docs and dumpster-diving the issues section to piece together how to build my project. wtf...

Dude, this work is people's free time. If it doesn't work for you, go build it yourself.

**Comment by yairEO** [comment]
@olingern - I have dedicated 15 years of my life to open-source, specifically javascript and am maintaining dozens of projects, full-time, without having a single sponsor and not asking for one. 

All I want is my time not wasted while I am grinding code for my open source projects which helps countless of people to achieve their goals with a single `npm install`, and am working hard to please all the users who open issues. 

When I say I've wasted time on Parcel, you should take notice I don't say this lightly. It probably came out too harsh and for that I am sorry, but I had spent many hours of my own birthday, just the other day, sitting alone trying to debug and make sense why weren't things working as expected. I promised that at my birthday I would release a big project which I have working on for over a month, and the stuff I said earlier made me miss my schedule and I failed to release the project exactly on my birthday, as a celebration event :/

**Comment by mischnic** [comment]
Both of your problems are listed here in the migration guide:
- https://v2.parceljs.org/getting-started/migration/#--out-dir
- https://v2.parceljs.org/getting-started/migration/#package.json%23main

It's not *our* responsibility to meet *your* deadline.

**Comment by yairEO** [comment]
@mischnic - sorry for wasting your time - deleted all my comments

**Comment by eduardobcastro** [comment]
`--dist-dir` is not working. It creates a lot of files in the root dir.

**Comment by mischnic** [comment]
@eduardobcastro You probably have a `main: "index.html"` line in your package.json. Remove that

**Comment by dev-ggaurav** [comment]
> @eduardobcastro You probably have a `main: "index.html"` line in your package.json. Remove that

This worked for me thanks!

**Comment by mkpasala** [comment]
> If you have scripts like
> 
> ```json
>   "scripts": {
>     "build:client": "parcel build client/index.html --out-dir dist/client",
>     "build:server": "parcel build server/index.js --target node --out-dir dist/server",
> }
> ```
> 
> How would you migrate that to v2?

its worked for me thanks

**Comment by mkpasala** [comment]
> In the meantime, `--dist-dir` was added for Parcel 2 (behave like v1's `--out-dir`)

its worked for me

**Comment by jamesvclements** [comment]
@mischnic in the monorepo setup, what’s the best way to ask for each `package/*` to have its own `dist` folder when you build from the root directory?

**Comment by devongovett** [comment]
@jamesvclements did you check out https://parceljs.org/getting-started/library/? You can define targets in each package.json (e.g. `main`/`module`).

**Comment by jamesvclements** [comment]
@devongovett
I did but I think I'm lost on the exact config. 

My repo structure looks like this:

```
/
  package.json
  packages/
    package/
      src/
        index.js
      package.json
```

The root `package.json` has the build command:

```
"build": "parcel build packages/*/src/*.js"
``` 

and the `package/package.json` has the `target`:

```
    "targets": {
        "default": {
            "distDir": "./dist"
        }
    },
```

but running `npm run build` from the root directory still outputs in `/dist/index.js` rather than `/packages/package/dist/index.js`

**Comment by jamesvclements** [comment]
Update—I found a workaround. I definitely don't think this is the correct way to do it, but specifying targets for each package lets me run one `build` command, and then I can publish individual packages with `npm publish packages/video-autoplay`, etc:

![CleanShot 2022-04-27 at 15 47 42@2x](https://user-images.githubusercontent.com/20052710/165618758-43d052cf-a144-4221-b90f-cd9b261e0627.png)

**Comment by Nikh9123** [comment]
> @eduardobcastro You probably have a `main: "index.html"` line in your package.json. Remove that

i don't have main: "index.html" this but it is also not working

**Comment by samiwazni** [comment]
My project is built with React and the server is apps-script. When I make changes the React index.html generates the changes to apps-script.
I run into an error: 
> embolab_booking_system@1.0.0 start
> parcel src/ --dist-dir ./apps-script

**error: unknown option `--dist-dir'**

**Comment by mischnic** [comment]
https://parceljs.org/getting-started/migration/#--out-dir

**Comment by samiwazni** [comment]
@mischnic  I do have it as:
"parcel build src/index.html --dist-dir"
"parcel build src/index.html --dist-dir"
