### ISSUE TITLE
[RFC][V2] Support multi source

### ISSUE THREAD

**Issue by brillout** [parcel-bundler/parcel#3822]
# 💬 RFC

I'm building an [SSR plugin for Parcel v2](https://github.com/brillout/parcel-ssr). My SSR plugin also does Static Rendering and I'd like my users to be able to define pages like this:

~~~
pages/package.json
pages/index.html
pages/landing/Landing.page.js
pages/landing/style.css
pages/about/About.page.js
~~~

My Static Render plugin then renders `About.page.js` and `Landing.page.js` into `pages/index.html`. In other words, an HTML transformer would take `pages/index.html` and return two new HTML assets: one HTML asset for `About.page.js` and another one for `Landing.page.js`.

This means that the user will have to define multiple sources:

~~~js
// pages/package.json
{
  "source": [
    {entry: "**/*.page.js", outDir: "dist/"},
    {entry: "index.html", outDir: "dist/"}
  ]
}
~~~

Related discussion: #3302.

**Comment by mischnic** [comment]
I'm not quite sure if I fully understood your setup (is the HTML file essentially a template?), but:
The `source` example you gave doesn't really convey that the JS and HTML assets are connected in the way you described. So I don't think this is something to be added to Parcel itself.

My idea to achieve this in "userspace": a transformer for `*.ssr.html`, that detects occurences of `<script src="./*.page.js">` and returns an asset for each JS file.

**Comment by devongovett** [comment]
Could you make a transformer from JS to HTML for each of the page.js files instead of the other way around?

**Comment by brillout** [comment]
> Could you make a transformer from JS to HTML for each of the page.js files instead of the other way around?

That should work :+1:. I'll try this, I guess this ticket can be closed in the meantime.

> doesn't really convey that the JS and HTML assets are connected in the way you described

They would be connected by the file directory structure. For example:

~~~
pages/index.html
pages/landing/Landing.page.js
pages/about/About.page.js
pages/about/index.html
~~~

The closest `.html` file to `pages/landing/Landing.page.js` is `pages/index.html`. And the closest to `pages/about/About.page.js` is `pages/about/index.html`.

I'm aware that such convention over configuration is not that widespread in JS world. I'm not settled on the design.
