### ISSUE TITLE
Cannot provide configuration values to node-sass

### ISSUE THREAD

**Issue by goyney** [parcel-bundler/parcel#383]
It is not possible to set configuration values for node-sass using Parcel. I would like to be able to set the node-sass configuration option `includePaths` so that I do not have super large `import "../../../../style.scss";` lines in my scss files.

**Comment by devongovett** [comment]
You can add a `.sassrc` or `.sassrc.js` file to configure sass. We need to document that better. Can you open an issue on https://github.com/parcel-bundler/website/issues?

**Comment by goyney** [comment]
I beg to differ. Adding a .sassrc file with `includePaths` does not work. I wrestled with it for about 3 hours today before giving up and going back to relative paths.

**Comment by tomatau** [comment]
Having the same issue. includePaths actually breaks relative imports too! It's also a bit frustrating having to remember to --no-cache after changing the includePaths setting.
Event a simple import from a .scss file inside node_modules doesn't work at all.

The format of the includePaths is a bit unclear too: 
- should it be a relative path?
- does the trailing slash that's used in some examples have an impact?

**Comment by chriszrc** [comment]
Looks like the answer for now is here - https://github.com/parcel-bundler/parcel/issues/39#issuecomment-353722786
