### ISSUE TITLE
Difference between "parcel" and "parcel watch"

### ISSUE THREAD

**Issue by damianobarbati** [parcel-bundler/parcel#3834]
What is the actual difference between running `yarn parcel index.html` and `yarn parcel watch index.html`? Are they just alias?

**Comment by mischnic** [comment]
`parcel index.html` is the same as `parcel serve index.html`: it starts a dev server and rebuilds the files on changes.

`parcel watch.html` rebuilds the files on changes into the dist folder without the server.

`parcel watch` = `parcel build` + automatic rebuild
`parcel` = `parcel server` = `parcel watch` + dev server

**Comment by damianobarbati** [comment]
Thanks @mischnic !
