### ISSUE TITLE
Parcel 2: The engine "parcel" appears to be invalid.

### ISSUE THREAD

**Issue by a-x-** [parcel-bundler/parcel#3838]
# 🐛 bug report

<img width="906" alt="Screenshot 2019-11-23 at 14 19 14" src="https://user-images.githubusercontent.com/6201068/69477865-7390a380-0dfc-11ea-9f78-bcbcd66396dc.png">

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | v12.13.0
| Yarn         | 1.13.0
| Operating System | macos mojave

**Comment by mischnic** [comment]
This is fixed in Yarn v1.18.0 and newer.
