### ISSUE TITLE
React Refresh doesn't work with TypeScript

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#3844]
> I tried in parcel@2.0.0-alpha.3.2, but it seems not work with TypeScript.
>
> _Originally posted by @foisonocean in https://github.com/parcel-bundler/parcel/issues/3499#issuecomment-557907073_

This is the problem (causing the wrapping transformer to not run for jsx/ts/tsx assets):
https://github.com/parcel-bundler/parcel/blob/cf3e84cbfc5d3f4a18da9fdcdacaae96c75b5550/packages/core/core/src/Transformation.js#L413-L415

T-220

**Comment by foisonocean** [comment]
Is there a new alpha release so I can help test if it works

**Comment by mischnic** [comment]
@foisonocean Not yet, unfortunately.

**Comment by thdxr** [comment]
I'm still running into this even with the nightly - is this still a problem?

**Comment by mischnic** [comment]
This particular problem is fixed. Maybe you can open a new issue with a reproduction for your problem?

**Comment by ranisalt** [comment]
Why is a new alpha version taking so long to launch? It looks like several relevant bugs have been fixed, more than previous alpha point releases.

**Comment by meriadec** [comment]
https://www.npmjs.com/package/parcel/v/2.0.0-alpha.3.2
