### ISSUE TITLE
What exactly is Parcel?

### ISSUE THREAD

**Issue by ericmorand** [parcel-bundler/parcel#3846]
Hi huys,

I'm very confused about what Parcel is.

At first, looking at the homepage (https://parceljs.org/), it looks obvious that it is a bundler:

`Blazing fast, zero configuration web application bundler`

But then, you scroll down and you discover that you have to start a dev server, which makes Parcel not a bundler but a development paltform:

`Run parcel index.html to start a dev server. Importing JavaScript, CSS, images, and more just works! 👌`

So my question is: what is Parcel exactly? If it is a development platform, where can I download the bundler itself - I use my own development platform. If it is a bundler, why does it come with a dev platform that could be a separate package?

**Comment by DeMoorJasper** [comment]
It's both a bundler and a dev server in one. So I guess it can be called a development platform, although we don't really do everything you'd expect in a fully fledged dev platform afaik. We don't provide any tooling for things like testing and type-checking (although type-checking and linting will be possible in Parcel 2. Actually testing as well now that I think of it although I wouldn't see the value in that)

In Parcel 2 the dev server will be a separate package, but it will also be part of the default config...

Anyway if you wanna use your own dev server, you can either use the Parcel cli and use `parcel watch ...` (https://parceljs.org/cli.html#watch) which just bundles the code and watches for changes and rebundles on changes. Or you can use the Node API if you'd prefer: https://en.parceljs.org/api.html

**Comment by ericmorand** [comment]
> In Parcel 2 the dev server will be a separate package, but it will also be part of the default config...

Does it mean that we will be able to not download the dev server if we don't need it? Or use it as a standalone dev server?

>  Or you can use the Node API if you'd prefer: https://en.parceljs.org/api.html

I'm reading this and I'll have some few questions about the API in a separate issue.

**Comment by DeMoorJasper** [comment]
> > In Parcel 2 the dev server will be a separate package, but it will also be part of the default config...
> 
> Does it mean that we will be able to not download the dev server if we don't need it? Or use it as a standalone dev server?

It does mean you can opt out of downloading the dev server if you use a custom parcel config, but you won't be able to use it as a standalone server as it's built specifically for use as a dev server with Parcel.

**Comment by ericmorand** [comment]
OK, thanks a lot, that's great. Time to try Parcel@next.
