### ISSUE TITLE
What about css extracting?

### ISSUE THREAD

**Issue by a-x-** [parcel-bundler/parcel#3847]
# ❔ Question

In webpack we have https://github.com/webpack-contrib/mini-css-extract-plugin.

I didn't found any doc or plugin or question about this must have feature in parcel 2.

**Comment by a-x-** [comment]
It's nice to have it enabled by default

**Comment by mischnic** [comment]
Could you please give a description/example of what you think should be changed?
I couldn't find any example usage of that webpack plugin.

**Comment by a-x-** [comment]
By default, css-in-js libraries dynamically inject style-elements into head, 
so css is bundled into js.

But there is best practice when css extracted out of js and bundled into separate css bundle along with js bundle

**Comment by devongovett** [comment]
Parcel doesn’t bundle CSS into JS like webpack does when you import a CSS file. It already goes into a separate CSS bundle by default.

**Comment by a-x-** [comment]
You can write about in the docs as a selling point. 

For me it does not work like this, though, but I cannot create minimal repro example

**Comment by mischnic** [comment]
We can't help you if you cannot tell us what you want. We cannot read your mind

**Comment by a-x-** [comment]
I understand,

Anyway, You can write about css extracting in the docs as a cool selling point.
