### ISSUE TITLE
How to write a bundle using the API?

### ISSUE THREAD

**Issue by ericmorand** [parcel-bundler/parcel#3848]
Reading the API documentation, it is not clear how we are supposed to write a bundle to the filesystem:

https://parceljs.org/api.html#bundle

Actually, it is unclear how to prevent Parcel from writing the bundle and assets itself - is setting `outDir` to undefined the way to go?

**Comment by DeMoorJasper** [comment]
Parcel will always output the bundles into the fileSystem
