### ISSUE TITLE
Is Parcel suitable for a monorepo toolchain with Typescript project references?

### ISSUE THREAD

**Issue by tommedema** [parcel-bundler/parcel#3853]
# ❔ Question

I'm trying to determine if Parcel is right for me. I'm looking to setup a toolchain with the following stack:

- Typescript project references (composite)
- Monorepo using Yarn workspaces + Lerna
- React (Typescript)
- Serverless framework (Parcel needs to bundle package to be zipped as artifact)

Unfortunately I haven't been able find much information at all regarding using Parcel with Typescript project references (i.e. where one typescript package imports another package within the same monorepo; Typescript understands the graph dependencies etc.).

Is Parcel suitable for a monorepo toolchain with Typescript project references?

**Comment by DeMoorJasper** [comment]
For project references there is a seperate issue https://github.com/parcel-bundler/parcel/issues/1839
Parcel has monorepo support, not entirely sure what you specifically want though.
React has been supported from the start, in Parcel 2 it's even more reliable with TypeScript due to the default ts transformer using Babel.
Not sure how the zipping of bundles would work. I guess we could create a zip per entrypoint? Maybe that would be a reporter plugin? Not entirely sure how you see this.

**Comment by tommedema** [comment]
Thanks @DeMoorJasper 

I'm giving it a try and documenting my attempt at https://github.com/tommedema/startup-boilerplate

So far it works by relying on Babel to pickup the linked packages, and my editor picks up the typings because it understands Typescript project references. It seems ugly that Typescript's native support for project references is not used by Babel, but it does work.

My approach re serverless is a little naive: I simply have parcel [bundle node_modules too](https://github.com/tommedema/startup-boilerplate/blob/master/packages/serverless-api/package.json#L11), and then the Serverless Framework [builds with Parcel prior to packaging](https://github.com/tommedema/startup-boilerplate/blob/master/packages/serverless-api/serverless.yml#L75), while completely [skipping all node_modules except for the Parcel bundled files](https://github.com/tommedema/startup-boilerplate/blob/master/packages/serverless-api/serverless.yml#L68). There are two problems with this approach:

1. it only works if the dependency in node_modules can be bundled/understood by Parcel, e.g. no unknown file types
2. it doesn't include implicit dependencies such as binaries that are packaged with the node_module

I'd really prefer to not have Parcel bundle node_modules, but then the Serverless framework doesn't know how to create the artifact since the node_modules would have to be flattened again (which is not the case in a mono repo).
