### ISSUE TITLE
File extension resolution list

### ISSUE THREAD

**Issue by demigor** [parcel-bundler/parcel#3855]
# 🙋 feature request
Currently we use Webpack config.resolve.extensions to specify customer/platform specific javascript files. Before switching to Parcel as our default bundler, we need to have this gap closed.

## 🤔 Expected Behavior
Using command line, specify file extensions priority list which is used to locate a module, imported without file extensions.

## 😯 Current Behavior

No known way to do conditional import based on default extensions.

## 🔦 Context

For example, there are components, which have different implementations for different target platforms. To use such component, we import it from js-file without file extension specified.
Depending on target platform, for Android build "*.android.js" extension has a priority before default "*.js" file, for OSX platform "*.osx.js" has a priority before default "*.js" file etc. In case of platform specific js file found, it replaces file with plain js extension. This is very convenient and clear approach (peeked from React Native team) to separate common and specific logic in single project.

## 💻 Examples

For example, my application has two build variants: for customer A and for customer B.
I define common code in normal *.js files, but specifics for customer A in *.a.js, and for customer B in *.b.js. For customer A I do build with "parcel --extensions .a.js,.js", so bundler includes only *.a.js files instead *.js file if and only if *.a.js file exists, otherwise *.js file is included.

For customer B, I use "parcel --extensions .b.js,.js" and have my customer-specific code imported from *.b.js files.

**Comment by yazfield** [comment]
Hi, I'd like to take this feature.
My plan is to write a utility function 

```resolveFileExtension(files?: Array<string>, extensions?: Array<string): ?Array<string>)```

this handles file path resolution based on `extensions` priority list.
The function will assume that the file versions are in the same directory.
i.e: if files=['user.js'] extensions=['.a.js', '.js'] the function expects user.a.js to be in the same folder as user.js.

I'd appreciate any suggestions or guidelines 😄

**Comment by mischnic** [comment]
(I'm talking about Parcel 2 here.)

Changing the priority based on globs (or adding "extensions") could be done with a custom resolver already, but with the current architecture, there might be much code duplication in the custom resolver. Not sure if using cli flag would fit with the current DX design.

Apart from this issue, we haven't found a good way to generate the extensions list
https://github.com/parcel-bundler/parcel/blob/9c883cb2b9c7331fe3d805bc1372879af624d252/packages/resolvers/default/src/DefaultResolver.js#L32
ideally, somehow from the parcelrc file (just using the extensions from the `transformers` list?) - but this list is also different per file type

cc @devongovett

**Comment by demigor** [comment]
Should be possible to either specify configuration file from cli or directly specify extensions from cli. This will allow standard package.json scripts to build for different targets.

**Comment by devongovett** [comment]
I don't think we should support non-standard extensionless imports. Node only allows js and json, and ts requires imports be extensionless. In ESM mode, Node actually requires all extensions to be explicit, even JS, but we won't go that far yet. Other than that, it's better for performance and also for less ambiguity if extensions are required. It's possible to write a custom resolver plugin that does something different if you like.
