### ISSUE TITLE
Can not add BrowserSync to the mix.

### ISSUE THREAD

**Issue by BrahimS** [parcel-bundler/parcel#386]
🙋 feature request?

### 🎛 Configuration (package.json)

```json
{
  "scripts": {
    "dev": "npm-run-all --parallel open lint:watch test:watch",
    "start": "browser-sync start --server",
    "open": "parcel index.pug",
    "lint": "esw src/js/*.js",
    "lint:watch": "npm run lint -- --watch",
    "test": "jest",
    "test:watch": "jest --watch",
    "build": "parcel build src/js/index.js -d build/output"
  },
  "devDependencies": {
    "autoprefixer": "^7.2.3",
    "babel-core": "^6.26.0",
    "babel-jest": "^22.0.3",
    "babel-preset-env": "^1.6.1",
    "browser-sync": "^2.21.0",
    "eslint": "^4.13.1",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-watch": "^3.1.3",
    "jest": "^22.0.3",
    "node-sass": "^4.7.2",
    "npm-run-all": "^4.1.2",
    "regenerator-runtime": "^0.11.1"
  },
  "dependencies": {
    "parcel-bundler": "^1.3.0",
    "parcel-plugin-pug": "^0.2.1"
  }
}
```

### 🔦 Context

i would like to get the connexion between parcel and browserSync working :)

it would be cool to find a solution directly by using the npm scripts

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v1.3.0
| Node             | v9.3.0
| npm/Yarn         | v1.3.2
| Operating System | macOS High Sierra v10.13.

**Comment by DeMoorJasper** [comment]
Please fill in the form...

**Comment by BrahimS** [comment]
Hi, DeMoor Jasper, first thanks for the good work, as you can see i've fill the form.
Are there any support for the browserSync server yet?
Best

**Comment by devongovett** [comment]
Sounds like an interesting plugin. Maybe it could be based on this one? https://github.com/Va1/browser-sync-webpack-plugin

**Comment by devongovett** [comment]
Closing, since it won't be handled by parcel core. Let us know if you end up writing a plugin though!

**Comment by padupuy** [comment]
@BrahimS I found a working example here https://github.com/trustyoo86/parcel-browsersync-proxy-example and you could improve it, launch in parallel the node server and parcel.

```json
{
  "scripts": {
    "dev": "concurrently --kill-others \"npm run browsersync\" \"npm run server\"",
  },
  "devDependencies": {
    "concurrently": "4.0.1",
  },
}
```

**Comment by umarzaman** [comment]
I m trying to use browser sync in my project when I run the server it loads the html but it never loads the stylesheet.

I am using this in my scripts:
`"start": "browser-sync start --server --index src/index.html",`
And if i use --files instead of --index I get error saying cannot get / in browser.
