### ISSUE TITLE
Changing publicUrl requires clearing the cache

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#3862]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
	"scripts": {
		"start": "parcel index.html",
		"build": "parcel build index.html"
	},
	"devDependencies": {
		"@babel/core": "^7.7.4"
	},
	"default": "dist/index.html",
	"targets": {
		"default": {
			"publicUrl": "SOME_URL"
		}
	}
}
```

`parcel build index.html`

## 🤔 Expected Behavior

Updating the `publishUrl` value should also change the html file.

## 😯 Current Behavior

Occurrences of the public url in the index.html aren't updated, e.g.
`<script src="SOME_URL/test.98afe41f.js"></script>`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |v2
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by kelvinz** [comment]
I don't even get the SOME_URL after clearing the cache. It seems that publicUrl just doesn't work for me using 2.0.0-alpha.3.2.
