### ISSUE TITLE
import svg error

### ISSUE THREAD

**Issue by jaysg** [parcel-bundler/parcel#3866]
![image](https://user-images.githubusercontent.com/28700250/70041638-7e1b1c00-15f8-11ea-81c6-aa5b4ea9cb1d.png)
![image](https://user-images.githubusercontent.com/28700250/70041690-8ecb9200-15f8-11ea-883f-2e54920204ff.png)
![image](https://user-images.githubusercontent.com/28700250/70041737-a4d95280-15f8-11ea-8fca-95cbd5497e38.png)
github:https://github.com/jaysg/TypeScriptDemo/tree/master/parcel-antd

**Comment by mischnic** [comment]
I cloned your repo, ran `yarn` and `yarn dev`, but there is no error in Chrome.
