### ISSUE TITLE
ReferenceError: module is not defined

### ISSUE THREAD

**Issue by MegaJSDeveloper** [parcel-bundler/parcel#3868]
# 🐛 bug report

module object not exists in <script></script> tags

## 🤔 Expected Behavior

inline scripts from `index.html` like this:
```html
<script> console.log(module) </script>
```
must have `module` object and must wrapped like assets

## 😯 Current Behavior

```Uncaught ReferenceError: module is not defined```

## 💁 Possible Solution
wrap content from inline scripts as assets

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | --------- |
| Parcel           | 1.12.4
| Node             | 12.13.1
| npm/Yarn         | npm 6.12.1
| Operating System | Windows 10 64x

**Comment by mischnic** [comment]
Which version of Parcel are you using?

**Comment by MegaJSDeveloper** [comment]
@mischnic I updated the issue, but I do not know how to find out the version of the globally installed package. the command `` npm list -g parcel`` does not produce anything. but I can say that the latest version. I installed parcel just now.

**Comment by mischnic** [comment]
Parcel 1 doesn't process inline assets: https://github.com/parcel-bundler/parcel/issues/808
