### ISSUE TITLE
Resolve config files from custom path?

### ISSUE THREAD

**Issue by IniZio** [parcel-bundler/parcel#387]
🙋 feature request

I am making a preset-based configuration tool [Clipped](https://github.com/clippedjs/clipped) which tries to solve pain of making recipes for build tools like webpack, rollup.

Since parcel seems really user friendly, I hope to make a preset of parcel as well.

### 🎛 Configuration (.babelrc, package.json, cli command)

Here i ran the a task in the preset which already has the .babelrc and postcss.config.js

```js
clipped.hook('dev')
  .add('parcel', clipped =>
    new Promise((resolve, reject) => {
       const bundler = new Bundler(clipped.resolve('index.html'), {watch: true})
       bundler.serve(8080)
    })
  )
```

### 🤔 Expected Behavior

hope could have an option  that can add module resolving paths like webpack's `module.resolve`

### 😯 Current Behavior

It seems like parcel searches for  the settings only within the package.json folder of the index.html rather than from `process.cwd()`, and does not provide an option to customize.

### 💁 Possible Solution

Add an option for custom configuration files path?

### 🔦 Context

hope to find a way to make a preset for parcel :thinking: 

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.2.1 |
| Node             | 8.7.0 |
| npm/Yarn         | 5.6.0 |
| Operating System | Ubuntu 17.10 |

**Comment by devongovett** [comment]
Most configurations that parcel supports (e.g. `.babelrc`, `.postcssrc`, `package.json`, etc.) are searched recursively upward from the file being imported. For example, if you had `package.json` at the root, and `src/index.js` and you ran `parcel src/index.js`, parcel would search upward until it found `package.json` in the root.

What particular issue are you having with this behavior?

**Comment by IniZio** [comment]
Like if my preset is at `/home/someone/apreset/` and i call `parcel /home/someone/realproject/index.html`, I hoped that it would use the configurations in `/home/someone/apreset` rather than in the project. That way just by importing the preset in [Clipped](https://www.npmjs.com/package/clipped), user can already use the configurations without repeatingly copy and pasting.

**Comment by stereobooster** [comment]
in my POV it is better to use convention over configuration otherwise it will be another webpack. I like https://github.com/davidtheclark/cosmiconfig approach - covers all existing use cases, standardize resolution algorithm.

**Comment by IniZio** [comment]
Yes I really like the current convention over configuration approach, just that I would like to make a feature request of having an option for alternate resolve path. I do not think it violates the current approach since it can be the default value.

**Comment by brandon93s** [comment]
> in my POV it is better to use convention over configuration otherwise it will be another webpack. I like davidtheclark/cosmiconfig approach - covers all existing use cases, standardize resolution algorithm.

`cosmiconfig` looks interesting, and I think is worth exploring separate from this discussion. Unfortunately, it doesn't look like it would satisfy the requested feature unless the config happened to be in a direct parent directory.

For the time being, I do not think supporting custom config file paths is in the spirit of parcel's objectives. Feel free to open a PR for review with proposed changes if you'd like.

**Comment by IniZio** [comment]
Thanks for the info, I will look for workarounds or make a PR. Parcel is awesome :+1: .
