### ISSUE TITLE
Received URL without a pathname for CSS behavior URL

### ISSUE THREAD

**Issue by treshugart** [parcel-bundler/parcel#3873]
Parcel version: 2.0.0-alpha.3.2

When Parcel comes across something like `behavior: url(#behavior)` in CSS files, it attempts to resolve the URL, but since it only contains a fragment (which is the behavior identifier), it throws:

```
🚨 Error: Received URL without a pathname
```

I know `behavior` was specific to older Internet Explorer releases and not supported by modern browsers, but some of these are in [dependencies](https://github.com/mapbox/mapbox.js/blob/publisher-production/theme/style.css#L155), so we have no control over how these URLs are being specified.

I was looking at writing a custom resolver to try and ignore these paths, but it seems that the `pathname` check comes before any resolvers can inspect it.

Is this a bug, or is there a way to work around this?

A possible solution for this might be to ignore the URL altogether if it contains a fragment but no pathname.

**Comment by yanneves** [comment]
Can confirm, just ran into this myself with an older Highcharts dependency, in this case `behavior:url(#default#VML);` may be the culprit.

**Comment by kud** [comment]
I've got the same problem with svg in my html:

```
                <svg role="img" class="kud-Svg kud-Svg--github">
                  <use href="#kud-Svg--github"></use>
                </svg>
```

`Error: Received URL without a pathname #kud-Svg--github.`

**Comment by massless** [comment]
I also have this same problem when including an SVG.  An example section within the SVG is this...

```html
<mask id="mask-3" fill="white">
  <use xlink:href="#logo-small-path-2"></use>
</mask>
```
