### ISSUE TITLE
Parcel 2 gets stuck when importing SVG files

### ISSUE THREAD

**Issue by samuelgozi** [parcel-bundler/parcel#3878]
# 🐛 bug report]
This is a parcel 2 issue.
I'm trying to import multiple svg icons in order to use them in my app.
`import icons from '../assets/icons/*.svg';`

However, this line parcel to get stuck at:
`⠸ Building *.svg...`
It just never finishes.
When importing a single file it doesn't happen.

## 🎛 Configuration (.babelrc, package.json, cli command)

The command im using is:
`parcel build src/index.html`
and I'm using in the project the svelte transformer:
```
"parcel-transformer-svelte": "^1.0.3"
```

`.parcelrc` looks like this:
```
{
	"extends": [
		"@parcel/config-default"
	],
	"transforms": {
		"*.svelte": [
			"parcel-transformer-svelte"
		]
	}
}

```

## 🤔 Expected Behavior

Should finish compiling or throw an error.

## 😯 Current Behavior

Never finishes...

## 💁 Possible Solution

As a quick fix, maybe how to disable the svg optimizer.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |^2.0.0-alpha.3.2
| Node             |12
| npm/Yarn         |1.19.2
| Operating System |Catalina

**Comment by devongovett** [comment]
Glob imports aren’t supported in Parcel 2 (yet?). You could use this Babel plugin I wrote which behaves the same way as Parcel 1: https://www.npmjs.com/package/babel-plugin-transform-glob-import

**Comment by samuelgozi** [comment]
@devongovett Thank you for the answer. Is this feature being considered?

**Comment by mischnic** [comment]
Apart from the feature request, this seems to now print an actual error:
`@parcel/resolver-default: Cannot find module './*.png'`

**Comment by Ajaxy** [comment]
> Glob imports aren’t supported in Parcel 2 (yet?). You could use this Babel plugin I wrote which behaves the same way as Parcel 1: https://www.npmjs.com/package/babel-plugin-transform-glob-import

@devongovett It doesn't work with the `url:` prefix — resulting to an empty object. Any workaround here?

**Comment by AngryBotIY** [comment]
> Glob imports aren’t supported in Parcel 2 (yet?). You could use this Babel plugin I wrote which behaves the same way as Parcel 1: https://www.npmjs.com/package/babel-plugin-transform-glob-import

How to use it?
