### ISSUE TITLE
Importing CSS from node_modules results in "undefined" class name in html

### ISSUE THREAD

**Issue by alexiwonder** [parcel-bundler/parcel#3879]
# 🐛 bug report

I could successfully import CSS/SCSS files into my React modules:
```
import * as styles from './my-component.css';
....
<div className= {`${styles.glory}`}>A text</div> // Which will be generated as <div class = "_glory_c5yp0">A text</div>
```
What I'm not able to do is to do the same for a CSS file in a `node_modules` package:

```
import * as styles from 'bootstrap/dist/css/bootstrap.css';
....
<div className= {`${styles.row}`}>A text</div> // Which will be generated as <div class = "undefined">A text</div>
``` 

## 🎛 Configuration (.babelrc, package.json, cli command)
.postcssrc
```
{
  "modules": true,
  "plugins": {
    "autoprefixer": {
      "grid": true,
    },
    "postcss-modules": {
      "camelCase": true
    }
  }
}
```
.babelrc
```
{
  "presets": [
    "@babel/preset-react",
    "@babel/preset-env",
    [
      "@emotion/babel-preset-css-prop",
      {
        "sourceMap": false
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    [
      "@babel/plugin-transform-runtime",
      {
        "regenerator": true
      }
    ]
  ]
}
```
Nothing fancy in package.json. Installed packages:
- `parcel-plugin-typed-css-modules`  
- `autoprefixer`
- `@types/autoprefixe`
- `postcss-modules`

## 🤔 Expected Behavior
```
<div className= {`${styles.row}`}>A text</div>
```
should be generated to
```
<div class = "row">A text</div>`
```
## 😯 Current Behavior

```
<div className= {`${styles.row}`}>A text</div>
```
is generated to
```
<div class = "undefined">A text</div>`
```

No error is generated. 

## 🔦 Context

I want to have type-check and intellisense for class names of the CSS stylesheets of installed npm packages like Bootstrap.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 10.16.3
| npm/Yarn         | 6.6.0
| Operating System | Windows 10

**Comment by alexiwonder** [comment]
Any help?

**Comment by DeMoorJasper** [comment]
This is mentioned in the docs. https://parceljs.org/css.html#usage-with-existing-css-libraries

We use the postcssrc closest to the file, and do not go outside of node_modules. So you would have to add a postcssrc file to the node_module. This is to prevent side-effects.

**Comment by alexiwonder** [comment]
@DeMoorJasper Thanks for your reply. I tried adding a `.postcssrc` file to `node_modules` folder with the following content:
```
{
  "modules": true,
  "plugins": {
    "autoprefixer": {
      "grid": true
    }
  }
}
```
Unfortunately, no success :(

**Comment by DeMoorJasper** [comment]
It should be in `node_modules/bootstrap` as that is the node module you're requiring. Hopefully this works, you will probably have to clear parcel cache as well as it didn't have a config file before

**Comment by alexiwonder** [comment]
@DeMoorJasper Legend!
Thanks so much 😊.
