### ISSUE TITLE
Tree shaking conflicts with auto inserted require("process")

### ISSUE THREAD

**Issue by dvarnai** [parcel-bundler/parcel#3890]
# 🐛 bug report

When using the experimental tree shaking feature, the auto inserted process module (https://github.com/parcel-bundler/parcel/blob/1.x/src/visitors/globals.js) doesn't always get bundled into the output file.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
parcel build src/index.html --experimental-scope-hoisting 
```

## 🤔 Expected Behavior

Process module should get bundled

## 😯 Current Behavior

```js
Error: Cannot find module 'process'
```

## 🔦 Context

Tried to use tree shaking with bootstrap-vue

## 💻 Code Sample

The following line triggers the issue when using bootstrap-vue
 (https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/utils/env.js):

```js
var env = typeof process !== 'undefined' && process ? process.env || {} : {};
```

Inserting the same in my own source file does bundle the module.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.4
| Node             |   13.3.0
| npm         |  6.13.1
| Operating System | macOS 1.15.1

**Comment by pipe01** [comment]
A workaround for bootstrap-vue is including the components you need directly by their file, for example
```js
import { LayoutPlugin } from 'bootstrap-vue/esm/components/layout'

Vue.use(LayoutPlugin);
```

This way the entire bootstrap-vue library won't be packaged.

**Comment by dvarnai** [comment]
> A workaround for bootstrap-vue is including the components you need directly by their file, for example
> 
> ```js
> import { LayoutPlugin } from 'bootstrap-vue/esm/components/layout'
> 
> Vue.use(LayoutPlugin);
> ```
> 
> This way the entire bootstrap-vue library won't be packaged.

Thanks for the advice, I was already doing that, unfortunately the util causing the issue is used by one of the plugins I use (at least I believe so)

**Comment by pipe01** [comment]
The tree shaking still doesn't work for me either, but I'm using this workaround instead of the tree shaking.

**Comment by DeMoorJasper** [comment]
Does this work in Parcel 2? We are trying to get it stable in Parcel 2 (as it'll be enabled by default)

**Comment by pipe01** [comment]
On Parcel 2 I get an unrelated Vue error:
```
vue.runtime.common.dev.js:4471 Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('http://localhost:1234/apphome.8b9202c5.vue') is not a valid name.
    at Object.isUnknownElement (http://localhost:1234/home.045275aa.js:5801:21)
    at isUnknownElement$$1 (http://localhost:1234/home.045275aa.js:6053:14)
    at createElm (http://localhost:1234/home.045275aa.js:6090:13)
    at Vue.patch [as __patch__] (http://localhost:1234/home.045275aa.js:6667:9)
    at Vue._update (http://localhost:1234/home.045275aa.js:4106:19)
    at Vue.updateComponent (http://localhost:1234/home.045275aa.js:4227:10)
    at Watcher.get (http://localhost:1234/home.045275aa.js:4638:25)
    at new Watcher (http://localhost:1234/home.045275aa.js:4627:12)
    at mountComponent (http://localhost:1234/home.045275aa.js:4234:3)
    at Vue.$mount (http://localhost:1234/home.045275aa.js:8565:10)
```

**Comment by DeMoorJasper** [comment]
@pipe01 ow I didn't realise this was a vue error, vue isn't supported in Parcel 2 yet.

thought the original issue was about `process.env`

**Comment by pipe01** [comment]
Well the original issue was about bootstrap-vue, which is used with Vue

**Comment by dvarnai** [comment]
> @pipe01 ow I didn't realise this was a vue error, vue isn't supported in Parcel 2 yet.
> 
> thought the original issue was about `process.env`

well the issue is triggered by the process polyfill not being bundled by parcel in this case with tree shaking enabled, removing the line mentioned in my original post fixes the issue. I actually just found a potentially similar bug report from a few months back:

https://github.com/parcel-bundler/parcel/issues/3179
