### ISSUE TITLE
Parcel 2: TypeScript definition generation is non-deterministic

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#3891]
It seems to depend on build order. In a monorepo, if some of the packages depended on by another package haven't built their types yet, you get relative paths instead of node_modules paths.

For example, with a setup like this:

```
packages
  - foo
    - package.json
    - index.ts
  - bar
    - package.json
    - index.ts
```

In each package.json, there is a `"types": "dist/index.d.ts"` field. When it doesn't exist yet, TypeScript falls back to resolving from `index.ts`.

If `bar` depends on `foo`, and builds before `foo/dist/index.d.ts` is generated, TypeScript will generate a `.d.ts` for `bar` with an import to `../foo/index` instead of `foo`. This appears to be because the path pointed to in foo's package.json doesn't exist yet. If foo builds first, bar's generated .d.ts will be correct.

I'm not sure how to fix this. The order packages build cannot be deterministic. If we cannot get TypeScript itself to fix it (doubt it), then we might need to check for relative imports in generated `.d.ts` files and re-resolve them to the package they would be importing. Not 100% sure if this is safe or not. Are there cases where we actually do want relative paths in generated .d.ts files?

**Comment by waynevanson** [comment]
Is this relating to generating type definitions for Parcel 2 or for bundling packages with Parcel 2?

If the first, does this mean that typescript types are not being generated for Parcel 2?

If the second, I plan to open a separate issue with the first: Are there any type definitions available for `parcel@next`?

**Comment by mischnic** [comment]
This is fixed when the `outFile` entry in the TS options is omitted:
https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/typescript-types/src/TSTypesTransformer.js#L40

But then the visitor for `program.emit` get called on each SourceFile and not once on the whole bundle...
