### ISSUE TITLE
Parcel 2: Terser configuration is not respected without "--no-source-maps"

### ISSUE THREAD

**Issue by machsix** [parcel-bundler/parcel#3892]
# ❔ Question

https://github.com/parcel-bundler/parcel/blob/7eab25079157fb6e6afc2269b68944887c3d3683/packages/optimizers/terser/src/TerserOptimizer.js#L38-L60

Terser configuration is overwritten without "--no-source-maps". Is it a bug or the designed feature?

**Comment by mischnic** [comment]
This is fixed now: https://github.com/parcel-bundler/parcel/blob/8e80016d8b61c5d68759bfd1caa9fb827e46643c/packages/optimizers/terser/src/TerserOptimizer.js#L27-L45
