### ISSUE TITLE
Parcel 2: Should differential script loading cause duplication of non-js dependencies?

### ISSUE THREAD

**Issue by tylerbrostrom** [parcel-bundler/parcel#3898]
# ❔ Question

1. Should differential script loading cause duplication of non-js dependencies? (Currently it does.)

1. How much of a concern is this really? Should a special case be made to dedupe non-js dependencies in these scenarios?

1. Can we confidently say that certain types of assets (e.g. CSS, images, videos, etc.) don’t change from `<script nomodule>` to `<script type="module">`? (Initial thought is yes.)

## 🔦 Context

When a JS asset is included twice using the differential loading technique, that JS asset’s dependencies will be duplicated. While this behavior is somewhat expected—and in the case of JS dependencies, desirable—it has the undesirable effect of duplicating CSS, images, videos, etc.

### Input

```html
<!-- src/index.html (entrypoint for app) -->
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    …
    <script type="module" src="./some-script.js"></script> 
    <script nomodule src="./some-script.js"></script>
    …
```

```js
// some-script.js
import "./styles.css";
```

### Output

```html
<!-- dist/index.html -->
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="/some-script.82756a35.css" />
    <link rel="stylesheet" href="/some-script.03410cc1.css" />
  </head>
  <body>
    …
```

The quick solve for this example is:
>Just move your css to the html entrypoint.

But I'd have to imagine there are scenarios where that solve is not ideal, or even impossible.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2

**Comment by mischnic** [comment]
I've just tried this again, and the html bundle now contains two link tags to the same file.
```html
<!-- dist/index.html -->
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="/some-script.ecf8427e.css" />
    <link rel="stylesheet" href="/some-script.ecf8427e.css" />
  </head>
  <body>
    …
```

Relevant code: https://github.com/parcel-bundler/parcel/blob/14eaa0f4bcddc79efa3ba383dbd0726f16ca0276/packages/packagers/html/src/HTMLPackager.js#L60

**Comment by devongovett** [comment]
Appears to work properly in the latest nightly.
