### ISSUE TITLE
How are multiple global variables specified?

### ISSUE THREAD

**Issue by jeremyong** [parcel-bundler/parcel#3899]
❔ Question

Using the `--global` flag, I was able to denote that a variable belongs to the global context. However, I haven't had any luck getting this to work with multiple variables (tried comma delimiters which didn't work for example).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.4
| Node             |v13.3.0
| npm         |6.13.2
| Operating System |Linux

**Comment by mischnic** [comment]
So you want to have multiple global variables for the exports that point to the same value?

**Comment by jeremyong** [comment]
Point to different values

**Comment by mischnic** [comment]
That doesn't really work with the `--global flag`, because it doesn't know what the value should be.
You can just set global variables in your JS code. Can you explain further why you want to do this?

**Comment by jeremyong** [comment]
I may have misunderstood what the flag was for. To provide more context, I had an ambient declaration for a global in a typescript declaration file, but I found that when transpiled, the final output failed to resolve naked references to the variable (for example, `my_global` as opposed to `window.my_global`). Adding `my_global` to the flag fixed this, and I was wondering how to achieve the same behavior for more such references.

**Comment by mischnic** [comment]
`--global foo` does this when you invoke parcel on this file
```js
module.exports = {something: 1234}
```

and then use the produced bundle:

```html
<script src="dist/bundle-from-parcel.js"></script>
<script>
	console.log(foo) // == {something: 1234}
</script>
```

**Comment by jeremyong** [comment]
Ok that clears up exactly what's happening thanks. I did indeed misunderstand the docs here.

Cheers
