### ISSUE TITLE
Importing CSS from node_modules

### ISSUE THREAD

**Issue by shiloa** [parcel-bundler/parcel#39]
Hi,

Looks very cool!

I have a SCSS file in a project that imports CSS from `node_modules` using `@import` declaration:

```scss
@import '~some-package/path/to/style';
@import '../../styles/colors';

// etc...
``` 

When I run parcel I get the following error:

```
🚨  /Users/shiloa/projects/myapp/src/components/MainApp.scss: File to import not found or unreadable: ~some-package/path/to/style.
Parent style sheet: stdin
```

I should note that I did not configure anything specifically for parcel before running `parcel src/index.jsx` (I have an existing webpack and babel configuration). Do I need some special configuration to support SCSS files or `@import` from `node_modules` ?

**Comment by devongovett** [comment]
The node_modules resolution algorithm isn't implemented yet for SASS/SCSS. Currently you could make a `.sassrc` or `.sassrc.js` file to configure the node-sass `includePaths` option to include `node_modules`.

The real solution will be to replace sass's default resolution algorithm with parcel's (node). I recently did this for stylus, so just a bit more work for sass.

**Comment by shiloa** [comment]
Sounds good - thanks!

**Comment by StarpTech** [comment]
@devongovett I tried it with `.sassrc` but it doesnt work.

```
@import "./variables";
@import "bulma/bulma.scss";
```
```
{
  "includePaths": [
    "node_modules"
  ]
}
```
```
> parcel watch ./app/index.js

🚨  E:\Repositorys\pe-dotnet-core\src\pe-dotnet-core\wwwroot\app\styles\app.scss:2:1: File to import not found or unreadable: bulma/bulma.scss.
Parent style sheet: stdin
    at options.error (E:\Repositorys\pe-dotnet-core\src\pe-dotnet-core\wwwroot\node_modules\node-sass\lib\index.js:291:26)
```

**Comment by shiloa** [comment]
I agree, still running into the same issue. Haven't had a chance to look at the source that originates it yet.

**Comment by DanielRuf** [comment]
Same here. It resolves some but not all, especially subdirs.

**Comment by j-o-d-o** [comment]
**Here is a quick workaround until this issue is resolved:**
I am having this folder structure:
![unbenannt](https://user-images.githubusercontent.com/15958535/34082183-03f38a0c-e35a-11e7-92e4-1f833229b42b.PNG)

Change your scripts like this in **package.json**:
```
{
  "scripts": {
    "build-css": "node-sass --include-path node_modules src/index.scss src/bundle.css",
    "watch-css": "node-sass --include-path node_modules src/index.scss src/bundle.css --watch --recursive",--watch --recursive",
    "start-parcel": "parcel src/index.html",
    "start": "npm-run-all -p watch-css start-parcel",
    "build": "npm run build-css && parcel build src/index.html"
  },
  ...
}
```

Note that you need npm-run-all as a dev dependencies, so run:
`>> npm install --save-dev npm-run-all`

In your index.js file just import the css file:
`import './bundle.css';`

----

So here is what's going on. node-sass is building a css file: `bundle.css` when running `>> npm run build-css` or is watching the whole process with `npm run watch-css` and adds the node_modules path. 
In index.js instead of importing the scss file just import the created bundle.css file.
I was successfully able to import all the material components web scss files like this.

**Comment by StarpTech** [comment]
This looks a like manual way to build sass files. This isn't a workaround for parcel but thanks. Until this is fixed I will use another build tool.

**Comment by DanielRuf** [comment]
@StarpTech maybe there is one at https://github.com/danielruf/awesome-bundlers

**Comment by j-o-d-o** [comment]
@StarpTech yes, manually building sass files and then adding the css file to the parcel build. To me this falls exactly into the definition of a workaround ; )

**Comment by xzyfer** [comment]
FWIW the Sass import resolution algo is non-trival to reimplement. Keep in mind Sass is ~10 years old with tens of millions of lines of Sass could out in the wild. 

Any subtle changes to the import resolution algo could break a lot of existing code. I suggest looking at https://github.com/sass-eyeglass/eyeglass for prior work in the field of adapting Sass' import resolution for node_modules.

**Comment by tomatau** [comment]
I've been fighting with this for a while using .sassrc as a JSON object and yaml, neither worked.
But!

I changed to .sassrc.js and added the following configuration:

```js
const path = require('path')

const CWD = process.cwd()

module.exports = {
  "includePaths": [
    path.resolve(CWD, 'node_modules'),
    path.resolve(CWD, 'src')
  ]
}
```

This works like a charm :)

PS. don't forget to `--no-cache`

**Comment by lowski** [comment]
@tomatau thanks - this work like a charm!

`--no-cache` (parcel `src/index.html --no-cache`) is important - without this it throws the same error.

**Comment by ryuheechul** [comment]
I am still having the same issue even though I added `.sassrc.js` as suggested above.
I'm trying to change [this](https://github.com/grommet/grommet-standalone) to use parcel instead of webpack

and got this message
```shell
🚨  /Users/me/grommet-standalone/node_modules/grommet/scss/vanilla/index.scss:4:1: File to import not found or unreadable: inuit-defaults/settings.defaults.
Parent style sheet: /Users/me/grommet-standalone/node_modules/grommet/scss/grommet-core/_settings.scss
    at options.error (/Users/heechul/me/grommet-standalone/node_modules/node-sass/lib/index.js:291:26)
```

**Comment by jeanleonino** [comment]
Working like a charm here with `bulma`. Not intuitive, should be documented, but working.

**Comment by bfred-it** [comment]
I think that until this is fully implemented it's best to just use the ugly-but-perfectly-working

```scss
@import url(node_modules/blahblah/file.scss)
```

**Comment by TotomInc** [comment]
Any plans on this?

**Comment by eirikb** [comment]
The solution by @tomatau works for me, thanks! It would really be nice if this fix was part of parcel somehow, as I think this is very common thing to do.
@bfred-it I don't think that approach works if the `file.scss` again imports stuff from other dependencies, like material-components-web does with  `@material/button` : `@import "@material/ripple/common";`

**Comment by TotomInc** [comment]
@eirikb how did this works for you? It looks like parcel doesn't take my `.sassrc.js` configuration file. I have done the same steps and I'm running parcel with `--no-cache` flag.

**Comment by eirikb** [comment]
@TotomInc This is how I did it: https://gist.github.com/eirikb/ea6248feab5411a5e4a6bf720ab984fe . I didn't need the `--no-cache` flag, or at least id doesn't seem so.
The demo is missing `src` folder simply because of gist.
Run like this:
```shell
nvm use 8.10.0
git clone https://gist.github.com/eirikb/ea6248feab5411a5e4a6bf720ab984fe
cd ea6248feab5411a5e4a6bf720ab984fe
npm i && npm start
```

**Comment by TotomInc** [comment]
Thanks for taking the time to do a gist @eirikb, it really helps a lot! 😄

**Comment by matthewmorgan** [comment]
@erikb your approach worked for me but only using `--no-cache`.  Thanks for that.

**Comment by safareli** [comment]
using `.sassrc.js` messes staff up see #1280

**Comment by dobesv** [comment]
One workaround is to symlink the node_modules path into your source tree, e.g.

    ln -s ../../../../node_modules/bootstrap-sass/assets/stylesheets/bootstrap bootstrap

**Comment by DanielRuf** [comment]
I guess there are still just workarounds and no real fixes or the "right" solution.
I'm a bit sad to see that Parcel started so strong and now has so many (small) issues which make the dev life harder again as most devs need a bit more complex configs for bigger projects.

That is one of the reasons why I evaluated Parcel for my frontend colleagues and decided against it as it would have reduced all the possibilities, introduced new issues and hurdles and created a new whole ecosystem (we work on enterprise projects so it is crucial for such big teams to have a reliable solution without changing the whole toolchain and workflows).

How can we (the community) support Parcel and bring it forward or what is the current status of it?

**Comment by thiagovilla** [comment]
We could start by listing and prioritizing the current issues, gathering who's interested in improving Parcel, and then (optional: split into teams and) start working.

**Comment by DanielRuf** [comment]
That would be great as I see much interest in the community and possibly people who could solve the issues together.

**Comment by franz899** [comment]
What about integrating https://github.com/sass-eyeglass/eyeglass?

I've created a small example, its just two lines of code and it solves the problem of importing sass files from node_modules.

I still have to add tests for it.

**Comment by LukBukkit** [comment]
I'm using the package [node-sass-package-importer](https://github.com/maoberlehner/node-sass-magic-importer/tree/master/packages/node-sass-package-importer) with this you can use `~` for importing from the `node_modules` and it includes css files, if you omit the `.css` extension.
As a result a scss file could look like this:
```scss
// Importing a css file from the node_modules
@import "~frappe-charts/dist/frappe-charts.min";

// Importing a scss file from the node_modules
@import "~uikit/src/scss/uikit-theme.scss";
```

To you this node-sass importer install the package and create a `.sassrc.js` file:
```js
const packageImporter = require('node-sass-package-importer');

module.exports = {
    importer: [
        packageImporter()
    ]
};
```

I hope this can help you guys 😉

**Comment by michaelpumo** [comment]
I couldn't get Parcel to import CSS files from `node_modules` within SCSS files, but for what it's worth, it works within JS files. 

I needed to use `normalize.css` from `node_modules`, so I simply imported the CSS from within my `app.js` (entry file) like so:

**/js/app.js**

`import '../node_modules/normalize.css/normalize.css'`

This appeared to work just fine and upon running `parcel build ./js/app.js`, the CSS is combined into the `app.css` file that Parcel produces (as expected).

Hope this helps someone.

**Comment by alexandernst** [comment]
Why can't parcel handle all this nonsense by it's own?!

**Comment by phifa** [comment]
What is the recommended practive here? @DanielRuf were you able to get it working with foundation? I am looking for a faster alternative when working with webpack and foundation.

**Comment by DanielRuf** [comment]
> What is the recommended practive here? @DanielRuf were you able to get it working with foundation? I am looking for a faster alternative when working with webpack and foundation.

A faster alternative for webpack + Foundation?
It depends.

Do you want to keep webpack or use Parcel?
We tried Parcel but it had too many issues at the time and did not test further. Our setups are all with current webpack versions.

**Comment by figalex** [comment]
> Indeed, it works! Though what I find spooky is the fact that mentioning the name of the missing dependency `Buffer` in a comment or string includes it in the bundle:

@is-already-taken did you ever figure out why do you need the "magic" comment including the word "Buffer"?
I had the same problem and that magic comment solved it but I don't like magic 🙃

**Comment by juniorgarcia** [comment]
Right here I'm importing like

```scss
@import "~bootstrap/scss/grid";
```

and my `.sassrc` is like
```json
{
    "includePaths": ["node_modules"]
}
```

Everything is working fine with Parcel v1.10.3.

**Comment by bionicles** [comment]
getting this problem. frustrating because I thought parcel was meant to be simpler and easier than webpack -- it can't find Bulma sass files?

**Comment by coder82** [comment]
@juniorgarcia that worked!

**Comment by blowsie** [comment]
> Why can't parcel handle all this nonsense by it's own?!

My first time using parcel and I have some level of agreement with this statement since parcel is a "zero configuration web application bundler"

**Comment by molecule** [comment]
Is there any resolution or recommended work-around for this?

**Comment by steinwaywhw** [comment]
For me, simply writing `@import "normalize.css/normalize.cc` works. I'm using Parcel 1.12.4.

**Comment by weirdyang** [comment]
I've tried what is suggested but I cant get it to work, is my folder structure wrong?

![image](https://user-images.githubusercontent.com/25576022/155595309-71f58c80-2dd7-41f1-b9ab-203a68c08340.png)
