### ISSUE TITLE
yarn-error.log published with @parcel/logger@1.11.1 triggering GitHub Vulnerability Alert

### ISSUE THREAD

**Issue by Kmaschta** [parcel-bundler/parcel#3900]
# 🐛 bug report

It seems that a `yarn-error.log` file was published inadvertently by @devongovett in the `@parcel/logger@1.11.1` package.
This file contains a reference to `safer-eval` which has a critical vulnerability. This **do not** affect parcel users in any ways.

That being said, it seems that GitHub parses this file and trigger a GitHub Alert anyway.

## 🎛 How to Reproduce
In order to reproduce, install the package, and you'll find the file at `node_modules/@parcel/logger/yarn-error.log`.

```bash
$ yarn add @parcel/logger@1.11.1
$ head node_modules/@parcel/logger/yarn-error.log -n 25

Arguments: 
  /Users/devongovett/.nvm/versions/node/v8.11.1/bin/node /Users/devongovett/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js add @parcel/workers

PATH: 
  /Users/devongovett/.nvm/versions/node/v8.11.1/bin:/Users/devongovett/.cargo/bin:/Users/devongovett/Downloads/emsdk_portable:/Users/devongovett/Downloads/emsdk_portable/clang/e1.35.0_64bit:/Users/devongovett/Downloads/emsdk_portable/node/4.1.1_64bit/bin:/Users/devongovett/Downloads/emsdk_portable/emscripten/1.35.0:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/devongovett/.cargo/bin:/usr/local/mysql/bin

Yarn version: 
  1.10.1

Node version: 
  8.11.1

Platform: 
  darwin x64

Trace: 
  Error: https://registry.npmjs.org/@parcel%2fworkers: Not found
      at Request.params.callback [as _callback] (/Users/devongovett/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:61073:18)
      at Request.self.callback (/Users/devongovett/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:120166:22)
      at emitTwo (events.js:126:13)
      at Request.emit (events.js:214:7)
      at Request.<anonymous> (/Users/devongovett/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:121138:10)
      at emitOne (events.js:116:13)
      at Request.emit (events.js:211:7)
      at IncomingMessage.<anonymous> (/Users/devongovett/.nvm/versions/node/v8.11.1/lib/node_modules/yarn/lib/cli.js:121060:12)
```
In this file, you can see a reference to `safer-eval`:

```bash
$ grep "safer-eval" node_modules/@parcel/logger/yarn-error.log

safer-eval@^1.2.3:
  resolved "https://registry.yarnpkg.com/safer-eval/-/safer-eval-1.2.3.tgz#73ba74a34bc8a07d6a44135c815fd18a8eebe7a0"
    safer-eval "^1.2.3
```

Even tho this dependency is no longer used in parcel.

Having this dependency on any GitHub repository will trigger a vulerability alert:

![image](https://user-images.githubusercontent.com/1819833/70607123-2aaf5c00-1bfe-11ea-9e27-8655440a84b9.png)

## 💁 Possible Solution

Apart explaining this situation to all `@parcel/logger` users, I don't know if there is a solution.

May I suggest that next versions of Parcel packages should ignore `yarn-error.log` file.

I didn't try to find this file in other versions of Parcel packages.
I contacted the GitHub Support to get more info about that alert, I'll update the issue when they respond.

**Comment by DeMoorJasper** [comment]
I guess we can publish a new version to fix this? Not entirely sure if it's worth it though...

People do tend to get stuck on these warnings, even though most of them aren't even really vulnerabilities...

**Comment by Kmaschta** [comment]
I agree, this is not threat to anyone, and there is no real security issue about that.
But this "critical severity vulnerability issue" coming from GitHub is kind of spooky.

Moreover, I received this alert on the repository of a library I maintain. It's possible that all dependents received the same alert, and I'm not sure how to react.
It's just noise, this is why I contacted GitHub to see if they can suppress that warning, I'm not sure they need to parse `yarn-error.log` (but I might miss something).

Having a new version just to suppress that warning might be cumbersome, I'd understand that. It's up to you!

**Comment by Kmaschta** [comment]
Hello !
I received an answer from GitHub support, and it seems that the vulnerability alert comes from a cache issue on their end.

I guess that we can close this issue!

**Comment by benpolinsky** [comment]
Hi,

Not sure I follow the reasoning. After a fresh install of parcel, a `npm ls safer-eval` reveals:
```
`-- parcel@1.11.0
  `-- serialize-to-js@1.2.1
    `-- safer-eval@1.2.3
```
How does parcel not rely on this package?

**Comment by Kmaschta** [comment]
On our library, we use [pasteljs](https://www.npmjs.com/package/pasteljs), which uses directly parcel-bundler@1.12.4 and not parcel.

**Comment by benpolinsky** [comment]
Sorry! I had an old version in my `package.json` as well-- whoops.

Just wanted to be certain - thanks all.
