### ISSUE TITLE
Plugin not detected if its not on npm 

### ISSUE THREAD

**Issue by SindreSvendby** [parcel-bundler/parcel#391]
🐛 bug report 

Hi, I'm trying to work on a plugin, and it's not published to NPM yet.
Im able to install it with `yarn install` so yarn find the plugin, but when running parcel, it 
complains it can not find it and is not on npm registry.

Create and minimal example here: https://github.com/SindreSvendby/parcel-plugin-minimal-example

### 🤔 Expected Behavior

Your able to run parcel and it will find the parcel-plugin-example and try to use it

### 😯 Current Behavior

when running parcel I get the following error:
`error Couldn't find package "parcel-plugin-example" on the "npm" registry`

### 🔦 Context

I want to work with developing a parcel plugin without publishing it.

**Comment by ssuman** [comment]
https://github.com/SindreSvendby/parcel-plugin-minimal-example/blob/master/parcel-plugin-example/package.json. Could you try changing main from index.js to main.js ? OR change the name to index.js ?

**Comment by DeMoorJasper** [comment]
As long as the package.json and name of the plugin starts with ``parcel-plugin-`` it should work.
@ssuman 's fix should work

**Comment by SindreSvendby** [comment]
Yes, indeed. My bad.
