### ISSUE TITLE
Parcel 2 and TypeScript

### ISSUE THREAD

**Issue by Pi-Bouf** [parcel-bundler/parcel#3911]
# 🐛 bug report

I have some trouble on TS ! When I try this:

```
export class Test1 {
    constructor(
        private _sausage: string
    ) {
    }
}
```

I got that error:
```
× @parcel/transformer-babel: Unexpected reserved word 'private' (5:8)
C:\Holo5-Client\Client\Sources\ts\Test1.ts:5:8
  4 |     constructor(
> 5 |         private _saucisse: string
>   |        ^
  6 |     ) {
  7 |     }
```

This `transformer-babel` really don't help me... x)

## 🎛 Configuration (.babelrc, package.json, cli command)
parcel Client\Sources\ui.html

```js
{
  "plugins": [
    "@babel/plugin-transform-runtime",
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose" : true }]
  ],
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": "> 0.25%, not dead",
        "useBuiltIns": "entry"
      }
    ]
  ]
}
```

## 🤔 Expected Behavior

A functional Parcel ? :D

## 🔦 Context

No context, brand new solution without any dependencies except parcel and babelrc's stuff in .babelrc

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2 beta
| Node             | latest
| npm/Yarn         | latest
| Operating System | windows

**Comment by mischnic** [comment]
You need to use add `@babel/preset-typescript` to your babelrc.

(Parcel 1 merged its default babelrc with the one you provide, but that caused issues as well. So Parcel 2 uses the project's babelrc without modifications.)

**Comment by Pi-Bouf** [comment]
Oooooooookay I see ! Where we can find thin kind of information please ?

Thank you very much Dude !

**Comment by mischnic** [comment]
We really need to start writing the docs for Parcel 2 😬
