### ISSUE TITLE
Tree shaking not working with Typescript

### ISSUE THREAD

**Issue by ShirasawaSama** [parcel-bundler/parcel#3914]
# 🐛 bug report

Tree shaking not working with Typescript.

**When a typescript interface is imported**

## 🎛 Configuration (.babelrc, package.json, cli command)

tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "esnext",
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "experimentalDecorators": true,
    "noEmit": true,
    "jsx": "react",
    "isolatedModules": true,
    "lib": ["webworker", "scripthost", "dom", "es2019"]
  },
  "include": [
    "src"
  ]
}
```

## 🤔 Expected Behavior

The error should not occur, and the code should be compiled successfully.

## 😯 Current Behavior

Error:
```
×  src\utils\index.ts does not export 'DownloadItem'
  at replaceExportNode (%PROJECT%\node_modules\parcel\src\scope-hoisting\concat.js:55:13)
  at ReferencedIdentifier (%PROJECT%\node_modules\parcel\src\scope-hoisting\concat.js:342:20)
  at newFn (%PROJECT%\node_modules\@babel\traverse\lib\visitors.js:216:17)
  at NodePath._call (%PROJECT%\node_modules\@babel\traverse\lib\path\context.js:55:20)
  at NodePath.call (%PROJECT%\node_modules\@babel\traverse\lib\path\context.js:42:17)
  at NodePath.visit (%PROJECT%\node_modules\@babel\traverse\lib\path\context.js:90:31)
  at TraversalContext.visitQueue (%PROJECT%\node_modules\@babel\traverse\lib\context.js:112:16)
  at TraversalContext.visitSingle (%PROJECT%\node_modules\@babel\traverse\lib\context.js:84:19)
  at TraversalContext.visit (%PROJECT%\node_modules\@babel\traverse\lib\context.js:140:19)
  at Function.traverse.node (%PROJECT%\node_modules\@babel\traverse\lib\index.js:84:17)
```

## 💁 Possible Solution

Add interfaces export check for typescript or clear interfaces export before compiling.

## 🔦 Context

I ran this code:

```bash
parcel build index.html --target electron --public-url . --bundle-node-modules --no-source-maps --experimental-scope-hoisting
```

## 💻 Code Sample

a.ts:

```ts
export interface DownloadItem { url: string, file: string }
```

b.ts:

```ts
import { DownloadItem } from './a.ts'

export { DownloadItem } from './a.ts'

const obj: DownloadItem = { url: 'foo', file: 'bar' }
window.download(obj)
```

Then compile `b.ts` by parcel.

This file can be found in my [project](https://github.com/Apisium/PureLauncher/blob/master/src/utils/index.ts#L59).

I've tried to use `isolatedModules: false` and `sideEffects: false` in the config files, but it still don't work.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 12.12.0
| npm         | 6.11.3
| Operating System | Windows 10
| Typescript | 3.7.3

**Comment by smithki** [comment]
Is there a current workaround to this issue?

**Comment by DeMoorJasper** [comment]
Does it work with parcel 2? We’ve been adding a lot of tree shaking fixes to it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by smithki** [comment]
> Does it work with parcel 2? We’ve been adding a lot of tree shaking fixes to it

I'm not totally clear on how to implement Parcel 2 in an express server (which is my use-case currently). I've searched for documentation, but I can't find it 😞

For now I'm following the [source code here](https://github.com/parcel-bundler/parcel/blob/v2/packages/core/parcel/src/cli.js). Is there a migration guide I'm missing?
