### ISSUE TITLE
Script tag in HTML

### ISSUE THREAD

**Issue by horosgrisa** [parcel-bundler/parcel#3915]
# ❔ Question

I have a deprecated site with `html` with 

```html
<script src="assets/js/jquery.min.js"></script>
<script src="assets/js/main.js"></script>
```
But in `main.js` appear error '$ not defined'.
I understand that Parcel wraps the content of `jquery.js` and `$` doesn't appear in `window`.
How I can add script tag is as without wrapping/modifications?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
You could:
- use a CDN for jQuery
- import jQuery in main.js like this `import jquery from "jquery";`
- create a wrapper `jquery.js` that doesn: `import jquery from "jquery"; window.$ = jquery;`

**Comment by horosgrisa** [comment]
@mischnic OK, I understand that I can use CDN. But I have not the only jQuery, but I also have a lot of HTML files, with large set of dependencies.

**Comment by mischnic** [comment]
Please see https://github.com/parcel-bundler/parcel/issues/357
