### ISSUE TITLE
postcss-url does not work properly with url: "inline" option

### ISSUE THREAD

**Issue by gokhantaskan** [parcel-bundler/parcel#3916]
# ❔ Question

I want to see a base64 encoded image in my css file.
I just wonder how to make it.
Official documentation: https://github.com/postcss/postcss-url#inline

## 🔦 Context

What I want to accomplish:
```
background: url("data:image/svg+xml...")
```
What I got:
```
background: url("/assets/urlINLINE.f34b6713.png")
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.4
| Node             |12.13.1
| npm         |6.12.1
| Operating System |Windows 10 Pro 64bit

**Comment by gokhantaskan** [comment]
postcss.config.js
```
/* eslint-disable no-undef */
module.exports = {
  "plugins": {
    "autoprefixer": {
      "grid": true
    },
    "postcss-url": {
      url: "inline"
    }
  }
};
```

**Comment by mischnic** [comment]
Parcel works like this
- the url is replaced with a random hash
- postcss runs (including plugins)
- when bundling assets into a single output bundle, the hash is replaced with the final filepath.

For this reason, plugins like `postcss-url` don't work. Parcel 2 will be able to do this natively with a named pipeline (without `postcss-url`).

**Comment by jonka-blip** [comment]
postcss-url offers the ability to inline svg images from within *.css files. 
I could not accomplish this with Parcel 2. 
With Parcel 2 it is possible to inline images from .js via " import imageName from './path/to/image' ". 

I could get the desired behaviour for Parcel 2 with the help of "postcss-inline-svg" plugin though. But is this really necessary? If not, what is the syntax to import inlined images from within *.css files? 🙏
