### ISSUE TITLE
🙋 Tree Shaking

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#392]
We should add tree shaking to Parcel in production mode so we have smaller bundle sizes. Because this requires cross-file optimizations, it will be harder to do with Parcel's parallel architecture. This basically means that tree-shaking must be done in a Packager.

There are a few approaches we could take:

* Use [Rollup](http://rollupjs.org). I tried creating a RollupPackager to replace the current JSPackager in production mode, which just runs everything through Rollup. This worked and was relatively simple to implement, but was extremely slow. e.g. a 3s build went to 15s. It also only really works well with ES6 modules, not CommonJS which is much more common (haha) still especially in Node modules.
* Use something like [common-shake](https://github.com/indutny/common-shake), which is a library for doing tree-shaking on CommonJS modules. I haven't tried it, but it looks neat and is a library rather than a full bundler.
* Implement something ourselves. Sounds like a lot of work, but we may be able to tune it specifically for Parcel's architecture, e.g. doing some work in the Asset workers, and some in the Packager.

Goals we should aim for:

* Support ES6 modules
* Support CommonJS modules
* Eliminate the module wrappers/runtime that JSPackager uses as much as possible by e.g. concatenating modules like Rollup does (scope hoisting)
* Be relatively fast still
* Support something like webpack 4's `sideEffects: false` [option](https://github.com/webpack/webpack/tree/next/examples/side-effects) in `package.json` to enable us to not parse or include all code that is imported but not used.

Would love to hear some feedback on this, and if you have ideas on how we should implement this or features we should support please comment below! 😍

**Comment by lukeed** [comment]
I'm sorry to say, but since you're already constructing your own Asset & Bundle trees, it makes most sense (to me) that you create your own tree shaker. You have (nearly) all the info that you need to know, so why pass it off to another tool which is going to reconstruct another/similar tree, just to acquire the same info you already have. 🙃

**Comment by steveblue** [comment]
+1 custom. If Parcel can treeshake with multiple cores, it would be a huge advantage over the competition. There are fairly huge limitations with the tools you mentioned @devongovett. The only way to overcome those limitations would be a custom implementation. The multiple module patterns is a huge problem that needs to be resolved by someone.

**Comment by xywai1993** [comment]
source map  😄

**Comment by xuqiang521** [comment]
It is worth waiting 😍  fighting ~

**Comment by devongovett** [comment]
@davidnagli did you mean to close this?

**Comment by davidnagli** [comment]
Whoops sorry!!!!

**Comment by jackwen110200** [comment]
waiting special

**Comment by emmanuelchucks** [comment]
Can't wait to see this implemented in Parcel

**Comment by jsiebern** [comment]
+1, I'm trying Parcel for the first time & it is a great experience, the only issue I have is that my bundle sizes are **singnificantly** bigger than with Webpack (I'm talking 300kb no gzip production mode)

**Comment by Siyfion** [comment]
@jsiebern I know that this doesn't solve the root-issue, but perhaps think about doing some code-splitting? You could potentially provide a better experience to your end-users if you split the codebase and pre-fetched in the background after the initial load? Plus, when tree-shaking is implemented, it's still a decent thing to have done.

**Comment by jsiebern** [comment]
@Siyfion Unfortunately I'm shipping my code as part of a Wordpress plugin where every environment / url is totally different (and out of my control), code splitting won't work for me unfortunately

**Comment by ConneXNL** [comment]
One example of where tree shaking makes a lot of sense to work by default is when using a library like  lodash.

**Comment by Siyfion** [comment]
To be completely honest @ConneXNL, tree shaking makes sense for almost *every* library.

**Comment by mischnic** [comment]
Just for reference, there is a pull request: #731.

**Comment by HenrikJoreteg** [comment]
Any reason to not just use rollup? Also, if speed is a concern, one could potentially *just* do it when building for production. 

The lack of treeshaking is the only thing keeping me from using parcel for production projects.

**Comment by HenrikJoreteg** [comment]
Also, even if treeshaking only was applied for packages that have a ‘module’ field in the package.json that still seems like a big improvement to me.

**Comment by wzrdtales** [comment]
Does this issue respect css treeshaking as well already?

**Comment by devongovett** [comment]
See #1104, where scope hoisting is being discussed/implemented. You can check the [scope-hoist](https://github.com/parcel-bundler/parcel/compare/parcel-bundler:master...parcel-bundler:scope-hoist) branch to follow along with our progress!

**Comment by jbreckmckye** [comment]
@devongovett 

> Sure, I did get sending to rollup on build working at one point. It was really slow though. A 3s build to 15s is not acceptable IMO.

If it's a production build - maybe it is? It could be an optional parameter. I can accept a 15s build on CI, so long as my devzone builds remain lightning-quick.

**Comment by ozra** [comment]
Being used to compiling C++ with LTO opts, minutes wouldn't be a problem for production builds. It's only in dev where the speed really is needed imo. Tests take a whole lot more time to run through any way.

**Comment by xemasiv** [comment]
Goddamn I love parcel. - my mind was fucking blown when I saw it install the missing dependencies.
I'm using it for dev right now and I can just imagine the comfort it gives to js newcomers.

**Anyways ontopic** : I personally think using parcel for prod would be a big tradeoff though since not everyone's prod requirements are the same - like me, some people are optimization freaks - maybe parcel can **optionally** accept custom configs?

It's prod anyways, I sincerely think this is the right spot to introduce optional webpack-level configurability.

Oh parcel <3

**Comment by devongovett** [comment]
Tree shaking is now merged in v1.9.0! 🚀 

You can try it out with the `--experimental-scope-hoisting` flag. We'll enable it by default in a coming version.

Read more about how it works here: https://medium.com/@devongovett/parcel-v1-9-0-tree-shaking-2x-faster-watcher-and-more-87f2e1a70f79

**Comment by goyney** [comment]
```
$ parcel build --experimental-scope-hoisting --out-dir ../build/dist --public-url ./ ./index.html

  error: unknown option `--experimental-scope-hoisting'
```

**Comment by devongovett** [comment]
@goyney make sure you're running the latest version 😉

**Comment by goyney** [comment]
Definitely on 1.9.0.

**Comment by friday** [comment]
If you are on 1.9.0, the output of `parcel --version` should be `1.9.0`.

If it's not, then it's likely that you have installed 1.9.0 locally for the repo, but are running the command with a global installation of parcel from earlier. Try adding `npx` before your command to use the local version.

**Comment by goyney** [comment]
```
mirigoyen@mirigoyen-mac:~/Git/projectname$ ./node_modules/.bin/parcel --version
1.9.0
mirigoyen@mirigoyen-mac:~/Git/projectname$ ./node_modules/.bin/parcel --experimental-scope-hoisting --out-dir ../build/dist --public-url ./ ./index.html

  error: unknown option `--experimental-scope-hoisting'
```

What else can I provide to help troubleshoot?

**Comment by goyney** [comment]
Stupid me, I left out the word `build`. :( Carry on.

**Comment by kimamula** [comment]
It seems Parcel 1.9.0 only accepts `false` for the `sideEffects` option.
Are you planning to support specifying an array of file names for the `sideEffects` option as webpack does?
