### ISSUE TITLE
npm does not install v2

### ISSUE THREAD

**Issue by K-Thompson** [parcel-bundler/parcel#3921]
npm install -g parcel-bundler

install parcel-bundler@1.12.4 and not v2.x.x

I understand that yarn might install v2, but yarn and npm should not be co-mingled on a project, per 

>warning package-lock.json found. Your project contains lock files generated by tools
>other than Yarn. It is advised not to mix package managers in order to avoid resolution 
>inconsistencies caused by unsynchronized lock files. To clear this warning, remove
>package-lock.json.

**Comment by talentlessguy** [comment]
What does this issue mean?

* Parcel already uses the current pm in a current directory

* To install v2 version of Parcel, use `@beta` version, e.g. `yarn add -D parcel-bundler`

**Comment by mischnic** [comment]
> To install v2 version of Parcel ...

... use the `@next` version, e.g. `yarn add -D parcel-bundler@next` 😉

**Comment by K-Thompson** [comment]
@mischnic  `@next` is not recognized.

From PowerShell terminal on Windows 10 client.

>PS C:\wwwroot\loancalc> npm install parcel-bundler@next -g  
>npm ERR! code ETARGET
>npm ERR! notarget No matching version found for parcel-bundler@next.
>npm ERR! notarget In most cases you or one of your dependencies are requesting       
>npm ERR! notarget a package version that doesn't exist.

@talentlessguy 

`@beta`, seems to install (using NPM), with lots of errors. 

>PS C:\wwwroot\loancalc> npm install parcel-bundler@beta -g
>npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
>npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.

But why install a beta?  I don't see where what's hosted here is marked as a beta version?

node v12.13.1
npm v6.12.1

**Comment by K-Thompson** [comment]
I guess my question is, isn't the current stable version v2.x.x?

And if so, shouldn't

`npm install -g parcel-bundler`

install if, and not version 1.12.4?

**Comment by mischnic** [comment]
2.x.x isn't stable yet.

I'm sorry, it's `parcel@next`

**Comment by talentlessguy** [comment]
> > To install v2 version of Parcel ...
> 
> ... use the `@next` version, e.g. `yarn add -D parcel@next`

uh sorry my bad

**Comment by guawme** [comment]
npm install --save-dev parcel@next

**Comment by Somesh001yt** [comment]
it still gives me an error with npm i parcel@next -D what should I do
