### ISSUE TITLE
preact/compat doesn't reload browser on file change on Parcel 2 

### ISSUE THREAD

**Issue by talentlessguy** [parcel-bundler/parcel#3923]
# 🐛 bug report

When I tried to run a dev server on `parcel@next` I didn't see the browser updating on file changes (which is out-of-the-box behaviour of Parcel v1)

Parcel v1 works absolutely fine and reload happens

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
parcel index.html -p 3000
```

or 

```js
parcel serve index.html -p 3000
```

## 🤔 Expected Behavior

Dev server would reload my page

## 😯 Current Behavior

Currently the browser doesn't reload but WebSocket is being sent (I see `console clear` message flickering when I update file)

## 💁 Possible Solution

Write custom config maybe? I'm not sure which one but I expect this to be working out of the box

## 🔦 Context

This issue affected me after starting a dev server on Parcel 2.

I'm writing an app with Preact, Emotion and Rebass.

## 💻 Code Sample

Put this into package.json:

```
"alias": {
    "react": "preact/compat",
    "react-dom": "preact/compat"
  }
```

Then write this:
```
import React from 'react'
import { render } from 'react-dom'

render(<h1>Hello World</h1>, document.getElementById('app')
```

And try to change component's contents. Nothing will change.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | 13.2
| npm/Yarn         | 1.19.2
| Operating System | Linux 5.14

**Comment by talentlessguy** [comment]
I have a theory that Parcel 2 tries to use React refresh but it is preact so refresh doesn't happen

**Comment by DeMoorJasper** [comment]
@talentlessguy possibly, react refresh is part of the default config and you are using react in the code so it probably detects it as react.

You could use a custom parcel config. Or maybe react-refresh shouldn't be part of the default config as it's not really a standard thing.

**Comment by talentlessguy** [comment]
@DeMoorJasper could you please show a config to disable react refresh?

Also I found [this issue](https://github.com/preactjs/preact/issues/2184) on Preact repo so I think there might be a fix, but I still would like to use Preact with aliases to React

**Comment by DeMoorJasper** [comment]
@talentlessguy something like this?

```JSON
{
  "bundler": "@parcel/bundler-default",
  "transforms": {
    "types:*.{ts,tsx}": ["@parcel/transformer-typescript-types"],
    "bundle-text:*": ["@parcel/transformer-inline-string", "..."],
    "data-url:*": ["@parcel/transformer-inline-string", "..."],
    "*.{js,mjs,jsm,jsx,es6,ts,tsx}": [
      "@parcel/transformer-babel",
      "@parcel/transformer-js"
    ],
    "*.{json,json5}": ["@parcel/transformer-json"],
    "*.toml": ["@parcel/transformer-toml"],
    "*.yaml": ["@parcel/transformer-yaml"],
    "*.{gql,graphql}": ["@parcel/transformer-graphql"],
    "*.{styl,stylus}": ["@parcel/transformer-stylus"],
    "*.{sass,scss}": ["@parcel/transformer-sass"],
    "*.less": ["@parcel/transformer-less"],
    "*.css": ["@parcel/transformer-postcss", "@parcel/transformer-css"],
    "*.sss": ["@parcel/transformer-sugarss"],
    "*.{htm,html}": [
      "@parcel/transformer-posthtml",
      "@parcel/transformer-html"
    ],
    "*.pug": ["@parcel/transformer-pug"],
    "*.coffee": ["@parcel/transformer-coffeescript"],
    "*": ["@parcel/transformer-raw"]
  },
  "namers": ["@parcel/namer-default"],
  "runtimes": {
    "browser": [
      "@parcel/runtime-js",
      "@parcel/runtime-browser-hmr"
    ],
    "node": ["@parcel/runtime-js"]
  },
  "optimizers": {
    "data-url:*": ["...", "@parcel/optimizer-data-url"],
    "*.css": ["@parcel/optimizer-cssnano"],
    "*.js": ["@parcel/optimizer-terser"],
    "*.html": ["@parcel/optimizer-htmlnano"]
  },
  "packagers": {
    "*.html": "@parcel/packager-html",
    "*.css": "@parcel/packager-css",
    "*.js": "@parcel/packager-js",
    "*.ts": "@parcel/packager-ts",
    "*": "@parcel/packager-raw"
  },
  "resolvers": ["@parcel/resolver-default"],
  "reporters": [
    "@parcel/reporter-cli",
    "@parcel/reporter-dev-server",
    "@parcel/reporter-hmr-server"
  ]
}
```

**Comment by mischnic** [comment]
I can't reproduce this (anymore)

**Comment by talentlessguy** [comment]
@mischnic because now it works (I guess someone made a fix in preact or parcel), closing the issue

**Comment by willybrauner** [comment]
@talentlessguy HMR works with your configuration? I got the same issue with these packages:

```json
  "dependencies": {
    "preact": "^10.5.15",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@parcel/reporter-bundle-analyzer": "^2.0.0",
    "@parcel/transformer-inline-string": "^2.0.0",
    "@parcel/transformer-less": "^2.0.0",
    "parcel": "^2.0.0",
    "typescript": "^4.4.4"
  },
  "alias": {
    "react": "preact/compat",
    "react-dom": "preact/compat"
  }
```
