### ISSUE TITLE
ReferenceError when building with minification and scope hoisting

### ISSUE THREAD

**Issue by regiontog** [parcel-bundler/parcel#3932]
# 🐛 bug report

For certain targets parcel outputs code with references to bindings that don't exist or have a different name. This causes a ReferenceError at runtime. This output only occurs when running a 'build' with both minification and scope hoisting enabled.

I have looked into this and I found that `mangeScope` tries to rename a binding to a class but it does not rename all references to the class.

## 🎛 Configuration (.babelrc, package.json, cli command)

https://github.com/regiontog/parcel2-bug

## 🤔 Expected Behavior

Code provided in minimal project above should run without a ReferenceError. 

## 😯 Current Behavior

```
ReferenceError: $ab990cecfaab6ff29180e1961614b8cd$var$Item is not definedparcel2-bug.e18fda96.js:formatted:6
    get parcel2-bug.e18fda96.js:6
    <anonymous> parcel2-bug.e18fda96.js:10
    <anonymous> parcel2-bug.e18fda96.js:11
```

## 💁 Possible Solution

I think this is a bug in [babel](https://github.com/babel/babel/issues/10896). So a possible fix would involve upgrading babel when they push a fix. Another possibility would be to not rely on `scope.crawl()` from babel, as that seems to be where the bug is. But I don't know if that is a viable option, maybe in some cases it can be avoided?

## 💻 Code Sample

```js
class Item {
    constructor() { }

    get() {
        return new Item();
    }
}

const item = new Item(); // This is fine
item.get(); // But this causes a ReferenceError
```

## 🌍 Your Environment

```bash
npx envinfo
  System:
    OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 6.58 GB / 15.95 GB
    Container: Yes
    Shell: 5.4.2 - /bin/zsh
  Binaries:
    Node: 13.3.0 - ~/.nvm/versions/node/v13.3.0/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.1 - ~/.nvm/versions/node/v13.3.0/bin/npm
  npmPackages:
    core-js: ^3.5.0 => 3.5.0
    parcel: ^2.0.0-alpha.3.2 => 2.0.0-alpha.3.2
```

**Comment by mischnic** [comment]
Closing as duplicate
