### ISSUE TITLE
How do I prevent parcel changing script variable names (without --no-minify)?

### ISSUE THREAD

**Issue by nevernotsean** [parcel-bundler/parcel#3934]
# ❔ Question

How do I prevent parcel changing script variable names without --no-minify?

## 🔦 Context

I'm creating a Doubleclick banner with parcel. Doubleclick banners require a global variable called `clickTag`. Parcel is changing the name of this variable. Using `--no-minify` works, but my js/css files are then unminified.

## 💻 Code Sample

.htmlnanorc
`{
    "collapseAttributeWhitespace": false,
    "collapseBooleanAttributes": false,
    "collapseWhitespace": "conservative",
    "custom": [],
    "deduplicateAttributeValues": false,
    "mergeScripts": false,
    "mergeStyles": false,
    "removeUnusedCss": false,
    "minifyJs": false,
    "minifySvg": false,
    "removeEmptyAttributes": false,
    "removeRedundantAttributes": false,
    "removeComments": false
}`

index.html:
`<head>
    <script>
        var clickTag = "http://www.google.com";
    </script>
</head>`

after build
`<head>
    <script>
        var o = "http://www.google.com";
    </script>
</head>`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 12.13.0
| npm/Yarn         | npm 6.12.0
| Operating System | MacOSX Mojave

**Comment by mischnic** [comment]
`window.clickTag` would work

**Comment by nevernotsean** [comment]
Great answer, Although the HTML5 Validator (https://h5validator.appspot.com/) still gives my ZIP a CLICK_TAG_MISSING. I'm going to close this because I think the real issue is with the validator -- it is only looking for `var clickTag`, even though the banner ad works fine.

**Comment by welljs** [comment]
2024 and the same issue. Has there been a solution for this year?

**Comment by chrissound** [comment]
Running into the same issue (perhaps we can reopen the ticket?)... Flag to avoid this is now `--no-optimize`.
