### ISSUE TITLE
Will it support build finish callbacks?

### ISSUE THREAD

**Issue by Berkays** [parcel-bundler/parcel#3935]
# 🙋 feature request

It would be useful to have callbacks when parcel finished building on watch and serve modes. In a react ssr app, i can use this to restart the server after the client app is bundled succesfully.
 
## 🤔 Expected Behavior

onSuccess and onFailure callbacks can be passed to the CLI arguments (Much like tsc-watch package) to run necessary scripts.

## 😯 Current Behavior

Currently there is no way to know the build status of the bundler. Probably can be mitigated by some file watchers but requires extra packages and configuration of other parts. 

## 💁 Possible Solution

tsc-watch package currently does this pretty well. It provides onSuccess and onFailure callbacks as a CLI argument.

## 🔦 Context

As I mentioned, this feature can be useful where an other application relies on this build operation like a servers-side rendering application.

**Comment by mischnic** [comment]
Would invoking Parcel via the node API work for you?

**Comment by Berkays** [comment]
@mischnic What exactly do you mean by invoking with node API?

**Comment by DeMoorJasper** [comment]
@Berkays see the docs about the node.js api https://parceljs.org/api.html

**Comment by Berkays** [comment]
@DeMoorJasper This should work just fine thank you but isn't it more elegant to also have it as a CLI argument?

**Comment by DeMoorJasper** [comment]
@Berkays I personally think it’s a bit much to put it in the cli

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
