### ISSUE TITLE
API proxy opportunity 

### ISSUE THREAD

**Issue by egorovsa** [parcel-bundler/parcel#3939]
# 🙋 feature request

API proxy support with no additional packages like this https://www.npmjs.com/package/parcel-proxy-server

## 🤔 Expected Behavior

Have a look at webpack proxy behavior .

Proxying some URLs can be useful when you have a separate API backend development server and you want to send API requests on the same domain.

## 😯 Current Behavior

no possible to proxy API

## 💁 Possible Solution

as all the same packages are using http-proxy-middleware package

**Comment by mischnic** [comment]
This is implemented in Parcel 2 already: https://github.com/parcel-bundler/parcel/pull/3281
