### ISSUE TITLE
Basic TypeScript example not working `define is not defined`

### ISSUE THREAD

**Issue by alexeypetrushin** [parcel-bundler/parcel#394]
Create HTML page with TypeScript script

index.ts 

```
alert('hi')
```

It fails with `Uncaught ReferenceError: define is not defined`

### 🎛 Configuration (.babelrc, package.json, cli command)

No babel config or package.json

### 🌍 Your Environment

Mac OS, Node 9.3

parcel 1.3.1

### More

The content of the build https://gist.github.com/alexeypetrushin/2d3a2a5dabddc34afd0ba09ed02f14b4

There's no declaration for `define` function

**Comment by kingdaro** [comment]
Maybe try setting your tsconfig.json to use commonjs, as it looks like it's using AMD by default for some reason.
```json
{
  "compilerOptions": {
    "module": "commonjs"
  }
}
```

**Comment by devongovett** [comment]
We default the `module` option to commonjs [here](https://github.com/parcel-bundler/parcel/blob/master/src/assets/TypeScriptAsset.js#L11) but you can override it in your `tsconfig.json`. Any chance that's happening? I suppose we could enforce it to commonjs in parcel.

**Comment by kingdaro** [comment]
Yeah, that's why I thought it was weird. After some investigation, the simple example code provided doesn't output any AMD wrapping at all unless `require`, `export`, etc. are used. @alexeypetrushin What's your typescript version? And is this the _only_ file in the entire project? No `tsconfig` or anything?

**Comment by alexeypetrushin** [comment]
Hmm, I already killed the example, sorry don't have it anymore. There was `tsconfig.json`, I believe the module declaration was "AMD"

**Comment by strepkov** [comment]
I have the same problem. I have tsconfig file. It works perfectly with the module:umd option but unfortunately does not work with amd. But I still need to compile with amd for my project and now I see only one solution to does not specify the module option in tsconfig file and add it directly during compilation: tsc --module amd. I use jasmine-ts for testing and it adds automatically module type commonjs if it is not specified in tsconfig. Maybe it will be useful for someone :)
