### ISSUE TITLE
Parcel watch bundles properly but build does not

### ISSUE THREAD

**Issue by JeremyCraigMartinez** [parcel-bundler/parcel#3943]
# 🐛 bug report

When running `parcel build`, we are getting import issues saying that attributes of an import are undefined. For example, one file will be imported fine, but another will not be.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// babel.config.js
module.exports = {
  presets: [
    '@babel/preset-env',
    '@babel/preset-react',
    '@babel/preset-flow',
  ],
  plugins: [
    'add-module-exports',
    '@babel/plugin-syntax-dynamic-import',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-transform-modules-commonjs',
    '@babel/plugin-proposal-object-rest-spread',
    '@babel/plugin-transform-async-to-generator',
    '@babel/plugin-syntax-import-meta',
    '@babel/plugin-proposal-json-strings',
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    '@babel/plugin-proposal-function-sent',
    '@babel/plugin-proposal-export-namespace-from',
    '@babel/plugin-proposal-numeric-separator',
    '@babel/plugin-proposal-throw-expressions',
  ]
};
```

command: `parcel build --no-cache -d dist-client ./client/index.jsx ./client/main.css`

## 🤔 Expected Behavior

`parcel build --no-cache -d dist-client ./client/index.jsx ./client/main.css` should spit out directory that works properly in browser

```
$ tree dist-client/
dist-client/
├── index.js
└── main.css
```

## 😯 Current Behavior

index.js file fails in client claiming an import is missing a field. `_questions2` should export an object as that file has many `export`s (no `export default` though). Other imports in this same file work fine, however.

```javascript
Uncaught TypeError: (0 , _questions2.validateFields) is not a function
    at goToNextPage (index.js:52294)
    at HTMLUnknownElement.callCallback (index.js:4989)
    at Object.invokeGuardedCallbackDev (index.js:5038)
```

## 💁 Possible Solution

When I make a change to the file `parcel-bundler/src/Bundler.js` it works fine. It also works fine with `parcel watch`. It is just `parcel build` that causes this issue. The change I make to the file can be see below in the function `normalizeOptions`. The line changes are hardcoding `watch` and `production` to false in the return object:

```javascript
/* from this */
production: isProduction,
/* to this */
production: false, // isProduction,
```
```javascript
/* from this */
watch: watch,
/* to this */
watch: false, // watch,
```

Entire surrounding blob seen below:
```javascript
...
  normalizeOptions(options) {
    const isProduction =
      options.production || process.env.NODE_ENV === 'production';
    const publicURL = options.publicUrl || options.publicURL || '/';
    const watch =
      typeof options.watch === 'boolean' ? options.watch : !isProduction;
    const target = options.target || 'browser';
    const hmr =
      target === 'node'
        ? false
        : typeof options.hmr === 'boolean'
        ? options.hmr
        : watch;
    const scopeHoist =
      options.scopeHoist !== undefined ? options.scopeHoist : false;
    return {
      production: false, // isProduction,
      outDir: Path.resolve(options.outDir || 'dist'),
      outFile: options.outFile || '',
      publicURL: publicURL,
      watch: false, // watch,
...
```

Not stating this is a viable solution, but this is what makes it work. Perhaps these two fields should be exposed via parameter `--watch=<boolean>` and `--production=<boolean>`

## 🔦 Context

This is preventing us from using Parcel as a bundler for production. Right now our workaround for the lower environments is to use `parcel watch` with some bash trickery

```bash
# clean up anything existing in the dist-client directory
rm -rf dist-client/*
# parcel watch and send to background
parcel watch --no-cache -d dist-client ./client/index.jsx ./client/main.css &
# loop until this file is bundled and spit out
while [ ! -f dist-client/index.js ]; do sleep 2; done
# once bundle is on the file system, kill the process
pkill -f 'parcel watch'
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.4|
| Node             |v10.16.1|
| npm/Yarn         |v6.12.1|
| Operating System |Linux|

**Comment by mischnic** [comment]
`NODE_ENV=development parcel build --no-minify ...` should be equivalent to `parcel watch`.

**Comment by JeremyCraigMartinez** [comment]
@mischnic this doesn't change anything. If you look at the code in `src/cli.js` in the parcel-bundler, `command.production` is being set to true regardless of the `NODE_ENV`

```javascript
...

async function bundle(main, command) {
  // Require bundler here so the help command is fast
  const Bundler = require('../');

  if (command.name() === 'watch') {
    command.watch = true;
  }

  if (command.name() === 'build') {
    command.production = true;
    process.env.NODE_ENV = process.env.NODE_ENV || 'production';
  } else {
    process.env.NODE_ENV = process.env.NODE_ENV || 'development';
  }

...

```

**Comment by ben8p** [comment]
@JeremyCraigMartinez did you find a proper fix?
I'm observing the exact same issue!

**Comment by tristan-f-r** [comment]
Same behavior is being observed from [this SO post](https://stackoverflow.com/questions/75236338/parcel-external-css-syncfusion-spreadsheet-present-in-watch-but-not-in-build) (#8795) - the bundle is also working in dev mode alongside with watch mode, just not with build mode.

EDIT: This was due to files being incorrectly marked as pure.
