### ISSUE TITLE
Parcel 2: '.env' named folder throws

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#3944]
# 🐛 bug report

Having a `.env` named folder at any level of the path of the package directory results in parcel throwing
```
[Error: EISDIR: illegal operation on a directory, read] {
  errno: -4068,
  code: 'EISDIR',
  syscall: 'read'
}
```

**Comment by mischnic** [comment]
Related code: https://github.com/parcel-bundler/parcel/blob/afa74132eebba15fb1e139e26d7cf74e509e898f/packages/core/core/src/loadDotEnv.js#L10-L51

**Comment by yazfield** [comment]
Hi, I'd like to take this issue.
