### ISSUE TITLE
How to get optimized Elm code during development?

### ISSUE THREAD

**Issue by jjant** [parcel-bundler/parcel#3951]
# ❔ Question

I currently run `npx parcel src/index.html` to get my Elm app up and running, I'd like to have the code be compiled with the `--optimize` flag passed to the compiler (some of the stuff is perf heavy and needs it to have a decent experience). How could I achieve this?

## 🌍 Your Environment

Environment Info:
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - ~/.nix-profile/bin/yarn
    npm: 6.10.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Safari: 13.0.4
  npmPackages:
    parcel-bundler: ^1.10.0 => 1.12.4

**Comment by mischnic** [comment]
This isn't possible with `parcel src/index.html`, which builds without minification and `optimize` is only added with minification:
https://github.com/parcel-bundler/parcel/blob/6a6613f93734dd0711e0e8287b2330c49b2dd47e/packages/core/parcel-bundler/src/assets/ElmAsset.js#L42-L46

**Comment by jjant** [comment]
@mischnic Hey thanks for the reference. So the quickest way to get this working for me would be to edit those files under my parcel install, right? Thanks again!

**Comment by mischnic** [comment]
That would work (though a bit fragile)
