### ISSUE TITLE
Use tsc instead of babel

### ISSUE THREAD

**Issue by Pytal** [parcel-bundler/parcel#3952]
# ❔ Question

I'm having a peculiar issue when using [parcel-plugin-linaria](https://github.com/callstack/parcel-plugin-linaria) with React TypeScript.

Normally when parcel detects a .tsx file it uses tsc to compile to .js but when using this plugin it doesn't use the typescript package.

Instead it seems that parcel just uses babel so I have to install [@babel/preset-typescript](https://www.npmjs.com/package/@babel/preset-typescript) to transpile .tsx to .js files.

How do I get parcel to use tsc prior to initiating the use of [parcel-plugin-linaria](https://github.com/callstack/parcel-plugin-linaria)?

## 🔦 Context

I am trying to write css-in-js with [linaria](https://github.com/callstack/linaria) with a React TypeScript stack.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel               |   1.12.4
| Node                |  12.14.0
| npm/Yarn         |  6.13.4
| Operating System |  Windows 10

**Comment by DeMoorJasper** [comment]
This is how the linaria plugin is written. Parcel 1 uses tsc by default. Please open an issue in the parcel-plugin-linaria repo

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Pytal** [comment]
Looks like Parcel 2 allows more granular control I'm gonna try it out!
