### ISSUE TITLE
Parcel 2: Functions not defined in script tags

### ISSUE THREAD

**Issue by JonathanTroyer** [parcel-bundler/parcel#3954]
# 🐛 bug report

In Parcel 2, calling a function defined in a `<script>` tag from HTML (i.e. button `onclick`) leads to a reference error.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "parcel2-inline-script",
  "version": "1.0.0",
  "description": "Shows off a bug with inline scripts in Parcel 2",
  "main": "dist/index.html",
  "scripts": {
    "dev": "parcel src/index.html",
    "build": "parcel src/build index.html"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/JonathanTroyer/Parcel2-inline-script.git"
  },
  "author": "Jonathan Troyer",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/JonathanTroyer/Parcel2-inline-script/issues"
  },
  "homepage": "https://github.com/JonathanTroyer/Parcel2-inline-script#readme",
  "devDependencies": {
    "parcel": "^2.0.0-alpha.3.2"
  }
}
```

## 🤔 Expected Behavior

The function should be run, same as in Parcel

## 😯 Current Behavior

I get `Uncaught Reference Error: x is not defined`

## 💁 Possible Solution

¯\\\_(ツ)\_/¯  It may be related to https://github.com/parcel-bundler/parcel/issues/1618. See also https://github.com/parcel-bundler/parcel/issues/3301

## 🔦 Context

This is blocking me from transitioning an app from Parcel to Parcel 2, as several pages use script tags on the page.

## 💻 Code Sample

[Demo repo](https://github.com/JonathanTroyer/Parcel2-inline-script)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.
| Node             | 12.13.0
| npm/Yarn         | npm 6.12.0
| Operating System | Windows 10 Pro 1909 build 18363.535

**Comment by mischnic** [comment]
A workaround:
```js
window.test = function ....
```

**Comment by BenedictLang** [comment]
Got this error too, in Parcel 1, the function names have been minified but not the names in the onclick calls. In Parcel 2 at least this bug is fixed, but now you need the `window.functionName = functionName(){}`, otherwise the script tag will be just empty after bundeling as it is not bound to the HTML doc. Still I have the issue, that my function can not be accessed if defined in an imported file. like `<script type="module" src="./index.js" defer></script>`

**Comment by mischnic** [comment]
This should work now with a non-module ("classic") script: https://parceljs.org/languages/javascript/#classic-scripts
