### ISSUE TITLE
Outputting css and js assets when transforming css-in-js

### ISSUE THREAD

**Issue by Pytal** [parcel-bundler/parcel#3956]
How do you return both css and js assets in a transformer plugin for Parcel 2?

**Comment by mischnic** [comment]
You ... return them in the transform method, e.g:
https://github.com/parcel-bundler/parcel/blob/6a6613f93734dd0711e0e8287b2330c49b2dd47e/packages/transformers/html/src/HTMLTransformer.js#L26-L30

https://github.com/parcel-bundler/parcel/blob/6a6613f93734dd0711e0e8287b2330c49b2dd47e/packages/transformers/html/src/inline.js#L92-L110

**Comment by Pytal** [comment]
When I return css and js parcel gives the error: `HTML bundles must only contain one asset`?

**Comment by Pytal** [comment]
I saw [a TODO in the default namer](https://github.com/parcel-bundler/parcel/blob/e2ea84373758ef22da979bc7abaf9b8ca29a1f59/packages/namers/default/src/DefaultNamer.js#L17-L19) is this related?
