### ISSUE TITLE
Babel macros with typescript

### ISSUE THREAD

**Issue by onursagir** [parcel-bundler/parcel#3957]
# 🐛 bug report
Babel macros don't seem to work in TypeScript file, however it does work in plain JS 

## 🎛 Configuration (.babelrc, package.json, cli command)
```js
// index.js
import styled from 'styled-components/macro'

console.log(styled.p) // templateFunction() { }
```

```js
// index.ts
import styled from 'styled-components/macro'

console.log(styled.p) // undefined
```

```js
// .babelrc
{
  "plugins": ["babel-plugin-macros"]
}
```

## 🤔 Expected Behavior
The styled.p should be a function

## 😯 Current Behavior
The styled.p is undefined

## 🔦 Context
It prevents me from using macros

## 💻 Code Sample
[codesandbox](https://codesandbox.io/s/interesting-lederberg-jxdgl)
Check console tab
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.12.4
| Node             | v12.1.0
| npm/Yarn         | 1.19.1
| Operating System | MacOS Mojave (10.14.6)

**Comment by DeMoorJasper** [comment]
Should be fixed in parcel 2, we use tsc in Parcel 1 and it probably strips away some stuff you might need? Not entirely sure how the macro works and what exactly tsc makes of your code

**Comment by onursagir** [comment]
@DeMoorJasper Just checked Parcel 2 and it seems it's still there, I'm unfamiliar with the Parcel codebase but I think you need to run the .ts(x) files trough Babel as-well

**Comment by DeMoorJasper** [comment]
That’s what parcel 2 does by default strange that it doesn’t work

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by onursagir** [comment]
@DeMoorJasper maybe I'm implementing it wrong but I made a [code sandbox](https://codesandbox.io/s/festive-gauss-nddiu)

**Comment by DeMoorJasper** [comment]
@onursagir couldn't get it working in codesandbox as it kept crashing for me but when running it locally it worked fine if there's a correct `.babelrc` file.

```JSON
{
  "plugins": [
    "babel-plugin-macros"
  ],
  "presets": [
    "@babel/preset-typescript",
    "@babel/preset-react",
    "@babel/preset-env"
  ]
}
```
