### ISSUE TITLE
Cannot read property getAsset of undefined

### ISSUE THREAD

**Issue by vipinsingh211** [parcel-bundler/parcel#396]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
🐛

### 🎛 Configuration (package.json)

package.json
```js
{
  "name": "scoreboard-ui",
  "version": "1.0.0",
  "description": "...",
  "main": "index.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "",
  "dependencies": {
    "angular": "^1.6.4",
    "angular-cookies": "^1.6.4",
    "angular-route": "^1.6.4",
    "bootstrap": "^3.3.7",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "lodash": "^4.17.4"
  }
}
```

### 😯 Current Behavior

Trying to build my project written in Angular.js. But getting below error:

<img width="322" alt="capture4" src="https://user-images.githubusercontent.com/16261219/34330201-f7ca46f0-e910-11e7-9d8b-02f444555c03.PNG">

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.3.1 |
| Node             | 6.11.0 |
| npm/Yarn         | 3.10.10
| Operating System | Windows 10 |

**Comment by d4rkr00t** [comment]
Oh, it's an Out of Memory issue. Is that an open source project? I would love to experiment with it :)

**Comment by brandon93s** [comment]
Hello @vipinsingh211, 

Do you have a test repo we can take a look at that reproduces this issue?

**Comment by vipinsingh211** [comment]
Hi,

Here is the [bitbucket link to the project](https://bitbucket.org/vipinsingh211/scoreboard/admin).

**Comment by vipinsingh211** [comment]
Were you able to reproduce the issue?

**Comment by jichangee** [comment]
npm uninstall -g typescript

**Comment by vipinsingh211** [comment]
@jichangee Are you suggesting me reinstall typescript and try again?

**Comment by jichangee** [comment]
You can try.
if you use npm before

**Comment by jichangee** [comment]
I have a

**Comment by jichangee** [comment]
Yes.
I have a similar situation with you.
I use yarn to reinstall typescript.

**Comment by leoyoung07** [comment]
I met the same issue. Using local typescript (`npm install -D typescript`) instead of global typescript solved the problem.

**Comment by DeMoorJasper** [comment]
Are u still able to reproduce this in the latest master branch?

**Comment by pengliheng** [comment]
i also has  same problem , how can i solve it?????????????

**Comment by dridgely** [comment]
I'm getting the same error with parcel 1.5.1 running in a node:8-alpine docker container. If I run against the same project on my host machine the build succeeds without issue.

<img width="594" alt="screen shot 2018-02-15 at 6 54 27 pm" src="https://user-images.githubusercontent.com/1350241/36290366-0eb7eff8-1282-11e8-9e7c-8e98fd9ed5ae.png">

**Comment by leafiy** [comment]
still having the same issue
But the strange thing is its happens in the modules I'm not included to my project

**Comment by mischnic** [comment]
Does someone still have this issue and can provide a instruction to reproduce?
