### ISSUE TITLE
Parcel 2: CLI is sometimes inconsistent with build state

### ISSUE THREAD

**Issue by lbogdan** [parcel-bundler/parcel#3961]
# 🐛 bug report

CLI is sometimes inconsistent with build state.

## 🤔 Expected Behavior

CLI is consistent with build state at all times.

## 😯 Current Behavior

Sometimes (rarely on first build, but very often on rebuilds) the CLI output is inconsistent with the build status, permanently showing a spinner with "Optimizing file..." after the build succeeds:

![image](https://user-images.githubusercontent.com/2083930/71771305-84771d80-2f41-11ea-86d9-4c2742b77d03.png)

## 💁 Possible Solution

Investigating this, I found the root cause to be the throttled (delayed) dispatch of `buildProgress` events

https://github.com/parcel-bundler/parcel/blob/ddb253e6ce00a1709131519c349f892322b53526/packages/reporters/cli/src/UI.js#L44-L53

causing events to be dispatched out-of-order and get into an inconsistent state, because `buildProgress` events will be dispatched **after** the `buildSuccess` one.

Is there any particular reason for that throttling?

If no, I tested removing it - fixes the issue.

If yes, I tested delaying the dispatch of `buildSuccess` / `buildFailure` events with 200ms (> the throttling interval of 100ms) - fixes the issue.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2 branch |

**Comment by DeMoorJasper** [comment]
This is a known issue that we've recently discovered as well, related to throttling as you also discovered.

This was introduced to speedup processing on the main thread and use less processing power for the cli. There's probably better solutions to this like using a seperate worker for the reporters...

**Comment by lbogdan** [comment]
Would it make sense to create a PR with the delayed dispatch of `buildSuccess` / `buildFailure`?

**Comment by DeMoorJasper** [comment]
@lbogdan I think delaying it with 100ms should also work, basically throttling all events, but yeah that would be the fastest way to fix it afaik.

**Comment by lbogdan** [comment]
I tried with 100, but it was flaky (probably because of a race condition in how timeout handlers are queued / processed?) so I said 200 is a safer / the safest bet. 🙂

OK then, I'll go ahead and create a PR.
