### ISSUE TITLE
Parcel 2: @parcel/watcher is missing in v2 branch

### ISSUE THREAD

**Issue by fengzilong** [parcel-bundler/parcel#3962]
# ❔ Question

source code of @parcel/watcher is missing in v2 branch, but used in some package like

https://github.com/parcel-bundler/parcel/blob/e2ea84373758ef22da979bc7abaf9b8ca29a1f59/packages/core/fs/src/NodeFS.js#L15

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by DeMoorJasper** [comment]
The parcel watcher for v2 is written in C++ therefore it makes CI/CD in combination with the monorepo a bit complex and we moved it to a seperate repo: https://github.com/parcel-bundler/watcher

**Comment by fengzilong** [comment]
Thanks for explanation 😀
