### ISSUE TITLE
Compile JS without requires

### ISSUE THREAD

**Issue by maximal** [parcel-bundler/parcel#3963]
I’m using `2.0.0-alpha.3.2` and I wonder how can I build JS file without `require()` calls in it?

If I call `parcel build index.html` then I get it right. But due to my current project structure I need to have `parcel build app.js` (in order to have constant minified JS file name). But in this case, it compiles unusable for browser execution (has `require()` calls inside).

**Comment by mischnic** [comment]
Please provide your package.json.

**Comment by maximal** [comment]
```json
{
	"name": "sijeko-test",
	"version": "2.0",
	"description": "Test frontend",
	"author": "Sijeko",
	"license": "ISC",
	"private": true,
	"dependencies": {
		"autosize": "^4.0.2",
		"jquery": "^3.4.1",
		"popper.js": "^1.15.0"
	},
	"devDependencies": {
		"eslint": "^6.6.0",
		"parcel": "^2.0.0-alpha.3.2",
		"parcel-plugin-externals": "^0.2.0",
		"sass": "^1.24.0",
		"typescript": "^3.0.0"
	},

	"browser": "web/dist/app.js",
	"main": "web/dist/app.js",
	"source": "frontend/js/app.js",
	"browserslist": [
		"> 1%",
		"not dead"
	],
	"externals": {
		"jquery": "jQuery",
		"bootstrap": true,
		"popper.js": true
	},
	"scripts": {
		"build": "parcel build frontend/js/app.js"
	}
}
```

**Comment by mischnic** [comment]
You need to remove these two lines:

> ```json
> 	"browser": "web/dist/app.js",
> 	"main": "web/dist/app.js",
> ```

<br>

> You have ~likely~ configured Parcel to run in library mode (not bundling imports).

**Comment by maximal** [comment]
Gonna try now. I add `main` because it is specified as mandatory in the readme.

**Comment by maximal** [comment]
Oh, seems like it’s working now. Thanks!!

Now, how can I set output `dist` directory path. I want it in `/web/dist` rather than in `/dist`.

**Comment by mischnic** [comment]
I think you need to put this into the package.json:
```json
"default": "web/dist/app.js"
```

**Comment by maximal** [comment]
@mischnic, this doesn’t help :-(

**Comment by mischnic** [comment]
Sorry, add this:
```json
"default": "web/dist/app.js",
"targets": { "default": {} }
```

**Comment by ricardobeat** [comment]
Having the same issue here. The moment I add `targets` to package.json it starts compiling to commonjs require() calls. I have none of main, default, or other extra fields in package.json.

.babelrc:

```
{
  "presets": [
    ["@babel/preset-react"],
    ["@babel/preset-typescript"]
  ],
  "plugins": [
    "@babel/plugin-transform-runtime",
    "@babel/proposal-class-properties",
    "@babel/proposal-object-rest-spread",
    "inline-react-svg"
  ]
}
```

I'm also seeing a bunch of `@parcel/packager-js: Cannot read property 'constantViolations' and ` Error: Got unexpected undefined` depending on how I setup these...

**Comment by maximal** [comment]
Thanks, @mischnic!

```json
"default": "web/dist/app.js",
"targets": { "default": {} }
```
works fine.

@ricardobeat, thank you for you suggestion, I’ll try it in future; as of now, I would rather prefer not to have any additional files like `.babelrc`.

**Comment by ricardobeat** [comment]
That wasn't a suggestion though, as I still haven't got it working :D Still stuck trying to debug the `Error: Got unexpected undefined`.

**Comment by maximal** [comment]
This solution is useless if you guys want to have external modules (like external jQuery or Bootstrap) and browser builds simultaneously. As described in https://github.com/parcel-bundler/parcel/pull/4072#issuecomment-627428171
