### ISSUE TITLE
How can I set an environment variable?

### ISSUE THREAD

**Issue by chovy** [parcel-bundler/parcel#3965]
I want to take process.env.FOO and set that in window.FOO on the client side.

How can I do this?

**Comment by mischnic** [comment]
```html
<!-- index.html -->
<script src="index.js"></script>
```
```js
// index.js
window.FOO = process.env.FOO;
```
`FOO=abc parcel build index.html`

<br>

Unless you mean without doing it "manually", that isn't possible.

**Comment by chovy** [comment]
ok. i'm wondering if i can read in a .env file and put them in the build.

**Comment by mischnic** [comment]
(Parcel reads .env files automatically - https://parceljs.org/env.html)

**Comment by chovy** [comment]
ahh ok, so I just need to copy it from process.env to window in index.js?

**Comment by mischnic** [comment]
Yes
