### ISSUE TITLE
[bug🐛] live-reload is not working sometime

### ISSUE THREAD

**Issue by beenotung** [parcel-bundler/parcel#397]
Live reloading (the webpage) is not always working.

### 🎛 Configuration (.babelrc, package.json, cli command)
testing repo: https://github.com/beenotung/parcel-demo

### 🤔 Expected Behavior

When the content of index.ts is changed from
```
document.writeln("ready");
document.writeln("<br>live reload?");
```
to
```
document.writeln("ready");
document.writeln("<br>live reload? sometime :/");
```
The webpage should be refreshed to latest content.

### 😯 Current Behavior

The webpage content is not refreshed. Need to manually restart the parcel process, then refresh the browser to see the update.

### 💁 Possible Reason

Check if the file change detection misses some type of change.

### 🔦 Context

When the content of index.ts is changed from
```
document.writeln("ready");
```
to
```
document.writeln("ready");
document.writeln("<br>live reload?");
```
The webpage was refreshed to latest content.

For the buggy case, even when I add extra empty lines, the change is still not detected.
(The console say Built, not Building)

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.3.1
| Node             | v8.6.0
| npm         | 5.3.0
| yarn         | 1.3.2
| Operating System | Archlinux
| OS Kernel | 4.14.8-1-ARCH
| inotify-tools | 3.14-4

**Comment by DeMoorJasper** [comment]
Could this be a safe write issue? We’ve seen it on ubuntu before

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by beenotung** [comment]
I was using Intellij Idea, which is using safe write approach. Can we handle safe write or it's in definition problematic?

**Comment by DeMoorJasper** [comment]
It currently breaks the file watcher, we have a fix for it but we still have to figure out a way to detect this

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by beenotung** [comment]
If you don't handle safe write specially, do it counts as two operation?

1. delete old file, that is part of the dependency. Now one dependency is missing
2. create a new file, that is matching the dependency tree, then it should trigger a reload

Or it's working in another way?

**Comment by brandon93s** [comment]
See #211 and #382. Currently, you must disable "safe write" for file watching to function correctly.

**Comment by cbrake** [comment]
do you think this would be worth adding to the documentation for editors like Vim?  I spun my wheels for quite awhile on this ...
