### ISSUE TITLE
Parcel 2: Alias watch

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#3970]
# 🐛 bug report

Aliased packages aren't watched for changes

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | Arch Linux |
| Parcel Version |  2.0.0-alpha.3.2 |

**Comment by DeMoorJasper** [comment]
Which version of parcel?

**Comment by Banou26** [comment]
Probably related, Parcel doesn't watch for changes on yarn linked(`yarn add link:/path/to/local/folder`) packages either.

Pretty weird since this is using simlinks.

**Comment by mischnic** [comment]
> Pretty weird since this is using simlinks.

I think this is because of the watcher: https://github.com/parcel-bundler/watcher/pull/32

**Comment by dbismut** [comment]
In my experience it doesn't watch anything outside the root folder.

```js
import { useTweaks, makeFolder, makeSeparator, makeButton } from '../../src' // not watched
```

**Comment by devongovett** [comment]
Dup of #4332
