### ISSUE TITLE
Cleaning up after invoking `bundler.bundle()`?

### ISSUE THREAD

**Issue by dchambers** [parcel-bundler/parcel#3972]
# ❔ Question

Is there a way to clean up open file & network handles after bundling?

## 🔦 Context

I'm writing some Tape unit tests that rely on Parser's programmatic API, and the tests don't terminate because open handles remain after invoking `bundler.bundle()`.

Using [`leaked-handles`](https://www.npmjs.com/package/leaked-handles) I see this:

```
no of handles 6

tcp stream {
  fd: 20,
  readable: false,
  writable: true,
  address: {},
  serverAddr: null
}

tcp stream {
  fd: 23,
  readable: false,
  writable: true,
  address: {},
  serverAddr: null
}

child process handle { pid: 25652, cmd: undefined, args: undefined }

child process handle { pid: 25653, cmd: undefined, args: undefined }

child process handle { pid: 25661, cmd: undefined, args: undefined }

child process handle { pid: 25662, cmd: undefined, args: undefined }
```

Thanks!

**Comment by mischnic** [comment]
This isn't an issue in our own test. How exactly are you invoking parcel?

**Comment by dchambers** [comment]
> This isn't an issue in our own test. How exactly are you invoking parcel?

@mischnic, you're right!

I was importing a bundle during module initialisation, like so:

```
import express from 'express'
import createParcelBundle from './create-parcel-bundle'

// THIS IS THE PROBLEM -----------> 
const clientBundlePromise = createParcelBundle(pwd('../client/index.ts'))

const server = express()
server.get('/bundle', async (_req, res) => {
  const clientBundle = await clientBundlePromise
  // more code here...
})

// more code here...

export default server
```

but the problem goes away if I delay bundle creation until the first time I need it, for example:

```
let clientBundle = null

server.get('/bundle', async (_req, res) => {
  if(!clientBundle) {
    // THIS FIXES THINGS -----------> 
    clientBundle = await createParcelBundle(pwd('../client/index.ts'))
  }

  // more code here...
})
```

I'm guessing that Parcel isn't fully initialised at module load, and performs some asynchronous tasks that it depends on happening before it's interacted with ... maybe?
