### ISSUE TITLE
Analog of webpack-node-externals

### ISSUE THREAD

**Issue by krutoo** [parcel-bundler/parcel#3973]
Hi. How can i declare list of packages for node.js target bundle to force add all items to bundle?

I mean behaviour like externals in webpack: https://webpack.js.org/configuration/externals/

```js
const nodeExternals = require('webpack-node-externals');

module.exports = {
  // ...
  target: 'node',
  externals: nodeExternals({
    whitelist: [/^react-.*/], // all packages starts with "react-" will be added in bundle
  })
  // ...
}
```

**Comment by mischnic** [comment]
This is not supported in Parcel 1.
With Parcel 2, you can set `includeNodeModules` in the package.json:
```json
{
  "default": "dist/index.js",
  "targets": {
    "default": {
      "includeNodeModules": ["react", "react-dom"]
    }
  }
}
```

Related: https://github.com/parcel-bundler/parcel/issues/3305, https://github.com/parcel-bundler/parcel/issues/144
