### ISSUE TITLE
using posthtml without options kills php tags

### ISSUE THREAD

**Issue by dannydulai** [parcel-bundler/parcel#3975]
in src/packagers/HTMLPackager.js, this code:

```js
  async addAsset(asset) {
    let html = asset.generated.html || '';

    // Find child bundles that have JS or CSS sibling bundles,
    // add them to the head so they are loaded immediately.
    let siblingBundles = Array.from(this.bundle.childBundles)
      .reduce((p, b) => p.concat([...b.siblingBundles.values()]), [])
      .filter(b => b.type === 'css' || b.type === 'js');

    if (siblingBundles.length > 0) {
      html = posthtml(
        this.insertSiblingBundles.bind(this, siblingBundles)
      ).process(html, {sync: true}).html;
    }

    await this.write(html);
  }
```

calls posthtml().process with a options `{sync: true}` and that causes it to strip out unknown directives.

do you mind if i load up the .posthtmlrc options and add sync: true to them and use that here? or any other suggestion?

My goal is to get php to not be clobbered by parcel's html asset handler

**Comment by DeMoorJasper** [comment]
Feel free to find a posthtml config that fixes this and pr it to the v2 branch

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mischnic** [comment]
```js
const posthtml = require('posthtml');

const html = `
<html>
 <head>
  <title>PHP-Test</title>
 </head>
 <body>
 <?php echo '<p>Hello</p>'; ?>
 </body>
</html>
`

const result = posthtml()
  .process(html, {
	sync: true,
	directives: [{name: '?php', start: '<', end: '>'}] }  // <----
  ).html

console.log(result);
```

**Comment by VladimirMikulic** [comment]
@mischnic thank you for the code example.
Could you please specify the equivelant **postHTML** config file to achieve this?

My current `.posthtmlrc` file looks like this but it doesn't seem
to be picked up by the Parcel:

```json
{
  "directives": [{"name": "?php", "start": "<", "end": ">"}] } 
}
```
