### ISSUE TITLE
How can I set a base url with multiple scripts that have different entry files?

### ISSUE THREAD

**Issue by michael-ottink** [parcel-bundler/parcel#3976]
I'm making a typescript project and and I want to set the base url so that I can do imports with paths that are relative to the src folder. My folder structure is as follows

    src
    -client
    --index.html
    --application.ts
    -server
    -shared

When I try to use the base url in my index.html

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Game</title>
    </head>
    <body>
        <canvas id="game-canvas"></canvas>
        <p>Client</p>
        <script src="~/client/ts/index.ts"></script>
    </body>
    </html>

And run the following script

    "watch-client": "parcel ./src/client/index.html --open --out-dir ./builds/development/public",
It will throw the following error

> Error: ENOENT: no such file or directory, open
> 'D:\Game\src\client\client\ts\index.ts'

it has client multiple times, why is this happening? It's almost as if it looks from the ./ that my script is compiling it from and that would be the client folder. So this would be no problem because I could just do ../ to get to my shared folder thus I changed the script in the index.html to ~/ts/index.ts and it works. But the index.ts imports an application in the same way and this works when I run the compiled build in the browser. So it's working. But now vscode throws the following error.

[https://i.stack.imgur.com/s8x8Y.png](url)

because vscode somehow thinks that it needs to be ~/client/ts/application.

[https://i.stack.imgur.com/hrS1Y.png](url)

But that throws an error in the command prompt when running the script. So how can I solve this error in vscode? The best thing would be if the path's can be relative to my src folder, but honestly, I wouldn't know how I could get that to work. This is what the parcel docs say

https://parceljs.org/typeScript.html#baseurl-and-paths

**tsconfig.json**

    {
          "compilerOptions": {
            /* Basic Options */
            "target": "ES6",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */
            "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
            "lib": ["DOM", "ES2018"],                             /* Specify library files to be included in the compilation. */
            "allowJs": false,                       /* Allow javascript files to be compiled. */
            "checkJs": false,                       /* Report errors in .js files. */
            "sourceMap": true,                     /* Generates corresponding '.map' file. */
            "removeComments": true,                /* Do not emit comments to output. */
            //"noEmit": false,                        /* Do not emit outputs. */
            "declaration": true,
            "baseUrl": "./src",
            "paths": {
              "~*": ["./*"]
            },
        
            /* Strict Type-Checking Options */
            "strict": true,                           /* Enable all strict type-checking options. */
            "noImplicitAny": true,                 /* Raise error on expressions and declarations with an implied 'any' type. */
            "strictNullChecks": true,              /* Enable strict null checks. */
            "strictFunctionTypes": true,           /* Enable strict checking of function types. */
            "strictBindCallApply": true,           /* Enable strict 'bind', 'call', and 'apply' methods on functions. */
            "strictPropertyInitialization": true,  /* Enable strict checking of property initialization in classes. */
            "noImplicitThis": true,                /* Raise error on 'this' expressions with an implied 'any' type. */
            "alwaysStrict": true,                  /* Parse in strict mode and emit "use strict" for each source file. */
        
            /* Additional Checks */
            "noUnusedLocals": true,                /* Report errors on unused locals. */
            "noUnusedParameters": true,            /* Report errors on unused parameters. */
            "noImplicitReturns": true,             /* Report error when not all code paths in function return a value. */
            "noFallthroughCasesInSwitch": true,    /* Report errors for fallthrough cases in switch statement. */
        
            /* Module Resolution Options */
            "moduleResolution": "node",            /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
            "typeRoots": ["node_modules/@types"],                       /* List of folders to include type definitions from. */
            "esModuleInterop": true,                  /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
            "forceConsistentCasingInFileNames": true,  /* Disallow inconsistently-cased references to the same file. */
            "experimentalDecorators": true
          },
          "include": ["src/**/*"],
        }

**Comment by mischnic** [comment]
> Error: ENOENT: no such file or directory, open 'D:\Game\src\client\client\ts\index.ts'

https://parceljs.org/module_resolution.html#~-tilde-paths:
> `~/foo` resolves foo relative to [...] the **entry root.**

> **entry root**: the directory of the entrypoint specified to Parcel, or the shared root (common parent directory) when multiple entrypoints are specified.

In your case, the entry root is apparently `D:\Game\src\client` (this is unintuitive and will be fixed in Parcel 2).

<br>

> But the index.ts imports an application in the same way and this works when I run the compiled build in the browser.

`paths: {"~*": ["./*"]}`  is relative to the `tsconfig` file, which is likely in the same folder as `src`?

**Comment by MikeOttinkHKU** [comment]
Yes my tsconfig is in the same folder as src. Is there any way that I can make imports relative to the src then with my project structure? And if not how would I make vscode understand the tilde target is correct so that it doesn't generate the error(because it won't generate one when compiling)?
