### ISSUE TITLE
Should building index.html in a nested directory grab assets from that directory

### ISSUE THREAD

**Issue by shivamMg** [parcel-bundler/parcel#3979]
# ❔ Question

Should building index.html in a nested directory grab assets from that directory

## 🔦 Context

I've the following directory structure:
```
.
├── css
│   └── styles.css
├── dir
│   └── index.html
└── index.html
```
`dir/index.html` contains ` <link href="/css/styles.css" rel="stylesheet">`. While building using `parcel build dir/index.html` I was hoping it picks `css` directory from the root. instead it fails with:
```
🚨  /tmp/tmp.95RU4CG4UQ/a/dir/css/styles.css:undefined:undefined: ENOENT: no such file or directory, open '/tmp/tmp.95RU4CG4UQ/a/dir/css/styles.css'
Error: ENOENT: no such file or directory, open '/tmp/tmp.95RU4CG4UQ/a/dir/css/styles.css'
```

I think when using `/css/styles.css` it should pick up from the current working directory, and when using `css/styles.css` it should look on the same level as index.html. 

## 💻 Code Sample

The above directory structure + link in `dir/index.html` should suffice to reproduce the issue.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4 |
| Node             | v13.5.0 |
| npm/Yarn         | 1.13.0 |
| Operating System | Arch Linux (`uname -a`: Linux smg 5.4.7-arch1-1 #1 SMP PREEMPT Tue, 31 Dec 2019 17:20:16 +0000 x86_64 GNU/Linux)

**Comment by mischnic** [comment]
https://parceljs.org/module_resolution.html describes that syntax that you can use.

The entry root in your case is `dir` and `~` and `/` refer to the entry root.

**Comment by shivamMg** [comment]
> entry root: the directory of the entrypoint specified to Parcel, or the shared root (common parent directory) when multiple entrypoints are specified.

The latter helped me understand the problem. I wasn't passing the root index.html. `parcel build dir/index.html index.html` worked. Thanks.
