### ISSUE TITLE
`build` and `watch` generate different hashes for svg files

### ISSUE THREAD

**Issue by flexdinesh** [parcel-bundler/parcel#3982]
# 🐛 bug report

I am playing around with React + SSR setup in a monorepo with Parcel. I can see that when I run parcel with [build](https://parceljs.org/cli.html#build) in the client dir, a hash is generated for the svg file. Now when I run parcel with [build](https://parceljs.org/cli.html#build) from the server dir, same hash is generated. But when I run parcel with [watch](https://parceljs.org/cli.html#watch) in server dir, a different hash is generated for the svg.

The code can be found in this repo — [flexdinesh/react-ssr-parcel](https://github.com/flexdinesh/react-ssr-parcel)

The component that imports the svg is in client dir — [App.js in client](https://github.com/flexdinesh/react-ssr-parcel/blob/master/app/src/components/App.js)

Hash generated in both client and server when using parcel with `build` — `logo.94f27200.svg`

Hash generated in client and server when using parcel with `watch` is different. Because of this I couldn't use `watch` command and instead using nodemon to rebuild and restart the server.

I am still in early stages of understanding the tool. This might be something simple and I might possibly missing something in the setup/config. But I'd like to know nevertheless. The tool is amazing and I want to build a scaffolding tool for React + SSR off this.

**Comment by DeMoorJasper** [comment]
Wow did not expect no-one to have responded to this in half a year.

This is expected behaviour, build hashes are filecontent hashes to ensure you can cache these assets on a cdn forever pretty much but a lifetime of a year is probably plenty.

You will be able to define your own naming strategy in Parcel 2 to resolve this.
