### ISSUE TITLE
Weird error whie packaging html with custom svg tags

### ISSUE THREAD

**Issue by asm0dey** [parcel-bundler/parcel#3999]
# 🐛 bug report

## 🎛 Configuration (cli command)

```
parcel build index.html
```

## 🤔 Expected Behavior

Resulting version is built

## 😯 Current Behavior

```
🚨  /home/finkel/work_self/marp/java-python/index.html: Error in parsing SVG: Unexpected close tag
Line: 9
Column: 142
Char: >
error Command failed with exit code 1.
```

To a pity there is not enough diagnostic information to create minimal working sample. But HTML looks valid and works correctly.

## 🔦 Context

I'm attaching HTML which can't be built here  
[example.zip](https://github.com/parcel-bundler/parcel/files/4059528/example.zip)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4 |
| Node             | v13.5.0 |
| Operating System | Manjaro Linux 18.1.5 |

**Comment by asm0dey** [comment]
Still needs solution

**Comment by asm0dey** [comment]
Still interested

**Comment by mischnic** [comment]
I'm not sure what your usecase is. But I don't get such an error with Parcel 2. I did find another problem though: https://github.com/parcel-bundler/parcel/issues/5706
