### ISSUE TITLE
Folder Structure Bundling

### ISSUE THREAD

**Issue by Gizmo-Rishab** [parcel-bundler/parcel#4006]
# 🙋 feature request

Could it be possible for parcel to bundle all the files according to the folder structure beginning from where are file is
## 🤔 Expected Behavior

Lets say we have the file structure below
| - Src -|
|           | - Server.js (config file)
|           | - Public - |
|           |                 | - Index.html
|           |                 | - Styles.css
Can it be loaded as the above in the dist
## 😯 Current Behavior
This is the file structre in dist
| - Server.js (config file)
| - Index.html
| - Styles.css

All files are in the root itself
## 💁 Possible Solution

Use fs-extra manipulation to load them as is

**Comment by Gizmo-Rishab** [comment]
Can I use parcel 2 as of now

**Comment by DeMoorJasper** [comment]
@Gizmo-Rishab we're working very hard to get to a stable version asap, you can try it out

**Comment by Gizmo-Rishab** [comment]
How can I try it?

**Comment by DeMoorJasper** [comment]
@Gizmo-Rishab follow the steps in the readme https://github.com/parcel-bundler/parcel#getting-started

**Comment by Gizmo-Rishab** [comment]
So I should run the commands below right?
```bash
$ npm uninstall parcel-bundler
$ npm install --save-dev parcel@next
```

**Comment by DeMoorJasper** [comment]
Yes

**Comment by Gizmo-Rishab** [comment]
Is this normal
![image](https://user-images.githubusercontent.com/29125087/72623508-40394380-396b-11ea-89de-2adafb3a826c.png)

**Comment by DeMoorJasper** [comment]
Probably npm audit doesn't really work properly

**Comment by Gizmo-Rishab** [comment]
When I checked npm audit's logs, it showed a 196 error's of deprecated dependencies

**Comment by DeMoorJasper** [comment]
I wouldn't worry about it, it reports a LOT of false positives. Most security issues according to npm aren't a security issue at all as they apply to a piece of code which is never even being ran or a dos vulnerability that makes no sense in the context it is used.

**Comment by Gizmo-Rishab** [comment]
Ok

**Comment by VincentVToscano** [comment]
Has this feature been rolled into `2.0.0-rc.0`?
