### ISSUE TITLE
Add another extensions

### ISSUE THREAD

**Issue by vitorcamachoo** [parcel-bundler/parcel#4008]
# ❔ Question
How can I add more extensions to the compiler ? Example, giving the following files:
- example.web.ts
- example.native.ts

When import `import example from 'example'` it should choose `web` or `native` giving the current extension configuration.

**Comment by DeMoorJasper** [comment]
What version of parcel are you using?

**Comment by vitorcamachoo** [comment]
> What version of parcel are you using?
"parcel-bundler": "^1.12.4"
