### ISSUE TITLE
Import partial HTML

### ISSUE THREAD

**Issue by vladciobanu** [parcel-bundler/parcel#4012]
# ❔ Question

Is there a way to import partial HTML files into another HTML file?

## 🔦 Context

I am trying to refactor my HTML pages, but there's no dynamic content so there's no point in doing this at runtime, either on the server or client. I want to be able to do this at bundle time. I also do not need all of the extra features of something like `pug` or a full templating engine. I literally just need to be able to insert inline the contents of a file.

## 💻 Code Sample

*index.html*:
```html
<html>
<body>
%%import top.html.partial
</body>
</html>
```

*top.html.partial*:
```html
<h1>Hello, world</h1>
%%import whatever.html.partial
```

*whatever.html.partial*:
```html
<div>And I would love if it worked arbitrarily deep.</div>
```

I would expect that pointing parcel to `index.html` would generate an `index.html` like:
```html
<html>
<body>
<h1>Hello, world</h1>
<div>And I would love if it worked arbitrarily deep.</div>
</body>
</html>
```

**Comment by mischnic** [comment]
You could use a posthtml plugin such as https://github.com/posthtml/posthtml-import

**Comment by vladciobanu** [comment]
Right, that sounds reasonable, thank you.
