### ISSUE TITLE
How to use Vue 3 alpha with Parcel 2?

### ISSUE THREAD

**Issue by maximelebreton** [parcel-bundler/parcel#4016]
Hello!

Can we use **[Vue 3](https://github.com/vuejs/vue-next)** alpha with **Parcel 2**?
I can't make `.vue` files compiling.
Can you provide an example?

Thanks!

`Parcel 2.0.0-alpha.3.2`
`Vue 3.0.0-alpha.2
`

**Comment by DeMoorJasper** [comment]
Parcel 2 does not yet support Vue

**Comment by mischnic** [comment]
Closing as a duplicate. You might want to subscribe to that issue.
