### ISSUE TITLE
Using parcel as a runtime tool for http endpoints

### ISSUE THREAD

**Issue by SindreSvendby** [parcel-bundler/parcel#402]
🙋 feature request

Hi, wanted to discuss my idea, before implementing. You guys probably have some good inputs to it.

## Idea

`Deliver the best code representation  of the source code that fits the browsers , to parse the code the quickest and reduce time to  first meaningful paint ` 

or to rephrase 

 `only transpiled whats needed for the specific browser`

## Background

Most webapps today uses babel to transpile their file down to the syntax the oldest browser they have to support supports.

But you could serve 2  versions, one with es6 modules and one without -   Like the suggestion here:
https://www.contentful.com/blog/2017/04/04/es6-modules-support-lands-in-browsers-is-it-time-to-rethink-bundling/

But since we have a lot of browsers, and the feature set is different for most of them. And the browser vendors are  prioritizing different, we will never have feature equality between the browsers. at least in my my head that's utopia.

In the approach above they suggest really 2 versions. and then based on a flag (modules/nomodules), we served two different representation of the source code.

## Solution suggestion

parcel's entrypoint is an html file and not a js file and I really like that. When I was thinking it through, i realized that I think that to give the user/browser the things it needs is a _runtime_ task and not a buildtime task.

So want I want to do is create a express middleware that uses parcel and  connects to the _html representations of the endpoints_,  checks the browsers users agent header and combine the awesome work that is done from parcel, babel-preset-env and [six-speed](http://incaseofstairs.com/six-speed/ ) to give the users the optimal code for that user.

## Disadvantages / Problems

I see some problems:
 * why run time, could you not just do this build time for all browsers ?
 ** Yes, what is described above  could be done build time. But would result in increased build time.

 * More complexed build/runtime example.
 ** This is a very valid concern. For most webapps this feature is  maybe not that important.
 My hope Is that if this is done as a middleware where the complexity is hidden inside the library, then it would be simple for the user to
 use it. If the complexity added vs runtime performance added is a good trade off for your application, depends on the applications, the size of it,  and it's user.
 

## In the future

I think the approche where you connect in front of the endpoint, and do the transpiling step there based on what the browser need,
could be a way to move this away from the applications itself and think of this more of like infrastructure. There are of course some challenges around this,
but I think it's possible to overcome these. Just think if you could write the source code in esnext, and cloudflare/heroku/whatever had a option to transpile your code
and chunk it how ever they feel is best for the user.

If we left this to a provider that is in front of applications itself, normally a cache layer, then this could do a much better work then what the application
Let's say that all websites that used react, jquery, moment or another popular npm could share the cached version of these libs.

I think this would be a giant leap forward for our users.
But this is in the future, I'm just pointing why I think is the correct to think of transpiling and chunking of something is decided runtime.

I'm not aware that someone has implemented anything like this, even though there are some similar approaches that touches into this:

1. https://unpkg.com - if everyone started using unpkg instead of chunking up stuff in their own webapp,
the users would get a faster web experience duo to increased caching.
The problem here is that if only a apps are using unkg, then most likely it's not cached in advanced.
So to achieve this we need to get it over what we call a  critical mass...
This approach is also lacking the runtime transpiling, but this could be implemented on top of it.

2. Cloudflare's rocket loader is trying to achieve better performance for the users,
but right now it's limited to async loading, caching (via localstorage) and bundling of JS. But it looks like what CF want to do is to give better experience without touching your _application_,.
but _how_ things is loaded should be separate from _what_ is loaded.
So we can hope they want to go down this road with rocket loader or a version of it, that would be really interesting to see.

It would be great to get feedback on the idea, the suggestion solution (express middleware that uses parcel), and the rest of the "vision".

**Comment by brandon93s** [comment]
If the "compilation" is happening as a middleware when the user requests the app from your server (e.g. just-in-time transpilation), I can't imagine a scenario where the run-time benefits outweigh the transpilation delay. In most cases, we (the community) are still transpiling down to the lowest-common-denominator. The run-time overhead of this transpiled code is minimal and ensures no performance traps on new features. 

It's an interesting concept, nontheless. Some things to consider:
- Is there a middleware to feature-detect based on user-agent? Might be a fun package to build.
- Heavy server-side caching of builds, by user-agent, would be needed.
- User-Agents aren't 100% (i.e. spoofing, custom, etc.), what do you do when you can't detect?

Parcel actually already has a middleware (largely undocumented) which I'd encourage you to take a look at for a starting point:

https://github.com/parcel-bundler/parcel/blob/8f1f497945d4e5102c401e3036c4bc30fd692348/src/Server.js#L8-L57

At the end of the day though, this sounds like it belongs as an advanced plugin or a separate project that leverages Parcel for the bundling - not part of parcel itself. Excited to see what you come up with and for the benchmarks of run-time vs compile time performance gains!

**Comment by SindreSvendby** [comment]
Thanks for the feedback.

It's not something that should  be in the this repo, I agree, Just wanted some feedback on the idea :)

the middleware looks interesting, will explore the possibilities, thanks!

About your points to consider:
* a  `user-agent to feature` library  needs to be create, I'm not aware of something like this. 
But we have [ua-parser-js](https://github.com/faisalman/ua-parser-js), [browserlist](https://github.com/ai/browserslist) and [babel-preset-env](https://github.com/babel/babel/tree/master/packages/babel-preset-env) so this should just be pluming to make them talk to each other.

* caching - yes. we do not want users to experience the transpiling. modern cache solutions creates a hot cache so (most) users gets a cached version. We def want to do the same. make sure that +95% of the users  gets a  cache version

* unknow user-agent - My suggestion here is to fallback to  the oldest transpiled version you want to support,
the most important thing is that is works!
