### ISSUE TITLE
Live Web Server with ReasonML Hooks throwing error

### ISSUE THREAD

**Issue by DrYSG** [parcel-bundler/parcel#4024]
# ❔ Bug?

Been using parcel quite a while but this is my first try with ReasonML (React-Hooks theme). just tried the generic bsb -init foobar -theme reason-hooks

Parcel seems to bundle things fine (I.e. if I copy the <dist> folder to my web server, I can open index.html and all works fine. (http://localhost/folder/index.html

The issue is with 

```
Server running at http://localhost:1234 
√  Built in 1.55s.

```
When I go to localhost:1234 I get the following Error with Chrome when loading.

(note what It says is the contents of index.html (Or is it index.bs.b68b9b3.js) (BTW: the JS file is just fine what it Chrome is showing is the contents of the index.html

![image](https://user-images.githubusercontent.com/2865368/72747638-3b4edc80-3b83-11ea-8705-316bab2d5dd4.png)

This is the content of the /dist folder
![image](https://user-images.githubusercontent.com/2865368/72747679-5588ba80-3b83-11ea-8665-93a21f88f81b.png)

## 🔦 Context
This is the npm script I use to build:

```
    "pack": "node_modules/.bin/parcel src/index.html --public-url ./",

```

## 💻 Index.js located at src/index.html

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Web Dashboard</title>
</head>

<body>
    <script>
        // stub a variable ReactJS checks. ReactJS assumes you're using a bundler, NodeJS or similar system that provides it the `process.env.NODE_ENV` variable.
        window.process = {
            env: {
                NODE_ENV: 'development'
            }
        };
    </script>

    <script src="Index.bs.js"></script>
</body>

</html>
```

## 🌍 Your Environment

windows 10
  "dependencies": {
    "react": "^16.8.1",
    "react-dom": "^16.8.1",
    "reason-react": ">=0.7.0"
  },
  "devDependencies": {
    "bs-platform": "^7.0.1",
    "moduleserve": "^0.9.0",
    "parcel-bundler": "^1.12.4"

**Comment by DrYSG** [comment]
I am not sure this is a question, or a bug anymore. I uses bsb with the vanilla -theme hooks (react) and when I use

```
./node_modules/.bin/parcel build parcel.html --public-url .
```
I have a perfectly functional bundle. But when I use
```
./node_modules/.bin/parcel parcel.html --public-url .
```

I get the error about the document (seems to be something in the live server).

**Comment by DeMoorJasper** [comment]
@DrYSG could you create a repo with a basic setup to reproduce this?

**Comment by DrYSG** [comment]
I think I am going to call this OBE. Our project is switching from ReasonML to RUST, so I will not have any more time to pursue reasonml with parcel.
