### ISSUE TITLE
Question about node native path resolving

### ISSUE THREAD

**Issue by glani** [parcel-bundler/parcel#4030]
# ❔ Question
Is it possible to adapt path for native modules (I mean something like alias) ?

## 🔦 Context
I have tried to use parcel for AWS lambda.

 parcel build src/process-media.ts --target=node --global handler -o process-media.js --bundle-node-modules --no-source-maps

### Result folder contains:
opencv4nodejs.6533dc6a.node
process-media.js

### In the source file:
> cv =require('../build/Release/opencv4nodejs.node')

Finally in the result file I got **require('/opencv4nodejs6533dc6a.node')**. This could be totally fine if it has been used in electron. However for AWS it is not suitable to point to the root folder.

Changing the string to **require('./opencv4nodejs6533dc6a.node')** works perfectly on AWS.

Probably some workaround exists ?

Right now I am doing it manually replacing path to the correct one. But this is additional step in the build process.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.4
| Node             | 10.x , 12.x
| npm/Yarn         | npm
| Operating System | Ubuntu18

**Comment by mischnic** [comment]
Maybe `--public-url ./` ?

**Comment by glani** [comment]
> Maybe `--public-url ./` ?

No it does not work
instead of module.exports="/opencv4nodejs.6533dc6a.node"; I got
module.exports="opencv4nodejs.6533dc6a.node";

but the line from original library 

> let cv = require('../build/Release/opencv4nodejs.node');

remains the same 

> let s=require("../build/Release/opencv4nodejs.node");s=r(s=e(s)),module.exports=s;
},{"./promisify":"lr6S","./src":"Z4j2","../build/Release/opencv4nodejs.node":"nSBh"}],"P6sZ"

Changing 
**let s=require("../build/Release/opencv4nodejs.node");** 
to 
**let s=require("./opencv4nodejs.6533dc6a.node");**
 helps.
