### ISSUE TITLE
CORS issue loading web app in microsoft edge using hmr

### ISSUE THREAD

**Issue by smooney123** [parcel-bundler/parcel#4032]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

Bug Report

I am trying to run my app in microsoft edge and getting the following error

SEC7120: [CORS] The origin 'ms-appx-web://microsoft.microsoftedge' failed to allow a cross-origin font resource at 'ms-appx-web:///assets/Fonts/BrowserMDL.ttf#Browser MDL2 Assets'.

I cannot use https and need to configure a custom host

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "openlayers",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "parcel index.html --host development.landwebni.gov.uk --port 9095",
    "build": "parcel build --public-url . index.html"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@babel/core": "^7.8.3",
    "app-root-path": "^3.0.0",
    "authenticate": "^0.1.5",
    "babel-preset-es2015": "^6.24.1",
    "babel-upgrade": "^1.0.1",
    "commonjs": "0.0.1",
    "config": "^3.2.5",
    "core-js": "^3.6.4",
    "document-ready": "^2.0.2",
    "eazy-logger": "^3.0.2",
    "fs": "0.0.1-security",
    "jquery": "^3.4.1",
    "leaflet": "^1.6.0",
    "ol": "^6.1.1",
    "ol-contextmenu": "^4.0.0",
    "ol-hashed": "^2.0.0",
    "ol-layerswitcher": "^3.5.0",
    "proj4": "^2.6.0",
    "sidebar-v2": "^0.4.0",
    "simple-datatables": "^2.1.9",
    "simple-node-logger": "^18.12.24",
    "winston": "^3.2.1",
    "winston-daily-rotate-file": "^4.4.1"
  },
  "devDependencies": {
    "babel-preset-env": "^1.7.0",
    "parcel-bundler": "^1.12.4"
  },
  "description": ""
}

```

### 🤔 Expected Behavior

My web app should load correctly.

Allow a change of the default hostname --hmr-hostname

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
> Allow a change of the default hostname --hmr-hostname

That option does exist:
https://parceljs.org/cli.html#hmr-hostname

**Comment by smooney123** [comment]
It does exist, but the default is localhost. it does not set it to a custom host for example development.landwebni.gov.uk

**Comment by smooney123** [comment]
ideally something like parcel index.html --host development.landwebni.gov.uk --port 9095  --hmr-hostname development.landwebni.gov.uk --hmr-port 9095 - which may not be accepted

**Comment by mischnic** [comment]
I've just tried `parcel index.html --hmr-hostname development.landwebni.gov.uk --hmr-port 9096` and that does work as expected:
```
WebSocket connection to 'ws://development.landwebni.gov.uk:9096/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
```
```js
// ...

if ((!parent || !parent.isParcelRequire) && typeof WebSocket !== 'undefined') {
  var hostname = "development.landwebni.gov.uk" || location.hostname;
  var protocol = location.protocol === 'https:' ? 'wss' : 'ws';
  var ws = new WebSocket(protocol + '://' + hostname + ':' + "9096" + '/');

// ...
```

---

In Parcel 2, we already changed it so use a single port.

**Comment by smooney123** [comment]
![image](https://user-images.githubusercontent.com/5982529/73002913-a9520880-3dfc-11ea-902e-9d4279a0dc2e.png)

**Comment by smooney123** [comment]
it does not resolve

**Comment by smooney123** [comment]
it is already added to my hosts file

**Comment by mischnic** [comment]
I've added `127.0.0.1 development.landwebni.gov.uk` to my hosts file and it worked in Chrome.

**Comment by smooney123** [comment]
# Added by Docker Desktop
172.16.5.136 host.docker.internal
172.16.5.136 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
127.0.0.1 development.landwebni.gov.uk

**Comment by smooney123** [comment]
is the default localhost:1234?

**Comment by mischnic** [comment]
For the dev HTTP server: yes
For the hmr connection: `${current hostname}:${random}`

**Comment by smooney123** [comment]
do i need to upgrade parcel-bundler?

**Comment by smooney123** [comment]
how do i change http server default?

**Comment by mischnic** [comment]
`parcel index.html --host development.landwebni.gov.uk --port 9095 --hmr-hostname development.landwebni.gov.uk --hmr-port 9096` should work in your case. (use two different ports)

**Comment by smooney123** [comment]
it works fine in chrome, but my problem is edge

**Comment by smooney123** [comment]
SEC7120: [CORS] The origin 'ms-appx-web://microsoft.microsoftedge' failed to allow a cross-origin font resource at 'ms-appx-web:///assets/Fonts/BrowserMDL.ttf#Browser MDL2 Assets'.

CSS3119: No fonts available for @font-face rule

**Comment by smooney123** [comment]
i cannot seem to have the two options together --host and --hmr-hostname

**Comment by smooney123** [comment]
if i just use --hmr-hostname its ok, but the url is http://localhost:1234
