### ISSUE TITLE
Parcel 2 - Running parcel in lerna monorepo breaks node_module exclusion

### ISSUE THREAD

**Issue by b0z1** [parcel-bundler/parcel#4040]
# 🐛 bug report
Today i tried parcel 2 for the first time and tried to use it in a monorepo of mine.
But i encountered an issue.
Running parcel using lerna seems to break parcels node_module exclusion.

## 🎛 Configuration (.babelrc, package.json, cli command)
I made an github repo for you to checkout and test it for yourself.
https://github.com/b0z1/parcel2-lerna-issue

## 🤔 Expected Behavior
node_module gets excluded in bundling.
In case of a monorepo it also should exclude the roots node_module folder.

## 😯 Current Behavior
Parcel is bundling stuff which is inside of node_modules

Here a sample of the console log
```
$ lerna run dev --parallel
lerna notice cli v3.20.2
lerna info versioning independent
lerna info Executing command in 1 package: "yarn run dev"
frontend: $ parcel src/index.html
frontend: Server running at http://localhost:1234
frontend: Building index.html...
frontend: Building index.jsx...
frontend: Building semantic.min.css...
frontend: Building index.js...
frontend: Building index.js...
frontend: Building index.js...
frontend: Building react.development.js...
frontend: Building react-dom.development.js...
frontend: Building icons.eot...
frontend: Building flags.png...
frontend: Building icons.woff2...
frontend: Building icons.woff...
frontend: Building icons.ttf...
frontend: Building outline-icons.woff2...
frontend: Building outline-icons.eot...
frontend: Building icons.svg...
frontend: Building outline-icons.woff...
frontend: Building outline-icons.ttf...
frontend: Building outline-icons.svg...
frontend: Building brand-icons.eot...
frontend: Building brand-icons.woff2...
frontend: Building brand-icons.woff...
frontend: Building brand-icons.ttf...
frontend: Building brand-icons.svg...
frontend: Building App.jsx...
```

## 💁 Possible Solution
-

## 🔦 Context
My monorepo has packages for api, frontend, common

## 💻 Code Sample
https://github.com/b0z1/parcel2-lerna-issue

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | v13.6.0
| Yarn         | 1.21.1
| Operating System | Ubuntu 18.04

**Comment by mischnic** [comment]
So you expect that if a monorepo package doesn't declare a dependency, is should automatically be excluded?

In your example, it doesn't make sense because you are using a html file as an entry point.
Otherwise, you have to declare this explicitly via targets:
```json
{
	"app": "output/index.js",
	"targets": {
		"app": {
			"includeNodeModules": false // or an array of packages to bundle
		}
	}
}
```
https://github.com/parcel-bundler/parcel#target-configuration

**Comment by b0z1** [comment]
To answer your question:
I would expect any dependency which is inside of a node_modules folder to be skipped by the builder

**Comment by mischnic** [comment]
I still don't understand why you want node_modules to be excluded for a HTML frontend entrypoint (unless you're on Electron).

If you want that, you can use the config I posted above.

**Comment by b0z1** [comment]
Okay maybe the confusion lays somewhere else.

When i used Parcel 1, the build times were extremly fast. And in the build process, none of the resources from the node_modules were listed.

With Parcel 2, the build time in this case is extremly long and it lists all resources from the node_modules folder.

I tried your config u posted but its still the same behaviour.
I dont know what changed from Parcel 1 to Parcel 2 but Parcel 1 worked with lerna with zero config.
