### ISSUE TITLE
serialize-to-js security alerts are back... again

### ISSUE THREAD

**Issue by sangeeth96** [parcel-bundler/parcel#4042]
I was trying out v2 and I'm getting security alerts from npm regarding the use of `serialize-to-js` inside `@parcel/utils` package. I noticed that there were previous discussions about these at #3882, #3597 and #3514. Associated vulnerabilities can be found here: https://snyk.io/test/npm/parcel/2.0.0-alpha.3.2?tab=issues

I believe simply bumping the version to `^3.0.0` would fix the issues since `@parcel/utils` is not using `deserialize()` and stop the barrage of audit alerts.

**Comment by DeMoorJasper** [comment]
ugh, yeah it's just a version bump. The security alert doesn't actually apply to Parcel
