### ISSUE TITLE
Profiling for bundle size statistics?

### ISSUE THREAD

**Issue by uglycoyote** [parcel-bundler/parcel#4044]
# ❔ Question

Is there a way to get statistics from Parcel about what is contributing to the bundle size?

I would like something to similar to what Webpack has with their ability to dump out statistics to a json file and then analyze the data with something that provides a nice visualization, e.g.:

https://github.com/chrisbateman/webpack-visualizer

## 🔦 Context

For devopment,  I have a large mono-app with a lot of different experiments.   The bundle size is 10 MB and it is taking Parcel longer and longer to build it.  On my small Linode machine than I run Jenkins on, Parcel frequently crashes during bundling (due to low RAM on the instance I believe).  For these reasons, I think it would be great to have some more data from my build that would help figure out where the fat could be trimmed.

Maybe this ties in with #3740?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.4

**Comment by DeMoorJasper** [comment]
https://yarnpkg.com/package/parcel-plugin-bundle-visualiser

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by uglycoyote** [comment]
Thanks. That is exactly what I was looking for, not sure why my searches didn't lead to that.
