### ISSUE TITLE
How two plugins that works with same Asset type work together?

### ISSUE THREAD

**Issue by anivle** [parcel-bundler/parcel#4045]
# ❔ Question

Have a project where I used `Cybolic/parcel-plugin-css-regex-replace` plugin for replacing some CSS imports on build time. 
Now I want to write a plugin that performs some checks on CSS files but since replaces plugin did not do the job, calling super.parce() throws an error.

What is the correct way to use plugins in this case?
Could I specify the order for plugins?

## 🔦 Context

Could not use 2 plugins for the same asset type.

## 💻 Code Sample

```js
class ValidatedCSSAsset extends CSSAsset {
...
parse(code) {
    this.validate(code);
    return super.parse(code);
  }
...
```

Here error `... Cannot resolve dependency ...` occurs on ` super.parse(code);` call.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | v12.14.1
| npm/Yarn         | 6.13.4
| Operating System | MacOS Mojave 10.14.6 (18G95)

**Comment by mischnic** [comment]
This is possible with Parcel 2's plugin system (and the main reason for the change).

**Comment by anivle** [comment]
@mischnic Thanks for your answer!
