### ISSUE TITLE
Tree shaking not working with react es6 classes vs functional components

### ISSUE THREAD

**Issue by mshaaban0** [parcel-bundler/parcel#4046]
# 🐛 bug report

Tree shaking is not working properly with react classes (stateful vs functional) components.

This repo https://github.com/mshaaban0/tree-shaker demonstrates the issue clearly for a better understanding.

## 🤔 Expected Behavior

Tree shaking should eliminate unused/not imported code from the built bundle.

## 😯 Current Behavior
Unused/not imported react classes gets included in the built bundle.

## 💻 Code Sample

Playground repo is available [here](https://github.com/mshaaban0/tree-shaker)

**Comment by mischnic** [comment]
Could you please try this with Parcel 2?

**Comment by mshaaban0** [comment]
Hey @mischnic Just did, same results unfortunately.

**Comment by mischnic** [comment]
As suspected, this is related to Babel transpiling the classes.
Parcel 1: [modern](https://parcel-repl.now.sh/#JTdCJTIyY3VycmVudFByZXNldCUyMiUzQSUyMkphdmFzY3JpcHQlMjIlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIybWluaWZ5JTIyJTNBZmFsc2UlMkMlMjJzY29wZUhvaXN0JTIyJTNBdHJ1ZSUyQyUyMnNvdXJjZU1hcHMlMjIlM0FmYWxzZSUyQyUyMmNvbnRlbnRIYXNoJTIyJTNBdHJ1ZSUyQyUyMmJyb3dzZXJzbGlzdCUyMiUzQSUyMkNocm9tZSUyMDcwJTIyJTJDJTIycHVibGljVXJsJTIyJTNBJTIyJTIyJTJDJTIydGFyZ2V0JTIyJTNBJTIyYnJvd3NlciUyMiUyQyUyMmdsb2JhbCUyMiUzQSUyMiUyMiU3RCUyQyUyMmFzc2V0cyUyMiUzQSU1QiU1QiUyMmluZGV4LmpzJTIyJTJDJTIyaW1wb3J0JTIwJTdCRiU3RCUyMGZyb20lMjAlNUMlMjIuJTJGb3RoZXIuanMlNUMlMjIlM0IlNUNuJTVDbmNvbnNvbGUubG9nKEYpJTNCJTIyJTJDMSU1RCUyQyU1QiUyMm90aGVyLmpzJTIyJTJDJTIyZXhwb3J0JTIwY2xhc3MlMjBYJTIwJTdCJTVDbiU1Q3RyZW5kZXIoKSUyMCU3QiU1Q24lNUN0JTVDdHJldHVybiUyMCU1QyUyMnglNUMlMjIlM0IlNUNuJTVDdCU3RCU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwRigpJTdCJTVDbiU1Q3RyZXR1cm4lMjAlNUMlMjJmJTVDJTIyJTNCJTVDbiU3RCU1Q24lMjIlNUQlNUQlN0Q=) vs [transpiled](https://parcel-repl.now.sh/#JTdCJTIyY3VycmVudFByZXNldCUyMiUzQSUyMkphdmFzY3JpcHQlMjIlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIybWluaWZ5JTIyJTNBZmFsc2UlMkMlMjJzY29wZUhvaXN0JTIyJTNBdHJ1ZSUyQyUyMnNvdXJjZU1hcHMlMjIlM0FmYWxzZSUyQyUyMmNvbnRlbnRIYXNoJTIyJTNBdHJ1ZSUyQyUyMmJyb3dzZXJzbGlzdCUyMiUzQSUyMiUyMiUyQyUyMnB1YmxpY1VybCUyMiUzQSUyMiUyMiUyQyUyMnRhcmdldCUyMiUzQSUyMmJyb3dzZXIlMjIlMkMlMjJnbG9iYWwlMjIlM0ElMjIlMjIlN0QlMkMlMjJhc3NldHMlMjIlM0ElNUIlNUIlMjJpbmRleC5qcyUyMiUyQyUyMmltcG9ydCUyMCU3QkYlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRm90aGVyLmpzJTVDJTIyJTNCJTVDbiU1Q25jb25zb2xlLmxvZyhGKSUzQiUyMiUyQzElNUQlMkMlNUIlMjJvdGhlci5qcyUyMiUyQyUyMmV4cG9ydCUyMGNsYXNzJTIwWCUyMCU3QiU1Q24lNUN0cmVuZGVyKCklMjAlN0IlNUNuJTVDdCU1Q3RyZXR1cm4lMjAlNUMlMjJ4JTVDJTIyJTNCJTVDbiU1Q3QlN0QlNUNuJTdEJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMEYoKSU3QiU1Q24lNUN0cmV0dXJuJTIwJTVDJTIyZiU1QyUyMiUzQiU1Q24lN0QlNUNuJTIyJTVEJTVEJTdE)

**Comment by mischnic** [comment]
@mshaaban0 With Parcel 2, it does work with minification enabled?

**Comment by mshaaban0** [comment]
@mischnic Nope, just tried it with minification. Same issue.

**Comment by mischnic** [comment]
Could you please update your repo to include only Parcel 2?
I can't find the text `StatefulModuleOne` in the output.

**Comment by mshaaban0** [comment]
@mischnic Done.

**Comment by mischnic** [comment]
PR: https://github.com/parcel-bundler/parcel/issues/4046

Terser wasn't configured correctly for the commonjs output format.

**Comment by mshaaban0** [comment]
@mischnic Thanks for looking into this 👍
