### ISSUE TITLE
Weird issue with packages installing

### ISSUE THREAD

**Issue by green-arrow** [parcel-bundler/parcel#4047]
# 🐛 bug report

I'm in the process of migrating a webpack project to parcel. After running the first time to see which issues I need to tackle, I keep getting a single error at a time followed by a ton of NPM package installs. After the second or so install, I get a bower package installed with a nice big warning message about a security bug.

![image](https://user-images.githubusercontent.com/2180127/73190372-e4ea1c80-40f3-11ea-8123-bcd6fec8fb3c.png)

I'm not sure if I'm doing something wrong or if there's something else causing this issue, but figured I'd start here and see if anyone has any ideas 😄

**Comment by green-arrow** [comment]
I just realized after posting this that it seems this is due to how we had webpack set up. We had it set to absolute imports, so things like `components/` and `lib/` are mapped to folders in the `src` directory. It looks like parcel picks these up as unresolved and attempts to automatically import them from npm? Is this the case? If so, I wonder if it could perhaps pose more harm than good.

Thank you again for all your work with parcel!

**Comment by DeMoorJasper** [comment]
You're using aliasing. Parcel has no clue about it and thinks it's a node_module as you figured out. Therefore it tries to install it automatically.

This is not standard JS in any way so this has to be configured, luckily we do support aliasing similar to webpack but a bit easier to setup.

See the docs to set this up: https://en.parceljs.org/module_resolution.html#aliases
