### ISSUE TITLE
Security Issue: sensitive environment variables are exposed to the frontend indiscriminately

### ISSUE THREAD

**Issue by tomasgvivo** [parcel-bundler/parcel#4049]
# 🙋 seurity issue

Frequently, backend and frontend applications can be found in the same project.
Many backend applications, frameworks and docker-compose make use of the `.env` file to store critical sensitive data like credentials to apis, databases, etc.
Parcel automatically loads environment variables from `.env` file (and shell) and exposes the to the frontend where it can be acceded by any (with some level of skill) user.
This is potentially dangerous for someone who didn't read the environment variables documentation for parcel.
But currently, there is no way to avoid this issue except for ditching out parcel entirely from a project.

## 💁 Possible Solution

My humble suggestion is to disable the exposure of environment variables to the frontend by default.
If enabled, the developer must specify if `.env` file should be loaded (and it's path) and if shell environment variables should be loaded.
In another issue (#3537) it was discussed a cli option for only exposing environment variables that matched certain prefix. This could also help.

**Comment by mischnic** [comment]
> Frequently, backend and frontend applications can be found in the same project.

So you mean "unknowingly" using `process.env.SECRET_BACKEND_TOKEN`  in the frontend?

**Comment by tomasgvivo** [comment]
> > Frequently, backend and frontend applications can be found in the same project.
> 
> So you mean "unknowingly" using `process.env.SECRET_BACKEND_TOKEN` in the frontend?

Exactly! Like JWT secrets, or cookie secrets.

**Comment by tomasgvivo** [comment]
> > Frequently, backend and frontend applications can be found in the same project.
> 
> So you mean "unknowingly" using `process.env.SECRET_BACKEND_TOKEN` in the frontend?

Hmm, I see... Only environment variables referenced from the frontend are exposed.
Found the source https://github.com/parcel-bundler/parcel/blob/7f40aed6e59152685309cf38bc87849dc3bbb6e4/packages/transformers/js/src/visitors/process.js
Maybe make it a bit more clear in the documentation, to prevent this kind of issues. 😅
