### ISSUE TITLE
Is it possible to cache the node_modules In development mode?

### ISSUE THREAD

**Issue by techsin** [parcel-bundler/parcel#4050]
# 🙋 feature request

## 🤔 Expected Behavior

build node_modules into a file and invalidate it only if it's deleted by user OR package.lock.json has changed. 

## 😯 Current Behavior

when you restart parcel it builds node_modules from scratch

## 🔦 Context

I hate waiting 40s for material ui to build every time I restart parcel, which btw also has to be done because parcel just gets stuck at building packages for no reason and have to be restarted to actually get it work.

**Comment by mischnic** [comment]
This should work.

Please fill out the issue template: how are you invoking Parcel, which version, ideally a code sample.

**Comment by techsin** [comment]
```"dev": "parcel serve --port 8080 --log-level 4 src/index.pug --bundle-node-modules",```

**Comment by mischnic** [comment]
> how are you invoking Parcel, **which version**, **(ideally) a code sample**

**Comment by mischnic** [comment]
Closing due to lack of response
