### ISSUE TITLE
Is there a way to ignore the external node module?

### ISSUE THREAD

**Issue by in-html** [parcel-bundler/parcel#4051]
Help me please. Is there a way to ignore the external node module?
I get a module syntactic error in the node_modules folder when I run the "yarn start". Is there a way to ignore this module?

**Comment by mischnic** [comment]
We can't help you at all without at least the error message.

**Comment by in-html** [comment]
Thanks for your reply.
I just need to ignore the module, which I cannot change.
The error looks like this: 
"Identifier '_toConsumableArray' has already been declared"
They 2 times declared a function with the same name.

**Comment by in-html** [comment]
I use React, Parcel and draftjs-md-converter. When i run the command "yarn start" I get an error:
Identifier '_toConsumableArray' has already been declared.
It seems the function is declared 2 times.
I understand that ignoring errors is bad. But I still want to know if there is a way to ignore errors for third-party modules?

**Comment by mischnic** [comment]
Again: you cannot 'ignore' a module, because that code is needed at runtime.

**Comment by in-html** [comment]
Okay, Is this a feature of Parcel? Why does this module work correctly in the base React?

**Comment by mischnic** [comment]
What do you mean by `base React`?  And I don't understand how Parcel, React and draftjs-md-converter are connected here.

**Comment by in-html** [comment]
Sorry, maybe I’m explaining poorly. I mean If I start the local server using the standard command: "node scripts/start.js" - it works. 
But if I execute the command:  "parcel --no-autoinstall  ./src/index.html" - I get an error starting the local server:
> 🚨 /my-project/node_modules/draftjs-md-converter/dist/index.js:195:9: Identifier '_toConsumableArray' has already been declared (195:9)
For this reason, I asked you.

**Comment by mischnic** [comment]
What does `scripts/start.js` do? 

This remote-debugger without a code sample won't lead anywhere...

**Comment by in-html** [comment]
Oh yes it doesn't look obvious. I mean this command in `package.json`:
```
"scripts": {
    "start": "react-scripts start",
    ...
  },
```

**Comment by mischnic** [comment]
So I'm guessing you're saying: it works with create-react-app but not with Parcel.

And again, I unfortunately can't help you without a code sample so I reproduce the error on my machine.

**Comment by in-html** [comment]
Good, I will try to create a sample

**Comment by in-html** [comment]
I replaced the library with this:
https://github.com/Rosey/markdown-draft-js
Now it works with Parcel.

Think we can close it. Thanks
