### ISSUE TITLE
Log levels are ignored for log messages

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#4052]
# 🐛 bug report

A regression from https://github.com/parcel-bundler/parcel/pull/4009

Previously:
https://github.com/parcel-bundler/parcel/blob/7f40aed6e59152685309cf38bc87849dc3bbb6e4/packages/reporters/cli/src/UI.js#L173-L177

Now:
https://github.com/parcel-bundler/parcel/blob/df482fb90c27822676bc47f34177beb7c422114f/packages/reporters/cli/src/CLIReporter.js#L90-L101

# Example

This causes e.g. verbose-level server logs to be printed by default
```
$ parcel2 index.html
ℹ️ Server running at http://localhost:1234
✨ Built in 1.59s
@parcel/reporter-dev-server: Request: localhost:1234/
@parcel/reporter-dev-server: Request: localhost:1234/react-hmr.e56dcd81.js
@parcel/reporter-dev-server: Request: localhost:1234/react-hmr.e56dcd81.js.map
@parcel/reporter-dev-server: Request: localhost:1234/_parcelsource_root/App.js
@parcel/reporter-dev-server: Request: localhost:1234/favicon.ico
```

**Comment by DeMoorJasper** [comment]
SimpleCLIReporter no longer exists right? It's just CLIReporter now

**Comment by Taym95** [comment]
I would like to take this issue!

**Comment by DeMoorJasper** [comment]
@Taym95 alright sounds good. Go for it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
