### ISSUE TITLE
Parcel failing to remove duplicate javascript 

### ISSUE THREAD

**Issue by uglycoyote** [parcel-bundler/parcel#4054]
# 🐛 bug report

Using the profiling tool that @DeMoorJasper  recommended in #4044, I discovered that one of the reasons for my large bundle size is duplicate copies of some of the contents of the [BlueprintJS ](https://blueprintjs.com/) package that I am using.

The webpage states that:

> If an asset is required in more than one bundle, it is hoisted up to the nearest common ancestor in the bundle tree so it is not included more than once.

## 🤔 Expected Behavior

Parcel should remove the duplicate copies of javascript code brought in through different branches of the tree.

## 😯 Current Behavior

Here's the `node_modules` part of my bundle tree as displayed by `parcel-plugin-bundle-visualiser`:

![image](https://user-images.githubusercontent.com/2461007/73330350-62f21480-4215-11ea-971b-fa592fd4381d.png)

Firstly the iconSvgPaths.js sticks out like a sore thumb here, it's hundreds of K, included three times, and I'm probably only using less than a dozen of the actual icons, so it's very unfortunate.  

Looking a bit closer, I can see that `@blueprintjs/core/lib/esm/components` is also repeated three times here.

## 💻 Code Sample

If it helps I can probably provide a repro sample without too much trouble just by creating a small project that imports a few parts of blueprintjs.

Before i spend too much time on repro details I thought I would just check to see if this is a bug, whether I should expect Parcel to remove these duplicates?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.4
| Node             |  10.16.3
| npm/Yarn         | npm 6.4.1
| Operating System |  Windows 10

**Comment by mischnic** [comment]
> If it helps I can probably provide a repro sample without too much trouble just by creating a small project that imports a few parts of blueprintjs.

Please do. But I think it's more likely that npm isn't deduping these pacakges in node_modules. Maybe you could also try running `npm dedupe` or using `yarn` ?

**Comment by uglycoyote** [comment]
Hi @mischnic your comment lead me to the solution, thanks.  I wasn't aware that deduping was a thing, I had assumed based on the statement I quoted above that this was Parcel's domain.  

>"If an asset is required in more than one bundle, it is hoisted up to the nearest common ancestor in the bundle tree so it is not included more than once."

I guess in this case it doesn't see it as the same asset if there are two different copies at different locations in node_modules.

originally I found this many copies of the icons file:

```
➜  node_modules git:(master) find . -iname iconSvgPaths.js
./@blueprintjs/table/node_modules/@blueprintjs/icons/lib/esm/generated/iconSvgPaths.js
./@blueprintjs/table/node_modules/@blueprintjs/icons/lib/esnext/generated/iconSvgPaths.js
./@blueprintjs/table/node_modules/@blueprintjs/icons/lib/cjs/generated/iconSvgPaths.js
./@blueprintjs/icons/lib/esm/generated/iconSvgPaths.js
./@blueprintjs/icons/lib/cjs/generated/iconSvgPaths.js
./@blueprintjs/select/node_modules/@blueprintjs/icons/lib/esm/generated/iconSvgPaths.js
./@blueprintjs/select/node_modules/@blueprintjs/icons/lib/cjs/generated/iconSvgPaths.js
```

whereas if using `yarn install` (which does deduping automatically) I'm down to just:

```
➜  node_modules git:(master) find . -iname iconSvgPaths.js
./@blueprintjs/icons/lib/esm/generated/iconSvgPaths.js
./@blueprintjs/icons/lib/esnext/generated/iconSvgPaths.js
./@blueprintjs/icons/lib/cjs/generated/iconSvgPaths.js
```

strangely, `npm dedupe` didn't achieve the same effect on the first try.  I think part of my problem is that I installed different parts of `@blueprintjs` at different times (the `table` and `select` parts are extras that are not part of their core package).  So having different versions of things in `node_modules` might have prevented the deduping from working. (in which case, I'm not sure how yarn was able to dedupe it because when testing with yarn I had a similar mishmash of version numbers).  In any case, after doing an `npm update` on all the `@blueprintjs` packages, the `npm dedupe` worked and got rid of the duplicates.

Maybe yarn is more thorough with its deduping abilities?  The maybe it dedupes based on contents rather than just version numbers?  

Thanks for the help, can consider this closed.   

If this is something that you would still consider a bug? Is parcel intended to strip out duplicates if they appear multiple times in `node_modules`?  or is it always up to the user to try to make sure they `dedupe` first?  Please close this if it's outside of Parcel's domain to solve this problem, otherwise I'll send you a small project soon with a case where you can reproduce this behaviour.

**Comment by mischnic** [comment]
> Maybe yarn is more thorough with its deduping abilities?

It is (or at least was).

> Maybe it dedupes based on contents rather than just version numbers?

No, but I do know that it sometimes chooses the version that fits most dependencies, rather than simply the newest.

> I had assumed based on the statement I quoted above that this was Parcel's domain.
>
> > "If an asset is required in more than one bundle, it is hoisted up to the nearest common ancestor in the bundle tree so it is not included more than once."

Well, from Parcel's perspective, "an asset" is one file. So you should read this "if a file is used in multiple bundles". We cannot search the whole node_modules folder for an identical file and "merge" them, this is npm/Yarn's domain.

> Please close this issue if it's outside of Parcel's domain to solve this problem,

Yes, as just explained.

**Comment by uglycoyote** [comment]
@mischnic, thanks for the explanation.
 
>We cannot search the whole node_modules folder for an identical file and "merge" them, this is npm/Yarn's domain.

I don't think it would be necessary to search the entire node_modules folder.   As Parcel is bulding up the bundle tree it could hash the contents of each file and then just check the tree for duplicate hashes.    In the "hoisting" process, I would have thought that assets would recognized as being the same by having the same content hash rather than having the same file path.  Would it be an improvement if it used content hashes, or is there some reason why that would not work? 

Thanks

**Comment by mischnic** [comment]
> I don't think it would be necessary to search the entire node_modules folder. As Parcel is bulding up the bundle tree it could hash the contents of each file and then just check the tree for duplicate hashes. In the "hoisting" process, I would have thought that assets would recognized as being the same by having the same content hash rather than having the same file path. Would it be an improvement if it used content hashes, or is there some reason why that would not work?

Files with the same content cannot be treated as "one asset": https://github.com/parcel-bundler/parcel/issues/3523

**Comment by uglycoyote** [comment]
That's interesting and unfortunate, but yes I see the problem!  
Thanks again for the continued explanations.
