### ISSUE TITLE
axios breaks with scope-hoisting

### ISSUE THREAD

**Issue by ericsoco** [parcel-bundler/parcel#4056]
# 🐛 bug report
Breaking out separate issue from [#4003](https://github.com/parcel-bundler/parcel/issues/4003#issuecomment-575318781).

As suggested by @mischnic [here](https://github.com/parcel-bundler/parcel/issues/1080#issuecomment-557240449), I'm using `transformer-raw` to import files that are loaded at runtime via XHR (specifically, [axios](https://github.com/axios/axios)). When running `parcel serve`, this works like a charm. When running a bundle generated via `parcel build`, however, the XHRs are requesting `[Object object]`.

## 🎛 Configuration (.babelrc, package.json, cli command)
All config is viewable in [the GH repo](https://github.com/ericsoco/fire-map/tree/aba3aa071dead1250a8b10989124114a4e3b7aba).

Also pasted below for reference.

`package.json`:
```js
  "default": "dist/index.html",
  "targets": {
    "default": {
      "publicUrl": "./"
    }
  }
```

`.parcelrc`:
```js
{
  "extends": "@parcel/config-default",
  "transforms": {
    "url:*": ["@parcel/transformer-raw"]
  }
}

```

`.babelrc`:
```js
{
	"presets": [
		"@babel/preset-env",
		"@babel/preset-react"
	],
  "plugins": [
    "@babel/plugin-proposal-optional-chaining",
    ["@babel/plugin-proposal-pipeline-operator", { "proposal": "minimal" }],
    "babel-plugin-styled-components",
    [
      "babel-plugin-import",
      {
        "libraryName": "@material-ui/core",
        "libraryDirectory": "",
        "camel2DashComponentName": false
      },
      "mui-core"
    ],
    [
      "babel-plugin-import",
      {
        "libraryName": "@material-ui/icons",
        "libraryDirectory": "",
        "camel2DashComponentName": false
      },
      "mui-icons"
    ]
  ]
}
```

## 🤔 Expected Behavior

The XHRs should target the files imported via `transformer-raw` in the `parcel build` bundle in the same way they do in the `parcel serve` bundle.

## 😯 Current Behavior

XHRs for the imported files in the `parcel build` bundle target `[Object object]`.

## 💁 Possible Solution

Is there another way to specify static files for runtime use? (See #1080)

## 🔦 Context

I'm loading a significant amount of data into my application, and need to chunk it to prevent a huge bundle up-front.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2 |
| Node             | 10.16.0 |
| npm/Yarn         | yarn@1.19.2 |
| Operating System | OSX |

**Comment by mischnic** [comment]
So you mean that the bundle doesn't do something like `fetch("./data-2019.geojson")` but instead `fetch("[Object object])` ?
This should work (especially if it does with `serve`). 

But I get only `ReferenceError: require is not defined`, will look into the original issue now....

**Comment by mischnic** [comment]
Reproducible with just
```js
import axios from 'axios';
import pkg from "url:./package.json";

axios(pkg).then(console.log)
```

**Comment by mischnic** [comment]
We are missing a strict mode directive in the output.
One of the differences between strict mode and loose mode: parameters and `arguments`:

```js
function request(config) {
	config = arguments[1] || {};
	config.url = arguments[0];

	return config;
}
function requestStrict(config) {
	'use strict';
	config = arguments[1] || {};
	config.url = arguments[0];

	return config;
}

console.log(request('foo')); // {url: [Circular to url]}
console.log(requestStrict('foo')); // {url: 'foo'}
``

In the first case, `config.url` is indeed an object.


https://github.com/axios/axios/blob/e50a08b2c392c6ce3b5a9dc85ebc860d50414529/lib/core/Axios.js#L27-L36

**Comment by devongovett** [comment]
Appears to work in the latest nightly.
