### ISSUE TITLE
throw error in dev when import scss in index.html and index.js

### ISSUE THREAD

**Issue by Hental** [parcel-bundler/parcel#406]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

🐛 bug

### 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```
{
  "name": "parcel",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "dev": "./node_modules/.bin/parcel src/index.html -p 3000",
    "build": "./node_modules/.bin/parcel build src/index.html -d dist"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "node-sass": "^4.7.2",
    "parcel-bundler": "^1.3.1"
  },
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  }
}
```

.babelrc 
```js
{
  "presets": [
    "react",
    "env"
  ]
}
```

### 🤔 Expected Behavior

no error

### 😯 Current Behavior

throw an Uncaught Error

```js
Uncaught Error: Cannot find module '4'
    at newRequire (023fb3ba8ca1e71b1d9b1e114c5f52a9.js:32)
    at localRequire (023fb3ba8ca1e71b1d9b1e114c5f52a9.js:38)
    at Object.require.6._css_loader (023fb3ba8ca1e71b1d9b1e114c5f52a9.js:17916)
    at newRequire (023fb3ba8ca1e71b1d9b1e114c5f52a9.js:46)
    at localRequire (023fb3ba8ca1e71b1d9b1e114c5f52a9.js:38)
    at Object.require.3../app.jsx (023fb3ba8ca1e71b1d9b1e114c5f52a9.js:17925)
    at newRequire (023fb3ba8ca1e71b1d9b1e114c5f52a9.js:46)
    at require.14 (023fb3ba8ca1e71b1d9b1e114c5f52a9.js:63)
    at 023fb3ba8ca1e71b1d9b1e114c5f52a9.js:68
```

### 💁 Possible Solution

if i only import scss in index.html or in index.js, it not throw an error.

### 🔦 Context

project
```
  -- src
    -- index.html
    -- index.js
    -- global.scss
    -- style.scss
  -- .babelrc
  -- package.json
```

index.html
```html
<!DOCTYPE html>
<html lang="zh-cnm-Hant-CN">
<head>
  <title>parcel</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="./global.scss">
</head>
<body>
  <div class="react-app"></div>
  <script src="./index.js"></script>
</body>
</html>
```

```index.js
import './app.jsx';
import './style.scss';

if (module.hot) {
  module.hot.accept(() => {
    console.log('hot up!');
  });
}

console.log('parcel demo');
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.3.1
| Node             | 8.9.2
| npm/Yarn         | 1.3.2
| Operating System | mac os high sierra 10.13.2

**Comment by runesam** [comment]
I hack with those

`    "build-css": "node-sass-chokidar app/ -o app/",
    "watch-css": "npm run build-css && node-sass-chokidar app/ -o app/ --watch --recursive",
    "start:dev": "cross-env NODE_ENV=development parcel index.html -p 3000",
    "start": "npm-run-all -p watch-css start:dev",
    "build:prod": "cross-env NODE_ENV=production parcel build index.html --no-minify --public-url /",
    "build": "npm-run-all build-css build:prod"`

`npm i -D npm-run-all node-sass-chokidar`

`app`  is my root. consider changing it to fit yours

**Comment by goyney** [comment]
+1 Having the same issue, same error "Cannot find module '4'"

**Comment by brandon93s** [comment]
A lot has changed and been fixed since this issue was opened! Please give a newer release of Parcel a try and let us know if the issues persists. Thanks.
