### ISSUE TITLE
Issue -- client side bug parcel related?

### ISSUE THREAD

**Issue by bingomanatee** [parcel-bundler/parcel#4068]
# 🐛 bug report

In the client , displays 'Error: Cannot find module '../node_modules/@babel/runtime/helpers/interopRequireDefault.js'''

doesn't seem to do any harm but unnerving

## 🎛 Configuration (.babelrc, package.json, cli command)

    "parcel-bundler": "1.12.3",

.babelrc

```js
{
  "presets": [
    [ "@babel/preset-env", {
      "targets": { "node": "10" }
    } ]
  ],
  "plugins": [ "@babel/plugin-transform-modules-commonjs",
    [
      "@babel/plugin-transform-runtime",
      { "regenerator": true }
    ]
  ]
}

```

## 🤔 Expected Behavior
not that...

## 😯 Current Behavior

In the client , displays 'Error: Cannot find module '../node_modules/@babel/runtime/helpers/interopRequireDefault.js'''

doesn't seem to do any harm but unnerving

## 🔦 Context

running a standard React app. 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
Please fill out the issue template: version, code sample.

`@babel/plugin-transform-modules-commonjs` isn't needed with Parcel, and you should specify the node version in `package.json#engines` instead of in the babelrc.

**Comment by mischnic** [comment]
Closing due to lack of response
