### ISSUE TITLE
rfc: make parcel logger configurable, pluggable, de-coupled from the bundler

### ISSUE THREAD

**Issue by cdaringe** [parcel-bundler/parcel#4071]
# 🙋 feature request

- support a simple logger interface, configuration, or instance when creating a new `Bundler()`

## 🤔 Expected Behavior

- *log nothing* when the bundler gets to work.  provide events to subscribe to, and consumers can log them as desired using the API, OR
- allow me to provide a logger (less desirable)

## 😯 Current Behavior

- the current logger is "smart", resets the cursor, and assumes it's the top level executable.  this is problematic. for library authors, we want to control our own I/O streams, and `parcel`'s logger assumes it's the only thing actively writing to stdio and/or asserts its opinion on the customer.

## 💁 Possible Solution

- de-singleton-ify the current logger impl
- in top level executables, e.g. cli tooling, init a logger, create a bundler, and wire in the logger to the bunder

## 🔦 Context

i'm trying to write a server using parcel as a library (as a koa middleware), but the bundler meddles w/ my process primitives.

## 💻 Examples

- https://github.com/parcel-bundler/parcel/blob/5cccb78eb4b1442832e38d1b31875bbd8139b3ca/packages/reporters/cli/src/render.js#L38

right now i can monkey patch the logger:

```js
  const info =  (...args: any[]) => services.logger.info('[parcel]', ...args) // injecting my logger instead
  const error = (...args: any[]) => services.logger.error('[parcel]', ...args)
  logger.log = info
  logger.error = info
  logger.write = info
  logger.warn = error
  logger.error = error
  logger.success = info
```

but it's not good enough, because there is a `reporter` that also is at play here, which is an independent logging mechanism

**Comment by devongovett** [comment]
In Parcel 2, logger events are sent to reporter plugins rather than directly logged. It would be up to the reporter to decide what to do with the log events. The default reporter logs them to the CLI, but other reporters may decide to do something else.

Going to close this since we're not really working on parcel 1 anymore.

**Comment by cdaringe** [comment]
@devongovett, will there be a default reporter when creating a bundler instance?  Will I be able to tune it?

**Comment by devongovett** [comment]
Yep! There’s a default one in the default parcel config, but you can override it in your own .parcelrc file.

**Comment by cdaringe** [comment]
sweet!  sorry to pester, but will it also be settable via the Bundler API?  The default parcel config and a file are both cool, but not precisely what I'm hoping to use as a library author

**Comment by devongovett** [comment]
You can provide a parcel config preset that others can extend in their own config. We don’t want to support “hidden” configuration in this kind of wrapper tool. It makes it hard for users to customize and understand what’s going on. We’ve seen this play out with eg create-react-app where when you need to change one tiny thing you have to eject. I think it’s better to provide explicit extension points and presets so that users can access all aspects if they need to.

**Comment by cdaringe** [comment]
right--that's what I'm after.  In code I want to specify `reporter: myEventingReporter` that does not write to stdio at all on its own, and just emits messages for me to log thru my own logging infrastructure

**Comment by devongovett** [comment]
.parcelrc

```json
{
  "extends": "@parcel/config-default",
  "reporters": ["@cdaringe/parcel-reporter-logger"]
}
```

@cdaringe/parcel-reporter-logger

```js
import {Reporter} from '@parcel/plugin';

export default new Reporter({
  report({event}) {
    // do stuff
  }
});
```

**Comment by cdaringe** [comment]
@devongovett,thanks for the support.  Looks like writing my own reporter won't be a problem :ok_hand: . However, I need to be able to plug it in programmatically through the bundler options. A RC file doesn't really work for library authors use case.  I don't have access or freedom to write a rc file to my consumer's projects/project directory.  will I be able to do something like `new Bundler({ reporter: bestReporter })`?
