### ISSUE TITLE
Defining a base path for assets like images (absolute, not relative)

### ISSUE THREAD

**Issue by iam-markus** [parcel-bundler/parcel#4075]
# ❔ Question
Having a folder structure like this:
- assets/
   a.png
   b.png
- src/
   - componentA.js
   - componentB.js
   - base_components/
      button.js

How can I get the path to the assets folder from any component.
I would then like to do this: `getAssetPath() + '/a.png'`

## 🔦 Context
I know how to reference images **relatively**.
But that assumes that if I move a component in a subfolder I would need to change the import path. E.g. if button.js moves up in the folder hierarchy, I would need to change my code from this:
`<img src={require('../../assets/image.png')} />`
to this.
`<img src={require('../assets/image.png')} />`

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4

Thank you.

**Comment by mischnic** [comment]
Something like
`<img src={require('/../assets/image.png')} />` or
`<img src={require('/assets/image.png')} />` should work

See https://parceljs.org/module_resolution.html#absolute-paths

**Comment by iam-markus** [comment]
Thank you, this works for me:
`<img src={require('/../assets/image.png')} />`
