### ISSUE TITLE
How does one use multi target using HTML

### ISSUE THREAD

**Issue by topaxi** [parcel-bundler/parcel#4078]
# ❔ Question

How does one use the multi target feature using HTML entries? Can this be achieved in one step? Or would I build the `index.js` using my desired targets and then do a second build with an HTML file referencing the generated builds (which would make the build a bit awkward as the HTML file would not reference the source files anymore)?

## 🔦 Context

Trying to build an `index.html` file  (actually several html files) with an `index.js` for legacy browsers like IE and a modern build for browsers that support modules.

I've read up on targets, but it does not seem possible specify targets on a per file basis.

## 💻 Code Sample

Given: 
```
src/index.html
src/index.js
src/index.legacy.js
```

`src/index.html`
```html
<!doctype html>
<script src="./index.legacy.js" nomodule></script>
<script src="./index.js" type="module"></script>
```

`src/index.js`
```javascript
async function main() {
  console.log(await fetch('/some/api/data.json'))
}

main().catch(console.error)
```

`src/index.legacy.js`
```javascript
import 'somepolyfills'
import './index.js'
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.77+287ac639
| Node             | v12.13.1
| Yarn         | 1.21.1
| Operating System | macOS

**Comment by devongovett** [comment]
That looks like a fine way to implement it. Was there an issue you ran into?

**Comment by topaxi** [comment]
I was wondering whether that could be done using one single build somehow. Doing it in two builds should be fine though, only makes my file references and directory structure a tiny bit more awkward, as the HTML now has to reference built files instead of source files.

And I'll also have to run two processes to watch for file changes / serve the HTML.
