### ISSUE TITLE
SVG minification deletes SVG

### ISSUE THREAD

**Issue by innovate-invent** [parcel-bundler/parcel#4083]
# 🐛 bug report

Enabling minify deletes the contents of a svg in a html document.
It does not occur for svg elements that actually draw content.

## 🎛 Configuration (.babelrc, package.json, cli command)

None

## 🤔 Expected Behavior

Whitespace should be removed between the tags but not delete tags

## 😯 Current Behavior

```html
<html><body>
...
            <svg>
                <filter id="shadow" x="-5" y="-5" width="200" height="200">
                    <feGaussianBlur in="SourceAlpha" stdDeviation="5"></feGaussianBlur>
                    <feColorMatrix result="matrixOut" in="offOut" type="matrix" values="0   0   0   0   0
                                0   0   0   0   0
                                0   0   0   0   0
                                0   0   0   2   0"></feColorMatrix>
                    <feMerge>
                        <feMergeNode></feMergeNode>
                        <feMergeNode in="SourceGraphic"></feMergeNode>
                    </feMerge>
                </filter>
            </svg>
...
</body></html>
```
The above svg element specifies a filter for use elsewhere in the document but is minified to `<svg></svg>`.

Disabling minification preserves the filter tag.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             |
| npm/Yarn         | 6.13.6
| Operating System | Linux

**Comment by devongovett** [comment]
likely an htmlnano issue?

**Comment by mischnic** [comment]
Put this in a .htmlnanorc:
```json
{ "minifySvg": { "plugins": [{ "removeUselessDefs": false }] } }
```
List of options: https://github.com/svg/svgo/#what-it-can-do

**Comment by innovate-invent** [comment]
Thanks! I am new to parcel and was unaware of these sub applications.
