### ISSUE TITLE
[RFC] Parcel 2: Lazy loaded dynamic imports

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#4089]
# 💬 RFC

I was wondering if [lazily load dynamic imports](https://parceljs.org/code_splitting.html#dynamic-imports-with-async/await) was really necessary.

It just seems confusing to change the behavior of how a language feature work, and on top of that it prevents optimizing web apps using defer loading until idle without adding custom code to make it work in parcel
 
## 🔦 Context
imagine a router using optimizations like pre-loading pages when idling, the router when idle calls
```js
const preloadLazyRoute = ({ url }) => {
  import(url)
}
```
in Parcel, this wouldn't work and actually defer the loading until the page is needed on render.

Since this could potentially? be a breaking change(not actually breaking anything, but changing the actual behavior), it could be removed for Parcel 2.

**Comment by mischnic** [comment]
I agree, Parcel's `import()` should behave the same as running the code untranspiled in a modern browser.

**Comment by devongovett** [comment]
I don't believe this is actually incorrect according to the spec. The spec only defines `import()` as a host defined function that returns a promise. It doesn't specify how or when the imported module is executed.

That said, I think Parcel 2 already doesn't load modules lazily. Did you run into a problem with it?

**Comment by Banou26** [comment]
No, it's just something i had encountered in v1 and didn't really like, i just randomly thought back of that so i just wanted to express my opinion about it before it's re-implemented in v2.

**Comment by devongovett** [comment]
K, going to close this then.

**Comment by mischnic** [comment]
> I think Parcel 2 already doesn't load modules lazily.

Indeed.

Even if a lazy `import()` were allowed by the spec, the Parcel output would still behave differently with the default browserlist and a modern `last 1 Chrome version` config.
