### ISSUE TITLE
How to enable runtime error overlays?

### ISSUE THREAD

**Issue by andrewpeterprifer** [parcel-bundler/parcel#4096]
# ❔ Question

Hey all, how do I get a similar runtime error overlay as shown in Devon's tweet [here](https://twitter.com/devongovett/status/1195377210133106690)? I'm trying out the react-refresh example and I'm only getting an overlay for bundling/transpiling errors, but not runtime ones, like the `ReferenceError` displayed here.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-alpha.3.2

**Comment by devongovett** [comment]
I believe I used this one: https://github.com/commissure/redbox-react with an error boundary around my app: https://reactjs.org/docs/error-boundaries.html
