### ISSUE TITLE
Allow to run server in build command

### ISSUE THREAD

**Issue by darky** [parcel-bundler/parcel#410]
### 🙋 feature request

Need to build and after run server for production use. Now server runned only with serve command.

### 💁 Possible Solution

* `parcel build` and it run server
* `parcel build-server`
* `parcel build --allow-server`
* ...

**Comment by DeMoorJasper** [comment]
In my opinion this would not be a great solution because for safety & caching/performance reasons you might still want to add a proxy in front of this server (ex. nginx) which would end up being the same as using build as currently implemented. Unless u mean having a minified version of watch, because this could trigger rebuilds for production environments?

**Comment by brandon93s** [comment]
Are you wanting to use the integrated development server in production, to serve to your users? The server has not been designed, built or tested for that use case and I would really advise against using it as a production file server.

**Comment by darky** [comment]
Yep, I want to use it for production.
I understand your opinion about nginx or haproxy, it more reliable instuments for this purpose.
But for my case it no matter.
No terrible much more, if you disagree, I can use simple asset server.
A little bit much work, ok.

> Unless u mean having a minified version of watch, because this could trigger rebuilds for production environments

Maybe this case make sense.

**Comment by devongovett** [comment]
I would recommend using something like nginx or even a node-based static file server like [serve](https://npmjs.com/package/serve). Just point it at your `dist` folder that is produced by Parcel. Or you could even just upload the files to S3 or some static file host.

The built-in development server is not meant to be used in production.
