### ISSUE TITLE
Explicitly extracing a relative import into separate file on build?

### ISSUE THREAD

**Issue by iLLucionist** [parcel-bundler/parcel#4107]
Very simple question (hopefully). I want to explicitly name a relative import to be built separately, so that I can manually replace that file AFTER build.

Use case: an interactive dashboard for which, after build, I manually change the data file.

Currently:
app.js
styles.css
index.html

I have a lot of modules (Vuex store modules) that relatively import variables from data.js'.

So I want to tell parcel something like 'build-separately' or 'extract'  data.js, yielding:

app.js
styles.css.
index.html
**data.js**

Then, I can just keep the whole build the same, but manually change out data.js.

I looked into code splitting and bundling, but I do not think that is what I am looking fore.

**Comment by oliver-hoff** [comment]
I have the exact same problem and I am not sure how to go about this
