### ISSUE TITLE
dart-sass url() doesn't resolve relative paths correctly when another file is imported.

### ISSUE THREAD

**Issue by Lusito** [parcel-bundler/parcel#4115]
# 🐛 bug report

I just switched from node-sass to dart-sass since parcel would hang with node-sass and people said to use dart-sass. However, when I include a font via a url() path relative to its css file, it tries to resolve the file relative to the root .scss file that is currently being processed (i.e. the one imported from .ts or .html).

This worked perfectly with node-sass.

I can just import the modules in typescript/javascript, but this should be possible from .scss files as well.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
        "sass": "^1.25.0",
        "parcel-bundler": "^1.12.4",
```

## 🤔 Expected Behavior

It should resolve the path relative to the file where the url statement is. 

## 😯 Current Behavior

It resolves the url path relative to the root file which is being processed.

```
×  <root>\src\styles\files\open-sans-latin-300.woff2: ENOENT: no such file or directory, open '<root>\src\styles\files\open-sans-latin-300.woff2'
Error: ENOENT: no such file or directory, open '<root>\src\styles\files\open-sans-latin-300.woff2'
```

## 💻 Code Sample

style.scss:
```scss
@import '~typeface-open-sans';
```
The css file from that module looks like this: https://github.com/KyleAMathews/typefaces/blob/master/packages/open-sans/index.css

I've tried putting the css file inside of the `<root>/fonts` folder, but that doesn't seem to change anything.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             |10.15.3
| npm/Yarn         | 6.4.1
| Operating System |Win7

**Comment by DeMoorJasper** [comment]
Gonna close this as it's basically a fundamental issue with sass not supporting this.

https://github.com/sass/sass/issues/2535

**Comment by Lusito** [comment]
Thanks for the research. Will watch the other topic and re-open when it gets resolved.
