### ISSUE TITLE
🙋 Add a way to specify what "*Asset.js" handles which types of assets

### ISSUE THREAD

**Issue by devmattrick** [parcel-bundler/parcel#412]
### 🤔 Expected Behavior
Ideally, there should be some way to specify how assets are handled by extension type. For example, Handlebars templates use `.hbs` or `.handlebars` conventionally, however they aren't necessarily bound by that convention and many people simply stick to `.html`, potentially for compatibility with their editor or for other reasons.

### 😯 Current Behavior
The ability to associate customize what extensions are handled by which asset types would allow for developers to specify how their assets are handled in the instance of either a conflict of extensions or if they use a nonstandard extension. Currently, developers must use standardized extensions which could potentially break their workflow.

### 💁 Possible Solution
I think the easiest way would to add an optional configuration file that can be passed to Parcel. This obviously isn't ideal and I understand the desire for a "zero configuration" type of build tool. However, I think an optional minimal configuration would give developers a bit more control when needed. Assets can be handled by their normal "asset type" handler by default, but then could be overridden by a Parcel config file, that way it doesn't break current build systems.

A potential configuration file could be similar to:

```
[
    // Use default registered extension
    {
        extension: "ext",
        handler: "<the extension registered with Parcel>"
    },
    // With Parcel core
    {
        extension: "ext",
        handler: "parcel-bundler/<the extension registered with Parcel>"
    },
    // With a specified plugin
    {
        extension: "ext",
        handler: "parcel-plugin-something/<the extension registered with Parcel>"
    }
]
```

### 🔦 Context
I've made [parcel-plugin-nunjucks](https://github.com/devmattrick/parcel-plugin-nunjucks), which currently handles the `.njk` file type. It has been somewhat adopted as a "standard", but many people use `.nunjucks` and `.html` as extensions for Nunjucks templates. Nunjucks is also compatible with Jinja, so people may be using their standardized extension as well.

Thanks for reading!

**Comment by brandon93s** [comment]
This may be best handled by the plugins themselves. `parcel-plugin-nunjucks` could support the configuration which tells it which extensions to register itself for. If the plugin were to register as `html` it would overwrite parcel's default implementation.

**Comment by devmattrick** [comment]
@brandon93s hmm, that's a good point. Perhaps the community should adopt a standard config name and format so users won't need to have multiple config files in their project root?

**Comment by brandon93s** [comment]
@devmattrick I'd stick with an already established convention:

- `.pluginrc`
- read from custom section in `package.json`
- `.plugin.yml`
- `plugin.config.{js|json}`
