### ISSUE TITLE
Inject #[no_mangle] automatically for rust

### ISSUE THREAD

**Issue by zackify** [parcel-bundler/parcel#4126]
# 🙋 feature request

I would like to add a step before compiling rust files that automatically adds #[no_mangle] above any function with “pub” in front of it. I haven’t worked much with parcel before but I could make a PR if this is something that would be accepted. Thanks

## 🤔 Expected Behavior

Automatically adds it. 

## 😯 Current Behavior

You have to manually add this for every function.

**Comment by devongovett** [comment]
Closing since Rust isn't supported in Parcel 2.
