### ISSUE TITLE
🙋 Browser error overlay similar to react-error-overlay

### ISSUE THREAD

**Issue by will-stone** [parcel-bundler/parcel#413]
Firstly, thanks for all the hard work on Parcel. I think this is going to be quite a force throughout 2018!

🙋 feature request

### 🎛 Configuration

N/A

### 🤔 Expected Behavior

Create-React-App has an error overlay that, when an error/warning occurs, shows details about the issue on the browser (overlaying the web app). Also this error is usually clickable, jumping straight to the file and line of the issue. I find this very useful and noticed I missed it when trying out Parcel. 

### 😯 Current Behavior

Error shown in terminal and browser console, but app remains in last good state.

### 💁 Possible Solution

I believe react-error-overlay uses webpack, so maybe that can be ported over to Parcel? Sorry, my knowledge of build tools isn't great. I'm sure this would be quite a project and I'm in no way asking for it to be added tomorrow; let's see if there's interest.

### 🔦 Context

Whilst the console errors are detailed, some users (and me) may tend to look to their browser first to see what has been affected by their code changes. This helps notify that an error has been found.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.3.1 |
| Node             | 9.3.0 |
| npm/Yarn         | Yarn 1.3.2 |
| Operating System | Windows/macOS |

**Comment by Faultless** [comment]
I think this is something most users will notice while setting up their first parcel project from scratch. Just yesterday one of my coworkers faced this minor inconvenience, being accustomed to the CRA way of developing React.

I'm looking into contributing to this project and this is a good place for me to help. I'll look into it.

**Comment by devongovett** [comment]
If we do this, we will not want the runtime to depend on a specific framework, like React. It should be plain JS.

**Comment by xpl** [comment]
I am now developing a plain JS alternative to `react-error-overlay` that could be used with Parcel:

https://github.com/xpl/panic-overlay

What do you think about that? I would be happy to see a feedback/contributions.
