### ISSUE TITLE
@parcel/validator-typescript fails with Error: Unexpected token export

### ISSUE THREAD

**Issue by astegmaier** [parcel-bundler/parcel#4136]
# 🐛 bug report

When I attempt to use `@parcel/validator-typescript`on a basic typescript project, parcel2 fails to build with `Error: unexpected token` (see below for the full message).

## 🎛 Configuration (.babelrc, package.json, cli command)

***.parcelrc:***
```js
{
    "extends": "@parcel/config-default",
    "validators": {
        "*.{ts,tsx}": ["@parcel/validator-typescript"]
    }
}
```
***Build script:*** `parcel build src/index.ts`

See [a sample project demonstrating the repo](https://github.com/astegmaier/parcel2-typescript-validator-bug) for more details.

## 🤔 Expected Behavior

Parcel2 should build the project. If I add a deliberate type error to `src/index.ts`, I should get a warning about it.

## 😯 Current Behavior

In all cases (with both valid and invalid typescript), I see this error:

```
$ parcel build src/index.ts
🚨 Build failed.
Error: Unexpected token export
/Users/Andrew/Projects/parcel2-typescript-validator-bug/node_modules/@parcel/ts-utils/src/index.js:2
export * from './FSHost';
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at NodePackageManager.load (/Users/Andrew/Projects/parcel2-typescript-validator-bug/node_modules/@parcel/package-manager/lib/NodePackageManager.js:112:9)
    at NodePackageManager.requireSync (/Users/Andrew/Projects/parcel2-typescript-validator-bug/node_modules/@parcel/package-manager/lib/NodePackageManager.js:78:17)
    at Module.m.require.id [as require] (/Users/Andrew/Projects/parcel2-typescript-validator-bug/node_modules/@parcel/package-manager/lib/NodePackageManager.js:99:19)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/Andrew/Projects/parcel2-typescript-validator-bug/node_modules/@parcel/validator-typescript/lib/TypeScriptValidator.js:14:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

```

## 💁 Possible Solution

Looking at the stack trace, the call before the error is this line in `<my-project>/node_modules/@parcel/validator-typescript/lib/TypeScriptValidator.js`
```
var _tsUtils = require("@parcel/ts-utils");
```
When I look at the `package.json` file in the installed package at `<my-project>/node_modules/@parcel/ts-utils/package.json`, I see:

```
{
  "name": "@parcel/ts-utils",
  "version": "2.0.0-alpha.3",
   ...
  "main": "src/index.js",
}
```
This is pointing at the un-transpiled `index.js` file. If I change `main` to `lib/index.js`, the error goes away, and everything starts to work.

When I look at the source code in the parcel repo, I see:

https://github.com/parcel-bundler/parcel/blob/9e4870b8c861134e45750671a84bee966eacbd8c/packages/utils/ts-utils/package.json#L12-L13

This looks correct, so there must be something in the build/publish step that is going wrong with this particular package.

## 🔦 Context

Trying to get parcel2 working end-to-end in a typescript-based project, and I'm super excited about using the built-in typechecker (with awesome error reporting 😃 )

## 💻 Code Sample

See [this sample project demonstrating the repo](https://github.com/astegmaier/parcel2-typescript-validator-bug).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.105
| Node             | 10.6.3
| Yarn         | 1.21.1
| Operating System | OSX 10.15.3

**Comment by astegmaier** [comment]
My bad - this issue is due to installing version `2.0.0-alpha.3` of `@parcel/validators`

However, when I update to the latest builds of `parcel` (`2.0.0-nightly.110`) and `@parcel/validator-typescript` (`2.0.0-nightly.112`), this error goes away, but instead I get a new problem: there's no errors displayed even when I have a type error in my source.

See new repro in [this branch](https://github.com/astegmaier/parcel2-typescript-validator-bug/tree/new-issue)

**Comment by DeMoorJasper** [comment]
Gonna close this as this was a known issue and has been fixed in v2 branch (and nightly releases)

**Comment by irskep** [comment]
It's still very easy to run into this if you naively `yarn install --dev @parcel/transformer-typescript-tsc`. I had to explicitly specify `2.0.0-beta.1`.

**Comment by jvidalv** [comment]
I know is wrong to post to say thanks, but you just saved an afternoon of pain @irskep , thanks.
