### ISSUE TITLE
Using Parcel with Globalize and multiple locales

### ISSUE THREAD

**Issue by dantman** [parcel-bundler/parcel#4140]
# ❔ Question

I'm looking into Parcel as people are recommending it over CRA, WebPack, etc. I would like to know what the "Parcel-way" to use Globalize would be.

## 🔦 Context

Globalize depends on data from CLDR, which there is a lot of, so you don't usually load every locale. With WebPack there are two ways I might use Globalize.

Method one would be to use `import` to async fetch data for different locales, e.g. ```import(`cldr/main/${locale}/numbers.json`)```. To avoid compiling hundreds of bundles that would never be used I'd use the IgnorePlugin to ignore the files from any locale other than the ones the application cares about.

Method two would be pre-compiling. globalize-compiler supports pre-compiling formatters as part of the build process, giving you your normal code but also a per-locale chunk that can be imported and contains the compiled code for the formatters you're using. The result is smaller code (only the runtime portion of Globalize is needed), smaller data (you don't import any cldr data, you only use the compiled code you need), and better performance (formatters don't need to be compiled client side). For this some people might use [globalize-webpack-plugin](https://www.npmjs.com/package/globalize-webpack-plugin). Which takes a list of supported languages and outputs a separate chunk for each locale with the compiled formatters.

As a complete hypothetical though, there is another way I might use Globalize if possible (it's not possible this way anywhere). In ESM import paths are treated like urls and different query arguments load separate instances of modules with separate urls in `import.meta.url`. There are also babel codegen/preval macros that allow generating the contents of modules. If it were at all possible, I would likely handle Globalize (pre-compiled or non-compiled) by doing a dynamic import like ```import(`./lang.js?locale=${locale}`)``` and in lang.js use a codegen/preval macro with the locale from `import.meta.url` to generate the necessary bundled json or compiled formatters at build time.

**Comment by TechQuery** [comment]
Here is a reference: https://web-cell.dev/WebCell/#internationalization
