### ISSUE TITLE
Feature: React Fast Refresh

### ISSUE THREAD

**Issue by bergkvist** [parcel-bundler/parcel#4144]
# React Fast Refresh
Inspired by: https://facebook.github.io/react-native/docs/fast-refresh

## 🤔 Expected Behavior
When changing a React (.jsx/.tsx) file, application state is preserved (whenever possible), and the changed component is swapped out without doing a window.reload().

## 😯 Current Behavior
When changing a React-file, the application is reloaded - resetting all state in the process.

## 💁 Possible Solution
[React fast refresh for webpack](https://github.com/pmmmwh/react-refresh-webpack-plugin) can be used as inspiration: 

## 🔦 Context
The goal of this is to improve developer experience - as the feedback loop between making a change and seeing the desired result becomes tighter for React development. This is good for productivity.

This idea is originally from 2015: [YouTube: Dan Abramov - Live React: Hot Reloading with Time Travel at react-europe 2015](https://www.youtube.com/watch?v=xsSnOQynTHs)

Recently, the React team themselves decide to create "React Fast Refresh" - which is already in use by React Native developers - and is making its way into create-react-app soon. [YouTube: React Developer tooling | Brian Vaughn](https://www.youtube.com/watch?v=Mjrfb1r3XEM)

## 💻 Examples
https://twitter.com/CompuIves/status/1214171786121793536

https://github.com/pmmmwh/react-refresh-webpack-plugin/tree/master/examples

**Comment by devongovett** [comment]
This is already implemented. In fact, Parcel was the first web bundler to do so. 😉 See https://twitter.com/devongovett/status/1195377210133106690?s=21

**Comment by bergkvist** [comment]
Oh, that explains why there wasn't even an issue about it!
