### ISSUE TITLE
[V2] Could build electron main bundle while renderer output is html

### ISSUE THREAD

**Issue by zcmgyu** [parcel-bundler/parcel#4149]
# 🐛 bug report

When I build electron main project, because of output type of electron renderer is `html`, so it became mismatch with output type of `main` is JS.

> yarn build

## 🎛 Configuration (.babelrc, package.json, cli command)

// package.js

```json
{
  "name": "parcel-demo",
  "version": "1.0.0",
  "license": "MIT",
  "main": "dist/main/index.js",
  "renderer": "dist/renderer/index.html",
  "targets": {
    "renderer": {}
  },
  "scripts": {
    "renderer:dev": "parcel ./src/renderer/index.html",
    "main:dev": "parcel ./src/main/index.js",
    "renderer:build": "parcel build ./src/renderer/index.html --target=renderer",
    "main:build": "parcel build ./src/main/index.js",
    "build": "yarn renderer:build && yarn main:build"
  }
}
```

## 🤔 Expected Behavior

I could build electron main and electron renderer without type mismatch problem.

## 😯 Current Behavior

Type mismatch

> 🚨 Build failed.
> @parcel/namer-default: Target "renderer" declares an output file path of "dist/renderer/index.html" which does not match the compiled bundle type "js".
> /Users/xxx/Documents/research/parcel-demo/package.json
> /Users/xxx/Documents/research/parcel-demo/package.json:6:15
>   5 |   "main": "dist/main/index.js",
> > 6 |   "renderer": "dist/renderer/index.html",
> >   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^ Did you mean "dist/renderer/index.js"?
>   7 |   "targets": {
>   8 |     "renderer": {}
> ℹ️ Hints:
> - Try changing the file extension of "renderer" in package.json.

## 💁 Possible Solution

No Idea

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2 |
| Node             | v11.13.0 |
| Yarn         | 1.17.3 |
| Operating System | macOS 10.15.1 |

**Comment by mischnic** [comment]
You could pass `--target=main` to the `main:*` scripts

**Comment by zcmgyu** [comment]
@mischnic Thanks a lot. It solved my issue. (bow)
