### ISSUE TITLE
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained

### ISSUE THREAD

**Issue by AaronJCunningham** [parcel-bundler/parcel#4167]
# ❔ Question

I keep getting the same error. "npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained..." Why is this happening?

## 🔦 Context

I actually tried this on both my laptops and I received the same error on both. One machine is WIndows 7, the other is Windows 10. 

I am using Visual Code Studio *latest version and Node.js *latest version.

I havent even started my project it is just an index.html, package.json, and thats all. I am trying to instal "npm install parcel-bundler" but I get the same message that my core-js is deprecated. I've tried updated the core-js which worked but I get the same message.

I already tried deleting the contents of appData/roaming/npm this did not work either.

## 💻 Code Sample

PS D:\Docs_Data\JS\test project> npm install parcel-bundler
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> parcel-bundler@1.12.4 postinstall D:\Docs_Data\JS\test project\node_modules\parcel-bundler
> node -e "console.log('\u001b[35m\u001b[1mLove Parcel? You can now donate to our open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/parcel/donate\u001b[0m')"

Love Parcel? You can now donate to our open collective:
 > https://opencollective.com/parcel/donate
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN test-project@1.0.0 No description
npm WARN test-project@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abbrev@1.1.1 (node_modules\fsevents\node_modules\abbrev):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\abbrev' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.abbrev.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ansi-regex@2.1.1 (node_modules\fsevents\node_modules\ansi-regex):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\ansi-regex' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.ansi-regex.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: aproba@1.2.0 (node_modules\fsevents\node_modules\aproba):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\aproba' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.aproba.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: balanced-match@1.0.0 (node_modules\fsevents\node_modules\balanced-match):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\balanced-match' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.balanced-match.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: chownr@1.1.3 (node_modules\fsevents\node_modules\chownr):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\chownr' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.chownr.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: code-point-at@1.1.0 (node_modules\fsevents\node_modules\code-point-at):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\code-point-at' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.code-point-at.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: concat-map@0.0.1 (node_modules\fsevents\node_modules\concat-map):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\concat-map' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.concat-map.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: console-control-strings@1.1.0 (node_modules\fsevents\node_modules\console-control-strings):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\console-control-strings' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.console-control-strings.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-util-is@1.0.2 (node_modules\fsevents\node_modules\core-util-is):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\core-util-is' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.core-util-is.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: deep-extend@0.6.0 (node_modules\fsevents\node_modules\deep-extend):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\deep-extend' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.deep-extend.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: delegates@1.0.0 (node_modules\fsevents\node_modules\delegates):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\delegates' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.delegates.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: detect-libc@1.0.3 (node_modules\fsevents\node_modules\detect-libc):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\detect-libc' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.detect-libc.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs.realpath@1.0.0 (node_modules\fsevents\node_modules\fs.realpath):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\fs.realpath' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.fs.realpath.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: has-unicode@2.0.1 (node_modules\fsevents\node_modules\has-unicode):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\has-unicode' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.has-unicode.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: inherits@2.0.4 (node_modules\fsevents\node_modules\inherits):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\inherits' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.inherits.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ini@1.3.5 (node_modules\fsevents\node_modules\ini):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\ini' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.ini.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: isarray@1.0.0 (node_modules\fsevents\node_modules\isarray):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\isarray' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.isarray.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@0.0.8 (node_modules\fsevents\node_modules\minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\minimist' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.minimist.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ms@2.1.2 (node_modules\fsevents\node_modules\ms):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\ms' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.ms.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: npm-normalize-package-bin@1.0.1 (node_modules\fsevents\node_modules\npm-normalize-package-bin):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\npm-normalize-package-bin' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.npm-normalize-package-bin.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: number-is-nan@1.0.1 (node_modules\fsevents\node_modules\number-is-nan):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\number-is-nan' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.number-is-nan.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: object-assign@4.1.1 (node_modules\fsevents\node_modules\object-assign):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\object-assign' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.object-assign.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-homedir@1.0.2 (node_modules\fsevents\node_modules\os-homedir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\os-homedir' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.os-homedir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-tmpdir@1.0.2 (node_modules\fsevents\node_modules\os-tmpdir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\os-tmpdir' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.os-tmpdir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: path-is-absolute@1.0.1 (node_modules\fsevents\node_modules\path-is-absolute):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\path-is-absolute' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.path-is-absolute.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: process-nextick-args@2.0.1 (node_modules\fsevents\node_modules\process-nextick-args):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\process-nextick-args' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.process-nextick-args.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@1.2.0 (node_modules\fsevents\node_modules\rc\node_modules\minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\rc\node_modules\minimist' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\rc\node_modules\.minimist.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safe-buffer@5.1.2 (node_modules\fsevents\node_modules\safe-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\safe-buffer' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.safe-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safer-buffer@2.1.2 (node_modules\fsevents\node_modules\safer-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\safer-buffer' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.safer-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sax@1.2.4 (node_modules\fsevents\node_modules\sax):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\sax' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.sax.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: semver@5.7.1 (node_modules\fsevents\node_modules\semver):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\semver' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.semver.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: set-blocking@2.0.0 (node_modules\fsevents\node_modules\set-blocking):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\set-blocking' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.set-blocking.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: signal-exit@3.0.2 (node_modules\fsevents\node_modules\signal-exit):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\signal-exit' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.signal-exit.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: strip-json-comments@2.0.1 (node_modules\fsevents\node_modules\strip-json-comments):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\strip-json-comments' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.strip-json-comments.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: util-deprecate@1.0.2 (node_modules\fsevents\node_modules\util-deprecate):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\util-deprecate' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.util-deprecate.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: wrappy@1.0.2 (node_modules\fsevents\node_modules\wrappy):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\wrappy' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.wrappy.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: yallist@3.1.1 (node_modules\fsevents\node_modules\yallist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\yallist' -> 'D:\Docs_Data\JS\test project\node_modules\fsevents\node_modules\.yallist.DELETE'

+ parcel-bundler@1.12.4
updated 1 package and audited 8601 packages in 94.637s
found 0 vulnerabilities
## 🌍 Your Environment

| Software         | Version(s) |
| Visual Code Studio  | 64bit 1.42.1 |
| Parcel           | 
| Node             | js 12.16.0
| npm/Yarn         |  npm
| Windows | 7 & 10

**Comment by chocolateboy** [comment]
See [here](https://github.com/parcel-bundler/parcel/issues/3308#issuecomment-559985900) for a fix/workaround.
