### ISSUE TITLE
Please change documentation to remove global install 

### ISSUE THREAD

**Issue by RichardJECooke** [parcel-bundler/parcel#417]
🙋 feature request

Your 'getting started' documentation recommends installing using the -global option. 

This is really bad practice because versions will differ over time as different developers try to setup the same project. It's better to install all packages locally in a project so their version numbers can stay in the package.json file, and so different versions of the same package can be used in different projects, which is impossible with global installations.

Please change the docs rather to remove the global option so parcel installs locally and then just use the line:
```
./node_modules/.bin/parcel index.html
```

**Comment by brandon93s** [comment]
Thanks for the suggestion. This really comes down to personal preference, and it may be better to highlight both the local and global installation in the docs. I agree a local installation would be preferred for a team or when working on multiple installations. For a quick "getting started", the global installation is quicker and easier for demonstration purposes though.

Feel free to continue the conversation on the website repo: https://github.com/parcel-bundler/website

**Comment by davorpeic** [comment]
Just for the future references, docs have been updated and local/per project information is in the docs. https://parceljs.org/getting_started.html#adding-parcel-to-your-project
