### ISSUE TITLE
Adding react and react-dom to package.json for no reason (?)

### ISSUE THREAD

**Issue by Oj18** [parcel-bundler/parcel#4183]
# 🐛 bug report

When running `> parcel index.html`, it adds `react` and `react-dom` to my package.json's dependencies, even though my project is not using react?

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`:
```json
{
  "name": "formuliser",
  "version": "13.0.0",
  "description": "Get info on chemical formulae.",
  "main": "code.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/oojmed/formuliser.git"
  },
  "keywords": [
    "chemistry",
    "webapp"
  ],
  "author": "Oojmed",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/oojmed/formuliser/issues"
  },
  "homepage": "https://github.com/oojmed/formuliser#readme",
  "devDependencies": {
    "parcel-bundler": "^1.12.4"
  },
  "dependencies": {
    "info": "0.0.6-beta.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  }
}
```

## 🤔 Expected Behavior

To not add them to the dependencies.

## 😯 Current Behavior

It's adding `react` and `react-dom` (and `info`?) to my dependencies when I don't use any of them.

## 💁 Possible Solution

Unknown.

## 🔦 Context

Just trying to split a static site into multiple JS files, it doesn't use React or any framework at all. (This might be intended behaviour but it doesn't seem like it?)

## 💻 Code Sample

My JS is just:
`js/app.js`:
```js
import { compoundLookup } from 'info/compounds';

console.log(compoundLookup);
```
`js/info/compounds.js`:
```js
export let compoundLookup = [
    { name: 'Water', formula: 'H2O' },
    { name: 'Glucose', formula: 'C6H12O6' }
];
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | parcel-bundler 1.12.4 |
| Node             | 13.8.0 |
| npm/Yarn         | npm 6.13.6 |
| Operating System | Arch Linux |

**Comment by mischnic** [comment]
(A workaround: `parcel --no-autoinstall`)

**Comment by leonm1** [comment]
I was able to duplicate this bug using the sample code.
