### ISSUE TITLE
🙋 Install peer dependencies of autoinstalled modules

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#419]
As a follow up to https://github.com/parcel-bundler/parcel/pull/239#discussion_r158898325, we need to potentially autoinstall peer dependencies of packages that are `localRequire`ed. e.g. `graphql-tag` has a peer dependency on `graphql` that won't be autoinstalled currently, but `graphql-tag` will. Users must manually fix by installing `graphql` in their projects.

**Comment by devongovett** [comment]
autoinstall code is here if you are interested in taking this issue: https://github.com/parcel-bundler/parcel/blob/master/src/utils/installPackage.js

**Comment by mannanali413** [comment]
@devongovett I would like to work on this. :)

**Comment by iamstratos** [comment]
Hello @mannanali413 do you have any updates on the issue?
