### ISSUE TITLE
How does parcel implement the unitless style value of Vue templates?

### ISSUE THREAD

**Issue by wspl** [parcel-bundler/parcel#4198]
# ❔ Question

I found that on webpack-based vue projects, the size value in the `: style` attribute needs to end with px. But it is not needed in parcel-based project. So I want to ask if this is the design of parcel, or does vue-template-compiler support unitless size?

## 🔦 Context
```vue
<div :style="{height: 100}">
```

**Comment by cdll** [comment]
i think it is an auto-transform logic of ``Number to String(with px)`` in js library as i known it is supported by ``Avalonjs`` at dynamic style binding directive; though i 'm now using ``rem`` unit system with ``Vuejs``.
