### ISSUE TITLE
Optimize loops 

### ISSUE THREAD

**Issue by pke** [parcel-bundler/parcel#42]
According to this https://jsperf.com/for-of-vs-for-loop for of loops are slower than the canonical loop in Javascript. Maybe it's worth a try to further increase performance of the tool. Once the compile bug on Windows is fixed I can give it a try

**Comment by thejameskyle** [comment]
I highly doubt this will have a noticeable impact on performance.

["microbenchmarks are evil" – jsPerf](https://twitter.com/jsperf/status/386195045206208512)
