### ISSUE TITLE
Can I import `.wasm` file as a public path?

### ISSUE THREAD

**Issue by Ajaxy** [parcel-bundler/parcel#4202]
# ❔ Question

How can I import `.wasm` file as a public path?

## 🔦 Context

I'm trying to get a public path to a `.wasm` file like I do for other assets, but I get it loaded and instantiated instead. I need the public path to provide it to a third-party library, that will later instantiate it.

## 💻 Code Sample

```ts
import OggOpusEncoderWasmPath from '../lib/opus-media-recorder/OggOpusEncoder.wasm';
```

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4

**Comment by mischnic** [comment]
This isn't possible with Parcel 1, but with Parcel 2 (`... from 'url:../lib/opus-media-recorder/OggOpusEncoder.wasm'`).

**Comment by Ajaxy** [comment]
> This isn't possible with Parcel 1, but with Parcel 2 (`... from 'url:../lib/opus-media-recorder/OggOpusEncoder.wasm'`).

@mischnic It didn't really help:

```ts
import OggOpusEncoderWasmPath from 'url:../lib/opus-media-recorder/OggOpusEncoder.wasm';
```

Still loads WASM as a module:

![image](https://user-images.githubusercontent.com/357153/75094999-c0694f00-5590-11ea-8e3d-7798afdcf368.png)

```sh
$ npx parcel --version
2.0.0-nightly.119
```

**Comment by Ajaxy** [comment]
@mischnic @wbinnssmith Can you reopen it or should I create a new issue?

**Comment by mischnic** [comment]
Parcel 2 doesn't support wasm at all yet, so this shouldn't be possible.

**Comment by mischnic** [comment]
I'm sorry, you're right.

**Comment by Ajaxy** [comment]
Is there any workaround for that? I tried to change the file extension, but that caused some other issues because the browser expects it to be exactly `.wasm`.

**Comment by mischnic** [comment]
Unfortunately not (the browser expects the WASM mime type and servers are configured to set that based on the extension), apart from copying the file manually into the dist dir.
I ran into this my self yesterday as well

**Comment by Ajaxy** [comment]
> apart from copying the file manually into the dist dir.

@mischnic Any idea how to do that in dev since there is no dist dir in v2?

**Comment by mischnic** [comment]
> Any idea how to do that in dev since there is no dist dir in v2?

There is, is `.parcel-cache/dist`

**Comment by Ajaxy** [comment]
Cool, will it be documented?

**Comment by mischnic** [comment]
Follow https://github.com/parcel-bundler/parcel/issues/3691 for that, maybe we move it somewhere else.

**Comment by mischnic** [comment]
I'm frankly not quite sure why but `import w from "url:./test.wasm";` works correctly in the current nightly. (`dependency.isAsync` is false for `url:`).

Importing a javascript asset via `url:` is still broken for a different reason.

**Comment by Ajaxy** [comment]
Nothing changed for me on `2.0.0-nightly.226`:

![image](https://user-images.githubusercontent.com/357153/79685886-57beeb80-823c-11ea-9b88-dcd5ddac1c61.png)

**Comment by Ajaxy** [comment]
Nvm, it worked after `.parcel-cache` cleanup. Thanks for the update.
