### ISSUE TITLE
@parcel/validator-typescript can report incorrect errors if you change multiple files at once

### ISSUE THREAD

**Issue by astegmaier** [parcel-bundler/parcel#4204]
# 🐛 bug report

In testing PR #4187 (which unblocks the ability of `@parcel/validator-typescript` to re-analyze files after they are saved), I discovered a pre-existing problem with the way that the validator handles re-analyzing projects in cases where multiple typescript files change at the same time. 

Thanks to @padmaia for asking [the right question](https://github.com/parcel-bundler/parcel/pull/4187#discussion_r382167489) to help uncover this.

## 🎛 Configuration (.babelrc, package.json, cli command)

***.parcelrc:***
```js
{
    "extends": "@parcel/config-default",
    "validators": {
        "*.{ts,tsx}": ["@parcel/validator-typescript"]
    }
}
```
***package.json:***
```
{
  "name": "parcel2-typescript-validator-bug",
  "version": "1.0.0",
  "main": "index.html",
  "private": true,
  "scripts": {
    "start": "parcel src/index.ts"
  },
  "devDependencies": {
    "@parcel/validator-typescript": "2.0.0-nightly.117", // In order to see this problem, you need to use a build created after #4187 is merged.
    "parcel": "2.0.0-nightly.115",
    "typescript": "3.7.5"
  }
}
```

***src/index.ts:***
```ts
import { showMessage } from "./showMessage";
const message: string= "A new Message!";
showMessage(message);
```

***src/myFunction.ts***
```ts
export function showMessage(message: string) {
    console.log(message);
}
```
## 🤔 Expected Behavior

When you start the above project with parcel (by running `parcel src/index.ts`), it should build with no warnings (because the initial types of both `index.ts` and `App.ts` are valid).

Now, change _both_ files (taking care to save them both at the same time) to:

***src/index.ts:***
```ts
import { showMessage } from "./showMessage";
const message: number = 123; // note the new type of 'number'
showMessage(message);
```

***src/myFunction.ts***
```ts
export function showMessage(message: number) { // we've also changed the type to 'number' here.
    console.log(message);
}
```
Parcel should rebuild the project successfully and not show any type errors (because there are none).

## 😯 Current Behavior

`@parcel/typescript-validator` will show:
```
🚨 Build failed.
@parcel/validator-typescript: Argument of type 'number' is not assignable to parameter of type 'string'.
/Users/Andrew/Projects/parcel2-typescript-validator-bug/src/index.ts
/Users/Andrew/Projects/parcel2-typescript-validator-bug/src/index.ts:3:13
  2 | const message: number = 123;
> 3 | showMessage(message);
>   |             ^^^^^^^^ Argument of type 'number' is not assignable to parameter of type 'string'.
  4 | 
```

## 💁 Possible Solution

[`TypeScriptValidator`](https://github.com/parcel-bundler/parcel/blob/v2/packages/validators/typescript/src/TypeScriptValidator.js) runs the `validate` method once for each file that changes. In order to make sure that the TypeScript `LanguageService` is updated about the changes, it needs to make an `invalidate()` call to the `LanguageServiceHost`, which ensures that when the `LanguageService` asks for that file, the it will inform the service about the changes. But because the `invalidate()` method for the _second_ file change changes is only run _after_ the first file is already analyzed, the first file's analysis is wrong (because it is based off the old version of the second file).

One idea of how to fix it would be: create some sort of queue that only calls the the `LanguageService` _after_ all the files that changed have been invalidated.

## 🔦 Context

Trying to get parcel2 working end-to-end in a typescript-based project, and I'm super excited about using the built-in typechecker (with awesome error reporting 😃 )

## 💻 Code Sample

See the `multiple-files-change-issue` branch of [this repo](https://github.com/astegmaier/parcel2-typescript-validator-bug/tree/multiple-files-change-issue) for a demonstration.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.115
| Node             | 10.6.3
| Yarn         | 1.21.1
| Operating System | OSX 10.15.3

**Comment by astegmaier** [comment]
This is turning into an extremely tricky bug to test and fix. I'm working on a PR right now, and here's the two things that are giving me heartburn:

1. ***Writing a Unit Test That Actually Catches the Problem*** Whether you see the bug or not depends on what order the files that are changed get validated, which is indeterminate. In the example above `index.ts` depends on `myFunction.ts`. Validation for all changed files is triggered through an array of promises that get executed simultaneously:

https://github.com/parcel-bundler/parcel/blob/870013cab1003cb422fd425af50c934407df9ecb/packages/core/core/src/AssetGraphBuilder.js#L211-L217

This is great for efficiency in production, but it means that a unit test that tries to catch the bug (and validate that it will remain fixed) will sometimes fail and sometimes succeed, depending on what promise gets executed first. (e.g. it will fail if the promise for `index.ts` goes first, and it will succeed if the promise for `myFunction.ts` goes first).

2. ***Actually Fixing The Problem*** It appears that the current contract with validator plugins expects them to be run one-at-a-time (through calling `async validate({asset})`). Because we currently cache instances of `TypeScriptLanguageHost` between calls to `validate()`, and whether a given file is valid can depend on the state of other files we can't, under the current contract, fix this without just assuming that all files in the project have changed any time one of them changes (which wouldn't be so great for efficiency).

I can think of ways that it might be possible to change the contract with validators to make it possible to fix this bug while still being efficient, but I'm not sure I know enough about the design intent of the contract to be able to suggest the optimal change. @DeMoorJasper / @padmaia - do you know the right people to bring into this conversation?

If it's helpful, I'm happy to share my WIP PR (which has a unit test displaying the behavior mentioning in point number 1 above).

**Comment by DeMoorJasper** [comment]
@astegmaier maybe 1 should be a queu instead of a promise.all, but that wouldn't really solve this issue as they can still resolve in a different order based on latency and validation time... unless we'd run queue's in the correct order when running with environment test, but that would probably slow down tests a lot. Maia probably has a more in depth knowledge of queues within parcel.

About fixing the problem I'm not sure, maybe we should send the entire array of assets that need to get validated to the validator at once. I don't even think it would give us a significant performance penalty.

Maybe it would be an idea to have a way to dedicate a worker to a validator pipeline, this way we could cache typechecking, linting, ... in memory. But that's definitely an optimisation that has no priority at all (if we'd move towards sending an array of assets)
