### ISSUE TITLE
Unsafe replacing of `typeof module`

### ISSUE THREAD

**Issue by Ajaxy** [parcel-bundler/parcel#4206]
# 🐛 bug report

Parcel replaces `typeof module` with `"object"` which leads to bugs when trying to later access `module` variable.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
  "browser": "build/index.html",
  "targets": {
    "browser": {
      "minify": false,
      "sourceMap": false
    }
  }
```

## 🤔Behavior

I have a [code](https://github.com/Ajaxy/parcel-bug-typeof-module/blob/master/index.js):
```js
console.log(
  typeof module !== 'undefined' && module.hasOwnProperty('exports'),
);
```

Which [gets bundled](https://github.com/Ajaxy/parcel-bug-typeof-module/blob/master/build/parcel-bug-typeof-module.ff3a3879.js) as:

```js
(function(){
// ASSET: /Users/zinchuk/Dev/parcel-bug-typeof-module/index.js
console.log("object" !== 'undefined' && module.hasOwnProperty('exports'));
})();
```

which leads to `Uncaught ReferenceError: module is not defined`.

## 💻 Code Sample

Isolated sample repo: https://github.com/Ajaxy/parcel-bug-typeof-module

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.119
| Node             | v12.13.0
| npm/Yarn         | 6.12.0
| Operating System | macOS 10.14.6

**Comment by mischnic** [comment]
cc @wbinnssmith

**Comment by wbinnssmith** [comment]
Related: #3933

**Comment by Ajaxy** [comment]
I noticed the same thing happens with `typeof require` and leads to equal bugs.

**Comment by mischnic** [comment]
The reason for this is that some older packages have a wrapper that checks verify whether `module` and `module.exports` exist before exporting themselves onto `module.exports` (to have one universal bundle for various module formats).

**Comment by devongovett** [comment]
Does this still happen in the latest nightly? I think we bail on non-statically analyzable module references now

**Comment by devongovett** [comment]
Verified that it works.
