### ISSUE TITLE
How to use with Nuxt.js (Vue.js)

### ISSUE THREAD

**Issue by Reechee88** [parcel-bundler/parcel#421]
Hi,

I would like to use awesome Parcel with my Vue.js project, especially with Nuxt.js. I am using Nuxt beacuse of SSR.

I know that Nuxt uses backpack and webpack for bundling, but I would be very happy to change it to Parcel.

How is it possible?

Thanks,
Richard

**Comment by devongovett** [comment]
This would probably need to be a change in Nuxt.js to swap out webpack for parcel under the covers.

**Comment by vampire624** [comment]
if using vue-server-render,  is that capable to realize SSR of Vue with Parcel?
