### ISSUE TITLE
Development server doesn't default to index.html when compiling with multiple files.

### ISSUE THREAD

**Issue by sinclairzx81** [parcel-bundler/parcel#4213]
# 🐛 bug report

When running the parcel development server, I note that index.html is not automatically resolved when browsing the root.

```bash
# run for all *.html files in the ./bench directory, output to ./target/bench.

$ parcel ./bench/*.html --out-dir ./target/bench --port 5000
```
```bash
http://localhost:5000/           # resolves 404 Not Found
http://localhost:5000/index.html # resolves 200 OK
```

## 🤔 Expected Behavior

The `index.html` file should be served if not explicitly passing a resource path (i.e. `http://<host>:<port>/`) or 404 if no `index.html` file exists. 

## 😯 Current Behavior

Returning a 404, even with index.html in the root.

## 🌍 Your Environment

Vanilla setup, using HTML, TypeScript files only.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 12.3.1
| npm         | 6.13.7
| Operating System | Windows

**Comment by DeMoorJasper** [comment]
This is actually a known bug, gonna close as it's a duplicate. This should have been fixed in Parcel 2
