### ISSUE TITLE
Scope hoisting: `import *` with re-exporting does not include all exports

### ISSUE THREAD

**Issue by wbinnssmith** [parcel-bundler/parcel#4216]
# 🐛 bug report

In the following case with scope hoisting enabled, using `import *` with the `@sentry/browser` package does not include all of its exports. This package re-exports quite a bit.

## 🎛 Configuration (.babelrc, package.json, cli command)

Defaults, `parcel2 build --no-minify`

## 🤔 Expected Behavior

All of the exports should be included when importing using `import *`

## 😯 Current Behavior

Only subset of exports is included.

## 💻 Code Sample

`yarn add @sentry/browser`

```js
import * as Sentry from '@sentry/browser';

Sentry.configureScope(scope => console.log('scope', scope));
console.log('Sentry', Sentry);
```

and build with `parcel2 build --no-minify index.js`

The above logs:
```
Sentry {
  Transports: {
    BaseTransport: [Function: BaseTransport],
    FetchTransport: [Function: FetchTransport],
    XHRTransport: [Function: XHRTransport]
  },
  Integrations: {
    FunctionToString: [Function: FunctionToString] { id: 'FunctionToString' },
    InboundFilters: [Function: InboundFilters] { id: 'InboundFilters' },
    GlobalHandlers: [Function: GlobalHandlers] { id: 'GlobalHandlers' },
    TryCatch: [Function: TryCatch] { id: 'TryCatch' },
    Breadcrumbs: [Function: Breadcrumbs] { id: 'Breadcrumbs' },
    LinkedErrors: [Function: LinkedErrors] { id: 'LinkedErrors' },
    UserAgent: [Function: UserAgent] { id: 'UserAgent' }
  }
}
```

...but should include `@sentry/browser`'s other exports, such as `configureScope` and `captureException`.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2 branch (04f2e662b571a9caba58363aa0ce3303a282e281)
| Node             | v12.16.1
| npm/Yarn         | yarn 1.21.1
| Operating System | macOS 10.15.3

**Comment by wbinnssmith** [comment]
cc @mischnic @devongovett

**Comment by mischnic** [comment]
Seems to be related to/caused by `sideEffects: false`

**Comment by mischnic** [comment]
`mod.meta.exportsIdentifier` is being inserted here, which refers to the reexporting asset which was excluded. It should instead be somehow resolved through to the actual asset.

https://github.com/parcel-bundler/parcel/blob/bb5ad3d1adaebb42514750b12d8f7470d66a7bd9/packages/shared/scope-hoisting/src/link.js#L342
