### ISSUE TITLE
SourceMapURL prefix or inline-source-map for Android Chrome Devtools

### ISSUE THREAD

**Issue by GimpMaster** [parcel-bundler/parcel#4226]
# 🙋 feature request

Hello, One of the issues with working with a framework like Cordova/PhoneGap is that we are dealing with an in-app browser based on chrome but loads its resources from a file:// URL. 

When the chrome devtools connects it attempts to find map files and then download them. However direct requests from Chrome devtools for the map files such as file://assets/www/js.1234.js.map fail giving you a cryptic error that Devtools failed to parse js1.234.js.map. In reality it just couldn't find it.

Webpack has solved this issue by allowing for inline-source-map that encodes the SourceMapURL to a data URL like:

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9u=

Another options that I have discovered that works is after parcel builds is to add a prefix to the file that is an http address where I am hosting the map files locally.

## 🤔 Expected Behavior

Ideally we would have a command line option where you can give a prefix or possibly a command line option to do inline source map files.

## 😯 Current Behavior

map files do not work with Chrome Dev tools in a cordova/phonegap/ionic app.

## 💁 Possible Solution

Commandline

## 🔦 Context

For now I'll just write a sed script that changes the sourceMapURL. However this would be a really nice feature.

## 💻 Examples

👉  https://opencollective.com/parcel/donate -->

**Comment by mischnic** [comment]
Already supported in Parcel 2 in the targets configuration: https://github.com/parcel-bundler/parcel#target-configuration:

```json5
{
  "targets": {
    "mytarget": {
      "sourceMap": {
        "sourceRoot": "prefix" // add a prefix, or
        "inline": true, // inline sourcemap itself
        "inlineSources": true // inline sources that sourcemap refers to
      }
    }
  }
}
```
