### ISSUE TITLE
feature request: Flow

### ISSUE THREAD

**Issue by mvolkmann** [parcel-bundler/parcel#423]
Does Parcel support stripping Flow types from code?

**Comment by brandon93s** [comment]
This would be handled by Babel, which parcel will run for you automatically. To strip flow types:

```shell
# Install Babel Transform
npm install --save-dev babel-plugin-transform-flow-strip-types
```

```js
// Add to .babelrc
{
  "plugins": ["transform-flow-strip-types"]
}
```

Reference: https://babeljs.io/docs/plugins/transform-flow-strip-types/

**Comment by mvolkmann** [comment]
Thanks Brandon!

**Comment by FDiskas** [comment]
This is production error in js file. :fu:
![error](https://i.imgur.com/jFeNbIE.png) :hocho:

**Comment by TrySound** [comment]
@FDiskas Show babel config.
