### ISSUE TITLE
ESLint couldn't find the config "../../../../.eslintrc.json"

### ISSUE THREAD

**Issue by QuantumInformation** [parcel-bundler/parcel#4230]
#  Question

Why is there a file that expects eslint file to be in a certain location?

{
  "extends": "../../../../.eslintrc.json"
}
from /node_modules/@parcel/fs/src/.eslintrc.json

gives us an error:

ESLint couldn't find the config "../../../../.eslintrc.json" to extend from. Please check that the name of the config is correct.

**Comment by hulkyhawk** [comment]
@QuantumInformation same problem encountered

i think, orignally this is to extend the config int the parcel directory.
unfortunately, when parcel-bundler is npm installed, there is no such direcotry then,
so eslint complains this erorr

**Comment by QuantumInformation** [comment]
still happens in new project, seems pretty urgent

**Comment by DeMoorJasper** [comment]
@QuantumInformation the eslint plugin is not an official parcel plugin, so it's kind of out of our control.

**Comment by QuantumInformation** [comment]
any ideas when 2.x will be published?
