### ISSUE TITLE
Nothing happens after source code change.

### ISSUE THREAD

**Issue by chen-xin** [parcel-bundler/parcel#424]
This a 🐛 bug report.

### 🎛 Configuration (.babelrc, package.json, cli command)

```
parcel index.html
```

### 🤔 Expected Behavior

After source code change, rebuild and print log to console, then reload page in browser.

### 😯 Current Behavior

Print "Built in xxxs" after running `parcel index.html`

Nothing happens after source html or js files change: no message printed, no new bundle generated, no reload in browser. 

index.html: 
```
<!DOCTYPE html>
<html>
    <body>
        <div class="header">
            <h1>222</h1>
        </div>
        <script src="bricks.js"></script>
    </body>
</html>    
```

brick.js:
```
console.log('111')
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.3.1
| Node             |8.9.3
| npm/Yarn         |5.6.0
| Operating System |Ubuntu 16.04

**Comment by DeMoorJasper** [comment]
This is a safe-write issue see #221

**Comment by chen-xin** [comment]
Thanks @DeMoorJasper !  It worked `:set backupcopy=yes` in vim.
