### ISSUE TITLE
Is it possible to enable module caching?

### ISSUE THREAD

**Issue by ramirofages** [parcel-bundler/parcel#4248]
# ❔ Question

How can I enable module caching so that I am able to create singletons?

## 🔦 Context

I'm working in the context of webgl applications, and I make good use of singleton classes for things like Input or Graphics ( to handle rendering specific stuff), but looks like due to HMR and a disabled module cache I can't create singletons like I would usually do:
```
class Input
{
	constructor()
	{
		
	}
}

export default new Input();
```

I have disabled HMR using the --no-hmr flag, but still didn't work so I was suspecting that maybe module caching is disabled, and thus everytime I import the Input module, a new instance gets created.

## 🌍 Your Environment

I'm using parcel 1

**Comment by mischnic** [comment]
ES6 imports are transpiled to `require`, and calling `require(foo)` multiple times *is* "cached".

Could you provide a more complete example?

**Comment by ramirofages** [comment]
Looks like I have found the problem while building a sample test. I have an index that imports two files, fileA and fileB. fileB sets some values in my singleton Input, and fileA reads those values. So it seems that they don't share this 'cache' when requiring files. Does it make sense?

**Comment by mischnic** [comment]
Like [this](https://parcel-repl.now.sh/#JTdCJTIyY3VycmVudFByZXNldCUyMiUzQSUyMkphdmFzY3JpcHQlMjIlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIybWluaWZ5JTIyJTNBdHJ1ZSUyQyUyMnNjb3BlSG9pc3QlMjIlM0FmYWxzZSUyQyUyMnNvdXJjZU1hcHMlMjIlM0FmYWxzZSUyQyUyMmNvbnRlbnRIYXNoJTIyJTNBdHJ1ZSUyQyUyMmJyb3dzZXJzbGlzdCUyMiUzQSUyMkNocm9tZSUyMDcwJTIyJTJDJTIycHVibGljVXJsJTIyJTNBJTIyJTIyJTJDJTIydGFyZ2V0JTIyJTNBJTIyYnJvd3NlciUyMiUyQyUyMmdsb2JhbCUyMiUzQSUyMiUyMiU3RCUyQyUyMmFzc2V0cyUyMiUzQSU1QiU1QiUyMmluZGV4LmpzJTIyJTJDJTIyaW1wb3J0JTIwYSUyMGZyb20lMjAlNUMlMjIuJTJGYSU1QyUyMiUzQiU1Q25pbXBvcnQlMjBiJTIwZnJvbSUyMCU1QyUyMi4lMkZiJTVDJTIyJTNCJTVDbiU1Q25hKCklM0IlNUNuY29uc29sZS5sb2coYigpKSUzQiUyMiUyQzElNUQlMkMlNUIlMjJhLmpzJTIyJTJDJTIyaW1wb3J0JTIwYyUyMGZyb20lMjAlNUMlMjIuJTJGY29tbW9uJTVDJTIyJTNCJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjAoKSUyMCUzRCUzRSUyMGMuc2V0KCklM0IlMjIlNUQlMkMlNUIlMjJiLmpzJTIyJTJDJTIyaW1wb3J0JTIwYyUyMGZyb20lMjAlNUMlMjIuJTJGY29tbW9uJTVDJTIyJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwKCklMjAlM0QlM0UlMjBjLmNoZWNrKCklM0IlMjIlNUQlMkMlNUIlMjJjb21tb24uanMlMjIlMkMlMjJjbGFzcyUyMFNpbmdsZXRvbiUyMCU3QiU1Q24lNUN0Y29uc3RydWN0b3IoKSUyMCU3QiU1Q24lNUN0JTVDdHRoaXMucmFuJTIwJTNEJTIwZmFsc2UlM0IlNUNuJTVDdCU3RCU1Q24lNUN0c2V0KCklN0IlNUNuJTVDdCU1Q3R0aGlzLnJhbiUyMCUzRCUyMHRydWUlM0IlNUNuJTVDdCU3RCU1Q24lNUN0Y2hlY2soKSU3QiU1Q24lNUN0JTVDdHJldHVybiUyMHRoaXMucmFuJTNCJTVDbiU1Q3QlN0QlNUNuJTdEJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBuZXclMjBTaW5nbGV0b24oKSUzQiUyMiU1RCU1RCU3RA==)?

**Comment by ramirofages** [comment]
Almost, this is how my index.html would look like:
```
		<script src="a.js"></script>
		<script src="b.js"></script>
```
the code you put in a,b, and common is correct

**Comment by mischnic** [comment]
I see, please take a look at https://github.com/parcel-bundler/parcel/issues/3575.
