### ISSUE TITLE
Compile esnext issue

### ISSUE THREAD

**Issue by LeonBeilis** [parcel-bundler/parcel#4251]
# 🐛 bug report

Hey, im using the latest parcel version that I have just installed to test it out
and I having issue with compiling js code that has esnext syntax, for example private variables in class:

×  X:\public\js\main.js:2390:4: Unexpected character '#' (2390:4)
  2388 |  */
  2389 | class TherapyUtils {
> 2390 |     #therapyType;
       |    ^
  2391 |     constructor(therapyType) {
  2392 |         this.#therapyType = therapyType;
  2393 |         this.attachSaveToMyPlanEvent();

the code works fine without a bundle, does any one had this issue and know how to fix?

package.json:
{
  "name": "x",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "parcel public/template/index.html",
    "build": "parcel build <your entry file>"
  },
  "repository": {
    "type": "git",
    "url": "git+ssh://git@x.git"
  },
  "keywords": [],
  "author": "x",
  "license": "ISC",
  "homepage": "https://bitbucket.org/x#readme",
  "devDependencies": {
    "parcel-bundler": "^1.12.4"
  }
}

**Comment by mischnic** [comment]
You have to use the plugin https://babeljs.io/docs/en/babel-plugin-proposal-private-methods
