### ISSUE TITLE
[v2] Does entry point default to package.json#source?

### ISSUE THREAD

**Issue by stefanprobst** [parcel-bundler/parcel#4253]
# ❔ Question

According to the README for v2, the default entry point should be [`package.json#source`](https://github.com/parcel-bundler/parcel#entries). However, the CLI will bail early when no entries were provided, see: 

https://github.com/parcel-bundler/parcel/blob/e8a4b8b7e54c33c38c6702e1c5b03f93af7a58bc/packages/core/parcel/src/cli.js#L168-L171

Which is correct?

## 💻 Code Sample

`package.json`:

```json
{
  "name": "parcel-2",
  "version": "1.0.0",
  "main": "dist/index.js",
  "source": "src/index.js",
  "license": "MIT",
  "devDependencies": {
    "parcel": "^2.0.0-nightly.131"
  },
  "scripts": {
    "build": "parcel build",
    "start": "parcel"
  }
}
```

Output:

```sh
yarn run v1.22.0
$ parcel build
No entries found
Done in 0.35s.
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.131
| Node             | 12.16.1
| npm/Yarn         | yarn 1.22
| Operating System | Ubuntu 18.04

**Comment by mischnic** [comment]
Providing the folder to the package(s) (`parcel build .`) will do what you want. This is more robust than using the cwd.
