### ISSUE TITLE
[v2] Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found  on Netlify

### ISSUE THREAD

**Issue by sw-yx** [parcel-bundler/parcel#4254]
# 🐛 bug report

It seems that a required version of libstdc is not available on Netlify. this is the error:

```bash
7:32:49 PM: Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /opt/build/repo/node_modules/@parcel/fs/node_modules/@parcel/watcher/build/Release/watcher.node)
7:32:49 PM:     at bindings (/opt/build/repo/node_modules/bindings/bindings.js:112:48)
7:32:49 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/@parcel/fs/node_modules/@parcel/watcher/index.js:1:36)
7:32:49 PM: error Command failed with exit code 1.
7:32:49 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Here is deploy log and repo
- https://app.netlify.com/sites/rincewind/deploys/5e5da58ba206e82095668599
- https://github.com/sw-yx/rincewind-demo

Dependencies used:

```js
"dependencies": {
    "@oclif/command": "^1",
    "@oclif/config": "^1",
    "@oclif/plugin-help": "^2",
    "@parcel/config-default": "^2.0.0-nightly.131",
    "@parcel/core": "^2.0.0-nightly.131",
    "@parcel/fs": "^2.0.0-nightly.131",
    "@parcel/package-manager": "^2.0.0-nightly.131",
    "@parcel/watcher": "^2.0.0-alpha.5",
}
```

## 🤔 Expected Behavior

should work like it does on my machine 😅 

## 🔦 Context

I can see that there was an attempted fix in @parcel/watcher alpha.5 https://github.com/parcel-bundler/watcher/issues/18 but it doesnt seem to have propagated properly, or the fix plain doesnt work

I am also writing a wrapper CLI around parcel so that might complicate things, however it doesn't seem like that's technically relevant.

anyway i didnt see other issues citing this libstdc error when I searched, so leaving this to leave a trail for others to follow. Let me know if there's something we shoudl add to the netlify build image: https://github.com/netlify/build-image/

**Comment by DeMoorJasper** [comment]
That’s pretty strange we build the watcher on centos 7 which should have a way older libc than ubuntu which you’re using at netlify. Will look into it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DeMoorJasper** [comment]
Looked at it and couldn't figure out how to get the netlify dockerimage to work,it seems like it's using an old yarn version that does not allow the `parcel` engines field.

<img width="1060" alt="Screenshot 2020-03-03 at 17 41 49" src="https://user-images.githubusercontent.com/2175521/75798024-46964a00-5d76-11ea-8a6c-6b6700f7b635.png">

**Comment by sw-yx** [comment]
@DeMoorJasper i dont think so - i also saw those errors - you can control what yarn version Netlify uses by setting environment variable YARN_VERSION to whatever, like 1.19.0. i did that in my deploy log above ([you should be able to see](https://app.netlify.com/sites/rincewind/deploys/5e5da58ba206e82095668599))

I'm not knowledgeable at all about libstdc and centos/ubuntu type issues so.. I'm not really sure what else I can do here haha. but i do know that @parcel/watcher alpha 5 was supposed to fix it, and i tried it, and as far as i can tell, it doesnt work yet, and/or it's not included in @parcel/fs@nightly.

**Comment by mischnic** [comment]
> and i tried it, and as far as i can tell, it doesnt work yet, and/or it's not included in @parcel/fs@nightly.

According to your lockfile, 

https://github.com/sw-yx/rincewind-demo/blob/68c5513277d0c2b3a36d0652cdba7432a5a58431/yarn.lock#L1688
https://github.com/sw-yx/rincewind-demo/blob/68c5513277d0c2b3a36d0652cdba7432a5a58431/yarn.lock#L2223

`@parcel/fs` is using `@parcel/watcher` alpha 4

**Comment by DeMoorJasper** [comment]
Just tried again with tweaking `./test-tools/test-build.sh` and YARN_VERSION 1.22 and don't seem to have any errors at all, might be the lockfile

**Comment by sw-yx** [comment]
ok so it sounds like i need to delete the lockfile then. sorry if this is false alarm.
