### ISSUE TITLE
Error if package#source == package#main or package#module

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#4255]
# 🐛 bug report

Parcel 2 shouldn't overwrite the source in these situations:

```json
{
	"module": "src/index.js",
	"source": "src/index.js"
}
```

`parcel build .`

---

```json
{
	"main": "src/index.js",
}
```

`parcel build src/index.js`

**Comment by JessieFrance** [comment]
Hello Parcel Friends. I think I found a place in the asset graph request code where we can implicitly detect these types of package.json configurations and either (1) rename the target so it doesn't overwrite the source, or (2) throw an informative error with a link to relevant Parcel 2 package.json configurations. Does this overall approach and/or one of the two strategies in particular sound good? If so, may I please work on this issue? :)

**Comment by ProLoser** [comment]
I feel like you should pick 1, not use the same point of entry for 3 different runtimes
