### ISSUE TITLE
Parcel v2: [Error: Error opening directory] from @parcel/watcher

### ISSUE THREAD

**Issue by somuchgoldy** [parcel-bundler/parcel#4256]
# 🐛 bug report

Hey, I am getting a [Error: Error opening directory] after building (even with no config at all) that I've been able to trace to @parcel/watcher 

## 🎛 Configuration (.babelrc, package.json, cli command)

No configuration at all (besides default package.json), just a simple `yarn parcel build ./a/index.js`

## 🤔 Expected Behavior

Parcel should work without giving me the error

## 😯 Current Behavior

Parcel is compiling successfully, but giving an error

```
parcel build ./a/index.js
√ Built in 1.38s

dist\index.js     0 B      5ms
└── a\index.js    5 B    3.16s
[Error: Error opening directory]
error Command failed with exit code 1.
```

## 💻 Code Sample

`parcel build ./a/index.js`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2@next
| Node             | 13.8.0
| npm/Yarn         | Latest
| Operating System | Windows 10 Pro

**Comment by mischnic** [comment]
🤔 https://github.com/parcel-bundler/watcher/blob/a66e9eb3aa68e9d83a6167c89796318727fff51b/src/windows/WindowsBackend.cc#L30

**Comment by raph-of-burgondy** [comment]
Hi. I have the same error with parcel V2 when building . 
No error occures when serving.
Any idea how to solve it :( ??

> √ Built in 64.66s

> dist\index.html             1.15 KB    36.89s

> dist\index.c53792e2.js     17.08 KB    35.88s

> dist\worker.003b44f7.js     2.95 KB    34.66s

> **[Error: Error opening directory]**

> npm ERR! code ELIFECYCLE

> npm ERR! errno 1

> npm ERR! mandco@1.0.0 build: `parcel build`

> npm ERR! Exit status 1

> npm ERR!

> npm ERR! Failed at the mandco@1.0.0 build script.

> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by NLumpov** [comment]
Same problem, parcel V2
```
> parcel build src/pages/index/index.pug

√ Built in 2.50s

dist\index.html    160 B    865ms
[Error: Error opening directory]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! parcel-lading-config@1.0.0 build: `parcel build src/pages/index/index.pug`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the parcel-lading-config@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2022-03-29T09_06_21_709Z-debug.log

Process finished with exit code 1

**Comment by carafizi1** [comment]
For those trying to find a solution: 

1) Try removing any special characters from the path (i.e.: language-specific punctuation like C://Users/Fulano/OneDrive/**Á**rea de Trabalho)

2) Remove the source-code folder from OneDrive.

**Moving the repository to the root of `C://` fixed the issue for me**

**Comment by jekiekolya** [comment]
Try add " **--no-cache**" 

for example: 
**BEFORE:**
"scripts": {
    "start": "parcel src/*.html",
    "build": "parcel build src/*.html --public-url /XXXXX/"
  },

**AFTER:**
"scripts": {
    "start": "parcel src/*.html **--no-cache**",
    "build": "parcel build src/*.html --public-url /XXXXX/ **--no-cache**"
  },

**Comment by Evangeliont** [comment]
> For those trying to find a solution:
> 
> 1. Try removing any special characters from the path (i.e.: language-specific punctuation like C://Users/Fulano/OneDrive/**Á**rea de Trabalho)
> 2. Remove the source-code folder from OneDrive.
> 
> **Moving the repository to the root of `C://` fixed the issue for me**

Your version helped me! Thanks

**Comment by Joothika** [comment]
> For those trying to find a solution:
> 
> 1. Try removing any special characters from the path (i.e.: language-specific punctuation like C://Users/Fulano/OneDrive/**Á**rea de Trabalho)
> 2. Remove the source-code folder from OneDrive.
> 
> **Moving the repository to the root of `C://` fixed the issue for me**

Thanks a lot.. I was facing this issue for 2hrs. Finally solved!!!
