### ISSUE TITLE
[Parcel 2] How do I build an entire folder

### ISSUE THREAD

**Issue by Yu02** [parcel-bundler/parcel#4261]
# ❔ Question

In V1, I was able to run `parcel build web/src/** --out-dir web/dist`, How can this be done in V2?

I want to accomplish this using the config, but the documentation is very unclear

**Comment by mischnic** [comment]
`parcel build web/src/**` should still work

**Comment by Yu02** [comment]
@mischnic I also need a custom dist directory

**Comment by mischnic** [comment]
Have you tried something like this in package.json ?
```json
{
  "targets": {
    "default": {
      "distDir": "web/dist"
    }
  }
}
```

**Comment by Yu02** [comment]
```
"targets": {
    "app": {
      "context": "browser",
      "publicUrl": "/content",
      "distDir": "client/dist",
      "sourceMap": {
        "inlineSources": true
      },
      "engines": {
        "browsers": [
          "last 3 Chrome versions"
        ]
      }
    }
``` 
Seems to be compiling to /dist instead of my custom directory

**Comment by Yu02** [comment]
Seems to work, thanks!

**Comment by Yu02** [comment]
Neverm
