### ISSUE TITLE
Can't import the same library in 2 JSX files

### ISSUE THREAD

**Issue by Yu02** [parcel-bundler/parcel#4262]
# 🐛 bug report

Trying to import the same library (React for example) in 2 different JSX files and compiling the entire parent directory causes a `@parcel/namer-default: Bundle group cannot have more than one entry bundle of the same type` error.

## 🎛 Configuration (.babelrc, package.json, cli command)

Default Config

## 🤔 Expected Behavior

Parcel should compile the directory

## 😯 Current Behavior
Parcel returns an error: 
```
@parcel/namer-default: Bundle group cannot have more than one entry bundle of the same type
```

## 💻 Code Sample
Create 2 JSX Files and put the following code inside them: 
```jsx
import React from 'react';
import RDom from 'react-dom';

RDom.render(<h1>Hi</h1>,document.querySelector("body"))
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.133+d665d06c
| Node             | v12.11.0
| npm/Yarn         | Latest
| Operating System | Windows 10 Enterprise

**Comment by mischnic** [comment]
> compiling the entire parent directory

What do you mean by that?

**Comment by Yu02** [comment]
@mischnic Simply running ```parcel build client/src/*/**```

**Comment by mischnic** [comment]
Working for me:
```js
$ parcel2 build src/*
✨ Built in 4.75s

dist/a.js                                                     127.52 KB      15ms
├── node_modules/react-dom/cjs/react-dom.production.min.js    264.02 KB     3.34s
├── node_modules/scheduler/cjs/scheduler.production.min.js     17.71 KB     222ms
├── node_modules/react/cjs/react.production.min.js             17.25 KB     3.34s
├── node_modules/object-assign/index.js                          2.6 KB     132ms
├── node_modules/react-dom/index.js                             1.54 KB     4.05s
├── node_modules/scheduler/index.js                               325 B      83ms
├── node_modules/react/index.js                                   308 B     4.05s
└── src/a.js                                                      293 B    12.10s

dist/b.js                                                     127.52 KB       5ms
├── node_modules/react-dom/cjs/react-dom.production.min.js    264.02 KB     3.34s
├── node_modules/scheduler/cjs/scheduler.production.min.js     17.71 KB     222ms
├── node_modules/react/cjs/react.production.min.js             17.25 KB     3.34s
├── node_modules/object-assign/index.js                          2.6 KB     132ms
├── node_modules/react-dom/index.js                             1.54 KB     4.05s
├── node_modules/scheduler/index.js                               325 B      83ms
├── node_modules/react/index.js                                   308 B     4.05s
└── src/b.js                                                      291 B    12.10s
```

**Comment by Yu02** [comment]
Try doing it inside of a sub-directory so the files will be in src/js/a.jsx and src/js/b.jsx

**Comment by Yu02** [comment]
Huh, for some reason a quick restart of the computer solved it.. weird

**Comment by JackHowa** [comment]
having the same issue https://github.com/JackHowa/whereami-w3w
