### ISSUE TITLE
Optimization trimming too much

### ISSUE THREAD

**Issue by ranisalt** [parcel-bundler/parcel#4268]
# 🐛 bug report

The optimization pass (I guess) is removing way too much code to the point it breaks and does not run.

## 🎛 Configuration (.babelrc, package.json, cli command)

Defaults, running `parcel build index.html` and monitoring this file:

```ts
import { shade, tint } from 'polished';

const funcs = [
	tint(0.66667),
	tint(0.46875),
	tint(0.29167),
	tint(0.13542),
	(x: string) => x,
	shade(0.11458),
	shade(0.20833),
	shade(0.28125),
	shade(0.33333),
];
export const colorscheme = (color: string) => funcs.map(fn => fn(color));
```

## 🤔 Expected Behavior

It should export the same calls to `shade` and `tint` with mangled names.

## 😯 Current Behavior

This code is generated:
```
    var wj = [{}(.66667), {}(.46875), {}(.29167), {}(.13542), function(e) {
        return e
    }
    , {}(.11458), {}(.20833), {}(.28125), {}(.33333)]
      , Ej = function(e) {
        return wj.map((function(t) {
            return t(e)
        }
        ))
    };
```

So it is replacing every call of `shade` and `tint` with `{}`, thus giving `Uncaught TypeError: {} is not a function`. The identity function is correctly translated.

The intriguing part is that using `serve` instead of `build` generates working code, which works properly, somehow. So I'm guessing it's some type of optimization.

## 🌍 Your Environment

I am using typescript, it might be an issue with the generated code from typescript compiler.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.137
| Node             | 13.9
| npm/Yarn         | 1.22
| Operating System | Arch Linux

**Comment by mischnic** [comment]
Please provide a complete (minimal) reproduction (babel/typescript config, source file[s]).
