### ISSUE TITLE
Fails when importing an NPM package with a dot in the name

### ISSUE THREAD

**Issue by ivanvillacreative** [parcel-bundler/parcel#427]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
🐛

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "timesheet",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "parcel src/index.html"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "bulma": "^0.6.1",
    "node-sass": "^4.7.2",
    "parcel-bundler": "^1.3.0"
  },
  "dependencies": {
    "easytimer.js": "^2.0.0",
    "jquery": "^3.2.1",
    "uuid": "^3.1.0"
  }
}
```

### 🤔 Expected Behavior

When I import a npm package with a . in the name "easytimer.js", Parcel should load that package from the node_modules

### 😯 Current Behavior

Parcel looks for the js property of easytimer object, and fails.
<img width="901" alt="screen shot 2017-12-28 at 1 33 28 pm" src="https://user-images.githubusercontent.com/9972541/34424276-3080d3f6-ebd7-11e7-9f54-105daf747d18.png">

### 💁 Possible Solution

I'm a beginner, but my guess is if Parcel could reference the node modules installed, if it found a name match, then it could skip trying to do more and just load that module.

### 🔦 Context

I'm just trying to load a npm package

### 💻 Code Sample

https://github.com/ivanvillacreative/timesheet/tree/timer

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.3.0
| Node             | 8.9.3
| npm/Yarn         | 5.6.0
| Operating System | mac high sierra 10.13.2

**Comment by DeMoorJasper** [comment]
Can't reproduce after using v1.4.1 and running
``npm install babel-preset-env --save-dev``
