### ISSUE TITLE
npm install fail: @parcel/transformer-sugarss@2.0.0-nightly.137 no matching version found

### ISSUE THREAD

**Issue by g4rick** [parcel-bundler/parcel#4270]
# 🐛 bug report

just `npm install --save-dev parcel@next` 
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @parcel/transformer-sugarss@2.0.0-nightly.137
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@parcel/config-default'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rick/.npm/_logs/2020-03-05T10_30_52_173Z-debug.log
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
    "browserslist": [
    "> 0.2%",
    "not dead"
  ],
  "devDependencies": {
    "eslint": "^6.8.0",
    "eslint-config-airbnb-base": "^14.0.0",
    "eslint-plugin-import": "^2.20.1",
    "parcel": "2.0.0-alpha.3.2"
  }
```

## 🔦 Context

I can use yarn add different version to use
```
Couldn't find any versions for "@parcel/transformer-sugarss" that matches "2.0.0-nightly.137+a07a8b84"
? Please choose a version of "@parcel/transformer-sugarss" from this list: (Us
e arrow keys)
❯ 2.0.0-nightly.135
  2.0.0-nightly.133
```

But in my customer's servers will fail because they use npm.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-alpha.3.2 |
| Node             | 11.14.0 |
| npm/Yarn         |  npm 6.7.0 |
| Operating System | mac & linux |

**Comment by mischnic** [comment]
I think this is some sort of caching problem, yarn just installed `@parcel/transformer-sugarss@2.0.0-nightly.137` for me.

**Comment by g4rick** [comment]
> I think this is some sort of caching problem, yarn just installed `@parcel/transformer-sugarss@2.0.0-nightly.137` for me.

What about using npm?  Does it work?

**Comment by g4rick** [comment]
Now work, don`t know why. Close.
