### ISSUE TITLE
Calling an imported `wasm` function blocks window `load` listener.

### ISSUE THREAD

**Issue by lgarron** [parcel-bundler/parcel#4278]
# 🐛 bug report

Consider this code (a simplified version of https://github.com/lgarron/parcel-wasm-window-load-bug):

    import { add } from "./add.wasm";
    console.log(add(3, 4));
    window.addEventListener("load", () => {
      console.log("window loaded!");
    });

`window loaded!` should appear in the console, but it doesn't. However, if you remove the call to `add` on line 2, then the listener gets called.

## 🎛 Configuration (.babelrc, package.json, cli command)

Reproduces with no configuration (see code sample below).

## 🤔 Expected Behavior

The `load` listener for `window` gets called regardless of whether `wasm` functions are used in the file.

## 😯 Current Behavior

The listener isn't called.

## 💻 Code Sample

See here:

    git clone https://github.com/lgarron/parcel-wasm-window-load-bug
    cd parcel-wasm-window-load-bug/
    parcel serve index.html

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4 |
| Node             | v13.10.1 |
| npm/Yarn         | 6.13.7 |
| Operating System | macOS 10.15.3 |

**Comment by mischnic** [comment]
Very strange
