### ISSUE TITLE
how to use with es7 

### ISSUE THREAD

**Issue by sowdf** [parcel-bundler/parcel#428]
```javascript
@isAnimal
class Monkey{
    toString(){}
}
console.log(Monkey.isAnimal);
```
⏳  Building...
⏳  Building androidMobile.js...🚨  /Users/caozhihui/Documents/JobCode/web/module/androidMobile/resource/dev/js/androidMobile.js:8:0: Unexpected token (8:0)   6 | }
   7 | 
>  8 | @isAnimal
     | ^
   9 | class Monkey{
  10 |     toString(){}
  11 | }

**Comment by thejameskyle** [comment]
You need to configure Babel through the `.babelrc` to support syntax extensions

**Comment by sowdf** [comment]
how to wtite . babelrc

**Comment by sowdf** [comment]
it is .babelrc 

```javascript
{
  "presets": ["env","es2017"]
}

```
