### ISSUE TITLE
V2: watch command should (optionally?) start HMR server

### ISSUE THREAD

**Issue by wis** [parcel-bundler/parcel#4284]
# 🐛 bug report
it looks like in Parcel 2, unlike Parcel 1 the `watch` command doesn't start a HMR server despite the mention of `--hmr-port` and `--hmr-host` in the output of `parcel watch --help`

## 🎛 Configuration (.babelrc, package.json, cli command)
`parcel watch index.html --public-dir './'`

## 🤔 Expected Behavior
Parcel V2's watch command should have the option to start a HMR server like the serve command and V1's watch command.

## 😯 Current Behavior
no option to start HMR server with the watch command.

also when using `--hmr-port` and `--hmr-host` with the watch command as described in its help page,
the parser doesn't accept them:
```
error: unknown option `--hmr-port'
error: unknown option `--hmr-host'
```

## 💁 Possible Solution
add the option or make it default behavior to start HMR server and no HTTP server with the watch command.

## 🔦 Context
as I [explained](https://github.com/parcel-bundler/parcel/issues/4186#issuecomment-596039229) in issue #4186, I'm developing a WebExtension with Parcel V2 and React and I'm trying to get the awesome default support for Fast Refresh of Parcel V2 to work with web pages not served from a server.

## 💻 Code Sample
**index.html**:
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <base href=".">
        <title>📦 Parcel</title>
    </head>
    <body>
        <noscript>You nttneed to enable JavaScript to run this application 😰</noscript>
        <div id="app"></div>

        <script src="./src/index.tsx"></script>
    </body>
</html>
```
**src/index.tsx**:
```js
import * as React from "react";
import { render } from "react-dom";
import { Componentx } from "./componentx";

class App extends React.Component {
  render() {
    return (
      <>
        <Componentx></Componentx>
      </>
    );
  }
}

render(<App />, document.getElementById("app"));
```
**src/componentx**:
```js
import React from "react";
export function Componentx() {
  return (
    <>
      <div>hello good world! </div>
    </>
  );
}
```

## 🌍 Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | v13.9.0
| npm/Yarn         | 1.22.0
| Operating System | Linux arch-linux-pc 5.5.7-arch1-1 #1 SMP PREEMPT Sat, 29 Feb 2020 19:06:02 +0000 x86_64 GNU/Linux

**Comment by mischnic** [comment]
👍 
This usecase was simply forgotten in https://github.com/parcel-bundler/parcel/pull/3918.

**Comment by mischnic** [comment]
Fixed by https://github.com/parcel-bundler/parcel/pull/4417
