### ISSUE TITLE
npm security report from Acorn dependency

### ISSUE THREAD

**Issue by cliffordp** [parcel-bundler/parcel#4289]
# 🐛 bug report

`npm audit` findings

## 🤔 Expected Behavior

No security warnings.

## 😯 Current Behavior

![image](https://user-images.githubusercontent.com/1812179/76157065-9b64f800-60c9-11ea-8e2e-c17d1319058d.png)

## 🌍 Your Environment

`"parcel-bundler": "^1.12.4"`

**Comment by mischnic** [comment]
There really isn't anything we can do here.
Parcel's direct dependencies that are transitively causing this (grapheme-breaker and htmlnano) are on the latest version.
