### ISSUE TITLE
🙋 Make htmlnano configurable for production builds

### ISSUE THREAD

**Issue by Pittan** [parcel-bundler/parcel#429]
### 🤔 Expected Behavior

To be able to pass options to `htmlnano`.  Just like https://github.com/parcel-bundler/parcel/issues/347 did.

```
{
    minifySvg: false
}
```

### 😯 Current Behavior

Not able to pass any options.

### 🔦 Context
My SVG file written in HTML is already optimized by svgo (but not to remove `viewBox`).
Using production build on parcel removes viewBox from SVGs.

**Comment by thejameskyle** [comment]
There doesn't appear to be a standard config file for htmlnano

**Comment by Olian04** [comment]
@thejameskyle if htmlnano takes an options object in its constructor, we could use that as the configuration file pattern?

**Comment by devongovett** [comment]
We've been following this pattern for supported file names when a standard one isn't available: `.htmlnanorc`, `.htmlnanorc.js`.

**Comment by Pittan** [comment]
@devongovett Thank you!! You saved my life:)

**Comment by gurmukhp** [comment]
Hi,

Please can you share an example of how to ensure viewbox doesn't get removed?

**Comment by albertorestifo** [comment]
I too am incurring the same issue as @gurmukhp, any solution?

**Comment by bfred-it** [comment]
@gurmukhp @albertorestifo 

I think you can change svgo's config by creating a `.svgo.yml` file in the folder where `parcel` runs. I think it would be:

```yml
plugins:
  - removeViewBox: false
```

**Comment by ikniaziuk** [comment]
Just create `.htmlnanorc` file in the root folder of the project and write:

```
{
  minifySvg: false,
}
```
It will save viewbox attr.

**Comment by jaydickinson** [comment]
Doesn't work? anyone actually have a solution that works for this really frustrating just want to turn off the viewbox on minify... 

tried creating the .htmlnanorc and adding 
`{
  minifySvg: false,
}`

but nothing changes?

**Comment by hesselbom** [comment]
@jaydickinson I had the exact same problem. What solved it for me was to `rm -rf .cache` and then rebuilding.

**Comment by WazzaMo** [comment]
When using parcel, to see the effect of adding `.htmlnanorc.js` you need to remove the `.cache` directory and do a full rebuild.
My `.htmlnanorc.js` is as follows:
```js
module.exports = {
  "minifySvg": false
}
```
I confirmed that it was loaded by doing a console.log() in this .js file, and this only appeared after deleting the .cache and also that's when my SVG appeared correctly.

**Comment by Amy-tech** [comment]
Thankyou so much WazzaMo
your solution worked for me XD so happy

**Comment by Amy-tech** [comment]
> When using parcel, to see the effect of adding `.htmlnanorc.js` you need to remove the `.cache` directory and do a full rebuild.
> My `.htmlnanorc.js` is as follows:
> 
> ```js
> module.exports = {
>   "minifySvg": false
> }
> ```
> 
> I confirmed that it was loaded by doing a console.log() in this .js file, and this only appeared after deleting the .cache and also that's when my SVG appeared correctly.

Thankyou so much WazzaMo
your solution worked for me XD I am so happy
