### ISSUE TITLE
HMR not working with `--https` and Firefox

### ISSUE THREAD

**Issue by Feirell** [parcel-bundler/parcel#4291]
# 🐛 bug report

Using the `--https` flag with parcel serve results in Firefox not being able to connect to the hmr WebSocket port.

## 🎛 Configuration (.babelrc, package.json, cli command)

Pretty barebone, see the gist for all created files. Startup via npm run start (`parcel serve index.html --https`)

## 🤔 Expected Behavior

HMR should work like it does without the https option.

## 😯 Current Behavior

Firefox will not establish a connection to the websocket port since the self signed certificate is not deemed trustworthy until the user accepts it.

## 💁 Possible Solution

This seems to be coming from the need for the user to accept the self signed certificate prior to connecting.

You can manually fix this by navigating to the websocket port via the https protocol and accepting the security risk.

E.g. when the websocket server runs on wss://localhost:56501 you just need to navigate to https://localhost:56501 accept the risk and then reload your actual page.

Fix might be to use the same port for the websocket server and the http(s) server.

## 🔦 Context

Was trying to test some features with Firefox with https enabled.

## 💻 Code Sample

https://gist.github.com/Feirell/d52dd5cf168612fdf509b7c90bf5038a

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 12.14.0
| npm/Yarn         | yarn 1.21.1
| Firefox | 74.0b9 (64-Bit)
| Operating System | Win 10 1803

**Comment by mischnic** [comment]
> Fix might be to use the same port for the websocket server and the http(s) server.

Already done in Parcel 2.
