### ISSUE TITLE
Parcel puts file in the wrong location

### ISSUE THREAD

**Issue by dschuessler** [parcel-bundler/parcel#4294]
# 🐛 bug report

Steps to reproduce:

1. `git clone https://github.com/dschuessler/parcel-bug-example`
2. `cd parcel-bug-example`
3. `yarn install`
4. `yarn watch` (`"parcel watch src/main/index.ts src/renderer/index.html --public-url ./ -d build --target=electron`)

## 🎛 Configuration (.babelrc, package.json, cli command)

For config files see https://github.com/dschuessler/parcel-bug-example

## 🤔 Expected Behavior

This is the expected file structure after build:

```
.
└── build
    ├── main
    │   ├── index.js
    │   └── index.js.map
    └── renderer
        ├── index.html
        ├── style.fc0058f6.css
        ├── style.fc0058f6.css.map
        ├── style.fc0058f6.js
        └── style.fc0058f6.js.map
```

## 😯 Current Behavior

This is the actual file structure after build:

```
└── build
    ├── main
    │   ├── index.js
    │   └── index.js.map
    ├── renderer
    │   └── index.html
    ├── style.fc0058f6.css
    ├── style.fc0058f6.css.map
    ├── style.fc0058f6.js
    └── style.fc0058f6.js.map
```

Note that the link to `style.fc0058f6.css` in `build/renderer/index.html` is actually broken. 

## 🔦 Context

Run `yarn start` to see that the window is white. If the style sheets are in the right place, it is grey. This is just a minimal example. The actual application I took this from breaks due to this issue.

## 💻 Code Sample

see above

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4 | 
| Node             | 13.10.1 |
| Yarn         | 1.22.0 |
| Operating System | macOS 10.14.6 |

**Comment by dschuessler** [comment]
In case this has been ignored due to the usage of Parcel 1: It also happens with Parcel 2.

**Comment by DeMoorJasper** [comment]
@dschuessler I don't think this is a bug, it's how parcel works. We only maintain filepaths for html files and entrypoints to ensure SEO. everything else gets hashed and flattened. We should however offer a way to simply accomplish this in Parcel 2.

In parcel 2 there are namer plugins for this use-case, but that's still rather complex for this simple use-case

**Comment by dschuessler** [comment]
I understand. But nonetheless the outputted `index.html` file expects these hashed and flatted files in the same directory and not one level above. The link parcel produces is broken.

**Comment by DeMoorJasper** [comment]
Ow in that case it's a bug
