### ISSUE TITLE
npm audit is showing that parcel-bundler has a dependence with vulnerability

### ISSUE THREAD

**Issue by sssouza** [parcel-bundler/parcel#4296]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
  "dependencies": {
    "@meliuz/lib-auth-js": "1.2.6",
    "@sentry/node": "5.9.0",
    "clipboard-copy": "3.1.0",
    "cookie-parser": "1.4.4",
    "express": "4.17.1",
    "jsonwebtoken": "8.5.1",
    "mustache": "3.1.0",
    "mustache-express": "1.3.0",
    "nanoid": "2.1.5",
    "newrelic": "6.1.0",
    "node-fetch": "2.6.0",
    "parcel-bundler": "1.12.4"
  },
  "devDependencies": {
    "nodemon": "2.0.0",
    "sass": "1.23.7"
  }
```

## 🤔 Expected Behavior

Pass `npm audit`

## 😯 Current Behavior

Failing `npm audit`

## 💁 Possible Solution

Update Acorn, the dependence with vulnerability

## 🔦 Context

Our tests are failing because the `npm audits` task fails.

## 💻 Code Sample

![Captura de tela de 2020-03-09 16-07-53](https://user-images.githubusercontent.com/6945385/76249089-5f44ab00-6221-11ea-96aa-744dc99a8171.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 13.10.1
| npm/Yarn         | 1.22.0
| Operating System | Ubuntu 18.04.4 LTS

**Comment by mischnic** [comment]
Please see https://github.com/parcel-bundler/parcel/issues/4289#issuecomment-596183677
