### ISSUE TITLE
Disable AutoInstall by default

### ISSUE THREAD

**Issue by erhathaway** [parcel-bundler/parcel#4298]
## 💬 RFC

From my perspective, it is a massive security flaw that packages are implicitly downloaded behind the scenes by default. 

Multiple times now, myself and others I know, have miss-typed dependencies in a file import statement and Parcel downloaded a package that matched the off-by-one spelling. 

I purpose that this behavior is turned off by default.

## 🔦 Context

Undesired packages are installed when mistakes are made on import statements. These packages are, in turn, able to execute post-install scripts and thus easily execute malicious behavior.

It is unrealistic for NPM or other registries to guard against off-by-one misspellings.

From a security first perspective, Parcel should not implicitly download packages - especially ones the Parcel team doesn't audit.

## 💻 Examples

The relevant PR would disable the AutoInstall behavior by default and users would need to explicitly enable it if they desired it.

**Comment by mischnic** [comment]
Related: https://github.com/parcel-bundler/parcel/issues/2081

**Comment by erhathaway** [comment]
@mischnic thanks for the related link!

Do you know who would be best to pull into this RFC conversation to get consensus on this issue?

**Comment by samsch** [comment]
Another case where autoinstall was both a major inconvenience and potential security issue: I'm converting a codebase which used something like Babel `module-resolver`, with import paths like `import xyz from 'xyz/path/to/file';`, where `xyz` is a folder in `src/`. Running parcel against this installed several packages with src folder names (aka, `xyz`).

**Comment by samsch** [comment]
This is still an outstanding issue

**Comment by samsch** [comment]
As noted here: https://github.com/parcel-bundler/parcel/pull/5267#issuecomment-716040487, v2 doesn't auto-install deps.

This can probably be closed?
