### ISSUE TITLE
Conditional reference of imported symbol breaks scope hoisting

### ISSUE THREAD

**Issue by wbinnssmith** [parcel-bundler/parcel#4299]
# 🐛 bug report

If an imported symbol is conditionally referenced, a declaration is created in that scope, and it may not be initialized for following references.

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json:
```
{
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "react": "^16.13.0",
    "react-dom": "^16.13.0"
  }
}
```

`parcel build index.js`

## 🤔 Expected Behavior

No error occurs.

## 😯 Current Behavior

```
/path/to/app/dist/index.js:8549
$dab9de5d978d909db2660c4851$$interop$default.render($ea7b41558fa2f98$$interop$default.createElement("div", null), document.getElementById('app'));
                                                                                      ^

TypeError: Cannot read property 'createElement' of undefined
    at /path/to/app/dist/index.js:8549:87
    at Object.<anonymous> (/path/to/app/dist/index.js:8550:3)
```

## 💻 Code Sample

index.js:

```js
import React from 'react';
import ReactDOM from 'react-dom';

if (false) {
  console.log(React)
}

ReactDOM.render(
  <div/>,
  document.getElementById('app'),
)
```

The compiled output looks like this:

```js
if (false) {
  var $ea7b41558fa2f98$$interop$default = $parcel$interopDefault($ea7b41558fa2f98$exports);
  {
    console.log($ea7b41558fa2f98$$interop$default);
  }
}

var $dab9de5d978d909db2660c4851$$interop$default = $parcel$interopDefault($dab9de5d978d909db2660c4851$exports);
$dab9de5d978d909db2660c4851$$interop$default.render($ea7b41558fa2f98$$interop$default.createElement("div", null), document.getElementById('app'));
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | parcel v2 @ f2a62434adbba86bdd56774833d70d7852988ed1 and mischnic/dev @ 6135d13acc63260e4bd4cb3175b6fc38ad79daaa
| Node             | v12.16.1
| npm/Yarn         | yarn 1.21.1
| Operating System | macOS 10.15.3

**Comment by wbinnssmith** [comment]
cc @mischnic — this occurs even on `mischnic/dev`

**Comment by mischnic** [comment]
[REPL](https://parcel2-repl.now.sh/#JTdCJTIyY3VycmVudFByZXNldCUyMiUzQSUyMkphdmFzY3JpcHQlMjIlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIybWluaWZ5JTIyJTNBZmFsc2UlMkMlMjJzY29wZUhvaXN0JTIyJTNBdHJ1ZSUyQyUyMnNvdXJjZU1hcHMlMjIlM0FmYWxzZSUyQyUyMnB1YmxpY1VybCUyMiUzQSUyMiUyMiUyQyUyMnRhcmdldFR5cGUlMjIlM0ElMjJicm93c2VycyUyMiUyQyUyMnRhcmdldEVudiUyMiUzQW51bGwlMkMlMjJzaG93R3JhcGhzJTIyJTNBZmFsc2UlN0QlMkMlMjJhc3NldHMlMjIlM0ElNUIlNUIlMjJpbmRleC5qc3glMjIlMkMlMjJpbXBvcnQlMjBSZWFjdCUyMGZyb20lMjAlNUMlMjIuJTJGcmVhY3QlNUMlMjIlM0IlNUNuJTVDbmlmJTIwKGZhbHNlKSUyMCU3QiU1Q24lMjAlMjBjb25zb2xlLmxvZyhSZWFjdCklM0IlNUNuJTdEJTVDbiU1Q25jb25zb2xlLmxvZyglM0NkaXYlMjAlMkYlM0UpJTNCJTVDbiUyMiUyQzElNUQlMkMlNUIlMjJyZWFjdC5qcyUyMiUyQyUyMmZ1bmN0aW9uJTIwY3JlYXRlRWxlbWVudCgpJTIwJTdCJTdEJTVDbm1vZHVsZS5leHBvcnRzJTIwJTNEJTIwJTdCJTVDbiUyMCUyMGNyZWF0ZUVsZW1lbnQlNUNuJTdEJTNCJTVDbiUyMiU1RCU1RCU3RA==) 😉

Related code:
https://github.com/parcel-bundler/parcel/blob/f2a62434adbba86bdd56774833d70d7852988ed1/packages/shared/scope-hoisting/src/link.js#L186-L195

**Comment by mischnic** [comment]
I guess we should simply do
```js
        if (binding) {
          parent = path.findParent(p =>
            t.isProgram(p.parent)
          );
        }
```
to make sure that the interop var is declared in the program block
