### ISSUE TITLE
Module collapsing

### ISSUE THREAD

**Issue by alexreardon** [parcel-bundler/parcel#4301]
When running `parcel build src/index.html` I have noticed a behaviour where modules with duplicate content can become a single module.

```js
// app-context.js
export default React.createContext(null);
```

```js
// item-context.js
export default React.createContext(null);
```

in the production build these become one module:

```js
'[some-hash]': {
  export default React.createContext(null);
}
```

This is bad as in this case it is causing React to treat both of these seperate references as the same - causing them to step on one another in the React tree.

This is happening in parcel 1 and parcel 2

I don't think this should be the expected behaviour. There might be lots of reasons why two seperate modules with identical contents would want to be continue to be treated as seperate modules. Collapsing them based on content will lead to bugs. I might rely on the modules returning different references even if their contents are the same. 

Work around

```js
// app-context.js

// forcing component to have different content
console.log('app');
export default React.createContext(null);
```

```js
// item-context.js

// forcing component to have different content
console.log('item');
export default React.createContext(null);
```

This behaviour exists even when passing in all these options:

```
--no-cache --no-minify --no-source-maps --no-autoinstall --no-content-hash
```

**Comment by alexreardon** [comment]
#3523

**Comment by alexreardon** [comment]
To me this is a critical bug

**Comment by mischnic** [comment]
> To me this is a critical bug

It is

> This is happening in parcel 1 and **parcel 2**

Are you sure? This example triggers the issue on Parcel 1 but Parcel 2 works fine (both with and without scope hoisting).
If not, this indeed a duplicate of 3523.

```js
// index.js
import a from "./a";
import b from "./b";

console.log(a === b);

// a.js
import ctx from "./a-ctx"
export default ctx;

// b.js
import ctx from "./b-ctx"
export default ctx;

// a-ctx.js
export default new URL("https://parceljs.org");

// b-ctx.js
export default new URL("https://parceljs.org");
```

**Comment by alexreardon** [comment]
Parcel 2 is not working. I checked today

**Comment by alexreardon** [comment]
My appologies - i was running parcel 1. I am having other issues getting started (svgs don't seem to work out of the box) so i cannot completely confirm this is not an issue - but given you have called out that it is fixed let's assume it is for v2 :)

**Comment by mischnic** [comment]
You mean importing svgs into react?
You can add a `.parcelrc` file with:
```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.svg": ["@parcel/transformer-svgo", "@parcel/transformer-svg-react"]
  }
}
```
