### ISSUE TITLE
Inlining shared, small modules can yield non-standard behavior

### ISSUE THREAD

**Issue by surma** [parcel-bundler/parcel#4302]
# 🐛 bug report

If you have 2 `<script>` tags that share a dependency, that dependency will get chunked out if it is above a certain size (is this size threshold documented somewhere?).

However, this can yield non-standard behavior compared to using normal ES modules. For example, exporting an object, all importers will get a reference to the _same_ object. So one function change the object, other importers should see those changes.

## 🎛 Configuration (.babelrc, package.json, cli command)

Please see [repro repo](https://github.com/surma-dump/parcel-shared-objects)

## 🤔 Expected Behavior

`obj.js` should land in its own chunk.

## 😯 Current Behavior

`obj.js` is inlined into both `component-1.js` and `component-2.js`.

## 💁 Possible Solution

See “Expected Behavior”.

## 🔦 Context

E.g: A module exporting a global config object that gets augmented by other modules.

## 💻 Code Sample

Please see [repro repo](https://github.com/surma-dump/parcel-shared-objects)
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | v12.8.0
| npm/Yarn         | 6.12.1
| Operating System | MacOS 10.15.3 (19D76)

**Comment by mischnic** [comment]
The second script tag would have to import that shared module from the first script tag (a mechanism for that exists already).

I think taking all the script tags as one bundlegroup and each script tag as a bundle would automatically cause that behavior. Currently we completely ignore that fact that these bundles are actually related (so two script tags behave just like two worker calls - which is quite a simplification).

But sharing local variables between the script tags is still something we wouldn't support (what do you think?)

> that dependency will get chunked out if it is above a certain size (is this size threshold documented somewhere?).

Here (that plugin handles all the chunking): https://github.com/parcel-bundler/parcel/blob/v2/packages/bundlers/default/src/DefaultBundler.js#L10

**Comment by surma** [comment]
> But sharing local variables between the script tags is still something we wouldn't support (what do you think?)

The reason I bring this up is because it would behave differently with 2 `<script type="module">` tags. The parcel output logs `1 1`, while the source with native ES modules logs `1 2`.

It feels unexpected (and undesirable) to me that behavior would change because I ran parcel.

**Comment by mischnic** [comment]
I agree that running Parcel shouldn't change the behaviour of the code.

**Comment by devongovett** [comment]
Should be fixed by #4786. Parcel will now deduplicate common modules between multiple script tags.
