### ISSUE TITLE
Generated script tags don’t have `defer` 

### ISSUE THREAD

**Issue by surma** [parcel-bundler/parcel#4304]
# 🐛 bug report

I have 2 entry points, `index.html` and `profile.html`, each of loading their own specific piece of JavaScript, `index.js` and `profile.js`. Both these JS files depend on a common dependency `utils.js`. If `utils.js` is big enough to become its own chunk, the resulting HTML contains an additional `<script>` tag for the common dependencies. 

## 🎛 Configuration (.babelrc, package.json, cli command)

Please see [repro repo](https://github.com/surma-dump/parcel-js-entry-cascade)

## 🤔 Expected Behavior

The `<script>` tag for the common dependency should have `defer` if the original `<script>` tag has a `defer` attribute. Same for `async`.

## 😯 Current Behavior

The `<script>` tag for the common dependency does not have any attributes and is therefore renderblocking.

## 🔦 Context

Normal web development.

## 💻 Code Sample

Please see [repro repo](https://github.com/surma-dump/parcel-js-entry-cascade)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | v12.8.0
| npm/Yarn         | 6.12.1
| Operating System | MacOS 10.15.3 (19D76)

**Comment by surma** [comment]
(The part where the generated `<script>` tag is in the wrong position in the markup I filed under #4303)

**Comment by mischnic** [comment]
Is the order of execution between two deferred/async script tags defined?

**Comment by surma** [comment]
Yes. They executed in parse-order.
