### ISSUE TITLE
Not using local TS

### ISSUE THREAD

**Issue by alexreardon** [parcel-bundler/parcel#4307]
I have noticed that the latest Parcel `^2.0.0-alpha.3.2` is not using the locally installed version of TypeScript. This bit me when I started using new TS syntax

**Comment by mischnic** [comment]
Do you get an error message? I'm trying to figure out which plugin isn't using the local version.

**Comment by alexreardon** [comment]
```ts
import type { Position } from '../types';
```

`type` is a new keyword

Error I am getting from parcel:

```
@parcel/transformer-babel: Unexpected token (1:12)
...
> 1 | import type { Position } from '../types';
>   |            ^

```

**Comment by alexreardon** [comment]
A local running of `tsc` is all good. But parcel goes *boom*

**Comment by mischnic** [comment]
> @parcel/transformer-babel

Parcel isn't using tsc. Add this `.parcelrc` to use tsc:
```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
}
```

**Comment by alexreardon** [comment]
I am using `tsc` to run a typecheck locally. In my package.json I just have this installed:

```
"typescript": "^3.8.3"
```

**Comment by alexreardon** [comment]
I added the lines you suggested and I am getting this error:

```
$ parcel src/index.html
ℹ️ Server running at http://localhost:1234
🚨 Build failed.
Error: Unexpected token export
[my project root]/node_modules/@parcel/ts-utils/src/index.js:2
export * from './FSHost';
^^^^^^
```

**Comment by mischnic** [comment]
Babel doesn't support `import type` yet (https://github.com/babel/babel/issues/10981), you'll have to use the tsc based transformer.

> Error: Unexpected token export

😬 I guess you'll have to use the nightly.

**Comment by alexreardon** [comment]
the nightly?

**Comment by DeMoorJasper** [comment]
@alexreardon yeah, we fixed the bug you've mentioned (with tsc) but it has not been deployed as an alpha yet. But available as a nightly release, which happens automatically every day from the v2 branch.

To install it run `yarn add parcel@nightly` and for the ts-transformer `yarn add @parcel/transformer-typescript-tsc@nightly` hopefully this clears it up :)

**Comment by alexreardon** [comment]
Thanks, I'll give it a go

**Comment by alexreardon** [comment]
It worked!

**Comment by DeMoorJasper** [comment]
Awesome, I'll close this issue as it's been resolved

**Comment by adrianmcli** [comment]
@DeMoorJasper when will another alpha build be published? I want to use this fix but I don't want to rely on having `nightly` in my `package.json`.

**Comment by mischnic** [comment]
We're hoping next week.
