### ISSUE TITLE
Raw transformation not working

### ISSUE THREAD

**Issue by awvalenti** [parcel-bundler/parcel#4310]
# 🐛 bug report

Importing a text file results in a string with a generated path, instead of file contents

## 🎛 Configuration (.babelrc, package.json, cli command)
Please see Code Sample below

## 🤔 Expected Behavior
Should output file contents

## 😯 Current Behavior
Outputs file path after minification:
![image](https://user-images.githubusercontent.com/834921/76372042-f80b2180-631a-11ea-87ea-d21ec92210b5.png)

 

## 💁 Possible Solution
Don't know

## 🔦 Context
I was trying to read a text file by importing it directly

## 💻 Code Sample
A fresh project can be created with the following bash script to reproduce the problem:
```bash
mkdir test
cd test
echo 'content' > file.txt
echo 'import file from "./file.txt"; alert(file);' > show.js
echo '<html><body><script src="show.js"></script></body></html>' > index.html
npm init -y
npm i -D parcel-bundler
npx parcel index.html --open
# Should alert "content", but alerts something like "/file.d9bcf180.txt"
```

## 🌍 Your Environment
Both Windows 10 with NodeJS v13.1.0 and Linux Mint Cinnamon 19 with NodeJS v10.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.4
| Node             |13.1.0
| npm/Yarn         |6.12.1
| Operating System | Windows 10

**Comment by mischnic** [comment]
This is per Parcel 1's design, you get the url if no asset type was registered for that extension.
Parcel 2 will allow this.
