### ISSUE TITLE
sourcemaps always forced to be relative even for absolute paths and http/https/file locations

### ISSUE THREAD

**Issue by aappddeevv** [parcel-bundler/parcel#4316]
"parcel-bundler": "^1.12.4",

In parcel-bundler/src/utils/loadSourceMap.js The code always assumes that source maps are relative to the asset it is describing, which is not always the case.

For example, if the source map sources item starts with "/" it should probably not use the relative scheme. Source maps that start with http/https should be passed through and those with file: could be passed through or resolved (parcel could choose or perhaps a switch).

For example, this fixes the absolute path issue:

```js
     if(source.startsWith("file:///")) source = source.slice(7) // triple slash is also absolute
    try {
              let sourceFile = path.isAbsolute(source) ? // CHECK FOR ABSOLUTE PATH HERE
                source:
                path.join(
                path.dirname(filename),
                sourceMap.sourceRoot || '',
                source
              );
```

Is this something that makes sense to fix?

**Comment by DeMoorJasper** [comment]
It does, will add it to my todo for parcel 2 sourcemaps! Sorry that I haven't responded to this earlier, good thing the stale bot reminded me

**Comment by aappddeevv** [comment]
Thanks a bunch!
