### ISSUE TITLE
Import lib with WebWorker

### ISSUE THREAD

**Issue by youncccat** [parcel-bundler/parcel#4317]
# 🐛 bug report

**foo.ts**
```typescript
export class Foo {
  constructor(){
    new WebWorker(require.resolve("./bar.ts"))
  }
}
```

**bar.ts**
```typescript
console.info('bar')
```

Then I'm attempting to run 
```
parcel ./foo.ts
```
Parcel will output two bundles
```
bar.f941a17c.js
foo.js
```

the Foo is same like a library of Javascript.

**main**
```typescript
import {Foo} from './foo.js'

new Foo()
```

## 🤔 Expected Behavior

perfect running

## 😯 Current Behavior

I get an error
```
bar.js:1 Uncaught SyntaxError: Unexpected token '<'
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.4|
| Node             |12.13.1|
| npm/Yarn         | Yarn|
| Operating System |Mac OS|

**Comment by mischnic** [comment]
There's an architectural problem here:
Originally (in Node) `require(require.resolve("./foo"))` is supposed to work. So `require.resolve` returns a module specifier to a file.
In contrast, `new Worker` expects a URL to a bundle (which necessarily means a different bundle).

So naively, this snippet should run fine, but there are contradicting requirements for the `require.resolve` result.
```js
const x = require.resolve("./bar.ts");

// (a) this would usually mean: `x` is in the same bundle, especially because require needs to be synchronous
console.log(require(x));

// (b) `x` needs to be a different bundle
new Worker(x);
```
The only solution I see (always speculatively making `require.resolve` add the asset the current bundle for (a) and creating a new bundle for (b) and wrapping all callsites of `require` and `new Worker` to decide what to use) is just bad.

A viable alternative (one which also fits the current architecture of Parcel) which I would really like to see implemented:
```js
import x from 'worker-url:./bar.ts'

new Worker(x);
```

**Comment by youncccat** [comment]
@mischnic Thx for your reply so much. but I'm confuse if Foo is a library of JS with web worker. As a user, I don't want to dep extract modules like FooWorker, this is my expected usage.

```typescript
import {Foo} from 'my-library'

new Foo();
```
Is there any other way?

**Comment by mischnic** [comment]
as I've said, the only way is:
```js
// node_modules/my-library/index.js
export class Foo {
	constructor(){
		this.worker = new Worker("./libraryworker.js")
	}
	// ...
}

**Comment by youncccat** [comment]
Thx, I'll give it a try :)
