### ISSUE TITLE
🙋 Importing stylesheets using `style` in module's package.json

### ISSUE THREAD

**Issue by DataTables** [parcel-bundler/parcel#432]
I'm trying to get stylesheets which an npm module's `package.json` defines a `style` property, and I'm struggling to get this working. I _think_ its a feature request rather than a bug, but I had been expecting it to work out of the box.

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "xxtmp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "datatables.net": "^1.10.16",
    "datatables.net-dt": "^1.10.16",
    "jquery": "^3.2.1"
  }
}
```

### 🤔 Expected Behavior

With an imported stylesheet of:

```css
@import 'datatables.net-dt';
```

I had expected it to automatically expand since `datatables.net-dt` defines a `style` property which points to its stylesheet.

### 😯 Current Behavior

I get an error stating that:

> main.css:2:1: Cannot resolve dependency 'datatables.net-dt'

### 💁 Possible Solution

Perhaps one solution would be to use [postcss-import](https://github.com/postcss/postcss-import) out of the box. If I use postcss import directly, it does inline the imported stylesheet as expected. I've tried using the following in a .postcssrc file, but it made no difference when using Parcel:

```js
{
    "plugins": {
        "postcss-import": {}
    }
}
```

### 🔦 Context

I'm trying to write a little blog post to demonstrate how Parcel can be used to easily build in my DataTables library. The problem I've had with just about every bundler is the CSS part - the JS is never a problem and I was hoping that Parcel might be an out of the box builder that would resolve this.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.3.1 |
| Node             | 8.1.2 |
| npm/Yarn         | 5.0.3 |
| Operating System | Fedora 27 |

**Comment by devongovett** [comment]
The code that does this type of resolution is here: https://github.com/parcel-bundler/parcel/blob/master/src/Resolver.js#L52.

You'll want to check for `pkg.style` there, but only if the parent module is a style file (CSS, SASS, Stylus, etc.).

**Comment by DataTables** [comment]
So would your preference be to resolve in Parcel rather than using postcss-import?

I've taken a quick poke around in the code and I see my `style` parameter being picked up in the resolver you linked to, but I'm not sure what to do with it from there. I'll poke around a bit more shortly, but any suggestions welcome :).

**Comment by devongovett** [comment]
Yes, we should resolve in Parcel. We should somehow register formats that are "style" files (e.g. CSS, stylus, sass, etc.), and if the parent module is one of those, set the `main` to `pkg.style` if it exists.

**Comment by DataTables** [comment]
I might be misunderstanding slightly (apologies if so), but wouldn't setting the `main` to be the `pkg.style` value cause issues with front-end packages which include both JS and CSS components. For example, [this package file](https://github.com/DataTables/Dist-DataTables-Bootstrap/blob/master/package.json) for DataTables Bootstrap styling integration requires both CSS and JS files to be loaded in, so `main` and `style` are both used in `package.json`.

**Comment by okyantoro** [comment]
@devongovett can I work on this issue?

**Comment by dalgard** [comment]
+1 for this feature.

When Parcel is used to precompile an NPM package with `--target node`, it outputs two files:

```
dist/index.css
dist/index.js
```

When I import the package somewhere else, it will take the main export from the file referenced in `package.json`'s `"main": "dist/"` property, but the CSS is left behind.

The point of precompiling the package is that it can be used anywhere without a specific loader setup, but in the case it is used in a Parcel project, it would seem fair that Parcel **automatically** includes the CSS file in any `package.json`'s `"style": "dist/"` property in the bundle.

**Comment by dalgard** [comment]
Seems like [parcelify](https://github.com/rotundasoftware/parcelify) has the exact functionality needed.

**Comment by std4453** [comment]
Came across this when using [react-dat-gui](https://github.com/claus/react-dat-gui).

For anyone that needs an immediate solution, importing the CSS file directly works, out-of-the-box, without configurations, like:

```javascript
import 'react-dat-gui/dist/index.css';
```

**Comment by devongovett** [comment]
This is supported using the package.json exports field, with the "style" condition. See https://parceljs.org/features/dependency-resolution/#conditional-exports
