### ISSUE TITLE
Plugin documentation

### ISSUE THREAD

**Issue by surma** [parcel-bundler/parcel#4320]
# 🐛 bug report

At the time of writing, the [README of Parcel 2](https://github.com/parcel-bundler/parcel/blob/da3cf2a5386d71d25eae5418ebef5d9bfb9e5d62/packages/core/parcel/README.md) contains a list of official plugins and a description of the plugin API.

However, I find the current contents insufficient. The plugins could use some description — both in the README as well as [on npm](https://npm.im/@parcel/packager-raw).

More importantly, the documentation for _authoring_ plugins is insufficent in that none of the data structures are document. What is a `asset`? What is in a `graph`? 

The plugin architecture seems at least as powerful as [Rollup’s plugin architecture](http://rollupjs.org/guide/en/#build-hooks), so I’d absolutely love to see a similarly detailed documentation (and Rollup’s documentation has a lot of room for improvement, too!)

**Comment by DeMoorJasper** [comment]
We're gonna get started on a docs site really soon, with a detailed description of every public part of parcel and how it works.

**Comment by mischnic** [comment]
We are aware of the general lack of documentation and hope to get something out in the near future.

**Comment by surma** [comment]
I guess this can be closed?

**Comment by wbinnssmith** [comment]
@surma We now link to the docs site for v2 in the README: https://v2.parceljs.org/ thanks to awesome work from @mischnic and @DeMoorJasper.

As noted, it's not exhaustive, and we definitely welcome feedback on where it can be improved 😄 

Would it be worthwhile to close this out and open issues about specific areas of improvement going forward?

**Comment by wbinnssmith** [comment]
Going to close this out in favor of more granular feedback now that this is generally addressed at https://v2.parceljs.org/. 

Thanks for all of your awesome feedback @surma and looking forward to more. Feel free to re-open of course.
