### ISSUE TITLE
Please make new release

### ISSUE THREAD

**Issue by bubnenkoff** [parcel-bundler/parcel#4324]
I want to try new version of Parcel, but the last version of Parcel 2 was published in last year. Possible I can use git version, but I am not professional js developer

**Comment by DeMoorJasper** [comment]
The last version was released 15 hours ago, install `parcel@nightly` to get the latest version.

We've mainly been focusing on getting Parcel 2 faster and more stable since the latest alpha so it should be fine to use the nightly.
