### ISSUE TITLE
Ignore other JavaScript Files.

### ISSUE THREAD

**Issue by SomeProgrammerGuy** [parcel-bundler/parcel#4328]
I did...

# 🙋 feature request

Simple attributes to ignore files (any file).

## 🤔 Expected Behavior << *SPELLING* 'Behaviour' (maybe it's a US thing I'm not sure).

A simple setting to ignore file.

## 😯 Current Behavior << *SPELLING* 'Behaviour' (maybe it's a US thing I'm not sure).

It doesn't I believe (maybe you have fixed this and I haven't found the right docs, ok cool my bad) (see below)

## 💁 Possible Solution

No matter how complicated what you are trying to do is, simply adding something like type="parcel/ignore" isn't really rocket science. I am sure there are many other just as satisfactory ways.

## 🔦 Context

I have been using Parcel today as an experiment on real code (as to other options). As I'm testing it it is just a local file system and a simple game (just used for testing *stuff*). Firstly some issues with local image resources that were fixed with "require" which was in itself not very good but that's a different issue. Mostly it just doesn't work when trying to include other JavaScript files that you want Parcel to ignore (and there are many good reasons for doing this). After Googling this a lot this evening I see bodges and add on's etc. etc. (and many folk complaining about such). But lets be honest this is an easy fix. Simply read an attribute that says hey Parcel just ignore me. That really isn't hard to add. I find it bizarre that library's such as this can do loads of complicated *stuff* and yet seem to ignore really easy fixes that are needed in the real world.

For note there is a time to stop trying to shave off a few seconds (even minutes and note I love fast) nobody cares about and fix the actual issues. 538 is a lot (14 Mar 2020)   ...

## 💻 Examples

Just add something like type="parcel/ignore" or *whatever* to the tags.

<!-- Love parcel? Please consider supporting our collective:

👉 I loved the idea. 

People asking for this type of (easy to add) thing over a year ago, will make many folk like myself get bored and never use your software again, which is a shame as **mostly** you are on the right track. Speed, ease of use etc.

**Comment by mischnic** [comment]
> (maybe it's a US thing I'm not sure).

Let me google that for you, ...., yes it is. Welcome to the inter(national)net.

> For note there is a time to stop trying to shave off a few seconds (even minutes and note I love fast) nobody cares about

You do not care, other people do care.

> and fix the actual issues. 538 is a lot (14 Mar 2020) ...

You are welcome to help out

**Comment by SomeProgrammerGuy** [comment]
The truth is that is quite an arrogant response and why I will now make a point of not using this software  (or anybody I'm connected with in the future). This isn't Facebook and it probably doesn't deserve this response as to some *student* (I'll come back to that point later).

As too your first point and note I say this laughing and with a sense of jest as I really don't care: "Let me google that for you, ...., yes it is. Welcome to the inter(national)net." If it is confusing for you it is the "ENGLISH" language. It doesn't have another version although lots of countries like to think it does. It's not "American English" its "American" take your pick... If somebody told you your name was now "Nicolas Miskulgnick" as we have decided to change **YOUR** language I'm sure that last post would be rather different. (again for note I really really don't care in real life).

Next "You do not care, other people do care.". No I'm sorry they really don't (if your software works). "Premature optimisation" (that I'm sure you can "LMGTFU" lol).

If you build a car that can travel at 200 MPH but the ignition system doesn't work, then I'm sorry nobody cares. Make it work first then worry about how fast it is.

I come to my comment above "This isn't Facebook and it probably doesn't deserve this response as to some *student* (I'll come back to that point later)".

I have been developing software far before you were born, and I still am very successfully (and employing many others that are as well). I would actually love to help out but I don't have all that free time a *student* has (I was *Helping out* free software that is far far before your time, and probably more of it to date. 

The truth is I have to spend a lot of time assessing what I and my staff are going to use next going forward. 

I give these comments as an actual *potential* user (hopefully to improve it) and after what is simply minutes I can see (after many years in the real world developing software) exactly why I wont (and many others are the same). Trust me I am giving a heads up, 90% of developers won't. They will just ignore you (which is a shame because mostly I love the idea and what this software is trying to solve).

But when I hear a **student** (who maybe need some safe space) writing this bullshit then hey... You lose another user. You may not think that matters but trust me it really does :-)

**Comment by DeMoorJasper** [comment]
@SomeProgrammerGuy the issue you bring up on being able to ignore imports in html is a valid point and has been brought up before, we never really came to a conclusion on how to implement it though...

But the arrogance you bring towards this issue is just insane, you shouldn't think you're better than a student because you are a senior or manager. Students can just as good of a job at writing software and maybe even better in some cases. As far as I know being this arrogant is a bad quality to have as a manager.

I'm gonna close this in favor of a more friendly and proper feature request that already requested this. #1186
