### ISSUE TITLE
Watching for files doesn't work

### ISSUE THREAD

**Issue by countcretinos** [parcel-bundler/parcel#4331]
# 🐛 bug report

[As the docs say](https://parceljs.org/getting_started.html), running parcel without mode specified should start a development server and watch files for changes. This doesn't happen.

> Parcel has a development server built in, which will automatically rebuild your app as you change files and supports hot module replacement for fast development. Point it at your entry file:

## 🎛 Configuration (.babelrc, package.json, cli command)

`$ node_modules/.bin/parcel src/index.html`

## 🤔 Expected Behavior

Parcel  should rebuild as the files change.

## 😯 Current Behavior

Rebuild is not done.

## 💻 Code Sample

**index.html**
```
<!doctype html>
<html>
  <head>
    <script src="./js/index.js"></script>
</head>
  <body>
      <div id="app" />
  </body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.2.14
| Node             | 12.16.1
| npm/Yarn         | 6.13.4
| Operating System | Alpine (node:12 from Docker Hub)

**Comment by DeMoorJasper** [comment]
It should work, we've had many issues with watching in the past, not entirely sure what your setup is but it might be an issue with chokidar or something?

Parcel 2 has a new watcher that should be faster and more reliable

**Comment by countcretinos** [comment]
Working now :confused:
