### ISSUE TITLE
Source Maps Paths aren't relative to input file from --out-dir.

### ISSUE THREAD

**Issue by asprich** [parcel-bundler/parcel#4335]
**Background and Praise! (unrelated to my issue):**
First off, I love Parcel. It's the only build tool I use or would recommend. I'm a professional C# developer getting a lot more into newer web development over the past few years. This includes node, vue, & angular. I mainly use Parcel for building small web apps with vue as side projects or for internal tools. I've been pushing for cleaning our old, tightly coupled, clunky, jquery-ish javascript with newer technologies however, bundling/minifying can be a fairly overwhelming task especially for those used to the ways of old. I started with Parcel, then spent a lot of time learning webpack then rollup. I quickly learned the need for Parcel, and all the problems you guys are solving. Thanks so much to everyone who brought this to life! 

# 🐛 bug report
My goal:
I'm trying to introduce npm and parcel to handle the bundling for a .net core c# web app. The Microsoft recommend bundling solution just sucks and Parcel is much better IMO.  

My problem:
The generated source maps don't seem to respect the --out-dir parameter in relation to the input files.  I'm running parcel (not v2) from the command line with build or watch and --out-dir.  
```
"scripts": {
    "build": "npx parcel build wwwroot/js/index.js --out-dir wwwroot/dist",
    "watch": "npx parcel watch wwwroot/js/index.js --out-dir wwwroot/dist"
  },
```

This is pretty close to this issue, but I'm not using the public url parameter:
https://github.com/parcel-bundler/parcel/issues/1180

Adding it didn't seem to make a difference, perhaps I'm not using it correctly?

## 🤔 Expected Behavior
The paths in the map file should be "../js/utilities/utilities.js" and "../js/main/alert-user.js" so they point to where the source files exist.

## 😯 Current Behavior
The paths in the .map file are "utilities/utilities.js" and "main/alert-user.js" and assume the source files are right beside the compiled files. Which is not the case, I would think, in the majority of cases.

## 💁 Possible Solution
Not sure, perhaps provide a source map root parameter? I can understand why in most cases this would not be not be need. But it would really solve a lot of problems for me. :)

## 🔦 Context
I'm unable to advocate for using parcel to solve all our build problems at work. :)

## 💻 Code Sample
https://github.com/asprich/parcel-issue

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.12.4 |
| Node             | v12.14.0 (but doesn't seem to matter) |
| npm         | 6.13.4 |
| Operating System | Windows 10 |

^ will do!

Side Note:
I'm using current stable in NPM. I tried the V2 nightly and it would not compile my files. I added  --dest-dir .\wwwroot\dist\ --no-scope-hoist. And this got me further, but still wouldn't compile my files.

**Comment by mischnic** [comment]
The source map problem won't be fixed in Parcel 1.

1. This causes the scope hoisting to crash (this code doesn't do what you want it to, but we should still handle it):
```js
global.myNamespace = {
    AlertUser,
    Utilities
};

export default myNamespace; // <---- not defined
```

2. There is a fundamental difference between default exporting an object and named exports. 
```js
//This is an example of bad code we want to replace
export default {
    isIE: false,
    isChrome: false,
    isEdge: false,
    getUserAgent() {
        return navigator.userAgent;
    }
}

// --

import { getUserAgent } from "../utilities/utilities"; // no
```

For Parcel 2, you will also need to remove `main: "index.js"` from your package json, then
`parcel build wwwroot/js/index.js --dist-dir wwwroot/dist` will work.
