### ISSUE TITLE
Cannot read property of null issue - while registering serviceWorkers with app.js

### ISSUE THREAD

**Issue by Dagge1** [parcel-bundler/parcel#4337]
I have entered registering serviceworker code (PWA) in my main app.js file and parcel throws an error. My backend is Node and frontend is Vue and besides this everything else works:
```
parcel] 🚨  Cannot read property 'js' of null
    at Bundler.createBundleTree (C:\Users\davorin\AppData\Roaming\npm\node_modules\parcel-bundler\src\Bundler.js:650:39)
    at Bundler.createBundleTree (C:\Users\davorin\AppData\Roaming\npm\node_modules\parcel-bundler\src\Bundler.js:692:12)
    at Bundler.createBundleTree (C:\Users\davorin\AppData\Roaming\npm\node_modules\parcel-bundler\src\Bundler.js:692:12)
    at Bundler.bundle (C:\Users\davorin\AppData\Roaming\npm\node_modules\parcel-bundler\src\Bundler.js:284:14)
```
My code in app.js for registering serviceworker is basic one:
```
if ('serviceWorker' in navigator) { // if the browser supports serviceworkers
    navigator.serviceWorker.register('/sw.js').then(() => {  //..register it (asynchronous, Promise based)
        console.log('Service worker registered');
    }).catch((e) => {
        console.log(e);
    });
}
```
I have seen this error but not connected to the serviceWorker registration process. What is the problem.

It works only if I copy serviceworker file _sw.js_ into _/dist folder_ manually. But despite I copied original sw.js file by myself, parcel added a ton of its own code into that file which I moved by my own. I cannot understand what is happening, I copied almost empty file which parcel refused to work on, then I copied file and parced changed it.

While fetching files for cache in sw.js file I cannot enter their real names but changed names made by parcel in /dist folder. For example I cannot state '/app.js' but I have to enter '/app.3343hf431,js' which is rather annoying because I have to put them manually after every major change in the code.

**Comment by mischnic** [comment]
Are you using the latest version of Parcel? The line numbers in the stack trace don't really match up...

**Comment by mischnic** [comment]
Closing due to lack of response
