### ISSUE TITLE
Asset development help needed

### ISSUE THREAD

**Issue by algebraic-brain** [parcel-bundler/parcel#434]
Hello,

I'm trying to develop [Gopherjs](https://github.com/gopherjs/gopherjs) asset for .go files: [gopherjs_parcel_asset](https://github.com/algebraic-brain/gopherjs_parcel_asset), using [Svelte plugin](https://github.com/DeMoorJasper/parcel-plugin-svelte) as prototype. But somehow it does not work.

Steps to reproduce:
```bash
git clone https://github.com/algebraic-brain/gopherjs_parcel_asset
cd gopherjs_parcel_asset/example
npm i .. -s
parcel index.html
```

Then we find that the `./go/hello.go` file was included into `index.html` with no changes.

What I do wrong? Please help me.

**Comment by devongovett** [comment]
at first glance, it looks like you're calling `this.async()` in `parse` which isn't a thing in parcel. https://github.com/algebraic-brain/gopherjs_parcel_asset/blob/master/GopherJSAsset.js#L10

You could return a promise:

```javascript
return new Promise((resolve, reject) =>
   // do some stuff
  resolve();
});
```

**Comment by algebraic-brain** [comment]
Thank you Devon. I'm going to rewrite the code of `GopherJSAsset` totally, but it seems that Parsel does not see my asset at all. Would it help if i give my asset name starting with `parcel-plugin-` ?

**Comment by brandon93s** [comment]
Yes, that naming convention is currently required for parcel to detect your plugins.
