### ISSUE TITLE
A way to force non-generated class names

### ISSUE THREAD

**Issue by cliffordp** [parcel-bundler/parcel#4341]
## 🙋 feature request

Let the PCSS compiling rename class names _unless_ there's an instruction not to, such as a prefix before the selector (example below).

## 🤔 Expected Behavior

Allow me to have both _raw_ (for lack of a better term) selectors and _generated_ selectors. If I'm targeting something outside of my app's scope, I'll know this beforehand, know what I need to target, and am fine with requiring a _prefix_ to do so.

## 😯 Current Behavior

If I add `.a-class-name { ... }` to my _.pcss_, the generated class is something like `._a-class-name_d9a6e { ... }`

This is fine, but sometimes I need to force a specific class name into the CSS or JS.

## 💁 Possible Solution

1)
Maybe a prefix to use that knows to remove the prefix but otherwise not modify it? For example: `RAW.a-class-name { ... }` => `.a-class-name { ... }`

2)
Alternatively, or in addition, maybe a file name prefix like `raw.my-style.pcss` where everything in _this_ file (any file with this _raw_ prefix) **won't** be customizing the selectors.

## 🔦 Context

For example, if I am integrating with another _thing_ (WordPress), I know the selector (class or ID) I need to override.

## 💻 Examples

I'm building a Settings Page in the WordPress admin, and I need to target their own `.components-panel__body-toggle.components-button` selector in my PCSS.

**Comment by mischnic** [comment]
You should be able to override the function with
a .postcssrc.js
```js
module.exports = {
	plugins: {
		"postcss-modules": {
			generateScopedName(name, filename, css){
				// this is what Parcel does by default:
				return `_${name}_${md5FromString(filename + css).substr(0, 5)}`;
			}
		}
	}
};

**Comment by cliffordp** [comment]
Looks promising, thanks! Unfortunately, couldn't get my rules to take effect (not an expert):

```
module.exports = {
	plugins: {
		"postcss-modules": {
			generateScopedName( name, filename, css ) {
				const asIsPrefix = 'raw__'; // if `.raw__some_class`, result is `.some_class`

				if ( name.startsWith( asIsPrefix ) ) {
					return name.substr( 0, asIsPrefix.length );
				}

				// this is what Parcel does by default:
				return `_${name}_${md5FromString( filename + css ).substr( 0, 5 )}`;
			},
		},
	},
};
```

What do I need in my `package.json` for this to work?

**Comment by cliffordp** [comment]
Hey, check this out:

![image](https://user-images.githubusercontent.com/1812179/77027013-17c9c780-6963-11ea-8e87-b144175bd419.png)

From https://github.com/css-modules/postcss-modules

**Comment by mischnic** [comment]
Does the `:global` thing work for your usecase?

This works for me:
```js
module.exports = {
	modules: true,
	plugins: {
		"postcss-modules": {
			generateScopedName(name, filename, css) {
				return name;
			}
		}
	}
};
```

**Comment by cliffordp** [comment]
**Yes!** With this `postcss.config.js` file:

```js
module.exports = {
	"modules": true,
	plugins: {
		'postcss-nested': {},
		'postcss-advanced-variables': {
			'variables': {
				'plugin-slug': 'cliff-wp-plugin-boilerplate',
			},
		},
	},
};
```

![image](https://user-images.githubusercontent.com/1812179/77243938-9fbb0600-6bdd-11ea-8c65-80fcf86c494e.png)
