### ISSUE TITLE
parcel build fails in the past 12 hours without "real" changes in the code

### ISSUE THREAD

**Issue by nagyv** [parcel-bundler/parcel#4343]
# 🐛 bug report

This is the first commit that fails the build:

![Screenshot_2020-03-18 Added link to index page (5e698bf8) · Commits · Viktor Nagy release-post-item-generator](https://user-images.githubusercontent.com/126671/76945796-53cd4000-6903-11ea-84f7-e534eef62e96.png)

## 🎛 Configuration (.babelrc, package.json, cli command)

My package.json is really minimal:

```
{
  "name": "frontend",
  "version": "1.0.0",
  "description": "",
  "main": "index.html",
  "scripts": {
    "test": "exit 1",
    "build": "parcel build --public-url /release-post-item-generator/ index.html",
    "start": "parcel index.html"
  },
  "author": "Viktor Nagy",
  "license": "MIT",
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/plugin-transform-runtime": "^7.8.3",
    "parcel-bundler": "^1.12.4"
  },
  "dependencies": {
    "@babel/runtime": "^7.8.4"
  }
}
```

.babelrc:

```
{
  "plugins": ["@babel/plugin-transform-runtime"]
}
```

## 🤔 Expected Behavior

The build should succeed

## 😯 Current Behavior

```
EISDIR: illegal operation on a directory, read 
Error: EISDIR: illegal operation on a directory, read
```

You can see a failing example pipeline at https://gitlab.com/nagyv-gitlab/release-post-item-generator/-/jobs/475509381

## 💻 Code Sample

https://gitlab.com/nagyv-gitlab/release-post-item-generator

## 🌍 Your Environment

I run the build in CI using https://hub.docker.com/r/ohko/parceljs

The same error happens locally with:

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4 |
| Node             | 10.13.0 |
| npm/Yarn         | 6.4.1 |
| Operating System | OSX |

**Comment by mischnic** [comment]
We unfortunately can't help you with your CI setup (which I suspect is the culprit here - maybe gitlab made some change). 

The error says that something tried to read a file at `/builds/nagyv-gitlab/release-post-item-generator` which is obviously a directory. 

We have made no changes to Parcel 1 in the last day.

**Comment by nagyv** [comment]
@mischnic the same happens locally, and I did not have this problem before. I guess the culprit might be some of the parcel dependencies, but the error message was totally uninformative.

**Comment by mischnic** [comment]
I don't know why (nor why now), but `<a href="../"` is causing this.

**Comment by nagyv** [comment]
As usual, the error was on my side. Thanks for your support.
