### ISSUE TITLE
Importing SVG sprites - issues with hash in sprite name

### ISSUE THREAD

**Issue by basher** [parcel-bundler/parcel#4346]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

- Here's my [Parcel repo with external SVG sprite](https://github.com/basher/parcel-boilerplate).
- Sprite is [imported in my index.js file](https://github.com/basher/parcel-boilerplate/blob/master/src/js/index.js).
- I want to **leverage browser caching of external SVG sprite** (rather than including the sprite directly in the HTML markup inside the `<body>` tag).
- My `index.html` contains this markup (simplified for clarity):

```html
<svg
    role="img"
    focusable="false"
>
    <use xlink:href="dist/svg-icon-defs.f3fae6c2.svg#icon-plus" />
</svg>
```

- Is there a way to remove the **hash** in `<use xlink:href="dist/svg-icon-defs.f3fae6c2.svg#icon-plus" />` so that in **DEV** and **PROD** modes, the SVG sprite path is always correct?
- Related issues [3982](https://github.com/parcel-bundler/parcel/issues/3982) and [4486](https://github.com/parcel-bundler/parcel/issues/4486).

## 🤔 Expected Behavior

Not sure - I was hoping that there is a way to remove the hash, or always make it the same value?

## 😯 Current Behavior

See above example code.

## 💁 Possible Solution

???

## 🔦 Context

See above explanation about wanting to use external SVG sprite (for caching) rather than inlining loads of SVG sprite HTML markup on every page.

## 💻 Code Sample

See my repo link above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | parcel@2.0.0-nightly.264
| Node             | v12.14.1
| npm/Yarn         | NPM v6.13.4
| Operating System | Windows 10

**Comment by mischnic** [comment]
Strange error with Parcel 2:

`Error: No transformers found for "4346-use-href/src/icons/svg-icon-defs.svg"`

**Comment by basher** [comment]
@mischnic Fix your transformers issue by adding a `.parcelrc` file in your repo root, with this content:

```
{
	"extends": "@parcel/config-default",
	"transformers": {
		"*.svg": ["@parcel/transformer-raw"]
	}
}
```

**Comment by DCzajkowski** [comment]
This is actually a big issue, because this svg transformer removes `title` and `role` attributes from svg icons. In my case, svg assets are always hand-crafted and highly curated, but when building with Parcel all of the accessibility features are stripped, leaving me with a naked SVG icon without all of those tags.

**Comment by basher** [comment]
@DCzajkowski 

Have you tried using an SVG sprite?

Parcel then only needs to bundle the sprite, leaving the inline `<svg>` icons intact with all their accessibility markup.

e.g. 
My sprite - `.\src\icons\svg-icon-defs.svg` - is setup like this:

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="display: none;">
    <symbol id="icon-search" viewBox="0 0 100 100">
        <path d="M90,87.2L75.4,72.6c6-6.6,9.6-15.4,9.6-25.1C85,26.8,68.2,10,47.5,10S10,26.8,10,47.5S26.8,85,47.5,85
        c9.6,0,18.4-3.6,25.1-9.6L87.2,90L90,87.2z M47.5,81C29,81,14,66,14,47.5C14,29,29,14,47.5,14S81,29,81,47.5C81,66,66,81,47.5,81z"/>
    </symbol>

    <!-- more <symbol> tags -->
</svg>
```

And my inline `<svg>` icons, which Parcel does **NOT** bundle, are like this:

```
<svg
    role="img"
    aria-labelledby="title-icon-search"
    focusable="false"
    class="icon"
>
    <title id="title-icon-search">search</title>
    <use xlink:href="#icon-search" />
</svg>
```

As a workaround for the Parcel hashing, I'm adding the sprite to the top of the `<body>` in every page rather than referencing the bundled sprite with `<use xlink:href="dist/svg-icon-defs.f3fae6c2.svg#icon-search" />`.
