### ISSUE TITLE
🐛 Unknown plugin *** in node_modules/**/.babelrc

### ISSUE THREAD

**Issue by Olian04** [parcel-bundler/parcel#435]
Parcel fails to bundle a project if one of its dependancies contains a `.babelrc` file with a plugin that you yourself are not using... 

![image](https://user-images.githubusercontent.com/5493406/34442760-7c13fbca-ecc4-11e7-9301-caa122006eab.png)

### 🤔 Expected Behavior

I expect parcel to not care what plugins a dep uses in its dev environment... 

### 😯 Current Behavior

As you can see in the image, parcel is complaining that the `.babelrc.env.development` file of the `react-dates` dependency is using a plugin that the current project isn't using.  

### 💁 Possible Solution

Don't parse transpiler configs for node modules.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.3.1
| Node             | 9.3.0
| Yarn         |  1.3.2
| Operating System | Ubuntu 17.04

**Comment by devongovett** [comment]
Dup of #13.
