### ISSUE TITLE
Parcel loads an incorrect WebWorker file if any WebWorker options are specified.

### ISSUE THREAD

**Issue by ahmed-musallam** [parcel-bundler/parcel#4350]
# 🐛 bug report

Parcel imports an incorrect WebWorker file if any WebWorker options are specified.

**Take this simple example:**

I have the following two files in the same directory:

```js
// main.js
console.log("test")
const worker = new Worker("./worker.js", {
  name: "test-worker"
})
```

```js
// worker.js
console.log("hi, I'm a webworker")
```

Then I run parcel on `main.js`:
```sh
parcel main.js
```

in dist, I see 2 files generated:
```js
main.js
worker.e19393a5.js
```

**The issue is: the _generated_ `dist/main.js` has this code:**

```js
var worker = new Worker("./worker.js", {
  name: "sample"
});
```

I expect it to have `./worker.e19393a5.js` instead of `./worker.js` so that it loads the correct file, but it does not.

**However, the following works:**

Now, if I change my source to remove the options object from the `Worker` constructor:

```js
// main.js
console.log("test")
const worker = new Worker("./worker.js")
```
it works as expected and the  the _generated_ `dist/main.js` has the correct path  `./worker.e19393a5.js`

Any idea why using the worker options causes this issue? 

Please note this also happens if I supply an empty options object.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel                 | 1.12.4   
| Node                  | v12.13.1
| npm/Yarn           | 6.12.1
| Operating System | OSX 10.14.5

**Comment by mischnic** [comment]
In Parcel 1, we check if the number of arguments is 1:
https://github.com/parcel-bundler/parcel/blob/14eaa0f4bcddc79efa3ba383dbd0726f16ca0276/packages/core/parcel-bundler/src/visitors/dependencies.js#L86

<br>

This is already fixed in Parcel 2

**Comment by ahmed-musallam** [comment]
@mischnic thanks for the quick response!! parcel 2 is not released yet, Is there a way I can fix this issue in v1? with a plugin maybe?
