### ISSUE TITLE
Parcel 2: dependency punycode is not support ES5

### ISSUE THREAD

**Issue by phamwon** [parcel-bundler/parcel#4357]
# 🐛 bug report

When build in production, final bundle has include script of punycode, but version of punycode > 1.4.1 is not support for ES5. Punycode lib has use in @parcel/node-libs-browser.

## 🎛 Configuration (.babelrc, package.json, cli command)

{ "browserslist": ["> 0.1%", "Android >= 5", "Chrome >= 48", "Firefox >= 20", "iOS >= 9"] }

## 😯 Current Behavior

Final bundle can't run on a old Browser (ex: Chrome 48)

## 💁 Possible Solution

Support run babel include with node_modules ?
 
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.157
| Node             | 13.10.1
| npm/Yarn         | npm 6.14.2 / yarn 1.22.4
| Operating System | Window 10

**Comment by mischnic** [comment]
> Support run babel include with node_modules ?

You can use the `include` option in a custom babelrc, but we should do this somehow automatically.
