### ISSUE TITLE
Parcel 2: HMR not working when react is a dev. dependency

### ISSUE THREAD

**Issue by dicearr** [parcel-bundler/parcel#4360]
# 🐛 bug report

When  `react` is installed as a development dependency HMR is not working.

## 🎛 Configuration (.babelrc, package.json, cli command)

Default.

## 🤔 Expected Behavior

I expected to see my component reloading whenever I change its source code no matter how I installed React.

## 😯 Current Behavior

The component is not reloading if I install React as a dev. dependency.

## 💁 Possible Solution

Debugging the problem I saw that the update sent via websocket is all the same but the `output` property. This are the differences I can see in the `output` between an update generated when React is installed as a dev. dependency and the same one (same file changes) when React is a dependency.

```diff
@@ -14,11 +14,15 @@
 
  var _react = _interopRequireWildcard(require(\"react\"));
 
+ var _s = $RefreshSig$();
+
  function _getRequireWildcardCache() { if (typeof WeakMap !== \"function\") return null; var cache = new WeakMap(); _getRequireWildcardCache = function () { return cache; }; return cache; }
 
  function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } if (obj === null || typeof obj !== \"object\" && typeof obj !== \"function\") { return { default: obj }; } var cache = _getRequireWildcardCache(); if (cache && cache.has(obj)) { return cache.get(obj); } var newObj = {}; var hasPropertyDescriptor = Object.defineProperty && Object.getOwnPropertyDescriptor; for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) { var desc = hasPropertyDescriptor ? Object.getOwnPropertyDescriptor(obj, key) : null; if (desc && (desc.get || desc.set)) { Object.defineProperty(newObj, key, desc); } else { newObj[key] = obj[key]; } } } newObj.default = obj; if (cache) { cache.set(obj, newObj); } return newObj; }
 
  const ChildComponent = () => {
+ _s();
+
  const [count, setCount] = (0, _react.useState)(0);
  return _react.default.createElement(\"p\", null, \"Foo with wooohooo state: \", count, \" \", _react.default.createElement(\"button\", {
  onClick: () => setCount(c => c + 1)
@@ -26,6 +30,14 @@
  };
 
  exports.ChildComponent = ChildComponent;
+
+ _s(ChildComponent, \"0y9ihJAcKCc4PLtrSDVu6q2+erM=\");
+
+ _c = ChildComponent;
+
+ var _c;
+
+ $RefreshReg$(_c, \"ChildComponent\");
  helpers.postlude(module);
 } finally {
  window.$RefreshReg$ = prevRefreshReg;

```

I won't mind to check the files involved in the `output` generation and propose a solution but I didn't have the time yet.

## 💻 Code Sample

1. Clone a repository in which fast refresh works nicely, for instance: `git clone https://github.com/astegmaier/parcel2-react-refresh`.
2. Run `npm install && npm start`.
3. Access the served application with your favorite browser.
4. Make changes to any file, for instance `sed -i 's/client/wooohooo/g' src/ChildComponent.js`.
5. You'll see that the application reloaded in the browser.
6. Now reinstall `react` as a development dependency `rm -r node_modules && npm uninstall react && npm install --save-dev react`.
7. Restart the web application.
8. Make changes again in the component `sed -i 's/wooohooo/all good/g' src/ChildComponent.js`, you'll notice that nothing changed in your browser.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | 12.14.0
| npm/Yarn         | 6.13.4
| Operating System | x86_64 GNU/Linux

**Comment by vazra** [comment]
I faced same issue, It can be reproduced from https://github.com/moctrash/parcel2-react-refresh by moving `react` and `react-doc` to dev deps.

**Comment by mischnic** [comment]
Is this still an issue?

I think this was fixed by https://github.com/parcel-bundler/parcel/pull/4999

**Comment by dicearr** [comment]
I don't think this is an issue anymore. I haven't been able to reproduce it with the latest version.  :+1:
