### ISSUE TITLE
Scope Hoisting: AssignmentExpressions (ex "var a = b += c") incorrectly factored out

### ISSUE THREAD

**Issue by mikehenrty** [parcel-bundler/parcel#4361]
# 🐛 bug report

This may turn out to be a bug in Babel (more about that below), but I think it's worth discussing here in Parcel-land first to decide on how to approach this.

The bug is that with scope hoisting enabled, the following code:
```javascript
var _thingy = 1;
var b =  _thingy += 2;
console.log(b);
```

 will get incorrectly optimized to:
```javascript
(function(){
// ASSET: /app/src/index.js
var $c9c6682be82cddc16ea99aceca520460$var$b = 2;
console.log($c9c6682be82cddc16ea99aceca520460$var$b);
})();
```

The first issue is that this will output the wrong thing (`2` instead of `3`). But the problem is compounded when the code depends on that nested assignment. For instance, in [three.js](https://threejs.org/) we have something like the following:

```javascript
var _bufferGeometryId = 1; // BufferGeometry uses odd numbers as Id

function BufferGeometry() {
	Object.defineProperty( this, 'id', { value: _bufferGeometryId += 2 } );
```
[Source](https://github.com/mrdoob/three.js/blob/2561e944e1f69ae02c3bf1e71d6bf80ddc73a53c/src/core/BufferGeometry.js#L29)

When we compile three.js as a dependency with scope hoisting enabled in Parcel, this `id` will be changed to the literal `2` for every instance of buffer geometry (while the `_bufferGeomoetryId` variable will be eliminated). This can cause subtle (and not so subtle) bugs in Three's rendering logic since it expects those id's to be unique for each `BufferGeometry` instance.

## 🎛 Configuration (.babelrc, package.json, cli command)

This bug happens with out-of-the-box configurations for Parcel 2. You can see this bug in action at [this Parcel REPL](https://parcel2-repl.now.sh/#JTdCJTIyY3VycmVudFByZXNldCUyMiUzQSUyMkphdmFzY3JpcHQlMjIlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIybWluaWZ5JTIyJTNBZmFsc2UlMkMlMjJzY29wZUhvaXN0JTIyJTNBdHJ1ZSUyQyUyMnNvdXJjZU1hcHMlMjIlM0FmYWxzZSUyQyUyMnB1YmxpY1VybCUyMiUzQSUyMiUyMiUyQyUyMnRhcmdldFR5cGUlMjIlM0ElMjJicm93c2VycyUyMiUyQyUyMnRhcmdldEVudiUyMiUzQW51bGwlMkMlMjJvdXRwdXRGb3JtYXQlMjIlM0FudWxsJTJDJTIyc2hvd0dyYXBocyUyMiUzQWZhbHNlJTdEJTJDJTIyYXNzZXRzJTIyJTNBJTVCJTVCJTIyc3JjJTJGaW5kZXguanMlMjIlMkMlMjJ2YXIlMjBfdGhpbmd5JTIwJTNEJTIwMSUzQiU1Q252YXIlMjBiJTIwJTNEJTIwJTIwX3RoaW5neSUyMCUyQiUzRCUyMDIlM0IlNUNuY29uc29sZS5sb2coYiklM0IlMjIlMkMxJTVEJTVEJTdE).

## Context

I looked into the Parcel scope hoisting code a tiny bit, and I believe part of the problem happens in [shake.js](https://github.com/parcel-bundler/parcel/blob/161837f71682f13d2b16e7396e82eb620fe06e4e/packages/shared/scope-hoisting/src/shake.js#L65).

```
  if (!binding.referenced && pure) {
    return binding;
  }
```
In the case of `BufferGeometry`, the variable `_bufferGeometryId` does not get a reference count from the Babel crawler for it's AssigmentExpression `value: _bufferGeometryId += 2`, and so the Scope Hoisting tree shaking logic removes it as an unused binding. But I'm not sure how `+=2` becomes `=2`.

I searched in Babel to see if this was a known bug, but the closest thing I found was this:
https://github.com/babel/babel/issues/2557

From that bug, its seems like the Babel maintainer recognizes that counting references in the following AssigmentExpression `a++` should behave the same as `a +=1` (and it currently ref counts `a++` but doesn't ref count `a+=1`). But the bug lost steam and was eventually closed as stale.

## 💁 Possible Solutions 

We could try to convince the Babel maintainers that this is a bug in their crawler (which I believe they would be open to). Or we could just workaround this in Parcel, but it's not entirely clear how.

Btw, thanks to the maintainers for all their hard work on Parcel! I am super excited about v2, and continually reach for Parcel as my build tool of choice whenever I have the freedom to do so. Keep it up!

**Comment by mischnic** [comment]
Does this still happen for you? The output from the current v2 branch (and from v2 at the time of your post) is:
```js
(function(){
var $ede061e2941ef3845e57af1da04905$var$_thingy = 1;
var $ede061e2941ef3845e57af1da04905$var$b = $ede061e2941ef3845e57af1da04905$var$_thingy += 2;
console.log($ede061e2941ef3845e57af1da04905$var$b, $ede061e2941ef3845e57af1da04905$var$_thingy);
})();
```

**Comment by mikehenrty** [comment]
I can't reproduce it anymore! Will close.

>  and from v2 at the time of your post ?!

Here's the weird thing: if manually check out a v2 commit from the time of my post and run `parcel build`, I can't reproduce the problem.

But, if I go into my project repo which included Parcel@Next at the time, I can still reproduce. I'll post the package.json file in parcel's node_module folder in case it helps. I also will keep a copy of the code locally in case we want to drill into this.

I'm also quite sure the Parcel REPL was reproducing the bug at the time. A even did a live demo of the problem to a colleague using that REPL link.

In any case, if we are interested in figuring out what happened there, I'm happy to look into this more. But I'm also just happy that it's fixed, so unless otherwise instructed will leave it as "works for me!"

```
{
  "name": "parcel",
  "version": "2.0.0-nightly.165+b9e4105c",
  "license": "MIT",
  "publishConfig": {
    "access": "public"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/parcel-bundler/parcel.git"
  },
  "bin": "lib/bin.js",
  "main": "lib/bin.js",
  "source": "src/bin.js",
  "engines": {
    "node": ">= 10.0.0"
  },
  "dependencies": {
    "@parcel/config-default": "2.0.0-nightly.167+b9e4105c",
    "@parcel/core": "2.0.0-nightly.165+b9e4105c",
    "@parcel/diagnostic": "2.0.0-nightly.167+b9e4105c",
    "@parcel/fs": "2.0.0-nightly.167+b9e4105c",
    "@parcel/logger": "2.0.0-nightly.167+b9e4105c",
    "@parcel/package-manager": "2.0.0-nightly.167+b9e4105c",
    "@parcel/utils": "2.0.0-nightly.167+b9e4105c",
    "chalk": "^2.1.0",
    "commander": "^2.19.0",
    "get-port": "^4.2.0",
    "react": "^16.7.0",
    "v8-compile-cache": "^2.0.0"
  },
  "devDependencies": {
    "@parcel/babel-register": "2.0.0-nightly.167+b9e4105c"
  },
  "gitHead": "b9e4105c50576ed22a99860e08e65491d4659a43"
}
```

**Comment by mischnic** [comment]
[Here is a REPL that was deployed 22 days ago, it does happen there](https://parcel2-repl-7t3vcjpj8.now.sh/#JTdCJTIyY3VycmVudFByZXNldCUyMiUzQSUyMkphdmFzY3JpcHQlMjIlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIybWluaWZ5JTIyJTNBZmFsc2UlMkMlMjJzY29wZUhvaXN0JTIyJTNBdHJ1ZSUyQyUyMnNvdXJjZU1hcHMlMjIlM0FmYWxzZSUyQyUyMnB1YmxpY1VybCUyMiUzQSUyMiUyMiUyQyUyMnRhcmdldFR5cGUlMjIlM0ElMjJicm93c2VycyUyMiUyQyUyMnRhcmdldEVudiUyMiUzQW51bGwlMkMlMjJvdXRwdXRGb3JtYXQlMjIlM0FudWxsJTJDJTIyc2hvd0dyYXBocyUyMiUzQWZhbHNlJTdEJTJDJTIyYXNzZXRzJTIyJTNBJTVCJTVCJTIyc3JjJTJGaW5kZXguanMlMjIlMkMlMjJ2YXIlMjBfdGhpbmd5JTIwJTNEJTIwMSUzQiU1Q252YXIlMjBiJTIwJTNEJTIwJTIwX3RoaW5neSUyMCUyQiUzRCUyMDIlM0IlNUNuY29uc29sZS5sb2coYiklM0IlMjIlMkMxJTVEJTVEJTdE)

<br>

It is still removed when commenting out this check
https://github.com/parcel-bundler/parcel/blob/297087a806f9ed958fad1e2217d735b284cd3d5c/packages/shared/scope-hoisting/src/shake.js#L69-L76
But if `hasSideEffects` was better optimized, it would remote `_thingy` as well (and cause the incorrect behaviour). So we should add the example to the test suite.
