### ISSUE TITLE
--dist-dir should override package.json main field

### ISSUE THREAD

**Issue by dephiros** [parcel-bundler/parcel#4363]
# 🙋 feature request

In #4113, I saw the team has added back  --dist-dir. However, it is unexpected to me that this option has lower priority than package.json main field.

## 🤔 Expected Behavior

 I would expect cli option take precedence over config

**Comment by mischnic** [comment]
The idea was that the config in package.json is more specific (per target) then the flag (for all targets) and so the more specific one applies.

cc @devongovett

**Comment by kflorence** [comment]
I just ran into this for `--public-url` and I also find it very unintuitive. I can't think of any other tools I use that don't allow CLI flags to override configuration. In my case, I am also building for a single target (`parcel build --target=web --public-url=./foo/bar`).
