### ISSUE TITLE
Could not resolve bundle for dynamic imports in inline script tag

### ISSUE THREAD

**Issue by garthenweb** [parcel-bundler/parcel#4365]
# 🐛 bug report

Using an inline script block in HTML file including a dynamic imported module, the build will throw at runtime with `Uncaught Error: Could not resolve bundle with id ...`.

## 🎛 Configuration (.babelrc, package.json, cli command)

See https://github.com/garthenweb/parcel-bug-report-examples/tree/bug/dynamic-inline-import-cannot-resolve-bundle

## 🤔 Expected Behavior
 
It should fetch the dynamic imported module and execute it properly.

## 😯 Current Behavior

Fails with `Uncaught Error: Could not resolve bundle with id ...`.

## 💁 Possible Solution

Moving the dynamic import out of the `index.html` into the `index.js` works properly.

## 🔦 Context

I am not sure if running an `import` from an inlined bundle is valid JavaScript, so maybe it could be ignored.

But I figured this out when importing a service worker from HTML which is kind of a common behavior from my point of view:

```html
<script async>
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('./service-worker.js');
  }
</script>
```

## 💻 Code Sample

See https://github.com/garthenweb/parcel-bug-report-examples/tree/bug/dynamic-inline-import-cannot-resolve-bundle

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.163
| Node             | v12.8.1
| npm         | v6.14.3
| Operating System | Windows (WSL v1/ Ubuntu Bash)

**Comment by mischnic** [comment]
> I am not sure if running an import from an inlined bundle is valid JavaScript.

Yes it is.

This has something to do with the runtime manifest: https://github.com/parcel-bundler/parcel/blob/f2a62434adbba86bdd56774833d70d7852988ed1/packages/runtimes/js/src/bundle-manifest.js

**Comment by devongovett** [comment]
Appears to work in the latest nightly.
