### ISSUE TITLE
Inline style causes build failure

### ISSUE THREAD

**Issue by hekevintran** [parcel-bundler/parcel#4367]
# 🐛 bug report

I have this HTML code.  If I delete one of the p tags it will compile but will fail when both are there.  I put the code in a repo https://github.com/hekevintran/parcel-crash

```html
<html>
  <head>
  </head>
  <body>
    <p style="font-family: sans-serif; color: white;"></p>
    <p style="font-family: sans-serif; color: white;"></p>
  </body>
</html>
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "parcel-crash",
  "version": "1.0.0",
  "description": "",
  "main": "dist/main/index.html",
  "scripts": {
    "build-works": "parcel build src/works.html",
    "build-fails": "parcel build src/fails.html"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "parcel": "^2.0.0-alpha.3.2"
  }
}
```

## 🤔 Expected Behavior

I expect inline styles not to make the compiler fail.

## 😯 Current Behavior

Using one p tag with inline styles will compile.  Using 2 p tags with inline styles will fail to compile.

```bash
> parcel build src/index.html

🚨 Build failed.
@parcel/core: Failed to resolve 'c8466d280fe801e394acdfaed9bae1b9' from './src/index.html'
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2|
| Node             |12.10.0|
| npm/Yarn         |npm 6.11.3|
| Operating System | macOS 10.14.6|

**Comment by mischnic** [comment]
I don't get this with your example, only with 
```html
<img src="http://example.com/img.png" style="margin-top: 5px;" />
<img src="http://example.com/img.png" style="width: 120px;" />
<span style="font-size: 25px;">REPL</span>
```
