### ISSUE TITLE
🐛 Cannot resolve dependency for `itms-apps://...`

### ISSUE THREAD

**Issue by hkwid** [parcel-bundler/parcel#437]
When I tried to use the app store link like `itms-apps://itunes.apple.com/en/app/awesomeApp/id1234567890` as `href` attr.
Get `Cannot resolve dependency` error.

```html
<!-- index.html -->
...
<a href="itms-apps://itunes.apple.com/en/app/awesomeApp/id1234567890">App Store Link</a>
...
```

### 🎛  Configuration

```bash
$ parcel src/index.html
```

### 🤔  Expected Behavior

When the URI schema is valid, it should not try to resolve the dependency.

### 😯  Current Behavior

Even the URI schema is valid, it tries to resolve the dependency.
The error log is like below

```bash
/path/to/the/project/src/index.html: Cannot resolve dependency './itms-apps:/itunes.apple.com/en/app/awesomeApp/id1234567890' at '/path/to/the/project/src/itms-apps:/itunes.apple.com/en/app/awesomeApp/id1234567890'
at /path/to/the/project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
at load (/path/to/the/project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
at onex (/path/to/the/project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
at /path/to/the/project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
at FSReqWrap.oncomplete (fs.js:152:21)
```

### 💁 Possible Solution

According to wiki [https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax), URI schema can include `.`, `-`, `+` ... etc.

Maybe tweak `SCHEME_REGEXP` in `src/utils/is-url.js` to cover such a schemas.

**Comment by devongovett** [comment]
Should be fixed by #438 which will be in a release shortly.
