### ISSUE TITLE
Using scope hoisting with aliased library results in runtime failure (with minimal reproduction)

### ISSUE THREAD

**Issue by ncthbrt** [parcel-bundler/parcel#4373]
# 🐛 Bug report

## 🤔 Expected Behavior

Application to correctly minify and treeshake required dependencies.

## 😯 Current Behavior
Application either incorrectly mangles dependencies or does not include them in the bundle. 

## Context
Our app was initially using React, Parcel and Typescript, but in an effort to reduce bundle size, we switched to preact using the aliasing method as detailed in this [user guide](https://preactjs.com/guide/v10/getting-started#aliasing-in-parcel). This worked flawlessly. 

In a further effort to reduce bundle size, I added the  `--experimental-scope-hoisting` flag to our build. This resulted in a number of different runtime errors when running a production build, seemingly related to missing dependencies, so I reverted back. I also tried another configuration which excluded minification, but got similar missing reference errors. 

Later investigating further, I started wondering if the problem was related to aliasing, so I modified the react imports in my `index.tsx` from the following: 
```ts
import * as React from "react";
import * as ReactDOM from "react-dom";
```
To:
```ts
import * as React from "preact/compat";
import * as ReactDOM from "preact/compat";
```
Running a production build with these changes resulting in a working application.

## Reproduction
Here is a link to a repository containing a minimal reproduction of the issue: 
https://github.com/ncthbrt/parcel-preact-treeshaking-error-reproduction

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  v1.12.4
| Node             |  v12.11.1
| npm        |  v6.11.3
| OS |  Windows 10 & Alpine Docker on Kubernetes

**Comment by maerteijn** [comment]
I was checking your repo to see if it has anything to do with #4410, it isn't, but while debugging I noticed that the same aliases with different keys (`react` and `react-dom`) seems to break it.

Adjusting your  `package.json` aliases to something like:
```
  "alias": {
    "react": "preact/compat",
    "react-dom/test-utils": "preact/test-utils",
    "react-dom": "preact/compat/dist/compat.js"
  }
```

"resolves" the issue. Not sure why and how (yet), but I thought I let you know.

**Comment by ncthbrt** [comment]
Thanks @maerteijn that's an interesting work around.
