### ISSUE TITLE
parcelRequire is not defined in service worker

### ISSUE THREAD

**Issue by garthenweb** [parcel-bundler/parcel#4374]
# 🐛 bug report

When using a service worker that shares dependencies with another child bundle, it throws with `Uncaught ReferenceError: parcelRequire is not defined` at runtime.

Looks like this is working without scope hoisting.

## 🎛 Configuration (.babelrc, package.json, cli command)

See https://github.com/garthenweb/parcel-bug-report-examples/tree/bug/service-worker-parcelerquire-not-defined

## 🤔 Expected Behavior

It throws with `Uncaught ReferenceError: parcelRequire is not defined` within the service worker.

## 😯 Current Behavior

Should not fail when accessing `parcelRequire` or not access it at all.

## 💁 Possible Solution

This setup injects promise polyfill which is required in all 3 bundles.
The service worker tries to register its export globally, which does not work as `parcelRequire` is not available within the service worker.

Maybe we just need to inject their own instance of `parcelRequire` into the service worker bundle?

## 💻 Code Sample

See https://github.com/garthenweb/parcel-bug-report-examples/tree/bug/service-worker-parcelerquire-not-defined

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.163
| Node             | v12.8.1
| npm         | v6.14.3
| Operating System | Windows (WSL v1/ Ubuntu Bash)

**Comment by mischnic** [comment]
The relevant code: https://github.com/parcel-bundler/parcel/blob/d05b3ccf15b9ad9ffbcb6dad64b7b655624f5789/packages/shared/scope-hoisting/src/utils.js#L38-L46

**Comment by wbinnssmith** [comment]
I also encountered this. At least in my case, it looks like the issue isn't that this worker needs the prelude, but that it shouldn't be registering assets in the first place.

We always add `parcelRequire.register()` calls if the asset is referenced by any bundle, regardless is that bundle is reachable by this particular entry [0]. Then, we only add the prelude if the bundle if this entry has js children or siblings [1] — in my case the worker had no children nor siblings.

[0] https://github.com/parcel-bundler/parcel/blob/e75bad2ff98eea4a02290bd74d71d1f77131e68e/packages/shared/scope-hoisting/src/link.js#L113

[1] https://github.com/parcel-bundler/parcel/blob/e75bad2ff98eea4a02290bd74d71d1f77131e68e/packages/shared/scope-hoisting/src/formats/global.js#L94

**Comment by mischnic** [comment]
@garthenweb This seems to have been fixed by #4391. Does it work for you now?

**Comment by garthenweb** [comment]
A, really cool. I just checked it out and can confirm its working like a charm now! Thank you :)
