### ISSUE TITLE
Source map comment get removed after minify

### ISSUE THREAD

**Issue by Austaras** [parcel-bundler/parcel#4388]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

running `parcel build <something>`

## 🤔 Expected Behavior

Parcel generate source map correctly, and have a source map comment on the end of file

## 😯 Current Behavior

Parcel generate source map correctly, but comment got removed so source map is not detected by browser, unless pass `--no-minify` flag.

## 🔦 Context

I'd like browser auto detecting source map even minified

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.175|
| Node             |13.11|
| npm/Yarn         |yarn |
| Operating System |linux|

**Comment by mischnic** [comment]
As I understand it, this was just fixed by https://github.com/parcel-bundler/parcel/pull/4358, should be in the next nightly.

**Comment by DeMoorJasper** [comment]
A fix for this has been merged a couple hours ago, should be live in the next nightly https://github.com/parcel-bundler/parcel/commit/c9c9b755cf9be72a5cf6f1c8ec8d4c150c6bea08

**Comment by Austaras** [comment]
Wow, that's fast. I will test with new nightly build when it's out
