### ISSUE TITLE
Parcel 2 (latest nightly) generates a `.map` file with `--no-source-maps`.

### ISSUE THREAD

**Issue by utkarshkukreti** [parcel-bundler/parcel#4390]
# 🐛 bug report

Parcel 2 (latest nightly) generates a `.map` file with `--no-source-maps`.

To reproduce:

```
$ yarn parcel --version
2.0.0-nightly.180+a1a2515f

$ cat a.js
console.log(1 + 2);

$ rm -rf dist && yarn parcel build a.js && cat dist/a.js.map
dist/a.js    46 B     10ms
└── a.js     20 B    655ms

{"mappings":"AAAAA,QAAQC,IAAI","sources":["a.js"],"names":["console","log"],"version":3,"file":"a.js.map","sourcesContent":["console.log(1 + 2);\n"]}                                                                                          

$ rm -rf dist && y parcel build --no-source-maps a.js && cat dist/a.js.map
dist/a.js    46 B      2ms
└── a.js     20 B    655ms

{"mappings":"AACAA,QAAQC,IAAI","sources":["0"],"names":["console","log"],"version":3,"file":"a.js.map","sourcesContent":[null]}
```
With `--no-source-maps`, `dist/a.js.map` is still generated (it doesn't have `sourcesContent` though).

## 🤔 Expected Behavior

`.map` file should not be generated.

## 😯 Current Behavior

`.map` file is generated.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.180+a1a2515f
| Node             | v13.11.0
| npm/Yarn         | yarn 1.22.4
| Operating System | macOS 10.15.3

**Comment by DeMoorJasper** [comment]
Will look into this and create a fix later today

**Comment by utkarshkukreti** [comment]
@DeMoorJasper thanks, the new nightly works!

**Comment by steelcracker** [comment]
Hmm.. parcel@nigthly.230 - ok with `parcel build`.
But still generates a 1kb js.map with `parcel watch`
