### ISSUE TITLE
Parcel 2: --target flag uses wrong package.json

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#4392]
# 🐛 bug report

Using the `--target` flag searches for its target in the root package.json of a monorepo instead of using its local package.json

```diff
- × Build failed.
- @parcel/core: Could not find target with name "test"
```

By the way, it's not just the search for the targets that's wrong, the dist path is also resolved from the root of the monorepo

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`
```json
{
  "private": true,
  "version": "1.0.0",
  "license": "MIT",
  "workspaces": [
    "packages/*"
  ],
  // If you uncomment these lines, it works
  // "test": "dist/test.js",
  // "targets": {
  //   "test": {
  //     "engines": {
  //       "browsers": [
  //         "last 1 chrome version"
  //       ]
  //     }
  //   }
  // }
}
```

`packages/core/package.json`
```js
{
  "test": "dist/test.js",
  "targets": {
    "test": {
      "engines": {
        "browsers": [
          "last 1 chrome version"
        ]
      }
    }
  },
  "scripts": {
    "dev": "parcel watch src/test.ts --target test --no-hmr"
  },
  "devDependencies": {
    "parcel": "^2.0.0-nightly.180"
  }
}
```

**Comment by vadistic** [comment]
Hah, I've just spend hour thinking something wrong with my config :)

`configPath` here is null

https://github.com/parcel-bundler/parcel/blob/db7e3a12105630abc44058bff7a88eb612f12e75/packages/core/core/src/loadParcelConfig.js#L50-L62

beacuse `dir` in `getResolveFrom` gets monorepo root dir

https://github.com/parcel-bundler/parcel/blob/db7e3a12105630abc44058bff7a88eb612f12e75/packages/core/core/src/loadParcelConfig.js#L50-L62

**Comment by mischnic** [comment]
Running `parcel build some/file` in a monorepo will use the root package.
Running `parcel build packages/core` in a monorepo will use the targets (and `source`) specified in `packages/core/package.json`.

I think we do plan to change this. @devongovett
