### ISSUE TITLE
Cannot resolve mailto: and tel: URIs dependencies

### ISSUE THREAD

**Issue by aurelienlewin** [parcel-bundler/parcel#44]
Hello,

If you use `mailto:` or `tel:` in your `href` anchors attributes, the build fails to resolve dependencies.

`$ parcel build src/index.html
🚨  /Users/a/Documents/a/a/src/index.html: Cannot resolve dependency './tel:+336…'`

**Comment by thejameskyle** [comment]
lol, amazing. [Relevant code is here](https://github.com/parcel-bundler/parcel/blob/7b899b38930a7a30943a6148f475a5007ce2c625/src/assets/HTMLAsset.js#L33)

**Comment by prichodko** [comment]
I'd love to take over this. Just to clear things up: Should we ignore something else? Like `href="#..."` or what if `target` is present?

**Comment by thejameskyle** [comment]
I don't think you need to worry about target either

**Comment by g3r4n** [comment]
Seems to be fixed in #50 ?
