### ISSUE TITLE
Wrong method called if build with NODE_ENV = "production"

### ISSUE THREAD

**Issue by JackD83** [parcel-bundler/parcel#4408]
# 🐛 bug report

I'm converting a very large project that was based on requirejs over to es6 and parcel. 
Its consisting of many different libs, some from npm and some own libraries. 

As I have a lot of different APIs, I use parcel-proxy-server to start my development server and everything worked fine. Whole project builds and can be used. 
Then I tried to integrate in own build process using `npm run build` with a very simple `parcel build ./index.html ` and that is where the fun starts. 

The main libraries we use are openlayers and cesiumjs and cesium fails now during creation of the globe.

I tracked it down to this call in one of the classes:
` result._template = clone(defaultValue(options.fabric, defaultValue.EMPTY_OBJECT));`

The clone method is the problem. Its imported using 
`import clone from '../Core/clone.js';`

In the development build, this is correctly imported, in the production build, clone **points to a completely unrelated method** and then the code obviously fails.

I tried to reproduce this error with only CesiumJS, but the error does not occur. 
Adding `--no-minify` does not help

If I start the parcel-proxy-server with `process.env.NODE_ENV = "production"` I get the same error as with parcel build

I would appreciate if someone can point me into the right direction!

## 🎛 Configuration (.babelrc, package.json, cli command)

I played with the .terserrc, but without any results

## 🤔 Expected Behavior

Production builds should behave like the development builds

## 🌍 Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | v12.16.1
| npm/Yarn         | npm 6.13.4
| Operating System | Windows 10

**Comment by zhaoyao91** [comment]
Similar problem. staging works well, but production version which was built with `NODE_ENV=production` doesn't work.
