### ISSUE TITLE
Scope hoisting not working correctly with `import _ from “lodash”`

### ISSUE THREAD

**Issue by maerteijn** [parcel-bundler/parcel#4410]
# 🐛 bug report
When I import `lodash` and build a really basic setup with `--experimental-scope-hoisting`, all browsers will display an error:
```
ReferenceError: require is not defined
```

This happens with:
```js
import _ from "lodash"
```
or 
```js
var _ = require('lodash')
```

When `--experimental-scope-hoisting` is not used, this does not occur.

## 🎛 Configuration (.babelrc, package.json, cli command)
I did not use any custom babel configuration.

I've created a [demo repository ](https://github.com/maerteijn/parcel-lodash-scope-hoisting-example)with the following package.json:
```package.json
{
  "name": "parcel-lodash-scope-hoisting-example",
  "version": "0.0.1",
  "main": "index.js",
  "scripts": {
    "dev": "parcel index.html",
    "build": "parcel build index.html --public-url ./",
    "build:scope-hoisting": "parcel build index.html --public-url ./ --experimental-scope-hoisting"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/maerteijn/parcel-lodash-scope-hoisting-example.git"
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.4"
  },
  "dependencies": {
    "lodash": "^4.17.15"
  }
}
```

## 🤔 Expected Behavior
A working bundle without JavaScript errors

## 😯 Current Behavior
A bundled JavaScript file which displays the error console message `ReferenceError: require is not defined` is all browsers.

## 🔦 Context

I can only reproduce this when I use `lodash`, and only with `import _ from "lodash"`. With specific imports like:
```js
import lowerCase from "lodash/lowercase"
```
all is fine.

(Probably) related issues: #3288 and #3625

## 💻 Code Sample

Reproducable when you use this repo: https://github.com/maerteijn/parcel-lodash-scope-hoisting-example
```bash
npm run build:scope-hoisting
```
Then open the built `index.html` in any browser. See also the README .

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 12.16.1
| Lodash             | 4.17.15
| npm/Yarn         | 6.13.4
| Operating System | Mac OSX Mojave (10.14.6)

**Comment by maerteijn** [comment]
Some extra info after some debugging.

in [assets/JSAsset.js](https://github.com/parcel-bundler/parcel/blob/1.x/src/assets/JSAsset.js#L181):
```javascript
      if (GLOBAL_RE.test(this.contents)) {
        await this.parseIfNeeded();
        walk.ancestor(this.ast, insertGlobals, this);
      }
```
`GLOBAL_RE.test(this.contents))` evaluates to True, so `insertGlobals` is inserted. Insert globals is an import of  [src/visitors/globals](https://github.com/parcel-bundler/parcel/blob/1.x/src/visitors/globals.js#L14) so the following code is run:
```javascript
    asset.addDependency('buffer');
    return 'var Buffer = require("buffer").Buffer;';
```
But the `buffer` package is not there in the final bundle (probably the scope hoisting removes it again ?), nor is the[ prelude code](https://github.com/parcel-bundler/parcel/blob/1.x/src/builtins/prelude2.js#L1) inserted which causes `require` to work in a browser, so my guess is that some optimizations in the hoisting are biting with this `insertGlobals`.

The `GLOBAL.RE` matches anything with the word "Buffer" in it, so maybe this regex is a bit too generic?

**Comment by mischnic** [comment]
This works in Parcel 2.

> The GLOBAL.RE matches anything with the word "Buffer" in it, so maybe this regex is a bit too generic?

We first check if "Buffer" is used and only then actually traverse the asset and do further (slower) checks.

**Comment by maerteijn** [comment]
> This works in Parcel 2.
> We first check if "Buffer" is used and only then actually traverse the asset and do further (slower) checks.

I tested this with Parcel 2 and indeed it's working correctly. After your comment I started comparing what's different between Parcel 1 and Parcel 2, and it this `GLOBAL_RE` was not causing the problem:

[Parcel 1](https://github.com/parcel-bundler/parcel/blob/v2/packages/core/parcel-bundler/src/assets/JSAsset.js#L100):
```javascript
  async transform() {
    if (this.options.target === 'browser') {
    ...
      if (GLOBAL_RE.test(this.contents)) {
        await this.parseIfNeeded();
        walk.ancestor(this.ast, insertGlobals, this);
      }
    }
```

[Parcel 2](https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/js/src/JSTransformer.js#L63):
```javascript
async transform({asset, options, logger}) {
    ...
    if (!asset.env.isNode()) {
    ...
      // Insert node globals
      if (code == null || GLOBAL_RE.test(code)) {
        let globals: GlobalsMap = new Map();
        walkAncestor(ast.program, insertGlobals, {asset, globals});

        if (globals.size > 0) {
          ast.program.program.body.unshift(
            ...[...globals.values()]
              .filter(Boolean)
              .map(({code}) => template.statement(code)()),
          );
          isASTDirty = true;
        }
      }
    }
```

The Parcel 2 version is a bit more developed but the essential code here, call `walkAncestor` to with `insertGlobals`, is the same.

So the next thing was to check what `insertGlobals` is doing and see what's different:

[Parcel 1](https://github.com/parcel-bundler/parcel/blob/v2/packages/core/parcel-bundler/src/visitors/globals.js#L28):
```javascript
  Identifier(node, asset, ancestors) {
    let parent = ancestors[ancestors.length - 2];
    if (
      VARS.hasOwnProperty(node.name) &&
      !asset.globals.has(node.name) &&
      types.isReferenced(node, parent)
    ) {
      asset.globals.set(node.name, VARS[node.name](asset));
    }
  }
```

[Parcel 2](https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/js/src/visitors/globals.js#L50):
```javascript
  Identifier(node: any, context: TraverseContext, ancestors: any) {
    let parent = ancestors[ancestors.length - 2];
    if (
      VARS.hasOwnProperty(node.name) &&
      !context.globals.has(node.name) &&
      types.isReferenced(node, parent) &&
      !types.isModuleSpecifier(parent) &&
      !hasBinding(ancestors, node.name)
    ) {
      context.globals.set(node.name, VARS[node.name](context.asset));
    }
  }
```

Again, in essence the same, but some extra check are being done in Parcel 2 (`!isModuleSpecifier` and `!hasBinding`). When I applied these checks in Parcel 1, [the bundling of the example with `_ from lodash`](https://github.com/maerteijn/parcel-lodash-scope-hoisting-example/tree/with-4410-parcel-1-fix-global-insertions) is correct with scope hoisting enabled.

See the diff: https://github.com/maerteijn/parcel/compare/backport-parcel-1.12.4...maerteijn:4410-parcel-1-fix-global-insertions

I also updated the test repository to demonstrate the fix: https://github.com/maerteijn/parcel-lodash-scope-hoisting-example/tree/with-4410-parcel-1-fix-global-insertions

So this looks good but...

**Comment by maerteijn** [comment]
Where is the Parcel 1 source-tree?

I'm confused where the Parcel 1 source-tree lives now.There is a [1.x branch](https://github.com/parcel-bundler/parcel/tree/1.x) but that is not updated since October 2018 (and latest version is 1.10.3).

Then I assumed that Parcel 1 is now in the [v2 source tree](https://github.com/parcel-bundler/parcel/tree/v2/packages/core/parcel-bundler), hence the convenient `./node_modules/.bin/parcel1` link.

But that version is pretty broken (mostly dependencies updated when the code was not), so I had to [backport the released 1.12.4 version first](https://github.com/maerteijn/parcel/compare/v2...maerteijn:backport-parcel-1.12.4).

I could not run the testsuite because the `devDependencies` also seem to be different / not updated / out of sync ([@parcel/test-utils](https://github.com/parcel-bundler/parcel/issues/4241) is not released?) I also saw that the [tests for the `parcel-bundler` package](https://github.com/parcel-bundler/parcel/blob/v2/.mocharc.json#L2) are disabled.

Before trying to fix the testrunner: Maybe there is another repository I'm not aware of where the Parcel 1 source-tree lives?

And on a more global scale: Is there still a future left for Parcel 1 before Parcel 2 is stable and feature complete?

**Comment by mischnic** [comment]
I wasn't aware of these problems.

> Maybe there is another repository I'm not aware of where the Parcel 1 source-tree lives?

No

> Is there still a future left for Parcel 1 before Parcel 2 is stable and feature complete?

No 😬, maintaining two versions would not be feasible.

**Comment by maerteijn** [comment]
Ok, so what to do with this issue. Shall I open a PR to fix the problems of Parcel 1 in the v2 source tree then? 

And Is there a chance of a release of Parcel 1 with the patch included, if so shall I add this as a PR as well?

**Comment by maerteijn** [comment]
I was able to fix the package so the [testrunner works again](https://github.com/maerteijn/parcel/compare/v2...maerteijn:backport-parcel-1.12.4) with a [separate command](https://github.com/maerteijn/parcel/commit/cad701f08ca56d49c494213d9e3e20daef5765ff). 

Mostly restoring what worked before as the tests for parcel 1 are not adapted to the `MemoryFS ncp` version for example.

Let me know if any further action (opening PR's) is desired.

**Comment by iam-markus** [comment]
I have the same issue of not being able to use scope-hoisting in production for parcel 1.
Makes a huge difference (2MB vs 300KB).

If this won't be fixed in the future, how can I get these changes into my project?

**Comment by devongovett** [comment]
Have you tried Parcel 2? Lots of scope hoisting bugs have been fixed there.

**Comment by iam-markus** [comment]
Thanks for the quick answer!
I am just concerned to use parcel 2 in production, as my impression is that is unfinished (alpha 3).

PS: Ok, just looked at the project board, and from there it seems that it's mostly new features going to be added for the final release? If that is the case, and it's already stable, I guess I should try parcel 2.

**Comment by mischnic** [comment]
>  it's already stable

I wouldn't call it stable, but the areas that are not 100% working are: caching, scope hoisting, builds with extensive code splitting

**Comment by iam-markus** [comment]
@mischnic Just so I understand correctly: It's not as stable as parcel 1 in the areas you mentioned, but fixes this specific issue?

**Comment by mischnic** [comment]
Scope hoisting: way less bugs than Parcel 1, but not sure completely sure about "stable"
Cache: not as stable Parcel 1
Code splitting: Parcel 2 does much more intelligent code splitting (shared bundles, also for workers), not sure how it compares to Parcel 1

**Comment by iam-markus** [comment]
Tried parcel 2, unfortunately it's not working with my setup (no output, just hangs).

Is there a way to import lodash in a correct way, some type of workaround? (several libraries I use, depend on lodash).
As parcel is part of our build pipeline, parcel is installed via yarn, so I can't really use another version instead, right? (like @maerteijn 's fixed version)

**Comment by maerteijn** [comment]
I'd be happy to provide a PR for the branch if desired if the the Parcel maintainers find it useful.

A workaround is to not import / require all of lodash but just the functions you need, for example:
```javascript
import lowerCase from "lodash/lowercase"
```
It looks like scope hoisting in parcel 1 will work correctly then.

**Comment by iam-markus** [comment]
Thanks @maerteijn, but the workaround to not import all of lodash would work if it were for my code only, but I unfortunately have no control over how other libraries include it (libraries which I depend on).

This is why I am trying to include a forked version of maerteijn's branch in my project: https://github.com/iam-markus/parcel/tree/4410-parcel-1-fix-global-insertions
```
"devDependencies": {
    "@babel/preset-env": "^7.8.7",
    "@babel/preset-react": "^7.8.3",
    **"@parcel/monorepo": "git://github.com/iam-markus/parcel#f4410-parcel-1-fix-global-insertions"**,
```
This works and I can get it checked out into node_modules, however I can't get it to link to the parcel executable/entrypoint.
I tried setting it via the "**bin**" property in **package.json** `to ./packages/core/parcel/src/bin.js`, but I guess that's the wrong one? (getting MODULE_NOT_FOUND errors)

I am sorry to take this a bit off topic here, but it's kind of a big deal to not be able to deploy to production 🙂

**Comment by mischnic** [comment]
> but I guess that's the wrong one?

packages/core/parcel-bundler/bin/cli.js

**Comment by iam-markus** [comment]
After getting this to run, it seem that the problem in my case doesn't seem to be lodash, but the **formik** library. I kept adding libraries I use until the error `"Uncaught ReferenceError: $Y29H$var$arrayBufferTag is not defined"` appeared (this is even with the proposed fix by maerteijn).

I filed an issue for formik here: https://github.com/jaredpalmer/formik/issues/2445

In the meantime, is there any way how I can disable a specific package (like formik) from being scope-hoisted, while all other packages are still packed?

**Comment by mischnic** [comment]
> I filed an issue for formik here:

I think that's from lodash as well: https://github.com/lodash/lodash/blob/588bf3e20db0ae039a822a14a8fa238c5b298e65/.internal/baseClone.js#L59
I vaguely recall fixing this in Parcel 2.

> In the meantime, is there any way how I can disable a specific package (like formik) from being scope-hoisted, while all other packages are still packed?

No

**Comment by mdenburger** [comment]
My project hits the same issue because it uses Formik.

I understand maintaining Parcel 1 is extra work, but basically declaring it dead leaves a lot of existing Parcel users in the cold right now since - as far as I understand - Parcel 2 is not production ready yet and there's no estimate when it will be. 

Why not keep the old Parcel 1 source tree around and accept fixes from the community in there? This issue seems a good candidate for a patch release.
