### ISSUE TITLE
Dynamic imports not working on parcel v1 and v2

### ISSUE THREAD

**Issue by polRk** [parcel-bundler/parcel#4413]
```js
  const html = await import(`../includes/${name}.${lang}.pug`)
```

```
Uncaught (in promise) Error: Cannot find module '../includes/confirm.ru.pug
```

**Comment by mischnic** [comment]
Duplicate of https://github.com/parcel-bundler/parcel/issues/125

**Comment by polRk** [comment]
@mischnic How can i solve the problem ?

**Comment by mischnic** [comment]
As described in that issue, dynamic imports with an argument that is not a static string are currently not supported.
