### ISSUE TITLE
Bundler middleware throws a TypeError when trying to serve bundle

### ISSUE THREAD

**Issue by nozzlegear** [parcel-bundler/parcel#442]
🐛 bug report 🐛

### 🎛 Configuration (.babelrc, package.json, cli command)

Not using custom babel configuration.

### 🤔 Expected Behavior

Using bundler middleware with Express server should serve the bundled file on request.

### 😯 Current Behavior

Bundler middleware throws the following TypeError when it tries to serve the file:

```
TypeError: Cannot read property 'type' of undefined
    at sendIndex (/home/fluidbyte/workspace/sandbox/react-parcel/node_modules/parcel-bundler/src/Server.js:33:29)
    at respond (/home/fluidbyte/workspace/sandbox/react-parcel/node_modules/parcel-bundler/src/Server.js:23:16)
    at /home/fluidbyte/workspace/sandbox/react-parcel/node_modules/parcel-bundler/src/Server.js:15:7
    at Layer.handle [as handle_request] (/home/fluidbyte/workspace/sandbox/react-parcel/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/fluidbyte/workspace/sandbox/react-parcel/node_modules/express/lib/router/index.js:317:13)
    at /home/fluidbyte/workspace/sandbox/react-parcel/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/fluidbyte/workspace/sandbox/react-parcel/node_modules/express/lib/router/index.js:335:12)
    at next (/home/fluidbyte/workspace/sandbox/react-parcel/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/home/fluidbyte/workspace/sandbox/react-parcel/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/home/fluidbyte/workspace/sandbox/react-parcel/node_modules/express/lib/router/layer.js:95:5)
```

The middleware [attempts to check the `type` prop on `bundler.mainAsset`](https://github.com/parcel-bundler/parcel/blob/c8a1156d4c2dd5902ba500aa9c25547bfab53eac/src/Server.js#L34), but `bundler.mainAsset` will be undefined [until the bundler bundles at least once](https://github.com/parcel-bundler/parcel/blob/c8a1156d4c2dd5902ba500aa9c25547bfab53eac/src/Bundler.js#L136).

### 💁 Possible Solution

I was able to work around this by calling `await bundler.bundle()`, [which defines the `mainAssset` property here](https://github.com/parcel-bundler/parcel/blob/c8a1156d4c2dd5902ba500aa9c25547bfab53eac/src/Bundler.js#L136), before using the middleware. A fix would involve at least defining the `bundler.mainAsset` property when using middleware like the current implementation does when calling `await bundler.bundle()`.

### 🔦 Context

I was trying to create a setup where I can run both my server and client at the same time and have requests from the client get to the server without having to create any proxies or hardcode URLs (I use relative `/path/to/api` paths instead). The solution was to run my regular express server and have it connect the Parcel middleware when in development mode.

### 💻 Code Sample

This does not work:

```ts
if (Constants.ISLIVE) {
    // Redirect http requests to https when live
    app.use(httpsRedirect());
} else {
    // Run Parcel bundler for client development
    const bundler = new Bundler(path.resolve(__dirname, "../client/index.html"))
    app.use(bundler.middleware());
}
```

But by calling `await bundler.bundle()` before using the middleware, this *does* work:

```ts
if (Constants.ISLIVE) {
    // Redirect http requests to https when live
    app.use(httpsRedirect());
} else {
    // Run Parcel bundler for client development
    const bundler = new Bundler(path.resolve(__dirname, "../client/index.html"))
    // Bugfix: parcel bundler must call bundle at least once before using middleware
    await bundler.bundle();
    app.use(bundler.middleware());
}
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.3.1 |
| Node             | 8.9.3 |
| npm/Yarn         | 5.5.1/1.3.2 |
| Operating System | Windows 10 FCU |

**Comment by devongovett** [comment]
Currently the middleware doesn't trigger the initial bundle. When starting up the built-in server, we do it separately here: https://github.com/parcel-bundler/parcel/blob/master/src/Bundler.js#L480-L481

Maybe we could move that into the middleware itself so it works for other users. Want to make a PR?
