### ISSUE TITLE
Parcel 2 ready for production?

### ISSUE THREAD

**Issue by talkingtab** [parcel-bundler/parcel#4422]
Parcel is just great. However, I can't use parcel-bundler because I use react-bootstrap. Parcel 2 works just fine with react-bootstrap. My sense is to use Parcel 2 despite it being alpha for my production release. Either it will work or some testing will show it has problems. It would be nice to get some guidance of issues, things to look for, concerns etc.

Please don't force me back to other build systems. My build size is just great, its easy to use etc.

**Comment by DeMoorJasper** [comment]
You are free to use it in production at your own risk, the main remaining issues are stability, caching and potential breaking changes.

So as long as you're not writing any custom plugins and keep in mind that you might have to remove cache on a weird bug you should be fine. These issues should get resolved before a stable release.

**Comment by dandv** [comment]
You might want to pin your version to a stable one rather than `@next`. I've just installed parcel@2.0.0-alpha.3.2 and I get "404 Page no found" when serving a simple HTML file with no links to other sources.

**Comment by talkingtab** [comment]
@dandv Good thought, thanks much for the idea.

@DeMoorJasper  - I'm having  a hard time finding the doc for how to import an svg file, in parcel-bundler this worked
```
import menusvg from "./images/menu.svg" 
``` 
Would appreciate ideas. Other than that  (and pinning a version) 2.0 seems good. Thanks!

**Comment by DeMoorJasper** [comment]
We have named pipelines in Parcel 2 this removed the implicit url importing you now have to use `url: ./images/menu.svg`

**Comment by cdbattags** [comment]
Looks like a few of the "loaders" (unsure if that's the right terminology) are not working on v2+? I just tried with a Rust file and got an error?

**Comment by D1plo1d** [comment]
I ran into the same issue as @cdbattags . I see #3365 is tracking Rust/Parcel 2 but there hasn't been an update in a bit. Is the Rust integration still planned for Parcel 2?

**Comment by DeMoorJasper** [comment]
@D1plo1d we're still planning to support rust but we don't have any Rust users/experts in the Parcel core team currently so it's probably best if someone external with better knowledge of rust would contribute the rust support like what happened in Parcel 1.

At some point we will probably port the old Parcel 1 rust transformer to Parcel 2 if no-one does. We're also mainly focused on getting the current version stable and ready for a beta and stable version.
