### ISSUE TITLE
`--source-maps` not an option

### ISSUE THREAD

**Issue by dandv** [parcel-bundler/parcel#4430]
If I'm interpreting [the README](https://github.com/parcel-bundler/parcel/blob/v2/packages/core/parcel/README.md#--no-source-maps) correctly, the "no-" part of `--[no-]source-maps` is optional, so `--source-maps` should be a valid option.

With 2.0.0-alpha.3.2 I get this error:

> $ node_modules/.bin/parcel serve index.html --no-cache --source-maps
error: unknown option `--source-maps'

Asking because I was trying to force rebuilding the source maps. I have a TypeScript project and all `.ts` files except `index.ts`, resolve to the source HTML.

**Comment by DeMoorJasper** [comment]
That's probably a mistake in the README, it should always output sourcemaps unless `no-source-maps` is provided

**Comment by Jogai** [comment]
nightly 230 is producing sourcemaps anyways.

Relevant part of package.json (windows only because of rmdir):

  "scripts": {
    "build": "rmdir dist /s /q && parcel build Css/style.scss Scripts/app.ts --no-source-maps",
    "watch": "parcel watch Css/style.scss Scripts/app.ts"    
  },

**Comment by mischnic** [comment]
@Jogai does this comment describe the behaviour you are seeing: https://github.com/parcel-bundler/parcel/issues/4390#issuecomment-618869433?

**Comment by Jogai** [comment]
No it was different, but todays build (nightly 247) fixes it. Thanks!
