### ISSUE TITLE
@parcel/transformer-babel: remove core-js dep?

### ISSUE THREAD

**Issue by corwin-of-amber** [parcel-bundler/parcel#4433]
# 🐛 bug report

It seems that this dependency is redundant:
https://github.com/parcel-bundler/parcel/blob/c690f91bcb28081ba370eacdb91b9b1b9a1baa6a/packages/transformers/babel/package.json#L32

Searching the code base, I only found `core-js` in the tests.

## 🔦 Context

`core-js` is particularly harmful due to https://github.com/zloirock/core-js/issues/548, https://github.com/zloirock/core-js/issues/611, https://github.com/zloirock/core-js/issues/708.

Any chance it can be removed?

**Comment by DeMoorJasper** [comment]
@corwin-of-amber there is nothing harmful about asking for some kind of sponsorship for an open source project.

That being said there's the issue of core-js no longer being maintained which will lead to it being replaced at some point...

**Comment by corwin-of-amber** [comment]
That is a bit subjective, but in that case the decision is yours.

At any rate, I did not find that @parcel/transformer-babel is even utilizing core-js at all. Am I wrong?

**Comment by mischnic** [comment]
It's used by `@babel/preset-env`: https://babeljs.io/docs/en/next/babel-preset-env.html#corejs

**Comment by corwin-of-amber** [comment]
Oh, I missed that! Sorry and thanks for the ref @mischnic!

**Comment by DeMoorJasper** [comment]
Can we close this, as it's not really an issue and a real dependency. The only way around this I see is to enforce all parcel users to install core-js and babel locally besides parcel which would not change anything.

core-js will eventually be replaced as it's no longer maintained but for now I don't see any issue in leaving it as is.

**Comment by mischnic** [comment]
> core-js will eventually be replaced as it's no longer maintained but for now I don't see any issue in leaving it as is.

If it becomes a problem, this is on Babel to fix.
