### ISSUE TITLE
Broken glob expansion

### ISSUE THREAD

**Issue by wyozi** [parcel-bundler/parcel#4436]
# 🐛 bug report

I'm not sure if this is a problem in parcel, underlying library or yarn (?), but I noticed that globbing seems to be broken for entrypoints.

My project structure is this
```
- src/a/index.html
- src/b/index.html
- src/index.html
- package.json
```

If I run `yarn run parcel build --dist-dir dist src/**/index.html` (ie. glob gets expanded in shell), it builds all three index.html -files properly.
If I run the exact same command through `yarn build` (the command being added to package.json scripts), parcel only builds `src/a/index.html` and `src/b/index.html`

## 🤔 Expected Behavior

Both should expand glob with `src/index.html` there.

## 😯 Current Behavior

Only shell globbing does that.

## 💁 Possible Solution

Fix the problem in the globbing library, if it's there (?)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | Nightly |
| Node             |  v12.14.1 |
| npm/Yarn         | 1.21.1 |
| Operating System | OS X 10.15.2 |

**Comment by mischnic** [comment]
> (ie. glob gets expanded in shell), it builds all three index.html -files properly.

Doesn't happen for me (by default)

```bash
$ echo src/**/index.html
src/a/index.html src/b/index.html
$ shopt -s globstar
$ echo src/**/index.html
src/a/index.html src/b/index.html src/index.html
```

> If I run the exact same command through yarn build (the command being added to package.json scripts), parcel only builds src/a/index.html and src/b/index.html

Yarn also uses a shell to execute the specified command (which is running with a different configuration that your own shell), but in this case it seems to interpret `**` as "one or more directories", you can verify this with:
```json
{
	"scripts": {
		"build": "echo parcel build --dist-dir dist src/**/index.html"
	}
}
```
which just prints out the command though would be run.

If you want Parcel to handle the glob, you need to do add single quotes around the glob.
```json
{
	"scripts": {
		"build": "parcel build --dist-dir dist 'src/**/index.html'"
	}
}
```

**Comment by wyozi** [comment]
Interesting! I thought double star was some kind of fixed glob expansion rule rather than something each shell configures themselves (in apparently different ways).

Single quotes do the trick for me, thanks :)
