### ISSUE TITLE
import styles in lit-element

### ISSUE THREAD

**Issue by timreichen** [parcel-bundler/parcel#4445]
# 💬 RFC

I want to import a .styl file into a .ts file to use it as styles for LitElement.
postcss should also be applied to it.
I read through some threads, nothing really helped.

## 💻 Examples

styles.styl
```styl
:host {
user-select: none;
}
```

component.ts
```ts

import { LitElement, customElement, css } from "lit-element"
import styles from "./styles.styl"

@customElement('my-component')
export class MyComponent extends LitElement {
static get styles = css(styles)
}
```

console.log(styles) should be
```css
:host {
user-select: none:
-webkit-user-select: none;
-ms-user-select: none;
}
```
I also tried with bundle-text: prefix.
```ts
import styles from "bundle-text:./styles.styl"
```
That throws an error during build: Failed to install bundle-text:..

How can this be done? I really like parcel but I cant figure this out. Thanks for your help.

**Comment by mischnic** [comment]
> That throws an error during build: Failed to install bundle-text:..

Sounds like you are running Parcel 1.x instead of Parcel 2?


> postcss should also be applied to it.

`bundle-text` would do that

**Comment by timreichen** [comment]
Thank you! I missed that 
```
npm install --save-dev parcel@v2
```
did throw an error so I used 

```
npm install --save-dev parcel@next
```
and that installed it properly.

<br>

```ts
import styles from "bundle-text:./styles.styl"
```
throws an error: Cannot find module 'bundle-text:./styles.styl'
which I bypass for now with a global.d.ts file:
```ts
declare module "*.styl"
```

That seems a bit hacky to me. Is there a proper way to do this?

**Comment by mischnic** [comment]
I have no experience with typescript. I don't know of a better way.
