### ISSUE TITLE
Consider shorter module name aliases

### ISSUE THREAD

**Issue by Ajaxy** [parcel-bundler/parcel#4446]
# 💬 RFC

Parcel v2 uses 32 symbol hex string (i.e. `98a8b4be7438864cba762c83cd5f7e6d`) to identify a module while v1 used various length `[A-Za-z0-9]` string (i.e. `Sh3W`). This results in larger builds in v2, and gzip won't help here. For example, the same file went from 95 KB to 103 KB (+ 8%) for me simply when switching to v2. Not a big deal, but still may be worth considering going back to older scheme.

**Comment by mischnic** [comment]
We have considered this and will possibly change this.

> but still may be worth considering going back to older scheme.

We will definitely have longer hashes than Parcel 1, because hash collisions were quite frequent.

(cc @wbinnssmith)

**Comment by Ajaxy** [comment]
@mischnic Can’t it be just incremental?
