### ISSUE TITLE
Custom class Node gets mixed with standard React Node element when making a production build.

### ISSUE THREAD

**Issue by simonssspirit** [parcel-bundler/parcel#4450]
# 🐛 bug report

Custom class Node gets mixed with standard React Node element when making a production build.

We have a custom class called Node when making a production build we assume that it gets mixed with the React Node, which causes an error as we are invoking a method of the custom Node class, but it results in undefined as the standard Node does not have it.

This is working fine with the development build.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "plugins": [
    "@babel/plugin-transform-runtime",
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }],
    "@babel/plugin-transform-react-jsx"
  ]
}
```

## 🤔 Expected Behavior

The page kendo-chart load correctly with the production build.

## 😯 Current Behavior

The page kendo-chart has a JS error.

## 💻 Code Sample

https://github.com/simonssspirit/kendo-react-chart-parcel - steps in the readme

**Comment by adilcem** [comment]
@simonssspirit Thanks for bringing this issue up. I'm having the same problem. Using kendo-chart in my project and building with Parcel for the production environment. The page gives a JS error when opening up. However, it's working without any problem for the development environment. Would appreciate your help on this @mischnic . Thanks!

**Comment by api182** [comment]
Would this be related to an error I'm experiencing giving this in the console: -

**TypeError: s.createDefinitions is not a function**

Trying to use a Kendo Gauge chart... Works fine in development env, as soon as I build to production I get the above on any page with a kendo chart...
