### ISSUE TITLE
HMR not working when using vscode Live share

### ISSUE THREAD

**Issue by yoyoys** [parcel-bundler/parcel#4451]
# 🐛 bug report

HMR not working when using vscode Live share

## 🎛 Configuration (.babelrc, package.json, cli command)
parcel index.html

## 🤔 Expected Behavior
HMR will auto update page at my browser and participant's browser.

## 😯 Current Behavior

HMR only auto update page at my browser.

And participant's browser need press f5 himself.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.4
| Node             |  13.7.0
| npm/Yarn         | 6.13.6
| Operating System | Mac 10.15.4

**Comment by mischnic** [comment]
So Parcel is running on your machine and the other party accesses the dev sever via port forwarding provided by VS Code?

**Comment by yoyoys** [comment]
> So Parcel is running on your machine and the other party accesses the dev sever via port forwarding provided by VS Code?

Yes, the port forwarding is provide by vscode.

**Comment by mischnic** [comment]
> Yes, the port forwarding is provide by vscode.

Then running `parcel index.html --hmr-port 42148` (some fixed port) and forwarding that port as well would probably make it work.

**Comment by yoyoys** [comment]
> > Yes, the port forwarding is provide by vscode.
> 
> Then running `parcel index.html --hmr-port 42148` (some fixed port) and forwarding that port as well would probably make it work.

Thanks for the reply!
So I need forwarding 2 ports(HTTP, HMR) to support HMR?

It sounds ok but not perfect...
Because webpack is easier to share dev server to my teammate.
Parcel should be the best prototype bundle tool,  right? ;)

**Comment by mischnic** [comment]
> So I need forwarding 2 ports(HTTP, HMR) to support HMR?

For Parcel 1, yes.
Parcel 2 uses one port for both.
