### ISSUE TITLE
HMR with multiple entry points, resulting JS is broken

### ISSUE THREAD

**Issue by kirkone** [parcel-bundler/parcel#4453]
# 🐛 bug report

If multiple entry points or globing ist used with `watch` or `serve` when HMR is enabled the compiled js is broken.

## 🎛 What I used:

```js
parcel watch src/app.ts src/app.scss
parcel watch src/*
```

## 🤔 Expected Behavior

The resulting js should not be broken.

## 😯 Current Behavior

The js file generated has multiple errors an is not working. Also the code from my `app.ts` is missing.
If I use an index.html as entry point all works fine but I have an additional html file that is not needed.

![image](https://user-images.githubusercontent.com/15778270/78798779-ac02d980-79b9-11ea-894d-e5d195df74fc.png)

I also tried to use a glob like this `src/*` but with the same result.

## 💁 Possible Solution

I have no idea.

## 🔦 Context

I only want to use parcel only for js and css without any html. I use it to generate files for an asp.net core site

## 💻 Code Sample

tbd

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4 |
| Node             | 12.16.1 |
| npm/Yarn         | 6.13.4 |
| Operating System | Windows 10 |

**Comment by mischnic** [comment]
It sounds like processes are writing to the same file concurrently and corrupting it..

**Comment by kirkone** [comment]
I have no idea where to look for a solution but if I can help in any way please give me a hint.

**Comment by rndD** [comment]
I have the same issue, parcel v1.12.4.

Only if I have multiple entrys

**Comment by rndD** [comment]
Ok, as a workaround you can turn off HMR: `watch somefiles/* --no-hmr`

**Comment by marcandre** [comment]
I can confirm the same bug, happening systematically for me, and `--no-hmr` indeed fixes the issue.

Probably easy to reproduce, but just in case:
1) checkout repo https://github.com/marcandre/np
2) `git reset --hard parcelbug`
4) `cd lib/np/app && yarn && parcel watch assets/index.* --global App --no-cache`
Open the newly created `dist/index.js` file. Locate line with `Kludge`; that line ends abruptly and is merged with extra code.

Adding `--no-hmr` option, or changing `index.*` to `index.js` does not create the issue.

As a complete newb' to `parcel`, this was quite frustrating and difficult to understand.

```
$ parcel info

Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (12) x64 Intel(R) Xeon(R) CPU           W3670  @ 3.20GHz
  Binaries:
    Node: 14.10.1 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 80.0.1
    Safari: 13.1.2
```

**Comment by mephinet** [comment]
I think you are running into the same issue as I did, and reported as #5890:
* `parcel watch app.ts` produces an app.js
* `parcel watch app.scss` produces an app.css and _also_ an app.js (that contains the HMR code)

To validate my assumption, can you please rename your entry.scss to whatever.scss and report whether that solves your issue?

**Comment by JAicewizard** [comment]
In my case the HMR js is only added in the first entry file, and it also points to the wrong URL. It also seems to not work if the second file is small? I am not sure how being small would change it but if I just remove text from the second entry it just stops putting it in. Really annoying TBH, extremely unreliable.

**Comment by JAicewizard** [comment]
can someone confirm broken/fixed? no longer have a good setup for trying this out.

**Comment by mephinet** [comment]
I can confirm that my reproducer in #5890 still reproduces the issue with 1.12.5.
