### ISSUE TITLE
Inline Javascript (<script> tag) always get minified in html

### ISSUE THREAD

**Issue by edify17** [parcel-bundler/parcel#4455]
# 🐛bug report
Inline Javascript (<script> tag) always get minified in entry/index html
Tried according to htmlnano documentation by giving htmlnano key in package.json as

```
{
      minifyJs: false
}
```
But Javascript inside script tag in index.html still minifies.

Issue faced is that I want to escape replacement of single quote to double quotes when Parcel Bundles application.

## 🤔 Expected Behavior

There should be a way to escape JS minification in html files or to not touch quotes during minification.

## 😯 Current Behavior

Not able to escape inline JS minification inside html.

## 🔦 Context

Came across this PR https://github.com/parcel-bundler/parcel/pull/1456, which introduced changes for processing inline styles and scripts, is there way to skip inline JS minification or changing quotes during minification.

## 💻 Code Sample

```
<script>
     var a = JSON.parse('{"a": 1}');
</script>
```
Converts to

```
<script>
     var a = JSON.parse("{"a": 1}");
</script>
```
post bundling.

Which breaks in browser with error `Uncaught SyntaxError: missing ) after argument list` as string parsing fails.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             |12.5.0
| npm/Yarn         |npm
| Operating System |macOS

**Comment by mischnic** [comment]
The `minifyJs` flag doesn't do anything because Parcel processes the inline JS  and re-inserts it after htmlnano ran.

> Which breaks in browser with error Uncaught SyntaxError: missing ) after argument list

That should definitely not happen.

**Comment by mischnic** [comment]
Your code sample works correctly for me.

**Comment by edify17** [comment]
Hi @mischnic, Are you not getting the error in console or Parcel doesn't change the quotes post bundling?

**Comment by mischnic** [comment]
With this input
```html
<script>
     var a = JSON.parse('{"a": 1}');
     console.log(a);
</script>
```
the output is
```html
<script>var a=JSON.parse('{"a": 1}');console.log(a);</script>
```

**Comment by edify17** [comment]
My exact code is
```var config = JSON.parse('{{{configObject}}}');```

which converts to
```var a=JSON.parse("{{{configObject}}}")```

Code inside ```{{{}}}``` is handlebars, which is later on parsed by my server. I do not want Parcel to change the quotes and treat ```{{{configObject}}}``` as string.

Expected Output:
```var a=JSON.parse('{{{configObject}}}')```

**Comment by mischnic** [comment]
I see, this is cause by terser, add this `.terserrc`:
```json
{
	"output": {"quote_style": 3}
}
```
(https://github.com/terser/terser#output-options)

**Comment by edify17** [comment]
Tried it, doesn't work for me. Does it work for you?

**Comment by mischnic** [comment]
Yes: https://github.com/mischnic/parcel-issue-4455.

I do indeed get:
> Expected Output: `var a=JSON.parse('{{{configObject}}}')`

**Comment by edify17** [comment]
Worked after deleting .cache folder and bundling again. 
I have witnessed multiple times that changes do not reflect until I build again after deleting .cache folder.

Anyway, Thanks for the help.
