### ISSUE TITLE
Undefined TypeScript class properties after redefining types

### ISSUE THREAD

**Issue by ross-pfahler** [parcel-bundler/parcel#4460]
# 🐛 bug report

I have a base class and a subclass.
I define a property in the base class and assign in the constructor.
I then redefine the property type in the subclass to give hints to the compiler. The constructor assignment doesn't seem to work in the subclass after this.

For example:
```
class Base {
  public get: () => any;
  public value: any;

  constructor(value) {
    this.value = value;
    this.get = () => value;
  }
}

class Extension extends Base {
  public get!: () => number;
}

const b = new Base(123);
console.log('base get', b.get());

const e = new Extension(123);
console.log('extension get', e.get());
```

Please note: I believe this *should* work -- but it is a bit contrived and odd (though came up in production code that works fine when compiled with Parcel 1). See examples below.

## 🎛 Configuration (.babelrc, package.json, cli command)

babel.config.json:
```js
{
  "plugins": [
    "@babel/plugin-proposal-class-properties"
  ],
  "presets": [
    "@babel/preset-env",
    "@babel/preset-typescript"
  ]
}
```

## 🤔 Expected Behavior

I believe this should work (please correct me if I'm wrong). I think this also works in Parcel 1.

If this is a bug somewhere else -- please let me know, happy to put in a different place.

## 😯 Current Behavior

In the example above `e.get` in undefined.

## 💁 Possible Solution

?

## 🔦 Context

I'm trying to get my Parcel 1 builds to work in Parcel 2.

## 💻 Code Sample

Complete example: https://github.com/ross-pfahler/parcel-2-demos/tree/master

Running with tsc: https://www.typescriptlang.org/play/index.html?target=1&ssl=18&ssc=39&pln=1&pc=1#code/MYGwhgzhAEBCkFNoG8BQ1oAcCuAjEAlsNAOYIAuAXNABQCU0AvAHzRgB2AngNzpZ6FiANzAhsCahx6o+wAPbsI5AE7Zg5OcpoixEtlwZoMGcgAsCEAHRlyTWgxbQd43hgC+qD6lCQYAUQAPcgRFAgVoBCCQgBMYeAgkI358IlIKAEJqeiZWdmwAW1wEZV4veUVbXDt2BAB3OEQaAEYAJgBmOl5yiDkQBEsQORIaAHJcRDTyEYAaaFxrCnpOmW7bJEZoGvrA4NCFZvbl7t7+weGRyN2IMPZJmYiF8iXeIA

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.207
| Node             | 12.16.1
| npm/Yarn         | yarn 1.19.1
| Operating System | osx catalina

**Comment by mischnic** [comment]
Strangely enough, it does work with the Babel REPL but not locally: https://github.com/mischnic/parcel-issue-4460
```
$ yarn transpile
yarn run v1.22.4
warning package.json: No license field
$ babel input.ts -o output.js
✨  Done in 1.56s.
$ node output.js
base get 123
.../4460-ts-subclass/output.js:64
console.log("extension get", e.get());
                               ^

TypeError: e.get is not a function
    at Object.<anonymous> (.../4460-ts-subclass/output.js:64:32)
```

If you look at the result, it is quite clear why:
```js
function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

class Base {
  constructor(value) {
    _defineProperty(this, "get", void 0);
    _defineProperty(this, "value", void 0);

    this.value = value;
    this.get = () => value;
  }
}

class Extension extends Base {
  constructor(...args) {
    super(...args); // <----- `this.get` is set to your function
    _defineProperty(this, "get", void 0); // <----- `this.get` is set to undefined
  }
}

const b = new Base(123);
console.log("base get", b.get());
const e = new Extension(123);
console.log("extension get", e.get());
```
So this seems to be a bug in Babel.
