### ISSUE TITLE
Parcel not loading .SCSS files

### ISSUE THREAD

**Issue by FrediArro** [parcel-bundler/parcel#4462]
# 🐛 bug report

Currently my React project using parcel is not seeing/loading .scss files. Have tried different suggested solutions, like installing `sass`, `node-sass` or even `dart-sass`. None of them have worked for me.

## 🎛 Configuration (.babelrc, package.json, cli command)
`.babelrc`
```
{
  "plugins": ["@babel/plugin-proposal-class-properties"],
  "presets": ["@babel/preset-env", "@babel/preset-react"]
}
```

`package.json`
```
{
  "name": "podder",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "classnames": "^2.2.6",
    "minimist": "^1.2.5",
    "parcel": "^1.12.4",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.0",
    "react-swipeable-views": "^0.13.9",
    "svjsl": "^1.8.4"
  },
  "scripts": {
    "start": "parcel public/index.html",
    "build": "parcel build public/index.html"
  },
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "babel-core": "7.0.0-bridge.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "parcel-bundler": "^1.12.4",
    "sass": "^1.26.3"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

## 🤔 Expected Behavior
All .scss file loaded.

## 😯 Current Behavior
No .scss file is coming through. So there is no styling on my elements.

## 💁 Possible Solution
Probably some sass, but I can't figure out which one.

## 💻 Code Sample
My code repo so far:
https://github.com/FrediArro/podder1/tree/master

What it the elements should look like:
https://github.com/AdrianMachado/KaiUI

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 12.16.1
| Yarn         | 1.21.1
| Operating System | Ubuntu 18.04

**Comment by mischnic** [comment]
Please provide a smaller code sample

**Comment by mischnic** [comment]
Closing due to lack of response
