### ISSUE TITLE
Parcel doesn't bundle correctly in build

### ISSUE THREAD

**Issue by micahlt** [parcel-bundler/parcel#4465]
# 🐛 bug report

So I'm building a web app with Vue and Sass, and Parcel has worked awesomely for watching my files and hosting on localhost.  However, when I run `parcel build`, and open the generated `index.html` file in Chrome, the styles are not applied and Vue does not render anything.  The correct files are in the `dist` folder, but when I look in Chrome DevTools the console says that the files could not be found.  The filenames do match, though, I've checked.  It's bizzare- any help is a appreciated!

## 🎛 Configuration (.babelrc, package.json, cli command)
Shouldn't be relevant, but I'm just running:
```bash
parcel build index.html
```

## 🤔 Expected Behavior

Styles should be applied and Vue should render correctly.

## 😯 Current Behavior

I see a default HTML page with no styling and my Vue template strings.

## 💁 Possible Solution

Er, maybe this is an issue with configuring Parcel that I missed while reading the docs?

## 🔦 Context

I'm trying to render an app with Vue and Sass to be compiled with Adobe PhoneGap and turned into a mobile app.

## 💻 Code Sample

You can see the repository at https://github.com/Scratch-Client-4/mobile

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | latest
| Node             | latest
| npm/Yarn         | latest
| Operating System | Ubuntu 20.04 LTS (development version)

**Comment by maerteijn** [comment]
Hi @micahlt 

Parcel is building fine; It is however assuming you are accessing the builded html on a webserver so the default root path that is used for all assets is `/`.

You can make those relative by adjusting your build command as following:

`"build": "parcel build index.html --global index --public-url ./"`

Then you can open the builded `index.html` from the filesystem in a browser and all assets are loaded correctly.

**Comment by micahlt** [comment]
Ah, okay!  Thanks so much for the help.
