### ISSUE TITLE
Uncaught Error: process.binding is not supported

### ISSUE THREAD

**Issue by malte-v** [parcel-bundler/parcel#4468]
# 🐛 bug report

I'm trying to bundle my GHCJS (Haskell-to-JS compiler) output using parcel. GHCJS produces an entirely self-contained folder (https://github.com/malte-v/parcel-4468-addendum) containing the output JS along with an index.html and some other junk that I do not really care about. When I open the index.html in the browser, I get no errors and my "hello world" message gets printed to the console. When I bundle the same index.html through parcel (i.e. `parcel index.html`), it successfully bundles the JS, but when I open it in the browser, I get an error saying `process.binding is not supported`.

I'm not really sure if this is parcel's fault, but I feel like my code should still work after it went through the bundler.

## 💻 Code Sample

https://github.com/malte-v/parcel-4468-addendum. Just clone it and...

- open index.html normally. Everything should work.
- run `parcel index.html` and navigate to wherever the parcel server is running. It won't work anymore, as explained above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | v10.19.0
| npm/Yarn         | yarn 1.22.4, npm 6.14.3
| Operating System | Linux linux 5.5.10-arch1-1 #1 SMP PREEMPT Wed, 18 Mar 2020 08:40:35 +0000 x86_64 GNU/Linux

**Comment by malte-v** [comment]
I've found the offending line in my code:
```js
if(typeof process !== 'undefined' && (typeof h$TH !== 'undefined' || (typeof require !== 'undefined' && typeof module !== 'undefined' && module.exports))) 
```
https://github.com/malte-v/parcel-4468-addendum/blob/master/rts.js#L1344

Apparently GHCJS uses `typeof require` to check whether it's running in a node environment. Since parcel defines `require`, the GHCJS output accesses `process.binding` and the described error occurs. Is there anything I can do to stop parcel from defining `require`?

**Comment by mischnic** [comment]
No, Parcel takes your assets and wraps them:
```js
(function(){
	// internal runtime
})({
	"index.js": function(require, module, exports) {
		// code for index.js
	},
	"thing.js": function(require, module, exports) {
		// code for thing.js
	}
});
```
Your usecase (multiple script tags) is a rather unusual one.

**Comment by mischnic** [comment]
Closing this since there is really nothing we can do here. Feel free to ask any questions you might still have though
