### ISSUE TITLE
Parcel 2 Feature Request: manual asset dependency

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#4474]
*might be related to https://github.com/parcel-bundler/parcel/issues/3757 ?*

# 🙋 feature request

I was wondering if you guys would be interested in supporting a way to get the url of processed assets without side effects.

We currently have multiple ways to have dependent assets that work automagically, e.g:

```js
navigator.serviceWorker.register('./script.js')
// or
import('./script.js')
// ect...
```

But i currently find myself in a need to just get the url of that asset and not do anything with it yet.
My use case would be to run this processed script in an iframe.

So i was wondering if it would be possible to have a way to get this behavior without side effects and just get the url of that processed asset.
It could be html, js, ect...

I was maybe thinking of using the `url:` syntax for this ?
```js
import myIframeHtml from 'url:./iframe.html'
import myScriptUrl from 'url:./script.ts'
```

Currently the only way to use processed assets is to define an entry point for that asset and set the desired output name, then use/import that output name from the original script.
And i thought this could be way cleaner if it was supported by a bundler.

Would you guys be interested in supporting this natively ?
If not, i could probably try to make a Parcel plugin for this anyways, but i'd rather know your opinion on this first.

**Comment by mischnic** [comment]
> So i was wondering if it would be possible to have a way to get this behavior without side effects and just get the url of that processed asset.

How does this differ from the current `url:` implementation/behaviour? (Expected Behavior/Current Behavior in the issue template 😉 )

Do you essentially want a `url-service-worker:` and `url-entry:` named pipeline?

**Comment by Banou26** [comment]
Yeah, my request would be somewhat of a  `url-service-worker:` and `url-entry:` looking thing.

## Current `url:` behavior:
`foo.ts`
```js
console.log('foo')
```

`index.ts`
```js
import fooUrl from 'url:./foo.ts'

console.log('index', fooUrl)
```

results in:
```
foo.ts:1 foo
index.ts:3 index {}
```

## Expected new `url:`/`url:x` named pipelines behavior:

`foo.ts`
```js
console.log('foo')
```

`index.ts`
```js
import fooUrl from 'url-entry:./foo.ts'

console.log('index', fooUrl)
```

results in:
```
index.ts:3 index './foo.hash.js`
```

**Comment by mischnic** [comment]
I think you ran into the bug that html, js, wasm and css can't currently be imported with the `url:` pipeline:

https://github.com/parcel-bundler/parcel/blob/ec34118223224c570bc4f2d30b9483f464db13f4/packages/runtimes/js/src/JSRuntime.js#L29-L32

Instead, you get `{}` as a value and the bundle loads as though you didn't specify `url:`

**Comment by Banou26** [comment]
Oh, alrighty, gonna change the title to represent a bug instead then.
