### ISSUE TITLE
get wrong value of document.documentElement.clientWidth 

### ISSUE THREAD

**Issue by BrotaOne** [parcel-bundler/parcel#4489]
Hi everyone!

I use "npx parcel test.html" to start a server,but when I use chrome , the value of document.documentElement.clientWidth  is always 768,but when I use edge with chromium ,I get the right value.

And if I open test.html directly with chrome, I also get the right value.

To find if the html file is wrong, I try with a html file with !+Tab in VScode, the result is the same .

I failed uploading my screenshot because of slow network.

Yesterday I used "npx parcel test.html",it works,so did i do something wrong ?

have a nice day!

**Comment by mischnic** [comment]
This should work. Can you provide a code sample?

**Comment by BrotaOne** [comment]
> This should work. Can you provide a code sample?

After I found the problem, I tried it with a new html.  There is only a little code.
//test.html
`<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <script src="./index.js"></script>
</body>

</html>`

//index.js
(Nothing)

//package.json
`{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "parcel-bundler": "^1.12.4"
  }
}`

**Comment by mischnic** [comment]
This isn't very helpful if your script doesn't even contain `document.documentElement.clientWidth`; with the code, I want to trigger the same problem you were having.

**Comment by BrotaOne** [comment]
> This isn't very helpful if your script doesn't even contain `document.documentElement.clientWidth`; with the code, I want to trigger the same problem you were having.

So you can't trigger the same problem?
But I didnt change `document.documentElement.clientWidth` in my script.

**Comment by mischnic** [comment]
> So you can't trigger the same problem?

Where do you access `document.documentElement.clientWidth`? I ran your example, opened the devtools and printed the value using the console; and the value was correct.

**Comment by BrotaOne** [comment]
![123](https://user-images.githubusercontent.com/30154715/80079885-6e8a7880-8583-11ea-8197-3cf9529a6063.png)
I get thewrong  value in console of Chrome  81.0.4044.113, but in ms edge it is correct

**Comment by mischnic** [comment]
I tried using the same Chrome version.

What happens if you start a normal http server in your project directory (not parcel) and open the html file in the browser? If it's still wrong, then it's a bug in Chrome.

**Comment by BrotaOne** [comment]
> I have the same Chrome version.
> 
> What happens if you start a normal http server in your project directory (not parcel) and open the html file in the browser? If it's still wrong, then it's a bug in Chrome.

Thank you!
Maybe it is something wrong with my chrome,I use vue-cli-service to start a server,it is also wrong.But before it was right.

After all, thanks for your help.
