### ISSUE TITLE
HTML Meta Tag with msapplication-config breaks bundling

### ISSUE THREAD

**Issue by ZachariahRosenberg** [parcel-bundler/parcel#4490]
# 🐛 bug report

Took a while to find this one...
Using an older version of parcel, ~1.9, everything worked correctly. The problem I had was that the older parcel version's server was running at +400% CPU on idle (That issue was reported here: https://github.com/parcel-bundler/parcel/issues/2456). 

After upgrading to any version 1.10 or later, the command `parcel app/index.html` was throwing:

> /Users/zr/project/app/none: ENOENT: no such file or directory, open '/Users/zr/project/app/none'
> Error: ENOENT: no such file or directory, open '/Users/zr/project/app/none'

The folder structure, briefly, is:
 ```
project:
- package.json
- .env
- README.md
- app:
    - index.html
    - css
    - img
    - js:
        - index.js
        ... and on
```

After commenting out line by line I found the culprit is in index.html, specifically the following line:

`<meta name="msapplication-config" content="none"/`

Removing that line fixed the issue.

## 🎛 Configuration (.babelrc, package.json, cli command)

```babel
{
  "presets": ["react", "es2015"],
  "env": {
    "development": {
    "plugins": [["react-transform", {
       "transforms": [{
         "transform": "react-transform-hmr",
         "imports": ["react"],
         "locals": ["module"]
       }]
     }]]
    }
  }
}
```

```cli
npx parcel app/index.html -p 8080
```

## 🤔 Expected Behavior

Successful build and server start

## 😯 Current Behavior

> /Users/zr/project/app/none: ENOENT: no such file or directory, open '/Users/zr/project/app/none'
> Error: ENOENT: no such file or directory, open '/Users/zr/project/app/none'

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | v10.16.0
| npm/Yarn         | 6.14.4
| Operating System | Mac OSX Catalina

Thank you! Happy to donate once I've fulled swapped webpack out - I'm certainly excited to do so!

**Comment by mischnic** [comment]
To fix this in Parcel 2, the value `none` should ignored in this case:
https://github.com/parcel-bundler/parcel/blob/8551183608cbaa640fbe8ef7e74c9cd9c1d350e3/packages/transformers/html/src/dependencies.js#L53

**Comment by vikene** [comment]
@mischnic I am new to the community, I tried fixing this bug. Let me know if I have to refactor my change or add an integration test.

**Comment by vikene** [comment]
Added test cases as you recommended @mischnic
