### ISSUE TITLE
Parcel 2 fails to resolve relative font paths in LESS->CSS imports

### ISSUE THREAD

**Issue by ashmind** [parcel-bundler/parcel#4494]
# 🐛 bug report

When running Parcel 2 over this less file:
```less
@import (less) './node_modules/typeface-open-sans/index.css';
```
I get
```
× Build failed.
@parcel/core: Failed to resolve './files/open-sans-latin-300.woff2' from './main.less'
@parcel/resolver-default: Cannot load file './files/open-sans-latin-300.woff2' in './'
```

This worked in Parcel 1.

### package.json
```json
{
  "name": "bugs-parcel2-less-font",
  "version": "0.0.0",
  "description": "",
  "scripts": {
    "build": "parcel index.html"
  },
  "private": true,
  "devDependencies": {
    "less": "^3.11.1",
    "parcel": "^2.0.0-nightly.223"
  },
  "dependencies": {
    "typeface-open-sans": "0.0.75"
  }
}
```

### index.html
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Parcel2 Less Fonts bug</title>
    <link rel="stylesheet" href="main.less">
  </head>
  <body>
  </body>
</html>
```

### main.less
```less
@import (less) './node_modules/typeface-open-sans/index.css';
```

## 🤔 Expected Behavior

Same as Parcel 1:

1. File `./node_modules/typeface-open-sans/index.css` should be inlined into resulting `main._hash_.css`
2. File `./node_modules/typeface-open-sans/files/open-sans-latin-300.woff2` and other fonts mentioned in `typeface-open-sans/index.css` should be copied to dist folder, e.g. `.parcel-cache/dist/open-sans-latin-300.woff2`.

## 😯 Current Behavior

```
× Build failed.
@parcel/core: Failed to resolve './files/open-sans-latin-300.woff2' from './main.less'
@parcel/resolver-default: Cannot load file './files/open-sans-latin-300.woff2' in './'
```

## 💁 Possible Solution

Seems like the font path is assumed to be relative to the importing `main.less`, not imported `typeface-open-sans/index.css`.

## 🔦 Context

I am trying to migrate existing project to Parcel 2 due to #1655. The goal is to have the fonts in dist together with the other assets, same as it worked before.

## 💻 Code Sample

[bugs-parcel2-less-font.zip](https://github.com/parcel-bundler/parcel/files/4495637/bugs-parcel2-less-font.zip)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.223 |
| Node             | 12.16.1 |
| npm/Yarn         | npm 6.13.4 |
| Operating System | Windows 10 |

**Comment by mischnic** [comment]
I had thought LESS did this automatically:
```less
// index.less
@import (less) './lib/index.less';


// lib/index.less
body {
	background-image: url("./logo.png");
}
```

Here, 
https://github.com/parcel-bundler/parcel/blob/7c0aa3d2b9cd4a8d3cb6135e6b07d05f33406389/packages/transformers/less/src/LessTransformer.js#L15-L28
`config.rewriteUrls = 'all'` should be set as well (docs: http://lesscss.org/usage/#less-options-rewrite-urls).

I would opt for 'all' instead of 'local' (because this way, renaming a CSS file to LESS wouldn't change Parcel's output). 

The test above should be added to https://github.com/parcel-bundler/parcel/blob/v2/packages/core/integration-tests/test/less.js
