### ISSUE TITLE
Cannot resolve dependency Yarn Berry

### ISSUE THREAD

**Issue by nnennajohn** [parcel-bundler/parcel#4499]
# 🐛 bug report

Trying to build an index.ts file that imports express along with others in a yarn berry monorepo setup, I run into the following error. I can confirm that yarn is installed, and I have this working with both tsc and webpack. Just wanted to give parcel a shot to minimize the numerous config files I have. 

<img width="1353" alt="Screen Shot 2020-04-19 at 6 08 35 PM" src="https://user-images.githubusercontent.com/1761197/79705092-39231980-8269-11ea-8fe2-e7cf6ca7cfd1.png">

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json is linked in above screenshot.

babel.config file has basic babel config with @babel/preset-env and @babel/preset-typescript

```js
{
  "your": { "config": "here" }
}
```

## 🤔 Expected Behavior

Should properly find installed modules

## 😯 Current Behavior

Does not find installed modules.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
Parcel 1 doesn't support Yarn PnP, Parcel 2 however does

**Comment by nnennajohn** [comment]
Ok. Thanks mishnic.

**Comment by nnennajohn** [comment]
@mischnic would this be  parcel@next, because that's what I installed.

**Comment by mischnic** [comment]
Not yet, only `parcel@nightly` for now (next is 5 months old 😬 ).

**Comment by nnennajohn** [comment]
Ah. No wonder. I gave up thinking I set something up wrongly. Will try again with the nightly. Perhaps this should be documented somewhere? 

Thank you.
