### ISSUE TITLE
Node 13.x bundle error (linecounter.length?)

### ISSUE THREAD

**Issue by ogomez92** [parcel-bundler/parcel#4500]
# 🐛 bug report

Error when building, apparentlys omething to do with lineCounter onb undle.js?
## 🎛 Configuration (.babelrc, package.json, cli command)
cli parcel-bundler with target electron

Default, I didn't change anything.
```js
{
  "your": { "config": "here" }
}
```

## 🤔 Expected Behavior
Successfully build.

Build / watch to work properly.
## 😯 Current Behavior
I'm having a similar issue. Happened right after upgrading to Node 13:
  "devDependencies": {
    "electron": "^8.2.3",
    "parcel-bundler": "^1.12.4"
  }
(base) MacBook-Pro-de-oriol:road uri$ npm run build

> roadsplat@4.0.1 build /Users/uri/git/road
> parcel build ./js/main.js -d . --target=electron

🚨  Cannot read property 'length' of undefined
    at lineCounter (/Users/uri/git/road/node_modules/parcel-bundler/src/utils/lineCounter.js:3:30)
    at JSPackager.writeModule (/Users/uri/git/road/node_modules/parcel-bundler/src/packagers/JSPackager.js:127:60)
    at async JSPackager.addAsset (/Users/uri/git/road/node_modules/parcel-bundler/src/packagers/JSPackager.js:88:5)
    at async Bundle._addDeps (/Users/uri/git/road/node_modules/parcel-bundler/src/Bundle.js:250:5)
    at async Bundle._package (/Users/uri/git/road/node_modules/parcel-bundler/src/Bundle.js:219:7)
    at async Promise.all (index 0)
    at async Bundle.package (/Users/uri/git/road/node_modules/parcel-bundler/src/Bundle.js:202:5)
    at async Bundler.bundle (/Users/uri/git/road/node_modules/parcel-bundler/src/Bundler.js:325:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! roadsplat@4.0.1 build: `parcel build ./js/main.js -d . --target=electron`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the roadsplat@4.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/uri/.npm/_logs/2020-04-20T09_33_53_350Z-debug.log
(base) MacBook-Pro-de-oriol:road uri$ npm -v
6.14.4
(base) MacBook-Pro-de-oriol:road uri$ node -v
v13.13.0
(base) MacBook-Pro-de-oriol:road uri$ 

Errors out.

I idid, above.
## 💁 Possible Solution
Not sure, it's something to do with bundle.js.

## 🔦 Context
I was trying to build my project which is using electron.

Unable to continue with my project.

## 💻 Code Sample
https://github.com/ogomez92/roadsplat3d.git

## 🌍 Your Environment
Mac OSX 10.15  latest node upgraded with brew upgrade node 13 and npm 6.14

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
Works for me:
```
$ yarn build
yarn run v1.22.4
$ parcel build ./js/main.js -d . --target=electron
✨  Built in 14.83s.

main.js.map    185.74 KB     148ms
main.js         70.87 KB    13.80s
✨  Done in 18.04s.
$ node -v
v13.13.0
```

**Comment by ogomez92** [comment]
Ohh, thank you so much, removing the .cache fixed it. Don't know how I overlooked it. Thank you!
