### ISSUE TITLE
dont mangle exports

### ISSUE THREAD

**Issue by JAicewizard** [parcel-bundler/parcel#4502]
# 🙋 feature request

A cli flag for disable mangling exports

## 🤔 Expected Behavior

I should be able to call `foo()` from HTML when I have foo exported in my javascript.

## 😯 Current Behavior

Right now exports are mangled/obvuscated in such a way that I cannot call `foo()` from HTML

## 💁 Possible Solution

I dont know about any workarounds, webpack 5.0 shoulld have this but I havnt been able to test it out because of a bug/setup issue.

## 🔦 Context

This is for use where I import a JS file from HTML and tooling packages it and minifies it

## 💻 Examples

index.html
```
  <!doctype html>
  <html>
   <head>
     <title>Getting Started</title>
   </head>
   <body>
     <script src="./main2.js"></script>
     <button type="button" onclick="hi()">hi</button>
   </body>
  </html>
```

main.js
```
export function hi() {
	console.log("hello world!!!");
}
```

`$parcel build main.js -o main2.js`

**Comment by Blakeinstein** [comment]
I am facing this problem as well, I do not understand why this was marked closed. I use parcel to create a single index.html file to import to webview, but I cant call webview.eval(js) as the top level variables are mangled.

**Comment by mischnic** [comment]
Exporting a variable in script tag doesn't expose it as a global variable.

If you try this with a `<script type="module">`  tag and the browsers's native ESM support, it wouldn't work either.

Do this instead: `window.hi = function hi(){ console.log(....); }`

**Comment by Blakeinstein** [comment]
thats the thing, I have structs containing my variablies, 
```js
const component = {
	hi: () => { console.log("hello world"); }
};
```

Since my toplevel component is mangled, component is converted to something like "o", and calling "component.hi()" doesn't work in production.
