### ISSUE TITLE
Upgrate Required Status Code on Watch

### ISSUE THREAD

**Issue by garthenweb** [parcel-bundler/parcel#4503]
# 🐛 bug report

When starting the watch task with an index.html file the watch server responds with 206 Upgrade Required status code.

## 🎛 Configuration (.babelrc, package.json, cli command)

See https://github.com/garthenweb/parcel-bug-report-examples/tree/bug/upgrade-required

## 🤔 Expected Behavior

Should serve the application in watch mode.

## 😯 Current Behavior

Responds with 206 Upgrade Required. 

## 💁 Possible Solution

I have no clue what is going one. Maybe parcel things it should serve via https? Or maybe something wrong with the dependencies (it is a fresh install).

Changing the port did not help.

## 💻 Code Sample

https://github.com/garthenweb/parcel-bug-report-examples/tree/bug/upgrade-required

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.226
| Node             | v12.8.1
| npm         | v6.14.4
| Operating System | Windows (WSL v1/ Ubuntu Bash)

**Comment by mischnic** [comment]
So you started `parcel watch` and opened `localhost:1234` in the browser?
The whole point of watch mode is provide your own http dev-server, only HMR is done by Parcel. So that status code is trying to tell you that you should change from http to a websocket.

**Comment by garthenweb** [comment]
Ah, really?! Okay, looks like I mixed things up. I did in deed expect the `serve` behavior from watch.

Thanks for the fast answer :)
