### ISSUE TITLE
Custom runtime which injects child bundles dynamically behaves unintended 

### ISSUE THREAD

**Issue by garthenweb** [parcel-bundler/parcel#4504]
# 🐛 bug report

When creating a custom runtime that injects child bundles as dynamic imports into the main bundle, the watch mode for child bundles is broken and the content is included twice in the application (in the main bundle as well in the child bundle).

## 🎛 Configuration (.babelrc, package.json, cli command)

See https://github.com/garthenweb/parcel-bug-report-examples/tree/bug/runtime-import-child-bundle

## 🤔 Expected Behavior

It should behave the same way as if you would add the code, which is created by the manifest, by hand:
* no duplicate content
* watch mode should work

See step 10 and 11 in the example repo.

## 😯 Current Behavior

* the watch does not update the bundles
* the content of the child bundles is included twice (this also happens when bundling for production)

## 💁 Possible Solution

Not so sure about this, I guess something is not running in the correct order.

## 🔦 Context

I am trying to build a plugin, similar to [react-imported-component](https://www.npmjs.com/package/react-imported-component), for parcel 2.

The goal is to fetch all required dynamic bundles before react starts rendering so that the whole application can start in sync and hydrate the markup generated on the server.

Therefore it finds out about all possible dynamic imports and injects them with a name that is known on the server into the document, so parcel can transform it afterward as usual.

I had the feeling that a custom runtime is to be the best solution to this, as other approaches would have required me to bundle the app twice.
Beside the mentioned side effects this is already working perfectly fine :)

## 💻 Code Sample

See https://github.com/garthenweb/parcel-bug-report-examples/tree/bug/runtime-import-child-bundle for a minimal setup.

If you like to check out the more advanced version, you can have a look here: https://github.com/garthenweb/pexo/blob/master/src/cli/parcel-runtime-pexo-dynamic-imports/index.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.226
| Node             | v12.8.1
| npm         | v6.14.4
| Operating System | Windows (WSL v1/ Ubuntu Bash)

BTW: Parcel 2 is looking more and more stable to me, really cool! You guys made awesome progress in the last weeks 🎉

**Comment by mischnic** [comment]
Here you are importing the entry asset, not the actual bundle.
```js
    for (let b of bundleGraph.getBundles()) {
      if (bundle === b) {
        continue;
      }
      const importBundleName = path.relative(
        __dirname,
        b.getMainEntry().filePath
      );
      imports.add(importBundleName);
    }

    return {
      filePath: __filename,
      code: `globalThis.test = () => {
        ${[...imports].map((importPath) => `import("${importPath}")`).join(";")}
        }`,
      isEntry: true,
    };
```
(because runtimes are processed by transformers just like any other asset)

I think you really need to fabricate a dependency from the runtime to the child bundle, but a runtime can't do that?

cc @wbinnssmith

**Comment by garthenweb** [comment]
Hmm, not sure if I can follow completely. But I also thought about whether the code is valid.

In the end, the entry asset as far as I understand is actually what I want (maybe I mixed terms in the description), as this is what we require in the code as well. The desired outcome looks good to me:

```
globalThis.test = () => {
      import("../src/child.js")
      }
```

The import path is relative to the runtime and it requires the file that was required in index as well.

If I just copy/paste this into the index.js (and adjust the path), everything works as expected when removing the runtime. 🤔 Do I miss anything?

**Comment by mischnic** [comment]
> If I just copy/paste this into the index.js (and adjust the path), everything works as expected when removing the runtime

There is a deduplication step before the runtimes are inserted (so for user assets). The deduplication that runs after runtimes are inserted is far less sophisticated. That would explain the difference here.

**Comment by garthenweb** [comment]
> There is a deduplication step before the runtimes are inserted (so for user assets). The deduplication that runs after runtimes are inserted is far less sophisticated. That would explain the difference here.

Okay, sounds valid.

> I think you really need to fabricate a dependency from the runtime to the child bundle, but a runtime can't do that?

I tried to make sense of this comment and found something like the following in my bundle (code is a bit beautified).

``` javascript
{
  "c00e607576b6da73f3471278d158f50f": [
    function (require, module, exports) {
      require("./child");
    },
    { "./child": "97a67c4f2653e245f41059089a75d0ee" },
  ],
  "97a67c4f2653e245f41059089a75d0ee": [
    function (require, module, exports) {
      module.exports = require("./loaders/browser/js-loader")(
        require("./bundle-url").getBundleURL() +
          require("./relative-path")("a1be717113550974", "26833814e0904a97")
      ).then(() => parcelRequire("6eec821e201d6adeef508e355d4711bd"));
    },
    {
      "./loaders/browser/js-loader": "c19d18327df717e70d631a984cadc3c0",
      "./bundle-url": "2146da1905b95151ed14d455c784e7b7",
      "./relative-path": "1b9943ef25c7bbdf0dd1b9fa91880a6c",
    },
  ],
}
```

If I call `parcelRequire("97a67c4f2653e245f41059089a75d0ee")` in my test function runtime, it fetches the bundle as expected.

The code `require("./loaders/browser/js-loader")(require("./bundle-url").getBundleURL.....` is injected using the JSRuntime using the `getLoaderRuntimes` function.

Therefore, if I would reuse this functionality but strip out the `module.exports =` but inject it inline into my runtime, I have the feeling this should work.

Do you think this is worth exploring? Would be super nice to get feedback on this idea to not waste too much time going into the wrong direction :)

**Comment by garthenweb** [comment]
So, I tried it out and it actually looks like it is working. But I needed to copy&past huge parts of the JSRuntime which is not ideal as every change in parcel could now break it.

Do you have any ideas on how to make stuff like that easier?

For this problem, it would help me to expose the helper functions from the JSRuntime so I could reuse them, but this is probably not a good solution thinking long term.
