### ISSUE TITLE
export interface unexpected token

### ISSUE THREAD

**Issue by MarkLyck** [parcel-bundler/parcel#4509]
Latest version of parcel@2.0.0-alpha.3.2 doesn't work with TypeScript.

error:
`@parcel/transformer-babel: Unexpected token (13:17)`

here's the code that causes the error:

```
export interface AdminPropsType {
  specUrl: string;
  setAuthToken: any;
  authToken: string;
  setSpec: any;
  showAllResources?: boolean;
  theme?: any;
}
```

using "interface" breaks the parcel bundler.

## 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc
```js
module.exports = {
  presets: ["@babel/preset-react"],
  plugins: [
    "styled-components",
    "@babel/plugin-syntax-export-default-from",
    [
      "module-resolver",
      {
        root: ["."],
        alias: {
          "~": "./src/",
          common: "./src/common",
          Admin: "./src/Admin",
          tests: "./tests",
        },
      },
    ],
  ],
};
```

tsconfig.json
```js
{
  "compilerOptions": {
    "outDir": "./dist/",
    "module": "esNext",
    "strictNullChecks": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "jsx": "react",
    "noUnusedParameters": true,
    "noUnusedLocals": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "declaration": true,
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "target": "es2019",
    "lib": ["es5", "es6", "es7", "es2017", "dom"],
    "sourceMap": true,
    "types": ["react", "jest", "node"],
    "baseUrl": ".",
    "paths": {
      "~*": ["./src/*"],
      "common/*": ["src/common/*"],
      "tests/*": ["tests/*"]
    }
  },
  "include": ["src/**/*", "src/typings.d.ts", "@types"],
  "exclude": ["./node_modules", "dist"]
}
```

## 🤔 Expected Behavior

It should parse Typescript correctly.

## 😯 Current Behavior

Unexpected Token error occurs

## 🔦 Context

This error only happens in parcel@2.0.0-alpha.x.x
When using parcel-bundler@1.12.4 this works just fine.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | v12.12.0
| npm/Yarn         | 1.17.3
| Operating System | MacOS Catalina

**Comment by mischnic** [comment]
By default, Parcel uses babel to transpile typescript. You created your own babelrc so Parcel's default babel config (which would specify `@babel/preset-env` and `@babel/preset-typescript` in this case) isn't being used. (Also Babel doesn't read your tsconfig at all.)

Either you add the typescript preset to your babel config or add a `.parcelrc`file:
```
{
  "extends": "@parcel/config-default",
  "transforms": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
}
```
to use tsc for handling Typescript.

**Comment by MarkLyck** [comment]
@mischnic ohh thank you!

That makes sense. Just didn't realize as it wasn't needed to specify it in v1.

Worth adding in the upgrade guide when v2 is stable :)

**Comment by mischnic** [comment]
> Worth adding in the upgrade guide ~when v2 is stable~

Or now: 😄 https://parcel2-docs.now.sh/getting-started/migration/#typescript
