### ISSUE TITLE
GraphQL : Export string instead of AST

### ISSUE THREAD

**Issue by squirly** [parcel-bundler/parcel#4511]
# 💬 RFC

Change the GraphQL transformer to return a string when importing a GraphQL file instead of an AST object.

## 🔦 Context

This would be a breaking change so the, v2 release is a perfect time to make this change.

For many reasons a string is a preferable return type:
-   Standard: From what I can find other bundlers export a string. I was not expecting an AST the first time I imported a graphql file using parcel.
-   Useability: It is ready to send to the server with `fetch` and a majority of http clients, so that the user does not need to have the `graphql` package on the frontend to format the value before use. Is the AST is desired it can be parsed.
-   Dependencies: Continued from above the `graphql` package is no longer required to make a valid query.
-   Bundle size: Continued again no longer need the `graphql` package on the frontend and it is a significantly smaller format to store the bundle:
    ```
    query GetUser($userId: ID!) {user(id: $userId) {id name isViewerFriend}}
    ```
    vs
    ```
    {"kind":"Document","definitions":[{"kind":"OperationDefinition","operati
    on":"query","name":{"kind":"Name","value":"GetUser","loc":{"start":6,"en
    d":13}},"variableDefinitions":[{"kind":"VariableDefinition","variable":{
    "kind":"Variable","name":{"kind":"Name","value":"userId","loc":{"start":
    15,"end":21}},"loc":{"start":14,"end":21}},"type":{"kind":"NonNullType",
    "type":{"kind":"NamedType","name":{"kind":"Name","value":"ID","loc":{"st
    art":23,"end":25}},"loc":{"start":23,"end":25}},"loc":{"start":23,"end":
    26}},"directives":[],"loc":{"start":14,"end":26}}],"directives":[],"sele
    ctionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"
    kind":"Name","value":"user","loc":{"start":29,"end":33}},"arguments":[{"
    kind":"Argument","name":{"kind":"Name","value":"id","loc":{"start":34,"e
    nd":36}},"value":{"kind":"Variable","name":{"kind":"Name","value":"userI
    d","loc":{"start":39,"end":45}},"loc":{"start":38,"end":45}},"loc":{"sta
    rt":34,"end":45}}],"directives":[],"selectionSet":{"kind":"SelectionSet"
    ,"selections":[{"kind":"Field","name":{"kind":"Name","value":"id","loc":
    {"start":48,"end":50}},"arguments":[],"directives":[],"loc":{"start":48,
    "end":50}},{"kind":"Field","name":{"kind":"Name","value":"name","loc":{"
    start":51,"end":55}},"arguments":[],"directives":[],"loc":{"start":51,"e
    nd":55}},{"kind":"Field","name":{"kind":"Name","value":"isViewerFriend",
    loc":{"start":56,"end":70}},"arguments":[],"directives":[],"loc":{"start
    ":56,"end":70}}],"loc":{"start":47,"end":71}},"loc":{"start":29,"end":71
    }}],"loc":{"start":28,"end":72}},"loc":{"start":0,"end":72}}],"loc":{"st
    art":0,"end":72}}
    ```

Further processing during transformation could be done by adding configuration. Eg:
```
{
  "graphql": {
    "processor": "graphql/language#parse",
  },
}
```

## 💻 Examples
Current:
```
import MyQuery from './MyQuery.graphql';
import {print} from 'graphql/language';

const query = print(MyQuery);

const result = await fetch(GRAPHQL_ENDPOINT, {
  method: 'POST',
  body: JSON.stringify(query: MyQuery, variables: {})
});
```
With string:
```
import MyQuery from './MyQuery.graphql';

const result = await fetch(GRAPHQL_ENDPOINT, {
  method: 'POST',
  body: JSON.stringify(query: MyQuery, variables: {})
});
```

### Client Breakdown
A survey of clients from [`graphql.org`](https://graphql.org/code/#javascript-1) to see what is popular.

Clients that expect an AST:
-   [`apollo-client`](https://www.apollographql.com/docs/react/api/react-hooks/) (has an included template tag provided to parse queries).

Clients that expect a string:
-   [`graphql-request`](https://github.com/prisma-labs/graphql-request)
-   [`lokka`](https://github.com/kadirahq/lokka)
-   [`urql`](https://formidable.com/open-source/urql/docs/basics/queries/)
-   [`graphqurl`](https://github.com/hasura/graphqurl)

Clients that expect a string passed to a tag:
-   [`nanographql`](https://github.com/yoshuawuyts/nanographql)

Other (I would not expect users of these to also use the parcel graphql transformer):
-   [`Relay`](https://relay.dev/docs/en/graphql-in-relay#graphql) (queries preprocessed to `GraphQLTaggedNode` with the relay compiler)
-   [gq-loader](https://github.com/Houfeng/gq-loader) (webpack loader that exports an async function)
-   [Grafoo](https://github.com/grafoojs/grafoo) (babel plugin that preprocesses a tag, would not support imported queries)

Unknown:
-   [AWS Amplify](https://docs.amplify.aws) (cannot find the graphql client docs)

**Comment by elliottkember** [comment]
@squirly Hi! I just discovered that I'll be affected by this, as I'm using `react-apollo` and upgrading to Parcel, so all my `.graphql` imports are now strings instead of ASTs.

I checked the documentation, and it says `With Parcel 2's new plugin architecture, creating a plugin that parses the string into an AST at build time (as Parcel 1 did) is very easy.` I haven't written a Parcel plugin before, but I suspect `gql(query)` will do everything I need. Is there an existing `graphql-ast` transformer that will do what I need, or do I need to make one?

Thanks!

**Comment by mischnic** [comment]
It would look something like this:

```js
import {Transformer} from "@parcel/plugin";
import gql from "graphql";

export default new Transformer({
	async transform({asset}) {
		let code = await asset.getCode();
		let result = gql.parse(code); // <-- not quite sure what need you call here
		asset.setCode(`module.exports = ${JSON.stringify(result)};`);
		return asset;
	}
}
```

and then in your project you need a .parcelrc with
```json5
{
	"extends": "@parcel/config-default"
	"transformers": {
		"*.{gql,graphql}": ["parcel-transformer-graphql-ast"], // <--- your package name
	}
}
```

**Comment by elliottkember** [comment]
@mischnic Thank you! I got it working at https://github.com/elliottkember/parcel-transformer-graphql-ast

**Comment by fenech** [comment]
@elliottkember the Github link is no longer available. I found the code on NPM and tried to install it, but it looks like the `package.json` refers to "parcel-bundler", whereas Parcel 2's package is just "parcel".

```package.json
  "devDependencies": {
    "babel-eslint": "^8.2.3",
    "eslint": "^4.19.1",
    "eslint-config-standard": "^12.0.0-alpha.0",
    "eslint-plugin-standard": "^3.1.0",
    "parcel-bundler": ">= 1.12.3 < 2",
    "pre-commit": "^1.2.2",
    "standard": "^11.0.1"
  },
  "peerDependencies": {
    "parcel-bundler": ">2"
  },
```
It seems strange to depend on both `<2` in devDependencies and `>2` in peerDependencies, too.

I am wondering what the best approach is here between fixing up the existing package or just making a completely separate one. Any preferences?

**Comment by elliottkember** [comment]
@fenech Sorry! I don't know what happened to that repository. I found this repository in my "deleted repositories" list (thanks github) https://github.com/elliottkember/parcel-plugin-graphql-ast/blob/master/src/transformer.js - that may be helpful? It has a slightly different name but I think it's the same. I no longer work on that GraphQL / react-apollo application so I can't be sure, but I remember it was a little bit involved.

As for the non-matching `parcel-bundler` imports, well... yeah, I'd say best idea is to make a separate one :)
