### ISSUE TITLE
Option for http2 protocol 

### ISSUE THREAD

**Issue by popuguytheparrot** [parcel-bundler/parcel#4513]
# 🙋 feature request

Option for http2 protocol 

## 🤔 Expected Behavior

change http/1.1 to h2 for fetch bundled resourses from server. 

## 😯 Current Behavior

No way to change protocol for fetch

## 💁 Possible Solution

CLI option which change protocols 

## 🔦 Context

I have a lot of lazy load modules and http/1.1 increases delay for response

**Comment by DeMoorJasper** [comment]
I'd say we could make it the default although I'm worried about us enforcing https in that case as well, which is a self-signed certificate in most cases.
