### ISSUE TITLE
build support for React Fast Refresh (HMR)

### ISSUE THREAD

**Issue by cliffordp** [parcel-bundler/parcel#4514]
Parcel got a mention from Dan Abramov at https://github.com/facebook/react/issues/16604#issuecomment-528663101 where he details what it would take for bundlers (e.g. webpack or parcel) to implement Fast Refresh. GIF from Twitter: https://twitter.com/addyosmani/status/1251967793479606272

I thought it'd be swell to at least get the TODO logged here. Not sure if the maintainers would only consider this for Parcel 2, but I don't know P2's status or if it's continually being worked on or when it's expected to be released.

**Comment by mischnic** [comment]
> I thought it'd be swell to at least get the TODO logged here

I don't know why Next.js's experimental implementation has spared the interest on Twitter.

I have implemented this feature 5 months ago and it's part of Parcel 2 since then: https://github.com/parcel-bundler/parcel/pull/3654

> if it's continually being worked

Yes

**Comment by cliffordp** [comment]
HaHaHa... dude, parcel is so cool. What's P2's status (alpha/beta)? Is it expected to be released in 2020?
