### ISSUE TITLE
Single command that can both "watch" and "serve" files

### ISSUE THREAD

**Issue by krisnye** [parcel-bundler/parcel#4518]
# 🙋 feature request

In a very simple project I can run "parcel watch src/index.html" and it will build the results into "./dist" folder and watch for changes (as well as run HMR server).

If I run "parcel serve src/index.html" it will NOT build that folder but it will serve the results over http.

I want a single command that will do both of the above.

I DO NOT want to have to run both of these as it's a pain and using & to run them in parallel leaves one as a background process.

## 🤔 Expected Behavior

Either 'parcel watch' should also serve files over http or else 'parcel serve' should also build to ./dist (if there are not multiple targets specified in the package.json)

## 😯 Current Behavior

@see above

## 💁 Possible Solution

I'll attach a PR for this later.

## 🔦 Context

We have a special native browser at Adobe which needs to use the output in the filesystem from 'parcel watch'.

We also need to test in a browser over http.

I want to be able to run a single command to serve up both with HMR.

**Comment by mischnic** [comment]
There is a difference between "watch mode with HTTP server" and "serve mode with that outputs to `dist`" if you don't specify any targets.

Would `parcel serve src/index.html --dist-dir ./something` work for you?

**Comment by krisnye** [comment]
Yes, that would work, and my PR actually makes it so that would work (which it wouldn’t before since serve would always force usage of .parcel-cache/dist).

I don't think it's ideal though.

Let me see if I understand current behavior.

If you have multiple defined targets in package.json then:

watch mode will build and incrementally rebuild all of them.
serve mode will throw an error if you don’t specify a target as it can't host them all on the same port.
if you specify a single target then it DOES build it to the specified dist directory.

If you do NOT have any targets defined then:

watch mode will build out to ./dist
serve mode will NOT build out to the ./dist directory

It seems for consistency that having no targets should be equivalent to having one default target which writes to ./dist in which case `parcel serve index.html` should write to ./dist.

**Comment by devongovett** [comment]
Proposal:

* Write to `./dist` by default if there are no targets defined in package.json
* If targets are defined, then write into .parcel-cache/dist by default, unless a target to build is specified on the cli with `--target`.
* If `--dist-dir` is specified, then write into that

**Comment by mischnic** [comment]
At some point, this was changed so that `parcel serve` also outputs to `./dist` by default instead of `.parcel-cache/dist`
