### ISSUE TITLE
Dead Code of Dependencies not removed

### ISSUE THREAD

**Issue by garthenweb** [parcel-bundler/parcel#4524]
# 🐛 bug report

When using if-else cases to differentiate between e.g. browser and server but also for different build env, unused dependencies are not removed.

The code is not failing in any way, it is just bigger than it needs to be.

## 🎛 Configuration (.babelrc, package.json, cli command)

See https://github.com/garthenweb/parcel-bug-report-examples/tree/bug/dead-code-elemination-dependency-wrong-branch

## 🤔 Expected Behavior

Should remove all unused code.

## 😯 Current Behavior

Keeps the library code.

## 💁 Possible Solution

* insert Buffer library after dead code elimination?
* remove Buffer library after dead code elimination?
* find out that Buffer is not used and split it out?
* insert the Buffer library into the branch where it is used in?

## 💻 Code Sample

```javascript
const btoa = process.browser
  ? globalThis.btoa
  : (str) => Buffer.from(str.toString(), "binary").toString("base64");

console.log(btoa("test"));
```
https://github.com/garthenweb/parcel-bug-report-examples/blob/bug/dead-code-elemination-dependency-wrong-branch/src/index.js

The same happens for the following code

```javascript
import { act } from 'react-dom/test-utils'
const fireAsAct = (cb: () => void) => {
  if (process.env.NODE_ENV === "test") {
    act(() => cb());
  } else {
    cb();
  }
};

fireAsAct(() => console.log('test'));
```

For the latter example, I am actually not sure if it is a bug, as the `react-dom` does not have `sideeffects: false` set in package.json. But inserting the Buffer in the first example is unexpected.

Rewriting the `react-dom` example to the following works as expected
```javascript
const fireAsAct = (cb: () => void) => {
  if (process.env.NODE_ENV === "test") {
    const { act } = require("react-dom/test-utils");
    act(() => cb());
  } else {
    cb();
  }
};

fireAsAct(() => console.log('test'));
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.226
| Node             | v12.8.1
| npm         | v6.14.4
| Operating System | Windows (WSL v1/ Ubuntu Bash)

**Comment by mischnic** [comment]
> For the latter example, I am actually not sure if it is a bug, as the react-dom does not have sideeffects: false set in package.json.

That would be the first step. But at the moment `index.js` would still have "act" marked as imported in `asset.symbols`, so it would still be included. 
Two ways to fix this:
1.  In `hoist.js` for `ImportDeclaration`, don't add it if: for every reference to the imported symbol there is a falsy conditional-statement among the node's ancestors (this sounds very expensive).
2. in the `JSTransformer` visitors  that does the `process.env` inlining, directly remove the unused branch from the AST (I think this is the preffered solution)

> But inserting the Buffer in the first example is unexpected.

Will open a PR for that in a bit.

**Comment by garthenweb** [comment]
> Will open a PR for that in a bit.

That was fast, really cool 😃  I can prove it's working!

> in the JSTransformer visitors that does the process.env inlining, directly remove the unused branch from the AST (I think this is the better solution)

I gave it a try, but have some questions about it. Maybe you like to have a look? (see the linked PR) :)

**Comment by AndyOGo** [comment]
I have the same issue, according to the docs **development-only features are supported** and [terser's `dead_code`](https://github.com/terser/terser#compress-options) facilitates them.

**But** this code has no removal effect:

```js
if (process.env.NODE_ENV === 'development') { // Or, `process.env.NODE_ENV !== 'production'`
  // Only runs in development and should be stripped from production build.
  // But isn't stripped fromproductoin build...
}
```

> To take advantage of the same kind of development-only debugging features, ensure that [terser's `dead_code` option](https://github.com/terser/terser#compress-options) is on (it is by default) and wrap any development-only debugging in a conditional check like so:
https://parceljs.org/production.html#optimisations

**Comment by mischnic** [comment]
Your case doesn't have to do anything with this issue, but `process.env.NODE_ENV` is replaced by Parcel itself by `"development"` or `"production"` and then afterwards Terser would remove that whole if statement.

**Comment by AndyOGo** [comment]
Thank you for your quick answer @mischnic 

Aforementioned module is exported as CommonJS and consumed as a dependency.
I double checked the resulting bundle properly replaces `process.env.NODE_ENV` with `"production"`, but as mentioned in the docs, the dead code should be removed, but is not.

Maybe I miss understand something in the docs here https://parceljs.org/production.html#optimisations
Though I'm sure, it should work, with or without tree shaking enabled, because it's baked by terser's `dead_code` option (which is enabled by default).

**Comment by AndyOGo** [comment]
Thanks @mischnic 

Yes, this is what I assumed too.

Here is how I got it working for my case:

`module-a.js` (did not work):
```js
import fatJson from './fat.json';

export function checkExistence(key) {
  if (process.env.NODE_ENV === "development") {
     // ... 
  }

  return true;
}
```

`module-a.js` (works this way):
```js
export function checkExistence(key) {
  if (process.env.NODE_ENV === "development") {
    const fatJson = require('./fat.json');
     // ... 
  }

  return true;
}
```

1. publish `module-a` on NPM
2. import in my app
3. build with parcel
4. production build now excludes the `fat.json`

**Comment by mischnic** [comment]
You're in the right issue after all, but that wasn't really obvious from your first example 😬 . And that's the workaround that I would have suggested as well.

(With scope-hoisting, the first case should work because the json should get removed).

**Comment by mischnic** [comment]
> `module-a.js` (did not work):
> ```js
> import fatJson from './fat.json';
> 
> export function checkExistence(key) {
>   if (process.env.NODE_ENV === "development") {
>      // check stuff with fatJson ... 
>   }
> 
>   return true;
> }
> ```

This works in Parcel 2 if you add
```js
{
	"sideEffects": ["module-a.js"]
}
```
or (depending on the situation)
```js
{
	"sideEffects": false
}
```
so that the JSON file is marked as side-effect free.
