### ISSUE TITLE
Output file "index.mjs" which does not match the compiled bundle type "js".

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#4529]
# 🐛 bug report

Given that Node sometimes requires the file extension `mjs`, this should be possible:

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
	"module": "dist/index.mjs",
	"devDependencies": {
		"@babel/core": "^7.0.0"
	}
}

```

```
Target "module" declares an output file path of "dist/index.mjs" which does not match the compiled bundle type "js".
```

**Comment by ianstormtaylor** [comment]
Running into this as well, happens with `.mjs` or `.cjs` extensions.

**Comment by devongovett** [comment]
This should have been fixed by https://github.com/parcel-bundler/parcel/commit/e24d8f78b00c32968079f2ae515b35e4a921e06e#diff-85544326b29368bcb94d16d90fed0f237d6136ec34c49cae51a7e8404d90681c
