### ISSUE TITLE
Problems with the `@parcel/core` api

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#4530]
Ok, I got the API to work, sort of.  I'm not sure if I should file a bug for this (i.e. are the docs wrong or the code?), but the following snippet from the docs link has some issues:

```
await b.build();

for (let file of outputFS.readdir("/")) { // TODO ?
  console.log(file, await outputFS.readFile(file, "utf8"));
}

await workerFarm.end();
```

* `b.build()` seems to expect an argument from which it wants to destructure `signal`.   I replaced this with `b.run()` and that seemed to work.

* `outputFS.readdir` is async and returns promises so the `for` loop fails

* `await workerFarm.end()` causes `[1]    65400 segmentation fault  node index.js` at the end of my script.  Without this, the script doesn't exit however.

Finally, my goal is to use the memory file system for both input and output filesystems.  If I do this by writing the code into the memory file system and using it for the input, then `b.run()`  never completes and I see no output.  If I write the code to disk then it works fine.

EDIT: here is a gist with the code I am using

https://gist.github.com/pagameba/b3f8aa27bf2c1bcaed9a2e0cf7cf5eec

_Originally posted by @pagameba in https://github.com/parcel-bundler/parcel/issues/3377#issuecomment-619366117_

**Comment by mischnic** [comment]
@pagameba

Your code works for me (macOS). 

> b.build() seems to expect an argument from which it wants to destructure signal. I replaced this with b.run() and that seemed to work.

I will correct the docs.

> outputFS.readdir is async and returns promises so the for loop fails

Yes, that's what the `TODO` comment was for.

**Comment by pagameba** [comment]
Thanks for looking at this so quickly @mischnic !  If you change the code in index.js and set the inputFS to be the memoryFS on line 13, that is when the problem happens when it hangs.

I'm also on macOS Catalina node v12.4.0 - not sure where the segfault is coming from :/

**Comment by mischnic** [comment]
This is an architectural problem:
- the `inputFS` is used for the input code *and for loading all the plugins*
- the `outputFS` is used for the output code *and for writing the cache*

But Plugin loading and cache should really be a `NodeFS` in most cases.

**Comment by devongovett** [comment]
Can you use an OverlayFS like the tests?

**Comment by mischnic** [comment]
That does work, but you can't use an arbitrary path as the entry point anymore, because for example`@babel/core`.
```js
const path = require("path");
const fs = require("fs");

const defaultConfig = require("@parcel/config-default");
const { default: Parcel, createWorkerFarm } = require("@parcel/core");
const { NodeFS, MemoryFS, OverlayFS } = require("@parcel/fs");

const workerFarm = createWorkerFarm();
const nodeFS = new NodeFS();
const memoryFS = new MemoryFS(workerFarm);

const BASE_PATH = __dirname; // <----- can't be changed
const SRC_PATH = `${BASE_PATH}/src`;
const DIST_PATH = `${BASE_PATH}/dist`;
const CODE_PATH = `${SRC_PATH}/api.js`;

const bundler = new Parcel({
  entries: CODE_PATH,
  cache: false,
  defaultConfig: {
    ...defaultConfig,
    filePath: require.resolve("@parcel/config-default"),
  },
  defaultEngines: {
    browsers: ["last 1 Chrome version"],
  },
  targets: {
    main: {
      engines: { browsers: ["last 1 Chrome version"] },
      distDir: `${DIST_PATH}`,
    },
  },
  inputFS: new OverlayFS(memoryFS, nodeFS),
  outputFS: memoryFS,
  workerFarm,
  autoinstall: false,
  patchConsole: false,
});

fs.readFile(path.join(__dirname, "src", "api.js"), async (err, code) => {
  await memoryFS.mkdirp(SRC_PATH);
  await memoryFS.mkdirp(DIST_PATH);
  await memoryFS.writeFile(`${SRC_PATH}/api.js`, code);
  console.log("bunder starting");
  await bundler.run();
  console.log("bunder complete");
  const files = await memoryFS.readdir(DIST_PATH);
  for (let file of files) {
    console.log(
      file,
      await memoryFS.readFile(path.join(DIST_PATH, file), "utf8")
    );
  }
  await workerFarm.end();
});
```

**Comment by pagameba** [comment]
:o this looks good ... alternately I could preload the memoryFS with the node_modules directory.  In practice, I will be fetching dependencies of the script being compiled from a dependency packager (https://github.com/codesandbox/dependency-packager) as cached JSON and will need that to be installed in the memoryFS as well.  Perhaps I can just get parcel as part of that and load it all up.

Thanks for the great support and feedback.
