### ISSUE TITLE
parcel 1 does not handle "?query" URLs as expected

### ISSUE THREAD

**Issue by endafarrell** [parcel-bundler/parcel#4535]
# 🐛 bug report

I am building a multi-page site; and one page is for some demos; and by passing different URL parameters different demos are run.

If I create links for these other demos in the form of 
* root-slash + path + ? + query (eg: &lt;a href="/demos/demo-a?x=1&y=2"&gt;X1/Y2&lt;/a&gt;) 

all is well.

If I create links for these other demos in the form of 
* ? + query (eg: &lt;a href="?x=1&y=2"&gt;X1/Y2&lt;/a&gt;) 

then the following error occurs:

    [10:29:11 AM]: Building demo-a.js...
    [10:29:11 AM]: 🚨  /Workspaces/LG/LG/UI/src/demos/null: ENOENT: no such file or directory, open '/Workspaces/LG/LG/UI/src/demos/null'
    [10:29:11 AM]: Error: ENOENT: no such file or directory, open '/Workspaces/LG/LG/UI/src/demos/null

## 🎛 Configuration (.babelrc, package.json, cli command)

No .babelrc
I can't give the package.json "as is" but I could supply parts if needed
My cli command is `parcel --log-level 5 src/index.html`

## 🤔 Expected Behavior

The desire to use `?query` only URLs is to allow for refactoring and renaming without breaking links. When parcel find a `?query` link it shouldn't look for a null named file in the directory, it should link back to the current page.

## 😯 Current Behavior

parcel looks for a null named file in the directory and fails.

The error is shown above. No obvious stack trace is available.

## 💁 Possible Solution

Hmmm. This ~looks~ like it's related to the building of the dependency graph, and likely to be deep in the bundler's core.

## 🔦 Context

Trying to keep code clean and refactorable by reducing the number of places documents are defined. Not a P1, but still both nice, and, perhaps, expected.

**Comment by devongovett** [comment]
Closing since this is for Parcel 1.
