### ISSUE TITLE
add parameters to the serve command to support path access for the entry file

### ISSUE THREAD

**Issue by tolerance-go** [parcel-bundler/parcel#4546]
# 🙋 feature request

I want to add parameters to the serve command to support path access for the entry file

希望 serve 命令，增加参数，对于入口文件支持路径访问

## 🤔 Expected Behavior

Execute `parcel -p src/**/*.visual.html`, It can be accessed through `localhost:1234/src/a/a.visual.html` or other matching paths

执行 `parcel -p src/**/*.visual.html`，可以通过 `localhost:1234/src/a/a.visual.html` 或者其他匹配路径访问

## 😯 Current Behavior

In my file structure, there are many index.html entry files with the same name. It seems that only the first one works

在我的文件结构中，有非常多的 index.html 入口文件，他们的名称都一样，似乎只有首个起作用了

**Comment by mischnic** [comment]
> In my file structure, there are many index.html entry files with the same name

In that case, your input file structure is preserved. I think `localhost:1234/a/a.visual.html` and so on should work.
You are likely getting one index.html because `localhost:1234/src/a/a.visual.html` doesn't actually exist and Parcel serves a root index as a fallback for SPA apps.

**Comment by tolerance-go** [comment]
@mischnic You reminded me that I have more than one path in front of the entry file with the same name, which can be accessed through URL. eg `localhost:1234/a/index.visual.html` `localhost:1234/b/index.visual.html` thx
