### ISSUE TITLE
Leave specific require() as-is?

### ISSUE THREAD

**Issue by sdegutis** [parcel-bundler/parcel#4547]
# 🙋 feature request

An option/flag to tell Parcel to ignore a specific require and leave it as-is instead of bundling it.

## 🤔 Expected Behavior

```js
const options = {
   // ...
  ignoreModules: ['aws-sdk'],
};
```

Output file:

```js
const AWS = require('aws-sdk'); // provided from deployment environment
// use AWS
```

## 😯 Current Behavior

No such option exists. All packages are bundled up. Output file:

```js
const AWS = /* embedded AWS SDK source code */;
// use AWS
```

## 💁 Possible Solution

Add the option, so that the given packages are not bundled up.

## 🔦 Context

Parcel is used by AWS CDK to bundle up NodeJS modules for deployment to AWS Lambda.

However, AWS Lambda has a size limit on the uploaded bundle.

But AWS Lambda also provides the `require` function at runtime, as well as the `aws-sdk`.

So if Parcel had an option to leave `require('aws-sdk')` as-is, then I could upload my code to AWS Lambda.

## 💻 Examples

See above.

**Comment by mischnic** [comment]
As a workaround you try to "outsmart" Parcel with: 😬
```js
let foo = "aws-sdk";
const AWS = require(foo);
```

Does this work for you?

> `ignoreModules: ['aws-sdk']`

Parcel 2 has something like that already implemented:
```json
{
	"app": "dist/index.js",
	"targets": {
		"default": {
			"includeNodeModules": { "aws-sdk": false }
		}
	},
	"engines": {
		"node": ">=10"
	}
}
```

**Comment by sdegutis** [comment]
The workaround works well enough for now, thanks :)
