### ISSUE TITLE
bundle-text: Unexpected missing module

### ISSUE THREAD

**Issue by timreichen** [parcel-bundler/parcel#4555]
# 🐛 bug report
I am experiencing a weird behavior using ```bundle-text:./…```to import styles.
I am working on a big project with lots of elements that import a styles.styl each. That style file loads fine in most of the modules. But on the client, it will throw an error for some.

Even though the style files are valid and the path also, it will always throw this error unless the imports are removed (tried removing cache and dist)

## 🎛 Configuration (.babelrc, package.json, cli command)
- using typescript
- using .styl files for import
```json
{
  "presets": [
    "@babel/preset-typescript",
    "@babel/preset-env"
  ],
  "plugins": [
    "@babel/plugin-transform-runtime",
    [
      "@babel/plugin-transform-typescript",
      {
        "allowNamespaces": true
      }
    ],
    "@babel/plugin-syntax-top-level-await",
    [
      "@babel/plugin-proposal-decorators",
      {
        "decoratorsBeforeExport": true
      }
    ],
    "@babel/plugin-proposal-class-properties"
  ]
}
```

## 🤔 Expected Behavior

imports all files without error

## 😯 Current Behavior

For some ```import styles from "bundle-text:./styles.styl"``` in some modules, it throws error:

```
Uncaught Error: Cannot find module 'e52b7a3caecb94243cd150150d82b143'
    at newRequire (app.ac551baa.js:58)
    at newRequire (app.ac551baa.js:42)
    at localRequire (app.ac551baa.js:80)
    at Object.f6b8f0f26a95fccbbb0986dc866fb9e9../bundle-manifest (app.ac551baa.js:137)
    at newRequire (app.ac551baa.js:68)
    at app.ac551baa.js:111
    at app.ac551baa.js:134
```

The module name of the error is always the same (e52b7a3caecb94243cd150150d82b143).

## 💁 Possible Solution

To be found.

## 🔦 Context

I think it has nothing to do with the setup since it works for some modules. I guess somehow the missing module is lost during the bundling.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.0-nightly.240
| Node             | 14
| npm/Yarn         | 6.14.4
| Operating System | MacOS 10.15.2

**Comment by mischnic** [comment]
As you might have expected, this is hard to investigate without a code sample.

**Comment by mischnic** [comment]
Closing due to lack of response
