### ISSUE TITLE
Wrong variable ordering in build output

### ISSUE THREAD

**Issue by deluksic** [parcel-bundler/parcel#4559]
# 🐛 bug report

I'm using nightly and serving works great, its simple and fast. However, build output seems to have some ordering issues (doesn't matter if the outputFormat is "global", "esmodule", or "commonjs"):
The `exports` object is undefined at this point
```js
  // ASSET: /***/MapsPage.tsx
  Object.defineProperty($a3027cedcf484e59a37c43ffd02f$exports, "__esModule", {
    value: true
  });
```
This produces `Uncaught TypeError: Object.defineProperty called on non-object`. Much later in the output I see:
```js
  var $a3027cedcf484e59a37c43ffd02f$var$_MapsPageQuery,
      $a3027cedcf484e59a37c43ffd02f$exports = {};
```
If I manually move the lines to correct order, everything works again.

NOTE: I'm also using yarn workspaces if that is relevant. Unfortunately, I can't share the project for repro.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "current"
        }
      }
    ],
    "@babel/preset-react",
    "@babel/preset-typescript"
  ],
  "plugins": [
    "relay"
  ]
}
```

## 🤔 Expected Behavior

It should not throw `Uncaught TypeError: Object.defineProperty called on non-object`.

## 💻 Code Sample

Unfortunately its a huge private repo. Reproducing this might be tough.

## 🌍 Your Environment

I'm trying to build a react app that is part of a monorepo. I already figured out how to build a subproject using `parcel build package/` and adding `source` field to `package.json`, but this problem I can't figure out what's wrong. I also checked and there is no circular dependencies either.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2|
| Node             | v12|
| npm/Yarn         | 2|
| Operating System | Ubuntu |

**Comment by deluksic** [comment]
Possibly related: #4399 ?

**Comment by deluksic** [comment]
Another clue: `--no-scope-hoist` 'fixes' the problem

**Comment by mischnic** [comment]
Which version of v2 are you using? Try `parcel@nightly` if this occurred with `parcel@next`.

**Comment by deluksic** [comment]
I am using nightly, freshly yarn installed.

**Comment by mischnic** [comment]
This statement isn't inserted by Parcel (in that case it would be `$parcel$defineInteropFlag($a3027cedcf484e59a37c43ffd02f$exports)`).

Please try this babelrc:
```json
{
  "presets": [
    "@parcel/babel-preset-env",
    "@babel/preset-react",
    "@babel/preset-typescript"
  ],
  "plugins": ["relay"]
}
```

and set your transpile target via `package.json#browserslist` or `.browserslistrc`.

**Comment by deluksic** [comment]
I set `babel.config.json` to what you suggested, cleared the cache and dist and built again using `parcel build package/ --no-minify`.

I'm getting a similar error, but now in a different place:
```js
// Uncaught TypeError: Object.defineProperty called on non-object.
Object.defineProperty($a3027cedcf484e59a37c43ffd02f$exports, "__esModule", {
  value: true
});
```

Also, my `package.json` contains this: 
```
  "main": "dist/index.js",
  "source": "src/index.tsx",
  "targets": {
    "main": {
      "context": "browser",
      "includeNodeModules": true,
      "isLibrary": true,
      "outputFormat": "global",
      "engines": {
        "browsers": [
          "last 1 chrome versions"
        ]
      }
    }
  },
  "browserslist": [
    "last 1 chrome versions"
  ]
```

**Comment by klipstein** [comment]
I've tried the current beta version today and ran into the same issue when switching from v1 to v2. While digging into the issue I was able to create a minimal example which makes this issue reproducible:

~~~js
// bar.js
import { baz } from './foo.js';
~~~

~~~js
// foo.js
const foo = 'foo';
const bar = 'bar';

export const baz = {
  [foo]: {},
  [bar]: {}
};
~~~

~~~bash
parcel build bar.js --no-minify
~~~

When opening the resulting build you'll notice that the variable ordering is wrong. Not really sure why computed property names lead to this issue, but I hope this helps to look closer into the issue.

**Comment by mischnic** [comment]
@klipstein Your situation isn't really related to this, but it's correct for me (computed properties are transpiled by Babel, that's why it might be problematic):
```js
(function () {
  var $bfc39b991eba9e88fc5405e407b67fe$var$_baz;

  function $bfc39b991eba9e88fc5405e407b67fe$var$_defineProperty(
    obj,
    key,
    value
  ) {
    if (key in obj) {
      Object.defineProperty(obj, key, {
        value: value,
        enumerable: true,
        configurable: true,
        writable: true,
      });
    } else {
      obj[key] = value;
    }

    return obj;
  }

  // foo.js
  var $bfc39b991eba9e88fc5405e407b67fe$var$foo = "foo";
  var $bfc39b991eba9e88fc5405e407b67fe$var$bar = "bar";
  var $bfc39b991eba9e88fc5405e407b67fe$export$baz =
    (($bfc39b991eba9e88fc5405e407b67fe$var$_baz = {}),
    $bfc39b991eba9e88fc5405e407b67fe$var$_defineProperty(
      $bfc39b991eba9e88fc5405e407b67fe$var$_baz,
      $bfc39b991eba9e88fc5405e407b67fe$var$foo,
      {}
    ),
    $bfc39b991eba9e88fc5405e407b67fe$var$_defineProperty(
      $bfc39b991eba9e88fc5405e407b67fe$var$_baz,
      $bfc39b991eba9e88fc5405e407b67fe$var$bar,
      {}
    ),
    $bfc39b991eba9e88fc5405e407b67fe$var$_baz);
  console.log($bfc39b991eba9e88fc5405e407b67fe$export$baz);
})();
```

**Comment by klipstein** [comment]
Result for me is currently. Maybe I need to upgrade to a newer babel version then?

~~~
function () {
  Object.defineProperty($d1ab709ba0bfbf1e091cce02dce20c22$exports, "__esModule", {
    value: true
  });
  var $d1ab709ba0bfbf1e091cce02dce20c22$export$baz = void 0;
  $d1ab709ba0bfbf1e091cce02dce20c22$exports.baz = $d1ab709ba0bfbf1e091cce02dce20c22$export$baz;
  var $d1ab709ba0bfbf1e091cce02dce20c22$var$_baz,
      $d1ab709ba0bfbf1e091cce02dce20c22$exports = {};

  function $d1ab709ba0bfbf1e091cce02dce20c22$var$_defineProperty(obj, key, value) {
    if (key in obj) {
      Object.defineProperty(obj, key, {
        value: value,
        enumerable: true,
        configurable: true,
        writable: true
      });
    } else {
      obj[key] = value;
    }

    return obj;
  }

  var $d1ab709ba0bfbf1e091cce02dce20c22$var$foo = 'foo';
  var $d1ab709ba0bfbf1e091cce02dce20c22$var$bar = 'bar';
  var $d1ab709ba0bfbf1e091cce02dce20c22$var$baz = ($d1ab709ba0bfbf1e091cce02dce20c22$var$_baz = {}, $d1ab709ba0bfbf1e091cce02dce20c22$var$_defineProperty($d1ab709ba0bfbf1e091cce02dce20c22$var$_baz, $d1ab709ba0bfbf1e091cce02dce20c22$var$foo, {}), $d1ab709ba0bfbf1e091cce02dce20c22$var$_defineProperty($d1ab709ba0bfbf1e091cce02dce20c22$var$_baz, $d1ab709ba0bfbf1e091cce02dce20c22$var$bar, {}), $d1ab709ba0bfbf1e091cce02dce20c22$var$_baz);
  $d1ab709ba0bfbf1e091cce02dce20c22$export$baz = $d1ab709ba0bfbf1e091cce02dce20c22$var$baz;
  $d1ab709ba0bfbf1e091cce02dce20c22$exports.baz = $d1ab709ba0bfbf1e091cce02dce20c22$export$baz;
})();
//# sourceMappingURL=bar.js.map
~~~

**Comment by klipstein** [comment]
I mostly wonder why it worked with Parcel 1 before and I did not change the babel setup.

**Comment by mischnic** [comment]
Is anyone still experiencing this?

**Comment by PiTiLeZarD** [comment]
Hi everyone, I'm running 2.0.0-beta.1 and end up with the same issue, I'm trying to narrow it down further but so far, using 
```
const sleepDiaryQuery = graphql`
   my_query
`;
```
seems to be the culprit. Building with --no-scope-hoist solves the issue but greatly increases the build size. I don't want to crowd this post with many useless files, if you want me to try anything I'm keen!

**Comment by mischnic** [comment]
@PiTiLeZarD Can you open a new issue with a small code sample to reproduce that problem?

**Comment by PiTiLeZarD** [comment]
@mischnic will do, thanks for answering ;)
