### ISSUE TITLE
[Question] Is there a way to get what is similar to`Webpack.providePlugin`

### ISSUE THREAD

**Issue by cyan33** [parcel-bundler/parcel#456]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
A question.

### 🎛 Configuration (.babelrc, package.json, cli command)

I'm using parcel with customized babel plugin. My `.babelrc` looks like this:

```js
{
  "presets": ["env", "react"],
  "plugins": [
    "transform-class-properties",
    "transform-object-rest-spread",
    [
      "transform-react-jsx",
      { "pragma": "Glamor.createElement" }
    ]
  ]
}
```

However, after transformation, the `Glamor` is not defined in the global scope.

Previously I could achieve this in `webpack.config.js` like this:

```js
...
plugins: [
  new webpack.ProvidePlugin({
    Glamor: 'glamor/react'
  })
]
```

Is there a similar way to do so? I've tried reading https://parceljs.org/plugins.html, but cannot get a clear idea of how to do so.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by devongovett** [comment]
Seems like a good babel plugin. From a quick search I found https://github.com/PavelDymkov/babel-plugin-auto-import. Not sure how well it works, but feel free to try it out and report back!

**Comment by cyan33** [comment]
That solved my problem. Thanks @devongovett 😄

**Comment by devinrhode2** [comment]
Not sure how to use this, but I have SO points for any help you guys can offer here: https://stackoverflow.com/questions/54054264/parcel-how-to-make-react-global-instead-of-importing-it-in-every-file
