### ISSUE TITLE
Autoprefixer browserlist configuration based on development or production build

### ISSUE THREAD

**Issue by ajayns** [parcel-bundler/parcel#4560]
# 🐛 bug report

Based on documentation and little bit of research to override autoprefixer, I use the following code:

```json
"postcss": {
    "plugins": {
      "autoprefixer": {
        "overrideBrowserslist": [
          "last 1 chrome version",
        ]
      }
    }
  }
```

But I'd like to have multiple browserslist depending on environment:
```json
"overrideBrowserslist": {
    "prod": [
      ">0.2%",
    ],
    "dev": [
      "last 1 chrome version",
    ]
  },
```
Possibly a feature that's already available but I'm unsure how to use it.

**Comment by mischnic** [comment]
Does specifying a (global) environment-dependent browserlist (https://github.com/browserslist/browserslist#configuring-for-different-environments) and removing the override work?

**Comment by ajayns** [comment]
Does Parcel pick different browserslist configs based on environment? Else it's just gonna default to "production" setting at all times

**Comment by mischnic** [comment]
Parcel sets `NODE_ENV` to `development` or `production` with `parcel serve` or `parcel build`.

**Comment by ajayns** [comment]
Ahh yes, that seems to do the job. Thaank you for the quick response!
Closing this issue
