### ISSUE TITLE
Strip new lines and tab spaces from GLSL code for production builds

### ISSUE THREAD

**Issue by ajayns** [parcel-bundler/parcel#4562]
# 🙋 feature request

I'd like Parcel to strip GLSL code of `\n` and `\t` characters.

## 🤔 Expected Behavior

Output of GLSL should be completely stripped of these characters in production build.

## 😯 Current Behavior

The output of code looks something like:
```
precision highp float;\n#define GLSLIFY 1\n\nattribute float pindex;\nattribute vec3 position;\nattribute vec3 offset;\nattribute vec2 uv;\nattribute float angle;\n\nuniform mat4 modelViewMatrix;\nuniform mat4 projectionMatrix;\n\nuniform float uTime;\nuniform float uRandom;\nuniform float uDepth;\nuniform float uSize;\nuniform vec2 uTextureSize;\nuniform 
...
```

## 🔦 Context

Reduces code bundle size by removing unnecessary characters.

## 💻 Examples

https://github.com/glslify/rollup-plugin-glslify I believe already does this job

**Comment by mischnic** [comment]
AFAICT, a newline still has to be preserved after macros (`#define GLSIFY 1`).

**Comment by ajayns** [comment]
Hmm that is true. But it in all other cases, they aren't required so maybe a selective removal?

**Comment by mischnic** [comment]
Merging into #3352 for a Parcel 2 implementation.

**Comment by matthijsgroen** [comment]
I don't think this issue is fixed at all. Given a plain shader, parcel in production only makes the source BIGGER by adding a `#define GLSLIFY 1` in there, that does not serve any purpose. 

All spaces, tabs and newlines are still in place. I would expect way more minification out of the box to be honest. or at least not the file to get BIGGER. placing the whole shader into a template literal is now smaller than using a `.vert` or `.frag` asset.

**Comment by mischnic** [comment]
What Parcel version are you using?

**Comment by matthijsgroen** [comment]
2.0.0-beta.2

**Comment by matthijsgroen** [comment]
Adding the following to your package.json:

```
"glslify": {
    "transform": [
      "glslify-optimizer"
    ]
  },
```

Requires that you install `glslify-optimizer` seperately first, but that requires `node-gyp` that is a pain to setup. All in all this optimizer is build upon https://github.com/aras-p/glsl-optimizer which is not actively maintained.

It seems a lot of setup to get some spaces stripped. Would it help to do a simple minification like this? I tested this on my shader and should work fine:

```javascript
const util = require("util");
const readFile = util.promisify(require("fs").readFile);

// Trim and remove line comments
const minifiyLine = (line) => line.trim().split("//")[0];

const minifiyShader = (shaderSource) =>
  shaderSource
    .split("\n")
    .reduce(
      (result, line) =>
        line.startsWith("#define")
          ? result + (result.endsWith("\n") ? "" : "\n") + `${line}\n`
          : result + minifiyLine(line),
      ""
    );

const start = async () => {
  const shaderSource = await readFile("./vertexShader.vert", "utf8");
  console.log("in:", shaderSource.length);
  const minified = minifiyShader(shaderSource);
  console.log("out:", minified.length);
  console.log(minified);
};

start();
```

output in my case was:

```
in: 3744
out: 3151
```

It does not 'parse' the shader, so it is not able to minify var/function names, but it does already more than the current setup, without dependencies.

Could this help in minifying the glsl code?

**Comment by matthijsgroen** [comment]
I added to a pre-build step for my project for now: https://github.com/matthijsgroen/geppetto-player/commit/b7b0b25ebfe14972d4eaa0cefb1fac3a7404d8ed

**Comment by matthijsgroen** [comment]
This minifier looks really good. I will test it later: https://github.com/leosingleton/webpack-glsl-minify

I just tested it. Minifying with the simple function above reduced the file to 84.16% using the webpack-glsl-minify reduced the file to 43.8%.

The command line I placed before the build now this: https://github.com/matthijsgroen/geppetto-player/blob/main/bin/minifyShader.ts

It would be awesome if parcel could do that out of the box. Also the directives in the shader like '@nomangle' are really nice.

**Comment by matthijsgroen** [comment]
@mischnic  Would it be an option to replace the glslify with the webpack minify version? it has comparable features, but also does the minifaction better, and does not have this `#define GLSLIFY 1` tax. All the webpack specific elements of the https://github.com/leosingleton/webpack-glsl-minify are dev-dependencies, so they are not a 'tax' when using this lib.
