### ISSUE TITLE
Parcel2 v. Webpack - parcel bundle size is significantly larger

### ISSUE THREAD

**Issue by astegmaier** [parcel-bundler/parcel#4565]
# 🐛 bug report

I've started trying to use Parcel2 in a real-life situation, and I'm noticed that the parcel bundle size (1.1MB) is significantly larger than webpack's (666 KiB) for the same app. (It's also significantly slower - see #4566).

Like all real-life situations, it's complicated, so I tried to create a simplified repro environment in the `fluentui-button-babel` branch of [this repo](https://github.com/astegmaier/parcel-webpack-comparer/tree/fluentui-button-babel). It's a simple react app with a single `Button` component from the [`@fluentui/react-northstar`](https://fluentsite.z22.web.core.windows.net/) library. This library is alpha-quality, and there's [known issues](https://github.com/microsoft/fluentui/issues/12953) about bundle size that the team is trying to address. However, webpack still does a significantly better job than parcel right now. The main driver seems to be that [this optimization](https://medium.com/@marijanajdova/fluentui-react-how-we-cut-more-than-30-of-components-bundle-size-by-creating-icons-package-474019d3123) that the library authors made is picked up by webpack but not by parcel.

## 🎛 Configuration (.babelrc, package.json, cli command)

***Webpack*** (full config [here](https://github.com/astegmaier/parcel-webpack-comparer/blob/fluentui-button-babel/webpack.config.js)):
- Using `babel-loader` with this config:
```
presets: [
   "@babel/preset-env",
   "@babel/preset-react",
   "@babel/preset-typescript",
]
```
- `production` flag set to `true`, which enables minification through [`TerserWebpackPlugin`](https://webpack.js.org/plugins/terser-webpack-plugin/) and scope-hoisting/tree-shaking through [`ModuleConcatinationPlugin`](https://webpack.js.org/plugins/module-concatenation-plugin/), among other optimizations.

***Parcel configuration***:

- No `.parcelrc` file, which means that the default babel transformer is being used.
- No custom babel configuration.
- Ran `parcel build src/index.html`

***src/index.html***:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Sample App</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
    <script src="./index.tsx"></script>
  </body>
</html>
```

***src/index.tsx***:
```typescript
import React from "react";
import ReactDOM from "react-dom";
import App from "./components/App";

ReactDOM.render(<App />, document.getElementById("root"));
```

***src/components/App.ts***:
```typescript
import React from "react";
import { Provider, themes, Button } from "@fluentui/react-northstar";

const App = () => (
  <Provider theme={themes.teams}>
    <Button content="Hello from FluentUI" />
  </Provider>
);

export default App;
```

## 🤔 Expected Behavior

Parcel and webpack build size should be roughly the same (or maybe Parcel should be better 😄).

## 😯 Current Behavior

Here's the bundle size comparison:
| Scenario                                                                                      | Bundle Size |
| --------------------------------------------------------------------------------------------- | ----------- |
| Build with parcel (default babel config with scope-hoisting and minification)                 | 1.11 MB     |
| Build with webpack (`babel-loader` with scope-hoisting and minification)                      | 660 KiB     |
| Build with webpack (`ts-loader` with `module: es6` with scope-hoisting and minification)      | 660 KiB     |
| Build with webpack (`ts-loader` with `module: commonjs` with scope-hoisting and minification) | 1.21 MB    |

## 💁 Possible Solution

By using `source-map-explorer` and [a custom node script](https://github.com/astegmaier/parcel-webpack-comparer/blob/fluentui-button-babel/scripts/analyze.ts), I generated a visualization of the stuff that is in the parcel bundle, but not the webpack bundle:

![image](https://user-images.githubusercontent.com/1000369/81002057-a6f94480-8e16-11ea-9923-31c487da1714.png)

You can see that the main driver of the increased size are icons from the `@fluentui/react-icons-northstar`. The fluentui team recently made [an optimization](https://medium.com/@marijanajdova/fluentui-react-how-we-cut-more-than-30-of-components-bundle-size-by-creating-icons-package-474019d3123) to allow webpack to tree-shake these icons, and it seems that it works with webpack, but not with parcel.

I'm not sure why this is happening - most likely something at the scope-hoisting phase that doesn't like the way this library was written. Even if there's something the library authors could do to improve this, it seems like a good goal to do our best to make sure that libraries that are optimized for webpack remain optimized with parcel.

## 🔦 Context

Trying to build a real-world app that uses [`@fluentui/react-northstar`](https://fluentsite.z22.web.core.windows.net/) and parcel2.

## 💻 Code Sample

See the `fluentui-button-babel` branch of [this repo](https://github.com/astegmaier/parcel-webpack-comparer/tree/fluentui-button-babel).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-nightly.248
| Node             | 12.16.3
| Yarn         | 1.22.4
| Operating System | OSX 10.15.4

**Comment by mischnic** [comment]
One reason that this library is rather hard to tree shake is that the module exports are assigned to and used inside the declaration, and the non-pure function call in the exports (which makes it even theoretically impossible to shake):
```js
function Box() {
	console.log(Box.displayName);
	return "This is a Box!";
}

Box.displayName = "Box";

export default withSafeTypeForAs(Box);
```

(This `withSafeTypeForAs` is a noop and is only a workaround to make tsc happy. They really should remove that.)

This means the either deferring mechanism needs to handle this:
```js
export { default as Button } from "./Button";
export * from "./Button";
export { default as Box } from "./Box";
export * from "./Box";
```
However, the `export * from` prevents that (at the moment).

And the wildcard export also prevents Parcel from excluding the asset in the packager (because it determined that `Box` isn't actually used).

----

We need to rework the (re)export wildcard handling.

**Comment by astegmaier** [comment]
Thanks for taking a look! I think you're right to focus on re-export handling. Here's two more data points I found that might be helpful:

1. If you change the way you import from `@fluentui/react-northstar` to this...
       
       import Box from "@fluentui/react-northstar/dist/es/components/Box/Box";
       import Provider from "@fluentui/react-northstar/dist/es/components/Provider/Provider";
       import teamsTheme from "@fluentui/react-northstar/dist/es/themes/teams";

   ...the package size shrinks to 631KiB (compared to 622 KiB for Webpack). That tells me that the main problem relates to way parcel tree-shakes the re-exporting that's happening in [`@fluentui/react-northstar/src/index.ts`](https://github.com/microsoft/fluentui/blob/master/packages/fluentui/react-northstar/src/index.ts) and child `index` files.

2. Even if you leave the imports as-is (i.e. `import { Provider, themes, Box } from "@fluentui/react-northstar"`), if you comment out [line 301 from `@fluentui/react-northstar/src/index.ts`](https://github.com/microsoft/fluentui/blob/96be539b49067b37f51f13a7ba8818226daefde9/packages/fluentui/react-northstar/src/index.ts#L301)...

        //export * from '@fluentui/react-icons-northstar';

   ...the bundle size shrinks to 777KiB (compared to 660 KiB in webpack). So most (but not all) of the size increase in Parcel is due to us not tree-shaking that statement as successfully as webpack.

**Comment by astegmaier** [comment]
I also wanted to clarify that there are at least two things going wrong in this scenario:

1. We're not tree-shaking `@fluentui/react-northstar` components - i.e. including a single component in your app results in many (most?) other components in the package getting included too. [The library authors are working on this right now](https://github.com/microsoft/fluentui/issues/12953#issuecomment-623578322), but I don't think we should focus on it for now because it affects webpack too, and it's probably an issue with the library.
2. In parcel, including a single component in your app ends up including all icons from `@fluentui/react-icons-northstar` too. This doesn't affect webpack - somehow it's able to tree-shake the icons. For the goal of "keeping libraries optimized for webpack also optimized for parcel", I think we should focus here.

**Comment by astegmaier** [comment]
I tested some of the @mischnic's hypotheses about what is producing issue 2, and came up with simplified repro. You can see it in [the `reexport-with-wrappers` branch of this repo](https://github.com/astegmaier/parcel-webpack-comparer/tree/reexport-with-wrappers).

I created a fake npm package (`src/node_modules/fake-package`) with 3 characteristics. In my tests, it appears that all three are necessary in order to see the problem:

1. An index file that re-exports everything another file:

   **src/node_modules/fake-package/index.js**

   ```js
   export * from "./messages";
   ```

2. The file re-exported by `index.js` contains statement that re-export the default exports of some other files:

   **src/node_modules/fake-package/messages.js**

   ```js
   export { default as message1 } from "./message1";
   export { default as message2 } from "./message2";
   ```

3. The default exports are the things returned by executing a function:

   **src/node_modules/fake-package/message1.js**

   ```js
   const getMessage1 = () => "Hello World!";
   export default getMessage1();
   ```

   **src/node_modules/fake-package/message2.js**

   ```js
   const getMessage2 = () => "Goodbye World!";
   export default getMessage2();
   ```

Then, in the main app, we import an use only one of the exports (`message1`):

**src/index.ts**

```ts
import { message1 } from "fake-package";

ready(() => {
  const root = document.getElementById("root");
  if (root) {
    root.textContent = message1;
  }
});

function ready(fn: () => void) {
  if (document.readyState != "loading") {
    fn();
  } else {
    document.addEventListener("DOMContentLoaded", fn);
  }
}
```

When the bundle is built by webpack with tree-shaking, but without minification (`yarn build:webpack:raw`), you can see that the output was successfully tree-shaked - `message2` / "Goodbye World!" is not present.

When the same bundle is built by parcel2 (`parcel build src/index.ts --noMinify`), `message2` / "Goodbye World!" is still in the bundle even though it is unused by the app.

Here is the bundle out put from parcel:

```js
(function () {
  // ASSET: /Users/Andrew/Projects/parcel-webpack-comparer/src/node_modules/fake-package/messages.js
  // ASSET: /Users/Andrew/Projects/parcel-webpack-comparer/src/node_modules/fake-package/message1.js
  const $ddbb96709a4990d332eedf0727c5879$var$getMessage1 = () => "Hello World!";

  var $ddbb96709a4990d332eedf0727c5879$export$default = $ddbb96709a4990d332eedf0727c5879$var$getMessage1();

  const $d3a229d82d83fefab2a3266a3adfcbac$var$getMessage2 = () =>
    "Goodbye World!";

  var $d3a229d82d83fefab2a3266a3adfcbac$export$default = $d3a229d82d83fefab2a3266a3adfcbac$var$getMessage2();
  $b04660a404e967a338647ceb28cef6e$var$ready(function () {
    var root = document.getElementById("root");

    if (root) {
      root.textContent = $ddbb96709a4990d332eedf0727c5879$export$default;
    }
  });

  function $b04660a404e967a338647ceb28cef6e$var$ready(fn) {
    if (document.readyState != "loading") {
      fn();
    } else {
      document.addEventListener("DOMContentLoaded", fn);
    }
  }
})();
//# sourceMappingURL=parcel-webpack-comparer.5ad8aacb.js.map
```

**Comment by astegmaier** [comment]
I confirmed that it is possible to fix the problem by adding `/*#__PURE__*/` annotations to the default exports, like this:

**src/node_modules/fake-package/message1.js**

   ```js
   import { wrapper } from "./wrapper";
   const message1 = "Hello World!";
   export default /*#__PURE__*/ wrapper(message1);
   ```

   **src/node_modules/fake-package/message2.js**

   ```js
   import { wrapper } from "./wrapper";
   const message2 = "Goodbye World!";
   export default /*#__PURE__*/ wrapper(message2);
   ```
Although a conscientious library maintainer might take the time to test and do this, it seems more likely that many won't (e.g. `@fluentui/react-northstar` [was only testing with webpack](https://github.com/microsoft/fluentui/issues/12953#issuecomment-623968360) which is hard to criticize at the moment, given [webpack's current popularity](https://2019.stateofjs.com/other-tools/build_tools)). I suspect consumers of libraries will have a better experience if we try to emulate webpack behavior here.

**Comment by kzc** [comment]
The pure annotation on the exported function call should not be required. The module in question specifies [`"sideEffects": false`](https://github.com/microsoft/fluentui/blob/a5b44ed833a4614d1333fa161ffd8fd467d33446/packages/fluentui/react-northstar/package.json#L84). parcel@next does not appear to respect this hint as rollup and webpack do.

Using the fake-package in the unannotated [example above](https://github.com/parcel-bundler/parcel/issues/4565#issuecomment-624423588) with the entry point:
```
$ cat main2.js 
import {message1, message2} from "fake-package";
console.log(message1);
```
compare:
```
$ echo '{}' > node_modules/fake-package/package.json 
$ rollup main2.js -p node-resolve --silent | node
I just wrapped a string:  Hello World!
I just wrapped a string:  Goodbye World!
Hello World!
```
to:
```
$ echo '{ "sideEffects": false }' > node_modules/fake-package/package.json
$ rollup main2.js -p node-resolve --silent | node
I just wrapped a string:  Hello World!
Hello World!
```

**Comment by mischnic** [comment]
> The pure annotation on the exported function call should not be required.

Yes. I really meant: Parcel failed to optimize this and the call doesn't make it easier for Terser either

**Comment by kzc** [comment]
Rollup handles this `sideEffects`-free scenario itself, but you might investigate whether webpack emits pure annotations for exported calls to the minifier in a production build.

**Comment by mischnic** [comment]
> Rollup handles this sideEffects-free scenario itself

In general, Parcel handles it as well (https://github.com/parcel-bundler/parcel/issues/4565#issuecomment-624423588), it's just that we currently bailout with wildcard exports.
So with `export * from "./messages";` it doesn't get removed, but `export {message1, message2 from "./messages";` does work as expected.

(Thank you for magically appearing in minification-related issues BTW)

**Comment by kzc** [comment]
Sorry for the noise about this known issue. I saw the "theoretically impossible to shake" comment and didn't realize you already had a strategy to deal with it.

> (Thank you for magically appearing in minification-related issues BTW)

:-)
I make the rounds at every bundler project occasionally to see what's state of the art.
Side note: esbuild has made some real progress lately. It'll be interesting to watch.

**Comment by mischnic** [comment]
> theoretically impossible to shake 

I mean AST-level shaking, not bundler level (`sideEffects`) shaking 😄 

> Side note: esbuild has made some real progress lately. It'll be interesting to watch.

Indeed, their performance is very impressive

**Comment by mischnic** [comment]
Before I forget again: this is part of the problem:

https://github.com/parcel-bundler/parcel/blob/0bdd83e24445b2b7f33fa269b8e94e6fc305e638/packages/core/integration-tests/test/scope-hoisting.js#L746-L747

**Comment by mischnic** [comment]
(I just found out that `@material-ui/core` suffers from exactly the same problem with the `export * `)

**Comment by mischnic** [comment]
I have implemented the fix and the bundle size is 632kb compared to Webpack's 635kb, will open a PR after more testing.

**Comment by astegmaier** [comment]
FYI for anyone re-visiting this issue - recent updates to `parcel` and `@fluentui/react-northstar` combined have made a huge difference in bundle size. New results are:
- parcel: 544 KB
- webpack: 496 KB

...which is much more reasonable (although could be better - part of the problem is that the fluentui theme imports definitions for every possible component, even if you're just using one). See the `fluentui-button-babel` branch of [this repo](https://github.com/astegmaier/parcel-webpack-comparer/tree/fluentui-button-babel) to try for yourself.

**Comment by mischnic** [comment]
Hopefully soon, this will go down to 500kb and also be a lot faster to build 😉
