### ISSUE TITLE
how to set extension plugins, like webpack

### ISSUE THREAD

**Issue by loqhcn** [parcel-bundler/parcel#4572]
**i need use it to develop a jquery plugin, but , jquery is extension,**

**Comment by mischnic** [comment]
Please provide more details

**Comment by loqhcn** [comment]
就是我要开发一个jquery插件,  jquery是从外部加载的, 这应该如何实现, 就像在webpack里有个extensions的配置

**Comment by mischnic** [comment]
I still don't understand, I don't know how jQuery plugins work or what you mean by "loaded from the outside"

**Comment by mischnic** [comment]
Closing due to lack of response
