### ISSUE TITLE
TypeError: Note is undefined

### ISSUE THREAD

**Issue by oxk4r01** [parcel-bundler/parcel#4573]
I'm triying to start using tonal.js in VisualStudioCode with Nodejs and Parcel.js as bundler. 
Here is my file structure and the package.json:
![image](https://user-images.githubusercontent.com/1032224/81160858-eba5ec80-8f8a-11ea-8148-ef5c37e56669.png)

But with a simple console.log() for testing, I'm getting this error:
![image](https://user-images.githubusercontent.com/1032224/81161195-7be43180-8f8b-11ea-8143-0c42be853cce.png)

**Comment by mischnic** [comment]
I'm afraid that `@tonaljs/tonal`'s `browser` entry point specified in `package.json` is not compatible with bundlers because it only adds a (somewhat) global variable `Tonal`.

The `browser` entry point should be a CommonJS or ESM module.
