### ISSUE TITLE
Baked in support for scoped css?

### ISSUE THREAD

**Issue by scottmas** [parcel-bundler/parcel#458]
🙋 Feature request
### 🤔 Expected Behavior

There needs to be a way to have scoped css out of the box. 

### 😯 Current Behavior

Currently there is only spotty support for scoped css using postcss. I tried to get it working in a half hour and it failed. Back to the same old Webpack configuration morass. Please no...

### 💁 Possible Solution

Lots of users are going to want to have global css. It's okay. And it's not an unreasonable default behavior. However, a lot of other users like me are going to want scoped css. 

The problem with scoped css however is that there are a million different implementations of it depending on your framework and build chain. 

One potential solution would be to be have a flag that allows css to be imported as a string into javascript. This is a generic enough solution that devs will be able to create a scoped css solution of their choice, stitching together libraries etc. Maybe eventually a standard scoped css approach would naturally emerge for the various frameworks and build chains, and these could be baked into parcel bundler. 

I'd be totally down for an easier solution but this is the best thing that comes to mind given the fragmented nature of scoped css. 

If you think there's a good enough solution for scoped css using postcss configuration, I'd be all ears. I have yet to see a working example though.

**Comment by devongovett** [comment]
You can do this with CSS modules. Just add a `.postcssrc` with the following:

```json
{
  "modules": true
}
```
