### ISSUE TITLE
How do you minify and process your images with Parcel?

### ISSUE THREAD

**Issue by sergiojunene** [parcel-bundler/parcel#4585]
Is there any way to process our images or media files with this excellent bundler? I'm using right now `imagemin` and its plugin but I don't know if I'm doing it right. I've this warning on my terminal. 

![screenshot 2020-05-08 a las 21 47 15](https://user-images.githubusercontent.com/22520811/81443436-ae518280-9175-11ea-8110-4275bb0074bf.jpg)

**Comment by mischnic** [comment]
You mean `parcel-plugin-imagemin`? Are you sure that warning is caused by that plugin?
@DeMoorJasper is the author

**Comment by DeMoorJasper** [comment]
I doubt this issue is caused by the parcel-plugin-imagemin plugin.

This error occurs when you try to use `readFileSync` with anything that cannot be statically analyzed, meaning using anything that isn't constant like a variable in the filepath.

**Comment by sergiojunene** [comment]
Yes, is exactly that @DeMoorJasper but this warning is caused by imagemin on async await anonymous function. But I'd like how can I work with images using Parcel?

**Comment by sergiojunene** [comment]
I didn't used `parcel-plugin-imagemin` but just only `imagemin` with its plugins

**Comment by DeMoorJasper** [comment]
@sergiojunene I guess you could share some of your code so we can reproduce this or give some guidance. `how can I work with images using Parcel` is pretty much out of the box, just require an image and it'll return a url, using the imagemin plugin it would minify it...

**Comment by sergiojunene** [comment]
Yeah, I know, but how do I configure on `package.json` my scripts, the entrypoint on parcel must be a file that not an image. I don't have a code yet, so I want to know how it's done.

**Comment by DeMoorJasper** [comment]
I really don't see how this is related to parcel in any way. You're asking us how you should setup your image pipeline?

I really don't understand what you're asking here. If you want to run a node script to optimize images ahead of time just run it using node... If you want parcel to do it, use a plugin.

**Comment by sergiojunene** [comment]
Yes, which is the code for images pipeline

**Comment by mischnic** [comment]
> Yes, which is the code for images pipeline

The question is: what do you want to achieve? 
- Get the URL to an image from JS? `import foo from "./logo.png"; console.log(foo);`
- Include a image in HTML? `<img src="logo.png">`

The warning you posted in the beginning is just that, a warning. Usually it means that you didn't actually mean to bundle that module because it won't work as expected in the browser.

**Comment by sergiojunene** [comment]
Not, I want process my images, from `src/images` for example, to `dist/images` and compress an minify all these images. As simple as that. With Gulp and Webpack this is really awesome but con Parcel I don't know do it.

**Comment by mischnic** [comment]
An example for minifying images:

index.html:
```html
<img src="./test.jpg" />
```
package.json
```json
{
  "dependencies": {
    "parcel-bundler": "^1.12.4",
    "parcel-plugin-imagemin": "^4.0.1"
  }
}
```

The compression itself can be configured via https://github.com/DeMoorJasper/parcel-plugin-imagemin#configuration.

**Comment by sergiojunene** [comment]
Ok, thanks a lot of, I'll check this configuration.
