### ISSUE TITLE
HMR on Parcel@next React app not preserving state

### ISSUE THREAD

**Issue by zanona** [parcel-bundler/parcel#4586]
# 🐛 bug report

### package.json
```json
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "parcel": "^2.0.0-alpha.3.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "typescript": "^3.8.3"
  }
}
```
### cli
```sh
parcel index.html
```

## 🤔 Expected Behavior

When saving `index.tsx` state of `foo` should be preserved

## 😯 Current Behavior

When saving `index.tsx` state of `foo` being reset to `0`

## 🔦 Context

I am not sure if preserving the state of a React component is possible, but I read through other issues and [saw a demo somewhere](https://user-images.githubusercontent.com/4643658/64480262-aa272c80-d1c4-11e9-8299-f1f04a915505.gif), getting the impression this is actually supported? I am looking on having file changes keeping the current state of a module upon saving. For example, once a modal is open through a state change, I can then update the text inside that modal without having to click a button to open it every time?

### index.html
```html
<!doctype html>
<head>
  <meta charset=utf-8>
  <title>Title</title>
  <script defer src='./index.tsx'></script>
</head>
<body>
  <main>!</main>
</body>
```

### index.tsx
```tsx
import React from 'react';
import {useState} from 'react';
import {render} from 'react-dom';

function Main() {
	const [foo,setFoo] = useState(0);
	return (
		<div onClick={() => setFoo(foo+1)}>
			Hello World {foo}
		</div>
	);
}

module.hot.accept();

render(<Main/>, document.querySelector('main'));
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | 14.0.0
| npm/Yarn         | 1.22.4
| Operating System | linux

**Comment by mischnic** [comment]
This is one of the limitations of React Fast Refresh: changes in the file that calls `ReactDOM.render()` will reset all of the state.

The WIP docs list some more: https://parcel2-docs.now.sh/recipes/react/#modifying-the-asset-that-calls-render-will-reset-all-state%3A

**Comment by zanona** [comment]
Thanks so much for the link! It was really helpful.
