### ISSUE TITLE
Testing JavaScript with Parcel

### ISSUE THREAD

**Issue by sjoerdvermeijden** [parcel-bundler/parcel#4589]
# 🙋 feature request

I'm not sure if this feature is available at the moment, but is it possible to add a JavaScript testing framework like Jest or Mocha?

## 🤔 Expected Behavior

I would like to be able to easily add this in one line like SCSS or Typescript

## 😯 Current Behavior

Not sure if this is available or not

## 💁 Possible Solution

Not sure tbh

## 🔦 Context

I would like to play around with a testing framework and Parcel seems like the perfect tool to learn a testing framework

A way to add this in one simple line

**Comment by mischnic** [comment]
I'm still not quite sure what you mean. Having a testing framework built into Parcel? That is outside of our its scope.

**Comment by sjoerdvermeijden** [comment]
So everything that is under asset types in the Parcel documentation is build in to Parcel?

**Comment by mischnic** [comment]
Yes, these file types are transpiled/processed.
