### ISSUE TITLE
v2 es output problem with html as entry file

### ISSUE THREAD

**Issue by GrosSacASac** [parcel-bundler/parcel#4594]
# 🐛 bug report
I tried 
It seems that https://github.com/parcel-bundler/parcel/issues/1401 is still an issue even with "outputFormat": "esmodule"

parcel works fine
parcel build is problematic

## 🤔 Expected Behavior

No error when opening the result in web page in a browser

## 😯 Current Behavior

Missing variable error in the browser console

## 🔦 Context

I am trying to use parcel in a simple way (raw css html js) ...

## 💻 Code Sample

If anyone can help here is the repo https://github.com/GrosSacASac/create-dom99-app/tree/try-parcel-v2

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel          |  2.0.0-alpha.3.2
| Node            |  14.1.0
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
Please provide a smaller example.

**Comment by GrosSacASac** [comment]
How small, it is pretty small already look at the source folder  there are like 5 files

**Comment by mischnic** [comment]
I also didn't know which script to run because the entry in `parcel build source/final-home.html` doesn't actually exist

**Comment by GrosSacASac** [comment]
npm run inline-html
then
npm run bundle-js
for parcel
it is in the readme

**Comment by mischnic** [comment]
Interesting, this is causing this:
```js
export {x};
const x = 2;
```
If you need a workaround:
```js
const x = 2;
export {x};
```

**Comment by GrosSacASac** [comment]
It is valid code

**Comment by GrosSacASac** [comment]
Does the Linked PR fix it ?

**Comment by mischnic** [comment]
Yes, will be fixed in the next nightly/alpha.
