### ISSUE TITLE
parcel stop watching replaced file

### ISSUE THREAD

**Issue by yukulele** [parcel-bundler/parcel#4598]
# 🐛 bug report

if i replace a file instead of edit it, parcel stop to watch it

## 🤔 Expected Behavior

parcel shoud continue watch it

## 😯 Current Behavior

parcel stop watch it

## 💁 Possible Solution

watch parent directory?

## 💻 Code Sample

my script contain
```js
import data from './data.txt';
```

if i execute in terminal 
```shell
touch data.txt
```
parcel reload but if i execute 
```shell
touch temp.txt
mv temp.txt data.txt
```
parcel reload once and stop watching

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.4
| Node             |  14.2.0
| npm/Yarn         |  6.14.4
| Operating System | ubuntu 18.04

**Comment by mischnic** [comment]
This is a known issue (https://parceljs.org/hmr.html#safe-write) and should work correctly already with Parcel 2.
