### ISSUE TITLE
Getting Started doesnt work, Maximum call stack size exceeded

### ISSUE THREAD

**Issue by StarpTech** [parcel-bundler/parcel#46]
Following Getting Started https://parceljs.org/getting_started.html

Result:
```
Server running at http://localhost:1234
⏳  Building index.html...
(node:11328) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): RangeError: Maximum call stack size exceeded
```
Node.js: 8.6.0

BTW: Highly recommend https://github.com/mcollina/make-promises-safe

**Comment by thejameskyle** [comment]
I'm assuming you're on Windows, please subscribe to: #11
