### ISSUE TITLE
Request to add support for purescript language

### ISSUE THREAD

**Issue by lsby** [parcel-bundler/parcel#4602]
# 🙋 Request to add support for purescript language

Can someone add support for pure scripting languages?
Its website: https://www.purescript.org/

## 🤔 Expected Behavior

There is a package called parcel-plugin-pure or something similar published on npm.
It can recognize the suffix ".purs" and parse it.

## 😯 Current Behavior

I didn't find such a library, either on npm or github.

## 💁 Possible Solution

In terms of compilation, we can use official tools to compile, which can be directly compiled into js. However, using it with other languages ​​still requires a lot of work.

## 🔦 Context

haskell is a great functional programming language.
purescript inherits part of its syntax and can be compiled into js.
Functional programming has many advantages.
I hope the parcel can support the purescript language.
After all, official tools can be used directly for compilation and conversion.
All we have to do is make it work with other languages. (For example, processing file references).

## 💻 Examples

```JavaScript
// index.js
import f from './a.purs'
console.log(f.greet('World'))
```

```purescript
# a.purs
import Prelude
import Effect.Console (log)

greet :: String -> String
greet name = "Hello, " <> name <> "!"
```

```shell
parcel build index.js
node dist/index.js
# Hello, World!
```

**Comment by Mateiadrielrafael** [comment]
+1

**Comment by devongovett** [comment]
Going to close this. I don't have the bandwidth to implement and maintain this. It would be great as a third party plugin if someone wants to build it!
