### ISSUE TITLE
Feature Parity: webpack-dev-server's writeToDisk option in parcel serve.

### ISSUE THREAD

**Issue by mekhami** [parcel-bundler/parcel#4606]
# 🙋 feature request

Enable parcel to write output files to disk as part of the dev server.

## 🤔 Expected Behavior

The ability to have the dev server[ write the files to disk](https://webpack.js.org/configuration/dev-server/#devserverwritetodisk-) (as well as serving them from memory) enables different workflows (namely https://pascalw.me/blog/2020/04/19/webpack-django.html which is a very simple and powerful configuration with django). Having this option would make parcel fit really well with different development setups.

What would the scope of work be to enable something like this?

## 😯 Current Behavior

I don't believe parcel currently supports this feature.

**Comment by mischnic** [comment]
`parcel serve` already writes to disk (the `dist` folder).
`parcel watch` only writes to disk (without a dev-server but with an HMR server).

Which version of Parcel are you referring to?

> serving them from memory

Parcel's dev server doesn't use an in-memory filesystem.

**Comment by mekhami** [comment]
I'm going to attempt this again with Parcel 1 (I don't remember what version I was testing it on.) This may have been a PEBKAC issue.

**Comment by mekhami** [comment]
@mischnic What I see now is that if I point parcel to an index.html entry point that has a script tag pointing to a javascript file, the output in the dist folder includes the index.html file but not the compiled javascript file.

What I'm looking for is that all of the top level files that get compiled like that get written to disk as well (with the option to not change/hash their file names) so that a different static file system can do the hashing.

Does what I'm saying make sense? The article linked above outlines the reasons and method for doing it in webpack.

**Comment by mekhami** [comment]
I can point parcel at the main.js entrypoint instead and that produces main.js, main.css. So maybe I just need to point directly to the javascript asset instead of the index.html file.

**Comment by mischnic** [comment]
(Well, with Parcel 2, it currently outputs to `.parcel-cache/dist`, but we are probably going to change that)

**Comment by mekhami** [comment]
Thanks. Sorry for the unnecessary issue :) (Is there a better channel to ask these sorts of questions and avoid cluttering the github issues system?)

**Comment by mischnic** [comment]
For now: https://spectrum.chat/parcel
