### ISSUE TITLE
Ability to do minimum build so I don't have to debug via source maps

### ISSUE THREAD

**Issue by chisholmd** [parcel-bundler/parcel#4608]
# 🙋 feature request
Debugging via source maps sucks hard.  Is there an option in Parcel to do a minimum bundle so that I don't have to use source maps?

I want a dev bundle instead of a prod bundle...does that make sense?

I want what Snowpack promises

**Comment by mischnic** [comment]
> I want a dev bundle instead of a prod bundle...does that make sense?

Please provide more details what you want. Do you mean transpiling files without bundling them together? 
After all, Parcel is (in its current state) a bundler...

**Comment by chisholmd** [comment]
To put it as simply as possible, I want to be able to debug without source maps.

**Comment by DeMoorJasper** [comment]
@chisholmd run with `--no-source-maps`?

**Comment by chisholmd** [comment]
Thanks @DeMoorJasper but, that simply removes the source maps, it does not remove the necessity of them to debug the code.  Eg. Its all still mashed together and minified and not readable.

I think I am barking up the wrong tree, I think what I want is to get Snowpack working.  What they promise is what I want.  

I am not sure how people work like this.

**Comment by mischnic** [comment]
`--no-minify`?

**Comment by chisholmd** [comment]
Yea!  I thought it was the source maps messing up the debugger, but looks like it was the minify.  

Thx
