### ISSUE TITLE
Importing CSS has two copies in javascript and css

### ISSUE THREAD

**Issue by bgold0** [parcel-bundler/parcel#4613]
# 🐛 bug report

I import css in my app.js file like so:

    import './main.css'

For some reason, it's being included in my javascript bundle but it is also being added to my css file. How do I get it out of my javascript file?

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
	"presets": ["@babel/preset-env", "@babel/preset-react"],
	"plugins": [
		"@babel/plugin-proposal-class-properties",
		[
			"import",
			{
				"libraryName": "antd"
			},
			"antd"
		]
	]
}

```

## 🤔 Expected Behavior
It should only be included in my css bundle

## 😯 Current Behavior

It is being included in my javascript bundle AND my css bundle. Same exact copy.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| npm/Yarn         | npm

**Comment by mischnic** [comment]
> How do I get it out of my javascript file?

What is *it*?

**Comment by bgold0** [comment]
The contents of 'main.css' @mischnic

**Comment by bgold0** [comment]
> > How do I get it out of my javascript file?
> 
> What is _it_?

The contents of 'main.css' @mischnic
