### ISSUE TITLE
Output Directory

### ISSUE THREAD

**Issue by LandonSchropp** [parcel-bundler/parcel#4633]
# 🙋 feature request

In Parcel 1, I have an `--out-dir` option that lets me specify the build directory. That setting doesn't seem to exist in Parcel 2's `serve` command.

## 🤔 Expected Behavior

Just like v1, I'd expect to be able to specify `--out-dir` along with a directory.

## 😯 Current Behavior

This option seems to be missing. It doesn't appear in `parcel serve --help`, and if I try to include it parcel complains that it's an unknown option.

## 💁 Possible Solution

Add the flag. (Apologies if there's already an issue for this. I couldn't find one when searching.)

## 🔦 Context

I was trying to output my files to a `build` directory.

## 💻 Examples

```
parcel serve source/index.html --out-dir build
```

**Comment by mischnic** [comment]
It is already implemented as `--dist-dir` in the nightly `yarn add parcel@nightly` or in the next beta (very soon).

**Comment by LandonSchropp** [comment]
Thanks!
