### ISSUE TITLE
Import html files that aren't linked from entry file

### ISSUE THREAD

**Issue by ajayns** [parcel-bundler/parcel#4635]
# 🙋 feature request

Say my entry file is `index.html` and I have other pages such as `page1.html` and `page2.html`. There are no links to these files as the routing is handled using JS: say it has a single link to `/page1.html` and JS changes it to `/page2.html` when required.

In such a case I don't see a method specified in the documentation on how I can make sure Parcel compiles these HTML files too. 

This seems to be a hack that does what I'm trying to achieve: 
```html
<!-- index.html (entry file) -->
...
<div id="imports" style="display: none;">
      <a href="./page1.html"></a>
      <a href="./page2.html"></a>
</div>
```

## 🤔 Expected Behavior

Some straightforward methods to specify files to be imported/compiled.

## 😯 Current Behavior

Have to use the hacky method to specify files to import.

## 💁 Possible Solution

Some form of importing in `index.html` file which specifies which all other pages to include and doesn't show up in the output compiled HTML file (a clean version of the hack I've used).

Alternatively some parcel config to compile all files in a certain folder maybe?

**Comment by mischnic** [comment]
> In such a case I don't see a method specified in the documentation on how I can make sure Parcel compiles these HTML files too.

`parcel build index.html page1.html page2.html` should do that.

**Comment by ajayns** [comment]
I wouldn't want to edit my package.json for each file added especially for a large number of files added. Isn't there any method using the already existing html/js files that helps achieve this?

**Comment by mischnic** [comment]
You can use a glob: `parcel build 'src/**/*.html'`

**Comment by ajayns** [comment]
Thank you, I'll work around that.
