### ISSUE TITLE
ENOENT: no such file or directory rename ... .parcel cache

### ISSUE THREAD

**Issue by bobbwhy** [parcel-bundler/parcel#4645]
# 🐛 bug report

I created a gitlab repo to show this issue in the simplest format possible.
https://gitlab.com/rlamarca/oof

thanks in advance

Trying to build a nano-react-app after creating it throws this error: 
`ENOENT: no such file or directory, rename '.../react/oof/.parcel-cache/84/d7d601396eb0fc48a66da026a4ba5a.blob.28162.1.0' -> '.../react/oof/.parcel-cache/84/d7d601396eb0fc48a66da026a4ba5a.blob'`

* This happened after I upgraded from Mojave to Catalina on Mac
* The project would work prior to the upgrade
* This also happens when i create a completely new project.
* I searched for the solution and it appears this happens in other projects that use parcel.
*  looked through the issues here, but could not find this exact issue

## 🎛 Configuration (.babelrc, package.json, cli command)
* os X catalina
* node 12.14.1
* yarn 1.22.4
* package.json: 
{
  "name": "oof",
  "version": "0.1.0",
  "description": "",
  "scripts": {
    "start": "parcel index.html",
    "build": "parcel build index.html"
  },
  "license": "MIT",
  "dependencies": {
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  },
  "devDependencies": {
    "babel-preset-nano-react-app": "^0.1.0",
    "parcel": "^2.0.0-alpha.3.2"
  },
  "babel": {
    "presets": [
      "nano-react-app"
    ]
  }
}

## 🤔 Expected Behavior

yarn start should build the project: 

## 😯 Current Behavior

I get this error
ENOENT: no such file or directory, rename '.../react/oof/.parcel-cache/84/d7d601396eb0fc48a66da026a4ba5a.blob.28162.1.0' -> '.../react/oof/.parcel-cache/84/d7d601396eb0fc48a66da026a4ba5a.blob'

## 💁 Possible Solution

* I may try to re-install my OS, but hoping to avoid that project.

## 🔦 Context

* I contacted maintainer at nano-react-app, but he could not replicate and suggested i try over here.

## 🌍 Your Environment

* os X catalina
* node 12.14.1
* yarn 1.22.4

**Comment by mischnic** [comment]
Which version are you using? Please try the latest nightly.
There is a recently fixed bug: https://github.com/parcel-bundler/parcel/issues/4614

**Comment by bobbwhy** [comment]
Niklas,

thanks so much for the fast reply.  I will give that a try this evening and
let you know.
Regards,
Robert

**Comment by bobbwhy** [comment]
Works now Niklas,
thanks again!
