### ISSUE TITLE
svg element id attribute was lost

### ISSUE THREAD

**Issue by cnshsliu** [parcel-bundler/parcel#4649]
# 🐛 bug report

I have an inline svg in the index.html, after parcel, the attribute of "id" was removed

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🤔 Expected Behavior

the attribute of inline svg tag should be kept

## 😯 Current Behavior
the part of the inline svg 
```
                            <g id="demo_chat">
                                <g>
                                    <path class="st33" d="M603.4,15.7c1.8-0.7,3.2-1.8,4.3-3c1-1.3,1.6-2.7,1.6-4.2s-0.5-2.9-1.6-4.2c-1-1.3-2.5-2.3-4.3-3
```
after pacel:

`<g><g><path class="st33" d="M603.4 15.7c1.8-.7 3.2-1`

the first <g>'s attribute id="demo_chat" was removed.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | v12.16.2
| npm/Yarn         | npm 6.14.5
| Operating System | MacOS Catalina  10.15.4

**Comment by mischnic** [comment]
Does adding this `.htmlnanorc` file fix it?
```
{ "minifySvg": { "plugins": [{ "cleanupIDs": false }] } }
```

List of options: https://github.com/svg/svgo

**Comment by DCzajkowski** [comment]
It did fix it for me. I think this should be the default though, as it really is an unexpected behavior and causes production builds to break images, whereas development builds are on point.

**Comment by mischnic** [comment]
Merging into #4675
