### ISSUE TITLE
source maps generated despite `sourceMap: false` in target configuration

### ISSUE THREAD

**Issue by rondonjon** [parcel-bundler/parcel#4660]
# 🐛 bug report

According to the [targets section of the README file](https://github.com/parcel-bundler/parcel#packagejsontargets), it should be possible to toggle/configure source map generation for each of the `targets:` in the `package.json` file, but setting `sourceMap: false` has no effect.

## 🎛 Configuration (.babelrc, package.json, cli command)

I have the following target configuration:

```
"targets": {
    "abc": {
      "context": "node",
      "includeNodeModules": true,
      "outputFormat": "commonjs",
      "engines": {
        "node": ">=10.x"
      },
      "sourceMap": false
    }
```

## 🤔 Expected Behavior

Parcel should generate no source maps for this target.

## 😯 Current Behavior

Running `parcel build src/index.ts --target abc` gives me:

```
dist/index.js.map    22.53 KB      6ms
dist/index.js        10.08 KB    1.23s
Done in 2.23s.
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4 |
| Node             | 12.16.3 |
| Yarn         | 1.22.4 |
| Operating System | Linux |

**Comment by mischnic** [comment]
The readme is about Parcel 2 (because the default branch on Github is `v2`).
So:
- either you use `yarn add parcel@next` instead or
- continue with Parcel 1 and run `parcel build src/index.ts --no-source-maps` (https://parceljs.org/cli.html)
