### ISSUE TITLE
Importing entire @material-ui/core creates a bundle with a TypeError using 2.0.0-alpha.3.2

### ISSUE THREAD

**Issue by danr** [parcel-bundler/parcel#4667]
# 🐛 bug report

When importing this library with `* as mui` and then using `mui.Paper` builds a bundle with a TypeError
```typescript
import * as mui from '@material-ui/core'
ReactDOM.render(<mui.Paper>Hello</mui.Paper>, root)
```

Interestingly, it does _not_ happen if the import is changed to: 

```typescript
import {Paper} from '@material-ui/core'`
```

## 🎛 Configuration (.babelrc, package.json, cli command)

There is a repo to reproduce here:
https://github.com/danr/parcel-import-bug

## 🤔 Expected Behavior

The bundle should not raise an exception.

## 😯 Current Behavior

```
Uncaught TypeError: $f is not a function
    at Ny (withStyles.js:6)
    at Paper.js:109
    at main.tsx:10
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2
| Node             | 14.2.0
| npm/Yarn         | yarn 1.22.4
| Operating System | Arch Linux

It also happens with 2.0.0-nightly.275

**Comment by mischnic** [comment]
Somehow the order of assets is wronng: https://github.com/parcel-bundler/parcel/blob/417a8c6cbb2eb7d7ca1d936c1d93a5cef8e91ba4/packages/shared/scope-hoisting/src/concat.js#L115-L156
