### ISSUE TITLE
How to convert less?

### ISSUE THREAD

**Issue by wotanjie** [parcel-bundler/parcel#467]

**Comment by DeMoorJasper** [comment]
Just point parcel to a less entrypoint and it'll build it?
A bit more context and filling in the issue template are very helpfull

**Comment by marsvogel** [comment]
The most basic example would be adding your less file to the `<head>` of your html file and run  `parcel index.html`. This should do the trick.

```html
<!DOCTYPE html>
<html>
<head>
    <title>App</title>
    <!-- Simple as that :) -->
    <link rel="stylesheet" type="text/css" href="app.less">
</head>
<body>
    <img src="example.jpg">
    <script type="text/javascript" src="app.js"></script>
</body>
</html>
```

**Comment by echowant** [comment]
npm install less

**Comment by DeMoorJasper** [comment]
@echowant this is not even necessary in new version, as it automatically installs less if it detects a less file
