### ISSUE TITLE
Minifier improvements inspired by Google's Closure Compiler

### ISSUE THREAD

**Issue by kungfooman** [parcel-bundler/parcel#4676]
I compared Parcel's minified code with Google's Closure Compiler's minified code (minify + scopehoist), and the latter uses some tricks to produce smaller builds.

## 🤔 Expected Behavior

Convert something like this:

```js
throw new TypeError("\"this\" is null or not defined");
```

Into this:

```js
throw TypeError('"this" is null or not defined');
```

And convert something like this:

```js
["Array", "Object", "Function", "Date", "RegExp", "Float32Array"]
```

Into this:

```js
"Array Object Function Date RegExp Float32Array".split(" ")
```

## 😯 Current Behavior

Does not do it.

## 💁 Possible Solution

Transform code via terser

## 🔦 Context

I am looking for a good minifier, and currently Google's Closure Compiler produces smaller minified builds.

**Comment by DeMoorJasper** [comment]
We use terser for code minification. Maybe you can configure it to do that, otherwise it would probably be a feature request for them

**Comment by mischnic** [comment]
> "Array Object Function Date RegExp Float32Array".split(" ")

There is a tradeoff between performance and size here. And I think Terser doesn't do type analysis like Closure Compiler (this transformation can only be done if all array elements are string literals)

With Parcel 2, you could easily swap out the terser optimizer plugin for a Closure Compiler optimizer plugin

**Comment by kzc** [comment]
Eliding the `new` is already done for a few builtin types:
```
$ echo 'throw new Error("abc");' | terser -c unsafe
throw Error("abc");
```
Extending it to other known builtin types would be straightforward.

> I think Terser doesn't do type analysis like Closure Compiler (this transformation can only be done if all array elements are string literals)

This is just static AST analysis - it is easy to determine whether all the children of the array literal are string literals without embedded spaces. One could devise an "unsafe" terser transform (String.prototype.split can be overridden in pathological code) to check all AST_Array elements are of type AST_String. 

> There is a tradeoff between performance and size here.

That's the real concern. It has a runtime cost. You wouldn't want to transform the code to use the split unless it would only run a low number of times in the lifetime of the program. But this transform does have the advantage of having faster JS parse time, similar to the technique where it is faster to have JSON parsing of large literal arrays and objects at program startup.

**Comment by kzc** [comment]
An illustrative micro benchmark...

```
$ cat array-literal-loop.js 
const f = +process.env.USE_SPLIT
    ? () => "Array Object Function Date RegExp Float32Array".split(" ")
    : () => ["Array", "Object", "Function", "Date", "RegExp", "Float32Array"];
for (var count = 0, i = 0; i < 1e7; ++i) {
    if (f() !== f()) count++;
}
console.log(count);
```
```
$ USE_SPLIT=0 /usr/bin/time node-v14.3.0 array-literal-loop.js 
10000000
        0.08 real         0.05 user         0.00 sys

$ USE_SPLIT=1 /usr/bin/time node-v14.3.0 array-literal-loop.js 
10000000
        3.20 real         3.17 user         0.02 sys
```
40X slower.

**Comment by kungfooman** [comment]
Your test lacks the parsing time and if you include that, the difference feels negligible:

```js
var start = performance.now();
for (var i=0; i<10000; i++) {
    eval(`"Array Object Function Date RegExp Float32Array".split(" ")`)
}
var end = performance.now();
console.log("USE_SPLIT=1", end - start, "ms");
```

```js
var start = performance.now();
for (var i=0; i<10000; i++) {
    eval(`["Array", "Object", "Function", "Date", "RegExp", "Float32Array"]`)
}
var end = performance.now();
console.log("USE_SPLIT=0", end - start, "ms");
```

And then you are testing for 10 million iterations... a large minified code base maybe has 100 of those cases. And you also don't measure the network time to download the code.

Randomly tested six times:

```js
USE_SPLIT=0 179.1250000242144 ms
USE_SPLIT=0 188.67499998398125 ms
USE_SPLIT=0 205.905000038445 ms
USE_SPLIT=1 180.21000001952052 ms
USE_SPLIT=1 210.68000001832843 ms
USE_SPLIT=1 206.74500003270805 ms
```

**Comment by mischnic** [comment]
The point I was making is that this might be benefitial in some cases but not for every codebase (as in: it should be opt-in. If Terser would support this, you could configure it in Parcel with a `.terserrc` file).

(Also: be careful with these benchmarks. `eval` might have a cache based on the string contents. In Node, your first example completes in 8ms, while factoring in `i` into the eval argument results in 108ms.)

**Comment by kzc** [comment]
> Your test lacks the parsing time

That's not correct. Parsing time is obviously included in my test case - it also includes process startup time, JIT startup time and executing the JS. There is no other way to explain the 0.08s real total process runtime for USE_SPLIT=0 versus the 3.20s for the USE_SPLIT=1 case.

`eval` as @mischnic pointed out changes everything and completely deoptimizes the USE_SPLIT=0 case by over an order of magnitude.

I wouldn't want to have a minifier perform the spit optimization by default to save a few bytes at the expense of poor runtime performance in the worst case in a hot code path, and be a near wash in the best case - particularly after gzip.

The [majority](https://github.com/terser/terser#terser-fast-minify-mode) of [minification](https://github.com/babel/minify#benchmarks) comes from whitespace elimination and symbol mangling. The only code optimizations of significance are the one that remove sections of unused or debug code.

**Comment by kzc** [comment]
Original micro benchmark adjusted to use `performance.now` where the array literal is accessed 1e7 x 2 times rather than [10,000 times](https://github.com/parcel-bundler/parcel/issues/4676#issuecomment-636466504):

```
$ cat array-of-strings.js 
const performance = require('perf_hooks').performance;
var start = performance.now();
const f = +process.env.USE_SPLIT
    ? () => "Array Object Function Date RegExp Float32Array".split(" ")
    : () => ["Array", "Object", "Function", "Date", "RegExp", "Float32Array"];
for (var count = 0, i = 0; i < 1e7; ++i) {
    if (f() !== f()) count++;
}
var end = performance.now();
console.log(count);
console.log("elapsed:", end - start, "ms");
```
```
$ USE_SPLIT=0 /usr/bin/time node-v12.13.0 array-of-strings.js
10000000
elapsed: 17.734260082244873 ms
        0.06 real         0.05 user         0.00 sys
```
```
$ USE_SPLIT=1 /usr/bin/time node-v12.13.0 array-of-strings.js
10000000
elapsed: 2980.5792959928513 ms
        3.02 real         3.00 user         0.02 sys
```
The relative timing difference is more pronounced with `performance.now`: 2980.579 / 17.734 = 168.1 times.
