### ISSUE TITLE
HMR is not working with WSL 2, WINDOWS 10 2004

### ISSUE THREAD

**Issue by geart891** [parcel-bundler/parcel#4677]
# 🐛 bug report

HMR is not working with parcel and WSL 2. I tried both parcel v1 and v2, results are the same.

![image](https://user-images.githubusercontent.com/27849964/83344548-6e278f00-a332-11ea-9958-32dfb93fa707.png)

## 🎛 Configuration (.babelrc, package.json, cli command)
command: `parcel src/index.html`

I didnt put anything in the babel configs, and I expect it to run with default configurations.

## 🤔 Expected Behavior

Parcel running normally without error and hmr working the same as running without WSL. my WSL version is 2.0

## 😯 Current Behavior

![image](https://user-images.githubusercontent.com/27849964/83344593-12a9d100-a333-11ea-8fe0-d59dbc92eb63.png)
![image](https://user-images.githubusercontent.com/27849964/83344606-484eba00-a333-11ea-9e16-9d298c70ce01.png)

As chrome console shows, hmr is not working. And I run parcel from WSL 2, open the page in windows.

## 💁 Possible Solution

No solution found yet, I have tried open firewall port on windows.

EDIT: I found a temporary fix. Change the `127.0.0.1:1234` to `localhost:1234` seems work, it doesnt show any error. The link shows in parcel terminal is `http://localhost:1234` however when ctrl+ click it resolves to `127.0.0.1:1234`. Is there anyway to change this behaviour?

## 💻 Code Sample

I have tried on the most simple example. One html files with an js file to console.log random texts but this error still exists.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v1|2@lastest
| Node             |14.4
| npm/Yarn         |@lastest
| Operating System |W10@2004 WSL2

**Comment by geart891** [comment]
Updated with temporary fix.

**Comment by bbouabou** [comment]
Same here, I can't map to a custom port in my docker-compose, I had to use the one from parcel. I use the option --port to be able to use the port I want.

**Comment by stloc** [comment]
Possible Solution OK

**Comment by stloc** [comment]
I have the error again. localhost or 127.0.0.1

**Comment by themuniz** [comment]
I have the same error if I use localhost or 127.0.0.1. Sometimes the error doesn't show on the console, but instead ``` parcel serve ``` just hangs. Also on wsl2/Windows 10.
