### ISSUE TITLE
V2 Scope hoisting seems to break renaming

### ISSUE THREAD

**Issue by jfrconley** [parcel-bundler/parcel#4687]
# 🐛 bug report

Enabling scope hoisting seems to break variable renaming resulting in a significantly increased bundle size.

This may be related to #3664, but I have verified that I have @babel/travers at 7.10.1 

## 🎛 Configuration (.babelrc, package.json, cli command)
```bash
parcel build --target lambda --no-source-maps dist/index.js --detailed-report
```
```json
{
  "lambda": "bundle/index.js",
  "targets": {
    "lambda": {
      "context": "node",
      "sourceMap": false,
      "includeNodeModules": {
        "@acuris/aws-es-connection": false,
        "@elastic/elasticsearch": false,
        "sharp": false,
        "aws-sdk": false,
        "jsonata": false,
        "pino-pretty": false,
        "jmespath": false
      }
    }
  }
}
```

## 🤔 Expected Behavior

Enabling scope hoisting should have shortest possible top level variable names, reducing overall bundle size.

## 😯 Current Behavior

While scope hoisting itself seems to be working, top level values all have super long generated names (ex: $b10acc16e6462fee040168c6ed2f0$var$actualClose), significantly increasing bundle size. In my case, the scope hoisted size was double that of simple bundling.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.277
| Node             | 12
| npm/Yarn         | 1.22.4
| Operating System | Ubuntu 20.04

**Comment by mischnic** [comment]
> hile scope hoisting itself seems to be working, top level values all have super long generated names (ex: $b10acc16e6462fee040168c6ed2f0$var$actualClose), significantly increasing bundle size. In my case, the scope hoisted size was double that of simple bundling.

I'm fairly confident that you have an `eval` somewhere in your code, which deopts Terser.

**Comment by jfrconley** [comment]
Just confirmed that there are no calls to eval or use of the Function constructor anywhere in my bundle.

**Comment by mischnic** [comment]
Strange, even if you build with `--no-minify`?

**Comment by jfrconley** [comment]
Yes, just double checked. The minify option seems to only apply to contents of modules, not the bundle

**Comment by mischnic** [comment]
>  The minify option seems to only apply to contents of modules, not the bundle

Parcel 1 ran Terser per file/asset, but Parcel 2 does run it on the concatenated bundle

**Comment by jfrconley** [comment]
Is there a documented list of things that cause terser to bail out? I'm testing this on a very small bundle (13 KB) and can't find anything that seems likely.

**Comment by jfrconley** [comment]
I figured it out. Terser does not mangle top level names by default, but requires the toplevel option to be set. Parcel should probably do this by default when scope hoisting.

https://terser.org/docs/cli-usage#cli-mangle-options

**Comment by mischnic** [comment]
We should:
https://github.com/parcel-bundler/parcel/blob/2668bee153af09e665c30408b1bdafe06e1cc3ac/packages/optimizers/terser/src/TerserOptimizer.js#L31-L33

Your outputformat should be commonjs, right?

**Comment by jfrconley** [comment]
That only applies to compression, not mangling. The issue goes away when I have .terserrc with the following config.

```json
{
	"mangle": {
		"toplevel": true
	}
}
```

**Comment by mischnic** [comment]
👍  Thanks for investigating!

**Comment by fregante** [comment]
It seems that the suggested way to handle this issue is to enable variable name mangling through minification, which makes variables less readable rather than more readable. 

Can Parcel do what Rollup does to generate readable code? My code has been rejected by a store due to “obfuscation”

![DCCF3E01-0D3C-4839-B9BE-043940D5C1FC](https://user-images.githubusercontent.com/1402241/114027917-189d0680-98a2-11eb-95f8-8fce7c4ccc3f.jpeg)

**Comment by mischnic** [comment]
@fregante  That's very unfortunate, can you open a new issue for that? Maybe we can try to shorten the names

**Comment by fregante** [comment]
Thanks! Done
