### ISSUE TITLE
Error in production bundle: Incompatible receiver, Map required

### ISSUE THREAD

**Issue by smeijer** [parcel-bundler/parcel#4692]
# 🐛 bug report
When including `aria-query` in my project, `parcel serve` works fine, but `parcel build` will result in a non-working state. The app will throw 

```
Incompatible receiver, Map required
```

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json:
```json
{
  "scripts": {
    "start": "parcel index.html",
    "build": "parcel build index.html && http-server dist",
  },
  "devDependencies": {
    "http-server": "^0.12.3",
    "parcel-bundler": "^1.12.4"
  },
  "dependencies": {
    "aria-query": "^4.0.2"
  }
}
```

index.html:

```html
<html>
<body>
  <div id="app"></div>
  <script src="./index.js"></script>
</body>
</html>
```

index.js:

```js
import { roles } from 'aria-query';
console.log('roles', roles);
```

## 🤔 Expected Behavior

As the app is running just fine in `serve` mode, (logs a message to console), the app should also run when being build with `parcel build`.

## 😯 Current Behavior

An error is thrown: 

```
internal-state.js:20 Uncaught TypeError: Incompatible receiver, Map required
    at internal-state.js:20
    at new <anonymous> (collection.js:49)
    at Object.parcelRequire.Xyow.@babel/runtime-corejs3/helpers/interopRequireDefault (ariaPropsMap.js:15)
    at f (tabpanelRole.js:25)
    at p (tabpanelRole.js:25)
    at Object.parcelRequire.EvzN.@babel/runtime-corejs3/helpers/interopRequireDefault (index.js:13)
    at f (tabpanelRole.js:25)
    at p (tabpanelRole.js:25)
    at Object.parcelRequire.Focm.aria-query (index.js:1)
    at f (tabpanelRole.js:25)
```

## 💁 Possible Solution

I don't have the solution, but it looks like it has something to do with core-js and Map being poly-filled more than once? But I'm not sure.

## 🔦 Context

I need to include `aria-query` into my client side bundle, but so far I'm unable to doing so, because of the error that is present in the production bundle (but not when running `parcel serve`).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v1.12.4
| Node             | v12.16.1
| npm              | v6.14.0
| Operating System | Ubuntu 19.10

**Comment by mischnic** [comment]
The serve mode output is on the left (working=, build mode on the right (broken):

![Bildschirmfoto 2020-06-04 um 22 40 11](https://user-images.githubusercontent.com/4586894/83808048-5a728480-a6b4-11ea-8eef-337aa78835d3.png)
so when some core-js files import "hidden-keys" they actually get "path". 

This is somehow caused by deduping assets when writing the bundle: https://github.com/parcel-bundler/parcel/blob/948cccd392eecf15ccbd08b91a0de239f6a3abcc/packages/core/parcel-bundler/src/packagers/JSPackager.js#L43

<br>

Ideally, aria-query would also publish a modern build to npm (ESM imports, native Maps, ...)

Works with Parcel 2...

**Comment by smeijer** [comment]
Thanks for the research. I've created a ticket at the `aria-query` repo.

But until Parcel 2 is released as the recommended release (non-alpha), I think it's worth fixing here as well.

As a quick fix, we could make the deduping optional? Although it might be better to figure out how deduping is causing this.

**Comment by jessebeach** [comment]
@smeijer aria-query can't be the only project in the dependency tree using `@babel/plugin-transform-runtime`. Maybe the error shows up for aria-query because it appears alphabetically first?

**Comment by smeijer** [comment]
I haven't verified, but that sounds plausible.

**Comment by sandrina-p** [comment]
The same problem is happening in a project that uses the latest Parcel 1.12.4 and parse 2.17.0. `dev` is fine but the `build` breaks.
Any suggestion?

Project source code: https://github.com/majac91/Travel_journal  - Exact [commit](https://github.com/majac91/Travel_journal/commit/0c02df64cda693be31ddbb1f7afcecb3b9f4eabd)

**Comment by MarkLyck** [comment]
Sorry to bump, but any news on this? same problem: `"parcel-bundler": "1.12.4",`

**Comment by quaos** [comment]
Just run into this in 2022, without `aria-query`.

I'm using `@parcel/babel-plugin-transform-runtime` with `corejs` version: 3 to try to fix `regeneratorRuntime` not defined issue.
