### ISSUE TITLE
V2: JSRuntime should reference child bundle dependencies with a require call when using commonjs

### ISSUE THREAD

**Issue by jfrconley** [parcel-bundler/parcel#4695]
# 🙋 feature request

JSRuntime should reference non-async child bundle dependencies with a require call when using commonjs, instead of falling back to the default url runtime.  This would allow for the bundler to split nodejs applications into multiple bundles.

## 🤔 Expected Behavior

When the bundler generates child bundles for a commonjs application, the JSRuntime should reference them using a require call.

## 😯 Current Behavior

No specific behaviour is in place for handling synchronous child bundles in commonjs so the runtime falls back to a url export.

## 💁 Possible Solution

Include something like this in the JSRuntime
```js
      if (bundle.env.outputFormat === 'commonjs') {
        assets.push({
          filePath: __filename,
          dependency,
          code: `module.exports = require("./" + ${getRelativePathExpr(bundle, mainBundle)})`
        });
        continue;
      }
```

## 🔦 Context

I am creating a custom bundler that allows me to split nodejs bundles at given files. This was fairly simple and generates correct graphs, but the runtime doesn't reference the child bundles correctly

**Comment by mischnic** [comment]
Makes sense

> I am creating a custom bundler that allows me to split nodejs bundles at given files.

Could you share that so that we can add a test case as well when fixing this?

**Comment by jfrconley** [comment]
Sure! https://github.com/jfrconley/parcel-bundler-splitable
All I did was add a package.json, "bundleSplits" (name up for debate) that is an array of files to split the bundle on. All together a less then 10 line change.

**Comment by mischnic** [comment]
In the short term, https://github.com/jfrconley/parcel-runtime-splitable/commit/e8550941939c6d4fc36f2fa50d81da9a106b3a01 could definitely be upstreamed as a bugfix (with a stripped down version of your bundle in the test case).

> what the official configuration method for it would be

> project philosophy

We plan on having these options
https://github.com/parcel-bundler/parcel/blob/e95fbaeac705c170719f771580e502c1f7f5865a/packages/bundlers/default/src/DefaultBundler.js#L15-L19
configureable by the user (probably via some config file), but that's not decided yet.
