### ISSUE TITLE
Build never finishes — gets stuck on random file and freezes

### ISSUE THREAD

**Issue by auchers** [parcel-bundler/parcel#4698]
# 🐛 bug report

Trying to build project ends up lagging on and freezing up — never completes, just leads to very hot and loud computer. Seems similar to some previous closed issues but nothing seems to help so far. 

That said, dev server works as expected and correctly compiles files. 

## 🎛 Configuration (.babelrc, package.json, cli command)

```js 
// tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "es2019"
    ],
    "noImplicitAny": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "sourceMap": true,
    "baseUrl": ".",
    "paths": {
      "~*": [
        "./src/*"
      ]
    }
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

```js
// package.json
{
  "main": "index.js",
  "scripts": {
    "dev": "parcel src/index.html",
    "build": "parcel build src/index.html",
    "prototypes-build": "parcel build src/index.html --log-level 4 --public-url http://[WEBSITE].com/prototypes ",
  },
  "devDependencies": {
    "@types/d3": "^5.7.2",
    "@types/d3-array": "^2.0.0",
    "@types/node": "^14.0.9",
    "@types/topojson-client": "^3.0.0",
    "@typescript-eslint/eslint-plugin": "^3.1.0",
    "@typescript-eslint/parser": "^3.1.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb-base": "^14.1.0",
    "eslint-plugin-import": "^2.20.2",
    "parcel": "^2.0.0-alpha.3.2",
    "parcel-bundler": "^1.12.4",
    "parcel-plugin-clean-dist": "^0.0.6",
    "sass": "^1.26.5",
    "typescript": "^3.9.3"
  },
  "dependencies": {
    "d3": "^5.16.0",
    "d3-array": "^2.4.0",
    "intersection-observer": "^0.10.0",
    "redux": "^4.0.5",
    "reselect": "^4.0.0",
    "scrollama": "^2.2.1",
    "stickyfill": "^1.1.1-strict",
    "topojson-client": "^3.1.0"
  }
}
```

## 🤔 Expected Behavior

Build a production bundle

## 😯 Current Behavior

No error, build process just freezes at some point on a given file. The file that it appears to get stuck on is not consistent. 

## 💁 Possible Solution

🤷 

## 💻 Code Sample

public version of the WIP app here: [https://github.com/auchers/mta-census-data-vis/tree/master/app](https://github.com/auchers/mta-census-data-vis/tree/master/app)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12
| Node             | v14.2.0
| Yarn         | 1.22.4
| Operating System | MacOS Catalina V10.15.5

**Comment by mischnic** [comment]
Very strange, seems like some while loop in the source map handling takes eccessively long. `--no-source-maps` works for me.

Parcel 2 works fine

**Comment by auchers** [comment]
`--no-source-maps` did the trick for me. 
Thanks for the help!
