### ISSUE TITLE
Parcel doesn't always pickup source map file correctly

### ISSUE THREAD

**Issue by gregid** [parcel-bundler/parcel#4699]
# 🐛 bug report

My current mono repo set up is as follows
```
- lib-dist
- lib-src
- app-dist
- app-src
```
where `lib-dist` is generated by `rollup` and `app-dist` is generated by `parcel` and has `lib-dist` as dependency

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json script:
```
"app:start": "parcel app-src/index.html --out-dir app-dist",
"build:watch": "rollup --watch --config --sourcemap",
```

## 🤔 Expected Behavior

If I make change to `app-src` or `lib-src` and save, `parcel` should pick up changes and reload app in the browser with correct (updated) source map mapping

## 😯 Current Behavior

If I make change to `app-src` and save, `parcel` picks up changes and reloads app in the browser with correct (updated) source map mapping.

But if I make change only to `lib-src` and save - `rollup` saves `lib-dist` and `parcel` picks up changes for source code and reloads app in the browser but in 50% of cases the source map for the `lib-dist` will be incorrect i.e.: in console it will show the same line number of the same file, e.g. `jquery.js:10873` (last line of jquery in this case) for every printed line

## 💁 Possible Solution

After making dummy change to `app-src` the `lib-dist` is correctly picked up. Since it only happens in about 50% of cases my guess is parcel picks up the source file before the source map is created by rollup.

## 🔦 Context

I need to make sure that I make some change to app-src every time I make change to lib-src for correctly debugging in browser console which is not ergonomic and time wasting.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4 & 2.0.0
| Node             | v13.5.0
| npm/Yarn         | 6.13.4
| rollup          | 2.13.1
| Operating System | Win10x64

**Comment by gregid** [comment]
I tried installing parcel2 and so far it seems it works correctly. Will see in the next few days if the problem appears.

**Comment by gregid** [comment]
Unfortunately with parcel2 (2.0.0-nightly.280) the problem is even bigger - it completely ignores source map for my rollup generated file.

**Comment by gregid** [comment]
I have created sample project showing the problem:
https://github.com/gregid/rollup-lib-parcel-app

**Comment by mischnic** [comment]
Loading source maps from via `sourceMappingURL` of input assets isn't implemented yet for Parcel 2

**Comment by gregid** [comment]
@mischnic thanks for the update - is there any single place where current status of Parcel 2 (implementation wise) is so I wouldn't raise unnecessary issues in my further testing of parcel2?

**Comment by mischnic** [comment]
> issues in my further testing of parcel2?

No, keep them coming 😄

**Comment by gregid** [comment]
Q: Is this PR: #4813 on the roadmap to next release? Is my understanding correct it should address the issue?

**Comment by DeMoorJasper** [comment]
@gregid it is, someone just needs to review it and then it should be on the next release

**Comment by gregid** [comment]
That's great, looking forward to testing it on nightly build once ready!

**Comment by mischnic** [comment]
> someone just needs to review it

And someone to fix CI 😉

**Comment by gregid** [comment]
sorry to be PITA but I've noticed the CI has been fixed for few days now and I am checking the progress few times a day (I need it a lot) hoping tomorrow is the day I could use it on nightly build...

**Comment by gregid** [comment]
Other than failing to build on incorrect sourcemap URL #5031 the initial problem - randomly picking up external sourcemaps seems to be gone with the new PR, I will continue to test it a bit further and if it will continue to work will close this issue.

**Comment by gregid** [comment]
Haven't failed so far, closing the issue.
