### ISSUE TITLE
JSON files are not resolved

### ISSUE THREAD

**Issue by gabrielsanterre** [parcel-bundler/parcel#47]
JSON files are not resolved.

We should be able to do:
```
import data from './data.json';
```

I'm currently getting error similar to this:
```
Cannot resolve dependency './data.json'
```

**Comment by gabrielsanterre** [comment]
Other example:
```
[my project path]/node_modules/moment-timezone/index.js:2:23: Cannot resolve dependency './data/packed/latest.json'
  1 | var moment = module.exports = require("./moment-timezone");
> 2 | moment.tz.load(require('./data/packed/latest.json'));
    |                        ^
  3 | 
```

**Comment by devongovett** [comment]
hmm, this should work and there are tests for it. https://github.com/parcel-bundler/parcel/tree/master/test/integration/json

are you sure you have the right relative path?

**Comment by gabrielsanterre** [comment]
Maybe not in my code but it should be the right one in the`moment-timezone` package. Also when I converted my data.json file to data.js and added `export default` at the beginning parcel successfully resolved it. So I don't think it's a path issue.

**Comment by gabrielsanterre** [comment]
In the test it's `require('./file.json')`, maybe it's an issue using `import file from './file.json'` ?
