### ISSUE TITLE
JS and CSS files not found after parcel build

### ISSUE THREAD

**Issue by zamhaq** [parcel-bundler/parcel#470]
🐛 bug report

`parcel build index.html` generates the `dist` folder with all the files, but launching `index.html` from inside the `dist` results in `can not find css and the js files`.

### 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc:-
```js
{
  "presets": [
        "env",
        "react"
    ]
}
```

package.json
```js
{
"name": "referraly-frontend",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "parcel index.html"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "material-ui": "^0.20.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-router-dom": "^4.2.2",
    "typeface-roboto": "0.0.45"
  },
  "devDependencies": {
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "parcel-bundler": "^1.3.1"
  }
}
```
`cli command` : `parcel build index.html`

### 🤔 Expected Behavior

Produces the build folder with the correct bundles instead of reporting missing `css` and `js` files in the browser console.

### 😯 Current Behavior

Errors in browser console on launching `index.html` from the build folder `dist`.
![js_not_found](https://user-images.githubusercontent.com/20766601/34479292-e6eceb8c-efcb-11e7-83c3-0291b2f58f51.png)

### 💁 Possible Solution
change `src` in `script` and `link` tags to remove errors.
eg:- change `src="/dist/cfb47e75612b85db2daa42a5bbad3b67.js"` to
`src="./cfb47e75612b85db2daa42a5bbad3b67.js"`

But still, only half of the page is displayed
![half_page](https://user-images.githubusercontent.com/20766601/34479684-3514e5b0-efce-11e7-95a1-f1b87f823131.png)

### 🔦 Context

Trying to produce the production build for a test deployment.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.3.1
| Node             | v8.6.0
| npm/Yarn         | 5.5.1
| Operating System | Ubuntu 16.04

**Comment by DeMoorJasper** [comment]
Change ``"start": "parcel index.html"``
to ``"start": "parcel index.html --public-url /"``

**Comment by zamhaq** [comment]
@DeMoorJasper still does not solves the issue. 
`npm run start` now gives a `404` error and `parcel build index.html` still results in `css and js` file not found.
Please reopen the issue if you think its a bug. Also, please comment if any additional info is required. :+1:

**Comment by DeMoorJasper** [comment]
ow my bad, i misread the start command.
U should add a build command like: ``parcel build index.html --public-url /``

**Comment by zamhaq** [comment]
`parcel build index.html --public-url /` results in the same errors on launching `index.html`.

**Comment by DeMoorJasper** [comment]
try ``parcel build index.html --public-url ./``
this is also documented on the doc site: https://parceljs.org/production.html

**Comment by zamhaq** [comment]
Ok @DeMoorJasper that solves the wrong `src`, sorry might have skipped that part when going through `docs` :sweat_smile: However, getting the following errors now: 
![consolerrorbild](https://user-images.githubusercontent.com/20766601/34480727-19e60a2a-efd4-11e7-9766-2452abcc54ff.png)

I think that is not a `parcel` issue? Since, I am using `react-router` and history does not work with `file://` url's maybe thats why I am getting those errors?

**Comment by DeMoorJasper** [comment]
This is a react-router issue, just has to do with filesystem not being a valid url, it should work fine if u test it on an apache,nginx,.. server

**Comment by zamhaq** [comment]
@DeMoorJasper Thanks for helping :smile:

**Comment by grrunnz** [comment]
But the default for --public-url should be ./ instead of ./dist/ since the index.html is in the dist folder.

**Comment by IsaacHub** [comment]
> Sorry i forgot a dot try `parcel build index.html --public-url ./`
> this is also documented on the doc site: https://parceljs.org/production.html

No it's not documented. The `--public-url ./` is not there.

**Comment by avalanche1** [comment]
> Sorry i forgot a dot try parcel build index.html --public-url ./
this is also documented on the doc site: https://parceljs.org/production.html

@DeMoorJasper, I'm sorry, but I don't see that in the docs. So I had to google this issues :(

**Comment by Nagasai20** [comment]
Can i know what is the solution for this ? why it was closed ?

**Comment by TheOddler** [comment]
> 
> 
> Can i know what is the solution for this ? why it was closed ?

For me the sollution seemed to be to add ` --public-url ./` to my `parcel` commands. So: `parcel src/index.js --target electron --public-url ./`

**Comment by DRocksCoding** [comment]
> > Can i know what is the solution for this ? why it was closed ?
> 
> For me the sollution seemed to be to add ` --public-url ./` to my `parcel` commands. So: `parcel src/index.js --target electron --public-url ./`

This worked for me too.
I was getting 404 files not found when dropping the dist folder content on my website server.
I changed my build commands like you said:
`
"scripts": {
    "dev": "parcel src/index.html",
    "build": "parcel build src/index.html --public-url ./"
  }
`

**Comment by SzymonRojek** [comment]
I couldn't properly deploy a project (parcel bundler) on gh-pages. For me it was completely new subject, but finally I have found this post and now the code works just fine, thanks!
```
 "scripts": {
    "dev": "parcel index.html",
    "build": "parcel build index.html --public-url ./",
    "deploy": "rm -rf dist/ && npm run build && gh-pages -d dist"
  },
  ```

**Comment by Berkmann18** [comment]
> > Sorry i forgot a dot try `parcel build index.html --public-url ./`
> > this is also documented on the doc site: https://parceljs.org/production.html
> 
> Now it's right here https://parceljs.org/cli.html#set-the-public-url-to-serve-on

Both pages lead to 404s and none of the solutions here work for me.

**Comment by Sambuxc** [comment]
> Sorry i forgot a dot try `parcel build index.html --public-url ./` this is also documented on the doc site: https://parceljs.org/production.html

This link should now be -> https://parceljs.org/features/production/
