### ISSUE TITLE
--experimental-scope-hoisting not working with firebase/analytics

### ISSUE THREAD

**Issue by sudssm** [parcel-bundler/parcel#4707]
# 🐛 bug report

On a simple test app with firebase analytics, running parcel build with `--experimental-scope-hoisting` causes errors. The same app works as expected when built without the flag

## 🎛 Configuration (.babelrc, package.json, cli command)

Parcel version 1.12

I don't have a .babelrc - if I understand correctly, this just means I'm using parcel's default.

My code:
```
import 'firebase/analytics'
import firebase from 'firebase/app'

const config = {
// firebase config
}

firebase.initializeApp(config)
firebase.analytics()
```

And the reference in my index.html: ` <script src="js/landing.js"></script>`

## 🤔 Expected Behavior

Should work with --experimental-scope-hoisting

## 😯 Current Behavior

I run `parcel build src/index.html --experimental-scope-hoisting`. This gives no errors, but when I go to my browser I see 
```
Uncaught (in promise) TypeError: Cannot set property 'update' of undefined
    at landing.9cf71f69.js:1
    at landing.9cf71f69.js:1
    at Object.next (landing.9cf71f69.js:1)
    at $ (landing.9cf71f69.js:1)
```
which points to an error deep inside firebase code. But, when I run  `parcel build src/index.html` everything works as expected. 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.12.4
| Node             | v14.3.0
| npm/Yarn         | npm 6.14.4
| Operating System | occurs on osx ans ubuntu

**Comment by devongovett** [comment]
Please try Parcel 2. v2's scope hoisting is much improved over v1.

**Comment by mismith** [comment]
@devongovett I know you likely don't want to have to answer this question, but what about if we can't use v2 for other reasons; is there any workaround for v1.9?
