### ISSUE TITLE
CSS appears before <!DOCTYPE html> if <body> is absent

### ISSUE THREAD

**Issue by yoursunny** [parcel-bundler/parcel#4712]
# 🐛 bug report

Parcel generates invalid HTML when:
* HTML does not contain `<head>` and `<body>` tags.
* JavaScript imports a CSS package.

**index.html**
```html
<!DOCTYPE html>
<script src="main.jsx"></script>
```

**main.jsx**
```jsx
import "purecss";

import { h, render } from "preact";

function App() {
  return <div class="pure-button pure-button-primary">OK</div>;
}

window.onload = () => {
  render(<App/>, document.body);
};
```

## 🎛 Configuration (.babelrc, package.json, cli command)

**package.json**
```json
{
  "private": true,
  "scripts": {
    "start": "parcel index.html --no-autoinstall"
  },
  "dependencies": {
    "preact": "^10.4.4",
    "purecss": "^2.0.3"
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.4"
  }
}
```

## 🤔 Expected Behavior

**dist/index.html** should contain:
```html
<!DOCTYPE html>
<link rel="stylesheet" href="/main.65f60760.css">
<script src="/main.65f60760.js"></script>
```

## 😯 Current Behavior

**dist/index.html** contains:
```html
<link rel="stylesheet" href="/main.65f60760.css"><!DOCTYPE html>
<script src="/main.65f60760.js"></script>
```

This is invalid HTML because `<!DOCTYPE html>` must appear before `<link>` element.

## 💁 Possible Solution

Adding a `<body>` tag, a `<head>` tag, or any element that causes the creation of a body would solve the issue. For example:

```html
<!DOCTYPE html>
<head>
<script src="main.jsx"></script>
```

```html
<!DOCTYPE html>
<script src="main.jsx"></script>
<body>
```

```html
<!DOCTYPE html>
<div></div>
<script src="main.jsx"></script>
```

However, adding a head-only element would not solve the issue:

```html
<!DOCTYPE html>
<meta charset="utf-8">
<script src="main.jsx"></script>
```

Also, this issue is not present in Parcel 2.0.0-nightly.282.

## 🔦 Context

I'm learning Preact and their getting started guide suggests `render(app, document.body);`.
Therefore, the minimal HTML that I came up with was the two lines at the top of this issue.

## 💻 Code Sample

See above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4 |
| Node             | v14.4.0 |
| npm/Yarn         | 6.14.5 |
| Operating System | Windows 10 version 2004 |

**Comment by mischnic** [comment]
Given that this is very easy to workaround and it works with Parcel 2, I'm going to close this since Parcel 1 will likely not receive new updates.
