### ISSUE TITLE
sourceMappingURL not being generated correctly in Parcel 2

### ISSUE THREAD

**Issue by fab7jj** [parcel-bundler/parcel#4714]
I am using Parcel 2 and in my package.json I have the following:

 "scripts": {
    "start": "parcel watch src/index.js"
  }

which then generates a dist folder with index.js and index.js.map, which I reference from my index.html as follows: 

<script src="./dist/index.js"></script> 

In the generated index.js the sourceMappingURL is as follows:

//# sourceMappingURL=index.js.map

But chrome developer tools does not find them, causing the debugger; command to not work correctly. If I then change that line to the below it works but I don't know how to make this change permanent

//# sourceMappingURL=./dist/index.js.map

**Comment by DeMoorJasper** [comment]
@fab7jj that's strange sourceMappingUrl should be relative to the source-file, so it should actually be: `//# sourceMappingURL=./index.js.map` not sure why that does not work

**Comment by fab7jj** [comment]
![Chrome Dev Tools](https://user-images.githubusercontent.com/40164436/84050286-cf440800-a9ad-11ea-96a1-f41049547476.PNG)

@DeMoorJasper The above picture illustrates what is happening to me. Once I manually fix the sourceMappingURL, then it's all good but of course it is very tedious. 

I recall that in parcel 1 you could someting like --public-url ./ in order to fix this but this is no longer available in parcel 2. Can you please enlighten me?

**Comment by kaiba42** [comment]
+1 on this issue

**Comment by DeMoorJasper** [comment]
@fab7jj does it work with `//# sourceMappingURL=./index.js.map` if it does we just need to change it to relative paths what we need to do anyway...

**Comment by fab7jj** [comment]
@DeMoorJasper no it only works with `//# sourceMappingURL=./dist/index.js.map` or `//# sourceMappingURL=/index.js.map` ... notice the ommission of the dot

My folder structure is as below:
![File structure](https://user-images.githubusercontent.com/40164436/84131344-b9cded00-aa44-11ea-97ca-aab1c0b87fda.PNG)

**Comment by fab7jj** [comment]
@DeMoorJasper @mischnic so this is a bug? It's not me using parcel incorrectly? If so is there active development on this project so I should expect a fix soonish? Thanks

**Comment by mischnic** [comment]
Yes it is a bug

**Comment by fab7jj** [comment]
@mischnic do you have a rough ETA for a fix?

**Comment by fab7jj** [comment]
@mischnic @DeMoorJasper does this mean that I can now update the parcel package and I will get this fix? Thanks a lot

**Comment by mischnic** [comment]
If you update to the latest nightly, yes.

**Comment by fab7jj** [comment]
I just need to run yarn upgrade --dev parcel@next? Sorry if it is a dump question but new to all this. Thanks a lot for your help

**Comment by mischnic** [comment]
`yarn add -D parcel@nightly` should work (and overwrite your currently installed version)
