### ISSUE TITLE
🐛Code splitting error in 1.4.1 with external lib (leafletjs)

### ISSUE THREAD

**Issue by ziaxdk** [parcel-bundler/parcel#472]
### 🤔 Expected Behavior

To work as in 1.3.1

### 😯 Current Behavior

Error in external lib, but works in 1.3.1

### 🔦 Context

In 1.4.1 it fails. In 1.3.1 it works

Change _package.json_ config to __~1.3.1__ and install again and it works.

### 💻 Code Sample

(https://github.com/ziaxdk/parcel-bug)

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.41
| Node             |8.9.3
| npm/Yarn         |npm
| Operating System |win10

**Comment by DeMoorJasper** [comment]
Can't seem to reproduce in 1.8.1
