### ISSUE TITLE
Parcel v2 is serving wrong index.html when there're multiple entry points

### ISSUE THREAD

**Issue by balthild** [parcel-bundler/parcel#4740]
# 🐛 bug report

If I have the followng directory structure

```
./a/index.html
./b/index.html
./c/ (no files under this dir)
```

and serving it with parcel v2. Visiting `http://localhost:1234/b` and `http://localhost:1234/c` gets `./a/index.html` instead of the correct ones.

Related: #3996

## 🎛 Configuration (.babelrc, package.json, cli command)

```
yarn parcel ./**/*.html
```

## 🤔 Expected Behavior

Get `./b/index.html` when visiting `/b` and a 404 error when visiting `/c` (since there's no ./index.html, it's not a SPA).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2 |
| Node             | v14.4.0 |
| npm/Yarn         | 1.22.4 |
| Operating System | macOS 10.15.5 |

**Comment by DeMoorJasper** [comment]
Have you tried using the nightly release of parcel `yarn add parcel@nightly`?

**Comment by balthild** [comment]
I've just tried it. The behavior is the same.

**Comment by mischnic** [comment]
The dev server should definitely behave more like a traditional web server. (and in the SPA case, use "a index.html in a parent folder" instead of "any index.html")

Somewhat related: https://github.com/parcel-bundler/parcel/issues/4429
