### ISSUE TITLE
Using public URL for dynamic imports

### ISSUE THREAD

**Issue by PurpleHexagon** [parcel-bundler/parcel#4747]
# 💬 RFC

When using code splitting and thus dynamic imports allow for public URL to be specified rather than trying to determine base URL based on stacktrace

## 🔦 Context

I am currently trying to get a React application working on some complex infrastructure which is out of my control. Due to the way this works the URL matched it the Error.stack is not correct ... referenced here https://github.com/parcel-bundler/parcel/pull/2434 which is basically this code https://github.com/parcel-bundler/parcel/blob/v2/packages/runtimes/js/src/bundle-url.js#L23 (Not sure if that is the right file as function is defined multiple places)

I would like to be able to use the public url which is already being passed into the parcel command in our case.

## 💻 Examples

Possible solution

parcel src/app.html -d dist/output/ --cache-dir .cache/output/ --public-url https://example.com/dist_alias --use-public-url-for-import true

And then check for this flag before trying to match the base url from error trace.

But am really open to anything that will allow for us to get the application working on this infrastructure.

**Comment by mischnic** [comment]
I think you are using Parcel 1 but referring to the sources for Parcel 2.

Could you share more details about your environment?

**Comment by PurpleHexagon** [comment]
You are correct I am using Parcel 1 ... the correct file should have been https://github.com/parcel-bundler/parcel/blob/1.x/src/builtins/bundle-url.js ... I just did a search on Github for the code and didn't see the version number.

I don't know too much about the environment but basically the React application that parcel is bundling up is hosted within AWS and is then embedded into Abobe Experience Manager. 

Everything works fine until the application is embedded in the CMS where the include of the first lazy loaded js file will break as the base url is incorrect.

The include is basically picking up the base url of the CMS as the React app is included via JavaScript.

**Comment by PurpleHexagon** [comment]
@mischnic Did you have any thoughts on how we might resolve this issue? I'm happy to do some development work. Looks like this issue will also be present in Parcel 2. Would be great if there was a way to not have to fork the repo. Also having trouble working out best way to get the public url into each generated file at time bundle is created.

**Comment by mischnic** [comment]
So the main bundle is loaded as `example.com/etc/cms/assets.js` and all of the other assets/JS bundles are in `example.com/parcel-dist`? (Did this happen because the entry bundle was somehow bundled again?)

For Parcel 2, all of this bundle loading is implemented in the js runtime plugin: https://github.com/parcel-bundler/parcel/blob/d19bee10bef6b611c02ef8af8b40101bb0a238cf/packages/runtimes/js/src/JSRuntime.js#L340

So in the worst case, you could use your own runtime plugin instead of the default one (without "forking" Parcel itself)

**Comment by PurpleHexagon** [comment]
example.com/etc/cms/assets.js is a script that is tasked with embedding the html output from Parcel which then loads the bundled js etc but with the wrong path. Its part of how SPA are embedded into this particular CMS I believe. 

Thank you for the information regarding Parcel 2 that looks like it could make things much easier, as you say without forking. 

Is there any rough schedule of how long V2 will be in beta?

Thanks again for your help and for the information regarding Parcel 2 runtime plugins.

**Comment by MaffooBristol** [comment]
Parcel 2 does this out of the box now via the runtime layer. See https://github.com/parcel-bundler/parcel/discussions/5732
