### ISSUE TITLE
Parcel does not load babel.config.js file

### ISSUE THREAD

**Issue by daniele-orlando** [parcel-bundler/parcel#4749]
# 🐛 bug report

Parcel loads correctly `.babelrc.js` file, but does not load `babel.config.js` file.

## 🤔 Expected Behavior

Parcel should load all Babel config formats.

## 😯 Current Behavior

Parcel loads only .babelrc and .babelrc.js files, but does not load `babel.config.js` file.
## 💁 Possible Solution

https://github.com/parcel-bundler/parcel/blob/e2ea84373758ef22da979bc7abaf9b8ca29a1f59/packages/core/parcel-bundler/src/transforms/babel/babelrc.js#L73

The list of searched files should be extended to support even 'babel.config.js'.

## 💻 Code Sample

```
echo "console.log('hello world from babel.config.js')" > babel.config.js

parcel --log-level 3 index.html
```

We should see 'hello world from babel.config.js', but nothing is printed.

This works instead

```
echo "console.log('hello world from .babelrc.js')" > .babelrc.js

parcel --log-level 3 index.html
```

showing "hello world from .babelrc.js".

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 13.8
| npm/Yarn         | 6.14
| Operating System | MacOS 15

**Comment by mischnic** [comment]
Parcel 2 supports `babel.config.js` (though this is still discouraged as this prevent some caching)

**Comment by daniele-orlando** [comment]
Is there any plan to backport it to the `1.x` branch, meanwhile Parcel 2 is not released and stabilised?

**Comment by DeMoorJasper** [comment]
@daniele-orlando there is not, Parcel 2 is fairly stable at this point and backporting it to Parcel 1 will be quite hard as it would require quite a large rework.
