### ISSUE TITLE
Generated web worker script tries to import css file on development

### ISSUE THREAD

**Issue by quangta93** [parcel-bundler/parcel#4751]
# 🐛 bug report

I am trying to set up a project with `tailwindcss` and `threads`, which provides a thin wrapper on top of native web worker.

On development environment with `parcel serve`, worker script has an unexpected `importScript('./app_name.[hash].css')` which crashes the worker thread. `parcel build` does not have this issue.

## 🎛 Configuration (.babelrc, package.json, cli command)

https://github.com/quangta93/parcel-tailwindcss-threads

## 🤔 Expected Behavior

Worker script built on development should not include style files. Scripts generated on development and production should have the same behaviors.

## 😯 Current Behavior

On development environment with `parcel serve`, worker script has an unexpected `importScript('./app_name.[hash].css')` which crashes the worker thread. `parcel build` does not have this issue.

![image](https://user-images.githubusercontent.com/2924390/84930539-13629700-b097-11ea-82eb-dc98476daef1.png)

## 💁 Possible Solution

Native web worker works fine with `tailwindcss`. It's the specific combination of `tailwindcss` (or maybe just postcss) with `threads` (which hijacks the native Worker class).

## 🔦 Context

A common scenario is to use web worker to handle I/O and heavy computation. I am utilizing `threads` and its observable pattern for this purpose. `tailwindcss` is for building UI components.

## 💻 Code Sample

https://github.com/quangta93/parcel-tailwindcss-threads

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-alpha.3.2|
| Node             |v12.14.1|
| npm/Yarn         |1.12.0|
| Operating System |Windows 10|

**Comment by quangta93** [comment]
Edit: The issue is only observed when using typescript!

**Comment by sangeeth96** [comment]
Same here. Even trying to import a JSON file into the worker is causing CSS import to be added.

**Comment by mischnic** [comment]
After bundling, the CSS bundle is a sibling of both the main JS bundle (correct) and the worker bundle (wrong)...

**Comment by mischnic** [comment]
Small reproduction:
```html
<script src="./threads"></script>
```
```js
// threads.js
import "./get-bundle-url";
import "./tailwind.css";

new Worker("./worker");

console.log("index");

// works.js
import "./get-bundle-url";
console.log("worker thread");

// other files's contents are arbitrary
```
`build` and `serve` behave differently because with `serve` the two `import "./get-bundle-url";` refer to the same asset in the asset graph while `build` causes two different assets to be created (not sure which of the two is correct)
