### ISSUE TITLE
Parcel 2 -> NODE_ENV is not recognized

### ISSUE THREAD

**Issue by fab7jj** [parcel-bundler/parcel#4756]
I am trying to setup a staging environment in order to be able to have different environment variables for staging... something like: ".env.staging".

After some research on how to do this, I tried the below code:

```
"scripts": {
    "build": "parcel build src/index.js",
    "stage": "NODE_ENV=staging parcel build src/index.js",
    "start": "parcel watch src/index.js"
  }, 
```

But whenever I run "yarn stage" I get the error that NODE_ENV is not recognised as a command. Am I doing something wrong or this was something of Parcel 1? If so how do I achieve this in Parcel 2?

Thanks a lot

**Comment by mischnic** [comment]
That error is caused by Yarn. Are you on Windows? In that case `cross-env NODE_ENV=staging parcel build src/index.js` (and install cross-env as a dev dependency)

**Comment by manish-baghel** [comment]
To confirm try `npm` instead of `yarn`. Most likely it's caused by `yarn`

**Comment by fab7jj** [comment]
@mischnic that was it, thanks a lot for your help, much appreciated.

The only thing I noticed after fixing this is that if I run yarn stage everything works as expected but then if afterwards I run yarn build, it still takes the environment variables of staging unless I manually delete the folder .parcel-cache.

Is this a bug or it is by design? Running yarn start always refreshes the cache and takes the development environment variables.

Thanks once again

**Comment by mischnic** [comment]
> Is this a bug

A known bug 😬
