### ISSUE TITLE
Running parcel build without  --no-scope-hoist generates an error about a missing export

### ISSUE THREAD

**Issue by youknowriad** [parcel-bundler/parcel#4758]
# 🐛 bug report

In https://github.com/youknowriad/asblocks/pull/32 I've tried moving our build setup from Webpack to parcel 2 beta 1. While everything works properly on dev, it seems the production build with scope hoisting enabled fails because of the @wordpress/element package.

Here's the full error I have

<img width="875" alt="Capture d’écran 2020-06-18 à 8 16 48 PM" src="https://user-images.githubusercontent.com/272444/85062991-5d37a400-b1a1-11ea-9eee-7d9919093ae0.png">

After digging into the source code of that package, I've found that the mentioned file there `node_modules/@wordpress/element/build-module/index.js` does `export * from ./react.js` and on that `react.js` file, there's indeed a `createElement` function being exported.

Can't tell for sure whether it's a bug on Parcel's tree shaking behavior or if it's the package doing it wrong.

## 🌍 Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2 beta 1
| Node             | v12.14.1
| npm/Yarn         | 6.14.5
| Operating System | MacOS

**Comment by mischnic** [comment]
That particular error was a bug and will be fixed by the linked PR.

But with that change applied, I get annother (genuine!) error:

```
@parcel/packager-js: node_modules/reakit/es/Composite/index.js does not export 'unstable_CompositeItem'
.../node_modules/@wordpress/components/build-module/alignment-matrix-control/cell.js:8:10
   7 |  */
>  8 | import { unstable_CompositeItem as CompositeItem } from 'reakit/Composite';
>    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   9 | /**
  10 |  * Internal dependencies
```

That file only export `export { unstable_CompositeItemWidget, unstable_useCompositeItemWidget } from ....';`.

**Comment by youknowriad** [comment]
Thanks for the fix for the original error :) 

Maybe you're fetching a wront reakit version for some reason, 

I do see `export { unstable_CompositeItem, unstable_useCompositeItem } from './CompositeItem.js';` when opening that file `node_modules/reakit/es/Composite/index.js` personally.

**Comment by mischnic** [comment]
I only have `export { CompositeItem, useCompositeItem } from './CompositeItem.js';`.

I checked out your branch and ran `npm ci`.

**Comment by youknowriad** [comment]
going to try a clean `rm -rf node_modules && npm install` and report back.

**Comment by youknowriad** [comment]
Here's my full terminal output for `rm -rf node_modules && npm ci && cat node_modules/reakit/es/Composite/index.js`

https://asblocks.com/write/W837wycKWAsZIxOlFKWL/4915db03-826a-429d-8349-f01584dcdb88#key=xE_2rq3l5AEi4bpf1omUjQ

As you can see on the two last lines, the export is there https://asblocks.com/read/W837wycKWAsZIxOlFKWL#key=xE_2rq3l5AEi4bpf1omUjQ 

I believe you might be getting the new version of reakit somehow instead of the one used there but regardless, it's seem more of an npm bug (or dependencies one) rather than a parcel one.

**Comment by youknowriad** [comment]
**Edit** I switched branches again and I'm reproducing your issue, I agree it's a genuine issue but don't bother with it. I'll find it.

**Comment by youknowriad** [comment]
Thanks again for the fix above.
