### ISSUE TITLE
npmjs.com upset because of missing readme

### ISSUE THREAD

**Issue by insuusvenerati** [parcel-bundler/parcel#4763]
Sorry if this is the wrong place for this. 

It seems since README.md is linked to the v2 branch, [npmjs.com](https://www.npmjs.com/package/parcel-bundler) is upset about a missing readme file.

**Comment by mischnic** [comment]
Duplicate of https://github.com/parcel-bundler/parcel/issues/2446

(And the `parcel-bundler` package isn't published from the v2 branch)
