### ISSUE TITLE
Parcel not working with HyperHTML (import package sub-folder)

### ISSUE THREAD

**Issue by chrismbeckett** [parcel-bundler/parcel#477]
Parcel Bundler: 1.4.1
Node: 8.9.3
OS: Windows 10
HyperHTML: 2.4.3

HyperHTML builds different module types into sub-folders (e.g. /esm /cjs). It differentiates for bundlers using the standard keys `main` and `module` in **package.json**.

```
{
  "main": "cjs/index.js",
  "module": "esm/index.js",
}
```

Importing from the package root is not working with parcel. Parcel does not throw an error, but when running the code, the import `hyper` reference is an empty object.

```
import hyper from 'hyperhtml'
```

To import using parcel requires including the sub-folder in the import:

```
import hyper from 'hyperhtml/esm'
```

I think that parcel should support the `main` and `module` keys.

**Comment by brandon93s** [comment]
Related to #418 & #298.

**Comment by chrismbeckett** [comment]
Confirmed the issue is with the `main` and `module` pointing to sub-folders. I added an index file in the root folder that just re-exports the file from the sub-folder and updated the `module` to point to the root file and it worked.

**Comment by DeMoorJasper** [comment]
Closing as #418 & #298 have been resolved.
