### ISSUE TITLE
length of undefined

### ISSUE THREAD

**Issue by NikosEfthias** [parcel-bundler/parcel#4770]
https://github.com/parcel-bundler/parcel/issues/4691#issue-630446011
My earlier bug report was closed with no fix but the problem persists and randomly happens so I am opening another bug report hopefully this wont be closed because closing the bug report does not fix the bug itself

**Comment by DeMoorJasper** [comment]
@NikosEfthias does it work in Parcel 2?

**Comment by NikosEfthias** [comment]
I have no idea but I figured when it happens exactly. When I fresh clone the repo after npm i things dont work givin length of undefined however if I do npm i --save parcel-bundler again it works. It is almost like base npm install after cloning does not pull everything needed but when I redownload parcel things just work.
How do I get parcel 2? On the website theres no mention of parcel 2 yet

**Comment by mischnic** [comment]
https://v2.parceljs.org/getting-started/webapp/

**Comment by NikosEfthias** [comment]
thanks

**Comment by arthursw** [comment]
I also have this problem, and found no solution so far.

**Comment by NikosEfthias** [comment]
@arthursw I dont have parcel installed globally
