### ISSUE TITLE
Specifying type="module" for script tag breaks HMR

### ISSUE THREAD

**Issue by subhero24** [parcel-bundler/parcel#4773]
# 🐛 bug report

When I add a type="module" attribute in a script tag in my index.html, the HMR fails when parcel wants to reload the page on saving changes to the index.html file.

In the browser the error is the following
```
HMRRuntime.js:56 Uncaught TypeError: Cannot read property 'parcelRequire' of undefined
    at HMRRuntime.js:56
    at Array.forEach (<anonymous>)
    at WebSocket.ws.onmessage (HMRRuntime.js:53)
```

## 🎛 Configuration

No configuration, just a html file like the following

```html
<!DOCTYPE html>
<html>
	<head>
		<script src="./index.js" type="module"></script>
	</head>
	<body>
		<div>test</div>
	</body>
</html>
```

**Comment by mischnic** [comment]
For development builds, we want to remove the `type=module` above and in the module/nomodule case remove the second script tag entirely.

**Comment by meetmangukiya** [comment]
Not sure if this is related
```
meet@meet-laptop /t/final-cornerstone-react-component-example-with-config-for-webworkers> parcel build src/index.html
🚨 Build failed.
@parcel/core: Failed to resolve 'cornerstone-math' from './src/index.js'
/tmp/final-cornerstone-react-component-example-with-config-for-webworkers/src/index.js:7:34
  6 | import * as cornerstone from "cornerstone-core";
> 7 | import * as cornerstoneMath from "cornerstone-math";
>   |                                  ^^^^^^^^^^^^^^^^^^
  8 | import * as cornerstoneTools from "cornerstone-tools";
  9 | import Hammer from "hammerjs";
@parcel/resolver-default: Could not load './src/index.js' from module 'cornerstone-math' found in package.json#module
/tmp/final-cornerstone-react-component-example-with-config-for-webworkers/node_modules/cornerstone-math/package.json:17:13
  16 |   "license": "MIT",
> 17 |   "module": "src/index.js",
>    |             ^^^^^^^^^^^^^^ './src/index.js' does not existundefined'
  18 |   "repository": {
  19 |     "type": "git",
```

parcel won't build if there is a `module` field in package's `package.json`, it seems to interpret it incorrectly

**Comment by oliverdunk** [comment]
@mischnic I ran in to this one today and I'm happy to take a look at fixing it.

**Comment by oliverdunk** [comment]
@mischnic Hey again 👋  I just started to take a proper look at this.

In the module/nomodule case, I'm not sure how to deal with the fact that we might get the nomodule script first. Any thoughts? I worry we need multiple passes, so we know if a given script will be followed by a better candidate 😱 

Also, just out of curiosity, since I'm quite new to Parcel - are there currently significant differences in what Parcel outputs when ES modules are the target vs not?

**Comment by mischnic** [comment]
Maybe it's safe to assume that if you have a `module` script, then there is a `nomodule` script as well? Then we really only need to exclude the `module` script and remove the `nomodule` attribute from the other one.

> ES modules are the target vs not?

The differences are:
- use actual ESM `import`s
- tell Babel to not transpile features that are supported by all browsers that support `type="module"` anyway

**Comment by RWOverdijk** [comment]
I'm using v2 (ts, no dependencies), and in the docs it does specify "module"

Am I right to assume I should drop type="module"? It seems to work fine for me, I just want to make sure that's the "fix".

**Comment by devongovett** [comment]
This should no longer be an issue in the latest nightlies.
