### ISSUE TITLE
Order of script tags in index.html breaks HMR

### ISSUE THREAD

**Issue by mattlockyer** [parcel-bundler/parcel#4774]
# 🐛 bug report

Script tag order seems to break the HMR

## 🎛 Configuration (.babelrc, package.json, cli command)

Stock config, parcel@nightly/next

```
<body>
	<div id="root"></div>
	<script src="http://localhost:5000/index.js"></script>
	<script src="./index.js"></script>
</body>
```

## 🤔 Expected Behavior

The HMR works

## 😯 Current Behavior

The HMR does not work

## 💁 Possible Solution

```
<body>
	<div id="root"></div>
	<script src="./index.js"></script>
	<script src="http://localhost:5000/index.js"></script>
</body>
```

## 🔦 Context

It seems that `./index.js` the entry point, MUST be imported before any other scripts?

## 💻 Code Sample

See above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | nightly/next
| Node             | 12.16.3
| npm/Yarn         | npm 6.14.4
| Operating System | Ubuntu 18.04 / Brave Browser

Yes I love parcel

**Comment by mischnic** [comment]
Are these HTML snippets your source code or the bundle that Parcel creates?

Are you running `parcel src/index.html`? Then only `<script src="./index.js"></script>` in your source code is sufficient

**Comment by mattlockyer** [comment]
Yes these are HTML snippets I created to run my project.

I'm importing a locally hosted library.

When I import it above `<script src="./index.js"></script>` the HMR breaks.

**Comment by mischnic** [comment]
Was the external script also created by Parcel? I suspect that the second bundle registers itself into the module registry of the first bundle and therefore the HMR runtime is not really loaded

**Comment by mattlockyer** [comment]
Yes they were both using parcel. Thanks for following up!
