### ISSUE TITLE
missing autoInstall type

### ISSUE THREAD

**Issue by djmisterjon** [parcel-bundler/parcel#4776]
Missing auto install in type definition ! 

![image](https://user-images.githubusercontent.com/24865815/85207015-e828b380-b2f3-11ea-8b57-1ceb1cc29606.png)

**Comment by mischnic** [comment]
The TS type definitions are not maintained by us, you should report this to/open a PR with https://github.com/DefinitelyTyped/DefinitelyTyped
(https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/parcel-bundler/index.d.ts)
