### ISSUE TITLE
<source> tags are not identified and bundled if they're used under <video> tags

### ISSUE THREAD

**Issue by maxweisel** [parcel-bundler/parcel#4777]
# 🐛 bug report

If I have the following html:

```
<video playsinline autoplay muted loop id="videoHeader">
  <source src="/assets/test.mp4" type="video/mp4" media="screen and (min-device-width:600px)">
  <source src="/assets/test-iphone.mp4" type="video/mp4" media="screen and (max-device-width:600px)">  -->
</video>
```

Parcel will not detect the assets in the <source> tags. It looks like this bug was previously reported and solved here: https://github.com/parcel-bundler/parcel/issues/987 However, it was only solved for `<img>` tags, and not `<video>` tags.

## 🎛 Configuration (.babelrc, package.json, cli command)

I'm not specifying a babel config.

## 🤔 Expected Behavior

Parcel should detect the source files in `<source>` tags and bundle them appropriately.

## 😯 Current Behavior

The tag is left untouched and the generated html file has a path that references an asset not in the bundle.

## 💁 Possible Solution

Ideally I'd love to see the fix for `<img>` tags applied to `<video>` tags, but I'm unsure how to do this.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 10.19.0
| npm/Yarn         | npm 6.14.2
| Operating System | macOS 10.15.5

**Comment by DeMoorJasper** [comment]
Does this work with Parcel 2?

Should work afaik: https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/html/src/dependencies.js#L14 You should probably also use relative paths

**Comment by maxweisel** [comment]
This works in parcel2, but oddly now parcel maps these to absolute paths? so it becomes `src="/test.fbab28da.mp4"`. Is there a way in parcel 2 to set it to be a relative include? I don't plan hosting the site in /, and it may actually be served from a few different places (it's documentation)

Max

**Comment by DeMoorJasper** [comment]
@maxweisel I'm not sure if this trick still works but you could try with `--public-url ./`
