### ISSUE TITLE
[v2] posthtml-transform throws an unknown error when using posthtml-obfuscate

### ISSUE THREAD

**Issue by maxweisel** [parcel-bundler/parcel#4783]
# 🐛 bug report

When I use posthtml-obfuscate to obfuscate email addresses with v2, I get this mysterious error:

```
@parcel/transformer-posthtml: Unexpected token u in JSON at position 0
```

## 🎛 Configuration (.babelrc, package.json, cli command)

this is what my .posthtmlrc file looks like:
```
{
  "plugins": {
    "posthtml-modules": {
      "root": "./src"
    },
    "posthtml-obfuscate": {}
  }
}
```

## 🤔 Expected Behavior

I'd expect the posthtml transformer to work without an error. This example (code provided below) works fine with parcel v1.

## 😯 Current Behavior

```
🚨 Build failed.
@parcel/transformer-posthtml: Unexpected token u in JSON at position 0
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.transform (node_modules/@parcel/transformer-posthtml/lib/PostHTMLTransformer.js:119:21)
```

## 💁 Possible Solution

Digging into PostHTMLTransformer.js, the error happens here:

```
    asset.setAST({
      type: 'posthtml',
      version: '0.4.1',
      program: JSON.parse(JSON.stringify(res.tree)) // posthtml adds functions to the AST that are not serializable

    });
```

My guess is that `res.tree` is undefined, but I'm unsure what would cause that

## 💻 Code Sample

.posthtmlrc
```
{
  "plugins": {
    "posthtml-obfuscate": {}
  }
}
```

index.html
```
<p>this is a test</p>
```

command:
`npx parcel build index.html`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | v10.19.0
| npm/Yarn         | 6.14.2
| Operating System | macOS 10.15.5

**Comment by DeMoorJasper** [comment]
`JSON.parse(JSON.stringify(res.tree))` is an easy way to clone an object, but you're right it's probably not serialisable by JSON.

Should be a fairly simple thing to fix, we just have to not clone it or use a proper cloning function/library

**Comment by mischnic** [comment]
> You can see we actually use the clone module in config.js:

I think this is the actual problem:

> My guess is that res.tree is undefined, but I'm unsure what would cause that

`JSON.parse(JSON.stringify(undefined)` throws that error

**Comment by DeMoorJasper** [comment]
@maxweisel can you create a small test-case we can use to reproduce this?

**Comment by maxweisel** [comment]
Sure thing. Here you go!

Max

[parcel2-posthtml-obfuscate.zip](https://github.com/parcel-bundler/parcel/files/4810164/parcel2-posthtml-obfuscate.zip)

**Comment by DeMoorJasper** [comment]
I've figured out why it happens, it's still pretty weird that posthtml didn't throw an error but apparently we did not instantiate plugins in the loadPlugin function if the config object is empty.

So you can workaround this using the following posthtml config:
```json
{
  "plugins": {
    "posthtml-modules": {
      "root": "./src"
    },
    "posthtml-obfuscate": {
      "includeMailto": false
    }
  }
}
```

**Comment by maxweisel** [comment]
Wonderful! Thanks for the incredibly fast responses.

**Comment by john01dav** [comment]
It seems like this issue is happening again in parcel `^2.0.0-beta.1`. It should probably be re-opened.

**Comment by bebaps** [comment]
@john01dav I was having this issue as well using `2.0.0-beta.1`. I switched to using `parcel@nightly`, and all works as expected now. Try that if you can.
