### ISSUE TITLE
Changing `--public-url` does not invalidate cache

### ISSUE THREAD

**Issue by DeMoorJasper** [parcel-bundler/parcel#4784]
# 🐛 bug report

When building a html asset and changing the `public url` cache does not get invalidated and nothing seems to change in the output bundle.

Derived from a discussion about how to get relative paths in HTML bundle https://github.com/parcel-bundler/parcel/discussions/4777

## 🤔 Expected Behavior

Should rebuild using the new `--public-url` and not use cached version as all cache should invalidate

## 😯 Current Behavior

Nothing changes

## 💁 Possible Solution

Clear cache... Although we should never have to advice this

## 🔦 Context

https://github.com/parcel-bundler/parcel/discussions/4777

## 💻 Code Sample

Any html asset really, example is taken from the discussion

```html
<video playsinline autoplay muted loop id="videoHeader">
  <source src="./test.mp4" type="video/mp4" media="screen and (min-device-width:600px)">
  <source src="./test-iphone.mp4" type="video/mp4" media="screen and (max-device-width:600px)">  -->
</video>
```

# Environment

Parcel 2-beta.1

**Comment by mischnic** [comment]
Duplicate of https://github.com/parcel-bundler/parcel/issues/3862 ? Since the CLI parameter just sets the target's `publicUrl`?

**Comment by DeMoorJasper** [comment]
@mischnic yes 100% a duplicate, should've had a look first. Gonna close this
