### ISSUE TITLE
Assets hashed differently by parcel serve and parcel build

### ISSUE THREAD

**Issue by kajic** [parcel-bundler/parcel#4787]
# 🐛 bug report

## 🤔 Expected Behavior
```bash
parcel build src/server.ts --target node
```
and
```bash
parcel serve src/client.tsx
```
should set the same filename hash on an asset, regardless of whether it's referenced by `server.ts` or `client.tsx`. I.e. asset hashing should be consistent when building using `parcel build` with when serving the application using `parcel serve`. 

Otherwise, a server side rendered application doesn't produce the same output as its client side counterpart. 

## 😯 Current Behavior

Instead of assigning the same hash to an asset, the asset is given different hashes for `parcel build` and `parcel serve`. For example, running `parcel build` an asset may be named `logo.ce7aa425.svg`, while running `parcel serve` names the same asset `logo.166ff680.svg`. 

## 💁 Possible Solution

Perhaps this difference in asset hashing is by design(?), but it'd be nice if one could at least optionally enable the same kind of asset hashing when running `parcel serve` as when running `parcel build`.

## 🔦 Context

I encountered this with a server side rendered react application, for which the react client warns:
```
react-dom.development.js:88 Warning: Prop `src` did not match. Server: "http://localhost:1234/logo.ce7aa425.svg" Client: "http://localhost:1234/logo.166ff680.svg"
    in img (created by LandingPage)
    in div (created by LandingPage)
    in div (created by LandingPage)
    in div (created by LandingPage)
    in div (created by LandingPage)
    in LandingPage
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | v14.3.0
| npm/Yarn         | 1.22.4
| Operating System | OSX 10.15.5

**Comment by DeMoorJasper** [comment]
You can disable content hashing to just get a hadh of the filepath https://en.parceljs.org/cli.html#disable-content-hashing not entirely sure if it’ll work

**Comment by kajic** [comment]
> You can disable content hashing to just get a hadh of the filepath https://en.parceljs.org/cli.html#disable-content-hashing not entirely sure if it’ll work.
> 
> Parcel 2 however supports multiple targets and custom naming strategies so it might be good to try that out as well

Thanks for the suggestion, but I’d rather not disable it. Additionally, that option is only available to `build` which would result in a similar asset name discrepancy that I’m facing (`serve` would add hashes while `build` would not.

**Comment by mischnic** [comment]
The root cause for this is that the output of serve and build is simply different (e.g. hmr, minification).

>  Additionally, that option is only available to build which would result in a similar asset name discrepancy that I’m facing

`--no-content-hash` is enabled by default for `serve`, that's why 😉

**Comment by kajic** [comment]
Ah I see! Using `--no-content-hash` indeed fixed the issue. Thanks!

**Comment by jordan-keen** [comment]
Hi all, wondering if anyone is able to help on a similar issue, I am trying to keep the hash the same for both local assets and the build process assets. 

Currently I have tried to add the --no-content-hash flag in the below code for package.json, the build process is still generating different hash's. I am using an older Parcel, version 1.12.3

`"build": "node parcel.config.js --no-content-hash -f './src/**/*.bundle.js'",`
