### ISSUE TITLE
CSS order changes between development and production

### ISSUE THREAD

**Issue by pmkroeker** [parcel-bundler/parcel#4792]
# 🐛 bug report
Using parcel 2 with Material UI in development vs production builds generates a different order for the files inserted in the html file.

In development, the Material UI generated styles get added _after_ the parcel generated script and css tags (see expected behaviour). In production, the order is reversed, the Material UI styles are placed _before_ the parcel generated script and css tags.

This results in different CSS styling between the two builds, as order is critical to how CSS works.

## 🎛 Configuration (.babelrc, package.json, cli command)
package.json
```json
{
  "name": "blog",
  "version": "1.0.0",
  "description": "",
  "main": "index.html",
  "targets": {
    "main": false
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "nodemon -r dotenv/config backend/server.js --watch backend",
    "predev": "rm -rf public/dev",
    "dev": "parcel watch index.html --dist-dir ./public/dev --public-url /static/dev --no-cache",
    "prebuild": "rm -rf public/app",
    "build": "parcel build ./index.html --dist-dir ./public/app --public-url /static/app"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@material-ui/core": "^4.10.2",
    "@material-ui/icons": "^4.9.1",
    "@parcel/transformer-typescript-tsc": "^2.0.0-beta.1",
    "@parcel/validator-typescript": "^2.0.0-beta.1",
    "autoprefixer": "^9.8.2",
    "dotenv": "^8.2.0",
    "eslint": "^6.8.0",
    "eslint-plugin-react": "^7.19.0",
    "nodemon": "^2.0.4",
    "parcel": "^2.0.0-beta.1",
    "postcss-modules": "^2.0.0",
    "preact": "^10.4.4",
    "preact-markup": "^2.0.0",
    "preact-render-to-string": "^5.1.9",
    "prettier": "^2.0.5",
    "prettier-eslint": "^9.0.1",
    "react-quill": "^2.0.0-beta.2",
    "sass": "^1.26.8",
    "typescript": "^3.9.5",
    "wouter-preact": "^2.4.0"
  },
  "dependencies": {
    "bcrypt": "^5.0.0",
    "compression": "^1.7.4",
    "express": "^4.17.1",
    "express-mysql-session": "^2.1.4",
    "express-session": "^1.17.1",
    "helmet": "^3.23.1",
    "knex": "^0.21.1",
    "mysql": "^2.18.1"
  },
  "alias": {
    "react": "preact/compat",
    "react-dom": "preact/compat"
  },
  "browserslist": [
    "defaults",
    "not IE 11",
    "not IE_Mob 11",
    "maintained node versions"
  ]
}
```
.parcelrc
```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  },
  "validators": {
    "*.{ts,tsx}": ["@parcel/validator-typescript"]
  }
}
```
.postcssrc
```json
{
  "modules": true,
  "plugins": {
    "postcss-modules": {
      "generateScopedName": "[hash:base64:5]__[local]",
    },
    "autoprefixer": true,
  }
}
```
tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es2017",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "alwaysStrict": true,
    "removeComments": false,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "allowSyntheticDefaultImports": true,
    "noUnusedLocals": true,
    "jsx": "react",
    "jsxFactory": "h",
    "skipLibCheck": true
  },
  "include": ["./frontend/**/*", "./css.d.ts"]
}
```

## 🤔 Expected Behavior
![image](https://user-images.githubusercontent.com/10147685/85421055-d419c780-b528-11ea-81ab-2d4bc4b67639.png)
In development (`parcel watch` or `npm run dev`, see above package.json), the Material UI injected styles are placed ABOVE the parcel generated assets, resulting in the ability to properly modify the CSS of the Material UI components through CSS imported in the app. This is the _expected_ behaviour in production.

## 😯 Current Behavior
![image](https://user-images.githubusercontent.com/10147685/85421225-0a574700-b529-11ea-9b8e-944324004981.png)
In production (`parcel build` or `npm run build`, see above package.json), the Material UI injected styles are placed BELOW the parcel generated assets. This results in the default Material UI styles _overriding_ my given custom styles and changing the appearance. 

## 💁 Possible Solution
Unsure.

## 🔦 Context
Output CSS changing between development and production builds is frustrating for the developer. This could potentially lead to large issues if people are using `display: hidden` and expect something to be hidden, and is hidden in _development_ but not in _production_. The order of the outputs should not change on the developer depending on the used build mode.

## 💻 Code Sample
[Code Sandbox](https://codesandbox.io/s/parcel-2-mui-css-order-t0gd4)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | 10.14.2
| npm/Yarn         | npm 6.13.4
| Operating System | Win 10 64-bit

**Comment by mischnic** [comment]
Please provide a reproduction which actually contains custom styles

**Comment by pmkroeker** [comment]
I'm working on a full reproduction, but it is not giving me the same problems. I believe it may have something to do with the chunking strategy and where script tags are injected into the head between the two.

If I clean the .parcel-cache and the output directory of the project that has this issue, it still results in this problem. The only difference between the two is in one I lazy load some routes and the other I do not.

**Comment by pmkroeker** [comment]
[Material UI](https://material-ui.com/customization/components/#overriding-styles-with-class-names) has a way of [specifying where the style tags get injected](https://material-ui.com/styles/advanced/#css-injection-order). This fixes the issue.

The interesting thing (and why I will keep this open for the time being) is that Material UI specifies that by default they put their style tags at the bottom of the head element. Parcel also seems to do a similar thing with chunks but depending on prod/dev build modes the chunks get inserted differently.

**Comment by pmkroeker** [comment]
I'm going to close this as I think it may be more related to how MUI does this than parcel.
