### ISSUE TITLE
how to use inline static images

### ISSUE THREAD

**Issue by gmchaturvedi1** [parcel-bundler/parcel#480]
Dear Friends,
this is superb library.But i am struggling  to inline my  static images. Can u please guide me the way.

Regards
gmchaturvedi

**Choose one:** is this a 🐛 bug report or 🙋 feature request?

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by DeMoorJasper** [comment]
Please fill in the issue form

**Comment by gmchaturvedi1** [comment]
im simply require('./logo.png') but it si not working as its work in webpack and others .KIndly suggest us the best way to use images of local folders.

**Comment by DeMoorJasper** [comment]
The following code should work, i'm just guessing what ur specific use case is though
```Javascript
const someImage = require('./someImage.jpeg');

render() {
  return <img src={someImage} />
}
```

**Comment by gmchaturvedi1** [comment]
thanks its working
