### ISSUE TITLE
Parcel 2: Configuration to avoid tree shaking specified modules for browser

### ISSUE THREAD

**Issue by avickers** [parcel-bundler/parcel#4803]
# 🙋 feature request

It seems Parcel 2 is more aggressive at Tree Shaking, which overall is a good thing; however, I now have problems where web components that I am importing are arbitrarily getting removed from production bundles.  Whereas, the exact same code worked consistently and as expected in Parcel 1.  We should be able to configure imports not to be removed.

## 🤔 Expected Behavior

```js
import 'weightless/button'
import 'weightless/textfield'
```
Both components should be bundled and the custom elements registered.  This worked in Parcel 1.

## 😯 Current Behavior

```js
import 'weightless/button' // works consistently; <wl-button> is registered
import 'weightless/textfield' // is stripped in Parcel 2
```

My triage is 
```js
import {Card} from 'weightless/card'
let wl = new Card  // and other failed imports
wl = null
```

## 💁 Possible Solution

```json
"default": "dist/index.html",
"targets": {
    "default": {
      "includeInBrowser": ["weightless/textfield"]
    }
  },
```

## 🔦 Context

There will hopefully be a way to import web components into our projects and have them available for declarative use in markup without having to resort to such hacks.  I'm all for aggressively shrinking bundle sizes, as long as we can override as needed.

It's also confusing that about half of the [weightless](https://weightless.dev) components made it into the bundle and half were stripped, even though they were all imported and used the same way.  IMO, inconsistent behavior is the worst kind of behavior.

## 💻 Examples

```js
import 'weightless/banner' // works
import 'weightless/button' // works
import {Card} from 'weightless/card'
import {Textfield} from 'weightless/textfield'

// will not survive code review
let wl = new Card
wl = new Textfield
wl = null

export default MyRoute extends Component {
  constructor() {}

  render() {
    return `
    <wl-card>
      <wl-button>Click me</wl-button>
    </wl-card>
    `
  }
}
```

**Comment by mischnic** [comment]
This looks like a bug.

> Examples

Your example isn't complete, is this a situation where this behaviour occurs?

```js
// index.js
import "weightless/textfield"
```

```html
<script src="index.js"></script>
<wl-textfield label="Label"></wl-textfield>
```
`parcel build index.html`

**Comment by avickers** [comment]
Sorry.  It works as expected if they are imported into the top level module.  I am struggling to isolate what circumstances are required to reproduce the issue inside of sub-modules.  I will close for now and reopen if I can pin the behavior down.
