### ISSUE TITLE
splitting css is Error.

### ISSUE THREAD

**Issue by BoltDoggy** [parcel-bundler/parcel#481]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

🐛

### 🎛 Configuration (.babelrc, package.json, cli command)

no config

### 🤔 Expected Behavior

It should not have a Error.

### 😯 Current Behavior

```
Uncaught (in promise) Error: Cannot find module '6'
    at newRequire (c01a5e6b1639926710648ba43bcefe3a.js:33)
    at newRequire (455c69cb5504513e24190c3539a136b0.js:30)
    at newRequire (c01a5e6b1639926710648ba43bcefe3a.js:22)
    at localRequire (c01a5e6b1639926710648ba43bcefe3a.js:48)
    at c01a5e6b1639926710648ba43bcefe3a.js:115
    at <anonymous>
```

### 🔦 Context

```
import('./index.css').then((data) => {
    console.log(data);
});
```

### 💻 Code Sample

https://github.com/BoltDoggy/parcel-demo-for-issues/tree/issues-481

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.4.1
| Node             |8.9.0
| npm/Yarn         |5.5.1
| Operating System |mac 10.13.2 (17C88)

**Comment by devongovett** [comment]
What would you expect `data` to be in your example?

**Comment by BoltDoggy** [comment]
![image](https://user-images.githubusercontent.com/2586280/34637585-7476da8c-f2f4-11e7-9883-5ab602bf1bb9.png)
