### ISSUE TITLE
package.json#source is ignored

### ISSUE THREAD

**Issue by youk** [parcel-bundler/parcel#4811]
# 🐛 bug report

According to https://github.com/parcel-bundler/parcel#sources, `package.json#source` can be used to specify the source file(s).  However, this attribute is ignored.

## 🎛 Configuration (.babelrc, package.json, cli command)

```
{
  "name": "test",
  "version": "0.0.1",
  "source": "src/test.js",
  "devDependencies": {
    "parcel": "^1.12.4"
  },
  "scripts": {
    "build": "parcel build"
  }
}
```

## 🤔 Expected Behavior

`parcel build` should bundle the file(s) specified in `package.json#source`.

## 😯 Current Behavior

Configured `package.json#source` is ignored. `parcel build` gives an error:

```
×  No entries found.
    at Bundler.bundle (***\test\node_modules\parcel\src\Bundler.js:275:17)
error Command failed with exit code 1.
```

## 💁 Possible Solution

Pass the sources directly to `parcel build`, i.e. `parcel build src/test.js`.

## 🔦 Context

I am trying to use Parcel in accordance with the documentation which does not seem to be valid.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 14.4.0
| Yarn         | 1.22.4
| Operating System | Windows 10.0.19041

**Comment by mischnic** [comment]
You still need to pass some path as an entry, in this case it should be `parcel build .`:

https://v2.parceljs.org/getting-started/configuration/#specifying-entrypoints

**Comment by youk** [comment]
This does not help. `parcel build .` or `parcel build src` give the same "No entries found" error as above.

**Comment by mischnic** [comment]
Sorry, I didn't see that you are using Parcel 1. Your link https://github.com/parcel-bundler/parcel#sources is the readme of the Parcel 2 branch. (`yarn add parcel@next`)

**Comment by youk** [comment]
Ah thanks. It's ok with Parcel 2.

**Comment by codemilli** [comment]
@mischnic why does it ignores though in website they say it references `source` in `package.json` ?
