### ISSUE TITLE
SSR for `index.html`

### ISSUE THREAD

**Issue by alexreardon** [parcel-bundler/parcel#4816]
Hi there!

I am currently using `parcel@2.0.0-beta.1` for building a small web app. The `index.html` file is fairly straightforward:

```html
<!DOCTYPE html>
<html lang="en">
  <body>
    <div id="root"></div>
    <script src="./entry.tsx"></script>
  </body>
</html>
```

Then inside of `entry.tsx`:

```tsx
import React from 'react';
import ReactDOM from 'react-dom';
import App from './app';

ReactDOM.render(<App />, document.getElementById('root'));
```

When building for production, I would like to be able to server side render the application. So the new html file would be would be:

```html
<!DOCTYPE html>
<html lang="en">
  <body>
    <div id="root">{result of ReactDOMServer.renderToString() goes here}</div>
    <script src="./entry.tsx"></script>
  </body>
</html>
```

Now doing a hydrate

```tsx
import React from 'react';
import ReactDOM from 'react-dom';
import App from './app';

ReactDOM.hydrate(<App />, document.getElementById('root'));
```

I am exploring a few different ways to do this. Rather than going all over the place I wanted to get your thoughts on what you think the best approach to this is with Parcel

**Comment by mischnic** [comment]
This might be possible with an optimizer plugin that somehow calls `ReactDOMServer.renderToString(....)` and injects it into the html bundle.
