### ISSUE TITLE
Aware of https://bundlers.tooling.report/?

### ISSUE THREAD

**Issue by kud** [parcel-bundler/parcel#4822]
Hello,

I wanted to know if you're aware of https://bundlers.tooling.report/ ?

As you can see, the score isn't so good compared to the other bundlers. It's a shame because I'd love to see parcel having a better reputation, because it's an excellent bundler to me.

How could we handle this? :)

**Comment by mischnic** [comment]
Yes, we are 😉 

They have also opened a few issues for the problems they've found:
https://github.com/parcel-bundler/parcel/issues/created_by/jakearchibald
https://github.com/parcel-bundler/parcel/issues/created_by/surma

Our unfinished documentation (https://v2.parceljs.org/) should also cover some of their "partial" ratings.

**Comment by kud** [comment]
Great!

Thank yo very much :)
