### ISSUE TITLE
Inline svg imports

### ISSUE THREAD

**Issue by alexreardon** [parcel-bundler/parcel#4829]
Hi there!

I am using parcel@2 and I am looking to inline some SVGs rather than just importing the path

Here is my current config:

```
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": [
      "@parcel/transformer-typescript-tsc"
    ],
    "*.svg": [
      "@parcel/transformer-raw"
    ]
  }
}
```

So I'm using the `transformer-raw`. Ideally I would use something like `transformer-string-inline` but that would already base64 encode the image

**Comment by mischnic** [comment]
Does `import x from "bundle-text:./logo.svg"` work for you?

**Comment by alexreardon** [comment]
Is there a way to do it with transformers in the config file? I am also using storybook which uses webpack, so ideally I don’t need to any anything to the import path

**Comment by alexreardon** [comment]
(I’ll also try your suggestion tomorrow)

**Comment by alexreardon** [comment]
I thought this might work, but no success:

```diff
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": [
      "@parcel/transformer-typescript-tsc"
    ],
    "*.svg": [
      "@parcel/transformer-raw"
    ]
  },
+  "optimizers": {
+    "*.svg": [
+      "@parcel/optimizer-data-url"
+    ]
  }
}
```

**Comment by alexreardon** [comment]
Sadly I could not get your suggestion to work

**Comment by christophz** [comment]
I have the exact same problem right now … would love to hear a solution for this.

**Comment by mischnic** [comment]
index.js:
```js
import svg from "./swim.svg";

console.log(svg);
```

parcelrc:
```json
{
	"extends": "@parcel/config-default",
	"transformers": {
		"*.svg": ["@parcel/transformer-inline-string", "..."]
	}
}
```

Output:
```js
(function () {
  ...
  var $c9cd9a05029e9b75462fe50fc01e00$exports = {};
  $c9cd9a05029e9b75462fe50fc01e00$exports = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SV...></svg>";
  ...
})();
```
