### ISSUE TITLE
parcel won't build if `module` field in package.json

### ISSUE THREAD

**Issue by meetmangukiya** [parcel-bundler/parcel#4833]
# 🐛 bug report

parcel won't build if there is a module field in package's package.json, it seems to interpret it incorrectly

## 🎛 Configuration (.babelrc, package.json, cli command)

command: `parcel build src/index.html`

## 🤔 Expected Behavior

It should build correctly.

## 😯 Current Behavior

```
meet@meet-laptop /t/final-cornerstone-react-component-example-with-config-for-webworkers> parcel build src/index.html
🚨 Build failed.
@parcel/core: Failed to resolve 'cornerstone-math' from './src/index.js'
/tmp/final-cornerstone-react-component-example-with-config-for-webworkers/src/index.js:7:34
  6 | import * as cornerstone from "cornerstone-core";
> 7 | import * as cornerstoneMath from "cornerstone-math";
>   |                                  ^^^^^^^^^^^^^^^^^^
  8 | import * as cornerstoneTools from "cornerstone-tools";
  9 | import Hammer from "hammerjs";
@parcel/resolver-default: Could not load './src/index.js' from module 'cornerstone-math' found in package.json#module
/tmp/final-cornerstone-react-component-example-with-config-for-webworkers/node_modules/cornerstone-math/package.json:17:13
  16 |   "license": "MIT",
> 17 |   "module": "src/index.js",
>    |             ^^^^^^^^^^^^^^ './src/index.js' does not existundefined'
  18 |   "repository": {
  19 |     "type": "git",
```
this is the error trace

## 💁 Possible Solution

Workaround was to remove the `module` field from `package.json` in the `node_modules/<package>/` directory, and if we would want to build this in CI, etc. we are going to need to fork these dependencies and remove ourselves, not ideal.

## 🔦 Context

Trying to build(`parcel build`). If it is of any relevance, development server works `parcel src/index.html`.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2 |
| Node             | v12.18.0 |
| npm/Yarn         | npm: 6.14.4, yarn: 1.22.4 |
| Operating System | linux |

P.S.: I may have wrongfully thought this was related to https://github.com/parcel-bundler/parcel/issues/4773. Checking https://github.com/nodejs/node-eps/blob/4217dca299d89c8c18ac44c878b5fe9581974ef3/002-es6-modules.md#51-determining-if-source-is-an-es-module and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules seems like they maybe related, not sure.. :sweat_smile: 

P.P.S.: Parcel is awesome :stars:

**Comment by meetmangukiya** [comment]
My initial guess was incorrect, it is not that parcel doesn't build if `module` field is provided. I checked the package, there was no `src/index.js` file which `module` field is referring to and which parcel tries to load. And hence, removing that field fixed the build. However, that was an accidental solution. 

However, the same thing is ignored if parcel 1 is used, i.e. parcel 1 ignores the module field or is not trying to include it. Either way not sure if this is a regression in parcel 2 or a bug in parcel 1. (This might be useful info either for parcel 1 or parcel 2)

The package in question -- cornerstone provides a `main` field that points to a built / bundled `dist/...js` file, and a `module` field that pointed to source. But the package published on npm is void of `src` directory.

**Comment by mischnic** [comment]
> The package in question -- cornerstone provides a main field that points to a built / bundled dist/...js file, and a module field that pointed to source. But the package published on npm is void of src directory.

This is obviously wrong.

Looking at
https://unpkg.com/browse/cornerstone-math@0.1.6/package.json and
https://unpkg.com/browse/cornerstone-math@0.1.7/package.json
it seems like `cornerstone-math@0.1.7` or newer should work

**Comment by meetmangukiya** [comment]
newer works :+1:
