### ISSUE TITLE
Feature request: Network throttle / artificial delay option for parcel serve

### ISSUE THREAD

**Issue by phaux** [parcel-bundler/parcel#4845]
# 🙋 Feature request

An option for `parcel serve` which enables network throttling or artificial delay for every request. This would be useful for testing apps with code splitting.

## 🤔 Expected Behavior

`parcel serve --net-delay 1` would add 1 second delay (maybe with some randomization) to every request's response time.

`parcel serve --net-bandwidth 100k` would limit network speed to 100 kilobytes per second.

It could also be smart and ignore requests for html and/or main js bundle, so that browser reloads are quicker.

## 😯 Current Behavior

No way to specify network throttling, other than using browser dev tools.

## 💁 Possible Solution

Implement the options.

## 🔦 Context

Firefox and Chrome dev tools have this feature, but it only supports limiting network speed. It makes you wait for the main bundle (which is usually huge when unoptimized) and only adds a tiny delay to other chunks (because they're usually small at early stage of development). It would be great if a delay could be added to every request, so that every load state for every chunk is clearly visible.

**Comment by mischnic** [comment]
> Firefox and Chrome dev tools have this feature, but it only supports limiting network speed. It makes you wait for the main bundle

In Chrome, You can specify a latency when creating a custom profile

<img width="786" alt="Bildschirmfoto 2020-07-11 um 22 56 22" src="https://user-images.githubusercontent.com/4586894/87233666-c6d65700-c3c9-11ea-98dc-6fc297a89019.png">
