### ISSUE TITLE
excludeNodeModules instead of includeNodeModules

### ISSUE THREAD

**Issue by 101arrowz** [parcel-bundler/parcel#4846]
# 🙋 feature request

The ability to use `excludeNodeModules` rather than `includeNodeModules` in each target config. Many more people need externals than need to forcibly bundle a specific module, so this seems like something that would semantically make sense.

## 🤔 Expected Behavior

```
{
  "targets": {
    "library": {
      "excludeNodeModules": {
        "react": true,
        "jquery": "$"
      }
    }
  }
}
```
A string value should be treated as the name of a global, while a boolean should be whether to keep the `require` or not (though, in my opinion, a value of `true` should cause an error in a browser build).

The same array syntax as `includeNodeModules` should be allowed, but only for exclusion of modules.

## 😯 Current Behavior

With `includeNodeModules`, not only are globals impossible, the syntax to exclude multiple (but not all) modules is cumbersome in comparison to a single array.

## 💁 Possible Solution

The Parcel source must already have some way to exclude any given node module. To add support for globals, Parcel must dynamically generate a fake dependency, i.e. to make `jquery` map to `$`, Parcel could create an asset with solely `module.exports=$`.

## 🔦 Context

This would fix #3305, which I have a similar use case for. Effectively, I'd like to emulate the behavior of [`parcel-plugin-externals`](https://github.com/FlorianRappl/parcel-plugin-externals).

**Comment by mischnic** [comment]
How does this differ from https://github.com/parcel-bundler/parcel/issues/3305?

**Comment by 101arrowz** [comment]
This is effectively the same but is meant to offer some sort of structure for implementation.

**Comment by mischnic** [comment]
What do you think about `"alias": {"jquery": {"global": "$"}}`? That would make sense (aliasing a package to a global variable), but it wouldn't be possible to specify per target.

**Comment by 101arrowz** [comment]
Suppose you're building an isomorphic package for both the browser and the server. You may want to use `pako` from a CDN in the browser (i.e. using a global) but require directly in the Node.js build. You would need some way to specify globals by target to make that work.

That's a niche use case, but I've personally experienced it in the past. In my opinion, `alias` should be the primary method of doing things, but optimally there should be a way to also specify in each target. Perhaps I'll implement both in my PR. Closing because this particular syntax (`excludeNodeModules`) won't be used.

**Comment by devongovett** [comment]
That makes sense. Maybe alias should also be supported per target?

**Comment by 101arrowz** [comment]
Target-specific aliases would be incredibly useful for library developers. Unfortunately, I'm not too familiar with the Parcel 2 codebase, so I don't think I'll be able to add target-specific aliasing in the PR but hopefully that could be done in the near future.

**Comment by decanTyme** [comment]
> That makes sense. Maybe alias should also be supported per target?

+1 to this. It would be beneficial for developers making a "browser-friendly" UMD bundle (alongside the usual esm and cjs) that maps some deps to globals from a CDN. Rollup [fully supports](https://rollupjs.org/configuration-options/#output-globals) this, and honestly this is tempting me to move to it altogether.

**Comment by devongovett** [comment]
That's already possible: https://parceljs.org/features/dependency-resolution/#global-aliases

**Comment by decanTyme** [comment]
> That's already possible: https://parceljs.org/features/dependency-resolution/#global-aliases

I've already tested this and it does this for all targets, am I correct? What I would like to happen is for just some select targets instead as I also output a main/module, but for some users that rely on a CDN and their globals, I also output a UMD that attaches itself so it is defined in `window`. Obviously without aliasing/externals it becomes a huge bundle since my package is a plugin that relies on two other packages.
