### ISSUE TITLE
Where can I see the change log?

### ISSUE THREAD

**Issue by chenym1992** [parcel-bundler/parcel#485]
parcel is great;
but i want to say  'Where can I see the change log?'(づ￣ 3￣)づ

**Comment by longility** [comment]
@chenym1992 It is being considered as seen in this issue: #138

**Comment by brandon93s** [comment]
The changelog is maintained here: https://github.com/parcel-bundler/parcel/blob/master/changelog.md

**Comment by chenym1992** [comment]
@brandon93s thx
