### ISSUE TITLE
Incorrect transpiled code when specifying engines.node >= 12.x

### ISSUE THREAD

**Issue by jogold** [parcel-bundler/parcel#4851]
# 🐛 bug report

Specifying `"node": ">= 12.x"` for a target with `"context": "node"` results in incorrectly transpiled code.

## 🎛 Configuration (.babelrc, package.json, cli command)

Given the following `package.json`
```json
{
  "node4": "node4/index.js",
  "node12": "node12/index.js",
  "targets": {
    "node4": {
      "context": "node",
      "engines": {
        "node": ">=4.x"
      },
      "minify": false
    },
    "node12": {
      "context": "node",
      "engines": {
        "node": ">=12.x"
      },
      "minify": false
    }
  },
}
```

and the following code for `index.js`
```js
const hello = require('./hello');

console.log(hello.sayHello());
```

and for `hello.js`:
```js
module.exports.hello = () => 'hello';

module.exports.sayHello = () => `Say ${this.hello()}`;
```

results in the following bundled/transpiled code for Node 4.x (working code)
```js
var $b6e224e90b159e88735cce5b1ef8b704$export$hello = function () {
  return 'hello';
};

var $b6e224e90b159e88735cce5b1ef8b704$export$sayHello = function () {
  return `Say ${$b6e224e90b159e88735cce5b1ef8b704$export$hello()}`;
};

console.log($b6e224e90b159e88735cce5b1ef8b704$export$sayHello());
```

and the following **incorrect code** for Node 12.x:
```js
var $b263a8e6c06539c203016879c52fc5c$export$sayHello = () => `Say ${this.hello()}`;

console.log($b263a8e6c06539c203016879c52fc5c$export$sayHello());
```

The minified code is:
```js
console.log((()=>"Say "+this.hello())());
```

==> `TypeError: this.hello is not a function`

## 🤔 Expected Behavior

The bundle for Node 12.x should contain valid code.

## 😯 Current Behavior

The bundle for Node 12.x contains invalid code.

`TypeError: this.hello is not a function`

## 🔦 Context

This is a trivial example of the problem but in production I'm using the module [`retry`](https://github.com/tim-kos/node-retry) that uses the same `this` pattern in its exports and I'm unable to bundle it when specifying `>= 12.x` for `engines.node`.

## 💻 Code Sample

Full repro at https://github.com/jogold/parcel-v2-engines-node-this

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1 |
| Node             | 12.18.0 |
| npm/Yarn         | 6.14.4 / 1.22.4 |
| Operating System | Ubuntu 20.04 |

**Comment by jogold** [comment]
The problem actually starts with `engines.node >= 6`. It's most probably due to a combination of babel preset env and how parcel rewrites `module.exports` statements.

**Comment by jogold** [comment]
The problem disappears with `--no-scope-hoist`... is scope hoisting a good default?

**Comment by mischnic** [comment]
This check is wrong:
https://github.com/parcel-bundler/parcel/blob/44a14ae76290115b3144120fd240939b64f6b93d/packages/shared/scope-hoisting/src/hoist.js#L299
arrow functions have a scope, but `this` should still be replaced..
