### ISSUE TITLE
bundle-text: causes inline source maps

### ISSUE THREAD

**Issue by jakearchibald** [parcel-bundler/parcel#4855]
# 🐛 bug report

When using `bundle-text:` on a source type that supports source maps (such as CSS), the source is inlined into the bundled text. This produces larger files in production.

## 🎛 Configuration (.babelrc, package.json, cli command)

https://github.com/GoogleChromeLabs/tooling.report/tree/parcel-updates/tests/non-js-resources/subtests/css/subtests/source/parcel

```js
import css from 'bundle-text:./styles.css';

const style = document.createElement('style');
style.textContent = css;
document.head.append(style);
```

```css
html {
  background: green;
}

h1 {
  color: white;
}
```

## 🤔 Expected Behavior

Either the sourcemap is removed, or becomes external.

```js
!function(){var e,t=document.createElement("style"),n=(e="html{background:green}h1{color:#fff}")&&e.__esModule?e.default:e;t.textContent=n,document.head.append(t)}();
//# sourceMappingURL=index.a3f3179f.js.map
```

## 😯 Current Behavior

```js
!function(){var e,t=document.createElement("style"),c=(e="html{background:green}h1{color:#fff}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJtYXBwaW5ncyI6IkFBQUEsS0FDQSxnQkFDQSxDQUVBLEdBQ0EsVUFDQSIsInNvdXJjZXMiOlsiLi9zcmMvc3R5bGVzLmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyJodG1sIHtcbiAgYmFja2dyb3VuZDogZ3JlZW47XG59XG5cbmgxIHtcbiAgY29sb3I6IHdoaXRlO1xufVxuIl0sIm5hbWVzIjpbXSwidmVyc2lvbiI6MywiZmlsZSI6ImluZGV4LkhBU0hfUkVGXzMxMjE0Y2I4ODM1NzdlNDYxMjVmMTg4ZWI5NGMzMTUwLmNzcy5tYXAifQ== */\n")&&e.__esModule?e.default:e;t.textContent=c,document.head.append(t)}();
//# sourceMappingURL=index.a3f3179f.js.map
```

## 💁 Possible Solution

Either the sourcemap is removed, or becomes external.

## 🔦 Context

The idea is to create an optimal build for production.

## 💻 Code Sample

https://github.com/GoogleChromeLabs/tooling.report/tree/parcel-updates/tests/non-js-resources/subtests/css/subtests/source/parcel

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | v12.16.1
| npm/Yarn         | npm 6.14.4
| Operating System | OSX 10.15.5

**Comment by DeMoorJasper** [comment]
This is already kind of tracked internally in height with **T-596**

Will fix this tomorrow or later today, seems like a fairly simple fix

**Comment by mischnic** [comment]
I guess sourcemaps should never be inlined? Inlining them somewhat defies their purpose of being able to debug a build that was deployed to production

This also happens woth inline script tags
```html
<script>
   import {add} from "lodash";
   console.log(add(1,2));
</script>
```

**Comment by jakearchibald** [comment]
Ah, sorry, I did search, but didn't find anything.

**Comment by mischnic** [comment]
It's not on Github (I noticed this issue a few days ago when preparing the list we reported to the tooling report 😉 )
