### ISSUE TITLE
Browserslist is ignored in Parcel v2 + TypeScript

### ISSUE THREAD

**Issue by takemyoxygen** [parcel-bundler/parcel#4866]
# 🐛 bug report

It looks like Parcel 2 provides a bundle incompatible with browsers listed in `.browserslistrc`

#### Package.json:
```
{
  "name": "parcel-browserslist",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {},
  "devDependencies": {
    "parcel": "^2.0.0-beta.1",
    "typescript": "^3.9.6"
  },
  "scripts": {
    "start": "parcel serve ./index.html"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```
#### .browserslistrc
```
defaults
ie 11
```

## 🤔 Expected Behavior
I expect the JS bundle to work in all browsers covered by `.browserslistrc`.

## 😯 Current Behavior

JS bundle assembled via `parcel serve` contains code incompatible with browsers that match `.browserslist`. e.g. it might contain object spread operator which is not supported in IE 11 and Edge 18. See the code sample below:

#### index.html
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>My Parcel Project</title>
  </head>

  <body>
    <div id="root"></div>
    <script src="./index.ts"></script>
  </body>
</html>
```

#### index.ts
```
const foo: any = {bar: 42};
const lol = {...foo};

console.log(lol);
```

(full source code of this example is available in https://github.com/takemyoxygen/playground/tree/master/js/parcel-browserslist)

After running `parcel serve ./index.html` in the `dist` folder there's a JS bundle which contains the following JavaScript:
```
const foo = {
  bar: 42
};
const lol = { ...foo
};
console.log(lol);
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-beta.1 
| Node             |v12.10.0
| npm/Yarn         |npm 6.10.3
| Operating System | Windows 10 1909

**Comment by mischnic** [comment]
This is by design because development is *usually* done on modern browsers. To override this, pass `--target` and specify a specific target:

`parcel serve index.html --target app`

(You also should remove `"main": "index.js",` from your package.json)
```json
{
  "name": "parcel-browserslist",
  "version": "1.0.0",
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "typescript": "^3.9.6"
  },
  "scripts": {
    "start": "parcel serve ./index.html"
  },
  "targets": {
    "app": {}
  }
}
```

**Comment by takemyoxygen** [comment]
Yes, indeed, specifying a target helped. Thanks!

**Comment by speigg** [comment]
Should this be a documentation bug then? I didn't find this information anywhere else.

**Comment by mischnic** [comment]
Yes, it's on our todo-list for the docs
