### ISSUE TITLE
Need web assembly 'application/wasm' MIME type for dev server.

### ISSUE THREAD

**Issue by kevzettler** [parcel-bundler/parcel#4867]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc
```js
{
  "presets": []
}
```
package.json
```js
{
  "name": "radcab",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@babel/preset-env": "^7.10.4",
    "parcel-bundler": "^1.12.4",
    "typescript": "^3.9.6"
  },
  "scripts": {
    "dev": "tsc src/index.ts --noEmit && parcel public/index.html",
    "build": "tsc src/index.ts --noEmit && parcel build public/index.html"
  }
}
```

cli command:
`npm run dev`

## 🤔 Expected Behavior

dev server at localhost:123 should return `'application/wasm'` MIME type for `.wasm` responses

## 😯 Current Behavior 
It returns  `text/html` mime type instead

![Screenshot 2020-07-09 15 09 10](https://user-images.githubusercontent.com/126209/87095820-4f9c9980-c1f6-11ea-842e-abaa538a9b0d.png)

## 💁 Possible Solution

 return `'application/wasm'` MIME type for `.wasm` responses.

## 🔦 Context

![Screenshot 2020-07-09 15 08 25](https://user-images.githubusercontent.com/126209/87095831-55927a80-c1f6-11ea-81b3-6aaa7a80ecba.png)

## 💻 Code Sample

A webassembly include is currently failing

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | v10.13.0
| npm/Yarn         | 0.34.0
| Operating System | Darwin kevs-mbp.lan 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

**Comment by Banou26** [comment]
Same result with `^2.0.0-nightly.385`

**Comment by mattbieber** [comment]
Any word on this?

**Comment by mischnic** [comment]
I've just tested this with Parcel 2 master (= parcel@2.0.0-nightly.395):

```html
<script src="index.js"></script>
```
```js
import wasm from "url:./test.wasm";

fetch(wasm);
```
(an empty file named `test.wasm`)

```sh
$ curl -v localhost:1234/test.f25a59d6.wasm
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 1234 (#0)
> GET /test.f25a59d6.wasm HTTP/1.1
> Host: localhost:1234
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, HEAD, PUT, PATCH, POST, DELETE
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Content-Type
< Content-Length: 0
< Content-Disposition: inline; filename="test.f25a59d6.wasm"
< Accept-Ranges: bytes
< Last-Modified: Wed, 09 Sep 2020 21:50:03 GMT
< Content-Type: application/wasm
< Date: Wed, 09 Sep 2020 21:50:13 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
* Connection #0 to host localhost left intact
* Closing connection 0
```

Seems to be correct.

**Comment by mattbieber** [comment]
cool, thanks @mischnic I'll try v2

**Comment by jessep** [comment]
I believe this is still an issue. When you `import` a `.wasm` file it is fine, but if you, say, fetch one from your root directory, it isn't. The mimetype appears to be `html` still.

I'm running into the issue with sql.js, where it looks for the file and requests it manually itself based on the dir you give it.

**Comment by HarikrishnanBalagopal** [comment]
> I believe this is still an issue. When you `import` a `.wasm` file it is fine, but if you, say, fetch one from your root directory, it isn't. The mimetype appears to be `html` still.
> 
> I'm running into the issue with sql.js, where it looks for the file and requests it manually itself based on the dir you give it.

This is still a problem when doing `npx parcel src/index.html` as shown in the tutorial https://parceljs.org/getting-started/webapp/
<img width="865" alt="image" src="https://user-images.githubusercontent.com/20921177/162693765-483a76f3-daf5-4d13-a077-e23067000cd9.png">

**Comment by mischnic** [comment]
> This is still a problem when doing npx parcel src/index.html as shown in the tutorial [parceljs.org/getting-started/webapp](https://parceljs.org/getting-started/webapp/)

This is because the server can't find the main.wasm file and instead of returning an 404, it falls back to the index.html file.

**Comment by Barmanjii** [comment]
### If anyone is still using the V1 of Parcel then do this.
There is one way around it - I have used Parcel - 1.12.5 for this
1. Create your `.wasm` or use, if you already have it.
2. Now serve the `index.html` using `parcel serve index.html` it'll create the dist folder inside the dir wherever you are, so check the Developer network tool if the `.wasm` is still the HTML / Text copy your `.wasm` into the `dist` which is created by the `parcel` and reload it.

That's it, folks... hope this help. :smile:

**Comment by antoooooooooooonie** [comment]
> I believe this is still an issue. When you `import` a `.wasm` file it is fine, but if you, say, fetch one from your root directory, it isn't. The mimetype appears to be `html` still.
> 
> I'm running into the issue with sql.js, where it looks for the file and requests it manually itself based on the dir you give it.

This is still an issue it seems (Parcel 2.11.0)

<img width="687" alt="Screenshot 2024-01-19 at 15 20 02 copy" src="https://github.com/parcel-bundler/parcel/assets/71470021/a4a249ed-9806-4b8c-9288-460a230e613a">

**Comment by Vico1993** [comment]
> This is still an issue it seems (Parcel 2.11.0)

Does someone have a fix, it seems like every time I include an HTML file in my parcel command, for all my files my MIME type is `text/html`. 
Even for **javascript** files and **css** files

**Comment by barman-peppermint** [comment]
Sorry for the late reply, but you can try my method just put them .wasm file into the dist directory and it should work. with V2 parcel.
