### ISSUE TITLE
Request: @parcel/optimizer-data-url additionally encode "-_.!~*'()"

### ISSUE THREAD

**Issue by sogaani** [parcel-bundler/parcel#4872]
# 🙋 feature request
@parcel/optimizer-data-url encode the caracters [`-_.!~*'()`] that [`encodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) does not encode.

## 🤔 Expected Behavior and 💻 Examples

`svg` files that contain `filter=url()` can be attached to `css` as a data url format and can be decoded by browsers  

``` css
.svgClass {
  background-image: url(data-url:../img/hoge.svg)
}
```
* hoge.svg contains `filter=url()`

## 😯 Current Behavior

`svg` files that contain `filter=url()` can be attached to css but it failed to be decoded on browsers because it contains unescaped characters `()`.

## 💁 Possible Solution

As [`MDN`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) suggests, we can use the following custom encode method so that data url encode is to be more stringent in adhering to RFC 3986.
```
function fixedEncodeURIComponent(str) {
  return encodeURIComponent(str).replace(/[!'()*]/g, function(c) {
    return '%' + c.charCodeAt(0).toString(16);
  });
}
```

* current workaround
I develop an optimizer encoding brackets`()` and use an optimizer pipeline to accomplish expected behavior.
```
{
  "extends": "@parcel/config-default",
  "optimizers": {
    "data-url:*": ["...", "parcel-optimizer-data-url-round-bracket"]
  }
}
```

**Comment by mischnic** [comment]
Could you open a PR to include your changes directly in `@parcel/optimizer-data-url`?
