### ISSUE TITLE
🙋 Watch pre-transform HTML files

### ISSUE THREAD

**Issue by ipmb** [parcel-bundler/parcel#488]
Consider a posthtml setup like the test case where `index.html` includes `other.html` https://github.com/parcel-bundler/parcel/blob/e0e231e359223343c0333013aeac4e4952fa7324/test/integration/posthtml/index.html

### 🤔 Expected Behavior

When I save a change to `other.html` while running `parcel index.html`, the page updates.

### 😯 Current Behavior

Parcel does not identify a change because it is not watching `other.html`, only `index.html`.

### 🌍 Your Environment=

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.4.1
| Node             |  v9.3.0
| npm/Yarn         | 1.3.2
| Operating System | MacOS

**Comment by dfang** [comment]
same here

**Comment by Alamantus** [comment]
This would also be a nice feature for `@import` directives in postCSS files as well. Parcel seems to only watch imports from Javascript files.

**Comment by shawwn** [comment]
I wonder if we could simply traverse all HTML attributes and try to see if any of them match a file on disk?

E.g. 

```
<!doctype html>
<html>
<body>
    <include src="other.html"></include>
</body>
</html>
```

Or we could manually add various HTML tags one by one.

**Comment by devongovett** [comment]
This would require Parcel to know about all possible non-standard syntax supported PostHTML plugins. Ideally there would be a way for PostHTML plugins to emit dependencies to Parcel (and other bundlers) instead.

Actually, this may be possible. Looking at the webpack posthtml-loader, it seems to handle `dependency` messages. Maybe we can do the same?
