### ISSUE TITLE
No transformers found for shaders (WebGL)

### ISSUE THREAD

**Issue by ivanfemia** [parcel-bundler/parcel#4891]
# 🐛 bug report

My index.html includes two shaders  

## 🎛 Configuration (.babelrc, package.json, cli command)

```
{
  "name": "myapp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "parcel --open --no-cache --no-hmr src/index.html ",
    "build": "bash scripts/deploy.sh",
    "build:parcel": "parcel build src/index.html --out-dir dist --public-url ./ --no-minify",
    "dist": "http-server dist -p 8080"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.2.2",
    "babel-plugin-transform-runtime": "^6.23.0",
    "eslint": "^4.18.2",
    "http-server": "^0.11.1",
    "parcel": "^2.0.0-beta.1",
    "stylus": "^0.54.5"
  },
  "dependencies": {
    "@tweenjs/tween.js": "^17.2.0",
    "npm": "^5.7.1",
    "random-spherical": "^1.1.2",
    "three": "^0.91.0",
    "three-orbit-controls": "^82.1.0",
    "to": "^0.2.9",
    "update": "^0.7.4"
  }
}
```

## 🤔 Expected Behavior

The build completes successfully

## 😯 Current Behavior

Parcel stops with the following error

> parcel --open --no-cache --no-hmr src/index.html

ℹ️ Server running at http://localhost:1234
🚨 Build failed.
Error: No transformers found for "/Users/uname/Code/webapp/myapp/src/index.x-vertex".

Error: No transformers found for "/Users/uname/Code/webapp/myapp/src/index.x-vertex".
    at ParcelConfig._getTransformerNodes (/Users/uname/Code/webapp/myapp/node_modules/@parcel/core/lib/ParcelConfig.js:157:13)
    at ParcelConfig.getTransformerNames (/Users/uname/Code/webapp/myapp/node_modules/@parcel/core/lib/ParcelConfig.js:164:29)
    at ConfigLoader.loadParcelConfig (/Users/uname/Code/webapp/myapp/node_modules/@parcel/core/lib/ConfigLoader.js:82:37)
    at /Users/uname/Code/webapp/myapp/node_modules/@parcel/core/lib/ConfigLoader.js:54:48
    at async PromiseQueue._runFn (/Users/uname/Code/webapp/myapp/node_modules/@parcel/utils/lib/PromiseQueue.js:98:7)
    at async PromiseQueue._next (/Users/uname/Code/webapp/myapp/node_modules/@parcel/utils/lib/PromiseQueue.js:85:5)

## 🔦 Context

build the app

## 💻 Code Sample

```
<script id="vertexShader" type="x-shader/x-vertex">
</script>
<script id="fragmentShader" type="x-shader/x-fragment">
</script>
```

## 🌍 Your Environment

 Parcel 2.0.0.beta1
  System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Safari: 13.1.1

**Comment by StevenStavrakis** [comment]
This bug persists

**Comment by devongovett** [comment]
Not sure this is really a bug? "x-shader/x-vertex" isn't a real mime type, so I'm not sure how parcel would know what to do with it. Using the file extension (e.g. `glsl`/`vert`/`frag`) should work:

```html
<script type="vert">
  ...
</script>
```

**Comment by charlieroberts** [comment]
The preferred MIME type for shaders is `text/plain` which is also not supported by Parcel. `vert` and `frag` work (thank you for pointing this out!) but that seems non-standard at best... anyways, I would assume this isn't a high priority, but the workaround could be worth mentioning on the GLSL transformer page.
