### ISSUE TITLE
Parcel 2 eagerly reads package.json#main

### ISSUE THREAD

**Issue by Andarist** [parcel-bundler/parcel#4895]
# 🐛 bug report

I was struggling a little bit if I should classify this as a bug - but this has worked with Parcel 1, there are no docs on how this use case can be achieved now and I've tried a bunch of different things to work around this and couldn't make it work.

## 🤔 Expected Behavior

Being able to build an example of a library without Parcel throwing with:
> 🚨 Build failed.
> @parcel/namer-default: Target "main" declares an output file path of "dist/react-textarea-autosize.cjs.js" which does not match the compiled bundle type "html".
> /react-textarea-autosize/package.json:17:11
>   16 |   "license": "MIT",
> 17 |   "main": "dist/react-textarea-autosize.cjs.js",
> |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Did you mean "dist/react-textarea-autosize.cjs.html"?
>   18 |   "module": "dist/react-textarea-autosize.esm.js",
>   19 |   "browser": {

## 😯 Current Behavior

It throws with this suggestion 😉 when trying to build an example for a library for a very [simple script](https://github.com/Andarist/react-textarea-autosize/blob/25028f42778f1e2f00c83ed57eef16223a468d3b/package.json#L35):
```
parcel build ./example/index.html --dist-dir ./example/dist --public-url .
```

## 🔦 Context

It has affected me when trying to migrate from Parcel 1 to Parcel 2.

## 💻 Code Sample

The project and the whole setup can be seen here:
https://github.com/Andarist/react-textarea-autosize/tree/25028f42778f1e2f00c83ed57eef16223a468d3b

I've even tried to add a dummy `package.json` in `example` directory but Parcel 2 still tries to apply `@parcel/namer-default` and related logic based on the root `package.json`.

**Comment by mischnic** [comment]
You could add a target for the example and specify it when running Parcel so that it doesn't try to use `main:`
```json5
{
	...,
	"targets": { "example": {} }
}
```
`parcel build ./example/index.html --dist-dir ./example/dist --public-url . --target example `

**Comment by Andarist** [comment]
@mischnic thank you for the answer! Truth to be told - I don't find this to be particularly intuitive. I applaud the 0-config approach by default though - so I understand that you have to operate on a convention-first basis and I might just not be familiar with the convention used here.

I've started to write some feedback about this but I've ditched it for now because I've realized that there is still some issue with my setup and I can't figure it out - knowing the answer for it would probably change my feedback or at least the understanding of conventions used here.

The problem is that somehow [this script](https://github.com/Andarist/react-textarea-autosize/blob/6012451efada9f553c46c11f2a01de75310f16b4/package.json#L38) based on this [`<script/>`](https://github.com/Andarist/react-textarea-autosize/blob/6012451efada9f553c46c11f2a01de75310f16b4/example/index.html#L20) doesn't load `./example/index.tsx` (or it loads it but removes it completely) but rather `./src/index.tsx`.

**Comment by mischnic** [comment]
Not sure if this was already the case at the time, but another option is 

```json
{
  "main": "unrelated.js",
  "targets": {
    "main": false
  }
}
```
https://v2.parceljs.org/configuration/package-json/#main-%2F-module-%2F-browser

**Comment by Andarist** [comment]
After your comment I've tried this but it didn't bundle dependencies (`require` calls were left in the bundle). However, I've attempted to just use a nested `package.json` with the latest nightly build and it works now 🎉 :
https://github.com/Andarist/react-textarea-autosize/commit/5ff8ed781e59dd6d5f1af224e5ace6d3ae58f8ad#diff-a593fc14fdef41aaf092f774b92cb74bafeda3e9559f8ae4762374bf4af80c92R1-R7

It seems that in the meantime the logic around this has changed and it doesn't happen anymore:
> I've even tried to add a dummy package.json in example directory but Parcel 2 still tries to apply @parcel/namer-default and related logic based on the root package.json.

**Comment by mischnic** [comment]
> require calls were left in the bundle

(Might be because you have `engines: {node: ...}` set or something like that)
