### ISSUE TITLE
Parcel 2, Typescript lib includes not respected? Promise, async/await

### ISSUE THREAD

**Issue by kevzettler** [parcel-bundler/parcel#4898]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```
$ parcel --version
2.0.0-nightly.339
```

`.parcelrc`
```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  },
  "validators": {
    "*.{ts,tsx}": ["@parcel/validator-typescript"]
  }
}

```

tsconfig.json
```
{
  "lib": ["dom", "es2015"],
  "include": ["src/**/*"]
}
```

*package.json*
```
{
  "name": "radcab",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "NODE_ENV=dev parcel src/index.html --no-cache",
    "build": "NODE_ENV=prod parcel build src/index.html"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@babel/preset-env": "^7.10.4",
    "@types/dropboxjs": "0.0.28",
    "@types/filesystem": "0.0.29",
    "@types/node": "~7.0",
    "browserfs": "^1.4.3",
    "typescript": "^3.9.6"
  },
  "devDependencies": {
    "@parcel/transformer-typescript-tsc": "^2.0.0-beta.1",
    "@parcel/validator-typescript": "^2.0.0-beta.1",
    "parcel": "^2.0.0-beta.1"
  }
}
```

## 🤔 Expected Behavior
Parcel should be-able to handle typescript that uses `async/await` keywords and has dependent libs 

## 😯 Current Behavior

```
$ npm run dev

> radcab@1.0.0 dev /Users/kevzettler/code/radcab
> NODE_ENV=dev parcel src/index.html --no-cache

ℹ️ Server running at http://localhost:1234
🚨 Build failed.
@parcel/validator-typescript: Cannot find global value 'Promise'.
@parcel/validator-typescript: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
/Users/kevzettler/code/radcab/src/index.ts:107:16
  106 |
> 107 | async function loadDosBox(){
>     |                ^^^^^^^^^^^ An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
  108 |   /* const zipRes = await window.fetch('./dosbox/dosx-doom.zip')
  109 |    * const zipABuff = await zipRes.arrayBuffer();
```
## 💁 Possible Solution

possible Parcel is not respecting the `lib` property of `tsconfig.json`

## 🔦 Context

cannot write simple async/await typescript code

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.339
| Node             | v10.13.0
| npm/Yarn         |npm 6.14.6
| Operating System | Darwin kevs-mbp.lan 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

**Comment by kevzettler** [comment]
If I remove the `--no-cache` flag the problem becomes intermittent. It will fail on the first time I run `npm run dev` then if I run it again it will build. But then if I change code and the dev server automatically reloads it fill fail again.

**Comment by mischnic** [comment]
The tsconfig loading is probably wrong.

> If I remove the --no-cache flag the problem becomes intermittent.

This is because at the moment, validators only run that file changed and eventual errors aren't somehow saved into the cache. So rebuilding without changes means no validators run and therefore no errors are thrown. We do plan to fix this

**Comment by kevzettler** [comment]
yes I needed `compilerOptions` in the tsconfig my mistake
