### ISSUE TITLE
🙋 work with test framework like jest

### ISSUE THREAD

**Issue by vincent178** [parcel-bundler/parcel#490]
Thanks for the great project!

I'd like to ask that how this project works with a test framework like jest?

Can you provide an example for this?

Thanks

**Comment by bickmista** [comment]
Install babel-jest from npm and it will read your .babelrc  file. No need to run it through parcel ☺️

**Comment by vincent178** [comment]
@bickmista thanks for your reply. 

When we're talking about the react project with parcel, I don't think it would work only with babel-jest, and in the meantime, the parcel already works for the bundle all the assets, can we leverage this ability for test purpose, and avoid to configure separately for test.

**Comment by bickmista** [comment]
@vincent178 No problem.

Looking at the Jest docs it looks like they offer limited help when integrating with webpack, But for assets it looks like they recommend mocking them rather than processing them. See here for more information: https://facebook.github.io/jest/docs/en/webpack.html#handling-static-assets.

Hope that helps / Sorry if i haven't quite understood your question

**Comment by vincent178** [comment]
Sorry for the unclear question. 

I have tested for integrating jest using parcel as the bundle solution, the jest provide a util to preprocess all the files before it run the tests, for example, ts integrate with jest (https://github.com/facebook/jest/tree/master/examples/typescript). In this preprocess case, it requires the preprocess to be run synchronously. While it looks like parcel only provide an async way to bundle/transform assets.

Do you think we can provide an synchronous api to transform all the assets?

Thanks.

**Comment by papaponmx** [comment]
I think I'll be moving to rollup. But pls let me know if you find a way to make them play nice

**Comment by kylemh** [comment]
As another use-case:

I'd like to use modern JavaScript inside my test files (such as `import`) for a simple node script on a take-home assignment. React isn't involved here and I didn't need a `.babelrc` - default Parcel was enough.

How can I get Jest to consume it's files using Parcel-transpiled code?

**Comment by JRJurman** [comment]
Not sure if people are still having issues with this, but after a couple of hours of tinkering around, I was able to get a `package.json` that ran with both parcel and jest as expect. I'm putting this here for anybody else who might also want such a configuration:

```json
{
  "scripts": {
    "start": "parcel index.html --open",
    "build": "parcel build index.html",
    "test": "jest --watch"
  },
  "dependencies": {
    "@babel/core": "7.2.0",
    "@babel/preset-env": "^7.4.5",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "jest-transform-stub": "^2.0.0",
    "parcel-bundler": "^1.6.1",
    "sass": "^1.20.1"
  },
  "babel": {
    "presets": ["@babel/preset-env"]
  },
  "jest": {
    "transform": {
      ".+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$": "jest-transform-stub",
      "^.+\\.js$": "babel-jest"
    }
  }
}
```

These configurations worked for a vanilla JS project that was using import and export syntax, and scss imports. If you are using `.jsx` or `.ts`, you may need to change the jest transform to process those files for `babel-jest` (if it can process it, which I believe it can). The `jest-transform-stub` basically tells jest to ignore css imports, which is more-or-less what you want to have happen for unit tests, so this functionality it ideal.

**Comment by Taxi4you** [comment]
Yes but it doesn't work when working with absolute paths..

**Comment by junwen-k** [comment]
Here assuming that you are using [`babel-jest`](https://www.npmjs.com/package/babel-jest) to compile your React code. To avoid parcel from using the `babel` config on your project root, you can write a custom script just for `jest`, for example. 

`babelJest.js`
```js
module.exports = require('babel-jest').createTransformer({
  presets: ['@babel/preset-env', '@babel/preset-react'],
});
```

And in your jest config (`package.json` or `jest.config.json` etc)
```json
{
  ...
  "transform": {
    "^.+\\.(js|jsx|mjs|cjs|ts|tsx)$": "<rootDir>/babelJest.js",
    ...
  },
  ...
}
```

The `babel` config will only apply for jest during testing. Parcel compiling will not be affected in this case. Hopefully it helps :)

**Comment by astridlyre** [comment]
I made a starter for anyone who, like me, struggled getting jest to work with parcel and react: https://github.com/astridlyre/react-jest-parcel-starter

**Comment by LnsooXD** [comment]
> Here assuming that you are using [`babel-jest`](https://www.npmjs.com/package/babel-jest) to compile your React code. To avoid parcel from using the `babel` config on your project root, you can write a custom script just for `jest`, for example.
> 
> `babelJest.js`
> 
> ```js
> module.exports = require('babel-jest').createTransformer({
>   presets: ['@babel/preset-env', '@babel/preset-react'],
> });
> ```
> 
> And in your jest config (`package.json` or `jest.config.json` etc)
> 
> ```json
> {
>   ...
>   "transform": {
>     "^.+\\.(js|jsx|mjs|cjs|ts|tsx)$": "<rootDir>/babelJest.js",
>     ...
>   },
>   ...
> }
> ```
> 
> The `babel` config will only apply for jest during testing. Parcel compiling will not be affected in this case. Hopefully it helps :)

Thank you for your help. But now to make `babelJest.js` work, adding a `.default` after `require` is needed. 

`babelJest.js`

```javascript
module.exports = require('babel-jest').default.createTransformer({
  presets: ['@babel/preset-env', '@babel/preset-react'],
});
```
