### ISSUE TITLE
Elm: `ReferenceError: document is not defined` when using Platform.worker in a Service Worker

### ISSUE THREAD

**Issue by baffalop** [parcel-bundler/parcel#4905]
# 🐛 bug report

I'm using Elm's [`Platform.worker`](https://package.elm-lang.org/packages/elm/core/latest/Platform#worker) (a headless Elm instance) within a Service Worker in a PWA. When I run the Parcel dev server for my app, I run into `ReferenceError: document is not defined` tracing to the function `wrapPublicModule` in the compiled `sw.js`. It seems this function is very keen to find a DOM node to use as the `node` parameter for Elm, even when I do not want to provide one.

## 🎛 Configuration (.babelrc, package.json, cli command)

```
parcel ./src/index.html --cert server.crt --key server.key
```

No Babel config. I do have `"browserslist": [ "since 2017-06" ]` in my `package.json` to prevent polyfilling async/await.

I have not tested with build yet as I'm not set up to serve the bundle with https. Judging by the comments in the served source file, it might well be that the compiled output from build will work differently.

## 🤔 Expected Behavior

`init` for a `Platform.worker` Elm application doesn't expect a `node` argument. When I omit this, no calls to `document` should be made, to avoid errors in various execution contexts.

## 😯 Current Behavior

When I call `init()` on my Elm element within an install event handler, I see the following error:

```
sw.js:4606 Uncaught (in promise) ReferenceError: document is not defined
    at Object.init (sw.js:4606)
    at sw.js:91
    at new Promise (<anonymous>)
    at fetchPlaylist (sw.js:87)
    at cacheOnInstall (sw.js:71)
    at sw.js:57
```

When I click through to `sw.js:4606` I see this function:

```js
function wrapPublicModule(path, module) {
    var originalInit = module.init;
    if (originalInit) {
        module.init = function (args) {
            var elm;
            var portSubscribes = {};
            var portSends = {};
            var domNode = null;
            var flags = null;
            if (typeof args !== 'undefined') {
                // normal case
                domNode = args['node'] && !isFullscreenApp()
                    ? wrapDomNode(args['node'])
                    : document.body;
                flags = args['flags'];
            } else {
                // rare case: Elm allows init to be called without any arguments at all
                domNode = document.body;
                flags = undefined
            }
            initializingInstance = registerInstance(domNode, flags, path, portSubscribes, portSends);
            elm = originalInit(args);
            wrapPorts(elm, portSubscribes, portSends);
            initializingInstance = null;
            return elm;
        };
    } else {
        console.error("Could not find a public module to wrap at path " + path)
    }
}
```

It looks like no matter which arguments I provide, a call to `document` is made at some point. Apparently my use case falls into the "rare case" category 😉 – but it's also the case that when init is called without any arguments at all for `Platform.worker`, you really don't need to reach for a DOM node.

For reference, `wrapDomNode` looks like this:

```js
function wrapDomNode(node) {
    // When embedding an Elm app into a specific DOM node, Elm will replace the provided
    // DOM node with the Elm app's content. When the Elm app is compiled normally, the
    // original DOM node is reused (its attributes and content changes, but the object
    // in memory remains the same). But when compiled using `--debug`, Elm will completely
    // destroy the original DOM node and instead replace it with 2 brand new nodes: one
    // for your Elm app's content and the other for the Elm debugger UI. In this case,
    // if you held a reference to the DOM node provided for embedding, it would be orphaned
    // after Elm module initialization.
    //
    // So in order to make both cases consistent and isolate us from changes in how Elm
    // does this, we will insert a dummy node to wrap the node for embedding and hold
    // a reference to the dummy node.
    //
    // We will also put a tag on the dummy node so that the Elm developer knows who went
    // behind their back and rudely put stuff in their DOM.
    var dummyNode = document.createElement("div");
    dummyNode.setAttribute("data-elm-hot", "true");
    dummyNode.style.height = "inherit";
    var parentNode = node.parentNode;
    parentNode.replaceChild(dummyNode, node);
    dummyNode.appendChild(node);
    return dummyNode;
}
```

Which provides a very reasonable rationale for most Elm apps. However, I doubt `Platform.worker` injects any debug interface given it's expressly headless. The comment also leads me to believe that running `parcel build` might not have these wrappers in place, but even if this is the case, I'd like to be able to use the Parcel dev server to test my PWA's service worker.

## 💁 Possible Solution

Do not call `document.body` in the "rare case" else clause. Of course, this would mean not passing a DOM node to `registerInstance`, and I'm not sure how deep it goes after that.

## 🔦 Context

In my Service Worker's install event, I need to dynamically cache a subset of my assets, according to some values planted in indexedDB when my app is first loaded. The logic to retrieve these values is common to my main Elm app and this install event, so it would help to share some modules between the main app and a `ServiceWorkerHelper.elm`.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.4 |
| Node             | 13.12.0 |
| npm/Yarn         | npm 6.14.4 |
| Operating System | macOS 10.15.4 |
| Browser | Chrome 83 |

**Comment by mischnic** [comment]
I'm not familiar with elm, but Parcel doesn't inject anything itself and merely calls `node-elm-compiler`: https://github.com/parcel-bundler/parcel/blob/939ce4196082e15c836f8a0fe7d07bd2cc041d20/packages/core/parcel-bundler/src/assets/ElmAsset.js#L74

**Comment by baffalop** [comment]
@mischnic Ah apologies. I didn't realise how many layers were involved here. Through a code search I've found the source of this in `NoRedInk/jetpack` but can't even establish a link from that to `rtfeldman/node-elm-compiler`. I guess I'll try an issue in one of those two repositories...
