### ISSUE TITLE
No .parcelrc with .babelrc fails on TSX

### ISSUE THREAD

**Issue by 101arrowz** [parcel-bundler/parcel#4919]
# 🐛 bug report

Without using `@parcel/transformer-typescript-tsc`, babel cannot parse JSX in `.tsx` files.

## 🎛 Configuration (.babelrc, package.json, cli command)

`.babelrc`:
```json
{
  "presets": ["@parcel/babel-preset-env"]
}
```

`index.html`:
```html
<!DOCTYPE html>
<html lang="en">
<body>
  <div id="root"></div>
  <script src="index.tsx"></script>
</body>
</html>
```
`index.tsx`:
```tsx
import React from 'react';
import { render } from 'react-dom';

render(<div>Hello World!</div>, document.getElementById('root'));
```

## 🤔 Expected Behavior

Running `parcel build src/index.html` bundles properly.

## 😯 Current Behavior
```
🚨 Build failed.
@parcel/transformer-babel: Support for the experimental syntax 'jsx' isn't currently enabled (4:8):
```

## 🔦 Context

I'm trying to port a Parcel 1 project to Parcel 2. That project has only TSX files.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | nightly (2.0.0-nightly.349)
| Node             | latest (14.05)
| npm/Yarn         | latest (yarn@1.22.4)
| Operating System | Ubuntu 18.04 LTS on WSL 2

**Comment by mischnic** [comment]
Works for me. Are you using a custom `.parcelrc`?

> Use @parcel/transformer-typescript-tsc by default

That's a different discussion....

**Comment by 101arrowz** [comment]
As I said, I tried the default no-config setup. I'll try to create a reproducible example.

**Comment by 101arrowz** [comment]
Never mind, this was zero-config for Parcel, but I had a .babelrc. I'll update the original issue

**Comment by mischnic** [comment]
This is by design. Parcel 2 uses a user provided `.babelrc` unmodified, setting it to `{ "presets": "@parcel/babel-preset-env" }` would work as expected.

**Comment by 101arrowz** [comment]
I still have a problem where Parcel doesn't invalidate the cache upon an update to `.babelrc`; should I file a separate issue or is that a known bug?

**Comment by 101arrowz** [comment]
Well, actually, even that doesn't work for me for some reason, even after clearing the cache.

**Comment by mischnic** [comment]
I'm sorry, I mixed something up: the only thing `@parcel/babel-preset-env` does at the moment is forwarding the browserslist and `modules: false`.

But ideally that preset would provide most of Parcel's default babel config (but I'm not sure if everything is even possible inside a preset).
