### ISSUE TITLE
The wrapped module seems to have the same name, resulting in access to the incorrect module.

### ISSUE THREAD

**Issue by 2234839** [parcel-bundler/parcel#4921]
# 🐛 bug report

![图片](https://user-images.githubusercontent.com/28727933/88159527-ff82f580-cc3f-11ea-8a26-db6a745c8927.png)

My code was reporting an error when accessing a module, and I interrupted to check to see that the variable was actually another module of the same name.

ubuntu packaging error, windos is normal

## 🎛 Configuration (.babelrc, package.json, cli command)

 See this https://github.com/2234839/userJS

## 🤔 Expected Behavior

The code is accessing the incorrect module

## 🔦 Context

I'm trying to access this module and I'm accessing another module.

## 🌍 Your Environment

https://github.com/2234839/userJS

step:
```
npm i
parcel build --no-minify --no-source-maps .\api自动提取\api自动提取.user.ts

## open file dist\api自动提取.user.js

```

Perform the same operation under windows and ubuntu.

ubuntu:
![图片](https://user-images.githubusercontent.com/28727933/88160762-b2a01e80-cc41-11ea-8002-8f949d43ae82.png)

windows: 
![图片](https://user-images.githubusercontent.com/28727933/88160841-ce0b2980-cc41-11ea-9866-25dae2275016.png)

I don't know exactly why, but I'm guessing there's a problem with the handling of Chinese paths in ubuntu.

**Comment by mischnic** [comment]
Probably duplicate of https://github.com/parcel-bundler/parcel/issues/3823, https://github.com/parcel-bundler/parcel/issues/3747, https://github.com/parcel-bundler/parcel/pull/4800
