### ISSUE TITLE
UMD export default module not correct

### ISSUE THREAD

**Issue by shahen94** [parcel-bundler/parcel#4922]
# 🐛 bug report

Created library and in `index.ts` I exported it as

![image](https://user-images.githubusercontent.com/13334788/88168587-b32dba80-cc2b-11ea-8f0c-ed6bd6230125.png)

![image](https://user-images.githubusercontent.com/13334788/88168621-bd4fb900-cc2b-11ea-8816-0037990fbc65.png)

## 🤔 Expected Behavior

It should be accessible via `new Ambasador` instead of `new Ambasador.default`

## 😯 Current Behavior

![image](https://user-images.githubusercontent.com/13334788/88168698-d6586a00-cc2b-11ea-9ca2-cd1acef5f58b.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.4
| Node             | 13
| npm/Yarn         | 6.14.4
| Operating System | MacOS Catalina

**Comment by mischnic** [comment]
do this instead:
```js
import ....;

module.exports = Ambasador;
```

**Comment by shahen94** [comment]
In that case, de can't export enums/interfaces from the module

```
export { AuthEnum, EventsEnum };
module.exports = Ambasador;
```

AuthEnum and EventsEnum are undefined

**Comment by mischnic** [comment]
> enums/interfaces

TS interfaces don't exist at runtime, they are removed when building: https://www.typescriptlang.org/play/#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgMQgjgG84BfAKEtEljmwBtMBnFuAIUykQFsxGwXsBTtCxEuSA

**Comment by shahen94** [comment]
Enums should work anyway

![image](https://user-images.githubusercontent.com/13334788/88197332-5c3bdb80-cc53-11ea-8f71-d16c94561e3c.png)

**Comment by shahen94** [comment]
and they are working before using `module.exports` as a solution

**Comment by mischnic** [comment]
```ts
enum Bar {
    A, B, C
}

class Foo {}

// @ts-ignore
module.exports = Foo;
// @ts-ignore
module.exports.Bar = Foo;
```

https://www.typescriptlang.org/play/#code/KYOwrgtgBAQghgJygbwFBQ1AggGlngYVQF9VUBjAGzgGcaoAxAeyZTNNQHpOoABAFxoBaAJYBzEEwTBUEJgBMwlYADpgADwAOUwVAC8jFgG4uPAcPGTpshUtUbtCQSvhIDzJkaA

**Comment by shahen94** [comment]
This worked, thank you!

I'm feeling that this is more like a hack than the expected result.

Thanks anyway.

**Comment by mischnic** [comment]
Same thing happens with ESM/CommonJS:

```js
export default class Thing {}
```
if you transpile that with Babel/Typescript and import is from CommonJS, you need to do:
```js
const library = require("library");

new library.default()
