### ISSUE TITLE
When using fetch inside a function, the compiler gives the same key param to the function and the promise response

### ISSUE THREAD

**Issue by yejiel** [parcel-bundler/parcel#4928]
# 🐛 bug report

Generic function with a param to send a fetch request.

  ` function getData(param){
    fetch(`${url}param=${param}`)
        .then(res => res.status === 200 && res.json())
        .then(res => res );
  } `
code works but when minified the result is:
`function(e){
   fetch(`${url}param=${e}`).then(e=>200===e.status&&e.json()).then(e=>e)}();
`
Using the same "key > e" for both the function parameter and the promise response param causing some issues, like using the function value once the promise is resolved
## 🎛 Configuration (.babelrc, package.json, cli command)
Build via "parcel build Dev-index/index.html --no-source-maps  --public-url ./"

```js
{
"presets": [
  ["env", {
    "targets": {
      "browsers": ["last 2 Chrome versions"]
    }
  }]
]
}
}
```

## 🤔 Expected Behavior

Use different param vars to avoid conflicts

## 😯 Current Behavior

Same var name , 2 places 

## 🔦 Context

Instead of getting the promise response , im getting the function param value
The workaround for us was switch to async await .

## 💻 Code Sample
  `function getData(param){
    fetch(`${url}param=${param}`)
        .then(res => res.status === 200 && res.json())
        .then(res => res );
  }`
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta-1 & 1.12.4
| Node             | 12.14.1
| npm/Yarn         | npm
| Operating System | windows 10 pro

**Comment by mischnic** [comment]
This is caused by [Terser](https://github.com/terser/terser), not Parcel (you can try it out here: https://try.terser.org/).

**Comment by yejiel** [comment]
Thanks @mischnic will close and open on terser i guess 😅
