### ISSUE TITLE
🐛  Build files are copied on server start

### ISSUE THREAD

**Issue by scriptPilot** [parcel-bundler/parcel#493]
### 🎛 Configuration (.babelrc, package.json, cli command)

Node 6.10

```js
"scripts": {
    "server": "node_modules/.bin/parcel src/client/index.html --port 8080",
    "build": "node_modules/.bin/rimraf dist/client && node_modules/.bin/parcel build src/client/index.html --out-dir dist/client --public-url ./"
  }
```

### 🤔 Expected Behavior

On `npm run build` files are build in dist/client folder.
On `npm run server`server is starting.

### 😯 Current Behavior

On `npm run build` files are build in dist/client folder.
On `npm run server`server is starting, files in dist/client folder are copied to dist folder.

### 💁 Possible Solution

?

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | newest
| Node             |  6.11.4
| npm/Yarn         | 3.10.10
| Operating System | Amazon Cloud9

![bildschirmfoto 2018-01-05 um 00 08 07](https://user-images.githubusercontent.com/19615586/34588304-8d354200-f1ac-11e7-8c3a-e6fdca764b68.png)

**Comment by devongovett** [comment]
The default behavior is to build into the `dist` folder. The server command also builds, so if you want it to build into `dist/client` you can set `--out-dir dist/client` just as you did in the build command.

```json
"scripts": {
    "server": "node_modules/.bin/parcel src/client/index.html --port 8080 --out-dir dist/client",
    "build": "node_modules/.bin/rimraf dist/client && node_modules/.bin/parcel build src/client/index.html --out-dir dist/client --public-url ./"
  }
```

**Comment by scriptPilot** [comment]
@devongovett - Thank you, would be good to have that hint in the docs.
