### ISSUE TITLE
Cannot read property 'Traffic' of undefined

### ISSUE THREAD

**Issue by hypnguyen1209** [parcel-bundler/parcel#4933]
# 🐛 bug report

I am building a project, which uses async in data analysis. 
The first is the "regeneratorRuntime" error, I fixed it after adding 
```js
import 'regenerator-runtime / runtime'
```
 now it appears a 
` Cannot read property 'Traffic' of undefined`. 
I hope everyone helps, thank you.

## 🎛 Configuration (.babelrc, package.json, cli command)

This is my `package.json` 

```json
{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "parcel src/index.html"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel-bundler": "^1.12.4"
  },
  "dependencies": {
    "axios": "^0.19.2",
    "re": "^0.1.4",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "sha1": "^1.1.1",
    "sweetalert2": "^9.17.0"
  }
}

```

## 💻 Code Sample

![error log](https://i.imgur.com/MeiXJTV.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 12.18.2
| npm/Yarn         | npm 6.14.5
| Operating System | Windows 10 Pro 64bit

**Comment by DeMoorJasper** [comment]
could you create a minimal example with which we can reproduce this?

**Comment by hypnguyen1209** [comment]
Oh, I fixed it, it's because my error code allied to the API. Thanks 😍
