### ISSUE TITLE
RFC: Service plugins

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#4937]
## Motivation

Today, Parcel's multi threaded architecture can sometimes make it difficult to support running tools that require cross-file analysis to work correctly rather than operating on an individual file basis. Examples of these include TypeScript, SASS, Less, Stylus, CSS Blocks, and other compilers. 

While TypeScript supports a `transpileModules` option that operates on individual files, it does not support all TS language features. For example, `const enum`s cannot be compiled without type information. In addition, because `transpileModules` does not perform type analysis, we would currently need to do two parses of each file: once in the transformer, and again in the validator (that does the type checking). Finally, it would be nice if multiple plugins could query information known to TypeScript. For example, a type aware packager/optimizer plugin, or an editor language service using the full Parcel graph.

## Service plugins

The main issue is that Parcel plugins run in separate workers per file that cannot access the same shared state. This is generally good for performance because work can be parallelized, but it presents issues when cross-file analysis is required. A potential solution to this is to introduce the idea of service plugins to Parcel that run in a single worker, and which can maintain some shared state, and respond to requests from other plugins across workers.

It might look something like this:

![excalidraw-2020291564](https://user-images.githubusercontent.com/19409/88470395-ba192f00-ceb0-11ea-8411-ff9a8709cb2a.png)

Parcel core would call workers in its worker farm to perform transformation and validation for each asset as it does today. Plugins within these workers could then make RPC calls to dedicated workers containing services that provide an interface that can be accessed to perform any type of operation. For example, the TypeScript service might expose a method to `emit` code for a particular file, and a `validate` method to return diagnostics for a file.

This design would allow much of Parcel to continue to be parallelized, even while certain parts rely on a single threaded operation. For example, in the above diagram, only the TS transformer blocks on the TS service, compilation from a `.vue` file into a TS part, and further JS transformation (e.g. scope hoisting) can continue to be done in parallel.

## API

Rather than leave this up to individual plugins to coordinate, Parcel core should provide an interface to facilitate this. These plugins could be registered in a Parcel config file:

```json
{
  "services": ["@parcel/service-typescript"]
}
```

Each service plugin would expose an API that can be accessed via RPC. Each of the functions passed to the `Service` plugin constructor would be exposed via the RPC interface.

```js
import {Service} from '@parcel/plugin';

// Store global state as a module local variable
let tsCompiler = createCompiler(...);

export default new Service({
  async compile({ args, resolve, options }) {
    // do compilation stuff...
    let code = tsCompiler.emit(args.filePath);
    return {code, dependencies};
  },

  async validate({ args, options }) {
    // do validation stuff...
  }
});
```

Then, transformers, validators, and other plugins could access services through an API provided by parcel, by passing the service plugin name.

```js
export default new Transformer({
  async transform({ asset, getService }) {
    let typescriptService = await getService('@parcel/service-typescript');
    let result = await typescriptService.compile({
      filePath: asset.filePath,
      code: await asset.getCode()
    });

    asset.setCode(result.code);
    for (let dep of result.dependencies) {
      asset.addDependency(dep);
    }
  }
});
```

Parcel core would facilitate the RPC work necessary to make this call get passed to the proper worker, serializing the arguments and result and such, and queuing to ensure workers aren't overloaded. This could be built as part of our existing worker farm infrastructure.

Service plugins would need access to certain Parcel features to do their work. For example, TypeScript will need a way to request dependencies using Parcel's infrastructure. A `request` function could be passed to service plugins by Parcel to provide this. This could then in turn go back to Parcel core to resolve the dependency. These would end up as requests in the request graph just like other dependencies. Once all requests have been satisfied, TS should be able to emit a compilation result, which could be returned back to the transformer plugin.

## Conclusion

This seems fairly complex, but as far as I can tell, it's the only way to fully support the full TypeScript language. I think we'd want to potentially support two modes here: the `isolatedModules` option in tsconfig could be used to fall back to `transpileModule` mode or babel which will allow faster compilation but not all features. This could allow people to make the tradeoff that makes sense for their application.

**Comment by danieltroger** [comment]
+1, if this makes it possible to have type information it sounds lit. I want something that automatically polyfills stuff as I use it and using type annotations to know whether i.e. `replaceAll` is called on a string sounds like a low hanging fruit.

**Comment by devongovett** [comment]
Going to close this. The landscape is quite different from where we were in 2020 with migration to Rust fully underway.
