### ISSUE TITLE
Switch to TSC transformer instead of Babel by default

### ISSUE THREAD

**Issue by devongovett** [parcel-bundler/parcel#4938]
We should measure the performance impact of doing this first. However, based on issues, it seems fairly clear that the Babel-based TypeScript support that we have now is too limited. `@babel/preset-typescript` doesn't enable all of the language features that TSC does, e.g. decorators, class properties, optional chaining, etc. This causes confusion for people.

We could either attempt to match the features that TSC supports in our default config, or just run TSC first, and then Babel like we did in v1. The main issue is that when you add a custom Babel config, you'd need to re-create our default yourself, which might also be confusing.

The action items here are:

1. Switch a large TypeScript project to use `@parcel/transformer-typescript-tsc` for `.ts` and `.tsx` files instead of babel, and measure the performance impact.
2. If the perf impact is manageable, switch the default config over to TSC. Otherwise, discuss other options.

**Comment by mikeplus64** [comment]
I wonder if this is the best criteria for deciding if TSC is OK as the default. Mainly, I would be surprised if there are actually any large TypeScript projects that didn't have a tsconfig / use TSC already.

**Comment by devongovett** [comment]
Having a tsconfig and using TSC for compilation are two different things. For example, you could have a tsconfig for type checking and editor integration, but use Babel for compilation. This is how popular tools like create-react-app and Next.js work.

**Comment by LukeTOBrien** [comment]
Hello there,

I think you've goon off topic abit, let me bring it back.

The point I make in my issue:  

> **What % of TypeScript projects use a tsconfig.json?**  
I use a tsconfig in 100% of my TypeScript project, so in my case at least I am always going to manually configure to use tsc (which I never did in Parcel 1, it just worked)

Also:

> for most cases developers will want to **transform TypeScript as nature intended using tsc**.

I think Parcel 2 should work the same as Parcel 1 with regard to TypeScript.  
The reason that Babel is used is that it is a bit faster, but I am not concerned with speed, Parcel is fast enough, and TBH even if it takes seconds or minutes then I don't mind.

**Comment by LukeTOBrien** [comment]
`tsc` - Compiling TypeScript as nature intended.

**Comment by lgarron** [comment]
> 1. Switch a large TypeScript project to use `@parcel/transformer-typescript-tsc` for `.ts` and `.tsx` files instead of babel, and measure the performance impact.

Suppose that we tried this on a moderately sized project and it failed. Is it worth filing bugs now, or if/when `tsc` is the default?

**Comment by mischnic** [comment]
> Is it worth filing bugs now

Yes

**Comment by lgarron** [comment]
> > Is it worth filing bugs now
> 
> Yes

I've given this a a go again, and this time I think I'm getting a TypeScript 3 compat error? Is that expected / worth filing an issue for?

    npm ERR! code ERESOLVE
    npm ERR! ERESOLVE unable to resolve dependency tree
    npm ERR! 
    npm ERR! While resolving: cubing@0.16.0
    npm ERR! Found: typescript@4.2.3
    npm ERR! node_modules/typescript
    npm ERR!   dev typescript@"^4.0.2" from the root project
    npm ERR! 
    npm ERR! Could not resolve dependency:
    npm ERR! peer typescript@"^3.0.0" from @parcel/transformer-typescript-tsc@2.0.0-nightly.625
    npm ERR! node_modules/@parcel/transformer-typescript-tsc
    npm ERR!   @parcel/transformer-typescript-tsc@"2.0.0-nightly.625" from the root project
    npm ERR! 
    npm ERR! Fix the upstream dependency conflict, or retry
    npm ERR! this command with --force, or --legacy-peer-deps
    npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
    npm ERR! 
    npm ERR! See /Users/lgarron/.cache/npm/eresolve-report.txt for a full report.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/lgarron/.cache/npm/_logs/2021-03-11T11_40_11_289Z-debug.log

**Comment by mischnic** [comment]
@lgarron I think that's already reported here: https://github.com/parcel-bundler/parcel/issues/5978?

**Comment by devongovett** [comment]
An update on this: We are now transpiling TypeScript with SWC by default as of #6230. It is an order of magnitude faster than both Babel and TSC. It also fixes several issues that people had with using Babel as a transpiler for TypeScript. I think this changes the equation for what should be the default in Parcel significantly. Perhaps we should attempt to read `tsconfig.json` and apply the settings to SWC, as well as enable TS-specific transforms by default (e.g. decorators), but I no longer think using TSC by default is a good idea as it would harm performance significantly.

**Comment by devongovett** [comment]
As of #6501 we are loading some settings from tsconfig.json and applying them via SWC. Currently we support settings for JSX and enabling decorators, which are the only compiler features that have to be enabled and are not part of the default configuration. As more experimental features are added, we will also support those.

Going to close this issue. If you want to use TSC, you still can by using `@parcel/transformer-typescript-tsc`.
