### ISSUE TITLE
parcel server sub/page.htm

### ISSUE THREAD

**Issue by urbanhop** [parcel-bundler/parcel#494]
Is it possible to have the root html in a sub directory? 
I cannot get parcel to start my page that is in 

    ./sub/page.htm

I tried

    parcel sub/page.htm
    parcel sub\page.htm 
    parcel sub/page.html
    parcel sub\page.html

also with 

    parcel serve

but nothing worked. Thanks for any hint or help.

**Comment by nnnikolay** [comment]
@urbanhop I think you need to show your `page.html` here, for me the following command works fine

`parcel src/index.html --out-dir build`

**Comment by urbanhop** [comment]
thx @nnnikolay, could not get it to work here. i am on windows (tried with / and \). i will debug this some time and maybe report back then. will close this now, as I found a way around. thx
