### ISSUE TITLE
Parcel throws unique name error with @babel/plugin-proposal-export-namespace-from and target#context:node

### ISSUE THREAD

**Issue by waynevanson** [parcel-bundler/parcel#4943]
🐛 bug report

Parcel throws a unique name error with `@babel/plugin-proposal-export-namespace-from` and `target#context:node`.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
"main": "dist/index.js",
  "targets": {
    "default": {
      "context": "node"
    }
  },
  "babel": {
    "presets": [
      "@babel/preset-env",
      "@babel/preset-typescript"
    ],
    "plugins": [
      // need this for the use case: `export * as something from "./somewhere"`
      "@babel/plugin-proposal-export-namespace-from"
    ]
  }
}
```

## 🤔 Expected Behavior

This looks like the correct configuration and should have no errors/bundle correctly.

## 😯 Current Behavior

Does not bundle.

## 🔦 Context

I'm using Typescript, `^3.9.7` and have `export * as something from "./somewhere"` as a LOC in the entry point that parcel cli accepts.

This is the function in `Parcel` that throws the error.
```js
async nameBundles(bundleGraph) {
    let namers = await this.config.getNamers();
    // there are 2 bundles in here. Should this be the case?
    let bundles = bundleGraph.getBundles();
    await Promise.all(bundles.map(bundle => this.nameBundle(namers, bundle, bundleGraph)));
    // the 2 items in the array the same
    let bundlePaths = bundles.map(b => b.filePath);

    _assert.default.deepEqual(bundlePaths, (0, _utils.unique)(bundlePaths), 'Bundles must have unique filePaths');
}
```

## 💻 Code Sample

[Reproduction here: github.com/waynevanson/parcel-issue-context-node-non-unique-file-paths](github.com/waynevanson/parcel-issue-context-node-non-unique-file-paths)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.0-beta.1
| Node             | v12.17.0 via nvm
| npm/Yarn         | Yarn 1.22.4
| Operating System | Linux 5.3.0-62-generic # 56~18.04.1-Ubuntu SMP x86_64 GNU/Linux

**Comment by mischnic** [comment]
You are actually creating two targets: `main` and `default`, but outputting to `dist/index.js`

Either do this:
```diff
diff --git package.json package.json
index 4e5eae0..41c387b 100644
--- package.json
+++ package.json
@@ -15,7 +15,7 @@
     "typescript": "^3.9.7"
   },
   "targets": {
-    "default": {
+    "main": {
       "context": "node"
     }
   },
```

Or I would recommend rather:
```diff
diff --git package.json package.json
index 4e5eae0..e6dc65b 100644
--- package.json
+++ package.json
@@ -14,10 +14,8 @@
     "parcel": "^2.0.0-beta.1",
     "typescript": "^3.9.7"
   },
-  "targets": {
-    "default": {
-      "context": "node"
-    }
+  "engines": {
+    "node": ">= 10"
   },
   "babel": {
     "presets":
```

**Comment by waynevanson** [comment]
These both work. I'll use the first one in my project.
Thank you so much!

Looks like I've been confused in the docs somewhere.
For future readers, this portion adds clarification to your explanation: [https://v2.parceljs.org/configuration/package-json/](https://v2.parceljs.org/configuration/package-json/)
