### ISSUE TITLE
Parcel 2: React Refresh doesn't work if react is not in package.json/dependencies

### ISSUE THREAD

**Issue by tajo** [parcel-bundler/parcel#4948]
It seems that `react` and `react-dom` have to be listed in `package.json` as `dependencies` to make react fast refresh to work. If they are installed through `devDependencies` or being deeper in the dependency tree, the refresh does not work even when the `node_modules` structure is identical for all three cases. It still correctly connects to `ws` and sends updates but the components don't update automatically.

This seems to be an arbitrary limitation that creates hurdles when "re-bundling" Parcel since you typically don't want to put `react` into `dependencies` and let the installation of `react` up to the consumer (then you can't test it as re-bundler library owner).

If there is some good reason, it should be probably [documented](https://v2.parceljs.org/recipes/react/).

**Comment by mischnic** [comment]
This is done because including React Fast Refresh has an overhead, so it is only done when:
- a file has a import to `react` and
- `react` is a dependency

This was the only way to achieve this without requiring some configuration from the user to enable it.

> This seems to be an arbitrary limitation that creates hurdles when "re-bundling" Parcel since you typically don't want to put react into dependencies and let the installation of react up to the consumer (then you can't test it as re-bundler library owner).

Could you give an example of this situation. Maybe we can improve the current logic?

**Comment by tajo** [comment]
> a file has a import to react and react is a dependency

Why you don't use it for all files that import react? Do you have to check for specific react version? Importing from react implies that React is installed?

> Maybe we can improve the current logic?

Can you also check for `devDependencies`? That would fix my use-case.

 I'm building a storybook like tool. You call a CLI command and it will serve you an application. The tool is using parcel v2 internally.

There are two possible options how it could be installed & used:

**A.** React is not included and needs to be installed separately. This is probably the safest option since it will rule out two versions of react being used by the `tool` and components/stories it loads. However, when developing `tool`, `react` is in `devDepedencies` and fast refresh doesn't work.

```sh
yarn add tool react react-dom
yarn tool serve
```

**B.** React is included (part of `tool`'s `dependencies`). This would make easier to install and use it but we could face two versions of React problem. Also, this would not work for fast refresh on the consumer side since react is not in top level `dependencies` at all. In fact, you would have to stop checking for React in top-level package.json completely.

```sh
yarn add tool
yarn tool serve
```

**Comment by mischnic** [comment]
> Why you don't use it for all files that import react?

There are two parts to it:
- wrapping each file with a `refresh.prelude(); try { ....the file....} finally { refresh.prelude(); }`, this is done if there is a `react` import
- each bundle needs to have a runtime that essentially enables Fast Refresh globalls (this needs to run before any other code), this is done if there is a `react` `dependency` in `package.json.

I think checking `devDependencies` too should be ok as well.

**Comment by aaronjensen** [comment]
We are trying to use parcel to build a package with a react component in it and using parcel to serve a scaffold app for development. We put react in peerDependencies and devDependencies as we cannot and should not put it in dependencies for a library.

So, in our case, checking devDependencies would be great. Thanks!

**Comment by mischnic** [comment]
> react in peerDependencies and devDependencies

Anyone want to open a PR for that?

https://github.com/parcel-bundler/parcel/blob/46e8ffa3e781fcbee71dfba2fe83b7c0857f4866/packages/runtimes/react-refresh/src/ReactRefreshRuntime.js#L30

**Comment by robintom** [comment]
> > react in peerDependencies and devDependencies
> 
> Anyone want to open a PR for that?
> 
> https://github.com/parcel-bundler/parcel/blob/46e8ffa3e781fcbee71dfba2fe83b7c0857f4866/packages/runtimes/react-refresh/src/ReactRefreshRuntime.js#L30

Done and have made a PR 👍
