### ISSUE TITLE
Parcel does not include some variable definitions in module bundle.

### ISSUE THREAD

**Issue by deebov** [parcel-bundler/parcel#4949]
# 🐛 bug report

Parcel does not include some variable definitions in module bundle.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": ["@babel/preset-typescript"],
  "env": {
    "production": {
      "plugins": ["emotion"]
    },
    "development": {
      "plugins": [["emotion", { "sourceMap": true }]]
    }
  }
}
```

.parcelrs
```js
{
  extends: "@parcel/config-default"
}
```

## 🤔 Expected Behavior

All variables must be included in all bundles

## 😯 Current Behavior

`$fc5587aadce60cccf10dc4ea26498cf9$var$selectors` this is how the lost variable named in module bundle. But it does not exist in module bundle. Everything works fine in main bundle.

## 🔦 Context

I am using parcel v2 for a design system/collection of components monorepo along with lerna. I run `parcel build` in the root directory. All bundles files are stored in package's directory e.g. `packages/components/dist`

## 💻 Code Sample

module.js
https://gist.github.com/deebov/786f8a9bbe91fc0d4f4cb7fcbfacc610#file-module-js-L97

main.js
https://gist.github.com/deebov/8ff02aa7854863e063f87f0f01b0ad1c

source.ts
https://gist.github.com/deebov/147866c9ee431cfd76e85eecdf2ef440

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  ^2.0.0-nightly.352
| Node             | v12.18.2
| npm/Yarn         | 1.17.3
| Operating System | macOS 10.15.5

**Comment by deebov** [comment]
i found a workaround by exporting the variable that gets "lost"

**Comment by deebov** [comment]
also, it works if I move the variable to the function scope that uses it

**Comment by mischnic** [comment]
Closing due to lack of response
