### ISSUE TITLE
Can the format of each file be customized?

### ISSUE THREAD

**Issue by bosens-China** [parcel-bundler/parcel#4954]
# 🙋 feature request

Now the output file is

``` js
parcelRequire = (function (e, r, t, n) {
   var i,
     o = "function" == typeof parcelRequire && parcelRequire,
     u = "function" == typeof require && require;
// ...
```
But I only use it in the browser, and I don't need to talk about redundant packaging. 
Is there any way to return only the pure source code?

## 🤔 Expected Behavior

``` js
let num = 0;
setInterval(() => {
  console.log(num);
  num++;
}, 1000);
```
build
``` js
var num = 0;
setInterval(function () {
  console.log(num);
  num++;
}, 1000);
```
## 😯 Current Behavior

Excess packages generated
## 💁 Possible Solution
You can choose the generated module type through options

``` js
  output: {
    // ...
    format: 'iife',
  }
```

**Comment by 101arrowz** [comment]
Actually, Parcel _does_ use an IIFE by default for every build. One of the core uses of a bundler is to support merging dependencies into a single file, so by default it creates an environment with a synthetic `require` function to support separate modules.

If you have no dependencies and don't need your code transpiled through Babel/PostCSS/whatever, there's really no point to using Parcel at all.
