### ISSUE TITLE
transformer-less is not always getting config

### ISSUE THREAD

**Issue by kuchta** [parcel-bundler/parcel#4966]
I have found out, that parcel's transformer less is not always getting configFile (config.getConfig() returns null) in function load({config}) defined in loadConfig.js. I think this is a bug.

## 🌍 Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | beta1 and 2.0.0-nightly.355
| @parcel/transformer-less | 2.0.0-nightly.357
| Node             | 12.18.0
| npm/Yarn         | npm@6.14.5
| Operating System | MacOS Mojave

**Comment by mischnic** [comment]
> not always

Please provide an example

**Comment by kuchta** [comment]
I'm trying to build quite a complex system which was previously build with webpack and reducing it to simple example would not be as easy, but I found out, that the config is missing in transforming less files that are not part of my package, but in one of my dependencies (antd). Since that dependency doesn't define it's own config I suppose this could be valid behavior, but if it is, how to override the configuration of transforming files in dependencies?

**Comment by mischnic** [comment]
> Since that dependency doesn't define it's own config I suppose this could be valid behavior

Yes (same applies to Babel as well). Which less config options are you trying to apply to the dependency?

**Comment by kuchta** [comment]
Thanks Niklas for prompt reply. I'm trying to apply this config
```
{
    "javascriptEnabled": true,
    "modifyVars": {
      "@primary-color": "#479a96",
      "@breadcrumb-link-color": "#479a96",
      "@menu-item-active-bg": "transparent",
      "@form-item-margin-bottom": "8px"
    }
  }
```
But it's javascriptEnabled that's blocking me from building the project since antd uses inline JavaScript...

**Comment by kuchta** [comment]
Hi guys,

Would it be ever possible to compile styles with project's configuration? This is the only thing that prevents me from using parcel...
