### ISSUE TITLE
Installation needed 319.9s on a beefy VPS

### ISSUE THREAD

**Issue by desmap** [parcel-bundler/parcel#4967]
Not a bug but tbh this should be mentioned in the README. Even if you do it once in a while or with every Docker production build, for some 319.9s incl millions of post installs might be a major turn-off. I know that there is already an issue and it was closed but again I've never seen such long install times with any npm package.

**Comment by mischnic** [comment]
What is taking so long? Downloading the packages? Or some postinstall step?

**Comment by desmap** [comment]
> Or some postinstall step?

Of the five minutes I've seen four minutes postinstalls (on a 4 core vps connected via 1GBit)

**Comment by mischnic** [comment]
I haven't seen such long postinstall times. Which packages are causing this?

**Comment by desmap** [comment]
Hey, I completely removed Parcel from my system again. I installed it two days ago, so it must have been the version you got from npm two days ago. re which packages? I just was installing Parcel, nothing more. I cannot help more sorry, I also won't use Parcel in future. However, just take your current vps or local machine do an install, take the time, share it with your collabs and look if and what you guys want to do.
