### ISSUE TITLE
Uncaught Error: Cannot find module '7'

### ISSUE THREAD

**Issue by alex1504** [parcel-bundler/parcel#497]
This happen when I resave css file. What make me confuse is that the browser livereload works when I change .html file, but when I change css file, I need to press F5 to reload. And the error occurs "can't not find module [number]". I reinstall, doesn't works for me. Node version is v8.9.3

**Comment by AdrianBilicz** [comment]
I have the same issue. Sometimes module '4' sometimes '7'.

**Comment by albinotonnina** [comment]
Have you tried to remove the .cache folder in the project root?

**Comment by AdrianBilicz** [comment]
I removed the .cache folder and changed the way I link the css file. Instead linking in the html file I import scss into js file. Everything worked fine until I added @import on top of scss file then I got error: Uncaught TypeError: Cannot read property 'js' of null . Browser still get the right css but console that error and  I have to manually reload the browser.

**Comment by breadadams** [comment]
An example where I've just seen the `Cannot find module 'X'` was after including a new component via `import`. On the live reload from saving this, the error appears, if I manually refresh the page it's no-long shows the error.

**Comment by alex1504** [comment]
Whatever I reinstall parcel or remove .cache file doesn't save my problem. Doesn't my node version matters?

**Comment by natew** [comment]
I'm getting this when changing a single import from `require` to `import`. Deleting `.cache` and re-running doesn't fix. Happy to help debug.

Also my source maps are off generally (1.5.1), so I have to turn them off to look through stack traces.

**Comment by DeMoorJasper** [comment]
@natew Sourcemaps don't perfectly work with hmr, it should be correct when you reload the page (so refetch the complete bundle). However it might be linked to this bug and make sourcemaps a little of

**Comment by devongovett** [comment]
Looks related to #879. Closing this one as that has more info.
