### ISSUE TITLE
Parcel ignores distDir/--dist-dir option

### ISSUE THREAD

**Issue by JonLopezGarcia** [parcel-bundler/parcel#4996]
# 🐛 bug report

Parcel ignores `distDir` / `--dist-dir` option with `build` command and output the bundled files in cwd.

## 🎛 Configuration (.babelrc, package.json, cli command)

**.babelrc**
```js
{
  "presets": ["@babel/preset-env", "@babel/preset-typescript"]
}
```

**package.json**
```js
{
  "name": "my-app",
  "version": "1.0.0",
  "default": "index.html",
  "license": "MIT",
  "scripts": {
    "start": " parcel index.html",
    "build": "parcel build index.html",
    "test": "jest",
    "test:watch": "jest --watch"
  },
  "targets": {
    "default": {
      "engines": {
        "browsers": "> 0.25%"
      },
      "distDir": "www",
      "publicUrl": ".",
      "sourceMap": false
    }
  },
  "dependencies": {
    "countup.js": "^2.0.4"
  },
  "devDependencies": {
    "@babel/core": "^7.11.1",
    "@babel/preset-env": "^7.11.0",
    "@babel/preset-typescript": "^7.10.4",
    "@types/jest": "^26.0.8",
    "babel-jest": "^26.2.2",
    "jest": "^26.2.2",
    "parcel": "^2.0.0-nightly.360",
    "rimraf": "3.0.0",
    "sass": "^1.25.1-test.1",
    "typescript": "^3.9.7"
  }
}
```

## 🤔 Expected Behavior

Bundled files should be outputted in `www` folder

## 😯 Current Behavior

Bundled files are outputted in cwd

## 🔦 Context

The option `sourceMap` in `package.json` is not ignored.
I tried with the **v2 alpha** first and ended up trying with the **nightly build** hoping it will solve my issue.

## 🌍 Your Environment

Node: v12.18.3
Yarn: v1.22.4
Operating System : Windows 10

**Comment by mischnic** [comment]
(Not meant as a fix but) Does deleting `.parcel-cache` make it output into that folder? Could be a caching issue...

**Comment by JonLopezGarcia** [comment]
Unfortunately deleting `.parcel-cache` does nothing...

**Comment by mischnic** [comment]
Ah, this line takes precendence:
```diff
"default": "index.html",
```
Just remove it

**Comment by tovare** [comment]
I had the same issue because I used npm init and set iindex.html as the default target.

**Comment by JonLopezGarcia** [comment]
> Ah, this line takes precendence:
> 
> ```diff
> "default": "index.html",
> ```
> 
> Just remove it

I removed it and it created a `dist` folder (instead of a `www` folder) and then failed, outputting the following error : 
![image](https://user-images.githubusercontent.com/22107965/89784794-92190500-db19-11ea-8576-7574e0a60acf.png)

I tried again deleting the `.parcel-cache` folder first. 
It created the `dist` folder (not the `www` specified) but succeeded to bundle.

So I think the `distFolder` option still gets ignored.

**Comment by EyMaddis** [comment]
@mischnic This does not seem to be fixed in parcel 2.0.0-beta.2. Having a "main" in the package.json still overrides the CLI setting (which it shouldn't)

**Comment by mischnic** [comment]
> Having a "main" in the package.json still overrides the CLI setting (which it shouldn't)

No, it should override. 

https://v2.parceljs.org/getting-started/configuration/#setting-the-output-path

**Comment by EyMaddis** [comment]
I removed the main, but still find it a bit odd that the cli param does not override it. 

If I where to setup a CI process that needs to put the files somewhere else, I would need to copy the files or change the package.json. In my opinion CLI arguments should always win against something that is in a file.
This goes against my understanding of how I expect CLI tooling to work. 

What is the reasoning that the precedence order is like that? Imho, it should be exactly reversed

**Comment by mischnic** [comment]
> In my opinion CLI arguments should always win against something that is in a file.

This does make sense, but it's also in conflict with our principle of having finer-grained options win against options applying to multiple entities. This is why per-target output options (in package.json) have a higher precedence than `--dist-dir`.

**Comment by ConteaHNL** [comment]
The best solution in my opinion is to remove the option to use a --dist-dir parameter as the conflict with targets creates a lot of confusion especially for people used to V1. Clearly stating that using targets for this is "the V2 way" is simple and easy to learn.

**Comment by hiroshi-yamamoto-dublr** [comment]
I still see this issue in Parcel 2.7.0.  I have:

```json
  "targets": {
    "main": {
      "includeNodeModules": true,
      "distDir": "docs"
    }
  },
```

Compiling with `npx parcel` writes the output to `dist/` -- the `distDir` option is ignored.

Compiling with `npx parcel --dist-dir docs` correctly writes the output to `docs/`.

Any suggestions, please?

**Comment by hiroshi-yamamoto-dublr** [comment]
OK, I figured it out. I had to change the target name from `main` to `default`, and now the option works.
