### ISSUE TITLE
Using Parcel 2 SVG attributes are all getting lower cased

### ISSUE THREAD

**Issue by dgkimpton** [parcel-bundler/parcel#5004]
# 🐛 bug report

Using Parcel 2 when I build, my inline SVG graphics get their attributes lowercased. SVG is a case sensitive specification, so this is not desired.  

There are several other bug reports here about SVGO stripping out tags (like viewBox) which I believe is happening exactly because of this attribute lowercasing.

It feels like this is something that could be solved if I could get the correct configuration, but I've spent half a day on it and gotten nowhere... maybe someone here knows how to solve it?

(apart from this niggle I'm loving Parcel 2 so far)

## 🎛 Configuration

cli-command:     ```npx parcel build index.html  ```

#### package.json
```json
{
  "name": "parcel2-svg-test",
  "private": true,
  "devDependencies": {
    "parcel": "^2.0.0-beta.1"
  }
}
```
#### .posthtmlrc
```js
{
	"xmlMode": true,
	"recognizeSelfClosing": true,
	"lowerCaseAttributeNames": false,
}
```
#### .htmlnanorc
```js
{
	"minifySvg": false
}
```

## 🤔 Expected Behavior

Attributes in the <svg> specification should not be changed to lower case.

## 😯 Current Behavior

The svg gets all its attribute names converted to lower case:

```xml
<svg viewbox="1.8 2.4 2 2" preserveaspectratio="xMinYMin meet"> <defs> <filter id="blur"> <feGaussianBlur in="SourceGraphic" stddeviation="0.01"></feGaussianBlur> </filter> </defs> <g> <path d="M2 3C3 2 4 3 3 4" stroke-width="0.1" stroke="blue" fill="none" filter="url(#blur)"></path> </g> </svg>
```

## 💻 Code Sample

index.html
```html
<!DOCTYPE html><html lang="en"><head></head><body>

	<svg viewBox="1.8 2.4 2 2" preserveAspectRatio="xMinYMin meet">
		<defs>
			<filter id="blur">
				<feGaussianBlur in="SourceGraphic" stdDeviation="0.01" />
			</filter>
		</defs>
		<g>
			<path d="M2 3C3 2 4 3 3 4" stroke-width="0.1" stroke="blue" fill="none" filter="url(#blur)"/>
		</g>
	</svg>

</body></html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1|
| Node             |v14.4.0|
| npm         |6.14.5|
| Operating System | Windows 10|

**Comment by mischnic** [comment]
It's actually not htmlnano (because it also happens with `--no-minify`), but:

https://github.com/parcel-bundler/parcel/blob/46e8ffa3e781fcbee71dfba2fe83b7c0857f4866/packages/transformers/html/src/HTMLTransformer.js#L20-L22

@wbinnssmith Any chance you remember why you added this?

**Comment by dgkimpton** [comment]
Apart from SVG, and possibly React custom attributes, this is generally a good choice. Even JS's Element.getAttribute() lowercases names before looking them up.

Chrome also doesn't seem to care about lowercase attributes in SVG, but a) the minimiser does and b) transforming valid code into technically invalid code just seems like a bad idea.

Is there a way to make this transformation be applied to everything except SVG?
(I've no idea what should be done about React and it's weird case sensitivity, make it optional I guess?).

**Comment by dgkimpton** [comment]
Although lowerCaseAttributeNames is forced to be true in the HTMLTransformer I'm still not convinced this is actually a Parcel issue. The fact that the htmlparser2 library converts svg attributes to lower case seems to be wrong behaviour. I've submitted an issue to that project here: https://github.com/fb55/htmlparser2/issues/539

I propose no-one change this Parcel 2 behaviour until we hear back from the maintainer of the parser. If the fix is applied at that level then upgrading the libraries will be enough.

**Comment by FRSgit** [comment]
Seems that htmlparser2 issue got closed. What would be the follow-up here?

**Comment by Dunks1980** [comment]
I looked everywhere and tried everything to resolve this with no luck, in the end I made this:
https://www.npmjs.com/package/@dunks1980/inline.svg

**Comment by AndrewKvalheim** [comment]
Per [above](https://github.com/parcel-bundler/parcel/issues/5004#issuecomment-671404517) this is caused by the use of `lowerCaseAttributeNames`. For a workaround it's sufficient to preempt the default HTML transformer with an empty one that parses without that option.

**Comment by devongovett** [comment]
I just tested and lower case attribute names seem to work for me in browsers. This makes sense as the HTML spec says

> In the HTML syntax, attribute names, even those for foreign elements, may be written with any mix of ASCII lower and ASCII upper alphas.

See https://html.spec.whatwg.org/multipage/syntax.html#syntax-attribute-name

Can someone explain what kind of problems they've seen with this?

**Comment by AndrewKvalheim** [comment]
SVGO [is opinionated][378575233] about attribute case and deletes `viewbox`.

[378575233]: https://github.com/svg/svgo/issues/939#issuecomment-378575233

**Comment by devongovett** [comment]
Hmm interesting. I'm not sure what we should do about this. We can't simply remove that parser option because we need to handle attributes of any case for other parts of HTML. I think ideally SVGO would have an option to indicate that the SVG is embedded inside HTML, because this is completely valid - i.e. someone could author their HTML that way and SVGO would be broken.

**Comment by devongovett** [comment]
Maybe we should just disable `removeUnknownsAndDefaults` for now?

**Comment by AndrewKvalheim** [comment]
That sounds reasonable; better to have some pending optimizations than corrupted images.
