### ISSUE TITLE
Id's in HTML are replaced with parcel build, while elements are not href'ed properly.

### ISSUE THREAD

**Issue by alanjyu** [parcel-bundler/parcel#5007]
# 🐛 bug report

Id's in HTML are replaced with parcel build, causing elements not href'ed properly.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "alanjyu.com",
  "version": "0.2.2",
  "description": "Personal/portfolio website.",
  "main": "main.js",
  "directories": {
    "lib": "lib"
  },
  "scripts": {
    "dev": "parcel src/index.html",
    "build": "parcel build src/index.html -d docs/"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/alanjyu/alanjyu.com.git"
  },
  "author": "Alan J. Yu",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/alanjyu/alanjyu.com/issues"
  },
  "homepage": "https://github.com/alanjyu/alanjyu.com#readme",
  "dependencies": {
    "bounds.js": "^1.0.4",
    "gsap": "^3.4.2",
    "typeface-ibm-plex-mono": "0.0.61",
    "typeface-rokkitt": "^1.1.3",
    "typeit": "^7.0.4"
  },
  "devDependencies": {
    "cssnano": "^4.1.10",
    "sass": "^1.26.10"
  }
}

```

## 🤔 Expected Behavior

Button displaying properly with proper element id reference.
![preview (in dev mode)](https://user-images.githubusercontent.com/48685257/89839801-e2995e00-db2b-11ea-8c4b-935a5b712f83.png)

## 😯 Current Behavior

Button displaying improperly after change of the element's id. For example, element **g#theme-switch--night** was replaced with **g#d** but hrefs under use were not replaced.
![product (after building)](https://user-images.githubusercontent.com/48685257/89839812-e7f6a880-db2b-11ea-94f3-9c3c27a59d81.png)

## 💁 Possible Solution

Not replacing the id's, or at least an option to turn off the function.

## 🔦 Context

With id's defined in ref, after building and uglifying the html, the id's were replaced so that href's were not correct.

## 💻 Code Sample

Included in the attached screenshots.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 14.5.0
| npm/Yarn         | 6.14.6
| Operating System | Win10 (20H1)

Thanks in advance.

**Comment by mischnic** [comment]
Probably caused again by htmlnano, try this in a `.htmlnanorc`:
```
{ "minifySvg": false }
```
