### ISSUE TITLE
A second `.d.ts` types target fails with error in Parcel 2

### ISSUE THREAD

**Issue by lgarron** [parcel-bundler/parcel#5010]
Suppose you want to build two `.d.ts` targets with Parcel 2:

    "types": "dist/main/index.d.ts",
    "extended-types": "dist/extended/index.d.ts",

Parcel 2 runs into an error if you try to build the second one.

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`

```json
{
  "name": "types-target-test",
  "types": "dist/main/index.d.ts",
  "extended-types": "dist/extended/index.d.ts",
  "targets": {
    "types": {},
    "extended-types": {}
  },
  "devDependencies": {
    "parcel": "^2.0.0-nightly.364"
  }
}
```

`src/extended.ts`
```
export function goodbye() {
  console.log("goodbye!");
}
```

Run:

```shell
npx parcel build --target extended-types src/extended.ts
```

## 🤔 Expected Behavior

The `extended-types` target should build.

## 😯 Current Behavior

    🚨 Build failed.
    @parcel/namer-default: Target "extended-types" declares an output file path of "dist/extended/index.d.ts" which does not match the compiled bundle type "js".
    /Users/lgarron/Code/parcel-second-types-target-simplified/package.json:4:21
      3 |   "types": "dist/main/index.d.ts",
    > 4 |   "extended-types": "dist/extended/index.d.ts",
    >   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^ Did you mean "dist/extended/index.d.js"?
      5 |   "targets": {
      6 |     "types": {},
    Try changing the file extension of "extended-types" in package.json.

## 💁 Possible Solution

There's probably a hardcoded assumption that prevents other `d.ts` targets from being handled like `types`?

## 🔦 Context

I have a few libraries that have multiple builds, including https://github.com/github/webauthn-json (which I'm using for this example).

Due to issues described in #4797, I make a separate target for every output JS entry file as well as its accompanying types.

## 💻 Code Sample

Here is a simplified repro: https://github.com/lgarron/parcel-2-multiple-.d.ts-targets

```shell
git clone https://github.com/lgarron/parcel-2-multiple-.d.ts-targets
cd parcel-2-multiple-.d.ts-targets
npm install
npx parcel build --target extended-types src/extended.ts
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.364 |
| Node             | v14.7.0 |
| npm        | 6.14.7 |
| Operating System | macOS 10.15.6 |

Apologies if this is a duplicate/known issue. I wasn't able to find an existing issue that quite covers this.

**Comment by devongovett** [comment]
This is because Parcel has no way of knowing that you want to compile to a `.d.ts` rather than `.js`. For `types`, this is configured in the default `.parcelrc` using a named pipeline that matches the target name: https://github.com/parcel-bundler/parcel/blob/7717e2547f510c89ea57bbfec62147bfb912ba49/packages/configs/default/index.json#L4

You could configure a custom `.parcelrc` to handle `extended-types` the same way:

```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "extended-types:*.{ts,tsx}": ["@parcel/transformer-typescript-types"],
  }
}
```

**Comment by lgarron** [comment]
> You could configure a custom `.parcelrc` to handle `extended-types` the same way:

Thanks! This workaround works perfectly! :-D
