### ISSUE TITLE
Be able to fail the build by throwing errors in resolvers

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5012]
# 🙋 feature request

## 🤔 Expected Behavior

Throwing an error in a resolver should fail the build.

## 😯 Current Behavior

Currently, throwing errors in resolvers doesn't fail the build but runs the next resolver specified in the parcelrc (and only if all of them didn't resolve, all errors are thrown).

## 💁 Solution

The Resolver's `resolve` function should have the return type `?ResolveResult | Array<Diagnostic>`.

https://github.com/parcel-bundler/parcel/blob/0648010297f5e9a08ddb4de2a53dfa09fce64e3d/packages/core/types/index.js#L1127

It would behave like this:
- returning a nullish value defers to the next resolver in line
- returning the diagnostics defers to the next resolver in line while also providing information about why this resolver failed (if configured resolver succeeded)
- throwing an Error/ThrowableDiagnostic fails the build immediately

## 🔦 Context

https://github.com/parcel-bundler/parcel/discussions/4992
cc @Aaronius

**Comment by mischnic** [comment]
Fixed by #5026

**Comment by Aaronius** [comment]
Just wanted to say thank you!
