### ISSUE TITLE
watch/serve doesnt respect targets.default.publicUrl

### ISSUE THREAD

**Issue by morbidick** [parcel-bundler/parcel#5014]
# 🐛 bug report

When running parcel in watch or serve mode the via package.json provided publicUrl is not respected. It has to be explicitly set via --public-url on the cli.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{

  "targets": {
    "default": {
      "publicUrl": "/mypublicpath/"
    }
  },
  "scripts": {
    "works-as-expected": "parcel serve --public-url mypublicpath/ src/index.htmll",
    "still-serves-everything-under-/": "parcel serve src/index.html"
  },
}
```

## 🤔 Expected Behavior

The asset paths include the publicUrl

## 😯 Current Behavior

Assets are served from /

## 💁 Possible Solution

Make watch and serve respect the publicUrl (or highlight the difference in the docs)

## 🔦 Context

I'm trying to integrate Parcel with an existing PHP application and for local development it would be superb to work with the same paths as in the prod environment.

## 💻 Code Sample

see above, if you need more i can create it

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | v10.15.2
| npm/Yarn         | 6.7.0
| Operating System | ubuntu 19.04

**Comment by mischnic** [comment]
This should work: `parcel serve index.html --target default`.
The idea behind the default options for serve mode (browserslist `last 1 version`, public url) is that the development environment is usually different to the production environment.

https://github.com/parcel-bundler/parcel/blob/0648010297f5e9a08ddb4de2a53dfa09fce64e3d/packages/core/core/src/requests/TargetRequest.js#L231-L251

**Comment by morbidick** [comment]
This works like a charm, @mischnic thank you so much. Should i close this Issue or leave it open until its in the docs?
