### ISSUE TITLE
Dynamic import causes static import to resolve to a Promise

### ISSUE THREAD

**Issue by developit** [parcel-bundler/parcel#5016]
# 🐛 bug report

A module containing both a static and dynamic import for the same specifier causes the static import to produce Promise values for its corresponding identifiers.

## 🎛 Configuration (.babelrc, package.json, cli command)

Parcel 2, stock config. Using the built-in Babel transformer on a TypeScript module, though I don't believe this is specific to TypeScript.

## 🤔 Expected Behavior

```js
import Foo from './foo';

console.log(Foo);  // class Foo {}

import('./foo').then(({ default: LazyFoo }) => {
    console.log(LazyFoo);  // class Foo {}
    assert.equal(LazyFoo, Foo);
});
```

## 😯 Current Behavior

```js
import Foo from './foo';

console.log(Foo);  // Promise<pending> (eventually resolves to class Foo {})

import('./foo').then(({ default: LazyFoo }) => {
    assert.equal(LazyFoo, Foo);  // (not sure if this resolves to the same)
});
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | 12.16.0
| npm/Yarn         | npm@6.13.4
| Operating System | MacOS Catalina

**Comment by mischnic** [comment]
This is a known limitation at the moment. We use the modulespecifier (`./foo`) to uniquely identify dependencies of an asset and this is one situation where two different (`isAsync: true/false`) dependencies have the same module specifier...
