### ISSUE TITLE
postHTML config file not read by Parcel

### ISSUE THREAD

**Issue by VladimirMikulic** [parcel-bundler/parcel#5019]
# 🐛 bug report

As the title suggests, I have a postHTML config file in my project (`.posthtmlrc`):

```json
{
  "options": {
    "directives": [
      {
        "name": "?",
        "start": "<",
        "end": ">"
      },
      {
        "name": "?=",
        "start": "<",
        "end": ">"
      }
    ]
  }
}
```

This configuration tells postHTML how to process Google Apps Script (GAS) template syntax.
I've tested this with postHTML and it works, but Parcel for some reason is not reading that file.
(nor other config file names that I've tried which are all mentioned in the [docs](https://parceljs.org/html.html))

postHTML command used for testing: `posthtml -c .posthtmlrc index.html -o dist/index.html`
HTML file: https://filebin.net/gh9li3r8vncaqz1f

## 🎛 Configuration (.babelrc, package.json, cli command)

```jsonc
{
  // ...
  "scripts": {
    "build": "parcel build index.html"
  }
}
```

## 🤔 Expected Behavior

I would expect the Parcel to output HTML file without stripping this block (hence custom postHTML config)

```
<? for (var i = 0; i < LANGUAGES.length; i++) { ?>
<? } ?>
```

## 😯 Current Behavior

Currently, it does remove the GAS template block from above.

## 💁 Possible Solution

It seems that the logic for reading config is in `node_modules/parcel-bundler/lib/transforms/posthtml.js` file (`_getConfig`).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 12.8.3
| npm/Yarn         | 6.14.7
| Operating System | Kubuntu 20.04

Thank you.

**Comment by ankitgandhi452** [comment]
Any luck on this even I am facing the same issue

**Comment by ankitgandhi452** [comment]
Guys any resolution on this. since I am also facing the same issue
