### ISSUE TITLE
Dev server incorrectly includes charset in Content-Type

### ISSUE THREAD

**Issue by developit** [parcel-bundler/parcel#5020]
# 🐛 bug report

When serving binary assets like `.wasm` files, Parcel's dev server (`parcel start`) includes `; charset=utf-8` in the `Content-Type` of all responses. This doesn't normally amount to much other than being unnecessary, however `WebAssembly.instantiateStreaming()` performs strict mime type checking on responses that does not allow the bogus charset.

In general, binary responses should not include a charset. There are probably other circumstances where doing so causes issues.

## 🎛 Configuration

Stock parcel config with the following code:

```js
import wasm from 'url:./foo.wasm';
WebAssembly.instantiateStreaming(fetch(wasm));
```

## 🤔 Expected Behavior

```js
import wasm from 'url:./foo.wasm';
WebAssembly.instantiateStreaming(fetch(wasm));  // doesn't throw
fetch(wasm).then(r => r.headers.get('Content-Type')) // "application/wasm"
```

## 😯 Current Behavior

```js
import wasm from 'url:./foo.wasm';
WebAssembly.instantiateStreaming(fetch(wasm));  // throws because of extraneous charset
fetch(wasm).then(r => r.headers.get('Content-Type')) // "application/wasm; charset=utf-8"
```

## 💁 Possible Solution

As a workaround, I'm using a custom Express middleware via `.proxyrc.js` to patch Response.setHeader and remove the extraneous charset:

```js
// .proxyrc.js
module.exports = function(app) {
  app.use(function(req, res, next) {
    const sh = res.setHeader;
    res.setHeader = function(key, value) {
      if (/^content-type$/i.test(key)) {
        const m = value && value.match(/^(image\/|application\/wasm); charset=.+$/);
        if (m) value = m[1];
      }
      return sh.call(this, key, value);
    }
    next();
  });
};
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | 12.16.0
| npm/Yarn         | npm@6
| Operating System | MacOS Catalina

**Comment by mischnic** [comment]
👍 
Not sure where this is coming from just by looking at the code, we call out to `serve-handler`:
https://github.com/parcel-bundler/parcel/blob/4c699d681e73767ab57c04fc05ad1eefaf4735fb/packages/reporters/dev-server/src/Server.js#L252-L265

**Comment by mischnic** [comment]
Coincidentally, this was already fixed by https://github.com/parcel-bundler/parcel/pull/4782 since the beta. You could try `parcel@nightly`
