### ISSUE TITLE
Expose Target info in PluginOptions

### ISSUE THREAD

**Issue by 101arrowz** [parcel-bundler/parcel#5022]
# 🙋 feature request

Expose target information such that plugins can access it
## 🤔 Expected Behavior

It should be possible to get info about the target of the asset (for example `publicUrl`) from a plugin (for example a transformer).
## 😯 Current Behavior

There is no way to get the`publicUrl` from a plugin.

## 🔦 Context

I'm trying to integrate a transformer with a build tool that needs to know the public URL in advance.

I would assume this is possible, since the `publicUrl` is exposed under the `serve` key of the `options` in development.

**Comment by mischnic** [comment]
Assets have no target. The target is reduced into an environment so that multiple targets can all use the same assets (while only transforming once).

The distdir and the publicURL in the `ServerOptions` is just the basedir for the server and the prefix that should be added to all URLs.

**Comment by 101arrowz** [comment]
Suppose I want to inject a favicon into an HTML file. After generating the favicon as a `Buffer`, how do know where the favicon is located such that I can link it in the final HTML? Normally I would just link with `./favicon.ico`, but that becomes an issue if the user is using the History API. A file may not exist at location `https://website.com/myApp/x/y/z`, so their server will return `https://website.com/myApp/index.html`, but then when the browser searches for the favicon, instead of getting `https://website.com/myApp/favicon.ico`, it tries to get `https://website.com/myApp/x/y/favicon.ico` and fails.

**Comment by devongovett** [comment]
As @mischnic said, you should use `addDependency` for this. In your transformer, set the `href` attribute for your favicon to the result of calling `addDependency({moduleSpecifier: './favicon.ico'})`. This is initially a hashed dependency id, but later on (after packaging) it is replaced with a final URL to the generate file and content hashed file for that icon. For an example, see how the HTML transformer does it.
