### ISSUE TITLE
Cannot resolve dependency with relative path inside node_modules

### ISSUE THREAD

**Issue by michaelmior** [parcel-bundler/parcel#5027]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

No `.babelrc`. The `package.json` is given below. I'm trying to run `parcel build`.

```json
{
  "name": "ibd-slides",
  "version": "0.0.1",
  "repository": "https://github.com/michaelmior/ibd-slides/",
  "author": "Michael Mior <mmior@cs.rit.edu>",
  "license": "MIT",
  "dependencies": {
    "reveal.js": "^4.0.2"
  },
  "devDependencies": {
    "parcel": "^1.12.4"
  },
  "scripts": {
    "build": "parcel build public/index.html",
    "dev": "parcel public/index.html"
  }
}
```

## 🤔 Expected Behavior

I'm simply trying to use [reveal.js](https://revealjs.com/) with Parcel and the included stylesheets.

## 😯 Current Behavior

```
$ yarn build
yarn run v1.22.4
$ parcel build public/index.html
🚨  /Users/mmior/apps/ibd-slides/node_modules/reveal.js/dist/theme/black.css:6:1: Cannot resolve dependency 'fonts/source-sans-pro/source-sans-pro.css'
  4 |  * By Hakim El Hattab, http://hakim.se
  5 |  */
> 6 | @import url(fonts/source-sans-pro/source-sans-pro.css);
    | ^
  7 | section.has-light-background, section.has-light-background h1, section.has-light-background h2, section.has-light-background h3, section.has-light-background h4, section.has-light-background h5, section.has-light-background h6 {
  8 |   color: #222; }
```

## 💁 Possible Solution

Unclear, but I assume that the path `fonts/source-sans-pro/source-sans-pro.css` is not being resolved relative to the directory `/Users/mmior/apps/ibd-slides/node_modules/reveal.js/dist/theme/black.css` is contained in.

## 💻 Code Sample

[This repository](https://github.com/michaelmior/ibd-slides) contains the complete code used in the example. [`public/index.html`](https://github.com/michaelmior/ibd-slides/blob/main/public/index.html) is the file being bundled.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 12.18.0
| Yarn         | 1.22.4
| Operating System | macOS Catalina 10.15.3

**Comment by michaelmior** [comment]
Update: This works if I change the dependency to start paths in `url` with `./` however it seems this should not be necessary.

**Comment by mischnic** [comment]
Strange, they should be relative to the current file anyway

**Comment by michaelmior** [comment]
@mischnic That was my assumption but it seems to not be the case.

**Comment by JannikZed** [comment]
I'm trying to bundle a node.js application with the Prisma Client as a dependency. I get this error:
```
> 1 | const prisma = require('.prisma/client')
    |                       ^
  2 | const path = require('path')
  3 |
  4 | module.exports = prisma
```
They are using an absolute path.. and I can't change that :D

**Comment by qwertie** [comment]
<s>I'm having the same problem in a different context; not sure if it's the same bug or a different one.</s>

Edit: I no longer think this is a problem with parcel, as the same problem occurs in an app created with create-react-app.

Files to repro:

### app.tsx

~~~ts
// VS Code is happy with this, parcel won't accept it (nor "./node_modules/mobx/dist/internal")
import * as internal from "mobx/dist/internal"

internal.die(12);
~~~

The error message mentions line 10 btw, which does not exist:

~~~
Server running at http://localhost:1234
×  C:\Dev\learn-react\try\app.tsx:10:36: Cannot resolve dependency 'mobx/dist/internal'
    at Resolver.resolve (C:\Users\Family\AppData\Roaming\npm\node_modules\parcel-bundler\src\Resolver.js:71:17)
    at async Bundler.resolveAsset (C:\Users\Family\AppData\Roaming\npm\node_modules\parcel-bundler\src\Bundler.js:433:18)
    at async Bundler.resolveDep (C:\Users\Family\AppData\Roaming\npm\node_modules\parcel-bundler\src\Bundler.js:484:14)
    at async C:\Users\Family\AppData\Roaming\npm\node_modules\parcel-bundler\src\Bundler.js:608:26
    at async Promise.all (index 2)
    at async Bundler.loadAsset (C:\Users\Family\AppData\Roaming\npm\node_modules\parcel-bundler\src\Bundler.js:599:21)
    at async C:\Users\Family\AppData\Roaming\npm\node_modules\parcel-bundler\src\Bundler.js:610:13
    at async Promise.all (index 0)
    at async Bundler.loadAsset (C:\Users\Family\AppData\Roaming\npm\node_modules\parcel-bundler\src\Bundler.js:599:21)
    at async Bundler.processAsset (C:\Users\Family\AppData\Roaming\npm\node_modules\parcel-bundler\src\Bundler.js:557:5)
~~~

**Comment by Rechdan** [comment]
> I'm trying to bundle a node.js application with the Prisma Client as a dependency. I get this error:
> 
> ```
> > 1 | const prisma = require('.prisma/client')
>     |                       ^
>   2 | const path = require('path')
>   3 |
>   4 | module.exports = prisma
> ```
> 
> They are using an absolute path.. and I can't change that :D

@JannikZed I'm facing this same issue, did you managed to fix that?

**Comment by MBelniak** [comment]
Same problem with prisma client on my side after migration from parcel@1 to parcel@2.
From docs 
> Bare specifiers start with any character except ., /, or ~. In JavaScript, TypeScript, and other JS-based languages, they resolve to a package in node_modules

So probably parcel treats .prisma as a relative path, because it starts with '.' smh...

**Comment by MBelniak** [comment]
Simple monkey-patch did the job
`"postinstall": "cp monkey-patch/prisma/index.js node_modules/@prisma/client/index.js"`
monkey-patch/prisma/index.js :
`module.exports = {
    ...require('../../.prisma/client/index.js'),
};
`
