### ISSUE TITLE
[Question] Is parcel suitable for building a npm package?

### ISSUE THREAD

**Issue by cyan33** [parcel-bundler/parcel#504]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

A question.

### 🎛 Configuration (.babelrc, package.json, cli command)

I'm writing a npm package, where I use the npm script to bundle the src files together into a single file. But I found the dist file doesn't bundle everything together, which causes this error: 

```js
/Users/changyan/Documents/repos/test/node_modules/react-animation-wrapper/lib/index.js:12:29: Cannot resolve dependency './emptyFunction'...
```
and when looking into the bundled file I noticed it's requiring something like this:

```js
var e,r=require("./emptyFunction")
```

My npm script looks like this:

```js
{
  "build": "parcel build ./src/index.js --out-dir ./lib",
}
```

And I searched around on the internet but didn't find something useful to resolve my problem. Also, I read a post that addressed that rollup or webpack are probably better choices for writing npm packages. Is that true? Or am I using it wrong?

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by jamesmcallister** [comment]
I think your after [https://github.com/developit/microbundle](https://github.com/developit/microbundle)

**Comment by albinotonnina** [comment]
Thanks @jamesmcallister , didn't know about this one!

**Comment by DeMoorJasper** [comment]
related to #192 Seems like u found a solution with microbundle ;)

**Comment by eldyvoon** [comment]
Having the same issue, what's wrong with using parcel-bundler for npm package bundling?

**Comment by DeMoorJasper** [comment]
@eldyvoon it should be possible

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by djstein** [comment]
@DeMoorJasper or anyone else, so what I'm reading is that adding:
```{
  "build": "parcel build ./src/index.js --out-dir ./lib",
}```
to one's `package.json` would remove the need for would remove the need for [rollup](https://github.com/rollup/rollup) or [microbundle](https://github.com/developit/microbundle)

**Comment by texastoland** [comment]
@djstein it looks like an extra option was added in #652.

**Comment by bntzio** [comment]
Interesting... but what about the TS typings files?

**Comment by tunnckoCore** [comment]
@chocolateboy don't think so.
