### ISSUE TITLE
Fix securiy vulnerabilities in parcel-bundler and @parcel/logger

### ISSUE THREAD

**Issue by SigurdMW** [parcel-bundler/parcel#5045]
#4638 🐛 bug report
I get multiple vulnerabilities when running Snyks security tool against my dependencies:

`parcel-bundler@1.12.4` and `@parcel/logger@1.11.1` are affected by many security vulnerabilities according to Snyk:
? ✗ High severity vuln found in acorn@5.7.3, introduced via @parcel/logger@1.11.1
    Description: Regular Expression Denial of Service (ReDoS)
    Info: https://snyk.io/vuln/SNYK-JS-ACORN-559469
    From: @parcel/logger@1.11.1 > grapheme-breaker@0.3.2 > brfs@1.6.1 > static-module@2.2.5 > falafel@2.1.0 > acorn@5.7.3

? ✗ High severity vuln found in acorn@6.3.0
    Description: Regular Expression Denial of Service (ReDoS)
    Info: https://snyk.io/vuln/SNYK-JS-ACORN-559469
    From: parcel-bundler@1.12.4 > htmlnano@0.2.5 > uncss@0.17.2 > jsdom@14.1.0 > acorn@6.3.0

? ✗ Medium severity vuln found in dot-prop@4.2.0
    Description: Prototype Pollution
    Info: https://snyk.io/vuln/SNYK-JS-DOTPROP-543489
    From: parcel-bundler@1.12.4 > cssnano@4.1.10 > cssnano-preset-default@4.0.7 > postcss-merge-longhand@4.0.11 > stylehacks@4.0.3 > postcss-selector-parser@3.1.1 > dot-prop@4.2.0

? ✗ Medium severity vuln found in elliptic@6.4.1
    Description: Timing Attack
    Info: https://snyk.io/vuln/SNYK-JS-ELLIPTIC-511941
    From: parcel-bundler@1.12.4 > node-libs-browser@2.2.1 > crypto-browserify@3.12.0 > browserify-sign@4.0.4 > elliptic@6.4.1

? ✗ High severity vuln found in elliptic@6.4.1
    Description: Cryptographic Issues
    Info: https://snyk.io/vuln/SNYK-JS-ELLIPTIC-571484
    From: parcel-bundler@1.12.4 > node-libs-browser@2.2.1 > crypto-browserify@3.12.0 > browserify-sign@4.0.4 > elliptic@6.4.1

? ✗ Medium severity vuln found in elliptic@6.4.1
    Description: Timing Attack
    Info: https://snyk.io/vuln/SNYK-JS-ELLIPTIC-511941
    From: parcel-bundler@1.12.4 > node-libs-browser@2.2.1 > crypto-browserify@3.12.0 > create-ecdh@4.0.3 > elliptic@6.4.1

? ✗ High severity vuln found in elliptic@6.4.1
    Description: Cryptographic Issues
    Info: https://snyk.io/vuln/SNYK-JS-ELLIPTIC-571484
    From: parcel-bundler@1.12.4 > node-libs-browser@2.2.1 > crypto-browserify@3.12.0 > create-ecdh@4.0.3 > elliptic@6.4.1

? ✗ Medium severity vuln found in minimist@1.2.0
    Description: Prototype Pollution
    Info: https://snyk.io/vuln/SNYK-JS-MINIMIST-559764
    From: @parcel/logger@1.11.1 > grapheme-breaker@0.3.2 > brfs@1.6.1 > quote-stream@1.0.2 > minimist@1.2.0

? ✗ Medium severity vuln found in minimist@0.0.8
    Description: Prototype Pollution
    Info: https://snyk.io/vuln/SNYK-JS-MINIMIST-559764
    From: parcel-bundler@1.12.4 > cssnano@4.1.10 > cssnano-preset-default@4.0.7 > postcss-svgo@4.0.2 > svgo@1.2.0 > mkdirp@0.5.1 > minimist@0.0.8

? ✗ Medium severity vuln found in node-addon-api@1.7.1
    Description: Remote Memory Exposure
    Info: https://snyk.io/vuln/SNYK-JS-NODEADDONAPI-571001
    From: parcel-bundler@1.12.4 > deasync@0.1.15 > node-addon-api@1.7.1

? ✗ High severity vuln found in serialize-to-js@3.0.0
    Description: Cross-site Scripting (XSS)
    Info: https://snyk.io/vuln/SNYK-JS-SERIALIZETOJS-536958
    From: parcel-bundler@1.12.4 > serialize-to-js@3.0.0

? ✗ Medium severity vuln found in yargs-parser@15.0.0
    Description: Prototype Pollution
    Info: https://snyk.io/vuln/SNYK-JS-YARGSPARSER-560381
    From: parcel-bundler@1.12.4 > htmlnano@0.2.5 > purgecss@1.4.1 > yargs@14.2.0 > yargs-parser@15.0.0

? ✗ Medium severity issue found in mdn-data@1.1.4
    Description: MPL-2.0 license
    Info: https://snyk.io/vuln/snyk:lic:npm:mdn-data:MPL-2.0
    From: parcel-bundler@1.12.4 > cssnano@4.1.10 > cssnano-preset-default@4.0.7 > postcss-svgo@4.0.2 > svgo@1.2.0 > css-tree@1.0.0-alpha.28 > mdn-data@1.1.4

? ✗ Medium severity issue found in mdn-data@1.1.4
    Description: MPL-2.0 license
    Info: https://snyk.io/vuln/snyk:lic:npm:mdn-data:MPL-2.0
    From: parcel-bundler@1.12.4 > cssnano@4.1.10 > cssnano-preset-default@4.0.7 > postcss-svgo@4.0.2 > svgo@1.2.0 > csso@3.5.1 > css-tree@1.0.0-alpha.29 > mdn-data@1.1.4

## 🎛 Configuration (.babelrc, package.json, cli command)

n/a

## 🤔 Expected Behavior

Package vulnerabilities are resolved quickly

## 😯 Current Behavior

Many, open vulnerabilities

## 💁 Possible Solution

`npm audit fix` and use Snyk to test you code regularly (they have a free option for Open Source)

## 🔦 Context

n/a

## 💻 Code Sample

n/a

## 🌍 Your Environment

n/a

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by ChildishGiant** [comment]
When installing with npm it found "46 high severity vulnerabilities", all of which can be fixed with `npm audit fix`

**Comment by damianobarbati** [comment]
Any news on this? Would a `resolutions` lock in parcel solve this?

**Comment by TractionTeam** [comment]
10 vulns, 4L, 2M, and 2H. Run `npm audit fix --force` with no clear resolution.

**Comment by murdocha** [comment]
also, seeing a security vulnerability for the "node-forge" dependency of the NPM parcel-bundler distribution (1.12.4).
parcel-bundler references "node-forge":"^0.7.1"

which causes this log from "npm audit" command:
```                       === npm audit security report ===                       
                                                                                
                                                                                
                                 Manual Review                                  
             Some vulnerabilities require your attention to resolve             
                                                                                
          Visit https://go.npm.me/audit-guide for additional guidance           
                                                                                
                                                                                
  High            Prototype Pollution in node-forge                             
                                                                                
  Package         node-forge                                                    
                                                                                
  Patched in      >= 0.10.0                                                     
                                                                                
  Dependency of   parcel-bundler [dev]                                          
                                                                                
  Path            parcel-bundler > node-forge                                   
                                                                                
  More info       https://npmjs.com/advisories/1561     
  ```
  
  what is a good short-term/long-term fix?

**Comment by tbsvttr** [comment]
The node-forge security issue still exists.

**Comment by DeMoorJasper** [comment]
Just realised this is a Parcel 1 issue and probably won't be fixed because of this as it's not a real security issue and you can work around it with resolutions in yarn and npm has something similar..
