### ISSUE TITLE
Provide local network address in `npx parcel dev`

### ISSUE THREAD

**Issue by mvasin** [parcel-bundler/parcel#5051]
# 🙋 feature request

I would like to expose dev server on the local network, like `serve` does.

## 🤔 Expected Behavior
This is the `serve`'s output:

```
npx serve dist-demo 

   ┌───────────────────────────────────────────────────┐
   │                                                   │
   │   Serving!                                        │
   │                                                   │
   │   - Local:            http://localhost:5000       │
   │   - On Your Network:  http://192.168.1.244:5000   │
   │                                                   │
   │   Copied local address to clipboard!              │
   │                                                   │
   └───────────────────────────────────────────────────┘
```

It contains two addresses - the localhost address and the local network address.

## 😯 Current Behavior

When starting the server with `npx parcel dev`, the webserver is only running on `localhost`.

**Comment by eddysims** [comment]
+1 on this

**Comment by devongovett** [comment]
It listens on all hosts, so you should already be able to access it via your ip.

**Comment by cozzbie** [comment]
Indeed. But it will be nice if Parcel could also show this in its terminal prompt also.
