### ISSUE TITLE
Not deduplicating between shared bundles includes asset twice in a single page

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5064]
# 🐛 bug report

In specific situations, some asset cannot be deduplicated without creating a new shared bundle, causing a single asset to be included twice in a context (and dependency chain):

JS import graph:

<img width="451" alt="Bildschirmfoto 2020-08-24 um 23 11 08" src="https://user-images.githubusercontent.com/4586894/91096922-19f52800-e65f-11ea-8c12-ee2fc2148e5b.png">

Bundle Graph (BundleS* are actually shared siblings, but this is how they are imported):

<img width="461" alt="Bildschirmfoto 2020-08-24 um 23 12 58" src="https://user-images.githubusercontent.com/4586894/91097074-5aed3c80-e65f-11ea-9c9a-2b9e4b627679.png">

If AssetC exports a React Context, Asset1 and Asset2 receive different instances.

## 😯 Current Behavior

The shared bundles optimization changes the behaviour of the code.

## 💁 Possible Solution

Not sure.

Create another shared bundle to deduplicate in shared bundles? Could hit request parallel request limit

## 🔦 Context

1. Strict equality is depended upon by React Contexts
2. side-effecty modules shouldn't be executed twice.

## 💻 Code Sample

https://github.com/mischnic/parcel-shared-double-run

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2

**Comment by garthenweb** [comment]
I though about this before, but was not sure if it is actually an issue...
What do you think about keeping both assets in each bundle but make sure (e.g. by using ids) that only one asset is executed (first bundle wins, second uses the existing module)?
This would create potential more code that is shipped but it should only apply for small bundles and it reduces the amount of network calls (that could potentially go wrong).

**Comment by mischnic** [comment]
>(first bundle wins, second uses the existing module)

We thought about that, but that only works without scope hoisting.

**Comment by devongovett** [comment]
Should be fixed with new scope hoisting implementation.
