### ISSUE TITLE
Error: Optimizer is not a constructor

### ISSUE THREAD

**Issue by alexreardon** [parcel-bundler/parcel#5065]
I am trying to write my own parcel 2 plugin.

I have copy pasted this boilerplate:

```
import { Optimizer } from '@parcel/plugin';

export default new Optimizer({
  async optimize({ bundle, contents, map }) {
	return {contents, map};
  },
});
```

When running the code, parcel spits out this error:

```
🚨 Build failed.
Error: Optimizer is not a constructor
```

- Node version: `12.16.3`
- Parcel version: `2.0.0-beta.1`

**Comment by mischnic** [comment]
Please provide a more complete example, e.g.: how are you transpiling your plugin into CJS so that Node can run it?
