### ISSUE TITLE
🙋Use fs-extra

### ISSUE THREAD

**Issue by zeakd** [parcel-bundler/parcel#508]
### 🔦 Context

Hi. How about use [fs-extra](https://www.npmjs.com/package/fs-extra) in `parcel` because it is little confuse some code use 'utils/fs' and others use 'fs' (like packager.js). Also, `fs-extra` is already Promise and have `mkdirp`, `outputFile`. 😃

**Comment by DeMoorJasper** [comment]
So u're suggesting to swap out https://github.com/parcel-bundler/parcel/blob/master/src/utils/fs.js for fs-extra?
This seems a bit overkill imo, although it could possibly make the code look cleaner

**Comment by zeakd** [comment]
Actually when I'm working on #433 I should use `fs.mkdirp` in packagers/Packager.js but it is already use 'fs' module for `createWriteStream`.

**Comment by DeMoorJasper** [comment]
What about always using utils/fs? I see your point though as utils/fs will eventually turn into `fs-extra` although `fs-extra` seems fairly large for what it actually does

**Comment by zeakd** [comment]
That's one of options. Then, should we re-exports `fs` methods on 'utils/fs'? like 
```
exports.createWriteStream = fs.createWriteStream; 
```

**Comment by DeMoorJasper** [comment]
Write and readstream should probably be kept inside the fs module.
