### ISSUE TITLE
readFileSync() results in ENOENT because the file being read shouldn't be packaged

### ISSUE THREAD

**Issue by mnapoli** [parcel-bundler/parcel#5080]
# 🐛 bug report

```js
function hasDockerCGroup() {
    return fs.readFileSync('/proc/self/cgroup', 'utf8').includes('docker');
}
```

this results in an error.

## 🎛 Configuration (.babelrc, package.json, cli command)

I don't have a `.babelrc` file.

## 🤔 Expected Behavior

The file should be ignored because it's an absolute path.

## 😯 Current Behavior

When running Parcel, this results in the following error:

> node_modules/is-docker/index.js:17:25: ENOENT: no such file or directory, open '/proc/self/cgroup'

Makes sense! But I don't want that file packaged or processed. How can I exclude it? It's a dependency, I can't even edit the code to hack around it. And it's an absolute path, it should be ignored right?

I searched in the docs but couldn't find anything helpful.

## 💁 Possible Solution

Ignore absolute paths?

## 🔦 Context

I'm running `parcel build`.

## 💻 Code Sample

```js
function hasDockerCGroup() {
    return fs.readFileSync('/proc/self/cgroup', 'utf8').includes('docker');
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 14.7.0
| npm/Yarn         |
| Operating System | MacOS

**Comment by mnapoli** [comment]
Here is the package that causes the problem: https://github.com/sindresorhus/is-docker/blob/master/index.js#L17

**Comment by mischnic** [comment]
> it should be ignored right?

This was recently fixed in Parcel 2 so that only files inside the project are inlined.

**Comment by mnapoli** [comment]
oh damn, it seems the v2 beta is not available in NPM. Any idea how to install it?

**Comment by mischnic** [comment]
With `parcel@next`

Docs: https://v2.parceljs.org/getting-started/webapp/

**Comment by mnapoli** [comment]
Thanks!
