### ISSUE TITLE
Inline style attribute not properly processed with PostCSS/Autoprefixer

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5087]
# 🐛 bug report

Inline `style=` attributes are processed by Parcel but PostCSS plugins aren't applied.

## 🤔 Expected Behavior

```
style="-moz-text-decoration: underline red;text-decoration: underline red;"
```

## 😯 Current Behavior

```html
<div style="text-decoration: underline red;">
	Hello!
</div>
```

## 💁 Possible Solution

Logging in PostCSSTransformer.js, it does get transformed but `generate` is never called...

## 💻 Code Sample

```json
{
	"dependencies": {
		"autoprefixer": "^9.8.6"
	},
	"browserslist": [
		"Firefox 30"
	]
}
```

```html
<div style="text-decoration: underline red;">
	Hello!
</div>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2

**Comment by devongovett** [comment]
Seems to work in the latest version.
