### ISSUE TITLE
Parcel Not outputting prefixed css

### ISSUE THREAD

**Issue by tms57** [parcel-bundler/parcel#5093]
I have been trying to set up Parcel to output prefixed css but have not had any luck. 
So far I've tried using a  .postcssrc config with:

{
  "plugins": {
    "autoprefixer": true
  }
}
but the outputted css had no vendor prefixes for flexbox or transforms.

Then I tried using a .browserlistrc file just using what are supposed to be defaults:

  > 0.5%,
  last 2 versions,
  Firefox ESR,
  not dead

but still nothing.

So am I missing something obvious? 
Isn't this something that should be part of the "zero-configuration" concept?

If getting Parcel to use autoprefixer IS possible, how should I be setting this up?

**Comment by mischnic** [comment]
This should work as you described. Do you have a CSS snippet that should be prefixed in this case so I can test this myself?

**Comment by tms57** [comment]
Hi Niklas.

Below is what I've been testing. Interestingly, it worked ONCE, but after
that (with no configuration changes) it just stopped working.

Here's the css that Parcel is generating:

h1
 {
  transform: rotate(-5deg);
}

._container_d127c {
  display: flex;
  flex-direction: column;
  width: 600px;
  height: auto;
}

/*# sourceMappingURL=/src.e31bb0bc.css.map */

I notice that Parcel has generated different class names
(eg: ._container_d127c)

I'm guessing this is the problem, but why is it generating class names that
can't be found???

I found one solution that said not to use "modules": true in the .postcssrc
file, but trying it with false doesn't work either.

Here is my .postcssrc file:

{
  "modules": true,
  "plugins": {
    "autoprefixer": {
      "grid": true
    }
  }
}

And what I've got in my .browserslistrc file:

defaults
not IE 11
not IE_Mob 11
maintained node versions

Thanks Ted



*Ted Shapera*

**Comment by mischnic** [comment]
> ._container_d127c {

That is definitely caused by CSS modules. Why are you setting `"modules": true` if you are not using them? Maybe deleting that line helps?

**Comment by tms57** [comment]
Niklas,  I created a github repo: https://github.com/tms57/parcel-test2

There is now no *modules: true *line in .postcssrc.

I added a .sassrc file as recommended in the docs.

But the srce31bb0bc.css generated in the dist folder still has no vendor
prefixes!
Am I doing something wrong?



*Ted Shapera*

**Comment by mischnic** [comment]
Apparently Parcel 1 doesn't process SASS files with postcss. Only CSS files are passed through postcss.

This is already fixed with Parcel 2.

**Comment by tms57** [comment]
Ok.

When is Parcel 2 available?

I am on version 1.12.4 and when I enter *npm update* no later version comes
up.

*Ted Shapera*
