### ISSUE TITLE
 Parcel build does not work normally (environment variable is set by cross-env)

### ISSUE THREAD

**Issue by rhkdgns95** [parcel-bundler/parcel#5094]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

> pacakge.json
```json
{
 "scripts": {
     // ...
    "cleanup": "rimraf .cache dist",
    "prestart": "npm run cleanup",
    "prebuild": "rimraf ./build && node ./fix-rc-table-source-code.js",
    "build": "parcel build public/index.html -d build --public-url ./ --log-level 4 --detailed-report 10",
    "build:local": "cross-env NODE_ENV=local npm run build",
    "build:dev": "cross-env NODE_ENV=development npm run build",
    "build:prod": "cross-env NODE_ENV=production npm run build",
  },
}
```

## 🤔 Expected Behavior
There are three ways to run the React build file.

1. Local only
```bash
$ yarn build:local
```
2. Development server only
```bash
$ yarn build:dev
```
3. Real operation server only
```bash
$ yarn build:prod
```

Set endpoint values ​​in environment variables through cross-env to run these three apps.

```ts
// ...
export const endpoint = process.env.GRAPHQL_ENDPOINT
```

## 😯 Current Behavior
If you look at my package.json, there are three build methods.
```
1. 'yarn build:local' - The build method requested to the endpoint of the local server.
2. 'yarn build:dev' - build method requested to the endpoint of the development server
3. 'yarn build:prod' - The build method requested to the endpoint of the actual production server.
```
The resulting build file is created normally.

However, an error occurs when executing the build file.
The only difference is the contents of the environment variable.
The only way to work is to simply enter'yarn build' to run normally.

Can you see why this is?

![image](https://user-images.githubusercontent.com/46029124/92073202-21020000-edee-11ea-95ff-98d5b40880dc.png)

## 💁 Possible Solution
...

## 🔦 Context
...

## 💻 Code Sample
- .env.local
```env
GRAPHQL_ENDPOINT=http://localhost:4000/graphql
```
- .env.development
```env
GRAPHQL_ENDPOINT=XXX
```
- .env.production
```env
GRAPHQL_ENDPOINT=XXX
```
```js
// fix-rc-table-source-code.js
const path = require('path');
const fs = require('fs');

const fileList = ['BodyContext.js', 'ResizeContext.js', 'TableContext.js'];
const folder = path.resolve(__dirname, './node_modules/rc-table/es/context');

fileList.forEach(item => {
  const file = path.resolve(folder, item);
  const context = fs.readFileSync(file).toString();
  if (!/console/mg.test(context)) {
    fs.writeFileSync(file, `${context}console.log('${item}')`)
  }
})
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  ^1.12.4 |
| Node             |v12.16.1|
| npm/Yarn         | 6.13.4 / 1.22.0 |
| Operating System | Windows 10 PRO|

**Comment by mischnic** [comment]
Are you sure this is caused by the environment variables?

**Comment by rhkdgns95** [comment]
@mischnic 

When executing parcel bundler, it works normally when cross-env is removed. I want to know why the build command should not be used with cross-env.

Since parcel contains dotenv internally, dotenv module is not installed separately.
