### ISSUE TITLE
question about react router / server side rendering

### ISSUE THREAD

**Issue by davidkwan95** [parcel-bundler/parcel#51]
This looks great! I have some question though, since we don't need to setup any configuration.
1. Can we generate all the static pages with the routes from React router?
2. How do you set this up for server side rendering?

**Comment by thejameskyle** [comment]
What do you mean by static pages from the routes? Is this something you can do in other bundlers?

I'll try to add support for parcel in React Loadable sometime for code splitting + server side rendering

**Comment by davidkwan95** [comment]
There are webpack plugins that will traverse the routes file and generate all the static pages. One example is [React Static Webpack Plugin](https://github.com/iansinnott/react-static-webpack-plugin).

I hope the best luck of luck for you guys. Can't wait to use this in production :+1:

**Comment by thejameskyle** [comment]
I think we're probably a ways off from something like this. I'd rather close it and see about a plugin system that would allow you to do this in the future within the ecosystem
