### ISSUE TITLE
Issue with parcel-plugin-* and map of requires? 

### ISSUE THREAD

**Issue by albinotonnina** [parcel-bundler/parcel#510]
### *Possibly* a 🐛 bug report

I'm testing my plugin to get inlined svgs instead of urls.

### 🤔 Expected Behavior

<img width="1253" alt="screen shot 2018-01-07 at 23 07 10" src="https://user-images.githubusercontent.com/37283/34655334-98aaa44a-f3ff-11e7-80dc-676c3c1c110f.png">

Below a screenshot of the build file:

<img width="762" alt="screen shot 2018-01-07 at 22 41 29" src="https://user-images.githubusercontent.com/37283/34655378-8507232c-f400-11e7-9df7-abf12ff0acf1.png">

### 😯 Current Behavior

<img width="1157" alt="screen shot 2018-01-07 at 23 05 37" src="https://user-images.githubusercontent.com/37283/34655332-93e0496a-f3ff-11e7-9be2-851a6827d291.png">

Below a screenshot of the build file:

![screen-shot-2018-01-07-at-22 40 05](https://user-images.githubusercontent.com/37283/34655382-8b515eb4-f400-11e7-98ae-578e499b7029.png)

### 💁 Possible *cause*

I'm asking for help people!

I guess the issue is with the asset ids...

This is kinda random...
Building and building again (eg. just changing the order of the requires) sometimes will not print the duplicate 4 (expected behaviour) but most of the times the requires will have that same numeric require (100% the number 4 in my example) hence the current behaviour. 
Numbers in general are sequential but often not (I don't know much about that, could you address me somewhere in the code?)
I'd like to start fixing this but I'd like to have a hint from you. Where to start? Is it my plugin? No idea yet. The plugin itself is very basic so far. Nothing fancy really.

### 💻 Code Sample

https://github.com/albinotonnina/parcel-plugin-inlinesvg/tree/master/example

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | any
| Node             | > 8
| npm/Yarn         | both :P
| Operating System | osx high sierra

# Thanks!

**Comment by albinotonnina** [comment]
Same happens with another plugin https://github.com/fansenze/parcel-plugin-url-loader

<img width="698" alt="screen shot 2018-01-08 at 14 57 34" src="https://user-images.githubusercontent.com/37283/34676324-5a71d506-f484-11e7-8d14-4835dc10e7ab.png">
<img width="654" alt="screen shot 2018-01-08 at 14 57 51" src="https://user-images.githubusercontent.com/37283/34676329-5d136248-f484-11e7-969e-47a07609f004.png">

**Comment by DeMoorJasper** [comment]
Does this still accure with latest master branch?

**Comment by albinotonnina** [comment]
@DeMoorJasper  afraid so!

**Comment by fathyb** [comment]
I had the same on `parcel-plugin-typescript` (see [#7](https://github.com/fathyb/parcel-plugin-typescript/issues/7)). This is because two `Asset.js` are used, one from `src` and one from `lib`, it means that you'll get duplicated IDs. [I did this](https://github.com/fathyb/parcel-plugin-typescript/blob/develop/src/frontend/assets/js-asset.ts) as a workaround :
```ts
import JSAssetLib = require('parcel-bundler/lib/assets/JSAsset')
import JSAssetSrc = require('parcel-bundler/src/assets/JSAsset')

export const JSAsset = parseInt(process.versions.node, 10) < 8 ? JSAssetLib : JSAssetSrc
```

**Comment by DeMoorJasper** [comment]
Related to #251 , the api should need an improvement to expose more internal functions in a proper way

**Comment by albinotonnina** [comment]
Thanks @fathyb, it fixes for me too.
`
const JSAssetLib = require('parcel-bundler/lib/assets/JSAsset')
const JSAssetSrc = require('parcel-bundler/src/assets/JSAsset')

const JSAsset = parseInt(process.versions.node, 10) < 8 ? JSAssetLib : JSAssetSrc
`

**Comment by devongovett** [comment]
Ah, ideally plugins wouldn't extend the internal asset types at all. The API should be better about allowing composition of assets.

**Comment by DeMoorJasper** [comment]
This no longer applies to parcel 2
