### ISSUE TITLE
Jquery UI build error

### ISSUE THREAD

**Issue by amarg26** [parcel-bundler/parcel#5114]
I have to use jqueryui in my project and whenever in include in my html and run `npm run dev` it is pointing error as 

`×  C:\Development-Folder\RHMS\css\images\ui-icons_444444_256x240.png: ENOENT: no such file or directory, open 'C:\Development-Folder\RHMS\css\images\ui-icons_444444_256x240.png'`

but `ui-icons_444444_256x240.png` is actually coming from `jquery-ui.min.js` core file. There is sure guarantee that jquery ui is unmodified and downloaded from jquery site.

Everytime I have to comment in html to build parcel.

**package.json**

```json
{
  "name": "RHMS",
  "version": "1.0.0",
  "description": "",
  "main": "postcss.config.js",
  "scripts": {
    "dev": "parcel index.html",
    "prod": "parcel index.html"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "autoprefixer": "^9.8.6",
    "jquery": "^3.5.1",
    "popper.js": "^1.16.1"
  },
  "devDependencies": {
    "cssnano-preset-advanced": "^4.0.7",
    "parcel-bundler": "^1.12.4",
    "postcss-modules": "^3.2.2",
    "postcss-uncss": "^0.17.0",
    "uncss": "^0.17.3"
  }
}
```

**Comment by mischnic** [comment]
Please provide a code sample (and the issue template is there for a reason)

**Comment by amarg26** [comment]
In my html wheever there is this tag 
`<link rel="stylesheet" href="css/jquery-ui.min.css">   `

I got error as 
`× C:\Development-Folder\RHMS\css\images\ui-icons_444444_256x240.png: ENOENT: no such file or directory, open 'C:\Development-Folder\RHMS\css\images\ui-icons_444444_256x240.png`

and this image are came from that min css

`.ui-icon,
.ui-widget-content .ui-icon {
    background-image: url("images/ui-icons_444444_256x240.png");
}
.ui-widget-header .ui-icon {
    background-image: url("images/ui-icons_444444_256x240.png");
}`


Probably the error will be thrown on this parts as well
`.ui-state-hover .ui-icon,
.ui-state-focus .ui-icon,
.ui-button:hover .ui-icon,
.ui-button:focus .ui-icon {
    background-image: url("images/ui-icons_555555_256x240.png");
}
.ui-state-active .ui-icon,
.ui-button:active .ui-icon {
    background-image: url("images/ui-icons_ffffff_256x240.png");
}
.ui-state-highlight .ui-icon,
.ui-button .ui-state-highlight.ui-icon {
    background-image: url("images/ui-icons_777620_256x240.png");
}
.ui-state-error .ui-icon,
.ui-state-error-text .ui-icon {
    background-image: url("images/ui-icons_cc0000_256x240.png");
}
.ui-button .ui-icon {
    background-image: url("images/ui-icons_777777_256x240.png");
}`
