### ISSUE TITLE
Dynamic imports not working on built project - only on the dev server

### ISSUE THREAD

**Issue by Taxi4you** [parcel-bundler/parcel#5118]
#4782 🐛 bug report

When I run `parcel index.html` (run dev server) the dynamic imports are working
When I run `parcel build index.html` (build static files for browser) the dynamic imports are not working.

This is the dynamic import I am trying to do:

```
const translations = await import('/en-us/translations.json')
await import('ltr-framework-bundle.css')
await import('/colors.css')
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
"dependencies": {
    "babel-polyfill": "^6.26.0"
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.4",
    "sass": "^1.26.8"
  }
```

There is no .babelrc or babel.config.js file.

## 🤔 Expected Behavior

First it should be working.
Second it should be work instead of this:

```
const translations = await import('/en-us/translations.json')
await import('ltr-framework-bundle.css')
```

but like this:

```
const translations = await import(`/${language}/translations.json`)
await import(`${direction}-framework-bundle.css`)
```

## 😯 Current Behavior

I got the following error when running the static files in browser (under http-server, of course):

`Unhandled Promise Rejection: Error: Cannot find module 'irlt'`

Well.. obviously - the browser doesn't know how to handle this promise which is not transformed to es5 in the build stage.
## 🔦 Context

I want to load specific files based on the locale of the user - if the user is from USA I will load English and LTR css files.
If the user is from Israel I will load Hebrew and RTL css files. etc.

So as you can see, I need to load the specific css file respectively.
## 💻 Code Sample

```
  if (new_language=="he-IL") {
      language.current = "he-IL"
      language.t = await import('/app/locales/he-IL/translations.json')
      await import('framework7/css/framework7.bundle.rtl.css')
    }
    if (new_language=="en-US") {
      language.current = "en-US"
      language.t = await import('/app/locales/en-US/translations.json')
      await import('framework7/css/framework7.bundle.css')
    }
    global.SetMonthAndDaysNames()
    await import('/colors.css')
    document.getElementsByTagName("html")[0].dir = language.t.dir
    return typeof cb !== "undefined" ? cb() : location.reload()
```

**Comment by AndrewKvalheim** [comment]
Possibly the same issue as #2515
