### ISSUE TITLE
Changing `scss`/`css` file breaks style on livereload

### ISSUE THREAD

**Issue by wesleycoder** [parcel-bundler/parcel#513]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)
The project I'm working is available [here](https://github.com/wescoder/tavern), you can checkout and reproduce the issue on it.

.babelrc:
```js
{
  "presets": ["env", "preact"],
  "plugins": [
    "transform-function-bind",
    ["transform-react-jsx", { "pragma": "h" }],
    ["module-resolver", {
      "root": ["."],
      "alias": {
        "@app": "./src"
      }
    }],
    "transform-object-rest-spread"
  ]
}
```
.postcssrc:
```
{
  "modules": true,
  "plugins": {
    "autoprefixer": {
      "grid": true
    }
  }
}
```

### 🤔 Expected Behavior
Changing a `scss` file with css modules enabled that is "named-imported" (`import s from './style.scss'`) in js and used in `className` by `preact`/`react`/etc should update the js that requires it providing the new `className` variable to it, without needing a manual full page reload.

### 😯 Current Behavior
Changing the `scss` updates the stylesheet causing the network fetch for the new asset but not for the js file, so all styles changed breaks on the page since the old classes doesn't exist anymore, to see the changes a manual full page reload is needed.

### 💁 Possible Solution
I really don't have a clue about this... Sorry...

### 🔦 Context
For example going into `src/home/home.scss` and changing `.Title` color will reproduce the bug (as of commit [451f3a2](https://github.com/wescoder/tavern/commit/451f3a2a5c23188f08419e33c8d2689e0c83e765))

### 💻 Code Sample
You can see the open sourced project here ([https://github.com/wescoder/tavern](https://github.com/wescoder/tavern))

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.4.1 |
| Node             | v9.2.0 |
| npm/Yarn         | 1.3.2
| Operating System | Linux Deepin 15.5 (Ubuntu based) |

**Comment by urfolomeus** [comment]
I have pretty much the same problem using CSS Modules but without SCSS. I figured it would be better to add to this thread than create a new one.

You can see my example project and the steps to replicate [here](https://github.com/urfolomeus/parcel-sample).

| Software | Version(s) |
|---|---|
| Parcel | 1.4.1 |
| Node | 8.8.0 |
| Yarn | 1.3.2 |
| OS | OS X 10.13.2 |

**Comment by dmsvlks** [comment]
Same problem for me when using CSS modules with HMR. This is the only thing that keeps me from using parcel for new projects.

**Comment by umamichi** [comment]
just, I confront the same problem.
For now, the only way to recompile .css file is saving .js file.

**Comment by BipinBhandari** [comment]
I was able to get fix this by setting this on .postcssrc 
```
{
  "modules": true,
  "plugins": {
    "autoprefixer": {
      "grid": true
    },
    "postcss-modules": {
      "generateScopedName": "[name]_[local]_[hash:base64:5]"
    }
  }
}
```

from  https://github.com/parcel-bundler/parcel/issues/809#issuecomment-385250361

**Comment by DeMoorJasper** [comment]
So this appears to be a mis-configuration can this be closed?

**Comment by BipinBhandari** [comment]
Please check if this is the best way to to solve this problem. And we should also update the documentation.
