### ISSUE TITLE
Parcel 2 does not build on Windows x86 or Node <10 

### ISSUE THREAD

**Issue by aminya** [parcel-bundler/parcel#5135]
# 🙋 feature request

Parcel 2 cannot be used on Node <10 or Windows x86 for bundling a package. This is a limitation which is sometimes important for the libraries that need to support older systems.

## 🤔 Expected Behavior

Build across multiple Node versions.

## 😯 Current Behavior

Windows x86 fails to build (the library is used for Atom which ships x86 binaries)
https://github.com/parcel-bundler/source-map/issues/31

Noe <10 fails to build (the library is used for multi-threading on a wide range of systems).
https://travis-ci.org/github/andywer/threads.js/builds/726670968

## 💁 Possible Solution

- fallback to JavaScript-based source map on Node <10 or Windows x86 instead of using a native module. 
or
- Build the native module on all versions and operating systems

## 🔦 Context

Many electron apps such as Atom ship x86 binaries. Most used libraries should be supported on a wide range of systems

Source map is not a "critical" part of Parcel, and it should not block the users from using Parcel just because of this. The compile-time benefit of using a native module should not limit the scope of Parcel 2 users.

**Comment by devongovett** [comment]
Node < 10 is not supported by Parcel 2 as it is no longer maintained by Node. See current LTS schedule: https://nodejs.org/en/about/releases/.

**Comment by DeMoorJasper** [comment]
This is already being tracked in the sourcemap repo. will close this as Devon mentioned we no longer support < node 10
