### ISSUE TITLE
Invalid Parcel Config

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#5137]
# 🐛 bug report

I'm trying to make a reporter plugin but while trying to launch the process, i'm getting an instant error thrown
```
[0] [ThrowableDiagnostic [Error]: Invalid Parcel Config] {
[0]   diagnostics: [
[0]     {
[0]       message: 'Invalid Parcel Config', 
[0]       origin: '@parcel/core',
[0]       filePath: '.parcelrc',
[0]       language: 'json',
[0]       codeFrame: [Object]
[0]     }
[0]   ]
[0] }
```

my current `.parcelrc` file is 
```json
{
  "extends": "@parcel/config-default",
  "reporter": "parcel-reporter-asar"
}

```

and the error thrown is from the `get-port` package

```js

const getPort = options => {
	options = Object.assign({}, options);

	if (typeof options.port === 'number') {
		options.port = [options.port];
	}

	return (options.port || []).reduce(
		(seq, port) => seq.catch(
			() => isAvailable(Object.assign({}, options, {port}))
		),
		Promise.reject() // ERROR THROWN IS "Exception has occurred: undefined"
	);
};
```

As a reporter plugin for now I copy/pasted the default reporter from parcel & removed the Flow types.
I correctly named the plugin following the naming convention `parcel-reporter-asar`

**Comment by mischnic** [comment]
One correct config would be `reporters: ['parcle-reporter-asar']` (https://v2.parceljs.org/configuration/plugin-configuration/).

But the error should obviously tell you this...

**Comment by Banou26** [comment]
Even with
```json
{
  "extends": "@parcel/config-default",
  "reporter": ["parcel-reporter-asar"]
}
```
it stills throw the same error
I also tried with
```json
{
  "extends": "@parcel/config-default",
  "reporter": ["@parcel/resolver-default", "parcel-reporter-asar"]
}
```
same result

**Comment by devongovett** [comment]
What's in the codeFrame property? Does that point to the issue?

**Comment by Banou26** [comment]
@mischnic fix corrected the problem.

**Comment by devongovett** [comment]
Default reporter should already handle showing the codeframe. I guess you're using the programmatic API though?

**Comment by Banou26** [comment]
No, i was running the CLI `parcel src/index.tsx`

**Comment by mischnic** [comment]
So I get this with the latest nightly:

```
$ yarn parcel index.js
yarn run v1.22.5
warning package.json: No license field
$ .../5137-config-diagnostic/node_modules/.bin/parcel index.js
@parcel/core: Invalid Parcel Config
.parcelrc:3:2
  2 |   "extends": "@parcel/config-default",
> 3 |   "reporter": "parcel-reporter-asar"
>   |   ^^^^^^^^^^ Did you mean "reporters"?
  4 | }
✨  Done in 0.52s.
```

**Comment by Banou26** [comment]
After upgrading to the latest nightly, the correct message gets reported.
(I thought that it was already upgraded, my bad)
