### ISSUE TITLE
parcel adds require where it shouldn't

### ISSUE THREAD

**Issue by jprochazk** [parcel-bundler/parcel#5139]
Using parcel-bundler 1.12.4

In an Electron BrowserWindow with `nodeIntegration: true`, trying to access `process.versions` returns an empty object, even though it should contain some version numbers (node, chrome, electron, etc).

The problem here is that parcel adds the `require("process")` into the output js file, even though in the actual code, I do not import/require it.

CLI command:
```
PS C:\app\> npx parcel ./src/index.html -d ./dist/
```

The code:
```ts
const nv = document.querySelector("#node-version");
if (nv) nv.innerText = process.versions.node;

const cv = document.querySelector("#chrome-version");
if (cv) cv.innerText = process.versions.chrome;

const ev = document.querySelector("#electron-version");
if (ev) ev.innerText = process.versions.electron;
```

The relevant output:
```js
var process = require("process");
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

var nv = document.querySelector("#node-version");
if (nv) nv.innerText = process.versions.node;
var cv = document.querySelector("#chrome-version");
if (cv) cv.innerText = process.versions.chrome;
var ev = document.querySelector("#electron-version");
if (ev) ev.innerText = process.versions.electron;
```

Removing the line
```js
var process = require("process");
```
from the generated output fixes the issue, and causes no other errors.

**Comment by jprochazk** [comment]
I don't know if this is sustainable, but my solution was to rename the node `require` in a script placed at the top of the html:

```html
<html>
    <head>
        <meta charset="UTF-8" />
        <title>Hello, World!</title>
        <meta
            http-equiv="Content-Security-Policy"
            content="script-src 'self' 'unsafe-inline';"
        />
        <script>
            window.nodeRequire = require;
            delete window.require;
            delete window.exports;
            delete window.module;
        </script>
        <link rel="stylesheet" href="./main.css" />
        <script src="./index.ts" async defer></script>
    </head>
    <body>
        <!-- ... -->
    </body>
</html>
```

**Comment by mischnic** [comment]
> npx parcel ./src/index.html -d ./dist/

Have you tried `-t electron` ? Though this might come with other problems...

**Comment by jprochazk** [comment]
> > npx parcel ./src/index.html -d ./dist/
> 
> Have you tried `-t electron` ? Though this might come with other problems...

I tried it, and you were right, it comes with other problems. Files are built and bundled correctly, but they aren't showing up. I'm guessing my build setup is wrong, but I can't seem to find any documentation on Parcel targets, outside of the fact that [they exist](https://parceljs.org/cli.html#target).
