### ISSUE TITLE
Inline CSS background-image not showing

### ISSUE THREAD

**Issue by owendlee** [parcel-bundler/parcel#5140]
##Hello, I am a beginner with regards to CSS and HTML but have searched everywhere for a solution to this and still have no idea what is going on. 

I am attempting to create a background image with a logo/subtitle on top of it. Although only the subtitle is showing up, I have gone over the syntax multiple times and am still unsure of where the error is, or if 

#HTML:
```
<div class="blog-type-wrapper">
        <div class="blog-type-img-background" style="background-image:url(images/software.jpg)"></div>
        <div class="img-text-wrapper">
          <div class="logo-wrapper">
            <img src="images/software-logo.png" alt="soft">
          </div>
          <div class="subtitle">
            Software N Stuff
          </div>
        </div>
      </div>
```

#CSS
```
.blog-type-img-background{
  height:500px;
  width:100%;
  background-size:cover;
  background-position:center;
  background-repeat:no-repeat;
}
```

There is space on the webpage allocated to the image, however no images appear. The images are in another folder named "images" in the same directory as both the html and css files.

**Comment by Natetronn** [comment]
This doesn't have anything to do with Parcel.js rather, it's an HTML and CSS question. Anyway...

Consider putting the background-image into the CSS itself, instead of inline and the format calls for quotation marks.

So either this:

```
.blog-type-img-background{
  height:500px;
  width:100%;
  background-image:url("images/software.jpg");
  background-size:cover;
  background-position:center;
  background-repeat:no-repeat;
}
```
Or this:
`<div class="blog-type-img-background" style="background-image:url("images/software.jpg")"></div>`

Make sure your paths are setup correctly as well. For example, are you able to `<img src="images/software-logo.png" alt="soft">` on its own?

**Comment by Natetronn** [comment]
You might look into [object-fit]( https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) as well.

**Comment by mischnic** [comment]
Closing this as it's not related to Parcel.

**Comment by HarshRajpoot-code** [comment]
Same issue after shifting to ParcelJS. Every image stopped loading, flickers for 1 second and not load after that, made the local files work by using `URL(file, import.meta.url).href` but no fix for CSS images.
