### ISSUE TITLE
Add back `--hmr-port`

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5150]
# 🙋 feature request

Add back a `--hmr-port` CLI flag.

## 🤔 Expected Behavior

Being able to do `parcel --hmr-port 9999 index.html`.

`parcel --port 5555 index.html` should point both HTTP server and HMR to port 5555.
The `--hmr-port` would override that value for HMR only.

## 💁 Possible Solution

The dev server itself should already support this. I think we just didn't add it as a CLI flag.

https://github.com/parcel-bundler/parcel/blob/52f365668013a08b8afa03e549934a6137eb9c4d/packages/core/parcel/src/cli.js#L89-L100

https://github.com/parcel-bundler/parcel/blob/52f365668013a08b8afa03e549934a6137eb9c4d/packages/core/parcel/src/cli.js#L346

**Comment by RizkyRajitha** [comment]
hi i like to work on this issue , 
i should add the `--hmr-port` to the `hmrOptions ` var in  `parcel/packages/core/parcel/src/cli.js` 
am i correct

**Comment by mischnic** [comment]
Correct 👍

**Comment by RizkyRajitha** [comment]
thanks i will make a pr

**Comment by RizkyRajitha** [comment]
hi @mischnic 

i added `  '--hmr-port': 'hot module replacement port',` to `parcel/packages/core/parcel/src/cli.js` file 
and to debug run in `parcel/simple-example` in path `packages/examples/simple`

 `parcel  src/index.js --port 8080`  command works fine but when i add `--hmr-port` , `parcel  src/index.js --port 8080 --hmr-port 9999 `

![port](https://user-images.githubusercontent.com/38534289/93783725-adfbe480-fc49-11ea-89d3-688a62394e9c.PNG)


it show errors

![hrmr](https://user-images.githubusercontent.com/38534289/93783730-b0f6d500-fc49-11ea-8ef4-aa95843341ae.PNG)


is it not reading the arguments correctly . 

thank you.

**Comment by mischnic** [comment]
You need to do `+  '--hmr-port <port>': 'hot module replacement port',` so that the number following that is actually used as a HMR port and not as an entry folder.

**Comment by RizkyRajitha** [comment]
thanks ,
now it is working 

simple js example

![adass](https://user-images.githubusercontent.com/38534289/94364752-46321780-00e9-11eb-9094-0d78fde8b47e.PNG)

html example

![hmra](https://user-images.githubusercontent.com/38534289/94364754-48947180-00e9-11eb-9735-4d6546b7634d.PNG)

but i am getting this one test failed . 

![tests](https://user-images.githubusercontent.com/38534289/94364864-159ead80-00ea-11eb-9bd8-69ec4a0e761e.PNG)

**Comment by mischnic** [comment]
Open a PR with your changes, symlinks on Windows are a bit problematic - we'll see.

**Comment by RizkyRajitha** [comment]
hi 
opened pull request #5187 

thank you
