### ISSUE TITLE
PostCSS 8

### ISSUE THREAD

**Issue by ai** [parcel-bundler/parcel#5152]
# 🙋 feature request

Update PostCSS from 7 to 8 in `v2` branch.

## 🔦 Context

[PostCSS 8 changelog](https://github.com/postcss/postcss/releases/tag/8.0.0)

PostCSS 8 came with a new plugin API. Right now Parcel users can use new PostCSS plugins because Parcel uses PostCSS 7.

PostCSS 8 has no breaking changes for Parcel 2 since Parcel 2 already dropped Node.js 6 and 8 support.

**Comment by mischnic** [comment]
So plugins for PostCSS 7 also work with version 8?

**Comment by ai** [comment]
Yeap. But PostCSS will show a warning and about using deprecated API.

**Comment by mischnic** [comment]
- Autoprefixer 10 (the latest version) supports only PostCSS 8
- Parcel uses https://github.com/css-modules/postcss-modules, which isn't updated yet

**Comment by aminya** [comment]
This can also help using Uncss with Parcel.
https://github.com/parcel-bundler/parcel/issues/1276#issuecomment-697131843

**Comment by ChristophP** [comment]
I also had this issue with `parcel@2.0.0-beta.1`. It was fixed once I cleared `.cache` and `node_modules`.
