### ISSUE TITLE
os.networkInterfaces() in Electron always returns an empty object

### ISSUE THREAD

**Issue by purplnay** [parcel-bundler/parcel#5154]
# 🐛 bug report

Calling networkInterfaces from Node's os module returns an empty object in Electron's browserWindow.

## 🎛 Configuration (.babelrc, package.json, cli command)

I am using this command to build my project:
```json
{
  "dev": "parcel watch src/index.html --public-url ./ target electron --out-dir build",
}
```

## 🤔 Expected Behavior

```js
import { networkInterfaces } from 'os';

console.log(networkInterfaces()); // => NetworkInterface[][]
```
When running this code (using require) with node.js, I get an object containing multiple network interfaces, same when running it from the console in Electron's browser window.

## 😯 Current Behavior

Using this code (with import or require) within my app that then gets bundled by Parcel will give me an empty object `{}` every time.

## 💁 Possible Solution

I took a look at the bundle's code and found this:
```js
exports.networkInterfaces
= exports.getNetworkInterfaces
= function () { return {} };
```
which comes from the os-browserify package in its `browser.js` file.

It seems like the bundle makes it in a way that if I am in a browser environment it will load the browserify version of the os module, and if not, it will load node's version.

## 🔦 Context

I don't know how all this works behind the scene but I am compiling for Electron and explicitly declaring it in my CLI command, so I wonder why I am getting some packages, such as browser implementations of Node's standard library, bundled with my code.

## 💻 Code Sample

```js
// index.js
import Vue from 'vue';
import getInterfaces from './utils';

console.log(getInterfaces());
```

```js
// utils.js
import { networkInterfaces } from 'os';

export const getInterfaces = () => {
  return networkInterfaces();
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 14.10.1
| npm/Yarn         | 6.14.8/1.22.5 (using Yarn)
| Operating System | Windows 10

**Comment by mischnic** [comment]
It should be `--target electron`, but that probably just a typo.

**Comment by purplnay** [comment]
Woops **_\*facepalm\*_**
Thanks for pointing that out, I actually had it wrong in my `package.json`
