### ISSUE TITLE
Parsing static json files without importing them as a module

### ISSUE THREAD

**Issue by moritzsalla** [parcel-bundler/parcel#5155]
# 🐛 bug report

I am trying to include a static manifest.json file in my bundle, yet Parcel transcribes my json to js. Using a .manifest file is not an option, as Chrome only recognises manifest.json files in Chrome browser extensions.

## 🎛 Configuration

```
parcel build --no-content-hash src/*.html src/*.ts src/*.js src/*.json --out-dir dist/chrome/
```

## 🤔 Expected Behavior

Move my static json file to `dist` without transcribing or renaming it.

## 😯 Current Behavior

Parcel outputs `manifest.js` + `manifest.js.map` files during build.

## 💁 Possible Solution

Add static imports for json files.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel | 1.12.4 |
| Node | 12.18.2 |
| npm/Yarn | 1.22.5 |
| Operating System | macOS Catalina |

**Comment by Spy-Seth** [comment]
I have the same need to be able to use the v2.

With parcel v1 I'm using the plugin https://github.com/elwin013/parcel-plugin-static-files-copy

**Comment by moritzsalla** [comment]
My solution is to run a `cp` bash command after `parcel build`, but this probably isn't the most sustainable thing to do.

I guess I'll have to install the beta for V2, the repository wasn't really clear on this.
