### ISSUE TITLE
Stylus wants the is-obj npm package when running parcel build

### ISSUE THREAD

**Issue by krstffr** [parcel-bundler/parcel#5156]
# 🐛 bug report
When running `parcel build main.ts` with a bunch of stylus files I get  an error that the module `is-obj` is missing. Running just `parcel main.ts` works. 

Running `npm i is-obj` solves the problem. 

The problem first started after I ran `npm audif fix`, and the is-obj npm package removed from dot-prop requires (see screenshot).

![bild](https://user-images.githubusercontent.com/93975/93486359-651ff500-f904-11ea-8b4c-b746c871022d.png)

## 🎛 Configuration (.babelrc, package.json, cli command)

Package.json:

```js
{
  "devDependencies": {
    "@babel/core": "^7.11.6",
    "@babel/plugin-transform-react-jsx": "^7.10.4",
    "core-js": "^3.6.5",
    "is-obj": "^2.0.0",
    "parcel": "^1.12.4",
    "stylus": "^0.54.8",
    "typescript": "^3.9.7"
  },
  "dependencies": {
    "preact": "^10.4.8"
  },
}
```

## 🤔 Expected Behavior

Build the js/css.

## 😯 Current Behavior

Throws an error.

```
×  REDACTED\templates\components\signup_form.styl:undefined:undefined: Cannot find module 
'is-obj'
Require stack:
- REDACTED\node_modules\dot-prop\index.js
- REDACTED\node_modules\postcss-minify-selectors\node_modules\postcss-selector-parser\dist\parser.js
- REDACTED\node_modules\postcss-minify-selectors\node_modules\postcss-selector-parser\dist\processor.js
- REDACTED\node_modules\postcss-minify-selectors\node_modules\postcss-selector-parser\dist\index.js
- REDACTED\node_modules\postcss-minify-selectors\dist\index.js
- REDACTED\node_modules\cssnano-preset-default\dist\index.js
- REDACTED\node_modules\cssnano\dist\index.js
- REDACTED\node_modules\parcel\src\utils\localRequire.js
- REDACTED\node_modules\parcel\src\Bundler.js
- REDACTED\node_modules\parcel\index.js
- REDACTED\node_modules\parcel\src\cli.js
- REDACTED\node_modules\parcel\bin\cli.js
```

## 💁 Possible Solution

Installning `is-obj` solves it.

## 🔦 Context

See above.

## 💻 Code Sample

NA

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.4
| Node             | 12.18.3
| npm/Yarn         |  NPM 6.14.5
| Operating System | Windows 10

**Comment by mischnic** [comment]
Which version of `dot-prop` do you have installed?

https://unpkg.com/browse/dot-prop@5.3.0/package.json does declare it as a dependency...

**Comment by krstffr** [comment]
@mischnic according to the screenshot from the package-lock file above the version is 4.2.0.
