### ISSUE TITLE
404 on Readme

### ISSUE THREAD

**Issue by peterennisrda** [parcel-bundler/parcel#516]
![capture1299](https://user-images.githubusercontent.com/1280523/34694140-e1ab335a-f47a-11e7-9c50-205d10a9a2cc.PNG)
![capture1298](https://user-images.githubusercontent.com/1280523/34694141-e1ca00fa-f47a-11e7-9502-8faf9350ed95.PNG)

**Comment by DeMoorJasper** [comment]
Should be fixed in my PR, although the svg doesn't work and i'll look into that as well
