### ISSUE TITLE
Watch mode broken for internally resolvable async dependencies

### ISSUE THREAD

**Issue by wbinnssmith** [parcel-bundler/parcel#5163]
When generating runtime code for internally resolvable async dependencies, the JSRuntime currently unnecessarily creates a dependency on user code: 

https://github.com/parcel-bundler/parcel/blob/2e0f1afca926b14d03478f8445651edfecf555ee/packages/runtimes/js/src/JSRuntime.js#L99-L101

This dependency on user code is found when transforming the runtime code, causing Parcel to read from the filesystem and hash the user code. Since this takes place during runtime generation, after the initial transformation phase, this results in a cache hit and further transformation stops.

Not only is this inefficient, but it also results in a runtime graph that is dependent on user code that isn't invalidated on change **and breaks watch mode when changing these assets**. The runtime asset, unlike the main asset graph, is not currently invalidated on filesystem changes.

We should:

* [x] Invalidate the runtime graph on file changes, in case another runtime plugin uses user code intentionally, or during local plugin development.
* [ ] In the case of internally resolvable async dependencies, refer to the inner synchronous dependency somehow else, such as by referring to the asset id and avoiding `require` in the generated code. `parcelRequire` is an option, but using it this way seems only to be an option ~~in the global output format~~ outside of scope hoisting.

cc @padmaia @mischnic @devongovett

**Comment by padmaia** [comment]
I'll start working on the first todo

**Comment by mischnic** [comment]
@wbinnssmith I think this is fixed by https://github.com/parcel-bundler/parcel/pull/5486?

**Comment by devongovett** [comment]
Appears that we are directly referencing the asset by id now.

https://github.com/parcel-bundler/parcel/blob/20f2f14a806cc2fcba4d33979add2ac11dce78eb/packages/runtimes/js/src/JSRuntime.js#L97
