### ISSUE TITLE
Allow to override cpu count auto detection using -j, --jobs flag or similar

### ISSUE THREAD

**Issue by sternenseemann** [parcel-bundler/parcel#5170]
# 🙋 feature request

It'd be great to have a way to override the detection of CPUs for parcel by manually specifying a job count.
This is useful if you are building in a restricted environment — [nix](https://nixos.org/) for example sandboxes
the build so `/sys/` which is used by `physical-cpu-count` is not present.

## 💁 Possible Solution

* Adding a `-j` or `--jobs` flag like many build systems have
* Adding an enviroment variable to influence the setting

**Comment by mischnic** [comment]
PARCEL_WORKERS should work.

**Comment by sternenseemann** [comment]
Awesome thank you that works. Do you know where this is documented? I looked earlier, but couldn't find anything of the sort.

**Comment by mischnic** [comment]
Good point, not at all as far as I can see...
