### ISSUE TITLE
Semantic UI React Error: Unknown version 59 of op_mob

### ISSUE THREAD

**Issue by evolfo** [parcel-bundler/parcel#5172]
# 🐛 bug report

Similar issue to this: https://github.com/parcel-bundler/parcel/issues/5164, I get this message when I try to start my server using npm start. 

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json: 

```js
{
  "name": "name",
  "version": "1.0.0",
  "description": "description",
  "main": "index.js",
  "scripts": {
    "start": "parcel index.html",
    "build": "parcel build index.html",
    "sitemap": "babel-node sitemap-builder.js"
  },
  "resolutions": {
    "browserslist": "4.14.4",
    "caniuse-lite": "1.0.30001129"
  },
  "author": "author",
  "license": "ISC",
  "dependencies": {
    "containers": "0.0.1",
    "emailjs-com": "^2.6.3",
    "iframe-resizer-react": "^1.0.3",
    "parcel-plugin-compress": "^2.0.2",
    "parcel-plugin-purifycss": "^1.0.5",
    "puppeteer-core": "^2.1.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-helmet": "^6.1.0",
    "react-markdown": "^4.3.1",
    "react-remarkable": "^1.1.3",
    "react-router-dom": "^5.1.2",
    "react-router-sitemap": "^1.2.0",
    "react-router-sitemap-builder": "^1.1.1",
    "remarkable": "^2.0.1",
    "semantic-ui-carousel-react": "^1.1.3",
    "semantic-ui-react": "^0.88.2"
  },
  "devDependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.9.0",
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/plugin-transform-runtime": "^7.9.0",
    "@babel/preset-env": "^7.9.0",
    "@babel/preset-react": "^7.9.1",
    "@babel/register": "^7.9.0",
    "@babel/runtime": "^7.9.2",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-wildcard": "^6.0.0",
    "marked": "^1.1.1",
    "parcel-bundler": "^1.12.4",
    "parcel-plugin-purgecss": "^3.0.0",
    "react-router-sitemap": "^1.2.0",
    "react-router-sitemap-builder": "^1.1.1",
    "sass": "^1.26.10"
  }
}

```

.babelrc:
```
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "targets": {
                    "browsers": [
                        ">0.25%",
                        "not ie 11",
                        "not op_mini all"
                    ]
                }
            }
        ],
        "@babel/preset-react"
    ],
    "plugins": [
        "@babel/plugin-transform-runtime",
        ["wildcard", {"exts": [
                "js",
                "es6",
                "es",
                "jsx",
                "md"
            ]}
        ]
    ]
}
```

## 🤔 Expected Behavior

Expected Parcel to build/run

## 😯 Current Behavior

Just errors, impossible to run successfully

## 💁 Possible Solution

I tried following the thread I linked above and this one as well: https://github.com/browserslist/browserslist/issues/537, however, they didn't seem to resolve my issue. 

## 🔦 Context

I'm unable to test my web app, or do any development. 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 13.8.0
| npm/Yarn         | 6.13.6
| Operating System | Mac OS 10.14.6

**Comment by rlacko58** [comment]
Have you tried installing the latest [browserslist npm package](https://www.npmjs.com/package/browserslist)? 
(https://github.com/parcel-bundler/parcel/issues/5164#issuecomment-696926731)

**Comment by mischnic** [comment]
Can you share a code sample so that I can reproduce the error?

**Comment by evolfo** [comment]
> Have you tried installing the latest [browserslist npm package](https://www.npmjs.com/package/browserslist)?
> ([#5164 (comment)](https://github.com/parcel-bundler/parcel/issues/5164#issuecomment-696926731))

Ah that's what fixed it, thank you! I thought it might be different since it was saying semantic-ui-react instead of browserslist in the other thread.
