### ISSUE TITLE
[Feature] Create a separate file consisting of common modules shared between multiple entry points?

### ISSUE THREAD

**Issue by samithaf** [parcel-bundler/parcel#518]
In the following example when I build the app with parcel.js angular loads two times which is not great. Currently I am using webpack CommonsChunkPlugin to handle this use case. 

E.g.

bootstrap.js
```
import angular from 'angular';

angular.element(document).ready(() => {
  angular.bootstrap(document.body, ['app'], { strictDi: true })
});
```

app.js

```
import angular from 'angular';

const moduleNames = APP_CONFIG.moduleNames;

// Bootstrap the application
const appModule = angular
  .module('app', moduleNames);

export default appModule;
```

**Comment by DeMoorJasper** [comment]
You could write an index.js as entrypoint and include bootstrap.js and app.js from there than they should share angular, otherwise it's impossible

**Comment by samithaf** [comment]
Well i just demonstrate the issue. I am trying to benchmark very large angular app currently on webpack. I have independent modules which gets lazy loads to gain performance. E.g. trading.bundle.js, portfolio.bundle.js. 

Sure I can simply concat all files in to a one but that will be very bad for performance.

**Comment by DeMoorJasper** [comment]
For angular you might be intrested in this plugin, not sure if it already supports the lazy loading https://github.com/fathyb/parcel-plugin-angular
I think what you are suggesting are improvements that we'll look at once treeshaking has landed, thanks for reporting.

**Comment by samithaf** [comment]
Thanks for considering the requirement. The plugin looks like only supports Angular 2+ and our application is on angular 1.6.x. Having said that I am sure the feature that I am requesting will be applicable to other apps based on React or Vue.

**Comment by itaditya** [comment]
@samithaf I'm also stuck with AngularJs 1.6.x app, were you able to work out something?

**Comment by samithaf** [comment]
@itaditya what's the error you are getting?

**Comment by itaditya** [comment]
In my case, the app is not even working, on the console I get module not found ..

Environment -
Windows 7, node v9.3.0, parcel v1.4.1, angular v1.6.8

**Comment by samithaf** [comment]
@itaditya Looks like at the stage parcel is not printing helpful errors. In my case following are the issues.
App has dynamic html attribute values. E.g. href or src
App has scss imports from node modules 
Angular loads many times due to no common chunks plugin kind of a feature

**Comment by devongovett** [comment]
See #189.
