### ISSUE TITLE
Web Workers not working

### ISSUE THREAD

**Issue by dioptre** [parcel-bundler/parcel#5180]
# 🐛 bug report

If you create a worker and use https://github.com/parcel-bundler/parcel/pull/3654 it seems to inject react-refresh and breaks the worker:

Worker1:
```
Uncaught ReferenceError: $RefreshReg$ is not defined
    at Object.e8f074bdcf290c40c28607a1be166da6.process
```

Worker2:
```
encoderWorker.18d1c79e.js:58 Uncaught Error: Cannot find module '6a2f65278353e882d7f14bcf674e0c85'
    at newRequire (encoderWorker.18d1c79e.js:58)
    at newRequire (encoderWorker.18d1c79e.js:42)
    at localRequire (encoderWorker.18d1c79e.js:80)
    at Object.64c1770b35b04eb343009bb27a752262.react-refresh/runtime (ReactRefreshRuntime.js:2)
    at newRequire (encoderWorker.18d1c79e.js:68)
    at encoderWorker.18d1c79e.js:111
    at encoderWorker.18d1c79e.js:134
```

## 🎛 Configuration (.babelrc, package.json, cli command)
```
{
  "extends": "@parcel/config-default",
  "transformers": {
    "rawjs:*": [
      "@parcel/transformer-raw",
       "@parcel/transformer-js"
    ]
  }
}
```

```
{
  "name": "browser",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "start": "parcel serve ./src/index.html",
    "build": "parcel build ./src/index.html",
    "nginx": "docker run -p 80:80 -v $(pwd)/dist:/usr/share/nginx/html nginx"
  },
  "targets": {
    "default": {
      "context": "browser"
    }
  },
  "dependencies": {
    "@material-ui/core": "^4.9.1",
    "@material-ui/icons": "^4.9.1",
    "common": "*",
    "hammerjs": "^2.0.8",
    "js-cookie": "^2.2.1",
    "mmirror": "^1.0.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "uuid": "^8.3.0"
  },
  "devDependencies": {
    "classnames": "^2.2.6",
    "live-server": "^1.2.1",
    "sass": "^1.26.10"
  }
}
```
## 🤔 Expected Behavior

React-Refresh should not be injected into the workers. Example:

```
      });

      // <script>
    } else if (globalName) {
      this[globalName] = mainExports;
    }
  }
})({"64c1770b35b04eb343009bb27a752262":[function(require,module,exports) {
var Refresh = require('react-refresh/runtime');

Refresh.injectIntoGlobalHook(window);
```

## 😯 Current Behavior

React-Refresh is injected into the workers, and the dependencies break, breaking the app.

## 💁 Possible Solution

Don't inject react-refresh into the workers

## 🔦 Context

Stopped us from developing without waiting for 60 seconds builds :/
Parcel serve is broken, but parcel build is ok.
Parcel server --no-hmr works

## 🌍 Your Environment

parcel@next
node 14
mac

thanks!

.....

Ok seems like there's also poor support for:

audioWorklet

Seems that this doesn't work at all. Maybe we need to implement workers in worklets too?

This can be fixed by using normal workers.

But before I ran the worker, I had to remove:

"@parcel/transformer-js"

as it seemed parcel mangled the worker in a really bad way. I started getting this craziness:

Uncaught RangeError: Maximum call stack size exceeded.
    at VM3 encoderWorker.min.b9542d47.js:1
    at VM4 encoderWorker.min.0dec9b5a.js:1

I changed the .parcelrc to this:

"transformers": {
    "rawjs:*": [
      "@parcel/transformer-raw"
    ]
  }

which is working in dev mode....

BUT when I parcel build in prod, the build is breaking per #3676:

🚨 Build failed.
@parcel/packager-js: The expression evaluated to a falsy value:

  (0, _assert.default)(typeof v === 'string')

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value

The crazy thing is all I want to do is import a static/inline js file and access it within parcel. The fact you can't just pull in a raw js file seems nuts to me :/ Am I missing something? Can I just pull it in somewhere else?

Really stuck, please help!

@ProLoser

....

Also if I try to use the url: pattern instead of the rawjs one above I get the following:
```
encoderWorker.js:1730 Uncaught RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.
```

Seems there's more bad mangling by parcel. 

....

So in summary I can work around the issue by using (the only way I see so far):

```
"transformers": {
    "rawjs:*": [
      "@parcel/transformer-raw"
    ]
  }
```

I need to include the audioWorklet as 
```
import EC_PATH from 'rawjs:./encoderWorker.min.js';
...
this.audioContext.audioWorklet.addModule(EC_PATH);
```
elsewhere in the code I also need to use the standard method for using web workers (I need to do this as parcel mangles irreparably the EC_PATH version):
```
this.encoder = new Worker('./encoderWorker.min.js');
```
notice I can't use the worker equivalent as audioWorklet's are not supported. This leaves with me with two encoderWorker.min.[#number].js files... 

The only time parcel build works is if I update the utils assertion (hack for now):
@parcel/scope-hoisting/lib/utils.js
```
function assertString(v) {
  (0, _assert.default)(typeof v === 'string' || typeof v === 'undefined');
  return v;
}
```

as this breaks for parcel build.

Would be great if we could just add a "raw" transformer without the need to build so much hack into the "nocode".

@mischnic this is your PR mate, have you got any ideas what the best way to go about fixing this?

**Comment by dioptre** [comment]
Ok seems like there's also poor support for:
```
audioWorklet
```

Seems that this doesn't work at all. Maybe we need to implement workers in worklets too?

This can be fixed by using normal workers.

But before I ran the worker, I had to remove: 

```
"@parcel/transformer-js"
```
as it seemed parcel mangled the worker in a really bad way. I changed the .parcelrc to this:

```
"transformers": {
    "rawjs:*": [
      "@parcel/transformer-raw"
    ]
  }
```

which is working in dev mode....

BUT when I parcel build in prod, the build is breaking per https://github.com/parcel-bundler/parcel/issues/3676:

```
🚨 Build failed.
@parcel/packager-js: The expression evaluated to a falsy value:

  (0, _assert.default)(typeof v === 'string')

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value
```

The fact you can't just pull in a raw js file seems nuts to me :/

Really stuck, please help!

**Comment by dioptre** [comment]
Also if I try to use the url: pattern instead of the rawjs one above I get the following:
```
encoderWorker.js:1730 Uncaught RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.
```

Seems there's more bad mangling by parcel.

**Comment by dioptre** [comment]
So in summary I can work around the issue by using (the only way I see so far):

```
"transformers": {
    "rawjs:*": [
      "@parcel/transformer-raw"
    ]
  }
```

but this breaks for parcel build, as it tries to enforce the js transform. How would we feel about removing that assertion?

**Comment by mischnic** [comment]
Please keep the issue description more structured

> audioWorklet

-> https://github.com/parcel-bundler/parcel/issues/1093

> The expression evaluated to a falsy value:

`@parcel/package-js` requires `@parcel/transformer-js`.

>  `import EC_PATH from 'rawjs:./encoderWorker.min.js'; `

There is some investigation here: https://github.com/parcel-bundler/parcel/issues/4498

**Comment by mischnic** [comment]
I think `|| asset.env.isWorker()` needs to be added here:
https://github.com/parcel-bundler/parcel/blob/1f5586657f1ea8660ca1f06abdd75687851ebbb2/packages/transformers/react-refresh-wrap/src/ReactRefreshWrapTransformer.js#L37

**Comment by dioptre** [comment]
Thanks @mischnic I'll try and let you know.

Sorry about the issue being clouded, we are just fighting a number of things to get this to build.

I also don't fully understand that url: js files *must* be transformed due to hoisting. As a developer I want the control to do what I want, without the build system badly mangling or injecting sometimes - and has been such a pain for our team we've considered replacing the parcel code or using gulp (heaven forbid). What's your opinion on this?

**Comment by mischnic** [comment]
> I want the control to do what I want, without the build system badly mangling

You have three options here:
- use ´--no-scope-hoist`, which will produce much bigger output JS bundles but doesn't "mangle" the code as "bad"
- use scope hoisting and accept the "mangling"
- use some other tool

**Comment by dioptre** [comment]
What about having a raw: file type that honors the build intent but isn't like url: 

It seems like this is so mixed up this feels like either a massive bug and/or a feature is missing.

**Comment by dioptre** [comment]
Ok my recommendation for others to fix this bug is to add (as per above):

```
function assertString(v) {
  (0, _assert.default)(typeof v === 'string' || typeof v === 'undefined');
  return v;
}
```

as it most likely isn't getting fixed anytime soon. That will help us survive til we get off parcel.

Thanks
Andrew

**Comment by ProLoser** [comment]
Actually in case anyone else wanders upon this thread we kinda just disabled HMR instead since live-reloading is not critical to development for us.

**Comment by devongovett** [comment]
This should be fixed in the latest nightlies. https://github.com/parcel-bundler/parcel/blob/e8c0c95729d87dd03b5763202a87cc0b5f3edadf/packages/transformers/react-refresh-wrap/src/ReactRefreshWrapTransformer.js#L14
