### ISSUE TITLE
@parcel/bundler-default: Got unexpected undefined

### ISSUE THREAD

**Issue by nyoijizai** [parcel-bundler/parcel#5181]
# 🐛 bug report

While testing out parcel v2 I ran into a fatal build error with an internal-looking failure.

```bash

ℹ️ Server running at http://localhost:1234
🚨 Build failed.
@parcel/bundler-default: Got unexpected undefined
Error: Got unexpected undefined
    at nullthrows (/node_modules/nullthrows/nullthrows.js:7:15)
    at BundleGraph.getBundleGroupsContainingBundle (/node_modules/@parcel/core/lib/BundleGraph.js:718:70)
    at /node_modules/@parcel/core/lib/BundleGraph.js:393:64
    at Array.every (<anonymous>)
    at BundleGraph.removeBundleGroup (/node_modules/@parcel/core/lib/BundleGraph.js:393:43)
    at MutableBundleGraph.removeBundleGroup (/node_modules/@parcel/core/lib/public/MutableBundleGraph.js:254:41)
    at Object.optimize (/node_modules/@parcel/bundler-default/lib/DefaultBundler.js:426:21)
    at BundlerRunner.bundle (/node_modules/@parcel/core/lib/BundlerRunner.js:276:21)
    at async Parcel.build (/node_modules/@parcel/core/lib/Parcel.js:579:25)
    at async Parcel.startNextBuild (/node_modules/@parcel/core/lib/Parcel.js:481:21)

```

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
	"name": "dev",
	"version": "0.0.1",
	"license": "MIT",
	"scripts": {
		"serve": "parcel './src/pages/**.*'",
		"build": "parcel build './src/pages/**.html'"
	},
	"devDependencies": {
		"parcel": "^2.0.0-beta.1"
	},
	"dependencies": {
		"jquery": "^3.5.1"
	}
}
```

## 🤔 Expected Behavior

Successful execution.

## 😯 Current Behavior

A fatal build error with an internal-looking failure.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | v14.12.0
| Yarn         | 1.22.5
| Operating System | macOS 10.13.6

**Comment by mischnic** [comment]
Can you share a reproduction?

**Comment by aminya** [comment]
I get this error too. The issue is solved when I remove the .parcel-cache. 

It happens quite randomly, and when I try to run build again.

**Comment by mischnic** [comment]
@aminya That is a completely different error.

**Comment by mischnic** [comment]
Well, by coincidence I just found a reproduction for this:

```js
// index.js (entry)
new Worker("./worker1.js");

// worker1.js
import "./worker2";

// workers2.js
import "./core.js";
new Worker("./worker3.js");

// worker3.js
import "./core.js";

// core.js
import "./worker3.js";
```

![before_bundle](https://user-images.githubusercontent.com/4586894/94376162-1c90e480-0119-11eb-93a8-7cc1a108e579.png)

**Comment by aminya** [comment]
> @aminya That is a completely different error.

You can reproduce mine here: https://github.com/aminya/github/tree/parcel-bug-report

**Comment by leaumar** [comment]
In case you're still looking for a repro: https://gitlab.com/Marnes/public-ip-display/-/commit/22b5ef6d9197966da41629d9c0d2b90d3bdf12d1

I came here from https://github.com/parcel-bundler/parcel/issues/5950#issuecomment-789312062

**Comment by nyoijizai** [comment]
> Can you share a reproduction?

**Comment by nyoijizai** [comment]
> Can you share a reproduction?

I accidentally closed the problem and did not receive a solution. Can you open the problem again?
