### ISSUE TITLE
RFC: css class name uglify in build mode

### ISSUE THREAD

**Issue by TroyTae** [parcel-bundler/parcel#5182]
# 💬 RFC

How about uglify css class name in build mode?

## 🔦 Context

Now `PostCSSTransformer` generates scope name like this:
https://github.com/parcel-bundler/parcel/blob/9120c257b94650ffaf44a3820f27bd1007cd83da/packages/transformers/postcss/src/PostCSSTransformer.js#L68-L70
If we uglify all of class names, we can reduce bundle size.

## 💻 Examples

Now:
```
{
  "title": "_title_xkpkl_5",
  "article": "_article_xkpkl_10"
}
```

After uglify:
```
{
  "title": "A",
  "article": "B"
}
```

**Comment by mischnic** [comment]
Class name collisions would be rather likely...

**Comment by TroyTae** [comment]
I already test about this in here: https://github.com/TroyTae/uglify-set
I think if we use `name, filename, css` as a unique key, we can prevent collision.

**Comment by mischnic** [comment]
As far as I can tell, you are saving all previous filenames in here: https://github.com/TroyTae/uglify-set/blob/aa798bb51ae49c0fa954f1c9b4b11d8ea69b016d/src/uglify.ts#L10-L13.

But all transformer run multithreaded, so you cannot have a  "global" list

**Comment by TroyTae** [comment]
Oops I don't know about architecture of `parcel`.
Then there is no shared variable each transformers?

**Comment by mischnic** [comment]
Currently, you cannot share information between transformers.

https://github.com/parcel-bundler/parcel/issues/4937

**Comment by TroyTae** [comment]
Oh as you said, we cannot apply this feature with the current architecture 😢 
I'll close this, but please reopen this issue if possible later!
