### ISSUE TITLE
HTML modules are not imported correctly from async js modules

### ISSUE THREAD

**Issue by FRSgit** [parcel-bundler/parcel#5189]
# 🐛 bug report

When loaded from js modules, html template import is empty (it's being included as `{default:{}}`).

## 🎛 Configuration (.babelrc, package.json, cli command)

Nothing specific, used html example to reproduce this.

## 🤔 Expected Behavior

HTML template should be imported as an string/URL to the asset, now it's neither of these.

## 😯 Current Behavior

If I do `import * as a from 'foo.html';` - `a` variable equals `{default:{}}`.

## 💁 Possible Solution

Not sure, would be nice if someone could point me in the proper direction.

## 🔦 Context

I'm trying to import HTML to my controller to use it as my component's template. In the perfect scenario I would lazy-load it together with the controller.

## 💻 Code Sample

The problem is reproduced in the test repo: https://github.com/FRSource/parcel/tree/bug-importing-html-template/packages/examples/html

Go to the HTML example (linked above), install dependencies with `yarn` and run the bundle with `yarn start`. The template is being imported within `async.js` and console.logged, so when you go to http://localhost:1234 you should see empty object logged in the console.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | 10.21.0
| npm/Yarn         | 1.22.4
| Operating System | MacOS

**Comment by FRSgit** [comment]
Bump @mischnic (sorry to bother, but you're the only person I know from this repo :<)

**Comment by mischnic** [comment]
I'm also seeing this with just
```js
import x from "./template.html";

console.log(x);
```
and
```html
<div>Hello!</div>
```

I'm not actually sure what should happen in this case. But this does at work:

```js
import x from "bundle-text:./template.html";

console.log(x);
```

**Comment by FRSgit** [comment]
That's a nice workaround! Maybe putting this info into the documentation is well enough?

**Comment by mischnic** [comment]
https://v2.parceljs.org/configuration/plugin-configuration/#predefined-(offical)-named-pipelines

Let's keep this open until there is some decision what `import x from "./template.html";` should actually do

**Comment by FRSgit** [comment]
Yea, saw that, but when looked for HTML support didn't saw a line regarding that - and I think this might be a quite often use-case (or maybe I'm wrong).

Okay, do you need any input from me? BTW. where this kind of decisions happen? Maybe I can be of help 😄

**Comment by mischnic** [comment]
> but when looked for HTML support didn't saw a line regarding that 

It works for every file types, feel free to extend the description: https://github.com/parcel-bundler/website

> where this kind of decisions happen

Talking with the rest of the Parcel team what they would think it should be/how we can make this consistent across file types....

I think we are probably not going to support importing html without a pipeline like `url:` or `bundle-text:`, because browsers aren't going to accept `import`ing html from ESM any time soon.

**Comment by FRSgit** [comment]
@mischnic I didn't closed it, because I've found out that in parcel 2 the `bundle-text:` with html partial doesn't work at all when shipped in production bundle 😅 
I will post a stack trace later on. But basically it looks like the module html partial should be in is missing from the final js bundle
