### ISSUE TITLE
Easy system to do compile-time templating, for example for a common header

### ISSUE THREAD

**Issue by john01dav** [parcel-bundler/parcel#5195]
# 🙋 feature request + 🔦 Context
It is frequently needed when creating a static frontend (to act on its own, as on Github pages, or to interface with a backend over ajax) to duplicate the same markup in many HTML files, for example for a common header, footer, or sidebar. I would like to request that Parcel add a system that facilitates this. 

## 🤔 Expected Behavior
The simplest way that this could work is to include something similar to C and C++'s `#include` directive, where the contents of a file are essentially copy/pasted into the file with the `#include` directive. For example, `#include "header.include.html"` could be used to include the header into a file, although this is not as powerful as it could be. To be more powerful, it should be possible to have a template file with slots for data to go in, and then the data file specifies a template file and what markup goes into which slot. I think that implementing both systems would be reasonable. They would still generate fully static HTML to render on the client side. Using JS to perform the final template substitution and inclusion on the client-side could possibly reduce bandwidth usage, at the expense of significant additional complexity and requiring JS for anything useful to appear (this is a very big cost IMO, so, at a minimum, such a system should not be mandatory).

## 😯 Current Behavior
As far as I know, nothing like this exists in parcel or can be easily used with it, but if something like this exists (even outside of parcel), please let me know!

## 💁 Possible Solution
A workaround for this is to use one's backend framework to generate the markup, and to use parcel only for non-markup assets. 

## 💻 Examples
C#'s ASP.NET Core Razor system allows for something similar, so looking into its implementation would be reasonable.

**Comment by mischnic** [comment]
Have you tried Pug's `include`? https://pugjs.org/language/includes.html

**Comment by john01dav** [comment]
@mischnic I looked into Pug and it seems like it gives a completely alternative syntax for HTML. I strongly prefer something that lets me work with normal HTML tags, although if that isn't going to happen, Pug may be an acceptable second choice.

**Comment by mischnic** [comment]
Them https://www.npmjs.com/package/posthtml-include?

**Comment by john01dav** [comment]
@mischnic I'm having some trouble getting that tool to work ([link](https://github.com/posthtml/posthtml-include/issues/52)), and I would prefer something that's a bit more integrated into parcel. Maybe it's possible to integrate it (I think that if I have this tool run first and then output html files that then get passed to parcel, with this dance coordinated by npm in package.json, it should work.), but I'm not sure and it definitely seems like it isn't the standard way to do this.

**Comment by mischnic** [comment]
It should "just work" with this .posthtmlrc config:

```
{
  "plugins": {
    "posthtml-include": {}
  }
}
```

after you've installed that package in your project.

**Comment by mischnic** [comment]
An example: https://github.com/mischnic/parcel-issue-5195-posthtml-include
