### ISSUE TITLE
Failed to import 'react-select'

### ISSUE THREAD

**Issue by Darmody** [parcel-bundler/parcel#520]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
bug

![2018-01-09 3 18 51](https://user-images.githubusercontent.com/6788752/34709109-b78dd2fe-f550-11e7-9961-4c746f32efd0.png)

**Comment by DeMoorJasper** [comment]
install babel-preset-es2015, remove the cache and re-run.

**Comment by Darmody** [comment]
@DeMoorJasper But I prefer to use babel-preset-env, it shouldn't be a limit.

**Comment by DeMoorJasper** [comment]
It's a dependency of the modules babelrc, feel free to out your opinion in the discussion about this: #13

**Comment by Darmody** [comment]
@DeMoorJasper gotcha.
