### ISSUE TITLE
sass: opacity x% becomes 1% on build

### ISSUE THREAD

**Issue by hugollm** [parcel-bundler/parcel#5207]
# 🐛 bug report

When in development mode, `opacity: x%` works normally, but when building it becomes `1%`.

## 🎛 Configuration (.babelrc, package.json, cli command)

No .babelrc.
package.json:

```
{
    "private": true,
    "scripts": {
        "start": "parcel src/index.html",
        "build": "rm -rf dist/* && parcel build src/index.html --no-source-maps"
    },
    "dependencies": {
        "preact": "^10.5.3",
        "true-store": "^0.5.2"
    },
    "devDependencies": {
        "parcel-bundler": "^1.12.4",
        "sass": "^1.26.11"
    }
}
```

## 🤔 Expected Behavior

* Ideally: opacity as percentage should work just fine.
* At least: dev and build should behave consistently.

## 😯 Current Behavior

Opacity percentage becomes 1% upon build. Does not happen when developing (which makes the problem worse).

## 💁 Possible Solution

Not using percentages (e.g. using 0.7 instead of 70%) is the current workaround.

## 🔦 Context

Page worked fine during development, but text disappeared on build (because they got changed to opacity 1%).

## 💻 Code Sample

![image](https://user-images.githubusercontent.com/376767/95017285-cc40e780-062e-11eb-912a-1e76453bb5eb.png)

## 🌍 My Environment

```
npm version: 6.14.8
node version: v10.19.0
parcel version: 1.12.4
sass version: 1.26.11 compiled with dart2js 2.9.3
OS: ubuntu 19.10 (eoan)
```

**Comment by mischnic** [comment]
This is apparently caused by cssnano, not sass: https://cssnano.co/playground

Follow this issue: https://github.com/cssnano/cssnano/issues/957
