### ISSUE TITLE
Moving a file into a directory causes unexpected build errors.

### ISSUE THREAD

**Issue by itsjohncs** [parcel-bundler/parcel#5213]
# 🐛 bug report

Moving a module into its own directory causes some build errors. For example, if I had `/foo.js` and wanted to give it its own directory and a new home as `/foo/index.js`, Parcel may error unexpectedly. A script that will reproduce the bug is provided below, check it out.

## 🎛 how to reproduce reliably

I have created a bash script that will reliably reproduce the bug on my Mac OS X computer.

```bash
#!/usr/bin/env bash

if [ -z "$1" ]; then
	echo USAGE: "$0" UNUSED_DIR_NAME
	echo
	echo Creates directory UNUSED_DIR_NAME and reproduces parcel bug in it
	exit 1
fi

set -xe

mkdir "$1"
( cd "$1" && npm init -y )

echo "-- Build 1 - This will succeed"
echo "import foo from './foo';" > "$1/entry.js"
echo "const foo = 1; export default foo;" > "$1/foo.js"
( cd "$1" && parcel build entry.js )

echo "-- Build 2 - This will fail"
mkdir "$1/foo"
mv "$1/foo.js" "$1/foo/index.js"
( cd "$1" && parcel build entry.js ) || true

echo "-- Build 3 - This will succeed"
echo "import foo from './foo/index';" > "$1/entry.js"
( cd "$1" && parcel build entry.js )

echo "-- Build 4 - This will succeed"
# This returns entry.js to what it was in Build 2 (which failed). So the
# same source tree is giving a failed build above, and a successful build
# here.
echo "import foo from './foo';" > "$1/entry.js"
( cd "$1" && parcel build entry.js )
```

And some versioning information about my environment:

```
$ sw_vers | head -n 2
ProductName:    Mac OS X
ProductVersion: 10.15.2

$ parcel --version
1.12.4

$ node --version
v12.14.1

$ npm version
{
  npm: '6.14.2',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '2.0.1',
  modules: '72',
  napi: '5',
  nghttp2: '1.40.0',
  node: '12.14.1',
  openssl: '1.1.1d',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.33.1',
  v8: '7.7.299.13-node.16',
  zlib: '1.2.11'
}
```

## 🤔 Expected Behavior

Build 2 in the script above should've suceeded.

## 😯 Current Behavior
Build 2 fails in the script above.

## 💁 Possible Solution

No clue, this is the very first time I'm using parcel. But I suspect some caching logic is misbehaving.

## 🔦 Context

I pretty quickly figured out how to get around this bug, so this isn't blocking me and I have almost no investment in this bug getting resolved. However, I searched through the open issues and didn't see mention of this, and wanted to share my findings in case its useful to ya'll.

**Comment by devongovett** [comment]
What version of parcel are you using?
