### ISSUE TITLE
TypeError: Cannot read property '../../../node_modules/@parcel/transformer-react-refresh-wrap/lib/helpers/helpers.js' of undefined

### ISSUE THREAD

**Issue by alexeychikk** [parcel-bundler/parcel#5226]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

No babelrc, just a simple typescript project.
```js
parcel src/index.html --open --host 127.0.0.1 --port 80
```

## 😯 Current Behavior

Every time I change the code this error occurs during HMR:
```
AboutMe.c6d8ee05.js:84 Uncaught TypeError: Cannot read property '../../../node_modules/@parcel/transformer-react-refresh-wrap/lib/helpers/helpers.js' of undefined
    at Function.resolve (AboutMe.c6d8ee05.js:84)
    at localRequire (AboutMe.c6d8ee05.js:80)
    at Object.eval (eval at hmrApply (HMRRuntime.js:220), <anonymous>:5:15)
    at newRequire (AboutMe.c6d8ee05.js:68)
    at hmrAcceptRun (HMRRuntime.js:272)
    at WebSocket.ws.onmessage (HMRRuntime.js:72)
```

## 💻 Code Sample

https://github.com/alexeychikk/alexeychikk.github.io

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.0-beta.1
| Node             | 12.16.3
| npm/Yarn         | 6.14.4
| Operating System | Windows 10

**Comment by mischnic** [comment]
Looks like you have Parcel installed globally?

**Comment by mischnic** [comment]
A similar error was fixed: https://github.com/parcel-bundler/parcel/issues/4356

Could you try the latest nightly `npm i parcel@nightly`?
