### ISSUE TITLE
optimizer/terser: "Export statement may only appear at the top level

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5230]
*Originally opened as https://github.com/parcel-bundler/parcel/discussions/4988*

# 🐛 bug report

1. We should obviously only emit exports on the top level
2. In this case, the `module.exports` statement is actually never called anyway...

## 😯 Current Behavior

```
🚨 Build failed.
@parcel/optimizer-terser: "Export" statement may only appear at the top level
src/index.js:2:1
  1 | !function (name, definition) {
> 2 |   if (typeof module != "undefined") module.exports = definition();
>   | ^ "Export" statement may only appear at the top level
  3 | };
  4 |
```

## 💻 Code Sample

```js
!function (name, definition) {
	if (typeof module != "undefined") module.exports = definition();
};
```

```json
{
  "module": "dist/index.js",
  "scripts": {
    "build": "parcel build src/index.js"
  }
}
```

**Comment by FRSgit** [comment]
Repro steps:
fork: https://github.com/FRSource/parcel/tree/bug-build-fail-when-referencing-common-js-like-module

Clone the repo, go into `packages/examples/html`, run `yarn` & `yarn demo`. It seems that terser is failing when sees CommonJS-like module definition ("module.exports" ).

**Comment by FRSgit** [comment]
Thank you @mischnic! <3
