### ISSUE TITLE
Parcel cannot consume something created by itself

### ISSUE THREAD

**Issue by jtenner** [parcel-bundler/parcel#524]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

It's both!

### 🎛 Configuration (.babelrc, package.json, cli command)

Please feel free to check out [jtenner/declarity](https://github.com/jtenner/declarity) which has the problem in the repo. All the configuration is there! 👍 

### 🤔 Expected Behavior

I don't know what I expect! It would be helpful to run two parallel instances of Parcel at the same time, one for library building and one for consuming the library and doing `jasmine` tests.

### 😯 Current Behavior

It just errors, unable to resolve the modules because they aren't relative to the `dist` folder, when it should just consume the bundle as-is.

### 💁 Possible Solution

1. Could prevent parsing of `require` calls if it's defined elsewhere as an identifier in the current context.
2. Could output `require` function calls as `parcel_require` or something else
3. Could ask parcel to ignore `require` calls somehow via command line
4. Point out how I've mismanaged parcel (I'm not ruling this out!)

### 🔦 Context

I am not using this in production yet, and would love to make a simple repo for a boilerplate of some variety.

### 💻 Code Sample

See the above repo link.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.4.1
| Node             | 9.3.0
| npm/Yarn         | 5.5.1
| Operating System | Windows 10

**Comment by bsonntag** [comment]
I think you should change your `<script>` tag to `<script src="../declarity.coffee"></script>` and then just run `parcel test/index.html`.
