### ISSUE TITLE
[v2] FATAL ERROR: v8::HandleScope::CreateHandle()

### ISSUE THREAD

**Issue by pr1ntr** [parcel-bundler/parcel#5245]
# 🐛 bug report

Seems like when I try to build it sporadically spits this node error out. There is no rhyme or reason to it afaik.

[here is a full output log with the error](https://gist.github.com/pr1ntr/8869e46f4e0f026ec538468ff2a80336)

.babelrc
```js
{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "plugins": [
    [
      "babel-plugin-styled-components",
      {
        "cssProp": true,
        "displayName": true
      }
    ],
    ["@babel/plugin-proposal-class-properties", { "loose": true }],
    ["@babel/plugin-proposal-optional-chaining"]
  ]
}
```
.parcelrc
```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{jpg,png,svg}": ["@parcel/transformer-raw"]
  }
}
```

script.
```json
{"scripts": {
    "build": "parcel build ./src/index.html --dist-dir dist --no-source-maps"
}}
```

## 🤔 Expected Behavior
It builds without Exit 134

## 😯 Current Behavior

Well it actually builds but the error exit with code 134  which causes CI exit code 1 and not continue the deployment.

## 💁 Possible Solution

Could be something to do with not enough resources?

## 🔦 Context

This happens on local and ci builds, and local dev. It also happens when i ctrl-c the dev server. It is sporadic. 

## 💻 Code Sample
Sorry all NDA

## 🌍 Your Environment

Happens on on my i5 4670k with 16gb ram, win 10
Happens in travis on xenial

**Comment by mischnic** [comment]
Which Node version are you using? Node 12?

**Comment by pr1ntr** [comment]
Yes I am using node 12

**Comment by mischnic** [comment]
So I guess there is a Node 12 bug with the `Napi::ObjectWrap` destructor....

https://github.com/parcel-bundler/source-map/blob/1fc437abc31d6d7cb9b532f1c5e2ac82a3d149fb/src/napi/SourceMap.cpp#L5

**Comment by pr1ntr** [comment]
Seems to be fixed with node 14. I also thing it has to do with the size of the build.

**Comment by codedazur-development** [comment]
I'm also experiencing this issue. It happens when I kill my dev build by pressing `control` + `c` in the terminal.

**Comment by NordlingDev** [comment]
> So I guess there is a Node 12 bug with the `Napi::ObjectWrap` destructor....
> 
> https://github.com/parcel-bundler/source-map/blob/1fc437abc31d6d7cb9b532f1c5e2ac82a3d149fb/src/napi/SourceMap.cpp#L5

@mischnic But OP is clearly building using parameter `--no-source-maps`. I'm having the same problem. I don't need source maps either.

**Comment by fernand0aguilar** [comment]
Up. Encountered the same problem with node 15.1.0 and "parcel": "^2.0.0-beta.1",

**Comment by Lusito** [comment]
In case this helps: I recently updated from 2.0.0-beta.1 to 2.0.0-nightly.443 and suddenly I got this error with every build. on beta.1 no issues at all.

**Comment by mischnic** [comment]
@Lusito Any chance you can figure out in which nightly version this started to happen? `2.0.0-nightly.300` was the very next version after beta.1 (https://www.npmjs.com/package/parcel?activeTab=versions)

Which Node version are you using?

**Comment by Lusito** [comment]
@mischnic The change from 2.0.0-nightly.389 to 2.0.0-nightly.395 brings the problem (there are no other nightlies in between).

I am on node v12.16.3.

**Comment by mischnic** [comment]
Thanks! These are the changes between the two nightlies https://github.com/parcel-bundler/parcel/compare/288396a5...ac21b528

Then it's probably https://github.com/parcel-bundler/parcel/pull/5106, so from `@parcel/source-map@2.0.0-alpha.4.13` to `@parcel/source-map@2.0.0-alpha.4.15`: https://github.com/parcel-bundler/source-map/compare/v2.0.0-alpha.4.13...v2.0.0-alpha.4.15. Strangely enough, no native code was changed between these versions.

@DeMoorJasper

**Comment by Lusito** [comment]
From the short description i would assume that node-addon-api contains native code. Its version was bumped from 2 to 3. That would be the first thing i would take a look at.

**Comment by Lusito** [comment]
Just tried it on my fresh linux manjaro setup where I am able to reproduce the issue on node 12.6.3 not with 15.2.0. I can try other node versions here if it helps.

**Comment by Lusito** [comment]
Node 12.18.3 is the first that works again. I think it might be this issue: https://github.com/nodejs/node/pull/33867

**Comment by mischnic** [comment]
Looking at the "n-api" list in https://github.com/nodejs/node/releases/tag/v12.18.3, I'd say it's https://github.com/nodejs/node/pull/33508? This issue is linked in there: https://github.com/nodejs/node-addon-api/issues/722, it has the exact same error message we are seeing here.
