### ISSUE TITLE
Parcel 2 Docs: Production Optimizations for API

### ISSUE THREAD

**Issue by ai** [parcel-bundler/parcel#5248]
# 🐛 bug report

When I am using Parcel 2 API from [docs](https://v2.parceljs.org/features/parcel-api/) I have no JS/CSS minification and `process.env.NODE_ENV` inlining.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
  let bundler = new Parcel({
    entries: join(__dirname, '../test/demo/index.html'),
    distDir: join(__dirname, '../test/demo/build'),
    cacheDir: join(__dirname, '../test/demo/.cache'),
    defaultConfig: join(__dirname, '../node_modules/@parcel/config-default'),
    patchConsole: false,
    sourceMaps: false,
    scopeHoist: true
  })
  await bundler.run()
```

I run this script with `NODE_ENV=production ./build.js`

## 🤔 Expected Behavior

Minify JS/CSS by default on `NODE_ENV=production` or show an option to do it in docs.

## 😯 Current Behavior

Output has no minification. `process.env.NODE_ENV` was not replaced to `"production"`.

## 🔦 Context

Adding `minify: true` do not fix the problem with replacing `process.env.NODE_ENV` to `"production"` in my code.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.425
| Node             | 14.14
| npm/Yarn         | Yarn 1.22.10
| Operating System | Fedora 32

**Comment by devongovett** [comment]
You could try the `mode: "production"` option maybe? The source for the parcel cli might also be helpful.

**Comment by ai** [comment]
Yeap, `mode: 'production'` works fine. Should we add it to docs?

**Comment by mischnic** [comment]
>  Should we add it to docs?

Sure. Either to https://v2.parceljs.org/plugin-system/api/#InitialParcelOptions or https://v2.parceljs.org/features/parcel-api/. What do you think? And `InitialParcelOptions` should also definitely linked to from the latter

We should probably also think about more sensible default values for these options.

**Comment by ai** [comment]
> Sure. Either to https://v2.parceljs.org/plugin-system/api/#InitialParcelOptions or https://v2.parceljs.org/features/parcel-api/. What do you think?

https://v2.parceljs.org/features/parcel-api/

It is a good copy-paste starting point for people.

**Comment by mischnic** [comment]
-> https://github.com/parcel-bundler/website/pull/754
