### ISSUE TITLE
Parcel build different result when add `--out-dir` option

### ISSUE THREAD

**Issue by dwqs** [parcel-bundler/parcel#525]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

`.babelrc`:
 
```js
{
  "presets": [
    "es2015",
    "stage-2"
  ],
  "plugins": [
    "transform-runtime"
  ]
}
```

`package.json`: 

```
{
   "dependencies": {},
  "devDependencies": {
    "@commitlint/cli": "^5.2.8",
    "@commitlint/config-angular": "^5.1.1",
    "autoprefixer": "^7.1.5",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "babel-eslint": "^8.0.1",
    "cz-conventional-changelog": "^2.1.0",
    "eslint": "^4.8.0",
    "eslint-config-vue": "^2.0.2",
    "eslint-plugin-vue": "^2.1.0",
    "less": "^2.7.2",
    "parcel-bundler": "^1.4.1",
    "parcel-plugin-eslint": "^1.0.0",
    "parcel-plugin-vue": "^1.5.0",
    "vue": "^2.5.8",
    "vue-template-compiler": "^2.5.8"
  }
}
```

![image](https://user-images.githubusercontent.com/7871813/34759931-aeddedd8-f618-11e7-91f8-bc94d003e424.png)

`tpl.html`:

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="renderer" content="webkit">
        <meta name="force-rendering" content="webkit">
        <title>A simple datepicker component based Vue 2.x</title>
    </head>
    <body>
       <div id="app"></div>
       <script src="./gh/index.js"></script>
    </body>
</html>
```

### 🤔 Expected Behavior

Build the same result whether or not add `--out-dir` option.

### 😯 Current Behavior

When run command ` ./node_modules/.bin/parcel build tpl.html` in the terminal, the build result as follows:

![image](https://user-images.githubusercontent.com/7871813/34760046-22532c74-f619-11e7-930e-09aa22c01129.png)

It works well. But when run command ` ./node_modules/.bin/parcel build tpl.html --out-dir demo`, the build result as follows:

![image](https://user-images.githubusercontent.com/7871813/34760117-6f949b1c-f619-11e7-999b-b74540187a59.png)

When visiting the HTML file in the browser(I already put it on the server):

![image](https://user-images.githubusercontent.com/7871813/34760445-d364640a-f61a-11e7-8903-df593fb9b3fa.png)

and when looking into the bundled file I noticed it's requiring something like this:

```js
var e=require("babel-runtime/core-js/symbol/to-string-tag"),n=D(e),
r=require("babel-runtime/core-js/object/is-frozen"),i=D(r),
o=require("babel-runtime/core-js/promise"),a=D(o),
s=require("babel-runtime/core-js/set-immediate"),u=D(s),
c=require("babel-runtime/core-js/object/get-own-property-descriptor"),
.....
```

Is that true? Or am I using it wrong?

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.4.1
| Node             | 8.9.0
| npm/Yarn         | npm/5.5.1
| Operating System | Mac OS 10.13.2

**Comment by dwqs** [comment]
same as when add `--public-url` option.

**Comment by StarpTech** [comment]
@dwqs can you reproduce with 1.7.0 ?

**Comment by dwqs** [comment]
@StarpTech It's ok with 1.7.0,  And Can i close this issue?
