### ISSUE TITLE
Add the possibility to disable Elm debugger without having to create a custom handler.

### ISSUE THREAD

**Issue by fortizflexidao** [parcel-bundler/parcel#5251]
# 🙋 feature request

Add the possibility to disable Elm debugger without having to create a custom handler.

## 🤔 Expected Behavior

Be able to disable elm debugger.

## 😯 Current Behavior

Time travelling debugger is enabled for development no matter what.

## 💁 Possible Solution

Passing` elmDebug: false` to the bundler options should prevent elm time travelling debugger.

## 🔦 Context

My problem is that I am developing a data intensive application, and the time travelling debugger holds all the intermediary states, the received data, everything. This causes the pages to become not responsive or simple freeze after a very short time. Development under this circumstances is unbearable, so I needed to create a custom handler with debug: false passed to the elm compiler.

## 💻 Examples

Try to make an application that transforms, aggregates and plots thousands of points according to user interaction while the time travelling debugger is on.

**Comment by MurkyMeow** [comment]
Developing a game with updates at 60 times per sec is causing the debugger to eat up ALL the memory very quickly.

In latest `parcel` (not `parcel-bundler`) versions use can use the env variable `PARCEL_ELM_NO_DEBUG=1 parcel index.jtml`
