### ISSUE TITLE
Parcel building incorrect Websocket address for Chrome extensions

### ISSUE THREAD

**Issue by mikemfleming** [parcel-bundler/parcel#5254]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

I'm not using a config file but here's my build command
```bash
parcel watch options/index.html \
    --public-url /build_output \
    --out-dir ./build_output  \
    --out-file options.html \
    --hmr-port 8080
```

## 🤔 Expected Behavior

No error is shown in the console.

## 😯 Current Behavior

It prints this error. 

```
options.e31bb0bc.js:28402 WebSocket connection to 'ws://mmaleomkmlchnokcblhlmihekcpeegpm:8080/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
```
Then in the referenced line of code:
```
  var hostname = "" || location.hostname;
...
  var ws = new WebSocket(protocol + '://' + hostname + ':' + "8080" + '/');
```
Parcel is building an incorrect path when it tries to connect to the websocket server here. It _should_ be `ws://localhost:8080`. It does not handle the way Chrome extensions populate the `window.location.hostname` field with the id of the current extension.

## 💁 Possible Solution

Find [some reliable way](https://stackoverflow.com/questions/7507277/detecting-if-code-is-being-run-as-a-chrome-extension) of finding if the bundle is being run in an extension context and handle the websocket connection appropriately. 

## 🔦 Context
I'm building a Chrome extension and using Parcel to bundle up the React app that we use for our user options menu. Chrome extensions do not have a convenient way to hot reload pages on changes to the code so we built our own hot reload function. 

While developing, when the browser opens the app will establish a websocket connection with Parcel's websocket server. I am specifying the port in my build command. When a change is made in the filesystem, that websocket is triggered and the extension refreshes the page. 

There's lots of copy pasta out there for this as well as a Webpack plugin that hasn't been maintained in 4 years. I prefer developing with Parcel and also want to be able to preprocess my code for this extension as I normally would with other web development projects.

## 💻 Code Sample
I don't think it's necessary but happy to share if you need it. 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.12.4
| Node             | v12.17.0
| Chrome         | Version 86.0.4240.80
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
Does `--hmr-host` work for you?

**Comment by mikemfleming** [comment]
Thanks for the response! Nice, adding the flag `--hmr-hostname localhost` worked for me. Appreciate the help!

Now I just need to get inline source maps working with Parcel because Chrome requires that they're inlined for security reasons. 

Anyway, good to close this issue. Thanks again!

**Comment by doub1ejack** [comment]
This works for me also, but note that [the flag is currently named](https://parceljs.org/cli.html#hmr-hostname) `--hmr-hostname` (not -host).

```
parcel watch options/index.html \
    --public-url /build_output \
    --out-dir ./build_output  \
    --out-file options.html \
    --hmr-port 8080\ 
    --hmr-hostname localhost
```
