### ISSUE TITLE
Parcel Sass Auto install freeze

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#5257]
# 🐛 bug report

`node^v14.14.0`

When trying to run parcel with an uninstalled package like sass, parcel tries to install it & freeze

```
$ yarn dev
yarn run v1.22.10
$ parcel src/index.html
⚠️  Port 1234 could not be used.
ℹ️ Server running at http://localhost:42293
Installing sass...
yarn: [1/4] Resolving packages
yarn: [2/4] Fetching packages
@parcel/package-manager: yarn: fsevents@2.1.3: The platform "linux" is incompatible with this module.
@parcel/package-manager: yarn: "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
yarn: [3/4] Linking dependencies
yarn: [4/4] Building fresh packages
@parcel/package-manager: yarn: Saved lockfile.
@parcel/package-manager: yarn: Saved 6 new dependencies.
@parcel/package-manager: yarn: Direct dependencies
@parcel/package-manager: yarn: All dependencies
⠋ Building index.scss...
```

The only dependency installed in my project is `parcel^2.0.0-nightly.425` and my html file only contains
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="index.scss">
</head>
<body>
  
</body>
</html>
```

The scss file is empty

This bug happens both on my windows & on my arch linux systems

**Comment by mischnic** [comment]
Works on macOS...

**Comment by mischnic** [comment]
The autoinstall took quite a while in my Windows 10 VM, but it did work without freezing

**Comment by Banou26** [comment]
I will make a repro on windows.

**Comment by Banou26** [comment]
*https://github.com/Banou26/parcel-bug-5257*

I also pushed to that repo the yarn-error.log for you guys to be able to find where it comes from more easily.

**Comment by ranisalt** [comment]
I have the same issue for everything. When parcel autoinstalls something, it freezes without completing, but still modifies package.json, so I have to run `yarn` *twice*, the first time to install whatever package was missing, the second to reinstall some packages that apparently are removed by either parcel autoinstaller or the first yarn run. Very weird and hard to debug/reproduce.
