### ISSUE TITLE
Unable to call External javascript functions

### ISSUE THREAD

**Issue by shridharkalagi** [parcel-bundler/parcel#5270]
# 🐛 bug report

Unable to call External javascript functions 

## 🤔 Expected Behavior
External JS function should have been called

## 😯 Current Behavior

Uncaught ReferenceError msg()
## 💻 Code Sample
My index.html 
````
<html>
<head>
<script type="text/javascript" src="message.js"></script>
</head>
<body>
<p>Welcome to JavaScript</p>
<form>
<input type="button" value="click" onclick="msg()"/>
</form>
</body>
</html>
````

message.js
````
function msg(){
 alert("Hello Javatpoint");
}
````

Above method ```msg()``` is not being called on click of the button. I'm getting Uncaught Reference exception.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | v12.4.0
| npm/         |6.9.0 
| Operating System | Mac

**Comment by mischnic** [comment]
Do this instead:
```
