### ISSUE TITLE
[RFC] Code from Unknown Sourcefiles

### ISSUE THREAD

**Issue by Lagicrus** [parcel-bundler/parcel#5273]
# 💬 RFC

I am trying to figure out what "Code from unknown sourcefiles" means when you builds the app.
I have Google'd it and checked the issues on here but nothing seems to be turning up.
Is this a Parcel thing or something else? 
And is there a way I can figure out what files it isn't playing nice with?

## 🔦 Context

This has affected be because it is attributing over half of the build size down to this so I am at a loss of what to improve.

## 💻 Examples

![image](https://user-images.githubusercontent.com/24227350/97087947-8c659280-1625-11eb-9ffb-3c8e90df9d00.png)

**Comment by mischnic** [comment]
This summary analyzes the sourcemaps, so there are probably some sourcemaps missing in the output.

cc @DeMoorJasper

**Comment by Lagicrus** [comment]
> This summary analyzes the sourcemaps, so there are probably some sourcemaps missing in the output.
> 
> cc @DeMoorJasper

Ah cool, that is what I thought.
Would it be too unreasonable to ask for it to say somewhere (even with a flag) what they were? 

Thanks

**Comment by mischnic** [comment]
> Would it be too unreasonable to ask for it to say somewhere (even with a flag) what they were?

What do mean?

A (simplified!) version of the problem:

Input:
```js
// a.js
import {otherClass, c} from "./b.js";
console.log(otherClass);
console.log(c);

// b.js
export const otherClass = 2;
export const c = 3;
````

Output (JS code + sourcemap):
```
source  | output code
------------------------------------
??? 	| (function () {
b.js	|   var $dc3a08609a8295a7a79be67f068405e$export$otherClass = 2;
b.js	|   var $dc3a08609a8295a7a79be67f068405e$export$c = 3;
a.js	|   console.log($dc3a08609a8295a7a79be67f068405e$export$otherClass);
a.js	|   console.log($dc3a08609a8295a7a79be67f068405e$export$c);
???		| })();
```

Now we go through every line, and add its bytecount to a counter for the corresponding source file. But if for example one file is missing here or some shift caused the sourcemap to be incorrect, we don't know where that line came from, thus counting it towards the "unknown source file".

```
source  | code
------------------------------------
??? 	| (function () {
b.js	|   var $dc3a08609a8295a7a79be67f068405e$export$otherClass = 2;
b.js	|   var $dc3a08609a8295a7a79be67f068405e$export$c = 3;
a.js	|   
a.js	|   
???		|   console.log($dc3a08609a8295a7a79be67f068405e$export$otherClass);
???		|   console.log($dc3a08609a8295a7a79be67f068405e$export$c);
???		| })();
```

**Comment by Lagicrus** [comment]
Right, I think I am beginning to follow the problem. Hm.

Ok, I will apologise beforehand if this is entirely wrong/barking up the wrong tree/doesn't help. I just recalled a tool called `source-map-explorer` (SME). Which after running on the generated scripts.HASH.js & scripts.HASH.js.map has got me wondering.
So, Parcel tells me that scripts.HASH.js is 505.87KB (bad I know), but, SME tells me the exact same. So they are talking about the same data.
Next parcel tells me that it doesn't know about `309.87KB` of source files, and this is where things start to go interesting.

![image](https://user-images.githubusercontent.com/24227350/97105496-08f28280-16b3-11eb-9448-70b896c30cb6.png)
I'll link the top 50 from Parcel here for your checking https://starb.in/viHhbh.txt with my ramble.

So the largest is `react-dom`, ok, that lines up. Next is `jss`, then `history`. Ok, wait. What happened to `slider` in `@material-ui`? That is larger than `history` and smaller than `jss` it should be in between, no? Ok, maybe it is just `@material-ui`, wait no, it missed `lodash` as well which is just 40KB larger than `history`. 
And so it continues, I was going down the list and none of the components in `@material-ui/core/esm` are listed in Parcel. Sure, it has styles, but no esm. 
Where it gets weird is I don't even use Slider, checking through all of the files in this project turns up 0 results for it, same for Tabs, and I am sure I can find more.
As far as I can tell, Parcel is having weird issues trying to both record what `@material-ui` components it is using, and to chuck the ones it isn't.
Now sure, 226.03KB isn't the whole 309.02KB and isn't the whole story and reason for it, but it does make up a sizable chunk and with the previous context in mind, it does seem to make sense to me.

I again apologise for the tangent but I just saw this rabbit hole and had to follow it to see where it went 😅

**Comment by Lagicrus** [comment]
Also as a mention, as I just decided to see how it would work with Parcel 1.12.4, running the exact same build command shows the core/esm modules 👍 
And after enabling `--experimental-scope-hoisting` it removes the ones I don't use as it should.
