### ISSUE TITLE
Support tilde ~ in Sass Transformer

### ISSUE THREAD

**Issue by limonte** [parcel-bundler/parcel#5275]
# 🙋 feature request

Support the `@import '~path/to/styles.scss'` syntax.

## 🤔 Expected Behavior

It should resolved from `node_modules`, it was working this way in Parcel v1.

## 😯 Current Behavior

```
Error: The @import path "~path/to/styles" is using webpack specific syntax, which isn't supported by Parcel.

To @import files from node_modules, use "path/to/styles"
```

The error message is actually incorrect. The tilde syntax is not only from Webpack, VScode also supports it: here's the demo:

![IGMC5dbA4i](https://user-images.githubusercontent.com/6059356/97107122-7c55bd80-16ce-11eb-93de-b38666a1aa51.gif)

## 💁 Possible Solution

Add the tilde ~ support.

## 🔦 Context

https://github.com/sweetalert2/sweetalert2-parcel-demo/blob/master/styles.scss

**Comment by DeMoorJasper** [comment]
We can support this again, however it's pretty weird that we would deviate from the standard resolver especially for sass.

Maybe this should be configurable in sassrc or something not sure yet how to solve this. This is custom syntax though.

In Parcel 1 we supported way too much custom and weird syntaxes that has been cleaned up/normalised in Parcel 2.

**Comment by limonte** [comment]
Thank you for the prompt response @DeMoorJasper!

> This is custom syntax though.

Agree, but it's widely used, e.g. in packages link https://github.com/sweetalert2/sweetalert2-themes where we

```scss
# 1. import default variables
@import '~sweetalert2/src/variables';

# 2. allow users to override default values
$swal2-background: black;

# 3. import the actual styles
@import '~sweetalert2/src/sweetalert2';
```

Without `~` those files wouldn't be resolved properly, so `~` is actually the only one way AFAIK for this approach and IMO should be supported by Parcel v2.

**Comment by noushad-pp** [comment]
I also have the same problem as the underlying library uses the ~ format and thus even though I resolve the file import to absolute path, the file imported has the same issue and parcel compilation is failing.

**Comment by valentinbdv** [comment]
Having the same issue. What would be the other way to do that using parcel 2?
Thanks for your help ;)

**Comment by toresbe** [comment]
This is also preventing me from upgrading to parcel 2, as I need to use in-house style libraries which use tilde paths to reference across other modules with npm dependencies.

**Comment by rutger1140** [comment]
Same here. 

Long time Parcel 1 user and this prevents me from going Parcel 2. Even with a very minimal setup (`parcel 2.0.0-beta.2`) these all don't work when using `@import` outside of the main import file. (from `main.scss` using `@import "~...` does work)

Hope someone can point me in the right direction for this seemingly very basic importing of scss files... 🤔 

With ~
```scss
@import "~bootstrap/scss/functions";
```
```shell
🚨 Build failed.
@parcel/transformer-sass: The @import path "~bootstrap/scss/functions" is using webpack specific syntax, which isn't supported by Parcel.

To @import files from node_modules, use "bootstrap/scss/functions"
  ╷
8 │ @import "~bootstrap/scss/functions";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Without ~
```scss
@import "bootstrap/scss/functions";
```

```shell
🚨 Build failed.
@parcel/transformer-sass: Failed to resolve 'bootstrap/scss/functions' from './src/assets/styles/common/\\\\\\_common.scss'
  ╷
8 │ @import "./bootstrap/scss/functions";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

With node_modules/ prefixed

```scss
@import "node_modules/bootstrap/scss/functions";
```
```shell
🚨 Build failed.
@parcel/transformer-sass: Failed to resolve 'node\\\\\\_modules/bootstrap/scss/functions' from './src/assets/styles/common/\\\\\\_common.scss'
  ╷
8 │ @import "node_modules/bootstrap/scss/functions";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
```

Only thing that works seems to be `@import "../../../../node_modules/bootstrap/scss/functions";` which is kinda ugly.

**Comment by devongovett** [comment]
FYI tilde imports are deprecated in webpack as well... https://webpack.js.org/loaders/sass-loader/#resolving-import-at-rules

**Comment by rb-ntnx** [comment]
Even after the closure of this, I am still facing the issue:

https://github.com/parcel-bundler/parcel/pull/6607#issuecomment-1064158720

Can someone guide me here ?

**Comment by YqxLzx** [comment]
and then , how to relsove this issue

> We can support this again, however it's pretty weird that we would deviate from the standard resolver especially for sass.
> 
> Maybe this should be configurable in sassrc or something not sure yet how to solve this. This is custom syntax though.
> 
> In Parcel 1 we supported way too much custom and weird syntaxes that has been cleaned up/normalised in Parcel 2.

if  other third-party libraries use "~" what help
