### ISSUE TITLE
HMR runtime references global by wrong name in Worker

### ISSUE THREAD

**Issue by bwrrp** [parcel-bundler/parcel#528]
🐛 bug report

I've created a very simple project with a web worker. It looks like the script reference in the Worker constructor call is picked up automatically by Parcel and compiled into a separate bundle, which is great. However, the generated bundle by default includes the hot module reloading runtime, which contains code referencing `window.location`. In a Worker scope, the global is called `self`, and the bundle code throws a ReferenceError before the actual worker script can run.

### 🎛 Configuration / code sample

Create the following files and run `parcel serve index.html`

#### index.js
```js
var w = new Worker('./worker.js');
w.onmessage = e => console.log(e.data);
setInterval(() => w.postMessage('test'), 1000);
```

#### worker.js
```js
self.onmessage = e => self.postMessage(e.data + ' from worker');
```

### index.html
```html
<script src="./index.js"></script>
```

### 🤔 Expected Behavior

Expected code to load and work correctly. 

### 😯 Current Behavior

Uncaught ReferenceError: window is not defined

The code in worker.js does not run and no "test" messages are logged to the console.

### 💁 Possible Solution

The error is thrown in what looks to be the following code, included in the Worker bundle: https://github.com/parcel-bundler/parcel/blob/06d5ffc33dac19fa9ca730bbf939052b500a34ec/src/builtins/hmr-runtime.js#L18 

The HRM runtime should either detect it is running in a Worker scope and use the self global, or be disabled for Worker bundles if there are other issues that prevent it from working in that context.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.4.1
| Node             | 8.4.0
| npm/Yarn         | npm 5.6.0
| Operating System | Windows 10

**Comment by DeMoorJasper** [comment]
related to #476

**Comment by bwrrp** [comment]
Oops, I think I forgot to search for PRs. This is indeed the same issue, sorry for the duplicate.
