### ISSUE TITLE
parcel build strips viewBox from svgs in index.html

### ISSUE THREAD

**Issue by alexreardon** [parcel-bundler/parcel#5289]
If I render an `<svg>` in a `index.html` file, the `viewBox` attribute is being removed from the `svg` when running `parcel build`

**Comment by devongovett** [comment]
Maybe an htmlnano issue?

**Comment by mischnic** [comment]
See https://github.com/parcel-bundler/parcel/issues/4508#issuecomment-617223278

**Comment by mischnic** [comment]
Does adding a .htmlnanorc with

```json
{ "minifySvg": { "plugins": [{ "removeViewBox": false }] } }
```

work for you?
