### ISSUE TITLE
typescript 4.0.5 is breaking @parcel/optimizer-terser

### ISSUE THREAD

**Issue by alexreardon** [parcel-bundler/parcel#5296]
parcel version: `2.0.0-beta.1`

When using typescript `4.0.5` I am getting this error when running `parcel build`

```bash
@parcel/optimizer-terser: "Export" statement may only appear at the top level
  546 | // ASSET: [FILE_PATH]/types.ts
> 547 | export{};function $aca084f62d8e1eb18d9e8221f2057564$var$_EMOTION_STRINGIFI
>     | ^ "Export" statement may only appear at the top level
```

This error does not exist when using typescript `3.9.7`

**Comment by mischnic** [comment]
Can you try a more recent nightly? This should have been fixed by https://github.com/parcel-bundler/parcel/pull/5220

**Comment by alexreardon** [comment]
Thanks!!
Nightly for just that plug-in, or for all of parcel 2?

**Comment by mischnic** [comment]
Generally, I would always try use every of the same version. We do still make breaking API changes

**Comment by alexreardon** [comment]
This is not an issue in `2.0.0-nightly.444`
