### ISSUE TITLE
Win10 build issue on empty project

### ISSUE THREAD

**Issue by lifeart** [parcel-bundler/parcel#53]
![image](https://user-images.githubusercontent.com/1360552/33670385-fe7c1078-dab5-11e7-9252-4a1869444c82.png)

index.js -> empty
index.html -> 

```
<html>

<body>
    <script src="./index.js"></script>
</body>

</html>

```

**Comment by lifeart** [comment]
![image](https://user-images.githubusercontent.com/1360552/33670515-573b17e0-dab6-11e7-8e6e-f45f88b44014.png)

**Comment by BChip** [comment]
This is a known issue: see #11

**Comment by davidnagli** [comment]
It looks like port :1234 is already being used by Windows. Try using the ‘-p’ flag to specify a different port (try :8080).

**Comment by lifeart** [comment]
@davidnagli ![image](https://user-images.githubusercontent.com/1360552/33670811-025c5206-dab7-11e7-8ded-5a9a37b5fa30.png)

same issue

**Comment by lifeart** [comment]
Node version v7.9.0

**Comment by davidnagli** [comment]
@lifeart That’s not the same error!!

**Comment by davidnagli** [comment]
The first one is just an issue with Parsel trying to use a port that’s already in use, the other error is an actual bug in Parcel’s code (an infinite recursive loop)

**Comment by devongovett** [comment]
Going to close this since it is covered by #11.
