### ISSUE TITLE
React Refresh needs updating

### ISSUE THREAD

**Issue by Lagicrus** [parcel-bundler/parcel#5301]
# 🐛 bug report

View https://github.com/facebook/react/issues/20100 for a history of this bug with Parcel2.

## 🎛 Configuration (.babelrc, package.json, cli command)

https://github.com/BlobEmoji/blobs.gg/blob/26f85b52f18efc7900f80891505549d162b3436c/package.json

## 💁 Possible Solution

Update react-refresh from `^0.6.0` to `^0.9.0` as that will have the fix supplied here https://github.com/facebook/react/pull/20129 

## 🔦 Context

DevTools doesn't update with the new nodes due to a bug in the old React-Refresh

## 💻 Code Sample

https://github.com/BlobEmoji/blobs.gg/tree/26f85b52f18efc7900f80891505549d162b3436c

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | 12.14.1
| npm/Yarn         | 6.14.6
| Operating System | Windows 10

**Comment by alphabet-codes** [comment]
@mischnic can I fix this?

**Comment by mischnic** [comment]
Sure

The dependencies are in these files:
https://github.com/parcel-bundler/parcel/blob/v2/packages/runtimes/react-refresh/package.json
https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/react-refresh-wrap/package.json
https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/react-refresh-babel/package.json

**Comment by Jadhielv** [comment]
Done @mischnic. Check **_PR_**: #5315
