### ISSUE TITLE
unknown option `--no-autoinstall` on v2 nightly builds

### ISSUE THREAD

**Issue by jogold** [parcel-bundler/parcel#5302]
# 🐛 bug report

Using the `--no-autoinstall` flag with `build` on the v2 nightly builds results in the following error:
```
unknown option `--no-autoinstall`
```

## 🤔 Expected Behavior

Should work like on v2.0.0-beta.1?

## 😯 Current Behavior

Doesn't work on v2 nightly builds

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.435 |
| Node             | v12.18.0 |
| npm/Yarn         | 1.22.4 |
| Operating System | Ubuntu 20.04 (WSL2) |

**Comment by DeMoorJasper** [comment]
Which command did you use?

**Comment by jogold** [comment]
> Which command did you use?

`build`

**Comment by mischnic** [comment]
Autoinstall is disabled by default for build, so it only exists for `watch` and `serve`.

**Comment by jogold** [comment]
> Autoinstall is disabled by default for build, so it only exists for `watch` and `serve`.

OK but this was not the case on v2.0.0-beta.1, right?

**Comment by mischnic** [comment]
Correct (it was changed by https://github.com/parcel-bundler/parcel/pull/4907).
