### ISSUE TITLE
Error: No transformers found for "*.ttf" (when testing #5304)

### ISSUE THREAD

**Issue by wachunei** [parcel-bundler/parcel#5305]
# 🐛 bug report

I'm currently testing the WebExt transformer proposed in #5304 and I'm running into a `.ttf` file extension error.

## 🎛 Configuration (.babelrc, package.json, cli command)

Running parcel/core/src/bin.js from #5304 branch, as described in [this comment](https://github.com/parcel-bundler/parcel/pull/5304#issuecomment-720065829)

## 🤔 Expected Behavior

Font files to be treated as assets

## 😯 Current Behavior

Getting an error

<img width="700" alt="Screen Shot 2020-11-01 at 18 47 42" src="https://user-images.githubusercontent.com/1024246/97816256-c9a7d100-1c72-11eb-800d-d7c4962e530c.png">

```sh

🚨 Build failed.
Error: No transformers found for "/Users/wachunei/projects/directUC/directUC/src/fonts/RedHatText-Regular.ttf".
Error: No transformers found for "/Users/wachunei/projects/directUC/directUC/src/fonts/RedHatText-Regular.ttf".
    at ParcelConfig._getTransformerNodes (/Users/wachunei/projects/parcel/packages/core/core/src/ParcelConfig.js:212:13)
    at ParcelConfig.getTransformerNames (/Users/wachunei/projects/parcel/packages/core/core/src/ParcelConfig.js:223:29)
    at ConfigLoader.loadParcelConfig (/Users/wachunei/projects/parcel/packages/core/core/src/ConfigLoader.js:63:37)
    at /Users/wachunei/projects/parcel/packages/core/core/src/ConfigLoader.js:43:48
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at PromiseQueue._runFn (/Users/wachunei/projects/parcel/packages/core/utils/src/PromiseQueue.js:84:7)
    at PromiseQueue._next (/Users/wachunei/projects/parcel/packages/core/utils/src/PromiseQueue.js:73:5)
```

## 🔦 Context

I'm testing a proposed WebExtension transformer. I'm importing these files from a `.js` source and using them in as any other asset like an image. 

## 💻 Code Sample

File where I'm importing them:

https://github.com/wachunei/directUC/blob/develop/src/js/ui/components/GlobalStyles.jsx#L2-L5

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | #5304 
| Node             | 12
| npm/Yarn         | 1.22.5
| Operating System | macOS Big Sur

**Comment by 101arrowz** [comment]
Simple fix, use a URL import.
```js
import RedHatTextRegular from "url:../../../fonts/RedHatText-Regular.ttf";
import RedHatTextMedium from "url:../../../fonts/RedHatText-Medium.ttf";
import RedHatDisplayRegular from "url:../../../fonts/RedHatDisplay-Regular.ttf";
import RedHatDisplayMedium from "url:../../../fonts/RedHatDisplay-Medium.ttf";
```

See [the docs](https://v2.parceljs.org/configuration/plugin-configuration/#predefined-(offical)-named-pipelines) for more info.

**Comment by wachunei** [comment]
Oops, sorry for this, I'm definitely not used to the new API 😅. Thank you!
