### ISSUE TITLE
Cannot find module 'setimmediate'

### ISSUE THREAD

**Issue by markg85** [parcel-bundler/parcel#5306]
# 🐛 bug report

Exactly as the title says

## 💻 Code Sample
```js
import nkn from 'nkn-sdk';

new nkn.Client({seed: window.localStorage.nknWalletSeedKey});
```

Running this (with an index.html that includes the above as "index.js" which is then pulled through parcel) will give the following error:
```plain
src.e31bb0bc.js:37 Uncaught Error: Cannot find module 'setimmediate'
    at newRequire (src.e31bb0bc.js:37)
    at localRequire (src.e31bb0bc.js:53)
    at Object.parcelRequire.../node_modules/@nodeguy/channel/lib/index.js (index.js:3)
    at newRequire (src.e31bb0bc.js:47)
    at localRequire (src.e31bb0bc.js:53)
    at Object.parcelRequire.../node_modules/@nkn/ncp/lib/channel.js.@nodeguy/channel (channel.js:8)
    at newRequire (src.e31bb0bc.js:47)
    at localRequire (src.e31bb0bc.js:53)
    at Object.parcelRequire.../node_modules/@nkn/ncp/lib/connection.js../channel (connection.js:8)
    at newRequire (src.e31bb0bc.js:47)
```

I'm running parcel with: `parcel src/index.html` so nothing special there.
I don't have special config files.

Any idea what i might be doing wrong here?

Cheers,
Mark

**Comment by markg85** [comment]
Bump. Anyone?

**Comment by mischnic** [comment]
I'm fairly sure that this happens because `@nodeguy/channel` https://unpkg.com/@nodeguy/channel@0.6.6/lib/index.js does contains this and we don't pick up that require call because it's a template literal, not a string literal:

```js
require(`setimmediate`);
```

**Comment by markg85** [comment]
> I'm fairly sure that this happens because `@nodeguy/channel` https://unpkg.com/@nodeguy/channel@0.6.6/lib/index.js does contains this and we don't pick up that require call because it's a template literal, not a string literal:
> 
> ```js
> require(`setimmediate`);
> ```

Amazing!
I changed that locally to strings and it magically started working! Awesome :)

But now i wonder where the bug is and where i need to report anything?
Is this a parcel thing that needs to be fixed?
Or is this a `@nodeguy/channel` thing where that dev just needs to change it to strings?

**Comment by mischnic** [comment]
> Is this a parcel thing that needs to be fixed?

We could add support for this, but that fix would only land in Parcel 2.

The reason why we haven't done this so far is that template literals are usually used for interpolation:
```
var x = "immediate"
require(`set${x}`);
```

which we don't support at all, but this special case could be added.

> Or is this a @nodeguy/channel thing where that dev just needs to change it to strings?

Probably not, it does work fine in Node....

(Even the requires in their example uses template strings: https://gitlab.com/NodeGuy/channel#basic-use)

**Comment by mischnic** [comment]
-> https://github.com/parcel-bundler/parcel/issues/5492
