### ISSUE TITLE
Add options to omit filenames in build output

### ISSUE THREAD

**Issue by AnthumChris** [parcel-bundler/parcel#5307]
# 🙋 feature request

Could a build option be added to prevent sources filenames from being added to the output build when `--no-minify` is used?  Filenames sometimes contain sensitive data, including usernames or other personal information.

## 🤔 Expected Behavior

```sh
$ parcel build --no-minify src/test.js
```
```js
(function () {
  console.log('foo');
})();
//# sourceMappingURL=test.js.map
```

## 😯 Current Behavior

Current behavior includes `// ASSET: ...` which can expose our usernames
```js
(function () {
  // ASSET: /Users/MY_USERNAME/tmp/src/test.js
  console.log('foo');
})();
//# sourceMappingURL=test.js.map
```

## 💁 Possible Solution

Adding a `--no-filenames` CLI flag would be nice.

## 🔦 Context

Potential security flaw.  Personal data can be exposed if the `--no-minify` flag is used by users.

Our team needs to upload built JS packages that are human-readable by another team when they are are in production.  These files run within an isolated NodeJS process, and support teams who do not have access to source code repositories may need to quickly identify problems.

**Comment by mischnic** [comment]
I'm not entirely sure why we have those, but would a relative path from the project root (probably `ASSET: src/test.js`in your case) work?

**Comment by AnthumChris** [comment]
@mischnic I think that's a great idea, because it provides values specific to the project root, and not the users' filesystems.

**Comment by AnthumChris** [comment]
Thanks for having a look at this and considering it to be changed!
