### ISSUE TITLE
JS output files are sometimes garbled

### ISSUE THREAD

**Issue by shawwn** [parcel-bundler/parcel#531]
🐛 bug report

JS output files are sometimes garbled:

![image](https://user-images.githubusercontent.com/59632/34776406-671600ee-f5dc-11e7-893b-16cedd7c4247.png)

(Notice that the content is bogus.)

The problem goes away by changing `src/Bundle.js` as follows:

![image](https://user-images.githubusercontent.com/59632/34776438-89e1effc-f5dc-11e7-9bd4-2ce9c21a84dd.png)

**Comment by DeMoorJasper** [comment]
Should be fixed already
