### ISSUE TITLE
Parcel v2 doesnt ignore targets as specified in the docs

### ISSUE THREAD

**Issue by paeolo** [parcel-bundler/parcel#5312]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "test",
  "version": "1.0.0",
  "description": "Make the coffee",
  "author": "You",
  "license": "MIT",
  "main": "index.js",
  "targets": {
    "main": false
  },
  "engines": {
    "node": ">= 10.0.0"
  },
  "scripts": {
    "build": "parcel build ."
  },
  "devDependencies": {
    "parcel": "2.0.0-beta.1",
  }
}

```

## 🤔 Expected Behavior

According to https://v2.parceljs.org/configuration/package-json/#main-%2F-module-%2F-browser, parcel creates automatically a target for "main" if you specify it.

However you can disable it with:
```js
  "targets": {
    "main": false
  },
```
It should disable the target, hence not try to build your code since there are no targets!
## 😯 Current Behavior
Parcel try to build your code.

## 🔦 Context

For monorepos, it would be nice to be able to disable the build for a package using this, or another flag. This way you can use for instance
```command
yarn parcel build packages/*
```
and disable some packages you don't want parcel to deal with. This would enable a progressive approach to adopt parcel as a build system for every packages.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node              | 14
| npm/Yarn         | yarn 1.22.10
| Operating System | linux

**Comment by mischnic** [comment]
`parcel build ....` *will* build try to build something, even if there is no explicit target

**Comment by alphabet-codes** [comment]
@paeolo are you suggesting that parcel should return a message(E.g. no build target was found ), instead of trying to build your code?

**Comment by paeolo** [comment]
@alphabet-codes Yes, but afterthought not sure if it makes sense, I was just confused by how targets work. My use case is a monorepo, where you wants parcel to watch/build packages, e.g `parcel build packages/*` but where some of the packages are not meant to be built by parcel.

**Comment by alphabet-codes** [comment]
@paeolo Your expectation is that when you run `parcel build packages/*`, parcel should ignore packages that are set to false in the targets.

**Comment by paeolo** [comment]
@alphabet-codes Yes that was my expectation before @mischnic told me that was not the case. I came to that conclusion after reading https://v2.parceljs.org/configuration/package-json/#main-%2F-module-%2F-browser so maybe we could add something here in the docs precising how targets works or maybe we could someting in parcel code so it ignores some packages when you use a glob. Anyway, it's already possible to do the second solution with a custom script, since you can call parcel build with a liste of packages.

**Comment by alphabet-codes** [comment]
@paeolo Maybe we should add it to the documentation on how targets work.

**Comment by mischnic** [comment]
-> https://github.com/parcel-bundler/website/issues/759

**Comment by paeolo** [comment]
@mischnic  @alphabet-codes That's fine with me, I can close the issue;) Ty for your time.

**Comment by alphabet-codes** [comment]
@paeolo you're welcome.
