### ISSUE TITLE
Sourcemap columns are off by 1

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5314]
# 🐛 bug report

cc @DeMoorJasper 

### Code
```html
<script src="index.js"></script>
```
```js
console.log("Hello!");



console.log("Other!");
```

### Current Behaviour

Running `parcel index.html` and opening `localhost:1234` in Firefox leads to this console output:
```
Hello!   index.js:1:8
Other!   index.js:5:8
```

Opening the index file without Parcel in Firefox (no bundling):
```
Hello!   index.js:1:9
Other!   index.js:5:9
```

### Expected Behaviour

Probably the latter?

**Comment by DeMoorJasper** [comment]
Awesome, thanks for testing this out and reporting. Will definitely look into this asap.

**Comment by DeMoorJasper** [comment]
Just had a look into this yesterday while I was tweaking and fixing my sourcemap visualiser and couldn't really find any real bug with this?

If the non bundled run through babel or something? Or is it just basic firefox behaviour? In the first case there's probably a Parcel bug in the second it's probably just firefox doing different mappings than Babel

**Comment by mischnic** [comment]
> Is the non bundled run through babel or something?

No. Feel free to close the issue if this is as expected

**Comment by DeMoorJasper** [comment]
Gonna close this for now, we can reopen this later if it really turns out to be a problem
