### ISSUE TITLE
 Unknown version 59 of op_mob when using font-awesome

### ISSUE THREAD

**Issue by mikeyakymenko** [parcel-bundler/parcel#5320]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "browserslist": [
    "last 4 version",
    "> 2%",
    "not dead",
    "IE 11",
    "not op_mob 59"
  ],
}
```

## 🤔 Expected Behavior

works fine?

## 😯 Current Behavior

Just import font-awesome

```
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome'
import {faFile} from '@fortawesome/free-solid-svg-icons'
```

and got error: `node_modules/@fortawesome/react-fontawesome/index.es.js: Unknown version 59 of op_mob`
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 16.8.3
| Node             | v14.11.0
| npm/Yarn         | yarn
| Operating System | Mac OS X

**Comment by mischnic** [comment]
Are you using `browserslist` 4.14.4? You might need to bump the version in your lockfile. https://github.com/parcel-bundler/parcel/issues/5164#issuecomment-696926731

> Parcel 16.8.3

There is no such version, the last v1 release was 1.12.4

**Comment by aileo** [comment]
I had the same problem (node 14.15.0 but using npm on ubuntu and parcel 1.12.4).

Thank you @mischnic, adding `"browserslist": "4.14.4"` as a dev dependency to my package.json solved it.
