### ISSUE TITLE
ParcelV2 not linking some images

### ISSUE THREAD

**Issue by bronze** [parcel-bundler/parcel#5328]
# 🐛 bug report
In V2, only images with `src` values are being bundled.
I'm using [UIkit](https://getuikit.com/) and they allow having an image with data-src, which then lazyloads. Another feature is background-images, pointing to the image url through a style url value in the html.
These images are not being recognized by V2 (had no problems on V1).

## 🎛 Configuration (.babelrc, package.json, cli command)
I have set up a demo on https://parcel2-imagebug.netlify.app/
Code at https://github.com/bronze/parcel2-imagebug

## 🤔 Expected Behavior
Recognizing these images and changing their address in the HTML.

**Comment by mischnic** [comment]
> had no problems on V1)

You mean `data-src` was being handled by Parcel 1?

**Comment by bronze** [comment]
@mischnic yes. I have no problem with *only* `data-src` on Parcel 1. It recognizes and bundles the images.

**Comment by mischnic** [comment]
> It recognizes and bundles the images.

But not `data-src`,  this is the output from your repo with Parcel 1 (`dist/index.html`):

```html
...
<img data-src="./img/isaac-quesada-mLDJLlx_ei4-unsplash.jpg" height="300" width="auto" class=" uk-responsive-height" uk-img="">
...
<img src="/isaac-quesada-mLDJLlx_ei4-unsplash.075d691e.jpg" height="300" width="auto" class="" uk-img="">
```

The first path wasn't rewritten, only the second one.

**Comment by bronze** [comment]
it appears I missed `parcel-plugin-lazy` in package.json... I'm terribly sorry.
closed.
