### ISSUE TITLE
Upgrading PostCSS8,the bug "'watchman' 不是内部或外部命令" was reported

### ISSUE THREAD

**Issue by tuhongwei** [parcel-bundler/parcel#5332]
# 🐛 bug report
When I updated PostCSS to >=8.0 by 'yarn add parcel@nightly',the error 'watchman' 不是内部或外部命令' was shown. And the package PostCss was not updated 8.

## 🎛 Configuration (.babelrc, package.json, cli command)
.postcssrc.js configuration 
module.exports = {
  plugins: {
    "postcss-import": {},
    "postcss-url": {},
    // to edit target browsers: use "browserslist" field in package.json
    "autoprefixer": {},
    "postcss-px-to-viewport": {
      viewportWidth: 750,
      viewportHeight: 1334,
      unitPrecision: 3,
      viewportUnit: 'vw',
      selectorBlackList: ['.usepixel'],
      mediaQuery: true,
      exclude: /node_modules/i
    }
  }
};

```js
{
  "your": { "config": "here" }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | 10.15.1
| npm/Yarn         | 6.4.1/1.13.0
| Operating System | windows7 x64

**Comment by vasanthdeveloper** [comment]
Try removing `yarn.lock` and `node_modules/` and then reinstall dependencies using `yarn`.

That did the trick for me.
