### ISSUE TITLE
Parcel ignoring PeerDependency if dependency has been installed in a library

### ISSUE THREAD

**Issue by dsluijk** [parcel-bundler/parcel#5336]
# 🐛 bug report

When using experimental scope hoisting the PeerDependency list is ignored for libraries when the dependency is also in `node_modules`. Any dependencies are included twice in the final bundle.

## 🎛 Configuration (.babelrc, package.json, cli command)

https://git.dany.dev/dsluijk/parcelpeers

## 🤔 Expected Behavior

There should be only one entity of a library in the final bundle output.

## 😯 Current Behavior

Two instances of the same library are included in the bundle, inflating the bundle unnecessary.

## 💁 Possible Solution

Check if a library is in peerdependencies before adding it into the bundle. As it's a peer dependency it's fair to assume another installation will be bundled.

## 🔦 Context

The library has the dependency both listed as dev as well as peer dependency. This is needed because we need it as a dev dependency for the build step, and as a peer dependency for actual usage of the library.

## 💻 Code Sample

I've created an example project here: https://git.dany.dev/dsluijk/parcelpeers

To reproduce:
1. Clone the repository.
2. Go into the `library` folder and run `yarn` + `yarn build`. This build the library, and also installs `preact` into `node_modules` as it's listed as dev dependency.
3. Exit `library` and enter `app`.
4. Install dependencies with `yarn`, this installs the second installation of `preact` as it's listed as a dependency.
5. Build and serve with `yarn serve`.
6. Go to http://localhost:1234/report.html to view the bundle report. Notice `preact` is included twice here.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4  |
| Node             | 15.1.0 |
| npm/Yarn         | Yarn 1.12.4 |
| Operating System | Arch Linux x86_64, 5.9.6-arch1-1 |

**Comment by dsluijk** [comment]
I just tried it with Parcel 2, and this is still an issue there

**Comment by dsluijk** [comment]
I resolved my issue by aliassing my dependency in `package.json` like so:

```json
  "alias": {
    "preact": "./node_modules/preact",
    "teenyui": "../"
  },

This did resolve my issue but it is also a hack, and should still be resolved properly.

**Comment by tripolskypetr** [comment]
Hello there! Still waiting for React components library bundling support on Parcel 2...

![image](https://user-images.githubusercontent.com/19227776/142487456-7c5aaa21-dce0-4c8a-a890-bab7b1fb14ca.png)

**Comment by michox** [comment]
This issue is still occurring, can we reopen this issue, please?

**Comment by LEW21** [comment]
Looks like a duplicate of #3971.
