### ISSUE TITLE
Parcel v2: Setting composite to true breaks transformer-typescript-types

### ISSUE THREAD

**Issue by paeolo** [parcel-bundler/parcel#5344]
# 🐛 bug report

`@parcel/transformer-typescript-types` is broken when setting `composite: true` in the `compilerOptions` of `tsconfig.json`
- When building with the example provided below I have this error:
```console
@parcel/transformer-typescript-types: File '~/parcel-issue-6786/src/add.ts' is not listed within the file list of project ''. Projects must list all files or use an 'include' pattern.
/home/paul/parcel-issue-6786/src/index.ts:1:15
> 1 | export * from './add';
>   |               ^^^^^^^^ File '/home/paul/parcel-issue-6786/src/add.ts' is not listed within the file list of project ''. Projects must list all files or use an 'include' pattern.
  2 | export default 'Hello World!';
```
- Looking at the `index.d.ts` file there are no types emitted.
## 🎛 Configuration (.babelrc, package.json, cli command)

https://github.com/paeolo/parcel-issue-5344

## 🤔 Expected Behavior

- `transformer-typescript-types` should make the types as if `composite: true` were not set. [composite](https://www.typescriptlang.org/docs/handbook/project-references.html#composite) shouldn't have an impact on type generation.
- Adding (patching) `composite: false` to [this line](https://github.com/parcel-bundler/parcel/blob/3bfef2821b6fa8031e8ec7778132581296266faa/packages/transformers/typescript-types/src/TSTypesTransformer.js#L34) does the trick for me. Types are emitted correctly. But maybe the fix is somewhere else;)

**Comment by mischnic** [comment]
> Adding (patching) composite: false to this line does the trick for me

AFAICT, that sounds good

**Comment by paeolo** [comment]
@mischnic fine;) Do you want me to do a PR for this?

**Comment by mischnic** [comment]
Sure
