### ISSUE TITLE
How to tell parcel to not bundle everything?

### ISSUE THREAD

**Issue by markg85** [parcel-bundler/parcel#5348]
Hi,

There's code that's build with node.js and would not run natively on the browser without a bundler.
Here parcel works amazingly simple and give you a js file that works in the browser. Super!
An example of that for my specific usecase is the [NKN SDK](https://github.com/nknorg/nkn-sdk-js).

Some packages provide a browser js blob (NKN in this case [does](https://github.com/nknorg/nkn-sdk-js/tree/master/dist) too).

But, as convenience is high, there is a really easy habit of just writing your site "with parcel" where parcel generates the js and css bundles for you.

Herein lies a problem.

Say you're using jQuery and bootstrap. Not a very uncommon combination of libraries to use.
You probably type something like:
```js
import $ from 'jquery';
import 'bootstrap'
```

From a developer point of view this is super handy!
From a performance point of view this is super bad.

Parcel makes a bundle out of it so you get 1 big file (1 for js, 1 for css).
Now the whole use of a CDN has become impossible.
Even if you were using libraries that were perfectly happy on your browser and wouldn't need parcel functionality at all.

Now i'm wondering. Is there a way to have the ease of use with parcel while maintaining the advantages of having a CDN?
For example, if i do:
```js
import $ from 'jquery'
```
I would expect parcel to **add** a line like:
```html
<script src="<some popular cdn>jquery-3.5.1.min.js"></script>
```

Or are there other projects out there that do this?
That give you the speed and ease of use of parcel but without bundling everything?

Cheers,
Mark

**Comment by devongovett** [comment]
You can do this using aliases in Parcel 2. You'll need to add the jQuery script tag from the CDN to your HTML page yourself, but then you can map the `jquery` import specifier to the existing global variable.

```html
<script src="https://cdn.com/jquery.js"></script>
```

package.json:
```json
{
  "alias": {
    "jquery": { "global": "jQuery" }
  }
}
```

See https://v2.parceljs.org/features/module-resolution#aliases

**Comment by markg85** [comment]
> You can do this using aliases in Parcel 2. You'll need to add the jQuery script tag from the CDN to your HTML page yourself, but then you can map the `jquery` import specifier to the existing global variable.
> 
> ```
> <script src="https://cdn.com/jquery.js"></script>
> ```
> 
> package.json:
> 
> ```json
> {
>   "alias": {
>     "jquery": { "global": "jQuery" }
>   }
> }
> ```
> 
> See https://v2.parceljs.org/features/module-resolution#aliases

That, to me, is pure magical.
As nothing in the config seems to define anything that i would read as "include this yourself in html script, it won't be bundled"..
Why isn't there something more obvious then this? No wonder i have a hard time figuring it out if it's named something seemingly completely different.

I would name it something like "excludeBundle" with a format like:
```json
{
    "excludeBundle": [
        {"jQuery": "https://cdn.com/jquery.js" },
        {"Socket.IO": "..." },
    ]
}
```
(note: literally just made this up, but you get the idea of a simple understandable syntax)

That would make a lot more sense to me. And by default i would add whatever is excluded from bundling to html script tags with the value url above. This would still give parcel the magic ability to do everything automatically while being CDN friendly.
