### ISSUE TITLE
v2 - WebComponents (LitElement) empty build

### ISSUE THREAD

**Issue by LukeTOBrien** [parcel-bundler/parcel#5361]
I am using TypeScript.  

I am creating a repository of WebComponents using [LitElement](https://lit-element.polymer-project.org/).  
The project doesn't have a single main entry point like index.js/ts, rather I have a folder structure with WebComponent (widget) files that I want to build individually.  
So I have a structure like:

* src
  * Paint
    * PaintWidget.ts
  * MusicBox
    * MusicBoxWidget.ts
  * ...

I am finding that Parcel is building and then disregarding my WebComponent classes.

# 🐛 bug report

I have the following script:

```
"build": "parcel build src/**/*Widget.ts --no-minify --dist-dir out"
```

When I run, it build fine but it seems to disregard the class, so the output is empty.  

```
> parcel build src/**/*Widget.ts --dist-dir out

√ Built in 5.70s

out\Paint\PaintWidget.js    41 B    894ms
```

The terminal outputs that the *Widget.ts is building,, and as you can see it is taking 894ms, but the transformed code is disregarded and the outputted JS lis empty:

```js

//# sourceMappingURL=PaintWidget.js.map

```

If I use `--no-minify` then I get 60B:

```js
(function () {})();
//# sourceMappingURL=PaintWidget.js.map
```

I think it might be an issue with scope, but when I try and set the class as a `window` variable, still no joy.

## 🎛 Configuration tsconfig.json

```js
{
  "compilerOptions": {
      "module": "CommonJS",
      "noImplicitAny": false,
      "removeComments": true,
      "preserveConstEnums": true,
      "sourceMap": true,
      "esModuleInterop": true,
      "target": "es6",
      "experimentalDecorators": true
  }
}
```

## 🤔 Expected Behavior

The WebComponent class should be not disregarded.

**Comment by mischnic** [comment]
1. Which Parcel version?
2. What does `PaintWidget.ts` look like? Does it export a value? Does it register the webcomponent?

**Comment by LukeTOBrien** [comment]
I am using Parcel 2  
`"parcel": "^2.0.0-beta.1"`

`PaintWidget` exports a class extending `LitElement`

```js
import { html, LitElement, unsafeCSS } from "lit-element";
import { customElement } from "lit-element/lib/decorators";

import styles from "./PaintWidget.less";

@customElement('paint-widget')
export class PaintWidget extends LitElement {
    
    static styles = unsafeCSS(styles);

    constructor() {
        super();
    }

    firstUpdated() {
    ...
    }

    render() {
        return html`<div id="paint"></div>`;
    }

}
```

**Comment by mischnic** [comment]
A workaround for now is adding this to package.json.
```js
	"targets": {
		"default": {
			"isLibrary": true,
			"outputFormat": "esmodule"
		}
	}
```
(alternatively `commonjs` as output format).

I was also slightly surprised to see this, maybe we can make this require less configuration...

**Comment by LukeTOBrien** [comment]
hmm, still 41B

```
> parcel build src/**/*Widget.ts --dist-dir out

√ Built in 6.61s

out\Paint\PaintWidget.js    41 B    1.04s
```

I also have `browserslist`
```js
"targets": {
		"default": {
			"isLibrary": true,
			"outputFormat": "esmodule"
		}
	},
  "browserslist": [
    "last 3 and_chr versions",
    "last 3 chrome versions",
    "last 3 opera versions",
    "last 3 ios_saf versions",
    "last 3 safari versions"
]
```

I think I will create a minimal repo.

**Comment by mischnic** [comment]
Can you try deleting `.parcel-cache` and rerunning?

At least when I tried this, there was something strange going on:
```
$ yarn parcel build src/widget.ts --no-cache --no-minify
110.43 KB bundle
$ yarn parcel build src/widget.ts --no-minify
empty bundle...
$ rm -rf .parcel-cache && yarn parcel build src/widget.ts --no-minify
110.43 KB bundle
```

**Comment by LukeTOBrien** [comment]
It took longer, still 41B

```
> parcel build src/**/*Widget.ts --dist-dir out

√ Built in 41.61s

out\Paint\PaintWidget.js    41 B    3.78s
```

.... I [created a minimal repo](https://github.com/LukeTOBrien/Parcel2LitElement), but when I run the build script....  
Is there something wrong with how I set it up? I'll take another look tomorrow.

```
PS C:\Parcel2LitElement> npm run build

> lil-repo@ build C:\Parcel2LitElement
> parcel build src/**/Widget*.ts --dist-dir out

× Build failed.
Error: Unexpected token 'export'
C:\Parcel2LitElement\node_modules\@parcel\ts-utils\src\index.js:2
export * from './FSHost';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at NodePackageManager.load (C:\Parcel2LitElement\node_modules\@parcel\package-manager\lib\NodePackageManager.js:192:9)
    at NodePackageManager.requireSync (C:\Parcel2LitElement\node_modules\@parcel\package-manager\lib\NodePackageManager.js:156:17)
    at Module.m.require (C:\Parcel2LitElement\node_modules\@parcel\package-manager\lib\NodePackageManager.js:178:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Parcel2LitElement\node_modules\@parcel\transformer-typescript-tsc\lib\TSCTransformer.js:10:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
```

**Comment by mischnic** [comment]
>     "@parcel/transformer-typescript-tsc": "^2.0.0-alpha.3",

There was a publish mishap in that version, use the version `next` here (so the beta)

**Comment by LukeTOBrien** [comment]
Thanks, after updating to the `beta.1` it now works fine, I added another component and the glob patten is working:

```
> parcel build src/**/Widget*.ts --dist-dir out

√ Built in 10.18s

out\Widget1\Widget1.js    20.82 KB    1.85s
out\Widget2\Widget2.js    20.82 KB    1.85s
```

I had to change to `outputformat` to `global`, after I tested my real component:

```js
"targets": {
    "default": {
      "isLibrary": true,
      "outputFormat": "global"
    }
  }
```

There also seemd to be an issue with quotes and glob patten, if I have the patten enclosed in quotes then the terminal say it has built but actually nothing happens:

```
> parcel build 'src/**/Widget*.ts' --dist-dir out

√ Built in 2.10s
```

As an aside, I wanted to get [Less working with PostCSS](https://v2.parceljs.org/languages/less/), with a LitElement, styles are string variables. In Parcel 1 project I used [parcel-plugin-text](https://www.npmjs.com/package/parcel-plugin-text).  
But that's a task for another day.

**Comment by mischnic** [comment]
Do you still get empty bundles with the latest versions?

> As an aside, I wanted to get Less working with PostCSS, with a LitElement, styles are string variables. In Parcel 1 project I used parcel-plugin-text.
But that's a task for another day.

Are you looking for `bundle-text:`? https://v2.parceljs.org/configuration/plugin-configuration/#predefined-(offical)-named-pipelines

**Comment by LukeTOBrien** [comment]
No I am not getting empty bundles, they are as expected and okay (just had to change the `outputformat`.

> Are you looking for bundle-text?

Yeah that `bundle-text` thing looks nifty and should be what I need thanks!  
The Less is processed I guess? You should add bundle-text on the the [Less doc](https://v2.parceljs.org/languages/less/).
