### ISSUE TITLE
Ctrl-c exit on windows hangs

### ISSUE THREAD

**Issue by anavarro9731** [parcel-bundler/parcel#5365]
# 🐛 bug report

When using Ctrl-C I get the "Parcel is shutting down" message and then it just hangs.  
Running from .bin or npm/npx all same problem. 
If i terminate the script with repeated Ctrl-C commands, the node process is still running and I then have to kill it manually
This happens even when the only thing I am compiling is a barebones HTML file

Presumably something with my setup? as no one else has raised this, but I'm not aware of any other issues with node, and wondering if other may also have the same problem.

## 🤔 Expected Behavior

It should exit to the terminal prompt

## 😯 Current Behavior

It just hangs on "shutting down" message

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.452
| Node             | 12.0.0
| npm/Yarn         | 6.9.0
| Operating System | Windows 10

## 🎛 Configuration (.babelrc, package.json, cli command)

calling npx parcel serve ../index.html 

no babel config,
```
{
  "name": "soap-app-sample",
  "version": "1.0.0",
  "dependencies": {
    "@azure/service-bus": "^7.0.0-preview.8",
    "@soap/modules": "^1.17.0",
    "@soap/react": "^1.11.0",
    "prop-types": "15.7.2",
    "react": "^16.14.0",
    "react-dom": "^16.14.0",
    "sanitize.css": "^8.0.1"
  },
  "devDependencies": {
    "parcel": "^2.0.0-beta.1",
    "@babel/core": "7.4.3"
  },
  "scripts": {
    "build": "npx parcel build ../index.html --public-url ./",
    "run": "npx parcel serve ../index.html"
  }
}

```

**Comment by anavarro9731** [comment]
Discovered for reasons I don't understand that by upgrading to node 15.2 from node 12 and also changing from NPM to YARN it now shuts down ok. I assume the change of node versions was the real reason without having tested both changes independently.

**Comment by NekitCorp** [comment]
Faced the same problem, command `Ctrl + C` does't work:

```
Server running at http://localhost:1234
√ Built in 20ms
Parcel is shutting down...
Parcel is shutting down...
Parcel is shutting down...
Parcel is shutting down...
Parcel is shutting down...
Parcel is shutting down...
Parcel is shutting down...
Parcel is shutting down...
Parcel is shutting down...
```

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1 |
| Node             | v16.13.1 |
| npm/Yarn         | npm v8.1.2 |
| Operating System | Windows 11 |

Tried to build a simple web application from the [example documentation](https://parceljs.org/getting-started/webapp/). Process termination on startup through `npx parcel src/index.html` occurs normally. But when using [package scripts](https://parceljs.org/getting-started/webapp/#package-scripts) this problem occurs.

**Comment by bmix** [comment]
@anavarro9731 Could you, please, reopen this, so the devs see it? Thanks.

I also have this problem but with pnpm/pnpx. It's interesting to note, that, for some reason, disk becomes very active, after `CTRL-C`.

|Software|Verion(s) |
|----------|----------|
|Node      |   14.17.0|
|pnpx       |     6.14.3|
|Windows|           10|
|Parcel     |       2.2.1|

`config.json` is:

```json
{
  "name": "app-example",
  "version": "0.1.0-exp",
  "description": "Testsite for app-example",
  "main": "index.xhtml",
  "source": "index.xhtml",  
  "scripts": {
    "start": "parcel index.xhtml",
    "build": "parcel build index.xhtml --public-url ./"
  },
  "devDependencies": {
    "parcel": "latest"
  },
  "dependencies": {
    "jquery": "latest",
    "easy-autocomplete": "latest"
  }
}
```

**Comment by pklaschka** [comment]
Not sure how this is related, but there seems to be some relation to #7271 (when a lock file exists higher up in the file tree, it fails).

I was also experiencing this issue (Node 16, npm 8, Windows 10, Parcel 2.3.2), and after deleting a `package-lock.json` file, I found higher up in the file tree (3 levels up, in my case), it solved this issue for me, as well.

So I'm not sure if/how this is related, but my best guess is that a lock file higher up the package tree brings Parcel into some undefined state where all kinds of weird stuff can happen 🤔 .

Not sure if this is "the only issue" at play, here, but maybe it'll help somebody 🙂

**Comment by lucasdavidferrero** [comment]
> Not sure how this is related, but there seems to be some relation to #7271 (when a lock file exists higher up in the file tree, it fails).
> 
> I was also experiencing this issue (Node 16, npm 8, Windows 10, Parcel 2.3.2), and after deleting a `package-lock.json` file, I found higher up in the file tree (3 levels up, in my case), it solved this issue for me, as well.
> 
> So I'm not sure if/how this is related, but my best guess is that a lock file higher up the package tree brings Parcel into some undefined state where all kinds of weird stuff can happen 🤔 .
> 
> Not sure if this is "the only issue" at play, here, but maybe it'll help somebody 🙂

I can confirm that I'm facing both: this issue and #7271. Node 16, Parcel 2.3.2, yarn 3.2.0 on Windows 10. 

So, there must be some kind of relation as @pklaschka says.
