### ISSUE TITLE
Parcel doesn't load external scss styles

### ISSUE THREAD

**Issue by brachkow** [parcel-bundler/parcel#5366]
# 🐛 bug report

When I am building a component with external scss styles imported via <style> tag, there are no styles loaded. But when I inline them into style tag they are loaded.

## 🎛 Configuration (.babelrc, package.json, cli command)

I run parcel with zero config.

## 🤔 Expected Behavior

Styles imported like this `<style src="./App.scss" lang="scss" scoped/>` must be loaded.

## 😯 Current Behavior

They are not loaded.

## 💻 Code Sample
```
<style src="./App.scss" lang="scss" scoped/> // not working

<style lang="scss" scoped> // working
.App {
  background-color: red;
}
</style>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.5
| Node             | 12.19.1
| npm/Yarn         | 1.22.10
| Operating System | MacOS 11.0.1

**Comment by DeMoorJasper** [comment]
Could you give a little more context, what file is the code sample for example.

Parcel 1 development has discontinued though, so you might want to try out Parcel 2

**Comment by brachkow** [comment]
App.vue
```
<template>
  <div class="app">
    It's not working
  </div>
</template>

<style src="./App.scss" lang="scss" scoped/>
```
App.scss
```
.app {
  background-color: red;
}
```

**Comment by brachkow** [comment]
As I remember closing style helped:
`<style src="./App.scss" lang="scss" scoped/>` → `<style src="./App.scss" lang="scss" scoped></style>`
