### ISSUE TITLE
Runtimes map to incorrect source files in source maps

### ISSUE THREAD

**Issue by DeMoorJasper** [parcel-bundler/parcel#5380]
# 🐛 bug report

Currently whenever a runtime asset gets created it maps to the runtime plugin in the sourcemap instead of the actual runtime asset.

The reason I've opened this issue is to provide some more context and figure out a proper solution for this as it'll require some reworking in the core logic of runtimes and/or asset requests

Example:

![Screenshot 2020-11-22 at 16 37 15](https://user-images.githubusercontent.com/2175521/99908117-ff276380-2ce0-11eb-9dce-1c15de0b8952.png)

## 🤔 Expected Behavior

Should map to the runtime's generated code.

## 😯 Current Behavior

Maps to the source code of the runtime plugin

## 💁 Possible Solution

I've got 2 ideas on how to fix this:

- Allow returning a sourcemap in the runtime plugin or generate one in applyRuntimes, both is currently impossible as `AssetRequestInput` has no sourcemap value.

- Implement some layer of virtual fs and create the files virtually.

## 🔦 Context

Trying to fix the remaining source map bugs

## 💻 Code Sample

```JS
import parcel from 'url:./parcel.webp';

console.log('test');

```

## 🌍 Your Environment

Current `v2` branch

**Comment by devongovett** [comment]
I like the idea of returning a source map from runtimes as part of assetrequestinput. But in most cases the source map should basically be an empty map that's 1:1 with the code, so maybe in the transformer when AssetRequestInput has a code property it could automatically generate an empty map if none is available?

**Comment by DeMoorJasper** [comment]
@devongovett the main issue is the actual source content being incorrect so in that case we would inline that source content into the 1:1 map?

Another issue I see with this is that it will need to reference some kind of unique/generated filepath that doesn't actually exist in the sourcemap as we deduplicate source references in the sourcemap library. I assume it'll be fine but could cause issues.

**Comment by mischnic** [comment]
Change the `RuntimeAsset`  type to contain `resolveFromDir` instead of `filePath`, then the path could be `${dir}/${md5(code)}.js` (that md5(code) is also the asset id)?

**Comment by devongovett** [comment]
Yeah that seems reasonable

**Comment by cdll** [comment]
this issue is still in v1 version~

**Comment by devongovett** [comment]
I think this is fixed now?
