### ISSUE TITLE
An array `package.json#source` should build these specified entries.

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5387]
Running `parcel build my-package/` should build `a.html, b.html` if `my-package/package.json` contains:
```json
{
  "source": ["a.html", "b.html"]
}
```

So be equivalent to `cd my-package && parcel build a.html b.html`.

The docs already say this should work: https://v2.parceljs.org/configuration/package-json/#source

Relevant code:
https://github.com/parcel-bundler/parcel/blob/064ba0a166ea63ccd2b623dc11324d4cd7ffb526/packages/core/core/src/requests/EntryRequest.js#L98-L126

**Comment by alphabet-codes** [comment]
@mischnic I'd love to pick this issue up.

**Comment by alphabet-codes** [comment]
Thanks, @mischnic

**Comment by alphabet-codes** [comment]
@mischnic how do you run build if there's a source file `{"source": "src/index.js"}` in your package.json for instance?

**Comment by mischnic** [comment]
Pass the directory which contains the package.json as an argument:

> Running `parcel build my-package/` should build `a.html, b.html` if `my-package/package.json` contains:

**Comment by alphabet-codes** [comment]
@mischnic I keep getting an error that says "no entries found" when I run the above command why?

**Comment by mischnic** [comment]
Example: https://github.com/mischnic/parcel-issue-5387

**Comment by alphabet-codes** [comment]
@mischnic, please help me review #5451. some checks are not passing

**Comment by alphabet-codes** [comment]
@mischnic, please review this pull request, so that I can pick up a new issue and work on it.

**Comment by mischnic** [comment]
You can also work on something else even before you PR is merged, if you want.
