### ISSUE TITLE
WebWorkers not working: window is not defined

### ISSUE THREAD

**Issue by cfoust** [parcel-bundler/parcel#5388]
# 🐛 bug report

It appears that hot module reloading breaks in WebWorkers because it assumes that `window` is defined. This looks very related to https://github.com/parcel-bundler/parcel/issues/5180 but I can't say for sure. This only occurs in development and seems related to HMR.

## 🎛 Configuration (.babelrc, package.json, cli command)

`babel.config.json`
```js
{
  "presets": [
    "@babel/react",
    "@babel/flow",
    [
      "@babel/preset-env",
      {
        "corejs": 3,
        "useBuiltIns": "usage"
      }
    ]
  ],
  "plugins": ["@babel/plugin-proposal-class-properties"]
}
```

Excerpt from `package.json`
```js
"devDependencies": {
  "@babel/core": "7.12.0",
  "@babel/node": "7.10.5",
  "@babel/plugin-proposal-class-properties": "7.10.4",
  "@babel/preset-env": "7.11.5",
  "@babel/preset-flow": "7.10.4",
  "@babel/preset-react": "7.10.4",
  "parcel": "2.0.0-nightly.462",
}
```

## 🤔 Expected Behavior

WebWorkers should work.

## 😯 Current Behavior

WebWorkers fail when they are created if they rely on modules that import React.

Here's the relevant code in the worker causing issues:
```js
var helpers = require("../../../../@parcel/transformer-react-refresh-wrap/lib/helpers/helpers.js");

var prevRefreshReg = window.$RefreshReg$;
var prevRefreshSig = window.$RefreshSig$;
helpers.prelude(module);
```

Here's an example of a stack trace:
![image](https://user-images.githubusercontent.com/4588553/100172626-97f2e600-2e7d-11eb-8170-922b8139cae1.png)

## 💁 Possible Solution

It appears that someone suggested a solution here: https://github.com/parcel-bundler/parcel/issues/5180#issuecomment-699692881

## 🔦 Context

We make extensive use of WebWorkers and Parcel 2 has been super dodgy with them. Even now things don't seem to work very well, though I've yet to file bug reports.

## 💻 Code Sample

Will do this soon.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.462
| Node             | 1.22.4
| npm/Yarn         | 1.22.4
| Operating System | Linux

**Comment by cfoust** [comment]
For those looking for a workaround, this appears to work but is unsatisfying and janky:
```js
const W = self.Worker
self.Worker = function (url, options) {
  const code = `
  var globalObject =
    typeof globalThis !== 'undefined'
      ? globalThis
      : typeof self !== 'undefined'
      ? self
      : typeof window !== 'undefined'
      ? window
      : typeof global !== 'undefined'
      ? global
      : {};
  var window = globalObject
  importScripts = (function(){return this.apply(self,[].slice.call(arguments).filter(function(x){return !/\\.css$/i.test(x)}).map(v => v.startsWith('./') ? '${
    window.location.href
  }' + v.slice(2) : v))}).bind(importScripts)\nimportScripts(${JSON.stringify(
    url
  )})`

  return new W(
    URL.createObjectURL(new Blob([code], { type: 'text/javascript' })),
    options
  )
}
```
Put this as close to the beginning of your main JS bundle as possible.

**Comment by devongovett** [comment]
We should probably check if the environment is a worker and exclude react refresh in that case.

Here: https://github.com/parcel-bundler/parcel/blob/064ba0a166ea63ccd2b623dc11324d4cd7ffb526/packages/transformers/react-refresh-wrap/src/ReactRefreshWrapTransformer.js#L37

And here: https://github.com/parcel-bundler/parcel/blob/064ba0a166ea63ccd2b623dc11324d4cd7ffb526/packages/transformers/react-refresh-babel/src/ReactRefreshBabelTransformer.js#L10

cc. @mischnic

**Comment by mischnic** [comment]
Indeed, as I've said here in the duplicate issue: https://github.com/parcel-bundler/parcel/issues/5180#issuecomment-699692881
