### ISSUE TITLE
Parcel 2: A way to avoid processing <link href>

### ISSUE THREAD

**Issue by ai** [parcel-bundler/parcel#5397]
# 🙋 feature request

I want to serve website icon from canonical `/favicon.ico` URL (without any cache buster). How I can achive it with Parcel 2?

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link rel="icon" href="/favicon.ico">
```

## 🤔 Expected Behavior

Have some way to ignore `<link>` or to avoid adding cache busters to file name.

## 😯 Current Behavior

I didn’t find a way in [Predefined (offical) named pipelines](https://v2.parceljs.org/configuration/plugin-configuration/#predefined-(offical)-named-pipelines) or `@parcel/transformer-html` sources.

## 💁 Possible Solution

```html
<link rel="icon" href="ignore:/favicon.ico">
```

or

```html
<link rel="icon" href="keep-origin:/favicon.ico">
```

**Comment by mischnic** [comment]
Do you actually want to ignore the tag (as in: not copy over the icon into the dist directory)? -> https://github.com/parcel-bundler/parcel/issues/1087

Or should Parcel simply omit the hash and otherwise behave the same? (e.g. what `<a href="...">` currently does)?

**Comment by ai** [comment]
> Do you actually want to ignore the tag (as in: not copy over the icon into the dist directory)? -> #1087

It is enouph. Thanks for the fast response (Parcel has the best support in all bundlers).

Sorry, I try to search for existed issues, but was not lucky.
