### ISSUE TITLE
The plugin "parcel-validator-eslint" is not compatible with the current version of Parcel

### ISSUE THREAD

**Issue by RyoheiTomiyama** [parcel-bundler/parcel#5399]
# 🐛 bug report

I created this plugin
https://github.com/RyoheiTomiyama/parcel-validator-eslint

I specified a `package.json#engines.parcel`.  
but, it got error.

```bash
$ parcel watch ./src/assets/*/*.{scss,js} --dist-dir ./assets --no-cache
🚨 Build failed.
Error: The plugin "parcel-validator-eslint" is not compatible with the current version of Parcel. 
Requires "2.x" but the current version is "2.0.0-beta.1".
```

if `package.json#engines.parcel` is specified `2.0.0-beta.1`, it's no problem.

What should I do now?

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json is here.

```json
{
  "name": "parcel-validator-eslint",
  "version": "0.1.0",
  "author": "RyoheiTomiyama",
  "engines": {
    "parcel": "2.x"
  },
  "license": "MIT",
  "keywords": [
    "Parcel"
  ],
  "source": "src/EslintValidator.js",
  "main": "dist/EslintValidator.cjs.js",
  "module": "dist/EslintValidator.esm.js",
  "unpkg": "dist/EslintValidator.umd.js",
  "scripts": {
    "build": "rollup --config build/rollup.config.js"
  },
  "devDependencies": {
    "@parcel/plugin": "^2.0.0-beta.1",
    "@parcel/utils": "^2.0.0-beta.1",
    "@rollup/plugin-buble": "^0.21.3",
    "rollup": "^2.34.0"
  }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | v14.15.1
| npm/Yarn         | Yarn 1.22.1
| Operating System | macOS Catalina 10.15.7

**Comment by mischnic** [comment]
So you copied the source from https://github.com/parcel-bundler/parcel/blob/v2/packages/validators/eslint/src/EslintValidator.js

but didn't do this:?

https://github.com/parcel-bundler/parcel/blob/064ba0a166ea63ccd2b623dc11324d4cd7ffb526/packages/validators/eslint/package.json#L18-L21

> if package.json#engines.parcel is specified 2.0.0-beta.1, it's no problem.
> What should I do now?

Why don't you want to do that?

**Comment by RyoheiTomiyama** [comment]
Sorry, I can do that.  
I mistaken `alpha` for `beta`...

Thanks your reply
