### ISSUE TITLE
WebWorkers: Support new Worker( new URL() ) syntax

### ISSUE THREAD

**Issue by gkjohnson** [parcel-bundler/parcel#5430]
# 🙋 feature request

As of v5 Webpack has [introduced support for WebWorkers](https://github.com/webpack/webpack/issues/6472#issuecomment-693549090) with the following syntax:

```js
const worker = new Worker( new URL( './worker.js', import.meta.url ) );
```

This is the right way to load a Worker with a relative path from a module. However this doesn't work in Parcel. It would be great if parcel supported this for Workers (or parsing new URL in general) to support this use case so packages can be written and used consistently across bundlers.

## 🤔 Expected Behavior

The following should instantiate a new Worker next to the current module file.

```js
const worker = new Worker( new URL( './worker.js', import.meta.url ) );
```

## 😯 Current Behavior

The worker is loaded from the wrong path.

## 💁 Possible Solution

Account for `new URL( <path>, import.meta.url )` when processing Workers.

## 🔦 Context

My valid, browser-runnable code cannot be built with Parcel but can be built with Webpack. I would like to be able to write code that works consistently across browsers and bundlers.

**Comment by mischnic** [comment]
Is there any official documentation for that?

This special case (`new Worker(new URL(XYZ, import.meta.url))`) should be easy to add here: https://github.com/parcel-bundler/parcel/blob/cebbec73a5e8d2bf740c8464afb106c848ca3b22/packages/transformers/js/src/visitors/dependencies.js#L164-L193

**Comment by gkjohnson** [comment]
> Is there any official documentation for that?

As far as I can tell, not yet. Webpack 5 just released recently so it's a pretty new feature.

**Comment by mischnic** [comment]
This should also apply to the various worklets: https://github.com/parcel-bundler/parcel/issues/1093

**Comment by ProLoser** [comment]
So would the context be `service-worker`? or just `worker`?

**Comment by mischnic** [comment]
`worker`

(These two should behave the same
```js
const worker = new Worker( new URL( './worker.js', import.meta.url ) ); // this issue
const worker = new Worker( './worker.js' ); // works already
```
)

**Comment by devongovett** [comment]
We should possibly drop the second syntax (what we currently support). In the browser, relative urls resolve from the page url not the script, so parcel currently doesn't match.

**Comment by mischnic** [comment]
In library builds,
```js
new Worker(new URL("./worker.js", import.meta.url));
```
should become
```js
new Worker(new URL("./worker.af82942.js", import.meta.url));
```

**Comment by devongovett** [comment]
This has been supported for a while.
