### ISSUE TITLE
Question:Can Parcel be used to bundle in browser? 

### ISSUE THREAD

**Issue by mpkelly** [parcel-bundler/parcel#546]
Hi,

Can I use Parcel to bundle assets in the browser? I'd like to bundle code from an editor and display the results in the same browser window without touching the file system. If not supported out of the box, can you advise which files I could use as a starting point. I'm mainly interesting in bundling  React Typescript code.

Thanks 
Mike

**Comment by DeMoorJasper** [comment]
You might wanna have a look at the examples repo: https://github.com/parcel-bundler/examples
I'm pretty sure all u ask for in here is hot module reload and bundling, what Parcel does out of the box without any config

**Comment by mpkelly** [comment]
Hi @DeMoorJasper - thanks for replying. 

I've looked at that repo but it doesn't seem to answer my question. I'd like to be able to call Parcel through a JS API which can accept a root entry point and also bundle imports from other files, including dependencies from NPM. All this I would like to do in the browser memory. I would expect that Parcel will need me to provide it with an alternative way to get file data when loading imports, as by default it expects to find this data on the file system. So, basically, I want to use Parcel with a virtual file system. 

I will take a look over Parcel's source code myself later but a few pointers would be great.

Mike

**Comment by mqudsi** [comment]
You can always use an in-memory filesystem output directory as a temporary workaround, though that has obvious kernel call overhead. I suppose it depends on your performance requirements.
