### ISSUE TITLE
Alias is not followed by parcel

### ISSUE THREAD

**Issue by ra1u** [parcel-bundler/parcel#5463]
# 🐛 bug report

parcel does not respect "alias" field in package.json

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```json
 "alias": {
    "vue": "vue/dist/vue.esm.js"
  },
  "devDependencies": {
    "parcel": "^1.12.4",
  },
  "dependencies": {
    "vue": "^2.6.12",
  },
```

app.js
```app.js
import Vue from 'vue'
```

## 🤔 Expected Behavior

no error

## 😯 Current Behavior

error:
Cannot resolve dependency 'vue'

## 💁 Possible Solution

including packet `parcel-bundler` fix an issue

**Comment by DeMoorJasper** [comment]
Which parcel version are you using? (we have these questions in the template for a reason)

**Comment by ra1u** [comment]
I was using parcel 1.12.4

```json  
"devDependencies": {
    "parcel": "^1.12.4",
 },
```

I am now not sure that, that reported solution is the solution and reported bug can be reproduced that easily. 
We observed that at one point 

    yarn parcel build index.html

did work ok, but

   yarn parcel serve index.html

Resulted in reported error. 

I am currently unable to reproduce such state, as it seems to obtained only by certain series of steps, rather than from predefined state defined by project layout.

I will try to find more reliable way to get to this point.

**Comment by whisper-bye** [comment]
+1
parcel 2.0.0-beta.2

**Comment by mischnic** [comment]
This should be working now
