### ISSUE TITLE
Compiling @azure/storage-blob pkg with V2 results in error (V1 fine)

### ISSUE THREAD

**Issue by anavarro9731** [parcel-bundler/parcel#5465]
# 🐛 bug report

Compiling @azure/storage-blob with any Parcel 2 version, 
Then require a module from the package, and you get an error.
MS say parcel is supported in docs, and v1 works fine.

I'm not an expert but in the source there appears to be a something less than normal about the Require arrangement in the file that's failing, see attached images.

no babel config
no tsconfig 
no parcelrc
(although i tried the options in the for using tsc.exe without success)

To test just a single line "import { BlobServiceClient } from '@azure/storage-blob";" in index.js and it will throw.

Works fine on codesanbox as well https://codesandbox.io/s/intelligent-herschel-qm30h?file=/src/index.js

```js
{
{
  "name": "sample",
  "version": "1.0.0",
  "dependencies": {
    "@azure/storage-blob": "^12.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "parcel":"2.0.0-nightly.476"
  },
  "scripts": {
    "build": "parcel build ./index.html --public-url ./",
    "serve": "parcel serve ./index.html"
  }
}
}
```

## 🤔 Expected Behavior

should import without error

## 😯 Current Behavior

<img width="461" alt="blobstorage error2" src="https://user-images.githubusercontent.com/549572/102018111-11864180-3d63-11eb-9cae-53153646f0d6.PNG">

<img width="441" alt="blobstorage error" src="https://user-images.githubusercontent.com/549572/102018075-ca984c00-3d62-11eb-9a1d-ee65a0876cfb.PNG">

**Comment by mischnic** [comment]
Bundling
```
import { BlobServiceClient } from "@azure/storage-blob";
console.log(BlobServiceClient);
```
with your package.json works fine for me. Please provide a complete example.
