### ISSUE TITLE
JS imported css files are bundled in the wrong order

### ISSUE THREAD

**Issue by FaberoM** [parcel-bundler/parcel#5469]
# 🐛 bug report

I'm importing these two css and scss files in my apps index.js:
```js
import 'normalize.css';
import './styles/main.scss';
```

Although `normalize.css` is imported before `main.scss` it ends up to the bottom of final bundled .css file and overrides values set in `main.scss` due to how css works.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "test",
  "version": "1.0.0",
  "description": "desc",
  "main": "index.js",
  "scripts": {
    "start": "parcel serve ./src/index.html",
    "build": "parcel build ./src/index.html"
  },
  "devDependencies": {
    "parcel": "^2.0.0-beta.1",
    "sass": "^1.30.0"
  },
  "dependencies": {
    "normalize.css": "^8.0.1"
  }
}

```

## 🤔 Expected Behavior

The final bundled .css should look like this:
```
main.css (compiled)
normalize.css
```

## 😯 Current Behavior

But instead currently looks like this:
```
normalize.css
main.css (compiled)
```

## 💁 Possible Solution

This might be a false lead; But from what I tested, seems like parcel might currently sort .css files by filesize(?) The .css file that had fewest code seemed to be at the top of bundled .css file and the one that had most code was on the bottom. Converting the .scss file to normal .css didn't seem to help either, the order stayed the same.

## 🔦 Context

I was trying to use normalize.css with my app and build my own css(scss) on top, but due to css file import being out of order I couldn't do that.

## 💻 Code Sample

Have 2 or more css/scss imports inside index.js and try to build.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | 15.3.0
| npm/Yarn         | Yarn 1.22.10
| Operating System | MacOS Big Sur (11.0.1)

**Comment by mischnic** [comment]
Can you provide a reproduction? Works correctly for me

**Comment by FaberoM** [comment]
Sure thing! After some further testing this seems to affect only `parcel serve` and not `parcel build` so my initial reproduce steps were wrong.

Here is my new test project which you can clone yourself: https://github.com/FaberoM/parcel-bug

The end result should be link with red background. What I found out when using `parcel serve` it was blue (files loading in wrong order) and when building it was back to correct order. The `index.js` has some comments regarding which file gives what background color.

**Comment by mischnic** [comment]
I cloned your repo, ran `yarn && yarn start` and the link has a correct red background.

Also, you can test if latest nightly behaves differently for you? `yarn add -D parcel@nightly`
