### ISSUE TITLE
Recognize `new URL("./thing.png", import.meta.url)`

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5473]
# 🙋 feature request

As introduced by Webpack.

## 🤔 Expected Behavior

Behave like `import ... from "url:./thing.png"`.

## 💁 Possible Solution

Should be implemented here: https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/js/src/visitors/dependencies.js

## 🔦 Context

This isn't related to `new Worker(new URL(...))`: https://github.com/parcel-bundler/parcel/issues/5430, because we need to detect the environment context `web-worker` in that case.

**Comment by hsablonniere** [comment]
Hello @mischnic 😉

I’m not sure you will need help on this but I implemented this as a Rollup plugin so I would be glad to participate if necessary

* Explainer with some discussions https://gist.github.com/hsablonniere/ec5e70ca920093010493e556d50dba03
* The Rollup plugin https://github.com/modernweb-dev/web/blob/master/packages/rollup-plugin-import-meta-assets/src/rollup-plugin-import-meta-assets.js

**Comment by mischnic** [comment]
Thanks! I haven't looked into this further but I think we already have all the needed architecture and this is essentially an alias for `url:` imports.

**Comment by devongovett** [comment]
Should that always create a dependency or only when used in contexts that already create one (eg workers). What if you want to create a URL relative to the actual bundle as would happen today?

**Comment by mischnic** [comment]
If we go by the principle "executing the source should behave just like executing the Parcel output", it should always be processed.

**Comment by devongovett** [comment]
We'd need to change the dependency based on where it's used though in order for the correct context to be applied, which may be hard.

eg 

```js
let url = new URL("./worker.js", import.meta.url);
let worker = new Worker(url);
```

And what happens if the url is used in multiple places?

**Comment by mischnic** [comment]
My suggestion was:
1. recognize `new Worker(new URL(...))`: https://github.com/parcel-bundler/parcel/issues/5430 (and worklet...)
2. treat everything that's left as `url:` import (this issue)

Otherwise, there is no way to easily determine how it's used.

**Comment by ProLoser** [comment]
@devongovett are you still looking into this? Do you have a WIP?
