### ISSUE TITLE
Make sure that automatically generated names don't start with a dot

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5474]
# 🐛 bug report

In some situations, the automatically generated bundle name could start with a dot if some parent folder does as well...

Came up in https://github.com/parcel-bundler/parcel/issues/5472

## 🔦 Context

This here

https://github.com/parcel-bundler/parcel/blob/ed27891c355410c4e900976a9fd0fdcdc96b5f7e/packages/namers/default/src/DefaultNamer.js#L127-L128

could potentially create a file called starting with a `.` (which is usually hidden by the OS).

This should happen if you have the files `.src/index.html` (with `<script src="index.js"></script>`) and `.src/index.js` in your project and call `parcel2 build .src/index.html`

## Solution

Remove leading `.`?

**Comment by JessieFrance** [comment]
Hello. May I please work on this issue?

**Comment by DeMoorJasper** [comment]
@JessieFrance yes, feel free to work on this
