### ISSUE TITLE
Offer a way to overwrite project root

### ISSUE THREAD

**Issue by surma** [parcel-bundler/parcel#5476]
# 🐛 bug report

I am using [11ty](https://www.11ty.dev/) to generate a blog and then want to use parcel to “productionize” it (hash file names, minify etc etc). The idea is that I can just leave 11ty in watch mode to develop my blog and then run parcel on CI to productionize it.

Because the output has a lot of hierarchy (`/blog/my-blog-topic/index.html` is the blog post, but `/blog/index.html` is the listing of blog posts), I am using absolute URLs for a lot of assets, like my profile image (`/profile.jpg`) etc. In my setup, 11ty puts all its output into `.tmp`.

However, absolute URLs are resolved against the _project_ root. So for Parcel to find my profile image I’d have to use `/.tmp/profile.jpg` rather than `/profile.jpg`. But that makes the 11ty output itself unusable. 

It’d be nice to have a simple flag for `--project-root` or something along those lines. My workaround is currently to give `.tmp` it’s own `package.json` with the sole purpose of installing Parcel there, effectively setting the project root to `.tmp`.

**Comment by mischnic** [comment]
> However, absolute URLs are resolved against the project root

They should be resolved relative to the entry root (the longest common prefix of all entrypoints).

Changing the project root could also be problematic because files outside of that aren't watched for changes (at the moment). I think in your case, some source files might be outside of that?

**Comment by surma** [comment]
> They should be resolved relative to the entry root (the longest common prefix of all entrypoints).

Oooh interesting! I just retried, and it seems like it’s not just the longest common prefix of all entrypoints, but also the dist dir.

```
# This works perfectly!
$ npx parcel build --dist-dir ./dir ./index.html
# ...

# This fails
$ npx parcel build --dist-dir ./dir ./index.html
 Build failed.
@parcel/core: Failed to resolve '/index.83af0cbf.css' from './dir/index.html'
unknown: Cannot load file '../index.83af0cbf.css' in './dir'.
Did you mean ./index.83af0cbf.css?
Did you mean ./index.83af0cbf.css.map?
```

Maybe all that needs to be done is to exclude the `dist` dir from that prefix calculation?

**Comment by mischnic** [comment]
Oh, I misread you comment.

What I meant was that with these inputs files:
```
a.html
sub/b.html
```

you get:
`parcel build a.html` -> `dist/a.html`
`parcel build sub/b.html` -> `dist/b.html`
`parcel build a.html sub/b.html` -> `dist/a.html`, `dist/sub/b.html`

----

Changing the projectroot itself has some other sideeffects. The last resort would certainly be a custom resolver that rewrites absolute specifiers and then calls the default resolver...

**Comment by mischnic** [comment]
> custom resolver that rewrites absolute specifiers 

-> https://www.npmjs.com/package/@mischnic/parcel-resolver-root
