### ISSUE TITLE
How to handle social media headers?

### ISSUE THREAD

**Issue by surma** [parcel-bundler/parcel#5478]
# 🙋 feature request

For social networks like Facebook or Twitter, sites often have `<meta>` headers like these:

```html
<meta
  property="og:image"
  content="https://surma.dev/social.jpg"
/>
<meta
  name="twitter:image"
  content="https://surma.dev/social.jpg"
/>
```

Now, both Twitter and OpenGraph require that the value provided in these tags are absolute URLs, so I am wondering how I can make Parcel ingest the correct file, hash it, and put the right file into these `<meta>` tags.

Any ideas?

**Comment by mischnic** [comment]
```html
<meta property="og:image" content="img.png" />
<meta name="twitter:image" content="img.png" />
```
\+
`parcel build index.html --public-url 'https://surma.dev'`

does already work as expected. But there might be some unwanted side-effects of that public url setting

**Comment by surma** [comment]
Ah that is good to know. Although it does add the full URL to _every_ link and include now, which kinda destorys local development. That works for me, but I could see it not working for others. Gonna close this, tho.
