### ISSUE TITLE
Recognize `require` call with template literals (but no placeholders)

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5492]
# 🐛 bug report

```
require(`lodash`)
```
should behave just like `require("lodash")` but are currently ignored.

<br>

```
require(`./${thing}`)
```
should still be ignored.

## 💁 Possible Solution

This case should be normalized here:

https://github.com/parcel-bundler/parcel/blob/a4cf3e958ea1136b4829eb93615fba5328213471/packages/transformers/js/src/visitors/dependencies.js#L56-L61

and also normalized to `"lodash"`.

Add a test similar to this one: https://github.com/parcel-bundler/parcel/blob/46af2476ecb78921af21432f978d863fbffafd9d/packages/core/integration-tests/test/javascript.js#L24-L35

**Comment by alphabet-codes** [comment]
@mischnic I'd love to pick up this issue

**Comment by DeMoorJasper** [comment]
@alphabet-codes sure, feel free to work on this

**Comment by ognjenjevremovic** [comment]
Hey @DeMoorJasper is this issue still open and up for grabs?
This seems to me like a welcoming issue for first time contributors to the project.

May I have a chance to provide a MR for this issue?

Many thanks!

**Comment by mischnic** [comment]
@ognjenjevremovic Sure
