### ISSUE TITLE
Broken output for `delete` on an process.env property 

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5493]
# 🐛 bug report

Don't replace `delete process.env.SOMETHING` with `delete undefined;`

## 🤔 Expected Behavior

Remove the whole statement or replace with an empty statement.

## 😯 Current Behavior

`delete undefined;` is invalid in strict mode. This is even verified by terser.

## 💁 Possible Solution

`process.env.*` is inlined here: https://github.com/parcel-bundler/parcel/blob/a4cf3e958ea1136b4829eb93615fba5328213471/packages/transformers/js/src/visitors/process.js#L26

This special case is described by `t.isUnaryExpression(path.parent, {operator: 'delete', argument: node})`.

**Comment by alphabet-codes** [comment]
@mischnic I'd love to pick up this issue

**Comment by ticklepoke** [comment]
Does this problem still need a fix?
