### ISSUE TITLE
ESM output format fails with ESM and CJS imports to the same external module

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5496]
# 🐛 bug report

The ESM output format fails with ESM and CJS imports to the same module.

## 💻 Code Sample

```js
import { Buffer as Buffer1 } from "buffer";

const { Buffer: Buffer2 } = require("buffer");

console.log(Buffer1, Buffer2);
```
```
{
	"type": "module",
	"module": "lib.js",
	"dependencies": {
		"@babel/core": "^7.12.10",
	}
}
```

## 😯 Current Behavior

```js
import _buffer from "buffer";
var Buffer; // <---- is never assigned!
const { Buffer: $id$var$Buffer2 } = _buffer;
console.log(Buffer, $id$var$Buffer2);
```

## Possible solution

The dependency to `buffer` has `dep.meta.isCommonJS: true`. But this isn't completely true...

The ESM outputformat's `generateExternalImport` assumes that a commonjs dependency only does default imports (and exactly one).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 3f1935a5401692f5710e0e9b377390cfa0e0f261

**Comment by devongovett** [comment]
Seems to work now.
