### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by webular** [parcel-bundler/parcel#55]
Is there a way to define a proxy?  In webpack we are doing something like this: 

```
devServer: {
  proxy: {
   '/api*' :{
      target: 'http://localhost:3001/graphql',
      secure: false,
    },
}
```

[More details about webpack's devserver proxy here.](https://webpack.js.org/configuration/dev-server/#devserver-proxy)

**Comment by devongovett** [comment]
I don't really think this should be the responsibility of the bundler... Can you just enable CORS and hit localhost:3001 directly?

Alternatively, you could build your own small server with express and use parcel as a middleware.

```javascript
let Bundler = require('parcel-bundler');
let express = require('express');

let bundle = new Bundler('entry.html');
let app = express();

// define proxy routes here

app.use(bundle.middleware());
```

**Comment by tb** [comment]
@devongovett I always use [create-react-app proxy](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#proxying-api-requests-in-development) This allows me to use relative urls like `/api/endpoint` / `/graphql`. The same urls work then after deployment to production server.

**Comment by webular** [comment]
@tb Oh - thats exactly what I want.  Thx for the tip!

**Comment by jylin** [comment]
It's not the responsibility of the bundler, but it would be a very useful feature for the dev server. If your server is not in NodeJS (and you don't want to enable CORS), then without this you have to use some kind of post-processing to replace "locaholhost:PORT" with something else when deploying to production. It's much nicer to be able to use relative links and have the dev server have a config to proxy to the appropriate backend endpoint.

**Comment by chasegiunta** [comment]
For the dev-server, I think this would be useful for non-spa sites as well (php applications, etc). Where you proxy the app (`myphpsite.test`), but watch the assets and/or templates directory for changes. Templates directory changes would trigger full reloads, while asset changes trigger HMR (in a perfect world)

**Comment by samithaf** [comment]
Hey @webular , you can probably use **browser-sync** and **http-proxy-middleware** to achieve your end goal and it's relatively easy to set it up. E.g. 

 ```
import assign from 'lodash/assign';
import Bundler from 'parcel-bundler';
import serve from 'browser-sync';
import proxy from 'http-proxy-middleware';
import compress from 'compression';

const bundler = new Bundler('index.html');
 serve({
    port: process.env.PORT || 3000,
    open: false,
    server: { baseDir: 'dist', https: true },
    middleware: [
      proxy(`${envConfig.endpoint}/api`, assign({}, proxyConfig)),
      proxy(`${envConfig.endpoint}/auth`, assign({}, proxyConfig)),
      compress(),
      bundler.middleware()
    ],
  }); 
```

**Comment by albinotonnina** [comment]
An complete example with express
```
const proxy = require('http-proxy-middleware')
const Bundler = require('parcel-bundler')
const express = require('express')

let bundler = new Bundler('src/index.html')
let app = express()

app.use(
  '/api',
  proxy({
    target: 'http://localhost:3000'
  })
)

app.use(bundler.middleware())

app.listen(Number(process.env.PORT || 1234))

```

**Comment by albinotonnina** [comment]
@yiranlee 

```
const proxy = require('http-proxy-middleware')
const Bundler = require('parcel-bundler')
const express = require('express')

const bundler = new Bundler('src/index.html', {
  cache: false
})

const app = express()

app.use(
  '/api',
  proxy({
    target: 'http://localhost:3000'
  })
)

app.use(bundler.middleware())

app.listen(Number(process.env.PORT || 1234))
```

**Comment by larrybolt** [comment]
For those still needing more help, the socketio example chat app altered to bundle the client-side files:
https://github.com/larrybolt/chat-example/commit/3757a42dd0fef26b996946fb0696fa56b4cd7f02

**Comment by NullVoxPopuli** [comment]
@albinotonnina that's not working for me for some reason.
I'm running in a docker-environment.

my requests to localhost:9091/api/whatever still just return the parcel index.html

```js
import proxy from 'http-proxy-middleware';
import Bundler from 'parcel-bundler';
import express from 'express';

const bundler = new Bundler('src/index.html', {
  cache: false
});

const app = express();

app.use(
  '/api',
  proxy({
    target: `http://${process.env.API_HOST}`
  })
);

app.use(bundler.middleware());

app.listen(Number(process.env.PORT || 1234))
```

**Comment by albinotonnina** [comment]
Hi @NullVoxPopuli,
Don't know really.
To understand: `http://${process.env.API_HOST}` prints http://localhost:9091 ?

**Comment by ThaddeusJiang** [comment]
It would be a very useful feature for spa.

**Comment by l-hammer** [comment]
@albinotonnina  nice example~ but i want to set --open parameters in `new Bundle('src/index.html')`? like this:

```javascript
const bundler = new Bundler(proxypath, {
  open: true,
})
```
But this has no effect，how to do it? Thx~
