### ISSUE TITLE
File Monitoring Issue

### ISSUE THREAD

**Issue by goldenMetteyya** [parcel-bundler/parcel#550]
**Choose one:** is this a 🐛 bug report

I am using the last master ranch from GitHub 

Ive been having trouble where the filesytem on my mac wont recognize all file changes to notify parcel, it works for html and js file but not elm, i have investigated and i can see the notifications come through for js file but not elm and i have also checked if parcel is wathcing the elm file and it is

### 🤔 Expected Behavior

js file changes make a update happen but elm file changes should as well.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by devongovett** [comment]
This is an issue with the elm plugin. It would need to provide parcel with a list of files to watch. Looks like this is being worked on in https://github.com/ssuman/parcel-plugin-elm/pull/3
