### ISSUE TITLE
🐛 Importing two different modules results in them exporting identical object

### ISSUE THREAD

**Issue by yunyu** [parcel-bundler/parcel#551]
### 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc:
```js
{
    "presets": ["env"],
    "plugins": ["inferno"]
}
```

### 🤔 Expected Behavior

If I do the following:

```js
import Inferno from 'inferno';
import Component from 'inferno-component';
console.log(Inferno === Component);
```
I expect it to log `false` in the console.

### 😯 Current Behavior

Instead, it logs `true`. The same occurs if I reverse the ordering of the imports, and Component still doesn't export correctly (instead it exports what Inferno should export) even if I remove the `inferno` import. This does not happen with Rollup.

### 💁 Possible Solution

Not sure ;(

### 🔦 Context

I am trying to import `inferno` and `inferno-component` so I can use class components with my Inferno application. Unfortunately, they return the exact same object. I suspect this may be an issue with any two modules in which the name of one starts with the name of the other.

### 💻 Code Sample

https://github.com/vanderbilt-design-studio/site-overrides/blob/fecc54137c4e83f29ef2ab2cdb09b519e16de379/overrides.jsx

https://github.com/yunyu/parcel-duplicate-module-reprod

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.4.1
| Node             | 8.9.4
| npm/Yarn         | NPM
| Operating System | Windows 10 x64

**Comment by yunyu** [comment]
Here is a very minimal reproduction case:

https://github.com/yunyu/parcel-duplicate-module-reprod

**Comment by yunyu** [comment]
Would someone be able to look into this? I think this could be indicative of a deeper issue.

**Comment by DeMoorJasper** [comment]
I've taken a look at it, can confirm something might be off here, but the code that's being required looks quite identical here, not sure if this is a bug (can't look further into it atm)

**Comment by yunyu** [comment]
Thanks for verifying, if I do a require() without Parcel, the two modules return different types (Inferno returns an Object while Component returns a function):

```js
const Inferno = require('inferno');
const Component = require('inferno-component');

// Should print false
console.log(Inferno === Component);
// Should print object
console.log(typeof Inferno);
// Should print function
console.log(typeof Component);
```

**Comment by devongovett** [comment]
Not an issue in Parcel 2
