### ISSUE TITLE
Arrow function class fields transform `this` to `undefined`

### ISSUE THREAD

**Issue by maxjoehnk** [parcel-bundler/parcel#5510]
# 🐛 bug report

I'm not sure whether this is a parcel or a babel issue but given the following Code 
```typescript
class DrawingArea extends React.Component<...> {
  private setCanvas = (canvas) => {
    this.setState(state => ({ ...state, canvas }));
  }
}
```

the transpiled result tries to call `setState` on `undefined` like so:
```javascript
class DrawingArea extends _reactDefault.Component {
  setCanvas = canvas => {
    undefined.setState(state => ({ ...state, canvas }));
  };
}
```

This might be the same issue as [this](https://github.com/webpack/webpack/pull/6380).

I can fix this issue for prod builds with a custom browserslist configuration but it will still occur in development builds.

## 🎛 Configuration (.babelrc, package.json, cli command)
package.json:
```json
{
  "scripts": {
    "start": "parcel serve --hmr-port 1235 src/index.html",
    "build": "parcel build src/index.html --no-minify"
  },
  "devDependencies": {
    "@parcel/validator-typescript": "^2.0.0-nightly.488",
    "glob": "^7.1.6",
    "http-proxy-middleware": "^1.0.3",
    "parcel": "^2.0.0-nightly.486",
    "sass": "^1.26.5",
    "typescript": "^3.8.3"
  }
}
```

## 🤔 Expected Behavior

`this` should not be replaced with `undefined` in class fields as the scope is well defined (the class instance).

## 😯 Current Behavior

`this` is replaced with `undefined`.

## 💻 Code Sample

https://github.com/maxjoehnk/remote-party-games/tree/feature/broken-build/applications/web-client

The snippet above is from [this file](https://github.com/maxjoehnk/remote-party-games/blob/feature/broken-build/applications/web-client/src/app/game-widgets/drawing/drawing-area.component.tsx)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.486 |
| Node             | v15.4.0 |
| npm/Yarn         | yarn 1.22.10 |
| Operating System | Linux |

**Comment by mischnic** [comment]
Related code: https://github.com/parcel-bundler/parcel/blob/f89e5ef87fcb58e6131475b5218f188cc231a1d9/packages/transformers/js/src/visitors/modules.js#L197-L207

**Comment by rinick** [comment]
reverting to 2.0.0-nightly.481 resolved this issue

**Comment by aminya** [comment]
**Out of the topic of this issue** but my recommendation is to not use anonymous functions when the function is named. Arrow functions are meant to be passed to other functions when they are unnamed. When you assign an anonymous function to a named variable, you have already named it, so this is not considered a good idea.

Also, from the performance perspective, doing this may prevent the browser engine to inline these because the arrow functions are usually calculated **during runtime**.

**Comment by maxjoehnk** [comment]
> **Out of the topic of this issue** but my recommendation is to not use anonymous functions when the function is named. Arrow functions are meant to be passed to other functions when they are unnamed. When you assign an anonymous function to a named variable, you have already named it, so this is not considered a good idea.
> 
> Also, from the performance perspective, doing this may prevent the browser engine to inline the calls to these lambdas because the arrow functions are usually calculated **during runtime**. 
> 
> <details>
> <summary>Benchmarks</summary>
> 
> About 50% slower than a free function and 10% slower than a method function. You may not notice it in a simple function that calls `this.setState` which probably will not be inlined anyway, but when inlining is important it can have a huge effect. 
> 
> ![image](https://user-images.githubusercontent.com/16418197/103407457-5b717480-4b24-11eb-9317-c33c76a6df8b.png)
> https://jsbench.me/g4kjcq9j3s/1
> 
> cc: @rinick @maxjoehnk @mischnic 
> 
> </details>

Interesting. I'm actually only using this kind of function when I'm passing it out of the current scope. E.g. in my example this method is part of a context object which is used in other components and I prefer this syntax to the bind calls in the constructor.
But maybe one could write a transform which transforms arrow functions to method functions with `bind(this)`.

**Comment by aminya** [comment]
> Interesting. I'm actually only using this kind of function when I'm passing it out of the current scope. E.g. in my example, this method is part of a context object which is used in other components and I prefer this syntax to the bind calls in the constructor.

If you bind it in a constructor, then there is nothing holding you back from converting it to a class method (I don't have a full context). This function seems simple enough to not have much performance difference. 

Firefox docs have a good explanation of some of the performance issues of passing lambdas directly to `addEventListener` instead of binding.

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Memory_issues


> But maybe one could write a transform which transforms arrow functions to method functions with bind(this).

There is a babel plugin for that 😉: https://babeljs.io/docs/en/babel-plugin-transform-arrow-functions
