### ISSUE TITLE
🐛 how to prohibit package background-image in css flies?

### ISSUE THREAD

**Issue by DimaLiLongJi** [parcel-bundler/parcel#552]
1. I am using cdn to store my image, so in my css files url is an absolute path like
 `background-image: url('/images/logo@2x.png');`. 

But when packaging , it will show me an error
 `Cannot resolve dependency './../../../../../../../../../../images/xxxx.png' at '/images/xxx.png'`

### 🎛 Configuration

 My cli command is 
``` sh
rm -rf .cache &&

NODE_ENV=development parcel watch public/app/modules/app/pc/index.js -d public/test &

NODE_ENV=development parcel watch public/app/modules/app/pc/style.js --public-url /public -d public/test &

nodemon bin/www
```

### 🤔 Expected Behavior

Use some cli commond to stop package image in css flies.

### 🌍 My Environment

| Software             | Version(s) |
| ---------------- | ---------- |
| Parcel                |  ^1.4.1
| Node                 |  v6.11.2
| npm/Yarn          |  npm 5.6.0
| Operating System |  macOS

**Comment by DeMoorJasper** [comment]
It resolves all paths, in the future it might also resolve absolute paths (see #290).
But i suppose u want it to ignore it and take it from the cdn? I'm wondering how this could be tackled in a non-hacky way. I'll flag this as RFC

**Comment by DimaLiLongJi** [comment]
Sorry, I forgot to show my structure.
```
myApp
    - /public
        - /images
        - /styles
```
But in my styles files, they are `background-image: url('/images/logo@2x.png');`
My root path isn't  `public`. So i want to ignore package image in CSS or set a root path for image in  cli command .

**Comment by devongovett** [comment]
You should use a relative path rather than an absolute one. Parcel will rewrite it to a URL on your CDN for you. `background-image: url('../images/logo@2x.png')` (relative from `styles`).
