### ISSUE TITLE
HMR Error when modifying inline assets in HTML

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5523]
# 🐛 bug report

HMR updates for inline assets in HTML aren't applied because of a JS error.

## 🤔 Expected Behavior

HMR works / the page is automatically reloaded.

## 😯 Current Behavior

```
Uncaught SyntaxError: Unexpected token '<'
    at new Function (<anonymous>)
    at hmrApply ((index):390)
    at (index):225
    at Array.forEach (<anonymous>)
    at WebSocket.ws.onmessage ((index):224)
```

## 💁 Possible Solution

Currently, three changed assets are sent to the hmr runtime (HTML itself, the inline CSS and the inline JS).

This change would prevent the syntax error
```diff
diff --git packages/reporters/dev-server/src/HMRServer.js packages/reporters/dev-server/src/HMRServer.js
index a65d84a3b..f4d38b8f1 100644
--- packages/reporters/dev-server/src/HMRServer.js
+++ packages/reporters/dev-server/src/HMRServer.js
@@ -99,7 +99,9 @@ export default class HMRServer {
   async emitUpdate(event: BuildSuccessEvent) {
     this.unresolvedError = null;

-    let changedAssets = Array.from(event.changedAssets.values());
+    let changedAssets = Array.from(event.changedAssets.values()).filter(
+      a => a.type === 'css' || a.type === 'js',
+    );
     if (changedAssets.length === 0) return;

     let queue = new PromiseQueue({maxConcurrent: FS_CONCURRENCY});
```

This makes HMR for the JS work, but CSS updates aren't applied (and the page isn't reloaded either) because the approach to reload CSS by invalidating the cache for `<link href=` tags in the page doesn't work for inline CSS.
https://github.com/parcel-bundler/parcel/blob/d374dbe60ef4372df6bc13bed451c2446630d82c/packages/runtimes/hmr/src/loaders/hmr-runtime.js#L200-L227

Either we fallback to reloading the page in that case, or we find a way to update the inline styles.

## 💻 Code Sample

```js
<!DOCTYPE html>
<html>
	<head>
		<title></title>
		<style>
			div {
				width: 100px;
				height: 100px;
				background: blue;
			}
		</style>
		<script>
			console.log("Hello inline");
		</script>
	</head>
	<body>
		<div></div>
	</body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | d374dbe60ef4372df6bc13bed451c2446630d82c

**Comment by faergeek** [comment]
May be it would make sense to not send updates for inline assets (`isInline: true`) to hmr client? As a user I would expect that if I edit an html, it can't be hot-reloaded reliably and will result in full page reload.

**Comment by mischnic** [comment]
We should probably do that at least to prevent the error. But ideally only the HTML page that was changed would reload, so somehow we'd have to compare the HTML asset that was sent to the hmr client runtime with the current page...

**Comment by devongovett** [comment]
I think this should be fixed now? This only handles JS and CSS changes, and all others cause the page to reload.

https://github.com/parcel-bundler/parcel/blob/946b1419d059c79d85be36b91b178a9b51708af1/packages/runtimes/hmr/src/loaders/hmr-runtime.js#L103-L109
