### ISSUE TITLE
@parcel/optimizer-terser: Unexpected token: operator (*=)

### ISSUE THREAD

**Issue by aminya** [parcel-bundler/parcel#5531]
# 🐛 bug report

Parcel optimizer parser breaks when it tries to parse the code. Here is the link for the reproduction:
https://github.com/atom-minimap/minimap/tree/parcel
```js
❯ npm install

> npm run build

> cross-env NODE_ENV=production parcel build --target main lib/main.js

× Build failed.
@parcel/optimizer-terser: Unexpected token: operator (*=)
C:\Users\aminy\@minimap\minimap\lib\mixins\plugin-management.js:22:0
  21 |
> 22 | // Initialize the properties for plugin management.
>    | ^ Unexpected token: operator (*=)
  23 |
  24 | /**
It's likely that Terser doesn't support this syntax yet.
npm ERR! code 1
npm ERR! path C:\Users\aminy\@minimap\minimap
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c cross-env NODE_ENV=production parcel build --target main lib/main.js

```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
  "targets": {
    "main": {
      "context": "node",
      "engines": {
        "node": ">=12.x"
      },
      "includeNodeModules": {
        "atom": false,
        "electron": false
      },
      "outputFormat": "commonjs",
      "isLibrary": true
    }
  },
```

## 🤔 Expected Behavior

Parse and optimize the code

## 😯 Current Behavior

Fails to parse and optimize

## 🔦 Context

Running `npm run dev` works without issues

## 💻 Code Sample

https://github.com/atom-minimap/minimap/tree/parcel

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.0-nightly.490
| Node             | 15.5.0
| npm/Yarn         | 6.14.8
| Operating System | Win 10

https://github.com/atom-minimap/minimap/pull/736

**Comment by aminya** [comment]
Not sure why, but this was fixed by moving one of my functions to the main entry of the package. The function returns `exports` which might be the reason it breaks the terser.

This is the function:
```js
export function provideMinimapServiceV1 () { return exports }
```

This is the commit that fixed the issue: 
https://github.com/atom-minimap/minimap/pull/736/commits/a7b88b59eec30c63f5d46201a890b91feeeef4ba#diff-7934bf411fea192ad8cd69e0a12911648a2842cb0f2409a8fb67b41b7069d757R357

**Comment by aminya** [comment]
I faced this issue in some other project!

https://github.com/aminya/solid-simple-table/runs/1610698172#step:4:73

**Comment by DeMoorJasper** [comment]
Maybe this is a scope-hoisting bug? @mischnic

**Comment by mischnic** [comment]
Yes, I ran into this as well some time ago. I thought I had opened an issue already...

**Comment by mischnic** [comment]
This is still a Parcel bug, but I would still recommend not mixing CJS and ESM syntax, you can import the file itself to get the namespace object, so instead of
```js
export function provideMinimapServiceV1() {
  return exports;
}
```
do
```js
import * as ns from "./plugin-management.js"; // the name of this file
export function provideMinimapServiceV1() {
  return ns;
}
```

<br>

I think the second case you posted has a different cause.

**Comment by aminya** [comment]
@mischnic Thanks for the information. This codebase had been written in the old times of CJS, and that's why we had this function. Unfortunately, we cannot just remove it because of backward compatibility. 

Is there an ES way to access the exports of the current file? Maybe I have to list the exports manually! 

```
export function provideMinimapServiceV1() {
  return {...ns, ...other_exports};
}
```

**Comment by mischnic** [comment]
> Is there an ES way to access the exports of the current file?

You don't need to list them. `ns` in my example is exactly the same as `exports`: https://codesandbox.io/s/trusting-dhawan-0zwq5?file=/src/index.js

**Comment by aminya** [comment]
@mischnic Oh, that's neat. I didn't notice that you're importing a module to itself 😄.

**Comment by mischnic** [comment]
Should be fixed with https://github.com/parcel-bundler/parcel/pull/4815

**Comment by ProLoser** [comment]
Parcel doesn't seem to support `?.` but I think it's supported in evergreen.

**Comment by mischnic** [comment]
You might need to upgrade Terser.

**Comment by ProLoser** [comment]
@mischnic Yeah I think upgrading my nightly fixed it, thanks!

**Comment by DwinaTech** [comment]
If you are still have the issue and you are using `styled-component` then this is the fix I got it works.
Add `babel-plugin-styled-components` to babelrc plugins and package.js dependencies.
```
{
  "plugins": [
    "babel-plugin-styled-components"
  ]
}
```
