### ISSUE TITLE
Cannot import less or styl in TypeScript files (Cannot find module 'less')

### ISSUE THREAD

**Issue by aminya** [parcel-bundler/parcel#5532]
# 🐛 bug report

I am trying to import a less or styl file, but although the documentation says they are supported out of the box, the plugin throws an error:

https://github.com/aminya/solid-simple-table/tree/less
```js
@parcel/transformer-less: Cannot find module 'less' from 'C:solid-tablesrc'
Error: Cannot find module 'less' from 'C:\\solid-table\src'
    at C:\\solid-table\node_modules\resolve\lib\async.js:116:35
    at processDirs (C:\\solid-table\node_modules\resolve\lib\async.js:269:39)
    at isdir (C:\\solid-table\node_modules\resolve\lib\async.js:276:32)
    at isDirectory (C:\\solid-table\node_modules\@parcel\utils\lib\resolve.js:92:9)
```

Also the printing of the paths seems to be broken for Windows (`'C:solid-tablesrc'`). 

## 🎛 Configuration (.babelrc, package.json, cli command)

babel
```json
{
  "presets": ["babel-preset-solid",  "@babel/preset-typescript", "@parcel/babel-preset-env"],
  "plugins": ["@parcel/babel-plugin-transform-runtime"]
}
```

package.json:
```json
  "main": "dist/SimpleTable.js",
  "module": "dist/SimpleTable.module.js",
  "scripts": {
    "dev": "cross-env NODE_ENV=development parcel watch src/SimpleTable.tsx",
    "build": "cross-env NODE_ENV=production parcel build src/SimpleTable.tsx"
  }
  "targets": {
    "main": {
      "context": "browser",
      "engines": {
        "browsers": "> 0.25%"
      },
      "includeNodeModules": true,
      "isLibrary": true
    },
    "module": {
      "context": "browser",
      "engines": {
        "browsers": "Chrome 76"
      },
      "includeNodeModules": false,
      "isLibrary": true
    }
  }
```

## 🤔 Expected Behavior

Transform and import less file

## 😯 Current Behavior

Throws an error

## 💁 Possible Solution
```
npm install --save-dev less
```

## 💻 Code Sample
https://github.com/aminya/solid-simple-table/tree/less

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.0-nightly.490
| Node             | 15.5.0
| npm/Yarn         | 6.14.8
| Operating System | Win 10

**Comment by mischnic** [comment]
Are you running `parcel build`? Autoinstall is disabled in that case, so you'll have to add it yourself

**Comment by aminya** [comment]
Yes, I use `parcel build`. Why should Auto install be disabled? This seems very inconsistent with the documentation.

**Comment by mischnic** [comment]
> Why should Auto install be disabled 

This was changed in https://github.com/parcel-bundler/parcel/pull/4907. @DeMoorJasper ?

**Comment by DeMoorJasper** [comment]
@mischnic It's only in production mode I think? Because of reproducible builds in CI

**Comment by mischnic** [comment]
But `parcel build` = production mode.

We should probably change the message if autoinstall is disabled to rather be "it's needed, please install this yourself because autoinstall is disabled".

**Comment by aminya** [comment]
Is there an option/flag to enable auto install back? I don't like this default option. 


If someone is supposed to install a dependency for building then what is the benefit of Autoinstall anyway?

**Comment by mischnic** [comment]
> Is there an option/flag to enable auto-install back?

At the moment, no. But it should be easy to add

https://github.com/parcel-bundler/parcel/blob/e6a2a6312a472e70c353b3de9978b4f2a2b3406f/packages/core/parcel/src/cli.js#L342

> Parcel 2-nightly.89 means Less 4.0.0

For Less, it's always the latest version. This is why it's important to lock the version by adding it to the project's dependencies.

https://github.com/parcel-bundler/parcel/blob/e6a2a6312a472e70c353b3de9978b4f2a2b3406f/packages/transformers/less/src/LessTransformer.js#L32-L34

> If auto-install always installs the latest package, then we have a problem here.

There are two reasons we install packages into the project instead of just adding more dependencies to Parcel itself:
1. you don't need to install less/vue/elm/typescript if you're not actually using them
2. You can specify the version you want to use (this is more of a problem with Typescript than Less)

**Comment by aminya** [comment]
> There are two reasons we install packages into the project instead of just adding more dependencies to Parcel itself:

It should not be hard to maintain a `autoinstall-dependencies.json` file and store the versions in that file, and then install the versions specified in that file.

Maybe I should open another issue for that. Thoughts?

**Comment by devongovett** [comment]
IMO auto install is a convenience for fast development iteration. It is not something that should be relied on for production builds, where consistency of versions is more important. When using auto install in development, the installed package should already be added to a yarn.lock or package-lock.json depending on your package manager. Then, when doing production builds, you will get a consistent version. I'm not sure I see the need for auto install in production, and either way I don't think it's a good idea.

**Comment by aminya** [comment]
If the version is locked in `autoinstall-dependencies.json` (which itself is locked with Parcel's version), all of these issues are fixed.

**Comment by devongovett** [comment]
Why do we need our own lock file? What would that provide that yarn.lock/package-lock.json doesn't provide already?

**Comment by aminya** [comment]
It is not a lock file, it is just a list of dependencies that `@parcel/autoinstall` uses (rather always using the last version).

autoinstall-dependencies.json
```
{
	"less": "4.0.0"
}
```

Then in a code:
```
// installing something reads the versions from a file:

const autoInstallDependencies = require("./autoinstall-dependencies.json")
const vresionToInstall = autoInstallDependencies[packageName]
```

**Comment by devongovett** [comment]
Isn't that the same as declaring them in package.json?

**Comment by avalanche1** [comment]
I would add that 
```
@parcel/transformer-stylus: Could not resolve module "stylus" from ".../src/entry/popup"
Autoinstall is disabled, please install this package manually and restart Parcel.
```
message is misleading; sometimes.
It took me some time to figure out that Parcel wanted not a transformer installed, but the 'stylus' package itself.
Not very obvious.

I propose to change the error msg to:
`Autoinstall is disabled for 'build' command; please install "`stylus`" package manually and restart Parcel.`

**Comment by aminya** [comment]
I think autoinstall now works in the production builds too.
