### ISSUE TITLE
Unexpected error with state={} in react class component

### ISSUE THREAD

**Issue by tnrich** [parcel-bundler/parcel#554]
Hey there,

I'm getting the following error: 
```
/Users/tnrich/Sites/treeview/Comp.js:10:7: Unexpected token (10:7)                     elDigestEnzymes });
> 10 |   state={
     |        ^
```

from the following piece of code

```js
export default class Ladder extends React.Component {
  state={
    highlightedFragment: undefined 
  }
```

The following code works and does the same thing, but I'd like to be able to do the top version. 
```
export default class Ladder extends React.Component {
  // constructor(props) {
  //   super(props);
  //   this.state = { highlightedFragment: undefined };
  // }
```

Does anyone know which babel transform I need to enable to get this to work? Thanks!

**Comment by DimaLiLongJi** [comment]
I think you should use `super()` in `constructor() {}` before  you use `this` when u  extend  a class.
In react docs, it's 
```
 constructor(props) {
    super(props);
    this.state = {date: new Date()};
  }
```

**Comment by devongovett** [comment]
https://babeljs.io/docs/plugins/transform-class-properties/

**Comment by silvestrevivo** [comment]
@devongovett thanks man!!! Problem resolved!!!

**Comment by antonrud** [comment]
@devongovett thx for the link!

However the main problem for me was my webpack config. Just deleted Babel options from _webpack.config.js_ and used only _.babelrc_ configuration instead. 

**webpack.config.js before**
```javascript
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /(node_modules|bower_components)/,
        loader: 'babel-loader',
        options: {presets: ['env', 'react']}  //bad line here
      },
...
```

**webpack.config.js after**
```javascript
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /(node_modules|bower_components)/,
        loader: 'babel-loader'
      },
...
```

**.babelrc**
```javascript
{
  "presets": [
    "env",
    "react"
  ],
  "plugins": [
    "transform-class-properties"
  ]
}

```

**Comment by vcasasc** [comment]
I have the same problem but with the Aribnb linter...
