### ISSUE TITLE
Parcel 2 fails when node_modules is a symlink

### ISSUE THREAD

**Issue by Dreamsorcerer** [parcel-bundler/parcel#5543]
`npm install` successfully installs the modules into the symlinked directory, but when building it doesn't seem to be able to search in the symlink.

package.json:
```
{
  "description": "Open Layers ES6 module",
  "license": "BSD-2-Clause",
  "repository": "github:openlayers/ol-parcel-es6",
  "main": "../teslaclub_app/static/js/ol.js",
  "scripts": {
    "preinstall": "mkdir -p ../node_modules;ln -fs ../node_modules node_modules",
    "build": "parcel build index.js"
  },
  "browserslist": [
    "supports custom-elementsv1 and supports es6-module-dynamic-import and supports es6-class and supports replace-all and supports shadowdomv1"
  ],
  "targets": {
    "main": {
      "includeNodeModules": true,
      "minify": false,
      "outputFormat": "esmodule"
    }
  },
  "dependencies": {
    "ol": "^6"
  },
  "devDependencies": {
    "parcel": "2.0.0-nightly.476"
  }
}
```

index.js:
```
export {Feature, Map, View} from 'ol';
export {Point} from 'ol/geom';
export {Tile as TileLayer, Vector as VectorLayer} from 'ol/layer';
export {fromLonLat} from 'ol/proj';
export {OSM, Vector} from 'ol/source';
export {Style, RegularShape, Fill, Stroke} from 'ol/style';
```

Error:
```
> npm install
[...]
added 1009 packages from 812 contributors and audited 1009 packages in 31.036s

143 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> npm run build
> @ build /home/ubuntu/hacking/teslaclub/mypy/openlayers
> parcel build index.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'v8-compile-cache'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ubuntu/hacking/teslaclub/.node_modules/parcel/lib/cli.js:125:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `parcel build index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by mischnic** [comment]
This seems to work on macOS. Could try adding a JS file in the same folder as `index.js`
```
require("v8-compile-cache");

console.log("hello");
```
and try running that with Node? Does that work for you?

**Comment by Dreamsorcerer** [comment]
I've added a file, but I'm not sure exactly what you want me to run?

I'm really not familiar with npm, what I've shown above is the complete npm project I am using (the built file is then imported into vanilla JS).

Running on Ubuntu (although I'd have thought that macOS would behave the same regarding symlinks).

**Comment by mischnic** [comment]
When in that project, run these two commands:
```
echo 'require("v8-compile-cache");\nconsole.log("hello");' > x.js
node x.js
```
Does it print `hello` or `Cannot find module 'v8-compile-cache'`?

**Comment by Dreamsorcerer** [comment]
Yes, that prints `hello`.

**Comment by mischnic** [comment]
I've tried it in a Ubuntu VM with Node 14.15.3. Which Node version are you using? That would also have been in the issue template...

**Comment by Dreamsorcerer** [comment]
Hmm, it's the apt installed version in Ubuntu 20.04. Seems to be v10.19.0. I'll see if I can upgrade it.

**Comment by mischnic** [comment]
Ubuntu 20.04.1 and Node v10.19.0 works in my VM

**Comment by Dreamsorcerer** [comment]
And you're just running:
```
npm install
npm run build
```
on the files in the description?

I got a slightly different error this time:
```
> npm run build
> @ build /home/ubuntu/hacking/teslaclub/mypy/openlayers
> parcel build index.js

🚨 Build failed.
Error: Cannot find module '@babel/core' from '/home/ubuntu/hacking/teslaclub/mypy/openlayers'
Error: Cannot find module '@babel/core' from '/home/ubuntu/hacking/teslaclub/mypy/openlayers'
    at /home/ubuntu/hacking/teslaclub/.node_modules/parcel/node_modules/resolve/lib/async.js:116:35
    at processDirs (/home/ubuntu/hacking/teslaclub/.node_modules/parcel/node_modules/resolve/lib/async.js:269:39)
    at isdir (/home/ubuntu/hacking/teslaclub/.node_modules/parcel/node_modules/resolve/lib/async.js:276:32)
    at isDirectory (/home/ubuntu/hacking/teslaclub/.node_modules/parcel/node_modules/@parcel/utils/lib/resolve.js:92:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `parcel build index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-12-29T23_51_48_273Z-debug.log
```

**Comment by mischnic** [comment]
> on the files in the description?

Yes

**Comment by Dreamsorcerer** [comment]
I've tried to look at the code, but in most places if I add a `console.log()` then it completely breaks with `Maximum call stack size exceeded`. I did manage to log the catch in `node_modules/parcel/node_modules/@parcel/utils/lib/resolve.js:92`. The last log was:
`Error: ENOENT: no such file or directory, stat '/home/ubuntu/hacking/teslaclub/.node_modules/parcel/node_modules/@parcel/node_modules/@parcel'`
Which is accurate, as it seems to be looking for a recursive directory that doesn't exist.

Not really sure how else I can debug the issue.

**Comment by mischnic** [comment]
The call stack error should go away if you set this to false:
https://github.com/parcel-bundler/parcel/blob/67aefd83f8a32813aa86c904952d6ceb63eb235c/packages/core/parcel/src/cli.js#L203

**Comment by Dreamsorcerer** [comment]
Ah, I've realised the slight mistake I made. I changed the preinstall script to symlink to '.node_modules', which causes it to fail. Seems that if you keep the `node_modules` name exactly, then it works. Which presumably means that it's still not following the symlink, but just finding the alternative folder in a parent directory. If you rename the linked directory, then it fails.

**Comment by mischnic** [comment]
Do you know of other tools that support this configuration? I'm getting `Error: Cannot find module 'v8-compile-cache'` now when renaming the symlink target folder to `nm`. But this seems to be caused by Node itself

**Comment by Dreamsorcerer** [comment]
My thought was that it was Parcel, as it didn't error until it runs parcel build. But, now I'm not so sure. I guess I can keep the `node_modules` name if there's no easy fix otherwise.
