### ISSUE TITLE
Scope hoisting fails with non-ASCII identifiers

### ISSUE THREAD

**Issue by skipjack** [parcel-bundler/parcel#5547]
Love what you guys are doing here, this is the first serious painpoint I've hit with parcel. When using `2.0.0-beta.1`, `parcel serve` is working great but `parcel build` yields the following error...

![image](https://user-images.githubusercontent.com/8988697/103372777-f9bbf680-4aa0-11eb-8dec-195408d0505e.png)

After some digging, I found babel/babel#8617 which seems to be related. However, when updating that line locally to work around the babel issue...

``` diff
-   if (duplicate) {
+   if (duplicate && this.hub) {
      throw this.hub.buildError(id, `Duplicate declaration "${name}"`, TypeError);
    }
```

Then I get a new error from `@parcel/optimizer-terser` which leads me to believe that `@babel/traverse` was correctly finding a duplicate declaration...

![image](https://user-images.githubusercontent.com/8988697/103373159-2d4b5080-4aa2-11eb-9dbf-2ec97b495f43.png)

I created [this repository][1] to demonstrate the issue. Also, here's the details on my environment...

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | 14.15.2
| npm        | 6.14.9
| Operating System | macOS 10.15.7

[1]: https://github.com/skipjack/parcel-build-bug

**Comment by mischnic** [comment]
This is caused by the linked Babel bug.

Doing this in Parcel
```diff
diff --git packages/shared/scope-hoisting/src/utils.js packages/shared/scope-hoisting/src/utils.js
index e01f6f5ea..f73dd2d5a 100644
--- packages/shared/scope-hoisting/src/utils.js
+++ packages/shared/scope-hoisting/src/utils.js
@@ -32,16 +32,7 @@ export function getName(
   ...rest: Array<string>
 ): string {
   return t.toIdentifier(
-    '$' +
-      asset.id +
-      '$' +
-      type +
-      (rest.length
-        ? '$' +
-          rest
-            .map(name => (name === 'default' ? name : t.toIdentifier(name)))
-            .join('$')
-        : ''),
+    '$' + asset.id + '$' + type + (rest.length ? '$' + rest.join('$') : ''),
   );
 }
```


But this case would still be broken with the same error you got:
```js
const ɵ2 = 1; // becomes '$...$var$2'
const ɵ3 = 2; // becomes '$...$var$3'
const ꝍ2 = 3; // becomes '$...$var$2' !!!
const ꝍ3 = 4; // becomes '$...$var$3' !!!

console.log(ɵ2, ɵ3, ꝍ2, ꝍ3);
```

**Comment by skipjack** [comment]
Thanks for the detailed explanation and jumping on this so quickly @mischnic! I’ll keep that repo up until these issues are closed. Lmk if there’s anything else I can do to help.

If you (or anyone else) have any ideas for a short term workaround, please share.

**Comment by mischnic** [comment]
`--no-scope-hoist` but there are of course big downsides with that.

Maybe renaming these non-ASCII bindings in https://unpkg.com/browse/@angular/core@11.0.5/fesm2015/core.js (and using `patch-package`)?
