### ISSUE TITLE
parcel 2: @parcel/transformer-js/src/esmodule-helpers.js is not being transpiled correctly when building for IE11

### ISSUE THREAD

**Issue by danieltroger** [parcel-bundler/parcel#5555]
# 🐛 bug report

Parcel includes an internal file when building for IE11 (@parcel/transformer-js/src/esmodule-helpers.js), but that file is not transpiled / using too new syntax and makes the whole output script fail.

The error is the following: `SCRIPT1028: Expected identifier, string or number`

This gets triggered as soon as anything with a promise is used, i.e.

```
main().then(e => console.log("main returned", e))
async function main(){
  return "HI IE11"
}
```

The problem is that IE11 doesn't understand this (quoting from @parcel/transformer-js/src/esmodule-helpers.js):
```
  get() {
        return source[key];
      },
 ```
 
 It would only understad this:
 ```
 get: function(){
   return source[key];
}
```

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json:

```js
{
  "ie11": "dist/ie11.js",
  "scripts": {
    "build": "parcel build src/main.ts --no-scope-hoist --log-level verbose --detailed-report 100 --no-minify --target ie11"
  },
  "browserslist": [
    "IE 11"
  ],
  "targets": {
    "ie11": {
      "engines": {
        "browsers": "ie 11"
      }
    }
  },
  "devDependencies": {
    "@babel/cli": "latest",
    "@babel/core": "latest",
    "@babel/preset-typescript": "latest",
    "@parcel/babel-plugin-transform-runtime": "latest",
    "@parcel/babel-preset-env": "latest",
    "parcel": "nightly",
    "terser": "latest"
  },
  "dependencies": {
    "@babel/runtime": "latest",
    "@babel/runtime-corejs3": "latest",
    "dotenv-cli": "latest"
  }
}
```

.babelrc:
```js
{
  "presets": ["@babel/preset-typescript", "@parcel/babel-preset-env"],
  "plugins": ["@parcel/babel-plugin-transform-runtime"]
}
```

cli command:
```
npm run build
```

## 🤔 Expected Behavior

The console should log `main returned HI IE11` when running the script instead of an error.

## 😯 Current Behavior

`SCRIPT1028: Expected identifier, string or number`

## 💁 Possible Solution

Transpiling everything correctly

## 🔦 Context

I was trying to compile my script for IE11 and now I will have to create something which switches to parcel 1 when I want to compile for IE11 :(

## 💻 Code Sample

[parcel-bug-repro.zip](https://github.com/parcel-bundler/parcel/files/5757137/parcel-bug-repro.zip)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.496+67aefd83 |
| Node             | v15.3.0 |
| npm/Yarn         | npm 7.3.0 |
| Operating System | macOS High Sierra 10.13.6 |

**Comment by danieltroger** [comment]
# Another issue

Not sure if I should open a second one, as you can use the same [**reproduction repository**](https://github.com/parcel-bundler/parcel/files/5757137/parcel-bug-repro.zip)

When building with scope hoisting (remove `--no-scope-hoist` from package.json) I get this error in IE11: `SCRIPT5007: Unable to get property 'mark' of undefined or null reference`

The error occurs on line 2 of this function:
```
function $0c9fdb84d80b31c16fbd69cc9b5f0571$var$_main() {
    $0c9fdb84d80b31c16fbd69cc9b5f0571$var$_main = $7271ab7ce4e339b40e30c407c9dac173$$interop$default( /*#__PURE__*/$f16c305f91df734ac9325a5601201c64$$interop$default.mark(function _callee() {
      return $f16c305f91df734ac9325a5601201c64$$interop$default.wrap(function _callee$(_context) {
        while (1) {
          switch (_context.prev = _context.next) {
            case 0:
              return _context.abrupt("return", "HI IE11");

            case 1:
            case "end":
              return _context.stop();
          }
        }
      }, _callee);
    }));
    return $0c9fdb84d80b31c16fbd69cc9b5f0571$var$_main.apply(this, arguments);
  }
})();
```

**Comment by mischnic** [comment]
Re issue 1: we can simply do make two changes regarding `get`: https://github.com/parcel-bundler/parcel/pull/5556
But I also needed to use this babelrc
```
{
	"presets": ["@parcel/babel-preset-env"],
	"plugins": [["@parcel/babel-plugin-transform-runtime", { "corejs": 3 }]]
}
```
because of https://github.com/babel/babel/issues/11805.

**Comment by mischnic** [comment]
Re issue 2: https://github.com/parcel-bundler/parcel/issues/5557

**Comment by danieltroger** [comment]
Thanks a lot for the quick fix! My script now works in IE11 as long as I build with `--no-scope-hoist`.
