### ISSUE TITLE
Typescript + Preact doesn't work

### ISSUE THREAD

**Issue by FDiskas** [parcel-bundler/parcel#5566]
# 🐛 bug report

`Uncaught ReferenceError: h is not defined`

## 🎛 Configuration (.babelrc, package.json, cli command)

I don't have any special configuration only tsconfig.json
```json
{
  "compilerOptions": {
    "esModuleInterop": true,
    "jsx": "react",
    "jsxFactory": "h",
    "lib": [
      "dom",
      "esnext"
    ],
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "target": "es5"
  }
}
```

## 🤔 Expected Behavior

it should display `hello` on the page

## 😯 Current Behavior

Throws error

## 💁 Possible Solution
If I add unused `h` it should not tree shake it, but it rises another issue not related to this one.
```js
console.log(typeof h);
```
Also its possible to just downgrade to parcel v1

## 🔦 Context

I can't bundle `preact`

## 💻 Code Sample

[trink_1609593696042.zip](https://github.com/parcel-bundler/parcel/files/5760277/trink_1609593696042.zip)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.0-nightly.500 |
| Node             | v14.13.1 |
| npm/Yarn         | npm 6.14.8 |
| Operating System | windows 10 |

**Comment by FDiskas** [comment]
Tried also with a simple jsx got
```
render.js:31 Uncaught TypeError: Cannot read property '__k' of null
```

**Comment by mischnic** [comment]
The problem seems to be that with this babel config:
```
{
	"presets": [
		"@parcel/babel-preset-env",
		"@babel/preset-typescript",
		["@babel/preset-react", { "pragma": "h" }]
	]
}
```
the Babel output is:
```js
import { render } from "preact"; // no h
var root = document.getElementById("root");
render(h("div", null, "hello"), root);
```

for  this input:
```js
import { h, render } from "preact";
const root = document.getElementById("root");
render(<div>hello</div>, root);
```

**Comment by mischnic** [comment]
See https://github.com/babel/babel/issues/12585
