### ISSUE TITLE
Cann't install nightly build

### ISSUE THREAD

**Issue by mrparag94** [parcel-bundler/parcel#5569]
npm install --save-dev parcel@2.0.0-nightly.504

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@parcel%2ffs-search - Not found
npm ERR! 404
npm ERR! 404  '@parcel/fs-search@2.0.0-beta.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\***********\AppData\Local\npm-cache\_logs\2021-01-03T10_47_53_977Z-debug.log

**Comment by amoutonbrady** [comment]
Yeah I've encountered the same this morning. Taking a look at issue, it seems like some internal package have changed or have not been published yet (@parcel/watcher, @parcel/fs) to their latest nightly version. I wouldn't worry too much about it, it will probably be uploaded soon :)

**Comment by DeMoorJasper** [comment]
We're aware of the issue with `@parcel/fs-search`, the watcher is on a seperate release cycle so shouldn't be impacted by this.

But the fs-search package is something new we just added recently and the release wasn't set up properly unfortunately

**Comment by danieltroger** [comment]
I'm also having this issue :(

**Comment by amoutonbrady** [comment]
@DeMoorJasper You are right, I thought I had read `@parcel/watcher`, but I must have been confused with something else.. This is just the @parcel/fs-search. Sorry for the confusion

**Comment by devongovett** [comment]
Just released a new nightly and the [@parcel/fs-search](https://www.npmjs.com/package/@parcel/fs-search) package appears to be published. I was able to install it on my machine successfully.

**Comment by danieltroger** [comment]
Nice, it works again. Thanks a lot!
