### ISSUE TITLE
Node 10 - assets.flatMap is not a function

### ISSUE THREAD

**Issue by aminya** [parcel-bundler/parcel#5577]
# 🐛 bug report

Parcel 2 does not work on Node 10 anymore
```js
Building SimpleTable.tsx...
Error: assets.flatMap is not a function
× Build failed.
TypeError: assets.flatMap is not a function
    at Transformation.runPipelines (D:\a\solid-simple-table\solid-simple-table\node_modules\@parcel\core\lib\Transformation.js:368:131)
```

## 🎛 Configuration (.babelrc, package.json, cli command)

Everything is available here:
https://github.com/aminya/solid-simple-table

```json
  "targets": {
    "main": {
      "context": "browser",
      "engines": {
        "browsers": "> 0.25%"
      },
      "includeNodeModules": true,
      "isLibrary": true
    },
    "module": {
      "context": "browser",
      "engines": {
        "browsers": "Chrome 76"
      },
      "includeNodeModules": false,
      "isLibrary": true
    },
}
```

babel
```json
{
  "presets": ["babel-preset-solid", "@babel/preset-typescript", "@parcel/babel-preset-env"],
  "plugins": ["@parcel/babel-plugin-transform-runtime"]
}

```

## 🤔 Expected Behavior
Node 10 should work like other versions

## 😯 Current Behavior
It does not work

## 💻 Code Sample
https://github.com/aminya/solid-simple-table

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |^2.0.0-nightly.489
| Node             | 10
| npm/Yarn         | 6
| Operating System | Win 10

**Comment by mischnic** [comment]
We have dropped Node 10 support because it's a maintenance LTS version already.

Didn't you get a warning from npm? We do specify `"engines": {"node": ">= 12.0.0"}`: https://unpkg.com/browse/@parcel/core@2.0.0-nightly.500/package.json

**Comment by aminya** [comment]
It was working a week ago. 

There are no deprecation warnings:
https://github.com/aminya/solid-simple-table/runs/1640726398#step:4:1

**Comment by mischnic** [comment]
With npm 6.14.8, I get loads of warnings:
```
npm WARN notsup Unsupported engine for parcel@2.0.0-nightly.506: wanted: {"node":">= 12.0.0"} (current: {"node":"10.23.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: parcel@2.0.0-nightly.506
npm WARN notsup Unsupported engine for @parcel/diagnostic@2.0.0-nightly.508: wanted: {"node":">= 12.0.0"} (current: {"node":"10.23.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @parcel/diagnostic@2.0.0-nightly.508
npm WARN notsup Unsupported engine for @parcel/logger@2.0.0-nightly.508: wanted: {"node":">= 12.0.0"} (current: {"node":"10.23.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @parcel/logger@2.0.0-nightly.508
npm WARN notsup Unsupported engine for @parcel/events@2.0.0-nightly.508: wanted: {"node":">= 12.0.0"} (current: {"node":"10.23.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @parcel/events@2.0.0-nightly.508
npm WARN notsup Unsupported engine for @parcel/utils@2.0.0-nightly.508: wanted: {"node":">= 12.0.0"} (current: {"node":"10.23.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @parcel/utils@2.0.0-nightly.508
npm WARN notsup Unsupported engine for @parcel/package-manager@2.0.0-nightly.508: wanted: {"node":">= 12.0.0"} (current: {"node":"10.23.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @parcel/package-manager@2.0.0-nightly.508
npm WARN notsup Unsupported engine for @parcel/core@2.0.0-nightly.506: wanted: {"node":">= 12.0.0"} (current: {"node":"10.23.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @parcel/core@2.0.0-nightly.506
...
```

Yarn:
```
$ yarn add -D parcel@nightly
yarn add v1.22.10
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error @parcel/fs@2.0.0-nightly.508: The engine "node" is incompatible with this module. Expected version ">= 12.0.0". Got "10.23.0"
error Found incompatible module.
```

> It was working a week ago.

https://github.com/parcel-bundler/parcel/pull/5542

**Comment by aminya** [comment]
@mischnic At least you could have released a beta version with locked dependencies before dropping Node 10 support. Now, there is no way to get Parcel 2 working on Node 10, while it was possible a week ago.

Using older parcel versions does not help as this happens even with parcel alpha.

**Comment by devongovett** [comment]
You could choose a nightly version. These have pinned dependencies. Or use a lock file.

May I ask why you're still using Node 10? It's going out of LTS in a couple months, so we figured dropping support would be ok.

**Comment by aminya** [comment]
> You could choose a nightly version. These have pinned dependencies. Or use a lock file.
> 

It does not seem to.

The job fails if I use something like `"parcel": "2.0.0-alpha.3.2 || ^2.0.0-nightly.489",` in package.json. It still resolves to a broken version on Node 10.

https://github.com/aminya/solid-simple-table/blob/11dd996ba137f8f91e582a508c94d81298021425/package.json#L43
https://github.com/aminya/solid-simple-table/runs/1641028296?check_suite_focus=true#step:4:5

> May I ask why you're still using Node 10? It's going out of LTS in a couple months, so we figured dropping support would be ok.

Definitely using the latest technology is a great idea, but when the workaround for supporting the old version, is just as simple as adding a version entry for the old Node, I don't see a reason for not doing so.

I use the latest Node, but as a library writer, I try to make the library buildable on the still supported software.

**Comment by mischnic** [comment]
`^2.0.0-nightly.489` matches any nightly that comes afterwards: https://jubianchi.github.io/semver-check/#/^2.0.0-nightly.489/2.0.0-nightly.20000

**Comment by aminya** [comment]
> `^2.0.0-nightly.489` matches any nightly that comes afterwards: [https://jubianchi.github.io/semver-check/#/^2.0.0-nightly.489/2.0.0-nightly.20000](https://jubianchi.github.io/semver-check/#/%5E2.0.0-nightly.489/2.0.0-nightly.20000)

Yeah, but why `2.0.0-alpha.3.2` is not chosen on Node 10. If the package.json entry has `Node > 12` for the nightly entry, this should not happen.

**Comment by mischnic** [comment]
alpha.3.2 uses non-exact ranges: https://unpkg.com/browse/parcel@2.0.0-alpha.3.2/package.json.
Which also match any nightly 😬  https://jubianchi.github.io/semver-check/#/^2.0.0-alpha.3.1/2.0.0-nightly.20000.
So even `parcel@2.0.0-alpha.3.2` will use nightlies....

The betas use exact ranges though. So you actually get what you specify

**Comment by aminya** [comment]
https://github.com/aminya/solid-simple-table/blob/5c9f7e129d836a21e8069edef07871d38fc08eee/package.json#L43

This does not work either:
```
    "parcel": "2.0.0-beta.1 || ^2.0.0-nightly.489",
```

I don't know how npm resolves things, but it seems it does not care about the Node version.

**Comment by mischnic** [comment]
>   "parcel": "2.0.0-beta.1 || ^2.0.0-nightly.489",

Why do you add the nightly as well?

npm probably takes the newest version here (the second half), so it will be the latest nightly anyway. Just use `2.0.0-beta.1`

**Comment by devongovett** [comment]
If you want to continue to run Parcel on node 10, you will need to pin it to an old version. Using any kind of range like that will result in newer versions. npm will not do any kind of node version-based matching for you.

**Comment by aminya** [comment]
I wrote a custom script to install and build the project using Parcel 1, 2-beta or 2-nightly based on the Node version.
```js
const child_process = require('child_process');
const path = require('path')

if (parseFloat(process.version.match(/^v(\d+\.\d+)/)[1]) < 10) {
  child_process.execSync(`npm install parcel@1`, {stdio: 'inherit'})
  child_process.execSync(`node ${path.resolve('./node_modules/parcel/dist/bin/parcel')} parcel build --target main --target types --target module  --experimental-scope-hoisting src/SimpleTable.tsx`, {stdio: 'inherit'})
} 
else if (parseFloat(process.version.match(/^v(\d+\.\d+)/)[1]) < 12) {
  child_process.execSync(`npm install parcel@2.0.0-beta.1`, {stdio: 'inherit'})
  child_process.execSync(`node ${path.resolve('./node_modules/parcel/dist/bin/parcel')} parcel build --target main --target types --target module src/SimpleTable.tsx`, {stdio: 'inherit'})
} else {
  child_process.execSync(`node ${path.resolve('./node_modules/parcel/dist/bin/parcel')} parcel build --target main --target types --target module src/SimpleTable.tsx`, {stdio: 'inherit'})
}
```
