### ISSUE TITLE
Extract CSS from the bundle

### ISSUE THREAD

**Issue by aminya** [parcel-bundler/parcel#5590]
# 🙋 feature request

 I have a component library that imports CSS into the components. I do this so Parcel transforms and bundles CSS for me. But I don't want them to be required into the JS bundle which breaks the workflow of anyone who does not use Parcel or similar transformers.

https://github.com/aminya/solid-simple-table/blob/20c4c543fe4604acd3877426055abc474416d67a/src/SimpleTable.tsx#L2

## 🤔 Expected Behavior

An option to remove `require('something.css')` after the bundle is created.

## 😯 Current Behavior

There is no way to remove `require('something.css')`.

## 💁 Possible Solution
I couldn't find a bundler agnostic CSS extractor, but probably there is one out there.
https://www.npmjs.com/search?q=extract%20css

## 🔦 Context
Related to https://github.com/parcel-bundler/parcel/discussions/5246

## 💻 Examples

```tsx
import "./MyStyle.less"
console.log('Hey')
```
I want the bundle to only include
```tsx
console.log('Hey')
```

**Comment by mischnic** [comment]
One workaround would be using alias in package.json to exclude the JS import: `alias: { "./src/MyStyle.less": false }`

**Comment by aminya** [comment]
@mischnic Using alias causes the `less` file to not be transformed at all.

**Comment by aminya** [comment]
I found a babel plugin that does this! 🎉 

However, Babel transformation happens "before" parcel performs the CSS bundling. If you can integrate this babel plugin and somehow run it in the end after everything is done, that exactly solves the issue.

https://www.npmjs.com/package/@iwatakeshi/babel-plugin-remove-import-styles

For now, I wrote a custom script and used babel's cli:

package.json
```
    "style": "babel dist --out-dir dist --config-file ./babel.style.config.json",
```
babel.style.config.json
```json
{
  "plugins": [
    [
      "@iwatakeshi/babel-plugin-remove-import-styles",
      {
        "extensions": [".css", ".less", ".sass"]
      }
    ]
  ]
}
```

**Comment by aminya** [comment]
Can we get this babel plugin integrated into Parcel? It should run after all the CSS transformations.

**Comment by mischnic** [comment]
You'd need to create another transformer that runs after all default JS transformers
