### ISSUE TITLE
babel transform error?

### ISSUE THREAD

**Issue by webular** [parcel-bundler/parcel#56]
error:

```
Server running at http://localhost:1234
🚨  ..../node_modules/react-dates/constants.js: Unexpected token ] in JSON at position 102
    at JSON.parse (<anonymous>)
    at Object.load (/Users/***/.config/yarn/global/node_modules/parcel-bundler/src/utils/config.js:35:17)
    at <anonymous>
```

code:
```
import { START_DATE } from 'react-dates/constants';
```

Am I missing a babel transform?

here is my .babelrc

```
{
  "presets": ["env", "react", "stage-0"],
  "plugins": [
    ["module-resolver", {
      "alias": {
        "common": "./src/common"
      }
    }]
  ]
}
```

**Comment by davidnagli** [comment]
Hi! Thanks for reporting the error!

I’m still new to the Parcel community, so I’m not experienced enough to know what the error means or how to fix it, but I can tell you that it looks VERY similar to the error from #19. 

Maybe to two are connected in some way?

**Comment by devongovett** [comment]
seems like maybe there is a parse error in the babelrc JSON?

**Comment by davidnagli** [comment]
No there isn’t I checked… 

In #19 (which is the exact same error message), the provided `.babelrc` actually does have a parse error. But I ran this one through `JSON.parse()` and it seems to be fine!

**Comment by DeMoorJasper** [comment]
Appears to be a JSON error in .babelrc from react-dates, closing of this issue
![capture](https://user-images.githubusercontent.com/2175521/33955184-f510a6b8-e03a-11e7-8f74-18ced6ffa0de.PNG)
If you feel this should be reopened feel free to do so
