### ISSUE TITLE
ParcelJS referencing files from DIS folder instead of the ROOT making it impossible to debug code

### ISSUE THREAD

**Issue by AyoDadesanya** [parcel-bundler/parcel#5616]
# 🐛 bug report

I cant debug my code because when I run dev mode, (npm run dev) the console is referencing the parcel js cloned file in the DIS folder.

This is not the expected behaviour. Parcel.js, in development mode should be referencing the original main.js file in the root folder.

I have ran another parcel.js installation on another mac to re-produce the same error, but parcel.js worked as expected, meaning this problem maybe isolated to my own mac. At this point i have no idea what to do.

I am a complete newbie.

Therefore I can't debug my code, look below where the errors are... its pointing to the cloned files in the DIS folder rather than my files in the ROOT folder.

[Console Window Error](https://i.stack.imgur.com/yyEaP.png)

The console logs are pointing to the cloned main.js file in the DIS folder.

I've re-installed parcel several times, I don't know what i'm doing wrong here.

This is what my set up looks like.

[Full view of my desktop and file structure, with console error](https://i.stack.imgur.com/o2lrp.png)

it should not be pointing too **main.1f19ae8e.js:121**
It should be pointing to **main.js**

**The worst thing about this issue is. it works on other machines following the same process.** 

_Everything works as expected when i click debug in the package.json_
[Debug](https://i.stack.imgur.com/wz9Ga.png)

[Debug report](https://i.stack.imgur.com/R6Y4p.jpg)

[My package.json](https://i.stack.imgur.com/p8gwX.png)

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json

{
  "name": "testt",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "dev": "parcel index.html"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel": "^2.0.0-beta.1"
  },
  "dependencies": {}
}

## 🤔 Expected Behavior

when i run 'npm run dev' and go into chrome development tools, all console.logs() should reference main.js in ROOT folder

## 😯 Current Behavior

when i run 'npm run dev' and go into chrome development tools, all console.logs() reference main.js in DIS folder

## 💁 Possible Solution

no idea at this point.

## 🔦 Context

i'm trying to set up a development environment rather than using live-server.

## 💻 Code Sample

https://github.com/ahinchliff/ayo

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.12.4
| Node             | v14.15.4
| npm/Yarn         | 6.14.10
| Operating System | macOS Catalina 10.15.7 (19H114)

**Comment by AyoDadesanya** [comment]
Solved it bro!!! I randomly tested it on fire-fox and it worked... so i switched off all my chrome extensions and tested it again...still didn't work.... then i decided to a clean reinstall of chrome and it worked! Guess i will never no the true fault. But my chrome install must of been buggy or something.

**Comment by naresh-webdev** [comment]
I faced the same issue and it worked 👍, thanks a lot.
