### ISSUE TITLE
Syntax error with number toString()

### ISSUE THREAD

**Issue by mariusk** [parcel-bundler/parcel#5618]
I recently upgraded from `2.0.0-nightly.506` to `2.0.0-nightly.522` and my builds started failing.

The error in the browser becomes:

`Uncaught SyntaxError: Invalid or unexpected token`

Looking into the actual problem, with the new version, this line of code:

`if(2147483647<=v)throw new RangeError("Attempt to allocate Buffer larger than maximum size: 0x"+(2147483647).toString(16)+" bytes");`

the parens gets removed, so that part of that line effectively becomes:

`2147483647.toString(16)`

which is what the browser barfs on.

I think this comes from me including the `autobahn` module in my project.

Reverting back to `506` everything gets built and works correctly again. When it works correctly again, I notice that there is an extra space in that line:

`2147483647 .toString(16)`

which seems to make it work. At least when I test both variants in Node.

**Comment by mischnic** [comment]
Can be triggered with this this:
```js
console.log("foo " + (1234).toString(16));
```

@devongovett

**Comment by devongovett** [comment]
Ah, probably a bug in astring...
