### ISSUE TITLE
JSON file empty when loaded in in 2.0.0-nightly.524

### ISSUE THREAD

**Issue by Cristy94** [parcel-bundler/parcel#5623]
# 🐛 bug report

Upgrading from 286 to 524 stops i18n translations from loading.

I import JSON files like this:

```js
import tranlationEN from './locale/en.json';
```

JSON Files contain a single key/value JSON object:

```
{
    "ab_test.add_change": "Add new change",
    "ab_test.add_new": "Add new test",
    "ab_test.change.info": "The change value can be a string or an array of CSS inline styles. \n For example: [['display', 'none']].",
    "ab_test.delete": "Delete this A/B test",
    "ab_test.edit": "Edit test"
}
```

I also want to mention that I keep trying upgrading from 286 to a newer version, but whenever I try to do so there's something that breaks (either building, file imports, hot reloading, etc.).

## 🎛 Configuration (.babelrc, package.json, cli command)
.babelrc
```json
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    "@babel/preset-typescript"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-nullish-coalescing-operator",
    "@babel/plugin-proposal-optional-chaining"
  ]
}
```

## 🤔 Expected Behavior

I am using i18n, and when upgrading from nightly 286 to 254, the JSON files I use for translations are no longer loaded.

## 😯 Current Behavior

Loaded JSON objects is empty.

## 💻 Code Sample
This is how the JSON is used:
```js
const resources = {
    en: {
        translation: tranlationEN
    },
    ro: {
        translation: tranlationRO
    },
    nl: {
        translation: tranlationNL
    },
    de: {
        translation: tranlationDE
    }
};

export const initialLanguageState = () => window.localStorage.ust_language || 'en';
moment.locale(initialLanguageState());
i18n
    .use(initReactI18next) // passes i18n down to react-i18next
    .init({
        resources,
        lng: initialLanguageState(),

        debug: Config.IS_DEV,

        keySeparator: false, // we do not use keys in form messages.welcome

        interpolation: {
            escapeValue: false // react already safes from xss
        },

        fallbackLng: 'en',
    });

export default i18n;
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.524 
| Node             | 14.15.0
| npm/Yarn         | 6.14.8
| Operating System | W10

**Comment by mischnic** [comment]
Have you cleared the cache after upgrading? Works for me in a small test case

**Comment by Cristy94** [comment]
The good part is that building still works (couldn't build with other versions that I tried from 286, but this one works).

I cleared the cache after upgrading and it seems to work now.
I have to note that I did clear the cache **before upgrading**.

Thanks for the help and good job with fixing most of the build issues!

The only major issue I encounter with parcel is https://github.com/parcel-bundler/parcel/issues/4882, which makes writing CSS that overwrites other imported libraries CSS not work (as bundled CSS is always imported at the top).

**Comment by Cristy94** [comment]
Actually, it happened again. So it seems like sometimes the JSON files fail to load and then their empty contents are cached.

**Comment by Cristy94** [comment]
Ok, this clearly still happens.

What I noticed is that when it happens if I change the JSON file it's loaded correctly, but if I revert my changes the file is loaded as being empty again. I assume that somehow the parcel-cache wrongly assigns the current file hash an empty file content, so whenever the file has again that has, the empty cached file is loaded.

**Comment by mischnic** [comment]
That sounds plausible, probably related to #5570 / #5311 / #5656.
