### ISSUE TITLE
HMR bugs out with react

### ISSUE THREAD

**Issue by alexreardon** [parcel-bundler/parcel#5626]
After a few modifications to an existing file, HMR stops working and I see this issue all over the place:

> react.development.js:246 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

I suspect it *might* be related to https://github.com/emotion-js/emotion/issues/1404

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.524 |
| Node             | 14.15.0 |
| npm/Yarn         | yarn |
| Operating System | mac 11.1 |

**Comment by mischnic** [comment]
Please provide a reproduction

**Comment by alexreardon** [comment]
How would you like me to set up a reproduction? Would you like me to create a new repo?

**Comment by mischnic** [comment]
Yes, that would be great.

**Comment by 101arrowz** [comment]
I used to get this with Preact, but `preact/compat` fixed it. You may need to create a Babel config with the Emotion plugin.

**Comment by alexreardon** [comment]
I have the emotion Babel plugin running. I will try make a stand alone repo soon
