### ISSUE TITLE
[regression in parcel2] optional chaining is still used in the transpiled code of optional chaining

### ISSUE THREAD

**Issue by danieltroger** [parcel-bundler/parcel#5627]
# 🐛 bug report

[optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) is broken and [it is not a babel bug](https://babel.dev/repl#?browsers=chrome%2032&build=&builtIns=false&spec=false&loose=false&code_lz=JYMwFAJg9gxgrgWwKYDsAuB-AdAIyhAT2wEc4kAnAgZSQBskY0pywAiLNJAZzVYEpswFCgoAVJAA80AAgC886awAWwfgG8AUNOkBDeuTRsA6kp1oA5F2lwADhn4BuDQF8NQA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.12.9&externalPlugins=)

## 🎛 Configuration (.babelrc, package.json, cli command)

Similar to #5555 except I tried to add `"@babel/plugin-proposal-optional-chaining"` to .babelrc in an attempt to fix it, **please just check the reproduction repo**

## 🤔 Expected Behavior

transpiled code is supposed to _not include `?.`_ when building for IE11, but it does.

**This is built with parcel `2.0.0-nightly.520+71264fe1` where it still works, notice it doesn't contain any ?.**

```
(function () {
  // ASSET: src/main.ts
  var $c897f61df880517db71e186672d4df37$var$_document, $c897f61df880517db71e186672d4df37$var$_document$body, $c897f61df880517db71e186672d4df37$var$_document$body$queryS;

  if ((($c897f61df880517db71e186672d4df37$var$_document = document) === null || $c897f61df880517db71e186672d4df37$var$_document === void 0 ? void 0 : ($c897f61df880517db71e186672d4df37$var$_document$body = $c897f61df880517db71e186672d4df37$var$_document.body) === null || $c897f61df880517db71e186672d4df37$var$_document$body === void 0 ? void 0 : ($c897f61df880517db71e186672d4df37$var$_document$body$queryS = $c897f61df880517db71e186672d4df37$var$_document$body.querySelector(".test")) === null || $c897f61df880517db71e186672d4df37$var$_document$body$queryS === void 0 ? void 0 : $c897f61df880517db71e186672d4df37$var$_document$body$queryS.innerText) === "hi") {
    alert("What's up??");
  }
})();
//# sourceMappingURL=ie11.js.map
```

## 😯 Current Behavior

```
(function () {
  // ASSET: src/main.ts
  var $c897f61df880517db71e186672d4df37$var$_document, $c897f61df880517db71e186672d4df37$var$_document$body, $c897f61df880517db71e186672d4df37$var$_document$body$queryS;
  if ((($c897f61df880517db71e186672d4df37$var$_document = document) === null || $c897f61df880517db71e186672d4df37$var$_document === void 0 ? void 0 : ($c897f61df880517db71e186672d4df37$var$_document$body = $c897f61df880517db71e186672d4df37$var$_document?.body) === null || $c897f61df880517db71e186672d4df37$var$_document$body === void 0 ? void 0 : ($c897f61df880517db71e186672d4df37$var$_document$body$queryS = $c897f61df880517db71e186672d4df37$var$_document$body?.querySelector(".test")) === null || $c897f61df880517db71e186672d4df37$var$_document$body$queryS === void 0 ? void 0 : $c897f61df880517db71e186672d4df37$var$_document$body$queryS?.innerText) === "hi") {
    alert("What's up?");
  }
})();

//# sourceMappingURL=ie11.js.map
```

I quote: `ent$body$queryS?.innerText) === "`
The `?.` throws a syntax error in IE11

## 💁 Possible Solution

Revert what made the issue appear

## 🔦 Context

I updated parcel to test if the MR mentioned in #5557 had fixed #5557 and was greeted with all my code stopping to work in IE11.

It is broken in this version: `2.0.0-nightly.524+97a7bfee` but it still works in `2.0.0-nightly.520+71264fe1`

## 💻 Code Sample

Reproduction "repo": [optional-chaining.zip](https://github.com/parcel-bundler/parcel/files/5802983/optional-chaining.zip)

```
if(document?.body?.querySelector(".test")?.innerText === "hi"){
  alert("What's up?");
}

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.524+97a7bfee |
| Node             | v15.5.1 |
| npm/Yarn         | npm v7.3.0
| Operating System | macOS 10.13.6

**Comment by mischnic** [comment]
Reproduction:
```js
import fs from 'fs';
import babelGenerate from '@babel/generator';
import {generate as astringGenerate} from 'astring';
import {
  generator,
  expressionPrecedence,
} from './packages/shared/babel-ast-utils/src/generator.js';
import {transformSync} from '@babel/core';

const INPUT = `let a;
console.log(a?.b);`;

const ast = transformSync(INPUT, {
  plugins: ['@babel/plugin-proposal-optional-chaining'],
  code: false,
  ast: true,
}).ast.program;

console.log("--- Babel:")
console.log(babelGenerate(ast).code);

console.log("--- astring:")
console.log(
  astringGenerate(ast, {
    generator,
    expressionPrecedence,
    comments: true,
  }),
);
```

Prints:
```
--- Babel:
"use strict";

let a;
console.log(a === null || a === void 0 ? void 0 : a.b);

--- astring:
Program
"use strict";
let a;
console.log(a === null || a === void 0 ? void 0 : a?.b);
```

**Comment by aminya** [comment]
This issue breaks my workflow too. 

I wish Parcel was like any other npm package and it released normal releases, so we don't have to be on the nightly releases which can break any time. 

Other packages follow Semantic release instead of just bumping the nightly number which does not count as a release. The major.minor.patch shows if the release is breaking or not.

Reminder: the last beta release was 7 months ago, and the last stable release was 1 year ago. This has forced most people to use nightlies

**Comment by danieltroger** [comment]
@aminya If you want to stay on one version you can run `npx parcel --version` and then in the packages.json replace nightly with said version.

But I agree that this regression sucked. Parcel 1 is too flawed for me so I had to upgrade. Don't know why parcel 2 doesn't get officially released.
