### ISSUE TITLE
Cache results in empty bundle

### ISSUE THREAD

**Issue by aminya** [parcel-bundler/parcel#5656]
# 🐛 bug report

In [a project](https://github.com/steelbrain/linter-ui-default) that I am working on, sometimes the build results in an empty bundle. I have to clean .parcel-cache to fix this problem.

```js
> cross-env NODE_ENV=production parcel build --target main ./lib/index.ts

√ Built in 7.07s

dist\index.js          35 B    177ms
└── lib\index.ts    1.61 KB    3.36s
```

This happens when I edit the code and build again.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
  "targets": {
    "main": {
      "context": "node",
      "includeNodeModules": {
        "atom": false,
        "electron": false,
        "react": false,
        "react-dom": false,
        "atom-package-deps": false
      },
      "outputFormat": "commonjs",
      "isLibrary": true
    }
  },
```

## 🤔 Expected Behavior
build normally

## 😯 Current Behavior
The build results in an empty bundle if .parcel-cache exists

## 💁 Possible Solution

Remove .parcel-cache

## 💻 Code Sample

https://github.com/steelbrain/linter-ui-default

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | Parcel 2 nightlies (this is an old bug I have seen for a long time)
| Node             | 15.5 (irrelevant) 
| npm/Yarn         | 6.14.11
| Operating System | Win 10

**Comment by mischnic** [comment]
> sometimes

Any chance you found a way to consistently trigger this (e.g. 1. clear cache 2. build 3. some changes 4. build again)

**Comment by aminya** [comment]
Running `npm run dev` stopping it using CTRL+C and then running `npm run build` is a way to reproduce this.

**Comment by mischnic** [comment]
👍 

1. rm -rf .parcel-cache dist
2. npm run build
3. npm run dev 
4. npm run build

4 is empty, the other ones are correct

**Comment by mischnic** [comment]
Reproduction:
```js
// a.ts
console.log("hello");
```
```json5
// .parcelrc
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
}
```

and then
`rm -rf dist .parcel-cache; yarn parcel build a.ts; yarn parcel watch a.ts; yarn parcel build a.ts`

Works fine without the typescript transformer.

Probably related to https://github.com/parcel-bundler/parcel/pull/5570 / #5311
