### ISSUE TITLE
{} is not a function

### ISSUE THREAD

**Issue by aminya** [parcel-bundler/parcel#5657]
# 🐛 bug report

In the recent nightlies dynamic requires in the Node context result in an empty object `{}`. This does not happen on 2.0.0-nightly.520.

```js
    if (!atom.inSpecMode()) {
      require('atom-package-deps').install('linter-ui-default')
    }
```
becomes
```js
    if (!atom.inSpecMode()) {
      ({}).install('linter-ui-default')
    }
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
  "targets": {
    "main": {
      "context": "node",
      "includeNodeModules": {
        "atom": false,
        "electron": false,
        "react": false,
        "react-dom": false,
        "atom-package-deps": false
      },
      "outputFormat": "commonjs",
      "isLibrary": true
    }
  },
```

## 🤔 Expected Behavior
Resolve the correct package

## 😯 Current Behavior
Changes require to an empty object

## 💁 Possible Solution
Downgrade to 2.0.0-nightly.520.

## 💻 Code Sample
https://github.com/steelbrain/linter-ui-default/tree/9d642de23507d704332b31051c547904477674cb

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.532
| Node             | 15.5 
| npm/Yarn         | 6.14.11
| Operating System | Win 10

**Comment by mischnic** [comment]
Reproduction:
```js
if (Date.now() > 0) {
	require("path").dirname("/abc");
}
```
```json
{
	"dependencies": {
		"parcel": "2.0.0-nightly.532"
	},
	"engines": {
		"node": ">= 10"
	}
}
```

Output:
```
var {dirname} = require("path");
if (Date.now() > 0) {
  ({})("/abc");
}
```

**Comment by aminya** [comment]
Is there a way to fix this?
