### ISSUE TITLE
Script tags with unknown type break the build

### ISSUE THREAD

**Issue by surma** [parcel-bundler/parcel#5675]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

I'm currently experimenting with import maps. This issue is not about adding support for import maps to Parcel (although that would also be great). Rather I think it’s sensible for Parcel to _ignore_ (but not remove) script tags that have an unknown `type` attribute value.

Currently, the build just fails.

```html
<script type="importmap">
  {
    "imports": {
      "lit1.3.0/": "/node_modules/lit1.3.0/"
    }
  }
</script>
```

Build error:
```
🚨 Build failed.
@parcel/namer-default: Destination name lab/diagram/lab.HASHREF87e0fc1c687aef7f40e7b239de7d6ef4.undefined extension does not match bundle type "undefined"

```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.537

**Comment by mischnic** [comment]
> adding support for import maps to Parcel (although that would also be great)

What do you have in mind here? Using import maps to solve the cascading invalidations problem instead of embedding something custom in the entry bundle as we currently do?
