### ISSUE TITLE
🐛Watch is not working with usage of native css variables

### ISSUE THREAD

**Issue by MathRobin** [parcel-bundler/parcel#568]
Hi everybody, thanks for this great tool !

On a really simple project, just to try, it seems that parcel doesn't detect changes in imported CSS files using native @import. Mainly for the changes concerning the native variable déclarations. Have made a simple repo to reproduce the problem here : https://github.com/MathRobin/parcel-bug-css-demo

If build first time (for generating dist files and cache). Reboot parcel and now modify one of the variables in variables.css files. This will not trigger the build. If you change the part with normal selector with no usage of variables, no problem. Super strange.

### 🎛 Configuration (.babelrc, package.json, cli command)

No babel used, no package.json, just ran this command :

`parcel index.html`

### 🤔 Expected Behavior

When changes css variables in variables.css, it should recompile.

### 😯 Current Behavior

It doesn't recompile, so need to relaunch parcerl.

### 💁 Possible Solution

No idea

### 💻 Code Sample

https://github.com/MathRobin/parcel-bug-css-demo

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel | 1.4.1 |
| Node | 8.9.3 |
| npm/Yarn | 5.6.0 |
| Operating System | Ubuntu 17.10 |

Kiss, love !

**Comment by GreggOrdHume** [comment]
Why would you @import .css files? It still requests multiple css files from browser to server. Its the same as including the variables.css file in the head of your index.html.

You can therefor include variables.css first, then your other css files in your head and still use the variables where ever you want.

or Rather use SASS and you can use css variables as well as sass variables in your sass files, much more modular and cleaner:
https://codepen.io/jakealbaugh/post/css4-variables-and-sass

**Comment by MathRobin** [comment]
Yes, Sass is more clean and has so much more avantage. But why not if i want to use it ? It's "vanilla". And a bug in an @import, could be less important than in sass, but it sends signal that something is not working in watch. Maybe at another place there is someting else which is not working too.

**Comment by osdevisnot** [comment]
If I understand this problem correctly, is seems the `WebSocket` client can not recover from disconnects. If you hit browser refresh, WS gets chance to re-connect and everything should work correctly.  Simple solution is for client WS to retry connection on close, something like this:
```
function start(){
  console.log('new HMR PORT : ', process.env.HMR_PORT)
  var ws = new WebSocket('ws://' + hostname + ':' + process.env.HMR_PORT + '/');
  ws.onmessage = function(event) {...};
  ws.onclose = () => {
    console.error('[parcel] 🚨 disconnected from server');
    setTimeout(function(){start()}, 5000);
  }
}

start();
```

But this will not work since current HMR setup picks up different port on re-runs. Maybe we can use a fix port for HMR updates. If that sounds ok, I can make a PR to that effect.

**Comment by DeMoorJasper** [comment]
@osdevisnot You can still use the random port but just save it somewhere, so you can reuse it on restarts/reconnects

**Comment by MathRobin** [comment]
No it's not that the problem. What i said is that css native variables changes are not detected.

**Comment by DeMoorJasper** [comment]
@MathRobin this should be fixed in the latest master branch version

**Comment by MathRobin** [comment]
Ok great to know, thanks :)
