### ISSUE TITLE
[webextension-transformer] browser_action.theme_icons should be an array of objects

### ISSUE THREAD

**Issue by Tezkerek** [parcel-bundler/parcel#5680]
Reference: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action
Relevant lines: https://github.com/parcel-bundler/parcel/blob/bdc45e49437b986934d3b1b0d8f6a4ecc292a2aa/packages/transformers/webextension/src/schema.js#L65-L73

An example from the manifest of Sidebery:
```json
"theme_icons": [
  {
    "light": "./assets/logo-native-light.svg",
    "dark": "./assets/logo-native-dark.svg",
    "size": 16
  },
  {
    "light": "./assets/logo-native-light.svg",
    "dark": "./assets/logo-native-dark.svg",
    "size": 32
  }
]

```

**Comment by mischnic** [comment]
So it should be this instead:
```js
theme_icons: {
  type: 'array',
  items: {type: 'object', properties: ...., required: ....}
}
```

Should they also be picked up by Parcel and copied into dist? That doesn't seem to be the case at the moment...

**Comment by Tezkerek** [comment]
Shouldn't all files referenced in manifest.json be output to dist? In the case of assets they would just be copied.

**Comment by 101arrowz** [comment]
Sorry about this, will fix now.
