### ISSUE TITLE
HTML entities are replaced with the actual symbols in the compiled css

### ISSUE THREAD

**Issue by mtskf** [parcel-bundler/parcel#5682]
# 🐛 bug report

HTML entities are replaced with the actual symbols in the compiled css.
And thus, the symbols show up garbled.

For example: If I comple scss with a pseudo element with html entity like this:

Source SCSS:
```
#test:before { content: "\2713"; }
```

Compiled css:
```
#test:before { content: "✓"; }
```

The html entity '\2713' is replaced with the actual symbol '✓' in the complied css,
and then, it's shown like this "eâœ“" on browsers.

**Comment by mischnic** [comment]
I think this is done by Sass: also happens when entering the source on https://www.sassmeister.com/.

**Comment by mtskf** [comment]
@mischnic 
Hmm, it seems the escaping is done by the both SASS & Parcel.

For example:
```
// SCSS code
@charset "UTF-8";
#test:before {
  content: "\1F44B";
  content: unquote("\"\\#{1F44B}\"");
}

// output with SassMeister:
#test:before {
  content: "👋";
  content: "\1F44B";
}

// output with Parcel
#test:before {
  content:"�";
  content:"👋"
}
```
