### ISSUE TITLE
Parcel 2 cannot build Vue and Tailwind

### ISSUE THREAD

**Issue by RichardJECooke** [parcel-bundler/parcel#5685]
# 🐛 bug report

Parcel 1 was building a one file Vue and Tailwind project fine.
But then it couldn't build a separate .vue file so Google told me to upgrade to Parcel 2.
I then got a build error that my postcss7 library was incompatible with the new Parcel so I upgraded to version 8, but now my css file won't build.

Which package version should I add or change please?

The error is 
```@parcel/transformer-postcss: Cannot read property 'unprefixed' of undefined
TypeError: Cannot read property 'unprefixed' of undefined
    at /mnt/c/data/celi/src/css/main.css:1:1
```

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```js
	"dependencies": {
		"tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.2",
		"vue": "^3.0.5"
	},
	"devDependencies": {
		"autoprefixer": "^9.8.6",
		"parcel": "^2.0.0-beta.1",
		"postcss": "^8.2.1"
	},
```

My CSS file:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

## 🌍 Your Environment

Latest Ubuntu subsystem on Windows 10.
Node 12.16.2.

Build command `npx parcel ./src/index.html`

**Comment by RichardJECooke** [comment]
Further, if I delete my `postcss.config.js` file, install `"@vue/compiler-sfc": "^3.0.5"` and remove Vue and install `"vue": "^3.0.5"` then Vue builds, but no Tailwind styles are applied.

**Comment by mischnic** [comment]
> `@parcel/packager-js: Asset has no content`

That is a known bug: https://github.com/parcel-bundler/parcel/issues/5311#issuecomment-750436106. Try deleting `.parcel-cache` as a workaround.

**Comment by RichardJECooke** [comment]
Ok, thank you. So the solution was to install `"@vue/compiler-sfc": "^3.0.5"` manually, delete `.parcel-cache`, and to keep `postcss.config.js` (without this file Tailwind doesn't seem to apply, even though Parcel tells me I should delete this file).

**Comment by justingolden21** [comment]
Deleting cache and parcel cache worked for me, tailwind now runs with parcel
