### ISSUE TITLE
What is recipe ?

### ISSUE THREAD

**Issue by MathRobin** [parcel-bundler/parcel#569]
Hi !

What is a recipe ? Its goal ? Compared to plugins.

Here (https://parceljs.org/recipes.html) I discover that there are recipes for React and Preact. But... what is a recipe ? What it does ? I don't know React, never used. So i don't know what does react in babel. I know i can search, but maybe a bit of adding documentation could help.

For example, I mainly use angularjs at my work. I will probably want to transform my directives (sort of components) with replacing the templateUrl property by template with inlined template. Classic way of building an app for prod with angularjs.

So I don't know if I have to write a recipe or a plugin. Firstly I thought it needs to be a plugin. But now I saw recipes for React, so not sure anymore.

**Comment by DeMoorJasper** [comment]
It's just a guide to setting up your project for react or preact

**Comment by MathRobin** [comment]
Not sure to understand but ok. So for my goal with angularjs, I must write a plugins so ?

**Comment by DeMoorJasper** [comment]
U can probably use this plugin, but angular should mostly work out of the box, https://github.com/fathyb/parcel-plugin-angular

**Comment by MathRobin** [comment]
It's for angular (so 2+), not for angularjs (1), but thanks, will search. Had my main question answered, if i need, i have to use/dev a plugin, not a recipe. Thanks :)

**Comment by DeMoorJasper** [comment]
It should work out of the box for Angular 2+ as well...
Parcel has typescript build in, the only advantage of the plugin i mentioned is the angular specific optimisation

**Comment by MathRobin** [comment]
Yes I know. angular 2+ already has webpack built-in when using the CLI. I was searching for angularjs (1), that's why I asked. Didn't found a plugin for my need so will probably write it.

**Comment by unt0xication** [comment]
@MathRobin Please let us know if you wrote a plugin for AngularJS. I experience some issues with AngularJS + Parcel and I don't know how i'll resolve that.

**Comment by MathRobin** [comment]
Not decided yet If i switched from my goold old gruntjs stack to parcel. Don't want to move to webpack, to much complicated and not compliant to my view of how to do develop for SEO.
For the moment, parcel's way is more compliant but not totally satisfying.
