### ISSUE TITLE
It there any possibility of upgrading the built in PostCSS to PostCSS 8?

### ISSUE THREAD

**Issue by raffi-minassian** [parcel-bundler/parcel#5695]
# 🙋 feature request

Is there any possibility of upgrading the built in PostCSS support to PostCSS 8 in parcel v1?

## 🤔 Expected Behavior

With Tailwindcss postcss7 compatibility build installed and configured, the "purge" options use of postcss-purgecss should not try to use postcss 8, but it does and this causes it to fail.

## 😯 Current Behavior

With Tailwindcss postcss7 compatibility build installed and configured, everything works admirably except for when using the "purge" option where we get the error message: "PostCSS plugin postcss-purgecss requires PostCSS 8" when trying to build.

## 💁 Possible Solution

Ideally we could get PostCSS 8 support in parcel v1 somehow. We have tried to use the v2 nightly build but that seems to be surfacing a lot of other issues. We are still testing it but we can not rely on it for production.

Is there any way to override parcel's built in postcss and replace it with latest version? I have tried to read over the docs for something like that but nothing is jumping out. Maybe I'm just missing it?

## 🔦 Context

Basically, our issue is that we use Tailwindcss as a postcss module and the latest release requires postcss 8. They offer a postcss7 compatibility build which works well except for when using the "purge" option because it seems the postcss-purgecss module is requiring postcss 8. This results in the error message "PostCSS plugin postcss-purgecss requires PostCSS 8" when trying to build.

## 💻 Examples

Node version: v14.15.1
This is the resulting package.json `devDependencies` after following the installation instructions for the PostCSS7 compatibility build at https://tailwindcss.com/docs/installation#post-css-7-compatibility-build . There are no other `dependencies` in the project where I have found this issue.

```
"devDependencies": {
    "@tailwindcss/postcss7-compat": "^2.0.2",
    "autoprefixer": "^9.8.6",
    "parcel-bundler": "^1.12.4",
    "postcss": "^7.0.35",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.2"
  }
```

This is the tailwind.config.js ...

```
module.exports = {
  purge: {
    enabled: true,
    content: [
      './src/**/*.html'
    ],
    options: {
      whitelist: ['mode-dark'],
    }
  },
  darkMode: 'media',
  theme: {
    extend: {
      //etc
    }
  },
  variants: {
    opacity: ['disabled']
  },
  plugins: []
}

```

This is the postcss.config.js ...

```
module.exports = {
  plugins: [
    require('tailwindcss')
  ]
}
```

**Comment by DeMoorJasper** [comment]
Parcel 2 has postcss 8 support, we're not planning on adding this to parcel 1 as it's a breaking change

**Comment by raffi-minassian** [comment]
That's what I guessed, but thanks for confirming! Will continue to try to do hack-arounds and hope for v2 solutions. 👍

**Comment by electrolyte-orb** [comment]
Does parcel 2 has any chance?

**Comment by StijnCoolen** [comment]
@DeMoorJasper when using v2 (`^2.0.0-beta.1`) I get the following error: 
```
🚨 Build failed.
@parcel/transformer-postcss: PostCSS plugin autoprefixer requires PostCSS 8.
```

There seems to be no postcss 8 in v2, or at least it is not recognized.

**Comment by mischnic** [comment]
> no postcss 8 in v2

Not yet in the beta, only in the nightly.

**Comment by StijnCoolen** [comment]
@mischnic seems to be included here: https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/postcss/package.json

**Comment by mischnic** [comment]
Which version are you using?

As I've said `parcel@2.0.0-beta.1` doesn't use version 8: https://github.com/parcel-bundler/parcel/blob/v2.0.0-beta.1/packages/transformers/postcss/package.json

**Comment by StijnCoolen** [comment]
You are right, how can I use v2 (nightly build) in my project?

**Comment by mischnic** [comment]
`parcel@nightly` instead of `parcel@next`
