### ISSUE TITLE
Css not auto-updating if required from html

### ISSUE THREAD

**Issue by DeMoorJasper** [parcel-bundler/parcel#57]
🙋 feature request
Include css-loader (auto-refresh css) in the bundle if the css is declared in the html

🔦 Context
So for example if someone would use one big global css file in index.html like this, it would not auto-update
```html
<link rel="stylesheet" href="./global.css" />
```

**Comment by davidnagli** [comment]
How is this different from #36? Didn’t you already fix this #58??

**Comment by DeMoorJasper** [comment]
#36 was a small bug with getBundleUrl, this is something in the bundler.
It does not include the css-loader.js module unless css is being imported from js.
So for example if someone would use one big global css file in index.html like this:
``
<link rel="stylesheet" href="./global.css" />
``
It would not auto-update

**Comment by devongovett** [comment]
I believe a parallel JS bundle will get created alongside the CSS, but it doesn't currently get inserted into the HTML. We should do that similar to how we do it for the opposite case (CSS imported from JS). https://github.com/parcel-bundler/parcel/blob/master/src/packagers/HTMLPackager.js#L11

**Comment by abienz** [comment]
I still see this issue with Parcel 1.4.1 and css or styl files in both Firefox and Google Chrome.

Has it actually been fixed?

**Comment by DeMoorJasper** [comment]
@abienz this is not yet published on npm, it’s already in the master branch however

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by abienz** [comment]
@DeMoorJasper Thanks for the update, I look forward to seeing the update.
