### ISSUE TITLE
URL in inline styles isn't rewritten (but the image is still copied).

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5706]
# 🐛 bug report

`url()`s in inline style attributes aren't rewritten. But the referenced file is correctly copied.

## 🤔 Expected Behavior

```html
<figure style="background-image: url('MVC.ebb30ebb.png')"></figure>
```

## 😯 Current Behavior

Input = Output

## 💻 Code Sample

index.html:

```html
<figure style="background-image: url('images/MVC.png')"></figure>
```

(and such an image)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 6d9e3901e213ebd1932d69eb0587d219033f1da7

**Comment by ProLoser** [comment]
You could import the asset url and then pass it as a string, no?

```
import mvcPng from './images/MVC.png'
// ...

<figure style={`background-image: url('${mvcPng}')`} />
```

This seems a more explicit way to tell parcel to process this asset rather than the complexity that would be involved with having parcel recognize inline react javascript css

**Comment by mischnic** [comment]
This is HTML, not JSX 😉

**Comment by ProLoser** [comment]
Oh hah touche i will stop commenting on random tickets lol

**Comment by mischnic** [comment]
Actually a duplicate of https://github.com/parcel-bundler/parcel/issues/5475...
