### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by Niggler** [parcel-bundler/parcel#571]
There have been some great fixes in the last few weeks since the 1.4.1 release.  When will the next version be released?

**Comment by dmitry-vakhnenko** [comment]
Guys, thanks for awesome tool! :100: 

But really, when will the next version? I can't use master on my productions :-(

**Comment by DeMoorJasper** [comment]
Very soon!

**Comment by devongovett** [comment]
Aiming for early next week. Sorry, I've been insanely busy at work lately. :)
