### ISSUE TITLE
await img.decode(); broken for local files

### ISSUE THREAD

**Issue by TonySpegel** [parcel-bundler/parcel#5711]
# 🐛 bug report

When trying to decode a local file using the asynchronous method `img.decode()` browsers throw an error in both dev and build mode, Chrome says `Uncaught (in promise) DOMException: The source image cannot be decoded.` and firefox `Uncaught (in promise) DOMException: Invalid encoded image data.` but the image data is fine and it's actually working when using a URL instead. It's also working when applied to a plain HTML file without using Parcel at all.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
    "name": "pineapple-paint",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
        "dev": "parcel index.html",
        "build": "parcel build index.html"
    },
    "author": "Tony Spegel",
    "license": "ISC",
    "devDependencies": {
        "parcel-bundler": "^1.12.4",
        "sass": "^1.32.5"
    },
    "browserslist": [
        "last 1 Chrome versions"
    ]
}
```
## 🤔 Expected Behavior

Being able to decode local images

## 😯 Current Behavior

Full error:
```bash
(index):14 Uncaught (in promise) DOMException: The source image cannot be decoded.
(anonymous) @ (index):14
async function (async)
(anonymous) @ (index):12
(anonymous) @ (index):14
```
## 🔦 Context
I'm trying to load an image to display it in a canvas later on, while trying so I wanted to use `img.decode()` which will return a promise when a browser has fully decoded an image.

## 💻 Code Sample
This does not work:
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <script>
            (async () => {
                const img = new Image();
                img.src = './assets/gray.png';
                await img.decode();

                console.log(`width: ${img.width}, height: ${img.height}`);
            })();
        </script>
    </body>
</html>
```
Test image created in Kolourpaint, but any image will do
![gray](https://user-images.githubusercontent.com/1145514/105777596-f36b4e00-5f6a-11eb-91f1-68e9eb15f896.png)

This does work:
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <script>
            (async () => {
                const img = new Image();
                img.src = 'https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png';
                await img.decode();

                console.log(`width: ${img.width}, height: ${img.height}`);
            })();
        </script>
    </body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4
| Node             | v15.5.1
| npm/Yarn         | npm
| Operating System | KDE Neon 5.20.5 Ubuntu 20.04

**Comment by mischnic** [comment]
The image file isn't copied into the dist directory because Parcel doesn't recognize that's used.

You can do something like `import imageURL from './test.png'` as described here: https://parceljs.org/javascript.html

**Comment by TonySpegel** [comment]
Okay I understand, thank you for your help! But why doesn't it know? I know it's probably not how it works but isn't `const img = new Image();` enough to tell Parcel that here should be an image to copy to? Or rather, shouldn't it copy any images in my asset folder anyway?

We can close this but maybe you could give me some more insights before that :)

**Comment by mischnic** [comment]
In this example, it would be possible to add support. But what if your code looks like this?
```js
async function load(src){
	const img = new Image();
	img.src = src;
	await img.decode();
	return img;
}

load('./assets/gray.png')
```
It becomes exceedingly difficult to statically determine which files are needed.

> Or rather, shouldn't it copy any images in my asset folder anyway?

No, this is not how Parcel works. The files are also renamed to include a hash for cache busting. So the JS file needs to know the resulting name as well

**Comment by TonySpegel** [comment]
I see, thank you. Have a nice day :)

Closed
