### ISSUE TITLE
firebase.firestore doesn't work from parcel@2.0.0-nightly.485

### ISSUE THREAD

**Issue by zanona** [parcel-bundler/parcel#5718]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "foo",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "firebase": "8.2.4",
    "parcel": "2.0.0-nightly.485"
  }
}
```

## 🤔 Expected Behavior

`firebase.firestore().collection('foobar')` should be invoked without returning any errors

## 😯 Current Behavior

`firebase.firestore().collection('foobar')` throws error

```
14:50:55.815 Uncaught TypeError: this.segments.slice is not a function
    rt prebuilt.js:1105
    ot prebuilt.js:1129
    toString prebuilt.js:1132
    Rs prebuilt.js:14145
    Hs prebuilt.js:14492
    collection prebuilt.js:17320
    ["5WHjR"]< index.js:6
    newRequire index.77429590.js:69
    <anonymous> index.77429590.js:118
    <anonymous> index.77429590.js:141
prebuilt.js:1105:29
    rt prebuilt.js:1105
    ot prebuilt.js:1129
    toString prebuilt.js:1132
    Rs prebuilt.js:14145
    Hs prebuilt.js:14492
    collection prebuilt.js:17320
    ["5WHjR"]< index.js:6
    newRequire index.77429590.js:69
    <anonymous> index.77429590.js:118
    <anonymous> index.77429590.js:141
```

## 🔦 Context

When using `parcel@2.0.0-nightly.481` (last available prior `485`), the problem doesn't occur.
I was looking into using the latest features of parcel _(.i.e: postcss 8)_ while keep using firebase.

#### index.html
```html
<!doctype html>
<script src="./index.js"></script>
```

#### index.js
```js
import firebase from 'firebase/app';
import 'firebase/firestore';

firebase.initializeApp({projectId: 'foo'});

firebase.firestore().collection('foobar');
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0@nightly.485
| Node             | 15.7.0
| npm/Yarn         | 6.14.11
| Operating System | linux

**Comment by mischnic** [comment]
> Code Sample

That doesn't throw an error for me. Neither with the latest nightly nor 485.

**Comment by zanona** [comment]
Hi, @mischnic, are you sure?
I just launched an empty node docker image and ran the below, getting an error under `localhost:1234`

```sh
docker run -it -p 1234:1234 node:alpine sh
```

## throws (485)
> Uncaught TypeError: this.segments.slice is not a function
```sh
cd ~/
npm i parcel@2.0.0-nightly.485 firebase@8.2.4
printf '<!doctype html>\n<script src="./index.js"></script>' > index.html
printf "import firebase from 'firebase/app';\nimport 'firebase/firestore';\nfirebase.initializeApp({projectId: 'foo'});\nfirebase.firestore().collection('foobar');" > index.js
./node_modules/.bin/parcel serve --port 1234 index.html
```
## ok (481)
> empty console output
```sh
cd ~/
npm i parcel@2.0.0-nightly.481 firebase@8.2.4
printf '<!doctype html>\n<script src="./index.js"></script>' > index.html
printf "import firebase from 'firebase/app';\nimport 'firebase/firestore';\nfirebase.initializeApp({projectId: 'foo'});\nfirebase.firestore().collection('foobar');" > index.js
./node_modules/.bin/parcel serve --port 1234 index.html
```

**Comment by mischnic** [comment]
Ah, I was trying `parcel build index.html`, but this only happens without scopehoisting (watch mode or `--no-scope-hoist`).

**Comment by mischnic** [comment]
Reproduction:
```js
// a.js
import { f } from "./b.js";
(function () {
	for (var f = [], i = 0; i < 10; i++) { // f is imported and also locally declared inside the loop head!
		f[i] = i;
	}

	console.log(f);
})();

// b.js
export const f = 123;
```

**Comment by zanona** [comment]
Awesome, thanks for pointing that out and sorry I forgot to add the running command on the initial report.
Hopefully we will be able to get this functionality back on a future release?
