### ISSUE TITLE
Can't build when browserslist excludes ie

### ISSUE THREAD

**Issue by ProLoser** [parcel-bundler/parcel#5724]
# 🐛 bug report

I am getting an error with parcel nightly whenever I `parcel build`. Doing `parcel serve --no-hmr` works without error.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// package.json
...
  "browserslist": {
    "production": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
...
```

## 🤔 Expected Behavior

I should be able to build without targetting IE.

## 😯 Current Behavior

```
yarn run v1.22.10
$ yarn workspace browser build
$ parcel build ./src/index.html
🚨 Build failed.
@parcel/transformer-babel: [BABEL] /Users/dsofer/Sites/zeus/packages/browser/src/index.js: Write any browsers query (for instance, `defaults`) before `not ie <= 11` (While processing: "/Users/dsofer/Sites/zeus/node_modules/@babel/preset-env/lib/index.js")
BrowserslistError: [BABEL] /Users/dsofer/Sites/zeus/packages/browser/src/index.js: Write any browsers query (for instance, `defaults`) before `not ie <= 11` (While processing: "/Users/dsofer/Sites/zeus/node_modules/@babel/preset-env/lib/index.js")
    at /Users/dsofer/Sites/zeus/node_modules/browserslist/index.js:324:15
    at Array.reduce (<anonymous>)
    at resolve (/Users/dsofer/Sites/zeus/node_modules/browserslist/index.js:318:18)
    at browserslist (/Users/dsofer/Sites/zeus/node_modules/browserslist/index.js:444:21)
    at getTargets (/Users/dsofer/Sites/zeus/node_modules/@babel/helper-compilation-targets/lib/index.js:204:48)
    at /Users/dsofer/Sites/zeus/node_modules/@babel/preset-env/lib/index.js:258:57
    at /Users/dsofer/Sites/zeus/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at /Users/dsofer/Sites/zeus/node_modules/@babel/core/lib/config/full.js:211:14
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/Users/dsofer/Sites/zeus/node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/dsofer/.nvm/versions/node/v14.15.2/bin/node
Arguments: /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js build
Directory: /Users/dsofer/Sites/zeus/packages/browser
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This works perfectly fine when running `parcel serve ./src/index.html --no-hmr`

## 💁 Possible Solution

I'm not sure how to fix this. I upgraded to parcel nightly because of #5021 

## 🔦 Context

I have just been relying on evergreen javascript and have been trying to avoid custom transpilers and babel configurations.

## 💻 Code Sample

There are no other custom configurations, the source code is all vanilla JS and JSX (React).  We are trying to use only evergreen features and cannot support older / other browsers.

## 🌍 Your Environment

Browser, webworker.

Was originally having problems with webworkers but now that I've upgraded to nightly this problem occurs during a build at the entrypoint file.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |parcel@2.0.0-nightly.553
| Node             |v14.15.2
| npm/Yarn         |6.14.9 / 1.22.10
| Operating System |OSX 10.15.7

**Comment by mischnic** [comment]
We aren't properly normalizing this syntax here: https://github.com/parcel-bundler/parcel/blob/b70830daef0c5673c4974c8f7de72c4ec2a7517a/packages/core/core/src/requests/TargetRequest.js#L292

and then this invalid value flows all the way through to the default babel presets we add

This should instead use `options.mode` to select the right value from the object

**Comment by ProLoser** [comment]
I got rid of the `production` and `development` keys and it fixed my problem.

**Comment by ProLoser** [comment]
Man I am having trouble figuring out what's going on. I'm seeing a new bug in build only:

`:1234/index.296122a4.js:1154 Uncaught SyntaxError: Identifier 'eT' has already been declared`

**Comment by mischnic** [comment]
You were simply using a browserslist-variant that wasn't handled correctly by Parcel. I've opened a PR already: https://github.com/parcel-bundler/parcel/pull/5726
