### ISSUE TITLE
"@parcel/transformer-typescript-types: Got unexpected undefined" on parcel@2.0.0-nightly.554

### ISSUE THREAD

**Issue by jeffpeck10x** [parcel-bundler/parcel#5735]
I saw this issue reported here:
https://github.com/parcel-bundler/parcel/issues/4035

But I think this case is different.

This is the full error message:
```
yarn workspace v1.22.10
yarn run v1.22.10
$ parcel build ./src/index.ts
🚨 Build failed.
@parcel/transformer-typescript-types: Got unexpected undefined
Error: Got unexpected undefined
    at nullthrows (/path-to-project/node_modules/nullthrows/nullthrows.js:7:15)
    at Object.transform (/path-to-project/node_modules/@parcel/transformer-typescript-types/lib/TSTypesTransformer.js:204:42)
    at async runTransformer (/path-to-project/node_modules/@parcel/core/lib/Transformation.js:651:3)
    at async Transformation.runPipeline (/path-to-project/node_modules/@parcel/core/lib/Transformation.js:422:36)
    at async Transformation.runPipelines (/path-to-project/node_modules/@parcel/core/lib/Transformation.js:363:40)
    at async Transformation.run (/path-to-project/node_modules/@parcel/core/lib/Transformation.js:277:19)
    at async Child.handleRequest (/path-to-project/node_modules/@parcel/workers/lib/child.js:255:9)
```

when I run `yarn build`.

Here is the relevant part of my package.json
```
  "type": "module",
  "main": "dist/main/index.js",
  "types": "dist/index.d.ts",
  "scripts": {
    "build": "parcel build ./src/index.ts",
    "dev": "parcel watch ./src/index.ts"
  }
```

I will add that this was all working 100% less than 24 hours ago. I have the dependency of `"parcel": "^2.0.0-beta.1"`, which is pulling `parcel@2.0.0-nightly.554`. I cannot confirm whether it was pulling that same version earlier this morning or yesterday, but it looks like that has been the latest release for about three days now, so I am pretty sure that hasn't changed.

EDIT:

One thing that works is if I turn off types and reference a manually written types declaration:
```
  "types": "index.d.ts",
  "targets": {
    "types": false
  },
  ```
  
But, it definitely worked without having to do this just this morning and yesterday, so I am not sure how this might be related.

Parcel seems like an awesome project and I really want to use it, so I would appreciate any help with this.

## 🤔 Expected Behavior

The project builds every time, even without `types: false`

## 😯 Current Behavior

The project does not build. This behavior started some time within the last 16 hours or so.

## 💻 Code Sample

I can try to put together a small project that reproduces the error if need be, although I would first like to see if this issue seems familiar to anyone here and if there are some things that I can try.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  parcel@2.0.0-nightly.554
| Node             | v12.20.1
| npm/Yarn         | yarn 1.22.10
| Operating System | MacOS 10.15.7

**Comment by jeffpeck10x** [comment]
Hrm, I added a `babel.config.json`:
```
{ 
  "presets": ["@babel/preset-typescript"]
}
```

and that seems to have fixed it.

This is my package.json:
```
  "main": "dist/main/index.js",
  "types": "dist/index.d.ts",
  "scripts": {
    "build": "parcel build ./src/index.ts",
    "dev": "parcel watch ./src/index.ts"
  },
  ```
  
  I am double-checking. But, that may have been the issue.
  
  Although, it still doesn't explain why it was working last night and this morning without that.

**Comment by jeffpeck10x** [comment]
I take that back.

It does work, yet I push my code, and then clone it to a new directory, and it is back to the same error.

It seems non-deterministic at this point. I am curious if there are any suggestions. Thanks.

**Comment by mischnic** [comment]
> I can try to put together a small project that reproduces the error if need be

That would be great. I'm not aware of any current bugs in the types transformer.

**Comment by jeffpeck10x** [comment]
So... in the process of making this into a smaller project that reproduces the error, I found several things that needed to be cleaned.

Everything is now working, but I cannot say for sure what exactly "fixed" it, especially since even while having this issue, it seemed to _sometimes_ build even without "fixing" anything.

I even tried reintroducing the things that were "wrong" in the original project (like a `.d.ts` file that was importing a nonexistent module), but my test project still builds, even after deleting `.parcel-cache`.

I would still consider this to be a bug, as the problem is ultimately that this error message did not contain any helpful information:
```
@parcel/transformer-typescript-types: Got unexpected undefined
```

Still, the fact that I cannot seem to pinpoint what the problem is means that it would be impossible to look into any further.

I think this can be closed, and if this comes up again in some easily repeatable way, I will create a new issue for it.

**Comment by mischnic** [comment]
> this error message did not contain any helpful information:

It's really an internal assertion. This isn't an error where some configuration is wrong (or a syntax error...) but because there's a bug in Parcel 😄

**Comment by jeffpeck10x** [comment]
That is reassuring. Thank you, really just affirm that this error was _possibly_  not on my end is a huge help.

Again, I wish I could have provided a clear way to reproduce it, but I'll be on the lookout for it to come up again.

**Comment by Banou26** [comment]
This issue is still present for me.

I get the same exact error(`@parcel/transformer-typescript-types: Got unexpected undefined`) with a `500` nightly build on Parcel.

But on a `600`-`700` nightly build, i get those errors instead
```
@parcel/transformer-typescript-types: Cannot find global value 'Promise'.      

@parcel/transformer-typescript-types: Cannot find module '@mfkn/oz-web/src/api/api' or its corresponding type declarations.

@parcel/transformer-typescript-types: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.

  C:/dev/oz/lib/src/index.ts:27:38
    26 | if (window.parent !== window) {
  > 27 |   window.addEventListener('message', async ev => {
  >    |                                      ^^^^^^^^^^^^^^ An async function 
or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a 
declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.
    28 |     const { data: messageData, origin }: { data: ApiMessageData } & Om    29 |

```
Even though running `tsc` returns `Found 0 errors.`

**Comment by kamontat** [comment]
I found out that if you run parcel from typescript file that not export any module but on **package.json** it contain `"type": module` or `"module": "<path>"` it will fail with this error when you have `"types": "<path>"`

Example: You can try create new repository which contain 1 file, that file contain single line of code `console.log('hello world')` and run `parcel build` with `"type": "module"` in **package.json**.

**Comment by tripolskypetr** [comment]
Double check your `tsconfig.json` for `"isolatedModules": true`

```tsx
import { myAmazingType as myAmazingTypeInternal } from "./types";
export type myAmazingType = myAmazingTypeInternal;
```
If so, disable this flag and rewrite library exports

```tsx
export{ myAmazingType } from "./types";
```

**Comment by alexkreidler** [comment]
> I found out that if you run parcel from typescript file that not export any module but on **package.json** it contain `"type": module` or `"module": "<path>"` it will fail with this error when you have `"types": "<path>"`

Yeah I had this issue: `@parcel/transformer-typescript-types: Got unexpected null`, but removed the `types` target from my package.json and it `Built in 394ms` successfully. It would be great to also be able to generate typedefs.

**Comment by mischnic** [comment]
This usually happens because there is some TS error during compilation but Parcel doesn't forward the error message. https://github.com/parcel-bundler/parcel/pull/8914 will fix at least that part

**Comment by FSPinho** [comment]
I'm still experiencing this today. In case someone has the same, my problem was that some TS files had no export.
