### ISSUE TITLE
WebP image generation fails on V2

### ISSUE THREAD

**Issue by ivoba** [parcel-bundler/parcel#5742]
# 🐛 bug report

WebP images are not created, when i follow the instructions on https://v2.parceljs.org/recipes/image/

## 🎛 Configuration (.babelrc, package.json, cli command)
I added sharp and @parcel/transformer-image:
```
 "devDependencies": {
    "@fortawesome/fontawesome-free": "^5.15.2",
    "@parcel/transformer-image": "^2.0.0-nightly.1981",
    "@parcel/transformer-typescript-tsc": "^2.0.0-alpha.3",
    "bootstrap": "^4.6.0",
    "cssnano": "^4.1.10",
    "parcel": "2.0.0-beta.1",
    "sass": "^1.32.5",
    "sharp": "^0.27.1"
  },
```
I also noticed that transformer-image is not added to default config. So i added .parcelrc:

```
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{png,jpg,jpeg}": ["@parcel/transformer-image"]
  }
}
```
index.html:

```
<picture>
            <source src="url:./img/ivos_ecotainment_newsletter.png?as=webp&width=350" type="image/webp" />
            <img src="url:./img/ivos_ecotainment_newsletter.png?width=350" alt="Ivo's Ecotainment Newsletter" width="350px" height="263px"/>
</picture>
```

## 🤔 Expected Behavior

WebP image should be generated.

## 😯 Current Behavior

But on npm start i get:

```
TypeError: Cannot read property 'map' of undefined
    at normalizeAssets (/home/ivo/Sites/eco.ivo/node_modules/@parcel/core/lib/Transformation.js:516:30)
    at runTransformer (/home/ivo/Sites/eco.ivo/node_modules/@parcel/core/lib/Transformation.js:471:23)
    at async Transformation.runPipeline (/home/ivo/Sites/eco.ivo/node_modules/@parcel/core/lib/Transformation.js:257:36)
    at async Transformation.runPipelines (/home/ivo/Sites/eco.ivo/node_modules/@parcel/core/lib/Transformation.js:193:40)
    at async Transformation.run (/home/ivo/Sites/eco.ivo/node_modules/@parcel/core/lib/Transformation.js:111:19)
    at async Child.handleRequest (/home/ivo/Sites/eco.ivo/node_modules/@parcel/workers/lib/child.js:165:9)
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | v12.20.1
| npm/Yarn         | 6.14.10
| Operating System | Ubuntu 18

**Comment by mischnic** [comment]
Try with the latest nightly.

> I also noticed that transformer-image is not added to default config

It is. You don't need that config file.

**Comment by ivoba** [comment]
Confirmed. Works with latest nightly.

My upgrade path:

```
npm uninstall parcel-bundler
rm -rf node_modules package-lock.json
npm install sharp parcel@^2.0.0-nightly -D
```
Got bitten by https://github.com/parcel-bundler/parcel/issues/4064 but `rm -rf node_modules package-lock.json` solved it.

Thank you +1
