### ISSUE TITLE
incorrect bundle type inferred from target

### ISSUE THREAD

**Issue by herobank110** [parcel-bundler/parcel#5743]
# 🐛 bug report

Target in package.json specifying output file causing incorrect bundle type to be inferred.

## 🎛 Configuration

.babelrc
```js
{
    "plugins": [
        [
            "@babel/plugin-transform-typescript",
            {
                "allowNamespaces": true
            }
        ]
    ]
}
```

package.json
```json
{
    # ...
    "scripts": {
        # ...
        "build-dev-watch": "concurrently \"tsc --inlineSourceMap -w\" \"parcel watch --target=clientSide index.html\"",
    },
    "clientSide": "build/clientSide/index.html",
    "targets": {
        "clientSide": {
            "context": "browser",
            "outputFormat": "global"
        }
    },
    "devDependencies": {
        # ...
        "concurrently": "^5.3.0",
        "parcel": "^2.0.0-nightly.560",
        "sass": "^1.32.5",
        "typescript": "^4.1.3"
    }
}
```
(The first tsc script is for nodejs server side code. I had trouble using multiple targets for parcel but I think it by design uses the same entry point for each target.)

cli command
```
npm run build-dev-watch
```

## 🤔 Expected Behavior

Compiled bundle type should be HTML probably since the input file was index.html. This error did not occur in parcel@2.0.0-beta.1.

## 😯 Current Behavior

```
Bundling...
× Build failed.
@parcel/namer-default: Target "clientSide" declares an output file path of "buildclientSideindex.html" which does not match the compiled bundle type "webmanifest".
C:\Users\d3\Documents\WebProjects\d3-web-remote\package.json:20:19
   19 |     },
 > 20 |     "clientSide": "build/clientSide/index.html",
 >    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Did you mean "build\clientSide\index.webmanifest"?
   21 |     "targets": {
   22 |         "clientSide": {
Try changing the file extension of "clientSide" in package.json.
```

## 🔦 Context

Trying to bundle up client side typescript and sass code with a html entry point. The html linked to a webmanifest which should be included in the build but not fundamentally affect the output type.
Then changing the clientSide as it instructs to "build\clientSide\index.webmanifest", results in the opposite error, it says it's an html bundle and I should call the output "build\clientSide\index.html". Changing it back brings the first error again.

## 💻 Code Sample

index.html
```html
# ...
<head>
    # ...
    <script src="src/clientSide/index.ts"></script>
    <link rel="stylesheet" href="res/style.scss">
    <link rel="manifest" href="manifest.webmanifest">
    <link rel="icon" href="res/icon/favicon-96x96.png" sizes="96x96" type="image/png">
</head>
# ...
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.560
| Node             | v14.8.0
| npm/Yarn         | 6.14.7
| Operating System | Windows 10 v10.0.14393 Build 14393

**Comment by mischnic** [comment]
`"clientSide": "build/clientSide/index.html",` is correct. This is a bug

**Comment by folknor** [comment]
[Reduced test case attached.](https://github.com/parcel-bundler/parcel/files/5947191/testing.zip)

Removing the line `<link rel="manifest" href="manifest.json">` from `index.html` "fixes" the problem.

**Comment by AndKenneth** [comment]
Does anyone have any tips about how to get around this? Is there a way I can serve the web manifest as a static file instead?

**Comment by mischnic** [comment]
`<link rel="manifest" href="url:manifest.webmanifest">` might work

**Comment by AndKenneth** [comment]
I seem to have solved this by just removing `main` from package.json. this seems fine for now but I'm not sure if there might be any side effects of that.

**Comment by folknor** [comment]
> `<link rel="manifest" href="url:manifest.webmanifest">` might work

Still errors on latest nightly:
```
🚨 Build failed.
@parcel/namer-default: Target "web" declares an output file path of "dist/www/index.html" which does not match the compiled bundle type "webmanifest".
/.../package.json:24:9
  23 |   "source": "index.html",
> 24 |   "web": "./dist/www/index.html",
>    |          ^^^^^^^^^^^^^^^^^^^^^^^ Did you mean "dist/www/index.webmanifest"?
  25 |   "targets": {
  26 |     "web": {
```

**Comment by temetvince** [comment]
Still errors
