### ISSUE TITLE
Uncaught ReferenceError: globalThis is not defined

### ISSUE THREAD

**Issue by aminya** [parcel-bundler/parcel#5746]
# 🐛 bug report

Compiling a package with Node (or Electron-renderer) context and using it triggers this error in some cases.

```
ReferenceError: globalThis is not defined
    at /packages/linter-ui-default/dist/index.js:1:7989
    at Se (/packages/linter-ui-default/dist/index.js:1:8142)
    at oi (/packages/linter-ui-default/dist/index.js:1:44368)
    at _e (/packages/linter-ui-default/dist/index.js:1:15274)
    at _e (/packages/linter-ui-default/dist/index.js:1:7948)
    at st (/packages/linter-ui-default/dist/index.js:1:15266)
    at Qn.e.forEach.e (/packages/linter-ui-default/dist/index.js:1:83011)
    at Array.forEach (<anonymous>)
    at /packages/linter-ui-default/dist/index.js:1:82976)
    at mn.updateTooltip (/packages/linter-ui-default/dist/index.js:1:89363)
    at textEditor.onDidChangeCursorPosition (/packages/linter-ui-default/dist/index.js:1:88651)
    at /packages/linter-ui-default/dist/index.js:1:41580)
    at /packages/linter-ui-default/dist/index.js:1:41857)
    at /packages/linter-ui-default/dist/index.js:1:41746)
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
  "engines": {
    "atom": ">=1.19.0 <2.0.0",
    "electron": ">=5.x"
  },
  "targets": {
    "main": {
      "context": "node",
      "includeNodeModules": {
        "atom": false,
        "electron": false,
        "atom-package-deps": false,
        "disposable-event": false
      },
      "outputFormat": "commonjs",
      "isLibrary": true
    }
  },
```
```
    "build": "cross-env NODE_ENV=production parcel build --target main ./lib/index.ts",
```

## 🤔 Expected Behavior
globalThis should not be needed?

## 😯 Current Behavior
Parcel generates `globalThis`

## 💁 Possible Solution
Use unbundled JS

## 🔦 Context
https://github.com/steelbrain/linter-ui-default/issues/617

## 💻 Code Sample
https://github.com/steelbrain/linter-ui-default

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | "parcel": "2.0.0-nightly.562",
| Node             | 12
| npm/Yarn         | 6
| Operating System | win 10

**Comment by aminya** [comment]
My raw JS does not work. I have downgraded Parcel to some old version to see if this fixes the error :( 
Not sure where this error has come from

**Comment by mischnic** [comment]
So `2.0.0-nightly.440` transpiles globalThis? It doesn't for me...

**Comment by mischnic** [comment]
But something funky is going on here:

`global` and `"engines": {"node": ">= 10"}` and `--no-scope-hoist`: unchanged
`global` and no engines and `--no-scope-hoist`: transpiled
`globalThis` and `"engines": {"node": ">= 10"}` and `--no-scope-hoist`: unchanged
`globalThis` and no engines and `--no-scope-hoist`: unchanged

`global` and no engines and scope hoisting: transpiled
`global` and `"engines": {"node": ">= 10"}` and scope hoisting: transpiled
`globalThis` and no engines and scope hoisting: unchanged
`globalThis` and `"engines": {"node": ">= 10"}` and scope hoisting: unchanged

**Comment by aminya** [comment]
No, I thought it is because of the Parcel version. This seems to be caused by solid-js, which uses `globalThis` somewhere in the code.
https://github.com/ryansolid/solid/search?q=globalThis

**Comment by mischnic** [comment]
Ah, so downgrading didn't fix the error

**Comment by aminya** [comment]
No, it did not. Should I open an issue for solid too? or this is just a Parcel issue?

**Comment by mischnic** [comment]
`globalThis` is modern JS, we just never updated the code for the `global` variable to also apply to `globalThis`.

**Comment by mischnic** [comment]
Because `globalThis` works fine with Node 12+. It's probably a older version in your situation.

**Comment by aminya** [comment]
Oh, right! I just checked the issue report and they are using an old Atom version that used Node 10. 🙅🏻

**Comment by aminya** [comment]
Interestingly, using `babel-plugin-transform-globalthis` in the plugins entry does not fix the error. I had to run babel on the output of Parcel
```
    "babel.globalThis": "babel dist --out-dir dist --plugins babel-plugin-transform-globalthis --retain-lines",
```

https://github.com/steelbrain/linter-ui-default/pull/618

**Comment by mischnic** [comment]
The custom babel config (so `babel-plugin-transform-globalthis`) is not applied to node_modules. Does that explain what you're seeing?

**Comment by aminya** [comment]
Removing `"exclude": "node_modules/**"` from babel.config.json does not fix the issue. But yes, that is probably because of what you are saying.

**Comment by mischnic** [comment]
Parcel still excludes node_modules then 😬

**Comment by mischnic** [comment]
I'm also somewhat surprised that `@babel/preset-env` doesn't handle globalThis...

**Comment by aminya** [comment]
Yes. I agree. This seems strange. Does Parcel run babel on the output bundle?

**Comment by mischnic** [comment]
TIL: preset-env doesn't really transpile API, only syntax. So we should transpile `globalThis` ourselves just like `global` (but probably only when it's unsupported)

**Comment by aminya** [comment]
This seems to be fixed in the recent versions. Is it? 

See this:
https://github.com/steelbrain/linter-ui-default/pull/647#issuecomment-864841118
