### ISSUE TITLE
Parcel 2 improperly serves entry files named other than index.html

### ISSUE THREAD

**Issue by avalanche1** [parcel-bundler/parcel#5752]
# 🐛 bug report

Parcel 2 improperly serves entry files named other than index.html.
If I run cli with `parcel src/entry/popup/popup.html --open`
Shows 404 Not found instead of åctual html.

If I rename popup.html to index.html and then run cli with `parcel src/entry/popup/index.html --open` - all is good.
## 🎛 Configuration (.babelrc, package.json, cli command)

```js
.babelrc - I dont have
.parcelrc:
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
}

```

## 🤔 Expected Behavior
Should accept any entry file name

## 😯 Current Behavior
See bug description.

## 🔦 Context
Just building a simple html.

## 💻 Code Sample
src/entry/popup/popup.html
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title></title>
  </head>
  <body>
    <div id="ExtnPopup">This is the popup UI</div>

    <script src="./popup.ts"></script>
  </body>
</html>
```
src/entry/popup/popup.ts
```
// empty
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  ^2.0.0-nightly.562
| Parcel           |   ^2.0.0-beta.1

**Comment by mischnic** [comment]
Relevant code for determining what to server on `localhost:1234`: https://github.com/parcel-bundler/parcel/blob/5d9143b752614c7719735b7862a0f636136e98a5/packages/reporters/dev-server/src/Server.js#L151-L169

**Comment by MaffooBristol** [comment]
I had this same regression with Parcel 2. I simply added a plugin which would rewrite the output:

```
npm install -D parcel-namer-rewrite
```

### .parcelrc
```
{
  "extends": "@parcel/config-default",
  "namers": ["parcel-namer-rewrite"]
}
```

### package.json
```
  "parcel-namer-rewrite": {
    "rules": {
      "popup.html": "index.html"
    }
  }
```

**Comment by avalanche1** [comment]
That's a workaround; we need a fix.

**Comment by avalanche1** [comment]
NOT FIXED in `^2.0.0-nightly.579`

**Comment by avalanche1** [comment]
Moreover, it turns out you cannot call chrome extn popup html file `index.html`!!!
Weirdly, it will show this broken page:
![image](https://user-images.githubusercontent.com/10534563/107552528-adf28600-6be4-11eb-8ee6-43f5568af32e.png)
So, guys, plz fix.

**Comment by mischnic** [comment]
> If I run cli with parcel src/entry/popup/popup.html --open
> Shows 404 Not found instead of actual html.

That works correctly for me with `2.0.0-nightly.579`.
