### ISSUE TITLE
Parcel 2: transformer-typescript-tsc not respected during build

### ISSUE THREAD

**Issue by avalanche1** [parcel-bundler/parcel#5761]
# 🐛 bug report

Although, I have transformer-typescript-tsc set up in `.parcelrc` - it looks like the code is still being piped through Babel.
I am calling a top-level `await`. Clearly, Babel doesn't support that out of the box, while TS 4.1 does.

## 🎛 Configuration (.babelrc, package.json, cli command)

`.parcelrc`:
```
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
}
```
`.package.json`:
```
    "parcel": "^2.0.0-nightly.566",
    "typescript": "^4.1.3"
```

## 😯 Current Behavior
I get this console error
```
🚨 Build failed.
@parcel/transformer-babel: 'await' is only allowed within async functions (4:12)
SyntaxError: 'await' is only allowed within async functions (4:12)
    at Object._raise (/Users/Kat/Documents/Travail_code/WebDev/21-02_Smart-Scanner/node_modules/@babel/parser/lib/index.js:748:17)
    at Object.raiseWithData (/Users/Kat/Documents/Travail_code/WebDev/21-02_Smart-Scanner/node_modules/@babel/parser/lib/index.js:741:17)
    at Object.raise (/Users/Kat/Documents/Travail_code/WebDev/21-02_Smart-Scanner/node_modules/@babel/parser/lib/index.js:735:17)
    at Object.checkReservedWord (/Users/Kat/Documents/Travail_code/WebDev/21-02_Smart-Scanner/node_modules/@babel/parser/lib/index.js:11386:14)
    at Object.parseIdentifierName (/Users/Kat/Documents/Travail_code/WebDev/21-02_Smart-Scanner/node_modules/@babel/parser/lib/index.js:11350:12)
    at Object.parseIdentifier (/Users/Kat/Documents/Travail_code/WebDev/21-02_Smart-Scanner/node_modules/@babel/parser/lib/index.js:11317:23)
    at Object.parseExprAtom (/Users/Kat/Documents/Travail_code/WebDev/21-02_Smart-Scanner/node_modules/@babel/parser/lib/index.js:10408:27)
    at Object.parseExprAtom (/Users/Kat/Documents/Travail_code/WebDev/21-02_Smart-Scanner/node_modules/@babel/parser/lib/index.js:4763:20)
    at Object.parseExprSubscripts (/Users/Kat/Documents/Travail_code/WebDev/21-02_Smart-Scanner/node_modules/@babel/parser/lib/index.js:10150:23)
    at Object.parseUpdate (/Users/Kat/Documents/Travail_code/WebDev/21-02_Smart-Scanner/node_modules/@babel/parser/lib/index.js:10130:21)
/Users/Kat/Documents/Travail_code/WebDev/21-02_Smart-Scanner/src/entry/popup/popup.ts:4:12
  3 | const foo = (bar) => (bar ? bar + "  ikki" : 1);
> 4 | console.log(await browser.storage.local.get());
>   |            ^
  5 | //# sourceMappingURL=popup.js.map
```

## 🤔 Expected Behavior

Obviously, compile w\o errors; using `tsc`.

## 💻 Code Sample

`popup.ts`:
```ts
import {browser} from "webextension-polyfill-ts";
import "./popup.sass";

const foo = (bar?: string): number | string => (bar ? bar + "  ikki" : 1);
console.log(await browser.storage.local.get());
```

**Comment by mischnic** [comment]
This should work:
```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"],
    "*.{js,mjs,jsm,jsx,es6,cjs}": ["@parcel/transformer-js"]
  }
}
```

**Comment by avalanche1** [comment]
Nope
```
🚨 Build failed.
@parcel/transformer-js: 'await' is only allowed within async functions (3:12)
```

**Comment by mischnic** [comment]
I'm afraid TLA isn't support at the moment: https://github.com/parcel-bundler/parcel/issues/4028

**Comment by danieltroger** [comment]
@mischnic why is TLA so complicated? Parcel wraps all code into a `(function(){code})()`, all it has to do is wrap it into `(async function(){code})()` instead, or am I missing something?

**Comment by avalanche1** [comment]
A pity about TLA.
Although, my initial issue is with .ts code being handled by Babel.

**Comment by mischnic** [comment]
@danieltroger -> https://github.com/parcel-bundler/parcel/issues/4028#issuecomment-772529210

@avalanche1 tsc did run in your case, it's just that Babel also ran after that. I guess that's unexpected?

**Comment by avalanche1** [comment]
It is not. Is that by design? Seems like a redundant iteration (from a user standpoint).

**Comment by mischnic** [comment]
One thing that the tsc transformer doesn't do is applying the browserslist config (= what babel-preset-env does)

**Comment by avalanche1** [comment]
1. Can we opt out of running Babel if we dont have `browserslist` entry in `package.json`?
2. Parcel 1 doesnt have this issue and runs TS seamlessly out of the box? Can we not have that seamless experience in V2?

**Comment by mischnic** [comment]
1. That is already the case
2. TS works out of the box already (with Babel). See https://github.com/parcel-bundler/parcel/issues/4938 for whether TSC should be used by default

**Comment by danieltroger** [comment]
> Parcel 1 doesnt have this issue and runs TS seamlessly out of the box? Can we not have that same seamless experience in V2?

Can you elaborate why you want tsc? I'm curious lol.

Imo it is buggy and I don't like its philosophy of "you have to configure it with some options you can never guess or it will transpile your code wrong". I switched to parcel 2 nightly in production solely because I wanted to get away from tsc and do not regret it.

So please let's keep the seamless experience of not using tsc.

**Comment by avalanche1** [comment]
Because, as stated in the official V2 documentation - https://v2.parceljs.org/languages/typescript/:
- Babel doesn't support `tsconfig.json`
- Babel doesn't support advanced features like top-level await; out of the box, needs its own proper plugins installed.

**Comment by danieltroger** [comment]
> Babel doesn't support tsconfig.json

And it's not possible to configure what you want differently?

> Babel doesn't support advanced features like top-level await; out of the box, needs its own proper plugins installed.

Ah yeah that sucks.
I always have to create an async function called main and call it to circumvent that :(

Thanks for the insight!

**Comment by avalanche1** [comment]
> Can we opt out of running Babel if we dont have browserslist entry in package.json?

> That is already the case

I can attest to that. I think that is worth noting in the docs.

**Comment by avalanche1** [comment]
I, no

> > Can we opt out of running Babel if we dont have browserslist entry in package.json?
> 
> > That is already the case
> 
> ~I can attest to that. I think that is worth noting in the docs.~

Ah, no; that was a false positive. Gotta re-open.
After I've deleted `.parcel-cache` folder and re-built - I still gotten `🚨 Build failed. @parcel/transformer-babel: 'await' is only allowed within async functions ` notice.
Removing

**Comment by mischnic** [comment]
Without any browserslist config and without any babelrc file, I still get `@parcel/transformer-js: Unexpected reserved word 'await' (1:12)` (so the Babel transformer indeed didn't run).

But as I've said, all of these workarounds don't change the fact that TLA won't work

> I'm afraid TLA isn't support at the moment: #4028

**Comment by avalanche1** [comment]
Let TLA support simmer in it's own issue.
This issue is about Babel being run after TSC - which is not voluntarily.

**Comment by avalanche1** [comment]
> (so the Babel transformer indeed didn't run).

Hmm.. I do get `@parcel/transformer-**babel**: 'await' is only allowed within async functions `; although I dont have neither browserslist config, nor .babelrc file. How can I pin it down?

**Comment by mischnic** [comment]
You could print the config here: https://github.com/parcel-bundler/parcel/blob/0d3abd6ffa8fc21bbefe6f48bd6edb9713512edc/packages/transformers/babel/src/BabelTransformer.js#L33

**Comment by avalanche1** [comment]
> You could print the used (/generated) Babel config here:
> 
> https://github.com/parcel-bundler/parcel/blob/0d3abd6ffa8fc21bbefe6f48bd6edb9713512edc/packages/transformers/babel/src/BabelTransformer.js#L33

I didn't understand, what you meant
