### ISSUE TITLE
Add pure comment to interop default calls

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5765]
# 🐛 bug report

We should add pure comments to `$parcel$interopDefault` to make Terser work more effectively.

## 😯 Current Behavior

```js
(function () {
  function $parcel$interopDefault(a) {
    return a && a.__esModule ? a.default : a;
  }
  // ASSET: other.js
  var $8bf2b002e7750989eecfecf5770ea680$exports = {};
  $8bf2b002e7750989eecfecf5770ea680$exports = "some unused data";
  var $8bf2b002e7750989eecfecf5770ea680$$interop$default = $parcel$interopDefault($8bf2b002e7750989eecfecf5770ea680$exports);
  if (false) {
    console.log($8bf2b002e7750989eecfecf5770ea680$$interop$default);
  }
})();
```

Minified:
```js
!function(){var e;(e="some unused data")&&e.__esModule&&e.default}();
```

## 🤔 Expected Behavior

```js
var $8bf2b002e7750989eecfecf5770ea680$$interop$default = /*@__PURE__*/ $parcel$interopDefault($8bf2b002e7750989eecfecf5770ea680$exports);
```

## 💁 Possible Solution

Add it here: https://github.com/parcel-bundler/parcel/blob/017e8d795b3237c61c1cdf82c5e68052dda5bf28/packages/shared/scope-hoisting/src/concat.js#L65

## 💻 Code Sample

```js
import x from "./other.js";
if (false) {
	console.log(x);
}

// other.js
module.exports = "some unused data"
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 017e8d795b3237c61c1cdf82c5e68052dda5bf28

**Comment by danieltroger** [comment]
+1, great idea

**Comment by danieltroger** [comment]
This isssue also happens when importing a single export from a file importing some css through `bundle-text`, making the resulting bundle contain huge amounts of unused css
