### ISSUE TITLE
Parcel 2 does not support scripts with # src prefix

### ISSUE THREAD

**Issue by jam13** [parcel-bundler/parcel#5768]
# 🐛 bug report

In parcel 1, we used a script tag with a hash (#) prefix which allowed us to add a script outside the bundle, unprocessed by parcel. Parcel 2 doesn't seem to allow this and returns an error.

## 🎛 Configuration (.babelrc, package.json, cli command)

`src/index.html`
```html
<script src="#env.js"></script>
```

## 🤔 Expected Behavior

Script tag is added to bundled index.html, but with the # removed.

## 😯 Current Behavior

```
Error: Received URL without a pathname #env.js.
    at ResolverRunner.resolve ([redacted]/apps/modify/node_modules/@parcel/core/lib/ResolverRunner.js:109:15)
    at async DepPathRequestRunner.runRequest ([redacted]/apps/modify/node_modules/@parcel/core/lib/RequestTracker.js:372:43)
    at async [redacted]/apps/modify/node_modules/@parcel/core/lib/AssetGraphBuilder.js:305:9
    at async PromiseQueue._runFn ([redacted]/apps/modify/node_modules/@parcel/utils/lib/PromiseQueue.js:98:7)
    at async PromiseQueue._next ([redacted]/apps/modify/node_modules/@parcel/utils/lib/PromiseQueue.js:85:5)
```

## 🔦 Context

We used this for two reasons:

1) To allow an `env.js` configuration file to be added to a deployed bundle and loaded at runtime so that the
behaviour of the app could be adapted for different environments.

2) Loading preprocessed js files which we didn't want to be passed through the normal bundling process. e.g. tracking scripts

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | next
| Node             | 14.15.4
| npm/Yarn         | 1.22.10
| Operating System | MacOS

**Comment by mischnic** [comment]
Can you try using `parcel@nightly`? Might already be fixed by https://github.com/parcel-bundler/parcel/pull/5188

**Comment by jam13** [comment]
Tested parcel@nightly and as suggested it leaves # src links unchanged, however this was not the behaviour of parcel 1, which stripped off the # iirc. Nightlies are also not an option for us at the moment due to errors with terser when processing some third party js files.

I'm going to have a go at creating a custom plugin to achieve what we want. Will try to make it generic so it will be useful for others.

**Comment by mischnic** [comment]
The reason for this specific behaviour was svg: https://github.com/parcel-bundler/parcel/pull/5188

**Comment by mischnic** [comment]
Parcel 1 behaves just like Parcel nightly after the linked PR.

**Comment by jam13** [comment]
> Parcel 1 behaves just like Parcel nightly after the linked PR.

Sorry yes, you are correct. I had forgotten that we were using `parcel-plugin-html-root-syntax` to strip the #.
