### ISSUE TITLE
The js and css cited in the build index.html do not support absolute paths.

### ISSUE THREAD

**Issue by yebingo** [parcel-bundler/parcel#577]
I've tried executing the command **parcel index.html - public-url //cdn.test.com/**, but the final result reference is **/cdn.test.com/xxx** and the result I want is **//cdn. test.com/xxx**, would like to ask how to solve this problem?

**Comment by tk1024** [comment]
Is this same issue? #409

**Comment by devongovett** [comment]
This is an issue with protocol-less urls. The code you're looking for is here: https://github.com/parcel-bundler/parcel/blob/master/src/utils/urlJoin.js#L9. There is an option in the Node URL parsing API to parse double slashes as the host. https://nodejs.org/dist/latest-v8.x/docs/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost I think if you enable that option it should be fixed.

Would one of you like to make a PR for that and add a test? They are here: https://github.com/parcel-bundler/parcel/blob/master/test/url-join.js

**Comment by iifeoluwa** [comment]
I'll love to take a stab at this.
