### ISSUE TITLE
Cannot find module error in dev and build mode

### ISSUE THREAD

**Issue by odoe** [parcel-bundler/parcel#5772]
# 🐛 bug report

Using the [`@arcgis/core`](https://www.npmjs.com/package/@arcgis/core) package, a parcel build throws an error that it can't find a certain file. I've found some similar issues, like [this one](https://github.com/parcel-bundler/parcel/issues/5683), but unsure if they are related.

repro: https://github.com/odoe/parcel-arcgis-test/tree/parcelv2

~The `@arcgis/core` package has a static assets folder with built workers that I am currently copying over. I'm not sure if that has an impact, I can't tell from the error messages.~

* Updated with latest `next` release of parcel. Slightly different errors.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "main": "index.js",
  "scripts": {
    "start": "parcel index.html",
    "build": "parcel build --public-url . index.html"
  },
  "dependencies": {
    "@arcgis/core": "next",
    "parcel-bundler": "next"
  }
}

```

## 🤔 Expected Behavior

In my sample app, I would expect the app to build without errors.

## 😯 Current Behavior

Build fails when trying to load a file.

```
index.9c2fc5dc.js:1 Uncaught Error: Cannot find module '7PhYn'
    at o (index.9c2fc5dc.js:1)
    at Object.<anonymous> (runtime-0438ffd82ff3d68d.js:1)
    at o (index.9c2fc5dc.js:1)
    at Loadable.js:5
o @ index.9c2fc5dc.js:1
(anonymous) @ runtime-0438ffd82ff3d68d.js:1
o @ index.9c2fc5dc.js:1
(anonymous) @ Loadable.js:5
index.9c2fc5dc.js:1 Uncaught Error: Cannot find module '7PhYn'
    at o (index.9c2fc5dc.js:1)
    at Object.<anonymous> (runtime-b3d992f139c967d3.js:1)
    at o (index.9c2fc5dc.js:1)
    at basemapDefinitions.js:5
o @ index.9c2fc5dc.js:1
(anonymous) @ runtime-b3d992f139c967d3.js:1
o @ index.9c2fc5dc.js:1
(anonymous) @ basemapDefinitions.js:5
index.9c2fc5dc.js:1 Uncaught Error: Cannot find module '7PhYn'
    at o (index.9c2fc5dc.js:1)
    at Object.<anonymous> (runtime-1a1f6195fe87addf.js:1)
    at o (index.9c2fc5dc.js:1)
    at PortalRating.js:5
o @ index.9c2fc5dc.js:1
(anonymous) @ runtime-1a1f6195fe87addf.js:1
o @ index.9c2fc5dc.js:1
(anonymous) @ PortalRating.js:5
index.9c2fc5dc.js:1 Uncaught Error: Cannot find module '7PhYn'
    at o (index.9c2fc5dc.js:1)
    at Object.<anonymous> (runtime-a951ab373b65f555.js:1)
    at o (index.9c2fc5dc.js:1)
    at runtime-ba5ffc9f9d8a3eba.js:1
```

Not sure what could be causing the error.

## 💁 Possible Solution

Sorry, wish I knew. I work on the `@arcgis/core` package, so if there is something we need to fix there, please let me know. The entire package is deployed as ESM.

## 🔦 Context

We are working to make the `@arcgis/core` package usable across all build tools. So far, Parcel is the only one causing an issue we are unsure how to fix.

## 💻 Code Sample

Error happens with even a single imported file. We have a good size dependency tree.

```js
import ArcGISMap from "@arcgis/core/Map";

console.log('ArcGISMap', ArcGISMap);

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-rc.0
| Node             |  14.15.4
| npm              |  6.14.11
| Operating System |  Mac OS 10.15.7

**Comment by odoe** [comment]
I've updated this issue to use the latest `next` version of Parcel v2 and still get similar errors. It would be great if we could get some guidance on this. As I said, if we need to do something with our ESM package in order for this to work, we are open to it.

Thank you.

**Comment by pmacMaps** [comment]
I am also experiencing issues using the [@arcgis-core](https://www.npmjs.com/package/@arcgis/core) with parcel.  The issue occurs when I run the `parcel build` command.  I get the error in the image below.

I'm using version `2.5.0` of parcel.

![parcel-build-esri-js-api-error](https://user-images.githubusercontent.com/12861454/169601632-4e4621eb-5efc-4627-8d4d-bf951e933a8f.png)

**Comment by mischnic** [comment]
@pmacMaps Can you share a reproduction for that? I tried building https://github.com/Esri/jsapi-resources/tree/master/esm-samples/webpack with Parcel and didn't get that error

**Comment by odoe** [comment]
dev mode works, but production build does not. I don't get a build error, but a runtime error like original comment.

Made an index.html in the source folder of that sample.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
  </head>
  <body>
    <div id="viewDiv"></div>
    <script src="./index.js" type="module"></script>
  </body>
</html>

```

`npx parcel src/index.html` works, app runs as expected.

`npx parcel build src/index.html` no build errors, built app throws following runtime errors.

```
index.7acaf343.js:1 Uncaught Error: Cannot find module '48JJh'
    at i (index.7acaf343.js:1:446)
    at Object.<anonymous> (runtime-2bd3ba5244f3f640.js:1:1)
    at i (index.7acaf343.js:1:402)
    at renderable.js:5:1
index.7acaf343.js:1 Uncaught Error: Cannot find module '48JJh'
    at i (index.7acaf343.js:1:446)
    at Object.<anonymous> (runtime-6e1c554bb554e7ec.js:1:1)
    at i (index.7acaf343.js:1:402)
    at runtime-9173d8c6456b3359.js:1:549
index.7acaf343.js:1 Uncaught Error: Cannot find module '48JJh'
    at i (index.7acaf343.js:1:446)
    at Object.<anonymous> (runtime-c61c6cff11fad8aa.js:1:1)
    at i (index.7acaf343.js:1:402)
    at popupUtils.js:5:2399
index.7acaf343.js:1 Uncaught Error: Cannot find module 'kvpM4'
    at i (index.7acaf343.js:1:446)
    at runtime-3e26ad7f071fc971.js:1:58
```

node: 16.13.1
npm: 8.1.2
Mac OS: 12.3.1
Same errors in Chrome/Firefox

Updated repro sample: https://github.com/odoe/parcel-arcgis-issue

**Comment by mischnic** [comment]
That's the error I saw as well (but again, not the one about the redeclaration).

The `Cannot find module` one will be fixed relatively soon by https://github.com/parcel-bundler/parcel/discussions/7345#faster-bundling (the "has some correctness issues" part applies here).

You can try that out right now with

```json
{
  "private": true,
  "dependencies": {
    "@arcgis/core": "^4.23.0"
  },
  "scripts": {
    "build": "parcel build src/index.html",
    "start": "parcel src/index.html"
  },
  "devDependencies": {
    "@parcel/bundler-experimental": "2.5.1-nightly.2719",
    "@parcel/core": "2.0.0-nightly.1094",
    "parcel": "2.0.0-nightly.1094"
  }
}
```
`.parcelrc`

```
{
	"extends": "@parcel/config-default",
	"bundler": "@parcel/bundler-experimental"
}
```

**Comment by odoe** [comment]
Thanks! Tested that out and works great. Looks like we'll be able to add a parcel example to our samples repo, appreciate it!

**Comment by pmacMaps** [comment]
I'm running into issue with https://github.com/pmacMaps/camp-swatara-map/tree/esri-api-parcel.

npm install
npm run build

Those commands should reproduce error.

**Comment by mischnic** [comment]
As I've said in https://github.com/parcel-bundler/parcel/issues/5772#issuecomment-1133377231, it doesn't work out of the box yet, you need to opt into the experimental bundler plugin.

**Comment by pmacMaps** [comment]
Confirming use of experimental bundler plugin resolves my build issue.  Hopefully someone from Esri can update their documents for using ESM modules and parcel.js to build apps. Thanks again for the help!
