### ISSUE TITLE
.proxyrc.json is not working

### ISSUE THREAD

**Issue by zeng450026937** [parcel-bundler/parcel#5783]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)
with .proxyrc.json

```js
{
  "/api": {
    "target": "http://x.x.x.x:port",
    "changeOrigin": true,
    "ws": true
  }
}
```

## 🤔 Expected Behavior

http request start with /api should be proxied to target host in .proxyrc.json

## 😯 Current Behavior

proxy is not working and http request failed.
while using .proxyrc or .proxyrc.js work correctly

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-beta.1 |
| Node             |  v15.4.0 |
| npm/Yarn         | yarn |
| Operating System | win10 x64|

**Comment by heleg** [comment]
@mischnic I guess that this should be fixed there https://github.com/parcel-bundler/parcel/pull/5269, but not released yet?

**Comment by mischnic** [comment]
Not sure if that fixes it. But you could try the nightly version (`yarn add parcel@nightly`)

**Comment by heleg** [comment]
@mischnic Yes, it's working. I think you can close this issue.
