### ISSUE TITLE
Parcel 2 (nightly) CSS modules with typescript - unexpected null during build

### ISSUE THREAD

**Issue by sbauch** [parcel-bundler/parcel#5789]
# 🐛 bug report

I'm using nightly parcel builds and haven't been able to build beginning with nightly 504. I use typescript and css modules, and I get the following error when building for production, with the build hanging indefinitely:

```
console: (node:74787) UnhandledPromiseRejectionWarning: Error: Got unexpected null
    at nullthrows (/Users/samuelsbauch/Code/parcel-example/node_modules/nullthrows/nullthrows.js:7:15)
    at _generateFromAST (/Users/samuelsbauch/Code/parcel-example/node_modules/@parcel/core/lib/assetUtils.js:215:78)
```

## 🎛 Configuration (.babelrc, package.json, cli command)

I have a source available app where you can see a real world example, but the following is config for a test case I put together.

`package.json`:
```json
{
  "name": "parcel-example",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "build": "parcel build ./src/index.html --dist-dir ./public",
    "clean": "rm -rf public && rm -rf .parcel-cache",
    "start": "parcel serve ./src/index.html",
    "serve": "node-dev-server"
  },
  "targets": {
    "default": {
      "engines": {
        "browsers": "> 0.25%"
      },
      "distDir": "public",
      "publicUrl": "."
    }
  },
  "devDependencies": {
    "@babel/core": "^7.12.13",
    "@babel/preset-typescript": "^7.12.13",
    "@types/node": "^14.14.25",
    "@types/react": "^17.0.1",
    "@types/react-dom": "^17.0.0",
    "@types/react-router-dom": "^5.1.7",
    "@typescript-eslint/eslint-plugin": "^4.14.2",
    "@typescript-eslint/parser": "^4.14.2",
    "autoprefixer": "^10.2.4",
    "babel-plugin-import": "^1.13.3",
    "browserslist": "^4.16.3",
    "eslint": "^7.19.0",
    "eslint-config-prettier": "^7.2.0",
    "eslint-plugin-cypress": "^2.11.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-react": "^7.22.0",
    "eslint-plugin-simple-import-sort": "^7.0.0",
    "parcel": "2.0.0-nightly.504",
    "postcss": "^8.2.4",
    "postcss-modules": "^4.0.0",
    "prettier": "^2.2.1",
    "typescript": "^4.1.3"
  },
  "dependencies": {
    "prop-types": "^15.7.2",
    "react": "^17.0.1",
    "react-copy-to-clipboard": "^5.0.3",
    "react-dom": "^17.0.1",
    "react-router-dom": "^5.2.0"
  },
  "browserslist": {
    "development": [
      "last 1 Chrome version"
    ],
    "production": [
      "defaults"
    ]
  }
}
```

`bablerc.json`:
```json
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    "@babel/preset-typescript"
  ]
}
```

## 🤔 Expected Behavior

The app should build successfully.

## 😯 Current Behavior

I get the following error:
```
console: (node:74787) UnhandledPromiseRejectionWarning: Error: Got unexpected null
    at nullthrows (/Users/samuelsbauch/Code/parcel-example/node_modules/nullthrows/nullthrows.js:7:15)
    at _generateFromAST (/Users/samuelsbauch/Code/parcel-example/node_modules/@parcel/core/lib/assetUtils.js:215:78)
(Use `node --trace-warnings ...` to show where the warning was created)
console: (node:74787) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
console: (node:74787) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠴ Optimizing index.[hash].js...
```

The build hangs indefinitely.

If I switch to nightly 500, remove parcel-cache, and build again it succeeds as expected.

If I remove the classname and the css module import, the app also builds as expected.

## 🔦 Context

This hasn't affected me too much, I just end up closing dependabot PRs every morning so I do think I'd like to get off the nightly build treadmill. Is a more stable beta release planned?

## 💻 Code Sample

I experience this in my source a available app Osso. There should be a dependabot PR here for upgrading that links to buildkite CI - https://github.com/enterprise-oss/osso/pulls

I also figured I should put together a smaller test case to make sure it wasn't something unrelated. This repo is the smallest test case I could make to reproduce, with config mostly copied from my app:

https://github.com/sbauch/parcel-nighty-css-modules

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | nightly@ >= 504 
| Node             | 14
| npm/Yarn         | yarn 1.22.5
| Operating System | macOS, linux in CI

**Comment by mischnic** [comment]
This seems to be fixed since nightly 522?

**Comment by sbauch** [comment]
Ah ok. I re-read the manual a bit on css modules.

It seems like this is still an issue only when using default imports of css modules and scope hoisting (on by default for build)

But when using the recommended named imports, or by using the `--no-scope-hoist` option, everything builds correctly.

> Tree shaking isn't possible with default imports: import style from "./app.module.css";. Use namespace imports as above — no other changes are neccessary.

Happy to have you close, unclear to me if this is potentially a bug in parcel or a mistake I am making in trying to use default imports.

**Comment by mischnic** [comment]
default imports should still work, it's just that you have more unused CSS.

So, if you're using a recent nightly and run into some kind of build error or the produced CSS is invalid with either named or default imports, then it's a bug.

**Comment by sbauch** [comment]
I think my test case here fits what you describe - 

https://github.com/sbauch/parcel-nighty-css-modules

There I'm using nightly@574 with typescript and attempting to use a default import of a css module. The build hangs indefinitely. 

If I do any of the following, the app builds successfully:

• use named imports
• build with `--no-scope-hoist`
• switch to nightly@500
• remove the CSS module altogether

**Comment by mischnic** [comment]
You should be using `@parcel/babel-preset-env` instead of `@babel/preset-env` in the babelrc: https://v2.parceljs.org/languages/babel/#extending-the-default-babel-config

But that's more of a workaround and the error should be fixed anyway...

**Comment by mischnic** [comment]
So the case where the namespace object is imported but cannot be resolved to named symbols is broken with CSS modules:

```js
import * as styles from "./index.module.css";

const id = (v) => v;

console.log(id(styles));
```

**Comment by sbauch** [comment]
tysm for the tip and for looking into this!

ultimately i do prefer named imports, helped me catch some dead css etc., so all in all a happy accident.

I suppose I'll let the PR close this automatically, thanks for all the work you do on parcel!
