### ISSUE TITLE
Parcel 2: distDir is ignored, output is always in dist

### ISSUE THREAD

**Issue by SpadarShut** [parcel-bundler/parcel#5791]
# 🐛 bug report

The `distDir` target parameter is always ignored.

## 🎛 Configuration

package.json:

```json
{
  "name": "parcel-bug-report",
  "scripts": {
    "build": "parcel src/index.js"
  },
  "browser": "build/index.js",
  "targets":  {
    "browser": {
      "distDir": "build"
    }
  },
  "devDependencies": {
    "parcel": "^2.0.0-beta.1"
  }
}
```

## 🤔 Expected Behavior

Running parcel should put output in `build` directory.

## 😯 Current Behavior

Output is always in `dist`.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.beta 1
| Node             | 14
| Operating System | MacOS

**Comment by mischnic** [comment]
By default, serve mode uses a different target. So `parcel src/index.js --target browser` would definitely be needed.

The specified distdir is however also overwritten by the `--dist-dir` default value (`$pwd/dist`) here:

https://github.com/parcel-bundler/parcel/blob/0d3abd6ffa8fc21bbefe6f48bd6edb9713512edc/packages/core/core/src/requests/TargetRequest.js#L217

**Comment by Himavanth** [comment]
I tried the `distDir` provided in `serveOptions` but that too doesnt work. 
@mischnic Should i file a separate issue or would this one suffice ?
```
const ParcelCore = require("@parcel/core");
const path = require('path');
const { default: Parcel } = ParcelCore;

(async () => {
    let entryFile = path.join(__dirname, "src/index.html")
    let dest = path.join(__dirname, "dist1")

    let parcel = new Parcel({
        entries: entryFile,
        distDir: dest,
        defaultConfig: require.resolve("@parcel/config-default"),
        targets: { ['def']: { distDir: dest } },
        serveOptions: {
            distDir: dest,
            port: 1235,
            https: false
        },        
        additionalReporters: [
            { packageName: '@parcel/reporter-cli', resolveFrom: __filename },
            { packageName: '@parcel/reporter-dev-server', resolveFrom: __filename }
        ]
    });

    await parcel.watch(err => {
        if (err) throw err;
    });
})();
```
This never uses the `dist1` directory.

**Comment by devongovett** [comment]
The issue is that the dev server does not have access to the resolved targets (because that happens after the server starts). For this reason the specific target distDir is overwritten by the default dist dir in serve mode.

You can override the dist dir for serve in two ways:

1. Via the `--dist-dir` option on the CLI.
2. Using the `defaultTargetOptions.distDir` option to the Parcel API (which is what the CLI uses).

```js
new Parcel({
  defaultTargetOptions: {
    distDir: whatever
  }
});
```

@Himavanth `serveOptions.distDir` doesn't actually exist, and neither does the top-level `distDir` option. It's `defaultTargetOptions.distDir`. See https://v2.parceljs.org/plugin-system/api/#InitialParcelOptions for docs.

**Comment by Himavanth** [comment]
Thx @devongovett . `defaultTargetOptions` worked for my case.

**Comment by aheissenberger** [comment]
How can I get `new Parcel()` to ignore any settings which exist in the package.json if I need to run with different values? In my case I cannot change the package.json.

**The `"main": "maindist/index.js"` from `package.json` will override any settings for `distDir` to `maindist `** when trying to use `new Parcel()`:
`build.mjs`
```javascript
import ParcelCore from "@parcel/core";
import { createRequire } from "module";
import path from "path";

import { dirname } from 'path';
import { fileURLToPath } from 'url';

const { default: Parcel } = ParcelCore; // TODO

const __dirname = dirname(fileURLToPath(import.meta.url));

let bundler = new Parcel({
    entries: path.join(__dirname, "/index.mjs"),
    defaultConfig: createRequire(import.meta.url).resolve( "@parcel/config-default"),
    defaultTargetOptions: {
       // this will be overwritten by "main": "maindist/index.js" to "maindist"
        distDir: path.join(__dirname, "output"), 
    },
    mode: "production",
});

await bundler.run();
```

`package.json`
```json
{
  "name": "parcel-distdir",
  "version": "1.0.0",
  "main": "maindist/index.js",
  "license": "MIT",
  "private": true,
  "devDependencies": {
    "parcel": "^2.0.0-beta.2"
  }
}

```
you can test this with the code in this repository:
https://github.com/aheissenberger/parcel-distdir-bug

**Comment by Himavanth** [comment]
@aheissenberger You could specify targets like in the example here https://github.com/parcel-bundler/parcel/issues/5791#issuecomment-822375173

**Comment by aheissenberger** [comment]
> @aheissenberger You could specify targets like in the example here [#5791 (comment)](https://github.com/parcel-bundler/parcel/issues/5791#issuecomment-822375173)

@Himavanth thanks - this fixed the problem:
```js
...
   defaultConfig: createRequire(import.meta.url).resolve( "@parcel/config-default"),
   targets: {
        main: {
            distDir:path.join(__dirname, "output"),
        }
    },
```
