### ISSUE TITLE
Bundling service workers

### ISSUE THREAD

**Issue by Banou26** [parcel-bundler/parcel#5792]
# 🐛 bug report

When trying to bundle with a `service-worker` context for a v3 manifest chrome extension background service worker, parcel throws
```
[1] @parcel/core: Invalid target descriptor for target "service-worker"
[1] C:\dev\oz\packages\extension\package.json:14:18
[1]   13 |     "service-worker": {      
[1] > 14 | xt": "service-worker",       
[1] >    |      ^^^^^^^^^^^^^^^^ Did you mean "web-worker"?
[1]   15 |       "engines": {
[1]   16 |         "browsers": [
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "devDependencies": {
    "parcel": "^2.0.0-nightly.500"
  },
  "service-worker": "dist/service-worker.js",
  "targets": {
    "service-worker": {
      "context": "service-worker",
      "engines": {
        "browsers": [
          "last 1 chrome version"
        ]
      }
    }
  },
  "scripts": {
    "dev-content-script": "parcel watch src/content-script.ts --target service-worker --no-hmr --no-source-maps"
  }
}

```

**Comment by Banou26** [comment]
After updating to `2.0.0-nightly.574` i get `Error: Invalid target descriptor for target "service-worker"` instead

**Comment by mischnic** [comment]
> After updating to 2.0.0-nightly.574 i get Error: Invalid target descriptor for target "service-worker" instead

What do you mean? The error is the same for me with 2.0.0-nightly.500 or 2.0.0-nightly.572

**Comment by mischnic** [comment]
(`context: "service-worker"` doesn't do anything special yet, so it's the same as `web-worker`)

(You might be interested in https://v2.parceljs.org/recipes/web-extension/)
