### ISSUE TITLE
HMR persists old deleted code & cache folder inflation

### ISSUE THREAD

**Issue by yairEO** [parcel-bundler/parcel#5796]
Hello dear maintainers and bundle-enthusiasts

Errors appear in the browser's console regarding some *React JSX* issue, but they reference old code. I tried restarting *Parcel* (`parcel start`), restarting *vscode*, restarting my computer. still same error. 

![image](https://user-images.githubusercontent.com/845031/107241275-814b3c80-6a33-11eb-8cbe-8ab1b7844d16.png)

![image](https://user-images.githubusercontent.com/845031/107203667-61505480-6a04-11eb-97b8-8d60e75a29c1.png)

I inspected the error and saw the code (which the error in the console leads to by clicking on it) was much older than the current code, and that lead me to thinking maybe there's a cache somewhere. 

Saw `.parcel-cache` is over `10GB`, for a small new project so I immediately deleted the folder,
but after deleting the cache folders the problem remains.

Maybe related to this?
https://github.com/parcel-bundler/parcel/issues/4495

## `package.json`

```
{
  "name": "foo",
  "version": "1.0.0",
  "scripts": {
    "start": "parcel index.html",
    "prod": "parcel build index.html --dist-dir build"
  },
  "license": "ISC",
  "dependencies": {
    "@hot-loader/react-dom": "^17.0.1",
    "@xstyled/styled-components": "^2.2.2",
    "@yaireo/react-number-input": "^1.1.1",
    "@yaireo/ui-range": "^2.1.15",
    "@yaireo/ui-switch": "^1.0.5",
    "apexcharts": "^3.24.0",
    "core-js": "^3.8.3",
    "disqus-react": "^1.0.11",
    "i18next": "^19.8.7",
    "query-string": "6.13.8",
    "react": "^17.0.1",
    "react-apexcharts": "^1.3.7",
    "react-hot-loader": "^4.13.0",
    "react-i18next": "^11.8.5",
    "reactour": "^1.18.0",
    "src": "^1.1.2",
    "store": "^2.0.12",
    "store.js": "^1.0.4",
    "styled-components": "^5.2.1",
    "styled-media-query": "^2.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.13",
    "@babel/preset-env": "^7.12.13",
    "@babel/preset-react": "^7.12.13",
    "autoprefixer": "^10.2.4",
    "babel-plugin-styled-components": "^1.12.0",
    "postcss": "^8.2.5",
    "sass": "^1.32.6"
  },
  "alias": {
    "react-dom": "@hot-loader/react-dom",
    "components": "~/src/components",
    "utils": "~/src/utils",
    "hooks": "~/src/hooks",
    "routes": "~/src/routes",
    "store": "~/src/store",
    "styles": "~/src/styles"
  }
}

```

I am using this command in my main `index.js`:

    if (module.hot) {
      module.hot.accept()
    }

## 🤔 Expected Behavior

I expect not to see errors in the browser's console regarding old code changes and I really don't want 
my code to use deleted parts and persist those changes.

And I really don't want an inflated `.parcel-cache` folder 

## 😯 Current Behavior

1. As described above - seeing errors in the browser's console regarding my personal small React app which are obsolete since that code is long gone, but somehow persisted as a ghost to haunt me
2. Gigabytes of files accumulating in the `.parcel-cache` folder

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | v15.4.0
| npm/Yarn         | 7.0.15
| Operating System | Windows 10

**Comment by mischnic** [comment]
Parcel 2 supports the React Fast Refresh without any configurations/special dependencies: https://v2.parceljs.org/recipes/react/#hmr-(fast-refresh)

Do you have an example where you can trigger the HMR error consistently? (Starting with an empty cache folder)

There are eventual plans for cache garbage collection, but nothing concrete yet.

**Comment by yairEO** [comment]
I don't have an example, this just started happening in my (WIP) project about a week ago and I see now see errors referring to old code on every page refresh.

I went by the [instructions here](https://v2.parceljs.org/features/hmr/)

I've read before the page you were referring to, and it does not mention to ignore the HMR page instructions (which are above it in the left nav menu). I now carefully read it again and still see nothing there that mentions the other page.. if you say I don't need 

```js
if (module.hot) {
  module.hot.accept()
}
```

Then I'll remove those code lines, but should I keep `@hot-loader/react-dom` in the `package.json` or use the "real" `react-dom` lib? I remember If I installed `@hot-loader/react-dom` myself or not

**Comment by mischnic** [comment]
No, as I've said:

> without any special dependencies

The examples on https://v2.parceljs.org/recipes/react/ also don't have any special dependencies.

**Comment by bhallstein** [comment]
Throwing a jaunty +1 for improved management of .parcel-cache. Was just tracking down why my disk space was so low and ended up deleting approx. 20GB from various .parcel-cache directories in different project folders — the largest was about 5.7GB.

Using parcel 2.0.0-beta.2 everywhere. Happy to hear if I'm doing something wrong.

**Comment by 55Cancri** [comment]
Parcel cache is bloated and hmr doesn't actually update to latest jsx. I _always_ need to hard reset my browser to see the latest changes.

**Comment by aestheticsdata** [comment]
same for me. I need to manually delete the dist folder content to refresh the code changes
