### ISSUE TITLE
Ignore Babel-specific entries in `package.json` if TS is set as the transformer

### ISSUE THREAD

**Issue by avalanche1** [parcel-bundler/parcel#5799]
# 🙋 feature request

Change Parcel behaviour so as to if TS is set as the transformer - Parcel would ignore Babel-specific entries in `package.json`.
As discussed in https://github.com/parcel-bundler/parcel/issues/5761#issuecomment-775040632 and https://github.com/parcel-bundler/website/issues/809.

## 🤔 Expected Behavior

 ignore Babel-specific entries in package.json if TS is set as the transformer. So that the build doesn't break in case there are Babel-unsupported features like TLA.

## 😯 Current Behavior

if you have `browserslist` entry in `package.json` - Babel compiler will kick in, in spite of the fact that you've got @parcel/transformer-typescript-tsc in the transformers list.

## 🔦 Context

Given me some headaches and forced me to file an issue to get to the root of evil, when I had my builds breaking, when I had TS set as the transformer,  `browserslist` entry in `package.json` (came from legacy project - I don't really need it; although, didnt know it would affect the build process that badly) and TLA in the code.

**Comment by avalanche1** [comment]
bump

**Comment by mischnic** [comment]
What's your usecase here? Because

> So that the build doesn't break in case there are Babel-unsupported features like TLA.

Will then just instead break parts of Parcel that run after Babel

**Comment by avalanche1** [comment]
What do you mean 'my usecase'?
I want to use typescript + browserlist + TLA. And that was not possible at the time of writing (v2 beta 1)
