### ISSUE TITLE
V2: @parcel/config-webextension: generates unacceptable folder names __

### ISSUE THREAD

**Issue by avalanche1** [parcel-bundler/parcel#5808]
# 🐛 bug report
Running `parcel` for devving web-extn locally (`yarn start` from `package.json` below).
If extn `manifest.json` references a file outside `src` folder, say `..assets/icon.png` - Parcel will copy that file to `dist/__/assets/icon.png`.
Pls notice the intermediary `__` folder. This is prohibited for chrome extns. When I try to load the unpackaged extn into the browser via pointing to `dist/` - it will throw this err:
`Cannot load extension with file or directory name __. Filenames starting with "_" are reserved for use by the system`

This doesn't happen when running the `build` script, mind you.
## 💻 Code Sample

`manifest.json`:
```json
{
  ...
  "browser_action": {
    "default_icon": {
      "128": "assets/icon/icon.png"
    }
  },
  "icons": {
    "128": "assets/icon/icon.png"
  }
}
```
folder structure:
```
    .
    ├── assets           
      └── icon
        └── icon.png
    ├── dist
      └── __
        └── assets
          └── icon
            └── icon.png
      └── manifest.json
      └── ...
    ├── src
      └── manifest.json
      └── ...
```

## 🎛 Configuration (.babelrc, package.json, cli command)

`.parcelrc`:
```json
{
  "extends": "@parcel/config-webextension",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
}
```
` package.json`
```json
{
  "scripts": {
    "start": "parcel src/manifest.json --host localhost --target webext-dev",
    "build": "parcel build src/manifest.json --target webext-prod",
  },
  "targets": {
    "webext-dev": {
      "sourceMap": {
        "inline": true,
        "inlineSources": true
      }
    },
    "webext-prod": {}
  },

}
```
## 🤔 Expected Behavior

Do not generate folders with chrome-restricted names

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  `^2.0.0-nightly.574`
| Operating System | `osX 10.14`

**Comment by avalanche1** [comment]
Hmm... after killing `.parcel-cache` and `dist` folders - the issue is gone. What was that about?🤔

**Comment by avalanche1** [comment]
> Hmm... after killing `.parcel-cache` and `dist` folders - the issue is gone. What was that about?🤔

This was a mistake. I've put `assets` into `src` and it started building alright.

**Comment by fregante** [comment]
Note: The `__` naming is actually unrelated to the web extensions transformer, but it is a breaking issue **for** web extensions.

I had the same issue and thought of an alternative "solution" (i.e. don't preserve the directory tree), but I don't know how to achieve that: https://github.com/parcel-bundler/parcel/discussions/5858

**Comment by mischnic** [comment]
So this occurs because the output path of the bundles is `path.join(distDir, path.relative(entryRoot, entryAsset.filePath))`, and node_modules is outside of the entry root. And then the result is "sanitized" by replacing `.` with `_`.

**Comment by fregante** [comment]
Would the solution here be to just drop any `../` instead of sanitizing them? Or what do you suggest?

**Comment by mischnic** [comment]
You could run into a naming collision with that, e.g.:

```
src/index.html
src/src2/test.html
src2/test.html
```
and `src/index.html` being
```html
<a href="src2/test.html">X</a>
<a href="../src2/test.html">X</a>
```
would right now create:
```
dist/index.html
dist/src2/test.html
dist/__/src2/test.html
```

**Comment by fregante** [comment]
> You could run into a naming collision with that, e.g.:

Hashes (based on the filename if you use `--no-content-hash`)! If one needs public URLs like those html files then they wouldn't use this namer.

**Comment by fregante** [comment]
```
dist/index.html
dist/src2/test.html
dist/__/src2/test.html
```

would have to become

```
dist/index.html
dist/src2/test.html
dist/src2/test.717dcb8d.html
```

Linking to `..` would not make sense for public URLs anyway, so renaming the second `test.html` would be an alternative

**Comment by mischnic** [comment]
No, the contract for `bundle.isEntry` is not adding a hash.

**Comment by 101arrowz** [comment]
Perhaps we could use `$` instead of `_` to prevent naming collisions. I don't think there are too many things that depend on `$` (besides maybe shell variables, but realistically nobody will be running a shell script on Parcel output). Alternatively, the solution in #5893 doesn't seem too bad to me...

**Comment by mischnic** [comment]
We could also replace `__` with something like `dist`. Doesn't look as odd the various proposals involving different punctuation.

Do you want to open a new PR similar to the one you linked? Picking a different name other than `__` would certainly be a fine workaround for this issue

**Comment by 101arrowz** [comment]
I think it's a good idea to indicate somehow that a `..` was replaced somehow. Actually, I think #5893 should just be merged, since it seems to be a good-enough solution to this problem. I could recreate it, but realistically the use of `up_` is quite nice (the alternative is something like `bk_`).

**Comment by mischnic** [comment]
Someone has to recreate it, I can't reopen it because the branch was deleted

![Bildschirmfoto 2021-05-02 um 23 10 37](https://user-images.githubusercontent.com/4586894/116827852-9c919800-ab9b-11eb-82e9-96ed6459c2d4.png)

**Comment by 101arrowz** [comment]
#6223

**Comment by fregante** [comment]
I reopened my PR since it has more context, if you're interested in merging it.
