### ISSUE TITLE
Quoting inline styles

### ISSUE THREAD

**Issue by folknor** [parcel-bundler/parcel#5809]
# 🐛 bug report

Parcel 2.0 nightly misquotes inline CSS styles.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "testing",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "clean": "rm -rf dist/",
    "build": "npm run clean && parcel build index.html --no-minify --target web"
  },
  "web": "./dist/index.html",
  "targets": {
    "web": {
      "context": "browser",
      "publicUrl": "./"
    }
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel": "^2.0.0-beta.1"
  }
}

```

## 🤔 Expected Behavior

Quotes should be escaped, or used interchangeably as appropriate.

## 😯 Current Behavior

parcel currently changes this in the input HTML:
```html
					<div class="image col-lg-6 order-1 order-lg-2" style='background-image: url("img/services.jpg");'></div>
```

to
```html
					<div class="image col-lg-6 order-1 order-lg-2" style="background-image: url("services.ee985902.jpg");
"></div>
```

(note the weird \n as well)

Which is invalid.

**Comment by mischnic** [comment]
Doing something similar to https://github.com/parcel-bundler/parcel/blob/36035d8d0d7f785771dd24207fe17d67ed85f269/packages/packagers/js/src/JSPackager.js#L57-L60

in the HTML packager might work
