### ISSUE TITLE
Fails to inject bundle and copy html entry file to output dir after 2.0.0-nightly.560.....

### ISSUE THREAD

**Issue by DaveO-Home** [parcel-bundler/parcel#5818]
# 🐛 bug report

The test app worked fine before 2.0.0-nightly.560, V2 no longer injects the bundle into the html entry file.  Before I did not have the attribute "type='module'", this does not make a difference.

## 🎛 Configuration (.babelrc, package.json, cli command)

The test demo can be found @ https://github.com/DaveO-Home/embedded-acceptance-tests-react/tree/master/public/parcel/build

see build config in gulpfile.js  ~ line 229

The online test app is configured with  2.0.0-nightly.551 which works...

```js
{
  "your": { "config": "here" }
}
```

## 🤔 Expected Behavior

The entry html should be copied to output directory with hashed bundle name injected. 

## 😯 Current Behavior

No html file shows up in output directory

No errors - the bundler goes through the steps but no html file generated

## 💁 Possible Solution

Stay with 2.0.0-nightly.560 until resolved or get notified of new configuration

## 🔦 Context

Just making sure I can build with V2

## 💻 Code Sample

online at github

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by DaveO-Home** [comment]
Note; this is a React app and the css and js bundles are also not generated. Gulp is used and the require is;
```js
const Parcel = require("@parcel/core").default;
```

**Comment by mischnic** [comment]
We renamed some option props some time ago (regarding [these options](https://github.com/DaveO-Home/embedded-acceptance-tests-react/blob/c16aec80777b515a2b67c10adca712f6c8bccdf0/public/parcel/build/gulpfile.js#L236-L254)), but I'm not sure if this is related to your problems

https://github.com/parcel-bundler/parcel/pull/5572
https://github.com/parcel-bundler/parcel/pull/5696

**Comment by DaveO-Home** [comment]
@mischnic - seems that it was a config problem - 579 works with;

```js
        mode: isProduction? "production": "development",
        entryRoot: "../appl",
        entries: file,
        publicUrl: watch ? "/dist_test/parcel" : "./",
        hmrOptions: {port: port, host: "localhost"},
        serveOptions: { 
            publicUrl: "/dist_test/parcel",
            host: "localhost",
            port: port,
            https: false,
        },
        shouldDisableCache: !isProduction,
        shouldAutoInstall: true,
        shouldProfile: false,
        cacheDir: ".cache",
        shouldContentHash: isProduction,
        logLevel: 1, // 3 = log everything, 2 = log warnings & errors, 1 = log errors
        detailedReport: isProduction,
        defaultConfig: require.resolve("@parcel/config-default"),
        distDir: "../../" + dist,
        shouldPatchConsole: false,
        defaultTargetOptions: {
            shouldOptimize: isProduction,
            shouldScopeHoist: false,
            sourceMaps: isProduction,
            publicUrl: "./",
            distDir: "../../" + dist,
            engines: {
                browsers: ["> 0.2%, not dead, not op_mini all"]
            }
          }
```

Where can I find something on HMR/Serve  -- I get a messge that the server is started but shuts down after build, i.e. the watch isn't active?

**Comment by mischnic** [comment]
Are you using `.watch()` instead of `.run()`? https://github.com/parcel-bundler/parcel/blob/a26f6397c42370799391511361e4074a0df2d62a/packages/core/parcel/src/cli.js#L294-L298
