### ISSUE TITLE
Running two instances of parcel-watch at the same time will error out...sometimes

### ISSUE THREAD

**Issue by Sleepful** [parcel-bundler/parcel#5823]
# 🐛 bug report

Running two instances of parcel-watch at the same time will error out...sometimes

## 🎛 Configuration (.babelrc, package.json, cli command)

doing something like
```
yarn parcel watch --dist-dir /dist/app entry.ts & yarn parcel watch --dist-dir /dist/styles entry.scss
```
## 🤔 Expected Behavior

Should not error out

## 😯 Current Behavior

this error
```
[js] TypeError: Cannot read property 'port' of null
[js]     at HMRServer.start (/Users/code/node_modules/@parcel/reporter-dev-server/lib/HMRServer.js:51:38)
[js]     at Object.report (/Users/code/node_modules/@parcel/reporter-dev-server/lib/ServerReporter.js:81:23)
[js]     at ReporterRunner.report (/Users/code/node_modules/@parcel/core/lib/ReporterRunner.js:73:31)
[js]     at async Parcel.watch (/Users/code/node_modules/@parcel/core/lib/Parcel.js:326:7)
[js]     at async Command.run (/Users/code/node_modules/parcel/lib/cli.js:210:9)
[js] Bundling...
[js] /Users/code/node_modules/@parcel/reporter-dev-server/lib/HMRServer.js:121
[js]     this.options.logger.warn({
[js]                         ^
[js]
[js] TypeError: Cannot read property 'warn' of undefined
[js]     at WebSocketServer.handleSocketError (/Users/code/node_modules/@parcel/reporter-dev-server/lib/HMRServer.js:121:25)
[js]     at WebSocketServer.emit (events.js:315:20)
[js]     at Server.emit (events.js:315:20)
[js]     at emitErrorNT (net.js:1345:8)
[js]     at processTicksAndRejections (internal/process/task_queues.js:80:21)

```

## 💁 Possible Solution

retry until it works, or launch at different terminals/moments

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.384
| Node             | 14
| npm/Yarn         | yarn
| Operating System | macos

**Comment by mischnic** [comment]
Can you try with a recent nightly? I'm getting
```
[1]  + 57543 suspended (tty output)  yarn parcel watch --dist-dir dist-app entry.js
```

This is still rather problematic, because they might overwrite each other's cache. https://github.com/parcel-bundler/parcel/pull/5824 would make it possible to achieve what you want with just one Parcel invocation

>  Operating System: macos

I don't think this really matters, but I think you're using Docker, so Linux?

**Comment by mephinet** [comment]
I think you have the same issue that I just ran into, and reported as #5890 :
* `parcel watch entry.ts` produces an entry.js
* `parcel watch entry.scss` produces an entry.css and _also_ an entry.js (that contains the HMR code)

To validate my assumption, can you please rename your entry.scss to whatever.scss and report whether that solves your issue?

**Comment by mischnic** [comment]
This issue is for Parcel 2. Your issue for Parcel 1.

**Comment by mephinet** [comment]
Yep, I am curious whether it v2 is also affected...
