### ISSUE TITLE
some files can skip compilation ,edit html after compilation

### ISSUE THREAD

**Issue by pssgo** [parcel-bundler/parcel#583]
🙋 feature request

### 🎛 Configuration (.babelrc, package.json, cli command)

```html
  <body>
    <div id="app"></div>
    <script src="./src/index.js"></script>
    <script src="./init.js"></script>
    <script type="text/javascript">
    function init() {
      if ('serviceWorker' in navigator) {
        window.addEventListener('load', () => {
          navigator.serviceWorker.register('/sw.js').then((registration) => {
            console.log('SW registered: ', registration)
          }).catch((registrationError) => {
            console.log('SW registration failed: ', registrationError)
          })
        })
      }
    }
    init();
    </script>
  </body>
```
```js
// package.json

"build": "NODE_ENV=production parcel build ./index.html --public-url ./"

```
```js
// .babelrc

{
  "presets": ["env","react","stage-0"],
  "plugins": [
    "transform-decorators-legacy",
     "transform-object-rest-spread",
    ]
}


```

### 🤔 Expected Behavior

I want some file can jump the compile and I want to change the html after compilation

### 😯 Current Behavior

init.js and script tag can't skip compile

I don't know how to change html after compilation

### 💁 Possible Solution

I have no idea

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.4.1
| Node             | 9.2.0
| npm/Yarn         | 5.2.0
| Operating System | macos

**Comment by DeMoorJasper** [comment]
Using multiple entrypoints and running a script after parcel could help. In dev you'd probably have to use the api though
