### ISSUE TITLE
Set NODE_ENV does not work for production

### ISSUE THREAD

**Issue by Aben** [parcel-bundler/parcel#584]
> Enabling production mode also sets the NODE_ENV=production environment variable. Large libraries like React have development only debugging features which are disabled by setting this environment variable, which results in smaller and faster builds for production.

https://github.com/parcel-bundler/parcel/blob/b56b2a9f3c3ff6db2dd27a086b409a8d4af6f2bd/src/cli.js#L100-L102

https://github.com/parcel-bundler/parcel/blob/a120fbb2b7b4f52dd95e6146f4d5d76eed4b58b0/src/Bundler.js#L205-L207

Should I add a PR fix this?

**Comment by DeMoorJasper** [comment]
Isn't this a good thing? In a production environment u don't need debugging right?

**Comment by TuKun33** [comment]
i am using cross-env to set NODE_ENV, bug i can`t get the NODE_ENV of process.env，it`s give me a empty object

**Comment by DeMoorJasper** [comment]
@TuKun33 This issue has been fixed your issue is probably unrelated.
