### ISSUE TITLE
tsx file as `main` inside package.json breaks output file name(package name instead of hash)

### ISSUE THREAD

**Issue by shunia** [parcel-bundler/parcel#586]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

a 🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`:
```json
{
  "name": "my-app", 
  "main": "src/Index.tsx", 
  ...
}
```

### 🤔 Expected Behavior
`parcel index.html` should output a bundled file named `{hash}.js`.

### 😯 Current Behavior
`parcel index.html` output a bundled file named `ma-app.js`.

### 💁 Possible Solution
Delete the `main` part inside `package.json`

### 🔦 Context
`my-app.js` will cause cache problem, and it's just not behave as expected.

### 💻 Code Sample
As above, but it's a React app with TypeScript, not sure(not tested) other type of combination has the same problem or not.

### 🌍 Your Environment
VSCode +
TypeScript +
react +
tsx +
yarn

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |    1.4.1
| Node             |    8.9.3
| npm/Yarn         |    1.3.2
| Operating System |    macOS Sierra

**Comment by DeMoorJasper** [comment]
The naming strategy has been changed since 1.4.1.
