### ISSUE TITLE
`--no-content-hash` isn't working correctly

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#5894]
# 🐛 bug report

`--no-content-hash` doesn't seem to have an effect.

## 😯 Current Behavior

When changing the contents of an JS asset, the bundle hash changes.

## 🤔 Expected Behavior

Bundle name hash shouldn't change

## 💻 Code Sample

`parcel build index.html --no-content-hash`

```html
<script src="index.js"></script>
```
```js
console.log(123); // <- change this
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.603

**Comment by Kangaroux** [comment]
This is also not working for me in v1.12.4

**Comment by GreatState** [comment]
Ditto. 
![image](https://user-images.githubusercontent.com/35596657/109491811-f71a5500-7a81-11eb-9599-aabb6af78821.png)

Adding --no-content-hash doesn't work for me

**Comment by mischnic** [comment]
No. `--no-content-hash` still adds hashes, it's just that they are constant (and not changing based on the file contents)

**Comment by GreatState** [comment]
Excellent thanks for the clarification

**Comment by Kangaroux** [comment]
> No. `--no-content-hash` still adds hashes, it's just that they are constant (and not changing based on the file contents)

The help docs say it shouldn't include hashes.

```
--no-content-hash              disable content hashing
```

**Comment by mischnic** [comment]
No, as I've said, it "disables **content** hashing". It doesn't "disable hashing".

**Comment by Kangaroux** [comment]
I don't see the value of having a static hash if it doesn't match the content. Why isn't it completely disabled?

**Comment by mischnic** [comment]
See https://github.com/parcel-bundler/parcel/issues/2056

**Comment by devongovett** [comment]
Appears to be working in the latest nightly.

**Comment by RichardJECooke** [comment]
Even though I use `--no-content-hash` my filenames still change. Version 2.83. Look:

```bash

> rm -r dist || rm -r .parcel-cache || true && parcel build --no-content-hash src/index.html`

✨ Built in 15.71s

dist/index.html                   1.33 KB    17.54s
dist/logo.4f32dfb3.svg              355 B    17.53s
dist/app.webmanifest                450 B     2.09s
dist/appIcon512.7666cacc.png      6.09 KB    17.29s
dist/index.178894d8.css           4.15 KB     2.32s
dist/index.c2dc1f85.js          855.98 KB    13.90s

> rm -r dist || rm -r .parcel-cache || true && parcel build --no-content-hash --no-source-maps src/index.html

✨ Built in 20.37s

dist/index.html                   1.33 KB    13.59s
dist/logo.fde9f7fd.svg              355 B    13.58s
dist/app.webmanifest                450 B     837ms
dist/appIcon512.6a4fe200.png      6.09 KB    13.27s
dist/index.0c63f772.css            4.1 KB     1.13s
dist/index.62ba04f6.js          855.92 KB    13.31s
```

Is there a way to not have hashes in the filename please? It's confusing when trying to learn service workers and caching.

**Comment by mischnic** [comment]
The hash will still be dependent on some build options. It's just that "build", "change file", "build" won't change the hash.

**Comment by RichardJECooke** [comment]
> The hash will still be dependent on some build options. It's just that "build", "change file", "build" won't change the hash.

Ok, so how do I refer to these files correctly in my PWA's service worker if I don't want to have them go missing if I change something in my build please?

**Comment by mischnic** [comment]
You can do `import {manifest, version} from '@parcel/service-worker';` to get a file list, see https://parceljs.org/languages/javascript/#service-workers

**Comment by RichardJECooke** [comment]
Ok, the hashes are definitely not the same. I haven't changed any of my build commands and you can see here the filenames I cached are not the ones the dev server is supplying:
![image](https://github.com/parcel-bundler/parcel/assets/5468805/9e5341d2-3359-488d-9254-a876d4a69de7)

Secondly, the service workers documentation for Parcel is almost nonexistent - https://parceljs.org/languages/javascript/#service-workers.  How are filenames managed and added? The sample just imports something called manifest, but how does it get the filenames?

**Comment by RichardJECooke** [comment]
You can use this plugin to fully remove content hashes from your output - https://www.npmjs.com/package/parcel-namer-hashless

**Comment by RichardJECooke** [comment]
Ok, no, that plugin doesn't work, Parcel gives the error `AssertionError [ERR_ASSERTION]: Bundles must have unique names` even though the final output has no duplicates. The engine is a bit broken.

**Comment by mischnic** [comment]
>  The sample just imports something called manifest, but how does it get the filenames?

A parcel plugin automatically injects a manifest.
https://github.com/parcel-bundler/parcel/blob/e46be4dfed1f71dbb1fa04c34cc23ff4eeecfa0f/packages/runtimes/service-worker/src/ServiceWorkerRuntime.js

**Comment by Taxi4you** [comment]
+1

I don't want hash, why Parcel forces it?
I just want index.js bundle and thats it.

**Comment by nemanjacosovic** [comment]
This zero-configuration approach has came around to bite me (all of us) in 🍑 when we've decided to go with Parcel. 
Several times I've hit the wall of poor docs, no docs, setup acrobatics to get things to work...
