### ISSUE TITLE
Relative async imports resolve to incorrect paths in some scenarios

### ISSUE THREAD

**Issue by marcins** [parcel-bundler/parcel#5906]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command

I have a minimal-ish reproduction here: https://github.com/marcins/parcel-path-bug-repro. See the README for repro steps.

The build command is:
`parcel build --no-scope-hoist src/packages/entry/entry-a.js src/foo/entry-b.js`

Note the issue does _not_ occur when scope hoisting is enabled.

In terms of the setup - essentially I have two entry points in different paths: `src/packages/entry/entry-a.js` and `src/foo/entry-b.js`, these get bundled to non-root paths in `dist`: `dist/packages/entry/entry-a.js` and `dist/foo/entry-b.js` (if the entry points are in the _same_ path they end up in the dist dir root).

`entry-b` imports a deeply nested module `import deep from './one/two/three/deep.js';`, that deeply nested module has an async import `import("../../four/also-deep")`.  At runtime this import resolves to `http://127.0.0.1:8080/dist/packages/entry/../also-deep.79273ef1.js` which is the wrong path since `also-deep` is at the root of `dist`.

I suspect it's something to do with the `../../..` relative `import` that causes the problem.

## 🤔 Expected Behavior

Parcel should try to load `http://127.0.0.1:8080/dist/also-deep.79273ef1.js`

## 😯 Current Behavior

Parcel tries to load `http://127.0.0.1:8080/dist/packages/entry/../also-deep.79273ef1.js`.

## 💁 Possible Solution

I haven't had a chance to dig into the Parcel sources yet to understand what's causing this. I assume there's an incorrect assumption about some path resolution somewhere.

## 🔦 Context

The scenario is based on the real world structure of Jira's FE codebase, and I ran into this issue when trying to bundle Jira with Parcel 2.

## 💻 Code Sample

https://github.com/marcins/parcel-path-bug-repro

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | `2.0.0-nightly.606`
| Node             | `v12.20.1`
| npm/Yarn         | `7.5.5`
| Operating System | `macOS 10.15.7`

**Comment by mischnic** [comment]
This should actually be minimal:

[Archiv.zip](https://github.com/parcel-bundler/parcel/files/6032009/Archiv.zip)


Looks like this happens because the two bundle-manifests somehow overwrite each other at runtime:
The bundle for entry-a.js contains
```js
require('./bundle-manifest').register(JSON.parse("{\"2TIM8\":\"foo/entry-b.js\",\"2SZKk\":\"deep.ee7535ae.js\"}"));
},{"./bundle-manifest":"3CXJ5"}],"3CXJ5":[function(require,module,exports) {
```
and the bundle for entry-b.js contains:
```js
require('./bundle-manifest').register(JSON.parse("{\"2TIM8\":\"foo/entry-b.js\",\"2SZKk\":\"deep.ee7535ae.js\"}"));
},{"./bundle-manifest":"3CXJ5"}],"3CXJ5":[function(require,module,exports) {
```
