### ISSUE TITLE
Parcel@next does not install

### ISSUE THREAD

**Issue by paul-f-maxson** [parcel-bundler/parcel#5925]
# 🐛 bug report

parcel@next does not install under yarn version 2, raspbian, node 11 (latest node raspbian supports)

## 🤔 Expected Behavior

yarn add -D parcel@next should result in the installation of parcel

## 😯 Current Behavior
```bash
$ yarn add -D parcel@next
➤ YN0000: ┌ Resolution step
➤ YN0032: │ @parcel/watcher@npm:2.0.0-alpha.10: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ node-addon-api@npm:3.1.0: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ @parcel/source-map@npm:2.0.0-alpha.4.13: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ node-addon-api@npm:2.0.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ request@npm:2.88.2 is deprecated: request has been deprecated, see https://github.com/request/request/issues/3142
➤ YN0061: │ har-validator@npm:5.1.5 is deprecated: this library is no longer supported
➤ YN0061: │ request-promise-native@npm:1.0.9 is deprecated: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
➤ YN0061: │ urix@npm:0.1.0 is deprecated: Please see https://github.com/lydell/urix#deprecated
➤ YN0061: │ resolve-url@npm:0.2.1 is deprecated: https://github.com/lydell/resolve-url#deprecated
➤ YN0061: │ highlight.js@npm:9.12.0 is deprecated: Version no longer supported. Upgrade to @latest
➤ YN0032: │ evp_bytestokey@npm:1.0.3: Implicit dependencies on node-gyp are discouraged
$ cat package.json 
{
  "name": "myapp",
  "version": "1.0.0",
  "main": "index.js",
  "author": "Me",
  "license": "MIT",
  "private": true
}
```

## 💁 Possible Solution

I noticed this in #4426, it seems like maybe the same problem? https://github.com/parcel-bundler/parcel/issues/4426#issuecomment-609418522

> This is the package.json of @parcel/source-map@2.0.0-alpha.4.7 that npm installs:
There is a "install": "node-gyp rebuild" script that we did not specify
>
> {
>   // ...
>   "license": "MIT",
>   "main": "./dist/node.js",
>   "name": "@parcel/source-map",
>   "scripts": {
>     "benchmark": "npm run benchmark:node && npm run benchmark:wasm",
>     "benchmark:node": "cross-env BACKEND=node node ./bench/run",
>     "benchmark:wasm": "cross-env BACKEND=wasm node ./bench/run",
>     "build:dev": "node-gyp rebuild --debug",
>     "compile-wasm": "make",
>     "install": "node-gyp rebuild", /// <<-------- where does this come from?
>     "lint": "prettier --write src/*.js",
>     "postinstall": "node-gyp-build",
>     "prebuild": "prebuildify --napi --strip --tag-libc",
>     "prepublish": "npm run transpile",
>     "rebuild": "rm -rf build && yarn build:dev",
>     "test": "npm run test:node && npm run test:wasm",
>     "test:node": "cross-env BACKEND=node mocha ./test/*.test.js",
>     "test:wasm": "cross-env BACKEND=wasm mocha ./test/*.test.js",
>     "transpile": "babel ./src/*.js --out-dir ./dist && flow-copy-source -v src dist",
>     "typecheck": "flow"
>   },
>   "version": "2.0.0-alpha.4.7"
> }
> Compare to: https://unpkg.com/browse/@parcel/source-map@2.0.0-alpha.4.7/package.json
> 
> Great, npm adds this as a default value: https://docs.npmjs.com/misc/scripts#default-values

## 🔦 Context

I really just want to use parcel 2 on raspberry pi

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Node             |  11
| npm/Yarn         | yarnv2
| Operating System | Raspbian

**Comment by mischnic** [comment]
The log you pasted doesn't actually contain any error, only warnings.

Here's an issue about source-map on Raspberry Pi: https://github.com/parcel-bundler/source-map/issues/33

**Comment by paul-f-maxson** [comment]
The problem isn't in yarn's output- it's that it doesn't result in parcel being added as a dependency, as evidenced by the subsequent `$ cat package.json`. It's extra odd that, as you point out, there are no errors.

**Comment by paul-f-maxson** [comment]
Don't waste too much sweat on this though, I think I'm just gonna avoid building on the Pi altogether and just use it as a dumb server
