### ISSUE TITLE
PostCSS setup: PreCSS for PostCSS not working

### ISSUE THREAD

**Issue by agepoor** [parcel-bundler/parcel#593]
### Intro
I'm new to Parcel, and I was trying to convert a simple existing Gulp project to a Parcel project. I'm not sure how to set up the PostCSS configurations though. I use PreCSS instead of Sass for variables with a '$' and some other functions. While the output gives no error it does not transform my variables, so the CSS won't work. What am I doing wrong here? How do I set up a transformation that will use the PreCSS plugin before the rest?

It's a bit similar to [this problem](https://github.com/parcel-bundler/parcel/issues/329), only with PreCSS instead of CSSNext .

### 🎛 Configuration

./.postcssrc
```
{
  "modules": false,
  "plugins": {
    "precss": {}, // Sass-like markup for PostCSS
    "autoprefixer": { "browsers": ["last 1 version"] },
/*     "postcss-calc": {}, // Reduces calc() in CSS by calculating values */
    "postcss-safe-important": {},
    "postcss-discard-comments": {}
  }
}
```

./index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Test page</title>
  <link rel="stylesheet" href="./src/style.css">
</head>
<body>
</body>
</html>
```

./src/style.css
```
@import "./variables.css";
@import "./styles.css";
```

**Comment by agepoor** [comment]
Update: I found out it does create a file with all the right transformations in the /dist folder, but index.html references to the wrong css file.

**Comment by olivoil** [comment]
I have PreCSS working by using `postcss.config.js` and the `variables` option. I haven't tried with `.postcssrc` but I assume it should work. One thing I've noticed is that if postcss has an error in the configuration and does not run properly, parcel will just silently ignore it.

**Comment by agepoor** [comment]
I can make it work, but postcss transforms files before it imports them, so variables and functions  that need to work across different files don't compile like they should.

**Comment by DeMoorJasper** [comment]
Not sure if this has been resolvedm but there are a couple issues that describe issues with config. Gonna close this due to inactivity and duplicates
