### ISSUE TITLE
Comparison with Webpack bundle size

### ISSUE THREAD

**Issue by YagoLopez** [parcel-bundler/parcel#594]
Hello. I discovered Parcel recently and am enjoying using it instead webpack. I always disliked webpack but I would like to know if there are big differences in bundle size or any other comparison or data. In my experience Parcel is considerably faster than Webpack, but not sure about bundle size. Anyway, I hope the future of build tools go in the Parcel direction instead of Webpack. (It's horrible 😄).

Thought this information could be interesting for other programmers that's why opened the issue. Hope not to breake the conduct guidelines. Thank you and congratulations for the great job

**Comment by Grafikart** [comment]
Here is a simple example :

## Source 

```javascript
import a from './a'
import b from './b'

console.log(a, b)
```

## Webpack (657b)

I used `webpack src/index.js dist/webpack.js --env.prod --env min --optimize-minimize`

```
!function(e){function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}var t={};n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{configurable:!1,enumerable:!0,get:r})},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},n.p="",n(n.s=0)}([function(e,n,t){"use strict";Object.defineProperty(n,"__esModule",{value:!0});var r=t(1),o=t.n(r),u=t(2),c=t.n(u);console.log(o.a,c.a)},function(e,n){e.exports="a"},function(e,n){e.exports="b"}]);
```

## ParcelJS (912b)

I used `parcel build src/index.js`

```
require=function(r,e,n){function t(n,o){function i(r){return t(i.resolve(r))}function f(e){return r[n][1][e]||e}if(!e[n]){if(!r[n]){var c="function"==typeof require&&require;if(!o&&c)return c(n,!0);if(u)return u(n,!0);var l=new Error("Cannot find module '"+n+"'");throw l.code="MODULE_NOT_FOUND",l}i.resolve=f;var a=e[n]=new t.Module;r[n][0].call(a.exports,i,a,a.exports)}return e[n].exports}function o(){this.bundle=t,this.exports={}}var u="function"==typeof require&&require;t.Module=o,t.modules=r,t.cache=e,t.parent=u;for(var i=0;i<n.length;i++)t(n[i]);return t}({3:[function(require,module,exports) {
module.exports="a";
},{}],5:[function(require,module,exports) {
module.exports="b";
},{}],1:[function(require,module,exports) {
"use strict";var e=require("./a"),u=l(e),r=require("./b"),t=l(r);function l(e){return e&&e.__esModule?e:{default:e}}console.log(u.default,t.default);
},{"./a":3,"./b":5}]},{},[1])
```

## Bonus

| Number of package |  Webpack | Parcel |
| --- | --- | ---- |
|  2 | 657B | 657B |
|  1 | 610B | 808B |
|  0 | 494B | 636B |

You can also get some Bytes out using uglify on top of parcel

**Comment by YagoLopez** [comment]
Thank you very much. The information has been very useful. I wouldn't want to bother you but if in the future you have any benchmark about compilation times it would be useful as well.

My impression is Parcel is faster than Webpack but with less compression ratio. That seems to be logic and in my case I prefer faster iteration cycles over compression ratio. If you have any kind of impression regarding this topic I would like to know it. Thank you.

**Comment by Grafikart** [comment]
Parcel is faster for two reasons : 

- When building it caches every dependency in a `.cache` directory. Allowing the next build to be much faster if only one file changed.
- It splits parsing (resolving dependencies) and packaging (converting code) and use workers to make the best use of multi core system. So the speed gain may vary with your number of core. (webpack don't do things in parallel by default and you'll have to add another plugin like [happypack](https://github.com/amireh/happypack).

You can read more about what's under the hood in the [doc](https://parceljs.org/how_it_works.html) or looking at the code (even if it's not commented :( you can understand how Asset / Packager and Transform work)

**Comment by YagoLopez** [comment]
It awesome to use multithreading in a single-threaded language as javascript, great idea, and I agree about parcel/rollup suggestion. Other question is about source maps, but I think it's duplicated in other issue. I'll take a look. Anyway thanks again.
