### ISSUE TITLE
Caching environment variables between environments 

### ISSUE THREAD

**Issue by tonymaynard** [parcel-bundler/parcel#5940]
# 🐛 bug report

When using with postHTML Parcel caches the environment variable between builds which results in the same env variable being applied across different environments. 

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
in package.json:
  "babel": {
    "presets": [
      "@babel/preset-env",
      "@babel/preset-react"
    ],
    "plugins": [
      "@babel/plugin-transform-runtime"
    ]
  }

posthtml.config.js:
module.exports = {
  plugins: {
    "posthtml-expressions": {
      locals: {
       URL: process.env.URL_INJECTED_IN_HTML,
      },
    },
  },
};
```

## 🤔 Expected Behavior
The script tag in the index html file has the url 'some-nonprod-url'

## 😯 Current Behavior
The script tag in the index html file has the url from the first build, i.e. 'foo' which was read from the `.env` file. I think this is happening due to the caching, when I run a build with --no-cache we don't experience this issue.

## 🔦 Context

Currently cannot take advantage of the caching feature and I have to run without cache enabled when building.

## 💻 Code Sample

Using a .env file with the following entry:
```js
URL_INJECTED_IN_HTML='foo'
```
Then when ran in a jenkins file with similar step to below:

```js
        stage('End to End Test' ) {
            steps {
                     withNvm("yarn build")
                     withNvm("yarn e2e")
            }
...
        stage('Build for nonprod') {
            steps {
               sh "rm -rf /dist"
              withNvm("URL_INJECTED_IN_HTML=some-nonprod-url yarn build")
            }
        }
        }
```
The url in the application is the one found in the .env file, But when using --no-cache the url is `some-nonprod-url`
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.4
| Node             | 12.14
| Yarn         | 1.22.4
| Operating System | Linux
| posthtml-expressions | 1.7.1
| @babel/plugin-transform-runtime | 7.8.4

**Comment by devongovett** [comment]
I think this should be fixed by #5802. JS configs will be invalidated when parcel restarts.

**Comment by tonymaynard** [comment]
@devongovett Thanks, will take a look.

**Comment by devongovett** [comment]
Going to close as the PR is merged. It should be available in the latest v2 nightly shortly.
