### ISSUE TITLE
V2 fails to bundle programatically

### ISSUE THREAD

**Issue by TomzBench** [parcel-bundler/parcel#5942]
# 🐛 bug report

I am experimenting with the V2 API for programmatically creating a bundle.  I simply run the example from the docs:

```javascript
import path from "path";
import Parcel from "@parcel/core";

(async () => {
  let bundler = new Parcel({
    entries: path.join(__dirname, "src/index.js"),
    defaultConfig: require.resolve("@parcel/config-default"),
    defaultTargetOptions: {
      engines: {
        browsers: ["last 1 Chrome version"],
        node: "10",
      },
    },
    mode: "production",
  });

  await bundler.run();
})();
```
will throw error:
```
(node:115005) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "to" argument must be of type string. Received undefined
```
I dug into what is going on a little bit, and it seems that resolving the default config is incorrect. I believe the bundler expects a config, and the example is passing a string.
```
require.resolve("@parcel/config-default"),
```
I tried removing the `resolve` and still get errors. 

So the main question I guess is is V2 API stable? Or experimental?  Should I use V1 if using API instead of command line?

**Comment by mischnic** [comment]
The docs reflect the latest nightly, you might be using an older version. Try installing `@parcel/core@nightly` and `@parcel/config-default@nightly`

**Comment by TomzBench** [comment]
@mischnic 

Thanks, this seems to work better.
