### ISSUE TITLE
🐛 Babel Unknown Plugin transform-decorators-legacy

### ISSUE THREAD

**Issue by BlueBlazin** [parcel-bundler/parcel#596]
Running parcel is throwing the following error:
`Unknown plugin "transform-decorators-legacy" specified in...`

My .babelrc looks like this:

```
{
  "presets": ["env"],
  "plugins": [
    "transform-decorators-legacy",
    "transform-class-properties"
  ]
}
```

Relavent package.json:

```js
"devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators": "^6.24.1",
    "babel-preset-env": "^1.6.1",
```

**Comment by splodingsocks** [comment]
@BlueBlazin I'm running into this issue. It's saying that a babel plugin specified by a dependency is an Unknown plugin. Why'd you close this issue? Did you solve it somehow?

**Comment by splodingsocks** [comment]
Ah, it appears that it's being discussed here:
https://github.com/parcel-bundler/parcel/issues/13

For those coming along after me, a workaround is to just take the compiled output of whatever lib you're using and copy it directly into your project (if that's acceptable for your pipeline).
