### ISSUE TITLE
[2.0.0-beta.1] Source maps are not served

### ISSUE THREAD

**Issue by richthegeek** [parcel-bundler/parcel#5966]
# 🐛 bug report

Source map requests are not intercepted by the bundle server, instead the index.html is loaded.

This prevents source maps from working of course!

## 🎛 Configuration (.babelrc, package.json, cli command)

Configs are in this gist: https://gist.github.com/richthegeek/e7de4375b24eb06ad554396747687db1

CLI command is `yarn start` which runs `parcel serve ./src/index.html`

## 🤔 Expected Behavior

Source maps should be loaded from the server and used by the browser.

## 😯 Current Behavior

Source map requests render the built index.html.

![Screenshot 2021-03-05 at 14 26 25](https://user-images.githubusercontent.com/613900/110121528-c9eddf80-7dbe-11eb-8d47-b734704ca6a5.png)

## 💻 Code Sample

Ask if needed, sorry but I'm not sure what code would be useful to you here!

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | 14.15.1
| npm/Yarn         | 1.22.4
| Operating System | OSX 10.15.7

**Comment by OzzyCzech** [comment]
this is mention also here #5965

**Comment by mister-good-deal** [comment]
Same problem here for version `2.0.0-nightly.389` and `2.0.0-nightly.628` on both firefox-dev and chrome browers.

**Comment by typeofweb** [comment]
Same on `2.0.0-nightly.630`.
