### ISSUE TITLE
Parcel produces wrong output in typescript type definition files (circular dependencies)

### ISSUE THREAD

**Issue by benoitgrelard** [parcel-bundler/parcel#5967]
# 🐛 bug report

It seems **parcel** doesn't handle renamed imports (`import { something as somethingElse } …`) correctly within type definition files. Instead it produces a completely wrong output which references the wrong import thus creating circular dependencies.

## 🎛 Configuration (.babelrc, package.json, cli command)

- basic config
- no `.babelrc`
- only installed latest (`2.0.0-nightly.615`)

Package.json below 👇 

```json
{
  "name": "parcel-test",
  "version": "1.0.0",
  "description": "",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "source": "index.ts",
  "scripts": {
    "build": "parcel build index.ts"
  },
  "keywords": [],
  "author": "Benoît Grélard",
  "license": "ISC",
  "devDependencies": {
    "@parcel/packager-ts": "2.0.0-nightly.617",
    "@parcel/transformer-typescript-types": "2.0.0-nightly.617",
    "parcel": "2.0.0-nightly.615",
    "typescript": "^3.0.0"
  }
}

```

Setup:

```ts
// log.ts
export function log(message: string) {
  console.log(message);
}
```

```ts
// index.ts
import { log as logFn } from './log';

export function log(message: Parameters<typeof logFn>[0]) {
  return logFn('my app mesasage: ' + message);
}
```

## 😯 Current Behavior

```ts
// index.d.ts
declare function _log1(message: string): void;
export function log(message: Parameters<typeof log>[0]): void;

//# sourceMappingURL=index.d.ts.map

```

![image](https://user-images.githubusercontent.com/1539897/110159484-af2d6200-7de2-11eb-9dfb-9362ed13f6b6.png)

## 🤔 Expected Behavior

It seems parcel understands the fact that we are importing as renamed to avoid code conflict as the output contains a renamed `_log1` function (allbeit differently named than our renamed one `logFn`) but then it references the wrong one in the arguments, thus creating a circular dependency.

I would expect at the very least that it would reference the correct function…

```diff
declare function _log1(message: string): void;
-export function log(message: Parameters<typeof log>[0]): void;
+export function log(message: Parameters<typeof _log1>[0]): void;

//# sourceMappingURL=index.d.ts.map
```

## 🔦 Context

This is a big issue for us as it's outputting wrong types which are affecting the users of our library.
See this issue as an example: https://github.com/radix-ui/primitives/issues/472

We managed to get around it by using the `import * as something` syntax but that is a serious bug IMO.
It may also be related to another **parcel** issue we have had with `export as` syntax: https://github.com/parcel-bundler/parcel/issues/5424

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.615
| Node             | v12.20.2
| npm/Yarn         | yarn
| Operating System | MacOS 11.2.2

**Comment by benoitgrelard** [comment]
Thanks for fixing this! Do you have an idea of when it'll get released? Thanks!

**Comment by mischnic** [comment]
It's already in a nightly version

**Comment by benoitgrelard** [comment]
I can confirm that issue is fixed.
However, I can also confirm that the other issue I thought was related (and thought may be resolved at the same time) is still an issue: https://github.com/parcel-bundler/parcel/issues/5424

It does seem like a similar problem though as it's to do with the `as` syntax, but for exporting this time rather than importing.
