### ISSUE TITLE
web socket error

### ISSUE THREAD

**Issue by MatthewSmithwebdesign** [parcel-bundler/parcel#597]
I am getting this strange error in the console inspecting the page brought me to the .js file in the dist folder highlighting this line.
it's line 31
var ws = new WebSocket('ws://' + window.location.hostname + ':50013/');

i haven't went in to that file or changed anything in it.

any help would be great I am running a windows pc and haven't had any issues with parcel before.

**Comment by serranoarevalo** [comment]
@MatthewSmithwebdesign how did you fix it?

**Comment by MatthewSmithwebdesign** [comment]
i didn't no one responded so i started over without parcel

**Comment by DeMoorJasper** [comment]
Could u give us the specific error that the console throws? Than we might be able to help
@MatthewSmithwebdesign

**Comment by MatthewSmithwebdesign** [comment]
WebSocket connection to 'ws://localhost:58197/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
require.8 @ ..\..\..\..\AppData\Roaming\npm\node_modules\parcel-bundler\src\builtins\bundle-url.js:11

**Comment by DeMoorJasper** [comment]
Ow damn that's def weird, u on the latest version of parcel?

**Comment by MatthewSmithwebdesign** [comment]
how do u check the version?

**Comment by DeMoorJasper** [comment]
Normally parcel -V should work

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MatthewSmithwebdesign** [comment]
1.5.0

**Comment by fathyb** [comment]
@MatthewSmithwebdesign do you use any anti-virus or firewall? Parcel use random ports, on Windows this can be blocked by firewalls and anti-viruses.

Also you could help us by running this command and giving us the output of `netstat -a -b` in the Command Line Prompt while Parcel is running.
This will show uses what port are used and if they are blocked. Thanks

**Comment by MatthewSmithwebdesign** [comment]
The requested operation requires elevation.

**Comment by fathyb** [comment]
You might need to start the Command Prompt as Administrator for this one

**Comment by serranoarevalo** [comment]
In my case I just had to delete the .cache and dist folder and everything started working again.

**Comment by jmanuelcorral** [comment]
Hi, There is a way to setup this WS  port? I am working with Docker and I have to expose the port to the host machine.

**Comment by DeMoorJasper** [comment]
@jmanuelcorral yes, using —hmr-port

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thiagomajesk** [comment]
@Ponokefalos Same here, have you found a solution yet?

**Comment by phocks** [comment]
I've been getting this error too on this code [https://glitch.com/~parcel-js](https://glitch.com/~parcel-js)

I'm using `parcel watch index.html` so it doesn't spin up a web server and so I'm serving the files with Express, so I guess that's why.... Is there any way to stop it from requiring websockets? when using "parcel watch"?

Does it do the same in production build?

**Comment by byF** [comment]
If anyone comes across this as I did, use [`--no-hmr`](https://parceljs.org/cli.html#disable-hmr) flag. I think it's a bug where HMR should be disabled by default for `watch`.
