### ISSUE TITLE
Discrepancy with parcel@next transformers, the documentation, and confusing/unclear authoring instructions

### ISSUE THREAD

**Issue by Qix-** [parcel-bundler/parcel#5974]
> Apologies for deviating from the bug report template - I was having issues fitting the information neatly into the pre-defined fields as this is a bug report, feedback, and support request all in one. I apologize for the length.

Firstly, version info:

```
Welcome to Node.js v15.3.0.
Type ".help" for more information.
> require('parcel/package.json').version
'2.0.0-nightly.619+28eec7be'
> require('@parcel/plugin/package.json').version
'2.0.0-nightly.621+28eec7be'
```

---

I am attempting to port over https://github.com/tinchoz49/parcel-plugin-surplus to `parcel@next` (v2 plugin) as a Transformer.

There appears to be a discrepancy with the documentation on the [_Authoring Plugins_ page](https://v2.parceljs.org/plugin-system/authoring-plugins/) about the naming convention for transformers.

It states in one place that community packages should match `parcel-transformer-{name}` (with the `-er` suffix on `transformer`) but then later uses the `parcel-transform-{name}` convention (sans `-er`). In my own attempt to port a v1 plugin, it appears the **latter** is the only way Parcel picks up the plugin.

However, this is confusing, as looking at the Vue transformer for reference shows its [package.json's `"name"` key](https://github.com/parcel-bundler/parcel/blob/28eec7be0a7dc709f1142e49543d7a3770d60980/packages/transformers/vue/package.json#L2) as `@parcel/transformer-vue` (*with* the `-er` suffix), so I'm not sure if that plugin is broken or if there is conflicting logic within Parcel itself.

Just wanted to let you know. I would submit a PR but I've no idea where the actual issue is, or what the "correct" behavior should be.

**EDIT** This is fixed in parcel-bundler/website#829.

---

I'm also having issues with the port. [Surplus's compiler](https://github.com/adamhaile/surplus) is a simple text->text transformer (with an optional text->{source, map} overload, which is what I'm using). There is no configuration, no ASTs involved - it's quite simple.

First, what happens with a `.jsx` file with a `surplus` component **without** the plugin is that Parcel automatically tries to compile the JSX to a React-compatible source file. Everything else works fine - except that at runtime, the webpage errors with `Cannot find package 'react'`. This is expected (well, not _expected_ but it makes sense - personally I don't think we should treat React as a special-case or "defacto" but that's just my opinion).

I now want to augment this process by intercepting `.js` and `.jsx` assets, detecting a `surplus` import and then transforming them. The check is important - there's a [bug with the Surplus compiler](https://github.com/tinchoz49/parcel-plugin-surplus/issues/7) in certain cases with edge-case Javascript syntax, so targeting _just_ the files that need it is imperative.

I started with just a minimal transformer, raising an exception in the transform method.

```javascript
import { Transformer } from '@parcel/plugin';
import SurplusCompiler from 'surplus/compiler';

export default new Transformer({
	async transform({ asset, config, logger, resolve, options }) {
		throw new Error('skjskfjda');
	}
});
```
```json
{
  "name": "parcel-transform-surplus",
  "description": "Surplus compiler plugin for Parcel@2",
  "files": [
    "index.js"
  ],
  "engines": {
    "parcel": "2.x"
  },
  "keywords": [
    "parcel",
    "surplus",
    "transformer",
    "plugin",
    "compiler",
    "s.js",
    "adam",
    "haile"
  ],
  "dependencies": {
    "@parcel/plugin": "2.0.0-alpha.3"
  },
  "peerDependencies": {
    "surplus": "^0.5.3"
  }
}
```

However, this... just doesn't work. **Without** the plugin everything is okay (I get `Built in 5.13s` and Parcel serves me the React-expectant page) but **with** the plugin, I get a bunch of EventEmitter leak error messages, and... Parcel still serves me the React-expectant page.

```
> start
> parcel serve --dist-dir dist ./src/index.html

ℹ️ Server running at http://localhost:1234
console: (node:9618) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 unpipe listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
console: (node:9618) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
console: (node:9618) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 close listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
console: (node:9618) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 finish listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
✨ Built in 5.13s
```

I was hoping to see Parcel die in a hellfire when the plugin threw the exception, but.. nothing.

How do I get this to work? The page about Transformers just shows the skeleton (most of the methods are irrelevant to my plugin) but no additional information aside from class documentation.

For what it's worth, I first started my attempt with some rudimentary, catch-all transform logic before realizing Parcel wasn't going to show me any errors. I replaced this with the `throw` statement above just to debug, and came here to file this issue after Parcel refused to help me out 😅 

```javascript
	async transform({ asset, config, logger, resolve, options }) {
		const source = await asset.getCode();
		const { src: content, map } = SurplusCompiler.compile(
			source,
			{ sourcemap: 'extract' }
		);

		return [{
			content, map,
			type: 'js',
			uniqueKey: asset.id + '-surplus'
		}];
	}
```

Is there somewhere else that explains how to write a simple transformer? I'm not sure how to even get Parcel to show me errors, so debugging becomes a bit of a PITA.

**Comment by Qix-** [comment]
Interestingly, pasting the `package.json` into the above issue revealed a missing `,`, which should have resulted in a JSON syntax error when installing the package. However, unsurprisingly, `npm` failed to mention that during the install process.

Adding the comma did not change any behavior - the output from Parcel remains the same.

**Comment by Qix-** [comment]
Alright so I brought up a chrome inspector in my test project:

```console
$ node --inspect-brk --trace-warnings node_modules/.bin/parcel serve --detailed-report 10 --dist-dir dist -- src/index.html
```

After building and inspecting the source tree in the inspector, it appears Parcel _is not_ importing my plugin.

I manually tried to `require('parcel-transform-surplus')` in the inspector console and, naturally, got an error about `import`. Until now, I assumed Surplus was transforming plugin sources from ESM syntax to CJS syntax but I decided to err on the side of caution and changed the `import`s to `require()`s.

This resulted in the `EventEmitter` leak error messages to go away, but Parcel still seems to not be importing my plugin (at least, it's still not in the inspector source tree). Manually `requiring()` the transformer works, however.

As a final test, I named the plugin back to `parcel-transformer-surplus` (with the `-er` suffix, which previously didn't work). No change in behavior.

I'm stumped.

**Comment by Qix-** [comment]
Further, trying to get verbose logs from Surplus with `--log-level verbose` as documented on the [_CLI (General Parameters)_ page](https://v2.parceljs.org/features/cli/#general-parameters) appears to do nothing:

```console
$ node --trace-warnings node_modules/.bin/parcel  build --log-level verbose --detailed-report 10 --dist-dir dist -- src/index.html
```

As well, running `build` as opposed to `serve` shows more `EventEmitter` leak warnings.

**Comment by Qix-** [comment]
&ast;sigh&ast; Alright well digging around a bit more, something that was not at all obvious is that Parcel@2 is no longer "zero configuration" as the project boasts. **Please update this** as it's incredibly misleading (and in this case, time-wasting...)

![image](https://user-images.githubusercontent.com/885648/110274973-689d5a80-7fd0-11eb-9d6d-449193b1b7f2.png)
![image](https://user-images.githubusercontent.com/885648/110275005-79e66700-7fd0-11eb-86de-b41e8bba7fb2.png)
![image](https://user-images.githubusercontent.com/885648/110275029-8a96dd00-7fd0-11eb-83b0-79ba5ee5bafb.png)

This all coming before the "v2 might have changed this" disclaimer, I assumed that was still the case.

---

I created a simple `.parcelrc` in my test project:

```json 
{
  "transformers": {
    "*.{js,jsx,ts,tsx}": [
      "parcel-transform-surplus"
    ]
  }
}
```

Which promptly spit out:

```
> start
> parcel serve --dist-dir dist ./src/index.html

@parcel/core: Invalid Parcel Config
.parcelrc:4:4
  3 |     "*.{js,jsx,ts,tsx}": [
> 4 |       "parcel-transform-surplus"
>   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^ Parcel transformer packages must be named according to "parcel-transformer-{name}"
  5 |     ]
  6 |   }
```

So I suppose that's the correct behavior after all. Some of the package names need to be updated [here](https://v2.parceljs.org/plugin-system/authoring-plugins/#engines), then.

---

After changing the package name to `parcel-transformer-surplus`, updating `.parcelrc`, and trying again, Parcel hangs with no output.

I realize Parcel@2 is beta, but this along with #5943 making Parcel@1 almost unusable, is forcing me to switch to something else. It's just too broken. Sorry guys.

**Comment by DeMoorJasper** [comment]
@Qix- the thing about Parcel 2 is that you can configure it if you want.

This also means you can overwrite the entire config, resulting in the possibility of not defining any bundlers, optimizers, ... and parcel hanging because it's configured to do nothing. We should probably throw an error in this case.

I think you want something like this:
```
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{js,jsx,ts,tsx}": [
      "...",
      "parcel-transform-surplus"
    ]
  }
}
```

**Comment by mischnic** [comment]
(If you have a "something to JS" compiler, you'll want `"*.{js,jsx,ts,tsx}": ["parcel-transformer-surplus", "..."]` so that Parcel's default JS handling still runs afterwards.)

**Comment by mischnic** [comment]
Please open a new issue/discussion for a specific problem if you run into anything else
