### ISSUE TITLE
'npm i parcel -D' shows high vulnerability found, 'npm start' shows ELIFECYCLE error.  

### ISSUE THREAD

**Issue by ShardulAwate** [parcel-bundler/parcel#5977]
First when I tried to install parcel by using "npm i parcel -D" ...this happened.
![Capture](https://user-images.githubusercontent.com/79828473/110626334-716b6900-8155-11eb-8c04-12e683c519e2.JPG)

then I tried directly updating dependencies 'package.json' file by myself and then running "npm install" <- This command.
It actually worked.

![Capture again](https://user-images.githubusercontent.com/79828473/110626771-fe162700-8155-11eb-90ae-45c3d5aeea2f.JPG)

but after that when I tried to run parcel by command "npm start" it showed ELIFECYCLE error.

![Capture3](https://user-images.githubusercontent.com/79828473/110626987-46354980-8156-11eb-9aa7-1d6ed4cea60a.JPG)

Right now I am using:
Windows 10 64bit
npm version: 6.14.11.
nodejs version: v14.16.0.

**Comment by mischnic** [comment]
> but after that when I tried to run parcel by command "npm start" it showed ELIFECYCLE error.

Please post the actual error, above `code ELIFECYCLE`

**Comment by igorcmelo** [comment]
I am having this vulnerability issue and `npm audit fix --force` does not seems to fix it.

**Comment by mischnic** [comment]
For the "vulnerability", see https://github.com/parcel-bundler/parcel/issues/5564, https://github.com/parcel-bundler/parcel/issues/5250, https://github.com/parcel-bundler/parcel/issues/5204, https://github.com/parcel-bundler/parcel/issues/5145, https://github.com/parcel-bundler/parcel/issues/5145, https://github.com/parcel-bundler/parcel/issues/5045

**Comment by ShardulAwate** [comment]
Actual error, above code ELIFECYCLE

![Capture agin2](https://user-images.githubusercontent.com/79828473/110745406-0d49b300-81f0-11eb-9f72-be0d130bba05.JPG)

**Comment by mischnic** [comment]
Not sure why, the file `fs-search.win32-x64-msvc.node` does exist: https://unpkg.com/browse/@parcel/fs-search@2.0.0-nightly.2249/

**Comment by babul101** [comment]
Use this command: npm install parcel-bundler --save-dev
this will fix the issue
