### ISSUE TITLE
Changes in stylusrc imported files not being picked up

### ISSUE THREAD

**Issue by conlanpatrek** [parcel-bundler/parcel#5989]
# 🐛 bug report

I have a stylus file that I use to declare variables / functions. I include that file in the `imports` section of my stylusrc, so it's included automatically at the top of each styl file. I noticed that changes to this file don't trigger reloads on my server. Also I noticed that the contents of these files are not considered when looking up cached compilations.

## 🎛 Configuration (.babelrc, package.json, cli command)

Vanilla parcel configuration, but here is my .stylusrc.js

```js
const path = require('path')

module.exports = {
  "imports": ["global.styl"],
  "paths": [path.join(__dirname, "src")]
}
```

CLI command `parcel index.html --open`

## 🤔 Expected Behavior

Changes in stylus global includes should trigger reloads
Changes in stylus global includes should factor into which cached compilation gets served.

## 😯 Current Behavior

Changes to stylus files included this way don't reload my dev server.
Also currently, the cache isn't operating as expected. I can, say, add `html { color: red; }` in my config-included file. I can see this change if I then make a change to a stylus file that appears in the normal dependency graph (say, one pulled in by my js / html). I can just add a comment or something. If I then delete that comment, the page reloads as if a recompilation has occurred, but it will have reverted my red text.

Will include an example repo below.

## 💁 Possible Solution

I notice in the stylus transformer that we're doing some work with the paths. Maybe we can also iterate through the imports configuration and add them to the watchlist / dependency tree? (I'm not super familiar with the source, sorry if that's not helpful)

## 🔦 Context

Just trying to use the dev server. Having to keep restarting the server to get my updates.

## 💻 Code Sample

Here's a minimum recreation
https://github.com/conlanpatrek/parcel-stylus-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.623
| Node             | v14.15.4
| Yarn         | 1.22.10
| Operating System | macOS 10.14.6 (I know)

**Comment by mischnic** [comment]
Can you test whether the nightly version also has this problem?

**Comment by conlanpatrek** [comment]
Just switched my repro repo to `2.0.0-nightly.623` and the issue persists. Will update the description with this version.

**Comment by conlanpatrek** [comment]
Also, that installed `@parcel/transformer-stylus@2.0.0-nightly.625` (just so you have the full picture)

**Comment by mischnic** [comment]
1. Problem: Changing .stylusrc doesn't update the generated CSS.
stylus is rerun to re-compile to CSS, but somewhere down the line, Parcel incorrectly reuses a previous cached result. Might be the same problem as https://github.com/parcel-bundler/parcel/issues/5965

2. Problem: Changing files specified in `"imports"` doesn't trigger a rebuild.
 That should be somewhat easy to fix, by calling `asset.addIncludedFile(entry)` for the files in the config

**Comment by conlanpatrek** [comment]
@mischnic This was still affecting me, so I took a stab at a PR for this. I hope that's okay. #6587
