### ISSUE TITLE
Can't use an iframe when using development server

### ISSUE THREAD

**Issue by atrauzzi** [parcel-bundler/parcel#5992]
I get the message `Refused to display 'https://[whatever]/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.` when trying to do a simple iframe with the development server.

```html
<!doctype html>
<html>
    <head>
        <title>No iframes!</title>
    </head>
    <body>
        <div>
            <iframe src="https://www.google.com"></iframe>
        </div>
    </body>
</html>
```

Is there any way to configure the `x-iframe-options` that it serves?

**Comment by DeMoorJasper** [comment]
Not sure where this error originates from but you might give proxy a try: https://v2.parceljs.org/features/api-proxy/
