### ISSUE TITLE
transformer-postcss default.fromJSON is not a function

### ISSUE THREAD

**Issue by andrew-anguiano** [parcel-bundler/parcel#5993]
# 🐛 bug report
I'm attempting to use SCSS/CSS modules with Parcel 2 beta 1 however, as soon as I add a module import, I get the following error:
```
🚨 Build failed.
@parcel/transformer-postcss: _postcss(...).default.fromJSON is not a function
TypeError: _postcss(...).default.fromJSON is not a function
    at Object.transform (/Users/andrew/code/_pff/euclid/assets/node_modules/@parcel/config-default/node_modules/@parcel/transformer-postcss/lib/PostCSSTransformer.js:175:38)
    at async Transformation.runTransformer (/Users/andrew/code/_pff/euclid/assets/node_modules/@parcel/core/lib/Transformation.js:830:5)
    at async Transformation.runPipeline (/Users/andrew/code/_pff/euclid/assets/node_modules/@parcel/core/lib/Transformation.js:585:36)
    at async Transformation.runPipelines (/Users/andrew/code/_pff/euclid/assets/node_modules/@parcel/core/lib/Transformation.js:413:40)
    at async Transformation.runPipelines (/Users/andrew/code/_pff/euclid/assets/node_modules/@parcel/core/lib/Transformation.js:444:34)
    at async Transformation.run (/Users/andrew/code/_pff/euclid/assets/node_modules/@parcel/core/lib/Transformation.js:316:19)
    at async Child.handleRequest (/Users/andrew/code/_pff/euclid/assets/node_modules/@parcel/workers/lib/child.js:255:9)
✨  Done in 4.78s.

```

## 🎛 Configuration (.babelrc, package.json, cli command)
.babelrc
```js
{
    "presets": [
        "@babel/preset-env",
        "@babel/preset-typescript",
        ["@babel/preset-react",
          {
            "runtime": "automatic"
          }
        ]
    ]
}
```

## 🤔 Expected Behavior
The module is correctly imported and compiled.

## 😯 Current Behavior
The build fails

## 🔦 Context
This is a React app with Typescript and I can't use Parcel 2 with css modules. If change it from a module to a plain CSS import, it works fine.

## 💻 Code Sample
Component.tsx
```
import {FunctionComponent} from "react";
import {NavLink, NavLinkProps} from 'react-router-dom';

import styles from '../../styles/components/SidenavItem.module.scss';
// I've also tried `* as styles`...

export const SidenavItem: FunctionComponent<Pick<NavLinkProps, "to">> = (props) => {
  return (
    <NavLink {...props} style={styles.a}>
      {props.children}
    </NavLink>
  )
};
```

SidenavItem.module.scss
```
a {
  color: red;
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | `2.0.0-beta.1`
| Node             | `14.15.1`
| npm/Yarn         | `1.22.10`
| Operating System | MacOS 11.2.2 on a MacBook Air M1

**Comment by mischnic** [comment]
Can you test it with the latest nightly?

Also, we recommend using Parcel's babel presets: https://v2.parceljs.org/languages/babel/#extending-the-default-babel-config

**Comment by wmurphyrd** [comment]
Just observed the same with `parcel@2.0.0-nightly.623`

**Comment by andrew-anguiano** [comment]
@mischnic thanks for the response 🙂 I just tested with nightly and the babel presets recommended and still got the exact same error.

**Comment by mischnic** [comment]
This is actually caused by 
```
warning "parcel > @parcel/config-default > @parcel/transformer-postcss@2.0.0-nightly.627" has unmet peer dependency "postcss@^8.2.1".
```

because you at the moment, you need to add install `postcss` in the project yourself (so that's a workaround). But I admit that this isn't ideal (we have the same problem with `@babel/core`  at the moment)

**Comment by andrew-anguiano** [comment]
Ah, ok thanks for the tip! Feel free to close if you want.

**Comment by smurfpandey** [comment]
I am facing similar issue, and adding `postcss@8.2.1` as project dependency didn't help. After some digging, I think I found the issue.

Problem is `transfomer-postcss` depends on 3.2.2 version of `postcss-modules` which depends on `postcss@7.0.32`. 
```
@parcel/transformer-postcss -> postcss-modules@^3.2.2 -> postcss@^7.0.32 
```

Because of this dependency chain, the `postcss` version installed alongside `transform-postcss` is 7.0.32 which does not have `.fromJSON()` method.

**Comment by blvdmitry** [comment]
+1 to @smurfpandey. Chanding dependencies to postcss v7 helps us get past this error but then we get to the next one:
```
🚨 Build failed.
@parcel/transformer-postcss: input.toJSON is not a function
```
