### ISSUE TITLE
Build command ignores --dist-dir

### ISSUE THREAD

**Issue by predikdev** [parcel-bundler/parcel#5996]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "parcel2-boilerplate",
  "version": "1.0.0",
  "description": "Parcel 2 Boilerplate",
  "main": "index.html",
  "author": "PredikDev",
  "license": "MIT",
  "scripts": {
    "start": "parcel serve ./src/index.html --dist-dir dev",
    "build": "parcel build ./src/index.html --dist-dir dist"
  },
  "devDependencies": {
    "parcel": "^2.0.0-beta.1"
  }
}
```

## 🤔 Expected Behavior

I'm expecting, that **build** command will make new **dist** folder and there will be created files.

## 😯 Current Behavior

When I run **build** command, it will make new files in **current** directory, where is **package.json** located and in the console I become error as below:

```bash

console: (node:5868) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
console: (node:5868) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 13 close listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit

```
My folder structure

```
parcel2-boilerplate
|
|----- /dist
|----- /src
|----- .gitignore
|----- package.json
|----- README.md
|----- yarn.lock

```

## 💁 Possible Solution

Propably use **targets**, but I tried that too and it not work either.

## 🔦 Context

I am trying to do some simple boilerplate, which I can use on my simple projects and I don't want to everytime make this whole process again.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | Parcel 2.0.0 - beta.1
| Node             | v14.5.0
| Yarn         | 1.22.10
| Operating System | Windows 10 and macOS

**Comment by mischnic** [comment]
Remove this:
```
	"main": "index.html",
```

After that, your example works for me

**Comment by predikdev** [comment]
Thanks, now it works. 

Could you please in more detail explain, why this line causing problems?

**Comment by mischnic** [comment]
`"main": "index.html",` also specifies the output path for the bundle, and takes precedence over `--dist-dir`: https://v2.parceljs.org/getting-started/configuration/#setting-the-output-path

I've made a change to hopefully make that more clearer: https://github.com/parcel-bundler/website/pull/832
