### ISSUE TITLE
Builded project not working

### ISSUE THREAD

**Issue by Paul42812** [parcel-bundler/parcel#5999]
# 🐛 bug report
Im trying to make a Openlayers map on Github Pages. On the Openlayers repo i was told that it probably was a parcel issue

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "maps",
  "version": "1.0.0",
  "description": "",
  "main": "docs/index.html",
  "author": "",
  "assetsPath": "src/assets",
  "dependencies": {
    "ol": "6.5.0",
    "sass": "^1.32.8",
    "typescript": "^4.2.3"
  },
  "devDependencies": {
    "parcel": "^2.0.0-nightly.495"
  },
  "scripts": {
    "rm": "rm -R docs/*",
    "start": "cp -R src/assets docs && parcel src/index.html",
    "build": "cp -R src/assets docs && parcel build src/index.html"
  },
  "license": "ISC"
}

```
## 😯 Current Behavior

When started with `parcel <file>` the project starts as intendet, but when built using `parcel build <file>` and uploaded to github pages doesn't work

The console in the browser outputs `Loading failed for the <script> with source “https://paul42812.github.io/index.3ae6f9e7.js`

## 🔦 Context
Im trying to put an Openlayers map on Github Pages.

## 💻 Code Sample

https://paul42812.github.io/HZBT/
https://github.com/Paul42812/HZBT

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.0-nightly.495
| Node             | v10.23.2
| npm/Yarn         | 7.6.0
| Operating System | Linux manjaro

**Comment by mmiszy** [comment]
Looks like you're trying to load `https://paul42812.github.io/index.3ae6f9e7.js` but you should be `https://paul42812.github.io/HZBT/index.3ae6f9e7.js`

**Comment by ghost** [comment]
Works now
