### ISSUE TITLE
[Question] Can I use SCSS with parcel?

### ISSUE THREAD

**Issue by alanbuchanan** [parcel-bundler/parcel#60]
In the docs, I saw the loader I can use for PostCSS. But I didn't see anything for SCSS or Sass. Can I use it with parcel, and if so what package do I need?

**Comment by torosegon** [comment]
Built in. You need _node-sass_ package 
https://github.com/parcel-bundler/parcel/blob/master/src/assets/SASSAsset.js

**Comment by jeanleonino** [comment]
Just for reference, here it is on the documentation: https://en.parceljs.org/assets.html#scss
