### ISSUE TITLE
🤔 React SSR example

### ISSUE THREAD

**Issue by gregtillbrook** [parcel-bundler/parcel#600]
Hiya, I struggled to find a good example of how to setup a react ssr (server side rendered) app using parcel and ended up writing my own.  https://github.com/gregtillbrook/react-head-start

Im sharing the link here incase its of use to someone else.

**Comment by brandon93s** [comment]
@gregtillbrook - This looks great! Feel free to add it to [awesome-parcel](https://github.com/parcel-bundler/awesome-parcel) for others to discover.

**Comment by gregtillbrook** [comment]
Great idea, will do.

**Comment by albinotonnina** [comment]
@gregtillbrook this is great work! I'm taking inspiration, lots of solutions I didn't even know about

**Comment by gregtillbrook** [comment]
Thanks albinotonnina, glad to hear it's been useful.
