### ISSUE TITLE
Cannot resolve dependency '~hint.css/hint.min.css'

### ISSUE THREAD

**Issue by tnrich** [parcel-bundler/parcel#601]
Hey there, I'm hitting the following error 

```
/Users/tnrich/Sites/openVectorEditorTgen/src/style.css:3:1: Cannot resolve dependency '~hint.css/hint.min.css'
  1 | @import url(~@blueprintjs/core/dist/blueprint.css);
  2 | @import url(~react-select/dist/react-select.css);
> 3 | @import url(~hint.css/hint.min.css);
    | ^
```

It appears the file in question is indeed there:
![image](https://user-images.githubusercontent.com/2730609/35191798-4d92ccaa-fe39-11e7-8ab5-bf7d3b4635e3.png)

Any thoughts on why this is happening and how to fix it? 

Thanks!

**Comment by DeMoorJasper** [comment]
This is currently not a feature of parcel, it's already being discussed here: #336 and #25

**Comment by tnrich** [comment]
Thanks for the info!
