### ISSUE TITLE
🐛 bug report: error is occurred when we parcel a HTML file with links to other HTML files

### ISSUE THREAD

**Issue by zacky1972** [parcel-bundler/parcel#603]
🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

Configuration is as follows:

https://github.com/zacky1972/parcel-bug-20180121

package.json

```json
{
  "name": "parcel-bug-20180121",
  "version": "1.0.0",
  "description": "Website for enPiT everi",
  "main": "index.js",
  "repository": "git@github.com:zacky1972/parcel-bug-20180121.git",
  "author": "Susumu Yamazaki <zacky1972@gmail.com>",
  "dependencies": {
    "gulp": "^3.9.1",
    "gulp-coffee": "^3.0.2",
    "gulp-parcel": "^0.3.3",
    "jquery": "^3.3.0",
    "parcel-bundler": "^1.4.1"
  },
  "license": "MIT"
}
```

### 🤔 Expected Behavior

Run as follows:

```bash
$ gem install middleman slim
$ bundle install
$ yarn install
$ bundle exec middleman build
$ yarn parcel build build/index.html --out-dir dist --public-url ./
```

Then, index.html, index2.html and about/index.html should be parcelled. 

### 😯 Current Behavior

Run as follows:

```bash
$ gem install middleman slim
$ bundle install
$ yarn install
$ bundle exec middleman build
$ yarn parcel build build/index.html --out-dir dist --public-url ./
```

Then, the following error is occurred:

```bash
$ yarn parcel build build/index.html --out-dir dist --public-url ./
yarn run v1.3.2
$ .../parcel-bug-20180121/node_modules/.bin/parcel build build/index.html --out-dir dist --public-url ./
🚨  .../parcel-bug-20180121/build/index.html: Cannot resolve dependency './../../../..    at .../parcel-bug-20180121/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (.../parcel-bug-20180121/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (.../parcel-bug-20180121/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at .../parcel-bug-20180121/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:166:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### 💁 Possible Solution

Loading HTMLAsset might be wrong.

### 🔦 Context

I'm trying to parcel html files in a static web site by middleman, using gulp-parcel, which I'm developing.

### 💻 Code Sample

https://github.com/zacky1972/parcel-bug-20180121

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.4.1 |
| Node             | 9.4.0 |
| Yarn         | 1.3.2 |
| Operating System | macOS Sierra 10.12.6 |

**Comment by chrisdmacrae** [comment]
I ran into this issue and have come to the conclusion that it's caused by the md5.file action.

In most cases, this is caused by RawAsset trying to generate a hash for a dependency it cannot resolve on the filesystem.

I think parcel should check for an asset existing on the filesystem before trying to operate on it, and then be configurable to:

- Allow that asset to be ignored
- Or to throw an error

**Comment by chrisdmacrae** [comment]
I actually built a small plugin on top of HTMLAsset to patch the behaviour of `Asset.addDependency` to ensure that dependencies that can be resolved on the filesystem don't get added to the tree.

It isn't published yet, so in the meantime anyone can use the following code:

```
```
