### ISSUE TITLE
Uncaught Error: Minified React error #321 with parcel bundle file when bundle include react hook

### ISSUE THREAD

**Issue by Brew-Brew** [parcel-bundler/parcel#6036]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

babelrc
```js
{
	"presets": ["env","@babel/react"]
}
```

package.json
```js
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@storybook/addon-actions": "^6.1.15",
    "@storybook/addon-essentials": "^6.1.15",
    "@storybook/addon-links": "^6.1.15",
    "@storybook/react": "^6.1.15",
    "@types/classnames": "^2.2.11",
    "@types/react-dom": "^17.0.0",
    "babel-loader": "^8.2.2",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "parcel-bundler": "^1.12.4",
    "postcss-modules": "^3.0.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "sass-loader": "^10.1.1",
    "typescript": "^4.2.3"
  },
  "dependencies": {
    "classnames": "^2.2.6",
    "sass": "^1.32.5"
  },
  "peerDependencies": {
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  }
}

```

## 🤔 Expected Behavior

can use my library react component which is include react hook what was developed with parcel work well

## 😯 Current Behavior
i develop design system library with parcel, but when import my library component what includes react hook get error Minified react error. But component what does not includes react hook works well.

<img width="536" alt="스크린샷 2021-03-21 오후 5 45 37" src="https://user-images.githubusercontent.com/26598542/111899039-42b29400-8a6d-11eb-8cdd-04a8043be459.png">

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by Brew-Brew** [comment]
i install [parcel-plugin-externals](https://github.com/FlorianRappl/parcel-plugin-externals),  but it doesn't work with this error.

and my project repo what use my library was build with create react app

<img width="636" alt="스크린샷 2021-03-21 오후 6 00 13" src="https://user-images.githubusercontent.com/26598542/111899326-4cd59200-8a6f-11eb-9991-452f3ebfd0ae.png">

**Comment by harryhjsh** [comment]
Minified React error messages are just displayed when you've included a minfied/production version of React. The full error messages are removed for brevity - If you click [the link which React DevTools has provided for you](https://reactjs.org/docs/error-decoder.html/?invariant=321), you'll see the full error.

Make sure everything is up to date, that you're not importing React twice, and don't call a hook outside its own component. Also see [this page](https://reactjs.org/docs/hooks-rules.html).
