### ISSUE TITLE
parcel watch doesn't respect the --dist-dir

### ISSUE THREAD

**Issue by asprich** [parcel-bundler/parcel#6046]
# 🐛 bug report

When I run `npx parcel watch .\index.html`, it will output to the same root directory, overwriting my index.html file with the compiled one, which then looks like a change, thus causing it to fall into an endless loop creating multiple index.[hash].js files over and over.

Running  `npx parcel watch .\index.html --dist-dir .\wwwroot` has the same effect.

If I do build or serve instead of watch, they work totally fine with and with out the --dist-dir parameter.

To recreate:
1. npm init a new directory
2. install parcel
3. Add the most basic index.html and index.js files
4. run `npx parcel watch .\index.html`

## 🎛 Configuration (.babelrc, package.json, cli command)

I've made no config changes

```js
{
  "name": "parcel-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel": "^2.0.0-beta.2"
  }
}
```

## 🤔 Expected Behavior

I would expect the compiled code to be added to the wwwroot folder

## 😯 Current Behavior

Watch is stuck in an endless loop

## 💻 Code Sample

See the above, I've tried this on several different projects and its happening to me everywhere with the latest build.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-beta.2|
| Node             |v13.7.0|
| npm/Yarn         |6.13.6|
| Operating System |Windows 10 Pro|

**Comment by mischnic** [comment]
> `"main": "index.html",`

This line has multiple sideeffects, among of which is overriding `--dist-dir`

https://v2.parceljs.org/getting-started/migration/#package.json%23main

**Comment by asprich** [comment]
Ah... I did have a config change then. 

When you npm init, it creates the package.json file with "main" set to "index.js". 

Parcel gave me this feedback when I tried running the command above.

`
@parcel/namer-default: Target "main" declares an output file path of "index.js" which does not match the compiled bundle type "html".
C:\git\parcel-test\package.json:5:11
  4 |   "description": "",
> 5 |   "main": "index.js",
>   |           ^^^^^^^^^^ Did you mean "index.html"?
  6 |   "scripts": {
  7 |     "test": "echo \"Error: no test specified\" && exit 1"
Try changing the file extension of "main" in package.json.
`

I took the recommendation here. What should this be set to?

**Comment by asprich** [comment]
I understand now. Sorry, I didn't read that correctly I guess and pointed out exactly what the documentation says lol.  It may be helpful to let people know they're going to create an endless loop. Like Warning: your input file is the same as your output.

Thanks for the help! Sorry for the trouble! :D
