### ISSUE TITLE
🙋 HMR shouldn't reload unchanged contents

### ISSUE THREAD

**Issue by elsassph** [parcel-bundler/parcel#605]
### 😯 Current Behavior

Watcher will process and reload assets if you `touch` them.

### 🤔 Expected Behavior

If an asset's new processed content didn't actually change it shouldn't be HMR reloaded.

### 🎛 Configuration (.babelrc, package.json, cli command)

Just an `index.html` pointing to a vanilla `index.js`

### 🤔 Expected Behavior

When the processed content of a module doesn't change it shouldn't trigger an HMR reload.

### 😯 Current Behavior

Just `touch index.js` and the file will be re-processed and reloaded using HMR.

Re-processing is sensible, but the processed content may not change.

### 💁 Possible Solution

Keep the previous content hash and don't HMR reload the module if the processed content hash doesn't change.

### 🔦 Context

Working on a new language support where false positive fs changes may happen.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.4.1 |
| Node             | 8.9.4 |
| Yarn         | 1.3.2 |
| Operating System | Win and Mac |

**Comment by devongovett** [comment]
Not a problem in Parcel 2
