### ISSUE TITLE
JSRuntime: browser js loader rejects with an error Event, not an Error

### ISSUE THREAD

**Issue by wbinnssmith** [parcel-bundler/parcel#6052]
# 🐛 bug report

If loading js were to fail in a browser context with the global output format, the promise would be rejected with an error _Event_, not an Error object. This is not intuitive, and is inconsistent with real `import()`s in browsers and across how we implement this in other environments.

## 🤔 Expected Behavior

Should reject with an Error object instead. Real `import()`s can reject with a TypeError such as `TypeError: Failed to fetch dynamically imported module: http://localhost:5000/foo.js`.

## 😯 Current Behavior

If fetching the module fails, the promise returned by `import()` rejects with a DOM Error event.

https://github.com/parcel-bundler/parcel/blob/dea272f0708fdabfe11f844f189df6421e7a3b65/packages/runtimes/js/src/loaders/browser/js-loader.js#L20

## 💁 Possible Solution

Create our own error in the browser js loader that is shaped like what real `import()`s in browsers reject with in this case.

**Comment by wbinnssmith** [comment]
cc @peterwilliams

**Comment by mischnic** [comment]
> Create our own error in the browser js loader

That would be here:

https://github.com/parcel-bundler/parcel/blob/dea272f0708fdabfe11f844f189df6421e7a3b65/packages/runtimes/js/src/loaders/browser/js-loader.js#L17-L20

**Comment by mrkldshv** [comment]
Hi, I'd love to contribute! Can I work on this issue?
