### ISSUE TITLE
Transpilation differences between `parcel ..` and `parcel build`

### ISSUE THREAD

**Issue by achingbrain** [parcel-bundler/parcel#6056]
# 🐛 bug report

I have CJS dependencies that destructure required modules:

```js
const { foo: bar } = require('some-dep')

// use `bar`
```

These work as expected when using the dev server started by `parcel ./path/to/index.html` but if I run the js created by `parcel build ./path/to/index.html` it fails in the browser with errors similar to `bar is not defined`.

## 🎛 Configuration (.babelrc, package.json, cli command)

No config, only the defaults.

## 🤔 Expected Behavior

The code should be the same when created by the dev server or the bundle command.

## 😯 Current Behavior

See above.

## 💁 Possible Solution

🤷‍♂️ 

## 🔦 Context

Trying to build an app

## 💻 Code Sample

See above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-beta.2
| Node             |  15.11.0
| npm/Yarn         |  npm 7.6.0
| Operating System |  Mac OS X

**Comment by achingbrain** [comment]
This seems to be related to scope hoisting - if I pass the `--no-scope-hoist` flag it works as expected.

**Comment by ghost** [comment]
> --no-scope-hoist

I was getting the error `TypeError: Object.defineProperty called on non-object`. Adding `--no-scope-hoist` fixed that for me also.
