### ISSUE TITLE
Parcel 2: Code splitting generates syntax error in IE 11

### ISSUE THREAD

**Issue by martinsvoboda** [parcel-bundler/parcel#6059]
# 🐛 bug report

With code splitting, a bundle started to contains unsupported syntax (spread operator, Promise) even browserslist contains IE 11. This cause syntax error when running the bundle on IE 11.

## 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc
```js
{
  "presets": ["@parcel/babel-preset-env"],
  "plugins": [["@parcel/babel-plugin-transform-runtime"]]
}
```

package.json
```js
{
  "name": "parcel-code-splitting-ie11",
  "scripts": {
    "build": "parcel build index.js --dist-dir dist/"
  },
  "dependencies": {},
  "devDependencies": {
    "@parcel/babel-plugin-transform-runtime": "^2.0.0-beta.2",
    "@parcel/babel-preset-env": "^2.0.0-beta.2",
    "parcel": "^2.0.0-beta.2"
  },
  "browserslist": "IE 11"
}
```

index.js
```
console.log('index.js');

import('./extra').then(function(page) {
  console.log('test');
})

```

Running:
```
parcel build index.js --dist-dir dist/
```

## 🤔 Expected Behavior

The bundle should not contain unsupported syntax.

## 😯 Current Behavior

Bundle contains:
```
return new Promise((function(n,t){if([...document.getElementsByTagName("script")]
```

## 💻 Code Sample

Sample repository: https://github.com/martinsvoboda/parcel-code-splitting-ie11

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-beta.2
| @parcel/babel-plugin-transform-runtime             |  2.0.0-beta.2
| @parcel/babel-preset-env         |  2.0.0-beta.2

**Comment by mischnic** [comment]
That array spread comes from https://github.com/parcel-bundler/parcel/blob/2e760d2308502e3db221a6558f7c3eb4fa300d63/packages/runtimes/js/src/loaders/browser/css-loader.js#L6-L8

**Comment by martinsvoboda** [comment]
You are right, similar is in here https://github.com/parcel-bundler/parcel/blob/2e760d2308502e3db221a6558f7c3eb4fa300d63/packages/runtimes/js/src/loaders/browser/js-loader.js#L7

I suppose array spread and array function would be possible to rewrite with IE 9+ compatible code. Or do you recommend some other way, how to fix it?

**Comment by mischnic** [comment]
> I suppose array spread and array function would be possible to rewrite with IE 9+ compatible code

👍 

Array spread could become `[].concat(existingLinks)` and then regular function instead of arrow functions

**Comment by martinsvoboda** [comment]
> > I suppose array spread and array function would be possible to rewrite with IE 9+ compatible code
> 
> 👍
> 
> Array spread could become `[].concat(existingLinks)` and then regular function instead of arrow functions

I pushed the pull requests with the change. But I wonder if there isn't a problem with Babel layer. When I created the example package directly in parcel monorepo, yarn successfully transpile the output and remove array spread and arrow function. Also when calling like /path/to/monorepo/packages/core/parcel/src/bin.js build. But when I install Parcel as a dependency transpilation is not performed. Probably similar issue as #4951

**Comment by mischnic** [comment]
Yes, files inside node_modules aren't transpiled with Babel. That's why `js-loader.js` isn't transpiled when Parcel is installed as a dependency (inside `node_modules`)

**Comment by ghost** [comment]
Hey all, I'm seeing a similar issue when creating a barebones `<h1>Hello World</h1>` React with Parcel app. 

Some arrow functions are being left in the bundle which are causing a script error in IE11 stopping the application from loading.

Fyi I tried both **2.0.0-beta.2** and **2.0.0-nightly.631** with the same result. 

We recently upgrade from Parcel 1 to Parcel 2 and this is causing us an issue as we are currently supporting IE11 in production.  

Do you happen to have an ETA on a fix?  

Much appreciated!

**Comment by martinsvoboda** [comment]
Build **2.0.0-nightly.632** fixes this issue. @mischnic Thank you for your fast support!
