### ISSUE TITLE
🐛 live recompile not working when modifing scss imported from another scss

### ISSUE THREAD

**Issue by niicojs** [parcel-bundler/parcel#606]
**Choose one:** this is a 🐛 bug report 

### 🎛 Configuration (.babelrc, package.json, cli command)

No config necessary

### 🤔 Expected Behavior

Modifying a scss file (even burried in another scss file) should trigger a recompile

### 😯 Current Behavior

CSS is not recompiled, I have to modify something on the main scss to trigger a recompile

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.4.1
| Node             | 9.3.0
| npm/Yarn         | 5.5.1
| Operating System | Windows

**Comment by elsassph** [comment]
Ha! As I mention in my request for feedback #604, assets are lacking the concept of dependencies to watch to trigger an invalidation...

**Comment by bencodezen** [comment]
Running into the same problem here as well. It worked great for CSS, but not for SCSS.
