### ISSUE TITLE
Parcel Api watch() isn't working as I would expect.

### ISSUE THREAD

**Issue by asprich** [parcel-bundler/parcel#6064]
# 💬 RFC

I've looked at the documentation on the api and at the source code, but I cannot figure out how to do what the cli watch command does. 
https://v2.parceljs.org/features/parcel-api/

I'm in a situation where I need to use gulp, and I'm trying to kick off a watch. I see the bundler instance has a watch method on it, but it returns a subscription. I've seen test code where in some cases runNextBuild (or something like that) is called accepting the bundler instance as a parameter. What ever I'm doing isn't working though.

## 💻 Examples

Just make dir, init npm, and add an index.js file with some simple code.  
Then in package.json set "main" to "dist/index.js".

From the command line, I can run these 2 commands:
npx parcel build index.js
npx parcel watch index.js

And they both work as expected.

If I add this watch.js file with the following (this is just an example, not what I'm actually doing)
```javascript
const ParcelCore = require("@parcel/core");
const { default: Parcel } = ParcelCore;

const initFile = "./index.js";

(async function() {
    let bundler = new Parcel({
        entries: initFile,
        defaultTargetOptions: {
            sourceMaps: true,
            shouldOptimize: false
        },
        serveOptions: {
            https: true
        },
        LogLevel: "info",
        mode: "development"
    });
    
    //await bundler.run() -- this works
    await bundler.watch(); //this doesn't 
})();
```

Then run `node watch.js`, this does not work. It will just sit and wait, doesn't pick up changes and it doesn't build any code.

**Comment by asprich** [comment]
Ok, after doing a lot of playing around I suppose I was close. The seems to get me like 99% there, however I don't get any console output like I do when I run the command line command.

```javascript
const _defaultConfig = require("@parcel/config-default");
const ParcelCore = require("@parcel/core");
const { default: Parcel } = ParcelCore;

process.on('unhandledRejection', async (reason) => {
    console.log(reason);
    process.exit();
});

const initFile = "index.js";

(async function() {
    let parcel = new Parcel({
        entries: initFile,
        defaultConfig: _defaultConfig,
        serve: {
            https: true
        },
        logLevel: "debug",
        mode: "development",
        detailedReport: true,
        hot: {
            post: 1234,
            host: "localhost"
        },
        sourceMaps: true,
        minify: false,
        autoinstall: true
    });

    ({unsubscribe} = await parcel.watch((err,results) => {
        if (err) throw err;
        else if (results) console.log(results);
    }));
})();
```

**Comment by mischnic** [comment]
You need to pass them in separately, as the CLI does:

https://github.com/parcel-bundler/parcel/blob/59e6f1c8d364045e75d7291419d3a16395f6f171/packages/core/parcel/src/cli.js#L450-L452

https://github.com/parcel-bundler/parcel/blob/59e6f1c8d364045e75d7291419d3a16395f6f171/packages/core/parcel/src/cli.js#L481

**Comment by asprich** [comment]
Ah, I missed those when I was going through the cli file. Thanks so much, that solved it for me! Here's final working version. I still feel like it would help to include a similar example in the docs. :D

```javascript
const ParcelCore = require("@parcel/core");
const { default: Parcel } = ParcelCore;

process.on("unhandledRejection", async reason => {
    console.error(reason);
    process.exit();
});

(async () => {
    let parcel = new Parcel({
        entries: "./index.js",
        defaultConfig: require.resolve("@parcel/config-default"),
        sourceMaps: true,
        minify: false,
        env: { NODE_ENV: "development" },
        mode: "development",
        serve: { https: true },
        hot: { post: 1234, host: "localhost" },
        additionalReporters: [
            { packageName: '@parcel/reporter-cli', resolveFrom: __filename },
            { packageName: '@parcel/reporter-dev-server', resolveFrom: __filename }
        ]
    });

    await parcel.watch(err => {
        if (err) throw err;
    });
})();
```
