### ISSUE TITLE
Multiple Targets w/ Code Splitting sourceMap: false Causes Error

### ISSUE THREAD

**Issue by jgainfort** [parcel-bundler/parcel#6066]
# 🐛 bug report

When building for multiple targets, I have one that I want source maps and one where I don't. However it seems when building for the target that I don't want source maps for one of the code splitting bundles a source map is still expected and the following error is output:

```
[Error: ENOENT: no such file or directory, open '/path/to/project/dist/worker.121a9a54.js.map'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/path/to/project/dist/worker.121a9a54.js.map'
}
```

Looking at worker.121a9a54.js there is an unexpected sourceMappingURL `//# sourceMappingURL=worker.121a9a54.js.map`

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  ...
"main": "dist/lib.js",
  "dev": "dist/lib.dev.js",
  "targets": {
    "dev": {
      "includeNodeModules": true,
      "engines": {
        "browsers": "last 1 version"
      },
      "minify": false,
      "isLibrary": true
    },
    "main": {
      "includeNodeModules": true
    }
  },
  "scripts": {
    "build": "npm run clean && npm run build:prod",
    "build:dev": "npm run build:tsc && parcel build src/index.ts --target dev --log-level 4",
    "build:prod": "npm run build:tsc && parcel build src/index.ts --detailed-report",
    "build:tsc": "tsc -b",
    "clean": "rm -rf ./dist/* ./.parcel-cache && tsc -b --clean",
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
}
```

## 🤔 Expected Behavior

I would expect build to run without errors 

## 😯 Current Behavior

build errors with

```
[Error: ENOENT: no such file or directory, open '/path/to/project/dist/worker.121a9a54.js.map'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/path/to/project/dist/worker.121a9a54.js.map'
}
```

## 🔦 Context

I want to provide integrators of my lib a dev and production version. Dev should have source maps included and prod without.

## 💻 Code Sample

I am not able to provide a sample at the moment. 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1 |
| Node             | v14.15.5 |
| npm         | 7.6.3 |
| Operating System | macOS |

**Comment by mischnic** [comment]
Does this also happen with beta 2?

**Comment by jgainfort** [comment]
I missed the latest release. Updating to beta 2 solved the problem.
