### ISSUE TITLE
@parcel/transformer-babel Error 

### ISSUE THREAD

**Issue by CagriUysal** [parcel-bundler/parcel#6069]
# 🐛 bug report

When I run `yarn start` with parcel v2 in docker container, I get the following error. 
I made research on the topic but couldn’t find anything useful.
```
@parcel/transformer-babel: Config result is not hashable because it contains non-serializable objects. Please use config.setResultHash to set the hash manually.
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// .babelrc
{
  "presets": ["@babel/preset-typescript", "@emotion/babel-preset-css-prop"]
}
```

```js
// package.json
{
  "name": "react-app",
  "version": "1.0.0",
  "main": "src/index.jsx",
  "author": "CagriUysal",
  "license": "MIT",
  "private": true,
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@babel/preset-typescript": "^7.13.0",
    "@emotion/babel-preset-css-prop": "^11.0.0",
    "@types/reach__router": "^1.3.6",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@typescript-eslint/eslint-plugin": "^4.13.0",
    "@typescript-eslint/parser": "^4.13.0",
    "eslint": "^7.17.0",
    "eslint-plugin-react": "^7.22.0",
    "parcel": "^2.0.0-beta.2",
    "prettier": "^2.2.1",
    "typescript": "^4.1.3"
  },
  "dependencies": {
    "@apollo/client": "^3.3.6",
    "@emotion/react": "^11.1.4",
    "@reach/router": "^1.3.4",
    "apollo-link-token-refresh": "^0.3.2",
    "axios": "^0.21.1",
    "date-fns": "^2.17.0",
    "graphql": "^15.4.0",
    "jwt-decode": "^3.1.2",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  },
  "scripts": {
    "start": "parcel serve src/index.html",
    "build": "parcel build src/index.html"
  },
  "browserslist": [
    "last 1 Chrome version"
  ]
}
```

## 🤔 Expected Behavior

Parcel should bundle react code successfully.

## 😯 Current Behavior

I get the following error when I run `yarn start`,

```
@parcel/transformer-babel: Config result is not hashable because it contains non-serializable objects. Please use config.setResultHash to set the hash manually.
```

## 🔦 Context

I am trying to use parcel inside a docker container, it works fine in host machine but fails in the container.
I am aware this might be due to my wrongly configured Docker container, but I am also investigating this might due to the parcel v2.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |         v2.0.0-beta.2
| Node             |     v14
| npm/Yarn         | v1.22.5
| Operating System | Docker container, Alpine Linux 3.11

**Comment by CagriUysal** [comment]
Actually right now I am having the same problem in host also. My host machine is an MacOs Catalina.

When I install packages with `yarn install`, I get a warning which says,
```
warning "parcel > @parcel/config-default > @parcel/transformer-postcss@2.0.0-beta.2" has unmet peer dependency "postcss@^8.2.1".
```

Can the error related to this?

**Comment by mischnic** [comment]
No, postcss and babel don't have anything to do with each other

**Comment by CagriUysal** [comment]
**Update:** 

I guess I've found what was causing the issue, sorry for not including further information at first place.

My overall folder structure for this project as follows,

```
client
  | -- src/
     | -- pages/
     | -- components/
     | -- index.tsx
     | -- index.html
  | -- package.json
  | -- .babelrc
  ....
common ->> common folder has utility functions used both in client and server
  | -- util1.ts
  | -- util2.ts
  ....
server ->> server folder has its own package.json, irrelevant for parcel
  | -- src/
  package.json
  ....
``` 

Before I was dockerizing the project, there was a single `package.json` in the same level as *client* and *server* folders.
I've split the package.json into two separate package.json's for client and server.  At that point parcel started to return the error I've posted. I guess the problem is due to the following:

Right now I am running `yarn start` in the *client* folder, instead of *root* of the project. Some of the *components in the client*, imports from *common*, for example,

```javascript
// in client/src/component/A.tsx

import utils1 from ../../../common/utils1
```

When I copy the *common* folder into client and make path changes to the import statements, parcel works as expected.
So I guess parcel couldn't resolve imports from the sibling folders of *client*.
This seems the be same behavior as *create-react-app*, where you can only make imports in *src* folder with default configurations.

So I believe we can close the issue, but I want to ask, how can I resolve this issue right now, I really don't want to maintain my common folder in two different places(*server*, *client*), is there any way I can import from there to the client?
