### ISSUE TITLE
VIPS concurrency on single image processing causes segfaults

### ISSUE THREAD

**Issue by toastal** [parcel-bundler/parcel#6070]
# 🐛 bug report

Using `transformer-image` on my `manifest.webmanifest` file, I have a single SVG being used to generate several PNG files of varying sizes because many OSs are requiring PNGs. This seems like a common use case for this module, however it failed. Even `VIPS_CONCURRENCY=1` and `PARCEL_MAX_CONCURRENT_CALL=1` did not help. However, even sometimes with a single file, this can segfault as well.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json5
// vim: noai ts=2 sw=2
// vim: filetype=json5
// no file ext: https://github.com/parcel-bundler/parcel/issues/3430
{
  // https://github.com/parcel-bundler/parcel/blob/v2/packages/configs/default/index.json
  "extends": "@parcel/config-default",

  "transformers": {
    "*.{js,mjs,jsm,jsx,es6,cjs,ts,tsx}": [
      // Disabling unused React transformers
      // "@parcel/transformer-react-refresh-babel",
      "@parcel/transformer-babel",
      "@parcel/transformer-js",
      // "@parcel/transformer-react-refresh-wrap"
    ],
    "manifest.dhall": [
      "@toastal/parcel-transformer-dhall-webmanifest",
    ],
    "*.dhall": [
      "@toastal/parcel-transformer-dhall-json",
    ],
    // otherwise, don’t use `url:`
    "url:*.{avif,svg}": [
      "@parcel/transformer-image",
    ],
    // without `url:`, it is considered raw
    "*.svg": [
      "@parcel/transformer-raw"
    ],
  },
}

```

## 🤔 Expected Behavior

The build to not segfault. Either this module has special treatment for working on one file at a time or concurrency works as expected (probably upstream issue). I have not been able to test overriding the module's `sharp` with `sharp v0.28.0`, because my OS hasn't [upgraded to `libvips 8.10.6`](https://github.com/NixOS/nixpkgs/pull/117850) which is required, so I'm still on `v0.27.2`. The `vips` binary that `sharp` downloads isn't compatible with my OS.

## 😯 Current Behavior

When multiple `url:x.svg?as=png` are used, within the project, I get a segfault.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-beta.2 |
| Node             |  v14.16.0 |
| npm/Yarn         | 1.22.10 |
| Operating System | NixOS 21.05 (Okapi) x86_64 |

**Comment by DeMoorJasper** [comment]
I assume this is a sharp issue

**Comment by toastal** [comment]
I could be, or it could be something with how Parcel handle concurrent files. I'm not 100% sure and haven't looked deep enough into it.

**Comment by DeMoorJasper** [comment]
We use worker threads so probably related to that. A simple reproduction repo would be great for further investigation as I can't reproduce it on mac os

**Comment by devongovett** [comment]
I believe this was fixed recently when we upgraded sharp.
