### ISSUE TITLE
@parcel/transformer-babel: Support for the experimental syntax 'flow' isn't currently enabled

### ISSUE THREAD

**Issue by broofa** [parcel-bundler/parcel#6074]
# 🐛 bug report

I'm getting the following error after [starting to] port my codebase from plain JS to typescript.  This is for a fairly standard webapp using React+JSX.

Posting here because this refers to "flow", which is not something I've enabled or that's mentioned anywhere in my project, so I'm suspicious this may be related to the default parcel configuration(???)
```
$ parcel index.html
ℹ️ Server running at http://localhost:1234
🚨 Build failed.
@parcel/transformer-babel: Support for the experimental syntax 'flow' isn't currently enabled (7:8):
SyntaxError: Support for the experimental syntax 'flow' isn't currently enabled (7:8):
    at Object._raise (/Users/kieffer/projects/flightcard/node_modules/@babel/parser/lib/index.js:775:17)
    at Object.raiseWithData (/Users/kieffer/projects/flightcard/node_modules/@babel/parser/lib/index.js:768:17)
    at Object.expectOnePlugin (/Users/kieffer/projects/flightcard/node_modules/@babel/parser/lib/index.js:9731:18)
    at Object.isExportDefaultSpecifier (/Users/kieffer/projects/flightcard/node_modules/@babel/parser/lib/index.js:13456:16)
    at Object.maybeParseExportDefaultSpecifier (/Users/kieffer/projects/flightcard/node_modules/@babel/parser/lib/index.js:13357:14)
    at Object.parseExport (/Users/kieffer/projects/flightcard/node_modules/@babel/parser/lib/index.js:13310:29)
    at Object.parseStatementContent (/Users/kieffer/projects/flightcard/node_modules/@babel/parser/lib/index.js:12342:27)
    at Object.parseStatement (/Users/kieffer/projects/flightcard/node_modules/@babel/parser/lib/index.js:12236:17)
    at Object.parseBlockOrModuleBlockBody (/Users/kieffer/projects/flightcard/node_modules/@babel/parser/lib/index.js:12816:25)
    at Object.parseBlockBody (/Users/kieffer/projects/flightcard/node_modules/@babel/parser/lib/index.js:12807:10)
/Users/kieffer/projects/flightcard/db.ts:7:7
  6 | 
> 7 | export type tLaunch = {
>   |       ^
  8 |   id: number,
  9 |   name:  string,
```

## 🎛 Configuration (.babelrc, package.json, cli command)

Here's my `package.json` (with "babel" config):
```js
{
  "main": "index.js",
  "babel": {
    "presets": [
      "@babel/preset-react"
    ]
  },
  "dependencies": {
    "bootstrap": "4.6.0",
    "dexie": "3.1.0-alpha.8",
    "dexie-react-hooks": "1.0.6",
    "react": "^16.13.1",
    "react-bootstrap": "1.5.2",
    "react-dom": "^16.13.1",
    "react-router-dom": "5.2.0"
  },
  "devDependencies": {
    "@babel/eslint-parser": "7.13.10",
    "@babel/preset-react": "7.13.13",
    "eslint": "7.21.0",
    "eslint-config-standard": "16.0.2",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-node": "11.1.0",
    "eslint-plugin-promise": "4.3.1",
    "eslint-plugin-react": "7.22.0",
    "parcel": "2.0.0-beta.1"
  }
}

```

## 💻 Code Sample

This is part of a larger repository so, of course, providing a SSCCE will take a bit of work.  I'll work on that, but I'm hoping someone will recognize what's going on and be able to provide some insight in the meantime.

## 🌍 Your Environment

```
$ parcel --version
2.0.0-beta.1

$ node --version
v14.15.4

$ npm --version
6.14.10
```

**Comment by mischnic** [comment]
[That's simply the default error message when neither Flow nor Typescript are enabled in Babel](https://babeljs.io/repl#?browsers=Ie%2011&build=&builtIns=false&spec=false&loose=true&code_lz=KYDwDg9gTgLgBDAnmYCAyBDArgOwMYAWcAvHAN4BQAvgNxA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=true&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.13.14&externalPlugins=%40babel%2Fplugin-transform-destructuring%407.13.0)

This overrides the babel config:
```
  "babel": {
    "presets": [
      "@babel/preset-react"
    ]
```

either remove it if possible or follow this section: https://v2.parceljs.org/languages/babel/#extending-the-default-babel-config

**Comment by broofa** [comment]
Thanks for the quick response.   It looks like removing `babel.config.json` fixes the problem (yay!)

That said, if I use the `.babelrc` config suggested in that file, I get a "Support for the experimental syntax 'jsx' isn't currently enabled (9:17):" error so... just going w/out the babel config file for now since it's got me up and running.  (Thanks!)

----
For others that might stumble on this, I'd gone done a bit of a config-file rabbit-hole trying to get ESLint + Parcel + VSCode to all play nicely together.  Removing any/all babel configuration fixed the problem where parcel is concerned fixed this problem. And, for linting, I ended up with the following...

`devDependencies` in package.json:
```
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "4.20.0",
    "@typescript-eslint/parser": "4.20.0",
    "eslint": "7.21.0",
    "eslint-config-standard": "16.0.2",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-node": "11.1.0",
    "eslint-plugin-promise": "4.3.1",
    "eslint-plugin-react": "7.22.0",
    "parcel": "2.0.0-beta.1",
    "typescript": "4.2.3"
  },
```
... and  in `.eslintrc.json` the following`parser`, `plugins`, and `extends` settings:
```
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint"],
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "standard",
    "plugin:react/recommended"
  ],
```
