### ISSUE TITLE
Javascript Math class is overridden by three.js module

### ISSUE THREAD

**Issue by fedegratti** [parcel-bundler/parcel#6076]
# 🐛 bug report

It is quite difficult to explain, but it is easy to replicate. See the example below for a better understanding.

### Project 1:
CLI command:
```
yarn start
```
Package.json:
```js
{
  "name": "project-1",
  "version": "1.0.0",
  "scripts": {
    "start": "parcel ./index.html"
  },
  "dependencies": {
    "parcel": "^2.0.0-nightly.632"
  }
}

```

### Project 2:
CLI command:
```
yarn build
```
Package.json:
```js
{
  "name": "project-2",
  "version": "1.0.0",
  "module": "build/index.module.js",
  "scripts": {
    "build": "parcel build ./api.js"
  },
  "dependencies": {
    "parcel": "^2.0.0-nightly.632",
    "three": "^0.127.0"
  }
}
```

## 🤔 Expected Behavior

The `Math` class should be the javascript one.

## 😯 Current Behavior

The javascript `Math` class is being overridden by something else. It seems with the entire `three.js` module.

## 💁 Possible Solution

I don't know.

## 🔦 Context

I have 2 projects (both with Parcel). Project 1 is a regular website and Project 2 is a library that I export as a module for use in Project 1.

Project 2 has `three.js` library as a dependency. Every time I need to use `Math` class from `three.js`, I import it with an alias, so I can still have access to `Math` class from javascript. 

For example, here I'm using `clamp` method from three.js `Math` class , and `max` method from javascript `Math` class:
```javascript
import { Math as TMath } from 'three';

export default class Api {
    test() {
        let clamped_number = TMath.clamp(2, 0, 1);

        let result = Math.max(clamped_number, 3);
    }
}
```
If I run this code directly from Project 2 (like adding an index.html file and doing `yarn start`) it works fine.

But if I build it and then use it in Project 1, it throws the following error:
![image](https://user-images.githubusercontent.com/15077532/113452493-79c46600-93da-11eb-9dc9-9ea7dc75a2ef.png)

The `max` method should be called from javascript `Math` class, not three `Math` class. 
So, something weird is happening there.

## 💻 Code Sample

[Here](https://github.com/fedegratti/parcel-bug) you can find the example I described above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.632
| Node             |v15.12.0
| npm/Yarn         |Yarn 1.22.10
| Operating System |macOS 11.2.3

**Comment by ramirofages** [comment]
Wow it seems I was not the only one having this problem. I am also using threejs and parcel with the latest nightly version

**Comment by gianniballerini** [comment]
The same is happening to me! any solutions?

**Comment by fedegratti** [comment]
One thing to notice: on version `2.0.0-nightly.514` this is working.

I created the branch `working` with a working example:
https://github.com/fedegratti/parcel-bug/tree/working

I hope you can fix this on the latest version. I had to move my main project from Parcel to Rollup because of this bug.
