### ISSUE TITLE
.env variables are not loaded when using --target=node flag

### ISSUE THREAD

**Issue by wjuniorw** [parcel-bundler/parcel#6077]
# 🐛 bug report

i've created some scripts to run my nodejs project wich runs with '--target=node' flag.
But when i run build or development script, the environment variables are undefined, process.env is an object without .env variables.
In the other hand, without the flag all environments variables are found.

## 🎛 Configuration (package.json, cli command)

```js
{
  "name": "teste-parcel-node",
  "version": "1.0.0",
  "description": "",
  "main": "src/index.ts",
  "scripts": {
    "dev": "parcel src/index.ts --target=node",
    "build:front": "parcel build src/index.ts --no-source-maps",
    "build": "parcel build src/index.ts --target=node --no-source-maps",
    "start:front": "npm run build:front && node dist",
    "start:node": "npm run build && node dist"
  },
  "keywords": [],
  "author": "wjuniow",
  "license": "ISC",
  "devDependencies": {
    "parcel-bundler": "^1.12.5",
    "typescript": "^4.2.3"
  }
}
```
```npm run start:node```

## 🤔 Expected Behavior

Expect environment variables populated from .env file with '--target=node' flag

## 😯 Current Behavior

Environment variables are undefined
<img width="835" alt="Captura de Tela 2021-04-03 às 00 36 08" src="https://user-images.githubusercontent.com/4428298/113469294-d8adcd80-9422-11eb-8b68-f7f08d33859c.png">

## 💁 Possible Solution

Using external lib like dotenv

## 🔦 Context

Can't develop using local environments variable.

## 💻 Code Sample

```.env file```
```
TESTE_ENV="A_ENV_VARIABLE"
```

```src/index.ts```
```
const { TESTE_ENV } = process.env

console.log("<=====TESTE_ENV====>", TESTE_ENV)
console.log("<=====process.env====>", process.env)
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.12.5
| Node             | v14.15.4
| npm/Yarn         | 7.7.6
| Operating System | macOS 10.15.7

**Comment by mischnic** [comment]
Might also be related to https://github.com/parcel-bundler/parcel/issues/2191

**Comment by wjuniorw** [comment]
> Might also be related to #2191

No, if you can observe on src/index.ts, the second log without destructuring has the same problem.

**Comment by mischnic** [comment]
Env variables are only inlined for the browser target: https://github.com/parcel-bundler/parcel/blob/e11f0852e30fdac9ecae22398d1cf232b5eab9a2/packages/core/parcel-bundler/src/assets/JSAsset.js#L86-L89

**Comment by wjuniorw** [comment]
why not for node target?
this might be a good one.

> Env variables are only inlined for the browser target:
> 
> https://github.com/parcel-bundler/parcel/blob/e11f0852e30fdac9ecae22398d1cf232b5eab9a2/packages/core/parcel-bundler/src/assets/JSAsset.js#L86-L89

**Comment by wjuniorw** [comment]
Fix this issue by adding plugin ```parcel-plugin-electron-dotenv```  it's ok for node environment too.
