### ISSUE TITLE
Source Maps Don't Work / URL serves HTML files instead

### ISSUE THREAD

**Issue by samanime** [parcel-bundler/parcel#6078]
# 🐛 bug report

In the latest version (`2.0.0-beta.2`, installed with `npm i parcel@next`), source maps don't appear to be working at all, even with the most basic of setup. The file path to the .map file is serving up the `index.html` file instead. Looks like there probably needs to be an exception for `.map$` files to the SPA routing.

## 🎛 Configuration (.babelrc, package.json, cli command)

Default configuration.

## 🤔 Expected Behavior

The source maps are loaded properly / the index.#####.js.map file resolves properly.

## 😯 Current Behavior

The index.#####.js.map file returns the index.html content instead.

Chrome reports: 

```
DevTools failed to load SourceMap: Could not parse content for http://localhost:1234/index.fd532818.js.map: Unexpected token < in JSON at position 0
```

## 💁 Possible Solution

Configure the routing to serve the .map file properly.

## 🔦 Context

Trying to use source maps.

## 💻 Code Sample

A reproduction environment can be created with:

```bash
mkdir test
cd test
npm init -y
npm i -s parcel@next
echo '<!DOCTYPE html><body><script src="./test.js"></script>' > index.html
echo 'console.log("hello world")' > index.js
npx parcel serve index.html
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.2 / next |
| Node             | 15.7.0 |
| npm/Yarn         |7.4.3 |
| Operating System | Windows 10 Pro |

**Comment by DeMoorJasper** [comment]
This has been fixed already. Update the latest nightly

**Comment by jessabyrne** [comment]
I had this issue and upgraded to the latest nightly.  `"parcel": "^2.0.0-nightly.655",` 
Now I am getting
```
🚨 Build failed.
@parcel/core: Failed to resolve '@parcel/transformer-js/src/esmodule-helpers.js' from './node\\_modules/@parcel/transformer-js/lib/JSTransformer.js'
```
