### ISSUE TITLE
🙋 HMR should load files, not eval JS fragments

### ISSUE THREAD

**Issue by elsassph** [parcel-bundler/parcel#608]
### 😯 Current Behavior

Parceljs has a clever mechanism to load updates as fragments of JS directly evaluated:

- It is very difficult to add breakpoint in devtools (short of adding a `debugger;` instruction),
- If you want to support sourcemaps in HMR scenarios you'll basically need files.

### 💁 Possible Solution

HMR updates should be loaded as JS files.

**Comment by tomq123** [comment]
// index.html
`<html>
  <body>
    <script src="./app.js"></script>
  </body>
</html>`

// app.js
`const child = document.createElement('div')
child.innerText = 'Once'
document.querySelector('body').appendChild(child)`

HMR append child every time we save a change in app.js

**Comment by arctouch-raphaellupchinski** [comment]
Having the same issue as @tomq123, having the whole app being appended to the root div every file save.
couldn't we just force (for now) the browser to refresh every save, instead of relying on current behavior?

**Comment by elsassph** [comment]
So what's the plan for Parcel 2?

@tomq123 @arctouch-raphaellupchinski automatic HMR behaviour is surely a bit odd but that's a different issue than what I'm raising. You should raise another issue that browser should reload the page if no module calls `module.hot.accept`.
