### ISSUE TITLE
Parcel build fails on jsx syntax despite appropriate plugins presumably in place

### ISSUE THREAD

**Issue by jlipps** [parcel-bundler/parcel#6099]
# 🐛 bug report

I'm trying to run:

```
npx parcel build --target renderer './app/renderer/*.html'
```

And I get a build error related to JSX config (see below).

## 🎛 Configuration (.babelrc, package.json, cli command)

Parcel targets in package.json

```
  "targets": {
    "main": {
      "context": "electron-main",
      "distDir": "./dist"
    },
    "renderer": {
      "context": "electron-renderer",
      "publicUrl": ".",
      "distDir": "./dist",
      "includeNodeModules": [
        "@appium/gui-libs"
      ]
    }
  },
```

Babel.config.js:

```
  return (api) => {
    api.cache(true);
    return {
      plugins: [
        '@babel/plugin-syntax-jsx',
        '@babel/plugin-transform-react-jsx',
        '@babel/plugin-transform-runtime',
        'transform-class-properties',
      ],
      presets: [
        [
          '@babel/preset-env',
          {
            targets: { electron: electronVersion },
            useBuiltIns: 'usage',
            corejs: 2,
          }
        ],
        ['@babel/preset-react'],
      ],
    };
  };
```

.parcelrc:

```
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{js,jsx}": ["@parcel/transformer-babel", "@parcel/transformer-js"],
    "*.{jpg,png,svg}": ["@parcel/transformer-raw"]
  }
}
```

## 🤔 Expected Behavior

Build succeeds

## 😯 Current Behavior

Build fails with this message:

```
🚨 Build failed.
@parcel/transformer-js: This experimental syntax requires enabling one of the following parser plugin(s): 'jsx, flow, typescript' (25:8)
SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): 'jsx, flow, typescript' (25:8)
    at Parser._raise (/Users/jlipps/Code/appium/appium-desktop/node_modules/@babel/parser/lib/index.js:775:17)
    at Parser.raiseWithData (/Users/jlipps/Code/appium/appium-desktop/node_modules/@babel/parser/lib/index.js:768:17)
    at Parser.expectOnePlugin (/Users/jlipps/Code/appium/appium-desktop/node_modules/@babel/parser/lib/index.js:9731:18)
    at Parser.parseExprAtom (/Users/jlipps/Code/appium/appium-desktop/node_modules/@babel/parser/lib/index.js:11106:22)
    at Parser.parseExprSubscripts (/Users/jlipps/Code/appium/appium-desktop/node_modules/@babel/parser/lib/index.js:10689:23)
    at Parser.parseUpdate (/Users/jlipps/Code/appium/appium-desktop/node_modules/@babel/parser/lib/index.js:10669:21)
    at Parser.parseMaybeUnary (/Users/jlipps/Code/appium/appium-desktop/node_modules/@babel/parser/lib/index.js:10647:23)
    at Parser.parseExprOps (/Users/jlipps/Code/appium/appium-desktop/node_modules/@babel/parser/lib/index.js:10504:23)
    at Parser.parseMaybeConditional (/Users/jlipps/Code/appium/appium-desktop/node_modules/@babel/parser/lib/index.js:10478:23)
    at Parser.parseMaybeAssign (/Users/jlipps/Code/appium/appium-desktop/node_modules/@babel/parser/lib/index.js:10441:21)
/Users/jlipps/Code/appium/appium-desktop/node_modules/@appium/gui-libs/lib/components/ErrorBoundary/ErrorBoundary.js:25:8
  24 |       return (
> 25 |         <div className={styles.errorBoundary}>
>    |        ^
  26 |           <Alert
  27 |             message="Unhandled Exception"
```

## 🔦 Context

Upgrading from Parcel v1. Manually running `babel` on the offending file (and therefore using apparently the same babel config as Parcel) appears to transpile the file just fine.

## 💻 Code Sample

https://github.com/appium/appium-desktop/tree/split-apps

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.2
| Node             | 12.21.0
| npm/Yarn         | 7.5.6
| Operating System | macOS 10.15.7

**Comment by mischnic** [comment]
Files published to npm should not use non-standard JS extensions (typescript, jsx, ...). 

Parcel doesn't transpile node_modules, neither Parcel 1 nor Parcel 2.

**Comment by jlipps** [comment]
Oh, so what you're saying is that Parcel 2 will *bundle* certain node modules if requested, but it will never *transpile* them. Unfortunately that appears to invalidate my use case that I was describing in https://github.com/parcel-bundler/parcel/discussions/6082.

Can you think of a better way to share component code and styles between two separate Electron/Parcel projects? I.e., in both projects I want to be able to import components from a shared library. I guess I would need to figure out how to run all the preprocessing of CSS modules in addition to transpiling in the shared library itself before export? So using some combination of Babel and PostCSS or whatever in a "raw" fashion, without any bundler?

**Comment by mischnic** [comment]
> bundle certain node modules if requested, but it will never transpile them.

Correct, it will never transpile files in node_modules.

CSS imports themselves in node_modules are fine, you'd just need to transpile these language features away.
AFAICT, just adding `main: "dist/index.js"` to this package.json https://github.com/appium/appium-gui-libs/blob/main/package.json should work, since you already include the transpiled files in the published package: https://unpkg.com/browse/@appium/gui-libs@1.0.0-beta.5/

**Comment by jlipps** [comment]
Got it, that makes sense! Ran into another issue but will open a separate thread for that. Thanks.
