### ISSUE TITLE
Parcel 2 dev server is not serving source maps properly

### ISSUE THREAD

**Issue by broofa** [parcel-bundler/parcel#6100]
# 🐛 bug report

In the very simple project in the attached ZIP file (`index.html`, `index.js`, and `package.json`), when I run `parcel index.html` and open in the browser (Chrome or FF), Chrome fails to detect a sourcemap.

## 🤔 Expected Behavior

Parcel dev server should serve valid sourcemap content (as indicated by the `sourceMappingURL`).

## 😯 Current Behavior

Parcel is incorrectly serving up the home page content when the browser requests the sourcemap URL (which causes JSON.parse errors when the browser tries to parse it as a sourcemap).

## 💻 Code Sample

Unpack/install/run the attached project (3 files, < 1KB) like so:
```
$ ls -Fl parcel_sourcemap_bug.zip
-rw-r--r--  1 kieffer  staff  1218 Apr  8 18:40 parcel_sourcemap_bug.zip

$ unzip parcel_sourcemap_bug.zip
Archive:  parcel_sourcemap_bug.zip
   creating: parcel_sourcemap_bug/
  inflating: parcel_sourcemap_bug/index.html
  inflating: parcel_sourcemap_bug/index.js
  inflating: parcel_sourcemap_bug/package.json

$ cd parcel_sourcemap_bug

$ npm install
[*snip*]

$ parcel index.html
ℹ️ Server running at http://localhost:1234
✨ Built in 1.45s
```

Then open http://localhost:1234 in Chrome or Firefox and open developer tools.  Notice the following warning:
![image](https://user-images.githubusercontent.com/164050/114117371-41ad9f00-9882-11eb-9e90-0c76c8efb84f.png)

Other symptoms:
In chrome, right-click the sourcemap URL in the warning then 'Open in Tab', and you'll see parcel is serving the project home page at that URL (i.e. HTML, hence the warning about invalid sourcemap JSON).  E.g.:
![image](https://user-images.githubusercontent.com/164050/114117570-b08af800-9882-11eb-9cc9-2ac6606a33c9.png)

Parcel is building the sourcemap, though...

```
$ ls -Fl dist
total 2992
-rw-r--r--  1 kieffer  wheel  1135114 Apr  8 18:50 index.fd532818.js
-rw-r--r--  1 kieffer  wheel   386059 Apr  8 18:50 index.fd532818.js.map
-rw-r--r--  1 kieffer  wheel      146 Apr  8 18:50 index.html
```

## 🌍 Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.2 |
| Node             | 14.16.1 |
| npm/Yarn         | 6.14.12 |
| Operating System | macOS 11.1 |

**Comment by mischnic** [comment]
This is already fixed in the nightly versions

**Comment by broofa** [comment]
Cool, thanks.

@mischnic: Would it be worth pushing out a new release with the fix for this? The current "[Getting Started](https://v2.parceljs.org/getting-started/webapp/)" instructions tell folks to install `parcel@next` (currently `2.0.0-beta.2`), so pretty much all new users are going to be impacted by this.  😢

**Comment by Fr33maan** [comment]
All new user to be precise
