### ISSUE TITLE
Upgrade to cssnano 5 in optimizer

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#6102]
# 🙋 feature request

Upgrade https://github.com/parcel-bundler/parcel/blob/v2/packages/optimizers/cssnano/src/CSSNanoOptimizer.js to use https://github.com/cssnano/cssnano/releases/tag/cssnano%405.0.0

**Comment by danieltroger** [comment]
+1, maybe it finally actually can deduplicate media queries
