### ISSUE TITLE
Parcel servers HTML instead of source maps

### ISSUE THREAD

**Issue by jhannes** [parcel-bundler/parcel#6107]
# 🐛 bug report

When using parcel 2.0.0-beta.2, I get the following error (Chrome):

> DevTools failed to load SourceMap: Could not parse content for http://localhost:1234/index.02675e63.js.map: Unexpected token < in JSON at position 0

Examining the network content from the file in question (`http://localhost:1234/index.02675e63.js.map`) I see that the parcel server returns `index.html`, despite the source map file being present in the `dist` directory.

### package.json

```json
{
  "name": "parcel-sourcemaps-reproduction",
  "scripts": {
    "start": "parcel src/index.html"
  },
  "devDependencies": {
    "parcel": "*"
  },
  "dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  }
}
```

## 🤔 Expected Behavior

Source map should be available.

## 😯 Current Behavior

Source map is unavailable, making debugging my code harder.

![image](https://user-images.githubusercontent.com/18310/114282103-30ab8c00-9a42-11eb-8380-a4333656c176.png)
![image](https://user-images.githubusercontent.com/18310/114282144-7f592600-9a42-11eb-9d30-306f51bd05d5.png)

## 💁 Possible Solution

Examining the behavior, it seems like the Parcel dev server is very restrictive in what files it returns. In the same vein, favicon.ico-files are also not returned correctly. It probably would make sense for the dev-server to always return a file under `dist` if available.

## 🔦 Context

Source map is unavailable, making debugging my code harder. I am currently teaching web development at a local college, and I would like my students to enjoy parcel without losing source maps!

### Example index.html

```html
<html lang="en">
<body>
<div id="app"></div>    
</body>
<script src="/index.02675e63.js"></script>
</html>
```

### Example index.jsx

```javascript
import React from "react";
import ReactDOM from "react-dom";

ReactDOM.render(<h1>Hello World</h1>, document.getElementById("app"));
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.2-beta.2 |
| Node             | v14.15.0 |
| npm/Yarn         | npm 7.8.0 |
| Operating System | Windows 10 |

**Comment by DeMoorJasper** [comment]
This has been fixed in the latest nightly
