### ISSUE TITLE
Throw an error for `"main": "something.html"` in package.json

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#6110]
# 🐛 bug report

It happens way too often that `"main": "index.html"` is specified in package.json, and the source files are overwritten.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
    "name": "foo",
    "version": "1.0.0",
    "main": "index.html",
    "license": "MIT",
    "private": true
}
```

## 🤔 Expected Behavior

`"main" musn't specified a HTML file. Remove this property`

## 😯 Current Behavior

Builds *something*

## 💁 Possible Solution

Should be checked in here: https://github.com/parcel-bundler/parcel/blob/v2/packages/core/core/src/requests/TargetRequest.js

**Comment by devongovett** [comment]
Also if `main` points to a JS file but the entry is HTML (e.g. auto-generated package.json). Either just ignore that or error too?

**Comment by mischnic** [comment]
I would say error in that case as well. The possibilites to fix that would be to either remove the property or if you actually need it, add `targets: {main: false}`

**Comment by mischnic** [comment]
It should just always error if the type isn't JS. (e.g. `"main": "index.ts"`)
