### ISSUE TITLE
Parcel 2 somehow renames all private class properties to `undefined` when targeting newest chrome

### ISSUE THREAD

**Issue by danieltroger** [parcel-bundler/parcel#6115]
# 🐛 bug report

When building for the latest chrome version parcel renames all private class properties and methods to `undefined`.

It doesn't seem to be babel's fault: [babel REPL](https://babeljs.io/repl/#?browsers=last%201%20chrome%20version&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEC2CeEwFdgFNoG8BQ1oGIAHAJwEsA3MAFzUuOgF5oAiJVNZgbm1wJIupo26ABQBKLLzzE0VZMQB20KgAtSEAHREylGnW54AvjzwBzCkJSiJOPNNnylq9Vv67L7cQejHsv4AD2ChABIGgaIAGmIgpoAO5wiFZo4mLcQA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.13.15&externalPlugins=%40babel%2Fplugin-syntax-class-properties%407.12.13)

## 🎛 Configuration (.babelrc, package.json, cli command)

Please check attached .zip file. Doesn't matter if I remove the `.babelrc` or not.

Download, then `npm install`, then `npm run build`, then inspect stuff in `dist` folder.

## 🤔 Expected Behavior

Something like

`class mysauce{#privatevar="sauce";#privatesauce(){return this.#privatevar}givesauce(){return this.#privatesauce()}}console.log(new mysauce);`

## 😯 Current Behavior

`console.log(new class{#undefined="sauce";#undefined(){return this.#undefined}givesauce(){return this.#undefined()}});`

## 🔦 Context

I'm in search for a plugin that just transforms private class properties to public ones as esbuild produces much smaller outputs than parcel for the same target, and I think part of the reason is because of babel's HUGE polyfill for private class properties and methods. @mischnic do you know any way to just make all private props public? I don't care about private as long as the output is small.

## 💻 Code Sample

[parcel-private-class-things-weird.zip](https://github.com/parcel-bundler/parcel/files/6292676/parcel-private-class-things-weird.zip)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.635+f5962737 |
| Node             | v15.13.0 |
| npm/Yarn         | 7.7.6 |
| Operating System | macOS 10.15.7 (19H524) |

**Comment by mischnic** [comment]
This is probably because we don't use `@babel/generator` but astring: https://github.com/parcel-bundler/parcel/blob/e088bfadd9bd7da7fad033e10102118ce73247d7/packages/shared/babel-ast-utils/src/generator.js#L172-L187

**Comment by danieltroger** [comment]
This seems to now be working - probably because of https://github.com/parcel-bundler/parcel/pull/6230

@mischnic can you confirm and close?

**Comment by mischnic** [comment]
Correct
