### ISSUE TITLE
Parcel 2 not picking up babel configuration in a yarn monorepo

### ISSUE THREAD

**Issue by rauschie** [parcel-bundler/parcel#6119]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

Currently it seems that in a yarn monorepo, parcel does not pick up neither .babelrc, nor "babel" entry of package.json, whether its located at the workspace root or subrepo root.

## 🤔 Expected Behavior

The linked repo should build. Babel configuration in a subrepo root should be respected, or at the very least info should be provided where to put babel configuration in a monorepo in order for it to get respected by parcel

## 😯 Current Behavior
In a monorepo parcel complains about absence of plugin that is defined in .babelrc, regardless of .babelrc location

## 🔦 Context

I am trying to build a subrepo using parcel. Subrepo uses private class fields.

## 💻 Code Sample

the [repo](https://github.com/astegmaier/parcel2-monorepo-babel-bug) used to demonstrate the bug supposedly fixed in [#4132](https://github.com/parcel-bundler/parcel/pull/4132) still does not build neither with beta.2 nor with nightly.639 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by Fr33maan** [comment]
I actually HAD TO add a package-lock.json (even an empty one works) in the subrepo to have the subrepo babel.config.json to be used by parcel.
I'm using a monorepo structure with lerna.

You can see [in the doc](https://v2.parceljs.org/features/module-resolution/) that a package.json is not enough for parcel to consider a directory as a project directory, which is pretty confusing I think.

**Comment by rauschie** [comment]
> You can see [in the doc](https://v2.parceljs.org/features/module-resolution/) that a package.json is not enough for parcel to consider a directory as a project directory, which is pretty confusing I think.

Well That's cute. Dropping an empty package-lock.json in the subrepo did indeed solve the problem, a million thanks for the workaround!

**Comment by mischnic** [comment]
Adding package-lock.json files is not the correct solution.

Parcel just uses Babel's config resolution here, so this section applies: https://babeljs.io/docs/en/config-files#monorepos (so the "usual" approach of .babelrc's doesn't work in monorepos)

**Comment by Fr33maan** [comment]
Parcel don't use the package's babel config unless it sees a lock file.
The lock file might not be the "correct" solution, but it does the trick.
If you have a better approach, I would be really happy to ear it.

**Comment by Fr33maan** [comment]
The issue is to run the parcel command from the subrepo directory.
Babel doc tells about a ` "rootMode" option with "upward"` which can be passed as a CLI argument. How should it be done with parcel ?

**Comment by mischnic** [comment]
As described in the linked docs, you need to add a babel.config.json file in the root containing:
```
{ "babelrcRoots": ["app1", "app2"] }
```
