### ISSUE TITLE
NODE_OPTIONS handling breaks with quoted arguments

### ISSUE THREAD

**Issue by connor4312** [parcel-bundler/parcel#6123]
# 🐛 bug report

Running parcel under the VS Code debugger or under VS Code with Auto Attach enabled causes it to break with the error:

```
@parcel/workers: Cannot find module '"c:/Users/321/AppData/Local/Programs/Microsoft'
Require stack:
- internal/preload
Error: Cannot find module '"c:/Users/1/AppData/Local/Programs/Microsoft'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:742:27)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1221:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:446:5)
    at MessagePort.<anonymous> (internal/main/worker_thread.js:122:5)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:353:41)   
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26) 
```

## 🎛 Configuration (.babelrc, package.json, cli command)

N/A

## 🤔 Expected Behavior

It doesn't break!

## 😯 Current Behavior

It breaks!

## 💁 Possible Solution

It looks like the handling here is improper

https://github.com/parcel-bundler/parcel/blob/97a7bfeead8007df257d13d94c5b2f724a2ba0bd/packages/core/workers/src/Worker.js#L64-L74

This doesn't deal with quotes arguments, which then leads to a malformed environment. This can be seen easily by extracting that snippet to a test script:

![](https://memes.peet.io/img/21-04-7f179e81-b378-41c6-95e7-c91aee91856d.png)

## 🔦 Context

This was originally reported in https://github.com/microsoft/vscode-js-debug/issues/967

## 💻 Code Sample

N/A. Here's docs for auto attach if you want to try turning it on to reproduce locally: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_auto-attach

**Comment by StevenLeonCooper** [comment]
Okay so like... is there a solution here? I installed and used Parcel without issue on my laptop. Trying to get it to work on my Desktop and suddenly this: 

![image](https://user-images.githubusercontent.com/11396093/118595163-6fc6ae80-b75f-11eb-8222-0acaae09bfad.png)

**Comment by mischnic** [comment]
This is already fixed in the nightly version
