### ISSUE TITLE
Elm + parcel serve unusable: File changes not detected after compilation error

### ISSUE THREAD

**Issue by cmditch** [parcel-bundler/parcel#6124]
# 🐛 bug report

If Elm compilation fails then `parcel serve/watch` auto-recomplitaion mostly breaks.  If the entry-point Elm file (i.e. Main.elm) is edited then recompilation will work, but if any non-entry-point Elm file is edited recompilation does not occur. Since the entry point (`Main.elm`) is very rarely touched in most Elm projects it makes `parcel serve/watch` basically unusable w/ Elm.

[SSCCE here](https://github.com/cmditch/parcel2-elm-error)

## 🎛 Configuration (.babelrc, package.json, cli command)
https://github.com/cmditch/parcel2-elm-error/blob/master/package.json

## 🤔 Expected Behavior

Every time an Elm file is touched, regardless of the compilation state, `parcel serve/watch`should recompile the project.

## 💁 Possible Solution

No idea. The watcher seems to work on all Elm files, but only when the last compilation was a success.

## 💻 Code Sample
Clone and run `yarn; yarn hot` in the [SSCCE here](https://github.com/cmditch/parcel2-elm-error) and see [instructions here](elm-error/blob/master/src/elm/Init.elm#L3) to reproduce.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-nightly.639+059d502f
| Node             |  12.22.0
| npm/Yarn         |  yarn 1.22.10
| Operating System | macOS 10.15.7

Thanks,
Coury

**Comment by cmditch** [comment]
This sounds somewhat similar to what is being described here (https://github.com/parcel-bundler/parcel/issues/5660#issuecomment-813487241) and was potentially fixed here (https://github.com/parcel-bundler/parcel/pull/6072), but it doesn't look like the latter has fixed the issue. 

The primary difference is that the watcher breaks only after compilation error.

**Comment by neurodynamic** [comment]
I'm seeing this same behavior. Details:

- it appears to only happen after compilation errors
- it resolves itself if I make changes to a file that imports my Elm app (in my case, changing either my `main.ts` file or the `index.html` file that imports `main.ts` will resolve the issue, but changes to Elm files are not detected until I change one of those

**Comment by mischnic** [comment]
Does this still happen with the latest nightly?

**Comment by neurodynamic** [comment]
@mischnic Yup; just tried it with `^2.0.0-nightly.649` and same behavior as before.

**Comment by aivchen** [comment]
I am experiencing the same problem. If compilation fails due to errors in scss files then recompilation is working only in case of editing entrypoint file (index.html in my case)

**Comment by obiloud** [comment]
Just migrated to parcel 2. I am seeing the same with `^2.0.0-nightly.688`.

**Comment by arkadini** [comment]
I've noticed this problem, too, when I split my small Elm project into several source files: after any compilation error, changes to files included from the main Elm file are not detected (I'm at `2.0.0-beta.3.1`).

I've looked into the source code of the Elm transformer: the invalidations related to the source files included from the main Elm file are added to the main Asset object (by `addIncludedFile()`), but if compilation fails an exception is thrown from the `transform()` method of the transformer plugin, and the modified Asset object (with invalidations) is lost, making Parcel "lose track" of any included dependency Elm files.

Looking more through the core part of Parcel, I can't find a clean way to pass information about a failed transformation that would preserve the invalidations. That might be a reason for similar reports in some of the other transformation plugins / file formats (#5965) and why #6072 didn't solve this problem.

**Comment by pfiadDi** [comment]
Same here with every parcel 2.0 version, with Elm on Mac M1 OS 11.2.1

**Comment by myrho** [comment]
Workaround for vim: `autocmd BufWritePost *.elm :silent exec "!touch src/index.html"`

**Comment by domenkozar** [comment]
I don't get this bug with rc.

**Comment by wadouk** [comment]
@domenkozar are you sure ? on linux or osx when elm build failed, had to reload the build to recover.
yarn 1
parcel 2 RC 0
node 14

**Comment by domenkozar** [comment]
It works for me on linux, same verisons.

**Comment by domenkozar** [comment]
Ah sorry, it works for Main.elm but not other files.

**Comment by domenkozar** [comment]
@mischnic have you read https://github.com/parcel-bundler/parcel/issues/6124#issuecomment-855237095 - it might give a clue why plugin caching isn't working

**Comment by domenkozar** [comment]
There was a similar bug in v1: https://github.com/parcel-bundler/parcel/pull/2475

**Comment by n1k0** [comment]
Just to add my voice here, tested 2.0.0-nightly.843 today and the bug still exists.

**Comment by n1k0** [comment]
Similar to what @myrho [suggested for Vim users](https://github.com/parcel-bundler/parcel/issues/6124#issuecomment-870397412), here's a more generic node-based workaround using [chokidar-cli](https://www.npmjs.com/package/chokidar-cli) and [concurrently](https://www.npmjs.com/package/concurrently):

```json
{
  "scripts": {
    "start:watch": "chokidar 'src/**/!(Main).elm' -c 'touch src/Main.elm'",
    "start": "concurrently -n \"watch,parcel\" -c \"blue,green\" -k \"npm run start:watch\" \"parcel serve index.html\""
  }
}
```

**Comment by domenkozar** [comment]
I don't have time to fix this, but I'm willing to chip into whoever picks it up!

Doesn't have to be mergable, just that it works and improves my feedback loop.

It's most likely very similar to https://github.com/parcel-bundler/parcel/pull/2475 but for v2.

**Comment by voneiden** [comment]
@devongovett this issue got inadvertently closed.

**Comment by objarni** [comment]
I'm getting this with parcel 2.0.1 too; no reload when modifying `src/Main.elm`. Modifying `index.html` reloads in browser, as well as `styles.css` which is included in `index.html`. The `src/Main.elm` is indirectly included via a `app.js` script, which id directly included in `index.html`.

This happens even before any compiler error from elm.

**Comment by ChristophP** [comment]
I tried upgrading one of my Elm projects to parcel v2. I'm seeing the same issue: No recompilation after a breaking edit in any other elm file than `Main.elm`.

Everything else worked well. Would be so good to have this fixed. It's the only thing stopping Elm users from migrating to Parcel v2.

**Comment by ChristophP** [comment]
@n1k0 Thanks this chokidar and concurrently workaround works nicely for now.

**Comment by atlewee** [comment]
I have the same issue. And the suggestion over by touching the Main.elm file did break hot-reloading for me.
I found that touching index.js whenever any elm file changes will  preserve the hot reloading functionallity :)
in package.json
```  
  ...
  "scripts": {
    "start": "concurrently \"npm run touchindex\" \"parcel serve\"",
    "touchindex": "nodemon --watch src --ext 'elm' --exec  \"touch src/index.js\""
  },
  ...
```
