### ISSUE TITLE
🐛 error when i use antd Datepicker

### ISSUE THREAD

**Issue by tyaqing** [parcel-bundler/parcel#613]
```
import React from 'react';
import ReactDOM from 'react-dom';
import { Button ,DatePicker} from 'antd';
import moment from 'moment';

const { MonthPicker, RangePicker, WeekPicker } = DatePicker;


ReactDOM.render(
  <div>
<Button type="primary">Button</Button>
<DatePicker  defaultValue={moment('2015-01-01', 'YYYY-MM-DD')} />
  </div>
, document.getElementById('mountNode'));
```
console show that:
`moment.isMoment is not a function`
comment is installed,but it not working .
There's no problem using webpack.

**Comment by prilutskiy** [comment]
The issue is that date picker component uses `import * as moment from 'moment` inside. Thus, for it to work there should be something like `moment.default.isMoment` inside...

**Comment by tyaqing** [comment]
@prilutskiy   thanks,but im still confused.  But I can't modify antd

**Comment by tyaqing** [comment]
#530  successful!!
