### ISSUE TITLE
Background image / no such file or directory,

### ISSUE THREAD

**Issue by sylvainJacot** [parcel-bundler/parcel#6134]
# 🐛 bug report

 Trying to put a background image into my scss file but I've got   "no such file or directory" error 
`            background: url('../assets/images/home/jpg-png/hero-illu.png') center no-repeat;`

## 🎛 Configuration (.babelrc, package.json, cli command)

FILE STRUCTURE : 
```
src/
---assets/images/home/jpg-png/hero-illu.png
---js/main.js (with import "../style/main.scss";)
---prod/
---style/main.scss (with bg image)
```

```js
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "watch": "rm -rf ./.cache && parcel watch ./js/main.js --public-ur ./",
    "build": "parcel build js/main.js"
  },
  "watchreload": {
    "files": [
      "**/*.php",
      "**/*.scss"
    ],
    "reloadDelay": 200
  },
```
Everything is working fine except the background image path.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel  |  1.12.5
| Node | v14.15.4 
| npm  | 6.14.10

**Comment by contactjavas** [comment]
I also have issue with background image path
