### ISSUE TITLE
Inheritance issue

### ISSUE THREAD

**Issue by andrevenancio** [parcel-bundler/parcel#6137]
Giving the following example

```javascript
class Parent {
  constructor() {
    console.log('parent constructor')
    this.internalUpdate();
  }

  update() {
    console.log('parent update')
  }

  internalUpdate() {
    console.log('parent internalUpdate')
    this.update();
    requestAnimationFrame(this.internalUpdate.bind(this))
  }
}

class Child extends Parent {
  constructor() {
    super()
  }

  update() {
    console.log('child update')
  }


}

const test = new Child();
```

This is what I expect: method `update` on the Child class should be called as it's overriding the Parent update method.

This works if you just copy past it in JSFiddle or similar. But when testing in parcel, the Child `update` method is never called. What am I missing? Using parcel-bundler 1.12.5

**Comment by andrevenancio** [comment]
I can't replicate this on latest version 2.0.0-beta.2

**Comment by danieltroger** [comment]
> I can't replicate this on latest version 2.0.0-beta.2

Yeah parcel 1 is pretty much dead and abandoned

**Comment by DeMoorJasper** [comment]
As this no longer happens with Parcel 2, gonna close this. We're aiming to get a Release candidate out for Parcel 2 very soon
