### ISSUE TITLE
🐛 jsconfig.json (TS) is not supported and allowJS compiler option ignored in tsconfig.json

### ISSUE THREAD

**Issue by eddyw** [parcel-bundler/parcel#614]
**Choose one:**  🐛 bug report 

I usually use TypeScript to transpile regular JS files instead of babel. For intance, TypeScript allows to define a `jsconfig.json` file to do so. However, this behavior is not supported and apparently parcel tries to transpile with babel.

On the other side, the current behavior allows for TS files to be transpiled if `tsconfig.json` file is present. However, the `tsconfig.json` file also allows for `.js` files to be transpiled if setting the `{ allowJS: true }` compiler option but parcel still doesn't transpile `.js` files using this configuration.

### 🎛 Configuration (.babelrc, package.json, cli command)
Using `tsconfig.json`:
```js
{
  "compilerOptions": {
    "allowJs": true, // <-- Should allow .js as entry file
    "checkJs": true,
    "target": "es5",
    "module": "commonjs",
    "removeComments": false,
    "lib": [
      "es2015"
    ],
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "baseUrl": "src/"
  },
  "include": [ "src/*" ],
  "exclude": [ "node_modules" ]
}
```
Using `jsconfig.json`:
```js
{
  "compilerOptions": {
    "checkJs": true,
    "target": "es5",
    "module": "commonjs",
    "removeComments": false,
    "lib": [
      "es2015"
    ],
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "baseUrl": "src/"
  },
  "include": [ "src/*" ],
  "exclude": [ "node_modules" ]
}
```

### 🤔 Expected Behavior

It should respect compiler options in `tsconfig.json` if `{ allowJS: true }` and allow transpiling `.js` files using the TS Compiler instead of babel.

If `jsconfig.json` file is found, it should transpile `.js` files using the TypeScript Compiler instead of trying to use babel.

### 😯 Current Behavior

Parcel doesn't respect the compiler options in `tsconfig.json` for transpiling JS files. If using `jsconfig.json` the configuration is completely ignored.

### 💁 Possible Solution

Not to make it confusing to use, a possible solution may be for parcel to compile `.js` files using the TS Compiler when `jsconfig.json` is found instead of babel.

One reason why we do so is because we can gradually port parts of the application from JS to TS. However, the entry point still remains a `.js` file. For instance:
```
entry.js // imports example.ts
example.ts
```

### 🔦 Context

We don't always use babel. Most of the times, we use TS to transpile regular JS files to es5 and to be able to use TS modules from JS without having to transpile those first.

### 💻 Code Sample

`entry.js`:
```js
import fn from './tsFile'

console.log(
	'This is just a JS file',
	fn(1, 'string'),
)
```
`tsFile.ts` (Note: it's a TS file)
```ts
export default (a: number, b: string) => `${a}${b}`
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.4.1
| Node             | v9.3.0
| npm/Yarn         | NPM v5.5.1
| Operating System | MacOS

**Comment by DeMoorJasper** [comment]
Typescript only takes into account compileroptions of tsconfig.json.
After transpiling with ts it transpiles everything using babel if necessary, this appears to be kind of weird whenever babel is set to commonJS and ts to ES2016 or something similar

**Comment by eddyw** [comment]
@DeMoorJasper TS takes into account the compilerOptions in `tsconfig.json` or `jsconfig.json`. The difference between the two is mainly the `{ allowJS: true }` compiler option which doesn't need to be set if using `jsconfig.json` which tells TS to transpile regular `.js` files.

I don't want to transpile again my JS files with Babel. For instance:
With this configuration:
```json
{
	"compilerOptions": {
	  "allowJs": true,
	  "checkJs": true,
	  "target": "es5",
	  "module": "commonjs",
	  "removeComments": false,
	  "lib": [
		"es2015"
	  ],
	  "allowSyntheticDefaultImports": true,
	  "moduleResolution": "node",
	  "outDir": "out/",
	  "baseUrl": "src/"
	},
	"include": [ "src/*" ],
	"exclude": [ "node_modules" ]
  }
  ```
Running:
```bash
tsc -p tsconfig.json
```
And the following file `src/example.js`:
```js
class Example {
	constructor() {}
	method() {}
}

new Example()
```
would generate the following:
```js
var Example = /** @class */ (function () {
    function Example() {
    }
    Example.prototype.method = function () { };
    return Example;
}());
new Example();
```
..and that's all I care about. If a `.babelrc` file is not found maybe it shouldn't bother to try using babel after transpiling regular JS files or TS files.

Anyway, the point is, as for now, `parcel` doesn't respect `jsconfig.json` configuration file to transpile regular `.js` files with TS, but instead tries to use `babel`.

Some info here: https://code.visualstudio.com/docs/languages/jsconfig

**Comment by mindplay-dk** [comment]
It doesn't seem to respect `target` in `compilerOptions` of `tsconfig.json`?

I get ES5 output when following the [directions for Preact](https://parceljs.org/recipes.html#preact) and starting from a `.ts` file:

    parcel build src/app.tsx --out-dir dist --no-minify

It's reading the `tsconfig.json` for sure, because it's picking up `"jsxFactory": "h"`, but it seems to ignore the `"target": "es6"` setting.

Any way around that?

**Comment by DeMoorJasper** [comment]
@mindplay-dk make sure babelrc is also set to es5

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mindplay-dk** [comment]
@DeMoorJasper I thought this was "zero config" 😈

**Comment by eddyw** [comment]
@DeMoorJasper that goes back to my issue as well. I don't want to transpile with Babel. I mean, TS can be set to target even ES3 `{ "target": "es3" }` and after I would like to be able to opt not to transpile **again** with babel.

In my case, I start from a `.js` file which is worse because it completely ignores the `tsconfig.json` or `jsconfig.json` file.

@mindplay-dk I'm also believing that zero-config has many trade-offs. For instance, what if I want to transpile my `.js` files with closure-compiler. In my case, I want TS to do that job (not babel again), so if it can be solved, I guess it would be kind of a flag `--js babel`, `--js ts`, or `--js closure` to let parcel know which of the many JS transpilers it should use.

Anyway, so far parcel is limited to `babel` as the only way of transpiling JS files and that from my point of view is a really big trade-off of using zero-config.

**Comment by DeMoorJasper** [comment]
@eddyw I'm not sure how this can be accomplished as we use Babel for the ast generating and dependency collecting.

About the different compilers this seems like a very rare use-case as babel should work fine in almost any case and TypeScript should always have `.ts` as extension in my opinion

**Comment by eddyw** [comment]
@DeMoorJasper it's funny.. not long ago I was wondering why not using TS for AST generation and dependency collecting. While I was writing a TS loader for webpack, I found out that dependency collecting can pretty much work well using the TS Compiler.

Anyway, that leads to the root cause/problem of this issue, `parcel` doesn't give you a choice of which JS transpiler to use. I guess one of the advantages of using babel for AST and dependency collection is that the time spent building the project is reduced. However, it forces the user to a single and only tool for doing this job.
