### ISSUE TITLE
Cannot find module "@parcel/config-default"

### ISSUE THREAD

**Issue by loynoir** [parcel-bundler/parcel#6143]
# 🐛 bug report
Cannot find module "@parcel/config-default", 
due to pnpm [semi-strict](https://pnpm.io/blog/2020/10/17/node-modules-configuration-options-with-pnpm) mode.
```txt
Semi-strict means that your application will only be able to require packages that are added as dependencies to package.json
```

## 🎛 Configuration (.babelrc, package.json, cli command)

Minimal reproduce.
```txt
# cat .parcelrc
{"extends": "@parcel/config-default"}
```

## 🤔 Expected Behavior
```txt
$ pnpm i -D parcel@next
$ parcel build index.html
✨ Built in <foobar>ms
```

## 😯 Current Behavior
```txt
$ pnpm i -D parcel@next
$ parcel build index.html
> 1 | {"extends": "@parcel/config-default"}
>   |             ^^^^^^^^^^^^^^^^^^^^^^^^ Cannot find module "@parcel/config-default"
  2 | 
```

## 💁 <del>Possible Solution</del> Workaround
Furthur [reading](https://pnpm.io/blog/2020/10/17/node-modules-configuration-options-with-pnpm)

Add below at <project root>/.npmrc, or ~/.npmrc
```txt
$ cat .npmrc 
public-hoist-pattern[]=@parcel/*
```

## 🔦 Context

Unable to use parcel in strict mode.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.2
| Node             |  v14.16.0
| npm/Yarn         | N/A
| pnpm                | 6.0.2
| Operating System | archlinux

**Comment by loynoir** [comment]
Might be [related](https://github.com/parcel-bundler/parcel/issues/5603)

**Comment by mischnic** [comment]
This works correctly with Yarn PnP (which is also strict compared to "normal" node_modules).

~This dependency should ensure that config-default is available even without a custom parcelrc (and it should also resolve relative to this package):~

**Comment by mischnic** [comment]
You need to add `@parcel/config-default@next` as a dependency of your project if you list it in your .parcelrc

**Comment by loynoir** [comment]
Yeah, the rc above is just a minimal reproduce.
Do more digging, seems different PM produce DIFFERENT installation.

# Environment
Archlinux
```txt
$ npm --version
7.9.0
$ yarn --version
1.22.10
$ pnpm --version
6.0.2
```

# Prepare diff environment
```txt
$ cd `mktemp -d`
$ mkdir byNpm byYarn byPnpm byPnpmWhitelist
$ echo 'public-hoist-pattern[]=@parcel/*' > byPnpmWhitelist/.npmrc
$ env -C byNpm npm i -D parcel@next
$ env -C byYarn yarn add -D parcel@next
$ env -C byPnpm pnpm i -D parcel@next
$ env -C byPnpmWhitelist pnpm i -D parcel@next
```

# Different PM produce DIFFERENT installation
According to v2 website, `@next` seems to be more preferred.
```txt
$ ls byNpm/node_modules/@parcel|wc -l
50
$ ls byYarn/node_modules/@parcel|wc -l
49
$ ls byPnpm/node_modules/@parcel|wc -l
1
$ ls byPnpmWhitelist/node_modules/@parcel|wc -l
49
```

# Conclusion
If ONLY concentrate on '@parcel/*' pacakge
1. byNpm has `node-addon-api` while byYarn and byPnpmWhitelist has not.
2. byPnpmWhitelist is exactly same with byYarn
3. the only 1 inside  `byPnpm/node_modules/@parcel` is `@parcel/types`

**Comment by mischnic** [comment]
What do you want to say with that investigation?

> Do more digging, seems different PM produce DIFFERENT installation.

This is precisely why you need to add `@parcel/config-default@next` as a dependency (in addition to `parcel` itself).

**Comment by loynoir** [comment]
I think might be good to be documented on website.

**Comment by loynoir** [comment]
Closing as there is workaround, and solution.

**Comment by isaacadams** [comment]
> 
> 
> What do you want to say with that investigation?
> 
> > Do more digging, seems different PM produce DIFFERENT installation.
> 
> This is precisely why you need to add `@parcel/config-default@next` as a dependency (in addition to `parcel` itself).

running `@parcel/config-default@next` solved the issue I was having....

please add this to documentation!
