### ISSUE TITLE
Unexpected token error in @parcel/ts-utils

### ISSUE THREAD

**Issue by adjenks** [parcel-bundler/parcel#6149]
# 🐛 bug report

During the build process I get a Unexpected token error inside `@parcel/ts-utils/src/index.js:2`

## 🎛 Configuration (.babelrc, package.json, cli command)

.parcelrc
```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
}
```

## 😯 Current Behavior

> [[XXXX]]/node_modules/@parcel/ts-utils/src/index.js:2
> export * from './FSHost';
> ^^^^^^
> 
> SyntaxError: Unexpected token 'export'
>     at wrapSafe (internal/modules/cjs/loader.js:979:16)
>     at Module._compile (internal/modules/cjs/loader.js:1027:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at NodePackageManager.load ([[XXXX]]/node_modules/@parcel/package-manager/lib/NodePackageManager.js:208:9)
>     at NodePackageManager.requireSync ([[XXXX]]/node_modules/@parcel/package-manager/lib/NodePackageManager.js:174:17)
>     at Module.m.require ([[XXXX]]/node_modules/@parcel/package-manager/lib/NodePackageManager.js:194:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.<anonymous> ([[XXXX]]/node_modules/@parcel/transformer-typescript-tsc/lib/TSCTransformer.js:10:16)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
> 

## 🔦 Context

Just trying to build a hello world with React and typescript.

## 💻 Code Sample

`parcel build --detailed-report --target=exampleapp ./example/index.html --public-url /test/ --dist-dir='./example/`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-beta.2
| Node             | v14.16.1
| npm/Yarn         | 6.14.12
| Operating System | Linux

**Comment by adjenks** [comment]
Looks like ts-utils/package.json "main":"src/index.js" should be "lib/index.js" instead. When I change it, it moves along, but produces a new error about something else.

**Comment by mischnic** [comment]
Make sure that `@parcel/transformer-typescript-tsc` is also installed with version `2.0.0-beta.2`

**Comment by adjenks** [comment]
Installing it did not resolve the issue.

**Comment by mischnic** [comment]
Are you sure that `@parcel/ts-utils` is also the newest version?

You still have that one broken version installed if you still get
```
[[XXXX]]/node_modules/@parcel/ts-utils/src/index.js:2
export * from './FSHost';
^^^^^^

SyntaxError: Unexpected token 'export'
```

**Comment by adjenks** [comment]
My apologies @mischnic, I updated to the latest version assuming that it would be the one you requested me to install, but it was in fact not flagged as `@latest` and I did not check. After installing the specific version the build worked correctly. Perhaps 2.0.0-beta.2 should be tagged `@latest` now instead of `@next`. Thank you for your time.
