### ISSUE TITLE
import url:foo.html with transformer

### ISSUE THREAD

**Issue by xiaoliu-heng** [parcel-bundler/parcel#6156]
# 🐛 bug report

`index.js`
```js
import foo from 'url:./foo.html'
```
`foo.html`
```html
<script src="bar.js"></script>
```

can not resolve the script if import as 'url:*'

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "extends": "@parcel/config-webextension",
}
```

## 🤔 Expected Behavior

the HTML should be transform to 
```html
<script src="bar.[hash].js"></script>
```

## 😯 Current Behavior

the HTML not changed
```html
<script src="bar.js"></script>
```

## 💁 Possible Solution

add transformer
```js
"url:*.{htm,html}": []
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.2
| Node             | 12.21
| npm/Yarn         | npm
| Operating System | Windows 10

**Comment by devongovett** [comment]
Should be fixed in the latest nightly.
