### ISSUE TITLE
🐛 scope hoisting `const {x: y} = require()`

### ISSUE THREAD

**Issue by ghost** [parcel-bundler/parcel#6161]
# 🐛 bug report

### this only happens in production build (no `--no-scope-hoist`)
any pattern in third party libraries that use object destructuring assignment which renames the property like:
```js
const { factory: sha } = require('./sha')
```
will not rename the variable `sha` through the rest of the scope. note that build process will end with no error. but the bundle will have the exact name `sha` in the implementation which is undefined.

mentioned code piece is from `multihashing-async/src/crypto.js` . but this does not only apply to this specific library, it applies to the pattern mentioned.

further down the same scope there is reference to `sha` which will produce a `Uncaught ReferenceError: sha is not defined` in the browser.
```js
module.exports = {
  identity,
  sha1: sha('sha1'),
  sha2256: sha('sha2-256'),
  sha2512: sha('sha2-512'),
  dblSha2256: sha('dbl-sha2-256'),
  sha3224: hash('sha3-224'),
  sha3256: hash('sha3-256'),
  sha3384: hash('sha3-384'),
  sha3512: hash('sha3-512'),
  shake128: hash('shake-128'),
  shake256: hash('shake-256'),
  keccak224: hash('keccak-224'),
  keccak256: hash('keccak-256'),
  keccak384: hash('keccak-384'),
  keccak512: hash('keccak-512'),
  murmur3128: hash('murmur3-128'),
  murmur332: hash('murmur3-32'),
  addBlake: require('./blake')
}
```

looking at the bundle:
```js
$2bfff89baa2f43f8af6f563cfae519e9$exports = {
    identity: $2bfff89baa2f43f8af6f563cfae519e9$var$identity,
    sha1: sha("sha1"),
    sha2256: sha("sha2-256"),
    sha2512: sha("sha2-512"),
    dblSha2256: sha("dbl-sha2-256"),
    sha3224: $2bfff89baa2f43f8af6f563cfae519e9$var$hash("sha3-224"),
    sha3256: $2bfff89baa2f43f8af6f563cfae519e9$var$hash("sha3-256"),
    sha3384: $2bfff89baa2f43f8af6f563cfae519e9$var$hash("sha3-384"),
    sha3512: $2bfff89baa2f43f8af6f563cfae519e9$var$hash("sha3-512"),
    shake128: $2bfff89baa2f43f8af6f563cfae519e9$var$hash("shake-128"),
    shake256: $2bfff89baa2f43f8af6f563cfae519e9$var$hash("shake-256"),
    keccak224: $2bfff89baa2f43f8af6f563cfae519e9$var$hash("keccak-224"),
    keccak256: $2bfff89baa2f43f8af6f563cfae519e9$var$hash("keccak-256"),
    keccak384: $2bfff89baa2f43f8af6f563cfae519e9$var$hash("keccak-384"),
    keccak512: $2bfff89baa2f43f8af6f563cfae519e9$var$hash("keccak-512"),
    murmur3128: $2bfff89baa2f43f8af6f563cfae519e9$var$hash("murmur3-128"),
    murmur332: $2bfff89baa2f43f8af6f563cfae519e9$var$hash("murmur3-32"),
    addBlake: $99cc08284e7e24e8aa8db66cfabc3ce0$exports
};
```
which has `sha` undefined, in return what `sha` is representing is actually the `$95422a4ef3635abd4ce45e8b1a46a98e$exports.factory`

## theory tested
editing the source file and using `factory` instead of renaming it to `sha` won't result in the current situation.
## 🎛 Configuration (.babelrc, package.json, cli command)

zero config.

used `parcel build ./src/index.html --dist-dir ./public` command

## 🤔 Expected Behavior

the literal expression of `sha` shouldn't be in the bundle.

## 😯 Current Behavior

`sha` is there, even though it is not defined

## 💁 Possible Solution

:shrug: 

## 🔦 Context

trying to build a React application with `ipfs-core` as a dependency

## 💻 Code Sample

https://github.com/leilynn/parcel-v2-bug-report-sample

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |^2.0.0-nightly.643
| Node             |14.16.0
| npm/Yarn         |yarn 1.22.10
| Operating System |arch

**Comment by barnjamin** [comment]
I'm also seeing this issue

**Comment by devongovett** [comment]
Which version of parcel are you using? I believe we fixed some bugs related to this in beta 3.
