### ISSUE TITLE
Service workers stored to sub directory

### ISSUE THREAD

**Issue by jtojnar** [parcel-bundler/parcel#6173]
# 🐛 bug report

When I have JavaScript assets in a subdirectory, all files end up in the `dist` directory flat except, for service worker entry points. This will limit the _scope_ of the service worker preventing it accessing other assets (they are in the parent directory).

## 🎛 Configuration (.babelrc, package.json, cli command)

default configs, [`package.json`](https://github.com/jtojnar/repro/blob/eeb1d37e27b9adede3e7a86a480eefa606ddf0ab/parcel-sw-subdir/package.json):

```js
{
  "devDependencies": {
    "parcel": "^2.0.0-nightly.643"
  },
  "scripts": {
    "build": "parcel build index.html"
  }
}
```

## 🤔 Expected Behavior

The service worker would end up in the dist directory just like any other asset or entry point.

## 😯 Current Behavior

```ShellSession
$ parcel build index.html

✨ Built in 413ms

dist/index.89d79405.js                                        1.36 KB     49ms
├── node_modules/@parcel/runtime-js/lib/relative-path.js        573 B     52ms
├── node_modules/@parcel/runtime-js/lib/bundle-url.js           294 B     53ms
├── node_modules/@parcel/runtime-js/lib/bundle-manifest.js      267 B     52ms
├── node_modules/@parcel/runtime-js/lib/JSRuntime.js            103 B     16ms
├── js/index.js                                                  95 B    408ms
└── Code from unknown sourcefiles                                61 B      0ms

dist/index.html                                                 139 B     49ms
└── index.html                                                  161 B     99ms

dist/js/sw.js                                                    32 B     48ms
└── js/sw.js                                                      0 B      6ms
```

## 💁 Possible Solution

Tried using the non-deprecated URL constructor instead of the string literal but that is not even recognized as service worker: https://github.com/parcel-bundler/parcel/issues/6174

## 🔦 Context

Trying to [port selfoss to Parcel 2](https://github.com/fossar/selfoss/pull/1257) but service workers give me trouble.

## 💻 Code Sample

https://github.com/jtojnar/repro/tree/eeb1d37e27b9adede3e7a86a480eefa606ddf0ab/parcel-sw-subdir

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.643 |
| Node             |v14.16.1 |
| npm         | 6.14.12|
| Operating System | NixOS|

**Comment by mischnic** [comment]
If you run this code directly in the browser without bundling, then the serviceworker cannot serve index.html either? 

> The service worker would end up in the dist directory just like any other asset or entry point.

The reason for the current behaviour is that sw urls should be stable (not adding a hash to the filename)

**Comment by jtojnar** [comment]
> If you run this code directly in the browser without bundling, then the serviceworker cannot serve index.html either?

If I run it directly in the browser, the service worker will not be found since the service worker is in `js/` subdirectory and `serviceWorker.register` resolves the path relative to the document’s base. If I change the argument to `js/sw.js`, it will load and cache the index but browser will not be able to load the `index.html` in the offline mode since the scope of the service worker is the `js/` directory but index is in the parent directory (try https://github.com/jtojnar/repro/tree/parcel-sw-subdir/cache-index/parcel-sw-subdir)


> The reason for the current behaviour is that sw urls should be stable (not adding a hash to the filename)

The hash (or lack thereof) is not the issue. The problem is that `sw.js` ends up in `dist/js/` instead of `dist/`, even though all other assets are in `dist/`

**Comment by jtojnar** [comment]
The only solution I discovered so far is moving from

```
.
├── js/
│  ├── index.js
│  └── sw.js
└── index.html
```

to

```
.
├── js/
│  └── index.js
├── index.html
└── sw.js
```

But that means having a JS file outside of `js/` directory.

**Comment by mischnic** [comment]
> will not be able to load the index.html in the offline mode since the scope of the service worker is the js/ directory but index is in the parent directory

My point/question was: would you expect the service worker to cover `index.html` as well (after running Parcel)? Given that it isn't before bundling

> > The reason for the current behaviour is that sw urls should be stable (not adding a hash to the filename)
> 
> The hash (or lack thereof) is not the issue. The problem is that `sw.js` ends up in `dist/js/` instead of `dist/`, even though all other assets are in `dist/`

There are two modes we have: either hash and flatten the folder structure, or keep the relative paths and not hash. This case fits in neither of them.

**Comment by jtojnar** [comment]
> My point/question was: would you expect the service worker to cover `index.html` as well (after running Parcel)? Given that it isn't before bundling

Parcel places all other entry points directly to `dist/` so I would expect that for service workers as well. Otherwise, no files other than service workers can be cached, which is pointless.

> There are two modes we have: either hash and flatten the folder structure, or keep the relative paths and not hash. This case fits in neither of them.

Oh, that explains the behaviour. Though it leaves me confused how should we actually use service workers. Is it expected that we keep the service workers in the same source directory as `index.html`?

**Comment by mischnic** [comment]
We always try to to make Parcel not change the behaviour of the input code, so in that regard:

> Is it expected that we keep the service workers in the same source directory as index.html?

Without Parcel, this is the only way.

**Comment by jtojnar** [comment]
Okay, will do that. Thanks.
