### ISSUE TITLE
PluginsOptions.distDir in beta.1 and beta.2 (and possible in future stable release)

### ISSUE THREAD

**Issue by elwin013** [parcel-bundler/parcel#6175]
Hello, I'm maintainer of [parcel-reporter-static-files-copy](https://github.com/elwin013/parcel-reporter-static-files-copy). There are some differences between beta.1 and beta.2 release which I want to discuss. ;-)

# 💬 RFC

There is difference (somehow?) in `PluginOptions` interface between `2.0.0-beta.1` and ~~nightly build~~ `2.0.0-beta.2`.  In beta 1 version there is the possibility to get `--dist-dir` value from plugin options, but in beta 2 it is not possible. Also, there is no field `distDir` in the interface.

And the question - is there a chance that this data will be added to `PluginOptions` interface and be passed to plugins?

That could be good to have it, as plugins e.g. could do some "magic" after build on files in dist dir. ;-)

## 🔦 Context

Without `distDir` users who use the plugin to copy static files are forced to define it twice (if they want to change it) - first in Parcel parameter, then in the plugin configuration. 

## 💻 Examples

Minimal example available here: 
* https://github.com/elwin013/parcel-distdir-example

There are two build scripts:
* `build` - which builds to default dist dir (`dist`) - everything is OK, static file goes to `dist`,
* `build-dist` - which builds to custom dist dir (`build`) - build goes to `build`,  static file goes to `dist` because Plugin doesn't have access to `distDir` path.

## References

* https://github.com/elwin013/parcel-reporter-static-files-copy/issues/9

**Comment by mischnic** [comment]
`options.distDir` is/was really just the default value for `target.distDir` (which can also be specified per-target in `package.json#targets`). There is not always a single "global" distDir for the whole build.

So you should really be using this:
https://github.com/parcel-bundler/parcel/blob/3baf990a686d1c1dd0c5f4360296de890cc00c47/packages/core/types/index.js#L96-L97

**Comment by elwin013** [comment]
Ook, but this is `PluginsOptions` passed to plugin:

https://github.com/parcel-bundler/parcel/blob/3baf990a686d1c1dd0c5f4360296de890cc00c47/packages/core/types/index.js#L307-L322

And there is no target here. And this is what is passed to plugin: https://github.com/parcel-bundler/parcel/blob/6ce9e707443e609e1961d24a6563bc68a83a1486/packages/core/types/index.js#L1405-L1411

So, maybe we could have this target(s) in `PluginOptions` somehow?

**Comment by mischnic** [comment]
What already works would be `new Set(event.bundleGraph.getBundles().map(b => b.target))` which which gives you all of the targets

https://github.com/parcel-bundler/parcel/blob/6ce9e707443e609e1961d24a6563bc68a83a1486/packages/core/types/index.js#L1360

**Comment by elwin013** [comment]
O, that will do the job! :+1:  Thank you very much @mischnic for pointing in the right direction. :-)
