### ISSUE TITLE
Parcel - npm run start issue [cannot find the module]

### ISSUE THREAD

**Issue by ykristina** [parcel-bundler/parcel#6184]
Hey guys, I am experiencing a really weird issue with parcel version: ^2.0.0-beta.2".  As I am using Visual Studio Code, I successfully  installed parcel, using the terminal. Unfortunately, I am unable to use it. When I type npm run star in the terminal, a weird error appears. I have tried using different versions of parcel, tried to uninstall and install again , I have tried anything that comes to mind for a few days and I am still back to square one. 

The command I used :  npm run start

> forkify@1.0.0 start C:\Users\krist\Desktop\complete-javascript-course-master\18-forkify\starter
> parcel index.html

The error: The specified module could not be found.

I am really stressed out about this, as I really have no idea where the issue could be. Any advice is appreciated, thank you very much in advance! Please let me know if any additional info is needed!

**Comment by mischnic** [comment]
Is this the error you're getting? https://github.com/parcel-bundler/parcel/issues/6123

**Comment by ykristina** [comment]
> Is this the error you're getting? #6123

I am not sure where exactly the error number is specified, but this is the whole output I am getting in the terminal: 

Error: The specified module could not be found.
\\?\C:\Users\krist\Desktop\complete-javascript-course-master\18-forkify\starter\node_modules\@parcel\fs-search\fs-search.win32-x64-msvc.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (C:\Users\krist\Desktop\complete-javascript-course-master\18-forkify\starter\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\krist\Desktop\complete-javascript-course-master\18-forkify\starter\node_modules\@parcel\fs-search\index.js:15:18)
    at Module._compile (C:\Users\krist\Desktop\complete-javascript-course-master\18-forkify\starter\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! forkify@1.0.0 start: `parcel index.html`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the forkify@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\krist\AppData\Roaming\npm-cache\_logs\2021-04-24T12_40_19_081Z-debug.log
PS C:\Users\krist\Desktop\complete-javascript-course-master\18-forkify\starter>

**Comment by mischnic** [comment]
> `@parcel\fs-search\fs-search.win32-x64-msvc.node`

Try deleting  `node_modules` and reinstalling.

That file should exist: https://unpkg.com/browse/@parcel/fs-search@2.0.0-nightly.2267/

**Comment by ykristina** [comment]
> > `@parcel\fs-search\fs-search.win32-x64-msvc.node`
> 
> Try deleting `node_modules` and reinstalling.
> 
> That file should exist: https://unpkg.com/browse/@parcel/fs-search@2.0.0-nightly.2267/

I have tried this option as well, deleting node_modules and also the package-lock.json and then run npm install, unfortunately no result.

**Comment by ykristina** [comment]
I have finally found the solution and I am ecstatic. The issue was with the version of parcel I have been trying to use.  Instead of "^2.0.0-beta.2", I used "^2.0.0-beta.1" and it worked! :)

**Comment by natclark** [comment]
I'm having this exact issue. Using `@next`, `^2.0.0-beta.2`, and `^2.0.0-beta.1` didn't work for me on Windows but did on Linux. I've tried all basic troubleshooting, am using latest version of Node & NPM, reinstalled all deps, tried using npx and installing globally, but nothing has worked. I can use the v1 (`parcel-bundler`) just fine - but then there's hundreds of high-severity vulnerabilities.

EDIT: My mistake - there is a slight discrepancy between my error and OP's error. My error is as follows:

`Error: Cannot find module './fs-search.win32-ia32-msvc.node'`

I noticed that `@parcel/fs-search` doesn't contain such a file. I took a look at `@parcel/fs-search/index.rs` - it is very fragile. I would suggest adding proper error handling and support for IA-32 chipsets.

**Comment by mischnic** [comment]
See https://github.com/parcel-bundler/parcel/issues/5597

**Comment by tiborsaas** [comment]
I've ran into the same issue. I think this is a Node UX problem, their download page on windows downloads the 32-bit version by default. The 

`Error: Cannot find module './fs-search.win32-ia32-msvc.node'`

goes away if you install a 64-bit version of node and remove the `node_modules` and do a clean install.
