### ISSUE TITLE
"cannot find module 'react'" in browser console after v2 migration

### ISSUE THREAD

**Issue by Kangaroux** [parcel-bundler/parcel#6185]
# 🐛 bug report

I upgraded to `parcel@next` and followed the migration steps in the docs.

Running both `yarn build` and `yarn watch` compiles everything fine but when I try and open it in the browser, the app doesn't render and I get a message in the console saying "cannot find module 'react'"

I noticed the output size of the bundle is about 10x smaller than the one generated with parcel v1 (1MB vs. 100KB).

## 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc
```json
{
    "presets": [
        "@babel/preset-env",
        "@babel/preset-react"
    ],
    "plugins": [
        [
            "@babel/plugin-proposal-class-properties",
            {
                "loose": false
            }
        ]
    ]
}
```

.parcelrc
```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
}
```

package.json build scripts
```json
"scripts": {
    "build": "parcel build --no-source-maps client/index.html",
    "watch": "parcel watch client/index.html",
},
```

## 💻 Code Sample

Branch: https://github.com/OpenChartProject/OpenChart-web/tree/parcel-v2

Upgrade diff: https://github.com/OpenChartProject/OpenChart-web/compare/a3e4a8f...parcel-v2?expand=1

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel          | 2.0.0-beta.2
| Node            | 14.16.1
| npm/Yarn        | 1.22.10
| Operating System | Ubuntu 20.04

**Comment by Kangaroux** [comment]
Solved. The issue was caused by this I added to package.json:

```json
"engines": {
    "node": "14"
},
```

The migration guide made it sound as though I needed to add this to the package.json in any case, but really it should only be if you're targetting node (I assume). https://v2.parceljs.org/getting-started/migration/#--target

**Comment by mischnic** [comment]
> but really it should only be if you're targetting node (I assume)

Correct, that's why `--target node` is listed in the "before" block

**Comment by Kangaroux** [comment]
> > but really it should only be if you're targetting node (I assume)
> 
> Correct, that's why `--target node` is listed in the "before" block

If that change is only applicable when using `--target node` can we add a note that makes that more clear, or perhaps update the heading?

![image](https://user-images.githubusercontent.com/2302541/115962071-7f97fd80-a4e7-11eb-9a3a-caec1dcce4b2.png)
