### ISSUE TITLE
"HOT" module API is not standard

### ISSUE THREAD

**Issue by theKashey** [parcel-bundler/parcel#619]
**Choose one:** is this a  🙋 feature request? (actually, this is a bug)

module.hot.accept is too different from webpack or electron ones. Especially not the hot API, but module API. 

### 🤔 Expected Behavior

API should be consistent among different bundles.

### 😯 Current Behavior

Parcel's one is too simple.

### 💁 Possible Solution

1. Provide a module.id. Actually, this is the only change I am looking for.
2. In ideal - do not dispose the old accept handlers, and allow more that one accept callback.

### 🔦 Context

I come here from a React-Hot-Loader's issue (#500) -> version 4 is incompatible with parcel.
The problem - v4 introduces a new API, named `hot`. A customer could just call `hot(module)` and RHL will do the rest.

Meanwhile, a new logic bound to `module.id`, as long we are using it to track component instances, fabricated from the exported class to update them when the time comes.

You have that id, but as a part of module record.

**Comment by devongovett** [comment]
We could add `module.id` pretty easily. The `name` parameter inside this function is the id. Could just be passed to the Module constructor: https://github.com/parcel-bundler/parcel/blob/master/src/builtins/prelude.js#L40. Want to make a PR for that?

As for the `module.hot` API, the runtime is here: https://github.com/parcel-bundler/parcel/blob/master/src/builtins/hmr-runtime.js. We could definitely improve it to allow more than one callback.
