### ISSUE TITLE
Adding .babelrc breaks browserslist in serve

### ISSUE THREAD

**Issue by nattthebear** [parcel-bundler/parcel#6191]
# 🐛 bug report

I have a project with no `.babelrc` file that builds and runs fine, both in `parcel serve` and `parcel build`.  When I add a `.babelrc` file, `parcel build` behaves as before but `parcel serve` produces a bundle that needs regeneratorRuntime and has downlevel transpiled generator functions, even though I did not ask for it.

## 🎛 Configuration (.babelrc, package.json, cli command)

browserslist in `package.json`:
```json
  "browserslist": {
    "production": [
      "last 3 chrome version",
      "last 2 firefox version",
      "last 1 safari version",
      "firefox esr"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

`.babelrc` (only in the the broken build; the working build doesn't have this file at all):
```json
{
	"presets": [
		"@parcel/babel-preset-env",
		"@babel/preset-react"
	],
	"plugins": [
		[
			"@babel/plugin-transform-typescript",
			{ "isTSX": true }
		]
	]
}
```

Cli commands:
```json
    "start": "parcel serve ./public/index.html --dist-dir .parcel-dev --public-url / --port 3000",
    "build": "tsc && rimraf ./build && parcel build ./public/index.html --public-url . --dist-dir build --reporter @parcel/reporter-bundle-analyzer --no-scope-hoist",
```

## 🤔 Expected Behavior

Both versions should produce identical output.

## 😯 Current Behavior

In the working version:
`npm start` works
`npm run build` produces a working static build

In the broken version:
`npm start` produces a build that fails at runtime missing regeneratorRuntime
`npm run build` produces a working static build

## 🔦 Context

I want to make some changes to .babelrc, but to do that first I need to have a .babelrc, so my first step is to create a .babelrc that makes the application build and behave just like before, but I am unable to do that.

## 💻 Code Sample

This is full code to the entire project.  If you'd like to test it out, `npm install && npm start` should be sufficient; then see what is being served up at http://localhost:3000
The working version: https://github.com/nattthebear/ff12characterplanner/tree/babelrc-without
The broken version: https://github.com/nattthebear/ff12characterplanner/tree/babelrc-with

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.643
| Node             | 14.16.0
| npm/Yarn         | npm 6.14.11
| Operating System | Windows 10 Home

**Comment by arumsey** [comment]
I think I am experiencing something similar. When I include a `.babelrc` the sourcemaps generated by `parcel serve` are transpiled and not the original TS modules. 

.babelrc
```
{
  "presets": [
    ["@babel/env", {
      "bugfixes": true
    }],
    "@babel/react",
    "@babel/preset-typescript"
  ]
}
```

A similar issue also occurs when using the Typescript transformer.
```
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
```

If I delete `.babelrc` and `.parcelrc` the app still appears to be bundled correctly and the resulting sourcemaps contain the original source TS.

The following `browserlist` is included in the `package.json`.

```
  "browserslist": ["chrome >= 61, firefox >= 60, safari >= 11, edge >= 16"],
```

**Comment by arumsey** [comment]
While removing the `.babelrc` fixes the sourcemap issue with `serve` it also introduces the `regeneratorRuntime is not defined` error when attempting to load the resulting bundle from `build` into a browser. Also, the source maps generated by `build` are still the incorrect transpiled versions and not the actual source.

I have tried both beta-3.1 and the latest nightly builds. Are there any previous V2 builds where source map generation with Typescript did work? Is this a regression or has it never worked correctly?

**Comment by devongovett** [comment]
It probably worked prior to beta 3. We thought it had been fixed in https://github.com/parcel-bundler/parcel/pull/6238 but it may still be broken in certain scenarios. I believe @wbinnssmith is looking into it.

**Comment by arumsey** [comment]
Based on docs and https://github.com/parcel-bundler/parcel/issues/1762 I have updated my `.babelrc` to now be:
```
{
  "presets": [
    ["@parcel/babel-preset-env", {
      "bugfixes": true
    }],
    "@babel/react",
    "@babel/preset-typescript"
  ],
  "plugins": [
    "@parcel/babel-plugin-transform-runtime"
  ]
}
```

I've also been playing around with pre-Beta 3 nightlies to see if there is a magic combination that generates source maps correctly for `serve` and `build` while also avoiding the `regeneratorRuntime` error. Getting the source maps to generate correctly was easy. It seems like any pre-Beta 3 build works. Fixing the `regneratorRuntime` error with `build` however is proving to be more elusive.

I am currently on `2.0.0-nightly.654` but still getting the error but will reply back if I happen to find a version that does work.

**Comment by arumsey** [comment]
> I am currently on `2.0.0-nightly.654` but still getting the error but will reply back if I happen to find a version that does work.

`2.0.0-nightly.654` appears to be the last build where source maps worked. I moved up to `2.0.0-nightly.660` and source maps started showing transpiled contents again.
