### ISSUE TITLE
Could not find target with name ...

### ISSUE THREAD

**Issue by jlipps** [parcel-bundler/parcel#6199]
# 🐛 bug report

When running a build with what seems like a valid configuration, I get a cryptic error about an unexpected undefined.

## 🎛 Configuration (.babelrc, package.json, cli command)

I have 3 targets defined in my package.json:

```json
  "main": "dist/main.js",
  "renderer": "dist/index.html",
  "splash": "dist/splash.html",
  "targets": {
    "main": {
      "context": "electron-main",
      "distDir": "./dist",
      "source": "./app/main.js"
    },
    "renderer": {
      "context": "electron-renderer",
      "publicUrl": ".",
      "distDir": "./dist",
      "source": "./app/renderer/index.html",
      "includeNodeModules": [
        "@appium/gui-libs"
      ]
    },
    "splash": {
      "context": "electron-renderer",
      "publicUrl": ".",
      "distDir": "./dist",
      "source": "./app/renderer/splash.html"
    }
  },
```

## 🤔 Expected Behavior

I expect to be able to run e.g. `npx parcel build --target renderer .` and have a bundle generated. I'm attempting to keep as much information as possible in the config and as little on the CLI, so I figured specifying a target and a directory-style argument `.` would do that.

## 😯 Current Behavior

Instead, I get this, no matter what target I choose:

```
Error: Got unexpected undefined
    at nullthrows (/Users/jlipps/Code/appium/appium-desktop/node_modules/nullthrows/nullthrows.js:7:15)
    at RequestGraph.invalidateUnpredictableNodes (/Users/jlipps/Code/appium/appium-desktop/node_modules/@parcel/core/lib/RequestTracker.js:245:44)
    at loadRequestGraph (/Users/jlipps/Code/appium/appium-desktop/node_modules/@parcel/core/lib/RequestTracker.js:831:18)
    at async Function.init (/Users/jlipps/Code/appium/appium-desktop/node_modules/@parcel/core/lib/RequestTracker.js:792:17)
    at async Parcel._init (/Users/jlipps/Code/appium/appium-desktop/node_modules/@parcel/core/lib/Parcel.js:481:50)
    at async Parcel.run (/Users/jlipps/Code/appium/appium-desktop/node_modules/@parcel/core/lib/Parcel.js:518:7)
    at async run (/Users/jlipps/Code/appium/appium-desktop/node_modules/parcel/lib/cli.js:377:7) {
  framesToPop: 1
}
```

## 💻 Code Sample

[split-apps branch at the Appium Desktop repo](https://github.com/appium/appium-desktop/tree/split-apps)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.2
| Node             | 12.21.0
| npm/Yarn         | 7.5.6
| Operating System | Darwin 19.6.0

**Comment by mischnic** [comment]
Is it possible that this error comes up since you upgraded Parcel? The problem might be that the cache format changed between versions and deleting `.parcel-cache` for once might help

**Comment by jlipps** [comment]
Ah, good thought. I had been removing (via an npm script) `.cache` instead of `.parcel-cache`. Now, the error I get is:

```
@parcel/core: Could not find target with name "renderer"
```

(for all 3 targets)

**Comment by mischnic** [comment]
Then Parcel is apparently not using the package.json you posted for the targets. Are you invoking it from a subdirectory which also has a package.json?

**Comment by jlipps** [comment]
There is no package.json anywhere up the tree from this project directory.

**Comment by jlipps** [comment]
The full package.json is [here](https://github.com/appium/appium-desktop/blob/split-apps/package.json), in case you can see if there are any other entries which could be confusing Parcel?

**Comment by mischnic** [comment]
I think you are running Parcel 1 somewhere (globally?). I'm getting `error: unknown option '--out-dir'` after cloning your repo (because it was renamed to `--dist-dir` in v2)

**Comment by jlipps** [comment]
@mischnic thanks for cloning the repo! unfortunately the npm scripts are not in a runnable state as I've just been trying to get parcel itself working. Here's what I've been trying, for example:

```
~/C/a/appium-desktop ❯❯❯ npx parcel --version                                                                                                   
2.0.0-beta.2
~/C/a/appium-desktop ❯❯❯ npx parcel build --target splash .                                                                                         
🚨 Build failed.
@parcel/core: Could not find target with name "splash"
```

**Comment by mischnic** [comment]
You're right.

This seems to be an actual bug, introduced by https://github.com/parcel-bundler/parcel/pull/5861

<details>
<summary>Reproduction</summary>

```json
{
	"source": "index.js",
	"a": "dist/a.js",
	"b": "dist/b.js",
	"targets": {
		"a": {
			"source": "index.js"
		},
		"b": {
			"source": "index.js",
			"includeNodeModules": false
		}
	},
	"dependencies": {
		"nullthrows": "^1.1.1"
	},
	"engines": {
		"node": ">=12"
	}
}

```

```js
import nullthrows from "nullthrows";
console.log(nullthrows("Hello"));
```

`parcel build . --target a`
`parcel build . --target b`

</details>

BTW: I would recommend choosing a different name for the `main` target, because that name is intended for a CJS library build

**Comment by jlipps** [comment]
> I would recommend choosing a different name for the main target, because that name is intended for a CJS library build

Got it

**Comment by jlipps** [comment]
@mischnic can you think of a workaround for this scenario? or if it's an easy fix, point me in the right direction and I'm happy to try to submit a PR?

**Comment by mischnic** [comment]
A workaround is not using `"source"` inside of the targets but instead always specifying that file in the CLI invocation.

The bug is that the addition of
https://github.com/parcel-bundler/parcel/blob/a67a5f02a7a4f6fdf9e849847c1a7d86994bcd64/packages/core/core/src/requests/TargetRequest.js#L126-L128
made
https://github.com/parcel-bundler/parcel/blob/a67a5f02a7a4f6fdf9e849847c1a7d86994bcd64/packages/core/core/src/requests/TargetRequest.js#L151-L156
wrong. But I'm not quite sure how to fix this without investigating further
