### ISSUE TITLE
Option to ignore code blocks (.js) or individual links in .html <head>

### ISSUE THREAD

**Issue by mcerar333** [parcel-bundler/parcel#6203]
# 🙋 feature request

Provide an option for Parcel to ignore specified code blocks in .js and links within the .html head.
Something similar to: "// prettier-ignore", which will ignore / not format the next line of code.

## 🤔 Expected Behavior

Service workers should not be hashed and same goes for the icons specified inside of the .webmanifest file + related link tags in the .html <head>.

## 😯 Current Behavior

I've been implementing PWA features in my app and I've encountered a few roadblocks...

1.) All the icons in my .webmanifest and head <link> tags get processed & hashed by Parcel, which makes it impossible to precache / add to static cache from the service worker. "--no-content-hash" option is unreliable, so that isn't an option either.

2.) Registering a Service Worker like this -> `navigator.serviceWorker.register('./serviceWorker.js');` 
gives a warning: **_"Calling navigator.serviceWorker.register with a string literal is deprecated."_** ...and offers a solution: 
"Replace with: `navigator.serviceWorker.register(new URL('./serviceWorker.js', import.meta.url))`"

Follwing that advice results in Parcel hashing the service worker, rendering it unusable.

3.) There should be an option not to polyfill a service worker as that adds a ton of unnecessary bloat...

## 💁 Possible Solution

Make Parcel ignore the contents of .webmanifest files.
Fix a bug where service worker name gets hashed.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.644

**Comment by mischnic** [comment]
> Following that advice results in Parcel hashing the service worker, rendering it unusable.

That is a bug: https://github.com/parcel-bundler/parcel/issues/6103

> Make Parcel ignore the contents of .webmanifest files.

If you really want to, you could rename the file `manifest.json`, then Parcel should ignore it entirely.

> which makes it impossible to precache / add to static cache from the service worker

But isn't this a problem already anyway because you can't precache JS bundles which contain hashes?

**Comment by mcerar333** [comment]
What I meant is to manually cache some static assets from the service worker like this:
```
const assets = [
  '/',
  '/index.html',
  '/styles.css'
  '/script.js'
  '/manifest.webmanifest',
  '...and so on...'
];

const cacheStaticAssets = async () => {
  const cache = await caches.open(staticCacheName);
  cache.addAll(assets);
};
```
But since we don't know what will the final filename be, that can be a problem...

**Comment by mischnic** [comment]
Yes, I've run into this myself as well.

>   '/styles.css'
>   '/script.js'

But I meant that your actual page JS/CSS would have a hashed name already (even if the webmanifest + its images aren't hashed)

**Comment by mcerar333** [comment]
Yes, but I guess that shouldn't be a problem as long as '--no-content-hash' kept those names consistent...
