### ISSUE TITLE
--dist-dir not worked

### ISSUE THREAD

**Issue by Ivaneyko** [parcel-bundler/parcel#6211]
# 🐛 bug report

I try to create build in `build` folder with the command `parcel build ./src/index.html --dist-dir public`. But it anyway creates files inside the project root

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "test-parcel",
  "version": "1.0.0",
  "description": "Test parcel@next",
  "main": "index.html",
  "author": "Serhiy Ivaneyko",
  "license": "MIT",
  "devDependencies": {
    "parcel": "^2.0.0-beta.2"
  },
  "scripts": {
    "start": "parcel serve ./src/index.html",
    "build": "parcel build ./src/index.html --dist-dir public"
  },
  "browserslist": "> 0.2%"
}
```

## 🤔 Expected Behavior

Expected to see all files inside `build/` folder

**Comment by mischnic** [comment]
Remove this line:

> "main": "index.html",

We'll warn/throw an error in this case at some point: https://github.com/parcel-bundler/parcel/issues/6110

**Comment by Ivaneyko** [comment]
@mischnic thank you
