### ISSUE TITLE
fs-search is not a valid windows application

### ISSUE THREAD

**Issue by asjadjawed** [parcel-bundler/parcel#6212]
# 🐛 bug report

I am using windows 10, with the following dependencies:

```json
  "devDependencies": {
    "@parcel/transformer-sass": "2.0.0-beta.2",
    "autoprefixer": "^10.2.5",
    "eslint": "^7.22.0",
    "parcel": "^2.0.0-beta.2",
    "postcss": "^8.1.0",
    "rimraf": "^3.0.2"
  }
```
These work fine on Mac (Big Sur) or Linux (Ubuntu).
I am using yarn for package installation.

But don't work on windows 10 when I launch parcel, there is an error that says:

`fs-search is not a valid windows application`

**Comment by mischnic** [comment]
Is that really the full error message?

**Comment by asjadjawed** [comment]
This was strange I used npm install instead of yarn install and it worked succesfully.

I wasn't able to reproduce the error message.
