### ISSUE TITLE
FEATURE: Inline image in HTML

### ISSUE THREAD

**Issue by VladimirMikulic** [parcel-bundler/parcel#6224]
# 🙋 feature request

Hi! I would love to be able to have Parcel inline my images in HTML as `base64`s and not output them as files

## 🤔 Expected Behavior

Source HTML:

```html
<img src="./my-img.jpg" />
```

Output HTML:
```html
<img src="data:image/gif;base64,/9j/R0lGODlhAQABAAAAACH5BAEKAAEALA/AAAKL..." />
```

## 😯 Current Behavior

Currently, the Parcel will output images as files.

## 💁 Possible Solution

Parcel uses `@parcel/transformer-image` for transforming images which allows query parameters to be specified to each image.
So, I suspect we could add this feature to this core plugin which would insert images inline. ([sharp ref](https://github.com/lovell/sharp/issues/1337))

```html
<img src="./my-img.jpg?inline=true" />
```

## 🔦 Context

I am working on Google Apps Script project. (add-on for Google's office suite)
The problem is that Google's runtime allows only HTML and JS files. Images must be inlined.

**Comment by mischnic** [comment]
With Parcel 2, `<img src="data-url:./my-img.jpg" />` should work

**Comment by VladimirMikulic** [comment]
Wow! Thanks for the lightning-fast response @mischnic!
It does work very well!

**Comment by VladimirMikulic** [comment]
Documentation: https://v2.parceljs.org/configuration/plugin-configuration
