### ISSUE TITLE
unescaped script tags strings in injected code

### ISSUE THREAD

**Issue by hville** [parcel-bundler/parcel#6226]
# 🐛 bug report

Inline code injection into html pages can insert unescaped html tags (first mentioned in #6213) .
Javascript strings containing html code need to be escaped before html injection

## 💻 Code Sample AND Current Behavior

```javascript
//source module.js
export const tag = `<script></script>`
```

```html
//source index.html
<script type=module>import {tag} from './module.js'</script>
```

```html
//served bundled index.html
<script type=module>const tag = `<script></script>`</script>
```

## 🎛 Configuration (.babelrc, package.json, cli command)

no configuration file used

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.2
| Node             | v15.8.0

**Comment by mischnic** [comment]
The replacement happens here: https://github.com/parcel-bundler/parcel/blob/a67a5f02a7a4f6fdf9e849847c1a7d86994bcd64/packages/packagers/html/src/HTMLPackager.js#L127-L138

We "just" need to escape `</` in that string. (Though I'm not sure yet how)

**Comment by hville** [comment]
FWIW having the exact same issue with [vitejs/vite](https://github.com/vitejs/vite) *AND* [preactjs/wmr](https://github.com/preactjs/wmr) *AND* [snowpackjs/snowpack](https://github.com/snowpackjs/snowpack). Only [modernweb-dev/web](https://github.com/modernweb-dev/web) is so far immune to this...

**Comment by devongovett** [comment]
This was the best answer I found: https://stackoverflow.com/a/23983448. Basically replace `'</script'` with `'</scr\ipt'`.
