### ISSUE TITLE
Need a way to escape {{ }} characters.

### ISSUE THREAD

**Issue by miratcan** [parcel-bundler/parcel#6233]
Hello everyone!

I have a project in Parcel. I want to use the HTML5 template tag as a template and render it by using Mustache. Code below pretty explanatory:

```html
<template id="template"><img src="{{ profile_picture }}"></template>

<script>
  var template = document.getElementById('template').innerHTML;
  var rendered = Mustache.render(template, {profile_picture: '[path to image]'});
  document.body.innerHTML = rendered;
</script
```

But when I try to run this parcel thinks that {{ profile_picture }} is an asset that needs to be filled by the parcel itself. I'm getting this error:

```bash
$ parcel index2.html
Server running at http://localhost:1234
{{ profile_picture }}: ENOENT: no such file or directory, open '/project/{{ profile_picture }}'
```
I think a need a way to say that "You don't have to accept that {{ profile_picture }} as an asset."

Maybe a kind of escape character can be a solution. ( \{\{ profile_picture \}\} )

**Comment by mischnic** [comment]
Not at the moment.
See:
- https://github.com/parcel-bundler/parcel/issues/1186
- https://github.com/parcel-bundler/parcel/issues/1087
- https://github.com/parcel-bundler/parcel/issues/357

**Comment by VladimirMikulic** [comment]
@miratcan hopefully I am not too late here.
Check out https://www.npmjs.com/package/parcel-resolver-ignore

1. `npm i parcel-resolver-ignore -D`
2. `.parcelrc`
```json
{
  "extends": "@parcel/config-default",
  "resolvers": ["parcel-resolver-ignore", "..."]
}
```
3. `package.json`
```json
{
  "parcelIgnore": [
    "{{*.*}}"
  ]
}
```
