### ISSUE TITLE
Can not find module 'babel-runtime/core-js/symbol/to-string-tag' when importing vue

### ISSUE THREAD

**Issue by luikore** [parcel-bundler/parcel#624]
🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc :

```js
{
    "plugins": [
        "transform-runtime"
    ]
}
```

### 🤔 Expected Behavior

No throwing errors.

### 😯 Current Behavior

Opening localhost:1234 gives:

```
Uncaught Error: Cannot find module 'babel-runtime/core-js/symbol/to-string-tag'
    at newRequire (parcel-demo-for-issues.js:33)
    at localRequire (parcel-demo-for-issues.js:48)
    at Object.require.6 (parcel-demo-for-issues.js:1429)
    at newRequire (parcel-demo-for-issues.js:42)
    at localRequire (parcel-demo-for-issues.js:48)
    at Object.require.4.babel-runtime/core-js/promise (parcel-demo-for-issues.js:8693)
    at newRequire (parcel-demo-for-issues.js:42)
    at require.8 (parcel-demo-for-issues.js:67)
    at parcel-demo-for-issues.js:72
newRequire @ parcel-demo-for-issues.js:33
localRequire @ parcel-demo-for-issues.js:48
require.6 @ parcel-demo-for-issues.js:1429
newRequire @ parcel-demo-for-issues.js:42
localRequire @ parcel-demo-for-issues.js:48
require.4.babel-runtime/core-js/promise @ parcel-demo-for-issues.js:8693
newRequire @ parcel-demo-for-issues.js:42
require.8 @ parcel-demo-for-issues.js:67
(anonymous) @ parcel-demo-for-issues.js:72
```

### 🔦 Context

`import "vue"` gives the error, maybe related to #408

### 💻 Code Sample

You can clone this setup

https://github.com/luikore/parcel-demo-for-issues

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.4.1
| Node             | 9.3.0
| npm/Yarn         | 5.6.0/1.3.2
| Operating System | macOS High Sierra 10.13.2

**Comment by nooldey** [comment]
maybe you can use babel through `"babel-preset-env": "^1.6.1",` ， I also use parcel to bundler Vuejs web page , the config like this: 

**package.json**

`"devDependencies": {
    "autoprefixer": "^7.2.5",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "css-loader": "^0.28.9",
    "node-sass": "^4.7.2",
    "parcel-bundler": "^1.4.1",
    "parcel-plugin-vue": "^1.5.0",
    "postcss-modules": "^1.1.0",
    "vue-loader": "^13.7.0",
    "vue-style-loader": "^3.0.3",
    "vue-template-compiler": "^2.5.13"
  },
  "dependencies": {
    "vue": "^2.5.13",
    "vue-router": "^3.0.1"
  }`

**babelrc**
`{
    "presets": [
        [
            "env"
        ]
    ]
}`

**main.js**
`import Vue from 'vue'
import App from './App.vue'
import './style/index.scss'

new Vue({
    el: '#app',
    render: h => h(App)
})`

Now it runs normal and fast!
Hope this help.

**Comment by luikore** [comment]
@nooldey Thanks, removing transform-runtime and adding babel-preset-env works.
