### ISSUE TITLE
Parcel displays funding messages on install even when running npm install with --no-fund

### ISSUE THREAD

**Issue by unikitty37** [parcel-bundler/parcel#6249]
# 🐛 bug report

When installing with `npm install --no-fund`, the flag is ignored and a funding request is shown anyway.

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json:

```js
{
  "name": "foo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "author": "foo",
  "license": "MIT",
  "dependencies": {},
  "devDependencies": {
    "parcel-bundler": "1.12.5",
  }
}
```

## 🤔 Expected Behaviour

The user's explicitly communicated preferences not to see funding messages should be respected.

## 😯 Current Behaviour

The user's preferences are ignored:

```
> node -e "try{require('./postinstall')}catch(e){}"


> parcel-bundler@1.12.5 postinstall /tmp/project/node_modules/parcel-bundler
> node -e "console.log('\u001b[35m\u001b[1mLove Parcel? You can now donate to our open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/parcel/donate\u001b[0m')"

Love Parcel? You can now donate to our open collective:
 > https://opencollective.com/parcel/donate
```

## 💁 Possible Solution

Use the standard npm funding mechanism documented at https://docs.npmjs.com/cli/v6/configuring-npm/package-json#funding

## 🔦 Context

When packages show funding information, it tends to display at the end of `npm install`'s output, meaning useful information is likely to be scrolled off the screen. If funding information is output during CI builds, it increases the log storage requirement. You might say "it's only a few lines, just scroll past it", but this is like a spammer saying "it's only an email, just delete it" — once everybody starts doing it, the load is significant.

In addition to this, when I tell npm not to show funding information and Parcel ignores that, it makes me feel like the developers are saying "you don't control your own machine — **we** do", and leaves me wondering if even more intrusive advertising will be the result if this doesn't bring in enough money.

I'm working through a tutorial which uses Parcel, which I haven't used before. TBH, this doesn't really make me want to use it in the future.

While using the standard npm funding mechanism means some users will not see the message, it is unlikely to affect the amount of money brought in: somebody who has gone to the bother of finding out how to disable funding messages, and then altered their config in order to disable them, is likely to be angry at finding their wishes ignored. Angry people don't tend to want to give you money :)

## 💻 Code Sample

The `package.json` above should be all that's needed.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v1.12.5
| Node             | v14.16.1
| npm/Yarn         | 6.14.12
| Operating System | macOS 10.14.6 (18G9028)

**Comment by DeMoorJasper** [comment]
NPM's funding fields didn't exist when we added this. It probably came into existence because so many packages were pushing this using the post install message like we did.

There are environment variables for it which we do respect maybe? I'll open a PR to update it as it's not really helping anyway as far as I know.

I do want to note that this won't update in Parcel 1.

**Comment by DeMoorJasper** [comment]
Just realised we've already changed this for Parcel 2
