### ISSUE TITLE
[v2] `parcel serve`: @parcel/core: Failed to resolve '@parcel/transformer-js/src/esmodule-helpers.js'

### ISSUE THREAD

**Issue by danieltroger** [parcel-bundler/parcel#6254]
# 🐛 bug report

`parcel serve` is broken in the newest nightly, possibly related to the new SWC scope hoisting?

## 🎛 Configuration (.babelrc, package.json, cli command)

Please see the code sample below.

## 🤔 Expected Behavior

`parcel serve` should work

## 😯 Current Behavior

`parcel serve` fails with this error message:
```
daniel@Daniels-MacBook-Pro parcel-doesnt-declare-its-variables % npm run serve

> serve
> parcel serve --port 1234 src/main.ts

ℹ️ Server running at http://localhost:1234
🚨 Build failed.
@parcel/core: Failed to resolve '@parcel/transformer-js/src/esmodule-helpers.js' from './node\\_modules/@parcel/transformer-js/lib/JSTransformer.js'
```

## 💁 Possible Solution

No longer fail

## 🔦 Context

Coworker updated parcel and it didn't work

## 💻 Code Sample

Please try [this file](https://github.com/parcel-bundler/parcel/files/6359476/parcel-doesnt-declare-its-variables.zip) from https://github.com/parcel-bundler/parcel/issues/6167 - run `npm install` and then `npm run serve`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.655+ba57b650|
| Node             | v16.0.0 |
| npm/Yarn         |npm v7.11.2|
| Operating System | macOS 10.15.7 (19H1030) |

**Comment by danieltroger** [comment]
@mischnic is it possible that you need to increase the version number of transformer-js somewhere? There was no new nightly build this night and `parcel serve` still doesn't work: https://www.npmjs.com/package/parcel?activeTab=versions

**Comment by mischnic** [comment]
There was no nightly because somehow yarn install failed when the nightly was built: https://github.com/parcel-bundler/parcel/runs/2561261073?check_suite_focus=true

Should be published now: https://unpkg.com/browse/@parcel/transformer-js@2.0.0-nightly.662/

**Comment by danieltroger** [comment]
Epic.

@mischnic I edited the package.json myself and tried out the new version. I was shocked when the output became 10KB larger. Turns out my bundle-texted styling is included twice. I checked the output and it looks to me like https://github.com/parcel-bundler/parcel/issues/5765 regressed - the exact pure comment you added there is gone again. Should I open another issue or can you take a look?

Also I noticed that `something?.something?.maybefunction?.();` gets converted to `something?.something?.maybefunction();` and that is wrong and can throw errors, please compare those in a javascript console:

```
({notafunction: null})?.notafunction?.();
```
Returns: `undefined`

vs
```
({notafunction: null})?.notafunction();
```

returns: `Uncaught TypeError: ({notafunction:null}).notafunction is not a function`

Can you reproduce/fix this or should I investigate more and open an issue?

Also it seems like my targets are no longer correctly targeted, as optional chaining is supported by all these browsers `firefox 77, safari 13.1, ios 13.4` yet it got transpiled.

**Comment by mischnic** [comment]
> exact pure comment 
> Should I open another issue

~Please do that~ https://github.com/parcel-bundler/parcel/issues/6270

> also I noticed that `something?.something?.maybefunction?.();` gets converted to `something?.something?.maybefunction();`

Please open a new issue. That is working correctly for me.

> Also it seems like my targets are no longer correctly targeted, as optional chaining is supported by all these browsers firefox 77, safari 13.1, ios 13.4 yet it got transpiled.

Please open a new issue as well.

**Comment by danieltroger** [comment]
> #6270

Thanks!

> Please open a new issue. That is working correctly for me.

Downloading this: https://github.com/parcel-bundler/parcel/files/6359476/parcel-doesnt-declare-its-variables.zip, running `yarn install`, replacing the contents in main.ts  with `({notafunction: null})?.notafunction?.();` and running `yarn build` yielded the funkiest possible error message:

```
daniel@Daniels-MacBook-Pro src % yarn run build
yarn run v1.22.10
warning package.json: No license field
$ parcel build src/main.ts --log-level verbose --detailed-report 100 --target modern
🚨 Build failed.
@parcel/optimizer-terser: Unexpected token: punc (?.)
  1 | (function () {
> 2 | ?.();
>   | ^ Unexpected token: punc (?.)
  3 | 
  4 | })();
It's likely that Terser doesn't support this syntax yet.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
daniel@Daniels-MacBook-Pro src % cat main.ts 
({notafunction: null})?.notafunction?.()
daniel@Daniels-MacBook-Pro src % 
```

But in other contexts I cant reproduce. It is the craziest error ever. I see it happening when comparing the output of my code with old parcel and new parcel and have pinned it down to a library that I wrote where it always happens, but if I take the code which does it out of the library it no longer happens.

It removes the ?. before the function call to Node.cloneNode on a MutationRecord.target, so maybe it's an intentional optimization???

**Comment by danieltroger** [comment]
NO WAY, there is no `?.` in my code! The previous scope hoister or terser added it automatically to prevent me from encountering a bug! Can we have that behavior back? If not no worries, then it's resolved.

New question: do you need a more detailed bug report about the `Unexpected token: punc (?.)` mentioned above?

**Comment by mischnic** [comment]
> `({notafunction: null})?.notafunction?.();`
> `?.();`

I've already reported that in https://github.com/swc-project/swc/issues/1688.
