### ISSUE TITLE
Image optimization

### ISSUE THREAD

**Issue by windware** [parcel-bundler/parcel#627]
🙋 **Feature request**

Is it possible to add image optimizers?
I assume [webpack's image loader](https://github.com/tcoopman/image-webpack-loader) (or [another](https://www.npmjs.com/package/imagemin-webpack-plugin)) does it.

### 🤔 Expected Behavior

When importing images, they will be piped through image optimizers.

### 😯 Current Behavior

Not optimized.

### 🔦 Context

Possible option can be,

--optimize-image [quality] (If quality is not specified, does it losslessly)

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.4.1
| Node             | 8.9.4
| npm         | 5.6.0
| Operating System | Ubuntu 16.04.3

**Comment by DeMoorJasper** [comment]
Should this be a plugin or a core feature? I've not seen that many people request it so far. I'm intrested in writing it though

**Comment by windware** [comment]
If it goes in the core, maybe it shouldn't be enabled by default as it takes a while to optimize a large amount of images, giving wrong impressions for first time users but it could be handy if it's built in and users opt-in for it.

**Comment by brandon93s** [comment]
I think this fits best as a plugin. Seems very useful, but not everyone will want their images altered by their bundler.

**Comment by DeMoorJasper** [comment]
Initial version of the plugin is ready here: https://github.com/DeMoorJasper/parcel-plugin-imagemin

**Comment by windware** [comment]
I just ran the example and it showed an error at the jpeg file,

🚨  Error in file: parcel-plugin-imagemin/example/pexels-image.jpeg

write EPIPE
write EPIPE
    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)

Also, I ran it on my own files and it stopped with this, (I placed the imagemin.config.js at the project root where package.json is and also placed it at the directory where the entry point file is.)

🚨  asset.getConfig is not a functio
    at ImagePackager.addAsset (node_modules/parcel-plugin-imagemin/lib/ImagePackager.js:22:30)
    at Bundle._addDeps (node_modules/parcel-bundler/src/Bundle.js:106:20)
    at Bundle._package (node_modules/parcel-bundler/src/Bundle.js:89:18)
    at <anonymous>

**Comment by DeMoorJasper** [comment]
@windware i'll close down this issue, feel free to open any bug issues on https://github.com/DeMoorJasper/parcel-plugin-imagemin
