### ISSUE TITLE
Double whammy issue: new parcel can't hit targets and gets confused by calling a function #get

### ISSUE THREAD

**Issue by danieltroger** [parcel-bundler/parcel#6282]
# 🐛 bug report

I was able to create simple input code which makes double wrong output!

1. SWC thinks newest firefox supports private class fields which it does not
2. Parcel produces invalid output both when running `parcel serve` and `parcel build` if a class contains a private method called `#get`.

## 🎛 Configuration (.babelrc, package.json, cli command)

Please see attached .zip file

## Sample code

```
class myclass {
  #get(){
    console.log("Hi from a method with a private identifier called #get");
  }
  constructor(){
    this.#get();
  }
}

const instance = new myclass();
```

## 🤔 Expected Behavior

The same (or identically behaving) output as good old `2.0.0-nightly.650+dc79abcd` gives me:
```
! function() {
  var t = 0;

  function e(e) {
    return "__private_" + t++ + "_" + e
  }
  var r = e("get");

  function n() {
    console.log("Hi from a method with a private identifier called #get")
  }
  new class {
    constructor() {
      Object.defineProperty(this, r, {
        value: n
      }), ((t, e) => {
        if (!Object.prototype.hasOwnProperty.call(t, e)) throw new TypeError("attempted to use private field on non-instance");
        return t
      })(this, r)[r]()
    }
  }
}();
```

-> logs `Hi from a method with a private identifier called #get` to the console when ran

## 😯 Current Behavior

```
new class {
  #get() {
    console.log("Hi from a method with a private identifier called #get")
  }
  constructor() {
    (function(t, e) {
      if (!e.has(t)) throw new TypeError("attempted to get private field on non-instance");
      return e.get(t).value
    })(this, _get).call(this)
  }
};
```

In firefox (which was my build target) -> ` Uncaught SyntaxError: private fields are not currently supported`
In chrome: `VM450:9 Uncaught ReferenceError: _get is not defined`

## 💁 Possible Solution

Make it work correctly like it did before.

## 🔦 Context

I was, after already reporting multiple issues with the new SWC thing just by trying to use it and read the code, finally daring to run just a portion of the output code and it failed lol.

## 💻 Code Sample

[parcel-hashtag-get.zip](https://github.com/parcel-bundler/parcel/files/6475197/parcel-hashtag-get.zip)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.660+177f8eec|
| Node             |v16.1.0|
| npm/Yarn         |yarn 1.22.10|
| Operating System |macOS 10.15.7 (19H1030)|

**Comment by mischnic** [comment]
See https://github.com/swc-project/swc/issues/1694.

I think that swc does realize that Firefox 88 doesn't support them (because `this.#get();` is indeed transpiled), and the declaration `#get() { ... }` is just not transpiled for some reason.

**Comment by danieltroger** [comment]
@mischnic it seems to work now I think

**Comment by danieltroger** [comment]
WTF, now it doesn't work?? I swear it worked yesterday lol. I tried it on my actual code now and it still contained a bunch of hashtags
