### ISSUE TITLE
Build fails when css or scss is included, passes otherwise

### ISSUE THREAD

**Issue by bluepill** [parcel-bundler/parcel#6287]
# 🐛 bug report

Consider a simple project:

- index.html
- index.js
- style.css

Running parcel cli to build this using `parcel build index.html` fails if index.html links to style.css. If the style.css (or scss) is not used (commented out), the parcel-cli builds index.html just fine. See gif recording attached.

## 🎛 Configuration (cli command)

```js
parcel build index.html
```

## 🤔 Expected Behavior

Parcel build should build css and scss assets successfully

## 😯 Current Behavior

Parcel fails to build index.html if it links to css / scss files. The error message and trace is below:
```
×  F:\mycode\parcel-test\style.css:undefined:undefined: plugin is not a function
    at LazyResult.run (D:\development\npm\node_modules\parcel-bundler\node_modules\postcss\lib\lazy-result.js:288:14)      
    at LazyResult.asyncTick (D:\development\npm\node_modules\parcel-bundler\node_modules\postcss\lib\lazy-result.js:212:26)
    at D:\development\npm\node_modules\parcel-bundler\node_modules\postcss\lib\lazy-result.js:254:14
    at new Promise (<anonymous>)
    at LazyResult.async (D:\development\npm\node_modules\parcel-bundler\node_modules\postcss\lib\lazy-result.js:250:23)    
    at LazyResult.then (D:\development\npm\node_modules\parcel-bundler\node_modules\postcss\lib\lazy-result.js:131:17)
```

## 🔦 Context

Unable to build projects with css / scss

## 💻 Code Sample

Trivial. Create a simple html file with a style.css

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.5
| Node             | 14.17.0
| npm/Yarn         | 6.14.13
| Operating System | Windows 10 x64 20H2

![build_fail](https://user-images.githubusercontent.com/12779795/118366084-ec6d5780-b5bc-11eb-83e6-f4147220fb8b.gif)

**Comment by TheRealPayPaul** [comment]
I had the same problem as you. It seems that cssnano does some weird stuff and postcss can't handle it.
Uninstalling cssnano and installing an older version (cssnano@4.1.11) fixed the problem for me.

**Comment by devongovett** [comment]
Closing because this seems like a postcss/cssnano issue.

**Comment by stevenpicard** [comment]
I'm curious if @bluepill actually had "cssnano" installed. I have the same problem and I do not have postcss/cssnano installed. I think this should be reopened.

**Comment by getflourish** [comment]
As @TheRealPayPaul said, removing `cssnano` and installing `cssnano@4.1.11` worked.

I’ve used this code:

```
yarn remove cssnano
yarn add cssnano@4.1.11
```

**Comment by Tails** [comment]
The downgrade also worked for me, had the same error message.

```npm i -S cssnano@4.1.11```

**Comment by Group-5-Zen-Garden** [comment]
@Tails This worked for me. Thanks!
