### ISSUE TITLE
🙋  Allow configuration through package.json file

### ISSUE THREAD

**Issue by ghost** [parcel-bundler/parcel#629]
🙋 feature request

It would be nice to allow configuration and configuration extension from within your projects package.json rather than have several dot files littered around your root.

e.g. ESLint allows configuration and/or configuration extension from within your package.json, see point no.2 of Configuring ESLint section.

### 🤔 Expected Behavior

Allow configuration directly from within your package.json file, and allow the configuration to point to another file which extends the configuration.

```
e.g. {
    "eslintConfig": {
        "extends": "./path/to/file/.eslintrc.js"
    },
}
```

### 😯 Current Behavior

Several dot files are placed in projects root directory if configuration is required.

**Comment by brandon93s** [comment]
It's worth looking into https://github.com/davidtheclark/cosmiconfig. It supports this functionality, and it may be able to replace some of parcel's custom config resolving / loading code.

**Comment by hfunez007** [comment]
i have this and i am using parcel 2 but after run on app.js have a lot of changes. 

"watch:js": "parcel watch ./public/js/index.js --dist-dir ./public/js/bundle.js",
    "build:js": "parcel build ./public/js/index.js --dist-dir ./public/js/bundle.js"
