### ISSUE TITLE
parcel 2 with swc transpiles optional chaining even though it shouldn't

### ISSUE THREAD

**Issue by danieltroger** [parcel-bundler/parcel#6290]
# 🐛 bug report

Since parcel switched to SWC optional chaining is being transpiled for the target `firefox 77, safari 13.1, ios 13.4` even though all browsers in that target support optional chaining.

Note that originally my target was all browsers that support [String.prototype.replaceAll](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll) but I had to water it down to `firefox 77, safari 13.1, ios 13.4` because babel also kept transpiling it.

`firefox 77, safari 13.1, ios 13.4` **definitely** support optional chaining. You can try it for yourself, **see proof below** or read [here](https://caniuse.com/mdn-javascript_operators_optional_chaining) or [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining). And I am convinced that all browsers that support .replaceAll also do but you'll have to check that for yourself.

<img width="631" alt="Screenshot 2021-05-16 at 11 01 36" src="https://user-images.githubusercontent.com/4047180/118391722-1878ef00-b636-11eb-9619-842b4c9d33d9.png">
(Sorry for not having 13.1 but I can assure you it works there too because mdn and caniuse say so and 13.1.2 isn't far from 13.1)

<img width="744" alt="Screenshot 2021-05-16 at 11 04 40" src="https://user-images.githubusercontent.com/4047180/118391821-89b8a200-b636-11eb-8174-93efe263b339.png">

<img width="1893" alt="Screenshot 2021-05-16 at 11 05 35" src="https://user-images.githubusercontent.com/4047180/118391853-a9e86100-b636-11eb-960c-19016dc022d3.png">

## 🎛 Configuration (.babelrc, package.json, cli command)

Please see attached .zip file

## 🤔 Expected Behavior

`document?.querySelector?.(".lol")?.remove?.();`

## 😯 Current Behavior

`!function(){var l,o,n;null===document||void 0===document||null===(l=document.querySelector)||void 0===l||null===(o=l.call(document,".lol"))||void 0===o||null===(n=o.remove)||void 0===n||n.call(o)}();`

## 💁 Possible Solution

Don't transpile optional chaining for browsers that support it.

## 🔦 Context

I'm just trying to be able to upgrade parcel and not get bigger output than before the swc switch 🙂

## 💻 Code Sample

[parcel-accidentally-transpiles-optional-chaining.zip](https://github.com/parcel-bundler/parcel/files/6488942/parcel-accidentally-transpiles-optional-chaining.zip)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.669+afaab71a|
| Node             |v16.1.0|
| npm/Yarn         |yarn v1.22.10|
| Operating System |10.15.7 (19H1030)|

**Comment by danieltroger** [comment]
Also related: my first attempt at reporting this, https://github.com/parcel-bundler/parcel/issues/6273

**Comment by mischnic** [comment]
-> https://github.com/swc-project/swc/issues/1704
