### ISSUE TITLE
Import javascript file as string

### ISSUE THREAD

**Issue by mfbx9da4** [parcel-bundler/parcel#6295]
# 🙋 feature request

I have a very particular use case. I want to import a javascript file as a string and inject it into html responses at will in a service worker. I can't see how to do this using parceljs beyond hosting the javascript file somewhere and doing fetch at runtime to load the js file into memory. However, I want to do this at build time. How best to do this?

Note: Ideally the dependencies of javascript file I am importing should be bundled into the string.

**Comment by mischnic** [comment]
With Parcel 2, you can do

```js
import js from "bundle-text:./foo.js";
```

https://v2.parceljs.org/configuration/plugin-configuration/#predefined-(offical)-named-pipelines


But this might not work correctly for JS bundles

**Comment by mfbx9da4** [comment]
Thanks for the suggestion. I'm on `1.12.5`, I have managed to use 

```js
const js = readFileSync(__dirname + '/main.js', 'utf-8')
```

for the non-bundled version. Any chance you could verify if bundling works with the `bundle-text` version, can't imagine it would.

**Comment by mischnic** [comment]
This works correctly (and also transpiles that typescript file into JS), but I image it might break once `b.ts` has dynamic imports or imports something from a shared bundle.

```js
import js from "bundle-text:./b.ts";

console.log(js);
```

**Comment by mfbx9da4** [comment]
Nice will give it a shot. That's only for parcel 2 though right? Thank you!

**Comment by mischnic** [comment]
Correct
