### ISSUE TITLE
Parcel 2: another SWC regression: getters with non-boring names yield: `@parcel/transformer-js: Expected ,, got string literal (🍊)`

### ISSUE THREAD

**Issue by danieltroger** [parcel-bundler/parcel#6296]
# 🐛 bug report

Getters that are named with string-names make parcel fail building.

Take i.e. this input code:
```
const juice = {
  get "🍊"() {
    return "😋";
  },
};
console.log(juice['🍊']);
```

## 🎛 Configuration (.babelrc, package.json, cli command)

Please see attached .zip file

## 🤔 Expected Behavior

```
console.log({get"🍊"(){return"😋"}}["🍊"]);
```

(returns `😋` when ran)

## 😯 Current Behavior

```
daniel@Daniels-MacBook-Pro parcel-cant-get % npm run build

> build
> parcel build src/main.ts --log-level verbose --detailed-report 100 --target modern

🚨 Build failed.
@parcel/transformer-js: Expected ,, got string literal (🍊)
/private/tmp/parcel-cant-get/src/main.ts:2:7
  1 | const juice = {
> 2 |   get "🍊"() {
>   |       ^^^^
  3 |     return "😋";
  4 |   },
daniel@Daniels-MacBook-Pro parcel-cant-get % 
```

## 💁 Possible Solution

Revert to the behavior of 650 where it worked.

## 🔦 Context

I have an object that looks like this:
```
const localisations = {
  // stuff is here
  get "de-CH"(){
    return localisation['de-DE'];
  }
};
```

And since the swc update it no longer works. Version 650 still does it fine.

## 💻 Code Sample

[parcel-cant-get.zip](https://github.com/parcel-bundler/parcel/files/6492694/parcel-cant-get.zip)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.671+06bdb1fb|
| Node             |v16.1.0|
| npm/Yarn         |npm v7.11.2|
| Operating System |10.15.7 (19H1030)|

**Comment by mischnic** [comment]
-> https://github.com/swc-project/swc/issues/1708

**Comment by danieltroger** [comment]
@mischnic Could you maybe take another look at this? The repro zip now no longer fails, but the output doesn't use scope hoisting and is like 10x longer than the expected output. Did I misconfigure something?

**Comment by Abdulvorisjs** [comment]
hi 
```js
🚨 Build failed.

@parcel/transformer-js: Expected ',', got 'Esuperio'

  /media/abdulvoris/66C0DC25C0DBF8EF/Abdulvoris/app/maps/node_modules/faker/lib/locales/it/name/first_name.js:396:11
    395 |   'Eros',
  > 396 |   'Esa�',
  >     |          ^
    397 |   'Esuperio',
    398 |   'Eterie',
```
I have a bug, what can i do?
