### ISSUE TITLE
Parcel 2: another SWC regression: `Uncaught ReferenceError: $55cef6b6a3de3a733971a44b5a0765e6$exports is not defined` on runtime

### ISSUE THREAD

**Issue by danieltroger** [parcel-bundler/parcel#6304]
# 🐛 bug report

Congratulations on one of my scripts running error free in modern browsers with the new SWC nightlies!

However, there are still issues left when building for IE11.

In this case I get `Uncaught ReferenceError: $55cef6b6a3de3a733971a44b5a0765e6$exports is not defined` when running a script built for IE11.
I have narrowed it down to the String.prototype.replaceAll polyfill that I use. It seems to use https://github.com/inspect-js/object-inspect and something in there confuses SWC/Parcel.

What exactly it is is left as an exercise for the reader 😏 Easy reproduction .zip attached.

## 🎛 Configuration (.babelrc, package.json, cli command)

Please see attached .zip file.

## 🤔 Expected Behavior

No error / crash

## 😯 Current Behavior

Output doesn't run at all

## 💁 Possible Solution

Revert the behavior to my favorite version, 650, where everything works fine ☺️

## 🔦 Context

Modern version built and ran successfully. My hopes were high but I couldn't believe everything would actually work. Than I ran the version for older browsers and here we are. Back to 650 I go.

Also, there's another issue left with private class fields and I don't know what it is yet 😩

## 💻 Code Sample

[parcel-debugging-fun-for-mischnic.zip](https://github.com/parcel-bundler/parcel/files/6501026/parcel-debugging-fun-for-mischnic.zip)

Note: This .zip has a .babelrc, I don't know if it makes a difference.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.672+71b3b935|
| Node             |v16.1.0|
| npm/Yarn         |7.11.2|
| Operating System |macOS 10.15.7 (19H1030)|

**Comment by danieltroger** [comment]
Nooo, I just doxed myself… Now I have to think about what I say 😟

**Comment by mischnic** [comment]
Minimal reproduction:

```js
// index.js
var inspectCustom = require('./b.js').custom;
console.log(inspectCustom)
```

```js
// b.js (empty)
```

<br>

It works correctly with
```js
var inspectCustom = require('./b.js');
let y = inspectCustom;
console.log(y.custom)
```

so the problem is that the exports object isn't generated if we have determined that only specific values (`custom`) are used

---

>  has a .babelrc, I don't know if it makes a difference.

It still errors even without that, so apparently not.

**Comment by danieltroger** [comment]
Is there a workaround for this? I don't wanna be stuck on v650

Sorry for when-eta-ing but I can't resist
