### ISSUE TITLE
Error recovery for SCSS errors

### ISSUE THREAD

**Issue by adamreisnz** [parcel-bundler/parcel#632]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
Both?

When parsing SCSS that is invalid, Parcel throws an error and outputs log info in the console, e.g.

```
Undefined variable: "$colorTextMuted".
    at options.error (/Users/.../node_modules/node-sass/lib/index.js:291:26)
(node:42132) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Undefined variable: "$colorTextMuted".
(node:42132) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

First problem is the unhandled rejections warning, but second and more importantly, it doesn't seem there is any way to recover from these errors other than killing the Parcel process and restarting it.

When these errors appear, it would be nice if Parcel would automatically try to re-build when files have changed. This is not happening at the moment on OS X.

**Comment by brandon93s** [comment]
Looks like the error is occurring inside of `node-sass`. We could `try...catch` the `async` call into node-sass and fallback to an empty stylesheet, while reporting the error to the user. A similar strategy is likely warranted across other/all Asset types.

**Comment by adamreisnz** [comment]
Yeah that'd be good. Or perhaps if possible, use the last known valid stylesheet. But that might not be possible, I don't know the underlying architecture of parcel.

But usually with other bundlers, these errors are gracefully captured and when files are changed it tries again.

**Comment by brandon93s** [comment]
@adamreisnz what version of parcel are you using? It's currently working as we've discussed on my machine.

**OS:**      Windows 10
**Parcel:** 1.5.0

**Demo:**

![632](https://user-images.githubusercontent.com/4730164/35368208-2602a218-0150-11e8-9233-95514f6c9049.gif)

**Comment by farskid** [comment]
@brandon93s For me, on Mac OS Sierra with parcel v1.5.0, I get this error:
<img width="1145" alt="screen shot 1396-11-05 at 18 43 07" src="https://user-images.githubusercontent.com/8332043/35395506-c849ae36-01ff-11e8-801e-fba1fc529589.png">

**Comment by adamreisnz** [comment]
I was using `parcel` 0.0.1, before realising there's another package, `parcel-bundler` at 1.5.0.
I've re-tested with 1.5.0 and it seems to recover from the error (although it still complains about an unhandled rejection).

It's really confusing to have 2 packages out there that do (are?) the same. Can you please deprecate the one called `parcel` so it shows a warning, as it's clearly outdated and not in use?

This issue can probably be closed.

**Comment by jamesmenera** [comment]
This bug would be pretty hard to close as I don’t think we can have npm takedown the `parcel` package or forward it to `parcel-bundler` with out the help of `sifteo` which looks like it might be a defunct company as of ~4years ago or maybe find the person that registered it to npm. Although if anyone else knows any other suggestions I am all ears. 

Although I think it might be worth doing as people are trying to download it thinking it is affiliated with 'parcel-bundler` and most likely reflecting negatively on this project. The only contributor is https://www.npmjs.com/~jaredhanson. It might be worth reaching out and seeing if he could help.

Here are some download numbers
<img width="290" alt="screen shot 2018-01-30 at 6 35 08 pm" src="https://user-images.githubusercontent.com/398162/35602521-856fc356-05ed-11e8-9526-f928b36efa17.png">

**Comment by adamreisnz** [comment]
There's [deprecate](https://docs.npmjs.com/cli/deprecate), you can put a link to the new package in there and at least have a warning show up.

**Comment by jamesmenera** [comment]
@adamreisnz it is my assumption you might have mistakenly ran `npm install -g parcel` or `yarn global add parcel` Which is the package I have given the link to below and is the only parcel package at version `0.0.1`

https://www.npmjs.com/package/parcel

**Comment by adamreisnz** [comment]
Yes, that's what I wrote above. Is that package managed by parcel or not? If yes, it should be deprecated and a notice added to indicate it shouldn't be used. If not, the author should probably be contacted to do the same.

**Comment by DeMoorJasper** [comment]
@adamreisnz the package is owned by @jaredhanson not Parcel
