### ISSUE TITLE
Object spread doesn't work when transpiled

### ISSUE THREAD

**Issue by evanw** [parcel-bundler/parcel#6322]
# 🐛 bug report

I'm trying to build code that uses [object spread](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) but the result is always an empty object after bundling with Parcel if Parcel is configured such that object spread is transpiled. Here's an example:

```
$ cat package.json
{
  "engines": { "node": "8.0.0" },
  "dependencies": { "parcel": "2.0.0-beta.3.1" }
}

$ cat example.js
var obj = { foo: 1 }
console.log({ ...obj, foo: 2 })

$ node example.js
{ foo: 2 }

$ parcel build example.js

$ node dist/example.js
{}
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
parcel build example.js
```

## 🤔 Expected Behavior

I expected the transformed code to be equivalent to the original. Specifically, the output file should print `{ foo: 2 }` when run.

## 😯 Current Behavior

The transformed code prints `{}` instead, which is unexpected.

## 🔦 Context

The context is that I'm working on updating esbuild's benchmarks and the TypeScript benchmark makes use of object spread. I think I may be able to work around this issue by just picking a more modern build target but I figured I should file this bug anyway in case it's not already filed.

## 💻 Code Sample

```js
var obj = { foo: 1 }
console.log({ ...obj, foo: 2 })
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.3.1 |
| Node             | v16.0.0 |
| npm/Yarn         | 7.13.0 |
| Operating System | macOS 11.3.1 |

**Comment by mischnic** [comment]
The same bug as https://github.com/swc-project/helpers/issues/5, https://github.com/swc-project/swc/issues/1462.

The generated code is 
```js
var {objectSpread: $1BwTL$objectSpread} = require("@swc/helpers");

var $f4a43f8c2e096429b168e6bfc86748ad$var$obj = {
    foo: 1
};
console.log($1BwTL$objectSpread({
}, $f4a43f8c2e096429b168e6bfc86748ad$var$obj, {
    foo: 2
}));
```
at the moment. But we should probably still bundle `@swc/helpers` (so always, even if `includeNodeModules` is false).

**Comment by kdy1** [comment]
I tried fixing https://github.com/swc-project/swc/issues/1462, but it seems like recent version of swc can handle code properly.

```js
export default function _objectSpread(target) {
    var _arguments = arguments, _loop = function(i) {
        var source = _arguments[i] != null ? _arguments[i] : {
        };
        var ownKeys = Object.keys(source);
        if (typeof Object.getOwnPropertySymbols === "function") {
            ownKeys = ownKeys.concat(Object.getOwnPropertySymbols(source).filter(function(sym) {
                return Object.getOwnPropertyDescriptor(source, sym).enumerable;
            }));
        }
        ownKeys.forEach(function(key) {
            defineProperty(target, key, source[key]);
        });
    };
    for(var i = 1; i < arguments.length; i++)_loop(i);
    return target;
};
```

`arguments` is stored to a variable.

I'll try publishing a new version of `@swc/helpers`.

**Comment by kdy1** [comment]
I published a new version of `@swc/helpers`.
Can you try it again?

**Comment by mischnic** [comment]
Thanks, it works correctly now!
