### ISSUE TITLE
Native SSR API

### ISSUE THREAD

**Issue by brillout** [parcel-bundler/parcel#6324]
Hi, author of [vite-plugin-ssr](https://github.com/brillout/vite-plugin-ssr) here.

Vite has a "native" SSR API https://vitejs.dev/guide/ssr.html which nurtures a flourishing environment (SvelteKit, Ream, vite-ssr, vite-plugin-ssr, fastify-vite, and more coming.)

Is an API like this something Parcel is interested in?

I've extensive experience with SSR, happy to contribute to the development of a native SSR API, if you are interested.

(Congrats on the beta 3 release 🎉 .)

**Comment by mischnic** [comment]
I think that would be great. What features are we missing for that (on a high level)? Probably somehow "importing" the client bundles from a Node server?

Also, how do https://github.com/parcel-bundler/parcel/issues/3767 and https://github.com/parcel-bundler/parcel/issues/3821 relate to that

**Comment by brillout** [comment]
It's been 1.5 years I tried to do a parcel-ssr plugin, so I'm not too much into Parcel's plugin architecture anymore.

Vite's native SSR API is pretty much perfect: it takes care of all the painfull things while being flexible enough so that you can implement any SSR library/framework you want.

I highly recommend to dig into the examples https://vitejs.dev/guide/ssr.html#example-projects.

The API mainly revolves around `import.meta.glob()` (e.g. `import.meta.glob('/**/*.page.js')` to import all user-land `.page.js` files), and `ssrLoadModule()` to load the server-side entry that will transpile and execute modern user-code (ES6 modules, JSX, CSS, ...).

You can also have a look at https://github.com/brillout/vite-plugin-ssr and play with the boilerplates (`npm init vite-plugin-ssr`) to see what kind of projects Vite's SSR native API enables. In my case, it allowed me to easily (1.6k LOC) create a Next.js/Nuxt clone.

Once framework authors like myself have experienced such native SSR API, we will not want to choose any bundler that does not help us with SSR. Without such API, it's incredibly painful to implement SSR. It's only a matter of time until all bundlers have a native SSR API.

Let me know if you have any questions, happy to assist. I'm aslo happy to review any thoughts you may have around this.

**Comment by mischnic** [comment]
I've hacked https://github.com/vitejs/vite/tree/main/packages/playground/ssr-react to use Parcel instead: https://github.com/mischnic/parcel-ssr.

The heart of the whole thing is
```json
  "client": "dist-client/index.html",
  "ssr": "dist-server/index.js",
  "targets": {
    "client": {
      "source": "src/index.html",
      "engines": {
        "browsers": [
          "last 1 Chrome version"
        ]
      }
    },
    "ssr": {
      "source": "src/index.server.jsx",
      "isLibrary": true,
      "engines": {
        "node": ">= 14.0.0"
      }
    }
  },
```

Everything seems to work so far, though it's probably not very robust (e.g. the express server doesn't wait for the Parcel builds to be finished before responding). And referencing an image in the SSR output is broken because the bundle hashes are different

Our equivalent of `!import.meta.env.SSR` would be `process.browser` (which Parcel already handles)

Is this what you had in mind (as the foundation needed for something like vite-plugin-ssr)?

**Comment by brillout** [comment]
Neat.

Does a server-side change lead to a browser reload?

Also Vite has `import.meta.glob()` to specify custom user entry points (e.g. `import.meta.glob('**/*.page.*')`).

I guess `import * as pages from "./pages/*.jsx";` imports the pages eagerly. But that's a problem for the client-side as the browser shouldn't load all the pages at once. It's also a problem for the server where we want to lazy load pages for fast cold starts (e.g. for faster serverless deployement cold starts).

I'm glad Parcel is showing interested in this. I kinda lost hope when I tried back then :-).

**Comment by mischnic** [comment]
> Does a server-side change lead to a browser reload?

You mean a change to server-only code like https://github.com/mischnic/parcel-ssr/blob/master/src/index.server.jsx ?

Probably not, the existing ("client-side") React HMR works fine, so changing some React component doesn't lead to a hard refresh but the usual `module.hot.accept`-based component update.


> Also Vite has import.meta.glob() to specify custom

I just followed the vite example in that regard
`import.meta.globEager` should be `import * as pages from "./pages/*.jsx"; ` and
`import.meta.glob` should be `import("./pages/*.jsx")`

**Comment by brillout** [comment]
A neat (and crucial) thing about Vite's SSR API is that "full-stack" HMR is baked it; when a server-only code changes then the browser reloads and the right caches are invalidated. In other words, HMR (more precisely speaking auto-reload) works out of the box for SSR.

> `import.meta.globEager` should be `import * as pages from "./pages/*.jsx"; ` and
> `import.meta.glob` should be `import("./pages/*.jsx")`

Is there a way to load only one page? I guess `import("./pages/*.jsx")` loads all pages at once.

This is crucial at scale; for large apps loading all pages at once is not an option. I'm actually currently working on a project that has this very problem where loadings all pages takes 10 seconds, and the project isn't even that large.

**Comment by mischnic** [comment]
> A neat (and crucial) thing about Vite's SSR API is that "full-stack" HMR is baked it; when a server-only code changes then the browser reloads and the right caches are invalidated. In other words, HMR (more precisely speaking auto-reload) works out of the box for SSR.

Is that different from what I described? In the React SSR case, I think there aren't really server-only changes? Because otherwise the server-rendered HMR would not be the same as the client-side version when hydrating.
Or are you talking about another usecase? E.g. a site with no client-side JS like an eleventy blog.

> Is there a way to load only one page? I guess import("./pages/*.jsx") loads all pages at once.

No, it returns `{ fileA: [Function: a], fileB: [Function: b] }` and calling these functions would then actually start downloading the corresponding bundle.
So `import("./pages/*.jsx")` is equivalent to `{fileA: () => import("./pages/fileA.jsx"), fileB: () => import("./pages/fileB.jsx")`

**Comment by brillout** [comment]
Yes in SSR there are plenty of code that are server-only, e.g. https://github.com/brillout/vite-plugin-ssr#pageserverjs which is a central piece of `vite-plugin-ssr` and it's server-only.

**Comment by brillout** [comment]
So I guess (and AFAICT) the only thing missing for a Parcel SSR plugin like vite-plugin-ssr would be full-stack HMR support.

Is that something you are interested in implementing?

**Comment by DylanPiercey** [comment]
@mischnic I think the expectation is essentially that if a file invalidates and it supports HMR then:

If it is in both the server & browser compilations then do an HMR for the server and browser.
If it is only in the browser compilation then do a normal HMR for the browser.
If it is only in the server compilation then do HMR for the server and a full page reload for the browser.

This is basically what vite does.

**Comment by mariocesar** [comment]
There is already an SSR guide or solution for parcel?
