### ISSUE TITLE
🐛 issue with css outside of head tag

### ISSUE THREAD

**Issue by farskid** [parcel-bundler/parcel#633]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

This is a bug.

If I try to reference to my css outside of the `head` tag, it throws an error:
`Cannot read property 'content' of undefined`

### 🎛 Configuration (.babelrc, package.json, cli command)

My babel configuration is:
```js
{
  "presets": ["env", "stage-2"]
}
```

### 🤔 Expected Behavior

This should parse and add css no matter where it is referenced.

### 😯 Current Behavior

throws `Cannot read property 'content' of undefined`.

### Full error in console:

```
Cannot read property 'content' of undefined
    at HTMLPackager.getHeadContent (/usr/local/lib/node_modules/parcel-bundler/src/packagers/HTMLPackager.js:30:12)
    at HTMLPackager.insertSiblingBundles (/usr/local/lib/node_modules/parcel-bundler/src/packagers/HTMLPackager
.js:41:21)
    at /usr/local/lib/node_modules/parcel-bundler/node_modules/posthtml/lib/index.js:109:53
    at Array.forEach (<anonymous>)
    at PostHTML.process (/usr/local/lib/node_modules/parcel-bundler/node_modules/posthtml/lib/index.js:104:18)
    at HTMLPackager.addAsset (/usr/local/lib/node_modules/parcel-bundler/src/packagers/HTMLPackager.js:19:9)
    at Bundle._addDeps (/usr/local/lib/node_modules/parcel-bundler/src/Bundle.js:146:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.5.0
| Node             | 9.4.0
| npm/Yarn         | yarn v1.3.2
| Operating System | Mac OS Sierra 10.12.6

**Comment by brandon93s** [comment]
Hello @farskid - are you able to provide a sample gist / repository to reproduce this issue? I've been unable to reproduce with a simple "Hello World" referencing style sheets from the body.

**Comment by farskid** [comment]
Sure. I'll push the sample into a repo and reference it here :)

**Comment by brandon93s** [comment]
@farskid - Parcel is failing because the [entry](https://github.com/farskid/guessing-game/blob/develop/index.html) is not valid html. The build will succeed if you update your index to the following:

```html
<!DOCTYPE html>
<html lang="en">

    <link rel="stylesheet" href="style.css">

    <div id="base"></div>
    <button id="restart">Restart Game!</button>
    
    <script src="index.js"></script>

</html>
```

Is there a use case for excluding the necessary html file structure, or does this resolve your issue?

**Comment by farskid** [comment]
@brandon93s This makes sense. so by valid html you mean having the `html`, `head` and `body` tags?

**Comment by brandon93s** [comment]
That's correct. You can use the following to validate your HTML:

http://validator.w3.org/#validate_by_input

**Comment by farskid** [comment]
@brandon93s Correct. So as I mentioned [here](https://github.com/parcel-bundler/parcel/pull/654), if I added the `head` tag even without `html` tag, parcel would bundle successfully. maybe it's something worth to check too?
