### ISSUE TITLE
is .swcrc ignored in the new beta3

### ISSUE THREAD

**Issue by miguelcaravantes** [parcel-bundler/parcel#6335]
# 💬 RFC
i am creating a new react empty project using beta 3, according to blog it uses swc by default i have no .babelrc at all i make it work with react and added a .swcrc but changin values not make any change in the transpilation, so as parcel don't have any documentation at all using swc, my question is, .is .swcrc working with parcel out the box or should i use the old .babelrc instead

## 💻 Examples
.swcrc
```
{
  "jsc": {
    "externalHelpers": true
    "parser": {
      "jsx": true,
    },
    "transform": {
      "react": {
        "runtime": "automatic",
        "importSource": "react"
    }
    "target": "es6",
  }
}

```

react runtime automatic doesnt work, changing target doesnt change the output, i can even badformat the json and parcel doesn't even complains so i assuming is not reading the config.

**Comment by mischnic** [comment]
Yes, it is ignored at the moment. But this is something we need to look into

**Comment by miguelcaravantes** [comment]
thank you for let me know.

**Comment by ndrewtl** [comment]
I am trying to use `.swcrc` in 2022 and it still seems to be ignored. Any plans to reimplement?

**Comment by amartincolby** [comment]
Related: https://github.com/parcel-bundler/parcel/issues/8613
