### ISSUE TITLE
[Source Maps] TypeError: Cannot read property 'line' of undefined

### ISSUE THREAD

**Issue by robcrocombe** [parcel-bundler/parcel#634]
**Choose one:** this a 🐛 bug report

I get an error when I build my project with Parcel 1.5.0 with source maps enabled. With source maps disabled, it works fine (as in 1.4.1).

### 🎛 Configuration (.babelrc, package.json, cli command)

Using TypeScript, `tsconfig.json`:

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "noImplicitAny": false,
    "removeComments": false,
    "target": "es2015",
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "allowJs": true,
    "listFiles": true,
    "noUnusedParameters": true,
    "noUnusedLocals": true,
    "module": "commonjs"
  }
}
```

Calling Parcel directly (i.e. `import parcel from 'parcel-bundler';`) with a single `index.ts` as the entry point. Entry file imports other TS files and npm modules with the `import` syntax.

### 🤔 Expected Behavior

It should compile and run.

### 😯 Current Behavior

I get this error in the terminal:

```
(node:7050) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'line' of undefined
    at extension.eachMapping.mapping (/Users/.../node_modules/parcel-bundler/src/SourceMap.js:127:32)
    at Array.forEach (<anonymous>)
    at SourceMap.eachMapping (/Users/.../node_modules/parcel-bundler/src/SourceMap.js:93:19)
    at SourceMap.extendSourceMap (/Users/.../node_modules/parcel-bundler/src/SourceMap.js:125:15)
    at <anonymous>
(node:7050) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7050) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Exception occurs [here](https://github.com/parcel-bundler/parcel/blob/e9596d61f8ec534896359a3820817574c8fb1ea4/src/SourceMap.js#L127) in the Parcel source:

```js
extension.eachMapping(mapping => {
  let originalMapping = original.originalPositionFor({
    line: mapping.original.line, // <- HERE
    column: mapping.original.column
  });
```

This appears multiple times (I'm guessing because I have a lot of files).

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.5.0 |
| TypeScript       | 2.5.2 |
| Node             | 9.3.0 |
| npm         | 5.5.1 |
| Operating System | macOS Sierra 10.12.6 |

Thanks!

**Comment by DeMoorJasper** [comment]
Appears typescript builds invalid maps(although i’ve not seen this in my tests) i’ll push a fix asap

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
