### ISSUE TITLE
Incorrect args parse in multi targets

### ISSUE THREAD

**Issue by linbudu599** [parcel-bundler/parcel#6342]
# 🐛 bug report

When specifying multiplt targets like `--target app appModern`, an error would be thrown:

```bash
🚨 Build failed.
unknown: Entry D:\PROJECT\appModern does not exist
```
`appModern ` is regarded as entry incorrectly, the reason is `--target` in [CLI](https://github.com/parcel-bundler/parcel/blob/v2/packages/core/parcel/src/cli.js#L69) was set to `--target [name]`, which accept only one value.

To fix it, just make it `--target [name...]`, then `--target app appModern` will be parsed as `targets:["app", "appModern"]`

But it would require `--target` arg to be put behind entry ?

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
> To fix it, just make it --target [name...], then --target app appModern will be parsed as targets:["app", "appModern"]
>
> But it would require --target arg to be put behind entry ?

This is why I'm inclined to leave it as is, to avoid confusion.

**Comment by mischnic** [comment]
You can do `--target app --target appModern` in case you haven't tried that yet
