### ISSUE TITLE
Spread operator breaks js in ms edge webview

### ISSUE THREAD

**Issue by dhalucario** [parcel-bundler/parcel#6345]
# 🐛 bug report
I am currently trying to write a "webapp" which can be loaded into a webview using https://github.com/Boscop/web-view

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// .babelrc.json
{
  "presets": [
    ["@babel/preset-env", {
      "include": [
        "@babel/plugin-transform-spread",
        "@babel/plugin-proposal-object-rest-spread"
      ]
    }]
  ]
}
```

```html
<!-- Entrypoint index.html -->
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Casual Quickplay</title>

        <style>
            @import './css/import.scss';
        </style>
    </head>
    <body>
        ...
        <script>
            import './js/index.js';
        </script>
    </body>
</html>
```
## 🤔 Expected Behavior

I was hoping that it would replace all spread operators with `Object.assign()`

## 😯 Current Behavior

![grafik](https://user-images.githubusercontent.com/10533763/119373563-d6e0e780-bcb8-11eb-812f-5be94db498db.png)
![grafik](https://user-images.githubusercontent.com/10533763/119373692-fa0b9700-bcb8-11eb-8ba9-4223250b049c.png)

## 💻 Code Sample

There is not much of a difference in setup between a minimal install and this.
https://gitlab.com/dhalucario/tf2-cqp

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.3.1
| Node             | v16.2.0
| npm/Yarn         | 7.14.0
| Operating System | Windows 10 21H1 (Build 19043.985)

**Comment by danieltroger** [comment]
Did you configure a target in package.json ?

Parcel by default assumes that you will run your code on a modern browser. You need to tell it for which browser it should transpile the syntax, please see https://v2.parceljs.org/configuration/package-json/#targets or if you need an example the package.json that I used [here](https://github.com/parcel-bundler/parcel/files/6501283/parcel-private-class-trouble.zip)

**Comment by mischnic** [comment]
The problem here is that code from dependencies in node_modules isn't transpiled, even with a browserslist config (at least for some functions use rest parameters `function addClasses(elmts, ...classes) {`). See https://github.com/parcel-bundler/parcel/issues/1655

**Comment by dhalucario** [comment]
> 
> 
> Did you configure a target in package.json ?
> 
> Parcel by default assumes that you will run your code on a modern browser. You need to tell it for which browser it should transpile the syntax, please see https://v2.parceljs.org/configuration/package-json/#targets or if you need an example the package.json that I used [here](https://github.com/parcel-bundler/parcel/files/6501283/parcel-private-class-trouble.zip)

Would a .browserslistrc in the project folder fine too?

**Comment by dhalucario** [comment]
> 
> 
> The problem here is that code from dependencies in node_modules isn't transpiled, even with a browserslist config (at least for some functions use rest parameters `function addClasses(elmts, ...classes) {`). See #1655

Hm if that's the issue I have a small problem.

**Comment by danieltroger** [comment]
> The problem here is that code from dependencies in node_modules isn't transpiled, even with a browserslist config (at least for some functions use rest parameters `function addClasses(elmts, ...classes) {`). See #1655

Oh sorry, I didn't notice there was spread in node_modules, all I checked was package.json.

Might I recommend the forbidden solution? `sed -i 's/!filePath.includes(NODE_MODULES)/true/' node_modules/\@parcel/core/lib/summarizeRequest.js` (you might need to install gsed if you're using macOS)

This will enable transpilation of all your node_modules, provided that you have the right target configured.

**Comment by dhalucario** [comment]
> 
> 
> > The problem here is that code from dependencies in node_modules isn't transpiled, even with a browserslist config (at least for some functions use rest parameters `function addClasses(elmts, ...classes) {`). See #1655
> 
> Oh sorry, I didn't notice there was spread in node_modules, all I checked was package.json.
> 
> Might I recommend the forbidden solution? `sed -i 's/!filePath.includes(NODE_MODULES)/true/' node_modules/\@parcel/core/lib/summarizeRequest.js` (you might need to install gsed if you're using macOS)
> 
> This will enable transpilation of all your node_modules, provided that you have the right target configured.

Im gonna give that a try later, I hope it works on Windows.

**Comment by mischnic** [comment]
That command makes this function return `true` instead: https://github.com/parcel-bundler/parcel/blob/14a039f071c35ad154067715f49d2494c249890f/packages/core/core/src/summarizeRequest.js#L22

You can also modify `node_modules/@parcel/core/lib/summarizeRequest.js` by hand with an editor.
