### ISSUE TITLE
Parcel 2 SWC regression: In `--no-optimize` builds parcel escapes unicode strings imported with readFilySync in a way that throws a syntax error in IE11

### ISSUE THREAD

**Issue by danieltroger** [parcel-bundler/parcel#6356]
# 🐛 bug report

After the fixing of several other issues I happily tried the newest SWC nightly again, and it seems like pretty much everything works! 🎉

Well, except my non-serve dev builds in ie11.

main.ts:
```
import { readFileSync } from "fs";
console.log(readFileSync("./src/text.txt", "utf-8"));
```

text.txt
```
🤭
```

## 🎛 Configuration (.babelrc, package.json, cli command)

Please see attached .zip file.

## 🤔 Expected Behavior

Output of v650:
```
(function () {
  // ASSET: node_modules/@parcel/node-resolver-core/lib/_empty.js
  var $c0f442ee2b789b4d3c9bc37d6fb33f83$exports = {};
  console.log("🤭\n");
})();
```

## 😯 Current Behavior

```
(function () {
"use strict";


console.log("\u{1f92d}\n");

})();
//# sourceMappingURL=ie11.js.map

```

-> 
<img width="220" alt="Screenshot 2021-05-25 at 13 13 13" src="https://user-images.githubusercontent.com/4047180/119488545-f7fa1480-bd5a-11eb-9819-38bca0ec4617.png">

## 💁 Possible Solution

Revert to behavior of 650 - don't escape unicode characters which works in IE11:
<img width="388" alt="Screenshot 2021-05-25 at 13 15 38" src="https://user-images.githubusercontent.com/4047180/119488856-4e675300-bd5b-11eb-9848-3b42bf17c703.png">

Alternatively figure out a way of escaping the characters that doesn't crash IE11.

## 🔦 Context

Tried out new SWC parcel again. But tbh I guess this is low prio because it works correctly when building without `--no-optimize`.

## 💻 Code Sample

[parcel-breaks-ie11-with-escaped-unicode.zip](https://github.com/parcel-bundler/parcel/files/6538814/parcel-breaks-ie11-with-escaped-unicode.zip)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.686+14a039f0|
| Node             |v16.1.0|
| npm/Yarn         |npm v7.11.2 / yarn v1.22.10|
| Operating System |macOS 10.15.7 (19H1030)|

**Comment by mischnic** [comment]
https://github.com/swc-project/swc/issues/1744

**Comment by danieltroger** [comment]
@mischnic I think [swc finally made a new release](https://github.com/swc-project/swc/releases/tag/v1.2.59), feel free to update to it 😇

**Comment by danieltroger** [comment]
@mischnic thanks! Did this get into todays nightly or do I have to wait until tomorrow to test?

**Comment by mischnic** [comment]
The latest nightly is based on https://github.com/parcel-bundler/parcel/commit/760fc61c601641270e7ac7d4320682a074afebf8, so that PR was included

**Comment by danieltroger** [comment]
@mischnic this issue has a "regression", can you reopen? I can also create new issue otherwise.

How to reproduce:
download repro repo
replace contents of text.txt with

```
🤭
€
ł
£

```

run `yarn run build`

check output ->

```
(function () {
"use strict";


console.log("🤭\n€\nł\n\xa3\n");

})();
```

See bug (`\xa3`)
Profit
