### ISSUE TITLE
Uncaught ReferenceError caused by code hoisting

### ISSUE THREAD

**Issue by NovaAtWarren** [parcel-bundler/parcel#6358]
# 🐛 bug report

Issue with bundling Materialize, I believe it's to do with tree shaking / code hoisting since it goes away when it's disabled
When running the webapp, I get a "module is not defined"

## 🎛 Configuration (.babelrc, package.json, cli command)

No babel config

.parcelrc:
```js
{
	"extends": "@parcel/config-default",
	"transformers": {
		"*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
	}
}
```

package.json:
```js
{
  "devDependencies": {
    "@types/express": "^4.17.11",
    "@types/express-session": "^1.17.3",
    "@types/fs-extra": "^9.0.11",
    "@types/materialize-css": "^1.0.9",
    "@types/node": "^15.0.2",
    "@types/pg": "^8.6.0",
    "@types/shelljs": "^0.8.8",
    "@typescript-eslint/eslint-plugin": "^4.24.0",
    "@typescript-eslint/parser": "^4.24.0",
    "chai": "^4.3.4",
    "eslint": "^7.25.0",
    "eslint-plugin-vue": "^7.9.0",
    "fs-extra": "^10.0.0",
    "mocha": "^8.4.0",
    "nodemon": "^2.0.7",
    "npm-run-all": "^4.1.5",
    "nyc": "^15.1.0",
    "parcel": "^2.0.0-beta.2",
    "rimraf": "^3.0.2",
    "shelljs": "^0.8.4",
    "ts-node": "^10.0.0",
    "typescript": "^4.2.4"
  },
  "name": "chasm",
  "version": "1.0.0",
  "dependencies": {
    "@okta/oidc-middleware": "^4.0.3",
    "axios": "^0.21.1",
    "dotenv": "^10.0.0",
    "ejs": "^3.1.6",
    "express": "^4.17.1",
    "express-session": "^1.17.1",
    "materialize-css": "^1.0.0",
    "pg": "^8.6.0",
    "pg-promise": "^10.10.2",
    "vue": "^2.6.12",
    "vue-qrcode-reader": "^3.0.0"
  },
  "scripts": {
    "clean": "rimraf dist/*",
    "copy-assets": "ts-node tools/copyAssets",
    "lint": "eslint src",
    "lint-fix": "eslint --fix src",
    "tsc": "tsc --build --pretty tsconfig.json",
    "parcel": "parcel build --dist-dir dist/public/js/ --no-optimize src/public/js/*.ts",
    "parcel-optimize": "parcel build --dist-dir dist/public/js/ src/public/js/*.ts",
    "build": "npm-run-all clean lint tsc copy-assets parcel",
    "dev:start": "npm-run-all start",
    "dev": "nodemon --watch src -e ts,ejs --exec npm run dev:start",
    "prestart": "npm run build",
    "start": "node .",
    "test": "mocha tests/**/*.js",
    "coverage": "nyc -r lcov -e .ts -x \"*.test.ts\" yarn test",
    "initdb": "ts-node tools/initdb",
    "breakauth": "cp tools/break_oidcUtil.js node_modules/@okta/oidc-middleware/src/oidcUtil.js"
  },
  "alias": {
    "vue": "./node_modules/vue/dist/vue.common.js"
  },
  "author": "",
  "description": "",
  "license": "UNLICENSED",
  "peerDependencies": {
    "postcss": "^8.0.0"
  }
}
```

CLI:
`parcel build --dist-dir dist/public/js --no-optimize src/public/js/*.ts; node dist/src/index.js`
For context, dist/src/index.js was build by another program, and all it does is manage an API and serve the page that the parcel bundle is erroring out on. All data is being transferred correctly, the issue is with compilation itself.

## 🤔 Expected Behavior

Web app opening, functioning, etc (like it did with parcel-bundler)

## 😯 Current Behavior

```
Uncaught ReferenceError: module is not defined
    at materialize.js:1081
    at chargers.ts:449
(anonymous)	@	materialize.js:1081
(anonymous)	@	chargers.ts:449
```

## 💁 Possible Solution

WORKAROUND: use flag `--no-scope-hoisting`

## 🔦 Context

I understand it's a beta right now, but I was trying to upgrade to avoid some security flaws and deprecated packages, and having the default break the compilation didn't seem great.
I'm only trying to load, and use, materialize, by loading it into a file that is served instead of using a CDN (no guaranteed internet access, can't use a CDN)

## 💻 Code Sample

Pending - I'm trying to trim down the code base to remove NDA information before being able to release it

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.2 |
| Node             | 12.21.0 I think? not sure how to check through npm/yarn. |
| npm/Yarn         | Yarn 1.22.10, installed globally |
| Operating System | Ubuntu 21.04 |
| Hardware | 2 Core VPS on Docker |

**Comment by mischnic** [comment]
> 2.0.0-beta.2

Please try a newer version. This might already be fixed.

**Comment by NovaAtWarren** [comment]
Apologies, I just tested it and it seems to be working. I'd checked on NPM and it said the latest was 2.0.0-beta.2.
