### ISSUE TITLE
parcel fails silently without any error reporting

### ISSUE THREAD

**Issue by urbanhop** [parcel-bundler/parcel#636]
reproduce: create a file and name it index.htm (not html!)

    > parcel index.htm

parcel reports "Server running at http://localhost:1234", but this url is unaccessible.

would be nice to have error reporting.

**Comment by DeMoorJasper** [comment]
This seems like an easy fix, i'll throw in a PR in a bit

**Comment by urbanhop** [comment]
Thank you for caring about .htm files. In general making parcel more verbose (-verbose switch) might benefit users.
