### ISSUE TITLE
@parcel/transformer-svg-react is butchering SVG content (from Inkscape)

### ISSUE THREAD

**Issue by broofa** [parcel-bundler/parcel#6362]
# 🐛 bug report

Not a lot of detail needed on this one.  I'm importing [this SVG image](https://gist.github.com/broofa/9273cb527c75371c5edc8e2f98fbe520) using `@parcel/transformer-svg-react` with the following code:
```js
import Logo from './logo.svg';

return <Logo width='200' height='200' />
```

Here's what the original SVG looks like:
![image](https://user-images.githubusercontent.com/164050/119739761-6ce25280-be1e-11eb-908c-f4aa9a3255ea.png)

... and here's what the transfomer is rendering:
![image](https://user-images.githubusercontent.com/164050/119739719-5805bf00-be1e-11eb-84c3-e5ac270602c7.png)

FWIW, this SVG was created with Inkscape.

From my package.json:
```
@parcel/transformer-svg-react: 2.0.0-nightly.1739 => 2.0.0-nightly.1739
```

## 🎛 Configuration (.babelrc, package.json, cli command)

.parcelrc config:
```js
{
  "extends": "@parcel/config-default",

  "transformers": {
    "*.svg": ["@parcel/transformer-svg-react"]
  }
}
```

## 🌍 Your Environment

```
$ envinfo
npx: installed 1 in 0.962s

  System:
    OS: macOS 11.1
    CPU: (8) x64 Apple M1
    Memory: 43.41 MB / 16.00 GB
    Shell: 5.1.0 - /usr/local/bin/bash
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.77
    Firefox: 88.0.1
    Safari: 14.0.2
  npmPackages:
    @parcel/babel-plugin-transform-runtime: 2.0.0-nightly.1823 => 2.0.0-nightly.1823
    @parcel/packager-raw-url: 2.0.0-beta.2 => 2.0.0-beta.2
    @parcel/transformer-sass: 2.0.0-beta.2 => 2.0.0-beta.2
    @parcel/transformer-svg-react: 2.0.0-nightly.1739 => 2.0.0-nightly.1739
    @parcel/transformer-webmanifest: 2.0.0-beta.2 => 2.0.0-beta.2
    @types/react-dom: 17.0.3 => 17.0.3
    @types/react-router-dom: 5.1.7 => 5.1.7
    @typescript-eslint/eslint-plugin: 4.20.0 => 4.20.0
    @typescript-eslint/parser: 4.20.0 => 4.20.0
    bootstrap: 5.0.1 => 5.0.1
    checkcss: 1.0.2 => 1.0.2
    eslint: 7.21.0 => 7.21.0
    eslint-config-standard: 16.0.2 => 16.0.2
    eslint-plugin-import: 2.22.1 => 2.22.1
    eslint-plugin-node: 11.1.0 => 11.1.0
    eslint-plugin-promise: 4.3.1 => 4.3.1
    eslint-plugin-react: 7.22.0 => 7.22.0
    eslint-plugin-react-hooks: 4.2.0 => 4.2.0
    firebase: 8.4.2 => 8.4.2
    firebaseui: 4.8.0 => 4.8.0
    nanoid: 3.1.22 => 3.1.22
    parcel: 2.0.0-beta.2 => 2.0.0-beta.2
    react: ^16.13.1 => 16.14.0
    react-bootstrap: 2.0.0-alpha.2 => 2.0.0-alpha.2
    react-dom: ^16.13.1 => 16.14.0
    react-router-bootstrap: 0.25.0 => 0.25.0
    react-router-dom: 5.2.0 => 5.2.0
    sass: 1.32.12 => 1.32.12
    simplur: 3.0.0 => 3.0.0
    typescript: 4.2.3 => 4.2.3
```

**Comment by mischnic** [comment]
Strange, it seems to work correctly on https://react-svgr.com/playground/, which is the same tool that's used by that transformer.

https://github.com/parcel-bundler/parcel/blob/8c0721e5a835ff89c6ae88df75bb5957a5ee89f0/packages/transformers/svg-react/src/SvgReactTransformer.js#L23-L34

**Comment by broofa** [comment]
FWIW, here's the SVG markup I get when I select the rendered `Logo` element `copy outerHTML` (in Chrome Web Develope Tools): https://gist.github.com/broofa/60aef44cea80924e7e975c503d358459

**Comment by broofa** [comment]
More FWIW: If I compare the SVG DOM of the original file to the DOM in the gist above (the DOM being rendered by `svgr` I guess?) it looks like the issue is that the SVG child elements are being ordered differently: 

![image](https://user-images.githubusercontent.com/164050/119772068-535efc00-be5a-11eb-83ed-609d99d32993.png)

**Comment by broofa** [comment]
@mischnic Found the problem. `@parcel/transformer-svg-react@latest` is using `janjakubnanista/svg-to-jsx`, which is where the above issue is coming from. 

`next` and `nightly` are using  `gregberge/svgr`, which doesn't appear to have this issue.  But I'm running into  https://github.com/gregberge/svgr/issues/271.  I'll file a separate issue for that, though, as I think this may still be a parcel issue.  (If I run @svgr/core CLI  to produce a React class manually it works without error.  But transformer-svg-react is choking.)
