### ISSUE TITLE
@parcel/transformer-svg-react "Namespace tags are not supported by default" error

### ISSUE THREAD

**Issue by broofa** [parcel-bundler/parcel#6365]
While diagnosing #6362 (importing the `logo.svg` file attached to that issue), I ran into the "Namespace tags are not supported by default" error mentioned in gregberge/svgr#271.

If I run the svgr CLI and generate a React component manually, via `npx @svgr/cli logo.svg > Logo.jsx`, I'm able to use the resulting module without issue.  But if I do `import Logo from './logo.svg'`, I get the error in the title. 

What's the best way to resolve this?  The error message suggests setting `throwIfNamespace: false`.  But how/where do I do that?    (Is this a .babelrc thing?  If so, how do I set that up without being taken down the path of having to install a bunch of parcel and babel plugins and presets just to get back to the current baseline functionality Parcel provides?

[Edit to add...]
## envinfo
```
  System:
    OS: macOS 11.1
    CPU: (8) x64 Apple M1
    Memory: 38.84 MB / 16.00 GB
    Shell: 5.1.0 - /usr/local/bin/bash
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.77
    Firefox: 88.0.1
    Safari: 14.0.2
  npmPackages:
    @parcel/babel-plugin-transform-runtime: 2.0.0-nightly.1823 => 2.0.0-nightly.1823 
    @parcel/packager-raw-url: 2.0.0-beta.2 => 2.0.0-beta.2 
    @parcel/transformer-sass: 2.0.0-beta.2 => 2.0.0-beta.2 
    @parcel/transformer-svg-react: 2.0.0-beta.3.1 => 2.0.0-beta.3.1 
    @parcel/transformer-webmanifest: 2.0.0-beta.2 => 2.0.0-beta.2 
    @types/react-dom: 17.0.3 => 17.0.3 
    @types/react-router-dom: 5.1.7 => 5.1.7 
    @typescript-eslint/eslint-plugin: 4.20.0 => 4.20.0 
    @typescript-eslint/parser: 4.20.0 => 4.20.0 
    bootstrap: 5.0.1 => 5.0.1 
    checkcss: 1.0.2 => 1.0.2 
    eslint: 7.21.0 => 7.21.0 
    eslint-config-standard: 16.0.2 => 16.0.2 
    eslint-plugin-import: 2.22.1 => 2.22.1 
    eslint-plugin-node: 11.1.0 => 11.1.0 
    eslint-plugin-promise: 4.3.1 => 4.3.1 
    eslint-plugin-react: 7.22.0 => 7.22.0 
    eslint-plugin-react-hooks: 4.2.0 => 4.2.0 
    firebase: 8.4.2 => 8.4.2 
    firebaseui: 4.8.0 => 4.8.0 
    nanoid: 3.1.22 => 3.1.22 
    parcel: 2.0.0-beta.2 => 2.0.0-beta.2 
    react: ^16.13.1 => 16.14.0 
    react-bootstrap: 2.0.0-alpha.2 => 2.0.0-alpha.2 
    react-dom: ^16.13.1 => 16.14.0 
    react-router-bootstrap: 0.25.0 => 0.25.0 
    react-router-dom: 5.2.0 => 5.2.0 
    sass: 1.32.12 => 1.32.12 
    simplur: 3.0.0 => 3.0.0 
    typescript: 4.2.3 => 4.2.3 
```

**Comment by mischnic** [comment]
Does it work correctly if you add `@parcel/transformer-svgo` in the config? That should be done in any case.

```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.svg": ["@parcel/transformer-svgo", "@parcel/transformer-svg-react"]
  }
}
```

**Comment by mischnic** [comment]
> If I run the svgr CLI and generate a React component manually, via npx @svgr/cli logo.svg > Logo.jsx, I'm able to use the resulting module without issue

That CLI runs svgo by default, which would explain the difference in behaviour if you just run the svg-react transformer.
