### ISSUE TITLE
Dev server sourcemap file contains home page content.

### ISSUE THREAD

**Issue by broofa** [parcel-bundler/parcel#6369]
# 🐛 bug report

Parcel dev server is serving the bundled JS file, but is not serving the corresponding source map file (like _"it's right there next to the .js file! How is it not finding it?!?"_).

Recipe:

In https://github.com/broofa/flightcard ...

1. Check out repo, `npm install`
2. `npm start` to run parcel dev server (or just `parcel index.html`)
3. Navigate to http://localhost:1234 in Google Chrome
4. Open Dev tools, "Source" tab.
5. Select index.#####.js file in file explorer on left side.  _Notice "Source map detected"_
6. "View Page Source" in separate tab
7. Click on index.####.js link to view the raw bundled JS.  _Notice it's the JS bundle content, as expected_
8. Scroll to bottom.  _Notice `sourceMappingURL=index.####.js.map` points to the same file, just with a ".map" extension (again, as expected)_
9. Add ".map" to the URL in the location field.

_**Notice: This should display the sourcemap content, but is instead rendering the website homepage (HTML)**_

I've seen other issues that discuss using the --dist-dir and --public-dir flags to force an explicit path 

**Possibly helpful screengrab...?**

![usestorage](https://user-images.githubusercontent.com/164050/119874620-84bee280-bec1-11eb-8d7e-4778f5f4f117.gif)

## 🎛 Configuration (.babelrc, package.json, cli command)

See https://www.github.com/broofa/flightcard

## 🤔 Expected Behavior

The default dev server configuration should be smart enough to know how to serve a `.js.map` file that is immediately adjacent to it's `.js` file in the file system. 

## 🌍 Your Environment

```

  System:
    OS: macOS 11.1
    CPU: (8) x64 Apple M1
    Memory: 778.61 MB / 16.00 GB
    Shell: 5.1.0 - /usr/local/bin/bash
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.77
    Firefox: 88.0.1
    Safari: 14.0.2
  npmPackages:
    @parcel/babel-plugin-transform-runtime: 2.0.0-nightly.1823 => 2.0.0-nightly.1823 
    @parcel/packager-raw-url: 2.0.0-beta.2 => 2.0.0-beta.2 
    @parcel/transformer-sass: 2.0.0-beta.2 => 2.0.0-beta.2 
    @parcel/transformer-svg-react: 2.0.0-beta.3.1 => 2.0.0-beta.3.1 
    @parcel/transformer-webmanifest: 2.0.0-beta.2 => 2.0.0-beta.2 
    @types/react-dom: 17.0.3 => 17.0.3 
    @types/react-router-dom: 5.1.7 => 5.1.7 
    @typescript-eslint/eslint-plugin: 4.20.0 => 4.20.0 
    @typescript-eslint/parser: 4.20.0 => 4.20.0 
    bootstrap: 5.0.1 => 5.0.1 
    checkcss: 1.0.2 => 1.0.2 
    eslint: 7.21.0 => 7.21.0 
    eslint-config-standard: 16.0.2 => 16.0.2 
    eslint-plugin-import: 2.22.1 => 2.22.1 
    eslint-plugin-node: 11.1.0 => 11.1.0 
    eslint-plugin-promise: 4.3.1 => 4.3.1 
    eslint-plugin-react: 7.22.0 => 7.22.0 
    eslint-plugin-react-hooks: 4.2.0 => 4.2.0 
    firebase: 8.4.2 => 8.4.2 
    firebaseui: 4.8.0 => 4.8.0 
    nanoid: 3.1.22 => 3.1.22 
    parcel: 2.0.0-beta.2 => 2.0.0-beta.2 
    react: ^16.13.1 => 16.14.0 
    react-bootstrap: 2.0.0-alpha.2 => 2.0.0-alpha.2 
    react-dom: ^16.13.1 => 16.14.0 
    react-router-bootstrap: 0.25.0 => 0.25.0 
    react-router-dom: 5.2.0 => 5.2.0 
    sass: 1.32.12 => 1.32.12 
    simplur: 3.0.0 => 3.0.0 
    typescript: 4.2.3 => 4.2.3 
```

**Comment by mischnic** [comment]
>    @parcel/babel-plugin-transform-runtime: 2.0.0-nightly.1823 => 2.0.0-nightly.1823 
>    @parcel/packager-raw-url: 2.0.0-beta.2 => 2.0.0-beta.2 
>    @parcel/transformer-sass: 2.0.0-beta.2 => 2.0.0-beta.2 
>    @parcel/transformer-svg-react: 2.0.0-beta.3.1 => 2.0.0-beta.3.1 
>    @parcel/transformer-webmanifest: 2.0.0-beta.2 => 2.0.0-beta.2 
>    parcel: 2.0.0-beta.2 => 2.0.0-beta.2 

Please upgrade to the latest beta or the latest nightly. This problem is already fixed and using differing version for the individual packages can cause problems in itself

**Comment by broofa** [comment]
Sweet!

FWIW, I actually tried upgrading to beta previously, but ended up piecemeal upgrading the various @parcel/xxx packages, which led to scary errors of various sorts.  I just tried upgrading again, but installed all parcel dependencies "`@next`" across the board, and it's working nicely now.

Sorry for the bother!
