### ISSUE TITLE
2.0.0-beta.3.1 shows as outdated

### ISSUE THREAD

**Issue by jtojnar** [parcel-bundler/parcel#6376]
# 🐛 bug report

I installed `parcel@next` but when I run `npm outdated`, it wants to install nightly or even older beta.

## 🎛 Configuration (.babelrc, package.json, cli command)

Installing `parcel@next` and running parcel resulted in the following `devDependencies` in `package.json`:

```
    "@parcel/packager-raw-url": "^2.0.0-beta.3.1",
    "@parcel/transformer-sass": "^2.0.0-beta.3.1",
    "@parcel/transformer-webmanifest": "^2.0.0-beta.3.1",
    "parcel": "^2.0.0-beta.3.",
```

I also have `"parcel-config-precache-manifest": "^0.0.4",` but looking at its [`package.json`](https://github.com/101arrowz/precache-manifest/blob/2b5360a72debfdf709633e781b366eb79b01540f/packages/parcel-config-precache-manifest/package.json#L39-L41), it just has parcel as a peer dependency and removing the package does not help either.

## 🤔 Expected Behavior

It should be considered up to date.

## 😯 Current Behavior

When I run `npm update`, it wants to install nightly or even older beta. See also the output of `npm outdated`:

```
Package                                 Current              Wanted              Latest  Location                                      Depended by
@parcel/packager-raw-url         2.0.0-beta.3.1  2.0.0-nightly.1849  2.0.0-nightly.1849  node_modules/@parcel/packager-raw-url         assets
@parcel/transformer-sass         2.0.0-beta.3.1   2.0.0-nightly.690       2.0.0-alpha.3  node_modules/@parcel/transformer-sass         assets
@parcel/transformer-webmanifest  2.0.0-beta.3.1  2.0.0-nightly.2186  2.0.0-nightly.2186  node_modules/@parcel/transformer-webmanifest  assets
parcel                           2.0.0-beta.3.1   2.0.0-nightly.688        2.0.0-beta.2  node_modules/parcel                           assets
```

## 🔦 Context

Tried deleting `package-lock.json` and `node_modules` in case there is something cached (previously, I used parcel nightly) but still the same result.

I want to use parcel beta now.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |16.2.0
| npm         |7.13.0
| Operating System |NixOS

**Comment by mischnic** [comment]
Specifying `2.0.0-beta.3.1` instead of `^2.0.0-beta.3.1` works better here. semver unfortunately behaves very counterintuitively regarding prerelease versions

**Comment by jtojnar** [comment]
Is it possible to make `npm install -D parcel@next` use exactly the latest version? Or do you just manually change the constraints for all parcel dependencies in `package.json`?

**Comment by mischnic** [comment]
`npm install -DE parcel`

**Comment by jtojnar** [comment]
Hmm, that installs `2.0.0-nightly.688`. But `npm install -DE parcel@next` seems to work great. Same for other parcel packages. Thanks.

`npm outdated` still complains that the packages are outdated:

```
@parcel/packager-raw-url         2.0.0-beta.3.1  2.0.0-beta.3.1  2.0.0-nightly.1849  node_modules/@parcel/packager-raw-url         assets
@parcel/transformer-sass         2.0.0-beta.3.1  2.0.0-beta.3.1       2.0.0-alpha.3  node_modules/@parcel/transformer-sass         assets
@parcel/transformer-webmanifest  2.0.0-beta.3.1  2.0.0-beta.3.1  2.0.0-nightly.2186  node_modules/@parcel/transformer-webmanifest  assets
parcel                           2.0.0-beta.3.1  2.0.0-beta.3.1        2.0.0-beta.2  node_modules/parcel                           assets
```

Even though `parcel@^2.0.0-beta.3.1` should definitely not match `2.0.0-beta.2` or be older than it.

**Comment by mischnic** [comment]
There's nothing we can do about that npm behaviour

**Comment by jtojnar** [comment]
Looking at [`parcel` package on npm](https://www.npmjs.com/package/parcel), the `latest` tag seems to be stuck at `2.0.0-beta.2`, though. That might be confusing `npm outdated`.
