### ISSUE TITLE
parcel with preact: hot module reloading *appends* new html instead of replacing it.

### ISSUE THREAD

**Issue by urbanhop** [parcel-bundler/parcel#638]
using parcel with preact: 
when i edit a js file, hot module reloading *appends* the newly rendered html instead of replacing it.

how can i avoid that?
thx

**Comment by hobbes7878** [comment]
That's part of preact. See the note on `render`: https://preactjs.com/guide/differences-to-react#what-s-different-

To avoid, you can add a third argument to render like this:
```jsx
const node = document.body;

render(<SomeApp />, node, node.lastChild);
```

**Comment by urbanhop** [comment]
@hobbes7878 thank you for the heads up and the link. very helpful.

parcel is out here, closing it.

**Comment by jsdev17** [comment]
I found this answer after a single Google search. this makes me happy.
