### ISSUE TITLE
Log file name contains colons (which is illegal on Windows)

### ISSUE THREAD

**Issue by rjungbeck** [parcel-bundler/parcel#6381]
| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4  |
| Node             | 14.17.0  |
| npm/Yarn         | yarn |
| Operating System | Windows 10 |

When you specify --log-level 5 parcel tries to create a file like parcel-debug-2021-06-01T09:10:30.423Z.log

**Comment by DeMoorJasper** [comment]
We're no longer updating Parcel 1 as we're very close to a release candidate for Parcel 2
