### ISSUE TITLE
Treeshaking an web application importing BabylonJS fails

### ISSUE THREAD

**Issue by rjungbeck** [parcel-bundler/parcel#6382]
| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.4 |
| Node             | 14.17.0 |
| npm/Yarn         | yarn |
| Operating System | Windows 10 |

Treeshaking the app produces 

    'import' and 'export' may appear only with 'sourceType: "module"' (1:0)

during build.

Building the same app without treeshaking suceeds.

**Comment by mischnic** [comment]
You should definitely be using Parcel 2 if you want tree shaking/scope hoisting
