### ISSUE TITLE
The webextension build described in the doc doesn't work (`Invalid Parcel Config` )

### ISSUE THREAD

**Issue by eai04191** [parcel-bundler/parcel#6384]
Probably a duplicate of #6179, But it will post because it is also currently occurring.

# 🐛 bug report

Even if I set up the webextension as described in the [document](https://v2.parceljs.org/recipes/web-extension/), it does not start.

### .parcelrc

```json
{
    "extends": "@parcel/config-webextension"
}
```

### package.json

copied from https://v2.parceljs.org/recipes/web-extension/
```
{
    "name": "test",
    "version": "1.0.0",
    "main": "index.js",
    "license": "MIT",
    "devDependencies": {
        "@parcel/config-webextension": "^2.0.0-nightly.2151",
        "parcel": "^2.0.0-beta.3.1"
    },
    "targets": {
        "webext-dev": {
            "sourceMap": {
                "inline": true,
                "inlineSources": true
            }
        },
        "webext-prod": {}
    },
    "scripts": {
        "start": "parcel src/manifest.json --host localhost --target webext-dev",
        "build": "parcel build src/manifest.json --target webext-prod"
    }
}
```

### src/manifest.json

Probably not yet reached the stage read this.
```json
{
    "name": "test",
    "version": "0.0.0",
    "manifest_version": 2
}
```

### command

```bash
yarn start
```

## 🤔 Expected Behavior

webext is built.

## 😯 Current Behavior

An unknown error occurs.

```
yarn run v1.22.10
$ parcel src/manifest.json --host localhost --target webext-dev
@parcel/core: Invalid Parcel Config
node_modules\@parcel\config-webextension\node_modules\@parcel\config-default\index.json:96:14
   95 |   ],
>  96 |   "runtimes": {
>     |               ^
>  97 |     "browser": [
>     | ^^^^^^^^^^^^^^^^
>  98 |       "@parcel/runtime-js",
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  99 |       "@parcel/runtime-browser-hmr",
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 100 |       "@parcel/runtime-react-refresh"
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 101 |     ],
>     | ^^^^^^
> 102 |     "service-worker": [
>     | ^^^^^^^^^^^^^^^^^^^^^^^
> 103 |       "@parcel/runtime-js"
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 104 |     ],
>     | ^^^^^^
> 105 |     "web-worker": [
>     | ^^^^^^^^^^^^^^^^^^^
> 106 |       "@parcel/runtime-js"
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## 🌍 Your Environment

I tried it on windows and mac and the result was exactly the same.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.3.1 |
| Node             | v14.16.1 |
| npm/Yarn         | yarn 1.22.10 |
| Operating System | Windows 10 |

**Comment by mischnic** [comment]
>         "@parcel/config-webextension": "^2.0.0-nightly.2151",
>         "parcel": "^2.0.0-beta.3.1"

You need to make sure that all Parcel packages have the same version (or refer to the same time in case of nightly builds). So try with `"@parcel/config-webextension": "2.0.0-beta.3.1"`

**Comment by eai04191** [comment]
@mischnic Thanks, Certainly it worked when I installed `@parcel/config-webextension@next`. I apologize for my mistake.

**Comment by AntonOfTheWoods** [comment]
@mischnic , this is pretty confusing, and doesn't work for some plugins, like `service-worker` (which doesn't have a `2.0.0-rc.0`. If you just naively install without versions you get something incompatible:

```yarn add parcel @parcel/config-webextension```

If instructions like the above (i.e, must have the same version) were on the home page of the v2 docs, that would be a little clearer, at least until v2 is released. What do you think?
