### ISSUE TITLE
Support regex in alias

### ISSUE THREAD

**Issue by azzamsa** [parcel-bundler/parcel#6391]
# 🙋 feature request

Will Parcel support regex in alias?

## 🤔 Expected Behavior

Having the project structure such this:

```text
❯ tree
.
├── main.js
├── modules
│   └── lazyload
│       └── index.js
└── utilities
    ├── filters.js
    ├── helpers
    │   └── index.js
    ├── selectors
    │   └── index.js
    └── utils.js

5 directories, 6 files
```

Parcel should be able to use regex in import alias, such:

```js
alias: {
    '@modules': './src/scripts/modules',
    '@utilities': './src/scripts/utilities',
  },
```

## 😯 Current Behavior

Currently, we have to specify **explicitly** each alias:

```js
"alias": {
    "@modules/lazyload": "./src/scripts/modules/lazyload/index.js",
    "@utilities/selectors": "./src/scripts/utilities/selectors/index.js",
    "@utilities/helpers": "./src/scripts/utilities/helpers/index.js"
  },
```
  
## 💁 Possible Solution

How other bundler approaches the problem.
In other Bundler, I just need to specify **part** of alias (only top-level modules) :

Webpack:

```js
  alias: {
        "@utilities": path.resolve(__dirname, "src/site/includes/js/utilities"),
        "@modules": path.resolve(__dirname, "src/site/includes/js/modules"),
      },
```
      
Snowpack:

```js
alias: {
    '@modules': './src/scripts/modules',
    '@utilities': './src/scripts/utilities',
  },
```

esbuild:

```js
// Redirect all paths starting with "@modules/" to "src/scripts/modules"
    build.onResolve({ filter: /^@modules\// }, (args) => {
      // get such `@modules/mobile-nav` without the `@module` part
      let moduleName = args.path.split("/")[1]
      return { path: path.resolve("src/scripts/modules", moduleName, "index.js") }
    })

    build.onResolve({ filter: /^@utilities\// }, (args) => {
      let moduleName = args.path.split("/")[1]
      return { path: path.resolve("src/scripts/utilities", moduleName, "index.js") }
    })
```
    

## 🔦 Context

Imagine having more than 10 import to the different directory with the alias. In Parcel we need to specify explicitly 10 alias in `package.json` to **concrete file** instead of using regex.

```
"parcel": "^2.0.0-beta.3.1",
```

Related: https://github.com/parcel-bundler/parcel/discussions/6390

**Comment by mischnic** [comment]
I think something like

```
  alias: {
    '@modules/*': './src/scripts/modules/$1'
  },
```

should already be working, but I like the other version without the globs more.

**Comment by azzamsa** [comment]
Wow, it works!

```diff
   "alias": {
-    "@modules/lazyload": "./src/scripts/modules/lazyload/index.js",
-    "@utilities/selectors": "./src/scripts/utilities/selectors/index.js",
-    "@utilities/helpers": "./src/scripts/utilities/helpers/index.js"
+    "@modules/*": "./src/scripts/modules/$1",
+    "@utilities/*": "./src/scripts/utilities/$1"
```

I never know such feature. It doesn't mentioned in [alias doc](https://github.com/parcel-bundler/parcel#aliases)

**Comment by mischnic** [comment]
We also don't have any tests for it 😬

**Comment by azzamsa** [comment]
Should we add that feature in the docs?
Or do you plan to add another approach to this issue?

**Comment by mischnic** [comment]
We should probably add that to the docs. 

I still think we should support `'@modules': './src/scripts/modules'` for cross-compatibility reasons. Aliasing a folder to another folder should already work and this is just that one special case of mapping the org part of a package name.

**Comment by mrskiro** [comment]
It's not working...🤔
Can someone please tell me what the solution is?

```
 alias: {
    '~/*': './src/$1'
}
```

**Comment by DeMoorJasper** [comment]
@purp1eeeee using `~/` might be the issue as that is already handled by parcel itself, probably better to use something like `@/` instead

**Comment by mrskiro** [comment]
wow its working!!!
thunk you!

**Comment by devongovett** [comment]
This is now documented here: https://v2.parceljs.org/features/dependency-resolution/#glob-aliases
