### ISSUE TITLE
Parcel 2 does not preserve surroundings of @import in style tags.

### ISSUE THREAD

**Issue by adamierymenko** [parcel-bundler/parcel#6395]
# 🐛 bug report

I want to import two CSS files and have them inlined into HTML. This works fine like:

```
<style>
@import "./light.css";
@import "./dark.css";
</style>
```

However I want to surround dark.css with a media query like:

```
<style>
@import "./light.css";
@media (prefers-color-scheme: dark) {
  @import "./dark.css";
}
</style>
```

The `@media` enclosure is not present in the output. It just inlines both CSS files as before.

## 🤔 Expected Behavior

The contents of dark.css should be surrounded by a media selector.

## 😯 Current Behavior

The `@media` line is not present in the output.

## 💁 Possible Solution

I wrote a shell script that pre-processes the second file by adding `@media` to it.

**Comment by mischnic** [comment]
```
@import "./light.css";
@media (prefers-color-scheme: dark) {
  @import "./dark.css";
}
```
is not valid css. If you try this in a browser without running Parcel, `dark.css` is never requested (even when in dark mode).

**Comment by jdowens-commit** [comment]
Code of Conduct information is enforced.  Petitioned by father so law enforcement agencies to be a informed. Of petitioner rights moved negatives
