### ISSUE TITLE
No transformation for .eot found

### ISSUE THREAD

**Issue by puka-tchou** [parcel-bundler/parcel#6398]
# 🐛 bug report

## 🎛 Configuration (cli command)

Command line :

```
"parcel": "parcel build 'resources/systematik/{scripts,scss,img,fonts,favicon}/**/*.{scss,js,jpg,png,svg,eot,ttf,woff,woff2}' --dist-dir public/application/themes/systematik",
```
no `.babelrc`.

## 🤔 Expected Behavior

Parcel should copy the fonts without applying a transformation.

## 😯 Current Behavior

```
🚨 Build failed.
Error: No transformers found for /shared/httpd/base-concrete5/resources/systematik/fonts/icomoon.eot.
Error: No transformers found for /shared/httpd/base-concrete5/resources/systematik/fonts/icomoon.eot.
    at ParcelConfig._getTransformerNodes (/shared/httpd/base-concrete5/node_modules/@parcel/core/lib/ParcelConfig.js:185:13)
    at ParcelConfig.getTransformers (/shared/httpd/base-concrete5/node_modules/@parcel/core/lib/ParcelConfig.js:198:34)
    at Transformation.loadPipeline (/shared/httpd/base-concrete5/node_modules/@parcel/core/lib/Transformation.js:667:48)
    at Transformation.run (/shared/httpd/base-concrete5/node_modules/@parcel/core/lib/Transformation.js:325:31)
    at async Child.handleRequest (/shared/httpd/base-concrete5/node_modules/@parcel/workers/lib/child.js:255:9)
```

## 💁 Possible Solution

Skip transformations for unknown extensions?

## 🔦 Context

I'm trying to use Parcel to bundle all the files required for my website and so far the fonts are giving me a headache. I just want them to be copied to the destination.

## 💻 Code Sample

Try to process a `.eot` file, I can't easily provide a sample but it should be pretty straightforward I guess.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.688+8c0721e5 |
| Node             | v15.4.0 |
| npm         | 7.0.15 |
| Operating System | Ubuntu 20.04 LTS |

**Comment by devongovett** [comment]
Usually fonts wouldn't be an entry specified on the command line but rather referenced via another file (eg CSS).

**Comment by puka-tchou** [comment]
So you wouldn't recommend directly trying to process font files (or any non-JS or CSS files for that matter) but rather referencing to it from supported files?

**Comment by mischnic** [comment]
Correct, for example in this case, the url inside `@font-face` should be picked up automatically.
