### ISSUE TITLE
linting on build?

### ISSUE THREAD

**Issue by sarahbethfederman** [parcel-bundler/parcel#64]
Is there any functionality like eslint-loader for webpack? Plans for it? Currently I only see linting errors if I explicitly run an eslint command

**Comment by thejameskyle** [comment]
I guess that depends on how generic of a tool we want to make Parcel.

It's interesting because you could reuse the same logic for caching to decide which files to run tools like linters on.

Eventually I hope to see an extensible plugin system so if that happens people can do whatever they want.

**Comment by devongovett** [comment]
Seems to me like this might be better served by an in-editor tool, or a pre-test command, but happy to discuss.

**Comment by sarahbethfederman** [comment]
I think I agree. I am porting from webpack and I think I'll just add husky and a precommit command. Was just curious if I was doing something wrong since it was reading my other configs and that's why I wasn't getting it :)

**Comment by davidnagli** [comment]
I feel like it would be really awesome if we developers could have a tool that automatically lints, tests, transpiles, bundles and minifies code without any additional configuration. 

I get that this is might be outside the scope of a traditional bundler, but how awesome would it be if you could just type in the CLI command, and it would run this whole process on watch for you. 

This really depends on what you guys envision for Parcel, but I think the best place to implement such a tool is on the bundler level, and Parcel is ideal for this.

**Comment by lc60005457** [comment]
This is my attempt.
https://github.com/lc60005457/parcel-plugin-eslint

**Comment by brandon93s** [comment]
> Seems to me like this might be better served by an in-editor tool, or a pre-test command, but happy to discuss.

+1 - Forcing linting by default may be _too_ opinionated. People trying out `parcel` shouldn't be blocked by linting suggestions imposed by the bundler. I guess it could detect the presence of an eslint file and only run then? May be best suited as a plugin.

**Comment by devongovett** [comment]
Closing this. We won't support this out of the box in core. The best options are to lint on pre-commit or pre-test, or write a parcel plugin.
