### ISSUE TITLE
Parcel V2 not parsing image URLs in data-src for lazy-loading purposes?

### ISSUE THREAD

**Issue by moritzlaube** [parcel-bundler/parcel#6400]
# 🙋 feature request

I am trying to lazy load images with `lozad.js`. For that I have to put the image URL into the `data-src` attribute. Yet, Parcel isn't parsing those dependencies. Only when the `src` attribute is used, Parcel finds the images.
 
I saw a few discussions on this topic and also a few plugins. But they all solved the problem for V1. Is there a solution for V2 already? 

Thanks for your help!

**Comment by mischnic** [comment]
This should be third part plugin -> https://github.com/parcel-bundler/parcel/discussions/6405
