### ISSUE TITLE
native.js missing in transformer-js

### ISSUE THREAD

**Issue by fellmann** [parcel-bundler/parcel#6406]
# 🐛 bug report

Using the latest Parcel V2, native.js is missing in transformer.js

## 🎛 Configuration (.babelrc, package.json, cli command)

.parcelrc:
```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
}
```

## 🤔 Expected Behavior

It should compile.

## 😯 Current Behavior

```ℹ Server running at http://localhost:3000
× Build failed.
@parcel/transformer-js: Could not resolve module "xxxx\node_modules\@parcel\transformer-js\native" from "xxxx\node_modules\@parcel\transformer-js\lib\JSTransformer.js"```
```

## 💁 Possible Solution

Compiling works after manually copying native.js from https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/js/native.js to `xxxx\node_modules\@parcel\transformer-js\native.js`

## 🔦 Context

This bug occurs after updating an existing project to Parcel v2 Beta 3.1, yarn.lock, node_modules and parcel cache was cleared.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel   |     2.0.0-beta.3.1   |
| Node    |     v14.17.0  |
| npm/Yarn |    yarn 1.22.4    |
| Operating System  | Win 10 64Bit|

**Comment by mischnic** [comment]
This is indeed missing in the latest nightly. (Which means that you aren't actually using beta.3.1 and `^2.0.0-beta.3.1` probably makes Yarn install the nightly)

**Comment by fellmann** [comment]
@mischnic Interesting point. You are right, after the first install of parcel Beta 3.1 everything works.

But the wrong behavior of yarn is reproducible:

1. `yarn add -D parcel@next`
  Result: Added `"parcel": "^2.0.0-beta.3.1"` to package.json, all dependencies like transformer-js use beta.3.1 too. Everything works.
2. Delete `yarn.lock`
3. Run yarn
  Result: Parcel nightly is used, and all dependencies are nightly versions.
  
Is this the expected behavior? Probably yes.

```

parcel@^2.0.0-beta.3.1:
  version "2.0.0-nightly.704"
  resolved "https://registry.yarnpkg.com/parcel/-/parcel-2.0.0-nightly.704.tgz#f47589707c8404403d2c07c6d12e6b7f23d57a82"
  integrity sha512-QvVYYjtzjC1XS+7LkbpBxWscUsS8gHUJ8JFlUeE7FVKer3+PhmMNh59dopNu0Klw5V3GzXJ9w7YSU/IgnhF25w==
  dependencies:
    "@parcel/config-default" "2.0.0-nightly.706+760fc61c"
    "@parcel/core" "2.0.0-nightly.704+760fc61c"
    "@parcel/diagnostic" "2.0.0-nightly.706+760fc61c"
    "@parcel/events" "2.0.0-nightly.706+760fc61c"
    "@parcel/fs" "2.0.0-nightly.706+760fc61c"
    "@parcel/logger" "2.0.0-nightly.706+760fc61c"
    "@parcel/package-manager" "2.0.0-nightly.706+760fc61c"
    "@parcel/reporter-cli" "2.0.0-nightly.706+760fc61c"
    "@parcel/reporter-dev-server" "2.0.0-nightly.706+760fc61c"
    "@parcel/utils" "2.0.0-nightly.706+760fc61c"
    chalk "^4.1.0"
    commander "^7.0.0"
    get-port "^4.2.0"
    v8-compile-cache "^2.0.0"
    ```

**Comment by mischnic** [comment]
It's not wrong, it's just that semver doesn't really work as we would expect here: https://jubianchi.github.io/semver-check/#/^2.0.0-beta.3.1/2.0.0-nightly.555

So you need to do `yarn add -DE parcel@next` to get `"parcel": "2.0.0-beta.3.1"` to pin the beta
