### ISSUE TITLE
parcel crashes looking for SourceMapPackager

### ISSUE THREAD

**Issue by dotdash** [parcel-bundler/parcel#642]
### 🎛 Configuration (.babelrc, package.json, cli command)
```js
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
```

### 🤔 Expected Behavior

After installing parcel with `npm install -g parcel-bundler` parcel should not crash

### 😯 Current Behavior

parcel crashes

```
(node:29744) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module './SourceMapPackager'
```
### 🌍 Your Environment

Up-to-date Debian Sid installation with a freshly installed parcel.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.5.0 |
| Node             | 6.12.0 |
| npm         | 4.3.0 |
| Operating System | Debian Sid |

**Comment by vanam** [comment]
The same happened to me when following [Getting Started](https://parceljs.org/getting_started.html)

| Software | Version |
| --- | --- |
| Parcel | 1.5.0 |
| Node | 6.12.3 |
| npm | 5.6.0 |
| OS | Ubuntu 16.04.3 LTS |

**Comment by DeMoorJasper** [comment]
This is because Node 6 is not supported, Parcel currently only works with Node 8+ We are working to support Node 6 and 7 as well

**Comment by vanam** [comment]
You are right. After update it works.
