### ISSUE TITLE
no arrow functions transform

### ISSUE THREAD

**Issue by wendt88** [parcel-bundler/parcel#6423]
trying a simple bootstrap 5 project doe not work on IE 11

- [`browserlistrc` recommended from bootstrap](https://getbootstrap.com/docs/5.0/getting-started/browsers-devices/)
- simple `html` fith `js`: `import 'bootstrap';` included twice also with two builds (`<script type="module">` and `<script nomodule>`)
- error on `IE 11`: `Syntaxerror` (`let assets = data.assets.filter(asset => asset.envHash === HMR_ENV_HASH)`)

as [default babel settings](https://v2.parceljs.org/languages/babel/#extending-the-default-babel-config) gets used `@babel/preset-env`, so [`@babel/plugin-transform-arrow-functions`](https://babeljs.io/docs/en/babel-plugin-transform-arrow-functions) should be used too.

How can I define different babel settings for different builds (module and nomodule) for modern and legacy builds?

**Comment by shulcsm** [comment]
That bootstrap page explocitly states it does not support IE

**Comment by shulcsm** [comment]
That bootstrap page explicitly states it does not support IE

**Comment by mischnic** [comment]
What Parcel version are you using? (As asked in the issue template)

**Comment by wendt88** [comment]
sorry, somehow i did not get a template (maybe because of the login redirects)
I used `2.0.0-beta.3.1`, than I tried to upgrade to `2.0.0-nightly.711` but on that version both scripts are equal (`type="module"` and `nomodule` include the same file)

@shulcsm thx, did not realize that IE 11 is not supported, but in a legacy/nomodule js (transpiled with `@babel/preset-env`) arrow functions should be transpiled anyway

**Comment by mischnic** [comment]
> browserlistrc recommended from bootstrap

That config doesn't include IE11, which is why the code isn't transpiled to be compatible with IE11 (since the browserslist config says that it's not needed)

(Files in `node_modules` aren't transpiled).
