### ISSUE TITLE
dev tool working but not build

### ISSUE THREAD

**Issue by AlexisPister** [parcel-bundler/parcel#6425]
# 🐛 bug report

parcel dev works fine in my application, but parcel build gives me the following error :

```
🚨  /home/alexis/Projects/VisualQueries/VisualQueries/node_modules/jquery-ui-dist/jquery-ui.theme.css:undefined:undefined: plugin is not a function
    at LazyResult.run (/usr/local/lib/node_modules/parcel-bundler/node_modules/postcss/lib/lazy-result.js:288:14)
    at LazyResult.asyncTick (/usr/local/lib/node_modules/parcel-bundler/node_modules/postcss/lib/lazy-result.js:212:26)
    at /usr/local/lib/node_modules/parcel-bundler/node_modules/postcss/lib/lazy-result.js:254:14
    at new Promise (<anonymous>)
    at LazyResult.async (/usr/local/lib/node_modules/parcel-bundler/node_modules/postcss/lib/lazy-result.js:250:23)
    at LazyResult.then (/usr/local/lib/node_modules/parcel-bundler/node_modules/postcss/lib/lazy-result.js:131:17)
npm ERR! code 1
npm ERR! path /home/alexis/Projects/VisualQueries/VisualQueries
npm ERR! command failed
npm ERR! command sh -c parcel build src/index.html

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alexis/.npm/_logs/2021-06-08T09_37_51_646Z-debug.log
```

I think it has something to do with the minification process of the css. If I build with "parcel build src/index.html --no-minify" it works.

## 🎛 Configuration (.babelrc, package.json, cli command)

My package.json file :

```js
{
  "name": "visualqueries",
  "version": "1.0.0",
  "description": "Social network dynamic query system",
  "main": "src/index.html",
  "scripts": {
    "test": "cypress open",
    "dev": "parcel src/index.html",
    "build": "parcel build src/index.html",
    "update": "npm update git+ssh://git@gitlab.inria.fr/fekete/cypher-compiler-js.git; npm i git+ssh://git@gitlab.inria.fr/fekete/cypher-compiler-js.git"
  },
  "author": "Alexis Pister",
  "license": "ISC",
  "dependencies": {
    "canvas-lasso": "^1.0.0",
    "codemirror": "^5.61.0",
    "cypher-compiler-js": "git+ssh://git@gitlab.inria.fr/fekete/cypher-compiler-js.git",
    "d3": "^6.7.0",
    "d3-drag": "^2.0.0",
    "d3-selection": "^2.0.0",
    "datatables.net": "^1.10.24",
    "datatables.net-buttons": "^1.7.0",
    "datatables.net-buttons-dt": "^1.7.0",
    "datatables.net-buttons-se": "^1.7.0",
    "datatables.net-dt": "^1.10.24",
    "datatables.net-jqui": "^1.10.24",
    "datatables.net-se": "^1.10.24",
    "es6-promise": "^4.2.8",
    "flatted": "^3.1.1",
    "fomantic-ui": "^2.8.7",
    "jquery": "^3.6.0",
    "jquery-ui": "^1.12.1",
    "jquery-ui-bundle": "^1.12.1-migrate",
    "jquery-ui-dist": "^1.12.1",
    "jszip": "^3.6.0",
    "lasso-canvas-image": "^1.4.2",
    "leaflet": "^1.7.1",
    "pdfmake": "^0.1.71",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "regenerator-runtime": "^0.13.7",
    "sortablejs": "^1.13.0",
    "stream": "^0.0.2",
    "update": "^0.7.4",
    "webcola": "^3.4.0"
  },
  "devDependencies": {
    "@visdesignlab/trrack": "^2.0.0-alpha.10",
    "@visdesignlab/trrack-vis": "^2.0.0-alpha.12",
    "chance": "^1.1.7"
  }
}

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.12.5
| Node             |14.15.4
| npm/Yarn         |7.5.2
| Operating System |Ubuntu 20.04

**Comment by AlexisPister** [comment]
I updated to Parcel@next now and I have the following error :

Build failed.
@parcel/core: Failed to resolve '@visdesignlab/trrack' from './src/js/visualQueryComponents/ProvenanceManager.js'
/home/alexis/Projects/VisualQueries/VisualQueries/src/js/visualQueryComponents/ProvenanceManager.js:3:8
  2 |   initProvenance, Provenance, NodeID, createAction,
> 3 | } from '@visdesignlab/trrack';
>   |        ^^^^^^^^^^^^^^^^^^^^^^
  4 | import { ProvVisCreator } from '@visdesignlab/trrack-vis';
  5 | import {parse, stringify} from 'flatted';
@parcel/resolver-default: Could not load './dist/trrack_dev.esm.js' from module '@visdesignlab/trrack' found in package.json#module
/home/alexis/Projects/VisualQueries/VisualQueries/node_modules/@visdesignlab/trrack/package.json:15:13
  14 |   "main": "dist/index.js",
> 15 |   "module": "dist/trrack_dev.esm.js",
>    |             ^^^^^^^^^^^^^^^^^^^^^^^^ './dist/trrack\_dev.esm.js' does not exist, did you mean './dist/trrack.esm.js'?'
  16 |   "typings": "dist/index.d.ts",
  17 |   "license": "MIT",


I really don't understand since it is working with the parcel src/index.html command.

**Comment by mischnic** [comment]
`parcel index.html` prefers `main` over `module` while `parcel build` prefers `module` over `main`. See https://github.com/parcel-bundler/parcel/issues/4879, we might change this though

**Comment by AlexisPister** [comment]
> `parcel index.html` prefers `main` over `module` while `parcel build` prefers `module` over `main`. See #4879, we might change this though

So I am supposed to specify both in the package.json ?

**Comment by AlexisPister** [comment]
I get the following error when removing the dependencies causing the previous error :

🚨 Build failed.
@parcel/transformer-js: Invalid argument, T on unrwap is not the type of wrapped object
Error: Invalid argument, T on unrwap is not the type of wrapped object
    at NodeSourceMap.extends (/home/alexis/node_modules/@parcel/source-map/dist/node.js:58:35)
    at Object.transform (/home/alexis/node_modules/@parcel/transformer-js/lib/JSTransformer.js:551:26)
    at async Transformation.runTransformer (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/Transformation.js:821:5)
    at async Transformation.runPipeline (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/Transformation.js:577:36)
    at async Transformation.runPipelines (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/Transformation.js:426:40)
    at async Transformation.run (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/Transformation.js:326:19)
    at async Child.handleRequest (/usr/local/lib/node_modules/parcel/node_modules/@parcel/workers/lib/child.js:255:9)
/home/alexis/Projects/VisualQueries/VisualQueries/node_modules/cypher-compiler-js/dist/index.js

**Comment by mischnic** [comment]
Parcel uses whichever of these fields are listed in `package.json`, the problem in your case is that the package `@visdesignlab/trrack` specifies a file as `module` in https://unpkg.com/browse/@visdesignlab/trrack@2.0.0-alpha.10/package.json which doesn't exist in https://unpkg.com/browse/@visdesignlab/trrack@2.0.0-alpha.10/dist/

---

Did you remove the parcel cache folder `.cache` and/or `.parcel-cache` when upgrading Parcel?

**Comment by AlexisPister** [comment]
I just removed both .cache folder and I get the same errors.

I see... The thing is I don't really have control on this dependency.

Would there be a way to use the dev tool using parcel src/index.html to get a build ? Because it works with this but the build tool brings me a lot of errors.

**Comment by mischnic** [comment]
A workaround would be `parcel build --no-scope-hoist`, but the output bundles will be larger

**Comment by AlexisPister** [comment]
I tried this command and I still get this error  :

🚨 Build failed.
@parcel/transformer-js: Invalid argument, T on unrwap is not the type of wrapped object
Error: Invalid argument, T on unrwap is not the type of wrapped object
    at NodeSourceMap.extends (/home/alexis/node_modules/@parcel/source-map/dist/node.js:58:35)
    at Object.transform (/home/alexis/node_modules/@parcel/transformer-js/lib/JSTransformer.js:551:26)
    at async Transformation.runTransformer (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/Transformation.js:821:5)
    at async Transformation.runPipeline (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/Transformation.js:577:36)
    at async Transformation.runPipelines (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/Transformation.js:426:40)
    at async Transformation.run (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/Transformation.js:326:19)
    at async Child.handleRequest (/usr/local/lib/node_modules/parcel/node_modules/@parcel/workers/lib/child.js:255:9)
/home/alexis/Projects/VisualQueries/VisualQueries/node_modules/cypher-compiler-js/dist/index.js

**Comment by mischnic** [comment]
Any chance you can share your code (or some subset that triggers this error) so that we can reproduce that error? I haven't seen that before

A workaround might be `--no-source-maps`

@DeMoorJasper

**Comment by AlexisPister** [comment]
Sure, I uploaded the code here :
https://github.com/AlexisPister/Vgq/tree/main/VisualQueries/VisualQueries

I get another error with --no-source-maps

🚨 Build failed.
@parcel/core: Failed to resolve '@visdesignlab/trrack' from './src/js/visualQueryComponents/ProvenanceManager.js'
/home/alexis/Projects/VisualQueries/VisualQueries/src/js/visualQueryComponents/ProvenanceManager.js:3:8
  2 |   initProvenance, Provenance, NodeID, createAction,
> 3 | } from '@visdesignlab/trrack';
>   |        ^^^^^^^^^^^^^^^^^^^^^^
  4 | import { ProvVisCreator } from '@visdesignlab/trrack-vis';
  5 | import {parse, stringify} from 'flatted';
@parcel/resolver-default: Could not load './dist/trrack_dev.esm.js' from module '@visdesignlab/trrack' found in package.json#module
/home/alexis/Projects/VisualQueries/VisualQueries/node_modules/@visdesignlab/trrack/package.json:15:13
  14 |   "main": "dist/index.js",
> 15 |   "module": "dist/trrack_dev.esm.js",
>    |             ^^^^^^^^^^^^^^^^^^^^^^^^ './dist/trrack\_dev.esm.js' does not exist, did you mean './dist/trrack.esm.js'?'
  16 |   "typings": "dist/index.d.ts",
  17 |   "license": "MIT",


Thanks for your help, I will go back with Parcel 1 in the meantime, I think it was working with the --no-minify flag

**Comment by AlexisPister** [comment]
I could build my app with Parcel 1 and the --no-minify flag, but when I open dist/index.html it does not work. Is there an extra step to do ?

**Comment by mischnic** [comment]
> Sure, I uploaded the code here :
> https://github.com/AlexisPister/Vgq/tree/main/VisualQueries/VisualQueries

Running `yarn build` in that folder doesn't work because the src folder is missing.

> I get another error with --no-source-maps

You'd need to specify both `--no-source-maps` and `--no-scope-hoist`

**Comment by AlexisPister** [comment]
Sorry it did not push right, I updated the repo with the src/ folder

Also I don't know if this help but I never used yarn in this project

**Comment by devongovett** [comment]
Preferring main over module was changed in #6470

**Comment by dioptre** [comment]
I had the opposite happen but the same fix worked for me:

```
yarn run v1.22.10
$ parcel serve index.html
Server running at http://localhost:1234
🚨 Build failed.@parcel/packager-css:   Error
  at new NodeSourceMap (/Users/x/src/x/x-site/node_modules/@parcel/source-map/dist/node.js:19:30)
  at NodeSourceMap.addBuffer (/Users/x/src/x/x-site/node_modules/@parcel/source-map/dist/node.js:51:23)
```

**Comment by jelleklaver** [comment]
This happened to me when running `parcel serve`. I had the exact same error when I upgrade from parcel 2-beta.1 to 2.0.0:

```
🚨 Build failed.
@parcel/transformer-js: Invalid argument, T on unrwap is not the type of wrapped object
...
```

After trying a few things I found that running `parcel build index.html` installed a few missing dependencies (namely `@parcel/transformer-inline-string` and `@parcel/transformer-sass`) which resolved this issue for me. Maybe this helps anyone.
