### ISSUE TITLE
[V2] axios xhr.js fails with cookies.read is not a function

### ISSUE THREAD

**Issue by tomsontom** [parcel-bundler/parcel#6428]
# 🐛 bug report

I'm try to move a CRA/Webpack application to parcel v2 but Axios fails with the following error

```
Failed to load TypeError: cookies.read is not a function
    dispatchXhrRequest xhr.js:110
    xhrAdapter index.f1aa576d.js:93571
    dispatchRequest dispatchRequest.js:52
    promise callback*request Axios.js:61
    method Axios.js:76
    wrap bind.js:9
....
```

## 🎛 Configuration (.babelrc, package.json, cli command)

Just a package.json with "parcel": "next"

## 🤔 Expected Behavior

works like it does in the original CRA/Webpack application

## 😯 Current Behavior

Fails in Axios code with

```
Failed to load TypeError: cookies.read is not a function
    dispatchXhrRequest xhr.js:110
    xhrAdapter index.f1aa576d.js:93571
    dispatchRequest dispatchRequest.js:52
    promise callback*request Axios.js:61
    method Axios.js:76
    wrap bind.js:9
....
```

Setting a break point shows this

<img width="900" alt="Bildschirmfoto 2021-06-08 um 19 06 45" src="https://user-images.githubusercontent.com/52631/121243205-be1e2780-c89d-11eb-8966-9bc6faa59d97.png">

This means axios does not expect to get back an Promise from the require-call the cookies object defined helpers/cookies.

## 🔦 Context

Impossible to fetch data

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | next
| Node             | 
| npm/Yarn         | yarn
| Operating System | OS-X

**Comment by tomsontom** [comment]
Not sure who is at fault:
* me because I did forget something
* axios because it expects the require does not return a promise
* parcel because it return a promise from the require call

**Comment by tomsontom** [comment]
So if I get that right the Promise is from "browsers/js-load.js" so I think parcel is at fault but I'm glad if you could prove me wrong.

**Comment by mischnic** [comment]
Can you provide a code sample?

The only thing regarding axios that I remember is https://github.com/parcel-bundler/parcel/issues/4056, but that seems like an unrelated problem

**Comment by tomsontom** [comment]
Sample application [my-app.zip](https://github.com/parcel-bundler/parcel/files/6626371/my-app.zip)

leads to this
<img width="1203" alt="Bildschirmfoto 2021-06-09 um 21 27 15" src="https://user-images.githubusercontent.com/52631/121416820-867cb180-c969-11eb-91a9-bd9f3e7af4d0.png">

**Comment by mischnic** [comment]
Reproduction:

```js
new Promise((res) => {
	let b = require("./b");

	console.log(b);
});
```
should print the namespace exports object of `b.js`, but instead `require` is treated as a dynamic import and it returns a promise.

**Comment by bologer** [comment]
@tomsontom were you able to find some solution to this problem? 
It seems you can set `xsrfCookieName: undefined` for now, to bypass cookie.read() call.

**Comment by tomsontom** [comment]
No I've put conversion on hold
