### ISSUE TITLE
Variable on window object

### ISSUE THREAD

**Issue by LukeTOBrien** [parcel-bundler/parcel#6431]
Might not be a bug I just don't know how to do it.

I am using `2.0.0-beta.2` and I have a `.terserrc`:
```js
{
    "mangle": false
}
```

I am setting a window variable `functions` from inside my TypeScript:
```ts
export module Functions {
    export var utils = UtilFunctions;
    export var capture = Capture;
}

window['functions'] = Functions;
```

When I run my app in the browser and type into the `F12` console I find that `functions` is undefined but I do have a variable called `$13946bde23b191cb1e948be2757ae4b1$export$Functions`.  
How do I set variables onto the `window` object?

> I have just today updated the project from Parcel 1 to version 2 - It worked okay on version 1

#### Additional

I have just noticed [this blog post about beta 3](https://v2.parceljs.org/blog/beta3/#10x-faster-javascript-compiler-written-in-rust-%F0%9F%9A%80), it seems you will be replacing/removing Terser?  
If this is so then how do I preserve function names in the new minifier?

## 🤔 Expected Behavior

`functions` variable appears on global `window` object.

## 😯 Current Behavior

`functions` is undefined.

## 🔦 Context

My app is using [Blazor JS Interop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-5.0#invoke-javascript-functions-and-read-a-returned-value-invokeasync) and I need the functions to be on the global `window` object so I can invoke them from .NET.  
So for eg I have a function that returns the `navigator.platform` and I can invoke it like so:
```csharp
await js.InvokeAsync<string>("functions.utils.getPlatform");
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.2
| Node             | 14.17

**Comment by mischnic** [comment]
I tried this and it worked fine:

```ts
const UtilFunctions = {
    add() {},
    sub() {},
};

function Capture() {}

export module Functions {
    export var utils = UtilFunctions;
    export var capture = Capture;
}

window["functions"] = Functions;
```

Also `mangle: false` isn't necessary, Terser makes sure that everything you can access retains its name.
