### ISSUE TITLE
Migration guide missing explanation for hooking into bundle/build events 

### ISSUE THREAD

**Issue by jsjoeio** [parcel-bundler/parcel#6432]
# 🐛 bug report

Related to documentation

## 🤔 Expected Behavior

The [Migration Guide](https://v2.parceljs.org/getting-started/migration/) and the [Parcel API docs](https://v2.parceljs.org/features/parcel-api/) should mention how to migrate to v2 with regard to hooking into bundle events i.e. `buildEnd`, `buildError`.

## 😯 Current Behavior

The migration don't mention anything leaving users to search GitHub Issues and Discussions and diving into codebase trying to find answers/examples. 

## 💁 Possible Solution

Based on [this comment](https://github.com/parcel-bundler/parcel/discussions/3377#discussioncomment-24536), I am guessing I could do something like:

```typescript
const parcel = new Parcel({ /* ... */ })
parcel.watch((err, buildEvent) => {
  if (err) throw err

  if(buildEvent === "buildEnd") {
     console.log("[parcel] bundled")
  }

  if(buildEvent === "buildError") {
    console.error("[parcel]", err)
  }
})
```

## 🔦 Context

I'm trying to migrate from v1 to v2. We use parcel to bundle a couple of files for the browser for [code-server](https://github.com/cdr/code-server) ([see code](https://github.com/cdr/code-server/blob/main/ci/dev/watch.ts#L175-L192)).

## 💻 Code Sample

Here is the code from v1. 
```typescript
// Simplified version
import Bundler from "parcel-bundler"

function createBundler(out = "dist"): Bundler {
    return new Bundler(
      [
        path.join(this.rootPath, "src/browser/register.ts"),
        path.join(this.rootPath, "src/browser/serviceWorker.ts"),
        path.join(this.rootPath, "src/browser/pages/login.ts"),
        path.join(this.rootPath, "src/browser/pages/vscode.ts"),
      ],
      {
        outDir: path.join(this.rootPath, out),
        cacheDir: path.join(this.rootPath, ".cache"),
        minify: !!process.env.MINIFY,
        logLevel: 1,
        publicUrl: ".",
      },
    )
  }

const bundler = createBundler()

const bundle = bundler.bundle().catch(() => {
  console.log("parcel watcher terminated unexpectedly")
})

bundler.on("buildEnd", () => {
  console.log("[parcel] bundled")
})

bundler.on("buildError", (error) => {
  console.error("[parcel]", error)
})
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.0-beta.3.1 | 
| Node             | v14.17.0 |
| npm/Yarn         | 1.22.10 |
| Operating System | macOS Big Sur 11.3 |

**Comment by mischnic** [comment]
> Based on this comment, I am guessing I could do something like:

Yes, did you run into a problem with that (apart from having to do `buildEvent.type === "..."` instead)? We could add that to the migration guide and https://v2.parceljs.org/features/parcel-api/

**Comment by jsjoeio** [comment]
> did you run into a problem with that (apart from having to do buildEvent.type === "..." instead)

I'm trying it out as we speak 🤞 But if that works, then that is fine for us!

Update: seems to work out perfectly! No issues.

> We could add that to the migration guide and https://v2.parceljs.org/features/parcel-api/

That would be awesome, and probably help others too! Do you want me to submit a PR?

**Comment by mischnic** [comment]
> Do you want me to submit a PR?

Sure!
