### ISSUE TITLE
Error: Bundles must have unique names

### ISSUE THREAD

**Issue by jsjoeio** [parcel-bundler/parcel#6433]
# 🐛 bug report

During the migration from v1 to v2, Parcel seems to be unhappy with my bundles and I'm not sure why (nor sure how to fix them). 

## 🎛 Configuration (.babelrc, package.json, cli command)

Not using a `.babelrc` file but heres' the code:

### v1

```sh
  parcel build \
    --public-url "." \
    --out-dir dist \
    $([[ $MINIFY ]] || echo --no-minify) \
    src/browser/register.ts \
    src/browser/serviceWorker.ts \
    src/browser/pages/login.ts \
    src/browser/pages/vscode.ts
```

### v2

```sh
  parcel build \
    --public-url "." \
    --dist-dir dist \
    $([[ $MINIFY ]] || echo --no-optimize) \
    src/browser/register.ts \
    src/browser/serviceWorker.ts \
    src/browser/pages/login.ts \
    src/browser/pages/vscode.t
```

## 🤔 Expected Behavior

Parcel 2 should bundle the files like Parcel 1 did (assuming the correct changes have been made).

## 😯 Current Behavior

Parcel is spitting out an error.

```javascript
🚨 Build failed.
Error: Bundles must have unique names
AssertionError [ERR_ASSERTION]: Bundles must have unique names
    at BundlerRunner.nameBundles (/Users/jp/Dev/code-server/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:482:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async BundlerRunner.bundle (/Users/jp/Dev/code-server/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:434:5)
    at async RequestTracker.runRequest (/Users/jp/Dev/code-server/node_modules/@parcel/core/lib/RequestTracker.js:694:20)
    at async Parcel._build (/Users/jp/Dev/code-server/node_modules/@parcel/core/lib/Parcel.js:661:25)
    at async Parcel.run (/Users/jp/Dev/code-server/node_modules/@parcel/core/lib/Parcel.js:510:18)
    at async run (/Users/jp/Dev/code-server/node_modules/parcel/lib/cli.js:367:7)
```

## 💁 Possible Solution

We thought it was because we had this line inside `register.ts`

```javascript
import "./pages/error.css"
import "./pages/global.css"
import "./pages/login.css"
```

Sadly removing that did not solve the issue. 

## 🔦 Context

We're trying to migrate from v1 to v2 because there are vulnerabilities in v1 and fixing them causing v1 to break so we're in a pickle 😅

## 💻 Code Sample

We use Parcel to bundle files for code-server (see [here](https://github.com/cdr/code-server/blob/main/ci/build/build-code-server.sh#L35-L42)).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.0-beta.3.1 | 
| Node             | v14.17.0 |
| npm/Yarn         | 1.22.10 |
| Operating System | macOS Big Sur 11.3 |

**Comment by mischnic** [comment]
Please tell me what commands I need to run after cloning your PR to reproduce this. I'm getting all sorts of errors when running `yarn build`

**Comment by jsjoeio** [comment]
I figured it might be easier to [record a Loom](https://www.loom.com/share/c96a982cd1ea41b3baf4a9dee6dfa75a) and show the error and explain some context too (though it is not captioned. if that doesn't work, happy to write out more context here).

> I'm getting all sorts of errors when running yarn build

Apologies about that. I don't want to have to ask you to work through various code-server issues to help us figure this out. 

If the Loom video doesn't work, I would be happy to try and isolate this in a small repo. Let me know!

**Comment by mischnic** [comment]
The reason I tried to reproduce it is that the error message doesn't really say which bundles are involved. So in that sense, a small repo would be great.

What you could also do is adding a console.log just before the failing assertion:
https://github.com/parcel-bundler/parcel/blob/1ba0bd1833d785c1acf6af36e0a1d429f1ce1fb6/packages/core/core/src/requests/BundleGraphRequest.js#L336
and retrieve the bundle names that way.

**Comment by jsjoeio** [comment]
> What you could also do is adding a console.log just before the failing assertion:

That helped! For some reason, it's giving the bundles the same name using a filename in another part of the codebase 🤔

![image](https://user-images.githubusercontent.com/3806031/121584151-0183ad80-c9e6-11eb-98f8-2535475cb118.png)
`/Users/jp/Dev/code-server/out/node/entry.js`

## Reproduction

In other good news, I was able to create a [small reproducible example](https://github.com/jsjoeio/parcel-v2-build-error).

1. `git clone https://github.com/jsjoeio/parcel-v2-build-error.git`
2. `yarn`
3. `yarn build`

**Comment by mischnic** [comment]
In case of your reproduction, the  problem was this
```diff
diff --git package.json package.json
index 7978540..ac50166 100644
--- package.json
+++ package.json
@@ -1,7 +1,6 @@
 {
   "name": "parcel-v2-build-error",
   "version": "1.0.0",
-  "main": "index.js",
   "license": "MIT",
   "scripts": {
     "build": "./build.sh"
```
The "main" field should only be set if you're building a library. And in this case all of the entry points passed to Parcel were assigned `index.js` as output.

Not sure if that is also causing your original problem though

**Comment by jsjoeio** [comment]
Ah, interesting! We set the "main" field because we publish `code-server` as an [npm package](https://www.npmjs.com/package/code-server).

But we have a build script that copies the `package.json` and makes some changes so we can work around this v2 change.
 
FWIW, Parcel v1 didn't care about the "main" field (or at least this way worked). (see [`parcel-v1` branch](https://github.com/jsjoeio/parcel-v2-build-error/tree/parcel-v1) in repro)

Thanks for helping us figure that out! Feel free to close this issue. 

Also happy to submit another PR to the migration guide on the website if that would be helpful.

**Comment by mischnic** [comment]
> FWIW, Parcel v1 didn't care about the "main" field

Correct

You can do this 
```js
{
  "main": "unrelated.js",
  "targets": {
    "main": false
  }
}
```
to make Parcel 2 ignore the main field:
https://v2.parceljs.org/configuration/package-json/#main-%2F-module-%2F-browser

**Comment by mischnic** [comment]
> Also happy to submit another PR to the migration guide on the website if that would be helpful.

Would a short note about `targets: {main: false}` in https://v2.parceljs.org/getting-started/migration/#package.json%23main have helped you?

**Comment by jsjoeio** [comment]
> > FWIW, Parcel v1 didn't care about the "main" field
> 
> Correct
> 
> You can do this 
> ```js
> {
>   "main": "unrelated.js",
>   "targets": {
>     "main": false
>   }
> }
> ```
> to make Parcel 2 ignore the main field:
> https://v2.parceljs.org/configuration/package-json/#main-%2F-module-%2F-browser

Oh wow, that's even easier! Thanks for the tip!

**Comment by jsjoeio** [comment]
> Would a short note about `targets: {main: false}` in https://v2.parceljs.org/getting-started/migration/#package.json%23main have helped you?

Definitely! That would have at least told me where our setup might break with V2.
