### ISSUE TITLE
swc + browserslist not transpiling ??=

### ISSUE THREAD

**Issue by nattthebear** [parcel-bundler/parcel#6440]
# 🐛 bug report

When browserslist includes `firefox esr`, `??=` is not transpiled.  The current Firefox ESR does not support this, and gives a syntax error.

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json` browserslist:

```json
  "browserslist": {
    "production": [
      "last 3 chrome version",
      "last 2 firefox version",
      "last 1 safari version",
      "firefox esr"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

build command:
```
parcel build ./public/index.html --public-url . --dist-dir build --reporter @parcel/reporter-bundle-analyzer --no-scope-hoist
```

## 🤔 Expected Behavior

`??=` should be transpiled as `"firefox esr"` does not support it.

## 😯 Current Behavior

`??=` is output raw and gives a syntax error.

## 💻 Code Sample

This is the full repo I experienced the issue in:

https://github.com/nattthebear/ff12characterplanner/tree/2de6fb1012123b4455d5acd8699d312dce72460b

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.3.1 |
| Node             | v14.16.0 |
| npm         | 6.14.11 |
| Operating System | Windows 10 |

**Comment by mischnic** [comment]
It seems to think that firefox >=72 supports nullish assignment.
