### ISSUE TITLE
Uppercase file extension match

### ISSUE THREAD

**Issue by Shaokun-X** [parcel-bundler/parcel#6441]
# 🙋 feature request
Be able to match uppercase file extension (or case insensitive)

## 🤔 Expected Behavior
For example if I have a `.jpg` file with **uppercase** extension:
```
<img src="url:./img/m1.JPG?as=webp" alt="image">
```
Parcel can still successfully match the file.

## 😯 Current Behavior

Parcel cannot match files with extensions that are not in lower case.

## 💁 Possible Solution

Maybe modify the `config-default`, makes the matching case insensitive.

## 🔦 Context

I worked with some images end with uppercase extension name, Parcel fails to convert them.

**Comment by mischnic** [comment]
Adding `nocase: true` here https://github.com/parcel-bundler/parcel/blob/1ba0bd1833d785c1acf6af36e0a1d429f1ce1fb6/packages/core/core/src/ParcelConfig.js#L332
should fix that.

**Comment by LironHazan** [comment]
@mischnic tiny PR --> https://github.com/parcel-bundler/parcel/pull/6513 🎉
