### ISSUE TITLE
Async react hooks do not run with Parcel 2

### ISSUE THREAD

**Issue by Himavanth** [parcel-bundler/parcel#6442]
# 🐛 bug report

Async function within react hook `useEffect` with an IIFE syntax is not executed in Parcel 2. It works fine in Parcel 1.
It also works fine if i make the function sync or call the function explicitly instead of using an IIFE.

## 🤔 Expected Behavior

Should see `running async func in useEffect hook` in browser console

## 😯 Current Behavior

Nothing in browser console

## 💁 Possible Solution

Change the async function to sync or get rid of IIFE syntax
## 💻 Code Sample

web-src/index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Async check</title>
</head>
<body>
  <div id="root"></div>
  <script src="./index.js" async="true"></script>
</body>
</html>
```
web-src/index.js
```
import 'regenerator-runtime/runtime'
import React, { useEffect } from "react"
import ReactDOM from 'react-dom'
import { Heading } from '@adobe/react-spectrum'

const App = () => {
  useEffect(() => {
    (async function namer () {
      console.log('running async func in useEffect hook')
      return
    })()
    // namer()
  }, [])
  return (
    <Heading level={1}>Welcome to repro-async-hook-ff!</Heading>
  )
}
ReactDOM.render( <App />, document.getElementById('root'))
```
package.json
```
{
  "name": "parcelissue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@adobe/react-spectrum": "^3.10.0",
    "parcel": "^2.0.0-beta.3.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-error-boundary": "^1.2.5",
    "react-router-dom": "^5.2.0",
    "regenerator-runtime": "^0.13.5",
    "uuid": "^8.3.2",
    "xml-js": "^1.6.11"
  }
}
```
issue.js
```
const ParcelCore = require("@parcel/core");
const path = require('path');
const { default: Parcel } = ParcelCore;
const getPort = require('get-port');

(async () => {
    let portToUse = await getPort({ port: 1234})
    console.log('portToUse: ' + portToUse)
    let parcelOptions = {
        entries: path.join(__dirname, "web-src/index.html"),
        defaultConfig: require.resolve('@parcel/config-default'),
        targets: {
          webassets: {
            distDir: path.join(__dirname, "dist/web-src-prod")
          }
        },
        additionalReporters : [
            { packageName: '@parcel/reporter-cli', resolveFrom: __filename },
        ],
        serveOptions: {
            port: portToUse,
            https: false
        },
    }
    console.log(parcelOptions)
    let parcel = new Parcel(parcelOptions);

    await parcel.watch(err => {
        console.log(err)
        if (err) throw err;
    });
})();
```
And run it with ...
**`node issue.js`**
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.3.1
| Node             | 12
| npm/Yarn         | 6
| Operating System | Mac

**Comment by mischnic** [comment]
Do you have a browserslist config?

It works correctly for me even when transpiling async, so with your two source files and
```json
{
  "scripts": {
    "build": "parcel build index.html"
  },
  "dependencies": {
    "@adobe/react-spectrum": "^3.10.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "browserslist": "chrome 40",
  "devDependencies": {
    "parcel": "2.0.0-beta.3.1"
  }
}
```

**Comment by Himavanth** [comment]
Thx for the quick reply @mischnic .
I just realised the code sample i pasted earlier is using the workaround of calling the function explicitly instead of using IIFE.
Changed the code sample to IIFE now. 
This actually works fine from CLI but the failure is when i use the API. I have added the API code as well to the code samples.
Could you check with the latest code ?

**Comment by mischnic** [comment]
This is already fixed in the nightly releases

https://github.com/parcel-bundler/parcel/pull/6325
https://github.com/swc-project/swc/issues/1722
