### ISSUE TITLE
Parcel dev server not working

### ISSUE THREAD

**Issue by pcpl2** [parcel-bundler/parcel#6443]
# 🐛 bug report

In the released parcel 2.0.0-nightly.646 (all nightly builds after that including beta.3.1) after running development server browser is showing "Cannot connect to server". 
After downgrade parcel to 2.0.0-nightly.644 everything works ok.

### package.json
```js
{
    "name": "parcel-test",
    "version": "1.0.0",
    "scripts": {
        "start": "parcel public/index.html --log-level verbose"
    },
    "validators": {
        "*.js": [
            "@parcel/validator-eslint"
        ]
    },
    "dependencies": {
        "cirrus-ui": "^0.6.2"
    },
    "devDependencies": {
        "@parcel/reporter-bundle-analyzer": "2.0.0-nightly.2250",
        "eslint": "~7.22.0",
        "parcel": "2.0.0-beta.3.1",
        "sass": "~1.32.4"
    }
}
```
### .parcelrc
```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{jpg,png,svg}": ["@parcel/transformer-raw"]
  },
  "reporters": ["@parcel/reporter-bundle-analyzer"]
}

```

## 🤔 Expected Behavior
![image](https://user-images.githubusercontent.com/1079037/121540813-13c21380-ca07-11eb-9bad-919d5dad589e.png)
```
▶ (⎈ |admin@default:default) npm start  

> parcel-test@1.0.0 start
> parcel public/index.html --log-level verbose

ℹ️ Server running at http://localhost:1234
✨ Built in 1.37s
@parcel/reporter-dev-server: Request: localhost:1234/
@parcel/reporter-dev-server: Request: localhost:1234/index.6788c1b1.js
@parcel/reporter-dev-server: Request: localhost:1234/favicon.ico
```

## 😯 Current Behavior
![image](https://user-images.githubusercontent.com/1079037/121540715-0016ad00-ca07-11eb-9bf7-146710685956.png)
```
▶ (⎈ |admin@default:default) npm start  

> parcel-test@1.0.0 start
> parcel public/index.html --log-level verbose

ℹ️ Server running at http://localhost:1234
✨ Built in 1.42s
```

## 💻 Code Sample

https://github.com/pcpl2/parcel-dev-server-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.646 and newer |
| Node             | 16.0.0 and 14.17.0 |
| npm/Yarn         | npm 7.10.0 |
| Operating System | macOS Catalina 10.15.7 |

**Comment by mischnic** [comment]
```
  "reporters": ["@parcel/reporter-bundle-analyzer"]
```
Overrides the existing reporters (including the dev server). You should do

```
  "reporters": ["@parcel/reporter-bundle-analyzer", "..."]
```

**Comment by pcpl2** [comment]
Ok works, thanks.
