### ISSUE TITLE
transformer-image automatically rotates 3:4 ratio images

### ISSUE THREAD

**Issue by Shaokun-X** [parcel-bundler/parcel#6444]
# 🐛 bug report

I have a bunch of images that I use Parcel/transformer-image to resize, I found that all the images of 3:4 ratio were automatically rotated 90 degrees thus became of 4:3 ratio. And I didn't find any way to configure this behavior.

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`:
```js
  "scripts": {
    "build": "parcel build index.html",
    "dev": "parcel index.html --open",
    "start": "npm run build && npm run dev"
  },
  "devDependencies": {
    "@parcel/packager-raw-url": "^2.0.0-beta.3.1",
    "@parcel/transformer-image": "^2.0.0-beta.3.1",
    "@parcel/transformer-sass": "^2.0.0-beta.3.1",
    "@parcel/transformer-webmanifest": "^2.0.0-beta.3.1",
    "parcel": "^2.0.0-beta.3.1",
    "posthtml-include": "^1.7.1",
    "sharp": "^0.28.3"
  }
```

Dev server:
```
$ npm run start
```

## 🤔 Expected Behavior

Converting images without rotation.

## 😯 Current Behavior

Converting all and only 3:4 images with 90 degrees rotation.

## 💻 Code Sample

I used HTML:
```html
<picture>
  <source srcset="url:./img/m1.jpg?as=webp&width=1280" type="image/webp">
  <img src="url:./img/m1.jpg?width=1280">
  <source srcset="url:/img/m1.jpg">
</picture>
```
Here `m1.jpg` is of 3024 × 4032 (3:4), the converted image became 1280 × 960 (4:3).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.3.1 |
| Node             | 14.15.4 |
| npm/Yarn         | 6.14.10 |
| Operating System | Windows 10 AMDx64

**Comment by Shaokun-X** [comment]
I haven't tested 4:3 images

**Comment by DeMoorJasper** [comment]
We need to do a rotate operation on the images to ensure the correct rotation https://sharp.pixelplumbing.com/api-operation#rotate 

If anyone wants to implement this feel free to do so, otherwise I'll look into this tomorrow

**Comment by LironHazan** [comment]
Will adding rotate() to ImageTransformer be enough? :)

```
      if (width || height) {
        imagePipeline.rotate().resize(width, height);
      }
```
