### ISSUE TITLE
CSS opacity property conversion bug

### ISSUE THREAD

**Issue by gordon-zhao** [parcel-bundler/parcel#6449]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

No .babelrc, no package.json. Only CLI and plain css. I'm able to reproduce the behavior using a minimal test set in the code sample. 
    
CLI command: 

    npm install --save-dev parcel && npx parcel build index.html

## 🤔 Expected Behavior

The opacity property in generated css should remain 100%.

## 😯 Current Behavior

The opacity value is changed from 100% to 1% in the generated css while running 'parcel build index.html' command.

Build Output: 

    .text{opacity:1%}
    /*# sourceMappingURL=index.85228101.css.map */

CSS generated from running 'parcel index.html' is not affected by this problem. 

Output:

    .text {
        opacity: 100%;
    }
    /*# sourceMappingURL=index.0f132b6c.css.map */

## 🔦 Context

This problem can accidentally hide elements, making unnecessary debug hassles. 

## 💻 Code Sample

    -- test/
      |-- index.html
      |-- index.css

index.html:

    <!DOCTYPE html>
    <html>
    <head>
        <link rel="stylesheet" href="./index.css">
    </head>
    <body>
        <h1 class="text">This is a heading</h1>
    </body>
    </html>

index.css:

    .text {
        opacity: 100%;
    }

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-beta.2
| Node             |  14.16.1
| npm/Yarn         | 6.14.12
| Operating System | Windows 10 20H2

**Comment by mischnic** [comment]
This should be fixed already in the nightly versions: https://github.com/parcel-bundler/parcel/issues/6308
