### ISSUE TITLE
[v2, swc regression] parcel/swc causes infinite loop by removing conditions in while loop

### ISSUE THREAD

**Issue by danieltroger** [parcel-bundler/parcel#6452]
# 🐛 bug report

For some reason swc, in both dev and production builds, assumes that conditions in a while loop can be optimized away which leads to the code infinite looping and hanging the browser.

## 🎛 Configuration (.babelrc, package.json, cli command)

Please see attached .zip.

## 🤔 Expected Behavior

Correctly transformed output code by v650:

```
(() => {
  let o;
  const e = {
    p: new Promise((e => o = e))
  };
  (async () => {
    for (; await e.p, 1;) console.log("Hello world")
  })(), (async () => {
    e.p = new Promise((() => {})), o()
  })()
})();
```

It prints "Hello world" once to the console.

## 😯 Current Behavior

```
! function() {
  let n;
  const o = {
    p: new Promise((o => n = o))
  };
  !async function() {
    for (;;) console.log("Hello world")
  }(), async function() {
    o.p = new Promise((() => {})), n()
  }()
}();
```

It prints "Hello world" an infinite amount of times to the console.

## 💁 Possible Solution

Don't do any optimizations that can infinite loop someones code. It's not cool.

## 🔦 Context

After some more bugs getting fixed I tried out the new parcel (old parcel being v650) with SWC again. To my delight everything seemed to work. Until I noticed that for some reason pound signs still get escaped in ie11 builds. Aaand then later on noticed that some of my stuff infinite loops.

## 💻 Code Sample

[parcel-infinity-loops.zip](https://github.com/parcel-bundler/parcel/files/6648368/parcel-infinity-loops.zip)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.720+ff6b7b4e|
| Node             |v16.2.0|
| npm/Yarn         |npm v7.13.0|
| Operating System |10.15.7 (19H1217)|

**Comment by danieltroger** [comment]
@kdy1 can you maybe check if this is SWC's fault and you can reproduce?

**Comment by danieltroger** [comment]
@mischnic Thanks for reporting to SWC! There seems to be a new release, https://github.com/swc-project/swc/releases/tag/v1.2.61, do you think we can get it into the next nightly so I can try upgrading again tomorrow? 👀 

I found my first bug in v650: `something ?? (bomething  || domething)` becomes `something ?? bomething  || domething` in `parcel serve` which causes a syntax error so I'd happily update because the new 7xx versions don't have that issue.

**Comment by kdy1** [comment]
This is not fixed yet on master, if I remember correctly

**Comment by kdy1** [comment]
Ah, sorry.
I misread it.
dead_branch_remover is fixed.
