### ISSUE TITLE
Wrong distDir when using `parcel watch .`

### ISSUE THREAD

**Issue by mariusGundersen** [parcel-bundler/parcel#6458]
# 🐛 bug report

The output of `parcel watch .` ends up in the wrong directory.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
// package.json
{
  "private": true,
  "targets": {
    "default": {
      "context": "browser",
      "source": "src/index.html",
      "distDir": "public"
    }
  },
  "scripts": {
    "watch": "parcel watch ."
  },
  "devDependencies": {
    "parcel": "^2.0.0-beta.3.1"
  }
}
```

The only other file I have is `src/index.html`.

![bilde](https://user-images.githubusercontent.com/464152/122064336-5e6dd200-cdf1-11eb-9e64-1fc66076ab55.png)

## 🤔 Expected Behavior

I want parcel to build and produce `public/index.html`. 

## 😯 Current Behavior

When I run this the file ends up in `public/<parent-folder-name>/src/index.html`. In the image below (and above) the project is in the folder `parcel-test`, which is why the build output is in `public/parcel-test/index.html`. 

![bilde](https://user-images.githubusercontent.com/464152/122064027-177fdc80-cdf1-11eb-814d-229e9c6a74f7.png)

## 💻 Code Sample

There's not much more than the `package.json` file in this scenario, just an html file with the default content from vscode snippet `html:5`:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>

</body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.3.1 |
| Node             | 14.16.1 |
| npm/Yarn         | 6.14.12 |
| Operating System | Windows 10 |

**Comment by JamesAlexanderHill** [comment]
In your package.json you need the following:
```
"web": "public/index.html",
"targets": {
    "web": {
        "context": "browser",
        "publicUrl": "./"
    }
},
```

and your build script should be `parcel build ./src/index.html --target web`

You can replace `web` with anything you want (As long as it is not an already defined target)

**Comment by mariusGundersen** [comment]
What if I have several html pages, do I need to specify a target for each one of them?

And why is this necessary to configure? It seems like a weird default to include the parent folder name in the path. What's the reason for doing so? When is that the expected output?

**Comment by JamesAlexanderHill** [comment]
I think you may be looking for this documentation: [Specifying entrypoints](https://v2.parceljs.org/getting-started/configuration/#specifying-entrypoints)

So you could define your script to be: `parcel watch './src/*.html' --target web`
and you package.json to have:
```
"web": "public/index.html",
"targets": {
    "web": {
        "context": "browser",
        "publicUrl": "./"
    }
},
```

As for your other questions, I dont know. Would be interested to find out if someone else can answer
_Note: the above has not been tested, just going off what I know/read and hopfully it can help you get going_
