### ISSUE TITLE
Aggregated export from a dependency is later available only in default export (named exports are missing)

### ISSUE THREAD

**Issue by quarties** [parcel-bundler/parcel#6461]
# 🐛 bug report

When I use `export * from 'some-module'` aggregated export syntax, then the named exports are available only via `default` export in a bundle.

## 🎛 Configuration (.babelrc, package.json, cli command)

`babel.config.json`
```json
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "targets": {
                    "node": "current"
                }
            }
        ]
    ]
}
```

`package.json`
```json
{
  // ...
  "main": "dist/index.js",
  "source": "src/index.js",
  "files": [
    "dist/**/*"
  ],
  // ...
  "engines": {
    "node": ">=10.11.0"
  },
  "targets": {
    "main": {
      "context": "node",
      "distDir": "dist",
      "includeNodeModules": false,
      "isLibrary": false,
      "optimize": false,
      "outputFormat": "esmodule",
      "scopeHoist": false,
      "sourceMap": false
    }
  }
}
```

command
```bash
parcel build src/index.js
```

## 🤔 Expected Behavior

The bundle should re-export all named exports as they are, so we can import them as follow:

```js
import { A, B, C } from 'my-module';
```

## 😯 Current Behavior

The bundle re-exports all named exports only via default export:

```js
// not working
import { A, B, C } from 'my-module'; 

// working
import { default as module } from 'my-module';
const { A, B, C } = module;
```

### Not working

`./node_modules/some-module/src/index.js` (source code before bundling, this module is also bundled with Parcel on my own)
```js
export const A = 'A';
export const B = 'B';
export const C = 'C';
```

`./node_modules/my-module/src/index.js` (source code before bundling)
```js
export * from 'some-module';
export const D = 'D';
```

`./src/index.js`
```js
import * as module from 'my-module';

console.log(module);
/* returns something like this:

[Module: null prototype] {
    __esModule: true,
    default: {
        A: 'A',
        B: 'B',
        C: 'C',
        D: 'D',
    },
    D: 'D'
}

instead of this:

[Module: null prototype] {
    __esModule: true,
    default: {
        A: 'A',
        B: 'B',
        C: 'C',
        D: 'D',
    },
    A: 'A',
    B: 'B',
    C: 'C',
    D: 'D'
}
*/
```

### Working

`./node_modules/some-module/src/index.js` (source code before bundling, this module is also bundled with Parcel on my own)
```js
export const A = 'A';
export const B = 'B';
export const C = 'C';
```

`./node_modules/my-module/src/index.js` (source code before bundling)
```js
export { A, B, C } from 'some-module';
export const D = 'D';
```

`./src/index.js`
```js
import * as module from 'my-module';

console.log(module);
/* returns something like this:
[Module: null prototype] {
    __esModule: true,
    default: {
        A: 'A',
        B: 'B',
        C: 'C',
        D: 'D',
    },
    A: 'A',
    B: 'B',
    C: 'C',
    D: 'D'
}
*/
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.3.1  |
| Node             | 14.16.1 |
| npm/Yarn         | 6.14.8 |
| Operating System | darwin - MacOS Big Sur 11.3.1 (20E241) |

**Comment by mischnic** [comment]
The problem is that Babel transpiles away all ESM import syntax into CJS before Parcel sees your code and CJS isn't enough for accurate library builds.

Either remove your babel config or follow https://v2.parceljs.org/languages/babel/#extending-the-default-babel-config

Why did you set `"isLibrary": false,`?

**Comment by quarties** [comment]
Oh, I forgot it has to be extended, nice catch. About `isLibrary` - I did it while trying to solve this on my own, hoping that maybe it would solve the issue. I'll extend the config and let you know about the results. Thanks for helping <3

**Comment by quarties** [comment]
Okay, so I had followed the [docs](https://v2.parceljs.org/languages/babel/#extending-the-default-babel-config), but now I don't have any named exports at all. I tried with `isLibrary` set both to `true/false`:
```
[Module: null prototype] {
  default: {
    A: [Getter],
    B: [Getter],
    C: [Getter],
    D: [Getter]
  },
  defineInteropFlag: undefined,
  export: undefined,
  exportAll: undefined,
  interopDefault: undefined
}
```

Same result when I entirely remove babel config files (.babelrc/babel.config.json)

**Comment by quarties** [comment]
New day, new ideas - I managed to properly set options to have proper builds. It looks like the main problem was the monorepo setup. Here is my current configuration:

`babel.config.json`
**removed**

`package.json`
```json
{
  // ...
  "type": "module",
  "main": "dist/index.js",
  "source": "src/index.js",
  "files": [
    "dist/**/*"
  ],
  // ...
  "engines": {
    "node": ">=10.11.0"
  },
  "targets": {
    "main": {
      "context": "node",
      "distDir": "dist",
      "includeNodeModules": false,
      "isLibrary": true,
      "optimize": false,
      "outputFormat": "esmodule",
      "scopeHoist": true,
      "sourceMap": true
    }
  },
  "alias": {
    "some-module": "../some-module/src/index.js"
  }
}
```

command
```bash
parcel build src/index.js
```

**Comment by quarties** [comment]
New day, new ideas - I managed to set options to have proper builds. It looks like the main problem was the monorepo setup. Here is my current configuration:

`babel.config.json`
**removed**

`package.json`
```json
{
  "name": "my-module",
  // ...
  "type": "module",
  "main": "dist/index.js",
  "source": "src/index.js",
  "files": [
    "dist/**/*"
  ],
  // ...
  "engines": {
    "node": ">=10.11.0"
  },
  "targets": {
    "main": {
      "context": "node",
      "distDir": "dist",
      "includeNodeModules": false,
      "isLibrary": true,
      "optimize": false,
      "outputFormat": "esmodule",
      "scopeHoist": true,
      "sourceMap": true
    }
  },
  "alias": {
    "some-module": "../some-module/src/index.js"
  }
}
```

command
```bash
parcel build src/index.js
```
