### ISSUE TITLE
Infer `"outputFormat": "esmodule"` for the "main" target with `"type": "module"`

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#6465]
With a `package.json` like
```json5
{
  "type": "module", // <----
  "main": "dist/index.js",
  "source": "src/index.js"
}
```

The default `outputFormat` of `main` should actually be `esmodule`, not `commonjs`.

**Comment by devongovett** [comment]
Should we also infer it if the file extension is .mjs?
