### ISSUE TITLE
Error "Cannot find module 'url: ...' or its corresponding type declarations" when using @parcel/validator-typescript

### ISSUE THREAD

**Issue by kylemclean** [parcel-bundler/parcel#6467]
# 🐛 bug report

Importing an asset in a TypeScript file using the `url` named pipeline causes an error when `@parcel/validator-typescript` is used as a validator.

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json:
```js
{
  "name": "parceltest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "parcel serve ./src/index.html",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@parcel/validator-typescript": "^2.0.0-nightly.724",
    "parcel": "^2.0.0-nightly.722",
    "typescript": "^4.3.2"
  }
}
```

.parcelrc:
```js
{
    "extends": "@parcel/config-default",
    "validators": {
        "*.{ts,tsx}": ["@parcel/validator-typescript"]
    }
}
```

tsconfig.json:
```js
{
    "include": [
        "src/**/*"
    ]
}
```

CLI command:
```parcel serve ./src/index.html```

## 🤔 Expected Behavior

The import statement in src/app.ts will not cause an error.

## 😯 Current Behavior

The build succeeds briefly, then shows the following error:

```
× Build failed.
@parcel/validator-typescript: Cannot find module 'url:./sound.wav' or its corresponding type declarations.
/parceltest/src/app.ts:1:19
> 1 | import sound from 'url:./sound.wav';
>   |                   ^^^^^^^^^^^^^^^^^^ Cannot find module 'url:./sound.wav' or its corresponding type declarations.
```

## 💁 Possible Solution

❓

## 🔦 Context

Importing assets normally works, but I want to use type checking with my TypeScript code. Unfortunately, using `@parcel/validator-typescript` causes this error so I am unable to do so.

I configured Parcel to do type checking for TypeScript using this page: https://v2.parceljs.org/languages/typescript/#type-checking

## 💻 Code Sample

src/index.html:
```html
<!DOCTYPE html>
<html>

<body>
    <script src="app.ts"></script>
</body>

</html>
```

src/app.ts:
```ts
import sound from 'url:./sound.wav';
```

src/sound.wav exists and is a valid file.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.722
| Node             | v14.17.1
| npm/Yarn         | npm 6.14.13
| Operating System | Windows 10 19042

**Comment by mischnic** [comment]
Following https://github.com/parcel-bundler/parcel/discussions/5194#discussioncomment-86432 should fix it

We should add that to the docs at some point: https://github.com/parcel-bundler/website/issues/843

**Comment by kylemclean** [comment]
> 
> 
> Following [#5194 (comment)](https://github.com/parcel-bundler/parcel/discussions/5194#discussioncomment-86432) should fix it
> 
> We should that to the docs at some point: [parcel-bundler/website#843](https://github.com/parcel-bundler/website/issues/843)

That works. Thank you.
