### ISSUE TITLE
SWC still escapes pound signs when building for IE11

### ISSUE THREAD

**Issue by danieltroger** [parcel-bundler/parcel#6469]
# 🐛 bug report

Parcel still escapes the pound sign when building for ie11

## 🎛 Configuration (.babelrc, package.json, cli command)

Please see attached .zip file. Target is `ie 11`

## 🤔 Expected Behavior

Output:
```
(function () {
"use strict";


console.log("££££££££££££££££££££££££££££££££££££££££££££££££££\n");

})();
//# sourceMappingURL=ie11.js.map

```

## 😯 Current Behavior

```
(function () {
"use strict";


console.log("\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\xa3\n");

})();
//# sourceMappingURL=ie11.js.map
```

## 💁 Possible Solution

Do like https://github.com/parcel-bundler/parcel/issues/6356 but also for the pound symbol.

## 🔦 Context

Script doesn't work in ie11

## 💻 Code Sample

[parcel-pound.zip](https://github.com/parcel-bundler/parcel/files/6664277/parcel-pound.zip)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.722+e9c4ebb1|
| Node             |v16.3.0|
| npm/Yarn         |npm v7.15.1|
| Operating System | macOS 10.15.7 (19H1217)|

**Comment by mischnic** [comment]
The output works fine for me in IE11

**Comment by danieltroger** [comment]
OOps. One second, let me debug some more.

**Comment by danieltroger** [comment]
@mischnic so it says `Expected hexadecimal digit` and highlights `z\u{142}` (which is the polish zloty symbol). But I have a script wrapped inside of a script, let me boot macOS again and try to change the repro repo to it to see if I'm the issue

<img width="210" alt="Capture" src="https://user-images.githubusercontent.com/4047180/122259208-373b0180-ced2-11eb-8ce9-8326916be89c.PNG">

**Comment by mischnic** [comment]
IE11 doesn't support `z\u{142}`, but `\xa3` works. So you're not actually having problems with the (GBP) pound sign?

**Comment by danieltroger** [comment]
It seems like I'm the issue.
I have a modern script wrapped inside of a string in an ie11 built script. The modern script contains escaped stuff and parcel just makes the ie11 script also contain escaped stuff. Is fixing my escaped stuff within parcel's scope?

**Comment by danieltroger** [comment]
> So you're not actually having problems with the (GBP) pound sign?

No. The problem is that my script doesn't run. The script contains a script in a string which is `if(!ie11)`'d and in an else is supposed to load the ie11 script. For some reason it doesn't run.
It contains a mapping of multiple currencies and I just saw that the pound sign still was escaped and opened the issue, sorry for that.

**Comment by danieltroger** [comment]
How I got to the pound sign: I unescaped my modern script by making a script that does `console.log(readFileSync("thescript"))` and taking the output thereof. The only currency symbol which didn't get escaped of that was the pound symbol… I didn't know some escape sequences work. Probably my output actually works lol. Lemme try

**Comment by danieltroger** [comment]
yeah, when the readFileSync'd text file doesn't contain `z\u{142}` it works. Sorry for the inconvenience!
