### ISSUE TITLE
`stream.on` is not a function

### ISSUE THREAD

**Issue by DeMoorJasper** [parcel-bundler/parcel#6475]
# 🐛 bug report

`@parcel/packager-js: stream.on is not a function` Happens when there's an html entrypoint without any linked js/ts files.

## 💻 Code Sample

```shell
parcel ./src/index.html
```

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

</body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |    2.0.0-nightly.722
| Operating System | OS X

**Comment by mischnic** [comment]
This is a bug in lmdb-store 1.5.3, fixed in 1.5.4 https://github.com/DoctorEvidence/lmdb-store/issues/51#issuecomment-862400843
