### ISSUE TITLE
Build fails in Parcel nightly 725

### ISSUE THREAD

**Issue by Cristy94** [parcel-bundler/parcel#6478]
# 🐛 bug report

I just upgraded from **nightly.570** to **nightly.725**. Everything worked fine before, but now when I try to build I get this error:

```
× Build failed.
@parcel/packager-js: The expression evaluated to a falsy value:

  (0, _assert().default)(typeof assetId === 'string')

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert().default)(typeof assetId === 'string')

    at ScopeHoistingPackager.resolveSymbol \node_modules\@parcel\packager-js\lib\ScopeHoistingPackager.js:698:27)
    at ScopeHoistingPackager.buildReplacements (node_modules\@parcel\packager-js\lib\ScopeHoistingPackager.js:607:27)
    at ScopeHoistingPackager.buildAsset (\node_modules\@parcel\packager-js\lib\ScopeHoistingPackager.js:416:39)
    at ScopeHoistingPackager.visitAsset (\node_modules\@parcel\packager-js\lib\ScopeHoistingPackager.js:376:17)
    at \node_modules\@parcel\packager-js\lib\ScopeHoistingPackager.js:209:40
    at \node_modules\@parcel\core\lib\Graph.js:538:16
    at \node_modules\@parcel\core\lib\Graph.js:538:16
    at \node_modules\@parcel\core\lib\Graph.js:538:16
    at walk (k\node_modules\@parcel\core\lib\Graph.js:403:26)
    at walk (\node_modules\@parcel\core\lib\Graph.js:425:22)
\dist\index.HASH_REF_638417ca3afb1157.js
```

I build with `--no-cache` and I also tried removing `.parcel-cache`.
The dev server works fine.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "scripts": {
    "build": "cmd /c \"set PARCEL_BUNDLE_ANALYZER=1 && parcel build src/index.html --no-cache --no-source-maps\"",
  },
  "dependencies": {
    "@date-io/moment": "^1.3.13",
    "@material-ui/core": "^4.10.2",
    "@material-ui/lab": "^4.0.0-alpha.56",
    "@material-ui/pickers": "^3.2.10",
    "@types/chart.js": "^2.9.21",
    "@types/deep-equal": "^1.0.1",
    "@types/heatmap.js": "^2.0.36",
    "@types/js-cookie": "^2.2.6",
    "@types/react-redux": "^7.1.9",
    "@types/react-router-dom": "^5.1.5",
    "chart.js": "^2.9.3",
    "deep-equal": "^2.0.4",
    "gulp-if": "^3.0.0",
    "heatmap.js": "^2.0.5",
    "i18next": "^19.4.5",
    "js-cookie": "^2.2.1",
    "material-table": "^1.60.0",
    "material-ui-confirm": "^2.0.5",
    "moment": "^2.26.0",
    "notistack": "^1.0.6",
    "query-string": "^6.13.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-i18next": "^11.8.13",
    "react-promise-tracker": "^2.1.0",
    "react-redux": "^7.2.2",
    "react-router-dom": "^5.2.0",
    "redux": "^4.0.5",
    "tslint": "^6.1.3",
    "yargs": "^15.4.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.0",
    "@babel/plugin-proposal-class-properties": "^7.10.1",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.10.1",
    "@babel/plugin-proposal-optional-chaining": "^7.10.1",
    "@babel/preset-env": "^7.10.2",
    "@babel/preset-react": "^7.10.1",
    "@babel/preset-typescript": "^7.10.1",
    "@parcel/transformer-image": "^2.0.0-nightly.2349",
    "@parcel/transformer-sass": "^2.0.0-nightly.727",
    "@types/jasmine": "^3.6.6",
    "@types/react": "^17.0.3",
    "@types/react-dom": "^17.0.3",
    "del": "^5.1.0",
    "gulp": "^4.0.2",
    "gulp-chmod": "^3.0.0",
    "gulp-delete-lines": "0.0.7",
    "gulp-file-checksum": "^2.0.1",
    "gulp-remove-code": "^3.0.4",
    "gulp-replace": "^1.0.0",
    "gulp-sftp": "git+https://git@github.com/webksde/gulp-sftp.git",
    "gulp-zip": "^5.0.1",
    "jasmine": "^3.6.4",
    "jasmine-console-reporter": "^3.1.0",
    "parcel": "^2.0.0-nightly.725",
    "puppeteer": "^8.0.0",
    "sass": "^1.26.8",
    "ts-node": "^9.1.1",
    "typescript": "^4.2.4"
  },
  "browserslist": [
    "last 1 Chrome version"
  ],
  "app": "dist/index.html",
  "targets": {
    "app": {
      "publicUrl": "./"
    }
  }
}

```

## 🤔 Expected Behavior

Build works.

## 😯 Current Behavior

Build fails.

```@parcel/packager-js: The expression evaluated to a falsy value:```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.725
| Node             | v14.15.0
| npm/Yarn         | npm 6.14.8
| Operating System | W10

**Comment by Cristy94** [comment]
Might be related: https://github.com/parcel-bundler/parcel/issues/6374

I reverted back to nightly 570 until this issue is fixed.

**Comment by DaveO-Home** [comment]
With 725 and Fedora 34, both node 12 & 14 I get the following;

Note; when wrapping this in a ```try``` the build works

```/* istanbul ignore else */
if (typeof require !== 'undefined' && undefined.extensions) {
    undefined.extensions['.handlebars'] = extension;
    undefined.extensions['.hbs'] = extension;
}
```
ERROR: TypeError: undefined has no properties

**Comment by mischnic** [comment]
@DaveO-Home -> https://github.com/parcel-bundler/parcel/issues/6479

---

@Cristy94 There's also https://github.com/parcel-bundler/parcel/issues/3676#issuecomment-860624452

Do you have a babel config that doesn't follow https://v2.parceljs.org/languages/babel/#extending-the-default-babel-config causing Babel to transpile ESM to CJS before Parcel itself processes the code?

Or is there a file in node_modules that does something like `require("./styles.css")`?
You can print out the filepath by adding `console.log(resolvedAsset.filePath);` just before the line where the assertion fails

**Comment by DaveO-Home** [comment]
My .babelrc
```{
  "presets": ["@parcel/babel-preset-env", "@babel/preset-react", [
    "@babel/preset-env", {
      "targets": {
           "ie": 11,
          "browsers": ["> 0.2%, not dead, not op_mini all"]
      },
      "modules": false,
      "debug": false,
      "useBuiltIns": "usage",
      "corejs" : "3"
  }
  ]],
  "plugins": ["@parcel/babel-plugin-transform-runtime"]
}
```

I do have the ```require("./styles.css")``` but in a totally unrelated module;
```node_modules/steal-bundler/test/basics/main.js:require("./styles.css");```

resolvedAsset is not defined in the bundle.

**Comment by Cristy94** [comment]
I tried upgrading again to see if the problem was fixed, but now there's a different build error in nightly746

```
@parcel/transformer-js: Browser scripts cannot have imports or exports. Use a <script type="module"> instead.
src\index.tsx:1:1
> 1 | import React from 'react';
>   | ^
  2 | import ReactDOM from 'react-dom';
  3 | import { Provider } from 'react-redux';
@parcel/transformer-js: The environment was originally created here:
\src\index.html:16:9
  15 |         <div id="modal-portal" class="fixed top left z-index-max"></div>
> 16 |         <script src="./index.tsx"></script>
>    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  17 |     </body>
  18 | </html>
  ```

This is my .babelrc

```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    "@babel/preset-typescript"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-nullish-coalescing-operator",
    "@babel/plugin-proposal-optional-chaining"
  ]
}
```

Do I just have to add `type=module`? Will this affect the build in any way (eg. lazy load the JS instead of sync load) ?

**EDIT:** Adding  `type=module` fixed the error, still got some weird build errors but after a cache clear and a few restarts it worked. That being said, the project is now no longer working (weird import issues). It's so strange that every nightly build something else breaks.

**Comment by mischnic** [comment]
> Do I just have to add type=module?

Yes

> Will this affect the build in any way (eg. lazy load the JS instead of sync load) ?

It will behave like the native `<script type="module">` (so the script is `defer` by default, so not parser blocking: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-defer)

> That being said, the project is now no longer working (weird import issues).

Can you give more details?

> It's so strange that every nightly build something else breaks.

This `<script type=module>` change was the biggest/only user-facing breaking change we wanted to do before the RC.

**Comment by Cristy94** [comment]
> Can you give more details?

It seems to be working now.
I think most of the issues were due to two things:

1) Parcel cache. Now it seems that after a build, even when building with `--no-cache`, when I start dev server again, it will fail with a syntax error unless I delete `.parcel-cache`.
2) Imports acting differently: With the previous nightly version, I think some files were imported automatically (even if I didn't specifically import them), but now I got some missing imports errors (which I think is good).

**Comment by mischnic** [comment]
> Parcel cache

Do you need to always clear it after building? That's a bug.

You should definitely delete the whole cache folder once after upgrading Parcel

**Comment by devongovett** [comment]
To be clear that _shouldn't_ be required, but sounds like there's a bug. Would be good to get to the bottom of it. 😉

**Comment by Cristy94** [comment]
> > Parcel cache
> 
> Do you need to always clear it after building? That's a bug.
> 
> You should definitely delete the whole cache folder once after upgrading Parcel

From what I can tell yes, I always have to clear cache after building, otherwise it says the script needs to have type module (even though it has).

**Comment by mischnic** [comment]
Can you share a reproduction?
