### ISSUE TITLE
require.extensions becomes undefined.extensions

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#6479]
With 725 and Fedora 34, both node 12 & 14 I get the following;

Note; when wrapping this in a ```try``` the build works

```/* istanbul ignore else */
if (typeof require !== 'undefined' && undefined.extensions) {
    undefined.extensions['.handlebars'] = extension;
    undefined.extensions['.hbs'] = extension;
}
```
ERROR: TypeError: undefined has no properties

_Originally posted by @DaveO-Home in https://github.com/parcel-bundler/parcel/issues/6478#issuecomment-864428606_

**Comment by DaveO-Home** [comment]
Verified - thanks...
