### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by gweinfurther** [parcel-bundler/parcel#648]
I just installed parcel. When running parcel in live or build mode, I get this message:

UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: 'super' keyword unexpected here

Running on Windows 10 in Chrome 63.
Parcel 1.5

**Comment by ZWkang** [comment]
i got it too~

**Comment by akosasante** [comment]
Same here
Running on Ubuntu 16.04
Parcel 1.50

**Comment by sinout** [comment]
Same here. Encountered after update from v1.4.1

**Comment by DeMoorJasper** [comment]
@sinout node.js 6 is currently not supported we are working to support it in the future

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by srph** [comment]
Having it as well. Just installed `v1.5`. Using node `v7.5.0`

**Comment by DeMoorJasper** [comment]
@srph node 7 isnt supported yet either only node 8+ is currently supported

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mdchristians** [comment]
Having the same issue.
Fresh install of Parcel on a fresh project.  Node v8.9.3.

**Comment by katsos** [comment]
For anyone who has the same problem, you can use nvm for your project with "v8" wrote in its .nvmrc file until it is fixed.

**Comment by mdchristians** [comment]
@katsos My project has an .nvmrc implemented already using 8.9.3...

**Comment by katsos** [comment]
@mdchristians don't forget to execute `nvm use` inside the folder from the same terminal that you are going to execute anything related to Node.

**Comment by mdchristians** [comment]
@katsos My .nvmrc file is being used.  Running` node -v` outputs 8.9.3 within the project directory.

**Comment by mdchristians** [comment]
It's working with Node v8.5.0 so now I'm pretty sure it's an issue with something else...

**Comment by DepickereSven** [comment]
I have this problem to. 

I have:
Node v8.9.4
Fresh install of Parcel

Every time I run it I get an other number in front of the error some examples:
`(node:16656) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: 'super' keyword unexpected here`
`(node:4332) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: 'super' keyword unexpected here`
``(node:7572) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: 'super' keyword unexpected here`
`(node:24156) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: 'super' keyword unexpected here`

Anyone a suggestion?

**Comment by davidnagli** [comment]
@devongovett Do you think we should work towards adding support for Node 6? Should we reopen this issue to track this?

**Comment by DepickereSven** [comment]
I had an older node version and I updated to version 8.9.4 and I still got that error.

So how did I fixed it?
I uninstalled Nodejs en nvm and then reinstall nodejs.
If you do that It should work.

**Comment by gamebox** [comment]
I guess one issue I would have with this - I have the same issue on Node v7.8.0 - is that the "engine" -> "node" key in the package.json should be updated to reflect that you need 8+.

**Comment by tiberiucorbu** [comment]
Node 6.x is still an active LTS and it will benefit maintenance until April 2019.
https://github.com/nodejs/Release

**Comment by ocsen** [comment]
node 7 isnt supported yet either only node 8+ is currently supported ！！！
nvm use 9
