### ISSUE TITLE
[Web Extension Transformer] doesn't support `background.page`

### ISSUE THREAD

**Issue by rraallvv** [parcel-bundler/parcel#6494]
# 🙋 feature request

`@parcel/transformer-webextension` doesn't pack the background page specified in the source `manijest.json` file.

## 🤔 Expected Behavior

The packed extension should have the `background.html` page with all assets (scripts, css, images, etc.)

## 😯 Current Behavior

Adding a background page to the `manifest.json`, like it's shown below, is ignored by the transformer:

```
{
...
  "background": {
    "page": "background.html",
    "persistent": true
  },
...
}
```

**Comment by HaNdTriX** [comment]
just as an escape hatch: try to use background scripts instead:

```json
...
	"background": {
		"persistent": true,
		"scripts": [
			"background.js"
		]
	}
...
```

**Comment by tylervick** [comment]
Definitely a valid workaround (and ideal for most scenarios). I'm attempting to build a Safari App Extension for iOS and listing script sources in the background.html file seems to be the easiest path forward. The only alternative I see is to configure a plugin to merge all imported modules into a single file (a la webpack).

**Comment by HaNdTriX** [comment]
I thought this is what parcel (bundler) is doing anyway. 

Create a background.js and use it as an entry point for all of your scripts. Parcel will bundle this for you, afaik.

**Comment by tylervick** [comment]
This might be a configuration issue of mine - I think last I tried this I had some files specified in `web_accessible_resources` which were copied over... I'll try this again without.
