### ISSUE TITLE
Parcel report dev server overwriting headers set on proxyrc.js middlewares

### ISSUE THREAD

**Issue by vitorcodesalittle** [parcel-bundler/parcel#6499]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

.proxyrc.js
```js
module.exports = function(app) {
  app.use((req, res, next) => {
    res.setHeader('Cross-Origin-Embedder-Policy', 'unsafe-none')
    next()
  })
}
```

.babelrc.json:
```json
{
  "presets": [
    "@parcel/babel-preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    "babel-plugin-transform-glob-import",
    "@parcel/babel-plugin-transform-runtime",
    ["import", { "libraryName": "antd", "libraryDirectory": "lib", "style": false}, "antd"],
    ["import", { "libraryName": "antd-new", "libraryDirectory": "lib", "style": "css"}, "antd-new"]
  ]
}
```
cli command:
`parcel public/index.html --port 4000 --log-level verbose`

## 🤔 Expected Behavior

Responses should have the header as defined on the middleware.

## 😯 Current Behavior

Response always with `Cross-Origin-Embedder-Policy: require-corp`. Probably also happens with other headers being set by
https://github.com/parcel-bundler/parcel/blob/e63235f33fadbc3009f94281b9c7420d0c4b383f/packages/reporters/dev-server/src/Server.js#L33

## 💁 Possible Solution

I believe is just a matter of the order of the middlewares being called. I would be glad try a PR once the issue is confirmed to be an issue.

## 🔦 Context

I wish I could have a more flexible development server.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.720
| Node             | 14.17.0
| npm/Yarn         | 6.14.13
| Operating System | Fedora 34

**Comment by mischnic** [comment]
I think it would make sense to call `setHeaders` before the proxyrc is applied 👍

**Comment by HenrikJoreteg** [comment]
This bit me.

I was just including Stripe and was surprised it didn't work when updating from Parcel 1 to Parcel 2. It's kind of uninituitive, IMO that something as benign as lazily loading 3rd party JS doesn't work.

**Comment by mischnic** [comment]
This has been reverted: https://github.com/parcel-bundler/parcel/pull/6789

**Comment by HenrikJoreteg** [comment]
@mischnic thanks 😊
