### ISSUE TITLE
Governance

### ISSUE THREAD

**Issue by thejameskyle** [parcel-bundler/parcel#65]
Hey, just wanted to start this earlier rather than later. A couple things:

- It'd be great to start creating GitHub teams to take on difference responsibilities: Core, Docs, Babel/TypeScript/Sass, etc
- To help organize ideas and feature requests, we could adopt an RFC process from tools like [Yarn](https://github.com/yarnpkg/rfcs)/[Rust](https://github.com/rust-lang/rfcs)/etc

**Comment by davidnagli** [comment]
+1

**Comment by yeskunall** [comment]
What's the vetting process look like for this @thejameskyle? 😁

**Comment by davidnagli** [comment]
For the time being, what’s the process for becoming a member in the Parcel organization?

**Comment by devongovett** [comment]
@davidnagli how would you like to contribute?

**Comment by shawwn** [comment]
I'd like to set up [gitter](https://gitter.im/) support if it seems like a good idea, but I'd need to become a member of the org. See #103 

It'd give newcomers a place to chat and figure things out together.

**Comment by davidnagli** [comment]
@devongovett From what I can see some of the most pressing things in this projects is “issue triage”, I try to help as much as I can but it would be great if I could add labels and close issues so I can save you and @thejameskyle some time 😇 

I also wanna help in any other way possible… I’m a student so I have plenty of free time to contribute to open source. Just tell me anything to work on, and I can work on it!

**Comment by devongovett** [comment]
@davidnagli @shawwn created a triage team to start with and invited you both.

**Comment by shawwn** [comment]
@devongovett @davidnagli @thejameskyle I created a slack workspace and invited all of you. I'll transfer primary ownership to @devongovett.

**Comment by yeskunall** [comment]
I can help improve docs and help in any other way if you'd like @devongovett. ✋🏽

Not sure if a team exists for that or not, but yeah. Down to help.

**Comment by TheLarkInn** [comment]
CoC could go under this issue also if relevant.

**Comment by albinotonnina** [comment]
If you need more help please don't hesitate to contact me as well

**Comment by devongovett** [comment]
Closing this for now, as we've accomplished most of this. If we would like to adopt a formal RFC process like Yarn and others have, I'm open to that. So far we've been moving pretty quickly and no super major/breaking features have been proposed yet.
