### ISSUE TITLE
image is not displayed when serving through parcel

### ISSUE THREAD

**Issue by akhildevelops** [parcel-bundler/parcel#6503]
# 🐛 bug report

Unable to display images when parcel server is running by the command parcel serve ./index.html. 

But works when using other server like live-server from vscode pointing to dist folder generated by parcel.

## 🎛 Configuration (.babelrc, package.json, cli command)
Package.json
```
{
  "name": "practice",
  "version": "1.0.0",
  "description": "Practice for JS",
  "main": "index.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "parcel serve ./index.html",
    "build": "parcel build ./index.html"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "d3": "^7.0.0"
  },
  "browserslist": [
    "last 3 Chrome versions"
  ],
  "devDependencies": {
    "parcel": "^2.0.0-beta.3.1"
  },
  "app": "dist/browser/index.js",
  "appModern": "dist/browserModern/index.js",
  "targets": {
    "app": {
      "engines": {
        "browsers": "> 0.25%"
      }
    },
    "appModern": {
      "engines": {
        "browsers": "Chrome 70"
      }
    }
  }
}

```

## 😯 Current Behavior

![parcel](https://user-images.githubusercontent.com/6951100/122942789-153ef480-d394-11eb-8d08-f81a61f96499.jpg)
This is what comes up when serving from parcel.

## 🤔 Expected Behavior

![live-server](https://user-images.githubusercontent.com/6951100/122943008-47505680-d394-11eb-8bf4-2c03bf247631.jpg)
This normally displays image when using vs-code live-server.

## 💻 Code Sample

```
<!DOCTYPE html>
<html>
  <link rel="stylesheet" href="main.css" />
  <body>
    <img
      class="fit-picture"
      src="https://www.freecodecamp.org/news/content/images/size/w2000/2020/11/Screen-Shot-2020-11-15-at-3.59.07-PM.png"
      rel="noreferrer"
    />
    <div class="container"></div>
  </body>
  <!-- <script src="main.js" type="module"></script> -->
</html>

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.729|
| Node             | v14.17.0 |
| npm/Yarn         | 6.14.13 |
| Operating System | Ubuntu |

**Comment by abhijitbcob** [comment]
I am also facing this issue

**Comment by mischnic** [comment]
> This is what comes up when serving from parcel.

Do you get an error message in the browser console if the image isn't displayed?

**Comment by DeMoorJasper** [comment]
Just tried this locally and this is due to our changes to the dev server to prepare for the breaking changes Chrome is gonna release soon: https://web.dev/coop-coep/

To fix your example you can add the `crossorigin` attribute to the `img` tag, like this:

```html
<img
      class="fit-picture"
      src="https://www.freecodecamp.org/news/content/images/size/w2000/2020/11/Screen-Shot-2020-11-15-at-3.59.07-PM.png"
      rel="noreferrer"
      crossorigin
    />
```

You can also undo our changes by creating a `.proxyrc.js` as mentioned here: https://github.com/parcel-bundler/parcel/issues/6561#issuecomment-878344133 but this is probably not really future proof

**Comment by Synchr0nicity** [comment]
adding crossorigin did nothing. Really what is happening here?

**Comment by RetryRain** [comment]
I have the same issue but with wow js animations

**Comment by KaraNxKP007** [comment]
Hi I think we need to convert that to meta url
const imageURL=new URL('path',import.meta.url)

then it worked for me thanks.
Hope it helps and I am not late delivering the soln.👍
