### ISSUE TITLE
SyntaxError: Invalid or unexpected token when importing a background image in SCSS

### ISSUE THREAD

**Issue by adamreisnz** [parcel-bundler/parcel#651]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
Bug

### 🎛 Configuration (.babelrc, package.json, cli command)

```scss
.Background {
  background: url('assets/bg.jpg');
}
```

### 🤔 Expected Behavior
For it to work

### 😯 Current Behavior
Fails with a JS error `SyntaxError: Invalid or unexpected token` on the following line at the bottom:

```
},{"./bundle-url":15}],9:[function(require,module,exports) {

        var reloadCSS = require('_css_loader');
        module.hot.dispose(reloadCSS);
        module.hot.accept(reloadCSS);
      
},{"./assets/bg.jpg":[["4edb26dd740df8d2a3,17:[function(require,module,exports) {
```
The background image itself is displaying fine. It's just crashing all the JS due to this error.

### 💻 Code Sample
See above
### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.5.0
| Node             | 8.9.3
| npm/Yarn         | Yarn, 1.3.2
| Operating System | OS X

**Comment by adamreisnz** [comment]
Additional information, this only started happening when I created a second HTML page, and linked to that second page from my first page. Once I removed that page it was back to working fine.

**Comment by martisj** [comment]
I am seeing the same issue. Does Parcel allow linking to other html pages from the entry point with `<a>` tags?
