### ISSUE TITLE
Invalidate cache when NODE_ENV changes

### ISSUE THREAD

**Issue by aminya** [parcel-bundler/parcel#6521]
# 🐛 bug report

IF you set `NODE_ENV` to `production` and build using Parcel, and then set it to `test` and rebuild, Parcel will use the production cache,

```js
scripts {
    "build.test": "cross-env NODE_ENV=test parcel build --target main ./lib/main.js",
    "build": "cross-env NODE_ENV=production parcel build --target main ./lib/main.js",
}
```

```
npm run build && npm run build.test
```

## 🤔 Expected Behavior

Invalidate the cache when `NODE_ENV` changes. 

## 😯 Current Behavior

It reuses the production cache in the test build.

## 💁 Possible Solution

Clean `.parcel-cache`.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2 nightly ~700
| Node             | All
| npm/Yarn         | All
| Operating System | All

**Comment by devongovett** [comment]
`parcel build` always does a production build, `NODE_ENV` does not affect that. You can use `--no-optimize` if you want to disable minification. Changing `NODE_ENV` does affect inlined `process.env.NODE_ENV` values and does invalidate the cache (I just verified, and we do have a test for that). Was there something else you were expected to be invalidated?

**Comment by aminya** [comment]
[I use a custom `.terserrc`](https://github.com/atom-community/terser-config-atomic/blob/20f41eda52c6b9fcc1ccb6d2dd4baccbe6670c54/src/.terserrc.js#L1-L2), which [replaces `process.env.NODE_ENV`](https://github.com/atom-community/terser-config-atomic/blob/20f41eda52c6b9fcc1ccb6d2dd4baccbe6670c54/src/.terserrc.js#L8) and some other compile-time variables (e.g. `Atom.inDevMode`) with its value at the compile time. 

I expected that Parcel does this by default for `process.env.NODE_ENV`, but apparently it doesn't. Without my custom `terserrc`, this results in the inclusion of development libraries (e.g. for React).

**Comment by devongovett** [comment]
> I expected that Parcel does this by default for process.env.NODE_ENV, but apparently it doesn't.

It does. Do you have a reproduction?

As for invalidation, JS configs should always be invalidated whenever you restart Parcel.

**Comment by mischnic** [comment]
The terser optimizer doesn't use the new `loadConfig` API 

https://github.com/parcel-bundler/parcel/blob/413a09364646811f6067be80065c15d7b6270236/packages/optimizers/terser/src/TerserOptimizer.js#L20-L27


and it's also missing the `invalidateOnStartup()` part like here
https://github.com/parcel-bundler/parcel/blob/413a09364646811f6067be80065c15d7b6270236/packages/optimizers/cssnano/src/CSSNanoOptimizer.js#L11-L25
