### ISSUE TITLE
parcel prepending urls with '/'

### ISSUE THREAD

**Issue by adventmedia** [parcel-bundler/parcel#6524]
# 🐛 bug report

regardless whether the href or src for an asset (css, img etc.) is set to (e.g.) `href="css/site.css" or `"href="./css/site.css"`,  it is rewritten by build as `href="/css/site.css"`, which breaks the site if it is not deployed at the root of the domain, e.g. `mydomain.com/iframes/parceled-microsite` - the html references are relative to `mydomain.com`, not the fully qualified path.

**Comment by devongovett** [comment]
You can use the `--public-url` option to override this.
