### ISSUE TITLE
Asset manifest generation for Progressive Web Apps

### ISSUE THREAD

**Issue by LukeTOBrien** [parcel-bundler/parcel#6537]
Hello there,

I would like to pose this idea and see what people think.

# 🙋 feature request

Add an option to `parcel build` command that will generate an asset manifest that can be used in Progressive Web Apps.

## 🔦 Context

In my small project (no images only fonts, CSS, js) I  have 34 files, in order to create a PWA with offline support I need the create an array [like this one](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers#lifecycle_of_a_service_worker) of string paths of the files to cache.  
In my case MS Build generates that arry for me, I think Parcel could also do the same.

## 💻 Examples

I have been doing work with Blazor and in the MS build [process there is a way to generate a asset manifest that can be used with service workers](https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-5.0&tabs=visual-studio#control-asset-caching).  
The resulting `service-worker-assets.js` looks something like:
```js
self.assetsManifest = {
  "assets": [
    {
      "hash": "sha256-Qd5OFPYSoBtsCZHoaUc4apRG\/+eYhrrprodkCXwRVUA=",
      "url": "index.html"
    },
    {
      "hash": "sha256-nhf\/6BT8lpqVCPNnhnOce1Ix+1IUye0hIF4nXXJe+vo=",
      "url": "script.js"
    },
    {
      "hash": "sha256-nhf\/6BT8lpqVCPNnhnOce1Ix+1IUye0hIF4nXXJe+vo=",
      "url": "styles.css"
    }
   ...
  "version": ""Ggap8cTj""
]
```
It is then imported into the main `service-worker.js` and assets are cached:
```js
self.importScripts('./service-worker-assets.js');
...
async function onInstall(event) {
    // Fetch and cache all matching items from the assets manifest
    const assetsRequests = self.assetsManifest.assets
        .map(asset => new Request(asset.url, { integrity: asset.hash }));
    await caches.open(cacheName).then(cache => cache.addAll(assetsRequests));
}
```

I just had the thought that whilst Parcel does it's bundling, it could compile a list of all the assets and generate an asset manifest like this one.  
What do you think? Would an option like this be a good idea?

**Comment by 101arrowz** [comment]
This is possible from a plugin. In fact, I've personally implemented exactly what you're asking for in [`parcel-config-precache-manifest`](https://github.com/101arrowz/precache-manifest/tree/master/packages/parcel-config-precache-manifest).

**Comment by LukeTOBrien** [comment]
ahh fantastic thanks! I will close this issue
