### ISSUE TITLE
Can't add css to .vue

### ISSUE THREAD

**Issue by sda3-14** [parcel-bundler/parcel#6546]
# 🐛 bug report

I tried adding some css to my apps .vue file, but I can't find a way with which it works.

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json: 
```json
{
	"name": "...",
	"version": "...",
	"description": "",
	"dependencies": {},
	"repository": {
		"type": "git",
		"url": "..."
	},
	"author": "",
	"license": "ISC",
	"bugs": {
		"url": "..."
	},
	"homepage": "...",
	"devDependencies": {}
}

```

## 🤔 Expected Behavior

Parcel adds the files.

## 😯 Current Behavior

I've tried different things (all with different errors), but it currently outputs
```
× Build failed.
@parcel/transformer-vue: Unknown style language: ".css"
```
Pretty sure it should know css, but I also tried .scss and that one failed too.

## 💻 Code Sample

index.htm: 
```html
<!doctype html>
<html>
	<head>
		<title>...</title>
	</head>
	<body>
		<div id="app"></div>
		<script src="./index.js"></script>
	</body>
</html>
```
index.js: 
```javascript
import { createApp } from 'vue';
import App from './App.vue';

const vapp = createApp(App);
vapp.mount('#app');
```
App.vue: 
```vue
<template>
	<div id="content">
		<p>testing</p>
	</div>
</template>
<style src="./App.css"></style>
<script lang="ts">
	export default {
		data() {
			return {
			};
		}
	};
</script>
```
App.css (example): 
```css
#content {
	color: red;
}
```

Inline css does not work either, but adding the css in the html file instead of the vue file works.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.3.1 |
| Vue              | 3.1.4 |
| @parcel/transformer-vue | 2.0.0-beta.3.1 |
| Node             | 6.14.13 |
| Operating System | Windows 11 (Insider Build) |

**Comment by mischnic** [comment]
Looks like these should instead check for `".less"` (and so on):
https://github.com/parcel-bundler/parcel/blob/55046276c1fd0765b30a228d5dca0df68ef718da/packages/transformers/vue/src/VueTransformer.js#L321-L326

**Comment by 247-coder** [comment]
Okay, thanks. Are there any workarounds?

**Comment by dqkit** [comment]
it seems js or ts file have same problem....
is should be check ".ts" or ".js"
