### ISSUE TITLE
Command line option hint mismatch

### ISSUE THREAD

**Issue by muminoff** [parcel-bundler/parcel#655]
First of all, thanks for the great tool! 👍 

Command line option has some hint mismatching. And, I think this is just letter conflict, not a 🐛 bug.

### 🤔 Expected Behavior

`$ parcel -h` should give help information.

### 😯 Current Behavior

`$ parcel -h` returns hmr-port argument missing error message.

### 🌍 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.5.0 |
| Node             | v9.4.0 |
| npm/Yarn         | npm 5.6.0 / yarn 1.3.2 |
| Operating System | macOS High Sierra 10.13.2 |

![screen shot 2018-01-25 at 10 57 38 am](https://user-images.githubusercontent.com/1235454/35369074-ace4ad20-01c9-11e8-88ec-7605d7d02ef6.jpg)

**Comment by devongovett** [comment]
Yep, we should remove the `-h` alias and only support `--hmr-port` for this. I think it should be a fairly rare option anyway.
