### ISSUE TITLE
Cannot load .php with Parcel

### ISSUE THREAD

**Issue by louiskuznik** [parcel-bundler/parcel#6550]
# 🐛 bug report

**.html load great
.php return** 
" This localhost page could not be found 
No web page found at: http: // localhost: 1234 /
HTTP ERROR 404 "
**ofc i change the package.json config to index.php**
**.php load fine in basic localhost with wamp server**

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
" {
  "name": "map",
  "main": "index.js",
  "dependencies": {
    "ol": "^6.5.0",
    "parcel": "^2.0.0-beta.2"
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.5"
  },
  "scripts": {
    "start": "parcel index.php",
    "build": "parcel build --public-url . index.php"
  },
  "version": "1.0.0",
  "author": "",
  "license": "ISC",
  "keywords": [],
  "description": ""
} "
```

## 😯 Current Behavior

" This localhost page could not be found 
No web page found at: http: // localhost: 1234 /
HTTP ERROR 404 "

![error](https://user-images.githubusercontent.com/37616802/124619957-5c8bb180-de79-11eb-9821-3f4c28b3b6e3.png)

## 🔦 Context

It worked fine, and it happened when i shutdown one virtual machine (why?maybe not the cause)
i tried uninstall and reinstall, and reswap to html, html work fine, my problem is php

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.5
| Node             | 10.16.0
| npm/Yarn         | npm
| Operating System | Windows 10

**Comment by flexchar** [comment]
Parcel cannot interpret PHP. When you specify `index.php` it will look for such path in the folder root. Most likely before you had a web server that was also serving on same host and served the contents. Therefore this is not an issue with the parcelJS.

I would strongly advise you to separate PHP & frontend assets. Do so by manually providing input files to parcel CLI and then include the output in PHP template. This way you will find yourself in less confusion. 

An example would be `parcel watch path/to/source.js --dist-dir public/assets` where `watch` may be replaced with `build`. `-d` is to specify out put folder. Run `npm parcel --help` for more options.

**Comment by louiskuznik** [comment]
> Parcel cannot interpret PHP. When you specify `index.php` it will look for such path in the folder root. Most likely before you had a web server that was also serving on same host and served the contents. Therefore this is not an issue with the parcelJS.
> 
> I would strongly advise you to separate PHP & frontend assets. Do so by manually providing input files to parcel CLI and then include the output in PHP template. This way you will find yourself in less confusion.
> 
> An example would be `parcel watch path/to/source.js --dist-dir public/assets` where `watch` may be replaced with `build`. `-d` is to specify out put folder. Run `npm parcel --help` for more options.

Thanks for this answer, i'll do that
