### ISSUE TITLE
Allow for safer development of Reporter plugins

### ISSUE THREAD

**Issue by marcins** [parcel-bundler/parcel#6557]
# 🙋 feature request

If I start developing a new Reporter plugin, and I even have an import error at the top then Parcel will get stuck an infinite loop trying to load my Reporter plugin in order to log the error which fails with an error and.. you get the idea!

I want a safe dev loop for Reporter plugins that don't need to log anything, but instead are used in order to produce metadata from build information at the end of the build (i.e. I just need `buildStart` / `buildEnd` type events, but not `log` events)

## 🤔 Expected Behavior

I should be able to create a Reporter plugin with errors that doesn't break Parcel.

## 😯 Current Behavior

A broken Reporter plugin breaks Parcel. You usually need to `killall node` in order to stop Parcel once it's stuck in this logging loop.

## 💁 Possible Solution

At a high level, I see a couple of potential solutions to this:

* A new plugin type that is designed for producing build metadata that isn't a Reporter plugin (i.e. just the `build`/`watch` related events - essentially a subset of Reporter)
* more resilience for plugin loading - if a plugin causes an error when loading then don't try loading that plugin again. Potentially gets a bit trickier when it comes to dealing with failed `log`s (this is kind of a special case)

There are probably other ways to approach this that someone with more familiarity with the architecture may come up with.

## 🔦 Context

As part of migrating our Webpack build to Parcel we need to provide equivalent functionality that's related to our build / deployment infrastructure - a lot of these will be implemented as Reporter plugins as they require access to the final build graph or build statistics (for example: logging build time metrics to our logging infra, producing asset metadata for our page composition service, producing bundle stats reports..) - having a safe devloop for these plugins will reduce frustration and increase velocity.

**Comment by DeMoorJasper** [comment]
When reporters where created we anticipated this: https://github.com/parcel-bundler/parcel/blob/v2/packages/core/core/src/ReporterRunner.js#L98

Where does this error happen that that line doesn't handle it?

**Comment by mischnic** [comment]
I think this happened because of some syntax/load time error, so there would be an error here:
https://github.com/parcel-bundler/parcel/blob/81293fc84517f756b593a73d94da4e2630339140/packages/core/core/src/ReporterRunner.js#L86

And then when printing that error, it tries to load the reporters once again

**Comment by DeMoorJasper** [comment]
You're probably right @mischnic 

Does #6580 fix this problem @marcins ?

In the future we could maybe let reporters define which events they want to listen to to detect whether they can infinitely loop or not. Or some other solution, pretty hesitant to add another plugin type
