### ISSUE TITLE
How to import zepto?

### ISSUE THREAD

**Issue by njleonzhang** [parcel-bundler/parcel#656]
with webpack, `imports-loader` can be leverage to load this kind of legacy lib. How about parcel?

```
module: {
    rules: [
        {
            test: require.resolve('zepto'),
            use: 'imports-loader?this=>window'
        }
    ]
}
```

**Comment by dicklwm** [comment]
I have the same issue, but I build zepto by myself and import it to my project, this issue has resolve.
I think zepto npm package have no update. You can update it by youself
see [#1211](https://github.com/madrobby/zepto/pull/1211)

**Comment by njleonzhang** [comment]
yeah, I have already fix it too. Thanks anyway. @dicklwm

**Comment by l-hammer** [comment]
@njleonzhang Hi~ . 请问是如何解决的？我用的版本是v1.2.0~   谢谢~

**Comment by njleonzhang** [comment]
@l-hammer 

```
/* Zepto v1.2.0 - zepto event ajax form ie - zeptojs.com/license */
(function(global, factory) {
  if (typeof define === 'function' && define.amd)
    define(function() { return factory(global) })
  else
    factory(global)
}(this, function(window) {   // change this to window
```

**Comment by l-hammer** [comment]
@njleonzhang Thanks~ Thanks~ Thanks~
