### ISSUE TITLE
Comments aren't stripped

### ISSUE THREAD

**Issue by zigomir** [parcel-bundler/parcel#657]
🐛 bug report.

### 🎛 Configuration package.json

```sh
npx parcel build index.html
```

### 🤔 Expected Behavior

Production build should output smallest file possible.

### 😯 Current Behavior

In production build there still are my silly comments.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.5.0
| Node             | 8.9.4
| npm/Yarn         | npm 5.6.0
| Operating System | macOS 10.13.2

**Comment by DeMoorJasper** [comment]
Comments should get stripped from the build, as long as their is Not a `--no-minify` flag and there is no .uglifyrc file stating otherwise in your source

**Comment by zigomir** [comment]
Yeah, I have no `--no-minify` nor `.uglifyrc`.

**Comment by shawwn** [comment]
@zigomir I see. You're saying that `parcel build index.html` outputs a `dist/` folder that contains JS with comments?

**Comment by DeMoorJasper** [comment]
Any way u could provide us with a test repo to reproduce this as i've added this to the improved uglify test here (#662) as i was pretty sure it's getting removed, and it is according to the test

**Comment by zigomir** [comment]
Ha, interesting, looks like I've stumped on edge case :)

So, comments aren't removed whenever your `.js` or `.ts` file has only contents of like:

```js
// this comment will be in prod build
```

or
```js
// this comment will be in prod build
console.log('yo')
```

this is exactly what I was testing it with :) But I guess this really is an edge case.

so when I add something more meaningful to it, for example file looks like:

```js
// this comment will be in prod build
console.log('yo')
document.write('haha')
```

then prod build strips away everything except `document.write('haha')` which makes sense.

**Comment by DeMoorJasper** [comment]
@zigomir this might be an uglify bug (although a 2 line script won't really need minifying) is it fine if i close this?

**Comment by seethroughtrees** [comment]
FWIW, I've noted this same issue with flow type files.  I have 2 files that only contain exported types, and they were not being removed by babel when using parcel.  (with the flow preset).

(they were however being removed when I was using webpack).

after adding a document.write to test, the type content was removed as expected.  

not sure where the bug would be here, but just wanted to add this note in case someone is searching for flowtype issues.

**Comment by bledari** [comment]
I think this should be reopened. My CSS comments weren't deleted after building for production.

**Comment by jvanderen1** [comment]
I still see this issue as of `"parcel": "^2.0.0-nightly.980"`.
