### ISSUE TITLE
TypeScript's dynamic import() doesn't work in production build.

### ISSUE THREAD

**Issue by zigomir** [parcel-bundler/parcel#658]
🐛 bug report

### 🎛 cli command

```sh
npx parcel build index.html
```

### 🤔 Expected Behavior

```ts
import('./module').then(x => console.log(x))
```
should work the same in prod build as it does in dev build.

### 😯 Current Behavior

Works well in dev mode, but doesn't work at all with production build.

### 💻 Code Sample

```html
<html>
<body>
  <script src="./index.ts"></script>
</body>
</html>
```

```ts
import('./yo').then(x => {
  console.log(x.default)
})
```

`yo.ts`

```ts
export default 'hello from yo'
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.5.0
| Node             | 8.9.4
| npm/Yarn         | npm 5.6.0
| Operating System |

**Comment by zigomir** [comment]
Ah, same thing as in #657 because I'm only using `console.log` and uglifier or something strips it away. Sorry 😊

**Comment by davidnagli** [comment]
I couldn’t reproduce this 😬 

Are that you’re running the HTML file from `dist/`?

**Comment by DeMoorJasper** [comment]
@zigomir we changed the default behaviour in 1.5.1 to not strip away console.log, just so u know this is safe to use without a config now

**Comment by zigomir** [comment]
Perfect, now works as expected. Thanks!
