### ISSUE TITLE
Parcel 2: - Watch mode runtime-react-refresh invalid

### ISSUE THREAD

**Issue by DaveO-Home** [parcel-bundler/parcel#6586]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{ 
  "presets": ["@parcel/babel-preset-env", "@babel/preset-react", [
    "@babel/preset-env", {
      "targets": {
           "ie": 11,
          "browsers": ["> 0.2%, not dead, not op_mini all"]
      },
      "modules": false,
      "debug": false,
      "useBuiltIns": "usage",
      "corejs" : "3"
  }
  ]],
  "plugins": ["@parcel/babel-plugin-transform-runtime"]
}
```

## 🤔 Expected Behavior
A devserver @ 3080

## 😯 Current Behavior
DevServer fails - getting
```
404
Page not found.
```
Displaying in console:
```
[HPM] Proxy created: /dist_test/parcel/appl  -> http://localhost:3080
[HPM] Proxy rewrite rule created: "^/dist_test/parcel/appl" ~> ""
[HPM] Proxy created: /dist_test/parcel  -> http://localhost:3080
[HPM] Proxy rewrite rule created: "^/dist_test/parcel" ~> ""
```

Parcel is looking for a hashed runtime but file does not exist.

Note: if I include;
```
additionalReporters: [
           { packageName: "@parcel/reporter-cli", resolveFrom: __filename },
           { packageName: "@parcel/reporter-dev-server", resolveFrom: __filename }
        ],
```
I get two more of the same error plus
```
@parcel/reporter-dev-server: Trying to create the devserver but it already exists.
```

```
[Error: ENOENT: no such file or directory, open '/public/node_modules/@parcel/runtime-react-refresh/lib/runtime-84cceff3fa1cd9d3.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/public/node_modules/@parcel/runtime-react-refresh/lib/runtime-84cceff3fa1cd9d3.js'
}
```

## 💁 Possible Solution
None

## 🔦 Context

Setting up parcel for development...

## 🌍 Your Environment

I also have a .parcelrc file;
```
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.js": ["parcel-transformer-strip", "..."]
  }
}
```

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | nightly.767
| Node             | 16.4.0
| npm/Yarn         | 7.18.1
| Operating System | Linux Fedora34

**Comment by devongovett** [comment]
I think this is the same error as is fixed by https://github.com/parcel-bundler/parcel/pull/6584

**Comment by DaveO-Home** [comment]
verified - not sure if an auto-reload shou;d happen? - the browser console just says "console cleared" - have to manually refresh? Also, until there is a code change this shows in browser console - [parcel] 🚨 Connection to the HMR server was lost
