### ISSUE TITLE
parcel/config-webextension doesn't build the webextension but only converts the manifest.json into js

### ISSUE THREAD

**Issue by lhk** [parcel-bundler/parcel#6590]
# 🐛 bug report

I'd like to bundle a webextension with parcel. It should copy all the resources over to dist and transform the source files into bundles. But instead it produces a `manifest.js` from the `manifest.json`.

## 🎛 Configuration (.babelrc, package.json, cli command)
My parcel config:
```js
{
  "extends": "@parcel/config-webextension"
}
```

## 🤔 Expected Behavior

Parcel should copy over the `manifest.json` to `/dist.` All the` .ts `entries should be converted to `.js` bundles.

## 😯 Current Behavior

Parcel produces a `manifest.js` in` /dist`. This file is not usable.

## 🔦 Context

I'd like to build a webextension with react, typescript, firebase, ....
These frameworks are not new to me, I use them extensively in other projects.
And there I bundle the code with parcel, which by the way works like a charm :)

If possible I'd like to keep using the exact same toolchain for a webextension.

## 💻 Code Sample

To make reproducing the issue easier, I've created a boilerplate webextension with Mozilla's https://webextensions.in/
On top of that I've installed parcel and the webextension plugin.
You can check out the code here: https://github.com/lhk/parcel_webext
```

git clone git@github.com:lhk/parcel_webext.git
cd parcel_webext
npm i
parcel build src/manifest.json
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-beta.3.1
| @parcel/config-webextension           |2.0.0-beta.3.1
| Node             | v15.14.0
| npm/Yarn         |7.19.1
| Operating System | pop-os 20.10

**Comment by Bauke** [comment]
I got it working by using version `2.0.0-rc.0` for both `parcel` and `@parcel/config-webextension`.

**Comment by evgromov** [comment]
Same problem. Anyone found solutions?

**Comment by alishi973** [comment]
It seems you use the global `parcel` version instead of the `parcel` that was declared in your `package.json`.
I added `"build": "parcel build ./src/manifest.json"` in your scripts section and run build, then `manifest.json` is appear on `/dist` folder.
Maybe your global parcel was not the same version as the parcel in your `package.json`.

**Comment by 101arrowz** [comment]
This shouldn't be an issue on recent versions of Parcel, try updating to the latest version (or at least v2.5.0+) if you're still facing this.

**Comment by fregante** [comment]
This issue should be closed. 

If you’re seeing this issue:

- ensure that the parcel you’re calling is v2 or higher
- ensure that your parcel configuration file exists and is being read
