### ISSUE TITLE
Infinite build hang on `parcel serve` with .pug files in React project

### ISSUE THREAD

**Issue by TheNathanBlake** [parcel-bundler/parcel#6591]
# 🐛 bug report

Recently when attempting to run my project through `parcel serve ./src/index.pug`, I get a hanging build on a random JS file.

e.g.
```
ℹ️ Server running at http://localhost:1234
console: PUB_CONFIG::NODE_ENV=development
console: PUB_CONFIG::HOST_API=http://localhost:1234/
⠼ Building jss-plugin-nested.cjs.js...
```

Once I get this hangup, I cannot use Ctrl+C to terminate the build.  I have to close the terminal and open a new one.

In order to get a successful build again, I have to delete all my cache folders, restart my computer, and repeat that process until it succeeds again.  It will usually build successfully for a few runs until it repeats this bug.

## 🎛 Configuration (.babelrc, package.json, cli command)

No .babelrc specified

Package.json:
```json
{
  "name": "nable-web",
  "version": "1.0.0",
  "description": "",
  "browserslist": "> .5%, IE 9-11",
  "dependencies": {
    "@emotion/react": "^11.4.0",
    "@emotion/styled": "^11.3.0",
    "@material-ui/core": "^5.0.0-alpha.33",
    "@material-ui/icons": "^5.0.0-alpha.29",
    "@material-ui/styles": "^4.11.4",
    "aws-amplify": "^4.1.2",
    "dotenv": "^10.0.0",
    "formik": "^2.2.9",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-helmet": "^6.1.0",
    "react-router-dom": "^5.2.0",
    "react-native": "^0.56",
    "yup": "^0.32.9"
  },
  "devDependencies": {
    "@parcel/transformer-image": "^2.0.0-beta.3.1",
    "@parcel/transformer-pug": "^2.0.0-beta.3.1",
    "parcel": "^2.0.0-beta.3.1",
    "pug": "^3.0.2"
  },
  "scripts": {
    "start": "rm -rf dist && rm -rf .parcel-cache && mkdir -p dist && cp public/aws-exports.js dist && parcel serve ./src/index.pug",
    "build:dev": "NODE_ENV=dev parcel build ./src/index.pug --dist-dir dist/dev",
    "build:test": "NODE_ENV=test parcel build ./src/index.pug --dist-dir dist/test",
    "build:prod": "NODE_ENV=prod parcel build ./src/index.pug --dist-dir dist/prod",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

CLI command used: `npm start`

(No .babelrc or other babel config specified)

## 🤔 Expected Behavior

The project should build and the web app should be accessible on localhost:1234

## 😯 Current Behavior

The project hangs forever on any random .js file.

e.g.
```
ℹ️ Server running at http://localhost:1234
console: PUB_CONFIG::NODE_ENV=development
console: PUB_CONFIG::HOST_API=http://localhost:1234/
⠼ Building jss-plugin-nested.cjs.js...
```

## 💻 Code Sample

This .pug file may help?

```pug
doctype html
html(lang="")
    head
        script(src=HOST_API + 'exports.js')
    body
    div(id="root")
        script(src="index.jsx")
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.3.1
| Node             | v12.22.1
| npm/Yarn         | n/a
| Operating System | MacOS Catalina 10.15.7
| Processor        | 2.3 GHz Dual-Core Intel Core i5

**Comment by mischnic** [comment]
Can you test using it using
```json
    "@parcel/transformer-image": "2.0.0-nightly.2393",
    "@parcel/transformer-pug": "2.0.0-nightly.771",
    "parcel": "2.0.0-nightly.769",
```
(you'll have to add `type="module"` to the script tag)?

And maybe ty replacing the pug file with the equivalent HTML to see if it's really caused by pug itself.

**Comment by TheNathanBlake** [comment]
@mischnic Just tried building with the nightly builds of all 3 of those.  I'm currently getting the following error with both index.js and index.pug, and both lead to the same infinite loop.

This indicates it's likely not the .pug file causing the issue.  I'm still at a loss as to what might be causing this.

I've also modified the `npm start` command to include Parcel logs:
`"start": "rm -rf dist && rm -rf .parcel-cache && mkdir -p dist && cp public/aws-exports.js dist && parcel serve ./src/index.html --no-source-maps"`

Doing so revealed that the react-native version was out-of-sync with react, but otherwise no new logs after fixing that.

**Comment by TheNathanBlake** [comment]
Closing this until I have a better idea what is causing this issue
