### ISSUE TITLE
SVGs get their <style /> tag removed 

### ISSUE THREAD

**Issue by Matnard** [parcel-bundler/parcel#6592]
# 🐛 bug report

Processed SVGs loose styles

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"],
    "*.svg": ["@parcel/transformer-svg-react"]
  },
  "validators": {
    "*.{ts,tsx}": ["@parcel/validator-typescript"]
  }
}
```

## 🤔 Expected Behavior

Expecting styles being carried over

## 😯 Current Behavior

Styles are removed and the SVG doesnt look like how it should

## 💁 Possible Solution

A fix could be to allow a config file for the SVG optimizer

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by devongovett** [comment]
Do you have an example of an SVG that shows the issue?

**Comment by Matnard** [comment]
Thanks for the response.
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 258 144">
  <defs>
    <style>
      .cls-1 {
        fill: url(#linear-gradient);
      }

      .cls-2 {
        fill: none;
      }

      .cls-3 {
        fill: #fff;
      }
    </style>
    <linearGradient id="linear-gradient" x1="68.56" y1="-32.68" x2="195.42" y2="187.04" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#ff8a3f" />
      <stop offset="0.22" stop-color="#ff8740" />
      <stop offset="0.35" stop-color="#ff7f42" />
      <stop offset="0.47" stop-color="#ff7045" />
      <stop offset="0.57" stop-color="#ff5b4a" />
      <stop offset="0.66" stop-color="#fe4051" />
      <stop offset="0.75" stop-color="#fe2058" />
      <stop offset="0.82" stop-color="#fe0060" />
      <stop offset="1" stop-color="#fe0060" />
    </linearGradient>
  </defs>
  <title>aiplogogradient</title>
  <g id="Layer_1" data-name="Layer 1">
    <rect class="cls-1" width="258" height="144" />
    <rect class="cls-2" width="258" height="144" />
    <path class="cls-2" d="M194.45,37.3H177.6l-6.27,35.24H188.2c12.23,0,18.46-4.46,19.75-11.75L210,49.05C211.34,41.75,206.69,37.3,194.45,37.3Z" />
    <path class="cls-3" d="M92.19,28.59a2.65,2.65,0,0,0-.21-1,2.44,2.44,0,0,0-.62-.87,2.52,2.52,0,0,0-2-.65H73a4,4,0,0,0-2.28.69,3.84,3.84,0,0,0-1.45,1.87L31.31,115.41c-.82,1.71-.29,2.56,1.44,2.56h64c1.89,0,2.76-1,2.56-2.56Z" />
    <path class="cls-3" d="M141.7,26.09h-8.29c-1.75,0-2.57.79-2.9,2.71l-15.35,86.4c-.38,1.89.16,2.71,1.93,2.71h8.3c1.87,0,2.56-.79,2.9-2.71l15.34-86.4C144,26.91,143.63,26.09,141.7,26.09Z" />
    <path class="cls-3" d="M196.42,26.09h-27.6c-1.75,0-2.57.79-2.9,2.71l-15.25,86.4c-.38,1.89.16,2.71,1.93,2.71h8.3c1.87,0,2.56-.79,2.89-2.71l5.56-31.46h16.86c23.38,0,32.62-9.72,34.55-20.79l2.83-16.05C225.55,35.82,219.8,26.09,196.42,26.09Zm13.62,23L208,60.79c-1.29,7.29-7.52,11.75-19.75,11.75H171.33L177.6,37.3h16.85C206.69,37.3,211.34,41.75,210,49.05Z" />
  </g>
</svg>`

**Comment by Matnard** [comment]
yes sure here is one 
https://gist.github.com/Matnard/9f44bdfe111e71246652848e3e457da3

**Comment by mischnic** [comment]
This isn't caused by the svg optimizer but svgr's SVGO step:

https://github.com/parcel-bundler/parcel/blob/940f4fc91f9b3dadd024db9b3b566da1cf951a60/packages/transformers/svg-react/src/SvgReactTransformer.js#L30

**Comment by devongovett** [comment]
Does it get removed completely or inlined? I've seen SVGO inline styles into the elements that use them before, ie a fill attribute is added to all the places where the class names are used.

**Comment by mischnic** [comment]
Your example works correctly for me with the nightly versions

**Comment by Matnard** [comment]
Thanks @mischnic I'll give it a try with the nighly versions.
