### ISSUE TITLE
Parcel 2: parcel serve does not complete build phase

### ISSUE THREAD

**Issue by TheNathanBlake** [parcel-bundler/parcel#6598]
# 🐛 bug report

When running `parcel serve` on a MacBook with an Intel architecture, after a few successful runs, the build phase will hang for a while on building any random JS file, and then infinitely try to build one of the JS files.  Ctrl+C doesn't exit the process, but Parcel will ignore the interrupt to keep trying to build the file:

```js
Server running at http://localhost:1234
console: PUB_CONFIG::NODE_ENV=development
console: PUB_CONFIG::HOST_API=http://localhost:1234/
⠹ Building index.js...
⠸ Building index.js...
⠴ Building index.js...
⠦ Building index.js...
⠼ Building index.js...
⠴ Building index.js...
```

This behavior doesn't occur on MacBooks running the M1 processor.

This behavior also _sometimes_ doesn't occur on the Intel chip, but I've done everything I can to attempt to purposely duplicate this bug or prevent the bug, and have come to the conclusion that it happens when a cosmic ray doesn't hit the processor in the right way during the build.

## 🎛 Configuration (.babelrc, package.json, cli command)

Default Babel rules (no .babelrc specified)

package.json:
```json
{
  "name": "nable-web",
  "version": "1.0.0",
  "description": "",
  "browserslist": "> .5%, IE 9-11",
  "dependencies": {
    "@emotion/react": "^11.4.0",
    "@emotion/styled": "^11.3.0",
    "@material-ui/core": "^5.0.0-alpha.33",
    "@material-ui/icons": "^5.0.0-alpha.29",
    "@material-ui/styles": "^4.11.4",
    "aws-amplify": "^4.1.2",
    "dotenv": "^10.0.0",
    "formik": "^2.2.9",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-helmet": "^6.1.0",
    "react-router-dom": "^5.2.0",
    "yup": "^0.32.9"
  },
  "devDependencies": {
    "@parcel/transformer-image": "^2.0.0-beta.3.1",
    "@parcel/transformer-pug": "^2.0.0-beta.3.1",
    "parcel": "^2.0.0-beta.3.1",
    "pug": "^3.0.2"
  },
  "scripts": {
    "start": "rm -rf dist && mkdir -p dist && cp public/aws-exports.js dist && parcel serve ./src/index.pug",
    "build:dev": "NODE_ENV=dev parcel build ./src/index.pug --dist-dir dist/dev",
    "build:test": "NODE_ENV=test parcel build ./src/index.pug --dist-dir dist/test",
    "build:prod": "NODE_ENV=prod parcel build ./src/index.pug --dist-dir dist/prod",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

CLI command:
`npm start` (see package.json)

## 🤔 Expected Behavior

If everything's good, the web app starts.

## 😯 Current Behavior

The build step hangs on a JS file somewhere.

## 💁 Possible Solution

It has to be something architecture-specific.  My colleague is able to build and run the project flawlessly on the M1 MacBook with the same node, npm, parcel, and OS version.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.3.1
| Node             | 14.17.3
| npm/Yarn         | 6.14.13
| Operating System | Catalina 10.15.7

**Comment by devongovett** [comment]
Is there any way we can reproduce this? Do you have a code sample that shows the issue?

**Comment by wbinnssmith** [comment]
The M1 machines shipped with Big Sur. This case is from Catalina. Could be the OS version as well.
