### ISSUE TITLE
Neither bundle-analyzer or bundle-buddy seem to be working 

### ISSUE THREAD

**Issue by damianobarbati** [parcel-bundler/parcel#6599]
Running either of:
```sh
parcel build app/index.html --no-cache --no-autoinstall --no-source-maps --reporter @parcel/reporter-bundle-analyzer

parcel build app/index.html --no-cache --no-autoinstall --no-source-maps --reporter @parcel/reporter-bundle-buddy
```

as mentioned in <https://v2.parceljs.org/features/production/> I don't see any `parcel-bundle-reports` directory being generated.

Am I missing something stupid here?

## 🌍 Your Environment

- node v16.4
- "@parcel/reporter-bundle-analyzer": "^2.0.0-nightly.1694"
- "@parcel/reporter-bundle-buddy": "^2.0.0-nightly.1902"
- "parcel": "^2.0.0-beta.1"
- "parcel-reporter-static-files-copy": "^1.3.0"

`.parcelrc`: 
```json
{
    "extends": ["@parcel/config-default"],
    "reporters":  ["...", "parcel-reporter-static-files-copy"],
    "transformers": {
        "*.md": ["@parcel/transformer-raw"],
        "*.png": ["@parcel/transformer-raw"]
    }
}
```

**Comment by ptitjes** [comment]
It seems it is not in the v2 documentation, or at least I did not find any mention of it, but you have to add a `PARCEL_BUNDLE_ANALZYZER=1` environment variable to your parcel command-lines.

**Comment by damianobarbati** [comment]
@ptitjes it works, thanks!

**Comment by damianobarbati** [comment]
@ptitjes it is it configurable to show human size values instrad of bytes? Are you actually using it as it is or do you use `buddy`?

**Comment by ptitjes** [comment]
I have no idea, sorry. I use the `reporter-bundle-analyzer` but did not try `buddy`.
