### ISSUE TITLE
🐛 I'd like my console.log statements to stay intact please 😅

### ISSUE THREAD

**Issue by HenrikJoreteg** [parcel-bundler/parcel#660]
🐛  report

even with a .uglifyrc that looks like:

```
{
  "compress": {
    "drop_console": false
  }
}
```

It still seems to strip `console.log` statements when I run `parcel build` through the CLI.

As an example, pull [the console branch of this repo](https://github.com/HenrikJoreteg/redux-bundler-example/tree/console) and run `npm run build`. 

The code that ends up in `dist` does not include any `console.log`

It causes no errors, just doesn't seem to pick up the config file at all.

Love parcel though ❤️

**Comment by devongovett** [comment]
hmm, seems like the test for this is actually wrong 🤦‍♂️ https://github.com/parcel-bundler/parcel/blob/master/test/javascript.js#L257 Should be asserting the inverse I think according to https://github.com/parcel-bundler/parcel/blob/master/test/integration/uglify-config/.uglifyrc#L3. Maybe the config isn't getting merged properly? cc @DeMoorJasper 

We could also consider making this the default. We probably shouldn't be doing unsafe optimizations like this by default. WDYT?

**Comment by DeMoorJasper** [comment]
Changed the test and default behaviour a bit, the test wasn't incorrect as far as i've looked through it. (see #662 )
I'll test out the branch Henrik provided and try to find where the config is failing. (As config appears to be working inside the test)

**Comment by devongovett** [comment]
Should be fixed by #662.

**Comment by HenrikJoreteg** [comment]
@devongovett @DeMoorJasper thanks! ❤️
