### ISSUE TITLE
`--out-dir`  returns `error: unknown option '--out-dir'

### ISSUE THREAD

**Issue by RichardJECooke** [parcel-bundler/parcel#6601]
# 🐛 bug report

This command `npx parcel build src/index.html --out-dir output` gives the error `error: unknown option '--out-dir'`

## 🤔 Expected Behavior

According to `https://parceljs.org/cli.html` this command should be a valid option `parcel build entry.js --out-dir build/output`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.0-nightly.548
| Node             |  v14.15.4
| npm/Yarn         | npm 
| Operating System | WSL

**Comment by DeMoorJasper** [comment]
It has been renamed to `--dist-dir` in Parcel v2, you can find the documentation for it here: https://v2.parceljs.org/features/cli/
