### ISSUE TITLE
Import axios not working 

### ISSUE THREAD

**Issue by skandasoft** [parcel-bundler/parcel#6612]
# 🐛 bug report

parcel build command doesn't seem to add the Axios library properly, though it seems to be working fine in start script in npm (parcel src/index.html).

Link to the issue ..
https://distracted-babbage-340f4c.netlify.app/github-profile/index.html

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
  "build": "parcel build src/index.html --no-cache ",

## 🤔 Expected Behavior

Pick AXIOS

## 😯 Current Behavior

Not Picking up axios

## 🔦 Context

Import Axios

## 💻 Code Sample

https://distracted-babbage-340f4c.netlify.app/github-profile/index.html

## 🌍 Your Environment

    "@parcel/transformer-sass": "^2.0.0-beta.2",
    "cssnano": "^5.0.6",
    "parcel": "*",

**Comment by devongovett** [comment]
Please try the latest nightly release. Axios should be working.

**Comment by skandasoft** [comment]
× Build failed.
@parcel/package-manager: Could not find module "@parcel/transformer-sass" satisfying 2.0.0-beta.3.1.
C:\Users\manic\exercise\50-days\github-profile\package.json:17:5
  16 |   "devDependencies": {
> 17 |     "@parcel/transformer-sass": "^2.0.0-beta.3.1",
>    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^ Found this conflicting local requirement.
  18 |     "cssnano": "^5.0.6",
  19 |     "parcel": "^2.0.0-beta.3.1",

**Comment by skandasoft** [comment]
× Build failed.
@parcel/package-manager: Could not find module "@parcel/transformer-sass" satisfying 2.0.0-beta.3.1.
C:\Users\xxx\github-profile\package.json:17:5
  16 |   "devDependencies": {
> 17 |     "@parcel/transformer-sass": "^2.0.0-beta.3.1",
>    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^ Found this conflicting local requirement.
  18 |     "cssnano": "^5.0.6",
  19 |     "parcel": "^2.0.0-beta.3.1",

**Comment by skandasoft** [comment]
"parcel": "^2.0.0-beta.3" looks good
