### ISSUE TITLE
The optimizer doesn't run anymore in the latest nightly

### ISSUE THREAD

**Issue by aminya** [parcel-bundler/parcel#6633]
# 🐛 bug report

I have faced a strange issue when I use `npm` as the package manager. The following command doesn't run the optimizer anymore. This works in Parcel nightly 760, but not in 776.
```
cross-env NODE_ENV=production parcel build --target main ./src/terminal.ts
```

To reproduce, update parcel in this PR to the latest nightly and run `npm run build`.
https://github.com/atom-community/terminal/pull/86

## 🎛 Configuration (.babelrc, package.json, cli command)

I use a custom `.terserrc`.

Here is the targets:
```json
  "targets": {
    "main": {
      "context": "electron-renderer",
      "includeNodeModules": {
        "atom": false,
        "electron": false,
        "node-pty-prebuilt-multiarch": false
      },
      "isLibrary": true
    }
  }
```

## 🤔 Expected Behavior
Optimize

## 😯 Current Behavior

Doesn't optimize

## 💁 Possible Solution

1) Downgrade to 760
2) use pnpm

## 💻 Code Sample

https://github.com/atom-community/terminal/tree/parcel-update

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0 Nightly 776
| Node             | 16
| npm/Yarn         | npm 6
| Operating System | Win 11

**Comment by devongovett** [comment]
We changed the default for libraries to not be minified in #6570 since it's fairly rare. You should be able to add the `"optimize": true` option to your target config if you do want minification.

**Comment by aminya** [comment]
Hmm, that was surprising. Not sure if there is a good correlation between a being library and not having optimizations. The various optimizations that are applied to the code can improve the performance of the users of that library.

**Comment by aminya** [comment]
What if you just deprecate the `isLibrary` option and use a more descriptive name that means "no bundling, no optimization"?

**Comment by devongovett** [comment]
"optimizations" in this case just means minification, it shouldn't affect runtime performance aside from number of bytes I think. Most libraries you'd find on npm aren't minified.

**Comment by aminya** [comment]
This should be documented in the docs. 
https://v2.parceljs.org/getting-started/library/
