### ISSUE TITLE
How create bundle es6 with export default ?

### ISSUE THREAD

**Issue by zababurinsv** [parcel-bundler/parcel#6636]
# 🙋 feature request

i have this structure
```
| -node_modules
| -src
------- index.mjs
         import some-function from 'node_modules'
         export default () => {}
| package.json
```
## 🤔 Expected Behavior

How to do the following.

* parcel ./src/index.mjs
* out -> bundle.index.mjs

and in index.html
```
<script type = "module">
import * as bundle from "./path to file"
</script>
```

## 😯 Current Behavior

When i run parcel build ./src/index.mjs i get js file. But there is no export deafult in this file
  
I cannot connect this bundle in the client project.

i see in bundle require

```
function e(e){return e&&e.__esModule?e.default:e}var r=e(*require("@orbit/db")*),t=e(require("ipfs-core"));let i=r;exports.orbitdb=i;let u=t;exports.ipfs=u;exports.default={author:"Zababurin Sergey",license:"GPL-3.0-or-later",bugs:{url:"https://github.com/zababurinsv/template/issues",mail:"s.zababurin.v@gmail.com"}};
```

## 💁 Possible Solution

I am building bundle now using webpack
ma by can i get module to out ? 

## 🔦 Context

```
And i can set  *.mjs in `main:"index.mjs"` in package.json it is get error.


parcel build ./public/index.mjs   --no-content-hash --no-source-maps

🚨 Build failed.
@parcel/namer-default: Target "main" declares an output file path of "index.mjs" which does not match the compiled bundle type "mjs".
/home/zb/Desktop/socket/bundle/orbit-db/package.json:11:11
  10 |   },
> 11 |   "main": "index.mjs",
>    |           ^^^^^^^^^^ Did you mean "index.js"?
  12 |   "repository": {
  13 |     "type": "git",
Try changing the file extension of "main" in package.json.

```

**Comment by devongovett** [comment]
> And i can set  *.mjs in `main:"index.mjs"` in package.json it is get error.

This should be fixed in the latest nightly build. We made some changes to allow the `.mjs` extension. This should also correctly infer the output format as well.
