### ISSUE TITLE
Version 2 beta 3 doesn't transpile ESM imports in Web Workers anymore

### ISSUE THREAD

**Issue by Ayc0** [parcel-bundler/parcel#6639]
# 🐛 Bug Report

When loading https://ayc0.github.io/color-visualizer/ in browsers **different** than chrome, I have those errors:
- in safari: `SyntaxError: Unexpected string literal "./index.cf68cd7c.js". import call expects exactly one argument.`,
- and in Firefox: `SyntaxError: import declarations may only appear at top level of a module`.

I think it comes from this file: `view-source:https://ayc0.github.io/color-visualizer/generate-colors.worker.0bf242fc.js` where an ESM `import` statement is still present in the compiled file.

My guess on this is that parcel (starting from the beta 2 beta 3 with swc) doesn't properly compiles ESM files in *WebWorker*

## 🎛 Configuration (.babelrc, package.json, cli command)

As I moved to 2 beta 3, I no longer have a .babelrc file, but this is my parcel file:

```json
{
    "extends": "@parcel/config-default",
    "transformers": {
      "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
    }
  }
```

## 🤔 Expected Behavior

Just  as `<script type="module" src="./src/index.ts"></script>` transform the ESM source file to a UMD bundle, I'd also have expected `new Worker(...., { type:'module'})` to convert the ESM source file to a UMD worker bundle. (just like what the v2 beta 2 was doing)

## 😯 Current Behavior

- in safari: `SyntaxError: Unexpected string literal "./index.cf68cd7c.js". import call expects exactly one argument.`,
- and in Firefox: `SyntaxError: import declarations may only appear at top level of a module`.

(no stack trace for any of those)

## 💁 Possible Solution

I have no idea, sorry :/ 

## 🔦 Context

I'm trying to load a local file in a web worker with:

```js
new Worker(new URL("./generate-colors.worker", import.meta.url), {
    type: "module",
  });
```

When the other file uses ESM + imports a node module

## 💻 Code Sample

You can see the full code here: https://github.com/Ayc0/color-visualizer/, but this line that seems to be causing the bug is this one:
https://github.com/Ayc0/color-visualizer/blob/89a2e6fb6a4638483aad7a8ff909ac5c37a1fc38/src/LCHPaint/generate-colors/index.ts#L2. This line + this file: https://github.com/Ayc0/color-visualizer/blob/89a2e6fb6a4638483aad7a8ff909ac5c37a1fc38/src/LCHPaint/generate-colors/generate-colors.worker.ts (the one used in the web-worker that imports an NPM package)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.3.1 |
| Node             | 16 |
| npm/Yarn         | yarn 1.22.10 |
| Operating System | macOS |

**Comment by devongovett** [comment]
Please try the latest nightly version. A lot of changes related to ESM workers have gone in since the beta.

**Comment by Ayc0** [comment]
It indeed fixed it!
Thanks 🙇
