### ISSUE TITLE
API usage:  TypeError: Parcel is not a constructor

### ISSUE THREAD

**Issue by ivoba** [parcel-bundler/parcel#6659]
# 🐛 bug report

When using Parcel V2 as API: https://v2.parceljs.org/features/parcel-api/ an error is thrown:
 TypeError: Parcel is not a constructor

## 🎛 Configuration (.babelrc, package.json, cli command)

My node version is v14.16.1 on Ubuntu.

```js
{
    "@parcel/config-default": "^2.0.0-nightly.778",
    "@parcel/core": "^2.0.0-nightly.776",
}
```

## 🤔 Expected Behavior

Parcel should generate the HTML file

## 😯 Current Behavior

Error is thrown on instanciation:

node lib/html.mjs
(node:23764) UnhandledPromiseRejectionWarning: TypeError: Parcel is not a constructor
    at file:///home/ivo/Sites/audiomoth-zx/lib/html.mjs:9:18
    at file:///home/ivo/Sites/audiomoth-zx/lib/html.mjs:32:3
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23764) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

## 💻 Code Sample

html.mjs
```js
'use strict';

import path from "path"
import Parcel from "@parcel/core"
import { createRequire } from 'module';
const require = createRequire(import.meta.url);

(async () => {
  const parcel = new Parcel({
    entries: "../views/index.html",
    defaultConfig: require.resolve("@parcel/config-default"),
    logLevel: 'verbose',
    targets: {
      default: {
        distDir: "../dist",
        distEntry: 'index.html',
        source: "../views/index.html",
        outputFormat: "esmodule"
      },
    },
    mode: "production",
  })

  await parcel.run().catch(err => console.log(err))
  console.log('end')
})();
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-nightly.776
| Node             | v14.16.1
| npm/Yarn         |
| Operating System | Ubuntu

**Comment by mischnic** [comment]
`import Parcel from "@parcel/core"` only works in Babel-flavoured ESM, not in Node directly. You probably have to use `new Parcel.default()` (or `const {default: Parcel} = require("@parcel/core")` with `new Parcel()`)

**Comment by ivoba** [comment]
@mischnic Thanks.
So i cant use Parcel API in node ES6 modules, *.mjs? It seems they dont support require, only import statements.

I reworked the script and now use require.
(Note: a semicolon was neccessary after the require statement, which i had not, see: https://stackoverflow.com/a/54998594/541949)
node lib/html.js:

```
'use strict';

const Parcel = require('@parcel/core').default;

(async () => {
  const parcel = new Parcel({
    entries: "../views/index.html",
    defaultConfig: require.resolve("@parcel/config-default"),
    logLevel: 'verbose',
    targets: {
      default: {
        distDir: "../dist",
        distEntry: 'index.html',
        source: "../views/index.html"
      },
    },
    mode: "production",
  })

  await parcel.run().catch(err => console.log(err))
  console.log('end')
})();

```

But still no output nor generated files.
Probably some swallowed seg fault somewhere?

**Comment by mischnic** [comment]
Add `additionalReporters: [{packageName: '@parcel/reporter-cli', resolveFrom: __filename}]` as an option to the constructor argument

**Comment by ivoba** [comment]
Yep, thank you.
That showed the reasons why it failed and i was able to fix it.
Works now.
