### ISSUE TITLE
how to change default parse action on @

### ISSUE THREAD

**Issue by wangjie-fourth** [parcel-bundler/parcel#6660]
### Discussed in https://github.com/parcel-bundler/parcel/discussions/6653

<div type='discussions-op-text'>

<sup>Originally posted by **wangjie-fourth** July 28, 2021</sup>
In my project, @ is used a lot to indicate the src location of the project. E.g:
```javascript
import request from '@/utils/request'
// is mean to
import request from './src/utils/request'
```

now, i wan to use parcel to build this project for unit test.but fail with
```shell
 Cannot resolve dependency '@/utils/request'
> 1 | import request from '@/utils/request'
```

I read the document that @ means npm package.So, is any way to change @ default parse action? Or, any way to slove this probelm?
Thanks in advance</div>

**Comment by mischnic** [comment]
Does adding `alias: { '@': "./src/' }`  to your package.json work?

**Comment by wangjie-fourth** [comment]
> Does adding `alias: { '@': "./src/' }` to your package.json work?

i tried before,but it didn't work

**Comment by devongovett** [comment]
You're going to need to give us more information about what went wrong if we are to help you.

**Comment by wangjie-fourth** [comment]
thanks for your help. i create [demo](https://github.com/wangjie-fourth/parcelDemo) to show the problem.

**Comment by devongovett** [comment]
`@` can't be used as an alias because it is a special symbol that indicates an npm organization.

**Comment by mischnic** [comment]
Does Webpack or Rollup support `@` as an alias?

**Comment by wangjie-fourth** [comment]
I understand @ indicates an npm organization.I'm just consider how to change default parse action on @? For example, first search according to the src directory, if not found, then load the npm package.

**Comment by wangjie-fourth** [comment]
> Does Webpack or Rollup support `@` as an alias?

Yes, but webpack needs to be configured to support.you can see [here](https://github.com/wangjie-fourth/parcelDemo/blob/main/build/webpack.dev.conf.js#L19)

**Comment by suhaotian** [comment]
@wangjie-fourth I change my project `@` to `~`, it works

`package.json`:
![2021-10-14 at 1 18 PM](https://user-images.githubusercontent.com/6512574/137256299-f99c1ca7-a4d9-415e-8c6f-910f681a7f1c.png)

`tsconfig.json`:
![2021-10-14 at 1 18 PM](https://user-images.githubusercontent.com/6512574/137256344-83adc9e2-9954-43bd-bb44-cb841543a740.png)

**Comment by suhaotian** [comment]
https://github.com/suhaotian/parcel-starter

check the starter, work perfect

**Comment by wangjie-fourth** [comment]
@suhaotian thanks, it look great. i will try on it
