### ISSUE TITLE
[2.0.0-nightly.792] `parcel serve` doesn't serve all the built artifacts

### ISSUE THREAD

**Issue by ptitjes** [parcel-bundler/parcel#6669]
# 🐛 bug report

When using `parcel serve`, only the html file seems to be served, despite all the artifacts are correctly built (css, js, ...).

## 🎛 Configuration (.babelrc, package.json, cli command)

Simple project with no `.parcelrc`, no babel configuration...

The command being used is:
```sh
parcel serve -p 3000 src/index.html --target browser --dist-dir build --public-url ./
```

## 🤔 Expected Behavior

`parcel serve` should also serve the built css and js files.

## 😯 Current Behavior

Chrome reports two 404 for the css and js files:

```
GET http://localhost:3000/index.566391a6.css net::ERR_ABORTED 404 (Not Found)
GET http://localhost:3000/index.8dff9d2c.js net::ERR_ABORTED 404 (Not Found)
```

## 💻 Code Sample

A simple reproduction repository:
https://github.com/ptitjes/test-parcel-2.0.0-beta.3.1
which despite its name uses parcel 2.0.0-nightly.792.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.792 |
| Node             | v14.17.0 |
| npm/Yarn         | Yarn 1.22.10 |
| Operating System | Fedora Linux 34 |

**Comment by devongovett** [comment]
I think this is related to your other issue – you're using a library target but trying to load it directly in the browser.

**Comment by ptitjes** [comment]
@devongovett so I changed the target name to 'app' and the outputFormat to 'esmodule' as advised in https://github.com/parcel-bundler/parcel/issues/6670. But this does not fix this issue.

I updated https://github.com/ptitjes/test-parcel-2.0.0-beta.3.1.

When I run
```
parcel serve -p 3000 src/index.html --target app --dist-dir build --public-url ./
```

In Chrome, I get:
```
index.566391a6.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
index.605d3bfc.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
favicon.ico:1 Failed to load resource: the server responded with a status of 404 (Not Found)
index.566391a6.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

Whereas, if I `npx http-server build/`, everything goes well (without HMR obviously).

**Comment by devongovett** [comment]
Seems to be caused by `--public-url ./`. Removing that (or using `/` which is the default) works. What was the reason for using a relative path?

**Comment by ptitjes** [comment]
Hmm, I must say I can't remember exactly. All this is copied from one of our production Electron app. I think it made sense at some point... Indeed, removing the `--public-url ./` fixes the problem. So I will also close this issue. (Sorry for the noise...)

Just to clarify, can you please validate the use of the `--public-url` option for:
- `parcel build` with a browser/electron-renderer target needs `--public-url ./`
- `parcel serve` with a browser/electron-renderer target needs `--public-url /`
- `parcel build` with a main/electron-main target needs no `--public-url`
- `parcel watch` with a main/electron-main target needs no `--public-url`

@devongovett Thanks a lot for your help. I <3 Parcel!
