### ISSUE TITLE
🙋Feature request: Add support for directory watching

### ISSUE THREAD

**Issue by asv1** [parcel-bundler/parcel#667]
Currently, parcel can import recursive all files in folder (ex: require('./folder/*')). But it doesn't rebuild file that imports directory when a new file is created in directory.

It is useful with Vue single component files. For every new created component I must restart parcel myself.

[In webpack it called Require.context](https://webpack.js.org/guides/dependency-management/#require-context)

**Comment by shawwn** [comment]
Thank you! I agree, this should happen for our new Vue support. (Were you referring to it? https://github.com/parcel-bundler/parcel/issues/5#issuecomment-359168173)

If you still have to restart Parcel while using that, let me know and I'll make sure it's solid for our next release.

**Comment by asv1** [comment]
It is more about general support at parcel core for watching folder.

**Comment by shawwn** [comment]
Ah, yes agreed. Thanks!

**Comment by devongovett** [comment]
The start of this happened in https://github.com/parcel-bundler/parcel/pull/1279

**Comment by mischnic** [comment]
Should have been fixed in 1.12.0: https://github.com/parcel-bundler/parcel/pull/2615
