### ISSUE TITLE
[2.0.0-nightly.792] `parcel build` adds CSS `import` to the built JS file

### ISSUE THREAD

**Issue by ptitjes** [parcel-bundler/parcel#6670]
# 🐛 bug report

Use a CSS `import` from Typescript file:

```ts
import '@rmwc/button/styles';

import React from 'react';
import ReactDOM from 'react-dom';

import { Button } from '@rmwc/button';

start();

export function start(): void {
  ReactDOM.render(<App/>, document.getElementById('root'));
}

function App() {
  return (
    <Button>
      Test
    </Button>
  );
}
```

When you build, the `import` is also generated at the start of the built JS file:

```js
import "./index.139f26b2.css";

function $parcel$interopDefault(a) {
[...]
```

## 🎛 Configuration (.babelrc, package.json, cli command)

Simple project with no .parcelrc, no babel configuration...

The command being used is:
```sh
parcel build src/index.html --target browser --dist-dir build --public-url ./
```

## 🤔 Expected Behavior

I believe that no CSS `import` should be put in the built JS file.

## 😯 Current Behavior

As the `import` is added to the beginning of the JS file, this file loads with an error in Chrome:
```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
```

## 💻 Code Sample

A simple reproduction repository:
https://github.com/ptitjes/test-parcel-2.0.0-beta.3.1
which despite its name uses parcel 2.0.0-nightly.792.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.792
| Node             | v14.17.0
| npm/Yarn         | Yarn 1.22.10
| Operating System | Fedora Linux 34

**Comment by devongovett** [comment]
The "browser" target is meant for libraries (i.e. you would publish to npm). If you meant to build an app, you should choose a different name.

I noticed you were using `"outputFormat": "commonjs"` though so now I am uncertain. CommonJS output only works in node or when building libraries, not directly in the browser. Are you trying to build a library or an app?

**Comment by ptitjes** [comment]
@devongovett thx for your very fast answer!

I define the target `browser` at the end of the `package.json` with context `browser`. I though that the important thing was the `context` referenced in the target definition (which here needs to be `browser`, right ?).

Do you mean that there are some reserved target names ? If that is the case, maybe the documentation should be clarified.

Indeed, I renamed the target `app` and the build goes well and does not add the `import` to the built JS file. I am closing the issue. Tell me if you want a contribution to clarify the documentation.

**Comment by mischnic** [comment]
> If that is the case, maybe the documentation should be clarified.

https://v2.parceljs.org/configuration/package-json/#main-%2F-module-%2F-browser

**Comment by ptitjes** [comment]
> https://v2.parceljs.org/configuration/package-json/#main-%2F-module-%2F-browser

Yes, I find this page really confusing. There is confusion between target names and contexts. And no explicit mention that indeed the three common package.json fields (`browser`, `main` and `module`) are reserved target names with strict pre-configuration. I am willing to propose/contribute some changes, if you feel like it.

**Comment by devongovett** [comment]
I was working on updating the docs about targets yesterday. Will have a PR soon.
