### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by andreyvital** [parcel-bundler/parcel#6677]
# 🐛 $f2f621353cc7e435$var$document is not defined

For some reason, when I compile with optimizations and scope hoisting, it produces the following error on **slate** with **slate-react**:

<img width="571" alt="Screen Shot 2021-08-03 at 10 57 05" src="https://user-images.githubusercontent.com/967317/128041313-d87439c0-c6b5-4a9c-95a7-8330827011f7.png">
<img width="976" alt="Screen Shot 2021-08-03 at 10 57 20" src="https://user-images.githubusercontent.com/967317/128041324-ce4095bd-1457-4698-89af-1617b321620f.png">

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// .babelrc
{
  "presets": ["@babel/typescript", "@emotion/babel-preset-css-prop"]
}

// .parcelrc
{
  "extends": [
    "@parcel/config-default"
  ],
  "reporters": [
    "...",
    "parcel-reporter-static-files-copy"
  ]
}

// package.json
"@babel/preset-typescript": "^7.12.1",
"@emotion/babel-preset-css-prop": "^10.0.27",

"@parcel/config-default": "^2.0.0-rc.0",
"parcel": "^2.0.0-rc.0",
"parcel-reporter-static-files-copy": "^1.3.0",
```

## 💁 Possible Solution

If I use `parcel build --no-scope-hoist --no-optimize` it doesn't produce the error. I don't know what's causing this but I'm pretty sure it's related to the optimization/hoisting process. I've also tried without one of the flags:

1. If I remove `--no-scope-hoist` *it still produces the error*;
2. If I remove `--no-optimize` *it still produces the error*.

**Comment by devongovett** [comment]
Do you have a code sample to reproduce this?
