### ISSUE TITLE
npm organization "@" results in "Cannot find module"

### ISSUE THREAD

**Issue by btkostner** [parcel-bundler/parcel#668]
this a 🐛 bug report
**NOTE**: This is using the `vue` branch

### 🎛 Configuration (.babelrc, package.json, cli command)

`.babelrc`
```
{
  "presets": ["env"]
}
```

`package.json`
```
{
  "name": "banshee",
  "version": "0.0.1",
  "main": "index.js",
  "license": "UNLICENSED",
  "scripts": {
    "start": "parcel src/index.html",
    "build": "parcel build src/index.html",
    "test": "ava"
  },
  "devDependencies": {
    "ava": "^0.24.0",
    "babel-preset-env": "^1.6.1",
    "cssnext": "^1.8.4",
    "parcel-bundler": "parcel-bundler/parcel#vue",
    "postcss-cssnext": "^3.1.0",
    "vue": "^2.5.13",
    "vue-component-compiler": "git+https://github.com/shawwn/vue-component-compiler.git#parcel-vue-component-compiler",
    "vue-router": "^3.0.1",
    "vue-template-compiler": "^2.5.13",
    "vuex": "^3.0.1",
    "vuex-router-sync": "^5.0.0"
  }
}
```

Package in question is linked locally with `npm link @system76/tachi`

Command Ran: `npm start` -> `parcel src/index.html`

### 🤔 Expected Behavior

Using an organization package does the same thing as a normal package

### 😯 Current Behavior

Running any parcel command with `import tachi from '@system76/tachi'` results in `Cannot find module '' from '/media/btkostner/bed36712-92fb-421c-86c3-7eaae27c0bb5/Projects/system76/banshee/src/store'`

This also happens if I switch it to another npm organization package I have installed like `@ava/write-file-atomic/index.js`.

This _does not_ happen with any other regular module import like `import test from 'ava'` or `import Vue from 'vue'`.

### 💻 Code Sample

`npm install ava`

```
import * as test from '@ava/write-file-atomic/index.js'
// Fails before getting to console log
console.log(test)
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |   "_from": "github:parcel-bundler/parcel#vue",  "_id": "parcel-bundler@1.4.1",
| Node             | v8.9.4 with nvm
| npm/Yarn         | npm 5.6.0
| Operating System | elementary OS Loki

**Comment by DeMoorJasper** [comment]
@shawwn this might be related to vue

**Comment by btkostner** [comment]
I can confirm, does not happen on the released `npm` version, just the `vue` branch

**Comment by inad9300** [comment]
I seem to be experiencing the same problem without using Vue. I'm importing [@soil/dom](https://www.npmjs.com/package/@soil/dom) and get the error `Error: Cannot find module './html/h'` when trying to do `import {h} from '@soil/dom'`.

**Comment by DeMoorJasper** [comment]
@inad9300 this doesn't seem to be related, wanna open up a seperate issue. I'll close this one, as Vue has been implemented and `@...package` should already be supported
