### ISSUE TITLE
Error: No native build was found on Docker node:16-alpine environment

### ISSUE THREAD

**Issue by krnlde** [parcel-bundler/parcel#6680]
# 🐛 bug report

When trying to run Parcel in a docker `FROM node:16-alpine` image I get the following since after the last `2.0.0-beta.3.1`:
```
#54 7.303 $ cross-env NODE_ENV=production parcel build frontend/app/index.html --dist-dir frontend/app/build --no-source-maps --no-scope-hoist
#54 7.816 Error: No native build was found for platform=linux arch=x64 runtime=node abi=93 uv=1 libc=musl node=16.6.0
#54 7.816     loaded from: /app/node_modules/lmdb-store
#54 7.816
#54 7.816     at Function.load.path (/app/node_modules/node-gyp-build/index.js:59:9)
#54 7.816     at load (/app/node_modules/node-gyp-build/index.js:21:30)
#54 7.816     at Object.<anonymous> (/app/node_modules/lmdb-store/index.js:7:49)
#54 7.816     at Module._compile (/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
#54 7.816     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
#54 7.816     at Module.load (node:internal/modules/cjs/loader:981:32)
#54 7.816     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
#54 7.816     at Module.require (node:internal/modules/cjs/loader:1005:19)
#54 7.816     at require (/app/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
#54 7.816     at _lmdbStore (/app/node_modules/@parcel/cache/lib/LMDBCache.js:31:39)
#54 7.956 error Command failed with exit code 1.
#54 7.957 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c yarn build]: exit code: 1
```

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json looks unsuspicious:
```json
{
  "scripts": {
    ...
    "build": "cross-env NODE_ENV=production parcel build frontend/app/index.html --dist-dir frontend/app/build --no-source-maps --no-scope-hoist",
    ...
  },
  ...
  "devDependencies": {
    ...
    "@parcel/transformer-sass": "2.0.0-nightly.795",
    "@parcel/transformer-svg-react": "2.0.0-nightly.2417",
    "@parcel/transformer-svgo": "2.0.0-nightly.2358",
    ...
  }
```
.parcelrc:
```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.svg": ["@parcel/transformer-svgo", "@parcel/transformer-svg-react"]
  }
}
```

I think the last working nightly version was `2.0.0-nightly.679` (at least somewhere around there).

## 🤔 Expected Behavior

It should build on `node:alpine-16` environment

## 🌍 Your Environment

As mentioned, it worked with beta.3.1 and some nightlies after that. It stopped working somewhere around  `2.0.0-nightly.679`.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-rc.0
| Node             | 16.6.0
| npm/Yarn         |  7.19.1/1.22.5
| Operating System | Docker node:alpine-16

**Comment by devongovett** [comment]
Maybe an issue with the [lmdb-store](https://github.com/DoctorEvidence/lmdb-store) module? Not sure what prebuilds they distribute. I'm a little surprised that it didn't get compiled on install though. Did you get any errors during npm/yarn install?

**Comment by krnlde** [comment]
At least I don't see any. Should I open an issue at lmdb-store itself? They don't seem to have an issue regarding this bug yet.

**Comment by devongovett** [comment]
Can you try installing lmdb-store by itself in your environment and then try to require it in the node repl? If that is broken, then you should file an issue there. Thanks!

**Comment by krnlde** [comment]
As you suggested, it also fails. I'll close this one here and open it over there. Thank your for the fast response!

**Comment by willstott101** [comment]
Should this really be closed? It seems to me like this affects parcel quite considerably and it makes sense to keep it open until parcel works in alpine docker out the box. The downstream issue suggested having the docker container build lmdb on each install but that seems pretty sub-optimal to me...

**Comment by krnlde** [comment]
The issue only occurs if you make use of `--ignore-scripts`. But you shouldn't use that anyways as I learned the hard way last week.

**Comment by willstott101** [comment]
Having to build a c++ project during installation of an npm package seems sensible to you? The _issue_ in my opinion is that there's no pre-built binary.

**Comment by krnlde** [comment]
No, but what makes sense was not the issue here. I would open that feature request at lmdb-store itself

**Comment by mountainash** [comment]
Can across this when trying to run `parcel@2.6.2` on `node:18-alpine`. After much reading and failed builds, my working local Dockerfile is: 
```
FROM node:18-alpine
ENV NODE_ENV=development
WORKDIR /usr/src/app
COPY package.json package-lock.json /usr/src/app/
RUN apk add --update --no-cache --virtual .build-deps \
python3 \
make \
g++ && \
npm install && \
apk del .build-deps
```

Nice and easy to copy and paste if any other Devs find themselves here.
