### ISSUE TITLE
Built scripts are not in strict mode if they import other scripts

### ISSUE THREAD

**Issue by brianpeiris** [parcel-bundler/parcel#6683]
# 🐛 bug report

Parcel v2 does not produce scripts in strict mode if the entry point imports other scripts. This occurs even if you add "use script" to the entry script, and even if you install and configure babel with @babel/plugin-transform-strict-mode. Strict mode is enabled if the entry script does not import other scripts.

## 🎛 Configuration (.babelrc, package.json, cli command)

This is reproducible with a zero-config project. I've create a repo with the most basic reproduction here: https://github.com/brianpeiris/parcel-v2-strict-test

Initializing and running that project, with `yarn; yarn start;`, will result in a page that logs "isStrict false" to the browser console. If you comment out the import line, it logs "isStrict true".

## 🤔 Expected Behavior

I'd expect parcel v2 to produce strict mode scripts by default, especially if the script is `type="module"`.

## 😯 Current Behavior

Parcel produces sloppy mode scripts, but only if you import other scripts in your entry file.

## 💻 Code Sample

https://github.com/brianpeiris/parcel-v2-strict-test

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.4.1
| Node             | v17.8.0
| Yarn         | 3.2.0
| Operating System | Ubuntu 21.04

**Comment by devongovett** [comment]
Prod builds should work because `<script type="module">` implies strict mode. But in dev, `type="module"` gets stripped, so I guess we need to add `"use strict"`.

**Comment by devongovett** [comment]
Not stale

**Comment by brianpeiris** [comment]
Thanks. Perhaps not surprising, but I've confirmed this is still an issue with Parcel 2.4.1. I've updated the reproduction accordingly.
