### ISSUE TITLE
Don't pass `-W` to Yarn 2

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#6684]
Yarn 2 doesn't support `-W`, we should only pass that for Yarn 1 (and determine that via `process.env.npm_config_user_agent ` or `yarn --version`):

https://github.com/parcel-bundler/parcel/commit/64797ba4298362e183f11f6056a03db12842177e

https://github.com/parcel-bundler/parcel/blob/64797ba4298362e183f11f6056a03db12842177e/packages/core/package-manager/src/Yarn.js#L63

**Comment by Augani** [comment]
Hello @mischnic , Can i take this?

**Comment by mischnic** [comment]
Sure!
