### ISSUE TITLE
Adding new `reporters` interferes with `parcel serve`

### ISSUE THREAD

**Issue by joegrenan** [parcel-bundler/parcel#6692]
# 🐛 bug report

When I add a new reporter, i.e. `parcel-reporter-static-files-copy`, or `parcel-reporter-multiple-static-file-copier` to my `.parcelrc` config, Parcel no longer serves the port (no matter what `--port` is set).

## 🎛 Configuration (.parcelrc)

```js
{
  "extends": "@parcel/config-default",
  "resolvers": ["parcel-resolver-ignore", "@parcel/resolver-default"],
  "reporters": ["parcel-reporter-multiple-static-file-copier"]
}
```

## 🤔 Expected Behavior

Parcel successfully serves the dist folder with the use of these plugins.

## 😯 Current Behavior

Parcel does not serve anything, no matter which port is used.

## 🔦 Context

I'd like to include static assets in my dist folder, but upon using any plugin that offers this functionality, Parcel's development servers no longer work at all.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.794, behavior consistent with Beta 3 as well
| Node             | v14.17.2
| npm/Yarn         | 7.20.1
| Operating System | Mac OS Big Sur 11.4

**Comment by mischnic** [comment]
You need to add `"..."` after your reporter in the arrray to keep the default plugins and not completely override them

**Comment by OiYouYeahYou** [comment]
> You need to add `"..."` after your reporter in the arrray to keep the default plugins and not completely override them

This is such an incredibly frustrating gotcha. Over the past few days I've been debugging why when I upgrade this breaks, but I've been needing some newer features. Google churned up nothing helpful at all. I've honestly come to a point where I never want to use parcel again.
