### ISSUE TITLE
 @parcel/core: Unexpected output file type .html in target "main"  

### ISSUE THREAD

**Issue by NIB-223** [parcel-bundler/parcel#6693]
# 🐛 bug report

Parcel will not build on localhost 1234 because it says the filetype in main is wrong (.html)

## 🎛 Configuration (.babelrc, package.json, cli command)

$parcel src/index.html

{
  "name": "myflix-client",
  "version": "1.0.0",
  "description": "",
  "main": "src/index.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "parcel src/index.html" 
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Drxl95/myFlix-client.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/Drxl95/myFlix-client/issues"
  },
  "homepage": "https://github.com/Drxl95/myFlix-client#readme",
  "dependencies": {
    "parcel": "^2.0.0-rc.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  }

}

## 🤔 Expected Behavior

it should build on localhost:1234

## 😯 Current Behavior

It gives me an error message saying .html is not the right file extension 

$ parcel src/index.html
Port "1234" could not be used
Server running at http://localhost:56058
🚨 Build failed.

@parcel/core: Unexpected output file type .html in target "main"

  C:\Users\Rob\Desktop\Coding\Bootcamp\myFlix-client\package.json:5:11      
    4 |   "description": "",
  > 5 |   "main": "src/index.html",
  >   |           ^^^^^^^^^^^^^^^^ File extension must be .js, .mjs, or .cjs
    6 |   "scripts": {
    7 |     "test": "echo \"Error: no test specified\" && exit 1",

  💡 The "main" field is meant for libraries. If you meant to output a .html file, either remove the "main" field or choose a different target name.

## 💻 Code Sample

see package.json above

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | v16.4.2
| npm/Yarn         | npm 7.18.1
| Operating System | Windows 10

**Comment by mischnic** [comment]
Have you tried to do as it says?

> If you meant to output a .html file, [...] remove the "main" field

**Comment by NIB-223** [comment]
> Have you tried to do as it says?
> 
> > If you meant to output a .html file, [...] remove the "main" field

I then get   "@parcel/transformer-js: Browser scripts cannot have imports or exports."

**Comment by devongovett** [comment]
Keep following the instructions in the error message. 😉

**Comment by NIB-223** [comment]
I found that adding "type = module" to my index.jsx file fixed the problem.
