### ISSUE TITLE
Quoting filename in parcel CLI throws error

### ISSUE THREAD

**Issue by fawazahmed0** [parcel-bundler/parcel#6697]
# 🐛 bug report

`parcel 'code/*.html' --https` doesn't work

It throws:

```
C:\Users\nawaz\Documents\GitHub\rti>parcel 'code/*.html' --https
@parcel/core: Invalid Parcel Config
node_modules\@parcel\config-default\index.json:106:14
  105 |   ],
> 106 |   "runtimes": [
>     |               ^
> 107 |     "@parcel/runtime-js",
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^
> 108 |     "@parcel/runtime-browser-hmr",
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 109 |     "@parcel/runtime-react-refresh"
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 110 |   ],
>     | ^^^ Expected type object
  111 |   "optimizers": {
  112 |     "data-url:*": [

```

## 💁 Possible Solution

`parcel code/*.html --https` works fine

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | 15.7.0
| npm/Yarn         | 7.20.0
| Operating System | Windows 10

**Comment by mischnic** [comment]
I don't know why quoting it makes a difference, but it looks like `@parcel/config-default` is a recent version while `@parcel/core` (and/or `parcel`) are older and incompatible with the config.

**Comment by fawazahmed0** [comment]
@mischnic what if the folder name has space in it, then we do have to quote it, for example:
`parcel 'code folder/*.html' --https`

**Comment by mischnic** [comment]
`parcel 'code/*.html'` and `parcel code/*.html` are indeed different, but I meant that this wouldn't make a difference for `Invalid Parcel Config` (so either both should work or neither)
