### ISSUE TITLE
Support Web Workers coming from node_modules

### ISSUE THREAD

**Issue by wojtekmaj** [parcel-bundler/parcel#670]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

Both, I guess?

### 🤔 Expected Behavior

* node_modules should be also checked when looking for a file

### 😯 Current Behavior

* trying to refer to a Service Worker file from node_modules fails with the following error:

```
×  C:\Users\wojtekmaj\Projekty\react-pdf\sample\parcel\node_modules\react-pdf\build\entry.parcel.js: Cannot resolve dependency './pdfjs-dist\build\pdf.worker.js' (...)
```

what it is trying to do is look for the path in `./` but not in `node_modules`.

### 💻 Code Sample

I'm currently working on support for Parcel in [React-PDF](https://github.com/wojtekmaj/react-pdf). That requires me to handle loading a service worker which is not mine.

In Webpack, the following code does the job:

```js
var pdfjs = require('react-pdf/build/pdf.js');
var PdfjsWorker = require('worker-loader!react-pdf/build/pdf.worker.js');

if (typeof window !== 'undefined' && 'Worker' in window) {
  pdfjs.PDFJS.workerPort = new PdfjsWorker();
}
```

I was trying to reproduce the same using Parcel, and here's what I got so far:

```js
const pdfjs = require('pdfjs-dist');

if (typeof window !== 'undefined' && 'Worker' in window) {
  pdfjs.PDFJS.workerPort = new Worker('pdfjs-dist/build/pdf.worker.js');
}
```

This results in an error described below. Changing the line to

```js
pdfjs.PDFJS.workerPort = new Worker('../node_modules/pdfjs-dist/build/pdf.worker.js');
```

stops the error, but:

* I'm not comfortable with relative path in a package like that
* This caused.. a 404 error! Parcel starts referring to a file it did not produced.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.5.0
| Node             |9.3.0
| npm/Yarn         |npm, newest
| Operating System |Windows 10

**Comment by wojtekmaj** [comment]
Here's my full code at the moment if you'd like to have a look:

https://github.com/wojtekmaj/react-pdf/tree/parcel/sample/parcel

**Comment by devongovett** [comment]
Ah this is an interesting issue. We treat the argument to Worker as a URL, which it can be. That means this is being treated as a relative path rather than a Node module path. We could maybe require the path to start with `./` or `../` in order to be relative? Not sure we can change this everywhere URL paths are used though since relative URLs without that are fairly common.

**Comment by wojtekmaj** [comment]
Actually that would be great. Not having `./` in front of the path suggests that the path either:

* is a path to node_module
* is a path set in jsconfig.json in `compilerOptions.paths` field as kind of a "root" directory

I'd greatly appreciate this improvement. I'm really looking forward to support Parcel :)

**Comment by mischnic** [comment]
The correct term would be web worker. Service workers handle caching and push notifications.

**Comment by wojtekmaj** [comment]
Guys, is there any news regarding that matter?

I'd really like to officially support Parcel in React-PDF, but I'm super unsure about web worker necessary for my project to run correctly. It *seems* like my workaround is doing the trick, but to me it looks just messy. Is there an official, recommended way to handle this?

**Comment by mischnic** [comment]
@devongovett  Inspired by the new resolver:
- "~/node_modules/pdfjs-dist/build/pdf.worker.js" for "[../]node_modules/pdfjs-dist/build/pdf.worker.js"
- "lib/worker.js" = "./lib/worker.js" for relative paths

**Comment by supertopoz** [comment]
@wojtekmaj Hi. I'm running into the following error relating to the line of code mentioned in the fix:

`typeError: Module scripts are not supported on WorkerGlobalScope yet`

Please note I'm using "Workbox" with Parcel.js for caching files for offline usage with a cache first approach. 

So far everything works fine except that error shows up. It doesn't seem to stop React-PDF from working though, both online and offiline.

**Comment by devongovett** [comment]
For Parcel 2, we are considering supporting an `npm:` URL protocol to resolve node_modules instead of as a relative path. For example:

```html
new Worker('npm:pdfjs-worker');
```

Without the `npm:`, it would resolve the same as `./pdfjs-worker`, since it is a URL.

See https://github.com/parcel-bundler/parcel/issues/3492#issuecomment-529120998 for more details.

**Comment by MikeYermolayev** [comment]
Looks like I have some similar issue. 
I'm trying to use a node_module which uses a worker-loader and get the error below. 

![image](https://user-images.githubusercontent.com/8783498/69001952-9a307500-08f8-11ea-9b0b-2c38b89796fb.png)


Are there any workarounds? Really don't want to switch to webpack because of that issue(((
Thanks in advance

**Comment by devongovett** [comment]
worker-loader is a webpack specific tool and work work with parcel. You can construct a worker like this:

```js
new Worker(“./worker.js”)
```

**Comment by mischnic** [comment]
@MikeYermolayev I fear there's nothing you can do here. (And I think publishing code with worker-loader calls is bad for exactly this reason).

**Comment by MikeYermolayev** [comment]
@mischnic yep. Had to reject using that library

**Comment by gabrielcsapo** [comment]
For anyone getting stuck on this, the support exists, here is the snippet from the react-pdf library

https://github.com/wojtekmaj/react-pdf/blob/main/sample/parcel2/Sample.tsx#L13C39-L16C14

```js
new URL(
  'npm:pdfjs-dist/build/pdf.worker.min.mjs',
  import.meta.url,
).toString();
```
