### ISSUE TITLE
Elm transform shows compiler errors twice

### ISSUE THREAD

**Issue by ChristophP** [parcel-bundler/parcel#6703]
# 🐛 bug report

When the elm compiler encounters errors, parcel logs them. But twice. Once in red once in gray:
<img width="423" alt="grafik" src="https://user-images.githubusercontent.com/5880236/128869789-d1565133-ee63-434a-9919-b47ba8f73906.png">
The gray is hard to read but often the thing that a developer sees because it the last thing that's logged.

## 🎛 Configuration (.babelrc, package.json, cli command)

No babel
simple JS that imports Elm
parcel src/index.js

## 🤔 Expected Behavior

I only wanne see the red output, not the gray one.

## 😯 Current Behavior

Red and gray output
<img width="423" alt="grafik" src="https://user-images.githubusercontent.com/5880236/128870059-b29ed054-8936-4f2a-bb3a-8f9b697da7d5.png">

## 💁 Possible Solution

Check why the output is logged twice

## 🔦 Context

Slowed down my developement because I need to scroll up to see the red output, the gray one is hard to read for me.

## 💻 Code Sample
-

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc1
| Node             | 14.17.5
| npm/Yarn         |  npm 7.6
| Operating System |  Mac OS, Big Surr

**Comment by mischnic** [comment]
(And this is also not using Parcel's system for errors with codeframes where you would see more context and also have syntax highlighting)

**Comment by domenkozar** [comment]
Most likely the cause: https://github.com/parcel-bundler/parcel/issues/6124

**Comment by ChristophP** [comment]
Thanks for fixing 👍
