### ISSUE TITLE
Invalid version: undefined

### ISSUE THREAD

**Issue by Joblyn** [parcel-bundler/parcel#6704]
### Discussed in https://github.com/parcel-bundler/parcel/discussions/6699

<div type='discussions-op-text'>

<sup>Originally posted by **Joblyn** August  9, 2021</sup>
Throws the above error while starting my app
Here's a shot of the error and my `devDependencies`
![Screenshot from 2021-08-09 23-14-12](https://user-images.githubusercontent.com/62160764/128781218-d980a063-8727-4df6-bfc0-b8378b3a66bc.png)
 
Any help is appreciated</div>

**Comment by DeMoorJasper** [comment]
Please don't open a duplicate issue
