### ISSUE TITLE
Scope Hoist breaks application

### ISSUE THREAD

**Issue by kevinresol** [parcel-bundler/parcel#6712]
When scope hoist is enabled, it breaks the app for some reason (to be investigated further)

# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

(Sorry I am in a hurry so please allow me to just dump the steps to reproduce)

```bash
echo '{}' > package.json
yarn add -D parcel@2.0.0-rc.0 http-server
yarn add @deck.gl/core@8.5.3
echo '<script src="index.js" type="module"></script>' > index.html
echo 'import * as Deck from "@deck.gl/core"' > index.js
echo 'console.log(Deck);' >> index.js
yarn parcel build index.html
yarn http-server dist &
open http://127.0.0.1:8080/index.html
```

## 🤔 Expected Behavior

The app should work

## 😯 Current Behavior

<img width="606" alt="Screenshot 2021-08-13 at 5 14 50 PM" src="https://user-images.githubusercontent.com/1103788/129334607-2214c9c9-97ec-4d86-a72f-cf719360fa2b.png">

## 💁 Possible Solution

Add `--no-scope-hoist` to the build command

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | 14.5.0
| npm/Yarn         | yarn 1.22.10
| Operating System | macos 10.15.7

**Comment by kevinresol** [comment]
The default behaviour generated the following code which does not work (`Log` is not defined)
```js
// --default
class b {
	// ...
}
Log.VERSION = ...;
```

While `--no-scope-hoist` generates the following which works
```js
// --no-scope-hoist
class y {
	// ...
}
(r.default = y), (y.VERSION = ...);
```

source code: https://github.com/uber-web/probe.gl/blob/3870d9be30372543514a759cb1e35b463852e721/modules/core/src/lib/log.js#L351

**Comment by mischnic** [comment]
Reproduction:
```js
// index.js
import Log from "./other.js";
console.log(Log);

// other.js
export default class Log {}
Log.VERSION = "VERSION";
console.log(module)
```
