### ISSUE TITLE
Cannot load .babelrc but can load babel.config.json

### ISSUE THREAD

**Issue by serkodev** [parcel-bundler/parcel#6713]
# 🐛 bug report

As the parcel 2 [document](https://v2.parceljs.org/languages/babel/) said:

> avoid Javascript config files (.babelrc.js and babel.config.js). Use the JSON versions instead (.babelrc or babel.config.json).

But I can only load `babel.config.json` but cannot load config inside `.babelrc`.

## 🎛 Configuration (.babelrc, package.json, cli command)

"parcel": "^2.0.0-rc.0"

## 🤔 Expected Behavior

Should auto load `.babelrc` bable config.

## 😯 Current Behavior

Cannot load `.babelrc` bable config but load `babel.config.json` fine.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | v15.14.0
| npm/Yarn         | Yarn
| Operating System | Mac

**Comment by mischnic** [comment]
Are you using a monorepo? If yes, then this is how Babel works in that case: https://babeljs.io/docs/en/config-files#monorepos

**Comment by serkodev** [comment]
> Are you using a monorepo? If yes, then this is how Babel works in that case: https://babeljs.io/docs/en/config-files#monorepos

So dose it need to edit the Parcel 2 document ?

**Comment by mischnic** [comment]
The part of the documentation you cited only says: we support Babel configs (and have no special logic about how they are used, which is why I posted the link to the Babel docs). But we encourage you to not use JS config files because JSON config files have better performance when using Parcel

**Comment by serkodev** [comment]
but Parcel 2 use `.babelrc` as the Code Example of the [document](https://v2.parceljs.org/languages/babel/).
So I think it should change to `babel.config.json` ? As `.babelrc` cannot be loaded as expected.

**Comment by mischnic** [comment]
Please provide a complete example of a project where this you think .babelrc is wrongly ignored.

**Comment by serkodev** [comment]
Oh I don't know why it's work now without change anything.
I will provide more information if I get a issue again. Thx for your reply!
