### ISSUE TITLE
object key named "function" breaks JSX parsing

### ISSUE THREAD

**Issue by shish** [parcel-bundler/parcel#6719]
# 🐛 bug report

broken in 2.0.0-rc0 (was working in 2.0.0-beta2)
```
const x = <div onclick={(e) => {function: 123}}></div>;
```
With the error:
```
@parcel/transformer-js: Unexpected token `div`. Expected jsx identifier
```
This works, which seems confirm the keyword "function" is the problem:
```
const x = <div onclick={(e) => {function_: 123}}></div>;
```

FWIW when I hit this for real, it was a big block of JSX where one of the inner elements had an onclick handler which mentioned `{function: blah}` -- but the error message pointed to the opening tag of the JSX block, not the tag with the attribute (I ended up deleting one element at a time from the big block of jsx to track down the element which was causing issues).

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
    "name": "browser2",
    "dependencies": {
        "@shish2k/hyperapp-hash-state": "^2.0.6",
        "@shish2k/hyperapp-localstorage": "^1.0.0",
        "@shish2k/hyperapp-mqtt": "^1.1.2",
        "hyperapp": "^2.0.18",
        "hyperapp-fx": "^2.0.0-beta.2",
        "hyperapp-jsx-pragma": "^1.3.0"
    },
    "scripts": {
        "build": "parcel build --public-url . src/index.html",
        "watch": "parcel watch --public-url . src/index.html",
        "serve": "parcel serve --port 1234 src/index.html",
        "format": "prettier --write 'src/**/*.tsx' --tab-width 4 --trailing-comma all"
    },
    "repository": "https://github.com/calaldees/KaraKara/",
    "license": "GPL-3.0-only",
    "devDependencies": {
        "@parcel/transformer-sass": "^2.0.0-rc.0",
        "parcel": "^2.0.0-rc.0",
        "parcel-config-pwa-manifest": "0.0.9",
        "prettier": "^2.3.2"
    },
    "pwaManifest": {
        "development": {
            "disabled": true
        },
        "name": "KaraKara",
        "shortName": "KaraKara",
        "startURL": ".",
        "theme": "#e9e9e9",
        "display": "standalone",
        "orientation": "portrait",
        "generateIconOptions": {
            "baseIcon": "./src/static/favicon.svg",
            "sizes": [
                192,
                384,
                512
            ],
            "genFavicons": true
        }
    }
}

```

**Comment by mischnic** [comment]
This is invalid syntax:

https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYewdgzgLgBAHjAvDAPAEwJYDcbmAGw2AGtEBvACgFMBKJAPhjIDMBXMYKDcALhgEYATAGYAvqPooA9Jiz0A3ACggA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.15.3&externalPlugins=&assumptions=%7B%7D

Did you forget to add parenthesis around the object?
```jsx
const x = <div onclick={(e) => ({function: 123})}></div>;
```

**Comment by shish** [comment]
Weird that it was working with 2.0.0-beta.2 with that syntax... but adding parenthesis doesn't stop the error I'm seeing:

Works:
```js
const x = <div onclick={(e) => ({function_: 123})}></div>;
```

Works with 2.0.0-beta.2, but error under 2.0.0-rc.0:

```js
// @parcel/transformer-js: Unexpected token `div`. Expected jsx identifier
const x = <div onclick={(e) => ({function: 123})}></div>;
```

Also pulling the code outside of JSX works too:
```js
const handler = (e) => ({function: 123});
const x = <div onclick={handler}></div>;
```

**Comment by Banou26** [comment]
I encountered an issue that is probably related to this one, using `^2.0.0-nightly.734`, in a `.ts` file, casting using the `<Type>` syntax doesn't work.

```ts
  const setAction = (fields: Partial<HeaderAction>) =>
    setCurrentAction({ ...<HeaderAction>getCurrentAction(), ...fields })
```
    
throws 
```
Building...
× Build failed.
@parcel/transformer-js: Unexpected token `HeaderAction`. Expected jsx identifier
C:\dev\oz\web\src\api\header\actions.ts:36:28
  35 |   const setAction = (fields: Partial<HeaderAction>) =>
> 36 |  ...<HeaderAction>getCurrentAction(), ...fields 
})
>    |      ^^^^^^^^^^^^
  37 |
  38 |   _actions([
```

This started happening once i removed my .babelrc which contained
```json
{
  "presets": [
    "@babel/preset-typescript",
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-proposal-throw-expressions"
  ]
}
```
after trying to upgrade to a newer Parcel version where it threw a warning saying that my presets were already Parcel's default.

**Comment by mischnic** [comment]
@Banou26 That seems to fail with Babel as well? 

https://babeljs.io/repl/#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=ATDGHsDsGcBdmgU1gQVLAllYBeYAKAMw0QBsATaASlwD4AoEEJWAYQFcAnTxSVdLJHwBvRkxAA6KQB4AEogCG5RJzSYotAObIO3Xv3VCqAGjHipE4mUpngAXyoBuIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Ctypescript&prettier=false&targets=&version=7.15.3&externalPlugins=&assumptions=%7B%7D

**Comment by Banou26** [comment]
Hmm, weird, it seems that on that repro https://github.com/Banou26/parcel-bug-6719 i can just use use the `<>` casting without problems, and if you try to delete the `.babelrc`, then it starts throwing.
