### ISSUE TITLE
Support Vue jsx and tsx

### ISSUE THREAD

**Issue by serkodev** [parcel-bundler/parcel#6723]
# 🙋 feature request

Support jsx and tsx for Vue

## 🤔 Expected Behavior

Adding `<script lang="tsx">` or `<script lang="jsx">` in `.vue` file and write somthing like

```jsx
<script lang="jsx">
const app = createApp({
  render() {
    return (
      <AnchoredHeading level={1}>
        <span>Hello</span> world!
      </AnchoredHeading>
    )
  }
})
</script>
```

See: [https://v3.vuejs.org/guide/render-function.html#jsx](https://v3.vuejs.org/guide/render-function.html#jsx)

## 😯 Current Behavior

```
🚨 Build failed.

@parcel/transformer-vue: Unknown script language: "tsx"
```

## 💁 Possible Solution

Add support jsx/tsx in @parcel/transformer-vue ?

## 💻 Examples

Same as "Expected Behavior"

**Comment by mischnic** [comment]
https://v3.vuejs.org/guide/typescript-support.html#project-creation recommends this
