### ISSUE TITLE
running `parcel` fails for error `@parcel/optimizer-cssnano: Could not resolve module "dot-prop" from "postcss-selector-parser"`

### ISSUE THREAD

**Issue by GuyKh** [parcel-bundler/parcel#6731]
# 🐛 bug report
running `parcel` fails for error `@parcel/optimizer-cssnano: Could not resolve module "dot-prop" from ".../postcss-selector-parser/dist/parser.js"`

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
...
...
  "main": "dist/index.js",
  "browser": "dist/public/js/main.js",
  "source": "build src/public/js/main.ts",
  "targets": {
    "browser": {
      "includeNodeModules": true
    }
  },
...
...
  "scripts":  {
  ... 
   "parcel": "parcel build src/public/js/main.ts --target browser --no-scope-hoist",
 ...
 }
}
```

## 🤔 Expected Behavior
Build should complete and work

## 😯 Current Behavior

Full error:
```
> parcel build src/public/js/main.ts --target browser --no-scope-hoist

🚨 Build failed.
@parcel/optimizer-cssnano: Could not resolve module "dot-prop" from "/Users/guyk/workspace/moneyball/mb_queue/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js"
Error: Could not resolve module "dot-prop" from "/Users/guyk/workspace/moneyball/mb_queue/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js"
    at NodeResolverSync.resolve (/Users/guyk/workspace/moneyball/mb_queue/node_modules/@parcel/package-manager/lib/NodeResolverSync.js:44:15)
    at NodePackageManager.resolveSync (/Users/guyk/workspace/moneyball/mb_queue/node_modules/@parcel/package-manager/lib/NodePackageManager.js:354:36)
    at NodePackageManager.requireSync (/Users/guyk/workspace/moneyball/mb_queue/node_modules/@parcel/package-manager/lib/NodePackageManager.js:173:14)
    at Module.m.require (/Users/guyk/workspace/moneyball/mb_queue/node_modules/@parcel/package-manager/lib/NodePackageManager.js:194:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/Users/guyk/workspace/moneyball/mb_queue/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js:7:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at NodePackageManager.load (/Users/guyk/workspace/moneyball/mb_queue/node_modules/@parcel/package-manager/lib/NodePackageManager.js:208:9)
ERROR: "parcel" exited with 1.
ERROR: "build" exited with 1.
[nodemon] app crashed - waiting for file changes before starting...
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-rc0 | 
| Node             |  v16.6.2 | 
| npm/Yarn         |  npm 7.20.6 |
| Operating System | MacOS 11.5.1 |

**Comment by GuyKh** [comment]
I had a dependency of `"postcss": "^8.2.10"`

When I removed this - I'm getting the following (different) error on build:
```
@parcel/core: node_modules/vue/dist/vue.runtime.esm-bundler.js does not export 'createElementBlock'

  /Users/guyk/workspace/moneyball/mb_queue/src/public/js/env-card-title.vue:1:115
  > 1 | <template>
  >   |           ^
    2 |   <div>
    3 |     <span class="card-title">
```

**Comment by mischnic** [comment]
>   "main": "dist/index.js",
>  "browser": "dist/public/js/main.js",

Are you building a webapp? If yes, then you should choose different names for "main" and "browser" (and maybe remove one of the entirely)

**Comment by GuyKh** [comment]
@mischnic this is an SSR, it has a express backend, and a vue frontend (under `js` folder)
I'll give it a try though

EDIT:
didn't help :(

**Comment by mischnic** [comment]
Please provide a code sample that reproduces the error(s).

**Comment by GuyKh** [comment]
Actually, removing the `postCss` dependency and rolling back to Parcel `2.0.0-beta2` seems to have solved the issue

**Comment by GuyKh** [comment]
With `Parcel 2.0.0` this issue returned.
Reopening the ticket :(

```
 Build failed.

@parcel/core: node_modules/vue/dist/vue.runtime.esm-bundler.js does not export 'createElementVNode'

  /Users/guyk/workspace/moneyball/mb_queue/src/public/js/env-card.vue:1:78
  > 1 | <template>
  >   |           ^
    2 |   <div class="row">
    3 |     <div class="col s12">
```

Need to mention that this works great in `2.0.0-beta2` - and upon upgrade to `2.0.0` it started happening again
Moreover - I tried to find the one dependency that caused it - 
It started happening when I updated `parcel` and `@parcel/transformer-vue` to `2.0.0`

**Comment by mischnic** [comment]
Please provide a complete code sample so that we can reproduce this.

**Comment by GuyKh** [comment]
for example, the following Vue file fails to copmile:

```
<template>
  <h3>Title</h3>
</template>
```

**Comment by mischnic** [comment]
I think this is because you are using Vue 2 in your project, and not Vue 3? https://github.com/parcel-bundler/parcel/issues/6153

**Comment by GuyKh** [comment]
> I think this is because you are using Vue 2 in your project, and not Vue 3? #6153

Nope. Latest vue 3
