### ISSUE TITLE
SCSS imports containing ~/ fail

### ISSUE THREAD

**Issue by mkg20001** [parcel-bundler/parcel#6734]
# 🐛 bug report

When using ~/ paths in SCSS @ imports it fails with an error message

## 🎛 Configuration (.babelrc, package.json, cli command)

See code sample gist, `yarn build`

## 🤔 Expected Behavior

SCSS import works as expected

## 😯 Current Behavior

Imports using ~ in SCSS cause the following error

```
yarn run v1.22.11
$ parcel build index.html
🚨 Build failed.

Error: ENOENT: no such file or directory, open '/home/maciej/Projekte/parcel-issue/file%3A/home/maciej/Projekte/parcel-issue/other.scss'

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
## 🔦 Context

It breaks build & serve

## 💻 Code Sample

https://gist.github.com/mkg20001/32cb89621833c22485290b13f8032313

Minimum reporduction is using ~ in SCSS @ import

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | v16.6.2
| npm/Yarn         | yarn 1.22.11
| Operating System | NixOS 21.11 (Porcupine)

**Comment by hexid** [comment]
This also affects node_modules imports like the following
```scss
@use 'sanitize.css';
@use 'sanitize.css/forms.css';
```

It appears to be caused by [sass@1.38.0](https://github.com/sass/dart-sass/releases/tag/1.38.0).
Adding the following to your package.json can be used as a temporary workaround

```json
{
  "resolutions": {
    "sass": "1.37.5"
  }
}
```

**Comment by hexid** [comment]
This is the problematic commit: https://github.com/sass/dart-sass/commit/4fd0472f2e7cbd12d7892cafe262199fbc1d145c

In my case, `file` contains something similar to

    file:///absolute/path/to/node_modules/sanitize.css/sanitize.css

Passing it into `p.toUri(file).toString()` transforms it into

    file%3A/absolute/path/to/node_modules/sanitize.css/sanitize.css

Removing this [pathToFileURL](https://github.com/parcel-bundler/parcel/blob/cd013739397927ba370a69ca36b05bd0ec641c04/packages/transformers/sass/src/SassTransformer.js#L184) call appears to solve this issue, but will likely also require that the `sass` dependency is bumped to 1.38.0.

```diff
@@ -4,7 +4,6 @@
 import {EOL} from 'os';
 import SourceMap from '@parcel/source-map';
 import sass from 'sass';
-import {pathToFileURL} from 'url';
 import {promisify} from 'util';

 // E.g: ~library/file.sass
@@ -181,7 +180,7 @@
       .then(resolved => {
         if (resolved) {
           done({
-            file: pathToFileURL(resolved.filePath).toString(),
+            file: resolved.filePath,
             contents: resolved.contents,
           });
         } else {
```

**Comment by mkg20001** [comment]
I've added this to my prestart/prebuild

```sh
sed 's|(0, _url().pathToFileURL)(resolved.filePath).toString()|resolved.filePath|g' -i node_modules/@parcel/transformer-sass/lib/SassTransformer.js
```

This command applies the change above
