### ISSUE TITLE
Unable to import `createApi` from Redux Toolkit

### ISSUE THREAD

**Issue by artdevgame** [parcel-bundler/parcel#6736]
# 🐛 bug report

When using Redux Toolkit Query, a couple of us are getting the following error:

> Uncaught TypeError: Cannot redefine property: createApi

When importing createAPI:
```
import { createApi } from '@reactjs/toolkit/query/react'
```

See: https://github.com/reduxjs/redux-toolkit/issues/1345

The author of that library has asked us to post here as it's possibly a bug in Parcel.

## 🤔 Expected Behavior

A project using Parcel and RTK should compile without error when importing `createApi`

## 💻 Code Sample

I have an example that demonstrates the behaviour:
https://github.com/artdevgame/rtk 

(run yarn followed by yarn start then look in console)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             |  16.6.0
| Yarn         | 1.22.5
| Operating System | Windows

**Comment by mischnic** [comment]
The reason here is that

```js
// index.js
import { createApi } from "./a.js";
console.log(createApi);

// a.js
export * from "./b.js";
var createApi = function createApiReact() {};
export { createApi };

// b.js
var createApi = function createApiB() {};
export { createApi };

// c.js
var createApi = function createApiC() {};
export { createApi };
```

is allowed, while having the following a.js isn't allowed by the spec (`'./a.js' contains conflicting star exports for name 'createApi`):
```js
export * from "./b.js";
export * from "./c.js";
```

**Comment by artdevgame** [comment]
@phryneas Does this make sense to you? I'm sorry for being dumb. Not sure if this is something I need to address in how I'm using RTK, or if it's something within RTK itself that needs addressing.

**Comment by mischnic** [comment]
This is a bug in Parcel.

**Comment by jainkunal** [comment]
@mischnic any updates on this?

**Comment by mischnic** [comment]
Fixed by https://github.com/parcel-bundler/parcel/pull/7016
