### ISSUE TITLE
No HMR option prevents standard reload

### ISSUE THREAD

**Issue by JaredSartin** [parcel-bundler/parcel#6737]
# 🐛 bug report

## 🎛 I am running multiple entry points and wanting to only have hot reload, not hot module replacement. When passing `--no-hmr` in to the command line, my build cooperates, but I don't get hot reloads.

My npm script below

```js
{
  "dev": "rimraf build-local && parcel app/main-menu.html test/runner/index.html --dist-dir ./build-local --no-hmr",
}
```

## 🤔 Expected Behavior

I expect my browser to fully reload on builds when not using hmr.

## 😯 Current Behavior

Browser must be manually refreshed to see changes.

## 💁 Possible Solution

HRM disabling also disable hot reloads, not looked into the code to verify, but these 2 should be separate.

## 🔦 Context

I have a test runner that runs in a specialized browser container and reports test results to a local server to show test state. We work in TDD fashion. I need the page to reload each time a build occurs so the test suite re-runs. With HMR it was not doing that, additionally HMR builds are erroring out on module inclusion for Mocha and Chai.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0..0-rc.0
| Node             | 14.1.7.3 x64
| npm/Yarn         | npm 6.14.13
| Operating System | Windows 10 Pro

**Comment by mischnic** [comment]
`--no-hmr` disables everything regarding hot reloads (be it page reloads or "hot updates" of code at runtime).

**Comment by JaredSartin** [comment]
@mischnic there is no middleground?

**Comment by mischnic** [comment]
Currently from the server's perspective, there is only "hmr" or "no hmr". The decision between page reload and hot updates happens on the client (depending on whether `module.hot.accept` was called)

**Comment by JaredSartin** [comment]
OK, so this is a non-issue. Will close.
