### ISSUE TITLE
🐛  javascript compression problem

### ISSUE THREAD

**Issue by yebingo** [parcel-bundler/parcel#674]
hi,I would like to ask why parcel package out of the beginning of the javascript file is not compressed, like this:
![image](https://user-images.githubusercontent.com/26788533/35432667-b80ff2c0-02bb-11e8-8d97-faa13d7aba84.png)
I did not add **--no-minify** parameters.
What is the reason? Why not compress the entire javascript file?

**Comment by yebingo** [comment]
@DeMoorJasper My parcel-bundler version is 1.5.1.
![image](https://user-images.githubusercontent.com/26788533/35438840-22cce020-02d3-11e8-9d76-b546700aa55d.png)

**Comment by davidnagli** [comment]
Parcel only minifies bundles when you build them for production using `parcel build file.abc`

If you just run `parcel file.abc`, it will include something called the HMR Runtime which is essentially some code we inject into the bundle to hot swap your code in the page every time you make changes. In addition to the HMR runtime (what you’re seeing), it also won’t minify any of the files anyways until you build for production.

Hope this helps :)

Feel free to re-open if you have any other questions or if you continue to have any problems.

**Comment by lightsinthesky** [comment]
Hello, using ```parcel build file.abc``` still does not minify. I'm using the following ```parcel build index.js -d dist/js``` and get the same results as above. Heres my package.json deps.
```
  "dependencies": {
    "babel-polyfill": "^6.26.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  },
  "devDependencies": {
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-1": "^6.24.1",
    "parcel-bundler": "^1.5.1"
  }
```

**Comment by davidnagli** [comment]
Hmm that’s very strange! 

I just tried to reproduce that but I wasn’t able to, it worked perfectly for me. Can you please send some example code and/or throw up an example repo showing the issue?

**Comment by lightsinthesky** [comment]
ahh, I see whats going on, ```yarn start``` is writing to the ./dist folder as well so there are non-min versions of the js files in the root of dist. Does ```parcel file.js``` automatically write to ./dist ? This can be closed.

**Comment by DeMoorJasper** [comment]
`./dist` is indeed the default folder for both builds and watching, the hashed name does change so there are 2 js files one minified one not minified.
Hope this clears up everything, glad u got it to work

**Comment by yebingo** [comment]
@davidnagli You can see this demo:https://github.com/yebingo/parcel-vue-demo.
@DeMoorJasper My build environment output folder is ./build, not ./dist.

**Comment by laosb** [comment]
I'm suffering this well.

![image](https://user-images.githubusercontent.com/2545261/35897381-df3a883a-0bfb-11e8-9ec2-24392b8b5ed5.png)

It gets me a non-minified head of the output.

![image](https://user-images.githubusercontent.com/2545261/35897405-fd28f21e-0bfb-11e8-8379-d0f2a0235577.png)

File contents are correctly minified.

**Comment by DeMoorJasper** [comment]
@laosb could u check the parcel version, `parcel -v`? It should work in the latest version
