### ISSUE TITLE
Adding a JS import breaks HMR

### ISSUE THREAD

**Issue by SimplyComplexable** [parcel-bundler/parcel#6741]
# 🐛 bug report

As soon as I add a JS import into my HTML file it breaks the HMR.

## 🎛 Configuration (.babelrc, package.json, cli command)

Here's a project where it's doing it. 
https://github.com/SimplyComplexable/parcel-example

## 🤔 Expected Behavior

HMR should work with JS files.

## 😯 Current Behavior

HMR doesn't work. It still builds correctly and refreshing shows the correct content, but it isn't automatically refreshed.

## 💁 Possible Solution

🤷

## 🔦 Context

I'm making changes to the HTML directly, just changing the content of the `h1`. Without the script tag HMR works fine, as soon as it's added it stops working.

## 💻 Code Sample

Linked above

## 🌍 Your Environment

Full reproduction provided.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| postcss | 8.3.6
| tailwindcss | 2.2.7
| Node             | 14.17.1
| npm/Yarn         | npm
| Operating System | Mac OS Big Sur 11.4

**Comment by mischnic** [comment]
It works correctly `<script src="..." type="module">` (so only broken for non-module scripts).

At runtime, these asset updates are sent to the browser. The HMR runtime's env hash is `4e5dac8afe405db7`, so it ignores the html update and doesn't trigger a reload.
```json5
{
  "type": "update",
  "assets": [
    {
      "id": "lnSHf",
      "type": "html",
      "output": "<html>\n  <head>\n    <title>Example</title>\n    <script src=\"5088da11ac4faa0d\" data-parcel-key=\"b30a35a321d75730\">\n  </script></head>\n  <body>\n    <h1>Hellosssssss</h1>\n  </body>\n</html>\n",
      "envHash": "69f74e7f31319ffd",
      // ...
      }
    },
    {
      "id": "6vNXn",
      "type": "js",
      "output": "",
      "envHash": "4e5dac8afe405db7",
      // ...
    }
  ]
}
```

**Comment by devongovett** [comment]
HMR isn't supported with non-module scripts.
