### ISSUE TITLE
"extendDefaultPlugins utility is deprecated" warning

### ISSUE THREAD

**Issue by astegmaier** [parcel-bundler/parcel#6744]
# 🐛 bug report

When running `parcel build` on a project with a no cache, `@parcel/optimizer-htmlnano` logs a message that the `"extendDefaultPlugins" utility is deprecated.` The error does not appear if you re-build with a warm cache. It looks like this may have been [hit by someone else incidentally](https://github.com/parcel-bundler/parcel/issues/6730#issuecomment-899923379) while debugging #6730 (which is a different issue)

### package.json:
```json
{
  "scripts": {
    "build": "parcel build src/index.html",
  },
  "devDependencies": {
    "parcel": "2.0.0-rc.0",
  },
  "browserslist": "> 0.5%, last 2 versions, not dead"
}
```

### index.html
```html
<!DOCTYPE html>
<html lang="en">
  <body>
    <h1>Test HTML Page with SVG</h1>
    <img src="test.svg" />
  </body>
</html>
```

## 🤔 Expected Behavior

Running `yarn build` does not produce deprecation warnings.

## 😯 Current Behavior

When you run `yarn build` on a project with a clean cache, you see this:
```
$ parcel build src/index.html

console: 
"extendDefaultPlugins" utility is deprecated.
Use "preset-default" plugin with overrides instead.
For example:
{
  name: 'preset-default',
  params: {
    overrides: {
      // customize plugin options
      convertShapeToPath: {
        convertArcs: true
      },
      // disable plugins
      convertPathData: false
    }
  }
}

✨ Built in 1.05s

dist/index.html             190 B    531ms
dist/test.e48e572b.svg    2.81 KB    479ms
✨  Done in 1.49s.
```
If you run `yarn build` again with a warm cache, the warning will not appear. To see it again, delete the `.parcel-cache` folder.

## 💁 Possible Solution

Use `preset-default` to configure svgo.

## 🔦 Context

There's no problems that I've noticed so far with the build output, but it might break in the future if it's deprecated.

## 💻 Code Sample

You can repro the issue [using this repo](https://github.com/astegmaier/parcel-svgo-plugins-warning)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | 14.17.5
| Yarn         | 1.22.11
| Operating System | OS X 11.5.2

**Comment by mischnic** [comment]
Instead of 
https://github.com/parcel-bundler/parcel/blob/de415831bdd6f36a1c71aff44c1c9ec4ef3ad266/packages/optimizers/htmlnano/src/HTMLNanoOptimizer.js#L60

it should instead use

```
   plugins: {
      name: 'preset-default',
      overrides: {
        ...
      }
    }
```
as introduced by
https://github.com/svg/svgo/pull/1513

(But we need to make sure that the svgo dependency semver range of htmlnano also supports this in every case.)

**Comment by astegmaier** [comment]
@mischnic - I made that change in [this branch](https://github.com/astegmaier/parcel/commit/a1a715e7627add69b48aa1cad62063cf9f462181), and it appears to work fine when I `yarn link` the local build to a test project, but it causes some unit tests to fail - I think something might be getting messed up with the unit tests somehow running with an earlier version of `svgo`, maybe because of the worry you mentioned about `htmlnano` not yet supporting the latest version of `svgo`. I'll debug more next week, but I wanted to share progress in case someone else is looking at this and wants a starting place.

**Comment by isanchezd** [comment]
Someone know about this issue?

I have a personal project and i´m migrating from parcel V1 to V2 and i have this issue

Thanks!

**Comment by jeffpeck10x** [comment]
@isanchezd1988 It is resolved in the latest parcel nightly branch.
```
yarn add --dev parcel@nightly
```

However, it is just a warning and can ignored.
