### ISSUE TITLE
Build breaks with browserslist configuration "supports es6-module"

### ISSUE THREAD

**Issue by 01231** [parcel-bundler/parcel#6749]
# 🐛 bug report

The build crashes. I found out when I remove this statement `"browserslist": "supports es6-module"` in the `package.json` the build works flawless.

## 🎛 Configuration (package.json)

```json
{
  "name": "project",
  "version": "0.1.0",
  "description": "",
  "source": "src/index.html",
  "browserslist": "supports es6-module",
  "scripts": {
    "start": "parcel --open chrome",
    "build": "parcel build"
  },
  "repository": "",
  "author": "",
  "license": "MIT",
  "dependencies": {
    "eslint-config-airbnb": "^18.2.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.0"
  },
  "devDependencies": {
    "parcel": "^2.0.0-rc.0"
  }
}

```

## 🤔 Expected Behavior
In my opinion this should just work out of the box. I did run `npx browserslist 'supports es6-module'` to test if this is a valid query for browserslist and it did work.

## 😯 Current Behavior

This is the output when running `yarn build`.
```bash
$ parcel build
🚨 Build failed.

@parcel/transformer-js: Invalid Version: TP.0.0

  TypeError: Invalid Version: TP.0.0
  at new SemVer
  (.../project/node_modules/semver/semver.js:323:11)
  at compare
  (.../project/node_modules/semver/semver.js:614:39)
  at Function.gt
  (.../project/node_modules/semver/semver.js:643:10)
  at Object.transform
  (.../project/node_modules/@parcel/transformer-js/lib/JSTransformer.js:312:58)
  at processTicksAndRejections
  (internal/process/task_queues.js:95:5)
  at async Transformation.runTransformer
  (.../project/node_modules/@parcel/core/lib/Transformation.js:604:5)
  at async Transformation.runPipeline
  (.../project/node_modules/@parcel/core/lib/Transformation.js:357:36)
  at async Transformation.runPipelines
  (.../project/node_modules/@parcel/core/lib/Transformation.js:241:40)
  at async Transformation.run
  (.../project/node_modules/@parcel/core/lib/Transformation.js:167:19)
  at async Child.handleRequest
  (.../project/node_modules/@parcel/workers/lib/child.js:217:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.0-rc.0
| Node             | v14.17.0.
| npm/Yarn         | 1.22.11
| Operating System | macOS Big Sur 11.4

**Comment by devongovett** [comment]
Seems like potentially an issue with browserslist. They should be returning a version number. I'm not sure what TP is...

**Comment by mischnic** [comment]
https://github.com/parcel-bundler/parcel/blob/95f5648d775fbea72506c3c4f7a67fe48efa8d43/packages/transformers/js/src/JSTransformer.js#L311-L329

`browser` is `"safari TP"`, then `semverVersion` is `TP.0.0` which is of course an invalid version number

**Comment by cekvenich2** [comment]
Watching.

**Comment by folknor** [comment]
In fact the bug is with any valid `supports foo` keyword, as far as I can see - I tested 6 of them.
EDIT: Ah, I read the relevant code above now, please excuse my unnecessary comment.
