### ISSUE TITLE
Unable to build TypeScript project

### ISSUE THREAD

**Issue by oliversalzburg** [parcel-bundler/parcel#6753]
# 🐛 bug report

When trying to build TypeScript sources, the build process fails trying to load `@swc/helpers`.

## 🎛 Configuration (.babelrc, package.json, cli command)

https://github.com/oliversalzburg/parcel-ts-repro/tree/369fdbb5fe7a5c1b5aa717f4c55f2331eb1c92b3

## 🤔 Expected Behavior

The project should be built.

## 😯 Current Behavior

```shell
🚨 Build failed.

@parcel/core: Failed to resolve '@swc/helpers' from './.yarn/unplugged/@parcel-transformer-js-npm-2.0.0-rc.0-59ac36b5ed/node_modules/@parcel/transformer-js/lib/JSTransformer.js'

  /home/oliver/fairmanager/fairmanager/core-web3/packages/core-models3/source/entities/UserProfile.ts:1:1
  > 1 | import * as Validate from "class-validator";
  >   | ^
    2 | import { stripIndent } from "common-tags";
    3 | import * as GraphQL from "type-graphql";

@parcel/resolver-default: External dependency "@swc/helpers" is not declared in package.json.

  /home/oliver/fairmanager/fairmanager/core-web3/packages/core-models3/package.json:38:3
    37 |   },
  > 38 |   "dependencies": {
  >    |   ^^^^^^^^^^^^^^
    39 |     "@mikro-orm/core": "4.5.7",
    40 |     "@mikro-orm/postgresql": "4.5.7",

  💡 Add "@swc/helpers" as a dependency.
```

## 💁 Possible Solution

~~I assume this is related to yarn's PnP and the dependency needs to be loaded differently.~~ Not related to PnP. Happens with node-modules linker as well.

You _can_ install `@swc/helpers` into your own dependencies to work around the issue. There'll still be confusing TS-related warnings though.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | v16.6.2
| npm/Yarn         | yarn 3.0.1
| Operating System | Windows

**Comment by devongovett** [comment]
Did you try following the instructions in the error message? That package must be a dependency in your package.json because the compiled output will reference it, so users will need it installed for your library to work correctly.

**Comment by oliversalzburg** [comment]
@devongovett I have tried that and mentioned it in the **Possible Solution** section.

What you're describing is non-obvious to a consumer of parcel. Especially given that other required modules are apparently auto-installed and this isn't happening here. From the documentation that I have read, it's not even clear that swc is being used by parcel. For a tool that prides itself on being "zero configuration", this feels a bit much.

**Comment by devongovett** [comment]
I'm not really sure what we could do about it though. The helpers are required for the code to work so they have to be a dependency. We don't auto install code dependencies, only build dependencies (eg compilers).

This is only required for libraries because the compiled code will be consumed outside parcel. For applications we use a bundled version of the helpers that comes with parcel.

**Comment by oliversalzburg** [comment]
Makes sense. Maybe this could be noted in the install instructions or a clearer instruction could be generated in this case?

**Comment by JanMisker** [comment]
The same applies to `regenerator-runtime`, has to be installed as a dependency in a library project.

**Comment by jschill** [comment]
I got a similar error once adding browserslist to my package.json. 

`@parcel/core: Failed to resolve '@swc/helpers' from './node_modules/@parcel/transformer-js/lib/JSTransformer.js'`

**Comment by taoeffect** [comment]
> I got a similar error once adding browserslist to my package.json.

I also have this issue and don't know what to do. Installing `@swc/helpers` as either a dev dependency or a regular one doesn't fix this issue... help?

**Comment by taoeffect** [comment]
> I also have this issue and don't know what to do. Installing @swc/helpers as either a dev dependency or a regular one doesn't fix this issue... help?

Figured it out: apparently after a dev dependency has been installed, running `npm i -S @swc/helpers` won't move it to the regular `"dependencies"` section... so I had to do that manually and now it seems to be working.

**Comment by oliversalzburg** [comment]
There is obviously no problem here

**Comment by dominictobias** [comment]
> There is obviously no problem here

When you say there is no problem here, what is the solution? I get this error even with `@swc/helpers` and `regenerator-runtime` installed as dependencies of the project (which I find a little weird but it doesn't work anyway)

The project was compiling fine until I added:
```
"browserslist": "> 0.25%",
  "engines": {
    "browsers": "> 0.25%"
  },
```

Which as far as I can tell makes it compile for the browser instead of node

Edit: Nvm fixed by targeting modern browsers: `"browsers": "last 2 years, > 1%, not dead"`

**Comment by oliversalzburg** [comment]
@DominicTobias I have to apologize. I was probably in a bad mood when I wrote that comment. I only briefly tried to use parcel, and no longer wanted to invest any energy into this issue/thread. I have no solution to offer. Sorry

**Comment by dominictobias** [comment]
> @DominicTobias I have to apologize. I was probably in a bad mood when I wrote that comment. I only briefly tried to use parcel, and no longer wanted to invest any energy into this issue/thread. I have no solution to offer. Sorry

Np I also gave up 😅  I couldn't get a browser build that ran without errors (using require() statements or other issues), copied one of my standard rollup configs instead and worked fine

**Comment by maheshk06** [comment]
> 

@DominicTobias I am also getting the same issue.
Could you please help me to fix this?
Thanks in advance.

**Comment by bsorrentino** [comment]
I'm working with parcel  `2.8.3` and I faced with same issue 

I solved it, switching to standard `tsc` compiler see [here](https://parceljs.org/languages/typescript/#tsc)
