### ISSUE TITLE
Parcel 2: CSS Modules throws error when building

### ISSUE THREAD

**Issue by thien-do** [parcel-bundler/parcel#6758]
# 🐛 bug report

When using CSS Modules, named import throws error when building, while default import throws warning

## 🎛 Configuration (.babelrc, package.json, cli command)

Just the default config. CSS Modules are automatically recognized due to the "module.css" suffix. I also have TypeScript, so my parcelrc looks like this:

```
{
	"extends": "@parcel/config-default",
	"transformers": {
		"*.{ts,tsx}": [
			"@parcel/transformer-typescript-tsc"
		]
	},
	"validators": {
		"*.{ts,tsx}": [
			"@parcel/validator-typescript"
		]
	}
}
```

## 🤔 Expected Behavior

No error when using named imports

## 😯 Current Behavior

When using default import (`import style from "./editor.module.css"`):

```
@parcel/packager-css: CSS modules cannot be tree shaken when imported with a default specifier

  💡 Instead do: import * as style from "./editor.module.css";
```

When using named import (`import * as style from "./editor.module.css"`):

```
@parcel/core: src/editor/editor.module.css does not export 'status'
```

## 🔦 Context

This doesn't allow me to build the project, so I must use default and accept the warning.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2 rc0
| Node             | latest
| npm/Yarn         | latest 1
| Operating System | Mac

**Comment by thien-do** [comment]
it's worth to note that this only happens for `parcel build`, and no problem when I start it

**Comment by thien-do** [comment]
Oh turn out the solution is 

		"allowSyntheticDefaultImports": true,

**Comment by thien-do** [comment]
Actually no, that was false. If I delete "parcel-cache", the error appears again. However, if I build again (keeping the cache) then the error gone.

**Comment by mischnic** [comment]
Please share your tsconfig.

**Comment by thien-do** [comment]
Thanks for the reply @mischnic :D

tsconfig:

```json
{
	"compilerOptions": {
		"target": "ES2021",
		"module": "commonjs",
		"allowJs": false,
		"jsx": "react-jsx",
		"isolatedModules": true,
		"strict": true,
		// "exactOptionalPropertyTypes": true,
		"allowSyntheticDefaultImports": true,
		"esModuleInterop": true,
		"skipLibCheck": true,
		"forceConsistentCasingInFileNames": true,
		"types": ["wicg-file-system-access", "css-font-loading-module"]
	},
	"include": ["src/**/*"]
}
```

global.d.ts
```ts
declare module "*.module.css" {
	const classes: { readonly [key: string]: string };
	export = classes;
	export default classes;
}
```

parcelrc
```json
{
	"extends": "@parcel/config-default",
	"transformers": {
		"*.{ts,tsx}": [
			"@parcel/transformer-typescript-tsc"
		]
	},
	"validators": {
		"*.{ts,tsx}": [
			"@parcel/validator-typescript"
		]
	}
}
```

**Comment by thien-do** [comment]
We switched to other bundler because of this so this issue is no longer valid for me 🙏 if others have it, please feel free to reuse

**Comment by lorna-propelle** [comment]
If anyone finds a similar issue, I sorta followed this https://stackoverflow.com/questions/41336858/how-to-import-css-modules-with-typescript-react-and-webpack

and by using (in a `global.d.ts` file)

```
declare module '*.module.scss' {
  interface IClassNames {
    [className: string]: string
  }
  const classNames: IClassNames;
  export = classNames;
}
```
annnnd

`import * as classes from './Component.module.scss'` in my `Component.tsx` file

Seemed to do the trick in terms of no pesky typescript errors or parcel build warnings

**Comment by Laindrion** [comment]
> If anyone finds a similar issue, I sorta followed this https://stackoverflow.com/questions/41336858/how-to-import-css-modules-with-typescript-react-and-webpack
> 
> and by using (in a `global.d.ts` file)
> 
> ```
> declare module '*.module.scss' {
>   interface IClassNames {
>     [className: string]: string
>   }
>   const classNames: IClassNames;
>   export = classNames;
> }
> ```
> 
> annnnd
> 
> `import * as classes from './Component.module.scss'` in my `Component.tsx` file
> 
> Seemed to do the trick in terms of no pesky typescript errors or parcel build warnings

Thank you sir!

**Comment by broofa** [comment]
Can we reopen this?  None of the suggested workarounds actually works (for me.)

Note: Also, it'd be nice if [these instructions in the Parcel docs](https://parceljs.org/languages/css/#tree-shaking) include instructions for working around this issue (assuming such exist.)

With `import styles from ...'` statements, I get these warnings:
```
@parcel/optimizer-css: CSS modules cannot be tree shaken when imported with a
default specifier

  /Users/kieffer/projects/flightcard/webapp/components/CardSummary/CardSummary.tsx:20:8
    19 | import { QuickUnits } from '../common/QuickUnits';
  > 20 | import styles from './CardSummary.module.scss';
  >    |        ^^^^^^
    21 |
    22 | function RocketDimensions({ rocket }: { rocket?: iRocket }) {

  💡 Instead do: import * as style from "./CardSummary.module.scss";
  📝 Learn more
```

But with `import * as styles from ...;` statements, I get these errors:
```
🚨 Build failed.

@parcel/core: components/CardSummary/CardSummary.module.scss does not export
'name'

  /Users/kieffer/projects/flightcard/webapp/components/CardSummary/CardSummary.tsx:122:30
    121 |           <div>
  > 122 |             <span className={styles.name}>
```

----

Of course, I have this `declare module` statement, but this only provides a type definition for the default export (`import styles as '...'`)

```ts
declare module '*.module.scss' {
  const value: Record<string, string>;
  export default value;
}
```

----

Here's my tsconfig.json file:

```json
{
  "exclude": ["dist"],
  "include": ["**/*.ts", "**/*.tsx"],
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "checkJs": false,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "react-jsx",
    "lib": ["dom", "es2022"],
    "module": "es2022",
    "moduleResolution": "node",
    "outDir": "dist_tsc",
    "paths": { "/*": ["./*"] },
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "es2022",
  }
}
```
