### ISSUE TITLE
--no-scope-hoist breaks IE11 compatibility

### ISSUE THREAD

**Issue by hallsbyra** [parcel-bundler/parcel#6767]
# 🐛 bug report

Building a fairly large project for both modern and old browsers.

`parcel build` works fine. Producing two separate bundles. One without arrow functions and one with.

`parcel build --no-scope-hoist` produces just a single bundle, containing lots of arrow functions. Including an excerpt below.

I could probably produce a repro-repo if you need it, but I figure you might identify the problem just by glancing at the excerpt below.

Excerpt from index.[hash].js:

```
"2XT7p":[function(e,t,r){var n=e("@parcel/transformer-js/src/esmodule-helpers.js");n.defineInteropFlag(r),n.export(r,"Headers",(()=>h)),n.export(r,"Request",(()=>x)),n.export(r,"Response",(()=>k)),n.export(r,"DOMException",(()=>D)),n.export(r,"fetch",(()=>E))
```

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-rc.0
| Node             |v14.17.5
| npm/Yarn         |6.14.14
| Operating System |Win10

**Comment by mischnic** [comment]
Do you have a browserslist config that includes IE 11? https://github.com/parcel-bundler/parcel/pull/6532 should have fixed this

**Comment by hallsbyra** [comment]
Yes, IE 11 is included in browserslist. And it works fine when doing a normal `parcel build`. I then get two bundles which are loaded selectively using the module/nomodule pattern like this in `index.html`: 

```html
    <script type="module" src="/index.e2e6a083.js"></script>
    <script src="/index.da6bef8e.js" nomodule="" defer></script>
```

But when building the same project with `parcel build --no-scope-hoist` I only get a single bundle which is loaded like this in `index.html`:

```html
    <script src="/index.a0894507.js" defer></script>
```

This single bundle contains arrow functions that prevent it from being loaded in IE11.

**Comment by mischnic** [comment]
Apparently, arrow functions are emitted for code from node_modules: https://github.com/parcel-bundler/parcel/issues/6676
