### ISSUE TITLE
Fast Refresh Does Not Work With TypeScript

### ISSUE THREAD

**Issue by nmggithub** [parcel-bundler/parcel#6777]
# 🐛 bug report

Following the recipe [here](https://v2.parceljs.org/recipes/react/), a user can see the React Fast Refresh support that Parcel brings. However, this immediately stops working upon changing the `index.js` file to `index.tsx` and changing the reference in `index.html` as well. This has been documented in #4146 and #3844, and both issues are inexplicably closed. The alpha version given in #3844 fails to even bundle the recipe.

## 🎛 Configuration (.babelrc, package.json, cli command)

The CLI command is as given in the recipe: `parcel index.html`. No Babel configuration is included.

## 🤔 Expected Behavior

React Fast Refresh should continue to work with a `.tsx` file.

## 😯 Current Behavior

React Fast Refresh fails to work with a `.tsx` file.

## 💁 Possible Solution

When comparing the files emitted by Parcel in both scenarios, the only things that really changed were the five-character index and `module.bundle.HMR_BUNDLE_ID` value of a module. Not sure how that would completely stop the functionality, but I thought I would mention it.

## 🔦 Context

I am wanting to use TypeScript and React so my application is more type-safe.

## 💻 Code Sample

See recipe.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0, 1.10.0-beta.1, 2.0.0-nightly.811
| Node             | v16.8.0
| npm/Yarn         | 7.16.0
| Operating System | Arch Linux

**Comment by nmggithub** [comment]
Ok, I seem to have gotten it working to some degree, but it's still not working in my actual implementation. I'm working on figuring out why.

**Comment by nmggithub** [comment]
Ok, I solved the issue. I had previously installed `react-refresh@0.10.0` in an unrelated attempt to integrate Fast Refresh. Installing `react-refresh@0.9.0` solved the issue.

**Comment by mischnic** [comment]
What's very important is that you don't have multiple versions of `react` and `react-refresh` installed. That was probably the cause

**Comment by nmggithub** [comment]
> What's very important is that you don't have multiple versions of `react` and `react-refresh` installed. That was probably the cause

Indeed it was, as I explained in my last comment.
