### ISSUE TITLE
CSS modules do not build correctly without scope hoisting

### ISSUE THREAD

**Issue by asmockler** [parcel-bundler/parcel#6780]
# 🐛 bug report

Running `parcel build --no-scope-hoist` causes used styles to be removed.

## 🎛 Configuration (.babelrc, package.json, cli command)

I built an example repo here that demonstrates the bug: https://github.com/asmockler/parcel-css-module-bug.

There are 2 build commands, one with scope hoisting on and the other with scope hoisting off. The build to different dist dirs to make it easier to compare the output.

## 🤔 Expected Behavior

All referenced classes from CSS modules should be included whether or not scope hoisting is turned on.

## 😯 Current Behavior

With `--no-scope-hoist`, all or almost all classes are removed during build. In a larger project where I first noticed the bug, I often wind up with just a single class in the output css. 

I will also note that it seems like the build step takes a long time on `Optimizing ModuleName.[hash].css` when it exhibits this behavior, which makes me think the styles are included and then tree-shaken, but I'm not sure. 

## 💁 Possible Solution

Really not sure -- running with `--no-optimize` doesn't seem to fix it, either, though.

## 🔦 Context

I think that with `--no-scope-hoist`, it would be ok to disable all tree-shaking from CSS modules.

## 💻 Code Sample

https://github.com/asmockler/parcel-css-module-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.0-rc.0 |
| Node             | Observed on `14.16` and `16.0` |
| npm/Yarn         | Yarn `1.22.10` |
| Operating System | Mac OS Big Sur |

**Comment by jeffpeck10x** [comment]
I am having this problem too.

**Comment by jeffpeck10x** [comment]
Aha! It looks like it only includes css selectors that contain an element.

So, if your stylesheet looks like this:
```css
.tomato {
  color: tomato;
}
div.salmon {
  color: salmon;
}
```

only `div.salmon { color: salmon }` will be included in the output.

**Comment by asmockler** [comment]
I didn't notice until I had already debugged and created a PR, but this seems to be a duplicate of https://github.com/parcel-bundler/parcel/issues/5986 and my PR (#6796) is very similar to this older PR (#5728).

It does still seem to fix the issue, though.

**Comment by mischnic** [comment]
> duplicate of #5986 

👍
