### ISSUE TITLE
Error: No transformers found for src/index.html with pipeline: 'types'.

### ISSUE THREAD

**Issue by Nsbx** [parcel-bundler/parcel#6791]
# 🐛 bug report

When i run `parcel build src/index.html` i have this error message.

```
Error: No transformers found for src/index.html with pipeline: 'types'.
```

## 🤔 Expected Behavior

The command should work like the dev command `parcel src/index.html`

No problem to work with this one.

## 💻 Code Sample

https://github.com/Nsbx/marvel-cinematic-universe-watch-order

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | v14.5.0
| Yarn         |1.22.4
| Operating System | Windows 10

**Comment by mischnic** [comment]
You should remove these three lines:

https://github.com/Nsbx/marvel-cinematic-universe-watch-order/blob/1f68de418951bfe45e5caa684f10925fc891dabb/package.json#L4-L6

**Comment by Nsbx** [comment]
Oh yeah that it.
I'm so sorry, i've made so many modification to fix errors i forget these lines.
Thank :D

**Comment by fregante** [comment]
Sorry to comment here but I'm having the same issue and commenting out `types` is not an option: It's there for a reason. Demo: https://github.com/pixiebrix/webext-messenger/runs/3709379080

Is there a way to ignore it?

I'm my situation I'm using parcel to build a test harness rather than the package itself, which is a plain TypeScript transpilation.

**Comment by cowboyd** [comment]
I have the same problem as @fregante, commenting out types is not an option as parcel is being used to build a web app that is contained within the library.

Is there a workaround?

**Comment by kryops** [comment]
Just got caught by this error as well. In my case I want to build both a library and a playground web app for it to host on GitHub pages.

I solved it by creating an dummy `playground/package.json` file like

```
{
  "name": "playground",
  "private": true,
  "source": "index.html"
}
```

and then building it from the root `package.json` via `parcel build ./playground --dist-dir=docs`

**Comment by khusamov** [comment]
Good afternoon! In the end, how to solve this problem? The main, module, types field is needed. And here they offer to delete them.

**Comment by fregante** [comment]
@Nsbx please reopen this issue so it can be tracked as usual

**Comment by mischnic** [comment]
You can make Parcel completely ignore main/module/browser/types lines by adding
```js
{
  "types": "unrelated.js",
  "targets": {
    "types": false
  }
}
```
https://parceljs.org/features/targets/#library-targets

Does that solve the problem here?
