### ISSUE TITLE
Testing Parcel 2 plugins?

### ISSUE THREAD

**Issue by VladimirMikulic** [parcel-bundler/parcel#6817]
# 💬 RFC

Hi! I have migrated some of my plugins from Parcel 1 to Parcel 2.
I was able to test plugins for Parcel 1, but I am not sure how the setup would go for Parcel 2?

Plugin for Parcel 1 (with tests): https://github.com/VladimirMikulic/parcel-plugin-gas
Plugin for Parcel 2 (wondering how to test): https://github.com/VladimirMikulic/parcel-optimizer-gas

Thanks!

**Comment by thewilkybarkid** [comment]
I struggled with this too. I was able to run Parcel programmatically (https://github.com/parcel-bundler/parcel/pull/6690#issuecomment-894103899), but ran in to trouble with the plug-in handling: the project has to have itself as a dependency (was basing this on [parcel-transformer-html-datasrc](https://github.com/moritzlaube/parcel-transformer-html-datasrc)).

Ending up taking a step back and just test a complete project (which has a relative dependency on the plugin): [parcel-transformer-graphviz](https://github.com/thewilkybarkid/parcel-transformer-graphviz) and [parcel-transformer-rough-svg](https://github.com/thewilkybarkid/parcel-transformer-rough-svg) use this approach.

Not ideal, but good enough for something small.

**Comment by mischnic** [comment]
For the official plugins, we do it like this:
- there's a "project" fixture for each test: https://github.com/parcel-bundler/parcel/tree/461de1149a0312d4c541d8e5fca977a7f3c58f7e/packages/core/integration-tests/test/integration/glob containing the `.parcelrc`, sourcefiles, and an empty yarn.lock
- That is then built here: https://github.com/parcel-bundler/parcel/blob/461de1149a0312d4c541d8e5fca977a7f3c58f7e/packages/core/integration-tests/test/glob.js#L14-L27 using some utils that use the Parcel API: 
https://github.com/parcel-bundler/parcel/blob/461de1149a0312d4c541d8e5fca977a7f3c58f7e/packages/core/test-utils/src/utils.js#L208-L213
https://github.com/parcel-bundler/parcel/blob/461de1149a0312d4c541d8e5fca977a7f3c58f7e/packages/core/test-utils/src/utils.js#L105-L136

---

I would create a monorepo with your plugin and a test package (that depends on Parcel and your plugin). In the test directory, create tests as I described above and have a script that executes them via the API.
(An alternative to the monorepo would be doing something via `link:` or `file:` in package.json

**Comment by mischnic** [comment]
Related: https://github.com/parcel-bundler/parcel/issues/4241
