### ISSUE TITLE
Some Unicode character are incorrectly encoded in JSX attributes

### ISSUE THREAD

**Issue by FilipJirsak** [parcel-bundler/parcel#6820]
## 🎛 Configuration (.babelrc, package.json, cli command)

Default configuration - no `.parcelrc`, no `.babelrc`. Contents of `package.json`:

```js
{
  "name": "parceljs-test",
  "source": "src/index.html",
  "scripts": {
    "start": "parcel",
    "build": "parcel build"
  },
  "devDependencies": {
    "parcel": "^2.0.0-rc.0"    
  },
  "dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  }
}
```

## 🤔 Expected Behavior

No UTF-8 characters should be encoded. If a character needs to be encoded, there should be only one backslash in the output.

## 😯 Current Behavior

Some UTF-8 characters are encoded, but there are double backslashes in the output file. So instead of proper character, there is a backslash and code on the HTML page.

For example `0x0159` (**ř**) is not encoded (which is OK), but `0x00ED` (**í**) is encoded into `\\xed` (so **\xed** is printed on HTML page).

When the text is in between the tags, it is OK. Bad encoding occurs only in attribute values.

## 💁 Possible Solution

I don't know which component does this encoding 🤷‍♂️

## 💻 Code Sample

```html
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
</head>
<body>
    <div id="app"></div>
    <script src="./index.jsx" type="module"></script>
</body>
</html>
```

```jsx
import React from "react";
import ReactDom from "react-dom";

const Test = ({ text }) => (
    <p>{text}</p>
);

const App = () => (
<>
    <h1>Actual output</h1>
    <Test text="Příšerně žluťoučký kůň úpěl ďábelské ódy." />
    <h1>Expected output</h1>
    <p>Příšerně žluťoučký kůň úpěl ďábelské ódy.</p>
</>
)

ReactDom.render(<App />, document.getElementById("app"));
```

It actually prints:

> Př\xedšerně žluťoučk\xfd kůň \xfapěl ď\xe1belsk\xe9 \xf3dy.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | 14.17.1
| npm         | 7.20.0
| Operating System | Windows 10

**Comment by LaraMateo** [comment]
> Bad encoding occurs only in attribute values.

A temporary solution for my project was to to put brackets around the string attribute values. As described [here](https://stackoverflow.com/questions/68988558/react-project-is-not-displaying-text-as-i-intend)

**Comment by mischnic** [comment]
This is working correctly in 2.0.0-nightly.838, probably after the swc update in https://github.com/parcel-bundler/parcel/pull/6848
