### ISSUE TITLE
Chrome Crashes If Parcel Dev Server Is Stopped and Tab is Refreshed

### ISSUE THREAD

**Issue by johndanek** [parcel-bundler/parcel#6839]
# 🐛 bug report

If I start my Vue 3 app via `parcel public/index.html` everything works fine. I can navigate to http://localhost:1234 and see my app. I can refresh this tab and everything works fine. If I do a Ctrl+C on the `parcel` process in my iTerm window, the local dev server stops. If I then go back to the http://localhost:1234 tab and refresh, the browser fully crashes and exits after about 1-2 seconds. Instead, it should display the "This site can't be reached, ERR_CONNECTION_REFUSED" Chrome message.

## 🎛 Configuration (.babelrc, package.json, cli command)
No babel, and this occurs whether or not I execute it via a yarn script or directly against the `parcel` executable in node_modules/.bin

## 🤔 Expected Behavior

Chrome shouldn't crash

## 😯 Current Behavior

After 1-2 seconds, Chrome fully exits, disappears, and upon starting back up it says "Chrome did not shut down correctly".

Unfortunately, the browser crashes before I can glean any useful information from Chrome dev tools.

## 💁 Possible Solution

No idea

## 🔦 Context

The obvious answer is to not refresh the tab after stopping the dev server, but sometimes I like to confirm that the dev server has fully shut down. Also, it can be inconvenient to totally lose whatever tabs I had up.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  ^2.0.0-rc.0 |
| Node             | v12.22.3 |
| npm/Yarn         | yarn 1.19.0
| Operating System | macOS 11.5.2 |

**Comment by mischnic** [comment]
That sounds more like a Chrome bug, not a Parcel bug?

**Comment by johndanek** [comment]
> That sounds more like a Chrome bug, not a Parcel bug?

I don't really see how- this only occurs with Parcel's dev server. Not Express.js nor php's `php -S` dev server.

edit: it only appears to occur in Chrome based browsers (Chrome, Brave). Also, the issue didn't happen with `"parcel-bundler": "^1.12.5"`. I only started noticing it when I upgraded to `"parcel": "^2.0.0-rc.0"`

**Comment by LiberQuack** [comment]
I see the same problem when I try to test my current project... Chrome on Android crashes

**Comment by mischnic** [comment]
> it should display the "This site can't be reached, ERR_CONNECTION_REFUSED" Chrome message.

This is what happens for me. Chrome 93.0.4577.63, macOS 10.15.5
