### ISSUE TITLE
Build freezes and ends with `[Error: Bad file descriptor]`

### ISSUE THREAD

**Issue by Yash-Singh1** [parcel-bundler/parcel#6840]
# 🐛 bug report

Build just freezes. It successfully finishes building, but never exits, same for the serve option. After around 5 minutes it exits with `[Error: Bad file descriptor]`.

## 🎛 Configuration (.babelrc, package.json, cli command)

https://github.com/Yash-Singh1/kanda-weather/blob/main/package.json

## 🤔 Expected Behavior

It exits after building

## 😯 Current Behavior

The build never stops even if it is done. At the end it actually prints out:

```console
[Error: Bad file descriptor]
```

## 💁 Possible Solution

Force quit the build after it is done and then manually start up the application. Of course, this is not the best option when testing or publishing in CI/CD. I am pretty sure there is some sort of 

## 🔦 Context

I am trying to build my React/Redux application

## 💻 Code Sample

https://github.com/Yash-Singh1/kanda-weather

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | `^2.0.0-beta.3.1`
| Node             | `v16.3.0`
| npm/Yarn         | `7.19.1`
| Operating System | `Ubuntu 20.04.3 LTS`

**UPDATE:**

I ran `sudo npm run build` as suggested over here https://github.com/parcel-bundler/parcel/issues/6463#issuecomment-868215580, and it ended up with a lot of parsing errors related to the `parcel` scoped dependencies internal javascript files.

**Comment by lukeknxt** [comment]
I was experiencing the same and managed to find a fix for my case. It doesn't appear to be the same as the OP given their `package.json`.

I'm running Ubuntu 20.04 on WSL2.

My `package.json` contained an entry point as per the [docs](https://parceljs.org/getting-started/webapp/#package-scripts):

```json
  "source": "public/index.html",
  "scripts": {
    "start": "parcel",
    "build": "parcel build"
  },
```

Running `npm run start` or `npm run build` would result in `[Error: Bad file descriptor]`.

However explicitly passing the entry point, such as `npm run start public/index.html` ran fine. Alternatively `npx parcel public/index.html` also worked.

**Comment by Yash-Singh1** [comment]
I pass in the entrypoint to the CLI currently. I will try to specify the source option in the package.json. Another note is that the application successfully deploys to Vercel (my CD).

**Comment by CreativeCactus** [comment]
For me, the solution was to ensure that parcel was installed in `package.json`.
Ad-hoc `npx` always resulted in `[Error: Bad file descriptor]`.
Edit: Also try `typescript` and `tsc` if you use them.
