### ISSUE TITLE
Can't find stylesheet to import for nested imports (material design components)

### ISSUE THREAD

**Issue by kvantetore** [parcel-bundler/parcel#6842]
# 🐛 bug report

It seems like transformer-sass hass issues finding nested @use/@forward uses in modules imported from node_modules.

when running `yarn run parcel build src\site.js --dist-dir dist` on the following repro case, get the following error

```
@parcel/transformer-sass: Can't find stylesheet to import.
   ╷
24 │ @forward './animation' show $deceleration-curve-timing-function, $standard-curve-timing-function, $acceleration-curve-timing-function, $sharp-curve-timing-function;
   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  file:\C:\Prosjekter\ParcelTest\node_modules\@material\animation\\_variables.scss 24:1  @use
  node_modules\@material\elevation\\_elevation-theme.scss 29:1                           @forward
  node_modules\@material\elevation\\_variables.scss 24:1                                 @forward
  node_modules\@material\elevation\\_index.scss 1:1                                      @use
  src\site.scss 1:1                                                                     root stylesheet
```

src/site.js:
```js
import "./site.scss";
```

src/site.scss:
```scss
@use "@material/elevation";

.elev {
    @include elevation.elevation(3);
}
```

package.json:
```json
{
  "dependencies": {
    "@material/elevation": "^12.0.0",
    "parcel": "^2.0.0-rc.0"
  },
  "devDependencies": {
    "@parcel/transformer-sass": "2.0.0-rc.0"
  }
}
```

.sassrc:
```json
{
    "includePaths": [
        "./node_modules"
    ]
}
```

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-rc.0
| Node             |  16.8.0
| npm/Yarn         |  yarn 1.22.5
| Operating System | win10-x64

**Comment by bhellema** [comment]
I'm experiencing something similar, so I tried to rollback versions:

`v2.0.0.beta.2` & `v2.0.0.beta.3` output the following error
```
Error: ENOENT: no such file or directory, open 'file%3A/Users/a/b/c/d/project/node_modules/@spectrum/spectrum-variables/sass/spectrum-light.scss'
```
`v2.0.0.rc-0` outputs
```
Error: ENOENT: no such file or directory, open '/Users/a/b/c/d/project/file%3A/Users/a/b/c/d/project/node_modules/@spectrum/spectrum-variables/sass/spectrum-light.scss'
```
and v2.0.0.beta.1 resolves the scss correctly

**Comment by StayHomeThereIsNoFrance** [comment]
I've got same problem when migrating from parcel v1 to v2. On parcel v1 it worked

![image](https://user-images.githubusercontent.com/4202834/132015481-ff3349c7-4d63-41d5-adbe-4a9638013200.png)

v2.0.0-beta.1 shows error:
`[Error: Bad file descriptor]`

any workaround?

**Comment by devongovett** [comment]
See #6745. Sass made a breaking change in a recent version regarding this. You can either upgrade to a recent parcel nightly which works around this, or pin your sass version to an older version for now.
