### ISSUE TITLE
`stream` polyfill issue: "Error: The _read() method is not implemented"

### ISSUE THREAD

**Issue by fregante** [parcel-bundler/parcel#6846]
# 🐛 bug report

I'm unable to bundle a node package. I receive this error when I run it in the browser:

```
VM31:1882 Uncaught Error: The _read() method is not implemented
    at new NodeError2 (<anonymous>:3896:26)
    at Readable._read (<anonymous>:1389:26)
    at Readable.read (<anonymous>:1267:14)
    at flow (<anonymous>:1641:35)
    at Readable.pipeOnDrainFunctionResult (<anonymous>:1505:13)
    at Readable.emit (<anonymous>:1890:40)
    at Readable.stream.resume (<anonymous>:903:36)
    at Readable.tr.resume (<anonymous>:9309:23)
    at Readable.on (<anonymous>:1553:43)
    at Readable.pipe (<anonymous>:1451:9)
```

## 🎛 Configuration (.babelrc, package.json, cli command)

1. Create a test.js file:

```js
import test from 'tape';

test('test using promises', t => {
  t.pass();
});
```

2. Run these commands

```sh
echo '{}' > package.json
npm i tape parcel
npx parcel build test.js
```

3. Copy the content of `dist/main.js` and execute it in the browser, like in the console.

## 💁 Possible Solution

Fixing the `streams` polyfill. `stream-browserify` works in webpack. More context in the issue I opened in the library I was trying to bundle https://github.com/substack/tape/issues/561

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | v16.4.2
| npm/Yarn         | 7.18.1
| Operating System | macOS 11.5.2

**Comment by mischnic** [comment]
This is the `stream` polyfill that's used:

https://github.com/parcel-bundler/parcel/blob/f03eddda4ca3de324586a163e3341ae88a8729d8/packages/utils/node-libs-browser/index.js#L28

https://github.com/parcel-bundler/parcel/blob/f03eddda4ca3de324586a163e3341ae88a8729d8/packages/utils/node-libs-browser/package.json#L37

> "browser": { "fs": false }

Parcel essentially does this by default.

So I'm curious if there's something we could change in Parcel to fix this..

**Comment by mischnic** [comment]
Interesting, it works with if it's instead polyfilled with `stream-browserify`.

This was changed by https://github.com/parcel-bundler/parcel/pull/4225

**Comment by ljharb** [comment]
I'm confused why #4225 happened - `readable-stream` isn't a browser package, it was always meant to be a polyfill for *older node*.

**Comment by mischnic** [comment]
I wish I could remember why 😬
