### ISSUE TITLE
Import { x } from "pkg" Intellisense not working 2.0.0-rc.0

### ISSUE THREAD

**Issue by baufometic** [parcel-bundler/parcel#6855]
VSCode Version: 1.59.1
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
Date: 2021-08-19T11:54:37.513Z
Electron: 13.1.7
Chrome: 91.0.4472.124

Node.js: 16.4.1
OS: Linux x64 5.11.0-27-generic

Issue:
- Updated to the latest VSCode the other night.
- npm packages compiled with Parcel 2.0.0-rc.0 no longer display intellisense suggestions at all
- All imports use the syntax:  import { x } from "pkg"
- The build works fine, this is just an issue of intellisense not showing any of the available imports in "pkg"
- Previously working fine on both npm link (offline testing) and when pushed and downloaded from npmjs

Folder structure:
- src/index.js
- package.json
- .eslintrc.js

package.json:
main: main.js
scripts:  parcel build src/index.js
dev-deps: parcel

Never had to specify any jsconfig.json files or babel configs, one of the things I love about Parcel out of the box.

Any suggestions at all?

**Comment by mischnic** [comment]
Parcel is not responsible for Intellisense. You need to raise this with VS Code: https://github.com/microsoft/vscode
