### ISSUE TITLE
"Pause on caught exceptions" hits `Error at getBundleURL` on every page load.

### ISSUE THREAD

**Issue by lgarron** [parcel-bundler/parcel#6858]
# 🐛 bug report

"Pause on caught exceptions" hits `Error at getBundleURL` on every page load.

## 🎛 Configuration (.babelrc, package.json, cli command)

```
git clone https://github.com/cubing/cubing.js && cd cubing.js
git checkout parcel-yet-again
npx parcel src/sites/index.html
open http://localhost:1234/alpha.twizzle.net/edit/
```

If you press "Pause on exceptions" and then "Pause on caught exceptions" in Chrome, then this happens every page load:

<img width="1221" alt="Screen Shot 2021-09-01 at 10 39 52" src="https://user-images.githubusercontent.com/248078/131718108-5616078a-2da0-47f7-8653-4c6a40902b55.png">

## 🤔 Expected Behavior

It would be really nice if Parcel did not introduce an error (even if caught) on every page load. This makes it hard to debug non-deterministic bugs that require reloading the page to test, because it:

1) Interrupts the page load while trying to see if another error occurs.
2) Can affect the timing 

In this case, it was actually easy to work around, and browsers provide ways to e.g. ignore certain files. But I don't know if this is safe in general (the error is in `http://localhost:1234/__parcel_source_root/node_modules/@parcel/runtime-js/lib/helpers/bundle-url.js`, which looks like a static URL, so ignoring it may mask other issues in the future), and if you're testing in different environments it would be nice not to have to work around this.

## 😯 Current Behavior

See screenshot.

## 💁 Possible Solution

Not sure. 😕

Unfortunately, I think this has been around a long time; I'm just getting around to filing a but now.

## 🔦 Context

See above.

## 💻 Code Sample

See above.

## 🌍 Your Environment

Parcel 2.0.0-rc.0
npm 7.21.0
node v16.8.0
macOS 11.5.2

**Comment by mischnic** [comment]
There's not much we can do here, see the linked PR. For example enabling that setting in a React app also triggers the debugger multiple times.
