### ISSUE TITLE
@parcel/config-default apparently incompatible with @parcel/core

### ISSUE THREAD

**Issue by oliversalzburg** [parcel-bundler/parcel#6869]
# 🐛 bug report

@parcel/core doesn't like @parcel/config-default.

## 🎛 Configuration (.babelrc, package.json, cli command)

`.parcelrc`
```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
}
```

## 🤔 Expected Behavior

I don't know.

## 😯 Current Behavior

```shell
@parcel/core: Invalid Parcel Config

../../.yarn/cache/@parcel-config-default-npm-2.0.0-alpha.3-9c60d4348f-6797c70611.zip/node_modules/@parcel/config-default/index.json:3:2
   2 |   "bundler": "@parcel/bundler-default",
>  3 |   "transforms": {
>    |   ^^^^^^^^^^^^ Did you mean "transformers"?
   4 |     "types:*.{ts,tsx}": [
   5 |       "@parcel/transformer-typescript-types"
   6 |     ],
   7 |     "bundle-text:*": [
   8 |       "@parcel/transformer-inline-string",
   9 |       "..."
  10 |     ],
  11 |     "data-url:*": [
  12 |       "@parcel/transformer-inline-string",
  13 |       "..."
```

## 💁 Possible Solution

Don't know

## 🔦 Context

Just trying to get parcel to work.

## 💻 Code Sample

Nothing

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | v16.8.0
| npm/Yarn         | 3.0.1
| Operating System | WSL

**Comment by oliversalzburg** [comment]
Seems like this is caused by `@parcel/config-default` still pointing `latest` to `2.0.0-alpha.3`. When installing `next` or `2.0.0-rc.0` manually, this issue is resolved.

**Comment by mischnic** [comment]
> `@parcel/config-default` still pointing `latest` to `2.0.0-alpha.3`

@devongovett

**Comment by oliversalzburg** [comment]
This is also the case for several transformer plugins. I didn't keep track of which one, but maybe all tags should be checked.
