### ISSUE TITLE
Assets hash changes on every build

### ISSUE THREAD

**Issue by ittaibaratz** [parcel-bundler/parcel#6878]
# 🐛 bug report

After upgrading from Parcel 2.0.0-nightly.634 to 2.0.0-rc.0, our asset hashes keep changing on every build, even for packages which rarely change (i.e. React). This impacts the cacheability of our application making it slower and increasing our hosting costs.

For example, https://experience.adobe.com/assets/FormatMessageInterpolator.be778ff2.js which was built by nightly.634, has been in use by all our versions (Going back at least 3 months with thousands of builds) up to when we upgraded to 2.0.0-rc.0

Since then, each build generates a different hash, i.e. 
https://experience.adobe.com/assets/FormatMessageInterpolator.0557c928.js
https://experience.adobe.com/assets/FormatMessageInterpolator.0064d27c.js
https://experience.adobe.com/assets/FormatMessageInterpolator.8a99a647.js

Not sure if this is related, but looking at the content of those files, they seem to be mostly identical, only the code appears in different order, i.e.

```
r.register("1gHkZ",(function(t,r){e(t.exports,"__extends",(function(){return i})),e(t.exports,"__assign",(function(){return a})),e(t.exports,"__rest",(function(){return o})),e(t.exports,"__spreadArray",(function(){return s}));

r.register("1gHkZ",(function(t,r){e(t.exports,"__assign",(function(){return a})),e(t.exports,"__spreadArray",(function(){return o})),e(t.exports,"__extends",(function(){return i}));
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
module.exports = function (api) {
  api.cache(true);

  return {
    env: {
      production: {
        plugins: [
          [
            'transform-react-remove-prop-types',
            {mode: 'remove', removeImport: true}
          ]
        ]
      }
    },
    presets: [
      [
        '@babel/preset-env',
        {
          bugfixes: true,
          corejs: 2,
          useBuiltIns: 'entry'
        }
      ],
      '@babel/preset-react',
      '@babel/preset-typescript'
    ],
    plugins: [
      '@babel/plugin-proposal-class-properties',
      ["@babel/plugin-proposal-decorators", {decoratorsBeforeExport: true}]
    ]
  }
};
```

Note - We use a custom namer, it simply adds "-nomodules" to assets which are not modules and otherwise is an exact copy of the parcel default namer. I don't think this is related but wanted to mention it still.

## 🤔 Expected Behavior

Resources should be immutable and maintain their names across builds if code has not changed.

## 😯 Current Behavior

Resources change their names every build, even when the code has not changed.

## 🔦 Context

Improve load performance by long term browser / service worker caching.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc |
| Node             | 14.15.4|
| npm/Yarn         |yarn|
| Operating System | os/linux/windows|

**Comment by JaredSartin** [comment]
I can't quite figure out the namer customization. I just want a clean output name - I get a bunch of `index.hash.js` files and would rather `index.js`, `foo.js`, `bar.js`

My CI machine is littering the output directory with trash files now (Yes, we are checking in built assets due to the nature of the product I am building).
