### ISSUE TITLE
cssnano configuration not honored within <style> tags

### ISSUE THREAD

**Issue by aakoch** [parcel-bundler/parcel#6883]
# 🐛 bug report
cssnano configuration not honored within <style> tags, only with external files.

## 🎛 Configuration (.babelrc, package.json, cli command)
.cssnanorc
```
{
  "preset": [
    "default",
    {
      "normalizeWhitespace": false,
      "mergeRules": false
    }
  ]
}
```

```
h1 {
  color: red;
}
h1 {
  background-color: blue;
}
```

snip:
```
<style>
  h1 {
    color: red;
  }
  h1 {
    background-color: blue;
  }
</style>
<link href="issue_15.css" />
```

Full code at https://gist.github.com/aakoch/aef284a7a72a9632f290c9b291df3427

## 🤔 Expected Behavior
Inline CSS should have the same behavior as linked CSS.

## 😯 Current Behavior
All optimazations are performed on code in <style> tag but not in inlined .css file.

snip from output HTML:
```
<style>h1{background-color:blue;color:red}</style>
```

CSS file:
```
h1{
  color:red;
}
h1{
  background-color:blue;
}
```

Parcel v2.0.0-rc.0

**Comment by mischnic** [comment]
First, cssnano runs over every CSS bundle. After that, htmlnano processes the HTML file after everything was inlined (and the cssnano options aren't passed to htmlnano). So passing the cssnano configfile to htmlnano might make sense

**Comment by devongovett** [comment]
Should we disable cssnano from running as a part of htmlnano? Wouldn't it have already run before we inline the contents anyway?
