### ISSUE TITLE
Can't @import normalize.css module within .css file

### ISSUE THREAD

**Issue by lucaseverett** [parcel-bundler/parcel#6886]
# 🐛 bug report

This is regarding [normalize.css](https://github.com/necolas/normalize.css).

When attempting to @import "normalize.css" within a .css file, Parcel assumes I'm attempting to import a file named normalize.css. It was working with the prior version of Parcel I used in my package (2.0.0-nightly.711). Upon updating to the new RC I found this issue. The import works correctly in a .js file. It is only in .css that the issue happens.

## 🤔 Expected Behavior

When using @import "normalize.css" it is expected to load the file from node_modules.

## 😯 Current Behavior

Parcel assumes I'm attempting to import a file named normalize.css and throws an error.

@parcel/core: Failed to resolve 'normalize.css' from './src/common/styles.css'

## 🔦 Context

Because of this issue I'm having to include the full path to the normalize.css file in node_modules.

**Comment by mischnic** [comment]
Does https://v2.parceljs.org/languages/css/#%40import work for you?

**Comment by lucaseverett** [comment]
@mischnic Yes, the npm URL scheme works. I apologize, I didn't realize that was available.

**Comment by lucaseverett** [comment]
@mischnic Actually, I was wrong. Adding the npm URL scheme made the error go away, but it didn't actually result in the normalize.css stylesheet from node_modules being imported into the project. The import shows up literally in the final stylesheet.

`@import "npm:normalize.css";`

I also tried `@import "npm:normalize.css/normalize.css";` but that also just literally places that import in the generated stylesheet rather than pulling in the expected stylesheet from node_modules.

**Comment by lucaseverett** [comment]
The workaround I'm using is `@import "~node_modules/normalize.css";`, but I just wanted to share my experience as I believe this is a bug.

**Comment by mischnic** [comment]
It's broken with rc.0 but working correctly with `yarn add parcel@nightly`
