### ISSUE TITLE
🙋 Add styleName for React projects using css modules

### ISSUE THREAD

**Issue by barabadzhi** [parcel-bundler/parcel#689]
This is a 🙋 feature request.

It will be really nice to have `styleName` feature working out-of-the-box or with minimal configuration for React projects like it is done in [babel-plugin-react-css-modules](https://github.com/gajus/babel-plugin-react-css-modules) which is not working with Parcel.

### 🤔 Expected Behavior

Code like this should work fine too:

```js
import './App.css'

const App = () => {
    return (
        <div styleName="app">
            Hello World!
        </div>
    )
}
```

### 😯 Current Behavior

Only this one is working:

```js
import styles from './App.css'

const App = () => {
    return (
        <div className={styles.app}>
            Hello World!
        </div>
    )
}
```

It will be a bit nicer: save typing and more React-ish.

### 💁 Possible Solution

I'm not sure here, but I think it can be done same way as in [babel-plugin-react-css-modules
](https://github.com/gajus/babel-plugin-react-css-modules)

**Comment by davidnagli** [comment]
Does it work when you put `react-css-modules` as a plugin in your `.babelrc`?

**Comment by hiseni** [comment]
I have ```postcss-modules``` in my ```.babelrc``` already.

**It's trying to work, kind of.**
Everything builds and runs.
Style names come processed fine, but **style definitions** themselves are **missing**. :o:

**Comment by davidnagli** [comment]
Not sure if this is a bug or a feature 😒

**Comment by devongovett** [comment]
Can you please post an example repo that isn't working, or your full `.babelrc` and `.postcssrc` files here so we can debug?

**Comment by barabadzhi** [comment]
Hi, sure! 🗃 
```.babelrc:```
```json
{
    "plugins": [
        ["import", {
            "libraryName": "antd",
            "style": true
        }],
        ["react-css-modules", {
            "handleMissingStyleName": "warn"
        }]
    ],
    "presets": [
        ["env", {
            "targets": {
                "browsers": [
                    ">1%",
                    "last 4 versions",
                    "Firefox ESR",
                    "not ie < 11"
                ]
            }
        }],
        "stage-2",
        "react"
    ]
}
```
and ```.postcssrc:```
```json
{
    "modules": true,
    "plugins": {
        "autoprefixer": {
            "browsers": [
                ">1%",
                "last 4 versions",
                "Firefox ESR",
                "not ie < 11"
            ],
            "flexbox": "no-2009"
        },
        "css-declaration-sorter": {
            "order": "smacss"
        },
        "doiuse": {
            "browsers": [
                ">1%",
                "last 4 versions",
                "Firefox ESR",
                "not ie < 11"
            ]
        },
        "postcss-font-magician": {
            "hosted": [
                "./src/assets/fonts"
            ]
        },
        "postcss-nested": {},
        "postcss-pxtorem": {},
        "postcss-simple-vars": {}
    }
}
```

**Comment by pselden** [comment]
I was able to fix this by setting both .babelrc and .postcssrc to use the same generateScopeName:

```
{
  "plugins": [
    [
      "react-css-modules",
      {
        "generateScopedName": "[path]__[name]__[local]__[hash:base64:5]",
        "handleMissingStyleName": "warn"
      }
    ]
  ],
  "presets": ["env", "react"]
}
```

```
{
  "modules": true,
  "plugins": {
    "autoprefixer": {
      "grid": true
    },
    "postcss-modules": {
      "generateScopedName": "[path]__[name]__[local]__[hash:base64:5]"
    }
  }
}
```

**Comment by kawamurakazushi** [comment]
Can this work using typescript?

**Comment by tacc-wbomar** [comment]
I have tried to use `react-css-modules` with Parcel, also, but have failed.

I tried @pselden 's [configuration](https://github.com/parcel-bundler/parcel/issues/689#issuecomment-362171594), but my results were less successful:

1. with no changes to the configuration suggestion
```
Server running at http://localhost:1234 
⠹ Building scheduler-tracing.development.js...Unknown error from PostCSS plugin. Your current PostCSS version is 7.0.27, but parser uses 5.2.18. Perhaps this is the source of the error below.
🚨  /[...]/src/index.js: Plugin/Preset files are not allowed to export objects, only functions. In /[...]/node_modules/babel-preset-react/lib/index.js
```
2. after removing the `"presets": ["env", "react"]`, which have not been necessary, from `.babelrc`
```Server running at http://localhost:1234 
⠹ Building scheduler-tracing.development.js...Unknown error from PostCSS plugin. Your current PostCSS version is 7.0.27, but parser uses 5.2.18. Perhaps this is the source of the error below.
⠹ Building ReactPropTypesSecret.js...Unknown error from PostCSS plugin. Your current PostCSS version is 7.0.27, but parser uses 5.2.18. Perhaps this is the source of the error below.
🚨  /[...]/src/components/Nav/Nav.js: /[...]/src/components/Nav/Nav.js: ENOENT: no such file or directory, open '/src/styles/components/c-nav.css'
```

The second error is the same error I have received with all prior attempts to use `babel-plugin-react-css-modules` (which is what `react-css-modules`—deprecated—will install instead).

The `parser` mentioned at version `5.2.18` is [`postcss-modules-parser`](https://www.npmjs.com/package/postcss-modules-parser), which has been renamed to [`postcss-icss`](https://www.npmjs.com/package/postcss-icss), and does indeed [use PostCSS at version 5.x](https://github.com/css-modules/postcss-icss/blob/master/package.json#L58).
