### ISSUE TITLE
Environment variables passed via command line not overriding .env

### ISSUE THREAD

**Issue by ghost** [parcel-bundler/parcel#6900]
Our npm script is run with environment variables on the command line, for example:

```
"scripts": {
    "build": "parcel build src/index.html --dist-dir build/release",
  },
```
```
API_GATEWAY=http://some-url npm run build
```

Before upgrading to v2 the API_GATEWAY env var was respected, in v2 the value is taken from .env and not overridden.

**Comment by mischnic** [comment]
I suppose that does make sense

Corresponding code: https://github.com/parcel-bundler/parcel/blob/aee3d3640314f8ba72244b31c1e19d0f3df1b6e5/packages/core/core/src/resolveOptions.js#L110-L119

(so putting the loadEnv entry at the top would make `process.env` overwrite it)

**Comment by ghost** [comment]
Would you like me to submit a pull request?

**Comment by mischnic** [comment]
Sure, that would be great.

The test for this would look like this test case (and we can reuse the `env-file` test project):

https://github.com/parcel-bundler/parcel/blob/9b610f355998c82f96d816e266cbe453f5169079/packages/core/integration-tests/test/javascript.js#L2921-L2931

but override some one of the vars in the env file like this:

https://github.com/parcel-bundler/parcel/blob/9b610f355998c82f96d816e266cbe453f5169079/packages/core/integration-tests/test/javascript.js#L2934-L2937
