### ISSUE TITLE
TypeScript aliases not supported

### ISSUE THREAD

**Issue by danmarshall** [parcel-bundler/parcel#6902]
# 🐛 bug report

Using a [TypeScript alias](https://www.typescriptlang.org/docs/handbook/namespaces.html#aliases) results in a runtime error when using Parcel V2

```ts
namespace Shapes {
  export namespace Polygons {
    export class Triangle {}
    export class Square {}
  }
}
import polygons = Shapes.Polygons;
let sq = new polygons.Square(); // Same as 'new Shapes.Polygons.Square()'
```

## 🤔 Expected Behavior

`polygons` should be a runtime alias of `Shapes.Polygons`

## 😯 Current Behavior

`Uncaught ReferenceError: polygons is not defined`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2
| Node             | 14
| npm         | 6
| Operating System | Windows 10

**Comment by mischnic** [comment]
This was already fixed by https://github.com/parcel-bundler/parcel/pull/7033
