### ISSUE TITLE
Error with multiple Targets: "TypeError: Cannot read property 'env' of undefined"

### ISSUE THREAD

**Issue by Cannedfood** [parcel-bundler/parcel#6905]
# 🐛 bug report
This is a refiling of #1277, since it still seem to exist, or at least I am getting the same error

When using more than one target and running `parcel serve notTheFirstTarget` it will crash with the error in the title.

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```js
{
  "targets": {
    "A": { "source": "./file.html" },
    "B": { "source": "./file.html" }
  },
  "devDependencies": {
    "parcel": "^2.0.0-rc.0"
  }
}
```
Executed command:
```
parcel serve --target B
```

The content of file.html doesn't matter to reproduce this issue.

Here's a repo that can reproduce this easily:
https://github.com/Cannedfood/parcel-error-repro

## 🤔 Expected Behavior

It should build target B, or output a user-friendly error message

## 😯 Current Behavior

I'm getting this beauty:

```
  TypeError: Cannot read property 'env' of undefined
  at TargetResolver.resolve (C:\Users\bstraub\Desktop\parcel-error-repro\node_modules\@parcel\core\lib\requests\TargetRequest.js:281:56)
  at async Object.run (C:\Users\bstraub\Desktop\parcel-error-repro\node_modules\@parcel\core\lib\requests\TargetRequest.js:145:17)
  at async RequestTracker.runRequest (C:\Users\bstraub\Desktop\parcel-error-repro\node_modules\@parcel\core\lib\RequestTracker.js:703:20)
  at async AssetGraphBuilder.runTargetRequest
  (C:\Users\bstraub\Desktop\parcel-error-repro\node_modules\@parcel\core\lib\requests\AssetGraphRequest.js:711:19)
  at async PromiseQueue._runFn (C:\Users\bstraub\Desktop\parcel-error-repro\node_modules\@parcel\utils\lib\PromiseQueue.js:88:7)
  at async PromiseQueue._next (C:\Users\bstraub\Desktop\parcel-error-repro\node_modules\@parcel\utils\lib\PromiseQueue.js:75:5)
```

## 💁 Possible Solution

The following line throws because `targets` is empty
https://github.com/parcel-bundler/parcel/blob/9b610f355998c82f96d816e266cbe453f5169079/packages/core/core/src/requests/TargetRequest.js#L293

It looks like the cause for this lies here:
https://github.com/parcel-bundler/parcel/blob/9b610f355998c82f96d816e266cbe453f5169079/packages/core/core/src/requests/TargetRequest.js#L173-L178

It seems to be that `exclusiveTarget` for whatever reason always comes out to be the first target in the package.json. Unfortunately I couldn't find out where that comes from.

## 🔦 Context

I was trying to use a webbrowser target for my (Vue.js) frontend and a node target for my (express.js) backend. It looks to me like targets are the only way to accomplish this.

## 💻 Code Sample

(See Configuration)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | v16.5.0
| npm/Yarn         | npm v7.19.1
| Operating System | Windows 10

**Comment by Guichaguri** [comment]
Also seeing the same issue on 2.0.0-nightly.836

**Comment by Calpoog** [comment]
Same issue for me on the same version. Interestingly, a second target with an empty definition {} does not cause this issue. Only when there are two+ targets that have options defined. This is with the recommended setup for web extensions, with one target enabling inline sourcemaps while the other has no definition in order to not sourcemap while in prod.

**Comment by suhaotian** [comment]
![2021-10-14 at 2 08 PM](https://user-images.githubusercontent.com/6512574/137261384-6229282f-13a1-4b5d-91fc-01a722178396.png)

same here

**Comment by bao5** [comment]
I found that adding a `targets.length > 0` check avoids the exception when running `parcel serve --target B`: https://github.com/tunafield/parcel-error-repro/commit/5d4c8a7c334ae59ca8fa6e4d010f6728439d46e8

However, the patch seems incomplete since `parcel build --target` is still broken:
```
> npx parcel build --target B
√ Built in 1.14s

dist\B\file.js    34 B    305ms
> npx parcel build --target A
√ Built in 1.03s

dist\A\file.js    34 B    198ms
> npx parcel build --target B
√ Built in 429ms

dist\A\file.js    34 B    198ms
```

The last `parcel build --target B` ends up building target A. It works properly if you add `--no-cache`.

**Comment by LPGhatguy** [comment]
This issue still occurs on Parcel 2.0.0 stable. It appears to make the "Targets" feature unusable.

Has anyone else figured out a workaround without patching Parcel in the meantime?

**Comment by suhaotian** [comment]
My current solution is avoid to use target with serve, check this one https://github.com/suhaotian/parcel-starter

**Comment by OzymandiasTheGreat** [comment]
I spent the whole day trying to debug this without much success. I did figure out a workaround tho.
Basically don't put the `source` prop in the `targets` object and provide entry files on the command line like
`parcel --target browser src/index.html`
and everything seems to work so far.
You can put every other prop in the object to customize targets, just not `source`.

**Comment by mischnic** [comment]
(I've opened https://github.com/parcel-bundler/parcel/issues/7215 for tracking the caching problem from https://github.com/parcel-bundler/parcel/issues/6905#issuecomment-946988249 - cc @evaera)
