### ISSUE TITLE
Built in console log getting clobbered

### ISSUE THREAD

**Issue by jeff-hykin** [parcel-bundler/parcel#6912]
# 🐛 bug report

I think parcel is somehow messing with console.log

## 🎛 Configuration (.babelrc, package.json, cli command)

None, `npm init -y` is my package.json

## 🤔 Expected Behavior

`console.log` should keep working

## 😯 Current Behavior

`console.log` does not work after run

## 💁 Possible Solution

I'm not sure why console.log is being messed with in the first place.

## 🔦 Context

I'm just trying to run the most minimal node.js version of parcel

## 💻 Code Sample

![Screen Shot 2021-09-11 at 8 54 40 AM](https://user-images.githubusercontent.com/17692058/132950299-8b5fa32e-8199-4e78-b6d8-56053ebadb01.png)

```js
Parcel  = require("@parcel/core").default

bundler = new Parcel({
    entries: 'a.js',
    defaultConfig: '@parcel/config-default'
})

const log = console.log

var output
bundler.run().then(o=>{
    output = o
    let {bundleGraph, buildTime} = output
    let bundles = bundleGraph.getBundles()
    console.log(`✨ Built ${bundles.length} bundles in ${buildTime}ms!`);
}).catch(error=>{
    console.debug(`err is:`,err)
    console.log(err.diagnostics)
})

// wait a few sec then try using console.log
```

## 🌍 Your Environment

Using `node v15.14.0`, no config, other than `a.js` totally empty project, running inside node repl.
| Software         | Version(s) |
| ---------------- | ---------- |
| @parcel/core           | 2.0.0-next
| Node             | v15.14.0
| npm/Yarn         | 7.7.6
| Operating System | MacOS 10.13.6

**Comment by devongovett** [comment]
I believe I recently fixed that in a nightly
