### ISSUE TITLE
Preserve SSI Comments

### ISSUE THREAD

**Issue by SoftCreatR** [parcel-bundler/parcel#6920]
It would be nice if we could keep SSI comments (see https://nginx.org/en/docs/http/ngx_http_ssi_module.html) during the build. I know, that there's `"removeComments": false` in the `.htmlnanorc` available, but this preserves every comment.

**Comment by mischnic** [comment]
This would have to be fixed in htmlnano, see https://github.com/posthtml/htmlnano/issues/73

**Comment by SoftCreatR** [comment]
Done. Now, it needs to be integrated into parcel :)

**Comment by mischnic** [comment]
This should already work with a `.htmlnanorc.js` once htmlnano is published. (Though needing a JS config file for this isn't ideal)

**Comment by SoftCreatR** [comment]
A new version of htmlnano has been released (1.1.1), but parcel still uses 1.0.1, doesn't it?

**Comment by mischnic** [comment]
`1.1.1` is covered by the range `^1.0.1`: https://jubianchi.github.io/semver-check/#/^1.0.1/1.1.1
So you just need to bump your lockfile.

**Comment by SoftCreatR** [comment]
My `yarn.lock` is up to date, but my `htmlnanorc.js` is ignored by parcel (2.0.0-rc.0). Only the `.htmlnanorc` is being used, and there, I can't make it work. Even the examples (https://htmlnano.netlify.app/modules#removecomments) aren't working.

**Comment by mischnic** [comment]
It works correctly for me with 
```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title></title>
	</head>
	<body>
		<!--# include file="footer.html" -->
	</body>
</html>
```

```json
{
  "dependencies": {
    "parcel": "2.0.0-nightly.843"
  }
}
```
and `.htmlnanorc.js`:
```js
module.exports = {
	removeComments: (comments) => {
		return !comments.startsWith("<!--#");
	},
};
`

**Comment by SoftCreatR** [comment]
Well... It works 😄 I guess, I just named the file wrong or something... Thank you very much :)
