### ISSUE TITLE
Use json5 to parse JSON for code highlights

### ISSUE THREAD

**Issue by wbinnssmith** [parcel-bundler/parcel#6921]
This can end up parsing things like json Babel configs, and Babel uses json5 to parse these (e.g. comments are acceptable here). We should do the same.

https://github.com/parcel-bundler/parcel/commit/f8e2b70bd2abb3a7c43b6bdf31206367c6334036#diff-134a886fda610bacddb75cca2472cb62e57ea8a994e791e8114daca435f8ce38R400

**Comment by thewilkybarkid** [comment]
I've also seen problems with the Parcel config file, which are also JSON5.

Having something like:

```json5
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.svg": [
      "parcel-transformer-does-not-exist"
    ],
  },
}
```

When running a build with `--no-autoinstall`, the error shown is a parsing failure rather than the actual error.

```
🚨 Build failed.

Error: Unexpected token } in JSON at position 127
```

Changing the config to regular JSON:

```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.svg": [
      "parcel-transformer-does-not-exist"
    ]
  }
}
```

And running again reveals the actual error:

```
🚨 Build failed.

@parcel/core: Cannot find Parcel plugin "parcel-transformer-does-not-exist"

  [...]/.parcelrc:5:7
    4 |     "*.svg": [
  > 5 |       "parcel-transformer-does-not-exist"
  >   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Cannot find module "parcel-transformer-does-not-exist"
    6 |     ]
    7 |   }
```

**Comment by wbinnssmith** [comment]
It looks like we'll need support in our json source maps for json5 to show these correctly, so this may not be a good first issue.

**Comment by mischnic** [comment]
Related: https://github.com/json5/json5/pull/195
