### ISSUE TITLE
svgo optimizer has ill-formed if-then-else, triggering errors. 

### ISSUE THREAD

**Issue by steinwaywhw** [parcel-bundler/parcel#6924]
Hi there, just wanna point out that I left new comments on https://github.com/parcel-bundler/parcel/pull/6481, potentially a bug.

**Comment by mischnic** [comment]
When you got that error, what was the value of `config` in `loadConfig`?

**Comment by steinwaywhw** [comment]
`console.dir(config)` shows `PublicConfig {}`. `JSON.stringify(config)` shows empty.

**Comment by mischnic** [comment]
Closing in favour of https://github.com/parcel-bundler/parcel/issues/6938 as that one also lists the error message
