### ISSUE TITLE
`require.resolve` is undefined in compiled code

### ISSUE THREAD

**Issue by ascorbic** [parcel-bundler/parcel#6925]
# 🐛 bug report

In code that contains `require.resolve`, the function is replaced with `undefined`

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "parcel-bug",
  "version": "1.0.0",
  "description": "",
  "source": "src/index.js",
  "main": "lib/main.js",
  "module": "lib/module.js",
  "scripts": {
    "build": "parcel build"
  },
  "devDependencies": {
    "parcel": "^2.0.0-rc.0"
  },
  "repository": "git@github.com:ascorbic/parcel-bug.git"
}

```

The source:

```js
export function handler() {
  const pad = require.resolve("left-pad");
  console.log({ pad });
}
```

## 🤔 Expected Behavior

Line 4 is compiled to `const pad = require.resolve("left-pad");`

## 😯 Current Behavior

It is compiled to `const pad = undefined("left-pad");`

## 🔦 Context

I am writing a build plugin for Netlify and need to find the path to a dependency in the user's site.

## 💻 Code Sample

Repo: https://github.com/ascorbic/parcel-bug/

Compiled output:

```js
function $fd0e4966f38fc4e4$export$151edcd6c2cd6dd7() {
    const pad = undefined("left-pad");
    console.log({
        pad: pad
    });
}


export {$fd0e4966f38fc4e4$export$151edcd6c2cd6dd7 as handler};
//# sourceMappingURL=module.js.map
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | v16.2.0
| npm/Yarn         | npm 7.13.0
| Operating System | macOS 11.2.3

**Comment by amiller-gh** [comment]
As a note, both whatwg and Node.js have been working on `import.meta.resolve`: https://github.com/nodejs/node/pull/31032

Parcel may want to deal with this API as well.

**Comment by amiller-gh** [comment]
Workaround: re-create your require object with the `module` module.

```js
import { createRequire } from 'module';
const req = createRequire(__dirname);
req.resolve('whatever');
```

**Comment by aariacarterweir** [comment]
Would really like to see this properly resolved :)

**Comment by conorzhong** [comment]
> Would really like to see this properly resolved :)

Same

**Comment by chrisdrackett** [comment]
ran into this today. The code in question is in a 3rd party package. I'm going to attempt to patch it using the above workaround

**Comment by MBelniak** [comment]
Any plans on working on that? It makes me want to ditch parcel, as this is kinda basic functionality IMO. AFAIK webpack provides `__non_webpack_require__ ` for such things

**Comment by danieldelcore** [comment]
Wow I'm surprised it's not supported 🤔 Does anyone have any workarounds?
