### ISSUE TITLE
TypeError: xxxxx is not a function

### ISSUE THREAD

**Issue by justadev999** [parcel-bundler/parcel#6926]
Hi, i'm trying to run a function , that actually looks like a function, but apparently it is not.

This is the function => 
<img width="702" alt="Screenshot 2021-09-14 at 11 14 33 AM" src="https://user-images.githubusercontent.com/70078126/133230621-323a6d21-e9c8-43ae-9b64-6826ac1b9e54.png">

But, while running it form the Controller.js ( I'm following an MVC method ) it says me it's not a function => 
<img width="427" alt="Screenshot 2021-09-14 at 11 16 01 AM" src="https://user-images.githubusercontent.com/70078126/133230825-80efb613-89cd-46a8-a4f9-ae32704df315.png">
<img width="595" alt="Screenshot 2021-09-14 at 11 15 43 AM" src="https://user-images.githubusercontent.com/70078126/133230829-1a63a8c7-3912-4f2f-b774-56677c4c0be0.png">

Now, i'm pretty sure i linked everything fine and i've imported everything in the proper way. It's not the first time i've a similar problem with Parcel, but actually i'm not able to solve this one.
Is there anyone who could help me?
Thank you

**Comment by mischnic** [comment]
We need a complete, self contained code sample to help you. (And please don't post screenshots of code)

**Comment by justadev999** [comment]
Thank you, at the end i solved the problem and it was a mistake of mine (lol).
