### ISSUE TITLE
Simple Google Direction Service Test fails with Parcel & Parcel Bundler but works without a bundler

### ISSUE THREAD

**Issue by BigBoulard** [parcel-bundler/parcel#6927]
# 🐛 bug report

I try to make a simple test (embedded version) of the Direction Service provided by Google but it doesn't work with parcel 1 or parcel 2 npm packages. [The full test code is here](https://jsfiddle.net/Big_Boulard/n21p4ze7/3/)

## 🎛 Configuration (.babelrc, package.json, cli command)
There's no Babel configuration. I've restricted the bundler to its minimal configuration to narrow down the field of possible errors.

package.json
```js
{
  "name": "googlemaps",
  "version": "1.0.0",
  "description": "",
  "main": "index.html",
  "scripts": {
    "dev": "parcel index.html",
    "build": "parcel build index.html --dist-dir ./dist"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@googlemaps/js-api-loader": "^1.12.2",
    "parcel": "^2.0.0-rc.0"
  }
}

```

## 🤔 Expected Behavior

Once you select a destination, the route should be traced on the map

## 😯 Current Behavior

The maps loads but if you select a destination to trace the route it fails and the below error is thrown whereas it works with the same code without using any bundler.
```
code: UNKNOWN_ERROR
endpoint: DIRECTIONS_ROUTE
message: DIRECTIONS_ROUTE: UNKNOWN_ERROR: There was an issue performing a Directions Request
stack: Error: DIRECTIONS_ROUTE: UNKNOWN_ERROR: There was an issue performing a Directions request.
    at _.qA.pA [as constructor] (https://maps.googleapis.com/maps-api-v3/api/js/46/4/util.js:204:28)
    at new _.qA (https://maps.googleapis.com/maps-api-v3/api/js/46/4/util.js:204:194)
    at https://maps.googleapis.com/maps-api-v3/api/js/46/4/directions.js:9:157
    at Yha.g (https://maps.googleapis.com/maps-api-v3/api/js/46/4/directions.js:4:504)
    at Function.Xha.c.zh (https://maps.googleapis.com/maps-api-v3/api/js/46/4/common.js:107:373)
    at HTMLScriptElement.h (https://maps.googleapis.com/maps-api-v3/api/js/46/4/common.js:105:326)
```

## 💻 Code Sample

[The full test code is here](https://jsfiddle.net/Big_Boulard/n21p4ze7/3/)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |       ^2.0.0-rc.0 (tested with parcel-bundler 1.12.5 too)   
| Node             |      v16.4.2
| npm/Yarn         |     npm 7.19.1   
| Operating System |.    macOS Catalina 10.15.7 (19H1323)

**Comment by mischnic** [comment]
Did you import `@googlemaps/js-api-loader` in your JS file? Please post the exact code that you used as input for Parcel

When I take the code from jsfiddle and add a `<script src="index.js"></script>` at the bottom of the HTML file, it works fine (apart from `InvalidKeyMapError` of course)

**Comment by BigBoulard** [comment]
Hi,

js-api-loader is in the package.json because I've tried to use it in the first place but as you can see the index.html already include the javascript library

```html
<script
      src="https://maps.googleapis.com/maps/api/js?key=API_KEY_WITH_DIRECTION_SERVICE_ENABLED_HERE&callback=initMap&libraries=&v=weekly&channel=2"
      async
    ></script>
```

... indeed I just realized that it may be the source of the problem.

For  a reason I can't explain, it's working now with this code: https://jsfiddle.net/Big_Boulard/sefp9btn/5/
So, if I use Parcel, I can't load the API with a script tag in the html file, correct ?
