### ISSUE TITLE
Error thrown when building native ESM code to "global" outputFormat

### ISSUE THREAD

**Issue by quarties** [parcel-bundler/parcel#6929]
# 🐛 bug report

We have a simple library used in react apps, but also in pure HTML, loaded from our CDN. It's responsible for communication between our and customers' services. It is written with support for native ESM with `"type": "module"` inside our `package.json` file. The problem is with UMD build setup - the Parcel does not build ANY target when there is `type` set to `module` and `outputFormat` to `global`. Even if I build only the main (ESM) target, I cannot do so, as the error is thrown. When I remove the UMD target definition, the main target works perfectly fine.

## 🎛 Configuration (.babelrc, package.json, cli command)

Here is config from `package.json
```js
{
  // ...
  "type": "module",
  "main": "dist/index.js",
  "umd": "dist/umd.js",
  "source": "src/index.js",
  "files": [
    "dist/index*"
  ],
  // ...
  "scripts": {
    // ...
    "prebuild": "rm -rf .parcel-cache dist/index*",
    "build": "parcel build src/index.js --target main",
    "build-umd": "parcel build src/umd.js --target umd",
    // ...
  },
  // ...
  "devDependencies": {
    "@parcel/babel-plugin-transform-runtime": "^2.0.0-rc.0",
    "@parcel/babel-preset-env": "^2.0.0-rc.0",
    // ...
    "parcel": "^2.0.0-rc.0",
    // ...
  },
  // ...
  "babel": {
    "presets": [
      "@parcel/babel-preset-env"
    ],
    "plugins": [
      "@parcel/babel-plugin-transform-runtime"
    ]
  },
  // ...
  "browserslist": [
    "defaults"
  ],
  "targets": {
    "main": {
      "context": "node",
      "distDir": "dist",
      "includeNodeModules": false,
      "isLibrary": true,
      "optimize": true,
      "outputFormat": "esmodule",
      "scopeHoist": true,
      "sourceMap": true
    },
    "umd": {
      "context": "browser",
      "distDir": "dist",
      "includeNodeModules": true,
      "isLibrary": true,
      "optimize": true,
      "outputFormat": "global",
      "scopeHoist": true,
      "sourceMap": false
    }
  }
}
```

## 🤔 Expected Behavior

1. When I build a single target, then only its definition should be validated.
2. The UMD target with `"outputFormat": "global"` can be built from module-type libs (it worked in `2.0.0-beta.3.1`).

## 😯 Current Behavior

1. When I build a single target, then only all targets definitions are validated.
2. The UMD target with `"outputFormat": "global"` cannot be built from module-type libs.

The error:
```
michalsypko@qrt-macbook connect-bridge % npm run build

> @livechat/connect-bridge@3.0.3 prebuild
> rm -rf .parcel-cache dist/index*


> @livechat/connect-bridge@3.0.3 build
> parcel build src/index.js --target main

🚨 Build failed.

@parcel/core: Declared output format "global" does not match expected output format "esmodule".

  /Users/michalsypko/Sites/fastify-boilerplate/packages/connect-bridge/package.json:89:23
     4 |   "description": "Wrapper for Postmate library",
  >  5 |   "type": "module",
  >    |           ^^^^^^^^ Inferred output format defined here
     6 |   "keywords": [
     7 |     "util",
     8 |     "livechat",
     9 |     "postmate"
    10 |   ],
    11 |   "author": "LiveChat, Inc. <integrations@livechatinc.com>",
    12 |   "homepage": "https://github.com/livechat/fastify-boilerplate#readme",
    13 |   "license": "UNLICENSED",
    14 |   "main": "dist/index.js",
    15 |   "umd": "dist/umd.js",

  💡 Either remove the target's declared "outputFormat" or remove the "type" field
```

## 🔦 Context

This library is used both for our private and customers services (i.e. WP sites) and it's a wrapper for post-message communication. The UMD lib is used on the customer's side, the module (main) is used in our frontend project. The UMD file is not part of a package available in the `npm` registry.

## 🌍 Your Environment

| Software | Version(s) |
| --- | --- |
| Parcel | 2.0.0-rc.0 |
| Node | 14.17.0 |
| npm | 7.19.0 |
| Operating System | macOS Big Sur 11.5.2 (20G95) |

**Comment by devongovett** [comment]
Instead of `"type": "module"`, could you use the `.mjs` extension in the `"main"` field, or use the `"module"` field? That will allow you to have both targets with different module formats.

**Comment by quarties** [comment]
The other version is never shipped with the package - there's no need for that. W upload the CJS version to our CDN manually. I think about one solution however, I don't see why Parcel does not allow such action. Sorry for the late response 😅
