### ISSUE TITLE
A Bug

### ISSUE THREAD

**Issue by wisdomQiuqiu** [parcel-bundler/parcel#693]
node version is 6.10.2
parcel version is 1.5.1

when I use 'parcel index.html', has a error is
(node:31816) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: 'super' keyword unexpected here

**Comment by DepickereSven** [comment]
How did you solved this problem?

**Comment by DeMoorJasper** [comment]
@DepickereSven Node 6 & 7 are currently not supported, updating to node 8 or 9 would fix it

**Comment by davidnagli** [comment]
@DeMoorJasper Didn’t we fix support for legacy node versions via #246?

**Comment by DeMoorJasper** [comment]
@davidnagli No there are still some minor issues that need to be resolved for Node 6 support
see #253, not sure if it's still being worked on though

**Comment by DepickereSven** [comment]
I have found a solution I posted in #648
