### ISSUE TITLE
Failed to resolve imported files when migrating from Parcel 1

### ISSUE THREAD

**Issue by Jikol** [parcel-bundler/parcel#6930]
# 🐛 bug report

I can not be able to build my project with latest version of parcel 2 when migrating from parcel-bundler

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "commander",
  "version": "1.0.0",
  "description": "",
  "type": "module",
  "main": "index.js",
  "source": "index.html",
  "scripts": {
    "dev": "yarn run clean-dist && concurrently --kill-others \"yarn run parcel-dev\" \"yarn run copy-config\"",
    "build": "yarn run clean-dist && yarn run parcel-build && yarn run copy-config-build",
    "parcel-dev": "parcel index.html ./template/*.mst ./media/map/points/*.png ./media/map/symbols/*.png ./media/map/units/*.png",
    "parcel-build": "parcel build --public-url ./ index.html ./template/*.mst ./media/map/points/*.png ./media/map/symbols/*.png ./media/map/units/*.png",
    "copy-config-build": "copy-and-watch config/config.js dist/config",
    "copy-config": "copy-and-watch --watch config/config.js dist/config",
    "scss": "node-sass --watch css/style.scss -o css",
    "clean-dist": "rimraf ./dist"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "Leaflet-MovingMaker": "^0.0.1",
    "concurrently": "^6.1.0",
    "copy-and-watch": "^0.1.5",
    "dexie": "^3.0.3",
    "dirty-json": "^0.9.2",
    "hex64": "^0.4.0",
    "iconv-lite": "^0.6.2",
    "jquery": "^3.5.1",
    "jspdf": "^2.3.1",
    "jspdf-autotable": "^3.5.14",
    "leaflet": "^1.7.1",
    "leaflet-simple-map-screenshoter": "^0.4.2",
    "mustache": "^4.1.0",
    "node-sass": "^6.0.1",
    "npm-check": "^5.9.2",
    "paho-mqtt": "^1.1.0",
    "postcss": "^8.2.3",
    "rimraf": "^3.0.2",
    "sass": "^1.32.2"
  },
  "devDependencies": {
    "parcel": "latest",
    "parcel-plugin-html-externals": "^0.3.0"
  },
  "externals": {
    "config/**/*": false
  },
  "browserslist": [
    "since 2017-06"
  ]
}
```

## 🤔 Expected Behavior

Build a project as normal behavior

## 😯 Current Behavior

Can't build due to resolve fail.

 @parcel/core: Failed to resolve './modules/map/_map' from './js/index.js'
[0]   D:\Projects\WebStorm\AX\commander\js\index.js:4:19
[0]     3 | import {rabbit} from "./modules/base/_rabbit"
[0]   > 4 | import {Map} from "./modules/map/_map"
[0]   >   |                   ^^^^^^^^^^^^^^^^^^^^
[0]     5 | import {MessageHandler} from "./modules/base/_message_handler"
[0]     6 | import {InfoController} from "./modules/controllers/_info_controller"
[0]
[0]
[0] @parcel/resolver-default: Cannot load file './modules/map/_map' in './js'.

## 💁 Possible Solution

I have no idea.

## 🔦 Context

Migrate from parcel-bundler latest version to parcel latest version

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | v16.9.1
| npm/Yarn         |  7.21.1 / 1.22.11
| Operating System | Windows 10

**Comment by devongovett** [comment]
Hey, thanks for opening an issue. I'm not sure we have enough information to debug this. Could you provide a small sample project that reproduces your issue, or give us more context about your project?

**Comment by Jikol** [comment]
Of course.
https://drive.google.com/file/d/1PQ5UFbGR7uqMNQPhJ2nG-Vb0M_ejT0jv/view?usp=sharing
Small sample project with reproduced issue.

**Comment by mischnic** [comment]
I get this error with your example:

```
$ parcel build
🚨 Build failed.

@parcel/core: Failed to resolve 'config/config.js' from './js/index.js'

6930-resolve-error/js/index.js:2:25
    1 | import $ from "jquery"
  > 2 | import {staticVar} from "config/config.js"
  >   |                         ^^^^^^^^^^^^^^^^^^
    3 |
    4 | const main = () => {
```

And it works fine after this change:

```diff
--- js/index.js
+++ js/index.js
@@ -1,5 +1,5 @@
 import $ from "jquery"
-import {staticVar} from "config/config.js"
+import {staticVar} from "../config/config.js"

 const main = () => {
     $('span:nth-of-type(1)').html("fizz");
```

**Comment by Jikol** [comment]
Yes, bad path declaration, thanks for the help.
