### ISSUE TITLE
Two more LF in `bundle-text` export

### ISSUE THREAD

**Issue by loynoir** [parcel-bundler/parcel#6931]
# 🐛 bug report

Not real world use case.
Come here as unit test failed.

Although small problem, but I think should open an issue.

There are two more LF in `bundle-text` export, at the end of string.

## 🎛 Configuration (.babelrc, package.json, cli command)

No custom parcel config. Default.

FYI to else user seeing this:

If outout set to `.mjs`, `var $XXX$exports = {};` will add to tranpiled `empty.js`

```js
  // package.json, without type: module
  "main": "dist/index.js",
```

## 🤔 Expected Behavior

```js
import emptyText from "bundle-text:./empty.mjs";
test("empty: bundle-text", async () => {
    assert.equal(emptyText, "");
});
```

## 😯 Current Behavior

```js
import emptyText from "bundle-text:./empty.mjs";
test("empty: bundle-text", async () => {
    const emp = "";
    const TWO_MORE_LF = '\n\n';
    assert.equal(emptyText, `${emp}${TWO_MORE_LF}`);
});
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | 14.17.4
| pnpm         | 6.14.3

**Comment by mischnic** [comment]
In this case, `empty.mjs` is parsed and "transpiled" with swc. So I would say this is "intentional".

**Comment by loynoir** [comment]
Although not my use case, but I think might be people expect

`sourceAlikeOP(filename) === filenameContext`

Maybe also using hash as id?

As I don't know that context of parcel calling swc, might better for you to open an issue there? @mischnic

**Comment by loynoir** [comment]
@mischnic

And I found if output to `.mjs`, additional code block are added to transpiled code.
Are there any `<prefix>:` read original source code? Tried `raw:foobar`, seems no luck.

Small wish, add a `parcel --showConfig` or something, let user see all available built-in `<prefix>:`.
Like `tsc --showConfig`, `jest --showConfig`.

**Comment by loynoir** [comment]
Edit: false msg. `targets` optimization trim LF, still not original source text.

<details>
  <summary></summary>
  <p>
 
Use `targets`,  2 `LF` are gone, plus `var $XXX$exports = {};` is not added to output.  
Can I use it this way to get original source code text? 🤔

```json
  "targets": {
    "a1": {
      "source": "src/feat-a1/indexParcel.mjs"
    }
  },
```

```js
{
  emptyText: '',
  emptyUrl: '/empty.xxxxxxxx.js',
  emptyDataUrl: 'data:application/javascript,',
  // expect: 'console.log("hello world");\n',
  helloText: 'console.log("hello world");',
  helloUrl: '/hello.xxxxxxxx.js',            
}
```

```json
  "source": "src/feat-a1/indexParcel.mjs",
```

```js
{
  emptyText: '\n\n',
  emptyUrl: 'file:///path/to/dist/empty.xxxxxxxx.js',
  emptyDataUrl: 'data:application/javascript,%0A%0A',
  helloText: 'console.log("hello world");\n\n\n',
  helloUrl: 'file:///path/to/dist/hello.xxxxxxxx.js',
}
```
  </p>
</details>

**Comment by mischnic** [comment]
My point was: `bundle-text:./empty.mjs` doesn't actually read the file from disk, but it also transforms it like any other JS file. 

If you actually want the file as it is, you could use https://v2.parceljs.org/features/node-emulation/#%F0%9F%93%84-inlining-fs.readfilesync

**Comment by loynoir** [comment]
@mischnic  
I try that example twice, one for pnpm and one for yarn, core dump twice.😂

Zsh lost `Ctrl-C` control twice. Archlinux here.

```txt
@parcel/core: Failed to resolve 'fs' from './index.js'
...
@parcel/resolver-default: External dependency "fs" is not declared in package.json.
...
💡 Add "fs" as a dependency.

uv loop at [xx] has open handles:
[xx] async (active)
        Close callback: xx 
        Data: xx 
        (First field): xx  [/path/to/lmdb-store/xx]
uv loop at [xx] has 1 open handles in total
node[xx]: ../src/debug_utils.cc:322:void node::CheckedUvLoopClose(uv_loop_t*): Assertion `0 && "uv_loop_close() while having open handles"' failed.
 1: xx node::Abort() [node]
 2: xx  [node]
 3: xx  [node]
 4: xx node::worker::Worker::Run() [node]
 5: xx  [node]
 6: xx  [/usr/lib/libpthread.so.0]
 7: xx clone [/usr/lib/libc.so.6]
[1]    xx abort (core dumped)  parcel build

```

**Comment by loynoir** [comment]
Close now. Seperate coredump to new issue.

https://github.com/parcel-bundler/parcel/issues/6943
