### ISSUE TITLE
Build failing with @parcel/optimizer-svgo: Config should be an object

### ISSUE THREAD

**Issue by shreyas-jadhav** [parcel-bundler/parcel#6938]
# 🐛 bug report

Hi, currently doing a `parcel build` is failing while optimizing the SVGs in my project. 

```
> parcel build src/index.html

🚨 Build failed.

@parcel/optimizer-svgo: Config should be an object

  Error: Config should be an object
  at Object.optimize

```

I'm using the `url:../../test.svg` syntax to import SVGs and also tried all other ways to import SVGs, but coudn't get away from this error. 

## 🎛 Configuration (.babelrc, package.json, cli command)

- NPM build command: `"build": "parcel build src/index.html",` (BTW passing `--no-optimize` works)
- no `.parcelrc`
- `.babelrc`: 
- 
```js
{
	"presets": ["@babel/preset-env", "@babel/preset-react", "@babel/preset-typescript"]
}

```
- `tsconfig.json`
```
{
	"compilerOptions": {
		"target": "esnext",
		"module": "commonjs",
		"strict": true,
		"jsx": "react",
		"rootDir": "./src",
		"outDir": "dist",
		"incremental": true,
		"sourceMap": true,
		"experimentalDecorators": true,
		"lib": ["dom", "es2015"],
		"noImplicitAny": true,
		"allowSyntheticDefaultImports": true,
		"typeRoots": ["node_modules/@types"]
	},
	"include": ["src/**/*", "./index.d.ts"]
}

```
## 🤔 Expected Behavior

It should properly build without failing to optimize SVGs

## 🔦 Context
I want to use markers SVGs from my file system for a Google Map component.

## 💻 Code Sample

```ts
import marker from 'url:../../../../assets/marker.svg';

...
<Marker

    icon={{
	url:  marker,
	scaledSize: new google.maps.Size(isPlaying ? 23 : 20, isPlaying ? 23 : 20),
	fillOpacity: 1,
    }}
>

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | `^2.0.0-rc.0`
| Node             | `v12.21.0`
| npm/Yarn         | `7.20.5`
| Operating System | Lubuntu

**Comment by mischnic** [comment]
Related: https://github.com/parcel-bundler/parcel/pull/6481#discussion_r707864127, https://github.com/svg/svgo/pull/1573

**Comment by thewilkybarkid** [comment]
Updating SVGO from 2.6.0 to 2.6.1 should now resolve this.

**Comment by shreyas-jadhav** [comment]
Thanks, updating SVGO seems to have fixed the issue. :+1:
