### ISSUE TITLE
Syntax error - Unicode variable names

### ISSUE THREAD

**Issue by LukeTOBrien** [parcel-bundler/parcel#6944]
# 🐛 bug report

I am creating a Web Component library using [Lit-element](https://lit.dev/) and [BabylonJS](https://www.babylonjs.com) written in TypeScript.  
The outputted bulnde works fine on FireFox but on Chrome and Edge (Chromium) I get a syntax error and it seems to be coming from this line:

```js
class $2c12b5036883b199$export$b30baf7b91992075 extends HTMLElement {
    constructor(){
        super(), this.Î i = new Map, this.Î o = void 0, this.Î l = void 0, this.isUpdatePending = !1, this.hasUpdated = !1, this.Î h = null, this.u();
    }
```

As you can see, there is a variable named `Î` which is unicode but I think an expression like `this.Î l = void 0,` is more likely to be causing the syntax error. - Does anyone recognise that syntax? Is it es2019 or what?  
Why does FireFox recognise it but the other browsers do not?

## 🎛 Configuration

`"parcel": "^2.0.0-rc.0"`

TSConfig:
```js
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": false,
        "removeComments": true,
        "preserveConstEnums": true,
        "sourceMap": true,
        "esModuleInterop": true,
        "target": "es2019",
        "experimentalDecorators": true
    }
}
```

## 🤔 Expected Behavior

The bundled JS should be recognised on all browsers.  
I think variable names should be a-z and not unicode at all.

## 😯 Current Behavior

Code not recognised in Chrome-based browsers.

**Comment by mischnic** [comment]
Can you post the original source code of that constructor?

`this.something = void 0` is totally fine, but there shouldn't be spaces in identifiers...

**Comment by mischnic** [comment]
It comes from here: https://unpkg.com/browse/@lit/reactive-element@1.0.0-pre.1/reactive-element.js

Is possible that your server doesn't declare the document encoding correctly?

**Comment by LukeTOBrien** [comment]
Thank you for the quick reply.

I do feel a little silly, after adding `<meta charset="utf-8" />` it now works fine on Chrome and Edge.  
I was just creating a demo HTML page, I guess FireFox must automaticly detect encoding or something.  

Thanks.
