### ISSUE TITLE
Support Vue 3's `<script setup>` transform

### ISSUE THREAD

**Issue by intrnl** [parcel-bundler/parcel#6949]
# 🐛 bug report

Parcel's Vue transformer currently does not support the new [`<script setup>` transform](https://v3.vuejs.org/api/sfc-script-setup.html).

```vue
<script setup>
	import { ref } from 'vue';

	let count = ref(0);

	function increment () {
		count.value++;
	}
</script>

<template>
	<div class='red'>It's red!</div>
	<button @click='increment'>{{ count }}</button>
</template>

<style scoped>
	.red {
		color: red;
	}
</style>
```

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`
```json
{
	"type": "module",
	"name": "project",
	"scripts": {
		"serve": "parcel serve ./src/index.html",
		"build": "parcel build ./src/index.html"
	},
	"dependencies": {
		"vue": "^3.2.11"
	},
	"devDependencies": {
		"@parcel/transformer-vue": "2.0.0-nightly.2464",
		"parcel": "2.0.0-nightly.840"
	}
}
```

## 🤔 Expected Behavior

`count` should be initialized, and the button should show `0`

## 😯 Current Behavior

The `<script setup>` is ignored in the compiled code, leaving the button empty.

## 💻 Code Sample

https://github.com/intrnl/parcel-issue-vue-3-setup

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.840
| Node             | 16.9.1
| npm/Yarn         | pnpm 6.15.1
| Operating System | Arch Linux 5.14.2-197-tkg-cacule

**Comment by lowet84** [comment]
I did some digging on this. 
https://github.com/parcel-bundler/parcel/blob/5277d24b4e62a93ab7d42af8a89ee62a98e33d18/packages/transformers/vue/src/VueTransformer.js#L54-L57
The output from the parsed code contains a property "parsed.descriptor.scriptSetup" while "parsed.descriptor.script" is undefined. Vue 3 has a compiler to convert script setup to normal script. See: https://github.com/vuejs/rfcs/blob/master/active-rfcs/0040-script-setup.md
Hope this helps on the way.

**Comment by Bornegrim** [comment]
Any updates on this? Trying to migrate to parcel but not supporting Vue 3.2 features (script setup + v-bind in css) is blocking.

**Comment by enriquecaballero** [comment]
Any update on this?

**Comment by ghost** [comment]
Looking forward to this.
* Sorry for the spam.

**Comment by devongovett** [comment]
I don't have a specific update other than to say contributions are welcome. As far as I am aware no one is currently working on this. If you are interested, feel free to comment here and we'd be happy to work with you.

**Comment by Jengamon** [comment]
I've been trying to get a test environment for this set up, but it seems that @parcel/package-manager doesn't like having `link:` or `workspace:` dependencies, neither does it support Yarn "resolutions"

**Comment by Jengamon** [comment]
I have a conceptual idea of what this fix would take, I think.
I just have no idea how to go about building parcel to test this change.

AFAIK, it simply would require https://github.com/parcel-bundler/parcel/blob/5277d24b4e62a93ab7d42af8a89ee62a98e33d18/packages/transformers/vue/src/VueTransformer.js#L69

to become:
```ts
  program: {
    ...parsed.descriptor,
    script: compiler.compileScript(parsed.descriptor, {
      id: asset.id,
      isProd: options.mode === "production",
    }),
  }
```

And adding the `options` to the destructured input arguments of `parse`

**Comment by Jengamon** [comment]
Ok, I've hacked the plugin in, and have verified that this method works, how would I contribute this to the project?
