### ISSUE TITLE
Specifying `browserslist` in a `target` raises a build exception

### ISSUE THREAD

**Issue by richard-jones** [parcel-bundler/parcel#6950]
# 🐛 bug report

Specifying `browserslist` in a `target` raises a build exception

```
"demo" : {
  > 15 |       "browserslist": "> 0.5%, last 2 versions, not dead",
  >    |       ^^^^^^^^^^^^^^ Possible values: "context", "includeNodeModules", "outputFormat", "distDir", "publicUrl", "isLibrary", "sourceMap", "engines", "optimize", "scopeHoist"
```

This seems to be at odds with the documentation: https://v2.parceljs.org/features/targets/#package.json%23browserslist

The docs also say "For example, you could have a “modern” target that targets newer browsers and a “legacy” target for older browsers." which implies that a target should be able to supply its own `browserslist`.

So, this might just be a documentation bug, I'm brand new to Parcel so still figuring things out.

## 🎛 Configuration (.babelrc, package.json, cli command)

in `package.json`

```js
"targets" : {
    "demo" : {
      "browserslist": "> 0.5%, last 2 versions, not dead",
      "source" : "views/demo.html"
    }
  },
```

## 🤔 Expected Behavior

I expected it to compile the target for that browser list

## 😯 Current Behavior

```
@parcel/core: Invalid target descriptor for target "demo"

  /home/richard/Code/External/edges2/package.json:15:7
    14 |     "demo" : {
  > 15 |       "browserslist": "> 0.5%, last 2 versions, not dead",
  >    |       ^^^^^^^^^^^^^^ Possible values: "context", "includeNodeModules", "outputFormat", "distDir", "publicUrl", "isLibrary", "sourceMap", "engines", "optimize", "scopeHoist"
    16 |       "source" : "views/demo.html"
    17 |     }
```

## 🔦 Context

I'm attempting to build a module that will run natively in the browser without using ES Modules or CommonJS require functions.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc0
| Node             | v15.13.0
| npm/Yarn         | 7.7.6
| Operating System | Ubuntu 18.04

**Comment by mischnic** [comment]
https://v2.parceljs.org/features/targets/#engines:

>  The `engines.browsers` field within a target can be used just like browserslist.

So
```json
  "targets" : {
    "demo" : {
      "engines": {
          "browsers": "> 0.5%, last 2 versions, not dead"
      },
      "source" : "views/demo.html"
    }
  },
```

**Comment by richard-jones** [comment]
Great, thanks!
