### ISSUE TITLE
Failed to install @parcel/transformer-sass: Callback must be a function. Received undefined.

### ISSUE THREAD

**Issue by serverhiccups** [parcel-bundler/parcel#6954]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{ //package.json
  "name": "minimum",
  "version": "1.0.0",
  "description": "",
  "source": "src/index.html",
  "scripts": {
          "build": "parcel build",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel": "^2.0.0-rc.0"
  }
}
}
```
index.html
```html
<html>
        <head>
                <title>minimum</title>
                <link rel="stylesheet" href="main.scss">
        <head>
        <body>
        </body>
</html>
```
main.scss is an empty file so parcel attempts to install @parcel/transformer-sass.

## 🤔 Expected Behavior

Parcel correctly installs transformers before building.

## 😯 Current Behavior

I get this error when running `parcel build`
```
> minimum@1.0.0 build
> parcel build

🚨 Build failed.

Error: Failed to install @parcel/transformer-sass: Callback must be a function. Received undefined

  Error: Failed to install @parcel/transformer-sass: Callback must be a function. Received undefined
  at install (/home/serverhiccups/minimum/node_modules/@parcel/package-manager/lib/installPackage.js:131:11)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async PromiseQueue._runFn (/home/serverhiccups/minimum/node_modules/@parcel/utils/lib/PromiseQueue.js:88:7)
  at async PromiseQueue._next (/home/serverhiccups/minimum/node_modules/@parcel/utils/lib/PromiseQueue.js:75:5)
```

## 💁 Possible Solution
This error is thrown due to fs.writeFile not being supplied a callback (https://github.com/parcel-bundler/parcel/blob/v2/packages/core/package-manager/src/Npm.js#L28)
This could be changed to a promise-based version? Although I'm not sure why it's creating a `package.json` file anyway, as one already exists.

## 🔦 Context

I have developed my code on a Mac (Big Sur, Node v16.9.1, npm 7.21.1), but am now trying to build it on a Linux server. I have had no build problems on the Mac, but cannot build on linux.

## 💻 Code Sample
See configuration.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | 16.9.1
| npm/Yarn         | 7.24.0
| Operating System | Debian 10

**Comment by serverhiccups** [comment]
After not changing anything, and cloning the repo for the fifth time, it worked... so closing this issue for now.

**Comment by richard-jones** [comment]
@serverhiccups I'm having the same problem under certain circumstances.  Which repo did you repeatedly clone until this worked?

**Comment by serverhiccups** [comment]
@richard-jones It was this [repo](https://github.com/serverhiccups/refolk), but I actually think the problem might have been caused by a rogue `.parcel-cache` folder in my home directory. I think that this (or something else, idk) messes up parcel's path/module resolution algorithm.
