### ISSUE TITLE
"Cannot find name 'Set'" when generating typescript types for a library referencing react

### ISSUE THREAD

**Issue by stevejhiggs** [parcel-bundler/parcel#6956]
# 🐛 bug report

A typescript library that includes react will build fine when I don't ask babel to generate types but errors out when a "types" entry point is provided in package.json. Interestingly types are still correctly generated though.

This behaviour occurs both when using Parcels typescript compiler and @parcel/transformer-typescript-tsc.

## 🤔 Expected Behavior

Building a library that references react with type generation enabled should not error.

## 😯 Current Behavior

When build is ran without a parcel-cache, provided a type entry point is provided, you will get the following errors:

```
@parcel/transformer-typescript-types: Cannot find name 'Set'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2015' or later.

  /code/personal/parcel2-react-types-bug/node_modules/@types/react/index.d.ts:415:23
    414 |         commitTime: number,
  > 415 |         interactions: Set<SchedulerInteraction>,
  >     |                       ^^^^ Cannot find name 'Set'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2015' or later.
    416 |     ) => void;
    417 |     interface ProfilerProps {

@parcel/transformer-typescript-types: Module '"/Users/steve/code/personal/parcel2-react-types-bug/node_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flag

  /code/personal/parcel2-react-types-bug/src/Component.tsx:1:8
  > 1 | import React from "react";
  >   |        ^^^^^^ Module '"/code/personal/parcel2-react-types-bug/node\_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flag
    2 |
    3 | export const Component: React.FC = () => (

```

You will get these errors even if you switch to using `@parcel/transformer-typescript-tsc` or explictly add a tsconfig with the above values set. Interestingly types do successfully generate.

## 🔦 Context

I'm building a component library using parcel and, while most stuff works there are a few issues causing pain.

## 💻 Code Sample

https://github.com/stevejhiggs/parcel2-react-types-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2.0.0-rc0
| Node             | v14.17.3
| npm/Yarn         | Yarn
| Operating System | OSX

**Comment by jamesBennett** [comment]
I'm getting this same error. I'm exporting a react module for npm. I get the same results. The types do get generated correctly.
 
Also getting this error.
```@parcel/transformer-typescript-types: Module '"/_mylocalpath_/node_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flag``` 

I have this flag set to true in the tsconfig.json.

I have "main" and "types" output paths set in the package.json and this is my targets

```"targets": {
        "main": {
            "isLibrary": true,
            "scopeHoist": true,
            "outputFormat": "esmodule",
            "engines": {
                "browsers": "defaults"
            }
        }
    },
  ```

**Comment by stevejhiggs** [comment]
I just checked and this is still an issue in nightly 845

**Comment by stevejhiggs** [comment]
Using nightly.845 and adding the following tsconfig.json resolves the issue for me:

```
{
  "compilerOptions": {
    "lib": ["es2015"],
    "esModuleInterop": true
  }
}
```

It appears the config does not get passed down properly in rc.0
