### ISSUE TITLE
delete fn inserted by Terser? - "Calling delete on expression not allowed in strict mode"

### ISSUE THREAD

**Issue by mattlockyer** [parcel-bundler/parcel#6968]
# 🐛 bug report

Running parcel build with optimizations on (default)
![image](https://user-images.githubusercontent.com/321340/134167879-bc53c798-5ee9-4ee5-95d4-903fa8f80d45.png)

## 🎛 Configuration (.babelrc, package.json, cli command)

Failing:
```js
"scripts": {
...
"build:test": "rimraf ./.parcel-cache && parcel build src/index.html",
...
},
```

Working (clear cache is needed):
```js
"scripts": {
...
"build:test": "rimraf ./.parcel-cache && parcel build src/index.html --no-optimize",
...
},
```

## 🤔 Expected Behavior

Default optimizations work.

## 😯 Current Behavior
![image](https://user-images.githubusercontent.com/321340/134167879-bc53c798-5ee9-4ee5-95d4-903fa8f80d45.png)

## 💁 Possible Solution

Unsure...

## 🔦 Context

Can't minify with Terser.

## 🌍 Your Environment

Ubuntu 20.04
npm 7.24.0
node v14.16.1 & v16.9.1

**Comment by mattlockyer** [comment]
There's no mention of delete in my src either... I can only assume parcel/terser inserts this?
![image](https://user-images.githubusercontent.com/321340/134173562-a458d3e3-c94c-4860-96c7-e993edd56e31.png)

**Comment by mattlockyer** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Delete_in_strict_mode

**Comment by mattlockyer** [comment]
Issue is in u3 lib, unmaintained...

https://github.com/inf3rno/u3/issues/3

**Comment by ghost** [comment]
@mattlockyer My libraries are not designed for strict mode, but I can fix this tomorrow if needed. At first glance it would be just removing these rows or replacing them with `fn = undefined`. I guess I added them to avoid memory leaks, but it was 5 years ago...

**Comment by mattlockyer** [comment]
I closed the issue. It's not parcel related. Parcel is doing its job following standards. But in case anyone has this issue it's likely in your dependencies and has nothing to do with parcel.

**Comment by ghost** [comment]
@mattlockyer I upgraded the lib, it should be strict mode compatible now.
