### ISSUE TITLE
🐛 Problem resolving npm packages that end in .js (i.e. mjolnir.js)

### ISSUE THREAD

**Issue by jgable** [parcel-bundler/parcel#697]
Originally identified as part of #679, but split out as a separate issue.

### 🎛 Configuration (.babelrc, package.json, cli command)

`.babelrc`

```js
{
  "presets": ["react-app"]
}
```

`package.json`

```js
{
  "name": "providers",
  "version": "1.0.0",
  "main": "providers/static/js/index.js",
  "repository": "[not my repo, so redacted]",
  "author": "Jacob Gable <jacob.gable@gmail.com>",
  "license": "Private",
  "private": true,
  "dependencies": {
    "babel-preset-react-app": "^3.1.1",
    "parcel-bundler": "^1.5.1",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-loadable": "^5.3.1",
    "react-map-gl": "3.2.1",
    "react-router-dom": "^4.2.2"
  },
  "scripts": {
    "build": "parcel build providers/static/js/app.js -d providers/static/js/built",
    "watch": "parcel watch providers/static/js/app.js -d providers/static/js/built"
  }
}
```

### 🤔 Expected Behavior

Should bundle `react-map-gl` (which has the mjolnir.js dependency) correctly.

### 😯 Current Behavior

```shell
/Users/jgable/projects/providers/node_modules/react-map-gl/dist-es6/components/interactive-map.js:19:29: Cannot resolve dependency 'mjolnir.js'
  17 | import TransitionManager from '../utils/transition-manager';
  18 | 
> 19 | import { EventManager } from 'mjolnir.js';
     |                              ^
  20 | import MapControls from '../utils/map-controls';
  21 | import config from '../config';
  22 | import deprecateWarn from '../utils/deprecate-warn';
```

### 💁 Possible Solution

via #679 and @davidnagli 

> it looks like Parcel has an edge case where it treats the .js in the name as meaning that it’s a file name rather than a package name.

### 🔦 Context

Nothing more to add.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.5.1
| Node             | 9.4.0
| npm/Yarn         | npm 5.6.0, yarn 1.3.2
| Operating System | macOS Sierra (0.12.6 (16G29))

**Comment by AgentEpsilon** [comment]
It looks like the problem was on `react-map-gl`'s side, and their issue (uber/react-map-gl#472) has been closed. I can't reproduce the issue in my own testing either. @davidnagli could this issue be closed?
