### ISSUE TITLE
Material-UI Failing in Parcel 2.0.0-rc.0

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#6970]
### Discussed in https://github.com/parcel-bundler/parcel/discussions/6966

<div type='discussions-op-text'>

<sup>Originally posted by **TheNathanBlake** September 21, 2021</sup>
Hi there,

I'm currently trying to build a project using Material-UI and Parcel V2 and PUGs (2.0.0-rc.0), and on running `parcel serve` I can successfully build the project, but trying to navigate to the locally deploy web page gives me the following error:

<img width="547" alt="Screen Shot 2021-09-20 at 6 41 43 PM" src="https://user-images.githubusercontent.com/9566223/134091802-8c918aa6-28e6-44a4-83a6-aa085e8e2eb3.png">

This seems to come from an unrelated colors import/export in the index.d.ts:
<img width="448" alt="Screen Shot 2021-09-20 at 6 43 08 PM" src="https://user-images.githubusercontent.com/9566223/134091849-ec8abb38-ead7-4cd5-af11-6a996303943e.png">
 
Normally I'd post this on the material-ui GitHub, but for some reason, reverting Parcel to v2.0.0-beta.3.1 solves this issue.

Does anybody know enough about Material UI or building with Parcel for React projects to point me in the right direction on this issue?

Here's a link to an example project that breaks: https://github.com/TheNathanBlake/parcel-pug-material-ui-example
</div>

**Comment by mischnic** [comment]
Reproduction (with `--no-scope-hoist`):

```js
// index.js
import { foo } from "./lib.js";
console.log("value =", foo);

// lib.js
export * from "./core.js";
export { default as foo } from "./foo.js";

// core.js
console.log("core");
export const foo = "core";

// foo.js
console.log("foo");
export default "foo";
```

The output for `lib.js` is

```js
var parcelHelpers = require("@parcel/transformer-js/src/esmodule-helpers.js");
parcelHelpers.defineInteropFlag(exports);
parcelHelpers.export(exports, "useAutocomplete", ()=>_useAutocompleteDefault.default
);
var _core = require("@mui/core");
parcelHelpers.exportAll(_core, exports);
var _useAutocomplete = require("./useAutocomplete");
var _useAutocompleteDefault = parcelHelpers.interopDefault(_useAutocomplete);
```

The `parcelHelpers.exportAll`  call reads `exports.useAutocomplete` here
https://github.com/parcel-bundler/parcel/blob/1b980caf31e324fd2285d4301067191e4ad99243/packages/transformers/js/src/esmodule-helpers.js#L15-L19
but `_useAutocompleteDefault` isn't defined yet.

Related: https://github.com/parcel-bundler/parcel/issues/6344

**Comment by wunderman4** [comment]
I am also hitting this problem, I went to Material-UI and opened a ticket, they told me to come here instead. Here is the link to the ticket which has another example project. https://github.com/mui-org/material-ui/issues/28526

Work around for now is to import each item individually.

**Comment by JILeXanDR** [comment]
I have the same problem, any thoughts how to fix it?

**Comment by wunderman4** [comment]
@JILeXanDR If you switch the import style to default imports instead of grouping them, it should fix the problem. Here is an example.
https://github.com/wunderman4/muiParcelBadImports/blob/main/src/App.jsx

**Comment by Poky85** [comment]
@wunderman4 Thank you, seems to solve the issue. Although I would like to know the root of the problem knowing that nothing will break after adding another import.

**Comment by wunderman4** [comment]
@Poky85 for now, the only option is to direct import when you use a component from the package thats causing issues. 

In my project any import from @mui/material that references @mui/core, the default is reported as undefined. I tried a few different ways and nothing seemed to work besides commenting those exports out from @mui/material/index.js. 

Seems like the root problem is how those imports are getting handled by parcel.

**Comment by wunderman4** [comment]
Thanks @devongovett much appreciated :)
