### ISSUE TITLE
SVG sprite becomes completely empty on build

### ISSUE THREAD

**Issue by yttrian** [parcel-bundler/parcel#6979]
# 🐛 bug report

When using the Font Awesome Brands SVG sprite in development, icons show up fine. But when `parcel build src/*.html` is ran, the SVG file becomes completely empty.

## 🎛 Configuration (.babelrc, package.json, cli command)

Snippet from `package.json`

```js
"devDependencies": {
    "@parcel/transformer-image": "2.0.0-rc.0",
    "@parcel/transformer-sass": "2.0.0-rc.0",
    "parcel": "^2.0.0-rc.0"
},
"dependencies": {
    "@fortawesome/fontawesome-free": "^5.15.4",
    "jquery": "^3.6.0"
},
```

Nothing else.

## 🤔 Expected Behavior

The SVG file should not be empty.

## 😯 Current Behavior

The SVG file is completely empty.

```
dist\brands.38d394c2.svg                  0 B    2.26s
```

## 💁 Possible Solution

I wish I knew.

## 🔦 Context

I want to build and deploy my website, but my SVGs that work when using the dev server are gone after doing a build.

I followed this https://fontawesome.com/v5.15/how-to-use/on-the-web/advanced/svg-sprites but used `href` instead of `xlink:href`. Using `xlink:href` doesn't appear to fix this issue either.

## 💻 Code Sample

```html
<svg>
    <use href="../node_modules/@fortawesome/fontawesome-free/sprites/brands.svg#linkedin"></use>
</svg>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0 |
| Node             | 14.17.6 LTS |
| npm/Yarn         | pnpm 6.12.0 |
| Operating System | Windows 10 21H1 |

**Comment by devongovett** [comment]
Probably another case of bad SVGO defaults. It's on the list to fix
