### ISSUE TITLE
@font-face files omitted when building with parcel build index.html

### ISSUE THREAD

**Issue by brielov** [parcel-bundler/parcel#698]
```javascript
import { h, app } from 'hyperapp';
import 'normalize.css';
import 'typeface-varela-round';
import './index.css';
```

This works fine when running `parcel index.html` but it does not work using `parcel build index.html`
Somehow, the typeface file gets omitted. The only way it'll work is if I manually copy the @font-face declaration to another css file that already contains some other css.

**Comment by yunyu** [comment]
I'm having this issue even when the @font-faces are included in a file with another CSS. They are just getting completely eaten from the output.

**Comment by olizilla** [comment]
I'm seeing this too. Is it possible to alter parcels cssnano config? It feels like it's related to http://cssnano.co/optimisations/discardunused/

**Comment by olizilla** [comment]
From parcel is currently using cssnano 3.10, and from the readme for that version:

> Note that cssnano enables aggressive optimisations by default, which might not always be what you want. Set options.safe to true if you want to disable this. In future versions, only safe options will be enabled by default, starting from version 4.

**Comment by DeMoorJasper** [comment]
You can use `cssnano.config.js` to configure cssnano

**Comment by olizilla** [comment]
@DeMoorJasper Could you share an example? I'm just scraping around the internet trying to find documentation, and it looks like it's a cssnano.config.js [was to be a cssnano v4](https://github.com/ben-eb/cssnano/issues/91) thing and parcel's [package.json on master](https://github.com/parcel-bundler/parcel/blob/master/package.json#L23) is pointing at cssnano@3.10

**Comment by DeMoorJasper** [comment]
Well it basically is the options that are passed to cssnano, it's being handled by parcel and passed as the options.
A random example taken from the cssnano website:
`cssnano.config.js`:
```Javascript
module.exports = {
  preset: ['default', {
    discardComments: {
      removeAll: true,
    },
  }]
};
```
And Parcel handles it like this:
```Javascript
cssnano((await asset.getConfig(['cssnano.config.js']))
```
Details: https://github.com/parcel-bundler/parcel/blob/9eac73e21dba7dfdf4d408902e206d76364ba9af/src/transforms/postcss.js#L54

**Comment by yunyu** [comment]
Would it make sense to preemptively apply the cssnano 4 safe defaults behavior to Parcel (to avoid breaking things for new users)?

**Comment by DeMoorJasper** [comment]
If it fixes the issue, it's probably a good idea. Although it might enlarge bundles for when this is not necessary, perhaps either detecting it or documenting it would be the best way?
