### ISSUE TITLE
Parcel cannot build react-toolbox

### ISSUE THREAD

**Issue by ngkahinkeith** [parcel-bundler/parcel#6989]
# 🐛 bug report
I am using parcel `2.0.0-rc.0` with docker, but parcel is unable to start the dev server or build production due to some error with `@parcel/transformer-js` and `react-toolbox`.

## 🎛 Configuration (.babelrc, package.json, cli command)

Package.json
```js
{
  "name": "parcel-react-toolbox-bug",
  "version": "0.0.0",
  "scripts": {
    "build": "parcel build index.html --dist-dir build/release --public-url ./",
    "dev": "parcel index.html --dist-dir build/debug -p 80 --host 0.0.0.0 --no-autoinstall --hmr-port 43575"
  },
  "dependencies": {
    "parcel": "^2.0.0-rc.0",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "react-toolbox": "^2.0.0-beta.13"
  },
  "devDependencies": {}
}
```

## 🤔 Expected Behavior

parcel should build and run react-toolbox without error

## 😯 Current Behavior

parcel cannot start the dev server or build production

<img width="751" alt="Screen Shot 2021-09-27 at 3 33 31 PM" src="https://user-images.githubusercontent.com/79431961/134864112-0f1bbff0-355e-49c2-9300-c6132496ce12.png">

<img width="752" alt="Screen Shot 2021-09-27 at 3 55 27 PM" src="https://user-images.githubusercontent.com/79431961/134867368-422a0352-32e8-4de3-880f-9993202f518d.png">

## 💻 Code Sample

[https://github.com/ngkahinkeith/parcel-react-toolbox-bug](https://github.com/ngkahinkeith/parcel-react-toolbox-bug)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |   2.0.0-rc.0
| Node             |    14-alpine3.13 (14.17.6)
| npm/Yarn         |   yarn with 1.22.5
| Operating System |   macOS 11.3 with docker engine 20.10.7

**Comment by mischnic** [comment]
Parcel doesn't support published npm packages that contain untranspiled Flow/Typescript or JSX syntax

**Comment by ngkahinkeith** [comment]
I just try using the last beta version `2.0.0-beta.3.1`, it can be able to run and build by adding the flag `--no-scope-hoist` while the `2.0.0-rc.0` cannot.

Is there any suggestion or config (like babel) need to be setup if I need to use react-toolbox?

thank you
