### ISSUE TITLE
Support for Custom Typescript transformers

### ISSUE THREAD

**Issue by deamme** [parcel-bundler/parcel#699]
Any plans to support custom typescript transformers? So I can use https://github.com/deamme/ts-transform-css-modules-next, https://github.com/deamme/ts-transform-inferno etc.

References:
https://github.com/Microsoft/TypeScript/pull/13940
https://github.com/TypeStrong/ts-loader/pull/535

**Comment by chenshuai2144** [comment]
+1 
I want to use ts-import-plugin
