### ISSUE TITLE
V2: Require is undefined

### ISSUE THREAD

**Issue by LukeTOBrien** [parcel-bundler/parcel#6997]
# 🐛 bug report

I have looked at https://github.com/parcel-bundler/parcel/issues/4914 and https://github.com/parcel-bundler/parcel/issues/4199 but neither sorted my issue.

I am creating a component library using [Lit](https://lit.dev/) with TypeScript, I am importing external dependancies but a lot of them do not get bundled into the final `js` file, instead I get a lot of `require` statements at the top.  
The only recent change I have mad to my project is updating Parcel from beta to the most recent.  
Do you know of any change that might of effected bundling?

This is what I have at the end of my output JS file:
```js
var $6PrNV$jquery = require("jquery");
var $6PrNV$lit = require("lit");
var $6PrNV$litdecorators = require("lit/decorators");
var $6PrNV$bundletextsimonweppickrdistthemesnanomincss = require("bundle-text:@simonwep/pickr/dist/themes/nano.min.css");
var $6PrNV$simonweppickr = require("@simonwep/pickr");
var $6PrNV$interactjsinteractjs = require("@interactjs/interactjs");
var $6PrNV$tippyjs = require("tippy.js");
var $6PrNV$bundletexttippyjsdisttippycss = require("bundle-text:tippy.js/dist/tippy.css");
var $6PrNV$litdirectivesunsafehtmljs = require("lit/directives/unsafe-html.js");
var $6PrNV$popperjscore = require("@popperjs/core");
var $6PrNV$hammerjs = require("hammerjs");
var $6PrNV$binddecorator = require("bind-decorator");
```

## 🎛 Configuration (.babelrc, package.json, cli command)

`parcelrc`
```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
}
```

`tsconfig`
```js
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": false,
        "removeComments": true,
        "preserveConstEnums": true,
        "sourceMap": true,
        "esModuleInterop": true,
        "target": "es2019",
        "experimentalDecorators": true
    }
}
```

## 🤔 Expected Behavior

The bundle size should be larger than it is and the bundle should include all imported libraries.

## 😯 Current Behavior

The oututted bundle is only `122KB`  and includeds `require` statement form imports.

## 💁 Possible Solution

Roll back to previous version when it was working fine.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-rc.0
| Node             |  v14.15.1
| npm/Yarn         | 6.14.8
| Operating System | Win10

**Comment by devongovett** [comment]
Maybe you have a main field in your package.json? Looks like it's being compiled as a library. See https://v2.parceljs.org/features/targets/#library-targets

**Comment by LukeTOBrien** [comment]
Thanks that did do the trick... I wouldn't of expected that.  
It is my intention to publish this project to public NPM registry and I understood that a `"main"` was necessary.

So the `"main"` overrides everything? Even if I use the `CLI` like `parcel build my-project.ts` the `main` will still take priority?

**Comment by devongovett** [comment]
The main is the output path, not the input. That way your build can be consumed by other tools.

**Comment by LukeTOBrien** [comment]
....okay well I guess I'll sort that out when I come to it.  

Now I am getting the following error `Unexpected token punc «.», expected punc «,»`... This project built successfully a few minutes ago!  
IMO, Parcel 2 is very unstable, the amount of trouble I have gone through getting my projects to build compared with Parcel 1 has been been too much. Parcel 1 was instantaneous, no problem, but Parcel 2 has been error after error.

**Comment by devongovett** [comment]
Sorry to hear that. However it's very hard for us to help you with so little context. Can you give us more details about your project, the errors you're seeing, etc.? A code sample would also be helpful.

**Comment by devongovett** [comment]
btw, it sounds like you actually do want to build a library, but want everything including 3rd party dependencies to be bundled? The default when building libraries is not to bundle external code (e.g. `lit`, `jquery`, etc.) which is why you see the require calls. If you want to configure Parcel to include node_modules when bundling the library, see https://v2.parceljs.org/features/targets/#includenodemodules.

**Comment by LukeTOBrien** [comment]
Thank you for your help RE include node modules, I have now switched to using the `"main"` again and it build okay.

I have had the `Unexpected token punc «.», expected punc «,»` error before, no filename is given, just this error. I think I never mentioned it before because it just goes away on it's own, shut down the laptop, the next day the error is gone.
However I am now getting another runtime error (which I think I had before too): In FireFox 92.0.1 `Uncaught SyntaxError: missing : after property id` (in Chrome 94.0 `Unexpected token '.'`, the offending code seems to be: 
```js
$7abYt.default.__utils = {
    $gs06g.exchange,
    $8kqXX,
    pointer: $7kYv1
};
```
Do you know what would cause this kind of output?  
Would it be my tsconfig (above)?  
I have also added `"browserslist": "last 2 Chrome versions"` to package.json

**Comment by devongovett** [comment]
That's strange. Any idea where the original code is coming from?

**Comment by LukeTOBrien** [comment]
... It was from [this node package](https://www.npmjs.com/package/@interactjs/interactjs) I updated the package and the error went away.  
I have no errors anymore so I will close this issue. Thank you very much for your help.
