### ISSUE TITLE
Parcel v2 ignores terser compress option (switches)

### ISSUE THREAD

**Issue by jiroler** [parcel-bundler/parcel#6999]
# 🐛 bug report

## 🎛  package.json

```json
{
  ...
  "check": "check.build.js",
  "targets": {
    "check": {
        "distDir": "./",
        "publicUrl": "./"
    }
  },
  "devDependencies": {
    "parcel": "^2.0.0-rc.0"
  }
}
```

## 🎛  .terserrc
```json
{
    "output": {
        "comments": true
    },
    "compress": {
        "switches": false
    }
}
```

## 🎛  check.js

```js
switch (true) {
    case true: console.error('true'); break
    default: console.error('default'); break
}
```

## 🎛  Cli command
```shell
npx parcel build ./check.js --target check
```

## 🤔 Expected Behavior (check.build.js)

```js
switch(!0){case!0:console.error("true");break;default:console.error("default");break}
```

## 😯 Current Behavior (check.build.js)

```js
console.error("default")
```

It is strange, because even if options is `"switches": true` (by default) output result incorrect. 
I checked build using only terser:
```shell
$ npx terser --compress -- check.js
console.error("true");

$ npx terser --compress "switches=false"  -- check.js
switch(!0){case!0:console.error("true");break;default:console.error("default");break}
```

This is `case true` branch, instead 'default' branch using compress.

## 🌍 My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | v14.17.3
| npm        | 6.14.13
| Operating System | Mac OS

**Comment by SoftCreatR** [comment]
Did you try a nightly build of parcel? Maybe that works.

**Comment by jiroler** [comment]
@SoftCreatR I tried `parcel@nightly` (`"parcel": "^2.0.0-nightly.845"`) and got the same result

**Comment by mischnic** [comment]
This is actually not caused by Terser, the input for Terser is already
```js
(() => {
console.error('default');

})();
```

It's optimized by swc: https://github.com/parcel-bundler/parcel/blob/5277d24b4e62a93ab7d42af8a89ee62a98e33d18/packages/transformers/js/core/src/lib.rs#L308-L311

What is your usecase for not optimizing switches?

**Comment by jiroler** [comment]
@mischnic I thought terser optimizes dead switch branches incorrect during writing this issue. I searched simple solution for my case.
Now I see this is problem of swc. I'll create issue in swc repo

**Comment by jiroler** [comment]
swc incorrect handles any `switch(true){}` block with `default:` branch

**Comment by jiroler** [comment]
https://github.com/swc-project/swc/issues/2328
