### ISSUE TITLE
Angular 2/4/5+ testing/support?

### ISSUE THREAD

**Issue by omouse** [parcel-bundler/parcel#7]
Without TypeScript support would be cool (though the Angular team is working really hard to push TypeScript).

**Comment by devongovett** [comment]
Typescript is being discussed in #3. What other things are needed for this issue?

**Comment by thejameskyle** [comment]
I'm pretty sure this is just TypeScript support, closing unless someone knows of additional requirements

**Comment by omouse** [comment]
I mentioned "without Typescript support" because it is possible to use Angular 2/4/5+ with plain JavaScript and may be easier to fix than implementing typescript support.

when I've got some time I'll give both AngularJS 1.x and Angular 2+ (plain javascript *no* typescript) a try to see what happens. Parcel looks promising!

**Comment by DeMoorJasper** [comment]
@omouse i made a super small boilerplate for angular and it does work just fine as far as i tested it https://github.com/DeMoorJasper/Angular-Parcel-Boilerplate

**Comment by filipesilva** [comment]
For Angular projects `ngc` (the Angular compiler) is also used as a replacement for TypeScript. Is it possible to override the default `TypeScriptAsset` with a plugin?

**Comment by DeMoorJasper** [comment]
It is possible to do so, u can have a look at [the plugins docs](https://parceljs.org/plugins.html).
Just setting extension to .ts and .tsx would overwrite the TypeScript Module.

**Comment by tatsujb** [comment]
@DeMoorJasper that boilerplate no longer works :(
