### ISSUE TITLE
SCSS build appears to succeed but outputs nothing

### ISSUE THREAD

**Issue by richard-jones** [parcel-bundler/parcel#7004]
# 🐛 bug report

Building an `scss` file does not output anything - no resulting file and no errors.

I'm running the command

```bash
parcel build --log-level verbose --detailed-report 10 sass/all.scss
```

(wrapped in a package.json script)

The output of this is

```
> edges@2.0.0-SNAPSHOT build-styles
> npm run clean-styles && parcel build --log-level verbose --detailed-report 10 sass/main.scss


> edges@2.0.0-SNAPSHOT clean-styles
> rm -rf ./.parcel-cache

✨ Built in 293ms
```

The verbose logging and detailed report do not output anything.  No resulting css file is generated in the `dist` folder (or anywhere else).

## 🎛 Configuration (.babelrc, package.json, cli command)

There's nothing particularly special about `package.json`, though these are the dependencies:

```json
"devDependencies": {
    "@babel/core": "^7.15.5",
    "@babel/plugin-transform-runtime": "^7.15.0",
    "parcel": "latest",
    "sass": "^1.39.2"
  },
  "dependencies": {
    "@parcel/transformer-sass": "^2.0.0-rc.0",
    "@babel/runtime-corejs2": "^7.15.4",
    "@swc/helpers": "^0.2.13",
    "jquery": "^3.6.0"
  }
```

`.babelrc` is

```json
{
  "plugins": [
    [
      "@babel/plugin-transform-runtime",
      {
        "corejs": 2,
        "regenerator": true
      }
    ]
  ]
}
```

## 🤔 Expected Behavior

Output a css file to the `dist` directory

## 😯 Current Behavior

Nothing happens, though it looks like it does (see description above).

## 💁 Possible Solution

No idea, I'm afraid.

## 🔦 Context

I'm currently unable to build my scss files for production, though `parcel serve` doesn't seem to have any problems building the files, so I am able still to use them for development.

## 💻 Code Sample

N/A

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc0
| Node             | v15.13.0
| npm/Yarn         | 7.7.6
| Operating System | Ubuntu 18.04

**Comment by mischnic** [comment]
Please provide a code sample that reproduces the issue.

**Comment by Razunter** [comment]
I don't know if it's the same issue, but it seems like Parcel isn't writing files if they are not changed since caching. This causes problems since it's common to cleanup build files on every rebuild. One way to solve it is to disable cache, but there should be a better solution.

**Comment by mischnic** [comment]
@Razunter It only skips writing bundles to the distdir if they haven't been deleted in the meantime.

**Comment by Razunter** [comment]
> @Razunter It only skips writing bundles to the distdir if they haven't been deleted in the meantime.

Not true in my case, it doesn't write bundle even when files are missing.
```
  "source": [
    "src/js/index.js",
    "src/css/index.scss"
  ],
  "targets": {
    "default": {
      "distDir": "./dist"
    }
  },
```
```
    "build": "cross-env NODE_ENV=production npm-run-all clean prod:parcel prod:eleventy",
    "clean": "rimraf \"dist/!(img)\"",
    "prod:eleventy": "eleventy --quiet",
    "prod:parcel": "parcel build --no-source-maps",
```

Windows, Node 14.

Parcel writes to log like it created files, but no files are actually created.
>dist\js\index.js       94.74 KB    1.47s
>dist\css\index.css    119.98 KB    1.94s

**Comment by brianhelba** [comment]
@mischnic I'm independently experiencing this problem too. On rebuilds with no changes to the source, Parcel reports that that the files were output, but does not write them to disk if they were already missing.

---

For my `package.json` with no customization of Parcel beyond:
```json
"build:clean": "rimraf ../project/static/",
"build:compile": "parcel build ./src/widget.ts --dist-dir ../project/static/ --no-source-maps",
"build": "npm-run-all build:clean build:compile"
```

If I run `npm run build`, it succeeds the first time, but on subsequent runs (or if I just delete the output files by hand and run `npm run build:compile`), it emits output:
```sh
✨ Built in 211ms

../project/static/widget.js     23.27 KB    549ms
../project/static/widget.css     1.85 KB    832ms
```
but the output directory is empty!

However, deleting `.parcel-cache` solves this for the next run (it writes the files properly again once).

---

I'm using:
```sh
npm run parcel --version
7.21.1
```

**Comment by mischnic** [comment]
@brianhelba In your case, the problem is probably that your dist dir is outside of the project root, so Parcel doesn't actually watch this and doesn't know when files were deleted. -> https://github.com/parcel-bundler/parcel/issues/7186

@Razunter I've tested it on Windows, and it seems to work correctly for me. Can you provide a full reproduction that I can clone?

**Comment by Razunter** [comment]
Failed to reproduce now too, don't know why 🤷‍♂️
