### ISSUE TITLE
[2.0.0-beta.2 -> 2.0.0-rc.0] getting "Error: Cannot find module '@parcel/babel-preset-env'"

### ISSUE THREAD

**Issue by yairEO** [parcel-bundler/parcel#7010]
I've tried searching in the issues and also google but found nothing of interest.

# 🐛 bug report

After upgrading `parcel` version from `2.0.0-beta.2` to `2.0.0-rc.0` I'm getting this error in the terminal: 
 
   Error: Cannot find module '@parcel/babel-preset-env'

![image](https://user-images.githubusercontent.com/845031/135732530-e67ebcbf-5b42-4e93-b7aa-6a707ff828b4.png)

## 🔦 Context

I simply wished to upgrade from version `2.0.0-beta.2` to `2.0.0-rc.0`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | v12.22.5
| npm/Yarn         | 7.9.0
| Operating System | Windows 10

**Comment by mischnic** [comment]
You need to list all plugin in your Babel config as dependencies. So add `@parcel/babel-preset-env` to package.json as well

**Comment by yairEO** [comment]
@mischnic - but it worked good without `@parcel/babel-preset-env` being manually installed as a dev dependency in Parcel version `2.0.0-beta.2`, why suddenly do all this extra things if Parcel's whole idea is to simplify things? Parcel has only been making things more difficult in the few years I have used it..

**Comment by mischnic** [comment]
It was always the case that you need to specify all packages that you rely on (in config files), this is the same situation as with `@babel/preset-env` (and a package manager like Yarn 3 would also have enforced this previously).
It worked previously only by coincidence because that package was a dependency of some other package (which was changed between beta and rc, so now it's not installed anymore).

**Comment by yairEO** [comment]
@mischnic - I need `@parcel/babel-preset-env` not `@babel/preset-env`. How can you say *"it has always been the case"* when clearly it was not with `beta-2`? 

I HARDLY believe this is a "coincidence", since this lib is extremely specific, meant as Parcel is a bundler aiming for the web, and 3rd-party packages has no use for Parcel what-so-ever as they will likely use Rollup/webpack. 

Also `@parcel/babel-preset-env` is a `dev-dependency` and will not be installed if specified in a 3rd-party module, since all modules ship already-bundled and ready-to-go, and do not require any "building".

Lastly - there are zero instruction regarding this packing in the [Parcel installing page](https://v2.parceljs.org/getting-started/webapp/), which means it must ship with parcel itself, which also makes a lot of sense, because why would it not be baked-in.
