### ISSUE TITLE
Building with parcel build gives confusing error

### ISSUE THREAD

**Issue by derekyle** [parcel-bundler/parcel#7011]
# 🐛 bug report

When I build, I am getting the error: 
```
@parcel/optimizer-terser: Unexpected token punc «.», expected punc «(»

It is likely that terser doesn't support this syntax yet.

```
![image](https://user-images.githubusercontent.com/2208099/135733328-300145d7-3c14-4563-a227-02b872dfedeb.png)

The confusing part is that I don't see a . anywhere there. I found other similar errors reported, but they are usually related to parcel's terser not yet supporting conditional ?.

What is the issue here? I had to upgrade from parcel v1 as it is starting to decay. Then I tried parcel v2rc0. I have now upgraded to nightly and am still getting this problem. The issue does not occur if I use the --no-scope-hoist flag.

Update: I ran parcel build with verbose logging turned on and got what might be a little more helpful output:

![image](https://user-images.githubusercontent.com/2208099/135734616-6b8e4afe-a8e4-45ce-af4c-968b88fb9371.png)

But I still am not sure what is causing this.

## 🎛 Configuration (.babelrc, package.json, cli command)

my package.json has:
```
    "parcel": "^2.0.0-nightly.850",
    "@parcel/transformer-sass": "^2.0.0-nightly.852",
    "@parcel/transformer-typescript-tsc": "^2.0.0-nightly.852",
```
and .parcelrc:
```
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"],
    "*.{jpg,png,svg,gif}": ["@parcel/transformer-raw"]
  }
}
```

## 🌍 Your Environment

yarn 1.22.15
node 14.17.6
parcel 2.0.0-nightly.850
Windows 10 WSL2 running Ubuntu 20

**Comment by devongovett** [comment]
Do you have a code sample that could help us reproduce the issue?

**Comment by derekyle** [comment]
Yes, here is a project that recreates the issue:

https://github.com/derekyle/parcel-test

Running "Yarn build" should give the error.
