### ISSUE TITLE
Not working with @mui/material

### ISSUE THREAD

**Issue by julianlionti** [parcel-bundler/parcel#7037]
# 🐛 bug report

I  have created a new project from sctach. Then i install @mui/material and configure parcel like says in the documentation and include any element from that library recieved this error

`
index.js:8 Uncaught TypeError: Cannot read properties of undefined (reading 'default')
    at Object.NoSsr (index.js:8)
    at esmodule-helpers.js:16
    at Array.forEach (<anonymous>)
    at Object.exports.exportAll (esmodule-helpers.js:10)
    at Object.fc6V0../colors (index.js:11)
    at newRequire (index.b4af9c3f.js:71)
    at localRequire (index.b4af9c3f.js:83)
    at Object.klsNh.react/jsx-runtime (App.tsx:1)
    at newRequire (index.b4af9c3f.js:71)
    at localRequire (index.b4af9c3f.js:83)
`

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "scripts": {
    "start": "parcel public/index.html",
    "build": "parcel build public/index.html",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "@emotion/react": "^11.4.1",
    "@emotion/styled": "^11.3.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@types/react": "^17.0.27",
    "@types/react-dom": "^17.0.9",
    "parcel": "^2.0.0-rc.0",
    "typescript": "^4.4.3"
  }
}

```

## 😯 Current Behavior

White screen and error in console

## 💻 Code Sample

```js
import { Typography } from "@mui/material";

export const App = () => {
  return <Typography>Example</Typography>;
};

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | 14.17.3
| npm/Yarn         | 7.22.0
| Operating System | Windows 10

**Comment by devongovett** [comment]
Did you try the nightly? I think this was recently fixed. #7016

**Comment by julianlionti** [comment]
Thanks for the answer! I just tried and same error.

**Comment by mischnic** [comment]
I just tested it with
```json
{
  "dependencies": {
    "@emotion/react": "^11.4.1",
    "@emotion/styled": "^11.3.0",
    "@mui/material": "^5.0.3",
    "parcel": "2.0.0-nightly.867",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  }
}
```
and it works correctly (both `start` and `build`)

**Comment by julianlionti** [comment]
Hi! Thanks for the answrs. In that version of parcel i get this error.

![image](https://user-images.githubusercontent.com/53407936/136658562-b4d195d1-3ca1-4a5c-974d-2f95056934fa.png)


Im also using typescript in my proyect and i hace .parcelrc in it.

```json
{
  "extends": [
    "@parcel/config-default"
  ],
  "transformers": {
    "*.{mp4,svg}": [
      "@parcel/transformer-raw"
    ]
  }
}

```

**Comment by julianlionti** [comment]
I Just tried to create a new proyect with those dependencis and now it works. It seems that i have a problem in other place.

Thanks for your answers
