### ISSUE TITLE
Auto-install downloads a 2+ year old version  

### ISSUE THREAD

**Issue by chasewalden** [parcel-bundler/parcel#7038]
package manager: pnpm (workspaces)
public-hoist-pattern[]=@parcel/*

When I added `@parcel/transformer-svg-react` to the .parcelrc file, the auto install step ended up installing `2.0.0-nightly.1739`, which is 2+ years old. 

Not necessarily a major issue, but one I have faced a few times. It seems like it’s due to the `latest` tag on npm pointing at this version. I’ve not seen other mentions of this, but it has happened to me several times. Maybe it is a pnpm quirk: when adding a dependency without a version, it resolves the `latest` tag where npm/yarn resolve the largest semver? Not sure, but thought to mention it

**Comment by devongovett** [comment]
Thanks. Should be fixed in a few days when we release the next version.

**Comment by chasewalden** [comment]
Issue fixed. Closing
