### ISSUE TITLE
🐛 Accessing an app with a non-loopback address when using --https prevents the JS code from running

### ISSUE THREAD

**Issue by jraoult** [parcel-bundler/parcel#704]
Following a discussion in https://github.com/parcel-bundler/parcel/pull/161#issuecomment-361304497. We found out that an error in JS makes it impossible to debug (or even run) an app using `--https` while accessing it with a non-loopback address (ie. not `localhost` and `127.0.0.1`).

**Choose one:** is this a 🐛 bug report or 🙋 feature request?

### 🎛 Configuration

`parcel --https index.html`

### 🤔 Expected Behavior

The JS should run and we should be able to use HMR whatever address we use. It is necessary especially when debugging from a mobile browser.

### 😯 Current Behavior

Nothing shows up and there is an error in the console:

In Chrome:
> Mixed Content: The page at 'https://192.168.1.13:1234/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://192.168.1.13:57476/'. This request has been blocked; this endpoint must be available over WSS.

In FF:
> SecurityError: The operation is insecure.

### 💁 Possible Solution

As I described in the comment, I think we would need to pass the https server instance as a parameter (cf.https://github.com/websockets/ws/blob/master/examples/ssl.js) when instantiating the [ws server](https://github.com/parcel-bundler/parcel/blob/v1.5.1/src/HMRServer.js#L7) to make it secure and switch the protocol in the URL when `--https` option is on.

EDIT:
~~It might be good also to make sure that even if the HMR snippet fails in the browser it does not prevent the rest of the code from running~~ Will be fixed by #684 

I'm happy to try to submit a fix for that if we think it is a good idea.

**Comment by niicojs** [comment]
For the second part (prevent crash), #684 should fix it.

**Comment by niicojs** [comment]
I gave it a shot at #708 if you want to test.

**Comment by jraoult** [comment]
@niicojs I just tested and it is indeed working. Thx for looking at that.
