### ISSUE TITLE
get an error when using priave package.

### ISSUE THREAD

**Issue by crazyit** [parcel-bundler/parcel#7040]
get error An unexpected error occurred: "https://registry.yarnpkg.com/webcore: Not found" when using private packge.in yarn. in yarn.lock,config "webcore:@http://192.168.4.22:3000/ting/webcore.git":
  version "1.0.30"
  resolved "http://192.168.4.22:3000/ting/webcore:.git#f2d1300be7f1aff20d0d013148a4a28f36422c2e"
  dependencies:
    "@types/lodash" "^4.14.166"
    lodash "^4.17.20"

packge.json config    
 "dependencies": {
        "@types/lodash": "^4.14.166",
        "h5core": "http://192.168.4.22:3000/ting/webcore.git",
        "lodash": "^4.17.21",
        "src": "^1.1.2"
    }

**Comment by devongovett** [comment]
what does this have to do with Parcel?

**Comment by crazyit** [comment]
My project is written in typescript and is a web game. I want to compile the typescript to JavaScript. i use this command "parcel . /src/* --no-hmr --out-dir bin/dist", it is possible to compile it without the company's private library. After using the private library, the compilation always fails

**Comment by crazyit** [comment]
Or could you please tell me how to configure the project to pass the compilation of parcel when using private libraries? Thanks!

**Comment by mischnic** [comment]
> the compilation always fails

The error you posted comes from Yarn, not Parcel
