### ISSUE TITLE
Relative URL bug "./" or "/" or ""

### ISSUE THREAD

**Issue by hasnath1** [parcel-bundler/parcel#7047]
I want to output my "index.html" with urls that start with "./" not "/" or "". ONLY "./" . Do you have a way to do this ?
I am working on my project . I don't have time . I wasted my time searching the web almost 1 hour but no answer . 
here is my output/build/production file : 
`<!DOCTYPE html><html lang="en"><head><script type="module" src="forms/form_1/login.b1fd498c.js"></script><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="index.6da98e01.css"><title>Multiple Forms</title></head><body>    <div class="container intro-ctn"> <div class="align-items-center logo-ctn row"> <img src="logo.d2099498.jpg" alt="Logo" class="logo"> </div> <div class="header-ctn row"> <div class="col intro-txt text-center"> Have a look into these 25 different forms <br> These looks awesome 😎😎😎 ! </div> </div> </div> <div class="container"> <div class="row"> <div class="col"><a href="forms/form_1/index.html">Form-1</a></div> <div class="col"><a href="forms/form_1/index.html"></a></div> <div class="col"><a href="forms/form_1/index.html"></a></div> </div> <div class="row"> <div class="col"><a href="forms/form_1/index.html"></a></div> <div class="col"><a href="forms/form_1/index.html"></a></div> <div class="col"><a href="forms/form_1/index.html"></a></div> </div> <div class="row"> <div class="col"><a href="forms/form_1/index.html"></a></div> <div class="col"><a href="forms/form_1/index.html"></a></div> <div class="col"><a href="forms/form_1/index.html"></a></div> </div> </div> <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script> <script type="module" src="index.29afb049.js"></script> </body></html>`

In the urls , you can see the urls don't start with "./" . But I want the urls to start with "./" .  

There is a option to use relative url `--public-url` . I used command, with following options :

`--public-url ./`  
`--public-url .` 
`--public-url "."`
`--public-url "./"`
 
but Both of the commands gives the same result . I want all of my urls to start with "./" . Nothing more .

**Comment by devongovett** [comment]
The ./ is unnecessary since URLs without it are also treated as relative. Why do you need it?

**Comment by hasnath1** [comment]
Just give me a way to do that . "webpack" has support for it . But I found parcel easy , so I used it . But Now I need this feature . I am going the upload this file in a sub-directory . As a result the requests from "index.html" goes to the root url "/" . But I want the requests to go to "/sub-directory/sub/" not at "/" . if the url is "./" it goes to "/sub-directory/sub/" , but if it is "/" it requests it's assets at the root directory . So , I specifically need "./" . 

**Sorry , There is no bug in "Parcel JS" . I just found that it was because of extension "live server" in vscode . That extension was serving the files from wrong directory so I was having this problem . I was serving the production build with this extension to see if everything works fine **

**Comment by hasnath1** [comment]
**Sorry , There is no bug in "Parcel JS" . I just found that it was because of extension "live server" in vscode . That extension was serving the files from wrong directory so I was having this problem . I was serving the production build with this extension to see if everything works fine **
