### ISSUE TITLE
Proxy doesn't work

### ISSUE THREAD

**Issue by olegKusov** [parcel-bundler/parcel#7051]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

http proxy middleware installed. I tried first with .proxyrc file without middleware but it wasn't working

.proxyrc.js
```
const { createProxyMiddleware } = require("http-proxy-middleware");

module.exports = function (app) {
  app.use(
      createProxyMiddleware("/api", {
        target: "https://myprod/",
        pathRewrite: {
          "^/api": "",
        },
      })
  );
};
```

## 🤔 Expected Behavior

want to have working proxy

## 😯 Current Behavior

it doesn't proxy requests. sends localhost:1234/api/* requests with 404 result in console.

## 💻 Code Sample

fetch('/api/sign-up', ...

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel          | 1.12.5 |
| Node           | 14.17.6 |
| npm/Yarn      |   yarn 1.22.11|
| Operating System  | windows 11 with wsl 2|

**Comment by mischnic** [comment]
Only Parcel 2 has this feature.
