### ISSUE TITLE
 🐛 Cannot assign to window object using `watch` or `build`

### ISSUE THREAD

**Issue by lrn2prgrm** [parcel-bundler/parcel#706]
When i work with `parcel index.html` the resulting files and served page can assign to window object.
However if I use watch or build window object doesn't have any of the assigned properties.

## Reproducing the error:

https://github.com/lrn2prgrm/parcel-bug/tree/master

### 🎛 Configuration (.babelrc, package.json, cli command)
{
  "name": "cli",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "dev-serve": "parcel src/index.html -d build --no-cache", 
    "watch": "parcel watch src/index.html -d build --no-cache", 
    "build": "parcel build src/index.html -d build --no-minify --no-cache",
    "start": "yarn build"
  },
  "devDependencies": {
    "parcel-bundler": "^1.5.1",
    "typescript": "^2.6.2"
  }
}

### 🤔 Expected Behavior

watch and build should allow assigning to window object as `parcel index.html``

either with
* "prestart": "yarn build",
* "prestart": "yarn watch",

0. yarn start
1. in my browser console: `foo` should not be undefined
2. in my browser console: `help` should not be undefined
3. in my browser console: `helpts` should not be undefined

### 😯 Current Behavior
window object doesn't get any of the assigned props.

either with
* "prestart": "yarn build",
* "prestart": "yarn watch",

0.  yarn start
1. in my browser console: `foo` is undefined
2. in my browser console: `help` is undefined
3. in my browser console: `helpts` is undefined

*dev-serve behaves correctly*

### 💁 Possible Solution
I don't know about the implementation, but I just recommend they all behave as the dev-serve. ~~If unwanted  then dev serve should behave like watch and build and at least we could provide a flag (although that would be a feature request instead)~~

### 🔦 Context
I have a reproduction of the bug repo where this context is not relevant at all.

~~I am building a browser CLI tool. it's on the browser because I am testing pieces of code that interact with browser APIs as websockets. I am trying to replicate the env of the code I am using in the CLI for what I need to serve with browser-sync the static files and proxy some other stuff.~~

~~Using the dev serve doesn't work with browser sync and I don't get the proxies I want (I tried to run both on parallel with parallelshell).  Using watch or build hide the object i want to expose in the browser console.~~

~~I guess the workaround would be a multistep process. yarn dev-serve, wait..., ctrl + c, yarn bsync. But that's what I want to avoid, it should simply be `yarn start` to get it up and running.~~

### 🌎 Environment
| Software   | Version(s) 
| Parcel        | 1.5.1
| Node         | 8.9.2
| Yarn           | 1.2.1
| OS             | Windows 10 Pro

**Comment by niicojs** [comment]
This has nothing to do about ``window`.  
If you look t it, the js was not found.  

Use this to generate files: `parcel watch src/index.html -d build --public-url=./`

**Comment by lrn2prgrm** [comment]
Okay, why isn't public-url just always defaults to ./ ???

**Comment by lrn2prgrm** [comment]
Thanks for the workaround niicojs, however I am filing a new bug because I don't think this is desired. https://github.com/parcel-bundler/parcel/issues/714
