### ISSUE TITLE
@parcel/resolver-default: External dependency "process" is not declared in package.json

### ISSUE THREAD

**Issue by zababurinsv** [parcel-bundler/parcel#7060]
# 🐛 bug report

I don't create bundle with emscripten module

## 🎛 Configuration (.babelrc, package.json, cli command)
.babelrc
```js
not this file
```
package.json  
```js
 {
  "name": "@zb/fs",
  "version": "1.0.0",
  "description": "peer to peer connect",
  "source": "./src/index.mjs",
  "author": "Zababurin Sergey",
  "module": "./dist/index.mjs",
  "license": "GPL-3.0-only",
  "private": true,
  "config": {
    "path": "./frontend/src/index.initiator.html",
    "port": 6899
  },
  "scripts": {
    "dev": "parcel $npm_package_config_path --port $npm_package_config_port --dist-dir ./docs",
    "build:html": "parcel build $npm_package_config_path --dist-dir ./docs",
    "build": "parcel build",
    "kill": "kill $(lsof -t -i:$npm_package_config_initiator)",
    "clean:parcel": "find . -name \".parcel-cache\" -exec rm -rf '{}' +; "
  },
  "devDependencies": {
    "parcel": "2.0.0-rc.0"
  },
  "dependencies": {
    "buffer": "^6.0.3"
  }
}

```
cli command
```js
 parcel build
```

## 🤔 Expected Behavior

How can i create bundle ?

## 😯 Current Behavior

I get error
```js
@parcel/core: Failed to resolve 'buffer' from './src/main.mjs'

  /home/zb/Desktop/fs/src/main.mjs:2463:16
    2462 |      var BUFSIZE = 256;
  > 2463 |      var buf = Buffer.alloc(BUFSIZE);
  >      |                ^^^^^^
    2464 |      var bytesRead = 0;
    2465 |      try {

@parcel/resolver-default: External dependency "buffer" is not declared in package.json.

  /home/zb/Desktop/fs/package.json:1:1
  > 1 | {
  >   | ^
    2 |   "name": "@zb/fs",
    3 |   "version": "1.0.0",

  💡 Add "buffer" as a dependency.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
zb@Node:~/Desktop/fs$ yarn add  buffer
yarn add v1.22.11
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ buffer@6.0.3
info All dependencies
└─ buffer@6.0.3
Done in 2.48s.
zb@Node:~/Desktop/fs$ yarn build
yarn run v1.22.11
$ parcel build
🚨 Build failed.

@parcel/core: Failed to resolve 'process' from './src/main.mjs'

  /home/zb/Desktop/fs/src/main.mjs:294:34
    293 | 
  > 294 | peof process === "object" && typeof process.versions === "object" && typeof process.versions.node === "string";
  >     |      ^^^^^^^
    295 | 
    296 | var ENVIRONMENT_IS_SHELL = !ENVIRONMENT_IS_WEB && !ENVIRONMENT_IS_NODE && !ENVIRONMENT_IS_WORKER;

@parcel/resolver-default: External dependency "process" is not declared in package.json.

  /home/zb/Desktop/fs/package.json:24:3
    23 |   },
  > 24 |   "dependencies": {
  >    |   ^^^^^^^^^^^^^^
    25 |     "buffer": "^6.0.3"
    26 |   }

  💡 Add "process" as a dependency.

```

## 💁 Possible Solution

I use import without bundle

## 💻 Code Sample

https://github.com/zababurinsv/zb-fs/tree/master/src

## 🌍 Your Environment

    "parcel": "2.0.0-rc.0"

**Comment by avalanche1** [comment]
What was the problem, how did you fix?

**Comment by zababurinsv** [comment]
I didn't fix it.
I was trying to run a project on a mobile device.
But apparently parcel cannot be run in termux.

**Comment by zababurinsv** [comment]
> What was the problem, how did you fix?

I didn't fix it.
I was trying to run a project on a mobile device.
But apparently parcel cannot be run in termux.

**Comment by Tails** [comment]
Same problem when depending on a library that used 'process' to determine its runtime environment. Had to adjust package.json to this:

```json
{
...
"alias": {
    "process": {
      "global": "process"
    }
  },
...
}
```

**Comment by dovydasvenckus** [comment]
I don't think this issue should be resolved. I'm still facing this issue. 

@Tails I have tried your fix. It solves when running `parcel index.html`. But when I build site and serve with HTTP server, site fails to load and I get errors in console.

It's hard to believe that only 3 people are interested in this issue. I would think more people are using `axios` :smile:

**Comment by mattlockyer** [comment]
UPDATE: https://github.com/parcel-bundler/parcel/issues/7697#issuecomment-1036296859

> Same problem when depending on a library that used 'process' to determine its runtime environment. Had to adjust package.json to this:
> 
> ```json
> {
> ...
> "alias": {
>     "process": {
>       "global": "process"
>     }
>   },
> ...
> }
> ```

Helped me thanks! In my case it was a sha256 package that was trying to determine if it was running in node vs. browser and process was not defined for parcel core:

```
@parcel/core: Failed to resolve 'process' from './node_modules/js-sha256/src/sha256.js'
```

**Comment by chang-ryan** [comment]
i'm getting this on ```'./node_modules/js-sha256/src/sha256.js'``` as well

**Comment by chang-ryan** [comment]
this issue shouldn't be closed

i was able at some point see:
```
@parcel/resolver-default: Auto installing polyfill for Node builtin module "process"...
```
but that behavior is **not** occurring by default

package.json
```json
{
  "name": "app",
  "version": "1.0.0",
  "license": "MIT",
  "source": "src/index.html",
  "scripts": {
    "serve": "parcel src/index.html",
    "build": "parcel build"
  },
  "dependencies": {
    "ethers": "^5.5.4",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "parcel": "^2.3.1"
  }
}
```

```js
// App.js
import { ethers } from "ethers";

export function App() {
  return <h1>Hello world!</h1>;
}
```

```sh

🚨 Build failed.

@parcel/core: Failed to resolve 'process' from './node_modules/js-sha3/src/sha3.js'

  ./node_modules/js-sha3/src/sha3.js:21:52
    20 |   var WEB_WORKER = !WINDOW && typeof self === 'object';
  > 21 |   var NODE_JS = !root.JS_SHA3_NO_NODE_JS && typeof process === 'object' && process.versions && process.versions.node;
  >    |                                                    ^^^^^^^
    22 |   if (NODE_JS) {
    23 |     root = global;

✨  Done in 3.77s.

```

the `package.json` `alias` fix is working for me for `parcel` but not `parcel build`

**Comment by dovydasvenckus** [comment]
Probably we could ask @zababurinsv to reopen issue. If he doesn't want to reopen it, we could create new issue.

**Comment by mischnic** [comment]
-> https://github.com/parcel-bundler/parcel/issues/7697

**Comment by chang-ryan** [comment]
thanks @mischnic

**Comment by Tails** [comment]
@[dovydasvenckus](https://github.com/dovydasvenckus) I jumped the gun unfortunately. Indeed did I find out later Parcel generated some module code (breaking my code) for the 'process' dependency even though it fixed the compile time issue. 

I removed the alias again, updated parcel and made sure to only invoke Parcel using ```npm run```to prevent version mismatch with a globalized parcel binary. 

I'm now left with this:

```
@parcel/transformer-js: Non-static access of an `import` or `require`. This
causes tree shaking to be disabled for the resolved module.
  /main.js:40030:59
    40029 |                 // tslint:disable-next-line: strict-type-predicates
  > 40030 | peof process !== 'undefined' ? process : 0) === '[object process]') 
  >       |      ^^^^^^^
    40032 |                 }
  📝 Learn more:
     https://parceljs.org/features/scope-hoisting/#dynamic-member-accesses
```

But it compiles and works. Would still like to know how to fix that though.
