### ISSUE TITLE
Can not resolve absolute path /js/index.js

### ISSUE THREAD

**Issue by skandasoft** [parcel-bundler/parcel#7062]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0.
| Node             |
| npm/Yarn         |
| Operating System |

I have the index.html in src directory of the root folder 
when I tried `parcel build src/index.html` it failed because the index.html has 
`<script src="/js/index.js" type="module"></script>` with the message
`@parcel/core: Failed to resolve '/js/index.js in  './src/index.html'.`

My src has js,css,img folders and all of them fail...and the package.json,node_module,src are in root folder

**Comment by devongovett** [comment]
/ resolves from the project root, so it should probably be /src/js/index.js instead.

**Comment by skandasoft** [comment]
is there a work around this..since / is  the root in the src directory

**Comment by devongovett** [comment]
You could possibly use a glob alias like "./(.*)": "./src/$1" (untested, on mobile) https://parceljs.org/features/dependency-resolution/#glob-aliases

**Comment by skandasoft** [comment]
I added to the package.json

```
  "source": {
   "./(.*)":  "./src/$1"
  },
```
also tried ` "./dist/*": "./src/$1"`

and ran parcel build src/index.html and still got the same error 

`@parcel/core: Failed to resolve '/css/index.css' from './src/index.html'`
`@parcel/resolver-default: Cannot load file '../css/index.css' in './src'.`

I also added the .parcelrc file. to the root folder

```
{
  "extends": "@parcel/config-default",
  "resolvers": ["@parcel/resolver-glob", "..."]
}
```

**Comment by devongovett** [comment]
Ok sorry, my mobile typing was bad. I think you need this:

```json
{
  "alias": {
    "./**": "./src/$1"
  }
}
```

The double `**` is necessary to match more than one directory deep.

**Comment by skandasoft** [comment]
still no luck ...`Cannot load file '../css/index.css' in './src' ` it is trying to go up to the root rather than look at the src folder for /css/index.css
