### ISSUE TITLE
dynamically Importing an external javascript file fails with "unknown pipeline https"

### ISSUE THREAD

**Issue by stevejhiggs** [parcel-bundler/parcel#7064]
# 🐛 bug report

I am attempting to dynamically import an external javascript file. According to https://parceljs.org/features/dependency-resolution/#url-schemes an import starting with http/https should be left alone by parcel but instead I get an error.

## 🎛 Configuration (.babelrc, package.json, cli command)

* No custom parcel config
* Building a frontend app

## 🤔 Expected Behavior

The import should be left alone by parcel to be then resolved in the browser

## 😯 Current Behavior

On build I get the following error:

```
🚨 Build failed.

@parcel/core: Unknown pipeline: https.

  /Users/steve/code/personal/parcel-wasm/src/App.tsx:2:10
    1 | export function App() {
  > 2 | import("https://unpkg.com/canvaskit-wasm@0.18.1/bin/canvaskit.js").then(
  >   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    3 |     (canvas) => console.log(canvas)
    4 |   );
```

## 🔦 Context

I have a system that builds js that is then consumed by another system. Although a library would be the traditional way to do this some annoying vagaries make it harder than I would like. As such we build a hosted js file that can then be pulled in elsewhere. Using a dynamic import to do this works fine in the browser but fails here.

## 💻 Code Sample

```
export function App() {
  import("https://unpkg.com/canvaskit-wasm@0.18.1/bin/canvaskit.js").then(
    (canvas) => console.log(canvas)
  );

  return "Hello world!";
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.882
| Node             | 14
| npm/Yarn         | yarn
| Operating System | osx

**Comment by devongovett** [comment]
Ah, we should clarify that. It's currently left untouched for URL dependencies in HTML, CSS, etc. but not in JavaScript. #4148

**Comment by stevejhiggs** [comment]
ah, sorry for the dupe. I didn't find that one in my search

**Comment by stevejhiggs** [comment]
Is there any way to effectively tell parcel2 to leave an import alone though? This would work fine if parcel would just skip it

**Comment by mischnic** [comment]
You need to outsmart the detection of `import("some string literal")`:
```js
export function App() {
  let src = "https://unpkg.com/canvaskit-wasm@0.18.1/bin/canvaskit.js";
  import(src).then(
    (canvas) => console.log(canvas)
  );

  return "Hello world!";
}
```

**Comment by grimmerk** [comment]
> You need to outsmart the detection of import("some string literal"):

@mischnic 
I have the same issue and don't understand what you mean. Could you elaborate more? Is it resolved (so closing this issue) or closing it is due to duplicated issue?

**Comment by mischnic** [comment]
It's a duplicate as https://github.com/parcel-bundler/parcel/issues/7064#issuecomment-942348392 said

**Comment by fregante** [comment]
@mischnic can this issue be reopened? That no longer works:

```js
	const url = 'https://cdn.skypack.dev/jszip@^3.10.0';
	const {default: JSZip} = await import(url);
```

because `import` is turned into a `require`

<img width="424" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/1402241/179344926-a5cce2d6-76d8-46db-8b9a-bf5ae184f218.png">


I just found out that this is even documented: https://en.parceljs.org/javascript.html

<img width="501" alt="Screen Shot 8" src="https://user-images.githubusercontent.com/1402241/179345372-af397281-9d6b-4514-acdf-62f5b1adff04.png">


but it fails as is:

<img width="378" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/1402241/179345377-c9676d02-03d8-45de-ac73-35cc368c3bd6.png">


Generated code:

<img width="322" alt="Screen Shot 6" src="https://user-images.githubusercontent.com/1402241/179345379-9bafad1c-5b17-4e5e-b00f-941faf6b571b.png">

**Comment by webdev23** [comment]
Are you serious with this bug. What a joke, the all terrain package manager of your dream has no clue of what is a CDN or https..., and that's a no fix after 3 years...

For the meme

`@parcel/resolver-default: Unknown url scheme or pipeline 'https:'`

Uninstalling

**Comment by noelrocha** [comment]
what a shame!

**Comment by sulume** [comment]
I used [parcel-resolver-ignore](https://www.npmjs.com/package/parcel-resolver-ignore) to make it pass. Maybe a bit cleaner workaround than eval suggested at https://github.com/parcel-bundler/parcel/issues/8316#issuecomment-1545787533.

`package.json`
```json
  "parcelIgnore": ["https://.+"]
```

Although it's disappointing to have to write this tweak irrelevant to my code for the "zero config" tool.
