### ISSUE TITLE
Parcel auto inserts "defer" attribute to script tags

### ISSUE THREAD

**Issue by kirillunlimited** [parcel-bundler/parcel#7065]
# 🐛 bug report
Today I migrated my project to Parcel v2. Everything works great but I noticed that every script tag has an additional "defer" attribute which I don't have in my source layout. I would like to get rid of it but I couldn't find any mentions in the documentation.

## 🤔 Expected Behavior
```
<script src="/index.js"></script>
```

## 😯 Current Behavior
```
<script src="/index.js" defer=""></script>
```

## 💁 Possible Solution
I would like to be able to control the behaviour of scripts by myself. For example, I need to process some script in `<head>` before actual rendering. So I think there should be an option to disable this behaviour.

## 🌍 Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | 14.17.6
|Yarn         | 1.22.11
| Operating System | MacOS Big Sur 11.6

**Comment by devongovett** [comment]
It should only add defer for `<script type="module">` when compiling for older browsers and in development, which matches the ES module spec. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#other_differences_between_modules_and_standard_scripts

**Comment by kirillunlimited** [comment]
@devongovett
Oh, thank you, I didn't know that.
Also I did find this info in [docs](https://parceljs.org/getting-started/migration/#code-changes).
