### ISSUE TITLE
after build with typeorm, run error: ColumnTypeUndefinedError

### ISSUE THREAD

**Issue by suhaotian** [parcel-bundler/parcel#7073]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)
tsconfig.json
```json
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "~/*": ["./*"]
    },
    "jsx": "react",
    "skipLibCheck": true,
    "target": "es2017",
    "useUnknownInCatchVariables": false,
    "module": "esnext",
    "lib": ["dom", "esnext"],
    "moduleResolution": "node",
    "importHelpers": true,
    "resolveJsonModule": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "strict": true,
    "strictPropertyInitialization": false,
    "esModuleInterop": true,
    "declaration": false,
    "allowSyntheticDefaultImports": true,
    "noImplicitReturns": false,
    "noImplicitAny": true,
    "noFallthroughCasesInSwitch": true
  },
  "exclude": ["node_modules"]
}

```

## 🤔 Expected Behavior

should run success
## 😯 Current Behavior

my old webpack project run with typeorm well, but the new one with parcel error:
```
ColumnTypeUndefinedError: Column type for User#username is not defined and cannot be guessed. Make sure you have turned on an "emitDecoratorMetadata": true option in tsconfig.json. Also make sure you have imported "reflect-metadata" on top of the main entry file in your application (before any entity imported).If you are using JavaScript instead of TypeScript you must explicitly provide a column type.
[0]     at ColumnTypeUndefinedError.TypeORMError [as constructor] (/Users/apple/Projects/parcel-starter/node_modules/typeorm/error/TypeORMError.js:9:28)
```
![2021-10-14 at 6 08 PM](https://user-images.githubusercontent.com/6512574/137297626-29fb3a69-b6a6-4ad5-b7fe-aa766f6fe19f.png)

## 💻 Code Sample

```yarn start```

https://github.com/suhaotian/parcel-starter/tree/typeorm

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2.0.0
| Node             | v14.0.0
| npm/Yarn         | yarn
| Operating System | MacOS

**Comment by devongovett** [comment]
I don't think the default transpiler supports emitDecoratorMetadata yet. You may need to use TSC for that: https://parceljs.org/languages/typescript/#tsc

**Comment by suhaotian** [comment]
@devongovett ok, it work now after add .parcelrc. Great , thank you
