### ISSUE TITLE
path alias build error:  @parcel/core: Failed to resolve...

### ISSUE THREAD

**Issue by suhaotian** [parcel-bundler/parcel#7074]
# 🐛 bug report

if the alias like ```
"alias": {
    "~/": "./"
  },
```, build will work. but with ` "~/": "./src"` will build error:

![2021-10-14 at 6 27 PM](https://user-images.githubusercontent.com/6512574/137300245-30cbd644-f858-4bdb-9382-9906ba2ed7ce.png)

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`
```json
{
   "alias": {
      "~/": "./src/"
    },
}
```
`tsconfig.json`
```json
"compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "~/*": ["./src/*"]
    },
...
}
```

## 🤔 Expected Behavior

should build ok

## 😯 Current Behavior

```

@parcel/core: Failed to resolve '~/common/utils' from './src/server/index.ts'

  /Users/apple/Projects/parcel-starter/src/server/index.ts:2:23
    1 | import fastify from "fastify";
  > 2 | import { getId } from "~/common/utils";
  >   |                       ^^^^^^^^^^^^^^^^
    3 | const app = fastify();
    4 | 

@parcel/resolver-default: Cannot load file '../../common/utils' in './src/server'.
💡 Did you mean '../common/utils'?
```

## 💻 Code Sample

`yarn start`:
https://github.com/suhaotian/parcel-starter/tree/path-alias

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | 14.0.0
| npm/Yarn         | yarn
| Operating System | MacOS

**Comment by JaredSartin** [comment]
Change your alias in package json

```
{
   "alias": {
      "~": "./src"
    },
}
```

**Comment by suhaotian** [comment]
@JaredSartin still not work

**Comment by DeMoorJasper** [comment]
`~` is special cased as we internally map it to the project root. This is a known issue and therefore a duplicate.

The only way to work around this is to use `@` or something instead.

**Comment by suhaotian** [comment]
ok, `/` support

**Comment by motoitanigaki** [comment]
@DeMoorJasper Sorry if you are not right person to be mentioned.

Is sharp ( # ) also not be able to be used in alias? We were using sharp like below to distinguish from npm packages.
```
  "alias": {
    "#components": "./src/components"
  }
```
It was working correctly with `parcel@2.0.0-rc.0` but with `parcel@2.0.0`, build fails.

I made sample project to reproduce it. Hope it helps.
https://github.com/motoitanigaki/parcel-v2-alias-sample
