### ISSUE TITLE
Minification doesn't work

### ISSUE THREAD

**Issue by shoonia** [parcel-bundler/parcel#7077]
# 🐛 Minification doesn't work

The minify doesn't work with `npx purcel build` command

`package.json`
```js
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "dist/index.js",
  "source": "src/index.js",
  "browserslist": "> 0.5%, last 2 versions, not dead",
  "type": "module",
  "scripts": {
    "build": "parcel build"
  },
  "dependencies": {
    "parcel": "^2.0.0"
  }
}

```
`src/index.js`

```js
export const test = (one, two) => {
  return one + two;
}
```

run
```bash
npm run build
# or
npx parcel build
```

result `dist/index.js`

```js
const $c38b013c361dbfdf$export$e0969da9b8fb378d = (one, two)=>{
    return one + two;
};


export {$c38b013c361dbfdf$export$e0969da9b8fb378d as test};
//# sourceMappingURL=index.js.map

```

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | v16.8.0
| npm/Yarn         | npm 7.21.0
| Operating System | macOS 11.5.2

**Comment by mischnic** [comment]
Minification is disabled intentionally for library builds (because you named it "main"). 

You can reenable it by adding this to package.json:
```json
  "targets": {
    "main": {
		"optimize": true
	}
  }

**Comment by shoonia** [comment]
Thanks a lot! Works

**Comment by GRA0007** [comment]
@mischnic Is there a specific reason as to why? I can't find anything about this in the docs.

**Comment by KillDozerX2** [comment]
This should be a part of the documentation for library

**Comment by devongovett** [comment]
See https://parceljs.org/features/targets/#optimize

**Comment by KillDozerX2** [comment]
> See https://parceljs.org/features/targets/#optimize

I understand that, but as someone trying out parcel for the first time, I clicked on the docs for library, but this was nowhere to be found.
