### ISSUE TITLE
With Parcel 2, how to pass options to @babel/preset-react?

### ISSUE THREAD

**Issue by bhallstein** [parcel-bundler/parcel#7078]
# 💬 RFC

In our repo with preact, we have the following .babelrc:

```json
{
  "presets": [
    [
      "@babel/preset-react",
      {"pragma": "h", "pragmaFrag": "\"span\""}
    ]
  ]
}
```

Since upgrading to parcel 2.0.0, the following warning is emitted on compile:

![Screenshot 2021-10-14 at 15 13 58](https://user-images.githubusercontent.com/3428028/137335258-6f3dfc64-d82e-4d7a-8038-ee56037dc136.png)

I read the [documentation page](https://parceljs.org/languages/javascript/) on JS compilation & babel, but I couldn't work out the preferred way to configure this.

## 🔦 Context

Parcel v2 is working great and the option to preset-react is being respected! We just want to silence the warning, and to make sure we are configuring parcel/babel in the optimal way.

**Comment by bhallstein** [comment]
Re-reading the linked doc, it seems one intended way to work around this is you should be able to _"override the default Parcel config for JavaScript to exclude @parcel/transformer-babel"_ like so:

.parcelrc:
```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{js,mjs,jsx,cjs,ts,tsx}": [
      "@parcel/transformer-js",
      "@parcel/transformer-react-refresh-wrap"
    ]
  }
}
```

.babelrc:
```json
{
  "presets": [
    "@babel/preset-env",
    [
      "@babel/preset-react",
      { "pragma": "h", "pragmaFrag": "\"span\"" }
    ]
  ]
}
```

(And with `@babel/preset-env` + `@babel/preset-react` installed in `devDependencies`.)

However, this doesn't seem to work, as after compilation I get a "can't find variable 'React'" browser error, suggesting the pragma options are not taking effect, so the babel config isn't working/being used.

Either way, it would be optimal to have a way to pass the `pragma` opts to parcel's react transpilation pipeline, rather than having to work around it.

**Comment by mischnic** [comment]
Either:
- remove the babel config and use a `jsconfig.json` file as described here:
https://parceljs.org/recipes/react/#css-in-js
```
{
    "compilerOptions": {
        "jsx": "react",
        "jsxFactory": "h"
        "jsxFragmentFactory": "\"span\""
    }
}
```
- Remove `@babel/preset-env` (if you can) and only use the react preset
- Replace `@babel/preset-env` with `@parcel/babel-preset-env` (https://parceljs.org/languages/javascript/#custom-plugins)

**Comment by bhallstein** [comment]
```json
{
  "compilerOptions": {
    "jsx": "react",
    "jsxFactory": "h",
    "jsxFragmentFactory": "\"span\""
  }
}
```

Thank you so much, this was exactly what I was looking for — passing these options to the JS compiler. (And then removing .babelrc.) Is there full documentation for `compilerOptions` somewhere yet? Would be great if this was included on the JS compilation page.

Re your other suggestions:

- _Remove `@babel/preset-env` (if you can) and only use the react preset_: In this situation parcel 2.0.0 warns that `@babel/preset-react` should be deleted from the babelrc file as in the issue.

- _Replace `@babel/preset-env` with `@parcel/babel-preset-env`_: Not sure I understand how this factors into passing the params to react compilation?

I don't think I have understood your second & third bullet points, apologies.

**Comment by mischnic** [comment]
> In this situation parcel 2.0.0 warns that @babel/preset-react should be deleted as in the issue.

Sorry, I forgot that. Maybe Parcel should only warn if there are no options

> Not sure I understand how this factors into passing the params to react compilation?

(Same as my previous statement.) 

> Thank you so much, this was exactly what I was looking for — passing these options to the JS compiler. Is there full documentation for compilerOptions somewhere yet? Would be great if they were included on the JS compilation page.

I also always struggle to find them. We should list what we support.
In this case, I found it via the typescript docs: https://www.typescriptlang.org/tsconfig#jsxFragmentFactory

**Comment by bhallstein** [comment]
Ah, thanks for that link. I think listing what `jsconfig` opts parcel supports would be a super useful addition to the docs.

Thanks for your help.
