### ISSUE TITLE
The "global" output format is not supported in the "browser" target

### ISSUE THREAD

**Issue by lukejagodzinski** [parcel-bundler/parcel#7080]
# 🐛 bug report

I guess it's related to 2.0.0 release but I've just tried to deploy the same app without changing anything today and it stopped working with the error: `@parcel/core: The "global" output format is not supported in the "browser" target.`. This format was supported and should be supported for the browser target.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
  "browser": "./dist/bootstrap.js",
  "targets": {
    "browser": {
      "distDir": "dist",
      "engines": {
        "browsers": "> 0.2%, not dead"
      },
      "includeNodeModules": true,
      "isLibrary": false,
      "outputFormat": "global"
    }
  }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | 12.22.1
| npm/Yarn         | Yarn 1.22.10
| Operating System | MacOS 11.6

**Comment by mischnic** [comment]
Please choose a different name than "browser".  That one is meant for libraries: https://parceljs.org/features/targets/#library-targets

**Comment by lukejagodzinski** [comment]
I've done more tests and it looks like the solution could be changing config to something like this:
```json
{
  "targets": {
    "bootstrap": {
      "engines": {
        "browsers": "> 0.2%, not dead"
      },
      "includeNodeModules": true,
      "outputFormat": "global"
    }
  }
}
```

But then I can't control the name of the output file... It's always index.js file. Sometimes I love Parcel and sometimes I hate it. I didn't change anything and now our entire project doesn't build...

**Comment by mischnic** [comment]
Do this:
```js
{
  "bootstrap": "my-dist/output.js"
  "targets": {
    "bootstrap": {
      "engines": {
        "browsers": "> 0.2%, not dead"
      },
      "includeNodeModules": true,
      "outputFormat": "global"
    }
  }
}
```

**Comment by lukejagodzinski** [comment]
It looks like I can still control the name with this:

```json
{
  "bootstrap": "dist/bootstrap.js",
  "targets": {
    "bootstrap": {
      "engines": {
        "browsers": "> 0.2%, not dead"
      },
      "includeNodeModules": true,
      "outputFormat": "global"
    },
    "controller": {}
  }
}
```
Would be great if docs mention it at all
