### ISSUE TITLE
[Feature] Make cache directory path configurable

### ISSUE THREAD

**Issue by scriptPilot** [parcel-bundler/parcel#709]
Maybe I missed some information somewhere. It seems the `.cache` folder cannot be changed by configuration, that is something what should be possible.

**Comment by davidnagli** [comment]
In what situations would this be useful?

**Comment by ksashikumar** [comment]
Something like `--cache-dir` cli option makes sense?

**Comment by scriptPilot** [comment]
@davidnagli - for example to use the default cache folder I use for all other scripts - or - because .cache is already used for another script
@ksashikumar - yes, like that!

**Comment by ekoeryanto** [comment]
1 more reason, faster build on netlify

**Comment by yereby** [comment]
Hi,
I have the same need.
I use electron-forge that use the same name and it create a conflict with parcel `.cache`.

**Comment by ekoeryanto** [comment]
@yereby I think it's better creating another new issue

**Comment by davidnagli** [comment]
@ekoeryanto No I think @yereby's point supports the use case for this issue, it's not really a separate issue the we need to address.

**Comment by devongovett** [comment]
`--cache-dir` flag was exposed in v1.9.3.
