### ISSUE TITLE
Parcel 2 CLI with --target doesn't seem to work

### ISSUE THREAD

**Issue by caleb** [parcel-bundler/parcel#7091]
EDIT: I should mention that if I remove the `prod` target and run `npx parcel build` then everything works correctly.

# 🐛 bug report

When I run parcel with a `--target` option but no entry point on the command line (e.g. `npx parcel build --target dev`), I get an error that says that source files of other targets (in this case my `prod` target) doesn't exist (because I have not created that input file yet). My `package.json` has the source specified in my dev target.

```
🚨 Build failed.

@parcel/core: target/public/cljs-out/prod/main.js does not exist.

  /Users/caleb/Desktop/mojo/package.json:16:17
    15 |     "prod": {
  > 16 |       "source": "./target/public/cljs-out/prod/main.js",
  >    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    17 |       "engines": {
    18 |         "browsers": "last 2 versions, > 0.5%, not dead"
```

However, if I run the same command but add my entry point to the end of the command looks like it works, but doesn't create my dev output file:

```
$ npx parcel build --target dev ./target/public/cljs-out/dev/main.js
✨ Built in 165ms
```

## 🎛 Configuration (.babelrc, package.json, cli command)

This is my `package.json`

```json
{
  "name": "mojo",
  "version": "1.0.0",
  "main": "./index.js",
  "dev": "./target/public/cljs-out/dev/main_bundle.js",
  "prod": "./target/public/cljs-out/prod/main_bundle.js",
  "targets": {
    "dev": {
      "source": "./target/public/cljs-out/dev/main.js",
      "engines": {
        "browsers": "last 2 versions, > 0.5%, not dead"
      },
      "outputFormat": "global"
    },
    "prod": {
      "source": "./target/public/cljs-out/prod/main.js",
      "engines": {
        "browsers": "last 2 versions, > 0.5%, not dead"
      },
      "outputFormat": "global"
    }
  },
  "dependencies": {
    "ora": "^6.0.1",
    "react": "^17.0.2"
  },
  "devDependencies": {
    "@babel/cli": "^7.15.7",
    "@babel/core": "^7.15.8",
    "@babel/preset-env": "^7.15.8",
    "parcel": "^2.0.0"
  }
}
```

## 🤔 Expected Behavior

I would expect that running `npx parcel build --target dev` would use the `source` from the `dev` target in my `package.json` file and only build that target

## 🔦 Context

I am using parcel as a bundler after compiling my ClojureScript code.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | 14.15.1
| npm/Yarn         | 6.15.8/1.22.10
| Operating System |macOS 11.6

**Comment by faizilham** [comment]
Not sure if this is related, but I'm also having problem with `--target`. It seems like there's problem with reading the cache.

My package.json looks something like this:
```json
"scripts": {
    "build-cmd": "rimraf dist/cmd && parcel build --target cmd",
    "build-web": "rimraf dist/web && parcel build --target web",
  },
"targets": {
    "cmd": {
      "context": "node",
      "source": "src-cmd/index.ts"
    },
    "web": {
      "context": "browser",
      "source": "src-web/index.html"
    }
  }
```

When I ran `yarn build-cmd` and `yarn build-web` for the first time, it built both targets correctly. But if I run `yarn build-cmd` again after that, it will instead build the `web` target:

```sh
$ yarn build-cmd
yarn run v1.22.17
$ rimraf dist/cmd && parcel build --target cmd
✨ Built in 686ms

dist\web\index.html           141 B    1.24s
dist\web\index.89b80370.js     61 B    388ms
Done in 5.35s.
```

Currently my workaround is by using `--no-cache` when using `--target`. Deleting `.parcel-cache` folder before building also works.
