### ISSUE TITLE
API Proxy does not work

### ISSUE THREAD

**Issue by danieldebuhr** [parcel-bundler/parcel#7092]
# 🐛 bug report

The API Proxy does not work on my machine. `.proxyrc`, `.proxyrc.json` as well as `.proxyrc.js` are ignored by parcel 2.0.0.

## 🎛 Configuration (.babelrc, package.json, cli command)

`.proxyrc`
```js
{
  "/api": {
    "target": "http://localhost:3000/",
    "pathRewrite": {
      "^/api": ""
    }
  }
}
```

`package.json`
```js
{
  ...
  "devDependencies": {
    "parcel": "^2.0.0"
  },
  "source": "src/index.html",
  "scripts": {
    "start": "parcel",
  }
}
```
`index.js`
```js
fetch("/api/data").then(d => d.text().then(console.log))
```
`directory`
```
 - web
   - .proxyrc
   - package.json
   - src
     - index.html
     - index.js
   - dist
     - ...
```

Run with `yarn start` eg. `parcel`.

## 🤔 Expected Behavior

The fetch above should result in an request to `http://localhost:3000/data` and return some text.

## 😯 Current Behavior

The console.log statement returns the contents of `/`, which is the index-page served by parcel. Even if i malform the `.proxyrc`, the output from parcel is always the normal `Build in xx ms`. It seems the file is completely ignored by parcel.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0 |
| Node             | 12.22.7 |
| npm/Yarn         | 1.22.15 |
| Operating System | Ubuntu 20.04 |

**Comment by jamesmcallister** [comment]
Try adding `@parcel/config-default` to `.parcelrc`

`{
  "extends": "@parcel/config-default"
}
`

**Comment by mischnic** [comment]
Currently, the proxyrc file has to be in the project root (= where your npm/yarn lockfile or .git directory is): https://github.com/parcel-bundler/parcel/blob/6e3ff0c1671be43660fb23f748bd69cff67142f8/packages/reporters/dev-server/src/Server.js#L366-L373

That's probably not the case for you?

**Comment by danieldebuhr** [comment]
@jamesmcallister Adding `@parcel/config-default` to `.parcelrc` does not change anything.
@mischnic The file is in the project root

**Comment by DeMoorJasper** [comment]
Can you provide a repo where we can reproduce this?

**Comment by nitelite** [comment]
@danieldebuhr Do you happen to have a package-lock.json file in the parent folder of the project folder? This seems to mess with the resolution of the projectRootDir which is used to find the .proxyrc file.

**Comment by vrdhn** [comment]
> @danieldebuhr Do you happen to have a package-lock.json file in the parent folder of the project folder? This seems to mess with the resolution of the projectRootDir which is used to find the .proxyrc file.

For me, copying .proxyrc to the top level of  pnpm workspace solved the problem. 👍🏽

**Comment by scottcorgan** [comment]
> > @danieldebuhr Do you happen to have a package-lock.json file in the parent folder of the project folder? This seems to mess with the resolution of the projectRootDir which is used to find the .proxyrc file.
> 
> For me, copying .proxyrc to the top level of pnpm workspace solved the problem. 👍🏽

This worked for me as well. But, we use Yarn workspaces, so this would conflict with other apps we have inside of the repo. Is there any way to get this feature to look in the directory that parcel was run?

**Comment by mischnic** [comment]
See https://github.com/parcel-bundler/parcel/issues/7257#issuecomment-1120371084

**Comment by PredokMiF** [comment]
In my case I can place `.proxyrc.js` in project root and it helped me, but I worry about valid support of yarn workspaces ([I have already solved the problem with parcel cache folder](https://github.com/parcel-bundler/parcel/issues/5927#issuecomment-1250395079))

**Comment by muzichen** [comment]
> #7257 (comment)

I try to delete the package.lock.json file in the root of monarepo and it works, why?
