### ISSUE TITLE
Build fails during image optimization

### ISSUE THREAD

**Issue by surma** [parcel-bundler/parcel#7096]
# 🐛 bug report

My project fails to build with this error:

```
@parcel/optimizer-image: Sampling factors too large for interleaved scan

  Error: Sampling factors too large for interleaved scan
  at Object.optimize
  (/Users/surma/src/github.com/surma/surma.dev/.tmp/node_modules/@parcel/optimizer-image/lib/ImageOptimizer.js:42:42)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async PackagerRunner.optimize
  (/Users/surma/src/github.com/surma/surma.dev/.tmp/node_modules/@parcel/core/lib/PackagerRunner.js:364:20)
  at async PackagerRunner.getBundleResult
  (/Users/surma/src/github.com/surma/surma.dev/.tmp/node_modules/@parcel/core/lib/PackagerRunner.js:255:15)
  at async PackagerRunner.getBundleInfo
  (/Users/surma/src/github.com/surma/surma.dev/.tmp/node_modules/@parcel/core/lib/PackagerRunner.js:239:9)
  at async PackagerRunner.run
  (/Users/surma/src/github.com/surma/surma.dev/.tmp/node_modules/@parcel/core/lib/PackagerRunner.js:160:183)
  at async Child.handleRequest
  (/Users/surma/src/github.com/surma/surma.dev/.tmp/node_modules/@parcel/workers/lib/child.js:217:9)
```

This error message is very likely from libjpeg via sharp, so it’s likely trying to optimize one of my images. Sadly, the error message does not convey which image was being optimized.

For this particular project, I’d actually want to turn _off_ image optimization, but [the docs](https://parceljs.org/recipes/image/#configuration) don’t seem to tell me how to disable it (I tried adding an empty `sharp.config.js`, to no avail).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2.0.0
| Node             | 16.4
| Operating System | MacOS M1

**Comment by surma** [comment]
~~Update:~~ 

- ~~Empty `sharp.config.json` does *not* fix it~~
- ~~`sharp.config.json` containing `{}` does *not* fix it~~
- ~~`sharp.config.json` containing `{"jpeg": {}}` *does* fix it~~

See @devongovett’s replies below. This will reencode all images which fixes the optimizer by accident. To really disable optimizations, I set my `.parcelrc` to

```js
{
  "extends": "@parcel/config-default",
  "optimizers": {
    "*.jpeg": [],
  }
}
```

**Comment by devongovett** [comment]
Hmm interesting. This is coming from libjpeg, but not via sharp. This is our default lossless image optimizer. Anything you can share about this image? Wonder if we should ignore errors like this, or make them warnings instead...

You can disable it by setting the optimizers for jpegs to an empty array in a .parcelrc: https://parceljs.org/features/plugins/#optimizers

**Comment by surma** [comment]
> Anything you can share about this image?

I have _no_ idea which image it is currently processing. I have quite a lot of them. 

> Wonder if we should ignore errors like this, or make them warnings instead

I like this idea. Not optimizing an image is arguable not fatal (although the opposite could be argued when compression is _explicitly_ requested via query parameters).

> You can disable it by setting the optimizers for jpegs to an empty array in a .parcelrc:

Is it worth adding a note to [the image section in the docs](https://parceljs.org/recipes/image/#configuration)?

**Comment by surma** [comment]
> This is coming from libjpeg, but not via sharp. 

Interesting. Curious how a `sharp.config.json` with `{"jpeg": {}}` is preventing this error from happening.

**Comment by devongovett** [comment]
With that sharp config, all jpegs get re-encoded by sharp prior to reaching the optimizer.

This is interesting because it means somehow sharp is able to decode that image. Maybe we are calling libjpeg wrong somehow... 🤔

**Comment by surma** [comment]
If you tell me how to figure out which image is causing the error, I’m (most likely) happy to share it :D

**Comment by mischnic** [comment]
Looks like this is the image in question: https://github.com/surma/surma.dev/blob/master/static/things/when-workers/banana.jpg

Crashes in an project with just `<img src="banana.jpg" />` as the Parcel entry point

(I added a try-catch around https://github.com/parcel-bundler/parcel/blob/85b76e86ddc431b7140e114db5b16486962bf964/packages/optimizers/image/src/ImageOptimizer.js#L13
to also print out `bundle.name` upon an error)

**Comment by devongovett** [comment]
Thanks @mischnic! Then to do:

- [ ] Debug why this error occurs and hopefully fix it
- [x] Improve error message to include file name or maybe a code frame if possible
- [x] Possibly change image optimization errors to warnings?
- [ ] Add a note to the image docs about how to turn off optimizers, pointing to the section linked above.

**Comment by DeMoorJasper** [comment]
Tried to figure out why this is happening but couldn't really figure it out, originally tried to get some info from the metadata of the file and couldn't find much besides it using a very new sampling technique as the tools I used just said `unknown`

Also tried getting more information from the rust trace without any luck https://gist.github.com/DeMoorJasper/dd49e53a56e79de537e58e360b784c8e
