### ISSUE TITLE
CSS modules don't hot reload on a React app

### ISSUE THREAD

**Issue by dariocravero** [parcel-bundler/parcel#7098]
# 🐛 bug report

CSS changes made into a `.module.css` file aren't hot reloaded into the browser. CSS changes in a `.css` file are reloaded fine.

## 🎛 Configuration (.babelrc, package.json, cli command)

Nothing special. The code is in https://github.com/dariocravero/viewstestparcel.

## 🤔 Expected Behavior

When I change a CSS property's value in `src/App/view.module.css`, e.g., `.Text's` class `color` it should update in the browser.

## 😯 Current Behavior

It doesn't update. If I refresh the page it works.

No error.

## 🔦 Context

Get CSS changes to show in the app without having to reload.

## 💻 Code Sample

https://github.com/dariocravero/viewstestparcel
`yarn start` starts parcel. The entrypoint is `src/index.html` that loads `src/index.js`. The view loading the CSS is `src/App/view.js` and the CSS modules file is `src/App/view.module.css`.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | 14.17.1
| Yarn         | 1.22.4
| Operating System | Mac Big Sur 11.5.2

Thanks!

**Comment by mischnic** [comment]
Only the new JS asset generated by the CSS module is sent over to the browser, not the actual CSS change. (There should be an update message with both the JS and CSS asset)

Regression of https://github.com/parcel-bundler/parcel/pull/6986

**Comment by salatielsql** [comment]
I'm facing the same issue. Here is my repo: https://github.com/salatielq/reactts-starter

run `npm install` then `npm run dev` to start

**Comment by zouloux** [comment]
Hello, any news on this ? Can i help in some way ?

**Comment by couleurs** [comment]
Running into the same issue with a vanilla CSS file and a vanilla web app (not React or any other framework).

**Comment by diegoserranor** [comment]
Experiencing this issue for both CSS and SCSS modules. Also need to refresh the browser. Only styles are affected. Changes to the JSX are immediately visible as expected.

**Comment by isjackwild** [comment]
+1 still experiencing this issue unfortunately. Using Parcel 2.0.1

**Comment by diegoserranor** [comment]
@isjackwild Try `parcel@2.0.0-nightly.961`, it is working there

Parcel 2.0.1 was released 2 months ago

**Comment by isjackwild** [comment]
@esfxra thank you so much for your quick response, i will try this — I was just using the latest NPM release

**Comment by salatielsql** [comment]
For everyone waiting the [version 2.1.0](https://github.com/parcel-bundler/parcel/blob/v2/CHANGELOG.md#210---2021-01-05) was released yesterday with this fix. I've tested on my project and is working properly 🚀

**Comment by zouloux** [comment]
Thanks ! 👏
