### ISSUE TITLE
Parcel  Error -  module not found @parcel\fs-search\fs-search.win32-x64-msvc.node

### ISSUE THREAD

**Issue by AmmarSayed** [parcel-bundler/parcel#7104]
# 🐛 bug report

Parcel gives me an error when I run yarn start, or yarn build, or npm start or build

I recently upgraded to windows 11 

** Updates: **
I've rolled back to a fresh installation of windows 10, and I got the same error 😒, I'm not sure what's happening here but it seems like there's some mistake in parcel installation.

## 🎛 Configuration ( package.json)

```js
{
  "name": "testing",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "start": "parcel index.html",
    "build": "parcel build"
  },
  "devDependencies": {
    "parcel": "^2.0.0"
  }
}
```

## 🤔 Expected Behavior
It should run the build or the development server, but neither happened

## 😯 Current Behavior
An error in the terminal 

```
λ yarn start
yarn run v1.22.15
$ parcel index.html
Error: The specified module could not be found.
\\?\C:\Users\Ammar Home\Desktop\testing\node_modules\@parcel\fs-search\fs-search.win32-x64-msvc.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (C:\Users\Ammar Home\Desktop\testing\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\Ammar Home\Desktop\testing\node_modules\@parcel\fs-search\index.js:19:20)
    at Module._compile (C:\Users\Ammar Home\Desktop\testing\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## 💁 Possible Solution
I removed entire node module , reinstalled parcel several times, and still facing the same issue 

## 🔦 Context
Just runing a normal start script to see a console log in the browser, it was just a startup file

## 💻 Code Sample
I have nothing special in my code, it's just a startup file

index.html file
```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Document</title>
</head>

<body>

  <script src="./index.js" type="module"></script>
</body>

</html>
```

index.js file
```
console.log("Hello world");
```

## 🌍 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  "^2.0.0"
| Node             | v14.18.1
| npm         | 6.14.15
| Yarn | 1.22.15
| Operating System | Windows 11 Pro
| Version  | 21H2
| OS build | 22000.258
| Experience | Windows Feature Experience Pack 1000.22000.258.0

## My labtop specification
| | |
| ---------------- | ---------- |
| Processor	| Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
| Installed RAM |	8.00 GB (7.88 GB usable)
| System type	| 64-bit operating system, x64-based processor

The wierd thing is when I looked at the specified folder in the error, I found that module "fs-search.win32-x64-msvc.node" , It's already there under following directory

- node_moduels /
-- @parcel /
 ---fs-search /
 ---- fs-search.win32-x64-msvc.node

, which the error claiming it's not found! 😕

I'm not sure what could be causing this issue, 
any one can help?

## Debug log:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.18.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle testing@1.0.0~prestart: testing@1.0.0
6 info lifecycle testing@1.0.0~start: testing@1.0.0
7 verbose lifecycle testing@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle testing@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Ammar Home\Desktop\testing\node_modules\.bin;C:\Users\Ammar Home\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\Users\Ammar Home\cmder\vendor\conemu-maximus5;C:\Users\Ammar Home\cmder\vendor\conemu-maximus5\ConEmu;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Users\Ammar Home\AppData\Local\Microsoft\WindowsApps;C:\Users\Ammar Home\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Ammar Home\AppData\Roaming\npm;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Ammar Home\cmder\vendor\bin;C:\Users\Ammar Home\cmder
9 verbose lifecycle testing@1.0.0~start: CWD: C:\Users\Ammar Home\Desktop\testing
10 silly lifecycle testing@1.0.0~start: Args: [ '/d /s /c', 'parcel index.html' ]
11 silly lifecycle testing@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle testing@1.0.0~start: Failed to exec start script
13 verbose stack Error: testing@1.0.0 start: `parcel index.html`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid testing@1.0.0
15 verbose cwd C:\Users\Ammar Home\Desktop\testing
16 verbose Windows_NT 10.0.22000
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v14.18.1
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error testing@1.0.0 start: `parcel index.html`
22 error Exit status 1
23 error Failed at the testing@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by AmmarSayed** [comment]
** Updates: **
I've rolled back to a fresh installation of windows 10, and I got the same error 😒, I'm not sure what's happening here but it seems like there's some mistake in parcel installation.

**Comment by regin-thomsen** [comment]
+1

**Comment by giacomoF5** [comment]
Hi, some of my students have the same problem : Parcel Error - module not found @parcel\fs-search\fs-search.win32-x64-msvc.node.
I solved the problem using Parcel v1 : npm install -D parcel-bundler
In some computer for any reason Parcel v2 does not work when you use "npx parcel src/index.html" and return the error "Error - module not found @parcel\fs-search\fs-search.win32-x64-msvc.node". Sorry I didn't find the root cause.

**Comment by Shausti** [comment]
This worked for me for parcel 2.

The issue is because the package is failing due to a missing library on the computer.  fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).

You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by mischnic** [comment]
That does make sense because the error message is `ERR_DLOPEN_FAILED`, not something like `ENOENT` (for "file not found").

**Comment by AmmarSayed** [comment]
> This worked for me for parcel 2.
> 
> The issue is because the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> 
> You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe

You Are Ssuuupppper Awwwwsomeee 
it worked, and I'll upgrade to windows 11 again and re-check,

just wondering if theres some mistake I did that caused that error, or is it just missing from the windows installation media files.

Thank you anyway for your support, 

the issue is resolved on my side for windows 10

**Comment by AmmarSayed** [comment]
Updates:

Issue is resolved as well on windows 11

**Comment by ubeydeozdmr** [comment]
> This worked for me for parcel 2.
> 
> The issue is because the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> 
> You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe

You're real hero! Thank you so much 😊

**Comment by Afshin-YazdanMehr** [comment]
> This worked for me for parcel 2.
> 
> The issue is because the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> 
> You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe

Thank you, it solved the error indeed.

**Comment by Afshin-YazdanMehr** [comment]
> This worked for me for parcel 2.
> 
> The issue is because the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> 
> You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64
Thank you, it worked indeed.

**Comment by Tech-sensei** [comment]
> This worked for me for parcel 2.
> 
> The issue is because the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> 
> You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe

This really worked for me❤❤❤❤❤ At first I had some doubts, but now I would recommend this to anyone having the same issue. Thanks by the way👍🏿

**Comment by Imtiajul** [comment]
> 

Thanks a lot. You are awesome. It took a lot of time to fix this. I got this error after updating the Windows version. It worked for me for gatsby Js framework.

**Comment by Imtiajul** [comment]
> This worked for me for parcel 2.
> 
> The issue is because the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> 
> You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe

Thanks a lot. You are awesome. It took a lot of time to fix this. I got this error after updating the Windows version. It worked for me for gatsby Js framework.

**Comment by ghost** [comment]
> > This worked for me for parcel 2.
> > The issue is because the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> > You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe
> 
> You Are Ssuuupppper Awwwwsomeee it worked, and I'll upgrade to windows 11 again and re-check,
> 
> just wondering if theres some mistake I did that caused that error, or is it just missing from the windows installation media files.
> 
> Thank you anyway for your support,
> 
> the issue is resolved on my side for windows 10

hey ammar i am facing the same issue as yours...can u please guide me on the parcel 2 thing plzz??

**Comment by AmmarSayed** [comment]
> > > This worked for me for parcel 2.
> > > The issue is because the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> > > You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe
> > 
> > 
> > You Are Ssuuupppper Awwwwsomeee it worked, and I'll upgrade to windows 11 again and re-check,
> > just wondering if theres some mistake I did that caused that error, or is it just missing from the windows installation media files.
> > Thank you anyway for your support,
> > the issue is resolved on my side for windows 10
> 
> hey ammar i am facing the same issue as yours...can u please guide me on the parcel 2 thing plzz??


Hello dear, it's just a missing c++ package in the windows installation, once I downloaded it and restated my laptop, it just works.

You can download it from here

https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by ghost** [comment]
hey ammar thanks for replying me...actually my issue got resolved already
but thanks anyway☺☺

**Comment by sakthivelamt** [comment]
It's work's for me anyone please explain me how it is working

**Comment by UsamaMohamedKhalil** [comment]
> > This worked for me for parcel 2.
> > The issue is because the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> > You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe
> 
> You Are Ssuuupppper Awwwwsomeee it worked, and I'll upgrade to windows 11 again and re-check,
> 
> just wondering if theres some mistake I did that caused that error, or is it just missing from the windows installation media files.
> 
> Thank you anyway for your support,
> 
> the issue is resolved on my side for windows 10

I install the file and still the error show on my face.   
![Screenshot 2022-10-23 011629](https://user-images.githubusercontent.com/115358777/197365778-28c92a37-0b9c-4fee-b63e-c7e48fbf2ba2.png)

**Comment by pablojsx** [comment]
> > > This worked for me for parcel 2.
> > > The issue is because the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> > > You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe
> > 
> > 
> > You Are Ssuuupppper Awwwwsomeee it worked, and I'll upgrade to windows 11 again and re-check,
> > just wondering if theres some mistake I did that caused that error, or is it just missing from the windows installation media files.
> > Thank you anyway for your support,
> > the issue is resolved on my side for windows 10
> 
> I install the file and still the error show on my face. ![Screenshot 2022-10-23 011629](https://user-images.githubusercontent.com/115358777/197365778-28c92a37-0b9c-4fee-b63e-c7e48fbf2ba2.png)

Had the same erro and I managed to solve it:
-I Updated windows 10 and then downloaded some security updates. 
-Installed the software from the post above.
-Reinstalled node. 
-Added NODE_PATH manually thanks to a youtube video.
-delete the node_modules folder from the project and run npm install

Then got a different error:
Restarted the computer and it worked. Remember that the "main" key inside the package.json must have a js extension.

**Comment by yiyasha15** [comment]
> This worked for me for parcel 2.
> 
> The issue is because the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> 
> You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe

What about macOS?

**Comment by okwedavid** [comment]
> This worked for me for parcel 2.
> 
> The issue is because the package is failing due to a missing library on the computer.  fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> 
> You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe

What do I do when this doesn't work?

**Comment by chaitanyatekane** [comment]
> Hi, some of my students have the same problem : Parcel Error - module not found @parcel\fs-search\fs-search.win32-x64-msvc.node. I solved the problem using Parcel v1 : npm install -D parcel-bundler In some computer for any reason Parcel v2 does not work when you use "npx parcel src/index.html" and return the error "Error - module not found @parcel\fs-search\fs-search.win32-x64-msvc.node". Sorry I didn't find the root cause.

this worked for me as https://aka.ms/vs/17/release/vc_redist.x64.exe was not working

**Comment by chaitanyatekane** [comment]
> > This worked for me for parcel 2.
> > The issue is because the package is failing due to a missing library on the computer.  fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> > You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe
> 
> What do I do when this doesn't work?

try using parcel v1 : npm install -D parcel-bundler

**Comment by sanyuan0704** [comment]
> This worked for me for parcel 2.
> 
> The issue is because the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> 
> You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe

You are the hero, bro

**Comment by yuvraj9011** [comment]
> This worked for me for parcel 2.
> 
> The issue is because the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> 
> You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe

Thanks worked for me

**Comment by Oluwakunmi-Obaditan** [comment]
> This worked for me for parcel 2.
> 
> The issue is because the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> 
> You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe

This worked for me. PS: using a windows 11 PC

**Comment by govindpateriya** [comment]
> > This worked for me for parcel 2.
> > The issue is because the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> > You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe
> 
> You're real hero! Thank you so much 😊

thanks brother problem sloved!

**Comment by skimran-coder** [comment]
> This worked for me for parcel 2.
> 
> The issue is because the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> 
> You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe

You're such a lifesaver. I wasted 2 hours on this; I wish I had found your solution earlier. Thank you so much. ❤️

**Comment by naasirshine** [comment]
> This worked for me for parcel 2.
> 
> The issue is that the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> 
> You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe

Thank you so much. ❤️
 appreciate that 
<img width="528" alt="error" src="https://github.com/parcel-bundler/parcel/assets/54545396/f2e87dc3-eee0-480e-8b36-d86920036121">

**Comment by awalhossainofficial** [comment]
> This worked for me for parcel 2.
> 
> The issue is because the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> 
> You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe

![RdjReliefGIF](https://github.com/parcel-bundler/parcel/assets/80216813/b2115852-b2d6-47b0-b66c-8b1f60437bc8)
This is a life saver, man! I just spent more than 4 hours solving this issue. Just setup my new PC and tried to run it. Thank God, I found it.

Thanks man!

**Comment by GagandeepSidhu** [comment]
It's not because of the missing library, but rather the older version of Node.js. Try upgrading the Node version and then running the command again, it should work now.

**Comment by shrijandra** [comment]
> Hi, some of my students have the same problem : Parcel Error - module not found @parcel\fs-search\fs-search.win32-x64-msvc.node. I solved the problem using Parcel v1 : npm install -D parcel-bundler In some computer for any reason Parcel v2 does not work when you use "npx parcel src/index.html" and return the error "Error - module not found @parcel\fs-search\fs-search.win32-x64-msvc.node". Sorry I didn't find the root cause.

Thanks this work for me.

**Comment by vishal-gupta-252310** [comment]
Thanks for the help guys..

**Comment by shrex01** [comment]
> This worked for me for parcel 2.
> 
> The issue is because the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> 
> You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe



YOU ABSOLUTE LEGEND, THIS WORKED FOR ME .. THANKS!!!

**Comment by sanyorat** [comment]
> > This worked for me for parcel 2.
> > The issue is because the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> > You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe
> 
> You Are Ssuuupppper Awwwwsomeee it worked, and I'll upgrade to windows 11 again and re-check,
> 
> just wondering if theres some mistake I did that caused that error, or is it just missing from the windows installation media files.
> 
> Thank you anyway for your support,
> 
> the issue is resolved on my side for windows 10

# Actually to implement HMR(Hot Module Replacement) parcel uses a File Watching Algorithm which is written in C++ and for that this might be needed.

**Comment by ermiyasasrat** [comment]
this worked for me. thanks

**Comment by deity-actual414** [comment]
I met that issue head-on and discovered the answer +1

**Comment by Lereste** [comment]
> This worked for me for parcel 2.
> 
> The issue is because the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).
> 
> You can get the download here -> https://aka.ms/vs/17/release/vc_redist.x64.exe

Thank you so much bro, it still work in 2025 xD
