### ISSUE TITLE
@parcel/transformer-js: Non-static access of an `import` or `require`. This causes tree shaking to be disabled for the resolved module

### ISSUE THREAD

**Issue by antimatter96** [parcel-bundler/parcel#7109]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

.parcelrc
```js
{
  "extends": "@parcel/config-default"
}
```
package.json
```
{
  "name": "calc",
  "version": "0.0.1",
  "scripts": {
    "dev": "parcel",
    "build": "rm -rf ./../dist && parcel build --dist-dir ./../dist --log-level verbose"
  },
  "source": "src/index.html",
  "dependencies": {
    "parcel": "^2.0.0",
    "posthtml": "^0.16.5",
    "posthtml-include": "^1.7.2"
  },
  "license": "MIT"
}
```

## 🤔 Expected Behavior

No warnings

## 😯 Current Behavior

Warnings
```bash
parcel/transformer-js: Non-static access of an `import` or `require`. This causes tree shaking to be disabled for
the resolved module.
  ...../js/main.js:x:y
  > x |   let w = new Week();
  >   |                ^^^^
```

## 💻 Code Sample

directory
```bash
root
 ┣ src
 ┃ ┣ js
 ┃ ┃ ┣ main.js
 ┃ ┃ ┣ week.js
 ┃ ┣ index.html
 ┃ ┗ style.css
 ┣ .parcelrc
 ┣ package.json
 ┗ yarn.lock
```

index.html
```html
<!DOCTYPE html>
<html lang="en">

<head>
  <link rel="stylesheet" href="./style.css">
  <title>Progress</title>
</head>

<body>
  <script type="module" src="./js/main.js"></script>
</body>

</html>

```
js/main.js
```js
import { Week } from "./week";
let w = new Week();
```

js/week.js
```js
export class Week {
  constructor(input) {}
}

```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | v14.17.6
| npm/Yarn         | 1.22.10
| Operating System | macOS Big Sur 11.4

**Comment by DexterHaxxor** [comment]
Still not fixed, when will we get proper warnings?

**Comment by ebrensi** [comment]
Is there a way to disable that particular warning?  I find that lots of this warning are getting in the way of reading other information.  

EDIT: Setting `--log-level info` suppresses the warning.

**Comment by tcstory** [comment]
still meet the problem, the tree shaking is disabled , the version of parcel is 2.3.2,

**Comment by josheppinette** [comment]
Why does this disable tree shaking?
