### ISSUE TITLE
🙋CSS-only asset compilation

### ISSUE THREAD

**Issue by nicohvi** [parcel-bundler/parcel#711]
I'm using parcel as the bundler for my `scss` files, which works great! (Massive kudos to all contributors, I'm **very** impressed with the speed and ease of use)

However, I was wondering whether it would be possible to use parcel as a CSS-bundler without having it produce `js`-files as well? The website I'm creating is **not** a SPA, which means I'd like to use the generated CSS without having to include it through JavaScript or a generated HTML file.

### 🎛 Configuration
Parcel version: `1.5.1`
CLI command: `parcel watch assets/style.scss -d public`

### 🤔 Expected Behavior

Running `parcel watch assets/style.scss -d public` could produce the following files:
```
public/style.css
public/style.map (Scss sourcemaps)
```

### 😯 Current Behavior
Running `parcel watch assets/style.scss -d public`produces the following files:
```
public/style.css
public/style.js
public/style.map (JS sourcemaps)
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.5.1 |
| Node             | 8.1.3 |
| npm/Yarn         | 1.3.2 |
| Operating System | macOS High Sierra |

**Comment by devongovett** [comment]
The JS it produces is for hot module reloading. You can disable that with the `--no-hmr` flag, and only a CSS file will be produced.

Source maps for CSS is a separate feature request.

**Comment by nicohvi** [comment]
Thank you very much for the clarification, @devongovett :+1:

**Comment by sheeldotme** [comment]
@davidnagli I think this one is safe to close!
