### ISSUE TITLE
(0, eval)('this') transformed into eval('this') which doesn't work

### ISSUE THREAD

**Issue by ondrejmirtes** [parcel-bundler/parcel#7116]
# 🐛 bug report

I'm using Knockout.js library. A few of the first lines of the library look like this:

```
(function(){
var DEBUG=true;
(function(undefined){
    // (0, eval)('this') is a robust way of getting a reference to the global object
    // For details, see http://stackoverflow.com/questions/14119988/return-this-0-evalthis/14120023#14120023
    var window = this || (0, eval)('this'),
        document = window['document'],
        navigator = window['navigator'],
        jQueryInstance = window["jQuery"],
        JSON = window["JSON"];

    if (!jQueryInstance && typeof jQuery !== "undefined") {
        jQueryInstance = jQuery;
    }
```

The problem is that Parcel transpiles that to:

```
(function() {
    var DEBUG = true;
    (function(undefined) {
        // (0, eval)('this') is a robust way of getting a reference to the global object
        // For details, see http://stackoverflow.com/questions/14119988/return-this-0-evalthis/14120023#14120023
        var window = this || eval('this'), document = window['document'], navigator = window['navigator'], jQueryInstance = window["jQuery"], JSON = window["JSON"];
        if (!jQueryInstance && typeof jQuery !== "undefined") jQueryInstance = jQuery;
```

In summary, `this || (0, eval)('this')` is changed to `this || eval('this')` which causes "window is undefined "error.

## 🎛 Configuration (.babelrc, package.json, cli command)

.parcelrc:

```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.txt": ["@parcel/transformer-raw"]
  }
}

```

No other relevant configuration is there.

## 🤔 Expected Behavior

Do not translate `(0, eval)('this')`.

## 😯 Current Behavior

`(0, eval)('this')` is translated

## 💻 Code Sample

The website where this is happening is open-source and available here: https://github.com/phpstan/phpstan/tree/master/website

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2.0.0
| Node             |  v16.4.0
| npm/Yarn         | v1.22.4
| Operating System | macOS, but happens on Ubuntu too

**Comment by ondrejmirtes** [comment]
Further debugging this - it's happening even with `--no-optimize`. I'm finding out that even with `--no-optimize`, Parcel does some modification on the source code. For example `knockout-latest.js` in `node_modules` is minified, but with `--no-optimize`, the code of `knockout-latest.js` is "beautified" (formatted and expanded to multiple lines) in the final bundled `.js` file again. And also in that code `(0,eval)("this")` is changed into `eval("this")` so whatever process is responsible for that is responsible for that mistake.

**Comment by ondrejmirtes** [comment]
One more test: This issue is reproducible both with and without my browserlist config:

```
"browserslist": ["defaults", "not IE 11"]
```

**Comment by ondrejmirtes** [comment]
Here's the simplest reproduction project: https://github.com/ondrejmirtes/parcel-issue-7116

Run:

```
yarn install
yarn run build
cd dist
http-server -p 8000 # needs http-server installed locally, or simply browse with a server of your choice
```

Visit localhost:8000 and you'll see this error in the console:

```
Uncaught TypeError: A is undefined
    <anonymous> knockout-latest.js:7
    <anonymous> knockout-latest.js:139
    <anonymous> knockout-latest.js:5
```

What's interesting that it works with `parcel serve` but not with the production build.

**Comment by ergomesh** [comment]
I have the same behavior when using an old version of firebase 2.4.2. it serves fine, but when I deploy even with `--no-optimize` it fails

```
firebase-web.js:12 Uncaught TypeError: Cannot read properties of undefined (reading 'navigator')
    at firebase-web.js:12
    at Object.<anonymous> (firebase-web.js:2)
```

It seems more like your issue is the same as mine, that navigator is unavailable. 

related code from firebase-web.js [version 2.4.2](https://www.npmjs.com/package/firebase/v/2.4.2)

```
function Da(a,b){b.push('"',a.replace(Fa,function(a){if(a in Ea)return Ea[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return Ea[a]=e+b.toString(16)}),'"')};function Ga(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^la()).toString(36)};var Ha;a:{var Ia=aa.navigator;if(Ia){var Ja=Ia.userAgent;if(Ja){Ha=Ja;break a}}Ha=""};function Ka(){this.Va=-1};function La(){this.Va=-1;this.Va=64;this.N=[];this.me=[];this.Wf=[];this.Ld=[];this.Ld[0]=128;for(var a=1;a<this.Va;++a)this.Ld[a]=0;this.de=this.ac=0;this.reset()}ma(La,Ka);La.prototype.reset=function(){this.N[0]=1732584193;this.N[1]=4023233417;this.N[2]=2562383102;this.N[3]=271733878;this.N[4]=3285377520;this.de=this.ac=0};
```

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by ondrejmirtes** [comment]
Hi, I just tried Parcel 2.0.1 and this problem still persists there.

**Comment by ondrejmirtes** [comment]
Alright, I just tried it in the minimal reproduction repo and it's fixed there, looks like yarn botched the upgrade and left some dependencies behind in my main project. Gonna look into it.

**Comment by ondrejmirtes** [comment]
Alright, figured it out - looks like there's a wide difference between `yarn upgrade parcel` and `yarn upgrade parcel -L`.

**Comment by manjoine** [comment]
I still have the problem with my specific issue and 2.0.1 I can setup a repo if you like?
