### ISSUE TITLE
Invalid Parcel Config on fresh install

### ISSUE THREAD

**Issue by nikokozak** [parcel-bundler/parcel#7120]
# 🐛 bug report

On attempting to run `parcel`, fails citing `@parcel/core: Invalid Parcel Config`

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  {
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel": "^2.0.0"
  }
}
}
```

Clean install of Parcel following the "get started instructions". Only previous command: `git init`.  

## 🤔 Expected Behavior

Parcel should run with no internal errors.

## 😯 Current Behavior

Parcel errors out, citing `@parcel/core: Invalid Parcel Config` 

```
node_modules/@parcel/config-default/index.json:149:2
  148 |   },
> 149 |   "compressors": {
>     |   ^^^^^^^^^^^^^ Possible values: "extends", "validators", "filePath", "resolveFrom"
  150 |     "*": [
  151 |       "@parcel/compressor-raw"
```

## 🔦 Context

None other than a clean install in an empty folder.

## 💻 Code Sample

`npm init`
`npm install --save-dev parcel`
`parcel`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2.0.0
| Node             | v16.10.0
| npm/Yarn         | v7.24.0
| Operating System | macOS Big Sur 11.4

**Comment by mischnic** [comment]
It works fine for me (and it installs `@parcel/core@2.0.0` and `@parcel/config-default@2.0.0`). You probably got an older version of `@parcel/core` for some reason.

**Comment by nikokozak** [comment]
In package-lock.json:

```
node_modules/@parcel/core": {                                              
  681       "version": "2.0.0",                                                       
  682       "resolved": "https://registry.npmjs.org/@parcel/core/-/core-2.0.0.tgz",   
  683       "integrity": "sha512-wiY3XyGetCpek0aEi+xB0eQQUn4v9xt20AKx71KpU30SShwcHnVEUEVxuVEi7+NgJQsUCs      p8nXUeZluwRTfUFA==",
```

I agree it's strange, but I can't quite figure out what's causing it.

**Comment by mischnic** [comment]
Can you share the complete lockfile?

**Comment by nikokozak** [comment]
Sure!

[package-lock.json](https://gist.github.com/nikokozak/a0098f339149833ee6730d93351acecf)

**Comment by mischnic** [comment]
That is identical to mine.

Are you actually invoking the locally installed Parcel version and not a global one? Usually you'd want to use `npx parcel`:
> ```
> npm init
> npm install --save-dev parcel
> parcel
> ```

**Comment by nikokozak** [comment]
You're absolutely right - I dug around and realized that I had a global parcel installation, which is what was being invoked and conflicting.

Running with `npx parcel` also worked. 

Thank you so much for your time.
