### ISSUE TITLE
proxy with websocket: failed: Invalid frame header

### ISSUE THREAD

**Issue by suhaotian** [parcel-bundler/parcel#7123]
# 🐛 bug report

Hi, I'm trying move my old project to parcel, but the websocket proxy didn't work(my old project is ok):

![2021-10-18 at 11 40 AM](https://user-images.githubusercontent.com/6512574/137665941-2105c47a-b1e1-4cde-b4ca-304ecdd71974.png)

## 💻 Code Sample

You can check the sample code here to reproduce: https://github.com/suhaotian/parcel-starter/tree/socket.io-proxy

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2.0.0
| Node             | v14.0.0
| npm/Yarn         | yarn
| Operating System | MacOS

**Comment by satoshi-soya** [comment]
Same problem。

**Comment by mischnic** [comment]
I don't understand why, but using this proxyrc instead seems to work:

```js
const { createProxyMiddleware } = require("http-proxy-middleware");

const target = "http://localhost:7080/";

module.exports = function (app) {
  app.use(
    "/io",
    createProxyMiddleware("/io", {
      target,
      ws: true,
    })
  );

  app.use(
    "/api",
    createProxyMiddleware({
      target,
      changeOrigin: true,
    })
  );
};
```

The Parcel upgrade probably also meant an upgraded `http-proxy-middleware` for you, causing this difference.
