### ISSUE TITLE
Migrating from v1, dependency not found in package.json

### ISSUE THREAD

**Issue by eliasjnior** [parcel-bundler/parcel#7128]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

In a empty project, just install the Chakra UI with the following command:

```
yarn add @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^4
```

After that, in a JSX try to import:

```jsx
import { Link } from '@chakra-ui/layout'
```

## 🤔 Expected Behavior

The code should be compiled normally.

## 😯 Current Behavior

The build is failing:

```
@parcel/resolver-default: External dependency "@chakra-ui/layout" is not declared in package.json.
@parcel/core: Failed to resolve '@chakra-ui/layout' from './assets/js/webcomponent/components/ProgramList.jsx'
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | v12.22.7
| npm/Yarn         | 1.22.15
| Operating System | MacOS

**Comment by mischnic** [comment]
Do you want to build n app or a library? It looks like Parcel is building a library. https://parceljs.org/getting-started/migration/#package.json%23main

Apart from that: I think you should be importing that component from `@chakra-ui/react`. (Or alternatively also add `@chakra-ui/layout` as a direct dependency of your project)

**Comment by eliasjnior** [comment]
@mischnic it's an app. A simple React App.

But about the dependency, yes, I can use the `@chakra-ui/react`, but the `@chakra-ui/layout` is also installed. Shouldn't we consider that we have this kind of dependency? Or some argument to skip this lib check?

For now, changing `/layout` to `/react` is what I did.

**Comment by mischnic** [comment]
What does your package.json look like? (E.g. a `main` field, `engines`, ...)

**Comment by eliasjnior** [comment]
@mischnic funny fact... I tested in a new repository, from scratch and worked fine with both imports 🤔
I think the cause must be something in the package.json, I will try to figure out what was.
