### ISSUE TITLE
No transformers found for .yml files 

### ISSUE THREAD

**Issue by mkaraula** [parcel-bundler/parcel#7135]
# 🐛 bug report

When having a `.yml` file parcel fails with `No transformers found for foo.yml`. When looking at `node_modules/@parcel/config-default/index.json`it looks like `@parcel/transformer-yaml` is only used for files ending with .y**a**ml but not .yml 

Using this .parcelrc fixes it 

```
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.yml": ["@parcel/transformer-yaml"]
  }
}
```

but I guess this should also be part of the default config. 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |   2.0.0

**Comment by devongovett** [comment]
Want to send a PR to add it? https://github.com/parcel-bundler/parcel/blob/v2/packages/configs/default/index.json#L21

**Comment by mkaraula** [comment]
Of course :) 

Here it is: https://github.com/parcel-bundler/parcel/pull/7192
