### ISSUE TITLE
Two index.[hash].js files produced when running parcel build

### ISSUE THREAD

**Issue by samwatkinson1** [parcel-bundler/parcel#7136]
# 🐛 bug report

Two index.[hash].js files are produced when building using parcel build. One of which is invalid, has differing file sizes/hash and produces errors such as `ReferenceError: invalid assignment left-hand side`.
## 🎛 Configuration (.babelrc, .parcelrc, cli command)
.babelrc
```js
{
  "presets": [
    ["@parcel/babel-preset-env"],
    [
      "@babel/preset-react",
      {
        "runtime": "automatic"
      }
    ]
  ]
}
```
.parcelrc
```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{js,mjs,jsx,cjs,ts,tsx}": [
      "@parcel/transformer-js",
      "@parcel/transformer-react-refresh-wrap"
    ]
  }
}
```
cli command ran
```
parcel build src/index.html --no-source-maps
```

## 🤔 Expected Behavior

Only one valid index.[hash].js file should be produced.

## 😯 Current Behavior

When running the `parcel build src/index.html --no-source-maps` command, two index.[hash].js files are produced. Both files have differing file sizes and hashes, and one produced causes errors if used as a script on the browser. The cli command produces a similar output to below:
```
√ Built in 14.39s

dist\index.html                377 B    7.62s
dist\index.f17801eb.js     972.13 KB    7.33s
dist\index.03ed802e.css    214.37 KB    3.73s
dist\index.28982703.js     936.22 KB    6.92s
```

The file with a smaller file size is the culprit for errors, as using this within the browser causes a variety of errors. Before the build, the parcel-cache is cleared. Including source maps does not affect the issue. This has only occured since migrating from parcel@2-beta2 to parcel@2.0.0. 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2.0.0
| Node             | v14.18.1
| npm/Yarn         | yarn v1.22.17
| Operating System | Windows 10 v21H1 build 19043

**Comment by samwatkinson1** [comment]
I've reran the command with --log-level verbose and compiled the errors into the file below:
[log.txt](https://github.com/parcel-bundler/parcel/files/7372675/log.txt)
Hope it is of use!

**Comment by mischnic** [comment]
Please provide a code sample that reproduces the issue.

Two JS files are generated because `<script type="module">` is transformed into a `<script nomodule>` and a `<script type="module">` in the output. This is by design, if you don't care about the older browsers, set a more recent browserslist config

**Comment by samwatkinson1** [comment]
Ah I see that clarifies the issue, modifying our production browsers list to query more recent browsers fixes this for me. 

Using the "supports es6-module" query does produce the same error already reported in #6749 too.

Appreciate the quick response!
