### ISSUE TITLE
'alias' is being picked up in node_module package.json

### ISSUE THREAD

**Issue by HHogg** [parcel-bundler/parcel#7139]
# 🐛 bug report

Parcel uses the alias property from node_modules when importing. Is this desired? Should it only be taken into account inside the project that parcel is bundling? 

## 🤔 Expected Behavior

IMO it is expected that alias is ignored when importing from node_modules. 

## 😯 Current Behavior

Parcel is resolving aliases of published packages. 

## 💁 Possible Solution

Ignore node_modules that have an alias defined in the package.json. 

## 🔦 Context

I am importing from a published package (one of my own) also has a site which is bundled by parcel. This site has an 'alias' property used for resolving the package internally. 

I am importing that package from another project that also parcel is bundling, however it is taking into the 'alias' property that is set in the package.json of the imported/published package. 

Note: This wasn't happening in Parcel v1. 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2.0.0
| Node             | v14.18.0
| Yarn         | v1.22.15
| Operating System | Mac OS

**Comment by mischnic** [comment]
At the moment, this is "per design". Though I haven't really thought about it specifically. I guess one question to ask here is whether Webpack/Rollup/Esbuild/... apply the aliases for node_modules.

**Comment by HHogg** [comment]
Thanks for the quick reply @mischnic and also the work that has gone into v2 of Parcel (It's been my goto bundler since the very first release (~I should definitely donate~) ✅ ). 

I'm not sure about other bundlers, I'll take a look and get back to you. 

I can't think about a use case for aliases to be used from packages 🤔  although I've never built a bundler before, so I'm unlikely to know. For my use case, its purely a development config so having it published and Parcel picking it up means it breaks the package, so I'm currently looking at a few options: 

- Finding a way to temporarily exclude it before publishing (with some script probably)
- Finding another way to reference the package in the site within the same repo (probably using yarn workspaces instead) 
  - **Edit 1:** I use semantic-release for autopublishing and generating change docs, and [semantic-release doesn't support workspaces](https://github.com/semantic-release/semantic-release/issues/193) 
  - **Edit 2:** However it's just one package, so might work with [configuring the npm-plugin]
  - **Edit 3:** After a bit of tweaking, I managed to get my project set up with yarn workspaces. 
- Removing all the references to package from the site within the same and replacing it with relative roots. 
- Getting a PR up here for comments and possible acceptance (this might take me a while to find/understand the part in the codebase) (any pointers and I'm happy to contribute).

**Comment by HHogg** [comment]
Thinking about how this might work with yarn workspaces/lerna. 

I'm not how importing from one yarn workspace into another is resolved, but if the imported workspace is using the alias field, I wonder if changing this would break that 🤔

**Comment by HHogg** [comment]
I'm going to close this as I found an alternative to using the alias field on my side, with yarn workspaces. It was an easy enough change so if I'm the only one with this setup there's no need to change parcel.
