### ISSUE TITLE
Postcss making a lot of problems after update

### ISSUE THREAD

**Issue by sque89** [parcel-bundler/parcel#7155]
# 🐛 bug report

To date we are using parcel 2.0.0-beta.1 to bundle a CSS file with postcss. Everything works currently as expected. Now i wanted to upgrade to parcel 2 but postcss makes a lot of trouble.

I cannot really imagine that this is a bug because i was not able to find anything similar in the issues. Is it a problem in my config?

## 🎛 Configuration (.babelrc, package.json, cli command)

I don't use a babel config anymore as the documentation suggests

**.postcssrc**

`{
  "plugins": {

    "postcss-easy-import": {},
    "postcss-at-rules-variables": {},
    "postcss-for": {},
    "postcss-each": {},
    "postcss-conditionals": {},
    "postcss-calc": {},
    "postcss-nested": {},
    "postcss-extend": {},
    "autoprefixer": {
      "grid": true
    },
    "postcss-preset-env": {
      stage: 0,
      importFrom: [
        "css/base/layout.css",
        "css/theme/colors.css",
        "css/theme/transitions.css",
        "css/theme/typography.css"
      ],
      features: {
        "nesting-rules": true
      }
    }
  }
}`

Package dependencies:

`"devDependencies": {

    "@rollup/plugin-commonjs": "^11.0.2",
    "@rollup/plugin-node-resolve": "^7.1.1",
    "autoprefixer": "^9.3.1",
    "choo-log": "8.0.0",
    "concurrently": "^4.0.1",
    "eslint": "^6.8.0",
    "eslint-config-standard": "^14.1.0",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-node": "^11.0.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "normalize.css": "^8.0.0",
    "parcel": "^2.0.0",
    "postcss": "^8.3.11",
    "postcss-at-rules-variables": "^0.3.0",
    "postcss-calc": "^8.0.0",
    "postcss-conditionals": "^2.1.0",
    "postcss-each": "^1.1.0",
    "postcss-easy-import": "^3.0.0",
    "postcss-extend": "^1.0.5",
    "postcss-for": "^2.1.1",
    "postcss-nested": "^5.0.6",
    "postcss-preset-env": "^6.7.0",
    "postcss-simple-vars": "^2.0.0",
    "rollup": "^2.2.0",
    "rollup-plugin-json": "^4.0.0",
    "rollup-plugin-sass-postcss": "^1.0.9",
    "rollup-plugin-terser": "^5.3.0",
    "rollup-plugin-visualizer": "^3.3.2",
    "stylelint": "^13.8.0",
    "stylelint-config-sass-guidelines": "^7.1.0"
  }`

## 🤔 Expected Behavior

CSS should be bundled without errors

## 😯 Current Behavior

When running: parcel build css/index.css

1. when a postcss @each rule is used (the cause seems to be the postcss-simple-vars plugin: _@parcel/transformer-postcss: postcss-simple-vars: Undefined variable $size_

2. @parcel/transformer-postcss throws an syntax error on each CSS calc statement. e.g.: min-height: calc(100vh - var(--navbar-height));

3. parcel now tries to transform css imported from node_module which results in an syntax error in some case because it is already

4. @parcel/transformer-postcss: input.toJSON is not a function

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0
| Node             |14.15
| npm/Yarn         |7.11.2
| Operating System |Manjaro

**Comment by devongovett** [comment]
Kind of hard to debug without more info, but perhaps the version of postcss you are using is not compatible? The `input.toJSON` error sounds like you are using an older version of postcss that isn't compatible with Parcel anymore.

**Comment by sque89** [comment]
@devongovett it turned out i was using some postcss plugins which relied on an outdated postcss version because they are unmaintained. So actually your comment pointed me into the right direction. Thanks a lot for that!
