### ISSUE TITLE
Parcel API not working

### ISSUE THREAD

**Issue by Devil7DK** [parcel-bundler/parcel#7156]
# 🐛 bug report

When I use the cli the project is building properly. But when I use Parcel API from @parcel/core no bundles are generated.

## 🎛 Configuration (.babelrc, package.json, cli command)

Using default parcel config

```json
{
  "name": "parcel-test",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "start": "node server.js",
    "build": "parcel build index.html"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@parcel/config-default": "^2.0.0",
    "parcel": "^2.0.0"
  }
}
```

## 🤔 Expected Behavior

Parcel should create assets in local filesystem.

## 😯 Current Behavior

No bundles are created. And bundle graph is empty object.

## 💻 Code Sample

```js
const { default: Parcel } = require('@parcel/core');
const { NodeFS } = require('@parcel/fs');
const { join } = require('path');

const bundler = new Parcel({
    defaultConfig: "@parcel/config-default",
    entrypoints: [join(process.cwd(), 'index.html')],
    outputFS: new NodeFS()
});

bundler.run().then(console.log).catch(console.error);
```

See [https://github.com/Devil7DK/Parcel-API-Test](https://github.com/Devil7DK/Parcel-API-Test)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0 |
| Node             | 14.17.3 |
| npm/Yarn         | 6.14.13 |
| Operating System | Windows |

**Comment by mischnic** [comment]
It should be `entries`:

```diff
diff --git server.js server.js
index 695409a..f931abc 100644
--- server.js
+++ server.js
@@ -3,7 +3,7 @@ const { join } = require('path');

 const bundler = new Parcel({
     defaultConfig: "@parcel/config-default",
-    entrypoints: [join(process.cwd(), 'index.html')]
+    entries: [join(process.cwd(), 'index.html')]
 });

 bundler.run().then(console.log).catch(console.error);
```

https://parceljs.org/features/parcel-api/#the-parcel-constructor

**Comment by Devil7DK** [comment]
Sorry @mischnic, I had the issue in a different project I'm working on so to share a reproducible sample I created that project in a hurry and made that mistake. I fixed that typo and it was working in this sample.

But, in my actual project even though I had that right it was not working. So I step by step updated this sample project to match my actual project (see [ts](https://github.com/Devil7DK/Parcel-API-Test/tree/ts) branch) and found that the bundling is not working when I use [targets](https://parceljs.org/features/targets/).

I have updated the sample by adding an target in package.json. Now when I use the API is not working.

**Comment by Devil7DK** [comment]
Hey @mischnic any updates on this...?

**Comment by Devil7DK** [comment]
Again... Any updates???

**Comment by Myrga** [comment]
Hello @Devil7DK,

I might have had the same issue. I looked at the Parcel configuration used by the CLI and I saw that, when using a target with no entries, entries was still set up.

In your case, it would look like: 
```javascript
import Parcel from "@parcel/core";

const bundler = new Parcel({
  entries: ['.'],
  defaultConfig: "@parcel/config-default",
  targets: ["app"],
});

bundler.run().then(console.log).catch(console.error);
```

Hopefully, it will help you and others :)

**Comment by Devil7DK** [comment]
Hi @Myrga 

I have moved to a different bundler in that project due to this issue and another one.

Anyway, will try the solution you have given in my sample.

Thank you.

**Comment by bao5** [comment]
> ```js
> import Parcel from "@parcel/core";
> 
> const bundler = new Parcel({
>   entries: ['.'],
>   defaultConfig: "@parcel/config-default",
>   targets: ["app"],
> });
> 
> bundler.run().then(console.log).catch(console.error);
> ```
I ran into the same problem. It seems that if you want to build specific targets, then you need to specify a folder containing `package.json` for `entries`, and specify the targest to build using `targets`.

In this situation, specifying entrypoint files (e.g. index.html) for `entries` does not work.

**Comment by HcroakerDev** [comment]
I was able to get the api working with this configuration:

```Javascript
let bundler = new Parcel({
  entries: ['.'],
  defaultConfig: '@parcel/config-default',
  defaultTargetOptions: {
    publicUrl: '/dist'
  }
});
```

And then I had to put this in my package.json:
```
"targets": {
    "client": {
      "source": "client/index.html",
      "context": "browser"
    },
    "server": {
      "source": "server/main.js",
      "context": "node",
      "outputFormat": "commonjs"
    }
  },
```

The docs are a little confusing and I would suggest the parcel team make a "guides" section to cater for newer developers?

**Comment by HcroakerDev** [comment]
What I actually ended up doing to get this to work was to create two bundlers:

```Javascript
let webBundler = new Parcel({
  entries: ['client/index.html'],
  defaultConfig: '@parcel/config-default',
  targets: {
    client: {
      context: "browser",
      distDir: "dist/client"
    },
  },
  hmrOptions: {
    port: 3000,
  },
  defaultTargetOptions: {
    publicUrl: '/dist',
  }
});

let serverBundler = new Parcel({
  entries: ['server/main.js'],
  defaultConfig: '@parcel/config-default',
  targets: {
    server: {
      context: "node",
      outputFormat: "commonjs",
      distDir: "dist/server"
    },
  },
  defaultTargetOptions: {
    publicUrl: '/dist',
  }
});
```

That way I could have my server running and watching for changes and my client running with HMR enabled as well.
