### ISSUE TITLE
[Parcel 2] Auto Installing failed all the time

### ISSUE THREAD

**Issue by TechQuery** [parcel-bundler/parcel#7159]
### `.parcelrc`

```json
{
    "extends": "@parcel/config-default",
    "transformers": {
        "*.{ts,tsx}": [
            "@parcel/transformer-typescript-tsc"
        ],
        "*.{png}": [
            "@parcel/transformer-raw"
        ]
    }
}
```

### `tsconfig.json`

```json
{
    "compilerOptions": {
        "target": "ES5",
        "module": "ES2020",
        "moduleResolution": "Node",
        "allowSyntheticDefaultImports": true,
        "experimentalDecorators": true,
        "jsx": "react",
        "lib": ["ES2020", "DOM"],
        "sourceMap": true,
        "outDir": "./dist/"
    },
    "include": ["src/**/*"]
}
```

## 🤔 Expected Behavior

no error

## 😯 Current Behavior

> Server running at http://localhost:1234
> 🚨 Build failed.
> 
> Error: Failed to install @parcel/transformer-webmanifest: process.chdir() is not supported in workers
> 
>   at install (\node_modules\@parcel\package-manager\lib\installPackage.js:131:11)      
>   at async PromiseQueue._runFn
>   (\node_modules\@parcel\package-manager\node_modules\@parcel\utils\lib\PromiseQueue.js:88:7)
>   at async PromiseQueue._next
>   (\node_modules\@parcel\package-manager\node_modules\@parcel\utils\lib\PromiseQueue.js:75:5)

## 🔦 Context

idea2app/React-MobX-Bootstrap-ts#1

## 💻 Code Sample

`src/index.html`

```html
<head>
    <link rel="manifest" href="manifest.json" />
</head>
```
run command without `@parcel/transformer-webmanifest` installed:

```shell
parcel src/index.html --open
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0 |
| Node             | 14.17.6 |
| NPM         | 6.14.15 |
| Operating System | Windows 10 Pro 21H1 |
| terminal | Git Bash |

**Comment by TechQuery** [comment]
When I installed & configured `@parcel/transformer-webmanifest` manually, I got a similar error:

> Error: Failed to install @parcel/packager-raw-url: process.chdir() is not supported in workers

Until I installed `@parcel/packager-raw-url`, my project got started finally...

I miss the **Auto installing of Parcel 1.x**...

**Comment by TechQuery** [comment]
Then I renamed `index.css` to `index.less`, I need to install `@parcel/transformer-less` & `less` manually;

In the end, I renamed `index.less` to `index.module.less`, I also need to install `@parcel/transformer-postcss`, `postcss` & `autoprefixer`...

**Comment by TechQuery** [comment]
Finally, I got a configure file of _Zero-configuration Bundler_ to finish my migration journey:

```json
{
    "extends": "@parcel/config-default",
    "transformers": {
        "*.{css,less}": [
            "@parcel/transformer-postcss"
        ],
        "*.webmanifest": [
            "@parcel/transformer-webmanifest"
        ],
        "*.{ts,tsx}": [
            "@parcel/transformer-typescript-tsc"
        ],
        "*.{png}": [
            "@parcel/transformer-raw"
        ]
    }
}
```

And have fun with my fat `package.json` of React-TypeScript PWA:

```json
{
    "devDependencies": {
        "@parcel/config-default": "^2.0.0",
        "@parcel/packager-raw-url": "^2.0.0",
        "@parcel/transformer-less": "^2.0.0",
        "@parcel/transformer-postcss": "^2.0.0",
        "@parcel/transformer-raw": "^2.0.0",
        "@parcel/transformer-typescript-tsc": "^2.0.0",
        "@parcel/transformer-webmanifest": "^2.0.0",
        "@types/react": "^17.0.31",
        "@types/react-dom": "^17.0.10",
        "@types/react-router-dom": "^5.3.1",
        "autoprefixer": "^10.3.7",
        "less": "^4.1.2",
        "parcel": "^2.0.0",
        "postcss": "^8.3.11",
        "typescript": "^4.4.4",
        "workbox-cli": "^6.3.0"
    }
}
```

**Comment by n-gt** [comment]
Same issues here, very messy...

wanted to get tailwind to work but it was complaining about postcss8, and postcss8 was asking for parcel 2, and parcel 2 is definitely not production ready atm.

**Comment by TechQuery** [comment]
@parcel-bundler Parcel failed to install packages automatically with PNPM too, there must be something wrong: #8304

**Comment by TechQuery** [comment]
Auto installation of NPM & PNPM works since `2.9.0`.

**Comment by mcqj** [comment]
Still seeing this error in 2.9.3
