### ISSUE TITLE
[Parcel 2] building failed with Husky Git hooks

### ISSUE THREAD

**Issue by TechQuery** [parcel-bundler/parcel#7161]
### `package.json`

```json
{
    "scripts": {
        "build": "parcel build src/index.html --public-url ."
    }
}
```

### `.husky/pre-push`

```shell
#!/bin/sh

. "$(dirname "$0")/_/husky.sh"

npm run build
```

## 🤔 Expected Behavior

Build locally without error.

## 😯 Current Behavior

> Error: No native build was found for platform=win32 arch=x64 runtime=electron abi=83 uv=1 libc=glibc node=14.17.6
>     loaded from: \node_modules\lmdb-store
> 
>     at Function.load.path (\node_modules\node-gyp-build\index.js:59:9)
>     at load (\node_modules\node-gyp-build\index.js:21:30)
>     at Object.<anonymous> (\node_modules\lmdb-store\index.js:6:49)
>     at Module._compile (\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
>     at Module.load (internal/modules/cjs/loader.js:937:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
>     at Module.require (internal/modules/cjs/loader.js:961:19)
>     at require (\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
>     at _lmdbStore (\node_modules\@parcel\cache\lib\LMDBCache.js:31:39)

## 🔦 Context

#7159 

## 💻 Code Sample

idea2app/React-MobX-Bootstrap-ts#1

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0 |
| Node             | 14.17.6 |
| NPM         | 6.14.15 |
| Operating System | Windows 10 Pro 21H1 |
| terminal | Git Bash |
| Husky | 7.0.4 |

**Comment by mischnic** [comment]
Does `npm run build` work if you run it manually outside of the git hook?

**Comment by TechQuery** [comment]
> Does `npm run build` work if you run it manually outside of the git hook?

Yes, it works.

**Comment by TechQuery** [comment]
My team and I have disabled `parcel build` in Husky Git hooks in Windows for a long time, is there anyone can resolve this bug?

**Comment by mischnic** [comment]
I just tried this on Windows, and it worked fine. But because your repo doesn't contain a lockfile, I was most likely using different versions than you.

**Comment by TechQuery** [comment]
There's a lock file: https://github.com/idea2app/React-MobX-Bootstrap-ts/blob/master/yarn.lock

**Comment by TechQuery** [comment]
It works with lastest versions of PNPM, Parcel & Husky: https://github.com/idea2app/React-MobX-Bootstrap-ts
