### ISSUE TITLE
@parcel/transformer-vue: Unknown script language: ".js"

### ISSUE THREAD

**Issue by TheBojda** [parcel-bundler/parcel#7182]
# 🐛 bug report

Parcel's vue transformer cannot parse .vue files with external js.

```js
<template>
    
</template>

<script src="./app.js">
</script>
```
This code throws: @parcel/transformer-vue: Unknown script language: ".js"

Parcel versions:
    "@parcel/transformer-vue": "^2.0.0",
    "parcel": "^2.0.0"

**Comment by TheBojda** [comment]
Possible solution: Cut the first character of the file extension (the dot), because the switch uses 'js' instead of '.js'.

**Comment by mischnic** [comment]
The fix for this was already merged: https://github.com/parcel-bundler/parcel/pull/7056
