### ISSUE TITLE
Uncaught (in promise) Error: Cannot find module '6f14adfddc7fba1996f0bfcf6f376782.jpg,18'

### ISSUE THREAD

**Issue by frederickalcantara** [parcel-bundler/parcel#719]
I get an error in the console log that says it cannot find module '6f14adfddc7fba1996f0bfcf6f376782.jpg,18', which has to do with the dist folder. Here is my file configuration 
![screen shot 2018-01-31 at 4 24 44 pm](https://user-images.githubusercontent.com/23001248/35648315-55c3b156-06a3-11e8-9edb-275bda1eb3f5.png)

https://github.com/frederickalcantara/rick-morty

**Comment by osdevisnot** [comment]
@frederickalcantara Looking at your repo, it seems the `./styles/styles.scss` is included twice, once in `src/styles.css` and also in `src/app.js`. I created a PR on your repo [here](https://github.com/frederickalcantara/rick-morty/pull/1/files), which seems to solve the issue.
