### ISSUE TITLE
IE 11: Arrow function when building

### ISSUE THREAD

**Issue by hazriqpedia** [parcel-bundler/parcel#7191]
# 🐛 bug report

Parcel generated js with arrow functions even with IE 11 on browerslist.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "widget",
  "version": "1.0.0",
  ...
  "targets": {
    "app": {}
  },
  "scripts": {
    ...
    "dev-embed": "parcel watch src/embed.js --dist-dir ./public --target app"
  },
  "devDependencies": {
    ...
    "@parcel/config-default": "2.0.0",
    "@parcel/transformer-raw": "2.0.0",
    "parcel": "2.0.0",
	...
	"@babel/plugin-transform-runtime": "^7.15.0",
    "@babel/preset-env": "^7.15.0",
    "@babel/preset-typescript": "^7.15.0",
  },
  "dependencies": {
    ...
    "@babel/runtime": "^7.15.3"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all",
      "ie 11"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version",
      "ie 11"
    ]
  }
}
```

```js

// .babelrc
{
  "plugins": ["@babel/plugin-transform-runtime"]
}
```

## 🤔 Expected Behavior

Generated `embed.js` should not have an arrow function.

## 😯 Current Behavior

Generated `embed.js` have an arrow function inside it. 

```js
// sample from generated embed.js
var parcelHelpers = require("@parcel/transformer-js/src/esmodule-helpers.js");
parcelHelpers.defineInteropFlag(exports);
parcelHelpers.export(exports, "applyDecoratedDescriptor", ()=>_applyDecoratedDescriptorDefault.default
);
parcelHelpers.export(exports, "arrayWithHoles", ()=>_arrayWithHolesDefault.default
);
parcelHelpers.export(exports, "arrayWithoutHoles", ()=>_arrayWithoutHolesDefault.default
);
parcelHelpers.export(exports, "assertThisInitialized", ()=>_assertThisInitializedDefault.default
);
```

## 💁 Possible Solution

N/A

## 🔦 Context

The code is working on modern browsers but not on IE 11 with "syntax error".  

Code working fine on Parcel 1 with no issues on modern browsers and IE 11. Confirmed that there's no arrow function in the generated file as well.

## 💻 Code Sample

N/A

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0  |
| Node             | v12.19.0 |
| npm/Yarn         | npm 6.14.8 |
| Operating System | Windows 10 |

**Comment by devongovett** [comment]
In development, Parcel uses a modern browser target by default. You can override this using the `--target` option. See https://parceljs.org/features/development#development-target

**Comment by hazriqpedia** [comment]
Hey @devongovett ,

If you see our scripts, we're do use `--target` :
```
"dev-embed": "parcel watch src/embed.js --dist-dir ./public --target app"
```

**Comment by mischnic** [comment]
See https://github.com/parcel-bundler/parcel/issues/6676, currently `parcelHelpers.export` incorrectly uses arrow functions for node_modules.
