### ISSUE TITLE
Scope hoisting: TypeError: b.default is not a constructor [with reproduction]

### ISSUE THREAD

**Issue by arty-name** [parcel-bundler/parcel#7196]
# 🐛 bug report

Building a simple script with a single dependency results in the `TypeError: b.default is not a constructor` when running, but only if built without `--no-scope-hoist`. This might be similar to #7183

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json, no other configuration
```json
{
  "dependencies": {
    "@kiltprotocol/core": "^0.24.0-6",
    "parcel": "^2.0.0"
  }
}
```

## 🤔 Expected Behavior

The code should not throw an error, regardless of hoisting.

## 😯 Current Behavior

Building the code and running it throws:
```
TypeError: v.default is not a constructor
    at /tmp/test/dist/input.js:1:49050
    at Object.<anonymous> (/tmp/test/dist/input.js:1:49325)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

If I add `--no-scope-hoist` when building the code, it doesn’t throw when run.

The imported file `@kiltprotocol/core/lib/balance/Balance.utils` does the following:
```js
import { BN, formatBalance } from '@polkadot/util'
export const KILT_COIN = new BN(1)
```

`@polkadot/util` re-exports `BN` from `bn.js`.

## 💁 Possible Solution

A wild guess: BN is imported by multiple files, once in an ESM context, once in CommonJS context. Without hoisting the imports are done differently, according to context. Hoisting ignores the context and reuses the ESM export in CommonJS code. If true, accounting for the context when hoisting will do the trick.

## 🔦 Context

I am building a cryptocurrency wallet browser extension, initially using webpack, but now switching to parcel. I was able to strip my code down to this minimal reproducible case.

## 💻 Code Sample

```js
// input.js
import { KILT_COIN } from '@kiltprotocol/core/lib/balance/Balance.utils';
console.log(KILT_COIN.toNumber());
```

```bash
yarn add @kiltprotocol/core@dev parcel
yarn parcel build input.js
node dist/input.js
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | v16.12.0
| npm/Yarn         | yarn 1.22.15
| Operating System | Ubuntu 21.10

**Comment by mischnic** [comment]
Smaller reproduction:

```js
// index.js
const util = require("./x.js");
console.log(new util.Foo());

// x.js
export { default as Foo } from "./y.js";

// y.js
module.exports = function Foo() {};
```

**Comment by Utsav2** [comment]
hi @mischnic, do you know if there's been any work to resolve this? Apollo Client has code that triggers this issue:

```
import { Observable, } from 'zen-observable-ts';
import 'symbol-observable';
var prototype = Observable.prototype;
var fakeObsSymbol = '@@observable';
if (!prototype[fakeObsSymbol]) {
    prototype[fakeObsSymbol] = function () { return this; };
}
export { Observable };
//# sourceMappingURL=Observable.js.map
```

```
Error in JS console with scope hoisting enabled:

Error: $77a110a91e0d610d$var$Observable is not a constructor
```

So any project that uses GraphQL presumably can't use scope hoisting.

**Comment by arty-name** [comment]
This seems to be fixed in https://github.com/parcel-bundler/parcel/releases/tag/v2.4.0
