### ISSUE TITLE
@parcel/core: Cannot find Parcel plugin "@parcel/transformer-typescript-types"

### ISSUE THREAD

**Issue by pelikhan** [parcel-bundler/parcel#7197]
# 🐛 bug report

Trying to build a TypeScript project with types leads to

    @parcel/core: Cannot find Parcel plugin "@parcel/transformer-typescript-types"

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
  "name": "test",
  "version": "0.0.0",
  "source": "src/index.ts",
  "module": "dist/module.js",
  "types": "dist/types.d.ts",
  "license": "MIT",
  "scripts": {
    "watch": "parcel watch",
    "build": "parcel build --no-autoinstall"
  },
  "devDependencies": {
    "@parcel/transformer-typescript-types": "^2.0.0",
    "parcel": "^2.0.0",
    "typescript": "^4.4.4"
  }
}
```

## 🤔 Expected Behavior

Build typescript project and product .d.ts file.

## 😯 Current Behavior

```
$ parcel build --no-autoinstall
🚨 Build failed.

@parcel/core: Cannot find Parcel plugin "@parcel/transformer-typescript-types"

.\node_modules\@parcel\config-default\index.json:4:26
    3 |   "transformers": {
  > 4 |     "types:*.{ts,tsx}": ["@parcel/transformer-typescript-types"],
  >   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Cannot find module "@parcel/transformer-typescript-types"
    5 |     "bundle-text:*": ["...", "@parcel/transformer-inline-string"],
    6 |     "data-url:*": ["...", "@parcel/transformer-inline-string"],

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## 💻 Code Sample

```typescript
export let x = 1
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel         |  2.0.0|
| Node          |   14.17.6|
| npm/Yarn    |     yarn 1.22|
| Operating System |Windows, git bash|

**Comment by mischnic** [comment]
Using your package.json running `yarn && yarn build`, I got
```js
@parcel/core: Cannot find Parcel plugin "@parcel/packager-ts"
```

After adding that as a dependency as well, it built successfully.

**Comment by drewdecarme** [comment]
I have the same issue here and the above-suggested fix didn't work for me. From what I can tell from the error report, Parcel might be trying to access the package from the wrong directory. I would expect that it would be in my `node_modules` but instead, the error report says it's looking for the package in the `Users/my_user_name/index`

```
$ parcel build
🚨 Build failed.

unknown: Could not resolve module "@parcel/transformer-typescript-types" from "/Users/my_user_name/index"
```

I think it's also probably worth noting that I'm on a MacBook Pro running Big Sur on an Intel chip

**Comment by crunchwrapsupreme666** [comment]
I'm also running into the same issue.

**Comment by ralvapil** [comment]
Just ran into the same error and the above workaround didn't seem to work for me either unfortunately. It seems to be something happening on MacOS machines, doesn't seem to happen on WSL for example.

**Comment by crunchwrapsupreme666** [comment]
Copy and pasting the default config's content `node_modules/@parcel/config-default/index.json` into the local `.parcelrc` seems to work.

**Comment by lann** [comment]
It has something to do with the project root being incorrectly set when calling `parcel build` with no input file. One workaround is to pass your source index, e.g. `parcel build src/index.js`.

**For others trying to debug:**
I traced the problem back to https://github.com/parcel-bundler/parcel/blob/d2a9b6bdd93855b468fa9911dad27a49e54e9557/packages/core/core/src/resolveOptions.js#L52 where `entries` has been resolved from the default `["."]` to the directory where I ran `parcel build` (e.g. `["/home/lann/my-project"]`). Then that line above appears to resolve to the _parent_ of my actual project root. It then tries to find a project root from there, which of course doesn't work properly.

**Comment by icopp** [comment]
Same problem here.

**Comment by simonschwitzky** [comment]
Can confirm this issue still persists, Parcel is looking for the module in `Users/my_user_name/index`.
```
"@parcel/packager-ts": "2.3.2"
"@parcel/transformer-typescript-types": "2.3.2"
"parcel": "^2.3.2"
```

**Comment by mrDarcyMurphy** [comment]
I ran into this as well. Deleting a stray `package-lock.json` and `.parcel-cache` in the parent folder has gotten my builds working again.

**Comment by peterhass** [comment]
I have a very similar issue here.

```
unknown: Could not resolve module "@parcel/transformer-yaml" from "/Users/peter/index"
```

Debugging into the code @lann mentioned leads me to the same observation. `getRootDir` sets the return value to my projects **parent directory**. https://github.com/parcel-bundler/parcel/blob/d2a9b6bdd93855b468fa9911dad27a49e54e9557/packages/core/utils/src/getRootDir.js#L14

Another fun thing: Parcel is rewriting my package.json file to the following .... 
```json
{
  "devDependencies": {
    "@parcel/transformer-yaml": "^2.3.2"
  }
}

```

**Update: With `parcel build --no-autoinstall` I don't end up with a invalid package.json file**
```

@parcel/core: Cannot find Parcel plugin "@parcel/transformer-yaml"

  /Users/peter/Documents/Business/nebenan.de/nebenan-landing-pages/node_modules/@parcel/config-default/index.json:21:22
    20 |     "webmanifest:*.{json,webmanifest}": ["@parcel/transformer-webmanifest"],
  > 21 |     "*.{yaml,yml}": ["@parcel/transformer-yaml"],
  >    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^ Cannot find module "@parcel/transformer-yaml"
    22 |     "*.{glsl,vert,frag}": ["@parcel/transformer-glsl"],
    23 |     "*.{gql,graphql}": ["@parcel/transformer-graphql"],
```

Wasn't able to find a good workaround yet. Manually passing source index via cli args works for me as well so maybe I move my whole `targets` configuration to args? Will update this comment if I have any new findings.

**Workaround: Having my own transformer config in .parcelrc**
Pretty much what was mentioned here: https://github.com/parcel-bundler/parcel/issues/7197#issuecomment-956963771

.babelrc
```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{yaml,yml}": ["@parcel/transformer-yaml"]
  }
}

```

**Comment by mischnic** [comment]
This will probably be fixed with https://github.com/parcel-bundler/parcel/pull/7537

**Comment by mischnic** [comment]
>  leads me to the same observation. getRootDir sets the return value to my projects parent directory.

This should be fixed with the current nightlies.

**Comment by Designer023** [comment]
I had these issues with a package in a pnpm monorepo. 

```
Error: Failed to install @parcel/transformer-typescript-types: pnpm failed to install modules
```

Adding the dependencies in the root `package.json` resolved the issue for me:

```
"@parcel/packager-ts": "2.3.2"
"@parcel/transformer-typescript-types": "2.3.2"
"parcel": "^2.3.2"
```
