### ISSUE TITLE
Glob alias `#/*` not respected when importing source files

### ISSUE THREAD

**Issue by akaltar** [parcel-bundler/parcel#7199]
# 🐛 bug report

Glob alias is simply not used/respected.
I tried stepping through the code in NodeResolver.js and I think the issue is trying to treat the filename as a URL/subpackage, which causes the alias resolution not to have the base path at all, hence no aliasing can happen on NodeResolver.js:232
Not sure how to fix though.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "typescript-react-custom-resolution-repro",
  "description": "Parcel TypeScript with custom alias resolution",
  "version": "1.0.0",
  "source": "src/index.html",
  "alias": {
    "#/*": "./src/$1"
  },
  "license": "MIT",
  "scripts": {
    "start": "parcel --open",
    "build": "parcel build",
  },
  "dependencies": {
    "react": "^16.14.0",
    "react-dom": "^16.14.0"
  },
  "devDependencies": {
    "@types/react": "^16.14.20",
    "@types/react-dom": "^16.9.14",
    "parcel": "^2.0.0",
    "typescript": "^3.9.10"
  }
}

```

## 🤔 Expected Behavior

`import 'App' from '#/App` should try to load `<project-root>/src/App.[js,ts]`

## 😯 Current Behavior

Alias isn't applied. Parcel is trying to load an index.js file.

```> parcel build

🚨 Build failed.

@parcel/core: Failed to resolve '#/App.tsx' from './src/main.tsx'

  D:\code\examples\typescript-react-with-custom-root\src\main.tsx:3:17
    2 | import { render } from 'react-dom'
  > 3 | import App from '#/App.tsx'
  >   |                 ^^^^^^^^^^^
    4 |
    5 | render(<App />, document.getElementById('app'))

@parcel/resolver-default: Cannot load file './index' in './src'.
💡 Did you mean './index'?
```

## 💁 Possible Solution

Not sure, maybe do alias resolution before trying to resolve as module?

## 🔦 Context

We're trying to move from Webpack to Parcel v2 on a big project. We don't want to replace all existing imports from root with `~/src/` (Which works). Instead we want to use the existing `#/` prefix to refer to root.
In theory glob alias should make this work, but it's not applied at all.
May be related to #7062

## 💻 Code Sample

https://github.com/akaltar/parcel-alias-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | v14.16.0
| npm/Yarn         | 6.14.11
| Operating System | Windows

**Comment by slaypni** [comment]
Same here. It was working on `2.0.0-rc.0`. Replacing `#` to another character such as `$` seems to work though.
