### ISSUE TITLE
🐛 not resolve 'srcset' url in html

### ISSUE THREAD

**Issue by itslooklike** [parcel-bundler/parcel#720]
### 🎛 Configuration (.babelrc, package.json, cli command)

`parcel src/index.html`
config "from the box"

### 🤔 Expected Behavior

url in `srcset` will be generate, and put pictures in `dist` folder

### 😯 Current Behavior

`srcset` urls stays as in source html

![image](https://user-images.githubusercontent.com/17547664/35650776-55e4f1e0-06ee-11e8-8542-ed0f20529fb9.png)

### 💁 Possible Solution

parsing `srcset` tag?

### 🔦 Context

i try to make retina ready html

info about `srcset`
https://htmlreference.io/element/img/
### 💻 Code Sample

```<img src="assets/restaurants/restaurant-mcdonalds.png" srcset="assets/restaurants/restaurant-mcdonalds@2x.png 2x" />```

![image](https://user-images.githubusercontent.com/17547664/35650845-8c4770be-06ee-11e8-869a-bd71e7607306.png)

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.5.1
| Node             | 8.9.3
| npm/Yarn         | 5.5.1
| Operating System | macos 10.13.3

**Comment by osdevisnot** [comment]
@itslooklike it seems @lbguilherme already resolved this in #681. It seems the fix will be available in next parcel release.

**Comment by brandon93s** [comment]
That's correct, this will be available in the next installer. You can use it now by installing from GitHub.

**Comment by mdings** [comment]
This still doesn't work for `srcset` defined on a `source` tag. 

For example:

```html
<picture>
    <source srcset="img/gallery/400x600.jpg" media="(min-width: 768px)">
    <img src="img/gallery/800x600.jpg">
</picture>
```

compiles to:

```html
<picture>
    <source srcset="img/gallery/400x600.jpg" media="(min-width: 768px)">
    <img src="/dist/f44ad9eb3800b52d8c644dd71c6f34d6.jpg">
</picture>
```
