### ISSUE TITLE
Parcel (via Typescript) does not find *.module.scss

### ISSUE THREAD

**Issue by jeffrson** [parcel-bundler/parcel#7231]
# 🐛 bug report

According to the documentation (https://parceljs.org/languages/sass/) imports of scss like
```js
import * as classes from './style.module.scss';
```
should work. However, the transpiler reports
```js
@parcel/transformer-typescript-types: Cannot find module './style.module.scss' or its corresponding type declarations.
```

## 🤔 Expected Behavior

No warning or error should be shown, styles should be imported with classnames as strings.

## 😯 Current Behavior

Lots of warnings.

## 🔦 Context

Yes, there are similar reports, but there's CSS, and no real solution. Also it should be correctly documented how it is supposed to work. I'm sorry I can't make any suggestion because I don't know how imports are done correctly.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | 16.13.ß
| npm/Yarn         | 1.2.17
| Operating System | Windows

**Comment by max-crcl** [comment]
Still an issue for me today. Any news?

**Comment by mischnic** [comment]
There isn't anything Parcel can do here, you need to tell TS about the css modules, so adding a file with
```ts
declare module '*.module.scss' {
  const value: Record<string, string>;
  export default value;
}
```
file somewhere, like https://parceljs.org/features/dependency-resolution/#typescript

**Comment by max-crcl** [comment]
Thanks for the reply.

I already had `declare module "*.scss";` inside a `parcel.d.ts` file, which seems to be sufficient for eslint, ts, ...
I now also tried your proposal.

It results in the same strange behavior: 
When I run `parcel build` the first time (no /dist folder), the error occurs. Running it again: the error doesnt occur.

I'll try to find out more about it...

**Comment by mischnic** [comment]
> I already had declare module "*.scss"; inside a parcel.d.ts file, which seems to be sufficient for eslint, ts, ...

The difference between the two is that `tsc` will pick up all ts files in your project, while the Parcel types transformer (and validator) only.

So either import that file or use a triple-slash directive (`/// <reference types="./parcel.d.ts" />`) e.g. in your index.js file to make sure this is picked up.

> When I run parcel build the first time (no /dist folder), the error occurs. Running it again: the error doesnt occur.

Are you getting this error from the validator or the types transformer?

**Comment by Sharklegs** [comment]
> I already had `declare module "*.scss";` inside a `parcel.d.ts` file, which seems to be sufficient for eslint, ts, ... I now also tried your proposal.

same to me, tsconfig include the *.d.ts does not work well when run build
use `/// <reference path="..." />`  in your ts file where you import css can solve the problem

**Comment by bratanon** [comment]
~Not sure this is the right way but if I add `"typeRoots": ["node_modules/@types", "src/types"]` to `tsconfig.json` I dont get these errors anymore.~

EDIT: Nope, did just work at first try, not consistent over builds.

In `src/types` I have a `parcel.d.ts` containing:
```typescript
declare module '*.module.scss' {
  const classes: Record<string, string>;
  export default classes;
}

declare module '*.module.sass' {
  const classes: Record<string, string>;
  export default classes;
}

declare module '*.module.css' {
  const classes: Record<string, string>;
  export default classes;
}

```

**Comment by schmolie** [comment]
Any new thoughts on this? 🤔 I also have declared modules and face same problem.

`@parcel/transformer-typescript-types: Cannot find module './Button.module.scss' or its corresponding type declarations.`

**Comment by mischnic** [comment]
You need to to this:

> So either import that file or use a triple-slash directive (/// <reference types="./parcel.d.ts" />) e.g. in your index.js file to make sure this is picked up.

**Comment by EvaCherkashyna** [comment]
Try writing to the console :    
```sh 
 npm config set legacy-peer-deps true 
````
And after that: 
```sh
 npm install 
```
It might help you.

**Comment by wkrueger** [comment]
Some extra info on this

  - As it is an error on the `d.ts` generator, it only happens with library target.

  - Adding the `//< reference path="..." />` at the root import fixed it.

  - The referenced `.d.ts` file which has the `declare module`'s must not have any import or export.

**Comment by iliocatallo** [comment]
Same problem here, even after following what suggested. It works if `d.ts` files are generated before running parcel (specifically, using [typed-scss-module](https://www.npmjs.com/package/typed-scss-modules))

**Comment by esegura71** [comment]
asi solucione el problema al 100% en mi caso y trabaja super bien!

en la carpeta src cree este archivo :

nombre del archvivo => react-app-env.d.ts
contenido del archivo => /// <reference types="react-scripts" />

**Comment by FlyAboveGrass** [comment]
I have define the correct module declaration, and include it in my tsconfig.json, but I still got the same problem.

finally, I solved this problem by exclude large folders with source files that I do not work on. hope it will help.

```"exclude": ["node_modules", "dist", ".yalc", "build", "public", "scripts"]```
