### ISSUE TITLE
In a workspace the Typescript transpiler uses tsconfig.json from root folder

### ISSUE THREAD

**Issue by jeffrson** [parcel-bundler/parcel#7232]
# 🐛 bug report

When transpiling a project in a workspace, the transpiler apparently uses tsconfig.json from workspace root instead of project.

## 🤔 Expected Behavior

Project's tsconfig.json should be preferred (if not used alone).

## 😯 Current Behavior

*Only* tsconfig.json from workspaces root is used - single workspace (project) not at all!

## 🔦 Context

The behaviour is quite contrary to tsc's behaviour. Tsc does not use any other tsconfig.json than that  located in the project.

BTW, .parcel_cache is created in workspace root as well. I'm not sure if this is correct - at least it was unexpected.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | 16.13.0
| npm/Yarn         | 1.2.17
| Operating System | Windows

**Comment by thewilkybarkid** [comment]
I noticed the point about the cache location too in https://github.com/thewilkybarkid/parcel-transformer-graphviz/commit/84914c7abab5038b6aceaf3419397d83b785258a: I had to set it explicitly in the workspace, but it did resolve against the workspace's `package.json` rather than the root's.

**Comment by marcosdiasdev** [comment]
@jeffrson did you manage to fix this?

**Comment by malixsys** [comment]
We use need to use a file not named `tsconfig.json` in root, is that possible?
