### ISSUE TITLE
JSX pragma leads to build failure

### ISSUE THREAD

**Issue by astegmaier** [parcel-bundler/parcel#7234]
# 🐛 bug report

If you include a JSX pragma at the top of your file like this:
```
/** @jsx h */
```
...parcel `@parcel/transformer-js` will throw an exception and `parcel build` will fail. This issue seems to have been noticed first by @Banou26 in follow-up comments to #6605, and it was also [reported on stackoverflow](https://stackoverflow.com/questions/69797352/building-error-at-parcel-transformer-js-cannot-access-a-scoped-thread-local-va), which led to a simplified repro below.

## 🎛 Configuration (.babelrc, package.json, cli command)

***package.json***
```
{
  "scripts": {
    "build": "parcel build src/index.tsx"
  },
  "dependencies": {
    "preact": "^10.5.15",
    "parcel": "^2.0.0"
  }
}
```

***src/index.tsx***
```js
/** @jsx h */
import { h } from "preact";

function ProductItem() {
  return <div>Hello World</div>;
}

```

## 🤔 Expected Behavior

When you run `parcel build src/index.tsx`, it should build correctly.

## 😯 Current Behavior

Instead, it throws this error:

```
$ parcel build src/index.tsx
⠙ Building index.tsx...
thread '<unnamed>' panicked at 'cannot access a scoped thread local variable without calling `set` first', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:168:9
🚨 Build failed.

@parcel/transformer-js: cannot access a scoped thread local variable without calling `set` first

  Error: cannot access a scoped thread local variable without calling `set` first
  at Object.transform (/Users/Andrew/Projects/stackoverflow-parcel-preact/node_modules/@parcel/transformer-js/lib/JSTransformer.js:365:31)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at async Transformation.runTransformer (/Users/Andrew/Projects/stackoverflow-parcel-preact/node_modules/@parcel/core/lib/Transformation.js:617:5)
  at async Transformation.runPipeline (/Users/Andrew/Projects/stackoverflow-parcel-preact/node_modules/@parcel/core/lib/Transformation.js:366:36)
  at async Transformation.runPipelines (/Users/Andrew/Projects/stackoverflow-parcel-preact/node_modules/@parcel/core/lib/Transformation.js:244:40)
  at async Transformation.run (/Users/Andrew/Projects/stackoverflow-parcel-preact/node_modules/@parcel/core/lib/Transformation.js:170:19)
  at async Child.handleRequest (/Users/Andrew/Projects/stackoverflow-parcel-preact/node_modules/@parcel/workers/lib/child.js:217:9)

error Command failed with exit code 1.
```
Removing the JSX pragma line will fix the issue and the build will succeed.

## 💁 Possible Solution

Not sure, but probably related to the discussion on #6605

## 🔦 Context

I was trying to help answer [this question on stackoverflow](https://stackoverflow.com/questions/69797352/building-error-at-parcel-transformer-js-cannot-access-a-scoped-thread-local-va) where someone was using parcel with preact. I recommended just removing the pragma, which should be a fine workaround (I think) but it still might be worth fixing this to make the experience smoother.

## 💻 Code Sample

See [this repo](https://github.com/astegmaier/stackoverflow-parcel-preact) for a reproduction.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | 14.17.5
| Yarn         | 1.22.15
| Operating System | Mac OS Big Sur 11.6

**Comment by bay-jacewhitten** [comment]
Was upgrading packages to 2.0.1 from beta.2 and hit this issue using @emotion/react and the /** @jsx jsx */ pragma for the css literals. 

Thankfully its a small refactor for me but wanted to add to this.

**Comment by tmoutinho** [comment]
Hey @bay-jacewhitten I am using emotion too. And it gives me the same error. How did you solve it?

I am using a mix of `.tsx` and `.js`, since the migration is still in process. 
In my files where I am using css attibute from emotion I have to add the `/** @jsx jsx */`

I am using react, not preact.

Thanks in advance

**Comment by bay-jacewhitten** [comment]
@tmoutinho fortunate for me I was only using the pragma in a couple places, so I simply refactored away the use of the css method for a styled div and span and then appended classes or vars as needed. For a bigger project this may be a much larger and arduous task. With that said, I went from 45 - 50 sec to almost 50% reduction in compile time (27 sec, 23 was the best), so there's that :) Also should be noted I upgraded from beta 2.

**Comment by tmoutinho** [comment]
@bay-jacewhitten  that's really nice. 

The project I am working on has tons of inline css. 
So refactoring using styled would improve the bundle size. Did not know that.

**Comment by sethsamuel** [comment]
Working off https://github.com/parcel-bundler/parcel/issues/6605#issuecomment-882082094, the problem is related to the React automatic runtime. Manually setting `automaticJSXRuntime = false` in `JSTransformer.js` fixes the crash, though obviously not a real solution.

As a workaround, switching from `/** @jsx jsx */` to `/** @jsxImportSource @emotion/react */` seems to resolve the problem for me. ~~The only downside is for some reason that triggers parcel to import chunks of my server code, and then all the node polyfills, which I'm still trying to figure out why.~~ ETA: This was just an erroneous import on my part.

**Comment by aspirisen** [comment]
I have the same issue in this case:
```
/** @jsx h */

import { h } from '../testutils/hyperscript'
```

**Comment by mischnic** [comment]
In the next Parcel version, this error will be printed:


<img width="655" alt="Bildschirmfoto 2022-05-18 um 23 49 10" src="https://user-images.githubusercontent.com/4586894/169161572-719c4e43-5df9-4c32-aacc-3edb33898c5b.png">



You also need to switch to the classic jsx runtime to set a pragma:
```js
/** @jsxRuntime classic @jsx h */
import { h } from '../testutils/hyperscript'

function ProductItem() {
  return <div>Hello World</div>;
}

console.log(ProductItem);
```
