### ISSUE TITLE
[Parcel 2] building failed with React

### ISSUE THREAD

**Issue by TechQuery** [parcel-bundler/parcel#7238]
## 🎛 Configuration

https://github.com/idea2app/React-MobX-Bootstrap-ts/blob/8f51f83/package.json
https://github.com/idea2app/React-MobX-Bootstrap-ts/blob/8f51f83/tsconfig.json
https://github.com/idea2app/React-MobX-Bootstrap-ts/blob/8f51f83/.parcelrc

## 🤔 Expected Behavior

Build successfully.

## 😯 Current Behavior

An inner `parcelRequire` returns a Module Factory instead of Module Object for [an External Package](https://github.com/idea2app/Edkit/tree/ee078a6/React) (which is bundled by Parcel 2), so any export of this module can't be accessed.

> Uncaught TypeError: Class extends value undefined is not a constructor or null

![image](https://user-images.githubusercontent.com/19969570/139951622-1808a2a5-4696-49cd-b631-4a46436b7058.png)

## 🔦 Context

1. #7159
2. #7161
3. https://ideapp.dev/React-MobX-Bootstrap-ts/ (the old version of this scaffold with Parcel 1 works well with Parcel 2 bundled packages)

## 💻 Code Sample

https://github.com/idea2app/React-MobX-Bootstrap-ts/tree/8f51f83/

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0 |
| Node             | 14.17.6 |
| NPM         | 6.14.15 |
| Operating System | Windows 10 Pro 21H1 |

**Comment by mischnic** [comment]
I cloned the repo and get no error. Please provide more detailed steps to reproduce this.

**Comment by TechQuery** [comment]
> I cloned the repo and get no error. Please provide more detailed steps to reproduce this.

But the built bundle failed to run in my Windows 10 all the time.
