### ISSUE TITLE
🐛 Using type="text" on input in HTML gets stripped

### ISSUE THREAD

**Issue by donaldallen** [parcel-bundler/parcel#724]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
🐛

### 🎛 Configuration (.babelrc, package.json, cli command)

No config. Just a HTML5 Boilerplate with Parcel.

### 🤔 Expected Behavior

When running ```parcel build index.html --public-url ./```, any HTML <input type="text"> should not be altered.

### 😯 Current Behavior

When running ```parcel build index.html --public-url ./```:

```<input type="text" name="FirstName" class="form-control" id="FirstName" placeholder="*Firstname" required>```

changes to

```<input name="FirstName" class="form-control" id="FirstName" placeholder="*Firstname" required="">```

### 💁 Possible Solution

Not sure.

### 🔦 Context

Need type="text" to stay, especially when using CSS [type="text"].

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.4.1
| Node             | 8.5.0
| npm/Yarn         | 5.3.0
| Operating System | macOS 10.13.2

**Comment by davidnagli** [comment]
When is this a problem? Because I’m pretty sure the browser defaults to assuming that an input is `type=“text”`, so it’s actually kinda redundant information.

Is there some case you encountered where this behavior get’s in the way?

**Comment by fathyb** [comment]
@davidnagli it's a problem because it breaks CSS selectors, it's a known side-effect from `htmlnano`

@donaldallen did you try the [`htmlnano` `removeRedundantAttributes` option](https://github.com/posthtml/htmlnano#removeredundantattributes)?

Example, in a `.htmlnanorc` file (see #445 for a list of possible location for the configuration) : 
```js
{
  removeRedundantAttributes: false
}
```

**Comment by donaldallen** [comment]
That did the trick. Thanks @fathyb!
