### ISSUE TITLE
Parcel 2.0.0 not reloading page on change anymore (Parcel 2.0.0-rc.0 still works fine)

### ISSUE THREAD

**Issue by ayebear** [parcel-bundler/parcel#7241]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

`.parcelrc`

```js
{
  "extends": [
    "@parcel/config-default"
  ],
  "reporters": [
    "...",
    "parcel-reporter-static-files-copy"
  ],
  "resolvers": [
    "@parcel/resolver-glob",
    "..."
  ],
  "transformers": {
    "*.{js,mjs,jsx,cjs,ts,tsx}": [
      "@parcel/transformer-js"
    ]
  }
}
```

`package.json` relevant lines
```
"@parcel/core": "^2.0.0",
"@parcel/resolver-glob": "^2.0.0",
"@parcel/transformer-image": "^2.0.0",
"parcel": "^2.0.0",
"parcel-reporter-static-files-copy": "^1.3.0",
```

## 🤔 Expected Behavior

Page should reload when editing a file.

## 😯 Current Behavior

Nothing changes, but the browser console gets cleared. No new code gets injected. Have to manually refresh to see code changes.

## 💁 Possible Solution

No idea how to fix this, but I suspect it's related to this if statement branching differently between 2.0.0 and 2.0.0-rc.0:
https://github.com/parcel-bundler/parcel/blob/v2.0.0/packages/runtimes/hmr/src/loaders/hmr-runtime.js#L113

Downgrading my packages to 2.0.0-rc.0 corrects the issue for me.

## 🔦 Context

This is for a pixi.js game project.

## 💻 Code Sample

I'll try to make a minimal example later that reproduces this issue.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | 16.12.0
| Yarn         | 1.22.15
| Operating System | Linux Mint

**Comment by ayebear** [comment]
Looks like #6685 is similar, however, there are no errors, even when preserving the log, just console cleared.

**Comment by Warry** [comment]
I have the same behaviour (using a proxyrc file and commonJs `require()` in the project) since I upgraded to 2.0.0 from rc and these plugins:

```
        "@parcel/plugin": "^2.0.0",
        "@parcel/transformer-elm": "^2.0.0",
        "@parcel/transformer-image": "^2.0.0",
```

no error, it silently fails.

**Comment by JaredSartin** [comment]
Same, it's rather annoying.

```
"@parcel/core": "2.0.0",
"@parcel/resolver-glob": "2.0.0",
"parcel": "2.0.0",
```

**Comment by ayebear** [comment]
The changes made to the hmrAcceptCheck function in this commit are a bit sus: https://github.com/parcel-bundler/parcel/commit/7468864f5ef8404309f4c681a2aa104d400cf5fc#diff-fa61a8f9c88b99c211b1544b5549ddc7137a02632c9fa8486875101aba57c356R337

But I am not 100% certain, there are many other factors that could affect it.

**Comment by ideaOwl** [comment]
I'm having this same problem too.  Running the RC gets reloading to work again, though other issues arise.

Parcel 2.0.1 is what I currently have, and I've noticed that including classic JS files (not ES modules) is what causes reloading to not happen anymore.  Trying this (https://github.com/parcel-bundler/parcel/issues/1591#issuecomment-944189408) gets reloading to work, but I don't want to have to rewrite my code to get things to work again.

**Comment by megaphonecolin** [comment]
We are also having this problem. Like [ideaOwl commented](https://github.com/parcel-bundler/parcel/issues/7241#issuecomment-961563322), we have classic JavaScript files linked with type="text/javascript" in our main entry point (index.html). The linked .js files are, however, from a third party, so we cannot add any code to them. Furthermore, our app is not compiled correctly by Parcel 2.0.0-rc.0, so I can't determine whether this issue occurs for us in rc.0. When rc.0 compiles our app, the objects created in our classic .js files are not found at runtime.

Thanks in advance for any help/fix.

**Comment by GeorgeFlorian** [comment]
I can confirm that this does not work for me as well.
I'm using `"parcel": "^2.0.1"` on VSC, on Ubuntu 20.04 LTS on a very simple and bare-boned structure.
```
{
  "name": "forkify-app",
  "version": "1.0.0",
  "description": "",
  "default": "index.html",
  "scripts": {
    "start": "parcel index.html",
    "build": "parcel build index.html"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/GeorgeFlorian/Forkify-App.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/GeorgeFlorian/Forkify-App/issues"
  },
  "homepage": "https://github.com/GeorgeFlorian/Forkify-App#readme",
  "devDependencies": {
    "@parcel/transformer-sass": "^2.0.1",
    "parcel": "^2.0.1"
  }
}
```
I have first tried running the script with the `--no-cache` option but to no avail.

I have changed from `<script defer src="src/js/controller.js"</script>` to `<script defer src="src/js/controller.js" type="module"></script>` and it started working for just one .js file.

Then I've created new .js files that I import inside `controller.js`. Changes made in those files do not reflect in the page. I have to manually reload the page in order to see the changes.

This bug kills productivity when you're trying to watch tutorials and you do the exact same things as the tutor, but it doesn't work as expected and then you have to search endlessly for a solution.

**Comment by ayebear** [comment]
I ended up upgrading to parcel 2.0.1 and just including this in my main js file:
```javascript
if (module.hot) {
  module.hot.accept(() => {
    location.reload()
  })
}
```

Which works for now. But, the default behavior should be either working HMR **or** page reload.

**Comment by megaphonecolin** [comment]
Any update on this issue? @ayebear's fix does not seem to work for us.
