### ISSUE TITLE
Typescript type assertion using angle brackets compiled incorrectly [with reproduction]

### ISSUE THREAD

**Issue by arty-name** [parcel-bundler/parcel#7243]
# 🐛 bug report

I tried to use [type assertion with angle brackets](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions) in my Typescript files, and Parcel compiled that to invalid code, throwing errors at runtime.

## 🎛 Configuration (.babelrc, package.json, cli command)

There’s no configuration

```bash
yarn parcel build fail.ts pass.ts
```

## 🤔 Expected Behavior

Parcel should strip type assertion without breaking the code:
```javascript
(async()=>{const o=await new Promise((o=>setTimeout(o,10)));console.log(o)})();
```
## 😯 Current Behavior

Parcel produces the following code: 

```javascript
(async()=>{await new Promise((e=>setTimeout(e,10))),console.log(a)})();
```

## 💁 Possible Solution

No idea

## 🔦 Context

I thought that `<Type>x` is clearer than `x as Type`, but I can still use the latter until the bug is fixed.

## 💻 Code Sample

 ```typescript
// fail.ts
(async() => {
  const a = await new Promise(resolve => setTimeout(resolve, 10));
  console.log(<number>a);
})();

// pass.ts
(async() => {
  const a = await new Promise(resolve => setTimeout(resolve, 10));
  console.log(a);
})();
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | v16.13.0
| npm/Yarn         | 1.22.15
| Operating System | Ubuntu 21.10

**Comment by mischnic** [comment]
This was already fixed (probably with https://github.com/parcel-bundler/parcel/pull/7114). It works correctly with the nightly (`yarn add parcel@nightly -E`)
