### ISSUE TITLE
Debugging target detection

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#7245]
# 🙋 feature request

Provide a way to print the target configuration that was inferred from/configured in `package.json` and CLI flags like `--public-url`. So what was detected and ideally where that information comes from.

## 💁 Possible Solution

- Either on `--log-level verbose`
- Or (what might be easier to use) a CLI command like `parcel print-targets` that does exactly that.

## 🔦 Context

cc @fregante 

https://twitter.com/fregante/status/1455678061119168519

**Comment by fregante** [comment]
It would be great to automatically print this information when an error happens, especially because often they don't have a lot of context information, for example:

- https://github.com/parcel-bundler/parcel/issues/7255
