### ISSUE TITLE
Caching issues with @parcel/resolver-glob

### ISSUE THREAD

**Issue by silvenon** [parcel-bundler/parcel#7247]
# 🐛 bug report

I've found some caching issues and errors related to `@parcel/resolver-glob` when adding and deleting files in the glob path.

## 🎛 Configuration (.babelrc, package.json, cli command)

CLI command:

```
parcel index.html
```

`.parcelrc`:

```json
{
  "extends": "@parcel/config-default",
  "resolvers": ["@parcel/resolver-glob", "..."]
}
```

## 🤔 Expected Behavior

Adding and removing files in globbed path should automatically update everything, including refreshing the page.

## 😯 Current Behavior

- adding new files inside the glob path doesn't refresh the page
- deleting a file inside the glob path causes a `no such file or directory` error that doesn't go away until I delete the cache (simply restarting Parcel doesn't work because the error gets cached), or if I add a new file

## 🔦 Context

I have a `posts` directory containing MDX files, so I'm importing them using `import posts from "./posts/*.mdx"` and rendering the post based on the URL, e.g. `/post/my-post` will render `posts['my-post'].default`.

## 💻 Code Sample

I created a [repository](https://github.com/silvenon/repro/tree/parcel-glob-cache-invalidation) where you can reproduce these issues, first start Parcel with `npx parcel index.html`. To reproduce the first issue you can add a new file in `globbed`, for example `d.js`, and see that the content wasn't updated, and that it still says "Loaded modules: a.js, b.css, c.js". `d.js` will be displayed once you reload the page manually. To reproduce the second issue delete any file in `globbed`, notice that the error doesn't go away despite refreshing the page or restarting Parcel, either delete the cache or add a new file in `globbed`.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | v16.13.0
| npm        | 8.1.0
| Operating System | macOS 11.6

**Comment by mischnic** [comment]
Related: https://github.com/parcel-bundler/parcel/issues/6875 and https://github.com/parcel-bundler/parcel/issues/6874

**Comment by silvenon** [comment]
I missed those when searching, sorry. 😅
