### ISSUE TITLE
Compiling deeply nested closures is failing with difficult to diagnose results

### ISSUE THREAD

**Issue by richard-jones** [parcel-bundler/parcel#7252]
# 🐛 bug report

I have a block of code which works as raw javascript running in the browser, but when compiled via parcel throws nonsensical errors.  It is difficult to give you an MRE, but here is the non-working fragment from my project:

```javascript
let ageComponents = [];
for (let i = 0; i < state_progression.length; i++) {
    ageComponents.push(
        edges.newHorizontalMultibar({
            id: "age_" + state_progression[i],
            dataFunction: function(state) {
                let ageRanges = ["<1M", "1-2M", "2-3M", "3-4M", "4-5M", "5M+"]
                return function(component) {
                    let histogram = false;
                    let states = component.edge.result.aggregation("states")
                    for (let i = 0; i < states.buckets.length; i++) {
                        let bucket = states.buckets[i];
                        if (bucket.key === state) {
                            histogram = bucket.age
                            break;
                        }
                    }

                    let values = [];
                    let longTail = 0;

                    if (histogram) {
                        for (let i = 0; i < histogram.buckets.length; i++) {
                            let bucket = histogram.buckets[i];
                            if (i < ageRanges.length - 1) {
                                values.push({label: ageRanges[i], value: bucket.doc_count});
                            } else {
                                longTail += bucket.doc_count;
                            }
                        }
                    } else {
                        for (let i = 0; i < ageRanges.length - 1; i++) {
                            values.push({label: ageRanges[i], value: 0});
                        }
                    }

                    values.push({label: ageRanges[ageRanges.length - 1], value: longTail});

                    return [{key: state, values: values}]
                }
            }(state_progression[i]),
            renderer : edges.nvd3.newHorizontalMultibarRenderer({
                barColor : ["#1e9dd8"],
                showLegend: false,
                xAxisLabel: "Age",
                yAxisLabel: "Count",
                marginLeft: 80,
                valueFormat: ".0"
            })
        })
    )
}
```

When compiled and executed in the browser this gives the error message on the 2nd line of the above: `i is not defined`.  It continues to provide this *exact same* error message even if I switch the loop counter from `i` to, say, `j`.  That is, it *does not* say `j` is undefined, it continues to say `i` is undefined, even though nowhere have I tried to use `i`.

I was able to get this code fragment to execute by commenting out 4 lines from the body of the fragment.  The ones which read:

```javascript
for (let i = 0; i < ageRanges.length - 1; i++) {
    values.push({label: ageRanges[i], value: 0});
}
```

and

```javascript
values.push({label: ageRanges[ageRanges.length - 1], value: longTail});
```

(note that changing the loop counter in this second loop to another letter such as `k` also did not affect the error message, it continued to complain about `i`.

Obviously, after removing those lines my code did not do the job it needed to do, so this wasn't a viable workaround.

After some experimentation, I was able to get the code to compile, execute and also do the correct job by restructuring it as follows:

```javascript
function stateDataFunction(state) {
    let ageRanges = ["<1 m", "1-2 m", "2-3 m", "3-4 m", "4-5 m", ">5 m"]
    return function (component) {
        let histogram = false;
        let states = component.edge.result.aggregation("states");
        let values = [];
        let longTail = 0;

        for (let i = 0; i < states.buckets.length; i++) {
            let bucket = states.buckets[i];
            if (bucket.key === state) {
                histogram = bucket.age
                break;
            }
        }

        if (histogram) {
            for (let i = 0; i < histogram.buckets.length; i++) {
                let bucket = histogram.buckets[i];
                if (i < ageRanges.length - 1) {
                    values.push({label: ageRanges[i], value: bucket.doc_count});
                } else {
                    longTail += bucket.doc_count;
                }
            }
        } else {
            for (let k = 0; k < ageRanges.length - 1; k++) {
                values.push({label: ageRanges[i], value: 0});
            }
        }

        values.push({label: ageRanges[ageRanges.length - 1], value: longTail});

        return [{key: state, values: values}]
    }
}

function getAgeComponents(stateProgression) {
    // Age distribution
    let ageComponents = [];
    for (let j = 0; j < stateProgression.length; j++) {
        ageComponents.push(
            new Chart({
                id: "g014-age-chart-" + stateProgression[j][0],
                dataFunction: stateDataFunction(stateProgression[j][0]),
                renderer: new HorizontalMultibarRenderer({
                    barColor: ["#1e9dd8"],
                    showLegend: false,
                    marginLeft: 80
                })
            })
        )
    }
    return ageComponents;
}
```

That is, I have separated the `dataFunction` closure from the body of the code that calls it, and placed it in its own function.  This seems to unconfuse the compiler, and the code starts to work.

## 🎛 Configuration (.babelrc, package.json, cli command)

.babel.rc:

```json
{
  "plugins": [
    [
      "@babel/plugin-transform-runtime",
      {
        "corejs": 2,
        "regenerator": true
      }
    ]
  ]
}
```

package.json (operational bits)

```json
{
  "alias": {
    "d3": {
      "global": "d3"
    },
    "nv": {
      "global": "nv"
    }
  },
  "targets": {
    "g014": {
      "source": "src/g014.js",
      "engines": {
        "browsers": "> 0.5%, last 2 versions, not dead"
      },
      "isLibrary": false,
      "optimize": false,
      "outputFormat": "global",
      "distDir": "../nglp/static/js"
    }
  },
  "devDependencies": {
    "@babel/core": "^7.15.5",
    "@babel/plugin-transform-runtime": "^7.15.0",
    "parcel": "latest",
    "sass": "^1.42.1"
  },
  "dependencies": {
    "@babel/runtime-corejs2": "^7.15.4",
    "@parcel/transformer-sass": "^2.0.0-rc.0",
    "jquery": "^3.6.0",
    "latlon-geohash": "^2.0.0"
  }
}
```

## 🤔 Expected Behavior

I'd expect any syntactically valid javascript to be compiled into equivalent working javascript

## 😯 Current Behavior

Everything is covered in the first section

## 💁 Possible Solution

The inner workings of a javascript compiler are well beyond me!  The workaround that I put in seems to suggest that the parcel compiler is having trouble with nested inline closures.

## 🔦 Context

There are 2 big problems here that this has caused me:

1. I have to debug a really non-obvious problem.  The issue and the fix aren't obviously related, the error message is confusing, the behaviour of the compiled code is highly sensitive to seemingly unrelated changes in the source.  It's a real, time consuming challenge to figure it out.

2. I don't know now if I can trust *at all* that parcel is going to produce code which executes as I've written it.  And what if, instead of just not working, it executes different instructions?

## 💻 Code Sample

As above

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc1
| Node             | 15
| npm/Yarn         | 7.7
| Operating System | Ubuntu 18.04

**Comment by mischnic** [comment]
> 2.0.0-rc1

First of all, try using 2.0.0 (stable).

Otherwise, please provide a code sample to reproduce that error. I took your code and added this at the top but didn't get the error you described.

```js
const state_progression = [1, 2, 3, 10];
const edges = {
    newHorizontalMultibar() {},
    nvd3: { newHorizontalMultibarRenderer() {} },
};
```

**Comment by richard-jones** [comment]
Thanks, I'll upgrade to the latest version and see if I can reproduce again, and if I can I'll do my best to get an MRE for you.  It might take a little while, other projects to focus on this week!
