### ISSUE TITLE
`Bundles must have unique names` has no context, like many other errors

### ISSUE THREAD

**Issue by fregante** [parcel-bundler/parcel#7255]
Also reported in https://github.com/parcel-bundler/parcel/issues/7245, but the topic was around targets instead

# 🐛 bug report

Errors almost always lack any context as to what's happening or what they even refer to. For example:

```
🚨 Build failed.

Error: Bundles must have unique names

  AssertionError [ERR_ASSERTION]: Bundles must have unique names
  at BundlerRunner.nameBundles
  ./node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:343:23)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async BundlerRunner.bundle
  ./node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:286:5)
  at async RequestTracker.runRequest
  ./node_modules/@parcel/core/lib/RequestTracker.js:721:20)
  at async Object.run
  ./node_modules/@parcel/core/lib/requests/ParcelBuildRequest.js:62:7)
  at async RequestTracker.runRequest
  ./node_modules/@parcel/core/lib/RequestTracker.js:721:20)
  at async Parcel._build ./node_modules/@parcel/core/lib/Parcel.js:397:11)
  at async Parcel.run ./node_modules/@parcel/core/lib/Parcel.js:275:18)
  at async run ./node_modules/parcel/lib/cli.js:374:7)
```

I had to follow the stack trace and add a plain `console.log(bundleNames)` before the assertion to see a list of the bundles that it's trying to generate and figure out what could be happening.

_Ah, I also had to add `await new Promise((resolve, reject) => setTimeout(resolve, 100000));` or else the output was promptly replaced, even with `CI=true parcel` 😰_

## 🎛 Configuration (.babelrc, package.json, cli command)

Any config

## 🤔 Expected Behavior

```
  AssertionError [ERR_ASSERTION]: Bundles must have unique names, found ["file.js, "file.css", "file.css"]
```

## 😯 Current Behavior

```
  AssertionError [ERR_ASSERTION]: Bundles must have unique names
```

## 💻 Code Sample

I assume this is reproducible via:

```
parcel build file.js file.css
```

```js
/* file.js */
import "./another.css"
console.log("Other JS code");
```

```css
/* file.css */
* {color: hotpink}
```
```css
/* another.css */
* {font-style: italic}
```

## 🔦 Context

I'm trying to [migrate from Webpack](https://github.com/refined-github/refined-github/pull/5014/files), but with Parcel I need to both reference the CSS file in the `manifest.json` (the entry point) and import other CSS files together with the JS file. This results in the `entry.js` file generating a `entry.css` file as well. No deduplication is attempted by Parcel, so I get the error

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             |16.4.2
| npm/Yarn         | 8.0.0
| Operating System | macOS

**Comment by pouya-loyall** [comment]
same issue, have you found any workaround?

parcel build --dist-dir wwwroot/js/quizzes/dist wwwroot/js/quizzes/*.js
× Build failed.
Error: Bundles must have unique names
  AssertionError [ERR_ASSERTION]: Bundles must have unique names
...

**Comment by runninyeti** [comment]
I was facing a very similar thing working with creating an npm package - my solution ended up being to add an `index.js` file that imported and exported all the directory components

e.g.
```javascript
// quizzes/index.js
import QuizA from "./quiz-a.js";
import QuizB from "./quiz-b.js";
...

export {
  QuizA,
  QuizB,
  ...
};
```

then switching the parcel command to something like
```bash
parcel build --dist-dir wwwroot/js/quizzes/dist wwwroot/js/quizzes/index.js
```

**Comment by pouya-loyall** [comment]
> I was facing a very similar thing working with creating an npm package - my solution ended up being to add an `index.js` file that imported and exported all the directory components
> 
> e.g.
> 
> ```js
> // quizzes/index.js
> import QuizA from "./quiz-a.js";
> import QuizB from "./quiz-b.js";
> ...
> 
> export {
>   QuizA,
>   QuizB,
>   ...
> };
> ```
> 
> then switching the parcel command to something like
> 
> ```shell
> parcel build --dist-dir wwwroot/js/quizzes/dist wwwroot/js/quizzes/index.js
> ```

exactly resolved by separating each scripts instead of *.js

**Comment by jeff-hykin** [comment]
for me it was because I didn't have `--target` as the correct value when trying to bundle node modules

failed:
```shell
npx parcel build
npx parcel build --target node 
```
succeeded:
```shell
npx parcel build --target default
```
part of my package.json 
```jsonc
    "engines": {
        "node": "10"
    },
    "targets": {
        "default": {
            "includeNodeModules": true
        }
    },
```

**Comment by vaibhavarora14** [comment]
Damn, you could also remove "main" from `package.json` to fix this error

**Comment by fregante** [comment]
> Damn, you could also remove "main" from `package.json` to fix this error

I have no `main` in my package.json and even specifically disable the `main` target: https://github.com/refined-github/refined-github/blob/fa2eb1c952da8d03672d19866782652474dae884/package.json#L131-L132

**Comment by leaumar** [comment]
Edit: problem solved so post removed.

It took quite some time to get around what seems like a silly problem. I eventually figured out how I could run the yarn script via my IDE and let it halt on a breakpoint inside parcel. That revealed the duplicate filenames at last.

If I may divert to the nature of the error rather than the message content for a moment... Now I need to change my project file structure and/or alter my build scripts to not overlap with any (possibly changing over time) imports through code paths, making it all fragile (my current wildcard entrypoints ensure the files I know to be critical are all there) and parcel-dictated. Parcel's UX really suffers at times with some updates. Can it really not deduplicate on file paths itself? It really shouldn't be considered a fault to specify a file to include in the build output through a CLI wildcard and code import at the same time IMO. This also makes it so that I can't really avoid inconsistent filenaming between dev time and build time, and that when I package my project for distribution I have to make sure to build against clean dirs so I don't package all the one-time-use WIP files. Before, simply all my root files were entrypoints (sometimes redundantly through html references) so they all generated fixed-name single output files, making development and packaging robust and simple.

**Comment by SsadiqRoy** [comment]
> 

This worked for me

> Damn, you could also remove "main" from `package.json` to fix this error

**Comment by TechQuery** [comment]
> I assume this is reproducible via:
> 
> ```shell
> parcel build file.js file.css
> ```
> ```js
> /* file.js */
> import "./another.css"
> console.log("Other JS code");
> ```
> ```css
> /* file.css */
> * {color: hotpink}
> ```
> ```css
> /* another.css */
> * {font-style: italic}
> ```

@fregante I found out why: The JavaScript with CSS imported needs to create a CSS bundle with the same base name, and at the same time, you make Parcel to build another CSS file with the same base name, so the Asset list in Parcel runtime will have 2 CSS assets with the same name.

This bug also shows in the scenario of "CJS & ESM format bundles with CSS": https://github.com/parcel-bundler/parcel/issues/7842#issuecomment-5207636339
