### ISSUE TITLE
CSS modules not applied when using web components

### ISSUE THREAD

**Issue by domenkozar** [parcel-bundler/parcel#7256]
# 🐛 bug report

When a library is using inline CSS modules, those don't get applied when they are used within a web component.

## 🤔 Expected Behavior

Styles are applied.

## 😯 Current Behavior

No styling.

## 🔦 Context

I'm using web components to wrap React components (since those are used within Elm).

## 💻 Code Sample

To reproduce see https://github.com/domenkozar/parcel-web-components-css-modules-issue

**Comment by mischnic** [comment]
I get this, so at least some styles are applied (not sure if this is totally correct though?):

![Bildschirmfoto 2021-11-07 um 17 34 03](https://user-images.githubusercontent.com/4586894/140653579-0e93ed00-f3d5-49db-a6cf-79d791f2b7be.png)

**Comment by domenkozar** [comment]
Did you revert the latest commit that disables shadow root?

**Comment by devongovett** [comment]
Hmm, I'm not sure how we could solve this. How could we know what shadow root to inject the styles into, especially if the code containing the css module is third party (e.g. in node_modules)?

**Comment by devongovett** [comment]
The best way to handle this is using bundle inlining. This will inline the contents of the CSS bundle as a JS string, which will allow you to inject it into a `<style>` element within your shadow root. https://parceljs.org/features/bundle-inlining/#inlining-a-bundle-as-text
