### ISSUE TITLE
Proxy doesn't appear to be running/working on 2.0, Mac OSX 12.0.1

### ISSUE THREAD

**Issue by crwilcox** [parcel-bundler/parcel#7257]
# 🐛 bug report

In an attempt to run the devserver + proxy, it seems the proxy isn't running? Or at least not functioning as expected?

I followed the instructions at https://parceljs.org/features/development/ and it seems to me that this rule should proxy . As authored it works on a linux OS, but not on my mac os x machine.

## 🎛 Configuration (.babelrc, package.json, cli command)

.proxyrc
```
{
  "/api": {
    "target": "http://localhost:8080/"
  }
}
```

## 🤔 Expected Behavior

```
http://localhost:1234/api -> http://localhost:8080/api
```

```
curl http://localhost:1234/api/endpoints

{ "some":  "json content served at http://localhost:8080/api/endpoints"}
```

## 😯 Current Behavior

the call currently returns the contents of http://localhost:1234.

I also used a linux machine I have, same node, npm, parcel versions. The proxy appears to be working on that machine, this may be OS X specific.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0 and 2.0.1
| Node             | 16.13.0
| npm/Yarn         | 8.1.0 
| Operating System | Mac OS X  v12.0.1

**Comment by mischnic** [comment]
This is working for me on macOS (10.15.5, but I don't think that makes a difference).

Is it possible that you are invoking a global Parcel install and your machines have different versions installed?

**Comment by crwilcox** [comment]
This seems unlikely as I have never (knowingly) used Parcel before friday. 

```
❯ nvm version
v16.13.0
❯ which parcel
parcel not found
❯ nvm use 16
Now using node v16.13.0 (npm v8.1.0)
❯ npm run start

> gcping@1.0.0 start
> parcel

Server running at http://localhost:1234
✨ Built in 21ms
```

separate window
```
❯ curl http://localhost:1234
<!DOCTYPE html>
<html>
...
❯ curl http://localhost:1234/api/endpoints
<!DOCTYPE html>
<html>
...
```

I installed v16 after this issue so my environment should be about as clean as it can?
```
❯ npm list -g
/Users/crwilcox/.nvm/versions/node/v16.13.0/lib
├── corepack@0.10.0
└── npm@8.1.0
```

**Comment by mischnic** [comment]
This works for me on macOS: https://github.com/mischnic/parcel-issue-7257

**Comment by crwilcox** [comment]
EDIT: it is working, but the path api/endpoints doesn't have content :)

Thank you @mischnic  for making a repro.

Start API
```
❯ npm run api

> api
> serve


   ┌────────────────────────────────────────────────────┐
   │                                                    │
   │   Serving!                                         │
   │                                                    │
   │   - Local:            http://localhost:3000        │
   │   - On Your Network:  http://100.88.157.113:3000   │
   │                                                    │
   │   Copied local address to clipboard!               │
   │                                                    │
   └────────────────────────────────────────────────────┘
```

Start Parcel
```
❯ npm run start

> start
> parcel index.html

Server running at http://localhost:1234
✨ Built in 48ms
```

Curl the endpoint. stripped additional styling output.
```
❯ curl http://localhost:1234/api/data
working
```

**Comment by mischnic** [comment]
You need to do `curl http://localhost:1234/api/data` to request this file: https://github.com/mischnic/parcel-issue-7257/blob/master/api/data

**Comment by crwilcox** [comment]
Yep. figured that out and was editing my comment. I am trying to re-run my parcel code, which is pretty basic, so trying to spot the difference, hopefully I can find it and this will help another that comes along :)

**Comment by crwilcox** [comment]
Okay, so the only difference is the webserver I am running is golang, though 

```
❯ curl http://localhost:8080/api/endpoints
working

❯ curl http://localhost:1234/api/endpoints
returns content of http://localhost:1234
```


By simplifying my package.json, I was able to get it to work though. The following works correctly:
```
"scripts": {
    "start": "parcel src/index.html",
    "build": "parcel build"
  },
  "devDependencies": {
    "parcel": "^2.0.1"
  }
}
```

However, my original package.json fails
```
{
  "source": "src/index.html",
  "scripts": {
    "start": "parcel",
    "build": "parcel build"
  },
  "devDependencies": {
    "parcel": "^2.0.1"
  }
}
```

It seems when calling `parcel` without a target, and relying on "source" the proxy isn't behaving as expected

**Comment by mischnic** [comment]
I've pushed a change to https://github.com/mischnic/parcel-issue-7257 to use the `source` field like in your example. Still works for me

**Comment by crwilcox** [comment]
I just pulled and the behavior of this is now failing in the same way as my repository:
```
❯ curl http://localhost:1234
hi<script src="/parcel-issue-7257.4ac18030.js"></script>%
❯ curl http://localhost:1234/api
hi<script src="/parcel-issue-7257.4ac18030.js"></script>%
❯ curl http://localhost:1234/api/data
hi<script src="/parcel-issue-7257.4ac18030.js"></script>%
❯ curl http://localhost:3000/api/data
working%
```

**Comment by andrewn** [comment]
I'm getting the same issue as @crwilcox using the linked test-case repo.

- macOS Monterey 12.0.1 (21A559)
- node v16.13.0
- npm 8.1.0
- yarn 1.22.15
- `which parcel` → `./node_modules/.bin/parcel`

I tried with both `npm` and `yarn` and see the same issue. 

```
$  curl http://localhost:1234
hi<script src="/parcel-issue-7257.062f15fb.js"></script>%
$  curl http://localhost:1234/api/data
hi<script src="/parcel-issue-7257.062f15fb.js"></script>%
$  curl http://localhost:3000/api/data
working%
```

I'd like to help debug this as I need the proxy for a project, but not sure where to start?

**Comment by mischnic** [comment]
Strange, i'm on 10.15 and it works correctly (for reference):
```
$ curl http://localhost:1234
hi<script src="/7257-proxy.356c6128.js"></script>%
$ curl http://localhost:1234/api/data
working%
$ curl http://localhost:3000/api/data
working%
```

**Comment by andrewn** [comment]
In the test-case repo, I changed the start script in `package.json` to specify the entry:

```diff
@@ -1,7 +1,7 @@
 {
   "source": "src/index.html",
   "scripts": {
-    "start": "parcel",
+    "start": "parcel src/index.html",
     "api": "serve",
     "query": "curl localhost:1234/api/data"
   },
```

And then it works as expected:

```
$  curl http://localhost:1234
hi<script src="/parcel-issue-7257.356c6128.js"></script>%
$  curl http://localhost:1234/api/data
working%
$  curl http://localhost:3000/api/data
working%
```

Is it worth mentioning that I'm using [`zsh`](https://support.apple.com/en-us/HT208050)? 🤷

**Comment by lettertwo** [comment]
FWIW, the example works for me on MacOS 11.6.1 (Big Sur).

**Comment by benmosher** [comment]
I am seeing something like this in a project with Yarn/npm `workspaces`. I am using Parcel in only one workspace (so far) but it was installed by Yarn in the root `node_modules` folder.

On a hunch (off of @mischnic's comment about global vs. local), I tried moving the `.proxyrc` file to the root next to the `node_modules` where it is installed, and now the proxy is working as expected.

**Comment by levrik** [comment]
I was also just hit by this issue and confirm @benmosher's theory. I'm using a Yarn workspace and moving `.proxyrc.js` to the workspace root works while having it on a local project doesn't.
If I find some time I'll try to pick this up for a fix but I can't promise.

**Comment by mischnic** [comment]
>  moving .proxyrc.js to the workspace root works while having it on a local project doesn't.

This is the current intended behaviour:

https://github.com/parcel-bundler/parcel/blob/b833a5f52387bf25cfa60a5555dd4e9a399b906d/packages/reporters/dev-server/src/Server.js#L368-L373

The reason being that the reporter doesn't have easy access to the list of entry points, e.g. if that is `root/packages/webapp/src/index.html`, the search could start from `root/packages/webapp/src` and then fallback on a the current `root/.proxyrc.js`
