### ISSUE TITLE
Parcel (2) Serve in Docker container does not rebuild project when files on a mounted volume are modified from the host

### ISSUE THREAD

**Issue by darrentorpey** [parcel-bundler/parcel#7258]
# 🐛 bug report

Parcel 2 server (`parcel serve`) running in a standard Node.js (16.13) Docker container does not detect changes to files on a mounted volume when they are updated from the host and thus does not rebuild the project it is serving. This prevents us from effectively using Parcel 2 in development.

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`
```js
{
  "dependencies": {
    "parcel": "2.0.0"
  }
}
```

`parcel serve src/index.js`

## 🤔 Expected Behavior

Parcel Serve rebuilds files when they are modified from the host

## 😯 Current Behavior

Parcel Serve does not attempt to rebuild the project when files are modified from the host.

To see the problem:

1. Run `docker compose up --build`
2. Edit a file in `src` directory from the host machine
    - Ensure you're not using an editor that uses "safe write" ([reference](https://parceljs.org/features/development#safe-write))
3. Observe that Parcel 2 does not see the file change and does not rebuild the project

👉🏻 Note that **Parcel 2's server *will* see the file change and will successfully rebuild if you `touch` the file from within the container itself**. To see this, make the change as above and notice that Parcel doesn't rebuild, then run:

## 💁 Possible Solution

I am guessing this is due to Parcel 2's new file watcher looking for an event that isn't being propagated to the container.

## 🔦 Context

In order to maintain a consistent build stack between all dev's work computers, CI/CD, and production, we use Docker. We're not doing anything usual with Docker so we expected this to work out of the box. It seems issues like these are common but Docker is a very common way to run dev environments, so it was a surprise that this does not work and will probably mean we cannot update to Parcel 2 until it's fixed.

## 💻 Code Sample

This repo offers a minimal-setup reproduction of the issue to help debug and assess possible workarounds or fixes:
https://github.com/darrentorpey/parcel2-fun/tree/parcel2-server-not-rebuilding

It has a quick README to demonstrate how to run it. It's a very small project so it's very easy to repro the issue.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | 16.13
| npm/Yarn         | 8.1.0
| Operating System | MacOS 10.15.7
| Docker Desktop | 4.1.1

**Comment by darrentorpey** [comment]
💁🏻‍♂️ Because I've seen so many similar tickets like this talking about a *different* scenario, I'll just call a couple things out quickly:
- This is not a "safe write" issue. Even a file edit via `echo "// nothing" >> src/animals.js` will demonstrate the issue
- I'm not talking about HMR here -- the project is never rebuilt by Parcel at all until you restart the container thus causing it to run `parcel serve` once again, but again it will only build once unless you go into the container itself and `touch` a file there that Parcel is watching.

**Comment by darrentorpey** [comment]
This is the closest issue I've seen to mine; I can't tell if it's the same issue as I don't have a Windows machine to try their issue on, and FWIW I think/hope my repro is even simpler: https://github.com/parcel-bundler/parcel/issues/3922

**Comment by Fabious** [comment]
I got the same issue, same setup as you on a Windows machine:

- If i edit a file on host, nothing happens. I can see the file correctly edited if i peek inside the container
- If i edit a file directly inside the container, rebuild happens! And the file is correctly edited on the host

**Comment by darrentorpey** [comment]
Sounds the same, @Fabious. I only implied this so let me be more explicit: the files in my case *are* instantly updated on the container as observed from the container itself, so when I do the `touch` the build not only happens again but does in fact have the new contents of the file.

There's just some disconnect with Parcel 2's file watcher noticing the file has change on the container.

**Comment by jtraub** [comment]
@darrentorpey I've faced the same problem today.

It seems that Parcel doesn't pickup changes in files that are under `/mnt` folder in WSL. Once you move them to `/home` and access through network (`\\wsl$\...`) it starts working. It is a workaround but it solved the problem for me so leaving a comment here for other people who might be looking for a workaround

I guess it is related to https://github.com/microsoft/WSL/issues/4417

**Comment by floyd-may** [comment]
This is keeping me from being able to upgrade from v1. Since v1 uses chokidar under the hood, I can put it into polling mode, which works okay enough.

Also, seems maybe this is the more updated issue to track in WSL?
https://github.com/microsoft/WSL/issues/4739

**Comment by viktorkasap** [comment]
Did you manage to find a solution?
I faced the same problem, everything works as it should on Maos, it doesn't work on Windows

https://github.com/kasapvictor/frontent-boilerplate/tree/parcel-2.5-develop

**Comment by djaffer** [comment]
I am stuck on this too. Thinking to downgrade to v1.

**Comment by viktorkasap** [comment]
> 

Parcel will work in docker if you install docker inside lnux terminal on windows

**Comment by djaffer** [comment]
any other solution. If the container closes then we will lose all changes. This is hacky workaround. This seems a fairly common issue most are facing.
