### ISSUE TITLE
Cannot resolve module, hard to debug where it's coming from

### ISSUE THREAD

**Issue by natew** [parcel-bundler/parcel#726]
🐛 bug report

![image](https://user-images.githubusercontent.com/12100/35717174-5e049994-0792-11e8-9aaf-52424837de81.png)

### 🤔 Expected Behavior

I can't tell where the error is coming from, this is actually more of a bug on the error message than the error itself. I'd expect an asset name + path.

### 😯 Current Behavior

Showing obfuscated names that point to internal parcel logic.

**Comment by davidnagli** [comment]
So basically you’re asking for better error handling on the HMR frontend…

I definitely think it’s something we should work on.

**Comment by Grafikart** [comment]
A thing I would change (that would improve this issue a bit) is including the name of the file as a prefix to the hash. Would it breaks some things ?
