### ISSUE TITLE
How to augment `import * as styles from "./index.css"` in TS?

### ISSUE THREAD

**Issue by chickencoding123** [parcel-bundler/parcel#7264]
The typescript keeps complaining about the css module imports:
```ts
import * as styles from "./index.css"
```
TS says there's a `styles.default`, but at run-time there's no such a thing and all the style rules are available directly under the `styles` variable. I tried making a type declaration under the `@types/css.d.ts`:
```ts
declare module '*.css' {
  export const styles: { [key: string]: string }
}
```
Which clearly does not work as I get `styles.styles` instead. How to augment the css modules that are imported this way?

PS: This way of importing is recommended by [parcel](https://parceljs.org/languages/css/#css-modules) for tree shaking.

**Comment by mischnic** [comment]
Does this work?
```ts
declare module '*.css' {
  export = { [key: string]: string }
}
```

**Comment by dmitrijs-balcers** [comment]
I would recommend using this transformer which is going to generate you `d.ts` files which will contain the record with correct keys based on your css modules: https://www.npmjs.com/package/parcel-transformer-ts-css-modules.

You can see sample usage here: https://github.dev/dmitrijs-balcers/react-css-modules-typescript-boilerplate/blob/master/src/components/App.tsx

**Comment by MartinDawson** [comment]
@mischnic No, my storybook webpack picks up the declarations fine but parcel does not. This issue also happens with scss files.

The workaround right now is to do `@ts-ignore`

Maybe it's because I'm using it with lerna & yarn workspaces..

**Comment by chickencoding123** [comment]
I did this:
```ts
declare module '*.css' {
  const styles: { [key: string]: string }
  export = styles
}
```
@dmitrijs-balcers Thank you magician from Riga. Nice transformer, didn't know about `export =` syntax
@MartinDawson I think this is better than `@ts-ignore`, but you can also use the transformer.
