### ISSUE TITLE
Incorrect output build

### ISSUE THREAD

**Issue by MartinDawson** [parcel-bundler/parcel#7266]
# 🐛 bug report

Generated output tested on `index.module.js` has this:

```
class $3dc63765f074c1e3$var$TextDecoration {
    constructor(text1, strikeThrough1, underline1){
        this.text = text1;
        this.strikeThrough = strikeThrough1;
        this.underline = underline1;
        this.text = text;
        this.strikeThrough = strikeThrough;
        this.underline = underline;
    }
}
```

Original:

```
class TextDecoration {
  constructor(
    public text: Text,
    public strikeThrough?: boolean,
    public underline?: boolean
  ) {
    this.text = text;
    this.strikeThrough = strikeThrough;
    this.underline = underline;
  }
```

Notice the duplicate constructor assignments :

```js
 this.text = text;
        this.strikeThrough = strikeThrough;
        this.underline = underline;
```

These variables don't exist and it throws errors on it.

## 🎛 Configuration (.babelrc, package.json, cli command)

I'm using yarn workspaces with lerna.

Root package.json

```
    "@parcel/packager-ts": "^2.0.0",
    "@parcel/transformer-typescript-types": "^2.0.0",
    "@parcel/transformer-sass": "^2.0.0",
```

Sub package.json

```
    "parcel": "^2.0.0",
    "@parcel/transformer-sass": "^2.0.0",
    "@parcel/transformer-typescript-types": "^2.0.0",
  "source": "src/index.ts",
  "exports": "./dist/index.modern.js",
  "main": "./dist/index.js",
  "module": "./dist/index.module.js",
  "types": "dist/index.d.ts",
   "build": "parcel build",
   "sass": {
    "includePaths": [
      "../../node_modules",
      "./node_modules"
    ]
  },
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0
| Node             | 12.20.1
| npm/Yarn         | 1.19.2
| Operating System | Ubuntu 12.x

**Comment by mischnic** [comment]
The duplication is "intentional": https://www.typescriptlang.org/play?#code/MYGwhgzhAEAqCmAPALgEXsA9gJzMglpgHbQDeAUNNFkRMtgK7DI4AUlV0ADgwEYj5g0ZEmQAuOKIA0HKj36DodbPgDW8WAAtsmBgHNNAfgm9MmEPDBEZnbnwFCGRACbxsAovGPRT5y0Q4ASjJZYU18CAA6ERRoAF5hUQBuUORwqOU1DW1dA3ileiytHX1NFNs0iMinV3d8T3yatw94cugAX3J2oA

The `public` keyword already does an assignment.

The fix for  the incorrect variable name is already merged: https://github.com/parcel-bundler/parcel/issues/7142
