### ISSUE TITLE
No support for custom babel config in a monorepo setup

### ISSUE THREAD

**Issue by desfero** [parcel-bundler/parcel#7269]
# 🐛 bug report

Parcel is not picking a custom `.babelrc` configuration in a monorepo setup.

A bare minimum repo to reproduce the issue: https://github.com/desfero/parcel-workspace-support.
The repo includes a basic monorepo setup on top of `npm workspaces` and `babel-plugin-transform-remove-console`.

Repro steps:
1. Clone repo
2. Run `parcel build` inside `apps/web` package
3. Go to `apps/web/dist` folder 
4. **`console.log` still stays in the final `dist` `main.js` even that we had `babel-plugin-transform-remove-console` plugin included in `.babelrc`**

## 🎛 Configuration (.babelrc, package.json, cli command)

A bare minimum configuration to reproduce bug: https://github.com/desfero/parcel-workspace-support

## 🤔 Expected Behavior

Parcel should properly use `.babelrc` for a given package in a monorepo setup

## 😯 Current Behavior

`.babelrc` is not taken into account during build time

## 💁 Possible Solution

The errors comes from `options.projectRoot` that's pointing to a `monorepo` root which at the end breaks `babel` config resolutions mechanism.

To simply patch setup temporary 
https://github.com/parcel-bundler/parcel/blob/ab0f5e1b25b187878e9fd9c014fb4191043baeb1/packages/transformers/babel/src/config.js#L93
can be replaced by 
```
cwd: process.cwd(),
```

Note: Seems like not only `transform-babel` package is affected. I can observe that `.parcel-cache` is also created in the monorepo root where it would be better to locale cache close to the package that's using parcel.

## 💻 Code Sample

Repository: https://github.com/desfero/parcel-workspace-support

**Comment by desfero** [comment]
Not exactly a duplicated but seems to be related https://github.com/parcel-bundler/parcel/issues/7232

**Comment by mischnic** [comment]
Have you seen/read https://github.com/parcel-bundler/parcel/issues/7075 ?

**Comment by desfero** [comment]
Oh i see, i have seen this one but after quick scan thought it's not related. 
Anyway it seems to be the same problem at the end. 
Closing the issue and will jump into the discussion there.
