### ISSUE TITLE
Failed to resolve '@material-ui/core/Unstable_TrapFocus'

### ISSUE THREAD

**Issue by useafterfree** [parcel-bundler/parcel#7273]
# 🐛 bug report

parcel build with react project with: `@material-ui/x-grid`

```js
{
    "@material-ui/core": "4.9.11",
    "@material-ui/x-grid": "4.0.0-alpha.27",
    "material-table": "1.57.1",
    "react": "16.9.0",
    "react-dom": "16.14.0",
}
```

## 🤔 Expected Behavior

should build

## 😯 Current Behavior

```
🚨 Build failed.

@parcel/core: Failed to resolve '@material-ui/core/Unstable_TrapFocus' from './node_modules/@material-ui/x-grid/dist/index-esm.js'

  /Users/boolean/Projects/Betterview/web/tower/node_modules/@material-ui/x-grid/dist/index-esm.js:1:1242
  > 1 |  from"@material-ui/core/Unstable_TrapFocus";import z from"@material-ui/core/FormControl";import T from"@material-ui/core/InputLabel";import A from"@material-ui/core/Select";import _ fr
  >   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2 | /*! *****************************************************************************
    3 | Copyright (c) Microsoft Corporation.

```
## 💻 Code Sample

```
// inside index.tsx
import {
  GridCellParams,
  GridColDef,
  GridSortModel,
  GridSortModelParams,
  LicenseInfo,
  useGridApiRef,
  XGrid
} from '@material-ui/x-grid';
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.1|
| Node             | v14.16.1|
| npm/Yarn         | 7.21.0 |
| Operating System | ProductName:	macOS / ProductVersion:	11.2.3 / BuildVersion:	20D91 |

**Comment by mischnic** [comment]
Which material-ui related dependencies did you declare? (core, styles, ...)

**Comment by useafterfree** [comment]
> Which material-ui related dependencies did you declare? (core, styles, ...)

@mischnic great question: I updated the first comment with those dependencies :)

**Comment by mischnic** [comment]
You should either upgrade material ui (I'm guess the versions of grid and core you're using are actually not compatible) or report this to https://github.com/mui-org/material-ui/issues.

There is no `@material-ui/core/Unstable_TrapFocus` file, so Parcel's error is correct here.

**Comment by useafterfree** [comment]
> You should either upgrade material ui (I'm guess the versions of grid and core you're using are actually not compatible) or report this to https://github.com/mui-org/material-ui/issues.
> 
> There is no `@material-ui/core/Unstable_TrapFocus` file, so Parcel's error is correct here.

The suggestion is to not fail fatally since it actually isn’t used. In webpack for example, it will not fail.
