### ISSUE TITLE
Inlining `fs.readFileSync` does not work for libraries

### ISSUE THREAD

**Issue by zr0z** [parcel-bundler/parcel#7275]
# 🐛 bug report

Inlining `fs.readFileSync` works as advertised in [the documentation](https://parceljs.org/features/node-emulation/#inlining-fs.readfilesync) for applications, but in the case of a library specified using the `main` key in `package.json`, Parcel complains that it can't resolves the `fs` module.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
  "name": "@visor/parcel@2",
  "version": "1.0.0",
  "description": "",
  "source": "src/index.js",
  "main": "dist/visor.js",
  "scripts": {
    "start": "parcel src/index.html",
    "build": "rm -rf dist && parcel build",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "zr0z@me.com",
  "license": "ISC",
  "devDependencies": {
    "parcel": "^2.0.1"
  }
}
```

## 🤔 Expected Behavior

I understand the behavior about not including Node Modules in the case of a library, especially the builtin ones, but the purpose of inlining `fs.readFileSync` is to include text content that you want to be part of the library at compilation time, not the `fs` module itself.

## 😯 Current Behavior

```sh
npm run build

> @visor/parcel@2@1.0.0 build
> rm -rf dist && parcel build

🚨 Build failed.

@parcel/core: Failed to resolve 'fs' from './src/view.js'

  /Users/zr0z/Sandbox/parcel@2-experiments/src/view.js:1:30
  > 1 | import { readFileSync } from "fs";
  >   |                              ^^^^
    2 |
    3 | export default readFileSync(__dirname + "/tpl.catalog", "utf-8");

@parcel/resolver-default: External dependency "fs" is not declared in package.json.

  /Users/zr0z/Sandbox/parcel@2-experiments/package.json:1:1
  > 1 | {
  >   | ^
    2 |   "name": "@visor/parcel@2",
    3 |   "version": "1.0.0",

  💡 Add "fs" as a dependency.
```

## 💁 Possible Solution

I guess a possible solution would be to detect inlining specifically for `fs.readFileSync` and adopt the behavior used in the case of an application.

## 🔦 Context

This breaks compatibility for our Parcel1 application and is delaying our migration.

We have several internal packages loaded as libraries in our main application that uses `fs.readFileSync` to inline XML file contents while keeping the original files and their file extensions in our repositories so they are still readable by the app used to create them.
Inlining removes the burden of having to deploy and serve those files statically or having to setup a pipeline to convert those files to JSON.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | v17.0.1
| npm/Yarn         | 8.1.0
| Operating System | macOs 12.0.1 M1 MacBook Pro

We love Parcel, thanks for an amazing bundler 🙇🏼

**Comment by zr0z** [comment]
I had a look at the documentation of SVGs that also have XML as their internal representation, and using the [`bundle-text: scheme `](https://parceljs.org/languages/svg/#inlining-as-a-string) from `@parcel/transformer-inline-string` solves my case.

Closing the issue, but I think `fs.readFileSync` should behave the same in case of an application and a library.

**Comment by sepsol** [comment]
@zr0z I'm having the same issue. Can you explain more about how you solved your problem? Did you do something like this?

```js
import fs from "bundle-text:fs";
import path from "path";

const data = fs.readFileSync(path.join(__dirname, "data.json"), "utf8");
console.log(data);
```

**Comment by jonahsnider** [comment]
This issue should not be closed, the bug is still present. @devongovett could you please re-open it?
