### ISSUE TITLE
🙋 Allow a html template entry like webpack

### ISSUE THREAD

**Issue by PerfectionCSGO** [parcel-bundler/parcel#728]
### 🔦 Context

I have a research project that uses a bunch of bleeding edge things. And it works with parcel, mostly. So that's nice.

This project has a webpack configuration and a parcel configuration. They're set up to be 'about'  the same.

With webpack, I provide main.tsx as an entry point and use Html plugin in webpack to generate a template index with the bundles.

With parcel I provide a index.html which refers to main.tsx and bundles those packages.

So in this set up the only code change required for me was to provide an alternative parcel index.html.

What I'd like to have is a way to tell parcel that 'these' are my packages and 'this' is my html entry.

### 💻 Code Sample

See https://github.com/PerfectionCSGO/nwn2cp for my current set up.
Parcel works but with the current configuration it will fail on the react-hot-loader/patch thing but that's a separate issue that's already been reported.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | latest
| Node             | 9
| npm/Yarn         | yarn
| Operating System | w10 64-bit

**Comment by davidnagli** [comment]
So are you trying to use _both_ Parcel _and_ Webpack on the same project?

**Comment by PerfectionCSGO** [comment]
It works. With just some minor configuration.
And yes, I am. This is for research purposes and demo purposes and it wouldn't be nessesairy in a real world scenario.

But it would just be nice to have this kind of feature to be able to switch over without having to change product code. 

/nopriority

**Comment by devongovett** [comment]
Going to close this. If you want to write a plugin to generate an HTML file, that seems like the right place for this to live.
