### ISSUE TITLE
When using targets, Parcel doesn't create declaration files

### ISSUE THREAD

**Issue by otaviobonder** [parcel-bundler/parcel#7281]
# 🐛 bug report

Whenever using `targets` in `package.json` to create different targets, the declaration files are not created, even if `types` is set in the `package.json`

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "targets": {
    "old": {
      "source": "src/old/index.ts",
      "distDir": "dist/old"
    },
    "default": {
      "source": "src/index.ts",
      "distDir": "dist"
    }
  },
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "files": [
    "dist",
    "README.md",
    ".npmrc"
  ],
  "scripts": {
    "start": "start-storybook -p 6006",
    "build": "rimraf dist && parcel build",
    "postbuild": "node scripts/build.js",
    "build:storybook": "build-storybook",
    "lint": "eslint \"src/**/*.ts\" \"scripts/**/*.js\""
  }
}
```

## 🤔 Expected Behavior

Parcel should create the declaration files.

## 😯 Current Behavior

Parcel is not creating the declaration files.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | 15.14.0
| npm/Yarn         | 7.7.6
| Operating System | Mac Monterey

**Comment by devongovett** [comment]
This is an interesting configuration. Your `old` and `default` targets have a `source` set, but `main` and `types` are not listed in `targets` and there is no root level `source` field. This results in only the `old` and `default` targets being compiled. If you want `main` and `types` to be compiled, you need to add a top-level `source` field.

**Comment by otaviobonder** [comment]
Unfortunately I really needed this config and moved to rollup. But what I did was to set the `types` in the `targets` as well, but this configuration was not accepted

**Comment by devongovett** [comment]
Sure, I guess I don't quite understand what you were expecting to happen. Which source file would be compiled to become main/types?

**Comment by samjt** [comment]
As it's not possible to set a types field in the targets section though, types are never generated when there is a target field, even if that target field only specifies parameters like `isLibrary:true, outputFormat: "esmodule"` and not any actual output destinations.

This seems to imply that you can't use typescript types and targets at the same time, which I'm not sure is intended behaviour. 

Also, this was really hard to discover as a bug from my perspective as I wasn't sure if this was a problem with yarn workspaces, caches, 'zero install' setup or something wrong with my tsconfig, as the JS files are still generated.
