### ISSUE TITLE
CSS modules do not work when applied to all files and global styles are imported from index.html

### ISSUE THREAD

**Issue by rabelloo** [parcel-bundler/parcel#7286]
# 🐛 bug report

If CSS modules are enabled for all files ([as described here](https://parceljs.org/languages/css/#enabling-css-modules-globally)) and the global stylesheet referenced in `index.html` ([like the first example here](https://parceljs.org/languages/css/)), neither global CSS nor CSS modules load correctly into the page.

Reproduction repository: https://github.com/rabelloo/parcel-css-issue

## 🎛 Configuration

Found at https://github.com/rabelloo/parcel-css-issue

## 🤔 Expected Behavior

CSS is correctly loaded into the webpage and applied to elements, even when CSS modules are enabled for all files and the global stylesheet is referenced in `index.html`

## 😯 Current Behavior

CSS is simply not loaded at all

## 💁 Possible Solution

Not sure how to solve it, it might be a bug in how [Parcel imports PostCSS config](https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/postcss/src/loadConfig.js), or it could be its HTML import resolution logic?

Workarounds are either:
1. import `index.scss` in `index.tsx` rather than referencing stylesheet in `index.html`
2. use default CSS modules config (delete `.postcssrc.json`) with `.module.` suffix

## 🔦 Context

Our team likes CSS modules by default (without `.modules.` file suffix), but we also need to apply our design system's global styles.

Importing from `index.tsx` rather than `index.html` is our current workaround, but because we automatically organise import statements, we have to open an exception to make sure `index.scss` (design system styles) is imported before modular CSS (app styles).

We would rather reference `index.scss` from `index.html` in the correct order and not worry about that.

Not to mention global CSS should start loading way before our app/JS is parsed.

## 💻 Code Sample

https://github.com/rabelloo/parcel-css-issue

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1 |
| Node             | 16.13.0 |
| npm        | 8.1.0 |
| Operating System | macOS Big Sur |

**Comment by devongovett** [comment]
CSS modules are really meant to be imported from JavaScript so that the proper class names can be referenced. It's not super obvious what should happen when linked directly from HTML. The workaround you've done seems fine to me. See also #4480.

**Comment by rabelloo** [comment]
You misunderstand. Only global CSS is imported from `index.html`, CSS modules are imported from JavaScript.

Please take a look at the reproduction repo.

**Comment by mischnic** [comment]
Does not setting "module" in the postcssrc and instead naming all css modules like "app.module.scss" work?

**Comment by rabelloo** [comment]
"module" is set in `postcssrc`, however we'd prefer modular CSS by default, with a single global sheet as an exception.

> Our team likes CSS modules by default (without .modules. file suffix), but we also need to apply our design system's global styles.

Edit: Ah sorry I misread the question. Yes your suggestion works just fine (possible solution number 2), but the above still stands.
