### ISSUE TITLE
🐛 invalidate the cache when a package is upgraded

### ISSUE THREAD

**Issue by fathyb** [parcel-bundler/parcel#729]
This is a 🐛 bug report

### 🤔 Expected Behavior

When upgrading/downgrading a package the cache should invalidate all the data related to this package.

### 😯 Current Behavior

It does not.

### 💁 Possible Solution

`rm -rf .cache` or `--no-cache`

### 💻 Code Sample

- `yarn init && yarn add react-dom@^16 react@^16 parcel-bundler`
- `echo "console.log('render', require('react-dom').render)" > index.js`
- `npx parcel build index.js` It works here
- `yarn upgrade react-dom@^15 react@^15`
- `npx parcel build index.js`
    ## booom!
   `Cannot resolve dependency './cjs/react-dom.production.min.js' at '/some-project/node_modules/react-dom/cjs/react-dom.production.min.js'`
- `npx parcel build index.js --no-cache` works back

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.5.1
| Node             | 8.9.1
| npm/Yarn         | yarn 1.3.2
| Operating System | macOS 10.13.2

**Comment by devongovett** [comment]
v2 should fix it.
