### ISSUE TITLE
Terser config keep_classnames don't build with original classes name.

### ISSUE THREAD

**Issue by bbohec** [parcel-bundler/parcel#7291]
# 🐛 bug report

Given the project have a `.terserrc` file with keep_classnames set to true
And the project use a class named `ProductionEventBus`
When the project build is executed with `parcel build`
Then the build file have a class named `$b5d844ad13508689$export$59a39a0b0112abf`.

## 🎛 Configuration (.terserrc)

``` json
{
    "keep_classnames": true
}
```

> the `.terserrc` configuration file is detected by parcel. Parcel-terser error on build if bad JSON config.

### Original
```typescript
export class ProductionEventBus implements EventBus {
    send (gameEvent: GameEvent): Promise<void> {
        return (this.gameSystem)
            ? this.gameSystem.onGameEvent(gameEvent)
            : Promise.reject(new Error('Gamesystem is not set.'))
    }

    setGameSystem (gameSystem:GenericGameSystem) {
        this.gameSystem = gameSystem
    }

    private gameSystem?: GenericGameSystem
}
```

### Build
``` javascript
class ProductionEventBus {
    send(gameEvent) {
        return this.gameSystem ? this.gameSystem.onGameEvent(gameEvent) : Promise.reject(new Error('Gamesystem is not set.'));
    }
    setGameSystem(gameSystem) {
        this.gameSystem = gameSystem;
    }
}
```

### Original
```typescript
export class ProductionEventBus implements EventBus {
    send (gameEvent: GameEvent): Promise<void> {
        return (this.gameSystem)
            ? this.gameSystem.onGameEvent(gameEvent)
            : Promise.reject(new Error('Gamesystem is not set.'))
    }

    setGameSystem (gameSystem:GenericGameSystem) {
        this.gameSystem = gameSystem
    }

    private gameSystem?: GenericGameSystem
}
```

### Build
``` javascript
class $b5d844ad13508689$export$59a39a0b0112abf {
    send(gameEvent) {
        return this.gameSystem ? this.gameSystem.onGameEvent(gameEvent) : Promise.reject(new Error('Gamesystem is not set.'));
    }
    setGameSystem(gameSystem) {
        this.gameSystem = gameSystem;
    }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | v14.15.4
| npm/Yarn         | 7.12.1
| Operating System | Windows 10

**Comment by devongovett** [comment]
This is not caused by terser but by scope hoisting. It's not possible to always keep variable names the same when scope hoisted, because two classes of the same name from different files would clash. If this is very important to you, you can use `--no-scope-hoist`.

**Comment by bbohec** [comment]
Thanks  @devongovett . It works as expected.
