### ISSUE TITLE
Build a library with JS and CSS

### ISSUE THREAD

**Issue by sque89** [parcel-bundler/parcel#7292]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)
```
{
  "source": "src/main.js",
  "main": "dist/main.js",
  "scripts": {
    "build": "npm run build:js && npm run build:css",
    "build:js": "parcel build",
    "build:css": "parcel build src/style.scss"
  },
  "devDependencies": {
    "@parcel/transformer-sass": "^2.0.1",
    "parcel": "^2.0.1"
  }
}
```
I am not sure if it is a bug. Basically what i want to do is to create a library with a script and some CSS which should be compiled from SASS. It appears that currenly parcel does not allow compiling another source type then the one specified in the main field.

## 🤔 Expected Behavior

JS and CSS are compiled properly while still being able to provide the main entry point for javascript (leaving CSS optional to import by the consumer)

## 😯 Current Behavior

If i run the build script at the step of comiling the SASS it gives the following error:

`@parcel/namer-default: Target "main" declares an output file path of "dist/main.js" which does not match the compiled bundle type "css".`

## 💁 Possible Solution
I could just leave out the source and main fields but then the main entry point would be missing for the consumer. I would like to know what the correct approach would be in such cases. I imagine that a library with some CSS is a quite common use case.

What also works for the library is to import the SASS file in the script but that leaves the consuming program (also parcel) bundling this specific CSS file with the JS which also feels wrong. In my consuming app i want to separately bundle JS and CSS by importing it separately in my index files.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.1
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by devongovett** [comment]
I would recommend using two targets for this case, rather than running Parcel twice. Something like this:

```json
{
  "main": "dist/main.js",
  "css": "dist/style.css",
  "targets": {
    "main": {
      "source": "src/main.js"
    },
    "css": {
      "source": "src/style.scss"
    }
  },
}
```

This way, you only need to run `parcel build` and it will compile both the JS and CSS. If you want to compile just one, run with the `--target` option, e.g. `parcel build --target css`. See the [targets](https://parceljs.org/features/targets/#multiple-targets) docs for more info.

**Comment by sque89** [comment]
Will do, thanks a lot!
