### ISSUE TITLE
Error cannot find module in generated typing file after build

### ISSUE THREAD

**Issue by quanphm** [parcel-bundler/parcel#7294]
# 🐛 bug report

I tried to create a library written by Typescript with Parcel 2.  The compiled JS files are fine but the generated typing file `index.d.ts` still has `import` clause which cause a type error:

```
Cannot find module 'types' or its corresponding type declarations.
```

## 🎛 Configuration

`package.json` file:

```json
"main": "dist/index.js",
"module": "dist/index.esm.js",
"types": "dist/index.d.ts",
"targets": {
  "main": {
    "optimize": true,
    "sourceMap": false
  },
  "module": {
    "optimize": true,
    "sourceMap": false
  }
},
```

## 🤔 Expected Behavior

I think the output of definition file should look like this:

```ts
export interface Value {
    id: number;
    value: unknown;
};

export const helpers: {
    log: (item: Value) => void;
};
```

## 😯 Current Behavior

```ts
export const helpers: {
    log: (item: import("types").Value) => void;
};
```

## 💻 Code Sample

This is my demo repository: 
https://github.com/mikunpham/parcel-build-issue

After running `yarn build`, you can see the result of the definition file here:
https://github.com/mikunpham/parcel-build-issue/blob/main/dist/index.d.ts

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1 |
| Node             | 14.18.0 |
| Yarn         | 1.22.15 |

**Comment by levino** [comment]
How was this resolved?

**Comment by levino** [comment]
Duplicate of #7951 and https://github.com/parcel-bundler/parcel/issues/8048

**Comment by sseidel16** [comment]
@quanphm  I am seeing the same issue. Did you find a way to resolve this?
