### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by proto1994** [parcel-bundler/parcel#73]
**First, this is a great tool.**
when I use it,  built show was correct, but console prompts **Uncaught ReferenceError: require is not defined** ,

node: 6.10
npm: 5.5.1

**Comment by devongovett** [comment]
Can you provide more info so we can reproduce your issue? Thanks!

**Comment by sanketsahusoft** [comment]
![image](https://user-images.githubusercontent.com/1733433/33703081-803d0c02-db4c-11e7-8282-ac4d547efed5.png)

Same here!

**Comment by jakoblind** [comment]
I had the same issue. I solved it by running node 8. @devongovett is node 8 a requirement for running parcel? If it is, then it should be stated somewhere in the docs.

**Comment by proto1994** [comment]
@jakoblind well. As you said, I upgraded node and solved it.Thanks.
node: 9.2.0
npm: 5.5.1

**Comment by thejameskyle** [comment]
This is a duplicate of #40, please search through issues before creating new ones
