### ISSUE TITLE
🙋 feature : add and Angular 5 recipe?

### ISSUE THREAD

**Issue by tatsujb** [parcel-bundler/parcel#730]
For this page https://en.parceljs.org/recipes.html

Would it be possible to make an Angular recipe as well. (even a bug-ridden wip one with a big fat disclaimer) ?

**Comment by davidnagli** [comment]
Hey thanks for taking the time to report this, but we have a separate repo for our website [parcel-bundler/website](https://github.com/parcel-bundler/website). Can you please open an issue there?
