### ISSUE TITLE
Scope hoisting doesn't work with opencv.js (opencv-ts)

### ISSUE THREAD

**Issue by PhotonQuantum** [parcel-bundler/parcel#7300]
# 🐛 bug report

Opencv.js can't be bundled with parcel. When run in the browser, the bundled page emits "ReferenceError: Can't find variable: Module" error. Disabling scope hoist solves this problem.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "parcel-opencv-min-reprod",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel": "latest"
  },
  "dependencies": {
    "opencv-ts": "^1.2.21"
  }
}
```

## 🤔 Expected Behavior

Built web page loads without error.

## 😯 Current Behavior

```
Uncaught ReferenceError: Module is not defined
    at YA (opencv.js:9852)
    at opencv.js:11
```

## 💁 Possible Solution

It seems that opencv.js is dumping something into the root namespace, and I suspect the side effects are not correctly handled.

## 💻 Code Sample

https://github.com/PhotonQuantum/parcel-opencv-min-reprod

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | 17.0.1
| pnpm         | 6.22.1
| macOS | 12.0.1

**Comment by mischnic** [comment]
https://unpkg.com/browse/opencv-ts@1.2.22/src/opencv.js doesn't work in strict mode (caused by `type=module`), even without running Parcel. So there's nothing we can do here.

**Comment by PhotonQuantum** [comment]
Thanks! I worked it around by moving opencv.js to web worker. Closing issue.
