### ISSUE TITLE
SyntaxError: Unexpected token '<' Error on index.html build file

### ISSUE THREAD

**Issue by rsa-doalllabs** [parcel-bundler/parcel#7305]
# 🐛 bug report

Final build files return errors when serving after migrating from previous Parcel version. Files: index.html

## 🎛 Configuration (.babelrc, package.json, cli command)

create-react-app w/parcel

```js
{
  "name": "parcel_test_app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.15.0",
    "@testing-library/react": "^11.2.7",
    "@testing-library/user-event": "^12.8.3",
    "parcel": "^2.0.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "web-vitals": "^1.1.2"
  },
  "scripts": {
    "start:parcel": "parcel public/index.html",
    "build:parcel": "parcel build public/index.html",
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

## 🤔 Expected Behavior

Build project; deploy build folder as web application by serving index.html or other related entry file. Same process has been used in previous Parcel V1.

## 😯 Current Behavior

Errors are returned when serving entry file.

**Index.html**
With node.
>
>```<!DOCTYPE html>```
>^
>
>SyntaxError: Unexpected token '<'
>     at Object.compileFunction (node:vm:352:18)
>     at wrapSafe (node:internal/modules/cjs/loader:1031:15)
>     at Module._compile (node:internal/modules/cjs/loader:1065:27)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) 
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
>     at node:internal/main/run_main_module:17:47

With Parcel Serve script

> × Build failed.
> 
> @parcel/core: Failed to resolve '/dist.ce4becc6.js.map' from './dist/index.html'
> 
> @parcel/resolver-default: Cannot load file '../dist.ce4becc6.js.map' in './dist'.
> ℹ Did you mean './dist.ce4becc6.js.map'?
> ℹ Did you mean './dist.ce4becc6.js'?
> 

## 💁 Possible Solution

N/A no working solution. My team has reverted to V1 after 26 hours of troubleshooting was spent.

## 🔦 Context

Semiconductor web applications and service workers. Impeding development on solutions for service engineers.

## 💻 Code Sample
Unfortunately, due to sensitive information and NDA protections against original config or contents of actual project could not be provided. However, we've successfully recreated the bugs by simply using create-react-app and installing Parcel 2.0.1 and stripping all requirements in the entry file of Index.html located in the public directory. Below the html returns a Hello World to eliminate any other suspicions. Launching the script above **build:parcel** completed a build while using **npx parcel serve dist/index.html** or **node dist/index.html** to serve. In Parcel V1 this has worked without an issue which lead to a longer pipeline deployment. Currently again the two scripts return either error. 

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta
      name="description"
      content="Web site created using create-react-app"
    />

    <title>React App</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <h1>Hello World!</h1>
  </body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | v16.13.0
| npm/Yarn         | 8.1.0
| Operating System | Windows 10 & OSX Monterey

**Comment by devongovett** [comment]
Can you provide any more information? It looks like you are perhaps running Parcel on the _output_ of a create-react-app (react-scripts) project? I'm not sure I can help without a little more context.
