### ISSUE TITLE
Parcel does not reload when module is not accepted

### ISSUE THREAD

**Issue by CGamesPlay** [parcel-bundler/parcel#7307]
# 🐛 bug report

My `index.html` file references `main.js`, which does not accept any hot updates:

```javascript
console.log("module loaded 1");
window.addEventListener("load", () => { console.log("onload"); });
```

## 🎛 Configuration (.babelrc, package.json, cli command)

No custom configuration is present.

## 🤔 Expected Behavior

In this configuration, modifying the code (e.g. changing "1" to "2") should reload the page, since the hot update cannot be accepted.

## 😯 Current Behavior

Instead, the hot update is accepted, the console is cleared, and the page is not reloaded. This is caused by [this check](https://github.com/parcel-bundler/parcel/blame/e0440dcbe6d6e419a412c8c568d94715cdb4282a/packages/runtimes/hmr/src/loaders/hmr-runtime.js#L339) returning true.

## 💁 Possible Solution

I don't know enough about the blame commit to propose a solution, unfortunately.

## 🔦 Context

A workaround is to manually accept the hot update and forcibly reload the page. However, this requires knowing that this is happening, so it's confusing for new users of Parcel, like myself. Additionally, this is a waste of a few cycles, since the updated module gets evaluated by the browser only to immediately reload the page and redo that work.

An example of the workaround code:

```javascript
if (module.hot) {
  module.hot.accept(() => {
    window.location.reload();
  });
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1 |
| Node             | 14.17.0 |
| npm/Yarn         | 1.22.17 |
| Operating System | macOS |

**Comment by devongovett** [comment]
Thanks for the detailed report!

**Comment by lucaseverett** [comment]
This appears to be the same issue I reported in October. My issue was regarding use of the Solid framework, but it's the same issue -- where Parcel is behaving as if module.hot has been accepted, even though it hasn't been.

https://github.com/parcel-bundler/parcel/issues/7171
