### ISSUE TITLE
replacing `**` with `Math.pow` breaks the code when operands are `BigInt`s

### ISSUE THREAD

**Issue by zohnannor** [parcel-bundler/parcel#7310]
# 🐛 bug report

The code like this

```ts
5n**10n;
```

would be converted to 

```js
Math.pow(5n, 2n);
```

and would produce an error, cause `Math.pow` does not accept bigints.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "newLine": "LF",
    "outDir": "./lib/",
    "sourceMap": true,
    "declaration": true,
    "jsx": "preserve",
    "lib": ["es2017", "dom", "ES2020", "ES2020.BigInt"],
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "target": "es2020",
    "skipLibCheck": true,
    "removeComments": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "noImplicitThis": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "baseUrl": "."
  },
  "exclude": ["node_modules"],
  "include": ["./src/**/*.ts"]
}
```

```js
"scripts": {
    "start": "parcel serve src/index.html"
}
```

## 🤔 Expected Behavior

It should not replace `**` with `Math.pow` if operands are instances of `BigInt`.

## 😯 Current Behavior

Code breaks with error message:
```js
Uncaught TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | `"parcel-bundler": "^1.12.5"`
| Node             | `v16.13.0`
| npm/Yarn         | `yarn 1.22.10`
| Operating System | `Windows 10`

**Comment by zohnannor** [comment]
Also applies to `**=` operator:
```js
x **= y;
```
transforms to
```js
x = Math.pow(x, y);
```

**Comment by devongovett** [comment]
This would be an SWC issue, but it seems that's what Babel does as well... https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=KwOwVGCMAMJA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.16.3&externalPlugins=&assumptions=%7B%7D

**Comment by mischnic** [comment]
It appear that the official solution for Babel is using a browserslist config that supports Bigints and therefore also `**` https://github.com/babel/babel/issues/13109.

**Comment by zohnannor** [comment]
I'm sorry for late response. Thanks, I've added `browserlist` field to my `package.json` with the following contents and the problem gone.

```js
"browserslist": {
  "production": [
    ">0.2%",
    "not dead",
    "not op_mini all"
  ],
  "development": [
    "last 1 chrome version",
    "last 1 firefox version",
    "last 1 safari version"
  ]
}
```

Closing the issue now.

Edit: `production` config still generates wrong code, I'll make it the same as development...
