### ISSUE TITLE
How can i include css in bundle ?

### ISSUE THREAD

**Issue by zababurinsv** [parcel-bundler/parcel#7311]
### Discussed in https://github.com/parcel-bundler/parcel/discussions/7299

<div type='discussions-op-text'>

<sup>Originally posted by **zababurinsv** November 15, 2021</sup>
My `package.json`
```
  "targets": {
    "main": false,
    "module": {
      "includeNodeModules": true,
      "optimize": true
    },
    "service": {
      "source": "./frontend/src/index.html"
    }
  },
  "devDependencies":  {
    "parcel": "2.0.1",
    "@parcel/packager-raw-url": "^2.0.1",
    "@parcel/transformer-webmanifest": "^2.0.1",
  }
```
I have this code

```
import React from 'react';
import { render } from 'react-dom';
import { useState, useEffect } from 'react';
import { AlarmList } from './components/Alarm'
import './css/index.scss';

.....

```
I want create bundle

```
  "component": "rimraf ./component/* && parcel build $npm_package_config_function --no-source-maps ",
```
Parameter    ` "includeNodeModules": true ` is include external packages in bundle

But i see css in bundle this 

```
import"./index.css"
```
And when I include this module in another module I get this error.
```
Uncaught SyntaxError: Unexpected token '.'
```

How can i include css style in bundle ?

</div>

**Comment by devongovett** [comment]
please keep discussions in discussions.
