### ISSUE TITLE
CSS Module Style Injection and React

### ISSUE THREAD

**Issue by cutterbl** [parcel-bundler/parcel#7319]
# Automatic CSS module injection

When reading various bits of React documentation, they all tell us that using CSS modules is pretty basic

```jsx
import React from 'react';
import styles from './myStyles.scss'

export default function MyComponent(props) {
  return <div className={styles.myCustomClass} {...props} />
};
```
Now, I've seen the console logging about `tree-shaking`, so I changed all of my import statements.
```js
import * as styles from './myStyles.scss';
```
And my build completes. But...

The default behavior here has always been that, when (and only when) my component would mount it would automatically inject the required CSS module of the specific component into the head of my document. This has been working great for well over a year.

But, I'm attempting to move my package build processes over from Rollup to Parcel. My builds are fine in Rollup, today, but I'm looking to make some changes and was trying out Parcel for faster, tighter builds. And things look great! 

Except for my CSS modules. When I run a build now it builds an external .css file and, looking at the bundle, that file is imported at the top of the file. 
```js
import('./myLibrary.css')
```
My parent project (which has an extremely complex Webpack build) has no idea what to do with this, when I import my component package, and it definitely isn't inlining my CSS.

Furthermore, when I look at my compiled code event further, I don't find references to these styles

```js
// source code
className={styles.myCustomClass}
// output code
className: {}
```

What I would expect, in the bundle, is something similar to:
```js
function styleInject(css, ref) {
  if ( ref === void 0 ) ref = {};
  var insertAt = ref.insertAt;
  if (!css || typeof document === 'undefined') { return; }
  var head = document.head || document.getElementsByTagName('head')[0];
  var style = document.createElement('style');
  style.type = 'text/css';
  if (insertAt === 'top') {
    if (head.firstChild) {
      head.insertBefore(style, head.firstChild);
    } else {
      head.appendChild(style);
    }
  } else {
    head.appendChild(style);
  }
  if (style.styleSheet) {
    style.styleSheet.cssText = css;
  } else {
    style.appendChild(document.createTextNode(css));
  }
}

var css_248z = ".footer-module_ul-footer__34LvJ{border-radius:0;min-height:50px;left:0;right:0;z-index:1030}.footer-module_ul-footer__34LvJ,.footer-module_ul-footer__34LvJ .navbar{margin-bottom:0}.footer-module_ul-footer__34LvJ>.ul-navbar{background-color:#fafafa!important;border-top-left-radius:0;border-top-right-radius:0;border-left:0;border-right:0;padding:15px 0}.footer-module_ul-footer__34LvJ>.ul-navbar .navbar-form{display:inline-block;margin:0!important}.footer-module_ul-footer__34LvJ>.ul-navbar .navbar-form:first-child{padding-left:0;padding-right:0}.footer-module_ul-footer__34LvJ>.ul-navbar .navbar-form>button{margin-left:2px;margin-right:2px}.footer-module_ul-footer__34LvJ>.ul-navbar .navbar-form>button:first-of-type{margin-left:0}.footer-module_ul-footer__34LvJ>.ul-navbar .navbar-form>button:last-of-type{margin-right:0}.footer-module_ul-footer__34LvJ>.ul-navbar .navbar-form>.dropdown,.footer-module_ul-footer__34LvJ>.ul-navbar .navbar-form>.dropup{margin-left:2px;margin-right:2px}.footer-module_ul-footer__34LvJ>.ul-navbar .navbar-form>.dropdown:first-of-type,.footer-module_ul-footer__34LvJ>.ul-navbar .navbar-form>.dropup:first-of-type{margin-left:0}";
var styles = {"ul-footer":"footer-module_ul-footer__34LvJ"};
styleInject(css_248z);
```
I don't know if `styleInject` is a helper from React, or specific to Rollup, I just know it's automatic. I know that bundles done with CRA (which, I think, uses Webpack) operate in the same fashion. Storybook does it just fine. I also know that putting my component/sass in a `codesandbox` gets compiled similarly as well.

My `.postcssrc` looks like:
```json
{
  "plugins": {
    "autoprefixer": true,
    "postcss-assets": true
  }
}
```
I did not use explicit "modules: true" here, as not all imports are CSS modules, and all modules are appended with '.module.[fileExt], which also didn't apply unique identifiers to the classes. When I *do* add "modules: true" I get the unique identifiers, but lose the ability to import non-modules when necessary.

Am I just doing something wrong? Some critical configuration I'm missing?

**Comment by mischnic** [comment]
This should work.

> When I run a build now it builds an external .css file and, looking at the bundle, that file is imported at the top of the file.

That sounds like Parcel is trying to build your project as a library and a webapp (could be caused by something like https://parceljs.org/getting-started/migration/#package.json%23main). Can you provide a reproduction?

**Comment by cutterbl** [comment]
This is a library of components. Part of the reasoning for component level CSS modules to begin with. Unfortunately it's a private repository on a private Git clone behind a firewall. I can try to spin up a quick example repo...

https://github.com/cutterbl/parcelexample

To be clearer: I am building several packages of components. Packages that represent modules of a larger application, or core shared components used within those modules. For instance, a select (in 'shared') is imported into 'health' (an application module) for use on a screen component. The 'shared' package is a production dependency in 'health'. The main (and very large) application has the 'health' package as a dependency, and imports the screen.

**Comment by devongovett** [comment]
When Parcel builds libraries, it expects that they will be consumed by another tool (e.g. published to npm and used in something like create-react-app, or another Parcel app). This is why CSS gets imported from JS - so that it can be consumed and combined with other libraries that are in that app.

If you are expecting the code to run directly in the browser without further build tooling, perhaps try compiling without library mode? https://parceljs.org/features/targets/#islibrary

**Comment by cutterbl** [comment]
@devongovett That assumes that a distributed 'library' might only be some form of utility. But there are many 'component' libraries (Bootstrap, Material, selects, calendars, etc) that one would want to publish and have consumed within an app. And most build processes would not recompile assets from node_modules, and expect those components to be built and run just as their core application code does. I would say that this use case, for CSS injection, is pretty commonplace, and even expected. But, maybe I just haven't found the proper mix of configuration for this scenario...

**Comment by Axxxx0n** [comment]
I am asking myself the same thing.
Maybe [bundle inlining](https://parceljs.org/features/bundle-inlining/) would help.
```javascript
// do this in library entry point
// inline css string in js bundle
import globalCss from 'bundle-text:./global.css';

// inject <style> tag
if(typeof window !== 'undefined') {
  let style = document.createElement('style');
  style.textContent = globalCss;
  document.head.appendChild(style);
}
```
It would be nice if we would have official way to do this. Something like `style-loader` from webpack.

**Comment by devongovett** [comment]
Actually, most build tools do support CSS imported within node_modules. One exception is Next.js, however, they are working on it: https://github.com/vercel/next.js/discussions/27953.

I think keeping separate CSS files rather than inlining CSS into a JavaScript string is much better because it allows the end user's build system to better optimize. Rather than each file being injected as a separate `<style>` element and bloating JS bundles, all of the CSS can be bundled together into a CSS file that is downloaded in parallel with the JS. That will avoid a potential flash of un-styled content.

If you do want/need to inline the css for some reason, you can do what @Axxxx0n suggested above. I don't think that should be the default though.
