### ISSUE TITLE
process.env.NODE_ENV doesn't work in production build

### ISSUE THREAD

**Issue by Sharklegs** [parcel-bundler/parcel#7320]
# 🐛 bug report
Environment Variables not be stripped in production builds and not be replace by its value

And how can i define like `process.env.BUILDTIME` that the value is the actual build time and use it in HTML or JS
```html
<!-- html -->
...
<script src="./index.js" nomodule></script>
```

```js
// index.js
if (process.env.NODE_ENV !== 'production') {
  console.log('Happy developing');
}
if (process.env.NODE_ENV === 'production') {
  console.log('Happy production');
}
```
``` bash
npm run build
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// package.json
{
  "browserslist": [
    "> 0.01%",
    "not dead",
    "not op_mini all"
  ],
  "scripts": {
    "build": "NODE_ENV=production parcel build --no-autoinstall",
  }
}
```

## 🤔 Expected Behavior

Only runs in development and will be stripped in production builds. 

## 😯 Current Behavior

``` js
"production"!==process.env.NODE_ENV&&console.log("Happy developing"),"production"===process.env.NODE_ENV&&console.log("Happy production");
```
dead code not be stripped  and  the process.env.XXX not be replace by real value like `true`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2.0.1
| Node             | 14.18.1
| npm/Yarn         | 6.14.15
| Operating System | macOs

**Comment by devongovett** [comment]
Environment variable replacement is not supported in non-module scripts (the `process` object is part of CommonJS). To fix this, add `type="module"` to your `<script>` element.
