### ISSUE TITLE
Can't create a new entry in a Transformer plugin

### ISSUE THREAD

**Issue by renanvaz** [parcel-bundler/parcel#7321]
# 🐛 bug report

I need to create a new entry file, cloning the original entry file, but with a new name. 
For this im trying to create a Transformer plugin.

## 🤔 Expected Behavior

My goal is to pass just one entry, example: `yarn parcel index.html`
But with the plugin, the goal is that the output is the same as what happens when we pass more than one entry, for example: `yarn parcel index.html index2.html` (the plugin would be responsible for generating the index2.html file virtually)

## 😯 Current Behavior

```
🚨 Build failed.

@parcel/namer-default: Bundle group cannot have more than one     
entry bundle of the same type

  AssertionError [ERR_ASSERTION]: Bundle group cannot have more   
  than one entry bundle of the same type
  at Object.name
  (PATH/node_modules/@parcel/namer-default/lib/DefaultNamer.js:82:29)
  at BundlerRunner.nameBundle
  (PATH/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:355:39)
  at
  PATH/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:331:50
  at Array.map (<anonymous>)
  at BundlerRunner.nameBundles
  (PATH/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:331:31)
  at processTicksAndRejections
  (node:internal/process/task_queues:96:5)
  at async BundlerRunner.bundle
  (PATH/node_modules/@parcel/core/lib/requests/BundleGraphRequest.js:286:5)
  at async RequestTracker.runRequest
  (PATH/node_modules/@parcel/core/lib/RequestTracker.js:721:20)     
  at async Object.run
  (PATH/node_modules/@parcel/core/lib/requests/ParcelBuildRequest.js:62:7)
  at async RequestTracker.runRequest
  (PATH/node_modules/@parcel/core/lib/RequestTracker.js:721:20)    
```

## 💻 Code Sample

I've tried many variations, but here's an example of simple plugin code:

```js
const { Transformer } = require('@parcel/plugin');

const plugin = new Transformer({
  transform({ asset }) {

    // Test to generate a new file as an Entry
    const assets = [{
        isEntry:        true,
        type:           'html',
        content:        'xxx',
        uniqueKey:      'index2.html',
        filePath:       'index2.html',
        bundleBehavior: 'isolated',
    }];

    return [asset, ...assets];
  },
});

module.exports = {
  plugin,
  default: plugin,
};
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | v16.13.0
| npm/Yarn         | 1.22.10
| Operating System | Ubuntu

**Comment by renanvaz** [comment]
Would someone know to explain to me the correct way to do this?

**Comment by mischnic** [comment]
I don't think this is possible from a transformer, and I can't think of a way to achieve this in general

**Comment by devongovett** [comment]
Could you give us a bit more detail on what you're trying to do? A more real-world use case would help. Thanks!

**Comment by renanvaz** [comment]
> Could you give us a bit more detail on what you're trying to do? A more real-world use case would help. Thanks!

Sure!

Where I work, we have a static website build flow, where we have an html template file, for example a product page, and our build generates all product pages/html based on this template.

I would like to be able to replicate this flow in the parcel 2, and I understood that the correct way would be to do it via transformer plugin.

In short, I would recognize that the entrypoint is a template file (eg identifying that the filename has a specific character that indicates a variable: products/`@slug`/index.html), and with it I would query a json, which would have the slugs of the products that need to be generated (eg ["product-1", "product-2"]). And at the end of the build, I need the system to generate the files `products/product-1/index.html` and `products/product-2/index.html`.

Thank you very much!

**Comment by renanvaz** [comment]
For that, I just needed to be able to create a new html file as a dependency of the entrypoint (which is also html), but that could keep the filename I defined (without the hash that is generated). Similar to what exists in the following example:
https://parceljs.org/plugin-system/transformer#returning-multiple-assets

**Comment by renanvaz** [comment]
Hi @mischnic and @devongovett , how are you?

With my explanation above, could you please tell me if there is any way I can get what I need to do in Parcel? Maybe what I need is just an example of how to create an HTML dependency (from an HTML entrypoint) so that the name I assign is kept.

Tks!
