### ISSUE TITLE
[bug] Syntax error in TypeScript type defination files

### ISSUE THREAD

**Issue by TechQuery** [parcel-bundler/parcel#7325]
### `package.json`

```json
{
    "source": "src/index.ts",
    "main": "dist/index.js",
    "module": "dist/index.esm.js",
    "types": "dist/index.d.ts",
    "dependencies": {
        "@swc/helpers": "^0.2.14",
        "web-utility": "^2.9.6"
    },
    "peerDependencies": {
        "katex": "^0.15.1",
        "react": ">=16",
        "react-bootstrap": "^1.6.4"
    },
    "devDependencies": {
        "@parcel/packager-ts": "^2.0.1",
        "@parcel/transformer-typescript-types": "^2.0.1",
        "@types/jest": "^27.0.2",
        "@types/katex": "^0.11.1",
        "@types/react": "^16.14.21",
        "husky": "^7.0.4",
        "jest": "^27.3.1",
        "katex": "^0.15.1",
        "lint-staged": "^12.0.3",
        "open-cli": "^7.0.1",
        "parcel": "^2.0.1",
        "prettier": "^2.4.1",
        "react": "^16.14.0",
        "react-bootstrap": "^1.6.4",
        "ts-jest": "^27.0.7",
        "typedoc": "^0.22.9",
        "typedoc-plugin-mdn-links": "^1.0.4",
        "typescript": "^4.5.2"
    },
    "browserslist": "> 0.5%, last 2 versions, not dead",
    "targets": {
        "main": {
            "optimize": false
        }
    }
}
```

### `tsconfig.json`

```json
{
    "compilerOptions": {
        "target": "ES5",
        "esModuleInterop": true,
        "jsx": "react",
        "lib": ["ES2021", "DOM"]
    },
    "include": ["src/**/*"]
}
```

## 🤔 Expected Behavior

Generate right **Type Defination** files for libraries, as what Parcel 2.0.0 did.

## 😯 Current Behavior

`dist/index.d.ts`

```typescript
import { PickData as  } from "web-utility";
import { PropsWithoutRef as , RefCallback as , PropsWithChildren as  } from "react";
import { type _PickData1 as  } from "web-utility/source/data";
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1 |
| TypeScript | 4.5.2 |
| Node             | 14.17.6 |
| Yarn         | 1.22.15 |
| Operating System | Windows 10 Pro 21H1 |

**Comment by TechQuery** [comment]
Parcel 2.0.0 + TypeScript 4.3.5 has no syntax error, but loses some `export` type defination:

```typescript
import XXX from './XXX';

export const doSomething = () => console.log(XXX);

export { default as XXX } from './XXX';
```
and same Type warnings appear:

![image](https://user-images.githubusercontent.com/19969570/142489674-e4195496-fc13-4ec7-a513-2702faa197ad.png)

**Comment by benqus** [comment]
I'm getting the same - sounds like this is a TypeScript issue then?

> Parcel 2.0.0 + TypeScript 4.3.5 has no syntax error, but loses some `export` type defination:
> 
> ```ts
> import XXX from './XXX';
> 
> export const doSomething = () => console.log(XXX);
> 
> export { default as XXX } from './XXX';
> ```
> 
> and same Type warnings appear:
> 
> ![image](https://user-images.githubusercontent.com/19969570/142489674-e4195496-fc13-4ec7-a513-2702faa197ad.png)

As per @TechQuery suggestions:
Reverted `typescript` from `^4.5.2` to `4.3.5` and using
```ts
export { MyModule } from './MyModule';
```

That worked!

**Comment by benpigchu** [comment]
I encountered a similar problem with Parcel 2.0.1 and Typescript 4.5.2. Parcel 2.0.1 and Typescript 4.4.4 works for me.

**Comment by benpigchu** [comment]
Typescript 4.5 added [`type` Modifiers on Import Names](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#type-modifiers-on-import-names). As a result, the API for ts.createImportSpecifier has changed, and therefore breaks the usage of the API in [transformers for typescript-types](https://github.com/parcel-bundler/parcel/blob/4f0d297b644bc7f6380fe39b11ad83576aac6eb2/packages/transformers/typescript-types/src/shake.js#L241)
