### ISSUE TITLE
Running Parcel installs modules in npm workspaces

### ISSUE THREAD

**Issue by jackwrighthellenic** [parcel-bundler/parcel#7331]
# 💬 RFC

When I run Parcel, it seems to install bundle dependencies into a given workspace's `package.json`. I use npm workspaces to organise my projects' imports. I would like to know if this is a new feature or if there is a config option I can add.

## 🔦 Context

This is a problem because node_modules folders are not pushed to the Git repository, but the package.json has been modified by Parcel during development. This means that when we run any build, the build fails because it cannot find, say, Sharp, which is now listed in `src/images/package.json` but is not installed.

I have only recently started having this problem.

## 💻 Examples

Below is an example of what the build server will now experience:

```
Server running at http://localhost:1234
× Build failed.

@parcel/package-manager: Could not find module "sharp", but it was listed in package.json. Run your
package manager first.

  C:\Users\JackWright\Version Control Projects\hellenic-master\frontend\src\images\package.json:5:5
    4 |   "devDependencies": {
  > 5 |     "sharp": "^0.29.3"
  >   |     ^^^^^^^ Defined here, but not installed
    6 |   }
    7 | }
```

**Comment by DeMoorJasper** [comment]
could you please provide a reproduction? sharp is a dependency of the image transformer so we shouldn't change your pkg.json in any way for that
