### ISSUE TITLE
Web extension - cannot import modules

### ISSUE THREAD

**Issue by avalanche1** [parcel-bundler/parcel#7333]
# 🐛 bug report

Parcel doesn't import any modules for the content-script of chrome extension.
On web page console I get this:
![image](https://user-images.githubusercontent.com/10534563/142666816-00084ec8-22b1-4884-9ccf-3ef93e216d30.png)

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`
```js
  "scripts": {
    "start": "parcel src/manifest.json --host localhost --target webext-dev",
  },
  "targets": {
    "webext-dev": {
      "sourceMap": {
        "inline": true,
        "inlineSources": true
      }
    },
    "webext-prod": {}
  },
```
`.parcelrc`
```js
{
  "extends": "@parcel/config-webextension",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
}
```
`.tsconfig`
```js
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "exactOptionalPropertyTypes": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "react",
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noPropertyAccessFromIndexSignature": true,
    "noUncheckedIndexedAccess": true,
    "resolveJsonModule": true,
    "strict": true,
    "suppressImplicitAnyIndexErrors": true,
    "target": "es2018",
    "typeRoots": ["node_modules/@types"],
    "types": ["jest", "expect-more-jest"]
  },
  "include": [
    "globals.d.ts",
    "src/assets/**/*",
    "src/**/*.ts",
    "src/**/*.tsx",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ]
}
```
`manifest.json` (partial)
```js
{
  "content_scripts": [
    {
      "matches": ["https://*.instagram.com/*"],
      "js": ["entry/content-script/cs.ts"],
      "css": ["entry/content-script/cs.css"]
    }
  ],
  }
}
```

## 🤔 Expected Behavior

On Parcel RC2 it worked fine.

## 😯 Current Behavior

I'm running Parcel `2.0.1` and the problem is here.

## 🔦 Context

Content script for web-extension.
The command I run for dev server is: "parcel src/manifest.json --host localhost --target webext-dev --lazy"
## 💻 Code Sample

`entry/content-script/cs.ts`
```js
import {sample} from "lodash-es";
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | 16.1.0
| npm/Yarn         |8.14.0
| Operating System | macOS

**Comment by e-krebs** [comment]
I have a working example in this repo: https://github.com/e-krebs/pile

The main difference I see are:
- relative path in `manifest.json`
- `module: "commonjs"` in `tsconfig.json`

**Comment by 101arrowz** [comment]
I really doubt `--lazy` works for web extensions, it works only for webpages AFAIK.

**Comment by avalanche1** [comment]
@101arrowz `lazy` does run, but adds all manner of unexpected behaviour when used in tandem with HMR.
Anyway, this is not an issue in `2.4.1`, so closing.
