### ISSUE TITLE
[v2.0.1] DOMException [DataCloneError]: Cannot transfer object of unsupported type.

### ISSUE THREAD

**Issue by HHogg** [parcel-bundler/parcel#7342]
# 🐛 bug report

After upgrading from 2.0.0 to 2.0.1, development and production builds are no longer working. 

## 😯 Current Behavior

```
DOMException [DataCloneError]: Cannot transfer object of unsupported type.
    at Worker.postMessage (internal/worker.js:340:23)
    at ThreadsWorker.send ([PATH]/node_modules/@parcel/workers/lib/threads/ThreadsWorker.js:74:17)
    at Worker.send ([PATH]/node_modules/@parcel/workers/lib/Worker.js:145:17)
    at Worker.call ([PATH]/node_modules/@parcel/workers/lib/Worker.js:165:12)
    at [PATH]/node_modules/@parcel/workers/lib/Worker.js:133:12
    at new Promise (<anonymous>)
    at Worker.sendSharedReference ([PATH]/node_modules/@parcel/workers/lib/Worker.js:132:12)
    at [PATH]/node_modules/@parcel/workers/lib/Worker.js:122:20
    at Array.map (<anonymous>)
    at Worker.fork ([PATH]/node_modules/@parcel/workers/lib/Worker.js:121:81)
```

## 💁 Possible Solution

Downgraded to v2.0.0

## 🔦 Context

This was an existing application, however I stripped everything right back to just a plain HTML file and it was still throwing the error on startup. I reinstalled all node_modules and cleared the .parcel-cache. The only thing that worked was downgrading to 2.0.0. 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.1
| Node             |v14.18.0
| Yarn         |1.22.15
| Operating System | OSX Big Sur 11.4 (M1)

**Comment by mischnic** [comment]
> This was an existing application, however I stripped everything right back to just a plain HTML file and it was still throwing the error on startup. I reinstalled all node_modules and cleared the .parcel-cache. The only thing that worked was downgrading to 2.0.0.

Can you share thihs minimal reproduction in a github repo or zip file?

**Comment by HHogg** [comment]
Thanks for the quick response @mischnic. I've just realised I also had `"@parcel/transformer-inline-string" installed, I upgraded this too and it fixed it for 2.0.1. I'll close this issue, however if it's possible a more helpful error might have helped point to my error here.

**Comment by mischnic** [comment]
So something like this?
```json
{
  "dependencies": {
    "@parcel/transformer-inline-string": "2.0.0",
    "parcel": "2.0.1"
  }
} 
```

I get this error:
```
@parcel/package-manager: Could not find module "@parcel/transformer-inline-string" satisfying ^2.0.1.

  package.json:3:5
    2 |   "dependencies": {
  > 3 |     "@parcel/transformer-inline-string": "2.0.0",
  >   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Found this conflicting local requirement.
    4 |     "parcel": "2.0.1"
    5 |   }

```

**Comment by HHogg** [comment]
Ah, apologies again. This in a yarn workspaces project, and another workspace had parcel@2.0.0 listed as a dependency so this might actually be a conflict with 2 parcel versions?
