### ISSUE TITLE
How do I specify the server dev path ?

### ISSUE THREAD

**Issue by zababurinsv** [parcel-bundler/parcel#7343]
### Discussed in https://github.com/parcel-bundler/parcel/discussions/7339

<div type='discussions-op-text'>

<sup>Originally posted by **zababurinsv** November 21, 2021</sup>
When i run dev server, this server run on on path 
```
http://localhost:1234
```
How can I indicate that the path would be 
```
http://localhost:1234/some-path
```

This is important to me because I use web worker and service worker

I can change path for all file in express server, but then run workers

```
   let url = new URL('./worker.mjs', import.meta.url)
``
Its path is calculated from the site root</div>

**Comment by devongovett** [comment]
Let's keep this in discussions please.

**Comment by prathibhaprevalentai** [comment]
what is the fix on the above issue ?
http://localhost:1234/some-path
