### ISSUE TITLE
Scope hoisting inline `typeof module`

### ISSUE THREAD

**Issue by wryk** [parcel-bundler/parcel#7347]
# 🐛 bug report

When upgrading a web application to parcel2 from parcel2-beta, scope hoisting broke  `typeof module !== undefined && module.require` by inlining `typeof module` expression, resulting to a runtime error when later executed in a browser.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
  "source": "index.html",
  "dependencies": {
    "parcel": "^2.0.1"
  }
}
```

```bash
npx parcel build
```

## 🤔 Expected Behavior

Should not inline `typeof module` expression as it's unexpected and a commonly used in runtime check

## 😯 Current Behavior

Scope hoisting inline `typeof module` expression to `"object"` string literal, resulting on browser with `typeof module !== undefined && module.require`  to a `Uncaught ReferenceError: module is not defined`.

## 💁 Possible Solution

Non optimal solution is to disable scope hoisting but if it's considered a bug it should be fixed.

## 💻 Code Sample

Code extracted from the migration MR (https://github.com/thomashoneyman/purescript-halogen-realworld/pull/100)

```js
if (typeof module !== "undefined" && module.require && !(typeof process !== "undefined" && process.versions["electron"])) {
	console.log('some platform specific code here')
}
```

Code given bellow is a minimal reproducible example I bundled with `parcel build` using various combination of production flags.

```js
// object literal
console.log(typeof {})

// object variable
const object = {}
console.log(typeof object)

// module variable
console.log(typeof module)
```

**Signifiant results**

|                 | Without scope hoisting | With scope hoisting |
|-----------------|------------------------|---------------------|
| typeof object   | typeof{}               | typeof{}            |
| typeof module   | typeof n               | "object"            |

**All results**

|                 | (no flags)    | --no-optimize                       | --no-scope-hoist | --no-optimize and --no-scope-hoist |
|-----------------|---------------|-------------------------------------|------------------|------------------------------------|
| typeof {}       | "object"      | "object"                            | "object"         | "object"                           |
| typeof object   | typeof{}      | typeof $e2fdc57efd9271d8$var$object | typeof{}         | typeof object                      |
| typeof module   | "object"      | "object"                            | typeof n         | typeof module                      |

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | 16.11.1
| npm              | 8.0.0
| Operating System | NixOS 21.05 (Okapi) x86_64

**Comment by mischnic** [comment]
Parcel emulates a CJS context and compiles it away so that the output works "everywhere". This is especially needed for consume browserify bundles (so that the first if branch is taken):

https://github.com/parcel-bundler/parcel/blob/3b3b13557dba9d1a403c86550915c6013dd78dfe/packages/core/integration-tests/test/integration/scope-hoisting/commonjs/browserify-compat/browserify-bundle.js#L36-L47
