### ISSUE TITLE
Non-deterministic builds

### ISSUE THREAD

**Issue by dioptre** [parcel-bundler/parcel#7349]
# 🐛 bug report

If I run `parcel serve` my app works.

When I run `parcel build`, I get a number of errors (in react) saying my React component is not valid (it's been substituted by an empty object).

<img width="1430" alt="Screen Shot 2021-11-22 at 22 55 10" src="https://user-images.githubusercontent.com/760216/142982167-4398dbbc-0789-4fa4-b206-47ded2d6f1e2.png">
<img width="1430" alt="Screen Shot 2021-11-22 at 22 54 55" src="https://user-images.githubusercontent.com/760216/142982172-67a755a7-7a7b-4935-b761-af478d369fdf.png">
<img width="1430" alt="Screen Shot 2021-11-22 at 22 54 37" src="https://user-images.githubusercontent.com/760216/142982174-15f3aafe-608d-4629-b471-861f628f3665.png">

##  🎛 Configuration (.babelrc, package.json, cli command)

parcelrc
```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    "react-svg:*.svg": ["@parcel/transformer-svg-react"]
  },
  "reporters":  ["...", "parcel-reporter-static-files-copy"]
}

```
build config
```js
"staging": {
      "engines": {
        "browsers": [
          "> 0.5%",
          "last 2 versions",
          "not dead"
        ]
      },
      "distDir": "dist/staging",
      "publicUrl": "/",
      "sourceMap": {
        "inline": true,
        "inlineSources": true,
        "sourceRoot": "."
      }
    },
```

running:
```PARCEL_WORKERS=0 NODE_OPTIONS=--max_old_space_size=64048 NODE_ENV=staging TARGET=Staging parcel build index.html --log-level info --no-cache --target staging```

## 🤔 Expected Behavior

App should produce a working minified build with inline sources.

## 😯 Current Behavior

Builds to completion, and when I run the app using `http-server-spa . ./index.html` it vomits a lot of errors, and page does not render.

## 💁 Possible Solution

Not sure how to debug this. Have a feeling during scope-hoisting/minification the process nukes the code.

## 🔦 Context

Can't build production.

## 💻 Code Sample

TBD

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | 17.1.0
| npm/Yarn         | yarn berry
| Operating System | macos

**Comment by devongovett** [comment]
Any way you could provide a code sample?

**Comment by dioptre** [comment]
It's going to be difficult for me to share the code, as its so large (>20M) and proprietary. Might try and work out a way to submit an empty project.

Going to add these things here in case someone else gets the same error.
- @parcel/reporter-sourcemap-visualiser produced invalid json and didn't work with https://sourcemap-visualiser.vercel.app/ 
- the build required more memory in a node setting. 

Tried a few more things now getting:
```
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 14
    <anonymous> index.jsx:192
react-dom.production.min.js:216:46
    React 5
    y scheduler.production.min.js:18
    React 9
    <anonymous> index.jsx:192
```

I'll try and mention you Devon after I get all my notes in.

**Comment by dioptre** [comment]
Ok I found its from using eval in a function. that was nested in a prototype defiinition.
