### ISSUE TITLE
Parcel - add svg sprite

### ISSUE THREAD

**Issue by Nikolasgrizli** [parcel-bundler/parcel#7353]
### Discussed in https://github.com/parcel-bundler/parcel/discussions/7317

<div type='discussions-op-text'>

<sup>Originally posted by **Nikolasgrizli** November 17, 2021</sup>
Hello, I'm trying Parcel as an alternative to webpack project builder and I like it, but there are one BUT that I still can't beat (here are links to starting builds - [build on Parcel](https://github.com/Nikolasgrizli/Starter-parcel) and [build on webpack](https://github.com/Nikolasgrizli/Starter-webpack5-/tree/onelang)):
In the assembly under the webpack, I used svg-sprite-loader to create svg sprites, which adds immediately after opening body svg with symbols like this:
<svg> <symbol ...> <symbol ...>
and I found plugin parcel-plugin-svg-sprite, judging by the description, should also work in a similar way, but it doesn't work for me.
I tried to configure the plugin both through the package.json and through a separate settings file, I also tried to run the project simply on html (I use a pug in the assembly), but unfortunately this did not work either ((
As a result, for now, I am inserting svg in the way described in the parcel documentation (I use a pug in the project):
```
svg
   use (href = "../../icons/facebook.svg")
```
but in this case, I only get an empty space, although when i click on the link in svg, the correct svg file opens((</div>

**Comment by mischnic** [comment]
If you have an svg file with listing all the symbols like this one

https://github.com/parcel-bundler/parcel/blob/8cabeae83ca838134a003a52be468328e15d19ed/packages/core/integration-tests/test/integration/pug/icons.svg#L3-L4

Then referencing them with the hash should work:
https://github.com/parcel-bundler/parcel/blob/8cabeae83ca838134a003a52be468328e15d19ed/packages/core/integration-tests/test/integration/pug/index.pug#L15-L16

**Comment by Nikolasgrizli** [comment]
@mischnic yes, thanks, I know - the sprite building works in the same way in my assembly on the webpack, it's just that the process is automated there, i.e. When the project is started, the plugin looks at the folder fed to it and processes all the svg found there into one file with symbols, which is then inserted into the resulting html. The point of this plugin is just to avoid building it manually)

**Comment by Nikolasgrizli** [comment]
The plugin developer for the first parcel made the build for the parcel v2, and I say thank you! Here is the plugin, tested it with html and pug, everything works! https://github.com/Epimodev/parcel-plugin-svg-sprite
