### ISSUE TITLE
CLI flags to disable HTML/CSS/JS minification individually

### ISSUE THREAD

**Issue by megaphonecolin** [parcel-bundler/parcel#7370]
# 🙋 feature request

Add independent CLI flags to disable HTML/CSS/JS minification individually. Example:
--no-optimize-html
--no-optimize-css
--no-optimize-js

The following question contains a workaround, but the workaround is error prone (see my comment for an explanation of why).
https://github.com/parcel-bundler/parcel/issues/2561

## 🔦 Context

1) Minification sometimes breaks applications in subtle, difficult-to-diagnose ways. Developers do not always have the time or expertise to determine the exact cause of a failure caused by minification, and, therefore, opt to disable minification completely to ensure their application works correctly. However, opting out of ALL minification is often overkill. If CSS or HTML minification causes an application to fail, a developer might want to opt out of the offending minification only, while retaining the benefits of all other minification.

2) Some developers prefer to keep their CSS or HTML source untouched  and human readable, while still minifying JavaScript.

**Comment by mischnic** [comment]
With parcel 2, you can do use this parcelrc to remove all default html optimizers
```json
{
	"extends": "@parcel/config-default",
	"optimizers": { "*.html": [] }
}
```

List of default optimizer plugins:

https://github.com/parcel-bundler/parcel/blob/b9426b83f86809143ff122bde3ee217fb64a8d78/packages/configs/default/index.json#L54-L61

**Comment by megaphonecolin** [comment]
Fantastic!! Just tested on our application (where HTML minification was causing failures). Works perfectly. Thanks for the lightning-quick response. This issue can be closed. I'll update my comment in question #2651 accordingly.

**Comment by hashimaziz1** [comment]
Thanks for this, Parcel's HTML minification was also causing noticeable bugs with my relatively small static site. Very worrying because I dread to think how much more damage would have been done if I'd been using it on a larger site.

**Comment by myklemykle** [comment]
I just tried this solution, to leave my index.html unchanged.  But it doesn't quite work.  

Html minification appears to be disabled in the file, but something else is still minimising the JS in the interior of <script> tags in the html file.  This prevents the JSON config section of my index.html from being legible or easily hand-edited.

**Comment by sekoyo** [comment]
I would prefer to just disable minification not "other optimizations"

**Comment by joebentaylor1995** [comment]
This doesnt work, my html output is still minified
