### ISSUE TITLE
Uncaught Error: Cannot find module 'react-refresh/runtime' when building for electron-renderer

### ISSUE THREAD

**Issue by maximilianschmitt** [parcel-bundler/parcel#7373]
I have a basic Electron app where I'm using Parcel to bundle the React-TypeScript-based frontend.

However, when launching the app, I get this error in the browser console:

```
Uncaught Error: Cannot find module 'react-refresh/runtime'
    at newRequire (index.870d9fbe.js:61)
    at newRequire (index.870d9fbe.js:45)
    at localRequire (index.870d9fbe.js:83)
    at Object.QBwKf (runtime-84cceff3fa1cd9d3.js:2)
    at newRequire (index.870d9fbe.js:71)
    at index.870d9fbe.js:120
    at index.870d9fbe.js:143
```

I didn't get this error when I was building for a normal environment (not Electron).

**Minimal example on GitHub:** https://github.com/maximilianschmitt/parcel-electron-issue

### package.json (excerpt)

```json
"targets": {
	"default": {
		"context": "electron-renderer"
	}
}
```

### .parcelrc

```json
{
  "extends": "@parcel/config-default",
}
```

## 💁 Possible Solution

- I've tried installing react-refresh as a dependency
- I've tried adding `@parcel/transformer-react-refresh-wrap` to `.parcelrc`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | 12.22.7
| Yarn         | 1.21.1
| react         | 17.0.2
| react-dom         | 17.0.2
| Operating System | macOS Monterey 12.1

## Reproducible Example

Minimal example on GitHub: https://github.com/maximilianschmitt/parcel-electron-issue

**Comment by GeorgeIvlev** [comment]
I have the same issue, seems like issue is related to wrong modules loaded in browser part, when you use `electron-renderer` context you will have next structure:

<img width="480" alt="Screenshot 2021-12-17 at 2 04 53 PM" src="https://user-images.githubusercontent.com/12997597/146544561-a4df1f71-4c66-4060-87e8-4d7ca185637a.png">


But if you change context to browser you will have the other structure:

<img width="320" alt="Screenshot 2021-12-17 at 2 03 59 PM" src="https://user-images.githubusercontent.com/12997597/146544866-93e1f30f-51e5-45f3-a981-271a16601ef3.png">

In second case it works fine without error because we have `transformer-react-refresh-wrap` module that includes `react-refresh` module. I also tried to use `transformer-react-refresh-wrap` in `.parcelrc` but no success.

**Comment by GeorgeIvlev** [comment]
@maximilianschmitt 
Seems like we are not using electron context right. If you target `electron-renderer` you should disable `contextIsolation` in main process like so:
```
webPreferences: {
   contextIsolation: false
}
```
This is related to security reasons in new versions of electron. When you use context isolation you should use preload script to write your frontend side code that uses node.js logic, with context isolation enabled electron will have two contexts for main process ( where you can write node.js side code ) and renderer context ( where you can only use browser code, but no access to node.js code ).
What you should do instead is change your target context in package.json to `browser` and use preload.js script to exchange data between render context and main context.

My package.json:
```
 "render": "dist/index.html",
 "main": ["dist/main.js", "dist/preload.js"],
 "scripts": {
  "dev:render": "parcel serve --target render",
  "dev:render:build": "parcel build --target render",
  "dev:backend": "parcel serve --target main",
  "dev:backend:build": "parcel build --target main"
 },
 "targets": {
  "render": {
		"source": "src/render/index.html",
		"context": "browser"
	},
  "main": {
   "source": ["src/backend/index.ts", "src/backend/preload.js"],
   "context": "electron-main"
  }
 },
```

preload.js file:
```
const { ipcRenderer, contextBridge } = require('electron');

contextBridge.exposeInMainWorld('electron', {
	notificationApi: {
		sendNotification(message) {
			ipcRenderer.send('notify', message);
		}
	}
})
```

then you can access `notificationApi` method in renderer process like that: `electron.notificationApi.sendNotification("hey")`


So when you use `electron-renderer` target on frontend side disable `contextIsolation`, if you use `browser` target on frontend side then you shoud enable `contextIsolation` and use `preload` script.

**Comment by maximilianschmitt** [comment]
Hi @GeorgeIvlev, thanks a lot for the detailed help! 💪 💪 💪 

I actually switched my project over to Vite and encountered the same problems there (it also didn't play nicely with Electron). I thereby also discovered the preload-script. I'm still on Vite atm but it's really good to know that Parcel seems to work for you when using the preload-script. I'd like to switch back to Parcel when I find the time. :)
