### ISSUE TITLE
Error when executing `npx parcel src/index.html`

### ISSUE THREAD

**Issue by MystPi** [parcel-bundler/parcel#7377]
When I execute the command `npx parcel src/index.html`, I get this error:

```
Error: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found
```

I'm on Debian 10, if that helps.

Any solutions would be appreciated!

**Comment by mischnic** [comment]
Duplicate of https://github.com/parcel-bundler/parcel/issues/6735
