### ISSUE TITLE
Web extension build not working with _locales, trying to process ".DS_Store"

### ISSUE THREAD

**Issue by bingqiao** [parcel-bundler/parcel#7385]
Parcel version: 2.0.1
@parcel/config-webextension: 2.0.1
Node: v16.13.0
OS: macOS Monterey

Run the following to build web extension:
`parcel build src/manifest.json --target webext-prod`

Error:

> > parcel build src/manifest.json --target webext-prod
> 
> 🚨 Build failed.
> 
> @parcel/core: Failed to resolve '_locales/.DS_Store/messages.json' from './src/manifest.json'
> 
> @parcel/resolver-default: Cannot load file './_locales/.DS_Store/messages.json' in './src'.
> 💡 Did you mean '_./_locales/de/messages.json_'?
> 💡 Did you mean '_./_locales/fr/messages.json_'?
> 

The workaround is to use "--no-cache".
`parcel build src/manifest.json --target webext-prod --no-cache`

I also had to delete "_locales/.DS_Store", otherwise a similar error happens.

**Comment by 101arrowz** [comment]
Should be fixed by #7050.
