### ISSUE TITLE
Cannot read property 'spec' of undefined 

### ISSUE THREAD

**Issue by orangeyyy** [parcel-bundler/parcel#739]
is this a 🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)
```json
//.babelrc
{
  "presets": [[
    "@babel/preset-env", {
      "modules": false
    }],
    "@babel/preset-stage-0"
  ]
}
```
```json
//package.json
{
  "name": "parcel-demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "parcel src/index.js",
    "parcel": "parcel build src/index.js -d parcel-build --no-minify",
    "babel": "babel src -d babel-build"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/cli": "^7.0.0-beta.39",
    "@babel/core": "^7.0.0-beta.39",
    "@babel/preset-env": "^7.0.0-beta.39",
    "@babel/preset-stage-0": "^7.0.0-beta.39",
    "less": "^2.7.3",
    "parcel-bundler": "^1.5.1"
  }
}
```

### 🤔 Expected Behavior
bundle the src/index.js and output in parcel-build folder

### 😯 Current Behavior
whatever I put some code in src/index.js, I got a error show below:
![image](https://user-images.githubusercontent.com/19667299/35775763-22e81248-09ca-11e8-907a-d46d8f7884e4.png)

### 💁 Possible Solution
when i remove the .babelrc or just leave an empty json object in .babelrc , it works fine.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.5.1
| Node             |8.9.4
| npm/Yarn         |5.6.0
| Operating System |Mac OS 10.13.2

**Comment by orangeyyy** [comment]
I know the reason, parcel is use babel 6.x now, and the error is  thrown by babel-cli because I use 7.x config. so when would parcel update the babel version?

**Comment by devongovett** [comment]
Babel 7 is currently in beta. We will update once a stable version is released.
