### ISSUE TITLE
Import asterik files and then exporting does not work

### ISSUE THREAD

**Issue by MartinDawson** [parcel-bundler/parcel#7391]
# 🐛 bug report
Asterik import exports are not being added to the export in the compiled dist.

```js
import Spreadsheet from './spreadsheet'
import * as functionHelperHtmlElementHelpers from './spreadsheet/functionHelper/functionHelperHtmlElementHelpers'
```

```js
export {
  Speadsheet,
  functionHelperHtmlElementHelpers
}
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "source": "src/index.ts",
  "exports": "./dist/index.modern.js",
  "main": "./dist/index.js",
  "module": "./dist/index.module.js",
  "types": "dist/index.d.ts",
  "scripts": {
    "build": "parcel build",
  },
  "devDependencies": {
    "parcel": "^2.0.1",
  },
}

```

## 🤔 Expected Behavior
```js
export {$7625d8864a76ee12$export$ba43bf67f3d48107 as functionHelperHtmlElementHelpers, $1d2a4b9bb8769dc2$export$2e2bcd8739ae039 as Spreadsheet};
```

## 😯 Current Behavior

```js
export {$1d2a4b9bb8769dc2$export$2e2bcd8739ae039 as Spreadsheet};
```

## Workaround

```js
import {
  functionHelperPrefix,
  createMainHeader,
  createHeader,
  createSubHeader,
  createCodeText,
  createParagraph,
  createSyntaxListItem
} from './spreadsheet/functionHelper/functionHelperHtmlElementHelpers'

const functionHelperHtmlElementHelpers = {
  functionHelperPrefix,
  createMainHeader,
  createHeader,
  createSubHeader,
  createCodeText,
  createParagraph,
  createSyntaxListItem
}

export {
  functionHelperHtmlElementHelpers
}
```

Missing the export for the asterik imported module.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.1
| Node             | 14.18.1
| npm/Yarn         | 1.22.15
| Operating System | Ubuntu 19.x

**Comment by acton-bell** [comment]
I'm seeing the same, cjs build looks good but wildcard import + re-exports are missing.

Reproduction with build outputs here:
https://github.com/acton-bell/parcel-esm-wildcard-import-issue

Specifically:
https://github.com/acton-bell/parcel-esm-wildcard-import-issue/blob/main/dist/module.js

**Comment by acton-bell** [comment]
Update the repro for Parcel 2.3.0, seeing the same:
https://github.com/acton-bell/parcel-esm-wildcard-import-issue

**Comment by acton-bell** [comment]
Seeing a similar problem with the built-in type generation, will create a new issue to track.

**Comment by acton-bell** [comment]
Another observation, this pattern works (foo symbol appears in esmodule output):

```js
import * as foo from "./a";
export const foo = foo;
```

This one doesn't (foo symbol missing from output):

```js
import * as foo from "./a";
export { foo };
```

**Comment by acton-bell** [comment]
Updated repro for Parcel 2.4.1:
https://github.com/acton-bell/parcel-esm-wildcard-import-issue
