### ISSUE TITLE
--no-cache still uses .parcel-cache

### ISSUE THREAD

**Issue by Sleepful** [parcel-bundler/parcel#7398]
# 🐛 bug report

option doesn't work

## 🎛 Configuration (package.json)

```js
  "main": "server/server.js",
  "targets": {
    "main": false
  },
```

## 🤔 Expected Behavior

`--no-cache` and it still caches

## 😯 Current Behavior

creates cache directory

## 💻 Code Sample

```
$ rm -rf .parcel-cache
$ yarn parcel build --no-scope-hoist --dist-dir dist/public/browser/ --no-cache src/ui/index.tsx
$ ls -a | grep ca
.parcel-cache
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0
| Node             | 14.x
| npm/Yarn         | 2...
| Operating System | OSX

**Comment by devongovett** [comment]
https://parceljs.org/features/development/#caching

> Note that this only disables reading from the cache – a .parcel-cache folder will still be created.
