### ISSUE TITLE
Parcel 2 scope hoisting breaks server-side rendering styles

### ISSUE THREAD

**Issue by vladinator1000** [parcel-bundler/parcel#7404]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "scripts": {
    "start": "yarn build && node dist/server/index.js",
    "build": "yarn parcel build --no-optimize"
  },
  "targets": {
    "client": {
      "source": "client/index.html",
      "engines": {
        "browsers": "> 0.5%, last 2 versions, not dead"
      }
    },
    "server": {
      "source": "server/index.js",
      "context": "node"
    }
  },
}
```

## 🤔 Expected Behavior
Should be able to conditionally import styles.

## 😯 Current Behavior

Parcel transforms code like this
```js
const isBrowser = typeof window !== 'undefined' &&
  typeof window.document !== 'undefined'

// This code needs to work in the browser and Node
if (isBrowser) {
  import('normalize.css')
}
```

into this
```js
var $abz4F$normalizecss = require("normalize.css");

const $84cfad4eff4197ad$var$isBrowser = typeof window !== 'undefined' && typeof window.document !== 'undefined';

if ($84cfad4eff4197ad$var$isBrowser) $abz4F$normalizecss;
```

When you `yarn parcel build` and run this in node with `node dist/server/index.js`, you get this error
```
/home/vlady/code/parcel2-ssr/node_modules/normalize.css/normalize.css:11
html {
     ^

SyntaxError: Unexpected token '{'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/vlady/code/parcel2-ssr/dist/server/index.js:5:27)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
error Command failed with exit code 1.
```

The Parcel docs say to [avoid conditional imports](https://parceljs.org/features/scope-hoisting/#avoid-conditional-require()) but it's not clear how you'd do server rendering otherwise. How would you solve this?

## 💁 Possible Solution

Figure out how to do conditional imports? Or maybe we could write a server-side recipe for the docs that has better practices than my example?

## 🔦 Context

I'm trying to do server-side rendering with React where I'm conditionally loading css styles for some components. 

## 💻 Code Sample
https://github.com/vladinator1000/parcel2-ssr

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2
| Node             | 17
| npm/Yarn         | 1.17
| Operating System | Ubuntu

**Comment by devongovett** [comment]
Looks like the import is being treated as an external, and then compiled to CommonJS.

One thing you could do would be to use `process.browser` instead of looking for a window object. This will be replaced statically, so the entire if statement should get removed.

```js
if (process.browser) {
  import('normalize.css');
}
```
