### ISSUE TITLE
🐛 bug report: parcel does not load existing sourcemaps of pre-transformed JS assets

### ISSUE THREAD

**Issue by lxe** [parcel-bundler/parcel#741]
This is a 🐛 bug report 

General summary:

Importing/requiring a pre-built file does not load its sourcemaps. 

For example, `mapbox-gl-js` exports a pre-packaged `main` which lives in `node_modules/mapbox-gl/dist/mapbox-gl.js`. It also contains a `sourceMappingUrl` `//# sourceMappingURL=mapbox-gl.js.map`.  There is a `mapbox-gl.js.map` in `dist/` as well.

When doing `import mapboxgl from 'mapbox-gl'` , parcel correctly bundles node_modules/mapbox-gl/dist/mapbox-gl.js, but does not load and re-process its sourcemap.

I haven't gotten far with debugging it, but it seems that that file does not satisfy any of the conditions that would mark it for transformation (https://github.com/parcel-bundler/parcel/blob/master/src/transforms/babel.js#L29).

Artificially marking it for a transform (by hardcoding something like `if (/mapbox-gl\.js/.test(asset.name)) return true` will run the babel compiler on it, which is also not what we want. 

To reproduce:

```
yarn add mapbox-gl
```

Inspect the entrypoint:

```
❯ jq .main node_modules/mapbox-gl/package.json
"dist/mapbox-gl.js"
```

Inspect the presence of the entrypoint and the map:
```
❯ ls node_modules/mapbox-gl/dist/
mapbox-gl-dev.js mapbox-gl.css    mapbox-gl.js     mapbox-gl.js.map svg
```

Looks like we're pointing to the sourcemap correctly:

```
❯ ag "sourceMapping"  node_modules/mapbox-gl/dist/mapbox-gl.js
566://# sourceMappingURL=mapbox-gl.js.map
```

Import the file, and package it with parcel:

```
// index.js
import mapbox from 'mapbox-gl`

// index.html
<html><body><script src="./index.js"></script></body></html>
```

```
❯ parcel index.html
Server running at http://localhost:64815
✨  Built in 1.88s.
```

Verify that the sourcemap of mapbox-gl.js does not get repackaged:

![](https://i.imgur.com/QpvTOb8.png)

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.5.1
| Node             | v8.9.3
| npm/Yarn         |  1.3.2
| Operating System | Darwin

**Comment by lxe** [comment]
Basically we need something  like https://github.com/webpack-contrib/source-map-loader

**Comment by Mickyfen17** [comment]
I've just come across this same issue today when trying to use mapbox-gl & parcel together.

**Comment by devongovett** [comment]
This seems easy enough to do. We already have the infrastructure in place, just need to parse the existing source map url comment in the code and load it.

**Comment by Offirmo** [comment]
Tried parcel, was delighted, then put a "debugger" statement...

Please fix this!

**Comment by snstrauss** [comment]
I agree.
Using a 'debugger;' statement causes the debug session to pause at random places across the code.

What can I do about it?

**Comment by lxe** [comment]
What does `debugger;` have to do with this issue? @Offirmo @snstrauss Did you mean to comment elsewhere?

**Comment by Offirmo** [comment]
@lxe think about it...

**Comment by iFwu** [comment]
any updates？

**Comment by medmin** [comment]
any updates ?

**Comment by Bug-Reaper** [comment]
Any insight into how to debug issues where parcel fails to load existing sourcemaps. Similar problem with this npm module: https://github.com/mfbx9da4/deep-email-validator

**Comment by Lemraus** [comment]
I am willing to re-open this issue as I have come across this problem earlier today, and after taking a look at  #1349 I understood where the problem is. #1349 did not entirely solve this issue, below is an explanation as to why.

From the source code of #1349, in file `src/assets/JSAsset.js`, line 26:
```js
const SOURCEMAP_RE = /\/\/\s*[@#]\s*sourceMappingURL\s*=\s*([^\s]+)/;
```
Then later, line 114:
```js
let match = this.contents.match(SOURCEMAP_RE);
```
This would work fine if all `sourceMappingURL` statements started with `//`, but guess what? It is not the case.
I have recently started to work with neovis.js, a client visualization tool for Neo4j databases, now take a look at their minified `neovis.js` file, line 95, column 21247:
```js
o&&btoa&&(i+="\n/*# sourceMappingURL=data:application/json;base64,".concat(btoa(unescape(encodeURIComponent(JSON.stringify(o))))," */"))
```
Uh-oh, looks like folks at neovis.js felt like using multiline comments (`/* */`) instead of the usual `//` for `sourceMappingURL`.
I started thinking that it might be a neovis.js related issue, however it turns out things work fine with webpack.

Should I file a merge request to change the regexp accordingly?

**Comment by jzohrab** [comment]
Hi all, I'm running into this now (parcel version 1.12.5), with a js library called Vexflow.  It has the same commenting style noted above:

```
o&&btoa&&(n+="\n/*# sourceMappingURL=data:application/json;base64,".concat(btoa(unescape(encodeURIComponent(JSON.stringify(o))))," */"))
```

@Lemraus I'm happy to create and submit this PR with your suggested regex above, but I don't see an obvious v1 branch or tag to work off of.  @devongovett - any suggestions?  Thanks!

---

edit: actually, it might be trickier than I expected.  My `node_modules/parcel-bundler/src/utils/loadSourceMap.js` already had `const SOURCEMAP_RE = /(?:\/\*|\/\/)\s*[@#]\s*sourceMappingURL\s*=\s*([^\s*]+)(?:\s*\*\/)?/;`, so I added the error details to the try/catch:

```
    } catch (e) {
      logger.warn(
        `Could not load existing sourcemap of "${asset.relativeName}, error = ${e}".`
      );
```

and got `Could not load existing sourcemap of "../node_modules/vextab/dist/div.prod.js, error = SyntaxError: Unexpected token r in JSON at position 0".`

Earlier in the code, it's doing

```
      if (dataURLMatch) {
        filename = asset.name;
        logger.warn(`a. making buffer from ${dataURLMatch[1]}`)   // <-- added
        json = Buffer.from(dataURLMatch[1], 'base64').toString();
```

which is outputting

```
a. making buffer from ".concat(btoa(unescape(encodeURIComponent(JSON.stringify(o)))),"
```

So the regex may be off, at least for this particular case.
