### ISSUE TITLE
Parcel 2.0.1  Building TS library failed

### ISSUE THREAD

**Issue by christopanayotovvia** [parcel-bundler/parcel#7411]
# 🐛 bug report

Following https://parceljs.org/getting-started/library/ to building TS library with types. Simple TS file in src/index.ts. and following package.json config ( see below ). Parcel 2.0.1, Node v16.13.0 , NPM 8.1.0 

## 🎛 Configuration (.babelrc, package.json, cli command)

```ts
// src/index.ts
export function add(a: number, b: number) {
  return a + b;
}

```

```json
// package.json
{
  "name": "test-library",
  "version": "1.0.0",
  "source": "src/index.ts",
  "main": "dist/main.js",
  "module": "dist/module.js",
  "types": "dist/types.d.ts",
  "scripts": {
    "watch": "parcel watch",
    "build": "parcel build"
  },
  "devDependencies": {
    "@parcel/transformer-typescript-types": "^2.0.1",
    "parcel": "^2.0.1"
  }
}

```

## 🤔 Expected Behavior

Build proper `dist/main.js`, `dist/module.js` and `dist/types.d.ts` files

## 😯 Current Behavior

Cleans package.json and installs @parcel/transformer-typescript-types as dev dependency. When reverting the package.json file and manually add @parcel/transformer-typescript-types v 2.0.1, it fails with the following error:

> parcel build

🚨 Build failed.

Error: Could not resolve module "wrap-ansi" from "/Users/USER/Desktop/PROJECT_FOLDER/node_modules/@parcel/reporter-cli/lib/CLIReporter.js"

Installing  `wrap-ansi` as dependency or dev dependency does not fix the isse. 

## 🔦 Context

Currently parcel v 2.0.1 cannot be used to build / distribute library

## 💻 Code Sample

```json
{
  "name": "test-library",
  "version": "1.0.0",
  "source": "src/index.ts",
  "main": "dist/main.js",
  "module": "dist/module.js",
  "types": "dist/types.d.ts",
  "scripts": {
    "watch": "parcel watch",
    "build": "parcel build"
  },
  "devDependencies": {
    "@parcel/transformer-typescript-types": "^2.0.1",
    "parcel": "^2.0.1"
  }
}
```

And literally any file in `src/index.ts`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | v16.13.0
| npm/Yarn         | 8.1.0
| Operating System | OS X

**Comment by fattslug** [comment]
Similar issue, but with the built-in `fs` module.

```
$ parcel build
🚨 Build failed.

@parcel/core: Failed to resolve 'fs' from './utils/visualizer/generate/src/generator.ts'

  /Users/spowell9/Development/tokens/utils/visualizer/generate/src/generator.ts:1:16
  > 1 | import fs from 'fs';
  >   |                ^^^^
    2 | 
    3 | import config from '../../config.json';

@parcel/resolver-default: External dependency "fs" is not declared in package.json.

  /Users/spowell9/Development/tokens/utils/visualizer/generate/package.json:1:1
  > 1 | {
  >   | ^
    2 |   "name": "@design-tokens/visualizer-assemble",
    3 |   "version": "10.45.3",
```

**Comment by fattslug** [comment]
Similar issue, but with the built-in `fs` module.

```
$ parcel build
🚨 Build failed.

@parcel/core: Failed to resolve 'fs' from './PROJECT/src/generator.ts'

  /Users/USER/Development/PROJECT/src/generator.ts:1:16
  > 1 | import fs from 'fs';
  >   |                ^^^^
    2 | 
    3 | import config from '../../config.json';

@parcel/resolver-default: External dependency "fs" is not declared in package.json.

  /Users/USER/Development/PROJECT/package.json:1:1
  > 1 | {
  >   | ^
    2 |   "name": "visualizer-assemble",
    3 |   "version": "10.45.3",
```

**Comment by astegmaier** [comment]
I can't repro this with the exact same parcel/node/npm/OS. @christopanayotovvia - can you provide a github repo where you get a consistent repro?

**Comment by mischnic** [comment]
Will be fixed in the next release: https://github.com/parcel-bundler/parcel/pull/7348
