### ISSUE TITLE
Image transformer ignores pug sources query parameters

### ISSUE THREAD

**Issue by pierredarrieutort** [parcel-bundler/parcel#7422]
# 🐛 Bug report

1. Start a new project with following `package.json`, and install dependencies.
2. Place aside at root a .jpg file and a index.pug file with following content :
   ```pug
    doctype html
    html
      body

        //- picture
        //-   <source srcset="image.jpg?as=webp&width=50 50w" type="image/webp">
        //-   img(srcset='image.jpg?width=50')

        picture
          source( srcset='image.jpg?as=webp&width=50 50w' type='image/webp')
          img(srcset='image.jpg?width=50')
   ```
   _The **commented** part contains a `source` tag writed in HTML.
    The **uncommented** part is fully writed in pug._

3. Just build your project with `npm run build`.
____

#### Pug source : _(webp : 69.29 KB)_
![image](https://user-images.githubusercontent.com/25182438/145358718-1f73e9b6-c6ee-45cb-9906-76b6a8a13f62.png)
#### HTML source : _(webp : 29.41 KB)_
![image](https://user-images.githubusercontent.com/25182438/145358774-d479b24a-79b1-4709-a621-429c2221d9c7.png)

**Observation :** When we use the pug `source` tag, the image isn't resized instead of using HTML `source` tag.
____

## 🎛 Configuration _(package.json)_

```json
{
  "scripts": {
    "start": "parcel index.pug",
    "build": "parcel build index.pug"
  },
  "dependencies": {
    "parcel": "^2.0.1"
  },
  "devDependencies": {
    "@parcel/transformer-pug": "^2.0.1",
    "sharp": "^0.29.3"
  }
}

```

## 🤔 Expected Behavior

When using a Pug `source` tag with query `?as=webp&width=50`, the image must be resized.

## 😯 Current Behavior

When we use a Pug `source` the image isn't resized.
No error message.

## 💁 Possible Solution

👻No idea, it's seems to be from Parcel side at compilation.

## 🔦 Context

I'm trying to get a resized version of a picture with differents formats such as webp.

## 💻 Full minimal reproducible repository 🚀
[parcel-pug-source-no-resize.zip](https://github.com/parcel-bundler/parcel/files/7683374/parcel-pug-source-no-resize.zip)

## 🌍 My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | 14.5.0
| npm         | 7.21.1
| Operating System | Windows 10

**Comment by Shinyaigeek** [comment]
this does not look like percel’s issue. `pug` compiler escapes some special characters automatically such as `&`. Parcel compile `.pug` into `.html` with `pug` compiler, this problem probably happened because `&` was escaped to `&amp;` at that compile time.

You can check this behavior easilly with pug playground https://pughtml.com/.

```diff
- source( srcset='image.jpg?as=webp&width=50 50w' type='image/webp’)
+ source( srcset!='image.jpg?as=webp&width=50 50w' type='image/webp’)
```

maybe, if you fix your `.pug` such above, image transformer will correctly work.

FYI: https://pugjs.org/language/attributes.html#unescaped-attributes

**Comment by Shinyaigeek** [comment]
However when I look at it again, it feels a bit confusing. Maybe some improvement should be done with parcel as well.

**Comment by mischnic** [comment]
This isn't really a problem specific to Parcel. There are other reasons outside of Parcel/these build-time params where you want to load an image from a server with some query params.

And we try to avoid customizing language so it doesn't derail from "standard Pug" to "ParcelPug".

**Comment by Shinyaigeek** [comment]
> And we try to avoid customizing language so it doesn't derail from "standard Pug" to "Parcel Pug".

I think this policy is correct.

When I commented, I meant that parcel could be possible to output warning message about escaped `&` for more kindfull developer experience.
However, if a developer look at the html output by parcel, a developer can notice `&` is escaped, so I changed my mind as if it was unnecessary

**Comment by christianhaller** [comment]
> this does not look like percel’s issue. `pug` compiler escapes some special characters automatically such as `&`. Parcel compile `.pug` into `.html` with `pug` compiler, this problem probably happened because `&` was escaped to `&amp;` at that compile time.
> 
> You can check this behavior easilly with pug playground https://pughtml.com/.
> 
> ```diff
> - source( srcset='image.jpg?as=webp&width=50 50w' type='image/webp’)
> + source( srcset!='image.jpg?as=webp&width=50 50w' type='image/webp’)
> ```
> 
> maybe, if you fix your `.pug` such above, image transformer will correctly work.
> 
> FYI: https://pugjs.org/language/attributes.html#unescaped-attributes

thank you very much @Shinyaigeek  ❤️
