### ISSUE TITLE
Common dependencies are implicitly written only to the dist folder of the first target

### ISSUE THREAD

**Issue by w0rm** [parcel-bundler/parcel#7436]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

Given the following project structure (where both `index.js` import the common script.js)

```
src/common/script.js
src/target1/index.html
src/target1/index.js
src/target2/index.html
src/target2/index.js
```

And the following package.json 

```json
{
  "name": "parcel-test",
  "private": true,
  "scripts": { "build": "parcel build" },
  "dependencies": { "parcel": "^2.0.1" },
  "targets": {
    "target1": { "source": "src/target1/index.html" },
    "target2": { "source": "src/target2/index.html" }
  },
  "@parcel/bundler-default": {
    "minBundles": 1,
    "minBundleSize": 1
  }
}
```

## 🤔 Expected Behavior

Running `parcel build` should produce self contained builds for both targets, or let me control where the common dependencies are being written to.

I expect the result `dist/target1` and `dist/target2` to contain all the necessary files for each target, so that they could be deployed in insolation.

## 😯 Current Behavior

The following is happening instead, the common dependencies are written only to the dist folder of the first target:

```
ls dist/target1 
index.1dd3ea00.js     index.1dd3ea00.js.map index.21a42281.js     index.21a42281.js.map index.html

ls dist/target2
index.d63e3149.js     index.d63e3149.js.map index.html
```

The second target doesn't have the `index.21a42281.js` file, even though its `index.html` requires it.

```
cat dist/target2/index.html 
<html><head><title>Target 2</title><script type="module" src="/index.21a42281.js"></script><script type="module" src="/index.d63e3149.js"></script></head><body></body></html>
```

## 🔦 Context

I am trying to use parcel in monorepo setup where each target corresponds to an individual app. I need to package and deploy each app and all its resources separately.

### common/script.js

```js
export function logToBody(text) {
  const entry = document.createElement('p'); entry.innerText = text; document.body.appendChild(entry);
}
```

### target1/index.html

```html
<html>
<head>
  <title>Target 1</title>
  <script type="module" src="./index.js"></script>
</head>
<body></body>
</html>
```

### target1/index.js

```
import { logToBody } from "../common/script";
logToBody("Hello from target 1");
```

### target2/index.html

```html
<html>
<head>
  <title>Target 2</title>
  <script type="module" src="./index.js"></script>
</head>
<body></body>
</html>
```

### target2/index.js

```
import { logToBody } from "../common/script";
logToBody("Hello from target 2");
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.1 |
| Node             | v14.17.0 |
| Yarn         | 1.22.10 |
| Operating System | macOS 11.6.1  |

**Comment by w0rm** [comment]
up

**Comment by mischnic** [comment]
Should be fixed now with the new bundler (https://parceljs.org/blog/v2-8-0/#new-bundling-algorithm). At least your example now works correctly
