### ISSUE TITLE
2.0.0-nightly.942 consumes 30GB of memory and crashes while building

### ISSUE THREAD

**Issue by folknor** [parcel-bundler/parcel#7441]
# 🐛 bug report

Here's the output from my pnpm update command:
```
- @parcel/optimizer-cssnano 2.0.0-nightly.942
+ @parcel/optimizer-cssnano 2.0.0-nightly.944 (2.0.1 is available)
- @parcel/optimizer-htmlnano 2.0.0-nightly.942
+ @parcel/optimizer-htmlnano 2.0.0-nightly.944 (2.0.1 is available)
- @parcel/packager-css 2.0.0-nightly.942
+ @parcel/packager-css 2.0.0-nightly.944 (2.0.1 is available)
- @parcel/packager-html 2.0.0-nightly.942
+ @parcel/packager-html 2.0.0-nightly.944 (2.0.1 is available)
- @parcel/packager-raw-url 2.0.2-nightly.2564
+ @parcel/packager-raw-url 2.0.2-nightly.2566
- @parcel/transformer-css 2.0.0-nightly.942
+ @parcel/transformer-css 2.0.0-nightly.944 (2.0.1 is available)
- @parcel/transformer-html 2.0.0-nightly.942
+ @parcel/transformer-html 2.0.0-nightly.944 (2.0.1 is available)
- @parcel/transformer-image 2.0.2-nightly.2564
+ @parcel/transformer-image 2.0.2-nightly.2566
- @parcel/transformer-js 2.0.0-nightly.942
+ @parcel/transformer-js 2.0.0-nightly.944 (2.0.1 is available)
- @parcel/transformer-postcss 2.0.0-nightly.942
+ @parcel/transformer-postcss 2.0.0-nightly.944 (2.0.1 is available)
- @parcel/transformer-posthtml 2.0.0-nightly.942
+ @parcel/transformer-posthtml 2.0.0-nightly.944 (2.0.1 is available)
- @parcel/transformer-sass 2.0.0-nightly.942
+ @parcel/transformer-sass 2.0.0-nightly.944 (2.0.1 is available)
- @parcel/transformer-webmanifest 2.0.2-nightly.2564
+ @parcel/transformer-webmanifest 2.0.2-nightly.2566
- parcel 2.0.0-nightly.940
+ parcel 2.0.0-nightly.942 (2.0.1 is available)
```

Before this update (that is, yesterday, using `parcel 2.0.0-nightly.940`) the build worked fine.

Now, it eats all my memory and then dies:
```
⠋ Building getCompositeRect.js...
WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(20em, 16) or calc(20em / 16)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
12 │ $fa-fw-width:          (20em / 16);
   │                         ^^^^^^^^^
   ╵
    node_modules/@fortawesome/fontawesome-free/scss/_variables.scss 12:25  @import
    sass/main.scss 12:9                                                    root stylesheet

@parcel/workers: Worker terminated due to reaching memory limit: JS heap out of memory

  Error [ERR_WORKER_OUT_OF_MEMORY]: Worker terminated due to reaching memory limit: JS heap out of memory
  at new NodeError (node:internal/errors:371:5)
  at Worker.[kOnExit] (node:internal/worker:276:26)
  at Worker.<computed>.onexit (node:internal/worker:198:20)

⠴ Building getAltAxis.js...
WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(20em, 16) or calc(20em / 16)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
12 │ $fa-fw-width:          (20em / 16);
   │                         ^^^^^^^^^
   ╵
    node_modules/@fortawesome/fontawesome-free/scss/_variables.scss 12:25  @import
    sass/main.scss 12:9                                                    root stylesheet
⠋ Building getAltAxis.js...
 ELIFECYCLE  Command failed with exit code 130.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

It dies in different places each time. This time in the log above it was `getAltAxis.js`. I've tried 5 times, different file each time.

I've tried:
- NODE_ENV production and development, no change
- Removing the only inline style attribute I had in my HTML, which was a `style="display: none;"` (because of https://github.com/parcel-bundler/parcel/commit/e3c89acd6c245a71e98e72e71c87f9cc7b6e621a), but made no difference
- Commenting out every JS import and related code, in chunks to try to narrow it down, but even when commenting out _all_ my JS it still doesn't work
- Commenting out `@import "../node_modules/bootstrap/scss/bootstrap.scss";` in my SCSS file prevents the build breaking
- Commenting out ALL my custom CSS and the inline display:none so that literally `@import "../node_modules/bootstrap/scss/bootstrap.scss";` is the only thing left in the SCSS, the build is still broken
- I've tried all --log-levels and I can't see anything relevant in any of them

I use bootstrap in all my projects, and the others build just fine even with build 942.

Please advise how to proceed. I realise you'd want a reduced test case, which I'm willing to do, but you might have an "aha!" moment and provide me with a fix or path to debug that is quicker, so I'm writing this before I make a reduced test.

**Comment by folknor** [comment]
I use `latest` (or equivalent) for all dependencies, so https://github.com/twbs/bootstrap/releases/tag/v5.1.3
But again, all my other sites use bootstrap as well and their builds work fine.

**Comment by mischnic** [comment]
The difference between the two versions is https://github.com/parcel-bundler/parcel/compare/b27515ec..8ee562ae


> Commenting out ALL my custom CSS and the inline display:none so that literally @import "../node_modules/bootstrap/scss/bootstrap.scss"; is the only thing left in the SCSS, the build is still broken

I just tried that and it builds fine for me.
So please share a reproduction, but it sounds like you're almost there already

**Comment by folknor** [comment]
Alright so in the process of reducing it down I reduced the SCSS to this:
```scss
@import "../node_modules/bootstrap/scss/functions";
@import "../node_modules/bootstrap/scss/variables";
@import "../node_modules/bootstrap/scss/mixins";
@import "../node_modules/bootstrap/scss/utilities";

@import "../node_modules/bootstrap/scss/progress";
```
And that makes it break. Specifically, https://github.com/twbs/bootstrap/blob/main/scss/_progress.scss

However, if I then comment out 50% of _progress, then run `parcel build`, it works fine. I then switch and comment out the other 50% of the file and build again, and it works fine. If I then uncomment the whole file and build, it also works. If I then delete `.parcel-cache`, it hangs again.

I'll keep at it.

**Comment by folknor** [comment]
I don't use any of the classes in that file in my HTML, and the build hangs even if my HTML file only has an empty body tag.

**Comment by folknor** [comment]
Having a file called `.postcssrc.json` in the project folder with this contents makes the build hang:
```json
{
	"plugins": {
		"postcss-preset-env": true
	}
}

```

**Comment by folknor** [comment]
[test.zip](https://github.com/parcel-bundler/parcel/files/7706704/test.zip)

1. Unzip to an empty project folder
2. cd in
3. `pnpm up`
4. `pnpm run build`

Hangs for me using pnpm 6.23.6.
EDIT: zip file accidentally included pnpm lock file. Updated.

**Comment by mischnic** [comment]
This appears to be a bug in postcss-preset-env:

In your project, create a file `in.css` with this content
```css
.progress-bar-striped {
  background-image: linear-gradient(
    45deg,
    rgba(255, 255, 255, 0.15) 25%,
    transparent 25%,
    transparent 50%,
    rgba(255, 255, 255, 0.15) 50%,
    rgba(255, 255, 255, 0.15) 75%,
    transparent 75%,
    transparent
  );
}
```
then install the `postcss-cli` package and run `postcss x.css`. That also has an infinite loop and would probably crash at some point.

<img width="413" alt="Bildschirmfoto 2021-12-13 um 22 28 43" src="https://user-images.githubusercontent.com/4586894/145891751-4980105b-ebfc-4063-9529-c6d559d72443.png">


https://github.com/csstools/postcss-preset-env/issues/233

**Comment by folknor** [comment]
Thanks a lot. And thank you for opening the bug upstream, I was on my way to do it when I noticed :-D
