### ISSUE TITLE
Image resizing not working on production environment

### ISSUE THREAD

**Issue by Chrissle28** [parcel-bundler/parcel#7463]
# 🐛 bug report

Hello everybody, I'm currently testing parcel for a small static one pager and I'm trying to use the responsive resizing the image transformer offers. However even if it works when I locally work with my parcel project , as soon as I deploy it from github via netlify there is just one static image loaded on my website and it doesn't use the responsive loading of images.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
    "name": "parcel-test",
    "version": "1.0.0",
    "description": "",
    "source": "src/index.html",
    "scripts": {
        "watch": "npx parcel src/index.html",
        "production": "parcel build src/index.html"
    },
    "author": "",
    "license": "ISC",
    "devDependencies": {
        "autoprefixer": "^10.4.0",
        "parcel": "^2.0.1",
        "postcss": "^8.4.1",
        "postcss-import": "^14.0.2",
        "sharp": "^0.29.3",
        "tailwindcss": "^3.0.3"
    }
}
```

## 🤔 Expected Behavior

The image should be loaded responsively according to current breakpoint set in the image element.

## 😯 Current Behavior

Only one version of the image is being loaded no matter the breakpoint

## 💁 Possible Solution

I can't really tell what a solution could be since I rarely work with static sites on netlify.

## 🔦 Context

I'm just testing Parcel because I want to build a static website for a friend of mine and Parcel seems to be a nice tool for that with no unnecessary overhead.

## 💻 Code Sample

```html
            <picture>
                <source
                    srcset="
                        ./assets/ocean.jpg?as=webp&width=400   400w,
                        ./assets/ocean.jpg?as=webp&width=800   800w,
                        ./assets/ocean.jpg?as=webp&width=1000 1000w
                    "
                    sizes="(max-width: 767px) 200px, (max-width: 1023px) 400px, (max-width: 1279px) 800px, (max-width: 5000px) 1000px"
                    type="image/webp"
                />
                <img
                    src="./assets/ocean.jpg"
                    class="w-full mb-20"
                    alt="Ocean"
                />
            </picture>
```

You can also take a look into my [test repo](https://github.com/Chrissle28/parcel-concept), clone it and check the problem for yourself if that helps.

## 🌍 Your Environment

The following describe my local environment but as described I'm only getting this problem when I deploy my project to netlify or other static services.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | 16.13.0
| npm/Yarn         | 7.5.4
| Operating System | macOS Monterey 12.1

**Comment by folknor** [comment]
Your test case works perfectly for me. I dropped it in one of my dozens of static sites I build with parcel that uses bootstrap 5.x, changed the image path, and tested using Firefox' Responsive design mode.

**Comment by mischnic** [comment]
Parcel correctly detected and generated files with these dimensions:
```html
                <source srcset="/ocean.6cd7d57b.webp   400w,/ocean.f5f84556.webp   800w,/ocean.38733ee2.webp 1000w" sizes="(max-width: 767px) 200px, (max-width: 1023px) 400px, (max-width: 1279px) 800px, (max-width: 5000px) 1000px" type="image/webp">
```

```
$ identify dist/ocean.*
dist/ocean.19a9847f.jpg JPEG 2399x1343 2399x1343+0+0 8-bit sRGB 619121B 0.000u 0:00.000
dist/ocean.38733ee2.webp WEBP 1000x560 1000x560+0+0 8-bit sRGB 24800B 0.010u 0:00.010
dist/ocean.6cd7d57b.webp WEBP 400x224 400x224+0+0 8-bit sRGB 6732B 0.010u 0:00.001
dist/ocean.f5f84556.webp WEBP 800x448 800x448+0+0 8-bit sRGB 17408B 0.000u 0:00.006
```
