### ISSUE TITLE
Cannot find Parcel plugin "@parcel/transformer-sass"

### ISSUE THREAD

**Issue by dwhenson** [parcel-bundler/parcel#7467]
# 🐛 bug report

On production build at Netlify and Vercal I get the following error: Cannot find module "@parcel/transformer-sass", did you mean "@parcel/transformer-css"?

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "author": "Dave Henson",
  "description": "FEM Challenge - Todo App",
  "version": "1.0.0",
  "keywords": [],
  "name": "todo-app",
  "source": "src/index.html",
  "scripts": {
    "start": "parcel",
    "build": "parcel build"
  },
  "license": "ISC",
  "devDependencies": {
    "eslint": "^8.4.1",
    "eslint-config-healthier": "^3.2.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-html": "^6.2.0",
    "eslint-plugin-unicorn": "^39.0.0",
    "healthier": "^4.0.0",
    "parcel": "2.0.1",
    "prettier": "2.5",
    "sass": "^1.45.0",
    "stylelint": "^14.1.0",
    "stylelint-order": "^5.0.0",
    "stylelint-scss": "^4.0.1"
  },
}
```

## 🤔 Expected Behavior

I expected the site to build and be deployed

## 😯 Current Behavior

Build fails with following error:

```
@parcel/core: Cannot find Parcel plugin "@parcel/transformer-sass"
--
11:15:03.484 | /vercel/path0/node_modules/@parcel/config-default/index.json:25:23
11:15:03.485 | 24 \|     "*.{styl,stylus}": ["@parcel/transformer-stylus"],
11:15:03.485 | > 25 \|     "*.{sass,scss}": ["@parcel/transformer-sass"],
11:15:03.485 | >    \|                       ^^^^^^^^^^^^^^^^^^^^^^^^^^ Cannot find module "@parcel/transformer-sass", did you mean "@parcel/transformer-css"?
11:15:03.485 | 26 \|     "*.less": ["@parcel/transformer-less"],
11:15:03.485 | 27 \|     "*.{css,pcss}": ["@parcel/transformer-postcss", "@parcel/transforme
```

## 💁 Possible Solution

Adding and installing this package fixed the issue:

```
 "dependencies": {
    "@parcel/transformer-sass": "^2.0.1"
  }
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | 17.0.1
| npm        | 8.1.0
| Operating System | OSx 12.0.1

**Comment by Shinyaigeek** [comment]
This issue seems to be related to #7097.
I feel that the behavior of autoImport `parcelDependencies` on vercel (and Nelify) CI is strange :thinking:

I think you can fix this bug via installing` @parcel/transformer-sass` to your local project and push it into vercel (or Netlify). (and if my understanding is correct, `@parcel/transformer-sass` is installed to your local project when you run `parcel build` on your local machine). However, this is just a workaround.

**Comment by mischnic** [comment]
Indeed a duplicate. 

With your package.json, the first thing that happens when I run `npm run build` is `@parcel/transformer-sass` being installed. Can you share a complete reproduction?

**Comment by nsadeh** [comment]
I have the same bug with transform-webmanifest
