### ISSUE TITLE
`@parcel/optimizer-terser` can't recognize a syntax which is supported in the latest version of terser

### ISSUE THREAD

**Issue by SukkaW** [parcel-bundler/parcel#7468]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

Not applicable.

## 🤔 Expected Behavior

Code should build.

## 😯 Current Behavior

```
@parcel/optimizer-terser: Unexpected token operator «?», expected punc «(»

  > 1966 |      */ function object?(value) {
  >      |                       ^ Unexpected token operator «?», expected punc «(»
    1967 |                             if (typeof value !== "object") throw new TypeError("Expected an object or null.");
    1968 |                         }

It's likely that Terser doesn't support this syntax yet.
```

## 💁 Possible Solution

You tell me. Terser 5.10.0 with default configuration doesn't have such an issue, only `@parcel/optimizer-terser` has. 

However, **it is more likely caused by the parcel's transformation during bundling**, as `@parcel/optimizer-terser` simply feeds the code to the `terser` directly.

## 💻 Code Sample

```js
// write or paste code here
class Sukka {
    static "object?"(value) {
        if (typeof value !== "object") {
            throw new TypeError("Expected an object or null.");
        }
    }
}

Sukka['object?']({});
```

Terser (and swc, and esbuild, and babel) can minify it into (checked using terser's REPL & swc's playground):

```js
(class{static"object?"(e){if("object"!=typeof e)throw new TypeError("Expected an object or null.")}})["object?"]({});
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | 17.3.0
| npm/Yarn         | 8.1.3
| Operating System | macOS 12.1.0

**Comment by danieltroger** [comment]
Do you know how the language feature is called? It seems interesting

**Comment by SukkaW** [comment]
> Do you know how the language feature is called? It seems interesting

@danieltroger It just exists.

See https://github.com/humanwhocodes/object-schema/blob/98308bc9bf05e491df18b192e614d7ba02d50a68/src/validation-strategy.js#L70 and https://github.com/humanwhocodes/object-schema/blob/98308bc9bf05e491df18b192e614d7ba02d50a68/src/validation-strategy.js#L94

See also https://tc39.es/ecma262/multipage/syntax-directed-operations.html#sec-static-semantics-propname

**Comment by mischnic** [comment]
@SukkaW I took your code sample and it works fine for me when building with `parcel build index.js`.

**Comment by SukkaW** [comment]
@mischnic Sorry, I forgot to add context to the original issue.

I was trying to bundle a browser version of eslint into a web application. I use the webpack to `browserify` the eslint because it has `node-polyfill-webpack-plugin` which supports a wider node built-in API than parcel's, and I feed the webpack emitted output to the parcel.

So here is a full repro:

```bash
git clone -b parcel-issue-7468 https://github.com/SukkaW/monsterbation-linter parcel-issue-7468
cd parcel-issue-7468
npm i
npm run build-eslint
npm run build
```

**Comment by mischnic** [comment]
So this is an swc bug, see the linked issue.

>  I use the webpack to browserify the eslint because it has node-polyfill-webpack-plugin which supports a wider node built-in API than parcel's, and I feed the webpack emitted output to the parcel.

Which packages does building eslint require that are missing from the Parcel polyfill list? As far as I can tell, the only difference are the various `_stream_*` packages?

**Comment by SukkaW** [comment]
> Which packages do building eslint require that are missing from the Parcel polyfill list? As far as I can tell, the only differences are the various `_stream_*` packages?

I will open another issue for that.
