### ISSUE TITLE
Babel config is not been picked up

### ISSUE THREAD

**Issue by huozhi** [parcel-bundler/parcel#7474]
# 🐛 bug report

Testing with styled-jsx, the babelrc file isn't been picked up

Issue report on styled-jsx side: https://github.com/vercel/styled-jsx/issues/767

## 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc
```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    "styled-jsx/babel"
  ]
}
```

## 🤔 Expected Behavior

styled-jsx is transformed with babel plugin

## 😯 Current Behavior

`<style jsx>` tags are not been transformed, the plugin isn't been called

## 💻 Code Sample

Reproduction: https://github.com/lCaveh/parcel2

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1 |
| Node             | 14.17.0 |
| Yarn         | 1.22.15 |
| Operating System | macOS |

**Comment by mischnic** [comment]
This happened because the Babel transformer was explicitly disabled/overwritten here:
```
    "*.{js,mjs,jsx,cjs,ts,tsx}": [
      "@parcel/transformer-js",
      "@parcel/transformer-react-refresh-wrap"
    ]
```

the default value is
https://github.com/parcel-bundler/parcel/blob/8823770717bf451da2667b4d0d24b8915698856d/packages/configs/default/index.json#L11-L15
