### ISSUE TITLE
🐛Build never finishes

### ISSUE THREAD

**Issue by tatsujb** [parcel-bundler/parcel#748]
### 🎛 Configuration (.babelrc, package.json, cli command)

angular-cli + parcel. mimicking this setup : https://github.com/tienne/angular-parcel

terminal:
`parcel build ./src/index.html -d /distribution --no-cache --no-minify`

package.json : 
```
{
  "name": "web.ui",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "parcel": "parcel",
    "start": "parcel ./src/index.html --no-cache",
    "build": "parcel build ./src/index.html -d /distribution --no-cache --no-minify"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@angularclass/hmr": "^2.1.3",
    "@angularclass/hmr-loader": "^3.0.4",
    "core-js": "^2.4.1",
    "parcel-plugin-inlinesvg": "0.0.12",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.6.6",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "eslint": "4.16.0",
    "eslint-config-prettier": "2.9.0",
    "eslint-plugin-prettier": "2.6.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "parcel-bundler": "^1.2.0",
    "parcel-plugin-eslint": "^1.0.3",
    "parcel-plugin-typescript": "0.2.0-angular.0",
    "postcss-modules": "^1.1.0",
    "prettier": "1.10.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}

```

### 🤔 Expected Behavior

build runs then finishes.

### 😯 Current Behavior

build runs but the process never finishes:
![image](https://user-images.githubusercontent.com/5132359/35813077-f7010d28-0a92-11e8-862a-5c552e805b66.png)

tested in GitBash, Powershell, CMD

this is severely hampering for integrating Parcel to a deployment process such as maven or jenkins.

the process needs to have a beginning and an end.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.5.1
| Node             | 8.9.4
| npm/Yarn         | 5.6.0
| Operating System | windows 10 pro 64bit

**Comment by fathyb** [comment]
This isn't a Parcel bug, it was a known bug of `parcel-plugin-typescript@0.2.0-angular.0` (which is very old and literally the first experimental release of the Angular support, not suited for prod at all), this has been fixed since.

I'm closing this, please continue the discussion on the Angular plugin issue tracker if needed.
