### ISSUE TITLE
Scope hoisting less effective since rewrite

### ISSUE THREAD

**Issue by 101arrowz** [parcel-bundler/parcel#7481]
# 🐛 bug report

Scope hoisting is dramatically less effective since #6230. This seems to be because `#__PURE__` annotations don't work properly anymore.

## 🎛 Configuration (.babelrc, package.json, cli command)

I'm testing with zero configuration. Here's `package.json`:
```json
{
  "name": "fflt",
  "version": "1.0.0",
  "license": "MIT",
  "devDependencies": {
    "parcel": "2.0.0-nightly.655"
  },
  "dependencies": {
    "fflate": "^0.7.2"
  }
}
```

## 🤔 Expected Behavior

The scope hoisting rewrite should not adversely affect scope hoisting for any case.

## 😯 Current Behavior

Scope hoisting is dramatically less effective in every version since ba57b6501632703d68923b214b0c0f6d47a34b1f (#6230).

## 💁 Possible Solution

The behavior is similar to what happens when you remove all [`#__PURE__` annotations](https://terser.org/docs/api-reference#annotations) from `fflate`. Maybe all comments are now being stripped before terser processes the code?

## 🔦 Context

Without the ability to utilize `/*#__PURE__*/` comments, every function call is considered a side effect, which makes it impossible to tree-shake out IIFEs and variables used in exported closures that are initialized to the result of a function call.

## 💻 Code Sample

Here's my `index.html`:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script type="module" src="./index.js"></script>
</body>
</html>
```
Here's `index.js`:
```js
import { gzipSync, strToU8 } from 'fflate';

console.log(gzipSync(strToU8('hello world')));
```

To build, I use `parcel build index.html`. When using `parcel@2.0.0-nightly.654` (`gitHead` = fdbcbd6996fe3e91014af0e5c18e8ae6ae282a04):
![6.78kB JS file](https://user-images.githubusercontent.com/29579245/147372512-c7d17a66-7447-4051-81d4-5d966b2cad3f.PNG)

Running the same command using `parcel@2.0.0-nightly.655` (`gitHead` = ba57b6501632703d68923b214b0c0f6d47a34b1f):
![21.79kB JS file](https://user-images.githubusercontent.com/29579245/147372585-9ecaf26a-82f6-4d3a-b935-dc9b9556ef7d.PNG)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | Any version since `2.0.0-nightly.655`
| Node             | v16.6.2
| npm/Yarn         | Yarn 1.22.15
| Operating System | Ubuntu 20.04 on WSL

**Comment by mischnic** [comment]
I have identified one problem where pure comments of IIFE are stripped during the build:

```js
// index.js
import { strToU8 } from './other.js';
console.log((strToU8('hello world')));


// other.js
var u32 = Uint32Array;
var flm = /*#__PURE__*/ hMap(flt, 9, 0);
var deo = /*#__PURE__*/ new u32([
    65540, 131080, 131088
]);
export function strToU8(a) {
    return "converted";
}
var Unzip = /*#__PURE__*/ (function () {
    console.log("UNUSED")
}());
export { Unzip };
```

results in 

```js
(() => {
var $da3800f92a93f12a$var$u32 = Uint32Array;
var $da3800f92a93f12a$var$flm = /*#__PURE__*/ hMap(flt, 9, 0);
var $da3800f92a93f12a$var$deo = /*#__PURE__*/ new $da3800f92a93f12a$var$u32([
    65540,
    131080,
    131088
]);
function $da3800f92a93f12a$export$366b39a6daa8ed7a(a) {
    return "converted";
}
var $da3800f92a93f12a$export$9b7485f84cbaaa56 = function() { // <-------  !!!
    console.log("UNUSED");
}();


console.log($da3800f92a93f12a$export$366b39a6daa8ed7a('hello world'));

})();
//# sourceMappingURL=index.js.map
```

See the linked swc issue, we'll see if there are more problems once that particular one is fixed.

**Comment by 101arrowz** [comment]
Thanks for researching the problem! For future reference, how did you get the bundled but pre-`terser` code?

**Comment by mischnic** [comment]
`parcel build ... --no-optimize`

**Comment by mischnic** [comment]
If I comment that `expr_simplifier` pass out, the output is 6.78 KB which seems to be what you were expecting.

**Comment by 101arrowz** [comment]
Since https://github.com/swc-project/swc/issues/3115 has been resolved if you add `paren_remover`, this should be fixable now in Parcel? Or is `paren_remover` on by default?

**Comment by mischnic** [comment]
swc needs to be bumped and that pass has be added
