### ISSUE TITLE
Build crashes with "@parcel/transformer-js: not implemented: add_effects for tagged template literal"

### ISSUE THREAD

**Issue by wmain** [parcel-bundler/parcel#7485]
# 🐛 bug report

Attempting to migrate from Parcel 1 to Parcel 2. Parcel 2 panics during build that worked in Parcel 1. Project is a Typescript project. Switching from SWC to TSC does not fix the bug.

## 🎛 Configuration (.babelrc, package.json, cli command)

No babel configuration.

tsconfig.json:
```
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "jsx": "react",
    "lib": ["es2021", "DOM", "WebWorker"],
    "module": "esnext",
    "moduleResolution": "node",
    "noErrorTruncation": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "es2021"
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "tests/**/*.ts",
    "tests/**/*.tsx",
    "src/types/global.d.ts"
  ],
  "exclude": []
}
```

## 🤔 Expected Behavior

No error should be thrown during build.

## 😯 Current Behavior

 Build thread panics:
```
thread '<unnamed>' panicked at 'not implemented: add_effects for tagged template literal', /Users/runner/.cargo/regist`
``` 
Parcel later reports the error as: 
```
🚨 Build failed.

@parcel/transformer-js: not implemented: add_effects for tagged template literal
```

## 💁 Possible Solution

Not a solution, but looking at the [source of where the error originates](https://rustdoc.swc.rs/src/swc_ecma_utils/lib.rs.html#1952) my best guess would be that using a ternary within a `styled-components` tagged template literal is causing this. Update: I tried building one file with a ternary within a tagged template literal and didn't receive an error.

## 🔦 Context

This bug is preventing a migration from parcel 1 to parcel 2.

## 💻 Code Sample

N/A

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | 14.16.0
| npm/Yarn         | npm 6.14.11
| Operating System | macOS Monterey 12.1

**Comment by mischnic** [comment]
Please provide a reproduction. Sounded like you had identified the lines that caused the error already?

**Comment by wmain** [comment]
I haven't figured out a reproduction yet. Building one of the suspected files directly with `parcel build File.tsx` as the entry rather than `parcel build index.html` doesn't reproduce. Is there any way I can get a better sense of which file is being processed when the error occurs?

**Comment by mischnic** [comment]
Maybe using `PARCEL_WORKERS=0 parcel build ... --log-level verbose`, but because of promises the logged filenames might still not correspond to the actual order
