### ISSUE TITLE
Generated Types are Broken

### ISSUE THREAD

**Issue by jvanderen1** [parcel-bundler/parcel#7488]
# 🐛 bug report

Using the new fix from https://github.com/parcel-bundler/parcel/pull/7424, I would have thought the types issue would have resolved my issue in https://github.com/parcel-bundler/parcel/issues/6815. However, the types generated result in broken import statements:

### types.d.ts

```ts
import { ReactNode as , ComponentType as  } from "react";
interface ContainerProviderProps<State = void> {
    initialState?: State;
    children: ReactNode;
}
interface Container<V, S = void> {
    Provider: ComponentType<ContainerProviderProps<S>>;
    useContext: () => V;
}
interface ContainerOptions {
    displayName?: string;
}
type UseHook<V, S> = (initialState?: S) => V;
export function createContainer<V, S = void>(useHook: UseHook<V, S>, options?: ContainerOptions): Container<V, S>;

//# sourceMappingURL=types.d.ts.map
```

As shown, the line `import { ReactNode as , ComponentType as  } from "react";` has incomplete syntax (missing identifiers).

### package.json

```
{
  "name": "@jvanderen1/unstated-next",
  "version": "1.0.0",
  "description": "Up-to-date version of everyone's favorite state management library unstated-next",
  "types": "dist/types.d.ts",
  "keywords": [
    "unstated",
    "react",
    "hooks",
    "context",
    "state",
    "react-hooks"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/jvanderen1/unstated-next"
  },
  "license": "MIT",
  "author": "<livetoscout@gmail.com>",
  "sideEffects": false,
  "main": "dist/unstated-next.cjs.js",
  "module": "dist/unstated-next.esm.js",
  "source": "src/index.ts",
  "browser": "dist/unstated-next.umd.js",
  "scripts": {
    "build": "parcel build",
    "clean": "npm run clean:dist && npm run clean:types && npm run clean:node-modules",
    "clean:dist": "rimraf dist/",
    "clean:node-modules": "rimraf node_modules/",
    "clean:types": "tsc --build --clean",
    "clean-install": "npm run clean && npm install",
    "dev": "parcel example/index.html",
    "lint": "eslint \"**/*.{ts,tsx}\"",
    "lint:fix": "npm run lint -- --fix",
    "prepare": "husky install",
    "pretty": "prettier --check \"**/*.{ts,tsx}\"",
    "pretty:fix": "prettier --write \"**/*.{ts,tsx}\"",
    "test": "",
    "types-check": "tsc --skipLibCheck --noEmit"
  },
  "devDependencies": {
    "@parcel/packager-ts": "^2.0.0-nightly.954",
    "@parcel/transformer-typescript-types": "^2.0.0-nightly.954",
    "@swc/cli": "^0.1.55",
    "@swc/core": "^1.2.123",
    "@types/node": "^17.0.5",
    "@types/react": "latest",
    "@types/react-dom": "latest",
    "@typescript-eslint/eslint-plugin": "^5.8.0",
    "@typescript-eslint/parser": "^5.8.0",
    "eslint": "^8.5.0",
    "eslint-plugin-react": "^7.28.0",
    "eslint-plugin-react-hooks": "^4.3.0",
    "husky": "^7.0.4",
    "lint-staged": "^12.1.4",
    "parcel": "^2.0.0-nightly.952",
    "prettier": "^2.5.1",
    "prop-types": "latest",
    "react": "latest",
    "react-dom": "latest",
    "ts-node": "^10.4.0",
    "typescript": "^4.5.4"
  },
  "peerDependencies": {
    "prop-types": ">= 15.5.0",
    "react": ">= 16.8.0"
  },
  "volta": {
    "node": "16.13.1"
  }
}
```

### .swcrc

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true,
      "tsx": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "target": "es2020",
    "loose": true
  },
  "module": {
    "noInterop": false,
    "type": "commonjs",
    "strict": true,
    "strictMode": true,
    "lazy": true
  },
  "sourceMaps": true
}
```

## 🤔 Expected Behavior

I expect types to be generated correctly.

## 😯 Current Behavior

Types are not generated correctly.

![Temp](https://user-images.githubusercontent.com/22926257/147420219-ddd54657-5bde-4608-821c-bbfec1c1024b.png)

## 💁 Possible Solution

Most likely will involve more fixes to `TSModuleGraph.js`

## 🔦 Context

I'd like to generate types for downstream users of @jvanderen1/unstated-next.

## 💻 Code Sample

Github repository: https://github.com/jvanderen1/unstated-next

## 🌍 Your Environment

Note: These nightly builds do still contain an error originally demonstrated in https://github.com/parcel-bundler/parcel/issues/6815. To resolve, follow the following: https://github.com/parcel-bundler/parcel/issues/6815#issuecomment-1001241288

| Software         | Version(s) |
| ---------------- | ---------- |
| parcel           |  ^2.0.0-nightly.952
| @parcel/packager-ts | ^2.0.0-nightly.954
| @parcel/transformer-typescript-types | ^2.0.0-nightly.954
| Node             | 16.13.1
| npm/Yarn         | 8.1.2
| Operating System | Windows 11

**Comment by mischnic** [comment]
This was already fixed by https://github.com/parcel-bundler/parcel/pull/7426

But I think you didn't install that change.

**Comment by jvanderen1** [comment]
What versions of nightly need to be installed?

**Comment by mischnic** [comment]
I cloned your repo at https://github.com/jvanderen1/unstated-next/commit/c93492902505b7b3a0fcfb0603b454a8f9d79c1e and used Yarn instead of npm to workaround https://github.com/parcel-bundler/parcel/pull/7489.
Then it worked just fined

**Comment by jvanderen1** [comment]
Thank you very much! I love how awesome the dev's have been 💯

**Comment by selfagency** [comment]
@mischnic I just tried installing the nightlies and I'm still running into the bad type compilation issue.

```json
  "devDependencies": {
    "@babel/core": "^7.16.7",
    "@babel/preset-env": "^7.16.7",
    "@babel/preset-typescript": "^7.16.7",
    "@parcel/babel-preset-env": "^2.0.0-nightly.961",
    "@parcel/config-default": "^2.0.0-nightly.961",
    "@parcel/core": "^2.0.0-nightly.961",
    "@parcel/packager-ts": "^2.0.0-nightly.961",
    "@parcel/transformer-typescript-types": "^2.0.0-nightly.961",
    "@parcel/validator-typescript": "^2.0.0-nightly.961",
    "@types/jest": "^27.4.0",
    "@types/node": "^17.0.5",
    "@typescript-eslint/eslint-plugin": "^5.8.1",
    "@typescript-eslint/parser": "^5.8.1",
    "eslint": "^8.5.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-jest": "^25.3.3",
    "jest": "^27.4.5",
    "parcel": "^2.0.0-nightly.961",
    "prettier": "^2.5.1",
    "typescript": "^4.5.4"
  }
```

Result:

```js
import { EventEmitter as  } from "events";
import { Getter as , Options as , Schema as  } from "./main.d";
```

**Comment by jvanderen1** [comment]
@selfagency Are you using yarn? When I retried using yarn, the versions I got in my package.json were "nightly" and it worked. I believe there's apparent versioning incompatibilities between some parcel packages.

**Comment by mischnic** [comment]
- Using a strict `2.0.0-nightly.961` version range for all of Parcel packages doesn't result in compatible packages, because lerna somehow introduced some offsets between the versions during publishing.
- Using a non-strict range is problematic in general, because even `2.0.0` is compatible with a caret nightly version range: https://jubianchi.github.io/semver-check/#/^2.0.0-nightly.961/2.0.0

For example these packages were all published at the same time:
```
 @parcel/config-webextension@2.0.2-nightly.2585
 parcel@2.0.0-nightly.961
 @parcel/transformer-xml@2.0.2-nightly.2585
 @parcel/transformer-yaml@2.0.0-nightly.963
```

**Comment by selfagency** [comment]
@jvanderen1 @mischnic I am using `yarn` and I switched from "^2.0.0-nightly.961" to "^2.0.0-nightly" and I'm still having the issue. You can try the repo [here](https://github.com/selfagency/antiflux). 

Also, how do I get the generated types file to inline my other types instead of importing them from my `main.d.ts`, which it's not even copying into the bundle?
