### ISSUE TITLE
postcss errors silently ignored

### ISSUE THREAD

**Issue by olivoil** [parcel-bundler/parcel#749]
This is a 🙋 feature request I think.

### 🎛 Configuration (postcss.config.js)

```javascript
// postcss.config.js

modules.export = function() {
   return {
      modules: true
   }
}
```

Parcel only works if `postcss.config.js` exports a direct object, not a function.

### 🤔 Expected Behavior

I think it would be helpful to the user, in case parcel does detect a postcss config, or any other supported transform config, to report errors back to the user, instead of silently ignoring them. Something along the line of `Parcel detected configuration for postcss, but was not able to use it: <error with stack trace if available>`.

### 😯 Current Behavior

Parcel does not give any error, and just bundles the css unprocessed. 

### 💁 Possible Solution

The underlying problem is that parcel silently ignores the error and doesn't give useful feedback that would help understand what is happening. If a configuration for a particular transform is detected but fails to run, parcel should tell the developer that instead of ignoring it. I haven't looked into the source code of parcel yet, but happy to start a PR if you point me in the right direction.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.4.1
| Node             | v8.9.4
| Yarn         | v1.3.2 
| Operating System | Linux Ubuntu 17.10

**Comment by olivoil** [comment]
Looks like possibly #593 and #329 are related. It seems giving an informative error message would help them figure out why postcss isn't working

**Comment by JounQin** [comment]
Why can not we support function PosctCSS config?

I have to call the function manually for now, which is ridiculous:

```js
module.exports = require('@1stg/postcss-config')({ env: process.env.NODE_ENV })
```
