### ISSUE TITLE
CSS Modules stop working after adding PostCSS config

### ISSUE THREAD

**Issue by blvdmitry** [parcel-bundler/parcel#7492]
# 🐛 bug report

When setting up a starter project I've noticed that CSS Modules worked fine at first, but when I add a postcss config to the project, CSS modules file detection stops working. Adding `modules: true` to the config enforces modules for all files in that case but that still gets applied only for the files located in the product and not in the library itself.

## 🎛 Configuration (.babelrc, package.json, cli command)

No additional configuration

## 🤔 Expected Behavior

Color from index.module.css styles get applied to the rendered text

## 😯 Current Behavior

CSS Modules import returns no classNames and text is rendered with the default browser color

## 🔦 Context

I've been trying to create an example of using my component library [Arcade together with Parcel](https://github.com/arcade-design/community/tree/master/examples). It heavily relies on 2 ideas of working with CSS:
- It exposes a postcss config that should be used on the product side by re-exporting it from postcss.config.js
- It works with CSS Modules which stay in the ESM build of the library and also can be used in the product code

## 💻 Code Sample

The issue can be reproduced here: 
https://github.com/blvdmitry/parcel-postcss-issue

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | 16.13.0
| npm/Yarn         | Yarn 1.22.11
| Operating System | Mac OS Big Sur 11.6.1

**Comment by devongovett** [comment]
Looks like custom PostCSS config is not currently merged with the default config for `.module.css` files. Instead it overrides. I think #7177 is related.

**Comment by blvdmitry** [comment]
Oh, yes, I think I've seen that one but for some reason thought it was slightly different. Should I just move the relevant additional information there and close this issue?
