### ISSUE TITLE
Compile time template (jsx or vue) rendering, or "static site generation" ?

### ISSUE THREAD

**Issue by yw662** [parcel-bundler/parcel#7497]
# 🙋 feature request

It's somehow like a `React` or `Vue` version of `pug`. And of course I have read #5195.
You can do compile-time scripting with `pug`, but it is not very handy to work with. Jsx (or Vue) provides a more flexible way, and more convenient since it is better supported.
There are already some "static site generator" that turns framework codes into HTML, like `Next.js` for `React`, and `ReactDOMServer` indeed provided 2 ways to do so, `RenderToString` and `RenderToStaticMarkup`, the later one would give fully static document. So there should be no worry about the compiling itself.

## 🤔 Expected Behavior

What I am suggesting is, 
* maybe a **transformer**, 
* to take in a specific kind of jsx code (maybe `.page.jsx` for example, so that normal `.jsx` files can be processed as usual),
* and render it into a `.html` with the same name, like `index.page.tsx` into `index.html`, at compile time.
* The file should, like what `Next.js` requires, export several **well-known names**, including:
    *  the component itself (which would be rendered into the document),
    *  the parameters passing to the component render function, or "initial properties", 
    * and maybe sth like whether it is for `RenderToString` or `RenderToStaticMarkup`, or additional React parameters.

Or, a general way for compile-time scripting, or "compile-time function execution": a way to run javascript at compile time, and use its output as a final compile result.

## 😯 Current Behavior

`jsx/tsx` will be compiled into `js`. The only templating language that compiles into `html` is `pug`.

## 💁 Possible Solution

1. As suggested above, a **transformer**, for a specific kind of `jsx` file (`.page.jsx` or `.page.tsx`), that will render the component exported by the `jsx` file into `html`.

or, 

2. Possibly a general compile-time scripting solution.

## 🔦 Context

Static site generation. And what #5195 was trying to achieve.

## 💻 Examples

```tsx
// index.page.tsx
export default function Page() {
return <div>Hello, World!</p>
}
```
And it compiles into:
```html
<!-- index.html -->
<div>Hello, World!</div>
```

**Comment by mischnic** [comment]
I think this would be better suited for a third-party plugin, because we don't want to enforce some convention the way Next.js does. As you've said this should be possible to implement entirely in a transformer.

Since you mentioned "static site generation" though: the difference between what you're proposing and something like Eleventy is being able to introspect the list of pages to generate i.e. a sitemap. That is harder: https://github.com/mischnic/parcel-ssg
