### ISSUE TITLE
Build not recognizing changes to routes in html, css, and sometimes javascript

### ISSUE THREAD

**Issue by BryanCanCode313** [parcel-bundler/parcel#7502]
# 🐛 bug report

I've been writing and re-writing code to this project. The Parcel.js bundle came with the template I downloaded. All the code i wrote worked fine until I tried to add a second page to route to. Once I did add the second page I noticed the the terminal no longer logged the build time after an edit had been mad to the code. 
    Whether the editing was happening in a CSS/HTML file that stylized/structured the second page (ironically my JS still effects the build), it would fail to build in the terminal and consequently, fail to reflect any changes in the local host server provided by Parcel. 
    
 I hope the following information is being described clearly enough.

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json, npm start

## 🤔 Expected Behavior

I'd like for the element selected to trigger routing to a new page to complete successfully. I'd also like for the build logged in the terminal to update when code gets revised on the new pages' CSS and HTML files 

## 😯 Current Behavior

The Local Host does not reflect the revised styling/structuring in the browser; the terminal is not building as code gets revised.

## 💁 Possible Solution

I've seen some discussions that suggest going into the package.json and pointing the build command to an alt HTML file in the directory that I'd like to otherwise, route to based on an event.  I toggle between typing "index.html" as a the value for the **build/npm start** key commands to see the updates my code revisions warrant
## 🔦 Context

  The issue has definitely impeded progress with designing the site. 

## 💻 Code Sample

    // index.html
      `<script type="module" src="js/main.js"></script>`

   // index.html
      `<link rel="stylesheet" href="css/main.css">`

   // main.js
      ` element.onclick = function () {
          **_location.href = "../home.html"_**;
        };`

[link to the repo of this project](https://github.com/BryanCanCode313/bmdws2.git)
## 🌍 Your Environment

Im writing all this code in Visual Code IDE

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |    "parcel-bundler": "^1.12.5"
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
> "parcel-bundler": "^1.12.5"

Parcel 1 is not maintained anymore.
