### ISSUE TITLE
Compressor type is not in `.d.ts` file for @parcel/plugin

### ISSUE THREAD

**Issue by deontologician** [parcel-bundler/parcel#7507]
# 🐛 bug report

I created a new parcel plugin and Typescript is complaining that `Compressor` isn't a member of `@parcel/plugin`.

It just looks like the `.d.ts` file wasn't regenerated after #6776 

(Apologies for deleting all the other stuff in the bug report, it looks pretty straightforward, I can probably submit a fix once I'm done with a current deadline)

**Comment by mischnic** [comment]
It seems that the only thing missing is the "reexport" in https://github.com/parcel-bundler/parcel/blob/v2/packages/core/plugin/src/PluginAPI.d.ts
