### ISSUE TITLE
Add option to disable `import.meta.env` replacement

### ISSUE THREAD

**Issue by itsMapleLeaf** [parcel-bundler/parcel#7520]
# 💬 RFC

I think Parcel should have a way to disable the replacement of `import.meta.env` with the path at build time. Either through config, or something like a `/* preserve-meta-url */` comment.

## 🔦 Context

I want to use Parcel to build a Node project with native ESM. Parcel's replacement of `import.meta.env` gets in the way of using it to resolve file-relative paths.

## 💻 Examples

Here's an example of using `import.meta.env` in node:

```ts
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const projectRoot = join(__dirname, "..")

export function fromProjectRoot(...subPaths: string[]) {
  return join(projectRoot, ...subPaths)
}
```

When running through node natively, `import.meta.env` is expected to be an absolute file URL to the file, so `file:///home/project/file.ts`

Instead, parcel replaces it with a project-relative URL: `file:///file.ts`

At runtime, `projectRoot` should be `/home/project`, but instead, it becomes `/`. Having a way to disable `import.meta.env` replacement and read it at runtime would be helpful to resolve this, to align with native node behavior.

**Comment by devongovett** [comment]
When bundling a project, Parcel's goal is that it behaves exactly the same as if it were unbundled, running the source directly. `import.meta.url` refers to the source file, so parcel compiles it  to preserve this behavior when the code is bundled. If we did not, then the path would be different than it was in the original source.

**Comment by itsMapleLeaf** [comment]
> When bundling a project, Parcel's goal is that it behaves exactly the same as if it were unbundled

That's the goal! But this is not what I'm observing :confused:

<details>

<summary>Here's a reproduction.</summary>

```js
// input
console.log(import.meta.url)
```
```js
var $241ffcb5afd12ecc$exports = {};
console.log("file:///input.js");


export {$241ffcb5afd12ecc$exports as default};
//# sourceMappingURL=output.js.map
```
```json
{
  "type": "module",
  "source": "input.js",
  "main": "output.js",
  "scripts": {
    "build": "parcel build && node input.js && node output.js"
  },
  "devDependencies": {
    "esmo": "^0.13.0",
    "parcel": "^2.0.1"
  }
}
```
```
> @ build /home/maple/dev/parcel-import-meta-url-node
> parcel build && node input.js && node output.js

✨ Built in 657ms

output.js    153 B    142ms
file:///home/maple/dev/parcel-import-meta-url-node/input.js
file:///input.js
```

</details>

Repo link: https://github.com/itsMapleLeaf/parcel-import-meta-url-node

If we wanted the output to behave exactly as the input would natively, shouldn't the paths be the same here?

---

Either way, if this is some behavior that can't or shouldn't be changed for whatever reason, what would you suggest as an alternative/workaround? e.g. For the `fromProjectRoot` use case in the issue description. I wanted to use `import.meta.url` as a stable path marker for finding the project root. Same path regardless of where or how it's run.

**Comment by devongovett** [comment]
The problem with inlining the whole absolute file path is that it's not portable. If you moved the dist to a different directory the output would need change but couldn't. Same if you built the project on a different machine. It doesn't seem terribly useful to inline that because the file path where the code is run might be different from where it was compiled.

The same issue occurs in browsers where the base url should be HTTP when loaded from source for example, which could change when the deployment is moved. I'm not sure how parcel could determine the correct base path at runtime.

**Comment by itsMapleLeaf** [comment]
Alright, I get the reasoning. So it sounds more to me like `import.meta.url` isn't the right tool to use here. A build-time constant would work better, maybe?

**Comment by itsMapleLeaf** [comment]
Yeah, I think that's the answer here. I'll close this
