### ISSUE TITLE
build failed with @parcel/optimizer-cssnano: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by Florian79** [parcel-bundler/parcel#7522]
# 🐛 bug report

I am getting a build failed error when building my project with parcel 2

Build failed.
@parcel/optimizer-cssnano: The "path" argument must be of type string. Received undefined
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
  at new NodeError (node:internal/errors:371:5)
  at validateString (node:internal/validators:119:11)
  at Object.resolve (node:path:1098:7)
  at pathToFileURL (node:internal/url:1479:25)
  at Input.origin (/Users/florianbauer/dev/bit.flower/client/node_modules/postcss/lib/input.js:158:43)
  at Input.error (/Users/florianbauer/dev/bit.flower/client/node_modules/postcss/lib/input.js:112:23)
  at Parser.checkMissedSemicolon (/Users/florianbauer/dev/bit.flower/client/node_modules/postcss/lib/parser.js:558:22)
  at Parser.decl (/Users/florianbauer/dev/bit.flower/client/node_modules/postcss/lib/parser.js:253:12)
  at Parser.other (/Users/florianbauer/dev/bit.flower/client/node_modules/postcss/lib/parser.js:115:18)
  at Parser.parse (/Users/florianbauer/dev/bit.flower/client/node_modules/postcss/lib/parser.js:59:16)
```

build works fine as long as i use the --no-optimize option. it looks like something went wrong inside postcss or nanocss but it does not indicates which of my js/css modules are affected.

## 🎛 Configuration (.babelrc, package.json, cli command)
i go pretty much with the default configuration:

```
package.json :

"targets": {
    "default": {
      "outputFormat": "esmodule",
      "context": "browser",
      "engines": {
        "browsers": [
          "> 0.5%, last 2 versions, not dead"
        ]
      },
      "distDir": "../public/parcel2"
    }
  },
"scripts": {
    "build:parcel": "parcel build --log-level warn --no-optimize src/index.js",
    "build:parcel.prod": "parcel build --log-level warn src/index.js",
},
"devDependencies": { 
    "parcel": "^2.0.1"
}

```

## 🤔 Expected Behavior

i would like to do a production build with parcel without errors

## 😯 Current Behavior

see stack trace above

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | 16
| npm/Yarn         | npm 8
| Operating System | ios

**Comment by ericzbeard** [comment]
Has anyone looked into this? I'm seeing the same behavior. I'm forced to add --no-optimize to work around it.

**Comment by mischnic** [comment]
This sounds like there's a parser error

>   at Input.error (/Users/florianbauer/dev/bit.flower/client/node_modules/postcss/lib/input.js:112:23)
>   at Parser.checkMissedSemicolon 

and it fails to print that parser error because `from` is undefined

https://github.com/parcel-bundler/parcel/blob/4745cd3023f8d5a5adcf9e565d5b82d1418dc262/packages/optimizers/cssnano/src/CSSNanoOptimizer.js#L48-L50

So maybe we should change that to be some actual string. 
But there should usually not be a parser error in the optimizer anyway...

**Comment by mbarker84** [comment]
I was getting the same error on build and also this one:
```
@parcel/optimizer-cssnano: <css input>:743:228: Unclosed string

  CssSyntaxError: <css input>:743:228: Unclosed string
  at Input.error
```
Appeared the problem was with base64 encoded SVGs in the stylesheet, e.g:
```css
background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' xml:space='preserve' viewBox='0 0 300 300'%3E%3Cpath fill='rgb(82, 96, 123)' d='M149.9 231.1-.6 114 34 69.6l115.9 90.2 115.5-90.2 34.6 44.3z'/%3E%3C/svg%3E");
```
I was able to work around this by instead using a relative URL:
```css
background-image: url('data-url:../icons/icon-chevron-down.svg');
```

**Comment by praneetloke** [comment]
I needed to disable CSS optimization to get around this in case anyone else hits this. I had this in my `.parcelrc` file.

```
{
    "extends": "@parcel/config-default",
    "optimizers": {
        "*.css": [],
    }
}
```

**Comment by devongovett** [comment]
Sounds related to #7710
