### ISSUE TITLE
Changes in SASS files that are included with `@import` are not picked up if there is a cached version.

### ISSUE THREAD

**Issue by renspr** [parcel-bundler/parcel#7524]
# 🐛 bug report

Changes in SASS files that are included with `@import` are not picked up if there is a cached version in `.parcel-cache`.

## 🎛 Configuration

I've created a minimal demo here: https://github.com/renspr/parcelbug

package.json

```js
{
  "name": "parcelbug",
  "private": true,
  "dependencies": {
    "parcel": "^2.0.1"
  },
  "scripts": {
    "parcel:serve": "parcel serve --dist-dir ./dist ./src/application.scss"
  },
  "devDependencies": {
    "@parcel/transformer-sass": "2.0.1"
  }
}
```

dist/index.html

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="application.css" data-turbo-track="reload" media="all">
</head>
<body>
  <h1>This is a test!</h1>
</body>
</html>
```

src/application.scss

```scss
@import "test.scss";

h1 {
  background-color: green;
}
```

src/test.scss

```scss
body {
  background-color: yellow;
}
```

command line

```
$ yarn parcel:serve
``` 

## 🤔 Expected Behavior

If I change `background-color` in `src/test.scss` from `yellow` to `red` I expect the background to be red. If I reverse the change back to `yellow` I expect the background to be yellow again.

## 😯 Current Behavior

Parcel will pickup the change from `yellow` to `red`. But if I reverse the change back to `yellow`, the background will stay red. If I disable caching with `--no-cache` it works as expected.

This only affects files that are included in another sass file using `@import`. Changes in `application.scss` (e.g. the background-color of the h1 tag) will always be picked up and it works as expected.

## 💻 Code Sample

You can find a minimal version to reproduce the bug here: https://github.com/renspr/parcelbug

I've also created a screen recording showing the bug: https://github.com/renspr/parcelbug/raw/main/demo.mov

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | 17.3.0
| npm/Yarn         | Yarn
| Operating System | MacOS

**Comment by mischnic** [comment]
You have Parcel installed globally? 

It works fine when doing `yarn add parcel` after cloning to install it in to the project

**Comment by renspr** [comment]
Hi, I don't have parcel installed globally. `yarn add parcel` will install parcel 2.0.1 in to the project, which is the version listed in package.json. `yarn parcel --version` will return `2.0.1`.

**Comment by mischnic** [comment]
I'm sorry, you're right. I can reproduce this
