### ISSUE TITLE
🙋 Add --rev option to `build` command for revved filenames

### ISSUE THREAD

**Issue by gamebox** [parcel-bundler/parcel#753]
### 🤔 Expected Behavior

When using `parcel build`, one should be able to supply a `--rev` option at the cli to have the resulting bundles filename be `bundlename-LAST_SIX_OF_MD5_HASH.ext`

### 😯 Current Behavior

No such option exists, requiring a multistep build process for production deployments

### 💁 Possible Solution

I think the cli flag discussed above is the best solution.

### 🔦 Context
We like to have all of our application bundles be "revved" with a chunk of the MD5 hash of the file appended to the bundle name for easy cache invalidation for the client.  We can do this now, but it requires yet another step in the build process.

**Comment by gamebox** [comment]
If it helps, I've went through the source and I _think_ I could put in a PR for this relatively easily.

**Comment by devongovett** [comment]
Should be solved by #1025 which generates content-hashed filenames for static assets. Please help test using the master branch - a release will hopefully come next week!
