### ISSUE TITLE
new URL() constructor does not work when passing the file path as a variable in a React Component

### ISSUE THREAD

**Issue by isjackwild** [parcel-bundler/parcel#7533]
# 🐛 bug report

When using the URL constructor to create a URL, I cannot use a variable for the file path. I'm creating the URL's dynamically within a React Component

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "cash-by-cash-app-2022",
  "version": "1.0.0",
  "license": "MIT",
  "source": "src/index.html",
  "browserslist": "> 0.5%, last 2 versions, not dead",
  "scripts": {
    "start": "parcel",
    "build": "parcel build"
  },
  "devDependencies": {
    "@parcel/resolver-glob": "^2.1.0",
    "@parcel/transformer-sass": "^2.1.0",
    "@types/react": "^17.0.38",
    "@types/three": "^0.135.0",
    "parcel": "^2.1.0",
    "parcel-reporter-static-files-copy": "^1.3.4",
    "sharp": "^0.29.3"
  },
  "dependencies": {
    "lodash": "^4.17.21",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "stats.js": "^0.17.0",
    "three": "^0.135.0"
  }
}

```

## 🤔 Expected Behavior

The URL constructor should work when passing in paths as variables.

## 😯 Current Behavior

The URL constructor only works if the string is directly hard coded into the URL constructor.

## 💁 Possible Solution

This has me stumped, I'm not sure!

## 🔦 Context

It's very limiting to not be able to have these paths as URL's, as in my case for example, I want to store image paths in a JSON file.

## 💻 Code Sample

This does not work, If I inspect the code, it's give the image src as `file:///src/images/1000x1000.png`:

```js
const imagePath = "/src/images/1000x1000.png";

<img src={new URL(imagePath, import.meta.url) as any as string} />
```

However this does work:

```js
<img src={new URL("/src/images/1000x1000.png", import.meta.url) as any as string} />
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.1.0
| Node             |  v16.13.1
| npm/Yarn         | 8.1.2
| Operating System | MacOS M1

**Comment by mischnic** [comment]
This is intentional, because at some point Parcel cannot figure out the filepath at buildtime anymore. So it has to be literally `new URL("a string literal", import.meta.url")`

**Comment by isjackwild** [comment]
okay, so there would be no way to store image paths in a JSON file in that case, if my thinking is correct (cannot use the new URL() constructor within JSON as it's Javascript)

**Comment by devongovett** [comment]
If they are all in the same folder, you could use the glob resolver: https://parceljs.org/features/dependency-resolution/#glob-specifiers

```jsx
import * as urls from "./images/*.png";

<img src={urls['1000x1000']} />
```

**Comment by mischnic** [comment]
This might be overkill for your situation but you could write a Parcel transformer plugin that reads in a json file
```json
{ 1000: "./1000x1000.png", 2000: "./2000x2000.png" }
```
and rewrites it into
```js
const images = { 1000: new URL("./1000x1000.png", import.meta.url), 2000: ...};
export default images;
```

That way, the paths are in a JSON file but are still passed as string literals into the constructor.

**Comment by isjackwild** [comment]
Thanks — this is really helpful @devongovett I'm currently using the approach you mention here but I'd like to make use of the image resizing and formatting feature. @mischnic I will take a look at your suggestion — it might be really good for my use case, and I'd be keen to have a stab at creating a custom transformer plugin.

PS. Parcel is awesome, thanks for all your hard work :)

**Comment by astro813** [comment]
Hey, @devongovett It's work well also for me. But when I using the TypeScript, it's got a TS error as show below:

![image](https://user-images.githubusercontent.com/15335943/182791970-2ed8214d-3949-4493-be16-947c644d1d9c.png)

I mean I could using @ts-ignore to solve, But not very nice. Any suggestion for this?

Thanks in advance.
