### ISSUE TITLE
Failed to resolve module specifier "react/jsx-runtime" since v2.0.0

### ISSUE THREAD

**Issue by KillerCodeMonkey** [parcel-bundler/parcel#7534]
# 🐛 bug report

Sadly bundling the renderer index.html file of my app leads to another error, when opening the bundled app. IMPORTANT: this is no error during bundling.
Background: my renderer is using react (nothing special):

And i get the error:
```
index.html:1 Uncaught TypeError: Failed to resolve module specifier "react/jsx-runtime". Relative references must start with either "/", "./", or "../".
```

## 🎛 Configuration (.babelrc, package.json, cli command)

My "dev" command to build the renderer:
```sh
parcel watch src/launcher/renderer/index.html --target electron-renderer --port 1236 --no-cache
```

My build command:
```sh
parcel build ./src/launcher/renderer/index.html --target electron-renderer --no-cache
```

```js
{
  "electron-renderer": "./dist/launcher/index.html",
  "targets": {
    "electron-renderer": {
      "context": "electron-renderer",
      "distDir": "./dist/launcher/renderer",
      "isLibrary": false,
      "publicUrl": "."
    }
  }
}
```

## 🤔 Expected Behavior

if its work in watch mode - it should work in production mode.

## 😯 Current Behavior

It works in watch-mode, but after building the error occurs when starting the app.

## 💁 Possible Solution

Seems like node_modules are not correctly bundled during production build or maybe it is the scope hoisting.

## 🔦 Context

Just want to build my electron app with a renderer using react.

## 💻 Code Sample

SourceCode:
```html
<html>
  <head>
    <meta charset="UTF-8" />
    <title>My App</title>
  </head>
  <body>
    <!-- You can also require other files to run in this process -->
    <script type="module" src="./index.tsx"></script>
  </body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.2.1 (tested with 2.0.0 and 2.1.1, as well)
| Node             | 16.10.0
| npm/Yarn         | 7.24.2
| Operating System | Ubuntu 20.04

**Comment by KillerCodeMonkey** [comment]
exists in 2.2.1 as well (only in production bundles)

**Comment by KillerCodeMonkey** [comment]
For everyone having this issue: it seems parcel 2.x does not handle nodeIntegration settings for electron-renderer bundles.

I deactivated nodeIntegration and activated contextIsolation for my BrowserWindows created by the main process.

I added a contextBridge in the preload script that i build as "electron-main" context.
My renderer will be now built as "browser" context and not as "electron-renderer".

I leave this issue open, because as a bundler building everything "out-of-the-box" with electron support should really provide an out of the box solution for that.

Keep up with the nice work! Thx

**Comment by cupcakearmy** [comment]
Same issue here

**Comment by zababurinsv** [comment]
Same issue here

**Comment by lemonspb** [comment]
i also faced this problem
