### ISSUE TITLE
Environment variables: "ReferenceError: process is not defined"

### ISSUE THREAD

**Issue by MiVe159** [parcel-bundler/parcel#7536]
# 🐛 bug report

We are currently migrating from Parcel 1 to 2. So far we could solve emerging issues but this one is blocking: we can't use environment variables (.env file).

It looks like the "process" object isn't being defined by Parcels' output. This wasn't an issue with version 1.

The .env file is in the same directory as package.json & .parcelrc

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json:

```json
{
  "name": "@zf/heat-erp",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "builddist": "parcel build ./src/index.html",
    "start": "parcel ./src/index.html --no-autoinstall --https",
    "build:artifacts": "cross-env-shell NODE_ENV=production parcel build ./src/index.html --no-source-maps --no-cache && copy \"web.config\" \"dist\\web.config\"",
    "build:artifacts-staging": "cross-env-shell NODE_ENV=staging parcel build ./src/index.html --no-source-maps --no-cache && copy \"web.config\" \"dist\\web.config\"",
    "clean": "rm -rf dist .cache junit.xml",
    "test": "jest --reporters=jest-junit --reporters=default --passWithNoTests"
  },
  "browserslist": [
    "> 0.5%",
    "last 1 version",
    "not dead",
    "not ie 11",
    "not Samsung < 12",
    "not OperaMobile < 48",
    "not OperaMini all",
    "not ExplorerMobile < 12",
    "not Baidu < 12",
    "not Android < 70",
    "not QQAndroid < 2"
  ],
  "dependencies": {
    "@reach/router": "^1.3.4",
    "@zf/auth": "^1.0.0",
    "@zf/css-variables": "^1.0.0",
    "@zf/hooks": "^1.0.0",
    "@zf/stella-react": "^1.0.0",
    "axios": "^0.19.0",
    "browserify": "^16.5.2",
    "classnames": "^2.2.6",
    "clone": "^2.1.2",
    "core-js": "2.6.5",
    "detect-browser": "^4.6.0",
    "install": "^0.13.0",
    "interweave": "^12.7.1",
    "moment": "^2.24.0",
    "npm": "^6.13.4",
    "paragraph": "^0.0.1",
    "query-string": "^6.9.0",
    "react-json-view": "^1.21.3",
    "react-sortablejs": "^1.5.1",
    "react-tracked": "^1.1.0",
    "recharts": "^2.0.8",
    "sortablejs": "^1.11.2-alpha.3",
    "xlsx": "^0.15.4"
  },
  "devDependencies": {
    "@svgr/parcel-plugin-svgr": "^4.3.2",
    "@types/accounting": "^0.4.1",
    "@types/classnames": "^2.2.9",
    "@types/file-saver": "^2.0.1",
    "@types/reach__router": "^1.2.4",
    "@zf/api-types": "^1.0.0",
    "autoprefixer": "^9.6.1",
    "cross-env": "^6.0.3",
    "jest": "^24.8.0",
    "lodash": "^4.17.15",
    "parcel": "^2.1.1",
    "parcel-plugin-bundle-visualiser": "^1.2.0",
    "@parcel/resolver-glob": "^2.1.1",
    "@parcel/transformer-sass": "^2.1.1",
    "@parcel/transformer-raw": "^2.1.1",
    "postcss-modules": "^1.4.1",
    "postcss-url": "^8.0.0",
    "prop-types": "^15.7.2",
    "sass": "^1.22.9",
    "tsify": "^4.0.1"
  }
}
```

.parcelrc (we added the transformer in the hope to see parcel 1 behavior for the .env file):

```json
{
  "extends": "@parcel/config-default",
  "resolvers": [
    "@parcel/resolver-glob",
    "..."
  ],
  "transformers": {
    "*.{env}": [
      "@parcel/transformer-raw"
    ]
  }
}
```

## 🤔 Expected Behavior

`process` is defined so we can call `process.env.API_ENDPOINT` for example.

## 😯 Current Behavior

![image](https://user-images.githubusercontent.com/97302787/148572676-978457f7-921c-4d27-85ac-40b1e57cdbfd.png)

![image](https://user-images.githubusercontent.com/97302787/148572758-27d0f7dd-c71d-490d-a8af-7851078aa2d8.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.1.1
| Node             | 16.13.1
| npm/Yarn         | npm 8.1.2 / Yarn 1.22.5
| Operating System | Windows 10 64-bit

**Comment by mischnic** [comment]
Can you please post the code that causes the "process is not defined" error?

Even if the env file isn't read, `process.env.API_ENDPOINT` should just becomes `undefined` and not cause that error

**Comment by MiVe159** [comment]
`process.env` is called the first time inside a `<script>` tag in index.html.

I saw that `type="module"` was missing there but it didn't fix the issue completely. The process.env object is now empty instead of undefined:

![image](https://user-images.githubusercontent.com/97302787/148679819-49412830-bdc2-447f-8895-740f3d7b8c77.png)

![image](https://user-images.githubusercontent.com/97302787/148679950-77db69f8-a8b2-4ed3-9918-5e1eda689280.png)

`process.env.API_ENDPOINT` is called inside our constants ts file:

![image](https://user-images.githubusercontent.com/97302787/148680257-7d077047-8e57-4555-9778-33889f6801c8.png)



![image](https://user-images.githubusercontent.com/97302787/148679828-913d2032-0478-49f0-a524-0f0d06e562bb.png)

This is the location of the .env file relative to package json and parcelrc:

![image](https://user-images.githubusercontent.com/97302787/148679879-b06b3b46-5ab1-4e8e-9705-4bda82ae4c7d.png)

And its content (trimmed for security reasons):

![image](https://user-images.githubusercontent.com/97302787/148680079-e5ea2fc6-48bd-43d3-b6f2-b1cfa2d343fd.png)

**Comment by mischnic** [comment]
> I saw that type="module" was missing there but it didn't fix the issue completely. The process.env object is now empty instead of undefined:

So it looks like `process.env.*` isn't being replaced with non-module scripts.

<br>

You have to use `process.env.SOMETHING` to have it replaced by Parcel (so not `console.log(process.env);`).
But that doesn't really explain why `if(!process.env.API_ENDPOINT)` doesn't work.

> Accessing process.env in any non-static ways (e.g. dynamic property lookups) is not supported.
> (https://parceljs.org/features/node-emulation/#environment-variables)

**Comment by Stono** [comment]
I think I'm hitting a very similar bug, we have this in `.env`: 

```
SASS_PATH="./src/assets/styles"
```

I get:
```

🚨 Build failed.

@parcel/transformer-sass: Can't find stylesheet to import.
╷
1 │ @import '_base';
│         ^^^^^^^
╵
src/assets/index.scss 1:9  root stylesheet

  Error: Can't find stylesheet to import.
  ╷
  1 │ @import '_base';
  │         ^^^^^^^
  ╵
```

But if i manually set it with `export SASS_PATH="./src/assets/styles"`, it's fine:

```
✨ Built in 1.21s

dist/index.html                414 B    339ms
dist/index.e5caa423.js     129.43 KB    702ms
dist/index.52cb5cfc.css         92 B    686ms
```

This was fine on parcel v1

PS.  I'm new to parcel, so there's also a solid chance i've just done something wrong :)

**Comment by MiVe159** [comment]
We made the switch to Webpack, cost us about a week but also resolved quite some issues.

**Comment by albinbrengesjo** [comment]
Facing the exact same problem. Anyone found a solution? Running on parcel 2.7.0

**Comment by dillonkelley** [comment]
This is still a bug. I receive the error `Uncaught ReferenceError: process is not defined`.

But when I console log `process.env.NODE_ENV` it returns `development`

So there is some expected behavior but at the cost of console errors...

**Comment by samuliasmala** [comment]
> This is still a bug. I receive the error `Uncaught ReferenceError: process is not defined`.
> 
> But when I console log `process.env.NODE_ENV` it returns `development`
> 
> So there is some expected behavior but at the cost of console errors...

This can be fixed by installing process polyfill `npm install --save-dev process` and after that [Parcel will use it automatically](https://parceljs.org/features/node-emulation/#polyfilling-%26-excluding-builtin-node-modules). I'm running parcel@2.8.3 and it works nicely.

**Comment by roark** [comment]
I also was experiencing this issue in `2.8.3`, which used to work in `2.0.0-beta.2`.

Updating my script type from `text/javascript` to `module` and adding the process polyfill did seem to resolve it for me.

**Comment by vanya2h** [comment]
I can confirm I'm facing the same issue with `2.12.0`. Couldn't find any possible workarounds on this..

**Comment by nitelite** [comment]
Upgraded from 2.9.2 to 2.12.0 and is now facing the same issue. Installing the `process` dependency did not change anything. Code that previously read the appropriate .env.xxx file just fine and provided the value when referenced using `process.env.variableName` is now giving me an error when running parcel in serve mode: 

`ReferenceError: process is not defined`
