### ISSUE TITLE
Question: How to use precaching with differential bundling?

### ISSUE THREAD

**Issue by fellmann** [parcel-bundler/parcel#7539]
What is the recommended approach to precache assets for offline usage together with differential bundling? I have a working solution using parcel-config-precache-manifest with Parcel 2, but I cannot differentiate in the service worker between the currently used JS versions and the one for compatibility, so everything is downloaded and precached twice.
This is bad for data usage and device storage usage.

**Comment by devongovett** [comment]
Makes sense. I think we probably produce two versions of the service worker already, one for old browsers and one for new browsers. We should probably provide a subset of the assets to the service worker that match the same output format.

**Comment by fellmann** [comment]
I would argue there are two separate problems:
1. Differential builds for service workers, depending on the bundle who registers it. Currently, only one version of the service worker is built, either module or non-module, depending on requested browser support.
2. Using a different set of files to precache depending on the browser capability to use modules.


In order not to block 2 by 1, I would propse the following solution:
- Build two precache manifests, one for nomodule, one for module scripts
- If there are two JS bundles with the same source asset, one with outputFormat "global", one with outputFormat "esmodule", then only add it to the matching precache manifest. All other bundles are added to both manifests.
- Inject both manifests into the service worker.
- Decide which one to use based on the script type, that registers the service worker.

While at it: Why is there only one version generated for all assets? Best practice seems to be using one version for each asset, for example the bundle hash. Otherwise, if one file changes, everything is download again. The format for Workbox Precaching also includes one version for each asset.
