### ISSUE TITLE
Argument for passing a different .env file

### ISSUE THREAD

**Issue by dailypixie** [parcel-bundler/parcel#7542]
# 🙋 feature request

I have multiple builds from the same code base (extension, mobile, electron etc.). I would like a way to pass a different .env file or to mark somehow that is visible in code that what the build/target is designed for.

**Comment by mischnic** [comment]
Would a CLI flag also work or are you specifically looking for target-specific env variables?

https://github.com/parcel-bundler/parcel/issues/7027

**Comment by dailypixie** [comment]
Sure, a CLI flag would work. A more elegant solution would be in the target configuration, but a CLI is good enough for me. Thank you for your fast reply 🤗

**Comment by mischnic** [comment]
Duplicate of https://github.com/parcel-bundler/parcel/issues/7027
