### ISSUE TITLE
Regular Expression Denial of Service in postcss used by uncss

### ISSUE THREAD

**Issue by leicht-io** [parcel-bundler/parcel#7543]
@parcel/optimizer-htmlnano@2.1.1 uses uncss@0.17.3 which depends on postcss@7.0.39.

In versions of postcss prior to 8.2.13 the following DoS was found on the 7th of January: ​https://github.com/advisories/GHSA-566m-qj78-rww5

**Comment by devongovett** [comment]
Unfortunately, this is a dependency of htmlnano. It has been removed, but the fix has not been released to npm yet. I left a comment here: https://github.com/posthtml/htmlnano/issues/165#issuecomment-1010461433

**Comment by leicht-io** [comment]
@devongovett htmlnano@v2 is released.
