### ISSUE TITLE
`@parcel/reporter-dev-server` reports mismatching versions error expecting parcel `^2.1.1`, even though parcel `2.1.1` is installed

### ISSUE THREAD

**Issue by Luna-Klatzer** [parcel-bundler/parcel#7544]
# 🐛 bug report

I am currently having an issue setting up parcel in an GitHub Actions environment. I am trying to install parcel from a package-lock.json file to ensure that my wanted version is used, but despite that I am getting an error that the plugin `@parcel/reporter-dev-server` expects parcel `^2.1.1`, even though parcel `2.1.1` is installed.

## 🎛 Configuration (.babelrc, package.json, cli command)

- Command: `parcel build src/index.html --public-url {{ env.URL }} --dist-dir .`
- [package.json](https://gist.github.com/Luna-Klatzer/1a099c115498fbdf01a6c4a749ceb2d5)
- [package-lock.json](https://gist.github.com/Luna-Klatzer/c5d109f6f9f3e5002546cc1f758f1ee3)

## 🤔 Expected Behavior

Parcel should build the files successfully, without reporting any version errors.

## 😯 Current Behavior

I am receiving the following output when trying to build my files: 

```bash
Error: bleDiagnostic [Error]: The plugin "@parcel/reporter-dev-server" is not compatible with the current version of Parcel. Requires "^2.1.1" but the current version is "2.0.1".] {
  diagnostics: [
    {
      message: 'The plugin "@parcel/reporter-dev-server" is not compatible with the current version of Parcel. Requires "^2.1.1" but the current version is "2.0.1".',
      origin: '@parcel/core',
      codeFrames: [Array]
    }
  ]
}
Error: bleDiagnostic [Error]: The plugin "@parcel/reporter-dev-server" is not compatible with the current version of Parcel. Requires "^2.1.1" but the current version is "2.0.1".] {
  diagnostics: [
    {
      message: 'The plugin "@parcel/reporter-dev-server" is not compatible with the current version of Parcel. Requires "^2.1.1" but the current version is "2.0.1".',
      origin: '@parcel/core',
      codeFrames: [Array]
    }
  ]
}
Error: bleDiagnostic [Error]: The plugin "@parcel/reporter-dev-server" is not compatible with the current version of Parcel. Requires "^2.1.1" but the current version is "2.0.1".] {
  diagnostics: [
    {
      message: 'The plugin "@parcel/reporter-dev-server" is not compatible with the current version of Parcel. Requires "^2.1.1" but the current version is "2.0.1".',
      origin: '@parcel/core',
      codeFrames: [Array]
    }
  ]
}
Error: Process completed with exit code 1.
```

## 🔦 Context

[GitHub Actions file, which should successfully build the files](https://gist.github.com/Luna-Klatzer/66d263fac4ebd09fd890f2ec4431a1dc)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.1.1 |
| Node             | 16.13.1 |
| npm/Yarn         | 8.1.2 |
| Operating System | Linux Ubuntu  20.04.3 |

**Comment by mischnic** [comment]
Should be solved after https://github.com/parcel-bundler/parcel/commit/699f0b24c38eabcdad0960c62c03bd2f2902b19e in >= 2.3.2
