### ISSUE TITLE
Running the command 'npx parcel index.html' gets hanged without any error

### ISSUE THREAD

**Issue by ankasani** [parcel-bundler/parcel#7548]
Running the command 'npx parcel index.html' gets hanged without any error, even i cannot cancel ctrl + c, need to close the command prompt.

<img width="373" alt="image" src="https://user-images.githubusercontent.com/35102519/148979986-38fd2652-733d-496f-be29-19e85ce2336b.png">

if i run the build command: npx parcel build index.html ... even it hang

<img width="266" alt="image" src="https://user-images.githubusercontent.com/35102519/148979832-02a4abb7-0855-4571-af48-37cb23e73ead.png">

Versions: 
Parcel: 2.1.1
node: 16.13.2
npm : 8.1.2
windows : 10

**Comment by ankasani** [comment]
even using the latest version 2.2.0 had the same issue.

**Comment by djoyjose1** [comment]
I am having an issue somewhat similar, but not exactly the same. On my machine, just the .parcel-cache folder is created with two files - data.mdb and lock.mdb. Nothing else happens.
Screenshot below:
![image](https://user-images.githubusercontent.com/97246555/150064636-566cfc35-aaaf-40d3-9b56-dcbff16fa29a.png)

**Comment by cabiamdos** [comment]
I have the same issue
