### ISSUE TITLE
Parcel replaces String constructor, breaks some libraries

### ISSUE THREAD

**Issue by sseidel16** [parcel-bundler/parcel#7551]
# 🐛 bug report

Parcel replaces `new String("*")` with `"*"`. Although similar, there are some subtle differences that break code in some libraries (e.g. lunr).

## 🎛 Configuration (.babelrc, package.json, cli command)

Minimal configuration (--no-optimize is only to see results more clearly), package.json:
```js
{
    "name": "project3",
    "version": "1.0.0",
    "scripts": {
        "build": "parcel build ./src/main.js --no-optimize"
    },
    "devDependencies": {
        "parcel": "2.1.1"
    },
    "author": "Stephen Seidel",
    "license": "ISC"
}
```

src/main.js:
```
var s = new String("*");
s.test = "hello";
console.log(s.test);
```

## 🤔 Expected Behavior

This previous code should log "hello" on the console.

## 😯 Current Behavior

Instead, it logs undefined, because it generates this code:
```
(function () {
var $2ff896eeb24a2657$var$s = "*";
$2ff896eeb24a2657$var$s.test = "hello";
console.log($2ff896eeb24a2657$var$s.test);

})();
//# sourceMappingURL=main.js.map
```

String constructor call is replaced with string literal.

## 💁 Possible Solution

Am unable to find even a workaround. Tried with swc, babel, with browserlist, etc. Always seems to exhibit above behavior.

## 🔦 Context

Was attempting to use the useful [lunr](https://github.com/olivernn/lunr.js/) library. It contains code similar to the above and I am unable to use now with parcel.

## 💻 Code Sample

See above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.1.1
| Node             | v14.16.1
| npm/Yarn         | 8.3.0
| Operating System | Mac

**Comment by sseidel16** [comment]
I ran the previous code through swc directly, and through babel directly, and neither of them replaced `String("*")` with `"*"`, so it does not seem like either of these is the culprit.

**Comment by kravets-levko** [comment]
I also encountered this issue yesterday (also with `lunr`), and after some debugging I ended up at this line. Right before it, `code` contains correct js, and immediately after `compiledCode` is already broken.

https://github.com/parcel-bundler/parcel/blob/ec8ed461d2b5dbe014fa60627664fcb8136ad12e/packages/transformers/js/src/JSTransformer.js#L377-L420

Parcel: 2.3.2
Node: 16.13.1
NPM: 8.5.4
Build command: `parcel build --no-cache --no-optimize --dist-dir ./out in.js`

<details>
<summary>Config (`@parcel/config-default` after removing everything not required to build)</summary>

```json
{
  "bundler": "@parcel/bundler-default",
  "transformers": {
    "*.js": ["@parcel/transformer-js"]
  },
  "namers": ["@parcel/namer-default"],
  "runtimes": ["@parcel/runtime-js"],
  "optimizers": {},
  "packagers": {
    "*.js": "@parcel/packager-js"
  },
  "compressors": {
    "*": ["@parcel/compressor-raw"]
  },
  "resolvers": ["@parcel/resolver-default"]
}
```
</details>

<details>
<summary>Input</summary>

```js
"use strict"

const s = new String("test");

s.TEST = "test";

console.log(s);
```
</details>

<details>
<summary>Output</summary>

```js
(function () {
"use strict";
var $4933cc6e62534150$var$s = "test";
$4933cc6e62534150$var$s.TEST = "test";
console.log($4933cc6e62534150$var$s);

})();
//# sourceMappingURL=in.js.map

```
</details>
