### ISSUE TITLE
Parcel watch gives HTTP 426 "Upgrade Required"

### ISSUE THREAD

**Issue by codebling** [parcel-bundler/parcel#7552]
# 🐛 bug report

Starting from a brand new project with Parcel 2.1.1 and a simple index.html, after running `parcel watch`, any request to the Parcel server returns HTTP 426 Upgrade Required. 

steps to reproduce
```
mkdir test && cd test
npm init -y && npm i -D parcel
sed -i -E 's/"main":.*$//' package.json   #remove "main" from package.json to prevent complaints from Parcel
echo "<html><body><pre>hello</pre></body>" > index.html
./node_modules/.bin/parcel watch index.html &
curl -vvv localhost:1234
```

Output of `curl` command is:
```
*   Trying 127.0.0.1:1234...
* Connected to localhost (127.0.0.1) port 1234 (#0)
> GET / HTTP/1.1
> Host: localhost:1234
> User-Agent: curl/7.80.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 426 Upgrade Required
< Content-Length: 16
< Content-Type: text/plain
< Date: Tue, 11 Jan 2022 20:02:06 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
```

`./node_modules/.bin/parcel --version`: 2.1.1

## 🎛 Configuration (.babelrc, package.json, cli command)

N/A

## 🤔 Expected Behavior

HTTP 200 with correct contents, or an error that `parcel watch` is unsupported and we should use `parcel` with no subcommand

## 😯 Current Behavior

See above

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.1.1
| Node             | 16.13.0
| npm/Yarn         |
| Operating System | linux

**Comment by devongovett** [comment]
`parcel watch` does not run the dev server, only the HMR server (which uses a web socket). You can run the dev server using the `parcel serve` command.

**Comment by codebling** [comment]
My bad. Documentation at https://parceljs.org/features/cli/ is correct on this. Thanks

**Comment by karneaud** [comment]
hello,

I too am experiencing this subject error. This is my package.json

```
"main": "index.js",
  "scripts": {
    "dev": "parcel serve --port 3000 --no-cache --hmr-port 3001 --log-level verbose index.html"
  },
  "license": "MIT",
  "browserslist": [
    "> 1%",
    "last 3 versions"
  ],
  "bugs": {
    "url": "https://github.com/vedees/wcms/issues"
  },
  "dependencies": {
    "axios": "^0.27.2",
    "chart.js": "^2.7.3",
    "codemirror": "^5.42.0",
    "locutus": "^2.0.10",
    "save": "^2.3.3",
    "uimini": "^1.1.3",
    "vue": "^3.0.2",
    "vue-chartjs": "^3.4.0",
    "vuex": "4.0.0"
  },
  "devDependencies": {
    "@parcel/transformer-stylus": "2.6.0",
    "@parcel/transformer-vue": "2.6.0",
    "parcel": "^2.6.0",
    "process": "^0.11.10"
  },
```

I'm using the  command `yarn dev` and as you can see I'm using `parcel serve` and getting the same result as the OP.

**Comment by codebling** [comment]
@karneaud consider opening a new issue with the details, including the command you are using to test
