### ISSUE TITLE
Hot module replacement not working with React

### ISSUE THREAD

**Issue by Aloso** [parcel-bundler/parcel#7560]
# 🐛 bug report

A new project with `parcel-bundler`, `typescript` and `react` should provide hot module replacement out of the box. However, when a `.tsx` file is modified, the page is refreshed and all state is lost. This is not the case when using `create-react-app` instead of parcel.

## 💻 Code Sample

Put these files in a new folder and run `npm install && npx parcel run index.html --open`.

`index.tsx`:

```tsx
import React, { useState } from 'react'
import { render } from 'react-dom'

function App() {
  const [x, setX] = useState(0)
  return (
    <h1>
      Counter: {x}
      <button onClick={() => setX(x + 1)}>Add 1</button>
    </h1>
  )
}

render(<App />, document.getElementById('root'))
```

`index.html`:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Test</title>
  </head>
  <body>
    <div id="root"></div>
    <script src="./index.tsx"></script>
  </body>
</html>
```

`package.json`:

```json
{
  "name": "test",
  "dependencies": {
    "@types/react": "^17.0.38",
    "@types/react-dom": "^17.0.11",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.5",
    "typescript": "^4.5.4"
  }
}
```

`tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "es2016",
    "module": "ESNext",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "jsx": "react",
    "skipLibCheck": true
  }
}
```

## 🤔 Expected Behavior

Clicking on the button and then editing the `App` component (e.g. adding an attribute to the `<h1>` tag) should _not_ reset the counter.

## 😯 Current Behavior

The counter is reset to 0.

## 🔦 Context

What are you trying to accomplish?

I want to get the same UX as `create-react-app --template=typescript` offers by default.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.5
| Node             | 17.3.0
| npm         | 8.3.0
| Operating System | Manjaro 21.2.1
| DE | KDE 5.89.0 / Plasma 5.23.4
| Browser | Firefox 96.0

**Comment by lucassarcanjo** [comment]
Hey @Aloso, 

I'm new here, but like the official npm page of `parcel-bundler` [says](https://www.npmjs.com/package/parcel-bundler), the v1 has been deprecated and if you are creating a new project, consider use `parcel` instead.

**Comment by mischnic** [comment]
Exactly, Parcel 2 supports React Fast Refresh which retains the state.

**Comment by Aloso** [comment]
Thanks. I followed an online tutorial and wasn't aware that parcel-bundler is deprecated.
