### ISSUE TITLE
Comments Not Removed in Build Files

### ISSUE THREAD

**Issue by jvanderen1** [parcel-bundler/parcel#7563]
# 🐛 bug report

When compiling my typescript project, the comments in the files are not removed.

### package.json

```json
{
  "name": "@jvanderen1/compare-versions",
  "version": "1.0.0",
  "description": "Compare semver version strings to find greater, equal or lesser.",
  "keywords": [
    "semver",
    "version",
    "compare",
    "browser",
    "node"
  ],
  "homepage": "https://github.com/jvanderen1/compare-versions#readme",
  "bugs": {
    "url": "https://github.com/jvanderen1/compare-versions/issues"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/jvanderen1/compare-versions.git"
  },
  "license": "MIT",
  "author": "<livetoscout@gmail.com>",
  "sideEffects": false,
  "main": "dist/compare-versions.cjs.js",
  "module": "dist/compare-versions.esm.js",
  "source": "src/index.ts",
  "browser": "dist/compare-versions.umd.js",
  "types": "dist/types.d.ts",
  "files": [
    "dist/"
  ],
  "scripts": {
    "build": "parcel build --no-source-maps",
    "clean": "pnpm run clean:dist && pnpm run clean:parcel-cache && pnpm run clean:types && pnpm run clean:node-modules",
    "clean-install": "pnpm run clean && pnpm install",
    "clean:dist": "rimraf dist/",
    "clean:node-modules": "rimraf node_modules/",
    "clean:parcel-cache": "rimraf .parcel-cache/",
    "clean:types": "tsc --build --clean",
    "test": "c8 --reporter=lcov mocha"
  },
  "devDependencies": {
    "@parcel/core": "2.0.0-nightly.980",
    "@parcel/packager-ts": "2.0.0-nightly.982",
    "@parcel/transformer-typescript-types": "2.0.0-nightly.982",
    "c8": "7.11.0",
    "mocha": "9.1.4",
    "parcel": "2.0.0-nightly.980",
    "typescript": "4.5.4"
  },
  "volta": {
    "node": "16.13.2"
  }
}

```

## 🤔 Expected Behavior

When running `parcel build`, I expect comments to be removed from files under `dist/`.

## 😯 Current Behavior

Comments are not being removed.

## 💁 Possible Solution

If this is intended, maybe add a flag or configuration option to remove comments.

## 🔦 Context

This increases the end bundle size significantly.

## 💻 Code Sample

https://github.com/jvanderen1/compare-versions/tree/10dc5d1497ed81ce6e143eb87bb109158f5d4147

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @parcel/core           |  2.0.0-nightly.980
| @parcel/packager-ts | 2.0.0-nightly.982
| @parcel/transformer-typescript-types | 2.0.0-nightly.982
| parcel | 2.0.0-nightly.980
| Node             | 16.13.2
| pnpm        |  6.26.1
| Operating System | macOS 12.1

**Comment by digibake** [comment]
I'm new to Parcel and I've been stuck on this for hours. In my case, I needed to tell parcel to optimize in package.json

```json
"targets": {
  "main": {
    "optimize": true
  }
}
```

I also updated my tsconfig.json to remove comments

```javascript
{
  "compilerOptions": {
    ...
    "removeComments": true
  }
}
```

**Comment by msanguineti** [comment]
> I'm new to Parcel and I've been stuck on this for hours. In my case, I needed to tell parcel to optimize in package.json
> 
> ```json
> "targets": {
>   "main": {
>     "optimize": true
>   }
> }
> ```
> 
> I also updated my tsconfig.json to remove comments
> 
> ```js
> {
>   "compilerOptions": {
>     ...
>     "removeComments": true
>   }
> }
> ```

for building a library with TS and generating types:

 ```json
 "targets": {
   "main": {
     "optimize": true
   },
   "module": {
     "optimize": true
   }
 }
 ```

**DO NOT** use `removeComments: true` in `tsconfig.js`. This will produce a types `.d.ts` file fully commented (from your source files) while the rest of the library files will be void of comments and minified. If you use `removeComments: true`, your generated types will not have any comments... I prefer to have a *types* file fully commented (so that VSCode or similar will pick up definitions and display comments) and optimised JS files.

**Comment by kpotschi** [comment]
For everything js, you can create a ```.terserrc```  file in your project root and tell terser (the underlying minifier for parcel) to remove comments.

**.terserrc**
`{
	"format": {
		"comments": false
	}
}
`

There's more specific optiuons to be found in ther Terser docs.
