### ISSUE TITLE
image url: pipeline fails for web-extension config production build

### ISSUE THREAD

**Issue by Calpoog** [parcel-bundler/parcel#7568]
# 🐛 bug report

When using the url: pipeline for images in my react code, parcel non-production works fine but production (`parcel build`) fails with bundle resolution errors. The images are *not* used in a content script – only in a React app that is displayed in a devtools panel or popup window.

## 🎛 Configuration (.babelrc, package.json, cli command)

.parcelrc
```
{
  "extends": "@parcel/config-webextension"
}
```

package.json
```json
  "targets": {
    "webext-dev": {
      "source": [
        "src/manifest.json",
        "src/app/index.html"
      ],
      "distDir": "dist",
      "sourceMap": {
        "inline": true,
        "inlineSources": true
      }
    },
    "webext-prod": {
      "source": [
        "src/manifest.json",
        "src/app/index.html"
      ],
      "distDir": "dist",
      "sourceMap": false
    }
  },
  "scripts": {
    "start": "rimraf dist && parcel watch --no-hmr --target webext-dev",
    "start:hmr": "rimraf dist && parcel watch --host localhost --hmr-port 1235 --target webext-dev",
    "build": "rimraf dist && parcel build --target webext-prod --detailed-report",
    "test": "jest"
  },
```

## 🤔 Expected Behavior

No bundle resolution errors for my url: pipeline images.

## 😯 Current Behavior

When running my extension which spawns a popup window with my react app, an error for each url: image shows as
![image](https://user-images.githubusercontent.com/3476942/149866110-296c939b-5bcb-4c94-b83b-9d7fe8f5ad45.png)

When looking at the minified file I can see that the three images I'm having trouble with are all required before they are later registered:
![image](https://user-images.githubusercontent.com/3476942/149866182-97912742-1709-4fe2-bee4-fc2c0bc68922.png)
![image](https://user-images.githubusercontent.com/3476942/149866219-0064be05-607b-475a-944f-a9911212e67e.png)

## 💁 Possible Solution

I assume this is due to the optimization processes that occur during a production build, but I'm unable to understand what is causing the issue.

## 💻 Code Sample

How I'm using the url: pipeline in code:
```jsx
import searchIcon from 'url:../../images/search.svg';
```

How I'm running my build
```
yarn build
```
which corresponds to the package.json entry shown above.

All three images causing issues are used in this way.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.2.1
| Node             |14.18.0
| npm/Yarn         |1.22.15
| Operating System |Windows 10

**Comment by 101arrowz** [comment]
Known issue ATM, see https://parceljs.org/recipes/web-extension/#asset-urls. Will be fixed by #7050.
