### ISSUE TITLE
Combined scripts are not separated by ';'

### ISSUE THREAD

**Issue by janschoenherr** [parcel-bundler/parcel#7571]
# 🐛 bug report

At https://github.com/uikit/uikit/issues/4561 we have an open issue. 

```<!doctype html>
<html>
    <head>
        <script src="../node_modules/uikit/dist/js/uikit.min.js"></script>
    </head>
    <body></body>
</html>
```

This causes an exception: "uikit.min.js:1 Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(...) is not a function"

It seems that the Parcel's resulting index.HASH.js is not using a ';' to separate the combined scripts.

Is this a bug in Parcel or do we at UIkit need to fix this?

## 🎛 Configuration (package.json)

```js
{
  "dependencies": {
    "uikit": "3.10.0"
  },
  "devDependencies": {
    "@parcel/transformer-image": "2.0.0-rc.0",
    "@parcel/transformer-vue": "2.0.0-rc.0",
    "parcel": "^2.0.0-rc.0"
  },
  "scripts": {
    "start": "./node_modules/.bin/parcel serve src/index.html",
    "build": "./node_modules/.bin/parcel build src/index.html"
  }
}
```

## 🤔 Expected Behavior

No Error to be thrown.

## 💁 Possible Solution

Separate combined scripts by ';'

## 💻 Code Sample

This is the resulting code throwing the error.
```
},{}]},["glML1"], null, "parcelRequire8c16")
/*! UIkit 3.10.0 | https://www.getuikit.com | (c) 2014 - 2022 YOOtheme | MIT License */ (function(global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() : typeof define === 'function' && define.amd ? define('uikit', factory) : (global = typeof globalThis !== 'undefined' ? globalThis : global || self, global.UIkit = factory());
})(this, function() {
```

https://github.com/uikit/uikit/issues/4561
https://git.kaki87.net/playsearch.kaki87.net/v2-web/src/branch/master/package.json

**Comment by mischnic** [comment]
Seems to be fixed after upgrading to the latest version instead of 2.0.0-rc.0:
```json
  "devDependencies": {
    "@parcel/transformer-image": "2.2.1",
    "@parcel/transformer-vue": "2.2.1",
    "parcel": "2.2.1"
  },
```

**Comment by janschoenherr** [comment]
Thanks!

**Comment by KaKi87** [comment]
Oh, I didn't realized that the `@next` tag was no longer necessary.

Thanks, and sorry for the disturbance.
