### ISSUE TITLE
Configuration option to copy static files

### ISSUE THREAD

**Issue by sdavids** [parcel-bundler/parcel#7573]
# 🙋 feature request

Please provide a configuration option to copy static files during `parcel build`.

There are several commonly used static files belonging to a well-rounded website:

* robots.txt
* humans.txt
* sitemap.xml
* [.well-known](https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml) files
* favicon.ico

Currently only `favicon.ico` will be copied to the `dist` folder if you include `<link rel="icon" href="favicon.ico" type="image/x-icon"/>` in your HTML.

## 🤔 Expected Behavior

Static files are copied.

The files can be placed in another directory structure and an optional hash is added.

## 😯 Current Behavior

Static files are not copied unless they are referenced by the entry point.

A workaround is to include them via links:

```html
<a style="display: none" href="robots.txt"></a>
```

This does not scale well and it pollutes the HTML file.

Another workaround is to create a script copying the files over; caveats:

* the sub-directories from root have to be replicated 1:1 in `dist` and the files have to be copied accordingly
* the files cannot have a generated hash as part of their file name

Otherwise the links within the HTML, CSS, JS, etc. files would break.

### 1. file glob

`file glob` => Destination directory

#### Examples

rule: `asset/**/*.txt` => `""` (relative path); alternatively `"."` if `""` looks weird

`asset/a.txt` => `dist/asset/a.txt`; `<a href=asset/a.txt>`
`asset/a/b.txt` => `dist/asset/a/b.txt`; `<a href=asset/a/b.txt>`

rule: `asset/**/*.txt` => `"/"` (absolute URL path)

`asset/a.txt` => `dist/asset/a.txt`; `<a href=/asset/a.txt>`
`asset/a/b.txt` => `dist/asset/a/b.txt`; `<a href=/asset/a/b.txt>`

rule: `asset/**/*.txt` => `"x/y"` (relative URL path)

`asset/a.txt` => `dist/x/y/asset/a.txt`; `<a href=x/y/asset/a.txt>`
`asset/a/b.txt` => `dist/x/y/asset/a/b.txt`; `<a href=x/y/asset/a/b.txt>`

rule: `asset/**/*.txt` => `"x/y/"` (relative URL path)

`asset/a.txt` => `dist/x/y/asset/a.txt`; `<a href=x/y/asset/a.txt>`
`asset/a/b.txt` => `dist/x/y/asset/a/b.txt`; `<a href=x/y/asset/a/b.txt>`

rule: `asset/**/*.txt` => `"/x/y"` (absolute URL path)

`asset/a.txt` => `dist/x/y/asset/a.txt`; `<a href=/x/y/asset/a.txt>`
`asset/a/b.txt` => `dist/x/y/asset/a/b.txt`; `<a href=/x/y/asset/a/b.txt>`

Every rule could also have a `shouldHash` flag.

rule: `asset/**/*.txt` => `''` (relative path) and`"shouldHash": true`

`asset/a.txt` => `dist/asset/a.txt`; `<a href=asset/a.4a3e8342.txt>`
`asset/a/b.txt` => `dist/asset/a/b.txt`; `<a href=asset/a/b.7812d31b.txt>`

Also `stripPath`:

rule: `asset/**/*.txt` => `''` (relative path) and `"stripPath": true`

`asset/a.txt` => `dist/a.txt`; `<a href=a.txt>`
`asset/a/b.txt` => `dist/b.txt`; `<a href=b.txt>`
`asset/a/b/c.txt` => `dist/c.txt`; `<a href=c.txt>`

Also `stripPrefix`:

rule: `asset/**/*.txt` => `''` (relative path) and `"stripPrefix": "asset/"` -- implementation detail: are `"stripPrefix": "asset"` and `"stripPrefix": "asset/"` equivalent?

`asset/a.txt` => `dist/a.txt`; `<a href=a.txt>`
`asset/a/b.txt` => `dist/a/b.txt`; `<a href=a/b.txt>`

### Complete example

.parcelrc
```json
{
  "extends": "@parcel/config-default",
  "staticFiles": {
    "robots.txt": "",
    "meow.wav": "files",
    "src/sitemap.xml": {
      "destination": "",
      "stripPrefix": "src/"
    },
    "src/well-known/**/*": {
      "destination": ".well-known",
      "stripPath": true
    },
    "src/**/*.mp3": {
      "destination": "files",
      "stripPrefix": "src/",
      "shouldHash": true
    }
  }
}
```

With the input:

```
.
├── meow.wav
├── robots.txt
└── src
    ├── other
    │   └── pong.mp3
    ├── ping.mp3
    ├── sitemap.xml
    └── well-known
        ├── openid-configuration
        └── sub
            └── oauth-authorization-server
```

Output:

```
.
├── dist
│   ├── .well-known
│   │   ├── oauth-authorization-server
│   │   └── openid-configuration
│   ├── files
│   │   ├── meow.wav
│   │   ├── other
│   │   │   └── pong.fa3e834e.mp3
│   │   └── ping.181fd313.mp3
│   ├── robots.txt
│   └── sitemap.xml
├── meow.wav
├── robots.txt
└── src
    ├── other
    │   └── pong.mp3
    ├── ping.mp3
    ├── sitemap.xml
    └── well-known
        ├── openid-configuration
        └── sub
            └── oauth-authorization-server
```

#### 2. RegExp

Another option would be regular expressions with capture groups and substitutions.

Something along the lines:

`asset\/(.*)\.txt` => `styles/${1}.txt`

`asset/a.txt` => `dist/a.txt`; `<a href=a.txt>`
`asset/a/b.txt` => `dist/a/b.txt`; `<a href=a/b.txt>`
`asset/a/b/c.txt` => `dist/a/b/c.txt`; `<a href=a/b/c.txt>`

`asset\/?.*\/(.*)\.txt` => `styles/${1}.${hash}.txt`; `${hash}` is a pseudo key indicating that a hash is to be generated and added 

`asset/a.txt` => `dist/a.1a3c833e.txt`; `<a href=a.1a3c833e.txt>`
`asset/a/b.txt` => `dist/b.6183fdf13.txt`; `<a href=b.6183fdf13.txt>`
`asset/a/b/c.txt` => `dist/c.a13e2343.txt`; `<a href=c.a13e2343.txt>`

This would be quite powerful but unwieldy because of the need to escape `/` and `.` Also, not everyone is knowledgeable in regular expression crafting.

#### 3. Selectors

`(*)` = selector; only one allowed -- implementation detail: is a leading `/` discarded? -- `asset/(*).txt` vs. `asset(*).txt` => `/a` or `a`

`${all}` = all path segments
`${last}` = last path segment

Something along the lines:

`asset/(*).txt` => `styles/${all}.txt`

`asset/a.txt` => `dist/a.txt`; `<a href=a.txt>`
`asset/a/b.txt` => `dist/a/b.txt`; `<a href=a/b.txt>`
`asset/a/b/c.txt` => `dist/a/b/c.txt`; `<a href=a/b/c.txt>`

`asset/($).txt` => `styles/${last}.${hash}.txt`; `${hash}` is a pseudo key indicating that a hash is to be generated and added 

`asset/a.txt` => `dist/a.1a3c833e.txt`; `<a href=a.1a3c833e.txt>`
`asset/a/b.txt` => `dist/b.6183fdf13.txt`; `<a href=b.6183fdf13.txt>`
`asset/a/b/c.txt` => `dist/c.a13e2343.txt`; `<a href=c.a13e2343.txt>`

## 🔦 Context

#2099 had lots of activity but has been closed due to being stale.

At least 4 plugins of varying quality have been created:

* [parcel-plugin-custom-dist-structure](https://github.com/VladimirMikulic/parcel-plugin-custom-dist-structure)
* [parcel-plugin-structurize](https://github.com/samrith-s/parcel-plugin-structurize)
* [parcel-namer-rewrite](https://github.com/ol-loginov/parcel-namer-rewrite)
* [parcel-plugin-static-files-copy](https://www.npmjs.com/package/parcel-plugin-static-files-copy)

So there is a lot of demand for this feature in the community.

**Comment by devongovett** [comment]
It is possible to do, you just need to get it into the Parcel graph somehow. This can be done by either linking to the file from another file, or by adding it as an entry. For example:

```bash
parcel build src/index.html src/robots.txt
```

You just need to configure Parcel to handle the `.txt` file or whatever you need. You can do this in `.parcelrc`:

```json5
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.txt": ["@parcel/transformer-raw"]
  }
}
```

Now running the above command should output robots.txt in the dist directory.

The other feature being requested is to control the file naming. This is possible via [Namer](https://parceljs.org/plugin-system/namer/) plugins. You can either write some custom logic in a namer yourself, or use one that's already been built by the community. See [here](https://parceljs.org/plugin-browser/?type=%22namer%22&page=0&filter=%22%22&includeOfficial=false) for a bunch of available options.
