### ISSUE TITLE
The built in development server does not start when running the npx parcel src/index.html command

### ISSUE THREAD

**Issue by deejayjay** [parcel-bundler/parcel#7574]
I have installed parcel 2.2.1 to my project and I am trying to load the development server by running the npx parcel src/index.html command and it just creates .parcel-cache folder and files inside it, then does nothing. Please see file attached:

![image](https://user-images.githubusercontent.com/72120524/150069752-ab86a17a-23f1-4d50-b8b7-23a28afe0a3a.png)

**Comment by ulrokx** [comment]
This is happening to me too sporadically, tried reinstalling Node.js, installing package with yarn and npm, finally got it to work sometimes. It fails with error code 3221225477 when I run it with yarn. VSCode integrated terminal might be causing it as well. Made sure ignore-scripts was set to false when installing dependencies.

**Comment by sofianbello** [comment]
> This is happening to me too sporadically, tried reinstalling Node.js, installing package with yarn and npm, finally got it to work sometimes. It fails with error code 3221225477 when I run it with yarn. VSCode integrated terminal might be causing it as well. Made sure ignore-scripts was set to false when installing dependencies.

Yes I have the same Issue. I completely reinstalled VSCode, NodeJs and all dependencies but it didn't help. I also tried downgrading Parcel to earlier versions but nothing seemed to help. 

When I run `npx parcel src/index.html` in GitBash it throws out a segmentation fault message:
`/c/Program Files/nodejs/npx: line 45:  2104 Segmentation fault      "$NODE_EXE" "$NPX_CLI_JS" "$@"`

When trying to launch the server with GitBash I have a succesrate of 1/50 or even 1/100. 

Sometimes `npm cache verify` and `npm cache clean -f` seem to help but not often.

**Comment by jg185366** [comment]
I ran into this also and still haven't been able to build successfully. I downgraded to parcel 2.0.1 and ran `npm cache verify` and `npm cache clean -f` and still haven't had luck.

**Comment by devongovett** [comment]
Does it work without npx?

**Comment by sofianbello** [comment]
> Does it work without npx?

Unfortunately not. I installed parcel globally via `npm i -g parcel` and then ran `parcel src/index.html` with the same result. (Nothing)

Yesterday I even went ahead and reinstalled NodeJs (LTS and 17.4.0) via NVM but nothing worked.
I have also tried different Terminals (PowerShell 7, CMD, GitBash, VsCode Integrated Terminal) nothing seems to reliably fix the issue for me .

**Comment by dailypixie** [comment]
I am also getting a lot of segfaults and it works sporadically
/c/Program Files/nodejs/npm: line 44:  4006 Segmentation fault      "$NODE_EXE" "$NPM_CLI_JS" "$@"

**Comment by dailypixie** [comment]
I did a reinstall of npm and node, vscode. Nothing seems to work

**Comment by deejayjay** [comment]
> Does it work without npx?

No, it doesn't seem to work if I installed it globally either. There were a few rare occasions where the npx parcel src/index.html worked for me. But if I try running it again in like 10 seconds, it doesn't work.

**Comment by nshew13** [comment]
Windows 10 21H2 19044.1466, Node 16.13.2, npm 7.14.0, Parcel 2.2.1 and 2.0.1, GitBash/mintty 3.4.2 (also within VS Code)

The problem seems to affect both `start` and `build`. Both just die--silently in most cases or rarely with the segfault messaging. Commands fail when run using `npx`, as a `run`/`scripts` target and as `./node_modules/.bin/parcel build src/index.html`

It seems to die at different stages. Sometimes `.parcel-cache` is left with files that look like intermediate steps, sometimes with only `data.mdb` and `lock.mdb`, and rarely with the expected output.

`npm cache verify && npm cache clean -f` seem to help sometimes.

**Comment by djr319** [comment]
This is probably a duplicate for #7598, try the fix recommended

**Comment by jg185366** [comment]
> This is probably a duplicate for #7598, try the fix recommended

I can confirm that this fixed my issue.

1. Uninstall `parcel`
2. Remove the `@parcel/source-map` entry from `package-lock.json`
3. Re-install `parcel`

The `start` and `build` scripts now work as expected. Thank you!

**Comment by deejayjay** [comment]
@djr319: I removed parcel and reinstalled it and seems to work at my end now. Thank you so much for your help.
Thanks @devongovett for this fix :)

**Comment by reyemtm** [comment]
I seem to have something similar but with the normal `start` and `build` commands. They just fail silently with version 2.2.1. Version 2.0.0 works just fine, so something changed in between...

**Comment by deejayjay** [comment]
@reyemtm: Did you try the fix by @jg185366?

**Comment by reyemtm** [comment]
Yes, tried that. The only thing that worked for me was to downgrade to version 2.0.0. I am trying to build an app that has mapbox-gl, not sure if that matters.

**Comment by 2016lisali** [comment]
I ran into the same issue today, and fix it by deleting .parcel-cache folder

**Comment by Blackfyre360** [comment]
@2016lisali Cab you tell me how to delete .parcel-cache folder since on my one it won't delete. As soon as I delete it outside so it reappears agan when I open VS Code

**Comment by 2016lisali** [comment]
> @2016lisali Cab you tell me how to delete .parcel-cache folder since on my one it won't delete. As soon as I delete it outside so it reappears agan when I open VS Code
As the .parcel-cache is automatically generated by parcel, so it will appear again after being deleted.
However, delete/empty this folder can fix some parcel issues, like the parcel server does not start or the frontend UI not updated when changing CSS code.

**Comment by deejayjay** [comment]
@Blackfyre360 : In my case, I stopped the parcel server, deleted the folders mentioned above and then restarted the server. The folder gets recreated when the server is started.

**Comment by Serengia** [comment]
> 1. parcel

Worked for me too. Thanks.

**Comment by serengia** [comment]
> > This is probably a duplicate for #7598, try the fix recommended
> 
> I can confirm that this fixed my issue.
> 
> 1. Uninstall `parcel`
> 2. Remove the `@parcel/source-map` entry from `package-lock.json`
> 3. Re-install `parcel`
> 
> The `start` and `build` scripts now work as expected. Thank you!

Worked for me too. Thanks.

**Comment by michael-hamilton** [comment]
My workaround for this is deleting the `.parcel-cache` and `dist` directories, then running parcel again. It's annoying but less tedious than the other methods described here.

**Comment by Jay-Tillu** [comment]
> I ran into the same issue today, and fix it by deleting .parcel-cache folder

This worked for me thank you
