### ISSUE TITLE
import image with url scheme stopped working from nightly to stable

### ISSUE THREAD

**Issue by leny** [parcel-bundler/parcel#7577]
# 🐛 bug report

I had a project using parcel `2.0.0-nightly.587`, in which I had the following import:
```js
import bcgImage from "image:assets/bcg.jpg?as=webp&width=1920&quality=50";
```
which worked great without any issue.

Coming back on the project, I decided to upgrade parcel to `2.2.1`, and since the upgrade (no change on the code, only upgrading dependencies), my build is failing with the following messages:

- `@parcel/core: Failed to resolve '../assets/bcg.jpg?as=webp&width=1920&quality=50' from './src/containers/root.js'`
- `@parcel/resolver-default: Cannot load file '../assets/bcg.jpg?as=webp&width=1920&quality=50' in './src/containers'.`

Note: I already cleaned my node_modules, .parcel-cache & perform a "clean" install.

## 🎛 Configuration (.babelrc, package.json, cli command)

- `.babelrc`
```js
{
    "presets": [
        "@babel/preset-env",
        [
            "@babel/preset-react",
            {
                "runtime": "automatic"
            }
        ]
    ],
    "plugins": []
}
```

- `.parcelrc`
```js
{
    "extends": ["@parcel/config-default"],
    "transformers": {
        "*.{mp3,geojson,ogg}": ["@parcel/transformer-raw"]
    }
}
```

- `package.json`
```json
{
  "scripts": {
    "lint": "npx eslint --fix --cache src",
    "work": "npx parcel serve src/index.html",
    "build": "npx parcel build src/index.html"
  },
  "alias": {
    "assets": "./src/assets",
    "core": "./src/core",
    "hooks": "./src/core/hooks",
    "icons": "./src/assets/icons",
    "components": "./src/components",
    "containers": "./src/containers",
    "maps": "./src/data/maps",
    "sounds": "./src/assets/sounds",
    "store": "./src/store",
    "styles": "./src/styles"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@babel/eslint-parser": "^7.12.1",
    "@babel/preset-react": "^7.12.10",
    "@parcel/babel-preset-env": "~2.2.1",
    "@parcel/transformer-image": "~2.2.1",
    "@parcel/transformer-sass": "~2.2.1",
    "parcel": "~2.2.1",
    "postcss": "^8.2.6",
    "sass": "^1.32.5",
    "sharp": "^0.27.1"
  },
  "browserslist": [
    "since 2017-06"
  ]
}
```

## 🤔 Expected Behavior

It should not produce a compiling error when importing image with `url:` scheme.

## 😯 Current Behavior

When using an `url:` scheme pointing to an image in an import, as this:
```js
import bcgImage from "image:assets/bcg.jpg?as=webp&width=1920&quality=50";
```
it produce the following errors:

- `@parcel/core: Failed to resolve '../assets/bcg.jpg?as=webp&width=1920&quality=50' from './src/containers/root.js'`
- `@parcel/resolver-default: Cannot load file '../assets/bcg.jpg?as=webp&width=1920&quality=50' in './src/containers'.`

## 💁 Possible Solution

No idea, sorry. Was working in an (old) nightly, can't really find in documentation or changelog _when_ it changes.

## 💻 Code Sample

https://github.com/leny/enigjewo/tree/update-toolchain

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.2.1 |
| Node             | 14.16.1 |
| npm/Yarn         | 6.14.12 |
| Operating System | macOS Monterey 12.1 |

**Comment by devongovett** [comment]
I'm not sure that we ever supported an `image:` scheme, but perhaps you meant `url:`. That should still work but isn't necessary anymore. We also recommend using the `new URL` syntax for asset references now rather than import statements. See https://parceljs.org/languages/javascript/#url-dependencies

**Comment by leny** [comment]
Oh, yeah, sorry, it was `url:` (I've tested `image:` without success). With `url:`, it doesn't work.
