### ISSUE TITLE
incorrect `projectRoot` when using parcel in monorepo

### ISSUE THREAD

**Issue by oe** [parcel-bundler/parcel#7579]
# 🐛 bug report

I'm using lerna with yarn workspace just like you guys do.
When I run parcel within a sub package, it can't read the `.env` `.proxyrc.js` files inside the package, instead it reads them from the root  of repo.

After digging into the code, turns out that `projectRoot` was set incorrectly, and there is no way to specify its value. Here is the code in @parcel/core 

https://github.com/parcel-bundler/parcel/blob/v2/packages/core/core/src/resolveOptions.js#L52-L61

## 🎛 Configuration

with all  default Configurations

## 🤔 Expected Behavior

parcel can reads configurations  inside the sub package

## 😯 Current Behavior

parcel  reads configurations  from the root of repo

## 🔦 Context
possible solutions:
1. change parcel behavior in monorepo
2. add an option `--project-root`( `projectRoot` in API) to allow user to specify `projectRoot`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.2.1
| Node             | v16.9.1
| npm/Yarn         | yarn 1.22.11 / npm 7.21.1
| Operating System | macOS 12.1

**Comment by steve-taylor** [comment]
The documentation on monorepos is quite thin. It suggests that the only supported way to use Parcel in a monorepo is by running commands against the root. It would be nice to have some clarity around whether running Parcel inside individual packages is supported at all.

**Comment by chasewalden** [comment]
Agreed on adding or expanding on the monorepo documentation. It very briefly mentions that parcel ***can*** be run from the root by passing a glob, but not that it ***must***. 

If parcel is intended to be run from the root only, it should be mentioned somewhere. I hope this isn’t the case, however, as this effectively forces users to opt-out of other tools like Lerna or Turborepo, or even PNPM’s built in multi/recursive feature. 

For context: I’m working on converting one of my projects to a monorepo. Currently frontend and backend are in separate repos. The frontend is built with parcel, but backend is just tsc and turborepo. The apis are tRPC, so the frontend is devDependant on the backend. Both have some pipeline steps for build, lint, unit test, etc. There is also a third repo with some playwright e2e tests. 

At the moment, I can’t get pnpm, turborepo and parcel to play nicely this way. Maybe it’s actually a pnpm issue and yarn would work better, but turbo only supports yarn v1.

**Comment by jpapini** [comment]
Adding an empty `pnpm-lock.yaml` (or any lockfile) file to a subpackage of the monorepo fakes the `projectRoot` directory of Parcel.

**Comment by mischnic** [comment]
Note that Parcel doesn't watch anything outside the package root.
So moving it somewhere inside of the monorepo will not watch other packages you might import from the monorepo.

**Comment by kc97ble** [comment]
How about adding an option like `--env /path/to/.env` so that Parcel knows where to locate `.env` file?

Syntax like `parcel --env .env.production src/index.html` will be nice! Note that some projects might have more envs than `development` and `production`, for examples, `staging`, `test`.

Currently, I am adding an empty `yarn.lock` next to `package.json`. As mentioned above, with this setup, Parcel does not watch for changes from other packages in the monorepo.

**Comment by kc97ble** [comment]
A more robust workaround is to create a symbolic link:

**package.json**

```json
{
  ...
  "scripts": {
    "prepare-dot-env": "ln --force --symbolic ./packages/my-package/.env ../../.env",
    "build": "yarn run prepare-dot-env && parcel build src/index.html",
    "dev": "yarn run prepare-dot-env && parcel src/index.html"
  }
  ...
}
```

This workaround seems to work better than creating an empty lock file. The downside is that it pollutes the root folder.

**Comment by dminkovsky** [comment]
I have a similar issue, except with regards to TS (ie where Parcel looks for `tsconfig.json`). Without the empty lock files, when building a workspace, Parcel looks for a tsconfig in the root of the monorepo, not in the workspace that's being built. So without the workaround, each workspace can't have its own tsconfig.

**Comment by ianlet** [comment]
I would have to dig a little bit more but I think this issue is also affecting the [auto install](https://parceljs.org/features/development/#auto-install) feature of Parcel. At least when running Parcel using the `yarn workspace` command.

Let's say we have the following monorepo:
```
my-monorepo/
├── my-monorepo-web
│   ├── package.json
│   ├── public
│   ├── README.md
│   ├── src
│   └── tsconfig.json
├── package.json
├── README.md
└── yarn.lock
```
where `my-monorepo-web` is declared as the workspace `@my-monorepo/web`.

If I stay at the root of the repo to execute the following command:
```
yarn workspace @my-monorepo/web parcel build
```
and Parcel detects that it needs to install a missing dependency, it will add the dependency in the `package.json` at the root instead of the one in the `@my-monorepo/web`.

Note: I'm not using Lerna, just Yarn with its PnP feature.

**Comment by damianobarbati** [comment]
@ianlet did you manage to solve this? I'm having the same problem with latest parcel and pnpm: auto-install feature is adding packages to top-level package.json

**Comment by ianlet** [comment]
@damianobarbati I didn't manage to "properly" fix it. So for now I am not using the `yarn workspace ` commands and instead `cd` into the package directory.

You could try configuring the `projectRoot` in Parcel directly so it does not try to guess it or you could try [this workaround](https://github.com/elwin013/parcel-reporter-static-files-copy/issues/16#issuecomment-1657104463). There are also other workarounds listed [here](https://github.com/parcel-bundler/parcel/issues/7206).

**Comment by svaterlaus** [comment]
For anyone unsatisfied with the solutions offered so far, an easy fix for me is using [dotenv-cli](https://www.npmjs.com/package/dotenv-cli) and running Parcel like this:

```
dotenv -- parcel src/index.html --port 3001
```

It loads the environment variables from the nearest `.env` file instead of only from the monorepo root.
