### ISSUE TITLE
`parcel build` hangs on a random file

### ISSUE THREAD

**Issue by rjdellecese** [parcel-bundler/parcel#7585]
# 🐛 bug report

`parcel build` hangs, on a seemingly random file. My problem sounds identical to the one described in https://github.com/parcel-bundler/parcel/issues/6760. Passing the `--no-optimize` flag causes the build to succeed. I've also, through testing different configurations in my `.parcelrc`, discovered that removing the `@parcel/transformer-js` transformer allows the build to succeed, too (although the resulting build is unusable). `parcel serve` works fine.

My project comprises Elm and TypeScript (no `.js`, and literally one `.css` file with two lines, both of which are `@import`s).

## 🎛 Configuration

`package.json` excerpt

```json
{
  ...
  "engines": {
    "node": "^17.3.0"
  },
  "source": "src/index.html",
  "browserslist": "> 0.5%, last 2 versions, not dead",
  "pwaManifest": {
    ...
  },
  "devDependencies": {
    ...
    "@parcel/packager-raw-url": "^2.2.1",
    "@parcel/packager-xml": "^2.2.1",
    "@parcel/service-worker": "^2.2.1",
    "@parcel/transformer-elm": "^2.2.1",
    "elm": "latest-0.19.1",
    "parcel": "^2.2.1",
    "parcel-config-pwa-manifest": "^0.1.0",
    "typescript": "^4.5.4"
    ...
  },
  ...
}
```

`.parcelrc`

```json
{
  "extends": ["@parcel/config-default", "parcel-config-pwa-manifest"],
}
```

## 🤔 Expected Behavior

`parcel build` succeeds without incident.

## 😯 Current Behavior

`parcel build` hangs indefinitely on a random file.

https://user-images.githubusercontent.com/13547385/150435837-9f204470-961b-4a1f-9217-0c9ed1d5622c.mov

`parcel build --no-optimize` succeeds. `parcel serve` works fine.

## 🔦 Context

I just transitioned this project from Webpack 5. Everything has worked swimmingly, except for this!

## 💻 Code Sample

Unfortunately, the project in which I'm experiencing this issue is private, and I can't share the source code. I'm also not sure how to narrow the issue down any further than I have, but am more than willing to try if given suggestions on how!

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.2.1
| Node             | 17.3.0
| npm/Yarn         | 8.3.0
| Operating System | macOS Monterey 12.1

**Comment by mischnic** [comment]
> `parcel build` hangs indefinitely on a random file.
> `parcel build --no-optimize` succeeds. `parcel serve` works fine.


Does removing this line
https://github.com/parcel-bundler/parcel/blob/74fcc3fbe80cea993bff10e158df3d0f701973c7/packages/transformers/elm/src/ElmTransformer.js#L75

in `node_modules/@parcel/transformer-elm/lib/ElmTransformer.js` prevent the hanging? 
If yes, try to reduce the Elm code as much as possible so that you can share it.


> I'm also not sure how to narrow the issue down any further than I have 

Try removing these things:
- `parcel-config-pwa-manifest`
- Comment out the import to elm (so only build the TS & CSS parts)

**Comment by rjdellecese** [comment]
Thank you for your help @mischnic!

> Does removing this line ... in node_modules/@parcel/transformer-elm/lib/ElmTransformer.js prevent the hanging?

Removing that line causes the build to fail with an error!

```
❯ npx parcel build
🚨 Build failed.

@parcel/optimizer-terser: Undefined label scan

  /Users/rjdellecese/code/hab/web-app/node_modules/@lezer/common/dist/index.js:1392:34
    1391 |                     if (!cursor.parent())
  > 1392 |                         break scan;
  >      |                                  ^ Undefined label scan
    1393 |                     if (overlay && !--overlay.depth) {
    1394 |                         let ranges = punchRanges(this.ranges, overlay.ranges);

  💡 It's likely that Terser doesn't support this syntax yet.
```

Would it still be helpful to try to reduce the Elm code?

**Comment by rjdellecese** [comment]
I suppose that this is the line the error is referring to:

https://github.com/lezer-parser/common/blob/dffe4eda89fb46e6672eece613fdd0c9aeb7ad69/src/mix.ts#L183

`@lezer/common` is a dependency of my application via various CodeMirror modules, e.g. [@codemirror/language](https://github.com/codemirror/language)

**Comment by rjdellecese** [comment]
Let me know what else I can do here—happy to open an issue in another repo or do more testing/scope narrowing if that would be helpful. I've already tested with different Elm minification options by modifying the code in `node_modules/@parcel/transformer-elm/lib/ElmTransformer.js`, so far to no avail (I tried, for example, duplicating the Terser options I had been using via the Webpack plugin that I was previously using).

**Comment by mischnic** [comment]
1. Does 

> Comment out the import to elm (so only build the TS & CSS parts)

also result into the `@parcel/optimizer-terser` error?

2. Try to reduce the Elm code so that you can share it and we can reproduce the hanging. I'm not sure if this is a bug in Elm or Terser.

**Comment by rjdellecese** [comment]
> 1. Does
> 
> > Comment out the import to elm (so only build the TS & CSS parts)
> 
> also result into the `@parcel/optimizer-terser` error?

It looks like it does—the exact same error (I also deleted my `Main.elm` to make extra certain it wasn't being built).

**Comment by mischnic** [comment]
Then please also try to simplify the non-Elm parts so that you can share your code

**Comment by rjdellecese** [comment]
It seems to have to do with `@lezer/common` and the use of `"browserslist"`.

Here's a repo demonstrating the issue: https://github.com/rjdellecese/parcel-2-repro.

Let me know what else I can do!

**Comment by rjdellecese** [comment]
Actually, there might be more going on here, because just removing the `"browserslist"` entry from my `package.json` doesn't stop the build from hanging. But both removing the `"browserslist"` entry _and_ commenting out the Elm import does allow the build to complete successfully.

I'll keep investigating.

**Comment by mischnic** [comment]
👍  Perfect

Upstream swc issue for that terser/lezer problem: https://github.com/swc-project/swc/issues/3366
This was introduced recently when we enabled transpiling of node_modules

**Comment by rjdellecese** [comment]
I wasn’t having any luck isolating the issue any further, beyond that it had something to do with Terser minification. I also found mention of an issue with Terser on the Elm Discourse forum that matched exactly the description of the problem I was encountering, with no apparent resolution (https://discourse.elm-lang.org/t/ot-webpack-terser-build-issue/7606).

So I resolved the problem by forking the Elm transformer in Parcel and replacing Terser as the minifier with SWC (https://swc.rs/docs/configuration/minification), and everything has worked fine since.

At some point I might publish this on npm, but for now this plugin is just local to my project.

Thank you again for the help!

**Comment by balazs-lengyel** [comment]
@rjdellecese I'm having the same issue, thank you for narrowing it down. 
I haven't found your solution, so this is my first crude attempt (derived from your description): https://github.com/balazs-lengyel/parcel/commit/d92237b4b7a436273706fc6673279ace154fcda0 Do you have any suggestions for improvement?

>So I resolved the problem by forking the Elm transformer in Parcel and replacing Terser as the minifier with SWC (https://swc.rs/docs/configuration/minification), and everything has worked fine since.

**Comment by ARyaskov** [comment]
I'm experiencing the same Parcel 2.7.0 bug on building PNG files.
**Solution**: add **--log-level error** to **parcel build** command. 
It's weird I know.

**Comment by mzihlmann** [comment]
for me adding `--log-level error` only reduced the likelyhood, but did not fully fix the underlying issue.
