### ISSUE TITLE
JS file cannot import CoffeeScript file

### ISSUE THREAD

**Issue by provegard** [parcel-bundler/parcel#7591]
# 🐛 bug report

I'm trying to migrate from Parcel v1 to v2, and I'm hitting an issue with importing a CoffeeScript file from a JS file. The resolver cannot resolve the import.

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`:

```js
{
  "name": "parcel-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "parcel build --no-source-maps ./main.js --dist-dir ./dist"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@parcel/transformer-coffeescript": "^2.2.1",
    "parcel": "^2.2.1"
  }
}
```

## 🤔 Expected Behavior

Just like in Parcel v1, it should be possible to import a CoffeeScript file from a JS file.  I have:

`main.js`:

```
import "./other"
```

`other.coffee`:

```
console.log "imported"
```

## 😯 Current Behavior

I get an error:

```
@parcel/core: Failed to resolve './other' from './main.js'

  C:\kod\projects\parcel-crap\main.js:1:8
  > 1 | import "./other"
  >   |        ^^^^^^^^^

@parcel/resolver-default: Cannot load file './other' in './'.
ℹ Did you mean './other'?
```

## 🔦 Context

The issue prevents a migration from Parcel v1 to v2.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.2.1
| Node             | 16.4.1
| npm/Yarn         | npm 8.1.4
| Operating System | Windows 11

**Comment by mischnic** [comment]
You need to explicitly add the file extension. Only these ones are tested automatically: https://github.com/parcel-bundler/parcel/blob/74fcc3fbe80cea993bff10e158df3d0f701973c7/packages/resolvers/default/src/DefaultResolver.js#L25

**Comment by provegard** [comment]
Why does Parcel 2 care about the file extension? Parcel 1 didn't.
