### ISSUE TITLE
JSX automatic transform doesn't get used for 18+ prereleases

### ISSUE THREAD

**Issue by gaearon** [parcel-bundler/parcel#7595]
# 🐛 bug report

If you try using `react@next` or `react@experimental`, Parcel uses the old JSX transform, so it forces React to be in scope. But it should use the new one. Not sure how CRA is detecting it but it's worth aligning on the detection method IMO.

**Comment by mischnic** [comment]
There's an old WIP PR here: https://github.com/parcel-bundler/parcel/pull/6948
