### ISSUE TITLE
Parcel Build Crashes Due To Segmentation Faults

### ISSUE THREAD

**Issue by an0nusr** [parcel-bundler/parcel#7598]
# 🐛 bug report

When running Parcel 2.2.1, the build fails with one of several error messages:
  - `free(): invalid pointer`
  - `Segmentation fault`
  - `free(): double free detected in tcache 2`

All of these errors occurred running the exact same command (parcel build) one after the other with no changes to the code.

## 🎛 Configuration (.babelrc, package.json, cli command)

Package.json:

```js
{
  "name": "furryfont",
  "version": "1.0.0",
  "source": "index.html",
  "browserslist": "> 0.5%, last 2 versions, not dead",
  "author": "anonusr",
  "license": "AGPL-3.0-only",
  "scripts": {
    "start": "parcel",
    "build": "parcel build",
    "deploy": "echo 'furryfont.anonusr.org' > ./dist/CNAME && gh-pages -d dist"
  },
  "devDependencies": {
    "gh-pages": "^3.2.3",
    "parcel": "^2.2.0"
  }
}
```

## 🤔 Expected Behavior

Parcel does not crash.

## 😯 Current Behavior

Parcel crashes. Here is one of the possible errors:

```
yarn run v1.22.5
$ parcel build --log-level verbose
✨ Built in 1.27s

dist/index.html    5.13 KB    783ms
free(): double free detected in tcache 2
Aborted
```

## 💻 Code Sample

The issue is happening for me with this code here: https://github.com/an0nusr/furryfont/commit/7e279a691c8faeeaac536debf3557b1ec838322c

The code is pretty simple - there's no modules to bundle - just simple inline js in HTML.

**Note: the yarn lockfile in that commit was using Parcel 2.2.0 - the issue occurs in 2.2.1**

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.2.1 |
| Node             | v12.22.7 | 
| npm/Yarn         | yarn 1.22.5 |
| Operating System | Ubuntu 18.04 |

**Comment by provegard** [comment]
Related: #7590

**Comment by mischnic** [comment]
What version of `lmdb` is installed in your project? If you have 2.1.6 installed, try rolling back to 2.1.5 (e.g. via yarn resolutions)

**Comment by jdanyow** [comment]
@mischnic we've tried with lmdb 2.1.6 and 2.1.5.

Linking some dupes: #7590 #7603

**Comment by an0nusr** [comment]
@mischnic - manually setting the lmdb version to 2.1.5 does not appear to have an effect, I still see a `free(): invalid pointer` error when running `parcel build`.

**Comment by jdanyow** [comment]
Confirming both git bash and powershell, on the following windows versions:
```
Win 10: 2022-01 Cumulative Update for Windows 10 Version 21H2 for x64-based Systems (KB5010793)
Win 11 - 22000.434
```

**Comment by devongovett** [comment]
Does it work for anyone if you set the `PARCEL_WORKER_BACKEND=process` environment variable?

**Comment by devongovett** [comment]
I think we narrowed this down to an upgrade of napi-rs in the `@parcel/source-map` package, which was released sometime after Parcel 2.2.1. I still don't know the exact root cause, but for now I've reverted this upgrade and published `@parcel/source-map` v2.0.2. See https://github.com/parcel-bundler/source-map/pull/91.

You'll need to remove `@parcel/source-map` 2.0.1 from your lock file and re-install to get the upgrade. Please comment whether this works for you. Apologies again for the issue, and thanks for your patience while we track it down.

**Comment by dailypixie** [comment]
I works on my side with 2.1.1. Purging and updating to 2.2.1.
It works with 2.2.1. 
I noticed a minor issue, pressing CTRL+C does not automatically close the process, you have to press multiple times.

**Comment by jg185366** [comment]
> You'll need to remove `@parcel/source-map` 2.0.1 from your lock file and re-install to get the upgrade.

This worked for me. Thanks!

**Comment by maxackerman** [comment]
Using the latest Parcel `v2.3.1` I'm running into segmentation fault errors on my local machine and when deploying to Netlify.

Here is a stripped down example that has been consistently causing errors: https://github.com/maxackerman/deploy-test

node: `v17.0.1`

I just tried PARCEL_WORKER_BACKEND=process and that does seem to work as a temp fix!

**Comment by LeoniePhiline** [comment]
This is again the case with NodeJS 22.7.

The breakage occurs when upgrading https://hub.docker.com/r/amd64/node from 22.6.0-alpine to 22.7.0-alpine

Edit: I see, that's https://github.com/parcel-bundler/parcel/issues/9926
