### ISSUE TITLE
try bundle with vue: 'import' and 'export' may only appear at the top level

### ISSUE THREAD

**Issue by MrNewWorld** [parcel-bundler/parcel#760]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
a 🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc
```js
{
  "presets": [
    ["es2015"]
  ]
}
```

### 🤔 Expected Behavior
Build pass

### 😯 Current Behavior
Not passed

### 💁 Possible Solution
Maybe because of babel?

### 🔦 Context
I'm using parcel + vue-compiler with vue single file temeplate

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.51
| Node             |9.6.0
| npm/Yarn         |5.3.0
| Operating System |windows10

**Comment by lllllllqw** [comment]
I also got this error.
`parcel-plugin-vue` is installed, but in my `app.vue` , it throws `'import' and 'export' may only appear at the   top level`

**Comment by limitedeternity** [comment]
Same thing. My .babelrc is: 

![screenshot_2](https://user-images.githubusercontent.com/24318966/36121354-ef5ecaaa-1056-11e8-944f-bf33eca49b86.png)

**Comment by limitedeternity** [comment]
Solved. Successfully built.
![screenshot_1](https://user-images.githubusercontent.com/24318966/36157856-d807d956-10eb-11e8-8e21-f9d8526fd683.png)

**Comment by wtfuii** [comment]
@limitedeternity Plain Text would have been nice for quick copy/paste. ;)

**Comment by limitedeternity** [comment]
@wtfuii 

```json
.babelrc:

{
  "presets": [
    "env",
    "stage-0"
  ],
  "plugins": [
    "transform-vue-jsx",
    "transform-runtime",
    "syntax-dynamic-import"
  ]
}
```

**Comment by DeMoorJasper** [comment]
Seems to be a misconfigured babel
