### ISSUE TITLE
Unable to use Parcel (Windows x64)

### ISSUE THREAD

**Issue by djr319** [parcel-bundler/parcel#7603]
### Discussed in https://github.com/parcel-bundler/parcel/discussions/7593

- Parcel 2.2.1 

** Expected Behavior **
Running `npx parcel ./src/index.html` to launch dev server.

** Actual Behavior**
Running `npx parcel ./src/index.html` usually does nothing. A slight pause on the terminal before returning a new prompt. On rare occasion, the dev server has started, but when closed with Ctrl-C and restarted, fails. 

Edit: With Yarn: Command failed with exit code 3221225477

** Environment **
- Windows 10  (19043) x64
- Node v16.13.2 x64 (and v14 also failed)
- Launch via powershell in VS Code terminal (non-admin account, also tried with admin privileges)

**Comment by aochagavia** [comment]
Same here

**Comment by escline** [comment]
I'm having the same issue.
I created the most basic parcel example at https://github.com/escline/basic_parcel_test

1. clone repo
2. npm install
3. npx parcel src/index.html

If I try `npx parcel src/index.html` over and over, every once in a while it will start. But when it doesn't, there is no error response.

Edit: I forgot to include my environment.

- Windows 10 Home  x64 (21H2 - 19044.1466)
- Node v14.18.1
- Tried Windows cmd shell, Windows Powershell, and cmder

**Comment by jdanyow** [comment]
A few folks on my team can repro the `Command failed with exit code 3221225477` issue- if there's a way we can help, please ping me.

With npm:
![image](https://user-images.githubusercontent.com/1306747/150840162-aceb1d8e-2c6b-4270-895a-9d4116a67698.png)


With yarn:
![image](https://user-images.githubusercontent.com/1306747/150839601-f8a5d5ed-fbb0-4cf0-a46d-90bf169799d7.png)

**Comment by josephshen** [comment]
Got same problem. 
Maybe there are some problems related to Windows Update 21H2, after install the Feature update 21H2 yesterday evening, I got this strange problem today right after I reboot my computer, and same source code, same node\npm\parcel version, work fine on Ubuntu 21.10

**Comment by josephshen** [comment]
confirmed this, same source code, same node\npm\parcel version, work fine on Ubuntu 21.10

**Comment by devongovett** [comment]
Does it work for anyone if you set the `PARCEL_WORKER_BACKEND=process` environment variable?

**Comment by josephshen** [comment]
> 

set this flag still get the problem

**Comment by josephshen** [comment]
> Does it work for anyone if you set the `PARCEL_WORKER_BACKEND=process` environment variable?

![image](https://user-images.githubusercontent.com/2016010/151134957-c00a7def-0576-424a-b337-2a8fdfe3a64d.png)

set this flag fix the `free() invalid pointer` on my Ubuntu

**Comment by josephshen** [comment]
after remove dist node_module and package-lock.json and a clean npm install, unset PARCEL_WORKER_BACKEND, this bug did not happen.

![image](https://user-images.githubusercontent.com/2016010/151136141-11b9115c-108c-4881-a2a1-44936e30aa03.png)


so maybe it's a parcel depends bug?

**Comment by cbmek** [comment]
I did help me!

With this setting: `$env:PARCEL_WORKER_BACKEND="threads"` it doesn't work almost every time
With this setting: `$env:PARCEL_WORKER_BACKEND="process"` it does work every time

**Comment by devongovett** [comment]
I think we narrowed this down to an upgrade of napi-rs in the `@parcel/source-map` package, which was released sometime after Parcel 2.2.1. I still don't know the exact root cause, but for now I've reverted this upgrade and published `@parcel/source-map` v2.0.2. See https://github.com/parcel-bundler/source-map/pull/91.

You'll need to remove `@parcel/source-map` 2.0.1 from your lock file and re-install to get the upgrade. Please comment whether this works for you. Apologies again for the issue, and thanks for your patience while we track it down.

**Comment by djr319** [comment]
Thank you Devon, v2.2.1 working reliably. Closing the thread. Good job.

**Comment by MylesWardell** [comment]
> $env:PARCEL_WORKER_BACKEND="process"

I am still experiencing this issue and this fixed it for me. Whenever I ran parcel it was inconsistantly starting up the server or just closing the script. 

Below solved my issue

```powershell
nvm use $(Get-Content .nvmrc)
$env:NODE_ENV = 'mockapi'
$env:PARCEL_WORKER_BACKEND="process"
parcel src/index-web.html --lazy
```
