### ISSUE TITLE
Parcel build failing at Cannot load file '../parcel_sourcemap_wasm after attempted fix to segfault error

### ISSUE THREAD

**Issue by david-abell** [parcel-bundler/parcel#7619]
# 🐛 bug report

When running parcel start and build commands, build fails with error:
```
@parcel/core: Failed to resolve '../parcel_sourcemap_wasm/dist-web/parcel_sourcemap_wasm.js' from
'./node_modules/@parcel/source-map/dist/wasm-bindings-web.js'
```
## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`
```js
  "devDependencies": {
    "eslint": "^8.2.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.25.2",
    "eslint-plugin-prettier": "^4.0.0",
    "parcel": "^2.2.1",
    "parcel-transformer-html-datasrc": "^1.3.0",
    "prettier": "^2.5.1",
    "segfault-handler": "^1.3.0"
  }
```
`.parcelrc`
```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.html": [
      "parcel-transformer-html-datasrc",
      "..."
    ]
  }
}

```
package-lock.json source-map version
```
    "node_modules/@parcel/source-map": {
      "version": "2.0.2",
      "resolved": "https://registry.npmjs.org/@parcel/source-map/-/source-map-2.0.2.tgz",
      "integrity": "sha512-NnUrPYLpYB6qyx2v6bcRPn/gVigmGG6M6xL8wIg/i0dP1GLkuY1nf+Hqdf63FzPTqqT7K3k6eE5yHPQVMO5jcA==",
      "dev": true,
      "dependencies": {
        "detect-libc": "^1.0.3"
      },
      "engines": {
        "node": "^12.18.3 || >=14"
      }
    },

```

## 😯 Current Behavior

error to console:
```
🚨 Build failed.

@parcel/core: Failed to resolve '../parcel_sourcemap_wasm/dist-web/parcel_sourcemap_wasm.js' from
'./node_modules/@parcel/source-map/dist/wasm-bindings-web.js'

  C:\Users\neodi\Documents\HTML\JZ Carpentry\jzcarpentryvt\node_modules\@parcel\source-map\dist\wasm-bindings-web.js:19:62
    18 |
  > 19 | var _parcel_sourcemap_wasm = _interopRequireWildcard(require("../parcel_sourcemap_wasm/dist-web/parcel_sourcemap_wasm.js"));
  >    |                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    20 |
    21 | function _getRequireWildcardCache(nodeInterop) { if (typeof WeakMap !== "function") return null; var cacheBabelInterop = new WeakMap(); var cacheN
@parcel/resolver-default: Cannot load file '../parcel_sourcemap_wasm/dist-web/parcel_sourcemap_wasm.js' in './node_modules/@parcel/source-map/dist'.
```

## 🔦 Context

Issue began with segfault errors. Attempted fix as suggested in issue #7590 :
 - uninstall parcel, 
 - delete `@parcel/source-map` in package-lock.json (lines shown above in configuration) as suggested in [devongovett's suggestion in issue #7590](https://github.com/parcel-bundler/parcel/issues/7590#issuecomment-1022818556)
 - reinstall parcel
  
  Second attempt:
 - uninstall parcel,
 - force package-lock rebuild by renaming

## 💻 Code Sample

Repository is currently private

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.2.1
| Node             | v16.11.1
| npm/Yarn         | 8.0.0
| Operating System | windows 10 21H1

**Comment by devongovett** [comment]
I'm not sure how you are getting the wasm bindings. That should only happen if you are building for the browser. Are you trying to bundle parcel itself?

**Comment by david-abell** [comment]
Sorry if I didn't make it clear, the project is indeed being built for the browser. It is a simple static website. 

### I was able to resolve the issue this morning after giving it a weekend break.
I had not been uninstalling the plugin parcel-transformer-html-datasrc while attempting the parcel update and that was keeping some old parcel dependencies in the `package-lock.json`

Both the missing wasm issue and segfault errors have been fixed by doing a full uninstall of parcel as well as the installed plugin, then reinstalling both. When in doubt, turn it off and back on again still hold true.
- Thanks for looking at this issue. I believe it should be ok to close.
