### ISSUE TITLE
Improvement to dead code elimination

### ISSUE THREAD

**Issue by nickname76** [parcel-bundler/parcel#7627]
# 🙋 feature request

Parcel does great job, I'm asking to make it greater!

## 🤔 Expected Behavior

Removal of unused code (dead code), and producing following:
```js
console.log(1)
//# sourceMappingURL=index.js.map
```

## 😯 Current Behavior

Parcel produces following build:
```js
(()=>{console.log(1);let s="asdsda";s="asdasdsdasdasd"})();
//# sourceMappingURL=index.js.map
```

## 💁 Possible Solution

I have an idea of code graph, in which you can find parts that affect needed nodes (states, variables, objects, classes, functions, storages), like network socket, page content, local storage, their children (that does affect them) etc., and remove everything that is not affecting any needed nodes (their graphs).

## 🔦 Context

index.ts (entrypoint)
```ts
import govno from './govno'

console.log(1)

let a = 'asdsda'

let b = govno(a)

a = b
```

govno.ts
```ts
export default function(a: any) {
    a = 'asdasdsd'
    let b = a + 'asdasd'
    return b
}
```

## 💻 Examples

Just imagine this, but out of code.

![image](https://user-images.githubusercontent.com/41116859/151772076-9f2bd60a-9063-461a-8199-004776c02ce2.png)

Code graphs may be separated from each other, so graphs with needed code (that includes needed nodes) and graphs with dead code (that does not include needed nodes) may be detected very efficiently.

In case of Parcel, needed nodes can be statically defined, for example stdout (console.log), tcp/tls/http/https socket (fetch function), browser document object (web page content), etc.

**Comment by nickname76** [comment]
More examples

![image](https://user-images.githubusercontent.com/41116859/151776464-47756eee-a1cb-4e6c-bf57-0d457b3dcf5a.png)

I think the same thing can also help to restructure code to more efficient

**Comment by mischnic** [comment]
This optimization isn't done by Parcel itself but instead it uses Terser. You can test that by pasting the code from "current behaviour" here: https://try.terser.org/.

I've opened https://github.com/terser/terser/issues/1162
