### ISSUE TITLE
🐛 Cannot use font-awesome 4 CSS in HTML

### ISSUE THREAD

**Issue by sant123** [parcel-bundler/parcel#763]
**Choose one:** 🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

package.json

```js
{
  "name": "testing-parcel",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "start": "parcel src/index.html -d dev",
    "build": "parcel build src/index.html -d dist --public-url ./",
    "clean": "rimraf .cache dev dist"
  },
  "dependencies": {
    "bulma": "^0.6.2",
    "font-awesome": "^4.7.0",
    "moment": "^2.20.1",
    "parcel-bundler": "^1.5.1",
    "rimraf": "^2.6.2"
  }
}

```

### 🤔 Expected Behavior

In index.html when I import font-awesome it should load in the page.

```html
<link rel="stylesheet" href="../node_modules/font-awesome/css/font-awesome.css">
```

### 😯 Current Behavior

It show this error.

![image](https://user-images.githubusercontent.com/7959437/35934780-7e511d5c-0c0c-11e8-95ab-023ff4969ca4.png)

### 🔦 Context

Font-awesome is present in all parts of the webpage, that's why is imported in index.html

### 💻 Code Sample

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Testing parcel</title>
    <link rel="stylesheet" href="../node_modules/bulma/css/bulma.css">
    <link rel="stylesheet" href="../node_modules/font-awesome/css/font-awesome.css">
</head>
<body>
    <div id="root"></div>
    <script src="./js/main.js"></script>
</body>
</html>
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.5.1
| Node             |9.4.0
| npm/Yarn         |1.3.2
| Operating System |Windows 10

¡Thank you!

**Comment by mischnic** [comment]
This works fine with Parcel 1.11.0 (but even works if I install `parcel-bundler@1.5.1` ?):
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="../node_modules/font-awesome/css/font-awesome.css">
</head>
<body>
	<i class="fa fa-address-book"></i>
</body>
</html>
```

**Comment by sant123** [comment]
Interesting, I'm testing this in a Linux machine and works perfectly! @gabalicious are you in Windows? Maybe the problem is related in that OS.

**Comment by gabalicious** [comment]
@sant123  Mac

**Comment by gabalicious** [comment]
| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.12.3
| Node             | 10.16.3
| npm/Yarn         |6.9.0/1.17.3
| Operating System | Mac OS Catalina 10.15 Beta
