### ISSUE TITLE
No bundles produced when using the `source` option in a target to override the entry source

### ISSUE THREAD

**Issue by pastelsky** [parcel-bundler/parcel#7647]
# 🐛 bug report

When trying to use Parcel's API to build a very basic project with a custom target with a source like so —
```js
let bundler = new Parcel({
  entries: path.join(__dirname, "..", "project", "index.js"),
  defaultConfig: require.resolve("@parcel/config-default"),
  targets: {
    targetA: {
      distDir: path.join(__dirname, "..", 'project', 'dist'),
      source: path.join(__dirname, "..", 'project', 'index.js'), // Custom source — should work according to docs, but results in no bundles
    }
  }
});
```

See this reproduction repo for example —
https://github.com/pastelsky/parcel-issue-7647

As soon as the `source` field is removed from the target, the bundle gets produced normally.

## 🎛 Configuration (.babelrc, package.json, cli command)
N. A.

## 🤔 Expected Behavior
`targetA` results in the source being read and a bundle being output in `distDir`

## 😯 Current Behavior
The bundler produces no bundles at all.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |   2.0.0 | 
| Node             | 16.13.1 | 
| npm/Yarn         | 1.22 | 
| Operating System | Mac OS |

**Comment by pastelsky** [comment]
Hi @devongovett, are there any hints you could provide that'd help me debug this? Happy to submit a fix if I get some pointers.

**Comment by selul** [comment]
I'm facing a similar issue but I'm not sure if this is a bug or the API does not support this kind of behavior. My goal was to assign different targets per entry. 

Any help would be amazing.

**Comment by joostliketoast** [comment]
I am running into the same issue, i am trying to create multiple targets for serverless functions that each have their own source file.

**Comment by vdawg-git** [comment]
I had the same problem. Removing `targets` with the `source`-key from the `package.json` and passing the entries manually to the `parcel api` fixed this for me.
And thank you for creating this issue, I dont know how long it would have taken me to get around this without it :D

**Comment by mischnic** [comment]
See https://github.com/parcel-bundler/parcel/issues/8684
