### ISSUE TITLE
`_fsDefault.default.readFileSync is not a function` and file inlining

### ISSUE THREAD

**Issue by mathieucaroff** [parcel-bundler/parcel#7649]
# 🐛 bug report

The error happens both with the `serve` and `build` subcommands of parcel

## 💻 Code Sample

The code producing the bug is the following:

`ChangelogSection.tsx`
```ts
import fs from 'fs'

const markdownContent = fs.readFileSync(__dirname + '../CHANGELOG.md', 'utf-8')
```

## 🤔 Expected Behavior

The text file should be inlined in the bundle.

## 😯 Current Behavior

An error is raised:

```txt
Uncaught TypeError: _fsDefault.default.readFileSync is not a function
    anonymous page.a0256dfc.js line 911 > Function:23
    newRequire page.a0256dfc.js:71
    hmrAcceptRun runtime-ff8aa029182e6a79.js:456
    onmessage runtime-ff8aa029182e6a79.js:135
    dHHfE runtime-ff8aa029182e6a79.js:97
    newRequire page.a0256dfc.js:71
    <anonymous> page.a0256dfc.js:122
    <anonymous> page.a0256dfc.js:145
```

## 💁 Possible Solution

Load the file using the `bundle-text` named-pipe, like this:

```
// @ts-ignore
import markdownContent from "bundle-text:../CHANGELOG.md";
```

Note: this will add `"@parcel/transformer-inline-string": "^2.2.1"` to your devDependencies (if I'm right)

Please note that the documentation still endorse the use of `fs.readFileSync`, see: https://parceljs.org/features/bundle-inlining/#inlining-without-transforming

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.2.1 |
| Node             | Node.js v16.13.2 |
| Yarn         | v1.22.15 |

**Comment by mathieucaroff** [comment]
~~Weirdly, I have other places in the same project where fs.readFileSync inlines text files correctly.~~
`fs.readFileSync`  stops working whenever the project is built on Linux.

**Comment by danieltroger** [comment]
@mathieucaroff have you kept in mind that bundle-text resolves paths relative to the current file while fs.readFileSync resolves paths relative to your project root? (folder containing package.json)

Usually this is the error you get if it can't find the file

**Comment by danieltroger** [comment]
At least I think so. Usually I just do /src/myfile.ts in fs.readFileSync so I don't have to think

**Comment by mathieucaroff** [comment]
@danieltroger you are right! adding a slash before `..` to the string parameter solves the issue on Linux. Thus
```
fs.readFileSync(__dirname + '/../CHANGELOG.md', 'utf-8')
```
makes the project work on Linux as well. Thanks!

**Comment by juanmirocks** [comment]
AFAIK, in Parcel 2, the currently recommend way to read a file as literal, plain text is using the [`bundle-text:` scheme](https://parceljs.org/features/bundle-inlining/#inlining-a-bundle-as-text), as in:

```javascript
import text from 'bundle-text:./myFile';
console.log(text);
```
