### ISSUE TITLE
Source map location error

### ISSUE THREAD

**Issue by eco747** [parcel-bundler/parcel#7655]
Parcel 2 / typescript 4.5 / windows 10

multiline comments between methods in a class are not taken in account in the generated .map file

example 1:

```ts
// initial code
class MyClass {
	test( ) {
		debugger;                              //<<<< debugger stops here : normal
		console.log( 'here' );
	}
}

const t = new MyClass( );
t.test( );
```

```ts
// new code
class MyClass {
        /*
         * I have just added these
         * lines of comment.
         * chrome will stop far away from the correct position
         * this is due to a bad file mapping. (from js to ts)
         */

	test( ) {
		debugger;                              
		console.log( 'here' );
	}
}

const t = new MyClass( );  //<<<< debugger stops here : abnormal
t.test( );
```

```ts
// BUT
class MyClass {
        // with these single line comments
        // everything is ok

	test( ) {
		debugger;         //<<<< debugger stops here : normal                     
		console.log( 'here' );
	}
}

const t = new MyClass( );  
t.test( );
```

[demo.zip](https://github.com/parcel-bundler/parcel/files/8003801/demo.zip)

Thanks
Etienne

**Comment by eco747** [comment]
finally, It seems that all ml comments are problematic... everywhere in sources not only between methods

**Comment by mischnic** [comment]
I just tried the reproduction and it appears to be working fine with Parcel 2.2.1

**Comment by zealvurte** [comment]
I'm using parcel 2.6.2 and it happens. 🤷‍♂️ I don't have anything I can contribute to a reproducible test case though.

**Comment by Duckers** [comment]
Using Parcel 2.6.0 and it is still broken.

However, a work-around can be found here: https://www.npmjs.com/package/parcel-transformer-tsc-sourcemaps

**Comment by mischnic** [comment]
PR to fix this: https://github.com/parcel-bundler/parcel/pull/8734
