### ISSUE TITLE
Parcel build handles css calc() in unexpected manner

### ISSUE THREAD

**Issue by david-abell** [parcel-bundler/parcel#7659]
# 🐛 bug report

Running the parcel build script, can mutate css output depending on what contents are in css calc() parentheses.

## 🎛 Configuration (.babelrc, package.json, cli command)

cli command `npm run build`

`package.json`

```js
{
  "name": "...",
  "version": "1.0.0",
  "description": "...",
  "default": "./src/index.html",
  "scripts": {
    "start": "parcel src/index.html",
    "build": "parcel build src/index.html"
  },
  "author": "David Abell",
  "license": "ISC",
  "dependencies": {
    "bigpicture": "^2.6.1",
    "email-validator": "^2.0.4",
    "lozad": "^1.16.0",
    "wicg-inert": "^3.1.1"
  },
  "devDependencies": {
    "eslint": "^8.2.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.25.2",
    "eslint-plugin-prettier": "^4.0.0",
    "parcel": "^2.2.1",
    "parcel-transformer-html-datasrc": "^1.3.3",
    "prettier": "^2.5.1",
    "stylelint": "^14.3.0",
    "stylelint-config-prettier": "^9.0.3",
    "stylelint-config-standard": "^24.0.0"
  }
}
```
`.parcelrc`
```
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.html": [
      "parcel-transformer-html-datasrc",
      "..."
    ]
  }
}
```
`.eslintrc`
```
{
  "env": {
    "browser": true,
    "es2021": true
  },
  "extends": ["airbnb-base/legacy", "plugin:prettier/recommended", "prettier"],
  "parserOptions": {
    "ecmaVersion": "latest",
    "sourceType": "module"
  },
  "rules": {}
}
```
`.stylelintrc`
```
{
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-prettier"
  ]
}
```
## 🤔 Expected Behavior

When building for web, calc() should remain part of css such as:

```
:root {
  --test1: calc((100vw - var(--spacer-max-width)) / 2);
  --test2: calc((3 * var(--spacer-max-width) + 2));
  --test3: calc((var(--spacer-max-width) + 2 * 3));
  --test4: calc(var(--spacer-max-width) + 2 * 3);
  --test5: calc((var(--spacer-max-width) + 2));
  --test6: calc((var(--spacer) * 3));
  --test7: calc((var(--spacer) * 3.00));
}
```
## 😯 Current Behavior

resulting css file after cli `npm run build`

```
:root {
  --test1: calc((100vw - var(--spacer-max-width)) / 2);
  --test2: calc(var(--spacer-max-width) * 3 + 2);
  --test3: (var(--spacer-max-width) + 2 * 3);
  --test4: calc(var(--spacer-max-width) + 6);
  --test5: (var(--spacer-max-width) + 2);
  --test6: (var(--spacer) * 3);
  --test7: (var(--spacer) * 3);


}
```
- Note test 3, test 5 and test 6 have completely removed the calc() function. 
- test 2 reorders the integers but does not perform any math
- test 4 keeps the calc but performs math on the integers
- Linters did not catch or highlight the extra parenthesis wrapping the contents of the calc functions
- I'd be happy to have suggestions to updating linting settings if this should be fixed that way.

## 🔦 Context

I'm in no way an expert on this processing so I've no idea if this should be processing the calc() or more generally css property values or if everything should be passed through as a string in some situations without processing. I discovered this when a deployed build to netlify was not rendering spacing properly because the website (basic html, css, and js) depends on css variables in root for its spacing.

Like the above test cases, the live code snippet had extra parenthesis, probably added by vscode filling var(--spacer) inside the var statement and I just didn't notice them when deleting the extra var. They built as test cases 3,5,and 6 above, missing the calc function and showed as undefined variables when inspected with dev tools on the deployed site.

## 💻 Code Sample

repo is private but I can probably put something together if needed.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.2.1
| Node             | v16.11.1
| npm/Yarn         | npm 8.0.0
| Operating System | windows 10 19043

**Comment by mischnic** [comment]
Appears to be fixed with 2.6.0
