### ISSUE TITLE
Support generating a UMD bundle

### ISSUE THREAD

**Issue by ntomsic** [parcel-bundler/parcel#766]
**Choose one:** feature request?

Right now, parcel is used for compiling code to be used for a frontend server. There's no way to create a named library that you can use drop in a `<script src='...'>` tag and call via `myLibrary.Foo()`. Both rollup and webpack allow you to specify a config similar to

``` 
output: {
    file: 'dist/styled-components.js',
    format: 'umd',
    name: 'styled',
    exports: 'named',
}
```

It would be awesome if parcel supported something similar and wasn't strictly for server/html code.

**Comment by danawoodman** [comment]
I too would be able to use Parcel more if this was supported. It is equivalent to WebPack's `output.library` option.

**Comment by devongovett** [comment]
Related: https://github.com/parcel-bundler/parcel/pull/453

**Comment by willin** [comment]
It is also equivalent to Rollup's output.format option.

https://rollupjs.org/guide/en#command-line-flags

- -f, --output.format [es]    Type of output (amd, cjs, es, iife, umd)
- -n, --name                  Name for UMD export

**Comment by devongovett** [comment]
Fixed by #453. Modules are now exposed to CommonJS and AMD automatically, and if you specify a `--global <name>` flag, as a global variable.

**Comment by willin** [comment]
UMD...

**Comment by OfficialYoungX** [comment]
> Fixed by #453. Modules are now exposed to CommonJS and AMD automatically, and if you specify a `--global <name>` flag, as a global variable.

This work for me, but there sames no way to expose `myvariable` on the globle `window`.

**Comment by mischnic** [comment]
You cannot use ESM exports for that. `module.exports = ...` would make it available as `mylib`.

**Comment by niieani** [comment]
@devongovett is UMD still supported in Parcel 2? I see no mention of it in the docs - should we re-open this issue? Thanks! 🙇

**Comment by danmarshall** [comment]
@niieani - I'm not sure why this is not in V2, but here is my workaround:
```js
window['MyGlobalName'] = myGlobalVar;
```

**Comment by zhaoyao91** [comment]
> @niieani - I'm not sure why this is not in V2, but here is my workaround:
> 
> ```js
> window['MyGlobalName'] = myGlobalVar;
> ```

Need umd/iife format in v2
it is expected to bundle all dependencies into the final bundle expect the native node modules.
I guess your workaround won't handle the dependencies bundling problem.
