### ISSUE TITLE
Vue 3 runtime template compilation works in watch mode but crashes in build mode

### ISSUE THREAD

**Issue by joppuyo** [parcel-bundler/parcel#7663]
# 🐛 bug report

I'm trying to build a simple app with Vue 3 and Parcel 2. It works just fine when running in development mode `parcel watch` but if I run it in production mode `parcel build` the application crashes. It seems like there's an issue with Vue runtime template compilation.

### package.json

```js
{
  "name": "vue-3-parcel",
  "version": "1.0.0",
  "description": "",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "parcel": "^2.2.1",
    "vue": "^3.2.29"
  },
  "devDependencies": {
    "@parcel/transformer-vue": "^2.2.1",
    "@vue/compiler-sfc": "^3.2.29"
  },
  "alias": {
    "vue": "./node_modules/vue/dist/vue.esm-bundler.js"
  },
  "scripts": {
    "watch": "parcel watch ./src/script.js",
    "build": "parcel build ./src/script.js"
  }
}
```

## 🤔 Expected Behavior

App should work both when running parcel with `parcel watch ./src/script.js` and `parcel build ./src/script.js`.

## 😯 Current Behavior

App runs fine when running it with `parcel watch ./src/script.js`.

But if I run it with `parcel build ./src/script.js`, it crashes with the following error:

```
vue.esm-bundler.js:61 Uncaught ReferenceError: $77f1d4e004f07613$import$4f81359071792c76 is not defined
    at xr (vue.esm-bundler.js:61:47)
    at Tr (runtime-core.esm-bundler.js:7553:29)
    at runtime-core.esm-bundler.js:7408:2
    at Or (runtime-core.esm-bundler.js:7353:2)
    at R (runtime-core.esm-bundler.js:5079:39)
    at L (runtime-core.esm-bundler.js:5070:17)
    at g (runtime-core.esm-bundler.js:4628:34)
    at X (runtime-core.esm-bundler.js:5772:13)
    at mount (runtime-core.esm-bundler.js:3970:21)
    at Object.t.mount (runtime-dom.esm-bundler.js:1617:12)
```

The errors seems to be pointing to [this line](https://github.com/vuejs/core/blob/6b6889852f247a91df4793ad37e8e2e1d27c79b3/packages/vue/src/index.ts#L78) in Vue where `$77f1d4e004f07613$import$4f81359071792c76` is `runtimeDom`

## 💁 Possible Solution

–

## 🔦 Context

–

## 💻 Code Sample

Simple reproduction [here](https://github.com/joppuyo/vue-3-parcel).

### index.html

```html
<!DOCTYPE html>

<html lang="en">

<head>
    <title></title>
    <script type="module" src="./dist/script.js"></script>
</head>

<body>
<div class="js-vue">
    <my-vue-app></my-vue-app>
</div>
</body>

</html>
```

### src/App.vue

```vue
<template>
  <div>
    Hello World!
  </div>
</template>

<script>
export default {}
</script>
```

### src/script.js

```js
import {createApp} from 'vue';
import App from './App.vue';

document.addEventListener('DOMContentLoaded', () => {
    const appRoots = document.querySelectorAll('.js-vue');

    for (const root of appRoots) {
        const app = createApp({
            components: {
                'my-vue-app': App,
            },
        });
        app.mount(root);
    }
})


```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.2.1
| Node             | 16.13.2
| npm/Yarn         | npm 8.4.1
| Operating System | Mac

**Comment by joppuyo** [comment]
The app works with `build` command if I change the `vue` alias in `package.json` to `./node_modules/vue/dist/vue.esm-browser.js` but this way I will need to manually change the file to `./node_modules/vue/dist/vue.esm-browser.prod.js` when building for production. [As described here](https://v3.vuejs.org/guide/installation.html#explanation-of-different-builds) the browser bundlers are not really meant to be consumed by a bundler like Parcel.

**Comment by npulidom** [comment]
Same here, using production runtime build `vue.runtime.esm-browser.prod.js`, the js bundle executes without runtime errors. 

**Package.json**
```json
"alias": {
    "vue": "./node_modules/vue/dist/vue.runtime.esm-browser.prod.js"
}
```

**Comment by Jengamon** [comment]
I used
```json
"alias": {
    "vue": "vue/dist/vue.esm-bundler.js"
}
```
 and it worked.

**Note**: See [this](https://github.com/vuejs/core/tree/main/packages/vue#with-a-bundler). Pointing it to "vue.runtime.*" actually *prevents* runtime compilation (all templates must be pre-built), which is what I assume is going on here.
