### ISSUE TITLE
Comments break source maps in TypeScript

### ISSUE THREAD

**Issue by smoli** [parcel-bundler/parcel#7664]
# 🐛 bug report

I have a simple project with no parcel config using TypeScript and vue. Having a comment in a ts file breaks the sourcemaps and the line mapping is wrong.

Repository that consistently reproduces the behavior: [https://github.com/smoli/parcelSourceMapError](https://github.com/smoli/parcelSourceMapError)

* Just run parcel. (npm start)
* Open the webpage
* Click one of the buttons.
* In console, click on the source-location for the "DEBUG!" output
--> The output is associated with the wrong line number.

![image](https://user-images.githubusercontent.com/1009634/152745936-ae074f47-0912-4c98-9061-5f1cdd303d41.png)

Tested on Chrome 97 and Firefox 96

Turning off HMR does not help.

This is so simple to reproduce, I might do something wrong?

## 🎛 Configuration (.babelrc, package.json, cli command)

There is no config, neither for parcel nor for ts.

Find a repository here, that reproduces the problem: [https://github.com/smoli/parcelSourceMapError](https://github.com/smoli/parcelSourceMapError)

package.json
```js
{
  "name": "parcelSourceMaps",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "start": "parcel ./src/index.html",
    "startNoHMR": "parcel ./src/index.html --no-hmr"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "vue": "^3.2.29",
    "vuex": "^4.0.2"
  },
  "devDependencies": {
    "@parcel/transformer-vue": "^2.2.1",
    "parcel": "^2.2.1"
  }
}
```

## 🤔 Expected Behavior

Lines given on console output should match the source position where the console-statement was issued. This translates to break points and debugger statements.

## 😯 Current Behavior

Source lines are offset when comments are present in the file.

## 💁 Possible Solution

See comment below

## 🔦 Context

Makes debugging in large projects impossible.

## 💻 Code Sample

[https://github.com/smoli/parcelSourceMapError](https://github.com/smoli/parcelSourceMapError)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.2.1 
| Node             |  16.13.2
| npm/Yarn         |  npm 8.1.2
| Operating System | Win10

**Comment by smoli** [comment]
I found a fix by using 

[parcel-transformer-tsc-sourcemaps](https://www.npmjs.com/package/parcel-transformer-tsc-sourcemapsl)

and setting `removeComments: true` in `tsconfig.json`

See branch [fixedbyremovingcomments](https://github.com/smoli/parcelSourceMapError/tree/fixedbyremovingcomments) in the demo project.

As I understand it this fix should be preliminary as parcel-transformer-tsc-sourcemaps is preliminary to mitigate #7570

Maybe this gives some more insight into the problem. Seems as if comments might be considered twice when creating the sourcemaps.

Thanks to @iSplasher and @ImpendingDoom28

**Comment by eco747** [comment]
idem #7655
