### ISSUE TITLE
Parcel-Build: `@parcel/transformer-image: The image transformer does not support PNG images.`

### ISSUE THREAD

**Issue by Luna-Klatzer** [parcel-bundler/parcel#7665]
# 🐛 bug report

When using `@parcel/transformer-image` I am currently encountering this error reporting missing support for PNG images, despite the docs specifying there is proper support for PNG images.

## 🎛 Configuration (.babelrc, package.json, cli command)

- Command: `parcel build src/index.html --public-url {{ env.URL }} --dist-dir .`
- [package.json](https://gist.githubusercontent.com/Luna-Klatzer/1a099c115498fbdf01a6c4a749ceb2d5/raw/e18ebecb7b409c72c6a1a5d7b7b89f24acbb9c0d/package.json)
- [package-lock.json](https://gist.githubusercontent.com/Luna-Klatzer/c5d109f6f9f3e5002546cc1f758f1ee3/raw/da3906e529d03ada979b74eecf037442640501da/package-lock.json)

## 🤔 Expected Behavior

Parcel should build the files successfully, without reporting any unsupported image errors.

## 😯 Current Behavior

I am receiving the following output when trying to build my files: 

```bash
@parcel/transformer-image: The image transformer does not support PNG images.

  Error: The image transformer does not support PNG images.
  at Object.transform
  (/home/runner/work/Go-Healthy/Go-Healthy/node_modules/@parcel/transformer-image/lib/ImageTransformer.js:76:13)
  at Transformation.runTransformer
  (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/Transformation.js:627:23)
  at Transformation.runPipeline
  (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/Transformation.js:376:47)
  at Transformation.runPipelines
  (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/Transformation.js:253:51)
  at async Transformation.run
  (/usr/local/lib/node_modules/parcel/node_modules/@parcel/core/lib/Transformation.js:173:21)
  at async Child.handleRequest
  (/usr/local/lib/node_modules/parcel/node_modules/@parcel/workers/lib/child.js:217:9)
```

## 🔦 Context

[GitHub Actions file, which should successfully build the files](https://github.com/WMC-AHIF-2021/Go-Healthy/runs/5092049186?check_suite_focus=true)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.1.1 |
| Node             | 16.13.1 |
| npm/Yarn         | 8.1.2 |
| Operating System | Linux Ubuntu  20.04.3 |

**Comment by Luna-Klatzer** [comment]
Update: I was able to fix the issue when renaming some invalid file-endings from `.PNG` to `.png`. 

So as it's resolved for me, I will close this issue now, but will still leave my solution here for anyone with the same error :)

**Comment by salihah-rilvan** [comment]
I am facing a similar problem but with JPG. 
This is what I saw: @parcel/transformer-image: The image transformer does not support JPG images.
I am still facing this issue when I renamed the file extension from .JPG to .jpg. 
How can I go about solving this issue?

**Comment by NikolaM4** [comment]
> Update: I was able to fix the issue when renaming some invalid file-endings `.PNG` to `.png`. So as it's resolved for me I will close this issue, but leave my solution here for anyone with the same error.

Thank you! This helped me too.

**Comment by cyberadityacode** [comment]
Parcel converts static files to a URL. If the import is failing, try: 

`const imageUrl = new URL('./assets/aditya.jpg', import.meta.url);`

It works fine with png, avif or any other image MIME types
