### ISSUE TITLE
Error when building project with TypeScript definition output

### ISSUE THREAD

**Issue by alex-ketch** [parcel-bundler/parcel#7668]
# 🐛 bug report

I am unable to build a TypeScript project, targeting consumption from both JS and TS projects.
My impression is that the error seems to be with the `transformer-typescript-types`, as the project builds successfully when not attempting to build the type definitions.

Issue appears in the latest `nightly` release of Parcel, and the TypeScript related transformers.
The stable release does not seem to have this problem, however in my actual project I need to use the nightly release as otherwise I was facing this bug: https://github.com/parcel-bundler/parcel/issues/6815

Thanks for your time, and let me know if I can provide any more information.

## 🎛 Configuration (.babelrc, package.json, cli command)

**`package.json`**
```js
{
  "name": "parcel-types-debug",
  "version": "1.0.0",
  "description": "",
  "source": "src/index.ts",
  "main": "dist/index.js",
  "module": "dist/index.mjs",
  "types": "dist/types.d.ts",
  "scripts": {
    "build": "parcel build"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "@parcel/transformer-typescript-tsc": "^2.0.0-nightly.993",
    "@parcel/transformer-typescript-types": "^2.0.0-nightly.993",
    "parcel": "^2.0.0-nightly.991",
    "typescript": "^4.5.5"
  }
}
```

**`tsconfig.json`**

```json
{
  "compilerOptions": {
    "strict": true
  },
  "include": ["src"]
}

```

## 🤔 Expected Behavior

Library is built, and TypeScript type definitions generated.

## 😯 Current Behavior

Both generation of JS files, as well as of TypeScript definitions fails.

```sh
🚨 Build failed.

Error: mod[method] is not a function

  TypeError: mod[method] is not a function
  at WorkerFarm.processRequest
  (/Users/ketch/Developer/Stencila/parcelDebug/node_modules/@parcel/workers/lib/WorkerFarm.js:336:55)
  at Worker.<anonymous>
  (/Users/ketch/Developer/Stencila/parcelDebug/node_modules/@parcel/workers/lib/WorkerFarm.js:233:39)
  at Worker.emit (node:events:390:28)
  at Worker.receive
  (/Users/ketch/Developer/Stencila/parcelDebug/node_modules/@parcel/workers/lib/Worker.js:177:12)
  at ThreadsWorker.onMessage
  (/Users/ketch/Developer/Stencila/parcelDebug/node_modules/@parcel/workers/lib/Worker.js:98:64)
  at ThreadsWorker.handleMessage
  (/Users/ketch/Developer/Stencila/parcelDebug/node_modules/@parcel/workers/lib/threads/ThreadsWorker.js:70:10)
  at Worker.<anonymous>
  (/Users/ketch/Developer/Stencila/parcelDebug/node_modules/@parcel/workers/lib/threads/ThreadsWorker.js:55:44)
  at Worker.emit (node:events:390:28)
  at MessagePort.<anonymous> (node:internal/worker:232:53)
  at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)

```

## 💁 Possible Solution

Removing `"types": "dist/types.d.ts"` from the `package.json` allows the JS portion of the build to succeed, but then no TypeScript definitions are generated.

No combination of `declaration` or `emitDeclarationOnly` in the `tsconfig.json` had any impact on the build error.

## 🔦 Context

This bug makes it impossible to build and distribute a library package for consumption via TypeScript.

## 💻 Code Sample

Reproduction repo: https://github.com/alex-ketch/parcel-ts-debug

Running `npm run build` in the above repository should fail and display the error.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.991 |
| Node             | 16.13.0 |
| npm/Yarn         | NPM v8.1.0 |
| Operating System | macOS 12.2 |

**Comment by Pi-Bouf** [comment]
Try to use the latest version of Parcel, not a nightly !

**Comment by lukjaki** [comment]
Hi All, 

I have the same issue with `"parcel": "^2.3.0`

**Comment by alex-ketch** [comment]
The latest release v2.3.1 seems to have fixed this specific issue, but still encountering other problems building TypeScript in our project. Those are tracked by:
- `node.exportClause.elements is not iterable`: https://github.com/parcel-bundler/parcel/issues/5911
- `parcel/transformer-typescript-types: Got unexpected undefined`: https://github.com/parcel-bundler/parcel/issues/7669
