### ISSUE TITLE
Files in parent directories are not watched

### ISSUE THREAD

**Issue by sephii** [parcel-bundler/parcel#7673]
# 🐛 bug report

The `serve` and `watch` commands seem to only watch files and directories that are at the same level or below the directory of the project's `package.json` file.

[This repository](https://github.com/sephii/parcel-bug) shows the bug. The frontend parts of the project are isolated in a specific directory, and the templates that should be watched for changes are in a parent directory. Running `parcel build` works correctly, but `parcel serve` or `parcel watch` fail to detect any changes to the templates.

## 🎛 Configuration (.babelrc, package.json, cli command)

Everything is in the repository: https://github.com/sephii/parcel-bug

## 🤔 Expected Behavior

The CSS gets recompiled when the HTML files change. It would be nice if there was an option to add directories to watch for changes.

## 😯 Current Behavior

Parcel doesn’t recompile the CSS when the HTML files change.

## 🔦 Context

I’m trying to get Parcel to generate a CSS file with Tailwind classes without an HTML entry point (the HTML is generated on the backend, and I just want to include the CSS/JS in it).

## 💻 Code Sample

https://github.com/sephii/parcel-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.1
| Node             | 14.8.3
| npm/Yarn         | 6.14.15
| Operating System | NixOS (Linux)

**Comment by devongovett** [comment]
Same issue as #4332. Parcel does not currently watch any files outside the project root.
