### ISSUE TITLE
Parcel with Semantic Ui and Jquery building error

### ISSUE THREAD

**Issue by AlexisPister** [parcel-bundler/parcel#7679]
I have a project with Semantic Ui, Jquery and Parcel, which work well when I use npm run dev, but unfortunately I can't seem to make the building process work..

Here is my project structure : 

```
Project/
  index.html
  dist/
  src/
  semantic/
  semantic.json
  package.json
```

src/ contain all my js and css files, while semantic/ contains the semantic-ui distribution.

In index.html, I import first Jquery (https://stackoverflow.com/questions/47968529/how-do-i-use-jquery-and-jquery-ui-with-parcel-bundler), then Semantic Ui and finally my main.js file. In my mind this process should make Jquery and Semantic available in all my project ?

```
<script type="module">
        const jquery = require("jquery");
        window.$ = window.jQuery = jquery;
</script>
<link rel="stylesheet" type="text/css" href="./semantic/dist/semantic.min.css">
<script src="./semantic/dist/semantic.min.js"></script>
<script type="module" src="./src/js/main.js"></script>
```

It works well for development, but when I open my dist folder after the building process I get the following errors :

Uncaught ReferenceError: jQuery is not defined
    at index.303ccd9f.js:1:6163

and then 

Uncaught (in promise) TypeError: $(...).slider is not a function
    at cJ.setupConfigMenu (index.d08bc02d.js:24:1245545)
    at new cJ (index.d08bc02d.js:24:1245084)
    at index.d08bc02d.js:24:1248494
    at index.d08bc02d.js:24:1248611

So I have several questions :

1. Am I importing the dependencies right ? For what I understand, you can either import a package in a js file with the import keyword to make it available in the current file, or import it in the html to make it available in all the project, but it does not seem to work for production here
2. Why does my process work in development but not in production ? Am I importing things wrongly or is there a problem with Parcel and these dependencies ?

My package.json file :

```
{
  "name": "visualqueries",
  "version": "1.0.0",
  "scripts": {
    "test": "cypress open",
    "dev": "parcel index.html && parcel watch index.html",
    "build": "parcel build index.html",
    "parcel-version": "parcel --version"
  },
  "author": "Alexis Pister",
  "license": "ISC",
  "dependencies": {
    "autoprefixer": "^10.4.2",
    "canvas-lasso": "^1.0.0",
    "codemirror": "^5.61.0",
    "cypher-compiler-js": "git+ssh://git@gitlab.inria.fr/fekete/cypher-compiler-js.git",
    "d3": "^6.7.0",
    "d3-context-menu": "^2.1.0",
    "d3-sankey": "^0.12.3",
    "datatables.net": "^1.10.24",
    "datatables.net-autofill": "^2.3.9",
    "datatables.net-autofill-dt": "^2.3.9",
    "datatables.net-buttons": "^1.7.0",
    "datatables.net-buttons-dt": "^1.7.1",
    "datatables.net-dt": "^1.10.25",
    "dyngraph": "^0.0.2",
    "fomantic-ui": "^2.8.8",
    "html2canvas": "^1.1.4",
    "jquery": "^3.6.0",
    "jquery-confirm": "^3.3.4",
    "jszip": "^3.6.0",
    "leaflet": "^1.7.1",
    "lodash": "^4.17.21",
    "pdfmake": "^0.1.71",
    "postcss": "^8.4.5",
    "regenerator-runtime": "^0.13.7",
    "sortablejs": "^1.13.0",
    "stream": "^0.0.2",
    "update": "^0.4.2",
    "vega": "^5.20.2",
    "vega-embed": "^5.1.3",
    "vega-lite": "^5.1.1",
    "vega-lite-api": "^5.0.0",
    "world-atlas": "^2.0.2"
  },
  "devDependencies": {
    "@babel/preset-env": "^7.13.8",
    "@parcel/transformer-image": "^2.0.0-rc.0",
    "@types/npm": "^7.19.0",
    "@visdesignlab/trrack": "^2.0.0-alpha.10",
    "chance": "^1.1.7",
    "parcel": "^2.0.0-rc.0"
  }
}
```

I am stuck on this since several weeks and would really appreciate some help
Thanks

**Comment by mischnic** [comment]
> Am I importing the dependencies right ? For what I understand, you can either import a package in a js file with the import keyword to make it available in the current file, or import it in the html to make it available in all the project, but it does not seem to work for production here

No, this is not the case generally. Some packages might be setup for this, but not all. You generally always be using `import`.
