### ISSUE TITLE
parcel 2.3.0 build error

### ISSUE THREAD

**Issue by suhaotian** [parcel-bundler/parcel#7684]
# 🐛 bug report

![2022-02-10 at 10 15 AM](https://user-images.githubusercontent.com/6512574/153324282-4f66029c-4deb-482d-9c6d-595c99d6f0b2.png)

## 🎛 Configuration (.babelrc, package.json, cli command)

```
yarn build
```

## 💻 Code Sample

https://github.com/suhaotian/parcel-starter/tree/parcel-2.3.0

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.3.0
| Node             | 16.2.3
| npm/Yarn         | yarn
| Operating System | Mac OS

**Comment by jordaaash** [comment]
I ran into this issue as well. What was the cause / solution?

**Comment by suhaotian** [comment]
it's not error, just warning @jordansexton
