### ISSUE TITLE
Bundle size doubles compares to webpack

### ISSUE THREAD

**Issue by fellmann** [parcel-bundler/parcel#7691]
# 🐛 bug report

When bundling a simple js file that imports mobx and keycloak-js, the bundle size doubles, compared to webpack.

## 🎛 Configuration (.babelrc, package.json, cli command)

I have boiled the problem down to a minimal working example: https://github.com/fellmann/parcel2-webpack-demo

## 🤔 Expected Behavior

The bundle size should be roughly the same as the webpack generated bundle. Also, mobx should not change its bundle size when keycloak-js is added.

## 😯 Current Behavior

As soon as keycloak-js is imported on top of mobx, the bundle size doubles. 

## 💁 Possible Solution

-

## 🔦 Context

This might affect all frontend apps that use keycloak-js.

## 💻 Code Sample

https://github.com/fellmann/parcel2-webpack-demo

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.2.1 |
| Node             |  16.13.2  |
| Operating System | Win 10 64bit |

**Comment by mischnic** [comment]
This is caused by these evals: https://github.com/emn178/js-sha256/blob/189bb9b03782b80e59516dfbea78f16b5d9754ce/src/sha256.js#L84 (so this is not caused by keycloak itself but its dependency `js-sha256`)
which deopts Terser into not being able to minify variable names.
