### ISSUE TITLE
Code splitting creating duplicate files

### ISSUE THREAD

**Issue by azan-n** [parcel-bundler/parcel#7695]
# 🐛 bug report
I'm building a static website with plain HTML, SCSS, and JS complemented by Bootstrap. After build, I get two JS files `pricing.[hash].js` and `products.[hash].js` with size ~510kB.

On running `diff dist/products.ac35ec81.js dist/pricing.4efb29bf.js` we get the following diff which suggests the files are the same only with a difference in mapping file.
```diff
145c145
< })({"3hU5K":[function(require,module,exports) {
---
> })({"hhR8g":[function(require,module,exports) {
151c151
< module.bundle.HMR_BUNDLE_ID = "c9d8b443ac35ec81";
---
> module.bundle.HMR_BUNDLE_ID = "a579f2b54efb29bf";
1297c1297
< },{"axios":"esNlu","./plan-data":"k73Wf","75f74036bca4dc5a":"7M3Q2","7f78da0f068cb556":"jAx47","@parcel/transformer-js/src/esmodule-helpers.js":"d3obN","bootstrap":"kyoAg"}],"esNlu":[function(require,module,exports) {
---
> },{"axios":"esNlu","./plan-data":"k73Wf","75f74036bca4dc5a":"4HIDx","7f78da0f068cb556":"VvJ40","@parcel/transformer-js/src/esmodule-helpers.js":"d3obN","bootstrap":"kyoAg"}],"esNlu":[function(require,module,exports) {
5124,5125c5124,5125
< },{"@parcel/transformer-js/src/esmodule-helpers.js":"d3obN"}],"7M3Q2":[function(require,module,exports) {
< module.exports = require('./helpers/bundle-url').getBundleURL('hkqiz') + "images/tick.591c3578.svg" + "?" + Date.now();
---
> },{"@parcel/transformer-js/src/esmodule-helpers.js":"d3obN"}],"4HIDx":[function(require,module,exports) {
> module.exports = require('./helpers/bundle-url').getBundleURL('ecPg8') + "images/tick.591c3578.svg" + "?" + Date.now();
5162,5163c5162,5163
< },{}],"jAx47":[function(require,module,exports) {
< module.exports = require('./helpers/bundle-url').getBundleURL('hkqiz') + "images/cross.ce6e51f2.svg" + "?" + Date.now();
---
> },{}],"VvJ40":[function(require,module,exports) {
> module.exports = require('./helpers/bundle-url').getBundleURL('ecPg8') + "images/cross.ce6e51f2.svg" + "?" + Date.now();
11880c11880
< },{"./createPopper.js":"jxVuD","./modifiers/eventListeners.js":"hEHwP","./modifiers/popperOffsets.js":"46vzi","./modifiers/computeStyles.js":"dPTLS","./modifiers/applyStyles.js":"2dG18","@parcel/transformer-js/src/esmodule-helpers.js":"d3obN"}]},["3hU5K","am2u4"], "am2u4", "parcelRequiref610")
---
> },{"./createPopper.js":"jxVuD","./modifiers/eventListeners.js":"hEHwP","./modifiers/popperOffsets.js":"46vzi","./modifiers/computeStyles.js":"dPTLS","./modifiers/applyStyles.js":"2dG18","@parcel/transformer-js/src/esmodule-helpers.js":"d3obN"}]},["hhR8g","am2u4"], "am2u4", "parcelRequiref610")
11882c11882
< //# sourceMappingURL=products.ac35ec81.js.map
---
> //# sourceMappingURL=pricing.4efb29bf.js.map
```

These files furthermore are not being tree-shaked (if that is a word), as I notice bootstrap features like Modals, jQuery fallbacks, carousels, being packaged into the file. Regardless, what is more problematic is that I am essentially serving the same file twice.

On adding the following lines in `package.json`, I get a total of 4 smaller JS files ranging from 2-200kB. 
```json
  "@parcel/bundler-default": {
    "minBundles": 1,
    "minBundleSize": 300,
    "maxParallelRequests": 25
  }
```
I would however in this case much rather serve just one JS file sized ~500kB which would mean having to turn off code-splitting. Surprisingly, any value for `minBundleSize` other than 300 has been giving me the same results as before.

## 🎛 Configuration (.babelrc, package.json, cli command)

Have not defined a .babelrc explicitly. I believe the configurations given below are unrelated to the bug, but I will write them down anyway.

.posthtmlrc:
```json
{
    "plugins": {
        "posthtml-highlight": {
            "inline": true
        }
    }
}
```

.postcssrc:
```json
{
  "plugins": {
    "@fullhuman/postcss-purgecss": {
      "content": [
        "**/*.js",
        "**/*.html"
      ],
      "variables": true,
      "fontFace": true,
      "rejected": true,
      "safelist": [
        "tooltip",
        "tooltip-inner",
        "bs-tooltip-start",
        "bs-tooltip-end",
        "bs-tooltip-top",
        "bs-tooltip-bottom",
        "bs-tooltip-auto"
      ]
    }
  }
}
```

.parcelrc:
```json
{
	"extends": "@parcel/config-default",
	"namers": [
		"@mischnic/parcel-namer-preserve-structure",
		"..."
	]
}
```

command:
`parcel build`

## 🤔 Expected Behavior

If code is not being split, it should not be duplicated.

## 😯 Current Behavior

Code is being duplicated. I have no good way to control code splitting.

## 🔦 Context

I am trying to build a simple website with HTML, SCSS, and vanilla JS. I want it to be extremely fast for all devices, hence the low build-size. The total size of the site (including assets) will go from 1.4MB to ~900kB if the duplication in code is removed.

## 💻 Code Sample

I have yet to try reproducing the issue.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.2.1
| Node             | 16.13.0
| npm/Yarn         | 8.1.4
| Operating System | Ubuntu 20.04.3 LTS

**Comment by tpudel** [comment]
Having a very similar issue, have you found a solution yet?
