### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by obidnov** [parcel-bundler/parcel#77]
Hello, i started an empty project from the manual.
>node -v
v8.9.1

>parcel index.html
Server running at http://localhost:1234
⏳  Building index.html...
(node:18412) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): RangeError: Maximum call stack size exceeded
(node:18412) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

So i have messages and 1234 port is not binded (i do not use 1234 for anything).

Could anybody help me with it please?

**Comment by hearsay316** [comment]
You can update version 1.3

**Comment by thejameskyle** [comment]
I'm assuming this is the same Windows issue that was fixed in v1.0.3. See #11.

Also, please be sure to [search for existing issues](https://github.com/parcel-bundler/parcel/issues?utf8=%E2%9C%93&q=Maximum+call+stack+size+exceeded) before creating a new one
