### ISSUE TITLE
Alias (excluding React & ReactDOM) doesn't work in Parcel v2.3.1

### ISSUE THREAD

**Issue by contactjavas** [parcel-bundler/parcel#7700]
# 🐛 bug report

(I'm not sure if this is similar with #7677 but let me post this since my use-case seems more general)

In our case, we need to exclude React & ReactDOM from the build. This is because WordPress already provides a global `React` & `ReactDOM`. In `version <= 2.2.1`, the build process respects the alias set in _package.json_ file. So that the bundle doesn't contain React & ReactDOM.

After upgrading to `v2.3.1`, React & ReactDOM are both included in the bundle 😢 What I can do is just report this issue and go back to `v2.2.1` or switch back to webpack as the temporary solution.

### package.json

```json
{
    "name": "control-react-colorful",
    "version": "1.0.13",
    "description": "Development toolkit for Kirki's control-react-colorful",
    "repository": {
        "type": "git",
        "url": "git+https://github.com/kirki-framework/control-react-colorful.git"
    },
    "keywords": [
        "kirki-react-colorful"
    ],
    "author": "Kirki Framework",
    "license": "MIT",
    "bugs": {
        "url": "https://github.com/kirki-framework/control-react-colorful/issues"
    },
    "homepage": "https://github.com/kirki-framework/control-react-colorful#readme",
    "dependencies": {
        "colord": "^2.9.2",
        "react": "^17.0.2",
        "react-colorful": "^5.5.1",
        "react-dom": "^17.0.2",
        "reactcss": "^1.2.3"
    },
    "devDependencies": {
        "@babel/preset-react": "^7.16.7",
        "parcel": "^2.3.1"
    },
    "alias": {
        "jquery": {
            "global": "jQuery"
        },
        "wp": {
            "global": "wp"
        },
        "react": {
            "global": "React"
        },
        "react-dom": {
            "global": "ReactDOM"
        }
    },
    "browserslist": "> 0.5%, last 2 versions, not dead",
    "source": [
        "src/control.js",
        "src/preview.js"
    ],
    "scripts": {
        "build": "parcel build",
        "dev": "parcel build --no-optimize",
        "watch": "parcel watch"
    }
}

```

### .babelrc

```json
{
  "presets": [
    [
      "@babel/preset-react",
      {
        "runtime": "classic"
      }
    ]
  ]
}
```

### CLI to run

Either `npm run build` or `npm run dev`

## 🤔 Expected Behavior

Excluding library such as React & ReactDOM is **a real use-case**. Especially if you're developing in WordPress like developing Kirki or developing Gutenberg block. From what I know, `alias` is the best way to do that in Parcel. 

## 😯 Current Behavior

Version `2.2.1` works great. But version `2.3.0 and 2.3.1` seems not able to exclude the aliased libraries. 
Also, `v2.3.1` seems not able to build React using `classic` runtime even though it's set in  `.babelrc`. I reported that in issue #7701 .

## 💁 Possible Solution

💁 I don't have the skill for this. After updating to `2.3.1`, going back to `2.2.1` doesn't solve it (even after deleting node_modules, package-lock.json). So for now, I switch back to webpack as temporary solution.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.3.1
| Node             | 17.4.0
| npm/Yarn         | 8.3.1
| Operating System | Windows 11

Thanks!

**Comment by devongovett** [comment]
It works for me... Could you please provide a reproduction?

**Comment by contactjavas** [comment]
Hi @devongovett , thanks for responding :)
Sorry for just coming back to you :)

After long time not touching Kirki project (after switching to Webpack), today I switched back to Parcel and using `v2.5.0`.
It works great. I don't know what was it before, but I'm glad being able to switch back to Parcel.

Let me close this issue.

In case other people have the similar issue, here's the `package.json` content now:
```json
{
    "name": "control-react-colorful",
    "version": "1.0.15",
    "description": "Development toolkit for Kirki's control-react-colorful",
    "repository": {
        "type": "git",
        "url": "git+https://github.com/kirki-framework/control-react-colorful.git"
    },
    "keywords": [
        "kirki-react-colorful"
    ],
    "author": "Kirki Framework",
    "license": "MIT",
    "bugs": {
        "url": "https://github.com/kirki-framework/control-react-colorful/issues"
    },
    "homepage": "https://github.com/kirki-framework/control-react-colorful#readme",
    "dependencies": {
        "colord": "^2.9.2",
        "react": "^17.0.2",
        "react-colorful": "^5.5.1",
        "react-dom": "^17.0.2",
        "reactcss": "^1.2.3"
    },
    "devDependencies": {
        "@babel/preset-react": "^7.17.12",
        "@parcel/transformer-sass": "^2.5.0",
        "parcel": "^2.5.0"
    },
    "browserslist": "> 0.5%, last 2 versions, not dead",
    "alias": {
        "jquery": {
            "global": "jQuery"
        },
        "wp": {
            "global": "wp"
        },
        "react": {
            "global": "React"
        },
        "react-dom": {
            "global": "ReactDOM"
        }
    },
    "scripts": {
        "build": "parcel build src/control.js src/preview.js --dist-dir dist",
        "dev": "parcel build src/control.js src/preview.js --no-optimize --dist-dir dist",
        "watch": "parcel watch src/control.js src/preview.js --dist-dir dist"
    }
}
```
