### ISSUE TITLE
Building React component using `classic` runtime + `alias` doesn't work in Parcel v2.3.1

### ISSUE THREAD

**Issue by contactjavas** [parcel-bundler/parcel#7701]
# 🐛 bug report

In our case, we need to exclude React & ReactDOM from the build. This is because WordPress already provides a global `React` & `ReactDOM`. The aliasing problem is already reported in issue #7700 . This issue is for the `classic` runtime problem.

After upgrading to `v2.3.1`, the build of our component seems not using the `classic` runtime even though it is set in `.babelrc` 😢 What I can do is just report this issue and go back to `v2.2.1` or switch back to webpack as the temporary solution.

### package.json

```json
{
    "name": "control-react-colorful",
    "version": "1.0.13",
    "description": "Development toolkit for Kirki's control-react-colorful",
    "repository": {
        "type": "git",
        "url": "git+https://github.com/kirki-framework/control-react-colorful.git"
    },
    "keywords": [
        "kirki-react-colorful"
    ],
    "author": "Kirki Framework",
    "license": "MIT",
    "bugs": {
        "url": "https://github.com/kirki-framework/control-react-colorful/issues"
    },
    "homepage": "https://github.com/kirki-framework/control-react-colorful#readme",
    "dependencies": {
        "colord": "^2.9.2",
        "react": "^17.0.2",
        "react-colorful": "^5.5.1",
        "react-dom": "^17.0.2",
        "reactcss": "^1.2.3"
    },
    "devDependencies": {
        "@babel/preset-react": "^7.16.7",
        "parcel": "^2.3.1"
    },
    "alias": {
        "jquery": {
            "global": "jQuery"
        },
        "wp": {
            "global": "wp"
        },
        "react": {
            "global": "React"
        },
        "react-dom": {
            "global": "ReactDOM"
        }
    },
    "browserslist": "> 0.5%, last 2 versions, not dead",
    "source": [
        "src/control.js",
        "src/preview.js"
    ],
    "scripts": {
        "build": "parcel build",
        "dev": "parcel build --no-optimize",
        "watch": "parcel watch"
    }
}

```

### .babelrc

```json
{
  "presets": [
    [
      "@babel/preset-react",
      {
        "runtime": "classic"
      }
    ]
  ]
}
```

### CLI to run

Either `npm run build` or `npm run dev`

## 🤔 Expected Behavior

Excluding library such as React & ReactDOM is **a real use-case**. Especially if you're developing in WordPress like developing Kirki or developing Gutenberg block. 

For now, we don't see there's a UMD version of the new jsx runtime that we can use. That means, we need to use the `classic` one.

## 😯 Current Behavior

Version `2.2.1` works great. But version `2.3.0 and 2.3.1` seems not respecting the runtime specified in `.babelrc` file.

## 💁 Possible Solution

💁 I don't have the skill for this. After updating to `2.3.1`, going back to `2.2.1` doesn't solve it (even after deleting node_modules, package-lock.json). So for now, I switch back to webpack as a temporary solution.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.3.1
| Node             | 17.4.0
| npm/Yarn         | 8.3.1
| Operating System | Windows 11

Thanks!

**Comment by devongovett** [comment]
Is this a duplicate of your other issue #7700? I also cannot reproduce this.

**Comment by contactjavas** [comment]
Hi @devongovett , I think it was bit different. But issue #7700 has been fixed. No issue anymore.
Let me to also close this issue.
