### ISSUE TITLE
Issue 7147 Closed But Not Fixed

### ISSUE THREAD

**Issue by sseidel16** [parcel-bundler/parcel#7703]
# 🐛 bug report

[Issue 7147](https://github.com/parcel-bundler/parcel/issues/7147) was closed weeks ago with a few version releases since then, but the issue remains in Parcel in 2.3.1.

## 🎛 Configuration (.babelrc, package.json, cli command)

See [Issue 7147](https://github.com/parcel-bundler/parcel/issues/7147)

## 🤔 Expected Behavior

See [Issue 7147](https://github.com/parcel-bundler/parcel/issues/7147)

## 😯 Current Behavior

See [Issue 7147](https://github.com/parcel-bundler/parcel/issues/7147)

## 💁 Possible Solution

See [Issue 7147](https://github.com/parcel-bundler/parcel/issues/7147)

## 🔦 Context

See [Issue 7147](https://github.com/parcel-bundler/parcel/issues/7147)

## 💻 Code Sample

See [Issue 7147](https://github.com/parcel-bundler/parcel/issues/7147)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.3.1 |
| Node             | v14.16.1 |
| npm/Yarn         | 8.4.0 |
| Operating System | MacOS |

**Comment by florinvirdol** [comment]
Any news on this one from anyone? 
I'm experiencing something similar. 

Thanks!
