### ISSUE TITLE
Broken url strings in CSS

### ISSUE THREAD

**Issue by katzmo** [parcel-bundler/parcel#7710]
# 🐛 bug report

Since @parcel/transformer-css-~~2.2.0~~ 2.2.1 single quotes in CSS `url()` seem to be replaced with double quotes. This breaks url strings that contain double quotes.

## 🎛 Configuration (.babelrc, package.json, cli command)

No relevant config.

## 🤔 Expected Behavior

I’m expecting the following line to stay as is in the output CSS:

```css
background-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="32" height="24" viewBox="0 0 32 24"><polygon points="0,0 32,0 16,24" style="fill: rgb%2819, 80, 91%29"></polygon></svg>');`
```

## 😯 Current Behavior

From ~~2.2.0~~ 2.2.1 on `'` is changed to `"`, resulting in invalid CSS:

```css
background-image: url("data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="32" height="24" viewBox="0 0 32 24"><polygon points="0,0 32,0 16,24" style="fill: rgb%2819, 80, 91%29"></polygon></svg>");`
```

## 💁 Possible Solution

Is there some config that would allow me turn this off again? I've experimented with transformer settings but no luck.

For now, pinning @parcel/transformer-css to 2.1.1 is a workaround:

```json
  "resolutions": {
    "@parcel/transformer-css": "2.1.1"
  },
```

## 🔦 Context

There are no build errors but the resulting CSS is invalid and, in the above example, wouldn’t show the svg.

I cannot change the affected url string because it comes from a 3rd party dependency ([foundation-sites](https://github.com/foundation/foundation-sites/blob/master/scss/util/_mixins.scss#L151)).

## 💻 Code Sample

See example above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.3.1 |
| Node             | 14.17.4 |
| Yarn         | 1.22.17 |
| Operating System | Ubuntu 21.10 |

**Comment by Shinyaigeek** [comment]
<details>
<summary>simple reproduction</summary>

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>CSS Double</title>
  </head>
  <body>
    <h1>CSS Double</h1>
    <div class="background"></div>
    <style>
      .background {
        background-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="32" height="24" viewBox="0 0 32 24"><polygon points="0,0 32,0 16,24" style="fill: rgb%2819, 80, 91%29"></polygon></svg>');
        width: 100px;
        height: 100px;
      }
    </style>
  </body>
</html>
```
<details>

**Comment by mischnic** [comment]
Related: https://github.com/parcel-bundler/parcel/pull/7564 and https://github.com/parcel-bundler/parcel/issues/7556

**Comment by katzmo** [comment]
Thank you for looking into it!
