### ISSUE TITLE
Globbing in "source" values reports an error

### ISSUE THREAD

**Issue by furious-luke** [parcel-bundler/parcel#7719]
# 🐛 bug report

Using globbing in the "source" parameter of `package.json`, [as detailed here](https://parceljs.org/features/dependency-resolution/#glob-aliases) generates the following error:

```
🚨 Build failed.

Error: The "path" argument must be of type string. Received an instance of Object

  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
  at new NodeError (node:internal/errors:363:5)
  at validateString (node:internal/validators:119:11)
  at Object.join (node:path:1172:7)
  at EntryResolver.resolveEntry (/code/node_modules/@parcel/core/lib/requests/EntryRequest.js:229:42)
  at async Object.run (/code/node_modules/@parcel/core/lib/requests/EntryRequest.js:75:16)
  at async RequestTracker.runRequest (/code/node_modules/@parcel/core/lib/RequestTracker.js:725:20)
  at async AssetGraphBuilder.runEntryRequest (/code/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:746:18)
  at async $b0fd219fea43bcac$export$2e2bcd8739ae039._runFn (/code/node_modules/@parcel/utils/lib/index.js:32645:13)
  at async $b0fd219fea43bcac$export$2e2bcd8739ae039._next (/code/node_modules/@parcel/utils/lib/index.js:32638:9)
```

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json` --

```
{
  ...
  "source": {
    "./dist/*": "./src/$1"
  },
  "main": "dist/index.js",
  "typings": "dist/index.d.ts",
  ...
}
```

## 🤔 Expected Behavior

Based on the documentation, I would expect this to map to the source files when used as a part of a monorepo.

## 😯 Current Behavior

Please see above for the stack trace.

## 💁 Possible Solution

It appears that using an object as a "source" path is currently not being handled. Given it's in the documentation it's a bit confusing as to what's going wrong.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.3.1
| Node             | 16.3.0
| npm/Yarn         | 1.22.5
| Operating System | Arch Linux

**Comment by TiddoLangerak** [comment]
For anyone else getting caught up on this issue: you can likely just use `alias` instead, e.g..:

```
{
  ...
  "alias": {
    "./dist/*": "./src/$1"
  },
  "main": "dist/index.js",
  "typings": "dist/index.d.ts",
  ...
}
```

It requires some careful reading from the documentation, but this is how I understand it: 

In your root package, the `source` field is used as entry point to your application. Hence, this MUST be a string field, pointing to a single file. If you need aliases, you'll need to use the `alias` field.

If your package however is a library with multiple entry points, then you could use the `source` field as a map to map your compiled entry points to your source entry points. Crucially though, this only works if the library is _not_ directly bundled with `parcel`, but instead used as a dependency from your parcel project, e.g. in a monorepo:

> For example, you could use the source field to provide a mapping between compiled code in a package and the original source code. When the module is symlinked, or within a monorepo, this will allow Parcel to compile the module from source rather than use the pre-compiled version.

[source](https://parceljs.org/features/dependency-resolution/#glob-aliases)
