### ISSUE TITLE
Tailwind directives do not get parsed if used from npm package asset

### ISSUE THREAD

**Issue by nextlogic-ono** [parcel-bundler/parcel#7730]
# 🐛 bug report

If parcel loads `tailwindcss/tailwind.css` asset from tailwind npm package, it does not parse the directives written but if I copy that file as a local file, parcel parses the directives properly.

## 🎛 Configuration (.babelrc, package.json, cli command)

Repro repo with steps to reproduce.
https://github.com/windware-ono/parcel-tailwind-not-processed

## 🤔 Expected Behavior

Should parse the tailwind directives.

## 😯 Current Behavior

It does not parse the tailwind directive if specified from npm package asset.

## 💁 Possible Solution

Copy the file locally and compile that instead.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.3.1
| Node             |14.18.3
| npm/Yarn         |6.14.15
| Operating System | Ubuntu 20.04

**Comment by devongovett** [comment]
PostCSS config does not apply to node_modules. Only standard CSS should be published to npm, otherwise all apps using the library must re-create the correct config.

**Comment by nextlogic-ono** [comment]
Ok, thank you.
