### ISSUE TITLE
Update to sharp 0.30.x

### ISSUE THREAD

**Issue by jablonski** [parcel-bundler/parcel#7738]
In _/packages/transformers/image/src/loadSharp.js_ the version of sharp is fixed to ^0.29.1, but sharp releases are currently at ^0.30.x. Maybe this can be upgraded to benefit from latest developments of sharp.

https://github.com/lovell/sharp/blob/main/docs/changelog.md

**Comment by damianobarbati** [comment]
@jablonski did you manage to work around this?

I tried locking `sharp@0.29.3` but any further installs mess up the `yarn.lock` and parcel refuses to build again.
