### ISSUE TITLE
babel configuration does not seem to be picked up in Jenkins docker environment

### ISSUE THREAD

**Issue by PavelSkopik** [parcel-bundler/parcel#7742]
# 🐛 bug report

I have a library project where I use an i18n library that uses babel-plugin-macros. However in my particular setup, the macros configuration in either .babelrc or babel.config.json does not seem to be picked up by parcel when doing a build (at least that is what it seems).

Strangely, the build failure is intermittent. The build works on my Windows 10 machine and it does not work in our Jenkins builder in Docker container on CentOS 7.

I would appreciate any advice. Maybe I am doing something wrong regarding the configuration or I am overlooking something obvious.

I really like parcel and would like to use it going forward.

## 🎛 Configuration (.babelrc, package.json, cli command)

My babel configuration (babel.config.json):
```json
{
  "plugins": [
    "macros"
  ]
}

```
My package.json:
```json
{
  "name": "parcel-issue",
  "version": "1.0.0",
  "description": "",
  "author": "author",
  "license": "ISC",
  "engines": {
    "node": ">= 14.18.1 || <= 16.13.0",
    "yarn": ">= 1.21.1 || < 2.0.0"
  },
  "main": "./target/classes/parcel-issue/index.js",
  "module": "./target/classes/parcel-issue/index.es.js",
  "source": "./src/lib/index.ts",
  "browserslist": [
    "Chrome >= 71",
    "Firefox >= 68",
    "Safari >= 12"
  ],
  "dependencies": {
    "@lingui/react": "^3.13.2"
  },
  "peerDependencies": {
    "@emotion/core": "10.1.1",
    "@emotion/is-prop-valid": "1.1.0",
    "@emotion/styled": "10.0.27",
    "@material-ui/core": "4.11.4",
    "@material-ui/icons": "4.11.2",
    "@reduxjs/toolkit": "1.7.2",
    "classnames": "2.3.1",
    "react": ">=17.0.2",
    "react-dom": ">=17.0.2",
    "react-redux": "7.2.4",
    "react-spinners": "0.10.6",
    "redux": "4.1.0",
    "redux-logger": "3.0.6",
    "redux-thunk": "2.3.0",
    "reselect": "4.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.17.5",
    "@emotion/core": "10.1.1",
    "@emotion/is-prop-valid": "1.1.0",
    "@emotion/styled": "10.0.27",
    "@lingui/cli": "^3.13.2",
    "@lingui/macro": "^3.13.2",
    "@material-ui/core": "4.11.4",
    "@material-ui/icons": "4.11.2",
    "@parcel/packager-ts": "2.3.1",
    "@parcel/transformer-typescript-types": "2.3.1",
    "@reduxjs/toolkit": "1.7.2",
    "@storybook/addon-actions": "^6.4.19",
    "@storybook/addon-essentials": "^6.4.19",
    "@storybook/addon-interactions": "^6.4.19",
    "@storybook/addon-links": "^6.4.19",
    "@storybook/react": "^6.4.19",
    "@storybook/testing-library": "^0.0.9",
    "@testing-library/jest-dom": "^5.16.2",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.4.0",
    "@types/node": "^16.11.22",
    "@types/react": "^17.0.39",
    "@types/react-dom": "^17.0.11",
    "@typescript-eslint/eslint-plugin": "5.11.0",
    "@typescript-eslint/parser": "5.11.0",
    "babel-plugin-macros": "^3.1.0",
    "classnames": "2.3.1",
    "eslint": "8.9.0",
    "eslint-plugin-import": "2.25.4",
    "eslint-plugin-jsx": "0.1.0",
    "eslint-plugin-jsx-a11y": "6.2.3",
    "eslint-plugin-markdown": "1.0.0",
    "eslint-plugin-node": "11.1.0",
    "eslint-plugin-promise": "6.0.0",
    "eslint-plugin-react": "7.16.0",
    "eslint-plugin-react-hooks": "4.1.1",
    "eslint-plugin-standard": "5.0.0",
    "eslint-plugin-storybook": "^0.5.6",
    "jest": "27.5.1",
    "jest-dom": "3.1.3",
    "jest-extended": "0.11.1",
    "parcel": "2.3.1",
    "react": ">=17.0.2",
    "react-dom": ">=17.0.2",
    "react-redux": "7.2.4",
    "react-spinners": "0.10.6",
    "redux": "4.1.0",
    "redux-logger": "3.0.6",
    "redux-thunk": "2.3.0",
    "reselect": "4.0.0",
    "rimraf": "3.0.2",
    "ts-jest": "27.1.3",
    "ts-node": "10.5.0",
    "typescript": "4.5.5"
  },
  "scripts": {
    "clean": "rimraf target",
    "build": "parcel build",
    "build-storybook": "build-storybook",
    "i18n-build": "yarn i18n-extract && yarn i18n-compile",
    "i18n-extract": "lingui extract",
    "i18n-compile": "lingui compile",
    "start": "parcel src/test-app/index.html --open",
    "storybook": "start-storybook -p 6006",
    "test": "jest --config test/jest.config.ts"
  }
}

```

## 🤔 Expected Behavior

The build outputs compiled JS files in the target directory.

## 😯 Current Behavior

The build fails with the following errors:

```
@parcel/core: Failed to resolve '@lingui/macro' from
'./Component.tsx'

 Componentt.tsx:21:24
    20 |
  > 21 | import {t, Trans} from '@lingui/macro';
  >    |                        ^^^^^^^^^^^^^^^
    22 | import {makeStyles} from '@material-ui/core';
    23 | import React, {useEffect} from 'react';

@parcel/resolver-default: External dependency "@lingui/macro" is not declared in package.json.

  package.json:19:3
    18 |   ],
  > 19 |   "dependencies": {
  >    |   ^^^^^^^^^^^^^^
    21 |     "@lingui/react": "^3.13.2"
```

The particular library is included in devDependencies (as per instructions from the author). Adding it to dependencies would produce undesired output without expected transformations (it should transform some i18n specific components to components found in @lingui/core).

## 💁 Possible Solution

Remove the @lingui library and thus avoid using babel-plugin-macros. This is not desired as the library exactly fits the needs.

## 🔦 Context

I am building a module (library) that uses @linguijs library for internationalization. This issues prevents me from delivering a functioning build that can be included in the main application.

## 💻 Code Sample

I have created a minimal example which (of course) works. But it shows my setup.

https://github.com/PavelSkopik/parcel-issue

## 🌍 Your Environment

Also in the Jenkins Docker environment I had to set the PARCEL_WORKER_BACKEND environment variable to process.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.3.1
| Node             | 16.13.0
| npm/Yarn         | npm
| Operating System | CentOS 7 with private Docker image

**Comment by PavelSkopik** [comment]
I tried to research this a bit more. I noticed one thing - in our repo (which is a maven repo) we have multiple subfolders with maven modules. The module with the TypeScript code that is built by parcel is located in one of those subfolders. 

The docker working directory is the root of the repository. After I ran the build with parcel with cache on I noticed that .parcel-cache was created in the root folder instead of the folder where the code resides.

So I tried to move babel.config.json to the root folder but it did not make any difference. The babel config file was not picked up both the root folder and the subfolder.

However, the .parcel-cache folder location is puzzling. Does parcel have a debug output that I could switch on?

**Comment by devongovett** [comment]
The project root location is determined by finding the location of your `yarn.lock` or `package-lock.json` file, falling back to the location of `.git`.

**Comment by PavelSkopik** [comment]
Thanks for the response. The information led me straight to finding the issue. So it turns out that we had a "stray" package-lock.json which someone put in the root folder (do not know why, maybe a mistake) which made parcel to ignore the babel.config.json in the child folder with the source code.

Now that I have removed the invalid package-lock.json file the build succeeds and babel macros are applied as expected.

Do you think you could add more diagnostic information to the console output when babel config and such is not found?
