### ISSUE TITLE
Cannot import manifest.json in webextension

### ISSUE THREAD

**Issue by ClementParis016** [parcel-bundler/parcel#7747]
Hello 👋🏻 

# 🐛 bug report

I'm building a web extension using Parcel and when I try to import its `manifest.json` to read one of its properties from the source code of my extension I get a fatal error at build time.

## 🎛 Configuration (.babelrc, package.json, cli command)

- build command: `parcel build src/manifest.json`
- Parcel config is just the following (`.parcelrc`):
```js
{
  "extends": "@parcel/config-webextension"
}
```
- package.json is mostly empty, the only relevant thing to Parcel would be the browserslist config:
```json
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
```

## 🤔 Expected Behavior

I should be able to import `manifest.json` and build my app successfully.

## 😯 Current Behavior

App fails to build with error: "Bundles must have unique names"

![image](https://user-images.githubusercontent.com/5601687/155013990-1995ec1a-e13f-44eb-9194-2c9b5d8ab790.png)

## 💁 Possible Solution

I have absolutely no clue, the error seems to be thrown from Parcel's internals and the error message is quite vague.

[Parcel normally supports importing JSON files out of the box](https://parceljs.org/languages/json/), but I guess `manifest.json` is subject to a special treatment in the context of web extensions since it acts as the entry point?

## 🔦 Context

I'm trying to read a property of the `manifest.json` file at runtime from the source code of my web extension.

## 💻 Code Sample

The setup is pretty straightforward, it's all defaults from [Parcel's doc on Web Extensions](https://parceljs.org/recipes/web-extension/).

Once you have created the `src/manifest.json` file as instructed, you can add a background script at `src/background.ts` and reference it in the manifest:
```json
  "background": {
    "scripts": ["./background.ts"]
  },
```

In the `background.ts` add:
```ts
import manifest from './manifest.json';
```

Then build the package by following the instructions and see that it fails with the aforementioned error.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.3.1
| Node             | 16.14.0
| npm/Yarn         | Yarn 1.22.17
| Operating System | macOS 11.6

**Comment by robertmaier** [comment]
What's the manifest version are you using? Parcel currently only supports version 2

**Comment by ClementParis016** [comment]
Yes my manifest is indeed version 2:
<img width="354" alt="image" src="https://user-images.githubusercontent.com/5601687/156366415-c15734e9-f651-4872-82dc-21217354a54c.png">

**Comment by 101arrowz** [comment]
The engineering effort required to support this properly (i.e. embed the manifest post-transformation by Parcel) is probably not worth the effort, from what I can tell while working on MV3 support. So you might just need to hard-code it or use `chrome.runtime.getManifest()`/`browser.runtime.getManifest()`.

**Comment by fregante** [comment]
👎

While I agree that it’d be nice if it worked, the browser already has an API for that and you should use it to ensure that the manifest you get in javascript is exactly the manifest your browser is reading, which isn’t guaranteeable with `import`
