### ISSUE TITLE
dynamic import in electron not work

### ISSUE THREAD

**Issue by lqd1434** [parcel-bundler/parcel#7751]
# 🐛 bug report

when building parcel replace package name to a hash string like '3caaa88c22e4b560';
is there some way to make it work correctly?

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🤔 Expected Behavior
do not replace

## 💁 Possible Solution
what i just to asked

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | latest
| Node             | 16
| npm/Yarn         | yarn
| Operating System | macos

**Comment by sznowicki** [comment]
I think your issue lacks some more information. Can you define "correctly" in a more informative way?

If you don't want to have hashes you might want to try [--no-content-hash](https://parceljs.org/features/production/#content-hashing)

**Comment by lqd1434** [comment]
@sznowicki Thank you very much for your reply, I will try it right away
