### ISSUE TITLE
Bus Error

### ISSUE THREAD

**Issue by markxoe** [parcel-bundler/parcel#7754]
# 🐛 bug report

Hello! I am using parcel in multiple projects and since yesterday I cannot bundle anything using parcel.
When using `parcel build` (-> using package.json's targets) I get an `Bus error: 10`.
Even simple configurations as depicted in this issue under 🎛 Configuration do not work and result in Bus errors
BUT it works (more or less) perfectly fine when I bundle directly using the cli (e.g. `npx parcel index.html`)
And it does not work if the working directory only has the package.json and node_modules

this does not work for example: (empty directory)
```sh
npm init -y
npm i -D parcel
npx parcel
# results in
# (npm installing stuff...)
# [1]    15658 bus error  npx parcel
```

## 🎛 Configuration (.babelrc, package.json, cli command)

Example configuration, that does not work
package.json
```json
{
  ...,
  "targets": {
    "app": {
      "source": "index.html"
    }
}
```

## 🤔 Expected Behavior

1. `parcel` in an empty folder should return some "not found" error
2. `parcel` in an folder with package.json > "targets" configuration should serve content.

## 😯 Current Behavior

1. Results in bus error
2. Results in bus error

## 🔦 Context

I am using my MacBook Pro with M1 Pro processor an I've installed node using nvm
Every other Cli/program I've used works flawlessly.

Short list of things I've tried:
- Reinstall parcel (old versions too) also in empty projects (also clear npm cache)
- Reinstall node (every version from 14 to 17)
- Reinstall nvm
- Restart laptop
- Rebuild parcel locally (`yarn build-native` works, `yarn build` does not -> returns bus error)

## 💻 Code Sample

index.html
```html
<html>
  <body>
    <h1>Test</h1>
  </body>
</html>
```

package.json
```json
{
  ...
  "devDependencies": {
    "parcel": "^2.3.2"
  },
  "targets": {
    "app": {
      "source": "index.html"
    }
  }
}
```

And run
```sh
npm i
npx parcel
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.3.2 (also tried 2.1 and 2.0)
| Node             | 17, 16 and 14
| npm/Yarn         | 8.5.1
| Operating System | MacOS 12.2.1

Btw: I don't know if this is an error somewhere upstream
Still hope someone has any idea

**Comment by tillsanders** [comment]
I have a similar issue when running `npx parcel docs/index.html`. On a newly set-up project with just the sample index.html. The problem occurs with v2.3.2 but not with v2.3.1.

**Comment by markxoe** [comment]
I have tested even more.
`npm i -D parcel@2.3.1` - not working
Tried that with every version since 2.0.0, still no success
`npm ls @parcel/core` returns 2.3.2 even when installing parcel with version 2.0.0

So the next thing I tried was to install all @parcel packages that are installed with the old version, so I used
`fs.readdirSync("node_modules/@parcel").map(i=>`@parcel/${i}@2.0.1`).join(" ")`, but still npm ls returns some old and some new versions:
<img width="259" alt="image" src="https://user-images.githubusercontent.com/59475466/155693888-8a9fd44a-08ba-4d45-b2bd-4edaa8a691b7.png">

Also I tried running it using docker containers (e.g.
package.json
```json
{
  "name": "parceltesting",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "build": "parcel build"
  },
  "devDependencies": {
    "parcel": "2.2.1"
  },
  "targets": {
    "app": {
      "source": "index.html"
    }
  }
}
```

Dockerfile
```dockerfile
FROM node:alpine
COPY . .
RUN apk app python3 g++ make
RUN npm i
RUN npm run build
```
) which results in `✨ Built in 633ms [Error: Invalid argument]` (which I guess is an improvement but still bad)

**Comment by markxoe** [comment]
I was stupid, I installed an old version of parcel in the parent folder of all my projects some time ago and apparently npm uses the parcel from there and not the sub folder I am in. Fixed by removing the parent's folder node_modules
Thanks for the help tho

**Comment by luizjr8** [comment]
I got the problem after a parcel package upgrade. To solve it, I just removed the .parcel-cache folder and rerun the build. Probably an incompatible file stills on the cache and the new version tried to load it.

**Comment by jamesfawcett** [comment]
I can confirm same issue was solved by removing .parcel-cache. node_modules wasn't the culprit, I had swapped the .parcel-cache from one machine to another and it caused the bus error.
