### ISSUE TITLE
(JSX): When using props spread and key in the end children become [undefined, false, undefined, undefined] 

### ISSUE THREAD

**Issue by sznowicki** [parcel-bundler/parcel#7755]
Hello I posted the bug report on [react github](https://github.com/facebook/react/issues/23347) but one of the contributors checked it in `create-react-app` environment without being able to reproduce it so we suspect maybe Parcel has something to do with it.

# 🐛 bug report

Please read the [whole explanation with repro repo that uses parcel from the original bug report](https://github.com/facebook/react/issues/23347). 

Long story short, when rendering this kind of component `<SomeComponent {...props} key="foo">Some child</SomeComponent>` the `props.children` are replaced with `[undefined, false, undefined, undefined]`. Always exactly this array.

When I put `key` to before the spread (so, `key="foo" {...props}`) all works as expected (props.children are React element).

I think it may be actually parcel to the blame, but I have no idea what would that cause. I hope when you look at this you'd figure out what this could potentially be.

Also worth noting is that it occurs on both typescript and javascript setups.

**Comment by sznowicki** [comment]
Bump

I have a feeling this is getting buried under new issues ;)

**Comment by mischnic** [comment]
I'm not entirely sure how the transpiled calls to `createElement` *should* look like, but swc is currently not doing exactly what Babel does:  https://github.com/swc-project/swc/issues/4068
