### ISSUE TITLE
Hot Module Replacement not working in modules with exported React hooks

### ISSUE THREAD

**Issue by Duckers** [parcel-bundler/parcel#7759]
# 🐛 bug report

Hot module reload does NOT work in modules that contain exported React hooks (`use*()`)

In a minimal React project with just one module looking like this:

App.ts
```
export function App() {
  return <h1>Hello there</h1>;
}

export function useFoo() {
  return 0;
}
```

Hot module reload does NOT work. It detects the change and reloads, but code changes are not reflected in the browser.

If I delete or comment out the unused `useFoo` hook, it works as expected.

## 🎛 Configuration (.babelrc, package.json, cli command)

Can be reproduced with this minimal setup, along with the file above:

index.html
```
<html>
    <body>
        <div style="height: 100%" id="root"></div>
        <script type="module" src="index.tsx"></script>
    </body>
</html>
```

index.ts
```
import React from "react";
import ReactDOM from "react-dom";
import { App } from "./App";

ReactDOM.render(<App />, document.getElementById("root"));
```

And run with
```
parcel index.ts
```

## 🤔 Expected Behavior

HMR works, or if its expected not to work, an error message explaining why is given

## 😯 Current Behavior

HMR doesn't work

**Comment by mischnic** [comment]
I just tried your example and it worked fine for me with
```json
  "dependencies": {
    "parcel": "^2.6.2",
    "react": "^17",
    "react-dom": "^17"
  }
```

**Comment by hencca** [comment]
same issue here. console clears, no errors, but i have to manually refresh browser before new code shows

**Comment by mischnic** [comment]
@hencca Please share your code if you have a specific situation where HMR isn't working.
