### ISSUE TITLE
Parcel API not recognizing PostCSS & Tailwind config

### ISSUE THREAD

**Issue by nathanielop** [parcel-bundler/parcel#7760]
# 🐛 bug report

Parcel not recognizing/building mjs config files

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// src/build.js
import { Parcel } from '@parcel/core';

export default new Parcel({
  entries: 'src/index.html',
  defaultConfig: '@parcel/config-default'
});
```

```js
// My build function to call the config
import bundler from 'src/build.js';

const { console } = global;

try {
  const { bundleGraph, buildTime } = await bundler.run();
  console.log(
    `Built ${bundleGraph.getBundles().length} bundles in ${buildTime}ms`
  );
} catch (er) {
  console.log(er.diagnostics);
}
```
The function above is called via a shell script:
```
node src/functions/build.js
```

I'm using a postcss.config.mjs and tailwind.config.mjs in order to initialize Tailwind, as seen below

```js
// postcss.config.mjs
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {}
  }
}
```
```js
// tailwind.config.mjs
module.exports = {
  content: ['./src/**/*.{html,js}'],
  theme: {
    extend: {}
  },
  plugins: [],
  mode: 'jit'
};
```

...and importing tailwind into my project via an index.css file imported into index.html;
```css
/* src/index.css */
@tailwind base;
@tailwind components;
@tailwind utilities;
```
```html
<!-- src/index.html -->
<!doctype html>
<html>
  <head>
    <link href="./index.css" type="text/css" rel="stylesheet">
  </head>
  <body class='bg-black'>
    <script type='module' src='./index.js'></script>
  </body>
</html>
```
and lastly my package.json (where I define the project as a module)
```json
{
  "type": "module",
  "name": "app",
  "source": "./src/index.html",
  "dependencies": {
    "@parcel/config-default": "2",
    "autoprefixer": "10",
    "parcel": "2",
    "postcss": "8",
    "tailwindcss": "3"
  },
  "alias": { "src": "./src" },
}
```

## 🤔 Expected Behavior

Tailwind gets bundled into my application

## 😯 Current Behavior

No errors, builds as expected, configs are ignored and Tailwind isn't bundled and my index.css isn't transformed

## 💁 Possible Solution

Not recognizing .mjs file extensions? Not entirely sure here. 

## 🔦 Context

Any TailwindCSS application with this minimal repro setup.

## 💻 Code Sample

See `configuration`

## 🌍 Your Environment

Experienced via Docker Compose project

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2
| Node             | node:17.4.0-alpine3.14
| npm/Yarn         | 7.5.0
| Operating System | N/A

**Comment by LeoniePhiline** [comment]
- What's your package.json? 
- Is tailwindcss installed?
- Why use `.mjs` extension for CommonJS modules? (Either change the extension or the export style.)
- Did you try at all to use `.js`, or confirm that postcss and tailwindcss actually look for `.mjs` files?
- Did you try running tailwind cli to diagnose the issue?
