### ISSUE TITLE
Emoji support check is biased

### ISSUE THREAD

**Issue by kidonng** [parcel-bundler/parcel#7767]
# 🙋 feature request

Current code to check whether emoji is supported:

https://github.com/parcel-bundler/parcel/blob/18b038d57043965afb31077db1f46dadb11a6a78/packages/reporters/cli/src/emoji.js#L3-L4

This code is naive:

- It assumes **all** Windows version does not support emoji, which is not true. [According to Emojipedia](https://emojipedia.org/windows-emoji-support/), Windows supports emoji on Windows 7 or above. I doubt any Parcel user would not develop on a supported Windows version.
- It assumes **all** terminal's `$TERM` is `xterm-256color`. This is not true because obviously not all terminals are xterm. Some popular terminals use their own values (e.g. [kitty](https://sw.kovidgoyal.net/kitty/) uses `xterm-kitty`).

## 🤔 Expected Behavior

Parcel should correctly enable emoji on supported platforms.

## 😯 Current Behavior

Parcel does not correctly enable emoji on supported platforms.

## 💁 Possible Solution

- Remove Windows check all together, or at least add a major version check
- It's tricky to check actual emoji support, but we can safely assume that if a terminal supports 256 color, it probably supports emoji as well. The check can be done via e.g. [supports-color](https://github.com/chalk/supports-color).

**Comment by mischnic** [comment]
Maybe we should use https://github.com/sindresorhus/is-unicode-supported instead? Feel free to open a PR if you want

**Comment by kidonng** [comment]
> Maybe we should use [sindresorhus/is-unicode-supported](https://github.com/sindresorhus/is-unicode-supported) instead?

Yeah, that seems better.

~~Just want to mention this is not a Windows-specific feature though (as mentioned in my second point, it excludes many other terminals on Linux/macOS/whatever as well).~~

EDIT: oops, I misunderstood the code. This does only affect Windows platform.
