### ISSUE TITLE
Spread syntax 

### ISSUE THREAD

**Issue by HSQCoollaughing** [parcel-bundler/parcel#7800]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |
<img width="818" alt="image" src="https://user-images.githubusercontent.com/29752874/156890979-01dbfd55-5354-42b7-8441-4da695680b83.png">

**Comment by HSQCoollaughing** [comment]
{
    "plugins": ["transform-object-rest-spread"]
}

**Comment by HSQCoollaughing** [comment]
<img width="625" alt="image" src="https://user-images.githubusercontent.com/29752874/156891403-b766c869-6f40-43e0-9152-50aa11f2506e.png">
add plugin  `npm install --save-dev babel-plugin-transform-object-rest-spread`

**Comment by mischnic** [comment]
> <img alt="image" width="818" src="https://user-images.githubusercontent.com/29752874/156890979-01dbfd55-5354-42b7-8441-4da695680b83.png">

The error message isn't visible.

**Comment by HSQCoollaughing** [comment]
> > <img alt="image" width="818" src="https://user-images.githubusercontent.com/29752874/156890979-01dbfd55-5354-42b7-8441-4da695680b83.png">
> 
> The error message isn't visible.
  `babel-preset-env` 1.7.0  not contain  `babel-plugin-transform-object-rest-spread`，

**Comment by HSQCoollaughing** [comment]
> > <img alt="image" width="818" src="https://user-images.githubusercontent.com/29752874/156890979-01dbfd55-5354-42b7-8441-4da695680b83.png">
> 
> The error message isn't visible.

![image](https://user-images.githubusercontent.com/29752874/158320819-5b416dfe-e8a8-469d-a35a-0aea76143829.png)
