### ISSUE TITLE
Webextension managed storage

### ISSUE THREAD

**Issue by flo-pereira** [parcel-bundler/parcel#7808]
# 🐛 bug report

I tried to setup a managed storage (https://developer.chrome.com/docs/extensions/reference/storage/)

```json
// manifest.json
"storage": {
    "managed_schema": "schema.json"
  },
```

but my `schema.json` is compiled to a `schema.js` and in the manifest is changed to

```json
"storage": {
    "managed_schema": "/schema.js"
  },
  ```
  
  two issue there, the first is that managed_schema should'nt have the leading slash

`Extension failed to load:  storage.managed_schema must be a relative path without .. `

and the second is that the json file should only be copy as is because managed_schema does not support js file

`Extension failed to load: Line: 1, column: 1, Unexpected token.`

## 🤔 Expected Behavior

`/schema.js` -> `schema.json`

## 🌍 Your Environment

"@parcel/config-webextension": "2.3.2",
"@parcel/config-default": "2.3.2",
"parcel": "2.3.2"

Is this realy an issue or I missed something ?

thanks.

**Comment by 101arrowz** [comment]
This is an issue but should be fixed in #7050.
