### ISSUE TITLE
Build Error on firebase hosting

### ISSUE THREAD

**Issue by rajatdhoot123** [parcel-bundler/parcel#781]
build by using command `parcel --no-cache ./index.html`

Error `Uncaught SyntaxError: Unexpected token <` in browser console

![firebase hosting](https://user-images.githubusercontent.com/18528826/36059311-062ce52a-0e5c-11e8-8be3-4bb5ff752147.png)

**Comment by liranbg** [comment]
Please provide more information about your Project. I've started using parcel with React & Firebase and it seems to work perfectly.

For your interest, this is the build line I am using:
build:
```bash
cross-env NODE_ENV=production parcel build ./src/index.html --public-url ./
```
and locally run:
```bash
parcel ./src/index.html
```

**Comment by dinvlad** [comment]
@liranbg are you using reserved URLs for Firebase configuration? If yes, could you share how you got them working with Parcel; if no, please also share how you're including Firebase config for your setup.

**Comment by liranbg** [comment]
@dinvlad  I do not use reserved URLs.
'Firebase config' you mean the firebase.json file? if so, I do not include it anywhere in my code. it sits right in the root folder of my projects, and once I use the firebase cli tool, it detects it automatically.

**Comment by niksseif** [comment]
@liranbg Thank you so much for sharing your build line just wanted to add if anyone is using firebase just change the public in the firebase.json to dist/ like this :
"public": "dist/" 
Mine is working now.
