### ISSUE TITLE
Parcel is not compiling .mjs without filename

### ISSUE THREAD

**Issue by MylesWardell** [parcel-bundler/parcel#7812]
# 🐛 bug report

Parcel is not compiling .mjs files when the file type is not directly declared by the import
![image](https://user-images.githubusercontent.com/55673046/157393271-0953899f-5628-4487-b840-3cd84fdebe8c.png)

.babelrc
```json
{
  "plugins": [
    [
      "module-resolver",
      {
        "root": ["./src"],
        "alias": {
          "~": "./src"
        }
      }
    ]
  ]
}

```

## 🤔 Expected Behavior

This should compile

## 😯 Current Behavior

The compiler throws an error not recognising a valid mjs file

## 🔦 Context

I am trying to integrate with @trulioo SDK which provides a unique way of installing their custom SDK. In the node modules (the worst place to throw an error) parcel complains that it does not recognise a .mjs file because it does not include the file type (.mjs)

## 💻 Code Sample

```typescript
// How trulioo recommend to import their package 
const GlobalGatewayCapture = require('@trulioo/globalgateway-image-capture-sdk')
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.2.1
| Node             | 16.13.2
| npm         | 8.1.2
| Operating System | Windows

**Comment by mischnic** [comment]
mjs is missing in this list:
https://github.com/parcel-bundler/parcel/blob/083e530c089a1062ea4a51f45fc0c4e2e6db28ed/packages/resolvers/default/src/DefaultResolver.js#L25

I guess we should add it given that it's de-facto standardized by Node.

**Comment by MylesWardell** [comment]
Is their any short term solution I can use to get my current project up and running? Otherwise what would the ETA on a potential patch be?

I understand this is an open source project with limited available time, just trying to meet my teams requirements 👍

**Comment by danieltroger** [comment]
@MylesWardell this sounds like a case for `yarn patch`. With that you can basically have a patch references from your package.json that will automatically be applied for everyone running `yarn install`. Here I wrote about how to use a patch: https://github.com/DevExpress/testcafe/issues/6624#issuecomment-976660127 and to generate it just do `yarn patch <package>`.

Dunno if you need yarn berry for it though.

**Comment by devongovett** [comment]
This was added in the last release. #8667
