### ISSUE TITLE
Incorrect js file extension with --no-scope-hoist

### ISSUE THREAD

**Issue by unbornchikken** [parcel-bundler/parcel#7813]
![image](https://user-images.githubusercontent.com/5675531/157531084-8f3d9e94-e165-47ed-a1aa-3ccf7d0d60c3.png)

This is what I get by using the following build command:

`parcel build --dist-dir build --no-scope-hoist`

Notice the wrong js file name. In the compiled html I get:

`<script src="/index.ce910175.js" defer>`

So the js file name would go as expected at some point, but it won't get the correct file name when the build gets completed.

It's actually a TypeScript project with index.html + index.ts.

If I remove `--no-scope-hoist` the js file gets the correct extension. But  I don't want hoist, I need to keep the original identifier names intact.

parcel@2.3.2

**Comment by mischnic** [comment]
What OS are you using?

**Comment by unbornchikken** [comment]
It's Windows.

**Comment by mischnic** [comment]
How many cores does your CPU have?

Could you determine what this function returns for you? 
https://github.com/parcel-bundler/parcel/blob/e294eafd9a49c056fb4b223c5ace5c0653428ede/packages/core/workers/src/cpuCount.js#L44
e.g. by running
```
$ node -p 'require("@parcel/workers/lib/cpuCount").default()'
```
in the shell?

**Comment by unbornchikken** [comment]
Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz, 2808 Mhz, 10 Core(s), 20 Logical Processor(s)

**Comment by mischnic** [comment]
The problem is that when writing the bundles
https://github.com/parcel-bundler/parcel/blob/80c728ceffdc0829eca568a6ec66c07e07a0b87b/packages/core/core/src/requests/WriteBundleRequest.js#L253-L256
this rename here
https://github.com/parcel-bundler/parcel/blob/80c728ceffdc0829eca568a6ec66c07e07a0b87b/packages/utils/fs-write-stream-atomic/index.js#L103
isn't awaited but happens sometime afterwards asynchronously.  (The whole `handleClose` callback is called late, it's not just the missing `fs.rename` callback)

But it doesn't happen at all if Parcel stops the process forcefully: https://github.com/parcel-bundler/parcel/blob/80c728ceffdc0829eca568a6ec66c07e07a0b87b/packages/core/parcel/src/cli.js#L259

**Comment by alexreardon** [comment]
I am getting this error after upgrading to `parcel@2.4.0` from `2.2.1`

Here is the command I am running:

```
PARCEL_WORKERS=0 parcel build src/index.html --no-cache --no-source-maps --no-autoinstall
```

So I am seeing this error without `--no-scope-hoist` and with 0(?) workers (`PARCEL_WORKERS=0`)

- macOS 12.3
- 2.6 GHz 6-Core Intel Core i7

**Comment by alexreardon** [comment]
This bug occurs for me every time. A workaround is to manually fix the file names using a script after parcel is finished 😕

**Comment by alexreardon** [comment]
For anybody who needs it, here is a little script I am currently running after `parcel` to fix the incorrect filename additions

```ts
import globby from 'globby';
import invariant from 'tiny-invariant';
import { join } from 'path';
import { rename } from 'fs/promises';

// https://regexr.com/6ir3l
const regex = /^(?<correct>.*?)(?<broken>\.\d+)$/;
const distDirectory = join(process.cwd(), './dist');

// parcel bug is causing random digits to be appended to some filenames
// https://github.com/parcel-bundler/parcel/issues/7813
export async function fixParcelFilenames() {
  const files: string[] = await globby(`*`, {
    cwd: distDirectory,
  });

  for (let i = 0; i < files.length; i++) {
    const file = files[i];
    const match = regex.exec(file);

    if (match?.groups?.broken) {
      const correct = match?.groups?.correct;
      invariant(correct, 'expected to have correct file capture group');
      await rename(join(distDirectory, file), join(distDirectory, correct));
      console.log('broken file', file);
      console.log('renamed to', correct);
    }
  }
}
```

**Comment by mischnic** [comment]
When I got this, the output files were (often) empty, so renaming might not be enough.

Commenting out this line worked for me https://github.com/parcel-bundler/parcel/blob/80c728ceffdc0829eca568a6ec66c07e07a0b87b/packages/core/parcel/src/cli.js#L259

**Comment by mischnic** [comment]
Node 13.14.0 is working correctly, the next version 14.0.0 has this behaviour. Something regarding the timing of the `close` event on  the `createWriteStream()` stream has changed.

Potentially https://github.com/nodejs/node/commit/e13a37e49d
