### ISSUE TITLE
🐛 publicURL with development server

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#782]
### 🎛 Configuration (.babelrc, package.json, cli command)
`parcel src/index.html --public-url ./`
or 
`parcel src/index.html --public-url /`

### 🤔 Expected Behavior

The site should be served at `localhost:1234`.

### 😯 Current Behavior

- with `parcel src/index.html --public-url ./`:
	- `http://localhost:1234/` properly serves `index.html`
	- every request serves index.html (i.e. `http://localhost:1234/423958b25b168623f5a455b67f81b487.js` returns the `index.html` file)

- with `parcel src/index.html --public-url /`:

	- http://localhost:1234/ returns a 404
	- everything works when navigating to `http://localhost:1234/index.html`

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.5.1
| Node             |v9.5.0
| npm/Yarn         |yarn 1.3.2
| Operating System |macOS 10.12.6

**Comment by ChrisAckerman** [comment]
Am I missing something? I still have this problem even though this issue is closed?

**Comment by wxs77577** [comment]
Still have this problem too.
I need to build for hyber-app, so I can't use '/main.js' as the url, I need to use './main.js'.
But when I use `parcel --public-url ./ index.html` it's built successfully but I can't access any js file or css file.
