### ISSUE TITLE
Allow a output filename to be specified for bundles / predictable output filenames

### ISSUE THREAD

**Issue by philkunz** [parcel-bundler/parcel#7822]
# 🙋 feature request

Parcel v1 allowed to specify a output filename for bundles through the cli and public api. I can't find that feature in v2. This feature is needed though when writing tools that require a file with a predictable output filename.

## 🤔 Expected Behavior

bundle a javascript entrypoint into a bundle file with the specified name.

## 😯 Current Behavior

unpredictable bundle name.

**Comment by devongovett** [comment]
You can specify the output file path with targets: https://parceljs.org/features/targets/#multiple-targets, though not through the CLI. Do you need it via the CLI specifically or does that work for you?
