### ISSUE TITLE
i just want use Classic scripts only . how can i do ?

### ISSUE THREAD

**Issue by ghost** [parcel-bundler/parcel#7826]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
What exactly do you want and why do you want that?

**Comment by ghost** [comment]
@mischnic  
Some of our static pages are rendered with the back-end way, each time the packaging code will generate two copies of js, the back-end workload will increase twice

This feature should not be mandatory for each developer to enable, but optional

**Comment by shannonio** [comment]
I need this as well, I am developing a React Component for use inside of Salesforce. The only way to do this is to use their provided. lightning-component container library which loads my react component in an iframe in salesforce. iFrames do not support module scripts. 

Thoughts on ways around this?
