### ISSUE TITLE
Google Tag CORS errors

### ISSUE THREAD

**Issue by eastwing27** [parcel-bundler/parcel#7827]
We use Google Tags in our React app. WE did not face any errors while were using Parcel 1 but after migrating to Parcel 2 these errors keep appear:
`
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://stats.g.doubleclick.net/. (Reason: CORS request did not succeed). Status code: (null)`

Is it a bug? Is there any way we can force CORS for Google Tags?

## 🤔 Expected Behavior

No CORS errors

## 😯 Current Behavior

CORS errors appear intensely

**Comment by mischnic** [comment]
Not sure how this is related to Parcel.

How are you using Google Tags?
