### ISSUE TITLE
Add support for import subpath patterns

### ISSUE THREAD

**Issue by rsimp** [parcel-bundler/parcel#7840]
# 🙋 feature request

Add support for [import subpath patterns](https://nodejs.org/api/packages.html#subpath-patterns) for framework agnostic aliasing

## 🤔 Expected Behavior

With the following in package.json:
``` json
{
  "imports": {
    "#hooks/*": "./src/common/hooks/*",
  }
}
```
I should be able to import like the following:
``` js
import useHook from '#hooks/useHook';
```

## 😯 Current Behavior

Parcel already supports glob aliases to achieve the same thing. However import subpath patterns are a standard supported natively in node.

## 💁 Possible Solution

Implement code in dependency resolution to support `imports` in package.json. One part of the spec that helps is that `imports` entries MUST start with # in order to work. If an import starts with '#' then Parcel should check package.json for the `imports` section before resolving with it's own alias configuration. Webpack uses this same method, or rather it only will resolve '#' imports with package.json.

## 🔦 Context

While parcel aliasing is useful it's specific to Parcel. Jest, express, other bundlers, typescript all need their own specific configuration to support the same code. Webpack, express, build scripts, and top level jest imports all already support import subpath patterns. Jest mocking is waiting on a third party dependency to get support for mocking apis as well. It would be nice if typescript/vs code supported it as well, but as more packages implement the standard it puts more pressure on other packages to adopt.

Even in its current state I can at least get framework agnostic support for Parcel AND for node.js backend/scripts just like I can with Webpack.

**Comment by rsimp** [comment]
For more information, webpack achieves this using their [enhanced-resolve](https://github.com/webpack/enhanced-resolve) package. The issue for adding the `imports` field is: https://github.com/webpack/enhanced-resolve/issues/290

**Comment by rsimp** [comment]
Really this feature request should be for supporting the entire `imports` field specification. Not just subpath patterns

**Comment by rsimp** [comment]
Also esbuild and rollup support import subpath patterns as well

**Comment by mischnic** [comment]
Will be fixed by https://github.com/parcel-bundler/parcel/pull/8807 in the next release

**Comment by cybergrunge** [comment]
Well, it is not. (^2.9.1)

`@parcel/core: Failed to resolve '#utils/logger.js' from './src/index.js'`

**Comment by devongovett** [comment]
Please note that exports/imports support is currently opt-in to avoid breaking changes. To enable it, add the following to your project root package.json:

```json
{
  "@parcel/resolver-default": {
    "packageExports": true
  }
}
```

See the docs for more details: https://parceljs.org/features/dependency-resolution/#package-exports

**Comment by cybergrunge** [comment]
Thanks,  and apologies, I only found this issue when searching for informations about this.

**Comment by mitsukuri** [comment]
I've got
```
{
  "@parcel/resolver-default": {
    "packageExports": true
  }
}
```
and my subpath imports in `package.json` are as follows:
```
"imports": {
  "#*": "./src/ts/*"
}
```
but I'm getting `@parcel/resolver-default: Cannot find a package.json above './src/ts'`.
Any ideas why?
