### ISSUE TITLE
A project breaks at startup and build when using "source" in package.json

### ISSUE THREAD

**Issue by ziplb** [parcel-bundler/parcel#7843]
# 🐛 bug report

A project breaks at startup and build if the source file(e.g. `index.html`) is specified using property `source` in `package.json`. 

## 🎛 Configuration (.babelrc, package.json, cli command)

Project structure:

```
outer-dir/
├─ example/
│  ├─ public/
│  │  ├─ mainfest.json
│  ├─ src/
│  │  ├─ index.html
│  ├─ package.json
│  ├─ yarn.lock
├─ yarn.lock

```

package.json:
```js
{
  ...
  "source": "src/index.html",
  "scripts": {
    "start": "parcel",
    "build": "parcel build"
  },
  "devDependencies": {
    "@parcel/transformer-webmanifest": "2.3.2",
    "parcel": "^2.3.2",
    ...
  },
  ...
}
```

## 🤔 Expected Behavior

Commands `parcel` and `parcel build`  run without error.

## 😯 Current Behavior

To process `manifest.json`, Parcel needs `@parcel/transformer-webmanifest` that it cannot find and crashes with an error. The same happens with other packages needed to run or build a project. It seems that Parcel finds the most top-level `yarn.lock` and tries to resolve `node_modules` there. 

## 💁 Possible Solution

I assume that somewhere in the code there is an error due to which the collector is looking not for the first `package.json`, but for the last. 

## 🔦 Context

I caught this error completely by accident and had absolutely no idea that I might have `yarn.lock` up the tree that somehow got there.

## 💻 Code Sample

Here is a [repository](https://github.com/ziplb/parcel-error-reproduction/tree/main) with an example to reproduce the issue.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.3.2
| Node             | 16.13.1
| npm/Yarn         | yarn v.1.22.17
| Operating System | macOs Monterey

**Comment by Shinyaigeek** [comment]
this seems to going to be fixed with #7537

**Comment by ziplb** [comment]
@Shinyaigeek It seems to me that the above bug was not fixed in the task #7537. I caught the bug in the newest available version 2.3.2.

**Comment by Shinyaigeek** [comment]
@ziplb the above PR is still in review. Please try again after the PR will be merged and nightly version including this fix will be released

**Comment by ziplb** [comment]
@Shinyaigeek Thank you!
