### ISSUE TITLE
Replace terser with esbuild or swc minifier

### ISSUE THREAD

**Issue by guoyunhe** [parcel-bundler/parcel#7847]
# 🙋 feature request

Minification can take 30~50% of total production building time. However, terser isn't very good in performance. In our project, replacing terser with esbuild, reduced our build time by 34%. swc's minification is also very fast.

## 🤔 Expected Behavior

Use fast esbuild or swc as minifier.

## 😯 Current Behavior

Use slow terser as minifier.

**Comment by mischnic** [comment]
You can swap out the terser optimizer yourself with `@parcel/optimizer-swc` or `@parcel/optimizer-esbuild`. But we've found that, for now, they are either producing bigger or invalid output: https://github.com/parcel-bundler/parcel/pull/7212#issuecomment-954821231

.parcelrc:
```json
{
	"extends": "@parcel/config-default",
	"optimizers": { "*.js": ["@parcel/optimizer-swc"] }
}
```

**Comment by guoyunhe** [comment]
What is the current state of swc and esbuild optimizer?

**Comment by mischnic** [comment]
The next Parcel release is going to use swc by default: https://github.com/parcel-bundler/parcel/pull/8860
