### ISSUE TITLE
homebrew package

### ISSUE THREAD

**Issue by gintering1000** [parcel-bundler/parcel#7848]
# 🙋 feature request

## 💻 Examples

may i ask parcel to homebrew package?

**Comment by mischnic** [comment]
The general problem with global installs that you can't have different Parcel versions in different projects

Parcel's caching model is designed around Parcel being installed locally

Anyone can add a new Homebrew package, I imagine the one for Parcel would be similar to webpack: https://github.com/Homebrew/homebrew-core/blob/master/Formula/webpack.rb

**Comment by gintering1000** [comment]
is that possible to me? haha too hard to me
