### ISSUE TITLE
🐛 require does not import module properly

### ISSUE THREAD

**Issue by bpx279** [parcel-bundler/parcel#785]
### 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc
```js
{
  "presets": [
    "env",
    "es2015",
    "stage-2"
  ],
  "plugins": ["transform-es2015-modules-commonjs",
    ["module-resolver", {
      "root": "./src",
      "alias": {
        "vue$": "vue/dist/vue.esm.js"
      }
    }]
  ]
}
```

### 🤔 Expected Behavior

Please note that webpack works properly and has the expected behavior.

When importing ChartJS, the MomentJS instance should properly be loaded using require('moment') located in the ChartJS module.

require('moment') should return
```js
momentInstance
``` 

### 😯 Current Behavior

Right now, require('moment') returns an object with the expected result inside the "default" key.

require('moment') returns
```js
{default: momentInstance}
``` 
### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.4.1 (vue)
| Node             | 9.4.0
| npm/Yarn         | yarn 1.3.2
| Operating System | macOS High Sierra

**Comment by fathyb** [comment]
We have a temporary workaround using #530

**Comment by mischnic** [comment]
Works with Parcel 2
