### ISSUE TITLE
"404 Page not found" when using a link to HTML (<a>) or <iframe>

### ISSUE THREAD

**Issue by awvalenti** [parcel-bundler/parcel#7851]
# 🐛 bug report

Can't use any link (\<a\>) to HTML, it generates a 404 error. Same happens to \<iframe\>.

### package.json
```json
{
  "name": "404",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel": "^2.3.2"
  }
}
```
### Command
```sh
npx parcel a.html
```
### File a.html
```html
<a href="b.html">b</a>
```

## 🤔 Expected Behavior
Should show link to be clicked and take user to next page

## 😯 Current Behavior
Displays "404 Page not found." and nothing else.

![image](https://user-images.githubusercontent.com/834921/159498166-85dca59d-5313-4984-995a-6b76f69f09a4.png)

## 💁 Possible Solution
No idea!

## 🔦 Context
Simply tried to add links

## 💻 Code Sample
This script reproduces the problem completely:
```sh
mkdir 404
cd 404
npm init -y
npm install -D parcel
echo '<a href="b.html">b</a>' > a.html
echo b > b.html
npx parcel a.html
```
and open http://localhost:1234 or similar.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel          | 2.3.2|
| Node            | 17.7.2|
| npm/Yarn      |   npm 8.5.5|
| Operating System | Linux Mint 20.3 Una / Linux version 5.13.0-27-generic |

**Comment by awvalenti** [comment]
I tried forking the project and checking if I could fix the problem myself. Unfortunately, I was unable to understand anything or even build the project. Build errors occured, I found no useful development information on the README and gave up.

**Comment by devongovett** [comment]
You need to go to http://localhost:1234/a.html, since your file is called a.html and not index.html.

**Comment by awvalenti** [comment]
This behavior changed. It was possible before to define HTML entry point and it became the "index.html".

Anyway, appending `a.html` works. Thank you!

**Comment by awvalenti** [comment]
Anyway, please note that there's still a bug. If you replace `<a href="..."></a>` with `<h1>Test</h1>`, no 404 occurs anymore, it instead loads the page, even accesing `http://localhost:1234/` directly.
