### ISSUE TITLE
2.4.0 is broken

### ISSUE THREAD

**Issue by ThatOneCalculator** [parcel-bundler/parcel#7853]
# 🐛 bug report

Everything was working fine until I upgraded from 2.3.2 to 2.4.0

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json

```

```js
{
	"name": "zer0bin",
	"source": "index.pug",
	"version": "0.7.1",
	"browserslist": "> 0.5%, last 2 versions, not dead",
	"license": "MIT",
	"scripts": {
		"start": "parcel index.pug",
		"build": "parcel build index.pug"
	},
	"devDependencies": {
		"@parcel/compressor-brotli": "^2.4.0",
		"@parcel/compressor-gzip": "^2.4.0",
		"@parcel/config-default": "^2.4.0",
		"@parcel/transformer-pug": "^2.4.0",
		"@parcel/transformer-sass": "^2.4.0",
		"@types/core-js": "^2.5.5",
		"@types/node": "^17.0.21",
		"parcel": "^2.4.0"
	},
	"description": "just a place to paste",
	"repository": "https://github.com/Domterion/zer0bin",
	"author": "Domterion, ThatOneCalculator",
	"dependencies": {
		"@ant-design/icons": "^4.7.0",
		"@ant-design/icons-svg": "^4.2.1",
		"highlight.js": "^11.4.0",
		"js-confetti": "^0.10.2",
		"no-darkreader": "^1.0.1",
		"smooth-scrollbar": "^8.7.4",
		"tippy.js": "^6.3.7"
	}
}
```

## 🤔 Expected Behavior

Build suceeeds

## 😯 Current Behavior

```
➜  frontend git:(main) ✗ npm run build                         

> zer0bin@0.7.1 build
> parcel build index.pug

🚨 Build failed.

@parcel/optimizer-terser: ENOENT: no such file or directory, open
'/home/the1calc/zer0bin/frontend/node_modules/@parcel/runtime-js/lib/bundles/runtime-ff6e3d8ea9fe2fa0.js'

  Error: ENOENT: no such file or directory, open
  '/home/the1calc/zer0bin/frontend/node_modules/@parcel/runtime-js/lib/bundles/runtime-ff6e3d8ea9fe2fa0.js'

➜  frontend git:(main) ✗ ls node_modules/@parcel/runtime-js/lib
JSRuntime.js  helpers
```

## 💁 Possible Solution

Fix runtime-js to look for right path

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.0
| Node             | 16.14.0
| npm/Yarn         | yarn 3.2.0
| Operating System | Ubuntu 20.04 LTS

**Comment by ThatOneCalculator** [comment]
nvm, seems to have been a problem on my machine

**Comment by narva001** [comment]
I'm actually running into an issue with version 2.4.0 as well.

🚨 Build failed.
@parcel/transformer-css: Error parsing selector: InvalidState

I've reverted back to version 2.3.2 and it works.

Software | Version(s)
-- | --
Parcel | 2.4.0
Node | 14.16.1
npm | 6.14.12
Operating System | Mac Big Sur v 11.6

**Comment by devongovett** [comment]
The new css parser is more strict.  Do you have more information on which selector you are hitting an error on?

**Comment by praneetloke** [comment]
2.4.0 is [failing](https://github.com/deskypus/deskypus.github.io/runs/5662329021?check_suite_focus=true) for me. All I get is the following error message. Is there a way I can get more diagnostic info? The repo is https://github.com/deskypus/deskypus.github.io and it's public, so you could try to build it yourself too if you'd like.

```
Building...
thread '<unnamed>' panicked at 'internal error: entered unreachable code', src/properties/border.rs:1161:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
Error: The process 'npm' failed with exit code 134
```

**Comment by ThatOneCalculator** [comment]
Yea 2.4.0 has been giving me a myriad of different issues like this

**Comment by ThatOneCalculator** [comment]
Just got this new error out of the blue

![image](https://user-images.githubusercontent.com/44733677/159758972-53e531d6-9348-4ffc-8d3e-e043bf481cd8.png)

**Comment by narva001** [comment]
> The new css parser is more strict. Do you have more information on which selector you are hitting an error on?

@devongovett  - I haven't been able to/figure out which selector it's failing on.

**Comment by devongovett** [comment]
@narva001 most of the places where that error could occur is when you do something invalid in a selector after a pseudo element. For example, the following is invalid because attribute selectors aren't allowed after pseudo elements:

```css
input::placeholder[foo=bar] {}
```

You should be getting location information (i.e. a code frame) for errors. If not, it's possible you somehow have multiple copies of the `@parcel/diagnostic` package installed. I've had this happen before with npm. You'd need to deduplicate them in your lockfile.

**Comment by devongovett** [comment]
@praneetloke your issue is fixed in the commit linked above. Released in `@parcel/css` v1.7.3.

**Comment by narva001** [comment]
@devongovett  - I have a toolkit for our UI elements and I was able to look at the .scss file and manage to pull out a piece of code that the @parcel/transformer-css is having trouble with and giving me "@parcel/transformer-css: Error parsing selector: InvalidState"


Here's an example:

```
&.luna-nav_group--action-is_disabled:after {
        &.luna-nav_group--item-ledger:after {
          content: none;
        }
      }
```

**Comment by devongovett** [comment]
@narva001 that is actually invalid. When the nested selectors are expanded, you will have two `:after` pseudo elements there. You can't have a pseudo element after another pseudo element. That selector would have just been ignored in browsers before. I'd suggest you remove the outer `:after`.

**Comment by alexreardon** [comment]
Hi @devongovett,

Not sure if this is related, but I am using and `index.html` file as any entry point with parcel. In `2.4.0` I am now getting get this command line output:

`PARCEL_WORKERS=0 parcel build src/index.html --no-cache --no-source-maps --no-autoinstall`

```
✨ Built in 7.67s

dist/index.html                         1.87 KB    2.92s
...
```

But in `dist` the `index.html` filename is actually: `index.html.2575126421` 😬. Some files are named correctly, but the `js` bundle and a `svg` file also have a random number suffix after the file extension

**Comment by alexreardon** [comment]
Using `--no-content-hash` yielded the same result :(

**Comment by mischnic** [comment]
@alexreardon See https://github.com/parcel-bundler/parcel/issues/7813
