### ISSUE TITLE
RegExp error

### ISSUE THREAD

**Issue by iamlaobie** [parcel-bundler/parcel#786]
I Build a html file by the command
```
parcel build ./src/payment/index.html --out-dir ./payment --public-url http://share.jijiabaoxian.cn/misc/anlian_hk/payment/
```
 the file ./src/payment/index.html include some script what the RegExp in it
```
/<script>(.*)<\/script>/
```
was converted to 
```
/ <script>(.*)<\/script> /
```
Parcel auto add a space at the begining and the end, make a mistake

My Parcel version is 1.5.1

**Comment by mischnic** [comment]
Please provide a reproduction if this still happens. Seems to work with version 1.12.3.
