### ISSUE TITLE
Error parsing selector: InvalidState

### ISSUE THREAD

**Issue by lixiaofeng666** [parcel-bundler/parcel#7864]
# 🐛 bug report
```shell
@parcel/transformer-css: Error parsing selector: InvalidState

 > 1 | lbar:horizontal{height:6px}.el-input::-webkit-scrollbar-thumb{border-radius:5px;width:6px;background:#b4bccc}.el-input::-webkit-scrollbar-corner{background...
```

## 🎛 Configuration (.babelrc, package.json, cli command)
package.json deps :
```shell
"dependencies": {
    "axios": "^0.26.1",
    "element-plus": "^2.1.4",
    "vue": "^3.2.31"
  },
  "devDependencies": {
    "@parcel/transformer-vue": "^2.4.0",
    "parcel": "^2.4.0",
    "sass": "^1.49.9"
  },
```

I using it like this:

// index.js
```js
import { createApp } from 'vue'
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
import Appfrom './App.vue'

const app = createApp(App)

app.use(ElementPlus)
app.mount('#app')
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.0
| Node             | 14.17.3
| npm         | 6.14.13
| Operating System | Win 10

**Comment by Staz** [comment]
I'm getting the same error, but with no indication of where it is occurring.

`@parcel/transformer-css: Error parsing selector: InvalidState`

**Comment by devongovett** [comment]
See https://github.com/parcel-bundler/parcel-css/issues/122
