### ISSUE TITLE
Parcel 2.4.0 removes used CSS class

### ISSUE THREAD

**Issue by ondrejmirtes** [parcel-bundler/parcel#7865]
I have an open-source website build with 11ty and Parcel:

https://github.com/phpstan/phpstan/tree/1.5.x/website

It imports littlefoot.css in app.pcss file: https://github.com/phpstan/phpstan/blob/a6d536563486098432cb4ff2bc515feae378b0d5/website/src/app.pcss#L5

Before upgrading to 2.4.0, the littlefoot classes were part of the compiled file.

After upgrading to 2.4.0, the littlefoot classes are missing.

Bad commit: https://github.com/phpstan/phpstan/tree/690c310dfbfa9c84bf377794dcc4f66b3dc0411a/website

Good commit (after reverting the updates): https://github.com/phpstan/phpstan/tree/a6d536563486098432cb4ff2bc515feae378b0d5/website

If you build the bad commit with `yarn run build`, you'll see the littlefoot classes missing in website/dist/blog.xxxxxxxx.css.

If you build the good commit, the littlefoot classes are present in website/dist/blog.xxxxxxxx.css.

**Comment by devongovett** [comment]
This appears to be caused by the `sideEffects: false` in https://unpkg.com/browse/littlefoot@3.4.1/package.json.

**Comment by ondrejmirtes** [comment]
Thank you, I confirm the fix in Parcel 2.4.1.
