### ISSUE TITLE
`react-remove-scroll` doesn't let you scroll overflowing elements

### ISSUE THREAD

**Issue by atomiks** [parcel-bundler/parcel#7868]
# 🐛 bug report

Copy this same code and dependencies into a Parcel 2 project. You should be able to scroll the left panel.

https://codesandbox.io/s/elastic-shirley-tmo232?file=/src/index.js

## 🎛 Configuration (.babelrc, package.json, cli command)

N/A, fresh repo

## 🤔 Expected Behavior

Can scroll the left panel

## 😯 Current Behavior

Can't scroll left panel

## 🔦 Context

This works in Vite and CodeSandbox and I have _no idea_ why this doesn't work in Parcel. Felt like I was going insane 😭 

## 💻 Code Sample

https://codesandbox.io/s/elastic-shirley-tmo232?file=/src/index.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2.4.0
| Node             | v16.13.0
| npm/Yarn         | npm 8.5
| Operating System | macOS 12.1
| react-remove-scroll | 2.4.4

**Comment by mischnic** [comment]
The bug was that swc removed some parenthesis so
```js
function foo() {
    return (
        /*
         */
        1
    );
}
```
became
```js
function foo() {
return /*
		*/ 1;
}
```
which is equivalent to `return; 1;`

Will be fixed by bumping the swc version in https://github.com/parcel-bundler/parcel/pull/7870.
