### ISSUE TITLE
ESM cyclic dependencies not exporting default

### ISSUE THREAD

**Issue by 101arrowz** [parcel-bundler/parcel#7874]
# 🐛 bug report

Default exports are not available in cyclic dependencies. See the following example:

`a.js`:
```js
import './b.js'

export default 'hi';
export const a = (() => { console.log('a eval'); return 1; })();
```

`b.js`:
```js
import * as a from './a.js';

console.log(Object.getOwnPropertyNames(a));
```

## 🤔 Expected Behavior

As in browsers, this should print `['default', 'a']`, then `a eval`.

## 😯 Current Behavior

We get just `['__esModule', 'a']` before `a eval`.

## 💁 Possible Solution

Create a temp variable for exports without values. This patch does the trick:

```patch
diff --git a/packages/transformers/js/core/src/modules.rs b/packages/transformers/js/core/src/modules.rs
index 1a9567715..9c8a0572a 100644
--- a/packages/transformers/js/core/src/modules.rs
+++ b/packages/transformers/js/core/src/modules.rs
@@ -208,19 +208,27 @@ impl ESMFold {
   }
 
   fn create_exports_assign(&mut self, name: JsWord, right: Expr, span: Span) -> ModuleItem {
-    ModuleItem::Stmt(Stmt::Expr(ExprStmt {
-      expr: Box::new(Expr::Assign(AssignExpr {
-        op: AssignOp::Assign,
-        left: PatOrExpr::Expr(Box::new(Expr::Member(MemberExpr {
-          obj: Box::new(Expr::Ident(Ident::new("exports".into(), DUMMY_SP))),
-          prop: MemberProp::Ident(Ident::new(name, DUMMY_SP)),
-          span: DUMMY_SP,
-        }))),
-        right: Box::new(right),
-        span: DUMMY_SP,
-      })),
+    let export = Ident::new(
+      format!(
+        "$parcel$exportAssign${}{:x}",
+        name,
+        (self as *mut Self as usize)
+      )
+      .into(),
+      DUMMY_SP,
+    );
+    self.create_export(name, Expr::Ident(export.clone()), span);
+    ModuleItem::Stmt(Stmt::Decl(Decl::Var(VarDecl {
       span,
-    }))
+      kind: VarDeclKind::Var,
+      decls: vec![VarDeclarator {
+        span: DUMMY_SP,
+        name: Pat::Ident(export.into()),
+        init: Some(Box::new(right)),
+        definite: false,
+      }],
+      declare: false,
+    })))
   }
 
   fn create_import_access(&mut self, source: &JsWord, imported: &JsWord, span: Span) -> Expr {
```

I know using the memory address of the `ESMFold` struct as part of the temp variable name is a bit sketchy but it should do the trick to prevent collisions since `ESMFold` is module-scoped.

## 🔦 Context

I'm trying to add support for top-level await, but first it's probably best to get full spec compatibility for normal ESM. See https://github.com/parcel-bundler/parcel/issues/4028#issuecomment-1076872133.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2@HEAD
| Node             | v17.3.0
| npm/Yarn         | Yarn 1.22.4
| Operating System | WSL 2 (Ubuntu 20.04)

**Comment by mischnic** [comment]
I haven't looked into this in detail but:

> I know using the memory address of the ESMFold struct as part of the temp variable name is a bit sketchy but it should do the trick to prevent collisions since ESMFold is module-scoped.

This would produce non-reproducible builds because the pointer changes every time

**Comment by 101arrowz** [comment]
True, is there a way to generate a stable uid per module declaration?

EDIT: Actually maybe the UID isn't even needed, since these exports are per-module anyway. I was worried it would cause a collision in the case that the modules are all concatenated into the same scope (which I think happens in the scope hoisting packager but I might be wrong).
