### ISSUE TITLE
Service worker is placed in a subdirectory when built

### ISSUE THREAD

**Issue by GRA0007** [parcel-bundler/parcel#7879]
# 🐛 bug report

When building a React app with a service worker, Parcel places it at the path `dist/up_/src/service-worker.js`. This breaks the `fetch` listener as the service worker needs to be on the same level as the `index.html` file.

This is because no other files are below the service worker, as per [this stackoverflow post](https://stackoverflow.com/questions/34147562/service-worker-is-caching-files-but-fetch-event-is-never-fired).

### `package.json`
```json
{
  "name": "react app",
  "version": "1.0.0",
  "scripts": {
    "start": "parcel public/index.html --no-cache",
    "build": "rm -rf dist && parcel build public/index.html"
  },
  "dependencies": {
    "@emotion/react": "^11.1.4",
    "@emotion/styled": "^11.0.0",
    "@parcel/service-worker": "^2.4.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^6.0.0"
  },
  "devDependencies": {
    "@parcel/packager-raw-url": "2.4.0",
    "@parcel/transformer-webmanifest": "2.4.0",
    "parcel": "^2.4.0"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  }
}
```

## 🤔 Expected Behavior

The service worker file should be placed directly inside the `dist` folder so it is loaded at the same level as the `index.html` file.

## 😯 Current Behavior

Parcel doesn't change the path of the service worker file and instead puts it at `dist/up_/src/service-worker.js`

## 💁 Possible Solution

I've identified [the file](https://github.com/parcel-bundler/parcel/blob/e0440dcbe6d6e419a412c8c568d94715cdb4282a/packages/namers/default/src/DefaultNamer.js#L125) where this `up_` prefix is being added, but I'm not sure how this could be altered to fix this issue.

## 🔦 Context

I have tried changing the `scope` option for the `navigator.serviceWorker.register` function to `/up_/src/`, but not only does that feel wrong, it doesn't seem to fix the issue of the `fetch` event not firing, and the website being uninstallable.

Chrome also gives me this error which is a result of the service worker not being at the root level:
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/8862273/161051889-1e40cbed-46b9-431a-aa8d-e145467327d3.png">

## 💻 Code Sample

`registerSW.js` (which I call from my index.js)
```js
navigator.serviceWorker.register(
  new URL('service-worker.js', import.meta.url),
  {type: 'module'}
)
```

`service-worker.js`
```js
addEventListener('fetch', e => {
  console.log('fetch', e.request)
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.0
| Node             | 17.4.0
| Yarn         | 1.22.17
| Operating System | Mac OS Monterey (12.2.1) M1 Silicon

**Comment by GRA0007** [comment]
Ok, previously I had this file placed in my `src` folder, but this morning in a moment of desperation I tried moving it to my `public` folder, even though this shouldn't affect anything from Parcel's side, and it worked! Somehow the service worker is now compiled into the same folder as everything else. Is this the intended behaviour? It is now in the same folder as where I run my build command, however if this is how it should behave then the docs are lacking.

**Comment by mischnic** [comment]
If you have a `<a href>` or a serviceworker declaration, Parcel tries to retain the relative url from the entry root (= where the entrypoint you pass to the CLI is = `public`) to the service worker. But that ends up being `../src/sw.js` and `..` gets sanitized into `up_`.

So since the service worker location has to have a specific location relative to the index file, I think putting it there (into `public` in your case) is the right thing here.

**Comment by GRA0007** [comment]
Ok cool, that makes sense and I understand why it's implemented this way. I think this may need to be properly documented, as placing the service worker in the src folder, with the index.html entrypoint in the public folder is a common CRA pattern. Thanks for the clarification.

**Comment by devongovett** [comment]
Maybe we should add a warning to the namer when this happens...
