### ISSUE TITLE
crc32 scope hoisting issue

### ISSUE THREAD

**Issue by cybertelx** [parcel-bundler/parcel#7882]
# 🐛 bug report

I am using a library that depends on crc-32, and it hoists crc-32 even though it makes a dynamic export. 

## 🎛 Configuration (.babelrc, package.json, cli command)

Config is all default.

## 🤔 Expected Behavior

crc-32 should not be scope hoisted.

## 😯 Current Behavior

crc-32 is scope hoisted.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'exports')
    at Object.<anonymous> (:3000/index.8ed8d0c5.js:37:1858)
    at i (:3000/index.8ed8d0c5.js:1:455)
    at Object.<anonymous> (:3000/index.8ed8d0c5.js:36:706183)
    at i (:3000/index.8ed8d0c5.js:1:455)
    at Object.<anonymous> (:3000/index.8ed8d0c5.js:36:699702)
    at i (:3000/index.8ed8d0c5.js:1:455)
    at Object.<anonymous> (:3000/index.8ed8d0c5.js:36:622197)
    at i (:3000/index.8ed8d0c5.js:1:455)
    at Object.<anonymous> (:3000/index.8ed8d0c5.js:36:620491)
    at i (:3000/index.8ed8d0c5.js:1:455)
```

line 10. factory(exports) is causing it
```
if('object' === typeof exports) {
  factory(exports);
}
```

## 💁 Possible Solution

Not sure.

## 🔦 Context

I am trying to add something to a dapp (iKeen Finance), the issue causes the entire front-end to blank out and show nothing. This only started happening a day ago.

This bug is stalling the development of the frontend.

## 💻 Code Sample

https://github.com/ikeenfi/ikeen-frontend

## 🌍 Your Environment

I believe it might be a regression from a previous Parcel version, but I'm not sure.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.1
| Node             | 16.14.0
| npm/Yarn         | 3.2.0 yarn
| Operating System | Pop!_OS 20.04 (Ubuntu 20.04)

**Comment by mischnic** [comment]
Please provide a smaller reproduction.

**Comment by TechQuery** [comment]
@mischnic An `if` condition in source code is gone in bundled code, which causes this error:

![image](https://user-images.githubusercontent.com/19969570/175956754-959eb1e2-9014-47dd-aa2c-eee6cf72a10e.png)

![image](https://user-images.githubusercontent.com/19969570/175956984-d2ce6e70-e009-4065-9b43-f460453dcdac.png)

@cybertelx 's description reminds me to [disable Scope Hoisting](https://parceljs.org/features/cli/#parameters-specific-to-build), which works for my project:

```shell
parcel build src/index.html --no-scope-hoist
```

**Comment by mischnic** [comment]
Reproduction (happens only when wrapped): 
```js
if (Date.now() > 0) {
	const crc32 = require("crc-32"); // version 0.3.0

	const crcExpect = crc32.str("xyz");
	console.log(crcExpect);
}
```
