### ISSUE TITLE
picture srcset missing space

### ISSUE THREAD

**Issue by Baswazz** [parcel-bundler/parcel#7884]
# 🐛 bug report

When creating a picture element based on the [documentation](https://parceljs.org/features/production/#image-optimization|) Parcel removes the space between the 2 images when using more than one srcset image.

Source html:
```
<picture>
  <source type="image/webp" srcset="image.jpg?as=webp&width=400, image.jpg?as=webp&width=800 2x">
  <source type="image/jpeg" srcset="image.jpg?width=400, image.jpg?width=800 2x">
  <img src="image.jpg?width=400" width="400">
</picture>
```

after running parcel:
<img width="1047" alt="Schermafbeelding 2022-04-01 om 20 24 44" src="https://user-images.githubusercontent.com/1690629/161320983-8233e537-fb12-4d60-8805-f904bf986f57.png">

When adding the space manually with the dev tools it does load the image.

## 🎛 Configuration (.babelrc, package.json, cli command)

No configuration I just run from the commandline:
`npm run parcel src/index.html`
`npm run parcel build src/index.html`

## 🤔 Expected Behavior

I would expect the space to be here so it loads the image in the browser.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.1
| Node             | v16.13.0
| npm/Yarn         | 8.1.0
| Operating System | MacOS Big Sur 11.6.5

**Comment by devongovett** [comment]
I'm going to guess that this is a bug in htmlnano, but that needs confirmation.
