### ISSUE TITLE
Unexpected token. Expected jsx identifier.

### ISSUE THREAD

**Issue by melusc** [parcel-bundler/parcel#7887]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// Default
```

## 🤔 Expected Behavior

It should be able to parse the code without erroring.

## 😯 Current Behavior

It is unable to parse the code and throws.

```none
🚨 Build failed.

@parcel/transformer-js: Unexpected token `div`. Expected jsx identifier

  C:\path\to\parcel-jsx-identifier-bug\src\script.tsx:4:20
    3 | () => {
  > 4 |   return true ? <div ref={(): void => {}}></div> : null;
  >   |                     ^^^
    5 | };
    6 |
```

## 💁 Possible Solution

\-

## 🔦 Context

I have a component <https://github.com/melusc/melusc.github.io/blob/c9d289ef239d98c9bc8d6cdd8922a345db33b31c/src/lingo/components/lingo-row.tsx#L168> that previously compiled perfectly but doesn't anymore.

## 💻 Code Sample

```ts
() => {
	return true ? <div ref={(): void => {}}></div> : null;
};
```
I have created a [minimal reproducible example](https://github.com/melusc/parcel-jsx-identifier-bug). Run `yarn build`

That code might look weird but it is the result of removing everything except what causes it to throw.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | `2.0.0-nightly.1035` / `2.4.1`
| Node             | `17.8.0`
| npm/Yarn         | `yarn@1.22.18`
| Operating System | `Windows 11`

**Comment by devongovett** [comment]
Looks like an SWC bug. Reproduces on https://swc.rs/playground with v1.2.161 but not v1.2.162, so we probably just need to update.
