### ISSUE TITLE
Suggest inline config/options for plugins

### ISSUE THREAD

**Issue by 3cp** [parcel-bundler/parcel#7889]
# 🙋 feature request

Really enjoy parcel2! The plugin system is well designed.

When I design a transformer, the consuming app needs to create a config file such as `tool.config.json` for this transformer.
But my supported config are fairly tiny. I am wondering can parcel support inline config/options in `.parcelrc`?

## 🤔 Expected Behavior

Would like to see inline config/options similar to babelrc.
```
"transformers": {
  "*.ts": [ ["@company/parcel-transformer", {"some": "options"}], "..."],
}
```

Or a more readable but verbose syntax.
```
{ "name": "@company/parcel-transformer", "config": {"some": "options"} }
```

## 😯 Current Behavior

Currently the parcelrc only expects string typed plugin name.

## 💁 Possible Solution

No idea :-)
Probably need to improve `config.getConfig` api to cover inline config too.

## 🔦 Context

Not a blocker. But this feature can avoid unnecessary tiny config files in user's app.

## 💻 Examples

NA

**Comment by 3cp** [comment]
Just found out the option `packageKey` in `config.getConfig` for storing the confing in package.json.
I can live with that.

Feel free to close this request if it's undesired.

**Comment by devongovett** [comment]
Yeah this has been discussed before, feel free to search the issues. TL;DR is that it is hard to put things in `.parcelrc` because of extended configs. It's unclear how the merging of plugin configuration would work. Keeping config in separate files or in package.json is simpler.
