### ISSUE TITLE
HMR is not working with pug extends 

### ISSUE THREAD

**Issue by NLumpov** [parcel-bundler/parcel#7892]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// .parcelrc
{
  "extends": "@parcel/config-default",
  "namers": ["parcel-namer-custom", "..."]
}

// .pugrc
{
    basedir: "./"
}

// cli-commands
{
    "serve": "parcel src/pages/*/*.pug --no-cache --log-level info",
    "build": "parcel build 'src/pages/*/*.pug' --log-level info --no-cache",
}
```

## 🤔 Expected Behavior

The page should refresh automatically

## 😯 Current Behavior

I need to manually update page to see the changes

## 💁 Possible Solution

Idk, sorry

## 🔦 Context

I'm trying to use extends to add default webpage information like doctype html, head, scripts, styles etc. for all of my pages. And when I'm trying to edit any file, that have "extends" directive, it's not updating in my browser (HMR is not working, page is not reloading). I have to manually reload a page to see the changes.

## 💻 Code Sample

```pug
// container.pug
.files-container
        block content

// index.pug
extends container

block content
        header.header I'm header
        main.body I'm body
        footer.footer I'm footer
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.0 |
| Node             | 17.0.0 |
| npm         | 8.3.2 |
| Operating System | Windows 10 Pro |

**Comment by NLumpov** [comment]
Any updates?

**Comment by NLumpov** [comment]
Topic is still relevant...

**Comment by Gagan921** [comment]
Is it resolved?
