### ISSUE TITLE
Build process are stuck in kubernetes pod (containerd)

### ISSUE THREAD

**Issue by sebtiz13** [parcel-bundler/parcel#7893]
# 🐛 bug report

The Parcel process "build" are stuck in kubernetes pod (containerd)

## 🎛 Configuration (.babelrc, package.json, cli command)

```
// Default
```

## 🤔 Expected Behavior

Process run and finish normally

## 😯 Current Behavior

Process are stuck without finish

## 🔦 Context

Process executed in kubernetes pod, see [test-kube.yaml](https://github.com/sebtiz13/parcel-test/blob/main/test-kube.yaml) manifest.
Initially I have search why gatsby build process are stuck in kubernetes pod and I have found It's stuck here https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/parcel/compile-gatsby-files.ts#L48

With more search I have found in Parcel code the process are stuck exactly in this function
https://github.com/parcel-bundler/parcel/blob/80c728ceffdc0829eca568a6ec66c07e07a0b87b/packages/core/fs/src/NodeFS.js#L118-L124

## 💻 Code Sample

https://github.com/sebtiz13/parcel-test

## 🌍 Your Environment

Cluster kubernetes (distribution k3s `v1.22.6+k3s1`) installed on Debian 11 (bullseye)

Pod image: https://hub.docker.com/_/node

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.1 |
| Node             | 16.14 / 17.8 |
| npm/Yarn         | 1.22.18 |
| Operating System | alpine / debian |

**Comment by hex2f** [comment]
I get the same behavior when trying to build with a Dockerfile and it's driving me nuts! Do you have any insight on what was causing this or is it still unknown?
