### ISSUE TITLE
`parcel build` breaks CSS animations

### ISSUE THREAD

**Issue by ThatOneCalculator** [parcel-bundler/parcel#7894]
# 🐛 bug report

Left is with `parcel build`, right is with `parcel`

![](https://media.discordapp.net/attachments/872332549777666078/960361478383370250/out.gif?width=942&height=266)

## 🎛 Configuration (.babelrc, package.json, cli command)

See: https://github.com/zer0bin-dev/zer0bin/tree/main/frontend

## 💻 Code Sample

https://github.com/zer0bin-dev/zer0bin/blob/main/frontend/style/style.scss#L224

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.1
| Node             | 16.14.0
| npm/Yarn         | 3.2.0 (yarn)
| Operating System | Linux

**Comment by devongovett** [comment]
It appears to be working for me? I cloned your repo and ran `yarn start` and `yarn build` and see the same results when hovering over the logo. I do not see the fire animation shown in the gif in either case, however.

**Comment by ThatOneCalculator** [comment]
> It appears to be working for me? I cloned your repo and ran `yarn start` and `yarn build` and see the same results when hovering over the logo. I do not see the fire animation shown in the gif in either case, however.

It's because I commented out the fire animation. Uncomment lines 243 to 288 in `style.scss` and lines 42 to 46 in `index.pug`.
