### ISSUE TITLE
@parcel/transformer-css: Unknown at rule: @use - Using Less not Sass

### ISSUE THREAD

**Issue by LukeTOBrien** [parcel-bundler/parcel#7896]
I have just updated my project to use `2.4.1` from previously `2.0.0` and there is an issue with the transforming of LESS.  
The error seems to be with the file that Parcel is generating, you can see the error is on line 460 but of course the file isn't that large, so Parcel must be combining the files first then throwing this error.  
The error is also `@use`, which must be injected by Parcel because I am using LESS not SASS.

Why does Parcel inject these `@use` lines into my Less?

# 🐛 bug report

```
🚨 Build failed.

@parcel/transformer-css: Unknown at rule: @use

  C:\My_Project\Styles\styles.less:4609:5
    4608 | }
  > 4609 | @use "sass:meta";
  >      |     ^
    4610 | @use "sass:list";
    4611 | .dx-hc {
```

The original styles.less:

```less
@import (inline) "../node_modules/bootstrap/dist/css/bootstrap.min.css";
@import (less) "../node_modules/@fortawesome/fontawesome-free/css/all.min.css";
@import (less) "../../EnterPro.Web/packages/devexpress.blazor/20.2.5/staticwebassets/dx-blazor.css";
@import (less) "../node_modules/open-iconic/font/css/open-iconic-bootstrap.css";
@import (inline) "./app.css";

@import "./Icons.less";
@import "./General.less";
@import "./Form.less";
@import "./Menu.less";
@import "./Capture.less";
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
  "devDependencies": {
    "@parcel/transformer-less": "^2.4.1",
    "@parcel/transformer-typescript-tsc": "^2.4.1",
    "less": "^4.1.2",
    "parcel": "^2.4.1",
    "parcel-resolver-ignore": "^2.0.0",
    "typescript": "^3.8.3"
  }
```

Parcelrc:

```js
{
  "extends": "@parcel/config-default",
    "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  },
  "resolvers": ["parcel-resolver-ignore", "..."]
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.1 |
| Node             | v14.17.0 |

**Comment by devongovett** [comment]
Do you have a small reproduction or code sample we can look at?
