### ISSUE TITLE
Doubled Assets in Output

### ISSUE THREAD

**Issue by jeanfortheweb** [parcel-bundler/parcel#790]
### 🤔 Expected Behavior

Hoisted assets and all of its dependencies should not get rendered twice when they are already present on ancestor level.

### 😯 Current Behavior

Hoisted assets and all of its dependencies are getting rendered inside the ancestor and children.

### 💁 Possible Solution

I've found several solutions to fix this behavior but always knowing that it must be possible a way earlier than package time. I've finally made it work with some tweaks to createBundleTree and moveAssetsToBundle which I provide as an PR to 1.4.1.

### 🔦 Context

While integrating parcel into one of our projects, with lots of dependencies and sources as also complex requirements to each other, I've noticed that the rendered asset bundles a way bigger than they should as also that React and other libraries are getting initialized more than once causing wierd behaviors.

### 💻 Code Sample

Taking the dynamic-hoist test from parcel and changing it slightly will trigger the bug.
Inside `integration/dynamic-hoist`, require `common.js` inside `index.js`file, as also removing `common.js`from `a.js` replacing the exported value with a static `2`.

Then we've created a case where a dependency is present in a child while it is already present in the common ancestor or parent. When running the test now, it will fail since the `common.js` asset will be rendered in both, `b.js` and `index.js`. Same applies for all of it's dependencies.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.4.1
| Node             | 8.x
| npm/Yarn         | 0.27.x
| Operating System | Windows/OSX

**Comment by jeanfortheweb** [comment]
Actually I've already fixed that issue for 1.4.1, but we have to discuss how I should open the PR for it.

**Comment by jeanfortheweb** [comment]
Afaik it does not, but I will verify that using my tweaked test case asap. I'll report back then.

**Comment by jeanfortheweb** [comment]
I applied the integration/mock data changes to v1.5.1 for the hoist test. Same bug. If you like to see it for yourself, just checkout my fork and:

```sh
git checkout v1.5.1
git checkout bugfix/doubled-assets -- test/integration/dynamic-hoist
yarn test test/javascript.js 
```
This will only adjust the test data as described above without changing the bundle assertion which will fail then.

Maybe add an .only for the hoist test.

**Comment by jeanfortheweb** [comment]
PR is open again, but unfortunately AppVeyor fails on two HTML tests which do not intersect with the changes. Locally, all tests run fine. Any suggestions?

**Comment by jeyj0** [comment]
Hi - is this still an issue? :)

**Comment by natew** [comment]
@jeyj0 I just tested latest parcel and I still see it. All my parent packages use the same version, but it's in a lerna-symlinked monorepo so perhaps thats it?

**Comment by thr0w** [comment]
I'm running `npm dedupe` to solve that issue
