### ISSUE TITLE
Build times don't add up

### ISSUE THREAD

**Issue by mindplay-dk** [parcel-bundler/parcel#7901]
# 🐛 bug report

Build times don't add up.

## 🎛 Configuration (.babelrc, package.json, cli command)

No special configuration, just `package.json` [here](https://github.com/mindplay-dk/inertion/blob/master/package.json).

## 🤔 Expected Behavior

Numbers should correctly add up.

## 😯 Current Behavior

```
$ npm run build

> inertion@0.1.0 build
> parcel build

✨ Built in 185ms

dist/index.d.ts     3.22 KB     60ms
dist/index.js      40.31 KB    920ms
dist/index.mjs     39.96 KB    899ms
```

`60 + 920 + 899 = 1879`, but the output says `Built in 185ms`, so one of these is off by a decimal maybe? (though not quite??)

Project is located [here](https://github.com/mindplay-dk/inertion) if you want to try it locally.

## 💁 Possible Solution

🤷‍♂️

## 🔦 Context

(project link above.)

## 💻 Code Sample

(project link above.)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | `parcel@2.4.1`, `@parcel/packager-ts@2.4.1`, `@parcel/transformer-typescript-types@2.4.1`
| Node             | `v16.14.2`
| npm/Yarn         | n/a
| Operating System | Ubuntu 16.04.7 LTS, (Release:        16.04, Codename:       xenial)

**Comment by devongovett** [comment]
They won't add up because of multi threading - some of them are built in parallel. But I guess they should all be under the total amount...
