### ISSUE TITLE
Code splitting and azure-maps-control

### ISSUE THREAD

**Issue by jptissot** [parcel-bundler/parcel#7903]
# 🐛 bug report

I am trying to use code splitting with Vue2 this works well for most libraries I am using except with the `azure-maps-viewer` package. 

Here is how the component is referenced in the main vue app where it causes an exception:
```js
Vue.component('map-viewer', () => import("./AzureMapViewer.vue"));
```

Here is how the component is referenced in the main vue app and it works fine, but the bundle is huge
```js
import AzureMapViewer from "./AzureMapViewer.vue";
Vue.component('map-viewer',AzureMapViewer);
```

The AzureMapViewer component imports the azure library like this: 

```
<template>...</template>
<script>
import * as atlas from 'azure-maps-control';
...
</script>
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js

    const parcelConfig = {
        "extends": [
            "@parcel/config-default",
            "parcel-config-vue2"
        ]
      };
    let mode = command === "build" ? "production" : "development";
    let options= {
        shouldDisableCache: false,
        mode,
        shouldContentHash: false,
        serveOptions: false,
        shouldAutoInstall: false,
        logLevel: null,
        shouldProfile:  false,
        shouldBuildLazily: false,
        detailedReport: null,
        defaultTargetOptions: {
            engines: {
                browsers: "> 1%, last 2 versions, not dead",
            },
            shouldOptimize: mode === "production",
            sourceMaps: mode === "development",
            shouldScopeHoist: false,
            distDir: assetConfig.dest,
            outputFormat: "global",
        },
        env: {
            NODE_ENV: nodeEnv,
        },
        additionalReporters: [
            {
                packageName: "@parcel/reporter-cli",
                resolveFrom: process.cwd(),
            }
        ],
    };

    let parcel = new Parcel({
        entries: 'path/to/main.js',
        config: parcelConfig,
        shouldPatchConsole: true,
        ...options,
    });
```

## 🤔 Expected Behavior

No runtime exceptions

## 😯 Current Behavior

Runtime error when referencing the atlas library.
![image](https://user-images.githubusercontent.com/4681586/161632504-815e5d5b-3659-4fab-85b4-f7a85f49b3a7.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.1
| Node             | 16.x
| npm/Yarn         | yarn 3.2
| Operating System | Windows 10

**Comment by mischnic** [comment]
Can you share a complete example that I can run? I am not familiar with Vue
