### ISSUE TITLE
Resolved package.json does not reflect resolved file

### ISSUE THREAD

**Issue by wbinnssmith** [parcel-bundler/parcel#7908]
Consider the following tree:

```
foo/
  package.json {sideEffects: false}
  real-bar.js
  bar/
    package.json {main: '../real-bar.js', has no defined sideEffects property}
```

Intuitively, it seems that real-bar.js's sideEffects value should be `false`, not `undefined`, as it's a child of the foo directory, which has a package.json defining `"sideEffects": false`. 

However, when `import 'foo/bar'` is currently resolved, it resolves correctly to `foo/real-bar.js`, but the associated package.json for the asset is `foo/bar/package.json`, not `foo/package.json`. This makes `foo/real-bar.js`'s sideEffects value `undefined` when it's required as `import 'foo/bar'`, but it's `false` when it's required as `import 'foo/real-bar.js'` (or `import './real-bar.js'` or similar).

We should consider conditionally re-resolving an asset's package.json when the initially resolved package.json points to a module that would otherwise resolve a different package.json.

cc @mischnic @devongovett @thebriando

**Comment by mischnic** [comment]
I think the proposed way makes sense, in any case we should do what the other tools do
