### ISSUE TITLE
Symbol.toStringTag

### ISSUE THREAD

**Issue by geoynomous** [parcel-bundler/parcel#7911]
# 🐛 bug report

Getting this error message from graphql npm package during optimization only (@parcel/optimizer-terser)

```
node_modules/.pnpm/graphql@16.3.0/node_modules/graphql/language/ast.js:108:7
    107 | 
  > 108 |   get [Symbol.toStringTag]() {
  >     |       ^ "\_toStringTag" is redeclared
    109 |     return 'Token';
    110 |   }

  💡 It's likely that Terser doesn't support this syntax yet.
```

If I commented out all the occurrences of Symbol.toStringTag the optimizer works through. This element is well known: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag

## 🎛 Configuration (.babelrc, package.json, cli command)

Rather default setup

## 🤔 Expected Behavior

The optimizer finishes without a problem

## 😯 Current Behavior

The optimizer does report a problem of 'redeclaration' - but as said: When commenting out it works. But it does not work when a single Symbol.toStringTag is left. It seems to me that the string "Symbol.toStringTag" has been falsely identified as an identifier, and not as a 'function' that has dynamic value - depending on where it is called. And thus it finds 'redeclarations'

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.2
| Node             | 16.14.2
| pnpm         |  6.32.4
| Operating System | macOS

**Comment by mischnic** [comment]
Please provide a reproduction. Building this file works fine for me:
```js
import * as gql from "graphql";

console.log(gql)
```

**Comment by geoynomous** [comment]
I am trying to strip an example .. is there a way for more debug output of the terser? Like why it is found a 'redeclared' ... would be good to know where it was FIRST declared?

**Comment by mischnic** [comment]
swc generates this output once per input asset
```js
let _toStringTag = Symbol.toStringTag;
class Token {
    get [_toStringTag]() {
        return 'Token';
    }
}
```

There's a similar problem with https://github.com/parcel-bundler/parcel/issues/7101.

Reproduction:
```js
// a.js
import {B} from "./b.js";
import {C} from "./c.js";
console.log(B, C)

// b.js
export class B {
  get [Symbol.toStringTag]() {
    return 'Token';
  }
}

// c.js
export class C {
  get [Symbol.toStringTag]() {
    return 'Token';
  }
}
```
package.json:
```json
{
  "browserslist": "Chrome 60"
}
```

**Comment by geoynomous** [comment]
[demo.zip](https://github.com/parcel-bundler/parcel/files/8427357/demo.zip)

There is a minimal example when run with `npx parcel build index.html `

The problem appears with

```
  "browserslist": [
    "> 2%",
    "last 2 versions",
    "not dead",
    "not ie 11"
  ],
```
but disappears with 

```
   "browserslist": [
    "> 3%",
    "last 2 versions",
    "not dead",
    "not ie 11"
  ],

```
Checking next what is the diff between them

**Comment by geoynomous** [comment]
Ok ... it is this:

ios_saf 15.0-15.1
ios_saf 14.5-14.8

**Comment by onionhammer** [comment]
I'm getting the same issue with a pretty boilerplate 'hello world' app with urql and graphql

**Comment by halvardssm** [comment]
I'm facing the same issue, is there any workaround or fix for this?

**Comment by alippai** [comment]
@devongovett do you have a plan for a 2.5.1 or 2.6.0 release?
