### ISSUE TITLE
Parcel build doesn’t create distribution directory

### ISSUE THREAD

**Issue by geolal** [parcel-bundler/parcel#7912]
# 🐛 bug report

I install parcel, I run the build script, the server starts to run, but no distribution directory is created. Had the same outcome with more than one configurations.

## 🎛 Configuration (.babelrc, package.json, cli command)

- package.json A:
```js
{
  "name": "myapp",
  "main": "index.html",
  "scripts": {
      "start": "parcel index.html",
      "build": "parcel build index.html"
  },
  "devDependencies": {
      "parcel": "^2.2.1",
      "sass": "^1.26.10"
  }
}
```

- package.json B:
```js
{
  "name": "myapp",
  "default": "index.html",
  "browserslist": "> 0.5%, last 2 versions, not dead",
  "targets": {
    "main": false
  },
  "scripts": {
    "start": "parcel index.html",
    "build": "parcel build index.html --dist-dir ./dist"
  },
  "devDependencies": {
    "@parcel/transformer-sass": "^2.2.1",
    "parcel": "^2.2.1"
  },
  "dependencies": {
    "fracty": "^1.0.9"
  }
}
```
Used commands:
`npm i`
`npm start`

## 🤔 Expected Behavior

When it runs for the first time should create a dist directory that contains all the compiled files.

## 😯 Current Behavior
The build script runs, but no dist directory is created. The following screenshot is after using package.json B:
![A_2022-03-30_22-01-34-e9fd75d599e370b6c0a976a01c4efd4c](https://user-images.githubusercontent.com/70756606/162021919-04108e25-0396-43cb-bd5e-f76f77ea9622.png)

It succeeded only once to create a dist directory, when I installed parcel using the complete project, and exact the same configuration. As it seems, it installs an older version of lmdb (2.1.7 instead of 2.2.4):
![B_2022 03 31 package json - final - Visual Studio Code](https://user-images.githubusercontent.com/70756606/162021947-7b7467bd-6968-4d60-a491-02dc391bfd72.png)

However installing parcel from that specific _package-lock.json_ for a new project with `npm ci`, it again did not succeed to create a dist folder:
![C_2022-04-01 - last installation](https://user-images.githubusercontent.com/70756606/162021959-25b14446-8994-420a-80d7-4b924fde4551.png)

## 💁 Possible Solution

have no idea

## 💻 Code Sample

[https://github.com/jonasschmedtmann/complete-javascript-course/tree/updates-and-fixes/18-forkify/starter](https://github.com/jonasschmedtmann/complete-javascript-course/tree/updates-and-fixes/18-forkify/starter)
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.2.1
| Node             |v14.17.0 and v16.14.2
| npm/Yarn         |6.14.13 and 8.5.0
| Operating System |Windows 10

I updated my node.js to the current version, but nothing changed at all.

**Comment by mischnic** [comment]
Remove both `"main": "index.html"` and `"default": "index.html"`

https://parceljs.org/getting-started/migration/#package.json%23main

**Comment by geolal** [comment]
Excuse me for the delay,
I removed these lines from both the above package.json files, then tried them both, but again, dist folder wasn’t created. Here is with package.json A:

![package json A](https://user-images.githubusercontent.com/70756606/163847375-94481cb8-124c-4b53-acda-15a7d6c5d1d1.png)

**Comment by ThatBlokeCalledJay** [comment]
Hey guys, just want to chime in as I am experiencing the same thing within the same environment parameters.
