### ISSUE TITLE
Unexpected lazy behavior on execution of dynamically imported code

### ISSUE THREAD

**Issue by Foolyou** [parcel-bundler/parcel#792]
a 🐛 bug report

### 🎛 Configuration
Nothing special, just following code.

```html
<!-- index.html -->
<script src="loader.js"></script>
```
```js
// loader.js

async load() {
    import('./test.js');
}

load();
```
```
// test.js
console.log('test');
```
and then `parcel index.html`.

### 🤔 Expected Behavior
It should log `test` in console (Chrome and Webpack done this correctly).

### 😯 Current Behavior
It shows nothing, as the dynamically imported module `test.js` is wrapped with `LazyPromise` and not evaluated immediately after loaded.

Currently, you can add `.then` or `await` to that dynamic import, to force it evaluate. 
However it's not convenient when you just what to load a css file and doesn't care when it will be loaded.
```js
// loader.js

// this logs `test` correctly.
async load() {
    await import('./test.js');
}

load();
```

**Comment by avilapedro** [comment]
Hi!

It is actually expected:

> Dynamic imports are also lazily loaded in Parcel, so you can still put all your import() calls at the top of your file and the child bundles won't be loaded until they are used.
>
> -- <cite>https://en.parceljs.org/code_splitting.html</cite>

Also:

> Here you can see how `import()` enables lazy-loading modules upon navigation in a very simple single-page application:
>
> -- <cite>https://github.com/tc39/proposal-dynamic-import#example</cite>
