### ISSUE TITLE
Wrapping modules changes invocation of exported functions

### ISSUE THREAD

**Issue by wbinnssmith** [parcel-bundler/parcel#7920]
[Example on the repl](https://parcel2-repl.vercel.app/#JTdCJTIyY3VycmVudFByZXNldCUyMiUzQSUyMkphdmFzY3JpcHQlMjIlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIybWluaWZ5JTIyJTNBZmFsc2UlMkMlMjJzY29wZUhvaXN0JTIyJTNBdHJ1ZSUyQyUyMnNvdXJjZU1hcHMlMjIlM0FmYWxzZSUyQyUyMnB1YmxpY1VybCUyMiUzQSUyMiUyRl9fcmVwbF9kaXN0JTIyJTJDJTIydGFyZ2V0VHlwZSUyMiUzQSUyMmJyb3dzZXJzJTIyJTJDJTIydGFyZ2V0RW52JTIyJTNBbnVsbCUyQyUyMm91dHB1dEZvcm1hdCUyMiUzQW51bGwlMkMlMjJobXIlMjIlM0FmYWxzZSUyQyUyMm1vZGUlMjIlM0ElMjJwcm9kdWN0aW9uJTIyJTJDJTIycmVuZGVyR3JhcGhzJTIyJTNBZmFsc2UlMkMlMjJ2aWV3U291cmNlbWFwcyUyMiUzQWZhbHNlJTJDJTIyZGVwZW5kZW5jaWVzJTIyJTNBJTVCJTVEJTdEJTJDJTIyYXNzZXRzJTIyJTNBJTVCJTVCJTIyc3JjJTJGaW5kZXguanMlMjIlMkMlMjJpbXBvcnQlMjAlN0JidG9hJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZvdGhlci5qcyU1QyUyMiUzQiU1Q25jb25zb2xlLmxvZyhidG9hKCdmb28nKSklM0IlMjIlMkMxJTVEJTJDJTVCJTIyc3JjJTJGb3RoZXIuanMlMjIlMkMlMjJleHBvcnQlMjBjb25zdCUyMGJ0b2ElMjAlM0QlMjB3aW5kb3cuYnRvYSUzQiU1Q24lNUNuZXZhbCgnJyklM0IlMjIlNUQlNUQlN0Q=)

index.js:

```js
import {btoa} from "./other.js";
console.log(btoa('foo'));
```

other.js:

```js
export const btoa = window.btoa;

eval(''); // to force wrapping
```

This causes `btoa` to be invoked as a method, which apparently breaks its invocation: `console.log($9bb2a74c22793326fe949cf11616aca2$exports.btoa('foo')); // TypeError: Illegal invocation`

**Comment by wbinnssmith** [comment]
Since it's invoked differently it changes the value of `this` when other.js is defined like:

```js
export const btoa = function() {
  console.log(this);
}
eval('')
```

...depending on if the asset is wrapped or not. In the wrapped case, `this` is the module exports, otherwise it's `window` in browsers. We should run with an `undefined` `this` value when running imported named free functions.

**Comment by gorakong** [comment]
the repro has been converted to a test case in the branch `gkong/exported-free-functions` for anyone interested in tackling this
