### ISSUE TITLE
Parcel changes the name of a variable mid-function, making it throw

### ISSUE THREAD

**Issue by danieltroger** [parcel-bundler/parcel#7930]
# 🐛 bug report

In parcels output a function that accepted a function called `a_function` and then called it is transformed to a function that takes `a_function` and then calls `_a_function` which results in `ReferenceError: _a_function is not defined`.

## 🎛 Configuration (.babelrc, package.json, cli command)

Please see attached .zip file (run `yarn build`)

## 🤔 Expected Behavior

`default` is logged to the console

## 😯 Current Behavior

An error is thrown (`ReferenceError: _a_function is not defined`)

## 💁 Possible Solution

Make so that the variable doesn't randomly change name

## 🔦 Context

Updated parcel and now our IE11 builds are causing lots of errors in Sentry since they're failing in older browsers

## 💻 Code Sample

Please see this zip file: 
[parcel-broken-code.zip](https://github.com/parcel-bundler/parcel/files/8457173/parcel-broken-code.zip)

<details>
<summary>The code specifically which causes this:</summary>

```typescript
export const call_callback = (callback: () => Promise<void>) => callback();

function do_stuff(a_function: () => Promise<string> | string) {
  call_callback(async () => {
    labeled_block: {
      const mode = new URL(location.href).searchParams.get("mode");

      if (mode === "1") {
        a_function = () => "foo";
        break labeled_block;
      }
      const needed_for_next_condition = window?.heavy_function?.();
      if (needed_for_next_condition === "45") {
        a_function = () => "bar";
      }
    }

    const result = await a_function();
    console.log(result);
  });
}

do_stuff(() => "default");
```
</details>

<details>
<summary>What it's transformed to:</summary>

```typescript
function $5d135640d0b2a531$var$do_stuff(a_function) {
    $5d135640d0b2a531$export$6ae453fb2c673521(/*#__PURE__*/ (/*@__PURE__*/$parcel$interopDefault($08e99458bf6688f9$exports))(/*#__PURE__*/ (/*@__PURE__*/$parcel$interopDefault($56d1eef5cdc65a5e$exports)).mark(function _callee() {
        var _window, _window$heavy_functio, mode, needed_for_next_condition, result;
        return (/*@__PURE__*/$parcel$interopDefault($56d1eef5cdc65a5e$exports)).wrap(function _callee$(_context) {
            while(true)switch(_context.prev = _context.next){
                case 0:
                    mode = new URL(location.href).searchParams.get("mode");
                    if (!(mode === "1")) {
                        _context.next = 4;
                        break;
                    }
                    _a_function = function a_function() {
                        return "foo";
                    };
                    return _context.abrupt("break", 6);
                case 4:
                    needed_for_next_condition = (_window = window) === null || _window === void 0 ? void 0 : (_window$heavy_functio = _window.heavy_function) === null || _window$heavy_functio === void 0 ? void 0 : _window$heavy_functio.call(_window);
                    if (needed_for_next_condition === "45") _a_function = function a_function() {
                        return "bar";
                    };
                case 6:
                    _context.next = 8;
                    return _a_function();
                case 8:
                    result = _context.sent;
                    console.log(result);
                case 10:
                case "end":
                    return _context.stop();
            }
        }, _callee);
    })));
}
$5d135640d0b2a531$var$do_stuff(function() {
    return "default";
});
```
</details>

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.1041+39b330e74
| Node             |v17.8.0
| npm/Yarn         |yarn 3.2.0
| Operating System |macOS 12.2 (21D49)

**Comment by mischnic** [comment]
[Transpiling the output from Babel with standalone swc works](https://play.swc.rs/?version=1.2.157&code=H4sIAAAAAAAAA51U0U7CMBR95yuu1YdiyAZCQpSQ%2BGJ8NQafm27cwWJpl7YTjeHf7WAbpZs%2BuJetJ%2Fece%2B652%2FJdobQFxs2XTFfqGSVqbpWGTKsdkMeEJyhiXUqb7zDeoihQmzisJotBXgtp3DTo64nVL%2BXVOfYgK2VqcyVhrZixZZZRzhpsCN8D6FqkDgSIb68Ze3l7fWLsNu5rH%2B24fqetPku5EIj0JFpdGm2pZS91r3nRod5Qlipp8dOeNQD221wg0ImPAZh9btMt0JYSFRo%2FYAntWVY6lySAlBuE8cMFBpBnQK%2FoRqiEi9U2N1HCNSyXSyAT0pGorosmrul00SlJNPL3ED4MAuC8C6fSPp5R2te9zpVkSpFOh0XYotlCY5knuiwsJUeDZASzYUA5ZjTty8hLyPU%2BJXRH%2Biz%2Ba67zZC7%2FzmTH2f6M82h8FhpvB7dj58UdjBIYKoULnYcFtTN%2Fgr7Y5r93n%2Fgvp0FpO5vynEZCbaLqq6AeOPLVetvfP3QxgnJNQlvhS2GsKqqJ%2FGzDp8Oo%2BVDrwsPQ3YYVzS2i%2Fb2026533Ox0jRkvhXV7PTjGDzX2uKEfBQAA&config=H4sIAAAAAAAAA02OMQ6DMAxFr1J5zlAYGJi7cggrGJqKJMg2VRHK3ZtQEN2s7%2FefvcFLLLQbzMhCXCZZg%2BIHWiDrUSy7WcFkLEcDTkLJgDIGGSL7wk80ol0fZCOjxqxQXshAfwYdKfao%2BFdHHknLBanvdZXtU4xCB2DAu%2BCGtbht9DOTyLXCME4nmbLLx34pwQa6zrQ7G0iX4%2Bg56Q7w9x2F997ZP8l6sE%2BOnm5NBSl9ARDjxrEVAQAA), so there is a bug on the Parcel side.

**Comment by danieltroger** [comment]
@mischnic is the swc tag correct if it's a parcel bug?

**Comment by mischnic** [comment]
Well, it's related to swc. Not matter if it's Parcel using swc incorrectly or an actual swc bug

**Comment by danieltroger** [comment]
Ah, I see. Didn't understand that parcel doesn't do that much itself anymore

**Comment by mischnic** [comment]
(And specifically, we reuse swc's regenenerator transform.)

Could you verify that this is fixed with the latest nightly? As far as I can tell, it's failing with `2.5.0` and working with `2.0.0-nightly.1094`

**Comment by danieltroger** [comment]
Nice, it seems to be fixed in the latest nightly!
