### ISSUE TITLE
What's the reason for clearing the console on a failed build?

### ISSUE THREAD

**Issue by kkirby** [parcel-bundler/parcel#7940]
I'm referring to this code here:

https://github.com/parcel-bundler/parcel/blob/8daaed8a8c263635ef9e6c678fd92fef8c042c74/packages/reporters/cli/src/CLIReporter.js#L121

Having the console be cleared usually prevents seeing any kind of build errors that occurred, so debugging the failure is pretty difficult.

**Comment by devongovett** [comment]
It clears before printing the error message though, so you should still see it?

**Comment by kkirby** [comment]
It depends on who or what generated the error. What prompted me to create the issue is my build was failing with a cryptic error message: `@parcel/transformer-typescript-types: Got unexpected undefined`. And that's all it said. If I removed the `resetWindow()`, I got substantially more information and was able to fix the problem.

Before:
![CleanShot 2022-04-13 at 11 07 59@2x](https://user-images.githubusercontent.com/34333/163223524-411fb2a5-eb31-46fc-83e4-0bafb29a32a2.png)

After:
![CleanShot 2022-04-13 at 11 05 57@2x](https://user-images.githubusercontent.com/34333/163223545-10f6570c-181a-4f55-8928-d15e4c5bd841.png)

**Comment by devongovett** [comment]
Hmm not sure. I think those are separate warnings possibly not related to the error. So would showing them be more confusing?

**Comment by kkirby** [comment]
Well, the problem was that transformer-typescript-types was failing due to typescript failing, because there was missing type information. And I was only able to figure that out once I saw the warnings that had been cleared. I don't see the benefit of clearing out any warnings that have occurred. There's no way to tell if it attributed to the final error or not, but hiding them on an error seems counterintuitive to me.

Also, running typescript manually worked fine because typescript takes into account all files when compiling. But the typescript types transformer seems to be handling each file one at a time, so type information that is kept inside a d.ts file doesn't get resolved automatically.

**Comment by jackw** [comment]
I've spent a bit of time trying to migrate some libraries of a typescript monorepo from rollup to parcel and clearing these typescript warnings is causing a lot of headaches as it's impossible to understand what went wrong from `@parcel/transformer-typescript-types: Got unexpected undefined`. Maybe we could pass a flag to the reporter which would prevent it from clearing the window perhaps?

Is there a way I can disable this in a yarn berry pnp project to see the typescript warnings / errors? I tried mounting the yarn berry cache zip files in VS Code and removing the `resetWindow` calls but it seems to persist even after i unmount them. I also tried `--log-level` but that hasn't helped either. Could I write a "debug" reporter to be used in place of the cli reporter? (Sorry for these questions I'm very new to Parcel.)

**Comment by mischnic** [comment]
If you're on Unix, you can do `yarn parcel build index.js | cat` as a workaround. That will disable the clearing (though it will also disable colors).

**Comment by nCrazed** [comment]
Running into similar issue of loss of necessary context to debug build failure

**Comment by svallory** [comment]
This is still an issue in 2023. Is it possible to add a flag so output is NEVER cleared?
