### ISSUE TITLE
Bundle-text pipeline interferes with standard css import

### ISSUE THREAD

**Issue by astegmaier** [parcel-bundler/parcel#7941]
# 🐛 bug report

If you import a css file with the `bundle-text` pipeline (e.g. `import shadowStyles from "bundle-text:./shadow-dom-styles.css"`), and then (elsewhere) import a different css file with a standard global import (e.g. `import "./styles.css";`), you'll get the contents of _all_ the css imports in the `bundle-text` results, and nothing added globally.

## 🎛 Configuration (.babelrc, package.json, cli command)

***styles.css***
```css
.hello {
    color: blue;
}
```
***shadow-dom-styles.css***
```css
.goodbye {
    color: red;
}
```

***index.js***
```js
// BUG: shadowStyles will contain styles from _both_ shadow-dom-styles.css (expected) AND styles.css (unexpected).
// styles.css will not be referenced from the global DOM.
import shadowStyles from "bundle-text:./shadow-dom-styles.css";
import "./styles.css";
```

***index.html***
```html
<html>
  <body>
    <script src="./index.js" type="module"></script>
  </body>
</html>
```

## 🤔 Expected Behavior

`styles.css` is referenced at the root of the DOM with a `<style>` tag, and the contents of `shadow-dom-styles.css` are inlined as a string assigned to the `shadowStyles` variable.

## 😯 Current Behavior

The contents of _both_ `styles.css` and `shadow-dom-styles.css` are inlined as a string assigned to `shadowStyles`, and nothing is added to the root of the DOM.

## 💁 Possible Solution

Not really sure at this point.

## 🔦 Context

I was trying to help answer [this question on stackoverflow](https://stackoverflow.com/questions/71260911/parceljs-with-bundle-text-css-import-is-not-working).

## 💻 Code Sample

See [this github repo](https://github.com/astegmaier/stackoverflow-parcel-bundle-text-bug) for a simplified reproduction.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.1
| Node             | 14.18.2
| Yarn         | 1.22.17
| Operating System | Windows 11 / 10.0.22000 Build 22000

**Comment by ianhitchman** [comment]
While I'm able to avoid importing css, this issue means it's not possible to use bundle-text while also using npm packages that import their css. I'm using bundle-text to manipulate SVG files, but it breaks as soon as a package is used that uses import for css (in my case, fullcalendar).

Is there another way in Parcel to extract the text contents of a file, other than bundle-text? I've tried the nodejs fs.readFileSync, but couldn't get that working.

**Comment by mischnic** [comment]
If just reading the file contents are enough for you then yes, readFileSync should work: https://parceljs.org/features/node-emulation/#inlining-fs.readfilesync

The difference with bundle-text is that it first processes/transpiles the file before inlining.

**Comment by ianhitchman** [comment]
Thank you for the help. I was getting errors with that, but I'll give it another go.
