### ISSUE TITLE
Connection refused on --port 8081 and on --hmr-port 8082

### ISSUE THREAD

**Issue by Richard87** [parcel-bundler/parcel#7942]
# 🐛 bug report

When using `parcel serve`, no actuall tcp ports are opened. both the regular port, and the hmr-port is closed.

## 🎛 Configuration (.babelrc, package.json, cli command)

yarn run parcel serve --cache-dir ../.parcel-cache --dist-dir ../backend/public/build2 --port 8081 --hmr-port 8082 --host localhost --public-url http://localhost:8081/build2

```js
  "targets": {
    "app": {
      "source": "./assets/State/index.js",
      "distDir": "../backend/public/build2"
    },
    "styles": {
      "source": "./assets/global.css",
      "distDir": "../backend/public/build2"
    }
  },
```

## 🤔 Expected Behavior

Port should be open, and probably give me a 404 :) 

## 😯 Current Behavior

Connection refused, with curl, chrome, firefox... netstat does not list the port as open

## 💁 Possible Solution

No idea, makes no sense that it hasnt been reported by any other :O  Could it be MacOs 12, M1 issue? Any other services works nice, also nodejs projects, create-react-app, webpack-dev-server etc works as expected.

## 🔦 Context

Testing out Parcel 2.4.1, trying out a really fast dev-server that runs along-side my PHP server (port 8000, works nicely)

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v.2.4.1 |
| Node             |  17.3.1
| npm/Yarn         | yarn 1.22.17
| Operating System | MacOS 12.2.1 / 12.3.1 M1 (many reboots)

Also tried disabling MacOS firewall, without any change...

**Comment by Richard87** [comment]
I was using this .parcelrc file:
```json
{
  "extends": "@parcel/config-default",
  "reporters": ["parcel-reporter-bundle-manifest"]
}
```
The missing `"..."` was the cause of the issue, including it like this, solves my problem:
```json
{
  "extends": "@parcel/config-default",
  "reporters": ["...", "parcel-reporter-bundle-manifest"]
}
```

Test repo: https://github.com/Richard87/parcel-test

**Comment by dagnelies-elo** [comment]
Oh man... this costed me many hours 🤯 . Thanks for the solution.

It's so unintuitive that everything breaks when adding a reporter. The console should at least shout a big fat warning! 😠
