### ISSUE TITLE
Using Parcel in (rush) monorepo breaks flow. `projectRoot` should also resolve for `package.json`

### ISSUE THREAD

**Issue by alber70g** [parcel-bundler/parcel#7947]
# 🐛 bug report
When using Rushjs monorepo, with PNPM, we have a separate lock-file and store from which packages are symlinked into node_modules. So there's no lock file in the package. Therefore it'd be good to have the `projectRoot` resolver, look at `package.json` or have it passed to the commandline.

https://github.com/parcel-bundler/parcel/blob/v2/packages/core/core/src/resolveOptions.js#L54-L60

```diff
  let projectRootFile =
    (await resolveConfig(
      inputFS,
      path.join(entryRoot, 'index'),
-      [...LOCK_FILE_NAMES, '.git', '.hg'],
+      [...LOCK_FILE_NAMES, '.git', '.hg', 'package.json'],
      path.parse(entryRoot).root,
    )) || path.join(inputCwd, 'index'); // ? Should this just be rootDir

```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
Can you describe your project structure in more detail and the problems you're running into?

package.json should definitely not be listed in there (at least not by default): https://github.com/parcel-bundler/parcel/issues/7579#issuecomment-1098038157
