### ISSUE TITLE
NPM Publish Latest for Babelrc / node_modules fix

### ISSUE THREAD

**Issue by SilentCicero** [parcel-bundler/parcel#795]
Hi Parcel Team,

Can you publish the latest master, or when will that happen / be scheduled?

Really dying for that babelrc (getting into node_modules) fix. Literally will do anything for it. Anything in the world. Npm publish. Please.

Loving parcel. Thanks!

**Comment by davidnagli** [comment]
@devongovett

**Comment by lbguilherme** [comment]
As workaround, you can do:

```sh
yarn remove parcel-bundler
yarn add https://github.com/parcel-bundler/parcel
cd node_modules/parcel-bundler
yarn
cd ../..
```

**Comment by brandon93s** [comment]
A 1.6 release is being targeted for this week.

**Comment by SilentCicero** [comment]
Fastest issue in history ;) Thanks guys! @lbguilherme what about with NPM, sorry, against facebook packager :( too much power ;)

**Comment by davidnagli** [comment]
@SilentCicero “too much power” haha true 😂 

Ya yarn is totally optional, you can do the same using npm using `npm link`. I’ve never done it with npm myself, but 99% sure this should work:
```
# Get rid of the npm installed version of Parcel
npm uninstall -g parcel

# Clone the repo
git clone https://github.com/parcel-bundler/parcel.git
cd parcel

# Tell npm to use the repo version of Parcel
npm link
```

Some more info on how `npm link` works: [link | NPM Documentation](https://docs.npmjs.com/cli/link)

Hope this helps 😃

**Comment by brandon93s** [comment]
Cloning and using npm link is overkill. You can install from git using `npm` just like you can with `yarn`. `npm install {GitHub repo link}`.
