### ISSUE TITLE
Build result without type="module"

### ISSUE THREAD

**Issue by Dr-Chaos** [parcel-bundler/parcel#7959]
# 🙋 feature request

I have a script in my `<head>` that I want to execute synchronously (before the rest of the code and HTML), because I need a render blocking script:
```html
<head>
  <script src="index.js"></script>
  ...
</head>
```
But Parcel force me to use `type="module"` and then the script become defered

If I watch the code produces  with `parcel build`, I can see a js bundle for nomodule. I want to be able to use this bundle even if my browser is compatible with ES Modules

## 🤔 Expected Behavior
After run `parcel build`, just have a single bundle: 
```html
<script src="/index.js"></script>
````

## 😯 Current Behavior

```html
<script src="/index.111.js" type="module"></script>
<script src="/index.222.js" nomodule="" defer></script>
````

## 💁 Possible Solution

Add a CLI flag to disable differential bundling and produce a single bundle.js (like many other bundlers)

**Comment by mischnic** [comment]
You can still have a script without `type="module"`, you just can't use synchronous `import` or `require`: https://parceljs.org/languages/javascript/#classic-scripts

**Comment by NothingEverWorks** [comment]
> you just can't use synchronous `import` or `require`

That is not a useful alternative.

This feature request is actually a duplicate of https://github.com/parcel-bundler/parcel/issues/7583, which luckily is still open.

I've created a workaround in the following repo. https://github.com/NothingEverWorks/parcel-local-html
The workaround fixes the script tags after bundling by using the nomodule index.js output from the differential bundling, that already works with the `file:///` procotol and supports synchronous `import`!

**Comment by Ivanca** [comment]
This also means that you cannot using top-level async calls, instead one has to wrap them manually.

![image](https://user-images.githubusercontent.com/907138/212201247-cb4757ae-b54a-4861-8dd4-7863f64ae97e.png)

Parcel sells itself as the out-of-the-box alternative and then do stuff like this where it completely subvert basic expectations such as leaving `type="module"` intact, "Nothing Ever Works"... indeed.
