### ISSUE TITLE
Dead-code elimination of unused default parameters

### ISSUE THREAD

**Issue by bitjson** [parcel-bundler/parcel#7961]
# 🙋 Feature Request

During dead-code elimination/tree shaking, default parameters that aren't used by the bundle can be removed. 

## 🤔 Expected Behavior

For this simple example:

`module.js`:
```js
const internalAdd = (a, b) => (a === '0' ? b : a + b); // should not appear in bundle
export const addAndLog = (a, b, impl = internalAdd) => console.log(impl(a, b));
```

`app.js`:

```js
import { addAndLog } from './module.js';
const myAdd = (a, b) => a + b;
addAndLog(1, 2, myAdd); // => 3
```

The produced bundle should include only:
```js
const addAndLog = (a, b, impl) => console.log(impl(a, b));
const myAdd = (a, b) => a + b;
addAndLog(1, 2, myAdd); // => 3
```

## 😯 Current Behavior

Currently, parcel bundles the dead code:

```js
const internalAdd = (a, b) => (a === '0' ? b : a + b); // should not appear in bundle
const addAndLog = (a, b, impl = internalAdd) => console.log(impl(a, b));
const myAdd = (a, b) => a + b;
addAndLog(1, 2, myAdd); // => 3
```

## 🔦 Context

I maintain [Libauth](https://github.com/bitauth/libauth/), a library that offers WebAssembly crypto implementations (`ripemd160`, `sha1`, `sha256`, `sha512`, and `secp256k1`). As a [pure ESM library](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c), Libauth can asynchronously instantiate each WASM implementation internally, exporting simple interfaces that behave like collections of JS-only functions (with better performance). Many of Libauth's exported functions also use one of these built-in WASM instances as a default parameter. For example, `decodeBase58Address` has the definition:

```ts
export const decodeBase58Address = (
  address: string,
  sha256: { hash: (input: Uint8Array) => Uint8Array } = internalSha256
) => {
  // ...
};
```

Most applications can call `decodeBase58Address(address)` to automatically use the default, WASM-based `sha256` implementation (`internalSha256`).

However, applications that already have another `sha256` implementation can provide that implementation as the second parameter: `decodeBase58Address(address, mySha256Implementation)`. In this case, the default parameter (`internalSha256`) is dead code, and should be possible to eliminate from the application's bundle, saving hundreds of KBs from those bundles.

## 💻 Examples

A detailed example (testing with all known bundlers) is available at this repo: https://github.com/bitjson/shake-default-params

**Comment by mischnic** [comment]
I agree with https://github.com/evanw/esbuild/issues/2185#issuecomment-1100512969. The only DCE done by Parcel itself is excluding unused files (if they have `sideEffects: false`). Apart from that it just tries to transform as many imports into regular top-level functions calls as possible (and not with a namespace object as i.e. Babel does `_module.addAndLog()`). The actual dead code is then removed by Terser/whatever minified you want to use afterwards. 

Right now, Terser turns
```js
const internalAdd = (a, b) => "dead";
const addAndLog = (impl = internalAdd) => console.log(impl(1, 2));
addAndLog(3)
```
into
```js
const o=(o,c)=>"dead";((c=o)=>{console.log(c(1,2))})(3);
```

**Comment by bitjson** [comment]
Thanks for the info @mischnic! I just opened an issue for `terser`: https://github.com/terser/terser/issues/1199

For anyone finding this issue before Parcel/terser support this optimization, Rollup [will support tree-shaking default parameters](https://github.com/rollup/rollup/issues/4466#issuecomment-1126194068); the PR is here: https://github.com/rollup/rollup/pull/4498).
