### ISSUE TITLE
Could not resolve module @parcel/css/parcel-css.linux-x64-musl.node

### ISSUE THREAD

**Issue by hvolschenk** [parcel-bundler/parcel#7962]
# 🐛 bug report

```sh
Building...
🚨 Build failed.

@parcel/transformer-css: Could not resolve module
"/home/node/application/node_modules/@parcel/css/parcel-css.linux-x64-musl.node"
from "/home/node/application/node_modules/@parcel/css/node/index.js"
```

## 🎛 Configuration (.babelrc, package.json, cli command)

CLI command:

```sh
$ parcel index.html
```

## 🤔 Expected Behavior

The build should succeed.

## 😯 Current Behavior

When running the command inside Docker:

```sh
$ parcel index.html
```

I get the following error:

```sh
Error: Could not resolve module
"/home/node/application/node_modules/@parcel/css/parcel-css.linux-x64-musl.node"
from "/home/node/application/node_modules/@parcel/css/node/index.js"
at $0578d0f6e116167e$export$fb2a0b866a8162dc.resolve
(/home/node/application/node_modules/@parcel/package-manager/lib/index.js:4919:21)
at NodePackageManager.resolveSync
(/home/node/application/node_modules/@parcel/package-manager/lib/index.js:3510:42)
at NodePackageManager.requireSync
(/home/node/application/node_modules/@parcel/package-manager/lib/index.js:3351:34)
at Module.m.require
(/home/node/application/node_modules/@parcel/package-manager/lib/index.js:3365:25)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous>
(/home/node/application/node_modules/@parcel/css/node/index.js:21:22)
at Module._compile (node:internal/modules/cjs/loader:1103:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at NodePackageManager.load
(/home/node/application/node_modules/@parcel/package-manager/lib/index.js:3374:15)
```

## 💁 Possible Solution

No idea.

## 🔦 Context

I am running everything here inside a `fermium-alpine` Docker environment,
although the same happens in a `node:gallium-alpine` environment.

I started seeing the issue about a week ago, maybe a little less,
There is also a _Pull Request_ available with everything at latest [here](https://github.com/hvolschenk/small-glade/pull/51).

## 💻 Code Sample

The full codebase can be seen at [small-glade](https://github.com/hvolschenk/small-glade).
You can just run `docker-compose up`.

## 🌍 Your Environment

A `node:gallium-alpine` Docker environment.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | `2.4.0`
| Node             | `14.19.1`
| npm/Yarn         | `npm 6.14.16`
| Operating System | _Alpine_

**Comment by mischnic** [comment]
The package `@parcel/css-linux-x64-musl` should be installed in your project, does the folder `node_modules/@parcel/css-linux-x64-musl` exist?

**Comment by hvolschenk** [comment]
> The package `@parcel/css-linux-x64-musl` should be installed in your project

I don't get since when this is a thing?
It worked without it a week ago, and **with** it I cannot install dependencies outside of the container as they are meant for a different OS.

> does the folder `node_modules/@parcel/css-linux-x64-musl` exist?

No it does not.

**Comment by mischnic** [comment]
> The package @parcel/css-linux-x64-musl should be installed in your project

What I meant was: you don't need to add this manually but it should automatically get installed by npm/Yarn.

**Comment by hvolschenk** [comment]
> What I meant was: you don't need to add this manually but it should automatically get installed by npm/Yarn.

Oh, right. Yeah that is definitely not happening, and I don't feel like anything has changed to make this change.

**Comment by hvolschenk** [comment]
Okay 🎉 
Thanks to your replies I have managed to find the issue.

Inside the container I was running `npm install --no-optional`.
I changed it to `npm install` which has now resolved the issue.

I am thinking that because the `package-lock.json` file is generated outside of the container
that the dependency mentioned above is optional, and then got skipped while building the container.

I am still unsure of what exactly changed, as this had been working for months before,
but I guess that isn't important now.

Thank you for your time.

**Comment by afitzgerald** [comment]
I don't believe that requiring the removal of --no-optional should be the solution for this.  Parcel should call out @parcel/transformer-css as a required dependency.

**Comment by devongovett** [comment]
The dependencies have to be optional because they are specific to each platform. Otherwise, you'd need to install e.g. the linux and windows versions of the module even if you're using macOS. At the moment, optional dependencies are the best option available for installing native packages. I believe npm is working on improving the situation, but until that is widely supported I'm not aware of a better option.

We can however improve the error message here.

**Comment by hvolschenk** [comment]
Hey @afitzgerald, I think that @devongovett is correct here.

My situation is maybe a bit strange.
Like I said, the steps I followed to get to this issue are:

1. Install dependencies locally on my machine (MacOS).
2. Copy `package.json` and `package-lock.json` into an _Alpine_ container ([source](https://github.com/hvolschenk/small-glade/blob/main/Dockerfile#L19)).
3. Install dependencies inside the _Alpine_ container ([source](https://github.com/hvolschenk/small-glade/blob/main/Dockerfile#L20)) with the above lock-file.

Thus the lock-file says that `@parcel/transformer-css` is not required as it was generated on MacOS
but then I am installing dependencies on _Alpine_ which **does** require `@parcel/transformer-css`.

The weirdness here is that it worked a week or two ago and now doesn't
and I cannot quite pinpoint what updated to cause this change.
I initially thought it was something that `parcel` changed, but I am now doubting that.

**Comment by tanglebones** [comment]
I have the same issue, lock file is generated on a different OS than the CI build leading to the failure. Not sure how to fix it, or why it was working before.

**Comment by tanglebones** [comment]
I ended up changing the CI automation script to force the correct OS package to install:
```sh
...
npm install # uses package-lock.json
npm install @parcel/css@1.8 --no-save # override package-lock.json to force correct OS deps
...
```

**Comment by devongovett** [comment]
When I run `npm install @parcel/css`, I see the packages for all platforms listed in package-lock.json. What version of npm are you using?

**Comment by chasdl** [comment]
I encountered this issue as well.

> When I run `npm install @parcel/css`, I see the packages for all platforms listed in package-lock.json. What version of npm are you using?

Simply running `npm install --save-dev @parcel/css` fixed the issue in the CI pipeline.

**Comment by fregante** [comment]
I also encountered this issue, I had to `trash node_modules package-lock.json` and then it appeared in the lockfile (even locally on my Mac)

**Comment by dtgcsl** [comment]
In my case I edit my package.json file: 
move "@parcel/css" and "@parcel/transfomer-sass" to "devDependencies";
move "parcel" to "dependencies"  
![image](https://user-images.githubusercontent.com/99410773/203886919-9dc27552-b004-4a05-80ea-0a53eaf108f3.png)

I think the resson for this problem is @parcel/transfomer-css in dependencies is that mean you must install this pageages to run but change it to devDependencies it mean that this need for local development and testing and dont need to install this

**Comment by dev0652** [comment]
> parcel/css

Workd for me, thanks a lot!
