### ISSUE TITLE
@parcel/transformer-css: Unexpected token Delim('.') with `semantic-ui-css`

### ISSUE THREAD

**Issue by devmao** [parcel-bundler/parcel#7963]
# 🐛 bug report

The `build` command fails when transforming the `semantic-ui.min.css`

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{js,mjs,jsx,cjs,ts,tsx}": [
      "@parcel/transformer-js",
      "@parcel/transformer-react-refresh-wrap"
    ]
  }
}
```

## 🤔 Expected Behavior

The build success

## 😯 Current Behavior

The build failed:

```
@parcel/transformer-css: Unexpected token Delim('.')

  /Users/mauriziopucci/dev/ilapack/repos/ilapak-hmi-electron/node_modules/semantic-ui-css/semantic.min.css:308:4401
    307 |  *
  > 308 | after .header{background-color:none;color:#fff}[data-position="top center"][data-tooltip]:after{top:auto;right:auto;left:50%;bottom:100%;-webkit
  >     |      ^
    309 |  * # Semantic UI 2.4.0 - Progress Bar
    310 |  * http://github.com/semantic-org/semantic-ui/
```

## 💻 Code Sample

Just include the semantic ui css:

```js
import 'semantic-ui-css/semantic.min.css'
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.1|
| Node             | 16.9.1|
| npm/Yarn         | 8.5.5|
| Operating System | Darwin Kernel Version 21.4.0|

**Comment by mischnic** [comment]
This is invalid CSS, the problematic code:
```css
[data-tooltip][data-inverted]:after .header {
  background-color: none;
  color: #fff;
}
```

I think you can't have anything after a pseudoelement selector, but @devongovett might know exactly.

**Comment by devongovett** [comment]
Yep pseudo elements cannot have children

**Comment by AlexVipond** [comment]
[SOLVED] Related error in case anyone else hits it: 

```
@parcel/transformer-css: Unexpected token Delim('\\*')
```

This error throws when a CSS property has an asterisk in front of it:

```
.some-class {
  *color: ...;
}
```

It's a hack you'll see sometimes in vendored code, targeting old versions of IE. Further reading: http://www.javascriptkit.com/dhtmltutors/csshacks3.shtml

Use regex `/\s+\*\w/` to find instances in your project.

**Comment by mrcoles** [comment]
I ran into this recently in a project of my own and ultimately was able to upgrade my offending dependency to a version that didn’t have the hacks. As a workaround I’ve used the patch-package dep in the past to modify things—you could add a [post-install](https://github.com/ds300/patch-package) script that modifies the problem file to remove the `*` hack. (Still seems like a bug though that it breaks compilation?)

**Comment by mischnic** [comment]
You can add this to your package.json to skip of these problematic lines (but they won't be in the output either):
```
{
  "@parcel/transformer-css": {
    "errorRecovery": true
  }
}
```
