### ISSUE TITLE
@parcel/validator-typescript throws many errors with React 18

### ISSUE THREAD

**Issue by firebelley** [parcel-bundler/parcel#7964]
# 🐛 bug report

Upgrading my project to React 18 causes `@parcel/validator-typescript` to throw many errors, all errors have the following structure:

```
./node_modules/@types/react-dom/node_modules/@types/react/index.d.ts:3278:13
    3277 |             use: React.SVGProps<SVGUseElement>;
  > 3278 |             view: React.SVGProps<SVGViewElement>;
  >      |             ^^^^^ Subsequent property declarations must have the same type.  Property 'view' must be of type 'SVGProps<SVGViewElement>', but here has type 'SVGProps<SVGViewElement>'.
    3279 |         }
    3280 |     } 
```

Here is another slightly different error just to paint the full picture:
```
./node_modules/@types/react-dom/node_modules/@types/react/index.d.ts:3171:13
    3170 |             noindex: React.DetailedHTMLProps<React.HTMLAtt
  > 3171 |      noscript: React.DetailedHTMLProps<React.HTMLAttribute
  >      |      ^^^^^^^^^ Subsequent property declarations must have the same type.  Property 'noscript' must be of type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>', but here has type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'.
    3172 |             object: React.DetailedHTMLProps<React.ObjectHT
    3173 |             ol: React.DetailedHTMLProps<React.OlHTMLAttrib

@parcel/validator-typescript: Subsequent property declarations must have the same type.  Property 'object' must be of type 'DetailedHTMLProps<ObjectHTMLAttributes<HTMLObjectElement>, HTMLObjectElement>', but here has type 'DetailedHTMLProps<ObjectHTMLAttributes<HTMLObjectElement>, HTMLObjectElement>'.
```

The validator worked as expected previously when I was using React 17.

## 🎛 Configuration (.babelrc, package.json, cli command)

Relevant package.json (can provide full package.json if necessary)
```js
{
  // ...
  "dependencies": {
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
  },
  "devDependencies": {
    "@parcel/validator-typescript": "^2.4.1",
    "@types/node": "^17.0.21",
    "@types/react": "^18.0.5",
    "@types/react-dom": "^18.0.1",
    "parcel": "^2.4.1",
    "typescript": "^4.6.3"
  },
  "packageManager": "yarn@3.2.0"
}
```

.parcelrc
```js
{
  "extends": "@parcel/config-default",
  "validators": {
    "*.{ts,tsx}": [
      "...",
      "@parcel/validator-typescript"
    ]
  }
}
```

tsconfig.json
```
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "react",
    "module": "commonjs",
    "target": "ESNext",
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "strict": true,
    "isolatedModules": true
  },
  "include": ["./src/**/*"],
  "exclude": ["./src/electron/**/*"]
}
```

I believe I am using the latest version of all of the listed packages.

## 🤔 Expected Behavior

Expected that `@parcel/validator-typescript` only throws relevant typecheck errors when using React 18.

## 😯 Current Behavior

Many errors are thrown, all of which start with the message `Subsequent property declarations must have the same type` (as far as I can tell, the console fills up so quickly that I can't possibly see all of the errors). These issues appear to be invalid because the app still functions as expected and no type errors are surfaced by the IDE.

## 💁 Possible Solution

Unknown

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.4.1
| Node             | 16.10.0
| npm/Yarn         | Yarn 3.2.0
| Operating System | Ubuntu 20.04.3 LTS (WSL)

**Comment by Shinyaigeek** [comment]
I could not reproduce this in my environment. Can you share reproduction?

**Comment by firebelley** [comment]
The problem appears to be with my configuration and Yarn specifically. Adding the following to `package.json`:

```
"resolutions": {
    "@types/react": "^18.0.6"
}
```

fixes the issue.
