### ISSUE TITLE
Parcel not working with TypeScript project references

### ISSUE THREAD

**Issue by StokeMasterJack** [parcel-bundler/parcel#7968]
I am just trying out Parcel. Project References have been part of TypeScript since 3.0. TypeScript is now at 4.6.3. But Parcel does not seem to be following the project references. Is it a bug? There is nothing in your docs that mentions project references.

If there is no support for TypeScript project references, that is a deal breaker for me. I'll have to stick with webpack. 

Thanks

**Comment by devongovett** [comment]
I don't really know anything about project references. Is there an error you are seeing? Do you have an example?

**Comment by LeoniePhiline** [comment]
It's kind of a workspacing tool for structuring TypeScript projects into more independent sub-spaces:

https://www.typescriptlang.org/docs/handbook/project-references.html#what-is-a-project-reference

**Comment by devongovett** [comment]
I read that, but I still don't really understand what it actually does or what is missing from Parcel to make it work.
