### ISSUE TITLE
[🐛] compiling node_modules is not a great idea

### ISSUE THREAD

**Issue by kidandcat** [parcel-bundler/parcel#797]
### 🎛 Configuration (.babelrc)

ParcelJS compile node_modules:

### 🤔 Expected Behavior

It should work

### 😯 Current Behavior

It crashes with: 
* https://github.com/styleguidist/react-styleguidist/issues/454
* https://github.com/cssinjs/react-jss/issues/146

### 💁 Possible Solution

The solution is not to ask *repo* for a fix because there are a lot of packages that doesn't expect to be compiled

### 🔦 Context

I want to use https://material-ui-next.com

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel       |      1.2.0 |
| Node       |     9.3.0  |
| npm/Yarn    |    5.5.1  |
| Operating System |  macOS High Sierra |

**Comment by DeMoorJasper** [comment]
Is is fixed using the latest version of the master branch?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by emartini** [comment]
@kidandcat. If you have time take a look at #13. Otherwise try with the master branch or wait for the next release.

**Comment by kidandcat** [comment]
Thanks! I'll do it with master

**Comment by prependto** [comment]
Is this fixed ?

**Comment by AElouai** [comment]
No
