### ISSUE TITLE
development build works, production does not work

### ISSUE THREAD

**Issue by geoynomous** [parcel-bundler/parcel#7972]
We bundle for development in 'development' mode and for the production docker images in 'production' mode.

The builds work without error. However (ONLY) the production mode bundle then says 

`Uncaught Error: Could not resolve bundle with id jN1O1
    at Object.i (bundle-manifest.js:17:11)
    at runtime-7440477a0414a4c7.js:1:38`

Is there a way to find out what "bundle with id jN1O1" is? To get a hint where to look at?

Plus: Why it does not report an error while bundling in mode='production'

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.1
| Node             | 16.14.1

**Comment by geoynomous** [comment]
Some more info .. in one file we have

```
        ctrl.imageUrl = new URL(
            '/__assets/img/log.png?as=webp&width=140',
            import.meta.url,
        );
```

In other file we have

```
        ctrl.imageUrl = new URL(
            '/__assets/img/log.png?as=webp&width=85',
            import.meta.url,
        );
```

If I change the 85 to 140 in the second file the 'production' mode bundle works - but obviously not with the right effect - I guess it's an error in caching.

And still: Is there a way to get the '/__assets/img/log.png?as=webp&width=85' string just after 'jN1O1' in the error message. That would have cut down the time to search this problem.

**Comment by geoynomous** [comment]
More info

One files is `.vue`, the other is `.js`

If for both the 'resource' is the same string, the error comes up, but when we do in one file

```
ctrl.imageUrl = new URL(
            '/__assets/img/logo.png?as=webp&width=85',
            import.meta.url,
        );
```

and in the other file

```
ctrl.imageUrl = new URL(
            '/__assets/img/logo.png?width=85&as=webp',
            import.meta.url,
        );
```
 (note: interchanged query parameters)

It works as well. The problem does not happen if you have the same 'resource' string repeated over multiple `.vue` files - only in mixed file extensions scenarios!

**Comment by mischnic** [comment]
Please provide a code sample that reproduces the issue

**Comment by HaNdTriX** [comment]
I have the same issue using `@parcel/config-webextension` and mp4 files:

Here is a full reproduction example: https://github.com/HaNdTriX/parcel-webextension-bug

- `parcel watch` works
- `parcel build` breaks

![Screenshot 2023-01-12 at 18 53 01](https://user-images.githubusercontent.com/1265681/212142464-4e3b1ac3-5ea6-4486-97b4-2a79562fa248.png)


@mischnic Should I open a new Issue?
