### ISSUE TITLE
@parcel/optimizer-htmlnano: contents.filter is not a function

### ISSUE THREAD

**Issue by ahmethalc** [parcel-bundler/parcel#7974]
# 🐛 bug report
When I try to build with parcel, it crashes giving me the error: `@parcel/optimizer-htmlnano: contents.filter is not a function`.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  {
  "name": "app",
  "version": "1.0.0",
  "description": "Source codes for my personal website.",
  "source": "./src/index.html",
  "scripts": {
    "dev": "parcel",
    "build": "parcel build --public-url ./"
  },
  "keywords": [],
  "author": "Ahmet Halici",
  "license": "ISC",
  "devDependencies": {
    "autoprefixer": "^10.4.4",
    "parcel": "^2.4.1",
    "postcss": "^8.4.12",
    "postcss-import": "^14.1.0",
    "tailwindcss": "^3.0.23"
  }
}

}
```

## 🤔 Expected Behavior
Should build

## 😯 Current Behavior

> @parcel/optimizer-htmlnano: contents.filter is not a function

  TypeError: contents.filter is not a function
  at /Users/ahmethalici/Desktop/son/node_modules/htmlnano/lib/modules/removeComments.js:34:21
  at /Users/ahmethalici/Desktop/son/node_modules/htmlnano/lib/htmlnano.js:139:28
  at traverse (/Users/ahmethalici/Desktop/son/node_modules/posthtml/lib/api.js:105:26)
  at traverse (/Users/ahmethalici/Desktop/son/node_modules/posthtml/lib/api.js:111:5)
  at traverse (/Users/ahmethalici/Desktop/son/node_modules/posthtml/lib/api.js:105:17)
  at traverse (/Users/ahmethalici/Desktop/son/node_modules/posthtml/lib/api.js:111:5)
  at traverse (/Users/ahmethalici/Desktop/son/node_modules/posthtml/lib/api.js:105:17)
  at traverse (/Users/ahmethalici/Desktop/son/node_modules/posthtml/lib/api.js:111:5)
  at traverse (/Users/ahmethalici/Desktop/son/node_modules/posthtml/lib/api.js:105:17)
  at traverse (/Users/ahmethalici/Desktop/son/node_modules/posthtml/lib/api.js:111:5)

## 💁 Possible Solution
none

## 🔦 Context
I am trying to bulid a webpage I created using only TailwindCSS and raw JS/CSS.

## 💻 Code Sample
`<section class="py-10 xl:py-20">
    <div class="container">
        <div class="grid grid-cols-1 xl:grid-cols-2 gap-20">
            
            
            <div class="relative text-center xl:text-left">
                <h1 class="text-display-3 font-bold"> WELCOME TO MY PERSONAL WEBSITE</h1>
                <p class="mt-2 mb-4 text-xl text-gray-500 leading-relaxed">Spare some time to browse around. Start by clicking either of:</p>
                
                <div class="flex justify-center xl:justify-start">
                    <a href="" class="btn btn-primary">BROWSE CERTIFICATES</a>
                    <a href="" class="btn btn_light">BROWSE CV</a>
                </div>
            </div>
            
            
            <div class="relative self-start">
                <img class="relative rounded-2xl z-10" src="./assets/images/hero.jpg" alt="">
                <div class="w-16 hidden xl:flex absolute -left-12 -top-12 z-0">
                    <img src="./assets/images/doodle-1.svg" alt="">
                </div>
                <div class="w-16 hidden xl:flex absolute -right-12 -bottom-12 z-0 rotate-180">
                    <img src="./assets/images/doodle-1.svg" alt="">
                </div>
            </div>
            

        </div>
    </div>
</section>`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.1
| Node             | v16.14.2
| npm/Yarn         | 8.5.0
| Operating System | Mac OS

**Comment by mischnic** [comment]
Probably a bug in htmlnano.
Please build with `parcel build --no-optimize` and post the resulting (unminified) html file.

**Comment by ahmethalc** [comment]
@mischnic I have built with the command and have an HTML file without CSS. Github does not let me upload HTML files but as I said, there seems to be a .css file but it is somehow not connected to my HTML file and I have no idea why that happens. Is there any more details needed?

**Comment by mischnic** [comment]
The error you posted references a HTML minifier, so it appears to be related to an HTML file.

If the html file isn't too big, you can add it directly in your comment with backticks to format as code. Or zip it and upload that.

**Comment by ahmethalc** [comment]
""" link was deleted by the author """
here is the related html file.

 the CSS file should be included as `href="index.38428f07.css"` without the directory sign "/" but even after I manually change that, the images do not show up, their names seems to be different as well.

**Comment by mischnic** [comment]
That by itself minifies just fine. Please share your whole project (not just the output).

**Comment by ahmethalc** [comment]
[dist.zip](https://github.com/parcel-bundler/parcel/files/8597447/dist.zip)
here is the whole output.

**Comment by ahmethalc** [comment]
when I try to upload it says "is not included in the list
<img width="611" alt="Screen Shot 2022-04-30 at 20 01 40" src="https://user-images.githubusercontent.com/101047101/166115183-2bc8179a-97d3-4bc7-82ed-4e9c23fd23c4.png">
"

**Comment by ahmethalc** [comment]
""" link was deleted by the author """

here is the whole project except for "node_modules" because it would not upload properly otherwise.

**Comment by mischnic** [comment]
You need to upgrade htmlnano (to version 2.0.2) in your lockfile because 2.0.1 has a bug: https://github.com/posthtml/htmlnano/issues/182

And you should also rename `ahmethalici.png` to `ahmethalici.jpg` (because it's not really a PNG but a JPG file):
```
Could not optimize image src/assets/images/ahmethalici.png: Invalid header detected; Not a PNG file
```

**Comment by ahmethalc** [comment]
The bug is fixed after re installing the node modules. Thanks for all the help.
