### ISSUE TITLE
web-ext | mv3 | production build failing with error p.generateUtilityClasses

### ISSUE THREAD

**Issue by hanabanashiku** [parcel-bundler/parcel#7982]
# 🐛 bug report
I'm noticing that with the latest nightly my popup does not build correctly for production builds. (utilizing react, if it makes a difference). It works perfectly fine when using parcel watch, but with parcel build I get the following console error:

```
Uncaught TypeError: p.generateUtilityClasses is not a function
    at Object.iPms5.process (popup.87de9105.js:12:280485)
```

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```js
{
    "scripts": {
        "start": "parcel watch src/manifest.json src/options/**/**.html src/popup/**.html --target webext-dev",
        "build": "parcel build src/manifest.json src/options/**/**.html src/popup/**.html --target webext-prod"
    },
    "dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
  },
  "devDependencies": {
    "@babel/core": "^7.16.7",
    "@babel/eslint-parser": "^7.16.5",
    "@babel/eslint-plugin": "^7.16.5",
    "@babel/plugin-transform-react-jsx": "^7.16.7",
    "@babel/preset-env": "^7.16.11",
    "@babel/preset-react": "^7.16.7",
    "@parcel/babel-preset-env": "2.0.0-nightly.1055",
    "@parcel/config-webextension": "2.4.2-nightly.2678",
    "parcel": "2.0.0-nightly.1053",
    "parcel-reporter-static-files-copy": "^1.3.4",
  },
  "targets": {
    "webext-dev": {
      "distDir": "./dist",
      "sourceMap": {
        "inline": true,
        "inlineSources": true
      }
    },
    "webext-prod": {}
  },
}
```

babelrc
```js
{
  "plugins": [
    "lodash",
    "@emotion",
    "@babel/plugin-proposal-private-methods",
    "@babel/plugin-proposal-class-properties",
    [
      "babel-plugin-jsx-pragmatic",
      { "export": "jsx", "module": "@emotion/react", "import": "___EmotionJSX" }
    ],
    [
      "@babel/plugin-transform-react-jsx",
      { "pragma": "___EmotionJSX", "pragmaFrag": "React.Fragment" }
    ]
  ],
  "env": {
    "test": {
      "presets": ["@babel/preset-env", "@babel/preset-react"]
    }
  }
}
```

## 🤔 Expected Behavior

My popup window should not crash.

## 😯 Current Behavior

When loading the popup, I get a white screen/crash

```
index-esm.js:1 Uncaught TypeError: p.generateUtilityClasses is not a function
    at Object.iPms5.process (popup.87de9105.js:12:280485)
    at d (popup.87de9105.js:1:708)
    at f (popup.87de9105.js:1:812)
    at Object.4DYHp.@emotion/react (popup.87de9105.js:12:264182)
    at d (popup.87de9105.js:1:708)
    at f (popup.87de9105.js:1:812)
    at Object.5YHdq.@emotion/react (popup.87de9105.js:12:262095)
    at d (popup.87de9105.js:1:708)
    at f (popup.87de9105.js:1:812)
    at Object.iZ85G.@emotion/react (popup.87de9105.js:1:2188)
```

## 💻 Code Sample

[This is the repository for my code (please see branch feature/popup-fixes)](https://github.com/hanabanashiku/ashidori/commit/ac7df211b0da9db36ad6023e336c71f6d576e7e3)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-nightly.1053
| Node             |  17.9.0
| npm/Yarn         |  8.5.5
| Operating System | macOS 12.2.21 (intel)

**Comment by 101arrowz** [comment]
Can't reproduce this, try updating to the latest nightlies for Parcel and the web extension config. After building, I opened the popup page for your extension and got the following:
![image](https://user-images.githubusercontent.com/29579245/164154308-2a3677d3-f06f-402c-a82a-7aceb5ce5e40.png)

**Comment by hanabanashiku** [comment]
Sorry, by popup I meant the browser action that is triggered by clicking on the extension icon.
I did try updating to last night's nightly - `2.0.0-nightly.1054` and I was able to see the same issue.

**Comment by hanabanashiku** [comment]
Thanks for fixing @101arrowz! Seems to be working perfectly
