### ISSUE TITLE
Build and server hang permanently on Windows 10 on empty project

### ISSUE THREAD

**Issue by Javi** [parcel-bundler/parcel#7990]
# 🐛 bug report

Just trying out parcel, and it didn't work at all. Neither `yarn parcel` `yarn parcel --no-sourcemaps` `yarn parcel --no-cache` do anything, just hang on the terminal with no output, no matter the log level.

## 🎛 Configuration (.babelrc, package.json, cli command)

The same basic, empty, hello world src/index.html from the tutorial. No other dependencies on the package.json. No .rc files. Nothing but parcel and the index.html. 

## 🤔 Expected Behavior

Parcel should build when building and serve when serving

## 😯 Current Behavior
Running parcel as a regular user has no logs, just a hang. Running build hangs after apparently after building index.html correctly, no error or info logs.

Running parcel as an administrator works with the following output
```
$ C:\Workspaces\parcelProject\node_modules\.bin\parcel --log-level info
Error: Custom { kind: NotFound, error: "CreateProcessAsUserW: The system cannot find the file specified. (os error 2)" }
Error: Custom { kind: NotFound, error: "CreateProcessAsUserW: The system cannot find the file specified. (os error 2)" }
Server running at http://localhost:1234
√ Built in 4ms
Error: Custom { kind: NotFound, error: "CreateProcessAsUserW: The system cannot find the file specified. (os error 2)" }
Done in 4.69s.
```

I have no idea how to figure out what that file that's not found is and whether that's the root problem or not.

## 🌍 Your Environment

Yarn 1.22.18, node versions attempted were 12, 14 and 16 via nvm. Parcel versions were 2.5.0 and 2.0.0-nightly.1054, same behaviour. Windows 10.

**Comment by AbuZaitoun** [comment]
Did you try running using `yarn android`?
