### ISSUE TITLE
Option to enable scope hoisting in dev server?

### ISSUE THREAD

**Issue by JavaScriptBach** [parcel-bundler/parcel#7993]
# 🙋 feature request

Could we provide an option to enable scope hoisting in the dev server? Empirically I've discovered that scope hoisting seems to be never enabled in dev, and the docs imply that it's prod only. Are there constraints that make this impossible for some reason, e.g. it doesn't work with hot reloading?

## 🔦 Context

We'd like to turn on scope hoisting for our app, but each time it's broken multiple third party modules. I'm working on understanding why and filing a bug report with a minimal repro. But not being able to test scope hoisting in our development environment is a larger issue in general because it increases the risk that a breaking change will go undetected until it's deployed.

**Comment by mischnic** [comment]
> Empirically I've discovered that scope hoisting seems to be never enabled in dev, and the docs imply that it's prod only. 

It's enabled for `parcel build` and for `parcel watch` when building libraries.

> Are there constraints that make this impossible for some reason, e.g. it doesn't work with hot reloading?

Exactly, because of HMR.
