### ISSUE TITLE
Cannot find module {index.html path} from '.'

### ISSUE THREAD

**Issue by lifeart** [parcel-bundler/parcel#80]
![image](https://user-images.githubusercontent.com/1360552/33708190-c8dc6536-db4a-11e7-98da-751f34d19290.png)

index.html content:

```html

<html>

<body>

</body>

</html>

```

/ Win10 / Node 7 / Parcel 1.3

**Comment by Raathigesh** [comment]
Tried to reproduce this with the following versions but couldn't.

Parcel - 1.0.3
Node - 7.0.0
Windows - 10.0.16299.64

**Comment by lifeart** [comment]
@Raathigesh 
[parcel-test.zip](https://github.com/parcel-bundler/parcel/files/1538788/parcel-test.zip)

**Comment by lifeart** [comment]
@Raathigesh  looks like my file structure issue

**Comment by edbrannin** [comment]
@lifeart What did you change to fix this?  I'm seeing it right now on OSX.

**Comment by lifeart** [comment]
@edbrannin looks like empty imports issue
