### ISSUE TITLE
Build error You must provide the URL of lib/mappings.wasm

### ISSUE THREAD

**Issue by bre7** [parcel-bundler/parcel#8005]
# 🐛 bug report

Build was working fine days ago (before env was updated to Node 18).

## 🎛 Configuration (.babelrc, package.json, cli command)

```bash
parcel build --target=target2 dist2/perm.html --no-scope-hoist
```

.terserrc
```js
{
  "compress": {
    "drop_console": true
  }
}
```

## 🤔 Expected Behavior

Build should be successful.

## 😯 Current Behavior

Error message is displayed on console:

```
@parcel/optimizer-terser: You must provide the URL of lib/mappings.wasm by
calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using
SourceMapConsumer

  Error: You must provide the URL of lib/mappings.wasm by calling
  SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using
  SourceMapConsumer
  at readWasm
  (/home/circleci/project/web/node_modules/terser/node_modules/source-map/lib/read-wasm.js:8:13)
  at wasm
  (/home/circleci/project/web/node_modules/terser/node_modules/source-map/lib/wasm.js:25:16)
  at
  /home/circleci/project/web/node_modules/terser/node_modules/source-map/lib/source-map-consumer.js:264:14
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async SourceMap
  (/home/circleci/project/web/node_modules/terser/dist/bundle.min.js:19385:20)
  at async minify
  (/home/circleci/project/web/node_modules/terser/dist/bundle.min.js:27785:41)
  at async Object.optimize
  (/home/circleci/project/web/node_modules/@parcel/optimizer-terser/lib/TerserOptimizer.js:131:16)
  at async PackagerRunner.optimize
  (/home/circleci/project/web/node_modules/@parcel/core/lib/PackagerRunner.js:364:20)
  at async PackagerRunner.getBundleResult
  (/home/circleci/project/web/node_modules/@parcel/core/lib/PackagerRunner.js:255:15)
  at async PackagerRunner.getBundleInfo
  (/home/circleci/project/web/node_modules/@parcel/core/lib/PackagerRunner.js:239:9)
```

## 💁 Possible Solution

Workaround was to rollback to Node 17 (17.9.0)

## 🌍 Your Environment

CircleCI with docker image cimg/node:18.0

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.0
| Node             | 18.0.0
| npm/Yarn         | 1.22.18
| Operating System | Ubuntu 20.04.4 LTS

**Comment by devongovett** [comment]
Based on the stack trace, looks like a problem with terser?

**Comment by jtojnar** [comment]
A bug in source-map: https://github.com/mozilla/source-map/issues/432
Fixed but not in any stable version: https://github.com/mozilla/source-map/issues/452
Terser bumped the dependency to beta but it have not had a release yet either: https://github.com/terser/terser/pull/1164

**Comment by Mirokko** [comment]
It is already merged. https://github.com/terser/terser/blob/v5.13.1/package.json#L48

**Comment by benpigchu** [comment]
As another workaround, `export NODE_OPTIONS=--no-experimental-fetch` should work

**Comment by bre7** [comment]
Thanks ! Closing since both a solution (update terser or force resolution) and a workaround were provided

**Comment by neoswf** [comment]
I have updated Parcel locally and all dependencies, and even though I had to apply @benpigchu solution to be able to build.

**Comment by warifp** [comment]
> As another workaround, `export NODE_OPTIONS=--no-experimental-fetch` should work

Thank!

**Comment by abhijit-chikane** [comment]
it is still not working for me

**Comment by phoenixeliot** [comment]
Working for me after updating to parcel 2.9.1 from 2.3.2, make sure you've updated your version @abhijit-chikane

**Comment by abhijit-chikane** [comment]
for me it was due to some other reason but anyway thanks

**Comment by nikita-fuchs** [comment]
If it is an option for you, you can also jump back to node 16 real quick for a minute, à la `$ nvm use 16`
