### ISSUE TITLE
Nightly build versionings

### ISSUE THREAD

**Issue by arcanis** [parcel-bundler/parcel#8010]
# 🐛 bug report

Parcel seems to ship nightly builds using `2.0.0-nightly.XXX` (see versions [here](https://yarnpkg.com/package/parcel)). This is problematic, because `^2.0.0-nightly.1068` returns `2.5.0`, which is incorrect (2.0.0-nightly.1068 got released after 2.5.0).

## 💁 Possible Solution

Nightly builds should use patch rcs. For instance, assuming the last release is `2.5.0`, then the following rc should be `2.5.1-nightly.1068`. This way the caret selector wouldn't get confused.

## 🔦 Context

When running `yarn add parcel@nightly`, Yarn will resolve nightly to a range (`^2.0.0-nightly.1068`) then run the install. This new range will then lead to `2.5.0` being installed, which doesn't match the user request.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by devongovett** [comment]
Hmm I think we just use lerna's --canary flag for this...

**Comment by arcanis** [comment]
I'm adding support for this kind of thing in https://github.com/yarnpkg/berry/pull/4400 (SvelteKit does it [too](https://github.com/sveltejs/kit/discussions/4645)), but it could conceivably cause problems in other tools that don't implement special logic for this. Just figured it could be worth flagging 🙂
