### ISSUE TITLE
No transformers found for [package] with pipeline: 'types'.

### ISSUE THREAD

**Issue by Scalahansolo** [parcel-bundler/parcel#8014]
# 🐛 bug report

When following the steps at https://parceljs.org/languages/typescript/ I get the error below when trying to generate typings.

## 🎛 Configuration (.babelrc, package.json, cli command)

This is a forked repo from `emoji-mart` that I am attempting to convert to TS. Their repo uses yarn workspaces

https://github.com/Scalahansolo/emoji-mart

https://github.com/Scalahansolo/emoji-mart/blob/main/package.json
https://github.com/Scalahansolo/emoji-mart/blob/main/packages/emoji-mart/package.json
https://github.com/Scalahansolo/emoji-mart/blob/main/packages/emoji-mart/tsconfig.json

## 🤔 Expected Behavior

Expect that `yarn build` at the top level of the repo builds fine.

## 😯 Current Behavior

```
 Build failed.

@parcel/core: No transformers found for packages/emoji-mart/src/index.js with pipeline: 'types'.

  /Users/sean/workspace/emoji-mart/node_modules/@parcel/config-default/index.json:3:3
     2 |   "bundler": "@parcel/bundler-default",
  >  3 |   "transformers": {
  >    |   ^^^^^^^^^^^^^^^^^
  >  4 |     "types:*.{ts,tsx}": ["@parcel/transformer-typescript-types"],
  >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  >  5 |     "bundle-text:*": ["...", "@parcel/transformer-inline-string"],
  >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  >  6 |     "data-url:*": ["...", "@parcel/transformer-inline-string"],
  >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  >  7 |     "worklet:*.{js,mjs,jsm,jsx,es6,cjs,ts,tsx}": [
  >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  >  8 |       "@parcel/transformer-worklet",
  >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  >  9 |       "..."
  >    | ^^^^^^^^^^^
  > 10 |     ],
  >    | ^^^^^^
  > 11 |     "*.{js,mjs,jsm,jsx,es6,cjs,ts,tsx}": [
  >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  > 12 |       "@parcel/transformer-babel",
  >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  > 13 |       "@parcel/transformer-js",
  >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/sean/.nvm/versions/node/v16.13.0/bin/node
Arguments: /Users/sean/.node/corepack/yarn/1.22.15/lib/cli.js build
Directory: /Users/sean/workspace/emoji-mart/packages/emoji-mart
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.5.0
| Node             | 16.13.0
| npm/Yarn         | 1.22.15
| Operating System | MacOS M1

**Comment by mischnic** [comment]
Very strange, especially that it says `packages/emoji-mart/src/index.js`, even though the file is actually called `index.ts`.

But why are you declaring that `types:...` pipeline in your local .parcelrc in the first place? That shouldn't be necessary (and this error goes away when removing it)
