### ISSUE TITLE
GIFs silently not getting transformed

### ISSUE THREAD

**Issue by Commandtechno** [parcel-bundler/parcel#8021]
# 🐛 bug report

Using a GIF with any operation (`as`, `width`, `height`, etc.) silently does nothing.

![parcel html](https://commandtechno.com/i/7d4w660n6zi6)
![parcel output](https://commandtechno.com/i/7d4w6thgcsno)
![parcel output properties](https://commandtechno.com/i/7d4w7zxb8p5c)

Sharp is able to do any of the operations on its own.

![sharp code](https://commandtechno.com/i/7d4wx6ip26v0)
![sharp output properties](https://commandtechno.com/i/7d4wzqat8r4q)

## 🎛 Configuration (.babelrc, package.json, cli command)

cli command: `npx parcel build test.html`

## 🤔 Expected Behavior

The GIF gets converted, optimized, or resized as normal

## 😯 Current Behavior

The GIF is not modified at all

## 💁 Possible Solution

I have no idea why Parcel does this, GIF is listed as a format here: https://github.com/parcel-bundler/parcel/blob/e0440dcbe6d6e419a412c8c568d94715cdb4282a/packages/transformers/image/src/ImageTransformer.js#L14

## 🔦 Context

Use a gif, but have it converted to a reasonable format at the correct size

## 💻 Code Sample

test.html:

```html
<img src="assets/avatar.gif?as=webp&width=100&height=100" />
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.4.1
| Node             | 17.8.0
| npm/Yarn         | npm 8.5.3
| Operating System | could reproduce on windows and linux
| sharp | 0.29.3

**Comment by mischnic** [comment]
Gif isn't listed here:
https://github.com/parcel-bundler/parcel/blob/50893a7ec2b1490e6d0a2f5e1f9ab6a8fc57a113/packages/configs/default/index.json#L42

**Comment by Commandtechno** [comment]
👍 I'll open a PR to sync those 2 format lists!
