### ISSUE TITLE
It seems `parcel watch` is incorrectly listening on localhost:1234

### ISSUE THREAD

**Issue by Offirmo** [parcel-bundler/parcel#8023]
# 🐛 bug report

I'm developing both a backend and a frontend:
* I'm using `parcel serve` for the frontend
* I'm using `parcel watch` for the backend, as suggested on https://parceljs.org/features/cli/#parcel-watch-%3Centries%3E
However when launched at the same time, those 2 parcel invocations clash on trying to get port :1234

## 🎛 Configuration (.babelrc, package.json, cli command)

As stated above, running both `parcel serve` and `parcel watch` at the same time (different targets of course)

## 🤔 Expected Behavior

`parcel watch` should not try to listen on :1234 as stated on https://parceljs.org/features/cli/#parcel-watch-%3Centries%3E "The watch command (...) does not start a dev server"

## 😯 Current Behavior

the 2 parcel invocations clash on trying to get port :1234

```
[_dev--frontend] @parcel/reporter-dev-server: There is already a process listening on port 1234.
[_dev--frontend]
[_dev--frontend] Error: listen EADDRINUSE: address already in use :::1234
[_dev--frontend]     at Server.setupListenHandle [as _listen2] (node:net:1372:16)
[_dev--frontend]     at listenInCluster (node:net:1420:12)
[_dev--frontend]     at Server.listen (node:net:1508:7)
```

## 💁 Possible Solution

n/a

## 🔦 Context

I'm developing both a backend (netlify functions, dedicated node targets) and a frontend (dedicated browser target) at the same time. I want to have both the frontend and the backend rebuilt live.

In fact, I'd rather call parcel only once but `serve` won't build my node targets and `watch` won't serve my `browser` target.

## 💻 Code Sample

```json
"scripts": {
		"_parcel--watch": "parcel watch",
		"_parcel--serve": "parcel serve --lazy --target frontend",
		"_netlify--functions--serve": "netlify functions:serve",

		"_dev--frontend": "run-p _parcel--serve",
		"_dev--backend": "run-p _parcel--watch _netlify--functions--serve",

		"dev": "FORCE_COLOR=1 npm-run-all --print-label clean --parallel _dev--backend _dev--frontend"
	},
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.5.0
| Node             | 16.15
| Yarn         |  1.22.18
| Operating System | MacOs 11.6.5

**Comment by mischnic** [comment]
> parcel watch should not try to listen on :1234 as stated on [parceljs.org/features/cli/#parcel-watch-%3Centries%3E](https://parceljs.org/features/cli/#parcel-watch-%3Centries%3E) "The watch command (...) does not start a dev server"

The docs say:
> The watch command is similar to serve, but does not start a dev server. However, it automatically rebuilds your app as you make changes, and **supports hot reloading**.

`serve` starts a dev (= HTTP) server and a HMR server.
`watch` only has a HMR server, this is what you're seeing here.

The idea is that you might use your own (e.g. express) backend and server the bundles statically yourself but still want Parcel to send HMR updates.

If you don't want this, use `parcel watch --no-hmr`

**Comment by Offirmo** [comment]
Hi @mischnic thanks for the explanations. The use-case you're giving makes it much easier to understand the difference between `watch` and `serve`.

May I suggest that you add that to the documentation for the next user like me? Thanks a lot!
