### ISSUE TITLE
exclude node_modules for watch in  parcel  2.5.0

### ISSUE THREAD

**Issue by zababurinsv** [parcel-bundler/parcel#8035]
### Discussed in https://github.com/parcel-bundler/parcel/discussions/8019

<div type='discussions-op-text'>

<sup>Originally posted by **zababurinsv** April 28, 2022</sup>
I have a config.

```
 "targets": {
    "main": false,
    "dev": {
      "includeNodeModules": true,
      "optimize": false,
      "isLibrary": false,
      "distDir": "service/newkind-service",
      "sourceMap": true,
      "publicUrl": "/newkind-service",
      "source": "./frontend/src/index.html"
    },
    "service": {
      "includeNodeModules": true,
      "optimize": true,
      "isLibrary": false,
      "distDir": "service/newkind-service",
      "sourceMap": false,
      "publicUrl": "/newkind-service",
      "source": "./frontend/src/index.html"
    },
    "module": {
      "includeNodeModules": true,
      "optimize": true,
      "isLibrary": true,
      "sourceMap": false,
      "source": "./frontend/src/index.mjs"
    }
  },
```

When i run dev server
```
 "dev": "rimraf ./service/* && parcel --cache-dir ./.parcel-cache --no-hmr --port $npm_package_config_port_dev --dist-dir service/newkind-service --public-url /newkind-service --target dev",
   
```

I get error

```
inotify_add_watch on '/home/sergey/Desktop/newkind/newkind-service/node/src/github.com/zababurinsv/tera/node_modules/nanomatch/node_modules/define-property' failed: No space left on device]

```

How can i exclude all node_modules for watch node ?</div>

**Comment by devongovett** [comment]
Have you tried raising your inotify limits? https://parceljs.org/features/development/#linux%3A-no-space-left-on-device

**Comment by mischnic** [comment]
(Another potential cause is that Parcel might try to watch too much because it doesn't detect the project root correctly. E.g. it watches everything inside of `/home/sergey/Desktop` instead of just `/home/sergey/Desktop/newkind/`)

**Comment by zababurinsv** [comment]
Yes. It should not look at these directories, but I have the paths correctly specified.
And it should not touch directories that have node_modules directories

**Comment by mischnic** [comment]
The reason node_modules are also watched is that Parcel should also rebuild if you update a dependency. So "not watching node_modules at all" is not an option

**Comment by zababurinsv** [comment]
There should be no changes to node_modules.
These modules are used but not written.
But if so, then it turns out that it is impossible to remove the problem of excessive use of resources and the restriction on the size of the project in the parse?

**Comment by alexplummersky** [comment]
This is crippling a test machine I am running only for CI with no package updates.

Parcel used to prevent watch on node_modules if NODE_ENV=test was set but this no longer seems to be the case.

There is no way to increase inotify watchers on my host as there is no root access allowed so this option is not available to me.

So so many requests to disable watcher by flag and these are constantly turned down and even helpful code removed.
