### ISSUE TITLE
Hot reload not working on Windows 11

### ISSUE THREAD

**Issue by skysantoroa** [parcel-bundler/parcel#8040]
# 🐛 bug report

When launching a React application via docker the hot reload won't work.

## 🎛 Configuration (.babelrc, package.json, cli command)

Here's a [repository ](https://github.com/skysantoroa/parcel-hmr-not-working) reproducing the issue

## 🤔 Expected Behavior

Adding/modifying the code should trigger the hot reload via docker.

## 😯 Current Behavior

A warning message is printed on the console

`[parcel] 🚨 Connection to the HMR server was lost`

The application is not bundled in the container.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.5.0|
| Node             |16.14.0|
| npm/Yarn         |8.3.1|
| Operating System |Windows 11 latest build|

**Comment by viktorkasap** [comment]
Did you manage to find a solution?
I faced the same problem, everything works as it should on Maos, it doesn't work on Windows

https://github.com/kasapvictor/frontent-boilerplate/tree/parcel-2.5-develop

**Comment by Maxou44** [comment]
The CLI automaticaly rebuild files but the information is not always sent to the front using the websocket, a manual refresh of the page works. Maybe related to dynamic import?

**Comment by kahlan88** [comment]
Same issue here (Windows 11). I get:
`Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'parcelHotUpdate')`
upon saving an .scss or .ts file. Manual refresh works.

Any idea how to work around this?

**Comment by 523299338** [comment]
same problem
i have to refresh the page manually  on Windows

**Comment by TNSaturday** [comment]
Same problem
parcel 2.9.2
node 19.8.1
npm 9.6.7
