### ISSUE TITLE
Parcel's use of import.meta causes error in web-ext's linter

### ISSUE THREAD

**Issue by pieterdd** [parcel-bundler/parcel#8047]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

I've done the bare minimum of config to use Parcel for a WebExtension. I don't have a Babel config.

Commands:
- yarn parcel build src/manifest.json --dist-dir build
- yarn web-ext lint -s build

**.parcelrc**
```js
{
    "extends": "@parcel/config-webextension"
}
```

**package.json dependencies**

```json
{
    // some irrelevant stuff omitted here
    "devDependencies": {
        "@parcel/config-webextension": "^2.5.0",
        "@parcel/core": "^2.5.0",
        "@parcel/transformer-sass": "2.5.0",
        "autoprefixer": "^9.1.2",
        "del": "^3.0.0",
        "eslint": "^5.4.0",
        "parcel": "^2.5.0",
        "sass": "^1.49.7",
        "web-ext": "^6.8.0"
    }
}
```

## 🤔 Expected Behavior

The linter should not contain any errors related to Parcel's code translation.

## 😯 Current Behavior

I see this in lint:

```
Code              Message                       Description                                                  File                Line   Column
JS_SYNTAX_ERROR   JavaScript syntax error       There is a JavaScript syntax error in your code, which       popup.eecf1690.js   1      2606  
                  (Parsing as script error:     might be related to some experimental JavaScript features                                     
                  Cannot use 'import.meta'      that aren't an official part of the language specification                                    
                  outside a module at line: 1   and therefore not supported yet. The validation cannot                                        
                  and column: 2606)             continue on this file.      
```

## 🔦 Context // 💻 Code Sample

I tried to reference the fingerprinted URLs of some static assets in JavaScript as follows:

```
import someImage from '/src/assets/img/someImage.png';
```

I suspect that this has something to do with it.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.5.0
| Node             | 14.19.1
| npm/Yarn         | yarn 1.22.18
| Operating System | Ubuntu 20.04 LTS

**Comment by 101arrowz** [comment]
This seems more like an issue with `web-ext`'s lack of support for `import.meta` than Parcel. Maybe file an issue with `web-ext`?

**Comment by pieterdd** [comment]
Hmm, you have a point. `import.meta` seems to be part of the [language specification](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#prod-ImportMeta) and support for it seems to be [near-universal](https://caniuse.com/mdn-javascript_statements_import_meta) since 2020. I agree with your conclusion for now.

**Comment by pieterdd** [comment]
I talked to the web-ext lint team. The linter relies on me using the `.mjs` extension to indicate that the JavaScript file is a module. If it knew it was a module, it would not trigger the error. Parcel has the habit of renaming `.mjs` files to `.js`, so the linter cannot know it's a module.

Is there a specific reason why Parcel renames `.mjs` files to `.js`?

**Comment by 101arrowz** [comment]
`.mjs` is a quirk of the Node.js implementation for ES Modules and there are many reasons it isn't used for browser builds (one of them being the fact that many servers don't set the correct MIME type).

I suppose the file extension doesn't really matter for web extensions but I'd still argue this is an issue for `web-ext` and not Parcel since Parcel's output works perfectly fine in actual browsers. But if you wanted, you could force Parcel to use `.mjs` with a namer plugin.

**Comment by pieterdd** [comment]
Great news - your suggestion to use a namer plugin worked. I chose `parcel-namer-custom`. For future reference, here's my config.

**In package.json**
```json
    "parcel-namer-custom": {
        ".mjs$": "[name].[hash].mjs"
    }
```

**In .parcelrc**
```json
    "namers": [
        "parcel-namer-custom",
        "..."
    ]
```

It might be useful if `@parcel/config-webextension` applied this behavior automatically, but for now this workaround will do. Thanks for your help 101arrowz!

**Comment by fregante** [comment]
This is not an issue Parcel can or should solve. The syntax is valid and not specific to Parcel
