### ISSUE TITLE
[TS] Generated type definitions incorrect

### ISSUE THREAD

**Issue by levino** [parcel-bundler/parcel#8048]
# 🐛 bug report

Under certain conditions incorrect / broken type definitions are being generated.

## 🎛 Configuration (.babelrc, package.json, cli command)

See demo repo.

## 🤔 Expected Behavior

The type definitions should be correct and reflect all typings.

## 😯 Current Behavior

The type definitions use some incorrect import statements which render the output type definitions useless for usage in third party projects.

## 💁 Possible Solution

I do not know. But if I do not **export** the type [here](https://github.com/Levino/parcel-ts-bug/blob/bee242fed0acedcbb7e313bbf974f22a7de8d818/src/user.ts#L1) the problem goes away (the types are correctly inlined in the output file).
## 🔦 Context

I wanted to bundle a typescript library with multiple files into one output JS file and one output types.d.ts file.

## 💻 Code Sample

https://github.com/Levino/parcel-ts-bug/blob/bee242fed0acedcbb7e313bbf974f22a7de8d818/dist/index.d.ts#L2

## 🌍 Your Environment

[Please see the demo repo.
](https://github.com/Levino/parcel-ts-bug)

**Comment by sseidel16** [comment]
This is a serious issue that still exists.

**Comment by levino** [comment]
Yeah. Just use something else. This bundler is not worth the trouble.

**Comment by sseidel16** [comment]
@levino unfortunately I have to agree with you
