### ISSUE TITLE
PostHTML deletes PHP tags, ignores `directives` configuration

### ISSUE THREAD

**Issue by schuetzm** [parcel-bundler/parcel#8053]
# 🐛 bug report

Parcel (resp. PostHTML) deletes PHP tags from HTML input files during transformation. It also ignores any `directives` options in `.posthtmlrc` that are supposed to preserve them.

## 🎛 Configuration

Minimal default configuration, see below.

## 🤔 Expected Behavior

The resulting file should contain all `<?= ... ?>` and `<?php ... ?>` tags in the input file as-is.

## 😯 Current Behavior

The tags are removed.

## 💁 Possible Solution

Don't know, [this issue](https://github.com/parcel-bundler/parcel/issues/3975), which was wrongfully closed by the stale bot, contains some remarks that are probably outdated by now.

## 🔦 Context

The bug makes it impossible to include PHP snippets in bundled HTML files, which is a hard requirement for one of my current projects.

## 💻 Code Sample

**Reproduction**
https://github.com/schuetzm/parcel-deletes-php-tags

**index.html**
```html
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <user-defined-tag>This is preserved.</user-defined-tag>
    <?php phpinfo(); ?>
    The above tag is removed.
  </body>
</html>
```

**.posthtmlrc**
```json
{
  "render": {
    "directives": [{"name": "?php", "start": "<", "end": ">"}]
  },
  "directives": [{"name": "?php", "start": "<", "end": ">"}],
  "plugins": {
  }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.5.0
| Node             | 14.9.1
| npm/Yarn         | Yarn 1.22.17
| Operating System | openSUSE 15.3

**Comment by mischnic** [comment]
Something like adding `directives: config.directives` to these options
https://github.com/parcel-bundler/parcel/blob/9556a229186b0120cf588d2205021094aa887c89/packages/transformers/posthtml/src/PostHTMLTransformer.js#L92-L96
would work.

**Comment by schuetzm** [comment]
@mischnic Hmm... doesn't seem so. I modified the file in `node_modules` as a quick test, deleted the cache and rebuilt, but it didn't have an effect.

As for where to put it, `posthtml-cli` seems to have an `options` field, probably a good idea to follow that for compatibility:
https://github.com/posthtml/posthtml-cli/issues/306#issuecomment-673493974

**Comment by mischnic** [comment]
You need to edit `lib/PostHTMLTransformer.js` in node_modules, not `src/...`

**Comment by schuetzm** [comment]
@mischnic I know, that's what I did. I even inserted a `throw` to verify it's the right file.

Edit: Added [my attempt](https://github.com/schuetzm/parcel-deletes-php-tags/commit/aa5c48592d9b43b701280c210a2bff7988b1e1a4) to the reproduction repo.

**Comment by seamile4kairi** [comment]
Same problem for me. I tried the fixes in @schuetzm's repo in my local `node_modules/`, and `directives` sometimes worked as intended, sometimes not. I'm not sure of any reproduction conditions though...

Also, I found a similar PostHTML code in [`/packages/transformers/posthtml/src/PostHTMLTransformer.js`](https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/html/src/HTMLTransformer.js#L20). I guess there's need to load `directives` here as well...? 🤔

**Comment by ecmel** [comment]
This also effect EJS tags if you use `<? tag ?>`.

**Comment by cossssmin** [comment]
PostHTML has a bunch of other options besides `directives`, like `recognizeNoValueAttribute` or `recognizeSelfClosing`: https://github.com/posthtml/posthtml-parser#options

When added to the PostHTML config file, they should be used by the Parcel transformer; right now it's not possible to configure PostHTML to preserve PHP tags or to have it leave valueless attributes alone (i.e. don't change `<img alt>` to `<img alt="">`).
