### ISSUE TITLE
Hot reload doesn't work for postcss/Tailwind classes

### ISSUE THREAD

**Issue by nsadeh** [parcel-bundler/parcel#8057]
# 🐛 bug report

Hello - I have a Parcel build utilizing Tailwind which I built using the directions here: https://tailwindcss.com/docs/guides/parcel. The programming language is Elm. I have noticed that when I add classes to HTML elements, I see the styles initially in the app, but when I hard reload the app, they disappear. 

Sometimes I can get out of this issue by greying out the script tag for the index.js file in index.html file and restarting the server. Then it usually works, for a while

## 🎛 Configuration (.babelrc, package.json, cli command)

`.postcssrc`
```json
{
  "plugins": {
    "tailwindcss": true
  }
}
```

`tailwind.config.js`
```js
module.exports = {
  mode: 'jit',
  content: [
    './src/**/*.{js,elm}',
    './src/index.html'
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

`package.json`
```json
{
  "name": "fitapp",
  "source": "src/index.html",
  "browserslist": "> 0.5%, last 2 versions, not dead",
  "scripts": {
    "start": "parcel src/index.html",
    "build": "parcel build src/index.html --no-cache --public-url \".\"",
    "postbuild": "workbox generateSW"
  },
  "devDependencies": {
    "elm": "^0.19.1-5",
    "parcel": "^2.5.0",
    "parcel-plugin-sw-cache": "^0.2.5",
    "tailwindcss": "^1.8.10",
    "postcss-cli": "^7.1.0",
    "@parcel/packager-raw-url": "^2.5.0",
    "@parcel/transformer-css": "^2.5.0",
    "@parcel/transformer-elm": "^2.5.0",
    "@parcel/transformer-webmanifest": "^2.5.0"
  },
  "dependencies": {
    "bootstrap-icons": "^1.8.1",
    "node-elm-compiler": "^5.0.6",
    "workbox-cli": "^6.5.3"
  }
}
```

build command: `npx parcel src/index.html`

## 🤔 Expected Behavior

When adding or removing a Tailwind class, the style should be reflected in the app in the browser immediately during hot reload, and stay there when refreshing the page

## 😯 Current Behavior

The style appears in the app immediately but disappears after refreshing the page.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
> The style appears in the app immediately but disappears after refreshing the page.

This sounds like https://github.com/parcel-bundler/parcel/issues/7546#issuecomment-1074330854
Does it work correctly if you open the devtools and check "Disable cache"?

**Comment by mischnic** [comment]
> workbox-cli

(And furthermore, make sure that your serviceworker didn't cache it either)

**Comment by nsadeh** [comment]
Thanks, @mischnic! I did two things:
- Move the index.js script tag to the <body> section
- Disable cache like you said

Now it works like 95% of the time. When it doesn't, I have so far reliably gotten it to work by commenting my index.js reference in the body tag, reloading, and uncommenting.

How do I make sure the SW doesn't cache? I was under the impression, idk why, that developing on incognito helps with that.

**Comment by mischnic** [comment]
There's a "Bypass for network" checkbox in the chrome devtools's "Application" tab -> section "Service worker".
