### ISSUE TITLE
Support browser extension manifests

### ISSUE THREAD

**Issue by TiagoCavalcante** [parcel-bundler/parcel#8058]
# 🙋 feature request

There is the plugin @parcel/transformer-webmanifest that handles web manifests in HTML, the plugin is used when Parcel see a `<link rel="manifest" href="path-to-manifest" />`.

This is a example of a browser extension manifest:
```json
{
  "manifest_version": 3,
  "name": "Manifest",
  "version": "0.0",
  "permissions": [],
  "description": "Foo bar",
  "options_ui": {
    "page": "options.html",
    "open_in_tab": true
  },
  "icons": {
    "16": "16.png",
    "32": "32.png",
    "48": "48.png",
    "64": "64.png",
    "96": "96.png",
    "128": "128.png",
    "256": "256.png",
    "512": "512.png",
    "1024": "1024.png"
  },
  "author": "Parcel",
  "homepage_url": "https://www.url.com"
}
```

## 🤔 Expected Behavior

I believe a plugin could be added to support `<link rel="plugin-manifest" />`. This type of manifest is necessary for Chrome and Chromium-based browsers and for Firefox (both have the same manifest format) extensions, I haven't developed extensions for other browsers, but I'm sure the "core" part of the plugin could work anywhere. This plugin should:
1. Copy the manifest
2. Copy the images mentioned in the manifest

## 😯 Current Behavior

Currently it is necessary to use a copy command, what makes the build script complex, and that's against the objective of Parcel.

## 💁 Possible Solution

The plugin @parcel/transformer-webmanifest could be forked to @parcel/transformer-extensionmanifest and modified so it handles browser-extension manifests.

If you agree this feature I could try to port @parcel/transformer-webmanifest.

## 🔦 Context

My build script changed from `parcel build ./src/extension/chrome/*.html --dist-dir dist-chrome` to `cpy public/icons dist-chrome && parcel build ./src/extension/chrome/*.html  --dist-dir dist-chrome`.

## 💻 Examples

The plugin only needs to copy the file (what already happens) and copy the images.

**Comment by mischnic** [comment]
How is this different from https://parceljs.org/recipes/web-extension/?

As far as I know, the real entry point for extensions is the manifest itself, not some html page.

**Comment by TiagoCavalcante** [comment]
It is not, I didn't see that before.
