### ISSUE TITLE
Scope Hoisting Broken - Looking for a workaround

### ISSUE THREAD

**Issue by dioptre** [parcel-bundler/parcel#8062]
# 🐛 bug report
Scope hoist has been broken for me for a long time, so I've had to use the option "--no-scope-hoist". Our package is ~12MB and there's not much room for us to try too hard at debugging this rn - so just looking for a workaround atm. I've tried ```  "removeComments": true```.

I'd love to remove the "no static exports found" here as a temporary solution. We really don't want more cruft in the production bundle:
```
/*! no static exports found */function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0});var n=r(/*! @antv/util */"./node_modules/_@antv_util@2.0.10@@antv/util/lib/index.js"),o=r(/*! ../data-set */"./src/data-set.ts"),i=r(/*! ../util/option-parser */"./src/util/option-parser.ts");o.DataSet.registerTransform("pick",(function(e,t){var r=i.getFields(t,e.getColumnNames());e.rows=e.rows.map((function(e){return n.pick(e,r)}))}))},"./src/xxx/xxx.ts":
/*!*************************************!*\
  !*** ./src/xxx/xxx.ts ***!
```

How would I do it?

Using Parcel 2.3.0

**Comment by mischnic** [comment]
That comment is not added by Parcel. And Terser retains `/*!` comments by default thinking they are license comments. You can change that with a terserrc and `{comments: false}`

**Comment by Richard87** [comment]
Bumping this, I just had a issue where `parcel serve` worked perfectly, but when running `parcel build` our javascript was not executed!

Adding ` --no-scope-hoist` to the build command solved our issue eventually

**Comment by mischnic** [comment]
@Richard87 Please open a new issue with more details and a reproduction.
