### ISSUE TITLE
@parcel/transformer-css: Unknown at rule: @container

### ISSUE THREAD

**Issue by yuuk** [parcel-bundler/parcel#8066]
# 🐛 bug report

@parcel/transformer-css doesn`t support CSS Container Queries

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// package.json
"devDependencies": {
        "@parcel/transformer-less": "2.5.0",
        "@parcel/transformer-sass": "2.5.0",
        "@parcel/transformer-typescript-tsc": "^2.5.0",
        "@parcel/transformer-typescript-types": "2.5.0",
        "parcel": "2.5.0"
    }
```

```js
// .parcelrc
{
    "extends": "@parcel/config-default",
    "transformers": {
        "*.{ts,tsx}": [
            "@parcel/transformer-typescript-tsc"
        ]
    }
}
```

## 🤔 Expected Behavior

It shold be okay when use container queries

## 😯 Current Behavior

![Snipaste_2022-05-07_11-35-08](https://user-images.githubusercontent.com/9426456/167236574-9c8dc919-1dc4-41ea-b9f2-bd6fbd39c35e.png)

## 💻 Code Sample

```css
/* query container */
@container (width >= 375px) {
    body {
        background: #000;
    }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.5.0
| Node             | v14.17.0
| Yarn         |  1.22.17
| Operating System | windows 10

**Comment by devongovett** [comment]
See https://github.com/parcel-bundler/parcel-css/issues/158
