### ISSUE TITLE
HTML from pug file is minified even in development

### ISSUE THREAD

**Issue by CxRes** [parcel-bundler/parcel#8078]
# 🐛 bug report

HTML files are minified when I run `parcel`/`parcel serve`. This is not helpful while debugging.

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json

```json
{
  "source": "index.html",
  "scripts": {
    "start": "parcel"
  }
}
```

CLI

```sh
pnpm run start
```

## 🤔 Expected Behavior

HTML file should not be minified.

## 😯 Current Behavior

HTML file is minified.

## 🔦 Context

It is not nice to search for mistakes when the file is minified.

## 💻 Code Sample

Should be obvious on any repo with html entry file.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.5.0 |
| Node             | 14.19.2 |
| pnpm         | 7.0.1 |
| Operating System | Windows 10 x64 |

**Comment by mischnic** [comment]
I have just tested this with
```html
<!DOCTYPE html>
<body>

test

</body>
```
and the newlines didn't get removed in development, so it wasn't minified.

**Comment by CxRes** [comment]
@mischnic I ~~probably~~ made a mistake in describing the bug. I am starting with `.pug` file. Now, this definitely gives me a minified html output. What I did was to copy the output of the pug file and run it through prettier and test that again. I may have mixed-up the output files (for pug and html versions) and thus concluding it is a html bug.

To summarize, Parcel does minify when you start with a `.pug` file.

**Comment by mischnic** [comment]
The `pretty` option is discouraged by the Pug compiler:

> Adds whitespace to the resulting HTML to make it easier for a human to read using '  ' as indentation. If a string is specified, that will be used as indentation instead (e.g. '\t'). We strongly recommend against using this option. Too often, it creates subtle bugs in your templates because of the way it alters the interpretation and rendering of whitespace, and so this feature is going to be removed. Defaults to false.
https://pugjs.org/api/reference.html#options

But you can override it by adding a `.pugrc` with 
```json
{
	"pretty": true
}
```

**Comment by CxRes** [comment]
@mischnic Oh wow! Thanks for pointing that out. But, I think this needs to be documented by Parcel itself. 

Also, (a noob question) wouldn't adding a `.pugrc` also make a change in production? What if you wanted the change in development only?

**Comment by matiev** [comment]
[](https://github.com/parcel-bundler/parcel/issues/8078)
create .pugrc:
```
{
	"pretty": true
}
```
