### ISSUE TITLE
Unable to set breakpoints in debugger

### ISSUE THREAD

**Issue by skysantoroa** [parcel-bundler/parcel#8086]
# 🐛 bug report

The browser debugger (Chrome/Firefox) won't let me set any breakpoint in a `.tsx` file.

## 🎛 Configuration (.babelrc, package.json, cli command)

Clone my [repo](https://github.com/skysantoroa/parcel-hmr-not-working) and launch with `npm start`.

## 🤔 Expected Behavior

I should set breakpoints in the `/__parcel_source_root/*` files.

## 😯 Current Behavior

I can't set any breakpoint when `"sourceMap": true` in `tsconfig.json`. Setting `"inlineSourceMap": true` enables breakpoints but the steps are inconsistent with the source code and some lines cannot be set.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.5.0|
| Node             |16.14|
| npm/Yarn         |8.5.5|
| Operating System |Ubuntu 22.04|
|Firefox|100.0|
|Chrome|101.0.4951.54|

**Comment by skysantoroa** [comment]
When using the default parcel transpiler (remove the `.parcelrc` file) breakpoints are mapped correctly however not every line could be hit by the debugger (both Chrome and Firefox).

**Comment by mischnic** [comment]
The sourcemaps aren't right, there are somehow two sources:
![Bildschirmfoto 2022-05-12 um 12 02 38](https://user-images.githubusercontent.com/4586894/168046013-c5e016e7-0a8c-4ed0-8a57-f018c950a8f7.png)


![Bildschirmfoto 2022-05-12 um 12 02 28](https://user-images.githubusercontent.com/4586894/168045976-984d4957-4221-488e-9b6f-f3023732b7b5.png)


But this is true even with an empty tsconfig, so just the tsc transformer itself causes this

**Comment by skysantoroa** [comment]
> The sourcemaps aren't right, there are somehow two sources: ![Bildschirmfoto 2022-05-12 um 12 02 38](https://user-images.githubusercontent.com/4586894/168046013-c5e016e7-0a8c-4ed0-8a57-f018c950a8f7.png)
> 
> ![Bildschirmfoto 2022-05-12 um 12 02 28](https://user-images.githubusercontent.com/4586894/168045976-984d4957-4221-488e-9b6f-f3023732b7b5.png)
> 
> But this is true even with an empty tsconfig, so just the tsc transformer itself causes this

May I ask you how did you check the source maps?
Any workaround for this?

**Comment by skysantoroa** [comment]
~If you comment the `sourceMap: true` line in the `tsconfig` the debugger works.~

**Comment by mischnic** [comment]
The screenshots are from https://evanw.github.io/source-map-visualization/

> Any workaround for this?

Not that I know of
