### ISSUE TITLE
HMR not updating data from parcel resolver with a virtual module

### ISSUE THREAD

**Issue by danielfdsilva** [parcel-bundler/parcel#8090]
# 🐛 bug report

I have a [virtual module](https://parceljs.org/plugin-system/resolver/#virtual-modules), that outputs a variable with a string value read from a `.txt` file.
The resolved module is invalidated whenever this txt file is modified, however despite the HMR sending a signal to the app, it does not update the data.

## 🎛 Configuration (.babelrc, package.json, cli command)

See this repo: https://github.com/danielfdsilva/parcel-resolver-hmr-bug-ex

## 🤔 Expected Behavior

The app should show the new data from the virtual module.

## 😯 Current Behavior

The HMR sends a signal (get a "console was cleared" message), but the data is not updated.

To replicate:
- Run the app with `yarn serve`
- Open http://localhost:1234
- Change the content of `content.txt`

Data only updated if you force refresh.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.5
| Node             | 16 
| npm/Yarn         | yarn v1.22.15
| Operating System | MacOS Big Sur

**Comment by danielfdsilva** [comment]
@mischnic Is there any update related to this bug? Any idea where to start looking? (I may be able to lend a hand if I know where to start)

**Comment by mischnic** [comment]
I guess the first question is what actually gets sent to the client. Either the resolver module isn't actually being sent, or it's not being handled correctly by the HMR client.
