### ISSUE TITLE
Options Page in manifest not working with Chrome MV3

### ISSUE THREAD

**Issue by richard-313** [parcel-bundler/parcel#8091]
# 🐛 bug report

When I add options_page to manifest, I get the alert: "Did you mean "options\_ui", "devtools\_page"?"
In Chrome Manifest V3 now its: "options_page"
```
{
    "manifest_version": 3,
    "name": "Sample Web Extension",
    "version": "0.0.1",
    "background": {
      "service_worker": "background.js",
      "type": "module"
    },
    "content_scripts": [{
      "matches": ["*://my-site.com/*"],
      "js": ["content.js"]
    }],
    "options_page": "/options/options.html"
  }
```

## 🤔 Expected Behavior

Support for "options_page"

## 😯 Current Behavior

🚨 Build failed.

@parcel/transformer-webextension: Invalid Web Extension manifest

```
12 |     }],
  > 13 |     "options_page": "/options/options.html"
  >    |     ^^^^^^^^^^^^^^ Did you mean "options\_ui", "devtools\_page"?
    14 |   }
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by 101arrowz** [comment]
This is [deprecated](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/options_page) in Firefox, and for good reason. You can do the exact same thing with:

```json
"options_ui": {
  "page": "/options/options.html"
}
```

I notice that this isn't explicitly deprecated in Chrome but it's probably a good idea for the schema to only accept configs that work in every browser. So I don't think this is something that should be changed.

**Comment by richard-313** [comment]
Wow, thanks a lot! Its working with chrome. In firefox I receive the error, that MV3 isnt supported.

I think in the end I have to create two manifest files, for firefox and chrome, because e.g. the new MV3 background worker is not supportet in firefox.

**Comment by 101arrowz** [comment]
Closing since this issue seems to be resolved.
