### ISSUE TITLE
`watch` combined with `--target` does not build according to the target's options 

### ISSUE THREAD

**Issue by gillyspy** [parcel-bundler/parcel#8105]
# 🐛 bug report

`watch` combined with `--target` does not build according to the target's options 

## 🎛 Configuration (.babelrc, package.json, cli command)

see sampe below

```js
// defaults
```

## 🤔 Expected Behavior

I would expect these two commands to generate the same output:
- `parcel watch --target mytarget`
- `parcel bulid --target mytarget`

## 😯 Current Behavior

the `build` command works as expected from the target's options but the watch does not use them

## 💁 Possible Solution

not sure

## 🔦 Context

i can't use watch

i think the expected behaviour is pretty MVP

## 💻 Code Sample

ane example target i have is:
```json
...
"targets" : {
"restartTask": {
      "context": "browser",
      "source": ["code/scomefile.js"],
      "distDir": "dist/somefolder",
      "outputFormat": "global",
      "engines": {
        "browsers": "Chrome 72"
      },
      "optimize": false
    },
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |   2.4
| Node             | 17.1
| npm/Yarn         | 8.1.2
| Operating System | osx 12.0.1

**Comment by sarahrobichaud** [comment]
## Same Issue here

It works with `build` but not `server` nor `watch`.

## 🎛 Configuration (.babelrc, package.json, cli command)



```json
{
 "scripts": {
    "watch-js": "parcel serve --target resources",
    "build-js": "parcel build --target resources",
    "watch": "concurrently -n w-tailwind,w-js -c cyan,yellow \"npm run watch-tailwind\" \"npm run watch-js\"",
    "build": "npm run build-tailwind && npm run build-js"
  },
}
```

## 🔦 Context

I want to compile target `resources` into `/dist/resources`.

## 💻 Code Sample


```json
{
 "targets": {
    "resources": {
      "source": [
        "resources/resources.html"
      ],
      "publicUrl": "dist/resources/",
      "distDir": "dist/resources",
      "engines": {
        "browsers": "> 1%"
      }
    }
  },
}
```
## 🌍 Your Environment



| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.0 |
| Node             | 16.13.1 |
| npm/Yarn         | 8.5.5 |
| Operating System | Windows 11(21H2) |

**Comment by ericbiewener** [comment]
I'm also experiencing this. [Here's a reproduction repo](https://github.com/ericbiewener/parcel-watch-bug/tree/main).
