### ISSUE TITLE
Uncaught ReferenceError: globalThis is not defined

### ISSUE THREAD

**Issue by bobofueeeee** [parcel-bundler/parcel#8112]
![befaf8c77821eb4dcc3721db6ece3b0](https://user-images.githubusercontent.com/105898750/169483673-6f9690d0-75a6-4c11-969c-2ac4575cd3c6.jpg)

**Comment by bobofueeeee** [comment]
q

**Comment by devongovett** [comment]
Please provide a reproduction.
