### ISSUE TITLE
Cannot find module '../parcel_sourcemap_node/index'

### ISSUE THREAD

**Issue by LekoArts** [parcel-bundler/parcel#8114]
# 🐛 bug report

The 2.0.4 publish of `@parcel/source-map` is missing an index file:

https://unpkg.com/browse/@parcel/source-map@2.0.3/parcel_sourcemap_node/ vs https://unpkg.com/browse/@parcel/source-map@2.0.4/parcel_sourcemap_node/

Most likely due to https://github.com/parcel-bundler/source-map/pull/102

This currently hard fails any Gatsby builds with the latest Parcel versions, e.g. with an error like this:

```shell
Error: Cannot find module '../parcel_sourcemap_node/index'
  Require stack:
  - /home/circleci/project/starters/blog/node_modules/@parcel/source-map/dist/no  de.js
  - /home/circleci/project/starters/blog/node_modules/@parcel/utils/lib/index.js  - /home/circleci/project/starters/blog/node_modules/@parcel/core/lib/public/Co  nfig.js
  - /home/circleci/project/starters/blog/node_modules/@parcel/core/lib/utils.js
  - /home/circleci/project/starters/blog/node_modules/@parcel/core/lib/public/En  vironment.js
  - /home/circleci/project/starters/blog/node_modules/@parcel/core/lib/public/As  set.js
  - /home/circleci/project/starters/blog/node_modules/@parcel/core/lib/Parcel.js  - /home/circleci/project/starters/blog/node_modules/@parcel/core/lib/index.js
  - /home/circleci/project/starters/blog/node_modules/gatsby/dist/utils/parcel/c  ompile-gatsby-files.js
  - /home/circleci/project/starters/blog/node_modules/gatsby/dist/bootstrap/get-  config-file.js
  - /home/circleci/project/starters/blog/node_modules/gatsby/dist/bootstrap/load  -config/index.js
  - /home/circleci/project/starters/blog/node_modules/gatsby/dist/services/initi  alize.js
  - /home/circleci/project/starters/blog/node_modules/gatsby/dist/services/index  .js
  - /home/circleci/project/starters/blog/node_modules/gatsby/dist/bootstrap/inde  x.js
  - /home/circleci/project/starters/blog/node_modules/gatsby/dist/commands/build  .js
  - /home/circleci/project/starters/blog/node_modules/gatsby-cli/lib/create-cli.  js
  - /home/circleci/project/starters/blog/node_modules/gatsby-cli/lib/index.js
  - /home/circleci/project/starters/blog/node_modules/gatsby/dist/bin/gatsby.js
  - /home/circleci/project/starters/blog/node_modules/gatsby/cli.js
```

Also see: https://github.com/parcel-bundler/source-map/pull/102#issuecomment-1132620562

## 🤔 Expected Behavior

Correct `files` in `package.json`. If you compare the unpkg links the new version is missing `index.js` and `build.js` and possibly other files.

## 😯 Current Behavior

https://github.com/parcel-bundler/source-map/pull/102#issuecomment-1132620562

**Comment by LekoArts** [comment]
https://github.com/parcel-bundler/source-map/commit/fc948c6d93996b05dd924291f575fdbbdf6cbd60 should hopefully fix it after publish :)

**Comment by DeMoorJasper** [comment]
Publish in progress: https://github.com/parcel-bundler/source-map/actions/runs/2357113136

**Comment by yw662** [comment]
confirm solved

**Comment by LekoArts** [comment]
Yeah, works now again 👍

**Comment by ivoba** [comment]
I just started a new parcel project using the Getting Started guide:
https://parceljs.org/getting-started/webapp/
and i get the same error on `npx parcel src/index.html`:

> Error: Cannot find module '../parcel_sourcemap_node/index'

`npm outdated` does not offer me the updated **@parcel/source-map** yet.

`npm update @parcel/source-map` solves the issue though.
