### ISSUE TITLE
Parcel does not build dependencies with local paths correctly

### ISSUE THREAD

**Issue by carterworks** [parcel-bundler/parcel#8118]
# 🐛 bug report

Inside the package.json file, [NPM supports defining local files and directories as package sources](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#local-paths). This looks something like this:

_package.json_

```json
{
  //…
  "dependencies": {
    "name": "file:./static/name"
  }
}
```

In your code, you can use it as a regular NPM dependency, like so:

_static/name/index.mjs_

```js
export default "WORLD";
```

_src/index.mjs_

```js
import name from "name";

console.log(`Hello ${name}`);
```

## 🎛 Configuration (.babelrc, package.json, cli command)

Complete configruation can be found [in the GitHub repo I've set up to reproduce the issue](https://github.com/carterworks/parcel-local-packagejson-test).

## 🤔 Expected Behavior

The library should build correctly and run without issues

```
$ node dist/index.mjs
Hello WORLD
```

## 😯 Current Behavior

The library builds without errors, but running the library fails with runtime errors

```
$ node dist/index.mjs
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'name' imported from $REPO_PATH/carterworks/parcel-local-packagejson-test/dist/main.mjs
    at packageResolve (internal/modules/esm/resolve.js:664:9)
    at moduleResolve (internal/modules/esm/resolve.js:705:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:798:11)
    at Loader.resolve (internal/modules/esm/loader.js:100:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:246:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

## 🔦 Context

I work on a Firefox extension. Firefox requires you to submit reproducible builds. Our project also depends on some company-internal dependencies. To satisfy both these requirements, we copy the library into the repository and specify it as a dependency with a `file:` source. This worked without issue in Parcel v1, but we are working on upgrading to v2 and this is blocking us.

## 💻 Code Sample

[GitHub repo I've set up to reproduce the issue](https://github.com/carterworks/parcel-local-packagejson-test).

## 🌍 Your Environment

| Software         | Version(s)                  |
| ---------------- | --------------------------- |
| Parcel           | 2.5.0                       |
| Node             | 12.22.12                    |
| npm/Yarn         | 6.14.16                     |
| Operating System |  macOS 12.3.1 21E258 x86_64 |

**Comment by devongovett** [comment]
Your example works for me. I ran the build script, and then `node dist/main.mjs` and it printed "Hello name". Did I miss something?

**Comment by carterworks** [comment]
Weird. I tried it on a different machine (with the same version of node and npm) and things worked. Must be an oddity with my local setup. Thanks for the sanity check.
