### ISSUE TITLE
parcel evaluates colors in 0xFFFFFF format causing issues

### ISSUE THREAD

**Issue by alexander-macleod** [parcel-bundler/parcel#8127]
`const colors = [
	0xed6a5a,
	0xf4f1bb
]`

will be outputted by parcel as:

`const colors = [
    15559258,
    16052667
]`

this is causing me great pain with Three.js have you any solution to this issue?

Also.. why can't i use <script type="x-shader/x-vertex">...</script>?

it's so tedious to not have thought through this stuff

It feels like Parcel 2 isnt really ready for anything beyond the basic

**Comment by mischnic** [comment]
Looks like swc does this when it's set to minify:
https://play.swc.rs/?version=1.2.189&code=H4sIAAAAAAAAA0vOzyvOz0nVy8lP1zCoSE0xSzRN1LTmSkYRNjBISzMw0LQGAJu1qewtAAAA&config=H4sIAAAAAAAAA02OPQrDMAyF76LZQ%2FHQIXPXHkK4SnCwLSMpUBNy99ohkG5C73s%2FO6waYNqhoijJuLQVwy9MQCGjBonVwHWsv2ZMSocDQ1nIBqL%2B4X2XE7PSBTjIscS5jbDAuQqp3hKWJdFflGDRmSUPOtGCob0osKBxX2Oy0dGpzJ9tuHawVuksfsJxFw3OQdT3xZ2%2BH6wLibzcAAAA

In this case, it's exactly the same length as the input, but not for `0x00ff00`. Why exactly is this causing a problem?
