### ISSUE TITLE
parcel `fstat`s through the entire source tree?

### ISSUE THREAD

**Issue by larseggert** [parcel-bundler/parcel#8128]
# 🐛 bug report

I have a `parcel` setup that just became, really, really slow. I spied on what `parcel` is doing using `strace`, and it's apparently calling `fstat` on every single file in the source tree, even things in directories that aren't related to its operation at all.

(The source tree is 40GB and has ~.5M files in it. Those are lots of small asset files that I recently added; it was much faster before I did add those.)

## 🤔 Expected Behavior

Expected `parcel` not to get bogged down by files in the source tree that it doesn't need to touch.

## 😯 Current Behavior

`strace` shows that parcel is calling `fstat` on very many files it shouldn't need to.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.5.0
| Node             |v16.15.0
| npm/Yarn         |yarn 3.2.0
| Operating System |Docker in MacOS

**Comment by mischnic** [comment]
On startup, Parcel determines the list of changes that changed compared to the last build. So this covers the project root excluding `.git`, `.hg`  and Parcel's own cache dir.

On macOS (using fsevents) or if Watchman is installed, this doesn't have to traverse the filesystem. Otherwise, it does:

https://github.com/parcel-bundler/watcher/blob/caf372c41abff401a60dde698891631e3387ee77/src/shared/BruteForceBackend.cc#L26

> The source tree is 40GB and has ~.5M files in it.

~Is this some kind of monorepo and Parcel is only used to build some subpackage (which itself doesn't contain that many files)?~ Ah, assets

**Comment by larseggert** [comment]
The host is macOS, but parcel runs in a Linux container. So if I install and run watchman in the container, this should be faster?

**Comment by larseggert** [comment]
Also, the largest slowdown is not at the beginning but at the end, after the list of processed files is dumped on the console?

**Comment by larseggert** [comment]
OK, I installed `watchman` and I see that it is running in the container, using around 5% CPU during the time I wait for `parcel` to finish up. That wait time hasn't gotten any shorter though, still takes many minutes for it to return to the shell prompt after printing out the list of built assets.

**Comment by mischnic** [comment]
So the slow call is

https://github.com/parcel-bundler/parcel/blob/9a5d48d80ebc0466481ff87d9451d33e3dbe2d57/packages/core/core/src/RequestTracker.js#L1070-L1076

which generates a list of files and timestamps (to have something to compare against on the next run).

This is stored in `.parcel-cache` in a txt file which looks like this fo rme:
```
304224
72/Users/niklas/Documents/_dev/_git/parcel/_issues/8128-fstat/assets/849241653671467682322909 0
73/Users/niklas/Documents/_dev/_git/parcel/_issues/8128-fstat/assets/2962091653671498616889276 0
73/Users/niklas/Documents/_dev/_git/parcel/_issues/8128-fstat/assets/2501251653671490892386757 0
73/Users/niklas/Documents/_dev/_git/parcel/_issues/8128-fstat/assets/2643101653671493343888645 0
72/Users/niklas/Documents/_dev/_git/parcel/_issues/8128-fstat/assets/199901653671465011441292 0
72/Users/niklas/Documents/_dev/_git/parcel/_issues/8128-fstat/assets/790491653671467469633622 0
73/Users/niklas/Documents/_dev/_git/parcel/_issues/8128-fstat/assets/1575791653671474466465278 0
...
```
and indeed contains one entry per file (my assets folder has 300k files and this file lists 304224).

**Comment by mischnic** [comment]
As far as I can tell, Parcel only uses files inside the [ietf](https://github.com/ietf-tools/datatracker/tree/main/ietf) directory. Moving Parcel inside of that folder (and having a `ietf/yarn.lock` file) would move the project root to maybe not include include the assets.
Something like https://github.com/parcel-bundler/parcel/issues/7206 would simplify this by allowing to override the project root detection (and thus the file watching).

**Comment by larseggert** [comment]
Yes, that would work.

Could Parcel not automatically restrict itself to tracking under whatever the narrowest shared directory prefix of the sources is?
