### ISSUE TITLE
🐛 Cannot import *.json files

### ISSUE THREAD

**Issue by Siyfion** [parcel-bundler/parcel#813]
### 🎛 Configuration

`.babelrc`
```json
{
  "presets": ["env", "react"],
  "plugins": [
    "transform-object-rest-spread",
    "transform-class-properties"
  ],
  "ignore": [
    "node_modules"
  ]
}
```

### 🤔 Expected Behavior

```js
import exampleJson from './example.json'
```
Should correctly import the file and allow the JSON object to be used.

### 😯 Current Behavior

The project will build successfully, but then at runtime:
> `exampleJson is not defined`

Interestingly, if you change the import to the following:

```js
const exampleJson = require('./example.json')
```
It will be imported correctly and at runtime you will have access to the object.

### 💁 Possible Solution

Currently the test uses the `require` syntax, which is perhaps why this bug hasn't been picked up?

https://github.com/parcel-bundler/parcel/blob/master/test/integration/json/index.js

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v1.5.1
| Node             | v9.5.0
| npm/Yarn         | v1.3.2
| Operating System | macOS

**Comment by Siyfion** [comment]
After further investigations, it only *appears* that the `*.json` file isn't being imported correctly when debugging with Chrome DevTools. In actuality the file was imported correctly, and could be accessed fine. 

But if you load Chrome DevTools up and try to inspect the `exampleJson` variable, it comes back as not being defined.

I'll close this as it's not really the issue I thought it was, but perhaps this other side-effect needs to be looked into?

**Comment by fathyb** [comment]
Does it do it when source maps are disabled in the DevTools (Settings -> uncheck Enable JavaScript source maps)?

**Comment by Siyfion** [comment]
@fathyb ok, and it gets weirder.... 

If I mouse over the values in the following (with source maps enabled):
```js
console.log(`${example.a} + ${example.b}`)
```

I can see the JSON object in `example`, but if I mouse over the import statement, or use it in a watch, it complains.
