### ISSUE TITLE
Support safari webextensions in runtime-js

### ISSUE THREAD

**Issue by Kjoep** [parcel-bundler/parcel#8141]
# 🙋 feature request

Runtime-js currently has specific support for chrome and firefox extensions. It has logic to generate a url relative to the bundle root.  For Safari this logic is missing, and parcel generates non-functional URLs. (could be considered a bug, depending on how you look at it)

## 🤔 Expected Behavior

When accessing assets in a safari extension, URLs should be formed correctly by getBundleUrl/getBaseUrl/getOrigin.

## 😯 Current Behavior

URLs generated by getBundleUrl/getBaseUrl/getOrigin do not get transformed and are not generally resolvable in a safari extension.

## 💁 Possible Solution

Adapt the regex in bundle-url.js to also support safari extensions.
I wrote a fix here: https://github.com/parcel-bundler/parcel/commit/6b8231771555acc8d12da49d29ed9b97d4f0c165

**Comment by 101arrowz** [comment]
Feel free to make a PR with that commit! We have only tested that regex on Chrome and Firefox extensions, but I think pretty much every major browser beyond Firefox uses Chromium at this point so they all use `chrome-extension`. I guess Safari made their own implementation though.

**Comment by Kjoep** [comment]
Hi @101arrowz .  A PR is here: https://github.com/parcel-bundler/parcel/pull/8175  Let me know if I did it wrong ;)
