### ISSUE TITLE
`jsxImportSource` not working for packages with no `jsx-dev-runtime` export

### ISSUE THREAD

**Issue by mindplay-dk** [parcel-bundler/parcel#8148]
# 🐛 bug report (feature request?)

In `tsconfig.json`, regardless of setting `jsx` to `react` or `react-jsx`, when running `parcel` is development mode, it always attempts to load the `jsx-dev-runtime` from the `jsxImportSource`, and fails.

## 🎛 Configuration (.babelrc, package.json, cli command)

With `tsconfig.json` options set to, for example, this:

```js
{
    "jsx": "react-jsx",
    "jsxImportSource": "solid-js/h"
}
```

From my (limited) understanding, if `jsx` is set to `react-jsx` rather than `react`, it should always import from `solid-js/h/jsx-runtime`.

This works fine with `parcel build` - but with `parcel watch`, it attempts to load `solid-js/h/jsx-dev-runtime`, which doesn't exist in that package.

`solid-js` doesn't have any special module for development - it only has the `jsx-runtime`.

So I can use this package only with `parcel build` but not with `parcel watch`.

I don't see any way to override anything via configuration?

## 🤔 Expected Behavior

Not sure.

If I understand the difference between `jsx` being set to `react` or `react-jsx`, it shouldn't be trying to load the `jsx-dev-runtime`?

If that's not how that option works, maybe there should be some other way to configure it to use the `jsx-runtime`, even in development mode?

Or perhaps it should check first if `jsx-dev-runtime` exists, and automatically fall back to `jsx-runtime` if it does not?

## 😯 Current Behavior

With `parcel watch`, as soon as it encounters a file with JSX in it, it fails to build:

```
> parcel watch

🚨 Build failed.

@parcel/core: Failed to resolve 'solid-js/h/jsx-dev-runtime' from './src/client/app/App.tsx'

  /home/mindplay/workspace/dating/src/client/app/App.tsx:1:1
  > 1 | import { onCleanup, createSignal } from "solid-js";
  >   | ^
    2 | import { render } from "solid-js/web";
    3 |
```

## 🔦 Context

Plenty of JSX libraries don't have a dedicated `jsx-dev-runtime`, as far as I know?

## 💻 Code Sample

No code sample at the moment, as I can't install Parcel 2.6, which requires gyp with a newer version of Python, which isn't supported by my version of Ubuntu, and so it looks like I have to tear down my dev environment and start over. 😟

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | stuck on 2.5
| Node             | 16.14.12
| npm/Yarn         | npm 8.5.5
| Operating System | Ubuntu 16.04.7 LTS

**Comment by mischnic** [comment]
Preact also doesn't have a dev runtime, but they alias it the regular one:

https://github.com/preactjs/preact/blob/43d79c0e8f727e9ac745a50c3a61868adb2dcfe7/package.json#L54-L66

Here's the Parcel code that handles this

https://github.com/parcel-bundler/parcel/blob/f2d0a3a27d6e493b23ddc2edbc8a4c0053ff34ab/packages/transformers/js/src/JSTransformer.js#L197-L203

What I find strange about the tsconfig [`jsx`](https://www.typescriptlang.org/tsconfig#jsx) option is that there is no setting for "use jsxImportSource but automatically decide whether do use the dev version or not".

So what we might be able to do:
- make `react-jsx` always use the non-dev version. (As an override as you described)
- throw an error with `react-jsxdev` because this will result in the dev version being used even for production builds.

**Comment by mindplay-dk** [comment]
> What I find strange about the tsconfig [`jsx`](https://www.typescriptlang.org/tsconfig#jsx) option is that there is no setting for "use jsxImportSource but automatically decide whether do use the dev version or not".

The `tsc` compiler doesn't have production or development modes, so that's probably why? If you need more than one "mode", you create several `tsconfig.*.json` files, e.g. a `tsconfig.dev.json` which `extends` the production `tsconfig.json` and overrides the `jsx` option with e.g. `react-jsxdev`.

Parcel on the other hand (I guess?) expects a single `tsconfig.json` file from which it establishes it's defaults - then uses e.g. `targets` to override certain options.

Since Parcel operates with development and production modes, it should probably override these settings?

So, if `jsx` is set to `react-jsx`, and Parcel is in development mode, it should probably treat it as `react-jsxdev`.

Similarly, when `jsxImportSource` is set, Parcel should let development/production mode decide the name of the export that gets loaded - that part actually seems correct. If you were manually setting up multiple `tsconfig.*.json` files for `tsc`, you simple wouldn't use the `react-jsxdev` if your package doesn't support it. Only, in Parcel, we have one `tsconfig.json` for both production and development, so we have nowhere to configure that.

So maybe what it should do, in development mode, is check if an export with that name exists - and if not, fall back to the non-dev export? It should prefer the dev-mode export when available, it just shouldn't assume that it exists.

Does that make sense?

**Comment by mischnic** [comment]
> So, if jsx is set to react-jsx, and Parcel is in development mode, it should probably treat it as react-jsxdev.

That is exactly what's happening right now.

> So maybe what it should do, in development mode, is check if an export with that name exists - and if not, fall back to the non-dev export? It should prefer the dev-mode export when available, it just shouldn't assume that it exists.

This would have to be checked again for every single asset.

Can you workaround this by adding
```json
{
  "alias": {
    "solid-js/h/jsx-dev-runtime": "solid-js/h/jsx-runtime"
  }
}
```
in your project?


Also, have you seen https://github.com/solidjs/solid/issues/876?

**Comment by mindplay-dk** [comment]
> > So, if jsx is set to react-jsx, and Parcel is in development mode, it should probably treat it as react-jsxdev.
> 
> That is exactly what's happening right now.

Understood, I am just reaffirming that this already seems correct to me - just making sure I don't point you in a direction where we end up breaking something else. 🙂

> > So maybe what it should do, in development mode, is check if an export with that name exists - and if not, fall back to the non-dev export? It should prefer the dev-mode export when available, it just shouldn't assume that it exists.
> 
> This would have to be checked again for every single asset.

Maybe do the check once, at startup, and cache the result?

> Can you workaround this by adding
> 
> ```json
> {
>   "alias": {
>     "solid-js/h/jsx-dev-runtime": "solid-js/h/jsx-runtime"
>   }
> }
> ```
> 
> in your project?

Yes, I tried exactly that, before opening this issue. I don't understand what's different, but for some reason, in dev mode, that results in the standard counter example building and running without errors... but rendering the word "true" on the page instead of a counter. Is there JSX dev runtime somehow linked or treated differently than the non-dev run-time? I couldn't figure it out.

> Also, have you seen [solidjs/solid#876](https://github.com/solidjs/solid/issues/876)?

Yes, I saw that, and a stackoverflow post, and tried asking on the Solid discussion board as well, before I decided to open this issue. 

And yes, I have been able to get Solid to work with Babel and the custom transform.

The thing is, you shouldn't *need* the custom transform - there is a normal hyperscript `h` function available in Solid, which *should* work with the standard JSX transform.

(There's a list of reasons why I'm not enticed by the custom transform. For one, I would prefer to avoid Babel, and JS in general, letting Rust do the heavy lifting, for a smoother development cycle. The standard JSX transform produces smaller output code. The custom transform is an optimization, and the performance difference is marginal. And not least, the custom transform allows you to omit closures - but I actually like the closures, which, being optional, can be used to control what can or cannot update. For another, the standard JSX transform is extremely simple and very easy to explain.)

(I realize I may be swimming against the stream a little bit - to begin with, Solid recommends Vite, and for various reasons I prefer Parcel. It looks like no one else has tried or tested this exact combination. I just don't see why this shouldn't work. The `h` function is there and can be used with the hand-written approach, which is officially documented and supported. I've taken other frameworks in the past and used JSX to invoke their `h` function...)

**Comment by mischnic** [comment]
> Maybe do the check once, at startup, and cache the result?

I think your niche usecase (and apparently unsupported by Solid itself) doesn't quite justify such hacks 😬 

>  Is there JSX dev runtime somehow linked or treated differently than the non-dev run-time? I couldn't figure it out.

The only difference is the import specifier that gets inserted by swc. Otherwise there's no difference I know of (e.g. regarding resolving).
