### ISSUE TITLE
Live-reload extension upon manifest.json changes

### ISSUE THREAD

**Issue by ColdSauce** [parcel-bundler/parcel#8159]
# 🙋 feature request

Would be awesome if Parcel could watch for changes in `manifest.json` and somehow get the extension to `chrome.runtime.reload` itself. 

## 🤔 Expected Behavior

While running with HMR enabled, a change to the `manifest.json` should trigger a reload of the entire extension. 

## 😯 Current Behavior

Right now, devs have to manually reload an extension any time they make a change to the manifest. 

## 💁 Possible Solution

I'm not too familiar with Parcel's code, but if we could somehow run:

```
env.runtime.sendMessage({
      __parcel_hmr_reload__: true,
    });
```
whenever the `manifest.json` is modified, I think this would enable reloading.

## 🔦 Context

Two scenarios:
1. There have been countless times where my brain is in a "Parcel handles auto-reload for me so I don't have to worry about manually reloading my extension" mode. So when adding a new permission to my manifest, I sometimes forget I actually need to manually refresh my extension. 

2. We've built a framework for browser extensions that uses Parcel under the hood. Our framework auto-generates a `manifest.json` based on usage within the project. For example, when someone adds a `background.ts` file in their project directory, our framework will generate a manifest pointing to the built `background` source, and so on. Parcel's limitation makes the developer experience not great at times as devs have to guess when the framework will modify the `manifest.json` and reload accordingly. This limitation unfortunately introduces a leaky abstraction in our framework.

**Comment by 101arrowz** [comment]
This is currently already done for changes to content scripts but it might be harder to implement for changes to the manifest. I'll try to look into this.
