### ISSUE TITLE
parcel unable to build with npm i @voxeet/voxeet-web-sdk

### ISSUE THREAD

**Issue by azeemgujjar** [parcel-bundler/parcel#8164]
Hello,

I am using parcel for the first time in my project but unfortunately after installing "npm i @voxeet/voxeet-web-sdk"
parcel is unable to build project which is bottle neck for me.
Ofcourse i can't change thirdparty SDK, anybody can tell me how to resolve this?

Here is the error:

` * POSSIBILITY OF SUCH DAMAGE.

190 | rker("voxeet-dvwc-worker.js"),this.workerAsyncCall=new y(this.worker),this.worker.onmessage=e=>this.onWorkerMessage(e.data);const a=new MessageChannel,s
| ^^^^^^^^^^^^^^^^^^^^^^^
191 | //! moment.js
192 | i.version="2.29.1",t=Pt,i.fn=vn,i.min=function(){var e=[].slice.call(arguments,0);return Et("isBefore",e)},i.max=function(){var e=[].slice.call(argument

💡 Replace with: new URL('voxeet-dvwc-worker.js', import.meta.url)

**Comment by devongovett** [comment]
The code includes `new Worker('voxeet-dvwc-worker.js')`. Passing strings to the worker constructor is ambiguous, and cannot be resolved at build time. In the browser, this will resolve relative to the document URL, not relative to the script tag. Parcel cannot know what the document URL will be at build time. So we require you to use the `new URL` syntax as in the error message to make this explicit, i.e. relative to the containing script.

**Comment by mischnic** [comment]
The problem is that this worker call is part of an npm package: https://unpkg.com/browse/@voxeet/voxeet-web-sdk@3.5.1/dist/voxeet-sdk.js
