### ISSUE TITLE
Variable Interpolation is not compiling in parcel

### ISSUE THREAD

**Issue by ArunaArivazhagan** [parcel-bundler/parcel#8172]
Variable Interpolation is not getting compiled in parcel. Sample url is given below

Sample URL : https://lesscss.org/features/#variables-feature-variable-interpolation

Sample Code:
// Variables
@my-selector: banner;

// Usage
.@{my-selector} {
  font-weight: bold;
  line-height: 40px;
  margin: 0 auto;
}

## 🤔 Expected Behavior
.banner {
  font-weight: bold;
  line-height: 40px;
  margin: 0 auto;
}

## 😯 Current Behavior

Its not getting compiled and nothing is shown.

## 💻 Code Sample

// Variables
@my-selector: banner;

// Usage
.@{my-selector} {
  font-weight: bold;
  line-height: 40px;
  margin: 0 auto;
}

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.0
| Node             | 14.19.2
| npm/Yarn         | 6.14.17
| Operating System | MacOs

<img width="1645" alt="Screenshot 2022-05-30 at 6 31 17 PM" src="https://user-images.githubusercontent.com/106536703/171000532-c85660c4-646b-46b9-b111-62fb1c379c0e.png">

**Comment by mischnic** [comment]
I've just tried it and it works correctly. Please provide a zip file or repo with a small complete project that fails for you.

**Comment by ArunaArivazhagan** [comment]
I will try to attach sample code. Attached below the package.json. Let me know if anything is missed out.

{
    "name": "aem-site-template-standard-theme",
    "version": "0.0.1",
    "description": "Standard AEM site theme",
    "license": "MIT License, Copyright 2020 Adobe Systems Incorporated",
    "scripts": {
        "build": "rimraf dist && parcel build src/theme.ts --no-optimize",
        "watch": "parcel watch src/theme.ts",
        "proxy": "aem-site-theme-builder live",
        "live": "npm-run-all -p watch proxy"
    },
    "devDependencies": {
        "@adobe/aem-site-theme-builder": "5.2.1",
        "@parcel/transformer-less": "^2.6.0",
        "@parcel/transformer-sass": "^2.0.1",
        "autoprefixer": "^10.3.7",
        "browser-sync": "^2.26.13",
        "install": "^0.13.0",
        "normalize.css": "^8.0.1",
        "npm": "^8.1.4",
        "npm-run-all": "^4.1.5",
        "parcel": "^2.6.0",
        "parcel-namer-rewrite": "^2.0.0-rc.1",
        "postcss": "^8.3.11",
        "process": "^0.11.10",
        "rimraf": "^3.0.2",
        "typescript": "^4.5.2"
    },
    "parcel-namer-rewrite": {
        "chain": "@parcel/namer-default",
        "rules": {
            "(.*?)(\\.[a-f0-9]{8})?\\.(ttf|woff2?)": "resources/fonts/$1.$3",
            "(.*?)(\\.[a-f0-9]{8})?\\.(svg|png|gif|jpg|jpeg|webp)": "resources/images/$1.$3"
        }
    },
    "parcelDependencies": {
        "@parcel/optimizer-data-url": "2.6.0",
        "@parcel/packager-raw-url": "2.6.0"
    }
}

**Comment by muneesk** [comment]
@mischnic 

Find the below git repo and test to replicate the issue.
1. Clone the below repo
https://github.com/muneesk/aem-site-template-standard.git
2. from the root directory run "npm install "
3. then run "rpm run build" from the root directory.
4. Once the build success go to theme/dist/theme.css
5. Actually parcel is compiling only the last @import css in theme.less. it is not supporting two less import.

 Below trying to compile two Less file with variable interpolation approach like "@component-name: cmp-accordion;"
and for tabs "@component-name: "cmp-tabs"; and then trying to compile the less and its compiling only the last imported less file.

<img width="595" alt="lessimports" src="https://user-images.githubusercontent.com/3716038/171207911-826e7784-7fa0-499e-a0ec-4d199b313fa1.png">

<img width="703" alt="theme" src="https://user-images.githubusercontent.com/3716038/171208325-5e7abed4-9fb1-4232-b28e-1a66bab78ace.png">

Expected Output : 

<img width="924" alt="Expected" src="https://user-images.githubusercontent.com/3716038/171208816-1e2aa30f-ef10-4cf3-8a25-1a50e728b8ed.png">

**Comment by mischnic** [comment]
@ArunaArivazhagan Here's a working example: https://github.com/mischnic/parcel-issue-8172

**Comment by muneesk** [comment]
@mischnic - if it is single less file the parcel is compiling properly. If we are trying to import two less file with the same approach it's not compiling properly. please see the below example file to replicate the issue.

https://github.com/muneesk/parcel-issue-8172

cc: @ArunaArivazhagan

**Comment by mischnic** [comment]
@muneesk Your problem has nothing to do with the problem reported here. Please open a new issue

**Comment by ArunaArivazhagan** [comment]
This approach is working as expected. Thanks for your support !
