### ISSUE TITLE
HMR stops working when a page includes a "classic" script

### ISSUE THREAD

**Issue by supernes** [parcel-bundler/parcel#8173]
# 🐛 bug report

Live reloading on changes and HMR work as expected, until an HTML page includes a "classic" (non-module) script.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
"browserslist": "> 0.5%, last 2 versions, not dead",
"devDependencies": {
  "parcel": "^2.5.0",
  "posthtml-expressions": "^1.9.0",
  "posthtml-extend": "^0.6.3",
  "posthtml-include": "^1.7.4"
}
```

## 🤔 Expected Behavior

Modifications to files are automatically reflected by updating the page in the browser.

## 😯 Current Behavior

Reloading ceases to work after adding a `<script>` tag without a `module` attribute.

No error is shown, and no WS communication occurs.

## 💁 Possible Solution

Use modules always.

## 🔦 Context

I wanted to add a fairly simple, vanilla script to an HTML page, but noticed that auto-reload stopped working after I did so. It can either be an external script (`<script src="...">`) or inline (`<script>...</script>`). As long as it's not a module, HMR stops working entirely.

## 💻 Code Sample

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <script>
    window.addEventListener('load', e => console.log('load'))
  </script>
</head>
<body>
  This will not reload automatically when the page is changed (until the script is marked as a module).
</body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.5.0
| Node             |v16.13.1
| npm/Yarn         |8.10.0
| Operating System |Linux 5.15.32 armv7l

**Comment by mischnic** [comment]
HMR only works in for module scripts, this is an intentional decision/limitation of classic scripts

**Comment by supernes** [comment]
I'm sorry, I believe I didn't describe the issue well enough. What I meant to say is that all live reloading on changes - even of the HTML content - stops working, not just ES code replacement. Here's an illustration of various scenarios:

| Type of input | Live reload works? |
|------------------|---------------------------|
| HTML only   | 🟢 Yes |
| HTML + Classic script | 🔴 No |
| HTML + Module script | 🟢 Yes |
| HTML + Module + Classic | 🟢 Yes |

Can you please confirm that this is working as intended?

**Comment by mischnic** [comment]
Ah, that means we need to use the condition "has a module script" instead of just "has any script" here

https://github.com/parcel-bundler/parcel/blob/3b3b13557dba9d1a403c86550915c6013dd78dfe/packages/transformers/html/src/HTMLTransformer.js#L67-L69

**Comment by Magi-KS** [comment]
https://github.com/parcel-bundler/parcel/blob/3b3b13557dba9d1a403c86550915c6013dd78dfe/packages/transformers/html/src/HTMLTransformer.js#L67-L69

why is it necessary to check for "has a module script"?
i was thinking of just doing this:
```js
if (options.hmrOptions) { 
```
