### ISSUE TITLE
Multiple less files with variable interpolation is not compiling using parcel

### ISSUE THREAD

**Issue by ArunaArivazhagan** [parcel-bundler/parcel#8178]
I have tried to compile 2 less files with Variable declaration using Parcel. Below trying to compile two Less file with variable interpolation approach like "@component-name: banner1;"
and "@component-name: "banner2"; and then trying to compile the less and its compiling only the last imported less file.

Find the below git repo and test to replicate the issue.

Clone the below repo
https://github.com/ArunaArivazhagan/parecelless
from the root directory run "npm install "
then run "rpm run build" from the root directory.
Once the build success go to theme/dist/theme.css
Actually parcel is compiling only the last https://github.com/import css in theme.less. it is not supporting two less import.

<img width="407" alt="Screenshot 2022-06-01 at 11 48 02 AM" src="https://user-images.githubusercontent.com/106536703/171343101-31be69c2-4626-47c7-9ec3-7d1836d694ef.png">

<img width="381" alt="Screenshot 2022-06-01 at 11 48 19 AM" src="https://user-images.githubusercontent.com/106536703/171343135-029585e5-50b9-4aa1-981b-5d39b5570948.png">

<img width="587" alt="Screenshot 2022-06-01 at 11 48 30 AM" src="https://user-images.githubusercontent.com/106536703/171343222-dcb3a072-72d7-4b96-9dfa-46be964b4404.png">

**Comment by ArunaArivazhagan** [comment]
Any updates on the above issue ? Can anyone help me on this ?

**Comment by ArunaArivazhagan** [comment]
@mischnic 

Can you please help me on this issue ?

**Comment by mischnic** [comment]
It looks like less variables are global:

If you run `npx lessc index.scss` ([the official less compiler](https://lesscss.org/usage/#command-line-usage)) in that repo, the output is
```less
.banner2 {
  font-weight: bold;
  line-height: 40px;
  margin: 0 auto;
}
.banner2 {
  font-weight: bold;
  line-height: 40px;
  margin: 0 auto;
}
```
