### ISSUE TITLE
Build does not recognize JS assert import of stylesheets

### ISSUE THREAD

**Issue by uffeat** [parcel-bundler/parcel#8193]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
Please fill out the issue template
