### ISSUE TITLE
Suggest to add option to CLI for inline source map

### ISSUE THREAD

**Issue by 3cp** [parcel-bundler/parcel#8203]
# 🙋 feature request

Suggest to add option such as `--inline-source-maps` to turn on writing source maps in bundled js file itself.

Probably should also add `--inline-sources` and `--source-root=xxx` (`--source-root xxx`) to match the available sourceMap options in `targets` config.

Thx!

## 🤔 Expected Behavior

Expect to fully control the behaviour of source map without using `targets` config.

## 😯 Current Behavior

Currently parcel cli only supports `--no-source-maps` to turn of the default source map.
The default source map uses separate `.js.map` file, which is not changeable through CLI.

**Comment by devongovett** [comment]
What is your use case for this? Why can't you use the targets config? If we added every option to the CLI it would get out of hand fast.

**Comment by 3cp** [comment]
I see :-) Understandable.
Yes, I can use targets. Just wondering the possibility to avoid targets config.

**Comment by devongovett** [comment]
In general, configuring things in files is usually better than doing it on the CLI unless you need to change it dynamically (i.e. per `parcel` invocation). This way, it's written down and easier to share with other developers, and you don't need to remember all the options when running Parcel. If you are using package.json scripts to run the Parcel CLI, then you are already writing the options in the package.json file anyway, so it isn't really much different from adding the options elsewhere in the same file.
