### ISSUE TITLE
@parcel/transformer-css: Unexpected token Number ('.1') with semantic-ui

### ISSUE THREAD

**Issue by mathieucaroff** [parcel-bundler/parcel#8207]
# 🐛 bug report

I'm trying to start using parcel in a big project but `@parcel/transformer-css` conflicts with `semantic-ui-react`: the tokenization finds a floating point number in semantic-ui's minified CSS file, when it's actually a class selector (`.1`). This ends up causing a parsing error.

## 🤔 Expected Behavior

The CSS is tokenized, parsed, compiled and included into the bundle.

## 😯 Current Behavior

An error is reported and the bundle aborts:

```
@parcel/transformer-css: Unexpected token Number { has_sign: false, value: 0.1, int_value: None }

  C:\...\src\vendors\semantic-ui\semantic.min.css:75:18614
    74 |  *
  > 75 | e.neg.1:before{content:'\e3cb'}i.icon.exposure.neg.2:before{content:'\e3cc'}i.icon.exposure.plus.1:before{content:'\e3cd'}i.icon.exposure.plus.2:before{  >    |      ^
    76 |  * # Semantic UI 2.4.2 - Image
    77 |  * http://github.com/semantic-org/semantic-ui/
```

## 🔦 Context

I'm trying to switch from Create-React-App project (WebPack) to Parcel.

## 💻 Code Sample

`index.js`

```
import { Form } from 'semantic-ui-react'
```

`parcel build index.js`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.0 |
| Node             | v16.15.1
| npm/Yarn         | npm |
| Operating System | Windows |
| "semantic-ui-react" | "2.0.4" |
| Semantic UI | 2.4.2 |

This issue is similar to https://github.com/parcel-bundler/parcel/issues/7963 but I don't know whether the css syntax will favor parcel or semantic-ui this time around.

**Comment by mischnic** [comment]
As far as I can tell, a [class selector](https://drafts.csswg.org/selectors/#class-html) is `.` followed by an [identifier](https://drafts.csswg.org/css-values-4/#css-css-identifier) which is an [`ident-token`](https://www.w3.org/TR/css-syntax-3/#ident-token-diagram) which cannot start with a number.
