### ISSUE TITLE
parcel build segfaults on cache unreadable

### ISSUE THREAD

**Issue by mxork** [parcel-bundler/parcel#8208]
# 🐛 bug report

`parcel build --no-cache` attempts to open `.parcel-cache/lock.mdb` and `.parcel-cache/data.mdb`. If `.parcel-cache` is not readable, triggers segfault.

## 🎛 Configuration (.babelrc, package.json, cli command)

```
#!/bin/bash

mkdir demo
cd demo

cat > package.json <<EOF
{
  "name": "break-parcel",
  "devDependencies": {
    "parcel": "^2.6.0"
  }
}
EOF

cat > index.html <<EOF
<html></html>
EOF

npm install

rm -rf .parcel-cache
mkdir .parcel-cache
chmod 000 .parcel-cache

npx parcel build --no-cache index.html
```
output:

```
...
recreate.sh: line 20: 36479 Segmentation fault      (core dumped) npx parcel build --no-cache index.html
```

## 🤔 Expected Behavior

`--no-cache` should disable any reads, writes, or creates of the cache folder.

## 😯 Current Behavior

Segfault.

## 💁 Possible Solution

Do not read `.parcel-cache` if instructed not too.

## 🔦 Context

I originally encountered this while debugging a non-deterministic hang of `parcel build` inside a container, which I suspected was cache related. Attaching to the process showed that `data.mdb` and `lock.mdb` were both open and all threads were blocked on `epoll_wait` or `futex`. I tried disabling the cache with `--no-cache`, but the behavior persisted.

## 💻 Code Sample

Above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.0
| Node             | 16.14.2
| npm/Yarn         | 8.5.0
| Operating System | [Archlinux]()

**Comment by mxork** [comment]
maybe related: https://github.com/parcel-bundler/parcel/issues/7548

**Comment by mischnic** [comment]
> Do not read .parcel-cache if instructed not too.

The cache is still used for IPC communication with the workers. So `--no-cache` only means that it will not use results from previous builds.

**Comment by mxork** [comment]
Fair enough. Segfault'ing is a still a very surprising response to a filesystem error, so I will leave the issue open for the moment with reduced scope.

**Comment by mischnic** [comment]
👍  I suspect the segfault is caused by https://github.com/DoctorEvidence/lmdb-js not handling this FS error correctly
