### ISSUE TITLE
Incorrect resolution of package with conditional exports

### ISSUE THREAD

**Issue by marcoreni** [parcel-bundler/parcel#8221]
# 🐛 bug report

When trying to build a webapp with an isomorphic dependency that uses NodeJS conditional exports, the build loads the NodeJS version of the dependency.

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```json
{
  "dependencies": {
    "crypto-hash": "^2.0.1",
    "parcel": "^2.6.0"
  },
  "source": "index.html",
  "scripts": {
    "build": "parcel build --no-autoinstall"
  }
}
```

index.js
```js
import { sha256 } from "crypto-hash";

sha256("foobar").then((data) => console.log(data));
```

index.html
```html
<html>
  <body>
    <script type="module" src="index.js"></script>
  </body>
</html>
```
## 🤔 Expected Behavior

I expected Parcel to use the browser version of the library.

## 😯 Current Behavior

Parcel loads the NodeJS version of the library and attempts to install polyfills:

```

🚨 Build failed.

@parcel/core: Failed to resolve 'node:buffer' from './node_modules/crypto-hash/index.js'

  /Volumes/Workspace/work/data/parcel-repro/node_modules/crypto-hash/index.js:1:22
  > 1 | import {Buffer} from 'node:buffer';
  >   |                      ^^^^^^^^^^^^^
    2 | import {Worker} from 'node:worker_threads';
    3 | import crypto from 'node:crypto';

@parcel/resolver-default: Node builtin polyfill "buffer" is not installed, but auto install is disabled.

  /Volumes/Workspace/work/data/parcel-repro/node_modules/crypto-hash/index.js:1:22
  > 1 | import {Buffer} from 'node:buffer';
  >   |                      ^^^^^^^^^^^^^ used here
    2 | import {Worker} from 'node:worker_threads';
    3 | import crypto from 'node:crypto';

  💡 Install the "buffer" package with your package manager, and run Parcel again.
  📝 Learn more
```

## 🔦 Context

The [dependency](https://github.com/sindresorhus/crypto-hash/blob/main/package.json#L14) uses [Conditional exports](https://nodejs.org/docs/latest-v16.x/api/packages.html#conditional-exports) .

I was able to have the build working by setting an alias:

```json
"alias": {
  "crypto-hash": "crypto-hash/browser"
}
```
## 💻 Code Sample

See above

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | latest
| Node             | 16.15.1
| npm/Yarn         | npm 8.11.0
| Operating System | MacOS 12.3.1 on M1

**Comment by devongovett** [comment]
Conditional exports are not currently supported. Please see #4155.
