### ISSUE TITLE
Parcel serve gives HTTP 426 "Upgrade Required"

### ISSUE THREAD

**Issue by karneaud** [parcel-bundler/parcel#8222]
# 🐛 bug report

When using `parcel  serve...` I get the subject output response when visiting the started server url

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
"main": "index.js",
  "scripts": {
    "dev": "parcel serve --port 3000 --no-cache --hmr-port 3001 --log-level verbose index.html"
  },
  "license": "MIT",
  "browserslist": [
    "> 1%",
    "last 3 versions"
  ],
  "bugs": {
    "url": "https://github.com/vedees/wcms/issues"
  },
  "dependencies": {
    "axios": "^0.27.2",
    "chart.js": "^2.7.3",
    "codemirror": "^5.42.0",
    "locutus": "^2.0.10",
    "save": "^2.3.3",
    "uimini": "^1.1.3",
    "vue": "^3.0.2",
    "vue-chartjs": "^3.4.0",
    "vuex": "4.0.0"
  },
  "devDependencies": {
    "@parcel/transformer-stylus": "2.6.0",
    "@parcel/transformer-vue": "2.6.0",
    "parcel": "^2.6.0",
    "process": "^0.11.10"
  },
```

I have no  babel configuration

I run a yarn script `yarn dev`

## 🤔 Expected Behavior

Should see the project at the given url

## 😯 Current Behavior

Get HTTP 426 "Upgrade Required"

## 🔦 Context

Was simply starting a Vue.js project upgrading from Vue 2.x.x to Vue 3.x.x

## 💻 Code Sample

The project was taken from https://github.com/karneaud/wcms ...though it is initially using webpack I'm converting to parcel for a more simpler tooling approach

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.6.0
| Node             | v18.3.0
| npm/Yarn         | Yarn 1.22.19
| Operating System | Docker

**Comment by fhellwig** [comment]
This does not seem to be isolated. I too am observing this same behavior.

**Comment by karneaud** [comment]
> This does not seem to be isolated. I too am observing this same behavior.

@fhellwig

Are we using the same version? 

I'm going to reference [this issue](https://github.com/parcel-bundler/parcel/issues/7552) as there may be more to both.
