### ISSUE TITLE
Production build on AntD Menu widget results with error: Invalid attempt to spread non-iterable instance.

### ISSUE THREAD

**Issue by doronrosenberg** [parcel-bundler/parcel#8225]
# 🐛 bug report

Using the latest Parcel to deploy an application that uses Ant Design React Components:

```
import React from 'react';
import { Menu } from "antd";

export function App() {
  const items = [
    { label: 'item 1', key: 'item-1' },
  ];
  return <Menu items={items} />;
}
```

I am hitting the error:

```
 Invalid attempt to spread non-iterable instance.
```

The issue does not happen in development mode (`parcel`) but does happen in production (`parcel build`).  Removing the items property stops the error from happening as well.

## 🤔 Expected Behavior

Production code should work just like development.

## 😯 Current Behavior

The following error happens:

```
react-dom.production.min.js:189 TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at F (nonIterableSpread.js:2:9)
    at R (toConsumableArray.js:6:95)
    at PathContext.js:13:47
    at Object.useMemo (react-dom.production.min.js:184:189)
    at Object.T (react.production.min.js:25:208)
    at yt (PathContext.js:12:10)
    at Nt (MenuItem.js:204:26)
    at Li (react-dom.production.min.js:167:137)
    at Ru (react-dom.production.min.js:290:337)
    at Nc (react-dom.production.min.js:280:389)
```

## 💁 Possible Solution

Webpack works fine here, so this seems to not be a Ant Design issue but something Parcel uses?

## 💻 Code Sample

Reproduction:  https://github.com/doronrosenberg/parcel-antd-issue

## 🌍 Your Environment
Latest versions, running on an M1 Mac.

**Comment by mischnic** [comment]
It's a Terser minifier bug: https://github.com/terser/terser/issues/1214

**Comment by lemonspb** [comment]
Same problem. don't want to use webpack

**Comment by doronrosenberg** [comment]
> Same problem. don't want to use webpack

You can change parcel to use swc or esbuild to minify instead of terser.  That worked around the issue, though the bundle size is a bit larger with those.  I found the details at https://github.com/parcel-bundler/parcel/issues/7847.

**Comment by mischnic** [comment]
Another possibility would be adding a `.terserrc` that disables some features of terser:
```
{
  compress: {inline: 2},
}
```
The value can be 0-3, 3 is the default and does the most inlining. 0 doesn't inline anything. So I imagine that somewhere along that spectrum, the bug should go away

**Comment by lemonspb** [comment]
thank you very much this method worked for me
