### ISSUE TITLE
validator-eslint fails on glob patterns

### ISSUE THREAD

**Issue by mehdisadeghi** [parcel-bundler/parcel#8234]
# 🐛 bug report
Having both resolver-glob and validator-eslint in parcel config causes an error. eslint-validator tries to literally import the glob file such as `import ./modules/*.js'` and fails, since such file does not exist. However, the resolved files are inspected correctly.

## 🎛 Configuration (.babelrc, package.json, cli command)

.parcelrc file:
```

{
  "extends": "@parcel/config-default",
  "resolvers": ["@parcel/resolver-glob", "..."],
  "transformers": {
    "*.svg": ["...", "@parcel/transformer-svg-react"]
  },
  "validators": {
    "*.js": ["@parcel/validator-eslint"]
  }
}
```
babel config from package.json

```
  "babel": {
    "presets": [
      "@babel/preset-react"
    ],
    "plugins": [
      [
        "babel-plugin-styled-components"
      ]
    ]
  }
```

## 🤔 Expected Behavior

validator-eslint should treat a glob pattern as a pattern and not a literal file name

## 😯 Current Behavior

validator-eslint treats glob patterns as file names and displays an error

```
$ rimraf dist .parcel-cache && parcel
Server running at http://localhost:1234
🚨 Build failed.

Error: ENOENT: no such file or directory, stat 
'/home/.../frontend/src/modules/**/*.js'
```

## 💁 Possible Solution

Ignore file paths which contain asterisks. 

```diff
diff --git a/node_modules/@parcel/core/lib/Validation.js b/node_modules/@parcel/core/lib/Validation.js
index 3b30bb3..372a6b2 100644
--- a/node_modules/@parcel/core/lib/Validation.js
+++ b/node_modules/@parcel/core/lib/Validation.js
@@ -147,6 +147,10 @@ class Validation {
   async buildAssetsAndValidators() {
     // Figure out what validators need to be run, and group the assets by the relevant validators.
     await Promise.all(this.requests.map(async request => {
+      // Ignore glob patterns
+      if (request['filePath'].includes('*'))
+        return
+
       this.report({
         type: 'validation',
         filePath: (0, _projectPath.fromProjectPath)(this.options.projectRoot, request.filePath)
diff --git a/node_modules/@parcel/core/src/Validation.js b/node_modules/@parcel/core/src/Validation.js
index 3dcdcbc..d34aac8 100644
--- a/node_modules/@parcel/core/src/Validation.js
+++ b/node_modules/@parcel/core/src/Validation.js
@@ -135,6 +135,10 @@ export default class Validation {
     // Figure out what validators need to be run, and group the assets by the relevant validators.
     await Promise.all(
       this.requests.map(async request => {
+        // Ignore glob patterns
+        if (request['filePath'].includes('*'))
+          return
+
         this.report({
           type: 'validation',
           filePath: fromProjectPath(this.options.projectRoot, request.filePath),
```

## 🔦 Context

It pops up constantly as the first error during development with HMR and building production builds.

## 💻 Code Sample

Having any glob import and validator-eslint causes this error.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.1
| Node             | 18.3.0
| npm/Yarn         | 1.22.19
| Operating System | Arch Linux 5.18.1-arch1-1

**Comment by mehdisadeghi** [comment]
iirc it is not resolved yet, but I do have a workaroung in place (patching parcel) so I'll ignore stale bot's future notices and let this be closed if no one else cares about this.

**Comment by mischnic** [comment]
This really boils down to whether files generated by Parcel (such as this virtual module for glob dependencies) should be checked by eslint. And I guess the answer here is no because this is just useless:
```
@parcel/validator-eslint: ESLint found 3 errors and 0 warnings.

  src/v-*.js:1:16
  > 1 | const _temp0 = require("./v-1.js");
  >   |                ^^^^^^^^ 'require' is not defined.
  > 2 | const _temp1 = require("./v-2.js");
  >   |                ^^^^^^^^ 'require' is not defined.
  > 3 | module.exports = {
  >   | ^^^^^^^ 'module' is not defined.
    4 |   "1": _temp0,
    5 |   "2": _temp1
```

But then there's currently no way to tell whether an asset was created by a user or not (apart from checking whether an asset exists on disk at that location). The whole validation plugin system is problematic for this reason...
