### ISSUE TITLE
Outputting multiple source files to their own dist file.

### ISSUE THREAD

**Issue by ConduciveMammal** [parcel-bundler/parcel#8241]
# 🐛 bug report

For my project, part of a Shopify theme, I've built a `quiz.js` React file and `quiz-results.js` React file.
Previously in V1, I was able to build these files into their own `quiz.min.js` and `quiz-results.min.js` file but I can't seem to do this anymore! V1 had this feature perfect, I don't understand why it was removed?

Reading the docs, it mentions having to use `"main"` in my package.json, but this only allows for one file, not multiple, so I'm wondering if I've missed something?

## 🎛 Configuration (.babelrc, package.json, cli command)
Relevant package.json commands I previously used:
```
"quiz:build": "parcel build src/quiz/quiz.js -o quiz.min.js --dist-dir src/theme/assets/",
"quiz:watch": "parcel watch src/quiz/quiz.js --dist-dir src/theme/assets/ --hmr-port 56884",
"results:build": "parcel build src/results/results.js --dist-dir src/theme/assets/",
"results:watch": "parcel watch src/results/results.js --dist-dir src/theme/assets/",
```

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.1
| Node             | 14.18.0
| npm/Yarn         |  Yarn 1.22.19
| Operating System | macOS Montery

**Comment by ConduciveMammal** [comment]
Bump

**Comment by devongovett** [comment]
You can define multiple targets https://parceljs.org/features/targets/#multiple-targets

**Comment by damianobarbati** [comment]
@devongovett is this possible from cli somehow?

Example:
```sh
parcel 
   app/user/index.html --dist-dir dist/user
   app/admin/index.html --dist-dir dist/admin/
```
