### ISSUE TITLE
parcel build is different from parcel. And using parcel run server does not output esmodule file.

### ISSUE THREAD

**Issue by XiaofanLinUS** [parcel-bundler/parcel#8248]
# 🐛 bug report

I try to use top-level async but it needs to be a type module for it to work. I get around it by trying to output index.html having javascript run as the type module. The output from the command "parcel build" did generate the code for me but when I tried to run the live server through the command "parcel" the codes fall back to non-module type. How can I run a live server only on the codes output from build instead of regular parcel command? Some times, I have to repeat the command to get it to work. Sometimes, it doesn't work at all.

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json:
```
{
  "outputFormat": "esmodule",
  "source": "src/index.html",
  "includeNodeModules": true,
  "dependencies": {
    "gl-matrix": "^3.4.3",
    "lodash": "^4.17.21",
    "ts-node": "^10.8.1",
    "typescript": "^4.7.3"
  },
  "devDependencies": {
    "@parcel/resolver-glob": "^2.6.2",
    "@parcel/transformer-inline-string": "^2.6.2",
    "@parcel/transformer-typescript-tsc": "^2.6.2",
    "parcel": "^2.6.2"
  },
  "scripts": {
    "start": "parcel",
    "build": "parcel build",
    "check": "tsc --noEmit"
  }
}
```

## 🤔 Expected Behavior

Top-level-await works sometimes but doesn't work some other times.

## 😯 Current Behavior

```
Uncaught ReferenceError: await is not defined
    at 8QSpP../ObjectParser (Main.ts:45:13)
    at newRequire (index.d798abb8.js:71:24)
    at index.d798abb8.js:122:5
    at index.d798abb8.js:145:3
```

## 💁 Possible Solution

I don't know.

## 🔦 Context

I am using await to load texture as well as object file for CG rendering. Top-level-await simplifies my codes a lot by simulating synchronous function call.

## 💻 Code Sample

Github repo:
https://github.com/XiaofanLinUS/js_render_engine

## 🌍 Your Environment

Mac OS on M1

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.6.2
| Node             | 18.3.0
| npm/Yarn         | 8.11.0
| Operating System | Monterey 12.4

**Comment by mischnic** [comment]
Top level await is not supported yet: https://github.com/parcel-bundler/parcel/issues/4028
