### ISSUE TITLE
In some cases, the packaged files are decoded using the atob function for base64, resulting in Chinese garbled code.

### ISSUE THREAD

**Issue by Ar3h** [parcel-bundler/parcel#8250]
# 🐛 bug report

The atob() function does not support Chinese, which will lead to Chinese garbled code, and the packaged file uses the atob function.

---

When packaged using parcel, one of the data.js files is packaged in base64 form, which looks roughly like
<img width="669" alt="image" src="https://user-images.githubusercontent.com/46180221/175615332-d5a966e8-f3a4-45a5-b4a7-4beb74f5961f.png">

And this data.js file has Chinese in it
<img width="511" alt="image" src="https://user-images.githubusercontent.com/46180221/175616395-97a2b96c-355f-4f2e-9186-390ce4e0f0ce.png">

After visiting the web page generated by parcel, I found that the Chinese code is messed up
<img width="670" alt="image" src="https://user-images.githubusercontent.com/46180221/175614841-1ab899ae-9114-4144-9904-5234fa72afcf.png">

------------------------------

Description of the Chinese mess caused by atob().
`123abc中文` base64 is `MTIzYWJj5Lit5paH`

Decoding with the atob function results in garbled code.

<img width="205" alt="image" src="https://user-images.githubusercontent.com/46180221/175616149-fff4af43-663e-462b-9486-13c4f7279cd2.png">

## 🎛 Configuration (.babelrc, package.json, cli command)

`npm run build`

package.json
```js
{
  "source": "index.html",
  "scripts": {
    "build": "rm -rf ./dist && ./node_modules/.bin/parcel build"
  },
  "targets": {
    "default": {
      "sourceMap": false
    }
  },
  "devDependencies": {
    "parcel": "2.3.2",
    "parcel-transformer-obfuscation": "file:parcel-transformer-obfuscation"
  },
  "resolutions": {
	  "bin-wrapper": "npm:bin-wrapper-china"
  }
}
```

.parcelrc
```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    // Leave jQuery/Bootstrap assets as-is, as they're already minified
    "*jquery-3.5.1.slim.min.js": [],
    "*bootstrap-4.5.2.min.js": [],

    // Additionally 'obfuscate' files which may contain shell references
    "*data.js": [
        "...",
        "parcel-transformer-obfuscation"
    ]
  }
}

```

## 🤔 Expected Behavior

Normal display of Chinese

## 😯 Current Behavior

Chinese display is not normal

## 💁 Possible Solution

Use other base64 decoding functions

## 💻 Code Sample
Use a simple environment to simulate the situation of using parcel to package and then use the atob function to decode the messy Chinese code

index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="chineseTest.js"></script>
</head>
<body>
<script>
    console.log(CodeTest)
</script>
</body>
</html>
```

chineseTest.js
```js
Function(atob("Y29uc3QgQ29kZVRlc3QgPSB7CiAgICAnbnVtYmVyJzogJzEyMycsCiAgICAnY2hpbmVzZSc6ICfkuK3mlocnCn07Ci8vIEV4cG9ydCB0aGUgZGF0YSBmb3IgdXNlIHdpdGhpbiBuZXRsaWZ5IGZ1bmN0aW9ucyAvIG5vZGUKaWYgKHR5cGVvZiBleHBvcnRzICE9PSAndW5kZWZpbmVkJykgewogICAgZXhwb3J0cy5Db2RlVGVzdCA9IENvZGVUZXN0Owp9CgppZiAodHlwZW9mIHdpbmRvdyAhPT0gJ3VuZGVmaW5lZCcpIHsKICAgIHdpbmRvdy5Db2RlVGVzdCA9IENvZGVUZXN0Owp9Cg=="))();
```
<img width="420" alt="image" src="https://user-images.githubusercontent.com/46180221/175618659-1255af3c-ce8b-4a59-9fca-c0efc7c97f28.png">

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.3.2
| Node             |v17.7.2
| npm/Yarn         |8.5.2
| Operating System |MacOSX 11.6.6

**Comment by mischnic** [comment]
This is caused by `parcel-transformer-obfuscation`, not Parcel itself.
