### ISSUE TITLE
WGSL support

### ISSUE THREAD

**Issue by cancoel** [parcel-bundler/parcel#8256]
I really need a WGSL support for the shader import functionality.

**Comment by 101arrowz** [comment]
For now you can just:

```js
import { readFileSync } from 'fs';
const shaderCode = readFileSync('./shader.wgsl', 'utf8');
```

Even though `fs` is a Node module, Parcel knows to inline the contents of `shader.wgsl` into your browser build.

**Comment by cancoel** [comment]
> For now you can just:
> 
> ```js
> import { readFileSync } from 'fs';
> const shaderCode = readFileSync('./shader.wgsl', 'utf8');
> ```
> 
> Even though `fs` is a Node module, Parcel knows to inline the contents of `shader.wgsl` into your browser build.

I tried this and I'm getting 
> Uncaught TypeError: fs_1.default.readFileSync is not a function

**Comment by mischnic** [comment]
You need 
```js
import fs from "fs";
import path from "path";

const data = fs.readFileSync(path.join(__dirname, "data.json"), "utf8");
console.log(data);
```
https://parceljs.org/features/node-emulation/#inlining-fs.readfilesync

**Comment by cancoel** [comment]
> You need
> 
> ```js
> import fs from "fs";
> import path from "path";
> 
> const data = fs.readFileSync(path.join(__dirname, "data.json"), "utf8");
> console.log(data);
> ```
> 
> https://parceljs.org/features/node-emulation/#inlining-fs.readfilesync

Thank you for your reply.
I tried this and it's still not working.

> const shaderCode = fs.readFileSync(path.join('./src/shaders/', "invert_colors.wgsl"));

I am using it in my Shader Module like that:

>  const shaderModule = device?.createShaderModule({code: shaderCode })

**Comment by mischnic** [comment]
You're still missing the `__dirname` part, and the utf8

**Comment by cancoel** [comment]
> ./src/shaders/

You're right, I missed "utf8" and corrected it and ./src/shaders/ is the directory where my .wgsl file is located.

I think it's not working because fs isn't working via browser, only within node.

**Comment by devongovett** [comment]
An alternative is to use the `bundle-text:` pipeline for this:

```js
import text from 'bundle-text:./shader.wgsl';
// text is a string
```

See the docs here for more details: https://parceljs.org/features/bundle-inlining/
