### ISSUE TITLE
Downloading the '.env' file does not work (Sandbox)

### ISSUE THREAD

**Issue by khusamov** [parcel-bundler/parcel#8258]
# 🐛 bug report

Downloading the '.env' file does not work

## 🎛 Configuration 

```js
{
  "name": "parcel-env",
  "version": "1.0.0",
  "description": "",
  "main": "index.html",
  "scripts": {
    "start": "parcel index.html --open",
    "build": "parcel build index.html"
  },
  "dependencies": {
    "@types/node": "17.0.45",
    "parcel": "2.6.2",
    "parcel-bundler": "^1.6.1"
  },
  "devDependencies": {
    "typescript": "4.4.4"
  },
  "resolutions": {
    "@babel/preset-env": "7.13.8"
  },
  "keywords": []
}
```

## 🤔 Expected Behavior

Test value

## 😯 Current Behavior

undefined

## 💻 Code Sample

Sandbox:

https://codesandbox.io/s/parcel-env-m3h5m3?file=/src/index.ts

```typescript
const app = document.getElementById('app');
if (app) {
	app.innerHTML =
		process.env['MYVARIABLE'] === undefined
			? 'undefined'
			: process.env['MYVARIABLE'];
}
```

```
MYVARIABLE = "Test value"
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.2
| Node             | v16.14.0
| Yarn             | 3.2.0
| Operating System | MacOS

**Comment by mischnic** [comment]
I don't know what you mean by "downloading".
Also, Codesandbox doesn't actually use Parcel for bundling

**Comment by khusamov** [comment]
@mischnic Environment variables are not available in the code. Undefined is output instead of the variable value. And I expect the value of the variable from the .env file

How do I make this functionality work?

**Comment by khusamov** [comment]
I do according to the instructions as written on the page https://parceljs.org/features/node-emulation/#.env-files

APP_NAME returns undefined, although in the file.env the value "test" is written

**Comment by mischnic** [comment]
Here's an example: https://github.com/mischnic/parcel-issue-8258

**Comment by khusamov** [comment]
@mischnic Thanks for the answer! I understood why it doesn't work. I use yarn workspaces. And in this case the file .env does not work. Undefined is output instead of variable values.

I have prepared a repository where this error is reproduced.

https://github.com/khusamov/temp-parcel-issue-8258

**Comment by mischnic** [comment]
See https://github.com/parcel-bundler/parcel/issues/4110
