### ISSUE TITLE
bug: replaced script.js compiles only once

### ISSUE THREAD

**Issue by 11111000000** [parcel-bundler/parcel#826]
:thinking: Expected Behavior

When I replace script.js, - dev server updates every time

:hushed:  Current Behavior

When I replace script.js, - dev server updates only once

**Comment by 11111000000** [comment]
maybe this is related with https://github.com/parcel-bundler/parcel/issues/221 , but for out case - org mode tangle we can't "disable" anything to avoid file replacement...

**Comment by 11111000000** [comment]
maybe it's related to https://github.com/parcel-bundler/parcel/issues/754 too

**Comment by mischnic** [comment]
Which parcel version are you using ? How did you invoke parcel?
Is "script.js" your main script or is it imported somewhere else?

**Comment by 11111000000** [comment]
anyone can simply reproduce that on lastest parcel. 
script.js is main script
imported scripts also not works  :disappointed:

**Comment by 11111000000** [comment]
to test it I use simple Emacs Org Mode file, export it with **<C-x><C-e>hh** and tangle with **<C-c><C-v>t**:

```
#+HTML_HEAD: <script type="text/javascript" src="script.js"></script>
#+HTML_HEAD: <link href="style.css" rel="stylesheet">

#+BEGIN_SRC javascript :tangle style.css
body {
   background: black;
   color: white;
}
#+END_SRC

#+BEGIN_SRC rjsx :tangle script.js
console.log('ok1')
#+END_SRC

```

**Comment by DeMoorJasper** [comment]
This is related to #221

**Comment by 11111000000** [comment]
browserify + budo (i.e. watchify) also works
