### ISSUE TITLE
Can't do nested lazy import in react

### ISSUE THREAD

**Issue by dioptre** [parcel-bundler/parcel#8261]
# 🐛 bug report

I cant do something like:

```
const Documentation = lazy(() => import('./components/Documentation'));
```
then inside Documentation do:
```
const Chapter1 = lazy(() => import('./components/Chapter1'));
```

## 🤔 Expected Behavior

Should work

## 😯 Current Behavior

Errors out.

## 💁 Possible Solution

Hacky workaround is to use an import, stops the code splitting from working though.

## 🔦 Context

I want to use a nested route with a large site.

## 💻 Code Sample
as above
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.2
| Node             | 17.1
| npm/Yarn         | 3.2.1
| Operating System | Mac

**Comment by mischnic** [comment]
Please provide a reproduction. And also just saying "Errors out." without the actual error message isn't very helpful

**Comment by dioptre** [comment]
@mischnic do you use an online debugger for cases like this? I’m happy to replicate on a sandbox tool. Just so trivial to replicate I thought you would manage. But guess you guys must be swamped atm.

**Comment by mischnic** [comment]
I haven't tried it yet, but TBH it's rather often some small (unrelated) detail that triggers a reported bug.

And if you post the error, we can sometimes make educated guesses without even debugging it locally

Always swamped 😶😄
