### ISSUE TITLE
disable prefetch

### ISSUE THREAD

**Issue by RGdevz** [parcel-bundler/parcel#8265]
# 🙋 feature request
I use vue router and when I go to route parcel is adding many unnecessary prefetching links in the html <head> to others routes that I don't want to prefetch

## 🤔 Expected Behavior

have option disable prefetch?

## 😯 Current Behavior

parcel don't have option to disable prefetch

## 💁 Possible Solution

add option to disable  prefetch?

## 💻 Examples

 use vue router and set paths like this

`  {path: '/index', component: () => import('./pages/page1.vue')} `

 `   path: '/page', component: () => import('./pages/page2.vue')} `

when you go to `index` route parcel will add prefetch to `page` route

**Comment by mischnic** [comment]
Is this really caused by Parcel? I think you can set a flag to disable it in the vue router options: https://github.com/egoist/vue-router-prefetch#prefetch

**Comment by RGdevz** [comment]
hey mischnic thanks for helping out, what you sent is other npm package that is not part of the vue router and I don't use, I also check with other bundlers and with them there was no prefetch issue.

I tried to track the root of that and its look like this code is adding the prefetching [https://github.com/parcel-bundler/parcel/blob/6719204a36a378506908f862a6b70e24cbfaa1fc/packages/runtimes/js/src/helpers/browser/prefetch-loader.js](https://github.com/parcel-bundler/parcel/blob/6719204a36a378506908f862a6b70e24cbfaa1fc/packages/runtimes/js/src/helpers/browser/prefetch-loader.js)

**Comment by mischnic** [comment]
That is only used though if you do something like this:
https://github.com/parcel-bundler/parcel/blob/3baf990a686d1c1dd0c5f4360296de890cc00c47/packages/core/integration-tests/test/integration/dynamic-static-prefetch/async.js#L1-L3

**Comment by RGdevz** [comment]
Well I don't that what my router look like `
    


    routes: [

    { path: '/', component: hello },

     { path: '/test', component: () => import('./pages/testpage.vue') },

    { path: '/game', component: () => import('./pages/tests_map.vue') },
    { path: '/editor', component: () => import('./pages/Editor.vue') },
    {path: '/disconnected' , component: Disconnected},

**Comment by RGdevz** [comment]
I use `-no-scope-hoist` if that maybe matter

**Comment by RGdevz** [comment]
I checked again and this is the code that cause it to add prefetch [https://github.com/parcel-bundler/parcel/blob/c3940191602a3a5f56bfd4fe35ef990163870c41/packages/runtimes/js/src/helpers/browser/js-loader.js](https://github.com/parcel-bundler/parcel/blob/c3940191602a3a5f56bfd4fe35ef990163870c41/packages/runtimes/js/src/helpers/browser/js-loader.js)

edit: Also seems the problem is not prefetch but preload

**Comment by RGdevz** [comment]
I made repo so you can see the issue [https://github.com/RGdevz/test](https://github.com/RGdevz/test), when you go to testpage2 you will see it adding preload tag to testpage. It only happens when I use components in the page

**Comment by mischnic** [comment]
There are two output bundles which have "testpage" in their name. 
One of them is the actual testpage (1), and the other one is the loading component that is shared between the two pages. There are the bundles I that load:

```
Opening page 1:

http://localhost:3000/index.00893a6a.js     <-- main bundle
http://localhost:3000/testpage.1644d2f8.js  <-- contains loading.vue
http://localhost:3000/testpage.d9a8ad31.js  <-- contains testpage.vue

Opening page 2:

http://localhost:3000/index.00893a6a.js     <-- main bundle
http://localhost:3000/testpage.1644d2f8.js  <-- contains loading.vue
http://localhost:3000/testpage2.4c120350.js <-- contains testpage2.vue
```
