### ISSUE TITLE
`Uncaught ReferenceError: e is not defined` error when bundling auth0-js package

### ISSUE THREAD

**Issue by louh** [parcel-bundler/parcel#8277]
# 🐛 bug report

When importing from the `auth0-js` package, the following error appears in console:

```
Uncaught ReferenceError: e is not defined
    ["1PhJE"]< idtoken-verifier.esm.js:1
    newRequire index.0641b553.js:71
    localRequire index.0641b553.js:84
    bNKaB app.js:1
    newRequire index.0641b553.js:71
    <anonymous> index.0641b553.js:122
    <anonymous> index.0641b553.js:145
```

In my real-world use case, which uses Parcel's programmatic API to bundle the application inside of an Express app, the error also overlays the app like so:

<img width="1463" alt="Screen Shot 2022-07-03 at 10 22 39 AM" src="https://user-images.githubusercontent.com/2553268/177046899-77dc89b4-7189-4635-84a7-8bc65fad5aca.png">

## 🎛 Configuration (.babelrc, package.json, cli command)

I can recreate the error using a very minimal Parcel app. See link to minimal repro below.

## 🤔 Expected Behavior

Import should not mangle variables.

## 😯 Current Behavior

The source file, `idtoken-verifier.esm.js` (located in the `idtoken-verifier` dependency of `auth0-js`) has this following snippet (reformatted for readability):

```js
function e (t) {
  const e = { exports: {} }
  return t(e, e.exports), e.exports
}
const r = e(function (e, r) {
  [... rest of function snipped ...]
})
```

Note where `const r` runs `e()`, which is defined just above `r`.

In the Parcel bundle, the same snippet is now:

```js
function e8(t1) {
    var e7 = {
        exports: {}
    };
    return t1(e7, e7.exports), e7.exports;
}
var r = e(function(e9, r1) {
  [... rest of function snipped ...]
})
```

The line at `var r` calls `e`, which is not defined (raising the error), and it is not defined because the previous function has been renamed `e8`. Something is causing the original function to be renamed, but the calling function is not updated to refer to the renamed function.

## 💁 Possible Solution

Unknown.

## 🔦 Context

We're upgrading our application from Parcel v1 to Parcel v2. Our application worked fine in Parcel v1, but we also don't want to lock ourselves into an older and unmaintained version. As the JavaScript ecosystem evolves we are also updating our infrastructure. However, this issue blocks our ability to upgrade.

The Auth0-js package is part of our application to connect to Auth0, a user account login provider. It's a necessary part of our application. Without a workaround for building this package, we cannot update to Parcel v2.

## 💻 Code Sample

I have created a minimal reproduction of this issue using vanilla Parcel and no other frameworks. Please see this repository: https://github.com/streetmix/parcel-auth0-error

```
git clone https://github.com/streetmix/parcel-auth0-error.git
cd parcel-auth0-error
npm install
npx parcel src/index.html    
```

This creates a minimal page whose JavaScript bundle only imports a method from `auth0-js`. The error exists regardless of whether it's a minimal use case or a large application.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.6.2
| Node             | 18.4.0
| npm         |  8.12.1
| Operating System | MacOSX 12.4

Thank you!

**Comment by mountainash** [comment]
@louh Did this fix the issue for you? I'm running the latest version of parcel@2.6.2 (released with the SWC bump) but are also having the exact same error.
