### ISSUE TITLE
"Error: Bundles must have unique names" on assets imported through multiple code paths

### ISSUE THREAD

**Issue by leaumar** [parcel-bundler/parcel#8278]
# 🐛 bug report

I have a single .ts file defining some of my static images. This .ts file is imported by 2 different entrypoints (e.g. background.ts and content.ts), and this causes the "duplicate name" error. When I remove the _1_ reference to an asset listed here, the size of `bundleNames` in the check shrinks by _2_. I cannot make parcel include this asset in any other way than a cli entry and non-interpreted import.

## 🎛 Configuration (.babelrc, package.json, cli command)

There's a lot of configuration involved that could or could not be relevant, please check repro [in my later post](https://github.com/parcel-bundler/parcel/issues/8278#issuecomment-1416796154)

## 🤔 Expected Behavior

The same asset being referenced from different code paths shouldn't throw a duplicate resource name error.

## 😯 Current Behavior

- 2 entrypoints importing the same .ts file that references an asset by `new URL('foo.png', import.meta.url)` cause a naming conflict

## 💁 Possible Solution

Since I've only ever seen project-root-relative file paths in the bundleNames, can't parcel safely assume duplicates are effectively just the same file and stop throwing an error on this? That's been the case every time so far for me anyway.
This would
- fix this particular error case, albeit not by preventing the duplicate path to begin with
- allow me to keep (or rather, go back to) forcing my dist folder and root file structure to be the same as the source, and make the hashless-renamer unnecessary, by promoting some assets to entrypoints (images get hoisted out of /images, and css/js files imported by html can't be entrypoints)

Otherwise, at least imports at different levels resolving to the same file should be better detected.

## 🔦 Context

I have some assets (.png) used by my webextension. Recent parcel versions force me to check that my `build` cli globs don't overlap with any references to the same files that parcel recognizes in the code (mainly manifest.json). Really annoying, but I eventually found in the docs you can use URL detection in javascript to at least make this safe for assets you can refer to statically, leaving cli globs and non-parcel-resolved imports only for dynamic imports like `flag-${countryCode}.png`.

## 💻 Code Sample

edit: [minimal repro](https://github.com/parcel-bundler/parcel/files/10609092/bug-8278.zip) in post 8 

https://gitlab.com/Marnes-group/webextensions/-/tree/fix/icons

`nvs use` or equivalent (.node-version file)
`yarn install`
`cd extensions/doubleclick-image-downloader`
`yarn parcel:build`
Check the bundleNames in the check that throws the error: it contains error-128.png and icon-128.png (and some others that most likely have the same causes) twice each. error-128.png is **only** referenced from a single place, `src/common/images.ts` (which is imported by both background.ts and content.ts, 2 entrypoints). icon-128.png is referenced from manifest.json and the same ts file. I would have expected it to be in bundleNames _3_ times (manifest.json + double count from .ts entrypoints) but for some reason it isn't, so my interpretation of the cause might be off.

If this repro is too "noisy"/large and you'd prefer it trimmed down, let me know and I'll try to make a more minimal repro.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.2
| Node             | 16.15.1
| npm/Yarn         | 3.2.1
| Operating System | win10

**Comment by leaumar** [comment]
To further support my suspicion about multiple entrypoints, I moved error128 and icon128 out of images.ts (the shared file) and into a file strictly used by 1 entry point (notifications.ts). The double bundlenames of those 2 images became 1 bundlename each, leaving only the other filenames from images.ts as doubles.

Further duplicating images.ts so each entrypoint can import its own copy instead of sharing a file, also leaves the duplicate bundlenames when building.

**Comment by leaumar** [comment]
[bug-8278.zip](https://github.com/parcel-bundler/parcel/files/9254838/bug-8278.zip)

This zip file ^ contains the most minimal repro possible. Aside from some obvious necessities like a package.json, it's just 3 .ts files and a .json. The shared ts declares the json url for parcel to process, and the other two files are entrypoints that import this shared asset url.

- `nvs use` (or your flavor of node tool, see .node-version)
- `yarn`
- `yarn build`

Result: `Error: Bundles must have unique names`

How else am I supposed to use a shared asset in more than 1 entrypoint? Nothing short of duplicating the file on disk to 2 paths works.

Edit: updated zip to have even less content

**Comment by mischnic** [comment]
The problem was that you had `"main": "index.js",` in package.json, but multiple entrypoints. And it tried to name each of them "index.js". We need a better error message here

**Comment by leaumar** [comment]
My project doesn't actually set any `"main"` value, not sure why that got into the repro, sorry. Lemme see if I can change that and still repro it.

**Comment by leaumar** [comment]
Ok, so, let me link to my [current wip git branch](https://gitlab.com/Marnes-group/webextensions/-/tree/fix/icons)

What I'm trying to do on this branch is use `new URL("./img.png", import.meta.url).pathname` (which I recently happened to read about) so that my images get bundled automatically by parcel, instead of globbing them in my scripts as entrypoints and referring to them at runtime by an independent string.

I have multiple entrypoints (options/content/background/popup) and they can want to load the exact same images. Apparently this makes parcel generate _multiple_ bundleNames with a _different_ hash for the _same single_ resource by the time this check is done:
![image](https://user-images.githubusercontent.com/3950300/216675811-d7faf63f-122c-4bc0-8950-258f01abe2ec.png)

Letting the build continue, these redundancies are flattened and only a single file is written for each, with apparently a new hash again:
![image](https://user-images.githubusercontent.com/3950300/216675918-91025fe4-73e1-436d-b153-c6442ced6fbb.png)

However, I use parcel-namer-hashless for reasons, so I get the error that there are name collisions:
![image](https://user-images.githubusercontent.com/3950300/216676325-8ca45ca1-f286-4b2f-98d2-e73c4317af46.png)

The reason I opened this ticket is that this seems a false error to me. There are no bundle name collisions here, parcel is just unnecessarily adding duplicate bundle names for the same single file because it's loaded through different paths. It's even smart enough already to know _after this error check_ that they actually concern the same file and can be deduplicated, as the 22 bundle names (of which 6+6 are dupes) become 16 bundles.

Could this error check be smartened-up to understand the same-file-deduped outcome instead of failing on a non-problem and forbidding the same asset from being loaded in multiple entrypoints under hashless naming?

**Comment by leaumar** [comment]
I'm trying to make a minimal repro by adding hashless naming to the zip I provided, but so far it just works with 2 entrypoints loading the same image. I'm not sure yet what's so different in my real project.

**Comment by leaumar** [comment]
It seems this only happens with webextensions. I had to add a manifest.json referring to the same asset through different paths and the webextension config for this error to start happening. New minimal repro zip: [bug-8278.zip](https://github.com/parcel-bundler/parcel/files/10609092/bug-8278.zip)

It builds a manifest.json that refers to two entrypoints (bg and fg), both of which load a shared ts that imports a shared png.

If you run `yarn build` as-is, you'll get the bundleNames error. Remove the `content_scripts` section from manifest.json (so that fg is no longer bundled) and the error goes away.

**Comment by gxy5202** [comment]
> I'm trying to make a minimal repro by adding hashless naming to the zip I provided, but so far it just works with 2 entrypoints loading the same image. I'm not sure yet what's so different in my real project.

hi, I'm the author of parcel-namer-hashless, you can try v1.0.6.
