### ISSUE TITLE
Dynamic pages from JSON

### ISSUE THREAD

**Issue by ivoba** [parcel-bundler/parcel#8279]
# 🙋 feature request
Dynamic pages from JSON files with a common template.
Similar like createPages on nodes in Gatsby.

## 🤔 Expected Behavior
I load JSON data with posthtml-fetch and render the values in HTML pages.
Now i would like to create detail pages for each of the items when the link contains a certain trigger:
`<a href="{{link}}" make-page>detail</a>` 

Problem here is to create the pages and then let parcel follow all asset links inside the page.
How can this work?

The Pug transformer also creates HTML pages before processing them.
So there could be a way already.
Do you have an idea for this?

## 💻 Examples

Gatsby does this with the dynamicPages API: https://www.gatsbyjs.com/docs/reference/config-files/gatsby-node/#createPages

**Comment by mischnic** [comment]
Assets are detected in the output of the preceding posthtml plugin step. So what you describe should just work (= posthtml plugins insert references to other files). 

Do you have a code sample of something that you think should be working but isn't?
