### ISSUE TITLE
Incorrect code produced with ternaries, imported function calls, and ternaries

### ISSUE THREAD

**Issue by marcins** [parcel-bundler/parcel#8281]
# 🐛 bug report

Code like this produces incorrect output:

```
import { a, b } from "./foo";

const c = a() ? undefined : b?.();
```

A bisect shows that this is related to the change in #7956.

The optional chaining is relevant, as without it in the Repl correct output is produced (without optimisation that would potentially simplify the code further).

## 🤔 Expected Behavior

Code is bundled correctly, the right hand side of the ternary should be wrapped in parens:
`const c = (0, a)() ? undefined : (0, b)?.();`

## 😯 Current Behavior

The bundler outputs:

`const c = (0, a)() ? undefined : 0, b?.();`

Code on right hand side of ternary is not wrapped, which changes the behaviour.

This manifests itself initially at build time as a Terser parsing error "Missing initializer in const declaration", because it the resulting JS tries to re-initialise `b`.

As per above, without the optional chaining in the Parcel repl the output is `const c = (0, a)() ? undefined : (0, b)();`

## 💻 Code Sample

[Repro in repl](https://parcel2-repl-mischnic.vercel.app/#JTdCJTIyZmlsZXMlMjIlM0ElNUIlNUIlMjIlMkZzcmMlMkZpbmRleC5qcyUyMiUyQyU3QiUyMnZhbHVlJTIyJTNBJTIyaW1wb3J0JTIwJTdCYSUyQyUyMGIlN0QlMjBmcm9tJTIwJy4lMkZvdGhlciclM0IlNUNuJTVDbmNvbnN0JTIwZm9vJTIwJTNEJTIwYSgpJTIwJTNGJTIwdW5kZWZpbmVkJTIwJTNBJTIwYiUzRi4oKSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTVCJTIyJTJGc3JjJTJGb3RoZXIuanMlMjIlMkMlN0IlMjJ2YWx1ZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwYSUyMCUzRCUyMCgpJTIwJTNEJTNFJTIwZmFsc2UlM0IlNUNuZXhwb3J0JTIwY29uc3QlMjBiJTIwJTNEJTIwKCklMjAlM0QlM0UlMjAlNUMlMjJiJTVDJTIyJTNCJTIyJTdEJTVEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmVudHJpZXMlMjIlM0ElNUIlNUQlMkMlMjJtaW5pZnklMjIlM0FmYWxzZSUyQyUyMnNjb3BlSG9pc3QlMjIlM0F0cnVlJTJDJTIyc291cmNlTWFwcyUyMiUzQWZhbHNlJTJDJTIycHVibGljVXJsJTIyJTNBJTIyJTJGX19yZXBsX2Rpc3QlMjIlMkMlMjJ0YXJnZXRUeXBlJTIyJTNBJTIyYnJvd3NlcnMlMjIlMkMlMjJ0YXJnZXRFbnYlMjIlM0ElMjJDaHJvbWUlMjA5MCUyMiUyQyUyMm91dHB1dEZvcm1hdCUyMiUzQW51bGwlMkMlMjJobXIlMjIlM0FmYWxzZSUyQyUyMm1vZGUlMjIlM0ElMjJwcm9kdWN0aW9uJTIyJTJDJTIycmVuZGVyR3JhcGhzJTIyJTNBZmFsc2UlMkMlMjJ2aWV3U291cmNlbWFwcyUyMiUzQWZhbHNlJTJDJTIyZGVwZW5kZW5jaWVzJTIyJTNBJTVCJTVEJTJDJTIybnVtV29ya2VycyUyMiUzQTAlN0QlMkMlMjJ1c2VUYWJzJTIyJTNBZmFsc2UlMkMlMjJicm93c2VyQ29sbGFwc2VkJTIyJTNBJTVCJTVEJTJDJTIydmlld3MlMjIlM0ElNUIlMjIlMkZzcmMlMkZpbmRleC5qcyUyMiUyQyUyMiUyRnNyYyUyRm90aGVyLmpzJTIyJTJDJTIyT3B0aW9ucyUyMiU1RCUyQyUyMmN1cnJlbnRWaWV3JTIyJTNBMiU3RA==)

**Comment by mischnic** [comment]
Is a bug in swc: https://github.com/swc-project/swc/issues/5109
