### ISSUE TITLE
Parcel yarn start on docker not watching changes even with CHOKIDAR_USEPOLLING=true

### ISSUE THREAD

**Issue by djaffer** [parcel-bundler/parcel#8287]
I am using parcel on docker container with CHOKIDAR_USEPOLLING=true yarn start. The changes are not getting registered.

Package.json has  "start": "parcel src/index.html -p 3016 --hmr-port 3016",

**Comment by mischnic** [comment]
Parcel 2 doesn't use chokidar. See https://github.com/parcel-bundler/parcel/issues/7258

**Comment by djaffer** [comment]
well then how to get it work.
