### ISSUE TITLE
Tests combine with source code. 

### ISSUE THREAD

**Issue by seivan** [parcel-bundler/parcel#8291]
# 💬 RFC

How would one go about if I wanted to keep my unit tests together with my source but under a condition that gets tree shaken out on everything but `ENV == "tests"`

## 🔦 Context

Similar to how Rust does it. 

## 💻 Examples

```ts
// src/index.ts

// the implementation
export function add(...args: number[]) {
  return args.reduce((a, b) => a + b, 0)
}

// in-source test suites
if (import.meta.test) {
  const { it, expect } = import.meta.test
  it('add', () => {
    expect(add()).toBe(0)
    expect(add(1)).toBe(1)
    expect(add(1, 2, 3)).toBe(6)
  })
}
```

But for this to work. You need a way to tell Parcel & Jest which files include unit tests.
And it needs the ability (for TypeScript at least) to have a union type on `import.meta.test` to be `undefined | testAPIs`. 

Whatever portion of Parcel that sets up build time string replacement, would need to take something like .

```ts
if (NODE_ENV !== 'test') {
 buildTimeStringReplacement: {
   'import.meta.test': 'undefined',
 }
}
```
So it's `undefined` during anything other than 'test' environments. 

Example: https://vitest.dev/guide/in-source.html

**Comment by devongovett** [comment]
Should already work with `process.env.NODE_ENV === "test"`. Do we really need a new api for it or does that work for you?

**Comment by seivan** [comment]
That depends, is there something like pre-runner that could load up 
```import.meta.test``` with various modules (jest stuff, mocks, etc)? 

Yeah, I think its own API is necessary. So you aren't checking  `process.env.NODE_ENV === "test"`, you're checking if `import.meta.test` exists so you could further narrow its type. 

The type safety is nice, because before the condition, it's either `undefined` or not.
After the condition it will resolve to the correct type where you can pick and choose the stuff you want. 

Doing `process.env.NODE_ENV === "test"` is a lot more error prone, but also it can't help narrow down the type.

**Comment by seivan** [comment]
> Should already work with `process.env.NODE_ENV === "test"`. Do we really need a new api for it or does that work for you?

Also, I can't see on the docs how to actually do this. I am not sure if the responsibility lies with e.g Jest or Parcel. I think both have a part in this.

**Comment by devongovett** [comment]
Hmm, this might work:

```
if (process.env.NODE_ENV === "test" && import.meta.test) 
```
