### ISSUE TITLE
index.html changes does not reload browser

### ISSUE THREAD

**Issue by KatSick** [parcel-bundler/parcel#83]
When i change index.html it does not reload browser. Where this is configured ?

**Comment by thejameskyle** [comment]
Some relevant bits of code:

https://github.com/parcel-bundler/parcel/blob/4cc343b9bd866d3229925551f53d3f4f6d182ecf/src/Bundler.js#L401-L417

https://github.com/parcel-bundler/parcel/blob/4cc343b9bd866d3229925551f53d3f4f6d182ecf/src/HMRServer.js#L16-L37

https://github.com/parcel-bundler/parcel/blob/4cc343b9bd866d3229925551f53d3f4f6d182ecf/src/builtins/hmr-runtime.js#L19-L33

**Comment by Raathigesh** [comment]
Shall I take a look at this?

**Comment by KatSick** [comment]
@Raathigesh if you can. I also checking, but does not see the problem now

**Comment by albinotonnina** [comment]
this guy refreshes the page, in a webpack environment: 
[https://github.com/glenjamin/webpack-hot-middleware/issues/237#issuecomment-321553819](https://github.com/glenjamin/webpack-hot-middleware/issues/237#issuecomment-321553819)

**Comment by Raathigesh** [comment]
#90 works but not sure whether this is the way to go about this.

**Comment by thejameskyle** [comment]
Moving to #90
