### ISSUE TITLE
Invalid target passed to babel-preset-env for node ">= 6.0.0"

### ISSUE THREAD

**Issue by natew** [parcel-bundler/parcel#830]
**Choose one:** 🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc

```js
{
  "presets": ["env"]
}
```

running:

```
parcel --target=node
```

### 🤔 Expected Behavior

Should run a node app

### 😯 Current Behavior

Getting this error:

```
/Users/nw/projects/motion/orbit/apps/desktop/src/index.js: Invalid version passed for target "node": ">= 6.0.0". Versions must be in semver format (major.minor.patch)
    at /Users/nw/projects/motion/orbit/node_modules/.registry.npmjs.org/babel-preset-env/1.6.1/node_modules/babel-preset-env/lib/index.js:69:13
```

### 💁 Possible Solution

Seems like it's using `>=` rather than just passing in a node version, perhaps.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.1
| Node             | 9.2
| Operating System | High Sierra

**Comment by DeMoorJasper** [comment]
fixed by #827

**Comment by saada** [comment]
Are there any workarounds for this?

**Comment by DeMoorJasper** [comment]
Do you still have this bug on latest master branch version @saada ?

**Comment by saada** [comment]
Sorry @DeMoorJasper I'm using 1.6.1. I'll wait until the latest release comes out then

**Comment by lbguilherme** [comment]
Workaround is mentioned in #827
