### ISSUE TITLE
Invalid sourcemaps with template literal

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#8302]
After some heavy debugging I figured out.
If you are using Template literals (``) the source map is completely broken.

index.ts
```ts
 console.log("test1") // line 1 correct

let text = `
    1
    1
    1
    1
    1
    1
    `

console.log("test2") // this should be line 12, instead 17 in devtools

let test0
let test1

console.log("test3")  // this only woks because last line if you add more content it wont work
```

index.html
```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>
	</head>
	<body>
		<script src="./index.ts"></script>
	</body>
</html>
```

Devtools
![image](https://user-images.githubusercontent.com/33373714/178458786-4b75279a-4eff-4c23-9d5a-8212e36f7db9.png)

_Originally posted by @Levminer in https://github.com/parcel-bundler/parcel/issues/5815#issuecomment-1181540189_

**Comment by mischnic** [comment]
When using Windows line endings (cr + lf), [the sourcemaps are wrong](https://evanw.github.io/source-map-visualization/#MzM5AGNvbnNvbGUubG9nKCJ0ZXN0MSIpIC8vIGxpbmUgMSBjb3JyZWN0CjsKbGV0IHRleHQgPSBgDQogICAgMQ0KICAgIDENCiAgICAxDQogICAgMQ0KICAgIDENCiAgICAxDQogICAgYDsKY29uc29sZS5sb2coInRlc3QyIikgLy8gdGhpcyBzaG91bGQgYmUgbGluZSAxMiwgaW5zdGVhZCAxNyBpbiBkZXZ0b29scwo7CmxldCB0ZXN0MDsKbGV0IHRlc3QxOwpjb25zb2xlLmxvZygidGVzdDMiKSAvLyB0aGlzIG9ubHkgd29rcyBiZWNhdXNlIGxhc3QgbGluZSBpZiB5b3UgYWRkIG1vcmUgY29udGVudCBpdCB3b250IHdvcmsKOwoKLy8jIHNvdXJjZU1hcHBpbmdVUkw9aW5kZXguZDJlMGE0MmEuanMubWFwCjY2MgB7Im1hcHBpbmdzIjoiQUFBQyxPQUFPLENBQUMsR0FBRyxDQUFDLE9BQU8sQ0FBQyxDQUFDLGlCQUFpQjs7QUFFdkMsSUFBSSxJQUFJLEdBQUcsQ0FBQyxnREFPUixDQUFDO0FBRUwsT0FBTyxDQUFDLEdBQUcsQ0FBQyxPQUFPLENBQUMsQ0FBQyxpREFBaUQ7O0FBRXRFLElBQUksS0FBSztBQUNULElBQUksS0FBSztBQUVULE9BQU8sQ0FBQyxHQUFHLENBQUMsT0FBTyxDQUFDLENBQUUsd0VBQXdFIiwic291cmNlcyI6WyJpbmRleC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgY29uc29sZS5sb2coXCJ0ZXN0MVwiKSAvLyBsaW5lIDEgY29ycmVjdFxyXG5cclxubGV0IHRleHQgPSBgXHJcbiAgICAxXHJcbiAgICAxXHJcbiAgICAxXHJcbiAgICAxXHJcbiAgICAxXHJcbiAgICAxXHJcbiAgICBgXHJcblxyXG5jb25zb2xlLmxvZyhcInRlc3QyXCIpIC8vIHRoaXMgc2hvdWxkIGJlIGxpbmUgMTIsIGluc3RlYWQgMTcgaW4gZGV2dG9vbHNcclxuXHJcbmxldCB0ZXN0MFxyXG5sZXQgdGVzdDFcclxuXHJcbmNvbnNvbGUubG9nKFwidGVzdDNcIikgIC8vIHRoaXMgb25seSB3b2tzIGJlY2F1c2UgbGFzdCBsaW5lIGlmIHlvdSBhZGQgbW9yZSBjb250ZW50IGl0IHdvbnQgd29yayJdLCJuYW1lcyI6W10sInZlcnNpb24iOjMsImZpbGUiOiJpbmRleC5kMmUwYTQyYS5qcy5tYXAifQ==):

<img width="1422" alt="Bildschirmfoto 2022-07-12 um 14 23 43" src="https://user-images.githubusercontent.com/4586894/178488773-3636ff33-593b-4cea-9c0b-a3051687290a.png">

**Comment by Levminer** [comment]
As a workaround setting line endings LF in vs code fixes this, thanks for the help!

**Comment by mm-dsibinski** [comment]
Thanks, God, I found this issue! 😀 Was struggling with weird debugging issues and totally wrong source maps...
Changing CRLF to LF line endings is a workaround, but this should really be fixed.
