### ISSUE TITLE
@parcel/core: Failed to resolve '{{profileImageUrl}}'

### ISSUE THREAD

**Issue by mattes3** [parcel-bundler/parcel#8305]
Hi,

I am using parcel to pack a node express application with the mustache-express middleware.
https://github.com/bryanburgers/node-mustache-express

parcel fails on an image tag that has a dynamic "src" attribute value:

```html
<img class="h-10 w-10 rounded-full" id="profile-image-for-mobile" src="{{profileImageUrl}}" alt="" />
```

The error message is:

```
@parcel/core: Failed to resolve '{{profileImageUrl}}' from './packages/xyz/src/web/profile-image-mobile.html'
```

As a workaround, I changed "src" to "data-src" and used a short JavaScript to copy it into the "src" attribute. Of course, it would be much better, if parcel could handle this.

**Comment by mischnic** [comment]
See https://github.com/parcel-bundler/parcel/issues/6233 both for some related issues, and also a resolver plugin that appears to solve this.
