### ISSUE TITLE
Error: Registering service workers with a string literal is not supported. - Importing jquery

### ISSUE THREAD

**Issue by LukeTOBrien** [parcel-bundler/parcel#8307]
Hello

I am getting the following error whilst importing jQuery and assigning it to a variable:

```
@parcel/transformer-js: Registering service workers with a string literal is not supported.

  C:\VB Azure\EntERPro\UI\ASP\static\Script\script.ts:16:38
    15 |
  > 16 | window['$'] = window['jQuery'] = jquery
  >    |                                      ^^^
    17 | window['functions'] = Functions;
    18 |

  💡 Replace with: new URL('service-worker.js', import.meta.url)
  📝 Learn more: https://parceljs.org/languages/javascript/#service-workers
```

My script is:

```ts
import jquery from 'jquery';

...

window['$'] = window['jQuery'] = jquery
```

## 🤔 Expected Behavior

I should be able to import jQuery and assign it to a global variable.  
The error message shouldn't mention service workers when they are not being used

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.2
| Node             | v16.16.0
| npm         | 8.11.0
| Operating System | Windows 10

```
{
    "@parcel/transformer-typescript-tsc": "^2.6.2",
    "parcel": "^2.6.2",
}
```

**Comment by LukeTOBrien** [comment]
I have just cloned my project onto a new machine and updated Parcel the 2.6.2 from 2.0.0-rc.  
Here is my tsconfig, perhaps I need to update that also?

```js
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": false,
        "removeComments": true,
        "preserveConstEnums": true,
        "sourceMap": true,
        "esModuleInterop": true,
        "target": "es2019"
    }
}
```

**Comment by Kujo-Jotaro-AAAAA** [comment]
how to fix it?

**Comment by Kujo-Jotaro-AAAAA** [comment]
> how to fix it?

I got this issue `@parcel/transformer-js: Registering service workers with a string literal is not supported.`

**Comment by mevanloon** [comment]
I worked around this by putting the serviceWorker object in a separate reference:
```js
const s = navigator.serviceWorker
s.register('worker.js')
```

This tricks Parcel, but it works for me (for now). There are probably some issues down the line with this.

**Comment by LukeTOBrien** [comment]
I am not using service workers at all, I am just importing jQuery.

I think I remember 'solving' this issue by reverting back to ParcelJS 2-beta... Now I made the mistake of updating to 2.8 and I see this issue is still present.  
This error is wrong and is causing the build to fail.

```
🚨 Build failed.

@parcel/transformer-js: Registering service workers with a string literal is not supported.

  C:\VB Azure\EntERPro\UI\ASP\static\Script\scripts-main.ts:21:38
    20 | window['$'] = window['jQuery'] = jquery;
  > 21 | window['functions'] = Functions;
  >    |                                 ^
    22 |
    23 | VhFix();

  💡 Replace with: new URL('service-worker.js', import.meta.url)
  📝 Learn more: https://parceljs.org/languages/javascript/#service-workers
```

**Comment by LukeTOBrien** [comment]
@mischnic What do you think?

**Comment by crisdosaygo** [comment]
Also seeing this on windows. Going to try the hacky workaround!
