### ISSUE TITLE
Parcel autoprefix bug

### ISSUE THREAD

**Issue by ghost** [parcel-bundler/parcel#8314]
# 🐛 bug report

## 🎛 Configuration (package.json, cli command)

```js
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "source": "src/index.html",
  "browserslist": "defaults",
  "scripts": {
    "start": "parcel src/index.html --open",
    "clean": "rm -rf dist/*",
    "build:parcel": "parcel build src/index.html --no-content-hash --no-source-maps --public-url ./",
    "build": "npm run clean && npm run build:parcel"
  },
  "keywords": [],
  "author": "",
  "license": "",
  "devDependencies": {
    "parcel": "^2.6.2",
    "tailwindcss": "^3.1.5"
  }
}
```

## 🤔 Expected Behavior

With _build_ script Parcel should add vendor prefix to mask-image: linear-gradient:
``` mask-image: linear-gradient(to top, #d1f218 0%, transparent 90%); ```

as it does with an svg or png etc:
```mask-image: url('./../../medias/web3.svg'); -> -webkit-mask-image: url(web3.e062c7eb.svg);```

## 😯 Current Behavior

mask-image linear gradient ``` mask-image: linear-gradient(to top, #d1f218 0%, transparent 90%); ```
is not prefixed

mask-image url is prefixed :
```mask-image: url('./../../medias/web3.svg'); ```

but, it is added twice in the generated css:
```
.classic .wrapper {
    -webkit-mask-image: url(web3.e062c7eb.svg);       <--
    background-color: #f0f0f0;
    -webkit-mask-image: url(web3.e062c7eb.svg);       <--
    mask-image: url(web3.e062c7eb.svg);                     
    -webkit-mask-size: contain;
    mask-size: contain;
```

## 💁 Possible Solution
Sorry no idea

## 🔦 Context

I'm trying to apply a mask effect witch should work in all browsers.
 
- There are some styles added with Tailwind's ```@apply``` in my class, I thought it could be the cause of the bug, but after removing Tailwind styles, issue is the same.
- I also tried to add manually the vendor prefix in my dev file, but the build delete it.
- I tried to change browserslist settings but issue is the same.
- I had a look at the [Parcel CSS playground](https://parcel-css.vercel.app/#%7B%22minify%22%3Afalse%2C%22nesting%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A262144%2C%22firefox%22%3A131072%2C%22safari%22%3A131072%2C%22opera%22%3A131072%2C%22edge%22%3A131072%2C%22ie%22%3A131072%2C%22ios_saf%22%3A131072%2C%22android%22%3A131072%2C%22samsung%22%3A131072%7D%2C%22source%22%3A%22.x%20%7B%5Cn%20%20mask-image%3A%20linear-gradient(to%20top%2C%20%23d1f218%200%25%2C%20transparent%2090%25)%3B%5Cn%5Cn%5Cn%7D%5Cn.y%20%7B%5Cn%20%5Cnmask-image%3A%20url('.%2Fimage.png')%3B%5Cn%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D), if 4 last versions of Chrome are targeted, prefix works:

## 💻 Code Sample

With Tailwind:
```
.enter-site {
  @apply absolute bottom-0 right-0 overflow-hidden w-[calc(var(--wrapper-height)_*_1.5)] h-[var(--wrapper-height)];
  clip-path: polygon(50% 100%, 0 0, 100% 0);
  transform: rotate3d(1, 1, -1, -10deg) translateX(-20%);
  mask-image: linear-gradient(to top, #d1f218 0%, transparent 90%);
  mask-size: 100%;
}
```

Tried without Tailwind:
```
.enter-site {
  clip-path: polygon(50% 100%, 0 0, 100% 0);
  transform: rotate3d(1, 1, -1, -10deg) translateX(-20%);
  mask-image: linear-gradient(to top, #d1f218 0%, transparent 90%);
  mask-size: 100%;
}
```

Browslerslist differents settings:

```
and_chr 103
and_ff 101
and_qq 10.4
and_uc 12.12
android 103
chrome 103
chrome 102
chrome 101
edge 103
edge 102
firefox 102
firefox 101
firefox 91
ios_saf 15.5
ios_saf 15.4
ios_saf 15.2-15.3
ios_saf 14.5-14.8
ios_saf 14.0-14.4
ios_saf 12.2-12.5
kaios 2.5
op_mini all
op_mob 64
opera 87
opera 86
opera 85
safari 15.5
safari 15.4
samsung 17.0
samsung 16.0
```
```
and_chr 103
and_ff 101
and_qq 10.4
and_uc 12.12
android 103
android 4.4.3-4.4.4
chrome 103
chrome 102
chrome 101
chrome 100
chrome 87
edge 103
edge 102
edge 101
edge 100
firefox 102
firefox 101
firefox 100
firefox 99
ios_saf 15.5
ios_saf 15.4
ios_saf 15.2-15.3
ios_saf 15.0-15.1
ios_saf 14.5-14.8
ios_saf 14.0-14.4
ios_saf 12.2-12.5
kaios 2.5
op_mini all
op_mob 64
opera 87
opera 86
opera 85
opera 84
opera 83
safari 15.5
safari 15.4
safari 15.2-15.3
safari 15.1
safari 14.1
safari 13.1
samsung 17.0
samsung 16.0
samsung 15.0
samsung 14.0
constantin@mac-webc webc % npx browserslist
and_chr 103
and_ff 101
and_qq 10.4
and_uc 12.12
android 103
android 4.4.3-4.4.4
chrome 103
chrome 102
chrome 101
chrome 100
chrome 99
chrome 98
chrome 96
chrome 87
chrome 83
chrome 79
edge 103
edge 102
edge 101
firefox 102
firefox 101
firefox 100
ios_saf 15.5
ios_saf 15.4
ios_saf 15.2-15.3
ios_saf 15.0-15.1
ios_saf 14.5-14.8
ios_saf 14.0-14.4
ios_saf 13.4-13.7
ios_saf 12.2-12.5
kaios 2.5
op_mini all
op_mob 64
opera 87
opera 86
opera 85
safari 15.5
safari 15.4
safari 14.1
safari 14
safari 13.1
samsung 17.0
samsung 16.0
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.2
| Node             | 16.14.2
| npm/Yarn         | 8.5.0
| Operating System | masOS Monterey

**Comment by mischnic** [comment]
> mask-image linear gradient mask-image: linear-gradient(to top, #d1f218 0%, transparent 90%);
is not prefixed

Please open an issue for that here: https://github.com/parcel-bundler/parcel-css/issues

> but, it is added twice in the generated css:

That is apparently happening because both the CSS transformer and the CSS optimizer prefix it, so it's prefixed twice.
1. parcel-css should not prefix it again: https://github.com/parcel-bundler/parcel-css/issues/237
2. I'm not sure if something should be changed on the Parcel side to prevent double prefixing in the first place @devongovett ?

**Comment by devongovett** [comment]
Fixed upstream
