### ISSUE TITLE
Still same issue with Macbook M1 pro 

### ISSUE THREAD

**Issue by kamran96** [parcel-bundler/parcel#8321]
<img width="1430" alt="Screenshot 2022-07-19 at 11 25 43 AM" src="https://user-images.githubusercontent.com/28526984/179681061-cdf3d3bd-88ab-403c-96f5-e6651381860a.png">

**Comment by mischnic** [comment]
There are prebuilds for Apple Silicon with the watcher package: https://unpkg.com/browse/@parcel/watcher@2.0.5/prebuilds/

So the question is which version of the watcher you're using here
