### ISSUE TITLE
Generated web worker code always fails on Cannot find module '7pK6S'

### ISSUE THREAD

**Issue by sranka** [parcel-bundler/parcel#8324]
# 🐛 bug report
I am trying to migrate from an existing git project from parcel v1 to parcel v2. I followed the guide and repaired some configuration issues so that a new parcel is able to build the code. When the web application starts, it fails on `Cannot find module '7pK6S'`. The worker js file does not contain `parcelRequire.register("7pK6S",`, which is probably the reason of why it fails. 

## 🎛 Configuration (.babelrc, package.json, cli command)

See https://github.com/influxdata/chronograf/tree/chore/upgrade_to_parcel_v2/ui for all configuration files.

## 🤔 Expected Behavior

Produced worker js file does not fail on missing dependencies, they should be bundled as well.

## 😯 Current Behavior
The worker code fails on load with:
```
Uncaught Error: Cannot find module '7pK6S'
    at parcelRequire (worker.5dea93c6.js:34:15)
    at worker.5dea93c6.js:47:14
```

## 🔦 Context

I was trying to upgrade to parcel v2 since the used parcel v1 is not maintained anymore.

## 💻 Code Sample

```bash
git clone git@github.com:influxdata/chronograf.git
git checkout chore/upgrade_to_parcel_v2
yarn
cd chronograf/ui
yarn build:inspect
# build directory contains a woker<HASH>.js file that does not import dependecies
cd ..
go run ./cmd/chronograf -f
xdg-open http://localhost:8888
# observe browser logs
```

The worker code is imported in https://github.com/influxdata/chronograf/blob/chore/upgrade_to_parcel_v2/ui/src/worker/JobManager.ts#L30

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.2 |
| Node             | 14.18.1 |
| npm/Yarn         | yarn 1.22 |
| Operating System | Ubuntu 20 |

**Comment by mischnic** [comment]
You could try doing `new Worker(new URL(...), ...)` without the separate `url` variable, as shown here https://parceljs.org/languages/javascript/#web-workers

Splitting the `URL` and the `Worker` might be broken in subtle ways.

**Comment by sranka** [comment]
Thank you @mischnic, it helped.
