### ISSUE TITLE
-webkit-user-select is being removed in CSS selectors which contain user-select

### ISSUE THREAD

**Issue by isjackwild** [parcel-bundler/parcel#8327]
# 🐛 bug report

Autoprefixer is removing the `-webkit-user-select` property if it is specified in the same selector as `user-select`.

### .parcelrc

```js
{
  "extends": [
    "@parcel/config-default"
  ],
  "resolvers": [
    "@parcel/resolver-glob",
    "..."
  ],
  "reporters": [
    "...",
    "parcel-reporter-static-files-copy"
  ],
  "transformers": {
    "*.svg": [
      "...",
      "@parcel/transformer-svg-react"
    ],
    "url:*.json": [
      "@parcel/transformer-raw"
    ]
  },
  "optimizers": {
    "*.{jpg,jpeg,png}": []
  }
}

```

### package.json

```
{
  "name": "app",
  "version": "0.1.0",
  "private": true,
  "source": "src/index.html",
  "browserslist": [
    "> 0.5%",
    "last 4 versions",
    "not dead"
  ],
  "scripts": {
    "start": "parcel",
    "build": "parcel build --public-url ${PUBLIC_URL:='.'}"
  },
  "dependencies": {},
  "devDependencies": {
    "@parcel/resolver-glob": "^2.1.0",
    "@parcel/transformer-glsl": "^2.1.1",
    "@parcel/transformer-jsonld": "^2.2.1",
    "@parcel/transformer-sass": "^2.1.1",
    "@parcel/transformer-svg-react": "^2.2.0",
    "@types/howler": "^2.2.4",
    "@types/node": "17.0.40",
    "@types/react": "18.0.12",
    "@types/react-dom": "18.0.5",
    "@types/three": "^0.135.0",
    "eslint": "8.17.0",
    "eslint-config-next": "12.1.6",
    "flex-gap-polyfill": "^4.1.0",
    "parcel": "^2.1.1",
    "parcel-reporter-static-files-copy": "^1.3.4",
    "process": "^0.11.10",
    "sass": "^1.52.3",
    "sharp": "^0.29.3",
    "typescript": "4.7.3"
  }
}

```

## 🤔 Expected Behavior

As `user-select` needs a prefix, even in the newest version of iOS safari, the vendor prefixed version should be added automatically (and not removed if added explicitly!)

## 😯 Current Behavior

The `-webkit-user-select: none` is removed from the compiled CSS.

## 💁 Possible Solution

If you do not include `user-select: none` in the selector, the prefixed version is left alone.

## 🔦 Context

Trying to add CSS which will work consistently in iOS and non-iOS devices..

## 💻 Code Sample

```
// app.scss

button {
  -webkit-user-select: none;
  user-select: none;
}
```

```
// compiled css

button {
  user-select: none;
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.1.1
| Node             |v16.13.1
| npm/Yarn         | 8.1.2
| Operating System | macOS

**Comment by astro813** [comment]
Agree! Same issue for me. And also for @isjackwild, try this for fixing:
button {
  -webkit-user-select: none !important;
  user-select: none;
}

**Comment by devongovett** [comment]
As far as I can tell, it isn't being removed by Parcel CSS: [Example](https://parcel-css.vercel.app/#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22ios_saf%22%3A983040%7D%2C%22source%22%3A%22button%20%7B%5Cn%20%20-webkit-user-select%3A%20none%3B%5Cn%20%20user-select%3A%20none%3B%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D).

The version listed above (v2.1.1) is pretty old though. Are you seeing this in more recent versions?

**Comment by isjackwild** [comment]
Just tried this in parcel 2.7.0 and it does appear to be fixed in that
version

**Comment by astro813** [comment]
@devongovett works for me for updating from 2.5 to 2.7. Thanks!

**Comment by stevelacey** [comment]
@devongovett I am still seeing this behavior in 2.16.1
