### ISSUE TITLE
Animated gifs stopped working upgrading to 2.6.2

### ISSUE THREAD

**Issue by dioptre** [parcel-bundler/parcel#8328]
Using https://parceljs.org/recipes/image/

All of our images started cropping when using width/height changes and webp

Going to leave this as a footnote for now to see if it has effected anyone else.

Will report back soon.

**Comment by mischnic** [comment]
Nothing really changed in Parcel, maybe sharp did some breaking change?

**Comment by dioptre** [comment]
Ok thanks @mischnic 

Seems like something weird changed since 2.3.0 (we are on 2.6.2 now) maybe something to do with:

https://github.com/parcel-bundler/parcel/pull/8018

So it turns out animated GIFs are not working as expected. In version 2.3.0 we were able to specify:
```
import Image from '../../img/spinner.gif?as=webp&width=50&height=50' (this breaks in 2.6.2!!!)
```
While confusingly this is ok still:
```
import Image from '../../img/spinner.gif?as=webp' (this is ok!)
```
And the spinner animated fine at the new size, and now it doesn't work. I tried reverting the change by @Commandtechno but it still breaks,
https://github.com/parcel-bundler/parcel/commit/bb923d69f02612d65bc5f430a1cd2f7b21895252

So might be todo with the blob/streaming stuff @devongovett added above.

Can live with it, just a shame to have an upgrade that works less well than the earlier version.

Thanks

**Comment by mischnic** [comment]
So reverting https://github.com/parcel-bundler/parcel/commit/bb923d69f02612d65bc5f430a1cd2f7b21895252 apparently causes a different behaviour regarding cropping/repeat.

For me, both Parcel versions (2.3.0 and 2.6.2) remove the animation when specifying width or height.

> So might be todo with the blob/streaming stuff devongovett added above.

What change are you referring to?

**Comment by Commandtechno** [comment]
hmm, this is definitely strange behavior
with some testing, i found that `sharp('file.gif', {animated: true}).webp()` did not work, but `sharp('file.gif', {animated: true}).toFile('file.webp')` did
not sure if this is related, but hope it helps

**Comment by dioptre** [comment]
@mischnic 
https://github.com/parcel-bundler/parcel/commits/v2/packages/transformers/image/src

I tried with an earlier version of sharp but didn't seem to fix either :/ so not sure yet why it broke
