### ISSUE TITLE
🙋 HTML meta assets: React attribute(s) (xLinkHref)

### ISSUE THREAD

**Issue by tVeratti** [parcel-bundler/parcel#833]
# Feature Request
Add React-specific attributes to the list of recognized meta assets to be imported.

I'm not sure if this is something you'd consider a responsibility of Parcel since this is specific to JSX syntax, but I wanted to bring it up just in case since the basic HTML PR (#747) that brought the first iteration in of this a few days ago is fantastic!

### 🤔 Expected Behavior

If I am writing in JSX syntax and want to import an HTML meta asset, the JSX alternate of `xlink:href` (`xLinkHref`) should also import the svg reference.
```
<svg class="icon-facebook" viewBox="0 0 32 32">
  <use xLinkHref="./src/sprite.svg#facebook">
</svg>
```

would become:

```
<svg class="icon-facebook" viewBox="0 0 32 32">
  <use xlink:href="/123414523412341234.svg#facebook">
</svg>
```

### 😯 Current Behavior

The `xlink:href` must be named slightly different for JSX syntax. `xLinkHref` isn't included in the recognized attributes list and therefore does not get renamed and does not trigger an import of the asset into the dist folder.

### 💁 Possible Solution

Perhaps if the alternate JSX attribute name is included in a similar change as #747 it could also provide the same functionality.

### 🔦 Context

Writing a React application with JSX would really benefit from using the same meta asset syntax for external SVG sprites. Without this feature, I don't think component files outside of index.html would be able to import their own SVG symbols from external sprites.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.1
| Node             | 8.9.3
| npm/Yarn         | 5.6.0
| Operating System | Windows

**Comment by devongovett** [comment]
In JSX, you can use a `new URL` dependency in Parcel 2 for this.
