### ISSUE TITLE
"this" should reference the window object

### ISSUE THREAD

**Issue by johnhenry** [parcel-bundler/parcel#834]
This a 🐛 bug report.

"this" within imported scripts references an empty object rather than the window object.

### 🎛 Configuration

```bash
parcel index.html
```

(That's it! That's why I love parcel!!! :)) 

### 🤔 Expected Behavior

The window object should be available as "this" to scripts imported via the script tag.

### 😯 Current Behavior

"this" references an empty object instead.

### 💁 Possible Solution

I haven't had a chance to go through the source code, but I imagine that imported code is being run within with a context somewhere. We're passing in "{}" as the context where we should pass in the window object.

Alternatively, we might pass in a parcel-specific attribute to HTML tags that would direct parcel not to run code in a different context, but execute it untouched?

```html
<script parcel-untouched src="./external-script"></script>
```

### 🔦 Context

I'm developing packages with [rollup](https://rollupjs.org/). Creating modules that attach themselves to the window object appears to need "this" to reference the window.

This might be consider an issue with rollup, or maybe even just my configuration, but it seems entirely legitimate to develop other libraries in this way.

### 💻 Code Sample

external-script.js
```javascript
console.log(this);
```

index.html (partial)
```html
<script src="./external-script.js"></script>
<!-- logs "{}" -->
<script>
    console.log(this);
</script>
<!-- logs window object as expected-->
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.1
| Node             | 9.5.0
| npm/Yarn         | npm 5.6.0
| Operating System | Mac 10.13.3

**Comment by ronami** [comment]
Hey @johnhenry,

`this` is being replaced with `undefined` at compile time by Babel. Parcel compiles your ES6 modules with `babel-plugin-transform-es2015-modules-commonjs` which prevent you from using top-level `this`.

I think this is correct, and if you would like to use top-level `this` you can use CommonJs instead.

The plugin is configurable so we can allow top-level `this` expressions ([see here](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-modules-commonjs)). Even if we do this though, Parcel runs your modules with `this` being `module.exports` (which is how CommonJs works).

**Comment by mischnic** [comment]
I don't know if that would be correct.
Some sources:

> Babel assumes that all input code is an ES2015 module. ES2015 modules are implicitly strict mode so this means that top-level this is not window in the browser nor is it exports in node.

> Module code is always strict mode code. (http://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code)

> That means, among other things, that in browsers it's no longer possible to reference the window object through `this` inside a strict mode function. (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode)

**Comment by johnhenry** [comment]
@mischnic, thanks for the reply!

This should not have anything to do with ES2015 modules or strict mode, because i'm not referencing code that uses them. 

```javascript
console.log(this); //should log the window object.
```

```html
<script src="./external-script.js"></script>
```

To be explicit, the above code works properly on its own, but breaks when processed through parcel.

Assuming your sources are correct, by treating all code as as an ES2015 module when it is isn't, parcel potentially breaks existing code. It looks like the solution would be to prevent this from happening.

**Comment by dkundel** [comment]
According to the Babel docs there is a flag that allows you to disabled `strict` which will allow you to do what you want to @johnhenry but I do think that the default behavior makes sense. 

Why are you trying to access it implicitly instead of explicitly by using `window` instead?

**Comment by polRk** [comment]
How can i access functions in my index.ts file from code ? 
```html
<button onclick="myFn()">myFn</button>
```

```typescript
const myFn = () => {}
```

**Comment by mischnic** [comment]
> `const myFn = () => {}`

`window.myFn = ...` should work

**Comment by polRk** [comment]
> > `const myFn = () => {}`
> 
> `window.myFn = ...` should work

Typings errors... I do not want to override types.

**Comment by mischnic** [comment]
Either you do `(window as any).myFn = () => { }` or `document.querySelector(...).onclick = ...`

**Comment by polRk** [comment]
You can extend Window type like this

```
declare global {
  interface Window {
    fn: () => void
    cars: Car[]
  }
}
```

**Comment by graup** [comment]
Now there's also [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) which is another way to solve this issue. Anyway, as mentioned above, the current behavior seems to be correct. I think this issue can be closed.
