### ISSUE TITLE
Hang during "Bundling..." with large HTML input

### ISSUE THREAD

**Issue by pkgw** [parcel-bundler/parcel#8340]
# 🐛 bug report

I'm interesting in trying Parcel with large HTML inputs, where "large" is a single input file with >3 MB of markup that's mostly text and `<span>` tags. Unfortunately, Parcel is hanging for me in the `Bundling...` phase.

## 🎛 Configuration (.babelrc, package.json, cli command)

Completely vanilla since this I was just starting my experiments with parcel. Just running `yarn parcel` and/or `yarn parcel build`, with no configuration files and empty `package.json`.

## 🤔 Expected Behavior

No hang!

## 😯 Current Behavior

Parcel hangs and I need to SIGKILL the program. While hung it uses 100% of 1 CPU (I have 16), and the progress spinner is not spinning. With a 10 MB input, I let it run for 2.5 hours and it never exited. While the process was running, I noticed that its memory usage would creep up by a few hundred MB then drop back down, every 5 seconds or so.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.2 |
| Node             | 16.14.2 |
| npm/Yarn         | 1.22.19 |
| Operating System | Linux (Fedora 36, x86_64) |

**Comment by mischnic** [comment]
Can you share some HTML file that reproduces this?

**Comment by pkgw** [comment]
Sure, here: [index.html.zip](https://github.com/parcel-bundler/parcel/files/9190076/index.html.zip)

When I try to process this file, Parcel hangs in the "Bundling..." stage for at least 5 minutes. Done with

```
yarn add --dev parcel
yarn parcel build index.html
```

in a fresh directory.

(I'm well aware that this file could be optimized, but hopefully it's worth understanding what's going on in this stress-test in its current form.)

**Comment by mischnic** [comment]
The problem are the many inline style attributes, so there are about 21000 assets in the graph.

**Comment by pkgw** [comment]
@mischnic Thank you for investigating! Just for my own planning purposes, is this the sort of thing that you think will be worth addressing in Parcel? If I converted those style attributes to CSS classes, would that potentially make the content more Parcel-friendly?
