### ISSUE TITLE
Bundle analyzer (and code shaking not optimal?)

### ISSUE THREAD

**Issue by dioptre** [parcel-bundler/parcel#8343]
# 🐛 bug report

https://bundlephobia.com/package/react-dom@17.0.0 reports a 120kb minified size

while if you add the same to a parcel project the output is reported at ~400k by the parcel/reporter-bundle-analyzer

## 🎛 Configuration (.babelrc, package.json, cli command)

parcel 2.6.2

## 🤔 Expected Behavior
Expecting smaller files?

**Comment by mischnic** [comment]
There's nothing that can be treeshaking from react-dom, so I suspect the bundle analyzer is reporting invalid numbers, maybe the sourcemaps are slightly wrong again.
