### ISSUE TITLE
Using --target default in development with causes Javascript module to fail with "cannot find module"

### ISSUE THREAD

**Issue by CxRes** [parcel-bundler/parcel#8351]
# 🐛 bug report

Using `--target default` in development builds containing Javascript with `type="module"` results in error `cannot find module`, even though the Javascript file contains no module imports, even no modern Javascript (I am using a simplified toy case on purpose).

## 🎛 Configuration and Code Sample 

Package.json

```json
{
  "browserslist": [
    "> 0.25%",
    "last 2 iOS versions",
    "firefox esr",
    "last 2 years",
    "not dead"
  ],
  "scripts": {
    "start": "parcel src/index.pug --dist-dir=_dist --target default"
  }
}
```

Code not being loaded:

email.js

```js
const mail = document.body.querySelector('#about #mail');

const email = document.createElement('a');
email.textContent = 'foo@example.com';
email.title = 'Send E-mail';
mail.prepend(email);
```
index.pug

```pug
script(src='js/email.js', type='module', defer)
```

Take `type="module"` away and there is no error.

## 🤔 Expected Behavior

There should be no errors, since no modules are being loaded. 

I read elsewhere that this may possibly be due to tree-shaking of Parcel development modules. But, I have no clue!

## 😯 Current Behavior

Error with Stack Trace:

```
email.fa66079d.js:61 Uncaught Error: Cannot find module 'jj53V'
    at newRequire (email.fa66079d.js:61:19)
    at newRequire (email.fa66079d.js:45:18)
    at localRequire (email.fa66079d.js:84:35)
    at eJn8l.@swc/helpers/src/_async_to_generator.mjs (runtime-2e43062594ee6a7f.js:1:1)
    at newRequire (email.fa66079d.js:71:24)
    at email.fa66079d.js:122:5
    at email.fa66079d.js:145:3
```

Transformed JS (too big for Pasting here):
[email.fa66079d.js](https://github.com/parcel-bundler/parcel/files/9228533/email.fa66079d.js.txt)

## 🔦 Context

Incidentally, I am using `--target default` because of the autoprefixer bug #8295.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.2 |
| Node             | 18.6.0 |
| npm/Yarn         | 8.13.2 |
| Operating System | Windows 10 x64 |

**Comment by arty-name** [comment]
I think this is addressed in the latest 2.8.3
