### ISSUE TITLE
`browser` target generates `__filename` for `new Worker`

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#8367]
# 🐛 bug report

When using the `browser` target, code like this is generated: `new Worker(new URL("worker.6344e013.js", "file:" + __filename));` (which is for Node, not for browsers or bundlers)

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
	"source": "index.js",
	"browser": "dist/index.js",
	"dependencies": {
		"parcel": "^2.7.0"
	}
}
```

## 🤔 Expected Behavior

Use `import.meta.url` in the output?

## 😯 Current Behavior

Output: `new Worker(new URL("worker.6344e013.js", "file:" + __filename));`

`module` does use import.meta.url

## 💻 Code Sample

package.json from above

```js
// index.js
new Worker(new URL("worker.js", import.meta.url));

// worker.js empty
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0

**Comment by devongovett** [comment]
The browser target is meant to be commonjs though

**Comment by mischnic** [comment]
If you build a library with Parcel and then also build use that library, we prioritize `browser` before any other field. Then you get a build error about not using `new URL` for the worker. Is the solution here "don't use the `browser` field"?

**Comment by devongovett** [comment]
hmm I guess we have to also detect `"file:" + __filename` as an alias for `import.meta.url`?

**Comment by inimeseke** [comment]
Just mentioning that Rollup produces this kind of output instead of `import.meta.url`

`new Worker(new URL("worker.js", (typeof document === 'undefined' ? new (require('u' + 'rl').URL)('file:' + __filename).href : (document.currentScript && document.currentScript.src || new URL('index.js', document.baseURI).href))))`

Where index.js is the generated bundle file

**Comment by 101arrowz** [comment]
`__filename` is a Node + CommonJS thing, not a CommonJS thing - we can just find a replacement for `__filename` in CommonJS + browser (e.g. `document.currentScript.src` as shown above).
