### ISSUE TITLE
Parcel incorrectly bundles shared Vue components CSS 

### ISSUE THREAD

**Issue by ArthurMelin** [parcel-bundler/parcel#8368]
# 🐛 Bug report

When sharing Vue components between 2 different root HTML files (`a.html` and `b.html`), Parcel may incorrectly inject the compiled CSS from both of the 2 bundle trees into one of the HTML file.

## 🎛 Configuration (.babelrc, package.json, cli command)

`parcel build a.html b.html`

## 🤔 Expected Behavior

We want each HTML file to only be injected with the CSS from the components it uses (unique or shared).
```
a.html -> a.css (CSS from components unique to a.html + CSS from shared components)
b.html -> b.css (CSS from components unique to b.html + CSS from shared components)
```
or
```
a.html -> a.css (CSS from components unique to a.html) + shared.css (CSS from shared components)
b.html -> b.css (CSS from components unique to b.html) + shared.css (CSS from shared components)
```
## 😯 Current Behavior
```
a.html -> a.css (CSS from components unique to a.html + CSS from shared components)
b.html -> a.css (CSS from components unique to a.html + CSS from shared components) + b.css (CSS from components unique to b.html)
```
This causes problems because some of the CSS from the unique components of `a.html` is applied to b.html.

## 💻 Code Sample

https://gist.github.com/ArthurMelin/797b2479365a34a12278348da9d788aa

## 🌍 Your Environment

| Software | Version(s) |
| ----------|------------ |
| Parcel | 2.7.0
| Node | 18.7.0
| npm/Yarn | yarn 1.22.19
| Operating System | Linux x64

**Comment by mischnic** [comment]
With your example, I only get two CSS bundles.
