### ISSUE TITLE
readFileSync not resolving symbolic links

### ISSUE THREAD

**Issue by kcoop** [parcel-bundler/parcel#8373]
When using `yarn add link:` to install a local version of a dependency, then attempting to load a file from within that package with `readFileSync`, the dreaded and initially mystifying `Uncaught TypeError: (0 , _fs.readFileSync) is not a function` message appears, indicating Parcel was unable to resolve the file.

A workaround is to install a copy of the package with `yarn add file:`. This works, but it's not optimal, as it means local development of the dependent package must be done against a copy.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.2
| Node             | 18.7.0
| npm/Yarn         | yarn 1.22.19
| Operating System | MacOS Monterey 12.5

**Comment by mischnic** [comment]
That happens here: https://github.com/parcel-bundler/parcel/blob/69ef97adc626c1d9cf0626c0ef01df4b8bf93b71/packages/transformers/js/core/src/fs.rs#L125-L167

I suspect that you're linking to outside the project? The reason that's disallowed is a package from npm shouldn't be able to do something like `fs.readFileSync("/etc/passwd")`.

**Comment by kcoop** [comment]
Ah, feature, not bug. 

This is accessing a file from an external dependency that will be available within node_modules (using yarn link for development, as the two modules are intertwined, one exposing a public api). 

This is intended to be resolved at build time (browser based), so security isn’t an issue, but now I understand the rightly intentional limitation of the api, thanks. I’ll add a prebuild copy step instead.
