### ISSUE TITLE
css path is wrong in `parce build` generated index.html

### ISSUE THREAD

**Issue by jupiterben** [parcel-bundler/parcel#8374]
# 🐛 bug report

`parcel build`  gengerated index.html include css in a wrong path
 <script src="/index.3b75f4ea.js" type="module"></script>

## 🎛 Configuration (.babelrc, package.json, cli command)

the problem project is here
https://github.com/jupiterben/tsproject/tree/parcel

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.7.0
| Node             |  16.3.1
| npm/Yarn         | 8.1.2
| Operating System | Windows10

**Comment by mischnic** [comment]
The linked repo is probably not public?

**Comment by jupiterben** [comment]
> The linked repo is probably not public?

Sorry, changed the visibility . pls try again.

**Comment by mischnic** [comment]
What exactly is the problem? You wrote "css path is wrong" but then pasted the generated Javascript script tag

**Comment by jupiterben** [comment]
> What exactly is the problem? You wrote "css path is wrong" but then pasted the generated Javascript script tag
the generated dist/index.html  file can not display in a http server the  <script src="/index.3b75f4ea.js" type="module"></script> should be <script src="./index.3b75f4ea.js" type="module"></script>  isn't it?

**Comment by KingKyon** [comment]
Try running this - i have the same issue where it appends a "/" character in front of the file path...this seems to work for me:
"npx parcel build index.html --public-url ./"

By appending the "--public-url ./" on the end of the CLI build command, it seems to fix the paths issue for me!

**Comment by jupiterben** [comment]
> Try running this - i have the same issue where it appends a "/" character in front of the file path...this seems to work for me: "npx parcel build index.html --public-url ./"
> 
> By appending the "--public-url ./" on the end of the CLI build command, it seems to fix the paths issue for me!

It works , thanks
