### ISSUE TITLE
Bundling jQuery using browserslist > 0.25% produces infinite recursion

### ISSUE THREAD

**Issue by veldsla** [parcel-bundler/parcel#8382]
# 🐛 bug report

When parcel 2.7.0 bundles jQuery (3.6.0) using `browserslist": "> 0.25%` the jQuery.remove function results in an infinite recursion loop.

## 🎛 Configuration (.babelrc, package.json, cli command)

The issue appears to be triggered only when this line is present in `package.json`
```js
  "browserslist": "> 0.25%, last 2 versions, not dead"
```

## 🤔 Expected Behavior

Parcel builds functional bundle

## 😯 Current Behavior

The browser throws an error about the recursion limit (Uncaught InternalError: too much recursion)

## 💁 Possible Solution

Changing the `browserslist` line from
```
  "browserslist": "> 0.25%, last 2 versions, not dead"

```
to 
```
  "browserslist": "> 1%, last 2 versions, not dead"

```
mitigates the issue.
Also rolling back to parcel@2.6.2 works when  >0.25% used

## 🔦 Context

After updating parcel I noticed my jQuery code producing an infinite recursion loop in the jQuery.remove function. After some digging I identified the that restricting the supported browsers fixes the issue.

For my situation the > 1% will be fine, so I do not require this to be fixed, but I thought it might be interesting to report.

This issue might be more upstream in SWC perhaps? But I don't know if these versions changed between 2.6.2 and 2.7.0

## 💻 Code Sample

A gist to reproduce can be found here 
https://gist.github.com/veldsla/762e42bfeb1036e173bb4bc9954634f0
I ran this with
```bash
npx parcel serve --target default --no-hmr index.html 
```
Changing > 0.25% to > 1% in the package.json produces a functional page.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0
| Node             | v16.16
| npm/Yarn         | npm 8.16
| Operating System | Arch linux

**Comment by codinglobster** [comment]
<img width="465" alt="企业微信截图_f3f05c8c-a713-4b4a-aa71-60188012279f" src="https://user-images.githubusercontent.com/22992734/204247979-1b10c614-86db-40c5-81d2-9361fe8a6a8c.png">
jquery bundle result is above.
function with name, the call scope is changed, cause self call repetition.

**Comment by veldsla** [comment]
I just tested parcel-2.9.1 and it it appears to be resolved!
