### ISSUE TITLE
Uncaught TypeError: Class constructor [extended class] cannot be invoked without 'new'

### ISSUE THREAD

**Issue by rokyed** [parcel-bundler/parcel#839]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
// .babelrc
{
  "presets" : ["es2015-ie"]
}

//.postcssrc
{
	"modules": true,
	"plugins": {
		"autoprefixer": {
			"grid": true
		}
	}
}
//package.json
{
 "name": "",
 "version": "1.0.0",
 "description": "",
 "main": "index.js",
 "scripts": {
  "test": "echo \"Error: no test specified\" && exit 1",
  "start": "./node_modules/.bin/parcel --no-cache ./src/index.html --out-dir ./dist",
  "build": "./node_modules/.bin/parcel build --no-minify ./src/index.html --out-dir ./dist"
 },
 "author": "",
 "license": "",
 "dependencies": {
  "acorn": "^5.4.1",
  "babel-preset-es2015-ie": "^6.7.0",
  "mobile-detect": "^1.4.1",
  "node-sass": "^4.7.2",
  "parcel-bundler": "^1.6.1",
  "postcss-modules": "^1.1.0",
  "webpack": "^3.1.0",
  "wrench-set": "^1.0.6"
 }
}
```

### 🤔 Expected Behavior

It should just create the class and do the magic of Element. (wrench-set was created by me, and tested in another project, which works perfectly, using parcel 1.5.1)

### 😯 Current Behavior

it shoots error with class constructor cannot be invoked without new for the super()

Uncaught TypeError: Class constructor Element cannot be invoked without 'new'
    at new Viewport (viewport.js:5)
    at Object.require.4../index.scss (index.js:4)
    at newRequire (3127ebea6fd59e02267b4119b100f294.js:42)
    at require.14 (3127ebea6fd59e02267b4119b100f294.js:69)

### 💁 Possible Solution
the hacky way :smile: 
revert to 1.5.1 in order to be able to successfully compile the code 

### 💻 Code Sample

```js

// main.js
import style from './index.scss'
import Viewport from './viewport.js'

const VIEWPORT = new Viewport({
	renderTo: document.body
})

// viewport.js
import {Element} from 'wrench-set'
import style from './viewport.scss'

export default class Viewport extends Element {
	constructor (config) {
		super({
			renderTo: config.renderTo,
			innerHTML: 'hi',
			className: `${style.viewport}`
		})
	}
}
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.1
| Node             | 8.9.3
| npm/Yarn         | 5.5.1
| Operating System | Linux Mint 18

**Comment by mthadley** [comment]
I had a similar issue. I was extending a class exported from a node module. Upon inspecting the compiled code, I noticed that my class was transpiled into an ES5 class, but the code coming from the node modules was not being transpiled (it was still defined with the `class` keyword, etc).

So it was essentially an ES5 class extending an ES6 class, and that seems to cause this error. I haven't managed to fix it yet, but it seems like once reason might be because parcel isn't compiling the module.

[Here's the module in question.](https://github.com/metal/metal.js/tree/master/packages/metal-jsx). Maybe it has something in common with `wrench-set`?

**Comment by rokyed** [comment]
@mthadley about ```wrench-set```, yes, it's not minified. It's a module that I've built, it's super simple, it's based on ES6, but I don't think that should be the problem, when you are packaging something, you shouldn't expect that modules are already packaged, that's my understanding of a package. I think that it should be compiled/baked into your code, from the code that was provided.

**Comment by rokyed** [comment]
After further investigation, it seems that babel won't compile node_modules, in webpack there are ways to mitigate this trough webpack.

**Comment by FishOrBear** [comment]
I have encountered the same problem using webpack+typescript.

I use `@ContextMenuTarget`

**Comment by danmarshall** [comment]
@mthadley describes this bug succinctly:
> an ES5 class extending an ES6 class, and that seems to cause this error.

Parcel has compiled some of my `class`es to `function`s. 🤔
@FishOrBear do you have a workaround?

**Comment by danmarshall** [comment]
I have a simple repro:

#### test.html:
```html
<html>
<head>
    <script>
        //some other library
        class Animal {
            move(distance) {
                console.log(`Animal moved ${distance}`);
            }
        }
    </script>
</head>
<body>
    <script>
        new Animal().move(7);
    </script>
    <script src="test.js"></script>
</body>
</html>
```

#### test.js:
```js
class Horse extends Animal {
    move(distance) {
        console.log(`Horse galloped ${distance}`);
    }
}

new Horse().move(7);
```

## Output before Parcel:
```
Animal moved 7
Horse galloped 7
```

## Output after Parcel:
```
Animal moved 7
test.84371532.js:2 Uncaught TypeError: Class constructor Animal cannot be invoked without 'new'
    at new i (test.84371532.js:2)
    at Object.parcelRequire.4 (test.84371532.js:2)
    at i (test.84371532.js:1)
    at parcelRequire.4 (test.84371532.js:1)
    at test.84371532.js:1
i @ test.84371532.js:2
parcelRequire.4 @ test.84371532.js:2
i @ test.84371532.js:1
parcelRequire.4 @ test.84371532.js:1
(anonymous) @ test.84371532.js:1
```

**Comment by danmarshall** [comment]
Here is the compiled `Horse` which is now a `function` instead of a `class`:
```
var Horse = function (_Animal) {
    _inherits(Horse, _Animal);

    function Horse() {
        _classCallCheck(this, Horse);

        return _possibleConstructorReturn(this, (Horse.__proto__ || Object.getPrototypeOf(Horse)).apply(this, arguments));
    }

    _createClass(Horse, [{
        key: "move",
        value: function move(distance) {
            console.log("Horse galloped " + distance);
        }
    }]);

    return Horse;
}(Animal);
```

**Comment by Alber70g** [comment]
Any news on a fix? I'm using `LitElement` and creating mixins for classes but I'm not able to compile with Parcel. I'm also using Typescript.

**Comment by arnm** [comment]
bump...

**Comment by Nviano** [comment]
bump

**Comment by jamesgpearce** [comment]
If you manage the dependent module's `package.json`, you might be able to avoid this by using `"source": true`

**Comment by Alber70g** [comment]
> Any news on a fix? I'm using `LitElement` and creating mixins for classes but I'm not able to compile with Parcel. I'm also using Typescript.

I'm using this now in Parcel to make it not remove the `class` syntax. But it'll hurt older browsers:

Add this to your `package.json` and Parcel will pick it up as babel config.
```
"browserslist": [
    "last 1 chrome versions"
  ]
```

**Comment by DeMoorJasper** [comment]
Adding babel-polyfill would probably also fix this.

It's probably due to parcel compiling using babel after ts to correspond to specified browserlist as @Alber70g pointed out already

**Comment by prasannavl** [comment]
I think this real issue is due to the fact that parcel uses `pkg.module` is `package.json` incorrectly. Most well developed libraries today, set `main` to cjs versions, while `module` will be set to es6 versions. 

The correct behavior should be, when an es6 module is encountered, and the compile target is es6, parcel should compile these into es5, *despite* them being node_modules.

**Comment by jantimon** [comment]
@prasannavl the best practice is to transpile es6 as there are so many different es6 stages:

https://github.com/rollup/rollup/wiki/pkg.module#wait-it-just-means-import-and-export--not-other-future-javascript-features

**Comment by prasannavl** [comment]
@jantimon - Err, almost all modern platforms support a most of the commonly used features today, but not import and export. So, most modern libraries, take the polymer's `lit-html` just completely bids good-bye to es5.

**Comment by timdeng2324** [comment]
@prasannavl what should the babelrc target be for ES6? @Alber70g's latest 1 chrome version worked for me, but i want to make sure i have maximum browser compatibility. right now i'm just using @babel/preset-env.

**Comment by prasannavl** [comment]
@timdeng2324 - perhaps, try adding `@babel/plugin-transform-classes` to `exclude`, and see if that does the trick? (haven't really tested it myself)

**Comment by skukan159** [comment]
Anyone found a solution to this problem? My mixins are complaining that they cannot invoke class constructor without new.  This is my .babelrc 
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "browsers": [ "last 2 versions", "ie >= 11" ]
        },
        "exclude": [ "transform-classes" ]
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-object-rest-spread",
    "@babel/plugin-syntax-dynamic-import"
  ]
}

```
And here is the webpack script: 

`
const webpack = require('webpack');
const path = require('path');
//Not sure which we need from these
const ExtractTextPlugin = require('extract-text-webpack-plugin');
//const extractCSS = new ExtractTextPlugin('aem-bundle.css');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const WorkboxPlugin = require('workbox-webpack-plugin');
//const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');

module.exports = function (env) {
    return {
        entry: './src/index.js',
        output: {
            // options related to how webpack emits results
            path: path.resolve(__dirname, 'wwwroot'), // We want to output all of our files to wwwroot folder
            // the target directory for all output files
            // must be an absolute path (use the Node.js path module)
            filename: "[name].bundle.js",  // the filename template for entry chunks
            /* publicPath: "/include/", // string    // the url to the output directory resolved relative to the HTML page*/
        },
        //This has been added to fix an error regarding returning promises while lazy loading chunks from app shell base
        node: {
            dns: 'mock',
            net: 'mock'
        },
        /* optimization: {
             splitChunks: {
                 chunks: "all",
                 minSize: 0
             },
          //   minimize: true,
            minimizer: [
                 new UglifyJsPlugin()
             ],
             usedExports: true,
             sideEffects: true
         },*/
        module: {
            rules: [

        /*     {
                    "test": /\.html$/,
                    "exclude": /node_modules/,
                    "use": [
                        "babel-loader"
                    ]
                 },*/

                {
                    test: /\.js$/,
                   exclude: /node_modules/,
                    use: {
                        loader: 'babel-loader',
                        options: {
                            presets: ['@babel/preset-env'],
                            plugins: [
                                "@babel/plugin-proposal-class-properties",
                                "@babel/plugin-proposal-object-rest-spread",
                                "@babel/plugin-syntax-dynamic-import"
                            ]
                        }
                    }
                },
                {
                    test: /\.json$/,
                    use: 'json-loader'
                },
                {
                    test: /\.(png|svg|jpg|gif)$/,
                    use: [
                        {
                            loader: 'file-loader',
                            options: {
                                name: '/img/[name].[ext]'
                            }
                        }
                    ]
                }
            ]
        },
       
        resolve: {
            // options for resolving module requests
            // (does not apply to resolving to loaders)


            // directories where to look for modules
            modules: [
                "node_modules",
                path.resolve(__dirname, "src")
            ],
            // extensions that are used
            extensions: [".js", ".json"],

            //Used to provide global Mark variable without defining it in the index.html
            alias: {
                'markjs': path.resolve(__dirname, "./node_modules/mark.js/dist/mark.min.js"),
            }


        },

        plugins: [
            new webpack.ProvidePlugin({
                IntlMessageFormat: ['intl-messageformat/index.js', 'default'],
                'Mark': 'markjs'
            }),
            new CleanWebpackPlugin(['wwwroot']),
            new WorkboxPlugin.GenerateSW({
                // these options encourage the ServiceWorkers to get in there fast 
                // and not allow any straggling "old" SWs to hang around
                swDest: 'sw.js',
                clientsClaim: true,
                skipWaiting: true
            }),
            new CopyWebpackPlugin([
                //TODO: Clean up output locations for some of the files
                //You can remove the second parameter(wwwroot) from path.resolve,
                //and just hardcode the location

                {
                    from: './node_modules/web-animations-js/*{.js,.js.map}',
                    to: './node_modules/web-animations-js/[name].[ext]'
                },
                {
                    from: 'include/components/oidc-client/oidc-client.min.js',
                    to: path.resolve(__dirname, 'wwwroot'),
                    context: './src/'
                },
                {
                    from: 'manifest.json',
                    to: path.resolve(__dirname, 'wwwroot'),
                    context: './src/'
                },
                {
                    from: 'sw-service-worker.js',
                    to: path.resolve(__dirname, 'wwwroot'),
                    context: './src/'
                },
                {
                    from: 'include/images/*',
                    to: path.resolve(__dirname, 'wwwroot'),
                    context: './src/'
                },
                {
                    from: '*.html',
                    to: path.resolve(__dirname, 'wwwroot'),
                    context: './src/'
                }

            ])
        ],

 
        watch: true, // boolean
        watchOptions: {
            aggregateTimeout: 1000, // in ms
            // aggregates multiple changes to a single rebuild
            poll: true,
            poll: 500, // interval in ms
            // enables polling mode for watching
            // must be used on filesystems that doesn't notify on change
            // i. e. nfs shares
        },

    }
};`

**Comment by Mouvedia** [comment]
Is there a fix that doesn't involve using browserslist?

**Comment by leoseccia** [comment]
I had this problem too and after spending a day messing around with babel, I fixed it by changing the way I imported these (and don't use babel at all):
```
import Inline from 'quill/blots/Inline';
import ReactQuill from 'react-quill';
```

to:
```
import ReactQuill, {Quill} from 'react-quill';
let Inline = Quill.import('blots/inline');
```

**Comment by Mouvedia** [comment]
.

**Comment by Mouvedia** [comment]
> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

**Comment by DeMoorJasper** [comment]
This will get fixed in Parcel 2

**Comment by Mouvedia** [comment]
@DeMoorJasper last alpha release was in November of last year.

Do you have an idea of when Parcel will be stable?
Is it already fixed in the alpha?

**Comment by DeMoorJasper** [comment]
@Mouvedia we currently do not have a timeline on when a stable Parcel 2 version will be out, we are however working on a list of features/bugfixes that are required to get it to stable so we can focus on getting it out asap without focusing too much on improvements and features we can add-on afterwards.

I think it should be fixed in the current alpha, not entirely sure.

**Comment by marlonicus** [comment]
To anyone arriving here having this problem with TypeScript and Parcel, you probably just need to add the following to your `tsconfig.json` to fix the issue:

```
{
  "compilerOptions": {
    "target": "esnext"
  }
}
```
