### ISSUE TITLE
`ENOENT no such file or directory, open 'parcel/packages/runtimes/js/src/runtime-0b0f0826e994744b.js`

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#8392]
# 🐛 bug report

Codeframes generated for runtime assets cannot be printed and cause a `ENOENT` readFile error as which also prevent the original error of the codeframe to not be displayed at all.

## 🤔 Expected Behavior

Correct codeframe, but at the very least no error

The errors and filecontents that are hidden by the ENOENT problem:
```
##### parcel/packages/runtimes/js/src/runtime-81c42a3e30b1a42e.js:
module.exports =
  (__parcel__import__("./" +require('./helpers/bundle-manifest').resolve("4GllE"))).then(() => parcelRequire('4pa9y'));

##### parcel/packages/runtimes/js/src/runtime-0b0f0826e994744b.js:
require('./helpers/bundle-manifest').register(JSON.parse("{\"7ysn3\":\"index.js\",\"4GllE\":\"async.e6005160.js\"}"));


@parcel/transformer-js: Conditional or non-top-level `require()` call. This causes the resolved module and all dependendencies to be wrapped.
  parcel/packages/runtimes/js/src/runtime-0b0f0826e994744b.js:1:1

@parcel/transformer-js: Conditional or non-top-level `require()` call. This causes the resolved module and all dependendencies to be wrapped.
  parcel/packages/runtimes/js/src/runtime-81c42a3e30b1a42e.js:1:45
```

## 😯 Current Behavior

```
[Error: ENOENT: no such file or directory, open 'parcel/packages/runtimes/js/src/runtime-0b0f0826e994744b.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'parcel/packages/runtimes/js/src/runtime-0b0f0826e994744b.js'
}
```

## 💁Solution

1. Investigate why `codeframe.code` is not set for these runtimes (runtimes are the major reason why that property exists in the first place) and fix that
2. As a precaution, handle a missing file here gracefully (and just set `code` to null/undefined):
https://github.com/parcel-bundler/parcel/blob/9e2d5d0d60d08d65b5ae6cd765c907a8753bbf39/packages/core/utils/src/prettyDiagnostic.js#L63-L66

## 💻 Code Sample

Any project using dynamic imports, which causes the runtime assets shown above to be generated. Then running with `parcel build --log-level verbose` to generate these warnings.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 9e2d5d0d60d08d65b5ae6cd765c907a8753bbf39

**Comment by harshgandhi-1999** [comment]
Hello I am new to open source . May I take this issue?
