### ISSUE TITLE
Can stable@0.1.8 be abolished for @parcel/optimizer-svgo

### ISSUE THREAD

**Issue by Black-Jay** [parcel-bundler/parcel#8394]
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/46087015/184190361-a81c1890-382b-4c4f-8a4c-f3671591352b.png">

**Comment by mischnic** [comment]
```
$ yarn why stable
=> Found "stable@0.1.8"
info Reasons this module exists
   - "parcel#@parcel#config-default#@parcel#optimizer-htmlnano#svgo" depends on it
   - Hoisted from "parcel#@parcel#config-default#@parcel#optimizer-htmlnano#svgo#stable"
```

You should report this to svgo:
https://github.com/svg/svgo/blob/a9834efa1603198ae606765292215462ae193d0d/package.json#L113

But technically, svgo supports `"node": ">=10.13.0"`, and it only became stable in Node 12

**Comment by InsidiousForce** [comment]
quick note, svgo 3.0.0+ removes the dependency and only supports node >= 14

**Comment by XhmikosR** [comment]
Someone needs to update cssnano to v6.x which updates svgo to v3.x in order for this warning to be gone.
