### ISSUE TITLE
Full Parcel logo?

### ISSUE THREAD

**Issue by ericapisani** [parcel-bundler/parcel#8395]
# 🙋 feature request

An SVG logo with both the word 'parcel' and the box icon (like what's seen on the project website) that works for both light and dark themed websites.

## 😯 Current Behavior

The Parcel logo that I was able to find within the project only has the word ['parcel' and is missing the box](https://github.com/parcel-bundler/parcel/blob/v2/packages/utils/create-react-app/templates/default/src/parcel/logo.svg)

## 🔦 Context

The Netlify team is hoping to use this logo as part of some enhancements we're making to the [framework detection utility](https://github.com/netlify/framework-info/) that we maintain. We have the logo with just the word 'parcel' in there at the moment  (what I linked above) but are hoping to use the full one instead if possible.

**Comment by mischnic** [comment]
We have some existing assets here:
- https://github.com/parcel-bundler/assets
- https://github.com/parcel-bundler/website/tree/v2/src/assets

Do these work for you? We don't really have a box+name asset, they're separate elements even on https://parceljs.org/ or on the top left here: https://parceljs.org/docs/

**Comment by ericapisani** [comment]
> We don't really have a box+name asset, they're separate elements even on https://parceljs.org/ or on the top left here: https://parceljs.org/docs/

Ah ok, I didn't realize that the desire was to treat them (the logo and the name) as distinct things rather than both of them used together as the official logo.

Yeah those assets work for us, thank you for the links! We're currently using what's in the top left of the Parcel docs (just the [name](https://github.com/netlify/framework-info/blob/main/assets/logos/parcel/default.svg), no icon), but given the context in which this logo is likely to be used, I think the icon would work better (and there's an SVG that can be used in the links that you provided).

If there's a preference on the Parcel team's end for us to use the name rather than the icon let us know, happy to leave it as is/revert back to just the name.

**Comment by mischnic** [comment]
I suspect this is exposed somewhere in the Netlify frontend? Would be great if you post an example of what that looks like (if that project is already being deployed), but for example here it's also just the Parcel logo: https://bundlers.tooling.report/

**Comment by ericapisani** [comment]
> I suspect this is exposed somewhere in the Netlify frontend?

Yes, but the timeline for when the logos will be exposed there is yet to be determined, and we don't have any existing logic for me to give a concrete example to you at the moment unfortunately. 

I'm willing to speculate at the moment though that the context in which they would be rendered would lead the logos to be rendered on the smaller to medium size of things (similar to the bundlers tooling link you shared).

**Comment by mischnic** [comment]
No worries, I was just curious!
