### ISSUE TITLE
export symbols from asset doesn't contain CJS exports

### ISSUE THREAD

**Issue by wardpeet** [parcel-bundler/parcel#8400]
# 🐛 bug report

`asset.symbols` doesn't contain CJS exports
```
module.exports = {};
```

## 🎛 Configuration (.babelrc, package.json, cli command)

Base configuration

## 🤔 Expected Behavior

I'm expecting to get an AssetSymbol of module.exports and exports when using CJS modules. 

## 😯 Current Behavior

Empty array of symbols

## 💁 Possible Solution

I don't think module.exports are being collected. So my question would be, is this by design? If not I'm happy to do the work

**Comment by mischnic** [comment]
`module.exports` gets mapped to the `*` symbol (which all CJS assets have, regardless of whether they declare exports or not). Only `module.exports.foo = ` become named symbols (`foo`).

[Example](https://parcel2-repl.vercel.app/#JTdCJTIyZmlsZXMlMjIlM0ElNUIlNUIlMjIlMkZzcmMlMkZpbmRleC5qcyUyMiUyQyU3QiUyMnZhbHVlJTIyJTNBJTIyY29uc3QlMjB4JTIwJTNEJTIwcmVxdWlyZSglNUMlMjIuJTJGb3RoZXIuanMlNUMlMjIpJTNCJTVDbmNvbnNvbGUubG9nKHgpJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlNUIlMjIlMkZzcmMlMkZvdGhlci5qcyUyMiUyQyU3QiUyMnZhbHVlJTIyJTNBJTIybW9kdWxlLmV4cG9ydHMlMjAlM0QlMjAlN0IlN0QlM0IlNUNuJTIyJTdEJTVEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmVudHJpZXMlMjIlM0ElNUIlNUQlMkMlMjJtaW5pZnklMjIlM0FmYWxzZSUyQyUyMnNjb3BlSG9pc3QlMjIlM0F0cnVlJTJDJTIyc291cmNlTWFwcyUyMiUzQWZhbHNlJTJDJTIycHVibGljVXJsJTIyJTNBJTIyJTJGX19yZXBsX2Rpc3QlMjIlMkMlMjJ0YXJnZXRUeXBlJTIyJTNBJTIyYnJvd3NlcnMlMjIlMkMlMjJ0YXJnZXRFbnYlMjIlM0FudWxsJTJDJTIyb3V0cHV0Rm9ybWF0JTIyJTNBbnVsbCUyQyUyMmhtciUyMiUzQWZhbHNlJTJDJTIybW9kZSUyMiUzQSUyMnByb2R1Y3Rpb24lMjIlMkMlMjJyZW5kZXJHcmFwaHMlMjIlM0ElMjJzeW1ib2xzJTIyJTJDJTIydmlld1NvdXJjZW1hcHMlMjIlM0FmYWxzZSUyQyUyMmRlcGVuZGVuY2llcyUyMiUzQSU1QiU1RCUyQyUyMm51bVdvcmtlcnMlMjIlM0EwJTdEJTJDJTIydXNlVGFicyUyMiUzQWZhbHNlJTJDJTIyYnJvd3NlckNvbGxhcHNlZCUyMiUzQSU1QiU1RCUyQyUyMnZpZXdzJTIyJTNBJTVCJTIyJTJGc3JjJTJGaW5kZXguanMlMjIlMkMlMjIlMkZzcmMlMkZvdGhlci5qcyUyMiUyQyUyMk9wdGlvbnMlMjIlNUQlMkMlMjJjdXJyZW50VmlldyUyMiUzQTIlN0Q=)

<img width="605" alt="Bildschirmfoto 2022-08-16 um 23 52 46" src="https://user-images.githubusercontent.com/4586894/184991854-e8cabff4-989e-434a-9e9a-3d9be157b270.png">


Why is this a problem/what are you trying to achieve?
