### ISSUE TITLE
"import" of "@swc/helpers" in bundle that was built as commonjs library

### ISSUE THREAD

**Issue by picoderman** [parcel-bundler/parcel#8401]
# 🐛 bug report

There is extra "import" line in the code that was builded as commonjs

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json:
```json
{
  "name": "test",
  "version": "1.0.0",
  "scripts": {
    "build": "parcel build"
  },
  "engines": {
    "node": ">= 10"
  },
  "outputFormat": "commonjs",
  "source": "src/root.ts",
  "main": "dist/root.js",
  "dependencies": {
    "@swc/helpers": "^0.4.6",
    "typeorm": "^0.3.7"
  },
  "devDependencies": {
    "@types/node": "^18.7.6",
    "typescript": "^4.7.4",
    "parcel": "^2.7.0"
  }
}
```

## 🤔 Expected Behavior

I want to have code with commonjs imports only

## 😯 Current Behavior

There is extra `"import"` line after `require()` imports:
```js
require("@swc/helpers/lib/_ts_decorate.js");
var $3SimY$typeorm = require("typeorm");

import "33dff249418cd8b5:@swc/helpers/lib/_ts_decorate.js:esm";

let $33dff249418cd8b5$var$Data = class Data {
};
(0, $33dff249418cd8b5$import$53e81b1faa576921$2e2bcd8739ae039)([
    (0, $3SimY$typeorm.Column)()
], $33dff249418cd8b5$var$Data.prototype, "prop", void 0);
$33dff249418cd8b5$var$Data = (0, $33dff249418cd8b5$import$53e81b1faa576921$2e2bcd8739ae039)([
    (0, $3SimY$typeorm.Entity)()
], $33dff249418cd8b5$var$Data);




//# sourceMappingURL=root.js.map

```

## 💁 Possible Solution

🤔 

## 🔦 Context

I want to run my bundled code with nodejs without enabling esmodules

## 💻 Code Sample

src/mmm.ts:
```js
import { Column, Entity } from 'typeorm';

@Entity()
class Data {
  @Column()
  prop: number;
}

```

src/root.ts:
```js
import './mmm';
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0
| Node             | 12.22.10
| Yarn         |  1.22.17
| Operating System | MacOS 12.5, M1

**Comment by magnnus** [comment]
Related #8413

**Comment by mischnic** [comment]
Appears to be working with 2.8.3
