### ISSUE TITLE
Checking optional exports with truthyness gives `does not export`

### ISSUE THREAD

**Issue by wherget** [parcel-bundler/parcel#8407]
# 🐛 bug report

Some packages (emotion, material-ui) try to support multiple upstream library versions (react) by checking for exported symbols as follows:

```js
import * as other from './other.js';

const maybeFoo = other['foo']; // expecting 'undefined' when export is missing
if (maybeFoo) { maybeFoo() }
```

Parcel (somewhat justifiably) errors out with

```
error: src/other.js does not export 'foo'
```

## 🤔 Expected Behavior

The libraries to compile with parcel.

## 😯 Current Behavior

e.g. (for preact 10.10.3 and material-ui 5.10.1)
```
@parcel/core: node_modules/preact/compat/dist/compat.module.js does not export 'useId'

  node_modules/@mui/utils/esm/useId.js:21:25
    20 | 
  > 21 | const maybeReactUseId = React['useId' + ''];
  >    |                         ^^^^^^^^^^^^^^^^^^^
    22 | /**
    23 |  *
```

See also: [Failing](https://parcel2-repl-mischnic.vercel.app/#JTdCJTIyZmlsZXMlMjIlM0ElNUIlNUIlMjIlMkZzcmMlMkZpbmRleC5qcyUyMiUyQyU3QiUyMnZhbHVlJTIyJTNBJTIyaW1wb3J0JTIwKiUyMGFzJTIwb3RoZXIlMjBmcm9tJTIwJy4lMkZvdGhlci5qcyclM0IlNUNuJTVDbmNvbnN0JTIwbWF5YmVCYXIlMjAlM0QlMjBvdGhlciU1QidiYXInJTVEJTNCJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwdXNlQmFyKCklMjAlN0IlMjAlNUNuJTIwJTIwaWYlMjAobWF5YmVCYXIpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMG1heWJlQmFyJTNCJTVDbiUyMCUyMCU3RCU1Q24lMjAlMjByZXR1cm4lMjAlNUMlMjJlbXVsYXRlZCUyMGJhciU1QyUyMiUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyU1QiUyMiUyRnNyYyUyRm90aGVyLmpzJTIyJTJDJTdCJTIydmFsdWUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMGZvbyUyMCUzRCUyMCU1QyUyMmJhciU1QyUyMiUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCU1RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJlbnRyaWVzJTIyJTNBJTVCJTVEJTJDJTIybWluaWZ5JTIyJTNBZmFsc2UlMkMlMjJzY29wZUhvaXN0JTIyJTNBdHJ1ZSUyQyUyMnNvdXJjZU1hcHMlMjIlM0FmYWxzZSUyQyUyMnB1YmxpY1VybCUyMiUzQSUyMiUyRl9fcmVwbF9kaXN0JTIyJTJDJTIydGFyZ2V0VHlwZSUyMiUzQSUyMmJyb3dzZXJzJTIyJTJDJTIydGFyZ2V0RW52JTIyJTNBbnVsbCUyQyUyMm91dHB1dEZvcm1hdCUyMiUzQW51bGwlMkMlMjJobXIlMjIlM0FmYWxzZSUyQyUyMm1vZGUlMjIlM0ElMjJwcm9kdWN0aW9uJTIyJTJDJTIycmVuZGVyR3JhcGhzJTIyJTNBZmFsc2UlMkMlMjJ2aWV3U291cmNlbWFwcyUyMiUzQWZhbHNlJTJDJTIyZGVwZW5kZW5jaWVzJTIyJTNBJTVCJTVEJTJDJTIybnVtV29ya2VycyUyMiUzQTAlN0QlMkMlMjJ1c2VUYWJzJTIyJTNBZmFsc2UlMkMlMjJicm93c2VyQ29sbGFwc2VkJTIyJTNBJTVCJTVEJTJDJTIydmlld3MlMjIlM0ElNUIlMjIlMkZzcmMlMkZpbmRleC5qcyUyMiUyQyUyMiUyRnNyYyUyRm90aGVyLmpzJTIyJTVEJTJDJTIyY3VycmVudFZpZXclMjIlM0ExJTdE) Vercel repro.

## 💁 Possible Solution

Guarding the import like

```js
const maybeFoo = ('foo' in other) ? other['foo'] : undefined;
```

obviously produces the desired result. [(Vercel repro)](https://parcel2-repl-mischnic.vercel.app/#JTdCJTIyZmlsZXMlMjIlM0ElNUIlNUIlMjIlMkZzcmMlMkZpbmRleC5qcyUyMiUyQyU3QiUyMnZhbHVlJTIyJTNBJTIyaW1wb3J0JTIwKiUyMGFzJTIwb3RoZXIlMjBmcm9tJTIwJy4lMkZvdGhlci5qcyclM0IlNUNuJTVDbmNvbnN0JTIwbWF5YmVCYXIlMjAlM0QlMjAoJ2JhciclMjBpbiUyMG90aGVyKSUyMCUzRiUyMG90aGVyJTVCJ2JhciclNUQlMjAlM0ElMjB1bmRlZmluZWQlM0IlNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjB1c2VCYXIoKSUyMCU3QiUyMCU1Q24lMjAlMjBpZiUyMChtYXliZUJhciklMjAlN0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwbWF5YmVCYXIlM0IlNUNuJTIwJTIwJTdEJTVDbiUyMCUyMHJldHVybiUyMCU1QyUyMmVtdWxhdGVkJTIwYmFyJTVDJTIyJTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTVCJTIyJTJGc3JjJTJGb3RoZXIuanMlMjIlMkMlN0IlMjJ2YWx1ZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwZm9vJTIwJTNEJTIwJTVDJTIyYmFyJTVDJTIyJTNCJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmVudHJpZXMlMjIlM0ElNUIlNUQlMkMlMjJtaW5pZnklMjIlM0FmYWxzZSUyQyUyMnNjb3BlSG9pc3QlMjIlM0F0cnVlJTJDJTIyc291cmNlTWFwcyUyMiUzQWZhbHNlJTJDJTIycHVibGljVXJsJTIyJTNBJTIyJTJGX19yZXBsX2Rpc3QlMjIlMkMlMjJ0YXJnZXRUeXBlJTIyJTNBJTIyYnJvd3NlcnMlMjIlMkMlMjJ0YXJnZXRFbnYlMjIlM0FudWxsJTJDJTIyb3V0cHV0Rm9ybWF0JTIyJTNBbnVsbCUyQyUyMmhtciUyMiUzQWZhbHNlJTJDJTIybW9kZSUyMiUzQSUyMnByb2R1Y3Rpb24lMjIlMkMlMjJyZW5kZXJHcmFwaHMlMjIlM0FmYWxzZSUyQyUyMnZpZXdTb3VyY2VtYXBzJTIyJTNBZmFsc2UlMkMlMjJkZXBlbmRlbmNpZXMlMjIlM0ElNUIlNUQlMkMlMjJudW1Xb3JrZXJzJTIyJTNBMCU3RCUyQyUyMnVzZVRhYnMlMjIlM0FmYWxzZSUyQyUyMmJyb3dzZXJDb2xsYXBzZWQlMjIlM0ElNUIlNUQlMkMlMjJ2aWV3cyUyMiUzQSU1QiUyMiUyRnNyYyUyRmluZGV4LmpzJTIyJTJDJTIyJTJGc3JjJTJGb3RoZXIuanMlMjIlNUQlMkMlMjJjdXJyZW50VmlldyUyMiUzQTElN0Q=)

Disabling scope hoisting [(Vercel repro)](https://parcel2-repl-mischnic.vercel.app/#JTdCJTIyZmlsZXMlMjIlM0ElNUIlNUIlMjIlMkZzcmMlMkZpbmRleC5qcyUyMiUyQyU3QiUyMnZhbHVlJTIyJTNBJTIyaW1wb3J0JTIwKiUyMGFzJTIwb3RoZXIlMjBmcm9tJTIwJy4lMkZvdGhlci5qcyclM0IlNUNuJTVDbmNvbnN0JTIwbWF5YmVCYXIlMjAlM0QlMjBvdGhlciU1QidiYXInJTVEJTNCJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwdXNlQmFyKCklMjAlN0IlMjAlNUNuJTIwJTIwaWYlMjAobWF5YmVCYXIpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMG1heWJlQmFyJTNCJTVDbiUyMCUyMCU3RCU1Q24lMjAlMjByZXR1cm4lMjAlNUMlMjJlbXVsYXRlZCUyMGJhciU1QyUyMiUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyU1QiUyMiUyRnNyYyUyRm90aGVyLmpzJTIyJTJDJTdCJTIydmFsdWUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMGZvbyUyMCUzRCUyMCU1QyUyMmJhciU1QyUyMiUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCU1RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJlbnRyaWVzJTIyJTNBJTVCJTVEJTJDJTIybWluaWZ5JTIyJTNBZmFsc2UlMkMlMjJzY29wZUhvaXN0JTIyJTNBZmFsc2UlMkMlMjJzb3VyY2VNYXBzJTIyJTNBZmFsc2UlMkMlMjJwdWJsaWNVcmwlMjIlM0ElMjIlMkZfX3JlcGxfZGlzdCUyMiUyQyUyMnRhcmdldFR5cGUlMjIlM0ElMjJicm93c2VycyUyMiUyQyUyMnRhcmdldEVudiUyMiUzQW51bGwlMkMlMjJvdXRwdXRGb3JtYXQlMjIlM0FudWxsJTJDJTIyaG1yJTIyJTNBZmFsc2UlMkMlMjJtb2RlJTIyJTNBJTIycHJvZHVjdGlvbiUyMiUyQyUyMnJlbmRlckdyYXBocyUyMiUzQWZhbHNlJTJDJTIydmlld1NvdXJjZW1hcHMlMjIlM0FmYWxzZSUyQyUyMmRlcGVuZGVuY2llcyUyMiUzQSU1QiU1RCUyQyUyMm51bVdvcmtlcnMlMjIlM0EwJTdEJTJDJTIydXNlVGFicyUyMiUzQWZhbHNlJTJDJTIyYnJvd3NlckNvbGxhcHNlZCUyMiUzQSU1QiU1RCUyQyUyMnZpZXdzJTIyJTNBJTVCJTIyJTJGc3JjJTJGaW5kZXguanMlMjIlMkMlMjIlMkZzcmMlMkZvdGhlci5qcyUyMiUyQyUyMk9wdGlvbnMlMjIlNUQlMkMlMjJjdXJyZW50VmlldyUyMiUzQTIlN0Q=) also works around this issue, but is obviously not desirable for a production build.

Webpack (from https://github.com/webpack/webpack/issues/14814) has `strictExportPresence` as a toggle.

## 🔦 Context

Maybe someone with more insight into what the expected behaviour would be could chime in. I like that parcel detects this as a possible import problem, but OTOH I feel like expecting `undefined` for a missing (or, well, undefined) export isn't too unrealistic an expectation.

Possibly related: #7867 (which does not occur in my project (emotion 11.10, preact 10.10), so I'm submitting this as a different issue.)

At the end of the day, I just want my project to build. 😅

**Comment by wherget** [comment]
another similar pattern I just came across (in https://github.com/ariakit/ariakit) is

```js
const maybeFoo = typeof other["foo"] === "function" ? other["foo"] : undefined;
```

which seems redundant (as in, if it's not a function, it's probably `undefined`) to me?

**Comment by mischnic** [comment]
> Guarding the import like obviously produces the desired result.

To explain what's going on here: For better tree shaking, Parcel treats
```js
import * as other from './other.js';
console.log(other.foo);
```
as
```js
import {foo} from './other.js';
console.log(foo);
```
This is only possible as long as `other` is used only for member expressions, so adding `console.log(other)` would prevent this optimization and therefore also prevents the `does not export error` (and similarly your `"x" in other` check)

A big reason why we want to support this even for computed member expressions (`other["foo"]`) is that it makes using CSS modules easier, where you would do `styles["my-class"]` which isn't possible with the `other.foo` syntax.

> Possibly related: https://github.com/parcel-bundler/parcel/issues/7867

Yeah, that's the same problem.

**Comment by wherget** [comment]
Oh yes, I see how this is important for optimizing css modules, even better that it works for computed expressions. While I personally think that `"x" in other` would be a sensible check to add upstream for these "dependency might not export symbol" situations, I might be among a minority with that sentiment.

Do you think it might be useful to check if the member expression is used in a truthyness or type check somewhere down the tree, i.e. where `undefined` might be a valid value? Possibly with a warning that such an access downgrades export checking. I mean, it's always hard to say what users might do in the real world, but my gut feeling is that those would infrequently occur on css modules. 

Theoretically, you could even prune away pure calls resulting from such a check at compile time, as we'd **know** the export is missing. Right?

**Comment by sytabaresa** [comment]
Hi everyone! I have a workaround of this problem when you cannot modify the pattern, for example in a library.

I had the same issue with `Jotai`:
```
🚨 Build failed.

@parcel/core: /node_modules/preact/compat/dist/compat.module.js does not export 'use'

  /node_modules/jotai/react.js:26:11
    25 | };
  > 26 | var use = ReactExports.use || function (promise) {
  >    |           ^^^^^^^^^^^^^^^^
    27 |   if (promise.status === 'pending') {
    28 |     throw promise;

error Command failed with exit code 1.
```

So, I take advantage of file alias system that parcel uses, so an alias entry to file needs to be created:

package.json:
```json
  "..."
    "alias": {
        "react": "./preact.js",
        "react-dom": "preact/compat",
        "..."
    }
```

and the file has this content:
```js
// preact.js
import preact from "preact/compat"
export * from "preact/compat"
export const use = false // I use false here to define the symbol AND exit the if-else or ||  pattern
export default preact
```
That's all. Parcel compiles without the need to deactivate scope hoisting!

**Comment by bartrail** [comment]
@sytabaresa thanks for the update! Is there anything I can do with regular react to get `react-select` running using the alias trick? I already tried a bit but failed quite hard with nothing working at all.
