### ISSUE TITLE
node:path is not bundled for the browser when outputFormat is esmodule or global

### ISSUE THREAD

**Issue by aminya** [parcel-bundler/parcel#8409]
# 🐛 bug report

I am using `is-path-inside` in my package that uses `node:path`. But when I try to bundle it for the browser it fails with this error:

```js
@parcel/packager-js: External modules are not supported when building for browser

patha/node_modules/.pnpm/is-path-inside@4.0.0/node_modules/is-path-inside/index.js:1:18
  > 1 | import path from 'node:path';
  >   |                  ^^^^^^^^^^^
    2 | 
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
  "main.browser": "./dist/browser/index.js",
  "source": "./src/index.ts",
  "browser": {
    "path": "./node_modules/path-browserify",
    "process": "./node_modules/process"
  },
  "targets": {
    "main.browser": {
      "context": "browser",
      "engines": {
        "browsers": "> 0.5%"
      },
      "optimize": true,
      "includeNodeModules": true,
      "outputFormat": "global",
      "isLibrary": true
    }
  },
```

```
parcel build --target main.browser
```

## 🤔 Expected Behavior

`global` should bundle `node:path` similar to `esmodule` or `commonjs`

## 🔦 Context

Might be related to #8049 

## 💻 Code Sample

https://github.com/aminya/patha/pull/5

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.6.2
| Node             |  16
| npm/Yarn         | pnpm
| Operating System | Ubuntu 22

**Comment by aminya** [comment]
If the output format is `esmodule`, it doesn't error out, but it just copy-pastes `node:path` into the final bundle without doing anything about it.

**Comment by devongovett** [comment]
It's due to `isLibrary`:

https://github.com/parcel-bundler/parcel/blob/cbc84b0c1d538b0ec15a3bf01f95da3ed623ebbb/packages/utils/node-resolver-core/src/NodeResolver.js#L721-L727

This setting is not meant to work with the `global` output format. You should either switch to commonjs or esmodule, or remove `isLibrary`.

**Comment by aminya** [comment]
But I want to make a library for the browser users. If I remove `isLibrary` then the functions are not properly exported.

> You should either switch to commonjs or esmodule, or remove isLibrary.

I have switched to esmodule, but node:path is not still bundled. That's why my Deno integration test fails.

https://github.com/aminya/patha/runs/7936632445?check_suite_focus=true#step:8:41

**Comment by aminya** [comment]
It is not fixed yet.

**Comment by String10** [comment]
Face similar issue while bundling a project depending on `axios`. Parcel just writes `require ("buffer")` to the output even I set true to `includeNodeModules` in targets. Besides, I set type `commonjs` but nothing else in `package.json`.

It seems that parcel doesn't include the packages to the output file which are not just under the folder `node_modules` but in node cache.
