### ISSUE TITLE
Error: The specified module could not be found. \\?\E:\Bilal\Bootcamp2020\gatsby-contentful-blogsite\node_modules\@parcel\source-map\parcel_sourcemap_node\artifacts\index.win32-x64-msvc.node

### ISSUE THREAD

**Issue by Muhammad-Bilal90** [parcel-bundler/parcel#8410]
i am using gatsby and when I try to run "gatsby develop" for runing my app it throws the following error

E:\Bilal\Bootcamp2020\gatsby-contentful-blogsite\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

Error: The specified module could not be found.
\\?\E:\Bilal\Bootcamp2020\gatsby-contentful-blogsite\node_modules\@parcel\source-map\parcel_sourcemap_node\artifacts\index.win32-x64-msvc.node
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1210:18)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (E:\Bilal\Bootcamp2020\gatsby-contentful-blogsite\node_modules\@parcel\source-map\parcel_sourcemap_node\index.js:15:18)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (E:\Bilal\Bootcamp2020\gatsby-contentful-blogsite\node_modules\@parcel\source-map\dist\node.js:14:18)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32) {
  code: 'ERR_DLOPEN_FAILED'
}

**Comment by mischnic** [comment]
Try this: https://github.com/parcel-bundler/parcel/issues/7104#issuecomment-967260755

**Comment by Muhammad-Bilal90** [comment]
> Try this: [#7104 (comment)](https://github.com/parcel-bundler/parcel/issues/7104#issuecomment-967260755)

Thank You so much it's working fine now.

**Comment by srcnalt** [comment]
Installing the `VC_redist.x64.exe` did not help me in this case. Interesting this was working a week ago while I was working on the project however now it fails with the error.

```
> parcel build index.html

Error: Cannot find module './artifacts/index.win32-ia32-msvc.node'
Require stack:
- ...\node_modules\@parcel\source-map\parcel_sourcemap_node\index.js
- ...\node_modules\@parcel\source-map\dist\node.js
- ...\node_modules\@parcel\utils\lib\index.js
- ...\node_modules\@parcel\core\lib\public\Config.js
- ...\node_modules\@parcel\core\lib\utils.js
- ...\node_modules\@parcel\core\lib\public\Environment.js
- ...\node_modules\@parcel\core\lib\public\Asset.js
- ...\node_modules\@parcel\core\lib\Parcel.js
- ...\node_modules\@parcel\core\lib\index.js
- ...\node_modules\parcel\lib\cli.js
- ...\node_modules\parcel\lib\bin.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (...\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (...\node_modules\@parcel\source-map\parcel_sourcemap_node\index.js:15:18)
    at Module._compile (...\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '...\\node_modules\\@parcel\\source-map\\parcel_sourcemap_node\\index.js',
    '...\\node_modules\\@parcel\\source-map\\dist\\node.js',
    '...\\node_modules\\@parcel\\utils\\lib\\index.js',
    '...\\node_modules\\@parcel\\core\\lib\\public\\Config.js',
    '...\\node_modules\\@parcel\\core\\lib\\utils.js',
    '...\\node_modules\\@parcel\\core\\lib\\public\\Environment.js',
    '...\\node_modules\\@parcel\\core\\lib\\public\\Asset.js',
    '...\\node_modules\\@parcel\\core\\lib\\Parcel.js',
    '...\\node_modules\\@parcel\\core\\lib\\index.js',
    '...\\node_modules\\parcel\\lib\\cli.js',
    '...\\node_modules\\parcel\\lib\\bin.js'
  ]
}
```

How the artifacts folder looks:
<img width="185" alt="image" src="https://user-images.githubusercontent.com/3163281/224812194-591930b1-1472-4e4f-a66e-2db2f886b558.png">

---

Downgrading to node 18.15.0 from latest helped me.

**Comment by cooperate** [comment]
Having this same issue - except I don't have an ./artifacts folder as it's a clean project.

**Comment by abd123codes** [comment]
i am having this same issue while trying to run gatsby develop, alos i have another error when i run gatsby new. could you help me

**Comment by Muhammad-Bilal90** [comment]
The issue is because the package is failing due to a missing library on the
computer. fs-search requires Microsoft Visual C++ 2015 Redistributable
(x64).

You can get the download here ->
https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by abd123codes** [comment]
am still getting the error. i get this error whenever i run gatsby new. it displays after av set the project folder name, and initial settings, javascritp etc. after typing in yes for the shall we do this?, it shows this error                    

- Cloning site templateC:\Users\adams\AppData\Roaming\npm\node_modules\gatsby-cli\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

TypeError: Xi.cursorTo is not a function
    at Timeout._onTimeout (C:\Users\adams\AppData\Roaming\npm\node_modules\gatsby-cli\node_modules\create-gatsby\lib\index.js:5:854)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)

Node.js v18.15.0

**Comment by SiderFace** [comment]
I have a similar error, but not identical.  It is not solved with the ' Microsoft Visual C++ 2015 Redistributable
(x64). ' download.

Mine gives this error code:
Error: Cannot find module './artifacts/index.win32-ia32-msvc.node'

I assume it is referring to this folder:
' C:\..\@parcel\source-map\parcel_sourcemap_node\artifacts\ '

But the ' Error: Cannot find module ' ./artifacts/index.win32-ia32-msvc.node ' does not exist there.  I cant find it anywhere online.  All the files in this directory say "x64" or "arm64".

Why is my parcel trying to target this "ia32" that seems to not exist ?

**Comment by banjobyster** [comment]
> I have a similar error, but not identical. It is not solved with the ' Microsoft Visual C++ 2015 Redistributable (x64). ' download.
> 
> Mine gives this error code: Error: Cannot find module './artifacts/index.win32-ia32-msvc.node'
> 
> I assume it is referring to this folder: ' C:..@parcel\source-map\parcel_sourcemap_node\artifacts\ '
> 
> But the ' Error: Cannot find module ' ./artifacts/index.win32-ia32-msvc.node ' does not exist there. I cant find it anywhere online. All the files in this directory say "x64" or "arm64".
> 
> Why is my parcel trying to target this "ia32" that seems to not exist ?

I am facing the same problem. Have you found a solution?

**Comment by SiderFace** [comment]
> > I have a similar error, but not identical. It is not solved with the ' Microsoft Visual C++ 2015 Redistributable (x64). ' download.
> > Mine gives this error code: Error: Cannot find module './artifacts/index.win32-ia32-msvc.node'
> > I assume it is referring to this folder: ' C:..@parcel\source-map\parcel_sourcemap_node\artifacts\ '
> > But the ' Error: Cannot find module ' ./artifacts/index.win32-ia32-msvc.node ' does not exist there. I cant find it anywhere online. All the files in this directory say "x64" or "arm64".
> > Why is my parcel trying to target this "ia32" that seems to not exist ?
> 
> I am facing the same problem. Have you found a solution?

Not yet.  But I have a couple networks of people to keep working with on it.  Several have been stumped already, but will circle back as they get free time to help.  Lets keep each other posted until one of us solves it.

For now, consider with me what the best theory i, so far.  node is creating some/all of the "node_modules" as a 32-bit version, OR node is acting like a 32-bit version.  The latter is more likely because that is when it makes those files, that, if you follow them to their destination all have some sort of "64" aspect to their file name(s).  The folder in question ("...artifacts") would want to have a bunch of files with "32" in them to satisfy what the error code is saying it is missing and needs.  But that problem is a double-sided because I am (and probably you too) working with a 64-bit system.  The node is a 64-bit version (with certainty, as I've totally uninstalled and reinstalled several times).  The execution of parcel shouldn't create any instances of needing files designed to operate on 32-bit systems.  So that brings me back to the original logic: something is inherently wrong with parcel.  I have tried countless combinations of different versions of parcel and parcel-bundler with both version of node.  PATH variables are double-checked every time.  Further support of this suspicion is that 2 veteran devs who've looked in on my problem have said they know of some recent changes to parcel and parcel-bundler.
So, I believe there is a problem with how the parcel unpacks itself in the node_modules folder.  that being said, there doesn't seem to be anywhere on parcel's website, or anywhere else on the net that I can just manually set up that folder myself with the correct files.  Most notably, this specific "missing" file (let alone the whole folder).  With a file/OS specific problem like this, that would typically be the best way to solve it: tediously populating the appropriate folders wtih teh appropriate files.  But no google searches seem to show any acknowledgement that this file even exists.

We seem to have a rare error and/or one that is only just occurring for people :(
As frustrating as it is, we could take some real pride in solving it, and then having the solution out there for people, by having a distinct post syntax that will make others' able to easily find the solution via web search.

Good luck and keep me posted if you have any progress.  Maybe my theories, thus far, can trigger some revelation for you.

**Comment by banjobyster** [comment]
> > > I have a similar error, but not identical. It is not solved with the ' Microsoft Visual C++ 2015 Redistributable (x64). ' download.
> > > Mine gives this error code: Error: Cannot find module './artifacts/index.win32-ia32-msvc.node'
> > > I assume it is referring to this folder: ' C:..@parcel\source-map\parcel_sourcemap_node\artifacts\ '
> > > But the ' Error: Cannot find module ' ./artifacts/index.win32-ia32-msvc.node ' does not exist there. I cant find it anywhere online. All the files in this directory say "x64" or "arm64".
> > > Why is my parcel trying to target this "ia32" that seems to not exist ?
> > 
> > 
> > I am facing the same problem. Have you found a solution?
> 
> Not yet. But I have a couple networks of people to keep working with on it. Several have been stumped already, but will circle back as they get free time to help. Lets keep each other posted until one of us solves it.
> 
> For now, consider with me what the best theory i, so far. node is creating some/all of the "node_modules" as a 32-bit version, OR node is acting like a 32-bit version. The latter is more likely because that is when it makes those files, that, if you follow them to their destination all have some sort of "64" aspect to their file name(s). The folder in question ("...artifacts") would want to have a bunch of files with "32" in them to satisfy what the error code is saying it is missing and needs. But that problem is a double-sided because I am (and probably you too) working with a 64-bit system. The node is a 64-bit version (with certainty, as I've totally uninstalled and reinstalled several times). The execution of parcel shouldn't create any instances of needing files designed to operate on 32-bit systems. So that brings me back to the original logic: something is inherently wrong with parcel. I have tried countless combinations of different versions of parcel and parcel-bundler with both version of node. PATH variables are double-checked every time. Further support of this suspicion is that 2 veteran devs who've looked in on my problem have said they know of some recent changes to parcel and parcel-bundler. So, I believe there is a problem with how the parcel unpacks itself in the node_modules folder. that being said, there doesn't seem to be anywhere on parcel's website, or anywhere else on the net that I can just manually set up that folder myself with the correct files. Most notably, this specific "missing" file (let alone the whole folder). With a file/OS specific problem like this, that would typically be the best way to solve it: tediously populating the appropriate folders wtih teh appropriate files. But no google searches seem to show any acknowledgement that this file even exists.
> 
> We seem to have a rare error and/or one that is only just occurring for people :( As frustrating as it is, we could take some real pride in solving it, and then having the solution out there for people, by having a distinct post syntax that will make others' able to easily find the solution via web search.
> 
> Good luck and keep me posted if you have any progress. Maybe my theories, thus far, can trigger some revelation for you.

I'll keep you posted on my progress and any findings I come across. If you have any additional thoughts or ideas, please do share them.

**Comment by banjobyster** [comment]
> > > I have a similar error, but not identical. It is not solved with the ' Microsoft Visual C++ 2015 Redistributable (x64). ' download.
> > > Mine gives this error code: Error: Cannot find module './artifacts/index.win32-ia32-msvc.node'
> > > I assume it is referring to this folder: ' C:..@parcel\source-map\parcel_sourcemap_node\artifacts\ '
> > > But the ' Error: Cannot find module ' ./artifacts/index.win32-ia32-msvc.node ' does not exist there. I cant find it anywhere online. All the files in this directory say "x64" or "arm64".
> > > Why is my parcel trying to target this "ia32" that seems to not exist ?
> > 
> > 
> > I am facing the same problem. Have you found a solution?
> 
> Not yet. But I have a couple networks of people to keep working with on it. Several have been stumped already, but will circle back as they get free time to help. Lets keep each other posted until one of us solves it.
> 
> For now, consider with me what the best theory i, so far. node is creating some/all of the "node_modules" as a 32-bit version, OR node is acting like a 32-bit version. The latter is more likely because that is when it makes those files, that, if you follow them to their destination all have some sort of "64" aspect to their file name(s). The folder in question ("...artifacts") would want to have a bunch of files with "32" in them to satisfy what the error code is saying it is missing and needs. But that problem is a double-sided because I am (and probably you too) working with a 64-bit system. The node is a 64-bit version (with certainty, as I've totally uninstalled and reinstalled several times). The execution of parcel shouldn't create any instances of needing files designed to operate on 32-bit systems. So that brings me back to the original logic: something is inherently wrong with parcel. I have tried countless combinations of different versions of parcel and parcel-bundler with both version of node. PATH variables are double-checked every time. Further support of this suspicion is that 2 veteran devs who've looked in on my problem have said they know of some recent changes to parcel and parcel-bundler. So, I believe there is a problem with how the parcel unpacks itself in the node_modules folder. that being said, there doesn't seem to be anywhere on parcel's website, or anywhere else on the net that I can just manually set up that folder myself with the correct files. Most notably, this specific "missing" file (let alone the whole folder). With a file/OS specific problem like this, that would typically be the best way to solve it: tediously populating the appropriate folders wtih teh appropriate files. But no google searches seem to show any acknowledgement that this file even exists.
> 
> We seem to have a rare error and/or one that is only just occurring for people :( As frustrating as it is, we could take some real pride in solving it, and then having the solution out there for people, by having a distinct post syntax that will make others' able to easily find the solution via web search.
> 
> Good luck and keep me posted if you have any progress. Maybe my theories, thus far, can trigger some revelation for you.

For now, my problems have been solved by downgrading to node 16.

**Comment by okwedavid** [comment]
I downgraded to 16 but yet mine isn't working.

**Comment by okwedavid** [comment]
> > > > I have a similar error, but not identical. It is not solved with the ' Microsoft Visual C++ 2015 Redistributable (x64). ' download.
> > > > Mine gives this error code: Error: Cannot find module './artifacts/index.win32-ia32-msvc.node'
> > > > I assume it is referring to this folder: ' C:..@parcel\source-map\parcel_sourcemap_node\artifacts\ '
> > > > But the ' Error: Cannot find module ' ./artifacts/index.win32-ia32-msvc.node ' does not exist there. I cant find it anywhere online. All the files in this directory say "x64" or "arm64".
> > > > Why is my parcel trying to target this "ia32" that seems to not exist ?
> > > 
> > > 
> > > I am facing the same problem. Have you found a solution?
> > 
> > Not yet. But I have a couple networks of people to keep working with on it. Several have been stumped already, but will circle back as they get free time to help. Lets keep each other posted until one of us solves it.
> > 
> > For now, consider with me what the best theory i, so far. node is creating some/all of the "node_modules" as a 32-bit version, OR node is acting like a 32-bit version. The latter is more likely because that is when it makes those files, that, if you follow them to their destination all have some sort of "64" aspect to their file name(s). The folder in question ("...artifacts") would want to have a bunch of files with "32" in them to satisfy what the error code is saying it is missing and needs. But that problem is a double-sided because I am (and probably you too) working with a 64-bit system. The node is a 64-bit version (with certainty, as I've totally uninstalled and reinstalled several times). The execution of parcel shouldn't create any instances of needing files designed to operate on 32-bit systems. So that brings me back to the original logic: something is inherently wrong with parcel. I have tried countless combinations of different versions of parcel and parcel-bundler with both version of node. PATH variables are double-checked every time. Further support of this suspicion is that 2 veteran devs who've looked in on my problem have said they know of some recent changes to parcel and parcel-bundler. So, I believe there is a problem with how the parcel unpacks itself in the node_modules folder. that being said, there doesn't seem to be anywhere on parcel's website, or anywhere else on the net that I can just manually set up that folder myself with the correct files. Most notably, this specific "missing" file (let alone the whole folder). With a file/OS specific problem like this, that would typically be the best way to solve it: tediously populating the appropriate folders wtih teh appropriate files. But no google searches seem to show any acknowledgement that this file even exists.
> > 
> > We seem to have a rare error and/or one that is only just occurring for people :( As frustrating as it is, we could take some real pride in solving it, and then having the solution out there for people, by having a distinct post syntax that will make others' able to easily find the solution via web search.
> > 
> > Good luck and keep me posted if you have any progress. Maybe my theories, thus far, can trigger some revelation for you.
> 
> For now, my problems have been solved by downgrading to node 16.

I downgraded to 16 but yet mine isn't working
