### ISSUE TITLE
HMR is console.clear()'ing, which made it look like it wasn't working

### ISSUE THREAD

**Issue by web3d0** [parcel-bundler/parcel#8412]
# 🐛 bug report

## 🎛 Configuration (cli command)

```sh
parcel watch --no-autoinstall *.html
```

## 🤔 Expected Behavior

Works fine, except for HMR clearing the console every time it is triggered.

## 😯 Current Behavior

It should not clear the console. If I wanted that, I can insert the clearing into module.hot.accept().

## 💁 Possible Solution

Take out the console.clear() from HMR.

## 🔦 Context

When the console clears, it looks like a refresh rather than an updated continuation. So I spent all day trying to force it to only update changed code, until I realised it was changing the code and HMR was working.

**Comment by DarrenDanielDay** [comment]
Currently I hacked `console.clear` to disable this:

```html
<script>
console.clear = () => {};
</script>
```

Clearing the console in HMR updates makes it more difficult to debug the HMR code. I think there should be an option to disable this behavior for HMR plugin developers. Is there any guide for that?
