### ISSUE TITLE
[bug] "import" instead of "require()" with SWC helper in CJS bundle files

### ISSUE THREAD

**Issue by TechQuery** [parcel-bundler/parcel#8413]
@parcel-bundler

### `package.json`

```json
{
    "source": "source/index.ts",
    "types": "dist/index.d.ts",
    "main": "dist/index.js",
    "module": "dist/index.esm.js",
    "dependencies": {
        "@swc/helpers": "^0.4.6",
    },
    "devDependencies": {
        "@parcel/packager-ts": "^2.7.0",
        "@parcel/transformer-typescript-types": "^2.7.0",
        "parcel": "^2.7.0",
        "typescript": "~4.7.4"
    },
    "browserslist": "> 0.5%, last 2 versions, not dead",
    "targets": {
        "main": {
            "optimize": true
        }
    },
    "scripts": {
        "build": "rm -rf dist/  &&  parcel build"
    }
}
```

### `tsconfig.json`

```json
{
    "compilerOptions": {
        "module": "umd",
        "moduleResolution": "node",
        "esModuleInterop": true,
        "downlevelIteration": true,
        "lib": ["ES2021", "DOM", "DOM.Iterable"],
        "declaration": true,
        "skipLibCheck": true,
        "outDir": "dist/"
    },
    "include": ["source/**/*"]
}
```

## 🤔 Expected Behavior

Work well with other bundlers such as webpack based framework CLIs (Next.js etc.).

### Error message

> SyntaxError: Cannot use import statement outside a module

### Bundle result

There're several `import` statements in CJS files as shown below:

```js
import"8a6534942d6704f4:@swc/helpers/lib/_define_property.js:esm";
```

## 🔦 Context

https://cdn.jsdelivr.net/npm/koajax@0.8.1/dist/index.js

## 💻 Code Sample

EasyWebApp/KoAJAX@4a55ab7

## 🌍 Your Environment

| Software         | Version(s)          |
| ---------------- | ------------------- |
| Parcel           | 2.7.0               |
| Node             | 14.19.1             |
| PNPM             | 7.9.3               |
| Operating System | Windows 10 Pro 21H2 |

**Comment by TechQuery** [comment]
@mischnic If I downgrade Parcel `2.7.0` to `2.6.2`, the building succeed with a warning:

```text
@parcel/transformer-typescript-types: Cannot find module './index.module.less' or its corresponding type declarations.     
```

Reproduce codes is in idea2app/Idea-React@74e7fb1 & EasyWebApp/KoAJAX@0359f9a.

**Comment by magnnus** [comment]
I meet the same issue. 

I found it maybe related to the parcel **version**( and @parcel/* packages) and `browserslist` config.

**Comment by mischnic** [comment]
Should be fixed now, similar to https://github.com/parcel-bundler/parcel/issues/8401
