### ISSUE TITLE
prevent parcel changing variable and classes names it effect PostgreSQL column names

### ISSUE THREAD

**Issue by Mvurog** [parcel-bundler/parcel#8415]
# 🐛 bug report

I want to prevent parcel changing variable and classes names because it effect PostgreSQL column names as showing below

![image](https://user-images.githubusercontent.com/78096134/186252194-22a3a3dc-3e14-4f0d-8447-0617476ef869.png)

## 🎛 Configuration (.babelrc, package.json, cli command)

I used the Parcel API (@parcel/core)

```js
const bundler = new Parcel({
	config: "./script/parcel/config.json",
	entries: "lib/source/main.ts",
	shouldContentHash: false,
	defaultTargetOptions: {
		outputFormat: "commonjs",
		distDir: "dist",
		sourceMaps: true,
		shouldOptimize: false, // *
		shouldScopeHoist: false, // *
	},
	additionalReporters: [
		{
			packageName: "@parcel/reporter-cli",
			resolveFrom: import.meta.url,
		}
	],
	mode: development ? "development" : "production",
	env: {
		mode: development ? "development" : "production",
	},
	cacheDir: "cache",
});
```

config.json
```json
{
  "extends": "@parcel/config-default",
  "resolvers": [
    "parcel-resolver-tspaths",
    "..."
  ],
  "transformers": {
    "*.{ts}": [
      "@parcel/transformer-typescript-tsc"
    ]
  },
  "validators": {
    "*.{ts}": [
      "@parcel/validator-typescript"
    ]
  }
}
```

## 🤔 Expected Behavior

the column name should be `userUid`

## 😯 Current Behavior

the column name is `$19b689e40a74a507$export$1f44aaf2ec115b54Uid`

## 💁 Possible Solution

disable hashing, what i have tried 

```js
shouldOptimize: false,
shouldScopeHoist: false,
```

didn't work

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  @parcel/config-default: 2.7.0 , @parcel/core: 2.7.0
| Node             | v16.16.0
| npm/Yarn         | npm 8.17.0
| Operating System | windows 11

**Comment by mischnic** [comment]
That is a bug. Please provide your source code, just the file that contains `userUid` is probably enough.

**Comment by Mvurog** [comment]
the code is huge so I'm gonna upload it to gist.
https://gist.github.com/Mvurog/1d2fca15ce8a4b804f200c9feb511078

the `userUid` is auto generated from sequelize associations somehow.

**Comment by mischnic** [comment]
That code doesn't help unfortunately. Please look at the generated code which contains the problematic `19b689e40a74a507$export$1f44aaf2ec115b54Uid` to figure out which source file it's coming from

**Comment by Mvurog** [comment]
the issue very simple, i have model class `User` and also another one called `Topic`, when i tell sequelize that `User` has many `Topic`, he will use `User` class name and use the primary key which is Uid and merge it to be `UserUid`, so if i look up to the hash key i will see the class model, that why it has `Uid` at the end


so if there's no solution how i can disable hashing?

**Comment by Mvurog** [comment]
i used webpack.
