### ISSUE TITLE
How to watch full node_modules to support monorepo development?

### ISSUE THREAD

**Issue by mahoshojoHCG** [parcel-bundler/parcel#8418]
# 💬 RFC

We are working on a monorepo project recently migrated from webpack to parcel. And when we run `parcel serve` and change some files in other project, which are soft linked to `node_modules`, it didn't trigger a rebuild.

## 🔦 Context

According to the docs, parcel does watch `node_modules`. I created a project and noticed that after I install a package with package manager, parcel rebuilt. But changing some file in `node_modules` won't trigger rebuild.

I guess there are some limits on watching `node_modules`, such as parcel only watches sub folders of `node_modules`. 

Normally we shouldn't change `node_modules` contents manually, but working on monorepo definitely requires. Is there an option for parcel to watch full `node_modules`?

**Comment by Germey** [comment]
See https://github.com/parcel-bundler/parcel/issues/4332

Parcel does watch parent or sibling folders and other folders using symlink. Means that Parcel does not work well with MonoRepo...

Option1: Migrate to Parcel v1
Option2: Don't use Parcel anymore
Option3: Start another watcher for other folders then trigger auto save files in app folder, like the walk around solution mentioned in that issue.

**Comment by mischnic** [comment]
Parcel watches everything (including node_modules) inside the project root (= the monorepo root = the folder containing the lockfile). So consuming other packages in the same monorepo works fine. For packages linked in from outside the monorepo, see https://github.com/parcel-bundler/parcel/issues/4332.

Does that explain the behaviour you're seeing?
