### ISSUE TITLE
Suggest putting script tag in head and use defer html attribute

### ISSUE THREAD

**Issue by selfup** [parcel-bundler/parcel#842]
Hello! I would like to make a 🙋 feature request (if that's what we can call it) for the README.

### 🤔 Expected Behavior

Since Parcel is all about performance, suggesting the most performant way to load in JS can help 😄 

### 😯 Current Behavior

Currently:

```html
<html>
<body>
  <script src="./index.js"></script>
</body>
</html>
```

This loads in the JS once the body has been created.

### 💁 Possible Solution

```html
<html>
<head>
  <script defer src="./index.js"></script>
</head>
<body>
</body>
</html>
```

This will load in the JS and then execute it once the DOM has loaded (avoiding the need for 'DOMContentLoaded').

### 🔦 Context

Once apps get quite large (even code splitting won't necessarily solve the initial load), being able to asynchronously pull in JS while the page loads can shave down time!

**If this sounds like a good idea, I will go ahead and make a PR** 🙏 

### 💻 Code Sample

See **Possible Solution** above 🚀

Also I am using it here: https://github.com/selfup/hyperapp-one-parcel/blob/master/src/index.html#L3

And this is the resulting build for the HTML:

```html
<html> <head> <script defer="" src="d4641e58e2f3cd4891ec718a8741e366.js"></script> <link rel="stylesheet" href="d4641e58e2f3cd4891ec718a8741e366.css"></head> <body> <div id="app"></div> </body> </html> 
```

### 🌍 Your Environment

This _shouldn't_ be needed, but let me know if I need to!

**Comment by mischnic** [comment]
We can't just turn `<script>` into `<script defer>` automatically, because someone might actually need the first case. So this has to be done one a boilerplate/docs level.

**Comment by selfup** [comment]
Makes sense. Thanks for taking a look!
