### ISSUE TITLE
Redux toolkit query isn't compatible with parcel

### ISSUE THREAD

**Issue by mauriciolcs** [parcel-bundler/parcel#8420]
# 🐛 bug report

When i use redux toolkit query, the build occurs normally, but  i get this error on script load

![image](https://user-images.githubusercontent.com/33501188/186904592-3d4fa592-6c1b-4951-a002-00162bb3a928.png)

## 🎛 Configuration (.babelrc)

```js
{
  "plugins": ["babel-plugin-styled-components"]
}
```

## 🤔 Expected Behavior

The script should be load normally and fetch data with rtk query

## 😯 Current Behavior

Throw an error on script load

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.5
| Node             | 14.20.0
| Yarn         | 1.22.19
| Operating System | macOs Monterey 12.5

**Comment by mischnic** [comment]
>  Parcel 1.12.5

Parcel 1 isn't supported anymore.
