### ISSUE TITLE
SVGO and React Responsive Carousel

### ISSUE THREAD

**Issue by tadstr** [parcel-bundler/parcel#8426]
# 🐛 bug report
Error when running yarn build
@parcel item doesn't belong to list

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    "jsx:*.svg": [
      "...",
      "@parcel/transformer-svg-react"
    ],
    "svg:*": [
      "..."
    ]
  },
  "optimizers": {
    "data-url:*": [
      "...",
      "@parcel/optimizer-data-url"
    ]
  }
}
```

## 🤔 Expected Behavior

I should be able to use a carousel with svg

## 😯 Current Behavior

@parcel item doesn't belong to list

## 💁 Possible Solution

Something about svgo does not support external css

**Comment by mischnic** [comment]
Please provide a code sample that reproduces the issue and describe the error in more detail
