### ISSUE TITLE
ts validator for jest

### ISSUE THREAD

**Issue by cangSDARM** [parcel-bundler/parcel#8427]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
![image](https://user-images.githubusercontent.com/20441896/187162980-e344617e-0e8b-4381-9073-eafcdc0ed268.png)

.parcelrc
```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{js,mjs,jsx,cjs}": [
      "@parcel/transformer-js",
      "@parcel/transformer-react-refresh-wrap"
    ],
    "*.{ts,tsx}": [
      "@parcel/transformer-typescript-tsc",
      "@parcel/transformer-js",
      "@parcel/transformer-react-refresh-wrap"
    ]
  },
  "validators": {
    "*.{ts,tsx}": [
      "@parcel/validator-typescript"
    ]
  }
}
```

.babelrc
```json
{
  "presets": [
    "@babel/preset-env",
    ["@babel/preset-react", { "runtime": "automatic" }],
    "@babel/preset-typescript"
  ]
}
```

## 🤔 Expected Behavior

Ignore test files at compile time. *Those files should be treated as unreferenced dead code and should be tree shaken*.

## 😯 Current Behavior
I followed [guide](https://parceljs.org/languages/javascript/#usage-with-other-tools), and [searched for result](https://github.com/parcel-bundler/parcel/discussions/7881), but not work for me.

**jest works fine**, but not good for the project. It raise those error:

![image](https://user-images.githubusercontent.com/20441896/187163322-53b7877c-901d-481c-83fb-b79d03ad57f6.png)

Seems like parcel is trying to compile my test file and throws up a bunch of errors.

I tried to change `.parcelrc` to this (test in: https://www.digitalocean.com/community/tools/glob?comments=true&glob=%2A%2A%2F%21%28%2A.test%29.%7Bjs%2Cmjs%2Cjsx%2Ccjs%7D&matches=false&tests=%2Fwork.js&tests=%2Fwork.test.js&tests=%2Fxs%2Fwork.js&tests=%2Fxs%2Fwork.test.tsx):
```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "**/!(*.test).{js,mjs,jsx,cjs}": [
      "@parcel/transformer-js",
      "@parcel/transformer-react-refresh-wrap"
    ],
    "**/!(*.test).{ts,tsx}": [
      "@parcel/transformer-typescript-tsc",
      "@parcel/transformer-js",
      "@parcel/transformer-react-refresh-wrap"
    ]
  },
  "validators": {
    "**/!(*.test).{ts,tsx}": [
      "@parcel/validator-typescript"
    ]
  }
}
```
also cannot work, same errors.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.7.0
| Node             | 14.17.6
| npm/Yarn         | 6.14.11
| Operating System | win10

**Comment by cangSDARM** [comment]
I tested it, and simply deleting the validator for ts worked, so it didn't seem to involve tree shaking. But this is not what I wanted

**Comment by maxburs** [comment]
I encountered the same issue. Adding include + exclude properties to the tsconfing solved this for my team: 
<img width="747" alt="image" src="https://user-images.githubusercontent.com/8890312/191836939-f48121d5-7272-4c79-833d-382655f8d0e9.png">
