### ISSUE TITLE
No multiple CSS are generated for multiple targets

### ISSUE THREAD

**Issue by TheBojda** [parcel-bundler/parcel#8446]
# 🐛 bug report

My package.json contains multiple client targets, one for dynamic Vue rendering, and one for SSR. The package.json looks like this:

```
...
"targets": {
    "client": {
      "source": [
        "./src/client/index.ts",
        "./src/client/index_ssr.ts"
      ],
      "distDir": "./dist/client",
      "context": "browser"
    }, 
   ... 
  },
...

```
The problem is only one index.css is generated, no index_ssr.css is generated for the SSR part. If I delete index.ts source, then index_ssr.css is generated.

## 🤔 Expected Behavior

Two separate CSS should be generated. One for index.ts, and another for index_ssr.ts.

**Comment by mischnic** [comment]
You should use two different targets (with a single source each) instead.

**Comment by TheBojda** [comment]
The result is the same (only index.css is generated) with this config:

```
"targets": {
    "client": {
      "source": "./src/client/index.ts",
      "distDir": "./dist/client",
      "context": "browser"
    },
    "client_ssr": {
      "source": "./src/client/index_ssr.ts",
      "distDir": "./dist/client",
      "context": "browser"
    },
```
