### ISSUE TITLE
🐛Compile time error

### ISSUE THREAD

**Issue by ascoders** [parcel-bundler/parcel#845]
### 🤔 Expected Behavior

⏳  Building factory.js...
✨  Built in 35.12s.

built/bundle/index.js     ⚠️  1.6 MB    29.56s
built/bundle/index.css       363 KB       5.56s

### 😯 Current Behavior

⏳  Building factory.js...
✨  Built in 35.12s.

built/bundle/index.js     ⚠️  1.6 MB    1003.21s
built/bundle/index.css       363 KB       5.56s

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.1
| Node             | 8.1.3
| npm/Yarn         | npm
| Operating System | macos

**Comment by DeMoorJasper** [comment]
The total build time is the actual time parcel ran.
The breakdown is the time of each asset processing combined + packaging time per bundle. So the difference is due to parcel using workers.

Total build time = all bundle times / amount of workers

**Comment by ascoders** [comment]
@DeMoorJasper you can reappear this problem:

```shell
git clone https://github.com/gaeajs/gaea-site.git
cd gaea-site
npm i
npm run build
```

**Comment by DeMoorJasper** [comment]
That's strange if i use your example repo and change the build command to:
`parcel build ./src/pages/index.tsx --detailed-report`
And it fixes itself to 5seconds

Not sure but it appears to be caused by `pri` Not sure what it does either as it has no extended docs or repo
