### ISSUE TITLE
🐛"window is not defined" in code added by parcel, in web worker

### ISSUE THREAD

**Issue by ranfdev** [parcel-bundler/parcel#846]
🐛 bug report

### 🤔 Expected Behavior

parcel should'nt call ```window``` in web workers.
I didn't have any problem in parcel 1.5.1.

### 😯 Current Behavior
```Uncaught ReferenceError: window is not defined``` in code added by parcel (in my code i don't have any reference to the ```window``` object.

 I tracked down the error to this piece of code: 
```js

var parent = module.bundle.parent;
if ((!parent || !parent.isParcelRequire) && typeof WebSocket !== 'undefined') {
  var hostname = '' || location.hostname;
  var protocol = window.location.protocol === 'https:' ? 'wss' : 'ws';
  var ws = new WebSocket(protocol + '://' + hostname + ':' + '33277' + '/');
  ws.onmessage = function (event) {
    var data = JSON.parse(event.data);

    if (data.type === 'update') {
      data.assets.forEach(function (asset) {
        hmrApply(global.require, asset);
      });

      data.assets.forEach(function (asset) {
        if (!asset.isNew) {
          hmrAccept(global.require, asset.id);
        }
      });
    }

    if (data.type === 'reload') {
      ws.close();
      ws.onclose = function () {
        location.reload();
      };
    }

    if (data.type === 'error-resolved') {
      console.log('[parcel] ✨ Error resolved');
    }

    if (data.type === 'error') {
      console.error('[parcel] 🚨  ' + data.error.message + '\n' + 'data.error.stack');
    }
  };
}
```
As you can see, there is a line where parcel looks for the window object.

### 💁 Possible Solution
Change the call to the Worker scope location object.

### 🔦 Context

I'm trying to import a module inside a webworker

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.1
| Node             | 9.5.0
| npm/Yarn         | yarn 1.3.2
| Operating System | elementary os 0.4.1

**Comment by ranfdev** [comment]
I'm trying to solve the error, i will do a pr when i finish

**Comment by zababurinsv** [comment]
i have this problem too

**Comment by XSPGMike** [comment]
is there a solution to this issue?
