### ISSUE TITLE
Parcel segmentation fault on MacOS

### ISSUE THREAD

**Issue by ashleydavis** [parcel-bundler/parcel#8462]
# 🐛 bug report

I have an example of Parcel that causes a segmentation fault on MacOS.

It has been confirmed on two separate MacOS laptops running OS versions 12.4 and 12.5.1.

The problem cannot be reproduced on Windows or Ubuntu Linux.

## 🎛 Configuration

I'm using Pnpm to create a workspace that shares one package into the Parcel package. 

The symbolic link that Pnpm creates could be related to the problem. 

See below for reproduction of the issue.

## 🤔 Expected Behavior

Running `pnpm start` should produce a "Hello world" web page (this is the behavior on Windows and Ubuntu Linux).

## 😯 Current Behavior

Running `pnpm start` on MacOS results in a crash and this message:

```bash
zsh: segmentation fault  pnpm start
```

Running `npm start` also results in a crash on MacOS.

## 💁 Possible Solution

Possibly related to the symbolic link from one package to the other. See my workaround below.

## 🔦 Context

I've created a multi-package monorepo ([see the full repo here](https://github.com/data-forge-notebook/editor-core)) where I'm sharing packages within the monorepo between web pages. This has been working for the past 9 months or so nicely on Windows. When I tried to recently get the project to start on MacOS though I noticed the crash.

I've cut back my project substantially to demonstrate the problem: https://github.com/ashleydavis/parcel-crash

I have a workaround for now that should allow me to move forward. But it seems significant that there was a crash so I thought I'd report it and preserve the evidence until someone has time to look at it.

## My workaround

The crash can be avoided by editing packages/host-bridge/package.json and changing the value of "main" from "build/index.js" to "src/index.ts".

This isn't an ideal fix to the problem, but it should keep me moving forward and it might be a clue as to what's causing the crash.

## 💻 Code Sample

https://github.com/ashleydavis/parcel-crash

## Reproduction

Install pnpm:

```bash
npm install -g pnpm
```

Install deps, compile TypeScript to JavaScript, then run Parcel:

```bash
git clone https://github.com/ashleydavis/parcel-crash.git
cd parcel-crash
pnpm install
pnpm run compile
pnpm start
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.7.9
| Node             |v16.16.0 and v18.9.0
| pnpm        |7.11.0
| Operating System |MacOS 12.4 and 12.5.1

**Comment by mischnic** [comment]
Fixed by https://github.com/parcel-bundler/source-map/issues/103
