### ISSUE TITLE
In-SCSS calls to url() that don't resolve have confusing error message at run-time

### ISSUE THREAD

**Issue by davidhariri** [parcel-bundler/parcel#8464]
# 🐛 bug report
1. Define some styles that have incorrect relative references to static files
```scss
/* path should have been ./static/Remove.svg */
mask-image: url("../../static/Remove.svg");
```

2. Some component import's the styles:
```tsx
// ...
import "./styles.scss";

function myComponent(): JSX.Element {
// ...
```

3. At run time Parcel throws up an error (in-browser):
```
Cannot find module './styles.scss'
```
This error confused me for hours because it looks like a problem with module delcarations etc., but it's actually a problem with the incorrect `url()` reference _within_ the module.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// package.json
"dependencies": {
      "@parcel/transformer-react-refresh-wrap": "^2.0.1",
      "ace-builds": "^1.4.13",
      "add": "^2.0.6",
      "axios": "^0.24.0",
      "lodash": "^4.17.21",
      "react": "^17.0.2",
      "react-ace": "^9.5.0",
      "react-dom": "^17.0.2",
      "react-flow-renderer": "^9.6.11",
      "react-query": "^3.39.1",
      "react-router-dom": "6",
      "slate": "^0.81.1",
      "slate-history": "^0.66.0",
      "slate-react": "^0.81.0",
      "swr": "^1.3.0"
  },
  "scripts": {
      "start": "parcel src/index.html",
      "build": "parcel build src/index.html"
  },
  "devDependencies": {
      "@parcel/transformer-sass": "^2.7.0",
      "caniuse-lite": "^1.0.30001393",
      "parcel": "^2.7.0",
      "prettier": "2.7.1",
      "process": "^0.11.10"
  }
```

## 🤔 Expected Behavior

Should compile properly and have 404s in the browser or throw up a clear Parcel error message about the broken paths in the scss file.

## 😯 Current Behavior

See above

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0
| Node             | 18.3.0
| npm/Yarn         | 8.11.0
| Operating System | macOS Monterey

**Comment by mischnic** [comment]
This is what I get with both Parcel 2.8 and 2.7.0:

```
@parcel/core: Failed to resolve '../Remove.svg' from './index.scss'

  /.../index.scss:2:2
    1 | body {
  > 2 |   mask-image: url("../Remove.svg");
  >   |   ^
    3 | }
    4 |

@parcel/resolver-default: Cannot load file '../Remove.svg' in './'.
```
