### ISSUE TITLE
config-webextension Content Script Css has wrong urls

### ISSUE THREAD

**Issue by ritinkar8** [parcel-bundler/parcel#8474]
# 🐛 bug report

Whenever content scripts are compiled,  if the css has a local font import the url of the font in the compiled version is wrong.

So the fonts fail to load.

## 🎛 Configuration (.babelrc, package.json, cli command)

default babel config

## 🤔 Expected Behavior

The font src urls in content script should be prepended with `chrome-extension://__MSG_@@extension_id__/` as below.
Otherwise the browser will try to load them from the host in which the content script is running rather than the local fonts.

```
@font-face {
  font-family: primeicons;
  font-display: block;
  src: url(chrome-extension://__MSG_@@extension_id__/primeicons.33112b83.eot);
  src: url(chrome-extension://__MSG_@@extension_id__/primeicons.33112b83.eot#iefix) format("embedded-opentype"),
    url(chrome-extension://__MSG_@@extension_id__/primeicons.272612de.ttf) format("truetype"),
    url(chrome-extension://__MSG_@@extension_id__/primeicons.485a914f.woff) format("woff"),
    url(chrome-extension://__MSG_@@extension_id__/primeicons.44bc222d.svg#primeicons) format("svg");
  font-weight: 400;
  font-style: normal;
}
```

## 😯 Current Behavior

```
@font-face {
  font-family: primeicons;
  font-display: block;
  src: url(primeicons.33112b83.eot);
  src: url(primeicons.33112b83.eot#iefix) format("embedded-opentype"),
    url(primeicons.272612de.ttf) format("truetype"),
    url(primeicons.485a914f.woff) format("woff"),
    url(primeicons.44bc222d.svg#primeicons) format("svg");
  font-weight: 400;
  font-style: normal;
}
```
The browser is trying to load them from the host. Like, if the content script is running in "example.com" then it tries to load "example.com/primeicons.485a914f.woff"

## 💁 Possible Solution

Prepend the url with `chrome-extension://__MSG_@@extension_id__/` for content scripts.

## 🔦 Context

The fonts don't load.

currently I'm using `sed` to patch it after parcel has finished its bundling.

## 💻 Code Sample

Input css

```
@font-face {
    font-family: 'primeicons';
    font-display: block;
    src: url('./fonts/primeicons.eot');
    src: url('./fonts/primeicons.eot?#iefix') format('embedded-opentype'), url('./fonts/primeicons.ttf') format('truetype'), url('./fonts/primeicons.woff') format('woff'), url('./fonts/primeicons.svg?#primeicons') format('svg');
    font-weight: normal;
    font-style: normal;
}
```

It was inside a library in `node_modules`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |   2.7.0
| Node             |    16.15.1
| npm/Yarn         |  1.22.15
| Operating System | macos

**Comment by louisgv** [comment]
At the moment, parcel provides the full URL in js runtime by a try/catch hack (that uses the error to trace where the url came from). I think for css it doesn't really do anything atm, so it might be possible to inject the MSG string mentioned.

For me, I bundles the font file as data-base64 instead. Try out this example (plasmo uses parcel2 underneath): https://github.com/PlasmoHQ/examples/tree/main/with-content-scripts-ui

There's a font.css file that import a font in-lined into the content script, which worked.

**Comment by ritinkar8** [comment]
The problem that I faced while inlining the font as base64 is that it gets blocked by CSP, for example here on github.
