### ISSUE TITLE
HMR causes syntax errors on browsers not supporting dynamic imports

### ISSUE THREAD

**Issue by porst17** [parcel-bundler/parcel#8476]
# 🐛 bug report

I have to support older browsers (namely Chrome 56) that lack support for dynamic imports. However, since HMR seems to rely on dynamic imports, loading the site through Parcel's dev server triggers the error `Uncaught SyntaxError: Unexpected token import` and the remainder of my JS code is not executed.

I could disable HMR using the `--no-hmr` CLI option, but this would also disable it for newer browsers supporting dynamic imports slowing down development and testing.

## 🤔 Expected Behavior

- Web browser supports dynamic imports: HMR works as usual
- Web browser does not support dynamic imports: A warning appears in the console and HMR is disabled or replaced with a `window.location.reload()`.

## 😯 Current Behavior

On web browsers without support for dynamic imports (tested with Chrome 56), script execution stops with the following error message: `Uncaught SyntaxError: Unexpected token import`.

## 💁 Possible Solution

Feature detect dynamic imports similar to
```HTML
<script>
let hasDynamicImport = false;
let oldOnError = window.onError;
window.onerror = function(e) {
  console.log("Dynamic imports not supported. Downgrading HMR to full page reloads.");
  return true; // Prevents the (possible) syntax error form appearing in the console
}
</script>
<script>
import('data:text/javascript;base64,Cg==');
hasDynamicImport = true;
</script>
<script>
window.onerror = oldOnError;
// use hasDynamicImport to decide how to handle HMR requests
</script>
```
There are other ways to feature-detect dynamic imports that don't need several script tags, but they all involve `eval()` or `new Function()` AFAIK.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0 |
| Node             | 16.13.2 |
| npm/Yarn         | 8.4.1 |
| Operating System | macOS |

**Comment by mischnic** [comment]
https://github.com/parcel-bundler/parcel/blob/v2/packages/runtimes/hmr/src/loaders/hmr-runtime.js uses `eval` anyway, so maybe we could just put the `import()` into an eval with a try-catch

**Comment by porst17** [comment]
Yes, that would probably do it. Do you aim for a full page reload as a fallback or a no-op?

**Comment by mischnic** [comment]
We already have a codepath that uses `<script>` tags for loading the update (to get correct sourcemaps), so it should still work fine: https://github.com/parcel-bundler/parcel/blob/828a845e3adad12fd95041bed6ea5fc9d625870e/packages/runtimes/hmr/src/loaders/hmr-runtime.js#L339-L349

**Comment by foxt** [comment]
Just ran into this issue. It took some figuring out to realise that this is a HMR issue rather than just compilation not working correctly.
