### ISSUE TITLE
Bundler-default fails on production build when using normal and url: imports

### ISSUE THREAD

**Issue by sznowicki** [parcel-bundler/parcel#8480]
# 🐛 bug report

I notice many people complain on "missing module" in production build. I finally made a repro repo that proves there's something wrong with modules registry during prod build, but only in default bundler. Experimental works fine.

We observe this issue for some time, def. somewhere after 2.0.0 but it was something that comes and goes and I couldn't really make a reliable repro repo, also given that the project we've been observing this is massive and has many many variables that could impact it.

Now I finally got it, details how to reproduce it you'll find in the  README:

https://github.com/sznowicki/repro-repo-dynamic-imports/tree/parcel-bundler-missing-module

However, long story short: 

When one file is importing a package, that imports another package (in this case with dynamic imports), and another file is importing this package but via `url:package-name`, then on production build the website will throw errors everywhere due to missing imports.

Somehow bundler get's confused and even those the `xyz` module is indeed bundled, it fails to recognise it in many places.

## 🎛 Configuration (.babelrc, package.json, cli command)

Repro repo has everything.

## 💁 Possible Solution

I believe it must be some race condition or something similar in the internal parcel modules registry. 

## 🔦 Context

It was pretty sad to go back from vacation to figure out my main product doesn't work, after one commit was pushed with no apparent reason how this commit would impact the bundle.

Lessons learned: no matter what bundler is used, always check if website runs during CI/CD.

**Comment by devongovett** [comment]
You mentioned in your comment on #5683 that the issue is fixed when using `@parcel/bundler-experimental`. This will become the default very soon, so I think we can just wait until then. Going to close as a duplicate.

**Comment by sznowicki** [comment]
I still saw some related problems when using `lazy` with import in an non direct way like this:

```
const LazyComponent = ({ importer }) => {
   const Component = lazy(importer);
   return <Suspense ...><Component /></Suspense>
};

const callerImporter = () => import('./some-component.jsx');
const Caller = () => <LazyComponent importer={callerImporter} />
```

However I didn't figure out yet whether it may be bundler or some magic `lazy` potentially does in between.

I'll update my repro repo if I find something useful.


Also I start to miss the times when `require` was the only de-facto standard ;)
