### ISSUE TITLE
No transformers found for Duck.gltf or Duck.glb

### ISSUE THREAD

**Issue by donnyfe** [parcel-bundler/parcel#8482]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🤔 Expected Behavior

I hope parcel can transformer files .gltf、.glb when import threejs  files 

## 😯 Current Behavior

build errors

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/9570544/190861016-c71836d6-0f4e-4fac-9a54-9540710341e6.png">

## 💻 Code Sample

```js
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
const gltfLoader = new GLTFLoader()
gltfLoader.load(
//'../assets/models/Duck/glTF-Binary/Duck.glb',
  require('./assets/models/Duck/glTF-Draco/Duck.gltf')
 )

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.7.0
| Node             |  15.x
| npm/Yarn         | 7.24 
| Operating System |  macOS bigSur 11.6

**Comment by mischnic** [comment]
See https://parceljs.org/getting-started/migration/#importing-non-code-assets-from-javascript
