### ISSUE TITLE
Minified Sass breaks Parcel.js serve - @parcel/transformer-css: Unexpected token AtKeyword("import") 

### ISSUE THREAD

**Issue by victoriomolina** [parcel-bundler/parcel#8484]
I am using the following yarn script to compile my sass code:

```json
"scripts": {
    "start": "parcel src/pages/index.html",
    "watch-sass": "sass --watch src/sass/main.scss src/css/styles.css",
    "compile-sass": "sass src/sass/main.scss src/css/styles.comp.css",
    "prefix-css": "postcss --use autoprefixer -b 'last 5 versions' src/css/styles.comp.css -o src/css/styles.prefix.css",
    "minify-css": "sass --style=compressed src/css/styles.prefix.css src/css/styles.min.css",
    "build-css": "npm-run-all compile-sass prefix-css minify-css"
},
"devDependencies": {
    "autoprefixer": "^10.4.11",
    "npm-run-all": "^4.1.5",
    "parcel": "^2.7.0",
    "postcss-cli": "^10.0.0",
    "prettier": "^2.7.1",
    "sass": "^1.54.9"
}
```

In my `html` files, I am importing the .min.css stylesheets, which only contains one line of code (as they are minified).

When I try to serve my page using parcel, by using the command

 > parcel src/pages/index.html

I get the error:

> @parcel/transformer-css: Unexpected token AtKeyword("import")

This is how my minified css file looks like:

```css
@import"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700";/*!
 * Bootstrap  v5.2.1 (https://getbootstrap.com/)
 * Copyright 2011-2022 The Bootstrap Authors
 * Copyright 2011-2022 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/main/LICENSE)
 */@import"../../../../node_modules/bootstrap-icons/font/bootstrap-icons.css";@import"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700";@import"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700";/*...more code in one line...*/
```

How can I solve this?

Also reported [here](https://github.com/sass/dart-sass/issues/1803)

**Comment by devongovett** [comment]
That code seems to parse just fine - [Example](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22source%22%3A%22%40import%5C%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DOpen%2BSans%3A300%2C400%2C600%2C700%5C%22%3B%2F*!%5Cn%20*%20Bootstrap%20%20v5.2.1%20(https%3A%2F%2Fgetbootstrap.com%2F)%5Cn%20*%20Copyright%202011-2022%20The%20Bootstrap%20Authors%5Cn%20*%20Copyright%202011-2022%20Twitter%2C%20Inc.%5Cn%20*%20Licensed%20under%20MIT%20(https%3A%2F%2Fgithub.com%2Ftwbs%2Fbootstrap%2Fblob%2Fmain%2FLICENSE)%5Cn%20*%2F%40import%5C%22..%2F..%2F..%2F..%2Fnode_modules%2Fbootstrap-icons%2Ffont%2Fbootstrap-icons.css%5C%22%3B%40import%5C%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DOpen%2BSans%3A300%2C400%2C600%2C700%5C%22%3B%40import%5C%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DOpen%2BSans%3A300%2C400%2C600%2C700%5C%22%3B%2F*...more%20code%20in%20one%20line...*%2F%5Cn%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D). Do you have a full reproduction?
