### ISSUE TITLE
Error when importing "onnxruntime-web" from within an audioworklet

### ISSUE THREAD

**Issue by ricky0123** [parcel-bundler/parcel#8490]
# 🐛 bug report

When creating an audio worklet where I import the library "onnxruntime-web," I get `ReferenceError: self is not defined` from within the browser. I created a minimal example to reproduce the error [here](https://github.com/ricky0123/parcel-audioworklet-troubles). I am not sure if the error is specific to importing onnxruntime-web or if it would happen when importing other libraries. Note that I don't need to run the code from that library in order to get the error, importing something is enough.

## 🎛 Configuration (.babelrc, package.json, cli command)

[Here](https://github.com/ricky0123/parcel-audioworklet-troubles/blob/master/package.json) is the package.json of the example library and [here](https://github.com/ricky0123/parcel-audioworklet-troubles/blob/master/demo/package.json) is the package.json of an example web page demonstrating the error.

## 🤔 Expected Behavior

Running [this demo](https://github.com/ricky0123/parcel-audioworklet-troubles/tree/master/demo), I would expect the audio worklet to run and do nothing without any error.

## 😯 Current Behavior

I get this error in the browser console: 

```
ReferenceError: self is not defined
    a1Bf8 http://localhost:1234/my-worklet.67c998ce.js?1663595643492:167
    newRequire http://localhost:1234/my-worklet.67c998ce.js?1663595643492:71
    localRequire http://localhost:1234/my-worklet.67c998ce.js?1663595643492:84
    ["4s777"]< http://localhost:1234/my-worklet.67c998ce.js?1663595643492:146
    newRequire http://localhost:1234/my-worklet.67c998ce.js?1663595643492:71
    <anonymous> http://localhost:1234/my-worklet.67c998ce.js?1663595643492:122
    <anonymous> http://localhost:1234/my-worklet.67c998ce.js?1663595643492:145
```

## 💁 Possible Solution

I'm not sure if this is a bug within parcel or a mistake in my configuration.

## 🔦 Context

It would be useful to be able to process audio using onnx models from within audio worklets.

## 💻 Code Sample

[See here](https://github.com/ricky0123/parcel-audioworklet-troubles).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0 |
| Node             | 16.14.2 |
| npm         | 8.5.0 |
| Operating System | Ubuntu |

**Comment by ricky0123** [comment]
It doesn't seem to be specific to "onnxruntime-web"

**Comment by mischnic** [comment]
As far as I can tell, worklets don't have `self` and one has to use `globalThis` instead.

And that library simply has `self` in the output: https://unpkg.com/browse/onnxruntime-web@1.12.1/dist/ort-web.js

**Comment by mischnic** [comment]
-> https://github.com/microsoft/onnxruntime/issues/13072
