### ISSUE TITLE
Make links to other resources stay relative

### ISSUE THREAD

**Issue by GrosSacASac** [parcel-bundler/parcel#8505]
# 🙋 feature request

Make links to other resources stay relative

## Set up

```html
<!doctype html>
<html>
<head>
    <link rel="stylesheet" href="./b.css">
    <script type="module" src="./a.js"></script>
</head>
<body></body>
</html>
```

`parcel build html.html --dist-dir demobuilt`

## 🤔 Expected Behavior

Expected html output

```html
<!doctype html>
<html>
<head>
    <link rel="stylesheet" href="./b.a1d2ce9f.css">
    <script type="module" src="./a.zez4zu99.js"></script>
</head>
<body></body>
</html>
```

## 😯 Current Behavior

The links become absolute (to the root of the server)

```html
<!doctype html>
<html>
<head>
    <link rel="stylesheet" href="/b.a1d2ce9f.css">
    <script type="module" src="/a.zez4zu99.js"></script>
</head>
<body></body>
</html>
```

## 🔦 Context

The problem is that you cannot put all the built files in example.com/something/project
because /b.a1d2ce9f.css will try to use example.com/b.a1d2ce9f.css and not example.com/something/project/b.a1d2ce9f.css

This is not a problem if the files are all root top level

**Comment by caxapexac** [comment]
Any solutions yet?

**Comment by caxapexac** [comment]
Solved with `"publicUrl": "."` but looks like this must be default behaviour of the framework (its bad when your application is only working from the site's root)

**Comment by GrosSacASac** [comment]
?
