### ISSUE TITLE
Support use case where page only needs to be refreshed when a code change occurs

### ISSUE THREAD

**Issue by hubol** [parcel-bundler/parcel#8514]
# 🙋 Feature Request

It would be nice to have a CLI flag that causes the page to simply refresh when a code change occurs, rather than use HMR.

## 🔦 Context

My project is written in a custom framework that does not need to retain any state between code changes. My project is a game that uses OpenGL textures, and I have observed texture issues when using HMR. This issue occurs inconsistently and is difficult to debug. The texture anomalies are resolved when I refresh the page manually.

My use case is unusual, and it's likely that very few people would benefit from this feature. If there is some hack I can incorporate to accomplish this, that would be great too!

**Comment by jschill** [comment]
The page should be [refreshed by default](https://parceljs.org/features/development/#hot-reloading) on a code change?

But if it's still using the HMR maybe you can customize the code example in the link above, to something like this:

```js
if (module.hot) {
  module.hot.dispose(function () {
    location.reload();
  });
}
```

**Comment by mischnic** [comment]
> The page should be [refreshed by default](https://parceljs.org/features/development/#hot-reloading) on a code change?

Yes. It should do a full reload by default, and only do HMR replacements when opting in via the `module.hot.accept()` API.

Can you provide an example project where this doesn't happen for you?

**Comment by hubol** [comment]
@mischnic Is there a way I can reliably tell that it HMR is happening? The way I was able to determine it was HMR was that I was throwing an error when I detected my texture anomalies, and the error stack trace included a file that was clearly a replacement function from parcel HMR. But it wasn't super reliable...

**Comment by mischnic** [comment]
If you enable "Preserve log" in the chrome devtools, then there will be a "clear was prevented due to 'Preserve log' message on every HMR update. If that's what you mean
