### ISSUE TITLE
`parcel src/*.html` shows the index page no matter what

### ISSUE THREAD

**Issue by TiagoCavalcante** [parcel-bundler/parcel#8515]
# 🐛 bug report

The `index.html` page is shown no matter what is after the slash (/) when running `parcel src/*.html`

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "presets": [
    [
      "solid",
      {
        "generate": "dom",
        "hydratable": true
      }
    ]
  ]
}
```

## 🤔 Expected Behavior

The correct page or a 404 page is shown.

## 😯 Current Behavior

The path after the slash is just being ignored, so all of the URLs below map to `index.html`:
- `http://localhost:1234/`
- `http://localhost:1234/page.html`
- `http://localhost:1234/this_page_of_course_does_not_exist`

## 🔦 Context

I need to build and then use a server to "fix" this problem.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0
| Node             | v18.10.0
| npm         | 8.15.0
| Operating System | Elementary OS

**Comment by mischnic** [comment]
The main reason that there is no 404 page supporting SPA apps with client-side routing.

But if you have e.g. `src/foo.html` and `src/bar.html`, then `parcel src/*.html` should serve `localhost:1234/foo.html` and `localhost:1234/bar.html` as you'd expect. Do you have a concrete problem where this isn't the case or were you just expecting a proper 404 page?

**Comment by TiagoCavalcante** [comment]
@mischnic I have an HTML file named `options.html`, along with `index.html`, but `parcel src/*.html` only shows the index page in the URL `http://localhost:1234/options.html`

**Comment by TiagoCavalcante** [comment]
> Do you have a concrete problem where this isn't the case or were you just expecting a proper 404 page?

@mischnic yes, I have a concrete problem: I wasn't expecting a 404 page

**Comment by mischnic** [comment]
It's working for me: https://github.com/mischnic/parcel-issue-8515
