### ISSUE TITLE
Proxy setting file .proxyrc.js seems ignored by parcel, but .proxyrc.json works

### ISSUE THREAD

**Issue by matrixhcl** [parcel-bundler/parcel#8518]
# 🐛 bug report

I was trying to update parcel from 2.2.1 to 2.7.0. After update, the `.proxyrc.js` setting seems not working. I tried to move all settings to `.proxyrc.json` again and it works as expected.

## 🎛 Configuration (.babelrc, package.json, cli command)

The `.proxyrc.js` file I used: (target is replaced by a dummy domain)
```js
const serveStatic = require('serve-static')
const { createProxyMiddleware } = require('http-proxy-middleware')

module.exports = function (app) {
  // this middleware serve statc assets
  app.use(serveStatic('src/public'))
  app.use(
    createProxyMiddleware(['/cms-api', '/api'], {
      target: 'https://example.com/',
      changeOrigin: true,
    }),
  )
}
```
I tried to remove serveStatic middleware but it still doesn't work, all API call (e.g. /api/login ) return a 405 method not allowed error.

The `.proxyrc.json` I used:
```json
{
    "/api": {
      "target": "https://example.com/",
      "changeOrigin": true
    },
    "/cms-api": {
        "target": "https://example.com/",
        "changeOrigin": true
    }
  }
```
Since `.proxyrc.json` doesn't support static file serving so it only handle API proxying, and the api proxy setting works as expected.

## 🤔 Expected Behavior

`.proxyrc.js` setting file should work just like in version 2.2.1

## 😯 Current Behavior

`.proxyrc.js` file seems to be ignored by parcel, and the only way to fix it is to use `.proxyrc.json` or maybe `.proxyrc`(didn't test for `proxyrc`)

## 🔦 Context

Since parcel doesn't natively support static assets, the `serve-static` middleware was the easiest way for me to serve static files on the dev server. It can't be used if I could only use `.proxyrc.json` file for proxy configuration, unfortunately.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0
| Node             | 16.16.0
| npm/Yarn         | yarn 3.2.0
| Operating System | macOS 12.3.1

**Comment by mischnic** [comment]
This appears to be working for me: https://github.com/mischnic/parcel-issue-8518

**Comment by matrixhcl** [comment]
Yeah, it works totally fine on your repository. 
I am not sure if it's related to my project directory structure. I placed `index.html` inside the `src` folder, and all static assets in `src/public` folder, then started the development environment with the script below:

`parcel src/index.html --dist-dir build/debug --no-autoinstall --lazy`

I tried to reproduce the bug with a similar directory structure on your repository but failed though... I will do more investigation on my repo.

**Comment by lorenzogrv** [comment]
We have observed parcel will silently continue running without loading the `.proxyrc.js` file when its load produces an error (i.e. - missing dependency in our case).

You can check parcel behavior writing a `require('unexistant-package')` within the `.proxyrc.js` file beginning

You can test the file errors at import using `node .proxyrc.js`.

Maybe parcel should report the error, though

**Comment by mischnic** [comment]
Incidentally, there will be an error shown in the next release, but then there's still the problem that on "build success", the terminal is cleared to remove potential prior build errors, which includes this warning:

https://user-images.githubusercontent.com/4586894/236700691-f569332e-f07d-4e2a-89b7-f255314c01ef.mov

**Comment by mischnic** [comment]
Previously, [`MODULE_NOT_FOUND` and `ENOENT` errors were not printed](https://github.com/parcel-bundler/parcel/blob/2facd5df904b3888774a965a6be0e16248006449/packages/core/utils/src/config.js#L87). This will incidentally be fixed in the next release

<img width="1079" alt="Bildschirm­foto 2023-05-07 um 22 18 45" src="https://user-images.githubusercontent.com/4586894/236700808-fe223766-d062-4fd5-a25f-30f759c06371.png">

**Comment by atuldemond** [comment]
## CORS Configuration

To handle cross-origin requests in this project, we use the CORS middleware with the following configuration:

```js
// CORS configuration for handling cross-origin requests
const cors = require("cors");

// Define CORS options
const corsOptions = {
  origin: "http://localhost:1234", // Specify the allowed origin for requests
  optionsSuccessStatus: 200, // Set success status for legacy browsers (e.g., IE11, SmartTVs)
  methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"], // Allow all common HTTP methods
  credentials: true, // Allow credentials (cookies, authentication headers) in requests
};

// Apply CORS middleware with defined options
app.use(cors(corsOptions));
