### ISSUE TITLE
Running out of heap memory caused by square brackets

### ISSUE THREAD

**Issue by JoshuaAmaju** [parcel-bundler/parcel#8519]
# 🐛 bug report

Running `parcel build` never completes and fails with the log show below. And increasing the heap memory (`--max-old-space-size`) didn't fix it.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🤔 Expected Behavior

The build should run fine with no build or memory issues

## 😯 Current Behavior

NodeJS runtime runs out of heap memory

```
<--- Last few GCs --->

[23194:0x7f814eb00000]   732134 ms: Scavenge 1947.5 (2001.5) -> 1940.6 (2005.0) MB, 8.8 / 0.0 ms  (average mu = 0.371, current mu = 0.368) task 
[23194:0x7f814eb00000]   732188 ms: Scavenge 1951.6 (2005.2) -> 1944.4 (2008.7) MB, 4.6 / 0.0 ms  (average mu = 0.371, current mu = 0.368) task 
[23194:0x7f814eb00000]   732234 ms: Scavenge 1954.5 (2008.7) -> 1947.7 (2012.2) MB, 4.8 / 0.0 ms  (average mu = 0.371, current mu = 0.368) task 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10b6c4005 node::Abort() [/usr/local/bin/node]
 2: 0x10b6c4188 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x10b82e0f7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x10b82e093 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x10b9cf345 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 6: 0x10b9d337b v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
 7: 0x10b9cfc4c v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x10b9cd0fa v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x10b9d68e0 v8::internal::Heap::FinalizeIncrementalMarkingIfComplete(v8::internal::GarbageCollectionReason) [/usr/local/bin/node]
10: 0x10b9e6ddc v8::internal::IncrementalMarkingJob::Task::RunInternal() [/usr/local/bin/node]
11: 0x10b72d2bb node::PerIsolatePlatformData::RunForegroundTask(std::__1::unique_ptr<v8::Task, std::__1::default_delete<v8::Task> >) [/usr/local/bin/node]
12: 0x10b72bd07 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/usr/local/bin/node]
13: 0x10c06a82b uv__async_io [/usr/local/bin/node]
14: 0x10c07df7b uv__io_poll [/usr/local/bin/node]
15: 0x10c06ad21 uv_run [/usr/local/bin/node]
16: 0x10b5ff743 node::SpinEventLoop(node::Environment*) [/usr/local/bin/node]
17: 0x10b702af1 node::NodeMainInstance::Run(int*, node::Environment*) [/usr/local/bin/node]
18: 0x10b702773 node::NodeMainInstance::Run() [/usr/local/bin/node]
19: 0x10b692cbf node::Start(int, char**) [/usr/local/bin/node]
20: 0x11af3c52e 
```

## 💁 Possible Solution

After trying different things, I realised it had to do with the name of one folder. Seems parcel can't handle file names starting and ending with square brackets.

```
- companies
--- [company]
```

The build works fine when I remove the surrounding brackets

## 🔦 Context

Trying to mimic the Next.js folder structure

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0
| Node             | 14
| npm/Yarn         |
| Operating System | MacOS

**Comment by mischnic** [comment]
https://github.com/parcel-bundler/parcel/blob/e3a39a1f3642d28f8fd25919cda698ad34502cee/packages/core/core/src/requests/EntryRequest.js#L156-L166

There's an infinite loop here when doing `parcel build \[src\]/index.js`:

`resolveEntry(".../[src]/index.js")`: 
1. `isGlob(".../[src]/index.js") === true`
2. `files === [".../[src]/index.js"]`
3. `resolveEntry(".../[src]/index.js")` ----------^


Somewhat related: https://github.com/parcel-bundler/parcel/issues/7486

**Comment by JoshuaAmaju** [comment]
I'd be glad to help with this, anything thing I need to know to do that?

**Comment by mischnic** [comment]
I think `glob` should only ever be called once, so `resolveEntry` shouldn't be recursive.

**Comment by debanjanbanerjee46** [comment]
I want to work on this

**Comment by hacknlove** [comment]
If nobody has taken this, I will gladly take it.

**Comment by hacknlove** [comment]
The PR for this is there waiting.
