### ISSUE TITLE
Importing an HTML file into a web extension does not start scripts

### ISSUE THREAD

**Issue by clentfort** [parcel-bundler/parcel#8528]
# 🐛 bug report

When importing an HTML file into a background script of a web extension, a linked script file is loaded and compiled but never started.

I have create this [reproduction](https://github.com/clentfort/parcel-bug-repo) to showcase the issue. In the reproduction I have a [background script](https://github.com/clentfort/parcel-bug-repo/blob/trunk/src/background.js) that loads an [HTML file](https://github.com/clentfort/parcel-bug-repo/blob/trunk/src/index.html), the HTML file than loads a [JavaScript file](https://github.com/clentfort/parcel-bug-repo/blob/trunk/src/index.js). 

Parcel detects all three files when running `parcel watch` (with the webextension config loaded) and compiles the files. However, it does not execute the module from "index.js" because neither `entry` nor `mainEntry` are set in the transpiled code. See the generated [output](https://github.com/clentfort/parcel-bug-repo/blob/trunk/dist/parcel-bug.37dc76c6.js#L148) here. I tried with HMR enabled and disabled, same result. In the reproduction HMR is disabled to keep the dist-files small.

## 🎛 Configuration (.babelrc, package.json, cli command)

`.parcelrc`
```js
{
  "extends": "@parcel/config-webextension"
}
```

## 🤔 Expected Behavior

`entry` and `mainEntry` are set

## 😯 Current Behavior

`entry` and `mainEntry` are not set, contents of "index.js" does not execute.

## 🔦 Context

I spent an entire day scratching my head why my module didn't do anything.

## 💻 Code Sample

https://github.com/clentfort/parcel-bug-repo

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0
| Node             | v16 and v18
| npm/Yarn         | Yarn 1.22.19 and pnpm 7.13.1
| Operating System | MacOS and Linux

**Comment by 101arrowz** [comment]
This seems like expected behavior. You can't just import an HTML file like that - that wouldn't work if you were building a website either. When you import a `.html` you'll usually get a link to that file, but it won't be interpreted/evaluated.

You can get the behavior you probably want by simply using a background page:

```json
{
    "background": {
        "page": "index.html"
    }
}
```
