### ISSUE TITLE
Set target:es5, but the class public filed syntax is not compiled

### ISSUE THREAD

**Issue by fhyoga** [parcel-bundler/parcel#8529]
# 🐛 bug report

Set target:es5, but the class public filed syntax is not compiled
## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// tsconfig
{
  "compilerOptions": {
    "strict": true,
    "target": "es5",
    "esModuleInterop": true,
    "jsx": "react",
    "resolveJsonModule": true,
    "sourceMap": true,
    "lib": ["es2015", "DOM"]
  },
  "include": ["src"]
}
```

## 🤔 Expected Behavior
![image](https://user-images.githubusercontent.com/20250430/194697785-0acfde03-9ac8-49a8-9153-afc074a1f6a1.png)

## 😯 Current Behavior
![image](https://user-images.githubusercontent.com/20250430/194697803-aa91e6c8-e3fc-45ef-8838-7cae23a79429.png)

## 💻 Code Sample
https://github.com/SortableJS/react-sortablejs

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0
| Node             | 14.17.0
| npm/Yarn         | 1.22.17
| Operating System | macos

**Comment by mischnic** [comment]
You should set a browserslist config. Parcel doesn't read `target` inside of tsconfig.json.

https://parceljs.org/languages/javascript/#browser-compatibility
