### ISSUE TITLE
sass module watch not working

### ISSUE THREAD

**Issue by surajrathod** [parcel-bundler/parcel#853]
![untitled](https://user-images.githubusercontent.com/12035730/36389716-2ea74b1e-15c6-11e8-802d-e6c0217afd3c.jpg)

this is the structure that i want to work on.
when I make changes to ./sass/_one.scss  parcel watch does not output the compiled css.
but when i  save the base file it compile correctly
base.scss is included in index.js

**Comment by surajrathod** [comment]
help me to structure the sass modular format

**Comment by DeMoorJasper** [comment]
This should be fixed in latest version
