### ISSUE TITLE
No way to generate source map FILES for web-extension

### ISSUE THREAD

**Issue by avalanche1** [parcel-bundler/parcel#8530]
# 🐛 bug report
There is no way to generate Source map files for the web-extension platform.
They get generated inline (unless I fully disable them with `--no-source-maps`); no matter what options I set in `targets` in `package.json` - and I, of course, don't want them inline in my production build - instead I need to upload `.map` files to [Sentry](sentry.io).

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
  "scripts": {
    "build:prod": "parcel build src/entry/manifest.json --target prod --no-content-hash",
  },
  "targets": {
    "prod": {
      "sourceMap": {
        "inline": false
      }
    }
  },
```

## 🤔 Expected Behavior

`.map` files sd be generated for both the content and background script files.

## 😯 Current Behavior

Source maps are inlined in the `.js` files.

## 💁 Possible Solution

https://github.com/parcel-bundler/parcel/discussions/8523#discussioncomment-3834467

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  ^2.7.0
| Operating System | macOS 12.6

**Comment by mischnic** [comment]
https://github.com/parcel-bundler/parcel/discussions/8523:

> Looks like this is caused by these hardcoded overrides:
> 
> https://github.com/parcel-bundler/parcel/blob/de1569572ab681bb6e90d2b330d002b5df7947ea/packages/transformers/webextension/src/WebExtensionTransformer.js#L387-L408
> 


> Source maps don't actually work when they aren't inline in web extensions but we should allow this feature to be overridden when needed. Haven't been too active on maintaining webext in parcel lately but I think this should be an easy fix for anyone else.

**Comment by SpaceK33z** [comment]
Had the same issue, made a PR with the fix: #8541

**Comment by avalanche1** [comment]
@SpaceK33z What is the diff bw the `inlineSources` & `inline` params?

**Comment by SpaceK33z** [comment]
@avalanche1 whether to inline the original source code into the sourcemap rather than to link it. I think actually if you use it for uploading to Sentry you might want to set it to `inline: false, inlineSources: true`. See [docs here](https://parceljs.org/features/targets/#sourcemap).

**Comment by avalanche1** [comment]
@SpaceK33z setting the config as you suggested doesn't make any difference - the source maps are still inlined in the `.js` file.

**Comment by SpaceK33z** [comment]
Yes, this only works after my PR has landed (#8541). Didn't mean that it works now.

**Comment by SpaceK33z** [comment]
Commenting to mark it as not-stale, my open PR still seems to be valid: #8541.

**Comment by senese** [comment]
Is there a forecast on when PR #8541 will be reviewed?

**Comment by flexchar** [comment]
Hey @avalanche1, did you get this to work? :)
