### ISSUE TITLE
Uncaught ReferenceError; assignmen to undeclared variable on Parcel BUILD 

### ISSUE THREAD

**Issue by kordou** [parcel-bundler/parcel#8539]
Hi,

i am building a webpage with vanilla JS, parcel 1.7 on Visual studio Windows

in this page i have creates some custom classes that i import in my main index.js

when i deploy with dev all works fine

but when i am trying to bulid, i get no errors on build but on the main page, an error appears
"Uncaught ReferenceError; assignmen to undeclared variable"

basically i can understanth that my custom Classes are not included. 

![full](https://user-images.githubusercontent.com/45435435/195654471-db36f300-171d-4a0d-b5ba-77c9c519b4e8.jpg)
![index](https://user-images.githubusercontent.com/45435435/195654476-f659576e-70e8-4375-89fc-d0b82cbe7755.jpg)
![result](https://user-images.githubusercontent.com/45435435/195654480-fa617d6e-5760-4efa-b626-9920ed6757bd.jpg)
![siteMenu](https://user-images.githubusercontent.com/45435435/195654481-538daeab-4962-42ff-8b5b-99b046e9f3d7.jpg)

i also tried one version of parcel down but still the same issue

**Comment by mischnic** [comment]
Please provide a complete code sample.
