### ISSUE TITLE
Top-level await doesn't work, even though type="module" is specified

### ISSUE THREAD

**Issue by nc7s** [parcel-bundler/parcel#8558]
# 🐛 bug report

I'm trying to use [libsodium-wrappers](https://npmjs.com/package/libsodium-wrappers) in the browser. It requires `await`ing its exported `ready` attribute before using.

```html
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
</head>
<body>
	<script type="module">
import s from 'libsodium-wrappers'
await s.ready
document.body.innerText = `
key pair: ${JSON.stringify(s.crypto_box_keypair(), null, 4)}
`
	</script>
</body>
</html>
```

Parcel compiles fine, but the script tag seems to be stripped of `type="module"`, causing the error:

```
Uncaught ReferenceError: await is not defined
```

When that's added back in `dist/index.html`, another error comes out:

```
Uncaught SyntaxError: await is a reserved identifier
```

Using `s.ready.then()` works, but I'd rather not.

A working top level await demo:

```html
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
</head>
<body>
	<script type="module">
function x() {
	return new Promise((resolve, _) => {
		setTimeout(() => {
			document.body.innerText = new Date
			resolve()
		}, 3000)
	})
}

await x()
	</script>
</body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0
| Node             | 18.11.0
| pnpm             | 7.13.3
| Firefox Developer| 106.0b9
| Operating System | macOS 12.6

**Comment by mischnic** [comment]
Top level await isn't supported yet: https://github.com/parcel-bundler/parcel/issues/4028
