### ISSUE TITLE
Packaged JS files should be MIME type 'text/javascript', not 'application/octet-stream'

### ISSUE THREAD

**Issue by CraigThompsonCCL** [parcel-bundler/parcel#8559]
# 🐛 bug report

Packaging a React app sometimes outputs a distribution with the MIME type `application/octet-stream`. [Per the standard, Javascript files should have the MIME type `text/javascript`.](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types)

## 🎛 Configuration (.babelrc, package.json, cli command)

The app is built from the CLI with `parcel build $page`.

package.json:
```
{
  "name": "ccl_action_tracker",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@date-io/core": "^1.3.13",
    "@date-io/date-fns": "^1.3.13",
    "@date-io/dayjs": "^1.3.13",
    "@date-io/moment": "^1.3.13",
    "@emotion/react": "^11.10.4",
    "@emotion/styled": "^11.10.4",
    "@material-ui/core": "^4.12.4",
    "@material-ui/icons": "^4.11.3",
    "@material-ui/lab": "^4.0.0-alpha.61",
    "@material-ui/pickers": "^3.3.10",
    "@orrisroot/react-html-parser": "^2.1.1",
    "@types/react": "^17.0.50",
    "axios": "^1.1.2",
    "classnames": "^2.3.2",
    "date-fns": "^2.29.3",
    "dayjs": "^1.11.5",
    "highcharts": "^10.2.1",
    "highcharts-react-official": "^3.1.0",
    "lodash.clonedeep": "^4.5.0",
    "lodash.debounce": "^4.0.8",
    "lodash.get": "^4.4.2",
    "lodash.has": "^4.5.2",
    "lodash.noop": "^3.0.1",
    "lodash.pick": "^4.4.0",
    "lodash.throttle": "^4.1.1",
    "lottie-web": "^5.9.6",
    "moment": "^2.29.4",
    "prop-types": "^15.8.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-paginate": "^8.1.3",
    "react-window": "^1.8.7"
  },
  "parcel-namer-rewrite": {
    "chain": "@parcel/namer-default",
    "rules": {
      "(.*).js": "$1.{hash}.js",
      "(.*).css": "$1.{hash}.css"
    }
  },
  "scripts": {
    "build": "bash ./build_script.sh",
    "start": "bash ./start_script.sh",
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@parcel/transformer-sass": "^2.7.0",
    "@simbathesailor/use-what-changed": "^2.0.0",
    "buffer": "^6.0.3",
    "parcel": "^2.7.0",
    "parcel-namer-rewrite": "^2.0.0-rc.2",
    "process": "^0.11.10",
    "sass": "^1.55.0"
  }
}
```

./build_script.sh:

```
#!/bin/bash
set -euo pipefail

if [ $# -ne 2 ]
then
    echo "ERROR: you must pass the following arguments:"
    echo "   -an app (home, dashboard, create, goals)"
    echo "   -an environment (PROD, DEV, LOCAL)"
else
    export REACT_APP_RPC_ENV=$2
    page="./${1}/src/${1}.js"
    parcel build $page
fi
```

## 🤔 Expected Behavior

All .js files generated from Parcel reflect the MIME type `text/javascript` (or `text/plain`).

## 😯 Current Behavior

We have 5 React applications built using Parcel. Without the `--no-scope-hoist` flag, all 5 .js files generated from Parcel reflect the MIME type `application/octet-stream`. With the `--no-scope-hoist` flag, only one of the .js files reflect the MIME type `application/octet-stream`.

## 💁 Possible Solution

Since MIME type is not an actual piece of metadata, just something detected by an operating system (Linux: `file --mime-type <filename>`), this seems like something core to the code generated by Parcel. I don't know where to go from here.

## 🔦 Context

We recently upgraded to Parcel v2 and have run into this. We upload our app to a vendor who hosts the application. The vendor will not allow .js files of MIME type `application/octet-stream` (understandably) because the unknown binary contents of the file could possibly contain malicious code.

## 💻 Code Sample

The repository is private. But here is an example of the entry file from one of the applications:
```
import React from "react";
import ReactDOM from "react-dom";
import App from "./CreateApp";

function getCurrentScriptEl() {
  const scriptEls = document.querySelectorAll("script[data-render='here']");
  if (scriptEls.length === 0) {
    console.warn(
      "Unable to find a <script> to render to. Falling back to document.currentScript, which is not supported in all browsers."
    );
    return document.currentScript;
  } else if (scriptEls.length > 1) {
    console.warn(
      "Found more than one <script> to render to. Rendering only to the first."
    );
  }
  return scriptEls[0];
}

function loadScript() {
  const containerEl = document.createElement("div");
  const currentScriptEl = getCurrentScriptEl();
  currentScriptEl.parentNode.insertBefore(containerEl, currentScriptEl);
  ReactDOM.render(<App />, containerEl);
}

window.addEventListener('load', loadScript);
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.7.0
| Node             | 18.9.1
| npm        | 8.19.1
| Operating System | Ubuntu 20.04.3 LTS on WSL2 Windows 11 Home 21H2

**Comment by mischnic** [comment]
>  We upload our app to a vendor who hosts the application. The vendor will not allow .js files of MIME type application/octet-stream (understandably) because the unknown binary contents of the file could possibly contain malicious code.

As you've said, webservers infer the mimetype from the file extension since files themselves don't have a mimetype.
So I don't see what Parcel can do here. The problem is rather that your vendor's mimetype detection isn't working correctly.
