### ISSUE TITLE
Failed to construct 'WebSocket': The URL 'ws://:61948/' is invalid

### ISSUE THREAD

**Issue by Slapbox** [parcel-bundler/parcel#856]
For whatever reason the hot-loader is not recognizing my hostname. I'm also not able to populate `HMR_HOSTNAME`, although I have no problem populating other environmental variables using `cross-env`

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.6.1
| Node             | 8.9.1
| npm/Yarn         | 1.3.2 (yarn)
| Operating System | Windows 7 x64

**Comment by jbreckmckye** [comment]
What is happening with this? Parcel is great, but right now I can't use live reload in my project. If I can't resolve this I am going to have to switch back to webpack.

**Comment by DeMoorJasper** [comment]
@jbreckmckye could u possibly provide a test repository, I'll try find some time to look into it as it seems to be a quite important bug

**Comment by jbreckmckye** [comment]
Thanks for fixing this so quickly!

**Comment by ZachSaucier** [comment]
I'm still getting this error on version 1.9.2, having to use the `--no-hmr` flag to avoid it.

**Comment by felipemullen** [comment]
I'm seeing this issue as well working with an Electron app. It started the moment I added jquery to an html file:

`<script src="../lib/js/jquery-3.2.1.slim.min.js"></script>`

it's a very simple page, just login with vanilla js and bootstrap

**Comment by teriyakigod2** [comment]
Also getting this error on version 1.9.4.
@ZachSaucier  the same resolution works.

**Comment by j0hnm4r5** [comment]
Kind of the same issue here, on ^1.9.7, but weirder.

Basic Websocket connection from client to a node instance running with concurrently. It started off giving the same `Failed to construct 'WebSocket'` error, then I added the `--no-hmr` flag and reran it. Without HMR it ran fine.

But then I re-enabled HMR, and it _continued_ to run fine.

**Comment by michapietsch** [comment]
I came here because of the WebSocket error message. The original issue (first post: populate ```HMR_HOSTNAME```) does not affect me.

But I noticed the error in a quick static demo that I directly opened in the browser. The error went away when I accessed the demo through a server.

Maybe that's it for some of you, too. 🤷‍♂️
