### ISSUE TITLE
JS Dependency import / export reordering

### ISSUE THREAD

**Issue by conlanpatrek** [parcel-bundler/parcel#8560]
# 🐛 bug report

When using an `import` and an `export from` in the same file, the order of the statements are not respected. It appears that all import statements are hoisted above all export statements.

## 🎛 Configuration (.babelrc, package.json, cli command)

Completely vanilla parcel configuration.

## 🤔 Expected Behavior
```js
export * from './first' // Should evaluate first
import './second' // Should evaluate second
```

## 😯 Current Behavior
```js
export * from './first' // Actually evaluated second.
import './second' // Actually evaluated first.
```

## 💁 Possible Solution
I'm guessing that there is some code in the js dependency tree builder / packager that scans for all imports in the current file and misses exports that also have an implicit import, or chooses to operate on them separately, after adding all of the imports to the dependency graph.

If that's the cause here I would want that hypothetical code to retain import / export order. Basically treat all `export from` statements as an implicit import THEN an export. That way the implicit import gets hoisted appropriately, and in the right order.

## 🔦 Context
The problem with execution order and side effect imports should be self explanatory. My specific issue has to do with CSS order though, which is sort of a side effect, I suppose.

I use a regular pattern in my react applications that keeps my BEM styles and my components separate. Essentially I have a lot of this sort of structure:

My files:
```
src/Component/Button/
- index.js
- Button.js
- Button.css

src/Component/Icon/
- index.js
- Icon.js
- Icon.css
```

src/Component/Button/index.js:
```js
export * from './Button'
import './Button.css'
```

src/Component/Button/Button.js:
```js
import { Icon } from 'Root/Component/Icon'

export const Button = ({ children }) => (
    <button className="Button"><Icon className="Button-icon"/> {children}</button>
)
```

src/Component/Button/Button.css:
```css
.Button-icon {
    /* Should override .Icon styles */
    width: 2em;
    height: 2em;
    color: red;
}
```

Most of my styles are, by discipline, applied to single class selectors, making overriding dependency styles pretty simple. In the case above, the button component styles the icon component by its single class. I expect that the order I've imported these files, that Button.css would appear after Icon.css.

However, since the import statements are being pushed into the dep tree before export froms, I don't even have the ability to control order with this pattern.

Now that I know a little more about the issue I can work around it, maybe by including a separate, explicit `import`

```js
import './Button'
export * from './Button'
import './Button.css'
```

Or maybe this, which is hacky but dry.
```js
export * from './Button'
export {} from './Button.css'
```

## 💻 Code Sample
[Here's a git repo with a minimum recreation of the issue](https://github.com/conlanpatrek/parcel-reordered-js-dependencies-bug)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.0.0-nightly.1175
| Node             | 16.13.1
| npm/Yarn         | yarn 1.22.18
| Operating System | Mac Big Sur

**Comment by conlanpatrek** [comment]
So I've done a little digging, and I found that in JSTransformer.js:

https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/js/src/JSTransformer.js#L379

`dependencies` is already out of order, as are the rewritten imports in `code`.

I've glanced at `lib.rs` and `dependency_collector.rs` and I'm not sure that I see where this dependency reordering could be occurring. But then this is, admittedly, the first time I've read through Rust.

~~Could this be an swc bug?~~ I just pulled down the latest version of swc and I'm not seeing this issue immediately. I think I'm just not sure where to look in the parcel source.

**Comment by mischnic** [comment]
The order of `dependencies` doesn't actually matter (for JS). Without scope hoisting, the order of the `require` calls in `compiledCode` matters. With scope hoisting, the order of the `import "...";` statements in `compiledCode` matters.

**Comment by conlanpatrek** [comment]
> The order of `dependencies` doesn't actually matter (for JS). Without scope hoisting, the order of the `require` calls in `compiledCode` matters. With scope hoisting, the order of the `import "...";` statements in `compiledCode` matters.

I'm not sure if you're providing context or pushback, so I'll add this:

The imports in `compiledCode` are also out of order. So what I'm seeing is given this source file:

```js
export * from './a'
import './b'
```

With hoisting enabled, `compiledCode` evaluates to
```js
import "e293157254c18bfb:./b:esm";
import "e293157254c18bfb:./a:esm";
```

And with hoisting disabled, `compiledCode` evaluates to
```js
var parcelHelpers = require("@parcel/transformer-js/src/esmodule-helpers.js");
parcelHelpers.defineInteropFlag(exports);
var _b = require("./b");
var _a = require("./a");
parcelHelpers.exportAll(_a, exports);
```

Both of which import b before importing a. That can't be expected, right?

The "`dependencies` order not mattering" context is helpful, though I do suspect them being out of order is a symptom of the same problem that causes the compiled code to be wrong.

**Comment by mischnic** [comment]
> context or pushback

Context.

So yes, it should be "a", then "b". And both Parcel versions are indeed incorrect.

**Comment by mischnic** [comment]
But as far as I can tell, it's working correctly with `"parcel": "2.0.0-nightly.1185"`?

**Comment by conlanpatrek** [comment]
@mischnic Not by my testing. I updated the example repo with parcel nightly 1185 (was 1175) and see no difference.

parcel gitHead is `05d0bc0bc59bf966285dfb0966f3390dca6e7fbc`, which is a commit from yesterday.

There are different native modules doing the rewrite depending on OS / architecture. Could be that the issue is specific to the `parcel-swc.darwin-x64.node` binary, or it could be that your setup doesn't satisfy the criteria? Can you share how you tried to repro, maybe I can help diagnose what's going on there?

EDIT - Could also be an environment variable causing some config difference between our machines 🤔. Were you using the repro I provided, with the alert example?

**Comment by mischnic** [comment]
It might be that I only tested a production scopehoisting build.  (I'm also Intel Mac)
With your current repo, it's indeed incorrect for dev, but it does work correctly with `parcel build index.html`

**Comment by conlanpatrek** [comment]
@mischnic you patched this so fast. tysm
