### ISSUE TITLE
parcel+tailwindcss+daisyui result in bad CSS output

### ISSUE THREAD

**Issue by tfc** [parcel-bundler/parcel#8577]
# 🐛 bug report

Parcel creates invalid CSS for specific input.

## 🎛 Configuration (.babelrc, package.json, cli command)

Minimal reproducer repository with all the info: https://github.com/tfc/tailwindcss-hovertr

## 🤔 Expected Behavior

I expect parcel to generate valid output CSS from valid input CSS.

## 😯 Current Behavior

```
@parcel/transformer-css: Unsupported pseudo class or element: hovertr

  /tmp/tailwindcss-hovertr/src/index.css:4302:26
 ```

In the non-optimized output, the `hover` class for `tr` elements looks like this:

```
.table .hover\:hover:hovertr:hover th, .table .hover\:hover:hovertr:hover td, .table .hover\:hover:hovertr:nth-child(2n):hover th, .table .hover\:hover:hovertr:nth-child(2n):hover td {
  --tw-bg-opacity: 1;
  background-color: hsl(var(--b3, var(--b2)) / var(--tw-bg-opacity));
}
```

## 💻 Code Sample

Minimal reproducer repository with all the info: https://github.com/tfc/tailwindcss-hovertr

**Comment by mischnic** [comment]
This problem occurs with 
```js
// tailwind.config.js
module.exports = {
  content: ["foo.js"],
  plugins: [require("daisyui")],
};
```
```js
// foo.js
module.exports = {
	".table tr.hover:hover td": {
		backgroundColor: "red",
	},
};
```

which results in this output after running Tailwind:
```css
.table tr.hover:hover td {
    background-color: red
}
.table .hover\:hover:hovertr:hover td {
    background-color: red
}
```

This is simply incorrect CSS (the backslash and also the `:hovertr` pseudoclass). You should report this as a bug of daisyui

**Comment by tfc** [comment]
Well.. i thought the same and already reported this as a bug in daisyui, and the maintainer said he can't do anything because the input css is valid: https://github.com/saadeghi/daisyui/issues/1277#event-7683688779

This is a little bit of a sad situation for me when both sides say they don't own the bug, not sure what to do now to fix this, as it is keeping me from updating my inputs.

**Comment by mischnic** [comment]
Why have you added `content: [ "node_modules/daisyui/dist/**/*.js" ]` ? Removing that part does fix the problem. And in the daisyui examples I don't see that either.

**Comment by tfc** [comment]
I am a newbie and i was afraid that the target CSS file would be missing attributes that are mentioned in that library.

**Comment by mischnic** [comment]
But the resulting page does have the correct styling now?

**Comment by tfc** [comment]
@mischnic i dropped the line you mentioned from the `content` array and now it works.

It was all my own fault. Sorry for the noise! Thank you very much for helping me identify the problem!
