### ISSUE TITLE
Parcel 2 doesn't work out of box, parcel 1 however does.

### ISSUE THREAD

**Issue by pencilcheck** [parcel-bundler/parcel#8595]
# 🐛 bug report

Just expressing my experience, if parcel 2 can live up to the disclaimer to be "The zero configuration build tool for the web" then it should be "The zero configuration build tool for the web".

Tons of issues using Parcel 2
1. process not defined (meaning dotenv isn't loading correctly and process.env.VAR isn't replaced for some reason, not sure why)
2. the files are not defined (resolver can't find files), and had to add .parcelrc but still doesn't really work as it require relative path so had to change everything there
3. Build error when using JS imports: Browser scripts cannot have imports or exports https://github.com/parcel-bundler/parcel/discussions/6490 (using jquery and if the original jquery script didn't export while adding a separate script side by side to export to windows, somehow it needs a type="module" on a require and changing to type="module" stops windows global from working which beats the point)

There could be more but it is not really zero configuration and drop in, tons of issues, but the moment I revert back to 1, it just works magically

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by devongovett** [comment]
This isn't really an actionable issue without a reproduction.

**Comment by pencilcheck** [comment]
I'm trying to reproduce a website that I can send here for you all to test
