### ISSUE TITLE
Parcel not compiling scss correctly for dev mode

### ISSUE THREAD

**Issue by borbollabaroni** [parcel-bundler/parcel#8596]
I'm doing a project, and I have this code on my scss file;
-webkit-box-decoration-break: clone;
      box-decoration-break: clone;

When a run to check if everything is ok, the -webkit part isn't added on the css file for dev. But for production it is.

**Comment by mischnic** [comment]
See https://github.com/parcel-bundler/lightningcss/issues/325

As a workaround, you use `parcel index.html --target default` (so add that target flag) to make it use the production browserslist config in dev as well.

**Comment by devongovett** [comment]
Should be fixed in the latest version.
