### ISSUE TITLE
Babel overwrites target ecmaVersion of tsconfig

### ISSUE THREAD

**Issue by DeMoorJasper** [parcel-bundler/parcel#860]
🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

tsconfig => es2018
babel => no config

### 🤔 Expected Behavior

Babel shouldn't transpile down

### 😯 Current Behavior

Babel does transpile down

### 💁 Possible Solution

Check if it's already transpiled in JSAsset.parse and just convert to a babel ast if it has been

### 🔦 Context

See twitter conversation: https://twitter.com/martin_hotell/status/965862279022632961

### 🌍 Your Environment
Accurs in all parcel versions

**Comment by Hotell** [comment]
Just adding more info:

**TS version:** 2.7.2

**tsconfig.json**

```json
{
  "compilerOptions": {
    "target": "esnext",
    "sourceMap": true, 
    "importHelpers": true,
    "pretty": true,
    "skipLibCheck": true,
    "strict": true, 
    "moduleResolution": "node",
    "esModuleInterop": true                     
  }
}
```

**Comment by devongovett** [comment]
In the latest Parcel version, we apply babel-preset-env by default. If you don't specify browser targets, we'll choose a set of default browser targets (> 1% marketshare). This means your code will be transpiled by babel after typescript runs. You can stop this from happening by setting some browser targets for your app in package.json:

```json
{
  "browserslist": ["last 2 Chrome versions"]
}
```
