### ISSUE TITLE
I see wrong file names in the console 

### ISSUE THREAD

**Issue by pupok90** [parcel-bundler/parcel#8620]
# 🐛 bug report

each time i see my code in the browser if it have any errors or console.log, i dont see the actual file name and line where it occured, instead i see the actual parcel output file after bundling 

## 🎛 Configuration (.babelrc, package.json, cli command)
```
{
  "name": "forkify",
  "version": "1.0.0",
  "description": "Recipe application",
  "default": "index.html",
  "browserslist": "> 0.5%, last 2 versions, not dead",
  "targets": {
    "main": false
  },
  "scripts": {
    "start": "parcel index.html",
    "build": "parcel build index.html --dist-dir ./dist"
  },
  "author": "Jonas Schedtmann",
  "license": "ISC",
  "devDependencies": {
    "@parcel/transformer-sass": "^2.2.1",
    "parcel": "^2.2.1"
  },
  "dependencies": {
    "fracty": "^1.0.9"
  }
}

```

## 😯 Current Behavior
![chrome_Juw7sOyaMe](https://user-images.githubusercontent.com/117883479/201191194-9a3cb0fe-aed0-4075-aaa7-72cb81f4affc.png)

## 💻 Code Sample
https://github.com/pupok90/forkify

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
What was your source code in that case?

**Comment by pupok90** [comment]
here is the code https://github.com/pupok90/forkify

**Comment by mischnic** [comment]
That repo is private or doesn't exist.
