### ISSUE TITLE
Error: No space left on device (windows and ubuntu)

### ISSUE THREAD

**Issue by 11ume** [parcel-bundler/parcel#8622]
# 🐛 bug report

Hi, im making a migration from CRA to parcel 2, the build works really fine but parcel 2 leaves me without space on the device, this happens after doing some compilations or in the first compilation.

## 🎛 Configuration (.babelrc, package.json, cli command)

Zero configuration.

## 🤔 Expected Behavior

Compilation/s should build/start whiout cusming all device space.

## 😯 Current Behavior

Fails with:

```bash
ENOSPC
[Error: inotify_add_watch failed: No space left on device]
```

## 💁 Possible Solution

**Ubuntu**:

```bash
sudo sysctl fs.inotify.max_user_watches=1048576 # increase to 1048576

#This doesn't seem to be the ultimate solution or the best solution.
```

**Windows**

No solution.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  latest
| Node             | 16.16.0
| npm/Yarn         |  8.11.0
| Operating System | windows/ubuntu

<br/>

**Project size**:

```bash
4,0K    dev.yaml
4,0K    Dockerfile
1,5G    node_modules       (big)
8,0K    package.json
2,2M    package-lock.json
4,0K    prod.yaml
30M     public                      (big)
4,0K    README.md
92K     server
18M     src                           (big)
4,0K    tsconfig.json
```

**Comment by devongovett** [comment]
See https://parceljs.org/features/development/#linux%3A-no-space-left-on-device
