### ISSUE TITLE
Image optimizations on images imported through glob

### ISSUE THREAD

**Issue by t1enne** [parcel-bundler/parcel#8623]
# 🐛 bug report

If I import my images with a glob, the query parameters used for image optimizations don't work.

```js
import IMAGES from "/assets/*.jpg";

const url = new URL(IMAGES[0][0] + "?as=webp", import.meta.url)
```

in the example above url doesn't get transformed, probably because the glob operator already transforms the url string of the images, so the query parameters are not parsed correctly.

The above works if I use an absolute url to a single image.

Let me know if I'm doing this wrong

## 🤔 Expected Behavior

images should be transformed according to the query parameters specified

## 😯 Current Behavior

images are not being transformed, sharp isn't being installed.

**Comment by mischnic** [comment]
What you're trying to do is not statically analyzable, but something we could support (if it isn't already) is
`import IMAGES from "/assets/*.jpg?as=webp";`. Have you tried that already?

**Comment by t1enne** [comment]
Thank you for the quick answer!

`import IMAGES from "/assets/*.jpg?as=webp";`

this line gives back an empty object.

I also tried adding the query params without the `new URL` call, with no luck.

**Comment by mischnic** [comment]
So another (non-critical) problem with your code is https://github.com/parcel-bundler/parcel/issues/8704

Then, the glob resolver doesn't correctly handle the query at the correctly: the `?...` part should be stripped of before processing the glob and then put back onto the end (just like the pipeline already is)
https://github.com/parcel-bundler/parcel/blob/da6cbb3633d2c0e9fedb8e2af560c82504d05ddc/packages/resolvers/glob/src/GlobResolver.js#L139-L152
