### ISSUE TITLE
CSS module exports, for library target, incompatible with NextJS

### ISSUE THREAD

**Issue by wkrueger** [parcel-bundler/parcel#8626]
# 🙋 feature request + context

When you import a library exported by Parcel in NextJS, it complains that "Global CSS can only be imported in _app.js".

The first line in the exported `module.js` is an import for a single CSS:
```js
// module.js
import "./main.css";
import {jsxDEV as $8gYtZ$jsxDEV} from "react/jsx-dev-runtime";
// ...
```

## 😯 Current Behavior

All CSS is bundled into a single output and required on the JS bundle.

## 💁 Possible Solution

Suggestion - allow one of the following through an option:

  - Option to keep JS files split and not converting `.module.css` files to plain CSS. CSS module processing is delegated to the consumer;
  - Option to disable the `require('./main.css')` so the consumer can manually do it.

**Comment by wkrueger** [comment]
Maybe I'm just using the wrong tool for the job, I could just run TSC and Sass separately on the codebase since it is not intended to be consumed by a browser...

**Comment by mischnic** [comment]
See this thread: https://twitter.com/timneutkens/status/1603407819310792705

This is really just an artificial limitation imposed by Next.js (but apparently that changes with version 13 as per that thread), all other build tools support this just fine.
