### ISSUE TITLE
🙋 Replace chokidar with fb-watchman

### ISSUE THREAD

**Issue by hayeah** [parcel-bundler/parcel#863]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

`chokidar` only supports native file-system notification for MacOS (a limitation because it relies on fsevents).

[watchman](https://facebook.github.io/watchman/docs/install.html) provides efficient fs notification for all platforms. Watchaman is used by the `react-native` bundler, which seems to work pretty well.

**Comment by devongovett** [comment]
Interesting. Are there nodejs bindings that don't require installation via `brew` or another package manager but just via npm?

If someone wants to experiment with this, it looks cool!

**Comment by mrcoles** [comment]
Also, FWIW, `create-react-app` sees changes for me in this situation.

setup:

```bash
$ create-react-app -V
1.5.2
$ create-react-app test-create-react-app
$ cd test-create-react-app/
$ yarn start
```

Then edit `src/App.js` and http://localhost:3000/ auto-updates.

**Comment by davidnagli** [comment]
I think this a really interesting idea, agree with @devongovett here, we should definitely experiment with this 👍 

I found that for some reason it’s a bit hard to find information on google about using watchmen with Node-JS, so here are some links to use as starting points:

[Watchmen NodeJS Docs](https://facebook.github.io/watchman/docs/nodejs.html)
[Watchmen NPM Package](https://www.npmjs.com/package/fb-watchman)

**Comment by davidnagli** [comment]
@mrcoles Are you talking about the dropbox thing?

**Comment by yakotika** [comment]
I tried to replace the library in the library, but I got the error 

> Watchman was not found in PATH.

**Comment by yakotika** [comment]
I tried to replace the chokidar in the fb-watchman, but I got the error:

> Watchman was not found in PATH.

I tried to do like in this [webpack-watchman-plugin](https://github.com/researchgate/webpack-watchman-plugin/blob/master/src/WatchmanConnector.js)

**Comment by brandon93s** [comment]
From the `webpack-watchman-plugin` readme:

> Make sure watchman is installed and ready to use on your system.

You have to install it on your machine on your own for the plugin to work. This is going to be the biggest barrier to switching.

**Comment by DeMoorJasper** [comment]
I'm not sure it's worth switching as installing watchman to enable the watcher would sort of defy the whole `zero-config` experience.
On the other side however, we could create a simple adapter in between our watcher code and chokidar and watchman, and switch according to what exactly is installed. If i'm not mistaken, watchman's node mappings have a function that checks what version is installed. If no watchman is found we could always fallback to chokidar with polling to ensure 100% accuracy, but poor performance.

I have not experimented enough with watchman to be able to say if it's even that much better than chokidar in the first place (it might not be worth it)

**Comment by davidnagli** [comment]
Oh wow I didn’t realize it would require a separate install, that’s super annoying. I like @DeMoorJasper’s idea, but all this adds a huge unforeseen layer of complexity that will probably bring little benefit. 

I think for now we should just make a super basic implementation that just assumes it’s already installed, and then run perf tests on that to see if Watchmen even brings any benifits in the first place.

**Comment by davidnagli** [comment]
Whoops accidental closed... reopening

**Comment by yakotika** [comment]
Do I understand correctly that you want to temporarily make the condition:

**Comment by yakotika** [comment]
Do I understand correctly that you want to temporarily make the condition:
If no watchman is found, the return chokidar, otherwise watchman?

**Comment by davidnagli** [comment]
I would try a barebones implementation first, then if you see performance benifits maybe actually implement that whole thing.

**Comment by AndyOGo** [comment]
Hey guys,
that's really annoying with `watchman`...
Basically it is build as a service which you have to install at your OS first.
Afterwards you can `npm install fb-watchman` to get NodeJS client, which consumes this service. Really no one wants *out-of-npm* installs for node apps to be working 😱 

**Node Sentinel File Watcher** `NSFW` provides proper bindings and is a much better alternative to chokidar 🎉 
https://github.com/Axosoft/nsfw/issues/18

**Comment by AndyOGo** [comment]
@deniskabana 
I see. Thanks for testing it.
So I guess both come with their downsides and upsites 🤔

**Comment by hennr** [comment]
Both alternatives to chokidar, watchmen and NSFW seem to need locally installed packages to work.
@DeMoorJasper said that this would not comply to the zero-configuration approach and everyone else agreed.
Leaving the issue open seems pointless to me at the moment.
Anyone against closing it?
