### ISSUE TITLE
RFC: Mobile preview with scannable QR code that opens up your dev server

### ISSUE THREAD

**Issue by jesselawson** [parcel-bundler/parcel#8634]
# 💬 RFC

I use Parcel to build mobile experiences. One feature I'd like to have is the ability to scan a QR code in my terminal and have that open up what I'm working on in my phone's browser. This is important to me because I can debug a lot closer to what the user experience will be.

## 🔦 Context

This is part convenience and part artistic debugging. What I am trying to accomplish is to preview what I'm building in Parcel with my phone, since that is my target audience.

## 💻 Examples

- Flutter 
- https://github.com/formspark/localview

**Comment by mischnic** [comment]
This could be a third party reporter plugin, which does
```js
import {Reporter} from '@parcel/plugin';

export default (new Reporter({
  async report({event, options}) {
    if (event.type === 'watchStart' && options.serveOptions) {
      let {host, port} = options.serveOptions;
      console.log(generateQRCode(host, port)); // = what that localview tool does
    }
  },
}));
```

And personally, I don't see a need for this to be enabled by default, as typing in the IP and port isn't that big of a hassle (or using macOS Handover or Chrome's "Send to Device" feature).

**Comment by jesselawson** [comment]
As a reporter plugin makes a lot of sense! Thank you!
