### ISSUE TITLE
Raw-url doesn't work as expected

### ISSUE THREAD

**Issue by caxapexac** [parcel-bundler/parcel#8640]
# 🐛 bug report

.parcelrc
```
    "packagers": {
        "rawurl:*": "@parcel/packager-raw-url"
    }
```

Source html:
```html
...
<script src="rawurl:external.js"></script>
...
```

## 🤔 Expected Behavior

Compiled html:
```html
<script src="external.js"></script>
```

## 😯 Current Behavior

Compiled html:
```html
<script src="rawurl:external.js"></script>
```

Any way of just ignoring parsing script declaration (and any other URL declaration)?

(Yeah, I couldn't find any README on these plugins (raw, raw-url and many others))

**Comment by caxapexac** [comment]
Solved by https://www.npmjs.com/package/parcel-resolver-exclude-assets

But this is also poor solution because I can't make a prefix so I need to manually type every single filename I want to exclude from resolving:
```json
    "resolverExcludeAssets": [
        "external1.js",
        "external2.js"
    ]
```

(My external scripts don't have a common prefix to use here in `resolverExcludeAssets`)

**Comment by mischnic** [comment]
You could write a resolver to achieve this: https://github.com/mischnic/parcel-example-rawurl

> (Yeah, I couldn't find any README on these plugins (raw, raw-url and many others))

That is not what the raw-url packager does. (The raw packager doesn't do any processing and just outputs the asset as it came from a transformer. The raw-url packager does the same but additionally replaces dependency specifiers that transformers have written into the asset content.)

**Comment by caxapexac** [comment]
Thanks, now it makes sense!
