### ISSUE TITLE
Parcel randomly builds wrong target probably because of cache bug, probably because of separate dist directories

### ISSUE THREAD

**Issue by caxapexac** [parcel-bundler/parcel#8649]
# 🐛 bug report

- Here we have 2 targets with separate dist folders
- `build` the first one. Everything works
- `build` the second one. The first one is being build from time to time

Sometimes problem sovles when I clear parcel cache

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```json
"targets": {
        "pure": {
            "context": "browser",
            "source": "src/index-pure.html",
            "distDir": "./dist",
            "publicUrl": "."
        },
        "w4-debugfast": {
            "context": "browser",
            "source": "src/index-w4.html",
            "distDir": "../_out/debugfast/w4-temp",
            "publicUrl": "."
        },
},
"scripts": {
        "start": "parcel serve --target pure",
        "start:w4-debugfast": "parcel serve --target w4-debugfast",
        "build": "parcel build --target pure",
        "build:w4-debugfast": "parcel build --target w4-debugfast",
        "clean": "rimraf dist && rimraf .parcel-cache && rimraf parcel-bundle-reports"
},

```
parcelrc
```json
{
    "extends": "@parcel/config-default",
    "reporters": [
        "...",
        "parcel-reporter-static-files-copy"
    ],
    "resolvers": [
        "parcel-resolver-exclude-assets",
        "..."
    ]
}
```

babelrc
```json
{
    "plugins": [
        "babel-plugin-styled-components"
    ]
}
```

## 🔦 Context

I'm making a game UI which takes pretty much time to build (game and react source code builds separately so doesn't affect each other). So I've make this `debugfast` parcel target to mock my game's API to test the react UI code

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.0
| Node             | 16.8.0
| npm/Yarn         | 8.3.0
| Operating System | Windows 10 22H2

**Comment by caxapexac** [comment]
Look:
Here we have 2 targets - `pure` and `debugfast`
`Pure` has `"source": "src/index-pure.html", "distDir": "./dist",`
`Debugfast` has `"source": "src/index-w4.html", "distDir": "../_out/debugfast/w4-temp",`

Now lets build then change target then build etc.:
![image](https://user-images.githubusercontent.com/33996246/203008451-359c41e8-1ee8-4bf5-a9bb-8337863918dd.png)

As you can see we have index-w4 inside the wrong dist directory

**Comment by caxapexac** [comment]
Problem still exist and thats really annoying

**Comment by caxapexac** [comment]
Problem still exists, any chance of troubleshooting help please?

**Comment by mischnic** [comment]
The problem appears to be that `--target` somehow doesn't do anything for `parcel serve` in your case. Because if when changing the distDirs in each target, `parcel serve  --target pure` always outputs to `dist`.

**Comment by caxapexac** [comment]
@mischnic thanks for reply! Can I use something instead of `--target` for now? How can I help with debug?
