### ISSUE TITLE
background-image css rule raises "Uncaught (in promise) Error: Cannot find module" in console

### ISSUE THREAD

**Issue by targumon** [parcel-bundler/parcel#865]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
This is a 🐛 bug report.

### 🎛 Configuration
Here's the smallest reproducible configuration. No .babelrc, just 3 simple files:
index.html - `<link rel="stylesheet" href="index.css">` in head and `<div>hi</div>` in body.
index.css - `div { background: url("bg_diag.png"); }`
bg_diag.png - ![bg_diag.png](https://user-images.githubusercontent.com/7461344/36420422-b34c4b90-163d-11e8-9ad0-c1050e25b9dc.png)

### 🤔 Expected Behavior
Clean console

### 😯 Current Behavior
http://localhost:1234/ seems okay (there's a single network request and the page loads with that background-image for the div element).
However, there's an error in console:
```
Uncaught (in promise) Error: Cannot find module '6b40fa7fa533b048cde070004da2b0e1.png,4'
    at newRequire (css-loader.js:30)
    at newRequire (css-loader.js:22)
    at localRequire (css-loader.js:30)
    at css-loader.js:30
    at <anonymous>
```

### 🌍 Your Environment
    "devDependencies": {
      "parcel-bundler": "^1.6.2"
    }

| Software         | Version(s) |
| ---------------- | ---------- |
| Node             | v8.9.4
| npm        | 5.6.0
| Operating System | Chrome on macOS

**Comment by benhutton** [comment]
I'm seeing something very similar when trying to get hmr working with the latest parcel version.

**Comment by xiemingzhang** [comment]
![wechatimg3](https://user-images.githubusercontent.com/21289714/36629721-1e62bb1c-1995-11e8-8bc2-e26928f496e8.jpeg)

**Comment by mischnic** [comment]
Some findings:

```js
newRequire(name){
	...
	console.log(name)
	...
}

// prints
12
0
13
11
["a34b5839f12b33bc85271b84ecf5f50f.png", 8]
["a34b5839f12b33bc85271b84ecf5f50f.png", 8]
```
This doesn't seem right (sometimes array, sometimes number).

Content of `modules`: `{0: Array(2), 4: Array(2), 7: Array(2), 11: Array(2), 12: Array(2), 13: Array(2)}` -   there is no `8`.

**Comment by realdennis** [comment]
I have the same situation with you.

Chrome:
<img width="942" alt="2018-03-11 3 42 31" src="https://user-images.githubusercontent.com/26633162/37246124-5841f308-24de-11e8-9302-1944c63e4995.png">
Firefox:
<img width="1153" alt="2018-03-11 3 42 41" src="https://user-images.githubusercontent.com/26633162/37246126-5d3a0436-24de-11e8-8ee5-be71b22a3822.png">

Node v9.7.1
npm 5.6.0

**Comment by realdennis** [comment]
I just add ` import 'index.css' `in entry js,
 and remove the` <link rel="stylesheet" href="index.css">` to resolve this issue.

**Comment by targumon** [comment]
@realdennis good for you! ^_^
My use case is with HTML as entry point, not JS.

**Comment by realdennis** [comment]
@targumon  I mean that if you have `<script src="index.js"></script>` in your HTML, you can add` import '...css'` in the top of index.js , but also use command `parcel index.html`, roundabout but it worked for me.

**Comment by skotniczny** [comment]
The last version without this error is 1.4.1

**Comment by kaishiro** [comment]
Just confirming that this is a bug for me in 1.7.1 and I can verify what @skotniczny said that 1.4.1 is the last version where this works correctly for me.

**Comment by davidnagli** [comment]
@devongovett @DeMoorJasper Guys this looks like a regression!!  I ran into this when using Parcel myself 😟 

I did some digging and the root cause of the issue (the reason why it works in`v1.4.1` but not `v1.5.0`) is, unsurprisingly, because 1.5.0 is when we first introduced CSS HMR: #128. I guess the initial implementation didn't account for CSS child assets or something 🤷‍♂️ (not sure, didn't get a chance to investigate in-depth)

The repro for this issue is pretty easy, but I added mine to my [parcel-issue-repro](https://github.com/davidnagli/parcel-issue-repro/tree/master/865) if you wanna just use that to make your life easier.

### For anybody else running into this issue looking for a quick fix: Run Parcel with the `--no-hmr` flag
