### ISSUE TITLE
CSS module import: Cannot find module or its corresponding type declarations

### ISSUE THREAD

**Issue by caxapexac** [parcel-bundler/parcel#8650]
# 🐛 bug report

Clion IDE

![image](https://user-images.githubusercontent.com/33996246/203030318-0f0a41f3-fdc1-41d1-94af-3500091b2c2c.png)

## 🎛 Configuration (.babelrc, package.json, cli command)

tsconfig
```json
{
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "esModuleInterop": true,
        "jsx": "react",
        "jsxImportSource": "react"
    }
}
```

## 🤔 Expected Behavior

Docs doesn't say anything about prerequisites:

![image](https://user-images.githubusercontent.com/33996246/203032210-519097f2-4fcd-44ee-84c0-3e8ba033be2a.png)

## 😯 Current Behavior

Intellisense doesn't work

## 💁 Possible Solution

https://stackoverflow.com/questions/70485587/reactjs-cannot-find-module-app-module-css-or-its-corresponding-type-declara

declarations.d.ts
```ts
declare module '*.css';
```
It works but looks like a crutch

**Comment by mischnic** [comment]
See https://github.com/parcel-bundler/parcel/issues/7264. We should also add something to the docs.
