### ISSUE TITLE
Parcel not reload changes(I just give up)

### ISSUE THREAD

**Issue by ambastos** [parcel-bundler/parcel#8657]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🤔 Expected Behavior

   When I change files, Parcel do not reload them even if I refresh. So, I just giveup! And instead I'm using Live-server inside the VSCODE and it works fine!
## 😯 Current Behavior

I change the page and it's not reflect even If I refresh the page

## 💁 Possible Solution

    I've seen many messages like this in this and other foruns and any solution found. So, I am just here to say that I give up fro parcel and even snowpack(for another reasons) and just use a simple live server
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.0 ou 2.0.0
| Node             | 16.xxx
| npm/Yarn         | npm
| Operating System | windows 10

**Comment by devongovett** [comment]
Without some kind of reproduction, this is not an actionable issue for us. Sorry you had this experience though.

**Comment by ambastos** [comment]
> Without some kind of reproduction, this is not an actionable issue for us. Sorry you had this experience though.
For example,  I just create a new project with just some files
   folder: src:: index.html
                      style.css
                      app.js

When I change any of those, it not reflect the changes. Without  any configuration
The content of the package.json:
`{
  "devDependencies": {
    "parcel": "^2.8.0"
  }
}
`
It doesn't work.(They starts but doesn't reflect the changes, only if stop and reestart the server....
It's strange, because in another computer it works! Even with Parcel 2.0.0, it doens't work as well...)
