### ISSUE TITLE
Updating to 2.8.0 from 2.6.2 breaks production build for @parcel/config-webextension

### ISSUE THREAD

**Issue by everdimension** [parcel-bundler/parcel#8664]
# 🐛 bug report

After updating to 2.8.0, running the script shows the following error:
```
Uncaught ReferenceError: $ce507344e8a6f2ed$export$405d0624ed55a03f is not defined
    at queryClient.ts:4:28
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```
// .parcelrc
{
  "extends": "@parcel/config-webextension",
  "transformers": {
    "jsx:*.svg": ["@parcel/transformer-svg-react"],
    "jsx:*": ["..."]
  }
}
```

```
// package.json
  "@parcel/bundler-default": {
    "minBundles": 10000000,
    "minBundleSize": 3000,
    "maxParallelRequests": 20
  },
```

Building is done by running this command:

```sh
parcel build src/manifest.json --no-content-hash
```

```js
{
  "your": { "config": "here" }
}
```

## 💁 Possible Solution

May be related to this: https://github.com/parcel-bundler/parcel/issues/8071

Currently, downgrading to 2.6.2 works.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.0
| Node            | v16.14.0
| npm/Yarn        | 8.3.1
| Operating System  | macos 11.5.1

**Comment by mischnic** [comment]
Please try the nightly version, this is hopefully fixed already: https://github.com/parcel-bundler/parcel/issues/8624
