### ISSUE TITLE
Build in developement mode

### ISSUE THREAD

**Issue by caxapexac** [parcel-bundler/parcel#8665]
`Parcel build` can now only output production build, even with `--no-optimize`. I have third-party webserver so I can't use parcel serve. How to build developement build?

**Comment by mischnic** [comment]
`parcel watch` also does development builds. Would that fit your usecase?

**Comment by caxapexac** [comment]
@mischnic no it didn't help. `parcel watch` doesn't create files in the dist directory just like a `serve`

**Comment by mischnic** [comment]
Well, it does/should. The question is why it doesn't in your case.

**Comment by caxapexac** [comment]
I think its because of https://github.com/parcel-bundler/parcel/issues/8649

**Comment by caxapexac** [comment]
@mischnic could you please take a look at https://github.com/parcel-bundler/parcel/issues/8649? Its been a month already
