### ISSUE TITLE
Material UI React applications don't package correctly

### ISSUE THREAD

**Issue by tomkcook** [parcel-bundler/parcel#8674]
# 🐛 bug report

A simple app using Material UI works when served from the ParcelJS built-in development server but not when parcelled with `parcel build`.  A complete example is given in the "configuration" section below.  To reproduce on the source code below, run `npm run dist`, edit the resulting `dist/index.html` to remove the leading `/` from the JS path, then load the resulting HTML in Chrome.  Or serve the parcelled files from any web server.

I don't have a babel configuration, or not one that I've edited.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dist": "parcel build --no-cache --no-minify index.html"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel-bundler": "^1.12.5"
  },
  "dependencies": {
    "@emotion/styled": "11.10.5",
    "@emotion/react": "11.10.5",
    "@mui/material": "5.10.16",
    "@types/react": "18.0.26",
    "@types/react-dom": "18.0.9",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  }
}
```

```js
import * as React from 'react';
import { Button } from '@mui/material';
import { render } from 'react-dom';
import { createRoot } from 'react-dom/client';

function App() {
  return <Button>Test</Button>;
}

const container = document.getElementById("root");
console.log(container);
const root = createRoot(container);
root.render(<App/>);
```

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Test</title>
</head>

<body>
  <div id="root"></div>
  <script src="test.js"></script>
</body>

</html>
```

## 🤔 Expected Behavior

Browser should display a button with the text "TEST".

## 😯 Current Behavior

```
test.b20cb9fc.js:5710 Uncaught TypeError: Cannot read properties of undefined (reading 'default')
    at Object.get [as unstable_generateUtilityClasses] (test.b20cb9fc.js:5710:36)
    at Object.get [as default] (test.b20cb9fc.js:14307:19)
    at Object.parcelRequire.eW5O.../generateUtilityClass (test.b20cb9fc.js:22952:59)
    at newRequire (test.b20cb9fc.js:47:24)
    at localRequire (test.b20cb9fc.js:53:14)
    at Object.parcelRequire.K26e.@babel/runtime/helpers/esm/extends (test.b20cb9fc.js:22969:30)
    at newRequire (test.b20cb9fc.js:47:24)
    at localRequire (test.b20cb9fc.js:53:14)
    at Object.parcelRequire.jIKT../OptionUnstyled (test.b20cb9fc.js:23127:46)
    at newRequire (test.b20cb9fc.js:47:24)
```

## 🔦 Context

Parcelling any MUI application appears to suffer from this problem.

## 💻 Code Sample

As above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.5 |
| Node             | v16.15.0 |
| npm/Yarn         | 8.5.5 |
| Operating System | Ubuntu 22.04 |

**Comment by mischnic** [comment]
Parcel 1 isn't supported anymore. This works correctly with Parcel 2.

**Comment by tomkcook** [comment]
I'm so sorry for wasting your time.  If it's any comfort, I wasted a considerable quantity of mine in figuring this out, too.
