### ISSUE TITLE
weird characters after build

### ISSUE THREAD

**Issue by Belouccio** [parcel-bundler/parcel#8675]
Hi there! I use parcel to build my preact app. After build, some symbols (cyrrilic) randomly replaces to ��, you can see that on the screenshot below. How can i fix that, any ideas?

![image](https://user-images.githubusercontent.com/25301055/205921229-c3171494-5f4e-456d-8c17-2980d4c4ebdf.png)

it randomply replace symbols after each build, if i run build command again (without any changes), this symbol will be nice, but other will broken

parcel verrsion: 'next'
preact version: 10.5.14
nodejs: v14.15.0
system: ubuntu 16

**Comment by mischnic** [comment]
Please share some source code that causes this behaviour.
