### ISSUE TITLE
Cannot find bundle id in release build

### ISSUE THREAD

**Issue by tmpfs** [parcel-bundler/parcel#8680]
# 🐛 bug report

Release build yields a bundle not found error but development build works fine.

## 🤔 Expected Behavior

Release build should work the same as the development build.

## 😯 Current Behavior

My program works fine using the parcel development server but when I create a release build using the `build` command I get a bundle not found error in the browser:

```
Error: Could not resolve bundle with id ePjiX
```

I am using webassembly and web workers and setting the appropriate headers (`.proxyrc.js`):

```javascript
module.exports = function (app) {
  app.use((req, res, next) => {
    res.setHeader("Cross-Origin-Embedder-Policy", "require-corp");
    res.setHeader("Cross-Origin-Opener-Policy", "same-origin");
    next();
  });
};
```

This command works:

```
parcel src/index.html --port 7070
```

Then when I build using:

```
parcel build src/index.html
```

The generated build yields that error. Note that I am also setting the correct HTTP headers when running the release build.

## 💻 Code Sample

https://github.com/LavaMoat/tss-snap/tree/main/snap/dapp

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.0
| Node             | 16.3.2
| npm/Yarn         | yarn@1.22.17 npm@8.1.2
| Operating System | MacOS Monterey M1

**Comment by tmpfs** [comment]
Possibly related to: https://github.com/parcel-bundler/parcel/issues/7609

Building with `--no-scope-hoist` does not fix the problem.

Note that the code uses a `Worker` like this:

```javascript
const webWorker = new Worker(new URL("./worker.ts", import.meta.url), {
  type: "module",
});
```

**Comment by tmpfs** [comment]
Downgrading to 2.7.0 does not fix the issue, also I tried going all the way back to `2.0.0-rc.0` and the problem still exists.

**Comment by tmpfs** [comment]
My only workaround is using webpack to generate the release build which is a shame as I much prefer parcel.

**Comment by mischnic** [comment]
What commands do I need to execute after cloning to then successfully run `parcel src/index.html --port 7070` or `parcel build src/index.html`? (And also, on which commit in case you changed the build setup in the meantime)

**Comment by tmpfs** [comment]
Thanks @mischnic  for taking a look, it's actually a little awkward to set up as it relies on some webassembly compiled using Rust.

You should be able to reproduce on HEAD.

For docker I have to use a relative file path for a particular dependency (due to a flaw with `wasm-bindgen` packaging), see:

https://github.com/LavaMoat/tss-snap/blob/main/snap/dapp/package.json#L53

If you change that to use the version in npm (`0.2.1`):

https://www.npmjs.com/package/@lavamoat/mpc-ecdsa-wasm

Then you shouldn't have to worry about compiling the WASM. If that doesn't work you will need the rust toolchain and `wasm-pack` installed and then should be able to run `make wasm` at the top-level of the repository.

You will also need a `.env.production` in the `snap/dapp` folder that looks like this:

```
INFURA_API_KEY=XXX
WS_URL=wss://tss.ac/mpc
SNAP_ID=npm:@lavamoat/tss-snap
```

Then to reproduce the problem in `dist`:

```
cd snap/dapp
yarn install
yarn clean && yarn build   # parcel release build which exhibits the error
```

Then to start a static server that sets the appropriate HTTP headers (assuming you have the rust toolchain installed) - this will use the relative path to the `dist` folder by default:

```
cd cli
cargo run
```

Now visit `http://localhost:3030`; the error should be visible in the console logs.

I upgraded to `2.8.2` yesterday and just checked a parcel release build again and am able to reproduce the problem.

Thanks!
