### ISSUE TITLE
Watch does not work underneath directory containing parentheses

### ISSUE THREAD

**Issue by mrcoles** [parcel-bundler/parcel#869]
## 🐛 bug report

I’m noticing that `parcel src/index.html` is not seeing any changes in my file when it is in a directory underneath a Dropbox directory on my computer.

### 🎛 Configuration (.babelrc, package.json, cli command)

No configuration, just a single `index.html` file and `parcel src/index.html`.

### 🤔 Expected Behavior

Editing `src/index.html` should result in a new build getting kicked off while running `parcel src/index.html`.

### 😯 Current Behavior

When I edit `src/index.html`, like add some extra letters inside the `h1` tag, no build is kicked off in my terminal and refreshing the webpage localhost:1234 shows no changed.

If I stop and restart `parcel src/index.html`, then it *will* reflect the change.

This happens in both my personal (`~/Dropbox\ \(Personal\)/test-parcel/`) and work (`~/Dropbox\ \(Work\)/test-parcel/`) dropbox folders.

*If I create the project in my home directory `~/test-parcel/`, then it works fine.*

I tried creating a symlinked directory in my home directory, thinking this could be the issue from Dropbox, but this directory worked fine too.

I ran a script to check `fs.statSync(filepath).mtime` of files in the different directories, and they appeared to have updated mtimes after editing just fine.

### 💁 Possible Solution

🤷‍♀️ 

### 🔦 Context

This meant, I had to kill and restart `parcel src/index.html` to test any change while developing.

### 💻 Code Sample

Create the project with the following bash commands:

```bash
mkdir -p test-parcel/src/
cd test-parcel
echo '<!DOCTYPE html>
                  <html>
                    <head>
                      <meta charset=utf-8>
                      <title>Test Parcel with Dropbox</title>
                    </head>
                    <body>
                      <h1>Test</h1>
                    </body>
                  </html>' > src/index.html
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.5.1 |
| Node             | v9.5.0 |
| Yarn         | 1.3.2 |
| Operating System | OS X 10.13.2 |
| Dropbox | v43.4.50 |

**Comment by devongovett** [comment]
Mmm interesting. It's possible dropbox blocks fs events from occurring. Maybe this is another situation where we need polling?

**Comment by mrcoles** [comment]
Also, FWIW, `create-react-app` sees changes for me in this situation.

setup:

```bash
$ create-react-app -V
1.5.2
$ create-react-app test-create-react-app
$ cd test-create-react-app/
$ yarn start
```

Then edit `src/App.js` and http://localhost:3000/ auto-updates.

**Comment by mrcoles** [comment]
IDK if this is potentially related, but running `yarn run test` I’m seeing some errors show up, which seem to be related to micromatch not handling parenthesis in filenames properly.

```
  1) glob should require a glob of files:
     TypeError: Cannot read property 'slice' of null
      at GlobAsset.load (src/assets/GlobAsset.js:27:10)
      at GlobAsset.loadIfNeeded (src/Asset.js:49:34)
      at GlobAsset.process (src/Asset.js:153:18)
      at Pipeline.processAsset (src/Pipeline.js:32:19)
      at Pipeline.process (src/Pipeline.js:16:32)
      at Object.exports.run (src/worker.js:17:33)
      at src/utils/promisify.js:4:13
      at new Promise (<anonymous>)
      at Object.run (src/utils/promisify.js:3:12)
      at WorkerFarm.run (src/WorkerFarm.js:97:38)
      at Bundler.loadAsset (src/Bundler.js:439:35)
      at Promise.all.dependencies.map (src/Bundler.js:469:24)
      at <anonymous>
```

I filed this issue with micromatch: https://github.com/micromatch/micromatch/issues/123
