### ISSUE TITLE
ESM output errors importing commonjs modules

### ISSUE THREAD

**Issue by pedromcunha** [parcel-bundler/parcel#8692]
# 🐛 bug report

I'm converting a package from commonjs to esm and getting some errors when importing external commonjs modules. Here are some of the errors I'm receiving:

```
SyntaxError: Named export 'Arrow' not found. The requested module '@radix-ui/react-popover' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@radix-ui/react-popover';
const {Arrow: $TBcmg$Arrow, Content: $TBcmg$Content1, Root: $TBcmg$Root2, Trigger: $TBcmg$Trigger1, Portal: $TBcmg$Portal1} = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:435:15) {
  page: '/'
}
```

Also a secondary issue is that we're running into some errors because imports don't have file extensions when referencing a particular file. This is a lesser issue as we can just add the file extension manually but was hoping maybe there was a solution when generating the module as well.

## 🎛 Configuration (.babelrc, package.json, cli command)

The relevant package.json properties look like this:
```js
{
    ...
    "source": "src/index.ts",
   "exports": "./dist/index.module.js",
   "module": "dist/index.module.js",
   "types": "dist/index.d.ts",
   "type": "module",
   "files": [
    "dist"
    ],
   ...
}
```

## 🤔 Expected Behavior

Generating the module should take care of converting these imports to something that works for ESM modules, or it should error out and not generate a build.

## Environment

Parcel: 2.6.2
Nodejs: 18.2.0
MacOS 12.2.1 (Monterey)

**Comment by devongovett** [comment]
The error shown appears to be coming from Node, not Parcel. Could you provide more details on how to reproduce?

**Comment by pedromcunha** [comment]
Yeah I think you're actually correct. Spent a whole day debugging these errors. Seems like a specific nextjs issue when importing my library that I built with parcel. In the end what fixed it was this module that transpiles packages when building them on the server: https://github.com/martpie/next-transpile-modules, which suggests that it's a nextjs issue with their build system (webpack 5)
