### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by bq-hentai** [parcel-bundler/parcel#87]
In README, the **HOW IT WORK** section,

`Once the asset tree **as** been constructed, the assets are placed into a bundle tree.`

Maybe it should be

`Once the asset tree **has** been constructed, the assets are placed into a bundle tree.`

:P

**Comment by davidnagli** [comment]
Why don’t you just change it and make a PR? :)

**Comment by bq-hentai** [comment]
I will next time :+1:
