### ISSUE TITLE
deprecation warning when installing: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated.

### ISSUE THREAD

**Issue by ChillerDragon** [parcel-bundler/parcel#8701]
# 🐛 bug report

```
$ npm i parcel
⸨#########⠂⠂⠂⠂⠂⠂⠂⠂⠂⸩ ⠙ idealTree:posthtml: sill placeDep node_modules/@parcel/transformer-html semver@5.7npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
```

## 🤔 Expected Behavior

Installing parcel should not show any deprecation warnings.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2.8.2
| Node             | v16.13.1
| npm         | 8.1.2
| Operating System | Linux debian 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux

**Comment by mischnic** [comment]
This is caused by svgo

https://github.com/parcel-bundler/parcel/blob/da6cbb3633d2c0e9fedb8e2af560c82504d05ddc/yarn.lock#L12460-L12471

so upgrading from version 2 to 3 would solve this.
