### ISSUE TITLE
Glob resolver doesn't support `/` and `~`

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#8704]
# 🐛 bug report

These don't work correctly (the glob resolver doesn't replace these special start characters with the correct absolute path before resolving the glob):
```js
import images from "/assets/*.png";
import images from "~/assets/*.png";
```

## 💁 Possible Solution

Handle these cases here:
https://github.com/parcel-bundler/parcel/blob/da6cbb3633d2c0e9fedb8e2af560c82504d05ddc/packages/resolvers/glob/src/GlobResolver.js#L135-L137

This is what the default resolver does:
https://github.com/parcel-bundler/parcel/blob/da6cbb3633d2c0e9fedb8e2af560c82504d05ddc/packages/utils/node-resolver-core/src/NodeResolver.js#L578-L614

## 💻 Code Sample

- `assets` contains png image files.
- Then the imports above should return those instead of an empty object.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.2

**Comment by debanjanbanerjee46** [comment]
i want to work on this

**Comment by cacti23** [comment]
@mischnic please assign me this issue. I would love to work on this

**Comment by Bhavyaatrivedi** [comment]
Can I work on this issue
