### ISSUE TITLE
Regression: parcel@2.8.1 build keeps undefined `$7f9d4f94f3d938e3$re_export$bool` for ESM

### ISSUE THREAD

**Issue by arty-name** [parcel-bundler/parcel#8705]
# 🐛 bug report

When I build my project using `parcel build` the output file includes an undefined identifier `$7f9d4f94f3d938e3$re_export$bool`. Trying to actually use it results in error.

This error only started appearing after #8624 was fixed.

## 🎛 Configuration (.babelrc, package.json, cli command)

The [parcel configuration of the project](https://github.com/BTE-Trusted-Entity/didsign/blob/main/package.json#L84-L90) is pretty basic
```json
  "targets": {
    "default": {
      "source": "src/index.html",
      "distDir": "build",
      "context": "browser"
    }
  },
```

## 🤔 Expected Behavior

When optimizing the code parcel should not remove declarations of constants that are used in the code.

## 😯 Current Behavior

The code includes the line `e(aA,"bool",(()=>$7f9d4f94f3d938e3$re_export$bool)),..` and `$7f9d4f94f3d938e3$re_export$bool` is not defined anywhere, resulting in runtime errors.

## 💁 Possible Solution

Stay on parcel@2.7.0 for now?

## 🔦 Context

I was trying to upgrade a [project](https://github.com/BTE-Trusted-Entity/didsign/) to use the parcel@2.8.1 and will not do this now. 

## 💻 Code Sample

[The parcel update PR in my project](https://github.com/BTE-Trusted-Entity/didsign/pull/154) and [it’s deployed version](https://pr-154.d3lrbynfv0twvc.amplifyapp.com/).

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.8.1
| Node             |v18.12.1
| npm/Yarn         |1.22.19
| Operating System |Ubuntu 22.04.1

**Comment by mischnic** [comment]
MInimal Reproduction:
```js
import * as ns from "./library/b";
console.log(ns, ns.value1, ns.value2);

// library/package.json 
{ "sideEffects": false }

// library/b.js
export { value1, value2 } from './c.js';

// library/c.js
export { value1, value1 as value2 } from "./d";

// library/d.js
export const value1 = 2;
```

A regression caused by https://github.com/parcel-bundler/parcel/pull/8432
