### ISSUE TITLE
Inconsistent javascript `arguments` behavior between live development and production builds

### ISSUE THREAD

**Issue by phfaist** [parcel-bundler/parcel#8706]
Hi, Thanks first of all for this really wonderful and useful project!

# 🐛 bug report

I noticed what appears to be an inconsistency in how the `arguments` keyword in javascript is handled within a module, depending on if I run parcel in development mode or in production build mode.

In strict mode (in particular, in ES modules), the `arguments` keyword should not sync with the function names [according to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#no_syncing_between_parameters_and_arguments_indices). That is, assigning to a function's argument name should not modify the object referred to by the `arguments` keyword.

However, there appears to be a situation, when running parcel's development server, where the presence of a single import statement switches to the incorrect behavior of the keyword 'arguments'. This situation seems to reflect javascript's non-strict mode. Parcel's production builds do not seem to be affected.

Here's a minimal working example. The issue appears with parcel 2.8.2 as well as with parcel 2.7.0.

`parcel_arguments_bug.js`:
```js
'use strict'; // add this just to be sure, even though this is a module

// comment out the following line to mysteriously restore the expected behavior in live devel mode
import './empty.js';

// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#no_syncing_between_parameters_and_arguments_indices

function testargs1(a, b)
{
    var b = 1;
    console.log('named arguments: ', [a, b],
                ' (should be ["one", 1])');
    console.log('"arguments": ', [...arguments],
                ' (should be ["one", {...}] in strict mode)');

    if (b === arguments[1]) {
        throw new Error("*** Modifying `b` should not have also modified `arguments[1]`");
    } else {
        console.log("All good, `b` and `arguments[1]` are not synced.");
    }
}

testargs1('one', {'key': 'value'});
```

`empty.js` is an empty file.

`parcel_arguments_bug.html`:
```html
<!DOCTYPE HTML>
<html>
<head>
<script type="module" src="./parcel_arguments_bug.js"></script>
</head>
<body></body>
</html>
```

## 🎛 Configuration (.babelrc, package.json, cli command)

No `.babelrc`.

`package.json`:
```js
{
  "name": "parcel-live-bug",
  "packageManager": "yarn@3.3.0",
  "dependencies": {
    "parcel": "^2.8.2",
    "sirv-cli": "^2.0.2"
  }
}
```

`.yarnrc.yml`:
```yaml
nodeLinker: 'node-modules'
```

Run in development server:
```sh
yarn parcel parcel_arguments_bug.html
```
→ point browser to `http://localhost:1234` and observe the exception in the JS console.

Run production build:
```sh
yarn parcel build parcel_arguments_bug.html && yarn sirv dist/
```
→ point browser to `http://localhost:8080/parcel_arguments_bug.html` and observe the expected behavior in the JS console.

## 🤔 Expected Behavior

The `arguments` keyword in the function `testargs1()` should not be affected by the assignment to `b` at the beginning of the function. The exception in `testargs1()` (with message '*** Modifying ...') should not fire.

## 😯 Current Behavior

In parcel's development server, the `arguments` keyword in the function `testargs1()` is affected by the assignment to `b` at the beginning of the function. The exception in `testargs1()` (with message '*** Modifying ...') fires.

Furthermore, if I comment out the dummy import statement, then the Expected Behavior is mysteriously restored.

In the production build, everything seems to work according to the Expected Behavior, regardless of whether or not the import statement is present.

## 💁 Possible Solution

No idea, sorry.

## 🔦 Context

This issue appeared while bundling code generated by the wonderful [Transcrypt](https://transcrypt.org/) Python-to-JavaScript transliteration tool. The code generated by Transcrypt to mimic python's keyword arguments syntax (kwargs) uses the `arguments` JS keyword in a way that is affected by the present issue.

## 💻 Code Sample

see above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.2 or 2.7.0
| Node             | v19.2.0
| npm/Yarn         | Yarn 3.3
| Operating System | macOS Ventura 13.0.1

**Comment by mischnic** [comment]
Yeah, the current behaviour is quite inconsistent. I think we don't handle strict mode anywhere explicitly. And adding `"use strict";` manually just works by accident in some cases, this explains why adding the import changes the strict mode in your example:

<img width="859" alt="Bildschirm­foto 2022-12-21 um 16 23 24" src="https://user-images.githubusercontent.com/4586894/208940631-cbd44f1b-e595-4027-aadb-71b12fa28e31.png">

<img width="872" alt="Bildschirm­foto 2022-12-21 um 16 23 31" src="https://user-images.githubusercontent.com/4586894/208940651-e8606d44-3a15-4dae-93a8-71c0d18944fd.png">

---

Parcel can't really retain the strict-mode-ness of the input files either, because once you're using `<script type="module">` in production, then it's always strict anyway.

So we should just add `"use strict";` at the top of every bundle. And then if some packages break because they expect non-strict-mode, then it's the package's fault because they can't be used in module script tags.
