### ISSUE TITLE
web extension dynamic entry point

### ISSUE THREAD

**Issue by sergey-shpak** [parcel-bundler/parcel#8707]
Hi guys, 
I'm working on web extension and we are planning to support new browsers soon, but there are differences between manifest file properties for different browsers and versions which cannot be combined into single manifest file(like for example `minimum_chrome_version` and `minimum_opera_version` etc). So it would be awesome if there would be possibility to set different entry points for web extension, for example:
```json
"bundle:chrome": "parcel build src/chrome.manifest.json --dist-dir ./chrome  --no-cache",
"bundle:firefox": "parcel build src/firefox.manifest.json --dist-dir ./firefox  --no-cache",
```

**Comment by mischnic** [comment]
This is already almost possible, see https://github.com/parcel-bundler/website/pull/1052#issuecomment-1312425002

Would be great if someone could fix that last bit
