### ISSUE TITLE
Async functions are always transformed to regenerator runtime

### ISSUE THREAD

**Issue by aocenas** [parcel-bundler/parcel#871]
🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)
Without config just do
```
yarn init
yarn add parcel-bundler
```
create index.js:
```
(async function () { return await 1 })()
```

```
parcel index.js
```

### 🤔 Expected Behavior
Without any babel config I would assume no transformation will be made, just bundling into one file.

### 😯 Current Behavior
Dist file will contain
```
_asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee() {
...
```

### 🔦 Context

In specific project async functions are transformed no matter what .babelrc I try. I am trying to migrate from browserify but using
```
node_modules/.bin/parcel build ./src/client/index.js --out-dir ./public --out-file bundle.js --no-minify
```
will give me code with async functions transformed, where
```
node_modules/.bin/browserify ./src/client/index.js -o ./public/bundle.js -t [ babelify ]
```
will keep async functions unchanged. I would expect these to behave the same in regards to babel transforms.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.2
| Node             | v8.1.4
| npm/Yarn         | 1.3.2
| Operating System | Mac

**Comment by aocenas** [comment]
Seems like it could be related to https://github.com/parcel-bundler/parcel/issues/509 somehow, but `no-cache` does not help and I did not have any async transform set up anywhere.

**Comment by devongovett** [comment]
Parcel automatically applies babel-preset-env to some default engines (> 1% marketshare). You can change your app's browser targets by adding a `browserslist` key to your package.json.

**Comment by aocenas** [comment]
@devongovett Thanks for quick reply. As you say using `env` preset and specific targets helped. Sorry, this was not clear to me from the documentation and is a bit confusing when having a `.babelrc` defined. I would still assume that defining `.babelrc` would override the default transforms, while at the moment it seems it is merging them in some sense.

**Comment by davidnagli** [comment]
@aocenas That’s a good point. If you want, feel free to open up an issue in the website repo so it get’s added to the docs 👍

**Comment by AbeEstrada** [comment]
I was getting this error when using `async/await`:
`ReferenceError: regeneratorRuntime is not defined`

My solution was adding: `import "babel-polyfill";`

Leaving this comment for reference.

**Comment by silvestrevivo** [comment]
Here my solution: 
npm install --save-dev babel-plugin-transform-runtime
And in .babelrc 
`{
  "plugins": ["transform-runtime"]
}`

**Comment by brandiqa** [comment]
Found this solution:

```bash
npm install --save-dev babel-plugin-transform-runtime babel-runtime
```

Create .babelrc file and add:
```js
{
    "plugins": [
        ["transform-runtime",
        {
            "polyfill": false,
            "regenerator": true
        }]
    ]
}
```

**Comment by silvestrevivo** [comment]
@brandiqa that solutions looks like very similar to mine but more complete. That is nice!!

**Comment by NullVoxPopuli** [comment]
@brandiqa this doesn't seem to work when typescript is involved.

tsconfig.json
```
{
  "compilerOptions": {
    "jsx": "react",
    "experimentalDecorators": true,
    "lib": ["es2017", "dom"],
    "target": "es2018",
    "baseUrl": ".",
    "paths": {
      "react": ["node_modules/@types/react/index.d.ts"],
      "redux": ["node_modules/redux/index.d.ts"],
      "react-toastify": ["node_modules/react-toastify/index.d.ts"]
    }
  }
}
```

**Comment by theoutlander** [comment]
I had accidentally set the config value to:

```
"plugins": [
    [
      "transform-object-rest-spread",
      "syntax-dynamic-import",
      "transform-runtime",
      {
        "polyfill": false,
        "regenerator": true
      }
    ],
    "syntax-dynamic-import"
  ]
```
Changing it to the following worked for me:

```
"plugins": [
    "transform-object-rest-spread",
    "syntax-dynamic-import",
    [
      "transform-runtime",
      {
        "polyfill": false,
        "regenerator": true
      }
    ],
    "syntax-dynamic-import"
  ]
```

**Comment by janat08** [comment]
Perhaps the runtime transform should be default?

**Comment by tajchumber** [comment]
> Found this solution:
> 
> ```shell
> npm install --save-dev babel-plugin-transform-runtime babel-runtime
> ```
> 
> Create .babelrc file and add:
> 
> ```js
> {
>     "plugins": [
>         ["transform-runtime",
>         {
>             "polyfill": false,
>             "regenerator": true
>         }]
>     ]
> }
> ```

I'm trying this and I still can't get it to work:
![screenshot 2018-10-29 at 15 10 25](https://user-images.githubusercontent.com/16062635/47659411-cf064880-db8c-11e8-9e7d-d30e29741ddb.png)

I'm simply trying to add ckeditor to my application.

**Comment by wesbos** [comment]
In case anyone skimmed past @devongovett's you can fix this by just specifying the browsers you are targeting in your package.json:

```
"browserslist": [
    "last 1 version"
  ],
```

**Comment by wesbos** [comment]
I run into this all the time with demos - so if you want to just ignore this error and use the browsers built in async/await I use this for a quick fix without having to install any babel plugins:

```
"browserslist": [
    "last 1 Chrome version"
  ],
```

**Comment by thedamon** [comment]
Is this supposed to work somehow without babel-polyfill? 

I tried all the .babelrc plugin settings to no avail.. babel-polyfill did it, but it's a pretty heavy dependency to make something work that actually [works natively in all evergreen browsers](https://caniuse.com/#feat=async-functions) now

**Comment by gcv** [comment]
@thedamon: I didn't want to use `babel-polyfill` either, but @wesbos's suggestion of using `browserslist` works well. I added the following to `package.json`:

```
  "browserslist": [
    "since 2017-06"
  ],
```

**Comment by Cody0913** [comment]
Just an update to @brandiqa solution for those with a babel version of 7^.
The polyfill option has been removed from the transform-runtime plugin has been removed and is now just the following:
`
["@babel/plugin-transform-runtime",
      {
        "regenerator": true
      }
    ]`

**Comment by thedamon** [comment]
@gcv.. yeah that would work for a lot of users.. i think i just wish there was a way to use async/await simply and still support IE11.. kinda the point of babel.. but without needing the babel-polyfill on all sites because it's like 300k and that's nuts. currently i can't make it work in Chrome without babel-polyfill and that actually makes no sense because it shouldn't be necessary because it shouldn't have anything to polyfill.

but this applies to babel moreso than parcel so i'll stick a lid on it 😋

**Comment by adrianmcli** [comment]
@thedamon Does adding `@babel/plugin-transform-runtime` work for you? Or does it also bloat the production build?

**Comment by MarvelousWololo** [comment]
I love how after one year and half we still don't have a definitive answer for this question. Every solution here includes adding a bunch of dependencies to your project and stopping doing that when the issue actually ceases or seems to be solved.

Gotta love modern JS tooling. It's 2019 and we are struggling to do a simple HTTP request. On the web. <3

**Comment by gcv** [comment]
True, true, but let's remember that web development is the process of shoehorning state into a stateless evolution of [Gopher](https://en.wikipedia.org/wiki/Gopher_(protocol)), and — on the front end — forcing a system with dreadful display primitives and brain-damaged programming support to work as a universal application delivery system. The web browser exemplifies [worse is better](https://www.dreamsongs.com/RiseOfWorseIsBetter.html) in modern software. It's 2019, and we are struggling because turning this lousy platform into a high-level nice-to-program system with nice abstractions is such a _bloody_ hard problem.

**Comment by adrianmcli** [comment]
On a more practical note, should we petition the team to re-open this issue or perhaps open a new one?

**Comment by mischnic** [comment]
Related: https://github.com/babel/babel/issues/8829#issuecomment-480706039

**Comment by adrianmcli** [comment]
@mischnic Thanks for re-opening!

**Comment by TempD** [comment]
Just want to leave a note and say that my code worked with this fix now. Running Babel core 7.7.5. Here is my .babelrc:
```
{
    "presets": ["@babel/preset-react"],
    "plugins": [
        [
            "@babel/plugin-transform-runtime",
            { "regenerator": true }
        ]
    ]
}
```

> Just an update to @brandiqa solution for those with a babel version of 7^.
> The polyfill option has been removed from the transform-runtime plugin has been removed and is now just the following:
> ` ["@babel/plugin-transform-runtime", { "regenerator": true } ]`

**Comment by wangcch** [comment]
I was also getting this error when using async/await:
ReferenceError: regeneratorRuntime is not defined

My solution is to change tsconfig `target`:

```json
// tsconifg.json
{
  "compilerOptions": {
    "target": "es5",
    ...
  },
  ...
}
```

For reference

**Comment by adrianmcli** [comment]
> Just want to leave a note and say that my code worked with this fix now. Running Babel core 7.7.5. Here is my .babelrc:
> 
> ```
> {
>     "presets": ["@babel/preset-react"],
>     "plugins": [
>         [
>             "@babel/plugin-transform-runtime",
>             { "regenerator": true }
>         ]
>     ]
> }
> ```
> 
> > Just an update to @brandiqa solution for those with a babel version of 7^.
> > The polyfill option has been removed from the transform-runtime plugin has been removed and is now just the following:
> > ` ["@babel/plugin-transform-runtime", { "regenerator": true } ]`

This works, but we shouldn't need to do this in 2019.

**Comment by rosman21** [comment]
> > Just want to leave a note and say that my code worked with this fix now. Running Babel core 7.7.5. Here is my .babelrc:
> > ```
> > {
> >     "presets": ["@babel/preset-react"],
> >     "plugins": [
> >         [
> >             "@babel/plugin-transform-runtime",
> >             { "regenerator": true }
> >         ]
> >     ]
> > }
> > ```
> > 
> > 
> > > Just an update to @brandiqa solution for those with a babel version of 7^.
> > > The polyfill option has been removed from the transform-runtime plugin has been removed and is now just the following:
> > > ` ["@babel/plugin-transform-runtime", { "regenerator": true } ]`
> 
> This works, but we shouldn't need to do this in 2019.

what other options do we have?

**Comment by corwin-of-amber** [comment]
> what other options do we have?

All major browsers and Node.js have had  async/await support for about two years now.
I have found that setting `"browserslist": "since 2017-06"` in `package.json` does not turn off the regenerator transform in babel, but e.g. `"browserslist": "Chrome 78"` does.

**Comment by danielfilho** [comment]
I have tried every single solution (and many combinations of those) in this whole thread and none seems to work for me 😞

**Comment by corwin-of-amber** [comment]
@danielfilho Are you using the latest version of `@babel/core`? I just tried with 7.8.4 and it still works as long as you include the `"browserslist": ["Chrome 78"]` in your `package.json` (without it it still breaks).

**Comment by danielfilho** [comment]
these are the versions I'm using:

```
 "devDependencies": {
    "@babel/core": "7.2.0",
    "@babel/preset-env": "^7.4.3",
    "babel-jest": "^24.7.1",
    "jest": "^24.7.1",
    "parcel-bundler": "^1.6.1"
  }```

Locally, I was trying to update all dependencies to the latest but the problem was still there. Even cleaning node_modules and npm cache.

I solved this giving up on doing locally and moving the development to codesandbox.io, which is far from ideal. But at least I could move on with the project.

I know how weird it sounds, but I tried everything, and then gave up to this solution. Thanks for asking, @corwin-of-amber.

**Comment by corwin-of-amber** [comment]
@danielfilho I am attaching a minimal code example that shows the problem so that you and other users visiting this issue could perhaps use to troubleshoot.

Notice how removing `browserslist` from `package.json` causes the error (`Can't find variable: regeneratorRuntime`).

[generator-minimal.zip](https://github.com/parcel-bundler/parcel/files/4148683/generator-minimal.zip)

**Comment by jcs224** [comment]
Thought I'd throw this in, as this seems like the most "correct" way (serious air quotes here) based on what seems like best practice in Babel and what actually ended up working for me:

**Install the plugin transform runtime**
```
npm install --save-dev @babel/plugin-transform-runtime
```
**Add this to your `.babelrc` file**
```js
{
  "plugins": ["@babel/plugin-transform-runtime"]
}
```

**Comment by zavan** [comment]
This may be helpful for those that need to make it work with old browsers (e.g.: with the default (or no) `browserslist`): https://github.com/parcel-bundler/parcel/issues/1762#issuecomment-628071116

**Comment by corwin-of-amber** [comment]
Seems like this is not fixed (as the workaround from 11/8/2020 shows?), is it no longer an issue in Parcel 2.0.0?

**Comment by mischnic** [comment]
- Re "Async functions are always transformed to regenerator runtime":
This is intentional, as the default browserslist simply contains browsers that don't support await/async. https://github.com/parcel-bundler/parcel/issues/871#issuecomment-551173805

- Re "Uncaught ReferenceError: regeneratorRuntime":
See https://github.com/parcel-bundler/parcel/issues/1762#issuecomment-714322965.

**Comment by corwin-of-amber** [comment]
> * Re "Uncaught ReferenceError: regeneratorRuntime":
>   See [#1762 (comment)](https://github.com/parcel-bundler/parcel/issues/1762#issuecomment-714322965).

Great! Thanks for adding this reference for anyone who encounters this error in the future.
