### ISSUE TITLE
parcel serve ignores targets.<target>.distDir

### ISSUE THREAD

**Issue by benvh** [parcel-bundler/parcel#8715]
# 🐛 bug report

``parcel serve --target <target>`` ignores ``distFolder`` configured for said target

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
  "targets": {
    "app": {
      "source": "src/index.html",
      "distDir": "build"
    }
```

## 🤔 Expected Behavior

running ``parcel serve --target app`` builds the app and outputs all of its files to the ``targets.app.distDir`` configured folder ``build`` + serves it through its dev server.

## 😯 Current Behavior
 ``parcel serve --target app`` completely ignores the ``distDir`` configuration value and always outputs everything to ``dist`` instead. Also note that ``parcel build --target app`` does properly takes into account the ``distDir`` value.

## 💁 Possible Solution

uncertain

## 🔦 Context

I am trying to set up a simple project using parcel and was configuring builld output location. Parcel ignoring your configuration and creating unexpected directories is confusing and not particularly nice.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.2
| Node             | 16.19.0
| npm/Yarn         | 8.19.3
| Operating System | voidlinux 6.0.13

**Comment by kaifaty** [comment]
Same for me on last version of parcel.

But it works if use cli command: 
```--target=docs --dist-dir=./docs/dist```

**Comment by joas8211** [comment]
I encountered this bug today with Parcel 2.9.3, Node v20.5.0, Yarn 1.22.19 on Arch Linux. I think this should be reopened.
