### ISSUE TITLE
@parcel/core: Failed to resolve 'core-js/core/dict' from

### ISSUE THREAD

**Issue by bilalnizamani1234** [parcel-bundler/parcel#8722]
what is solution of this error 

🚨 Build failed.

@parcel/core: Failed to resolve 'core-js/core/dict' from './src/js/controller.js'

  D:\building application forkify app\src\js\controller.js:10:21
     9 | import { async } from 'regenerator-runtime';
  > 10 | import { get } from 'core-js/core/dict';
  >    |                     ^^^^^^^^^^^^^^^^^^^
    11 |
    12 | // if (module.hot) {
 ////

this my package.json file

{
  "name": "building-application-forkify-app",
  "version": "1.0.0",
  "description": "",
  "default": "index.html",
  "scripts": {
    "start": "parcel index.html",
    "build": "parcel build index.html"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@parcel/transformer-sass": "^2.8.1",
    "@types/core-js": "^2.5.5",
    "@types/regenerator-runtime": "^0.13.1",
    "parcel": "^2.8.1"
  },
  "dependencies": {
    "core-js": "^3.26.1",
    "fractional": "^1.0.0",
    "regenerator-runtime": "^0.13.11"
  }
}

**Comment by mischnic** [comment]
Please provide a reproduction
