### ISSUE TITLE
glob entry not working when wrapped in single quotes

### ISSUE THREAD

**Issue by mbrinkl** [parcel-bundler/parcel#8725]
# 🐛 bug report

I followed [this](https://parceljs.org/features/targets/#%24-parcel-%3Centries%3E) example and setup my start script like this

`"start": "parcel './src/*.html'"`

When running `npm start`, nothing is built. If I remove the single quotes, it builds correctly.

## 💻 Code Sample

- `src` folder that contains an index.html and another html file

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.2 |
| Node             | 18.12.1 |
| npm        | 9.2.0 |
| Operating System | Windows 11 |

**Comment by mischnic** [comment]
What is the full path of that project? Any special characters or spaces in there?

**Comment by mbrinkl** [comment]
Created minimal example here https://github.com/mbrinkl/globbug

No special characters or spaces locally, the path to my local looks like C:\Users\Michael\desktop\globbug
