### ISSUE TITLE
An imported and then re-exported value is being excluded from the MJS build

### ISSUE THREAD

**Issue by stevenpetryk** [parcel-bundler/parcel#8748]
# 🐛 bug report

Hi, I have an interesting example of what I _think_ is unexpected behavior with library MJS builds. When I import something and then re-export it from my source file like this:

```tsx
import * as vec from './vec'
export {vec}
```

It doesn't get included in the MJS build. However, if I import and re-export it like this:

```tsx
import * as vec2 from './vec'
export const vec = vec2
```

It does get included! Seems odd.

## 🎛 Configuration (.babelrc, package.json, cli command)

- [`package.json`](https://github.com/stevenpetryk/mafs/blob/7ad530062f5c08e2d1797deaf717780bf230ba20/package.json)
- Build command: `pnpm build`

I think the easiest way to see this issue might be to just clone the affected repo and run `pnpm build` before and after the commit that fixed it. Let me know if you want a more isolated reproduction.

Here's the commit that fixed:
https://github.com/stevenpetryk/mafs/commit/7ad530062f5c08e2d1797deaf717780bf230ba20

Here's a commit where it is broken (the parent commit)
https://github.com/stevenpetryk/mafs/commit/8a07e283e2cf1ed0c671a4a9fc4af5bb31165040

Full reproduction steps:

```bash
git clone git@github.com:stevenpetryk/mafs.git
cd mafs

# Check out the bad commit
git checkout 8a07e283e2cf1ed0c671a4a9fc4af5bb31165040
pnpm install
pnpm build
# Take a look at build/index.mjs and see that it doesn't export vec

git checkout 7ad530062f5c08e2d1797deaf717780bf230ba20
pnpm build
# Take a look at build/index.mjs and see that it now _does_ export vec
```

## 🤔 Expected Behavior

I would expect that the first syntax above makes `vec` get re-exported in my output .mjs file.

## 😯 Current Behavior

The syntax above leads to `vec` not getting exported.

## 💁 Possible Solution

I do wonder if this is related to tree shaking. Perhaps Parcel doesn't notice that `export { vec }` constitutes a usage of `vec` so it is getting tree-shaken away?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.2
| Node             | 16
| pnpm        |  7.12.2
| Operating System | macOS 12.6 (Apple Silicon)

**Comment by mischnic** [comment]
`export * as vec from './vec'` also doesn't work (and is equivalent to your failing example)

[REPL](https://parcel2-repl.vercel.app/#JTdCJTIyZmlsZXMlMjIlM0ElNUIlNUIlMjIlMkZzcmMlMkZvdGhlci5qcyUyMiUyQyU3QiUyMnZhbHVlJTIyJTNBJTIyY2xhc3MlMjBUaGluZyUyMCU3QiU3RCU1Q25jb25zdCUyMHglMjAlM0QlMjAxMjMlM0IlNUNuZXhwb3J0JTIwJTdCVGhpbmclMkMlMjB4JTdEJTNCJTIyJTdEJTVEJTJDJTVCJTIyJTJGc3JjJTJGaW5kZXguanMlMjIlMkMlN0IlMjJ2YWx1ZSUyMiUzQSUyMmV4cG9ydCUyMColMjBhcyUyMHZlYyUyMGZyb20lMjAlNUMlMjIuJTJGb3RoZXIuanMlNUMlMjIlM0IlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlNUIlMjIlMkZwYWNrYWdlLmpzb24lMjIlMkMlN0IlMjJ2YWx1ZSUyMiUzQSUyMiU3QiU1Q24lMjAlMjAlNUMlMjJtb2R1bGUlNUMlMjIlM0ElMjAlNUMlMjJkaXN0JTJGaW5kZXguanMlNUMlMjIlNUNuJTdEJTIyJTdEJTVEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmVudHJpZXMlMjIlM0ElNUIlNUQlMkMlMjJtaW5pZnklMjIlM0FmYWxzZSUyQyUyMnNjb3BlSG9pc3QlMjIlM0F0cnVlJTJDJTIyc291cmNlTWFwcyUyMiUzQWZhbHNlJTJDJTIycHVibGljVXJsJTIyJTNBJTIyJTJGX19yZXBsX2Rpc3QlMjIlMkMlMjJ0YXJnZXRUeXBlJTIyJTNBJTIyYnJvd3NlcnMlMjIlMkMlMjJ0YXJnZXRFbnYlMjIlM0FudWxsJTJDJTIyb3V0cHV0Rm9ybWF0JTIyJTNBbnVsbCUyQyUyMmhtciUyMiUzQWZhbHNlJTJDJTIybW9kZSUyMiUzQSUyMnByb2R1Y3Rpb24lMjIlMkMlMjJyZW5kZXJHcmFwaHMlMjIlM0FmYWxzZSUyQyUyMnZpZXdTb3VyY2VtYXBzJTIyJTNBZmFsc2UlMkMlMjJkZXBlbmRlbmNpZXMlMjIlM0ElNUIlNUQlMkMlMjJudW1Xb3JrZXJzJTIyJTNBMCU3RCUyQyUyMnVzZVRhYnMlMjIlM0FmYWxzZSUyQyUyMmJyb3dzZXJDb2xsYXBzZWQlMjIlM0ElNUIlNUQlMkMlMjJ2aWV3cyUyMiUzQSU1QiUyMiUyRnNyYyUyRmluZGV4LmpzJTIyJTJDJTIyJTJGc3JjJTJGb3RoZXIuanMlMjIlMkMlMjIlMkZwYWNrYWdlLmpzb24lMjIlNUQlMkMlMjJjdXJyZW50VmlldyUyMiUzQTIlN0Q=)

**Comment by sambacha** [comment]
> # 🐛 bug report
> 
> 
> 
> Hi, I have an interesting example of what I _think_ is unexpected behavior with library MJS builds. When I import something and then re-export it from my source file like this:
> 
> 
> 
> ```tsx
> 
> import * as vec from './vec'
> 
> export {vec}
> 
> ```
> 
> 
> 
> It doesn't get included in the MJS build. However, if I import and re-export it like this:
> 
> 
> 
> ```tsx
> 
> import * as vec2 from './vec'
> 
> export const vec = vec2
> 
> ```
> 
> 
> 
> It does get included! Seems odd.
> 
> 
> 
> ## 🎛 Configuration (.babelrc, package.json, cli command)
> 
> 
> 
> - [`package.json`](https://github.com/stevenpetryk/mafs/blob/7ad530062f5c08e2d1797deaf717780bf230ba20/package.json)
> 
> - Build command: `pnpm build`
> 
> 
> 
> I think the easiest way to see this issue might be to just clone the affected repo and run `pnpm build` before and after the commit that fixed it. Let me know if you want a more isolated reproduction.
> 
> 
> 
> Here's the commit that fixed:
> 
> https://github.com/stevenpetryk/mafs/commit/7ad530062f5c08e2d1797deaf717780bf230ba20
> 
> 
> 
> Here's a commit where it is broken (the parent commit)
> 
> https://github.com/stevenpetryk/mafs/commit/8a07e283e2cf1ed0c671a4a9fc4af5bb31165040
> 
> 
> 
> Full reproduction steps:
> 
> 
> 
> ```bash
> 
> git clone git@github.com:stevenpetryk/mafs.git
> 
> cd mafs
> 
> 
> 
> # Check out the bad commit
> 
> git checkout 8a07e283e2cf1ed0c671a4a9fc4af5bb31165040
> 
> pnpm install
> 
> pnpm build
> 
> # Take a look at build/index.mjs and see that it doesn't export vec
> 
> 
> 
> git checkout 7ad530062f5c08e2d1797deaf717780bf230ba20
> 
> pnpm build
> 
> # Take a look at build/index.mjs and see that it now _does_ export vec
> 
> ```
> 
> 
> 
> ## 🤔 Expected Behavior
> 
> 
> 
> I would expect that the first syntax above makes `vec` get re-exported in my output .mjs file.
> 
> 
> 
> ## 😯 Current Behavior
> 
> 
> 
> The syntax above leads to `vec` not getting exported.
> 
> 
> 
> ## 💁 Possible Solution
> 
> 
> 
> I do wonder if this is related to tree shaking. Perhaps Parcel doesn't notice that `export { vec }` constitutes a usage of `vec` so it is getting tree-shaken away?
> 
> 
> 
> ## 🌍 Your Environment
> 
> 
> 
> 
> 
> 
> 
> | Software         | Version(s) |
> 
> | ---------------- | ---------- |
> 
> | Parcel           | 2.8.2
> 
> | Node             | 16
> 
> | pnpm        |  7.12.2
> 
> | Operating System | macOS 12.6 (Apple Silicon)
> 
> 
> 
> 
> 
> 

You should redo your package manifest to be like the following: 

~~~jsonc

//...
  "type": "module",
  "main": "dist/index.cjs",   // or .js if "type" is unspecified
  "exports": {
    "import": "./dist/index.js",   // no need for .mjs if "type" is "module" (recommended)
     "require": "./dist/index.cjs"   // or .js if "type" is unspecified
//...
~~~

You can see that by specifying type module you shouldnt use mjs.

Here are the collected notes I have on modules and packaging hopefully its useful 

https://github.com/sambacha/typescript-cjs-esm-tests

If you need any assistance happy to do so!
