### ISSUE TITLE
Panini for Parcel

### ISSUE THREAD

**Issue by ahiyalala** [parcel-bundler/parcel#8751]
# 🙋 feature request

As per Zurb's [Panini](https://get.foundation/sites/docs/panini.html) website:
> Panini is a flat file compiler that uses the concepts of templates, pages, and partials—powered by the [Handlebars](https://handlebarsjs.com/) templating language—to streamline the process of creating static prototypes

Panini is very great for prototyping front-end pages; unfortunately, it requires Gulp in order to be added to any front-end repository _(totally defeats Parcel's zero configuration principle, and also is that even possible to add Gulp simultaneously?)_. Is it possible to have this feature in Parcel or as a plugin? Or does Parcel already have any plugins that came close to Panini?

**Comment by devongovett** [comment]
Seems like a great opportunity for a third party plugin. I don't think we want to maintain too many languages in core. Check out the docs for details about the plugin system: https://parceljs.org/features/plugins/. Additionally, there are already some plugins available for templating languages like handlebars and ejs, so see the plugin search page for that: https://parceljs.org/plugin-browser/
