### ISSUE TITLE
Script from pages in project with multi entry point gets mixed

### ISSUE THREAD

**Issue by muhammadnasr** [parcel-bundler/parcel#8765]
# 🐛 bug report

I have a project with multi entry point (many .html files). When I try to run any html file I see that scripts from other pages are loaded.

I am using parcel v2.8.2

## 🤔 Expected Behavior
Each page should include only its related scripts
## 😯 Current Behavior

Pages includes scripts from other pages for now reason. For ex in this screen shot I am loading localhost:8080/processExplorer/unitOperations/viewEdit.html but I can see it also loaded pages with same name "viewEdit" but from other folders like processComponents. Which cause the page to no load properly.

![image](https://user-images.githubusercontent.com/165384/212170189-ca2b4dfa-1026-4c5d-a27e-2a08960fb60e.png)

## 💁 Possible Solution

Workarounds:

## 🔦 Context

Building my frontend for production (I am a big fan of parcel and using it to replace webpack )

## 💻 Code Sample

Private

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.8.2
| Node             | 14.17.6
| npm/Yarn         | rpm 8.13.2
| Operating System | Mac OS ventura

**Comment by mischnic** [comment]
Can you share a reproduction?

**Comment by niklas-e** [comment]
I'm having the same issue with TS+react. I tried to create a repro example, but got it to reproduce only partially. I'd guess it's not supposed to work like that.

Repo: https://github.com/niklas-e/parcel-multi-html-bug 
1. Run `npm i`
1. Run `npm run build`
1. Check contents of `dist/a.html` - it contains references to scripts from C in addition to the correct scripts.

-----

In my actual project I have three html entrypoints similarly, but the build results into all of them having "cross references" to each other.

**Comment by mischnic** [comment]
The cross-referencing itself it expected. It's just that there is some shared code between the pages and the shared bundle then get its name from an arbitrary page.

So unless you're seeing some error at runtime (as @muhammadnasr seems to have), then it's working as intended.
