### ISSUE TITLE
--public-url ./ does not work for building assets relative to index.html

### ISSUE THREAD

**Issue by abhinavgurung** [parcel-bundler/parcel#8769]
# 🐛 bug report

My site has a url such as https://site.ca/myApp
The index.html page is loading but the assets(js/css) is not found (404).

## 🎛 Configuration (.babelrc, package.json, cli command)

If describing a bug, tell us what your babel configuration looks like

```js
{
  "build-prod-release": "parcel build ./index.html  --dist-dir dist-prod-release --public-url ./ "
}
```

## 🤔 Expected Behavior

The assets(js/css) should be placed relative to index.html file. 

## 😯 Current Behavior

 I am getting `resource not found` 

## 🔦 Context

 I have seen multiple issues related to this topic but the solution does not work for me. Also I am using react-router. 
I am not sure if it has to do with that.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |   2.7.0
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
`--public-url ./` will emit relative urls, so `<script src="index.c75ff108.js"></script>`. But if your url is `site.ca/myApp`, then it will request `site.ca/index.c75ff108.js`. If you redirect (on the server-side) to `site.ca/myApp/` (with a trailing slash), then it will work correctly.

One alternative would be `--public-url myApp`

**Comment by abhinavgurung** [comment]
@mischnic  Hi, so my url is similar to `site.ca/myApp` and on my server I am redirecting to `site.ca/myApp/`
the browser is trying to get assets from `site.ca/myApp/index.js` but still getting 404.
I am using `--public-url ./` option.
I have different path on url based on english and french so giving one value like `--public-url myApp` is not possible for me.
since english url is `site.ca/myApp` and in French I have `site.ca/myAppFR`.

**Comment by mischnic** [comment]
So does `site.ca/myApp/index.html` contain something like `<script src="index.c75ff108.js"></script>`?

**Comment by abhinavgurung** [comment]
Yes It is similar to that. Here is the image.
![image](https://user-images.githubusercontent.com/12020147/214310396-f9c216cf-0348-471a-97a7-f8832267048a.png)

**Comment by mischnic** [comment]
Well, then it should work. This will request `site.ca/myApp/index.5994865e.js` which does exist. So I don't think this is Parcel's fault.

**Comment by abhinavgurung** [comment]
So I just checked again, it seems to work. Can this be made to work without the trailing slash ?

**Comment by mischnic** [comment]
No. (But this is not a limitation of Parcel. You'd have this problem even with handwritten HTML)
