### ISSUE TITLE
Can't install parcel

### ISSUE THREAD

**Issue by Suprefuner** [parcel-bundler/parcel#8772]
Hi there, 
I can't install parcel by  `npm i --save-dev parcel`
only `npm i --save-dev parcel@1` works for me
![parcel](https://user-images.githubusercontent.com/95112878/213071969-0d801ba3-515d-4095-a057-218ca5360c28.png)

**Comment by mischnic** [comment]
Try using file path without spaces (https://github.com/nodejs/node-gyp/issues/65)

**Comment by ast511** [comment]
> Hi there, I can't install parcel by `npm i --save-dev parcel` only `npm i --save-dev parcel@1` works for me ![parcel](https://user-images.githubusercontent.com/95112878/213071969-0d801ba3-515d-4095-a057-218ca5360c28.png)

Have you find any solutions? I get the same errors...

**Comment by mischnic** [comment]
node-gyp apparently has problems with spaces in file paths. There's not much Parcel can do about it.
