### ISSUE TITLE
@parcel/core: Failed to resolve 'got'

### ISSUE THREAD

**Issue by wassafr** [parcel-bundler/parcel#8773]
# 🐛 bug report

Parcel fails to resolve `got` module.
The exact same code works fine with Vite and Webpack so it's not an issue with the `got`. 

## 🤔 Expected Behavior

It should build 🤷‍♂️

## 😯 Current Behavior

It doesn't build, neither in dev nor in prod:

`@parcel/core: Failed to resolve 'got'` when running `yarn parcel` or `yarn parcel build`

## 💻 Code Sample

```
import got from "got"
got("https://google.com")
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.2
| Node             | 16.14.2
| Yarn         | 1.22.18
| Operating System | macOS 13.0.1 
| got | 12.5.3

**Comment by wassafr** [comment]
Forgot to mention that many other packages are successfully imported in this project so it's really on `got` that fails

**Comment by mischnic** [comment]
This is caused by https://github.com/parcel-bundler/parcel/issues/4155

You could use got 11 as a workaround for now.

**Comment by arty-name** [comment]
If this somehow helps in the future, this error started appearing in the latest parcel@2.8.3. Previous versions of parcel didn’t work with got@12 for other reasons.

**Comment by venkatj87** [comment]
my code builds fine when i built it on local. But production builds fails on the server.

```
@parcel/core: Failed to resolve './components/header/HeaderComponent' from
--
 | './src/App.js'
 | /vercel/path0/src/App.js:3:29
 | 2 \| import ReactDOM from 'react-dom/client';
 > 3 \| import HeaderComponent from './components/header/HeaderComponent';
```

The component path is correct though It fails
