### ISSUE TITLE
 ERR_REQUIRE_ESM with `parcel watch` and ESM-only dependencies 

### ISSUE THREAD

**Issue by arty-name** [parcel-bundler/parcel#8774]
# 🐛 bug report

The watch mode of parcel produces CJS code regardless of `"type": "module"` in `package.json`. As a result, purely ESM packages like `got` cannot be used: Node throws ERR_REQUIRE_ESM for the code.

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json`:
```json
{
  "main": "index.js",
  "dependencies": {
    "got": "^12.5.3",
    "parcel": "^2.8.2"
  }
}
```

`index.ts`: 
```ts
import { got } from 'got';

console.log(got);
```

## 🤔 Expected Behavior

It would be nice to be able to use even ESM-only packages with parcel’s watch mode. 

## 😯 Current Behavior

```sh
$ parcel watch index.ts
✨ Built in 277ms

$ node index.js
index.js:1
var $jPS5E$got = require("got");
                 ^

Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/got/dist/source/index.js from index.js not supported.
Instead change the require of node_modules/got/dist/source/index.js in index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (index.js:1:18) {
  code: 'ERR_REQUIRE_ESM'
}

```

## 💁 Possible Solution

Would it be viable to generate ESM code in watch mode?

## 🔦 Context

I am using the `got` package in my projects, and it was updated to ESM-only version 12 quite some time ago. I cannot upgrade to this version because it’s not usable with parcel for development.

## 💻 Code Sample

[The same minimal reproduction as gist](https://gist.github.com/arty-name/c30dfd807fcbfa4d51db26fe5dc5da50)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.2
| Node             | 18.13.0
| npm/Yarn         | yarn 1.22.19
| Operating System | Ubuntu 22.04

**Comment by mischnic** [comment]
Strange, we already have some logic that should make it ESM: https://github.com/parcel-bundler/parcel/blob/7023c08b7e99a9b8fd3c04995e4ef7ca92dee5c1/packages/core/core/src/requests/TargetRequest.js#L1146

**Comment by arty-name** [comment]
Uhm, looks like I messed up with my minimal reproduction case based on outdated knowledge. But please don’t close it yet, as I did have the problem in a bigger project just today. I’ll update the issue shortly!

**Comment by arty-name** [comment]
While I try to minimize the reproduction case, here’s the [branch of the project with ESM-only version of `got`](https://github.com/BTE-Trusted-Entity/socialkyc.io/tree/renovate/got-12.x). After running `yarn parcel watch` I get the code in `dist/backend/server.js` which cannot be run with type=module and without it. 

type=module:
```
var err = new Error("Cannot find module '" + name + "'");
                  ^

Error: Cannot find module '@hapi/inert'
    at newRequire …
```

type=commonjs:
```
return nodeRequire(name);
                 ^

Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/got/dist/source/index.js…
```

**Comment by arty-name** [comment]
I’ll just close this ticket after all. I believe it all comes down to https://github.com/parcel-bundler/parcel/issues/4155. 

For the record: with type=module parcel@2.8.2 and before in watch mode generated code that could not import other packages (like @hapi/hapi could not be imported). Somehow running this code in the CommonJS mode worked, by adding another package.json with type=commonjs. Adding pure ESM packages broke this at runtime, but the cause is the poor workaround.

The latest parcel@2.8.3 at least properly indicates during the build stage that it cannot load the pure ESM module. Looking forward to having support  for them!
