### ISSUE TITLE
Parcel CLI (ignored --dist-dir flag)

### ISSUE THREAD

**Issue by nuno-bento-biglight** [parcel-bundler/parcel#8775]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

cli command:

```js
parcel build "/Users/[MY-USERNAME]/Documents/parcel-test/test.js" --dist-dir "/Users/[MY-USERNAME]/Documents/parcel-test/output-test.js" --no-source-maps --no-optimize --no-cache
```

## 🤔 Expected Behavior

It should output the js file to `/Users/[MY-USERNAME]/Documents/parcel-test/output-test.js`

## 😯 Current Behavior

It is outputting the js file to `/Users/[MY-USERNAME]/index.js`
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/45204857/213477858-6b943c9e-181b-4ecc-9bdc-e11c945bb01f.png">

Beyond the fact that outputs in the wrong folder, it doesn't even output the right file name which should be `output-test.js`

## 💻 Code Sample

```js
parcel build "/Users/[MY-USERNAME]/Documents/parcel-test/test.js" --dist-dir "/Users/[MY-USERNAME]/Documents/parcel-test/output-test.js" --no-source-maps --no-optimize --no-cache
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |   2.8.3
| Node             |  14.16.0
| npm        |   6.14.11
| Operating System |   macOS Monterey 12.5.1

**Comment by mischnic** [comment]
It's called `dist-dir`, so you specify the output folder and not the output filename.

What does your package.json contain? Is there a `main` field?

**Comment by nuno-bento-biglight** [comment]
Thanks for your reply @mischnic 

even with 
```
parcel build "/Users/[MY-USERNAME]/Documents/parcel-test/test.js" --dist-dir "/Users/[MY-USERNAME]/Documents/parcel-test" --no-source-maps --no-optimize --no-cache
```

it still creates an `index.js` in `/Users/[MY-USERNAME]/index.js`

Not sure what you mean by package.json, I simply installed `npm i parcel -g` globally and then simply used the CLI command shared above.

**Comment by nuno-bento-biglight** [comment]
@mischnic I know you might be busy, but any idea what the problem is?

**Comment by mischnic** [comment]
So that command should work.
Unless you have this in your package.json (if yes, just remove that line):
```json
{
	"main": "index.js"
}
```
