### ISSUE TITLE
Running Parcel through Turborepo fails to build packages

### ISSUE THREAD

**Issue by sldavidson** [parcel-bundler/parcel#8777]
# 🐛 bug report

I have a Turborepo with some packages that use Parcel to build. If I use `turbo` at the monorepo root to build the packages, the package doesn't build and the script never finishes. The process will run until it is terminated. The package will build if I am in the package root and use npm to run the build script.

## 🎛 Configuration (.babelrc, package.json, cli command)

Repo root `package.json`
```json
{
  "name": "turbo-parcel",
  "version": "0.0.0",
  "private": true,
  "workspaces": [
    "apps/*",
    "packages/*"
  ],
  "scripts": {
    "build": "turbo run build",
    "dev": "turbo run dev --parallel",
    "lint": "turbo run lint",
    "format": "prettier --write \"**/*.{ts,tsx,md}\""
  },
  "devDependencies": {
    "@parcel/packager-ts": "^2.8.3",
    "@parcel/transformer-typescript-types": "^2.8.3",
    "eslint-config-custom": "*",
    "prettier": "latest",
    "process": "^0.11.10",
    "turbo": "latest",
    "typescript": "^4.9.4"
  },
  "engines": {
    "node": ">=14.0.0"
  },
  "packageManager": "npm@8.19.3"
}
```
Package's `package.json`
```json
{
  "name": "lib-2",
  "version": "0.0.0",
  "source": "./index.tsx",
  "main": "./dist/index.js",
  "module": "./dist/index.mjs",
  "types": "./dist/index.d.ts",
  "license": "MIT",
  "scripts": {
    "build": "parcel build",
    "lint": "TIMING=1 eslint \"**/*.ts*\""
  },
  "devDependencies": {
    "@types/react": "^17.0.37",
    "@types/react-dom": "^17.0.11",
    "eslint": "^7.32.0",
    "eslint-config-custom": "*",
    "parcel": "^2.8.3",
    "tsconfig": "*",
    "typescript": "^4.5.2"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
}

```

## 🤔 Expected Behavior

When building with turbo, expect the packages using Parcel to build.

## 😯 Current Behavior

The process hangs and never terminates. I don't get any error message.

## 💁 Possible Solution

I can't think of any, but from digging through the issues, it seems like in general there are issues with using Parcel with monorepo  tools such as pnpm and turborepo. 

## 🔦 Context

I like the simplicity of Parcel and wanted to migrate our packages in our monorepo to use it for the standard build tool, but the issues I have had with pnpm and turborepo migrating over became a no-go. 

## 💻 Code Sample

https://github.com/sldavidson/turbo-parcel-example

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3
| Node             |18.13.0
| npm/Yarn         | 8.19.3
| Operating System | Kubuntu 22.10

**Comment by devongovett** [comment]
What makes you think this is a Parcel issue rather than a Turborepo one? You said it works without turborepo (eg via npm).

**Comment by sldavidson** [comment]
Yeah it could be a Turborepo issue. My line of reasoning was Turborepo works fine with Vite, tsup, esbuild, Webpack, but not with Parcel. There is this issue #7579 with finding the project root, #7578 where  Turbo + Parcel  caused an error on a Windows machine, and #8304 where the autoinstall doesn't work with pnpm. My intuition is that maybe running Parcel through Turbo is obfuscating the process or package root from Parcel so that Parcel isn't able to resolve and proceed.  

I would be willing to dig into it a bit, and would appreciate any direction.

**Comment by Yhozen** [comment]
@sldavidson did you find a way to make it work?
