### ISSUE TITLE
Difference in CSS bundle results between watch and build

### ISSUE THREAD

**Issue by dsibinski** [parcel-bundler/parcel#8795]
# 🐛 bug report

I have a case in which parcel outputs different CSS bundles results in `watch` and `build` modes. It concerns importing external CSS files from node modules.

## 🎛 Configuration (.babelrc, package.json, cli command)
This is a `package.json`:
```json
{
  "name": "parcel-test-app",
  "version": "1.0.0",
  "description": "",
  "source": "index.html",
  "scripts": {
    "cleanup": "if exist dist rmdir /q /s dist",
    "build": "npm run cleanup && parcel build --no-optimize",
    "watch": "npm run cleanup && parcel watch",
    "start": "parcel"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@parcel/transformer-sass": "^2.8.3",
    "parcel": "^2.8.3",
    "process": "^0.11.10"
  },
  "dependencies": {
    "@syncfusion/ej2-base": "^20.4.44",
    "@syncfusion/ej2-icons": "^20.4.42",
    "@syncfusion/ej2-popups": "^20.4.44",
    "@syncfusion/ej2-react-buttons": "^20.4.44",
    "@syncfusion/ej2-react-diagrams": "^20.4.42",
    "@syncfusion/ej2-react-dropdowns": "^20.4.43",
    "@syncfusion/ej2-react-inputs": "^20.4.42",
    "@syncfusion/ej2-react-lists": "^20.4.42",
    "@syncfusion/ej2-react-navigations": "^20.4.44",
    "@syncfusion/ej2-react-popups": "^20.4.44",
    "@syncfusion/ej2-react-richtexteditor": "^20.4.44",
    "@syncfusion/ej2-react-splitbuttons": "^20.4.42",
    "@syncfusion/ej2-react-spreadsheet": "^20.4.44",
    "@syncfusion/ej2-richtexteditor": "^20.4.44",
    "@types/react": "^18.0.27",
    "@types/react-dom": "^18.0.10",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "typescript": "^4.9.4"
  }
}
```

As you can see, it's React & TypeScript app. I use latest parcel (2.8.3).

There's an `index.html` which only provides a placeholder for React component.

`App.tsx` file renders another component:

```tsx
import { SyncfusionSpreadsheet } from "./SyncfusionSpreadsheet";

export const App = () => {
  return <SyncfusionSpreadsheet />;
};

```

which looks as follows:
```tsx
// Syncfusion Spreadsheet
import "./node_modules/@syncfusion/ej2-inputs/styles/bootstrap5.css";
import "./node_modules/@syncfusion/ej2-buttons/styles/bootstrap5.css";
import "./node_modules/@syncfusion/ej2-lists/styles/bootstrap5.css";
import "./node_modules/@syncfusion/ej2-dropdowns/styles/bootstrap5.css";
import "./node_modules/@syncfusion/ej2-grids/styles/bootstrap5.css";
import "./node_modules/@syncfusion/ej2-react-spreadsheet/styles/bootstrap5.css";

export const SyncfusionSpreadsheet = () => {
  return <div>SyncfusionSpreadsheet</div>;
};
```

As you can see I only import `.css` files from Syncfusion npm packages. I import them directly in the React file, because when doing it in another .css or .scss files, I'm getting other errors (see [this issue](https://github.com/parcel-bundler/parcel/issues/8789)).

Here comes the weird part. Using `npm run watch` and `npm run build` gives different results. See below.

## 🤔 Expected Behavior

In case of building this app with both `parcel watch` and `parcel build --no-optimize`, the external CSS should be present in output bundles.

## 😯 Current Behavior
Using `npm run watch` which runs parcel in watching mode, it outputs a CSS bundle with `spreadsheet` classes (which come from Syncfusion's CSS files imported in the React component):

![image](https://user-images.githubusercontent.com/7132073/214788027-6f590027-1b83-40be-b45d-f7db70a9262d.png)

However, if I use `npm run build` which uses `parcel build` command (`--no-optimize` is added to disable minification [as per documentation](https://parceljs.org/features/production/#minification)), there's no CSS bundle built at all:

![image](https://user-images.githubusercontent.com/7132073/214788079-61240fae-be33-44d2-83c7-c2fe63c61144.png)

## 💁 Possible Solution

I don't really know, but I guess there's a bug somewhere. The `watch` and `build` commands should not produce totally different results. In that case, `build` seems to completely ignore the imported CSS in bundles.

## 🔦 Context
The issue was found when I started working with this particular Syncfusion Spreadsheet component. To be honest, importing CSSes from different npm packages in the same way doesn't give these differences in bundles... So there must be something specific for this case.

The sample app I provided (also attached below) is a simplified version to reproduce the issue. In the real world app I work on, we use multiple `source` entries in `package.json`. Parcel doesn't build any single entry points like `index.html` or `index.js`, but multiple "apps" which we serve in a custom way (from .NET web server). That's why when I import these external CSS files in `.css` or `.saas` files (instead of inside React components), parcel gives me a lot of compilation errors (duplicated bundles names, or "@parcel/bundler-default: Expected content key 46fff9ce3c3ba568 to exist" errors). It lead me to try importing CSS directly inside the React component.

Currently, we are unable to ship our app because of this `parcel build` issue.
## 💻 Code Sample
Please find the sample app described in this item below:

[parcel-syncfusion-app.zip](https://github.com/parcel-bundler/parcel/files/10507609/parcel-syncfusion-app.zip)

To reproduce:
1. `npm install`
2. `npm run watch` - see the CSS is in the bundles
3. `npm run build` - see there's no CSS in the bundles

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.8.3
| Node             | v18.12.1
| npm/Yarn         | npm 8.19.2
| Operating System | Windows 11

**Comment by tristan-f-r** [comment]
As I've mentioned in [a StackOverflow answer](https://stackoverflow.com/a/75285951/7589775), this is an issue with the CSS framework you're using. **However**, I don't think this is justification to leave this as completed and move on. This is a very good reason to provide a useful warning, for example:

> File `x` was imported but is marked as side effect free
