### ISSUE TITLE
CSS modules bundled with dependency with Parcel 2.8.x

### ISSUE THREAD

**Issue by YoruNoHikage** [parcel-bundler/parcel#8799]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

No babelrc, no parcel config.

package.json
```json
{
  "browserslist": "> 0.5%, last 2 versions, not ios_saf < 13, not dead",
  "dependencies": {
    "@blueprintjs/core": "~4.6.0",
    "classnames": "^2.3.2",
    "normalize.css": "^8.0.1",
    "process": "^0.11.10",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "cross-env": "^7.0.3"
  }
}
```

## 🤔 Expected Behavior

normalize.css gets applied, then blueprint.css and then styles.module.css.

## 😯 Current Behavior

normalize.css and styles.module.css seems to be bundled together and appearing first in the markup, which makes the blueprint.css classes be applied after the ones defined in styles.module.css.

It seems commenting out the normalize.css import fixes the bug temporarily, but removing .parcel-cache and dist makes it reappear.

## 💁 Possible Solution

Downgrade to 2.7.

## 🔦 Context

I want to tweak blueprint.css style by applying CSS module classes to an element.

## 💻 Code Sample

Here's a gist with the file to reproduce the bug: https://gist.github.com/YoruNoHikage/16b90678b4c9203a989a008bc815bd92

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3 |
| Node             | 18.2.0 |
| npm/Yarn         | 9.2.0 |
| Operating System | Pop OS |

**Comment by mischnic** [comment]
These lines here force Parcel to create 2 CSS bundles:
```css
    <link rel="stylesheet" href="npm:normalize.css/normalize.css" />
    <link rel="stylesheet" href="npm:@blueprintjs/core/lib/css/blueprint.css" />
```

And then the CSS module probably gets put into the first one.  The alternative here would be to create yet another CSS bundles, which doesn't really scale.

You should instead create a single `style.css` file for global styles and `<link>` that. Then put `@import "..."` in there for the two dependencies.

**Comment by YoruNoHikage** [comment]
So you're saying using multiple `<link>` is discouraged when using CSS Modules because Parcel puts everything at the end of the first CSS bundle it finds, right?

Since my CSS modules are imported from the `index.jsx` which is itself referenced at the end of the `index.html`, I assumed everything would have been put at the end in a bundle of its own. The result is unexpected.

(I updated my reproduction to add `styles.module.css` I previously forgot to add)
