### ISSUE TITLE
Environment variables and React.lazy()

### ISSUE THREAD

**Issue by soyjavi** [parcel-bundler/parcel#8803]
# 🐛 bug report

Seems if you use `React.lazy` and within the component you wanna use any environment variable (ex. process.env.EXAMPLE) it is always `undefined`. Meanwhile if that same component is loaded as usual (without React.lazy) it can get the value of that environment variable.

## 🤔 Expected Behavior

Both methods should get the environment variable.

## 😯 Current Behavior

React.lazy method doesnt get the environment variable.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3
| Node             | 16.15
| npm/Yarn         | 1.22.10
| Operating System | MacOs Ventura

**Comment by devongovett** [comment]
Seems to work in this [example](https://parcel2-repl-mischnic.vercel.app/#JTdCJTIyZmlsZXMlMjIlM0ElNUIlNUIlMjIlMkZzcmMlMkZpbmRleC5odG1sJTIyJTJDJTdCJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJ2YWx1ZSUyMiUzQSUyMiUzQyFET0NUWVBFJTIwaHRtbCUzRSU1Q24lM0NtYWluJTNFJTNDJTJGbWFpbiUzRSU1Q24lM0NzY3JpcHQlMjBzcmMlM0QlNUMlMjIuJTJGaW5kZXguanN4JTVDJTIyJTIwdHlwZSUzRCU1QyUyMm1vZHVsZSU1QyUyMiUzRSUzQyUyRnNjcmlwdCUzRSUyMiU3RCU1RCUyQyU1QiUyMiUyRnNyYyUyRmluZGV4LmpzeCUyMiUyQyU3QiUyMnZhbHVlJTIyJTNBJTIyaW1wb3J0JTIwKiUyMGFzJTIwUmVhY3QlMjBmcm9tJTIwJTVDJTIycmVhY3QlNUMlMjIlM0IlNUNuaW1wb3J0JTIwJTdCJTIwY3JlYXRlUm9vdCUyMCU3RCUyMGZyb20lMjAncmVhY3QtZG9tJTJGY2xpZW50JyUzQiU1Q25pbXBvcnQlMjAlN0JBcHAlN0QlMjBmcm9tJTIwJy4lMkZBcHAuanN4JyUzQiU1Q25sZXQlMjByb290JTIwJTNEJTIwY3JlYXRlUm9vdChkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCU1QyUyMm1haW4lNUMlMjIpKSUzQiU1Q25yb290LnJlbmRlciglM0NBcHAlMjAlMkYlM0UpJTNCJTIyJTdEJTVEJTJDJTVCJTIyJTJGc3JjJTJGQXBwLmpzeCUyMiUyQyU3QiUyMnZhbHVlJTIyJTNBJTIyaW1wb3J0JTIwKiUyMGFzJTIwUmVhY3QlMjBmcm9tJTIwJTVDJTIycmVhY3QlNUMlMjIlM0IlNUNuJTVDbmNvbnN0JTIwTGF6eSUyMCUzRCUyMFJlYWN0LmxhenkoKCklMjAlM0QlM0UlMjBpbXBvcnQoJy4lMkZMYXp5JykpJTNCJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMEFwcCgpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDUmVhY3QuU3VzcGVuc2UlMjBmYWxsYmFjayUzRCU3QiUzQ3NwYW4lM0VMb2FkaW5nJTNDJTJGc3BhbiUzRSU3RCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NMYXp5JTIwJTJGJTNFJTVDbiUyMCUyMCUyMCUyMCUzQyUyRlJlYWN0LlN1c3BlbnNlJTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEJTIyJTdEJTVEJTJDJTVCJTIyJTJGc3JjJTJGTGF6eS5qcyUyMiUyQyU3QiUyMnZhbHVlJTIyJTNBJTIyaW1wb3J0JTIwUmVhY3QlMjBmcm9tJTIwJ3JlYWN0JyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwTGF6eSgpJTIwJTdCJTVDbiUyMCUyMHJldHVybiUyMCUzQ2RpdiUzRUVYQU1QTEUlM0ElMjAlN0Jwcm9jZXNzLmVudi5FWEFNUExFJTdEJTNDJTJGZGl2JTNFJTNCJTVDbiU3RCUyMiU3RCU1RCUyQyU1QiUyMiUyRnBhY2thZ2UuanNvbiUyMiUyQyU3QiUyMnZhbHVlJTIyJTNBJTIyJTdCJTVDbiUyMCUyMCUyMCUyMCU1QyUyMm5hbWUlNUMlMjIlM0ElMjAlNUMlMjJyZXBsJTVDJTIyJTJDJTVDbiUyMCUyMCUyMCUyMCU1QyUyMnZlcnNpb24lNUMlMjIlM0ElMjAlNUMlMjIwLjAuMCU1QyUyMiUyQyU1Q24lMjAlMjAlMjAlMjAlNUMlMjJlbmdpbmVzJTVDJTIyJTNBJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU1QyUyMmJyb3dzZXJzJTVDJTIyJTNBJTIwJTVDJTIyc2luY2UlMjAyMDE5JTVDJTIyJTVDbiUyMCUyMCUyMCUyMCU3RCUyQyU1Q24lMjAlMjAlMjAlMjAlNUMlMjJ0YXJnZXRzJTVDJTIyJTNBJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU1QyUyMmFwcCU1QyUyMiUzQSUyMCU3QiU3RCU1Q24lMjAlMjAlMjAlMjAlN0QlMkMlNUNuJTIwJTIwJTIwJTIwJTVDJTIyZGVwZW5kZW5jaWVzJTVDJTIyJTNBJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU1QyUyMnJlYWN0JTVDJTIyJTNBJTIwJTVDJTIyKiU1QyUyMiUyQyU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlNUMlMjJyZWFjdC1kb20lNUMlMjIlM0ElMjAlNUMlMjIqJTVDJTIyJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCU1QyUyMnJlYWN0LXJlZnJlc2glNUMlMjIlM0ElMjAlNUMlMjIlNUUwLjkuMCU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlN0QlNUNuJTdEJTIyJTdEJTVEJTJDJTVCJTIyJTJGLmVudiUyMiUyQyU3QiUyMnZhbHVlJTIyJTNBJTIyRVhBTVBMRSUzRHRlc3QlMjIlN0QlNUQlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZW50cmllcyUyMiUzQSU1QiU1RCUyQyUyMm1pbmlmeSUyMiUzQWZhbHNlJTJDJTIyc2NvcGVIb2lzdCUyMiUzQWZhbHNlJTJDJTIyc291cmNlTWFwcyUyMiUzQXRydWUlMkMlMjJwdWJsaWNVcmwlMjIlM0ElMjIlMkZfX3JlcGxfZGlzdCUyMiUyQyUyMnRhcmdldFR5cGUlMjIlM0ElMjJicm93c2VycyUyMiUyQyUyMnRhcmdldEVudiUyMiUzQW51bGwlMkMlMjJvdXRwdXRGb3JtYXQlMjIlM0FudWxsJTJDJTIyaG1yJTIyJTNBdHJ1ZSUyQyUyMm1vZGUlMjIlM0ElMjJkZXZlbG9wbWVudCUyMiUyQyUyMnJlbmRlckdyYXBocyUyMiUzQWZhbHNlJTJDJTIydmlld1NvdXJjZW1hcHMlMjIlM0FmYWxzZSUyQyUyMmRlcGVuZGVuY2llcyUyMiUzQSU1QiU1RCUyQyUyMm51bVdvcmtlcnMlMjIlM0EwJTdEJTJDJTIydXNlVGFicyUyMiUzQWZhbHNlJTJDJTIyYnJvd3NlckNvbGxhcHNlZCUyMiUzQSU1QiU1RCUyQyUyMnZpZXdzJTIyJTNBJTVCJTIyJTJGc3JjJTJGaW5kZXguaHRtbCUyMiUyQyUyMiUyRnNyYyUyRmluZGV4LmpzeCUyMiUyQyUyMiUyRnNyYyUyRkFwcC5qc3glMjIlMkMlMjIlMkZwYWNrYWdlLmpzb24lMjIlMkMlMjIlMkZzcmMlMkZMYXp5LmpzJTIyJTJDJTIyJTJGLmVudiUyMiU1RCUyQyUyMmN1cnJlbnRWaWV3JTIyJTNBNSU3RA==) (press Build then open the Preview tab). Can you please provide a reproduction?
