### ISSUE TITLE
How to solve Reference error :self is not defined

### ISSUE THREAD

**Issue by nit08** [parcel-bundler/parcel#8804]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by devongovett** [comment]
Please provide a code sample that reproduces your problem.
