### ISSUE TITLE
Import JS polyfills and helper functions from a separate package

### ISSUE THREAD

**Issue by AlexVipond** [parcel-bundler/parcel#8809]
# 🙋 feature request

For libraries, it would be awesome if Parcel could be configured to import JS polyfills and helpers from a separate dependency, excluded from the library bundle.

Basically, take the same approach that Babel did with `@babel/runtime`: https://babeljs.io/docs/en/babel-runtime

## 🤔 Expected Behavior

When a project installs multiple JS libraries that were all bundled with Parcel, the final bundle should include only one of each polyfill or helper function that is needed, instead of a separate copy of each polyfill in each library bundle that needed it.

## 😯 Current Behavior

Polyfills and helpers get included in the final bundle of every Parcel-bundled library. A project that imports multiple libraries bundled by Parcel will have its bundle size increased unnecessarily.

## 💁 Possible Solution

Publish polyfills and helpers in a separate package that library authors can list as a dependency and exclude from their bundles. Downstream authors will be able to import multiple Parcel-bundled packages which in turn import Parcel polyfills and helpers, and the final bundle will only include one copy of each polyfill/helper.

## 🔦 Context

I'm a library author that uses Babel with `@babel/runtime` in several different packages (via Rollup's Babel plugin). I'd like to fully replace it with Parcel for speed and transpilation quality, without increase bundle size for anyone who uses my packages (including me).

## 💻 Examples

See Babel docs for more info https://babeljs.io/docs/en/babel-runtime

**Comment by mischnic** [comment]
Which functions are you talking about exactly?

**Comment by AlexVipond** [comment]
Things like this that get inserted into transpiled scripts—I assumed they came from `@parcel/transformer-js` but maybe I'm wrong?

```
function _arrayLikeToArray(e, s) {
    (null == s || s > e.length) && (s = e.length);
    for (var n = 0, i = new Array(s); n < s; n++)
        i[n] = e[n];
    return i
}
function _arrayWithHoles(e) {
    if (Array.isArray(e))
        return e
}
function _defineProperty(e, s, n) {
    return s in e ? Object.defineProperty(e, s, {
        value: n,
        enumerable: !0,
        configurable: !0,
        writable: !0
    }) : e[s] = n,
    e
}
function _iterableToArrayLimit(e, s) {
    var n = null == e ? null : "undefined" != typeof Symbol && e[Symbol.iterator] || e["@@iterator"];
    if (null != n) {
        var i, t, o = [], a = !0, r = !1;
        try {
            for (n = n.call(e); !(a = (i = n.next()).done) && (o.push(i.value),
            !s || o.length !== s); a = !0)
                ;
        } catch (e) {
            r = !0,
            t = e
        } finally {
            try {
                a || null == n.return || n.return()
            } finally {
                if (r)
                    throw t
            }
        }
        return o
    }
}
```

**Comment by mischnic** [comment]
These are the swc helpers actually: https://github.com/swc-project/swc/tree/main/packages/swc-helpers/src

If you build a library with Parcel, it should exclude the helpers. Can you provide an example where you'd have expected them to get excluded but Parcel didn't?

**Comment by AlexVipond** [comment]
Thanks for this info. I realized that all the Parcel work I've been doing lately is with classic scripts, not libraries, so that's probably why the helpers are getting included.

Feel free to close this feature request, thanks again!
