### ISSUE TITLE
@parcel/transformer-posthtml: 'mapurl' is not defined

### ISSUE THREAD

**Issue by fireball8931** [parcel-bundler/parcel#8811]
# 🐛 bug report

When upgrading parcel packages in my package.json, anything version of parcel higher than 2.7.0 throws the error:
🚨 Build failed.

`@parcel/transformer-posthtml: 'mapurl' is not defined`

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json:
```js
{
  "name": "aolccbc.com",
  "description": "This is the source code for aolccbc.com",
  "version": "1.0.0",
  "scripts": {
    "build": "parcel build",
    "dev": "parcel"
  },
  "source": "src/index.html",
  "targets": {
    "default": {
      "distDir": "./www"
    }
  },
  "engines": {
    "node": ">=18.7.0",
    "npm": ">=8.18.0",
    "posthtml": "^0.16.6",
    "@parcel/transformer-jsonld": "^2.7.0",
    "parcel": "^2.7.0"
},
  "repository": {
    "type": "git",
    "url": "git+https://github.com/fireball8931/aolccbc.com.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/fireball8931/aolccbc.com/issues"
  },
  "homepage": "https://github.com/fireball8931/aolccbc.com#readme",
  "devDependencies": {
    "parcel": "^2.7.0",
    "parcel-reporter-static-files-copy": "^1.4.0",
    "posthtml-img-autosize": "^0.1.6",
    "posthtml-modules": "^0.9.0"
  },
  "dependencies": {
    "@parcel/plugin": "^2.7.0",
    "posthtml": "^0.16.6",
    "posthtml-doctype": "^1.1.1",
    "posthtml-include": "^1.7.4"
  }
}
```

.parcelrc
```js
{
  "extends": ["@parcel/config-default"],
  "reporters":  ["...", "parcel-reporter-static-files-copy"]
}
```
### cli
```npm run dev```

## 🤔 Expected Behavior

Site should compile and serve on port 1234

## 😯 Current Behavior

```js
🚨 Build failed.

@parcel/transformer-posthtml: 'mapurl' is not defined

  ReferenceError: 'mapurl' is not defined
      at placeholders (/home/vagrant/aolccbc.com/node_modules/posthtml-expressions/lib/placeholders.js:73:19)
      at /home/vagrant/aolccbc.com/node_modules/posthtml-expressions/lib/index.js:212:29
      at Array.reduce (<anonymous>)
      at walk (/home/vagrant/aolccbc.com/node_modules/posthtml-expressions/lib/index.js:185:27)
      at /home/vagrant/aolccbc.com/node_modules/posthtml-expressions/lib/index.js:229:22
      at Array.reduce (<anonymous>)
      at walk (/home/vagrant/aolccbc.com/node_modules/posthtml-expressions/lib/index.js:185:27)
      at /home/vagrant/aolccbc.com/node_modules/posthtml-expressions/lib/index.js:166:9
      at /home/vagrant/aolccbc.com/node_modules/posthtml/lib/index.js:166:55
      at Array.forEach (<anonymous>)
```

## 🔦 Context

I am trying to keep my tools up to date to avoid security and performance issues.

## 💻 Code Sample

https://github.com/fireball8931/aolccbc.com/tree/update-all-packages

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | >=2.8.0
| Node             |  18.7.0
| npm         |  8.18.0
| Operating System | ubuntu, Windows 10, alpine

***ninja edit: spelling***

**Comment by mischnic** [comment]
I think in `src/locations.html`, you called the variable `mapsurl`. But in `src/components/location.htm` you reference `mapurl`. It builds successfully when naming them consistently.
This isn't really related to Parcel

**Comment by fireball8931** [comment]
Wow, I didn't catch that!
That means my locations page was broken this whole time!
I guess we can also classify this as a feature for checking my variables.

That actually led me to fix the values too, as Google changed their maps url for our second location.
