### ISSUE TITLE
Port used when running `parcel watch` against a library package

### ISSUE THREAD

**Issue by maxburs** [parcel-bundler/parcel#8812]
# 🐛 bug report

When running `parcel watch` in a package where `isLibrary` is set to `true` in the package.json, a port is used. 

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
    "source": "src/index.ts",
    "isLibrary": true,
    "main": "dist/index.js",
    "types": "dist/index.d.ts",
    "files": [
        "dist",
        "locale"
    ],
    "targets": {
        "types": false
    }
}

```

## 🤔 Expected Behavior

No port is used.

## 😯 Current Behavior

Port is used.

<img width="365" alt="image" src="https://user-images.githubusercontent.com/8890312/216736524-01ff8e6c-736b-4a39-9861-5c2b0010c2e9.png">

## 🔦 Context

This can be rather annoying when running `parcel watch` on multiple library packages. It's not a huge problem though, just annoying.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.8.1 |
| Node             | 16.14.1 |
| npm/Yarn         |  yarn 3.3.1 |
| Operating System | macOS 13.1 |

**Comment by mischnic** [comment]
You can do `--no-hmr` as a workaround. But yeah, this feature for webapps doesn't make sense when watching only libraries...

**Comment by maxburs** [comment]
> You can do `--no-hmr` as a workaround. But yeah, this feature for webapps doesn't make sense when watching only libraries...

This worked, thanks for the tip
