### ISSUE TITLE
crypto.randomUUID is not a function

### ISSUE THREAD

**Issue by 0x1af2aec8f957** [parcel-bundler/parcel#8820]
In my project, the use scenario of `crypto` is not directly introduced through the import syntax. In some places, I directly use the `window.crypto.randomUUID` method. This method can work as expected in the `Chrome console`. After the `parceljs build`, it cannot work as expected. I guess this may be related to `Node Emulation`. Can I configure it through `@parcel/transformer-js` in `package.json`? I can't find relevant documents.

Error screenshot: 

![Error screenshot](https://user-images.githubusercontent.com/25100196/217410464-c41049f3-1b81-46c9-9ec5-d33a70b4da7d.png)

**Comment by 0x1af2aec8f957** [comment]
Additional note: The same code will not have this problem if it is run through `parse serve`.

**Comment by awerlang** [comment]
Note that `window.crypto.randomUUID` is only available under HTTPS context: https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

`parcel serve` might be running under HTTPS while your app doesn't?

**Comment by 0x1af2aec8f957** [comment]
@awerlang It is indeed available in the context of `HTTPS`. However, `HTTPS` is not used in the `parcel run` mode, which is inconsistent with the expected effect.

Related screenshots:

![image](https://user-images.githubusercontent.com/25100196/217691158-747ce228-3e14-415e-af94-8cf7494a117b.png)

**Comment by awerlang** [comment]
No idea why it behaves that way.

I think you have three options:

1. Make sure your app only runs under HTTPS;
2. Use `import("crypto")` syntax to get "node emulation";
3. Bring your own polyfill for window.crypto.

**Comment by awerlang** [comment]
If `parcel run` adds a `window.crypto` polyfill that's not available in a production build, I'd mark this as a bug.

**Comment by mischnic** [comment]
`localhost` is treated a secure origin, even without HTTPS. 
For everything apart from localhost, you do need HTTPS.
