### ISSUE TITLE
Reloading before code has updated, insert a delay so the rest of code can finish updating before triggering reload

### ISSUE THREAD

**Issue by web3d0** [parcel-bundler/parcel#8827]
# 🐛 bug report

Parcel is picking up that a file has changed and immediately triggers a reload. However other files are still being updated as part of the compile, so the browser is not picking up all of the changes.

## 🎛 Configuration (.babelrc, package.json, cli command)

Mac, VSCode, Typescript, Tailwind.

## 🤔 Expected Behavior

The browser should pick up the changes when parcel issues the reload trigger.

## 😯 Current Behavior

The browser reloads, and then I have to reload again to get it to pick up the changes.

## 💁 Possible Solution

Pause until files stop changing before issuing the reload trigger to the browser. Half a second would work fine for me, so either a variable amount of time before reload, or wait for some amount of time before files stop changing before reload.

**Comment by mischnic** [comment]
In what situation does this happen (which two operations do you perform in these 500ms)?

**Comment by web3d0** [comment]
When I hit "Save" in VSCode, or change to the browser which triggers a save, then the browser will reload immediately as it detects the saved file, but before the Typescript / Tailwind pipeline has finished generating the other derived files. So I have to wait half a second, and then press reload in the browser, which will then load all the changed files properly.

Another possibility is that since I'm serving the files from expressjs, it has a 1 second cache rather than serving raw files. I will look into this aspect further. EDIT: Disabling cache control didn't help, can't find any caching in expressjs except querying for file changes. Perhaps that query is looking at time stamps, and only has a 1 second resolution?

**Comment by web3d0** [comment]
A temporary workaround is to enable network throttling in Chrome and set it to 10000kbit at 5ms latency, so it's still nearly as fast as local but slowed down to about half a second of transfer time. The network cache doesn't need to be disabled, strangely enough.

So this problem would only show up when the server and the browser are on the same computer (eg, my laptop), and wouldn't show up at all when connecting to a test server over the network.

**Comment by mischnic** [comment]
> Typescript / Tailwind pipeline has finished generating the other derived files

So you're not using tailwind via the postcss Parcel transformer? https://parceljs.org/recipes/react/#tailwind-css
And what is the Typescript part doing?

**Comment by web3d0** [comment]
Yes, Parcel is handling both the Typescript conversion to JS, and running the Tailwind transformer via PostCSS, so there is no external watch process running in parallel which could be causing a timing issue. VSCode is using Typescript separately (internally) for error messages only, and there isn't any build task running which would cause the JS files to output twice.

I have tested this by quitting VSCode and editing the source file using 'vi' while Parcel is running, and it still needs to be saved twice unless I have the Developer panel open in Chrome with a very slight slowdown in Networking. I am currently working with very small test files, so it may be just 5ms delay which is needed for the OS to flush to the filesystem.

In case it helps:

`parcel watch --no-autoinstall *.html hospital/*.html nurse/*.html account/*.html admin/*.html`

**Comment by mischnic** [comment]
> However other files are still being updated as part of the compile, so the browser is not picking up all of the changes.

Can you give an concrete example of this? Something like the JS being updated and reloading the CSS in the browser, before the CSS bundle was written by Parcel?

**Comment by web3d0** [comment]
Burst of busy right now, then will make a github repository to clone so you can see the issue. Who knows, maybe I'll find the problem but then I will describe what happened to close this issue off properly. Thank you for reading and your patience.

**Comment by web3d0** [comment]
Proposed for closing if fixed by other issues, seems to be updating properly for my use case.
