### ISSUE TITLE
Parcel build replaces HTML autocomplete attribute value with "on"

### ISSUE THREAD

**Issue by yefim** [parcel-bundler/parcel#8828]
# 🐛 bug report

When developing, I want to set an the `autocomplete` attribute of an `<input>` tag to "tel". However, upon deploying and building the site, the attribute is set in the HTML to "on" which is not correct. My form is relatively complicated with a `<form>` tag at the top of the page and many nested `<div>`s and `<section>`s so the `<input>` is not an immediate child of the `<form>`. This works in development mode but not when `parcel build` is called. See code below.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
}
```

Empty config. See https://github.com/yefim/valentine-roulette/blob/main/package.json

## 🤔 Expected Behavior

`<input type="tel" autocomplete="tel">` should build to the same thing.

## 😯 Current Behavior

`<input type="tel" autocomplete="tel">` builds to `<input type="tel" autocomplete="on">`

## 💻 Code Sample

Here's the input that gets incorrectly built.

https://github.com/yefim/valentine-roulette/blob/4132beb33e39e466e50ddf29edd162f7a703ea3f/send.html#L52

You can run `npm run build` to see the incorrect output.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3 |
| Node             | 18.12.1 |
| npm        | 8.19.2
| Operating System | macOS 13.2 |

**Comment by awerlang** [comment]
`htmlnano` doesn't know about extended values for `autocomplete`, ref. https://github.com/posthtml/htmlnano/blob/master/lib/modules/normalizeAttributeValues.es6#L75

This behavior can be disabled with a `.htmlnanorc` located at project root:

```json
{
    "normalizeAttributeValues": false
}
```

**Comment by yefim** [comment]
Ooh thank you - that worked!
