### ISSUE TITLE
Parcel resolver fails dependency check when using i18nextify in a project

### ISSUE THREAD

**Issue by Kilkenni** [parcel-bundler/parcel#8834]
# 🐛 bug report

Building a static site with [i18nextify](https://github.com/i18next/i18nextify/issues/91) fails if it is added via <script> tag into ```index.html```.

## 🎛 Configuration (package.json)

```
...
"scripts": {
    "dev": "rm -rf dist/* && parcel src/*.html src/locales/*/*",
    "build": "rm -rf dist/* && parcel build src/*.html src/locales/*/* --public-url /my-site/"
  },
  "devDependencies": {
    "@parcel/transformer-sass": "^2.8.3",
    "parcel": "^2.8.3",
    "posthtml-include": "^1.7.4",
    "sass": "^1.58.0"
  },
  "dependencies": {
    "@mischnic/parcel-namer-preserve-structure": "^0.2.0",
    "i18nextify": "^3.2.3",
    "modern-normalize": "^1.1.0"
  }
...
```

.parcelrc :

```
{
	"extends": "@parcel/config-default",
	"namers": ["@mischnic/parcel-namer-preserve-structure", "..."],
  "transformers": {
    "*.json": ["@parcel/transformer-raw"]
  }
}
```

## 🤔 Expected Behavior

Prod version (parcel build) works similarly to dev version.

## 😯 Current Behavior

```npm run dev``` works as expected, running the dev version. ```npm run build```, however, doesn't.

The build fails with an error:

![Flameshot_2023-02-15_21-42-11](https://user-images.githubusercontent.com/12563370/219208091-e9a6313b-ab45-4660-99aa-bd52adbd2bd7.png)

**adrai** pointed out that [dependency chain seems to be in order](https://github.com/i18next/i18nextify/issues/91#issuecomment-1432073402), so the problem is supposedly with Parcel's resolver.

## 💁 Workaround

I've tried importing i18nextify directly into JavaScript as suggested [here](https://github.com/i18next/i18nextify/issues/91#issuecomment-1432097817) instead of using ```<script>``` tag and the build apparently finished successfully.

Is it possible that resolver fails to find a dependency for script added via HTML tags, but works correctly when a script is added via ```import``` directly into index.js?

## 💻 Code Sample

```
<head>
...
<script src="/node_modules/i18nextify/i18nextify.min.js" type="module" id="i18nextify" fallbacklng="en"></script>
...
</head>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3
| Node             | 16.15.0
| npm         | 9.4.0
| Operating System |Ubuntu 22.04.1 LTS

**Comment by mischnic** [comment]
I don't get that error with your code snippet. Please provide a full reproduction.

**Comment by Kilkenni** [comment]
> I don't get that error with your code snippet. Please provide a full reproduction.

Kinda strange, because I tried reproducing it myself by reverting to import via <script>, but now it builds as usual in both cases.
I did many different things this weekend (including a minor Linux core upgrade), so I can't pinpoint what could have possibly fixed that. Sorry that I can't be of more help.
