### ISSUE TITLE
Import specifiers starting with a hash # resolve to the current asset

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#8839]
# 🐛 bug report

Import specifiers starting with a hash will resolve to the current asset.

## 🤔 Expected Behavior

Either error, or use the `imports` field.

## 😯 Current Behavior

The file reimports itself. 

## 🔦 Context

https://github.com/parcel-bundler/parcel/discussions/8836

## 💻 Code Sample

```
import { method } from "#/foo.js";
console.log(method());
```

with 
```
	"alias": {
		"#/*": "./$1"
	},
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3

**Comment by devongovett** [comment]
This will use the imports field in the new resolver.
