### ISSUE TITLE
Add Android Compatibility

### ISSUE THREAD

**Issue by RyanLarge13** [parcel-bundler/parcel#8840]
`Error: Cannot find module './artifacts/index.android-arm64.node'
`

After globally installing Parcel with the latest version of Node.js and npm installed through Termux, and installing required dependencies for a React application bundled by parcel this above error occurs in the terminal.

I wish to use Parcel through Termux on Android, as it is a great tool for bundling modular code!!

**Comment by spz2020** [comment]
....

**Comment by spz2020** [comment]
reopen it
