### ISSUE TITLE
Inlining environment variables not working in Web workers

### ISSUE THREAD

**Issue by tim-we** [parcel-bundler/parcel#8841]
# 🐛 bug report

Parcel supports inlining environment variables in JavaScript. However this feature does not seem to work in Web workers.

## 🎛 Configuration

- default `package.json` (generated by `npm init` and `npm i -D parcel`)

- `.env`
```
ENV_VALUE=42
```

CLI command: `npx parcel build src/index.html`

(Source files for min. example listed in the Code Sample section)

## 🤔 Expected Behavior

Parcel should replace ALL occurrences of `process.env.ENV_VALUE` with `"42"`.

## 😯 Current Behavior

`index.[hash].js` has `process.env.ENV_VALUE` replaced while `worker.[hash].js` still has the original expression.
In the worker context `process` is undefined and therefore this leads to a runtime error.

I'm not seeing any errors reported by parcel.

## 🔦 Context

I'm trying to switch a project from webpack to parcel. The webpack version uses the [define plugin](https://webpack.js.org/plugins/define-plugin/) to define some constants used in the code. AFAIK the only way to do something similar with parcel is to define environment variables, e.g. via a `.env` file.
I think this feature should also work with workers, for example to allow more detailed logs in dev mode.

## 💻 Code Sample

- src/index.html
```html
<!DOCTYPE html>
<html>
<head>
    <script type="module" src="main.js"></script>
</head>
</html>
```

- `src/main.js`
```js
console.log(process.env.ENV_VALUE);
new Worker(new URL("worker.js", import.meta.url));
```

- `src/worker.js`
```js
console.log(process.env.ENV_VALUE);
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3
| Node             | 18.12.0
| npm/Yarn         | npm 8.19.2
| Operating System | Linux Mint 20.3

**Comment by mischnic** [comment]
You need do to `new Worker(new URL("worker.js", import.meta.url), { type: "module" })`.

**Comment by tim-we** [comment]
Thanks, with `type: "module"` it actually works. Its a bit surprising to me that this feature (Node emulation but especially this inlining) is disabled in classic scripts though.
