### ISSUE TITLE
Uncaught ReferenceError: window is not defined

### ISSUE THREAD

**Issue by rschoenbichler** [parcel-bundler/parcel#8852]
# 🐛 bug report

When following the service worker example in the documentation, the service worker fails registering due to a reference error.

## 🎛 Configuration (.babelrc, package.json, cli command)

I'm using
```
"@parcel/service-worker": "^2.8.3",
"parcel": "^2.8.3",
"typescript": "^4.9.5"
```

## 🤔 Expected Behavior

the service worker should startup and register normally

## 😯 Current Behavior

```
serviceWorker.a76f4d16.js?1677147243266:634 Uncaught ReferenceError: window is not defined
    at 1dldy.26b841041df55918 (serviceWorker.a76f4d16.js?1677147243266:634:3)
    at newRequire (serviceWorker.a76f4d16.js?1677147243266:71:24)
    at localRequire (serviceWorker.a76f4d16.js?1677147243266:84:35)
    at 1xC6H.93eb803fa9d325fa (serviceWorker.a76f4d16.js?1677147243266:147:20)
    at newRequire (serviceWorker.a76f4d16.js?1677147243266:71:24)
    at serviceWorker.a76f4d16.js?1677147243266:122:5
    at serviceWorker.a76f4d16.js?1677147243266:145:3
 ```

## 💻 Code Sample

I register the service worker via
```
const url = new URL("../backend/serviceWorker", import.meta.url);
await navigator.serviceWorker.register(url, { type: "module", scope: "/api/" });
```
The service worker itself is empty.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3
| Node             | 16
| npm/Yarn         | 8
| Operating System | Linux - Fedora

**Comment by mischnic** [comment]
Try
```js
await navigator.serviceWorker.register(new URL("../backend/serviceWorker", import.meta.url), { type: "module", scope: "/api/" });
```
Parcel detects this specific pattern and then knows that `backend/serviceWorker` should be a service worker and not just a regular import (which would have access to window).

**Comment by rschoenbichler** [comment]
Yes, thank you, that was it.

I think this needs to be pointed out in the documentation however!
It seems to be quite a work around. Why instead not make the service worker script detect the presence of window?
