### ISSUE TITLE
zustand

### ISSUE THREAD

**Issue by drmax24** [parcel-bundler/parcel#8858]
it looks like pupular state manager zustand is not compatible with parcel optimizer.

I use parcel 2.8.3 and zustand 4.3.3.
react 18.2

Production build is made but the code does not work. yarn start works fine though

```
UserState.ts:17 Uncaught TypeError: (0 , $3c928a8b05ebf5cc$exports.create) is not a function
    at UserState.ts:17:30
```

Referencing another person having a problem too
https://github.com/pmndrs/zustand/issues/1563
It is mentioned that this is not a zustand problem but parcel's one

**Comment by mischnic** [comment]
Please provide a reproduction.

**Comment by kai-dorschner-twinsity** [comment]
in @drmax24 's original issue the problem is solved. It wasn't Parcel in particular. Just some false configuration on the user-end.

Cheers
