### ISSUE TITLE
[webextension] `options_ui.chrome_style` is not supported

### ISSUE THREAD

**Issue by fregante** [parcel-bundler/parcel#8866]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

The schema forces me to use `browser_style`, but Chrome does not support that.

```js
{
	"extends": "@parcel/config-webextension"
}
```

```json
{
	"options_ui": {
		"browser_style": true,
		"chrome_style": true,
		"page": "options.html"
	}
}
```

## 🤔 Expected Behavior

It should be accepted and preserved

## 😯 Current Behavior

```js
🚨 Build failed.

@parcel/transformer-webextension: Invalid 
Web Extension manifest

  manifest.json:30:3
    29 |     "browser_style": true,
  > 30 |     "chrome_style": true,
  >    |     ^^^^^^^^^^^^^^ Possible values: "open\_in\_tab"
    31 |     "page": "options.html"
    32 |   },
```

## 💁 Possible Solution

Change the schema to accept it

## 🔦 Context

Chrome doesn't care about `browser_style`:

<img width="416" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/222416729-0909e563-a732-46ed-9e26-02ea4c330f6e.png">

It only works with `chrome_style`:

<img width="416" alt="Screenshot 4" src="https://user-images.githubusercontent.com/1402241/222416762-16f62575-8e9e-43f5-a441-93e9f97921ba.png">

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3
| Node             | v18.13.0
| npm/Yarn         | 8.19.3
| Operating System | macOS 13.2

**Comment by mischnic** [comment]
Relevant file containing the schema definitions: https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/webextension/src/schema.js

`chrome_style` should be added similarly how `browser_style` is already supported.
