### ISSUE TITLE
🐛in watch mode several reload after changes

### ISSUE THREAD

**Issue by fabioricali** [parcel-bundler/parcel#887]
Hi,

I discovered this in my Chrome console:

![crazy-calling](https://user-images.githubusercontent.com/12598754/36588160-7e9b2fc8-1887-11e8-871c-aed98d1ab880.PNG)

### 🌍 My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| PHPstorm           | 2017.3.4
| Parcel           | 1.6.2
| Node             |  8.9.1
| npm/Yarn         |  npm 5.3.0
| Operating System | win 10

**Comment by DeMoorJasper** [comment]
Could you give us a code example?

**Comment by fabioricali** [comment]
My scenario:

index.php

```php
<?php
$src = isset($_REQUEST['DEVELOP']) ? 'dist' : 'build';
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black"/>
    <link rel="stylesheet" href="<?php echo $src ?>/bundle.css">
    <title>Radio Subasio Player</title>
</head>
<body>
<div id="root"></div>
<script type="text/javascript" src="<?php echo $src ?>/bundle.js"></script>
</body>
</html>
```
npm script
```
    "watch": "parcel watch src/index.js --out-file bundle.js",
    "build": "parcel build src/index.js --out-file bundle.js --out-dir build --public-url ./",
```

**Comment by megalithic** [comment]
For the record, I'm experiencing this with Ruby on Rails + parcel-rails (and by proxy, parcel). If you turn off HMR, it  at least won't infinite reload :)

**Comment by fabioricali** [comment]
But without HMR you must refresh manually :(... HMR is a great feature if work fine...

**Comment by fabioricali** [comment]
Hi there... I have still issues with HMR... The scenario: my script adds a node to the DOM.. when there are changes Parcel reload again the script that adds another node to the DOM... so I have double nodes.. How to resolve it?

**Comment by hmaurer** [comment]
I am experiencing the same issue when using Parcel with a React application.

**Comment by simonbuchan** [comment]
Use code like this to handle HMR for react, or just have a `<div id="root">` in your html:

```js
const root = document.getElementById("root") ||
  document.body.appendChild(
    Object.assign(document.createElement('div'), { id: 'root' })
  );

render(
  <App />,
  root,
);
```

**Comment by mischnic** [comment]
Some time ago, we switch the HMR strategy to reload the whole page by default, instead of only rerunning the JS.
