### ISSUE TITLE
SVG style broken by conversion of lines to path

### ISSUE THREAD

**Issue by Absotively** [parcel-bundler/parcel#8886]
# 🐛 bug report

I ran parcel on this SVG:
```svg
<svg version="1.1"
     viewBox="0 0 10 10"
     xmlns="http://www.w3.org/2000/svg">
<style> line { stroke-width: 10%; stroke: darkgrey; } </style>
<line x1="0" y1="10" x2="10" y2="0"/>
<line x1="-1" y1="1" x2="1" y2="-1"/>
<line x1="9" y1="11" x2="11" y2="9"/>
</svg>
```

It output this SVG:
```svg
<svg viewBox="0 0 10 10" xmlns="http://www.w3.org/2000/svg"><style>line{stroke-width:10%;stroke:#a9a9a9}</style><path d="M0 10 10 0M-1 1l2-2M9 11l2-2"/></svg>
```

The lines in the output SVG do not have the right stroke-width and stroke colour.

## 🎛 Configuration (.babelrc, package.json, cli command)

CLI command:
```npx parcel build hatching.svg```

## 🤔 Expected Behavior

The defined style should be used for the lines in the image, so that they have the specified stroke-width and stroke colour.

## 😯 Current Behavior

The defined style is not applied to the converted lines/path, because the style is still only applied to line elements, but the line elements have been converted to a path element.

## 💁 Possible Solution

Any of the following would be fine: the lines are not converted to a path because the style exists; the lines are converted and the style is updated to apply to paths instead of lines; the lines are converted and the resulting path element has a style attribute with the appropriate properties.

## 🔦 Context

The image is used as a repeating background image in HTML, to provide a hatched background/fill effect.

I am able to work around this bug by changing the original file to use a path.

## 💻 Code Sample

```svg
<svg version="1.1"
     viewBox="0 0 10 10"
     xmlns="http://www.w3.org/2000/svg">
<style> line { stroke-width: 10%; stroke: darkgrey; } </style>
<line x1="0" y1="10" x2="10" y2="0"/>
<line x1="-1" y1="1" x2="1" y2="-1"/>
<line x1="9" y1="11" x2="11" y2="9"/>
</svg>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3
| Node             | v18.14.0
| npm/Yarn         | 9.4.2
| Operating System | Windows 10 Home 21H2

**Comment by mischnic** [comment]
I think this is https://github.com/svg/svgo/issues/1466

A workaround is adding this svgo.config.json file:
```json
{
	"plugins": [
		{
			"name": "preset-default",
			"params": {
				"overrides": {
					"convertShapeToPath": false
				}
			}
		}
	]
}
```
