### ISSUE TITLE
Question: How I can add resolver alias / prefix / postfix ?

### ISSUE THREAD

**Issue by lifeart** [parcel-bundler/parcel#89]
if I do `import AngularController from 'modules/common/controllers/defaultController';`,
how I can specify `./src` prefix for this resolution?

if I need alias for import `jquery-ui/datepicker`  like `jquery-ui/lib/dist/datepicker`, how I can do it?

**Comment by philipodev** [comment]
would'nt [babel-plugin-module-alias](https://www.npmjs.com/package/babel-plugin-module-alias) do the trick since `parcel` is using your `.babelrc`?

**Comment by thejameskyle** [comment]
Let's merge this into #25
