### ISSUE TITLE
Loading fonts asynchronously?

### ISSUE THREAD

**Issue by thinkloop** [parcel-bundler/parcel#890]
I normally load fonts asynchronously so that they do not block rendering, using something like:

```
<head>
<script>
// load fonts asynchronously
function loadStyles(url) {
	return new Promise(function(resolve, reject) {
		var xhr = new XMLHttpRequest();
		xhr.returnType = 'text';
		xhr.onload = function() {
			var link = document.createElement('link');
			link.rel = 'stylesheet';
			link.href = url;
			document.head.appendChild(link);
			resolve();
		};
		xhr.onerror = reject;
		xhr.open('get', url);
		xhr.send();
	});
}

loadStyles('/assets/fonts/sans-book/sans-book.css');
loadStyles('/assets/fonts/sans-medium/sans-medium.css');
</script>
</head>
```

This does not work in parcel because the paths are simple strings that won't get converted into a hash, nor will the underlying files be processed. What is the best way around this?

**Comment by DeMoorJasper** [comment]
Copy them over to the output folder?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thinkloop** [comment]
That's embarrassingly helpful, thanks.

**Comment by JacobMGEvans** [comment]
@DeMoorJasper @thinkloop  Lifesaver, thanks.
