### ISSUE TITLE
While running build script , It showing like this , I am unable to understand

### ISSUE THREAD

**Issue by deepoa** [parcel-bundler/parcel#8907]
# 🐛 bug report

 While running build script , It showing like this , I am unable to understand

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🤔 Expected Behavior

 It should build the file .

## 😯 Current Behavior

It is showing error ,
```
@parcel/namer-default: Target "main" declares an output file path of "app.js" which does not match the compiled bundle type "html".

  /home/deepesh/Desktop/namaste1.0/ReactDev/package.json:5:11
    4 |   "description": "Namaste React Bootcamp",
  > 5 |   "main": "app.js",
  >   |           ^^^^^^^^ Did you mean "app.html"?
    6 |   "scripts": {
    7 |     "start": "parcel index.html",

  💡 Try changing the file extension of "main" in package.json.
```

## 💻 Code Sample
```
import React from "react";
import ReactDOM from "react-dom/client";

console.log("deepesh");
const heading = React.createElement(
  "h1",
  {
    id: "heading",
  },
  "hello world"
);
const root = ReactDOM.createRoot(document.getElementById("root"));

root.render(heading);

```

// Imp notes Regarding package lock.json

/*
Package lock.json  is a very imp file it locks the version , you never have to keep in gitignore,

It maintains the hash on the app ensures what version running in the local server and local production server

We should parcel.cache in gitignore

Transitive Dependencies =>  dependencies have their own dependencies

*/

/*
What Parcel do

*/

## 🌍 Your Environment 

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.8.3
| Node             |v16.13.2
| npm/Yarn         |9.4.1
      
| Operating System | Kali linux

![image](https://user-images.githubusercontent.com/102285786/227142939-ee9c5aba-2005-4338-b313-11d2ca5656c9.png)

**Comment by mischnic** [comment]
Just remove the line `"main": "app.js",`.

**Comment by deepoa** [comment]
Thnks @mischnic
