### ISSUE TITLE
🐛 --target=electron does not import "fs" module

### ISSUE THREAD

**Issue by scriptPilot** [parcel-bundler/parcel#893]
### 🤔 Expected Behavior

When build with --target=electron

```js
const fs = require('fs');
const files = fs.readdirSync('/');
```
... files contains array with files ...
### 😯 Current Behavior
fs.readdirSync() is no function

### 💁 Possible Solution
Load basic node modules when target is electron.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by lbguilherme** [comment]
I created a file called `index.js` with:

```js
const fs = require('fs');
const files = fs.readdirSync('/');
console.log(files);
```

Then compiled with `parcel build index.js --target=electron`. Then I ran `electron dist/index.js`. It worked as expected.

Is there anything unusual with your setup? Can you give me a way to reproduce the problem, starting from an empty directory?

**Comment by davidnagli** [comment]
@scriptPilot Can you please fill out the bottom part of the issue template with your info, so we can try to reproduce your issue

**Comment by starkwang** [comment]
Cannot reproduce this issue. Could you show the bundled file?

**Comment by scriptPilot** [comment]
I will review the issue shortly. Thanks so far.
