### ISSUE TITLE
Parcel fails to handle async import from 'mermaid' libary

### ISSUE THREAD

**Issue by dwmkerr** [parcel-bundler/parcel#8935]
# 🐛 bug report

When loading the [mermaid.js](https://github.com/mermaid-js/mermaid) diagramming library, via `import`, the library loads correctly. However, when a command is called that leads to an `async import` call in the library itself, the command fails. I _think_ this is either because:

- Tree shaking is removing the required code from the dist, as the import is dynamic
- Somehow module names are being changed in a way that is not properly handled by the library, such as the required module having a hash added but the source code not using the hash.

I have created a very minimal reproduction of the issue in a repository. In the same reproduction repository I have also verified that the issue does _not_ occur if using the [rollup.js](https://rollupjs.org/) bundler:

https://github.com/dwmkerr/parcel-mermaid-import-issue

## 🎛 Configuration (.babelrc, package.json, cli command)

- [`package.json`](https://github.com/dwmkerr/parcel-mermaid-import-issue/blob/main/package.json)
- No babelrc

## 🤔 Expected Behavior

When the "Render" button in the screenshot below is pressed, parcel would allow me to call the 'render' API from the mermaid.js library:

<img width="453" alt="image" src="https://user-images.githubusercontent.com/1926984/229590958-fa21b380-307b-49be-8377-c5d500106bce.png">

## 😯 Current Behavior

The call fails. Initially, it would seem like a mermaid error:

<img width="1574" alt="image" src="https://user-images.githubusercontent.com/1926984/229591155-a1681929-96db-4837-935c-b7b424410747.png">

However, debugging the code shows that the root cause, at least from mermaid's perspective is here:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/1926984/229593589-e688c3a6-b4ce-46b1-8195-7cd395afebe4.png">

This code can be seen here: https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/diagrams/flowchart/flowDetector-v2.ts#L22

I believe the issue is the line:

```js
const { diagram } = await import('./flowDiagram-v2');
```

It seems the required file, `flowDiagram-v2`, is not present in the loaded code:

<img width="661" alt="image" src="https://user-images.githubusercontent.com/1926984/229594256-56c830e9-2d09-420c-aafc-1e653ea2b807.png">

This file should be present - it is adjacent in the source tree:

<img width="678" alt="image" src="https://user-images.githubusercontent.com/1926984/229594443-51890bd3-8a81-4030-80d6-9fc47590a450.png">

## 💁 Possible Solution

I have tried the following:

1. Loading the mermaid.js code via the CDN (`import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10.0.2/+esm'`) - however contrary to the documentation (see this issue https://github.com/parcel-bundler/parcel/issues/7823)
2. Using `--no-optimize` this doesn't seem to work
3. Bundling the code without using `@parcel/config-webextension` seems to eliminate the issue

## 🔦 Context

I am trying to import mermaid.js into a chrome web extension - parcel is working amazingly web for the bundling, way easier than webpack, but the import of this third party module seems to be failing.

## 💻 Code Sample

- Clone the https://github.com/dwmkerr/parcel-mermaid-import-issue repo
- Follow the steps in the README - this is the most minimal reproduction I could create

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3 |
| Node             | 16.16.0 |
| npm/Yarn         | NPM 8.11.0 |
| Operating System | MacOS Venture 13.2.1 |
| Mermaid.JS | 10.0.2 |

**Comment by mischnic** [comment]
So you can't reproduce this outside of web extensions?

**Comment by dwmkerr** [comment]
I cannot reproduce the issue if I remove the use of `@parcel/config-webextension`
