### ISSUE TITLE
Word of warning for anyone trying parcel for the first time.

### ISSUE THREAD

**Issue by Ivanca** [parcel-bundler/parcel#8936]
This tool it's supposed to make frontend development less messy, among other reasones because it lets you start with no configuration... that wasn't my experience, parcel does a lot of weird unexpected things with your code and files:

- it changes the names of static files (e.g the `src` of videos)

- if you put "type=module" on a script tag it deletes it (after investigating its due some incompatibility with how parcel works and top level awaits)

- if you try to use any library that works on both the browser and node like fabricjs it fails at compile time (some parsing goes wrong), if you try to find some way to ignore such files you discover the only way is to host that script online because parcel doesn't touch these

- if you use shadow Dom in your app it appends everything inside those twice when hot-reloading modules (tbf that has an easy solution that listens, to listen a parcel event to force a reload, about 3 lines of JS)

And some other smaller issues, in conclusion it was a mistake to try it out, I converted it to webpack an it works all better now, I should have gone with webpack from the beginning and avoid things I haven't used before just from fake promises of simplicity.

**Comment by mischnic** [comment]
> it changes the names of static files (e.g the src of videos)

That is to make it easy to serve these files with a long HTTP cache duration or `Cache-Control: Immutable`.

> if you put "type=module" on a script tag it deletes it (after investigating its due some incompatibility with how parcel works and top level awaits)

Parcel creates legacy and modern bundles for the input files. The modern bundles get `<script type="module">`, the legacy ones get `<script>` which is the usual [module/nomodule pattern](https://web.dev/serve-modern-code-to-modern-browsers/). Top level await is [not supported at the moment](https://github.com/parcel-bundler/parcel/issues/4028), even if it might appear to work in simple cases

> if you try to use any library that works on both the browser and node like fabricjs it fails at compile time (some parsing goes wrong), if you try to find some way to ignore such files you discover the only way is to host that script online because parcel doesn't touch these

I just tried it and it works fine for me. Can you share an example and the error message?

> if you use shadow Dom in your app it appends everything inside those twice when hot-reloading modules (tbf that has an easy solution that listens, to listen a parcel event to force a reload, about 3 lines of JS)

That should also work correctly out of the box by doing a full page reload instead unless you opt into HMR with `module.hot.accept()`. Can you share an example?
