### ISSUE TITLE
Scope hoisting results in `ReferenceError` when overriding config containing `@parcel/transformer-js` transformer

### ISSUE THREAD

**Issue by Eric-Arellano** [parcel-bundler/parcel#8938]
# 🐛 bug report

I'm getting this error when loading using `@fortawesome/fontawesome-svg-core` unless I use `parcel build --no-scope-hoist`.

```
[Error] ReferenceError: Can't find variable: $a43d996a7aa8a839$export$b839f963c7dc0e34

	Código de módulo (index.html:1:62115)
```

## 🎛 Configuration (.babelrc, package.json, cli command)

I created a minimum reproduction.

package.json:

```js
{
  "name": "parcel-fontawesome-bug",
  "version": "1.0.0",
  "type": "module",
  "source": "index.html",
  "scripts": {
    "build": "parcel build"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "==6.4.0"
  },
  "devDependencies": {
    "parcel": "==2.8.3"
  }
}
```

## 😯 Current Behavior

If I set `--no-scope-hoist`, the site works without a `ReferenceError`.

If I remove this Parcel config, it also works:

```
  "transformers": {
    "*.js": ["@parcel/transformer-js"]
  }
```

(I set that Parcel config so I can use Babel to run Jest tests, per https://parceljs.org/languages/javascript/#usage-with-other-tools.)

So that suggest to me that this is specifically an issue with `@parcel/transformer-js`, compared to whatever the default is.

## 🔦 Context

I'm happy to help fix this, particularly if you can give me some pointers.

(Parcel is awesome; thank you for your work on it! You've made my life much more enjoyable working on https://github.com/ParkingReformNetwork/parking-lot-map and helped decrease bundle size by 45%)

## 💻 Code Sample

`index.html`:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Parcel Bug Report</title>
</head>
<body>
  <script type="module">
    import setUpIcons from "./setup.js";
    setUpIcons();
  </script>
</body>
</html>
```

`setup.js`:

```
import { dom } from "@fortawesome/fontawesome-svg-core";

const setUpIcons = () => {
  dom.watch();
};

export default setUpIcons;
```

`.parcelrc`:

```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.js": ["@parcel/transformer-js"]
  }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3
| Node             | 19.3.0
| npm/Yarn         | node 9.2.0
| Operating System | macOS, Safari

**Comment by mischnic** [comment]
You want `"*.{js,mjs,jsm,jsx,es6,cjs,ts,tsx}": ["@parcel/transformer-js"]` instead.

@lettertwo  noticed this some time ago as well: https://github.com/parcel-bundler/parcel/pull/8468. We really should add some kind of error here
