### ISSUE TITLE
Import statements trigger an error in virtual modules

### ISSUE THREAD

**Issue by samvv** [parcel-bundler/parcel#8939]
# 🐛 bug report

While working on a special resolver using virtual modules, I've discovered that `import` statements are not working properly on the latest version of Parcel.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "extends": "@parcel/config-default",
  "resolvers": ["parcel-resolver-test", "..."]
}
```

## 🤔 Expected Behavior

Imports should just be accepted, just like any other JavaScript construct.
 
## 😯 Current Behavior

Imports trigger a 'file not found' error, as desribed in #6874.
What #6874 did not describe is that valid code is also rejected, on top of invalid code.

```
🚨 Build failed.

Error: ENOENT: no such file or directory, open '/home/username/often/path/to/generated/file.js'
```

## 💁 Possible Solution

I am not familiar with the code base, so I can't tell.

## 🔦 Context

I am squeezing the most out of Parcel by creating a web framework kind of like [Gatsby](https://www.gatsbyjs.com/). Parcel is heavily used for building the app.

## 💻 Code Sample

I've created [a repository](https://github.com/samvv/parcel-resolver-test) showcasing what goes wrong.

```js
import { Resolver } from '@parcel/plugin';
import path from 'path';

export default new Resolver({
  async resolve({specifier}) {
    if (specifier === 'special-module') {
      return {
        // This may look arbitrary but I've checked best as Parcel's console allows me to do that this is correct.
        filePath: path.join(__dirname, '..', '..', 'example', 'special-modulus.js'),
        // This really should be correct. I've even pasted it in TypeScript to be extra sure.
        code: 'import { foo } from "./foo";\nexport default foo;'
      };
    }
    return null;
  }
});
```

Here's how I used it:

```ts
import foo from "special-module"

console.log(`The correct answer is: ${foo}`);
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3
| Node             |v18.10.0
| npm/Yarn         | npm 8.19.2
| Operating System | Ubuntu 22.04

**Comment by mischnic** [comment]
What you need is `path.join(__dirname, '..', 'example', 'special-modulus.js')` (one less `..`), currently there's a build error because of that

```
@parcel/core: Failed to resolve './foo' from 'parent-folder-of-project/example/special-modulus.js'
  parent-folder-of-project/example/special-modulus.js:1:21
  > 1 | import { foo } from "./foo";
  >   |                     ^^^^^^^
    2 | export default foo;
```

This line tries to read the non-existing file from disk while printing the error: https://github.com/parcel-bundler/parcel/blob/5b901a317c3b0788feca1ab14aff6fba949b8d7e/packages/core/core/src/requests/PathRequest.js#L188

**Comment by samvv** [comment]
> What you need is `path.join(__dirname, '..', 'example', 'special-modulus.js')` (one less `..`), currently there's a build error because of that
> 
> ```
> @parcel/core: Failed to resolve './foo' from 'parent-folder-of-project/example/special-modulus.js'
>   parent-folder-of-project/example/special-modulus.js:1:21
>   > 1 | import { foo } from "./foo";
>   >   |                     ^^^^^^^
>     2 | export default foo;
> ```
> 
> This line tries to read the non-existing file from disk while printing the error:
> 
> https://github.com/parcel-bundler/parcel/blob/5b901a317c3b0788feca1ab14aff6fba949b8d7e/packages/core/core/src/requests/PathRequest.js#L188

Really? I thought I managed to ensure a valid path. I've just tested it, and you're right: the bug is solved.

There's still another problem I have with watching virtual imports but if I can replicate it I'll open a separate issue.

Thanks!

**Comment by mischnic** [comment]
Let's keep this open to fix the error message
