### ISSUE TITLE
Request 404 error on hot module reload: https://fonts.googleapis.com/css?1681671981056 

### ISSUE THREAD

**Issue by amarmanhala** [parcel-bundler/parcel#8944]
![image](https://user-images.githubusercontent.com/46095869/232336349-2ac58d68-ab14-48ed-8043-30ae92684eb7.png)

**Comment by mischnic** [comment]
Which Parcel version are you using? How exactly are you triggering this?

Modifying the CSS file in this example works fine for me.
```html
<html>
  <head>
    <meta charset="utf-8" />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Tangerine"
    />
    <link rel="stylesheet" type="text/css" href="style.css">
  </head>
  <body>
    <div>Making the Web Beautiful!</div>
  </body>
</html>
```
with style.css
```css
body {
    font-family: "Tangerine", serif;
    font-size: 12em;
}
```

**Comment by amarmanhala** [comment]
I am using  "parcel": "^2.8.3". When I make any changes to index.css or even add any tailwinds class to tag then this error triggers. I have also imported index.css in the app.js file.

"devDependencies": {
    "@babel/core": "^7.21.3",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "parcel": "^2.8.3",
    "process": "^0.11.10"
  },
  "dependencies": {
    "@reduxjs/toolkit": "^1.9.5",
    "baseui": "^12.2.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-redux": "^8.0.5",
    "react-router-dom": "^6.10.0",
    "styletron-engine-atomic": "^1.5.0",
    "styletron-react": "^6.1.0"
  },
