### ISSUE TITLE
Support const type parameters (TypeScript 5)

### ISSUE THREAD

**Issue by nartallax** [parcel-bundler/parcel#8945]
# 🙋 feature request

In TypeScript 5 [there is a new feature that allows to control type inferrence of type parameters](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#const-type-parameters).  
Can we support it please?

## 🤔 Expected Behavior

It should not cause build error

## 😯 Current Behavior

It causes build errors:
```bash
🚨 Build failed.

@parcel/transformer-js: Expected ',', got 'T'

  /Users/username/filepath.ts:19:26
    18 |
  > 19 | function exampleFn<const T>(value: T): T {
  >    |                          ^
    20 |   return value
    21 | }
```

## 💁 Possible Solution

Add TypeScript 5 syntax features support in `parcel/transformer-js`?

## 💻 Examples

Parcel won't build project if this function is present in code:
```typescript
function exampleFn<const T>(value: T): T {
	return value
}
```

**Comment by devongovett** [comment]
This would need to be implemented in SWC first.

**Comment by mischnic** [comment]
One of the swc version upgrades we merged since the last release has resolved this already. You can try to use the nightly version until the next release: `yarn add parcel@nightly`
