### ISSUE TITLE
Parcel doesn't work correctly with the "notistack" library

### ISSUE THREAD

**Issue by evitalv** [parcel-bundler/parcel#8950]
# 🐛 bug report

The "notistack" library provides small notifications/snackbars. When you run the application using the "parcel" command, everything works fine. But when you use "parcel build", all the CSS styles are stripped from the notification. If you run "parcel build --no-optimize", everything looks fine, which means that **this bug is probably caused by production build optimization**.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "scripts": {
    "start": "parcel --open",
    "build": "parcel build  --dist-dir prod",
  },
  "babel": {
    "presets": [
      "@babel/preset-env",
      "@babel/preset-react",
      "@babel/preset-typescript"
    ]
  },
}
```

## 🤔 Expected Behavior

![notif_correct](https://user-images.githubusercontent.com/50102168/233055864-7f6930c2-4877-41fc-ab85-7c24f6a68cdb.png)

## 😯 Current Behavior

![notif_incorrect](https://user-images.githubusercontent.com/50102168/233055951-3ca6f4d0-38c5-4da2-99f0-f1a038cdee77.png)

## 💁 Possible Solution

Improve the build optimization process.

## 💻 Code Sample

In the main app file:
`        <SnackbarProvider
          maxSnack={3}
          autoHideDuration={3000}
          anchorOrigin={{
            vertical: 'bottom',
            horizontal: 'center',
          }}
          action={(snackbarId) => (
            <Button onClick={() => closeSnackbar(snackbarId)}>Dismiss</Button>
          )}>
          <Layout />
        </SnackbarProvider>
`

Anywhere else where you need a snackbar:
`enqueueSnackbar('Error', { variant: 'error', persist: true })`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.2 |
| Node             | 16.14.0 |
| npm/Yarn         | npm 8.3.1
| Operating System | built on Windows 11, used on Linux

**Comment by mischnic** [comment]
Please provide a complete code sample.

with 
```js
import { SnackbarProvider, enqueueSnackbar } from "notistack";

export const App = () => {
	return (
		<div>
			<SnackbarProvider />
			<button onClick={() => enqueueSnackbar("That was easy!")}>
				Show snackbar
			</button>
		</div>
	);
};
```
I get this with `parcel build index.html`:

<img width="333" alt="Bildschirm­foto 2023-04-21 um 21 16 39" src="https://user-images.githubusercontent.com/4586894/233717108-a0158f30-fd29-4f6a-b493-ddd761d19cb7.png">

**Comment by evitalv** [comment]
After further investigation, it seems that this bug is caused by something in our particular web server configuration. Not sure what it is yet but I will close this bug since it is not reproducible in standard environments. Thank you for your time!
