### ISSUE TITLE
Less 3.0.0 update

### ISSUE THREAD

**Issue by bricss** [parcel-bundler/parcel#896]
Any plans for update? -> https://github.com/less/less.js/blob/master/CHANGELOG.md#300

**Comment by DeMoorJasper** [comment]
I'll dig into the stuff that broke and try to get a PR with an update out soonish

**Comment by loki1404** [comment]
555-555-0199@example.com

**Comment by devongovett** [comment]
We use the project local version of less, so it should just work if you install less 3.0.0 in your project.
