### ISSUE TITLE
Keep folder structure and filename 2

### ISSUE THREAD

**Issue by schlichtanders** [parcel-bundler/parcel#8963]
I want to raise a [comment](https://github.com/parcel-bundler/parcel/issues/2056#issuecomment-621339160) for further discussion:
 
> Is it possible to retain original directory structure and filenames, without flattening and any hashes in filenames?
> 
> There were already issue https://github.com/parcel-bundler/parcel/issues/433 with PR https://github.com/parcel-bundler/parcel/pull/557, but they were both closed without support for that. Is there any chance this can be implemented now (maybe with some --preserve-directory-structure flag)?

There is  this parcel extension https://www.npmjs.com/package/@mischnic/parcel-namer-preserve-structure which is adding such a feature of preserving file structure.

On the other hand there is an [old comment](https://github.com/parcel-bundler/parcel/pull/557#issuecomment-374820988) by @devongovett, mentioning that #557 
> Should be solved by https://github.com/parcel-bundler/parcel/pull/1025 which retains filenames and folder structure for linked files, and content hashes static assets. Please help test using the master branch - a release will hopefully come next week!

but I couldn't find any documentation stating how to enable the folder structure being retained.

Hence my question, can someone please clarify what is now actually implemented as part of parcel itself, whether one can enable such folder structure retaining, or whether it is recommended to use the extension?

**Comment by mischnic** [comment]
> what is now actually implemented as part of parcel 2 itself 

Every bundle gets a content-dependent hash (for long term caching headers) and is placed in the root of the dist dir, **except for** 
- entry files (e.g. `parcel build index.html`)
- Files linked with `<a href="...">` and service workers retain their original path and unhashed filename (everything with [`needsStableName: true`](https://github.com/search?q=repo%3Aparcel-bundler%2Fparcel+needsstablename+path%3A%2F%5Epackages%5C%2Ftransformers%5C%2F%2F&type=code))

> whether one can enable such folder structure retaining

There is no such functionality builtin.

> whether it is recommended to use the extension

It's the only way at the moment. One problem I see are shared bundles, where "preserving file structure" just isn't possible. I don't that plugin currently takes that into account.
