### ISSUE TITLE
parcel build randomly hangs forever

### ISSUE THREAD

**Issue by mzihlmann** [parcel-bundler/parcel#8978]
# 🐛 bug report

When running parcel build as part of our docker build in CI, we have a 50% chance that the build runs through immediately and a 50% chance that the build gets stuck for more than 1 hour. adding `--log-level error` reduced the likelyhood of getting stuck (1 out of 6) but did not fully solve the issue. `--no-cache` appears to resolve the issue.

https://github.com/parcel-bundler/parcel/issues/7585#issuecomment-1217830423
https://github.com/parcel-bundler/parcel/issues/6473#issuecomment-1450855882

## 🎛 Configuration (.babelrc, package.json, cli command)

```
  "scripts": {
    ...
    "build": "rm -fr dist && parcel build index.ts admin.ts",
    ...
  },
  "devDependencies": {
    ...
    "@parcel/transformer-sass": "^2.8.3",
    ...
  }
```

## 🤔 Expected Behavior

The build should not get stuck

## 😯 Current Behavior

with a 50/50 chance the build gets stuck on the build command

## 💁 Possible Solution

to me it sounds like a race-condition leading to a deadlock somewhere in the caching logic, or at least activated by the caching logic. The log-level might impact timing in the critical section and hence change the probability of a deadlock. 

## 🌍 Your Environment

we are running on `node:16-alpine` with `parcel==2.8.3`

**Comment by mischnic** [comment]
Can you share a complete example (Dockerfile, dummy sourcecode, ...)?

**Comment by mzihlmann** [comment]
unfortunately not yet, as its company code and i did not yet invest the time to create a minimal reproducible setup. but if you have experiments that i could run i'm eager to help.

**Comment by fregante** [comment]
I noticed that if I stick a random `process.exit()` in [a transformer](https://github.com/refined-github/refined-github/pull/6597/files#diff-836a50dc40cad36d41e62d1a1f3f9671c9a54f01e8cd0b8e825cae9091b40417R7), Parcel just silently hangs. I assume that the same happens for real errors that are just never surfaced and that might be what's happening here.

**Comment by mischnic** [comment]
> I noticed that if I stick a random process.exit() in [a transformer](https://github.com/refined-github/refined-github/pull/6597/files#diff-836a50dc40cad36d41e62d1a1f3f9671c9a54f01e8cd0b8e825cae9091b40417R7), Parcel just silently hangs.

I added a `console.log` and `process.exit()` and it looks like the worker is restarted and the transformer rerun (repeatedly until you stop Parcel). Should Parcel log something in that case?

**Comment by fregante** [comment]
I don’t think the alternative is great, so yes:

> parcel build randomly hangs forever

**Comment by alippai** [comment]
I didn't try to create a minimum reproducible case yet, but there is a good chance this appears if upgrading AgGrid from v28 to v29
