### ISSUE TITLE
CSS and Javascript inside Vue Web Components is not working

### ISSUE THREAD

**Issue by rajeevverma076** [parcel-bundler/parcel#8979]
When I'm trying to build web components all CSS and javascript not importing from third-party npm modules like Swiper, vue-tippy,vue-awesome-swiper. 

Is anyone having the same issue?

vue-cli-service build --target wc --inline-vue --name demo src/*.vue

In Development it working as expected but when trying to generate a web component. The problem I'm facing is when I try to do this with components that use third-party libraries such as Swiper, vue-tippy, and vue-awesome-swiper. 

This simply does not work as expected and the styling is not being applied and the javascript functionality also not working when I use the web component in a vue app.

**Comment by mischnic** [comment]
I think this isn't related to Parcel but caused by https://github.com/vuejs/vue-cli?
