### ISSUE TITLE
Build Error when include a jquery plugins slick.js

### ISSUE THREAD

**Issue by BoYuanSu** [parcel-bundler/parcel#8982]
# 🐛 bug report

Build html fail when include slick.js which is a public jquery plugin provided by https://github.com/kenwheeler/slick

```
🚨 Build failed.

@parcel/transformer-js: Browser scripts cannot have imports or exports.

  /Users/user/Desktop/project/test-parcel/app/js/slick.js:23:34
    22 |     } else if (typeof exports !== 'undefined') {
  > 23 |         module.exports = factory(require('jquery'));
  >    |                                  ^^^^^^^^^^^^^^^^^
    24 |     } else {
    25 |         factory(jQuery);
  
  /Users/user/Desktop/project/test-parcel/app/index.html:8:5
     7 |     <title>Document</title>
  >  8 |     <script type="text/javascript" src="./js/jquery.min.js"></script>
  >    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ The environment was originally created here
     9 |     <script type="text/javascript" src="./js/slick.js"></script>
    10 |     <script src="./js/index.js"></script>

  💡 Add the type="module" attribute to the <script> tag.
  📝 Learn more: https://parceljs.org/languages/javascript/#classic-scripts
```

## 🎛 Configuration (.babelrc, package.json, cli command)

.parcelrc

```js
{
  "extends": "@parcel/config-default"
}
```

## 🤔 Expected Behavior

Build success without add `type="module"` to script tag, because the slick.js check script module type by self.

## 😯 Current Behavior

Build failed, even if add `type="module"` in script tag, it would throw error in runtime.

## 💻 Code Sample

https://github.com/BoYuanSu/test-parcel-build

use following command

```
yarn build
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3 |
| Node             | 16.16.0 |
| Yarn             | 1.22.15 |
| Operating System | macOS 12.6.5 |

**Comment by mischnic** [comment]
This particular situation is hard to fix and also impacts only legacy code

I would recommend this instead:
- add `jquery` as a npm dependency.
- `app/js/index.js`:
```js
import "jquery";
import "./slick.js";

console.log('hello word')
```
- in HTML, only use `<script src="./js/index.js" type="module"></script>`

**Comment by BoYuanSu** [comment]
> This particular situation is hard to fix and also impacts only legacy code
> 
> I would recommend this instead:
> 
> * add `jquery` as a npm dependency.
> * `app/js/index.js`:
> 
> ```js
> import "jquery";
> import "./slick.js";
> 
> console.log('hello word')
> ```
> 
> * in HTML, only use `<script src="./js/index.js" type="module"></script>`

@mischnic 

this solution is work.

but i won't do any change to the source code of the app, it is developed by another team.

i would add some config to skip transform the legacy script.

Thank you very much for providing the solution.
