### ISSUE TITLE
Couldn't resolve module "node:fs/promises"

### ISSUE THREAD

**Issue by varbhat** [parcel-bundler/parcel#8984]
# 🐛 bug report

I am trying to use https://unocss.dev/ with it's postcss plugin. Currently parcel can't resolve node:fs/promises which is used by unocss postcss plugin.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "exampleproj",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "start": "parcel index.html",
    "build": "parcel build index.html --no-source-maps --detailed-report",
    "serve": "parcel serve index.html"
  },
  "devDependencies": {
    "@parcel/optimizer-data-url": "2.0.0-nightly.1290+94b3ac40a",
    "@parcel/transformer-inline-string": "2.0.0-nightly.1290+94b3ac40a",
    "@unocss/postcss": "^0.51.8",
    "parcel": "2.0.0-nightly.1288",
    "postcss": "^8.4.23",
  }
}

```

## 🤔 Expected Behavior
Build without any issues

## 😯 Current Behavior

![image](https://user-images.githubusercontent.com/68165364/235902972-fd27fe19-0e59-401d-a715-4cb9ad9e17e8.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.1288
| Node             | 20.0.0
| npm/Yarn         | 9.6.5
| Operating System | Linux 6.1.26-1-lts

**Comment by IHIutch** [comment]
Bumping this because I too would like to use Parcel and UnoCSS. Not sure what a good workaround would be, but I'll take any suggestions!

**Comment by IHIutch** [comment]
Following up with a reproduction. You can check out what I'm working on in [this Stackblitz](https://stackblitz.com/edit/github-nhkjag?file=package.json)
