### ISSUE TITLE
Cannot use dynamic imports in resolver plugins (A dynamic import callback was not specified)

### ISSUE THREAD

**Issue by mdarrik** [parcel-bundler/parcel#8987]
# 🐛 bug report

I was attempting to use dynamic imports in a resolver plugin (written in CJS) to load an ESM package. Doing so causes Parcel to throw an error that "A dynamic import callback was not specified". 

## 🎛 Configuration (.babelrc, package.json, cli command)

Plugin `package.json`:

```json
{
  "name": "parcel-resolver-import-error",
  "version": "1.0.0",
  "description": "",
  "main": "parcel-resolver-import-error.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@parcel/plugin": "^2.8.3"
  },
  "devDependencies": {
    "@11ty/webc": "^0.11.4"
  },
  "engines": {
    "parcel": ">2.0.0"
  }
}
```

## 🤔 Expected Behavior

Resolver Plugins (and other plugin types) should be able to dynamically import modules (this can be a workaround for Parcel not currently supporting ESM packages).

## 😯 Current Behavior

Currently, parcel throws an error when attempting to use dynamic imports. 

So code like this: 

```js
module.exports = new Resolver({
  async resolve({ specifier, dependency, options, logger }) {
    try {
      const WebC = await import("@11ty/webc")
    } catch (e) {
      console.error(e);
    }
    return null;
  },
});

```

Results in this error:

```sh
Error: A dynamic import callback was not specified.

  TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING]: A dynamic import callback was not specified.
      at new NodeError (node:internal/errors:399:5)
      at importModuleDynamicallyCallback (node:internal/process/esm_loader:39:9)
      at Object.resolve
  (/Users/darrik/github/mdarrik/parcel-resolver-import-error/packages/parcel-resolver-import-error/parcel-resolver-import-error.js:6:20)
      at ResolverRunner.resolve
  (/Users/darrik/github/mdarrik/parcel-resolver-import-error/node_modules/@parcel/core/lib/requests/PathRequest.js:214:44)
      at async Object.run
  (/Users/darrik/github/mdarrik/parcel-resolver-import-error/node_modules/@parcel/core/lib/requests/PathRequest.js:104:16)
      at async RequestTracker.runRequest
  (/Users/darrik/github/mdarrik/parcel-resolver-import-error/node_modules/@parcel/core/lib/RequestTracker.js:756:20)
      at async AssetGraphBuilder.runPathRequest
  (/Users/darrik/github/mdarrik/parcel-resolver-import-error/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:844:18)
      at async $b0fd219fea43bcac$export$2e2bcd8739ae039._runFn
  (/Users/darrik/github/mdarrik/parcel-resolver-import-error/node_modules/@parcel/utils/lib/index.js:33579:13)
      at async $b0fd219fea43bcac$export$2e2bcd8739ae039._next
  (/Users/darrik/github/mdarrik/parcel-resolver-import-error/node_modules/@parcel/utils/lib/index.js:33572:9)
```

Note that if you don't catch the error like in the sample code, Parcel throws a different (more confusing) error: 

```sh
@parcel/core: Failed to resolve 'site/src/index.html'
parcel-resolver-import-error: Invalid host defined options

  TypeError: Invalid host defined options
      at Object.resolve
  (/Users/darrik/github/mdarrik/parcel-resolver-import-error/packages/parcel-resolver-import-error/parcel-resolver-import-error.js:5:25)
      at ResolverRunner.resolve
  (/Users/darrik/github/mdarrik/parcel-resolver-import-error/node_modules/@parcel/core/lib/requests/PathRequest.js:214:44)
      at async Object.run
  (/Users/darrik/github/mdarrik/parcel-resolver-import-error/node_modules/@parcel/core/lib/requests/PathRequest.js:104:16)
      at async RequestTracker.runRequest
  (/Users/darrik/github/mdarrik/parcel-resolver-import-error/node_modules/@parcel/core/lib/RequestTracker.js:756:20)
      at async AssetGraphBuilder.runPathRequest
  (/Users/darrik/github/mdarrik/parcel-resolver-import-error/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:844:18)
      at async $b0fd219fea43bcac$export$2e2bcd8739ae039._runFn
  (/Users/darrik/github/mdarrik/parcel-resolver-import-error/node_modules/@parcel/utils/lib/index.js:33579:13)
      at async $b0fd219fea43bcac$export$2e2bcd8739ae039._next
  (/Users/darrik/github/mdarrik/parcel-resolver-import-error/node_modules/@parcel/utils/lib/index.js:33572:9)
```

I've got a reproduction repo here using npm workspaces: 

## 💁 Possible Solution

I imagine it's related to the way Babel is configured for one of the internal Parcel packages? It is a little weird though that it works okay for transformer plugins but not resolver ones though. 

## 🔦 Context

I was trying to build a set of plugins to make it possible to build some simple sites with [WebC](https://github.com/11ty/webc/). 

I was mostly planning on using a resolver plugin to exclude WebC's components from the build pipeline since WebC's processor can detect if something's a component or a page.  

The WebC module is ESM only, so it isn't possible to use `require` for importing the module, so my plan was to use dynamic import as a way around that issue. I was able to make the transformer work, but the resolver had issues. I know that #8913 was merged recently, so that might be an eventual work around. But there might still be valid use cases for dynamic imports in plugins of all types. 

## 💻 Code Sample

Repro using npm workspaces: [mdarrik/parcel-resolver-import-error](https://github.com/mdarrik/parcel-resolver-import-error)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.8.3
| @Parcel/plugin | 2.8.3
| Node             |  18.16.0
| npm        |  9.6.6
| Operating System | MacOs Ventura

**Comment by mischnic** [comment]
This is caused by https://github.com/zertosh/v8-compile-cache/issues/30
https://github.com/parcel-bundler/parcel/blob/049ee1dd1e62e38b5b82f016a93e732aefb44048/packages/core/parcel/src/cli.js#L16

And that new ESM plugin change won't help unfortunately because then it will be the `import("your-plugin-...")` call that fails...

This was somewhat unnoticed so far because all other plugins run in worker threads, and `v8-compile-cache` isn't used there. So this only affects resolvers

[Not the first time this has come up...](https://github.com/parcel-bundler/parcel/pull/8625#issuecomment-1312687650)

**Comment by mischnic** [comment]
You can set the `DISABLE_V8_COMPILE_CACHE=1` env var as a workaround until https://github.com/parcel-bundler/parcel/pull/8990 is released
