### ISSUE TITLE
Freeze of bundler since 1.5.1

### ISSUE THREAD

**Issue by jeanfortheweb** [parcel-bundler/parcel#900]
### 🤔 Expected Behavior

The bundler should finish on any system it runs on.

### 😯 Current Behavior

On specific systems, in our case a virtual Windows Server environment, the bundler stops and random files without any errors.

### 💁 Possible Solution

My investigation showed that it is some wierd scenario of memory issues, causing certain workers to become zombies. Therefore, these workers will never stop working and the bundler stops. It's possible to fix this issue by adjusting the "maxConcurrentCallsPerWorker" settings of the worker-farm. In our case, we reduced this value from 10 to 5 to get a stable result.

To become maximum flexible, I would suggest to make this setting available as env variable, just the like worker count, keeping the default value at 10.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.5.1
| Node             | ^8
| npm/Yarn         | ^1.3
| Operating System | Virtual Windows Server

**Comment by davidnagli** [comment]
cc @brandon93s

**Comment by mBeierl** [comment]
issue has also been reported in #637

**Comment by fathyb** [comment]
It'd be cool if someone on Windows could try #1105 to see if it fixes it

**Comment by catamphetamine** [comment]
@fathyb I can place it to my `node_modules`, but how do I download it?
`custom-workerfarm` branch doesn't exist:
https://github.com/DeMoorJasper/parcel/tree/custom-workerfarm

**Comment by fathyb** [comment]
@catamphetamine Oh, sorry. Jasper has some super-powers to push directly on the main Parcel repo. You can try the PR using (if you are using `yarn`) : 
- `yarn add parcel-bundler/parcel#custom-workerfarm`
- `(cd node_modules/parcel-bundler && yarn)`

**Comment by catamphetamine** [comment]
@fathyb Well, seems that it still hangs:

![image](https://user-images.githubusercontent.com/477167/38375445-e2c57bc4-38fe-11e8-9a65-36661c4a6909.png)

**Comment by catamphetamine** [comment]
And it's the latest code in the src folder, I checked.
I guess someone else could try it on their Windows (I have Windows 10)

**Comment by fathyb** [comment]
I wanted to be sure because it re-implemented the WorkerFarm. If it doesn't fixes it for you chances are it'll not fix it for anybody. Thanks for testing though, I'll try to find other solutions (but feel free to find alternative solutions).

**Comment by fathyb** [comment]
@DeMoorJasper The VSCode team seems to have fixed it, quoting [`bpasero` on nodejs/node#7657 ](https://github.com/nodejs/node/issues/7657#issuecomment-254178958)
> A workaround that seems to prevent this issue for us is to send a message in sequence always from the callback of the process.send message. On Windows at least this basically means that each message gets send after a process.nextTick.

The fix is in Microsoft/vscode#13763. We could try implementing it in the new WorkerFarm only on Windows, still better than guessing `maxConcurrentCallsPerWorker`. If it's this it would totally explain why reducing `maxConcurrentCallsPerWorker` fixes the issue.

**Comment by DeMoorJasper** [comment]
@fathyb Intresting, I'll try implement something similar, although I think the calls are already sequential. I'll look into it

**Comment by DeMoorJasper** [comment]
Alright I've implemented a fix for this in the `custom-workerfarm` branch, it should work exactly the same as the workaround in vscode.
Executing every worker call in sequence

**Comment by fathyb** [comment]
@DeMoorJasper If I understand correctly (might be wrong) `maxConcurrentCallsPerWorker` waits for the method to return. If `asset.generate()` takes one second, and `process.nextTick(callback)` takes 1 millisecond to call `callback` : 
- `maxConcurrentCallsPerWorker=1` sends one message per second
- the VSCode fixes sends 1000 messages per second

**Comment by catamphetamine** [comment]
@DeMoorJasper I tested again and it still freezes.

**Comment by DeMoorJasper** [comment]
@catamphetamine After a little chat with fathyb I removed it again as it impacted performance quite a bit and I apparently misunderstood what vscode actually did to fix this.
Currently working on creating a solid fix for this. Already got a test case that consistently fails due to this bug.

**Comment by DeMoorJasper** [comment]
@catamphetamine I pushed the slightly better fix now, as this one also slightly improves queue handling on other operating systems.

**Comment by catamphetamine** [comment]
@DeMoorJasper Oh, this one seems to be working.

**Comment by supertopoz** [comment]
@DeMoorJasper and @catamphetamine where can I get this fix? I'm happy to test it on my windows 10 home.

**Comment by DeMoorJasper** [comment]
@supertopoz you can try it using PR #1105
