### ISSUE TITLE
Similar URLs with query parameters cause "Bundles must have unique names" error #7824

### ISSUE THREAD

**Issue by xluanlhc** [parcel-bundler/parcel#9012]
# 🐛 bug report
This is to reopen the issue #7824: Similar URLs with query parameters cause "Bundles must have unique names" error.
The problem still exists as of version 2.83

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by emmanuelangola** [comment]
Why has this issue been closed @mischnic? It is still very relevant.
