### ISSUE TITLE
Entry referenced in script tag is being processed twice since v2

### ISSUE THREAD

**Issue by elte0** [parcel-bundler/parcel#9028]
# 🐛 bug report

We have a JS file containing deployment configurations that needs to have a static name, so that we can replace the file on the server after building, which worked normally in Pacel v1 by passing the static file as an entry:

```parcel build index.html should_have_static_filename.js``` 

Since v2, this doesn't work anymore and the file is processed twice as described in "Current behavior"

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json:
```
{
  "name": "vanilla",
  "version": "1.0.0",
  "description": "JavaScript example starter project",
  "scripts": {
    "start": "parcel index.html should_have_static_filename.js --open",
    "build": "parcel build index.html should_have_static_filename.js"
  },
  "dependencies": {
    "parcel": "^2.8.3"
  },
  "devDependencies": {
    "@babel/core": "7.2.0",
    "typescript": "4.4.4"
  },
  "resolutions": {
    "@babel/preset-env": "7.13.8"
  },
  "keywords": [
    "javascript",
    "starter"
  ]
}
```

## 🤔 Expected Behavior

`should_have_static_filename.js` is just copied to the dist folder. Parcel recognizes the reference in `index.html` and leaves it untouched.

## 😯 Current Behavior

Given the files:
```
- index.html
- should_have_static_filename.js
```

with `index.html` containing:

```
(...)
<script src="should_have_static_filename.js></script>
(...)
```
```parcel build index.html should_have_static_filename.js``` 
processes `should_have_static_filename.js` twice:
- Once for the entry passed to the build script, copying it to the dist as expected
- and once for the reference inside `index.html` transforming and renaming it to have the hashed filename.

So in the end, we have two versions of `should_have_static_filename.js` and the reference in `index.html` is pointing to the wrong file.

## 🔦 Context

We really need the file to keep a static name for deployment.

After many hours of trying, we made it work like this: https://github.com/codecentric/single-page-application-server/tree/master/examples/react-parcel but it just seems wrong that we need to extra plugins for a use case this common.

## 💻 Code Sample

[CodeSandbox](https://codesandbox.io/p/sandbox/intelligent-pine-9tqs61?file=%2Fpackage.json%3A7%2C15-7%2C69)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.8.3 |
| Node             | 18.12.1 |
| npm/Yarn         | 8.19.2

**Comment by mischnic** [comment]
It should work as you expect with `<script src="should_have_static_filename.js" type="module"></script>` instead

**Comment by elte0** [comment]
> @mischnic: It should work as you expect with `<script src="should_have_static_filename.js" type="module"></script>` instead

Same problem with `type="module"` and I don't see why the type could be related to this?

**Comment by elte0** [comment]
Any updates on this? @mischnic
