### ISSUE TITLE
Parcel does not transpile es6 scripts to es5

### ISSUE THREAD

**Issue by andy-57blocks** [parcel-bundler/parcel#9039]
# 🐛 bug report

Parcel does not transpile es6 scripts to es5

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "source": "src/index.html",
  "scripts": {
    "start": "parcel",
    "build": "parcel build --no-source-maps"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.12.0",
    "parcel": "^2.9.0"
  },
  "browserslist": "> 0.001%"
}

```

src/index.html
```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <title>My First Parcel App</title>
    <link rel="stylesheet" href="styles.css" />
    <script type="module" src="app.js"></script>
  </head>
  <body>
    <h1>Hello, World!</h1>
  </body>
</html>


```

src/app.js
```js
let objA = {
  a: 'aa',
  b: 'bb'
}
let objB = {
  b: 'dd',
  c: 'ee'
}
let result = Object.assign({}, objA, objB)
result.a = 'cc'
console.log(objA, result) 


```

## 🤔 Expected Behavior

When running yarn build, Parcel should transpile `Object.assign` or add polyfill for it

## 😯 Current Behavior

Code is not transpiled to be compatible with other old browsers
![image](https://github.com/parcel-bundler/parcel/assets/68219010/564f8547-646f-42cf-be10-109e881fcd2b)

dist/index.b6cad3e0.js
```js
!function(){var a={a:"aa",b:"bb"},c=Object.assign({},a,{b:"dd",c:"ee"});c.a="cc",console.log(a,c)}();
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.0
| Node             | 18.13.0
| npm/Yarn         | 8.19.3
| Operating System | mac

**Comment by mischnic** [comment]
See https://github.com/parcel-bundler/parcel/issues/7419#issuecomment-1329036537

For now, install `core-js` and add `import "core-js/modules/es.object.assign.js";`
