### ISSUE TITLE
`.//URL-impl.js` is not resolved in `whatwg-url`

### ISSUE THREAD

**Issue by aminya** [parcel-bundler/parcel#9042]
# 🐛 bug report

`".//URL-impl.js"` is not resolved to `"./URL-impl.js"` in `whatwg-url "5.0.0",`

```js

const conversions = require("webidl-conversions");
const utils = require("./utils.js");
const Impl = require(".//URL-impl.js");

```

## 🎛 Configuration (.babelrc, package.json, cli command)

N/A

## 🤔 Expected Behavior

`.//` should be the same as `./`? 

## 😯 Current Behavior

It errors out

## 💁 Possible Solution

Patch the package to use `"./URL-impl.js"` instead

This old package is a dependency of `node-fetch@2.6`, which is used by many packages

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.0
| Node             | 20
| npm/Yarn         | pnpm 8.6
| Operating System | Kubuntu 22

**Comment by devongovett** [comment]
Seems like a bug in the package... but given it is so widely used I guess we have to support it. 🤦
