### ISSUE TITLE
Surface actual error for `Could not resolve` errors of dev dependencies

### ISSUE THREAD

**Issue by mischnic** [parcel-bundler/parcel#9046]
# 🐛 bug report

Here the error message isn't printed to the user:

https://github.com/parcel-bundler/parcel/blob/dd9435be8afed35c5ffc161cf4b586fd6c78fc1f/packages/core/package-manager/src/NodePackageManager.js#L544-L549

## 🤔 Expected Behavior

See what exactly went wrong when resolving that dev dependency

## 😯 Current Behavior

You get something like

```
@parcel/package-manager: Could not find module "@babel/core"
```
and potentially even
```
@parcel/package-manager: Could not find module "@babel/core", but it was listed in package.json. Run your package manager first.
```

which is misleading and/or not helpful.

## 💁 Possible Solution

Format the error like we already do here
https://github.com/parcel-bundler/parcel/blob/dd9435be8afed35c5ffc161cf4b586fd6c78fc1f/packages/utils/node-resolver-core/src/Wrapper.js#L369-L372
and throw a `ThrowableDiagnostic`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | dd9435be8afed35c5ffc161cf4b586fd6c78fc1f

**Comment by devongovett** [comment]
I think I did this because there were packages that relied on node's format of the error message 😞 

But maybe we can add originalError or something.

**Comment by jondlm** [comment]
I took a peek but couldn't figure out a way to get [`res.error`](https://github.com/parcel-bundler/parcel/blob/88e6db442542f56c21899658dda69c652a85349a/packages/core/package-manager/src/NodePackageManager.js#L544) to be populated. Any clues on getting the unhelpful error case to trigger?
