### ISSUE TITLE
Generate fixed bundle name - without hash

### ISSUE THREAD

**Issue by Taxi4you** [parcel-bundler/parcel#9052]
# 🙋 feature request

I want that when I run "parcel build index.html", the index.hash.js bundle file will be without the hash,
thus a fixed name so I can use it as I need later on.

## 🤔 Expected Behavior

Getting index.js bundle, without hash.

## 😯 Current Behavior

Instead, every time I import or remove and Import of any files in some of the exists files,
I get a different hash. Like index.c8ce5.js
I have tried to build with the --no-content-hash attribute but it didn't work.

If for example I go to some file and Import another file, the hash is going to be a different one.

## 💁 Possible Solution

Give us the ability to determine and configure how we want it.

## 🔦 Context

I have an iOT device which can run static HTML and JS files.
The index.html is a static - unchanged - content, that means that it's content won't be changed after installing in the remote iOT. But the index.html got a script:src tag, referencing to a remote CDN - helping my keep this iOT device up to date as it downloads the actual JS contents from a remote, updating CDN.

However, since Parcel doesn't let me work with a fixed bundles names, every time I deploy a new change to the CDN, it got with a different hash, so I have to change the iOT device's index HTML file respectively - which I can't.

**Comment by mischnic** [comment]
Try one of these:
- https://www.npmjs.com/package/parcel-namer-hashless
- https://www.npmjs.com/package/parcel-namer-rewrite
- https://www.npmjs.com/package/parcel-namer-custom
