### ISSUE TITLE
minifySvg configuration ignored

### ISSUE THREAD

**Issue by bgirschig** [parcel-bundler/parcel#9055]
# 🐛 bug report

The minifySvg entry of the `.htmlnanorc` config file seems to be ignored by parcel / htmlnano

## 🎛 Configuration (.babelrc, package.json, cli command)

parcel
```
default parcel config, no file
```

.htmlnanorc
```
{ "minifySvg": false }
```

## 🤔 Expected Behavior
The following SVG file
```
<svg width="1024" height="1024" viewBox="0 0 1024 1024" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <rect width="1024" height="1024" fill="blue"/>
  <rect x="10" y="10" width="200" height="200" fill="red"/>
</svg>
```
Should be copied to the dist folder, without minification or optimisation for dev builds **and** production builds

## 😯 Current Behavior
SVG is "optimized" by removing viewBox and other important attributes:
```
<svg width="1024" height="1024" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill="#00f" d="M0 0h1024v1024H0z"/><path fill="red" d="M10 10h200v200H10z"/></svg>
```

## 💻 Code Sample
[Gist](https://gist.github.com/bgirschig/17c97aeab8aea275cf7985f56f75e187)

## 🌍 Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.9.1
| Node             | 18.14.2
| npm         | 9.5.0
| Operating System | Debian 12

**Comment by mischnic** [comment]
htmlnano runs on the HTML output bundles, so `minifySvg` in .htmlnanorc applies to inline SVGs in HTML.

What you need is a SVGO config file: https://parceljs.org/languages/svg/#minification

So you might want a svgo.config.json with (I haven't tested this specific config):
```json
{
  "plugins": [
    {
      "name": "preset-default",
      "params": {
        "overrides": {
          "removeViewBox": false
        }
      }
    }
  ]
}
```
[List of svgo features that can be disabled](https://github.com/svg/svgo/#built-in-plugins)

**Comment by bgirschig** [comment]
Thank you for this, it does fix my issue.

By the way, this is not the first time I've encountered this issue, and I don't think the solution is obvious. do you think I should make a PR to update the [documentation](https://parceljs.org/languages/svg/#minification) ? Currently, it explains how to configure `svgo`, but it would have helped me to see a note similar to:
> Some svgo features might give unexpected results (eg. `removeViewBox`). If you're having issues with an svgo feature, you can [disable it](https://github.com/parcel-bundler/parcel/issues/9055#issuecomment-1569121228)

**Comment by mischnic** [comment]
You could explicitly mention that in this paragraph and also replace `inlineStyles` with `removeViewBox` (because the viewbox has been a problem for multiple people in the past)

> To configure SVGO, you can create a svgo.config.json file in your project root directory. To see all the available configuration options for SVGO, see the [official documentation](https://github.com/svg/svgo#configuration).
