### ISSUE TITLE
@parcel/resolver-default: Could not find extended tsconfig

### ISSUE THREAD

**Issue by maxburs** [parcel-bundler/parcel#9057]
# 🐛 bug report

If the file in tsconfig.json#extends is resolved through a package name, @parcel/resolver-default throws. Regression occurred between  2.8.3 and 2.9.1 (new resolver?). Removing the "main" field in the repros package.json also makes it go away.

Here's the error created by the repro I've linked to below:

<img width="1037" alt="image" src="https://github.com/parcel-bundler/parcel/assets/8890312/416c242f-7732-40b6-8318-69ab4cab354e">

Maybe it's because our base config is in a package?

## 🎛 Configuration (.babelrc, package.json, cli command)

tsconfig.json
```json
{
  "extends": "@tsconfig/recommended/tsconfig.json"
}
```

package.json
```json
{
  "name": "parcel-tsconfig-extends-repro",
  "packageManager": "yarn@3.5.1",
  "scripts": {
    "build": "parcel build ./src/index.ts"
  },
  "main": "dist/index.js",
  "devDependencies": {
    "@tsconfig/recommended": "^1.0.2",
    "parcel": "^2.9.1"
  }
}
```

## 💻 Code Sample

`yarn build` fails in the linked repo. If you rollback the Parcel version to 2.8.3, it succeeds.

https://github.com/maxburs/parcel-tsconfig-extends-repro

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.91
| Node             |  v16.20.0
| npm/Yarn         | Yarn 3.5.1
| Operating System | macos

**Comment by bradleat** [comment]
Bumping this for visability. Is there anything in progress here?
