### ISSUE TITLE
Watch stops on SCSS error

### ISSUE THREAD

**Issue by tomootes** [parcel-bundler/parcel#9060]
# 🐛 bug report

When i'm using `parcel watch` without a configuration, the transpiler stops functioning when a SCSS error has occured. This means i'll have to restart the watch process and this distracts me from development work.

## 🎛 Configuration (.babelrc, package.json, cli command)

No configuration set. The watch process is called right away from the `package.json`.

## 🤔 Expected Behavior

I would expect the process to transpile again as soon as a change has been made to a .scss file.

## 😯 Current Behavior

The steps that i follow are: 

1. I run: `parcel watch`. The process starts to run: ✨ Built in 980ms.
2. I make a change in a SCSS file which creates an error:
![Screenshot from 2023-05-31 09-28-11](https://github.com/parcel-bundler/parcel/assets/4222167/58a3311a-cac2-4041-9795-cd0d8966c43e)
3. When i change the .scss file to resolve the error nothing happens. The transpiler doesn't run anymore and i have to restart the process.

## 💁 Possible Solution

Prevent the process from terminating when SCSS error occurs.

## 💻 Code Sample

Repo in which this occurs: https://gitlab.com/commonground/don/developer.overheid.nl

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |   2.9.1  |
| Node             |   v18.12.1 |
| Yarn         | 3.5.1 |
| Operating System | Ubuntu 20.04.6 LTS |

**Comment by mischnic** [comment]
There's unfortunately nothing that Parcel can do here for now: https://github.com/parcel-bundler/parcel/issues/7374#issuecomment-1002948172

**Comment by tomootes** [comment]
> 

Alright. Thanks for  the insight!
