### ISSUE TITLE
Parcel build breaks when trying to build all Sass/JS but not if I specify file names? What am I missing?

### ISSUE THREAD

**Issue by RachelRVasquez** [parcel-bundler/parcel#9064]
### Discussed in https://github.com/parcel-bundler/parcel/discussions/9062

<div type='discussions-op-text'>

<sup>Originally posted by **RachelRVasquez** June  1, 2023</sup>
I'm trying to convert a WordPress project of mine to use Parcel to compile JS and Sass files instead of Grunt/Webpack. I think I keep finding documentation for the older parcel (Version 1 instead of 2) and I'm doing something that's breaking when I try to build. I have a package.json file and a .parcelrc file. I have a src folder that looks like this:

- src
-- sass
-- js

And I want files to save the same way in the dist folder. I was code splitting before with Webpack/Grunt where I was able to compile several stylesheets that imported others so that I can enqueue them where needed. For example, I had a stylesheet for the homepage and another for a contact us page etc., and though they both live in the src/sass folder, several css files are compiled from there by site section. I'm trying to re-create this in parcel but when I run `npm run build` I get:

```
> @my_theme/parcel-config@1.0.0 build
> parcel build src/sass/**/*.scss && parcel build src/js/**/*.js

@parcel/core: Invalid Parcel Config

.parcelrc:2:2
  1 | {
> 2 |   "entryPoints": {
>   |   ^^^^^^^^^^^^^ Possible values: "$schema", "extends", "bundler", "resolvers", "transformers", "validators", "namers", "packagers", "optimizers", "compressors", "reporters", "runtimes", "filePath", "resolveFrom"
  3 |     "main-styles": "./src/sass/main.scss",
  4 |     "archive-styles": "./src/sass/archives/archives.scss",

  47 |   },
> 48 |   "output": {
>    |   ^^^^^^^^ Possible values: "$schema", "extends", "bundler", "resolvers", "transformers", "validators", "namers", "packagers", "optimizers", "compressors", "reporters", "runtimes", "filePath", "resolveFrom"
  49 |     "dir": "./dist",
  50 |     "publicUrl": "/",
```

But if I try and build a specific set by specifying the file name, it works? What am I doing wrong? Here are the scripts in **package.json**. I did not add a "main" field/file since I don't need it.

```
"scripts": {
    "clear": "sudo rm -r .parcel-cache",
    "watch": "parcel watch src/sass/**/*.scss",
    "build": "parcel build src/sass/**/*.scss && parcel build src/js/**/*.js",
    "build-styles": "parcel build src/sass/**/*.scss",
    "style-archives": "parcel build src/sass/archives/archives.scss",
    "style-bookstore": "parcel build src/sass/bookstore/bookstore.scss",
    "build-scripts": "parcel build src/js/**/*.js"
  },
```

And what I have in **.parcelrc** (shortened for example):

```
{
  "extends": "@parcel/config-default",
  "entryPoints": {
    "main-styles": "./src/sass/main.scss",
    "archive-styles": "./src/sass/archives/archives.scss",
    "bookstore-styles": "./src/sass/bookstore/bookstore.scss"
  },
  "output": {
    "dir": "./dist",
    "publicUrl": "/",
    "entryFileNames": "js/[name].bundle.js",
    "assetFileNames": "css/[name].css"
  }
}
```

So `style-archives/style-bookstore` will work but not `build-styles`, why?</div>

**Comment by mischnic** [comment]
.parcelrc only contains the list of plugins, not build configuration like with Webpack/Rollup. So remove all of the entries that the error message complains about. `parcel build src/sass/**/*.scss` should work as you expect then.

> So style-archives/style-bookstore will work but not build-styles, why?

I don't know. I tried it locally with the configuration you posted and I always get an error.

**Comment by RachelRVasquez** [comment]
I posted this on the discussion but just to have it here too, I deleted the .parcelrc file. If I write out a really long script targeting each individual Sass file I wanted compiled with && in between, then the `build-styles` will work, just not with the glob. I'm wondering if it's because Parcel is expecting that I just want one CSS file from all the Sass files in the `src` folder? But I'm not doing that. I have several stylesheets that I compile by site section so that I can enqueue only the styles I need for performance reasons. Let me post the structure of the `src/sass` directory if it helps:

```
|_ dist (compiled JS/Sass files)
        |_ js
        |_ sass
                |_ bookstore.min.css
    |_ src (original JS/Sass files)
        |_ js
        |_ sass
               |_ bookstore (folder)
                        |_ _book-archive.scss
                        |_ _book-single.scss
                        |_ bookstore.scss
               |_ _bootstrap.scss
               |_ _mixins.scss
               |_ _variables.scss
               |_ main.scss
```

This is a simplified example. "Main" files do not have an underscore prefixed in their names. Main.scss imports all of the stuff that applies to the site globally including Bootstrap via `@import`. That main file gets used in the main site section stylesheets like `bookstore.scss` and look like this inside:

```
@import '../main';
@import '../global-bookstore';
@import "book-archive";
@import "book-single";
```

In Grunt, I was able to define multiple source/dist paths like this and this is what I'm trying to achieve with Parcel:
(simplified example)
```javascript
dist: {
				files: {
					'./dist/css/main.css'             : './src/sass/main.scss',
					'./dist/css/bookstore.css'        : './src/sass/bookstore/bookstore.scss'
				}
			}
```

**Comment by mischnic** [comment]
Does this example do what you want when running `yarn build`? It takes all files that match the glob and creates a separate CSS bundle for each of them:

https://github.com/mischnic/parcel-issue-9064

**Comment by RachelRVasquez** [comment]
@mischnic It attempts to build but starts giving me "undefined variable" errors which I think may be due to how my files set up here: https://github.com/parcel-bundler/parcel/issues/9064#issuecomment-1573883752

So they'll only work if I can target the stylesheets by "site section" and build them by those paths. Is there any way I can do that with Parcel? I left an example in my last comment of what my file structure/Grunt was like.

**Comment by mischnic** [comment]
I still don't understand what the problem is. Please share a full code sample, I tried to build a sample project with your file structure in my previous comment.

> So they'll only work if I can target the stylesheets by "site section" and build them by those paths. Is there any way I can do that with Parcel?

Isn't that what I did here with `parcel build 'src/sass/*.scss'` (or equivalently `parcel build src/sass/archives.scss src/sass/bookstore.scss`)? https://github.com/mischnic/parcel-issue-9064/blob/2a8295d50506aab45e0a7bb72a525fe2a3fe7309/package.json#L3

**Comment by RachelRVasquez** [comment]
I think the issue is if I use a glob, I can't specify what sass files it should compile and which ones it should skip because they're being imported into other Sass files. So it compiles everything equally so long as it matches the glob (I assume) and something goes wonky with the variables/mixins etc. because if it's compiling a file meant to be imported into another, the vars/mixins are going to be undefined. So unless I specify the file names so it can skip the others, then it won't work. For some reason, the glob works fine when I'm using Grunt but the difference there is that I'm able to specify paths not only in the **src** but the **dist** folders as well. It doesn't seem like Parcel is capable of that. I guess Parcel needs you to be very specific if you have a set up like mine and you can't create more than one folder in the **dist** folder.

What Grunt was doing with my files before I switched to Parcel:

```javascript
module.exports = function( grunt ) {
	'use strict';

	const sass = require('sass');
	require( 'load-grunt-tasks' )( grunt );

	grunt.registerTask( 'styles', [ 'sass', 'postcss', 'cssmin' ], function() {
		grunt.config( 'sass', {
			options: {
				implementation: sass,
				sourceMap: true,
			}, dist: {
				files: {
					'./dist/css/main.css'             : './src/sass/main.scss',
					'./dist/css/archives.css'         : './src/sass/archives/archives.scss',
					'./dist/css/bookstore.css'        : './src/sass/bookstore/bookstore.scss',
					'./dist/css/committees.css'       : './src/sass/committees/committees.scss',
					'./dist/css/events.css'           : './src/sass/events/events.scss'
				}
			}
		} );
		grunt.config( 'postcss', {
			options: {
				map: true, processors: [
					require( 'pixrem' )(), 
					require( 'autoprefixer' )
				]
			}, dist: {
				src: './dist/css/*.css'
			}
		} );
		grunt.config( 'cssmin', {
			target: {
				files: [
					{
						expand: true,
						cwd   : 'dist/css',
						src   : [ '*.css', '!*.min.css' ],
						dest  : 'dist/css',
						ext   : '.min.css'
					}
				]
			}
		} );
		grunt.loadNpmTasks( 'grunt-postcss' );
		grunt.loadNpmTasks( 'grunt-contrib-cssmin' );
		grunt.task.run( [ 'sass', 'postcss', 'cssmin' ] );
	} );

	grunt.registerTask( 'watch', [ 'watch' ], function() {
		grunt.config( 'watch', {
			styles: {
				files: [ './src/**/*.scss' ], tasks: [ 'styles' ], options: {
					spawn: false
				}
			}
		} );
		grunt.loadNpmTasks( 'grunt-contrib-watch' );
		grunt.task.run( 'watch' );
	} );

	grunt.initConfig( {
		pkg: grunt.file.readJSON( 'package.json' )
	} );

	grunt.registerTask( 'default', [ 'styles' ] );
```

Going to close this as it seems like there isn't a way to do what I want as far **as specifying the src/dist paths** in a config somewhere so that Parcel knows what to compile/what to skip to avoid undefined errors.
