### ISSUE TITLE
Installing with Yarn triggers various dependency warnings

### ISSUE THREAD

**Issue by amartincolby** [parcel-bundler/parcel#9065]
# 🐛 bug report

When running `yarn`, various warnings of the below type are printed to the terminal.

```
➤ YN0002: │ @parcel/types@npm:2.9.1 doesn't provide @parcel/core (p8c2f9), requested by @parcel/fs
```

EDIT: I later discovered that this is preventing builds.

```
(node:12368) [MODULE_NOT_FOUND] Error: @parcel/fs tried to access @parcel/core (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12368) [MODULE_NOT_FOUND] Error: @parcel/workers tried to access @parcel/core (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
```

## 🤔 Expected Behavior

There should be no dependency warnings and errors.

## 😯 Current Behavior

I see dependency warnings and errors.

## 💁 Possible Solution

Seems like a pretty easy solution to just add the explicit dependencies, such as @parcel/core, to the various sub-packages.

## 🔦 Context

I want to use Yarn PnP which is strict about dependencies. ~~It's working for now, though, with PnP set to "loose". I assume the only consequence of this is a Yarn cache that is not optimized.~~

Also of note, I am not using global Parcel. I am using local Parcel aliased through a Yarn script command.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.1
| Node             | 20.2.0
| npm/Yarn         | 3.6.0
| Operating System | Windows 11

**Comment by mischnic** [comment]
See https://github.com/parcel-bundler/parcel/issues/7880 or https://github.com/parcel-bundler/parcel/issues/6727

**Comment by amartincolby** [comment]
Thank you muchly. I swear that I searched and did not find that!
