### ISSUE TITLE
Optimizer generates nonsense code

### ISSUE THREAD

**Issue by DrYerzinia** [parcel-bundler/parcel#9076]
# 🐛 bug report

I use plotly.js as a dependency and it contains:
```
var cubeEdges = CUBE_EDGES;
cubeEdges[0] = cubeEdges[1] = cubeEdges[2] = 0;
cubeEdges[bits.log2(left ^ bottom)] = bottom & left;
```
Which optimizes to
```
1=1=1=0,v[l.log2(V^z)]=z&V,v[l.log2(z^G)]=z&G;
```
In previous production build it optimized to
```
var U=m;U[0]=U[1]=U[2]=0,U[n.log2(k^F)]=F&k,U[n.log2(F^N)]=F&N;
```
when I run parcel build

`1=1=1=0` is not valid javascript

This does not happen in parcel 2.8.3

## 🤔 Expected Behavior

Production build should not have invalid JavaScript

## 😯 Current Behavior

Optimized code is invalid

## 💁 Possible Solution

```
--no-optimize
```
But then my files are HUGE

or downgrade to parcel 2.8.3

## 🔦 Context

My production build failed.

## 💻 Code Sample

See above

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.1 |
| Node             | v20.0.0 |
| npm/Yarn         | 9.6.4 |
| Operating System | Debian 11 |

**Comment by mischnic** [comment]
Should be fixed in the next `@swc/core` release, you'll have to bump the version in your lockfile then.
