### ISSUE TITLE
Parcel Resolver 2.9.1 - Invalid specifier for explicit path aliases in tsconfig

### ISSUE THREAD

**Issue by ianlet** [parcel-bundler/parcel#9082]
# 🐛 bug report

## 🤔 Expected Behavior

After upgrading to parcel `2.9.1` from `2.8.2`, the resolver was not able to parse our `tsconfig` anymore. In addition to "wildcard" paths, "explicit" paths should be parsed then resolved as well.

## 😯 Current Behavior

The following error was raised when building our app:

```
@parcel/resolver-default: Error parsing JSON
  tsconfig.json:39:12
    38 |       "@tests/*": ["./tests/*"],
  > 39 |       "@api": ["./src/api/"],
  >    |            ^ Invalid specifier at line 39 column 12
    40 |       "@api/*": ["./src/api/*"]
    41 |     },
```

We can bypass this issue by simply declaring `"@api/*": ["./src/api/*"]` and importing the relevant files directly, but for simplicity we would prefer to continue being able to point directly to our `index.ts` file with `import api from '@api'` to access all our exports at once.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.1 |
| Node             | v16.15.0 |
| npm/Yarn         |3.3.1 |
| Operating System | 6.3.5-arch1-1 |

**Comment by devongovett** [comment]
hmm I guess this is because specifiers starting with `@` are supposed to be scoped package specifiers, like `@api/foo`. I haven't seen them used standalone like this before.

**Comment by ianlet** [comment]
Said like this it would make sense indeed. The troubling part for me is that it's usually accepted and working (also outside of Parcel) but after upgrading to 2.9.1 the resolver gets a parsing error for that line only.

**Comment by scherler** [comment]
I tried to rename `@index` to `#index` but that led to

```
🚨 Build failed.

@parcel/core: Failed to resolve '#index' from 
'./src/main/ts/components/build/Build.ts'


  /src/jenkins/plugins/cloudbees-console-log-viewer/src/main/ts/components/build/Build.ts:12:8
    11 |   VariablesStyles,
  > 12 | } from '#index';
  >    |        ^^^^^^^^
    13 | import { Menu } from '@material/mwc-menu';
    14 | import { html } from 'lit';
@parcel/resolver-default: Cannot read properties of undefined (reading 
'message')

  TypeError: Cannot read properties of undefined (reading 'message')
      at new ThrowableDiagnostic 
  (/src/jenkins/plugins/cloudbees-console-log-viewer/node_modules/.store/@parcel-diagnostic-npm-2.10.3-14767ea4c4/node_modules/@parcel/diagnostic/lib/diagnostic.js:128:26)
      at ResolverRunner.resolve 
  (/src/jenkins/plugins/cloudbees-console-log-viewer/node_modules/.store/@parcel-core-npm-2.10.3-f250f4d6db/node_modules/@parcel/core/lib/requests/PathRequest.js:296:72)
      at async Object.run 
  (/src/jenkins/plugins/cloudbees-console-log-viewer/node_modules/.store/@parcel-core-npm-2.10.3-f250f4d6db/node_modules/@parcel/core/lib/requests/PathRequest.js:92:16)
      at async RequestTracker.runRequest 
  (/src/jenkins/plugins/cloudbees-console-log-viewer/node_modules/.store/@parcel-core-npm-2.10.3-f250f4d6db/node_modules/@parcel/core/lib/RequestTracker.js:634:20)
      at async AssetGraphBuilder.runPathRequest 
  (/src/jenkins/plugins/cloudbees-console-log-viewer/node_modules/.store/@parcel-core-npm-2.10.3-f250f4d6db/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:339:18)
      at async $31bd78e367586e0a$export$2e2bcd8739ae039._runFn 
  (/src/jenkins/plugins/cloudbees-console-log-viewer/node_modules/.store/@parcel-utils-npm-2.10.3-d9e6599ea3/node_modules/@parcel/utils/lib/index.js:34294:13)
      at async $31bd78e367586e0a$export$2e2bcd8739ae039._next 
  (/src/jenkins/plugins/cloudbees-console-log-viewer/node_modules/.store/@parcel-utils-npm-2.10.3-d9e6599ea3/node_modules/@parcel/utils/lib/index.js:34287:9)

```
https://betterprogramming.pub/the-native-way-to-configure-path-aliases-in-frontend-projects-5db70f19a6e0 I tried as well adding it to the imports but that did not work neither.

```
  "alias": {
    "buffer": false,
    "#index": "./src/main/ts/index.ts"
  },
  "imports": {
    "#index": "./src/main/ts/index.ts"
  },
```

**Comment by mischnic** [comment]
You need to enable package exports/imports: https://parceljs.org/features/dependency-resolution/#enabling-package-exports

Then putting `#index` in `imports` works
