### ISSUE TITLE
"@parcel/transformer-css: Invalid @ rule body" with @property rule

### ISSUE THREAD

**Issue by foxbunny** [parcel-bundler/parcel#9084]
# 🐛 bug report

Using the [`@property` rule](https://developer.mozilla.org/en-US/docs/Web/CSS/@property) triggers the "Invalid @ rule body".

The CSS looks like this:

```css
@property --primary {
	syntax: "<color>";
}
```

## 🎛 Configuration (.babelrc, package.json, cli command)

No configuration. The dependency versions are as follows:

```
    "@parcel/transformer-sass": "^2.9.1",
    "parcel": "^2.9.1",
    "parcel-plugin-nuke-dist": "^1.0.1"
```

## 🤔 Expected Behavior

There should be no error.

## 😯 Current Behavior

The error message appears:

```
🚨 @parcel/transformer-css: Invalid @ rule body
[/path/to/sorce]
  30 |   syntax: "<color>";
> 31 | }
```

Also note that the output points at the closing curly of the at rule, which may be a separate bug.

## 💁 Possible Solution

Add `@property` to supported at rules.

## 🔦 Context

I'm adding the `@property` rule so that some variables can transition smoothly on supported browsers.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.1
| Node             | 20.1.0
| npm/Yarn         | 9.6.4
| Operating System | Win 10

**Comment by foxbunny** [comment]
Also, I would appreciate a suggestion for a workaround if possible.

**Comment by mischnic** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@property says
> `@property` rules require a [`syntax`](https://developer.mozilla.org/en-US/docs/Web/CSS/@property/syntax) and [`inherits`](https://developer.mozilla.org/en-US/docs/Web/CSS/@property/inherits) descriptor; if either are missing, the entire rule is invalid and must be ignored. The [`initial-value`](https://developer.mozilla.org/en-US/docs/Web/CSS/@property/initial-value) descriptor is optional only if the syntax is the [universal syntax definition](https://drafts.css-houdini.org/css-properties-values-api/#universal-syntax-definition), otherwise the descriptor is required; if it's missing, the entire rule is invalid and must be ignored.

When specifying all of them, [it should work](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22nesting%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%40property%20--property-name%20%7B%5Cn%20%20syntax%3A%20%5C%22%3Ccolor%3E%5C%22%3B%5Cn%20%20inherits%3A%20false%3B%5Cn%20%20initial-value%3A%20%23c0ffee%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)
