### ISSUE TITLE
Unstable breaking builds

### ISSUE THREAD

**Issue by elmar-hinz** [parcel-bundler/parcel#9086]
# 🐛 bug report

The build result sometimes works and sometimes breaks.

![Screenshot 2023-06-11 at 11 32 15](https://github.com/parcel-bundler/parcel/assets/1227339/900a1a9a-09ae-49b6-bc09-cf76e1964d7e)

When it breaks it reports, that the function `select` select is undefined, which get's imported from node module `d3`.

I apologise if similar bugs have already been reported. Such instabilities are quite unspecific by nature, so that specific search terms are missing.

## 🎛 Configuration (.babelrc, package.json, cli command)

It's the configuration of this commit: https://github.com/home-assistant-tutorials/20.mermaid-card/commit/02e83b52475545bc7f663bde3142c52479ef8383

```json
{
  "source": "src/index.js",
  "module": "dist/card.js",
  "targets": {
    "module": {
      "includeNodeModules": true
    }
  },
  "scripts": {
    "watch": "parcel watch",
    "build": "parcel build"
  },
  "devDependencies": {
    "parcel": "^2.8.3"
  },
  "dependencies": {
    "lit": "^2.7.4",
    "mermaid": "^10.2.3"
  }
}

```

## 🤔 Expected Behavior

![Screenshot 2023-06-11 at 11 47 23](https://github.com/parcel-bundler/parcel/assets/1227339/fbb556d1-7d66-475b-b1cf-7a2c0de303e4)

## 😯 Broken Behavior

![Screenshot 2023-06-11 at 11 45 49](https://github.com/parcel-bundler/parcel/assets/1227339/8944ada7-9f37-4bee-b591-379322fc44de)

In the moment the behaviour does not happen as I want to copy the stack trace.

## 💁 Possible Solution

Sometimes it helps, to just run `npm run build` again. Sometimes it helps to delete `.parcel-cache/` and `dist/` before.

## 🔦 Context

I am running the code inside a docker container on a recent Mac. The directory is mounted. There could be writing instabilities during generation, although I don't observe complaints of a missing file.

The code is called inside a `Lit` based HTML custom element so inside a shadow DOM as well.

## 🌍 Your Environment

See repository. Mac Mini 2023. Docker desktop 4.19.0.

**Comment by mellodev** [comment]
I am experiencing a similar problem with Parcel 2.9.2+. The minified build/dist output differs from that served through the dev server. The dist output is missing a symbol for react-router which breaks the entire app. Meanwhile everything works properly while serving with the dev server.

Our app builds correctly with 2.8.1, so I assume this bug was introduced in 2.9.x!

**Comment by mischnic** [comment]
Please provide a [small code sample that reproduces the issue](https://minimum-reproduction.wtf/).
