### ISSUE TITLE
Live server stops working after several reloads

### ISSUE THREAD

**Issue by vlad-tymoshchyk** [parcel-bundler/parcel#9087]
# 🐛 bug report
I run `npx parcel src/test.html --no-cache`. After I modify `test.html` a few times, the automatic reloading stops woking. When I update the page in the browser it doesn't help. The only way is to restart parcel.

## 🤔 Expected Behavior
Automatic change detection, rebuild and reload should work

## 😯 Current Behavior
The web page stops reloading and new changes are not pulled in by the browser.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.1
| Node             | 16.19
| npm         | 8.19
| Operating System | Ubuntu 20

https://github.com/parcel-bundler/parcel/assets/25420932/4bdf6cde-dcae-41ac-b0f7-1309da155d0d

**Comment by samvv** [comment]
I believe I have the same problem, and I don't really understand why it is happening. When I write `index.ts` using Neovim, the Parcel console shows a different number, so I'm assuming it did receive the change to my file. In the browser, however, nothing happens, not even in the console.

This happens in different projects with different (recent) versions of NodeJS and on Ubuntu 23.04.
