### ISSUE TITLE
[WebExtension] Add support for transformation of `options_page` key.

### ISSUE THREAD

**Issue by nullishamy** [parcel-bundler/parcel#9090]
# 🙋 Feature request

It would be nice if parcel automatically captured, bundled, and rewrote the `options_page` key of the manifest file.

## 🤔 Expected Behavior

Parcel should transform the options page

## 😯 Current Behavior

Parcel ignores the options page

## 💁 Possible Solution

Should be similar to the implementation of 
```json
"action": {
	"default_popup": "...." 
}
```

## 🔦 Context

Currently making a template, based on parcel, for web extensions. I noticed the options page is not transformed, so cannot use
any of the parcel integrations I have configured (tailwind, etc).

**Comment by 101arrowz** [comment]
`options_page` is deprecated and will not work in Firefox. As all browsers support `options_ui.page` we opted not to allow the `options_page` key. See [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/options_page) for more details.

**Comment by nullishamy** [comment]
Oh, right, thanks for letting me know! I never checked the MDN page for `options_page` lol. Everything works now, closing.
