### ISSUE TITLE
Hash value of image file changes from time to time

### ISSUE THREAD

**Issue by lazex** [parcel-bundler/parcel#9091]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

- default setting
- disable cache
- production build

## 🤔 Expected Behavior

The same file should always have the same hash value.

## 😯 Current Behavior

Hash values change from time to time.

## 💁 Possible Solution

As far as I can see, there are two hash value patterns, and they switch from time to time.

There are files that occur frequently and those that do not occur at all.

They look the same, but the file sizes are different.
I think that the hash value is different because the binary file of the image file after optimization does not match.

## 💻 Code Sample

```css
.foo {
  background-image: url(/img/01.png);
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.2
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
Please share a complete reproduction. This must somehow be related to your specific image (and maybe even OS)

**Comment by lazex** [comment]
I am using windows 10.
I've attached a package to reproduce.
The build is repeated 100 times using `build-repeat.ps1`. Its log is `build-log.txt`.
Notice lines 164, 798, 1533.
The hash value and byte size are different from the previous and following builds.

[pkg.zip](https://github.com/parcel-bundler/parcel/files/11737895/pkg.zip)
