### ISSUE TITLE
`<script>` insertion broken on HTML pages with `<base>` tags

### ISSUE THREAD

**Issue by jtojnar** [parcel-bundler/parcel#9092]
# 🐛 bug report

After update to Parcel 2.9, scripts can no longer be loaded because the `<script>` tags are inserted before the `<base>` tag.
As a result, the scripts will be loaded relative to the current directory in the URL, where they might not exist.

Additionally, it makes the HTML invalid, see the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base):

> **Warning** If \[`href` attribute is specified\], this element must come before other elements with attribute values of URLs, such as [`<link>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link)'s `href` attribute.

## 🎛 Configuration (.babelrc, package.json, cli command)

```
parcel build index.html opml.html --dist-dir ../public/ --public-url ./
```

## 🤔 Expected Behavior

Scripts should not be inserted before `<base>` tag.

## 😯 Current Behavior

Scripts are inserted at the beginning of `<head>` no matter the other content:

```html
<!doctype html><html><head><script nomodule defer src="index.52e81471.js"></script><script type="module" src="index.c5da8bed.js"></script><meta charset="utf-8"><title>selfoss</title><base href="@basePath@">…
```

## 💁 Possible Solution

- The script tags could be inserted after `<base>` tag, if present.
- Or `<base>` tag could be moved at the beginning of `<head>`.

## 🔦 Context

We have a single-page application that supports being installed into web root subdirectory just by copying it there. The app uses URI path for routing so it is not possible to determine the web root in JavaScript.

To make this work, we put [`<base>` attribute with a placeholder](https://github.com/fossar/selfoss/blob/2a89be58b5f3f5517db61c275112577d1b3fc710/client/index.html#L9) value into Parcel’s HTML entry point and then replace the placeholder on the server side, when serving it.

It stopped working after I updated Parcel from 2.8.3 to 2.9.2.

## 💻 Code Sample

https://github.com/jtojnar/repro/tree/0377c9acd25e089c3adc118b5e20be804fd4cc51/parcel-9092

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.9.2
| Node             |v19.5.0
| npm         |9.3.1
| Operating System |NixOS

**Comment by jtojnar** [comment]
I bisected it by running `git bisect start v2.9.2 v2.8.3` in the local checkout in the parcel repo, saving the following code as an executable `bisect.sh` script, and then executing `git bisect run ./bisect.sh`:

<details>
<summary><code>bisect.sh</code> script</summary>

```shell
#!/usr/bin/env nix-shell
#!nix-shell -I nixpkgs=channel:nixos-unstable -i bash -p nodejs_latest -p yarn -p rustc -p cargo -p jq

set -o errexit

# Build Parcel
yarn install
# We have already obtained Rust with nix-shell, let’s set the target so that napi-rs does not try to fetch Rust using rustup.
export RUST_TARGET="$(env RUSTC_BOOTSTRAP=1 rustc -Z unstable-options --print target-spec-json | jq '."llvm-target"' --raw-output)"
yarn build-native

# Build project
pushd ~/Projects/repro/parcel-9092
# Remove parcel dependency to ensure parcel is picked up from our PATH.
rm -rf .parcel-cache dist
npm remove --save-dev parcel || true
PATH="$HOME/Projects/parcel/node_modules/.bin:$PATH" npm run build
popd

# Restore the lockfile so that bisection can continue.
git reset --hard HEAD

# Detect the issue
! grep 'head><script' ~/Projects/repro/parcel-9092/dist/index.html
```

</details>

That resulted in “https://github.com/parcel-bundler/parcel/commit/359f6bbba0739c3872ee82ea4984c93adaf4da47 is the first bad commit”:

```
commit 359f6bbba0739c3872ee82ea4984c93adaf4da47
Author: mattcompiles <mattjones701@gmail.com>
Date:   Wed Feb 22 13:20:20 2023 +1100

    Split large runtime manifest into separate bundles (#8837)

 packages/core/core/src/BundleGraph.js              | 97 +++++++++++++++++++++-
 packages/core/core/src/applyRuntimes.js            | 46 +++++++++-
 .../core/core/src/requests/BundleGraphRequest.js   | 50 ++++++-----
 packages/core/integration-tests/test/bundler.js    | 61 ++++++++++++++
 .../integration/html-js-shared-head/package.json   |  5 ++
 .../test/integration/html-js-shared-head/yarn.lock |  0
 .../test/integration/html-js-shared/package.json   |  5 ++
 .../test/integration/html-js-shared/yarn.lock      |  0
 .../test/integration/split-manifest-bundle/a.js    |  1 +
 .../test/integration/split-manifest-bundle/b.js    |  1 +
 .../integration/split-manifest-bundle/index.html   |  9 ++
 .../integration/split-manifest-bundle/index.js     |  4 +
 .../integration/split-manifest-bundle/package.json |  6 ++
 .../integration/split-manifest-bundle/yarn.lock    |  0
 packages/core/integration-tests/test/javascript.js |  6 +-
 packages/core/types/index.js                       |  3 +
 packages/runtimes/js/package.json                  |  1 +
 packages/runtimes/js/src/JSRuntime.js              | 76 ++++++++++++++++-
 18 files changed, 341 insertions(+), 30 deletions(-)
 create mode 100644 packages/core/integration-tests/test/integration/html-js-shared-head/package.json
 create mode 100644 packages/core/integration-tests/test/integration/html-js-shared-head/yarn.lock
 create mode 100644 packages/core/integration-tests/test/integration/html-js-shared/package.json
 create mode 100644 packages/core/integration-tests/test/integration/html-js-shared/yarn.lock
 create mode 100644 packages/core/integration-tests/test/integration/split-manifest-bundle/a.js
 create mode 100644 packages/core/integration-tests/test/integration/split-manifest-bundle/b.js
 create mode 100644 packages/core/integration-tests/test/integration/split-manifest-bundle/index.html
 create mode 100644 packages/core/integration-tests/test/integration/split-manifest-bundle/index.js
 create mode 100644 packages/core/integration-tests/test/integration/split-manifest-bundle/package.json
 create mode 100644 packages/core/integration-tests/test/integration/split-manifest-bundle/yarn.lock
```

**Comment by Hades32** [comment]
Did you find a workaround against this aggressive reordering? This also breaks manually inserted <script> tags that point to CDNs and have to load before anything else

**Comment by mischnic** [comment]
This logic here should find the correct position to insert these script tags (after any meta/base tags): https://github.com/parcel-bundler/parcel/blob/5ac45672bb603841bf294c66019930be4354625a/packages/packagers/html/src/HTMLPackager.js#L216-L259

So somehow that's not working in your case.

**Comment by jtojnar** [comment]
Still an issue in 2.12. I have this on my todo list.
