### ISSUE TITLE
Modules not loading in dev server

### ISSUE THREAD

**Issue by w-mcilhagga** [parcel-bundler/parcel#9098]
# 🐛 bug report

After bundling a web app & opening the app using the dev server, receive an error

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

This occurs at a point where a webworker module would be loaded and run using the code

new Worker(workerURL, {type:'module'})

## 🎛 Configuration (.babelrc, package.json, cli command)

no babel, no config at all, 
just did npx parcel index.html

nb index not in a src/ folder

no js config

## 🤔 Expected Behavior

It should have loaded the worker with the correct mime type

## 😯 Current Behavior

I get this error

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

## 💁 Possible Solution

no idea. Works fine without bundling (but then that's a different server)

## 🔦 Context

I'm trying to run a bundled web app and I can't

## 💻 Code Sample

not relevant? 

## 🌍 Your Environment

These aren't relevant, it bundles fine. It's the dev server that fails

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | downloaded today 17/06/23
| Node             | 16.15.1
| npm/Yarn         |  8.11.0
| Operating System | Win 10

**Comment by w-mcilhagga** [comment]
sorry, forgot to say the error appears in a dev console in the browser when attempting to use the app

**Comment by mischnic** [comment]
Using `new Worker` with just any variable as the script path doesn't work. Here's what you need to do: https://parceljs.org/languages/javascript/#web-workers

It says that the MIME type is wrong because instead of 404s, the Parcel dev server returns the index HTML file.
