### ISSUE TITLE
Problem: Cannot find entry point xxx

### ISSUE THREAD

**Issue by ogomez92** [parcel-bundler/parcel#910]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
Bug

### 🎛 Configuration (.babelrc, package.json, cli command)
cli command

```js
{
  "your": { "config": "here" } I didn't change anything
}
```

### 🤔 Expected Behavior
It should find the file in the location provided.

### 😯 Current Behavior
C:\sys\beatjs>parcel build client/main.js
×  Cannot find module 'C:\sys\beatjs\client\main.js' from '.'
    at C:\Users\ogomez\AppData\Roaming\npm\node_modules\parcel-bundler\node_modu
les\browser-resolve\node_modules\resolve\lib\async.js:55:21
    at load (C:\Users\ogomez\AppData\Roaming\npm\node_modules\parcel-bundler\nod
e_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\ogomez\AppData\Roaming\npm\node_modules\parcel-bundler\nod
e_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\ogomez\AppData\Roaming\npm\node_modules\parcel-bundler\node_modu
les\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)

C:\sys\beatjs>

### 💁 Possible Solution
My build script in package.json looks like this
"build": "parcel build client/main.js -d client/bundle.js --target=electron",

Reason is that it's not finding client/main.js.
It is there.
Itried going into the client folder and typing parcel build main.js --target=electron and nothing.
It doesn't work without the --target=electron either.

### 🔦 Context
It does not build.
It affects the entire process.

### 💻 Code Sample
"build": "parcel build client/main.js -d client/bundle.js --target=electron",

### 🌍 Your Environment
Windows 7 (for now), npm and npm installed parcel 1.6.2, electron.

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by DeMoorJasper** [comment]
Could u share a test repo as this error is not reproducible without it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ogomez92** [comment]
Maybe it is a windows thing, I will try on a different system and let
you know. I cannot currently share a test repo as I only installed it
on my game.
If you want to, you can grab that, as it is public.
Just git pull, npm install and npm run build.

http://oriolgomez.com:9900/ogomez92/beatjs

**Comment by ogomez92** [comment]
It was my damn fault sorry.

**Comment by vishwajeetraj11** [comment]
Can you please tell me. how did you fix it. Maybe I made the same mistake.

**Comment by houssemFat-DDF** [comment]
Getting the same error, it removes all slashes under a window machine with command `parcel .`

**Comment by JosephFinny** [comment]
> Can you please tell me. how did you fix it. Maybe I made the same mistake.

I just moved all the src file contents outside and it works
