### ISSUE TITLE
@parcel/transformer-css: Could not resolve module 

### ISSUE THREAD

**Issue by ifg-sam** [parcel-bundler/parcel#9100]
# 🐛 bug report

I'm encountering the below error when trying to build my site on Cloudflare Pages.

The build succeeds locally on my macbook pro, but fails in my build pipeline.

Some cursory googling suggests that I can perhaps fix this by upgrading parcel, but I am on latest parcel 2.9.2

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
    "extends": [
        "@parcel/config-default"
    ],
    "reporters": [
        "...",
        "parcel-reporter-static-files-copy"
    ]
}

```

## 🤔 Expected Behavior

The build should succeed

## 😯 Current Behavior

The build fails with the following error:

<pre class="c_hv c_bv c_gv c_gw c_nf c_ng c_df c_nu c_nv c_nw c_nx c_fb c_fc c_nh c_bx c_ny">
2:15:29.063 | Building...
22:15:29.422 | 🚨 Build failed.
22:15:29.424 |  
22:15:29.425 | @parcel/transformer-css: Could not resolve module
22:15:29.425 | "../lightningcss.linux-x64-gnu.node" from
22:15:29.425 | "/opt/buildhome/repo/node_modules/lightningcss/node/index.js"
22:15:29.426 |  
22:15:29.427 | Error: Could not resolve module "../lightningcss.linux-x64-gnu.node" from
22:15:29.427 | "/opt/buildhome/repo/node_modules/lightningcss/node/index.js"
22:15:29.427 | at NodePackageManager.resolveInternal
22:15:29.427 | (/opt/buildhome/repo/node_modules/@parcel/package-manager/lib/index.js:3672:21)
22:15:29.427 | at NodePackageManager.resolveSync
22:15:29.428 | (/opt/buildhome/repo/node_modules/@parcel/package-manager/lib/index.js:3567:29)
22:15:29.428 | at NodePackageManager.requireSync
22:15:29.428 | (/opt/buildhome/repo/node_modules/@parcel/package-manager/lib/index.js:3394:34)
22:15:29.428 | at m.require
22:15:29.428 | (/opt/buildhome/repo/node_modules/@parcel/package-manager/lib/index.js:3410:25)
22:15:29.428 | at require (node:internal/modules/helpers:119:18)
22:15:29.429 | at Object.<anonymous>
22:15:29.429 | (/opt/buildhome/repo/node_modules/lightningcss/node/index.js:21:22)
22:15:29.429 | at Module._compile (node:internal/modules/cjs/loader:1275:14)
22:15:29.429 | at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
22:15:29.430 | at Module.load (node:internal/modules/cjs/loader:1133:32)
22:15:29.430 | at NodePackageManager.load
22:15:29.430 | (/opt/buildhome/repo/node_modules/@parcel/package-manager/lib/index.js:3423:15)
22:15:29.430 |  
22:15:31.364 | Failed: build command exited with code: 1
22:15:34.816 | Failed: error occurred while running build command
</pre>

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.2
| Node             | 19.8.1
| npm/Yarn         | 9.5.1
| Operating System | 

Here are my package.json dependencies:

```json
    "dependencies": {
        "@parcel/css": "^1.14.0",
        "@parcel/reporter-bundle-analyzer": "^2.9.2",
        "@parcel/transformer-css": "^2.9.2",
        "@parcel/transformer-less": "^2.9.2",
        "parcel": "^2.9.2",
        "parcel-reporter-static-files-copy": "^1.5.0",
    }
```

**Comment by nitelite** [comment]
Same error for me building with Github Actions, also with Parcel 2.9.2. 
As far as I can tell from my CI logs, the same package.json seems to have built without errors 3 days ago.

```
@parcel/transformer-css: Could not resolve module 
"../lightningcss.linux-x64-gnu.node" from 
"/github/workspace/node_modules/lightningcss/node/index.js"

  Error: Could not resolve module "../lightningcss.linux-x64-gnu.node" from 
  "/github/workspace/node_modules/lightningcss/node/index.js"
      at NodePackageManager.resolveInternal 
  (/github/workspace/node_modules/@parcel/package-manager/lib/index.js:3672:21)
      at NodePackageManager.resolveSync 
  (/github/workspace/node_modules/@parcel/package-manager/lib/index.js:3567:29)
      at NodePackageManager.requireSync 
  (/github/workspace/node_modules/@parcel/package-manager/lib/index.js:3394:34)
      at m.require 
  (/github/workspace/node_modules/@parcel/package-manager/lib/index.js:3410:25)
      at require (node:internal/modules/cjs/helpers:110:18)
      at Object.<anonymous> 
  (/github/workspace/node_modules/lightningcss/node/index.js:21:22)
      at Module._compile (node:internal/modules/cjs/loader:1254:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
      at Module.load (node:internal/modules/cjs/loader:1117:32)
      at NodePackageManager.load 
  (/github/workspace/node_modules/@parcel/package-manager/lib/index.js:3423:15)
```

**Comment by devongovett** [comment]
This indicates that your package manager (eg npm) is not installing the `lightningcss-linux-x64-gnu` dependency correctly.

**Comment by ifg-sam** [comment]
> This indicates that your package manager (eg npm) is not installing the `lightningcss-linux-x64-gnu` dependency correctly.

It is a transitive dependency of `@parcel/transformer-css`/`@parcel/css` - I don't think @nitelite or I are explicitly requiring `lightningcss-linux-x64-gnu` and neither of our package.json's have changed 🤔

**Comment by nitelite** [comment]
When executing `npm list -a` from my build environment, it seems like non of the os-specific dependencies under lightningcss gets installed. I created an issue in the repo, in case the appriate people are more likely to see it there.

From my build dev:
```
├─┬ @parcel/css@1.14.0
│ └─┬ lightningcss@1.19.0
│   ├── detect-libc@1.0.3
│   ├── UNMET OPTIONAL DEPENDENCY lightningcss-darwin-arm64@1.19.0
│   ├── UNMET OPTIONAL DEPENDENCY lightningcss-darwin-x64@1.19.0
│   ├── UNMET OPTIONAL DEPENDENCY lightningcss-linux-arm-gnueabihf@1.19.0
│   ├── UNMET OPTIONAL DEPENDENCY lightningcss-linux-arm64-gnu@1.19.0
│   ├── UNMET OPTIONAL DEPENDENCY lightningcss-linux-arm64-musl@1.19.0
│   ├── UNMET OPTIONAL DEPENDENCY lightningcss-linux-x64-gnu@1.19.0
│   ├── UNMET OPTIONAL DEPENDENCY lightningcss-linux-x64-musl@1.19.0
│   └── UNMET OPTIONAL DEPENDENCY lightningcss-win32-x64-msvc@1.19.0
```

**Comment by devongovett** [comment]
This is strange because `@parcel/css` is not a dependency of Parcel. That package was replaced with `lightningcss` 9 months ago. It should be a direct dependency of `@parcel/transformer-css` in the latest version. The current version of `lightningcss` is also 1.21.0, not 1.19.0. Are you sure you don't just have an outdated lock file?

**Comment by nitelite** [comment]
> This is strange because `@parcel/css` is not a dependency of Parcel.

I wasn't even aware. I went back to look at my git history for package.json, and it looks like I added @parcel/css as a devDependency when I upgraded Parcel from 2.7.0 to 2.8.3 back in Feb 2023. Unfortunately, I also upgrade quite a few other package at the same time, so not 100% what made me include the @parcel/css dep.

I am running the following devDependencies at the moment, are there any other parcel deps that I have include that is not actually neccesary to include directly like this? Maybe I just need to fix my deps.

```
....
"devDependencies": {
    "@ianvs/prettier-plugin-sort-imports": "4.0.2",
    "@parcel/config-default": "2.9.2",
    "@parcel/css": "1.14.0",
    "@parcel/reporter-bundle-analyzer": "2.9.2",
    "@parcel/reporter-bundle-buddy": "2.9.2",
    "@parcel/transformer-pug": "2.9.2",
    "@parcel/transformer-sass": "2.9.2",
    "@types/lodash-es": "4.17.7",
    "autoprefixer": "10.4.14",
    "ava": "5.3.0",
    "classnames": "2.3.2",
    "cross-env": "7.0.3",
    "dotenv": "16.1.4",
    "http-proxy-middleware": "2.0.6",
    "node-fetch": "3.3.1",
    "parcel": "2.9.2",
    "parcel-reporter-static-files-copy": "1.5.0",
    "postcss": "8.4.24",
    "prettier": "2.8.8",
    "process": "0.11.10",
    "rimraf": "3.0.2",
    "sharp": "0.31.1",
    "typescript": "5.1.3"
  },
...
```

**Comment by nitelite** [comment]
I removed `postcss` and `@parcel/css` from my package.json, but this did not resolve the issue since `@parcel/config-default` still added v1.19.0 of lightningcss as a transitive dependency. 

I was able to resolve the issue though, by adding `lightningcss@1.21.0` directly to my package.json so that v1.19.0 was no longer used "indirectly". Not sure if @ifg-sam has the same transitive dependency pulling in v1.19.0, but the error seems to be limited to that version, at least for me.

**Comment by devongovett** [comment]
It is a caret range so with a fresh install npm should pull in the latest. You probably had an outdated lockfile entry for it that prevented the newer version from being installed.

**Comment by nitelite** [comment]
Thanks, I will give it a try in my test-branch and see removing my lock file and reinstalling dependencies also gives me a newer lightningcss 👍

**Comment by nitelite** [comment]
I can confirm that removing my package-lock.json and reinstalling all dependencies allowed it to pull down v1.21.0 which does not have this problem. Not sure why v1.19.0 has suddenly stopped working though.

**Comment by hrynevychroman** [comment]
Maybe someone can help me with my sourcefile bug, i'm so confused that no one can help and give me some response - https://github.com/parcel-bundler/parcel/issues/9099

**Comment by michael-lynch** [comment]
My team came across this same issue. We are building a React component library and it seemed to appear after we upgraded to React 18, though I don't know if that has anything to do with it. In our case, we are using...

```
"devDependencies": {
  "@parcel/packager-ts": "2.8.0",
  "@parcel/transformer-sass": "2.8.0",
  "@parcel/transformer-typescript-types": "2.8.0",
  "parcel": "2.8.0",
}
```

One of these dependencies installed `lightningcss@1.16.1`, which failed to resolve `lightningcss.darwin-x64-gnu.node` locally and `lightningcss.linux-x64-gnu.node` in our pipeline.

Installing `lightningcss@1.21.0` explicitly fixed the issue.

**Comment by eldang** [comment]
I am running into the same issue today with Parcel 2.9.3, and forcing lightningcss to either 1.21.0 or 1.21.5 doesn't resolve it.  Curiously, I can build the project just fine on my Mac; it's only Github's automation (running an Ubuntu 22.04.3 VM) where it fails.  Here's the relevant subset of `npm list -a` output on my own machine:

```
│ │ ├─┬ @parcel/optimizer-css@2.9.3
...
│ │ │ ├─┬ lightningcss@1.21.5
│ │ │ │ ├── detect-libc@1.0.3 deduped
│ │ │ │ ├── UNMET OPTIONAL DEPENDENCY lightningcss-darwin-arm64@1.21.5
│ │ │ │ ├── lightningcss-darwin-x64@1.21.5
│ │ │ │ ├── UNMET OPTIONAL DEPENDENCY lightningcss-linux-arm-gnueabihf@1.21.5
│ │ │ │ ├── UNMET OPTIONAL DEPENDENCY lightningcss-linux-arm64-gnu@1.21.5
│ │ │ │ ├── UNMET OPTIONAL DEPENDENCY lightningcss-linux-arm64-musl@1.21.5
│ │ │ │ ├── UNMET OPTIONAL DEPENDENCY lightningcss-linux-x64-gnu@1.21.5
│ │ │ │ ├── UNMET OPTIONAL DEPENDENCY lightningcss-linux-x64-musl@1.21.5
│ │ │ │ └── UNMET OPTIONAL DEPENDENCY lightningcss-win32-x64-msvc@1.21.5
```

As far as I can tell, all the "unmet optional dependency" warnings are simply because it's appropriately only installed the right build for this environment.

I have tried blowing away `package-lock.json` and reinstalling, and I've tried Node versions 16 and 20 in the Github action, all to no avail.  I'm not blocked because I can build on my own machine, but may have to temporarily work around the issue by removing one of the code checks in Github.

**Comment by Eric-Arellano** [comment]
See https://github.com/parcel-bundler/lightningcss/issues/567#issuecomment-1685295558. That suggestion worked for me with GitHub Actions 🙌

**Comment by lorenzogrv** [comment]
Today I rant into this issue with `lightningcss-linux-arm64-musl`, within a multi-platform buildx build which uses remote builders.

The solution was regenerating the lockfile, but care: **If you don't remove `node_modules` it won't work**check

```bash
rm -rf node_modules package-lock.json
npm install
git diff package-lock.json  # be sure to overview the changes
```

Side node: this may upgrade other dependencies, depending on your pinnings
