### ISSUE TITLE
Minifier seems unable to remove some dead code

### ISSUE THREAD

**Issue by nattthebear** [parcel-bundler/parcel#9111]
# 🐛 bug report

In a specific instance, the minifier is unable to remove code that is dead.

## 🎛 Configuration (.babelrc, package.json, cli command)

`package.json` excerpt:

```json
{
  "scripts": {
    "build": "rimraf build && parcel build ./src/index.html --dist-dir ./build"
  },
  "targets": {},
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel": "^2.9.2"
  }
}
```

## 🤔 Expected Behavior

The final generated `.js` file should be entirely empty.

## 😯 Current Behavior

All code is preserved in the final generated `.js` file:

```javascript
const t=Symbol("symbol called");function s(s){return s===t}class c{static #t=(()=>{this.staticProp=s})()}
//# sourceMappingURL=index.8def1b4a.js.map
```

## 💁 Possible Solution

I'm not sure.  The circumstances to get this dead code to fail to eliminate seemed to be very specific.  Hopefully this minimal example will assist in fixing it.

## 🔦 Context

The example was created as a minimum reproduction by paring down a library I was working on.  In that library, I was expecting a particular feature not to be included in the build if the user didn't import it themselves, but somehow it was still being included.

## 💻 Code Sample

The code in question is a single typescript file:

```typescript
const S = /*#__PURE__*/ Symbol("symbol called");

function test(val) {
	return val === S;
}

class SomeClass {
	static staticProp = test;
}
```

The environment (including one other dummy js file, an html file, and the full settings of the minifier) may also be relevant in triggering the issue.  The full example is available here:  https://github.com/nattthebear/parcel-minifier-example/commit/ddc22d990d72532d87e0bdb8188a6eb494d5497c

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.2 |
| Node             | 18.12.1 |
| npm/Yarn         | npm 8.19.2 |
| Operating System | Windows 10 |

**Comment by danieltroger** [comment]
For me pure annotations also aren't respected at all, on 2.9.2. I think it's probably the same issue?

EDIT: Some are, but the one that aren't might be due to this issue?

**Comment by danieltroger** [comment]
Has this been fixed?
