### ISSUE TITLE
Parcel not inserting line breaks properly in generated javascript

### ISSUE THREAD

**Issue by lalunamel** [parcel-bundler/parcel#9118]
# 🐛 bug report

Thanks so much for all the work you do on Parcel - it's a lovely tool!

While noodling on a little project to explore how to render graphs in the browser, I ran across the most perplexing behavior. The code I was writing was clearly correct, but when it was executed, it failed in a way I would not expect! I tried changing lines, extracting statements into their own variables, and the error would change, again in some way I wouldn't expect.

Eventually I decided to look at the un-sourcemapped code and lo, the JS code generated by Parcel was not correct!

Specifically, Parcel was not maintaining a line break and was smooshing two separate lines together, causing all sorts of weird errors.

## 🎛 Configuration (.babelrc, package.json, cli command)

No custom configuration

`package.json`
```json
{
  "name": "renderer",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "parcel index.html"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "parcel": "^2.9.3",
    "process": "^0.11.10"
  },
  "dependencies": {
    "konva": "^9.2.0",
    "react": "^18.2.0",
    "react-konva": "^18.2.10"
  }
}
```

## 🤔 Expected Behavior

The line breaks in my source code should be maintained in the javascript generated by Parcel.

## 😯 Current Behavior

The line breaks in my source code are not maintained in the javascript generated by Parcel.

## 💻 Code Sample

[Here](https://github.com/lalunamel/graphRenderer) is the repo in which this error is occurring.
I made a [branch](https://github.com/lalunamel/graphRenderer/compare/bad-semicolon-insertion-with-parcel) and [commit](https://github.com/lalunamel/graphRenderer/commit/e2a661384d6285f193f502a4fbe45054f591aa08) to demonstrate the error.

If you'd like to see the code executed in the browser, simply `npm install`, `npm start`, open `localhost:1234`, and mouse over one of the green circles that is rendered.

### Bad

Here is the relevant source code that Parcel is acting on:

```javascript
const getAllConnectedNodeIds = (rootNodeId) => {
    const connectedNodeIds = new Set()
    const unvisited = [rootNodeId]
    while(unvisited.length !== 0) {
        const id = unvisited.pop()
        connectedNodeIds.add(id)
        (connections[id] || []).forEach((connectedId) => { 
            unvisited.push(connectedId) 
        })
    }

    return connectedNodeIds
}
```

Here is the code that Parcel generates, given the snippet above.
Note that the line `connectedNodeIds.add(id)` is smooshed together with `(connections[id] || []).forEach((connectedId) => {`
This code produces the error `Uncaught TypeError: connectedNodeIds.add(...) is not a function`
```javascript
const getAllConnectedNodeIds = (rootNodeId) => {
    const connectedNodeIds = new Set();
    const unvisited = [
        rootNodeId
    ];
    while (unvisited.length !== 0) {
        const id = unvisited.pop();
        connectedNodeIds.add(id)(connections[id] || []).forEach((connectedId) => {
            unvisited.push(connectedId);
        });
    }
    return connectedNodeIds;
};
```
### Good

If I amend the source snippet such that the line `connectedNodes.add(id)` has a semicolon after it:
```javascript
const getAllConnectedNodeIds = (rootNodeId) => {
    const connectedNodeIds = new Set()
    const unvisited = [rootNodeId]
    while(unvisited.length !== 0) {
        const id = unvisited.pop()
        connectedNodeIds.add(id);
        (connections[id] || []).forEach((connectedId) => { 
            unvisited.push(connectedId) 
        })
    }

    return connectedNodeIds
}
```

Here is the code that Parcel generates.
This code does not produce an error.
Note that the offending `connectedNodeIds.add(id)` is now on its own line.
```javascript
const getAllConnectedNodeIds = (rootNodeId) => {
    const connectedNodeIds = new Set();
    const unvisited = [
        rootNodeId
    ];
    while (unvisited.length !== 0) {
        const id = unvisited.pop();
        connectedNodeIds.add(id);
        (connections[id] || []).forEach((connectedId) => {
            unvisited.push(connectedId);
        });
    }
    return connectedNodeIds;
};
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.9.3
| Node             |  v17.8.0
| npm        | 8.5.5
| Operating System | 2020 Macbook Air - MacOS Ventura 13.4.1 (22F82)

**Comment by lalunamel** [comment]
Apologies that this isn't a nice, small, self contained repo with no dependencies.
If this issue does end up getting investigated, I'm happy to put in the work to extract this into a simpler example that's easier to work with.

**Comment by mischnic** [comment]
Either this is
- working as expected and the swc parser is following the JS standard'a rules for Automatic Semicolon Insertion
- or a bug in the swc parser.

I'm currently not at my computer, so please test that source code snippet in the browser without Parcel (e.g. pasting into devtools console). Otherwise/afterwards you can experiment with https://play.swc.rs and see how it interprets this code. If it's not doing what it should, there's a "report issue" button. Once this is fixed in swc we can upgrade swc in Parcel.

**Comment by lalunamel** [comment]
In the browser console:

```javascript
const connections = {
    "abc": ["def"]
}

const getAllConnectedNodeIds = (rootNodeId) => {
    const connectedNodeIds = new Set()
    const unvisited = [rootNodeId]
    while(unvisited.length !== 0) {
        const id = unvisited.pop()
        connectedNodeIds.add(id)
        (connections[id] || []).forEach((connectedId) => { 
            unvisited.push(connectedId) 
        })
    }

    return connectedNodeIds
}

getAllConnectedNodeIds("abc")
```

Produces:
```
VM350:11 Uncaught TypeError: connectedNodeIds.add(...) is not a function
    at getAllConnectedNodeIds (<anonymous>:11:9)
    at <anonymous>:19:1
```

---

WILD!
I've never actually seen automatic semicolon insertion act in a way that I did not expect.
Do you happen to know why it produces this behavior? 

I'll certainly do my own research, but I'm shocked that the snippet above produces the line `connectedNodeIds.add(id)(connections[id] || []).forEach((connectedId) => { `

**Comment by lalunamel** [comment]
I can't find the relevant section in the ECMAScript reference, but apparently it's valid to call a function and have whitespace between the function name and it's parens, like this: `foo       ("bar")`

There's even an eslint rule: https://eslint.org/docs/latest/rules/func-call-spacing

That's what's going on here. 🤯
