### ISSUE TITLE
Parcel doesn't copy unchanged files to `--dist-dir`

### ISSUE THREAD

**Issue by adrian5** [parcel-bundler/parcel#9132]
# 🐛 bug report

When using the `--dist-dir` flag, `parcel build` doesn't recreate the full bundle with each invocation.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
  "name": "mysite-com",
  "scripts": {
    "dev": "pnpm parcel src/index.html"
  },
  "devDependencies": {
    "@parcel/config-default": "^2.9.3",
    "parcel": "^2.9.3",
    "posthtml-include": "^1.7.4"
  },
  "@parcel/transformer-css": {
    "drafts": {
      "nesting": true
    }
  }
}
```

```
$ pnpm parcel build --dist-dir=/tmp/mysite-build src/index.html
```

## 🤔 Expected Behavior

Removing the dist dir and running the build again should re-create the bundled output.

```
$ rm -rf /tmp/mysite-build
$ pnpm parcel build --dist-dir=/tmp/mysite-build src/index.html
$ ls /tmp/mysite-build
> bundled output…
```

## 😯 Current Behavior

I find an empty directory, nothing is being copied from the cache. Only changed sources produce new files in the target directory.

```
$ rm -rf /tmp/mysite-build
$ pnpm parcel build --dist-dir=/tmp/mysite-build src/index.html
$ ls /tmp/mysite-build
> empty dir
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.3
| Node             | 20.4.0
| pnpm            | 8.6.7
| Operating System | Arch Linux

**Comment by adrian5** [comment]
Note: the same issue occurs when overriding the default target config:

```json
"targets": {
  "default": {
    "distDir": "/tmp/mysite-build"
  }
},
```

**Comment by tech-run** [comment]
Note: simliar issue also occuring where --dist-dir- is sometimes creating dist dir. 
```
$ rm -rf ./../build
$ parcel build index.html --dist-dir ./../build
ls ./../build
> empty
```



<html>
<body>


Software | Version(s)
-- | --
Parcel | 2.9.3
Node | 16.20.1
npm | 8.15.0 
Operating System | Arch Linux


</body>
</html>
