### ISSUE TITLE
Parcel HMR v2.9.3 not working

### ISSUE THREAD

**Issue by yashone7** [parcel-bundler/parcel#9144]
# 🐛 bug report

Parcel HMR bundles the code, but module not found error in the browser, this is occurring when we import a new file or a new module into our codebase.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
 "devDependencies": {
    "@parcel/packager-raw-url": "^2.9.3",
    "@parcel/resolver-glob": "^2.9.3",
    "@parcel/transformer-webmanifest": "^2.9.3",
    "@types/lodash": "^4.14.195",
    "@types/node": "^20.3.1",
    "@types/react": "^18.2.14",
    "@types/react-dom": "^18.2.6",
    "@typescript-eslint/eslint-plugin": "^5.60.0",
    "@typescript-eslint/parser": "^5.60.0",
    "autoprefixer": "^10.4.14",
    "buffer": "^6.0.3",
    "parcel": "^2.9.3",
    "postcss": "^8.4.26",
    "process": "^0.11.10",
    "tailwindcss": "^3.3.3"
```

## 🤔 Expected Behavior

HMR should work as expected when importing a new module

## 😯 Current Behavior

Upon importing a new module parcel is bundling the code, there are no errors in the cli, but when I open the browser I get no module found error, this is happening every time I import a new file or a new module in my codebase

Stacktrace
```
Error: Cannot find module 'bUkj4'
▼ 9 stack frames were expanded.
newRequire
http://localhost:1234/index.2d3ace14.js:61:19
newRequire
http://localhost:1234/index.2d3ace14.js:45:18
localRequire
http://localhost:1234/index.2d3ace14.js:84:35
aIcrQ../chunk-Z47J5YMH.mjs
node_modules/.pnpm/@chakra-ui+layout@2.1.19_@chakra-ui+system@2.5.7_react@18.2.0/node_modules/@chakra-ui/layout/dist/index.mjs:23
newRequire
http://localhost:1234/index.2d3ace14.js:71:24
localRequire
http://localhost:1234/index.2d3ace14.js:84:35
eSZll../chunk-DGNA6VRZ.mjs
node_modules/.pnpm/@chakra-ui+react@2.6.1_@emotion+react@11.11.0_@emotion+styled@11.11.0_@types+react@18.2.14_fr_iggde4axewbmvucqkk5aagow7q/node_modules/@chakra-ui/react/dist/index.mjs:25
newRequire
http://localhost:1234/index.2d3ace14.js:71:24
localRequire
http://localhost:1234/index.2d3ace14.js:84:35
▲ 9 stack frames were expanded.
7F5Te.react/jsx-dev-runtime
src/App.tsx:1
```

## 💁 Possible Solution

Solution, first close the parcel process, clear parcel cache, and then re-run parcel command, this time it bundles correctly.

## 🔦 Context

New module imports, new file imports are failing.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel               |  v2.9.3
| Node                | v18.6.0
| npm/Yarn         | pnpm 8.4.0
| Operating System | win 11

**Comment by mischnic** [comment]
There's not much we can do here without a full reproduction
