### ISSUE TITLE
🙋 feature request: html partials

### ISSUE THREAD

**Issue by mdings** [parcel-bundler/parcel#915]
When working on larger html-files it would be great if we can split them up into partials, maybe by using an include directive. How about something as following?

```html
<html>
<head>
...
</head>
<body>
  <div class="container">
    <!-- @include header.html -->
    <!-- @include about-us.html -->
    <!-- @include testimonials.html -->
  </div>
</body>
</html>
```

**Comment by davidnagli** [comment]
Wow this would actually be a really cool feature!!! 👍 😃 

Did you just make up the `@include` syntax, or is this an established convention from elsewhere? Is there already some existing web spec/api on how html includes should work?

I tried looking into `link rel=‘import’` (see: [Article](https://www.html5rocks.com/en/tutorials/webcomponents/imports/) and [Spec](http://w3c.github.io/webcomponents/spec/imports/)), but it seems pretty cumbersome to use, so I think what you’re proposing would actually be incredibly useful for people writing direct html without using view libraries like React/Angular.

We should also discuss if we want to add this to Parcel’s core, or if it would be better of separated into its own plugin.

**Comment by devongovett** [comment]
This could be done using [posthtml-include](https://github.com/posthtml/posthtml-include) I think. Just create a `.posthtmlrc` file like this one in the tests: https://github.com/parcel-bundler/parcel/blob/master/test/integration/posthtml/.posthtmlrc.js

**Comment by mdings** [comment]
> Did you just make up the @include syntax, or is this an established convention from elsewhere? Is there already some existing web spec/api on how html includes should work?

I think I've seen this before with [codekit](https://codekitapp.com/). Not sure if there is an existing spec for it. Anyway, I will try using posthtml-include for now and see how that works out.

**Comment by mdings** [comment]
This is not working. The <include> tag is just used as-in the generated output.

Input:
```html
<!doctype html>
<html>
<body>
    <include src="title.html"></include>
</body>
</html>
```

Output:
```html
<!doctype html>
<html>
<body>
    <include src="title.html"></include>
</body>
</html>
```

Expected output:
```html
<!doctype html>
<html>
<body>
    <h1>Hello world</h1>
</body>
</html>
```

**Comment by davidnagli** [comment]
You probably didn’t create a .posthtmlrc with posthtml-included as a plug-in.

**Comment by mdings** [comment]
Oh wait. I actually created `.posthtmlrc.js` but didn't export the config object..  Sorry, never mind. Works perfectly 👯

**Comment by wzrdtales** [comment]
@devongovett Is there any intention to support this in a sense of being actually usable? As @mdings mentioned, this way there is no auto reload. And even worse, in CI processes it will fail to recognize to build these, if you do not clear the cache.

**Comment by gitowiec** [comment]
For me it worked with `.posthtmlrc.js` as in tests. My parcel configuration is based on https://github.com/azu/parcel-typescript-example

**Comment by callumgare** [comment]
> This could be done using [posthtml-include](https://github.com/posthtml/posthtml-include) I think. Just create a `.posthtmlrc` file like this one in the tests: https://github.com/parcel-bundler/parcel/blob/master/test/integration/posthtml/.posthtmlrc.js

The new url for this is: https://github.com/parcel-bundler/parcel/blob/v2/packages/core/integration-tests/test/integration/posthtml/.posthtmlrc.js
