### ISSUE TITLE
@parcel/bundler-default Settings Not Working

### ISSUE THREAD

**Issue by mattsputnikdigital** [parcel-bundler/parcel#9155]
Im trying to get Parcel to just provide one .js and one .css file on build.

I have added the settings as per the docs to package.json but they do not seem to do anything.

```
"@parcel/bundler-default": {
    "minBundles": 1,
    "minBundleSize": 9999999999,
    "maxParallelRequests": 1
  }
```

**Comment by AGawrys** [comment]
These settings alter what we call "shared bundles" which are automatically split out files/code that can be "shared" between your other bundles. 
What those settings do not affect, are any entries to your project (So we will not combine `a.js` with `b.js` if you're doing something like `parcel build a.js b.js`  ) And then we also do not combine asynchronous assets, so if you've done something like `import('./c');` , c will not be removed. 
Let me know if this doesn't answer your question, Thanks!
