### ISSUE TITLE
Transpilation to media query range syntax without regarding browserslist

### ISSUE THREAD

**Issue by rienheuver** [parcel-bundler/parcel#9157]
# 🐛 bug report

`@media (min-width: 600px)` will get transpiled to `@media (width >= 600px)` by Parcel, even though the latter is much new syntax and not fully supported by all browsers. Safari 16.3 for example doesn't support it but still has pretty big usage.

## 🎛 Configuration

I have this in my package.json:

```json
"@parcel/transformer-css": {
    "drafts": {
      "nesting": true
    }
  }
```

but otherwise have nothing special.

## 🤔 Expected Behavior

It should not transpile at all. Why transpile this? The old syntax will be fine for years to come.

## 😯 Current Behavior

It gets transpiled and then causes bugs in browsers that don't support the new syntax.

## 💁 Possible Solution

Haven't found one yet, any suggestions are very much welcome because I don't feel like telling my customers to update their macbooks ;-) 

## 🔦 Context

I've build a page where I use this to have some responsiveness. Heard from a customer that it doesn't work correctly and checked with a colleague who also has a macbook. He had the same problem as well and we noticed he didn't have the last update of OSX yet. After updating this afternoon, it worked for him. So then I started digging and found this.

## 💻 Code Sample

```css
.modal {
  @media (min-width: 600px) {
    min-width: 450px;
  }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.3
| Node             |  18.5.0
| npm/Yarn         | 9.5.0
| Operating System | Ubuntu 22.04

**Comment by sebastianwinter** [comment]
I had the same problem. Changing the settings in my package.json prevented the transpilation of media queries:
– Adding 'browserlist'
– Updating the @parcel/transformer-sass
` 
"devDependencies": {
    "@parcel/transformer-sass": "^2.9.3",
    "parcel": "^2.9.3"
 },
 "browserslist": "> 0.5%, last 3 versions, not dead"
  `
  
When built, the CSS has the 'min-width' declarations again.

**Comment by mischnic** [comment]
Adding `browserslist` is the correct answer here, that will ensure that all output files (be it CSS or JS) are compatible with the browsers you want to target.

**Comment by rienheuver** [comment]
This doesn't work for me. I'm already on parcel 2.9.3 (and don't use sass). I've added the browserslist and rebuild everything, but it's still transpiling it.

**Comment by rienheuver** [comment]
Could you therefore please reopen the issue @mischnic ?

**Comment by devongovett** [comment]
If you mean in development, see https://github.com/parcel-bundler/parcel/issues/9139#issuecomment-1670489296

**Comment by rienheuver** [comment]
Ah right, thanks @devongovett that was indeed the problem. Got this sorted now, thanks all for your help!
