### ISSUE TITLE
Assume async js functions are supported if no browserslist is specified

### ISSUE THREAD

**Issue by KrakenZ** [parcel-bundler/parcel#916]
**Choose one:** 🙋 feature request

### 🤔 Expected Behavior

1. Create and use an async js function.
2. ```parcel build file.js```
3. Works as intended.

### 😯 Current Behavior

1. Create and use an async js function.
2. ```parcel build file.js```
3. Get ```ReferenceError: regeneratorRuntime is not defined```

### 💁 Possible Solution

If no browserslist is specified, assume async functions are supported if used.

### 🔦 Context

Until I searched the specified note on the parcel website, I didn't know I needed to import the babel-polyfill module and/or specify browserslist in package.json

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.6.2
| Node             |9.5.0
| Yarn         |1.5.1
| Operating System | win x64

**Comment by techieshark** [comment]
Or at least give a good terminal warning with a suggested fix, rather than having "regeneratorRuntime is not defined" shown in the browser console.

**Comment by helpermethod** [comment]
Yes please! Took me hours to figure out the problem! I'm currently writing a Chrome extension where I can expect users to use a new version with `async/await` support.

**Comment by DeMoorJasper** [comment]
Not sure if this should be fixed. As we currently set a default to browserlist that doesn't assume async is support (as it includes IE11).

We could however probably document this properly?

**Comment by Jancat** [comment]
Meet the same error in latest Chrome. How to solve the issue temporarily? 

Should I add the `regenerator-runtime` dependency?

**Comment by DeMoorJasper** [comment]
@Jancat temporarily?

You can stop supporting IE, by changing the browserfield in `package.json` or created a browserlist config. Than it should work without polyfill.

If the polyfill is causing any issues that might be a problem with the polyfill and should be filled in the Babel repo, but I guess this wasn't what you meant?

**Comment by Jancat** [comment]
@DeMoorJasper I'm building an H5 app and targeting moder mobiles. I set the `browserslist` field in **package.json**
```json
"browserslist": [
    "Android >= 6.0",
    "iOS >= 10.3"
  ]
``` 

The `Async functions` support __Android 5, iOS 10.3 and Chrome 42__ in [caniuse](https://caniuse.com/#search=async%20functions)

But I debug in latest Chrome(v67) and the console throw the `regeneratorRuntime` error:
```
Uncaught ReferenceError: regeneratorRuntime is not defined
```

I had to `import 'babel-polyfill` to make it works.

**Comment by DeMoorJasper** [comment]
That's strange perhaps that's a bug from Babel, not sure why this is happening @Jancat

**Comment by Jancat** [comment]
@DeMoorJasper From Babel? But I use `TypeScript` in my project, no Babel except the `babel-polyfill`.

Is bug from Parcel TypeScript loader?

**Comment by DeMoorJasper** [comment]
Parcel runs the javascript output from TS through babel to fit the browserlist

**Comment by hatched** [comment]
Using `1.9.7` I was able to fix this by adding the following to our package.json:

```json
  "browserslist": [
    "last 1 Chrome version"
  ]
```

This stopped it from doing the incomplete transpilation on the async/await functions.
Hope this helps.

**Comment by DeMoorJasper** [comment]
This is never gonna happen, as far as I know changing the default value dynamically isn't a good idea.

This will cause nasty side-effects, require lot's of documentation, cause issues and people still rely on old browsers.

Gonna close this issue as it will never get fixed.

Note: Once Babel 7 support lands we'll try to use `useBuiltins` for preset-env, so this error will never occur as it will just bundle in the polyfills automatically.
