### ISSUE TITLE
Can't set sass compiler option for vue SFC styles

### ISSUE THREAD

**Issue by Bludator** [parcel-bundler/parcel#9161]
# 🙋 feature request/🐛 bug report

## 🤔 Expected Behavior

There should be way how to set up the sass compiler used for the style section of the vue single file component. E.g. by reusing the `.scss` configs.

## 😯 Current Behavior

`.scssrc` is ignored for the vue sfc and there is no other way how to set it up.

## 🔦 Context

I am using a sass library that imports other sass library. There it causes 
```
  Error: Can't find stylesheet to import.
```
Because it expects the `node_modules` directory to be included in the import resolution. 

In the `.scss` files this could be fixed by setting appropriate values to the `.scssrc` file ([as per docs](https://parceljs.org/languages/sass/#configuration)) but have no effect on compiling SCSS style section in vue single file component.

After some source code digging, I have found that the plain `.scss` file is compiled using the `@parcel/transformer-sass` which loads the `.scssrc` config and runs with it the sass compiler.

On the other hand the vue sfcs are compiled by the `@parcel/transformer-vue` which uses `@vue/compiler-sfc` which in turn runs the sass compiler (i.e. the compiler options must be passed by the `@parcel/transformer-vue`)

**Comment by Bludator** [comment]
For setting `loadPath`/`includePaths` there is workaround:

Sass also uses `SASS_PATH` environment variable for this purpose, so setting it to the appropriate values before running parcel works. If you want to use `.env` file beware that parcel uses/emulates the variable for your code not for itself/plugins (i.e. it does not work) and you have to run something line `env-cmd` before parcel

**Comment by towry** [comment]
what a tool

https://github.com/parcel-bundler/parcel/pull/6607
