### ISSUE TITLE
Names for images in meta tags do not get hashed

### ISSUE THREAD

**Issue by axel-zarate** [parcel-bundler/parcel#9167]
# 🐛 bug report

When adding an Open Graph meta tag with `content` set to an image path, the image name is not hashed when running `serve` or `build` commands. If other HTML elements (such as `img`) have the same path, they will also result in an unhashed path after build.

## 🎛 Configuration (.babelrc, package.json, cli command)

Default config.

## 🤔 Expected Behavior

When using a tag such as:
```
<meta property="og:image" content="./img/logo.jpg" />
```
It should result in something similar to:
```
<meta property="og:image" content="/logo.8a6a7831.jpg" />
```
with the corresponding renaming of the actual file.

## 😯 Current Behavior
The image name remains the same:
```
<meta property="og:image" content="/img/logo.jpg" />
```
and the file is copied to the output directory as is, even with subfolders.

## 💁 Possible Solution

Unfortunately, I don't know enough about the inner workings of Parcel to make a suggestion.

## 💻 Code Sample
Simple HTML file. Parcel freshly installed with no custom configuration:
```html
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>My Parcel App</title>
    <meta property="og:image" content="./img/logo.jpg" />
  </head>
  <body>
    <img src="./img/logo.jpg" alt="Logo">
  </body>
</html>
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.3
| Node             | 16.19.0
| npm/Yarn         | 9.4.2/1.22.19
| Operating System | Windows 10

**Comment by devongovett** [comment]
I think this was intentional? Some services require the open graph image urls to be stable I believe.

**Comment by esfomeado** [comment]
Any update regarding this issue?
