### ISSUE TITLE
Build Error For Specific SVGs: Invalid Character Entity

### ISSUE THREAD

**Issue by simonferndriger** [parcel-bundler/parcel#9171]
# 🐛 bug report
This build error occurs:

> @parcel/optimizer-svgo: SvgoParserError: <input>:2:25: Invalid character entity
>
>  1 | <?xml version="1.0" encoding="UTF-8"?>
> 2 | <svg xmlns:x="&nsextend;" xmlns:i="&ns_ai;" xmlns:graph="&nsgraphs;" xmlns="ht…
  3 | <style>.st0{clip-path:url(#SVGID_00000130622006894310625020000004174188710254592…
  4 | <switch>

## 🤔 Expected Behavior
The SVG should be accepted as it is, since there is nothing wrong with it to my knowledge.

## 😯 Current Behavior
Parcel bundler seems not to be able to handle HTML entities within xml attribute values in SVGs.

## 🌍 Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.9.3
| Node             |  v18.17.0
| Operating System | Windows 10

**Comment by howbizarre** [comment]
I added `--no-optimize` to the build script and everything works fine.
During the build, Parcel shows a message

```
⠸ Optimizing index.html...
You are trying to configure cleanupIDs which is not part of preset-default.
Try to put it before or after, for example

plugins: [
  {
    name: 'preset-default',
  },
  'cleanupIDs'
]
```
There is something with the svgo npm package

**Comment by dekaido** [comment]
> I added `--no-optimize` to the build script and everything works fine. During the build, Parcel shows a message
> 
> ```
> ⠸ Optimizing index.html...
> You are trying to configure cleanupIDs which is not part of preset-default.
> Try to put it before or after, for example
> 
> plugins: [
>   {
>     name: 'preset-default',
>   },
>   'cleanupIDs'
> ]
> ```
> 
> There is something with the svgo npm package

Worked for me thanks
