### ISSUE TITLE
Build failed @parcel/optimizer-swc: unknown field `output`

### ISSUE THREAD

**Issue by liliakai** [parcel-bundler/parcel#9174]
# 🐛 bug report

Build fails using latest version of parcel

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
"devDependencies": {
  "@parcel/config-webextension": "^2.9.3",
  "@parcel/transformer-vue": "^2.9.3",
  "npm-run-all": "^4.1.5",
  "parcel": "^2.9.3",
  "stylelint": "^14.9.1",
  "stylelint-config-xo": "^0.21.0",
  "xo": "^0.50.0"
},
```

## 🤔 Expected Behavior

Build succeeded

## 😯 Current Behavior

🚨 Build failed.

```js
parcel build source/manifest.json --no-content-hash --no-source-maps --dist-dir distribution --no-cache --detailed-report 0


@parcel/optimizer-swc: unknown field `output`, expected one of `parse`, `compress`, `mangle`,
`format`, `ecma`, `keep_classnames`, `keepClassnames`, `keep_fnames`, `keepFnames`, `module`,
`safari10`, `toplevel`, `sourceMap`, `outputPath`, `inlineSourcesContent`, `emitSourceMapColumns` at
line 1 column 209
```

## 💁 Possible Solution

Seems like some kind of dependency version mismatch?

## 🔦 Context

Building https://github.com/bellingcat/auto-archiver-extension on mac

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.3
| Node             | 20.4.0
| npm        | 9.7.2
| Operating System | OSX Ventura 13.0.1

**Comment by liliakai** [comment]
Looks similar to #9041

**Comment by liliakai** [comment]
I was able to build successfully with parcel@2.8.3 , so this is almost certainly an issue with the swc optimizer added in 2.9.x

**Comment by mischnic** [comment]
This will be fixed in the next swc release, you'll need to bump your lockfile entry for `@swc/core` once that is published.

https://github.com/swc-project/swc/pull/7746
