### ISSUE TITLE
Array.flat doesn't work under Microsoft Edge or IE11

### ISSUE THREAD

**Issue by 0x1af2aec8f957** [parcel-bundler/parcel#9176]
`Parcel2` did not provide the correct filling method for [Array.flat](https://caniuse.com/mdn-javascript_builtins_array_flat) according to the target`IE 11`. 
A similar source to this issue is: [babel-issue](https://github.com/babel/babel/issues/9749#issuecomment-475686062).

package.json:  
```json
...
"browserslist": "IE 11",
...
```

.parcelrc:  
```json
{
  "extends": "@parcel/config-default",
  "resolvers": ["@parcel/resolver-glob", "..."]
}
```

I did not use Babel's configuration file in the project.

I am now adding `<script src="https://polyfill.io/v3/polyfill.min.js?features=Array.prototype.flat%2CArray.prototype.flatMap"></script>` obtain a temporary solution.

**Comment by 0x1af2aec8f957** [comment]
In addition to the above, I also found that the following methods lack necessary filling schemes:
1. intl-pluralrules
2. finally-polyfill
3. Abortcontroller

I am currently obtaining a temporary solution through the following channels:

```html
...
<script src="https://polyfill.io/v3/polyfill.min.js?features=Array.prototype.flatMap%2CArray.prototype.flat%2CAbortController%2CIntl%2CPromise.prototype.finally"></script>
...
```

Please note that `IE11` does not support `Promise.finally`, therefore `finally-polyfill` needs to be added.

**Comment by devongovett** [comment]
Parcel does not insert any polyfills automatically. It only does syntax transforms. For runtime poly filling, what you're doing is the right way. Alternatively you could import polyfills from something like core-js.
