### ISSUE TITLE
Parcel spends a lot of time doing SymbolPropagation in large apps

### ISSUE THREAD

**Issue by pastelsky** [parcel-bundler/parcel#9190]
# 🐛 bug report

I've been profiling Parcel for a few sections of our app, and noticed that the symbol propagation step takes a very long time during compilation.

I've recorded a trace and split it apart by workers (otherwise its too large and can make the visualizer crash). This is the trace for the master worker —

[profile-master.json.zip](https://github.com/parcel-bundler/parcel/files/12318172/profile-master.json.zip)

This can be analyzed using something like https://www.speedscope.app/

<img width="1725" alt="Screenshot 2023-08-11 at 7 44 21 AM" src="https://github.com/parcel-bundler/parcel/assets/8946207/dd8b3fde-f8d7-4ba1-861d-454ad2246c1b">

Top times taken by functions —

```
Total (min:sec) |  Self (min:sec)  |  Symbol Name
-- | -- | --
4:13 (26%) | 4:12 (26%) | (anonymous SymbolPropagation.js:90)
2:47 (17%) | 1:58 (12%) | getNodeByContentKey
4:19 (27%) | 1:36 (9.9%) | (anonymous SymbolPropagation.js:505)
3:03 (19%) | 1:22 (8.4%) | getIncomingDependencies
1:35 (9.9%) | 1:19 (8.2%) | getNodeIdsConnectedTo
55.68s (5.7%) | 55.47s (5.7%) | (garbage collector)
51.41s (5.3%) | 50.95s (5.2%) | getNode
12:00 (74%) | 23.56s (2.4%) | propagateSymbolsDown
22.41s (2.3%) | 19.73s (2.0%) | Resolver
23.51s (2.4%) | 18.68s (1.9%) | has
14.92s (1.5%) | 12.12s (1.2%) | propagateSymbolsUp
```

Things to note —
- This was recorded with all optimizations including sourcemaps, and scope hoisting turned off.
- It seems that symbol propagation was enabled in https://github.com/parcel-bundler/parcel/pull/8723 even when scope hoisting is turned off (cc: @mischnic)
- This problem is exaggerated by the fact that the symbol propagation is single threaded — which means using beefier machines has little to no effect on compilation times.

## 🎛 Configuration (.babelrc, package.json, cli command)
N.A.

## 🤔 Expected Behavior
Symbol propagation does not happen or does not take as long with scope hoisting turned off.

## 😯 Current Behavior
Symbol propagation can account for nearly 50-60% of parcel build time in large apps, and it doesn't (or can't) make use of multithreading.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.9.3 |
| Node             | 16.9.0 |
| npm/Yarn         | 1.22 | 
| Operating System | Ubuntu 22 |

**Comment by mischnic** [comment]
Could you compare the performance of 2.9.0 and 2.8.3? I wonder if the new incremental approach made it worse
