### ISSUE TITLE
Why there are`<anon>` files in source map?

### ISSUE THREAD

**Issue by jecfish** [parcel-bundler/parcel#9208]
# 🐛 bug report

## 🎛 Configuration
- Here is the sample code: https://github.com/jecfish/consistent-source-map-demo.
- This happen in  v2.9.3. It was working fine in 2.8.3 (perhaps due to terser to swc changes)

Run `parcel build src/index.html` with v2.9.3 and host the output with a web server. View the sources in Chrome DevTools. Chrome DevTools used the source map files to generate the output. Here is the output:

- `index...js` is the minifed js file
- `src/script.ts` is the file mapped from source map with the `inde..js.map` file.
- `<anon>` is the file mapped from source map with the `inde..js.map` file.

![sm](https://github.com/parcel-bundler/parcel/assets/5917927/b3f02e7f-5d00-4aa1-8bf5-f039489b34bb)

## 🤔 Expected Behavior

- Expect to see `src/script.ts`. 
- Do not expect to see `<anon>` file. 
- Expect the `index...js.map` source map file to have only `"sources": ["src/script.ts"]`

## 😯 Current Behavior

- See `<anon>` file in Chrome DevTools
- The `index...js.map` source map file have  2 items in`"sources": ["<anon>", "src/script.ts"]`

## 💁 Possible Solution

What is the purpose of the `<anon>` output? From the file, I guess it is the intermediary (unminified) javascript output. Does Parcel dev use that for debugging?

The possible solution is to remove `<anon>` from the source map. Or give it a better name (e.g. index ...unminified.js? 

## 🔦 Context

This issue make Chrome DevTools display `<anon>` files in the Sources. Developers are confuse about what the file is about.

## 💻 Code Sample

https://github.com/jecfish/consistent-source-map-demo

**Comment by devongovett** [comment]
Looks like it comes from SWC: https://github.com/swc-project/swc/blob/662f236aa5c1375ea4b175dbb6d85ad974503b84/crates/swc_common/src/syntax_pos.rs#L258

**Comment by jecfish** [comment]
Thanks Devon! Filed an upstream bug in swc. https://github.com/swc-project/swc/issues/7851
