### ISSUE TITLE
Dev server serves wrong page when using query parameters without extension

### ISSUE THREAD

**Issue by kixelated** [parcel-bundler/parcel#9211]
# 🐛 bug report
The dev server serves the wrong page when both:
* no extension is provided
* query parameters are used

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  	"source": [
		"index.html",
		"publish.html",
	],
}
```

## 🤔 Expected Behavior

* `/publish` returns `publish.html`
* `/publish?foo=bar` returns `pubish.html`
* `/publish.html?foo=bar` returns `publish.html`

## 😯 Current Behavior

* `/publish` correctly returns `publish.html`
* `/publish?foo=bar` **incorrectly** returns `index.html`
* `/publish.html?foo=bar` correctly returns `publish.html`

## 💻 Code Sample

Reproducible on [this commit](https://github.com/kixelated/moq-js/tree/226eeaf0bfd04a4ef34393e7a8a7e5fca86e3e51).

**Comment by mischnic** [comment]
The relevant code: https://github.com/parcel-bundler/parcel/blob/feae29ebaebcc79f624c87c386de8137970835b0/packages/reporters/dev-server/src/Server.js#L184

**Comment by tanmoyopenroot** [comment]
Hey @mischnic, Taking this up.
