### ISSUE TITLE
I added Parytown to my project and i got @parcel/core: No transformers found for index.partytown.

### ISSUE THREAD

**Issue by AhmadHddad** [parcel-bundler/parcel#9215]
# 🐛 bug report

I'm using React and i'm trying to add Partytown to my project, when i got this error 
"@parcel/core: No transformers found for index.partytown."
i tried adding searching for a resolver but i couldn't find any, also i tried deleting the .parcel-cach, that didn't work either. 

is there anything that i can do to fix this?

"scripts": {
    "start": "parcel --port 3000",
    "partytown": "partytown copylib public/~partytown"
  },

```js
{
  "extends": "@parcel/config-default",
  "resolvers": ["parcel-resolver-ts-base-url", "..."]
}

```

## 🤔 Expected Behavior

Normal build

## 😯 Current Behavior

Build failed.
@parcel/core: No transformers found for index.partytown.
node_modules/@parcel/config-default/index.json:3:3
     2 |   "bundler": "@parcel/bundler-default",
  >  3 |   "transformers": {
  >    |   ^^^^^^^^^^^^^^^^^
  >  4 |     "types:*.{ts,tsx}": ["@parcel/transformer-typescript-types"],
  >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  >  5 |     "bundle-text:*": ["...", "@parcel/transformer-inline-string"],
  >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  >  6 |     "data-url:*": ["...", "@parcel/transformer-inline-string"],
  >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  >  7 |     "worklet:*.{js,mjs,jsm,jsx,es6,cjs,ts,tsx}": [
  >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  >  8 |       "@parcel/transformer-worklet",
  >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  >  9 |       "..."
  >    | ^^^^^^^^^^^
  > 10 |     ],
  >    | ^^^^^^
  > 11 |     "*.{js,mjs,jsm,jsx,es6,cjs,ts,tsx}": [
  >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  > 12 |       "@parcel/transformer-babel",
  >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  > 13 |       "@parcel/transformer-js",
  >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

## 🔦 Context

Installing Partytown and using it

## 💻 Code Sample

`
    <script src="./public/~partytown/partytown.js">
  <script type="text/partytown">  
-- any JS script here --
      </script>`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel                  | "^2.9.3"
| @builder.io/partytown                  | "^0.8.0
|React                  | v18.2.0
| Node                    | v16.19.1
| npm/Yarn             | 1.22.19
| Operating System | MacOS: 13.4

**Comment by devongovett** [comment]
`text/partytown` causes Parcel to look for a transformer for the partydown language. https://github.com/parcel-bundler/parcel/blob/f569eb1a8493c333e5431e1c459526a608245ce0/packages/transformers/html/src/inline.js#L55

You could configure this in your `.parcelrc`:

```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.partytown": ["@parcel/transformer-raw"]
  }
}
```

This example uses the the raw transformer to pass through the content unmodified.
