### ISSUE TITLE
Nearly all dist files are named "index"

### ISSUE THREAD

**Issue by Badisi** [parcel-bundler/parcel#9218]
# 🐛 bug report

## 🎛 Configuration

```js
// package.json
{
    "source": [
        "src/index.html",
        "src/404.html"
    ],
    "browserslist": "> 0.5%, last 2 versions, not dead",
    "scripts": {
        "start": "parcel",
        "build": "parcel build --no-source-maps --detailed-report"
    },
    "devDependencies": {
        "@parcel/packager-raw-url": "^2.9.3",
        "@parcel/transformer-sass": "^2.9.3",
        "@parcel/transformer-webmanifest": "^2.9.3",
        "parcel": "^2.9.3"
    }
}
```

## 🤔 Expected Behavior

After running the `build` command I'm expecting every file in the dist folder to have kept its original name.

## 😯 Current Behavior

What happened instead is that mostly every dist file are named the same (ie. "index.{hash}.*")

<img width="478" alt="Screen Shot 2023-08-28 at 22 11 54" src="https://github.com/parcel-bundler/parcel/assets/674862/d8ca0e36-9d10-41d5-82ea-46f085bbc734">

## 🔦 Context

I'm running the following command: `parcel build --no-source-maps --detailed-report`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.3
| Node             | 16.20.0
| npm/Yarn         | 9.8.1
| Operating System | macOS 10.13.6

**Comment by codewizard13** [comment]
I'm curious about this as well.

**Comment by devongovett** [comment]
They are named that way because they are sibling files to your entry point (index.html). To control naming, use a custom Namer plugin. https://parceljs.org/features/plugins/#namers

**Comment by Badisi** [comment]
This used to work in parcel v1..
Sad to see there is no built-in setting to keep it backward compatible, as it is actually a mess when you need to debug things.
What was the reasoning to named everything with the same name as the entry point ?

Also I've tried using existing custom namer plugins but none solved it.
Is there a way I could configure my own namer without having to build a plugin as a package ?

Thanks
