### ISSUE TITLE
@parcel/optimizer-htmlnano: Could not resolve module "node:os"

### ISSUE THREAD

**Issue by sjsouvik** [parcel-bundler/parcel#9224]
# 🐛 bug report

An import of a module inside node_modules(`/node_modules/cosmiconfig/dist/index.js`) breaks the build.

`const node_os_1 = __importDefault(require("node:os"));`

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "app",
  "version": "1.0.0",
  "description": "",
  "source": "src/index.html",
  "scripts": {
    "start": "parcel",
    "build": "parcel build",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "parcel": "^2.9.3",
    "process": "^0.11.10"
  },
  "browserslist": "> 0.5%, last 2 versions, not dead"
}

```

## 🤔 Expected Behavior

Executing `parcel build` should build the project.

## 😯 Current Behavior

```
npm run build

> app@1.0.0 build
> parcel build

🚨 Build failed.

@parcel/optimizer-htmlnano: Could not resolve module "node:os" from 
"/app/node_modules/cosmiconfig/dist/index.js"

  Error: Could not resolve module "node:os" from "/app/node_modules/cosmiconfig/dist/index.js"
      at NodePackageManager.resolveInternal 
  (/app/node_modules/@parcel/package-manager/lib/index.js:3672:21)
      at NodePackageManager.resolveSync (/app/node_modules/@parcel/package-manager/lib/index.js:3567:29)
      at NodePackageManager.requireSync (/app/node_modules/@parcel/package-manager/lib/index.js:3394:33)
      at m.require (/app/node_modules/@parcel/package-manager/lib/index.js:3410:25)
      at require (node:internal/modules/cjs/helpers:103:18)
      at Object.<anonymous> (/app/node_modules/cosmiconfig/dist/index.js:23:35)
      at Module._compile (node:internal/modules/cjs/loader:1218:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
      at Module.load (node:internal/modules/cjs/loader:1081:32)
      at NodePackageManager.load (/app/node_modules/@parcel/package-manager/lib/index.js:3423:15)
```

## 💁 Possible Solution

Still looking for that 🔎

## 🔦 Context

Want to build the project so that it can be deployed.

## 💻 Code Sample

https://github.com/sjsouvik/infinite-scroll-react

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.3
| Node             | v18.13.0
| npm/Yarn         | 8.19.3
| Operating System | macOS Ventura 13.5.1

**Comment by caizixian** [comment]
Rolling back to `"cosmiconfig": "=8.2.0"`fixes the issue for me

**Comment by ErikBooij** [comment]
Same issue here.

@caizixian's tempfix works as a temporary workaround (thanks!).

**Comment by bpampuch** [comment]
For those of you who still struggle, downgrade htmlnano (by adding `"htmlnano": "2.0.3"` to your devDependencies in package.json and running`yarn` or `npm install`). The issue seems to be in cosmiconfig version references by htmlnano

**Comment by ux-ui-pro** [comment]
It helped me `npm install cosmiconfig@8.2.0`

udp.
`npm list cosmiconfig` - you should see that the version of cosmiconfig in your project has changed to 8.2.0

**Comment by raph6** [comment]
For npm you can add to your `package.json`
```json
  "overrides": {
    "@parcel/optimizer-htmlnano": {
      "htmlnano": "2.0.3"
    }
  },
```

For yarn
```json
  "resolutions": {
    "htmlnano": "2.0.3"
  }
```

**Comment by velusgautam** [comment]
Downgrading the parcel to `"parcel": "v2.8.0"` will also fix this for the `htmlnano` `node:os` issue.

**Comment by gowrissnkr** [comment]
Same issue here. If anyone have to solution?

**Comment by lodenos** [comment]
Same problem, even a SIGABRT

```
yarn run v1.22.19
$ parcel build
libc++abi: terminating due to uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by JayRichh** [comment]
Thanks my dudes, appreciate the assist been having an issue with this one over the weekend.

**Comment by ncharanaraj** [comment]
> Same issue here. If anyone have to solution?

Dowgrade the cosmiconfig version from 8.3.4 to 8.2.0 using this commond **npm i -D cosmiconfig@8.2.0**

**Comment by caizixian** [comment]
This should be fixed now in cosmiconfig 8.3.5 https://github.com/cosmiconfig/cosmiconfig/issues/323

**Comment by mischnic** [comment]
So this can be closed now?

**Comment by raph6** [comment]
> So this can be closed now?

lgtm, no problem for me anymore

**Comment by seba-campo** [comment]
Thanks!!!  worked with  `yarn install cosmiconfig@8.2.0` for me.
