### ISSUE TITLE
Build warning: Unknown usage of CommonJS `exports` object.

### ISSUE THREAD

**Issue by Tomalak** [parcel-bundler/parcel#9230]
# 🐛 bug report

I'm using Parcel to bundle a web application based on knockout.js. Building it with `--log-level verbose` gives an _"Unknown usage of CommonJS `exports` object. This causes tree shaking to be disabled."_ warning.

## 🎛 Configuration / Minimal Setup

Everything is at default. No babel config file, no parcel config file.

## 💻 Code Sample

package.json
```json
{
    "source": "index.html",
    "sideEffects": ["main.js"],
    "dependencies": {
        "knockout": "^3.5.1"
    },
    "devDependencies": {
        "parcel": "^2.9.3"
    }
}
```

main.js
```js
import ko from 'knockout';
ko.applyBindings({ sampleText: 'It works!' });
```

index.html
```html
<html>
  <head>
    <script type="module" src="main.js"></script>
  </head>
  <body>
    <div data-bind="text: sampleText"></div>
  </body>
</html>
```

## 🤔 Expected Behavior

`npx parcel build index.html --log-level verbose`

should build without issues.

## 😯 Current Behavior

Output
```text
@parcel/transformer-js: Unknown usage of CommonJS `exports` object. This causes tree shaking to be disabled.

  C:\Users\Tomalak\Projects\parcel-bug\node_modules\knockout\build\output\knockout-latest.js:7:300
    6 |
  > 7 | rts||exports):n(A.ko={})})(function(S,T){function K(a,c){return null===a||typeof a in W?a===c:!1}function X(b,c){var d;return function(){d||(d=a.a.setTimeout
  >   |      ^^^^^^^
    8 | d=a.a.setTimeout(b,c)}}function Z(a,c){c&&"change"!==c?"beforeChange"===c?this.pc(a):this.gb(a,c):this.qc(a)}function aa(a,c){null!==c&&c.s&&c.s()}function b
    9 | a.version);a.options={deferUpdates:!1,useOnlyNativeEvents:!1,foreachHidesDestroyed:!1};a.a=function(){function b(a,b){for(var c in a)f.call(a,c)&&b(c,a[c])}f
  ℹ Learn more: https://parceljs.org/features/scope-hoisting/#commonjs

√ Built in 5.47s

dist\index.html              188 B    1.77s
dist\index.cf94ac65.js    65.75 KB    1.86s
```

Removing the `||exports` directly in `\node_modules\knockout\build\output\knockout-latest.js` makes the warning go away, and (I suppose?) enables tree-shaking.

The [original source](https://github.com/knockout/knockout/blob/45e86bf0347cf742ca359bab051ea82fdfae7a5d/build/fragments/amd-pre.js#L8) of the affected line is: 

```js
(function(factory) {
    // Support three module loading scenarios
    if (typeof define === 'function' && define['amd']) {
        // [1] AMD anonymous module
        define(['exports', 'require'], factory);
    } else if (typeof exports === 'object' && typeof module === 'object') {
        // [2] CommonJS/Node.js
        factory(module['exports'] || exports);  // module.exports is for Node.js
    } else {
        // [3] No module loader (plain <script> tag) - put directly in global namespace
        factory(window['ko'] = {});
    }
}
```

## 💁 Possible Solution

I think this particular usage of `exports` should not result in a warning. Although I admit that I don't really understand the rationale/underlying cause, it might well be that knockout is doing its AMD wrapper wrong.

## 🌍 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.9.3
| Node             |16.15.1
| npm/Yarn         |npm
| Operating System |Windows

**Comment by devongovett** [comment]
It's just a warning, it should still work ok. This setup would not be tree-shakeable anyway due to the function wrapper. I would just ignore this warning if I were you.

**Comment by Tomalak** [comment]
@devongovett I am. This bug report was less meant to be a complaint or an ask for help - I just wanted to point out a situation where usage detection for `exports` _might_ be a bit off in Parcel. If it's fine, it's fine.
