### ISSUE TITLE
Release v2.10.0

### ISSUE THREAD

**Issue by legobeat** [parcel-bundler/parcel#9235]
# 🙋 feature request

A few anticipated improvements and fixes have been merged since last release `2.9.3`. Any indications on release schedule for the v2 lineage?

**Comment by legobeat** [comment]
@mischnic @devongovett Anything in the pipe? :)

**Comment by mischnic** [comment]
Yes: https://github.com/parcel-bundler/parcel/releases/tag/v2.10.0

**Comment by devongovett** [comment]
https://github.com/parcel-bundler/parcel/releases/tag/v2.10.0

**Comment by legobeat** [comment]
Thanks!
