### ISSUE TITLE
Assertion error in getBundleFromBundleRoot

### ISSUE THREAD

**Issue by kyegupov** [parcel-bundler/parcel#9238]
# 🐛 bug report

I'm getting this with parcel 2.9.3:

```
AssertionError [ERR_ASSERTION]: false == true
      at getBundleFromBundleRoot (/home/redacted/workspace/.yarn/cache/@parcel-bundler-default-npm-2.9.3-da108dccec-271f354e61.zip/node_modules/@parcel/bundler-default/lib/DefaultBundler.js:952:27)
      at createIdealGraph (/home/redacted/workspace/.yarn/cache/@parcel-bundler-default-npm-2.9.3-da108dccec-271f354e61.zip/node_modules/@parcel/bundler-default/lib/DefaultBundler.js:625:21)
      at Object.bundle (/home/redacted/workspace/.yarn/cache/@parcel-bundler-default-npm-2.9.3-da108dccec-271f354e61.zip/node_modules/@parcel/bundler-default/lib/DefaultBundler.js:105:19)
```

## 🎛 Configuration (.babelrc, package.json, cli command)

Our setup is quite complicated (yarn with workspaces and pnp). I'd need some help with debugging before I can extract a minimal repro case.

## 🤔 Expected Behavior

Parcel should work and start the dev server.

## 😯 Current Behavior

Parcel crashes with the error message as per above.

The interesting bit: if I restart `yarn parcel src/pages/index.html`, it never crashes and seems to work, but the route in question is not working (Cannot find module).

## 🔦 Context

What I'm doing is: trying to migrate a project from Next.js 12 to vanilla React + Parcel.
I've been adding routes one-by-one to the index page, and after adding our most complex route, the failure starts to happen.

The command is `yarn parcel src/pages/index.html`

I've identified the bundleRoot in question to be a scss file for one of the components, there's nothing obviously fishy about it.

It's pretty hard to debug, 
I've tried to run Parcel from source, using `yarn link [workspace] --all`, but it either crashes during yarn install or fails due to mismatching versions, so I have resorted to patching package zip to get some debug info.

But it feels like I'm out of my depth, I have a hard time understanding what's going on in DefaultBundler.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.9.3 |
| Node             | 16 |
| npm/Yarn         | yarn 3.3.1 |
| Operating System | Linux (Ubuntu) |

**Comment by mischnic** [comment]
cc @AGawrys
