### ISSUE TITLE
how to add a https ca certificate inclusion in package.json file 

### ISSUE THREAD

**Issue by sarathskr-dev** [parcel-bundler/parcel#9268]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
Do you mean running a https dev server? https://parceljs.org/features/cli/#parameters-specific-to-serve-and-watch
