### ISSUE TITLE
cvn

### ISSUE THREAD

**Issue by darkomenz** [parcel-bundler/parcel#930]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "your": { "config": "here" }
}
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by DeMoorJasper** [comment]
Could you provide a proper description of the issue?
I'll close this off for now but will definitely reopen if a description is provided
