### ISSUE TITLE
Parcel build breaks swiper package

### ISSUE THREAD

**Issue by PaulT-0** [parcel-bundler/parcel#9305]
# 🐛 bug report

I'm using swiper in a project and when I run parcel serve everything works fine, but when I do parcel build, the built app doesn't initialize swiper correctly when I call swiper's initialize() method

## 🎛 Configuration (.babelrc, package.json, cli command)

No babelrc, .parcelrc is this (probably unrelated)
```js
{
    "extends":"@parcel/config-default",
    "transformers": {
        "jsx:*.svg": ["...", "@parcel/transformer-svg-react"]
      }  
}
```

for testing I'm doing "npx parcel build src/index.tsx --dist-dir build --log-level verbose --no-optimize --no-scope-hoist". Problem persists without those arguments though

## 🤔 Expected Behavior

The app produced by parcel build should work identically to that from parcel serve

## 😯 Current Behavior

I've stepped through the problem code and I can see that there's a function extend() within swiper. Within this function there's a for loop that checks the arguments provided to extend(). 
When I run parcel build (even with --no-optimize) the built version refactors the contents of the for loop into a function called _loop(). _loop still tries to access the arguments, but gets its own arguments instead of the arguments provided to extend().

See below for examples of the extend function from parcel serve vs parcel build:

Parcel Serve:
```js
function extend() {
    const to = Object(arguments.length <= 0 ? undefined : arguments[0]);
    const noExtend = [
        "__proto__",
        "constructor",
        "prototype"
    ];
    for(let i = 1; i < arguments.length; i += 1){
        const nextSource = i < 0 || arguments.length <= i ? undefined : arguments[i];
        if (nextSource !== undefined && nextSource !== null && !isNode(nextSource)) {
            const keysArray = Object.keys(Object(nextSource)).filter((key)=>noExtend.indexOf(key) < 0);
            for(let nextIndex = 0, len = keysArray.length; nextIndex < len; nextIndex += 1){
                const nextKey = keysArray[nextIndex];
                const desc = Object.getOwnPropertyDescriptor(nextSource, nextKey);
                if (desc !== undefined && desc.enumerable) {
                    if (isObject(to[nextKey]) && isObject(nextSource[nextKey])) {
                        if (nextSource[nextKey].__swiper__) to[nextKey] = nextSource[nextKey];
                        else extend(to[nextKey], nextSource[nextKey]);
                    } else if (!isObject(to[nextKey]) && isObject(nextSource[nextKey])) {
                        to[nextKey] = {};
                        if (nextSource[nextKey].__swiper__) to[nextKey] = nextSource[nextKey];
                        else extend(to[nextKey], nextSource[nextKey]);
                    } else to[nextKey] = nextSource[nextKey];
                }
            }
        }
    }
    return to;
}
```

Parcel Build:
```js
function extend() {
    var _loop = function(i) {
        var nextSource = i < 0 || arguments.length <= i ? undefined : arguments[i];
        if (nextSource !== undefined && nextSource !== null && !isNode(nextSource)) {
            var keysArray = Object.keys(Object(nextSource)).filter(function(key) {
                return noExtend.indexOf(key) < 0;
            });
            for(var nextIndex = 0, len = keysArray.length; nextIndex < len; nextIndex += 1){
                var nextKey = keysArray[nextIndex];
                var desc = Object.getOwnPropertyDescriptor(nextSource, nextKey);
                if (desc !== undefined && desc.enumerable) {
                    if (isObject(to[nextKey]) && isObject(nextSource[nextKey])) {
                        if (nextSource[nextKey].__swiper__) to[nextKey] = nextSource[nextKey];
                        else extend(to[nextKey], nextSource[nextKey]);
                    } else if (!isObject(to[nextKey]) && isObject(nextSource[nextKey])) {
                        to[nextKey] = {};
                        if (nextSource[nextKey].__swiper__) to[nextKey] = nextSource[nextKey];
                        else extend(to[nextKey], nextSource[nextKey]);
                    } else to[nextKey] = nextSource[nextKey];
                }
            }
        }
    };
    var to = Object(arguments.length <= 0 ? undefined : arguments[0]);
    var noExtend = [
        "__proto__",
        "constructor",
        "prototype"
    ];
    for(var i = 1; i < arguments.length; i += 1)_loop(i);
    return to;
}
```

## 🔦 Context

I'm trying to use the swiper package within my app that uses parcel. I'm not sure what's causing this build issue, hopefully there's some config option I'm unaware of that changes the behaviour here?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |	2.9.3
| Node             |	14.18.2
| npm/Yarn         |	npm 6.14.15
| Operating System |	Win10

**Comment by mischnic** [comment]
This is a bug, it works fine in standalone swc for some reason:
https://play.swc.rs/?version=1.3.74&code=H4sIAAAAAAAAA12OwQrCMBBE7%2F2KOSYoxZ7T%2BiPiIdRtbI0bSDegSP%2FdVGkE57APdmeGHRL3MgYGPYT4ojReFbKGEKE8CUZ0aExGCxtduhPLXHtiJ9d1u8vXLbOqDzwLbA6pGz01uiMkJjLFUIqn7DmYjBbNh%2F9VW13wVPvglD1N5%2F3vCV2MS%2FWdyxsSpn9mzQAAAA%3D%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rq7Sl30Dj2ERZ2IiJ9sIhVFuXsJgbTZ4ffGjLwOSsEsGp5qLc8yRGQhPueSSPYJPyUB0g5Fs4kJbr2dZa9GtEI12o4GEvJEqW7JveFgQxDqeMuc8WbM%2F0IdXGQSuYI7in6ydNUNTQkuvJdatkNSjnToH%2FCDuuz8GIy8%2BmbihYbtC6sl6BwUAQAA
