### ISSUE TITLE
More into: https://parceljs.org/features/dependency-resolution/#package-entries

### ISSUE THREAD

**Issue by damian-pastorini** [parcel-bundler/parcel#9308]
More into: https://parceljs.org/features/dependency-resolution/#package-entries
```
Parcel checks the following fields (in order):

source – If the module is behind a symlink (e.g. in a monorepo, or via npm link), then Parcel uses the source field to compile the module from source. The source field can also be used as an alias mapping if a package has multiple entry points – see Aliases below for details.
exports – Package exports, see below for details.
browser – A browser-specific version of a package. If building for a browser environment, the browser field overrides other fields. The browser field can also be used as an alias mapping if a package has multiple entry points – see Aliases below for details.
module – An ES module version of the package.
```

So basically, that doesn't seems to be the case, because browser comes before module in our package and Parcel does it the other way around, maybe that is the bug?

_Originally posted by @damian-pastorini in https://github.com/parcel-bundler/parcel/discussions/8126#discussioncomment-7254368_

**Comment by mischnic** [comment]
I'm not sure if I understood you correctly, but for these "legacy" entries (compared to [`exports`](https://parceljs.org/features/dependency-resolution/#conditional-exports)), the order of declaration doesn't matter. 

https://github.com/parcel-bundler/parcel/blob/96185d00d19b79becfb49b8990c927f1a2784cb1/packages/utils/node-resolver-rs/src/package_json.rs#L744-L788

So what behaviour are you seeing and what did you expect to happen instead?
