### ISSUE TITLE
🙋, how compress build file?

### ISSUE THREAD

**Issue by daoket** [parcel-bundler/parcel#931]
### 🤔 Expected Behavior
```
yarn run build  --->  target.zip
```

### 😯 Current Behavior
target
├── index.html
├── *.js
├── *.css
└── *.png

### 💁 Possible Solution

```
parcel build index.html -d target -zip
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.6.2
| Node             |  8.9.4
| Yarn         | 1.3.2
| Operating System | win10

**Comment by DeMoorJasper** [comment]
Just chain the command with a zip command, this is out of scope of parcel as far as i know

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
