### ISSUE TITLE
Uncaught ReferenceError: <Class> is not defined

### ISSUE THREAD

**Issue by fguillen** [parcel-bundler/parcel#9316]
# 🐛 bug report

A class definition is not found when I try to make 

```js
new MyClass();
```

It works in development mode but not in production build

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json

```js
{
  "name": "parcel-test",
  "source": "src/index.html",
  "scripts": {
    "start": "parcel --public-url ./",
    "build": "parcel build --public-url ./",
    "deploy": "push-dir --dir=dist --branch=gh-pages --cleanup --verbose"
  },
  "devDependencies": {
    "parcel": "^2.10.0",
    "push-dir": "^0.4.1"
  }
}

```

## 🤔 Expected Behavior

I want the definition of my classes to be accesible. As in normal execution or in parcel development.

## 😯 Current Behavior

```
app.js:3 Uncaught ReferenceError: Class1 is not defined
    at new <anonymous> (app.js:3:24)
    at app.js:7:1
```

## 💁 Possible Solution

?

## 🔦 Context

I can not deploy my app.

## 💻 Code Sample

- https://github.com/fguillen/ParcelBugTest
- https://fguillen.github.io/ParcelBugTest/

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.10.0  |
| Node             |
| npm/Yarn         | yarn v1.22.19 |
| Operating System | MacOS 13.5 (22G74) |

**Comment by mischnic** [comment]
The scripts get minified separately. What you should do instead is
Only
```html
  <script src="./js/app.js" type="module"></script>
```
and then import
```js
import {Class1} from "./class_1.js";
class App {
  constructor() {
    this.class_1 = new Class1();
  }
}

new App();
```

(and do `export class Class1 ...`)

**Comment by fguillen** [comment]
@mischnic thanks for the quick and detailed explanation. It is working:

- https://github.com/fguillen/ParcelBugTest/compare/main...fix

:)
