### ISSUE TITLE
Invalid path of `@parcel\config-default\index.json`

### ISSUE THREAD

**Issue by lazex** [parcel-bundler/parcel#9319]
I got a `no such file or directory` error when I run `parcel build index.js`.
There was no error before and it happened when I updated the `parcel` package from 2.8 to 2.10.
However, it is now happening in 2.8 as well.
It's probably caused by packages installed by dependencies of `parcel`.

According to the error message, the file path being accessed is:

```
C:\?\Volume{UUID}\bar\node_modules\@parcel\config-default\index.json
```

Actual path is:

```
C:\foo\bar\node_modules\@parcel\config-default\index.json
```

If using volume:

```
\\?\Volume{UUID}\bar\node_modules\@parcel\config-default\index.json
```

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.10       |
| Node             | 18         |
| npm/Yarn         | yarn       |
| Operating System | Windows    |

**Comment by lazex** [comment]
The volume is mounted on `C:\foo`.

**Comment by GillesTourreau** [comment]
I confirm that I have the same issue.
I created a DevDrive volume mounted to a Windows directory, and parcel does not work when source code is access with a volume mounted to a directory.
