### ISSUE TITLE
Transformer "Invalid specifier type: custom"

### ISSUE THREAD

**Issue by grishy** [parcel-bundler/parcel#9377]
# 🐛 bug report

I wanted to add a custom resolve for files added to Transformer. But when I try to specify the "custom" type, I get an error. The typescript says that it is possible to use this type.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    "entrypoint": [
      "./src/parcel-plugins/parcel-transformer.mjs"
    ]
  },
  "resolvers": [
    "./src/parcel-plugins/parcel-resolver.mjs",
    "..."
  ]
}

```

## 🤔 Expected Behavior

I will be able to add deps to file and after that handle it in resolver.

## 😯 Current Behavior

```
npm run build

> grishy-blog@1.0.0 build
> parcel build

🚨 Build failed.

@parcel/core: Failed to resolve '/Users/grishy/projects/lab/blog/content/posts/hello-world/index.md' from './entrypoint'
@parcel/resolver-default: Invalid specifier type: custom

  Error: Invalid specifier type: custom
```

## 💁 Possible Solution

Remove from docs `custom` or allow to handle it.  
Docs:
```ts
export type SpecifierType = "commonjs" | "esm" | "url" | "custom";
// ...
  /**
   * How the specifier should be interpreted.
   *   - esm: An ES module specifier. It is parsed as a URL, but bare specifiers are treated as node_modules.
   *   - commonjs: A CommonJS specifier. It is not parsed as a URL.
   *   - url: A URL that works as in a browser. Bare specifiers are treated as relative URLs.
   *   - custom: A custom specifier. Must be handled by a custom resolver plugin.
   */
  readonly specifierType: SpecifierType;
```

## 💻 Code Sample

```js
// parcel-transformer.mjs
import { Transformer } from '@parcel/plugin';
import utils from '@parcel/utils';
import fs from "@parcel/fs";
import path from "path";

const root = process.cwd();
const nodeFS = new fs.NodeFS();

export default new Transformer({
  async transform({ asset, logger }) {
    logger.info({
      message: `Tranform: ${asset.filePath}`
    });

    const globPath = path.join(root, "./content/posts/**/index.md");
    let files = await utils.glob(globPath, nodeFS, {
      onlyFiles: true,
    });

    for (let file_path of files) {
      logger.info({
        message: `Add post: ${file_path}`
      });

      // const relativePath = path.relative(root, file_path);
      asset.addDependency({
        specifier: file_path,
        specifierType: 'custom',
      });
    }

    // Return the asset
    return [asset];
  }
});
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.10.2 |
| Node             | v18.11.0| 
| npm/Yarn         |9.1.2|
| Operating System | macOS

**Comment by mischnic** [comment]
Have you made sure that `./src/parcel-plugins/parcel-resolver.mjs` handles all of these custom dependencies?

**Comment by grishy** [comment]
You are right! Sorry for time wasting.
I think I had an error elsewhere in resolver, I was adding logs but because there was an error, all the info was deleted and I didn't notice the output of resolver. (during error all info msg above erased).  
With ` |& cat` I found error 🙂

**Comment by grishy** [comment]
@mischnic 
 Is it normal that when an error occurs, the output before the error is erased?

**Comment by mischnic** [comment]
Unfortunately yes (normal in the sense of: it's a known inconvenience)

**Comment by grishy** [comment]
Got it, if possible I would just change the error message like  
`parcel/resolver-default: "custom" type is not supported`
