### ISSUE TITLE
🙋 - Is there a way to save the `--out-dir` config?

### ISSUE THREAD

**Issue by kenmorechalfant** [parcel-bundler/parcel#939]
I know that it's a goal of this project not to add any Parcel-specific config files, but is there any way that to set this up once and not have to pass the option every time?

If not, I think it's sorely needed.

**Comment by pierredavidbelanger** [comment]
I do not know specifically the answer to your question, but you can achieve mostly the same with the `"scripts"` section of the `package.json` file, like this:

```json
  "scripts": {
    "build": "parcel build --out-dir out www/index.html"
  }
```

Then, just `run` it:

```sh
$ npm run build
```

**Comment by kenmorechalfant** [comment]
@pierredavidbelanger That's pretty good, I suppose.

On a different note: Is there a "build" for development? It seems like that's sort of a missing option. I suppose it's not so bad to `watch` and then just `ctrl-c` but it seems like building for production should have been a flag and not the whole `build` command.

**Comment by pierredavidbelanger** [comment]
I guess you are searching for `parcel build --no-minify index.html` to build for "dev" and `parcel build index.html` to build for prod.

**Comment by kenmorechalfant** [comment]
This is really strange but now my output file name is some crazy random name:
`78bfe7508e2986e20ac4eb8ff6ea87bd.js`

**Comment by pierredavidbelanger** [comment]
The "crazy random name" is a hash, it is intended and it is useful to bust cache :)

**Comment by kenmorechalfant** [comment]
I figured as much. And I also figured out how to get back the normal name: I left off the `.js` in my command.

What's the reasoning for this behavior? I get the point of a hashed name but shouldn't it be an option and not sort of "hidden" by having to know to leave off the extension?

**Comment by pierredavidbelanger** [comment]
I am sorry, I am confused by your last comment.
I hope someone not newbe as me with parcel will be able to help you :)

**Comment by kenmorechalfant** [comment]
Or is that a bug? To be clear, this is the command I used:

`parcel build public/js/main.js -d public/dist`

And the output file name was also `main.js` as expected. Then, without the `.js` it gave me the hash name.

**Comment by pierredavidbelanger** [comment]
Oh I see, 

In the first command, you are building a specific file, this file is the entry point, the entry point file name is never a hash.

In the second command, you are building a folder, parcel will build this as a module (so it must contains an index.js).

I guess you already read the [Getting Started](https://parceljs.org/getting_started.html) section that explain very well the main use case. 

I suggest you [head over to the chat](https://github.com/parcel-bundler/parcel#community) if you have others questions like that (or feedbacks, or suggestions).

**Comment by DeMoorJasper** [comment]
I'll close this of as Parcel is currently a CLI tool (with an API) and can only be used using the cli (or a self-made script that uses the api)
So like @pierredavidbelanger already said u can use this to keep it stored
> ```json
>  "scripts": {
>    "build": "parcel build --out-dir out www/index.html"
>  }
>```

**Comment by muhammedMoussa** [comment]
> I'll close this of as Parcel is currently a CLI tool (with an API) and can only be used using the cli (or a self-made script that uses the api)
> So like @pierredavidbelanger already said u can use this to keep it stored
> 
> > ```json
> >  "scripts": {
> >    "build": "parcel build --out-dir out www/index.html"
> >  }
> > ```

i'm running parcle ``` ^2.0.0-alpha.3.2``` and got `error: unknown option `--out-dir'`

**Comment by mischnic** [comment]
Will be added back as `--dist-dir` in the next alpha: https://github.com/parcel-bundler/parcel/pull/4113
