### ISSUE TITLE
Parcel with electron typescript and rust?

### ISSUE THREAD

**Issue by knipferrc** [parcel-bundler/parcel#940]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
Bug

Just playing around with using typescript react electron and rust. Just a fun little learning project but when using rust code nothing will render in electron once the rust import is removed everything is fine. Here is my repo. This only happens on build. 

https://github.com/knipferrc/recode

### 🤔 Expected Behavior

Should render the production build

### 😯 Current Behavior

Nothing renders on build

### 🔦 Context

Render a production build in electron with typescript, react and rust.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel        |  1.6.2.
| Node         |  9
| npm/Yarn       | npm
| Operating System | OSX

**Comment by davidnagli** [comment]
Please fill out the rest of the issue template and provide the error that you’re getting

**Comment by mischnic** [comment]
I'm guessing you mean something like this:
```jsx
import {add} from "./add.rs";

const App = () => (
  <SplitPane split="vertical" defaultSize="20%">
    <div>File Tree: {add(1,3)}</div>
    <div>
      <CodeEditor />
    </div>
  </SplitPane>
)
```

http://webassembly.org/getting-started/developers-guide/:
>Finally, to actually run the program, we cannot simply open the HTML file in a web browser because cross-origin requests are **not supported for the file protocol scheme**. We have to actually serve the output files over HTTP.

As a workaround, put `require("electron").webFrame.registerURLSchemeAsPrivileged("file")` at the beginning of the main javascript bundle.

**Comment by knipferrc** [comment]
@mischnic That works like a charm. Thanks!! Is there a way to get that added automatically during build without having to manipulate the bundle every time?

**Comment by mischnic** [comment]
Currently not, you could write a plugin.

---
There seem to be more issues regarding electron: dynamic `imports` don't seem to work either (not even using `file://`, but with parcel's dev server):
```
Uncaught AssertionError: path must be a string
    at Module.require (module.js:512:3)
    at require (internal/module.js:11:18)
    at newRequire (http://localhost:1234/build/2da45210846b87bb3ce9a2cb109ed3bb.js:22:18)
    at localRequire (http://localhost:1234/build/2da45210846b87bb3ce9a2cb109ed3bb.js:48:14)
    at loadBundlesLazy (http://localhost:1234/build/2da45210846b87bb3ce9a2cb109ed3bb.js:115:28)
    at Object.require.3._bundle_loader (http://localhost:1234/build/2da45210846b87bb3ce9a2cb109ed3bb.js:184:26)
    at newRequire (http://localhost:1234/build/2da45210846b87bb3ce9a2cb109ed3bb.js:42:24)
    at require.6 (http://localhost:1234/build/2da45210846b87bb3ce9a2cb109ed3bb.js:69:5)
    at http://localhost:1234/build/2da45210846b87bb3ce9a2cb109ed3bb.js:74:3
```

**Comment by knipferrc** [comment]
Thank you so much for your help @mischnic, for now I went ahead and just created a little shell script to add it to the beginning of the file, but will look into creating a plugin to do this. Unless there is a better solution.
