### ISSUE TITLE
No named export when building a library with multiple targets

### ISSUE THREAD

**Issue by georapbox** [parcel-bundler/parcel#9414]
# 🐛 bug report

I'm building a library with multiple targets using Parce v2.10.3. More specifically I'm building a Custom Element (Web Component) and I would like to generate 2 different files. The one should export the class of the library and the other should export the class but also registers the custom element as a side effect.

The result is that only the second file has the named export of my class although it should also be included in the first one. The same configuration was working as expected with Parcel v2.9.3 or earlier.

I've also created a [repository](https://github.com/georapbox/reproduce-parcel-bug) that reproduces the issue.

## 🎛 Configuration (.babelrc, package.json, cli command)

Here's my `package.json` configuration:

```js
{
  "name": "my-counter",
  "version": "1.0.0",
  "module": "dist/my-counter.js",
  "type": "module",
  "targets": {
    "my-counter": {
      "context": "browser",
      "outputFormat": "esmodule",
      "source": "src/my-counter.js",
      "optimize": true,
      "isLibrary": true,
      "distDir": "dist",
      "engines": {
        "browsers": "> 0.5%, last 2 versions, not dead"
      }
    },
    "my-counter-defined": {
      "context": "browser",
      "outputFormat": "esmodule",
      "source": "src/my-counter-defined.js",
      "optimize": true,
      "isLibrary": true,
      "distDir": "dist",
      "engines": {
        "browsers": "> 0.5%, last 2 versions, not dead"
      }
    }
  },
  "scripts": {
    "build": "parcel build",
  },
  "devDependencies": {
    "parcel": "~2.10.3"
  }
}
```

## 🤔 Expected Behavior

The expected behavior is that both the generated files should contain a named export of my class.

## 😯 Current Behavior

The current behavior is that my named export is included only in one of the generated files instead of being present in both of them. So, when I'm trying to import it I get the following error:

```
Uncaught SyntaxError: The requested module './dist/my-counter.js' does not provide an export named 'MyCounter'
```

## 💁 Possible Solution

Not a suggestion actually, but from what I've noticed, is that if I use only one target, the generated file does have the named export.

## 🔦 Context

I'm building a Custom Element (Web Component) `<my-counter>` as library and I would like to generate 2 files (ES modules), one file is `my-counter.js` which contains the definition of the custom element (`MyCounter` class) and just export it. The second file `my-counter-defined.js` is just importing `MyCounter` class and exports it again but also registers the custom element as a side effect. This way, the end user can choose themselves if they want to automatically register the element or do it at a later point like this:

```js
import { MyCounter } from './dist/my-counter.js';

// Register the Custom Element...
MyCounter.define();
```

To achieve the above, I'm using 2 targets as shown above in the `package.json` configuration.

The issue is that from the generated files, the `my-counter.js` does not have the named export and therefore the end user cannot import it when consuming the module. On the other hand, the second file `my-counter-defined.js` includes the named export as expected. 

## 💻 Code Sample

Here is a repository with a reproduction of the behavior: https://github.com/georapbox/reproduce-parcel-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel | v2.10.3 |
| Node | v18.7.0, v20.8.1 |
| npm | v8.15.0, v10.1.0 |
| Operating System | macOS Ventura Version 13.4 |

**Comment by OdapX** [comment]
Running through the same issue, any updates on this ?
