### ISSUE TITLE
[v.2.10.3] .posthtmlrc config yields ts(1005) errors

### ISSUE THREAD

**Issue by christopherball** [parcel-bundler/parcel#9427]
# 🐛 bug report

Followed the instructions at https://parceljs.org/languages/html/#posthtml to add support for the posthtml plugin by creating a `.posthtmlrc` file.  While my plugin works correctly (in my case, using https://github.com/andrey-hohlov/posthtml-inline-svg), I can't for the life of me either _**resolve or silence these ts(1005) errors**_ (which appear to be related to parcel's native typescript).  I am using out of the box configurations for parcel itself.  These errors are present due to the format of the file itself, not the content of the specific plugin.  I've confirmed this by copy pasting the default example from the first link I provided above (see 2nd screenshot).

## 💻 Code Sample

![image](https://github.com/parcel-bundler/parcel/assets/5790394/a4c9d69d-b1fe-48a8-9c39-d63189babbbd)

![image](https://github.com/parcel-bundler/parcel/assets/5790394/0fefff66-2717-42cf-bf91-5830d8de7892)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.10.3
| Node             | 20.9.0
| npm/Yarn         | 10.1.0
| Operating System | Mac Sonoma 14.1.2

**Comment by christopherball** [comment]
While it'd be nice to have this as an error-free implementation option, as a workaround to entirely avoid using a plugin for SVG injection, I've gone with the following typescript solution (in case anyone else happens upon this need in the future):

```js
import svg from "bundle-text:../assets/image.svg";
...
...
document.querySelector<HTMLElement>("div").innerHTML = svg;
```

And then in your own parcel.d.ts, add the following to silence typescript complaints about the import:
```js
declare module "*.svg" {
  const classes: string;
  export default classes;
}
```

**Comment by mischnic** [comment]
These ts errors have nothing to do with Parcel, some plugin you have installed must be causing that.
You could also try to use the `exclude` option in tsconfig.json to make Typescript ignore that posthtmlrc

**Comment by christopherball** [comment]
Sadly I tried the exclude option also before posting.  I have a minimal set of extensions installed.  Best guess is "prettier" is the culprit.  Thanks for the ideas!
