### ISSUE TITLE
Hot reload doesn't work for an empty HTML page without external CSS/JS imports

### ISSUE THREAD

**Issue by RIP21** [parcel-bundler/parcel#943]
### 🐛 bug report

No files or configs

### 🤔 Expected Behavior

I have empty HTML without any external resources (such as local CSS files or JS). When I change it and save I should get an immediate update in the browser without refresh while in dev mode.

### 😯 Current Behavior

I change anything in the HTML file, it gets rebuilt but not refreshed automatically in the browser. I need to click refresh.

### 💁 Possible Solution

When I add any import. For example <link> to the CSS external local file and then refresh the page once, all changes to HTML start to immediately displayed on saving without a need to press refresh

### 💻 Code Sample

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<p style="color: red">Hello world</p>
</body>
</html>
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | latest to date
| Node             | 8.9.3
| Yarn         | 1.5
| Operating System | Mac OS High Sierra

**Comment by mischnic** [comment]
There is no javascript bundle to append the HMR runtime to.
https://github.com/parcel-bundler/parcel/blob/420ed63ed18c6a09e8b25754d0142b3b87ebcd71/src/packagers/JSPackager.js#L185-L191

We would have to inject a script tag into the html file.

**Comment by RIP21** [comment]
Glad that my bug contribution is not false positive :) Waiting for the fix ;)

**Comment by RIP21** [comment]
@vsui I think you could. It's quite annoying.

**Comment by cacheflow** [comment]
I'll take this on if it's still open @RIP21 @vsui.

**Comment by akselinurmio** [comment]
This sure needs to be fixed. I’m not familiar with the internals of Parcel, but I guess that to support auto reloading without JS, we’d have to:

1. create a browser module including HMR runtime, and then
2. inject it to the HTML.

[Browsersync](https://github.com/Browsersync/browser-sync) injects its client script after the opening `<body>` tag, would that be wise to do here too?

**Comment by MegaJSDeveloper** [comment]
## 💁 Possible Solution

if page has no one scripts, you must automatically add reload helper script, to the beginning of the head element, like:

```html
<script id="__parcel__helper__">
  /* code */
  /* code */
  /* code */

  // clear html from helper script tag, just in case
  var helperScriptElement = document.getElementById('__parcel__helper__')
  helperScriptElement.parentNode.removeChild(helperScriptElement);
</script>

<title> e.t.c. </title> 
```

**Comment by AleksueiR** [comment]
I finally "solved" this by adding a [live.js](https://livejs.com) script into the `*.pug` pages. It does a good job at reloading the pages--might not be as fast as Parcel's hmr, but it works.

```pug
script(src="https://livejs.com/live.js#html")
```

Don't forget to remove this line when building for production.

**Comment by kud** [comment]
Interested by this feature.

**Comment by WickyNilliams** [comment]
I am still seeing HTML not be reloaded whether i have a script or not. I assume this shouldn't be the case?

**Comment by joelhickok** [comment]
> I am still seeing HTML not be reloaded whether i have a script or not. I assume this shouldn't be the case?

Me too.  JS reloads happen from my entry file, but if I modify the index.html file the page does NOT reload.  Parcel v2.

**Comment by devongovett** [comment]
Make sure you're on the latest nightly release. Some fixes for this went in quite recently

**Comment by chtenb** [comment]
I don't see any reloading of my HTML either. According to NPM I'm on version `parcel@2.0.0-nightly.725`.

**Comment by chtenb** [comment]
FWIW: the livejs solution also does not work. Even with my devtools open and "Disable Cache" enabled, my browser (chrome) keeps showing the outdated html page. And I have verified that the html in the `dist` directory changed.

**Comment by cstuncsik** [comment]
Using `pug` with a conditional empty javascript file also works

```pug
doctype html
html
  head
    meta(chrset='utf-8')
    meta(name='viewport', content='width=device-width, initial-scale=1')
    meta(http-equiv='X-UA-Compatible' content='ie=edge')
    link(rel='stylesheet', href='./style.scss')
    if process.env.NODE_ENV === 'development'
      // just to make HMR work
      script(type='module', src='./index.js')
    title Page title
  body
