### ISSUE TITLE
Image transformer properties `width` and `height` do not work when they come after `as=webp`

### ISSUE THREAD

**Issue by Fruitsalad** [parcel-bundler/parcel#9448]
Here's a minimal reproduction with the bug annotated. Note that this is Pug code, but I expect that it's reasonably understandable how this compiles into HTML.
```pug
doctype html
html(lang="en")
  head
    meta(charset="utf-8")
    title Parcel image size bug
  body
    // These two work as expected:
    img(src="./large_image.jpg?height=100&as=webp")
    img(src="./large_image.jpg?width=100&as=webp")
    // These two ignore the size property and do not resize the original image:
    img(src="./large_image.jpg?as=webp&height=100")
    img(src="./large_image.jpg?as=webp&width=100")
```
I have not tested this with other image formats than webp, so it might also affect other formats.

Affects parcel 2.10.2 & 2.10.3

**Comment by Fruitsalad** [comment]
On closer inspection I made a mistake about where the bug lies: The first two `img` tags also do not work. The problem is that only the first property seems to be evaluated so anything behind the ampersand is ignored.

**Comment by pieter-experience-republic** [comment]
Possibly redundant but I have the same issue using plain HTML:

```
<li>
   <figure>
      <img src="./assets/img/image.jpeg?as=webp&height=270&quality=90" />
   </figure>
</li>
```

Only the first query parameter gets evaluated, the rest gets ignored. So in my example I end up with an image that is converted to webp but not resized nor compressed. Changing the order of the query parameters leads to the same problem, only the first parameter gets evaluated.

I'm using:

```
 "parcel": "^2.10.3",
 "sharp": "^0.31.1"
 ```
 
 The issue occurs both in development mode and build mode.

**Comment by pieter-experience-republic** [comment]
@Fruitsalad, the issue I had was that I was using a task runner that transformed the `&` character into `&amp;`, since you are using Pug, it's possible you have the same issue. Maybe there is a Pug configuration that turns off the transformation.

**Comment by sdedovic** [comment]
I am having this issue too.

Only the first query string parameter is handled properly, so if I switch the order, `foo.png?width=200&as=webp` vs `foo.png?as=webp&width=720` it will alternate between a 200x200 PNG and a 1080x1080 WebP, respectively.

**Comment by sdedovic** [comment]
> @Fruitsalad, the issue I had was that I was using a task runner that transformed the `&` character into `&amp;`, since you are using Pug, it's possible you have the same issue. Maybe there is a Pug configuration that turns off the transformation.

I can confirm this is the issue. See the Pug documentation: [Attributes - Unescaped Attributes](https://pugjs.org/language/attributes.html#unescaped-attributes)

> By default, all attributes are escaped—that is,special characters are replaced with escape sequences—to prevent attacks (such as cross site scripting). If you need to use special characters, use != instead of =.

So by switching
```diff
- img(alt="" src="assets/image.png?as=webp&width=200")
+ img(alt="" src!="assets/image.png?as=webp&width=200")
```

The problem goes away.

**Comment by Fruitsalad** [comment]
I haven't worked with Parcel lately so I haven't taken the time to confirm the solution, but I trust upon it that it's fine. Closing this issue.
