### ISSUE TITLE
JSX runtime is not automatically injected when using pnpm workspaces

### ISSUE THREAD

**Issue by polc** [parcel-bundler/parcel#9452]
# 🐛 bug report

I'm using `pnpm` workspaces with the following setup : 

```
package.json
pnpm-workspace.yaml
packages
  my-app
    package.json
  my-component-library
    package.json
```

 The packages `react` and `react-dom` are declared in the root `package.json`  but not in `my-app/package.json` nor in `my-component-library/package.json`. It's usefull so `my-app` and `my-component-library` can share the same `react` version.

I've no problems when running `pnpm parcel` in `./packages/my-app`, the React app is running well. However, when building the app for production : `pnpm parcel build`, I got the following error :  **`Uncaught ReferenceError: React is not defined`**.

I found 2 ways to resolve the issue, either : 
- Add `react` back to `my-app/package.json` dependencies

- Add a `tsconfig.json` in the root foler with the following content : 
```
{
  "compilerOptions": {
    "jsx": "react-jsx",
  }
}
``` 

## 💁 Possible Solution

The problem seems to lie in https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/js/src/JSTransformer.js#L159, 
the function `config.getPackage()` doesn't seem to take the workspace dependencies into account. 

There may be another problem here : https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/js/src/JSTransformer.js#L192, where the function `config.getConfigFrom<TSConfig>()` seem to take into account only the workspace root `tsconfig.json`, and not the local one `./packages/my-app/tsconfig.json`.
 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.1469 (for the `--watch-dir` option)
| Node             | v21.4.0
| pnpm         | 8.12.1
| Operating System | Arch Linux (btw)

**Comment by devongovett** [comment]
I think react should be declared in any package where it is used, not only the monorepo root. If you were to publish that package, and it didn't have react declared, it would not work. Even if you don't plan to publish it, packages should be self contained.

**Comment by polc** [comment]
Thanks for responding ! I found it useful to keep the same `react` version by using the root `package.json`, but I'm not sure it's the intended usage.

I also found [syncpack](https://jamiemason.github.io/syncpack/command/fix-mismatches/) which seems to give me the same result, just with one more step. Thanks !
