### ISSUE TITLE
[webextensions] Parcel doesn't accept manifest v3 with both `service_worker` and `scripts`

### ISSUE THREAD

**Issue by fregante** [parcel-bundler/parcel#9458]
# 🐛 bug report

Parcel supports _either_ `background.service_worker` or `background.scripts`, but not both.

Firefox supports `background.scripts`, but warns that it doesn't support the other one.

Chrome won't load a manifest that has `background.scripts`

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
	"extends": "@parcel/config-webextension"
}
```
```json
{
	"name": "Awesome Extension",
	"version": "0.0.0",
	"description": "An awesome new browser extension",
	"manifest_version": 3,
	"background": {
		"service_worker": "background.js",
		"type": "module",
		"scripts": [ "background.js" ]
	}
}
```

## 🤔 Expected Behavior

Parcel should build both, so that the extension can (eventually) be loaded in both browsers

## 😯 Current Behavior

```js
🚨 Build failed.

@parcel/transformer-webextension: Invalid Web 
Extension manifest

  ./source/manifest.json:36:3
    35 |   "background": {
  > 36 |     "service_worker": "background.js",
  >    |     ^^^^^^^^^^^^^^^^ Possible values: "page", "persistent"
  > 37 |     "type": "module",
  >    |     ^^^^^^ Possible values: "page", "persistent"
    38 |     "scripts": [ "background.js" ]
    39 |   }
```

## 💁 Possible Solution

Allow and build both pages, ideally build a single `background.js` file without generating two separate bundles.

## 🔦 Context

Chrome has been open to allowing the `scripts` property in the manifest without throwing, however this hasn't been fixed in several months. It would be great for Parcel to start supporting it as soon as possible so that we don't have to wait any longer once Chrome supports it.

## 💻 Code Sample

1. Check this out https://github.com/fregante/browser-extension-template
2. Add `"scripts": ["background.js"],` to its manifest 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.10.3
| Node             | 20
| npm/Yarn         | 10
| Operating System | macOS

**Comment by fregante** [comment]
Additional relevant threads:

- Other report: https://github.com/parcel-bundler/parcel/issues/8785#issuecomment-1872618090
- Intent to ship in Chrome 121 (Tue, Jan 23, 2024) https://github.com/w3c/webextensions/issues/282#issuecomment-1786857524
- This bug blocks me: https://github.com/fregante/browser-extension-template/issues/78#issuecomment-1848921642

**Comment by fregante** [comment]
Chrome 121 is out and this is preventing me from building cross-browser MV3 extensions unfortunately.

**Comment by zopieux** [comment]
Per https://stackoverflow.com/a/78088358/180709 both are valid and this *finally* allows truly cross-browser extension packaging with Parcel.

Please allow both keys.

**Comment by tdriley** [comment]
> both are valid and this _finally_ allows truly cross-browser extension packaging with Parcel.

This is great news!

Official docs from Chrome about their MV3 manifest accepting the MV2 background values without erroring: https://developer.chrome.com/docs/extensions/whats-new#background-key-warning

**Comment by tjarbo** [comment]
Do you have any ETA when these changes will be released?
