### ISSUE TITLE
Parcel's branch removal doesn't combine with TypeScript's import elision

### ISSUE THREAD

**Issue by lukaw3d** [parcel-bundler/parcel#9463]
# 🐛 bug report

Parcel's branch removal does not behave the same as manually removing a dead branch in TypeScript:
```ts
import * as constants from '@parcel/cache/lib/constants';

if (process.env.NODE_ENV !== 'production') {
  console.log(constants)
}
```

## 🎛 Configuration (.babelrc, package.json, cli command)

Default / see https://github.com/lukaw3d/parcel-branch-removal-with-typescript-import-elision-bug

## 🤔 Expected Behavior

The result should be the same as manually removing the branch and building
```ts
import * as constants from '@parcel/cache/lib/constants';
```
this builds into empty file
```js
```

So: Expected Parcel to remove dead branch, and then TypeScript to remove (elid) unused imports (and reduce bundle size)

## 😯 Current Behavior

Builds into
```js
var e;Object.defineProperty(e={},"__esModule",{value:!0}),e.WRITE_LIMIT_CHUNK=void 0,e.WRITE_LIMIT_CHUNK=2147483648;
```

So I think TypeScript first tries to remove unused imports, but they're still used

```ts
import * as constants from '@parcel/cache/lib/constants';
if (process.env.NODE_ENV !== 'production') {
    console.log(constants);
}
```

and then Parcel removes the branch, but the import remains

```ts
import * as constants from '@parcel/cache/lib/constants';
```

## 💁 Possible Solution

Difficult solution: Add an additional implementation of branch removal in an earlier step (TypeScript transformer), but then it would have to evaluate the condition written in TypeScript.

Easy solution: Add a warning in documentation, and suggest using a dynamic import inside the condition:
```ts
if (process.env.NODE_ENV !== 'production') {
    import('@parcel/cache/lib/constants').then(({constants}) => console.log(constants));
}
```

## 🔦 Context

> How has this issue affected you? What are you trying to accomplish?

I'm trying to reduce the bundle size by removing a dependency based on env variable.

## 💻 Code Sample

https://github.com/lukaw3d/parcel-branch-removal-with-typescript-import-elision-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.10.3 |
| Node             |
| npm/Yarn         |
| Operating System |

**Comment by mischnic** [comment]
> 🤔 Expected Behavior

It's unfortunately not that easy. For that import to be completely ignored, the file it references (`constants`) needs to be sideEffect free: https://parceljs.org/features/scope-hoisting/#side-effects

With that, it will work as you expect.

**Comment by lukaw3d** [comment]
TypeScript import eliding is a separate behavior from treeshaking based on sideEffects. That's why these build differently:
```ts
import * as constants from '@parcel/cache/lib/constants';
if (process.env.NODE_ENV !== 'production') {
  console.log(constants)
}
```
vs
```ts
import * as constants from '@parcel/cache/lib/constants';
```

**Comment by lukaw3d** [comment]
I just tried vite and it has the same inconsistency, so maybe others expect it already :shrug: 
```ts
import ReactDOM from 'react-dom/client'; // import not elided
if (!import.meta.env.PROD) { // dead branch removed
  console.log(ReactDOM);  // dead branch removed
} // dead branch removed
// 141kb
```
vs
```ts
import ReactDOM from 'react-dom/client'; // import is elided
// 0.7kb
```

**Comment by mischnic** [comment]
Exactly, and furthermore:

> TypeScript automatically elides (does not emit) imports that are only used in type positions and exports that only refer to types

So it sounds like this isn't true for values, only types. (And I don't know what swc actually does)
