### ISSUE TITLE
Parcel Build Command Incorrectly Picks Expo Entry Point for Chrome Extension Project

### ISSUE THREAD

**Issue by mikelgarciaurbina** [parcel-bundler/parcel#9480]
# 🐛 bug report

## 🎛 Configuration (.babelrc, package.json, cli command)

I am working on an Expo app and trying to add a Chrome extension within the same project in src/extension. I use Parcel for building the extension, and it works fine with the start-extension script, but the build-extension script doesn't recognize the specified entry point and defaults to the Expo app entry point from package.json.

Here is the relevant part of my package.json:
```json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start-extension": "parcel serve src/extension/index.html",
    "build-extension": "parcel build src/extension/index.html"
  },
  "alias": {
    "react-native": "react-native-web"
  },
}
```

## 🤔 Expected Behavior

The build-extension script should use src/extension/index.html as the entry point for building the Chrome extension.

## 😯 Current Behavior

When running yarn build-extension, Parcel does not use src/extension/index.html as the entry point and instead defaults to the Expo app entry point defined in package.json. If I remove "main" from package.json everything works fine.

## 💁 Possible Solution

Not sure of the solution, but it seems like a potential issue with how Parcel resolves entry points in the build command.

## 🔦 Context

I want to build a Chrome extension within my Expo app project to reuse components and logic, but this issue is preventing a successful build of the extension.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.11.0
| Node             | v18.18.1
| npm/Yarn         | 9.8.1
| Operating System | macOS 14.2.1

**Comment by mischnic** [comment]
https://parceljs.org/features/targets/#library-targets

> To make Parcel ignore one of these fields, specify false in the targets field.
> ```json
> {
>   "main": "unrelated.js",
>   "targets": {
>     "main": false
>   }
> }
> ```

**Comment by mikelgarciaurbina** [comment]
It works! thank you @mischnic
