### ISSUE TITLE
Webstorm prompt grammatical errors when i use 'import()' for code splitting 

### ISSUE THREAD

**Issue by annnhan** [parcel-bundler/parcel#95]
webstorm Prompt: “'from' expected”. 

It is suggested to support AMD writing. For example:

    require('./page', function (page) {
       // do something ...
    })

or:

    require('./page').then(function (page) {
       // do something ...
    })

**Comment by chee** [comment]
@annnhan i tried this in Webstorm, and i can't recreate it.

what version of Webstorm are you using?

have you got the correct Language Version selected for JavaScript in the Languages & Frameworks section in your settings?

dynamic import, `import()`, is a real life stage 3 proposal https://github.com/tc39/proposal-dynamic-import

**Comment by devongovett** [comment]
This sounds like an editor issue. The `import()` syntax is not specific to parcel.
