### ISSUE TITLE
🤔 Bundle visualiser plugin

### ISSUE THREAD

**Issue by gregtillbrook** [parcel-bundler/parcel#950]
Hiya, Ive created a plugin to visualise bundles as a treemap (like webpack-bundle-analyzer but for parcel). It's only a basic MVP atm but what's there should still be useful.

https://www.npmjs.com/package/parcel-plugin-bundle-visualiser

**Comment by davidnagli** [comment]
Cool! Feel free to add this to parcel-bundler/awesome-parcel :)
