### ISSUE TITLE
Please provide an example how to console.log "Hello World" through Plugin API [docs]

### ISSUE THREAD

**Issue by projektorius96** [parcel-bundler/parcel#9502]
# 🙋 feature request

I was scrolling the docs for Parcel Plugin development, however Parcel docs provide only generic example how to extend `.parcelrc` . It's like Google docs for Chrome extension development without a simplest example how to make one, just the reference. I simply don't get it, guys, how do you think we will now how to put things in a right place a plugin to work ? We desperately need an example even the simplest one !

## 🤔 Expected Behavior

Consider your own provided example, but a little bit modified, just as follows:

```json5
// .parcelrc
{
  "extends": ["@parcel/config-default", "@placeholder/hello-world"]
}
```

## 😯 Current Behaviour

N/A

## 💁 Possible Solution

N/A

## 🔦 Context

N/A

## 💻 Examples

Following [Parcel API docs](https://parceljs.org/features/parcel-api/) I managed to find this, just at the top of the page as follows:

```js
import {Parcel} from '@parcel/core';

let bundler = new Parcel({
  entries: 'a.js',
  defaultConfig: '@parcel/config-default'
});
```

Judging the code above, our so called `@placeholder/hello-world` plugin is merged into `@parcel/config-default` . Perhaps I get that part right, but then my question is as follows:

**How to export** `@placeholder/hello-world` **and what signature to follow to get that Hello World printed but through means of Plugin API** ?  In other words, I don't see how `@placeholder/hello-world` reflects in the codebase, simply put –  no example ! 

I am kindly requesting to update the docs with the example explaining how to hook our `@placeholder/hello-world` and what entry point to use (if any) in Parcel API config.

Cheers ♥

**Comment by projektorius96** [comment]
Inactive, so closing. Please re-open, if you need.

**Comment by mischnic** [comment]
In "defaultConfig" you should specify a parcelrc file or a config package as described on https://parceljs.org/plugin-system/configuration/.

The individual plugins are then specified in there
