### ISSUE TITLE
Q: How to keep the same output directory structure as the source, after processing?

### ISSUE THREAD

**Issue by pentool** [parcel-bundler/parcel#951]
Hello,

When I have an HTML file with an image tag `<img src="img/city.jpg">`, after processing parcel will copy the image from the `img` folder into the root of the `dist` folder. Is there a way to tell parcel to keep the structure the same as in the source folder? (eg copy the image from `src/img` into `dest/img` as opposed to just dump it into the root).

This goes for other asset files (eg css/scss) as well.

Thanks.

**Comment by DeMoorJasper** [comment]
Currently it isn't possible to do so, see #872 for the new parcel naming strategy that is being discussed, feel free to read through it and append to that.

**Comment by equinusocio** [comment]
@DeMoorJasper I have the same issue but i can'd find a solution from #872

**Comment by LauraSophieM** [comment]
It's 2019. Is thery a solution now? Having the same problem over here...

**Comment by rifat-H** [comment]
> It's 2019. Is thery a solution now? Having the same problem over here...

i dont think so... wait for verson 2.0

**Comment by spsaucier** [comment]
Is this resolved in 2.0 then?

**Comment by FaigBagirov** [comment]
no changes yet?

**Comment by MichaelChistyakov** [comment]
Any news?
