### ISSUE TITLE
Re-exporting CJS to ESM causes broken build

### ISSUE THREAD

**Issue by 3x071c** [parcel-bundler/parcel#9513]
# 🐛 bug report

Parcel appears to create a bad bundle when re-exporting in certain situations. In my case, I noticed it with the [vercel/arg](https://github.com/vercel/arg) package, a simple CommonJS module. Attempting to re-export from my own (es module) app leads to bad output:

![image](https://github.com/parcel-bundler/parcel/assets/87198856/106bd75f-233b-462a-9d87-e022149d5640)

## 🎛 Configuration (.babelrc, package.json, cli command)

```jsonc
// package.json
{
	"name": "parcel-9513",
	"type": "module",
	"engines": {
		"node": ">= 18"
	},
	"scripts": {
		"build": "parcel build --no-cache",
		"start": "node ."
	},
	"main": "dist/index.js",
	"dependencies": {
		"arg": "5.0.2"
	},
	"devDependencies": {
		"parcel": "2.11.0",
		"typescript": "5.3.3"
	},
	"source": "src/index.ts"
}
```
```ts
// src/arg.ts
export { default as getArgs } from 'arg';
```
```ts
// src/index.ts
import { getArgs } from './arg';

const x = getArgs({ ... });
console.log(x);
```

## 🤔 Expected Behavior

No broken output:

```js
import $lSd6q$arg from "arg";

const $db641dfff82f38df$var$x = (0, $d8366e8ecbd1714a$re_export$getArgs)({
    "--help": Boolean
});
console.log($db641dfff82f38df$var$x);
```
^--- `$lSd6q$arg` is unused and was apparently rewritten to `$d8366e8ecbd1714a$re_export$getArgs` (which does not exist)

## 😯 Current Behavior

Since the bundle is not referencing the correct import variable, this is all I'm getting:

```
ReferenceError: $...$re_export$getArgs is not defined
    at ...

Node.js v21.5.0
```

## 💻 Code Sample

I have created a simple [reproduction](https://github.com/3x071c/parcel-9513) of the issue.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel             | latest (2.11.0)
| Node             | 21.5.0
| OS             | macOS

**Comment by ggzui** [comment]
+1
