### ISSUE TITLE
Support specifying custom conditions for resolving conditional imports/exports

### ISSUE THREAD

**Issue by jbms** [parcel-bundler/parcel#9514]
# 🙋 feature request

It would be very useful for Parcel to support specifying custom conditions to use when resolving conditional imports, as supported by esbuild, vite, webpack, tsc:

https://esbuild.github.io/api/#conditions
https://webpack.js.org/configuration/resolve/#resolveconditionnames
https://vitejs.dev/config/shared-options#resolve-conditions
https://www.typescriptlang.org/tsconfig#customConditions

Ideally, the list of conditions could be specified either by a config file or on the command line.

**Comment by jbms** [comment]
I was able to implement this as a plugin in a hacky way that nonetheless seems to work:

```javascript
import { Resolver } from "@parcel/plugin";
import {
  dependencyToInternalDependency,
  getPublicDependency,
} from "@parcel/core/lib/public/Dependency.js";
const CONFIG = Symbol.for("parcel-plugin-config");

const ENV_VAR = "PARCEL_CONDITIONS";

export default new Resolver({
  async loadConfig(args) {
    const { options, config } = args;
    config.invalidateOnEnvChange(ENV_VAR);
    config.invalidateOnBuild();
    const conditions = (process.env[ENV_VAR] ?? "").split(",");
    const baseResolver = (
      await options.packageManager.load(
        "@parcel/resolver-default",
        options.projectRoot,
      )
    ).default[CONFIG];
    const baseConfig = await baseResolver?.loadConfig(args);
    return { baseResolver, baseConfig, conditions };
  },

  async resolve(options) {
    let { dependency } = options;
    if (dependency != null) {
      const { config } = options;
      const dep = options.dependency;
      const internalDep = dependencyToInternalDependency(dep);
      const newInternalDep = {
        ...internalDep,
        customPackageConditions: [
          ...(internalDep.customPackageConditions ?? []),
          ...config.conditions,
          "module",
          dep.specifierType === "commonjs" ? "require" : "import",
        ],
      };
      dependency = getPublicDependency(newInternalDep, options.options);
    }
    return await options.config.baseResolver.resolve({
      ...options,
      dependency,
      config: options.config.baseConfig,
    });
  },
});
```

**Comment by devongovett** [comment]
You could use the `@parcel/node-resolver-core` package to do this. The default resolver uses the same library internally: https://github.com/parcel-bundler/parcel/blob/v2/packages/resolvers/default/src/DefaultResolver.js. If you copy that code as a starting point and modify it that should be a little cleaner at least.

**Comment by jbms** [comment]
For some context, I am trying to use package conditions similarly to cargo features.  In particular, I have a library that supports various data formats and protocols, and I'd like users of the library to be able to select which of these to support when their own application is bundled, as opposed to fixing it when the library itself is published.  Normally a library might simply enable each format by having the user import a module, which takes care of registering support in a global registry somehow.  However, the complication is that my library makes use of 2 different web workers in addition to the portion intended to run in the main UI thread, and supporting the data format requires importing some modules in each of the web worker kinds as well as the main thread.  Therefore, the solution I have is to define subpath imports like "#format/xxx/main", "#format/xxx/worker1", "#format/xxx/worker2" that map to either the real implementation or an empty module depending on the conditions that are set.  Then the main thread always imports "#format/xxx/main" for each format and similarly the workers.

> You could use the `@parcel/node-resolver-core` package to do this. The default resolver uses the same library internally: https://github.com/parcel-bundler/parcel/blob/v2/packages/resolvers/default/src/DefaultResolver.js. If you copy that code as a starting point and modify it that should be a little cleaner at least.

Thanks, I had taken a look at that file but I didn't think of just using `@parcel/node-resolver-core` directly --- I can see that it would be more straightforward.

A few questions:
- I have to synthesize some of the default conditions, including ones that depend on how the module is imported, when overriding the conditions.  It would be nice if that could be avoided, although ultimately not that big of a deal.
- It seems that this could potentially be added as an option to the default resolver, since it would be a relatively minor addition.  However, the existing configuration of the default resolver happens only through package.json and can't be overridden through the Parcel API.  Given the nature of the single existing option that is not really an issue but for conditions it would be important to be able to build with multiple configurations.
- Another plugin might also need to resolve modules, and therefore also make use of node-resolver-core or the default resolver to do so, since there isn't, as far as I can see, a way to ask Parcel to resolve a path using whatever resolver plugins have been configured.  That plugin would end up not using the extra conditions.
- There are "expected content key to exist" errors if I don't call `config.invalidateOnBuild()` but I'm not sure why.
