### ISSUE TITLE
Q: Is it possible to keep output file names the same as the source?

### ISSUE THREAD

**Issue by pentool** [parcel-bundler/parcel#952]
Hello,

After processing the files, parcel renames them with hex names (js, css, images, etc) in the `dist` folder. Is it possible to keep the original file names (as they are named in the `src` folder), and if so how?

Thanks.

**Comment by DeMoorJasper** [comment]
Currently it isn't possible to do so, see #872 for the new parcel naming strategy that is being discussed, feel free to read through it and append to that.
