### ISSUE TITLE
Live linting ?

### ISSUE THREAD

**Issue by Sharlaan** [parcel-bundler/parcel#953]
Hi, Parcel is awesome but i'm missing live linting-on-save for my dev experience.

I found integration of eslint/tslint in precommit, but apparently it does not work on save (without installing anything more than Parcel itself), maybe i missed something ?

If not, would it be possible to integrate linting-on-save into the zero-config-Parcel ?

**Comment by DeMoorJasper** [comment]
We are no big fan of this feature as this is more an IDE feature than bundler feature, there is a plugin for this somewhere

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by davidnagli** [comment]
Ya I agree with @DeMoorJasper, this is beyond the scope of Parcel as a bundler...

But it would be REALLY awesome if someone would make a tool that would easily orchestrate the bundler, linter, test runner, etc.

**Comment by Sharlaan** [comment]
i made [this shareable eslint-config](https://github.com/Sharlaan/eslint-config-sharlaan)

At first glance it seems to work flawlessly alongside Parcel

**Comment by jaredscheib** [comment]
What do y'all think about a config option for something like a callback function in the parcel config, where we could simply give an npm command to run on (re)build? That way no plugin is necessary. Does this exist? We're blocked on switching to Parcel from Webpack until we can get TSLint output on each (rebuild)/save, and a precommit hook isn't ideal.

**Comment by jaredscheib** [comment]
After further exploration, I've revised my thinking and no longer believe that the build process should run linters or type-checkers. Thanks again!
