### ISSUE TITLE
react-refresh dependency is locked at v0.9.0

### ISSUE THREAD

**Issue by jboler** [parcel-bundler/parcel#9531]
# 🐛 bug report

Package `react-refresh` is locked at v0.9.0 which was released in 2020. v0.14.0 is available which was released in 2022.

See https://github.com/parcel-bundler/parcel/blob/v2/packages/runtimes/react-refresh/package.json#L26

Is there any reason this can't be upgraded? Just calling it out in case it's accidentally version locked.

**Comment by mischnic** [comment]
That is indeed a good question: if there were breaking changes between 0.9 and 0.14 that affect the Parcel usage in
- https://github.com/parcel-bundler/parcel/blob/v2/packages/runtimes/react-refresh/src/ReactRefreshRuntime.js
- https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/react-refresh-wrap/src/ReactRefreshWrapTransformer.js
- https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/react-refresh-wrap/src/helpers/helpers.js

**Comment by jboler** [comment]
Should I not be using react-refresh v0.14.0? I've been using it for over a year and haven't noticed a problem. I've been doing this in package.json:
```json
  "resolutions": {
    "react-refresh": "0.14.0"
  },
```
How do you expect the incompatibility show itself? I'm using Parcel v2.11.

**Comment by mischnic** [comment]
It's a semver major version change, so technically there could be breaking API/behaviour changes 🤷 

> How do you expect the incompatibility show itself? 

I suspect there might be some runtime error if some API changed/maybe lost updates/...

**Comment by jboler** [comment]
I believe in [semver](https://semver.org/) that `0.9.0` to `0.14.0` is just a minor version update so all changes should be backwards compatible. Parcel should be able to update to `0.14.0` no problem.

**Comment by mischnic** [comment]
No, there are special rules for `0.x.x`: https://jubianchi.github.io/semver-check/#/^0.9.0/0.14.0
Otherwise, Yarn/npm would already give you `0.14.0` even without having to override via `resolutions`.

**Comment by jboler** [comment]
I did not know of the special rule for `0.x.x` - good to know! 

I looked at the `react-refresh` diff for `git diff f021a983..5cc2487e -- ./src/*.js` (0.9-0.14) and the changes don't look like they affect Parcel - I couldn't say definitively tho. I'll leave this diff here because I can't get GH to compare 2 commits for just 1 directory: [react-refresh-f021a983-5cc2487e.patch](https://github.com/parcel-bundler/parcel/files/14890990/react-refresh-f021a983-5cc2487e.patch)
