### ISSUE TITLE
@parcel/transformer-css: Unknown at rule: @apply

### ISSUE THREAD

**Issue by jveLebreault** [parcel-bundler/parcel#9533]
# 🐛 bug report

Tailwindcss @apply directive is not being recognized by @parcel/transformer-css

## 🎛 Configuration (.babelrc, package.json, cli command)

```sh
npx parcel src/index.html
```

## 🤔 Expected Behavior

@apply directive should be passed to tailwind so it gets properly applied

## 😯 Current Behavior

The following message is logged to the console:

@parcel/transformer-css: Unknown at rule: @apply

## 🔦 Context

The rules should be passed to tailwindcss so the rules can be inlined.

## 💻 Code Sample

[Repo with reproducible bug ](https://github.com/jveLebreault/parcel-bug-report)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.11
| Node             | v18..19.0
| npm/Yarn         | node v18.19.0
| Operating System | ubuntu jammy (22)

**Comment by chi11ax** [comment]
I have this same issue too.

index.pcss:
```
@import "tailwind-directives.pcss";
@import "main.pcss";
```

tailwind-directives.pcss:
```
@tailwind base;
@tailwind screens;
@tailwind components;
@tailwind utilities;
```
but while compiling with `npx parcel build` I get the error:

```
@parcel/transformer-css: Unknown at rule: @apply
🚨 Build failed.

Error: Expected content key 681abad9e4faf6c2 to exist
```
