### ISSUE TITLE
@parcel/optimizer-css rejects CSS namespaces on the ground they should appear earlier in the CSS

### ISSUE THREAD

**Issue by Offirmo** [parcel-bundler/parcel#9534]
# 🐛 bug report

My CSS is [styling SVG links](https://developer.mozilla.org/en-US/docs/Web/CSS/@namespace#specifying_default_and_prefixed_namespaces) and as such is using a CSS namespace.

However the CSS optimizer rejects my CSS on the ground that namespaces should come earlier.

However it is not easy nor convenient to order one's CSS.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
	"extends": "@parcel/config-default",

	"resolvers": [
		"@parcel/resolver-glob",
		"...",
		"@offirmo-private/parcel-resolver"
	]

}
```

## 🤔 Expected Behavior

It should work.

## 😯 Current Behavior

```
🚨 Build failed.

@parcel/optimizer-css: @namespaces rules must precede all rules aside from @charset, @import, and @layer statements

  /Users/<redacted>/index.HASH_REF_8e97ecbb9fe9c4a6.css:112:11
    111 |
  > 112 | @namespace svg "http://www.w3.org/2000/svg";
  >     |           ^
    113 |
    114 | svg|a:link, svg|a:visited {
```

## 💁 Possible Solution

It is not possible to manually ensure that a namespace definition comes first in the CSS.

There is no mention in the spec that CSS namespaces should come first. If the CSS bundler wants it first, the bundler is welcome to automatically hoist the namespace definition.

## 🔦 Context

Trying to style SVG links as suggested in https://developer.mozilla.org/en-US/docs/Web/SVG/Element/a#example

## 💻 Code Sample

sub.css:
```
/* As SVG does not provide a default visual style for links,
   it's considered best practice to add some */

@namespace svg url(http://www.w3.org/2000/svg);
/* Necessary to select only SVG <a> elements, and not also HTML's.
   See warning below */

svg|a:link,
svg|a:visited {
  cursor: pointer;
}

svg|a text,
text svg|a {
  fill: blue; /* Even for text, SVG uses fill over color */
  text-decoration: underline;
}

svg|a:hover,
svg|a:active {
  outline: dotted 1px blue;
}
```

main CSS:
```
:root {
  /* whatever */
box-sizing: border-box;
}

@import "sub.css";
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.11.0
| Node             | 20
| npm/Yarn         | yarn 1.22.21
| Operating System | MacOS

**Comment by devongovett** [comment]
See https://drafts.csswg.org/css-namespaces/#syntax

> Any @namespace rules must follow all @charset and @import rules and precede all other non-ignored at-rules and style rules in a style sheet.

`@import` rules must also come before other rules: https://drafts.csswg.org/css-cascade-5/#at-import

> Any @import rules must precede all other valid at-rules and style rules in a style sheet (ignoring @charset and @layer statement rules) and must not have any other valid at-rules or style rules between it and previous @import rules, or else the @import rule is invalid.

I believe this will also error in Parcel in the next version (once Lightning CSS is used to implement the CSS packager).

So to fix your issue, you should move the `@import` to the top of the file.

**Comment by Offirmo** [comment]
Hi @devongovett thanks a lot for your time and for your answer. TIL about this CSS rule!

I understand it's not Parcel's job but I believe when bundling different CSS files, the CSS bundler should automatically hoist those namespace definitions. Otherwise it requires a precise control over all the CSS used in the app.

Is Lightning CSS the right place to request such a feature? Or is Parcel planning to implement its own CSS bundler in the future?
