### ISSUE TITLE
Provide an option not to use babel transform on typescript code

### ISSUE THREAD

**Issue by piscisaureus** [parcel-bundler/parcel#954]
Starting with parcel 1.6, all javascript code is transformed by babel.
Our project (https://github.com/propelml/propel) uses typescript, which already knows how to target different versions of javascript/ecmascript. 
Therefore the babel transform is unnecessary -- and it actually creates problems because babel generates code that is dependent on regeneratorRuntime.
Could there be an option to disable the babel transform (either for typescript or for all javascript code)?

**Comment by davidnagli** [comment]
I agree. Typescript already handles transpiling code, so it doesn’t make any sense for us to run that through Babel. It just makes the bundle larger and wastes time duplicating the work that Typescript did.

We should also optimize the way we handle typescript assets too. Maybe we can even take the AST from the [TypeScript Compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API), and pass it into Uglify similar to what do with Babel.

**Comment by DeMoorJasper** [comment]
@davidnagli The AST is different from the babel AST, so this would be impossible, however this feature can be achieved by either converting Typescript AST to Babel AST (might be slightly faster if done correctly, but way more complex). Or generate a new AST from the output (kind of what we do now but without the actual transpiling)

**Comment by fathyb** [comment]
I started working on this on the TypeScript plugin, see [parcel-plugin-typescript#c511bd](https://github.com/fathyb/parcel-plugin-typescript/commit/c511bd6c3b55e63d306b702997e719281b363c47).
Babel isn't called once, it's direct `TS code -> TS AST -> transformations -> TS AST -> JS`, with a support for `fs.readFileSync`, `require`, `import`, `process` and node.js globals.
On my big corporate projects it improves build time by a 1.5 factor.

We can merge this here if you guys are interested.

**Comment by davidnagli** [comment]
Ya I think that would be a great idea. 

I never really understood why we have a seperate plugin if we have Typescript support in the core. I think we should merge the plugin’s features into core and get rid of the plugin. 

@devongovett @DeMoorJasper Thoughts?

**Comment by DeMoorJasper** [comment]
@davidnagli The direct typescript ast transform would be nice, more predictable as well. About porting over all the plugin features wouldn’t be a good idea, the plugin seems to go beyond parcels scope, another nice feature the plugin has is typescript error handling (and i don’t mean the annoying typing warnings, but actual compile-errors)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iocat** [comment]
Hi guys! Any update on this? 

pre-babel transpiling breaks my code. My project is using ES2017 async/await, so babel transpiling adds generatorRuntime(). And that function isn't included in runtime after the typescript transpiling phase.

If parcel uses pure Typescipt transpilation, I believe all the async/await is polyfilled directly by  Typescript without generatorRuntime in babel-polyfill library.

```typescript
export async function makeIdyllMarkupPromise(idyllMarkup: IdyllMarkup) {
    return await idyllMarkup;
}
```

becomes this with babel transpiling

```js

/*
Typescript does NOT give this TT.TT
function regeneratorRuntime()
*/

function makeIdyllMarkupPromise(idyllMarkup) {
    return __awaiter(this, void 0, void 0, /*#__PURE__*/regeneratorRuntime.mark(function _callee() {
        //....
    }
}
```

while without babel transpiliing, it should be

```javascript
function __awaiter(){/* typescript gives this */}
function __generator(){/* typescript also gives this */}

function makeIdyllMarkupPromise(idyllMarkup) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(
            //...
        );
    }
}
```

**Comment by ry** [comment]
Yes please add this feature. Also (and I'm not totally sure if this is related but I think so) Parcel tends to swallow very obvious syntax errors. I love Parcel - but this is a deal breaker for me.

**Comment by cerlestes** [comment]
Seriously, there needs to be an option to turn off babel. I don't want babel. I'm getting errors left and right because of some exotic libraries that TypeScript can handle to transpile correctly, but babel then messes up.

Is there a way to disable babel via .babelrc? I couldn't find one.

**Comment by devongovett** [comment]
Parcel compiles code to the specified browser/node version target in your app. It determines this based on the `browserslist` or `engines.node` keys in package.json depending on the `--target` flag. If neither of those are available, a default is picked: > 0.25% marketshare for browsers, or the node LTS version (currently 6). If you want to disable compilation, you can specify higher engine versions in your package.json.

**Comment by screendriver** [comment]
@devongovett I created a `.browserslistrc` directly in my project root directory and filled it with

```
> 1%
last 2 versions
not dead
```

But unfortunately I'm still getting following error when I try to do a `await import('./...');` in my `TypeScript` project:

```js
Uncaught ReferenceError: regeneratorRuntime is not defined
```

It seems that `Parcel` is still using Babel and tries to find its `regeneratorRuntime` (that I don't use because of TypeScript has everything included for `async / await` and dynamic imports)

**Comment by anjmao** [comment]
I think we need to create a bundler which works out of the box with Typescript and doesn’t use Babel when not needed.

**Comment by screendriver** [comment]
@anjamo there is already one: [FuseBox](https://github.com/fuse-box/fuse-box).

**Comment by agonbina** [comment]
That's what we need, yet another bundler!

**Comment by icek** [comment]
At this moment, the workaround is adding the following lines to the package.json:

```json
"browserslist": [
  "last 1 Chrome version"
],
```

**Comment by youk** [comment]
I guess it can be closed now that https://github.com/parcel-bundler/parcel/pull/6230 is implemented.

**Comment by DeMoorJasper** [comment]
Oh this was possible from the start with Parcel 2, can definitely be closed
