### ISSUE TITLE
Add timestamp to "watched" status messges

### ISSUE THREAD

**Issue by mike-ward** [parcel-bundler/parcel#957]
**Choose one:** is this a 🐛 bug report or 🙋 feature request? 🙋

### 🤔 Expected Behavior

When running Parcel in watch mode, it would be handy to know the time when the build occurred in addition to how long it took to build.

### 😯 Current Behavior

![image](https://user-images.githubusercontent.com/567927/37069394-2e678184-2181-11e8-8701-66a98936f90a.png)

### 💁 Possible Solution

Willing to do a pull request to add this...

### 🔦 Context

On a single screen laptop, there's not enough real estate to keep the command window visible.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.1
| Node             | 8.9.4
| npm/Yarn         |  5.6.0
| Operating System | Windows 10

**Comment by davidnagli** [comment]
See #712

**Comment by mike-ward** [comment]
I searched for "timestamp" when I  checked old issues. Figures...

**Comment by davidnagli** [comment]
ya took me a while to find it too 😝 😂
