### ISSUE TITLE
Default Cache folder location is on root instead of workspace folder

### ISSUE THREAD

**Issue by Tri125** [parcel-bundler/parcel#9581]
# 🐛 bug report

According to the documentation, by default the cache folder should be stored in the .parcel-cache folder inside your project.
When using parcel with npm workspaces I observed that the cache is stored on the root level but I would have expected it to be stored under the workspace folder.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
// root package.json - overly simplified sample
{
  "name": "@examples",
  "main": "index.js",
  "scripts": {
    "start:first": "npm run -w first start",
    "start:second": "npm run -w second start"
  },
  "workspaces": [
    "./apps/*"
  ],
  "engines": {
    "node": ">=14.21.3",
    "npm": ">=7.24.2"
  },
  "devDependencies": {
    "parcel": "^2.11.0"
  }
}

```

```js
// workspace package.json for workspace 'first' - overly simplified sample
{
    "name": "first",
    "main": "index.js",
    "private": true,
    "scripts": {
        "start": "parcel *.html --no-cache"
    },
}
```

/myProject
├── apps
│   ├── first
│   │   ├── index.html
│   │   ├── script.js
│   │   ├── package.json
│   ├── second
│   │   ├── index.html
│   │   ├── script.js
│   │   ├── package.json
├── package.json
├── package-lock.json

From the root directory I would execute the following command:

``npm run start:first``

I am aware that the sample that I'm sharing here does disable reading from the cache .

## 🤔 Expected Behavior

From reading the [documentation](https://parceljs.org/features/development/#caching), I was expecting the following structure with the cache being created under the project folder being currently executed : 

/myProject
├── apps
│   ├── first
│   │   ├── .parcel-cache
│   │   │   ├── data.mbd
│   │   │   ├── lock.mbd
│   │   ├── index.html
│   │   ├── script.js
│   │   ├── package.json
│   ├── second
│   │   ├── index.html
│   │   ├── script.js
│   │   ├── package.json
├── package.json
├── package-lock.json

## 😯 Current Behavior

The cache is created on the root level.

/myProject
├── .parcel-cache
│   ├── data.mbd
│   ├── lock.mbd
├── apps
│   ├── first
│   │   ├── index.html
│   │   ├── script.js
│   │   ├── package.json
│   ├── second
│   │   ├── index.html
│   │   ├── script.js
│   │   ├── package.json
├── package.json
├── package-lock.json

## 💁 Possible Solution

As a workaround ``/apps/first/package.json`` can specify the ``--cache-dir`` cli option and the cache will be correctly created under ``/apps/first``.

## 🔦 Context

A slight confusion but with a rather straight forward workaround. No impact.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  2.11.0
| Node             | 14.21.3
| npm/Yarn         | npm 8.19.4
| Operating System | Windows 10

**Comment by Harshitazz** [comment]
i want to work on this (beginner)

**Comment by mischnic** [comment]
This behaviour is correct. One benefit is that multiple workspace packages (e.g. `app1` and `app2`) can share cache information (for `lib1`).

The cache folder is put in the project root (this describes a bit how it is determined: https://parceljs.org/features/dependency-resolution/#absolute-specifiers)
