### ISSUE TITLE
Imported image paths during development

### ISSUE THREAD

**Issue by jaredpalmer** [parcel-bundler/parcel#96]
I am having issues with image asset paths during development and production. 

During dev, if i do `import logo from './logo.svg` this becomes => `1230981023.png`.  
During build, `import logo from './logo.svg` this becomes => `/dist/1230981023.png`. 

This may have to do with a public URL issue during dev but i'm not sure.

**Comment by devongovett** [comment]
url is generated here https://github.com/parcel-bundler/parcel/blob/master/src/assets/RawAsset.js#L10

**Comment by thejameskyle** [comment]
Also see https://github.com/parcel-bundler/parcel/blob/7b899b38930a7a30943a6148f475a5007ce2c625/src/Asset.js#L140-L157

**Comment by RakanNimer** [comment]
Hey, 

Thanks for the great work on parcel, going through the code was fun !

I wrote a fix for this that's working on my machine.

I'm cleaning it up and will send a PR in a bit if no one is working on this.

Cheers !

**Comment by gisderdube** [comment]
I had the same issue with importing assets (jpg|svg), but after fiddling with the `--public-url` it worked out just fine. Perhaps you can share some of your project structure?

**Comment by devongovett** [comment]
Should be fixed by https://github.com/parcel-bundler/parcel/pull/160. You just need to set `--public-url` when building for prod.

**Comment by samsch** [comment]
I think I'm having the same issue using Parcel 1.2.1 development server (`parcel src/index.html`). My imported url (`import image from './path/to/image.jpg';`) is `/24e15f924c17a873dc81435468e5287b.jpg`, while it would need to be `/dist/24e15f924c17a873dc81435468e5287b.jpg` to work.

**Comment by QuantumInformation** [comment]
I have an issue here with a path that is correct for importing an image

<img width="823" alt="screen shot 2019-01-24 at 11 53 42" src="https://user-images.githubusercontent.com/216566/51676518-ba402200-1fce-11e9-8b50-e3a5f0256a53.png">

**Comment by mischnic** [comment]
> I have an issue here with a path that is correct for importing an image

Does it build/run correctly?
Then it's only TypeScript not recognizing it, does this fix work: https://github.com/Microsoft/TypeScript-React-Starter/issues/12#issuecomment-326370098

**Comment by QuantumInformation** [comment]
It builds but i get

⠧ Building SpaceInvaders.ts...🚨  /Users/nikos/WebstormProjects/youtube-space-invaders/src/SpaceInvaders.ts(14,21)
Cannot find module './images/backgrounds/sunrise.jpg'.
    13 |
  > 14 | import sunrise from './images/backgrounds/sunrise.jpg'
       |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    15 |


⠴ Packaging...🚨  /Users/nikos/WebstormProjects/youtube-space-invaders/src/SpaceInvaders.ts(14,21)
Cannot find module './images/backgrounds/sunrise.jpg'.
    13 |
  > 14 | import sunrise from './images/backgrounds/sunrise.jpg'
       |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    15 |


✨  Built in 2.81s.

**Comment by mischnic** [comment]
@QuantumInformation 	Please open a new issue that importing raw files (or at least images) can't be imported in typescript.

**Comment by QuantumInformation** [comment]
I updated parcel, issue went away, but now I get this

Server running at http://localhost:1234
🚨  /Users/nikos/WebstormProjects/youtube-space-invaders/src/SpaceInvaders.ts:18:7: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (18:8):
  16 | import { Interpreter } from './agent/Interpreter'
  17 |
> 18 | export enum Actions {
     |       ^

**Comment by QuantumInformation** [comment]
maybe https://github.com/fathyb/parcel-plugin-typescript/issues/59#issuecomment-457199020
