### ISSUE TITLE
Parcel fetching configs from where it's installed instead of where the process is running

### ISSUE THREAD

**Issue by mojtabast** [parcel-bundler/parcel#9602]
# 🐛 bug report

Parcel looking for configs from where its installed, not where the binary is running. For monorepos, This can be problematic when parcel installed in the workspace root.

## 🎛 Configuration (.babelrc, package.json, cli command)

cli:
`parcel build`

package.json:
```
  "@parcel/resolver-default": {
    "packageExports": true
  }
```

## 🤔 Expected Behavior

When `parcel` running from packages, it should start from where it's running and not where it's installed.

## 😯 Current Behavior

Applying configs from nearest package.json that parcel installed there as well.

## 💁 Possible Solution

Start getting configs where process is going to be run.

## 🔦 Context

We've installed parcel in root because there are some clients that need to being built by Parcel. We need to be able to config each client separately and not globally essentially .

Consider this structure:

```
/    <- parcel installed here
/packages/client1
/packages/client2
```

When we are adding the following config to `/packages/client1` it doesn't work:

```
  "@parcel/resolver-default": {
    "packageExports": true
  }
```

But when add to `/package.json` (workspace) root it will be applied correctly.

## 💻 Code Sample

(https://github.com/mojtabast/parcel-resolve-config-from-root)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.12.0
| Node             | v20.9.0
| npm/Yarn         | yarn 1.22.19
| Operating System | Mac

**Comment by zbmovo** [comment]
> # 🐛 bug report
> Parcel looking for configs from where its installed, not where the binary is running. For monorepos, This can be problematic when parcel installed in the workspace root.
> 
> ## 🎛 Configuration (.babelrc, package.json, cli command)
> cli: `parcel build`
> 
> package.json:
> 
> ```
>   "@parcel/resolver-default": {
>     "packageExports": true
>   }
> ```
> 
> ## 🤔 Expected Behavior
> When `parcel` running from packages, it should start from where it's running and not where it's installed.
> 
> ## 😯 Current Behavior
> Applying configs from nearest package.json that parcel installed there as well.
> 
> ## 💁 Possible Solution
> Start getting configs where process is going to be run.
> 
> ## 🔦 Context
> We've installed parcel in root because there are some clients that need to being built by Parcel. We need to be able to config each client separately and not globally essentially .
> 
> Consider this structure:
> 
> ```
> /    <- parcel installed here
> /packages/client1
> /packages/client2
> ```
> 
> When we are adding the following config to `/packages/client1` it doesn't work:
> 
> ```
>   "@parcel/resolver-default": {
>     "packageExports": true
>   }
> ```
> 
> But when add to `/package.json` (workspace) root it will be applied correctly.
> 
> ## 💻 Code Sample
> (https://github.com/mojtabast/parcel-resolve-config-from-root)
> 
> ## 🌍 Your Environment
> Software	Version(s)
> Parcel	^2.12.0
> Node	v20.9.0
> npm/Yarn	yarn 1.22.19
> Operating System	Mac

I tried to install it in /root/packages/xxx but it still looks for package.json under /root. 😂
