### ISSUE TITLE
open browser customization

### ISSUE THREAD

**Issue by shrynx** [parcel-bundler/parcel#961]
**Choose one:**  🙋 feature request?

Parcel cli has an option `--open`, which opens default browser.
There are two aspects that i would like to change
1. Allow providing custom browser option (eg: “parcel  ...  --open ‘firefox’ “)
2. Try best to re use existing open tab.

### 💁 Possible Solution
I have a PR implementing both the above mentioned changes.
but wanted to discuss if it is in scope of parcel.
https://github.com/parcel-bundler/parcel/pull/960

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.2
| Node             | 8.4.0
| npm/Yarn         | 1.5.1
| Operating System | macOS High Sierra 10.13.3

**Comment by devongovett** [comment]
This is implemented in parcel 2.
