### ISSUE TITLE
Object spread operator causes build error

### ISSUE THREAD

**Issue by turnerhayes** [parcel-bundler/parcel#9615]
# 🐛 bug report

I'm getting a build error from Tailwind config file, seemingly resulting from an object spread operator

## 🎛 Configuration (.babelrc, package.json, cli command)

See below repo. No custom .babelrc, little in package.json.

## 🤔 Expected Behavior

Build without error

## 😯 Current Behavior

Build without error

![image](https://github.com/parcel-bundler/parcel/assets/6371670/4d5a9317-40d3-4896-ae24-5ecbf260fe99)

## 🔦 Context

I started this from a [Codesandbox.io](https://codesandbox.io/p/sandbox/date-picker-tests-h439cw), where it seems to build without error, but taking it local, the error cropped up.

Can't build or run the server locally.

## 💻 Code Sample

https://github.com/turnerhayes/date-picker-examples/tree/config-error

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.1
| Node             | v20.7.0
| npm/Yarn         | npm v10.1.0
| Operating System | Windows 10 on WSL2 (Ubuntu)

**Comment by mischnic** [comment]
Parcel 1 isn't maintained anymore, maybe try Parcel 2.
Otherwise, bumping Babel-related packages in your lockfile might help.
