### ISSUE TITLE
reload when saving the file even without any changes

### ISSUE THREAD

**Issue by Lycheemisu** [parcel-bundler/parcel#962]
### 🤔 Expected Behavior

when i save the file, parcel will compare the changes between current version and old version, then decides the necessary update&reload;
### 😯 Current Behavior

now always reloads when saving the file even without any changes, also sometimes don't reload when real changes.

### 💁 Possible Solution

i saw Hot Module Replacement in the website about Module.hot API  and  react-hot-loader, but could you please support the case in a simple way.

thanks

**Comment by DeMoorJasper** [comment]
This is due to parcel looking at mtime not actual content as this would slow down and not really be a big addition.
About the sometimes not happening, would be nice to have some tests or more detailed description of the issue

**Comment by davidnagli** [comment]
@Lycheemisu When would this matter? Is there any case where it’s important to not trigger HMR on a file save with no change?

As @DeMoorJasper mentioned, comparing content changes is much slower than just looking at mtime.

**Comment by Lycheemisu** [comment]
@DeMoorJasper @davidnagli   thanks for answer.

I see, looking at mtime will be much faster.  

Just sometimes modified without logic reloads surprising
