### ISSUE TITLE
Images are not created in the dist folder

### ISSUE THREAD

**Issue by MatGPereira** [parcel-bundler/parcel#9625]
# 🐛 bug report

There are several images in my project. Some in SVG and others in PNG.

Whenever Parcel runs the build it creates a copy of the image in the dist/ directory with names like `<IMAGE_NAME>.<ANY_HASH>.<IMAGE_EXTENSION>.`

However, in this process, some images are not being taken to rendering.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
	"source": "./index.html",
	"type": "module",
	"scripts": {
		"start": "parcel .",
		"build": "parcel build",
	},
	"devDependencies": {
		"@commitlint/cli": "19.2.1",
		"@commitlint/config-conventional": "19.1.0",
		"@parcel/transformer-sass": "2.12.0",
		"@typescript-eslint/eslint-plugin": "7.5.0",
		"@typescript-eslint/parser": "7.5.0",
		"commitizen": "4.3.0",
		"cz-conventional-changelog": "3.3.0",
		"eslint": "8.57.0",
		"husky": "9.0.11",
		"lint-staged": "15.2.2",
		"parcel": "2.12.0",
		"prettier": "3.2.5",
		"stylelint": "16.3.1",
		"stylelint-config-sass-guidelines": "11.1.0",
		"stylelint-config-standard": "36.0.0",
		"stylelint-config-standard-scss": "13.1.0",
		"stylelint-high-performance-animation": "1.10.0",
		"stylelint-sass-render-errors": "3.2.1"
	},
	"lint-staged": {
		"*.{html,js,md}": "prettier --write",
		"*.{css,scss}": [
			"prettier --write",
			"stylelint --fix --allow-empty-input"
		]
	},
	"config": {
		"commitizen": {
			"path": "./node_modules/cz-conventional-changelog"
		}
	}
}
```

## 🤔 Expected Behavior

It was expected that all images would be transferred to the dist/ directory so that the build code could use them in the DOM and render them on the page

## 😯 Current Behavior

Some images are left out in the dist/ folder creation process during bundler and Parcel build.

O.B.S.: We tried to delete the Parcel cache to solve the problem, but it didn't work

## 💁 Possible Solution

The way I managed to solve this was by creating several `<img></img>` tags directly in the html to see if the images were generated. So, after they were generated, I took their path and manually inserted it into the JSON file that stores the image paths

## 🔦 Context

O código é composto de templates gerados em uma classe TypeScript que, após a chamada de um evento global window( `window.addEventListener('DOMContentLoaded', () => {})`) insere este template no DOM de forma dinâmica através do uso de template strings

## 💻 Code Sample

```js
private template({ image, content }: IParticipantsProps): string {
  return `
	  <article class="c-participant">
		  <header class="c-participant__header color-girl-1">
			  <img
				  src="${image.path}"
				  alt="${image.alt}"
				  class="c-participant__picture"
			  />
		  </header>
   `
```

onde os parâmetros 

```js

{ image, content }: IParticipantsProps
```

recebem valores do tipo `string`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.12.0
| Node             |20.12.0
| npm/Yarn         |10.5.0
| Operating System | Ubuntu 22.04.0

**Comment by mischnic** [comment]
Does this help? https://parceljs.org/languages/javascript/#url-dependencies

**Comment by MatGPereira** [comment]
> Does this help? https://parceljs.org/languages/javascript/#url-dependencies

This didn't work for some reason.
Even so, the image was not loaded by Parcel.

It doesn't bring up any errors in the terminal for some reason.

**Comment by mischnic** [comment]
And you also did indeed use `new URL("some_concrete_image.jpeg", import.meta.url)` wherever you call `template()`?
Simply using `new URL(image.path, import.meta.url)` inside of `template` won't work.

**Comment by MatGPereira** [comment]
Now throw this error:
Security Error: Content at http://localhost:1234/ may not load or link to file:///src/assets/images/logos/cresca-mais.svg.

**Comment by MatGPereira** [comment]
Now it's resolved, but the issue is that the first parameter of new URL() needs to be a string for parcel to compile.

So I can't pass the paths dynamically through variables. Do you have any idea how to resolve this?

**Comment by mischnic** [comment]
> So I can't pass the paths dynamically through variables. Do you have any idea how to resolve this?

Exactly. You have to structure your project to always have strings in there. There is no way around this, otherwise Parcel wouldn't know which images it needs to copy.

Alternatively, there's https://github.com/elwin013/parcel-reporter-static-files-copy

**Comment by MatGPereira** [comment]
> > So I can't pass the paths dynamically through variables. Do you have any idea how to resolve this?
> 
> Exactly. You have to structure your project to always have strings in there. There is no way around this, otherwise Parcel wouldn't know which images it needs to copy.
> 
> Alternatively, there's https://github.com/elwin013/parcel-reporter-static-files-copy

Okay, dude, everything works now. Thanks so much.
