### ISSUE TITLE
@parcel/rust package should only install binaries for the host platform

### ISSUE THREAD

**Issue by broofa** [parcel-bundler/parcel#9642]
### Problem

`@parcel/rust` is installing binaries for all supported platforms, _on every platform._   This bloats the install footbrint by 165-169MB.

### Current Behavior

For example, with a fresh install (new, empty directory):
![CleanShot 2024-04-14 at 09 30 03@2x](https://github.com/parcel-bundler/parcel/assets/164050/ad23a02e-e7af-4508-96d0-954a963f1b8f)

### Desired Behavior

`parcel` should only install the one binary needed for the current host `os`/`cpu` architecture.

I know this is a non-trivial problem, but other projects seem to have solved this.  E.g. `esbuild` [ships it's binaries as separate `optionalDependencies`](https://github.com/evanw/esbuild/blob/main/npm/esbuild/package.json#L20-L44) and relies on the package manager to decide which one to install.  (It's worth noting that they had [considerable discussion on this topic](https://github.com/evanw/esbuild/issues/789) before settling on this solution.)

**Comment by mischnic** [comment]
Yes, we definitely want this. It's just that somebody need to implement it.

https://github.com/parcel-bundler/lightningcss has this approach as well, and that seems to work well.

Previous discussion: https://github.com/parcel-bundler/parcel/issues/6483

**Comment by devongovett** [comment]
> and that seems to work well

...mostly. There are some issues with package managers not installing any of the optional dependencies sometimes.
