### ISSUE TITLE
To update svgo to version 3.0 in @parcel/optimizer-htmlnano.

### ISSUE THREAD

**Issue by zbmovo** [parcel-bundler/parcel#9660]
> # 🐛 bug report
> The deprecated warning for stable@0.1.8 is displayed during Parcel installation.
> 
> ```
> Downloading @parcel/rust@2.12.0: 65.58 MB/65.58 MB, done
> Downloading @swc/core-win32-x64-msvc@1.4.16: 16.65 MB/16.65 MB, done
>  WARN  1 deprecated subdependencies found: stable@0.1.8  <-----------
> Packages: +172
> ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
> Progress: resolved 210, reused 0, downloaded 172, added 172, done
> node_modules/.pnpm/@swc+core@1.4.16_@swc+helpers@0.5.10/node_modules/@swc/core: Running postinstall script, done in 69ms
> node_modules/.pnpm/msgpackr-extract@3.0.2/node_modules/msgpackr-extract: Running install script, done in 153ms
> node_modules/.pnpm/lmdb@2.8.5/node_modules/lmdb: Running install script, done in 188ms
> 
> devDependencies:
> + parcel 2.12.0
> 
>  WARN  Issues with peer dependencies found
> .
> └─┬ parcel 2.12.0
>   └─┬ @parcel/config-default 2.12.0
>     └─┬ @parcel/optimizer-htmlnano 2.12.0
>       └─┬ htmlnano 2.1.0
>         └── ✕ unmet peer svgo@^3.0.2: found 2.8.0 in @parcel/optimizer-htmlnano
> 
> Done in 10.3s
> ```
> 
> ## 🎛 Configuration (.babelrc, package.json, cli command)
> ```shell
> pnpm i parcel -D
> ```
> 
> ## 🤔 Expected Behavior
> Do not display the deprecated warning.
> 
> ## 😯 Current Behavior
> The console outputs "WARN 1 deprecated subdependencies found: stable@0.1.8."
> 
> ## 💁 Possible Solution
> https://github.com/parcel-bundler/parcel/blob/91b47ff5823d3c91cd46937bca83da4a8e29abb5/packages/optimizers/htmlnano/package.json#L27
> 
> The svgo version used here is v2.4.0, and its dependency, stable v0.1.8, has been deprecated. It's now possible to update to the latest version of svgo, v3.2.0, to address the deprecation warning encountered during Parcel installation.
> 
> 
> 
> ## 🌍 Your Environment
> | Software            | Version(s) |
> | -----------         | -----------|
> | Parcel              | ^2.12.0    |
> | Node                | v20.11.0   |
> | pnpm                | v9.0.4     |
> | Operating System    | windows 10 |

**Comment by broofa** [comment]
Please reopen.  This is still an issue.

attn: @devongovett

```
$ npm i parcel@latest
npm warn deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility

...

$ npm ls stable
foo@ /private/tmp/foo
`-- parcel@2.12.0
  `-- @parcel/config-default@2.12.0
    +-- @parcel/optimizer-htmlnano@2.12.0
    | `-- svgo@2.8.0
    |   `-- stable@0.1.8
    `-- @parcel/optimizer-svgo@2.12.0
      `-- svgo@2.8.0
        `-- stable@0.1.8 deduped
```

**Comment by mischnic** [comment]
That should be finnaly fixed now with https://github.com/parcel-bundler/parcel/pull/9969, but only on nightly versions so far.

**Comment by devongovett** [comment]
Should be fixed by the above merged PR. Will be released soon.
