### ISSUE TITLE
@parcel/transformer-raw adds a dot at the end of filename

### ISSUE THREAD

**Issue by kalucky0** [parcel-bundler/parcel#9686]
`@parcel/transformer-raw` adds a dot at the end of a filename turning `file` into `file.`

```
├── public
│   ├── CNAME
└── dist
    └── CNAME.
```

## 🎛 Configuration

`.parcelrc`
```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "public/**/*": [
      "@parcel/transformer-raw"
    ]
  }
}
```

`package.json`
```json
{
  "name": "website",
  "source": "src/index.html",
  "scripts": {
    "start": "parcel",
    "build": "parcel build src/index.html",
    "postbuild": "parcel build public/**/*"
  },
  "devDependencies": {
    "parcel": "latest"
  }
}
```

## 🌍 Environment

| Software | Version |
| - | - |
| Parcel | v2.12.2 |
| Node | v22.0.0 |
| npm |  v10.5.2 |
| Operating System | Windows 11 Pro [10.0.22631 Build 22631] |

**Comment by mischnic** [comment]
I suspect this isn't actually caused by the raw transformer but by Parcel core itself, because there are various places where it does `basename + "." + type`.
