### ISSUE TITLE
DOMException undefined - Cannot read properties of undefined (reading 'constructor')

### ISSUE THREAD

**Issue by damian-pastorini** [parcel-bundler/parcel#9775]
# 🐛 bug report

With Parcel 2.11.0, the current build gives:
https://gist.github.com/damian-pastorini/98ef3dc96e0d63b994e60b0b1fecd034

With Parcel 2.12.0, the build gives:
https://gist.github.com/damian-pastorini/c7c49f46ea5b7fecb0ebd000f5d5fbdd

## 🎛 Configuration (.babelrc, package.json, cli command)

Same code built on open-source project:
https://github.com/damian-pastorini/reldens/tree/v4.0.0-beta.36
https://github.com/damian-pastorini/reldens/blob/master/package.json
https://github.com/damian-pastorini/reldens/blob/master/lib/bundlers/drivers/parcel-config.json

Client build and configuration is all set in the same file:
https://github.com/damian-pastorini/reldens/blob/468257d4accd0014d462c87c9c8ccb028111f611/lib/game/server/theme-manager.js#L278

## 🤔 Expected Behavior

With Parcel 2.11.0 everything works fine on the site and throwing a console log gives the following:
![image](https://github.com/parcel-bundler/parcel/assets/1211779/8df7ea05-83d2-44b0-914c-304ad49138b2)

## 😯 Current Behavior

With Parcel 2.12.0 we can see the missing DOMException object and because of that the following error:
![image](https://github.com/parcel-bundler/parcel/assets/1211779/aab6838e-0a37-4131-85be-a1c0e75927e9)

```
Uncaught TypeError: Cannot read properties of undefined (reading 'constructor')
    at iB1GV.bbf92b62ba9b2dbc (index.3928b1e6.js:8100:15)
    at c (index.3928b1e6.js:21:21)
    at d (index.3928b1e6.js:27:36)
    at e7bNv.b2aadf47cb91c5bf (index.3928b1e6.js:85:5817)
    at c (index.3928b1e6.js:21:21)
    at d (index.3928b1e6.js:27:36)
    at clSRy.688460f732490733 (index.3928b1e6.js:80:9)
    at c (index.3928b1e6.js:21:21)
    at d (index.3928b1e6.js:27:36)
    at bHWOE.f6a573e6a894b077 (index.3928b1e6.js:52:32)
```

## 💁 Possible Solution

Not a clue, sorry, I would to find a fix for it.

## 🔦 Context

I should be able to build the same code base after upgrading Parcel from 2.11.0 to 2.12.0.
The build starts on the index.html file and from there it grabs the JS and CSS.

## 💻 Code Sample

The entire project is open source, you can clone the repository or try with the Skeleton project:
https://github.com/damian-pastorini/reldens-skeleton/ > updating Parcel to 2.12.0 here would give the same issue.

## 🌍 Your Environment
Parcel 2.11.0 > trying to upgrade to 2.12.0
Node JS v20.11.1
NPM 9.6.7
Windows 11 with GitBash

**Comment by damian-pastorini** [comment]
Closing I had some missing packages on my package.json, updated according: 
https://github.com/parcel-bundler/parcel/blob/v2/packages/configs/default/package.json
It's working now.

**Comment by PenghaiZhang** [comment]
> Closing I had some missing packages on my package.json, updated according: https://github.com/parcel-bundler/parcel/blob/v2/packages/configs/default/package.json It's working now.

Hi @damian-pastorini can I ask how you fixed this issue ?

**Comment by damian-pastorini** [comment]
hi @PenghaiZhang , I had updated parcel and the config, but some packages referenced in the config were not included in the package.json file on my project, I've compared the parcel packages in my project against the ones in the link above to include the missing ones and remove the ones that I didn't need anymore.
