### ISSUE TITLE
`process.env` inline doesn't work with non-module script

### ISSUE THREAD

**Issue by SukkaW** [parcel-bundler/parcel#9788]
# 🐛 bug report

As the title.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "private": true,
  "browserslist": "defaults, since 2016, not dead",
  "scripts": {
    "dev": "parcel 'src/*.html'",
    "prebuild": "rimraf dist",
    "build": "parcel build 'src/*.html' --no-source-maps"
  },
  "devDependencies": {
    "parcel": "^2.12.0",
    "rimraf": "^5.0.7"
  }
}
```

## 🤔 Expected Behavior

Given minimum reproduction:

```html
// src/index.html
<!DOCTYPE html>
<HTML>

<head>
</head>

<body>
    <script src="./index.js"></script>
</body>

</html>
```

```js
// src/index.js

console.log(process.env.NODE_ENV !== 'development');
```

Run `npm run dev` and open `localhost:1234` in the browser, open the browser's devtools and see `false` being logged in the console.

## 😯 Current Behavior

```
ReferenceError: process is not defined
```

## 💁 Possible Solution

It seems that the `process.env` inline doesn't work for normal non-module scripts.

## 🔦 Context

I am migrating an old-school project to a modern tech stack w/ parcel, I can't add `type="module"` to all of `<script />` at once.

## 💻 Code Sample

See above.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.12.0
| Node             | 20.13.1
| npm/Yarn         | npm 10.5.2
| Operating System | Linux 6.8.11-300.fc40.x86_64

**Comment by devongovett** [comment]
This is working as expected. Classic scripts (without `type="module"`) behave like they do in the browser, so `import`, `require`, and other CJS/ESM features are not supported there. See https://parceljs.org/languages/javascript/#classic-scripts
