### ISSUE TITLE
Follow links in custom markup

### ISSUE THREAD

**Issue by pierredavidbelanger** [parcel-bundler/parcel#980]
I guess its a question 🙋:

How one should handle the the "links" in custom markup ?

For example, I am using the [Onsen UI](https://onsen.io/) framework, and some of its components have attributes that can refers to other HTML pages , like the `ons-navigator`'s [page attribute](https://onsen.io/v2/api/js/ons-navigator.html#attributes).

I think I have 3 choices:
- I clone, apply the bellow diff, push, use (forever) Parcel from my own repo (I will need #936 for this 😉)
- Submit a PR with the bellow diff for this specific framework, and slowly `src/assets/HTMLAsset.js` will bloat with every custom markup details
- Think of a generic way (through the plugin API ?) to support this and other framework on a per project basis, then submit a PR 

What do you think is best for Parcel ?

```diff
diff --git a/src/assets/HTMLAsset.js b/src/assets/HTMLAsset.js
index 4c63c8d..eed3a87 100644
--- a/src/assets/HTMLAsset.js
+++ b/src/assets/HTMLAsset.js
@@ -22,7 +22,12 @@ const ATTRS = {
   href: ['link', 'a'],
   poster: ['video'],
   'xlink:href': ['use'],
-  content: ['meta']
+  content: ['meta'],
+  page: [
+    'ons-navigator',
+    'ons-splitter-side',
+    'ons-tab'
+  ]
 };
 ```

**Comment by davidnagli** [comment]
I think this should be done through a plugin 👍 

This is way to specific to be part of the Parcel core, and it would be impossible to maintain a central list of every small nuance of every JS framework.

**Comment by mischnic** [comment]
Is something planned regarding this in Parcel 2?

**Comment by Seeingred0** [comment]
Did anyone find a decent solution here? Having trouble loading a-frame assets with Parcel.
