### ISSUE TITLE
🐛SVG files are watched but not updated

### ISSUE THREAD

**Issue by fregante** [parcel-bundler/parcel#983]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
Bug

SVG files linked via `img[src]` or `svg>use[xlink:href]` are detected and correctly watched (the build runs on change) but they aren't updated until `parcel` is run again.

### 🎛 Configuration (.babelrc, package.json, cli command)

```sh
❯ parcel --version
1.6.2

❯ echo '<!DOCTYPE html><body><img src="./file.svg"></body>' > index.html

❯ echo '<svg xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" height="10" width="20" fill="black" /></svg>' > file.svg

❯ parcel
Server running at http://localhost:1234
✨  Built in 5ms.
```

### 🤔 Expected Behavior

If you change `fill` to `red`, the SVG file in `dist` should be updated

### 😯 Current Behavior

The watch detects the file change, the build runs, but no files updated and `index.html` doesn't reload.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.2
| Node             | 8.6.0
| npm/Yarn         | 5.7.1
| Operating System | macOS 10.13.3

**Comment by elgs** [comment]
This happens to js files in my project, too.

**Comment by davidnagli** [comment]
Looks like a problem with safe write... are you sure that your files are being properly watched?


See: #221 and [the safe-write section of the HMR docs](https://parceljs.org/hmr.html#safe-write)

**Comment by elgs** [comment]
@davidnagli please note the title of this issue, the files are watched, but the browser is not updated.

**Comment by mischnic** [comment]
This happens with images (e.g. png) as well.

**Comment by voland62** [comment]
My workaround:
```javascript
if (module.hot) {
    module.hot.accept(function () {
        window.location.reload();
    });
}
```

**Comment by bfred-it** [comment]
I don’t think that’s enough, in my case the SVG isn’t updated. Updating the page will still show the old SVG.

**Comment by bfred-it** [comment]
Caching of what? The actual file does not update on the file system.

**Comment by mischnic** [comment]
> Caching of what? The actual file does not update on the file system.
> 
> This is not a browser-side issue, it’s a build issue.

Strange. For me, the "dist/file.---.svg" file updated correctly. (Parcel 1.11.0, macOS 10.13.6)

**Comment by fregante** [comment]
> Strange. For me, the "dist/file.---.svg" file updates correctly and refreshing the page then updates the image. (Parcel 1.11.0, macOS 10.13.6)

I confirm that's the case for me in Parcel 2.0.0-alpha.3.2 as well (macOS 10.15.7)
