### ISSUE TITLE
import() in safari bug ?

### ISSUE THREAD

**Issue by jun-lu** [parcel-bundler/parcel#985]
![image](https://user-images.githubusercontent.com/491651/37282761-918250ba-2630-11e8-95b9-e91d0de56e1f.png)

 code 

````

 aaa(){
    import("./pages/index").then((a)=>{
      console.log(a)
    });
  }

<a onClick={this.aaa}>click me</a>

````

Chrome is  ok ok ok,  safari load javascript error. why ?

parcel version 1.6.2

**Comment by davidnagli** [comment]
Does Parcel produce any error in the terminal?

**Comment by jun-lu** [comment]
not error in terminal
