### ISSUE TITLE
how to resolve the bundled file cache in browser

### ISSUE THREAD

**Issue by chunzj** [parcel-bundler/parcel#986]

**Comment by DeMoorJasper** [comment]
Could u add an issue description?

**Comment by chunzj** [comment]
@DeMoorJasper I rebuild to generate the bundled files and publish to production，how to update these files(css、js、image) cache from browser because of  not change of these files's name

**Comment by DeMoorJasper** [comment]
@chunzj u could change the output directory for each version, in the future we are planning on basing the filename on the content (by using a content hash) #829 & #872

**Comment by chunzj** [comment]
@DeMoorJasper I hope the authorities can solve this problem as soon as possible, Thanks!
