### ISSUE TITLE
🐛 `--help` should show all commands (build, serve, watch)

### ISSUE THREAD

**Issue by fathyb** [parcel-bundler/parcel#989]
**Choose one:** is this a 🐛 bug report ~or 🙋 feature request?~

### 🎛 Configuration (.babelrc, package.json, cli command)

None.

### 🤔 Expected Behavior

`parcel --help` should display the three main commands documentation.

### 😯 Current Behavior

It only shows `serve`: 
```
$ parcel --help

Usage: serve [options] [input]

  starts a development server


  Options:

    -p, --port <port>          set the port to serve on. defaults to 1234
    --hmr-port <port>          set the port to serve HMR websockets, defaults to random
    --hmr-hostname <hostname>  set the hostname of HMR websockets, defaults to location.hostname of current window
    --https                    serves files over HTTPS
    --open                     automatically open in default browser
    -d, --out-dir <path>       set the output directory. defaults to "dist"
    -o, --out-file <filename>  set the output filename for the application entry point.
    --public-url <url>         set the public URL to serve on. defaults to the same as the --out-dir option
    --no-hmr                   disable hot module replacement
    --no-cache                 disable the filesystem cache
    --no-source-maps           disable sourcemaps
    -t, --target [target]      set the runtime environment, either "node", "browser" or "electron". defaults to "browser"
    -V, --version              output the version number
    -h, --help                 output usage information
```

### 💁 Possible Solution

Implement it in `cli.js`?

### 🔦 Context

Reported on Slack by `Nathan Tomsic`

### 💻 Code Sample

`parcel --help`

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.2
| Node             | 8.9.1
| npm/Yarn         | Yarn 1.5.1
| Operating System | macOS 10.13.3 (17D47)

**Comment by davidnagli** [comment]
So you expect `parcel help` to NOT show the list of CLI options? 😕 

 I personally think this would be more annoying then helpful, but let's see what others say. 🙂 🤷‍♂️

**Comment by fathyb** [comment]
@davidnagli oh no, I meant that `parcel --help` should do the same as `parcel help` 😄

**Comment by davidnagli** [comment]
tbh I'm personally more of a fan of the old way. 

@DeMoorJasper @devongovett What do you guys think?

**Comment by devongovett** [comment]
Yeah, I think this is a bug. `parcel --help` should list all of the commands the same way `parcel help` does. `parcel <command> --help` should do the same thing as `parcel help <command>`.
