### ISSUE TITLE
🐛Using Rust with FFI, results in WebAssembly Instantiation error

### ISSUE THREAD

**Issue by conblem** [parcel-bundler/parcel#990]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

🐛Im currently trying to get Parcel running with a combination of Rust and the FFI interface.

### 🎛 Configuration (.babelrc, package.json, cli command)

No config

### 🤔 Expected Behavior
I can import the Rust function which calls the native C code as simple as:
```js
import { get_size } from "./lib.rs"

console.log(get_size())
```
### 😯 Current Behavior
Parcel and The rust Code builds fine but i get the following runtime error:
```Uncaught (in promise) TypeError: WebAssembly Instantiation: Imports argument must be present and must be an object```

### 💁 Possible Solution

I'm a total WebAssembly noob but i think this points in the right direction
[https://stackoverflow.com/questions/48039547/webassembly-typeerror-webassembly-instantiation-imports-argument-must-be-pres](https://stackoverflow.com/questions/48039547/webassembly-typeerror-webassembly-instantiation-imports-argument-must-be-pres)
Either Parcel should automatically import all required modules or it is possible to configure the WebAssembly instantiation.

### 🔦 Context

Im trying to get rnnoise running in the browser with the least amount of configuration and maximum ease of use.

### 💻 Code Sample

[Example Repo](https://github.com/conblem/nois.ly)
clone it using ```git clone --recurse-submodules https://github.com/conblem/nois.ly```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.2
| Node             | 8.9.4
| Yarn         | 1.3.2
| macOS | 10.13.2

**Comment by davidnagli** [comment]
cc @albizures

**Comment by albizures** [comment]
Ok, so here are happening two things. 

* First, the error is saying that you need to provide a function, in this case, `rnnoise_get_size` through an importObject, sadly parcel doesn't support it yet. 😞You can see #647 for more info.
* Second, as I understood `rnnoise_get_size` is a C function, so importObject is not the right way to provide it, I think the correct way is providing the object file with `rnnoise_get_size` to the Rust compiler, kind of like this `rustc main.rs -l doubler.o -L`, but again this is not supported for parcel either 😭

**Comment by conblem** [comment]
@albizures 
As for the second part, atleast on the rust side the buildscript should take care of the linking process.
The C functions get linked just fine if I use them directly in Rust, but this is my first time using a C library so im pretty clueless.

Anyway maybe someday i will get it working this simply 😿 , also thanks for the fast answer and the awesome piece of software that parcel is 😺.

**Comment by samvv** [comment]
Got the same problem; trying to figure it out right now.
