### ISSUE TITLE
The "loader" generated by code splitting feature should be inlined

### ISSUE THREAD

**Issue by stargazer33** [parcel-bundler/parcel#9930]
# 🙋 feature request
Code splitting feature generates an additional "runtime" JS file. Example:
```
dist/ex/ex.runtime.c5ec135b.js               1021 B
```
Looks like a loader for other .js files

This loader is only 1 KB big.
It make sense to inline it. This should increase page loading speed.

## 🤔 Expected Behavior
The loader is inlined (not a separate .js file)

## 😯 Current Behavior
The loader is in a separate .js file.

## 🔦 Context
Having loader inlined should increase page loading speed.

**Comment by devongovett** [comment]
This is configurable. See here https://parceljs.org/features/production/#cascading-invalidation
