### ISSUE TITLE
Parcel cache not working under windows

### ISSUE THREAD

**Issue by ogsadmin** [parcel-bundler/parcel#9952]
# 🐛 bug report

A new install of parcel under windows 11 and trying to build the getting-started code failes with `[Error: Error opening directory]` (reported twice). Subsequent runs of `npx parcel src/index.html` fail with error message `[Error: Unable to open snapshot file: No such file or directory]`, so overall it is not possible to use parcel...

After adding the `--no-cache` flag everything works (workaround found [here](https://stackoverflow.com/questions/73186224/parcel-build-throws-the-error-error-error-opening-directory), so I think this is related to caching (maybe a windows only issue)). 

The project path does not contain spaces, the node.js version is the current v20.17.0 LTS version, npm is v10.8.2.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "name": "my-project",
  "source": "src/index.html",
  "scripts": {
    "start": "parcel",
    "build": "parcel build"
  },
  "devDependencies": {
    "parcel": "latest"
  }
}
```

The cli command to run the build I use is `npm run start`.

## 🤔 Expected Behavior

Well, not throwing an error and dropping back to command line, but continuing to build/serve.

## 😯 Current Behavior

The cli command to run the build is `npm run start`, which failes with:

``` cmd
❯ npm run start
> start
> parcel

Server running at http://localhost:1234
✨ Built in 653ms
[Error: Error opening directory]
[Error: Error opening directory]
❯ 
```

Subsequent runs of `npm run start` fail with:

``` cmd
❯ npm run start
> start
> parcel

[Error: Unable to open snapshot file: No such file or directory]
❯ 
```

## 💁 Possible Solution

The workaround is to add the `--no-cache` flag to all parcel commands (workaround found [here](https://stackoverflow.com/questions/73186224/parcel-build-throws-the-error-error-error-opening-directory), so I think this is related to caching (maybe a windows only issue)). 

A working package.json is:

```js
{
  "name": "my-project",
  "source": "src/index.html",
  "scripts": {
    "start": "parcel --no-cache",
    "build": "parcel build --no-cache"
  },
  "devDependencies": {
    "parcel": "latest"
  }
}
```

## 🔦 Context

I was trying to follow the "getting started" tutorial.

## 💻 Code Sample

Just follow the "getting started" under Windows 11.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  parcel@2.12.0 |
| Node             |  v20.17.0
| npm/Yarn         | 10.8.2
| Operating System | WIndows 11

**Comment by devongovett** [comment]
Are you missing permissions to create a `.parcel-cache` folder in your project?

**Comment by ogsadmin** [comment]
No, I have full control of the project folder, I can see the `.parcel-cache` folder getting created. Manually deleting the cache folder (running under the same user account) makes the next parcel run work (and the one after it fail again). This is even repeatable with creating a new project in a new folder.

As a side note: I also seem to have troubles with file watching - the watcher seems to crash now and then when I save changes (but this might be related to the VSCode settings - I've read the docs ;-)). So again maybe likely not a parcel issue, but a watcher issue...

**Comment by ogsadmin** [comment]
Sorry, I've tried again and was not able to reproduce anymore. I've started a new, clean project and everything works. Went back to the old project (where I had the problems) and also everything works there now. 

Sorry for the false report, obviously this was something related to my machine.

**Comment by joscha** [comment]
I encounter this when programmatically invoking parcel in a test environment, see: https://github.com/planet-a-ventures/parcel-optimizer-versioned-imports/actions/runs/11700263235/job/32583910351
