### ISSUE TITLE
@parcel/optimizer-swc: 'const' declarations must be initialized is utterly unhelpful

### ISSUE THREAD

**Issue by smileart** [parcel-bundler/parcel#9956]
# 🐛 bug report

Basically, when I'm tying to build the entire project, I get this error:

```shell
yarn parcel build src/index.html
```

<img width="638" alt="image" src="https://github.com/user-attachments/assets/6825915e-d9a0-46aa-afc3-a11cdf8204a6">

Which, as I understand it, comes from one of the dependencies (checked every single constant in my codebase, and everything is initialised, besides linter wouldn't allow it not to be), but with `optimizer-swc` error message pointing into nothing in bundle line number 45753, it's really hard even to identify the culprit, let alone resolve the issue. So, basically, the project builds are stuck.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  //  ...
  "type": "module",
  "scripts": {
    "dev": "parcel src/index.html",
    "build": "parcel build src/index.html",
  },
  "devDependencies": {
    "buffer": "^5.5.0||^6.0.0",
    "crypto-browserify": "^3.12.0",
    "daisyui": "^3.9.4",
    "events": "^3.1.0",
    "os-browserify": "^0.3.0",
    "parcel": "^2.12.0",
    "path-browserify": "^1.0.0",
    "postcss": "^8.4.31",
    "postcss-100vh-fix": "^1.0.2",
    "process": "^0.11.10",
    "standard": "^17.1.0",
    "stream-browserify": "^3.0.0",
    "tailwindcss": "^3.3.3",
    "vm-browserify": "^1.1.2"
  },
  "dependencies": {
    "@hookform/error-message": "^2.0.1",
    "@uidotdev/usehooks": "^2.4.1",
    "dotenv": "^16.3.1",
    "localforage": "^1.10.0",
    "match-sorter": "^6.3.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-error-boundary": "^4.0.13",
    "react-hook-form": "^7.47.0",
    "react-infinite-scroller": "^1.2.6",
    "react-router-dom": "^6.17.0",
    "sort-by": "^1.2.0"
  }
}
```

## 🤔 Expected Behaviour

Better error context to be able to identify the place where the constant is actually not initialised (to change the dependency or to write the author, etc.)

## 😯 Current Behaviour

The stack-trace/error-log pointing to an empty line in an enormous build file (don't even know the path to the file to somehow skim / debug it)

## 💁 Possible Solution

Installing SWC as a compiler and trying it with every JS/JSX file in the project (not in the dependencies) compiles without a problem. No idea how to improve, enlarge the context, not a Rust developer.

## 🔦 Context

Trying to build the front-end of my project, but stuck with this sudden issue and simply can't move forward.

## 💻 Code Sample

The project is relatively big, and the issue seems to be in the dependency rather than in the project itself.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.12.0
| Node             | 20.14.0 
| npm/Yarn         | 4.2.2
| Operating System | macOS Sonoma 14.6.1

UPD: By starting with routing and methodically commenting out chunks of the project, I managed to find the issue. I had a couple of constants destructured from an object, but since not every value was available on the right-hand side, the transpiled version resulted in something just a `const name;`. However, every time I commented out a chunk, the places pointed to in the transpiled giant file either had nothing to do with the error or, more often, pointed to an empty line in a 48,000-ish-line in the file. It was virtually impossible to figure out which of my constants had turned into one without a value.

**Comment by devongovett** [comment]
Seems like this is a problem with SWC, not parcel.
