### ISSUE TITLE
Browser scripts should allow typescript type imports

### ISSUE THREAD

**Issue by lovasoa** [parcel-bundler/parcel#9959]
Browser scripts cannot have imports or exports.
But type imports are only present at compile time, they do not prevent compiling to a browser script.
`@parcel/transformer-js` should not return an error when a browser script contains a type import like 

```ts
import type xxx from "xxx";
```

**Comment by devongovett** [comment]
Why can't you use `<script type="module">` which allows import syntax? I don't think this should be supported in classic scripts (they are parsed differently).

**Comment by lovasoa** [comment]
Browser scripts are still very common and useful. Is there any reason to prevent typescript type imports in them ?
