### ISSUE TITLE
🐛 Inline SVGs with <use> are replaced by undefined

### ISSUE THREAD

**Issue by bfred-it** [parcel-bundler/parcel#996]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

🐛Bug

If an inline SVG (in HTML) contains the `use` tag, the whole SVG will be replaced by the string `undefined`

### 🎛 Configuration (.babelrc, package.json, cli command)

No config

```html
❯ echo '<!DOCTYPE html><svg><use xlink:href="./file.svg"></svg>' > index.html

❯ parcel build index.html
✨  Built in 992ms.

dist/index.html    25 B    938ms

❯ cat dist/index.html
<!DOCTYPE html>undefined 
```

### 🤔 Expected Behavior

Output should be unchanged

### 😯 Current Behavior

Output is:

```html
<!DOCTYPE html>undefined 
```

Strange thing is that parcel doesn't check for the file at all during `parcel build` but will fail during `parcel watch`:

```
🚨  ..../index.html: Cannot resolve dependency './file.svg' at    at Resolver.resolve (/usr/local/lib/node_modules/parcel-bundler/src/Resolver.js:73:17)
```

### 🔦 Context

This: https://css-tricks.com/svg-use-external-source/

### 💻 Code Sample

```html
<!DOCTYPE html><svg><use xlink:href="./file.svg"></svg>
```

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.2
| Node             | 5.6.0
| npm/Yarn         | 5.7.1
| Operating System | macOS 10.13.3

**Comment by DeMoorJasper** [comment]
Related to https://github.com/svg/svgo/issues/921 ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bfred-it** [comment]
It doesn't look like it, that one drops `href`, this bug replaces the whole `<svg>` with `undefined`, regardless of other content

**Comment by DeMoorJasper** [comment]
Could u open up an issue in the htmlnano repo? As I don’t think this is a parcel bug

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bfred-it** [comment]
Indeed, as long as it's also tracked here

**Comment by maltsev** [comment]
[SVGO](https://github.com/svg/svgo) doesn't handle `xlink:href` attributes:
```
> node_modules/.bin/svgo -s '<svg><use xlink:href="./file.svg" /></svg>'
Error in parsing SVG: Unbound namespace prefix: "xlink"
```

So there is nothing I can fix in `htmlnano`, unfortunately. Though, I'd suggest replacing `xlink:href`, which is [deprecated](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href), with `href`.

**Comment by bfred-it** [comment]
Probably that error is due to the lack of the xlink namespace definition. I probably can’t use `href` without the namespace with the same browser compatibility. I’ll try.

**Comment by bfred-it** [comment]
> Probably that error is due to the lack of the xlink namespace definition

That was indeed the case:

```sh
❯ svgo --version
1.0.3

❯ svgo -s '<svg xmlns:xlink="http://www.w3.org/1999/xlink"><use xlink:href="./file.svg" /></svg>'
<svg xmlns:xlink="http://www.w3.org/1999/xlink"><use xlink:href="./file.svg"/></svg>
```

**Comment by bfred-it** [comment]
This still seems to be a bug in parcel@master, even if [htmlnano 0.1.7 fixed the output to `error`](https://github.com/posthtml/htmlnano/issues/47#issuecomment-372699634)

```sh
❯ npm i parcel-bundler/parcel

❯ echo '<!DOCTYPE html><svg><use xlink:href="./file.svg"></svg>' > index.html

❯ npm ls htmlnano svgo
/
└─┬ parcel-bundler@1.6.2 (github:parcel-bundler/parcel#c469751e145a426fee2f1de27ccb2a747c7f5d1e)
  ├─┬ cssnano@3.10.0
  │ └─┬ postcss-svgo@2.1.6
  │   └── svgo@0.7.2 
  └─┬ htmlnano@0.1.7 
    └── svgo@1.0.5  extraneous

❯ parcel build index.html
✨  Built in 68ms.

dist/index.html    25 B    4ms

❯ cat dist/index.html
<!DOCTYPE html>undefined
```

**Comment by bfred-it** [comment]
Neat. `--no-cache` shows the error. Without it it's `undefined`

```js
❯ npm i parcel-bundler

❯ ./node_modules/.bin/parcel --version
1.6.2

❯ ./node_modules/.bin/parcel build index.html
✨  Built in 58ms.

dist/index.html    180 B    3ms

❯ ./node_modules/.bin/parcel build index.html --no-cache
🚨  Error in parsing SVG: Unbound namespace prefix: "xlink"
Line: 0
Column: 79
```

**Comment by DeMoorJasper** [comment]
@bfred-it cache only keeps in mind the version of parcel, not the dependencies so it makes sense. Can we close this issue?

**Comment by bfred-it** [comment]
If using the cache has the bug I don't think the issue can be closed.

Can you try on your machine? These are the 5 commands to run

```sh
echo '<!DOCTYPE html><svg><use xlink:href="./file.svg"></svg>' > index.html
npm i parcel-bundler
./node_modules/.bin/parcel --version
./node_modules/.bin/parcel build index.html
./node_modules/.bin/parcel build index.html --no-cache
```

**Comment by bfred-it** [comment]
Ok I deleted `.cache` and now it fails even without `--no-cache`

I found another SVG bug related to htmlnano though

**Comment by hehe1111** [comment]
> [SVGO](https://github.com/svg/svgo) doesn't handle `xlink:href` attributes:
> 
> ```
> > node_modules/.bin/svgo -s '<svg><use xlink:href="./file.svg" /></svg>'
> Error in parsing SVG: Unbound namespace prefix: "xlink"
> ```
> So there is nothing I can fix in `htmlnano`, unfortunately. Though, I'd suggest replacing `xlink:href`, which is [deprecated](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href), with `href`.

Thanks, it works.
