### ISSUE TITLE
/*@__PURE__*/ comments are not removed in the final build

### ISSUE THREAD

**Issue by GeorchW** [parcel-bundler/parcel#9978]
# 🐛 bug report

I see `/* @__PURE__ */` comments that were generated somewhere in the build still present in the resulting output. This makes the bundle size bigger for no reason.

A very basic setup:

test.html:
```html
<!DOCTYPE html>
<html>
<head>
    <script src="test.js"></script>
</head>
</html>
```

test.js:
```js
console.log(100 + /*@__PURE__*/myPureFunction());
```

## 🎛 Configuration (.babelrc, package.json, cli command)

Vanilla Parcel 2.12.0:

```bash
mkdir repro; cd repro
yarn add parcel
```

## 🤔 Expected Behavior

The resulting `dist/test.[hash].js` file should not contain any comments.

## 😯 Current Behavior

The file keeps the `/*@__PURE__*/` comment.

## 💁 Possible Solution

A workaround is to add a `.terserrc` file with this content:

```json
{
    "format": {
        "comments": false
    }
}
```

But I wonder why that is not the default. 

I guess it's similar to https://github.com/parcel-bundler/parcel/issues/7563 or maybe even the same? Except that in my case, the comments weren't there at the start.

## 🔦 Context

If you replace the `+` with a `/`, then SWC removes the space between `/` and `/*`, which makes a line comment out of the block comment and results in invalid code. That's how I noticed -- builds resulted in broken code, since PURE-comments were generated and then combined into line comments.

I already filed that issue in SWC: https://github.com/swc-project/swc/issues/9630 

But I think it's a bit of a weird behavior to start with.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.12.0
| Node             | 20.18.0
| npm/Yarn         | yarn 1.22.19
| Operating System | Linux

**Comment by devongovett** [comment]
SWC would also be responsible for removing comments, so the issue isn't with Parcel.

**Comment by GeorchW** [comment]
> SWC would also be responsible for removing comments, so the issue isn't with Parcel.

SWC can do that, it just needs to be configured correctly. 
I'm sorry, the issue template makes this a bit verbose. The relevant bit is this:

> A workaround is to add a .terserrc file with this content:
> ```json
> {
>     "format": {
>         "comments": false
>     }
> }
> ```
> 
> But I wonder why that is not the default.
> 
> I guess it's similar to https://github.com/parcel-bundler/parcel/issues/7563 or maybe even the same? Except that in my case, the comments weren't there at the start.

So, SWC *can* absolutely remove those comments, but it's not configured to do so by Parcel right now. I think the expectation would be that a zero-config web-app bundler would remove all comments by default, even more so these auto-generated comments. 

So, my suggestion is to change the default setting for `format.comments` to `false`.
