### ISSUE TITLE
@parcel/resolver-default: Failure "Module '<dependency>' is not exported from the '<dependency>' package" when <dependecy>'s export is an object

### ISSUE THREAD

**Issue by david-nordvall** [parcel-bundler/parcel#9980]
# 🐛 bug report

Resolving exports in packages using objects in the `export`s property of their `package.json` fails. As an example, I have created a simple [Svelte](https://svelte.dev) web app and tried to import the package `svelte-french-toast` package. Bundling the simple web app fails.

The `svelte-french-toast` exports modules with the following declaration in its `package.json`:

```jsonc
{
  // Omitted for brevity.
  // .
  // .
  // .
  "type": "module",
  // Critically, the "exports" property is an object.
  "exports": {
     ".": {
       "types": "./dist/index.d.ts",
       "svelte": "./dist/index.js"
     }
   },
   "svelte": "./dist/index.js",
   "types": "./dist/index.d.ts",
  }
}
```

If I import any modules from the `svelte-french-toast` package from my web app,

```js
import toast, { Toaster } from "svelte-french-toast";
```
bundling fails.

Please note that the package `svelte-french-toast` is only used as an example. Bundling fails when importing modules from any package which exports its modules by using an object style `exports` property.

Importing modules from packages that export its modules using a string style `exports` property works without problem.

### My `package.json`
```jsonc
{
    "name": "parcel-resolver-exports-bug",
    "private": true,
    "license": "MIT",
    "devDependencies": {
        "@picocss/pico": "2.0.6",
        "parcel": "2.12.0",
        "parcel-transformer-svelte3-plus": "0.2.10",
        "svelte": "4.2.19",
        "svelte-french-toast": "1.2.0"
    },
    "scripts": {
        "serve": "npx parcel index.html",
        "build": "npx parcel build index.html"
    },
    // Note that I have enabled packageExports!
    "@parcel/resolver-default": {
        "packageExports": true
    }
}
```
### My `.parcelrc`
```json
{
    "extends": "@parcel/config-default",
    "transformers": {
        "*.svelte": [
            "parcel-transformer-svelte3-plus"
        ]
    }
}
```

## 🤔 Expected Behavior

I expected Parcel's resolver to resolve the imported modules and for the bundling to succeed.

## 😯 Current Behavior

Bundling fails, 
```sh
$ yarn build
yarn run v1.22.22
$ npx parcel build index.html
⠦ Building App.svelte...
🚨 Build failed.

@parcel/core: Failed to resolve 'svelte-french-toast' from './App.svelte'

  /workspaces/parcel-resolver-exports-bug/App.svelte:4:36
    3 | 
  > 4 |     import toast, { Toaster } from "svelte-french-toast";
  >   |                                    ^^^^^^^^^^^^^^^^^^^^^
    5 | </script>
    6 | 

@parcel/resolver-default: Module 'svelte-french-toast' is not exported from the 'svelte-french-toast' package

  /workspaces/parcel-resolver-exports-bug/node_modules/svelte-french-toast/package.json:18:14
    17 |   "type": "module",
  > 18 |   "exports": {
  >    |              ^
  > 19 |     ".": {
  >    | ^^^^^^^^^^
  > 20 |       "types": "./dist/index.d.ts",
  >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  > 21 |       "svelte": "./dist/index.js"
  >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  > 22 |     }
  >    | ^^^^^
  > 23 |   },
  >    | ^^^
    24 |   "svelte": "./dist/index.js",
    25 |   "types": "./dist/index.d.ts",

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## 💻 Code Sample

See repository https://github.com/david-nordvall/parcel-resolver-exports-bug for a reproduction of the error.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.12.0
| Node             | 22.9.0
| npm/Yarn         | Yarn 1.22.22
| Operating System | Debian 12 (Bookworm) on WSL2

**Comment by david-nordvall** [comment]
Ok, so turns out I hadn't read the documentation properly. According to the [Conditional exports](https://parceljs.org/features/dependency-resolution/#conditional-exports) section of the Dependency resolution documentation, `"svelte"` is not a supported conditional exports expression.

I will close this issue and re-open a feature request (for adding support for the `"svelte"` conditional exports expression) instead.

For anyone looking for a workaround, you can add an `"alias"` entry for any dependencies that fail because they are using the `"svelte"` (or any other unsupported) conditional exports expression in your `package.json`. In my code sample (linked above), where the package `svelte-french-toast` was used as an example, I can work around the error by adding the following snippet:

```jsonc
"alias": {
  // Exacty what your alias should look like depends on you dependency. Normally, you should
  // be able to simple use the file exported with the "svelte" conditional export expression (and
  // prefix the path with the path to you node_modules).
  "svelte-french-toast": "./node_modules/svelte-french-toast/dist/index.js" 
}
```

**Comment by JoacoEsteban** [comment]
Hey, did you manage to open the feature request? I'm stuck with the same issue and the same package. Aliasing did the job for `svelte-french-toast` but they didn't do it for other packages, eg: `@threlte/extras`.
