### ISSUE TITLE
css keyframes are missing after building

### ISSUE THREAD

**Issue by b862** [parcel-bundler/parcel#999]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

```js
parcel build index.html -d build  --public-url ./
```

### 🤔 Expected Behavior
No bug occurred

### 😯 Current Behavior
My page cannot show loading animation

### 💁 Possible Solution
set option below:
https://github.com/ben-eb/cssnano/issues/351#issuecomment-277406846

### 🔦 Context
After finishing building my project, I found that all of the loading animations cannot show, then I tried to check @keyframes in my stylesheet but found nothing. But it surely exists in my source code.

### 💻 Code Sample
`import './assets/semantic/dist/semantic.css'`

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |1.5.1
| Node             |9.6.0
| npm/Yarn         |5.6.0
| Operating System |windows 10

**Comment by cxreiff** [comment]
This is happening to me as well. It seems that the minifier is removing @keyframes definitions in production builds even if they are being used.
