### ISSUE TITLE
Parcel build fails with no error

### ISSUE THREAD

**Issue by LukeTOBrien** [parcel-bundler/parcel#9996]
# 🐛 bug report

Parcel build is failing with no errors, if you look at the screenshot below you can see that the last stage the build process got to was `Building runtime-b26d016a60e99e5f.js...`.  

When I add `--log-level verbose`, then I can see tree-shaking warnings but no error.  
The warnings point to the [docs](https://parceljs.org/features/scope-hoisting/#commonjs) which mention 'bail outs' but I don't think this is the kind of bail out the docs are talking about.

![image](https://github.com/user-attachments/assets/0cc8511c-510b-4b94-bb1b-a65968009525)

Does anyone know what could be causing this issue?

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```js
{
   ...
"targets": {
        "default": {
            "distDir": "./dist",
            "sourceMap": false,
            "context": "browser",
            "outputFormat": "global"
        }
    }
...
}
```

tsconfig
```js
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": false,
        "removeComments": true,
        "preserveConstEnums": true,
        "sourceMap": true,
        "esModuleInterop": true,
        "target": "ES2020",
        "experimentalDecorators": true,
        "useDefineForClassFields": false
    }
}
```

.parcelrc
```js
{
  "extends": "@parcel/config-default",
  "transformers": {
    "*.{ts,tsx}": ["@parcel/transformer-typescript-tsc"]
  }
}
```

.terserrc
```js
{
    "compress": {
        "hoist_props": false
    },
    "mangle" : {
        "reserved" : [ "$", "L" ],
        "keep_fnames": true
    },
    "format": {
        "ascii_only": true
    }
}
```

## 🤔 Expected Behavior

Just work.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  "^2.12.0"
| Node             | 22.8.0
| npm/Yarn         | npm@10.8.2 
| Operating System | Windows 11
| TypeScript |  "^5.6.2"

**Comment by PenghaiZhang** [comment]
Hi @LukeTOBrien may I ask how you fixed this issue ?
